### ISSUE TITLE
TraCI-Removed vehicle causing Error

### ISSUE THREAD

**Issue by Domsall** [eclipse/sumo#10008]
I am running a TraCI-controlled SUMO instance. After removing a vehicle via TraCI und running simulationStep(), I am getting the assertion-error `assert(myFurtherLanes.size() > 0)` in `MSVehicle::getBackPositionOnLane`.

I am using LC2013 with continuous lane changes (duration=4.0).
Running SUMO in the Debug-Mode, I found out that the removed vehicle is still in `myPartialVehicles`.
When updating the lane via `MSLane::planMovements(SUMOTime t)`, the follower vehicle wants to get leader info via `updateLeaderInfo`.
In `updateLeaderInfo`, `getPositionOnLane` of this (removed) leader vehicle gets called. The assertion-error then is called, because `myFurtherLanes` has been cleared by removing the vehicle (but `myPartialVehicles` has not been, as is seems).

Do you need to reproduce the error on your side to find the issue? Do you need all configuration/additional files for this? I am using a configuration with 2 SUMO instances running in parallel with a lot of routes/additional files.

**SUMO-version:** "FKFS"-Development Version SUMO 1.10

**operating system:** Windows

**Comment by namdre** [comment]
I'd take any help I can get with producing a small test case. Maybe you can filter out the critical sequence of commands from a traceFile (https://sumo.dlr.de/docs/TraCI/Interfacing_TraCI_from_Python.html#generating_a_log_of_all_traci_commands)?

**Comment by Domsall** [comment]
I did not do extra debugging to find out if this is my actual issue,
but the following test case that looks like my problem is failing :)

[RemoveVehicle_whenLaneChangingError.zip](https://github.com/eclipse/sumo/files/7909005/RemoveVehicle_whenLaneChangingError.zip)

**Comment by Domsall** [comment]
Seems to arise from a previous SUMO version or by custom changes. The test works with the newest version. Sorry for bothering
