### ISSUE TITLE
Vehicles cannot enter the parking lot

### ISSUE THREAD

**Issue by Virli13** [eclipse/sumo#10002]
Hi, I am trying to assign parking for the vehicle, but there is a problem during operation as shown in the video.  I don't know how to deal with this bug. Is there any solution to this issue? I sincerely look forward to your reply.

https://user-images.githubusercontent.com/81471957/150288132-d4a826ac-f1c0-400e-9299-67b447e3291a.mp4

**Comment by namdre** [comment]
your video does not work. Also, please see https://sumo.dlr.de/docs/FAQ.html#what_should_i_do_to_get_helpful_answers_on_the_mailing_list_or_on_the_issue_tracker !

**Comment by Virli13** [comment]
![image](https://user-images.githubusercontent.com/81471957/150316190-7e7ad124-832b-4856-a6ab-1bee9e8e9d3a.png)
![image](https://user-images.githubusercontent.com/81471957/150316340-a64b7055-1210-48e2-a27c-b3ec232ba755.png)
Sorry, there seems to be something wrong with the video. Here are two screenshots from the video. The problem I have is that the color of the parking lot does not change after the car enters the parking lot.  And the subsequent vehicles can not enter the parking lot.  I tried many things, but I couldn't solve the problem.  I sincerely hope you can provide some guidance.

**Comment by namdre** [comment]
The problem you observe has been fixed via #10005 (you can obtain an updated development version tomorrow or wait for new release next week).

However, onRoad parking can also suffer from #10007 which isn't fixed yet.

**Comment by Virli13** [comment]
Thanks for your help.

> The problem you observe has been fixed via #10005 (you can obtain an updated development version tomorrow or wait for new release next week).
> 
> However, onRoad parking can also suffer from #10007 which isn't fixed yet.

**Comment by behrisch** [comment]
Keep commenting if you have more remarks
