### ISSUE TITLE
NEMA shouldn't default to minRecall on all phases 

### ISSUE THREAD

**Issue by mschrader15** [eclipse/sumo#10009]
@qichaow I don't think that NEMA should default to having a minRecall on each phase.

For example, I am trying to test coordinated mode against a SIL controller with maxRecall on 2 & 6. If I pass just `<param key="maxRecall" value="2,6"/>`, the code will automatically place minRecalls on all phases. This does not permit phase skipping.

https://github.com/eclipse/sumo/blob/f6ce91af43340b431c57b32459aada6f5f5a897d/src/microsim/traffic_lights/NEMAController.cpp#L75

**Comment by qichaow** [comment]
Default to all phase minimum recall will not change the results of the
previous test file. If you want to skip phases, just set minRecall to the
phase that you want minRecall or empty (“”). I think it’s a personal
preference that I don’t know what the best default value has to be.

Qichao

**Comment by mschrader15** [comment]
@qichaow defaulting to have minRecall on all phases will change the behavior. The nextPhase algorithm checks to see if a detector **or** a recall is active for the phase.

https://github.com/eclipse/sumo/blob/f6ce91af43340b431c57b32459aada6f5f5a897d/src/microsim/traffic_lights/NEMAController.cpp#L1050

 If "Free" of "Fully Actuated" mode is desired in conjunction with a maxRecall, the user will have to know to add `<param key="minRecall" value="0"/>`

**Comment by qichaow** [comment]
MaxRecall won’t give you free mode. The previous code before min/max recall
features is basically acting as min recall on all phases. Changing
minRecall default now will make the previous scenarios from test files
behave differently. I don’t have a strong preference on what the default
should be. Just feel with default to all phases minRecall won’t change the
behavior if someone already have SUMO files with the previous code.

**Comment by mschrader15** [comment]
You are right @qichaow . I will close this!
