### ISSUE TITLE
NEMA should support NEMA TS1 and NEMA TS2 offsets as well as Type 170

### ISSUE THREAD

**Issue by mschrader15** [eclipse/sumo#10013]
@qichaow I noticed that your implementation of the offset is Type 170 (according to [Chapter 6.3.4](https://ops.fhwa.dot.gov/publications/fhwahop08024/chapter6.htm). 

We use TS2 controllers here and I am seeing some differences in testing that I think will be hard to resolve without explicitly supporting TS2.

**Comment by mschrader15** [comment]
I will take the lead on this @qichaow , just wanted to make note of it here

**Comment by qichaow** [comment]
Sure, go ahead.

Qichao

**Comment by qichaow** [comment]
Hi Max,

Just want to let you know that TS1/2 is a cabinet standard, not a
controller type.

Thanks,
Qichao

**Comment by mschrader15** [comment]
@qichaow that it is (and sorry if my language has been unclear), but it also determines how the offset is calculated no? See [Chapter 6.3.4 here](https://ops.fhwa.dot.gov/publications/fhwahop08024/chapter6.htm) for FHWA description of the offset calculation and how it relates to TS1/2 and Type 170

**Comment by mschrader15** [comment]
FYI the option I added as `cabinetType` and documented it https://sumo.dlr.de/docs/Simulation/NEMA.html#param_attributes
