### ISSUE TITLE
"The route cannot be build" error

### ISSUE THREAD

**Issue by rjmaris** [eclipse/sumo#10024]
I have been using the OSMWebWizard for the first time, and the result is amazing!
However, when I start to clean the net, i.e. get rid of really unimportant net elements in order to be able to focus on the core of a selected (wizard) rectangle, a serious unexpected problem arises:

The simulation starts with:

> Error: The edge '-23383617' within the route for trip 'veh30' is not known.
>  The route can not be build.

From https://github.com/eclipse/sumo/issues/5832 I know that --ignore-route-errors does not work when the start or endedge are not known. BTW: The config file already sets this option to true.

Initially, I went on to manually remove trip entries in the four trip files that were generated from the wizard.
But this is very tedious, also because only one (the first encountered) error is shown in the output window.
The net editor seems not to offer a capability to address this using one of the processing tools under the superfunction demand.

  
---
*If possible, upload an example that shows your problem.* I could upload it (appox. 3 MB) if desired.

**SUMO-version:** 1.11.0

**operating system:** Linux (ubuntu repo based flavor)

**Comment by namdre** [comment]
You can regenerated the traffic so that it fits your modified net by running the batch file **'build.bat'** in the scenario folder.

Netedit filters trips automatically if you load the traffic before editing the net. You can also load the traffic into your modified net and netedit will filter it out then as well.

Lastly, duarouter with option **--repair --ignore-errors --write-trips** could also filter trips automatically.

**Comment by rjmaris** [comment]
Many thanks. Regarding build.bat: In parallel to my posting I also imagined that the Wizard process runs for the most of the effort locally after the map has been extracted from openstreetmap.

**Comment by namdre** [comment]
You are correct. After downloading the map everything runs locally and is reproducible with configs and scripts.

**Comment by MoiGabriel** [comment]
I have been using the OSMWebWizard for generating my map.
After I made a custom junction I have an error:
Error: The edge '685985556' within the route for trip 'veh59' is not known.
The route can not be build.
I tried to run build.bat but is not working. I cannot figure out what is the problem. Can someone help me, please

**Comment by namdre** [comment]
@MoiGabriel  Make sure to close all instances of sumo-gui before running build.bat. Otherwise, the sumo-gui process prevents updating of the files.

**Comment by MoiGabriel** [comment]
I did it, I moved it from the first location, should I edit something in the bat? It's not even opening. I tried to run it as administrator, I have it on Desktop.

**Comment by MoiGabriel** [comment]
The problem was the Path of Python ig. I fixed it after installing Python again and added it to the Environment Variables.

**Comment by Fakryt** [comment]
@MoiGabriel Hi. Can u explain more carefully that how u repaired this error?

**Comment by MoiGabriel** [comment]
Hello, @Fakryt! To be honest I don't remember the error. My last comment suggests to reinstall Python and after go to Settings - Edit the system environment variables - Environments variables  and add the path for Python.
