### ISSUE TITLE
How to increase the length of induction loop detector?

### ISSUE THREAD

**Issue by rahulbhadani** [eclipse/sumo#10023]
I am defining the properties of an Induction loop. I looked at https://sumo.dlr.de/docs/Simulation/Output/Induction_Loops_Detectors_%28E1%29.html and I didn't find any ways to increase the length of the induction loop.  I tried two properties: size and length but they don't seem to affect the length of the induction loop. What can I do to increase the length of the induction loop? 

Following is a snapshot of my current scenario:
![image](https://user-images.githubusercontent.com/8680176/150701009-7802031a-5fb5-4a8b-aed1-36e3f625dfc9.png)
I would like longer detectors.
  
---

**SUMO-version:** Eclipse SUMO sumo Version v1_8_0+1437-c7ee52dce9

**operating system:** Ubuntu 20.04 LTS

**Comment by namdre** [comment]
The length of the inductionLoop detector cannot be increased. If you need to detect vehicles on a larger area in SUMO, you can use a laneAreaDetector: https://sumo.dlr.de/docs/Simulation/Output/Lanearea_Detectors_%28E2%29.html

**Comment by rahulbhadani** [comment]
Thank you.
