### ISSUE TITLE
Is there a way to disable re-routing?

### ISSUE THREAD

**Issue by Oritchimaru** [eclipse/sumo#10040]
_I need the vehicles to follow the same route of consecutive lanes every time I run the program_ but they seem to change lanes. Is there an option that can be added to **sumocfg.xml** or something? I think I was able to achieve than in the past but I don't remember what I changed... or maybe the vehicle device (although I'm not experienced with modifying these).

[EDIT1]

I correct my self, I meant changing lanes. I now try this command and run it for every vehicle I add to the network. 
`				traci.vehicle.setLaneChangeMode(veh_id, 0b000000000000)
`
As long as, I want to have full control over the speed and behaviour of the cars I think this is alright but I'm not entirely sure.

Thanks!

**Comment by namdre** [comment]
You can disable individual lane change motivations with vType attributes in xml input (i.e. `lcSpeedGain="0"` to disable changing for speed gain). Likewise, setLaneChangeMode can control motivations for strategic, cooperative, ... changing).

Another way to set a fixed sequence of lanes is by setting waypoints: https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#waypoints
