### ISSUE TITLE
create page for "change inductionloop state"

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#10064]
see #10048

(also, parameters can be set on inductionloops via traci)

**Comment by yunpangfloetteroed** [comment]
Just let me know if I should add something more!

**Comment by yunpangfloetteroed** [comment]
will add the content

**Comment by yunpangfloetteroed** [comment]
please give a look if the codes are correct!

**Comment by namdre** [comment]
0x22 is correct. However, the command isn't a compound command but rather a "simple" command because it only sends a single double as additional parameter. The object id is always sent it doesn't count as as a component entry.
For another example, see `vehicle.setSpeed` which is simple as well.

**Comment by yunpangfloetteroed** [comment]
The corresponding change has been made. I close therefore this ticket.
