### ISSUE TITLE
Simulation run/stop toggle via space bar

### ISSUE THREAD

**Issue by rjmaris** [eclipse/sumo#10068]
As an aid in quick stop and restart of a running simulation, the space bar could serve good value when a quick pause is requesten upon viewing a specific behaviour.
  
---
*If possible, upload an example that shows your problem.*

**SUMO-version:** 1.12

**operating system:** Linux Mint 20.4

**Comment by namdre** [comment]
The hotkeys ctrl+a, ctrl+s, ctrl+d are available for this. See the 'Simulation' Menu for reference.
Also, breakpoints can be useful for stopping the simulation at a time of interest: https://sumo.dlr.de/docs/sumo-gui.html#breakpoints

**Comment by rjmaris** [comment]
I know about these hotkeys. It's just from my experience with e.g. electronic measuring/capture systems that it's very handy to suddenly be able to hit the space key if you see an event where you want to freeze.
Just try to do that with CTRL-S. You'd need to keep two finger at a resting position onto those keys. The space key can be hit in a sorf of Miss Piggy manner. Clash!

**Comment by namdre** [comment]
I see your point and will consider adding the space key.
Far more often than start/stop I'm using breakpoints since there are long stretches of "boring" simulation vs short interesting parts where I need to rewind and step through them.

**Comment by rjmaris** [comment]
The breakpoint concept is familiar, however in a code debug environment. In the SUMO case, I just discovered why I found some breakpoints in the table. The reason (from the doc): "by clicking on an underlined time value in the message/warning log area ..."
Since only two input fields are present in the sumo-gui that only accepts numbers & dec. point, plain alpha keybindings should be available for handy&quick control of the simulation. E.g. single step via the 's' key, besides CTRL-d.

_BTW: I had to tag this issue as "feature request" or the like._

**Comment by namdre** [comment]
Your suggestion received overwhelming support

**Comment by rjmaris** [comment]
Well, one could also add other key bindings... e.g.
- B for set beakpoint
- R for reverse single step (if possible), or the A-key because it is just on the left side of the S (step forward) key.
- L for set loop start (could be used together with a breakpoint e.g. 30 seconds in future)
- Ctrl-L for resume from loop start point

**Comment by rjmaris** [comment]
If all those changes would be implemented, almost full keyboard control is possible. That permits it to add full screen mode as well (F11). This is especially helpful since the graphics does not support anti-aliasing (as far as I know, OSes only control aliasing properties of text). For this reason zooming in is required more often in order so see details better.

**Comment by namdre** [comment]
regarding your other suggestsions
- B for adding a breakpoint is a good idea
- reversing is not possible at the moment. 
- looping might be made possible via #10198
- PgUp and PgDown are currently used for scrolling but they would indeed be more useful for delay control
- I'm not convinced about the usefulness for a scale-hotkey
- full-screen mode is available via Ctrl+f   (though there are some issues with returning from full-screen on linux

**Comment by rjmaris** [comment]
Am 22.02.2022, 09:46 Uhr, schrieb Jakob Erdmann ***@***.***>:

>
> regarding your other suggestsions
> B for adding a breakpoint is a good idea
> reversing is not possible at the moment.
I can imagine that it's difficult to rewind a collision, just as is also the case for the real world. I'd believe that rewinding is possible only when the exact full state of each of (e.g.) the last 20 simulation steps be stored in a ringbuffer, so that one could step back up to 20 steps.
It's the question whether saving the whole state takes too much time. But that's hardly believable when I consider the mass movements performed onto the display. And a ring buffer with pointers is an efficient concept.
>
> looping might be made possible via #10198
The string buffer (as a solution option) requirement is already mentioned by you.

>
> PgUp and PgDown are currently used for scrolling but they would indeed be more useful for delay control
> I'm not convinced about the usefulness for a scale-hotkey
Right, this is merely the mentioning of an idea. I'm aware of it that this parameter would usually stay unchangned during a simulation.

>
> full-screen mode is available via Ctrl+f (though there are some issues with returning from full-screen on linux
Not only linux, but especially when you're working with two screens. The program understands full screen as spawning over both screens (which is not intended when these are different pixel geometry). Usually full screen options spawn to full of the screen where the window lives. I.e.: "kiosk" mode.

**Comment by namdre** [comment]
Space should be working now, For the breakpoint hotkey, see #10400
