### ISSUE TITLE
support fake detector calls from context menu

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#10067]
see #10045 #10048 and #1951

- [x] inductionLoop
- [x]  laneAreaDetetector
- [x] highlight detector in special color to indicate override

...

- [ ] add hotkeys so we can use this to play DOOM via #10049 :grin:

**Comment by namdre** [comment]
@mschrader15  as soon as you finish #10045 I'll hook it up to the gui for quick visual debugging.

**Comment by mschrader15** [comment]
Sounds good!
