### ISSUE TITLE
Phase Tracker Vector index out of bounds

### ISSUE THREAD

**Issue by mschrader15** [eclipse/sumo#10069]
@namdre just ran across this in testing:

 `i` reaches `0` before `lookBack` meaning that the next iteration causes `i = -1`. I'm not sure if this is a simple as ` while (lookBack > 0 && i > 0) { `  or if is indicative of a larger problem. 

https://github.com/eclipse/sumo/blob/5f88272382984b01cc5ca9498856e699d063e000/src/gui/GUITLLogicPhasesTrackerWindow.cpp#L887-L889

**Comment by namdre** [comment]
I see the problem with the code but have trouble finding a test case for reproducing this. Can you attach something?

**Comment by mschrader15** [comment]
Yep, see attached. It happens on the left-most intersection, `63082002`

[PhaseTrackerIssues.zip](https://github.com/eclipse/sumo/files/7964335/PhaseTrackerIssues.zip)
