### ISSUE TITLE
retrieve lanes and positions of multientryexit

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#10083]
maybe something like
- getDetEntryLanes  (reuse VAR_LANES)
- getDetExitLanes   (0x31 VAR_EXIT_LANES)
- getDetEntryPositions (reuse VAR_POSITION
- getDetExitPositions (0x43 VAR_EXIT_POSITIONS)

**Comment by schwamborn** [comment]
Can't seem to find TraCI constants to reuse for these variable types. Do we want to allocate 4 new constants, although we're running short on unused byte values?
