### ISSUE TITLE
draw optional tooltip below mode-buttons on mouseover

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#10085]

**Comment by angelobanse** [comment]
this could be done with all buttons - for consistency and because it would be easier to read text in the new Tooltip than in the Status Line below

**Comment by rjmaris** [comment]
I was missing tooltips as well. Later on I saw that such "tooltips" are already provided: Shown in the status bar at the bottom. Just as it was usual habit in former times ;-).
