### ISSUE TITLE
NEMA initial phase isn't reflected in SUMO 

### ISSUE THREAD

**Issue by mschrader15** [eclipse/sumo#10081]
The phase tracker and tls state output show the following light as being in 2+6 (mainline all green). This is not reflected in the GUI nor in the vehicles behavior. 

If I switch it to the default TLS program and then back to NEMA via the GUI the state updates correctly. 

![image](https://user-images.githubusercontent.com/57813331/151815140-ec78024e-5a97-4a35-964b-456ca357455c.png)

**Comment by namdre** [comment]
How about the tlsState output, does it always show the expected values? (https://sumo.dlr.de/docs/Simulation/Output/Traffic_Lights.html#tls_states)

**Comment by mschrader15** [comment]
Yea this behavior is actually reflected in the tests as well. Not sure how this slipped through the cracks. 

Below is an image from https://github.com/eclipse/sumo/tree/main/tests/sumo/basic/tls/NEMA/basic

![image](https://user-images.githubusercontent.com/57813331/151823288-126db525-d00b-4c23-87a3-61769a4958c8.png)

Both https://github.com/eclipse/sumo/blob/main/tests/sumo/basic/tls/NEMA/basic/tls_state.sumo and https://github.com/eclipse/sumo/blob/main/tests/sumo/basic/tls/NEMA/basic/tls_state_switch.sumo reflect the state as being 4+4 green

**Comment by namdre** [comment]
@mschrader15  Can you take a stab at debugging this?

**Comment by mschrader15** [comment]
Will do!

**Comment by namdre** [comment]
:+1:
