### ISSUE TITLE
polyconvert failed

### ISSUE THREAD

**Issue by lubaso** [eclipse/sumo#10094]
I tried to import geometrical shapes from an osm file, but polyconvert fails. I get the following message n times:
Error: Could not build poly with ID '1' in netedit; declared twice.
...
Error: Could not build poly with ID 'n' in netedit; declared twice.
Error: Loading of <file> failed.
---

**SUMO-version: Eclipse SUMO sumo Version 1.10.0**

**operating system: macOS Big Sur Version 11.6**

**Comment by namdre** [comment]
looks like you tried to load the same file twice

**Comment by lubaso** [comment]
I am not sure if that is the case. I used the following command:
`polyconvert --osm-files mynet.osm -o polygons.poly.xml`

After that, I press `Open Network` and load the osm file `mynet.osm`. Also, I hit  `Addtionals and Shapes` -> `Load Additionals` and chose the polygons.poly.xml as additional.

**Comment by namdre** [comment]
According to your polyconvert call,  `mynet.osm` is an osm data file. 
You should first use `netconvert --osm-files mynet.osm -o mysumo.net.net.xml` to convert it into a sumo network.  
Then you can load the `.net.xml` file and the polygons with netedit.
Please refer to the documentation on useful / recommend options for OSM impor: https://sumo.dlr.de/docs/Networks/Import/OpenStreetMap.html

**Comment by lubaso** [comment]
That is what I have done:

**Comment by namdre** [comment]
could this be what happend: ?
1. you loaded the polygons and nothing happend
2. you tried to load them again and got the errors

The reason for (1) is #10101 
The suggested fix is to download the latest development version and try again: https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_development_version



please try with the latest dev version (https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_development_version)
If
