### ISSUE TITLE
Can routesampler.py take a road network as input?

### ISSUE THREAD

**Issue by parksanha** [eclipse/sumo#10095]
May I ask you one thing?
Can routesampler.py take a road network as input?

In the link below
It seems that routessampler.py gets the road network with -n net.net.xml.

https://sumo.dlr.de/docs/Tools/Turns.html#multiple_vehicle_types

**Comment by namdre** [comment]
fixed via 0cfceb9ea4d0d11c34ae2408573b260bfe578dbc

**Comment by parksanha** [comment]
@namdre Oh, thank you.
