### ISSUE TITLE
response for TraCI context subscription contains invalid command length

### ISSUE THREAD

**Issue by kschrab** [eclipse/sumo#10108]
When adding a context subscription via TraCI for a vehicle (`0x84`) to retrieve surrounding vehicles (`0xa4`) , the response message contains an invalid command length. 

Command:
`00 00 00 2a 26 84 40 1c 00 00 00 00 00 00 40 8f 40 00 00 00 00 00 00 00 00 05 76 65 68 5f 31 a4 40 69 00 00 00 00 00 00 01 40`

Response
`00 00 00 20 07 84 00 00 00 00 00 00 00 00 00 14 94 00 00 00 05 76 65 68 5f 31 a4 01 00 00 00 00`

Expected Response:

`00 00 00 19 07 84 00 00 00 00 00 11 94 00 00 00 05 76 65 68 5f 31 a4 01 00 00 00 00`

Detailed description found in the following images. The command length in the actual response (2nd picture) starts with a byte value of `0`, implying an extended `length` field. the subsequent integer then contains a value  of `20`. However, the actual length of the whole command, including the `length` field of 5 bytes, is 21 bytes long in total. Therefore, I would expect that `21` would be the actual content of the `length` field.

![image](https://user-images.githubusercontent.com/2386865/152806303-85a7ced8-e6d3-4f78-b98c-d2ad051c4c22.png)

![image](https://user-images.githubusercontent.com/2386865/152789323-05444b06-4f07-4bd6-b9cd-7f60af45f5a8.png)

The **expected** response would use the normal length field using one byte only, as the command length is shorter than 255 bytes: 

![image](https://user-images.githubusercontent.com/2386865/152806319-087842d8-a10a-4bc7-a996-02e608372f08.png)

**SUMO-version:** 1.12.0

**operating system:** Windows 10

**Comment by behrisch** [comment]
It does not affect the python client which simply ignores the length of the return string but it is definitely a bug. Thanks for tracking this one down!

**Comment by behrisch** [comment]
Just for the record: None of our clients checks the length of the (inner) return message and consequently none of our clients will be able to handle multiple messages in one batch although the TraCI protocol allows it.

**Comment by kschrab** [comment]
Something still seems to be wrong:

I now get an invalid response when sending a normal vehicle subscription (`0xd4`):

Receiving a response with a length of 156 bytes:
`00 00 00 9c 07 d4 00 00 00 00 00 95 e4 ...`

with 
`00 00 00 9c` = 156 bytes length 
`07`
`d4` -> vehicle subscription
`00 00 00 00 00` -> status code = "ok"
`95` = 149 bytes command length (! this is wrong, should be 145!)

I proposed a solution in https://github.com/eclipse/sumo/commit/78d59ddb46672e942517d88d99a0ce18dd343310#r66731320

**Comment by behrisch** [comment]
You are right. But I think it may be better to revert to always sending the extended length. This way all clients relying on the old behavior (e.g. Traas) will still work. What do you think?

**Comment by kschrab** [comment]
Sure, I see no problem there.
