### ISSUE TITLE
Need for Big Artificial Scenarios

### ISSUE THREAD

**Issue by Oritchimaru** [eclipse/sumo#10102]
Can I find anywhere big scale "Artificial" Scenarios, let's say with 50-200 edges.

I'm testing various RL algorithms in order to train agents optimal driving policies and till now I was working with imported networks with OSMWizard but it seems that some minor details like really small junctions that don't provide something or really small edges etc. produce problems.

This is why I'm in search for big artificial scenarios that will not have such imperfections. If there are not then I should proceed to make some myself.

**Comment by namdre** [comment]
I recommend a combination of 
https://sumo.dlr.de/docs/Networks/Abstract_Network_Generation.html
and
https://sumo.dlr.de/docs/Tools/Trip.html#randomtripspy

**Comment by Oritchimaru** [comment]
@namdre Thanks alot, that seems to work for me! Just one question now that I'm generating some networks, is there a way to make edges with more than 1 lane with this random process?

**Comment by namdre** [comment]
**--default.lanenumber**

**Comment by namdre** [comment]
also: https://sumo.dlr.de/docs/Networks/Abstract_Network_Generation.html#further_options

**Comment by Oritchimaru** [comment]
@namdre Thanks alot, that did a great work for me, I'm using now these settings and it works fine, also the names convention used it just how I wanted.

<random_network>
        <rand value="true"/>
        <rand.iterations value="10"/>
        <rand.max-distance value="350"/>
        <rand.min-distance value="50"/>
    </random_network>

    <output>
        <output-file value="test.net.xml"/>
    </output>

    <building_defaults>
        <default.lanenumber value="2"/>
    </building_defaults>

I wish there was a way to randomize the amount of lanes an edge has (let's say for example [1,3] but I guess that's pretty much impossible by your side because it iteratively adds these networks to the existing with rand.iterations.

**Comment by namdre** [comment]
**--rand.random-lanenumber**

**Comment by Oritchimaru** [comment]
@namdre  **WOW!** Seem I missed it when read the documentation! That's a really big deal for me, I can't thank you enough... also sorry for the inconvenience with that many questions over these last months. Cheers!
