### ISSUE TITLE
create osmGet / webWizard tests that downloads OSM Data

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#10116]
best to load from our own osm server rather than risk being ip-blocked

reason: we don't have this yet and things might brake during refactoring

**Comment by behrisch** [comment]
but how can we keep this stable if the input changes all the time and how do we detect errors the people encounter if we don't use the public instance?

**Comment by namdre** [comment]
Our private instance gets updated occasionally (I think) so we will get more errors from that
With lots of filtering, we should be able to check what we really need: A scenario is created and runs to completion.
We might even randomize the coordinates to get more coverage.

**Comment by behrisch** [comment]
first we need to check whether the local OSM instance is still active

**Comment by namdre** [comment]
is this downloading data from the public servers with each test?

**Comment by behrisch** [comment]
yes but it is in the perf tests so it is only triggered by the nightly build on our servers
