### ISSUE TITLE
[Warning: Ignoring program 'online'...] with traci saveState&loadState

### ISSUE THREAD

**Issue by sky4994** [eclipse/sumo#10124]
Hello

First of all I am using sumo 1.11 version.

And I am using the saveState and loadState functions in traci.

However, the following warning message occurs:
[Warning: Ignoring program 'online' for traffic light 'TL_ID' in loaded state]

I need information about this warning message and help on how to get a normal simulation.

![image](https://user-images.githubusercontent.com/48505033/153177143-3db57dd6-5c1a-46e0-85dd-32a5d5a96694.png)

Thanks in advance for your help

**Comment by namdre** [comment]
The program "online" is created whenever you modify traffic light states via TraCI (the original program is kept around and can be restored by `traci.trafficlight.setProgram`). When loading a state, the online program is ignored and the original program is used. You need to take control again via TraCI if you want to restore whatever special states it had.  Apart from that, the warning can be safely ignored.
