### ISSUE TITLE
Sub-lane changing model

### ISSUE THREAD

**Issue by emotion68** [eclipse/sumo#10138]
I want to write a lane-changing model by myself. In the lane-changing model I wrote, I need to obtain the information of the vehicles ahead and behind in the side lane. I used the methods of _getRightLeaders_ or _getRightFollowers_, but I meet two problems:
(1) These two methods are said to be applicable to the sub-lane model. Do I need to define the vehicle lane-changing model as a sub-lane model before defining my own lane-changing model?
(2) In these two methods, traci.vehicle.getRightFollowers(vehID, blockingOnly=False), I don't know the blockingOnly=False parameter is what mean. 
(3)Which of the following should be the format of the second parameter in this method?
traci.vehicle.getRightFollowers(vehID, blockingOnly=False) or traci.vehicle.getRightFollowers(vehID, False)
(4)The default lane change mode is 0b011001010101 = 1621 ,I want to know the sub-lane model.

**Comment by namdre** [comment]
(1) If your own lane-changing model is intended for  sublane-laneChangeModel, then you must run sumo with the sublane-model enabled (the vehicles will then run with SL2015 automatically)
(2) blocking=True, only those vehicles that block a change in the respective direction are returned
(3) both work
(4) it's the same

**Comment by emotion68** [comment]
> (1) If your own lane-changing model is intended for sublane-laneChangeModel, then you must run sumo with the sublane-model enabled (the vehicles will then run with SL2015 automatically) (2) blocking=True, only those vehicles that block a change in the respective direction are returned (3) both work (4) it's the same

(1) I know LC2013 is 1621, but I don't know the number for SL2015.
(2) I mean if I need to get the vehicle information for the side lane, do I need to set the vehicle to the SL2015 model? Or is it possible to get information about vehicles in the side lane without setting it?

**Comment by namdre** [comment]
> (1) I know LC2013 is 1621, but I don't know the number for SL2015.
I already gave you the answer: *4) it's the same* 

> (2) I mean if I need to get the vehicle information for the side lane, do I need to set the vehicle to the SL2015 model? Or is it possible to get information about vehicles in the side lane without setting it?

It doesn't matter what you set the vehicle model to but rather whether sumo runs with option **--lateral-resolution** or not.
If the option is set, there may be multiple leaders / followers per lane. Otherwise there may be at most one.
