### ISSUE TITLE
collision

### ISSUE THREAD

**Issue by emotion68** [eclipse/sumo#10148]
![sumocfg_collision](https://user-images.githubusercontent.com/82993708/153785553-59eb6baf-ee79-4638-89be-12b3eb6ebbc4.jpg)
![1644802030(1)](https://user-images.githubusercontent.com/82993708/153785562-d831c712-c1ef-4cee-b9ca-e9f58507c88b.jpg)

Is this how the collision output is written in the sumocfg configuration file? Why is the runtime always telling me that I have no options

**Comment by namdre** [comment]
That option was added in version 1.9.0. An upgrade is recommended.
