### ISSUE TITLE
personGenerator.py does not work from the command line

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#10143]
It always gives 
```
Traceback (most recent call last):
File "./personGenerator.py", line 461, in <module>
source, destination = parser.parse_args()
TypeError: 'Namespace' object is not iterable     
```
It probably never worked, at least I cannot spot the commit which changed it. Now that we have personFlows directly in SUMO it is maybe not useful anymore.
@tkchouaki Do you still need it?

**Comment by tkchouaki** [comment]
I don't think it is still relevent.
Also +1 for removal.
