### ISSUE TITLE
relative instead of absolute file paths stored in xml-files should be favoured

### ISSUE THREAD

**Issue by rjmaris** [eclipse/sumo#10144]
When I do version control with a plain simulation project, e.g. to enable team work, a problem arises - for example - when I load additionals in netedit. The additionals may be flagged immediately as modified, and hence should be saved. When I do that, diff shows exactly changes in `<input>` and `<output>` tags.

Also without versioning, this feels as uncomfortable. E.g. when I move the project into another directory, or when I email a zipped project directory to anyone.

**Side topic:**
Options (F10) are also stored in additional file. But when netedit starts with loading the net.xml file, the Options show up with their default values. This also gets reflected in the additionals:

git diff:
```
-    <bicycle>
-        <bikelanes.guess.max-speed value="13.89"/>
-        <bikelanes.guess.min-speed value="2.5"/>
-    </bicycle>
```

The defaults show up as 22.22 resp. 5.8. That means 80 km/h (wow!) resp. 21 km/h (min-speed!)
  
---
*If possible, upload an example that shows your problem.*

**SUMO-version:** 1.12

**operating system:** Linux

**Comment by namdre** [comment]
1. For relative paths, the dev-version contains the new option **--save-configuration.relative** (for the very reason you mention ... #6578)

2. The options you mention are not for the speed of bike lanes themselves. Rather, they are a filter for roads that should receive bike lanes when option **--bikelanes.guess** is set.
Very fast roads (i.e. motorways) should not get bike lanes and very slow roads (i.e. residential zones with reduced speed) also should not get bike lanes.

**Comment by rjmaris** [comment]
Sorry, I did a search before posting:
`is:issue is:open relative path`
... but had to wipe out the text part "is: open". I'll try to remind that.
