### ISSUE TITLE
Bicycles' preference for bike paths

### ISSUE THREAD

**Issue by dolevi-tub** [eclipse/sumo#10146]
Currently, bicycles do not treat bike paths any different from other lanes in their `bestLane` calculation.

It would be more realistic to have bicycles consider bike paths better than other lanes.

**Comment by namdre** [comment]
somewhat related: #9091

**Comment by namdre** [comment]
duplicate of #5480

**Comment by namdre** [comment]
@dolevi-tub (please continue discussion in #5480)
