### ISSUE TITLE
generation of invalid trips with od2trips

### ISSUE THREAD

**Issue by Inspire71** [eclipse/sumo#10152]
I have a two TAZ gate with only two edges each one (type=highway.motorway), input and output of the transport network of the simulation area. One of them can only be "from" and another one only "to".

When I use od2trips to generate the trips with the TAZ file and the OD matrix in O-format, od2trips selects as "from" edge the road that can only be "to". Then, when the routes are subsequently generated with duarouter, the logical connection error is generated

Warning: No connection between edge '14-source' and edge '13-sink' found.
Warning: Mandatory edge '13-sink' not reachable by vehicle '6384'.
Warning: The vehicle '6384' has no valid route.

To avoid generating improbable trips I have eliminated some roads where routes cannot start or end, that is, roads where there are no homes or there is no possibility of parking. In this way od2trips cannot select these routes as origin or destination. But, in the case of the TAZ gates I have maintained these roads since they are the exit and entrance of the simulation area.

In randomtrips there is an argument, --validate, which allows to identify if the routes are viable, but the same does not exist in od2trips.

How can I do so that od2trips does not select me from the origin of the trip this type of edges from which routes can not leave?

Thank you

**SUMO-version: nightly-extra version (January 12, 2022) 

**operating system: windows 11

**Comment by namdre** [comment]
Each TAZ can define distinct probabilities for an edge to be source or destination. For source-only TAZ, the destination probabilities should be set to 0 for all edges (and vice versa for destination-only TAZ).
See https://sumo.dlr.de/docs/Demand/Importing_O/D_Matrices.html#differentiated_probabilities


route validation with od2trips is currently not possible: #8588

**Comment by Inspire71** [comment]
Thank you Namdre. I've tried it and it solves my problem, including only that probability on the TAZ Gate edges, as in the example below.

<tazs>
    <taz id="1" color="242,122,112" edges="......... ....... ......"/>
    <taz id="2" color="155,60,26" edges="......... ....... ......"/>
    <taz id="3" color="252,0,63" edges="......... ....... ......"/>
.....
    <taz id="13" color="80,131,26">
      <tazSource id="250403659" weight="1"/>
      <tazSink id="243684096" weight="1"/>
    </taz>
    <taz id="14" color="132,18,3">
      <tazSource id="299684723#0" weight="1"/>
      <tazSink id="300402931#3" weight="1"/>
    </taz>
