### ISSUE TITLE
+ the question about the route file by jtrrouter with turn-ratio file and flow file

### ISSUE THREAD

**Issue by JaydenGao-gjd** [eclipse/sumo#10154]
Hello,
I generated the route file by jtrrouter with turn-ratio file and flow file. But I found the route file generated didn't match the turn-ratio I set in the turn-ratio file. Could you please tell me why it happened or how to deal with this question?

**Comment by JaydenGao-gjd** [comment]
> please attach minimal input files (zipped) to reproduce your problem.
I found the turn ratio of the intersection or the ratio from main-road to off-ramp in the route file generated were different from the ratio I set in the "city.turns.xml". Did I make the wrong settings in the file?
[test_demo.zip](https://github.com/eclipse/sumo/files/8066089/test_demo.zip)

**Comment by namdre** [comment]
You are using jtrrouter version 1.3.1. That version does not support the `<edgeRelation>` elements and simply ignores them. Instead the default turning ratios of 30% right turns, 50% straight and 20% left turns are used (option **--turn-defaults**).
I recommend upgrading to version 1.12.0: https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_release_version_1120

**Comment by JaydenGao-gjd** [comment]
> You are using jtrrouter version 1.3.1. That version does not support the `<edgeRelation>` elements and simply ignores them. Instead the default turning ratios of 30% right turns, 50% straight and 20% left turns are used (option **--turn-defaults**). I recommend upgrading to version 1.12.0: https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_release_version_1120

I have solved it for your reply. Many thanks for your kind and warm help.
