### ISSUE TITLE
Error: Another vehicle type (or distribution) exists.

### ISSUE THREAD

**Issue by Inspire71** [eclipse/sumo#10156]
I have built a simulation starting from an OD matrix (O-format) and some TAZ districts, where I have included a vehicle distribution file (vTypes) classifying them according to their environmental label, and therefore with a type of emissionclass (according to a HBEFA3 model) and vClass (passengers, motorcycle, delivery, moped, truck,..). There are 20 vType in this file for a single vTypeDistribution.

I have run od2trips identifying this --vtype "my distribution type name". Later I have generated the routes with duarouter, including as additional files the vtypes.xml which includes the vTypeDistribution identified in od2trips with the 20 vType, its emissionclass, its vClass, etc, and its probability.

I have created the sumo configuration file, where in the section <inputs> I have loaded the network, the routes file and as additional, the TAZ polygons and the vtypes file.xml.

I think that up to this point everything is correct, since I have been verifying each step. The problem is when I run the .sumocfg file through sumo-gui or sumo, when it finishes loading all the files it gives me an error that says the following:

Loading ...........
Loading done.
Error: Another vehicle type (or distribution) with the id 'NRP_moto_G_EU5_C' exists.
Quitting (on error).

I have verified that in the xml vtypes file with the vtypedistribution there is only one vtype with the reference 'NRP_moto_G_EU5_C'. Obviously it appears several times in the routes file depending on the assigned probability of that vtype. This is the first vtype of the routes file and it looks like it starts reading from the beginning and stays here.

To test, I changed the simulation with another vtype file with less vtype and shorter names (in this case only 3 vtypes) and it worked correctly, I was able to run the simulation without errors, which ensures that the process of executing trips and routes is fine and that the problem comes from the vtypes file.xml.

There are a limited number of vtypes that can be included in each vtypeDistribution?, 
Is there a limit on the name extension of each vtype?,
All the vtypes included must be referenced in the header of the route file?, in my case duarouter has been including them as they appeared in the generation of routes.

Thanks in advance
---
**SUMO-version: nightly-extra version (January 12, 2022)

**operating system: windows 11

**Comment by namdre** [comment]
By default duarouter includes all types in it's output and this gives you two choices
a)  do not load any further vtype file in your .sumocfg (duarouter output is ready to use) and this avoids the duplicate-type error
b) use duarouter options **--keep-vtype-distributions --vtype-output dummy.xml**  (sumo will re-sample the vTypes). 

option b) is not recommended if the choice of route is affected by the type of vehicle (i.e. roads that disallow motorcycle). In that case, go with option a)

**Comment by Inspire71** [comment]
thanks namdre, option a) allows me to run the simulation correctly.

**Comment by Inspire71** [comment]
I will also try option (b) as well.
