### ISSUE TITLE
behavior of traci.person.setSpeed

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#10166]
It currently changes the speed for all stages (even the past ones) and tries to adapt the speed for possible future steps by changing the vtype (but unsuccessfully). We could also use an influencer here as in the vehicle case but first we should clear the expectations.

**Comment by namdre** [comment]
- changing the speed for past stages is a bug
- changing the vtype and thus the speed for all future stages is ok (similar to how vehicle.setSpeed sets a persistent speed)
- I don't think we need a full-blown influencer here since we don't need time-lines for persons imho
