### ISSUE TITLE
Netedit crashes when changing departSpeed for vehicle flow (from-to edges)

### ISSUE THREAD

**Issue by malle72** [eclipse/sumo#10165]
Just straight up closes the window when I try to change the value for departSpeed. I've replicated it a number of times now with a route selected and without. At first I thought it crashed because the speed of the road selected to have the flow was lower than the speed I was setting, however even when I adjusted the road speed prior to attempting to create the flow it still crashes. And, again, it still crashes when changing the same value without any edges selected at all. 
  
---
![image](https://user-images.githubusercontent.com/42781131/154302126-44ad25e1-954e-40e5-b9e9-5d7bd1ae8e9e.png)

SUMO & Netedit version: 1.12.0

Windows 10

**Comment by palvarezlopez** [comment]
Hi @malle72. Thanks for your report. In the current dev version this error was fixed. You can download the new version of SUMO tomorrow.
