### ISSUE TITLE
Run Error

### ISSUE THREAD

**Issue by Aarnnity** [eclipse/sumo#10176]
Add your issue description here.
  
---
*If possible, upload an example that shows your problem.*
Hi, when I run the program, SUMO is not able to run successfully, I get the following error.
![3dbb725cff9946ffd01b98ce02d48a0](https://user-images.githubusercontent.com/66675156/154641195-ac569c74-07ed-4668-8b61-e9eb8f124f49.png)

I don't know what's wrong. So, can you offer some advice? thanks.

**SUMO-version:**
1.8.0
**operating system:**
Windows10

**Comment by namdre** [comment]
set environment variable `SUMO_HOME=E:\SUMO\sumo-win64-1.8.0\sumo-1.8.0`

The cause of your error is that you set it to `SUMO_HOME=E:\SUMO\sumo-win64-1.8.0\sumo-1.8.0\tools`

**Comment by Aarnnity** [comment]
> 

OK, the issue is resolved, thank you！
