### ISSUE TITLE
Invalid use of traci.trafficlights.setCompleteRedYellowGreenDefinition

### ISSUE THREAD

**Issue by symonsg88** [eclipse/sumo#10174]
I am using sumo through traci4matlab. I generated the complete definition of the semaphore through traci.traffilights.gCompleteRedYellowGreenDefinition At this point I intervened as per attachment for the duration of the green on the definition generated. I would now like to restore this modified definition via traci.trafficlights.setCompleteRedYellowGreenDefinition however the code keeps giving me error. Can anyone tell me where am I wrong? Thank you all
  
logic_list = traci.trafficlights.getCompleteRedYellowGreenDefinition('B1'); 

for tt = 1:numel(logic_list{1, 1}.phases)
    if contains(logic_list{1, 1}.phases{tt}.state,'G')
                logic_list{1, 1}.phases{tt}.duration = 10;
                logic_list{1, 1}.phases{tt}.minDur=10;
                logic_list{1, 1}.phases{tt}.maxDur=10;
    end
end

logic = traci.trafficlights.Logic("1", 0, 0, logic_list{1, 1}.phases);
traci.trafficlights.setCompleteRedYellowGreenDefinition('B1',logic);

**SUMO-version 1.11.0:**

**windows 10:**

**Comment by namdre** [comment]
traci4matlab is not supported by the core team and thus any related questions tend not to get quick answers.
It generally helps if you quote any errors you are receiving verbatim.

**Comment by symonsg88** [comment]
thank you.

Error is: 

"Error using uint8
Conversion to uint8 from string is not possible.

Error in traci.trafficlights.setCompleteRedYellowGreenDefinition (line 29)
    traci.packInt32(length(tls.programID)) uint8(tls.programID)];

Error in untitled2 (line 107)
traci.trafficlights.setCompleteRedYellowGreenDefinition('B1',logic);"

while using directly traci.trafficlights.setCompleteRedYellowGreenDefinition('B1',logic_list);

error is:

"Dot indexing is not supported for variables of this type.
 
Error in traci.trafficlights.setCompleteRedYellowGreenDefinition (line 15)
len = 1+4 + 1+4 + length(tls.programID) + 1+4 + 1+4 + 1+4; % tls parameter
 
Error in untitled2 (line 107)
traci.trafficlights.setCompleteRedYellowGreenDefinition('B1',logic_list);"

**Comment by namdre** [comment]
error1 looks like a bug in traci4matlab as it is trying to convert the programID (a string) into an integer
error2 also looks like a bug in traci4matlab (i'd guess the original implementer copied code from python and then never tested the function).

My recommended approach would be to 
- report the error you encounter at https://github.com/pipeacosta/traci4matlab/issues
- find an alternative to traci4matlab or at least to that function as it might take a while for the problem to be resolved (the last commit to traci4matlab was 9 months ago).

Alternatively, you could try to correct the bug in traci4matlab yourself and send a pull-request to it's maintainer

**Comment by symonsg88** [comment]
ok, i will try. Thank you!
