### ISSUE TITLE
getLeader

### ISSUE THREAD

**Issue by emotion68** [eclipse/sumo#10178]
Add your issue description here.
  
---
*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**

traci.vehicle.getLeader(v_id)
what distance does the second parameter get? From where to where?

**Comment by namdre** [comment]
for the distance parameter, see https://sumo.dlr.de/pydoc/traci._vehicle.html#VehicleDomain-getLeader

**Comment by emotion68** [comment]
> for the distance parameter, see https://sumo.dlr.de/pydoc/traci._vehicle.html#VehicleDomain-getLeader

The distance is measured from the front + minGap to the back of the leader, so it does not include the
minGap of the vehicle.
I don't understand how to calculate the distance, this return value is not equal to the x-coordinate difference between the two ids in the fcd file

**Comment by namdre** [comment]
on a straight road without [length/geometry mismatch](https://sumo.dlr.de/docs/Simulation/Distances.html#length-geometry-mismatch), the distance between vehicles A and B with positions x1,y1  and x2,y2 is equal to
`sqrt((x1-x2)*(x1-x2) + (y1-y2)*(y1-y2)) - vehLength_B - minGap_A`

**Comment by emotion68** [comment]
> on a straight road without [length/geometry mismatch](https://sumo.dlr.de/docs/Simulation/Distances.html#length-geometry-mismatch), the distance between vehicles A and B with positions x1,y1 and x2,y2 is equal to `sqrt((x1-x2)*(x1-x2) + (y1-y2)*(y1-y2)) - vehLength_B - minGap_A`

That is, if I want to get the distance between two cars, not the space headway, is it to add the distance return value of this leader method to minGap?

**Comment by emotion68** [comment]
> on a straight road without [length/geometry mismatch](https://sumo.dlr.de/docs/Simulation/Distances.html#length-geometry-mismatch), the distance between vehicles A and B with positions x1,y1 and x2,y2 is equal to `sqrt((x1-x2)*(x1-x2) + (y1-y2)*(y1-y2)) - vehLength_B - minGap_A`

traci.vehicle.getLeader(v_id)
First of all, I got the second parameter value based on this method.
Now I am not very clear. If I want to get the distance between the ego car and the preceding car, pay attention not to the space headway. Should I add mingap to this return value or subtract it?

**Comment by namdre** [comment]
add minGap to the value of getLeader to get the distance follower-front-bumper-to-leader-back-bumper.

**Comment by emotion68** [comment]
thank &nbsp;!



发自我的iPhone


------------------ Original ------------------
From: Jakob Erdmann ***@***.***&gt;
Date: Mon,Feb 21,2022 10:10 PM
To: eclipse/sumo ***@***.***&gt;
Cc: emotion68 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [eclipse/sumo] getLeader (Issue #10178)





 
add minGap to the value of getLeader to get the distance follower-front-bumper-to-leader-back-bumper.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by CRHPlusAI** [comment]
I have a follow up question along this chain regarding the second and optional input to `getLeader` functio. By default the value is 0. According to [https://sumo.dlr.de/pydoc/traci._vehicle.html#VehicleDomain-getLeader](https://sumo.dlr.de/pydoc/traci._vehicle.html#VehicleDomain-getLeader)
"The dist parameter defines the minimum lookahead, 0 calculates a lookahead from the brake gap."
What does brake gap mean? What does lookahead mean? Does it mean the maximum distance it would consider a lead?
And is look ahead in meter or in seconds? 

Thanks!

**Comment by behrisch** [comment]
The lookahead is indeed the maximum distance to look for a leading vehicle in meters. The brake gap is the distance the vehicle would travel if it would brake immediately with full deceleration. Please open rather new issues for additional questions especially if the issue has been closed for more than a year.

**Comment by CRHPlusAI** [comment]
> The lookahead is indeed the maximum distance to look for a leading vehicle in meters. The brake gap is the distance the vehicle would travel if it would brake immediately with full deceleration. Please open rather new issues for additional questions especially if the issue has been closed for more than a year.

Thank you very much!
