### ISSUE TITLE
Heatmap feature

### ISSUE THREAD

**Issue by rjmaris** [eclipse/sumo#10186]
I'd wish to see a heatmap feature for SUMO that might be drawn after stop of a simulation. It would give a visual representation where improvements in the net (e.g. tls) are to being realized. It also helps identifying rat-run traffic - which usually becomes more apparent when the traffic density goes towards congestion.

As a refinement, a left side bar showing all the defined flows where you could select to exclude or include individual flows for the heatmap representation.
  
---

**Comment by namdre** [comment]
features that might serve this purpose
- vehicle visualization
   - set "draw with constant size when zoomed out"
   - color by
      - speed
      - waiting time
     - accumulated waiting time
- set edge coloring to
  - by occupancy
  - by speed
  - by relative speed
  
also: record traffic metrics during simulation (edgeData) and visualize the aggregated values (i.e. timeLoss) in sumo-gui: https://sumo.dlr.de/docs/sumo-gui.html#visualizing_edge-related_data

**Comment by rjmaris** [comment]
@namdre Later on yesterday I found the information you're pointing to. Shortly thereafter I grasped that the dropdown box containing "standard", "real world" etc. can be extended which own view settings by name. And hence I defined view settings "occupancy", "lane density" and "entered". Cool! Only the default rainbow scale is not sooo cool becaue low density is then represented as red. Therefore I defined another scale from hue 242 till 410 (=50) in six steps of 28.
![heatmap](https://user-images.githubusercontent.com/1149309/154948781-553bba08-7e12-45ce-aa25-ec35f18d9745.png)

However, I encounter a practical handling problem:
I need an extra additional file, which - yet - contains this:
```
<additional>
    <edgeData id="full" file="output/edgedata.xml"/>
</additional>
```
The file is saved when I end the simulation by choosing to close files & views. In order to be able to view the heatmap, I need to reload the simulation. But then, the file is overwritten with a fresh header part without data. My workaround is as follows: Close files & view; rename edge data file in the file manager and then reload simulation.
Do I miss something?

**Comment by namdre** [comment]
- for some applications a color scale that starts at grey is more useful compared to one that starts at red. For this, the checkbox 'hide below threshold' and the neighboring threshold value field are useful. 
- to decouple generating edgeData and visualizing edgeData, my recommended approach is to define a second .sumocfg which only loads the .net.xml and edgeData file (**--edgedata-files**). The problem of "sumo-gui" overwrites outputs applies to any xml output and for larger projects I also tend to have a sumocfg for generating output and another one for only viewing the simulation. A quick fix to prevent overwriting outputs is to lauch sumo-gui with the option **--output-prefix someValue** which modifies output file paths and thus prevents overwriting.

**Comment by rjmaris** [comment]
@namdre Momentarily I also opt for the second sumocfg. Simply as an extra opened instance. When the simulation instance is ready, I'd reload the other instance: One caveat: reload (for simulation) takes a few seconds. I also see that just opening the net file, (and eventually the poly file) are enough prerequisites to open an edge data file. Could I define this in a sumocfg as well? I prefer this over restarting from the shell.

As a feature extension I'd wish that the dialog that appears at the end of the simulation would do the following when NO is answered (not closeAllWIndows):
- transfer the collected edge data that's still in memory (and not outputted to file) to the system's edge data structure for immediate visualisation usage

OR: 
- flush & close the open (output) files
- load the then readable edge data file whose name is specified in the additionals file as mentioned above.
In both cases, the user can reload the simulation when desired, regardless whether edge data is visualized or not.
However, in the "NO" case, it would speed up consequtive simulations when no reload would be necessary, but instead the time counter is set to zero as well as all other initializations for the start condition are executed (e.g. writing an almost empty edge data file ;-) )

**Comment by namdre** [comment]
> Could I define this in a sumocfg as well?

Anything you can start from a shell you can also put in a .sumocfg. If you are unsure how the config should look, append ** -C new.sumocfg** to your shell command to write a corresponding config.

> transfer the collected edge data that's still in memory (and not outputted to file) to the system's edge data structure for immediate visualisation usage

I think you are asking for #9756

**Comment by rjmaris** [comment]
Thanks for extended clarification.
Regarding #9756: Exactly!

Am 21.02.2022, 18:14 Uhr, schrieb Jakob Erdmann ***@***.***>:

**Comment by namdre** [comment]
should be working now.
