### ISSUE TITLE
Image information

### ISSUE THREAD

**Issue by Aarnnity** [eclipse/sumo#10185]
Add your issue description here.
  
---
Hi, being a newbie, I want to ask you a question. In the SUMO environment, is it possible to obtain the image directly in front of the currently controlled vehicle?

**SUMO-version:**
SUMO-1.8.0
**operating system:**
Windows10

**Comment by namdre** [comment]
No. Sumo does not provide this. The main visualization engine is the top-down 2D view.
The [extra-version](https://sumo.dlr.de/releases/1.12.0/sumo-win64extra-1.12.0.msi) permits a 3D view and you could potentially modify the camera view dynamically to match the viewpoint of a vehicle but there is currently not path by which to extract these images (even the traci-screenshot function does not work for the 3D view).
