### ISSUE TITLE
random.shuffle does not take a rng parameter any longer

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#10187]
It is deprecated since python 3.9 and will be removed in 3.11. We have the choice to either skip the parameter and loose the ability to get the same results across python version (especially 2 vs 3) or switch to numpy randomness altogether.

It affects at least routeSampler.py (which uses numpy anyway so here the second path might be the better one).

**Comment by behrisch** [comment]
have a look at osmtaxiStop

**Comment by namdre** [comment]
according to https://wiki.python.org/moin/TimeComplexity#set, the runtime should be ok

**Comment by behrisch** [comment]
reproducibility between python2 and python3 is not important any longer

**Comment by behrisch** [comment]
@bcoueraud87 for you

**Comment by bcoueraud87** [comment]
@behrisch Please assign me.

**Comment by namdre** [comment]
as discussed with @bcoueraud87 : the only tool using `random.shuffle` is osmTaxiStop and it's not affected by the deprecation.
