### ISSUE TITLE
getDrivingDistance

### ISSUE THREAD

**Issue by emotion68** [eclipse/sumo#10183]
Add your issue description here.
  
---
*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**
[getDrivingDistance]() (self, vehID, edgeID, pos, laneIndex=0)
I want to know the pos refers to the distance from where to where? It is from the starting point of the road or the starting point of this edge?

**Comment by namdre** [comment]
```
        For an edge along the remaining route of vehID, return the distance from the current vehicle position
        to the given edge and position along the vehicles route.
        Otherwise, return INVALID_DOUBLE_VALUE
```

**Comment by ngochungnguyenlg** [comment]
HI Mr. Namdre,
I am confused about the data-type of pos, and what is the meaning of that parameters?
