### ISSUE TITLE
permit clicking on vehicles

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#10191]
- start / end tracking
- check ids and properties

Problem:
The 2D-view approach to selecting objects (drawing something in a small boundary and recording the ids of everything that was drawn) is not appicable to the 3D-view. Here, the viewport and rendering are managed by the OSG library and the sumo code only updates object positions. 
Possible solutions:
- use a native object picking strategy (if OSG provides any functions for this)
- convert the window-relative mouse position into a sumo-network x,y coordinate and look up nearby objects in an RTree-like structure

**Comment by m-kro** [comment]
String names can be assigned to OSG objects (thus nodes) and the node(s) at the mouse position can be retrieved with the pick handler. I just checked that it is effectively possible to read the found object names related to vehicles.

Then I think the code for the context menu needs to be adapted/separated from 2D specific parts to be reused for the OSG view.

**Comment by namdre** [comment]
can't we just retrieve the GUIGlObject and call `openObjectDialog` to render the popupMenu on top of the OSGView?

**Comment by m-kro** [comment]
OK, does this always exist even if there is no 2D view?

**Comment by namdre** [comment]
Yes. Every vehicle is instantiated as a GUIVehicle which is also a GUIGlObject (even if it's 2D rendering method is never called)
