### ISSUE TITLE
setAccel set Speed

### ISSUE THREAD

**Issue by Hjp-momojiji** [eclipse/sumo#10196]
---
I close cfmodel, and set a new speed/Accel to the vehcle,but it didn't work.The vehicle can accelerate to  the target speed,but  Accel is not the desired acceleration.How to control the vehicle to accelerate to the target speed with the desired acceleration?
Here are my control way now.
setSpeedMode(vehID, 0)
setSpeed(vehID,17)
setAccel(vehID, 1.5)

**SUMO-1.9.2:**

**Comment by namdre** [comment]
either:
- vehicle.setSpeed in every step with the speed that would result from the desired acceleration
- vehicle.slowDown with a target speed that would result from constant acceleration or deceleration for the given duration

**Comment by Hjp-momojiji** [comment]
> either:
> 
> * vehicle.setSpeed in every step with the speed that would result from the desired acceleration
> * vehicle.slowDown with a target speed that would result from constant acceleration or deceleration for the given duration

thanks , I just succeeded in controlling the acceleration with the first method!
