### ISSUE TITLE
deleting last (or only) personTrip-element crashes netedit

### ISSUE THREAD

**Issue by angelobanse** [eclipse/sumo#10192]
When attempting to delete the only PersonPlan (or if there are multiple, the last one), in PersonPlans-Mode using the context menu in the Hierarchy view section, netedit crashes.

![delete_crash](https://user-images.githubusercontent.com/16121932/154973088-ac9396dc-442e-47e1-9ac8-d92542ab2592.png)

**Comment by namdre** [comment]
please check whether this is a regression and if so, in which version

**Comment by angelobanse** [comment]
It is indeed a regression. It was working just fine until version 1.11.0
