### ISSUE TITLE
How to handle collisions

### ISSUE THREAD

**Issue by emotion68** [eclipse/sumo#10195]
Add your issue description here.
  
---
*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**
![1645495143(1)](https://user-images.githubusercontent.com/82993708/155049425-950e2c32-a3ca-437a-a596-4ee5134dc2d6.jpg)
![1645495097(1)](https://user-images.githubusercontent.com/82993708/155049434-0f2a7136-32bb-41e7-8d40-243470d518d7.jpg)

The two cars collided and even pressed him to walk over, why? How to deal with it?

**Comment by namdre** [comment]
It depends. Are you using TraCI? Did you do any of the things mentioned in https://sumo.dlr.de/docs/Simulation/Safety.html#collisions_during_car-following? What sumo version are you using?

**Comment by emotion68** [comment]
> It depends. Are you using TraCI? Did you do any of the things mentioned in https://sumo.dlr.de/docs/Simulation/Safety.html#collisions_during_car-following? What sumo version are you using?

I am using Traci
I set changelane mode=0, and then set the lane-changing rules of the vehicles myself, but I found that the vehicles would collide or even overlap, and would not queue up

**Comment by emotion68** [comment]
> 这取决于。你在使用 TraCI 吗？[您是否做了https://sumo.dlr.de/docs/Simulation/Safety.html#collisions_during_car-following](https://sumo.dlr.de/docs/Simulation/Safety.html#collisions_during_car-following)中提到的任何事情？你用的是什么相扑版本？

1.12.0 version

**Comment by emotion68** [comment]
> 这取决于。你在使用 TraCI 吗？[您是否做了https://sumo.dlr.de/docs/Simulation/Safety.html#collisions_during_car-following](https://sumo.dlr.de/docs/Simulation/Safety.html#collisions_during_car-following)中提到的任何事情？你用的是什么相扑版本？

1.12.0 version
![image](https://user-images.githubusercontent.com/82993708/155080410-96a06a79-684a-4036-9cc6-bbaef9f3c0cf.png)

**Comment by namdre** [comment]
lanechangemode=0 can do this: It disables all safety checks during traci-triggered lane changing.
use 256 or 512 instead (https://sumo.dlr.de/docs/TraCI/Change_Vehicle_State.html#lane_change_mode_0xb6)

**Comment by emotion68** [comment]
> lanechangemode=0 可以做到这一点：它在 traci 触发的车道变换期间禁用所有安全检查。 改用 256 或 512 ( https://sumo.dlr.de/docs/TraCI/Change_Vehicle_State.html#lane_change_mode_0xb6 )


Thanks, but it still happens after I set it up, why ？
![image](https://user-images.githubusercontent.com/82993708/155081671-b66c29e7-748d-4bc4-a8f1-2d30fdf6e640.png)

**Comment by namdre** [comment]
I'm not a magician and cannot see your traci code or vehicle configuration. The configuration space for intentional collisions is quite big (and those must be ruled out before I investigate this as a possible bug). I recommend that you simplify your test case until you have determined the traci call or vType parameter that is causing this. If all vehicles have lane change mode = 512,  than the next likely reason is speedmode or your parameterization of the vType

**Comment by emotion68** [comment]
> I'm not a magician and cannot see your traci code or vehicle configuration. The configuration space for intentional collisions is quite big (and those must be ruled out before I investigate this as a possible bug). I recommend that you simplify your test case until you have determined the traci call or vType parameter that is causing this. If all vehicles have lane change mode = 512, than the next likely reason is speedmode or your parameterization of the vType
Thank you for your help
If I wrote a series of rules for updating the speed based on speedmode=IDM, that is to say, I got the acceleration according to the rules, and then based on the theory of v(t+1)=v(t)+at, I used 'setspeed' to set the following one simulation step speed.
After I delete the speed rules I set, it is true that there is no collision, but what if I want to continue using these speed rules?

![1645516689(1)](https://user-images.githubusercontent.com/82993708/155088217-008180cc-704e-48de-8433-6bca84d6a3cf.jpg)

This picture shows some of the rules for updating the speed. The logic is as follows: The red box are the speed update rules I set, the acceleration is calculated according to the equation. In the blue box, the next speed is calculated based on the acceleration obtained in the previous step, use the setspeed method to set the next speed. I think so right? Why is there such a serious collision? If I don't run these codes, the vehicle does reduce collisions, but I'm very interested to know why?

**Comment by emotion68** [comment]
> > I'm not a magician and cannot see your traci code or vehicle configuration. The configuration space for intentional collisions is quite big (and those must be ruled out before I investigate this as a possible bug). I recommend that you simplify your test case until you have determined the traci call or vType parameter that is causing this. If all vehicles have lane change mode = 512, than the next likely reason is speedmode or your parameterization of the vType
> > Thank you for your help
> > If I wrote a series of rules for updating the speed based on speedmode=IDM, that is to say, I got the acceleration according to the rules, and then based on the theory of v(t+1)=v(t)+at, I used 'setspeed' to set the following one simulation step speed.
> > After I delete the speed rules I set, it is true that there is no collision, but what if I want to continue using these speed rules?

I'm not a magician and cannot see your traci code or vehicle configuration. The configuration space for intentional collisions is quite big (and those must be ruled out before I investigate this as a possible bug). I recommend that you simplify your test case until you have determined the traci call or vType parameter that is causing this. If all vehicles have lane change mode = 512, than the next likely reason is speedmode or your parameterization of the vType
Thank you for your help
If I wrote a series of rules for updating the speed based on speedmode=IDM, that is to say, I got the acceleration according to the rules, and then based on the theory of v(t+1)=v(t)+at, I used 'setspeed' to set the following one simulation step speed.
After I delete the speed rules I set, it is true that there is no collision, but what if I want to continue using these speed rules?
This picture shows some of the rules for updating the speed. The logic is as follows: The red box are the speed update rules I set, the acceleration is calculated according to the equation. In the blue box, the next speed is calculated based on the acceleration obtained in the previous step, use the setspeed method to set the next speed. I think so right? Why is there such a serious collision? If I don't run these codes, the vehicle does reduce collisions, but I'm very interested to know why?

[155088217-008180cc-704e-48de-8433-6bca84d6a3cf.zip](https://github.com/eclipse/sumo/files/8114763/155088217-008180cc-704e-48de-8433-6bca84d6a3cf.zip)

**Comment by namdre** [comment]
the original IDM model requires time steps < 1s (our own implementation of IDM works around this by having an internal stepping loop if the step length is too high).
I recommend that you test your model with option **--step-length 0.1**.  Also, when writing your own car-following  code, investigate every single collision in detail and do manual computation of expected speeds to see whether there is a bug in your code.

**Comment by emotion68** [comment]
> the original IDM model requires time steps < 1s (our own implementation of IDM works around this by having an internal stepping loop if the step length is too high). I recommend that you test your model with option **--step-length 0.1**. Also, when writing your own car-following code, investigate every single collision in detail and do manual computation of expected speeds to see whether there is a bug in your code.

Thanks!
Another question is, I use the slowdown method to set the speed of the vehicle, why is this speed not reached in the next step of the simulation?
At time t, the speed of the car whose id is 100 is 11.78. At this time, according to the speed update rules I wrote, the acceleration is 0.98, which means that the speed needs to reach 11.78+0.98=12.77 in the next simulation step. But it only reached 11.87 in the next second, why?

![image](https://user-images.githubusercontent.com/82993708/155097018-59635da0-a4ed-4320-a253-8266210ee918.png)

**Comment by namdre** [comment]
#7361

**Comment by emotion68** [comment]
> #7361

thank!!
