### ISSUE TITLE
How to divide long roads

### ISSUE THREAD

**Issue by mooejun** [eclipse/sumo#10200]
i try to convert osm to opendrive, it contains some highway,
after converted, i find the road is too long,
i want use some node tag to division it, but it seems no use,
could you tell me how to deal with this situation, thank you.

for example
![before](https://user-images.githubusercontent.com/17379856/155116486-9674fa08-cc7f-41e2-bc56-9235a7430a9d.png)
![after](https://user-images.githubusercontent.com/17379856/155116379-f51096f5-7968-4a92-9205-d26c679a670b.png)

the two 'way' finally convert to one road

--
SUMO-version: 1.12.0

operating system: win7 64

**Comment by namdre** [comment]
1. do not set option -R (--geometry.remove) 
2. set option --geometry.split if you need more intermediate nodes
3. set option --geometry.max-segment-length X if you still need more nodes

**Comment by mooejun** [comment]
it's working.
but i just want few nodes. 
for example if the distance between two nodes is greater than 100m, then intermediate it.
it seem like step3 you provided, but i dont need every node to be intermediated(step2).
--geometry.split false  --geometry.max-segment-length 100 seem no use

**Comment by namdre** [comment]
try **--geometry.min-dist 100  --geometry.max-segment-length 100 --geometry.split**

**Comment by mooejun** [comment]
**--geometry.min-dist 100** reduced map accuracy
still thank you, it helps me a lot (o゜▽゜)o☆
