### ISSUE TITLE
device.ssm

### ISSUE THREAD

**Issue by emotion68** [eclipse/sumo#10207]
Add your issue description here.
  
---
*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**
![image](https://user-images.githubusercontent.com/82993708/155275194-fd08a850-c244-49bb-9f8c-0ffcb843baeb.png)

![image](https://user-images.githubusercontent.com/82993708/155275283-46f227cd-1665-4bac-ab55-c01423f85c5e.png)
The car with id of 0 is clearly equipped in the route.xml file, but why is it not displayed during simulation?

**Comment by namdre** [comment]
add `<param key="device.ssm.trajectories" value="true"/>` if you want trajectory output.

What exactly do you mean by *"why is it not displayed during simulation"* ?

**Comment by emotion68** [comment]
> add `<param key="device.ssm.trajectories" value="true"/>` if you want trajectory output.
> 
> What exactly do you mean by _"why is it not displayed during simulation"_ ?

![image](https://user-images.githubusercontent.com/82993708/155288366-744beee7-8592-4ca0-8ca6-e3b9f5f7361e.png)
![image](https://user-images.githubusercontent.com/82993708/155288518-d20fefa8-9167-4335-a98e-ba28c8ba0a90.png)
I want to know why such a prompt appears? In the route file, all the vehicles are equipped with the same content, but this is only prompted for vehicle 0 during simulation.

**Comment by namdre** [comment]
The warnings for subsequent vehicles are omitted by design. Note, that you can set all the configuration `<param>`s in the vType (i.e. `L0`) to avoid redundant definitions.
