### ISSUE TITLE
erroneous routes with duarouter

### ISSUE THREAD

**Issue by Inspire71** [eclipse/sumo#10202]
I have created a trips file with od2trips (with O-format matrix and taz districts assigned), removing some edges from the transport network (an additional revised network file) where trips are unlikely to start or end.

od2trips -n TAZ_rev.taz.xml -d O_format_Base.txt -o OD_Base.trips.xml true --departlane best --departpos free --ignore-errors --verbose --vtype All_vehicles

with the trip file obtained, I have created the route file with duarouter, including in this case the complete transport network to generate the routes and the complete TAZ file

duarouter -n map.net.xml --route-files OD_Base.trips.xml -o OD_Base.rou.xml --ignore-errors --verbose --with-taz --additional-files vtypes_Base.xml,TAZ.taz.xml

The obtained file does not generate the expected routes, modifying for many vehicles the origin and destination of the trips and not completing the expected route, losing routes along many edges of the network. I modified the command line with different routing arguments but I can't get the expected routes with duarouter.

Finally, I have routed the trips directly from sumo and the result if it has been as expected, but this causes me problems when I want to put together different routes files in the simulation because the output file is not sorted by departure times and then ignoring de vehicles.

Could you help me with duarouter?, what am I doing wrong?

Thanks in advance
  
---
**SUMO-version: nightly-extra version (January 12, 2022)

**operating system: windows 11

**Comment by namdre** [comment]
remove option **--with-taz**. This way duarouter will let the trips start at the edges assigned by od2trips rather than searching for shortest routes between taz (and thereby re-assigning `from` and `to`).

also, sumo returns sorted routes when setting option **--vehroute-output.sorted**

**Comment by Inspire71** [comment]
Solved issue. Thanks namdre

**Comment by Ammarah-Irum** [comment]
@namdre  Hello.
I'm working on SUMO to analyze public demand and offer. I've used od2trips to generate individual passenger trips from an Origin-Destination (OD) matrix of 2 hours period in the morning(7 am-9 am), which gives me around 5000 passenger trips for 2 hour window. However, when I use duarouter to filter out invalid (disconnected) passenger trips, it outputs only 122 passenger trips for 3-minute window (7:00:00 am -7:03:00 am). The duarouter command that I'm using is as follows:

duarouter --net-file center_v2.net.xml --route-files output.odtrips.xml,gtfs_pt_vehicles.add.xml --additional-files gtfs_pt_stops.add.xml,pt_vtypes.xml --output-file duarouter.rou.xml --persontrip.walk-opposite-factor 0 --repair true --human-readable-time true -v  -b 25200 -e 32400 

Kindly suggest me a solution to get individual passenger routes also for 2-hours period. Thanks.
