### ISSUE TITLE
Get the value of the distance from a point in the road

### ISSUE THREAD

**Issue by emotion68** [eclipse/sumo#10220]
Add your issue description here.
  
---
*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**
The vehicle is on an edge of the route, if I want to get the distance between the vehicle and the end of this edge instead of the end of the route, which method should I use?

**Comment by namdre** [comment]
`traci.lane.getLength(traci.vehicle.getLaneID(vehID)) - traci.vehicle.getLanePosition(vehID)`
