### ISSUE TITLE
Error deleting vehicles with embedded routes

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#10226]
If embedded route is removed, vehicles's reference remains in AttributeCarriers. This produces a crash reloading or creating a new network.

**Comment by namdre** [comment]
@palvarezlopez  is this a regression?

**Comment by palvarezlopez** [comment]
Yes, probably exists  since embedded routes were designed and implemented

**Comment by namdre** [comment]
If it existed since creation (and thus never worked) it's **not** a regression.
