### ISSUE TITLE
PHEM light V5 support

### ISSUE THREAD

**Issue by Reivajar** [eclipse/sumo#10237]
Dear SUMO team,

I was using the last version of PHEM light dataset for emissions, but unfortunately, I am finding some issues with running it in SUMO 1.8, 1.9 and even 1.12.

However, with V4 it is working fine. I think the format of PHEM light files has changed between V4 and V5. Can it be related to that issue?

Thank you so much.
  
---

**SUMO-version: 1.8, 1.9 and 1.12**

**operating system: Ubuntu 18**

**Comment by behrisch** [comment]
The basic model works now in the latest development version but the new correction model is still missing

**Comment by namdre** [comment]
new classes must also be documented
