### ISSUE TITLE
memory leak on reload

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#10232]
about 8MB per run of the osm-webwizard test

first report by @rjmaris 
>  I see a memory leak after reloading a simulation in sumo-gui. 
> After starting sumo-gui, the memory increases from 2.5 until 7.5 % of 6 Gigs of memory till end of a simulation (tool: top/htop)
> Upon every reload+simulation approx. 4 % is added to memory usage.
> (v 1.12.0 as well as +0904, with minor differences in memory figures)

**Comment by namdre** [comment]
reproducible by reloading just a network (no traffic)

**Comment by namdre** [comment]
When loading the sumo-prorad/master This what I see in htop:
- initial size 1200M VIRT and 100M RES
- running sim once: 1260M VIRT and 200M RES
- if I just reload the sim without running it, I see + 12M VIRT + 1M RES per reload
- for run+reload, I see +90M VIRT + 90M RES per reload

**Comment by namdre** [comment]
Benchmarking a webwizard scenario with persons and public transport does not show memory increase with `valgrind --tool=massif`. Reported memory use stays constant over multiple reloads (might be the difference between VIRT and RES)

**Comment by namdre** [comment]
increasing memory use is tied to shape (`<poly>`) rendering!

**Comment by rjmaris** [comment]
Ah! Good to have it localized.

**Comment by namdre** [comment]
Problem is most likely related to specific polygon shapes that allocate extra memory during tessellation. The problem and it's solution are described at https://stackoverflow.com/questions/12258404/how-to-free-memory-allocated-in-glu-tess-combine-callback

heap tracing by Massif also points in this direction:
```
>12.93% (11,940,096B) 0x56D429: combineCallback(double*, double**, float*, double**) (GUIPolygon.cpp:79)
| ->12.93% (11,940,096B) 0x77CA418: ??? (in /usr/lib64/libGLU.so.1.3.1)
|   ->12.93% (11,940,096B) 0x77CA4AB: ??? (in /usr/lib64/libGLU.so.1.3.1)
|     ->12.93% (11,940,096B) 0x77CBF0D: ??? (in /usr/lib64/libGLU.so.1.3.1)
|       ->12.93% (11,940,096B) 0x77CCEBE: gluTessEndPolygon (in /usr/lib64/libGLU.so.1.3.1)
|         ->12.93% (11,940,096B) 0x56E2E1: GUIPolygon::performTesselation(bool, PositionVector const&, double) (GUIPolygon.cpp:231)
|           ->12.93% (11,940,096B) 0x56EA4A: GUIPolygon::drawInnerPolygon(GUIVisualizationSettings const&, SUMOPolygon const*, GUIGlObject const*, PositionVector, bool, double, bool, int) (GUIPolygon.cpp:339)
|             ->12.93% (11,940,096B) 0x56DE22: GUIPolygon::drawGL(GUIVisualizationSettings const&) const (GUIPolygon.cpp:173)
```
