### ISSUE TITLE
 traffic requirements

### ISSUE THREAD

**Issue by emotion68** [eclipse/sumo#10249]
Add your issue description here.
  
---
*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**
In the route file, ‘flows’ are used to define vehicles with parameters vehsPerHour or period or probability or number to define traffic requirements. When vehicle are defined individually, can only define how many vehicles there are in total? How to define how many vehicles are input per hour?

**Comment by namdre** [comment]
There is no general mechanism to scale global vehicles per hour. However, if you create your individual vehicles with the randomTrips.py tool you can set a global insertion period using option **--period**. the default value of '1' gives you 3600 vehicles per hour (possibly limited by the insertion capacity of your network).

**Comment by emotion68** [comment]
> There is no general mechanism to scale global vehicles per hour. However, if you create your individual vehicles with the randomTrips.py tool you can set a global insertion period using option **--period**. the default value of '1' gives you 3600 vehicles per hour (possibly limited by the insertion capacity of your network).

I define each vehicle individually. If there are 100 vehicles in total, what are the rules for these 100 vehicles to appear on the road?

**Comment by emotion68** [comment]
> There is no general mechanism to scale global vehicles per hour. However, if you create your individual vehicles with the randomTrips.py tool you can set a global insertion period using option **--period**. the default value of '1' gives you 3600 vehicles per hour (possibly limited by the insertion capacity of your network).

I define each vehicle individually. If there are 100 vehicles in total, what are the rules for these 100 vehicles to appear on the road?

**Comment by namdre** [comment]
each vehicle will appear at the specified `depart` time if there is sufficient space on the road. With insufficient space, insertion will be delayed. For details, see https://sumo.dlr.de/docs/Simulation/VehicleInsertion.html

**Comment by namdre** [comment]
see https://sumo.dlr.de/docs/Simulation/Distances.html

**Comment by emotion68** [comment]
> each vehicle will appear at the specified `depart` time if there is sufficient space on the road. With insufficient space, insertion will be delayed. For details, see https://sumo.dlr.de/docs/Simulation/VehicleInsertion.html

Since vehicles will appear as long as there is space, how do I know how many vehicles will be suitable for the road I build?

**Comment by emotion68** [comment]
> see https://sumo.dlr.de/docs/Simulation/Distances.html

![image](https://user-images.githubusercontent.com/82993708/156303539-d2b36ea9-1dd4-499f-918e-32e4c4aa5acb.png)
Is there a way for SUMO to directly change the coordinates or the title information on this picture with a py tool?

**Comment by namdre** [comment]
> Since vehicles will appear as long as there is space, how do I know how many vehicles will be suitable for the road I build?

https://sumo.dlr.de/docs/Simulation/RoadCapacity.html

**Comment by namdre** [comment]
> Is there a way for SUMO to directly change the coordinates or the title information on this picture with a py tool?

Assuming, your plot was created by the tool plot_trajectories.py, you can change the title by setting option **--label**.  To change the style of the plot, use the **--trajectory-type** option. There are currently no facilities for scaling (i.e. from m to km) but you can write the plot data as csv with option **--csv-output** and replot the data according to your requirements.

**Comment by emotion68** [comment]
> > Since vehicles will appear as long as there is space, how do I know how many vehicles will be suitable for the road I build?
> 
> https://sumo.dlr.de/docs/Simulation/RoadCapacity.html

I know how much road capacity should be set for the road I build, and I also want to implement the input of  road capacity (veh/h), but now, because the way I create the route is to input the vehicle individually, not how much density traffic flow, so only the total number of vehicles can be changed, not the number of vehicles in one hour. In short, it means that if I want to set the traffic capacity of the road to 2000 veh/h, then I use a separate definition vehicle when writing a route file , how many cars should be programmed?

**Comment by behrisch** [comment]
The capacity is not an input parameter but rather an emergent property of the simulation. You cannot define it in advance you can just set the "circumstances".
