### ISSUE TITLE
Flash back when opening sumo GUI

### ISSUE THREAD

**Issue by wangyinyin1028** [eclipse/sumo#10243]
When sumo-gui loads the config file, the road network will appear (1 second) and flash back immediately.
---

**SUMO-version:**
1.6.0
**operating system:**
window
[sumo_flashback.zip](https://github.com/eclipse/sumo/files/8161685/sumo_flashback.zip)
s

**Comment by namdre** [comment]
this is due to the options
```
<start value="t"/>
<quit-on-end value="t"/>
```
remove 'start' so the simulation waits for you to press the 'run' button
remove quit-on-end to keep it up after termination

**Comment by wangyinyin1028** [comment]
Thank you ！！！！I will try it tomorrow !



发自我的iPhone


------------------ Original ------------------
From: Jakob Erdmann ***@***.***&gt;
Date: Tue,Mar 1,2022 11:50 PM
To: eclipse/sumo ***@***.***&gt;
Cc: wangyinyin1028 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [eclipse/sumo] Flash back when opening sumo GUI (Issue #10243)
