### ISSUE TITLE
python2 and libsumo/libtraci

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#10241]
- currently, importing libsumo/libtraci fails with `TypeError: unbound method _manageStepListeners() must be called with Connection instance as first argument (got module instance instead)`
- libsumo with sumo-gui throws an exception `terminate called after throwing an instance of 'ProcessError("No option with the name 'vehroute-output.write-unfinished' exists")`
- CMake should prefer building the bindings for python3 if both versions are present on the system

**Comment by behrisch** [comment]
Current findings

- the immediate problem with the step listener has been solved, the general approach of the helper functions being transformed into class methods however does not seem to work with python2
- the preference mechanism via Python_ADDITIONAL_VERSIONS does not work well with GitHub Actions. It picks up libraries which are different from the Python interpreter version leading to failing tests. Furthermore the whole FindPythonLibs is deprecated, see #10278.
