### ISSUE TITLE
multiple crashes: model crashes with 1) meso, 2) no-internal-links, 3) in re-routing

### ISSUE THREAD

**Issue by ambuehll** [eclipse/sumo#10252]
Helping out @joelscha running a scenario. We came across multiple crashes.

sumo-gui crashed directly when opening the scenario with:
1) meso true
2) no-internal-links true 

sumo-gui crashed some while after starting the run of the scenario with:
3. when re-routing prob >0

Scenario files: [link](https://drive.google.com/drive/folders/1UjQ7t-9NN7c6v5ADaTapdCCJ27Kteb8s?usp=sharing)
**SUMO-version:** current build

**operating system:** Windows Server

Thanks!
Lukas

**Comment by namdre** [comment]
couldn't yet reproduce the crash by calling `sumo-gui -c MT_Mahe_220118_cleaned_withBus.sumocfg.xml --device.rerouting.probability 1`
How many runs should I expect before a crash happens?

Also, please try running without option `<threads>`. This is the most likely source of bugs.
Since it doesn't actually give meaningful speedup (at less then 16 cores) we're not heavily testing parallel simulations at the moment.

**Comment by ambuehll** [comment]
Sorry, `device.rerouting.probability` >0 was too general. If you set device.rerouting.probability =0.8, then it crashes in our scenario (with yesterday's build) at around 25000 with 4 threads. You're right, threads has an influence. When removing the option threads, the crash happens less often (2/4 runs).

**Comment by namdre** [comment]
I'm able to reproduce the crash now.  The scenario is subject to #10292 (but that shouldn't be cause for crashing).

**Comment by namdre** [comment]
After fixing #10294 I haven't be able to trigger the crash anymore. Please report if you still observe crashing.

**Comment by joelscha** [comment]
I tried it with today's latest development version. Sumo-gui and sumo still crashed 3 times each with `device.rerouting.probability = 1`.
 `threads` and `device.rerouting.threads` were commented out.
However, I am not sure if it is the same error now. While crashes so far seemed to occur randomly, they now always happen between 24690 - 27720.

**Comment by ambuehll** [comment]
I can confirm the crash with the latest dev for `device.rerouting.probability = 1` and `device.rerouting.probability = 0.8`.

**Comment by namdre** [comment]
Your scenario was also affected by #10298. Again, please report if you can still get it to crash.

**Comment by joelscha** [comment]
Thanks a lot for your efforts. I'm afraid it still crashes at the same time.

**Comment by namdre** [comment]
I'm somewhat optimistic that #10312 was responsible. Please report if you can still get it to crash after this fix.

**Comment by joelscha** [comment]
It looks like we got it! It ran through 3 times now without an error. :)
Thank you for your perseverance! 🥇

**Comment by namdre** [comment]
Your combination of options/inputs was rather productive in demonstrating bugs (-:
Please re-open if you find more.
