### ISSUE TITLE
Netedit: wrong conversion of junction to roundabout in lefthand systems

### ISSUE THREAD

**Issue by joelscha** [eclipse/sumo#10258]
Hi there, 
the conversion of an intersection to a roundabout in a left hand driving system in netedit is not working properly. The result is a roundabout as shown in the screenshot.

**SUMO-version: Latest development extra version**

**operating system: Windows 10**
 
![Roundabout_lefthand_example](https://user-images.githubusercontent.com/94970201/156323268-d508372a-6970-484b-93e4-d3652e51f48e.PNG)

Edit: For convenience reasons: here is a simple example network. By right-click on the junction and choosing "convert to roundabout" the issue can be reproduced.
[roundabout_lefthand.net.xml.zip](https://github.com/eclipse/sumo/files/8168288/roundabout_lefthand.net.xml.zip)

**Comment by namdre** [comment]
Thanks for reporting!
