### ISSUE TITLE
When roads merge and split, lanes are missing

### ISSUE THREAD

**Issue by mooejun** [eclipse/sumo#10267]
when I converted OSM to OpenDrive, it seemed some lane connect nothing
for example

![image](https://user-images.githubusercontent.com/17379856/156491262-a1bfe391-ef88-44a7-a179-dd193dc1182c.png)

netconvert --osm-files map.osm --opendrive-output map.xodr --geometry.remove true --offset.x 0 --offset.y 0 --roundabouts.guess true --tls.discard-simple true --tls.join true --tls.guess-signals true --tls.default-type actuated --keep-edges.by-vclass passenger --junctions.join true --junctions.corner-detail 5 --junctions.scurve-stretch 0.75 --osm.turn-lanes true

![image](https://user-images.githubusercontent.com/17379856/156491316-1916a527-9e1e-45f9-9711-813383d6f02a.png)
the highlight lane should connect to the right lane

---

**SUMO-version:** 1.12.0

**operating system:** win7 64

**Comment by namdre** [comment]
Thanks. It's a know feature request (#9674)

(Background: sumo models a lane drop like this to notify vehicles that they have to change lanes)
