### ISSUE TITLE
routeID defined in .rou.xml not found by rerouter defined in .add.xml

### ISSUE THREAD

**Issue by schwamborn** [eclipse/sumo#10275]
Output from `sumo-gui -c circular.sumocfg`:

> Loading net-file from 'circular.net.xml' ... done (3ms).
> Loading additional-files from 'circular.add.xml' ... 
> Error: MSTriggeredRerouter rerouterBottom: Route 'routeRight' does not exist.
> Loading of additional-files failed.
> Quitting (on error).

MWE attached here: [circular.zip](https://github.com/eclipse/sumo/files/8177533/circular.zip)

Same issue when calling `sumo -c circular.sumocfg`.

---
**SUMO-version:**
1.12.0+1067-9f738abf540

**operating system:**
Windows and Linux

**Comment by namdre** [comment]
This is the expected behavior (see https://sumo.dlr.de/docs/sumo.html#loading_order_of_input_files)

**Comment by namdre** [comment]
You can use your input files with `sumo -a circular.rou.xml,circular.add.xml -n circular.net.xml`
