### ISSUE TITLE
simulation is interrupted when using closingLaneReroute

### ISSUE THREAD

**Issue by Inspire71** [eclipse/sumo#10276]
I have applied the closingLaneReroute to a single lane of an edge with two lanes in the same direction. I have located the rerouter signage on the previous edge so that the vehicles have a rerouting behavior (R). When I run the simulation the vehicles stop at the entrance of the lane and are not rerouted. Subsequently, I equipped all vehicles with a reroutingDevice (--device.rerouting.probability 1), and run the simulation again, then the simulation is interrupted by 263 seconds (the simulation period is 3600s and starts at 46800s). I have done the same with closingReroute and it works perfectly (without a reroutingDevice). This is my additional file to close a lane

<additional>
   <rerouter id="obra" edges="945791976" probability="1">
      <interval begin="48000" end="50400">
         <closingLaneReroute id="27853892#0_0"/>
      </interval>
   </rerouter>
</additional>

In case it has anything to do with the problem, the following attributes are defined in the routes file: departLane="best", departPos="free" and departSpeed="max" 

Thanks in advance
---
**SUMO-version: nightly-extra version (January 12, 2022)

**operating system: windows 11

**Comment by Inspire71** [comment]
The zip contains all the basic files to reproduce the error. I have included 3 sumo configuration files (.sumocfg) with the following cases:
- the first (osm_PT.sumocfg) is the base file without the closure of the lane, including vehicle routes and public transport routes. This works correctly in the simulation
- the second (osm_closelane_PT.sumocfg) is the same previous configuration file with the addiotional file with the rerouter closing lane, and includes the --device.rerouting.probability 1 argument. This file where the simulation is interrupted in the second 47063 and sumo-gui is closed. 
- the third file (osm_closelane.sumocfg), includes the rerouter with the closing of the lane and includes the --device.rerouting.probability 1 argument, but I have removed the public transport routes and additional PT files, and the simulation works correctly again and vehicle rerouting is executed with the lane closed properly

I need to included the PT in the simulation

could be the problem with the association of a device.rerouting to buses?

thanks namdre

[10276_test.zip](https://github.com/eclipse/sumo/files/8179892/10276_test.zip)

**Comment by namdre** [comment]
Thank you for the test input!

The crash was caused by the 'arrivaEdge' attribute in the public transport vehicles. Rerouting may shorten their routes so that the old arrivalEdge is no longer applicable (now this gives a warning instead of a crash).
I'd suggest to disable rerouting for public transport (only) by modifying their type like this
```
<vType id="bus" vClass="bus">
   <param key="has.rerouting.devicel" value="false"/>
</vType>
```

While running your simuation I noticed multiple warnings (i.e. collisions) caused by unsafe right-of-way rules at motorway on-ramps. It seems that you set attribute `pass=true` to compensate for lack of acceleration lanes.
You may wish to add those lanes to your network by re-processing it with 
`netconvert -s map.net.xml --ramps.guess -o map2.net.xml`
An alternative (though probably a bit less realistic) solution would be to change the junction type where an on-ramp enters the motorway to 'zipper' so that the rightmost motorway lane and the on-ramp merge smoothly without collisions.

**Comment by Inspire71** [comment]
Hi Jakob,

I'm going to do some testing with the changes about closingLaneReroute

Thank you for the recommendations regarding ramps. At first I had a lot of congestion problems at these highway intersections and I was looking for some solutions. I'm going to test your modification proposals to improve it. very grateful

De: Jakob Erdmann ***@***.***>
Enviado el: viernes, 4 de marzo de 2022 13:45
Para: eclipse/sumo ***@***.***>
CC: Inspire71 ***@***.***>; Author ***@***.***>
Asunto: Re: [eclipse/sumo] simulation is interrupted when using closingLaneReroute (Issue #10276)


Thank you for the test input!

The crash was caused by the 'arrivaEdge' attribute in the public transport vehicles. Rerouting may shorten their routes so that the old arrivalEdge is no longer applicable (now this gives a warning instead of a crash).
I'd suggest to disable rerouting for public transport (only) by modifying their type like this

<vType id="bus" vClass="bus">

   <param key="has.rerouting.devicel" value="false"/>

</vType>

While running your simuation I noticed multiple warnings (i.e. collisions) caused by unsafe right-of-way rules at motorway on-ramps. It seems that you set attribute pass=true to compensate for lack of acceleration lanes.
You may wish to add those lanes to your network by re-processing it with
netconvert -s map.net.xml --ramps.guess -o map2.net.xml
An alternative (though probably a bit less realistic) solution would be to change the junction type where an on-ramp enters the motorway to 'zipper' so that the rightmost motorway lane and the on-ramp merge smoothly without collisions.

-
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Feclipse%2Fsumo%2Fissues%2F10276%23issuecomment-1059131503&data=04%7C01%7C%7C4977afccbe484ba30ccf08d9fddcd453%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637819947154530864%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Wu%2Bu5KwJ5Qy2sbJg%2FdPYP5mgzuU3qVLlvSBA6mT%2BvdI%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXYJ72BAKDXVTDPHXIACSWLU6IAVTANCNFSM5P27UKGA&data=04%7C01%7C%7C4977afccbe484ba30ccf08d9fddcd453%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637819947154530864%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2BHX7RLxbUUnd3FevwKdgOoGsOZZAcdB8phgPlnXjhFY%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C4977afccbe484ba30ccf08d9fddcd453%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637819947154530864%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=x%2BXl0DtgVQgNpCCmNQPIoa0jlLWxJeU1dJaar18cqDA%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C4977afccbe484ba30ccf08d9fddcd453%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637819947154530864%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=C4N80WNrkGjEoa9%2BJxLQcXBW4iZRFtzRl05PMrTYE6U%3D&reserved=0>.
