### ISSUE TITLE
ssm_ttc_value

### ISSUE THREAD

**Issue by emotion68** [eclipse/sumo#10274]
Add your issue description here.
  
---
*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**
When defining a vehicle with 'flow', how to get the ssm value of the vehicle?

**Comment by namdre** [comment]
enable the ssm device either in the vType or the fhe flow element (via `<param>`) or for all traffic using sumo options

**Comment by emotion68** [comment]
> enable the ssm device either in the vType or the fhe flow element (via `<param>`) or for all traffic using sumo options

How to increase traffic density when defining vehicles with 'flow'? I changed the value of the 'vehsPerHour' parameter, why do I feel that the density of the traffic flow has not changed, but just the simulation time has become longer?

**Comment by namdre** [comment]
delayed insertion. See
https://sumo.dlr.de/docs/Simulation/VehicleInsertion.html
https://sumo.dlr.de/docs/Simulation/RoadCapacity.html#further_headway_effects

**Comment by emotion68** [comment]
> delayed insertion. See https://sumo.dlr.de/docs/Simulation/VehicleInsertion.html https://sumo.dlr.de/docs/Simulation/RoadCapacity.html#further_headway_effects

First of all, thank you very much for your explanation, but I want to say that after I set it up as you said, the k-q graph will still show such a trend, instead of first rising and then falling, but I see congestion, which is Why?
![1646573236](https://user-images.githubusercontent.com/82993708/156925281-577b8343-ed46-4159-a1fd-04791252fbb8.jpg)

**Comment by namdre** [comment]
- what exactly did you set up?
- what exactly do you see that qualifies as "I see congestion?"

Note, that flow and density values obtained via edgeData are averages over space (the whole edge) and time (the aggregation interval configured by `freq`). You will be able to obtain more data points if you split your road into shorter edges and use a lower aggregation interval.

**Comment by emotion68** [comment]
> * what exactly did you set up?
> * what exactly do you see that qualifies as "I see congestion?"
> 
> Note, that flow and density values obtained via edgeData are averages over space (the whole edge) and time (the aggregation interval configured by `freq`). You will be able to obtain more data points if you split your road into shorter edges and use a lower aggregation interval.

I have set the collection frequency to 1, the road length is 3000, and the hourly traffic flow is 1500. The congestion I see is that vehicles have queued up.

**Comment by namdre** [comment]
If the queue doesn't fill the whole edge, then the local speed drop may be "hidden" when averaging over the whole edge. 
This is why I suggested to split the edge into shorter sections.

**Comment by emotion68** [comment]
Does sumo have a python tool for drawing 3d graphs?

**Comment by namdre** [comment]
I think not. @behrisch , please correct me, if I'm wrong

**Comment by emotion68** [comment]
> I think not. @behrisch , please correct me, if I'm wrong

[]([]([](https://sumo.dlr.de/docs/Simulation/Output/Lane-_or_Edge-based_Traffic_Measures.html))
Average number of vehicles on the edge (#) = sampledSeconds /  period
what does ‘period’ mean？)

**Comment by emotion68** [comment]
https://sumo.dlr.de/docs/Simulation/Output/Lane-_or_Edge-based_Traffic_Measures.html
Average number of vehicles on the edge (#) = sampledSeconds /  period
what does ‘period’ mean？

> I think not. @behrisch , please correct me, if I'm wrong

https://sumo.dlr.de/docs/Simulation/Output/Lane-_or_Edge-based_Traffic_Measures.html
Average number of vehicles on the edge (#) = sampledSeconds /  period
what does ‘period’ mean？

**Comment by namdre** [comment]
'period' refers to the aggregation period configured by attribute 'freq'
