### ISSUE TITLE
How to add a special car

### ISSUE THREAD

**Issue by zhl555** [eclipse/sumo#10279]
Hello guys!

How to add a car like this, it will not affect the surrounding vehicles, even if the car stops, it will not affect the normal driving of the surrounding cars .

I would like to be able to add a car like this that can be controlled with traci. However, the surrounding vehicles can be unaffected by it, not stopped because of it, nor slowed down because of it. How should this be achieved?

**Comment by namdre** [comment]
Vehicle interacting is a key component of traffic simulation and hard to suppress. If you need something that looks like a car but doesn't interact at all, define a a POI (`<poi id="car" color="yellow" layer="100.00" x="..." y="..." imgFile="car.png" width="5" height="2"/>`)
and move it around with `traci.poi.setPosition` and `setAngle`
