### ISSUE TITLE
Scramble crossing

### ISSUE THREAD

**Issue by TakumiSeo** [eclipse/sumo#10286]
Hello
I have created the intersection having got 4 crosswalks.
The point is that I am trying to create this kind of crosswalk called maybe scramble crossing.
![x_crosswalk](https://user-images.githubusercontent.com/49015441/156890187-62c3c7a6-b5b9-496c-9522-c876eefa9a46.jpg)

How can I possiblly make it in netedit or other method?
If anyone helps me, it will be quite supportive for my work.
Thank you:)
---
*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**

**Comment by namdre** [comment]
Select two sides to make one diagonal crossing, then repeat with a rotated selection:

![scramble](https://user-images.githubusercontent.com/6240630/156895254-3f016dc4-e430-4de6-9607-758bd9e08289.png)

**Comment by TakumiSeo** [comment]
Thank you for the reply.
Following the method you mentioned, it shows me this kind of imbalanced diagonal crossing.
![imbalanced_crosswalk](https://user-images.githubusercontent.com/49015441/156906723-48b5a9a5-c6fc-4020-b5d2-e0563f49af55.png)
Is it possible to make crossing from each four corners accurately?

**Comment by namdre** [comment]
In netedit, right click on a crossing and click "set custom shape", after editing the shape with dragging, confirm with enter.

**Comment by saihinchi-tak** [comment]
Thank you! It works well!
