### ISSUE TITLE
Question about ubuntu16.04 installing sumo-1.9.2

### ISSUE THREAD

**Issue by Morefrees** [eclipse/sumo#10283]
Add your issue description here.
First I downloaded the sumo-1.9.2 package and then followed the steps on the official website to install it. 
sudo apt-get install git cmake python3 g++ libxerces-c-dev libfox-1.6-dev libgdal-dev libproj-dev libgl2ps-dev python3-dev swig default-jdk maven libeigen3-dev
 git clone --recursive https://github.com/eclipse/sumo
 export SUMO_HOME="$PWD/sumo"
 mkdir sumo/build/cmake-build && cd sumo/build/cmake-build
 cmake ../..
 make -j$(nproc)
I found that my folder sumo-1.9.2/bin does not have netconvert and netgenerate files in it, which caused me to run flow-project in pycharm (my own road network always shows the road network generating error)
It seems that I used the relatively new sumo function tracei, which caused me to not run smoothly with the old version of flow, so I wanted to experiment with the new version of the sumo
Looking forward to receiving your reply, we would appreciate it！
---
*If possible, upload an example that shows your problem.*
(base) cl@cl-virtual-machine:~/sumo-1.9.2/build/cmake-build$ make -j $(grep -c ^processor /proc/cpuinfo)
[ 67%] Built target generate-version-h
[ 67%] Built target foreign_phemlight
[ 67%] Built target utils_xml
[ 67%] Built target foreign_tcpip
[ 67%] Built target od
[ 67%] Built target utils_common
[ 67%] Built target router
[ 67%] Built target utils_distribution
[ 67%] Built target utils_emissions
[ 67%] Built target utils_geom
[ 67%] Built target utils_importio
[ 67%] Built target utils_iodevices
[ 67%] Built target utils_options
[ 67%] Built target utils_shapes
[ 67%] Built target utils_traction_wire
[ 67%] Built target utils_vehicle
[ 67%] Built target mesogui
[ 67%] Built target mesosim
[ 67%] Built target microsim_actions
[ 67%] Built target libsumostatic
[ 67%] Built target microsim_cfmodels
[ 67%] Built target microsim_engine
[ 67%] Built target microsim
[ 67%] Built target microsim_lcmodels
[ 67%] Built target microsim_devices
[ 67%] Built target microsim_transportables
[ 67%] Built target microsim_traffic_lights
[ 67%] Built target microsim_output
[ 67%] Built target microsim_trigger
[ 67%] Built target utils_foxtools
[ 67%] Built target netload
[ 67%] Built target utils_gui_globjects
[ 67%] Built target utils_gui_div
[ 67%] Built target traciserver
[ 67%] Built target utils_gui_settings
[ 67%] Built target utils_gui_tracker
[ 67%] Built target utils_gui_images
[ 67%] Built target utils_gui_windows
[ 67%] Built target utils_gui_cursors
[ 67%] Built target utils_gui_shortcuts
[ 67%] Built target gui_dialogs
[ 67%] Built target gui
[ 67%] Built target guinetload
[ 67%] Built target foreign_eulerspiral
[ 67%] Built target sumo
[ 67%] Built target netimport_vissim
[ 67%] Built target netbuild
[ 67%] Built target netimport
[ 67%] Built target guisim
[ 67%] Built target activitygen_activities
[ 67%] Built target netimport_vissim_tempstructs
[ 67%] Built target netwrite
[ 67%] Built target activitygen_city
[ 67%] Built target duarouter
[ 67%] Built target dfrouter
[ 67%] Built target netimport_vissim_typeloader
[ 67%] Built target libsumojni
[ 67%] Built target jtrrouter
[ 67%] Built target libtracistatic
[ 67%] Built target marouter
[ 67%] Built target libtracicpp
[ 67%] Built target libsumocpp
[ 67%] Linking CXX executable ../../../../bin/polyconvertD
[ 67%] Linking CXX executable ../../../../bin/netgenerateD
[ 67%] Built target emissionsDrivingCycle
[ 67%] Built target emissionsMap
[ 67%] Built target utils_traci
[ 67%] Built target testlibsumo
[ 67%] Built target testlibsumostatic
[ 67%] Built target netedit_elements_data
[ 67%] Built target netedit_changes
[ 67%] Built target netedit_dialogs
[ 67%] Built target netedit_frames
[ 67%] Built target netedit_frames_common
[ 67%] Built target netedit_frames_network
[ 67%] Built target netedit_frames_demand
[ 67%] Built target netedit_frames_data
[ 67%] Built target netedit_elements
[ 67%] Built target netedit_elements_network
[ 67%] Built target netedit_elements_demand
[ 67%] Built target netedit_elements_additional
[ 67%] Built target od2trips
[ 67%] Built target sumo-gui
[ 67%] Linking CXX executable ../../../bin/netconvertD
[ 67%] Built target activitygen
Scanning dependencies of target libtracijni
[ 67%] Building CXX object src/libtraci/CMakeFiles/libtracijni.dir/java/libtraciJAVA_wrap.cxx.o
//usr/lib/x86_64-linux-gnu/libpoppler.so.58：对‘TIFFDefaultStripSize@LIBTIFF_4.0’未定义的引用
//usr/lib/x86_64-linux-gnu/libpoppler.so.58：对‘TIFFFdOpen@LIBTIFF_4.0’未定义的引用
//usr/lib/x86_64-linux-gnu/libpoppler.so.58：对‘TIFFWriteScanline@LIBTIFF_4.0’未定义的引用
//usr/lib/x86_64-linux-gnu/libpoppler.so.58：对‘TIFFClose@LIBTIFF_4.0’未定义的引用
//usr/lib/x86_64-linux-gnu/libpoppler.so.58：对‘TIFFSetField@LIBTIFF_4.0’未定义的引用
collect2: error: ld returned 1 exit status
src/polyconvert/CMakeFiles/polyconvert.dir/build.make:346: recipe for target '../../bin/polyconvertD' failed
make[2]: *** [../../bin/polyconvertD] Error 1
CMakeFiles/Makefile2:2953: recipe for target 'src/polyconvert/CMakeFiles/polyconvert.dir/all' failed
make[1]: *** [src/polyconvert/CMakeFiles/polyconvert.dir/all] Error 2
make[1]: *** 正在等待未完成的任务....
//usr/lib/x86_64-linux-gnu/libpoppler.so.58：对‘TIFFDefaultStripSize@LIBTIFF_4.0’未定义的引用
//usr/lib/x86_64-linux-gnu/libpoppler.so.58：对‘TIFFFdOpen@LIBTIFF_4.0’未定义的引用
//usr/lib/x86_64-linux-gnu/libpoppler.so.58：对‘TIFFWriteScanline@LIBTIFF_4.0’未定义的引用
//usr/lib/x86_64-linux-gnu/libpoppler.so.58：对‘TIFFClose@LIBTIFF_4.0’未定义的引用
//usr/lib/x86_64-linux-gnu/libpoppler.so.58：对‘TIFFSetField@LIBTIFF_4.0’未定义的引用
collect2: error: ld returned 1 exit status
src/netgen/CMakeFiles/netgenerate.dir/build.make:241: recipe for target '../../bin/netgenerateD' failed
make[2]: *** [../../bin/netgenerateD] Error 1
CMakeFiles/Makefile2:2496: recipe for target 'src/netgen/CMakeFiles/netgenerate.dir/all' failed
make[1]: *** [src/netgen/CMakeFiles/netgenerate.dir/all] Error 2
//usr/lib/x86_64-linux-gnu/libpoppler.so.58：对‘TIFFDefaultStripSize@LIBTIFF_4.0’未定义的引用
//usr/lib/x86_64-linux-gnu/libpoppler.so.58：对‘TIFFFdOpen@LIBTIFF_4.0’未定义的引用
//usr/lib/x86_64-linux-gnu/libpoppler.so.58：对‘TIFFWriteScanline@LIBTIFF_4.0’未定义的引用
//usr/lib/x86_64-linux-gnu/libpoppler.so.58：对‘TIFFClose@LIBTIFF_4.0’未定义的引用
//usr/lib/x86_64-linux-gnu/libpoppler.so.58：对‘TIFFSetField@LIBTIFF_4.0’未定义的引用
collect2: error: ld returned 1 exit status
src/CMakeFiles/netconvert.dir/build.make:115: recipe for target '../../bin/netconvertD' failed
make[2]: *** [../../bin/netconvertD] Error 1
CMakeFiles/Makefile2:712: recipe for target 'src/CMakeFiles/netconvert.dir/all' failed
make[1]: *** [src/CMakeFiles/netconvert.dir/all] Error 2
[ 67%] Linking CXX shared module ../../../../bin/liblibtracijni.so
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building libtraci NKNOW
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ libtraci ---
[INFO] Deleting /home/cl/sumo-1.9.2/build/cmake-build/src/libtraci/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ libtraci ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources to META-INF
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ libtraci ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 79 source files to /home/cl/sumo-1.9.2/build/cmake-build/src/libtraci/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ libtraci ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/cl/sumo-1.9.2/build/cmake-build/src/libtraci/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:testCompile (default-testCompile) @ libtraci ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.17:test (default-test) @ libtraci ---
[INFO] No tests to run.
[INFO] 
[INFO] --- maven-jar-plugin:2.3.1:jar (default-jar) @ libtraci ---
[INFO] Building jar: /home/cl/sumo-1.9.2/src/libtraci/../../bin/libtraci-NKNOW.jar
[INFO] 
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ libtraci ---
[INFO] Installing /home/cl/sumo-1.9.2/src/libtraci/../../bin/libtraci-NKNOW.jar to /home/cl/.m2/repository/org/eclipse/sumo/libtraci/NKNOW/libtraci-NKNOW.jar
[INFO] Installing /home/cl/sumo-1.9.2/build/cmake-build/src/libtraci/pom.xml to /home/cl/.m2/repository/org/eclipse/sumo/libtraci/NKNOW/libtraci-NKNOW.pom
[INFO] 
[INFO] >>> maven-source-plugin:3.2.0:jar (default-cli) > generate-sources @ libtraci >>>
[INFO] 
[INFO] <<< maven-source-plugin:3.2.0:jar (default-cli) < generate-sources @ libtraci <<<
[INFO] 
[INFO] --- maven-source-plugin:3.2.0:jar (default-cli) @ libtraci ---
[INFO] Building jar: /home/cl/sumo-1.9.2/src/libtraci/../../bin/libtraci-NKNOW-sources.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.982 s
[INFO] Finished at: 2022-03-04T21:05:32+08:00
[INFO] Final Memory: 17M/244M
[INFO] ------------------------------------------------------------------------
[ 67%] Built target libtracijni
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
(base) cl@cl-virtual-machine:~/sumo-1.9.2/build/cmake-build$ sudo make install
[  2%] Built target utils_xml
[  2%] Built target generate-version-h
[  3%] Built target foreign_phemlight
[  3%] Built target foreign_tcpip
[  4%] Built target od
[  6%] Built target router
[  8%] Built target utils_common
[  8%] Built target utils_distribution
[  9%] Built target utils_emissions
[ 10%] Built target utils_geom
[ 10%] Built target utils_importio
[ 11%] Built target utils_iodevices
[ 11%] Built target utils_options
[ 12%] Built target utils_shapes
[ 13%] Built target utils_traction_wire
[ 13%] Built target utils_vehicle
[ 13%] Built target od2trips
[ 13%] Built target mesogui
[ 16%] Built target libsumostatic
[ 17%] Built target mesosim
[ 20%] Built target microsim
[ 21%] Built target microsim_actions
[ 23%] Built target microsim_cfmodels
[ 26%] Built target microsim_devices
[ 27%] Built target microsim_engine
[ 27%] Built target microsim_lcmodels
[ 30%] Built target microsim_output
[ 33%] Built target microsim_traffic_lights
[ 34%] Built target microsim_transportables
[ 35%] Built target microsim_trigger
[ 36%] Built target netload
[ 39%] Built target traciserver
[ 41%] Built target utils_foxtools
[ 42%] Built target utils_gui_div
[ 43%] Built target utils_gui_globjects
[ 44%] Built target utils_gui_images
[ 44%] Built target utils_gui_settings
[ 44%] Built target utils_gui_tracker
[ 46%] Built target utils_gui_windows
[ 46%] Built target utils_gui_cursors
[ 46%] Built target utils_gui_shortcuts
[ 47%] Built target gui
[ 48%] Built target gui_dialogs
[ 48%] Built target guinetload
[ 51%] Built target guisim
[ 51%] Built target sumo-gui
[ 51%] Built target sumo
[ 51%] Built target foreign_eulerspiral
[ 54%] Built target netbuild
[ 57%] Built target netimport
[ 57%] Built target netimport_vissim
[ 59%] Built target netimport_vissim_tempstructs
[ 65%] Built target netimport_vissim_typeloader
[ 66%] Built target netwrite
[ 67%] Linking CXX executable ../../../bin/netconvertD
//usr/lib/x86_64-linux-gnu/libpoppler.so.58：对‘TIFFDefaultStripSize@LIBTIFF_4.0’未定义的引用
//usr/lib/x86_64-linux-gnu/libpoppler.so.58：对‘TIFFFdOpen@LIBTIFF_4.0’未定义的引用
//usr/lib/x86_64-linux-gnu/libpoppler.so.58：对‘TIFFWriteScanline@LIBTIFF_4.0’未定义的引用
//usr/lib/x86_64-linux-gnu/libpoppler.so.58：对‘TIFFClose@LIBTIFF_4.0’未定义的引用
//usr/lib/x86_64-linux-gnu/libpoppler.so.58：对‘TIFFSetField@LIBTIFF_4.0’未定义的引用
collect2: error: ld returned 1 exit status
src/CMakeFiles/netconvert.dir/build.make:115: recipe for target '../../bin/netconvertD' failed
make[2]: *** [../../bin/netconvertD] Error 1
CMakeFiles/Makefile2:712: recipe for target 'src/CMakeFiles/netconvert.dir/all' failed
make[1]: *** [src/CMakeFiles/netconvert.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**SUMO-version:**
1.9.2   sumo-src-1.9.2.tar.gz
**operating system:**
ubantu16.04

**Comment by behrisch** [comment]
You need to decide either you clone the git repo or you build the downloaded src
I just retried on a clean ubuntu xenial and the following worked:
```
apt update
apt install git cmake python3 g++ libxerces-c-dev libfox-1.6-dev libgdal-dev libproj-dev libgl2ps-dev python3-dev swig default-jdk maven libeigen3-dev
tar xzf sumo-src-1.9.2.tar.gz 
mkdir sumo-1.9.2/build/cmake-build && cd sumo-1.9.2/build/cmake-build
cmake ../..
make -j8
```
There is possibly something wrong in your setup

**Comment by behrisch** [comment]
Closing for lack of feedback. Please leave a comment if you have more info.
