### ISSUE TITLE
how to make truck drive in the lane which just allow cars?

### ISSUE THREAD

**Issue by meco2020** [eclipse/sumo#10293]
Hello！I have a question about SUMO.
In the real highway scene, it occasionally happens that the truck occupies the lane of the car. 

But in SUMO, the allowed vehicle type of the lane is determined by vClass, and when the highway road network is finely adjusted, we tend to ban large trucks from the inner roads of the highway.

What I'm wondering is that in SUMO, is there a way to implement a truck driving in a lane where trunk is prohibited.
Thanks!

**Comment by namdre** [comment]
you can define a "special" truck with vClass="passenger". Just make sure to set all other parameters (length, width, accel, decel, guiShape ...) to values appropriate for a truck.

**Comment by meco2020** [comment]
> 

If you follow your method, will the truck of "passenger" type occupy the lane of "passenger" for a long time? In the real world, truck only occasionally occupies the lane of "passenger"

**Comment by namdre** [comment]
if you configure the truck to drive slower, it will tend to drive on the right more often than regular cars. You can also increase it's affinity to drive on the right by setting vType attribute lcKeepRight to a larger value (i.e .2-3, whereas the default is 1).
