### ISSUE TITLE
How SUMO makes vehicles to follow each other, keep distance between them and not to crash one in another when following? 

### ISSUE THREAD

**Issue by lola-notraffic** [eclipse/sumo#10299]
For example, if we want to insert 2 vehicles in lane 1 in a certain way:

car1 = speed=10, dist=50, lane=1
car2 = speed=10, dist=56, lane=1
minimum gap between vehicles: >1 

where:
dist - is the distance from a stop line.
 
It is a simple example for numerous vehicles we insert. 
So we want to know how SUMO makes vehicles to follow each other, keeps them at given distance and allows not to crash one in another when following? 

Thank you!
---

SUMO-version: 1.9.2

operating system: ubuntu 20.04

**Comment by namdre** [comment]
distance keeping is handled by the configured carFollowModel. See

https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#car-following_models
https://sumo.dlr.de/docs/Car-Following-Models.html

You can access carFollowModel functions via TraCI:

https://sumo.dlr.de/pydoc/traci._vehicle.html#VehicleDomain-getFollowSpeed
https://sumo.dlr.de/pydoc/traci._vehicle.html#VehicleDomain-getSecureGap
