### ISSUE TITLE
How to set a different speed limit for different lanes of edge

### ISSUE THREAD

**Issue by xielang404** [eclipse/sumo#10308]
Add your issue description here.
      How to set a different speed limit for different lanes of edge? For a road with three lanes, I want to set different lanes on different edges to have different speed limits。
     For example, from point A to point B, there is an edge with Edge_1,There are three lanes on Edge_1, lane_1, lane_2, lane_3, how to set the maximum speed limit of lane_1 to 80Km/h, the maximum speed limit of lane_2 to 100Km/h, and the maximum speed limit of lane_3 to 120Km/h.
---
*If possible, upload an example that shows your problem.*
     For example, from point A to point B, there is an edge with Edge_1,There are three lanes on Edge_1, lane_1, lane_2, lane_3, how to set the maximum speed limit of lane_1 to 80Km/h, the maximum speed limit of lane_2 to 100Km/h, and the maximum speed limit of lane_3 to 120Km/h.
**SUMO-version:  1.12.0**

**operating system:  Win10**

**Comment by namdre** [comment]
you can set the speed for each lane: https://sumo.dlr.de/docs/Netedit/editModesCommon.html#inspecting_lanes

**Comment by xielang404** [comment]
However, netedit can only set the speed of the side, and cannot set the speed limit of the three-day lane on the edges separately.

**Comment by xielang404** [comment]
> 
However, netedit can only set the speed of the side, and cannot set the speed limit of the three lanes on the edge separately.

**Comment by namdre** [comment]
Each lane has its own attributes (including speed) and the link I gave explains how to inspect / edit those attributes.

**Comment by xielang404** [comment]
> 每个车道都有自己的属性（包括速度），我提供的链接解释了如何检查/编辑这些属性。

First of all, thank you for your patience. I think you maybe misunderstood my question. There will be three lanes (left, center and right) on the highway. I want to modify the speed of the left, center and right lane at the same time, but Netedit will modify one of the three, the other two will be synchronized. The core problem:  the left, middle, and right lane belong to edges.The three can't be separated, this is my trouble

**Comment by namdre** [comment]
I agree that there must be a misunderstanding somewhere. If you set the 'speed' property of the edge, then all lanes with have the same speed. If you set the speed property of the lane (after shift+click on the lane), the only the speed of that lane will be modified. This allows to set different speeds for the left middle an right lane of the same edge.

**Comment by xielang404** [comment]
Thaks！！Bro！！GET it！！

**Comment by xielang404** [comment]
> 我同意某处一定有误会。如果您设置边缘的“速度”属性，则所有车道都具有相同的速度。如果设置了车道的速度属性（shift+点击车道后），只会修改该车道的速度。这允许为同一边缘的左中间和右车道设置不同的速度。

thanks bro！！
