### ISSUE TITLE
speed rarely increases or decreases alot for no particular reason

### ISSUE THREAD

**Issue by Oritchimaru** [eclipse/sumo#10309]
I'm developing an algorithm where I manually set the speed by hand by setting each vehicle's speed (using setSpeed()) at each simulation step based on calculated acceleration that comes from a reinforcement learning pipeline. I'm also using 
`
traci.vehicle.setSpeedMode(veh_id, 0)`

for each vehicle.

My action space for accel/decel is [-5, 3] so for a vehicle to reach 0 speed from 16 in 1 timestep (1s) is impossible, yet it still happens.

It happens rarely for no particular or visible reason, like approaching a collision or whatever.
I would like to know if there's something that invokes such behavior or if I should exclude more safety checks somehow like setSpeedMode(veh_id,0).

**Comment by namdre** [comment]
If speedMode is 0 and you are calling setSpeed in *every* simulation step then you should not see any speed changes beyond those you requested. Please provide your scenario files along with a trace file of all traci commands https://sumo.dlr.de/docs/TraCI/Interfacing_TraCI_from_Python.html#generating_a_log_of_all_traci_commands

**Comment by Oritchimaru** [comment]
@namdre ok that covers me, I just wanted to ensure that's not anything left to remove from speed behavior control. I'm pretty sure now that's a problem from my side. I consider this topic closed. Thanks alot.
