### ISSUE TITLE
Longitudinal distance calculataion at turns

### ISSUE THREAD

**Issue by pradeeporuganti** [eclipse/sumo#10316]
Hello,
I am trying to understand how SUMO returns the longitudinal distance to a leader when the lanes they occupy are bent with respect to the other (for example when the lane turns right 90 degrees at an intersection). getLeader() gives the distance from the rear vehicle front bumper + mingap to the back of the leader vehicle. Does it also take into account the change in orientation of the lanes and vehicles? Additionally, does a similar calculation happen when querying information about leaders and followers in adjacent lanes using getNeighbours() ?

**Comment by namdre** [comment]
longitudinal distance is always computed along the center line of a lane
- the distance along a a lane with a 90 degree bend is the same as the distance along a straight lane
- when taking a turn at an intersection, the longitudinal distance is the sum of all the linear segment lengths that make up the curved lane
- the distance to another vehicle on a neighboring lane is computed as if the ego vehicle were already on that lane (so without taking lateral distance into account)

See also: https://sumo.dlr.de/docs/Simulation/Distances.html
