### ISSUE TITLE
SUMO visualisation issue

### ISSUE THREAD

**Issue by prashanth712** [eclipse/sumo#10324]
I have installed sumo using Nightly snapshots in windows system. But visualization of road network and GUI interface is distorted and not able to have clear view of vehicles and lanes.

Could you please help me in this regard to solve the issue
  
Below is the screenshot of the issue 
![SUMO_error (3)](https://user-images.githubusercontent.com/101544573/158113240-5a68f48b-7e2f-4386-b572-2ebb529d3b0d.PNG)

**SUMO-version:  SUMO v1_12_0+0529-fa2936cbd8d

**operating system: Windows 10

**Comment by namdre** [comment]
The most likely cause of this are invalid graphic card drivers. Please try installing the latest driver from the graphics card manufacturer

**Comment by prashanth712** [comment]
Thank you for the feedback I have also tested installing different simulators and other softwares that consumes high graphic interface. They all are working fine.

**Comment by namdre** [comment]
does the release version 1.12 work without those glitches?

**Comment by prashanth712** [comment]
Even for I have tried that but it is visualizing the same way. But i have tried in other systems it was working dine without any error

**Comment by namdre** [comment]
Note, that other simulators may be using a different graphics API (DirectX) rather than the platform-independent OpenGL API used by sumo-gui. Thus your success with other software does not reveal whether the OpenGL drivers for your graphics card are installed properly.

**Comment by prashanth712** [comment]
Ok, Thank you I'll check this out and let you know

**Comment by behrisch** [comment]
also see #7511

**Comment by prashanth712** [comment]
Thank you for the solution. Issue got resolved
