### ISSUE TITLE
Questions for start time of vehicles

### ISSUE THREAD

**Issue by Shiyunyang-seu** [eclipse/sumo#10330]
Hi, I want to know how the vehicle start time is calculated before the signal-controlled intersection in the current simulation. Many vehicles have a delay in starting up in the real world, are the current calculation rules related to the car-following model?
  
---
*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**

**Comment by namdre** [comment]
SUMO currently doesn't model start-time delay at signal-controlled intersections. A discussion on this topic including the current workaround is at #7832
