### ISSUE TITLE
calculate output time prefix only once

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#10346]
when using the time prefix for outputs different outputs of the same simulation might get different prefixes because they get instantiated at different steps in the simulation. A common one would help in grouping them.

**Comment by namdre** [comment]
while we're at it:  
- maybe the magic TIME value should also be interpreted in the whole file name and not just the prefix?
- people have reported issues when starting multiple time prefixed runs in the same second. Maybe we need to provide an option that adds subsecond precision to the time stamps?

**Comment by behrisch** [comment]
maybe it is better to use the process id to avoid name clashes

**Comment by behrisch** [comment]
yes, we could also add a prefix like % to the keywords if we fear accidental replacement

**Comment by behrisch** [comment]
Maybe the best solution is to "abuse" environment variable substitution and define `${TIME}` and `${PID}`

**Comment by behrisch** [comment]
local time and utc should be possible

**Comment by behrisch** [comment]
should be fixed now
