### ISSUE TITLE
osmWebWizard  "504 Gateway Timeout" 

### ISSUE THREAD

**Issue by toddchang45** [eclipse/sumo#10350]
Hi, I tried to use osmWebWizard tool to generate a simulation scenario.
My SUMO version and Python are both the latest. (for Windows 11)
When I pressed _Generate Scenairo_, the prompt showed "504 Gateway Timeout" and no osm files were generated.
I saw people run into this problem because of the large selection area.
But I don't think my selection area is so large.
As shown in the following screenshot.
 
![image](https://user-images.githubusercontent.com/43679461/158731327-ad0f2355-556e-4380-a4e5-4eeca8fa730e.png)

How could I solve this?
I might need to generate bigger simulation scenarios in the future.

**Comment by namdre** [comment]
- Sometimes, the osm servers ban an IP address. Trying again at a later time may help
- see also https://sumo.dlr.de/docs/Networks/Import/OpenStreetMapDownload.html

**Comment by toddchang45** [comment]
Got it. Thank you for replying!
