### ISSUE TITLE
osmWebWizard.py always returns 504 Gateway Timeout

### ISSUE THREAD

**Issue by micdic** [eclipse/sumo#10359]
I'm trying to generate a scenario with osmWebWizard.py.
From my shell log i see these errors:

...
Building scenario in '/Users/mic/sumo/tools/2022-03-17-15-30-12'
Downloading map data
504 Gateway Timeout
Converting map data
Written configuration to 'osm.netccfg'
Parsing types from '/Users/mic/sumo/data/typemap/osmNetconvert.typ.xml' ... done.
Error: Could not open osm-file 'osm_bbox.osm.xml.gz'.
Repeating initial error messages:
Could not open osm-file 'osm_bbox.osm.xml.gz'.
Error: No nodes loaded.
Quitting (on error).
Written configuration to 'osm.polycfg'
Error: Could not open net-file 'osm.net.xml'.
Quitting (on error).
...

Only 2 files in the folder "2022-03-17-15-30-12". 
osm.netccfg
osm.polycfg
Nothing more downloaded

I'm running sumo 1.12.0 on Mac OS BigSur.
I've also tried to reduce the requested map from OSM (very few roads, less elements, different geographic areas, ecc.), i've also changed the network connection, browsers, ecc. but still getting the same error.

Any hints? 
Thanks in advance.
Michele.

**Comment by micdic** [comment]
I've forced the creating of the scenario after downloaded manually the OSM map following:

https://github.com/eclipse/sumo/issues/10032#issuecomment-1028104289

then i've modified the oswWebWizard.py to work in the prepared directory and the scenario generated seems to work now.

I suppose that the OSM script (osmGet.py)  used to download the map had a possible issue...still having 504 Bad Gateway. Not really sure about it but I suggest to double check it.
Thanks.

**Comment by namdre** [comment]
@behrisch: I can confirm the Gateway Timeout even for small areas. Can you check whether your last work on osmGet might be related?

**Comment by behrisch** [comment]
It works here for the "default" Berlin-Mitte but I will have another look

**Comment by namdre** [comment]
working for me again as well. Might have been an issue on the OSM server side.

**Comment by micdic** [comment]
I can confirm, it's working now...after a couple of attempts (the first still having 504 bad gateway).
Used the default Berlin area.
Thanks
