### ISSUE TITLE
Regarding routeSampler.py and vehicle distributions

### ISSUE THREAD

**Issue by SkewAlex** [eclipse/sumo#10353]
Hello everyone, 
I would like to ask if it would be possible to add an option that would let routeSampler.py compute routes for all the vehicle types included on a vehicle distribution given by an additional file, like other tools such as flowrouter.py do, instead of running routeSampler.py once for each vehicle type included on my vehicle fleet data.

---
*If possible, upload an example that shows your problem.*

**SUMO-version: 1.12.0**

**operating system: Linux**

**Comment by namdre** [comment]
flowrouter.py also routes one vehicle category at a time so there must be a misunderstanding here.
However, if you have counting data that does not distinguish between the types in your distribution, you can call 

```
python tools/routeSampler.py --attributes="type=\"vTypeDistributionID\"" ...
```
And then load the generated traffic along with your vTypeDistribution.
