### ISSUE TITLE
Depart time

### ISSUE THREAD

**Issue by Anas-1998** [eclipse/sumo#10355]
Hello, firstly thanks for your time for answering this.
My problem is simply that I have a network, a highway specifically. and I want to spawn two vehicles at the same time with initial distance difference of 40m
What happen is that always the first vehicle spawns at t=0 and the second vehicle at t=1, even though the depart parameter is set to zero, can anyone tell me what I can do to force it to spawn at t=0?
Thanks again!

Sumo Version: Eclipse SUMO sumo Version 1.12.0
Operating System: Ubuntu 20.04.4 

<routes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/routes_file.xsd">
    <route id="route_highway" edges="Edge1 Edge2 Edge3" color="yellow"/>
    <route id="route_ramp" edges="EdgeRamp Edge2" color="yellow"/>
    <vehicle id="vehicle_0" depart="0.00" departPos="40.00" departSpeed="30.00" route="route_highway"/>
    <vehicle id="vehicle_1" depart="0.00" departSpeed="30.00" color="blue" route="route_highway"/>
    <vehicle id="vehicle_ramp" depart="0.00" departSpeed="30.00" color="red" route="route_ramp"/>
</routes>

**Comment by namdre** [comment]
most likely, the distance is considered unsafe for the given departure speeds.  Workarounds: https://sumo.dlr.de/docs/Simulation/VehicleInsertion.html#forcing_insertion_avoiding_depart_delay
