### ISSUE TITLE
Disabling automatic lane change teleportation

### ISSUE THREAD

**Issue by rahulbhadani** [eclipse/sumo#10368]
How to disable automatic Lange change of vehicles?
In my case, I tried to do with the following command in Python using Traci:

```
traci.vehicle.setLaneChangeMode("v_id_1",512)
```
I also tried the value of 256 and 0 as well

```
traci.vehicle.setLaneChangeMode("v_id_1",256)
```

```
traci.vehicle.setLaneChangeMode("v_id_1",0)
```

However, the behavior was unexpected after changing setLaneChangeMode to 256, 512, or even 0. The vehicle didn't proceed beyond the traffic intersection even though the traffic light was green.
  
Any idea on what could have gone wrong here?

**SUMO-version:**
Eclipse SUMO sumo Version v1_8_0+1437-c7ee52dce9 

**operating system:**
Ubuntu 20.04 LTS

**Comment by namdre** [comment]
Some lane changing (so called 'strategic' changing) is necessary to reach the correct turn lane. If the vehicle is forbidden from changing to the turn lane and you do not trigger a change with traci.changeLane the vehicle will be stuck.
