### ISSUE TITLE
module 'traci' has no attribute 'sumolib'

### ISSUE THREAD

**Issue by LetStarFly** [eclipse/sumo#10363]
Add your issue description here.
INFO: Starting new sumo server...
 Retrying in 1 seconds
Traceback (most recent call last):
  File "run_synchronization.py", line 319, in <module>
    synchronization_loop(arguments)
  File "run_synchronization.py", line 237, in synchronization_loop
    args.sumo_port, args.sumo_gui, args.client_order)
  File "/data/Co-Simulation/Sumo/sumo_integration/sumo_simulation.py", line 336, in __init__
    self.net = _get_sumo_net(cfg_file)
  File "/data/Co-Simulation/Sumo/sumo_integration/sumo_simulation.py", line 304, in _get_sumo_net
    sumo_net = traci.sumolib.net.readNet(net_file)
AttributeError: module 'traci' has no attribute 'sumolib'
Step #0.00Error: tcpip::Socket::recvAndCheck @ recv: peer shutdown
Quitting (on error).

  我想问一下，我跑example的时候遇到这个问题~~ 又大佬遇到过吗？

**Comment by namdre** [comment]
sumolib is it's own module and unrelated to traci: https://sumo.dlr.de/docs/Tools/Sumolib.html

**Comment by behrisch** [comment]
The module is sumolib not traci.sumolib. In which example did you encounter this? (Please post in English or German ;-) if possible)

**Comment by zhanghaochenkaixin** [comment]
> 在此处添加您的问题描述。信息： 正在启动新的相扑服务器...在 1 秒内重试回溯（最近一次调用最后一次）：文件“run_synchronization.py”，第 319 行，在 synchronization_loop（参数） 文件“run_synchronization.py”，第 237 行，在 synchronization_loop args.sumo_port、args.sumo_gui、args.client_order） 文件“/data/Co-Simulation/Sumo/sumo_integration/sumo_simulation.py”，第 336 行，**init** self.net = _get_sumo_net（cfg_file） 文件“/data/Co-Simulation/Sumo/sumo_integration/sumo_simulation.py”，第304行，_get_sumo_net sumo_net = traci.sumolib.net.readNet（net_file） 属性错误：模块'traci'没有属性'sumolib'步骤#0.00Error：tcpip：：Socket：：recvAndCheck @ recv：peer shutdown Quitting（出错时）。
> 
> 我想问一下，我跑example的时候遇到这个问题~~ 又大佬遇到过吗？
Is this problem going to be solved

**Comment by zhanghaochenkaixin** [comment]
Is this problem going to be solved?Can you introduce how to solve it?

**Comment by namdre** [comment]
The problem is on your end because you are using the imports wrong. Only you can solve your problem:

`
import traci
import sumolib
`

**Comment by hs867785578** [comment]
You should change the line 304 "traci.sumolib.net.readNet(net_file)" to sumolib.net.readNet(net_file) and import sumolib on the top of program.

**Comment by Jiaqi07** [comment]
> You should change the line 304 "traci.sumolib.net.readNet(net_file)" to sumolib.net.readNet(net_file). 
@hs867785578 
You have no idea how grateful I am for this response, it has taken me way too many days to try and figure out the AttributeError: module 'traci' has no attribute 'sumolib' provided when trying to run the default provided Cooperative merge and joining a platoon under co-simulation (SUMO required). Your solution was the only correct one I could find for my situation. Thanks!
