### ISSUE TITLE
How to obtain, within the time interval (k), the section flow Q_i (k) and density ρ_i (k)?

### ISSUE THREAD

**Issue by xielang404** [eclipse/sumo#10366]
Add your issue description here.
      My experimental setup: 11 nodes, 10 consecutive roads (line L0, L1...L9), each line is 100m, the traffic flow starts at L0 and ends at L9, how to get the k time interval , the flow Q_i (k) and the density ρ_i (k) of each road (straight line L0, L1...L9)
---
*If possible, upload an example that shows your problem.*

**SUMO-1.12.0:**

**Win10:**

**Comment by namdre** [comment]
https://sumo.dlr.de/docs/Simulation/Output/Lane-_or_Edge-based_Traffic_Measures.html
