### ISSUE TITLE
How do you make your own lane change strategy? What is Sumo's own lane change strategy?  I need to add my own lane change strategy to some sections.  

### ISSUE THREAD

**Issue by xielang404** [eclipse/sumo#10369]
Add your issue description here.
  
For example, road A (100m in length) has two roads, lane_1 and lane_2. The strategy I want to set is: for the first 80 meters, vehicles in lane_1 and lane_2 will not change lanes, and after 20 meters, they can change lanes.
---
*If possible, upload an example that shows your problem.*

**SUMO-1.12:**

**Win10:**

**Comment by namdre** [comment]
If you just want to forbid all lane-changing for the first 80m, the split the road into two parts and use attributes  changeLeft,changeRight to prohibit changing on the first part: https://sumo.dlr.de/docs/Networks/PlainXML.html#lane_change_restrictions

If you want to take dynamic control of lane changing, use TraCI functions vehicle.changeLane and vehicle.setLaneChangeMode: https://sumo.dlr.de/docs/TraCI/Change_Vehicle_State.html

If you want to understand sumo's model read: https://elib.dlr.de/102254/1/Springer-SUMOs_Lane_changing_model.pdf

If you want to write you own model, good luck (-:
