### ISSUE TITLE
deadlock on opposite overtaking slalom

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#10360]

**Comment by namdre** [comment]
found more deadlocks with stopped queues

**Comment by namdre** [comment]
There is still a deadlock in tests/sumo/opposite_direction_driving/slalom/4queues_deadlock and I'm unsure on how to solve it:
- a plattoon of vehicles is aproaching the deadlock section from both sides
- by the time they "see" each other it's too late

**Comment by behrisch** [comment]
maybe annotating the edge coud increase at least efficiency but in general teleporting is fine

**Comment by namdre** [comment]
Any new deadlock-avoidance requests should go into a new ticket then.
