### ISSUE TITLE
Error when importing traci in spyder IDE

### ISSUE THREAD

**Issue by shiyu022** [eclipse/sumo#10376]
when i import traci with spyder, it shows that please declare environment variable 'SUMO_HOME'. I guess my environment variable 'SUMO_HOME' is something wrong and i am a rookie. So can anybody help me? I appreciate it very much
![屏幕快照 2022-03-21 下午6 58 53](https://user-images.githubusercontent.com/101698390/159248520-630b3d0c-acca-416a-b942-59f6282c5347.png)
![屏幕快照 2022-03-21 下午6 58 29](https://user-images.githubusercontent.com/101698390/159248534-9f513d75-f3a6-41d2-ba6d-762b5fc63878.png)
![屏幕快照 2022-03-21 下午6 58 40](https://user-images.githubusercontent.com/101698390/159248554-ed003796-089d-41fe-b9ca-248f0071f074.png)
.

**Comment by shiyu022** [comment]
please

**Comment by schwamborn** [comment]
I'm not familiar with the spyder IDE, but a quick google search turned up this:
https://stackoverflow.com/questions/60210038/using-system-environment-variables-in-spyder

So you might have to add the SUMO_HOME environment variable to your spyder (project) configuration (Tools -> Current user environment variables)

**Comment by schwamborn** [comment]
Closing due to missing reply.
