### ISSUE TITLE
Change speed limits of multiple edges 

### ISSUE THREAD

**Issue by toddchang45** [eclipse/sumo#10382]
Hello,
I would like to change the speed limits of many edges, by selecting certain types of edges.
I generated my simulation from Google Maps by using osmWebWizard. 
There are some dirt roads, and these roads are categorized as highway-residential with speed limits of 13.89 m/s, which is too high for dirt roads in residential areas. 
I find that the speed setting in edges (lanes) will overwrite the speed limit in edge type.
For example, the speed limit of a lane is 13.89, and it won't work if I change the speed of the edge type to be lower.

I need to change the speed limit with these roads.
I am able to select all roads with highway-residential type in NetEdit, but it seems that I can only change the speed limit on edge by one edge. 
Is there a way to change speed limits of all selected roads? or other suggestions for doing this?

**Comment by namdre** [comment]
Once you have all the roads select, switch to inspect mode and click on one of the selected edges. Any changes you make to the edge attributes will be applied to all selected edges.

**Comment by toddchang45** [comment]
It works!! Thank you so much.
I thought I can only change one edge at a time.
