### ISSUE TITLE
How does Traci count the number of vehicles passing through the intersection in a certain period of time？

### ISSUE THREAD

**Issue by xielang404** [eclipse/sumo#10394]
Add your issue description here.
  I want to count the traffic of a certain road and the number of cars passing through this road over a period of time
---
*If possible, upload an example that shows your problem.*

**SUMO-version:1.12.0**

**operating system:Win10**

**Comment by namdre** [comment]
Options
- place a multiEntryExit detector that covers all lanes of that road / intersection and call traci.multientryexit.getLastIntervalVehicleSum
- traci.edge.getLastStepVehicleIDs for all relevant edges in every step and count *unique* ids over a time period
