### ISSUE TITLE
period as alias for freq

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#10390]
All outputs which use the `freq` attribute should understand `period` as an alias which makes it more consistent for instance with flow definitions and also unit wise it is in fact not a frequency

**Comment by namdre** [comment]
@palvarezlopez this also requires updating some netedit test results.

**Comment by schwamborn** [comment]
> @palvarezlopez this also requires updating some netedit test results.

Should be:
> netedit.daily.additional.e2detector : additionalelements/e2detector/load/tl
> daily.additional.e2multilanedetector : additionalelements/e2multilanedetector/load/tl

Would update myself but can't seem to successfully run the netedit tests on my machine.

**Comment by schwamborn** [comment]
Test `tools/xml/schemaCheck/tests/additional` now fails as `data/xsd/additional_file.xsd` doesn't allow `period` as an attribute, yet. However, XML v1.0 doesn't seem to support attribute aliases, unfortunately. As a workaround, the `freq` attribute could be replaced by `period` in the schema but this might confuse users who validate their additionals files still using `freq` instead of `period`.

**Comment by namdre** [comment]
I has bothered me for a while that freq/period is required for detectors. In contrast, edgeData works fine with optional freq and simply aggregates over the whole simulation duration by default.

My proposal is to make both 'freq' and 'period' optional in the xsd and let the period default to SUMOTime_MAX

**Comment by schwamborn** [comment]
We should consider moving or even deleting the `errors/freq_missing` test cases as they are technically not an error anymore.

**Comment by schwamborn** [comment]
> default period should be `SUMOTime_MAX - SUMOTime_MAX % DELTA_T` (the highest time that is a multiple of DELTA_T)

Is this in reply to commit b768a7b?
I deliberately did not touch the values since I do not know whether that would break anything.

**Comment by namdre** [comment]
It was a misunderstanding on my part because I didn't  see it was already working like this from 8bd5431a0cd25ac1fd33142a3d80421857f47ef0

**Comment by namdre** [comment]
@schwamborn can this issue be closed or is something still missing?
