### ISSUE TITLE
How a signal return from preemption to the pretimed timing?

### ISSUE THREAD

**Issue by MohamadReza-Haghani** [eclipse/sumo#10402]
Hi,

I am making a signal preemption algorithm in SUMO. There are three signalized intersections in my traffic network. A coordination exists between these three signals. I used "traci.trafficlight.setPhase" command for preemption to prioritize a special vehicle. I was wondering how the signal goes back to its pretimed timing after the preemption is finished and no other "setPhase" command is executed from traci. I need to know whether the coordination system is disturbed when the preemption ends.

**SUMO-version: 1.10**

**operating system: Windows 10**

**Comment by namdre** [comment]
If you are using traffic lights of type 'static', then a call to setPhase will shift the program in it's cycle and it will be out of coordination. You then need to call setPhase again (or maybe setPhaseDuration) to re-align it with the cycle.

If you are using an actuated traffic light with the appropriate coordination attributes, it will return to the original timing in the next cycle  (https://sumo.dlr.de/docs/Simulation/Traffic_Lights.html#coordination)
