### ISSUE TITLE
The question of merging area in SUMO environment

### ISSUE THREAD

**Issue by JaydenGao-gjd** [eclipse/sumo#10403]
Add your issue description here.

Hello, J am building a merging area to sim the real freeway. But I found these questions:

1) how can I make the jam in the merging?

2) how can I avoid collisions in the connection area?

3) how can I change the location of lane-changing via my set?

4) how can I obtain the traffic statistics in the connection area?

Could you please help me?
---
*If possible, upload an example that shows your problem.*

**SUMO-version: 1.12.0**

**operating system: win10**
[test.zip](https://github.com/eclipse/sumo/files/8334501/test.zip)

**Comment by namdre** [comment]
1.  there are three kinds of merging strategies available:
- equal priority merging (also known as zipper merge): https://sumo.dlr.de/docs/Netedit/neteditUsageExamples.html#creating_a_zipper_merge
- on-ramp merging with a dead-end acceleration lane: https://sumo.dlr.de/docs/Simulation/Motorways.html
- unequal priority merging (two connections target the same lane and only one of them has priority). This is only recommended for special cases (i.e. a bike lane ends and the bicycle must yield before entering the road).

2. Do not define two priority connections (white bars in sumo gui) that target the same lane
3. via the lcStrategic parameter and the length of the acceleration lane 
4. edgeData or detectors:   https://sumo.dlr.de/docs/Simulation/Output/Lane-_or_Edge-based_Traffic_Measures.html https://sumo.dlr.de/docs/Simulation/Output/index.html#simulated_detectors
