### ISSUE TITLE
recheck ignore-junction-blocker behavior

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#10413]
in test junction_model/ignoreJunctionBlocker/ignore_after_30
ignoring after 30s is not triggered, (teleporting is disabled)

**Comment by behrisch** [comment]
probably happened in test refactoring for #1078

**Comment by namdre** [comment]
ignore-junction-blocker checks the *waitingTime* of the blocking vehicle. In this test case, the leader is *stopped* rather than waiting and thus not ignored. Working as intended.
