### ISSUE TITLE
Question related to getFoes(self, laneID, toLaneID) in TraCI

### ISSUE THREAD

**Issue by Maxolus** [eclipse/sumo#10428]
In issue https://github.com/eclipse/sumo/issues/7717#issuecomment-738143689 a "_0" is added in the method call, why is this done? 
  
---

**SUMO-version:** 1.12.0

**operating system:** Windows 10

**Comment by namdre** [comment]
- `traci.lane.getFoes` requires a laneID as argument. 
- The method `person.getNextEdge` returns an edgeID
- currently, pedestrians reliably walk on the rightmost lane and this laneID can be derived from the edgeID by appending `_0` (0 is the index of the rightmost lane).
