### ISSUE TITLE
permit ':' in network ids except for the first character

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#10421]
currently a leading `:` indicates an junction internal objects (internal edges, lanes and internal junctions) so the first character cannot be freely assigned by the user.

However, the input validation prohibits `:` in all positions which prevents users from using naming scheme such as `FROM_NODE_ID:TO_NODE_ID` (observed in shapefile input)

**Comment by namdre** [comment]
@behrisch @palvarezlopez discuss!

**Comment by behrisch** [comment]
I don't know of any code which checks for the ':' in another place than the first. So yes, more power to the user.

**Comment by namdre** [comment]
I grepped our source tree and didn't find any code that checks for `:` except for position 0
