### ISSUE TITLE
vehicle overtaking problem

### ISSUE THREAD

**Issue by xielang404** [eclipse/sumo#10423]
Add your issue description here.
  For example, a car V_0, with a speed of 10m/s, has n cars behind it, and the maximum speed is 15m/s. On a road with multiple lanes, how can this n car surpass the preceding car V_0?
---
*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**

**Comment by namdre** [comment]
The n cars should do this automatically in their default configuration if there is sufficient space on the road.
You probably need to add more details about your setup (i.e. use of traci or custom vType configuration).

**Comment by namdre** [comment]
1. https://elib.dlr.de/102254/1/Springer-SUMOs_Lane_changing_model.pdf
2. traci.setLaneChangeMode, traci.changeLane (https://sumo.dlr.de/docs/TraCI/Change_Vehicle_State.html)

**Comment by xielang404** [comment]
May I ask how your vehicle getbestlines() is implemented? What is the core of the calculation method of bestlines? @ @ @namdre

**Comment by namdre** [comment]
See https://github.com/eclipse/sumo/blob/49ba1525d34ae23b515d08cf2643975a1f7b169c/src/microsim/MSVehicle.cpp#L5243
In particular https://github.com/eclipse/sumo/blob/49ba1525d34ae23b515d08cf2643975a1f7b169c/src/microsim/MSVehicle.cpp#L5447-L5624

It's working backwards along the route to find the lanes that minimize the number of needed changes.
