### ISSUE TITLE
Manipulation of jmIgnoreJunctionFoeProb during the runtime in TraCI

### ISSUE THREAD

**Issue by Maxolus** [eclipse/sumo#10427]
Good day, 

I wanted to ask if and how it is possible to change and get the attributes from the vType of pedestrians with TraCI - Python. Especially the parameters jmIgnoreJunctionFoeProb and jmIgnoreFoeProb. 
I'm working on an implementation of Issue https://github.com/eclipse/sumo/issues/7717 and I want to let pedestrians ignore the foe at junctions with a given probability when autonomous vehicles (there are already vehicles with this parameter in the simulation) are approaching.

---

**SUMO-version:** 1.12.0

**operating system:** Windows 10

**Comment by namdre** [comment]
solution: `traci.person.setParameter("ego2", "junctionModel.ignoreIDs", "foe.7 foe.8 foe.9")`

**Comment by namdre** [comment]
Note, that you currently need to roll the dice on all approaching vehicles in your script and then ignore the chosen ids.
