### ISSUE TITLE
pedestrian simulation problems

### ISSUE THREAD

**Issue by SuirongYi** [eclipse/sumo#10424]
I am doing a project on pedestrian simulation by using SUMO, mainly to simulate pedestrians crossing zebra crossings (using social force model). But I have encountered some problems, I hope you can give me some help, thank you very much!

1. The first is how to get the id of the zebra crossing through traci or other packages,

![c82e73aa877ae7246c74330eba48541](https://user-images.githubusercontent.com/92314798/160348929-5908b8ff-a199-4323-b99e-f12f19597cd5.png)
      As shown above I want to get ":gneJ1_c2" in python.

2. The second is that I want to get the coordinates of the zebra crossing, for example I want to get the coordinates of the four vertices with the id ":gneJ1_c2" in python, how should I do it?

3. The third is that I replace the next state of the pedestrian (x, y, angle, speed) with the state calculated by the social force model I use, but there will be some problems in the gui. Some pedestrians will disappear suddenly, and some will standstill on the zebra crossing.

I have used SUMO not long ago, and hope you forgive me if there is anything wrong. I really hope you can help me solve these problems, thank you very much.Happy work and good health!

---
*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**

**Comment by namdre** [comment]
1.  The crossings are named `:JUNCTIONID_cINDEX` where INDEX is numbered clockwise starting at the top. You can traverse the network including the junction internal lanes, crossings and walkingares by using sumolib.net.readNet(FILE, withInternal=True). See also https://github.com/eclipse/sumo/blob/main/tests/tools/sumolib/net_intermodal/runner.py
2. the shape of the crossing is it's centerline. You can shift that line by half the crossing width to the left or right to obtain the sides (sumolib.geomhelper.move2side)
3. I assume that you are using moveToXY to remote-control the pedestrian. It may be possible that you are hitting on bugs within that functionality. The best way for me to handle those is if you create one or more more minimal test cases (.net.xml, .rou.xml, runner.py) and document the exact mismatch between expected and observed behavior for me to look at. Attach each test cases as a zip file to this ticket.

**Comment by SuirongYi** [comment]
Thank you very much for your very detailed reply! In the third question, I did use moveToXY to control the pedestrian. I now need to review my code to see if a miscalculation is causing the pedestrian to behave so strangely. If I find some problems, I will follow the way you gave to create some minimal test cases and document the exact mismatch between expected and observed behavior to you.Thanks again for your patient reply！
