### ISSUE TITLE
Get the next second of acceleration

### ISSUE THREAD

**Issue by zhl555** [eclipse/sumo#10434]
In sumo, how to get the acceleration for the next second?
For example, if t=1 now, the acceleration a1=v1-v0 obtained by using traci.vehicle.getacceleration() in sumo. But when t=1, can a2 be obtained?

**Comment by behrisch** [comment]
No, SUMO cannot look into the future ;-) But if you describe what you want to achieve, maybe we can find a way

**Comment by zhl555** [comment]
I want to implement the adaptive cruise driving function for a car in sumo, and I limit the maximum deceleration of the ego car to no more than 3. However, before the traffic light, when the vehicle in front suddenly decelerates, the self-vehicle has no time to react, and collisions often occur. So I want to get information about the future of the car in front, so as to better develop a braking strategy

**Comment by namdre** [comment]
You can get an upper bound on the front vehicle speed (and hence it's acceleration) by calling traci.vehicle.getFollowSpeed and traci.vehicle.getStopSpeed by entering the parameters of the leader vehicle and the leaders leader (or the distance to a red traffic light).

**Comment by zhl555** [comment]
Thanks a lot, I'll try it
