### ISSUE TITLE
connections without conflict should be major on right-before-left junctions

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#10439]

**Comment by behrisch** [comment]
This changes nearly every right-before-left junction (almost 80 networks in the tests) because right turns are always major then. @namdre I think I need a  second option before committing.

```
diff --git a/src/netbuild/NBNode.cpp b/src/netbuild/NBNode.cpp
index a35da31290d..545601e6afc 100644
--- a/src/netbuild/NBNode.cpp
+++ b/src/netbuild/NBNode.cpp
@@ -2294,7 +2294,7 @@ NBNode::getLinkState(const NBEdge* incoming, NBEdge* outgoing, int fromlane, int
     if (outgoing == nullptr) { // always off
         return LINKSTATE_TL_OFF_NOSIGNAL;
     }
-    if (myType == SumoXMLNodeType::RIGHT_BEFORE_LEFT) {
+    if (myType == SumoXMLNodeType::RIGHT_BEFORE_LEFT && mustBrake(incoming, outgoing, fromlane, toLane, true)) {
         return LINKSTATE_EQUAL; // all the same
     }
     if (myType == SumoXMLNodeType::ALLWAY_STOP) {

```

**Comment by namdre** [comment]
I think it makes sense to accept this change and let every right  turn be major on a right_before_left junction. By default there will still be some deceleration due to turning speed reduction.

**Comment by behrisch** [comment]
another side effect is that turnaround junctions at the net boundary might now be major in some cases FWIW

**Comment by namdre** [comment]
> another side effect is that turnaround junctions at the net boundary might now be major in some cases FWIW

My gut feeling would be to keep turn-around connections minor regardless of conflicts

**Comment by behrisch** [comment]
> > another side effect is that turnaround junctions at the net boundary might now be major in some cases FWIW
> 
> My gut feeling would be to keep turn-around connections minor regardless of conflicts

Should we change the junction type then?

**Comment by namdre** [comment]
junctions with only one incoming edge are 'priority' anyway. This has to be changed in `getLinkState`
