### ISSUE TITLE
Is there a way to run simulation using GPU?

### ISSUE THREAD

**Issue by ajinra020307** [eclipse/sumo#10433]
Currently sumo is running using cpu. Is there a way to tell sumo to use gpu also?

**Comment by namdre** [comment]
Unfortunately, no. The simulation core isn't tailored to being vectorized and even multi-cpu parallelism is still a challenge (#9278)

**Comment by behrisch** [comment]
@jinyuxinjinyuxin Please open a new ticket with a detailed error description then
