### ISSUE TITLE
import type from shapefile

### ISSUE THREAD

**Issue by axonEmily** [eclipse/sumo#10444]
Hi, I want to use polyconvert to create some polygon by shape file. I can run it successfully but I fail to add type to it. I use --shapefile.type-columns ZONE_LABEL (which is the column name of zone type inside .dbf)  and --type-file type.typ.xml (I use the value of ZONE_LABEL as type id). The type of polygon is still unknown. Why is that?
The following image is my type file. 
*If possible, upload an example that shows your problem.*
![image](https://user-images.githubusercontent.com/96557891/160771270-e40e3e3a-40cc-4488-88bf-b349fd21f264.png)

**SUMO-version:**
sumo Version v1_12_0+1718-028626a5a4c
**operating system:**

**Comment by namdre** [comment]
can you post the exact polyconvert options and attach a shape file input example?

**Comment by axonEmily** [comment]
polyconvert --net-file net.net.xml --shapefile-prefixes Merge --shapefile.type-columns ZONE_LABEL --type-file type.typ.xml --shapefile.add-param true --shapefile.traditional-axis-mapping --output-file taz.xml
the folders I have:
![image](https://user-images.githubusercontent.com/96557891/160795938-781874d0-e889-4b1a-b0be-11a6ad3689fc.png)
a part of shape file:
![WhatsApp Image 2022-03-30 at 17 24 58](https://user-images.githubusercontent.com/96557891/160798923-da7a273c-ce7c-4ce2-83c0-a2e2a3e17b36.jpeg)

**Comment by namdre** [comment]
Can you attach the zipped shapefiles rather than a screenshot?

**Comment by axonEmily** [comment]
zipped shapefiles:
[Merge.zip](https://github.com/eclipse/sumo/files/8385842/Merge.zip)
(Data obtained from https://data.gov.hk/sc/)

**Comment by namdre** [comment]
The type file was using element `type` instead of the required `polygonType`.
Also, the previous version requires an explicit 'type' attribute (something like
`<polygonType id="AGR"  color="160,82,45"  type="AGR"  fill="true"  layer="-1"  discard="false" type="AGR"/>` ) but the latest dev version now uses the id as the type.

**Comment by axonEmily** [comment]
Thank you for your help! It works now. However, the 'type' attribute is still 'unknown' (others such as color is ok), why is that? How can I change 
![image](https://user-images.githubusercontent.com/96557891/161179809-77baca37-621a-48a8-abc2-c183e39e2ad9.png)

**Comment by namdre** [comment]
either
- add attribute **type** to your `<polygonType . ../>`
- updated to the latest development version where the polygonType id is used as fallback `type`

**Comment by axonEmily** [comment]
I have add the attribute type already,which is something like<polygonType id="RICH" color="255,255,255" fill="true" layer="-1" discard="false" type="RICH"/>. And I have download the version 
![image](https://user-images.githubusercontent.com/96557891/161214542-af7c8020-9304-4413-9081-36b55f5bcc7c.png)
today and try again(try with and without 'type' attribute), but the result of type is still 'unkown'.

**Comment by namdre** [comment]
- Sorry, I gave you the wrong attribute. It must be `name="RICH"`
- The nightly build failed tonight so the download still contained an unfixed version. Please try again tomorrow.
