### ISSUE TITLE
Invalid junction shape when conversion of xodr file to .net.xml file

### ISSUE THREAD

**Issue by Maheshwarneelam** [eclipse/sumo#10442]
Hi,

I have converted the xodr file to .net.xml format using netconvert in SUMO and compared converted .net.xml file with the default .net.xml file.  I noticed some extra area added at junctions.

For the references I have attached the Default .net.xml file image and the converted .net.xml file image which is using netconvert in SUMO.

Please help/suggest with the proper solution for the this issue.

*Please find the image showing the issue*
<img width="219" alt="Untitled" src="https://user-images.githubusercontent.com/102646156/161102122-aafa4958-9adc-4b3d-87db-83885067fea8.png">

Left image is default .net.xml file and Right image is converted .net.xml file from xodr using nectconvert in SUMO

**SUMO-version:*sumo 1.11.0*

**operating system:*windows 10*

**Comment by namdre** [comment]
- what is the relationship between the "default .net.xml" file and the xodr file that you used as input? (did you do .net.xml -> xodr -> .net.xml ?)
- can you attach the "default .net.xml" file and post all used netconvert options?

**Comment by behrisch** [comment]
Closing for lack of feedback. Feel free to add another comment if you have more information or can provide your input data.
