### ISSUE TITLE
Edge is deviating from original position when converting xodr file into .net.xml format using netconvert in SUMO

### ISSUE THREAD

**Issue by Maheshwarneelam** [eclipse/sumo#10443]
Hi,

I have converted the xodr file to .net.xml format using netconvert in SUMO and compared converted .net.xml file with default .net.xml file. I noticed the Edge is deviating from original position.

Please help/suggest with the proper solution for the this issue.

For the references I have attached the Default .net.xml fila and the converted .net.xml file using netconvert in SUMO.

*Please find the image showing the issue*
<img width="328" alt="Edge deviation" src="https://user-images.githubusercontent.com/102646156/160762760-d29952fb-0999-4d20-b8ba-b47ceaca9893.png">

Left side highlighted image is default .net.xml file and Right side highlighted image is converted .net.xml file from xodr using nectconvert in SUMO

**SUMO-version:*sumo 1.11.0*

**operating system:*windows 10*

**Comment by namdre** [comment]
possibly duplicate:

@Maheshwarneelam  Is this the same network and conversion process as in #10442  ?

**Comment by namdre** [comment]
Please comment if this is an original issue
