### ISSUE TITLE
support bidi edge interaction for all vehicles

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#10445]
context: bicycle simulation where a wide road is used in both directions across the whole width.

netconvert:

- [x] define forward and backward edge with the same (reversed) geometry and set edge attribute `bidi="true"` (same idea as in railway simulation)
- [x] preserve bidi attribute when loading .net.xml with netconvert
- [ ] ~~add option **--bidi.guess**~~ moved to #13546 

netedit
- [x] make 'bidi' into computed/overrideable edge attribute (type string) in netedit
- [x] visualization when 'spread' is set

sumo
- [x] identify overlapping lanes and assign the corresponding value to be returned by `MSLane::getBidiLane` (widths must match)
- [x] map vehicles from the bidi-lane as partial vehicles into the current lane so they are recognized during `MSVehicle::planMove` and `MSLaneChanger::change`
- [ ] refactor code that detects opposite vehicle direction (must check lcModel->isOpposite as well isOnBidi)

sumo-gui
- [x] visualization when 'spread' is set

Benefits:
- permits simulation of narrow roads, ""two-way left turn lane" and "suicide lane" arrangements even without sublane model.
- high fidelity bicycle simulation with sublane model

**Comment by yunpangfloetteroed** [comment]
The directory names of the tests represent the issues which should be checked.

**Comment by yunpangfloetteroed** [comment]
Vehicle still wiggles especially when the second bike is passing by and the vehicle makes an emergency braking which is not expected (he should be able to see the second bike coming eariler).

The sumo version v1_13_0+0846-9b68eadfd9
[bikePassingWithVehWiggle.zip](https://github.com/eclipse/sumo/files/8908768/bikePassingWithVehWiggle.zip)
6

**Comment by namdre** [comment]
creating a new bidi-pair in netedit currently requires to manually reset the endpoints. This should be improved.

**Comment by yunpangfloetteroed** [comment]
As we talked about, bikes should prefer to make overtaking on the right hand side, not like vehilces (on the left hand side). So, this should be improved as well.

**Comment by namdre** [comment]
There was a change in this regard in 7221494980ac4f3c40688712829bfa4dff5ac2fc]. Do you still see a problem with any of the existing tests? If not can you provide a new test case?

**Comment by yunpangfloetteroed** [comment]
Regarding  overtaking on the left hand side it can still be seen in the existing test ~\sumo_git\tests\sumo\sublane_model\bidiEdge\bikeFaultCollision

**Comment by yunpangfloetteroed** [comment]
Yes, now both of them pass by the vehicle on the right hand side. 

When the cyclist, in the aforementioned test, is going to approach/pass the vehicle from the other direction, he/she is still speeding up, like an overtaking action. But, I think, he/she should take an action more like "conflict avoiding" than "overtaking". So, the repsective speed may be actually getting slower or keeping the same. What do you think? 
Are both cases dealed as overtaking action in SUMO currently?

**Comment by namdre** [comment]
Actually, the speeding happens because the cyclist is below the desired speed. It is not directly related to overtaking.

**Comment by yunpangfloetteroed** [comment]
you mean the pre-defined max speed. right? it is actually not desired speed, but technical speed ability, as you wrote in #11102.  Perhaps this could be changed after your implementation in #11102.

**Comment by namdre** [comment]
It would be more accurate to say that the maxSpeed is currently used to model the desired speed since we don't have a distinct value for desiredMaxSpeed yet and bicycles have no relevant technical limit in this scenario.

**Comment by yunpangfloetteroed** [comment]
Yes, you are right with this point. Sorry, I did not make my point clear. The issue I would like to point out is that the cyclist should not try to speed up for reaching his/her desired speed, under such condition since he/she is actually under some "pressure" for safely riding through the narrow space between him/her and the vehicle (my own experience). In my case, I might (1) even stop for let the vehicle pass firstly or (2) continue and speed up when the vehicle stops and wait for that I pass by. The current situation is more like a situation with autonomous bike. And, the bike is 100% sure to run through the narrow space, while the vehicle aslo runs at the same time.

**Comment by felixfroehling** [comment]
Hey, is there any way I can already test the current development status?
For example in a nightly snapshot version?
And do you guys know, when the feature will be officially released?

**Comment by namdre** [comment]
> Hey, is there any way I can already test the current development status?

You can test the current features with 1.14.1 with examples from https://sumo.dlr.de/extractTest.php?path=sumo/sublane_model/bidiEdge

**Comment by yunpangfloetteroed** [comment]
Unable to execute isBidi in netedit also when the box is not shown grayed out.  Together with the attached example file the situation is described as below
- the links (E1, -E1, 977388750, -977388750, 371502353#0, -371502353#0)  could be set via isBidi 
-  These links were reset by klicking isBidi again
- Then it does not work when trying to set these links as bidi-links.
[problem.net.xml.zip](https://github.com/eclipse/sumo/files/9393084/problem.net.xml.zip)
