### ISSUE TITLE
Improve lane-changing model

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#1045]
this is for work on MSLCM_JE2013''''''

differences between JE2013 and the default model (LC2013)
* ~~[99b7bf7](../commit/99b7bf79cf06c447be7214dd3ef8162cebf5064a) (aka r15173)~~
* [9b5fcb6](../commit/9b5fcb69f18ef01588b46206e40bb9165a7b920b) (aka r15284),[574840e](../commit/574840ead240de342a399535b6eaf8408c40b43f) (aka r16540) recheck stayOnBest TURN_LANE_DIST 200 improves iTETRIS but makes BS run worse
* ROUNDABOUT_DIST_BONUS set to 100 (80 in LC2013)
* [2cd5fda](../commit/2cd5fda995851fa4786ab0b12bdc89089cd8469a) (aka r17057). improves A92 and iTETRIS (mostly) but makes bs_dido worse
* [2bbd7da](../commit/2bbd7da38f09854ad9716d933f9fd716019458f7) (aka r17100),[6e2c602](../commit/6e2c602c701628f8265030815c1a959856083ade) (aka r17102) calibration constant changed, still needs testing on BS

open sub-tickets (not bugs)
* #1136
* #1266
* #1435
* #1440

**Comment by namdre** [comment]
This meta ticket has not been used/useful for some time.
