### ISSUE TITLE
simple netconvert error: can not open the file

### ISSUE THREAD

**Issue by shiyu022** [eclipse/sumo#10452]
i don't know why, i do exactly follow the tutorial.
![屏幕快照 2022-03-31 下午4 17 36](https://user-images.githubusercontent.com/101698390/161016619-222e7611-d640-4a83-8a79-dd2619212d2f.png)
![屏幕快照 2022-03-31 下午4 23 34](https://user-images.githubusercontent.com/101698390/161016647-996194d0-c8f9-458a-a233-42c38f9c1dc5.png)
![Uploading 屏幕快照 2022-03-31 下午4.23.34.png…]()

**Comment by shiyu022** [comment]
beginner

**Comment by namdre** [comment]
your command `netconvert --node-files=hello.nod.xml ...` requires that hello.nod.xml is in the current working directory. It looks like you try to run netconvert from your home directory and maybe you put the input files in a different folder?

**Comment by angelobanse** [comment]
You are still on the wrong directory (your Home folder). 

Using `Finder` select the "未命名文件夹" Folder (where your **hello.edg.xml** and **hello.nod.xml** files are) and go to `Finder` > `Services` > `New Terminal at Folder`. Use the netconvert command in this new Terminal window.

**Comment by shiyu022** [comment]
> You are still on the wrong directory (your Home folder).
> 
> Using `Finder` select the "未命名文件夹" Folder (where your **hello.edg.xml** and **hello.nod.xml** files are) and go to `Finder` > `Services` > `New Terminal at Folder`. Use the netconvert command in this new Terminal window.
![屏幕快照 2022-03-31 下午7 02 39](https://user-images.githubusercontent.com/101698390/161041008-541ccfd0-a94d-4ca6-a567-60c53d7bcac3.png)
well, damn it

**Comment by namdre** [comment]
Note, that the error "Could not open nodes-file" has been solved. Now it appears that the contents of the file are not what they should be.

**Comment by angelobanse** [comment]
At least it is now finding the files (the "Could not open nodes-file" error no longer appears). 

Did you copy the content from the tutorial into these files? Put both **hello.edg.xml** and **hello.nod.xml** in a ZIP file and upload it here, for me to take a look.

**Comment by shiyu022** [comment]
> At least it is now finding the files (the "Could not open nodes-file" error no longer appears).
> 
> Did you copy the content from the tutorial into these files? Put both **hello.edg.xml** and **hello.nod.xml** in a ZIP file and upload it here, for me to take a look.

[未命名文件夹.zip](https://github.com/eclipse/sumo/files/8388829/default.zip)
wow, i appreciate it very much. thanks!!

**Comment by angelobanse** [comment]
It looks like you used Microsoft Word to generate those XML files. Please use Notepad or Notepad++.

**Comment by shiyu022** [comment]
> It looks like you used Microsoft Word to generate those XML files. Please use Notepad or Notepad++.



> It looks like you used Microsoft Word to generate those XML files. Please use Notepad or Notepad++.
![屏幕快照 2022-03-31 下午7 25 47](https://user-images.githubusercontent.com/101698390/161044704-247c31e9-f285-46a6-93ae-4df04cf786a4.png)
what is use is this, i'll download notepad and try again

**Comment by angelobanse** [comment]
I see. You used `TextEdit` and saved it using the "Microsoft Word 2003 (.xml)" option. This does not work. 
On Mac i would recommend you to use BBEdit or VSCode.

**Comment by shiyu022** [comment]
> I see. You used `TextEdit` and saved it using the "Microsoft Word 2003 (.xml)" option. This does not work. On Mac i would recommend you to use BBEdit or VSCode.

exactly! i did use textedit and save it as u said.

**Comment by shiyu022** [comment]
> I see. You used `TextEdit` and saved it using the "Microsoft Word 2003 (.xml)" option. This does not work. On Mac i would recommend you to use BBEdit or VSCode.

so i can't use mac textedit to draw the network, is that right?

**Comment by shiyu022** [comment]
> I see. You used `TextEdit` and saved it using the "Microsoft Word 2003 (.xml)" option. This does not work. On Mac i would recommend you to use BBEdit or VSCode.
![屏幕快照 2022-03-31 下午7 40 55](https://user-images.githubusercontent.com/101698390/161047018-90884929-0471-40bb-ba82-787ce1a1b555.png)

that's very kind of you!!! love u bro

**Comment by angelobanse** [comment]
> 

Don't use TextEdit.
Take a look at this Tutorial: https://sumo.dlr.de/docs/Tutorials/Hello_World.html - you can define and edit networks graphically using [netedit](https://sumo.dlr.de/docs/Netedit/index.html).
