### ISSUE TITLE
The simulation is not smooth in sumo-gui

### ISSUE THREAD

**Issue by guichuan0817** [eclipse/sumo#10459]
Add your issue description here.
Hi Jacob;
when I running my simulation code, the video in sumo-gui looks not very smooth, and it seems like a bit laggy,  how can I solve it? in other words, which parameters should I set to make the simulation looks more smooth?
*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**

**Comment by namdre** [comment]
The smoothness of (longitudinal) vehicle movements depends on the step length discretication (default 1s) if you want position updates with double frequency, set option **--step-length 0.5**
For the smoothness of lateral movements see https://sumo.dlr.de/docs/Simulation/SublaneModel.html#simple_continuous_lane-change_model (or activate the more complex sublane model)
