### ISSUE TITLE
Precision of FCD output

### ISSUE THREAD

**Issue by hanwiz** [eclipse/sumo#10465]
Geo-precision prevails for FCD output. This means speed or pos also has the same precision of 6 just like latitude or longitude. For these parameters, it should use the default precision 2. I think this should save some size and useless 0000 at the end for most of the other parameters.

*If possible, upload an example that shows your problem.*
`        <vehicle id="0" x="-78.695146" y="35.794948" angle="193.985693" type="tvnc" speed="24.590000" pos="5.000000" lane="48003557_0"/>`

**SUMO-version: 1.10

**operating system: Windows 10

**Comment by namdre** [comment]
You can set option **----fcd-output.attributes** to reduce the list of written attributes if you wish to conserve space.
Saving as gzipped by setting the output file name to **--fcd-output fcd.gz** is also possible.
