### ISSUE TITLE
I would like to ask a road network design question, how to gradually change from four lanes to two lanes?

### ISSUE THREAD

**Issue by xielang404** [eclipse/sumo#10469]
Add your issue description here.

The shape of the road connecting the four-lane and two-lane is similar to a trapezoid

**SUMO-version:**

**operating system:**

**Comment by namdre** [comment]
- If you want merging with equal priority, define zipper merges (https://sumo.dlr.de/docs/Netedit/neteditUsageExamples.html#creating_a_zipper_merge) with lanes 0,1 merging onto 0, and lanes 2,3 merging on to lane 1
- If you want merging similar to an on-ramp (merging flow must yield), define a lane drops (https://sumo.dlr.de/docs/Simulation/Motorways.html#reduction_in_the_number_of_lanes)

In many cases it may be more realistic to first change from 4 to 3 and then from 3 to 2.

**Comment by xielang404** [comment]
I also want to ask you a question, that is, the three-lane turns into a two-lane, which is a bottleneck problem. In reality, there should be some congestion, but the internal strategy in sumo avoids this part of the congestion. How to more realistically depict the traffic problem at the drop bottleneck?

> * 如果您想以相同的优先级合并，请定义拉链合并（https://sumo.dlr.de/docs/Netedit/neteditUsageExamples.html#creating_a_zipper_merge），车道 0,1 合并到 0，车道 2,3 合并到车道1
> * 如果您想合并类似于入口匝道（合并流必须让路），请定义车道下降（https://sumo.dlr.de/docs/Simulation/Motorways.html#reduction_in_the_number_of_lanes）
> 
> 在许多情况下，首先从 4 更改为 3，然后从 3 更改为 2 可能更现实。

I also want to ask you a question, that is, the three-lane turns into a two-lane, which is a bottleneck problem. In reality, there should be some congestion, but the internal strategy in sumo avoids this part of the congestion. How to more realistically depict the traffic problem at the drop bottleneck?

**Comment by namdre** [comment]
It depends. Is the real world situation closer to a lane drop or a zipper merge? How did you model it in sumo?
