### ISSUE TITLE
Lane Proirity issue

### ISSUE THREAD

**Issue by lola-notraffic** [eclipse/sumo#10468]
Hello,
I've uploaded the image that you may see the issue there:
The issue is that right turns (from WEST direction) are priorotized by permissive left turns from EAST direction. The problem is that when vehicles from left permissive (from EAST direction) are not driving (because the vehicles that come straight from WEST ), but still they have green: in that case vehicles on right turn still don't drive because of the priority defined globally in NET.XML file in the intersection definition. Is there any additional definition that we may add to make right turn vehicles go?
Thank you!

![Ajo Mission EBRT](https://user-images.githubusercontent.com/95179338/161416317-c31c3517-9771-45ff-ad93-22e8250cfd6e.jpg)

**SUMO-version:** 1.9.2

**operating system:** ubuntu 20.04

**Comment by namdre** [comment]
giving the right-turning traffic a green light ('G') instead of an uncontrolled link should solve this.

**Comment by namdre** [comment]
please add a comment if your problem isn't solved.
