### ISSUE TITLE
How to add a default traffic light program to a junction of an existing .net.xml file?

### ISSUE THREAD

**Issue by rahulbhadani** [eclipse/sumo#10467]
I have a `.net.xml` file at 

https://github.com/rahulbhadani/Carla_SUMO/blob/master/SUMOServer/simulations/Town03/Town03.net.xml

but there is no traffic light program associated with it.

I want to add a default TL program to junction 159.
I find that one way is to add TL program manually by editing the `<connection>` tag. 
Is there any other established procedure to add a default TL program to an existing `.net.xml`

**My SUMO version**:
Eclipse SUMO sumo Version v1_8_0+1437-c7ee52dce9

**Operating System**:
Ubuntu 20.04 LTS

**Comment by namdre** [comment]
1. open the .net.xml file in netedit
2. click on any junction that you wish to turn into a traffic light controlled junction
3. change attribute type to 'traffic_light'
4. save the network

If you need it, netedit also provides features to modify many junctions at once and to fine tune the auto-generated traffic light programs.
