### ISSUE TITLE
Bad reommendation in the installation interface (macOS)

### ISSUE THREAD

**Issue by luchengqi7** [eclipse/sumo#10464]
The recommendation given by the intaller (mac) is not a very good one. 
- First, it does not solve my problem at all (as I am already running on reletively new macOS version)
- Second, the force update option will simply interrupt your on-going work when the download is finished and just install the update. My unsaved work are lost and I suddenly cannot work with my computer at least for  20 mintues. So I don't think you should recommend user to use the force update option.

**SUMO-version:**

**operating system: macOS Monterey 12.3.1

![截屏2022-04-01 11 34 57](https://user-images.githubusercontent.com/43133404/161237624-3d0a0912-d494-4dda-836c-002cf1597c22.png)

**Comment by angelobanse** [comment]
That Error message comes directly from Homebrew, and not SUMO. 
Which version of Homebrew are you using? `brew --version`

**Comment by luchengqi7** [comment]
Oh, I see. Thanks for the information!

My homebrew version is 3.4.4

Homebrew 3.4.4
Homebrew/homebrew-core (git revision e4126999478; last commit 2022-04-01)
Homebrew/homebrew-cask (git revision 7be58e2f36; last commit 2022-04-01)

**Comment by angelobanse** [comment]
Run `brew doctor` and take a look at the warnings you get.

Homebrew needs you to have the updated version of the Xcode Command Line Tools (CLS). 
-> `softwareupdate --all --install --force`

**Comment by luchengqi7** [comment]
I just follow the suggestion returned by the brew doctor and manually downloaded the XCode Command line. Now I can install SUMO properly (excpet for the OSM web wizard). 

Thanks a lot for the help!
