### ISSUE TITLE
Cars only occupying 1 lane 

### ISSUE THREAD

**Issue by e1294jr** [eclipse/sumo#10470]
Hello, 

I am working on my third year research project and I am having an issue where my cars are only moving in one lane at a time, despite the fact that there are other empty lanes, meaning that there is unnecessary congestion. I have tried using the departLane attribute but that didn't change anything. 

If you could help me work out how to fix it then that would be amazing. 

Thank you in advance
[map.txt](https://github.com/eclipse/sumo/files/8404535/map.txt)

**Comment by namdre** [comment]
The junction types in the roundabout are wrong:
- 17660715 is type "right_before_left" but should be a traffic light
- the connections are bad. right-click the junction and select 'reset connections' in netedit
- J24 should be traffic_light and the two traffic lights ahead should be 'priority' instead
