### ISSUE TITLE
some problems in sumo_output

### ISSUE THREAD

**Issue by CSU-LHM** [eclipse/sumo#10474]
After I run the main.py in src folder,  I have two problems is in the out folder.
One is some of the values of timeLoss from the Tripinfo output is negative but others are positive. Are these negative values about attribute timeLoss normal?  Or it might be a bug from my codes.
Another problem is when I use --device.ssm.file to output the ssm_sum file, it contains only globalMeasures elements, no conflict elements. I want to get TTC and DRAC, but they are not in here. I also get an error when I use the --device.ssm.measures command.
[fcfs-intersection.zip](https://github.com/eclipse/sumo/files/8407583/fcfs-intersection.zip)

**SUMO-version:**sumo 1.11.0

**operating system:**windows 10

**Comment by CSU-LHM** [comment]
> 



> 1. The negative timeLoss may be caused by influencing vehicle speeds to make the drivers drive faster than speedLimit * speedFactor (where speedFactor is the value returned by traci.vehicle.getSpeedFactor).
> 2. set option **--device.ssm.measures 'TTC DRAC'**

So,  is there a problem(bug) with my code? Every time I run the program timeLoss has some negative values.

**Comment by CSU-LHM** [comment]
> 1. The negative timeLoss may be caused by influencing vehicle speeds to make the drivers drive faster than speedLimit * speedFactor (where speedFactor is the value returned by traci.vehicle.getSpeedFactor).
> 2. set option **--device.ssm.measures 'TTC DRAC'**

And after I use the option --device.ssm.measures 'TTC DRAC', I could get nothing.![ssm_veh_0](https://user-images.githubusercontent.com/88091384/161571583-c7ab668b-a907-4361-b3a7-705365d461c5.JPG)
![TTC_DRAC](https://user-images.githubusercontent.com/88091384/161571647-bc86142f-9c8c-439e-a0e1-f895b9517560.JPG)

**Comment by CSU-LHM** [comment]
![output_summary](https://user-images.githubusercontent.com/88091384/163676533-7c48f212-2fc0-4625-804f-631c669e3314.JPG)
In Output-Summary, what's the meaning of 'which are not waiting at a <stop>',  is this <stop> means all the vehichle of which speed is zero. Or only means the vehicle which stop at the bus stop or stop at a zebra crossing.

**Comment by behrisch** [comment]
It means vehicle which stop intentionally because they have a stop defined in their route are not taken into account.

**Comment by CSU-LHM** [comment]
> It means vehicle which stop intentionally because they have a stop defined in their route are not taken into account.

So, when the vehicle stops at a red traffic light, that doesn’t belong to the <stop> situation？

**Comment by CSU-LHM** [comment]
In python, how to use traci to set the vehicle's CarFollowing model?

**Comment by namdre** [comment]
You must have a pre-defined vType with that carFollowModel and then switch to it using `traci.vehicle.setType(vehID, typeID)`

**Comment by CSU-LHM** [comment]
1. When I use the traci.vehicle.add to add the vehicles to the sumo-gui, how to control the departure time between two cars added to the same lane? My current situation is to add a vehicle every 1 second, but I think this is too short, I'd like to chang it.
2. How can I use tracI to get vehicles added to SUMO of which arrival obey the λ distribution?

**Comment by CSU-LHM** [comment]
The type of the junction is priority. How does it work?
Why do I use the priority type intersection in my design of two-way six-lane unsignalized intersections, resulting in east-west traffic giving way to north-south traffic? That is, after the north-south vehicles through the intersection, the east-west vehicles began to pass.
How can traffic from east, west, north and south enter the intersection at the same time and have equal priority?

**Comment by namdre** [comment]
The available junction types are described at https://sumo.dlr.de/docs/Networks/PlainXML.html#node_types
If none of them fit your purpose, please describe in more details the kind of intersection rules you wish to simulate.
