### ISSUE TITLE
Colour legend in sumo-gui edge data view suggests "no data" as part of the colour scale

### ISSUE THREAD

**Issue by rjmaris** [eclipse/sumo#10507]
The legend accidentally includes the no data colour. This is a bit confusing since the colour continues to change beyond the highest value. One could believe that the colour scale would continue beyond the max value.
 I'd suggest to remove the no data colour or to show this in its own rectangle.
Refer also to #5682.

See also screenshot (no data is white here)
![sample-routes](https://user-images.githubusercontent.com/1149309/162144893-1f625947-fe48-45cd-a725-efeb2a1667b8.png)

**SUMO-version:** 1.12.0+xxx
**operating system:** Linux (should be irrelevant with this issue)

**Comment by rjmaris** [comment]
BTW: in #5682, the used font had been made bigger, but to my opinion the text font is too big....

**Comment by namdre** [comment]
On my end it looks like this:
![Bildschirmfoto von 2022-04-08 09-40-21](https://user-images.githubusercontent.com/6240630/162388881-86f89d52-329d-47d5-8c3d-51fe4423d4b8.png)

Can you provide minimal input files?

**Comment by namdre** [comment]
also: #10522

**Comment by rjmaris** [comment]
Oh, you have a "missing data" text.
Mine was generated using +1990.
But the "no data" button is inactive (greyed). Perhaps this makes the difference?
BTW: I did not manage to get this button active (but I remember, that it had been active under certain circumstances).

Regards,
Rob


Am 08.04.2022, 09:41 Uhr, schrieb Jakob Erdmann ***@***.***>:

>
> On my end it looks like this:
>
>
> Can you provide minimal input files?
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.



-- 
Dem Ingeniör ist nichts zu schwör (außer bei Force Majör)

**Comment by namdre** [comment]
The text label was lost when loading settings from file (but present when setting up the scheme manually in the gui)

**Comment by rjmaris** [comment]
I built +2058 now and see no difference (no text for "no data"). But apart of this, what is missing is a separate colour box for no data because of the suggestion of a colour scale beyond the max value.
(just written in a hurry because of an appointment)

**Comment by namdre** [comment]
possibly your gui settings file doesn't contain the label because it was loaded and saved before the fix. Try to recreate the settings from scratch and then save/load them.

**Comment by namdre** [comment]
What I meant by "from scratch" is:
- open sumo-gui without loading any stored settings
- modify the settings to your liking
- save the settings to a file

The documentation at https://sumo.dlr.de/docs/sumo-gui.html#gui-settings_files hopefully more clear now.

**Comment by rjmaris** [comment]
Okay, the text is better now, especially the separation with a new subsection (as seen by viewing the old state of the .md file).

What is very important is the following: if view/gui-settings is loaded via the -g argument, this results in an ignore of the settings, as included in sumocfg-file.
The sentence "The option --gui-settings-file is specific to sumo-gui" has been dropped but could be re-used with a hint upon the above behavioural aspect, eventually with the notion that a loaded file must be transferred into the registry, and by this means a read of viewsettings parameters from sumocfg inclusion can be read while actually using intended viewsettings via registry.

Upon testing if breakpoint settings are saved (while the appropriate tick box is ticked), I see no new entries in the viewsettings file.

Some typos:
- breapoints (missing 'k')
- schemese (was not altered, but I see it now: schemas?

In the section "Changing the appearance/visualisation of the simulation I'd suggest the following changes (bold face):

For customizing the simulation one can make changes e.g. to the background coloring, streets and vehicle appearance as well as the visualization of POIs. If you change any settings, a new settings name "custom_n" (n=number) in the top left dropdown box is created automatically. If settings are according to the intentions, then this should be renamed to your desire by means of Furthermore one can save (Save_to_registry.gif). "custom_n" is actually not saved, and would didappear upon restart. Furthermore one can and delete (Delete_from_registry.gif‎) settings to the registry or export (Save.gif) custom made settings files and load previews settings again Open_sim.png. So one can use different favorite viewsettings files for any simulation (or even for plain post-simulation of e.g. edgedata files (link necessary).

The current settings filename is also shown in a drop down menu in the top bar of the View Settingsmain window where you can switch back to default settings. quickly select between settings. Because of the limited text width, short names should be used if you create a new custom setting in the viewsettings dialog.

(Optional, or for usage in a more detailed description elsewhere)
Hint: if you customize e.g. an edgedata specific representation (in the Streets tab), you may find that the export file contains numerous other specific settings which you did not touch. You would even be able to customize settings for a range of edgedata attributes in one single step and then save and/or export this file. In this case, the settings name (scheme name) should be generic. In that case however, you would be forced to use the viewsettings dialog to change to e.g. another attribute to being represented graphically. The scheme name always refers to the whole set of all settings over all tabs!


Am 18.04.2022, 09:59 Uhr, schrieb Jakob Erdmann ***@***.***>:

**Comment by behrisch** [comment]
thank you, the typos have been fixed
