### ISSUE TITLE
Attribute named "acceleration" in lanes

### ISSUE THREAD

**Issue by redfish9** [eclipse/sumo#10504]
**Problem Description**
An attribute of lanes named "**acceleration**" occurred on the generated net, but I didn't find any description on documentation pages about it. I want to know what the parameter represents and the meaning of its value. Thanks a lot!
**Example**
```xml
        <lane index="0" acceleration="1" speed="25.00">
            <param key="origId" value="96367164 253589730 253589729"/>
        </lane>
```
**SUMO-version:**
1.12.0.
**operating system:**
Win64

**Comment by namdre** [comment]
it designates the lane as a motorway acceleration lane. This information is used by the lane change model and it's usually assigned automatically by netconvert in the ramp-guessing step.

**Comment by redfish9** [comment]
Does the value, 1,  of `acceleration` have any meaning?  Or say, is there any other values `acceleration` can take? Thanks!

**Comment by namdre** [comment]
It's a boolean (only 0 and 1 have meaning)

**Comment by redfish9** [comment]
Get it, thanks a lot!
