### ISSUE TITLE
NEMA generated detector naming leads to issues when mutiple edges in same phase

### ISSUE THREAD

**Issue by mschrader15** [eclipse/sumo#10517]
Due to https://github.com/eclipse/sumo/issues/10045#issuecomment-1022207944

**Comment by EGDoge** [comment]
Here is the error message:

`Error: laneAreaDetector detector '131_K102_D6.0' could not be build (declared twice?).
Quitting (on error).`

![image](https://user-images.githubusercontent.com/82061683/162286513-e978321e-310c-4459-8438-f243dd7f2ee5.png)

For phase 6, there ware two edges: one for thru movement and one for right turn movement.

**Comment by namdre** [comment]
That error message should only be triggered when loading xml files. If you want to replace an auto-generated detector by a custom detector with the same id, you should indicate this with a `<param>`: https://sumo.dlr.de/docs/Simulation/Traffic_Lights.html#custom_detectors_2

But maybe I'm misunderstanding the issue. In this case, please attach example input for reproducing the error.

**Comment by EGDoge** [comment]
@namdre You are correct. This error is triggered when loading xml files.

Here is a test sample network. Please look pay attention to phase 4.
![image](https://user-images.githubusercontent.com/82061683/162356474-f855e29e-04cf-4b7e-bb83-f7bf29821b6b.png)

[NEMA Example.zip](https://github.com/eclipse/sumo/files/8448258/NEMA.Example.zip)
