### ISSUE TITLE
Question: unreasonable occupancy 

### ISSUE THREAD

**Issue by wxinl** [eclipse/sumo#10525]
From my edge output data, for each edge, I was trying to extract the occupancy and I thought the maximum would be 100. However, there were edges having occ>100 while I checked the number of lanes for the edge is 1. Is this making sense? And I was wondering how occupancy was calculated? Was it density*effective vehicle length/edge length?

**Comment by namdre** [comment]
occupancy "sum of vehicle lengths" / edgeLength / laneNumber  
(averaged over the measurement interval) - multiplied by 100 to express it as a percentage.

This might exceed 100% if you have multiple vehicles driving on the same lane in parallel (i.e. in a jammed sublane simulation). If that does not describe your simulation, Please attach a minimal example for reproducing the elevated occupancy values.

**Comment by wxinl** [comment]
I think this was caused by when I converted my net from shapefile to netfile,  a bunch of short edges was produced which was way shorter than my vehicle length. For instance, the shortest edge in my network was ~13 meters, but after conversion, the edge was 0.2meter. I attached the zipp
[street_network.zip](https://github.com/eclipse/sumo/files/8477223/street_network.zip)
ed shapefile here.

**Comment by behrisch** [comment]
No there is no need to divide. Very short edges are almost always a bad idea. Can youn please share the precise command you used to convert the net?

**Comment by namdre** [comment]
> So to get the effective occupancy of the edge, I will need to divide the number by number of lanes, is that correct?
No.  If you have an edge with two lanes that are fully occupied, the occupancy is 100.  

> there were edges having occ>100
In my test, occupancy has it's max at 100 even on an edge of length 0.2m.  I'll need an example scenario including traffic, sumocfg and all input files to reproduce your finding on my end.

**Comment by wxinl** [comment]
I attached all files here.
[test.zip](https://github.com/eclipse/sumo/files/8518932/test.zip)

**Comment by namdre** [comment]
Those files do not permit running the simulation.
Please provide all the commands that must be run in sequence (i.e. for netconvert and od2trips).

**Comment by behrisch** [comment]
Closing for lack of feedback. Feel free to add another comment if you have more information or can provide the full scenario.
