### ISSUE TITLE
Cloning sumo repository gives an error 

### ISSUE THREAD

**Issue by SafrasIqbal** [eclipse/sumo#10527]
Hello All,

I get below error please help. 

`git clone --recursive https://github.com/eclipse/sumo
Cloning into 'sumo'...
remote: Enumerating objects: 1184385, done.
remote: Counting objects: 100% (60678/60678), done.
remote: Compressing objects: 100% (8886/8886), done.
error: RPC failed; curl 56 GnuTLS recv error (-9): Error decoding the received TLS packet.
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
`
![sumo_gitclone-error](https://user-images.githubusercontent.com/18607009/162632639-e5693eae-3d98-4431-961a-ac97e72c1ec7.png)

**Comment by namdre** [comment]
It's working here. Possibly, this was a temporary github outage. Please try again.
