### ISSUE TITLE
crash when merging overlapping networks with junction params

### ISSUE THREAD

**Issue by sky4994** [eclipse/sumo#10528]
Hi. First, Thanks in advance for any help.

I am trying to combine 2 or more networks using sumo's netconvert.
This is because more than one person edits each network through netedit and merges them back into one network.

This is the network I want to join now.
![인천_in,out_캡쳐_01](https://user-images.githubusercontent.com/48505033/162682744-d5abb54d-a3f0-42f2-84a6-49a7fc37b87a.png)

But when I try to combine the networks using netconvert, netconvert hangs.
![image](https://user-images.githubusercontent.com/48505033/162683516-dbd62299-7b05-4ebe-9970-962ebe8f9bc4.png)

Here is my netconvert code.
**netconvert -s test.net.xml,test2.net.xml -o re_test.net.xml**

I would be very grateful if someone could help me with this matter. Thanks in advance for your time.

**SUMO-version:** : 1.11.0

**operating system:** Window 10

**Comment by namdre** [comment]
Please attach input files (zipped) for reproducing the problem (the smaller the better).

**Comment by sky4994** [comment]
Could I send the attachment to your email?

**Comment by namdre** [comment]
Thank you. I've received the networks and can reproduce the problem.

**Comment by namdre** [comment]
https://sumo.dlr.de/docs/Downloads.php#nightly_snapshots  (anything with a timestamp of today or later)
