### ISSUE TITLE
SSL Verification Error - Unable to generate scenario

### ISSUE THREAD

**Issue by devanshee38** [eclipse/sumo#10524]
Hello! When I try to generate scenario from osmWebWizard, I face the issue below:
I am using the latest version of SUMO, have tried reinstalling certificate, disabling certificate etc, but I still face the same issue.  I would be grateful for help, it is rather urgent
![image](https://user-images.githubusercontent.com/86478053/162575685-3ca153f1-1cb2-48c1-9643-f2574498f096.png)

**Comment by devanshee38** [comment]
I have used all of the solutions in issue #9304 but they don't seem to work for me.

**Comment by behrisch** [comment]
Please send the full stack trace if possible and also report your platform /OS and which browser you use.

**Comment by behrisch** [comment]
Closing for lack of feedback. Please add another comment if you have more data.
