### ISSUE TITLE
Angular coordinates are not smooth - Vehicle dynamics

### ISSUE THREAD

**Issue by p-testolina** [eclipse/sumo#10535]
Hello,
we are working on an autonomous driving project that requires the precise position of a vehicle at each timestep as it moves throughout a map. Another requirement is that the timestep granularity should be must be fine enough (at least 1/60 s).

We are trying to use SUMO and Traci for traffic management, but the angular position of the vehicle is somewhat strange. As you can see from this picture
![yaw_pitch_roll](https://user-images.githubusercontent.com/32326757/162785170-97531820-684d-4d4b-8d3a-4f8aff78ce2b.png)
the yaw of the vehicle does not have a smooth evolution (see zoomed picture:)
![yaw_zoom](https://user-images.githubusercontent.com/32326757/162785323-9324d4e1-3185-4d76-8b7f-11d93d329834.png)
The pitch, which should be constant and always equal to 0, also presents some discontinuities that are noticeable in our experiment:
![pitch_zoom](https://user-images.githubusercontent.com/32326757/162785791-7980ccf0-0af2-4f45-bf81-a6e4022669e1.png)

I have tried different car-following models (IDM, EIDM, smartSK), step lengths, integration methods (default Euler and ballistic), and action step lengths. The issue is always present.

I attach the files to reproduce the problem (and the graphs, remove the corresponding lines if not needed)
- _E-N_Crossing_CropField.rou.xml_ contains the "ego" vehicle route, which is the only vehicle present in the simulation
- _sumo_design.sumocfg_ is the SUMO configuration file
- _Town07_Opt.net.xml_ is the SUMO network for the map. It is automatically generated from a XODR file available from the CARLA Simulator (included in the zip file as _Town07_Opt.xodr_) using the script _netconvert_carla.py_, also included.
- _test_sumo_ego_only.py_ is the Python script using Traci for the simulation.

At this point, I can't tell if I'm looking at the wrong settings, or if there is an issue with the net file. I'm fairly new to SUMO so it may be either:)

(SUMO/OS)-versions that were tested: 1.12/ubuntu 18.04, 1.4.0/ubuntu 20.04

Thank you for your help!

[mwe.zip](https://github.com/eclipse/sumo/files/8466131/mwe.zip)

**Comment by Domsall** [comment]
To get higher discretized yaw values on junctions, you can use the option `--opendrive.internal-shapes true`.
The changed netconvert_carla.py file (as .txt upload): [netconvert_carla.txt](https://github.com/eclipse/sumo/files/8466362/netconvert_carla.txt)

The map actually has z-values. But unlike the angle calculation, which uses the front and back position of the vehicle (see #8772 ), the slope calculation only uses the front position (see #8802). @namdre please correct me if I am wrong.

**Comment by p-testolina** [comment]
Thanks, @Domsall. Using the internal shapes gives indeed better results:
![yaw_zoom](https://user-images.githubusercontent.com/32326757/162815305-5bc28109-dc86-45f5-b107-44223daba9a5.png)

Regarding the pitch, do you mean that the discontinuities are present in the map z-coordinates? In the XODR file? It's supposed to be a flat road. If that is the case, I can report it to the map designers. Thanks!

(sorry but I'm new to these map formats. I cannot read them on my own)

**Comment by Domsall** [comment]
Yes, the z-coordinates must come from the OpenDrive-File (or netconvert is doing something weird).

Still, the pitch should be smooth, too. But that is already tracked in another issue.

**Comment by namdre** [comment]
Internal lanes generated by netconvert consist of 5 linear segments by default regardless of junction size or curvature. This accounts for abrupt changes in angle under close scrutiny. You can double this with option **--junctions.internal-link-detail 10**.

When importing the internal shapes directly from OpenDRIVE, the default geometry resolution is 2m per linear segment.

The above geometry resolution carries over to z data. As @domsall has pointed out, the pitch is not smoothed by averaging over the front and back position of the vehicle. Instead, only the local pitch angle at the vehicle front is taken and this varies "sharply" from line segment to line segment.

**Comment by behrisch** [comment]
Please add a comment if this did not answer your question
