### ISSUE TITLE
Question about emergency vehicles in SUMO

### ISSUE THREAD

**Issue by thinker310** [eclipse/sumo#10534]
Hello, I wonder if there is a setting which can make the emergency vehicle ignore the traffic lights at the intersection. I want to create a scenario that emergency vehicle can go through the intersection whether a red light or yellow light. Could you give me some solutions? Thank you in advance!

**Comment by namdre** [comment]
set vTypeParameters `jmDriveAfterRedTime="1000"` (https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#junction_model_parameters)

**Comment by thinker310** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
