### ISSUE TITLE
Instant vehicle speed values passed into SUMO

### ISSUE THREAD

**Issue by badjasonbourne** [eclipse/sumo#10537]
My issues are as follows: 

I have a set of collected flow data and I'm wondering if this can be used to modify the vehicle flow in SUMO. In other words, can vehicle speed values be updated each timestamp through communication? Or, can speed data for every vehicle at each timestamp be assigned using a dataset? THANKS!

SUMO-version: SUMO 1.12.0 for Win 64-bit

**Comment by namdre** [comment]
You  can remote-control speeds via the TraCI API using the commands vehicle.setSpeed and vehicle.slowDown
https://sumo.dlr.de/docs/TraCI.html
https://sumo.dlr.de/docs/TraCI/Change_Vehicle_State.html
If you have only aggregated speed data you could also use a speed calibrator: https://sumo.dlr.de/docs/Simulation/Calibrator.html

**Comment by namdre** [comment]
The easiest way is outside of sumo, coupled via TraCI (i.e. `traci.vehicle.changeLane` and `traci.vehicle.setLaneChangeMode`). However, the laneChangeModel code in the C++ core is modular and designed to accommodate additional models should you need this.
