### ISSUE TITLE
Vehicle stop at intersection suddenly

### ISSUE THREAD

**Issue by guichuan0817** [eclipse/sumo#10547]
Add your issue description here.
Hi Jacob
     when I run an intersection environment in sumo, the vehicles will stop at the intersection with no collision, as shown in the figure below, could you tell me the reason? and how to solve this problem?

![987](https://user-images.githubusercontent.com/80901665/163741900-9b67d87c-b548-4cac-bedd-95ebd13e4048.PNG)

**SUMO-version:**

**operating system:**

**Comment by namdre** [comment]
I'd guess you drove the ego vehicle onto the intersection via remote control and the other traffic stopped in response
