### ISSUE TITLE
How to generate position, speed and acceleration of each car in an output file sumo

### ISSUE THREAD

**Issue by harirRzi** [eclipse/sumo#10549]
I'm working on sumo and I want to generate the trajectory for each car of a flow in an output file. To generate an output file containing each vehicle's position, speed, acceleration, I found maybe the most suitable output file is the following link:

[](https://sumo.dlr.de/docs/Simulation/Output/AmitranOutput.html)
However after generating this output file, I see that it doesn't contain the position information for each car. I appreciate if any one can help me how can I produce these data in an output file in sumo.

Here is what it produces:

```
<trajectories xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/amitran/trajectories.xsd" timeStepSize="1000">
    <actorConfig id="6" vehicleClass="Passenger" fuel="Gasoline" emissionClass="Euro4" ref="car"/>
    <vehicle id="0" actorConfig="6" startTime="0" ref="myflow.0"/>
    <motionState vehicle="0" speed="1425" time="0" acceleration="0"/>
    <actorConfig id="7" vehicleClass="Passenger" fuel="Gasoline" emissionClass="Euro4" ref="malicious-car"/>
    <vehicle id="1" actorConfig="7" startTime="0" ref="myflowmalicious.0"/>
    <motionState vehicle="1" speed="1490" time="0" acceleration="0"/>
    <motionState vehicle="0" speed="1557" time="1000" acceleration="1317"/>
    <vehicle id="2" actorConfig="6" startTime="1000" ref="myflow1.0"/>
    <motionState vehicle="2" speed="932" time="1000" acceleration="0"/>
    <motionState vehicle="1" speed="1737" time="1000" acceleration="2465"/>
    <motionState vehicle="0" speed="1738" time="2000" acceleration="1809"/>
    <motionState vehicle="2" speed="1212" time="2000" acceleration="2799"/>
...
```

*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:macos**

**Comment by namdre** [comment]
**--fcd-output fcd.xml --fcd-output.acceleration**
https://sumo.dlr.de/docs/Simulation/Output/FCDOutput.html

**Comment by harirRzi** [comment]
Thank you very much for your help
