### ISSUE TITLE
Consider Using SonarQube

### ISSUE THREAD

**Issue by RichardKav** [eclipse/sumo#10541]
It would be useful to run the code through SonarQube (https://sonarcloud.io/projects). 

I've done this on a locally available installation of SonarQube so can't make the results available. It highlights several bugs in the code that can be found via static code analysis.

**Comment by behrisch** [comment]
Thanks for doing this and reporting back! Can you give at least a rough estimation? Are we talking about 10 or 10000 bugs? And is this of severity level "You need to make up a rather convoluted string to let SUMO crash" or "Pressing the wrong key will corrupt your disk drive"?

**Comment by RichardKav** [comment]
Hi Behrisch,

I thought I'd work out a way to show you instead, though the answer is 92 bugs in the python code. I've performed a scan using the link I suggested on the python element of the codebase see:

https://sonarcloud.io/summary/overall?id=sumo

The parameters passed to run a manual scan of this were as follows:

sonar-scanner-4.7.0.2747-windows\bin\sonar-scanner.bat -D"sonar.organization=richardkav-github" -Dsonar.login=d668b61a6bc368ea368adc4175e0b87f62b2b179 -D"sonar.projectKey=sumo" -D"sonar.inclusions=**/*.py" -D"sonar.sources=." -D"sonar.host.url=https://sonarcloud.io" -X

**Comment by behrisch** [comment]
we should also consider doing this for c++

**Comment by RichardKav** [comment]
> we should also consider doing this for c++

I've run SonarQube with a scanner suitable for c++. See the following results: 
https://sonarcloud.io/summary/overall?id=sumocplusplus

**Comment by behrisch** [comment]
Thanks a lot! Eclipse seems to have already some projects on the sonar cloud so we should find out how to add SUMO there. @RichardKav Am I right that the C++ scanner is not available for free?

**Comment by behrisch** [comment]
Just for the record: The syntax for disabling checks in the code is `// NOSONAR` or `# NOSONAR` at the end of the line because we probably won't strive for encryption safe randomness ;-) and disable those checks.

**Comment by RichardKav** [comment]
The C++ scanner is also free, but it just took a bit more configuration. The python can be scanned very easily with the commands I illustrated above, in the case of C++ however it needs to wrap around the "make" process as well. e.g.

build-wrapper-linux-x86-64 --out-dir bw-output make -j$(nproc)

sonar-scanner   -Dsonar.organization=richardkav-github   -Dsonar.projectKey=sumocplusplus   -Dsonar.sources=.   -Dsonar.cfamily.build-wrapper-output=bw-output   -Dsonar.host.url=https://sonarcloud.io -Dsonar.login="d668b61a6bc368ea368adc4175e0b87f62b2b179" -D"sonar.exclusions=**/*.java,**/*.js"

This is why I also added the exclusion in the example above for the Java code which would also need to be compiled for it to be considered in scope.

I fully understand why you use: // NOSONAR. Static code analysis like any software metrics sometimes needs to be taken with a pinch of salt. The analyser can't tell the difference between the need for a cryptographically secure random number generator and a place in the code where random is good enough. :-)

**Comment by RichardKav** [comment]
> Thanks a lot! Eclipse seems to have already some projects on the sonar cloud so we should find out how to add SUMO there. @RichardKav Am I right that the C++ scanner is not available for free?

It looks like at: [Eclipse Wiki SonarQube](https://wiki.eclipse.org/SonarQube) that you can simply put a support request in order to add an Eclipse project into [SonarCloud.io](https://www.sonarcloud.io/).

Overall SonarQube is free for Open Source Projects and is available with all languages. Only when it comes to private projects do they [charge](https://sonarcloud.io/pricing).

**Comment by behrisch** [comment]
It's finally there and updated nightly (hopefully): https://sonarcloud.io/summary/overall?id=org.eclipse.sumo The only thing missing is to use the cache because currently it takes more than 3 hours to process everything.

**Comment by RichardKav** [comment]
Glad to see that you've got it up and running.  I hope SonarQube helps you in the future.

**Comment by behrisch** [comment]
@RichardKav Thanks for your support!

Two further notes:

- we should add a badge somewhere (at least if it does not show red anymore ;-))
- we should include coverage results

**Comment by behrisch** [comment]
before making it very public we still want to fix #11054

**Comment by behrisch** [comment]
badges are there, work continues in #11766
