### ISSUE TITLE
which Wiedemann is this?

### ISSUE THREAD

**Issue by manman25** [eclipse/sumo#10544]
The Wiedemann Model car-following model is used in SUMO as a sub-module.
But there are many versions of Wiedemann Model.
Which Widemann is in MSCFModel_Wiedemann.h and MSCFModel_Wiedemann.cpp ?
Dear Dr. Behrisch, I hope you can answer my question.

![image](https://user-images.githubusercontent.com/20472753/163671247-aad0dfe9-070b-43f1-a72a-513d1c9d930c.png)
Furthermore, It is difficult for me to search the references mentioned as shown in the above png. can you tell me the details such as DOI of these papers?

**Comment by namdre** [comment]
the "Wiedemann" Model is supposed to be the 74 version (I think).
The Ostam & Tapani paper can be found at https://www.diva-portal.org/smash/get/diva2:673977/FULLTEXT01.pdf
I'm unable to find the others myself.

Note, that SUMO also provides the W99-Wiedemann Model (`carFollowModel="W99"`) 
http://w99demo.com/ (https://github.com/glgh/w99-demo)

The original Wiedeman model code is *elusive*: https://www.researchgate.net/post/Where-I-can-find-the-mathematical-formulation-of-Wiedemann-99-car-following-model

**Comment by khzannat** [comment]
Hi, I have a kind of similar query. I found "Wiedemann 74" is particularly suitable for inner-city and out-of-town weaving sections at low speeds. At higher speeds, the desired safety distance is smaller for Wiedemann 74 than for Wiedemann 99. So to implement Wiedemann 74 in sumo could you please give me additional documentation? In the given link, I found two term for Wiedemann model estimate and security, how they are related to the equation of the model?
