### ISSUE TITLE
Vehicle stop at intersection simultaneously

### ISSUE THREAD

**Issue by guichuan0817** [eclipse/sumo#10548]
Add your issue description here.
Hi Jacob
when I run an intersection environment in sumo, the vehicles(yellow and blue) will stop at the intersection simultaneously with no collision, as shown in the figure below, could you tell me the reason? and how to solve this problem?
![987](https://user-images.githubusercontent.com/80901665/163742047-c6f9a9b4-e9b1-4584-b910-5a55a375fcc7.PNG)

*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**

**Comment by namdre** [comment]
'd guess you drove the ego vehicle onto the intersection via remote control and the other traffic stopped in response

**Comment by guichuan0817** [comment]
> 'd guess you drove the ego vehicle onto the intersection via remote control and the other traffic stopped in response

yes, when the ego vehicle(blue) approach the intersection, other vehicle(yellow) also stop at the intersection simultaneously, and they(both blue and yellow) will waiting at the intersection until it reach the  episode  max steps. how should I do to solve this problem?

**Comment by namdre** [comment]
This question can only be answered in reference to all the traci commands you are sending to the vehicles. (i.e. are you using moveToXY?)

**Comment by guichuan0817** [comment]
> This question can only be answered in reference to all the traci commands you are sending to the vehicles. (i.e. are you using moveToXY?)

oh no, I don't send any traci commands to the vehicles, and the ago vehicle is controled by the RL algorithm, the other vehicle is used the defaul car-following model "Krauss", I guess whether the right-of-way cause this problem, because there is a crossroads at the intersection, but at this time , I dont't add pedestrians to the environment, the ego(blue) and the other vehicle(yellow) will still stopped  before the intersection. I'm very confused, can you tell me the reason?

**Comment by namdre** [comment]
> I don't send any traci commands to the vehicles
> the ago vehicle is controled by the RL algorithm

By what mechanism does this happen? Usually the RL algorithm uses traci for this. These are the "traci commands you are sending" ("you", refering to everything that happens outside of SUMO)

- If the RL algorithm is responsible for driving the vehicle onto the intersection the RL algorithm is responsible for continuing the turn and driving all the way across the intersection.
- Possibly, the RL algorithm drove the vehicle onto the intersection while a yellow vehicle was starting to drive across. In response to this, the yellow vehicle would stop to avoid collision.

**Comment by guichuan0817** [comment]
> > I don't send any traci commands to the vehicles
> > the ago vehicle is controled by the RL algorithm
> 
> By what mechanism does this happen? Usually the RL algorithm uses traci for this. These are the "traci commands you are sending" ("you", refering to everything that happens outside of SUMO)
> 
> * If the RL algorithm is responsible for driving the vehicle onto the intersection the RL algorithm is responsible for continuing the turn and driving all the way across the intersection.
> * Possibly, the RL algorithm drove the vehicle onto the intersection while a yellow vehicle was starting to drive across. In response to this, the yellow vehicle would stop to avoid collision.

Hi Jacob
   thanks for your reply, but when I try to debug this problem, I found that , for the surrounding vehicles  when I set the departlane=0（the outermost lane） for them,  they will not stop before the intersection as shown in the first figure below,  but when I set the departlane=1(the innermost lane) for them, the problem mentioned above will occur, the surrounding vehicle will stop before the intersection, as shown in the second figure below,  Note: the vehicles are only allowed to go straight or right-turn at the intersection.
![捕获97](https://user-images.githubusercontent.com/80901665/164397027-d2bff621-c16a-48cc-8a0b-2ca16d1472d2.PNG)
![捕获123](https://user-images.githubusercontent.com/80901665/164397048-ebb8c8de-4d92-486c-aa8a-cc536c3a6ba1.PNG)

**Comment by namdre** [comment]
Again: It's impossible to tell what is happening in your simulation without knowing all the traci commands that are sent behind the scenes (supposedly by your RL framework).
You can produce a log of commands as explained here: https://sumo.dlr.de/docs/TraCI/Interfacing_TraCI_from_Python.html#generating_a_log_of_all_traci_commands

**Comment by namdre** [comment]
@guichuan0817  If you managed to solve your problem, please add an explanation so that other users who look at this ticket can benefit from your experience
