### ISSUE TITLE
Display parameters on the sumo-gui interface

### ISSUE THREAD

**Issue by zhl555** [eclipse/sumo#10557]
Hello, I would like to ask how to add a window to the sumo-gui interface to display some real-time parameters?
For example, I want to display the speed, acceleration and other information of a vehicle at every moment on the sumo-gui interface. How can I achieve this?

**Comment by namdre** [comment]
Up to 2 attributes can be rendered on top of each vehicle by changing the *View Settings* to color or scale by that attribute and then activate the *show color value* / *show scale value* checkbox.  

https://sumo.dlr.de/docs/sumo-gui.html#textual_annotations

Custom attributes can be rendered by selecting the *show vehicle text param* checkbox if those parameters were pre-defined in the xml input or set via TraCI: 

See also https://sumo.dlr.de/docs/sumo-gui.html#plotting_object_properties
