### ISSUE TITLE
apparent freeze in SUMO-GUI due poission definition in person flows

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#10567]
See SUMO\tests\netedit\demandelements\personflow\create\poisson

**Comment by namdre** [comment]
duplicate of #4008 

The problem is unrelated to poisson flow. It's just extremely dense pedestrian traffic that causes a huge number of warnings.

**Comment by namdre** [comment]
@palvarezlopez If you wish to make the test run without congestion, set `departPos="random"` for the personFlows.
