### ISSUE TITLE
Tau for IDM

### ISSUE THREAD

**Issue by Anas-1998** [eclipse/sumo#10576]
Hello, I have been hardly trying to understand how tau is implemented inside the IDM equations.
I could not see it in the documentation, and when I opened the cpp file of IDM inside the car-following folder from src->microsim->cfmodels
https://github.com/eclipse/sumo/blob/main/src/microsim/cfmodels/MSCFModel_IDM.cpp
basically, I cant get where is tau used here, and how it affects the acceleration value, if you may just tell me which variable name is affected at which line or how it affects the IDM equations in general, I would be thankful.

**Comment by namdre** [comment]
the value of 'tau' is stored as `myHeadwayTime`. it is used in functions `insertionFollowSpeed`, `getSecureGap` and `_v`
