### ISSUE TITLE
Fuel and Emission values/plots from simulation

### ISSUE THREAD

**Issue by prasuka4** [eclipse/sumo#10575]
Hi,
I have been using SUMO for my research work and i was trying to plot emission output and fuel consumption from point A to point B.
But i'm getting a constant fuel consumption value even after completing the simulation. Is there any process to get fuel and emission values based on real time data?
Please do let me know if any other information is required
![Screenshot 2022-04-23 195542](https://user-images.githubusercontent.com/48856575/164910155-e3d4376c-95c5-4cef-867d-1fc3f498cc8d.png)

**SUMO-version:** SUMO - 1.8

**operating system:** Windows 11

**Comment by namdre** [comment]
As long as the speed remains constant, the consumption per second may remain constant as well.
If you need aggregated values for a subsecond simulation, the easiest way is to set option **--emission-output.step-scaled**.
This will write per-step values and you can simply add them up in post-processing.

**Comment by prasuka4** [comment]
Hi, Thank you for the feedback, I have tried to use the same command in sumocfg file for getting output but i'm unable to get the result and obtaining an error. could you please tell me if it is correct or not
![Screenshot 2022-04-24 170011](https://user-images.githubusercontent.com/48856575/164974305-f7ec429d-86a3-4216-8647-0c3b04822d08.png)

**Comment by namdre** [comment]
The option is only available since version 1.10.0.

**Comment by prasuka4** [comment]
Thanks for the information, I have tried to use --emission-output.step-scaled for generating emission output. Also when car-following model of CACC is used for forming platoons, the emission, fuel percentage remains same. But as per the real time test cases, the fuel consumption of platoon followers should be less than the platoon leader. Could you please help me in this regard for obtaining proper results while forming platoons

**Comment by namdre** [comment]
The effect of air resistance reduction in closely-spaced platoons is not considered by any of the current emission models in SUMO  (#10587)
