### ISSUE TITLE
Get the position of the signal light

### ISSUE THREAD

**Issue by zhl555** [eclipse/sumo#10571]
Can sumo get the position of a signal light?
 Or how to get the distance between the ego car and the traffic light that has left?(Not an upcoming traffic light on the road ahead, but a traffic light already passed by the ego vehicle)

**Comment by namdre** [comment]
TraCI is mostly tailored to retrieve dynamic aspects of the simulation.
You can use sumolib to read a network and retrieve its edges,junctions,traffic lights etc.: https://sumo.dlr.de/docs/Tools/Sumolib.html
With this you can look backward along the vehicles route to find passed traffic lights.

Alternatively, record the relative position of the traffic light before passing (vehicle.getDistance() + distance from getNextTLS) and then compute the distance from vehicle.getDistance() after passing.
