### ISSUE TITLE
make the vehicle ignore the right of the way

### ISSUE THREAD

**Issue by guichuan0817** [eclipse/sumo#10577]
Add your issue description here.
Hi Jacob
   when I run an intersection environment,  when my algorithm control the ego vehicle(red)  enter the intersection, the other vehicle (yellow) will stop before the intersection, but at the same time my  ego vehicle also stopped , they will not cross the intersection anymore, how should I do?  I try to set the speedmode for the yellow vehicle, make them ignore the right of the way, but it doesn't seem to work? can you give me some advice? I don't want all vehicles crowded at the intersection, as shown below.

![00000000000000000000000](https://user-images.githubusercontent.com/80901665/164980372-87ee02a1-a611-4f38-ac75-9cd9e4ee5f86.PNG)

*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**

**Comment by guichuan0817** [comment]
Additionally, I try to use the command traci.vehicle.setParameter(id1, "junctionModel.ignoreIDs", id2）, it also doesn't work.  my sumo-version is 1.8.0

**Comment by namdre** [comment]
- setSpeedMode only takes affect when also calling `vehicle.setSpeed` or `vehicle.slowDown`
- you could set **----ignore-junction-blocker TIME** to let the yellow vehicles ignore ego after some time
- junctionModel.ignoreIDs is only available since version 1.9.1
