### ISSUE TITLE
Permit merging short roads despite difference in street name

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#10582]
currently, the default value of **--geometry.remove.min-length** is *0*.
However, if only street names differ for a short stretch (which occurs frequently due to mapping errors in OSM), geometry should be joined by default.

**Comment by behrisch** [comment]
another option: ignore name differences if the value is not set for one part

**Comment by namdre** [comment]
One problem with th

**Comment by namdre** [comment]
> The problem with (named) bridges on unnamed motorways might also be solved by using the motorway reference if no name is available. Or it could be solved with the original idea of a length-threshold

Another idea: Motorways currently store their reference (secondary name) as `<param key="ref" .../>`. We could keep selectively preserve empty streetnames (instead of merging) if 'ref' is set.  

@behrisch  thoughts?

**Comment by behrisch** [comment]
I think those are two different problems. We could invent an option which "elevates" the reference into a street name if the name is not set but to solve the issue of bridge names determining the name of the merged street I'd prefer to do majority vote similar to #10539. So a short named part will not be merged but a long named part will be merged wirth a short unnamed one.
