### ISSUE TITLE
tag state explicitly as meso or micro (trac #1059)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#1059]
at the moment it is determined implicitly from the vehicle attribute "pos".

Migrated from http://sumo.dlr.de/ticket/1059
```json
{
    "status": "new", 
    "changetime": "2013-10-31T09:38:13Z", 
    "description": "at the moment it is determined implicitly from the vehicle attribute \"pos\".", 
    "reporter": "behrisch", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1383212293259253", 
    "component": "simulation data output", 
    "summary": "tag state explicitly as meso or micro", 
    "priority": "major", 
    "keywords": "", 
    "time": "2013-10-31T09:38:13Z", 
    "milestone": "1.0.0", 
    "owner": "", 
    "type": "enhancement"
}
```

**Comment by lbieker** [comment]
In the header of the state file it is named that the file was generated with meso:
    <mesoscopic>
        <mesosim value="true"/>
    </mesoscopic>

To make it more explicite a tag for every vehicle in every time step could be given as output that meso was used. But normally the value should not change in the ouput (only meso or micro is used). So a lot of output for just one information? Still usefull? Maybe only write the tag for meso?

**Comment by namdre** [comment]
The header is only a comment (which is not parsed). The original idea was probably to add attribute mesosim="true/false" to the toplevel element `<snapshot>`.
Not other element needs to be changed.
