### ISSUE TITLE
addTAZ.py throws an error: 'list' object has no attribute 'push_back'

### ISSUE THREAD

**Issue by hagerradi** [eclipse/sumo#10599]
Was tools/route/addTAZ.py tested? When using it, it throws this error: AttributeError: 'list' object has no attribute 'push_back'. I believe it should be "append" rather than a "push_back" for ambiguousSource and ambiguousSink lists, as i reported before for route2OD.

**SUMO-version:**
Eclipse SUMO sumo Version 1.12.0

**operating system:**
Build features: Linux-4.15.0-167-generic x86_64 GNU 9.3.0 Release Proj GUI SWIG GDAL GL2PS
Copyright (C) 2001-2022 German Aerospace Center (DLR) and others; https://sumo.dlr.de/

**Comment by namdre** [comment]
Thanks for pointing this out.
The code mirrors route2OD.py and the same answer as given in #10586 applies
