### ISSUE TITLE
adapt or remove min-distance for small web wizard scenarios

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#10592]
Especially when doing bug reports the scenario should be as small as possible and it is irritating that the web wizard does not create traffic because of the hard coded `--min-distance 300` in the randomTrips call. There are several (non-exclusive) ways to fix that

- adapt the distance to the network size
- remove the min distance completely for small networks
- always generate "fringe to fringe trips" even if they are below min distance
- make min distance configurable from the UI

**Comment by namdre** [comment]
I'm in favor of suggestion **3** (maybe configurable with a new randomTrips option --min-distance.fringe, defaulting to 0) and  suggestion **4**

**Comment by behrisch** [comment]
one more vote for 3

**Comment by namdre** [comment]
why not min-dist-fringe 0 for all classes?

**Comment by behrisch** [comment]
because it allows immediate turnarounds (at least if turnarounds are present in the net) but we can also allow it

**Comment by namdre** [comment]
I guess it's fine as it is. Most users probably won't try to extract networks that are smaller than 10m in diameter
