### ISSUE TITLE
shift person location when drawn as circles

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#10608]
currently, the circle is centered on the pedestrian position (the tip of it's nose).
This gives a misleading impression when persons are waiting a traffic light.
It would be better to center the circle on the center-of-mass of the person.

**Comment by Domsall** [comment]
that would be great, just discovered that issue yesterday.

**Comment by namdre** [comment]
there would still be some ambiguity since the circle is intentionally bigger than the physical extent of the person (to have an easy default setting for improved visibility).

**Comment by namdre** [comment]
It's somewhat consistent with vehicles which are also drawn as circle centered at their front bumper position

**Comment by Domsall** [comment]
ok, I must have misunderstood something.
I was refering to the difference between "standard" and "real world" view. In SUMO 1.10.0 the "real world" vehicle has the same position as the "standard" vehicle?!

But persons are drawn differently. In "standard" the person is drawn with like a vehicle with its front being at the corresponding lane position, but in "real world" the lane position is used as the middle of the drawn shape.

**Comment by namdre** [comment]
In the "real world" scheme, person drawing style is "simple shape" and here the nose is pretty much where the point of the triangle is. Well, actually, the nose sticks out ~2cm but the center-of-mass of the shape is consistent with the center-of-mass of the triangle.

This ticket is about the drawing style "as circles".

**Comment by Domsall** [comment]
Just checked it with the current SUMO-Version. You are right, that was an issue with SUMO 1.10.0, but not anymore.
Sorry for the mistake.
