### ISSUE TITLE
permit vehroute-output with internal edges

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#10601]
currently, the exit times alone leave some gaps in the data since they are only given for "normal" edges. Thus the time spent within junctions remains unclear.
This gap could be plugged by adding normal-edge `entryTimes`

**Comment by behrisch** [comment]
I would prefer to add something like "addInternal" which adds the internal edge names to the route output itself and the exit times (if wished). This would also cover the case of multiple internal edges and keeps the 1:1 correspondence between the edge ids and the times. The downside is that the route file is no longer readable by sumo/duarouter but this could also be fixed quite easily (or ignored with --ignore-route-errors).

**Comment by namdre** [comment]
I envisioned a new output attribute `entryTimes` which would follow the same correspondence as `exitTimes`.
While adding internal edges has the advantage of higher detail I foresee that this will lead to unpleasant support question down the line.
