### ISSUE TITLE
trafficlight.setPhaseDuration

### ISSUE THREAD

**Issue by zhousndie** [eclipse/sumo#10620]
traci.trafficlight.setPhase("gneJ3",2)
traci.trafficlight.setPhaseDuration("gneJ3",15)
print(traci.trafficlight.getPhaseDuration("gneJ3"))

 I use traci.trafficlight.setPhaseDuration("gneJ3",15) for setting new phase
duration.

When I checked the duration by
traci.trafficlight.getPhaseDuration("gneJ3"), it is showing me *20.0*
which is unchanged.

So, can you give me any idea how can I change the particular phase timing
during each simulation run?

**Comment by namdre** [comment]
setPhaseDuration is only for the current cycle whereas getPhaseDuration returns the "standard" duration that is used in subsequent cycles.
To change the latter, you have to load a new program.
This can be achieved with `trafficlight.setProgramLogic`. To create the required program object (traci.trafficlight.Logic) the easiest way is to retrieve the existing program(s) with `trafficlight.getAllProgramLogics` and modify it to your needs.

**Comment by zhousndie** [comment]
traci.trafficlight.setPhaseDuration("gneJ3",15) Has the duration been modified？

**Comment by namdre** [comment]
> traci.trafficlight.setPhaseDuration("gneJ3",15) Has the duration been modified？

This sets the **remaining** duration of the current phase to 15s (but only affects this cycle)

**Comment by zhousndie** [comment]
Thank you very much！！！
