### ISSUE TITLE
How to make accelerations change smoothly?

### ISSUE THREAD

**Issue by ZhenQin2000** [eclipse/sumo#10639]
SUMO-version: 1.12.0
operating system: Windows 10 (21H2)
Hello, in the IDM car-following model environment, I use the **traci.vehicle.slowDown(vehID="veh0", speed=0,duration=50)** command, and the resulting acceleration change graph is shown in the figure. 
![20220430_13 54 59_Accelerations](https://user-images.githubusercontent.com/101858713/166094086-981ebec4-bc56-49c8-8470-b1c843829239.png)
It can be seen that the acceleration changes very quickly. Is there a way to make it change more smoothly like the figure below?
![6](https://user-images.githubusercontent.com/101858713/166094155-8740166d-18d9-419e-8139-aeb432e8f7fd.png)
Very grateful for your help!

**Comment by namdre** [comment]
- the slowDown command only supports constant acceleration. 
- if you use vehicle.setSpeedFactor instead, at least accelerations will be smooth. However, IDM will still show almost constant deceleration
- consider using model EIDM which achieves smooth acceleration in response to modifying speedFactor.

**Comment by ZhenQin2000** [comment]
Many thanks, I will try to use EIDM.
