### ISSUE TITLE
How to set visibility distance attribute?

### ISSUE THREAD

**Issue by thinker310** [eclipse/sumo#10638]
Hello, I see the visibility distance attribute in SUMO document, but there is not a tutorial that setting this attribute and I have not found the button GUI for visibility distance in NETEDIT when I click a lane or edge. Could you tell me how to set it? Thank you!

**Comment by namdre** [comment]
https://sumo.dlr.de/docs/Netedit/neteditUsageExamples.html#setting_connection_attributes

**Comment by thinker310** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
