### ISSUE TITLE
what's the difference between dfrouter and flowrouter?

### ISSUE THREAD

**Issue by meco2020** [eclipse/sumo#10630]
Hello,  in [Introduction of flowrouter.py](https://sumo.dlr.de/docs/Tools/Detector.html), it says that  ""flowrouter.py" serves as a drop in replacement for [dfrouter](https://sumo.dlr.de/docs/dfrouter.html)", and I didn't find a file on the difference between the road traffic flows generated by the two. Whether the results using the two traffic generation methods are the same for the same road network and detector traffic data?

**Comment by namdre** [comment]
https://sumo.dlr.de/docs/Demand/Routes_from_Observation_Points.html#introduction
