### ISSUE TITLE
Traffic density problem(Sumo) How to measure the maximum density of the lane and the critical density to maintain maximum flow？

### ISSUE THREAD

**Issue by xielang404** [eclipse/sumo#10644]
Add your issue description here.
   My experimental scenario is a three-lane highway, without any congestion problems (and no accidents), here I want to test that I define the incoming road traffic by changing the vehsPerHour in the rou.xml file:
     <flow id="mix1_" begin="0" end="7200" vehsPerHour="2500" type="typedist1" route="routedist1" departLane='0'/>
     <flow id="mix2_" begin="0" end="7200" vehsPerHour="2500" type="typedist1" route="routedist1" departLane='1'/>
     <flow id="mix3_" begin="0" end="7200" vehsPerHour="2500" type="typedist1" route="routedist1" departLane='2'/>
  But I found that the vehsPerHour of each lane is defined as 1500veh/h, which is defined as 2500veh/h. The density measured in the time interval of 10s is similar. How can it be possible to generate an increase in traffic flow and lead to an increase in vehicle density?I would rather measure the maximum density of the lane and the critical density to maintain maximum flow.

**SUMO-version:1.12.0**

**operating system:  Win10**

**Comment by namdre** [comment]
see
https://sumo.dlr.de/docs/Simulation/VehicleInsertion.html#insertion_departure
https://sumo.dlr.de/docs/Simulation/RoadCapacity.html#further_headway_effects

**Comment by xielang404** [comment]
> 
Sorry, these two posts are not particularly detailed. Sumo simulates a flow of 7500veh/h (that is, in this hour of simulation time, the total number of vehicles flowing into the road network is 7500), how should I do it?

**Comment by xielang404** [comment]
> 
Sorry, these two posts are not particularly detailed. Sumo simulates the inflow of 7500veh/h (that is, in one hour of simulation time, the total number of vehicles flowing into the road network is 7500), how should I do it? @namdre

**Comment by namdre** [comment]
**--extrapolate-departpos**  
`<vType id="highFlow"  sigma="0" speedDev="0" .../>`
`<flow type="highFlow"  departSpeed="avg" .../>`

Further ways to increase flow:
`<vType minGap="1" length="3" .../>`
`   <vType tau="0.5" .../> `  with option **--step-length 0.5**
