### ISSUE TITLE
Make a car stop on the connector within an intersection

### ISSUE THREAD

**Issue by thinker310** [eclipse/sumo#10640]
Hello, I would like to make a vehicle stop at the junction proactively, are there any methods to make it?  That car had better stop in the middle of the intersection. Exactly, I mean that let a car stop on a connector, because I find connections in SUMO do not have ids, I cannot get certain connection and its information by Traci. Are there any solutions for the problem? Thank you very much!

**Comment by namdre** [comment]
See https://sumo.dlr.de/docs/sumo-gui.html#investigating_internal_edges_and_lanes
You can define stops on these "internal lanes"
