### ISSUE TITLE
broken shapefile tests

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#10646]
netconvert / polyconvert assume shapefile coordinates are WGS84 if nothing else is specified. The tests in import/shapefile however contain projected coordinates. Did this ever work? Some archaeology and discussion about user expectations might be needed.

**Comment by namdre** [comment]
archaeology: 0.12.0 was unable to load *ANY* shapefiles due to attempting to retrieve faulty options.

**Comment by namdre** [comment]
I think the current fix is fine.

**Comment by behrisch** [comment]
test should either get an adapted net or saved as is
