### ISSUE TITLE
OSM netconvert: oneway=yes & oneway:bus=no 

### ISSUE THREAD

**Issue by ambuehll** [eclipse/sumo#10650]
I wanted to point out some issue concerning oneway tags in OSM. As far as I can tell oneway is generally applied for cars, but then corrected for other modes (oneway:bus or oneway:bicycle)

I've come across some cases (in the Zurich network 45 cases), where `oneway=yes`, but `oneway:bus=no`. In this case netconvert correctly builds a bus lane in the opposite direction and car-only lanes in the oneway direction. The issue, however, is that it then that the arguments `lanes:backward` and `lanes:forward` are ignored, and the the argument lanes overrides them. 
Here a screenshot

original OSM: oneway=yes for 28682845#3 with lanes:backward=1 and lane:forward=1
<img width="139" alt="image" src="https://user-images.githubusercontent.com/48930860/166217231-c9bd9cdc-53fd-4da0-b10d-14723422f140.png">

modified OSM: oneway=no for 28682845#3 with lanes:backward=1 and lane:forward=1
<img width="154" alt="image" src="https://user-images.githubusercontent.com/48930860/166217376-6172c2d2-bcbc-46f4-8214-fdd71ae20248.png">

A potential solution is to ignore the oneway attribute when there is a oneway:bus; or not to ignore the lanes:backward/lanes:forward argument. Not sure what the best option is.

As always, many thanks for looking into this.
[files](https://drive.google.com/drive/folders/1VH8_dR-DdUhwCbiO55Pse2iEQy3eyO21?usp=sharing); current dev.

Lukas

**Comment by behrisch** [comment]
fixed via #12592
