### ISSUE TITLE
Access violation when using libtracicpp on Windows (MSVC compiler)

### ISSUE THREAD

**Issue by chrico84** [eclipse/sumo#10652]
Hello, I am building an example application that shows some of the cool features SUMO offers. The application uses libtracicpp.dll library and I'm getting an error when calling functions from this library.

The error I'm getting when calling a function from libtracicpp library is for instance:

Exception thrown at 0x00007FFD683E7360 (libtracicpp.dll) in TrafficExample.exe: 0xC0000005: Access violation reading location 0x0000000000000054.

Am I missing something or should I try something different?
I'm getting this error just on Windows, the same TrafficExample application works fine on Linux, compiled with GCC when linking with libtracicpp.so.

main.cpp:
```
... 

#include <libsumo/libtraci.h>
#include <libsumo/TraCIConstants.h>
#include <libsumo/TraCIDefs.h>

int main(int argc, char* argv[]) {
  const auto& version = libtraci::Simulation::getVersion();
  ...
```

In the application itself I'm not doing  many fancy things. 

This is my (draft ofcourse) CMake.

```
project(TrafficExample)

add_executable(TrafficExample
               main.cpp)

target_link_directories(TrafficExample PUBLIC "C:\Program Files (x86)\Eclipse\Sumo\bin")
			   
target_include_directories(TrafficExample PUBLIC "C:\Program Files (x86)\Eclipse\Sumo\include")

target_link_libraries(TrafficExample
                      libtracicpp)
```

**SUMO-version:**
Tried both 1.12 and 1.10.

**operating system:**
Windows 10. 
Compiler: Visual Studio 2017.

**Comment by behrisch** [comment]
The first command should always be libtraci::Simulation::start but you are right it should not crash

**Comment by chrico84** [comment]
Allright, I thought I got the same error before when using "start", but actually it's a different one, a SocketException. I will check it.

Unhandled exception at 0x00007FFDC3DA4F69 in TrafficExample.exe: Microsoft C++ exception: tcpip::SocketException at memory location 0x000000CF5F2FECB8.

exception.what() returns  "tcpip::Socket::getFreeSocketPort() Unable to bind socket: WSAStartup not yet called"

**Comment by chrico84** [comment]
Indeed, calling WSAStartup before libtraci::Simulation::start works for me (Release mode only for now, but I will figure out why it doesnt work for Debug build).

The application is running.

Thanks!
