### ISSUE TITLE
traffic light mode: support new phase attributes

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#10656]
all values are time values (just like duration,minDur,maxDur)
They are optional (can be left empty)

- tlType=NEMA:
  - vehExt 
  - yellow 
  - red 
- tltype=actuated
  - earliestEnd (also permits -1)
  - latestEnd  (also permits -1)

**Comment by palvarezlopez** [comment]
Netconvert tests

**Comment by namdre** [comment]
NEMA attributes should be initialized with defaults (set by new options):

- tls.nema.vehext 2
- tls.nema.yellow 3
- tls.nema.red 2

**Comment by palvarezlopez** [comment]
Fixed (and netconvert test updated)

**Comment by namdre** [comment]
The column width for 'state' is not correct for the NEMA controller. It's sized correctly for the other tlTypes
