### ISSUE TITLE
Unable to download SUMO 1.13.0 for Windows 64-bit

### ISSUE THREAD

**Issue by ZhenQin2000** [eclipse/sumo#10654]
I want to updata SUMO, but I find that when I click download I got a 404 NOT FOUND

I have tried many times and always got the same 404

![image](https://user-images.githubusercontent.com/101858713/166411777-7f4bf07f-c1aa-403b-8c32-bb42fbc46b87.png)
![image](https://user-images.githubusercontent.com/101858713/166411807-ad9274fe-40da-4e4a-af64-85b592bed741.png)

**Comment by namdre** [comment]
Please try. The release files should be fully uploaded now

**Comment by ZhenQin2000** [comment]
It works now, thanks
