### ISSUE TITLE
Bad Practice: sys.exit in library

### ISSUE THREAD

**Issue by neumannje** [eclipse/sumo#10667]
The python sumolib calls sys.exit() at several places.

Sumolib is supposed to be imported as a library and is not a standalone software. The calling code should decide how to handle exceptions.

```
$ grep 'sys.exit' -r
net/__init__.py:                sys.exit(1)
net/__init__.py:                sys.exit(1)
options.py:            sys.exit()
vehicletype.py:            sys.exit()
vehicletype.py:            sys.exit("Only one of distribution or attribute value should be defined, not both")
vehicletype.py:                sys.exit("The distribution %s is not known. Please select one of: \n%s " %
vehicletype.py:                sys.exit("Cannot parse existing %s. Error: %s" %
visualization/helpers.py:            sys.exit()
visualization/helpers.py:            sys.exit()
visualization/helpers.py:            sys.exit()
visualization/helpers.py:            sys.exit(1)
```

**Comment by schwamborn** [comment]
Actually trying to make sense of the `exit` parameter here:
https://github.com/eclipse/sumo/blob/ac567737d7d8ee411babf24145aa17e9862bbf7c/tools/sumolib/options.py#L149-L170
Especially with unreachable (?) line 261:
https://github.com/eclipse/sumo/blob/ac567737d7d8ee411babf24145aa17e9862bbf7c/tools/sumolib/options.py#L260-L262

What am I missing @behrisch @namdre ?

**Comment by namdre** [comment]
@schwamborn  The call to sys.exit() in options.py is a special case: This is only triggered when calling an application with the option --save-configuration. The expected behavior for any application is to write it's configuration and exit.

**Comment by schwamborn** [comment]
Thank you for clarifying. I already deleted my comment shortly after I figured it out. Anyway, do you suggest we leave this as is?

**Comment by namdre** [comment]
Yes. I'd say the option module is working as intended (also, this isn't a case of exception handling)

**Comment by behrisch** [comment]
I think we should in most cases raise an ValueError instead of a generic Exception here

**Comment by namdre** [comment]
Also, the tools that use the library should catch the exception or the user will see a stack trace instead of a clean error.
