### ISSUE TITLE
[BUG] Crash on missing rtree in environment without stderr

### ISSUE THREAD

**Issue by neumannje** [eclipse/sumo#10666]
Using sumolib.net.getNeighboringEdges in python, when
- rtree is not installed
- stderr is not available (None)

sumolib crashes: AttributeError: 'NoneType' object has no attribute 'write'

This is caused by https://github.com/eclipse/sumo/blob/main/tools/sumolib/net/__init__.py

```
288 except ImportError:
289   if allowFallback:
290     if not self.hasWarnedAboutMissingRTree:
291       sys.stderr.write("Warning: Module 'rtree' not available. Using brute-force fallback\n")
292       self.hasWarnedAboutMissingRTree = True
```

This environment is not rare or unlikely to encounter. The problem was encountered when using sumolib inside a QGIS Plugin.
When the QGIS Python Console is not open, sys.stderr is not available (sys.stderr == None). 

Possible fix:
- Check if sys.stderr is available, if not ignore printing the warning.
```
288 except ImportError:
289   if allowFallback:
290     if not self.hasWarnedAboutMissingRTree:
291       sys.stderr.write("Warning: Module 'rtree' not available. Using brute-force fallback\n") if sys.stderr else ...
292       self.hasWarnedAboutMissingRTree = True
293     else:
294       sys.stderr.write("Error: Module 'rtree' not available.\n") if sys.stderr else ...
295       sys.exit(1)
```

- Add an option to suppress the warning
```
276 def getNeighboringEdges(self, x, y, r=0.1, includeJunctions=True,
277          allowFallback=True, supressWarning=False):
[...]
288   except ImportError:
289     if allowFallback:
290       if not self.hasWarnedAboutMissingRTree:
291         sys.stderr.write("Warning: Module 'rtree' not available. Using brute-force fallback\n") if not supressWarning else ...
292         self.hasWarnedAboutMissingRTree = True
293     else:
294       sys.stderr.write("Error: Module 'rtree' not available.\n") if not supressWarning else ...
295       sys.exit(1)
```

**SUMO-version:**
```
>>> sumolib.version.gitDescribe()
'v1_12_0+0000-800cb422fa4'
```
**operating system:**
N/A

**Comment by behrisch** [comment]
fixed in 501bae7 It should be possible to disable warnings. Please add a comment if it does not help in your case
