### ISSUE TITLE
actuated: detectors "miss" vehicles because the detectors are too short

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#10668]
in sumo inductionLoops have no length and this may result in missed detection of waiting vehicles (if the detector happens to be located in the gap between vehicles. In reality, the induction loops at actuated traffic lights are often ~2m long.

Possible mitigation: use lanearea detectors for 'actuated'

**Comment by behrisch** [comment]
benchmarks needed to make sure lanearea detectors do not have a big performance penalty

**Comment by namdre** [comment]
if benchmarks show a problem we could also give inductionLoops an optional length (since they have one in reality anyway)

**Comment by namdre** [comment]
switching the detector type would break backward compatibility for anybody who relies on the outputs or access the default detectors via TraCI. Since adding an optional length to the inductionLoop is trivial to implement, I prefer to go this way.
