### ISSUE TITLE
editing parameters does not mark a traffic light as changed

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#10673]
If I only change parameters the traffic light does not seem to recognize it has been modified. I cannot save the changes.

**Comment by palvarezlopez** [comment]
Only for dialog

**Comment by namdre** [comment]
Could it be that this also marks the traffic light as changed if the dialog was closed with 'ok' without doing any changes?

**Comment by palvarezlopez** [comment]
Yes, I fix it
