### ISSUE TITLE
Build Error: undefined reference to `libsumo'

### ISSUE THREAD

**Issue by arun1dubey** [eclipse/sumo#10675]
SUMO-version:1.12

Ubuntu

[ 82%] Built target netedit_frames_common
[ 83%] Built target netedit_frames_network
/usr/bin/ld: Consolidate compiler generated dependencies of target netedit_frames_data
CMakeFiles/testlibsumo.dir/testlibsumo_main.cpp.o: in function `main':
/home/arun/Documents/Twin_Project/sumo/src/traci_testclient/testlibsumo_main.cpp:33: **undefined reference to `libsumo::Simulation::load(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)'**
/usr/bin/ld: /home/arun/Documents/Twin_Project/sumo/src/traci_testclient/testlibsumo_main.cpp:38: undefined reference to `libsumo::Simulation::start(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, void*)'
/usr/bin/ld: /home/arun/Documents/Twin_Project/sumo/src/traci_testclient/testlibsumo_main.cpp:40: **undefined reference to `libsumo::Simulation::close(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'**
[ 83%] Building CXX object src/netedit/elements/CMakeFiles/netedit_elements.dir/GNEAttributeProperties.cpp.o
[ 83%] Built target netedit_frames_demand
collect2: error: ld returned 1 exit status
make[2]: *** [src/traci_testclient/CMakeFiles/testlibsumo.dir/build.make:101: ../../bin/testlibsumoD] Error 1
make[1]: *** [CMakeFiles/Makefile2:4080: src/traci_testclient/CMakeFiles/testlibsumo.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 83%] Building CXX object src/netedit/elements/CMakeFiles/netedit_elements.dir/GNETagProperties.cpp.o
[ 84%] Built target netedit_frames_data

**Comment by behrisch** [comment]
Can you please give a little more context such as where you downloaded the source and in which way you called cmake / make?

**Comment by arun1dubey** [comment]
Thanks for your response, I'm following the steps described on _https://sumo.dlr.de/docs/Installing/Linux_Build.html_ 
ubuntu version I'm using is Ubuntu 22.04 LTS

**Comment by behrisch** [comment]
And you downloaded this file for the sources: https://sumo.dlr.de/releases/1.12.0/sumo-src-1.12.0.tar.gz ?

**Comment by arun1dubey** [comment]
I'm using: " git clone --recursive https://github.com/eclipse/sumo" to download this file from the source.

**Comment by behrisch** [comment]
Okay, I was asking because you mentioned 1.12 as SUMO version. And did you modify the cmake call? I am asking because it appears as if you are doing a debug build. Or just a plain `cmake ../..`

**Comment by arun1dubey** [comment]
I'm getting it with debug build. But when doing a normal build, I get even if everything is there in place:
cc1plus: fatal error: usr/local/share/sumo/src/utils/traci/TraCIAPI.cpp: No such file or directory
compilation terminated.
cc1plus: fatal error: usr/local/share/sumo/src/foreign/tcpip/socket.cpp: No such file or directory
compilation terminated.
cc1plus: fatal error: usr/local/share/sumo/src/foreign/tcpip/storage.cpp: No such file or directory
compilation terminated.

**Comment by behrisch** [comment]
Can you imagine why the compiler is looking into  usr/local/share ?

**Comment by behrisch** [comment]
This seems to be a very strange setup with sources in /usr/local/share. Please leave another comment if you can give more details
