### ISSUE TITLE
A question about the break in the intersection

### ISSUE THREAD

**Issue by JaydenGao-gjd** [eclipse/sumo#10681]
Add your issue description here.

*If possible, upload an example that shows your problem.*

**SUMO-version: 1.12

**operating system: win10
Hello, I am building an intersection in SUMOv1.12. But I found the dead lock as shown in the figure. How to solve it except the all-red time setting? Thank u.
![屏幕截图 2022-05-05 183827](https://user-images.githubusercontent.com/56961646/166907318-0c5ca856-c1ba-45d4-b032-2a3be2e87265.png)

**Comment by namdre** [comment]
A *brute-force* fix is to set sumo option **--ignore-junction-blocker TIME**  to ignore the blocked vehicles after the given TIME
