### ISSUE TITLE
TrafficLight

### ISSUE THREAD

**Issue by zhousndie** [eclipse/sumo#10680]
I want to use the traffic flow to allocate the green light duration, but the traffic flow will get stuck during the simulation. Can you help me how to modify the code?

while step<3600:
        traci.simulationStep()

#        time.sleep(0.5)
        

        Qsum=traci.edge.getLastStepVehicleNumber('E2')+traci.edge.getLastStepVehicleNumber('E4')+
        traci.edge.getLastStepVehicleNumber('E1')+traci.edge.getLastStepVehicleNumber('E3')
       
        if traci.trafficlight.getPhase(TLid) == 0:
            
           Q1=traci.lane.getLastStepVehicleNumber('E2_0')+traci.lane.getLastStepVehicleNumber('E2_1')+
           traci.lane.getLastStepVehicleNumber('E2_2')+traci.lane.getLastStepVehicleNumber('E2_3')+
           traci.lane.getLastStepVehicleNumber('E2_4')+traci.lane.getLastStepVehicleNumber('E4_0')+
           traci.lane.getLastStepVehicleNumber('E4_1')+traci.lane.getLastStepVehicleNumber('E4_2')+
           traci.lane.getLastStepVehicleNumber('E4_3')+traci.lane.getLastStepVehicleNumber('E4_4')
            t1=(T-4*ty)*(Q1/Qsum)
            Q_1 = Q1
            traci.trafficlight.setPhaseDuration(TLid,(T-12)*(Q_1/Qsum))
            traci.trafficlight.setPhase(TLid, 1)

        if traci.trafficlight.getPhase(TLid) == 2:
            Q2=traci.lane.getLastStepVehicleNumber('E2_5')+traci.lane.getLastStepVehicleNumber('E4_5')
            t2=(T-4*ty)*(Q1/Qsum)
            Q_2 = Q2 + (t1+ty)*R
            traci.trafficlight.setPhaseDuration(TLid,(T-12)*(Q_2/Qsum))
            traci.trafficlight.setPhase(TLid, 3)

       if traci.trafficlight.getPhase(TLid) == 4:
            Q3=traci.lane.getLastStepVehicleNumber('E1_0')+traci.lane.getLastStepVehicleNumber('E1_1')+
            traci.lane.getLastStepVehicleNumber('E1_2')+traci.lane.getLastStepVehicleNumber('E3_0')+
            traci.lane.getLastStepVehicleNumber('E3_1')+traci.lane.getLastStepVehicleNumber('E3_2')
            t3=(T-4*ty)*(Q1/Qsum)
            Q_3 = Q3 + (t1+t2+2*ty)*R
            traci.trafficlight.setPhaseDuration(TLid,(T-12)*(Q_3/Qsum))
            traci.trafficlight.setPhase(TLid, 5)
            
      if traci.trafficlight.getPhase(TLid) == 6:
            Q4=traci.lane.getLastStepVehicleNumber('E1_3')+traci.lane.getLastStepVehicleNumber('E3_3')
            t4=(T-4*ty)*(Q1/Qsum)
            Q_4 = Q4 + (t1+t2+t3+3*ty)*R
            traci.trafficlight.setPhaseDuration(TLid,(T-12)*(Q_4/Qsum))
            traci.trafficlight.setPhase(TLid, 7)
            
    step=step+1
    traci.close()
![999](https://user-images.githubusercontent.com/66585602/166900871-ced8e787-0076-4a5d-b4ca-3485ed571bfc.png)

**Comment by namdre** [comment]
Your screenshot only shows that there is more traffic than the controller can handle.
Unless you can provide an argument that this is somehow a bug in sumo, then the following applies: https://sumo.dlr.de/docs/FAQ.html#i_want_to_do_a_project_with_sumo_can_you_help_me_with_the_implementation
