### ISSUE TITLE
Can not set the vehicle's acceleration to a negative value 

### ISSUE THREAD

**Issue by ZhenQin2000** [eclipse/sumo#10693]
When I use **traci.vehicle.setacceleration**, it says that Acceleration must not be negative.
So how can I set the vehicle's acceleration to a negative value ?

**SUMO-version:1.13.0**

**operating system:Windows 10**

**Comment by ZhenQin2000** [comment]
I really need to fix the now : ). Is there anyway that I can fix the bug on my compuer?
Maybe I can install the **Latest Development Version**?

**Comment by namdre** [comment]
you can download the latest development version which includes the fix at https://sumo.dlr.de/docs/Downloads.php#nightly_snapshots
