### ISSUE TITLE
The 'mode' parameter passed to function getNeighbors

### ISSUE THREAD

**Issue by redfish9** [eclipse/sumo#10690]
What does the bitset mean in the `mode` parameter of getNeighbors?  I wanna request SUMO for the distance of the right following vehicle then what bitset shall I pass? 
BTW, what's the system of the bitset,  whether a BIN or HEX?

**Comment by redfish9** [comment]
And what does the bit3 parameter blocking mean?

**Comment by namdre** [comment]
it's mode=1.
"blocking" means vehicles that undercut the "secure gap" of the follower vehicle in case of a lane change in that direction.

see https://sumo.dlr.de/docs/TraCI/Vehicle_Value_Retrieval.html#neighboring_vehicles_0xbf
and https://github.com/eclipse/sumo/blob/5da43dba5145845b9641e5e1874d072086e0096a/tools/traci/_vehicle.py#L572-L580
