### ISSUE TITLE
OpenDRIVE: crash on encountering road object validity record

### ISSUE THREAD

**Issue by Yunfei-Zhang** [eclipse/sumo#10701]
The `netconvert` function of the latest SUMO version cannot read the OpenDRIVE network as instructed in [SUMO OpenDRIVE docu](https://sumo.dlr.de/docs/Networks/Import/OpenDRIVE.html). If I specify the `verbose`, the following message will appear without any error:

```shell
netconvert --opendrive <OpenDRIVE file> -o mySUMOnetwork.net.xml -v True
Parsing types from 'C:\Program Files (x86)\Eclipse\Sumo\/data/typemap/opendriveNetconvert.typ.xml' ... done.
Parsing opendrive from <OpenDRIVE file> ...
```

**SUMO-version: 1.13.0 for Windows 64-bit**

**operating system: Windows 10 Enterprise**

**OpenDRIVE version: openDRIVE 1.6**

Thanks in advance! ❤

**Comment by namdre** [comment]
- Is this problem specific to 1.13.0 or does it also show up with older versions?
- can you provide the opendrive input file? You may send it privately if you do not wish to attach it here in public.

**Comment by Yunfei-Zhang** [comment]
> Is this problem specific to 1.13.0 or does it also show up with older versions?
I tried older versions and did no work either.

> can you provide the opendrive input file? You may send it privately if you do not wish to attach it here in public.
Sent! Thanks Jakob!
