### ISSUE TITLE
crash when importing plain-xml with self-looped edge and re-occuring edge ids

### ISSUE THREAD

**Issue by ftpot** [eclipse/sumo#10700]
The text displayed on the command line is as follows：
Warning: Cannot read local schema 'D:\Program Files\sumo-git\tools/data/xsd/additional_file.xsd', will try website lookup.
Warning: Cannot read local schema 'D:\Program Files\sumo-git\tools/data/xsd/routes_file.xsd', will try website lookup.
Warning: Cannot read local schema 'D:\Program Files\sumo-git\tools/data/xsd/net_file.xsd', will try website lookup.
Warning: Edge's '42935265' from- and to-node are at the same position.
Warning: Edge's '209742641' from- and to-node are at the same position.
Warning:  Removing self-looping edge '42935265'
Warning:  Removing self-looping edge '209742641'
Warning: 2 self-looping edge(s) removed.
Warning: Shape for junction '219761' has distance 27.73 to its given position.
Warning: Shape for junction '22426' has distance 73.02 to its given position.
Warning: Shape for junction '24110' has distance 76.33 to its given position.
Warning: Shape for junction '28553' has distance 20.40 to its given position.
Warning: Shape for junction '293530' has distance 22.34 to its given position.

-----------------------------------------------------------------------------------
The data is exported from the Networkx data of Python. As mentioned above, the output result has neither “error” nor “success”.

**Comment by ftpot** [comment]
I have used the option --verbose, and the exact command as follow:
netconvert osm.netccfg

the text in osm,netccfg as follow:
<?xml version="1.0" encoding="UTF-8"?>

<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/netconvertConfiguration.xsd">

    <input>
        <node-files value="osm.nod.xml"/>
        <edge-files value="osm.edg.xml"/>
        <type-files value="osm.typ.xml"/>
    </input>

    <projection>
        <proj.utm value="true"/>
    </projection>
	
    <output>
        <write-license value="true"/>
        <output-file value="osm.net.xml"/>
    </output>

</configuration>

the picture of the result as follow:
![CW4EO$1_Y%8BHTUCGC7GXVT](https://user-images.githubusercontent.com/87177796/167752696-d2bdd5b2-5d35-4f35-b219-9c4d75186daf.png)

**Comment by namdre** [comment]
Can you zip and attach the xml input files?

**Comment by ftpot** [comment]
[SUMO_netconvert.zip](https://github.com/eclipse/sumo/files/8667169/SUMO_netconvert.zip)
