### ISSUE TITLE
Add button "extendFrame" to FXGroupBoxModule

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#10717]
Will be used in TLS Frame

**Comment by namdre** [comment]
I think this should be a toggle button to revert to the previous frame width

**Comment by namdre** [comment]
frame extension is not wide enough for tlType 'actuated' and 'NEMA'  (i.e. sumo/tls/actuated/basic/net.net.xml)

**Comment by palvarezlopez** [comment]
Fixed in #11241
