### ISSUE TITLE
Emergency Braking

### ISSUE THREAD

**Issue by Anas-1998** [eclipse/sumo#10711]
Hello, I would like to know what is the condition for activating the emergency braking, as in the documentation its only mentioned that its activated to avoid accidents, but is there a specific equation to satisfy? I hope if it exists anywhere in the documentation, or code somewhere if you can point me to.
Thanks in advance

**Comment by namdre** [comment]
The "safe" velocity is computed by the configured carFollowModel  so the exact code location therefore depends on the model choice.
The model code can be found in src/microsim/cfmodels

For details on the warning, see https://sumo.dlr.de/docs/Car-Following-Models.html#decel_apparentdecel_emergencydecel
