### ISSUE TITLE
TraCI findRoute reports valid route although starting edge is internal

### ISSUE THREAD

**Issue by hawxkeye** [eclipse/sumo#10722]
When using the findRoute call via TraCI, it reports a valid route between an internal starting edge and an actual end edge.
The behavior does not appear if both start and end edge are internal, neither when only the end edge is internal.

#### Correct behavior:
Edges tried:  F4F5 :D0_1
Stage(type=3, edges=(), travelTime=0.0, cost=0.0, length=0.0, depart=INVALID, departPos=INVALID, arrivalPos=INVALID)

Edges tried:  :C4_3 :D2_8
Stage(type=3, edges=(), travelTime=0.0, cost=0.0, length=0.0, depart=INVALID, departPos=INVALID, arrivalPos=INVALID)

#### Wrong behavior:
Edges tried:  :E0_11 B1C1
Stage(type=3, edges=(':E0_11', 'E0D0', 'D0C0', 'C0B0', 'B0B1', 'B1C1'), travelTime=145.7936191724194, cost=145.7936191724194, length=1977.2000000000003, depart=INVALID, departPos=INVALID, arrivalPos=INVALID)

#### Additional infos 
SUMO Version 1.8.0
TraCI Interface via Python 3.8
Tested on a grid network, with random selection of start and end edges.

**Comment by namdre** [comment]
This is a feature rather than a bug:  Vehicles which are currently on an intersection should be able to find a route (and the possible routes do depend on the starting internal edge).

It is even possible to define a route that starts with an internal edge in a route-file or via TraCI.
