### ISSUE TITLE
How to judge the lane and edge values of a coordinate point？

### ISSUE THREAD

**Issue by Jianhua-Jiang** [eclipse/sumo#10723]
I have a specific coordinate. How can I get the lane and edge information where the point is located？

**Comment by namdre** [comment]
see https://sumo.dlr.de/docs/Geo-Coordinates.html#mapping_geo-coordinates

**Comment by Yangangren** [comment]
> I have a specific coordinate. How can I get the lane and edge information where the point is located？



> see https://sumo.dlr.de/docs/Geo-Coordinates.html#mapping_geo-coordinates

Thanks for your answer very much!
