### ISSUE TITLE
noise in randomTrips

### ISSUE THREAD

**Issue by Oritchimaru** [eclipse/sumo#10735]
**This is not an issue** but a recommendation.

It would be awesome to be able to pass an argument while calling randomTrips.py that will add noise to the vehicles arrival times (let's say like the already implemented --random option) but in a measurable manner.

For example, let's say we have vehicles join the network with a rate of 1 vehicle per 4 secs. If we were to set this noise factor to 0.5, a vehicle would join the network in a spectrum [-0.5, 4*t, 0.5] uniformly.

That's not an issue, because someone can really easily access the .trips and .rou and change these values by hand.

I'm just recommending this as I'm understanding that this feature really comes in handy when working with AI, ML or RL projects and you want a more generalized learning. Having this procedure done automatically saved you one or two external scripts!

Looking forward listening to your opinion about this and If you think it can be implemented as it is now but with an easier way than what I said earlier, let me know!

Thanks for your time!

**Comment by namdre** [comment]
Thanks for the recommendation.

This very feature is available via sumo option --random-depart-offset X.
While it only sets a positive delay (random distributed in [0, X]) this is equivalent to symmetrical noise when shifting the original departures back by X/2.
