### ISSUE TITLE
Python Sumolib lane.getOutgoing documentation

### ISSUE THREAD

**Issue by neumannje** [eclipse/sumo#10730]
The Method `Lane.getIncoming` returns a list of Lanes connection with lane. 
On the other hand the method `Lane.getOutgoing` returns a list of `Connection`s.
(https://sumo.dlr.de/daily/pydoc/sumolib.net.lane.html#Lane)

I expect the method `Lane.getOutgoing` to have a equivalent function to `Lane.getIncoming`.

To highlight this difference, the method should be documented properly.

Additionally a method, similar to `Lane.getIncoming`, which returns all outgoing lanes of a particular Lane-Object could be helpful. (Something along the lines of `Lane.getOutgoingLanes`)

ATM I use:
```
[conn.getToLane() for conn in lane.getOutgoing()]
```
I am not familiar with the details of the `Connection` Object and don't know if I am missing something with this implementation.

Since I mix two different topics in this issue I can split it up if required.

**Comment by bcoueraud87** [comment]
My ticket I guess :)

**Comment by namdre** [comment]
fixed in 0976e96a9cc6431e2aa0582998b91bc116550461
