### ISSUE TITLE
Crash taking SVG picture in Windows

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#10731]
Related with new GL2PS version

**Comment by palvarezlopez** [comment]
Disable PNG support in GL2PS fix the problem. New GL2PS version in SUMOLibraries avaliable

**Comment by namdre** [comment]
how is PNG support related to SVG export?
Does the latest library version support both formats?

**Comment by palvarezlopez** [comment]
@namdre yes, supports SVG, PS and PNG. I think, the problem is that FOX and GL2PS is compilated with LibPNG, and this could generate an incompatibility. Now if we want to save picture in PNG format, SUMO uses FOX Toolkit, and if we want to save in SVG, SUMO uses GL2PS.
