### ISSUE TITLE
taxi simulation with traci in sumo (passengers are not picked up)

### ISSUE THREAD

**Issue by marayaaghnia** [eclipse/sumo#10738]
I have a taxi simulation with sumo. When starting the simulation directly on the sumo config file, the taxi could pickup and drop off the passengers. But when I'm trying to use TraCI by the code below, the taxis couldn't pickup the passengers. What can I do?

[---code below---]
import os
import sys
import optparse

if 'SUMO_HOME' in os.environ:
    tools = os.path.join(os.environ['SUMO_HOME'], 'tools')
    sys.path.append(tools)
else:
    sys.exit("please declare environment variable 'SUMO_HOME'")

from sumolib import checkBinary 
import traci
import random

def run():
    step = 0
    while step < 86400:
        traci.simulationStep()
        step += 1
        traci.addStepListener(traci.StepListener)

    rebalanced_veh = {'-5670924#1': [], '5670651#5': [], '5672138#4': []}
    nr_at_station = {'-5670924#1': 0, '5670651#5': 0, '5672138#4': 0} 
   
    def dist_to_edge(vehId, edgeId):
        try:
            start_edge = traci.vehicle.getLaneID(vehId)
            start_edge = start_edge[:len(start_edge)-2]
            if start_edge != '':
                stage = traci.simulation.findRoute(fromEdge=start_edge, toEdge=edgeId, vType=traci.vehicle.getTypeID(vehId))
                dist = stage.length
            else:
                tmp_target = traci.vehicle.getRoute(vehId)[-1]
                try: 
                    traci.vehicle.changeTarget(vehID=vehId, edgeID=edgeId)
                    dist = traci.vehicle.getDrivingDistance(vehID=vehId, edgeID=edgeId, pos=0)
                    traci.vehicle.changeTarget(vehID=vehId, edgeID=tmp_target)
                except traci.exceptions.TraCIException as e:
                    #do something with the exception here if desired
                    pass
                 
        except traci.exceptions.TraCIException as e:
            print(e)
            tmp_target = traci.vehicle.getRoute(vehId)[-1]
            try: 
                traci.vehicle.changeTarget(vehID=vehId, edgeID=edgeId, pos=0)
                dist = traci.vehicle.getDrivingDistance(vehID=vehId, edgeID=edgeId, pos=0)
                traci.vehicle.changeTarget(vehID=vehId, edgeID=tmp_target)
            except traci.exceptions.TraCIException as e:
                pass
        return dist
         
        
    def rebalance(method, max_occ=1):
        global rebalanced_veh
        global nr_at_station
         
        new_idle_veh = []
        max_occ = 5 * max_occ
        prt_stops = ['-5670924#1', '5670651#5', '5672138#4']
            
        fleet = traci.vehicle.getTaxiFleet(0)
        veh_ids_sum = []
        for veh_ids in rebalanced_veh.values():
            veh_ids_sum += veh_ids
        veh_ids_sum = list(set(veh_ids_sum))
        for v in fleet:
            if not traci.vehicle.isSToppedParking(v):
                if v not in new_idle_veh:
                    if v not in veh_ids_sum:
                        new_idle_veh.append(v)
        for waiting_vehs in rebalanced_veh.values():
            for veh in waiting_vehs:
                try:
                    if traci.vehicle.isStoppedParking(veh):
                       waiting_vehs.remove(veh)
                    if veh in traci.vehicle.getTaxiFleet(1):
                        waiting_vehs.remove(veh)
                    if veh in traci.vehicle.getTaxiFleet(2):
                        waiting_vehs.remove(veh)
                except traci.exceptions.TraCIException as e:
                    if 'is not known' in str(e):
                        waiting_vehs.remove(veh)
                    pass
                  
        for stop in prt_stops:
            nr_at_station[stop] = traci.parkingarea.getVehicleCount(stop) + len(rebalanced_veh[stop])
            
        for veh in new_idle_veh:
            found_parking = 0 #the vehicle has not found a slot in one of the stations
            min_dist = float("inf") #set the minimal distance to inf for each vehicle
            for stop in prt_stops: #check the distance to the stop
                dist_to_stop = dist_to_edge(veh, stop)
                if 0 < dist_to_stop < min_dist:
                    if nr_at_station[stop] < max_occ:
                        found_parking = 1
                        min_dist = dist_to_stop
                        new_destination = stop
                
            if found_parking > 0:
                try:
                    rebalanced_veh[new_destination].append(veh)
                    traci.vehicle.changeTarget(vehID=veh, edgeID=new_destination)
                    traci.vehicle.setParkingAreaStop(vehID=veh, stopID=new_destination, duration=999999, flags=1)
                    nr_at_station[new_destination] = traci.parkingarea.getVehicleCount(stop) + len(rebalanced_veh[new_destination])
                except traci.exceptions.TraCIException or traci.exceptions.FatalTraCIError:
                    pass
        
        if method == 'random_idling':
            return
                        
        elif method == 'park_closest_idling':
            new_idle_veh = []
            max_occ = 5 * max_occ
            prt_stops = ['-5670924#1', '5670651#5', '5672138#4']

            fleet = traci.vehicle.getTaxiFleet(0)
            veh_ids_sum = []
            for veh_ids in rebalanced_veh.values():
                veh_ids_sum += veh_ids
            veh_ids_sum = list(set(veh_ids_sum))
            for v in fleet:
                if not traci.vehicle.isStoppedParking(v):
                    if v not in new_idle_veh:
                        if v not in veh_ids_sum:
                            new_idle_veh.append(v)
            for waiting_vehs in rebalanced_veh.values():
                for veh in waiting_vehs:
                    try:
                        if traci.vehicle.isStoppedParking(veh):
                            waiting_vehs.remove(veh)
                        if veh in traci.vehicle.getTaxiFleet(1):
                            waiting_vehs.remove(veh)
                        if veh in traci.vehicle.getTaxiFleet(2):
                            waiting_vehs.remove(veh)
                    except traci.exceptions.TraCIException as e:
                        if 'is not known' in str(e):
                            waiting_vehs.remove(veh)
                        pass

            for stop in prt_stops:
                nr_at_station[stop] = traci.parkingarea.getVehicleCount(stop) + len(rebalanced_veh[stop])

            for veh in new_idle_veh:
                found_parking = 0  
                min_dist = float("inf")  
                for stop in prt_stops: 
                    dist_to_stop = dist_to_edge(veh, stop)
                    if 0 < dist_to_stop < min_dist:
                        if nr_at_station[stop] < max_occ:
                            found_parking = 1
                            min_dist = dist_to_stop
                            new_destination = stop

                if found_parking > 0:
                    try:
                        rebalanced_veh[new_destination].append(veh)
                        traci.vehicle.changeTarget(vehID=veh, edgeID=new_destination)
                        traci.vehicle.setParkingAreaStop(vehID=veh, stopID=new_destination, duration=999999, flags=1)
                        nr_at_station[new_destination] = traci.parkingarea.getVehicleCount(stop) + len(rebalanced_veh[new_destination])
                    except traci.exceptions.TraCIException or traci.exceptions.FatalTraCIError:
                        pass
                
    def dispatch(strategy):
        free_taxis = traci.vehicle.getTaxiFleet(flag=0)
        reservations = traci.person.getTaxiReservations(1)
        if strategy == "mockup":
            for reservation in reservations:
                try:
                    traci.vehicle.dispatchTaxi(random.choice(free_taxis), reservation.id)
                except traci.exceptions.TraCIException:
                    pass
        return   
    traci.close()
    sys.stdout.flush()
    
def get_options():
    opt_parser = optparse.OptionParser()
    opt_parser.add_option("--nogui", action="store_true",
                           default=False, help="run the commandline version of sumo")
    options, args = opt_parser.parse_args()
    return options

if __name__ == "__main__":
    options = get_options()
    if options.nogui:
        sumoBinary = checkBinary('sumo')
    else:
        sumoBinary = checkBinary('sumo-gui')

    traci.start([sumoBinary, "-c", "trialTraci.sumocfg",
                "--tripinfo-output", "tripinfo.xml"])
    
    run()
[---end of the code---]

I am currently using the sumo 1.12 version in windows

thank you in advance

**Comment by namdre** [comment]
This is too much of "please read and debug my code". See https://sumo.dlr.de/docs/FAQ.html#i_want_to_do_a_project_with_sumo_can_you_help_me_with_the_implementation

If you can boil down your problem to a specific reproducible problem situation and a few lines of traci code (preferably as a [traceFile](https://sumo.dlr.de/docs/TraCI/Interfacing_TraCI_from_Python.html#generating_a_log_of_all_traci_commands)) i'll reconsider .

**Comment by marayaaghnia** [comment]
I want to ask some questions about the usage of TraCI in sumo 1.13.
1. What should be included in "def run():"? Should I restate about the things that I already state in route files (ex: the action where person are reserve a taxi then taxi will pick them up)? Or I could just do this code for my "def run():"

[---beginning of the code---]
def run():
    """execute the TraCI control loop"""
    step = 0
    while step < 87000:
        traci.simulationStep()
        #if traci.inductionloop.getLastStepVehicleNumber("0") > 0:
        #    traci.trafficlight.setRedYellowGreenState("0", "GrGr")
        step += 1
        traci.addStepListener(traci.StepListener)
        traci.close()
        sys.stdout.flush()
[---end of code---]

2. Then if I want to do "def dist_to_edge", "def rebalance", and "def_strategy" to assign the movement of taxis where taxis should go to any free parking area when they have finished to drop off the passenger and haven't been assigned to another passenger (idling)? or is there any code examples that I could learn about the usage of TraCI for this case?


I am currently using the sumo 1.13 version in windows

thank you in advance @namdre or the others

**Comment by namdre** [comment]
example code can be found here:
https://sumo.dlr.de/extractTest.php?path=complex/traci/vehicle/taxi
https://github.com/eclipse/sumo/blob/main/tools/drt/drtOnline.py
