### ISSUE TITLE
let EIDM support startupDelay

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#10736]
@Domsall  Due having it's custom implementation of `finalizeSpeed` the use of MSCFModel::applyStartupDelay must be added explicitly.

**Comment by Domsall** [comment]
yes, its on my agenda. I have a few refactoring points I need to do.

**Comment by Domsall** [comment]
can be closed, was done in https://github.com/Domsall/sumo/commit/03da4666d6c71281c7ba7bcb98271c6921a84158
