### ISSUE TITLE
What is the difference between "getJamLengthVehicle" and "getLastStepHaltingNumber"?

### ISSUE THREAD

**Issue by JamesPsh** [eclipse/sumo#10741]
What is the difference between "getJamLengthVehicle" and "getLastStepHaltingNumber"?

https://sumo.dlr.de/pydoc/traci._lanearea.html#LaneAreaDomain-getJamLengthVehicle
https://sumo.dlr.de/pydoc/traci._lanearea.html#LaneAreaDomain-getLastStepHaltingNumber

**Comment by namdre** [comment]
For a simulation with default parameters (step-length = 1, laneAreaDetector timeThreshold = 1) there is no difference.
However:
- Any vehicle with speed below `speedThreshold` is considered as halting
- Any vehicle that has been halting for at least timeThreshold is considered part of a "jam"

So if you use a lower step-length or higher timeThreshold, then the number of halting vehicles may be higher than the number of jammed vehicles.

**Comment by JamesPsh** [comment]
I have one more question.
Is "getJamLengthMeters" the sum of the lengths of vehicles corresponding to "getJamLengthVehicle"?

https://sumo.dlr.de/pydoc/traci._lanearea.html#LaneAreaDomain-getJamLengthMeters

**Comment by namdre** [comment]
jamLengthInMeters also include the gaps between vehicles. This should be the same as  numberOfJammed * (length + minGap) in most cases but some carFollowModels might not always stop at minGap exactly.
