### ISSUE TITLE
review NEMA error message

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#10744]
@mschrader15 please review the generated error message when loading NEMA controller in sumo. I'm not sure whether it is valid.

netfiles:
- https://github.com/eclipse/sumo/blob/main/tests/netconvert/import/XML/tl_types/NEMA/NEMA_noLeftTurnLane/net.netconvert
- https://github.com/eclipse/sumo/blob/main/tests/netconvert/import/XML/tl_types/NEMA/NEMA_3arm_noS/net.netconvert

**Comment by namdre** [comment]
@mschrader15 

The 3 arm examples now create two NEMA phases (straight/left) for the every arm. It would be great if you could review them (at least they load without error).

Also, I've notice that the naming of the barriers is inconsistent at https://sumo.dlr.de/docs/Simulation/NEMA.html (barrier1/barrier2 in params vs picture).

**Comment by mschrader15** [comment]
@namdre the generated NEMA configs look correct from a phasing standpoint. There remains a timing bug as the phases before barrier 1 do not add to the same amount of time. Its not important for free mode (which these controllers default to), but probably good practice to time correctly from the get-go.

        <param key="ring1" value="1,2,3,0"/>  (maxDur_1 + yellow_1 + red_1) + (maxDur_2 + yellow_2 + red_2) = 110.00
        <param key="ring2" value="0,6,0,8"/>  (maxDur_6 + yellow_6 + red_6) = 55

Could be timed as

        <phase duration="90" state="rrrrGGrrr" minDur="5" maxDur="10" vehext="2" yellow="3" red="2" name="1"/>
        <phase duration="90" state="GGgrrrrrr" minDur="5" maxDur="35" vehext="2" yellow="3" red="2" name="2"/>
        <phase duration="90" state="rrrGggrrr" minDur="5" maxDur="50" vehext="2" yellow="3" red="2" name="6"/>

Good point about the documentation, I'll submit a PR to fix
