### ISSUE TITLE
routeExtension to pickup multiple person in group

### ISSUE THREAD

**Issue by radhityavirya** [eclipse/sumo#10753]
Hi, 
I'm currently doing a simulation with SUMO using routeExtension dispatch algorithm and randomCircling for taxi. This is my person and vehicle xml route's code example:
![person](https://user-images.githubusercontent.com/97588265/169229472-435ff413-d6b6-4bab-bf60-474d687c1c0a.PNG)
![vehicle](https://user-images.githubusercontent.com/97588265/169229480-9ec6c75e-3d7f-478a-92ce-6d852c8802fc.PNG)
But when I run the config file, the output (dispatchinfo) has no dispatch info:
![dispatch info](https://user-images.githubusercontent.com/97588265/169229912-a619c34e-12ae-497a-9573-b1c15a297e5a.PNG)
Then, what should i do and fix? Thankyou..

**SUMO-version: 1.12.0

**operating system: Windows

**Comment by namdre** [comment]
Please attach the scenario files (zipped)

**Comment by radhityavirya** [comment]
Sure, this is the scenario files
https://drive.google.com/drive/folders/1sKM8AJWlviOvLGBCwvX_l5hb3v1Gj2Lb?usp=sharing

**Comment by namdre** [comment]
dispatchInfo is only written for cases of ride sharing. Most likely, your scenario isn't dense enough for this to occur.

Note, that you can simplify your network (and speed up loading) for mesosim by processing it with 
`netconvert -s ringroad.net.xml --no-internal-links -o ringroad2.net.xml`

**Comment by radhityavirya** [comment]
But, when i use greedyShared with relLoss Threshold= 20.35 and absLoss Threshold=1000.35 and also randomCircling, the dispatchinfo can come out. Is it because the threshold?

**Comment by namdre** [comment]
the algorithms have different criteria for dispatching shared rides and greedyShared is much more flexible in this regard

**Comment by radhityavirya** [comment]
ok i understand, thankyou so much for the explanation 🙏

**Comment by radhityavirya** [comment]
Hello
I want to ask again, I will model a motorcycle, is there a class emission
for motorcycles in SUMO? Thankyou

**Comment by namdre** [comment]
Currently, no. Potentially, hey will be added as part of the HBEFA4 dataset (#7277). 
@behrisch can you confirm that motorcycles are part of the HBEFA4 classes?

**Comment by radhityavirya** [comment]
If no, what emission class is most suitable for the motorcycle?
