### ISSUE TITLE
inverse script to tls_csvSignalGroups.py

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#10756]
It would be great if one could build human readable descriptions from a SUMO tll file.
Pro: stable during connection / network updates (so it should at least optionally group the links into signal groups)
Con: non standard format

**Comment by behrisch** [comment]
@m-kro Please comment here so that I can assign you, thanks

**Comment by m-kro** [comment]
I'll work on this issue.

**Comment by namdre** [comment]
Can this also handle actuated tls?

**Comment by namdre** [comment]
See #10719 for how the actuated tls timings are encoded in csv.

**Comment by namdre** [comment]
python2 tests still fail in reverse-mode. Most likely due relying on the natural ordering of a dict or set. Can you check?
