### ISSUE TITLE
Could NOT find PythonInterp (missing: PYTHON_EXECUTABLE) - Error when installing SUMO to macOS Monterey

### ISSUE THREAD

**Issue by ajmacmahon** [eclipse/sumo#10755]
Tried to follow the steps for installation on macOS as described on https://sumo.dlr.de/docs/Installing/index.html#macos

But I always get the following error:

alexandermacmahon@Alexanders-Air ~ % brew install sumo
==> Downloading https://sumo.dlr.de/releases/1.13.0/sumo-src-1.13.0.tar.gz
Already downloaded: /Users/alexandermacmahon/Library/Caches/Homebrew/downloads/70e9c2e9b12bb6bf1c1fc67ce60b0f43a3a866450cab97e14873fdab62e3f97f--sumo-src-1.13.0.tar.gz
==> Installing sumo from dlr-ts/sumo
==> cmake ../.. -DCHECK_OPTIONAL_LIBS=OFF
Last 15 lines from /Users/alexandermacmahon/Library/Logs/Homebrew/sumo/01.cmake:
--     CMake: 3.23.1
--     CMake generator: Unix Makefiles
--     CMake build tool: /opt/homebrew/Library/Homebrew/shims/mac/super/gmake
--     Compiler: Clang 13.1.6.13160021
-- 
CMake Error at /opt/homebrew/Cellar/cmake/3.23.1_1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find PythonInterp (missing: PYTHON_EXECUTABLE)
Call Stack (most recent call first):
  /opt/homebrew/Cellar/cmake/3.23.1_1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /opt/homebrew/Cellar/cmake/3.23.1_1/share/cmake/Modules/FindPythonInterp.cmake:169 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:170 (find_package)

-- Configuring incomplete, errors occurred!
See also "/tmp/sumo-20220519-84812-8k9rp4/sumo-1.13.0/build/cmake-build/CMakeFiles/CMakeOutput.log".

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/dlr-ts/homebrew-sumo/issues

**macOS Monterey (12.3.1)**

**Comment by namdre** [comment]
@schwamborn shouldn't python by available by default?

Either document:
- python as installation requirement
- troubleshooting information for people that are missing out on the default python installation

**Comment by ajmacmahon** [comment]
Thanks a lot for the quick reply! Yes, Python is installed by default. I've also tried to install various versions of python with `pynev` but it still doesn't work.

**Comment by schwamborn** [comment]
@ajmacmahon after some tests on my machine, the formula itself should be fine.
Please try the following:

> % brew untap dlr-ts/sumo
> % brew update
> % brew update
> % brew tap dlr-ts/sumo
> % brew install sumo

There might also be problems with your homebrew environment, so you might also want to
> % brew doctor

**Comment by ajmacmahon** [comment]
Hey guys! Thanks a lot for your speedy support! I'm afraid I still haven't managed to get SUMO running, though...

> alexandermacmahon@Alexanders-Air ~ %  brew untap dlr-ts/sumo
Untapping dlr-ts/sumo...
Untapped 1 cask and 16 formulae (37 files, 208.7KB).
alexandermacmahon@Alexanders-Air ~ % brew update
Updated 2 taps (homebrew/core and homebrew/cask).
==> Updated Formulae
ccache                                           ffuf                                             tfsec
==> Updated Casks
feed-the-beast                                                           lagrange
alexandermacmahon@Alexanders-Air ~ % brew update
Already up-to-date.
alexandermacmahon@Alexanders-Air ~ % brew tap dlr-ts/sumo
==> Tapping dlr-ts/sumo
Cloning into '/opt/homebrew/Library/Taps/dlr-ts/homebrew-sumo'...
remote: Enumerating objects: 733, done.
remote: Counting objects: 100% (44/44), done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 733 (delta 18), reused 28 (delta 16), pack-reused 689
Receiving objects: 100% (733/733), 96.24 KiB | 3.70 MiB/s, done.
Resolving deltas: 100% (439/439), done.
Tapped 1 cask and 16 formulae (36 files, 207.5KB).
alexandermacmahon@Alexanders-Air ~ % brew install sumo
==> Downloading https://sumo.dlr.de/releases/1.13.0/sumo-src-1.13.0.tar.gz
Already downloaded: /Users/alexandermacmahon/Library/Caches/Homebrew/downloads/70e9c2e9b12bb6bf1c1fc67ce60b0f43a3a866450cab97e14873fdab62e3f97f--sumo-src-1.13.0.tar.gz
==> Installing sumo from dlr-ts/sumo
==> cmake ../.. -DCHECK_OPTIONAL_LIBS=OFF
Last 15 lines from /Users/alexandermacmahon/Library/Logs/Homebrew/sumo/01.cmake:
--     CMake: 3.23.1
--     CMake generator: Unix Makefiles
--     CMake build tool: /opt/homebrew/Library/Homebrew/shims/mac/super/gmake
--     Compiler: Clang 13.1.6.13160021
-- 
CMake Error at /opt/homebrew/Cellar/cmake/3.23.1_1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find PythonInterp (missing: PYTHON_EXECUTABLE)
Call Stack (most recent call first):
  /opt/homebrew/Cellar/cmake/3.23.1_1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /opt/homebrew/Cellar/cmake/3.23.1_1/share/cmake/Modules/FindPythonInterp.cmake:169 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:170 (find_package)


-- Configuring incomplete, errors occurred!
See also "/tmp/sumo-20220519-90029-138yjlr/sumo-1.13.0/build/cmake-build/CMakeFiles/CMakeOutput.log".

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/dlr-ts/homebrew-sumo/issues

alexandermacmahon@Alexanders-Air ~ % brew doctor
Your system is ready to brew.
alexandermacmahon@Alexanders-Air ~ % brew doctor
Your system is ready to brew.
alexandermacmahon@Alexanders-Air ~ % brew install sumo
Running `brew update --preinstall`...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> New Formulae
gcc@12                                           pget                                             ttmath
==> Updated Formulae
Updated 21 formulae.
==> Updated Casks
Updated 12 casks.

==> Downloading https://sumo.dlr.de/releases/1.13.0/sumo-src-1.13.0.tar.gz
Already downloaded: /Users/alexandermacmahon/Library/Caches/Homebrew/downloads/70e9c2e9b12bb6bf1c1fc67ce60b0f43a3a866450cab97e14873fdab62e3f97f--sumo-src-1.13.0.tar.gz
==> Installing sumo from dlr-ts/sumo
==> cmake ../.. -DCHECK_OPTIONAL_LIBS=OFF
Last 15 lines from /Users/alexandermacmahon/Library/Logs/Homebrew/sumo/01.cmake:
--     CMake: 3.23.1
--     CMake generator: Unix Makefiles
--     CMake build tool: /opt/homebrew/Library/Homebrew/shims/mac/super/gmake
--     Compiler: Clang 13.1.6.13160021
-- 
CMake Error at /opt/homebrew/Cellar/cmake/3.23.1_1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find PythonInterp (missing: PYTHON_EXECUTABLE)
Call Stack (most recent call first):
  /opt/homebrew/Cellar/cmake/3.23.1_1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /opt/homebrew/Cellar/cmake/3.23.1_1/share/cmake/Modules/FindPythonInterp.cmake:169 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:170 (find_package)


-- Configuring incomplete, errors occurred!
See also "/tmp/sumo-20220520-93287-14hykbf/sumo-1.13.0/build/cmake-build/CMakeFiles/CMakeOutput.log".

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/dlr-ts/homebrew-sumo/issues

>

**Comment by namdre** [comment]
If you call `python` in a shell it opens up a python interpreter?

**Comment by ajmacmahon** [comment]
No, I need to type `python3`

alexandermacmahon@Alexanders-Air ~ % python
zsh: command not found: python
alexandermacmahon@Alexanders-Air ~ % python3
Python 3.8.9 (default, Apr 13 2022, 08:48:06) 
[Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by namdre** [comment]
try creating a symlink so that calling 'python' works as well

**Comment by schwamborn** [comment]
I'm still confused as to why homebrew does not try to install the pre-compiled bottle. Can you please try a `brew install --verbose sumo`?
If we go the self-compile path, I would not recommend using homebrew in this case and instead use git directly (see https://sumo.dlr.de/docs/Installing/MacOS_Build.html). This way, you can also specify the Python paths manually as described [here](https://sumo.dlr.de/docs/Installing/MacOS_Build.html#python_for_libsumo_on_macos) using something like:
> cmake \
> -DPYTHON_EXECUTABLE=/usr/bin/python3 \
> -DPYTHON_INCLUDE_DIR:PATH=/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Headers \
> -DPYTHON_LIBRARY:FILEPATH=/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/Current/lib/libpython3.8.dylib \
> ../..

Note that this example uses Python from the command line tools of Xcode. The Python paths might be different on your machine.

**Comment by ajmacmahon** [comment]
> try creating a symlink so that calling 'python' works as well

Tried it
 `alexandermacmahon@Alexanders-MacBook-Air ~ % sudo ln -fs python3 python
Password:
alexandermacmahon@Alexanders-MacBook-Air ~ % python
Python 3.8.9 (default, Apr 13 2022, 08:48:06) 
[Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
alexandermacmahon@Alexanders-MacBook-Air ~ % brew install sumo 
==> Downloading https://sumo.dlr.de/releases/1.13.0/sumo-src-1.13.0.tar.gz
Already downloaded: /Users/alexandermacmahon/Library/Caches/Homebrew/downloads/70e9c2e9b12bb6bf1c1fc67ce60b0f43a3a866450cab97e14873fdab62e3f97f--sumo-src-1.13.0.tar.gz
==> Installing sumo from dlr-ts/sumo
==> cmake ../.. -DCHECK_OPTIONAL_LIBS=OFF
Last 15 lines from /Users/alexandermacmahon/Library/Logs/Homebrew/sumo/01.cmake:
--     CMake: 3.23.1
--     CMake generator: Unix Makefiles
--     CMake build tool: /opt/homebrew/Library/Homebrew/shims/mac/super/gmake
--     Compiler: Clang 13.1.6.13160021
-- 
CMake Error at /opt/homebrew/Cellar/cmake/3.23.1_1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find PythonInterp (missing: PYTHON_EXECUTABLE)
Call Stack (most recent call first):
  /opt/homebrew/Cellar/cmake/3.23.1_1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /opt/homebrew/Cellar/cmake/3.23.1_1/share/cmake/Modules/FindPythonInterp.cmake:169 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:170 (find_package)


-- Configuring incomplete, errors occurred!
See also "/tmp/sumo-20220520-98500-5c0tjy/sumo-1.13.0/build/cmake-build/CMakeFiles/CMakeOutput.log".

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/dlr-ts/homebrew-sumo/issues

alexandermacmahon@Alexanders-MacBook-Air ~ % 
`

**Comment by ajmacmahon** [comment]
> I'm still confused as to why homebrew does not try to install the pre-compiled bottle. Can you please try a `brew install --verbose sumo`? If we go the self-compile path, I would not recommend using homebrew in this case and instead use git directly (see https://sumo.dlr.de/docs/Installing/MacOS_Build.html). This way, you can also specify the Python paths manually as described [here](https://sumo.dlr.de/docs/Installing/MacOS_Build.html#python_for_libsumo_on_macos) using something like:
> 
> > cmake 
> > -DPYTHON_EXECUTABLE=/usr/bin/python3 
> > -DPYTHON_INCLUDE_DIR:PATH=/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Headers 
> > -DPYTHON_LIBRARY:FILEPATH=/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/Current/lib/libpython3.8.dylib 
> > ../..
> 
> Note that this example uses Python from the command line tools of Xcode. The Python paths might be different on your machine.

Same problems here I'm afraid...

alexandermacmahon@Alexanders-MacBook-Air ~ % brew install --verbose sumo
Running `brew update --preinstall`...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> New Formulae
helmify

==> Downloading https://sumo.dlr.de/releases/1.13.0/sumo-src-1.13.0.tar.gz
Already downloaded: /Users/alexandermacmahon/Library/Caches/Homebrew/downloads/70e9c2e9b12bb6bf1c1fc67ce60b0f43a3a866450cab97e14873fdab62e3f97f--sumo-src-1.13.0.tar.gz
==> Verifying checksum for '70e9c2e9b12bb6bf1c1fc67ce60b0f43a3a866450cab97e14873fdab62e3f97f--sumo-src-1.13.0.tar.gz'
==> Installing sumo from dlr-ts/sumo
tar --extract --no-same-owner --file /Users/alexandermacmahon/Library/Caches/Homebrew/downloads/70e9c2e9b12bb6bf1c1fc67ce60b0f43a3a866450cab97e14873fdab62e3f97f--sumo-src-1.13.0.tar.gz --directory /private/tmp/d20220520-727-1qkyrdk
cp -pR /private/tmp/d20220520-727-1qkyrdk/sumo-1.13.0/. /private/tmp/sumo-20220520-727-cmk3i5/sumo-1.13.0
chmod -Rf +w /private/tmp/d20220520-727-1qkyrdk
==> cmake ../.. -DCMAKE_INSTALL_PREFIX=/opt/homebrew/Cellar/sumo/1.13.0 -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DBUILD_TESTING=OFF -DCMAKE_OSX_SYSROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -DCHECK_OPTIONAL_LIBS=OFF
-- The CXX compiler identification is AppleClang 13.1.6.13160021
-- The C compiler identification is AppleClang 13.1.6.13160021
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/homebrew/Library/Homebrew/shims/mac/super/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/homebrew/Library/Homebrew/shims/mac/super/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- CMAKE_BINARY_DIR: /tmp/sumo-20220520-727-cmk3i5/sumo-1.13.0/build/cmake-build
-- CMAKE_SOURCE_DIR: /tmp/sumo-20220520-727-cmk3i5/sumo-1.13.0
-- 
-- Platform: 
--     Host: Darwin-21.4.0 arm64
--     Target: Darwin-21.4.0 arm64
--     CMake: 3.23.1
--     CMake generator: Unix Makefiles
--     CMake build tool: /opt/homebrew/Library/Homebrew/shims/mac/super/gmake
--     Compiler: Clang 13.1.6.13160021
-- 
CMake Error at /opt/homebrew/Cellar/cmake/3.23.1_1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find PythonInterp (missing: PYTHON_EXECUTABLE)
Call Stack (most recent call first):
  /opt/homebrew/Cellar/cmake/3.23.1_1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /opt/homebrew/Cellar/cmake/3.23.1_1/share/cmake/Modules/FindPythonInterp.cmake:169 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:170 (find_package)


-- Configuring incomplete, errors occurred!
See also "/tmp/sumo-20220520-727-cmk3i5/sumo-1.13.0/build/cmake-build/CMakeFiles/CMakeOutput.log".

==> Formula
Tap: dlr-ts/sumo
Path: /opt/homebrew/Library/Taps/dlr-ts/homebrew-sumo/Formula/sumo.rb
==> Configuration
HOMEBREW_VERSION: 3.4.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 30e3d8883cde265cbc16ff94b49a3ac14137590e
Last commit: 10 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 74f86cf4aceccd73d0b946450aca9debed59ea48
Core tap last commit: 25 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.1.6 build 1316
Git: 2.32.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.3.1-arm64
CLT: 13.4.0.0.1.1651278267
Xcode: N/A
Rosetta 2: false
==> ENV
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j8
CMAKE_PREFIX_PATH: /opt/homebrew/opt/expat:/opt/homebrew
CMAKE_INCLUDE_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_PATH: /opt/homebrew/opt/libpng/lib/pkgconfig:/opt/homebrew/opt/freetype/lib/pkgconfig:/opt/homebrew/opt/fontconfig/lib/pkgconfig:/opt/homebrew/opt/jpeg/lib/pkgconfig:/opt/homebrew/opt/libtiff/lib/pkgconfig:/opt/homebrew/opt/libpthread-stubs/lib/pkgconfig:/opt/homebrew/opt/libxau/lib/pkgconfig:/opt/homebrew/opt/libxdmcp/lib/pkgconfig:/opt/homebrew/opt/libxcb/lib/pkgconfig:/opt/homebrew/opt/libx11/lib/pkgconfig:/opt/homebrew/opt/libxfixes/lib/pkgconfig:/opt/homebrew/opt/libxrender/lib/pkgconfig:/opt/homebrew/opt/libxcursor/lib/pkgconfig:/opt/homebrew/opt/libxext/lib/pkgconfig:/opt/homebrew/opt/libxft/lib/pkgconfig:/opt/homebrew/opt/libxi/lib/pkgconfig:/opt/homebrew/opt/libxrandr/lib/pkgconfig:/opt/homebrew/opt/expat/lib/pkgconfig:/opt/homebrew/opt/libxdamage/lib/pkgconfig:/opt/homebrew/opt/mesa/lib/pkgconfig:/opt/homebrew/opt/mesa-glu/lib/pkgconfig:/opt/homebrew/opt/fox/lib/pkgconfig:/opt/homebrew/opt/proj/lib/pkgconfig:/opt/homebrew/opt/xerces-c/lib/pkgconfig:/opt/homebrew/opt/xorgproto/share/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/opt/homebrew/Library/Homebrew/os/mac/pkgconfig/12
HOMEBREW_GIT: git
HOMEBREW_SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk
ACLOCAL_PATH: /opt/homebrew/share/aclocal
PATH: /opt/homebrew/Library/Homebrew/shims/mac/super:/opt/homebrew/opt/cmake/bin:/opt/homebrew/opt/libpng/bin:/opt/homebrew/opt/freetype/bin:/opt/homebrew/opt/fontconfig/bin:/opt/homebrew/opt/jpeg/bin:/opt/homebrew/opt/libtiff/bin:/opt/homebrew/opt/pkg-config/bin:/opt/homebrew/opt/expat/bin:/opt/homebrew/opt/gettext/bin:/opt/homebrew/opt/fox/bin:/opt/homebrew/opt/proj/bin:/opt/homebrew/opt/xerces-c/bin:/usr/bin:/bin:/usr/sbin:/sbin

Error: dlr-ts/sumo/sumo 1.13.0 did not build
Logs:
     /Users/alexandermacmahon/Library/Logs/Homebrew/sumo/00.options.out
     /Users/alexandermacmahon/Library/Logs/Homebrew/sumo/01.cmake.cc
     /Users/alexandermacmahon/Library/Logs/Homebrew/sumo/01.cmake
     /Users/alexandermacmahon/Library/Logs/Homebrew/sumo/build
If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/dlr-ts/homebrew-sumo/issues

**Comment by ajmacmahon** [comment]
Do you guys have any other idea what may work?

**Comment by ajmacmahon** [comment]
Guys - I just tried to install Python again via Homebrew (`brew install pyhon`) and went for `brew install sumo` once more and for some reason it worked this time!

alexandermacmahon@Alexanders-MacBook-Air ~ % brew install python
Running `brew update --preinstall`...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> New Formulae
bore-cli               cxgo                   erlang@24              gokart                 naml                   opentelemetry-cpp      tinysearch             xpipe
==> Updated Formulae
Updated 169 formulae.
==> New Casks
bilibili-official              cardpresso                     contour                        hdfview                        input-source-pro               oso-cloud
==> Updated Casks
Updated 109 casks.

==> Downloading https://ghcr.io/v2/homebrew/core/gdbm/manifests/1.23
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/gdbm/blobs/sha256:62a2c1994737a2677f318a97ac64a32690f9f958086310a49f37e3fcfd5b6731
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:62a2c1994737a2677f318a97ac64a32690f9f958086310a49f37e3fcfd5b6731?se=2022-05-24T09%3A45%3A00Z&sig=igbXZT
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/mpdecimal/manifests/2.5.1
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/mpdecimal/blobs/sha256:726e8ec0713eb452bb744fe9147771bacc2c3713a128aaee03b6ddcc78011d1a
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:726e8ec0713eb452bb744fe9147771bacc2c3713a128aaee03b6ddcc78011d1a?se=2022-05-24T09%3A45%3A00Z&sig=sTbg8H
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/sqlite/manifests/3.38.5
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/sqlite/blobs/sha256:ec526591d77541ae811e1d91381e5c109e5110ec8643bd3ba394f025be1b32ef
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:ec526591d77541ae811e1d91381e5c109e5110ec8643bd3ba394f025be1b32ef?se=2022-05-24T09%3A45%3A00Z&sig=4z1G2k
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/xz/manifests/5.2.5
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/xz/blobs/sha256:fcda3e81efe284f7e07effcb4ba03a87c8d828833351ac3f41e1e808e7753b0a
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:fcda3e81efe284f7e07effcb4ba03a87c8d828833351ac3f41e1e808e7753b0a?se=2022-05-24T09%3A45%3A00Z&sig=LXLusk
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/python/3.9/manifests/3.9.13
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/python/3.9/blobs/sha256:7bf1e26018eee5c546ffe26d499923415b74ef2d050f8cd4a26eb64be5a8a8e3
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:7bf1e26018eee5c546ffe26d499923415b74ef2d050f8cd4a26eb64be5a8a8e3?se=2022-05-24T09%3A45%3A00Z&sig=rvilhe
######################################################################## 100.0%
==> Installing dependencies for python@3.9: gdbm, mpdecimal, sqlite and xz
==> Installing python@3.9 dependency: gdbm
==> Pouring gdbm--1.23.arm64_monterey.bottle.tar.gz
🍺  /opt/homebrew/Cellar/gdbm/1.23: 24 files, 1MB
==> Installing python@3.9 dependency: mpdecimal
==> Pouring mpdecimal--2.5.1.arm64_monterey.bottle.tar.gz
🍺  /opt/homebrew/Cellar/mpdecimal/2.5.1: 71 files, 2.2MB
==> Installing python@3.9 dependency: sqlite
==> Pouring sqlite--3.38.5.arm64_monterey.bottle.tar.gz
🍺  /opt/homebrew/Cellar/sqlite/3.38.5: 11 files, 4.4MB
==> Installing python@3.9 dependency: xz
==> Pouring xz--5.2.5.arm64_monterey.bottle.tar.gz
🍺  /opt/homebrew/Cellar/xz/5.2.5: 95 files, 1.4MB
==> Installing python@3.9
==> Pouring python@3.9--3.9.13.arm64_monterey.bottle.tar.gz
==> /opt/homebrew/Cellar/python@3.9/3.9.13/bin/python3 -m ensurepip
==> /opt/homebrew/Cellar/python@3.9/3.9.13/bin/python3 -m pip install -v --no-deps --no-index --upgrade --isolated --target=/opt/homebrew/lib/python3.9/site-packages /opt/homebrew/Cellar/p
==> Caveats
Python has been installed as
  /opt/homebrew/bin/python3

Unversioned symlinks `python`, `python-config`, `pip` etc. pointing to
`python3`, `python3-config`, `pip3` etc., respectively, have been installed into
  /opt/homebrew/opt/python@3.9/libexec/bin

You can install Python packages with
  pip3 install <package>
They will install into the site-package directory
  /opt/homebrew/lib/python3.9/site-packages

tkinter is no longer included with this formula, but it is available separately:
  brew install python-tk@3.9

See: https://docs.brew.sh/Homebrew-and-Python
==> Summary
🍺  /opt/homebrew/Cellar/python@3.9/3.9.13: 3,088 files, 57.6MB
==> Running `brew cleanup python@3.9`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
==> Caveats
==> python@3.9
Python has been installed as
  /opt/homebrew/bin/python3

Unversioned symlinks `python`, `python-config`, `pip` etc. pointing to
`python3`, `python3-config`, `pip3` etc., respectively, have been installed into
  /opt/homebrew/opt/python@3.9/libexec/bin

You can install Python packages with
  pip3 install <package>
They will install into the site-package directory
  /opt/homebrew/lib/python3.9/site-packages

tkinter is no longer included with this formula, but it is available separately:
  brew install python-tk@3.9

See: https://docs.brew.sh/Homebrew-and-Python
alexandermacmahon@Alexanders-MacBook-Air ~ % brew install sumo
==> Downloading https://sumo.dlr.de/releases/1.13.0/sumo-src-1.13.0.tar.gz
Already downloaded: /Users/alexandermacmahon/Library/Caches/Homebrew/downloads/70e9c2e9b12bb6bf1c1fc67ce60b0f43a3a866450cab97e14873fdab62e3f97f--sumo-src-1.13.0.tar.gz
==> Installing sumo from dlr-ts/sumo
==> cmake ../.. -DCHECK_OPTIONAL_LIBS=OFF
==> make
==> make install
==> Caveats
In order to let X11 start automatically whenever a GUI-based SUMO application
(e.g., "sumo-gui") is called, you need to log out and in again.
Alternatively, start X11 manually by pressing cmd-space and entering "XQuartz".

Don't forget to set your SUMO_HOME environment variable:
  export SUMO_HOME="/opt/homebrew/opt/sumo/share/sumo"

Please report any problems with this formula directly to the eclipse/sumo issue tracker:
https://github.com/eclipse/sumo/issues

==> Summary
🍺  /opt/homebrew/Cellar/sumo/1.13.0: 1,917 files, 130.5MB, built in 3 minutes 50 seconds
==> Running `brew cleanup sumo`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).

**Comment by behrisch** [comment]
Are the brew binaries platform dependent? Maybe we do not have binaries for the correct platform?

**Comment by ajmacmahon** [comment]
Thanks again for your input on this, guys! I'm very happy that all finally works! Following the rest of the installation guide went smoothly!
