### ISSUE TITLE
traci.vehicle.dispatchTaxi got stuck while using random.choice for TraCI in SUMO

### ISSUE THREAD

**Issue by marayaaghnia** [eclipse/sumo#10760]
I'm currently doing a taxi simulation with SUMO where it is using the "--device.taxi.dispatch-algorithm=traci". On the TraCI python code, I am using a dispatch strategy where it needs a random.choice from random.py. 

[---code start---]
def dispatch(strategy):
    free_taxis = traci.vehicle.getTaxiFleet(flag=0)
    reservations = traci.person.getTaxiReservations(1)
    if strategy == "mockup":
        for reservation in reservations:
            try:
                **traci.vehicle.dispatchTaxi(random.choice(free_taxis), reservation.id)**
            except traci.exceptions.TraCIException:
                pass
[---code end---]

But when I start the simulation, it got stuck on step 6082, the play button still selected but the step is stuck (picture below). Then when I checked on the Spyder, it said that:

"    traci.vehicle.dispatchTaxi(random.choice(free_taxis), [reservation.id](http://reservation.id/))
  File "random.py", line 290, in choice
IndexError: Cannot choose from an empty sequence "

![Screenshot (6391)](https://user-images.githubusercontent.com/83570414/169303141-3d703ea1-c56b-4a0f-a3f2-08c32e46ee28.png)

What could I do?

SUMO-version: 1.13.0

operating system:Windows

**Comment by schwamborn** [comment]
It looks like `free_taxis` was empty in that case. You need to check the result from `traci.vehicle.getTaxiFleet(flag=0)` accordingly.
