### ISSUE TITLE
sumo does not open!

### ISSUE THREAD

**Issue by contesara** [eclipse/sumo#10762]
Hi!
I'm a Mac user and I installed sumo following the steps on the website. 
Now that sumo and netedit appear in my applications, every time I try to open them both clicking on the icon both from the terminal, nothing happens.
I already tried redownloading everything but it doesn't change.
If I run xclock in my terminal  a clock appears so it's not the problem.
What can I do?
Thanks for the future answer and sorry for bothering you
Sara

**Comment by schwamborn** [comment]
Have you set your `SUMO_HOME` environment variable as described [here](https://sumo.dlr.de/docs/Installing/index.html#macos)?

**Comment by contesara** [comment]
a file text with on
export SUMO_HOME=/your/path/to/sumo
appears.
Am I supposed to write like /Applications/sumogui ?

**Comment by schwamborn** [comment]
Assuming you installed with homebrew, try

> export SUMO_HOME=/usr/local/opt/sumo/share/sumo

**Comment by contesara** [comment]
I did it and nothing and sumo still does not open

**Comment by behrisch** [comment]
closing for lack of feedback. Please add another comment with the required information if the problem persists
