### ISSUE TITLE
walkingareas look glitched in 3D view

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#10773]
@m-kro it appears they are drawn at the same z-offset as the junction shape and this creates artifacts.

**Comment by namdre** [comment]
example network: tests/tools/import/OSM/webWizard/osmimport.tools

**Comment by m-kro** [comment]
Currently, walkingareas are treated the same as other road segments, using their given coordinates - no special z offset is applied. 
I don't know why the other example works, but would expect it to be random / a floating point issue. So should we add a small z offset then?

**Comment by namdre** [comment]
Yes. I think a z-offset that puts it above the junction would be best. also for crossings probably.

**Comment by behrisch** [comment]
maybe rise walking areas 10cm similar to the real world

**Comment by m-kro** [comment]
![grafik](https://user-images.githubusercontent.com/33294728/171349626-06d6ebcc-8150-4715-8157-9134608563e2.png)

- The screenshot shows walkingareas and sidewalk lanes raised to 10cm height. 
- The shading / normals are now computed by OSG itself, as the ones defined manually would brake when applying the polygon tessellator. This leads to some "rounding shadow" in some places.
- The near/far ratio of OSG has been increased: Small Z offsets are now rendered correctly. This comes with the price of very close items not being rendered anymore.
- There is currently no good solution for overlapping shapes in the same plane, like rail tracks inside a junction

**Comment by namdre** [comment]
looks nice!

**Comment by m-kro** [comment]
As far as walkingareas are concerned, I'd consider this issue as done. Obviously there remain other issues with overlapping shapes like tram tracks across junctions...
