### ISSUE TITLE
Cannot get traci.constants.VAR_ELECTRICITYCONSUMPTION values

### ISSUE THREAD

**Issue by xl-svm** [eclipse/sumo#10785]
Add your issue description here. Cannot get traci.constants.VAR_ELECTRICITYCONSUMPTION value through the self.conn.junction.subscribeContext(). When I use SUMO-Python to simulate the change of electric energy consumption of electric vehicles, the function self.conn.junction.subscribeContext(tsc_id, traci.constants.CMD_GET_VEHICLE_VARIABLE, 150,    
                                        [traci.constants.VAR_LANEPOSITION,    
                                        traci.constants.VAR_SPEED,      
                                        traci.constants.VAR_LANE_ID,
                                        traci.constants.VAR_ELECTRICITYCONSUMPTION,
                                        traci.constants.VAR_TYPE]
get the result at one step as  {86: 26.550190000000008, 64: 10.655019000000001, 81: '-gneE8_2', 113: 0.0, 79: 'eCar'},
the output of  traci.constants.VAR_ELECTRICITYCONSUMPTION=0, but in the  networks/Battery.out.xml (<battery-output value="networks/Battery.out.xml"/>), I can see the vehicle ELECTRICITYCONSUMPTION like <vehicle id="-gneE90" energyConsumed="0.6542" totalEnergyConsumed="23.2714" ...>

*If possible, upload an example that shows your problem.*

**SUMO-version:** SUMO 1.13.0   (Python 3.6)

**operating system:**WINDOWS 10
@namdre Jakob Erdmann

**Comment by namdre** [comment]
define your vehicle with `emissionClass="Energy"` and then it should work.

**Comment by xl-svm** [comment]
Thanks! 
By define the vehicle with emissionClass="Energy", then get  the result at one step as {86: 50.729028, 64: 15.629028, 81: 'gneE11_2', 113: 4.30224011315848, 79: 'eCar'}, it means traci.constants.VAR_ELECTRICITYCONSUMPTION=4.30224011315848.
