### ISSUE TITLE
decals and multi-view are not restored on reload

### ISSUE THREAD

**Issue by yunpangfloetteroed** [eclipse/sumo#10788]
When pressing the circle icon in SUMO-GUI for reloading a scenario, the pre-defined picture in the respective setting file cannot be reloaded.

*If possible, upload an example that shows your problem.*

**SUMO-version:**
 v1_13_0+0269-18191dd03c2
**operating system:**
Build features: Windows-10.0.19042 AMD64 MSVC 19.29.30137.0 Release Proj GUI SWIG GDAL FFmpeg OSG GL2PS Eigen

**Comment by yunpangfloetteroed** [comment]
An example is put under S:\Sumo\Bugreports\10788_picture_in_setting_file_cannot_be_reloaded .

**Comment by namdre** [comment]
regression via #10398
