### ISSUE TITLE
IDM following model

### ISSUE THREAD

**Issue by Anas-1998** [eclipse/sumo#10784]
Hello, I was wondering if I can make the vehicle using IDM, in a specific lane to consider the front vehicle on the lane beside it to be the preceding vehicle? is there any way to do that? I tried to manipulate the minimum gap value, but I also need to manipulate the speed of the preceding vehicle, or do I need to write a new car following model for that?
I would be thankful if you point me to any thing regarding this.
Thanks in advance

**Comment by namdre** [comment]
If the vehicles are approaching a zipper merge junction they will do as you described (https://sumo.dlr.de/docs/Netedit/neteditUsageExamples.html#creating_a_zipper_merge)

If you want to achieve the same effect in arbitrary locations you can use traci function `vehicle.getFollowSpeed` and `vehicle.setSpeed` to determine and force the desired speed.
