### ISSUE TITLE
Issues with mouse control in the racing game

### ISSUE THREAD

**Issue by vijay-jaisankar** [eclipse/sumo#10783]
There are some serious issues that arise from the mouse position controls in the racing game:
- The vehicle size keeps increasing and decreasing as it traverses the grid
- The `TS` parameter is too high for an ordinary user to play the game solely using mouse controls, in my opinion. 
- With a low value of `delay`, there is also a lot of glitching and flickering.

Examples of the car shrinking and expanding:
![Small Car](https://user-images.githubusercontent.com/56185979/169670820-857541cd-be49-44f3-9a24-10b3d090b796.png)
![Large Car](https://user-images.githubusercontent.com/56185979/169670823-ab8603a3-af00-4a43-bee4-c1d48b78b45f.png)

In my opinion, the mouse control feature can be removed altogether, or can be restricted to it being invoked only on a special flag given to the program (For example `-m` : this can be configured in the Options Parser.)

If you feel like this can be done, I'd love to take this up and make a PR for the same :) 

Thanks,
Vijay

Configuration Information:
**SUMO-version: 1.12.0**
**operating system: (Linux)**

**Comment by namdre** [comment]
Thanks for pointing out the glitches. The racing game should now work as intended again. The settings had not kept up with changes in gui behavior.  Feel free to add a pull request that switches between steering options.

**Comment by vijay-jaisankar** [comment]
Thanks for the comments, the game is working fine now :)

I have just made a PR for the steering options.

**Comment by namdre** [comment]
thanks!
