### ISSUE TITLE
some problems in traci.start

### ISSUE THREAD

**Issue by SuirongYi** [eclipse/sumo#10781]
I want to use [sumo-gui] as a server, and the simulation can be started by setting the option **--start**  。But I want to know the specific usage, because I can't find relevant reference materials on the official website. As shown below, this is someone else's code I saw, but I don't know the meaning of the strings circled by these red boxes. I hope you can give me a detailed answer, thank you very much!
![a17d41ec7545dcd922488ba39d6edaa](https://user-images.githubusercontent.com/92314798/169642458-e328b850-039b-4e1a-94d8-d747caebf09b.png)

**Comment by namdre** [comment]
https://sumo.dlr.de/docs/Simulation/Basic_Definition.html (first page suggested by https://www.google.com/search?q=sumo+step+length)
https://sumo.dlr.de/docs/Simulation/Randomness.html (first page suggested by https://www.google.com/search?q=sumo+random)
https://sumo.dlr.de/docs/sumo.html (third page suggested by https://www.google.com/search?q=sumo+no+warnings)

Please do some basic research before posting questions here!
