### ISSUE TITLE
Could not import libsumo

### ISSUE THREAD

**Issue by Shinerow** [eclipse/sumo#10782]
Hi! I'm trying to use libsumo. When i import libsumo, there's a problem like this:

![Screenshot (1805)](https://user-images.githubusercontent.com/75409478/169645370-d8635f28-abf7-41fa-9fb5-052c8e59842f.png)

I found a discussion about the steps to use libsumo for windows (this is the discussion: https://www.eclipse.org/lists/sumo-user/msg04118.html) and i have followed those steps. Any idea how to solve this problem? Thank you!

SUMO-version:
SUMO 1.12.0

operating system:
Windows 11

**Comment by behrisch** [comment]
Can you please report your python version and how you built libsumo?
