### ISSUE TITLE
Zoom through 3D viewport dialog changes camera direction

### ISSUE THREAD

**Issue by m-kro** [eclipse/sumo#10791]
When changing the zoom value in the 3D viewport dialog of sumo-gui to values > 100, the Z value of the camera location decreases, but the lookAt coordinates remain unchanged. This means the lookAt position (= the point the camera should look at) is above the camera, thus the camera points into the sky.

**SUMO-version:** current dev ver.

**Comment by namdre** [comment]
first thought:  shouldn't the look-at coordinate be always on the ground?
second thought: in complex 3d networks, it may be desirable to point the camera skywards (https://en.wikipedia.org/wiki/Stack_interchange)

**Comment by m-kro** [comment]
I changed the title to make the problem more clear. Explicitly looking to the sky is possible by either entering the corresponding coordinates in the dialog or manipulating the view directly. But zooming should preserve the camera direction  which currently is not the case.

**Comment by m-kro** [comment]
The zoom value in 3D view is now only used as a helper within the viewport dialog, as the view is already entirely defined by the camera and the position to look at. 

- A zoom value of 100 leaves the view unchanged.
- Values greater 100 zoom in by (zoom - 100) meters, 
- Values smaller than 100 zoom out in view direction
- The zoom value is reset to 100 when the viewport dialog is shown the next time
