### ISSUE TITLE
Feature Proposal: Dark mode/Light mode Preference in the `osmWebWizard` tool

### ISSUE THREAD

**Issue by vijay-jaisankar** [eclipse/sumo#10797]
## Idea
We can use the OS' preferences through the CSS [color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme) property to add light/dark mode capabilities to the osmWebWizard's `index.html`. 

## Proposal
- Initialise the `color-scheme` property with all attributes 
```css
:root {
  color-scheme: light dark;
}
```
- Light/Dark mode toggle switch
- Default mode can be light mode

## Compatibility
[Mozilla Web Docs](https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme) reports that this feature is supported across all major browsers (barring IE).  

If this feature looks nice, can I please make a PR for the same?

Thanks,
Vijay

**Comment by angelobanse** [comment]
Hi Vijay. I myself am a big dark mode enthusiast (thats why the SUMO Documentation has a dark mode in the first place), 
but unfortunately there is not an "elegant" way to implement it on the osmWebWizard right now.

The only element we really can *directly* change is the purple sidebar (which already isn't that light). For the map tiles (which occupy the majority of the viewport) we rely on OSM. We could invert the colors or apply other type of CSS filters to the tiles (see https://github.com/openstreetmap/openstreetmap-website/issues/2332#issuecomment-727266980), but it would look weird and not necessarily consistent across all browsers (as also discussed in the thread linked above).

Let's wait for the official OSM dark mode support.

**Comment by vijay-jaisankar** [comment]
Sure thing! Thanks for the feedback
