### ISSUE TITLE
how can I change the nextSwitch time of traffic light if I changed the program through Traci

### ISSUE THREAD

**Issue by lightly-lyx** [eclipse/sumo#10803]
Add your issue description here.
Hello, I want to change the timing plan through traci. But when I set a new ProgramLogic, the new timing plan won't switched as I think, but it is affected by the nextSwitch() parameter, which I think is determined by old timing plan. So how can I make sure the phases in my new timing plan can be switched according to their durations.

*If possible, upload an example that shows your problem.*
    def set_plan(self,node_name,stage_plan):
        # plan is a list, which contains different phases, each phase is a dict with signal state as key and duration as value.
        cur_program = self.sim.trafficlight.getAllProgramLogics(node_name)
        next_program = cur_program
        # set index start from 0
        next_program[0].currentPhaseIndex = 0
        next_program[0].type = 0
        phase_data_type = next_program[0].phases[0]
        phases = []
        #change the phase parameter
        for item in stage_plan:
            key = list(item.keys())[0]
            value = item[key]
            phase_data_type.state = key
            phase_data_type.duration = value
            phase_data_type.minDur = -1
            phase_data_type.maxDur = -1
            phases.append(copy.deepcopy(phase_data_type))
        next_program[0].phases = tuple(phases)
        # set new program
        self.sim.trafficlight.setProgramLogic(node_name,next_program[0])

**SUMO-version:**1.8

**operating system:**PYTHON

**Comment by lightly-lyx** [comment]
actually, I find that sumo will firstly finish the current phase of old timing plan, then will execute the new timing plan from the second phase in new timing plan. but I want to terminate the current phase of old plan to execute the new timing plan from the first phase.

**Comment by lightly-lyx** [comment]
I can use the setPhaseDuration() =0 of the current phase to skip the current phase in old plan, but the first phase in my new plan will still be skipped :(

**Comment by m-kro** [comment]
You can study the test sim at [tests/complex/traci/trafficlight/trafficlight](https://github.com/eclipse/sumo/tree/main/tests/complex/traci/trafficlight/trafficlight) which switches to a signal program generated in TraCI. See [docs ](https://sumo.dlr.de/docs/Tutorials/index.html#using_examples_from_the_test_suite)on how to download a test.
