### ISSUE TITLE
Output of Taxi Simulations in SUMO (are always the same?)

### ISSUE THREAD

**Issue by marayaaghnia** [eclipse/sumo#10801]
Hi, I want to ask about the output of simulation in SUMO. I'm using randomCircling and also Stop for the device.taxi.dispatch-algorithm of my taxis in different models. I did some running to look for the difference of each tripinfo-output. But when I checked on the tripinfos, the outputs are all the in exact same numbers. Does the algorithm of the models are not having like a random different movement in every running of the simulations?

For example like RAND() in excel will give different numbers in every change.

SUMO-version: 1.13.0

operating system: Windows

**Comment by behrisch** [comment]
If you want to trigger differences in the simulations try starting sumo with the `--random` option set.
