### ISSUE TITLE
Feature Request: Co Simulation with OSI compatible simulators

### ISSUE THREAD

**Issue by jdsika** [eclipse/sumo#10807]
Given:
The [Open Simulation Interface (OSI)](https://github.com/OpenSimulationInterface/open-simulation-interface) is a [ASAM e.V.](https://www.asam.net/standards/detail/osi/) open simulation standard. There is the possibility to integrate different kind of models as Functional Mockup Units (FMUs) into a Co Simulation. It primarily started for the use case of sensor models but has expanded to be able to use for steering traffic participants with the [traffic command](https://github.com/OpenSimulationInterface/osi-sensor-model-packaging/pull/84) .

When:
I am using a OSI compliant simulator I want to integrate traffic participant behaviour.

Then:
I could consider SUMO as a proper open source solution if it would support the integration with OSI and FMI

**Comment by namdre** [comment]
An FMI wrapper has already been created (#6533).
Ongoing work is documented at (#10053, #10106)

see also https://sumo.dlr.de/docs/Developer/FMI.html

Feel free to post here if there are still questions.
