### ISSUE TITLE
emission formula for vehicle?

### ISSUE THREAD

**Issue by radhityavirya** [eclipse/sumo#10818]
hello i want to ask, i'm modeling taxi with emission class HBEFA3/LDV and output emission. can you explain how the emission (tripinfo) works on the vehicle? Is there a certain formula when the taxi carries passengers or is it empty? and how are the emissions when the taxi is idle or running? thanks

**Comment by namdre** [comment]
Passenger weight is currently not taking into account by the HBEFA3 emission model. 
(#2337)

The vehicle speed does have an impact on emissions, so the idling emissions should generally be lower than the driving emissions.
