### ISSUE TITLE
described error-Multi-Entry-Exit Detectors (E3)-Generated Output

### ISSUE THREAD

**Issue by ijcfamily** [eclipse/sumo#10817]
Error in the interpretation of the E3 detector output.
https://sumo.dlr.de/docs/Simulation/Output/Multi-Entry-Exit_Detectors_%28E3%29.html#generated_output
<img width="1043" alt="image" src="https://user-images.githubusercontent.com/94910197/170849967-e46aa1a3-f8c8-4645-aac3-872bee923a07.png">

meanIntervalHaltsPerVehicleWithin | # | 
The number of vehicles that have left the area during the interval, collected during the written interval. Averaged over the interval and vehicles.
-- | -- | --
meanIntervalDurationWithin | s | 
The number of vehicles that have left the area during the interval, collected during the written interval. Averaged over the interval and vehicles.
‘meanIntervalHaltsPerVehicleWithin’ and ‘meanIntervalDurationWithin ’have the same interpretation of the results

**operating system:**

**Comment by namdre** [comment]
Thanks!
