### ISSUE TITLE
Can't find libiconv-2.dll

### ISSUE THREAD

**Issue by superlinger** [eclipse/sumo#10812]
Add your issue description here.
After I finished building sumo , I run sumo-gui.exe ,then show the message " can't find libiconv-2.dll..."
I searched the folder "SUMOLibraries" ,but couldn't find the libiconv-2.dll.
*If possible, upload an example that shows your problem.*

**SUMO-version:**
clone the newest version this morning
**operating system:**
win 10

**Comment by m-kro** [comment]
There is a **libiconv.dll** in SUMOLibraries, while a **libiconv-2.dll** is supplied e.g. with mingw64. Do you have installed mingw64 with git and put its bin folder in the PATH env variable? If yes, please remove it and then try a new build of SUMO.

**Comment by superlinger** [comment]
> 
Thank you  a lot.
Actually ,I installed git which included mingw64.  I removed the folder 'Git\mingw64\bin' in the PATH env variable and rebuild again. But still the same warning message.
 Then I found the 'libiconv-2.dll' in the folder 'Git\mingw64\libexec\git-core' ,and put this folder in the PATH env variable.
I run the sumo-gui.exe, It worked!
