### ISSUE TITLE
The green line covers the network part

### ISSUE THREAD

**Issue by quanghuy89** [eclipse/sumo#10819]
Add your issue description here.

*If possible, upload an example that shows your problem.*
SUMO-version:1.13.0

Anyone help me solve this problem . I can't see may network because green line

![sumo -error](https://user-images.githubusercontent.com/71219472/170878091-69abb625-1d73-42e4-833c-e164c4546229.png)

**Comment by m-kro** [comment]
Please check your graphic card drivers are up to date.
