### ISSUE TITLE
Issue on adding a polygon via Traci

### ISSUE THREAD

**Issue by Imperialpiggy** [eclipse/sumo#10814]
Hello,

I wish to add a polygon dynamically when running the simulation via Traci:
My code is (I tried the layer value from -1 to 10) :
shapelist = ((9455, 9902), (12703, 6900))
traci.polygon.add(polygonID="test111", shape=shapelist, color=(200, 200, 200, 255), fill=True, layer=-1)
        
But the polygon does not show up. Yet I can fetch the attributes of the polygon, which means sumo-gui received the request:
color = traci.polygon.getColor("test111")
print(color) # result: color=(200, 200, 200, 255)

Thank you in advance for your time and your kindness

**SUMO-version: 1.9.0**

**operating system: windows 10**

**Comment by m-kro** [comment]
Your geometry contains only two points. Add at least one more so that your polygon covers an area > 0.

**Comment by Imperialpiggy** [comment]
> Your geometry contains only two points. Add at least one more so that your polygon covers an area > 0.

oh, thanks very much, (¦3」∠)
