### ISSUE TITLE
 ramp question,vehicle unable to merge

### ISSUE THREAD

**Issue by zhengkemei** [eclipse/sumo#10815]
Hello,I have a question about  ramp.  when the vehicle on the acceleration lane_0, I give the target lane is lane_1.The vehicles unable to merge (change lanes) and stop at the end of the acceleration lane even no vehicle on the main road, i have make the acceleration lane longer than in reality ,is 350m,the junction type is zipper,but it still unable to merge.
Could you please help me?

**SUMO-version:sumo-1.11.0

**operating system:windows10
![ramp](https://user-images.githubusercontent.com/84378054/170819943-18f41dce-2a8c-4ab9-aa96-712f16c63097.png)

**Comment by namdre** [comment]
- is TraCI involved?
- can you attach your scenario files (zipped)?

**Comment by behrisch** [comment]
Closing for lack of feedback. Feel free to add another comment if you have more information or can provide a scenario.
