### ISSUE TITLE
Add virtual leader in Sumo

### ISSUE THREAD

**Issue by zjh6252007** [eclipse/sumo#10828]
Hello guys,
I'm now doing an experienment and I need to add a virtual leader to a vehicle so that it can affect the following behavior of it. Now I'm using the MSCFModel_ACC and I need to change the leader's information (speed, gap2pred, predSpeed, PreMaxDecel) to create the virtual leader. I check the source code but I don't know where to change these information. Can anyone help me of this?

**Comment by namdre** [comment]
The easiest way to accomplish this is by adding an actual leader vehicle and then remote-controlling it's position and speed via TraCI
(i.e. vehicle.setSpeed, vehicle.moveTo, vehicle.moveToXY, vehicle.setDecel,...) See https://sumo.dlr.de/docs/TraCI.html
