### ISSUE TITLE
Cloning Command Updation

### ISSUE THREAD

**Issue by vijay-jaisankar** [eclipse/sumo#10829]
Github has announced that plans to [do away with HTTPS-based authentication](https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/).  

So, we should update the `README` file with new SSH-based `git clone` commands.

**Comment by namdre** [comment]
Things like `git push` are already affected and we're using tokens for this. Since we don't need tokens for `git clone` I don't think this is affected (nor should it be because sumo is readable without authentication).

**Comment by vijay-jaisankar** [comment]
Awesome, thanks for the info.
