### ISSUE TITLE
How can I let the vehicles enter to free lanes in the downstream segment

### ISSUE THREAD

**Issue by lightly-lyx** [eclipse/sumo#10821]
there is a spillover in the downstrem, but still some space in another lane, how can I let the vehicle drive to the free lane in the green time.
![微信截图_20220530110316](https://user-images.githubusercontent.com/44825306/170957902-5c2a2ed0-419a-451d-b945-32af8bde4d6c.png)

**SUMO-version:**1.8

**operating system:**python

**Comment by lightly-lyx** [comment]
Even I have added connections from upstrem lane to both of the two downstrem lanes, vehicles can move to the free lane. It is really make my frustrated. Your help will be appreciated!

**Comment by namdre** [comment]
possibly, the left lane is not useful for continuing the route of the vehicle. Feel free to attach your scenario files for closer inspection.

**Comment by behrisch** [comment]
closing for lack of feedback, please add a comment if you can share more info
