### ISSUE TITLE
Can i check trafficlight logic for conflicts or access junction conflict information on runtime via TraCI?

### ISSUE THREAD

**Issue by julisokay** [eclipse/sumo#10834]
I'd like to create new trafficlight logic in runtime without the risk of collision. Is there a way to check wether a given Logic object would possibly create conflicts for a trafficlight? I know the junction has this information stored in the .net.xml file with the response and foes bitset. A possible workaround would be parsing the xml on runtime for said junction controlled by the targeted trafficlight, but before i start doing that i thought maybe there already is a solution to that.

**SUMO-version:**
1.12
**operating system:**
Python

**Comment by namdre** [comment]
see https://sumo.dlr.de/pydoc/traci._lane.html
lane.getFoes
lane.getInternalFoes
lane.getLinks

also trafficlight.getControlledLinks
