### ISSUE TITLE
file not found when run osmWebwizard.py

### ISSUE THREAD

**Issue by tiny-un1verse** [eclipse/sumo#10832]
**SUMO-version:1.13.0
**operating system:Ubuntu22.04
As shown in the screenshot, I installed SUMO 1.13.0 on Ubuntu 22.04 via Sudo. When I run the osmWebwizard.py file, it says file not found, but there is index.html in the webWizard folder.Is it because I'm using Ubuntu22.04?

![image](https://user-images.githubusercontent.com/93510416/171077925-677f5dff-cf01-4be2-9313-780d77bd4536.png)
![image](https://user-images.githubusercontent.com/93510416/171078696-04b42bdc-349f-4bbb-9681-f04dbda72b08.png)

**Comment by usamael2000** [comment]
I think this problem is related to snap, as the default Firefox currently is the snap version. You may try to run Firefox from terminal with --no-sandbox

**Comment by tiny-un1verse** [comment]
Thanks a lot!
The problem is caused by the snap version.
I tried running firefox with no-sandbox but it still didn't work, so I uninstalled firefox and installed it from its official website and then I was able to run osmWebWizard.py!

**Comment by behrisch** [comment]
Just for the records: The snap version of firefox on ubuntu 22.04 works fine here
