### ISSUE TITLE
misplaced actuation detector on internal lane

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#10838]
a detector which is moved to an internal lane may get a position much further upstream than the rest. see e1Detector:KennedyPlatz_0_D14.3 in BS

**Comment by behrisch** [comment]
I though the problem was that the detector got moved to far (was not moved to the end of the internal lane as expected)

**Comment by namdre** [comment]
one detector was moved as far as "intended" (which includes internal lanes by design) and the others were not moved because they had multiple predecessor (internal) lanes.
