### ISSUE TITLE
Vehicles trying to change lane while they have stopped before in the signal queue

### ISSUE THREAD

**Issue by MohamadReza-Haghani** [eclipse/sumo#10847]
Hi,

I am using an e2 detector close to an intersection. There are three lanes close to the intersection in my network. The left lane is an exclusive left-turn lane. The middle lane can be only used for going through. And, the right lane can be used by the vehicles going through and right turning vehicles. I saw that some vehicles that are in the right lane queue try to move to the left lane when they have stopped before in the right lane. Here in the attached screenshot, you can see that the fourth vehicle in the right lane tries to move to the left lane, and the third vehicle in the middle lane reduced its speed because of that. All the vehicles in the screenshot should go through. Therefore, the reason of lane-changing is not being at a dead lane.

Regards,
Reza.
 
![Capture2](https://user-images.githubusercontent.com/64617116/171209830-9e8c68e4-c40b-4413-b70d-9d8ac114dab0.JPG)

**SUMO-version:1.10.0**

**operating system: Windows**

**Comment by namdre** [comment]
The reason for lane changing is speedGain. The fourth vehicle can advance in the middle lane and thereby reach it's destination a bit earlier. The general affect from this is that all lanes that are valid (for continuing the route) have queues of similar length.
