### ISSUE TITLE
Invalid representation of Containers in NETEDIT

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#10844]
- [x] Path creator doesn't shown
- [x] Lines attribute isn't written
- [x] Invalid representation in NETEDIT
- [ ] Problem loading ContainerPlans

![Sin título](https://user-images.githubusercontent.com/8238561/171187106-7eb222bf-313a-4748-8f3a-22a2a3472b06.png)

**Comment by namdre** [comment]
If any of this is a regression, we should separate the tickets into regressions and "original" bugs.

**Comment by palvarezlopez** [comment]
Path creator doesn't shown is a regression
