### ISSUE TITLE
split citymobil test

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#10842]
into several smaller ones for the older and the newer implementations

**Comment by namdre** [comment]
also, it seems that the current tests don't actually run the scenario (at least the taxi version). This way we don't even get to see the effects of #10822, #10823

**Comment by namdre** [comment]
Tests behavior looks fine now. Though I'm not sure why there are 8 tests even though the runner code only has 4 different branches.

**Comment by behrisch** [comment]
In theory there are six cases 2 with the taxi network (the ones prefixed with person) with busses and with cyber cars and four old ones (agent scheduling and simple scheduling with busses and with cyber cars). In practice they all look different and I have to check why
