### ISSUE TITLE
POI Colour Filters for Images

### ISSUE THREAD

**Issue by vijay-jaisankar** [eclipse/sumo#10848]
## Relevant Files

The following files are relevant to this conversation:

`pink.png`
![pink](https://user-images.githubusercontent.com/56185979/171292223-cb578d46-e4f8-48b6-83c6-0bf253c03287.png)

`green.png`
![green](https://user-images.githubusercontent.com/56185979/171292228-7ac8c58e-4359-4f83-bd42-f8785d165b4c.png)

## Situation Context

While initialising a POI in TraCI, the`x`, `y`, and `color` attributes are mandatory.  
If we initialise the POI with an `imgFile`, the `color` provided acts as a filter for the image. 

For example,
```py
traci.poi.add(poiID="demo100", x = 3834.7883983257707,  y = 3268.0471488538005, color=(255,0,0), layer = 202.0, imgFile="/home/vijay/Pictures/pink.png") 
```
Here, we can see the superimposition of the red in the `color` attribute and the pink of `pink.png`.
![Image Filter](https://user-images.githubusercontent.com/56185979/171289968-a476faf5-6509-42da-8061-316018349024.png)

If one wishes to use the same colour as the image provided (i.e "no filter"), they would have to pass the color as `(255,255,255)` + alpha(if desired).

For example,
```py
traci.poi.add(poiID="demo100", x = 3834.7883983257707,  y = 3268.0471488538005, color=(255,255,255), layer = 202.0, imgFile="/home/vijay/Pictures/pink.png")
```
![Raw Image](https://user-images.githubusercontent.com/56185979/171290488-ba6ea707-e222-4987-8773-de66514bbc81.png)

While this "compounding" colour aspect might be surprising at first glance, a problem occurs as the same filters are applied to any new image file for the POI (`setImageFile` arguments). Unless a user knows about this effect, they will get very confused as the colour they're expecting might not manifest in the image.

For example,
```py
traci.poi.add(poiID="demo100", x = 3834.7883983257707,  y = 3268.0471488538005, color=(255,0,0), layer = 202.0, imgFile="/home/vijay/Pictures/pink.png") 
traci.poi.setImageFile("demo100", "/home/vijay/Pictures/green.png")
```
![Changed Image](https://user-images.githubusercontent.com/56185979/171291377-ebd28411-bbcc-4dc7-a6e7-c26116abf703.png)
We can see the effect of the initial filter.

## Proposed Changes
- Documentation updates to tell the users about the addition of the colours in `color` and the image itself while creating the POI.
- Making `setImageFile` a compound operation
```py
def setImageFile(self, poiID, imageFile, keepFilters = False):
        """setImageFile(string, string) -> None

        Sets the image file of the poi.
        Resets the color of the image if keepFilters is not set

        """
        if not keepFilters:
                self._setCmd(tc.VAR_COLOR, poiID, "c", (255,255,255))
        self._setCmd(tc.VAR_IMAGEFILE, poiID, "s", imageFile)

```

If this sounds like a good idea, can I please work on this and make a PR for the same? 

Thanks,
Vijay

## Additional Information

**SUMO-version: 1.13.0**
**operating system: Linux**

**Comment by namdre** [comment]
- I agree with extending the documentation 
- extending the python code in the proposed way would lead to an inconsistency between traci and libsumo (or rather between the C++ API and the python API), hence I'm reluctant about this
- right now, the default color for pois added via xml input is "red". I think it might be useful to change the default to "white" if the user has set the 'imgFile' attribute.

@behrisch thoughts? (in particular on the consistency)

**Comment by behrisch** [comment]
I agree with changing the default color when adding pois with an image file but I don't think we should change the existing setImageFile method. If you absolutely need it, just add another method (setRawImageFile or sth like that, better names are welcome :-)) which can be "imported" into libsumo like the other helper methods.

**Comment by vijay-jaisankar** [comment]
Thanks for your points @namdre @behrisch 

After looking at the issue a bit more, I agree that the new method might be overkill.

After looking through the code, I could not find where the "red as default on xml input" condition was defined, can you please guide me to the same? 

Thanks

**Comment by vijay-jaisankar** [comment]
This PR (#10848) contains the changes pertaining to the `default colours` point
