### ISSUE TITLE
lock mode does not work as expected

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#10863]
- [x] rectangle selection adds locked junctions even if they are locked
- [x] if edges are locked, they can still be inspected as part of an "overlapped" group
- [x] if junctions are locked, edges cannt be inspected when overlapped by a junction
- [x] if 'lock selected' is active and an edge is selected, overlapping edges in the same spot cannot be selected
- [x] locking an edge via 'lock selected' has no impact on connection mode. It should prevent clicks from going to the locked 
- [x] if 'lock selected' is active and an edge is selected, overlapping edges in the same spot, both selected and unselected edges show up in the 'overlapped' group

**Comment by namdre** [comment]
relevant for #11197

**Comment by palvarezlopez** [comment]
Fixed

**Comment by namdre** [comment]
I can still replicate error nr 2.
