### ISSUE TITLE
how to avoid surrounding participants collide with the ego car

### ISSUE THREAD

**Issue by Yangangren** [eclipse/sumo#10864]
I have an issue: the ego car is added in the traffic by traci.moveToXY() at each step, but the surrounding cyclists and vehicles seem not to realize the ego and will collide with it. How to aviod this problem?

**Comment by namdre** [comment]
please provide a minimal scenario that shows the problem (preferably with a log of traci commands instead of your own traci script: https://sumo.dlr.de/docs/TraCI/Interfacing_TraCI_from_Python.html#generating_a_log_of_all_traci_commands
