### ISSUE TITLE
Is it possible to get the shape of the lanearea similar to the shape of the lane?

### ISSUE THREAD

**Issue by JamesPsh** [eclipse/sumo#10861]
Is it possible to get the shape of the lanearea similar to the shape of the lane?
(ex : https://sumo.dlr.de/pydoc/traci._lane.html#LaneDomain-getShape)

I've been trying to get the coordinates of the car by positioning it on a laneposition using a specific moveTo, but it doesn't work. Even if I adjust the position of the car with moveTo, the car is not positioned exactly where I want it to be.
As in the code below, when I try to place the car in 5.0, it is not located there.

traci.vehicle.moveTo(vhcl_id, lane_id, pos = 5.0)
traci.simulationStep()
traci.vehicle.getLanePosition(vhcl_id)
results : 12.55245

**Comment by JamesPsh** [comment]
My question about the moveTo function has been solved.

I just want to know if there is a way to immediately know the shape of the lanearea.

**Comment by namdre** [comment]
for others reading this: moveTo is executed before vehicle movements so at the next simulation step, the vehicle has already moved from the assigned position

you can get the length of the lane (as experienced by the drivers) with traci.lane.getLength and the geometrical shape (which may have a different length) with traci.lane.getShape. This gives you the center-line of the lane. If you need the sides of the lane, use sumolib.geometry.move2side(shape, +/- halfLaneWidth)
