### ISSUE TITLE
recheck battery model defaults

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#10883]
the code in EnergyParams.cpp refers to the Springer publication after the SUMO 2013 conference but the values deviate (especially mass and recuperation efficiency). It has a changed default for mass which probably fits better a standard vehicle (1000kg) but not for front area which is too big for a standard car (probably something between 2 and 2.5). Furthermore it has recuperationEfficiencyByDecel which is 0 by default and documented nowhere.

The defaults should be modified such that they fit a standard passenger car (bonus points for a reference).

**Comment by namdre** [comment]
something like this: https://sumo.dlr.de/docs/Models/Electric.html#example_configurations ?

**Comment by behrisch** [comment]
yes, much better, although I would prefer to approximate the front surface by an ellipse rather than a rectangle and default to height * width * PI / 4.
