### ISSUE TITLE
 the effect of lane width on road capacity

### ISSUE THREAD

**Issue by JaydenGao-gjd** [eclipse/sumo#10884]
Add your issue description here.

*If possible, upload an example that shows your problem.*

**SUMO-version:** 1.12.0

**operating system:** win10

Hello, I am researching the effect of lane width on road capacity; but when I change the lane width, the lane width has no obvious effect on vehicle speed and flow, can you give me some guidance?

**Comment by namdre** [comment]
in the default model, lane width has almost no effect (except very indirectly by influencing the shape and size of intersections).
However, if you activate the sublane model (https://sumo.dlr.de/docs/Simulation/SublaneModel.html) then multiple vehicles can fit on the same lane and capacity depends on width.
