### ISSUE TITLE
homebrew error on running netconvert

### ISSUE THREAD

**Issue by yangh0597** [eclipse/sumo#10893]
run: netconvert --node-files=hello.nod.xml --edge-files=hello.edg.xml --output-file=hello.net.xml

res:
dyld[4912]: Library not loaded: /usr/local/opt/gdal/lib/libgdal.31.dylib
  Referenced from: /Library/Python/2.7/site-packages/sumo/bin/netconvert
  Reason: tried: '/usr/local/opt/gdal/lib/libgdal.31.dylib' (no such file), '/usr/local/lib/libgdal.31.dylib' (no such file), '/usr/lib/libgdal.31.dylib' (no such file)

**Comment by yangh0597** [comment]
I use brew install, version is
![image](https://user-images.githubusercontent.com/86940083/173033260-b317e583-448b-4612-b3a6-e2ba9e7c40ce.png)

**Comment by yangh0597** [comment]
install use this 
![image](https://user-images.githubusercontent.com/86940083/173034058-70d9f7dd-12de-469d-886d-f85211aa691c.png)

**Comment by angelobanse** [comment]
Which version of gdal do you have installed? Check for gdal under `brew list --versions`

**Comment by behrisch** [comment]
could be related to #10935

**Comment by mesjou** [comment]
I experience the same error with `gdal 3.5.2_1`. Any recommendations how to solve this issue?

**Comment by angelobanse** [comment]
Downgrade to `gdal 3.5.1_2`

**Comment by mesjou** [comment]
I downgraded to `gdal 3.5.1_2`.

In the meantime I installed sumo with all the other requirements via 
`brew install --with-ffmpeg --with-gdal --with-gl2ps --with-open-scene-graph --with-swig --HEAD sumo`

No I receive this error message:

```
Could not connect to TraCI server at localhost:53613 [Errno 61] Connection refused
 Retrying in 1 seconds
dyld[26071]: Symbol not found: (_av_frame_make_writable)
  Referenced from: '/Users/user/.pyenv/versions/3.8.14/envs/venv-3.8.14/lib/python3.8/site-packages/sumo/bin/sumo-gui'
  Expected in: '/opt/homebrew/Cellar/ffmpeg/5.1.2/lib/libavcodec.59.37.100.dylib'
```

**Comment by yangh0597** [comment]
ok,thanks

**Comment by angelobanse** [comment]
> I downgraded to `gdal 3.5.1_2`.
> 
> In the meantime I installed sumo with all the other requirements via `brew install --with-ffmpeg --with-gdal --with-gl2ps --with-open-scene-graph --with-swig --HEAD sumo`
> 
> No I receive this error message:
> 
> ```
> Could not connect to TraCI server at localhost:53613 [Errno 61] Connection refused
>  Retrying in 1 seconds
> dyld[26071]: Symbol not found: (_av_frame_make_writable)
>   Referenced from: '/Users/user/.pyenv/versions/3.8.14/envs/venv-3.8.14/lib/python3.8/site-packages/sumo/bin/sumo-gui'
>   Expected in: '/opt/homebrew/Cellar/ffmpeg/5.1.2/lib/libavcodec.59.37.100.dylib'
> ```

Did you also install sumo via pip?

**Comment by mesjou** [comment]
Yes, this was the error. Removing sumo from virtual environment and adding
```
if 'SUMO_HOME' in os.environ:
    tools = os.path.join(os.environ['SUMO_HOME'], 'tools')
    sys.path.append(tools)
else:
    sys.exit("please declare environment variable 'SUMO_HOME'")
```
before running `import traci` fixed the issue for me.

**Comment by angelobanse** [comment]
@yangh0597 is it working for you?
