### ISSUE TITLE
Crash of sumo-gui when setting up GL2 compatible shaders

### ISSUE THREAD

**Issue by RNippold** [eclipse/sumo#10895]
When trying to execute a 3D simulation in sumo-gui, it crashes with to following error: 

"StatsHandler::StatsHandler() Setting up GL2 compatible shaders". 

The network is loaded successfully, I can rotate and navigate through the network. Furthermore, the command line version can execute this simulation example successfully. 

SUMO version: v1_13_0+0703-89572ed5a65
OS: linux (but crashes under windows as well)
[3d_demo.zip](https://github.com/eclipse/sumo/files/8870160/3d_demo.zip)

**Comment by m-kro** [comment]
Probably related to custom 3D shapes for vehicles

**Comment by RNippold** [comment]
Appeared to be a problem related to specific 3ds models...

**Comment by behrisch** [comment]
nevertheless whatever strange models I feed to sumo it should not crash
