### ISSUE TITLE
3D signal enhancements

### ISSUE THREAD

**Issue by m-kro** [eclipse/sumo#10913]
![grafik](https://user-images.githubusercontent.com/33294728/173346336-666626ac-62b8-493a-b5dd-06e70a0033bc.png)
The semi-transparent "dome" around the traffic signal erases the lane-based signal state spheres behind. They should remain visible behind/inside the "dome". Only happens under certain view angle.

**Comment by namdre** [comment]
- do we even need the dome?
- can we try to draw the signal mast to the side of the road? 
   - Where is the location currently configured?
   - Where is this documented?

**Comment by behrisch** [comment]
Actually I like the dome (but I may be biased ;-)) It is a good compromise between the very technical "link markers" on the street and light coming directly from traffic light pole which is hardly visible if you get the angle only slightly wrong (and which is not a light source in the OSG sense which makes it even harder to see). But I agree that having link markers and the dome on by default is maybe too much. So maybe we need some config saying for each of "dome", "link markers" and "model" whether they should be visible and the default for dome is off.

**Comment by m-kro** [comment]
Well I see several options with respect to your proposals.

- Shorten the "anti-glare shield" of the 3D model so that the signal state can be seen better
- Add options in the visualisation settings (in junctions tab like other TL settings?): Checkbox ~ "Show TL link markers in 3D view", Checkbox ~ "Show dome" (needs better wording)
-  Alternatively add option to build a "3D signal bridge/cantilever" automatically and make the link markers semi-transparent if drawn. Then the old way of adding additional 3D signal poles at custom locations can either stay or be deprecated.

**Comment by m-kro** [comment]
- [x] Shorten anti-glare shield of 3D traffic light model
- [x] Adding a gui settings checks "draw 3D tls link markers"
- [ ] Adding another check that draws auto-generated poles
- [x] Adding a third check that toggles the "dome"

**Comment by m-kro** [comment]
A short glimpse on how the auto-generated TLS models look like:
![grafik](https://user-images.githubusercontent.com/33294728/176198104-dcc3b515-8049-4061-9c70-937d64f3c528.png)
They reuse the same 3D models as the TLS placed through the decals table (pole and signal part have been split for that reason).

**Comment by m-kro** [comment]
The original problem with the wrong transparency seems not so easy to fix. Maybe it gets better if the bubble is not underground for half of its body but just covers the signal... If that does not work, we can also just leave it like that.

**Comment by behrisch** [comment]
Does this mean we do not need the traffic light files in sumo/data/3D any longer?

**Comment by m-kro** [comment]
No, we need them. They are used both for the auto-generated model as for the ones placed through the decals table. The auto-generated model is just a mix of three poles with adjusted scale and orientation and some signals.
