### ISSUE TITLE
May I know how the direction is determined in getLinks?

### ISSUE THREAD

**Issue by JamesPsh** [eclipse/sumo#10911]
May I know how the direction is determined in traci.lane.getLinks?

I've done some tests and I'm a little confused.
In all three cases below, R(r) should appear, but it is not.

I want to know by what criteria the direction is determined in getLinks.

print(traci.lane.getLinks(lane1)) # direction : R
print(traci.lane.getLinks(lane2)) # direction : s
print(traci.lane.getLinks(lane3)) # direction : r

![image](https://user-images.githubusercontent.com/101240964/173284697-e14e8c0c-ec43-46e8-9d09-95043c31bddd.png)

thank you

**Comment by namdre** [comment]
There are some angular thresholds to determine the direction code (https://github.com/eclipse/sumo/blob/df0e85a9185ea51dd5b62c93baca0cf964e317b2/src/netbuild/NBNode.cpp#L2223)

The focus of the direction codes is to distinguish the different connections from the same edge.  
Note, that the direction codes are strictly local so in the case of lane 1, the fact that the connection leads to a road with a 90 right turn downstream is not not factored into the computation.

**Comment by JamesPsh** [comment]
@namdre Thank you very much for your reply.
