### ISSUE TITLE
crash when drawing tazRelations

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#10929]

**Comment by palvarezlopez** [comment]
if (width != myLastWidth) {
            myLastWidth = width;
            // cast object (check this, is ugly)
            GNETAZRelData* TAZRelData = const_cast<GNETAZRelData*>(this);
            myNet->removeGLObjectFromGrid(TAZRelData);
            TAZRelData->updateGeometry();
            myNet->addGLObjectIntoGrid(TAZRelData);
        }

**Comment by palvarezlopez** [comment]
Use "Recalculate boundaries" after setting new exaggeration

**Comment by namdre** [comment]
regression in 1.11.0 via 741f72972ea09b1e9664a451f6f17ce728bc8572
