### ISSUE TITLE
Implementing randomTrips.py 

### ISSUE THREAD

**Issue by 22046364** [eclipse/sumo#10939]
When I try to make use of randomTrips.py I get the following TypeError:
is_fringe() got an unexpected keyword argument 'checkJunctions'

My CMD line is as follows:
python randomTrips.py -n test.net.xml -r map.rou.xml -e 1000 -l

I have ensured that rendomTrips.py is in my working directory, along with my test.net.xml file

I am working on Windows 11

**Comment by namdre** [comment]
probably due to a mismatch between SUMO / randomTrips.py version and sumolib version
