### ISSUE TITLE
make selection file work for data elements

### ISSUE THREAD

**Issue by yunpangfloetteroed** [eclipse/sumo#10936]
Add your issue description here.
   - see the title
   -The saved information about the selected TAZ-relations should at least include fromTaz, toTaz and the count

It would be more useful if the saved information can be loaded to netedit (or/and sumo-gui) again, just like the current feature "Load" under "Selection"

**Comment by namdre** [comment]
If you want to save only a selection, the recommended approach is to use the 'reduce' button which deletes everything except for the selection.

**Comment by yunpangfloetteroed** [comment]
just want to double check: is it already possible to change the width of TAZ-relation lines so that it will be easiler to click them for inspection.

**Comment by palvarezlopez** [comment]
Problem loading selection
