### ISSUE TITLE
Taxi vehicles get removed from simulation after dropping off their last passengers

### ISSUE THREAD

**Issue by BjoernPK** [eclipse/sumo#10933]
As part of a student thesis, we used SUMO, TraCI, and Python to implement a custom disposition system (based on parts of the "drtOnline" tool) for a fleet of 10 shuttle vehicles that receives ride requests from pedestrians at bus stops and assigns them to the vehicles (with taxi devices). After long, non-deterministic simulation times, individual shuttle vehicles are removed from the simulation after dropping of their last passenger, even though the `randomCircling` algorithm was selected to handle idle shuttles.

The simulation is based on a slightly modified version of the Brunswick scenario. Due to size constraints, the model can be downloaded [here](https://www.dropbox.com/s/79doft1qtywvpka/vivre_brunswick_issue.zip?dl=0). In addition, we created a TraCI log file named `traci_commands.log` that is part of the zip file. We stopped the test simulation immediately after the leaving of the vehicle was detected, i.e., you should be able to find the relevant situation not more than 45 seconds before the end of the log file. During the simulation it could be observed that the drop-off time was gradually decreased while the vehicles stops at its destination. When the value `0` was reached, the vehicle was removed from the simulation. With the predefined scheduling algorithms, no errors could be determined.

SUMO version: 1.3.0
OS: Windows 10

Feel free to contact me, if you have any additional questions. We would be very happy to find a solution to this difficult-to-debug problem - many thanks in advance for your support!

**Comment by namdre** [comment]
most likely the removal happens 8 hours after departure. See here on how to change this:

https://sumo.dlr.de/docs/Simulation/Taxi.html#idle_behavior
https://sumo.dlr.de/docs/Simulation/Taxi.html#taxi_behavior

Please report whether setting a larger value solves your problem.

**Comment by BjoernPK** [comment]
Unfortunately, setting the parameter with `<param key="device.taxi.end" value="1000000"/>` to a larger value did not bring any change. All shuttle vehicles are inserted at the beginning of the simulation - in the current simulation run, the first vehicle was removed after 7784.8 seconds.

Please find an updated Traci log file (with deactivated getters) attached.

**Comment by namdre** [comment]
There were recent fixes which might have been related to your problem (#10860, #10859). Please try with the latest development version.

**Comment by BjoernPK** [comment]
I have now executed the simulation again with the latest development version. Unfortunately, the error occurred again. Please find an updated log file attached.

[traci_commands_3.log](https://github.com/eclipse/sumo/files/8916326/traci_commands_3.log)
