### ISSUE TITLE
Homebrew Update made gdal 31 instead of 30 

### ISSUE THREAD

**Issue by rhata23** [eclipse/sumo#10935]
I am trying to run sumo via traci. Everything was working fine until I reinstalled sumo, and when I ran the program again I am getting this error: 

Library not loaded: /usr/local/opt/gdal/lib/libgdal.30.dylib

Not sure how to fix this.

**SUMO-version:**
1.13.0

**operating system:**
Mac Monterey

**Comment by namdre** [comment]
How did you fix your problem?
