### ISSUE TITLE
the speed does not match with --fcd-output and --save-state.files when a record period is given

### ISSUE THREAD

**Issue by minnie-jo** [eclipse/sumo#10945]
When running the following command:

`sumo -c erlangen.sumo.cfg --device.fcd.period 500 --fcd-output save500.fcd.xml --save-state.times 500 --save-state.files save500.xml`

, the speed information does not match. It's `0.1` off. In other words, I will get the matching speed information, only when I execute the following command:

`sumo -c erlangen.sumo.cfg --device.fcd.period 499.9 --fcd-output save500.fcd.xml --save-state.times 500 --save-state.files save500.xml`

Is this intended?

**SUMO-version: 1.8.0

**operating system: MacOS

**Comment by namdre** [comment]
Yes.  States are saved at the beginning of a time step (before vehicle movements take place) whereas fcd-output is saved at the end of a time step (after movements). See #1463
