### ISSUE TITLE
netdiff.py: support saving and loading configurations

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#10942]
netdiff.py uses positional arguments.  What would be a good way to include these in a config file?

**Comment by behrisch** [comment]
The argument parser supports names for positional args already. So instead of parsing only the known args we could give names to the positionals and use them in the config

**Comment by namdre** [comment]
Effectively this would provide an alternative to pass positional args as named args by using those names, right? That would be a good thing in general for all our position args.

**Comment by behrisch** [comment]
yes

**Comment by vijay-jaisankar** [comment]
![Positional Arguments](https://user-images.githubusercontent.com/56185979/174124432-1e3c2512-f7a7-4b61-91f4-50f646855650.png)

As per the above analysis, these files use positional arguments, we can update these to make them use named arguments. 
If this seems like a good idea, please assign me to the same.

**Comment by behrisch** [comment]
not every script which refers to sys.argv has positional arguments and this ticket refers more to the ArgumentParser being used to parse the only some of the arguments but if you feel like it please go ahead

**Comment by namdre** [comment]
before there is another misunderstanding, **we are striving for backwards compatibility here**. Positional arguments should still be usable but there should also be a way to use named arguments instead.

**Comment by behrisch** [comment]
Actually it is not about new options at all it is just about the parsing code. The argument parser can give the positional argument an _internal_ name which should be used in the config as well.

**Comment by vijay-jaisankar** [comment]
I was thinking of doing something similar to the scheme in `tools/game/racing.py` (with special consideration to any default arguments used in the functions.) Would that be okay?

**Comment by behrisch** [comment]
No, actually not. argparse supports both "real" options starting with "-" or "--" and positional arguments which get an internal name see https://docs.python.org/3/library/argparse.html#the-add-argument-method. My proposal was to replace the positional arguments which are currently extracted from the remaining args by the named args of argparse

**Comment by vijay-jaisankar** [comment]
Thanks for the info, so from what I understand, if we have something like
```py
def main(in, out, opt=10):
  # Function body
```
The parser would be like
```py
parser.add_argument('in', ...)
parser.add_argument('out', ...)
parser.add_argument('-opt', ...)
```

Is this correct?

**Comment by behrisch** [comment]
yes although Iwould not state it in terms of the main function but rather how the script can be called from the command line. So it needs to be `script.py infile outfile` with an optional `-opt` switch

**Comment by vijay-jaisankar** [comment]
Okay, thanks for the clarification!

I'll work on the PR and send it soon.

**Comment by vijay-jaisankar** [comment]
This PR (#10975) contains said changes. Not sure why the tests are failing though.

**Comment by behrisch** [comment]
This is deviating a little from the original issue. The PR does not even touch netdiff. Furthermore we would like to use our own sumolib.options.ArgumentParser because that's the only way to support config saving

**Comment by vijay-jaisankar** [comment]
Thanks for the feedback.

The PR contains changes for the files in the above image (https://github.com/eclipse/sumo/issues/10942#issuecomment-1157910983)

I will use `sumolib.options.ArgumentParser` and update the PR, and add changes for the netdiff file too if required.

**Comment by behrisch** [comment]
No, it is probably more like 
```
optParser.add_argument("source", help="source network")
...
```

**Comment by vijay-jaisankar** [comment]
Sure thing, the three lines above were the existing code which I will change as you mentioned.

**Comment by behrisch** [comment]
@vijay-jaisankar Please see my last commit maybe it makes things clearer. Now you can save positional args to configs and load them. It currently works only as an "appender" so the positional args from the config are only added to the args present on the command line (but in the expected order even if they have a different order in the config file). So the common cases of giving all or none of them in the config or the command line are covered. What is still missing is the possibility to overwrite a (positional) config value with a value on the command line. Also maybe there was a misunderstanding with @namdre: this will not allow got give named arguments for the positionals on the command line just in the config.

If overwriting is not needed we could close this.

**Comment by behrisch** [comment]
whenever we feel like overwriting positional arguments is an issue we should open a new ticket
