### ISSUE TITLE
sumo-gui shows black screen if opened via Traci 

### ISSUE THREAD

**Issue by rhata23** [eclipse/sumo#10946]
Hello,

I am trying to run a simulation via TracI, however when TracI opens sumo, there are no errors but the screen is black. When I open sumo-gui through the terminal, the screen shows all of the edges. I reinstalled sumo to see if that would solve the issue but it did not. I checked to see if the Sumo_Home is set correctly and itis. 

I am not sure how to fix this error and any help would be greatly appreciated. 

Opened by Traci
<img width="758" alt="Screen Shot 2022-06-15 at 1 54 27 PM" src="https://user-images.githubusercontent.com/66279607/173893212-936826cb-675b-4ca9-9051-eeaed3ae3e30.png">

Opened via Terminal 

![Screen Shot 2022-06-15 at 1 56 15 PM](https://user-images.githubusercontent.com/66279607/173893555-30bfd5d7-af7b-46f1-be87-453f10393241.png)

**SUMO-version:**
1.13

but at the top of where I am running via traci it says SUMO v1_12_0+1347-4683761ae0c

**operating system:**
MacOS Monterey

**Comment by namdre** [comment]
You have two versions of sumo on your system. Remove the one that doesn't work and set SUMO_HOME to the one that does (also check how your traci script finds sumo because this may vary from script to script).
