### ISSUE TITLE
Can I know the x,y coords at a specific position in lane?

### ISSUE THREAD

**Issue by JamesPsh** [eclipse/sumo#10948]
Can I know the x,y coords at a specific position in lane?

All I know is the position in the lane where a point is located.
And what I want to know is the x,y coordinates of that point.

It seems that knowing the coordinates gives me a position in the lane,
(ex : traci.simulation.convertRoad(x, y))

but I would like to know if the reverse is also possible.

Should I put the vehicle over there and get the car's coordinates?

![image](https://user-images.githubusercontent.com/101240964/174026514-14152eb2-6f00-4849-9d81-d3ca3b3cee11.png)

Thank you~!

**Comment by behrisch** [comment]
Yes, there is [traci.simulation.convert2D](https://sumo.dlr.de/pydoc/traci._simulation.html#SimulationDomain-convert2D)

**Comment by JamesPsh** [comment]
@behrisch Oh thank you very much.

Can I know the angle of the lane at a given position as well?

**Comment by JamesPsh** [comment]
@namdre I'll be able to use it soon. thank you~!
