### ISSUE TITLE
inspect mode: discrete choice dropdown is too narrow

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#10955]
The dropdown for junction attribute 'type' has names that are wider than the default frame width. This makes it hard to select the junction type without expanding the frame width.

There may be a way to make the expanded dropdown panel be wider than it's parent widget

**Comment by palvarezlopez** [comment]
@namdre my 
![Sin título](https://user-images.githubusercontent.com/8238561/174082018-421c940b-baef-40a8-8fcc-e9d19293e1d2.png)
proposal:

**Comment by namdre** [comment]
yes. this is what i mean
