### ISSUE TITLE
Remote controlled vehicles in junction should trigger collision warnings

### ISSUE THREAD

**Issue by jjyyxx** [eclipse/sumo#10952]
May be related to #6327. By setting `--collision.action` to `warn`, a remote-controlled vehicle (using movetoXY) collision can be detected on lane. However, remote-controlled vehicle collisions are still undetected in junction with `--collision.check-junctions` set.

```python
import traci

def main():
    sumo_args = [
        "sumo-gui",
        "--configuration-file", "./test.sumocfg",
        "--step-length", "0.1",
        "--collision.action", "warn",
        "--collision.mingap-factor", "0",
        "--collision.check-junctions",
        "--seed", "1"
    ]
    traci.start(sumo_args)

    traci.simulationStep(20.0)

    variant = "junction"  # "junction" or "lane"
    if variant == "junction":
        move_id = "carflow_-9_3.1"
        move_coord = (98.42, 131.43, 170.0)  # Rough position of carflow_-9_3.0
        traci.vehicle.moveToXY(move_id, '-1', 0, *move_coord, keepRoute=0b011)
        traci.simulationStep()
        traci.vehicle.moveToXY(move_id, '-1', 0, *move_coord, keepRoute=0b011)
        traci.simulationStep()
        collisions = traci.simulation.getCollisions()
        print(collisions)
    else:
        move_id = "carflow_-3_11.1"
        move_coord = (135.32,117.02, 290.0)  # Rough position of carflow_-3_11.0
        traci.vehicle.moveToXY(move_id, '-1', 0, *move_coord, keepRoute=0b011)
        traci.simulationStep()
        traci.vehicle.moveToXY(move_id, '-1', 0, *move_coord, keepRoute=0b011)  # ... A
        traci.simulationStep()                                                  # ... B
        collisions = traci.simulation.getCollisions()
        print(collisions)

    traci.close()

main()
```
The scenario files are available at https://gist.github.com/jjyyxx/779e4245b63551f75b6a730138a5ab83#file-test-net-xml.

For variant `lane`, without the line `A` AND `B`, the collision is undetected. With line `B` and optionally line `A`, the collision can be detected. I do not fully understand the mechanism why the first `moveToXY + simulationStep` does not lead to a detected collision (maybe something documented in [Application order of traci commands and simulation step](https://sumo.dlr.de/docs/TraCI/Change_Vehicle_State.html#application_order_of_traci_commands_and_simulation_step)? ), but it fits our need overall (call moveToXY at every step).

For variant `junction`, the collision can not be detected under any condition/combination I tried out.

**SUMO-version:** 1.13.0

**operating system:** Windows 10 / Ubuntu 20.04.4

**Comment by namdre** [comment]
The undetected collision on the junction is actually a bug in moveToXY (the vehicle is positioned "outside" the network even though it should clearly be on the junction)

**Comment by namdre** [comment]
The collision on lane was fixed in b13d83826e0fc611c159c131b59c1996703f794e

**Comment by jjyyxx** [comment]
I build the binary at commit e61024982871731e78d222e3fa1048262d3f6d2a, the sumo-gui title is `SUMO v1_13_0+0979-e6102498287`. But the problem I described seems to persist. Not sure if I missed something.

**Comment by namdre** [comment]
The 'junction' case isn't fixed yet but the 'lane' case is flagged as a collision on my end.

**Comment by jjyyxx** [comment]
Thanks, I got it. I misread your commit message previously.

**Comment by namdre** [comment]
The parallel bicycle lane across the intersection was throwing off the moveToXY mapping.

**Comment by jjyyxx** [comment]
Thanks! Can confirm this working on `SUMO v1_13_0+1024-fd2ab534e53`. 😄 

Any schedule for a stable release?

**Comment by namdre** [comment]
https://github.com/eclipse/sumo/milestones (though the July milestone might be pushed back to August due to vacations).
