### ISSUE TITLE
Is it not available to get data of lanearea using traci.junction.subscribeContext?

### ISSUE THREAD

**Issue by JamesPsh** [eclipse/sumo#10960]
Is it not available to get data of lanearea using traci.junction.subscribeContext?
I want to get the data of all laneareas that exist on the network, but I get the following error

![image](https://user-images.githubusercontent.com/101240964/174232223-118c203b-5a5d-44c2-ba51-0c6f61ad33cc.png)
![image](https://user-images.githubusercontent.com/101240964/174232518-c21b821a-6279-40a2-b73e-0515f1899b05.png)

**Comment by JamesPsh** [comment]
I reinstalled sumo, but retrieve doesn't work. How could I use the above features?

**Comment by namdre** [comment]
Did you install the latest nightly build (https://sumo.dlr.de/docs/Developer/Nightly_Build.html)?
Make sure that this is also the version being launched by your traci script (i.e. launch with sumo-gui and check the version printed in the window title bar).

**Comment by JamesPsh** [comment]
oh! thank you. the problem was solved.
