### ISSUE TITLE
randomTrips.py: patch comment header of output files processed by duarouter

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#10973]
when running randomTrips with option **--validate** the trips are processed by duarouter and the fact that they were created by randomTrips.py is no longer retrievable from their header. (The same applies when generating route output with option **-r**)

**Comment by behrisch** [comment]
@bcoueraud87 for you

**Comment by namdre** [comment]
@bcoueraud87 only the part **"The same applies when generating route output with option -r"** is still missing.

**Comment by namdre** [comment]
@behrisch Do you see a feasible way of testing this with texttest? I mean, can we overwrite the **run_dependent_text** setting for a single test? We still need to filter out the timestamp but could keep the rest of the  header comment since it's all relative paths.

**Comment by behrisch** [comment]
No, I don't think so but just try it out
