### ISSUE TITLE
Show demand amount of selected TAZ-relations

### ISSUE THREAD

**Issue by yunpangfloetteroed** [eclipse/sumo#10983]
Users can see 

(1) the demand amount (to, from or both) of each selected TAZ-relation
(2) the total demand amount of selected TAZ-relations

directly in netedit.

**Comment by namdre** [comment]
- The widgets in the top bar already permit selecting the dataset, dataType, interval and attribute (i.e. count).
- with the buttons "only draw TAZRel from" etc. we can select whether from,to or both are shown
- by inspecting a TAZ we can select whether this setting shall be applied to one or all TAZ (see #10972)

All we need is a place where we can write the sum of all attribute values.   @palvarezlopez How about in the bottom of the inspect frame (only when in data mode)?

**Comment by palvarezlopez** [comment]
Will be implemented here: #11735
