### ISSUE TITLE
Getting e2 detector output using command line

### ISSUE THREAD

**Issue by MohamadReza-Haghani** [eclipse/sumo#10989]
Hi,

I was wondering if there is a way to get the output of e2 detectors through the command line. I get all of the other outputs using the command line's commands in python as you can see in the attached screenshot. 

Regards,
Reza.

![Capture1](https://user-images.githubusercontent.com/64617116/174687537-b5c52f89-4340-46d1-9042-61ba567d110f.JPG)

**SUMO-version: 1.10.0**

**operating system: Windows 10**

**Comment by namdre** [comment]
No. Detectors require multiple parameters and must therefore be defined in an additional file.
