### ISSUE TITLE
Questions regarding lane change status

### ISSUE THREAD

**Issue by pradeeporuganti** [eclipse/sumo#10987]
Hello,

I am running a simple script to understand lane changes for different lane change model parameters in a given simulation. I specify the model parameter distribution in the config files and write a simple python script to report states. I do not force any lane changes and only use the 'get' commands relating to lane changes. At each time step I am requesting the following:

print('id', vehID, 'status:', traci.vehicle.getLaneChangeStatusPretty(vehID, 1), 'success:', traci.vehicle.wantsAndCouldChaneLane(vehID, 1))

I am trying to understand the output, for example:

id 727 status (['left', 'right', 'sublane'], ['right', 'sublane']) success True
id 776 status (['left', 'strategic', 'urgent', 'blocked by left leader', 'overlapping'], ['left', 'strategic', 'urgent', 'blocked by left leader', 'overlapping']) success False

I have the following questions:
1) Can i interpret the first list as what the vehicle has performed at this time step, and the right list as what was the command sent to it in the previous time step ?
2) What do states 'urgent' and 'overlapping' mean ? 
3) Is there a way to only report changes over lanes and not sublanes directly? I can imagine writing a small 'if' condition to check this if not. 
4) Does 'blocked by left leader' mean that the longitudinal distance to the leader in the left lane is more than the minimum longitudinal gap defined by the car-following model ?
5) Is there a way to report unsafe/ forced lane changes ?

I apologize for my many questions...

**Comment by namdre** [comment]
1. The first list is what the vehicle wanted to do and what obstructions it faced. The second list is a summary of the same information. See here: https://github.com/eclipse/sumo/blob/fedde589153949486337c6925d5c5b3377df7fd2/tools/traci/_vehicle.py#L851-L865
2. urgent: strategic change where surrounding vehicles (typically) perform cooperative speed adjustments
3. No. You have to do this filtering yourself. If you run a default simulation (no sublane stuff active), then the sublane flag will never appear
4. it means that the gap is less than the value deemed safe (see traci.vehicle.getSecureGap)
5. only by checking whether post-change gaps are shorter than the secure gap
