### ISSUE TITLE
Running jtcrouter.py on command line

### ISSUE THREAD

**Issue by jylee3302** [eclipse/sumo#10999]
Add your issue description here.

*If possible, upload an example that shows your problem.*
I'm trying to run jtcrouter.py with the options -n -t and -o as below at command line.
Nothing have worked in this machine. I have another machine and jtcrouter.py properly works in there, so I suppose it is this machine-specific issue. But, not aware of what to do to solve this. Already checked the PATH and SUMO_HOME part in the system environment variables.

Thank you very much as always.

**C:\Users\user\Desktop\test>jtcrouter.py -n osm.net.xml -t turnfile.xml -o output.xml**
usage: jtcrouter.py [-h] [-n NET] [-t TURNFILE] [-o OUT] [--turn-output TURNOUTPUT] [--flow-output FLOWOUTPUT]
                    [--turn-attribute TURNATTR] [-b BEGIN] [-e END] [-p COUNTPARAM] [--fringe-flows]
                    [--discount-sources] [--prefix PREFIX] [-a FLOWATTRS]

Route by turn counts

optional arguments:
  -h, --help            show this help message and exit
  -n NET, --net-file NET
                        Input net file
  -t TURNFILE, --turn-file TURNFILE
                        Input turn-count file
  -o OUT, --output-file OUT
                        Output route file
  --turn-output TURNOUTPUT
                        Intermediate turn-ratio-file
  --flow-output FLOWOUTPUT
                        Intermediate flow file
  --turn-attribute TURNATTR
                        Read turning counts from the given attribute
  -b BEGIN, --begin BEGIN
                        begin time
  -e END, --end END     end time (default 3600)
  -p COUNTPARAM, --count-param COUNTPARAM
                        the connection parameter to use as count
  --fringe-flows        Avoid overlapping flows (start only on the outside of the network)
  --discount-sources, -D
                        passes option --discount-sources to jtrrouter
  --prefix PREFIX       prefix for the flow ids
  -a FLOWATTRS, --attributes FLOWATTRS
                        additional flow attributes

**C:\Users\user\Desktop\test>jtcrouter.py what is going on?**
gives same result. even typing in jtcrouter.py results the same.

**SUMO-version:**
1.13.0-64-extra

**operating system:**
Windows 11

**Comment by namdre** [comment]
see https://sumo.dlr.de/docs/FAQ.html#the_python_scripts_do_not_accept_command_line_arguments_windows_only
