### ISSUE TITLE
Sumo convertRoad shows non-deterministic behavior

### ISSUE THREAD

**Issue by jjyyxx** [eclipse/sumo#11002]
With traci/libsumo, calling `convertRoad` at coordinate where a normal edge and a crossing edge meet shows non-deterministic behavior. Scenario files at https://gist.github.com/jjyyxx/ca403ab79d4fb34749c3370cb6e53b11

```python
import traci

def main():
    sumo_args = [
        'sumo',
        '--configuration-file', 'test.sumocfg',
        '--no-warnings',
        '--no-step-log',
        '--seed', '489553810'
    ]
    traci.start(sumo_args)

    print(
        traci.simulation.convertRoad(148.57147338, 92.28970517, False, 'passenger')
    )

    traci.close()

main()
```
**On Windows platform**, running this script several times get two different result `(':1_34', 27.011059759999995, 0)` (seems more likely) and `('5', 0.0, 2)`. (Tested on more than one computer + fresh installation). Within a single run, the result seems to be consistent.

**On Linux Ubuntu**, I did not find such an easy example, but a trace file shows consistent different behavior with `traci` `(':1_34', 27.011059759999995, 0)` and `libsumo` (adding LIBSUMO_AS_TRACI=1) `('5', 0.0, 2)`. (Only reproducible on some of my servers)
The trace file [trace.txt](https://github.com/eclipse/sumo/files/8955577/trace.txt) rename to `trace.py` to run.

**SUMO-version:** 1.13.0

**operating system:** Windows 10 / Ubuntu 20.04

**Comment by namdre** [comment]
was caused by memory-dependent sorting order of candidate lanes with equal scoring.
