### ISSUE TITLE
Are there anyone knowing what the extension in the vedio for SUMO is?

### ISSUE THREAD

**Issue by thinker310** [eclipse/sumo#11006]
Hello, I found an great extension for SUMO, and I wonder where I can download it? The link for this extension is here:https://www.youtube.com/watch?v=hoj-Abkp568
Thank you in advance!

**Comment by namdre** [comment]
Youtube gives you the details as
```
A Simulation Framework for Testing a Conceptual Hierarchical Autonomous Traffic Management System including an Intelligent External Traffic Simulation.

Henning, Sven;Biemelt, Patrick;Rüddenklau, Nico;Gausemeier, Sandra;Trächtler, Ansgar

In: Proceedings of the DSC 2018 Europe VR: New trends in Human in the Loop simulation and testing. Driving simulation and VR, S. 91-98, 2018 Driving Simulation Conference, Driving Simulation Association
```

I suggest you contact the publication authors directly since nobody who can give you the link will likely be viewing this issue.
