### ISSUE TITLE
Traffic Measures time intervals

### ISSUE THREAD

**Issue by icanfast** [eclipse/sumo#11019]
I'm trying to measure traffic in 10 minute intervals like this: 
```
<additional>
    <edgeData id="10" file="status_data.xml" start="0" end="600" excludeEmpty="True"/>
    <edgeData id="20" file="status_data.xml" start="600" end="1200" excludeEmpty="True"/>
    <edgeData id="30" file="status_data.xml" start="1200" end="1800" excludeEmpty="True"/>
    <edgeData id="40" file="status_data.xml" start="1800" end="2400" excludeEmpty="True"/>
    <edgeData id="50" file="status_data.xml" start="2400" end="3000" excludeEmpty="True"/>
    <edgeData id="60" file="status_data.xml" start="3000" end="3600" excludeEmpty="True"/>
</additional>
```
However the output intervals I'm getting always start with 0:
```
<interval begin="0.00" end="600.00" id="10">
<interval begin="0.00" end="1200.00" id="20">
<interval begin="0.00" end="1800.00" id="30">
<interval begin="0.00" end="2400.00" id="40">
<interval begin="0.00" end="3000.00" id="50">
<interval begin="0.00" end="3600.00" id="60">
```
Thereby my question is: are all the measurements actually begin at 0, or is it merely a typo. It's hard to infer myself since all the measurements are aggregated. And If it isn't a typo, maybe there is a workaround around this?

I'm running on macOS Big Sur 11.6.3, SUMO version 1.13.0

**Comment by namdre** [comment]
1) the attribute is called `begin`, not `start`
2) a single definition is enough to retrieve multiple intervals  `<edgeData id="data" file="status_data.xml" freq="600"/>`
