### ISSUE TITLE
Traffic Light cannot be built in NETEDIT

### ISSUE THREAD

**Issue by aminissn** [eclipse/sumo#11020]
After modifying the connections in some junctions, the traffic light cannot be built. NETEDIT warning message says: Junction "does not control any links; it will not be build."
Here is the network.
[tls_issue.net.zip](https://github.com/eclipse/sumo/files/8965728/tls_issue.net.zip)

**Comment by namdre** [comment]
The connections at that intersection all have attribute 'uncontrolled=true'.
A cause could be that the original network was imported from osm with option **----tls.uncontrolled-within** and the junction in question was "inside" a tls cluster.
