### ISSUE TITLE
macOS Monetery brew install issue

### ISSUE THREAD

**Issue by Anishkulkarni9001** [eclipse/sumo#11038]
I'm having difficulty installing SUMO with 'brew install' because of some cmake issue.
I keep getting the following output: 

brew install sumo
Warning: No available formula with the name "cmake" (dependency of dlr-ts/sumo/sumo).
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
Found a cask named "cmake" instead. Try
  brew install --cask cmake

However, cmake is already installed, and I have tried reinstalling multiple times, even uninstalling and reinstalling Homebrew altogether. Everything seems in order, but I can't figure out the problem.

**Comment by namdre** [comment]
How did you fix your problem?
