### ISSUE TITLE
Not sure why my buttons in Netedit on Sumo are very small

### ISSUE THREAD

**Issue by lindaludian** [eclipse/sumo#11037]
Whenever I open up Netedit on Sumo, the buttons are squeezed together and it makes it very hard to use. I have pasted an example below:

![3](https://user-images.githubusercontent.com/108088796/175359960-60057819-a568-4ed7-a792-79ac46b91ac9.JPG)

Similarly, on Java OpenStreetMap, I have the opposite problem where my buttons are overblown and the font size is too big. I have pasted an example of this below as well:

![4](https://user-images.githubusercontent.com/108088796/175360371-d8bfa669-3666-4500-8b02-eeacb2616a2e.JPG)

Can someone please help me with this and tell me why this is the case for both these softwares?

**Comment by lindaludian** [comment]
Sorry! Forgot to mention. I'm using Windows 10.

**Comment by namdre** [comment]
Might this be because your Windows display settings are set to a scaling  larger than 100% ?

**Comment by lindaludian** [comment]
Thank you! I played around with the windows setting for multiple monitors display and it worked!
