### ISSUE TITLE
improve functionality of "add reverse edge" for spreadtype=center

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#11046]
right now a parallel disconnected edge is created (to prevent overlapping edges).

An alternative implementation would be to:
1. change the spreadType to 'right'
2. reset geometry endpoints and then
3. add a normal reverse edge

For edges with spreadType=center, the edge context menu should contain the following entries:
- `Add reverse direction (spreadType=right)`
- `Add reverse direction (disconnected)`

**Comment by palvarezlopez** [comment]
@namdre I cannot reproduce it.
