### ISSUE TITLE
Future position prediction of vehicle in an intersection (junction)

### ISSUE THREAD

**Issue by miracelplus** [eclipse/sumo#11048]
Hi,

I am currently working on a project using sumo, which requires the prediction of the future position of one specific vehicle (with route) after 1 second. Currently, I am using **traci.vehicle.getBestLanes** to fetch the upcoming lanes and corresponding offset of the vehicle on a specific route. Also, I am using **convert2D** to transfer the position (lane and offset) to position (x,y). This works on the straight lane. However, when facing a junction (e.g., intersections, roundabouts), I found that the **getBestLanes** method cannot provide the edge and lane id of the junction and I cannot get the (x,y) position of the vehicle anymore. That means if the vehicle's future position is in an intersection, I cannot locate it and get the coordinate of the vehicle.

Therefore, I wonder if there is a function that can provide all future lanes (including lanes and junctions) for a specific vehicle on the route? Thanks a lot!

*If possible, upload an example that shows your problem.*

**SUMO-version:**
1.13.0

**operating system:**
Ubuntu 20.04

**Comment by namdre** [comment]
```
net = sumolib.readNet(netfile, withInternal=True)
route_with_internal = route.addInternal(net, edges)
```

You still have determine the internal lane ids based on the internal edge ids though. (see also `net.getInternalPath`)
