### ISSUE TITLE
Feature Request: "Copy to clipboard" button for code blocks 

### ISSUE THREAD

**Issue by vijay-jaisankar** [eclipse/sumo#11050]
The UX of the documentation will be improved if we add a `copy to clipboard` button (small icon) for code blocks, particularly for users implementing the tutorials.

There is another option too: Instead of adding a button, the text will be copied to the clipboard automatically if the user clicks within the code block.

For example,
![sample copy to clipboard button](https://media.discordapp.net/attachments/845744017056858172/990012809507119184/20220625_032607.jpg)

**Comment by vijay-jaisankar** [comment]
Relevant issues: https://github.com/squidfunk/mkdocs-material/issues/315

**Comment by angelobanse** [comment]
In some places we use \<code> blocks that have no code but rather text/comments (that would be odd to copy)

**Comment by behrisch** [comment]
I think it would not hurt to have the copy to clipboard button even if it is no code.

**Comment by behrisch** [comment]
Just a small remark: I would have preferred an icon here instead of the text "copy". Is there a reason for not having the icon?
