### ISSUE TITLE
StartupDelay may be overwritten by patchSpeed

### ISSUE THREAD

**Issue by Domsall** [eclipse/sumo#11067]
A startupDelay (0m/s) can get overwritten by patchSpeed, because patchSpeed uses calculations like `(vNext + vMax) / 2.0`.
In Debug Mode the assertion in `applyStartupDelay` then gets thrown after the next time step: `assert(veh->getSpeed() <= SUMO_const_haltingSpeed);`.

For the EIDM, I solved the problem with this simple if-clause:
`if (vNext > 0.) { vNext = veh->getLaneChangeModel().patchSpeed(vMin, vNext, vMax, *this); }`

Does it make more sense to do the startup calculations after patchSpeed (StartupDelay and slowToStart)?! Does this even make a difference?!

**SUMO-version:** v1_13_0+1097-7a1403be7a1

**operating system:** Windows 10

**Comment by Domsall** [comment]
Can you give an update when this is approx. going to get fixed?
I have another pull request with EIDM updates waiting :)

**Comment by namdre** [comment]
I currently don't have a scenario that triggers this. My gut feeling would be to ignore startupDelay if the car does lane changing stuff (my fix would be to move the assertion condition into the if clause).

- could you provide a small scenario to test this?
- any thoughts on my proposed solution?

**Comment by Domsall** [comment]
I will create a test and upload it here.

I think the assertion is perfectly placed, otherwise I would not have recognized the bug.
`patchspeed` overwrites the intended startupDelay, this results in the vehicle not delaying the startup.

In the example I found, two vehicles are standing next to each other at a traffic light. When the signal turns to green, one vehicle directly starts driving, while the other is being delayed.

**Comment by namdre** [comment]
I see. Then i'll move the startupDelay to after the lc-patching once I have your test

**Comment by Domsall** [comment]
I was just not sure, if this may break something else.

[StartupDelay_overwritten11067.zip](https://github.com/eclipse/sumo/files/9027615/StartupDelay_overwritten11067.zip)
