### ISSUE TITLE
breakpoints set in sumo-gui should override breakpoints from options

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#11061]
reloading should keep the hotkeys set by the user. Somewhat related to #10398

**Comment by behrisch** [comment]
but a warning should be emitted

**Comment by palvarezlopez** [comment]
We have an excel with all shortcuts

**Comment by namdre** [comment]
I mistyped the issue name. There is currently no way to set hotkeys from options nor to set them in sumo-gui. This ticket is totally  unrelated to setting hotkeys in XML input.
