### ISSUE TITLE
I'd like to know how sumo works with cars through intersections.

### ISSUE THREAD

**Issue by Lemon007-kui** [eclipse/sumo#11073]
When I use KraussOrig1 to help the vehicle through the intersection, the vehicle will slow down near the intersection and stop automatically. How is this controlled by  KraussOrig1 model?

**Comment by namdre** [comment]
- The right of way rules are encoded in the network
- The junction model determines whether a car must yield in a given situation
- the method `MSCFModel_KraussOrig1::stopSpeed` is called to determine the actual speed for stopping at the intersection.

See also https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#junction_model_parameters
