### ISSUE TITLE
Feature proposal: PCU Units as an extension to the Vehicle Class

### ISSUE THREAD

**Issue by vijay-jaisankar** [eclipse/sumo#11074]
Ref: https://www.cycling-embassy.org.uk/dictionary/passenger-car-unit

As mentioned in this article, many calculations can be done through aggregates of PCU values of all vehicles in the network/lane/area, etc. 

This proposal consists of the following steps:
- Extending the vehicle class with a new attribute 
- Setting default values for certain vehicle types 
- Adding getter and setter methods for PCU Value.
- These steps: https://sumo.dlr.de/docs/Developer/How_To/Extend_Vehicles.html

If this sounds like a good idea, can you please assign me to the same?

Thanks,
Vijay

**Comment by m-kro** [comment]
From my point of view, PCU is used mostly where your data does not contain more detailed information. It is a statistical measure people get from other studies. Let's say you only have vehicle counts per vehicle type and want to do some weighting, then it might add some value.
As SUMO already contains much more information about the vehicles, this seems unnecessary to me. If it comes to density, you could do as well width*length on a vehicle base and get a more appropriate statistics...

**Comment by namdre** [comment]
I also don't think this is needed as a core feature.
SUMO provides setting custom parameters on all vehicles or types, to include them in outputs and to retrieve/manipulate them via TraCI. (`<param key="PCU" value="2"/>`)

**Comment by vijay-jaisankar** [comment]
Okay, thanks for the info! @m-kro @namdre 

I'll check out the custom parameters' and density calculations modules, looks interesting!
