### ISSUE TITLE
cmake and make error during install sumo in centOS 8

### ISSUE THREAD

**Issue by sky4994** [eclipse/sumo#11099]
hi
I have some problems while installing sumo on centOS.
In fact, I am not familiar with Linux environment...
I have a situation where I need to install sumo in offline environment

**SUMO-version:**
my sumo : 1.13.0 
file name  : sumo-src-1.13.0.tar.gz
**operating system:**
OS : Oracle Linux 8.5

First, cmake error
It said it couldn't find the packages below even when I tried to install with cmake..
And I installed the following packages separately..! 
but i get the same error

-- Could NOT find X11 (missing: X11_X11_INCLUDE_PATH X11_X11_LIB)
-- Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
-- Could NOT find SWIG (missing: SWIG_EXECUTABLE SWIG_DIR) (Required is at least version "3.0")
-- Could NOT find GDAL (missing: GDAL_LIBRARY GDAL_INCLUDE_DIR) (found version "GDAL_VERSION-NOTFOUND")
-- Could NOT find suitable FFmpeg.
-- Could NOT find osgGA (missing: OSGGA_LIBRARY OSGGA_INCLUDE_DIR)
-- Could NOT find osgViewer (missing: OSGVIEWER_LIBRARY OSGVIEWER_INCLUDE_DIR)
-- Could NOT find osgUtil (missing: OSGUTIL_LIBRARY OSGUTIL_INCLUDE_DIR)
-- Could NOT find osgDB (missing: OSGDB_LIBRARY OSGDB_INCLUDE_DIR)
-- Could NOT find osgText (missing: OSGTEXT_LIBRARY OSGTEXT_INCLUDE_DIR)
-- Could NOT find osg (missing: OSG_LIBRARY OSG_INCLUDE_DIR)
-- Could NOT find OpenThreads (missing: OPENTHREADS_LIBRARY OPENTHREADS_INCLUDE_DIR)
-- Could NOT find OpenSceneGraph (missing: OPENSCENEGRAPH_LIBRARIES OPENSCENEGRAPH_INCLUDE_DIR) (Required is at least version "3.4.0")
-- Could NOT find GL2PS (missing: GL2PS_LIBRARY GL2PS_INCLUDE_DIR)
-- Could NOT find Eigen3 (missing: EIGEN3_INCLUDE_DIR EIGEN3_VERSION_OK) (Required is at least version "3.2")
-- Could NOT find Java (missing: Java_JAVAC_EXECUTABLE Java_JAR_EXECUTABLE Java_JAVADOC_EXECUTABLE Java_JAVAH_EXECUTABLE Development) (found version "1.8.0.332")
-- Could NOT find Git (missing: GIT_EXECUTABLE)

Second, make error
![image](https://user-images.githubusercontent.com/48505033/176840590-ad2d0e56-24d4-4daa-9dfd-9a1c33643287.png)

/home/ui/sumo-1.13.0/src/utils/iodevices/OutputDevice_File.cpp: In constructor ‘OutputDevice_File::OutputDevice_File(const string&, bool)’:
/home/ui/sumo-1.13.0/src/utils/iodevices/OutputDevice_File.cpp:64:57: error: ‘binary’ was not declared in this scope
     myFileStream = new std::ofstream(localName.c_str(), binary ? std::ios::binary : std::ios_base::out);
                                                         ^~~~~~
/home/ui/sumo-1.13.0/src/utils/iodevices/OutputDevice_File.cpp:64:57: note: suggested alternative: ‘Boundary’
     myFileStream = new std::ofstream(localName.c_str(), binary ? std::ios::binary : std::ios_base::out);
                                                         ^~~~~~
                                                         Boundary
/home/ui/sumo-1.13.0/src/utils/iodevices/OutputDevice_File.cpp:64:103: error: invalid use of incomplete type ‘std::ofstream’ {aka ‘class std::basic_ofstream<char>’}
     myFileStream = new std::ofstream(localName.c_str(), binary ? std::ios::binary : std::ios_base::out);
                                                                                                       ^
In file included from /usr/include/c++/8/ios:38,
                 from /usr/include/c++/8/ostream:38,
                 from /usr/include/c++/8/iostream:39,
                 from /home/ui/sumo-1.13.0/src/utils/iodevices/OutputDevice_File.cpp:24:
/usr/include/c++/8/iosfwd:119:11: note: declaration of ‘std::ofstream’ {aka ‘class std::basic_ofstream<char>’}
     class basic_ofstream;
           ^~~~~~~~~~~~~~
make[2]: *** [src/utils/iodevices/CMakeFiles/utils_iodevices.dir/build.make:118: src/utils/iodevices/CMakeFiles/utils_iodevices.dir/OutputDevice_File.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:3220: src/utils/iodevices/CMakeFiles/utils_iodevices.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

**Comment by behrisch** [comment]
You actually found a bug where sumo does not compile if zlib is not available. But you nevertheless probably want to install some of the needed libraries cmake mentions as missing. Just take a look here: https://sumo.dlr.de/docs/Installing/Linux_Build.html and try to find the equivalent parts on your system. If you find at least something like zlib-devel this should solve your problem.
