### ISSUE TITLE
simplify external speed control loop

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#11091]
Goal: have an external controller override/patch the vehicle speeds computed by sumo
See #7190, #8661, #10947, #11089

For details, see (https://sumo.dlr.de/docs/Developer/Implementation_Notes/Simulation_Loop.html)

Problem when using `moveTo`:
- the speed computed/used by sumo in the previous step is available at the start of the next step (`vehicle.getspeed`)
- this can be corrected with `setPreviousSpeed` and the position can be patched with `moveTo` (though with some difficulty: #11089 )
- **these patched positions/speed will never show up in sumo-gui or fcd-output** (or any other xml output except for saved state) because these outputs are always done at the end of a step (right before traci does the patching)

Problem when using `moveToXY`: 
- the patched x,y position can be computed from a patched laneID,pos and will be applied at the end of a step.
- it will show up in sumo-gui and outputs
- it cannot really be used to patch the previous speed because it modifies the speed that is used in the *current* step. Thus any reaction to things happening in the current step is impossible. Basically,  **the control loop lags the simulation**

The problem is the following fixed order of things:
1. TraCI retrieves vehicle data
2. moveTo-patching
3. Simulation moves vehicle
4. moveToXY-patching
5. outputs

What we would need instead was this:
1. Simulation moves vehicle
2. TraCI retrieves vehicle data
3. some kind of position/speed patching
4. outputs

A possible solution would be to permit some/all TraCI comands to be run in between the *Simulation-moves-vehicle* and the *output* step. To avoid duplicating all commands we might add a new function to toggle the traci server between *apply the following commands **before** the Sim-move-step* and *apply the following commands  *after** the Sim-move-step*
(i.e. `traci.simulation.applyCommandsAfterMovements(bool)**

We shouldn't need much more than a second buffer for TraCI commands. @behrisch any thoughts on this?

**Comment by namdre** [comment]
Problem: the toggle-approach doesn't work with libsumo

**Comment by behrisch** [comment]
Just one more remark here: I do not know about all the discussed use cases, but all outputs which make use of the movereminder will _not_ be affected by this change

**Comment by behrisch** [comment]
You can now execute traci commands after executeMove but before output has happened. There is no filtering yet on which commands are allowed

**Comment by namdre** [comment]
What is still needed to close this ticket? We need to put something into the changelog
