### ISSUE TITLE
Unable to import libsumo after building (Windows)

### ISSUE THREAD

**Issue by Lenakeiz** [eclipse/sumo#11103]
Hello everyone,

I am having issues importing libsumo to a python project after building the sumo in Windows.
I am trying to use CMake, but have no previous experience with CMake makefile so I hope the one should work correctly

When trying to import to a new python project I receive the following error message.

`
Traceback (most recent call last): File "C:\tsr-trafficserver\tsr-libsumo\test_libsumo_import.py", line 5, in <module> import libsumo File "C:\sumo\tools\libsumo\__init__.py", line 30, in <module> from .libsumo import vehicle, simulation, person, trafficlight # noqa File "C:\sumo\tools\libsumo\libsumo.py", line 13, in <module> from . import _libsumo ImportError: cannot import name '_libsumo' from partially initialized module 'libsumo' (most likely due to a circular import) (C:\sumo\tools\libsumo\__init__.py)
`

I have cloned sumo using `--recursive` option, `SUMOLibraries` correctly cloned and environmental variable set. `SUMO_HOME` is set to the cloned folder and `PYTHONPATH` contains the nested 'tools' folder. I have generated the solution files using CMake 3.23.2 for Visual studio 2019 with the following configuration

![image](https://user-images.githubusercontent.com/8957206/176903545-e269f2c3-0fce-4759-93b9-9a643cdf7831.png)

Can someone have any idea what I am missing?
Happy to provide any additional information.

**Comment by behrisch** [comment]
Can you show the value of PYTHONPATH and the contents of tools\libsumo? Can you import other things like sumolib or traci?

**Comment by Lenakeiz** [comment]
Hi @behrisch thank you very much for the quick reply.

I am using Python 3.10.5. 
This is the content of sumo/tools/libsumo
![image](https://user-images.githubusercontent.com/8957206/176935992-f1a46bb6-8e87-4f79-9cd6-5fd64f47f5dd.png)

And here a screenshot of the system enviromental variables
![image](https://user-images.githubusercontent.com/8957206/176936144-e10021ac-a3dc-4b13-ae71-a1b382bdc798.png)

We are using different project and I am successfully importing and using sumolib and traci.

Thank you for looking at it.

**Comment by behrisch** [comment]
OK this looks as if the build was not successful. If you run just `sumo` from the command line does it have SWIG in the features line?

**Comment by Lenakeiz** [comment]
Hi @behrisch,

What is the expected output from the build for that folder? If I remember correctly (also double checked now) a version of SWIG is included within the `SUMOLibraries`.

I cannot run `sumo` in cmd because it is not present in the `sumo/bin` folder (which is added to both the `Path` user environment variable and system variable. Do I need to install SUMO from the msi or was sumo.exe expected to be in the bin folder after the successfull build?

I have included the dir of sumo\bin if that can be helpful.
[sumobininfo.txt](https://github.com/eclipse/sumo/files/9030869/sumobininfo.txt)

Thank you!

**Comment by behrisch** [comment]
Somehow you did a debug build which will not build libsumo. Did you open the solution in Visual Studio or build from the command line? If you did in VS make sure you selected the release configuration.

**Comment by Lenakeiz** [comment]
I see. Yes I have been building the debug from visual studio. I have regenerated again the solution with Cmake (configuration from above) and I have selected Release from Visual studio and I have done Build-->Rebuild Solution
![image](https://user-images.githubusercontent.com/8957206/177053293-fcc6c7ea-33b4-45fa-9256-5ee23b2ba793.png)
![image](https://user-images.githubusercontent.com/8957206/177053327-39d11a52-eab8-41be-816a-095807174894.png)

Now it seems I have also `.pyd` file in libsumo folder 
![image](https://user-images.githubusercontent.com/8957206/177053347-5dd7fd9f-91eb-4739-b5cc-ca4c47fa7cbf.png)

However a simple python script which just try to import `libsumo` still fail (I have added libsumo folder to the `PYTHONPATH`) with a slightly different message this time (dll loading fail)

![image](https://user-images.githubusercontent.com/8957206/177053496-b7562e89-ea03-4519-babd-dac4d124e32f.png)

I have also tried to load the pyd using `ctypes` python library but also no luck.

I know that I am going with a trial and error approach here, but I really appreciate your patience.

**Comment by behrisch** [comment]
Please try to build not only libsumo but sumo as well and/or make sure that the install_dll target has been executed

**Comment by behrisch** [comment]
BTW: you know that you can also install libsumo using pip? You do not need to build it yourself

**Comment by Lenakeiz** [comment]
Hi @behrisch 

I have tried the other suggestion and run `pip install libsumo` with `--user` option. I still got an error as the `__init.py__` when importing libsumo has it has some hardcoded path depending on the path of __init.py__ file. Having `SUMO_HOME` or not as enviromental variable does not change the result of this process.
 
![image](https://user-images.githubusercontent.com/8957206/177979671-c6dd978f-4ec7-4438-8d0f-eae9666d887b.png)
 
 I will leave it here, in case someone will have faced my same problems, but I am going to give up on this for now 😞

**Comment by behrisch** [comment]
I am sorry to hear that. The issue you mentioned about the absolute paths has been fixed in the current development version and is being released next week. Maybe you try again then. The other issues are now tracked in #11115
