### ISSUE TITLE
show vClass-specific speeds in lane parameter dialog

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#11100]

**Comment by vijay-jaisankar** [comment]
Can I please work on this? 

To my understanding, we should add new `mkItem` calls in `GUIParameterTableWindow*
GUILane::getParameterWindow()` of the `src/guisim/GUILane.cpp`. Is this correct?

**Comment by namdre** [comment]
Yes and yes. The new items should only be shown if the lane has vClass-specific speeds. The attribute name should be something like:
```
maxspeed [m/s]         |  27.78
    maxspeed (truck)   |  16.67
```

with a slight indent to make it from a group with the default `maxspeed [m/s]` item

**Comment by vijay-jaisankar** [comment]
Hello, while working on this, I faced an issue.
This is the code so far:
```cpp
 // vClass specific speed
    GUINet* net = MSNet::getInstance();
    if(net->getRestrictions(myEdge->getEdgeType()) != nullptr){
        for (const auto& item : net->getRestrictions(myEdge->getEdgeType())) {
            const SUMOVehicleClass svc = item.first;
            const double speed = item.second;
            // Todo: Convert svc into a string
    }
```

Can you please let me know if 
- I'm on the right track
- If yes, how do you convert the `svc` object into a string for the `mkItem` call? I tried `c_str()` but it didn't work.
- If not, which other function call I should focus on instead.

Thanks,
Vijay

**Comment by behrisch** [comment]
You can simply use `toString(svc)` to convert it into a string

**Comment by vijay-jaisankar** [comment]
Thanks a lot, https://github.com/eclipse/sumo/pull/11243 contains the changes mentioned, please check.

**Comment by namdre** [comment]
Thanks!
