### ISSUE TITLE
lcStrategic Attribute in lane change model

### ISSUE THREAD

**Issue by hesuieins** [eclipse/sumo#11109]
Hi all,

I tried to set the `lcStrategic`'s value to -1 to disable the strategic lane change.
![image](https://user-images.githubusercontent.com/56532686/177025709-fc717582-fa6f-4196-b3bf-3b2bf22b43bf.png)

However, after simulation, I found that there were still many strategic lane change maneuvers. 
![image](https://user-images.githubusercontent.com/56532686/177025798-19151e0d-8fe5-483c-95b1-7e457d74ffac.png)

I'm wondering if there is any other settings that I need to adjust or I misunderstand the description for `lcStrategic` in [link](https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html).

Thanks!

**Comment by namdre** [comment]
Possibly you are using an older SUMO version where the setting of `-1` wasn't yet implemented. If you are using 1.13.0 this could be a bug. Can you attach a small example scenario for replicating this issue?

**Comment by hesuieins** [comment]
Hi, I'm running 1.13.0 on Windows OS. I also tried same setting files on Ubuntu 18.04. The results are same. I attached the `.sumocfg`, `passenger.trips.xml`, `net.xml` and output. Can you have a try of my settings? Thanks!

Btw, an additional question, if all things go well, after I disable the strategic lane change, what will happen for the vehicles that can not find routes to their destinations?
Thanks!
[sumo_setting.zip](https://github.com/eclipse/sumo/files/9035038/sumo_setting.zip)

**Comment by namdre** [comment]
Thanks for the example. There was some left-over code for non-urgent strategic changing that didn't check for the "-1" yet.

The expected behavior is for cars to "teleport" onto the next edge after 300s of being stuck on the wrong lane (time threshold configurable via option **--time-to-teleport**).
