### ISSUE TITLE
simplify modeling of bicycle speed distributions

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#11102]
currently, most roads have no bicycle-specific speed limits (with the exception of bicycle specific roads, #10976)  and bikes are limited by their default maxSpeed of 20km/h.

In order to make use of speedDeviations, we could use the following two strategies:

a) set [bicycle-specific max speed](https://sumo.dlr.de/docs/Networks/PlainXML.html#vehicle-class_specific_speed_limits) for all roads and also increase the default maxSpeed for vTypes with vClass bicycle.
b) use speed deviation to sample a custom maximum speed for each bicycle (`customMaxSpeed = vTypeMaxSpeed * speedFactor`). This approach is currently used to achieve pedestrian speed distributions.
   - in contrast to pedestrians, we might still want to keep the normal speedFactor around because bicycles could in principle also be restricted by a speed limit

I leaning towards b). Any thoughts @behrisch ?

**Comment by behrisch** [comment]
I am not a big fan of either approach. We could also
c) always apply speed factor to the minimum of vehicle max speed and lane max speed
d) use the opportunity to work on https://github.com/eclipse/sumo/issues/8492

**Comment by behrisch** [comment]
OK, so implementing something like #3920? Or only the desired speed without the acceleration profile?

**Comment by namdre** [comment]
Only desiredMaxSpeed as a new attribute. Lets take it slow.
