### ISSUE TITLE
 traci.vehicletype.setVehicleClass

### ISSUE THREAD

**Issue by GNAWOAIM** [eclipse/sumo#11117]
Hi there,

i met a problem while using traci with the code below:

traci.lane.setDisallowed("e1_1", ["custom1"]) 
...
            if traci.vehicle.getDistance(vehs[id])  > 1000: 
                traci.vehicletype.setVehicleClass('veh', 'custom2') 

the lane "e1_1" is disallowed for the type of vehicle ["custom1"], 
after a certain driving distance e.g.1000m, by changing the vehicle type to 'custom2', i would like to see this vehicle change to the lane "e1_1" to overtake the front car, but it doesn't change its driving lane and still follows behind the slow car. 

Really appreciate if i could get a hint,
Greets,
Mia

**Comment by namdre** [comment]
use sumo-gui to check whether the vehicle has vClass 'custom2' (right-click vehicle -> *Show type parameter*) in that situation.

**Comment by GNAWOAIM** [comment]
> use sumo-gui to check whether the vehicle has vClass 'custom2' (right-click vehicle -> _Show type parameter_) in that situation.

Thank you for the reply.
I've checked in sumo-gui, the vClass changed to 'custom2', also i've checked with traci.vehicletype.getVehicleClass("veh"), also returns vClass has changed to 'custom2', but it just doesn't behave like it.

**Comment by namdre** [comment]
Either upgrade to the latest development version or, as a workaround call `traci.vehicle.updateBestLanes()` after changing the type.

**Comment by GNAWOAIM** [comment]
> Either upgrade to the latest development version or, as a workaround call `traci.vehicle.updateBestLanes()` after changing the type.

Problem solved with traci.vehicle.updateBestLanes().
Thanks a lot!
