### ISSUE TITLE
libsumo build issues

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#11115]
- [x] not only the static lib but at least the python module (Java probably as well) depends on install_dll
- [x] check if we can ensure that MSVC selects "Release" as the default config because "Debug" does not build libsumo properly

**Comment by kschrab** [comment]
Not sure if this belongs here: if I build SUMO on a headless linux server (gentoo) with FOX_CONFIG disabled (`cmake -D CHECK_OPTIONAL_LIBS=OFF -D FOX_CONFIG= ../..`), I get the following error when loading libsumo in python or java:

```
ImportError: /#######/sumo-1.14.0/tools/libsumo/_libsumo.so: undefined symbol: _ZN7libsumo3GUI9DOMAIN_IDE
```

with 1.13.0 I get a similar error:

```
ImportError: /#######/sumo-1.13.0/tools/libsumo/_libsumo.so: undefined symbol: _ZN7libsumo3GUI11getBoundaryERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```

With 1.12.0 `libsumo.so` can be successfully loaded. Loading `libtraci` instead shows no problems in all versions.

**Comment by namdre** [comment]
@kschrab: I tried to fix this with liberal use of fox-related ifdefs (as we do in other parts of the code) but to no avail because the value of `HAVE_FOX` is not set for some reason when compiling `libsumo/GUI.h`.
I'm leaving this to Michael for when he comes back from vacation.
