### ISSUE TITLE
buttons do not fit into the default tls frame width (linux)

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#11148]
The two key differences to version 1.13.0:

- the two-column button layout enforces equal width for both columns in the dev version but created a narrow left column and a wider right column in 1.13.0
- 1.13.0 had less horizontal margin around the button text (must likely this is a consequence of the fox-toolkit layout manager judging the available space differently).

Still looks nice on windows, so only low priority

**Comment by palvarezlopez** [comment]
Fixed in #11241

**Comment by namdre** [comment]
![Bildschirmfoto von 2022-08-10 20-51-39](https://user-images.githubusercontent.com/6240630/183993879-99478b7b-afe1-4c1d-a169-fa5578183b4a.png)
default frame width

**Comment by palvarezlopez** [comment]
The current solution is not the definitive. After the release of the new version of FOX Toolkit, I'm going to try to remove the vertical scroll bar.
