### ISSUE TITLE
About --tls.discard-loaded / --tls.discard-simple

### ISSUE THREAD

**Issue by JamesPsh** [eclipse/sumo#11145]
I would like to get rid of all signal intersections that have been set up on the road network.

I found the two options below, could I ask which one is right for me?
I'm not sure about the difference between the two options.

--tls.discard-loaded
--tls.discard-simple

(https://sumo.dlr.de/docs/netconvert.html#tls_building)

**Comment by namdre** [comment]
- **discard-loaded** discards all traffic lights
- **discard-simple** discards only those traffic lights which are not at a "real" road intersection
