### ISSUE TITLE
regarding increasing the "--step-length"

### ISSUE THREAD

**Issue by JamesPsh** [eclipse/sumo#11161]
I try to use "--step--length" greater than 1 to shorten the time the simulation runs.

I'm going to use "--step--length" as 3 or 4.

I want the simulation result when "--step--length" is set to 4 to be similar to the result when "--step--length" is set to 1.
Could I ask if setting tau to 4 in vtype is sufficient? And I'd like to know if there are any other settings that I need to configure.

Thank you~

**Comment by namdre** [comment]
Most of the models have never been tested with a step-length above 1. You are likely to see interesting artifacts with this setting.
Also, `tau=4` has a huge impact on maximum traffic flow an will basically be unrealistic.

Consider using meso to increase your running speed: https://sumo.dlr.de/docs/Simulation/Meso.html

**Comment by JamesPsh** [comment]
Thank you very much for your reply.
I will check and apply what you said to me.
