### ISSUE TITLE
Specific auto-generated 3D signals for pedestrians and bikers

### ISSUE THREAD

**Issue by m-kro** [eclipse/sumo#11162]
Complete the auto-generated 3D signals from #10913 with custom design for ped / bike signals. Related to #11143 .

- [x] smaller signals for ped / bike
- [x] check position (lane center; bike only: in front of, otherwise behind the intersection)
- [x] check pole position of vehicle signal when the outer lane is for pedestrians

**Comment by namdre** [comment]
The models look nice!
Running tests/sumo/net3.net.xml shows some weird offsets though:
![Screenshot from 2022-08-16 22-04-15](https://user-images.githubusercontent.com/6240630/184976071-fdd0d27e-7fa2-4f9c-a1cc-feac91a46204.png)
