### ISSUE TITLE
Infinite loop removing edge with person plan

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#11176]
found during #11044

**Comment by namdre** [comment]
ouch. Still working in 1.13.0?

**Comment by namdre** [comment]
The error occurs if the person has more than 1 item in their plan, right?

**Comment by palvarezlopez** [comment]
Yes. I forget to check this case.

**Comment by namdre** [comment]
Please do a test with plan elements from multiple persons on the removed edge
