### ISSUE TITLE
show complete textfield content on hover

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#11194]
this is a general GUI feature but probably most useful in netedit. If a text field is too small to show the whole content it would be convenient to hover over the field and get the content as tooltip

**Comment by behrisch** [comment]
If you have a textfield which does not show the complete content like here: 
![grafik](https://user-images.githubusercontent.com/454288/179803829-2a51c64c-f44c-4216-a6a4-19e00c73b142.png)
moving the mouse pointer over it should reveal the whole content as a tool tip like here: 

![Bildschirmfoto_2022-07-19_18-53-07](https://user-images.githubusercontent.com/454288/179807049-89229f10-ce8e-4558-8d30-1311959b4587.png)

**Comment by palvarezlopez** [comment]
Finished.

**Comment by palvarezlopez** [comment]
After updating width, check if tooltip is needed
