### ISSUE TITLE
Idling and coasting emissions

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#11198]
why has a standing vehicle emissions and a coasting one has not? we need to discuss this with the PHEMlight people

**Comment by behrisch** [comment]
The answer is surprisingly simple. A vehicle needs to be able to switch off the engine at coasting. Otherwise the engine and the wheels would work against each other. That's why even older vehicles do switch off the engine and hence do not burn fuel in this case.

**Comment by namdre** [comment]
There is such thing as "motorbremsung" where you slow the car by having the wheels work against the engine and so far all cars I drove had this.  How does this square with "not letting the engine and the wheels work against each other"?

**Comment by behrisch** [comment]
If I understand it correctly a "Motorbremsung" means exactly that. The wheels are "moving" the engine so the engine does not burn any fuel otherwise it would not brake.
