### ISSUE TITLE
Result when running simulation with traci.simulation.loadState(file_name)

### ISSUE THREAD

**Issue by JamesPsh** [eclipse/sumo#11202]
Whenever I run a simulation using "traci.simulation.loadState(file_name)", the simulation results are different.

sumo_cmd = [checkBinary('sumo-gui')]
sumo_cmd += ['-n', 'sumo.net.xml']
sumo_cmd += ['-r', 'sumo.rou.xml']
sumo_cmd += ['--seed', '111']

traci.start(sumo_cmd)
traci.simulation.saveState('state_0')

when I run the simulation again, I load the state as shown below without terminating the simulation by using traci.close().

traci.simulation.loadState('state_0')

I've tried using the "--seed" option in sumo, but I get different results.
Could I ask if there is a way to get the same results?

**Comment by namdre** [comment]
add option **--save-state.rng** to also reset the state of the random number generator in loadState.
