### ISSUE TITLE
Environment Variable declaration not recognized

### ISSUE THREAD

**Issue by Anishkulkarni9001** [eclipse/sumo#11201]
Hi, I'm new to SUMO. I'm having an installation issue where I have exported the environment variable, but I still cannot run the files. When I run 'echo $SUMO_HOME', I get the expected path, but each time I try to run OSM, it says "please declare environment variable ...". How do I fix this?

**SUMO-version:** Latest

**operating system:** macOS Monterey

**Comment by namdre** [comment]
- what is the result of `echo $SUMO_HOME`
- are you running the osmWebWizard.py from the same shell where you also ran `echo` ?

**Comment by Anishkulkarni9001** [comment]
echo $SUMO_HOME gives the expected output (the path that was listed after I installed SUMO in the brew output). I tried running osmWebWizard on the shell with echo, a new instance of shell (after re-exporting the variable directly) and I tried the application as well. All methods failed and I don't understand why.

**Comment by namdre** [comment]
Here is a wild guess: try removing the lines from tools/ptlines2flows.py as indicated in this commit: 92d38de7be1fdd4fa0439bfb73d5d96616410535

**Comment by Anishkulkarni9001** [comment]
Ok, that seems to have worked. Thank you so much! I'll keep trying to figure out the rest of this.
