### ISSUE TITLE
Query about the vehicle number and speed for using osmwebwizard

### ISSUE THREAD

**Issue by conjurer-Fan-Wu** [eclipse/sumo#11218]
Hi, everyone,
When I use osmwebwizard and select the area in one city, I can set the parameters through-traffic-factor and count, and then I could see the statistical data with commands. I use SUMO-1.14.0, based on Ubuntu20.04. I want to make clear some questions. 

1. Is the number of involved vehicles in osm.passenger.trips.xml  generated according to the software? Can I set the vehicle number like using netgenerate -p command? I see that many researchers use 200, 400, or more vehicles to make figures in their papers, but I get the numbers like 187, 176, 83, and so forth, not just serveral hundreds.

2. However I change  the parameters through-traffic-factor and count, the average speed varies very small. For me, each time the number is between 15 and 21. Is that element determined by crowdness and speed limitation of the street? If I want to test the speed of 30m/s, should I use highway map on between cities?

Thanks a lot.

**Comment by m-kro** [comment]
The OsmWebWizard offers an easy way to obtain a runnable SUMO simulation based on map data. It only provides a subset of the options available within the SUMO suite to keep its clean interface.

1. The traffic demand in osmWebWizard is given in relation to the network size as you noticed. It calls the [randomTrips](https://sumo.dlr.de/docs/Tools/Trip.html#randomtripspy) script internally to create the traffic demand. You can run randomTrips again on the network created by osmWebWizard with the parameter _--insertion-rate <value>_ to control the absolute number of vehicles within a certain time interval.
2. Speed is limited based on the road type provided by OpenStreetMap. You won't get avg speeds of 30m/s in a city environment unless you edit the network yourself.

**Comment by conjurer-Fan-Wu** [comment]
Thanks a lot.&nbsp;
I have another question:
For instance, randomTrips -p 1 -e 300 means: in simulation time 300 seconds, one vehicle will occur in every second. When I use randomTrip --insertion-rate 50, I found that there are 299 vehicles when I use the command
sumo -c osm.sumocfg --fcd-output trace.xml
I do not understand where this number comes from. I see that the value after --insertion-rate denotes for vehicles arrives for one hour.&nbsp; &nbsp;Why are 299 vehicles in the statistical list? I am confused.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "eclipse/sumo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月18日(星期一) 下午5:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [eclipse/sumo] Query about the vehicle number and speed for using osmwebwizard (Issue #11218)





 
The OsmWebWizard offers an easy way to obtain a runnable SUMO simulation based on map data. It only provides a subset of the options available within the SUMO suite to keep its clean interface.
  
The traffic demand in osmWebWizard is given in relation to the network size as you noticed. It calls the randomTrips script internally to create the traffic demand. You can run randomTrips again on the network created by osmWebWizard with the parameter --insertion-rate  to control the absolute number of vehicles within a certain time interval.
 
Speed is limited based on the road type provided by OpenStreetMap. You won't get avg speeds of 30m/s in a city environment unless you edit the network yourself.

**Comment by m-kro** [comment]
I just tried it myself and indeed, a few vehicles are missing each time. Thank you for pointing us to the problem. The option --insertion-rate is rather new (see #11053 ) and maybe there is still something to adjust. 
@bcoueraud87 Maybe have a look?

**Comment by bcoueraud87** [comment]
Although I am not entirely sure, I think this is not related to the new `--insertion-rate` option but rather to the capacities of the different roads that compose the user's network, as explained in the _Note_ of the _Traffic Volume / Arrival rate_ section of the randomTrips [documentation](https://sumo.dlr.de/docs/Tools/Trip.html).

**Comment by behrisch** [comment]
I think it is another instance of #8843
