### ISSUE TITLE
SUMO Gui not opening

### ISSUE THREAD

**Issue by erev-84** [eclipse/sumo#11217]
Hello All,

After I click on 'GENERATE SCENARIO' Sumo GUI is not automatically opening and scenario is not being created. Can anyone please tell me what the issue could be with?

Please suggest me any solution to solve this problem if you have encountered this problem before.

Thanks in advanced!

![148F2164-F9F5-4BEE-B8DD-B624F582A871](https://user-images.githubusercontent.com/82845085/179405607-634702ac-71e3-4506-8cb1-36c14b202f61.jpeg)

![F5AD1B8B-88AF-4B83-BB1C-EEB647EF9035](https://user-images.githubusercontent.com/82845085/179405611-7e23ad39-6741-4d9e-8dcd-1dcfb3a0c3b6.jpeg)

![A44C9E75-F835-405A-9CDD-C27DF1D42193](https://user-images.githubusercontent.com/82845085/179405726-602f9873-94e7-45d3-95c8-263340fa7788.jpeg)

![3BCFDB0F-0EF4-487D-B792-1604BCF626E2](https://user-images.githubusercontent.com/82845085/179405741-7971268b-cce5-4466-99d8-bf2a10724853.jpeg)

![F45E970B-F03F-4EDE-841B-AC35EC6778BD](https://user-images.githubusercontent.com/82845085/179405749-ac369f70-18d5-4420-8490-7c6e91443f53.jpeg)

**SUMO-version: Sumo [1.14.0]**

**operating system: Windows 8.1 (X64 bit)**

**Comment by angelobanse** [comment]
SUMO 1.14.0 has a regression where Python 2.7 support was broken (see #11159). You can:
- Use python3
- Update to SUMO 1.14.1 (available starting 19.07.2022)
