### ISSUE TITLE
SUMO - Plot

### ISSUE THREAD

**Issue by erev-84** [eclipse/sumo#11228]
Hello,

I created emmision file by using “--emission-output” but how can I create plots from the generated xml file as seen in the photos below

Is there a tool available to plot the CO2, Noise, etc.. emission outputs ?

![FC0D8011-6C77-49EA-9601-716ABBE904E1](https://user-images.githubusercontent.com/82845085/179832015-cec0e7ac-7c59-42ef-8807-6868ebde3b7b.jpeg)

Thanks in advance

**Comment by m-kro** [comment]
The figures you posted look like they originate from Microsoft Excel, thus have been postprocessed there.
We have some tools to help processing SUMO XML output:

- [plotXMLAttributes.py](https://sumo.dlr.de/docs/Tools/Visualization.html#plotxmlattributespy) will create a 2D plot of two attributes, likely the time and some emission over all or a filtered subset of vehicles
- [xml2csv.py](https://sumo.dlr.de/docs/Tools/Xml.html#xml2csvpy) flattens the XML output to CSV format for further processing in a spreadsheet program
