### ISSUE TITLE
I wonder how the Sumo following model controls the vehicle through the intersection?

### ISSUE THREAD

**Issue by Lemon007-kui** [eclipse/sumo#11222]
I built a simple no-signal intersection, using the default car following model, I found that vehicles can pass through the intersection without conflict, how is this simulation control realized? How the speed of this is set. ? What's the algorithm for avoiding collisions？

**Comment by m-kro** [comment]
SUMO uses an extensive set of rules to avoid conflicts between vehicles at intersections. The rules are not as "encapsulated" as the car following model, such that we do not have a complete description of what is happening. There are some parameters known as the "[junction model](https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#junction_model_parameters)" which influence the vehicles' behaviour at intersections. When building your network, you can set allowed speeds for turnings either individually (Netedit) or using the [junction-related options](https://sumo.dlr.de/docs/netconvert.html#junctions) in netconvert.

**Comment by angelobanse** [comment]
*The vehicle dynamics at intersection are governed by the intersection model described in [[Road Intersection Model in SUMO, Krajzewicz et al]](http://elib.dlr.de/93669/1/LNCS_SUMOIntersections.pdf)*

Take a look at the documentation -> [Intersections](https://sumo.dlr.de/docs/Simulation/Intersections.html)

**Comment by namdre** [comment]
please note that junction type  'unregulated' has a special meaning in sumo: https://sumo.dlr.de/docs/Networks/PlainXML.html#node_types

**Comment by Shawkncok** [comment]
As the article [http://elib.dlr.de/93669/1/LNCS_SUMOIntersections.pdf] say, if we use Krauss car-following model, and (1) know the lead vehicle; (2)define distance between the follower and the lead vehicle. The collision would not happen. But if I use "unregulated" node, collision still happen. I wish to know the reason why collision happens in "unregulated" node.

**Comment by Shawkncok** [comment]
As the article [http://elib.dlr.de/93669/1/LNCS_SUMOIntersections.pdf] say, if we use Krauss car-following model, and (1) know the lead vehicle; (2)define distance between the follower and the lead vehicle. The collision would not happen. But if I use "unregulated" node, collision still happen. I wish to know the reason why collision happens in "unregulated" node.
