### ISSUE TITLE
Setting traffic phases 

### ISSUE THREAD

**Issue by btopii32** [eclipse/sumo#11221]
How do I get and set traffic phases based on the number of vehicles on edges ( with the edge having most cars set to green at a particular time step)?

**Comment by m-kro** [comment]
You can use TraCI for that purpose. Have a look at our [TraCI tutorial](https://sumo.dlr.de/docs/Tutorials/TraCI4Traffic_Lights.html) which you can adapt to your needs. It uses detectors, but you can replace the call `traci.inductionloop.getLastStepVehicleNumber(<Detector ID>)` by `traci.edge.getLastStepVehicleNumber(<Edge ID>)` to refer to the number of vehicles on a specific edge.

**Comment by btopii32** [comment]
Thank you for your response sir. I actually have done that. On reading the simulation, at a specific time step, significant number of vehicles are on 2 particular edges with their traffic light state set to red and the other edges with little to no vehicles have green states. Is there a way to deal with this please?

**Comment by m-kro** [comment]
That depends probably on how your traffic light logic works. You can debug your logic in an IDE or add print statements to check that the numbers given by TraCI are correct. If you notice some suspicious value, please share a minimum working example of the problem here in this issue. If not, then there may be a problem with your logic why it does not give green to some direction.

**Comment by btopii32** [comment]
![bestinstance.png](https://user-images.githubusercontent.com/57776760/180021055-3573935b-2533-4d0f-9cfb-958b7b105be4.png)

I've actually been able to count and get the number of vehicles on each edge.
That's the code on the left and the simulation on the right.
At this particular time step, you see the vehicles are on 2 edges where the traffic light is red. I just want to set the traffic light phases to make those edges green for longer time at this time step.
Am I making sense sir?

**Comment by btopii32** [comment]
I really appreciate you sir. I'll take a look at these resources. Thank you so much!

**Comment by btopii32** [comment]
Good day, good people
I wanted to know a way I could count vehicles in a video and then feed this input into a simulation using SUMO
Is there a way to do this please?

**Comment by namdre** [comment]
> Good day, good people I wanted to know a way I could count vehicles in a video and then feed this input into a simulation using SUMO Is there a way to do this please?

see trraci function `vehicle.add`: https://sumo.dlr.de/docs/TraCI.html#state_changing

**Comment by btopii32** [comment]
Thank you for responding Sir but I have not been able to understand you
 I looked through the documentation link you sent also, could not find the vehicle.add function

**Comment by namdre** [comment]
https://sumo.dlr.de/pydoc/traci._vehicle.html#VehicleDomain-add
see also https://sumo.dlr.de/docs/TraCI/Interfacing_TraCI_from_Python.html

**Comment by btopii32** [comment]
Hello good people
What is an ".h5" file and what is it used for in SUMO?

**Comment by btopii32** [comment]
I actually have tried reading the h5 file. This is the output below. Can anyone help me on how to get more information out of it please?![r.png](https://user-images.githubusercontent.com/57776760/185808440-3d4968b8-b1d6-4b1b-886f-ccf9565fa6ea.png)

**Comment by behrisch** [comment]
Please do not ask questions in unrelated issues, rather open a new one. I do not know of any h5 files in sumo. How was it generated?

**Comment by btopii32** [comment]
I think it's a keras file Sir. For reinforment learning purposes
I don't really know how it was generated Sir

**Comment by behrisch** [comment]
Then please ask at the reinforcement learning environment you use. SUMO does not contain such a framework.
