### ISSUE TITLE
add open build service badges

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#11238]
to the daily test page at least

**Comment by behrisch** [comment]
have been added now but it should be discussed whether we move them elsewhere and maybe also add a subset of the badges to our README

**Comment by angelobanse** [comment]
I think it would be too much for the README. I have always seen the "Status of daily build and tests" page as the main dashboard, where one could expect to find all those badges and the general status (passing or failing) of everything possible. 
Prominently linking this "Status of daily build and tests" on the README could be enough.

A redesign of the upper section of that page (the one with the badges) is necessary, though, to make it easier on the eye.

**Comment by behrisch** [comment]
@angelobanse feel free :-)

**Comment by behrisch** [comment]
I just moved them to the bottom now, improvements are of course still welcome
