### ISSUE TITLE
Web-based translation using Weblate

### ISSUE THREAD

**Issue by ovari** [eclipse/sumo#11237]
Can SUMO please be translatable with a web-browser using a web-based translation service such as [Hosted Weblate](https://hosted.weblate.org/)?

Another option is to host your own instance of Weblate like:
* [LibreOffice](https://translations.documentfoundation.org/)
* [Linphone](https://weblate.linphone.org/)

What do you think?

Thank you

**Comment by behrisch** [comment]
Which language(s) would you be interested in? I used [Transifex](https://www.transifex.com/) before. Do you know it and can tell something about the differences to Weblate?

**Comment by ovari** [comment]
Thank you for your response.

> Which language(s) would you be interested in?

Hungarian (magyar).

> I used [Transifex](https://www.transifex.com/) before. Do you know it and can tell something about the differences to Weblate?

We are familiar with both Transifex and Weblate.

Please see the [Weblate](https://weblate.org/) webpage.
> Web-based continuous localization
> Copylefted libre software, used by over 2,500 libre software projects and companies in over 165 countries.

It is understood that Transifex is not libre software.

If you can integrate Weblate, please do so.

If your project is listed on [Hosted Weblate](https://hosted.weblate.org/), translators can see your project and starting contribute.

**Comment by namdre** [comment]
Is this mainly about the documentation or are you interested in translating the UI (menu entries etc.)?

If the former, can you give a rough judgement of the quality of automated translation (https://sumo-dlr-de.translate.goog/docs/?_x_tr_sl=en&_x_tr_tl=hu&_x_tr_hl=en&_x_tr_pto=wapp) ?

**Comment by ovari** [comment]
> Is this mainly about the documentation or are you interested in translating the UI (menu entries etc.)?

UI (menu entries etc.)

**Comment by namdre** [comment]
It could be useful to introduce a general string formatting macro in the spirit of `WRITE_MESSAGEF` to avoid splitting translatable sentences at their dynamic contents. (Though it may be that this doesn't even occur in the context of UI strings).

**Comment by behrisch** [comment]
Now we have macros for WRITE_MESSAGEF and WRITE_ERRORF which work similar to WRITE_WARNINGF and we even have THROWF which can be used to replace 
```
throw ProcessError("Unknown bus station " + toString(refID));
```
with
```
THROWF(ProcessError, TL("Unknown bus station %."), refID);
```
and get coherent strings.

**Comment by behrisch** [comment]
@ovari we now have this: https://hosted.weblate.org/projects/eclipse-sumo/ Should I add hungarian (`hu`)?

**Comment by ovari** [comment]
> Can we somehow add a requirement that every contributor has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)?

Have you asked Weblate?

**Comment by ovari** [comment]
> Should I add hungarian (hu)?

Yes please.

**Comment by behrisch** [comment]
We already hit the limit. There are only four languages allowed in the free version. Maybe we need to rethink whether we use weblate. We could self host it but honestly I am not sure it is worth the effort.

**Comment by ovari** [comment]
> We already hit the limit. There are only four languages allowed in the free version. Maybe we need to rethink whether we use weblate. We could self host it but honestly I am not sure it is worth the effort.

Strange, other programs have more than 4, for example:
* https://hosted.weblate.org/projects/logarithmplotter/#languages
* https://hosted.weblate.org/projects/plots/#languages

**Comment by namdre** [comment]
There is something about our project not being fully evaluated as 'libre'. It might be that more languages are unlocked after this evaluation.

**Comment by ovari** [comment]
> There is something about our project not being fully evaluated as 'libre'. It might be that more languages are unlocked after this evaluation.

Yes.

Also it might be better to not have any languages shown automatically and wait for people to request the language through Weblate.

If Spanish have no translations you could delete that language. Then you could wait for our request via Weblate to add Hungarian (hu).

What do you think?

**Comment by namdre** [comment]
we already have requests for a Spanish translation.

**Comment by behrisch** [comment]
@comradekingu Do you know whether it is possible to add the requirement that every author has signed the Eclipse Contributor agreement? There is a github action checking this but I cannot run the action on weblate, can I?

**Comment by comradekingu** [comment]
@behrisch Can you cite what is beyond https://accounts.eclipse.org/user/login?destination=user/eca ?
Often what people put in those is covered by https://hosted.weblate.org/legal/terms/

If not, it can be added in the CLA field https://docs.weblate.org/en/latest/admin/projects.html#contributor-agreement
Also, drop the CoC, it does nothing well and discourages contributions.

**Comment by behrisch** [comment]
It is basically this one: https://www.eclipse.org/legal/ECA.php. Sorry for asking but what is CoC?

**Comment by namdre** [comment]
@ovari I think all evaluations regarding "libre" status have passed. Feel free to work on the Hungarian translation!

**Comment by ovari** [comment]
Thank you @namdre for your comment. Please see comments in Weblate. Thank you

**Comment by m-kro** [comment]
@ovari : Please ignore the Weblate checks of C type format. They do not match our syntax but we haven't found a way to disable them globally. There is no need to write a comment in Weblate for each of them. Regarding the other comments, we'll have a look at it during the next days.

**Comment by comradekingu** [comment]
@m-kro 
You can set flags in https://hosted.weblate.org/settings/project/component/#translation or by using the
bulk edit plugin described in https://docs.weblate.org/no/latest/admin/addons.html#addon-weblate-flags-bulk  from https://hosted.weblate.org/addons/project/component

**Comment by m-kro** [comment]
@comradekingu Thanks for the hint. We'll configure our translation components such that only meaningful checks are executed.
