### ISSUE TITLE
Add TraCI function to change viewport angle

### ISSUE THREAD

**Issue by Ljiaooo** [eclipse/sumo#11239]
I want to change the viewport angle realtime for better visualization, but i didn't find any traci function to do this. can anyone help

**Comment by m-kro** [comment]
This is currently not possible, but we will implement it. Linked to #11125 .

**Comment by Ljiaooo** [comment]
thanks for your reply and your effort on this fantastic work

**Comment by m-kro** [comment]
Added the option to change the viewport angle through TraCI for the 2D view. The OSG view still needs some refactoring to make it work as expected.

**Comment by m-kro** [comment]
Now works fine in OSG.
