### ISSUE TITLE
Questions about traci.vehicle.getLaneID

### ISSUE THREAD

**Issue by ShenZC25** [eclipse/sumo#11234]
Add your issue description here.
When I run traci.vehicle.getLaneID (), the return value is None.
*If possible, upload an example that shows your problem.*
traci.simulationStep()
        # get the vehicle id list
        self.vehID = traci.vehicle.getIDList()
        # select the ego vehicle ID
        self.egoID = input(
            "Please choose your ego vehicle ID (pressing enter only chooses 1st as ego): "
        )
        if self.egoID == "":
            self.egoID = self.vehID[0]
        # traci.gui.trackVehicle(traci.gui.DEFAULT_VIEW, self.egoID)
        # traci.gui.setZoom(traci.gui.DEFAULT_VIEW, 5000)
        # get observations with respect to the ego-vehicle
        curr_pos = traci.vehicle.getPosition(self.egoID)
        x, y = curr_pos[0], curr_pos[1]
        lane_x, lane_y = traci.vehicle.getLanePosition(self.egoID), traci.vehicle.getLateralLanePosition(self.egoID)
        lane_id = traci.vehicle.getLaneID(self.egoID)#这个返回值是None
        if lane_id == "":
            return None
        else:
            lane_index = traci.vehicle.getLaneIndex(self.egoID)
            lane_width = traci.lane.getWidth(lane_id)
**SUMO-version:**
1.13.0
**operating system:**
Windows 10

**Comment by m-kro** [comment]
An empty string is returned if the vehicle is not on the road. Is this the case in your simulation?

**Comment by ShenZC25** [comment]
> An empty string is returned if the vehicle is not on the road. Is this the case in your simulation?

Yeah，I set the vehicle to randomly appear on a lane line in rou.xml file, 
---------------------------------------------------------------------------------------------------
<vehicle id="genveh_1" type="typegen_1" route="route_0" departSpeed="28.650000" depart="0" departPos="random" departLane="random" color="1,0,0"/>
---------------------------------------------------------------------------------------------------
but when I gave an 'ego ID', it couldn't capture ego's positon by 'curr_pos = traci.vehicle.getPosition(self.egoID)' and so there's no 'LaneID' by 'lane_id = traci.vehicle.getLaneID(self.egoID)'
I have consulted the relevant documents, and it is described as follows
![image](https://user-images.githubusercontent.com/89288084/180109662-3dac4a9b-bbb8-4dbc-b2b9-0b1dd4a895d7.png)
![image](https://user-images.githubusercontent.com/89288084/180109558-4f756889-b281-4648-84d4-e36b7c84c10d.png)

**Comment by m-kro** [comment]
The invalid vehicle position makes me think that the vehicle does not exist in this time step. Please test your code without interactive user input, e.g. `self.egoID=traci.vehicle.getIDList()[0]`.

**Comment by ShenZC25** [comment]
> 无效的车辆位置使我认为车辆在此时间步长中不存在。请在没有交互式用户输入的情况下测试您的代码，例如.`self.egoID=traci.vehicle.getIDList()[0]`

Thank you for your patient answer. I'm building a reinforcement learning environment with Traci to do the joint simulation of python and SUMO.

1. I found that my problem may be due to my setting to randomly send out a traffic flow in the road network, but when I randomly selected the ID of a car on the interactive interface, the car was not loaded at 0 in the ’reset ( )‘ stage (because it seems that not all cars can be loaded at the same time). Do you have any common solutions?

2. In addition, I want to ask a new little question. In order to avoid a lot of issues, I asked it directly in the thread here. The angle obtained by' traci.vehicle.getAngle ()' is the angle of the vehicle relative to the centerline of the lane (maybe called local coordinates? ) or the angle of the vehicle relative to the whole map (perhaps called global coordinates? ）. The default coordinates and speeds (such as vx and vy) in the joint simulation are relative to the car itself (maybe called local coordinates? )?

Thanks very much.

**Comment by m-kro** [comment]
Concerning your follow-up questions:

1. There are some handles how to make space for more vehicles at the departure point. Have a look at the [flow options](https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#available_vehicle_attributes). If you have multiple lanes, you can distribute the flow either explicitly by splitting it into separate flows per lane (departLane=<laneIndex>) or trying out the other options (e.g. "best"). Then, the car-following settings and the departure speed influence the loading of vehicles. See also [FAQ notes](https://sumo.dlr.de/docs/FAQ.html#how_do_i_get_high_flowsvehicle_densities).
2. The angle is denoted in a "world"/global coordinate system with 0° at north/top screen and clockwise increasing value. Speeds are related to the driving direction / lane center.
