### ISSUE TITLE
netconvert: the custom shape of lane is modified

### ISSUE THREAD

**Issue by Weis-98** [eclipse/sumo#11231]
hello, 
I need to create a net using netconvert, given the node.xml, edge.xml and connection.xml. I give it the shape of lane (edge shape is not given), node and connection, but netconvert modifys my shape of lane. 
The gap between the  end of lane: "48-4-0_0" and the biginning of connection: from48-4-0_0to4-40-0_0 is terrible. In my custom shape, they are very closed. (lane end:-2171.81,-2066.85, connection beginning: 2171.778,-2066.812)
I want to know how to aviod this modification?

the warning may be useful.
Warning: Custom shape has distance 4.21 to incoming lane for connection 48-4-0_0->4-40-0_0.

terminal:
netconvert -n node.xml -e edge.xml -x connection.xml -o sumo.net.xml --no-warnings --ignore-errors.edge-type --default.spreadtype=center --no-turnarounds --offset.disable-normalization

**SUMO-version:1.14.1**

**operating system:**
ubuntu20.04

**test_file**
[test.zip](https://github.com/eclipse/sumo/files/9147969/test.zip)

**Comment by Weis-98** [comment]
thank you, I do provide the shape for junctoin "4", except changing the shape of junction is there another method to deal with this problem? I find a handle configuration "--geometry.avoid-overlap [<BOOL>]" and set it "false" but it doesn't work. 
Is changing the shape of junction the only way? 

thank for your patience.

**Comment by namdre** [comment]
netconvert will always cut the lane shape at the junction border so you have to modify the junction shape to avoid this. 
Note, that the junction shape is also influenced by the edge shape so it might already be enough to set the edge shape attribute equal to that of on of your lanes to achieve the needed junction shape.
