### ISSUE TITLE
Use Netedit to edit the coordinate value in the lower right corner of the network file, and the value is not displayed.

### ISSUE THREAD

**Issue by radiateboy** [eclipse/sumo#11230]
Use Netedit to edit the coordinate value in the lower right corner of the network file, and the value is not displayed.

_coordinate show N/A_

![1658287367(1)](https://user-images.githubusercontent.com/9248754/179889582-50be3270-f22b-4a00-b02a-6a480753d292.png)

**SUMO- Version v1_14_0+0160-503dac77597:**

**ubuntu 22.0**

**Comment by palvarezlopez** [comment]
@radiateboy thanks!

**Comment by namdre** [comment]
was broken in 1.14.0

**Comment by prashanth712** [comment]
Still the issue exists in version 14.1. Could you please have a look and fix the bug
![image](https://user-images.githubusercontent.com/101544573/183632163-fbfeda7f-6946-4f36-84af-571a2446e53a.png)

**Comment by namdre** [comment]
version v1_14_1+0109-916a72fc82b is from 11 days ago. You need the latest nightly build.

**Comment by palvarezlopez** [comment]
@prashanth712 execute the python script <sumo-folder>\tools\build\updateDailyVersion.py

**Comment by namdre** [comment]
Our automated nightly build has not run successfully since v1_14_1+0109-916a72fc82b so you really do need to build sumo yourself at the moment.
