### ISSUE TITLE
Meaning of "From 30.000 feet"

### ISSUE THREAD

**Issue by osakanatengoku-AS193** [eclipse/sumo#11233]
I am embarrassed to ask a very small question.
What is the meaning of "From 30.000 feet"?
Does it mean that the traffic flow can be observed microscopically?

**Comment by angelobanse** [comment]
> Does it mean that the traffic flow can be observed microscopically?

not in that context

**Comment by namdre** [comment]
However, sumo is definitely a microscopic simulation and you can observe your scenarios from a virtual viewpoint above your city at any chosen "height".
