### ISSUE TITLE
Satellite Background Error

### ISSUE THREAD

**Issue by erev-84** [eclipse/sumo#11247]
Hello,

When I select satellite background from osmwebwizard to add to the simulation and then press generate scenario, I am getting the error seen in the screenshot below, why I am getting this error? and how can i fix it?

![F0AE070D-539F-41A2-9F52-A242FD26C55C](https://user-images.githubusercontent.com/82845085/180645701-fb6a3ee3-bdfd-4347-8477-d98da4308635.jpeg)

![47225D95-AA8C-468B-B5A6-14594AE87CEF](https://user-images.githubusercontent.com/82845085/180645540-c328b007-5775-43d0-bd31-5df8378685aa.jpeg)

Thanks in advance

**Comment by m-kro** [comment]
OsmWebwizard calls [tileGet ](https://sumo.dlr.de/docs/Tools/Misc.html#tilegetpy)script for this task. You can try to call it independently from OsmWebWizard and see what result it gives you. I just tested the satellite background image feature and it works for me...

**Comment by erev-84** [comment]
Hello,

First of all thank you very much for the reply 

Which of the following file should I use instead of test.net.xml?

![12425C64-543B-4092-91E7-6D0584CF55EF](https://user-images.githubusercontent.com/82845085/180747796-9dc0f17d-aa43-4067-a6ff-c3dc9cd78398.jpeg)

**Comment by angelobanse** [comment]
> Hello,
> 
> First of all thank you very much for the reply
> 
> Which of the following file should I use instead of test.net.xml?
> 
> ![12425C64-543B-4092-91E7-6D0584CF55EF](https://user-images.githubusercontent.com/82845085/180747796-9dc0f17d-aa43-4067-a6ff-c3dc9cd78398.jpeg)

`osm.net.xml`

**Comment by erev-84** [comment]
Although I have pyproj installed, I am getting the error message seen in the screenshot below.

![1D17E727-040F-496A-BE8D-22AE5B51A057](https://user-images.githubusercontent.com/82845085/180809998-6cfd66e2-f50d-4550-aeab-c49a526ddc4b.jpeg)

**Comment by erev-84** [comment]
Hello,

First of all, thank you very much 

I added the Satellite Background to the simulation with the tileGet script, but as can be seen in the screenshot below, the resolution and the quality of the background are very bad. What is the reason for this and what should I do to get a better quality background?

![0A3E19B1-2C08-4F34-B660-CEB273964D1E](https://user-images.githubusercontent.com/82845085/180869435-37c3253a-dd0e-497d-beb3-d55fc01f627a.jpeg)

Another problem is, as can be seen in the screenshot below, the satallite backgorund does not appear in some areas.  What is the reason for this? and what do I need to do to fix this problem?

![A7BEA8D1-79CD-4F9E-8E74-DA242F1C6833](https://user-images.githubusercontent.com/82845085/180870009-a230c52c-e28c-4afc-80d1-5d1f2b0b7ba9.jpeg)

Thanks in advance

**Comment by behrisch** [comment]
has been answered in #11254
