### ISSUE TITLE
How to control traffic lights using Neuro-Fuzzy rules generated by ANFIS/MATLAB

### ISSUE THREAD

**Issue by erev-84** [eclipse/sumo#11244]
Hello,

I designed a controller using the ANFIS toolbox of the Matlab program for to determine the green light duration with the Neuro-Fuzzy rules according to the number of vehicles and vehicle type as input parameters.

How can I use the Neuro Fuzzy rules that I designed and which are in ".fis" format to control the traffic lights in the simulation in SUMO? (Check Traffic Light.pdf file to see the content of the “.fis” file)

I would be very grateful if you could give me detailed information on how to carry out such a project with SUMO.

[Traffic Light.pdf](https://github.com/eclipse/sumo/files/9176428/Traffic.Light.pdf)

Thanks in advance

**Comment by m-kro** [comment]
You can use the [TraCI ](https://sumo.dlr.de/docs/TraCI.html)interface to interact with SUMO. There is also an interface to MATLAB called [TraCI4MATLAB](http://www.mathworks.com/matlabcentral/fileexchange/44805-traci4matlab). There are several functions in TraCI to query information about vehicles and vehicle types. Please try out some [TraCI tutorial](https://sumo.dlr.de/docs/Tutorials/index.html#traci_tutorials) to get familiar with it.
