### ISSUE TITLE
Satellite View

### ISSUE THREAD

**Issue by erev-84** [eclipse/sumo#11245]
Hello,

How can I add a satellite view background to the simulation as shown in the picture below? Is there a way to download the map to be used in the simulation from openstreetmap with satellite view? If there is no such method, is there a tutorial you can suggest me on how to add satellite view to the map?

![3A66BC95-D3E5-4A5B-9330-25C584FB6AB2](https://user-images.githubusercontent.com/82845085/180503872-079efbaa-7d3f-4330-81d8-416c76582d91.jpeg)

Thanks in advance

**Comment by m-kro** [comment]
You can add background images and position them in line with your network, see [docs](https://sumo.dlr.de/docs/sumo-gui.html#showing_background_images). There is also a [script ](https://sumo.dlr.de/docs/Tools/Misc.html#tilegetpy) to help you with downloading satellite image.

**Comment by namdre** [comment]
The easiest way to get these images is by activating the 'satellite background' option in osmWebWizard https://sumo.dlr.de/docs/Tutorials/OSMWebWizard.html
