### ISSUE TITLE
Emission Output - Warning

### ISSUE THREAD

**Issue by erev-84** [eclipse/sumo#11252]
I am using the following command to generate the emission output of the simulation

sumo -c osm.sumocfg --emission-output my_emission_file.xml

But I am getting some warning messages as seen in the screenshot below, what is the reason for this? and will these warnings affect the data in the file to be created?

![8BDABD25-380E-4E5B-8551-550B29B1AF26](https://user-images.githubusercontent.com/82845085/180879032-dd3f61e0-6291-4cb9-8153-798ec8713fcb.jpeg)

Thanks in advance

**Comment by m-kro** [comment]
There is a page in the docs [about teleporting](https://sumo.dlr.de/docs/Simulation/Why_Vehicles_are_teleporting.html) and how you can avoid it. Essentially it will effect your data, because the vehicles will skip some part of their route and thus also probably emit less.
