### ISSUE TITLE
unknown options are no longer reported

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#11258]
`~/sumo/tools/randomTrips.py --blubber blub -n ~/sumo/tests/sumo/net.net.xml` just runs but it should complain

**Comment by behrisch** [comment]
The breaking commit was d7e05e1d722333b670c1509e3c9b7ec2e34a3784

**Comment by behrisch** [comment]
This is not completed yet. The current option parsing is still too generous because it still accepts an option like `--foo-bar baz` but at least not `--foo baz` any longer. I would propose that the call to parse_args (or the constructor of the ArgumentParser) gets another parameter which defines the program prefixes to accept. Alternatively (and less preferred) we could hardcode the common SUMO programs (like sumo, duarouter etc.) Please discuss!

**Comment by namdre** [comment]
I'd prefer an extra option for ArgumentParser.

**Comment by bcoueraud87** [comment]
@namdre I would like to solve this issue.

**Comment by namdre** [comment]
fixed in #11368

**Comment by namdre** [comment]
also creates problems with duaIterate.py (but a different error)
