### ISSUE TITLE
Given a GPS point and edge id, Could I ask if there is a way to know the pos from the edge?

### ISSUE THREAD

**Issue by JamesPsh** [eclipse/sumo#11269]
Given a GPS point and edge id,
Could I ask if there is a way to know the pos from the edge?

For example
fun(edge_id, coord) -> pos

**Comment by m-kro** [comment]
https://sumo.dlr.de/docs/TraCI/Simulation_Value_Retrieval.html#command_0x82_position_conversion

**Comment by namdre** [comment]
see also https://sumo.dlr.de/docs/Geo-Coordinates.html#performing_coordinate-transformations

**Comment by JamesPsh** [comment]
@m-kro @namdre 

Thanks to you all, I found the "urls" you gave me and various other things.
As a result, I found the function below.

============================================

from sumolib.geomhelper import polygonOffsetWithMinimumDistanceToPoint
polygonOffsetWithMinimumDistanceToPoint((x, y), edge.getShape())
