### ISSUE TITLE
Blurred Satellite Background Image

### ISSUE THREAD

**Issue by erev-84** [eclipse/sumo#11261]
Hello,

As suggested to me in Issue #11254, since ArcGIS's image quality is not good, I tried to get satellite background photos from MapQuest, but as can be seen in the photos below, MapQuest's image quality is as bad as ArcGIS.

Also,  the coordinates of the location where i want to get the satellite background images are 35.186715 32.999921

ArcGIS ==>

![54B8C105-A92C-4148-A56D-FFF21B32BA77](https://user-images.githubusercontent.com/82845085/181368175-3f69ce32-5573-4401-affd-5832d5cef752.jpeg)

MapQuest ==>

![339EC4B7-CCC0-41FA-955A-4663EF28749D](https://user-images.githubusercontent.com/82845085/181380295-34787dbe-9c43-4846-93e3-80c3feb18002.jpeg)

![39839A9A-B52A-4A46-AA6E-6703F8F9303B](https://user-images.githubusercontent.com/82845085/181368496-1acaaa48-bea4-4f75-af4e-0f55ed11832e.jpeg)

![832846F5-B0A2-4561-B9F8-DEF0DBE97E5B](https://user-images.githubusercontent.com/82845085/181368548-5fe62b2e-5cd9-42b8-abca-86f72153a853.jpeg)

Also, I want to point out that as can be seen on the screenshot below the satellite images in the same location on the MapGuest site are very high quality. What is the reason for the quality difference between the quality of satellite images on MapQuest's site and the satellite images downloaded via api?

![632CC1A9-07E7-45D0-803C-45AD06B7B0C0](https://user-images.githubusercontent.com/82845085/181385026-2001a585-c5cf-4c88-bc12-22104c351987.jpeg)

I also wanted to try Google Map, but I couldn't test the image quality of Google Maps because Google Map's API is very expensive. 

Apart from Google Maps, ArcGIS and MapQuest, are there any other geo data providers I can try?

If you could help me to get good quality satellite background images, I would be very grateful.

Thanks in advance

**Comment by behrisch** [comment]
Did you try increasing the number of tiles? Maybe -t 100?

**Comment by erev-84** [comment]
Hello @behrisch,

First of all thank you for the reply.

No but I'll try it today and let you know. By the way, what is a tile and what happens when it is increased?

**Comment by m-kro** [comment]
Tiles are parts of a bigger map or satellite image. They are used to keep the original map modular and allow selective download of a smaller area. In the context of tileGet.py, increasing the number of tiles will reduce the area each tile represents and hopefully lead to better resolution.

**Comment by erev-84** [comment]
Hello,

Thanks, by the way, how much can I increase the tile up to?, ıs there have any limit?

**Comment by m-kro** [comment]
No hard limit, at least not from our side. Every tile corresponds to a request to the map provider. Mayb your IP gets blocked for a while if you exaggerate the number of requests per unit of time.

**Comment by erev-84** [comment]
Hello,

I increased the tile as you suggested and the resolution is better now. I tried several times but maximum tile limit is 448 in my end.

For reference, if anyone has resolution problems like me, I am sharing the results below.

10 Tile ==>

![E63A056F-C489-4375-B02D-8A01242A2517](https://user-images.githubusercontent.com/82845085/181582265-33115426-c657-477b-be2c-0dbc35dad743.jpeg)

100 Tile ==>

![22584E18-13C6-4357-A79D-CA7D143D8CBF](https://user-images.githubusercontent.com/82845085/181581985-afa6a3e6-a5ed-41d5-b244-aa3db2a1181a.jpeg)

448 Tile ==>

![C6251078-D076-450C-B0D0-C42CD7E10A70](https://user-images.githubusercontent.com/82845085/181581939-ad039b98-068c-4cb5-a125-3925fffcf82c.jpeg)

**Comment by erev-84** [comment]
By the way, I set tale to 1000 but it stays at 458 every time.

 is there a method that you can suggest to make tile more than 458?

**Comment by erev-84** [comment]
By the way, I set tale to 1000 but it stays at 458 every time.

is there a method that you can suggest to me to make tile more than 458? @behrisch @m-kro

**Comment by namdre** [comment]
Most likely you have reached the resolution limit of your map server. There might other vendors that offer higher-resolution data at a price.

**Comment by erev-84** [comment]
Hello again,

The screenshot below is taken from Apple Map's app and as you can observe, resolution of the satellite image is better with Apple Maps. Is it possible to get satellite images from Apple Maps? and how can I do that?

![image](https://user-images.githubusercontent.com/82845085/185469824-896d732c-93ea-4d16-85e4-ba8ec883b5a4.png)

ArcGIS satellite image ==>

![image](https://user-images.githubusercontent.com/82845085/185471794-3cda680b-ce3b-4036-b730-a6fcebcfe4f5.png)

**Comment by behrisch** [comment]
You could try to follow this documentation: https://developer.apple.com/documentation/snapshots/create_a_maps_web_snapshot

**Comment by behrisch** [comment]
seems to be resolved
