### ISSUE TITLE
Problems encountered during the addition of a new cfmodel

### ISSUE THREAD

**Issue by 9873-kun** [eclipse/sumo#11268]
When I study this tutorial [[Developer](https://sumo.dlr.de/docs/Developer)[How_To](https://sumo.dlr.de/docs/Developer/How_To) Car-Following Model]. Why the model MSCFModel_SmartSK, the case above the tutorial, is not working in my local SUMO simulation? I have downloaded the zip file sumo-main locally.

My error message is like this: "Error: Unknown car following model 'smartSK' when parsing vType 'xiaoqiche'
Quitting (on error)."

Looking forward to your answer, sincerely.

**Comment by m-kro** [comment]
"SmartSK" is the name of the car-following model added in the tutorial. It is only available after applying all the changes described at the [tutorial page](https://sumo.dlr.de/docs/Developer/How_To/Car-Following_Model.html) and compiling SUMO yourself. If you went to the end of the tutorial, please check whether you missed something.

**Comment by 9873-kun** [comment]
So do I need to recompile SUMO with CMake to get the new car-following model running? Or can I call the new car-following model directly through the Traci interface? For example, SmartSK.

Thanks a lot!

**Comment by m-kro** [comment]
You have to recompile SUMO absolutely after applying your changes (= a new car-following model)!

**Comment by 9873-kun** [comment]
How specifically do I operate CMake? Is there a relevant operating guide?

Thanks a lot!

**Comment by 9873-kun** [comment]
How specifically do I operate CMake to recompile SUMO? Is there a relevant operating guide?

Thanks a lot!

**Comment by m-kro** [comment]
If you don't have any experience please follow the relevant [build instructions](https://sumo.dlr.de/docs/Developer/index.html#build_instructions) for your OS.
