### ISSUE TITLE
Flowrouter doesn’t work

### ISSUE THREAD

**Issue by Mtbttt** [eclipse/sumo#11275]
Hello, 
I want to use the flowrouter to estimate the flow on roads in which detector data is not available. I have created a very simple network but the flowrouter doesn’t work. Here is a sample of what happens when I run the code. 
![AAE30D06-1B0C-44F6-BA88-AE4D44DCC20C](https://user-images.githubusercontent.com/110495683/182466048-ce41cf5c-9c48-424a-9d44-226892940596.jpeg)

**Comment by m-kro** [comment]
Do you want to share your example?

**Comment by Mtbttt** [comment]
Hello,
yes this is the example I used.
python Sumo\tools/detector/flowrouter.py -n
C:\Users\MAHGAM\Desktop\MAHGAM_TEST\MAHGAM_TEST.net.xml -d
C:\Users\MAHGAM\Desktop\MAHGAM_TEST\detector_TEST.xml -f
C:\Users\MAHGAM\Desktop\MAHGAM_TEST\flow_TEST.csv -o
C:\Users\MAHGAM\Desktop\MAHGAM_TEST\routes.rou.xml -v --debug
--revalidate-detectors

**Comment by Mtbttt** [comment]
yes sure this is the example

python Sumo\tools/detector/flowrouter.py -n C:\Users\MAHGAM\Desktop\MAHGAM_TEST\MAHGAM_TEST.net.xml -d C:\Users\MAHGAM\Desktop\MAHGAM_TEST\detector_TEST.xml -f C:\Users\MAHGAM\Desktop\MAHGAM_TEST\flow_TEST.csv -o C:\Users\MAHGAM\Desktop\MAHGAM_TEST\routes_text.rou.xml -v --debug --revalidate-detectors

[flow_TEST.csv](https://github.com/eclipse/sumo/files/9274748/flow_TEST.csv)

![image](https://user-images.githubusercontent.com/110495683/183242727-ef7c8c71-117f-4fa8-9865-9648b2cd87bf.png)

![image](https://user-images.githubusercontent.com/110495683/183242760-ec7b03e4-4356-4d79-ad34-b0a7265d7706.png)
![image](https://user-images.githubusercontent.com/110495683/183242766-dabc0d68-19a7-4e63-8317-9f80caf46429.png)

[routes_text.txt](https://github.com/eclipse/sumo/files/9274864/routes_text.txt)

I used the route files that I had created while utilizing sumo random trips. (routes.rou.alt.xml) I have also utilized trips.trips.xml file and routes.rou.xml file that have been created with sumo random trips.

**Comment by m-kro** [comment]
There is no need to put screenshots of text files. Just attach the files directly - the net is still missing.

**Comment by Mtbttt** [comment]
[detector.txt](https://github.com/eclipse/sumo/files/9282802/detector.txt)
[flow_TEST.csv](https://github.com/eclipse/sumo/files/9282805/flow_TEST.csv)
[mahgam_net.txt](https://github.com/eclipse/sumo/files/9282807/mahgam_net.txt)
[routes_text.txt](https://github.com/eclipse/sumo/files/9282808/routes_text.txt)
hello, 
I just attached all files as text
thank you

**Comment by m-kro** [comment]
Sorry for the delay. I had a closer look and could identify two causes:

- there seems to be some special character in the first line of flow_TEST.csv, so that the detector column is not found
- use the option `-e <FILE>` to write the resulting flows to an output file
