### ISSUE TITLE
Time field missing in .sumocfg files

### ISSUE THREAD

**Issue by mirkofranco** [eclipse/sumo#11271]
**SUMO-version: v_1_14_1**

The time field is missing in the .sumocfg file. The command sumo -c osm.sumocfg --fcd-output trace.xml generates a trace file with a different number of timesteps with respect to the duration specified in osmWebWizard.

**Comment by m-kro** [comment]
At most OsmWebwizard wording "duration" is a bit misleading, as it refers to the time interval for which trips will be created. Traffic participants may depart at the end of the given time and arrive later. But it's not a big deal to cut the simulation period to a custom time interval  (see [docs](https://sumo.dlr.de/docs/sumo.html#time)):
`sumo -c osm.sumocfg --end <DURATION>`

**Comment by mirkofranco** [comment]
@m-kro thank you for your response. 
So, the duration in osmWebWizard is not the duration of the simulation, but it refers to the maximum time a vehicle can depart, right? Instead, the number of timesteps in the trace file is the actual simulation time, right?

**Comment by m-kro** [comment]
Yes, you are right.

**Comment by namdre** [comment]
@angelobanse Can we add tooltips to the webwizard UI that would give additional information on the semantics of the 'Duration' field?
