### ISSUE TITLE
Detector 

### ISSUE THREAD

**Issue by erev-84** [eclipse/sumo#11274]
Hello,

I am trying to design a controller for determination of green light duration. In order to determine the duration of the traffic light, I need the number of vehicles waiting at the traffic light, the average waiting time, and the vehicle type(car, truck, ambulance etc…). 

Which detector (E1, E2, E3) can I use to obtain this data? Also, is there any other way to get this data without using detector?

Thanks in advance,

**Comment by m-kro** [comment]
There are several TraCI functions you can use in this context. Examples:

- get vehicle count from `traci.edge.getLastStepVehicleNumber` or `traci.lane.getLastStepVehicleNumber` > no detector needed, but it counts all vehicles on the given edge / lane
- get vehicle count from detector: `traci.<Domain>.getLastStepVehicleNumber` where `<Domain>` in {inductionloop, lanearea, multientryexit}
- in each of the cases named above, you can also access the vehicle IDs calling `traci.<Domain>.getLastStepVehicleIDs` and query further vehicle information via `traci.vehicle` functions
- waiting time: as you want to query the vehicle IDs anyway, you can store the arrival and departure within your area and derive the average waiting time.

**Comment by erev-84** [comment]
Hello @m-kro,

what type detector should I use for such a project? E1, E2 or E3? 

Also, Could you give me Short explaination about the differences between E1, E3 and E3 detectors please?

Thanks

**Comment by m-kro** [comment]
For detectors see [docs](https://sumo.dlr.de/docs/Simulation/Output/index.html#simulated_detectors). Any of the three types may work in your case. If you have not worked with detectors and TraCI yet, maybe start with E2 = lanearea.

**Comment by erev-84** [comment]
Hello @m-kro ,

Is there any way to change the color of the E2 Detector or make it as transparent?

I tried to set roads as mark as front element, I don't know why, but I can only set one road as mark as front element. For example, I cannot set 4 different paths as "mark as front element" all at once, as seen in the screenshot below. so I think mark as front element is not the solution.

![image](https://user-images.githubusercontent.com/82845085/186158302-48d594d9-e65d-45cd-a202-e6ee4432c7e3.png)

**Comment by m-kro** [comment]
You cannot configure the drawing order freely in SUMO (e.g. wouldn't make sense to draw the road above the cars). This "mark as front element" feature in netedit shall help only when editing overlapping elements. 

Here is some [text ](https://sumo.dlr.de/docs/sumo-gui.html#changing_the_appearancevisualisation_of_the_simulation)about changing the visual aspects in the GUI. You can hide detectors by setting their size to 0: In "Additionals" tab, set "Exaggerate" value to 0. Be beware of that this concerns all additional items (bus stops etc.), not just detectors.
