### ISSUE TITLE
Simpla relies on consistent lane index across edges for lane change commands 

### ISSUE THREAD

**Issue by sushmareddy569** [eclipse/sumo#11276]
I'm using Simpla as reference to create a platoon. In my case, I have three edges, when the platoon is moving from one edge to another edge, at the junction the vehicles are shifting to other lanes in the next edge. How do i stop the vehicles from lane changing and make them travel in the same lane from first edge to the last edge?

**Comment by m-kro** [comment]
Once a platoon of multiple vehicles has formed, the followers will change lanes if the leader does. So the question is rather how to restrict vehicles to certain lanes in general:

- allow certain vehicle classes only on the wanted lanes or
- add waypoints to the route (see [docs](https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#waypoints))

**Comment by sushmareddy569** [comment]
In my case, even if the leader does not change the lane, the follower is switching into other lanes after entering into second edge through a junction. 

Here I'm uploading my file which has network files, route files, cfg files.
[Hello.zip](https://github.com/eclipse/sumo/files/9249005/Hello.zip)

Could you please go through them and suggest how to restrict the vehicles from switching lanes when they pass from one edge to other edge?

**Comment by m-kro** [comment]
Worked with SUMO v.1.9.0. Followers change lanes starting with v.1.10.0.

**Comment by m-kro** [comment]
Problem was hidden before [this commit](https://github.com/eclipse/sumo/commit/a9bceee906f9442025984695e514f99429407e43). When the edge downstream has more lanes and the leader naturally switches from laneIndex 0 to 1 by driving straight, followers may change to lane 1 on the upstream edge and break the platoon.

**Comment by namdre** [comment]
Suggestion: if there is a direct connection from the follower lane to the leader lane, then the follower should stay on their lane (the check is a bit more involved if there are intermediate edges between leader and follower)

**Comment by m-kro** [comment]
Can't reproduce the problem with the current SUMO dev version anymore, because it was solved through merge of #9252 . I'll take the suggestions to create more advanced lane change to a new ticket.
