### ISSUE TITLE
TLS Switch Output

### ISSUE THREAD

**Issue by erev-84** [eclipse/sumo#11289]
Hello,

I am trying to generate TLS Switch outputs using the command below, but the outputs are not generated. What could be the reason for this and what should I do to generate TLS Switch outputs.

Command ==>

`<timedEvent type="SaveTLSSwitchTimes" source="<TLS_ID>" dest="<OUTPUT_FILE>"/> `

![CC3C66A3-7C7B-4A48-BE62-6EB48757E743](https://user-images.githubusercontent.com/82845085/183315267-2c50928d-7a57-465d-9ee5-1bcad87e1acf.jpeg)

![252D5A1A-8810-4D3E-8EBE-DB18193BBADF](https://user-images.githubusercontent.com/82845085/183315274-2ccdc3b7-2ffb-443d-a7e3-27235c11a020.jpeg)

![AB3BB408-7A15-4127-AD08-882598EF72F8](https://user-images.githubusercontent.com/82845085/183315275-b52350d3-3ec2-4edd-8691-d47c1919d0d2.jpeg)

Thanks in advance

**Comment by m-kro** [comment]
Please move the `additional` tag out of the sumocfg file to a separate additional file which you reference in `additional-files` value.

**Comment by erev-84** [comment]
> Please move the `additional` tag out of the sumocfg file to a separate additional file which you reference in `additional-files` value.

Thanks for your suggestion, it's worked
