### ISSUE TITLE
How to log SSM device data into same file?

### ISSUE THREAD

**Issue by osakanatengoku-AS193** [eclipse/sumo#11285]
Add your issue description here.
I followed this page and added <param key="device.ssm.file" value="FILE"/> under the vType element, but the SSM device file was created per vehicle and empty.
https://sumo.dlr.de/docs/Simulation/Output/SSM_Device.html

*If possible, upload an example that shows your problem.*

**route file**

```
<vType id="Type1_AudiA3_distATB0.859_tireRadius0.3" length="4.18" width="1.911" maxSpeed="60" speedDev="0.1" guishape="passenger" vClass="passenger" probability="0.1">
<param key="device.ssm.file" value="FILE"/>
</vType>
```
**Command line**

sumo -c gojodori.sumocfg --fcd-output gojofcd2.xml --device.ssm.file gojossm.xml

**SSM file**

   <input>
        <net-file value="test.net.xml"/>
        <route-files value="vehTypes.rou.xml,randomtrips3.rou.xml"/>
    </input>

    <output>
        <fcd-output value="gojofcd2.xml"/>
    </output>

    <time>
        <begin value="0"/>
        <end value="5000"/>
        <step-length value="0.1"/>
    </time>

    <processing>
        <lateral-resolution value="0.5"/>
        <ignore-route-errors value="true"/>
        <collision.action value="warn"/>
        <collision.mingap-factor value="0"/>
        <default.carfollowmodel value="Krauss"/>
    </processing>

    <ssm_device>
        <device.ssm.probability value="1"/>
    </ssm_device>

    <random_number>
        <seed value="22222"/>
    </random_number>

    <gui_only>
        <tracker-interval value="0.1"/>
    </gui_only>

**SUMO-version:**

**operating system:**

**Comment by m-kro** [comment]
I can't reproduce this. Can you please state your SUMO version, your OS and at best add a complete working example to this issue?

**Comment by osakanatengoku-AS193** [comment]
[question.zip](https://github.com/eclipse/sumo/files/9266289/question.zip)

Strangely enough, I couldn't reproduce it either.
This time not a single ssm file was created.

maybe SUMO version is 1.10 (SumoNetVis-1.6.0.dist-info is in my computer, is this latest？)
OS is Windows 11

**Comment by m-kro** [comment]
You did not add the SSM device this time (and had an invalid sumocfg with "inline additional elements"). Then you don't assign your custom vehicle types to the trips. Please read the docs carefully and maybe study some of our SSM tests (see [repo](https://github.com/eclipse/sumo/tree/main/tests/sumo/devices/ssm), [how to download tests](https://sumo.dlr.de/docs/Tutorials/index.html#using_examples_from_the_test_suite)).
