### ISSUE TITLE
Help: HighwayDetector

### ISSUE THREAD

**Issue by Pedro-Oliver** [eclipse/sumo#11284]
Goodnight,

I am conducting a study using detectors. I made a very, very, very simple network to simulate.
I'm trying to generate a simulation with detector counts. I performed the procedures through the tutorials available at:
https://sumo.dlr.de/docs/Tutorials/HighwayDetector.html
https://sumo.dlr.de/docs/Demand/Routes_from_Observation_Points.html

In the last step where I need to call sumo it returns the following warning
![image](https://user-images.githubusercontent.com/110643550/182978412-d511f4d8-358f-453b-a5ba-ad6f3a85a011.png)

SUMO-version: Sumo 1.14.1 for windows 64-bit

operating system:

Files here:
[SUMO_DETECTORES.zip](https://github.com/eclipse/sumo/files/9264336/SUMO_DETECTORES.zip)

Could anyone help me to solve this problem?

I thank you for your help.

**Comment by m-kro** [comment]
It happens because there is no sufficient gap to turn left, see [docs](https://sumo.dlr.de/docs/Simulation/Why_Vehicles_are_teleporting.html). 
Use SUMO parameter `--time-to-teleport -1` to disable teleporting. If you do that, think about creating sufficient gaps (~ longer intervals between departures) to allow vehicles from bottom to turn left. Otherwise you'll create congestion (which may be also OK if that is what you want).

**Comment by Pedro-Oliver** [comment]
Good Morning I entered the command --time-to-teleport "-1" I now have the
warning:
[image: image.png]
Could you help me?
Thank you very much.

Att,

Pedro Oliveira

Em sex., 5 de ago. de 2022 às 03:32, Mirko Barthauer <
***@***.***> escreveu:

**Comment by namdre** [comment]
> I now have the warning: [image: image.png]

your screenshot is not visible. You could simply copy/paste the warning message as a comment.

**Comment by Pedro-Oliver** [comment]
Good Morning,

Microsoft Windows [versão 10.0.19044.1826]
(c) Microsoft Corporation. Todos os direitos reservados.

C:\Users\Pedro\Desktop\SUMO_DETECTORES>sumo --net-file
C:\Users\Pedro\Desktop\SUMO_DETECTORES\Rede.net.xml --additional-files
C:\Users\Pedro\Desktop\SUMO_DETECTORES\routes.rou.xml,C:\Users\Pedro\Desktop\SUMO_DETECTORES\vehicles.rou.xml
--time-to-teleport "-1"
Warning: Environment variable SUMO_HOME is not set, schema resolution will
use slow website lookups.
Step #4473.00 (0ms ?*RT. ?UPS, vehicles TOT 300 ACT 0 BUF 0)

Tks.

Att,

Pedro Oliveira

Em ter., 9 de ago. de 2022 às 04:45, Jakob Erdmann ***@***.***>
escreveu:

**Comment by m-kro** [comment]
[See FAQ](https://sumo.dlr.de/docs/Basics/Basic_Computer_Skills.html#sumo_home)

**Comment by Pedro-Oliver** [comment]
Good Morning,

Tks!

Microsoft Windows [versão 10.0.19044.1826]
(c) Microsoft Corporation. Todos os direitos reservados.

C:\Users\Pedro\Desktop\SUMO_DETECTORES>sumo --net-file
C:\Users\Pedro\Desktop\SUMO_DETECTORES\Rede.net.xml --additional-files
C:\Users\Pedro\Desktop\SUMO_DETECTORES\routes.rou.xml,C:\Users\Pedro\Desktop\SUMO_DETECTORES\vehicles.rou.xml
--time-to-teleport "-1"
*Step #4473.00 (0ms ?*RT. ?UPS, vehicles TOT 300 ACT 0 BUF 0)*

Att,

Pedro Oliveira

Em ter., 9 de ago. de 2022 às 10:06, Mirko Barthauer <
***@***.***> escreveu:
