### ISSUE TITLE
Help Command

### ISSUE THREAD

**Issue by Pedro-Oliver** [eclipse/sumo#11287]
Hello,

could someone help me with this problem?
![image](https://user-images.githubusercontent.com/110643550/183092830-77be65e4-11c8-4ad4-8f23-7fd1adf97fd1.png)

I thank you for your help.

**Comment by m-kro** [comment]
Probably because you don't have the SUMO bin directory in your PATH environment variable... Either use the complete path to dfrouter or edit your environment vars.
