### ISSUE TITLE
Simulation Time

### ISSUE THREAD

**Issue by erev-84** [eclipse/sumo#11291]
Hello,

In Sumocfg file, I setted Step length to 0.1 and steps to 3600 steps but simulation finished in about 32-35 seconds.

Simulation, 360 (3600*0.1=360s) seconds
shouldn't it last? What is the reason for the simulation to finish in such a short time? Also, how can I calculate how long the simulation will take? Finally, if I set the step length to 0.001, how many seconds will the simulation be?

I would be glad if anyone can explain this situation to me 

Thanks in advance

**Comment by m-kro** [comment]
Time-related parameters in sumocfg are given in seconds. What option do you mean by the following:

> steps to 3600 steps

If you set the end time explicitly `--end <TIME>`, then the simulation will run that long (except for errors).

**Comment by erev-84** [comment]
Hello @m-kro ,

I meant 3600 seconds (1 hour) as the duration

Also, I set the --end time tp 30 seconds but simulation ended in just 4 seconds. what should I do to finish the simulation in 30 seconds?

![image](https://user-images.githubusercontent.com/82845085/183527632-e54c6821-8810-4897-9977-461cbcae1f69.png)

![image](https://user-images.githubusercontent.com/82845085/183528132-a6d9f028-f5d0-426e-a943-154fd7e8c191.png)

**Comment by m-kro** [comment]
Your screenshot shows t=29, so it actually does run longer than 4s?

**Comment by erev-84** [comment]
I turned on the stopwatch as soon as I started the simulation and yes simulation ended in 4 seconds even I set it to 30 seconds

**Comment by m-kro** [comment]
Is there any relevant message in the logging box below the network? Otherwise attach the scenario files to this issue.

**Comment by namdre** [comment]
> I turned on the stopwatch as soon as I started the simulation and yes simulation ended in 4 seconds even I set it to 30 seconds

The simulation runs as fast as possibly by default and this by a high multiple of real-time speed depending on the number of simulation vehicles. As a rule of thumb, sumo manages ~50.000 vehicle-updates per second.

If you want to observe a simulation running in real-time when it's running faster than real-time, you can use option **--delay 1000** or set the *delay* value in sumo-gui (delay is given as ms per simulated second).
