### ISSUE TITLE
Average Queue Length and Average Delay Time Graph

### ISSUE THREAD

**Issue by erev-84** [eclipse/sumo#11293]
Hello,

What should I do to create “Average Queue Length/Timestep and Average Delay Time/Timestep” graphs as seen in the example below?

![0D9151DF-E15F-4942-9AC7-55B7949265EB](https://user-images.githubusercontent.com/82845085/183317239-32876a06-cc14-43bc-9c27-2e4dfc906390.jpeg)

**Comment by m-kro** [comment]
1. get the data via [lane area detectors ](https://sumo.dlr.de/docs/Simulation/Output/Lanearea_Detectors_%28E2%29.html )using a short aggregation period
2. plot the data as you like (your own script, Excel, ... or use [our visualisation script](https://sumo.dlr.de/docs/Tools/Visualization.html#plotxmlattributespy)

**Comment by namdre** [comment]
- `maxJamLengthInVehicles` is the maximum queue length during each interval (300s in your case)
- `intervalHaltingDurationSum` is the sum of all waiting times per 300s interval. 

In the quoted output data, the vehicles all passed the detector with (almost) no delay.
