### ISSUE TITLE
Vehicle Type (Gui Shape)

### ISSUE THREAD

**Issue by erev-84** [eclipse/sumo#11290]
Hello,

In Sumo Gui, I want the gui shape and colors of the Ambulances to be as in the example below

![79517EA1-CDC5-41EC-B17A-3A932955C065](https://user-images.githubusercontent.com/82845085/183315471-1cd41303-d4a5-482e-b560-894ac06330ca.jpeg)

For this, I edited the gui shape from the attribute editor, but still the ambulances do not appear in the simulation. What is the reason of this? And what should I do to make the ambulances look like the ambulances as shown above?

![98908FD3-C080-43C4-AD3F-D86045ABD42D](https://user-images.githubusercontent.com/82845085/183315631-1b9bc7f4-e3d2-49bf-9282-783de8e17542.jpeg)

![9109AFD3-B5AC-4B3D-83FC-BDC498778A51](https://user-images.githubusercontent.com/82845085/183315626-e2a2fe21-dc7a-4aef-8509-8d9758ba68b4.jpeg)

Thanks in advance

**Comment by m-kro** [comment]
Check if you have vehicles of your type `emergency_vehicle` running through your network.
