### ISSUE TITLE
default "Tooltip"-Tooltip appears from time to time

### ISSUE THREAD

**Issue by angelobanse** [eclipse/sumo#11308]
Take a look at the upper-left corner:

https://user-images.githubusercontent.com/16121932/183650913-1d4afb33-2ccf-43ac-983f-fbf69c94f299.mov

It affects both `sumo-gui` and `netedit` on macOS.

**Comment by namdre** [comment]
probably related to #11278

**Comment by angelobanse** [comment]
> probably related to #11278

possibly, although strangely #11278 only affects `sumo-gui`

**Comment by palvarezlopez** [comment]
Fixed in https://github.com/eclipse/sumo/issues/11278
