### ISSUE TITLE
Detector

### ISSUE THREAD

**Issue by erev-84** [eclipse/sumo#11303]
Hello,

I want to know the number of vehicles, the type of vehicles and the waiting time of the vehicles in the area indicated by the arrows in the picture below, which detector should I use for this scenario? and I would be very grateful if you could give me a brief information about why I should use that detector.

![Detector](https://user-images.githubusercontent.com/82845085/183524891-8d36b589-de44-4e13-be62-a407199ea0de.jpg)

**Comment by m-kro** [comment]
You already asked almost the same question in #11274 . You should extend the detector downstream to the stop line using endPos or length attribute (see [docs](https://sumo.dlr.de/docs/Simulation/Output/Lanearea_Detectors_%28E2%29.html)). Then start learning TraCI and tryout the hints from #11274 .

**Comment by namdre** [comment]
Also, if you have a related follow-up questions after an issue was closed (i.e. #11274) please continue to comment in that ticket rather than opening a new one.  
To decide on the suitable detector, please refer to the documentation of their outputs. If, after this, you still have questions w.r.t  detector choice, please try to make your question more specific. This can lead to an improved documentation.

**Comment by erev-84** [comment]
Hello,

I am trying to place E2 detector in the areas I marked with an arrow below.

![image](https://user-images.githubusercontent.com/82845085/183988460-2f00cee8-bda7-4399-a10b-50729f83a2de.png)

but the junctions seen in the screenshots below prevent me from doing this because the detectors I want to place need to go beyond these junctions.

![image](https://user-images.githubusercontent.com/82845085/183988643-7e9ec71e-748a-4d03-83fe-c676febaef8e.png)
![image](https://user-images.githubusercontent.com/82845085/183988713-3f2bf7e9-4064-4313-93a7-bcbb06da9fbe.png)
![image](https://user-images.githubusercontent.com/82845085/183988978-e7a61b31-8371-4880-8490-fd209d4d4d6d.png)

To solve this problem, I tried to delete the junctions with delete mode, but this caused the entire road to be deleted.

![image](https://user-images.githubusercontent.com/82845085/183989863-d84d3830-b941-4a00-8e6c-1ea35eae83c3.png)
![image](https://user-images.githubusercontent.com/82845085/183989893-fde6f416-a35d-48b9-bc6c-ed6d81f418ad.png)


In the screenshot below, I tried to show how I want the E2 Detectors to be with arrows.
![image](https://user-images.githubusercontent.com/82845085/183989169-ae8e801f-8830-47c3-b8ad-3b3f48d7d42d.png)

I would be very grateful if you could teach me how to remove the junctions and place the E2 detectors at the desired length.

[2022-08-10-17-31-19.zip](https://github.com/eclipse/sumo/files/9303046/2022-08-10-17-31-19.zip)

**Comment by erev-84** [comment]
Hello,

I removed all side roads but as can be seen from the screenshot below "replace by geometry point" can't selectable

![image](https://user-images.githubusercontent.com/82845085/184000063-b526919e-4335-4c9c-8bb2-7b7257a16e46.png)
![image](https://user-images.githubusercontent.com/82845085/183999793-34c05420-e049-4d69-b446-0fa293ff3212.png)

Also, I tried to use multi-lane E2 detector as you suggest and I have few questions about it, the output of all vehicles that are on the detector (blue area), will be generated as in the E2-detector, right? and what is the difference between the E2 detector and multi-lane E2 detector?

![image](https://user-images.githubusercontent.com/82845085/183998902-b5b4be1e-660d-4893-9a03-0b4bb3b6550f.png)

**Comment by erev-84** [comment]
one more thing, I can not add the E2 Multilane Detector the the places I want. What is the reason of this?

See the attached screen recording please

[Screenrecording.zip](https://github.com/eclipse/sumo/files/9303775/Screenrecording.zip)

**Comment by namdre** [comment]
1. as the screenshot indicates, the edges have incompatible attributes ('spreadType') which you could change via inspect mode
2. the difference is, that the multi-lane version spans more than 1 lane. You can select any number of consecutive lanes but have to click on them in driving order.

**Comment by erev-84** [comment]
Hello @namdre ,

Were you able to watch the screen recording inside the zip file I attached? I don't know why but I could not place Multlane detector to the places/roads as I want. Could you please watch the screen recording and suggest me what do I need to do?

**Comment by namdre** [comment]
- you cannot click on junctions, instead click on the next lane beyond the junction
- you must not skip lanes, if you want a detector across 3 lanes then click on each of them in driving order

**Comment by erev-84** [comment]
Hello @namdre ,

Actually, I tried to add the multiline E2 detector to the other roads in the same way as I did to the first path seen in the screen recording, but I could not succeed. I uploaded the files in the first post, is it possible for you to show me what do I need to do to add the E2 Multiline detectors to the places I showed in my previous messages by taking a screen recording? Also, I would be glad if you can show me how to remove the junctions I showed in my previos mesaages. I would be glad if you can help me.

Finally, If you know any tutorial about that topic can you please sent me it’s link please?

Thanks in advance

**Comment by erev-84** [comment]
Hello,

What is the reason of conflict seen below?, Also, what kind of disadvantages / problems will I encounter if I select the save invalid positions button and save?

![image](https://user-images.githubusercontent.com/82845085/185206361-5c4de4f2-4f00-41b4-a826-e175adf3acee.png)
![image](https://user-images.githubusercontent.com/82845085/185206564-1303a875-e5c6-491f-8b18-f2b4ec663ca0.png)
![image](https://user-images.githubusercontent.com/82845085/185206879-95d79113-dcbc-44de-b0a5-e050b3b6d42f.png)

[Conventional.zip](https://github.com/eclipse/sumo/files/9365055/Conventional.zip)


Thanks

**Comment by erev-84** [comment]
From the screen recording below you can see the steps I followed to create Detectors and you can also see the "conflict" error.

[bandicam 2022-08-17 21-23-23-755.zip](https://github.com/eclipse/sumo/files/9365269/bandicam.2022-08-17.21-23-23-755.zip)

**Comment by namdre** [comment]
friendlypos=true will adjust detector length to the available lane length, thus the detector might be a bit shorter in the simulation but it won't give you an error.

**Comment by erev-84** [comment]
Hello,

Is there any way to change the color of the E2 Detector or make it as transparent?

I tried to set roads as mark as front element, I don't know why, but I can only set one road as mark as front element. For example, I cannot set 4 different paths as "mark as front element" all at once, as seen in the screenshot below. so I think mark as front element is not the solution.

![image](https://user-images.githubusercontent.com/82845085/185811329-4bb3b7a3-d05e-41c7-9220-9c22d193dc13.png)
