### ISSUE TITLE
Get currently loaded SUMO sumocfg / net file

### ISSUE THREAD

**Issue by m-kro** [eclipse/sumo#11319]
While TraCI is meant to access dynamic data during the simulation, sumolib.net provides helpers to analyze the network structure. 

- When combining both in a custom script, the sumocfg file is known and can be given as input to sumolib.net.
- When a more generic TraCI module (**simpla** in my case) wants to use sumolib.net, it has to know which net file is used

Does it make sense if the net file path could be returned by TraCI? Or would you consider this bad design as it is of help only for a limited range of occasions? Related to #11276  #11385.

**Comment by namdre** [comment]
I think being able to retrieve the network file path via TraCI wouldn't hurt.
Also, the functionality for checking whether two lanes are connected without lane changing could be turned into a sumolib.net library function to be used in other contexts.

It should probably be restrained to checking along a fixed list of edges (i.e. the route of the ego vehicle) to avoid extended searches.

**Comment by m-kro** [comment]
Added a more general solution: query any available SUMO option.

**Comment by behrisch** [comment]
@m-kro looks finished to me?

**Comment by m-kro** [comment]
@behrisch So no change of the constant? Ok then...

**Comment by behrisch** [comment]
almost forgot about that
