### ISSUE TITLE
Disabling auto removal of nonmoving vehicles

### ISSUE THREAD

**Issue by laurayuzheng** [eclipse/sumo#11323]
I'm trying to run co-simulation of SUMO and CARLA. Currently, I initialize the world with CARLA NPCs, and the synchronization is handled by the tick() function from this script: 
https://github.com/carla-simulator/carla/blob/8854804f4d7748e14d937ec763a2912823a7e5f5/Co-Simulation/Sumo/run_synchronization.py#L99

In short, the script updates SUMO state every tick by getting every CARLA vehicle and transforming it to SUMO coordinates. 
My goal with co-simulation is to collect CARLA sensor data along with simulation states from SUMO. It seems to work fine, but SUMO seems to randomly remove vehicles which have stopped moving for too long (and thus I get empty subscription results for vehicles which had subscriptions before). I tried to find documentation or sift through other issues on this, but I couldn't find anything on the auto removal of stopped vehicles. 

My question in short is _can I disable SUMO auto-removing vehicles via TraCI?_ I just need the sumo simulator to reflect that of the CARLA simulator, and all adding and removing of vehicles should be handled on the CARLA side. 

SUMO version: 1.10.0 
CARLA version: 0.9.10 

Any help is greatly appreciated!

**Comment by m-kro** [comment]
Vehicles leave when they have completed their route. This may be happen even earlier when they are [teleported](https://sumo.dlr.de/docs/Simulation/Why_Vehicles_are_teleporting.html). Some options to change / extend the route during simulation:
- [Rerouter ](https://sumo.dlr.de/docs/Simulation/Rerouter.html) item (reroute vehicles at a certain position)
- [Rerouting ](https://sumo.dlr.de/docs/Demand/Automatic_Routing.html) device
- Set the route directly via[ TraCI](https://sumo.dlr.de/pydoc/traci._vehicle.html#VehicleDomain-setRoute)

**Comment by namdre** [comment]
Actually, as long as you send a 'moveToXY' command in every simulation step, then vehicles will never be removed due to *reaching the end of their route* because the route will keep being extended (but you have to send moveToXY regardless of whether the vehicle has moved or not).

If sumo gives you warnings of the sort "Teleporting vehicles ..** then the remedy is setting option **--time-to-teleport -1**

**Comment by laurayuzheng** [comment]
Thanks for the speedy responses! Per the advice I looked at synchronization tick updates. 
I'm not _exactly_ sure what happened, but I optimized tick updates slightly and the vehicle removal problem seems to have fixed itself.. 
previously, 'moveToXY' command was called every tick, but co-simulation is very slow. Since CARLA controls the traffic and SUMO is only used for state labeling purposes, I update the SUMO simulation with 'moveToXY' once every N=10 CARLA ticks (when data is saved), instead of every CARLA tick. Now, everything seems to work fine and all vehicles in SUMO remain in simulation. 

I'll be closing this issue, but could slow co-simulation be a factor here?

**Comment by namdre** [comment]
updating positions in sumo less frequently shouldn't generally be a problem. You could set a different step-length in sumo that corresponds to the desired sumo-updating-period. Just make sure you call moveToXY with every call to `traci.simulationStep`.
