### ISSUE TITLE
where is the source code for Dijkstra, A star or other shortest path algorithm?

### ISSUE THREAD

**Issue by thinker310** [eclipse/sumo#11322]
Hello, I 'd like to find the source code for the shortest path algorithms in SUMO, but I did not see the code files, could you help me? In addition, I wonder if there exist some methods to retrieve the travel time for the connections in a node, because the weights for those shortest path algorithm take only account into link travel time, not considering the consumption in an intersection. 
Thank you in advance!

**Comment by namdre** [comment]
https://github.com/eclipse/sumo/tree/main/src/utils/router

the routing algorithms do take travel time and effort (i.e. consumption) on junctions into account (this is what the 'via' refers to ):
https://github.com/eclipse/sumo/blob/18c69e809f07fd2bcd2fbd0f33821f1e3eea274c/src/utils/router/DijkstraRouter.h#L211
