### ISSUE TITLE
TraCI Module - Problems running traci.isEmbedded()

### ISSUE THREAD

**Issue by Viloa13** [eclipse/sumo#11332]
```
def embed_traci(exe_name):
PORT = 8813  
if not traci.isEmbedded()
```
When I use the traci.isEmbedded(),  I get the following error: 
`AtributeError: module 'traci' has no attribute 'isEmbedded'`

 When I search for the traci module, and use the dir command to analyze , there is no isEmbedded function at all:
['Connection', 'FatalTraCIError', 'StepListener', 'TraCIException', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_busstop', '_calibrator', '_chargingstation', '_edge', '_gui', '_inductionloop', '_junction', '_lane', '_lanearea', '_meandata', '_multientryexit', '_overheadwire', '_parkingarea', '_person', '_poi', '_polygon', '_rerouter', '_route', '_routeprobe', '_simulation', '_trafficlight', '_variablespeedsign', '_vehicle', '_vehicletype', 'absolute_import', 'addStepListener', 'busstop', 'calibrator', 'chargingstation', 'close', 'connect', 'connection', 'constants', 'domain', 'edge', 'exceptions', 'getConnection', 'getFreeSocketPort', 'getLabel', 'getVersion', 'gui', 'hasGUI', 'inductionloop', 'init', 'isLibsumo', 'isLibtraci', 'isLoaded', 'junction', 'lane', 'lanearea', 'load', 'main', 'meandata', 'multientryexit', 'os', 'overheadwire', 'parkingarea', 'person', 'poi', 'polygon', 'print_function', 'removeStepListener', 'rerouter', 'route', 'routeprobe', 'setConnectHook', 'setLegacyGetLeader', 'setOrder', 'simulation', 'simulationStep', 'socket', 'start', 'step', 'storage', 'subprocess', 'switch', 'sys', 'tc', 'time', 'trafficlight', 'variablespeedsign', 'vehicle', 'vehicletype', 'warnings']

Can anyone explain how can I locate it? Thanks 
I am using **SUMO-version: 1.13.0**, was traci.isEmbedded included in another version?
**operating system: windows**

**Comment by namdre** [comment]
The function no longer exists because the related feature became obsolete. If you need to translate older scripts that use this method, you can always replace `traci.isEmbedded()` with `False`
