### ISSUE TITLE
netedit freezes on right-click

### ISSUE THREAD

**Issue by yunpangfloetteroed** [eclipse/sumo#11359]
Add your issue description here.
as title. This problem does not appear when using sumo-gui.

*If possible, upload an example that shows your problem.*
see the attached file

**SUMO-version:**
v1_14_1+0310-2143ada4799

**operating system:**
Windows

[osm.net.xml.zip](https://github.com/eclipse/sumo/files/9337266/osm.net.xml.zip)
s

**Comment by namdre** [comment]
problem is not related to locate dialog. Simply doing a right-click near edge 376977029#0 causes the problem.

Works fine on my machines though.

**Comment by yunpangfloetteroed** [comment]
wierd... Is it related to graphic card?

**Comment by angelobanse** [comment]
For me (using version `v1_14_1+0318-111e40803be`) right-clicking near that edge works just fine on macOS Monterey and on my DLR laptop.

**Comment by m-kro** [comment]
Same here, no problem on Window...

**Comment by yunpangfloetteroed** [comment]
After internal software updates and computer restart I do not experience this problem on my laptop. So, this problem cannot be re-produced. @namdre @palvarezlopez: close this ticket?

**Comment by palvarezlopez** [comment]
Yes. We can reopen again in the future if it's needed.
