### ISSUE TITLE
Emission Heatmap

### ISSUE THREAD

**Issue by erev-84** [eclipse/sumo#11351]
Hello,

Is there have any way to generate Emission Heatmap as shown below

![A15C2D3E-FFA5-4D93-BF67-208988C825AE](https://user-images.githubusercontent.com/82845085/184512427-fd5def3f-433c-4fb4-9228-f8d333c2781c.jpeg)

**Comment by namdre** [comment]
you can combine https://sumo.dlr.de/docs/Simulation/Output/Lane-_or_Edge-based_Emissions_Measures.html
with either
- https://sumo.dlr.de/docs/sumo-gui.html#visualizing_edge-related_data + screenshot
- https://sumo.dlr.de/docs/Tools/Visualization.html#plot_net_dumppy

**Comment by erev-84** [comment]
Hello @namdre ,

I didn't quite understand how to do it. Is there any example or tutorial you can show me? or can you give me a little more detail about how I can do it, please?

**Comment by namdre** [comment]
find example code at https://sumo.dlr.de/extractTest.php?path=sumo/output/meannoise_edgebased/two_same_vehicles/interval60s

**Comment by erev-84** [comment]
Hello @namdre 

I generated aggregated_60.xml file by running sumocfg then I tried the following code to visualize the the noise but unfortunately i couldn't. That's why, could you tell me how the code should be written please?

`python plot_net_dump.py -v -n net.net.xml \
 --xticks 7000,14001,2000,16 --yticks 9000,16001,1000,16 \
 --measures noise,noise --xlabel [m] --ylabel [m] \
 --default-width 1 -i aggregated_60.xml,aggregated_60.xml \
 --xlim 7000,14000 --ylim 9000,16000 \
 --default-width .5 --default-color #606060 \
 --min-color-value -.1 --max-color-value .1 \
 --max-width-value .1  --max-width 3 --min-width .5 \
 --colormap "#0:#00c000,.25:#408040,.5:#808080,.75:#804040,1:#c00000"
`

![image](https://user-images.githubusercontent.com/82845085/184645338-89093b4b-0001-4ab2-adc4-2e8b3056e444.png)
![image](https://user-images.githubusercontent.com/82845085/184645399-81ccce05-7a9f-45b5-bba4-30d29200fe7d.png)
![image](https://user-images.githubusercontent.com/82845085/184645690-93b1480d-554d-409a-95fb-de23743fe0fc.png)

I want to ask one last thing, how is the "aggregated_60.xml" file created? I searched for "aggregated" in all additional files to check the code, but I couldn't find anything. Could you please give me information about how this file was created?

**Comment by namdre** [comment]
The following works: "python3 /scr1/sumoD/tools/visualization/plot_net_dump.py -v -n net.net.xml --measures noise,noise --default-width 1 -i aggregated_60.xml,aggregated_60.xml --log-colors --log-widths" (since the output contains 3 data intervals, 3 images are created in sequence).

> I want to ask one last thing, how is the "aggregated_60.xml" file created?
Please look carefully at the .sumocfg and at input_additional.add.xml.
Then reread https://sumo.dlr.de/docs/Simulation/Output/Lane-_or_Edge-based_Emissions_Measures.html

**Comment by namdre** [comment]
Also, there was a bug in the default linear color scale generation (now fixed), so thanks for bringing this up.

**Comment by erev-84** [comment]
> Also, there was a bug in the default linear color scale generation (now fixed), so thanks for bringing this up.

Hello @namdre,

I am happy to be able to help make Sumo better. Also, thank you very much for your helps. You have given very descriptive answers to all the questions I have asked so far and you have helped me a lot and for that I am very grateful to you.

by the way, I updated the "tools/sumolib/visualization/helpers.py" file as seen below 

![image](https://user-images.githubusercontent.com/82845085/184880460-ee214990-f4f0-4e0b-baca-b6a9c91d461e.png)
![image](https://user-images.githubusercontent.com/82845085/184880348-18b8fcc6-05a2-4feb-bc60-b49f25385626.png)

But I am getting the error seen in the screenshot below, what is the reason for this?
![image](https://user-images.githubusercontent.com/82845085/184880718-9f0c8534-f6ec-40b0-8bd8-d3890169f9a8.png)

**Comment by namdre** [comment]
The error is due to invalid xml file given as input. Possibly you left sumo-gui still open and the final lines had not yet been written to the file.

**Comment by erev-84** [comment]
I uploaded a screen recording and network files. Could you check them please?

[Uploading bandicam 2022-08-16 16-02-07-670.zip…]()
[_output_meannoise_edgebased_two_same_vehicles_interval60s.zip](https://github.com/eclipse/sumo/files/9351223/_output_meannoise_edgebased_two_same_vehicles_interval60s.zip)

**Comment by erev-84** [comment]
I updated the "tools/visualization/plot_net_dump.py" file but I am still getting the error below. 

![image](https://user-images.githubusercontent.com/82845085/184899075-0ad6c850-29a5-4fcb-8d5b-08db3eb22704.png)

if you want to check, I attached the updated version of plot_net_dump.py

[plot_net_dump.zip](https://github.com/eclipse/sumo/files/9351720/plot_net_dump.zip)

**Comment by namdre** [comment]
you file contains some new lines but didn't remove the necessary lines. Simply copy the correct file form here:  https://raw.githubusercontent.com/eclipse/sumo/main/tools/visualization/plot_net_dump.py

**Comment by erev-84** [comment]
> The following works:
> 
> `python3 tools/visualization/plot_net_dump.py -v -n net.net.xml --measures noise,noise --default-width 1 -i aggregated_60.xml,aggregated_60.xml --log-colors --log-widths`
> 
> (since the output contains 3 data intervals, 3 images are created in sequence).
> 
> > I want to ask one last thing, how is the "aggregated_60.xml" file created?
> 
> Please look carefully at the .sumocfg and at input_additional.add.xml. Then reread https://sumo.dlr.de/docs/Simulation/Output/Lane-_or_Edge-based_Emissions_Measures.html

Hello,

First of all, I'm sorry if I'm asking too many questions.

It's working right now and I generated a figure with the command you gave but only 1 figure generated 3 images are not created in sequence

![image](https://user-images.githubusercontent.com/82845085/184908071-06de2fc6-7265-44a1-9ee2-d2ab101c9ba0.png)

**Comment by namdre** [comment]
once you close the figure, the next one opens

**Comment by erev-84** [comment]
Hello,

I faced with a problem, Could you check the attached screen recording?

[bandicam 2022-08-16 19-07-40-535.zip](https://github.com/eclipse/sumo/files/9352637/bandicam.2022-08-16.19-07-40-535.zip)

**Comment by erev-84** [comment]
I faced with one more problem, I created emission output with the command below

`<laneData id="dump_60" type="emissions" freq="60" file="emissions.xml" excludeEmpty="true"/>`

![image](https://user-images.githubusercontent.com/82845085/184941039-b2ed91a5-8c99-4667-9ea9-b36dd824b4a2.png)

Generated emission file ==>

![image](https://user-images.githubusercontent.com/82845085/184941248-a97ec5ed-cdce-4f48-a9ba-7d8a65da4526.png)

plot_net_dump.py Command ==>

`python plot_net_dump.py -v -n net.net.xml --measures  CO2_normed,CO2_normed --default-width 1 -i emissions.xml,emissions.xml --log-colors --log-widths`

Error ==>

`Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. Tüm hakları saklıdır.

C:\Users\Erol\Desktop\Sumo heatmap\_output_meannoise_edgebased_two_same_vehicles
_interval60s>python plot_net_dump.py -v -n net.net.xml --measures  CO2_normed,CO
2_normed --default-width 1 -i emissions.xml,emissions.xml --log-colors --log-wid
ths
Reading network from 'net.net.xml'
Reading colors from 'emissions.xml' (attribute:CO2_normed)
Reading width attribute from 'emissions.xml' (attribute:CO2_normed)
Processing interval with a beginning of 0.0
Color values are between None and None
Width values are between None and None
Traceback (most recent call last):
  File "C:\Users\Erol\Desktop\Sumo heatmap\_output_meannoise_edgebased_two_same_
vehicles_interval60s\plot_net_dump.py", line 268, in <module>
    sys.exit(main(sys.argv))
  File "C:\Users\Erol\Desktop\Sumo heatmap\_output_meannoise_edgebased_two_same_
vehicles_interval60s\plot_net_dump.py", line 241, in main
    color_bar = plt.colorbar(sm)
  File "C:\Ptthon 3.10\lib\site-packages\matplotlib\pyplot.py", line 2109, in co
lorbar
    ret = gcf().colorbar(mappable, cax=cax, ax=ax, **kw)
  File "C:\Ptthon 3.10\lib\site-packages\matplotlib\figure.py", line 1210, in co
lorbar
    cb = cbar.Colorbar(cax, mappable, **cb_kw)
  File "C:\Ptthon 3.10\lib\site-packages\matplotlib\colorbar.py", line 483, in _
_init__
    self._reset_locator_formatter_scale()
  File "C:\Ptthon 3.10\lib\site-packages\matplotlib\colorbar.py", line 1206, in
_reset_locator_formatter_scale
    self._process_values()
  File "C:\Ptthon 3.10\lib\site-packages\matplotlib\colorbar.py", line 1138, in
_process_values
    self.norm.vmin = 0
  File "C:\Ptthon 3.10\lib\site-packages\matplotlib\colors.py", line 1150, in vm
in
    self._changed()
  File "C:\Ptthon 3.10\lib\site-packages\matplotlib\colors.py", line 1178, in _c
hanged
    self.callbacks.process('changed')
  File "C:\Ptthon 3.10\lib\site-packages\matplotlib\cbook\__init__.py", line 292
, in process
    self.exception_handler(exc)
  File "C:\Ptthon 3.10\lib\site-packages\matplotlib\cbook\__init__.py", line 96,
 in _exception_printer
    raise exc
  File "C:\Ptthon 3.10\lib\site-packages\matplotlib\cbook\__init__.py", line 287
, in process
    func(*args, **kwargs)
  File "C:\Ptthon 3.10\lib\site-packages\matplotlib\cm.py", line 618, in changed

    self.callbacks.process('changed', self)
  File "C:\Ptthon 3.10\lib\site-packages\matplotlib\cbook\__init__.py", line 292
, in process
    self.exception_handler(exc)
  File "C:\Ptthon 3.10\lib\site-packages\matplotlib\cbook\__init__.py", line 96,
 in _exception_printer
    raise exc
  File "C:\Ptthon 3.10\lib\site-packages\matplotlib\cbook\__init__.py", line 287
, in process
    func(*args, **kwargs)
  File "C:\Ptthon 3.10\lib\site-packages\matplotlib\colorbar.py", line 551, in u
pdate_normal
    self.draw_all()
  File "C:\Ptthon 3.10\lib\site-packages\matplotlib\colorbar.py", line 578, in d
raw_all
    self._process_values()
  File "C:\Ptthon 3.10\lib\site-packages\matplotlib\colorbar.py", line 1139, in
_process_values
    self.norm.vmax = 1
  File "C:\Ptthon 3.10\lib\site-packages\matplotlib\colors.py", line 1161, in vm
ax
    self._changed()
  File "C:\Ptthon 3.10\lib\site-packages\matplotlib\colors.py", line 1178, in _c
hanged
    self.callbacks.process('changed')
  File "C:\Ptthon 3.10\lib\site-packages\matplotlib\cbook\__init__.py", line 292
, in process
    self.exception_handler(exc)
  File "C:\Ptthon 3.10\lib\site-packages\matplotlib\cbook\__init__.py", line 96,
 in _exception_printer
    raise exc
  File "C:\Ptthon 3.10\lib\site-packages\matplotlib\cbook\__init__.py", line 287
, in process
    func(*args, **kwargs)
  File "C:\Ptthon 3.10\lib\site-packages\matplotlib\cm.py", line 618, in changed

    self.callbacks.process('changed', self)
  File "C:\Ptthon 3.10\lib\site-packages\matplotlib\cbook\__init__.py", line 292
, in process
    self.exception_handler(exc)
  File "C:\Ptthon 3.10\lib\site-packages\matplotlib\cbook\__init__.py", line 96,
 in _exception_printer
    raise exc
  File "C:\Ptthon 3.10\lib\site-packages\matplotlib\cbook\__init__.py", line 287
, in process
    func(*args, **kwargs)
  File "C:\Ptthon 3.10\lib\site-packages\matplotlib\colorbar.py", line 551, in u
pdate_normal
    self.draw_all()
  File "C:\Ptthon 3.10\lib\site-packages\matplotlib\colorbar.py", line 578, in d
raw_all
    self._process_values()
  File "C:\Ptthon 3.10\lib\site-packages\matplotlib\colorbar.py", line 1144, in
_process_values
    b = self.norm.inverse(b)
  File "C:\Ptthon 3.10\lib\site-packages\matplotlib\colors.py", line 1554, in in
verse
    raise ValueError("Invalid vmin or vmax")
ValueError: Invalid vmin or vmax

C:\Users\Erol\Desktop\Sumo heatmap\_output_meannoise_edgebased_two_same_vehicles
_interval60s>`

**Comment by namdre** [comment]
> Hello,
> 
> I faced with a problem, Could you check the attached screen recording?
> 
> [bandicam 2022-08-16 19-07-40-535.zip](https://github.com/eclipse/sumo/files/9352637/bandicam.2022-08-16.19-07-40-535.zip)

update tools/sumolib/visualization/helpers.py with this https://raw.githubusercontent.com/eclipse/sumo/main/tools/sumolib/visualization/helpers.py

**Comment by namdre** [comment]
please zip and attach emissions2.xml

**Comment by erev-84** [comment]
[_output_meannoise_edgebased_two_same_vehicles_interval60s.zip](https://github.com/eclipse/sumo/files/9362989/_output_meannoise_edgebased_two_same_vehicles_interval60s.zip)

**Comment by namdre** [comment]
same as before: the file wasn't completely written most likely because sumo-gui wasn't closed yet.

**Comment by erev-84** [comment]
Hello, 

I tested on 3 different scenarios, but I got the following error in all of them. I would also like to point out that I am waiting for the simulation to complete, then I close the sumo-gui. Is there a bug or am I doing something wrong? Finally, please excuse me if I'm asking too many questions.

`
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. Tüm hakları saklıdır.

C:\Users\Erol\test>python plot_net_dump.py -v -n test.net.xml --measures CO2_nor
med,CO2_normed --default-width 1 -i emissions2.xml,emissions2.xml --log-colors -
-log-widths
Reading network from 'test.net.xml'
Reading colors from 'emissions2.xml' (attribute:CO2_normed)
Reading width attribute from 'emissions2.xml' (attribute:CO2_normed)
Processing interval with a beginning of 0.0
Traceback (most recent call last):
  File "C:\Users\Erol\test\plot_net_dump.py", line 268, in <module>
    sys.exit(main(sys.argv))
  File "C:\Users\Erol\test\plot_net_dump.py", line 189, in main
    helpers.logNormalise(colors, maxColorValue)
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\sumolib\visualization\helpers.
py", line 288, in logNormalise
    valRange = emax - emin
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'

C:\Users\Erol\test>
`
I 
![image](https://user-images.githubusercontent.com/82845085/185181771-573715b7-50a2-45e9-88b9-af6a11236e65.png)
![image](https://user-images.githubusercontent.com/82845085/185182069-0872eab9-ce6b-4f7e-8c7d-dfbec56ff4b0.png)

[test.zip](https://github.com/eclipse/sumo/files/9364326/test.zip)

**Comment by namdre** [comment]
do another update of https://raw.githubusercontent.com/eclipse/sumo/main/tools/sumolib/visualization/helpers.py

**Comment by erev-84** [comment]
Hello,

I am so sorry but it is still not working you can check the attached screen recording to see the steps I followed.

[bandicam 2022-08-18 16-47-20-145.zip](https://github.com/eclipse/sumo/files/9374358/bandicam.2022-08-18.16-47-20-145.zip)

**Comment by namdre** [comment]
A space character slipped into your command line: **--measures CO2_nor med,CO2_normed**
Look closely at the output
`Reading colors from emissions2.xml (attribute:CO2_nor)`

**Comment by erev-84** [comment]
Sorry it's my mistake but I am still getting error, (I am using the updated version of the helpers.py)

is there something i did wrong? 

[bandicam 2022-08-18 17-21-11-921.zip](https://github.com/eclipse/sumo/files/9374854/bandicam.2022-08-18.17-21-11-921.zip)

**Comment by namdre** [comment]
you are trying to plot empty intervals. update plot_net_dump.py to get a version that can handle this.

**Comment by erev-84** [comment]
I'm sorry for causing you so much trouble with this issue. But I think there are still some problems, I still can't generate the CO2_normed with updated version of the script.

[bandicam 2022-08-19 00-50-38-649.zip](https://github.com/eclipse/sumo/files/9377923/bandicam.2022-08-19.00-50-38-649.zip)

**Comment by behrisch** [comment]
Just for the sake of completeness. You are using lane based dumps but plot_net_dump expects edge based data (use edgeData instead of laneData).
