### ISSUE TITLE
In GNETLSFrame, sort programs by index

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#11358]
Currently are sorted using pointer:

![Sin título](https://user-images.githubusercontent.com/8238561/184629575-6cf039bf-74b1-4067-a81a-8388d7719bf3.png)

**Comment by namdre** [comment]
I think there is currently some code that relies on sorting-by-last edit

(if you duplicate a program, then the new program is selected because it's the first in the list)

**Comment by palvarezlopez** [comment]
But the list looks ugly :(

**Comment by namdre** [comment]
Yes. Though I still rate this as a minor problem because people rarely have multiple programs embedded in the net.

**Comment by palvarezlopez** [comment]
Probably I can solve it during #11360

**Comment by namdre** [comment]
please solve it separately rather than mixing the fixes.

**Comment by namdre** [comment]
:cry: as I expected: now when you duplicate a program, the list always switches to the first program rather than switching to the new one (as before) or even stay with the old.

This is way I recommended to delay this work until we have a regression test...
