### ISSUE TITLE
TraCI RerouteTraveltime not working

### ISSUE THREAD

**Issue by DFazekas** [eclipse/sumo#11353]
This may be a question rather than a bug. I just don't understand why it's not behaving as expected.

I simply want a single specific vehicle to avoid a specific edge.
The edge to avoid is highlighted here:
<img width="617" alt="image" src="https://user-images.githubusercontent.com/22490250/184522257-962863df-8ec0-4180-8ab9-881eca4689ba.png">

Soon after the target vehicle enters the network, I set its travel time for that edge to basically to 9999999999999 using TraCI. Then I trigger its reroute hoping it'll avoid that edge. These are the two commands used: `traci.vehicle.setAdaptedTraveltime(vehId, edgeId, 9999999999999)` and `traci.vehicle.rerouteTraveltime(vehId)`. Despite this, the vehicle follows the rest and drives straight through the edge regardless. Am I doing something wrong?

My setup is minimalistic. All edges have -1 (default) priority and identical length (500 meters). My trips file contains a handful of default vehicles with identical origin (far left edge) and destination (far right edge). The only other thing in my `main.py` script is:
```python
        traci.start(
        [
            sumoBinary,
            '-c', f'{dir}/config/main.sumocfg',
            '--device.rerouting.probability', '1',
            '--device.rerouting.period', '10'
        ])
```

Is the `device.rerouting.period` preventing TraCI from routing as desired? 

**SUMO-version:**
1.14.1

**operating system:**
Windows 10

**Comment by namdre** [comment]
please attach example files (directly as a zip archive)

**Comment by DFazekas** [comment]
> please attach example files (directly as a zip archive)

I found that removing the `rerouting.probability` and `rerouting.period` options resolved the issue; the vehicle reroutes as expected. However, reintroducing those options did not reproduce the bug. So I'll close this issue.
