### ISSUE TITLE
creeping collision with EIDM model

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#11361]
test coming soon

**Comment by namdre** [comment]
@domsall  I've found collisions in 9 of 64 test cases when running with (without option --end)
`tools/runSeeds.py -k test.sumocfg -a sumo --threads 16 --seeds 0:64`

**Comment by Domsall** [comment]
I found the issue and will upload it soon.
While working on this issue, I found two new bugs, one I fixed myself, the other one has to do with startupDelay:

When a vehicle is stopped, the stop-time does not count as waiting time. So during a stop, `myTimeSinceStartup` does not get reset. Could you please add this functionality? Thanks in advance!

**Comment by namdre** [comment]
You mean, a vehicle that is coming back from a stop should never experience startupDelay? Why not?

**Comment by Domsall** [comment]
no, it should :-)
this is just not happening right now

**Comment by namdre** [comment]
understood: #11374
