### ISSUE TITLE
Warning: The traffic light 'id' does not control any links; it will not be build.

### ISSUE THREAD

**Issue by JamesPsh** [eclipse/sumo#11363]
I set the "node type" to "traffic_light", but I can't input signal data. The error message is as below.
"Warning: The traffic light 'id' does not control any links; it will not be build."

Could I ask how can I solve this?

![image](https://user-images.githubusercontent.com/101240964/184779767-099b2d58-5122-4f34-ac2b-7d3958731b0c.png)
![image](https://user-images.githubusercontent.com/101240964/184779776-4e7183f8-effc-4f08-b4a1-ed6115ca7506.png)
![image](https://user-images.githubusercontent.com/101240964/184779790-65b1a470-f9e3-48fc-b263-b4cd280c47e7.png)

**Comment by m-kro** [comment]
Could you please add a example network file which shows the problem?

**Comment by JamesPsh** [comment]
@m-kro 

Here is the map file.
target node id is "cluster_188373_18950"
[sample.net.zip](https://github.com/eclipse/sumo/files/9348631/sample.net.zip)
.

**Comment by namdre** [comment]
all connections at that junction have attribute 'uncontrolled=true'.
See https://sumo.dlr.de/docs/Netedit/neteditUsageExamples.html#setting_connection_attributes
