### ISSUE TITLE
EIDM: vehicle does not reach stop, causing infinite sim

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#11364]
the vehicle stops  20cm before reaching the assigned stop position and thus the stop never qualifies as "reached".
Consequently, the simulation does not terminate.

same tests as for #11361  (seeds 14 and 36, and no **--end** option)

**Comment by namdre** [comment]
@Domsall function stopSpeed needs driving with increased precision.

**Comment by Domsall** [comment]
How can I spot the erroneous stops?!

I used the following command, but was not successful:
`sumo-guiD.exe --xml-validation never --write-license --default.speeddev 0 -n net.net.xml -r input_routes.rou.xml --no-step-log --step-length 0.1 --seed 36 -e 10000` and
`sumo-guiD.exe --xml-validation never --write-license --default.speeddev 0 -n net.net.xml -r input_routes.rou.xml --no-step-log --step-length 0.1 --seed 14 -e 10000`
