### ISSUE TITLE
duarouter --randomize flows couldn't match the vtype distribution

### ISSUE THREAD

**Issue by GNAWOAIM** [eclipse/sumo#11376]
Hi there,
 
i want to randomize  vehicles' departure times  of a flow,  to get a unevenly spaced flow, so i used duarouter option  --randomize-flows like below:

duarouter -n my.net.xml  -r my.rou.xml  --randomize-flows  -o randoflow.rou.xml 

my original rou.xml file with a definition of vType distribution with certain probabilities like below:

vType id="1"  vClass="custom1" probability="0.70"
vType id="2"  vClass="custom2" probability="0.30"
vTypeDistribution id="d1" vTypes="1 2"
route id="r0" edges="e1"  
flow id="flow1" route="r0" type="d1"  begin="0" end="3600" number="10

but the numbers of vehs from differnet vTypes after randomize flows, doenst follow the vType distribution probabilities.

i would like to know what could be the reason of this problem?
with many thanks!

**Comment by namdre** [comment]
which sumo version did you use?
can you attach example inputs?

**Comment by GNAWOAIM** [comment]
with an older version 1.10.
here's the input files. 
[input.zip](https://github.com/eclipse/sumo/files/9381894/input.zip)
Thank you!

**Comment by GNAWOAIM** [comment]
> which sumo version did you use? can you attach example inputs?

i've updated SUMO to the version of 1.14., but the numbers of vehs from different vTypes after randomize flows, still doenst follow the vType distribution probabilities. 
[input.zip](https://github.com/eclipse/sumo/files/9394363/input.zip)

**Comment by namdre** [comment]
Thanks for reporting! you can download a fixed version tomorrow at https://sumo.dlr.de/docs/Downloads.php#nightly_snapshots
