### ISSUE TITLE
issues (and crash) using the "undo/redo history" dialog

### ISSUE THREAD

**Issue by angelobanse** [eclipse/sumo#11370]
As we discussed on the phone, it seems to skip saving a step in the undo/redo history.

```
Error: Attempt to delete instance of GNEReferenceCounter with count 4
Error: Attempt to delete instance of GNEReferenceCounter with count 4
Error: Attempt to delete instance of GNEReferenceCounter with count 2
Error: Attempt to delete instance of GNEReferenceCounter with count 3
Error: Attempt to delete instance of GNEReferenceCounter with count 3
zsh: segmentation fault  netedit
```

**Comment by namdre** [comment]
is this a regression? If so which version was still working?

**Comment by angelobanse** [comment]
This issue is present since version 1.14.0 (where the ability to click on undo/redo elements from the history dialog was introduced). So no regression...

**Comment by palvarezlopez** [comment]
Part of ticket https://github.com/eclipse/sumo/issues/4765

**Comment by palvarezlopez** [comment]
The problem was caused by the use of MFXTreeListDynamic. The new UndoList design uses another elements.
