### ISSUE TITLE
Netedit 

### ISSUE THREAD

**Issue by erev-84** [eclipse/sumo#11388]
Hello

Is there have any way to remove back turns from whole network in simple way because removing back turns one by one is very difficult in  big networks

![image](https://user-images.githubusercontent.com/82845085/185687815-1668b50c-c2d8-4cb7-a629-19396b953b85.png)

**Comment by m-kro** [comment]
Run netconvert with option `--no-turnarounds true` (see [docs](https://sumo.dlr.de/docs/netconvert.html#junctions)).

**Comment by erev-84** [comment]
Hello

Unfortunately it did not work, could you give me information about what I'm doing wrong?

![image](https://user-images.githubusercontent.com/82845085/185748393-04283ffc-819b-4880-b8d9-5474c4f42f60.png)
![image](https://user-images.githubusercontent.com/82845085/185748354-9b0b7c11-bc60-4c58-8abb-1bd15921e702.png)
![image](https://user-images.githubusercontent.com/82845085/185748425-cc146fb5-bb71-43d8-b0a1-d87784987ae4.png)

**Comment by erev-84** [comment]
I also tried the following options but nothing changed on my network

![image](https://user-images.githubusercontent.com/82845085/185749227-bc7572b7-96c2-4b1c-93fd-754ccb4a1c07.png)

**Comment by palvarezlopez** [comment]
Can you send us our entire newtork (with all files generated by OSM)?

**Comment by erev-84** [comment]
Please check the attached file 

Also, the command I tried is as follow

`netconvert -s osm.net.xml --no-turnarounds true --no-turnarounds.geometry true --no-turnarounds.tls true`

[2022-08-22-10-38-24.zip](https://github.com/eclipse/sumo/files/9392353/2022-08-22-10-38-24.zip)

**Comment by erev-84** [comment]
Hello @palvarezlopez ,

Did you have an opportunity to check the file I attached?

What the problem is?

**Comment by palvarezlopez** [comment]
@erev-84 yes. The problem is that you modified the net file, instead of netconvert file (osm.netccfg) . I have modified it and recompiled network using netconvert. Check it: [2022-08-22-10-38-24_updated.zip](https://github.com/eclipse/sumo/files/9394622/2022-08-22-10-38-24_updated.zip)

**Comment by erev-84** [comment]
@palvarezlopez Thank you very much
