### ISSUE TITLE
dailyBuildMSVC.py

### ISSUE THREAD

**Issue by erev-84** [eclipse/sumo#11389]
Hello,

I am trying to run dailyBuildMSVC.py to get the Nightly Snapshots but I am getting the following error

![image](https://user-images.githubusercontent.com/82845085/185792351-51308985-5c42-4245-a496-8dbadb1d4c69.png)

I would be very grateful if you could explain to me step by step how I should run the dailyBuildMSVC.py script to get the Nightly Snapshots?

**Comment by palvarezlopez** [comment]
Hi Ereve. If you want the daily nightly snapshot, you cannot use dailyBuildMSVC.py. Instead you mus either download directly from SUMO Webseite, or run **SUMO\tools\build\updateDailyVersion.py**

**Comment by erev-84** [comment]
Hello,

First of all thank you very much for the reply

what do I need to do for to fix the problem seen below

![image](https://user-images.githubusercontent.com/82845085/185869565-6d83f1a4-c652-4e36-b57b-a7a7df51f21f.png)

**Comment by palvarezlopez** [comment]
you need to execute the script with admin rights, because you have your SUMO installation in C:\Program files

**Comment by erev-84** [comment]
Hello @palvarezlopez 

Thank you very much

I faced with a problem, could you help me with this problem please? 

![image](https://user-images.githubusercontent.com/82845085/185945937-e6c1184b-fe18-41e2-8947-108303551a91.png)

**Comment by erev-84** [comment]
Hello @palvarezlopez 

I updated the sumo with updateDailyVersion.py script, but as you can see in the screenshot below, the modified date of the files has not changed, what is the reason of this? If the dates don't change doesn't mean the files don't change either?

![image](https://user-images.githubusercontent.com/82845085/185964794-1a3a00dc-0d70-4d1d-a674-6770ae9c25a6.png)

**Comment by erev-84** [comment]
Hello again,

I tried one more time and now I am getting the error below, What is the reason of this error? and what do I need to do for the succesful instalation?

![image](https://user-images.githubusercontent.com/82845085/186173995-7cb86635-eed3-4b9d-9864-18f90624c97b.png)

**Comment by palvarezlopez** [comment]
@erev-84 what is your Python version?

**Comment by erev-84** [comment]
![image](https://user-images.githubusercontent.com/82845085/186176108-9b4671d0-0b49-438a-8f91-8b6f3191494f.png)

**Comment by palvarezlopez** [comment]
Try to write a simply python scripts that uses os.path.samefile() and say me if works with your python version. You have an example here

https://www.geeksforgeeks.org/python-os-path-samefile-method/#:~:text=os.-,path.,number%20of%20the%20given%20paths.

**Comment by erev-84** [comment]
i hope i did it right

![image](https://user-images.githubusercontent.com/82845085/186192873-86e9a528-69ee-4cc9-b396-2b14b9a79f57.png)

**Comment by palvarezlopez** [comment]
Check the python output. You're using an invalid pyhton version (probably because you're using the windows version). Instead "test.py", try "python test.py"

**Comment by erev-84** [comment]
![image](https://user-images.githubusercontent.com/82845085/186414106-99db332c-0012-4b20-a80b-020af9027be0.png)

**Comment by palvarezlopez** [comment]
install symlink using: "pip install symlink"
