### ISSUE TITLE
unable to set bidi-edges with netedit

### ISSUE THREAD

**Issue by yunpangfloetteroed** [eclipse/sumo#11397]
Add your issue description here.
Some edges cannot be set to bidi-edges with the spread-type-setting "center", since the check-box "isBidi" is either grayed out or has not action after clicking (see the attached example files problem2 and problem).
 
**SUMO-version:**
v1_14_1+0350-48d7f2812e8
**operating system:**
Windows
[problem2.net.xml.zip](https://github.com/eclipse/sumo/files/9400652/problem2.net.xml.zip)
[problem_edges.zip](https://github.com/eclipse/sumo/files/9400721/problem_edges.zip)

**Comment by yunpangfloetteroed** [comment]
The file problem2.net.xml.zip is redundant.  This issue is also reported in the ticket #10445

**Comment by yunpangfloetteroed** [comment]
A extracted network is generated and attached. A reverse edge (-403054383#8) of 403054383#8 is generated. When clicking one of these two edge the attribute "isBidi" of the Mode Inspect is still grayed out. No Bidi-edges can be generated accordingly.

Where exactly should a respective test be generated under sumo\tests?

[net.net.xml.zip](https://github.com/eclipse/sumo/files/9434456/net.net.xml.zip)

**Comment by namdre** [comment]
The geometries of both edges differs with regard to the endpoints. This is visible to the naked when looking at junction 5912628377

To enable bidi, select both edges and chose 'reset endpoints' from the context menu.

**Comment by yunpangfloetteroed** [comment]
The reversed edge is automatically generated by netedit. Don't they supposely have the same geometries regarding the end points? 

Just tried the method with 'reset endpoints' the endpoints are set back to the original ones once pressing F5/saving the network. And they can still not be set to bidi-edges.

**Comment by yunpangfloetteroed** [comment]
I attached another case here: Edges c and -c should be set to bid-edges.
1. No bidi can be generated after selecting these two edges and clicking the box "isBidi"
2. unable to reset endpoints: 'reset endpoints' is grayed out after selecting both edges
[net.net.xml.zip](https://github.com/eclipse/sumo/files/9454436/net.net.xml.zip)
