### ISSUE TITLE
Human-readable-time option

### ISSUE THREAD

**Issue by erev-84** [eclipse/sumo#11390]
Hello,

I want the time in my simulation to be in human readable format as in the example below. 

![image](https://user-images.githubusercontent.com/82845085/185794529-812ef0bf-af7c-48d9-927f-dab80207d7c8.png)

For this, I added the following code to the "net.xml" file by selecting the "human-readable-time" (option ==> output)  from Netedit  as I showed in the attached screen recording [bandicam 2022-08-21 16-53-04-629.zip](https://github.com/eclipse/sumo/files/9389235/bandicam.2022-08-21.16-53-04-629.zip), but nothing changed, what i did wrong? and Could you please help me on what should i do to make the time in "sumo-gui" in human readable format?

```
     <output>
         <human-readable-time value="true"/>
     </output>

```

**Comment by palvarezlopez** [comment]
Hi Ereve. This option is only for the output. If you want to see the counter in human readable format, you must click over label "time" to switch between all time formats.
