### ISSUE TITLE
flowrouter

### ISSUE THREAD

**Issue by Mtbttt** [eclipse/sumo#11395]
Hello, 

I have used flowrouter to estimate the count in my network where no detector data is available. When I simulate with flowrouter outputs, I see some of the vehicle routes are too long (they pass the same place twice while the vehicle can pass using other lanes). I tried using implausibleroutes. I added my network and the routes that flowrouter generated. the implausible routes gave me four outputs (routes22.8.rou.xml.implausible.add.xml, routes22.8.rou.xml.rerouted.rou.alt.xml, routes22.8.rou.xml.vehRoutes.xml,routes22.8.rou.xml.rerouted.rou.xml). When I tried simulating with my network file and routes22.8.rou.xml.rerouted.rou.xml, the simulation ended very soon. Can anyone help me? How can I use the flowrouter and implausible routes at the same time?

**Comment by behrisch** [comment]
The implausible routes are not meant to be fed into the simulation but to be used in a rerun of flowrouter with the flowrestrictions option to forbid them.
