### ISSUE TITLE
car blocks itself during continuous laneChange after loading state

### ISSUE THREAD

**Issue by JaydenGao-gjd** [eclipse/sumo#11394]
Hello. I used saveState and loadState to reproduce the saved state. I found sometimes a car stopped suddenly like video "test1.mov" and "test2.mov". But the simulation ran normally when I didn‘t use save and load state. I use "--ignore-junction-blocker 5", but it seems that it didn't work. The simulation code and config are zipped in "test_break.zip". Can you help me find why?

https://user-images.githubusercontent.com/56961646/185960620-8dace8be-468f-4f42-8e6f-d647a83b8bec.mov
[test_break.zip](https://github.com/eclipse/sumo/files/9395675/test_break.zip)

https://user-images.githubusercontent.com/56961646/185925769-6ae586e3-2c38-4545-87ad-123277927344.mov

car stopped suddenly 

*If possible, upload an example that shows your problem.*

**SUMO-version:1.14

**operating system:Mac OS

**Comment by namdre** [comment]
It's hard to figure out what is happening with all the different simulation starts. Please provide the following:

- a sumo configuration that saves the state
- a sumo configuration that loads the state which was saved by running the first configuration
- the id of the stuck vehicle and the time step when this happens when running the second simulation.

**Comment by JaydenGao-gjd** [comment]
> It's hard to figure out what is happening with all the different simulation starts. Please provide the following two **minimal** traceFiles (https://sumo.dlr.de/docs/TraCI/Interfacing_TraCI_from_Python.html#generating_a_log_of_all_traci_commands)
> 
> * a traceFile that saves a simulation state
> * a traceFile that calls loadState
> * the id of the stuck vehicle and the time step when this happens when running the second  traceFile

1. The first tracefile is "first_log" in "log" folder. 
2. The second tracefile is "second_log" in "log" folder. 
3. The stuck vehicle name is "sideroad.1020.0". The time step is 1140.
The saved state is in the "state" folder. Run the "control.py", and you can see the process of saving state, loading state and the stuck vehicle in the sumo-gui.
[test_break2.zip](https://github.com/eclipse/sumo/files/9427081/test_break2.zip)

Thanks for your time.

**Comment by JaydenGao-gjd** [comment]
Is there some way to solve this problem？
