### ISSUE TITLE
occupancy-info on bidi-edges cannot be interpreted in gui correctly

### ISSUE THREAD

**Issue by yunpangfloetteroed** [eclipse/sumo#11404]
Add your issue description here.
(1) The occupancy-info-color changes from low to high occupancy when only an object moves along a bidi-edge. 
(2) Moreover, the occupancy-info-color is displayed not on the correct edge, but on the opposite edge

*If possible, upload an example that shows your problem.*
On example can be found in the attached file: bike3 at Time 15s

**SUMO-version:**
v1_14_1+0350-48d7f2812e8
**operating system:**
Windows
[gui.zip](https://github.com/eclipse/sumo/files/9402580/gui.zip)

**Comment by namdre** [comment]
same problem occurs when combining the sublane model with opposite direction driving:
vehicles that a partially on an edge and going in the opposite direction are interpreted as if they were "old style" partial vehicles that occupy the whole space between their back-position and the end of the lane.
