### ISSUE TITLE
Help Needed regarding SpeedFactor

### ISSUE THREAD

**Issue by somkar** [eclipse/sumo#11407]
From the official sumo website, the formula is given below SpeedFactor
SpeedFactor = Vehicle speed/ Lane Speed limit

Since there are multiple attributes regarding speed i.e. "departSpeed" or "arrivalSpeed". Which attribute departSpeed or arrivalSpeed should be considered for calculating the SpeedFactor.
Any help or suggestion would be helpful.

SUMO-version:1.13.0

operating system: Windows

**Comment by m-kro** [comment]
Neither depart speed nor arrival speed - those concern only the moments when the vehicle is inserted and when it leaves the route. 
The speed factor references the allowed speed on a lane (see [docs ](https://sumo.dlr.de/docs/Networks/SUMO_Road_Networks.html#lanes)about SUMO lanes). You can edit this value in Netedit inspect mode: select an edge or a lane and change the speed attribute value.
