### ISSUE TITLE
About the capacity of SUMO

### ISSUE THREAD

**Issue by lightly-lyx** [eclipse/sumo#11400]
Hi, could anyone can tell me the capacity of SUMO. How many cars at most can operate at the same time? How many intersections can SUMO simulate?
Thanks in advance!

**Comment by namdre** [comment]
https://sumo.dlr.de/docs/FAQ.html#are_there_any_limits_in_regard_to_the_size_of_a_simulation_scenario
https://sumo.dlr.de/docs/FAQ.html#how_fast_can_sumo_run
