### ISSUE TITLE
make complete testsuite downloadable

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#11403]
The assumption in #9794 that all the downloadable zips from github (for the head and for the tags) contain the tests was wrong because we disabled them in the .gitattributes

**Comment by angelobanse** [comment]
What was the reason for preventing the tests export?

https://github.com/eclipse/sumo/blob/5426fe0ba58b2df17850e0b8538ef80bdd20f33c/.gitattributes#L69

**Comment by behrisch** [comment]
I think the main motivation was to use `git archive` to generate the release zip. But since we modify this archive anyway we might as well delete the tests afterwards.
