### ISSUE TITLE
Roud directional arrows on roundabout

### ISSUE THREAD

**Issue by erev-84** [eclipse/sumo#11410]
Hello 

![image](https://user-images.githubusercontent.com/82845085/186260787-d62fffa4-9f5c-4c7c-860d-fc541f5659be.png)

I want road directional arrows look like as below

![image](https://user-images.githubusercontent.com/82845085/186261723-b5a8760a-6e0b-4bdb-ac20-3162e9af00d6.png)

![image](https://user-images.githubusercontent.com/82845085/186261982-77529be1-4cea-48a5-b935-dd3b7b7a4a8a.png)

As can be seen from the screen recording [bandicam 2022-08-23 23-11-50-133.zip](https://github.com/eclipse/sumo/files/9410503/bandicam.2022-08-23.23-11-50-133.zip)  no matter what i do road directional arrows don't look the way i want. Could you tell me what i need to do to make them look like the way i want? or could you help me to do them as I want please?

My network file ==> [Gönyeli.zip](https://github.com/eclipse/sumo/files/9410561/Gonyeli.zip)

**Comment by namdre** [comment]
This is currently no supported. As a workaround you could disable drawing of directional arrows in the gui settings and substitute your own arrows by loading `<poi>` elements with an appropriate imgFile and angle attribute (https://sumo.dlr.de/docs/Simulation/Shapes.html#poi_point_of_interest_definitions)

**Comment by erev-84** [comment]
Hello @namdre 

Thanks for the reply 

First of all, I'm very sorry but I didn't understand exactly how to do it, could you please show me an example? Also, do I have to make my own direction lines for the whole network one by one from scratch? Is there a way to copy the directional arrows Which SUMO creates and just fix the wrong ones, or do I have to do all directional arrows from scratch?
Finally, how can I disable the directional arrows on SUMO GUI?

**Comment by namdre** [comment]
There is a gui setting in the 'Streets' tab *Show turning arrows* that disables **all** arrows in the network.
You could actually try to "patch over" only selected existing arrows by loading correcting images in the correct spot (instead of disabling all arrows). 
As an alternative to pois you may also use background images (placed at the appropriate layer): https://sumo.dlr.de/docs/sumo-gui.html#showing_background_images

Please refer to the linked documentation and hold your questions until you did some experiments. Be aware that my time is limited.

**Comment by namdre** [comment]
As you may have guessed by now, the aim of sumo-gui is not a photorealistic depiction of reality. The directional arrows are mainly meant to distinguish the available directions of movement and you are pretty much the first person ever who feels the need to customize their looks. 
Over time, some directional arrow assignments have to come to be used as semantic markers that are used within the simulation code (i.e. sumo vehicles set turn signals depending on whether a car wants to turn or not). In a roundabout, the cars that stay within generally do not set their turn signal whereas the cars that exit the roundabout do set their signals. Hence staying in the roundabout is coded as 'straight' whereas the exits are coded as turns. 

With regard to layering: for pois as well as for background images, the `layer` attribute determines the drawing order of items. A layer between 5 and 300 will put your image on top of the old arrows and below the cars.

**Comment by erev-84** [comment]
Hello @namdre 

Thank you very much, I changed the directional arrows successfully

**Comment by erev-84** [comment]
I wanted to prepare the following guide to explain step by step what to do for those who want to the same thing as me.

Step 1 ==> Create/draw your directional arrows by using any drawing software (e.g. photoshop) and save it as png (without background)

![erol](https://user-images.githubusercontent.com/82845085/186781383-1dd6e3fa-cf2c-49ff-ad90-0e6f294b2fd0.png)

Step 2 ==> Check the coorinates from the section seen below. You will need coordinates at step 4

![image](https://user-images.githubusercontent.com/82845085/186781485-91897f04-6d21-48ba-8d89-633b61c95dde.png)

Step 3 ==> open view settings 

![image](https://user-images.githubusercontent.com/82845085/186781620-11ffb841-ff10-4fb3-9fb4-5e71bb852908.png)

Step 4 ==> Load your background image and set it's X center, Y center, Height, Width 

![image](https://user-images.githubusercontent.com/82845085/186781763-d75f79cc-e0a5-4f9c-bd1c-b9bb97ea199b.png)

Step 5 ==> Set index between 6-300

![image](https://user-images.githubusercontent.com/82845085/186781904-991f6a71-3077-4d86-ac7b-8f60cdc2227a.png)

Results ==>

Before ==>
![image](https://user-images.githubusercontent.com/82845085/186782115-6a4668ac-1d7f-4bc6-9140-d8b1280aff72.png)



After ==>
![image](https://user-images.githubusercontent.com/82845085/186782360-81c1c973-f86d-44aa-add1-5d1eecb60e93.png)
