### ISSUE TITLE
add netconvert option for limiting angular velocity (trac #1141)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#1141]
The maximum speed on an edge should be influenced by its turning radius with sharper turns allowing less speed. This is particularly important on internal lanes which frequently take sharp turns (right turns, turnarounds).

It might also be a good idea to apply this to short edges with sharp turns anywhere else.
The question remains how to deal with long edges that have a sharp turn somewhere.
* one could add a netconvert option to cut this kind of edge into smaller parts on which the speed varies
* one could introduce a new network element which allows varying the speed in the middle of an edge (which might then serve additional purposes)

**Comment by namdre** [comment]
@leoluecken The conclusion of the linked report suggest that curvature and lane width are the main determinants of speed choice in curves. A suggested mechanism is the drivers desire to remain within lane boundaries when accounting for steering error.
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.468.8643&rep=rep1&type=pdf

**Comment by namdre** [comment]
implement #4219 instead

**Comment by namdre** [comment]
Micha suggest to do this only for internal lanes as it is a simply way to use a remaining degree of freedom (internal lane speeds are guessed anyway)

**Comment by namdre** [comment]
now using option by default via [d86c042719cde9194e68040d97e2451e8ea96ac5]
