### ISSUE TITLE
Why the E3 detector can not be built? 

### ISSUE THREAD

**Issue by thinker310** [eclipse/sumo#11411]
Hello, I encountered a problem that the E3 detectors are generated on the .net.xml file, but when I cannot run the configuration file successfully. The error tips me maybe the detector was declared twice, how to solve it? Thank you in advance and the attachment is my related SUMO file
[sumo_simulation.zip](https://github.com/eclipse/sumo/files/9414051/sumo_simulation.zip)
.

**Comment by namdre** [comment]
you config loads two additional files of which only one is provided in your zip

**Comment by thinker310** [comment]
> you config loads two additional files of which only one is provided in your zip

Sorry, I missed it and the e2.add.xml is another additional file
[e2.add.zip](https://github.com/eclipse/sumo/files/9414345/e2.add.zip)
.

**Comment by namdre** [comment]
One of your detectors occurs in both additional files. Remove either one.

**Comment by thinker310** [comment]
OK, thank you very much! I got it!
