### ISSUE TITLE
Create polygons from edited network

### ISSUE THREAD

**Issue by erev-84** [eclipse/sumo#11425]
Hello

As can be seen from the screenshot below some of the rods imported with their full length by osmWebWizard.py

![image](https://user-images.githubusercontent.com/82845085/186493275-8510eb38-d3d9-4ab1-9553-af03593c8ca6.png)

and for to fix this issue as can be seen from the screenshot below and as suggested in issue #11354 I edited the network by split edge & delete edge methods 

![image](https://user-images.githubusercontent.com/82845085/186493824-f926ae55-fd5f-40c1-86ac-a136fb3f67c3.png)

However, since my ".osm" file is not an edited version of the network, there is a sizing problem when I try to create a polygon using the following command with the osm file created by the osmwebwizard.py script.

`polyconvert --net-file osm.net.xml --osm-files osm_bbox.osm --type-file osmPolyconvert.typ.xml -o osm.poly.xml`

![image](https://user-images.githubusercontent.com/82845085/186495993-99d8cf6a-9474-4157-8e0d-d1f0ec6b655f.png)

Is there have any way to convert net.xml file to ".osm" file to create polygons. ( I can not get the osm file from the openstreetmap because as in the first screenshot it takes some of the roads with their full length and for this reason I want to generate osm file from the edited network) or is there have any other way to generate polgon file for the edited network?

If there is another way, what is the command I should try? You can check the names of files from the screenshot below

![image](https://user-images.githubusercontent.com/82845085/186498504-b8720ff5-9756-4c0a-97f3-d4f95e37f55c.png)

Thanks in advance

**Comment by namdre** [comment]
You can use polyconvert options `--prune.in-net` and `--prune.in-net.offsets` to filter out some polygons.
Also, take a look at https://wiki.openstreetmap.org/wiki/Osmfilter

**Comment by erev-84** [comment]
Hello 

I encountered the following warning, how can I fix it?

![image](https://user-images.githubusercontent.com/82845085/186726000-1bf271b9-1c66-4b21-870a-0ab54155c5f0.png)

Polygons still looks like below. (Not in correct size and at back layer)

![image](https://user-images.githubusercontent.com/82845085/186726293-815fba5b-1163-4e5b-aa22-0b2065f2fd01.png)

[Network_Files.zip](https://github.com/eclipse/sumo/files/9426835/Network_Files.zip)

**Comment by namdre** [comment]
You can either leave out option **--prune.in-net.offsets** or call it with 4 values such as **--prune.in-net.offsets a,b,c,d**.
However, since you are using a satellite background that covers most polygons, you might simply want to refrain from loading any polygons.
