### ISSUE TITLE
add a dedicated guiShape for taxis

### ISSUE THREAD

**Issue by angelobanse** [eclipse/sumo#11424]
To easily distinguish them from the default passenger class.

https://github.com/eclipse/sumo/blob/5426fe0ba58b2df17850e0b8538ef80bdd20f33c/src/utils/common/SUMOVehicleClass.cpp#L87

**Comment by namdre** [comment]
this could be handled similar to the police shape where the actual shape is almost the same (only add a taxi-sign on top) but the main difference is in the default coloring (in `GUIBaseVehicle::setFunctionalColor`)
