### ISSUE TITLE
include original ids of edges in joined junctions

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#11428]
similar to the original ids in merged edges the information should be still available if original ids are enabled

**Comment by palvarezlopez** [comment]
@behrisch Could be usefull to give the list of all original edges as parameters? (for example: "<param key="originalIDs" value="Edge1, Edge2, ...." />"

**Comment by behrisch** [comment]
Yes. I would probably use the same format as for the lanes: `<param key="origId" value="e1 e2 e3"/>`

**Comment by behrisch** [comment]
two params for edges and nodes would be even better:

- `origId` for the nodes
- `origEdgeIds` for the edges
