### ISSUE TITLE
Define the maximum length of a platoon ( number of cars in a platoon) with Simpla

### ISSUE THREAD

**Issue by TrinhTuanHung2021** [eclipse/sumo#11426]
Add your issue description here.

Hello
I am very grateful to you for sharing the materials. 

![image](https://user-images.githubusercontent.com/82990411/186592576-2c40e96f-e27b-40e0-986d-950edd9a6a81.png)

I used the Simpla module to create platoons at a signalized intersection. But I want to set the length of platoons ( the number of cars in a platoon). In my model, it is too long. So is there any way to set a fixed length for platoons?
I tried to modify parameters in `simpla.cfg.xml` but it is not correct

Thank you very much

*If possible, upload an example that shows your problem.*

**SUMO-version:**  1.14

**operating system:** Win 10

**Comment by m-kro** [comment]
As you noticed yourself, this is not possible currently but seems a valid feature to implement. Shouldn't take too long to do so. You'll be notified on this thread when is has been done.

**Comment by m-kro** [comment]
@TrinhTuanHung2021 Please feel free to test the feature. Just add a tag 
`<maxVehicles value="[YourMaxSize]"/>` to your simpla config file. The default maximum length amounts to ten vehicles.

**Comment by TrinhTuanHung2021** [comment]
> @TrinhTuanHung2021 Please feel free to test the feature. Just add a tag `<maxVehicles value="[YourMaxSize]"/>` to your simpla config file. The default maximum length amounts to ten vehicles.

Hello
I followed your instructions
![image](https://user-images.githubusercontent.com/82990411/216234664-965b1322-e77a-411c-a0d6-4e1236bd8047.png)

but it did not affect my model.
![image](https://user-images.githubusercontent.com/82990411/216234898-ea724acb-ef4c-487a-bc40-f193776af6bd.png)

**Comment by m-kro** [comment]
Did you update to the current developer version (in this case it is enough to update the folder tools/simpla)? Sorry that I took it as given in the earlier post...

**Comment by TrinhTuanHung2021** [comment]
> Did you update to the current developer version (in this case it is enough to update the folder tools/simpla)? Sorry that I took it as given in the earlier post...

Thank you for your quick reply. I added `<maxVehicles value="2"/>` in simpla config file and run my model in Sumo version 1.15.0. But the platoon configuration is the same as before

**Comment by m-kro** [comment]
Then you'll have to update SUMO. If you just want to try out the changes in simpla, the quickest option would be to download the changed [simpla files](https://github.com/eclipse/sumo/tree/main/tools/simpla) from github and patch the corresponding folder in your installation.
Other options: 

- download/clone the github repo and build the developer version yourself or 
- wait until our servers run again and download the compiled developer version for Windows
- wait until the next release (within a few days, depending on the server issue)
