### ISSUE TITLE
two objects meet and dangle at intersection on bidi-edges

### ISSUE THREAD

**Issue by yunpangfloetteroed** [eclipse/sumo#11436]
Add your issue description here.

Shuttle, bike and pedestrian meet each other at intersection connected with bidi-edges. After pedestrian has left the intersection, the shuttle try to cross the intersection, where a bike also waits on the opposite side (breakpoint: 520 s). It looks like that there is no enough space for passing through. So, both objects dangle there. 

Is it perhaps because that latAlignment="right" does not work at bidi-edge?

Is this issue also related to #11421?

**SUMO-version:**

**operating system:**
Windows

[dangleAtIntersectionWithBidi.zip](https://github.com/eclipse/sumo/files/9426527/dangleAtIntersectionWithBidi.zip)

**Comment by yunpangfloetteroed** [comment]
Moreover, the shuttle has higher priority than the bike in this case. should it not be the other way around?

one thought: bike should be able to adjust its lateral position while standing in order to provide enough space for object(s) with priority.

**Comment by namdre** [comment]
also affected by #12580
