### ISSUE TITLE
how to find the origin of this file?

### ISSUE THREAD

**Issue by sonya921** [eclipse/sumo#11437]
Hello，I find a file that can help me switch vehicles between SUMO and VTD, called translateVehTypes.py. 
I would like to know whether there is a document for converting pedestrians,and how to find it?

the partial contents of translateVehTypes.py as follow: 
#!/usr/bin/env python
"""
@file    translateVehTypes.py
@author  Daniel Krajzewicz
@date    27.03.2013
@version $Id$

SUMO, Simulation of Urban MObility; see http://sumo.sourceforge.net/
Copyright (C) 2008-2012 DLR (http://www.dlr.de/) and contributors
All rights reserved
"""

**Comment by namdre** [comment]
Where did you find that file and can you attach it (zipped)?

**Comment by behrisch** [comment]
also maybe @dkrajzew can help here

**Comment by behrisch** [comment]
closing for lack of feedback, please add a comment if you can share more info
