### ISSUE TITLE
How to remove TLS

### ISSUE THREAD

**Issue by erev-84** [eclipse/sumo#11446]
Hello,

Is there a way to completely remove the traffic lights marked in the screenshot below? If so, I would be very grateful if you could describe how I can remove them. 

![image](https://user-images.githubusercontent.com/82845085/186991438-96550e0f-2aff-4170-95f5-2eaab3002d52.png)
![image](https://user-images.githubusercontent.com/82845085/186986271-742421db-0d24-4fc4-bfe2-8172804af8cc.png)
![image](https://user-images.githubusercontent.com/82845085/186986139-b2f79aba-1107-48d4-a1cc-2f9013433578.png)

[Gönyeli2.zip](https://github.com/eclipse/sumo/files/9436335/Gonyeli2.zip)

**Comment by namdre** [comment]
set connection attribute 'uncontrolled' true: https://sumo.dlr.de/docs/Netedit/neteditUsageExamples.html#setting_connection_attributes

**Comment by erev-84** [comment]
Hello @namdre , 

Thank you, It's worked. 

I want to ask one more thing Is there have any way to combine(join) two or more TLS in one TLS. In other words is it possible to add id="Cluster_J12_J6_J7_J9" to id="JoinedS_0" ? If it's possible, How can i do that? I tried to change the type of  id="Cluster_J12_J6_J7_J9" to actuated to make it same with id="JoinedS_0" but not worked I mean they did not connected/combined.

![image](https://user-images.githubusercontent.com/82845085/187050102-6b33503b-b8bc-416a-bc1a-538600177b99.jpeg)

**Comment by namdre** [comment]
see also https://sumo.dlr.de/docs/Netedit/neteditUsageExamples.html#creating_joined_traffic_lights

**Comment by namdre** [comment]
https://sumo.dlr.de/docs/Netedit/neteditUsageExamples.html#creating_joined_traffic_lights

Am So., 28. Aug. 2022 um 00:39 Uhr schrieb erev-84 ***@***.***
