### ISSUE TITLE
scale parameter applies unevenly to flows

### ISSUE THREAD

**Issue by patmalcolm91** [eclipse/sumo#11441]
If I define several vehicle flows with equal begin, end, and number attributes and then use the ``--scale`` parameter to scale the demand, each flow is scaled differently. This also depends on the order in which the flows are defined in the ``rou.xml`` file. For example, if I have four flows and set the scale to 0.5, the first and third flows will have nearly their full demand, whereas the second and fourth flows will have nearly no demand.

Unscaled:
![unscaled](https://user-images.githubusercontent.com/13092577/186884106-ba896936-716d-459b-8f69-e60a64a07817.png)

Scaled:
![scaled](https://user-images.githubusercontent.com/13092577/186884130-32d11735-7ab7-4bf7-835b-956e08e65d47.png)

Here is a minimal example of a configuration that generates the above behavior.
[sumo scale bug.zip](https://github.com/eclipse/sumo/files/9432334/sumo.scale.bug.zip)

**SUMO-version: 1.14.1**

**operating system: Windows**

**Comment by m-kro** [comment]
Reproduced the problem with multiple scale values < 1. The outcome varies quite with the scale value: {0,5; 0,25; 0,1, ...} will insert only certain flows, choosing scale = 0,089 however doesn't seem too bad.

**Comment by m-kro** [comment]
For scale < 0, vehicles are dropped in the flow definition order. Current implementation leads to dropping flows with odd index for scale 1/n (where n is even).

**Comment by patmalcolm91** [comment]
I can confirm that this resolves the issue. Thanks for the fast response!
