### ISSUE TITLE
How to Combine Traffic Lights

### ISSUE THREAD

**Issue by erev-84** [eclipse/sumo#11449]
Hello,

Is there have any way to combine(join) two or more TLS in one TLS. 
In other words is it possible to add id="Cluster_J12_J6_J7_J9" to id="JoinedS_0" ? If possible, How can i do that? I tried to change the type of id="Cluster_J12_J6_J7_J9" to actuated to make it same as id="JoinedS_0" but not worked I mean they did not connected/combined.

![image](https://user-images.githubusercontent.com/82845085/187050622-a19b4fcb-3e4c-409d-b474-139b3ac82061.jpeg)

**Comment by namdre** [comment]
https://sumo.dlr.de/docs/Netedit/neteditUsageExamples.html#creating_joined_traffic_lights

**Comment by erev-84** [comment]
Thank you very much
