### ISSUE TITLE
Vehicle driving problem during simulation

### ISSUE THREAD

**Issue by 9873-kun** [eclipse/sumo#11447]
Vehicles always drive in the right lane, even if the left lane is relatively free. (Freeway simulation)

![2ABV BQGX5 M$3NX_9H(LNJ](https://user-images.githubusercontent.com/83941823/187008124-77e68f64-263b-47da-8ee6-9ac054cc4aed.jpg)

**SUMO-version: 1.14.1**

**operating system: WIN10**

**Comment by namdre** [comment]
This is most likely for *strategic* reasons: i.e. vehicles stay on the right because they need to take the next exit (which I suspect to be south of the shown location).
If you expect more vehicles to drive on the left, make sure to have enough routes that can continue on the other lanes.
