### ISSUE TITLE
Implement automated mapping between topological and logical edges (trac #1146)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#1146]
A topological edge is one that is relevant for routing (i.e. network topology). A topological eddge may be split into multiple logical edges to encode attribute changes such as speed limit or number of lanes. Currently, routes are expressed in terms of logical edges. This means, whenever an edge is split (i.e. to add turning lanes in front of a junction) all routes using that edge must be updated to use the new logical edge IDs.

A mapping between topological edges and logical edges should be built during network loading based on the names of logical edges (i.e. edge foo maps to logical edges foo.0, and foo.23). This would allow an automated interpretation of routes expressed in terms of topological edges (foo bar) instead of having to update to (foo.0 foo.23 bar).

Applications which write routes should express them in terms of topological edges by default.

Migrated from http://sumo.dlr.de/ticket/1146
```json
{
    "status": "new", 
    "changetime": "2014-05-26T07:48:33Z", 
    "description": "A topological edge is one that is relevant for routing (i.e. network topology). A topological eddge may be split into multiple logical edges to encode attribute changes such as speed limit or number of lanes. Currently, routes are expressed in terms of logical edges. This means, whenever an edge is split (i.e. to add turning lanes in front of a junction) all routes using that edge must be updated to use the new logical edge IDs.\n\nA mapping between topological edges and logical edges should be built during network loading based on the names of logical edges (i.e. edge foo maps to logical edges foo.0, and foo.23). This would allow an automated interpretation of routes expressed in terms of topological edges (foo bar) instead of having to update to (foo.0 foo.23 bar).\n\nApplications which write routes should express them in terms of topological edges by default.", 
    "reporter": "namdre", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1401090513866608", 
    "component": "other (also unclassified)", 
    "summary": "Implement automated mapping between topological and logical edges", 
    "priority": "major", 
    "keywords": "", 
    "time": "2014-02-14T07:21:23Z", 
    "milestone": "2.0.0", 
    "owner": "", 
    "type": "enhancement"
}
```

**Comment by namdre** [comment]
The new solution is to load the routes/vehicles in netedit before splitting the edge and then saving the updated routes.

closing as wont-fix
