### ISSUE TITLE
Traci4Matlab 

### ISSUE THREAD

**Issue by erev-84** [eclipse/sumo#11469]
Hello,

Hello, I want to retrieval the following values from E2 detectors using Traci4Matlab. Which functions do I need to use to retrival the following values?

- The number of vehicles in the frequency range I set when creating the detector in Netedit.
- Types of Vehicles (Motorcyle, Passenger, Bus etc...)  in the frequency range I set when creating the detector in Netedit.
- Mean Waiting time in the frequency range I set when creating the detector in Netedit.

According to my research, I have to use getLastStepVehicleNumber(self, detID), for the retrival of number of vehicles and   getLastStepVehicleIDs(self, detID) for the type of vehicle but I am not sure and I would appreciate it if you correct me if I am wrong. One more thing, for the retrival of mean waiting time I couldn't find any function, which function do I need to use to get the mean waiting time ?

Also, will the functions I mentioned above give the values in the specified frequency range? In other words, if I set the detector's frequency to 300 in Netedit, will the functions I mentioned above give the values of 300 time step? 

Finally, What values will the functions (getLastStepVehicleIDs & mean waiting time) return/give from the example below?

![E571C6F6-A991-4873-B1AF-1AFEBBA59679](https://user-images.githubusercontent.com/82845085/187250398-e6a57e4f-9249-4944-b0c5-f7d97d0df615.jpeg)

**Comment by erev-84** [comment]
One more question, Is there have any way to retrieve the quantity of each vehicle type with Traci4Matlab. In other words, I want to retrieve the quantity of each of the vehicle type which pass on the detectors and which function do I need to use for that?

**Comment by namdre** [comment]
- E2 (and E1) detectors do not (yet) support retrieval of aggregated data. All the methods only reflect the current state of the detector. The E3 detector already does support retrieval of aggregated data though.
- To retrieve the vehicle types, Either use vehicle.getTypeID(vehID) or define multiple detectors that filter out by type (detector attribute `vTypes`).

**Comment by erev-84** [comment]
Hello @namdre ,

First of all thank you very much for reply 

I am so sorry but I don't understand exactly what you mean? As far as I know, aggregated data is a process in which data is collected and expressed in a summary form. I couldn't figure out exactly what I can't do with E2 Detector. Which part I mentioned in my message above can't be done with the E2 detector? 

Also, which function should I use for mean waiting time? 

Finally, if you examine the E2 detector output that can be seen in the screenshot above, What values will the functions (getLastStepVehicleNumber(id)  & mean waiting time) return?

**Comment by erev-84** [comment]
- To retrieve the vehicle types, Either use vehicle.getTypeID(vehID) or define multiple detectors that filter out by type (detector attribute `vTypes`).

I want to retrieve not only the vehicle types, but also the number of vehicles of that type on the detector. How can I achieve this?

**Comment by namdre** [comment]
retrieve all vehicles individually, then the type for each vehicle, then count the number of occurrences per type.
