### ISSUE TITLE
emergency braking at lane-width change

### ISSUE THREAD

**Issue by yunpangfloetteroed** [eclipse/sumo#11467]
as title. The network is generated from OSM. 
It happens when the sublane model is used. 

**SUMO-version:**
v1_14_1+0619-59d86945e0a
**operating system:**
Windows

**Comment by yunpangfloetteroed** [comment]
After observing several similiar cases it looks like that bikes tend to accelerate in front of the respective intersections with walking areas, then make emergency braking when making a turn. The corresponding turning movement within the intersection/walking area is quite jagged.

**Comment by namdre** [comment]
it's the same situation as #11468

**Comment by yunpangfloetteroed** [comment]
New case with the same situation
[BikeEmbergencyBraking2.zip](https://github.com/eclipse/sumo/files/9453436/BikeEmbergencyBraking2.zip)

**Comment by namdre** [comment]
@yunpangfloetteroed the speedRestrictions file is missing

**Comment by yunpangfloetteroed** [comment]
sorry, You find attached the complete files! 

[BikeEmbergencyBraking2.zip](https://github.com/eclipse/sumo/files/9454359/BikeEmbergencyBraking2.zip)

**Comment by namdre** [comment]
the second kind of emergency braking is model-specif related (#11498)
