### ISSUE TITLE
Fly Movement in SUMO 3D View for Windows OS (Linux still pending)

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#11473]
Similar to a FPS: First-person shooter Movement (https://en.wikipedia.org/wiki/First-person_shooter) or a flight simulator

Controls: WASD oder arrows + mouse

Fly movement starts if mouse right click is pressed within the view.

more Info: https://learnopengl.com/Getting-started/Camera

**Comment by namdre** [comment]
I don't think that 'right click' is a good choice because it's already used for zooming and for the context menu.
However, I do agree that alternate view controls would be nice.

Here are my key suggestions
- us arrow keys to move / strafe (like WASD),  
   - keys a,s,d are already used as simulation control shortcuts
   - arrow keys currently serve no function in osg view
- use a key to toggle fly mode (ctrl + x) ?
  - all mouse movements translate directly to view rotation centered on the camera (no need to hold down a mouse button)

**Comment by palvarezlopez** [comment]
Q and E can be used for Rolling camera

**Comment by namdre** [comment]
ctrl+f is already used to toggle fullscreen. How about control + L ( *look around*)

**Comment by palvarezlopez** [comment]
I mean only F, without ctrl

**Comment by m-kro** [comment]
Well in principle OSG supplies a camera manipulator which can be used with few key handling code to allow translating the view by key. It even seems to care about animating the movement. But the arrow keys are used for shifting the focus between FOX GUI elements, so after a few times the button shifts the focus out of the 3D view!

**Comment by namdre** [comment]
Not necessarily! In the 2D view, the arrow-key events are capture and translated into a panning movement of the view.

**Comment by m-kro** [comment]
Still needs some fine tuning but in general I got it to work. Should this be an alternative to the current navigation in OSG or replace it?

**Comment by namdre** [comment]
since 'Flight Mode' translates all mouse movements into camera movements this might make it awkward to interact with objects. Hence I would turns this into a toggle (i.e. by pressing the **f**-key)

**Comment by m-kro** [comment]
@palvarezlopez  @namdre Now you can try the new OSG navigation...

**Comment by m-kro** [comment]
@namdre : There already was some preliminary feedback in the debug version which now has been enhanced and made available also in release. Jumps should be much smaller as big angles are dismissed. The big remaining problem is that the OS API call to set the cursor does not seem to take effect.

**Comment by namdre** [comment]
The cursor stays roughly in the center but view rotation is now so sluggish on my system as to be almost unusable.

**Comment by m-kro** [comment]
@namdre I tried with an Ubuntu VM and didn't notice any cursor centering. However the cursor would move upward whether it is reset by the program using a XWarpPointer call or not (and when the mouse is at stand-still).

**Comment by m-kro** [comment]
@namdre I won't be able to fix the Linux issue for the upcoming release because I don't have access to a real Linux system at the moment. Should I then deactivate the "fly mode" and hide the HUD text until this is fixed?

**Comment by m-kro** [comment]
Linux problems continue in #12503
