### ISSUE TITLE
Refactor MFXLCDLabel and add ToolTip

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#11476]
~~Current implementation causes the glitch https://github.com/eclipse/sumo/issues/11278~~

The cause of #11278 is not the MFXLCDLabel  :( But I'm going to use this ticket for add a custom tooltip

**Comment by namdre** [comment]
Arguably, the new tooltip code is causing the glitch because the MFXLCDLabel has been working fine for many years :grin:
