### ISSUE TITLE
Collision between objects on bidi-edge

### ISSUE THREAD

**Issue by yunpangfloetteroed** [eclipse/sumo#11477]
Add your issue description here.
collision between 2 bikes

**SUMO-version:**
v1_14_1+0619-59d86945e0a
**operating system:**
Windows

**Comment by yunpangfloetteroed** [comment]
Another case is found. It is not able to extract the corresponding small network. So, the orginal network and files are put under S:\Sumo\Bugreports\11477_collisonOnBidi2: 
 - collision between a bike and a shuttle 
 - involved objects: Easymiles.0, bike67, bike32; 
 - junction_id: 3792727043;
 - teleporting time: 724.40 s
 - many emergency brakings by bike67

**Comment by yunpangfloetteroed** [comment]
Another collision case in the aforementioned network 
Warning: Vehicle 'bike133' collision with person 'ped195', lane='25829749#2_0', gap=-1.48, time=1397.40, stage=move.

**Comment by yunpangfloetteroed** [comment]
Another case is found between two bikes on a bidi-edge when making a right turn. In the extracted network, only emergency braking can be reproduced, but, this causes a collision in a big scenario. 

The bike behaviour in the extracted network is similar to that in the big scenario:  one bike makes a weird right turn (has difficulty to make right turn). The other approaching bike has to make a emergency braking.

**Comment by namdre** [comment]
The latest test is unrelated to bidi and was therefore moved to a different folder with a simplified network (still showing the same wierd behavior and emergency braking). See #11639
