### ISSUE TITLE
Traci4Matlab Value Retrieval

### ISSUE THREAD

**Issue by erev-84** [eclipse/sumo#11470]
Hello,

I want to control the green light duration of the traffic lights with the Matlab/ANFIS method, and for this, I want to retrieve the vehicle types, their quantities and the average waiting time of the vehicles, as soon as the yellow light of traffic light turns on before it comes to the traffic light where the values will be retrieved. In other words, I do not want to retrieve the values within a certain period of time I just want to retrieve the values once when the yellow light of the previous step traffic light turns on. Is such a thing possible and I would be glad if you can you give me more detail about how I can achieve such a thing?

**Comment by namdre** [comment]
see `lane.getLastStepVehicleIDs`, `vehicle.getTypeID`, `vehicle.getWaitingTime`

**Comment by erev-84** [comment]
Hello @namdre ,

I guess I couldn't explain to you exactly what I wanted to achieve, I'm very sorry for that. As you can see in the screenshot below, I want to retrieve the datas/values from the detectors in Road 1 only once when Road 2 turns yellow. How can I do that such a thing?

![image](https://user-images.githubusercontent.com/82845085/187421790-ad30aa15-407b-4ed5-b33e-38eb88a236a4.jpeg)

**Comment by namdre** [comment]
lookup the documentation for the following traci methods:
`laneare.getLastStepVehicleIDs, vehicle.getTypeID, vehicle.getWaitingTime, `trafficlight.getPhase`

1. Monitor the traffic light for the relevant phase change, 
2. retrieve the vehicle ids
3. do your own aggregation of waitingTimes and types

**Comment by erev-84** [comment]
But as far as I understand, `vehicle.getTypeID` Returns the IDs of the vehicle types in the whole simulation but I just want to retrieve the vehicle types which on the area of the detector, How can I do that? Also, as I mentioned in issue #11469 

> * To retrieve the vehicle types, Either use vehicle.getTypeID(vehID) or define multiple detectors that filter out by type (detector attribute `vTypes`).

I want to retrieve not only the vehicle types, but also the number of vehicles of that type on the detector. How can I achieve this?

**Comment by namdre** [comment]
> But as far as I understand, vehicle.getTypeID Returns the IDs of the vehicle types in the whole simulation

No. compare
https://sumo.dlr.de/pydoc/traci._vehicle.html#VehicleDomain-getTypeID
https://sumo.dlr.de/pydoc/traci._vehicletype.html#VehicleTypeDomain-getIDList

> I want to retrieve not only the vehicle types, but also the number of vehicles of that type on the detector. How can I achieve this?

retrieve the type for each vehicle individually and count

**Comment by namdre** [comment]
You could hard-code the associations between traffic lights and E2 ids or compute them at runTime based on network topology (and looking up the laneIDs of all E2 detectors (`lanearea.getLaneID`)

**Comment by erev-84** [comment]
Hello @namdre ,

Could you show me an example please? or could you give me little bit more detail please?

**Comment by erev-84** [comment]
Hello @namdre again,

Instead of using vehicle.getTypeID, can I use getLastStepVehicleIDs(self, detID)? By this way, I think i can specify from which detector I want to retrieve type data? If getLastStepVehicleIDs(self, detID) function not suitable for this approach, could you give me an example about how can I determine from which E2 detector the values should be retrieved with vehicle.getTypeID(vehID) function?

**Comment by erev-84** [comment]
Hello @namdre again,

Could you please show me an example or help with the python code? so I can better understand how to do it and accomplish what I'm trying to do with Traci4Matlab.

As far as I understand, I can retrieve the IDs of all vehicles on the detector with the traci.lanearea.getLastStepVehicleIDs(ID_of_the_detector) function, but I did not understand how to retrieve the vehicle types from the IDs of the vehicles with the vehicle.getTypeID function. Also, another thing I did not understand is how to count each vehicle type separately.

I would be very grateful if you could help me by showing an example

Thanks in advance

**Comment by namdre** [comment]
```
from collections import defaultdict
typeCount = defaultdict(lambda : 0)
for vehID in traci.lanearea.getLastStepVehicleIDs(ID_of_the_detector):
   typeCount[traci.vehicle.getTypeID(vehID)] += 1
```
Please find a local programmer to guide you for further general programming questions: https://sumo.dlr.de/docs/FAQ.html#i_want_to_do_a_project_with_sumo_can_you_help_me_with_the_implementation
