### ISSUE TITLE
Adding Traffic Light Program as additional-file

### ISSUE THREAD

**Issue by erev-84** [eclipse/sumo#11489]
I want to control the traffic lights with Traci4Matlab, but all phases are listed under the same  (tlLogic id &  programID) as seen below and I can not find a way to switch between phases

![image](https://user-images.githubusercontent.com/82845085/187790900-5b00ab10-98f0-48fe-a51f-dd47b9f8aaf5.png)

As in the screenshot below, would it be correct if I define the programID separately for each phase and use that programID via traci for the phase I want to change?

![image](https://user-images.githubusercontent.com/82845085/187791266-72c228ee-fa2e-4b1a-8301-acb847cd60a8.png)

one more thing, I created a separate .xml file with traffic program (Traffic_Light_Program.tls.xml) as seen above and as mentioned on pages 16 and 17 of the document at [http://cse.iitkgp.ac.in/~soumya/micro/t2-7.pdf](http://cse.iitkgp.ac.in/~soumya/micro/t2-7.pdf?fbclid=IwAR3YfBKDFmfJN3GIp3p8O4aG-5cPjX19mKV5jX1lHFnDEwBOq2igsBw8kF8), deleted the tls program from network file and added the Traffic_Light_Program.tls.xml file I created to the .sumocfg file as an additional-file as seen below. 

![image](https://user-images.githubusercontent.com/82845085/187791423-6e0355f2-0ed1-4359-9084-d3d23b11ed04.png)

However, unfortunately, when I run sumo-gui, I am getting error and the simulation does not run. Is it not possible to save the traffic program as a separate .xml file and save it as an additional file in Sumocfg?

[Conventional_Matlab.zip](https://github.com/eclipse/sumo/files/9465425/Conventional_Matlab.zip)

**Comment by m-kro** [comment]
Change phase with `traci.trafficlight.setPhase` (see [docs ](https://sumo.dlr.de/docs/TraCI/Change_Traffic_Lights_State.html)/ [python interface](https://sumo.dlr.de/pydoc/traci._trafficlight.html#TrafficLightDomain-setPhase)).

Probably you edited the net file and removed the standard TLS program for J1. Don't do that! It will work if you recreate it.

**Comment by m-kro** [comment]
No, it is not a good strategy if your goal is just to have multiple phases (which should be the norm). Phases can be accessed based on their index resulting from the definition: first phase element inside a tlLogic has value 0, the second 1 and so on.

Docs: [Loading a new program](https://sumo.dlr.de/docs/Simulation/Traffic_Lights.html#loading_a_new_program)

**Comment by erev-84** [comment]
Hello @m-kro ,

First of all thank you for the reply.

I have one more question, I'm working on controlling the duration of traffic lights with Traci4Matlab but I can't decide whether to use setPhase or setRedYellowGreenState to switch to another phase. There is a duration for each phase in my tls program in the .net.xml file and if I use the SetPhase function, will it use the duration there, or can I still control/change the duration with setPhaseDuration. In other words If I use the SetPhase function, do I have to use the duration that is in the program which is located in .net.xml file? Also, could you please tell me the difference between SetPhase & setRedYellowGreenState functions and their usage differences?

**Comment by namdre** [comment]
https://sumo.dlr.de/docs/Simulation/Traffic_Lights.html#controlling_traffic_lights_via_traci

**Comment by erev-84** [comment]
> https://sumo.dlr.de/docs/Simulation/Traffic_Lights.html#controlling_traffic_lights_via_traci

Hello @namdre ,

I don't have any missing green phase but I am getting the error below. What is the reason of this errors?

![image](https://user-images.githubusercontent.com/82845085/188219638-39afc6d7-7809-4bd3-b5f6-8042148a421d.png)

![image](https://user-images.githubusercontent.com/82845085/188219738-56d8a690-a88d-4de8-b64f-baa4b086e782.png)

![image](https://user-images.githubusercontent.com/82845085/188219797-657d29ac-8899-4f2b-8149-927a4a5e1a69.png)

Thanks in advance

**Comment by namdre** [comment]
while each program has some green in it, each program has some indices that never get the green light.The default style of sumo programs is to have one big cycle where every index gets a green light in some phase, hence this triggers the warning. by default sumo does not switch between programs so it will not take into account your multi-program style when giving this warning.
