### ISSUE TITLE
vehicle generation problem

### ISSUE THREAD

**Issue by MarMar-s** [eclipse/sumo#11480]
Hello,
I have 2 origin nodes in my network which are connected to two different edges of 4 lanes and during a two hour simulation about 16000 vehicles should enter the network from node 1 and 10000 vehicles should enter the network from node 2. The departure time of all vehicles is randomly assigned with a uniform distribution and all vehicles are of the same type and there is no congestion in the network. When I run the simulation, all the vehicles from node 1 can enter the network during these two hours, but only about 4000 vehicles from node 2 can enter the network and I can't understand the reason. I would be very grateful if you could help me to solve this problem.
Thank you very much in advance.

**Comment by namdre** [comment]
check for delayed insertion: 
https://sumo.dlr.de/docs/Simulation/VehicleInsertion.html#investigating_insertion_delay
https://sumo.dlr.de/docs/Simulation/VehicleInsertion.html#forcing_insertion_avoiding_depart_delay

**Comment by MarMar-s** [comment]
Thank you so much for the answer
