### ISSUE TITLE
ped runs to bike on bidi

### ISSUE THREAD

**Issue by yunpangfloetteroed** [eclipse/sumo#11483]
Add your issue description here.
as title; moreover, it looks like that there is a collision between them, but no warning is generated.

**SUMO-version:**
v1_14_1+0698-6b8d6bc7318
**operating system:**
Windows

**Comment by yunpangfloetteroed** [comment]
another case is attached. 
[pedRunToBike2.zip](https://github.com/eclipse/sumo/files/9476774/pedRunToBike2.zip)

In both cases, bikes keep accelerating although they are approching the peds. No warinings are reported by sumo.

**Comment by namdre** [comment]
The second test fails because there is no look-ahead for pedestrians beyond the current lane.

**Comment by yunpangfloetteroed** [comment]
It would be more logical and realistic if pedestrians can be able to look ahead, especially when links are short.  Is there any plan to extend this part in the pedestrian model?

**Comment by namdre** [comment]
There is a misunderstanding here. The pedestrians do have some lookahead. It's the vehicles that do not have look-ahead for pedestrians beyond the current edge. And yes, there is a plan to fix this, hence I'm leaving this ticket open.
