### ISSUE TITLE
add gui-settings screenshot on sumo.dlr.de

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#11493]
An image that shows an opened gui-settings dialog and the view with "fancy" settings and labels.

**Comment by namdre** [comment]
![fancy_settings](https://user-images.githubusercontent.com/6240630/187870467-0a04a31b-95f0-4ca2-925b-9a1f2e6ae145.png)

**Comment by namdre** [comment]
another image for the image rotation.

**Comment by angelobanse** [comment]
Closed in https://github.com/eclipse/sumo.website/commit/d9f3d0271f1e0a446e066d7fd8067b7935dc857f

**Comment by namdre** [comment]
how long should it take for the new image to show up?

**Comment by angelobanse** [comment]
It can take up to 20 min, but i can see it now (i put it on 4th place on the slider)

**Comment by angelobanse** [comment]
And btw, i recreated your image, to get the aspect ratio used in the other screenshots.
