### ISSUE TITLE
Where to check the track principle of the vehicle at the intersection

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#11520]
**SUMO trajectory**

How is SUMO trajectory planning implemented?
How do I modify the SUMO trajectory?

**Comment by namdre** [comment]
- longitudinal behavior (speed) comes from the choice and configuration of the `carFollowModel` (https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#car-following_models)
- intersection behavior comes from junction model parameters (https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#junction_model_parameters)
https://sumo.dlr.de/docs/Developer/Implementation_Notes/Simulation_Loop.html
- lane changing behavior has other models and parameters: https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#lane-changing_models
- and you can override everything with your own code: https://sumo.dlr.de/docs/TraCI.html

here is how it all comes together: https://sumo.dlr.de/docs/Developer/Implementation_Notes/Simulation_Loop.html
