### ISSUE TITLE
Whether the SUMO intersection can be lined twice and whether the road network document has a clearer explanation

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#11521]
**SUMO:**
①Can the intersection be lined twice (to divide the conflict area)? How to do it?
②Is there a clearer explanation about the road network documents（.net.xml）? I still don't understand some parameters after consulting the official documents.

**Comment by namdre** [comment]
1. you can let wait within an intersection at a configurable position (i.e. left turners). See https://sumo.dlr.de/docs/Simulation/Intersections.html#waiting_within_the_intersection
2. it might help if you describe your question in more detail. The documentation is large and I have no way of knowing whether you found the relevant pages yet.
