### ISSUE TITLE
trajectory of SUMO

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#11525]
①Does the SUMO trajectory follow some polylines(the internal edge), or a curve? If it's a curve, how does the trajectory planning work? Do you fit the curve from coordinate points?
②Does the vehicle travel from the center line of the incoming lane to the center line of the outgoing lane? If so, how do I obtain the distance between the midpoint of the incoming lane stop line in each direction and the midpoint of the other outgoing lane stop line?(like the distance between point A and point B)
![QQ图片20220905151949](https://user-images.githubusercontent.com/54823725/188391166-c84f7f73-03e8-44c3-875a-ee22328211e6.png)
Thank you very much!
**SUMO-version:**

**Comment by namdre** [comment]
1. polyline (resolution configurable with netconvert/netedit option **--junctions.internal-link-detail**)
2. the internal lane corresponding to that movement has a length attribute and you can retrieve it with traci and sumolib
