### ISSUE TITLE
Conflict zone division

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#11522]
**SUMO-version:**
Does SUMO have conflict zone demarcation rules and displays for intersections?
I'd like to divide the center of the intersection into a few critical zones to facilitate car reservations，but I have no idea.
Thank you for your answer.

**Comment by namdre** [comment]
SUMO internally calculates conflict points for each pair of conflicting connections but these are not exposed to the user (except by changing the shape of the connecting curves). You could overlay your own polygons over the intersection area and then query for the presence/absence of cars in these areas via TraCI. This relies on you providing your own geometry computation with code running outside SUMO.
