### ISSUE TITLE
Does the vehicle movement in the intersection follow the internal edges?

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#11523]
①Does the vehicle movement in the intersection follow the internal edges?
②Can internal edges be displayed in NetEdit?
③What is the relationship between the connections and the internal edges?
**SUMO-version:**

**Comment by namdre** [comment]
1. yes
2. yes: 
  - go to inspect mode (i)
  - from the edit menu select 'show connections' (alt+6) or use the corresponding button in the top bar
3. each connection corresponds to an internal edge or a sequence of two internal edges (if there is a waiting position within the intersection). In this case, the 'connection' in netedit will show a little orthogonal line to mark the waiting spot.
