### ISSUE TITLE
Trajectory of vehicle movement

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#11536]
①Does traffic move along the internal lanes of the  connection at intersections？
②Are the adjacent points in the shape with the lanes of internal edges fitted by interpolated cubic spline?
Is the vehicle trajectory made up of many curves or many line segments?
③Whether the trajectory fitted by interpolated cubic spline conforms to the kinematics law of the vehicle？
Thank you very much
**SUMO-version:**

**Comment by namdre** [comment]
1. was already answered in the affirmative in #11525  (please continue posting in a ticket if the answer was unclear, even after the ticket has been closed)
2. yes.
3. in some contexts (racing, railways) the curve is rather a clothoid than a cubic bezier spline. However, for most applications the difference is negligible
