### ISSUE TITLE
Semantic representation around the vehicle

### ISSUE THREAD

**Issue by baimukashev** [eclipse/sumo#11538]
Hi,
Is it possible to get the bird's eye view image of the vehicle surroundings with more efficient way than the gui screenshots?

**Comment by namdre** [comment]
you could retrieve the angles and positions of all surrounding cars and then compose your own image (TraCI or fcd-output)
to get the road geometry, see 
- https://sumo.dlr.de/docs/Tools/Sumolib.html#import_a_network_and_retrieve_nodes_and_edges
- https://sumo.dlr.de/docs/Tools/Net.html#net2geojsonpy
