### ISSUE TITLE
Context subscription filters not appearing to work

### ISSUE THREAD

**Issue by DFazekas** [eclipse/sumo#11540]
### Desired scenario:
A stream of civilian vehicles drive from the leftmost edge towards the rightmost edge. At some point, an emergency vehicle (EV) enters the stream. I subscribe to the context of this EV, listening for nearby vehicles. Two filters are applied to the subscription:
1. **LCManeuver** - to control how far ahead and behind the EV to watch.
2. **VType** - to filter out the EV from its own result.

### Bug
The subscription should only have a 4-meter distance, but it's capturing vehicles far beyond this range. Here's the snippet:
```python
traci.vehicle.subscribeContext(ev.id, tc.CMD_GET_VEHICLE_VARIABLE, 4, [tc.VAR_DISTANCE])
```
and here you can see vehicles 10, 11, 8, and 9 are all being captured, yet all far from within range.
<img width="622" alt="image" src="https://user-images.githubusercontent.com/22490250/188538994-20a935f0-d9e8-44ea-8ba3-d72a83b876fc.png">

Additionally, to prevent the EV from appearing in the context subscription results, the following filter was applied to only capture the various types of civilians. And yet, as you can see from the above console output, "ER" is the first result.
```python
traci.vehicle.addSubscriptionFilterVType(['Civilian', 'C_Civilian'])
```

And finally, changing the `downstreamDist` and `upstreamDist` values on the following filter was also expected to impact the range of capturing. As you can see, both are set to 1-meter, and yet I'm capturing far beyond that range.
```python
traci.vehicle.addSubscriptionFilterLCManeuver(downstreamDist=1, upstreamDist=1)
```

I've provided the minimal code necessary to reproduce the bug.
https://gist.github.com/DFazekas/6b14b4ac1c0d5b2c85278b2585b8b852

**SUMO-version:**
1.14.1

**operating system:**
Windows 10

**Comment by behrisch** [comment]
I can confirm the behavior and it seems to be a bug in the LC filter. At least if I remove that one the list of vehicles is empty (excpet for the first step)

**Comment by behrisch** [comment]
OK so there is a small hint in the docs https://sumo.dlr.de/docs/TraCI/Object_Context_Subscription.html#intercompatibility about that but honestly I do not understand why it is done that way but we should discuss this before we change it.

**Comment by DFazekas** [comment]
@namdre, I don't comprehend your commit changes. What can I to change, will filter combinations work or?

**Comment by namdre** [comment]
lcmaneuver and vtype filter will now combine so you don't need to change your code. Simply update SUMO (after the nightly build has updated).

**Comment by DFazekas** [comment]
I believe this behaviour is still broken. Running SUMO version `v1_14_1+1008-de138fee043`.

I'm using the subscriptions/filters to halt vehicles that are too close to the firetruck. In theory, once a civilian vehicle is within-range, it halts until it's out-of-range. As you can see, this works at first, but once the firetruck begins to switch lanes (or stays between lanes), the nearby vehicles are no longer "visible" by the subscription, hence resume driving.

In the attached video, at time 6-seconds, the closest leading vehicles (IDs 8 and 9) are "seen" but not the adjacent vehicle (ID 10). Then at time 7-seconds, when the firetruck begins switching lanes, vehicle-9 is no longer visible. And at time 9-seconds, no vehicle is visible because the firetruck is driving in-between lanes.

https://user-images.githubusercontent.com/22490250/190217130-3497264b-c5f7-4ed6-b0c5-8be9268988fb.mp4
