### ISSUE TITLE
Trajectories of vehicle movements at intersections

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#11549]
①The planning process of vehicle trajectory is roughly: first find a set of points through bezier spline fitting, these points are the shape of the lane of the internal edge? and then connect the points with straight lines, So the trajectory is made up of a bunch of line segments,  am I right?
②if I am right，I need to know what the given points are and what the information is before we use the bezier spline method?
Thank you very much!
**SUMO-version:**

**Comment by namdre** [comment]
Yes, the trajectory is always a sequence of straight lines.
This "planning" takes place before the simulation and is encoded in the network.
The bezier control points are derived by extending the last geometry segment of the incoming lane to an intersection as well as the extension of the first segment of the outgoing lane. The extension distance depends on the size of the intersection.
You can find all the details by looking for the function `computeSmoothShape` in src/netbuild/NBNode
