### ISSUE TITLE
Sumo physical quantities do not represent reality, how to fix it?

### ISSUE THREAD

**Issue by ssooffiiaannee** [eclipse/sumo#11545]
SUMO provides ways to configure the speed, acceleration ...etc of vehicles, but an acceleration that goes from 0 to accel in no time does not represent reality (continuity of physical quantities), is there a way to fix this or to link SUMO to a real physical simulator?

**Comment by namdre** [comment]
see https://sumo.dlr.de/docs/Simulation/Basic_Definition.html#defining_the_integration_method

Also, SUMO is time-discrete which will always give deviations from reality. However, you can reduce the error by increasing the time resolution (i.e. **--step-length 0.1**)

**Comment by ssooffiiaannee** [comment]
Thank you! To be more specific, suppose I have the deceleration values of my vehicle at different time steps, is there a way to include this on sumo?

**Comment by namdre** [comment]
you can call `traci.vehicle.setAcceleration(-decel)` in every step and there is nothing simpler at the moment.

**Comment by ssooffiiaannee** [comment]
I am trying to do it in C++ with the following instruction : 

mobility->getVehicleCommandInterfarce()->setParameter('decel', #number);

I am not sure if this is correct since it is not working. I check the value right after setting it using : mobility->getVehicleCommandInterfarce()->getDeccel() and still doesn't show the updated value.

**Comment by namdre** [comment]
The method `setParameter` is mainly there to set custom user-define parameter rather than to influence the simulation.

The API provided by VEINS is only a subset of all methods provided by SUMO and `setAcceleration` is missing. (maybe @sommer knows somebody who can help here). 

An alternative would be to use the methods `setSpeed` (to set the speed that results from the desired acceleration once per timestep) or `slowDown` (to define a range of constant deceleration by giving a duration and target speed) which are both provided by VEINS.

**Comment by ssooffiiaannee** [comment]
Thank you. I appreciate your help. I may add it myself if I manage to make it work.

**Comment by ssooffiiaannee** [comment]
I encountered another issue while working on this. I am not sure if I GitHubo create another github issue.

I am trying to modify the speed every 0.01s, with the following : 
`setSpeed(mobility->getSpeed() + a * time_step)` // time_step = 1s
Because of the refresh that occurs in OMNet++ every 1 second, the previous instruction is executed every 1s. 
Due to the step length value in sumo.cfg file that is set to 0.01s. I get an overall deceleration of 100 x a lasting 0.01s, (ex: for a = -14.74m/s², I get -1474m/s² lasting 0.01s when I open the deceleration graph in SUMO).

![image](https://user-images.githubusercontent.com/37119086/189656591-937eb54b-e031-4075-8336-cab0b25f5a69.png)

This is not what I wanted to do, I want to change the speed every 0.01s, and omnet++ is running with steps of 1s and cannot be modified.

**Comment by namdre** [comment]
use the `slowDown` command to affect the speed over 1 second.

**Comment by ssooffiiaannee** [comment]
I tried it. The main problem is that those instructions are executed every 1s, and the remaining of the interval it is set to 0m/s²
`slowDown(mobility->getSpeed() + a * 0.5, 0.5);`
Result : 
![image](https://user-images.githubusercontent.com/37119086/189662231-b42fb5bb-beca-48b8-a8b1-ffb5c28da69b.png)
Since

**Comment by namdre** [comment]
The diagram shows constant acceleration for 0.5 seconds. In your command, use 1s instead of 0.5

**Comment by ssooffiiaannee** [comment]
My goal is to update that acceleration every 0.01s.

![image](https://user-images.githubusercontent.com/37119086/189665838-7a0fc1c9-bc86-4e5f-af38-9b6ef49fbbfe.png)

**Comment by namdre** [comment]
Then this is a question you should put to the Veins developers. I'm not sure whether their framework allows giving additional sumo commands in between the 1s omnet commands.

**Comment by ssooffiiaannee** [comment]
Since I already opened that issue on the Veins repo, maybe @sommer can help with this issue.

**Comment by ssooffiiaannee** [comment]
trying to run an example without Veins nor Omnet :  
`traci.vehicle.setAcceleration("v2", a, dt) `
gives an error : 
attributeerror: 'vehicleDomain' object has no attribute 'setAcceleration'

**Comment by namdre** [comment]
this indicats that your version of SUMO is too old. The latest release can be obtained here: https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_release_version_1141

**Comment by sommer** [comment]
> I want to change the speed every 0.01s, and omnet++ is running with steps of 1s and cannot be modified.

How did you determine that it "cannot be modified"? This is what the parameter at https://github.com/sommer/veins/blob/veins-5.2/src/veins/modules/mobility/traci/TraCIScenarioManager.ned#L50 is good for. See, for example, https://github.com/sommer/veins/blob/veins-5.2/examples/veins/omnetpp.ini#L40

**Comment by ssooffiiaannee** [comment]
Thank you both. 
I actually checked that parameter and changed the default value in TraCIScenarioManager.ned, It didn't work, idk why I didn't think of checking the omnetpp.ini, but now it works fine.

**Comment by FADEAWAY114** [comment]
> 这表明您的相扑版本太旧了。最新版本可在此处获得：https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_release_version_1141

When I use the latest version of sumo 1.17.0, I still get this error, how to solve this?
![image](https://github.com/eclipse/sumo/assets/105548396/84eca3d3-e577-4434-84d1-65ca2dc7e1f0)

**Comment by namdre** [comment]
most likely you are still using an outdated traci (client) library
