### ISSUE TITLE
Pedestrian cross at random locations

### ISSUE THREAD

**Issue by prashanth712** [eclipse/sumo#11565]
Is there any possibility of make pedestrians cross road/lanes randomly without zebra crossing at random locations?

**SUMO-version:**
![image](https://user-images.githubusercontent.com/101544573/189347947-c2d639db-f761-4e1a-9cff-5c04bd986fe7.png)

**operating system:**
windows - 10

**Comment by namdre** [comment]
currently not but I plan to add this in a future version. see #8839 for recommended workarounds
