### ISSUE TITLE
Netconvert error: 'No nodes loaded.' What is lacking the 'highway' key?

### ISSUE THREAD

**Issue by osakanatengoku-AS193** [eclipse/sumo#11569]
Add your issue description here.

I am getting the same "no nodes loaded" error as this question.(https://github.com/eclipse/sumo/issues/9391#issue-1035885669)
This page says it is "lacking of the highway key", but what is it?
I can't find anything about it in the sumo documentation.
This may be a rudimentary question, but I am stumped and would appreciate it if you could help me.

*If possible, upload an example that shows your problem.*
Command: netconvert --osm-files osm9_trafficsign.net.xml -o output.net.xml --tls.cycle.time 150 --tls.allred.time 3
Error: No nodes loaded.

**SUMO-version:**
1.11.0

**operating system:**
[osm9_trafficsign.net.zip](https://github.com/eclipse/sumo/files/9540597/osm9_trafficsign.net.zip)

**Comment by osakanatengoku-AS193** [comment]
Is there any way to edit this file so that it can be netconvert?
Also, is there a page that describes the highway key?

**Comment by behrisch** [comment]
The file you posted is a SUMO net not an OSM file. So you used the wrong option (or the wrong file). For feeding a SUMO net into netconvert use `--sumo-net-file` instead of `--osm-files`

**Comment by osakanatengoku-AS193** [comment]
Thank you very much.
It was really an elementary mistake...
The netconvert command worked, but when I open the resulting file, the options are not reflected.
The signal cycle times are still 90 seconds, and the phase where all signals turn red has not been added.
Why is this?
When I run netconvert, all I get is a warning that the connection speed has been reduced due to an angle problem.

**Comment by namdre** [comment]
The tls options such as **--tls.cycle.time** are only applied when building a network that doesn't yet have signal plans computed.
If you wish to recompute all signal plans with a new cycle length this is how to do it:

`netconvert -s old.net.xml -p plain`
`netconvert -e plain.edg.xml -n plain.nod.xml -x plain.con.xml --tls.cycle.time 100`

(The second step retains all the information from the original network except for the signal plans)

**Comment by osakanatengoku-AS193** [comment]
Thank you very much. I have 3 more questions...
① I got an error about "-p".
I used "--plain-output-prefix" and it worked. why?
"Error: On processing option '-p':
 No option with the name 'p' exists."

②I solved the following error by using "--ignore-errors.edge-type". Is there any disadvantage to this in the future?
"Error: 458 total messages of type: Additional lane information could not be set - the edge with id '%s' is not known.
Error: 164 total messages of type: Type '%' used by edge '%' was not defined (ignore with option --ignore-errors.edge-type)"

③Is the similar option "--ignore-errors" an option to ignore errors when sumo-gui is invoked?

**Comment by namdre** [comment]
1) The shortcut option name is only available since version 1.13.0
2) no
3) there is no sumo option **--ignore-errors**. Only **--ignore-route-errors** which is useful to simulate (temporary) blockages but would create undesired jams otherwise.

**Comment by osakanatengoku-AS193** [comment]
I appreciate your help .
