### ISSUE TITLE
trajectory of vehicle at the intersection

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#11561]
①For different types and sizes of vehicles, whether the trajectory at the same intersection is consistent?
②Is a internal lane of edge trajectory fitted by cubic bezier spline with  two bezier control points and two midpoints of the stop line and then in a particular way to find some points(sample from the curve), which are the points of the shape of the inner lane of edge? and then the points obtained by sampling are connected in pairs to obtain the trajectory？Am I right? Please correct me if I understand something wrong.
I still have some questions about the process of trajectory fitting, because I do not understand the source code, so I came to ask you, thank you very much!

**Comment by namdre** [comment]
(1) All cars follow the same polyline regardless of size and type.
(2) yes.
