### ISSUE TITLE
Question about how to set duration of the simulation and generate emission file.

### ISSUE THREAD

**Issue by erev-84** [eclipse/sumo#11568]
I'm trying to control the simulation with traci4matlab and I added the following option to the .sumocfg file to set the duration of the simulation

`<time>
<begin value="0"/> 
<end value="3600"/>
</time>`

Will the simulation use the time/end value found in .sumocfg file or do I need to specify the duration of the simulation with Traci4Matlab?

-----

one more question, I added the following option to the ".sumocfg" file to create emission output file. Since the simulation will be controlled with Traci4Matlab, will the following option added to the ".sumocfg" file be invalid and the emission output file will not be created? In other words, will the simulation being controlled with Traci4Matlab cause the options written to ".sumocfg" not to work?

`<output>
<emission-output value="Emission_output.xml"/>
</output>`

**Comment by behrisch** [comment]
If you start or load the simulation using your config in any flavor of traci or libsumo all the values set there will be respected just as in the command line or GUI version of sumo. With one major exception being `end`. This value gets ignored and the simulation runs until you stop sending simsteps (or send close or load / start another simulation).

**Comment by erev-84** [comment]
Hello @behrisch 

Thanks for the reply,

Which function should I use to determine the duration of the simulation with Traci4Matlab?

**Comment by behrisch** [comment]
you mean you want to read the `end` which has been given in the config? I am afraid that is currently not possible. There has been #11319 which makes that possible in the current development version (not released) but this has not been ported to Traci4Matlab yet. So either you parse the config yourself or configure it independently

**Comment by erev-84** [comment]
No, I mean how can I set end value by Traci4Matlab? Is there have any Traci4Matlab function to set the duration(end value) of the simulation?

**Comment by behrisch** [comment]
no, you need to count the number of simsteps you make yourself

**Comment by namdre** [comment]
actually, if the .sumocfg defines an end time, you can retrieve the value with `traci.simulation.getEndTime()` You can compare this value to `traci.simulation.getTime()`

**Comment by behrisch** [comment]
But this refers only to the python implementation, you will need to port this to matlab yourself.
