### ISSUE TITLE
osmWebWizard.py: adapt randomTrips min-distance to map size

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#11563]
current default for passenger trips is 300m which may fail to generate any trips on small networks

**Comment by namdre** [comment]
possible solutions
1. parse the network in webWizard and adapt the min-distance value
2. add a new random-trips option that automatially relaxes the min-distance requirement after a sufficient number of failed attempts.

I'm leaning towards 2

**Comment by behrisch** [comment]
duplicate of #10592 ?

**Comment by namdre** [comment]
It's closely related but the suggested solution may be more useful.

When setting **--min-distance.fringe 0**,  short fringe-to-fringe trips will be generated even when they are not necessary whereas proposed solution (2) will only generate short trips if needed.

**Comment by behrisch** [comment]
OK, so we need another option to configure the number of failures after which we apply min_dist_fringe?

**Comment by namdre** [comment]
yes.

**Comment by behrisch** [comment]
add as a generic option for all types but not make it configurable from webwizard

**Comment by behrisch** [comment]
also limiting retries should be done for subsequent trip generations

**Comment by namdre** [comment]
the key intent of only using **--min-dist-fringe** as a fallback if **--min-dist** causes failure was implemented in 108b7f900e5d0f0941a86a587079568c9d21fcb7
