### ISSUE TITLE
Mean waiting time of the vehicles waiting on E2 detectors

### ISSUE THREAD

**Issue by erev-84** [eclipse/sumo#11567]
Hello,

In order to calculate the average/mean waiting time of the vehicles found on the E2 (Lanearea) detector, I tried to retrieve the average waiting time of each vehicle on the detector with the vehicle.getWaitingTime function and divide them by the number of vehicles on the detector to find the average/mean value. However, as can be seen in the screenshot below, some of the vehicles on the detector are not waiting/in motion, which causes the average waiting time to decrease.

Sum of waiting time of the vehicles on the detector / number of the vehicles waiting on the detector

![image](https://user-images.githubusercontent.com/82845085/189445390-50bc4c20-61b0-463d-880f-70b5075d9e65.jpeg)

Is there any other way to retrieve the average/mean waiting time of vehicles waiting on the E2 (Lanearea) detector? Or how can I retrieve the number of vehicles **waiting on the detector**, not all the vehicles on the detector, is there any function for this?

Thanks in advance

**Comment by behrisch** [comment]
you could simply check whether the speed is 0 (or smaller than 0.1) or try to implement access to the lanearea values yourself. I leave this ticket open as a feature request to give traci access to more lanearea detector values

**Comment by erev-84** [comment]
Hello @behrisch 

First of all, thank you very much for the reply.

How can I retrieve and count the number of the vehicles which speed is 0 from the E2 lanearea detectors?

I would be glad if you can show me a sample code.

Thanks in advance

**Comment by behrisch** [comment]
I do not understand your question. In the original post you said you already retrieved the waiting time for all vehicles on the detector. So you seem to know how to retrieve the vehicles (`traci.lanearea.getLastStepVehicleIDs`) and in addition to retrieving the waiting time you may retrieve the speed.

**Comment by erev-84** [comment]
I have to use the function below to get the speed of the vehicles on the lanearea detector, right?

`getLastStepMeanSpeed(self, detID)`
