### ISSUE TITLE
Simulink and Sumo Connection

### ISSUE THREAD

**Issue by erev-84** [eclipse/sumo#11570]
I made the connection between Matlab and Sumo with Traci4Matlab Functions, but unfortunately I can't make the connection/communication between simulink and Sumo. In other words, Traci4Matlab functions work in Matlab Script but not work in Simulink.

What are your suggestions for a solution?

@pipeacosta 
@namdre

**Comment by behrisch** [comment]
Can you describe which errors occur and maybe also share the code?
