### ISSUE TITLE
Displays not working in Game Mode

### ISSUE THREAD

**Issue by erev-84** [eclipse/sumo#11571]
Hello,

As suggested in the issue #11379, I updated sumo/src/gui/GUIApplicationWindow.cpp file but Emergency Vehicle Waiting Time and Waiting Time displays still not working in game mode.

![image](https://user-images.githubusercontent.com/82845085/189553909-d2010e06-9cf7-4f20-bc43-327a5dc2b4a2.png)
![image](https://user-images.githubusercontent.com/82845085/189553517-679c4dcd-b622-4645-807a-0234b6c418b8.png)
![image](https://user-images.githubusercontent.com/82845085/189553702-47aec0a0-8970-4733-8deb-46bda6853dae.png)

I attached the GUIApplicationWindow.cpp file that I use

[GUIApplicationWindow.zip](https://github.com/eclipse/sumo/files/9543742/GUIApplicationWindow.zip)

**Comment by namdre** [comment]
please attach your scenario files

**Comment by namdre** [comment]
the correct initialization are only established if you start sumo with option **--game**  (note, that your screenshot doesn't show any normal vehicle waiting time either).

**Comment by erev-84** [comment]
Hello @namdre 

I initialized Sumo with --game option as seen below but how can ı control the simulation?

Don't have any button to start/stop simulation & I can't zoom the simulation

![image](https://user-images.githubusercontent.com/82845085/189704868-47b28651-7e93-4a38-b150-a755f7f43cf2.png)
![image](https://user-images.githubusercontent.com/82845085/189704978-e92593ce-e4c7-48ef-94fe-58e1fd11ef1a.png)

**Comment by namdre** [comment]
either toggle out of game mode with ctrl+g or control the simulation with hotkeys ctrl+a, ctrl+s, ctrl+d and load the desired zoom from a settings file.

**Comment by namdre** [comment]
or update SUMO to the nightly version where late-toggle now also works.

**Comment by erev-84** [comment]
okey now working, thanks
