### ISSUE TITLE
Error: unable to open file 'https://sumo.dlr.de/xsd/routes_file.xsd

### ISSUE THREAD

**Issue by 5651512351235123** [eclipse/sumo#11572]
hello!
Sumo can't run suddenly, I would like to ask you, is this a software problem or a code problem?

Warning: Cannot read local schema 'E:\SUMOgongzuo\Sumo\tools/data/xsd/routes_file.xsd', will try website lookup.
Error: unable to open file 'https://sumo.dlr.de/xsd/routes_file.xsd'
 In file 'E:\SUMOgongzuo\Sumo\project\fangzhen\912ceshi.rou.xml'
 At line/column 1/0.

Quitting (on error).

**SUMO-version:1.8.0

**operating system:Windows

**Comment by namdre** [comment]
see https://sumo.dlr.de/docs/FAQ.html#whats_the_deal_with_schema_resolution_warnings_xsd_errors

**Comment by 5651512351235123** [comment]
Please accept my heartfelt thanks！
