### ISSUE TITLE
trajectory tracking

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#11573]
①How do I verify that vehicles of different sizes and types have the same trajectory through the same intersection at the same turn
Is there any information in TRACI that records the vehicle's trajectory at the intersection at all times？
②How do you get Bessel control points？Can you give me an example of this, including the calculation process？And how to get the internal lane breakpoint through the cubic Bezier curve?(sampling).
The derivation process of this trajectory is very important for my research, and I can't understand the source code. Please describe it with pictures and the derivation process, thank you very much!!!

**SUMO-version:**

**Comment by namdre** [comment]
1.  https://sumo.dlr.de/docs/Simulation/Output/FCDOutput.html; Please don't confuse "verified simulation behavior" with "verified real world behavior". SUMO makes no claim that all vehicles have the same trajectory when going around a curve in the real world. 
2. Sorry, but No. You are asking for too much.
