### ISSUE TITLE
vehicle collision

### ISSUE THREAD

**Issue by ZXdemao** [eclipse/sumo#11588]
I think in case of vehicle collision, first of all, the following model and collision model of the system have been deleted. The speed of the rear car is 30, and the speed of the front car is 15. Both cars start from the starting point at the same time, but after a period of time, the car slows down to 14, and there is no collision. You've already deleted the following model. Is there any other way to have a collision other than setting the two cars to maintain a certain speed? Thank you for your answer

**SUMO-1.14.1:**

**Comment by namdre** [comment]
https://sumo.dlr.de/docs/Simulation/Safety.html
