### ISSUE TITLE
the shape of lane

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#11589]
Is the lane shape coordinate the intersection point between the center line of the lane and the beginning and end of the lane? As shown in the figure.(the yellow point)
![2c7cb9d7557152f6ecec1be91db86eb](https://user-images.githubusercontent.com/54823725/189894188-9e9a338e-3803-4189-9571-831f8f7412f2.jpg)

**Comment by namdre** [comment]
For a straight lane, yes. There are intermediate points if the lane is curved.
