### ISSUE TITLE
the shape of the lane of internal edge

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#11581]
How do you get the coordinates of the broken line points in Shape from a cubic Bessel curve（How to sample）

**SUMO-version:**

**Comment by namdre** [comment]
https://github.com/eclipse/sumo/blob/79d60b07ab3d9c7d59e8802bae9327a36529c8af/src/utils/geom/PositionVector.cpp#L1784

(called on a vector that holds the control points)
