### ISSUE TITLE
The "Save SUMOConfig" option doesn't include the network file

### ISSUE THREAD

**Issue by angelobanse** [eclipse/sumo#11587]

**Comment by angelobanse** [comment]
I was trying to save/create a config file - and not opening an existing one. Loading an existing config file works as expected.

My workflow:
1. Creating a network
2. Using demand mode to define trips
3. Saving the network file
4. Saving the demand file
5. Attempting to generate a SUMO Config file using File>SUMOConfig>Save SUMOConfig As...

The saved SUMO Config file not only does not contain the network file, but uses `route-files` instead of `value` as a key:

```
<configuration>
    <net-file value=""/>
    <route-files route-files="foobar.rou.xml"/>
</configuration>
```

**Comment by behrisch** [comment]
Furthermore this configuration does not use the "section style" so it won't validate against the schema

**Comment by namdre** [comment]
though the config files are never validated except in our schemacheck tests, right?

**Comment by behrisch** [comment]
right, the SUMO apps do not do this but it helps people who have XML editors with schema support to avoid typos.

**Comment by behrisch** [comment]
It still uses `route-files` instead of `value` here and has no sections or a schema. Can't we use the standard config writer?

**Comment by namdre** [comment]
If we can manage to create a new OptionsCont without clobbering our current Singleton instance, then yes.
