### ISSUE TITLE
crash in saving gui settings to registry

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#11595]
This seems to be visible only when running the Visusla Studio debugger.

- Run the GUI from the debugger and open the scenario in the GUI
- Change an arbitrary GUI setting
- Press the save to registry button
- enter a name -> crash

It bails out in GUICompleteSchemeStorage::remove, the name string seems to be already deleted

**Comment by behrisch** [comment]
It segfaults on Linux as well just later (on closing the GUI).

**Comment by namdre** [comment]
is this a regression?

**Comment by behrisch** [comment]
I am not sure and it is hard to check because it only shows up in the debug build

**Comment by namdre** [comment]
doesn't look like a recent regression
