### ISSUE TITLE
add more entries to help menu

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#11604]
- [x] Changelog (simply a link to the changelog page)
   - bonus points if we can make it point the the relevant section (i.e. dev or the respective release)
 - [x] Hotkeys: https://sumo.dlr.de/docs/sumo-gui.html#keyboard_shortcuts
   - the section in the documentation also needs to be updated
 - [x] Tutorial: https://sumo.dlr.de/docs/Tutorials/index.html

**Comment by palvarezlopez** [comment]
And for tutorials?

**Comment by namdre** [comment]
a single link to the tutorial page suffices
