### ISSUE TITLE
cadytsIterate.py fails to run due to invalid file paths

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#11600]
since #7162 (1.7.0 duaIterate creates subfolders for each iteration. It appears that cadytsIterate was not adapted to this.

This error was reported on the mailing list:

```
Error: Could not save configuration to '000/iteration_000.sumocfg'

Quitting (on error).

Execution of ['C:\\Program Files (x86)\\Eclipse\\Sumo\\bin\\sumo', '-c', '0/iteration_000.sumocfg'] failed. Look into cadySumo-log.txt for details.
```

**Comment by namdre** [comment]
@yunpangfloetteroed  can you perform a local test for cadytsiterate and replicate the problem?

**Comment by yunpangfloetteroed** [comment]
I thought, the cadytsIterate.py was already adjusted.  I will have a check on it!

**Comment by yunpangfloetteroed** [comment]
The problem is solved. The cadyts tool is currently not in the sumo-package (#11014). A daily test can be built for it, after/if we include it when building sumo.

**Comment by namdre** [comment]
@yunpangfloetteroed  After your refactoring, the python checker gives the warning:
`assign/duaIterate.py:497:50: F821 undefined name 'step'`

The code will crash when option **--eco-measure** is set.  
- obviously we are missing a test
- it's quite possible that the code already didn't work before your refactoring so it should be fixed

I hope you can handle both (-:
