### ISSUE TITLE
no selection editor in netedit

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#11611]
It is in the edit menu in sumo-gui but not in netedit

**Comment by palvarezlopez** [comment]
I thought is not neccesary because we have the "select mode"

**Comment by namdre** [comment]
Yes. This was a conscious design choice since selection mode contains a superset of functionality and makes this dialog obsolete.  I recommend closing this as 'worksforme'.

**Comment by behrisch** [comment]
Then where do I get a list of selected elements from? Saving to disk and use a text editor?

**Comment by palvarezlopez** [comment]
In select mode, save current selection

**Comment by namdre** [comment]
Depends on what you want to do with that list. If you want to jump to the respective objects or toggle their selection state, then using the locate dialog and filtering out unselected is the recommended approach (it also permits changing selection state)

**Comment by behrisch** [comment]
This works if I select only one kind of objects but yes I think it is enough for my use case and I can save to disk in any other case
