### ISSUE TITLE
Some lanes have no vehicles pass.

### ISSUE THREAD

**Issue by yifan-dadada** [eclipse/sumo#11626]
Hello! I'm having some problems using SUMO. When using the steering information in the figure, there will be no vehicles passing through the four lanes on the left, and the vehicles will pass through the four lanes on the right by default. Please let me know if there is a good solution to this problem.

<img width="712" alt="image" src="https://user-images.githubusercontent.com/88924753/190838978-08b60493-2fda-4327-b803-66778f8ab338.png">

![微信图片编辑_20220917113556](https://user-images.githubusercontent.com/88924753/190839040-6ef10b13-bd13-4123-b91d-88d83dc7b334.jpg)

**Comment by namdre** [comment]
having a lane for straight movement in between two lanes for left-turning movement is not handled by the lane-changing model and frankly such a layout would be highly irregular (probably forbidden) in a real world context to to it's unsafe nature.
I recommend correctiong the layout to avoid this in-between-ness
