### ISSUE TITLE
About the parking problem in sumo

### ISSUE THREAD

**Issue by OccZa** [eclipse/sumo#11628]
Vehicle parking in sumo needs to be set up with an xml file. When the parking lot set by vehicle A is full, I want to stop vehicle A from waiting in that parking lot by traci, and I don't want to change the parking location by ”reroute“ setting file. I just want to make the vehicle not wait next to the parking lot, but directly change the path of the vehicle. How do I do this, please?
I have tried ”setStop (duration=0)“ in Traci, but unfortunately this does not work.

**Comment by OccZa** [comment]
I find that i can use: traci.vehicle.replaceStop('vehicle_ID', nextStopIndex=0, edgeID='the edge of the vehicle's parkingarea', duration=0) to solve this problem. Thanks.

**Comment by namdre** [comment]
did you read about 
https://sumo.dlr.de/docs/Simulation/Rerouter.html#rerouting_to_an_alternative_parking_area
and
https://sumo.dlr.de/docs/Tools/Misc.html#generateparkingarearerouterspy
