### ISSUE TITLE
Vehicles halting during simulation regarding RL training.

### ISSUE THREAD

**Issue by Oritchimaru** [eclipse/sumo#11633]
Hello!

I run simulations (1 simulation = 1 episode) of 15 minute traffic through a random generated network in order to train some agents (reinforcement learning algorithm) thus I use setSpeed() to adjust speed manually given the agents' choice.

The problem is that many times vehicles stop for no reason, they can have a speed of 25 m/s and suddenly stop, rising the halting flag.

I've done my best to disable all safety measures regarding collision check, also I'm trying to make lane changing deterministic, to happen only when is needed for a vehicle to arrive to it's destination.

Below I provide some of the code I've used to give intuition on how I approach it.

Command I've used to generate my network:
`netgenerate --rand -o random.net.xml --rand.iterations=6 --rand.max-distance=400 --rand.min-distance=200 --rand.random-lanenumber=True --default.lanenumber=2 --no-turnarounds`

Command I've used to generate traffic for the above network:
`python3 PATH/randomTrips.py -n random.net.xml -b 0 -e 1800 -p 4 --trip-attributes="departLane=\"best\" departSpeed=\"10.0\" departPos=\"base\"" --route-file random.rou.xml --fringe-factor 20000 --random -o random.trips.xml`

Have tried to add these to newcoming vehicles and combinations of them, I struggle to fully understand what fits my scenario:
`traci.vehicle.setSpeedMode(veh_id, 32)
traci.vehicle.setSpeedMode(veh_id, 0)
traci.vehicle.setLaneChangeMode(veh_id, 0b001000000000)
traci.vehicle.setLaneChangeMode(veh_id, 512)`

My sumocmd arguments:
`sumoCmd = [sumoBinary, "-c", name + "/osm.sumocfg", "--collision.action", "remove",
		   "--collision.check-junctions", "true", "--no-step-log", "true", "--disable-textures",
		   "--waiting-time-memory", str(max_steps), "--no-warnings", "true"]`

An example of the problem.

![image](https://user-images.githubusercontent.com/26443186/190981715-976ee173-9668-49aa-930c-b77cc0afb570.png)

some of these vehicles had a speed of 30 m/s and instantly stopped, making the previous cars decel as needed to avoid collision, so of the cars marked, the leaders had the problem.

If anyone can spot anything and provide some feedback I will be more that thankful!

**Comment by namdre** [comment]
due to backward compatibility, one of the speedMode bits had to be inverted. To disable everything, use mode 32

**Comment by Oritchimaru** [comment]
> due to backward compatibility, one of the speedMode bits had to be inverted. To disable everything, use mode 32

ok, I use now
`traci.vehicle.setSpeedMode(veh_id, 32)
traci.vehicle.setLaneChangeMode(veh_id, 0b001000000000)`

the halting problem still remains though, below I give new example, inspecting the first problematic car of this queue that stopped instantaneously and regardless of being told to accelerate it remains with 0 speed. 

![image](https://user-images.githubusercontent.com/26443186/190985558-0febac22-21e1-43ca-90dd-ace28beb6bac.png)

**Comment by namdre** [comment]
Please provide a minimal reproducible example (sumo files + log of traci commands)
see https://sumo.dlr.de/docs/TraCI/Interfacing_TraCI_from_Python.html#generating_a_log_of_all_traci_commands

**Comment by Oritchimaru** [comment]
Nevermind, it was probably because of older version, I'm running it on different pc now with newer version, will attach results in a bit.

**Comment by Oritchimaru** [comment]
TRACE FILE
[trace_report.txt](https://github.com/eclipse/sumo/files/9597957/trace_report.txt)

SUMO FILES
(Converted them to .TXT in order to be able to upload them)

[small.trips.txt](https://github.com/eclipse/sumo/files/9597986/small.trips.txt)
[randomSmall.net.txt](https://github.com/eclipse/sumo/files/9597983/randomSmall.net.txt)
[osm.small.txt](https://github.com/eclipse/sumo/files/9597984/osm.small.txt)
[small.rou.txt](https://github.com/eclipse/sumo/files/9597985/small.rou.txt)

**Comment by JamesPsh** [comment]
@Oritchimaru

Hello.

May I ask you one thing?
I am very interested in reinforcement learning.

Could I ask which reinforcement learning algorithm you are using?

**Comment by Oritchimaru** [comment]
> @Oritchimaru
> 
> Hello.
> 
> May I ask you one thing? I am very interested in reinforcement learning.
> 
> Could I ask which reinforcement learning algorithm you are using? And how did you build the state, reward, and action?
> 
> Thank you.

@JamesPsh 

For confidentiality reasons I am not able to speak much into the details, I'm using PPO and I'm approaching it with a continuous action space. Rewards and states have to do with vehicle's attributes like personal speed, coordinates, leader's speed etc. When the respective paper is to be published I will be more than happy to share it with you!

**Comment by JamesPsh** [comment]
@Oritchimaru 

Thank you for the reply.
I would happy to see your paper.
