### ISSUE TITLE
coordinate display

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#11630]
My SUMO version is 14, but the coordinate in the lower right corner is not shown, how to solve, thank you
**SUMO-version:**

![3944e4f390ffd979b107d4fd933ab1e](https://user-images.githubusercontent.com/54823725/190885016-cfed77d8-e77c-498e-ac96-4da1226c981d.jpg)

**Comment by namdre** [comment]
this is a known and fixed bug: see #11230
