### ISSUE TITLE
Using Python XML-conversion tools on Mac OS

### ISSUE THREAD

**Issue by ajmacmahon** [eclipse/sumo#11638]
How can I use these tools on a Mac to convert to XML and back?

<img width="1404" alt="Bildschirmfoto 2022-09-20 um 00 03 58" src="https://user-images.githubusercontent.com/105850009/191128416-2e13dbe0-f676-4f2c-95ae-58a95d8310e6.png">

**Comment by namdre** [comment]
did you try installing python and calling the tool as described in the documentation?

**Comment by ajmacmahon** [comment]
`alexandermacmahon@Alexanders-MacBook-Air simulation % python tools/xml/xml2csv.py battery.xml
zsh: command not found: python
alexandermacmahon@Alexanders-MacBook-Air simulation % python3 tools/xml/xml2csv.py battery.xml
/opt/homebrew/bin/python3: can't open file '/Users/alexandermacmahon/Library/CloudStorage/OneDrive-WaldaschaffAutomotiveGmbH/Teams Wiki Data/02_SUMO/Autobahn Stuttgart/Eigene Versuche/220902/stuttgart-sumo-traffic-scenario-master/simulation/tools/xml/xml2csv.py': [Errno 2] No such file or directory
alexandermacmahon@Alexanders-MacBook-Air simulation %`

This is what I tried - I need to use command `python3` instead of `python` for some reason. Do I need to copy the XML-tools to my working directory?
