### ISSUE TITLE
NetConvert outputs differ based on OS (trac #1163)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#1163]
Sincere apologies if this is a duplicate. Using the site's search, I was not able to find a similar issue.

-----------
'''SUMMARY'''

Inconsistencies were detected when using NETCONVERT on different OSes to translate OSM-XML (e.g., map.osm) into SUMO-XML (e.g., roads.net.xml).

That is, net.xmls produced in Windows were different from those produced in Linux or MacOS. The expectation is that netconvert would produce the same outputs for all OSes/platforms.

-----------
'''DESCRIPTION'''

We created outputs on Windows and Linux, both with SUMO netconvert 0.19.0. Comparing both to an earlier version created on Mac (also 0.19):
* '''Item 1.1''': shapes are slightly adjusted
* '''Item 1.2''': junctions have significant differences in their "request" sub-elements (controls flows and right-of way within junctions).
* '''Item 1.3''': some lane connections are different (although they do lead into the same edges/roads).

Between Linux and Windows:
* shapes are exactly the same.
* junctions still exhibit differences in "request" sub-elements
* lane connections are also different.

An example of '''Item 1.3''', where lane changes are seen:
* <connection from="-48369" to="-48368" fromLane="0" toLane="0" dir="s" state="M"/> '''''(Windows)'''''
* <connection from="-48369" to="48369" fromLane="0" toLane="'''1'''" dir="'''t'''" state="'''m'''"/> '''''(Linux)'''''

~~Also, "dir" and "state" do not seem to be used by SUMO. They are probably artifacts from the translation from OSM. There seems no mention of it in official documentation or schema definitions.~~

----------------------
'''PRELIMINARY CONCLUSION'''

After investigation, the differences in junctions and lane connections were deemed minor.

In the case of junctions ('''item 1.2'''), only the right-of-way of vehicles were affected. Ultimately, the junctions are still at the correct coordinates, and connected to the correct roads.

In the case of lane connections ('''item 1.3'''), the affected roads are still connected to each other. It's just that the lanes are attached differently.

 
----------------------
'''NOTES'''

The original OSM data imported was 13MB and consistently produced the differing outputs.

Trying with smaller OSM exports (1MB to 8MB), sometimes the outputs were exactly the same (as expected). However, there were still instances where outputs were different.

Also tried:
* Zooming in a specific problem junction (from the original 13MB OSM)
* Re-exporting a smaller OSM around that junction
* Re-running netconvert on that smaller OSM on both Windows and Linux

Comparing the outputs, we see the junction itself is OK. However, other junctions become affected.

----------------------
'''END'''

I will try attaching the original OSM file, and netconvert outputs to this ticket (if possible... they are quite large).

Please advise if more data or information is needed.

Many thanks for allowing the use of SUMO.

Migrated from http://sumo.dlr.de/ticket/1163
```json
{
    "status": "new", 
    "changetime": "2016-10-25T09:33:11Z", 
    "description": "Sincere apologies if this is a duplicate. Using the site's search, I was not able to find a similar issue.\n\n\n-----------\n'''SUMMARY'''\n\nInconsistencies were detected when using NETCONVERT on different OSes to translate OSM-XML (e.g., map.osm) into SUMO-XML (e.g., roads.net.xml).\n\nThat is, net.xmls produced in Windows were different from those produced in Linux or MacOS. The expectation is that netconvert would produce the same outputs for all OSes/platforms.\n\n\n-----------\n'''DESCRIPTION'''\n\nWe created outputs on Windows and Linux, both with SUMO netconvert 0.19.0. Comparing both to an earlier version created on Mac (also 0.19):\n - '''Item 1.1''': shapes are slightly adjusted\n - '''Item 1.2''': junctions have significant differences in their \"request\" sub-elements (controls flows and right-of way within junctions).\n - '''Item 1.3''': some lane connections are different (although they do lead into the same edges/roads).\n\nBetween Linux and Windows:\n - shapes are exactly the same.\n - junctions still exhibit differences in \"request\" sub-elements\n - lane connections are also different.\n\n\nAn example of '''Item 1.3''', where lane changes are seen:\n - <connection from=\"-48369\" to=\"-48368\" fromLane=\"0\" toLane=\"0\" dir=\"s\" state=\"M\"/> '''''(Windows)'''''\n - <connection from=\"-48369\" to=\"48369\" fromLane=\"0\" toLane=\"'''1'''\" dir=\"'''t'''\" state=\"'''m'''\"/> '''''(Linux)'''''\n\n~~Also, \"dir\" and \"state\" do not seem to be used by SUMO. They are probably artifacts from the translation from OSM. There seems no mention of it in official documentation or schema definitions.~~\n\n\n----------------------\n'''PRELIMINARY CONCLUSION'''\n\nAfter investigation, the differences in junctions and lane connections were deemed minor.\n\nIn the case of junctions ('''item 1.2'''), only the right-of-way of vehicles were affected. Ultimately, the junctions are still at the correct coordinates, and connected to the correct roads.\n\nIn the case of lane connections ('''item 1.3'''), the affected roads are still connected to each other. It's just that the lanes are attached differently.\n\n \n----------------------\n'''NOTES'''\n\nThe original OSM data imported was 13MB and consistently produced the differing outputs.\n\nTrying with smaller OSM exports (1MB to 8MB), sometimes the outputs were exactly the same (as expected). However, there were still instances where outputs were different.\n\nAlso tried:\n - Zooming in a specific problem junction (from the original 13MB OSM)\n - Re-exporting a smaller OSM around that junction\n - Re-running netconvert on that smaller OSM on both Windows and Linux\n\nComparing the outputs, we see the junction itself is OK. However, other junctions become affected.\n\n\n----------------------\n'''END'''\n\nI will try attaching the original OSM file, and netconvert outputs to this ticket (if possible... they are quite large).\n\nPlease advise if more data or information is needed.\n\nMany thanks for allowing the use of SUMO.\n\n\n", 
    "reporter": "mardi almashor", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1477387991881859", 
    "component": "net building (NETGEN, NETCONVERT)", 
    "summary": "NetConvert outputs differ based on OS", 
    "priority": "minor", 
    "keywords": "mac, linux, windows, different netconvert outputs", 
    "time": "2014-02-24T06:50:59Z", 
    "milestone": "2.0.0", 
    "owner": "", 
    "type": "defect"
}
```

**Comment by namdre** [comment]
duplicate of #1483
