### ISSUE TITLE
Arbitrary text with poi 

### ISSUE THREAD

**Issue by btopii32** [eclipse/sumo#11647]
Hello guys, I'm trying to write arbitrary text on the sumo gui. I found out that poi is the way to go. I tried implementing it but the text is not showing. Can anyone help me with the implementation please?

**Comment by behrisch** [comment]
Please show what you tried and the we can work on it. You can basically visualize any param you give to the [poi](https://sumo.dlr.de/docs/Simulation/Shapes.html#poi_point_of_interest_definitions) or "abuse" the type attribute. then you need to enable drawing in the[ visualization settings](https://sumo.dlr.de/docs/sumo-gui.html#common_visualization_settings) in sumo-gui.

**Comment by btopii32** [comment]
What do you mean by visualize any param sir? Been reading around it but haven't been able to understand. This is me trying use the visualization in poi tab but I don't know what check boxes to tick. Below:
![vijay.png](https://user-images.githubusercontent.com/57776760/191478168-63bbacb8-1d58-4b5b-9edb-bc2fe6cb342a.png)

**Comment by btopii32** [comment]
I also used this tag in my .sumocfg file
<poi id="text1" type="this is my text" x="-55.19" y="83.66" color="0,0,0"/>

**Comment by namdre** [comment]
> What do you mean by visualize any param

If your poi looks like this:
```
 <poi id="text1" type="something unrelated" x="-55.19" y="83.66" color="0,0,0"> 
       <param key="custom" value="this is my text"/>
  </poi>
```

Then you can activate the gui setting 'Show poi text param' and select param 'custom' from the drop-down menu to the right of that checkbox.

However, for the poi you showed, activating 'Show poi type' is sufficient.
