### ISSUE TITLE
Driver proficiency coefficient of Krauss following model

### ISSUE THREAD

**Issue by ZXdemao** [eclipse/sumo#11649]
There is a driver proficiency coefficient in the Krauss following model. What is the evaluation criterion of this coefficient in practical application? Is it practical to think about how many miles drivers drive? Or how long it takes to get a driver's license? Or what else? Could you please answer it? Thank you.

**SUMO-14.1:**

**operating system:**

**Comment by namdre** [comment]
To my knowledge this coefficient (`sigma`) was never evaluated against practical driving proficiency. Instead it was added to the model as a means to replicate aggregated traffic measurements (i.e. https://en.wikipedia.org/wiki/Fundamental_diagram_of_traffic_flow).

Compared to other carFollowModels (EIDM, Wiedemann) that are more closely linked to behavioral / psychological assumptions, the Krauss model is an attempt to built a very simple model that suffices to replicate certain aggregated traffic statistics. 

A common way of using `sigma` is to distinguish human from automated driving (with the latter having sigma ~ 0)
