### ISSUE TITLE
collision between a veh (no lane-changing) and bike on bidi

### ISSUE THREAD

**Issue by yunpangfloetteroed** [eclipse/sumo#11642]
Add your issue description here.
The vehicle is customized not to make lane changing.  The bike does not try to yield or keep distance when meeting the vehicle.

This situation cannot be reproduced in a extracted network. The original scenario locates under S:\Sumo\Bugreports\11642_collision_shuttle_ped_bidi
Collision time: 58284.20
lane='26967263#8_0
vehicle 'bike152

SUMO-version:
v1_14_1+1149-c15e7942a49
operating system:
Windows

**Comment by yunpangfloetteroed** [comment]
In the same scenario there is another collsion case with the same vehicle, but on a different bidi-edge: vehicle had a collision with 'bike235', lane='26967263#4_0', gap=-0.07', latGap=-0.85, time=59452.90 s

**Comment by namdre** [comment]
- the scenario doesn't have vehicle on vehicle collisions any more
- there is still one vehicle vs pedestrian collison that persists even after updating the network
- the network reveals some issues with regard to recent changes in collision avoidance w.r.t. sublane model (#13313 causes braking even where sublanes do not interact)
