### ISSUE TITLE
initial stop assignment to edge without proper permissions

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#11656]
follow up to #11645, visible in tools/import/OSM/taxiStop/plain (and others)

**Comment by behrisch** [comment]
still problems in the webwizard scenario

**Comment by namdre** [comment]
I thought our original strategy to deal with a mismatch between edge permissions and stop permissions was to extend the edge permission as needed. Is the new strategy to find a better-matching edge now?

**Comment by behrisch** [comment]
The cases seem to be false negatives which disappeared now that the warnings are better focused. The topic is still not completely gone.
In the web wizard test there are bus stops (e.g. '3104797566' (Friedrichstr./ Reinhardtstr.)) which appear once as highway=stop (this is on the sidewalk) and once as public_transport=stop_position. I am not sure why we import both (and then discard the first one) and whether we could automatically detect that we have it in fact twice, but the result looks ok for now so I am closing here.
