### ISSUE TITLE
Ambiguous message when creating a new network with NetEdit

### ISSUE THREAD

**Issue by bcoueraud87** [eclipse/sumo#11655]
When creating a new network in NetEdit, if a network is already displayed, a message box will appear asking whether we want to save the network or not before creating a new one. The message box contains three buttons, the one on the left is named "Quit", which is not very informative as the button is used for discarding the current network. Could it be changed to "Discard" or "Don't save"? It would be perhaps more appropriate.

**Comment by palvarezlopez** [comment]
yes, I think is a good Idee. Thanks!

**Comment by behrisch** [comment]
Maybe we could adapt the scheme to the more general "save", "don't save", "abort" which you see for instance in MS Office
