### ISSUE TITLE
Vehicle change lane by its own

### ISSUE THREAD

**Issue by somkar** [eclipse/sumo#11657]
We tired to create a scenario in rout.xml and later-own used Traci commands control the vehicle.
However we observed that sometimes vehicle change lanes by its own. We tried to control its behaviors to avoid lane change but unable to do so.
Can you suggest the reason for this change of lane by vehicle. How can we stop the same.

SUMO-version: 1.13.0

operating system: windows

**Comment by namdre** [comment]
`vehicle.setLaneChangeMode(vehID, 256)`  should suffice to prevent all autonomous lane changes. See https://sumo.dlr.de/docs/TraCI/Change_Vehicle_State.html#lane_change_mode_0xb6
