### ISSUE TITLE
IDM carfollowing model The distance between two carsdistance will be small?

### ISSUE THREAD

**Issue by ZXdemao** [eclipse/sumo#11650]
Using the IDM car-following model built in SUMO, it is found that when the speed of the leading vehicle is 15m/s, the distance between the following vehicles at the rear is about 20m, and the driver's reaction time is 1 second. Will there be a collision when the current vehicle brakes in an emergency? Could you please help me? Thank you.

**SUMO-14.1:**

**operating system:**

**Comment by namdre** [comment]
No. The follower vehicle should have enough time to react with it's own emergency braking.
