### ISSUE TITLE
After Road Segment Refining ,The connection generate by netconvert is not balanced

### ISSUE THREAD

**Issue by songjianbupt** [eclipse/sumo#11658]
Add your issue description here.

*If possible, upload an example that shows your problem.*
when I use edge split, the default connection generate by netconvert is not balanced.
lanes number change from 3 to 2
```
        <edge id="0_#5#" name="DIRECTION_UNKNOWN" from="0" to="#5#" priority="3" numLanes="3" speed="13" length="171.2185" shape="" spreadType="right" allow="all">
                <lane index="0"  changeLeft="all" changeRight="all" speed="13.0" allow="all" />
                <lane index="1"  changeLeft="all" changeRight="all" speed="13.0" allow="all" />
                <lane index="2"  changeLeft="all" changeRight="all" speed="13.0" allow="all" />
                <split pos="0" lanes="0 1 2" />
                <split pos="82.2835" lanes="0 1" />
        </edge>
```

lanes number chang from 2 to 5:

        <edge id="#5#_0" name="NORTH" from="#5#" to="0" priority="3" numLanes="5" speed="13" length="171.78770000000003" shape="" spreadType="right" allow="all">
                <lane index="0" changeLeft="all" changeRight="all" speed="13.0" allow="all" />
                <lane index="1"  changeLeft="all" changeRight="all" speed="13.0" allow="all" />
                <lane index="2"  changeLeft="all" changeRight="all" speed="13.0" allow="all" />
                <lane index="3"  changeLeft="all" changeRight="all" speed="13.0" allow="all" />
                <lane index="4"  changeLeft="all" changeRight="all" speed="13.0" allow="all" />
                <split pos="0" lanes="0 1" />
                <split pos="87.9132" lanes="0 1 2 3 4" />
        </edge>
<img width="530" alt="image" src="https://user-images.githubusercontent.com/25786094/191646489-5ede856d-248d-49dd-a04d-435394122551.png">

I changed the generate method

```
diff --git a/src/netbuild/NBEdgeCont.cpp b/src/netbuild/NBEdgeCont.cpp
index 2595af2c754..2f50b063088 100644
--- a/src/netbuild/NBEdgeCont.cpp
+++ b/src/netbuild/NBEdgeCont.cpp
@@ -492,6 +492,7 @@ NBEdgeCont::processSplits(NBEdge* e, std::vector<Split> splits,
             NBEdge* ne = retrieve(idAfter);
             // reconnect lanes
             pe->invalidateConnections(true);
+            /*
             //  new on right
             int rightMostP = currLanes[0];
             int rightMostN = newLanes[0];
@@ -514,6 +515,25 @@ NBEdgeCont::processSplits(NBEdge* e, std::vector<Split> splits,
                 }
                 pe->addLane2LaneConnection(l - rightMostP, ne, l - rightMostN, NBEdge::Lane2LaneInfoType::VALIDATED, true);
             }
+            */
+            int rightMostP = currLanes[0];
+            int rightMostN = newLanes[0];
+            int leftMostP = currLanes.back();
+            int leftMostN = newLanes.back();
+            int numLanesP = leftMostP - rightMostP + 1;
+            int numLanesN = leftMostN - rightMostN + 1;
+            if (numLanesP >= numLanesN) {
+                for (int l = rightMostP; l < leftMostP + 1; ++l) {
+                    int out_index = int(round(1 / float(numLanesP) * (float)(l - rightMostP) * (float(numLanesN) - 1)));
+                    pe->addLane2LaneConnection(l, ne, out_index, NBEdge::Lane2LaneInfoType::VALIDATED, true);
+                }
+            } else {
+                for (int l = rightMostN; l < leftMostN + 1; ++l) {
+                    int in_index = int(round(1 / float(numLanesN) * (float)(l - rightMostN) * (float(numLanesP) - 1)));
+                    pe->addLane2LaneConnection(in_index, ne, l, NBEdge::Lane2LaneInfoType::VALIDATED, true);
+                }
+            }
+
```

After that, the new connection is like this
<img width="463" alt="image" src="https://user-images.githubusercontent.com/25786094/191647585-1b581cdc-7f5d-4def-b2e3-af2d85837f0c.png">

**SUMO-version:**

**operating system:**

**Comment by namdre** [comment]
leaving one lane unconnected is the recommended way to model a lane drop (especially at motoroway on-ramps). This forces vehicles to perform a lane change maneuver beforehand. 
Hence the split/connection code is working as intended.
An alternative is to model late merging via junction type 'zipper'. (https://sumo.dlr.de/docs/Networks/PlainXML.html#node_types)
