### ISSUE TITLE
trajectory tracking

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#11659]
I asked the question before, is the trajectory of the vehicle at the intersection along the broken line segment of the internal lane? More specifically, does the vehicle travel in a straight line on each line segment? How does it move at the inflection point? Or is the motion of the vehicle a curve?
It is very important for me, thank you very much

**SUMO-version:**

**Comment by behrisch** [comment]
What exactly was wrong with te answer given in #11578 ?
