### ISSUE TITLE
add more colors to crossing mode

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#11654]
once an edge is set to be crossed, edges on the opposite side of the intersection should not longer be eligible for clicking (and greyed out).

This avoids the misunderstanding where people try to create crossings similar to how they would create connections (selecting a start and end lane).

Edges at a 90 degree angle must still be clickable to permit creating diagonal crossings

**Comment by behrisch** [comment]
also a legend on the left would help

**Comment by namdre** [comment]
this seems to be working now.

**Comment by palvarezlopez** [comment]
All test green.
