### ISSUE TITLE
CACC performs emergency brakings and collisions

### ISSUE THREAD

**Issue by mehmetnedimyavuz** [eclipse/sumo#11653]
Add your issue description here.

*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**
[emergency_braking.zip](https://github.com/eclipse/sumo/files/9615054/emergency_braking.zip)

Hello,
I am using CACC car following model with default gain parameters on freeway network. I am facing emergency braking issues that some of them are on insertion and even collision between CACC vehicles. Simulation step-length is 0.1. I am using latest SUMO version. Why this happen? Can you help? I am adding my simulation files. Thank you for help,regards.

**Comment by namdre** [comment]
collisions are fixed but emergency brakings are still there (follow-up is #11679)
