### ISSUE TITLE
sumo has crashed without any error message in log

### ISSUE THREAD

**Issue by yunpangfloetteroed** [eclipse/sumo#11661]
Add your issue description here.
as title; the crash happens around 1604 s in the attached scenario.

Sumo does not crash, when
1. only base_pt.rou.xml is given as demand 
or 
2. all other route files are given as demand without base_pt.rou.xml

*If possible, upload an example that shows your problem.*
[scenario.zip](https://github.com/eclipse/sumo/files/9623881/scenario.zip)

**SUMO-version:**
v1_14_1+1196-7870e9dd88e

**operating system:**
Windows

**Comment by namdre** [comment]
crash due to inconsistency in input network (asymmetrical neigh relationship)

**Comment by namdre** [comment]
the simulation now ends with an error and it's not quite clear how that error relates to the inconsistent input (possibly caused by unequal neigh-lane lengths)

**Comment by yunpangfloetteroed** [comment]
The error shows that the lateral offset is needed for an invalid connection lane within the junction. Is overtaking allowed within a junction in SUMO? 

It would be aslo useful to have the warnings about "Warning: Asymmetrical neigh ..." shown in sumo-gui when opening netedit.

**Comment by namdre** [comment]
I was unable to create a small test case but the problem should be fixed now (the scenario runs to completion).
Follow up issues are #11721  and #11731
