### ISSUE TITLE
function setStop() of traci

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#11660]
Can you explain  the parameter "startPos" and "until" of this function  more clearly  to me? 
![14efa4bcb9a8b6c2f64d4c5146c4f36](https://user-images.githubusercontent.com/54823725/191685889-3e49d28e-4b61-48c3-9db6-54d57bd484d0.jpg)

**SUMO-version:**

**Comment by behrisch** [comment]
The docs for stops are here: https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#stops_and_waypoints
