### ISSUE TITLE
Problem with arrivalPos with the striping model and backward edges

### ISSUE THREAD

**Issue by bcoueraud87** [eclipse/sumo#11674]
An arrivalPos parameter with value less than 0.5 doesn't work with the striping model when used with a backward edge. The input files for reproducing this issue are [here](https://github.com/eclipse/sumo/files/9626632/two_edges_crosswalk_backward.zip).

**Comment by namdre** [comment]
The within-junction-routing failed to stay within the junction and could thereby produced an infeasible routes
