### ISSUE TITLE
 position of the  vehicles

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#11672]
The position of the various vehicles in the middle of the SUMO is how to view the vehicle as a point, is it the geometric center? (as shown in the following figure)
![微信图片_20220922210450](https://user-images.githubusercontent.com/54823725/191754763-4ce3b55e-6916-40ea-9225-90cc0b67c5d8.jpg)
**SUMO-version:**

**Comment by namdre** [comment]
position denotes the front of the vehicle.

**Comment by a-123-du** [comment]
> position denotes the front of the vehicle.
 Is it the midpoint of the front overhang（The blue dot are shown here）？
![微信图片_20220923160855](https://user-images.githubusercontent.com/54823725/191917954-b0ace832-d772-4aa7-afce-7baee746d046.jpg)

**Comment by namdre** [comment]
yes
