### ISSUE TITLE
Joining multiple platoons

### ISSUE THREAD

**Issue by prasuka4** [eclipse/sumo#11678]
I have tried to add group of platoon from one route to a group of platoon from other route. But it is not possible. Could you please let me know how to add.

I have tried to keep different vehicle routes but i was unable to understand how to provide information in simpla.cfg.xml. As it was throwing an error.

![image](https://user-images.githubusercontent.com/48856575/191884676-fc11f139-86ad-4dd9-9948-ec8d03ed706b.png)
![image](https://user-images.githubusercontent.com/48856575/191884721-3b440122-2eb2-4e69-8587-69dfda465873.png)

**SUMO-version:**
![image](https://user-images.githubusercontent.com/48856575/191884881-f2356056-0544-4a3e-9f68-0c7df2a89263.png)

**operating system:**
windows - 11

**Comment by m-kro** [comment]
Could you say a bit more than "it is not possible" and write the error message you get? You can add your simulation files for further diagnosis as well.

**Comment by m-kro** [comment]
Not enough information provided to investigate further...
