### ISSUE TITLE
How to use the custom lane change mode and following model

### ISSUE THREAD

**Issue by LittleWhiteRushRushRush** [eclipse/sumo#11673]
Add your issue description here.
**Hello developers! I have a question: I have defined a simple following and lane change mode according to the official document. How can I use it and where can I invoke it? Because the SUMO I downloaded appears to be compiled, I did not find the SRC source package in the installation directory.**
*If possible, upload an example that shows your problem.*

**SUMO-version:**
1.14.0
**operating system:**
windows

**Comment by LittleWhiteRushRushRush** [comment]
Hello, after reading the document link you provided, I still can't understand it well. I have configured a lane change mode and a galloping mode according to link 1 and link 2, but what I can't understand is how to apply these two modes to the simulation I designed. I use Windows. I downloaded the package and decompressed it, but there is no SRC file in the package, as shown in Figure 1. But following the tutorial for links 1 and 2, I need to add the custom model in the SRC file. So I cloned SUMO's source code and added the two schemas I mentioned above to the SRC file, as shown in Figure 2. The problem arises when I add a custom model to the source code, since I am still using the SUMO shown in Figure 1. Do I need to compile the SUMO in Figure 2 as a source build? And if so, how to do it. In addition, I wonder if I would have to rebuild SUMO through the source code every time I added a custom model, as I did in Figure 2. I hope you can help me. Thank you very much

Link1：https://sumo.dlr.de/docs/Developer/How_To/Car-Following_Model.html
Link2：https://sumo.dlr.de/docs/Developer/How_To/Lane-Changing_Model.html
F1：
![image](https://user-images.githubusercontent.com/81957538/191879512-750119e0-3206-4220-9072-a9d2c0857a0e.png)

F2：
![image](https://user-images.githubusercontent.com/81957538/191879616-091919f2-8af0-4a9f-b379-2fd732ba38f8.png)

**Comment by LittleWhiteRushRushRush** [comment]
Does the SRC file need to be recompiled every time a custom model is added to it.
https://sumo.dlr.de/docs/Installing/Windows_Build.html

**Comment by namdre** [comment]
> Does the SRC file need to be recompiled every time a custom model is added to it. https://sumo.dlr.de/docs/Installing/Windows_Build.html

yes.

**Comment by LittleWhiteRushRushRush** [comment]
Can you elaborate on how to recompile the document? I think I tried the wrong way.

**Comment by namdre** [comment]
Your questions suggest that you do not have much experience with software development for compiled languages. Unfortunately, we are not able to provide a general education on these topics here. I recommend that you find local help.
