### ISSUE TITLE
collision

### ISSUE THREAD

**Issue by LittleWhiteRushRushRush** [eclipse/sumo#11677]
Add your issue description here.
How to realize in SUMO that after two cars collide, they stop at the collision point for a period of time and are removed.
*If possible, upload an example that shows your problem.*
**SUMO-version:**
1.14.1
**operating system:**
windows

**Comment by namdre** [comment]
**--collision.stoptime TIME ----collision.action remove** (see https://sumo.dlr.de/docs/Simulation/Safety.html)

**Comment by LittleWhiteRushRushRush** [comment]
I've tried both, and when I use them together, I find that collison.stoptime doesn't work, when I use Collison.action alone, it works, while StopTime alone, no matter how big I make it, doesn't work, I don't know if there is something wrong with my method or if this is a bug.

In addition, I hope he stays after collision, but I read the official document stoptime explanation, it seems to be the stoptime before collision.

**Comment by namdre** [comment]
Possibly the collision has placed both vehicles in the same location. Try to use the 'locate' menu to find the collided vehicles.

The order is this:
- vehicles collide (this gives a warning message)
- both vehicles stop for the specified time
- both vehicles are removed (this gives another warning message)

**Comment by dongjingao** [comment]
Have your issues been resolved?
