### ISSUE TITLE
Help with SUMO scenarios for heavy truck charging

### ISSUE THREAD

**Issue by ajmacmahon** [eclipse/sumo#11685]
Hello everyone,

I am new to SUMO and have very limited practice in programming. I've done some of the practices in the SUMO documentation and found out how I want to use sumo w.r.t. electric vehicles and charging stations.

For my final thesis, my university demands a SUMO scenario for analysis of future BEV truck/lorry scenarios for long distance transport. My plan is to work with an existing scenario and change it acc. to my requirements.

I found a 24h scenario for a highway section near Stuttgart in a paper, which was built with a demand based on real traffic count data (about 600k codelines). I would like to adapt and analyze this scenario - but this will hardly be possible without appropriate Python programs.

Specifically, my plan is divided into the following steps:

1. 15% of the trucks are adapted from `type="Lkw"` to `type="eLkw"`. I place charging stations at pre-defined edges.
2. I define my vType eLkw as follows

```
 <vType id="eTruck" length="9.3" ([66]) maxSpeed="24.7" ([66]) color="1,1,1">
         <param key="has.battery.device" value="true"/>
         <param key="maximumBatteryCapacity" value="336000" ([66])/>
         <param key="maximumPower" value="400000" ([66])/>
         <param key="vehicleMass" value="27000" ([66])/>
        <param key="frontSurfaceArea" value="10" [67])/>
        <param key="airDragCoefficient" value="0.521" ([67])/>
      </vType>
```

 3. I assign a state-of-charge to each vehicle of type eLkw. The format for each vehicle then looks like this:

```
<routes>
    <vehicle id="0" type="eLkw" depart="0" color="1,0,0">
        <param key="actualBatteryCapacity" value="500"/>
    </vehicle>
</routes>
```

By default, the vehicles will otherwise have half the maximumBatteryCapacity. My plan is to assign normally distributed charge states that can range from 0 to 100% of maximumBatteryCapacity.

4. I run the simulation once and use the battery-output to identify all eTruck IDs that have a SOC of 0 at the end of the simulations. This tells me which eTrucks I need to send to charge.

5. The identified IDs are then hardcoded to be sent to charging. For this, I need to give the eTrucks their stop in addition to their actualBatteryCapacity in the following format:

```
<routes>
    <vehicle id="v0" route="route0" depart="0">
        <stop chargingStation="myChargingStationID" until="50"/>
    </vehicle>
</routes>
```

6. Then I run the simulation again and evaluate the information that the charging station output gives me. If necessary, I create additional edges with charging stations to make sure the charging delays are acceptable. 

Do you think, this could work? Are there Python templates or functions I can use without having to deep-dive into Python programming to make this happen? For step 5 - can I also define a pre-set duration for charging instead of an end time (until=)? A good friend of mine was able to help me to get to step 2 - now I am stuck in step 3.

I would really appreciate your help on this since I am a little desperate and only have limited time to finish my thesis. Also, the SUMO part is only a small part of the thesis compared to the rest of the work, but mandatory for the university. Despite me being lost on this, no one from my university is properly able to help me. :(

Thanks in advance for your support!

BR

**Comment by ajmacmahon** [comment]
I should add - my practice is only limited with SUMO but especially with Python.

**Comment by namdre** [comment]
Sorry, but we cannot support you in programming your project.
The plan you outlined appears feasible in principle but you will need to acquire moderate python skills (or someone who does).
A python tool to add stops that you might adapt to your purposes is described here https://sumo.dlr.de/docs/Tools/Routes.html#addstops2routespy

In step 5 you can define a duration using stop attribute 'duration' (https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#stops_and_waypoints)

**Comment by ajmacmahon** [comment]
Thanks a lot for your tipps and advice!

Together with the help of a friend, I was able to create Python scripts to get to step 6.

Within the simulation I saw though, that not all vehicles wait in queue until it's their turn to use the charging hub.

I receive the following errors:

`Warning: Teleporting vehicle '23007058to1593663570std0.0no996.8'; waited too long (jam), lane=':591497_0_0', time=4844.00.
Warning: Vehicle '23007058to1593663570std0.0no996.8' ends teleporting on edge '29983602', time=4844.00.
Warning: Teleporting vehicle '50226592to286893192std3600.0no954.5'; waited too long (jam), lane=':593566_0_0', time=5063.00.
Warning: Vehicle '50226592to286893192std3600.0no954.5' ends teleporting on edge '29983604', time=5063.00.
Warning: Teleporting vehicle '23007058to1593663572std3600.0no599.0'; waited too long (jam), lane=':591497_0_0', time=5229.50.
Warning: Vehicle '23007058to1593663572std3600.0no599.0' ends teleporting on edge '29983602', time=5229.50.
Warning: Teleporting vehicle '50226592to286893193std3600.0no955.4'; waited too long (jam), lane=':593566_0_0', time=5409.00.
Warning: Vehicle '50226592to286893193std3600.0no955.4' ends teleporting on edge '29983604', time=5409.00.
Warning: Teleporting vehicle '23845858to1775953093std3600.0no858.5'; waited too long (jam), lane=':593566_0_0', time=5714.50.
Warning: Vehicle '23845858to1775953093std3600.0no858.5' ends teleporting on edge '29983604', time=5714.50.
Warning: Teleporting vehicle '23845858to1775953093std3600.0no858.5'; waited too long (wrong lane), lane='29983604_1', time=6018.00.
Warning: Vehicle '23845858to1775953093std3600.0no858.5' skips stop on lane '29983604_0' time=6018.00.
Warning: Vehicle '23845858to1775953093std3600.0no858.5' ends teleporting on edge '24019722', time=6018.00.
Warning: Teleporting vehicle '50226592to286893193std3600.0no955.6'; waited too long (jam), lane=':593566_0_0', time=6547.00.
Warning: Vehicle '50226592to286893193std3600.0no955.6' ends teleporting on edge '29983604', time=6547.00.
Warning: Teleporting vehicle '50226592to286893193std3600.0no955.6'; waited too long (wrong lane), lane='29983604_1', time=6850.50.
Warning: Vehicle '50226592to286893193std3600.0no955.6' skips stop on lane '29983604_0' time=6850.50.
Warning: Vehicle '50226592to286893193std3600.0no955.6' ends teleporting on edge '24019722', time=6850.50.
Warning: Teleporting vehicle '184108995to1593663570std3600.0no476.0'; waited too long (jam), lane=':591497_0_0', time=7055.50.
Warning: Vehicle '184108995to1593663570std3600.0no476.0' ends teleporting on edge '29983602', time=7055.50.
Warning: Teleporting vehicle '9548590to286893193std3600.0no364.15'; waited too long (jam), lane=':593566_0_0', time=7201.00.
Warning: Vehicle '9548590to286893193std3600.0no364.15' ends teleporting on edge '29983604', time=7201.00.`

Since my biggest interest is the to for waiting for each vehicles or rather calculating an average waiting time depending on traffic demand, I really want all vehicles to wait in line until it is their turn to charge.

Do these errors make sense to you?

Thanks in advance for your support!

**Comment by namdre** [comment]
set sumo option **--time-to-teleport -1** to disable teleporting

**Comment by ajmacmahon** [comment]
Thanks a lot!

```
<configuration >
	<input>
		<net-file value="Highway.net.xml"/>
		<route-files value="step02_out.rou.xml"/>
		<additional-files value="additionals.xml"/>
	</input>

	<time>
		<begin value="0"/>
		<end value="93600"/>
		<step-length value="0.5"/>
	</time>

	<output>
		<tripinfo-output value="tripinfo_sunday.xml"/>
		<battery-output value="battery_step02.xml"/>
    	<chargingstations-output value="chargingstations1.xml"/>
	</output>

	<report>
		<error-log value="errors_workday.xml"/>
	</report>

	<gui_only>
		<gui-settings-file value="Gui.settings.xml"/>
	</gui_only>
</configuration>
```

In which part of the SUMO configuration do I set such an option?

**Comment by namdre** [comment]
Anywhere within the `<configuration>` element is fine. The sections are not compulsory.

**Comment by ajmacmahon** [comment]
Thank you!

So it could look as follows:

```
<configuration >

--time-to-teleport -1

	<input>
		<net-file value="Highway.net.xml"/>
		<route-files value="step02_out.rou.xml"/>
		<additional-files value="additionals.xml"/>
	</input>

	<time>
		<begin value="0"/>
		<end value="93600"/>
		<step-length value="0.5"/>
	</time>

	<output>
		<tripinfo-output value="tripinfo_sunday.xml"/>
		<battery-output value="battery_step02.xml"/>
    	<chargingstations-output value="chargingstations1.xml"/>
	</output>

	<report>
		<error-log value="errors_workday.xml"/>
	</report>

	<gui_only>
		<gui-settings-file value="Gui.settings.xml"/>
	</gui_only>
</configuration>
```

**Comment by namdre** [comment]
No. You still need the brackets:
```
<configuration >
   <time-to-teleport value="-1"/>
   ...

</configuration>
```
