### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#11681]
Can SUMO generate a picture of a vehicle's trajectory at an intersection, similar to the shape of the internal lane?
I can't find the image I want in the visualization.Thank you.
![微信图片_20220923173130](https://user-images.githubusercontent.com/54823725/191932222-d2888c68-99b2-4ec7-8122-b791bb6533cb.jpg)

**SUMO-version:**

**Comment by namdre** [comment]
https://sumo.dlr.de/docs/Tools/Visualization.html#plot_trajectoriespy
with option *-t xy*

**Comment by a-123-du** [comment]
> https://sumo.dlr.de/docs/Tools/Visualization.html#plot_trajectoriespy 带有选项_-t xy_
I mean output like a picture of a macro trajectory, can you give me the command example？
![image](https://user-images.githubusercontent.com/54823725/191957831-0018a317-a727-4bdb-ba5a-309fade905c1.png)
