### ISSUE TITLE
Vehicles enter to the simulation from the middle of the road

### ISSUE THREAD

**Issue by erev-84** [eclipse/sumo#11689]
Hello,

As can be seen in the screen recording I have uploaded, vehicles enter the simulation from the middle of the road, how can I prevent this?
I tried `--fringe-factor 10`, but my problem was not solved. The vehicles still enter the simulation from the point seen in the video I uploaded.

[bandicam 2022-09-24 00-06-58-049.zip](https://github.com/eclipse/sumo/files/9637117/bandicam.2022-09-24.00-06-58-049.zip)

**Comment by namdre** [comment]
for the record: you can customize the traffic generation probabilities https://sumo.dlr.de/docs/Tools/Trip.html#customized_weights
