### ISSUE TITLE
Krauss cf model performs emergency braking

### ISSUE THREAD

**Issue by mehmetnedimyavuz** [eclipse/sumo#11695]
Add your issue description here.

*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**
Hello,
A vehicle which is governed by Krauss car following model performs emergency braking on junction. I could not figure out why 
 this vehicle performs emergency braking. Additionaly, decel value exceeds emergencyDecel="9.0" value during emergency braking. Is this possible ?(Warning: Vehicle 'hd.983' performs emergency braking on lane ':J1_0_2' with decel=10.79, wished=2.00, severity=1.26, time=1705.80.) I am using the latest development version of SUMO. I am adding files. Thank you for help,regards.
[files.zip](https://github.com/eclipse/sumo/files/9641145/files.zip)

![screen1](https://user-images.githubusercontent.com/79362739/192151958-7afbc0cb-a36b-4674-8f52-2d85c666409f.PNG)

**Comment by namdre** [comment]
The error no longer occurs in the attached scenario. Feel free to add more examples should you encounter any more Problems.
