### ISSUE TITLE
How emission values generated

### ISSUE THREAD

**Issue by erev-84** [eclipse/sumo#11692]
Hello,

I generated the emission file with command belowe, but I wonder the idea behind it. 

<output>
     <emission-output value="emission_output.xml"/>
</output>

In other words, how the CO2, CO, HC, NOx, PMx and Noise emission values are determined?

I would be glad if you can give me detailed explanation.

Thanks in advance

**Comment by namdre** [comment]
see https://elib.dlr.de/89398/
