### ISSUE TITLE
invalid results when joining junctions (trac #1169)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#1169]
when applying junctions.join to sip/tests/AIM/navteq_bs2010_Q3 the following errors are observed (when looking at the first 6 clusters)

- joining 3 junctions which lie in a line leads to far-away edges being part of the same cluster
- joining connecting edge between divided ways results in a very thin junction shape
- joining 2 junctions with offset attachments (zig-zag) results in invalid shape and may be wrong anyway
- not joining junctions even though the intermediate edge lengths are below the length-threshold and are not listed as "too complex"
- not joining junctions even though the node shapes are overlapping and the cluster doesn't look complex (junction 54534755)

Migrated from http://sumo.dlr.de/ticket/1169
```json
{
    "status": "new", 
    "changetime": "2016-04-06T07:01:22Z", 
    "description": "when applying junctions.join to sip/tests/AIM/navteq_bs2010_Q3 the following errors are observed (when looking at the first 6 clusters)\n\n- joining 3 junctions which lie in a line leads to far-away edges being part of the same cluster\n- joining connecting edge between divided ways results in a very thin junction shape\n- joining 2 junctions with offset attachments (zig-zag) results in invalid shape and may be wrong anyway\n- not joining junctions even though the intermediate edge lengths are below the length-threshold and are not listed as \"too complex\"\n- not joining junctions even though the node shapes are overlapping and the cluster doesn't look complex (junction 54534755)", 
    "reporter": "namdre", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1459926082197589", 
    "component": "net building (NETGEN, NETCONVERT)", 
    "summary": "invalid results when joining junctions", 
    "priority": "major", 
    "keywords": "", 
    "time": "2014-02-28T08:18:07Z", 
    "milestone": "1.0.0", 
    "owner": "", 
    "type": "defect"
}
```

**Comment by namdre** [comment]
the network is no longer relevant
