### ISSUE TITLE
No option with the name 'param' exists error

### ISSUE THREAD

**Issue by btopii32** [eclipse/sumo#11690]
Good day
I'm looking to write an arbitrary text at the left corner of the my sumo gui
Been trying for a while now and still nothing
Below is a screenshot of me defining the poi tag in only my sumocfg file
![poi.png](https://user-images.githubusercontent.com/57776760/192063732-3f60abd5-86bb-4045-a604-fe7d2ebb5432.png)

When Changing the visualization of poi and setting poi to show has just "PARAM_TEXT" as the only content of the drop down box. Is that a problem? How do I fix it please?

Now, this is the error that shows when I run the sumocfg file
![err.png](https://user-images.githubusercontent.com/57776760/192063785-bacc9841-6ffc-4f3e-b767-df3418364805.png)

**Comment by namdre** [comment]
pois must be loaded with option --additional-files. See https://sumo.dlr.de/docs/Simulation/Shapes.html
