### ISSUE TITLE
Conflict points at intersections

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#11691]
Can the location information of conflict points at intersections in SUMO be obtained, and how to display and mark them in the road network?（as shown below）,thank you.
![image](https://user-images.githubusercontent.com/54823725/192079041-4d0b97d5-dea3-4efb-9167-a42eb4a809b3.png)
**SUMO-version:**

**Comment by namdre** [comment]
No. This isn't currently supported.
