### ISSUE TITLE
sumo-GUI Delay cells are blank in MacOS

### ISSUE THREAD

**Issue by Kingsely-o** [eclipse/sumo#11704]
Add your issue description here.

*If possible, upload an example that shows your problem.*

**SUMO-version:1.14.1

**operating system: macOS Monterey 12.4
<img width="266" alt="截屏2022-09-27 14 47 58" src="https://user-images.githubusercontent.com/52887356/192453358-eafaa62a-7223-42c6-8f14-e9c979324b2a.png">

**Comment by angelobanse** [comment]
I don't see a bug here. I suspect you manually deleted that value (i can see that the focus is still on that input field). If you click somewhere else (thus losing that focus) a default value 0 will appear there.

@Kingsely-o can you describe the steps that got you there?
