### ISSUE TITLE
semi-implicit Euler and  ballistics

### ISSUE THREAD

**Issue by LittleWhiteRushRushRush** [eclipse/sumo#11700]
Hello, I tried to read the source code of the following model, and came across semi-implicit Euler and ballistic method, but I could not understand these two concepts well through consulting the materials. May I ask which materials you have referred to

**SUMO-version:**
1.14.1
**operating system:**
windows

**Comment by namdre** [comment]
see https://sumo.dlr.de/docs/Simulation/Basic_Definition.html#defining_the_integration_method
