### ISSUE TITLE
define a node as roundabout

### ISSUE THREAD

**Issue by axonEmily** [eclipse/sumo#11707]
Add your issue description here.
Hi, I am trying to convert a network data by another format to sumo. That data defines roundabout as a node, is there any easy way for me to convert it directly to roundabout in sumo? Thank you.
*If possible, upload an example that shows your problem.*

**SUMO-version:**
v1_14_1+1072-92085999710
**operating system:**

**Comment by namdre** [comment]
The quickest way is to modify the network manually for the nodes in question as described here:
https://sumo.dlr.de/docs/Netedit/neteditUsageExamples.html#converting_an_intersection_into_a_roundabout

**Comment by axonEmily** [comment]
ok, thanks for your help!
