### ISSUE TITLE
How to randomly generated the traffic scenario?

### ISSUE THREAD

**Issue by hesuieins** [eclipse/sumo#11732]
I want to have randomly generated traffic scenario for different simulations. And I tried to set the `traffic.rou.xml` file as shown in the figure. However, I found that I get the same output when I run the simulation for several times. I'm wondering if the distribution of traffic flows will be generated randomly for different simulation?

![image](https://user-images.githubusercontent.com/56532686/192897213-a0e11c78-c323-4d79-a674-9d8e0d761ecd.png)

**Comment by namdre** [comment]
see 
https://sumo.dlr.de/docs/FAQ.html#how_to_perform_repeated_simulations_with_different_results
