### ISSUE TITLE
lane changing problem when i do not allow lane changing before intersection

### ISSUE THREAD

**Issue by Eviannn** [eclipse/sumo#11739]
Hi dear,

I set sublane model and adjust the proper parameters, i find that if i set changeleft and changeright parameters to "authority" to disable lane changing before intersection, some vehicles can not change lane in advance (drive to straight lane but they want to turn right because blocking vehicles do not slow down) so they can not move even if the light turns green. 

However, if i do not set "authority" and allow vehicles to change lane before intersection, these vehicles can change lane in advance (blocking vehicles will slow down).

I want to keep "authority" parameters and allow vehicles change lane in advance.

hope u can help!

thank u for ur patience.

**Comment by namdre** [comment]
This is a bug. Vehicles should rather stop than enter a lane from which they cannot change (and thus cannot continue their route).
Can you provide a minimal example scenario that shows the problem?

**Comment by Eviannn** [comment]
> 



> This is a bug. Vehicles should rather stop than enter a lane from which they cannot change (and thus cannot continue their route). Can you provide a minimal example scenario that shows the problem?

thank u for ur reply!

below shows the problem.

![can not change lane](https://user-images.githubusercontent.com/89377838/193047354-a3643b33-d329-4dac-be7e-dec90874d34e.png)

![can change lane](https://user-images.githubusercontent.com/89377838/193047380-cc3bfd9c-2350-4b5b-8609-b3e331c7f5ac.png)

**Comment by namdre** [comment]
Please attach the files for running the simulation as a zip archive (preferably, adjusted to the minimum network size and amount of vehicles that are necessary to observe the problem).

**Comment by namdre** [comment]
similar to #12118 (maybe duplicate)

**Comment by namdre** [comment]
please report whether your problem still occurs after the fix to #12118.

**Comment by Eviannn** [comment]
> please report whether your problem still occurs after the fix to #12118.

Do u modify the source code to fix #12118? Or u mean set departlane="best" to fix  #12118? I am not sure

**Comment by namdre** [comment]
we modified the source code so you need to download a development version from https://sumo.dlr.de/docs/Downloads.php#nightly_snapshots

**Comment by Eviannn** [comment]
> we modified the source code so you need to download a development version from https://sumo.dlr.de/docs/Downloads.php#nightly_snapshots

thx a lot! It can fix my problem. Now the vehicle can stop before the authority lane and wait for changing lane(as vehicle can still change lane while speed=0).

And actually, I modify the code of MSAbstractLaneChangeModel.cpp(return -1 in line 842) to disallow the vehicle to change lane if it is standing, so I wonder if the vehicle can stop earlier(like some meters ahead) to make the lane changing success. 

I am not allowed to provide the example for u to test according to the company request, hope u can understand, and I totally understand that if u can not give me an answer without the example as well.

Thx again for ur patience!

**Comment by namdre** [comment]
The problem with no-lanechange-while standing is this:  
Even if the vehicle stops some meters earlier, the next time that the vehicle starts moving again it has to predict whether lane changing will succeed this time. (or it would just have to stop again, closer to the lane end). This kind of prediction is hard and the current lane changing models are not written to support this (though of course it should be possible to code this up in principle).
