### ISSUE TITLE
boardingDuration

### ISSUE THREAD

**Issue by Claudiacbh85** [eclipse/sumo#11733]
Hi,

I am developing a simulation of a public transport network (BRT system), and, I'm running into a problem with the boardingDirection function: 

The first bus that arrives at a bus stop never leaves, so the other buses "skip stop on lane" after they waited too long (wrong lane - bus xxx teleporting on edge). 

It doesn't matter how short the boarding time or what the capacity of the bus is, nor how many users are at the bus stop waiting.

Has anyone found something like this, where the first bus that arrives at a bus stop is always waiting?

SUMO-version: 1.13.0
operating system: Windows

Code:

.rou.xml:
<routes>

    <vType id="bus" accel="2.6" decel="4.5" sigma="0" length="7" minGap="3" maxSpeed="30" color="1,1,0" personCapacity="10" guiShape="bus"/>

    <flow id="bus" from = "edge1" to ="edge1" type="bus" vehsPerHour="20">
                <stop busStop="bs_0" boardingDuration="0.0001"/>
                <stop busStop="bs_1" boardingDuration="0.0001"/>
		    <stop busStop="bs_2" boardingDuration="0.0001"/>
    </flow>

    <personFlow id="AZ" begin="0" end="3600" probability="0.01" guiShape="pedestrian">
 	 <stop busStop="bs_0" />
	 <ride from="edge1" to="edge2" lines= "1"/>
    </personFlow>
.
.
.

</routes>

Thanks for your help!

**Comment by Claudiacbh85** [comment]
It's "boardingDuration"!!  sorry

**Comment by namdre** [comment]
You need to define one or more end conditions for the stop: 'duration' or 'until'. See 
https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#stops_and_waypoints
Furthermore, 'boardingDuration' is an attribute of the vType. See here for a detailed explanation of what it does: https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#available_vtype_attributes

**Comment by Claudiacbh85** [comment]
Thank you. It´s primordial that the dwell time of bus at station is function of passengers at station and capacity of the bus. So , I used both.


<vType id="bus" accel="2.6" decel="4.5" sigma="0" length="7" minGap="3" maxSpeed="30" color="1,1,0" personCapacity="10" guiShape="bus"/>

<flow id="bus" from = "edge1" to ="edge1" type="bus" vehsPerHour="20">
            <stop busStop="bs_0" duration="0" boardingDuration="0.1"/>
            <stop busStop="bs_1" duration="0" boardingDuration="0.1"/>
	    <stop busStop="bs_2" duration="0" boardingDuration="0.1"/>
</flow>

<personFlow id="AZ" begin="0" end="3600" probability="0.01" guiShape="pedestrian">
 <stop busStop="bs_0" />
 <ride from="edge1" to="edge2" lines= "1"/>
</personFlow>

**Comment by namdre** [comment]
To model the influence of passenger count on dwell time either
- set an appropriate 'duration' value (and don't simulate actual passengers)
- use 'duration' only as a minimum stopping duration, simulate passengers that ride the bus, model the speed for boarding and deboarding a single passenger with the vType attribute 'boardingDuration' for your bus
