### ISSUE TITLE
redirect / redispatch an occupied taxi while "en route"

### ISSUE THREAD

**Issue by grabouillon06** [eclipse/sumo#11740]
Hello,

Is their any way to redirect a SUMO traci taxi that has already picked up a passenger ?

the idea is that when the taxi is disptached to go to a destination, it doesn't know yet what slot it will be allocated when arriving at the destination

the decision is made while the taxi is "en route", considering what are the available slot when it will arrive

Anyway to do that ?

Thanks,

Br,

Olivier

**Comment by namdre** [comment]
re-dispatch is supported as described here: https://sumo.dlr.de/docs/Simulation/Taxi.html#dispatchtaxi
