### ISSUE TITLE
How to resume car after set stop function in traci

### ISSUE THREAD

**Issue by Thilaga22** [eclipse/sumo#11758]
Hello,
I am trying to stop my vehicle on the edge for particular duration of time and resume after the duration is over. 
I found this below traci function to stop vehicle at the particular edge,
setStop(self, vehID, edgeID, pos=1.0, laneIndex=0, duration=-1073741824.0, flags=0, startPos=-1073741824.0, until=-1073741824.0)

Here is what I want to do, 
I want the vehicle 'veh1' to stop at the edge '45645668#3' for the duration of 20 second. The length of the edge is 822.06

**My problem is ,**
Vehicle "veh1" is making a stop at the edge, but it is **not resuming** after 20 second. It is in the stop position forever and not moving at all and the simulation is not ending/closing.

My code is as below,
```
while traci.simulation.getMinExpectedNumber() > 0:
       
        traci.simulationStep();
        timestep = traci.simulation.getTime()
        vehicles=traci.vehicle.getIDList();

        for i in range(0,len(vehicles)):

                vehid = vehicles[i]
                x, y = traci.vehicle.getPosition(vehicles[i])
                coord = [x, y]
                lon, lat = traci.simulation.convertGeo(x, y)
                gpscoord = [lon, lat]
                spd = round(traci.vehicle.getSpeed(vehicles[i])*3.6,2)
                edge = traci.vehicle.getRoadID(vehicles[i])
                lane = traci.vehicle.getLaneID(vehicles[i])
                                                                                                                                                    
                traci.vehicle.setStop (vehID = "veh1",edgeID='45645668#3',laneIndex=1,pos=50,duration=20,flags=0,startPos=20)  
                #traci.vehicle.resume('veh1')                               
                                                
traci.close()
```
I am using sumo version 1.12.0, Windows 10 operating system.

Please help me to resolve this issue. 

Thanks in Advance,
Thilaga.

**Comment by namdre** [comment]
Only call `setStop` once rather than repeatedly for the same car (which renews the duration).
