### ISSUE TITLE
gtfs2pt.py bus stops located at wrong edges

### ISSUE THREAD

**Issue by alexrsanchez** [eclipse/sumo#11759]
I am using the gtfs2pt script to obtain public transport routes and I have noticed that there are notable differences between real and simulated routes.
After some research, I have noticed that -inside my particular simulation domain- some bus stops are placed in wrong edges. This often happens when 2 buses stops have the same name on the "stops.txt" GTFS file but one uses one street direction and the other in opposite direction.
However, the coordinates for the wrong bus stops in the "stops.txt" file are correct, so I don't really understand why it is not located at its corresponding edge. This mistake on bus stops location is creating wrong routes. 
No matter how I manually adjust the wrong bus stop's coordinates, it won't change to the correct edge (it do changes lane position). An example of this behaviour is illustrated in the attached image.

![Bad_busstop_location](https://user-images.githubusercontent.com/72650160/193749755-5caab8ef-9276-4901-afa4-0338bb8d2eb9.png)

**SUMO-version: 1.13.0**

**operating system: Linux**

**Comment by m-kro** [comment]
Could you provide the input files to reproduce the problem?

**Comment by alexrsanchez** [comment]
Here you can find the input files used for gtfs2py script, and also the output files I got in case you need them.

[GTFS_issues_SUMO.zip](https://github.com/eclipse/sumo/files/9703682/GTFS_issues_SUMO.zip)

**Comment by m-kro** [comment]
The stop in question is "via Lusitana - Coimbra", right? Strange but I cannot reproduce the problem, neither with the script from v1.13 nor with the current dev version... Also the file "gtfs_publictransport.add.xml" you provided as output doesn't show the stop from the screenshot. Am I missing something?

**Comment by alexrsanchez** [comment]
It is indeed that bus stop, and after trying again with this data it works fine to me. That's my bad!

However, there are still some weird behaviours I cannot solve:
1. When a bus stop is nearby an intersection and its length is larger than the busstop_StartPos minus intersection_StartPos quantity, instead of relocating the bus stop further away on the same edge (so its lenght was shorter than the startPos-intersection distance), another bus stop is created at the other side of the intersection (see image). So there is an "artificial" bus stop that is selectionable by buses, creating wrong routes.
2. In the "stops.txt" file, there are 3 bus stops named "Intercambiador Plaza Elíptica". However, in SUMO there is a fourth (fifth if you count the previously mentioned duplicated bus stop as another one) bus stop with that name, and that shoudn't exist at all, as there are no bus stops at the street it is located. I haven't been able to remove it, I don't know if this is related to the issue in 1.
![False_bus_stop](https://user-images.githubusercontent.com/72650160/193774352-0012e360-9b63-4e54-b936-d8c6508b1747.png)

**Comment by m-kro** [comment]
Same again, I cannot reproduce it - I get three stops as expected. Can you check whether the GTFS files you supplied are the same you used before? In the header of the gtfs2pt.py output you select March 1 as date but the GTFS data covers timetable from September on...

**Comment by alexrsanchez** [comment]
Yes, it seems the GTFS data starts on September. However, even selecting September I cannot get rid of the unrealistic bus stop at edge 27497569#1

**Comment by alexrsanchez** [comment]
With SUMO 1.14.1 the problem is solved, thanks for your help!

Just one last question. Now I have noticed that I can reproduce the error from the following thread using v1.14.1:
https://www.eclipse.org/lists/sumo-user/msg12221.html

For example:
**gtfs_pt_vehicles.add.xml file**
    <vehicle id="6_LA0060011.0" **route="LA0060011"** type="busesMadridZBE" depart="19769" line="6_LA0060011"/>

**gtfs_pt_stops.add.xml file**
<**route id="6_LA0060011"** edges="-71443112 -43797370#6 -43797370#5 -43797370#4 -43797370#3 -43797370#2 -43797370#0 -785349564#0 -785349565#2 -785349565#1 27048213#0 27048213#1 27048213#2 27048213#4 27048213#5 27048213#6">
[...]
    </route>

There are inconsistencies on route names between gtfs files. Has it been fixed in the development releases?
