### ISSUE TITLE
Retrieving information from network file

### ISSUE THREAD

**Issue by erev-84** [eclipse/sumo#11753]
Hello,

Is there have any ready to use script or way to retrieve the following informations from the network file?

1. Area of network in km2
2. Total length of all roads in km
3. Total length of highways in km
4. Number of intersections
5. Number of traffic lights

Thanks in advance

**Comment by namdre** [comment]
not ready made but fairly easy to retrieve with https://sumo.dlr.de/docs/Tools/Sumolib.html

**Comment by erev-84** [comment]
Hello @namdre 

Could you tell me what type code should I use? I am sorry but I did not understand what should I do exactly and I would be glad if you can help me to the retrieve the informations I mentioned in my First post.

Thanks
