### ISSUE TITLE
"Disregard safe speed mode" not working ?

### ISSUE THREAD

**Issue by ssooffiiaannee** [eclipse/sumo#11756]
I am trying to spawn two vehicles with a departSpeed = MaxSpeed = 25 m/s, one at departPos = 110 the other at 100 (distance between the two is 10 and should not change).

I found that the initial speed of the second (following) vehicle is not 25 m/s, it starts with a lesser speed and increases with the distance between the two vehicles until 25 m/s.

I thought by disabling the "safe speed mode" of vehicle v2 by setting the first bit to 0 will solve the problem, but it is not. What am I missing?

```
<routes>
	<vType decel="9.81" sigma="0" id="t1" maxSpeed="25" minGap="0"/>
	<route id="route0" edges="gneE0"/>
	<vehicle id="v1" type="t1" depart="0" route="route0" departPos="110" departSpeed="max"/>
	<vehicle id="v2" type="t1" depart="0" route="route0" departPos="100" departSpeed="max"/>
</routes>
```
**SUMO-version:**
1.14.1
**operating system:**
Linux Ubuntu 20

**Comment by namdre** [comment]
speed mode is only applied on subsequent calls to 'setSpeed' or 'slowDown'.
If you want to force unsafe insertion, either force the vehicle into the network with 'moveTo'  or use vehicle attribute `insertionChecks="none"` (see https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#available_vehicle_attributes)
