### ISSUE TITLE
add functions to add / remove views

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#11760]
traci.gui.addView(viewID,  settingsID="")
traci.gui.removeView(viewID)

**Comment by ricardofdc** [comment]
I'm getting the following error:

self.sumo.gui.addView(self.id)
AttributeError: 'GuiDomain' object has no attribute 'addView'

why is this happening? what should I do to add a View? Do I need to update something?

**Comment by namdre** [comment]
You need the dev version (https://sumo.dlr.de/docs/Downloads.php#nightly_snapshots)
