### ISSUE TITLE
trying to understand how getLeader is estimated.

### ISSUE THREAD

**Issue by Oritchimaru** [eclipse/sumo#11768]
Hello I'm trying to understand reading the documentation how exactly the leading vehicle is calculated and returned from traci.vehicle.getLeader(args) function.

I seem to get vehicles really far away from my ego vehicle, sometimes not even one the same lane or road.

Is it calculated following some collision prediction or what are the rules that getLeader function follows?

Thanks in advance!

**Comment by namdre** [comment]
the function returns the leader by looking ahead along the current lane (regardless of how long that lane is) and possibly ahead on subsequent lanes. The observed distance along subsequent lanes depends on the `dist` parameter in the following way:

- if dist is given as 0 (the default) it is initialized to the braking distance (including reaction time tau)
- as long as the distance along observed lanes is less than `dist`, more lanes are checked
- the maximum distance than may be observed is limited by the planning horizon of the vehicle. This is at least the braking distance and at least 8 lanes or 3000m 

Thus, `dist` acts as a *lower* bound on observed distance.
