### ISSUE TITLE
sumo traci doesn't read my first signal phase and only read some seconds of second phase

### ISSUE THREAD

**Issue by jamanah** [eclipse/sumo#11765]
I tried to change my traffic signal program whenever the detector detects an emergency vehicle. In other words, whenever the traffic light for the approaching direction of the emergency vehicle is not green, the light on the green approach will be changed to yellow (and consequently red), and the approaching direction of the emergency vehicle will get green.

The additional program in add.xml file is as follows:

    <tlLogic id="J1" programID="P1" offset="0" type="static">
      <phase duration="3"  state="rrrryyyrrrrryyyr" /> 
      <phase duration="33" state="GGGrrrrrGGGrrrrr"/> 
      <phase duration="3"  state="yyyrrrrryyyrrrrr"/> 
      <phase duration="6"  state="rrrGrrrrrrrGrrrr"/> 
      <phase duration="3"  state="rrryrrrrrrryrrrr"/> 
      <phase duration="33" state="rrrrGGGrrrrrGGGr"/> 
      <phase duration="3"  state="rrrryyyrrrrryyyr"/> 
      <phase duration="6"  state="rrrrrrrGrrrrrrrG"/> 
      <phase duration="3"  state="rrrrrrryrrrrrrry"/> 

    </tlLogic>

The python code is as follows:

        for veh in det_vehs:     
            if traci.vehicle.getTypeID(veh) == "ev":
                if traci.vehicle.getRoadID(veh) == "nb1":
                    aa.append(step)
                    p1=next(t for t in aa if t)
                    print(p1)
                    if traci.trafficlight.getRedYellowGreenState("J1") != "GGGrrrrrGGGrrrrr":
                        PH = traci.trafficlight.getRedYellowGreenState("J1")
                        if step <= int(p1):
                            if PH == "rrrrGGGrrrrrGGGr":
                                traci.trafficlight.setProgram("J1", "P1") 
            step += 1

The problem that I have with this code is that the sumo will run this new signal program, but it will not read the first phase ( rrrryyyrrrrryyyr) and the second phase (GGGrrrrrGGGrrrrr), is run for 8 seconds (I need to change it to 58 seconds in the program to run for 33 seconds actually, which is not meaningful. I will be grateful if you can help me.

**SUMO-version: 1.14.1

**operating system: Windows

**Comment by jamanah** [comment]
@namdre @behrisch

**Comment by namdre** [comment]
All loaded programs are continuously advancing through the phases even while inactive. Thus, the exact state you get when calling `setProgram` depends on the time at which you call this function.  You can follow up with `setPhase` and `setPhaseDuration`  after switching to the new program.

See also https://sumo.dlr.de/docs/Simulation/Traffic_Lights.html#controlling_traffic_lights_via_traci

**Comment by jamanah** [comment]
Thanks for your reply. It helped me. I have a question. How can I change the next phase duration? (Since setPhaseDuration only changes the duration of the current phase).

**Comment by jamanah** [comment]
@namdre

**Comment by namdre** [comment]
the easiest solution is to wait until the traffic light switches into the next phase and then call setPhaseDuration.
