### ISSUE TITLE
Error: Driving in Circles with different bus lines and stop at several bus stops

### ISSUE THREAD

**Issue by Claudiacbh85** [eclipse/sumo#11777]
Hello.

I need to create a public transport system with buses from different lines. These buses stop at several bus stops and drive in circles (buses running around a loop given by their line). 

This is part of the code in .rou (for line 1):

    <vType id="bus1" vClass="bus" accel="2.6" decel="4.5" sigma="0" length="7" minGap="3" maxSpeed="30" color="1,1,0" personCapacity="50" guiShape="bus"/>
    <route id="bus_1" edges = "edge1 E1 E2 E3 E4 E5 E6 E7 E8 E9 E10 E11 edge2 E13 E14 E15 E16 E17 E18 E19 E20 E21 E22 E23 edge1" repeat="3">
               <stop busStop="bs_0_1" duration="0" boardingDuration="1"/>
               <stop busStop="bs_1_1" duration="0" boardingDuration="1"/>
               <stop busStop="bs_2" duration="0" boardingDuration="1"/>
               <stop busStop="bs_222_1" duration="0"  boardingDuration="1"/>
               <stop busStop="bs_555" duration="0" boardingDuration="1"/>
               <stop busStop="bs_3_1" duration="0" boardingDuration="1"/>
    </route>
    <flow id="bus_1" type="bus1" route="bus_1" begin="0.0" end="3600.0" number="30" line="1" />

This is what I’m getting in Sumo:   Error: Disconnected route 'bus_1' when repeating.

I tried to create a rerouter, but it doesn't work with multiple lines that stop at bus stops.

How can I correct this error and make buses drive in circles (buses running around a loop given by their line)?

Thank you!!

SUMO-version: 1.13.0

Operating system: Windows

**Comment by namdre** [comment]
remove the final `edge1` in edges of the route (it will automatically continue on that edge due to the `repeat` number).

**Comment by namdre** [comment]
note that `boardingDuration` refers to the time that a single passenger takes for boarding. If you do not simulate passengers, the bus will not stop for more than 1 step.

**Comment by Claudiacbh85** [comment]
Thank you very much!! It works very well.
