### ISSUE TITLE
simpla reporting fails handling None value

### ISSUE THREAD

**Issue by thinker310** [eclipse/sumo#11789]
Hello, I'm trying to using simpla to platooning vehicles in SUMO. However, there are two problems happended. 
![1665250221753](https://user-images.githubusercontent.com/62609436/194720310-6a46c434-30cb-4d77-a159-5b79cdc2303a.png)
For the picture above, firstly, I did not figure out what the error means and I hope someone could explain it for me. Then, I found that the code on line 52 did not exist in the source code file step.py, as the picture bleow shown.
![1665250777028](https://user-images.githubusercontent.com/62609436/194720502-d3a7050a-d69a-4f9b-bd0c-5bcc8931c344.png)
Could you help me find the source file? Thank you in advance!

**Comment by m-kro** [comment]
It is probably caused by 

https://github.com/eclipse/sumo/blob/fce39c43800abe3238fa62516777af119bd7690c/tools/simpla/_reporting.py#L52

Could you please prepare a small example and attach it here to replicate your problem on our side?

**Comment by thinker310** [comment]
> It is probably caused by
> 
> https://github.com/eclipse/sumo/blob/fce39c43800abe3238fa62516777af119bd7690c/tools/simpla/_reporting.py#L52
> 
> Could you please prepare a small exa
mple and attach it here to replicate your problem on our side?

OK, I tried it again with your tips but I failed. The attachment is a case with codes. The vehicle order in the platoon may be wrong according to the error.

[example.tar.gz](https://github.com/eclipse/sumo/files/9747394/example.tar.gz)

**Comment by m-kro** [comment]
@thinker310 : Thank you for providing the example. The problem with the simpla log has been solved. You can grab the updated file sumo/tools/simpla/_reporting.py directly here on Github or download the developer version snapshot tomorrow.

**Comment by thinker310** [comment]
> @thinker310 : Thank you for providing the example. The problem with the simpla log has been solved. You can grab the updated file sumo/tools/simpla/_reporting.py directly here on Github or download the developer version snapshot tomorrow.

Thank you for your help! I ran it with another rou.xml file 
but another Nonetype problem happened. The new attachment is here:
[Nonetype_problem.zip](https://github.com/eclipse/sumo/files/9754163/Nonetype_problem.zip)
Could you check this bug?
Thank you again!

**Comment by m-kro** [comment]
@thinker310 : Please open a new issue next time you encounter a separate problem from the one you discussed before. In this case, I cannot reproduce it. Which version of SUMO do you use?

**Comment by thinker310** [comment]
> @thinker310 : Please open a new issue next time you encounter a separate problem from the one you discussed before. In this case, I cannot reproduce it. Which version of SUMO do you use?

Ok. I use SUMO 1.14. I did not find the problem for reproduction and I recompress the files by tar.
[Nonetype_problem.tar.gz](https://github.com/eclipse/sumo/files/9754795/Nonetype_problem.tar.gz)

**Comment by m-kro** [comment]
Was solvedin issue #11223 . Please update to SUMO v1.14.1 or to the developer version.
