### ISSUE TITLE
add <neigh lane=""/> tag into netfile , the netedit will be crash 

### ISSUE THREAD

**Issue by skrillexxu** [eclipse/sumo#11785]
**SUMO-version:** 1.14.1

**operating system:** windows10

**Comment by namdre** [comment]
never edit the net.xml directly (https://sumo.dlr.de/docs/FAQ.html#i_made_changes_to_the_netxml-file_but_it_did_not_work_as_expected_why)

see the updated documentation at  https://sumo.dlr.de/docs/Simulation/OppositeDirectionDriving.html#building_a_network_for_opposite-direction-driving
