### ISSUE TITLE
sublane model problem

### ISSUE THREAD

**Issue by Eviannn** [eclipse/sumo#11786]
hi dear,

I used sublane model and tried to adjust all kinds of parameters, but i find that there are always vehicles crossing the solid line (i set "authority" for changeleft and changeright attributes) before the intersection to wait the traffic light turn green, i hope that no vehicle can cross the solid line but failed, hope u can help!

thank u for ur patience!

**Comment by namdre** [comment]
can you attach a zip archive with a minimal example that shows your problem?

**Comment by Eviannn** [comment]
> 
thank u for ur reply, below shows the problem.
![屏幕截图 2022-10-09 085758](https://user-images.githubusercontent.com/89377838/194732668-28b3decf-e5ba-4e06-8612-3e23095e7641.png)

**Comment by namdre** [comment]
can you briefly state how you fixed your problem?

**Comment by Eviannn** [comment]
> can you briefly state how you fixed your problem?

hi at the beginning I split one lane into 5 sublanes (0.7/3.5) so the issue happened, later I tried to split into 2 sublanes (1.75/3.5), I found that in the 2 situations, trajectories are similar and the problem would never occur, so I used 2 sublanes to simulate lateral behavior to make it look like much more real.
