### ISSUE TITLE
Distance

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#11784]
How does SUMO get the distance from the current edge start or How does SUMO get the distance from the current EDGE stop line？（for example the distance from the vehicle to the pointA）
![image](https://user-images.githubusercontent.com/54823725/194685476-355c0459-cc58-4e4d-9ccd-ff35b4eec968.png)

**SUMO-version:**

**Comment by namdre** [comment]
it sums up the length attribute of the involved lanes and subtracts the offset values (i.e. current vehicle position along the lane, offset of the target position)
