### ISSUE TITLE
Use randomTrips.py to generate random trips with predefined starting and ending edges

### ISSUE THREAD

**Issue by corinnegroth** [eclipse/sumo#11782]
I am having troubles using randomTrips.py to generate trips with predefined start and end edges using the argument
'python tools/randomTrips.py --weights-prefix example'. It appears that randomTrips.py generates trips with a specific start and random destinations or random starts and a specific destination. I would like to be able to have a specific start edge and a specific end edge, with random via edges. Is this possible?

SUMO 1.14.1

Windows

**Comment by namdre** [comment]
you need two weight files:
- a .src.xml file that puts all the weight on the desired origin edge
- a dst.xml file that puts all the weight  on the desired destination edge

**Comment by corinnegroth** [comment]
I have done that and it's still not working. The trips.trips.xml file and example.rou.xml files still produce random starting and ending edges.

I have attached the files I am currently using and what randomTrips.py is returning.
[example.zip](https://github.com/eclipse/sumo/files/9767832/example.zip)

**Comment by behrisch** [comment]
The call `$SUMO_HOME/tools/randomTrips.py -n example.net.xml --weights-prefix example` works just fine here. Telling from your output file you probably did not have the example.src and .dst in your working directory so they were not found and randomTrips did not mention that. This is a bug. There should be at least a warning

**Comment by corinnegroth** [comment]
I did that, but now all the vehicles are taking the same path.

**Comment by behrisch** [comment]
randomTrips just chooses random origins and destinations, _not_ random routes between them. Try adding random vias using `--intermediate 1` (or a higher number depending how many detours you want).

**Comment by namdre** [comment]
alternatively, set randomTrips option **--random-routing-factor X** (i.e. X=2) to disturb the add noise to the route search.
