### ISSUE TITLE
lanechange model problem

### ISSUE THREAD

**Issue by Viloa13** [eclipse/sumo#11787]
Hi,

I'd like to be able to control the lane change in the sumo by turning the corner. Can Sumo add a Vehicle dynamics model? 
Or how does the sumo reflect the change in wheel corners when changing lanes? Does it need to be implemented in conjunction with other simulation software such as MATLAB and Simulink?

hope u can help!

thank u for ur patience.

**SUMO-version: 1.13.0**

**operating system: Windows**

**Comment by namdre** [comment]
SUMO does not include a driving dynamics simulation (i.e. with steering angle, slippage etc.)  You can achieve full remote control over dynamics via TraCI at different granularites (traci.vehicle.changeSublane, traci.vehicle.moveToXY) .

Can you describe your use case in more detail?

**Comment by Viloa13** [comment]
My use case mainly used DRL algorithms to control vehicle lane changes in SUMO. I have now achieved lane changes via TraCI, but I saw that in SUMO lane changes are instantaneous and are done sideways from lane to lane. I wonder if sumo can change lanes by controlling the corner of the vehicle.  If sumo can't, can I combine SUMO and Vehicle dynamics in another simulation software such as Simulink to control lane changes?

**Comment by Viloa13** [comment]
> My use case mainly used DRL algorithms to control vehicle lane changes in SUMO. I have now achieved lane changes via TraCI, but I saw that in SUMO lane changes are instantaneous and are done sideways from lane to lane. I wonder if sumo can change lanes by controlling the corner of the vehicle. If sumo can't, can I combine SUMO and Vehicle dynamics in another simulation software such as Simulink to control lane changes?

**Comment by Viloa13** [comment]
> SUMO does not include a driving dynamics simulation (i.e. with steering angle, slippage etc.) You can achieve full remote control over dynamics via TraCI at different granularites (traci.vehicle.changeSublane, traci.vehicle.moveToXY) .
> 
> Can you describe your use case in more detail?

My use case mainly used DRL algorithms to control vehicle lane changes in SUMO. I have now achieved lane changes via TraCI, but I saw that in SUMO lane changes are instantaneous and are done sideways from lane to lane. I wonder if sumo can change lanes by controlling the corner of the vehicle. If sumo can't, can I combine SUMO and Vehicle dynamics in another simulation software such as Simulink to control lane changes?

**Comment by namdre** [comment]
only the fast default model has instant lane changing. There are two alternative modes you can activate for gradual lane changing: https://sumo.dlr.de/docs/Simulation/SublaneModel.html

**Comment by Viloa13** [comment]
> only the fast default model has instant lane changing. There are two alternative modes you can activate for gradual lane changing: https://sumo.dlr.de/docs/Simulation/SublaneModel.html

Ok, I've set up SublaneModel. 
The last question, is this gradual lane change just a visual effect? If not, what controls were used to change lanes? Is it possible to calculate the deflection angle between the front and center lines when changing lanes?

**Comment by namdre** [comment]
it's not just a visual effect, the vehicle occupies space on both lanes during the lanechange at the change itself lasts longer to finish. The angle is computed based on old a new vehicle positions rather than on a steering wheel model. You can use fcd-output to log the angle.
