### ISSUE TITLE
How to get turn or target lane?

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#11796]
How do you know in advance what direction a vehicle is turning before it enters an intersection, or what lane it is going to be in？

**SUMO-version:**

**Comment by namdre** [comment]
`traci.vehicle.getBestLanes`

 https://github.com/eclipse/sumo/blob/927cac5dee86cf7e54c75fd30a49ccf9655ee729/tools/traci/_vehicle.py#L532-L548

**Comment by a-123-du** [comment]
> 

May be not this.Sorry,I'm talking about the destination lane to get the car, the only lane to go to, not the lane he might go to.Can I get the direction or the destination lane ID of the car?

**Comment by namdre** [comment]
nextLane is `vehicle.getBestLanes(vehID)[vehicle.getLaneIndex(vehID)][-1][1]`

**Comment by namdre** [comment]
if the vehicle is on the lane before the intersection, than the code I gave will output the next normal lane (bestLanes only returns normal lanes)
