### ISSUE TITLE
setStop()

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#11790]
Can I use traci.vehicle.setStop() to stop the vehicle at the internal lane of the intersection?(The picture below shows the internal lane),thank you
![image](https://user-images.githubusercontent.com/54823725/194740297-1b548f48-9b29-4d7e-bb14-d9399e925f8e.png)

**SUMO-version:**

**Comment by namdre** [comment]
yes. You can use internal edge ids. See https://sumo.dlr.de/docs/sumo-gui.html#investigating_internal_edges_and_lanes
