### ISSUE TITLE
set up the pedestrian model

### ISSUE THREAD

**Issue by callmorn** [eclipse/sumo#11793]
I knew there were two pedestrian models, including ‘’nonInteracting” and “striping”, but I didn't know which file to set up the pedestrian model in

**Comment by namdre** [comment]
1. the documentation tells you that you can set the model "by using the simulation option --pedestrian.model*. This is a command line option but you can put the corresponding option <pedestrian.model value="nonInteracting"/> into a .sumocfg.
2. Please don't open up a new issue if you still have questions for the old one. Simply add comments there (i.e. #11788)
