### ISSUE TITLE
.netconvert command not found on mac terminal.

### ISSUE THREAD

**Issue by XZIBIT93** [eclipse/sumo#11795]
Hello ,

I am trying to use netconvert convert command on my mac from the specific folder path so as to compile my edge, node and type files but am unable to do so. Can someone kindly tell me a remedy. 
![Screenshot 2022-10-10 at 12 53 10 AM](https://user-images.githubusercontent.com/90576874/194783233-540a7f5a-6a04-4385-9631-ffa8128a9769.png)

**Comment by namdre** [comment]
Either use the full path to netconvert or add `$SUMO_HOME/bin` to your `PATH` variable. 
See https://sumo.dlr.de/docs/Basics/Basic_Computer_Skills.html#sumo_home

**Comment by rays236** [comment]
I am facing same issue while converting the files.
I am confused about the path that's required. I cannot locate the path to netconvert. My Sumo folder contains only the files I generated via OSM Scenario Wizard.
<img width="1082" alt="Image" src="https://github.com/user-attachments/assets/5566e5f3-70b5-4c04-a7c2-857da6533bef" />
