### ISSUE TITLE
netconvert crashes 

### ISSUE THREAD

**Issue by ambuehll** [eclipse/sumo#11803]
using my standard netcfg file crashes for an OSM network.

[files](https://drive.google.com/drive/folders/19oucm2SxITzFftwCIcNjhdxTC1XB5rrD?usp=sharing
)

**SUMO-version:**v1_14_1+1474

**operating system:**Win

**Comment by ambuehll** [comment]
does not crash in 1.14.0

**Comment by namdre** [comment]
still occurs with v1_14_1+1584 so its *not* a duplicate of #11779

**Comment by namdre** [comment]
[diff.platformID.txt](https://github.com/eclipse/sumo/files/9754050/diff.platformID.txt)

(debugging diff stored here in case of future need)
