### ISSUE TITLE
Call the TraCi interface to get the basic parameters of an edge.

### ISSUE THREAD

**Issue by ywq178** [eclipse/sumo#11807]
Add your issue description here.
Hello,
Can I get the basic parameters of an edge, such as the length of the edge, its from node, and its to node, by calling the TraCi interface?
*If possible, upload an example that shows your problem.*

**SUMO-version:**
1.11.0
**operating system:**

**Comment by m-kro** [comment]
You can use [sumolib](https://sumo.dlr.de/docs/Tools/Sumolib.html#import_a_network_and_retrieve_nodes_and_edges) for queries about static network data (TraCI is meant mostly for dynamic data / which may change during the simulation). You can find the sumolib reference [here](https://sumo.dlr.de/pydoc/sumolib.html) and the edge-related methods [there](https://sumo.dlr.de/pydoc/sumolib.net.edge.html).

**Comment by ywq178** [comment]
Thank you!
