### ISSUE TITLE
gtfs2pt.py places bus stops on pedestrian lane

### ISSUE THREAD

**Issue by m-kro** [eclipse/sumo#11802]
Discovered in the network from #11759 . For example "Rafaela Ybarra -  Pradolongo" on lane -71443112_0. This seems to be a consequence of the typed networks generated by the script. There netconvert is called to dismiss vClass data?!

https://github.com/eclipse/sumo/blob/9630bff95a2b43733eeebdd462efc2faf291c479/tools/import/gtfs/gtfs2pt.py#L164-L166

**Comment by namdre** [comment]
the assumption here is that only edges for a specific class remain and then the vClass data can be dismissed. Multi-modal edges violate this assumption.
