### ISSUE TITLE
remove short route id from vehicle id in gtfs2pt

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#11819]
It helps in identifying the vehicle but it may contain invalid characters such as spaces. Rather add a param for the short route id which can be visualized as well

**Comment by namdre** [comment]
can this be closed?

**Comment by behrisch** [comment]
still needs a test

**Comment by namdre** [comment]
it might be useful to put the short and long line id into params instead of comments so they can be checked in the gui
