### ISSUE TITLE
Automatic routing error

### ISSUE THREAD

**Issue by jamanah** [eclipse/sumo#11810]
I would like to do automatic routing for a vehicle. When I define a trip, including origin edge id and destination edge id in the route.xml file as follows:

<trip id="t1" depart="16" from="nb1" to="eb3"/>

<vehicle id="ev_0" type="ev" depart="16" route="t1" departSpeed="max"/>

I get the following error:

Error: The route 't1' for vehicle 'ev_0' is not known.

1) How can I fix the problem by giving the original edge and destination edge and letting the automatic routing decide middle edges?

2) How can I give original and destination junctions instead of edges?

**SUMO-version: 1.14.1

**operating system: windows

**Comment by jamanah** [comment]
@namdre

**Comment by namdre** [comment]
1. If you define a trip, there should be no route id anywhere. (i.e. `<trip id="t" depart="0" from="beg" to="end"/>`)
2. https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#routing_between_junctions

**Comment by jamanah** [comment]
If I want to write no route id:
( ie., <trip id="t1" depart="16" from="nb1" to="eb3"/>
<vehicle id="ev_0" type="ev" depart="16" trip="t1" departSpeed="max"/>)

I still get the following error:

Error: Vehicle 'ev_0' has no route.

**Comment by jamanah** [comment]
If I want to write no route id:
trip id="t1" depart="16" from="nb1" to="eb3"
vehicle id="ev_0" type="ev" depart="16" trip="t1" departSpeed="max"

I still get the following error:

Error: Vehicle 'ev_0' has no route.

**Comment by jamanah** [comment]
@namdre

**Comment by namdre** [comment]
vehicles need a route. See https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#vehicles_and_routes

It might be easier to define your traffic with netedit until you become familiar with the xml.

**Comment by jamanah** [comment]
I think you didn't understand what I mean. I worked with the following route.xml file that I created and it works before adding automatic routing

routes>

vType id="ev"
      vClass="emergency" length="7" accel="2.2" decel="3.2" sigma="0.5"
      maxSpeed="24.6" guiShape="emergency" minspeed="0.0"/>

route id="route_1" edges="E1 nb1 eb2 eb3" speedLimit="20"/>

vehicle id="ev_0" type="ev" depart="16" route="route_1" departSpeed="max"/>

However, I wanted to define a trip instead of above route with just origin and destination edges so that the automatic routing decides the best route for "ev_0" based on travel time which didn't work. 

1) When we define the route, including all edges, is it possible that automatic routing chooses another middle edge if travel times become better or it follows the route and doesn't change any edges?

2) Could you please write/let me know how I can define a trip for "ev_0" with origin edge "E1" and destination edge "eb3" so that automatic routing decides the middle edges?

**Comment by namdre** [comment]
1. yes, see https://sumo.dlr.de/docs/Demand/Automatic_Routing.html
2. `<trip id="ev_0" type="ev" depart="16" departSpeed="max" from="E1" to="eb3"/>`       (and neither a `<route>` nor `<vehicle>`)

**Comment by jamanah** [comment]
@namdre 

Thank you very much for your response. I have 2 questions.

1) For automatic routing, do we need rerouters, or it doesn't need anything?
2) How can we get the route/updated route edges as soon as the vehicle path changes the route while we are running the simulation, not after it is done?

**Comment by namdre** [comment]
1. rerouters are an alternative method to change routes but 'automatic routing' works independently.
2. `traci.vehicle.getRoute` returns the latest list of edges

**Comment by namdre** [comment]
1. yes, unless changed via option **--routing-algorithm**
2.
  a) vehroute-output will hold the list of all routes that each vehicle chose during the simulation. However, if the routes do not change (i.e. because the traffic conditions do not change). Also, verbose output lists the number of times that the routing algorithm has run
  b) yes. though it only proves that the route was computed once whereas period rerouting will recompute the route repeatedly.

**Comment by jamanah** [comment]
Thank you very much, Jakob! As you mentioned, I set the verbose format using:
 report>
    verbose value="true"/>
 report>

1) What type of file do I need to write in the output to list the number of times the routing algorithm has run? Could you please write the code line for that?

2) I used "device.rerouting.output" to list the number of times that the routing algorithm has run, but it gives me the travel time for every second; however, I set the "device.rerouting.period" value for every 10 seconds. Could you explain why?

**Comment by namdre** [comment]
1. **--log LOGFILE**
2. rerouting.output shows the result for *updating* the travel time estimation which is different from the rerouting period. The former is configured with **--device.rerouting.adaptation-interval**

**Comment by jamanah** [comment]
@namdre 

Thank you very much for your response and support. 

1) Based on the log file:
"DijkstraRouter answered 109 queries and explored 7.48 edges on average"
My simulation time is 210, and the rerouting period is 10. Why the number of queries is not 210/10 = 21 * 7.48 = 157
How the sumo calculates queries?

2) "DijkstraRouter spent 0.00s answering queries (0.01ms on average)."
0.01 ms is the average delay in running sumo for each routing, right?

3) Can we do the automatic routing based on distance instead of periodic-based? In other words, for instance, the rerouting for vehicle x will be iterated every 20 meters.
