### ISSUE TITLE
internal lane display and drawing on the internal lane

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#11822]
Does sumo support the display of internal lanes during emulation? One more question: Can rectangles be drawn and displayed on the internal lanes at intersections?
**SUMO-version:**

**Comment by m-kro** [comment]
Yes:
- press [F9] or click on the rainbow icon
- select Junctions tab
- unselect "Draw junction shape"

What kind of rectangle do you mean?

**Comment by a-123-du** [comment]
> Yes:
> 
> * press [F9] or click on the rainbow icon
> * select Junctions tab
> * unselect "Draw junction shape"
> 
> What kind of rectangle do you mean?
After following the steps you said, the intersection will not be shown, as shown in Figure 1.
![9a103ea1f21d57223c9ca04ea70c2a8](https://user-images.githubusercontent.com/54823725/195521879-3bf35268-8c07-4636-805f-23979da75a57.png)
 My question is can the internal lane (or connection) be shown in the simulation on sumo-gui?

**Comment by namdre** [comment]
The network you have was built without internal lanes. See https://sumo.dlr.de/docs/Simulation/Intersections.html#netconvert-option_--no-internal-links

To change this run
`netconvert -s old.net.xml --no-internal-links false -o new.net.xml`

**Comment by a-123-du** [comment]
> The network you have was built without internal lanes. See https://sumo.dlr.de/docs/Simulation/Intersections.html#netconvert-option_--no-internal-links
> 
> To change this run `netconvert -s old.net.xml --no-internal-links false -o new.net.xml`
There are internal lanes in the construction of my network, but I would like to ask how do the internal lanes or connections show up in the simulator while the vehicle is moving?
![image](https://user-images.githubusercontent.com/54823725/195530433-1bbaaf23-caa6-4034-af68-8365ecf999cd.png)

**Comment by namdre** [comment]
take the steps listed by mirko in sumo-gui or press ctrl+J to toggle junction drawing.
