### ISSUE TITLE
travelled distance

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#11823]
When a vehicle is moving from the midpoint of the source lane to the destination lane, how can it obtain the distance travelled from the midpoint of the stop line to a certain point on the internal lane while driving along the internal lane in the intersection?
![image](https://user-images.githubusercontent.com/54823725/195492652-c8083560-c5b8-40b5-9c7f-4c0a4ad151b2.png)

**SUMO-version:**

**Comment by a-123-du** [comment]
?

**Comment by namdre** [comment]
Internally, the vehicle always tracks the offset along it's current lane. This is what `traci.vehicle.getLanePosition` returns (also all relevant target points are encoded as offsets). The x,y position is computed from the offset (and mostly for visualization).

You can match x,y position to an offset using `traci.simulation.convertRoad(x, y)`
