### ISSUE TITLE
OSM is not opening 

### ISSUE THREAD

**Issue by tamewadihu** [eclipse/sumo#11821]
Hello all,
After I installed SUMO in windows 10. OSM file is not opening.
![image](https://user-images.githubusercontent.com/54150269/195452152-d0a1569b-5111-483d-acbc-0ac7958d1dcb.png)

![image](https://user-images.githubusercontent.com/54150269/195452189-43158a64-ca42-4020-91ee-b7f368ca5f1a.png)

**Comment by m-kro** [comment]
Please check where you actually installed SUMO. You can use Windows Explorer for that if you want. Then use the correct path to osmWebwizard.py to make it run.

**Comment by namdre** [comment]
The screen shows what is likely the result of running `sumo/bin/start-command-line.bat` so sumo is installed there.

Since you are on windows you need to need to call   `tools\osmWebWizard.py` instead of `tools/osmWebWizard.py`

**Comment by tamewadihu** [comment]
I tried using it in both cases it said that python can't open this file.  NETEDIT 1.14.1 is working and if I try to open OSM using using file explorer NETEDIT is can't open it. The following screen was displayed. 
![image](https://user-images.githubusercontent.com/54150269/195546722-cd5cf1d4-5ecc-4d88-b4f5-eadbf6b44f27.png)
Thank you for your cooperation!

**Comment by m-kro** [comment]
@tamewadihu Netedit is for SUMO networks, not for OSM data. You have to run netconvert first to convert from OSM to SUMO file format. Regarding OSM web wizard, you seem to have some trouble with your OS configuration. Maybe[ check the default programs](https://support.microsoft.com/en-us/windows/change-default-programs-in-windows-e5d82cad-17d1-c53b-3505-f10a32e1894d) for different file endings in the system settings.

**Comment by tamewadihu** [comment]
Dear  Mirko Barthauer,
Thank you for your reply. Actually, my aim is to simulate a fuzzy traffic
control system using SUMO.
Would you mind if you help me with this?
Regards,

Tamrat Delessa Chala
Széchenyi István University
School of Multidisciplinary Engineering
PhD Student
Mobile +36-20-5460973

**Comment by m-kro** [comment]
Keep in mind we don't have the resources to help you with your individual project (except paid support in bigger projects). We are happy to answer if you encounter some specific problem, bug etc. during your work. See our [FAQ](https://sumo.dlr.de/docs/FAQ.html#what_should_i_do_to_get_helpful_answers_on_the_mailing_list_or_on_the_issue_tracker) for more.

**Comment by tamewadihu** [comment]
Could you give me a short training on Sumo simulation, particularly on
fuzzy Traffic systems? If I will pay.
Looking forward to hearing from you soon!
Regards,

Tamrat Delessa Chala
Széchenyi István University
School of Multidisciplinary Engineering
PhD Student
Mobile +36-20-5460973
