### ISSUE TITLE
Poisson distribution and jtrrouter

### ISSUE THREAD

**Issue by hmzls** [eclipse/sumo#11834]
Hello,

I am trying to use a Poisson distribution for vehicle flows in combination with _jtrrouter_ and _--randomize-flows_ to generate random departure times.

Support for Poisson distributions was introduced in SUMO 1.13, and can be activated using the `<flow period="exp(123.0)">` notation.
Unfortunately, _jtrrouter_ hangs indefinitely when using the `exp()` notation, in combination with _--randomize_flows_.

After some debugging, it appears that _jtrrouter_ enters an infinite loop in `RONet::addFlow()`, because `flow->repetitionNumber` was initialized to 2147483647 for the Poisson distribution.  I get the impression that relevant changes were made to `RORouteHandler::closePersonFlow()`, but `RORouteHandler::closeFlow()` still requires some changes.  The function `addFlow()` should probably not be invoked at all for the Poisson distribution.  Am I correct in this observation?

What would be my best bet to get a Poisson distribution for departure times in _jtrrouter_?
Any hints would be much appreciated.

**SUMO-version: 1.14**

**operating system: Linux and Windows**

**Comment by namdre** [comment]
workarounds

a) define flow in a non-randomized manner (i.e. period="X") and set option **--randomize-flows**
b) use routeSampler.py with option **-f poisson** instead of jtrrouter (if you have turning counts rather than ratios)

**Comment by hmzls** [comment]
Thank you for your quick reply.

It seems that I have misunderstood the usage of _jtrrouter_ and _--randomize-flows_.  The `exp()` notation is not required at all to achieve a Poisson distribution.  The documentation at https://sumo.dlr.de/docs/Simulation/Randomness.html#router_options states this, but apparently I skimmed over the remark _"The following 2 sections ..."_.
