### ISSUE TITLE
invalid geometry when splitting rail edge

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#11837]
in attached net, try to split at any point along edge b2 (in both directiosn)

**Comment by namdre** [comment]
[input_net.net.xml.zip](https://github.com/eclipse/sumo/files/9785845/input_net.net.xml.zip)

**Comment by namdre** [comment]
not related to railway (same happens with normal car edges and spreadType=right

**Comment by palvarezlopez** [comment]
@namdre I cannot reproduce it :(
