### ISSUE TITLE
How to control the lane chose of vehicles

### ISSUE THREAD

**Issue by axonEmily** [eclipse/sumo#11830]
Add your issue description here.
Hi, I am trying to convert some network data from another software into sumo. To simplified the connections in each junction, I try to connect from_lanes to all possible to_lanes. The following picture shows an example of the connections:
![232453923f423f44a2430136c1f4787](https://user-images.githubusercontent.com/96557891/195797730-d580f333-d4a0-4a7a-a443-6d3c2140b66b.jpg)

The problem is vehicles will only choose one to_lane to travel. The following picture shows a signalized junction. Vehicles from left direction drive to right direction. There are two from_lanes and two to_lanes, vehicles from lane0 should choose lane0 of to_lane while vehicles from lane1 should choose lane1 of to_lane. But all vehicles choose lane1 of to_lane which is not make sense in reality. 
![e604b8e2a557c1b04867bb0ff8662fb](https://user-images.githubusercontent.com/96557891/195798319-fcb8cd6f-91c4-46f8-83d8-10bfeaf43121.jpg)

Is it the problem of driven behavior? How can I solve it without changing the connections of lane?
Thank you.
*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**

**Comment by namdre** [comment]
Please don't add any-to-any connections. In reality most lanes have dedicated successors.
In your setup, you are creating conflicts by multiple lanes that target the same outgoing lane and to resolve this one of the lanes gets priority. This is creating the problem.
