### ISSUE TITLE
multi_e2_detector_bug

### ISSUE THREAD

**Issue by Eviannn** [eclipse/sumo#11844]
hi,

my version is v1_14_1+1474-4a3b723138a using [sumo-win64extra-git](https://sumo.dlr.de/daily/sumo-win64extra-git.zip)

i found that when i used multilaneareadetector and set jamthreshold to 5, the additional.xml files recorded 1.39 instead of 5.

**Comment by m-kro** [comment]
Actually the documentation was wrong in this aspect, as a separate jam is detected when the distance to the next vehicles exceeds the jamThreshold value. Obviously it is expected to have inter-vehicle gaps less than the jamThreshold within the jam.
Thanks for pointing us to that problem.
