### ISSUE TITLE
**SUMO-version:**traci**python**

### ISSUE THREAD

**Issue by xhy12345x** [eclipse/sumo#11843]
**SUMO-version:**

*traci*
Error :could not access configuration 'base.sumocfg'
Use python to write traci,but it says:
"Retrying in 1 seconds
Could not connect to TraCI server at localhost:63655 [WinError 10061] 由于目标计算机积极拒绝，无法连接。
 Retrying in 1 seconds
Could not connect to TraCI server at localhost:63655 [WinError 10061] 由于目标计算机积极拒绝，无法连接。
 Retrying in 1 seconds
Could not connect to TraCI server at localhost:63655 [WinError 10061] 由于目标计算机积极拒绝，无法连接。
 Retrying in 1 seconds
Could not connect to TraCI server at localhost:63655 [WinError 10061] 由于目标计算机积极拒绝，无法连接。
 Retrying in 1 seconds"

**Could someone tell me how to solve this problem? Thank you very much**

**Comment by xhy12345x** [comment]
3447386862
***@***.***



&nbsp;Thank you very much for your reply. I would like to ask you how to solve this problem. I have tried many times but can't solve it




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "eclipse/sumo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月17日(星期一) 下午3:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [eclipse/sumo] **SUMO-version:**traci**python** (Issue #11843)





 
The original error is this one:
  
Error :could not access configuration 'base.sumocfg'
  
Please make sure the file path is right and that you have access to it. The following error messages just tell that SUMO is not running and that the TraCI script retries to connect.

**Comment by m-kro** [comment]
Once again: Please check 'base.sumocfg' file is in your current working directory when calling your script! In case you are not sure, give SUMO the absolute path to the configuration file. We cannot help you more in this respect as it depends on your system.

**Comment by xhy12345x** [comment]
Thank you very much! I find my problem and solve it successfully.Thank you again！




3447386862
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "eclipse/sumo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月17日(星期一) 下午3:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [eclipse/sumo] **SUMO-version:**traci**python** (Issue #11843)





 
Once again: Please check 'base.sumocfg' file is in your current working directory when calling your script! In case you are not sure, give SUMO the absolute path to the configuration file. We cannot help you more in this respect as it depends on your system.
