### ISSUE TITLE
Vehicles cannot be platooned by use simpla

### ISSUE THREAD

**Issue by zhaotuo0815** [eclipse/sumo#11842]
hello, sumo team. Why can't I generate a vehicle platoon with this configuration by using simpla.
![rou](https://user-images.githubusercontent.com/59630993/195990523-5380b10f-7a4c-4ba9-9d14-172bbde4926a.png)
![simpla](https://user-images.githubusercontent.com/59630993/195990528-824397f9-959e-47ee-b45c-9a88f6388c0f.png)
![warning](https://user-images.githubusercontent.com/59630993/195990530-b7e6f214-58d7-4d32-bb47-cd928cf42bb2.png)

**Comment by m-kro** [comment]
You did not specify the vTypes simpla should use for the given vehicle. This is done with the vTypeMap element in the simpla configuration, where you only put an entry for the "car" vType. 
Anyhow, it looks like you misunderstood how simpla works. There is no need to spawn vehicles with the vTypes listed in the {leader|follower|catchup|catupFollower} attributes, but rather use vTypes marked as "original". Then, all vehicles matching the vehicleSelectors criterion are managed by simpla automatically and use the vTypes listed in the corresponding vTypeMap element.
