### ISSUE TITLE
the number of polyline segments of the internal lane and and the endpoint positions of the polyline segments

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#11841]
What is the definition of the number of polyline segments of the internal lane and and the endpoint positions of the polyline segments corresponding to different trajectories?Based on what?
![lel](https://user-images.githubusercontent.com/54823725/195975899-abf916d5-0d1e-4722-bfdc-9bab37b898ba.png)
**SUMO-version:**

**Comment by m-kro** [comment]
See [netconvert option](https://sumo.dlr.de/docs/netconvert.html#junctions)  `--junctions.internal-link-detail [<INT>]` . Default value is 5, like you can already guess from the screenshot.

**Comment by a-123-du** [comment]
> See [netconvert option](https://sumo.dlr.de/docs/netconvert.html#junctions) `--junctions.internal-link-detail [<INT>]` . Default value is 5, like you can already guess from the screenshot.

How to modify the number of polyline endpoints? How are the ends of the polyline segments and the lengths of each polyline segment designed? Thank you for answering.
