### ISSUE TITLE
Vehicle movement

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#11846]
Are the front and rear suspension midpoints of the vehicle always in the internal lane (broken line segment) when moving through the vehicle intersection? Is the vehicle treated as a particle in accordance with the front suspension midpoint, along the internal lane through the intersection?

**SUMO-version:**

**Comment by m-kro** [comment]
Short answer: Yes. Like on other road segments, the lane angle at the front bumper determines the vehicle orientation.

Then there are a few exceptions, like overtaking inside the intersection when there are two parallel internal lanes.
