### ISSUE TITLE
alternative routes

### ISSUE THREAD

**Issue by jamanah** [eclipse/sumo#11850]
@namdre 

How can I get the alternative routes, not just the shortest, while I am running the simulation? In other words, I need alternative routes on each edge toward the destination. (destination is fixed, but origin will be updated after the vehicle passes an edge).

*If possible, upload an example that shows your problem.*

**SUMO-version: 1.14.1

**operating system: windows

**Comment by behrisch** [comment]
There is no easy way of telling what a good alternative route is. You could try to forbid some edges or give them higher travel times using https://sumo.dlr.de/pydoc/traci._vehicle.html#VehicleDomain-setAdaptedTraveltime and then simple do the routing again.

**Comment by behrisch** [comment]
There is also a script `tools/findAllRoutes.py`. But be warned. There may be _many_ of them.

**Comment by jamanah** [comment]
@behrisch 

Thank you very much for your support. Could please write the associated code line that I can call and use findAllRoutes? 

Since I used "traci.simulation.findAllroutes(origin edge, destination edge, vehicle type)" like traci.simulation.findRoute, but it gave me this error: "SimulationDomain' object has no attribute 'findAllroutes'"

**Comment by jamanah** [comment]
@behrisch 

I used the following code line to run 'findAllRoutes.py', but I there is something wrong since I cannot see anything in output file (alternatives.xml):

subprocess.run(['Python', '"C:/Program Files (x86)/Eclipse/Sumo/tools/findAllRoutes.py" -n "D:/Sumo/Third-routing/Third.net.xml" -o "D:/Sumo/Third-routing/alternatives.xml" -s "nb4" -t "E1"'])

1) Could you please tell me which part is wrong and write the correct format?

2) Is there anyway that I can use 'findAllRoutes.py' and get alternative ways while I am running the simulation instead of waiting till the end of simulation and seeing output file?

**Comment by jamanah** [comment]
@behrisch @namdre 

I would be grateful if you answer my questions.
