### ISSUE TITLE
intersection conflict

### ISSUE THREAD

**Issue by Eviannn** [eclipse/sumo#11852]
hi, in an intersection which is controlled by traffic light, if one vehicle passed the stop line and its light turned red immediately, its foe flow would drive into the intersection, and in the simulation, this vehicle would wait in the intersection and cause dead lock . However, in the real wolrd, the foe flow might wait and let this vehicle pass.

when i reduce the vehicle speed, this problem happens much more frequently.

i do not want to teleport this vehicle and i want to find somewhere to set the priority in order to aviod this problem forever.

hope u can help!

**Comment by m-kro** [comment]
Would you mind providing a minimum working example of your problem?

**Comment by Eviannn** [comment]
![屏幕截图 2022-10-18 174103](https://user-images.githubusercontent.com/89377838/196395560-3e04f1e7-1411-465d-8481-a7ae80fe6204.png)
thx for ur reply, above is the problem, the vehicle stops in the intersection because of the foe flow.

**Comment by m-kro** [comment]
Could you please attach the SUMO files to this issue?

**Comment by Eviannn** [comment]
![屏幕截图 2022-10-18 210325](https://user-images.githubusercontent.com/89377838/196437335-6947419d-459d-4780-9f81-37ce3d3e65bb.png)

**Comment by behrisch** [comment]
Closing for lack of feedback. Feel free to add another comment if you have more information or can provide a scenario.
