### ISSUE TITLE
Strange behaviour at intersection

### ISSUE THREAD

**Issue by alexrsanchez** [eclipse/sumo#11857]
I've been noticing in one specific intersection that vehicles performing a right turn, suddenly stop (without apparent reason) at the exit of the intersection resulting in unrealistic traffic jams and collisions.

Here is a video illustrating this issue. I have noticed this behaviour in both 1.13.0 and 1.14.1 versions.

https://user-images.githubusercontent.com/72650160/196623469-9781d7ec-1877-47ff-b39e-534df0dd4b98.mp4

**Comment by m-kro** [comment]
Indeed this looks strange. Could you please attach the files?

**Comment by alexrsanchez** [comment]
Of course, here you have the files

[strange_behaviour_files.zip](https://github.com/eclipse/sumo/files/9818079/strange_behaviour_files.zip)

**Comment by m-kro** [comment]
Follow-up question: Do you nonetheless expect the connections from the east approach to be like they are currently:

- two parallel incoming lanes with intersecting connections from there **AND** green signal at the same time?
- In Google Streetview the rightmost lane is reserved for taxi and bus. Do they still use the same green phase?

I fear SUMO currently cannot manage this particular setting with conflicts originating from the same incoming edge.

**Comment by alexrsanchez** [comment]
Hello again, sorry for the late response!

Indeed, there was a bug in my network. Only the rightmost lane should be allowed to turn right (it wasn't reserved for taxi and bus a few months ago). Performing this change, there are no vehicles suddenly stopping at the intersection, so the issue may come from the fact of two lanes merging into one after the intersection.
