### ISSUE TITLE
the center line of the exit lane

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#11868]
Does traffic in the normal lane follow the center line of the lane?
How do you find the coordinates of the points on the center line of the exit lane?（That red line in the picture）I only know the midpoint of the stop line out of the driveway,I need one other point.
![DE50B1 DXLELUNZK4823W~I](https://user-images.githubusercontent.com/54823725/196958168-46ded392-5f9f-40eb-b7fb-2b74648ce6a9.png)

**SUMO-version:**

**Comment by m-kro** [comment]
If you do not use the [Sublane Model](https://sumo.dlr.de/docs/Simulation/SublaneModel.html), then vehicles follow the center line. You can inspect the lane geometry using [sumolib](https://sumo.dlr.de/pydoc/sumolib.net.lane.html). If you have trouble with sumolib, have a look at the respective [test](https://github.com/eclipse/sumo/tree/main/tests/tools/sumolib/net).
