### ISSUE TITLE
net.xml

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#11860]
How do you design the naming rules and order of the internal lane ids in the xml file？Why don't some internal lanes for turning left in xml give five points? It's three points?(like :J1_2_0)
![image](https://user-images.githubusercontent.com/54823725/196855520-e0efc564-a38b-41c1-bf59-d3f6f9f091fa.png)
![9095fdde2539ecac1db308236eecd26](https://user-images.githubusercontent.com/54823725/196855589-ad698bf1-6da3-4b91-8e41-82d8e5f3df40.jpg)

**SUMO-version:**

**Comment by m-kro** [comment]
The naming convention is `:<JUNCTION_ID>_<INTERNAL_EDGE_INDEX>_<LANE_INDEX>`.

**Comment by a-123-du** [comment]
> The naming convention is .`:<JUNCTION_ID>_<INTERNAL_EDGE_INDEX>_<LANE_INDEX>`

Why don't some internal lanes for turning left in xml give five points? It's three points?(like :J1_2_0)

**Comment by m-kro** [comment]
It is probably due to the waiting position of permissive left turns. Then the turning consists of a first internal lane up to the waiting position and a second one to the junction exit. As a result, the whole turning still contains five geometry points, so everything is fine as you can tell from your own screenshot.

**Comment by a-123-du** [comment]
> 这可能是由于允许左转的等待位置。然后，转弯包括第一条内部车道，直到等待位置，第二条车道到达交叉口出口。因此，整个车削仍然包含五个几何点，因此您可以从自己的屏幕截图中看出一切正常。
There are only three coordinate points in net.xml, including the internal lane in the waiting position. How do I get the endpoints of the remaining internal lanes?（point as shown in the figure）? or , can I remove the waiting points at intersections so that each internal lane has five vertex coordinates？
![image](https://user-images.githubusercontent.com/54823725/197133129-705685cb-9173-40ec-a024-a6429ae26bbe.png)
![image](https://user-images.githubusercontent.com/54823725/197133012-55860083-8c32-42ba-ac70-a086a9f7cf7b.png)

**Comment by m-kro** [comment]
You look at the wrong part of the turning. The turning from top to right consists of  `:J1_2` (up to the waiting position) and then `:J1_12`.

**Comment by a-123-du** [comment]
Yes， I understand ，thank you
