### ISSUE TITLE
Calculate waiting time in statistic.xml

### ISSUE THREAD

**Issue by TrinhTuanHung2021** [eclipse/sumo#11867]
Add your issue description here.
Hello. I tried to build the formula to calculate the average waiting time.
I made an isolated road with a traffic light.

In statistic.xml I get the `waitingTime="85.88"`
and in GUI, the graph of waiting time
![image](https://user-images.githubusercontent.com/82990411/196957780-0d64dfe4-1ce8-4e5e-887f-b83f37f78291.png)

. In python.py I used
Option 1:
```
 waiting_time = traci.lane.getWaitingTime("e0_0") + traci.lane.getWaitingTime("e0_1")
a_waiting_time=waiting_time/len(car_list )
```

Option 2:
```
waiting_time = traci.lane.getWaitingTime("e0_0") + traci.lane.getWaitingTime("e0_1")
a_waiting_time=waiting_time/len(car_list )
```
Option 3:
`wait_time = traci.vehicle.getAccumulatedWaitingTime(car_id)`
`a_waiting_time = sum(waiting_times.values())/len(car_list)`
...
but I only got the graph like this
![image](https://user-images.githubusercontent.com/82990411/196957227-ba7ba66f-a602-4492-ba42-8cc03d7c642c.png)

Could you tell me the way to calculate average_waiting_ time in statistic.xml?
Thanks and best regards

*If possible, upload an example that shows your problem.*

**SUMO-version:** 1.14.1

**operating system:** Win

**Comment by namdre** [comment]
statistic-output and also the gui plot that you showed compute an average over the whole simulation whereas your code only computes an average over the cars currently on an edge.
The proper code is
```
totalWT = 0
totalVehs = 0

# in each step 
for id in traci.vehicle.getIDList():
   if traci.vehicle.getSpeed(id) < 0.1:
        totalWT += 1 # assuming step length 1s
totalVehs += traci.simulation.getArrivedNumber()

# finally
avgWT = totalWT / totalVehs
```
