### ISSUE TITLE
Let user control how bright the OSG scene should be

### ISSUE THREAD

**Issue by m-kro** [eclipse/sumo#11865]
Currently, OSG scenes in sumo-gui appear quite dark by default. The only option for now is to place extra lights (up to 8 of them can be defined in OpenGL). This has some shortcomings:

- depends on the user to configure the scene
- depends on the position of the light
- strong correlation between viewing angle and object orientation (faces get rendered way darker when the camera does not face directly their normal vector)

This can be configured by the 3D object material. OSG offers to specify the usual different light components:

- ambient
- diffuse
- specular
- (emissive)

Custom 3D objects loaded by OSG usually come with their own material settings. That's why the light components should be made adjustable at least for the 3D objects created by SUMO itself. For each light component, a slider/input field could be added to the 3D GUI settings.

**Comment by namdre** [comment]
- maybe a global brightness slider (for the default light source)

**Comment by namdre** [comment]
why is there an upper limit of 255 to the brightness? Couldn't we crank up the lumens arbitrarily?

**Comment by m-kro** [comment]
Light color is limited to RGB...

**Comment by m-kro** [comment]
Close here for change log as it has already been implemented. Further tweaking can happen in new issues.
