### ISSUE TITLE
the shape of the junction

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#11872]
where are  the coordinates in the shape property of the junction?What do they mean?
![704b44370f54832b0d7c037c88efa4f](https://user-images.githubusercontent.com/54823725/197130499-a4e8e81f-d1cc-434c-9f78-3c5c74d91422.jpg)

**SUMO-version:**

**Comment by m-kro** [comment]
They represent the junction shape (here in red). The polygon is defined by an ordered list of its points.  Just move over the network and compare some coordinates, then you understand it better hopefully!

**Comment by a-123-du** [comment]
> 它们表示结点形状（此处为红色）。多边形由其点的有序列表定义。只需在网络上移动并比较一些坐标，然后您就可以更好地理解它！
I know that the first and third points are the center of the junction，But below the second coordinate, I don't know where it's referring to, it's 9 away from the first coordinate.I have compared coordinates in netedit, but I don't know where to refer to.
