### ISSUE TITLE
Surrounding vehicles in SUMO do not respond to ego vehicle's behaviour that controlled by traci.vehicle.MoveToXY

### ISSUE THREAD

**Issue by yangkaia123** [eclipse/sumo#11877]
In our experiment, we use the command traci.vehicle.MoveToXY to control the ego vehicle position and surrounding vehicles are controlled by the carFollowModel="Krauss" in SUMO.We find that the surrounding vehicles do not respond to the behavior of the ego vehicle. However, when using the command traci.vehicle.setSpeed to control the ego vehicle, the surrounding vehicles will respond the behavior of ego vehicle. Due to that I want to control both the longitudinal and lateral motion of ego vehicle, so I need to use the command traci.vehicle.MoveToXY. How should I solve this issue. 

SUMO-version: 1.8.0

operating system: Ubuntu 20.04

**Comment by namdre** [comment]
Can you replicate the problem with the latest release version of SUMO?

**Comment by yangkaia123** [comment]
ok, i will try it soon, thanks for your reply.

**Comment by behrisch** [comment]
Closing for lack of feedback. Feel free to add another comment if you have more information.
