### ISSUE TITLE
information about all the internal lanes

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#11873]
How do I get information about all the internal lanes in the road network through sumoLib? Like the shape value in the internal line in net.xml.Can you give me the place described in the specific document or the specific code block
**SUMO-version:**

**Comment by a-123-du** [comment]
> How do I get information about all the internal lanes in the road network through sumoLib? Like the shape value in the internal line in net.xml.Can you give me the place described in the specific document or the specific code block **SUMO-version:**
Or instead of using sumolib, how to get information about the internal lanes in the road network (shape coordinates and their heading information)

**Comment by m-kro** [comment]
[https://sumo.dlr.de/pydoc/sumolib.net.lane.html](https://sumo.dlr.de/pydoc/sumolib.net.lane.html): `lane.getShape()`
See [this test](https://github.com/eclipse/sumo/blob/main/tests/tools/sumolib/net/runner.py) on how to access individual lanes.

**Comment by a-123-du** [comment]
> https://sumo.dlr.de/pydoc/sumolib.net.lane.html: `lane.getShape()` See [this test](https://github.com/eclipse/sumo/blob/main/tests/tools/sumolib/net/runner.py) on how to access individual lanes.

yes,but why when I write the code, the getShape() method is not found？
![image](https://user-images.githubusercontent.com/54823725/197194859-a38fdde9-f8a1-46a7-9059-5c846ab8ddd3.png)
![image](https://user-images.githubusercontent.com/54823725/197194957-dbdc661e-8dc6-4ba7-8987-62458580054f.png)

**Comment by m-kro** [comment]
```
net = sumolib.net.readNet(sys.argv[1], withInternal=True, withLatestPrograms=True)
lane = net.getLane("SC_0")
shape = lane.getShape()
```
