### ISSUE TITLE
TraCI slow

### ISSUE THREAD

**Issue by yangh0597** [eclipse/sumo#11871]
![image](https://user-images.githubusercontent.com/86940083/197124980-e3a97482-e90b-4459-9865-d1d9845970db.png)

We ran simulations using TraCI, had a lot of cars on the road, and found that running "_traci.simulationStep()" sometimes took 5s. Is there any plan to improve the situation?

**Comment by yangh0597** [comment]
There are about 2,000 cars

**Comment by namdre** [comment]
First, check whether any of the following things apply to your sim: 
- https://sumo.dlr.de/docs/FAQ.html#my_traci-program_is_to_slow_what_can_i_do
- https://sumo.dlr.de/docs/FAQ.html#how_can_i_make_the_simulation_run_faster
- https://sumo.dlr.de/docs/FAQ.html#the_simulation_gets_slow_with_many_vehicles_waiting_for_insertion

**Comment by yangh0597** [comment]
ok,thanks

**Comment by yangh0597** [comment]
done,thanks
