### ISSUE TITLE
Regular stops are omitted when setting stops on internal lane using TraCI 

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#11885]
Is there a way to set multiple stop coordinates on the internal lane in SUMO, and can it be stopped and restarted continuously but not use the traci.vehicle.setStop method more than once? If not, how do you stop and start and stop again in sumo? I understand that the traci.vehicle.setStop () method can stop the vehicle after a certain distance from the start of the lane, but is there a way to set multiple stops?
**SUMO-version:**

**Comment by m-kro** [comment]
It looks like you have found a bug. Thank you for notifying us. When setting stops on an internal lane using TraCI, other known  stops of the concerned vehicle on regular lanes are disregarded. This does not happen when predefining all stops in a route file.

**Comment by a-123-du** [comment]
> It looks like you have found a bug. Thank you for notifying us. When setting stops on an internal lane using TraCI, other known stops of the concerned vehicle on regular lanes are disregarded. This does not happen when predefining all stops in a route file.

I don't think I quite follow you, Sir. I mean now I want a car to stop at some point on the internal lane as it passes. But I don't want to set multiple setstops (), so how do I do that? Does sumo provide a list argument for the stop location?

**Comment by a-123-du** [comment]
![image](https://user-images.githubusercontent.com/54823725/197698914-92e000ce-a6c5-45ee-b11e-7a6dd64952e5.png)
Like the blue position on the internal lane shown below, I want to let the car stop at these points, but don't want to do it by setting setstop() four times. Is there another way?

**Comment by a-123-du** [comment]
![image](https://user-images.githubusercontent.com/54823725/197698914-92e000ce-a6c5-45ee-b11e-7a6dd64952e5.png)
Like the blue position on the internal lane shown below, I want to let the car stop at these points, but don't want to do it by setting setstop() four times. Is there another way?

**Comment by m-kro** [comment]
@a-123-du No there isn't. Just use setStop multiple times.

**Comment by a-123-du** [comment]
For questions about traci.vehicle.resume(), what does this method do? The duration parameter in setStop causes the vehicle to start at a set time. What does resume() do？

**Comment by m-kro** [comment]
If the vehicle is stopped, it will leave the stop even if the duration hasn't elapsed yet.

**Comment by a-123-du** [comment]
How do I use the traci.vehicle.resume() method?
![image](https://user-images.githubusercontent.com/54823725/197721153-32b3b899-fd18-481a-9cf3-54d501d5bc42.png)
Why is there an error for resume after setStop?

**Comment by m-kro** [comment]
Now stops on internal lanes are inserted at the right order and thus do not prevent stopping at other stops.
