### ISSUE TITLE
How to create routes that start and end at the fringe of network using jtcrouter?

### ISSUE THREAD

**Issue by MohamadReza-Haghani** [eclipse/sumo#11889]
Hi,

I used jtcrouter to create a route file in my network. I have a corridor with 4 consecutive intersections. I used the turning count data of four intersections as input for jtcrouter. As a result of using "python tools/jtcrouter.py -n <net-file> -t <turn-file> -o <output-file> --fringe-flows", a route file was created in which all the routes started at the entering edges of intersections and ended at the fringe of the network. I was wondering how I can create a route file in which the routes start and end at the fringe of the network.

Thanks,
Reza.

**Comment by m-kro** [comment]
This fringe mechanism will only shift the route starting point upstream for unambiguous situations, thus only to the next intersection. It stops when there are multiple predecessor edges.

**Comment by MohamadReza-Haghani** [comment]
Thank you for your response. So, is there any other way to create a route file from a network and turn count data in a way that routes only start and end at external edges?

**Comment by namdre** [comment]
routeSampler can do this. Use candidate routes generated by randomTrips.py with option --fringe-factor 1e100
See https://sumo.dlr.de/docs/Demand/Routes_from_Observation_Points.html#chosing_the_right_tool
