### ISSUE TITLE
the vehicles in SUMO

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#11887]
Are the vehicles in SUMO self-driving cars, human-driven cars, or both

**SUMO-version:**

**Comment by behrisch** [comment]
Both. Usually we parametrize automated cars differently (smaller headways, no imperfection) but it really depends how much you know about teh controller being used

**Comment by namdre** [comment]
it also depends on the carFollowModel i.e.
- EIDM: human
- CACC: self-driving
- Krauss: agnostic
