### ISSUE TITLE
How to merge edges in netedit?

### ISSUE THREAD

**Issue by MohamadReza-Haghani** [eclipse/sumo#11883]
Hi, 

I was wondering if there is a way to merge two successive edges with the same properties in netedit.

Best,
Reza.

**Comment by namdre** [comment]
right-click the junction between these edges and select 'Replace junction by geometry point'  (if the option is greyed out, take note of the specified reason that prevents it).

**Comment by MohamadReza-Haghani** [comment]
Thanks!
