### ISSUE TITLE
optionally, use stop attribute 'arrival' / 'started' to delay stop arrival

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#11899]
new option **--use-stop-started** (similar to **--use-stop-ended**)

either
- drive normally and just delay entering the 'reached' state of the stop (i.e. to prevent loading/unloading passengers)
- slow down the vehicle to make it reach the stop at the indicated time (more difficult since there might arbitrary traffic-related delays while approaching the stop). Maybe a special case for railway simulation if there are no more remaining signals on approach to the stop.

**Comment by behrisch** [comment]
Do trains really do this? I mean I would understand if they want to keep the track clear but this does not seem to be the case here.

**Comment by namdre** [comment]
attribuet 'started' and 'ended' are about replaying emperical data that is more accurate than the scheduled times 'arrival' and 'until'.  Hence we wish to replicate as much as possible from the "real" behavior in a way that is intuitive to someone watching the simulation.

**Comment by namdre** [comment]
> Do trains really do this? I mean I would understand if they want to keep the track clear but this does not seem to be the case here.

Yes. They do this to conserve energy. Driving at maximum speed is expensive and only done when needed to keep the schedule.

**Comment by namdre** [comment]
Implementation idea: new vType parameter that holds the minimum permitted speed which may be used to better match arrival/started time
