### ISSUE TITLE
Set the vehicle shape scheme in the settings file

### ISSUE THREAD

**Issue by MohamadReza-Haghani** [eclipse/sumo#11890]
Hi,

I was wondering if I can set the vehicle shape scheme to 'simple shapes' in the settings file instead of doing it manually in view settings every time I open SUMO GUI.

Thanks,
Reza.

**Comment by namdre** [comment]
It's `<vehicles vehicleQuality="2"/>` in the settings file (or just save settings from the dialog after configuring them to your preference).
