### ISSUE TITLE
permit loading a .sumocfg

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#11896]
- new option **--sumocfg FILE**
- load all files referenced in the configuration (with the appropriate handlers)
- allow manipulating all options (probably by parsing a configuration template in order to build a configuration wizard - see #4138)
- write all these options when using menu option to "Save SUMO-config"

**Comment by palvarezlopez** [comment]
For options we can use  https://github.com/eclipse/sumo/issues/2435

**Comment by namdre** [comment]
I think we shouldn't mix a property dialog with an options editor. 
- The network properties are just a collection of computed properties (i.e. total edge length)
- The sumo configuration should be edited in the same manner as it now happens with the netconvert options (F10)

**Comment by palvarezlopez** [comment]
Use options handlers
