### ISSUE TITLE
randomTrips.py: permit forcing all probability onto the fringe

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#11894]
right now, fringe-factor only permits increasing the probability of the fringe relative to everything else but the non-fringe probability cannot be made 0

**Comment by behrisch** [comment]
This more or less applies to all "probability modfiers". I cannot filter to allow only edges with 2 and more lanes or allow only edges with a minimum speed of x. I like the idea of having a separate filter script here. This way we could also distinguish whether we want to apply the filter only to source or sink or via. This way we could also try to keep the complexity of randomTrips down

**Comment by namdre** [comment]
I don't mind having a script for post-processing of custom probabilities. However, the use case "fringe-only" is the only one I had so far with regard to "hard" cut-offs and this one came up repeatedly (and also by other users).
Hence thinking of a good mechanism (i.e. some magic option value/keyword in lieu of a number) strikes me as much more helpful compared to the proposed workflow of:

1. call randomTrips once to initialize the probability maps
2. call a filter script to manipulate all or some of them
3. call randomTrips again with the new maps

**Comment by behrisch** [comment]
I just wanted to propose to move the filtering into sumolib if it is more generic than just fringe. Other scripts might want that too.

**Comment by namdre** [comment]
nothing generic so far.
