### ISSUE TITLE
Unable to start sumo flatpak

### ISSUE THREAD

**Issue by manikandancode** [eclipse/sumo#11893]
OS : Ubuntu 22.10
SUMO-version: v1_14_1

Error: FXApp::openDisplay: unable to open display :0.0

![Screenshot from 2022-10-26 12-50-55](https://user-images.githubusercontent.com/46480489/197961054-c4fb10a9-69fb-434a-a02a-ea9f2ff368a7.png)

**Comment by behrisch** [comment]
@manikandancode Can you try whether this helps: https://stackoverflow.com/questions/65819483/flatpak-on-wayland-error-cannot-open-display ?

**Comment by kevinsmia1939** [comment]
Hi,
Could you try running sumo like this?
`flatpak run --socket=x11 org.eclipse.sumo`

**Comment by manikandancode** [comment]
> Hi, Could you try running sumo like this? `flatpak run --socket=x11 org.eclipse.sumo`

![Screenshot from 2022-10-26 20-06-34](https://user-images.githubusercontent.com/46480489/198055857-d1a40af7-b484-4eea-a130-18bf17d6bc00.png)

**Comment by manikandancode** [comment]
> @manikandancode Can you try whether this helps: https://stackoverflow.com/questions/65819483/flatpak-on-wayland-error-cannot-open-display ?

![Screenshot from 2022-10-26 20-09-08](https://user-images.githubusercontent.com/46480489/198056459-58b44f19-29b1-4041-8bff-66ac1942750b.png)

**Comment by kevinsmia1939** [comment]
I think that sumo would not able to run on Wayland because it depend on fox toolkit. Could you try logging out and choose "Ubuntu on Xorg" before logging in again and see if it work?

**Comment by kevinsmia1939** [comment]
Does non-flatpak sumo work?

**Comment by manikandancode** [comment]
> Does non-flatpak sumo work?

Ubuntu ppa works

**Comment by manikandancode** [comment]
> I think that sumo would not able to run on Wayland because it depend on fox toolkit. Could you try logging out and choose "Ubuntu on Xorg" before logging in again and see if it work?

will try tomorrow. i am out now.

**Comment by manikandancode** [comment]
> > Ubuntu ppa works but installs version 1.12.0
> 
> That's strange. According to this: https://launchpad.net/~sumo/+archive/ubuntu/stable there should be an up to date version. Maybe call apt update again?

PPA is not updated for Ubuntu 22.10 . So it fetches from the default Ubuntu repository. 

sudo add-apt-repository ppa:sumo/stable
sudo apt-get update
sudo apt-get install sumo sumo-tools sumo-doc


![Screenshot from 2022-10-27 10-45-13](https://user-images.githubusercontent.com/46480489/198198440-805e1b39-2e15-4ab6-94d2-df6f262f5465.png)

**Comment by behrisch** [comment]
You are right, I misread your ubuntu version, there is no 22.10 upload yet

**Comment by behrisch** [comment]
I just added it. Have a look here: https://launchpad.net/~sumo/+archive/ubuntu/stable/+builds?build_text=&build_state=all If the build is finshed in about 50 minutes, it should be available

**Comment by manikandancode** [comment]
> I just added it. Have a look here: https://launchpad.net/~sumo/+archive/ubuntu/stable/+builds?build_text=&build_state=all If the build is finshed in about 50 minutes, it should be available

Now PPA installs 1.14.1 on Ubuntu 22.10 (Wayland) and it works correctly.

**Comment by behrisch** [comment]
@kevinsmia1939 Should I open a ticket at flathub? Do you have the time to look at it at all?

**Comment by kevinsmia1939** [comment]
> @kevinsmia1939 Should I open a ticket at flathub? Do you have the time to look at it at all?

sure thing

**Comment by behrisch** [comment]
@manikandancode we will track this further in the flathub ticket
