### ISSUE TITLE
the method setStop（）

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#11891]
Can't this pos parameter be 0? if I want  the vehicel stop at the entry point of the lane.
![image](https://user-images.githubusercontent.com/54823725/197928199-65209b17-a0ce-4beb-a0d7-72962fa3e84a.png)

**SUMO-version:**

**Comment by namdre** [comment]
There was a bug. The dev version now permits position 0.

**Comment by a-123-du** [comment]
> There was a bug. The dev version now permits position 0.

What is the dev version? Can you give me the link?

**Comment by namdre** [comment]
https://sumo.dlr.de/docs/Downloads.php#nightly_snapshots

**Comment by a-123-du** [comment]
> https://sumo.dlr.de/docs/Downloads.php#nightly_snapshots

If I use the Windows 64 operating system, can I download this ?Is this a bug-fixed version that includes the functionality of the github release?
![image](https://user-images.githubusercontent.com/54823725/198789187-c7aded2f-968d-40f9-bbb1-c02376bb3643.png)

**Comment by a-123-du** [comment]
> https://sumo.dlr.de/docs/Downloads.php#nightly_snapshots

I have a try ,but 0 position is not valid
![image](https://user-images.githubusercontent.com/54823725/198796517-230514cf-7f6a-4def-b9fc-f2f33a78d580.png)

**Comment by namdre** [comment]
Most likely you script is starting the old version of sumo. To check, run with sumo-gui and compare the version information in the title bar to the version information at the night_snapshot download page.  A quick fix could be to uninstall all versions except for the latest dev version.
