### ISSUE TITLE
Y intersection

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#11902]
Can Y intersection be drawn in SUMO？

**SUMO-version:**

**Comment by namdre** [comment]
yes

**Comment by a-123-du** [comment]
> yes

How to draw the Y intersection or other intersections? Where is it mentioned in the document?

**Comment by namdre** [comment]
create-edge mode in netedit permits drawing arbitrary edges and if you draw three edges with a common junction you have a y-intersection. It you could help me to understand why this was not obvious, that would be quite helpful.

**Comment by a-123-du** [comment]
> create-edge mode in netedit permits drawing arbitrary edges and if you draw three edges with a common junction you have a y-intersection. It you could help me to understand why this was not obvious, that would be quite helpful.

Yes ，thank you .
