### ISSUE TITLE
the juction controller

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#11906]
Is there a junction controller in sumo?(like the RSU)（It can monitor the information of vehicle movement and so on）
![image](https://user-images.githubusercontent.com/54823725/198178437-a5af18ff-b05a-495c-9c15-0d5bca068b27.png)

**SUMO-version:**

**Comment by namdre** [comment]
not as an explicit object. You can define various detectors/outputs for monitoring the traffic or retrieve all the data than an RSU would receive via TraCI.
