### ISSUE TITLE
Questions about "safety check" and "lane change" in Traci

### ISSUE THREAD

**Issue by ShenZC25** [eclipse/sumo#11905]
Hello, I'm using SUMO for RL study. But there are some questions about "safety check" and "lane change" in Traci. The following is a part of the source code of an open source program。
-------------------------------------------------------------------
We konwn:
sumo_ctrl = False
self.safety_0_check = False
self.safety_1_check = False
-------------------------------------------------------------------
The problem is:
if not sumo_ctrl:
    if not self.safety_0_check:
        traci.vehicle.setSpeedMode(self.ego_0_id, 0)    
        traci.vehicle.setLaneChangeMode(self.ego_0_id, -20)
else:
    traci.vehicle.setSpeed(self.ego_0_id, -1)

if not sumo_ctrl:
    if not self.safety_1_check:
        traci.vehicle.setSpeedMode(self.ego_1_id, 0)
        traci.vehicle.setLaneChangeMode(self.ego_1_id, 0)
else:
    traci.vehicle.setSpeed(self.ego_1_id, -1)
-------------------------------------------------------------------
Could you please tell me the meaning of "-20" in "traci.vehicle.setlanechangemode"? I didn't find it on official website.
I think this author turned off all the security checks and the switch of channel changing strategy about SUMO.

Next, I want to do something like this: use SUMO's built-in collision detection switch to judge that the car has collided, then it will stop the RL training by "not" letting the car do any lane change (only adjusting its own speed by accelerating and decelerating). Could you tell me how to set the parameters in "traci.vehicle.setSpeedMode" and "traci.vehicle.setLaneChangeMode"?

**Comment by namdre** [comment]
the argument to setLaneChangeMode is interpreted as a bitset with its meaning documented at https://sumo.dlr.de/docs/TraCI/Change_Vehicle_State.html#lane_change_mode_0xb6

You can retrieve collision events by calling `traci.simulation.getCollisions`.   
If your LR framework requests lanechanges (i.e. with `traci.vehicle.changeLane`) then you need to prevent these calls (setting laneChangeMode will generally not block traci-requested changes).
