### ISSUE TITLE
Issues while compiling sumo on MacOS

### ISSUE THREAD

**Issue by thibault-charlottin** [eclipse/sumo#11903]
Hello, I'm trying to compile SUMO from the GitHub release on macOS Monterey 12.3.1 (the goal is to control that calibration behaves well on the main branch files before adding my own modifications).

 While compiling and respecting all the steps from https://sumo.dlr.de/docs/Installing/MacOS_Build.html, I received those error messages : 
______________________________________________
Undefined symbols for architecture x86_64:
  "OGRCreateCoordinateTransformation(OGRSpatialReference const*, OGRSpatialReference const*)", referenced from:
      NBHeightMapper::loadShapeFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libnetbuild.a(NBHeightMapper.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [/Users/thibault.charlottin/sumo-git/bin/netgenerate] Error 1
make[1]: *** [src/netgen/CMakeFiles/netgenerate.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
______________________________________________

[ 67%] Linking CXX executable /Users/thibault.charlottin/sumo-git/bin/polyconvert
Undefined symbols for architecture x86_64:
  "OGRCreateCoordinateTransformation(OGRSpatialReference const*, OGRSpatialReference const*)", referenced from:
      PCLoaderArcView::load(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, OptionsCont&, PCPolyContainer&, PCTypeMap&) in PCLoaderArcView.cpp.o
  "OGRSpatialReference::SetAxisMappingStrategy(OSRAxisMappingStrategy)", referenced from:
      PCLoaderArcView::load(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, OptionsCont&, PCPolyContainer&, PCTypeMap&) in PCLoaderArcView.cpp.o
  "OGRFeature::GetFieldAsDouble(int) const", referenced from:
      PCLoaderArcView::load(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, OptionsCont&, PCPolyContainer&, PCTypeMap&) in PCLoaderArcView.cpp.o
  "OGRFeature::GetFieldAsString(int) const", referenced from:
      PCLoaderArcView::load(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, OptionsCont&, PCPolyContainer&, PCTypeMap&) in PCLoaderArcView.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [/Users/thibault.charlottin/sumo-git/bin/polyconvert] Error 1
make[1]: *** [src/polyconvert/CMakeFiles/polyconvert.dir/all] Error 2
______________________________________________

This leads to
______________________________________________
make: *** [all] Error 2
______________________________________________

Could someone help me figure out what's going on ?

Thanks !

**Comment by eknabevcc** [comment]
@thibault-charlottin May I ask if you found a solution to the problem? 

I'm trying to build (custom cmake config) for dual architecture arm_64 and x86_64, but get similar link error.

macOS 14 (Sonoma) works fine, but not macOS 11 (Big Sur) or macOS 12 (Monterey).
