### ISSUE TITLE
the relationship between the vehicle trajectory and the endpoint

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#11916]
Is the SUMO's vehicle trajectory a curve? Does the vehicle trajectory of sumo fit the trajectory through the internal lane endpoint or the broken line endpoint through the vehicle trajectory?This is crucial to my research.Thank you very much for your answer
![image](https://user-images.githubusercontent.com/54823725/198573250-61ec0e74-ae49-4794-ab4e-9fdfd8abc1d5.png)

**SUMO-version:**

**Comment by namdre** [comment]
Frankly, I do not understand your problem.
This question is virtually the same as many that have been asked and answered before, yet you never seem to engage with the answers already given. 
Also, the outputs of sumo are there to answer the question for you. Simply lower the step-length and observe the trajectories generated by the simulation (--fcd-output). I suspect that this will give you more insight than any of my repeated answers will give.

**Comment by namdre** [comment]
I notice that you are raising two additional topics that are not related to the original question.
- how is the shape generated (discussed in #11574, #11581) - I encourage you to find other people to guide you in Bezier shape generation.
- the coordinate system of SUMO: https://sumo.dlr.de/docs/Geo-Coordinates.html
