### ISSUE TITLE
SUMO Website Certificate Invalid

### ISSUE THREAD

**Issue by abrac** [eclipse/sumo#11910]
Hi there. The SSL certificate of https://sumo.dlr.de has expired, so we can no longer access the documentation.

**Comment by boxjuke** [comment]
Hi. I am also struggling with the same issue that SSL certificate of SUMO documentation and other services has expired. I can not access SUMO documentation. Please let me know how to figure it out. It seems the problem is not an individual-level problem.

**Comment by namdre** [comment]
Thanks for the notice. We are aware of the problem and working on a fix.

**Comment by namdre** [comment]
should be fixed now
