### ISSUE TITLE
about sl2015 calculation formula

### ISSUE THREAD

**Issue by 817horizon** [eclipse/sumo#11922]
Is there any text explaining the calculation formula of SL2015? Especially in terms of lane change safety spacing, I feel that if I can read the relevant literature, the figure will be more clear. Thank you

**SUMO-version:**
sumo-1.13.0
**operating system:**
windows

**Comment by namdre** [comment]
please post related questions directly in #11921

**Comment by 2847662024** [comment]
With the default SL2015 model, the cars are all blocking only one lane. I tried to adjust the parameters but it didn't solve the problem very well.
![image](https://user-images.githubusercontent.com/34417999/198870967-6f74c13c-c773-4273-9fa9-8feee56259cf.png)
These are the parameters I have tried
![image](https://user-images.githubusercontent.com/34417999/198871047-4e5d2619-13b9-414b-b4f5-97f6b9fb9dd3.png)
Please help me!

**Comment by namdre** [comment]
@2847662024 
some ground rules if you would like to receive answers:
- don't post the same question in multiple issues (i.e #https://github.com/eclipse/sumo/issues/10862#issuecomment-1296184389)
 - if you have a novel question open a new issue rather tan re-using an old one
 - attach a minimal failing example (all files in a zip)
