### ISSUE TITLE
increase lateral acceleration and lateral speed to change lane when standing (or driving very slowly) but result in orthogonal sliding in sublane model

### ISSUE THREAD

**Issue by Eviannn** [eclipse/sumo#11929]
hi dear,

I tried to set lcMaxSpeedLatFactor="-1" and lcMaxSpeedLatStanding="0" to increase lateral acceleration and lateral speed to change lane when standing (or driving very slowly) #8064 in order not to overtake after stopped takes a long time since the forward speed is kept low until clearing the obstacle fully #1997, finally, it works.

However, i observed orthogonal sliding #3392, i wonder how to avoid orthogonal sliding in sublane model. 

Thank u for ur patience!

**Comment by namdre** [comment]
Some sliding is currently not avoidable.  If you can provide a minimal example of the situation you are facing I might be able to think of a solution for your specific case.

**Comment by Eviannn** [comment]
> Some sliding is currently not avoidable. If you can provide a minimal example of the situation you are facing I might be able to think of a solution for your specific case.
