### ISSUE TITLE
how to get SL2015'S Model formula

### ISSUE THREAD

**Issue by 817horizon** [eclipse/sumo#11921]
Add your issue description here.
I wanna to get SL2015'S Model formula，how to get it
*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**

**Comment by namdre** [comment]
https://github.com/eclipse/sumo/blob/a4adfae36d3dccdfb9c0a76da17f349132c386e5/src/microsim/lcmodels/MSLCM_SL2015.cpp#L1

**Comment by 817horizon** [comment]
> https://github.com/eclipse/sumo/blob/a4adfae36d3dccdfb9c0a76da17f349132c386e5/src/microsim/lcmodels/MSLCM_SL2015.cpp#L1

thank you sir

**Comment by namdre** [comment]
see https://elib.dlr.de/102254/1/Springer-SUMOs_Lane_changing_model.pdf for the general architecture.
The safety spacing comes directly from the car-following model and is not part of SL2015.
