### ISSUE TITLE
define vehicle type

### ISSUE THREAD

**Issue by zhaotuo0815** [eclipse/sumo#11925]
hello, sumo teams, I saw others define the vehicle type like this（like picture） on github, but I didn't see it on sumo's official website, can you help me explain?
![vtype](https://user-images.githubusercontent.com/59630993/198871364-4eac0a42-330b-4a6f-bdee-6b98900db5e8.png)

**Comment by namdre** [comment]
the use of element `<carFollowing-XYZ .../>` is deprected.
Instead use `<vType id="typ1" carFollowModel="CC" tauEngine="0.5" .../>

see https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#car-following_models

**Comment by zhaotuo0815** [comment]
> the use of element `<carFollowing-XYZ .../>` is deprected. Instead use `<vType id="typ1" carFollowModel="CC" tauEngine="0.5" .../>
> 
> see https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#car-following_models

thank you so much for your replying. But I could not found the carFollowModel "CC" and the parameter of carFollowModel "CC" in the https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#car-following_models

**Comment by namdre** [comment]
the CC model requires the use of Plexe and may not work correctly when not using Plexe. Hence it's not part of the standard documentation.
