### ISSUE TITLE
sumo tutorial

### ISSUE THREAD

**Issue by dusiyuya** [eclipse/sumo#11928]
The search function of the sumo tutorial is unavailable.

**Comment by namdre** [comment]
please post a screenshot that shows the problem.

**Comment by behrisch** [comment]
search works just fine here. Please add another comment with a screenshot if the problem persists

**Comment by dusiyuya** [comment]
The search interface touch is unresponsive and there is no cursor.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "eclipse/sumo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月9日(星期三) 晚上11:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [eclipse/sumo] sumo tutorial (Issue #11928)





 
search works just fine here. Please add another comment with a screenshot if the problem persists

**Comment by behrisch** [comment]
@dusiyuya And this happens only on the tutorial page or on every documentation page? Did you try a different browser?
