### ISSUE TITLE
Lateral Acceleration with TraCI

### ISSUE THREAD

**Issue by LorenzoUccello** [eclipse/sumo#11924]
Hello, 

I created a simulation and I need to get the lateral acceleration of the vehicles in the simulation. I couldn't find a Traci command to do it. Is there a way to obtain the lateral acceleration of every vehicle in the simulation at every time step? 

Thank you in advance. 

**SUMO -Version: v1_14_1+0776-419d5e4252e**

**MacOS Monterey**

**Comment by namdre** [comment]
The lateral acceleration defaults to 1m/s so if you don't configure a different number, this is what it will always be (in the sublane model).

**Comment by LorenzoUccello** [comment]
Hi namdre, 

Thank you for your answer. 
How can I configure it in my simulation and how can I retrieve the correct value at every step of the simulation using TraCI and possibly TraCI subscriptions?

**Comment by namdre** [comment]
first of all which model are you using?
- default model
-  sublane model or
-  the *simple continuous lane change model*

(see https://sumo.dlr.de/docs/Simulation/SublaneModel.html)

**Comment by LorenzoUccello** [comment]
I am using the simple continuous lane change model

**Comment by namdre** [comment]
In the default mode, lane changing in instant and neither lateral speed nor lateral accelerations have any meaning. There is nothing to configure and nothing to obtain via TraCI.

**Comment by namdre** [comment]
The lateral acceleration in curves is currently not considered during the simulation (except very roughly by forced lowering of permitted speeds while turning a corner on a junction).

Here is what you can do:
- retrieve the absolute heading with traci.vehicle.getAngle (in each simulation step)
- compute curve radius as traveledDistance / angleDifference
- compute lateral accleration as speed^2 / radius
