### ISSUE TITLE
zsh: command not found: sumo-gui

### ISSUE THREAD

**Issue by Catalpae** [eclipse/sumo#11930]
I followed the installation tutorial [here](https://sumo.dlr.de/docs/Installing/MacOS_Build.html)
And I added the SUMO_HOME path in ~/.zshrc
However, when I enter the command sumo-gui, the terminal returns "zsh: command not found: sumo-gui"
When I click the application Icon, something like a gear wheel appears as the menubar icon for several seconds and then disappears. Nothing changes ever since then.
Really Frustrating. I think I've followed every instructions in the installation tutorial. Have anyone come across this kind of problem and help me out?😂

**operating system:** macOS Monterey 12.6

**Comment by Catalpae** [comment]
My bad. Everything's good now.

**Comment by angelobanse** [comment]
> When I click the application Icon, something like a gear wheel appears as the menubar icon for several seconds and then disappears.

FYI: This is expected and happens because the App launchers you click are actually Automator Workflows that start `$SUMO_HOME/bin/sumo-gui`, `$SUMO_HOME/bin/netedit` and `python $SUMO_HOME/tools/osmWebWizard.py` respectively.

**Comment by gandonna** [comment]
Hello! I have the same problem with installing on my Mac. I keep getting this message:
**zsh: no such file or directory: ./sumo-gui**

I opened the 'XQuartz' application just what the tutorial said but it still results to the same message.
Tutorial: https://www.youtube.com/watch?v=JAAPLxgQ5UQ&t=55s (Time: 04:43)

Would really appreciate it if someone could help me as I am not a programmer nor have much experience with using the Terminal and all. Thanks again!

**Comment by angelobanse** [comment]
Hi @gandonna. Are you building SUMO or using `brew install sumo`?

If you are building it, you should go and call `sumo-gui` from within the `bin` folder - or just execute `make install` to be able to call `sumo-gui` from any location on your system (making the binaries available in `/usr/local/bin/`).

Have you set the `SUMO_HOME` variable? Did you try to open sumo-gui using the [application launcher](https://sumo.dlr.de/docs/Downloads.php#application_launchers)?

**Comment by gandonna** [comment]
Hi @angelobanse, thank you very much for responding. Yes, I am building SUMO. I basically just copy pasted the codes written on this website: https://sumo.dlr.de/docs/Installing/MacOS_Build.html

**How do I did this? Sorry, how I call sumo-gui?**
"If you are building it, you should go and call sumo-gui from within the bin folder - or just execute make install to be able to call sumo-gui from any location on your system (making the binaries available in /usr/local/bin/)."

I just now downloaded the application launcher but it wouldn't open as well.

<img width="462" alt="Screen Shot 2022-11-29 at 10 42 35 AM" src="https://user-images.githubusercontent.com/119393506/204480993-ce5374ee-62a2-4258-b229-8a14a85308ce.png">

**Comment by angelobanse** [comment]
The launchers only work if you have the `SUMO_HOME` variable set. You need to go to the macOS "System Preferences" > "Privacy and Security" and allow those launchers to open (just the first time). [More info here](https://support.apple.com/en-us/HT202491).

By "calling sumo-gui" i mean opening a terminal and executing `sumo-gui`

**Comment by gandonna** [comment]
Thanks again @angelobanse! The Privacy and Security did not allow me to enter as well.

Then when I tried executing sumo-gui, it said: zsh: command not found: sumo-gui
<img width="450" alt="Screen Shot 2022-11-29 at 12 06 54 PM" src="https://user-images.githubusercontent.com/119393506/204500621-1ae9687e-41e2-48f7-893b-a1083c836a7c.png">

**Comment by angelobanse** [comment]
You need to set the `SUMO_HOME` environment variable, and call `sumo-gui` from where it is actually located.

Just message me on [Mattermost](https://mattermost.eclipse.org/eclipse/channels/sumo), and i will guide you step by step over there.

**Comment by gandonna** [comment]
Thank you! I will message you! @angelobanse

**Comment by gandonna** [comment]
hi @angelobanse. can't seem to find you in Mattermost. Are you able to join this link?

https://gandonna.cloud.mattermost.com/signup_user_complete/?id=bi86pfnbm7d1trzjwhmpqjpaho&sbr=fa

**Comment by angelobanse** [comment]
Just to document it: @gandonna needed to have Homebrew in the Path first, before attempting to install SUMO

**Comment by gandonna** [comment]
Thank you so much! It's working now! @angelobanse

**Comment by rchotai** [comment]
Hi,

I seem to be having the same issue unfortunately with sumo-gui not appearing under sumo/bin as it should do. Any advice on how to fix this would be greatly appreciated!

Thanks!

**Comment by angelobanse** [comment]
@rchotai did you install SUMO using Homebrew? If so, run `brew info sumo` and navigate to the path that you will see there for the SUMO_HOME variable (it will be something like `/opt/homebrew/opt/sumo/share/sumo`) to manually check the `bin` directory.

**Comment by rchotai** [comment]
Thank you @angelobanse

**Comment by AlBeck862** [comment]
> Just to document it: @gandonna needed to have Homebrew in the Path first, before attempting to install SUMO

Hi,

Sorry to bring this up nearly two years later. I seem to be having this issue, and when checking the path under opt/homebrew/opt, sumo is a dead link ("The operation can’t be completed because the original item for “sumo” can’t be found."). How was this resolved?

Thank you
