### ISSUE TITLE
WalkingArea will covered all junctions, when I creat a sidewalk.Although the two intersections are not connected

### ISSUE THREAD

**Issue by skrillexxu** [eclipse/sumo#11934]
I create a sidewalk like this
<img width="447" alt="8BF8878C-E554-4a00-B271-900966DF5071" src="https://user-images.githubusercontent.com/45363596/199176496-f90e9a26-5f91-4820-8050-f1bea7cd8ba5.png">
but,walkingArea covered all junctions.
<img width="279" alt="A6CDE437-09CF-4b40-AC85-735DB6BB91D7" src="https://user-images.githubusercontent.com/45363596/199176881-ea3f0d8d-d811-4a61-865a-104d00c3dd36.png">
How can I delete this walkingArea?
And this walkingArea makes me can't see the traffic Light
<img width="915" alt="B09E9CD3-4C7C-4aca-8536-4BCC10F28AFD" src="https://user-images.githubusercontent.com/45363596/199177536-04707554-ef96-4431-819a-db8eaa4b7ca8.png">

**Comment by namdre** [comment]
a walkingarea connects all adjacent pedestrian lanes at the junction. To fix this, disallow pedestrians on all lanes that should be exclusive to cars (happens automativcally if you use the 'add sidewalk' function).
See https://sumo.dlr.de/docs/Simulation/Pedestrians.html#building_a_network_for_pedestrian_simulation
