### ISSUE TITLE
vehicle stop when space is enough

### ISSUE THREAD

**Issue by Eviannn** [eclipse/sumo#11937]
hi,

i use sublane model and when i use junctionn to connect 4 lanes and 5 lanes, i find some vehicles stop when the space is enough.

Hope u can help! Thank u very much.

![屏幕截图 2022-11-01 174114](https://user-images.githubusercontent.com/89377838/199205668-391348c6-41f7-4443-a9ed-7665bfcbcd92.png)
![屏幕截图 2022-11-01 174418](https://user-images.githubusercontent.com/89377838/199205817-299677d6-3ad5-4ec0-ae3d-7997d2f57e5f.png)

**Comment by m-kro** [comment]
Could you please add the simulation files to this issue for further checks?

**Comment by behrisch** [comment]
Please add a comment if you have further input
