### ISSUE TITLE
possible simplification for edge/lane permission dialog

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#11940]
currently, both the 'allow' and 'disallow' attributes provide a button for opening a dialog.
However, that dialog always configures 'allow'. (it sets the list of all allowed things).

The UI might be more obvious if we remove the button for 'disallow' 

@palvarezlopez  what do you think about this?

**Comment by palvarezlopez** [comment]
Right. We can unify both allow/disallow  in the same double-Row with a common button:

![Untitled](https://user-images.githubusercontent.com/8238561/200850942-7a1a6243-dca5-49a1-9a27-eee70b8c704a.png)

What do yo think?

**Comment by namdre** [comment]
I'm not sure if we really need a double button (it might look ugly). Since the dialog effectively sets 'allow' I think a single button for 'allow' is enough.

**Comment by palvarezlopez** [comment]
@namdre it was a quick prototip with paint, the real will be prettier. The question is that could be a little bit confusing to have one parameter with dialog and another without dialog, having a big relation between both.

**Comment by namdre** [comment]
Actually, I don't see the problem with 'disallow' not having a dialog because many parameters don't have dialogs.
I rather see the old ambiguity of whether this dialog defines the 'allow' value or the 'disallow' value. (and even though it indirectly defines both, It's more accurate to say that it defines 'allow').

**Comment by palvarezlopez** [comment]
ok, then I'm going to disable "Disallow" button
