### ISSUE TITLE
Install sumo==1.8.0 in macOS

### ISSUE THREAD

**Issue by Catalpae** [eclipse/sumo#11944]
I would like to install an older version of sumo==1.8.0 in macOS. However it seems that the installation of this older version in macOS is not possible from the Python packaging index

Is there any method to install an older version of sumo==1.8.0 in macOS?

**SUMO-version:** 1.8.0

**operating system:** macOS

**Comment by behrisch** [comment]
You are right, this version does not exist for mac on pypi but you can always build it yourself, see https://sumo.dlr.de/docs/Installing/MacOS_Build.html. Instead of cloning the sumo repo you should download the source release https://sumo.dlr.de/releases/1.8.0/sumo-src-1.8.0.tar.gz
