### ISSUE TITLE
Does the period variable affect retrieve when defining the e2 detector?

### ISSUE THREAD

**Issue by JamesPsh** [eclipse/sumo#11945]
Does the period variable affect retrieve when defining the e2 detector?

**SUMO-version: 1.14.1

**operating system: window

**Comment by m-kro** [comment]
The period attribute is used to aggregate the detector values across a series of time intervals. The aggregated values are written to the detector output files. So if you intend to process [this output file type](https://sumo.dlr.de/docs/Simulation/Output/Lanearea_Detectors_%28E2%29.html#generated_output) after the simulation, then it determines how many "data rows" (actually XML items) you get for the same simulation time. If you intend to work with TraCI, there you'll always get the values of the last time step, no matter which period you choose in the detector definition.
