### ISSUE TITLE
crash if gzipped outputfile cannot be opened

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#11954]
```
Writing network ... terminate called after throwing an instance of 'std::length_error'
  what():  basic_string::_M_replace_aux
```
Plain XML writing works just fine

**Comment by behrisch** [comment]
still crashes on windows

**Comment by behrisch** [comment]
It seems to be an issue with our msvc runtime. It works if I delete msvcp140.dll from the bin folder. @palvarezlopez The files we ship in SUMOLibraries are almost three years old. Can we update them?

**Comment by palvarezlopez** [comment]
sure!
