### ISSUE TITLE
The stop line at the junction

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#11957]
Can I design a stop line in SUMO, keep the stop line in the picture below (because I want to use the internal line point)and regenerate a new line as the really stop line (the vehicle stop at the midpoint of the really stop line before entering the intersection)?
![image](https://user-images.githubusercontent.com/54823725/200154656-8e42fd7e-c002-4bb7-b8ff-edddd6607af0.png)

**Comment by namdre** [comment]
Sorry but you picture isn't clear to me. Please draw in the point where you wish the car to stop.

**Comment by a-123-du** [comment]
> 抱歉，您的图片和文字描述我不清楚。请画出您希望汽车停下来的点。

![image](https://user-images.githubusercontent.com/54823725/200214057-ed4869b2-eca2-41a5-affc-2e1e400fd6ad.png)
like the yellow line ,I want this line as the stop line

**Comment by namdre** [comment]
you can use edge or lane attribute 'stopOffset' to move the stop line upstream.

**Comment by a-123-du** [comment]
> 您可以使用边或车道属性“stopOffset”将停止线向上游移动。

Ok ,thank you

**Comment by a-123-du** [comment]
> > 您可以使用边或车道属性“stopOffset”将停止线向上游移动。
> 
> Ok ,thank you

I don't want to set it in netedit manually, Is there a method to set StopOffset in traci? I haven't found it.
![image](https://user-images.githubusercontent.com/54823725/200259285-f285dc83-d956-43b4-90de-065760f21856.png)

**Comment by namdre** [comment]
No. The stop-offset ist a network property (think of a line that is painted onto the road).
However, you can use vType attribute `jmStoplineGap' (https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#junction_model_parameters) to affect the stopping distance from the stop line.  Unfortunately, this attribute cannot currently be set at runtime but you could pre-define vTypes in xml input and use TraCI to switch between the types.
