### ISSUE TITLE
How to parse the desired attributes from net.xml?

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#11964]
How to get the coordinates of shape values corresponding to each internal lane is shown in the figure?Does traci or sumolib provide interface methods? Besides,how do you get the built-in lane id based on the inbound and outbound lanes?（This is shown in the second picture below）
![image](https://user-images.githubusercontent.com/54823725/200498047-d0df1adb-f4b8-45cb-a785-3c0bbb7b5136.png)
![image](https://user-images.githubusercontent.com/54823725/200500425-08fe7a13-3d7b-4353-815a-e6e1cd969c0d.png)
**SUMO-version:**

**Comment by m-kro** [comment]
This is very close to what you already asked in #11873 . There we already explained how to use sumolib to access lane shapes (including internal lanes). In the same package, you can find a method to query the "via" lane (see [sumolib.net.connection](https://sumo.dlr.de/pydoc/sumolib.net.connection.html)):

```
net = sumolib.net.readNet(sys.argv[1], withInternal=True, withLatestPrograms=True)
lane = net.getLane("SC_0")
firstVia = lane.getOutgoing()[0].getViaLaneID()
```
