### ISSUE TITLE
Trouble while using a custom car following model with traci

### ISSUE THREAD

**Issue by thibault-charlottin** [eclipse/sumo#11960]
Hello,

I have successfully implemented a custom car following model into SUMO that works fine with either SUMO and SUMO gui.
Yet I am still trying to use this model with Traci.

In the documentation, I don't get where I am supposed to declare the existence of the new CF model so that I can use it.

Thanks in advance !

Thibault Charlottin

**Comment by namdre** [comment]
It's currently not possible to change the carFollowModel via TraCI and there is not place where the new model must be declared.
To switch between models, pre-define diffrent vTypes in xml input files and then use `traci.vehicle.setType` to switch between them.
