### ISSUE TITLE
Changing the Weight of Lanes

### ISSUE THREAD

**Issue by sokyoei** [eclipse/sumo#11965]
In the simulation process, I want to reduce the probability of certain lanes being selected (these lanes change over time). I try to add a weight file, but its default value is not what I need. What should I do?

**SUMO-version: 1.14.1**

**operating system: win10**

**Comment by m-kro** [comment]
Vehicles choose lanes based on their route and the [lane change model](https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#lane-changing_models) settings. Weight files are used in routing, but don't play any role when driving on a certain edge. You can tweak somehow whether most vehicles would choose the outermost lane, overtake and when they change lane by setting parameters of the lane change model. However the lane choice is an outcome of the simulation, not an input. At least you cannot impose it with given percentages for certain lanes.

**Comment by namdre** [comment]
To discourage/encourage a specific lane you may
- set waypoints (https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#stops_and_waypoints)
- lower / raise the speed limit of that lane (this will influence lane changing behavior)
