### ISSUE TITLE
Integrate options for marker and linestyle into the visualization helper.

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#11985]
see a36e90ce5b627de705c025f945cdf61486dc2f11

refactoring related to #1197

**Comment by m-kro** [comment]
Options have been integrated into the common options set. As their usage depends on the chart type, they should be applied in the proper visualisation script (not in the helper as some options like ticks/title/etc are). _As far as I remember, Matplotlib does not offer the same style parameters for all chart types and returns an error when an illegal parameter is given._
