### ISSUE TITLE
[tools/plotXMLAttributes] Make the tool accept wildcards in IDs for filtering purposes.

### ISSUE THREAD

**Issue by bcoueraud87** [eclipse/sumo#11981]
It would be nice to filter the IDs using a wildcard; for instance `-filtered-ids 'bus_*'` would filter out all the attributes that begin with the characters 'bus_'.

**Comment by bcoueraud87** [comment]
@namdre Please assign me.

**Comment by behrisch** [comment]
solved with #11998
