### ISSUE TITLE
Example not running in Sumo installed with Docker

### ISSUE THREAD

**Issue by vijay-jaisankar** [eclipse/sumo#11999]
## Context
 A Docker image was built using `Dockerfile.ubuntu.latest` as follows:
```sh
docker build -t sumo:latest - < Dockerfile.ubuntu.latest --quiet
```

An instance of this image was then spun up using the steps mentioned in the file:
```sh
docker run -it sumo:latest bash
```
## Issue 
Continuing with the documentation provided in the file, the following command was attempted but it was met with an error:
```sh
sumo -c $SUMO_HOME/docs/examples/sumo/busses/test.sumocfg
```

Error: `Error: Could not access configuration '/usr/share/sumo/docs/examples/sumo/busses/test.sumocfg'. Quitting (on error).`

---

On further inspection, `$SUMO_HOME` of the image only contained the following folders:
![Docker Image ls command](https://user-images.githubusercontent.com/56185979/200963779-6804c79b-fc08-4d83-ad6c-91cdbf54bdac.png)
and hence the example file could not be run as the docs folder doesn't exist.

## System Information

**SUMO-version (of the version installed in the image):** 1.15.0
![Sumo version in the image](https://user-images.githubusercontent.com/56185979/200964286-21a6bf3e-1acb-4312-a292-59a2340c9103.png)

**Operating system (underpinning the image):** Ubuntu 18.04.6 LTS (Bionic Beaver)

**Comment by behrisch** [comment]
work is done in #5724
