### ISSUE TITLE
Libsumo can only be loaded with Python 3.8 on Windows platform

### ISSUE THREAD

**Issue by jjyyxx** [eclipse/sumo#11990]
On the Linux platform, the `_libsumo.so` can be loaded with multiple versions of Python (at least 3.7~3.9). But on the Windows platform, `_libsumo.pyd` can only be loaded with Python 3.8. `depends` confirms that it requires a `python38.dll` to be loaded.

Did I miss something? Is it a (documented) practical limitation for the Windows platform, or can it be improved?

**SUMO-version:** 1.13.0 ~ 1.15.0

**operating system:** Windows 10

**Comment by behrisch** [comment]
Did you install via pip or build yourself / use the release?

**Comment by jjyyxx** [comment]
Using this link https://sumo.dlr.de/releases/1.15.0/sumo-win64-1.15.0.msi

![image](https://user-images.githubusercontent.com/13808089/200821173-0746cba6-3d2c-4c6f-b778-982ec971df72.png)

**Comment by behrisch** [comment]
OK, please try using `pip install libsumo`, see #11992

**Comment by jjyyxx** [comment]
@behrisch Thanks for your suggestion and I can confirm this works. (though I seldomly use `libsumo` on my Windows laptop, only use `sumo-gui`)

But one more thing to ask, why `libsumo` in a system-wide sumo installation work for Linux? Is this a limitation of swig and `Py_LIMITED_API` on Windows (I do not know much about swig)? I hope this could be fixed instead of removed if possible.

And, if `libsumo` has to be removed (#11992), `libtraci` has the same problem and shall also be removed.

**Comment by behrisch** [comment]
I think it is different on Linux because we do not have self-built binaries from our own build server there but we build using either launchpad or the open build service directly within the districution so it will alwas use the "stock" python of the distribution. On Windows there is no such thing as a "stock" python. So if you install a different than the standard python on Linux you will encounter the same problems.

**Comment by jjyyxx** [comment]
@behrisch That may not be true. I use miniconda in Linux to manage different Python versions. Ubuntu 22.04.1 comes with Python 3.10, but I tested Python 3.9 ~ 3.11, all of which can load `libsumo` successfully. Python 3.7 ~ 3.8 fails to load with
```
ImportError: /usr/share/sumo/tools/libsumo/_libsumo.so: undefined symbol: PyCMethod_New
```
error message though.

**Comment by behrisch** [comment]
OK good to know. So maybe there were simply no API breaking changes inbetween. So if we build with python 3.10 on Windows it could work with the 3.9-3.11 as well? I still think removing it is the safer path.

**Comment by jjyyxx** [comment]
Maybe the loading mechanism is different. The Windows build explicitly depends on `python3x.dll` (from `depends`), but the Linux build shows no direct dependency (from `ldd`). So, I see no chance that a direct Python 3.10 build would work on Windows, only something through `Py_LIMITED_API` may work (but tricky).

Now that I understood the problem, I agree that `libsumo` and `libtraci` shall be removed from the Windows installation. Thanks for your kind explanation.
