### ISSUE TITLE
default dropOffDuration not via traci.vehicletype

### ISSUE THREAD

**Issue by rummel123** [eclipse/sumo#11993]
I can get the `dropOffDuration` (and the `pickUpDuration`) via traci with `traci.vehicletype.getParameter(id_vtype, 'device.taxi.dropOffDuration')` or `traci.vehicle.getParameter(id_vehicle, 'device.taxi.dropOffDuration')`. But only with `traci.vehicle` I get the default value. I guess it should work for both.
See documentation here: https://sumo.dlr.de/docs/Simulation/Taxi.html#customer_stops

**Comment by namdre** [comment]
No. There is a difference between normal vType attributes and params:
- if you ask a vehicle for a vType attribute it looks it up in the vType itself and so you have consistency
- if you as for a param it really matters whether the param was defined for the vehicle or the vType in the input.

**Comment by rummel123** [comment]
sure, but in the documentation it is not clear whether the default value for dropOffDuration is defined in the vehicle or the vtype. The code example suggests that it is defined in the vtype. Only 

> duration for drop-off stop can be configured with vType/vehicle param "device.taxi.dropOffDuration" (default "60")

gives a hint, that it could also be defined in the vehicle.
Now it know it ;-)
