### ISSUE TITLE
Issue in handling oneway/two-lanes/lefthand roads when converting .osm to .xodr

### ISSUE THREAD

**Issue by danigian** [eclipse/sumo#11995]
We would like to convert .osm to .xodr using netconvert, for following import in CARLA simulator.

When running the following conversion `netconvert --proj "+proj=tmerc" --geometry.remove --ramps.guess --edges.join --junctions.join --roundabouts.guess --default.lanewidth 4.0 --osm-files london.osm --opendrive-output london.xodr --keep-edges.by-type "highway.motorway, highway.motorway_link, highway.trunk, highway.trunk_link, highway.primary, highway.primary_link, highway.secondary, highway.secondary_link, highway.tertiary, highway.tertiary_link, highway.unclassified, highway.residential" --osm.layer-elevation 4.0 --no-turnarounds --lefthand` something is off with the generated OpenDrive file

In this [london.zip](https://github.com/eclipse/sumo/files/9971457/london.zip) you can find source .osm and target .xodr

As you can notice in the following image, successor and predecessors are computed wrongly. Light blue lane is highlighted and should *not* be connected to the green/orange successor/predecessor, the dark blue lane should be connected to these lanes.

![image](https://user-images.githubusercontent.com/1955514/200841489-ba6f2739-338f-4c11-94a7-b1bcdbf0ee46.png)

Any hint on understanding what we are doing wrong?

**SUMO-version:** 1.15.0

**operating system:** Windows 11

**Comment by danigian** [comment]
@namdre I saw you self-assigned this 2 days ago. Could you anticipate if we are doing something wrong or there's a bug in netconvert?

Thanks

**Comment by namdre** [comment]
My guess would be on a netconvert bug. Can you provide the IDs of the edges involved?

**Comment by danigian** [comment]
Hi @namdre,
I decided to reproduce the issue with a very simple .osm (so there are fewer IDs involved)

Please have a look at the attached zip file
[simple_repro.zip](https://github.com/eclipse/sumo/files/9989777/simple_repro.zip)

Thanks

**Comment by namdre** [comment]
Thanks! It's now fixed and you can get an updated version tomorrow at https://sumo.dlr.de/docs/Downloads.php#nightly_snapshots

By the way: Is it relevant for you whether the lanes have negative indices or positive indices? Usually, the left side of the road has positive indices but the current sumo export doesn't really combine the who sides anyway.

**Comment by danigian** [comment]
Thanks for the fast fix @namdre, it is really appreciated!

As of today, I can't give you an answer on whether the indices have to be positive. I think that, given the fact the two sides are not combined but are actually exported as two different roads, it does not matter whether they are positive or negative.

I noticed also a weird behavior on handling sidewalks in these lefthand worlds, can I file a bug and kindly ask you to have a look at it to provide your input?

**Comment by namdre** [comment]
> I noticed also a weird behavior on handling sidewalks in these lefthand worlds, can I file a bug and kindly ask you to have a look at it to provide your input?

Yes. Small failure examples of the kind previously provided are much appreciated.

**Comment by khibuya** [comment]
Is the solution released as the "--opendrive-output.lefthand-left" netconvert option, 
to deal with issues in the handling lefthand oneway roads when converting osm to xodr ??
(https://sumo.dlr.de/docs/netconvert.html)

But, I can't use "--opendrive-output.lefthand-left" option on the latest netconvert (1.15.0). 
Can I ask in which netconvert version that option is available ??

**Comment by namdre** [comment]
> Is the solution released as the "--opendrive-output.lefthand-left" netconvert option, to deal with issues in the handling lefthand oneway roads when converting osm to xodr ?? (https://sumo.dlr.de/docs/netconvert.html)
> 

The option is only for changing the writing style (whether positive or negative lane numbers are used )

> But, I can't use "--opendrive-output.lefthand-left" option on the latest netconvert (1.15.0). Can I ask in which netconvert version that option is available ??

The option is not yet available in 1.15.0 but in the development version (and in 1.16.0 scheduled for release on Feb 7th).
However, you likely won't need the option since that version also fixes general problems with lefthand networks.

**Comment by khibuya** [comment]
I have now understood the meaning of --opendrive-output.lefthand option and that netconvert default functionality will be updated about lefthand network on version1.16. Thank you very much for your response.
