### ISSUE TITLE
Speed gain considering occupancy 

### ISSUE THREAD

**Issue by Eviannn** [eclipse/sumo#12009]
Hi,

When I use lc models I find that many vehicles can only change lane to gain speed when their speed = 0, I think it is not real so I turn to lc2013 code.

I find that as for speed gain, there are 2 main conditions to execute. One is comparing probability with threshold, I wonder if we could give relativegain a factor named relativegain _factor (>1) to make vehicle change lane earlier instead of changing when they stop. Another is neighdist/max(.1,speed)>20, I wonder if we can give another factor to increase the right value or decrease the left value.

All I wanna do is to make vehicles change lane earlier to gain speed.

Another way is to put occupancy into speedgain judgement directly.

I do not know if my idea is right, hope u can help! Thx.

**Comment by m-kro** [comment]
What values did you set the lane change model parameters to (see [parameter table](https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#lane-changing_models) in the docs)?

**Comment by Eviannn** [comment]
> What values did you set the lane change model parameters to (see [parameter table](https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#lane-changing_models) in the docs)?

I tried a lot but existing parameters can not fix this problem

**Comment by m-kro** [comment]
Could you share your scenario? Then it is easier for us to check..

**Comment by Eviannn** [comment]
> I recommend that you set parameter `lcSpeedGainLookahead`. By default this is 0 which leads to insufficient foresight when approaching an obstacle. See https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#lane-changing_models

I have tried to set a large value to lcSpeedGainLookahead, but it did not work.

**Comment by namdre** [comment]
Then please share a minimal version of your scenario that shows the problem you are facing (attached as a zip archive to this ticket).
