### ISSUE TITLE
plotXMLAttributes.py: allow displaying human-readable-times on axes

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#12011]
needs an option to specify which axis should have its labels converted

**Comment by m-kro** [comment]
Follow-up of #11972

**Comment by m-kro** [comment]
This looks more like a common option for the visualisation scripts:
- xtickformatter
- ytickformatter

**Comment by m-kro** [comment]
Time formatters are already implemented in 

https://github.com/eclipse/sumo/blob/29852acc432f24992142c395e44b4e6c7e4df94e/tools/sumolib/visualization/helpers.py#L65-L72

Is there need for more? Like add a date offset / enter custom date format?

**Comment by namdre** [comment]
oh nice! I wasn't aware of these options.
This is pretty much working as needed then.

I think it would be nice to add --xtime0 / --ytime0 to have time as (hh)  though. (This implies that the tick spacing should also be multiples of full hours).
