### ISSUE TITLE
Unable to use SUMO in Mininet Wifi.

### ISSUE THREAD

**Issue by 14vv1A0516** [eclipse/sumo#12027]
When I run vanet_sumo.py from [here](https://github.com/intrig-unicamp/mininet-wifi), it doesn't find SUMO and traCI connection fails.
![image](https://user-images.githubusercontent.com/18321698/201475487-05890ed2-c83e-4220-96b2-80feaa3c2d91.png)

I can run run sumo configuration file successfully using **sumo-gui -c 'cfg_file.sumocfg'** command.  I imported sumo class and the error happens here in the code.
![image](https://user-images.githubusercontent.com/18321698/201475717-da93c0c7-160d-4dad-88f5-24617eafa213.png)

![image](https://user-images.githubusercontent.com/18321698/201475638-fde83cda-e4d1-4b5e-b564-3dd08712a1df.png)

Sumo version: v1.5
![image](https://user-images.githubusercontent.com/18321698/201475601-8dc127d1-12f8-401d-87ce-7b1f5377e744.png)

**Ubuntu 22.04**

Thank you.

**Comment by namdre** [comment]
possibly your installed sumo wasn't built with gui support. This can happen if the dependency `libfox` is missing.
If you cannot call 'sumo-gui' on the command line but `sumo` is working then this is the most likely explanation.

**Comment by behrisch** [comment]
@14vv1A0516 says he can run sumo-gui form the command line so it is probably there. IMO the problem is rather that vanet-sumo runs with sudo see also the comment here: https://stackoverflow.com/questions/74419669/unable-to-connect-sumo-with-mininet-wifi

**Comment by 14vv1A0516** [comment]
The explanation was submitted here. It says os.environ doesn't exactly get SUMO_HOME variable in the checkBinary API.

https://stackoverflow.com/questions/74419669/unable-to-connect-sumo-with-mininet-wifi

**Comment by behrisch** [comment]
I just opened intrig-unicamp/mininet-wifi#470 which hopefully resolves this issue for other users. Their install script always builds the head of the main branch in SUMO which IMO is not a great idea especially if you run sumo with root privileges afterwards. But probably it is intended to be used in a VM or docker environment.
