### ISSUE TITLE
Real-time value acquisition from e2 detector

### ISSUE THREAD

**Issue by e1958229** [eclipse/sumo#12026]
I want to run deep reinforcement learning using the values obtained every step from the e2 detector, but when I try to get the information from the xml file generated by the detector, I get the error xml.etree.ElementTree.ParseError: unclosed ParseError: unclosed token: line 3, column 0. I know why, because I am getting the information while the simulation is running and the output from the detector to the xml file is in progress. If anyone knows how to solve this error or how to get the information from the detector in a different way, please let me know. (I am using a translator)

PS
The value I want to get is meanhaltingduration, which is the average stopping time of the vehicle. Eventually the average stopping time of all vehicles will be used for training.

(base) PS C:\Users\tomya\SUMOmain> python experiment.py
C:\Program Files (x86)\Eclipse\Sumo\
With SUMO gui? (0=no, 1=yes):1
Traceback (most recent call last):
  File "experiment.py", line 98, in <module>
  File "experiment.py", line 41, in main
    ave_waitingTime = detector_output() #検知器のデータ
  File "experiment.py", line 71, in detector_output
    tree = ET.parse(result)
  File "C:\Users\tomya\anaconda3\lib\xml\etree\ElementTree.py", line 1202, in parse
    tree.parse(source, parser)
  File "C:\Users\tomya\anaconda3\lib\xml\etree\ElementTree.py", line 595, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: unclosed token: line 136, column 3

![スクリーンショット 2022-11-12 023917](https://user-images.githubusercontent.com/113490031/201397797-db6dbae9-9e5c-4f20-b9bc-4d07ad142bd8.png)

**Comment by m-kro** [comment]
Yuu can use TraCI for this. See 

- TraCI [general intro](https://sumo.dlr.de/docs/TraCI.html)
- [query lanearea detectors](https://sumo.dlr.de/docs/TraCI/Lane_Area_Detector_Value_Retrieval.html)

**Comment by e1958229** [comment]
First of all, I apologize for the delay in replying. And this is the part I didn't write, the information I want to get is meanhaltingduration, which is the average stopping time of the vehicle, can I get this by combining traci, etc.?

**Comment by namdre** [comment]
There is currently no traci function to retrieve this directly though it is planned for the future  (#12029).
Currently, you could replace your E2 detectors with E3 detectors to obtain the meanHaltsPerVehicle as well as the meanTimeLoss (which is strongly correlated with meanHaltingDuration). 
Another alternative would be to track the speeds of vehicles in the detector area during each simulation step directly in your script (thereby computing the desired statistics yourself).

**Comment by e1958229** [comment]
First, I apologize again for the delay in replying. And I really appreciate you providing me with all this information. I will try the information you gave me. Thank you very much.
