### ISSUE TITLE
get all node and edge ids and information in net.xml

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#12036]
Can you get all node and edge ids and information with sumolib in net.xml?
I only know how to get the information about the ID of  specified node
![image](https://user-images.githubusercontent.com/54823725/201567562-6a6fe0e3-28e5-4b1a-91fc-ec35b4144a22.png)

**SUMO-version:**

**Comment by namdre** [comment]
`net.getNodes` and `net.getEdges` (https://sumo.dlr.de/daily/pydoc/sumolib.net.html)
