### ISSUE TITLE
 index of connection

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#12035]
Where is the index of connection represented in the .net.xml？I know the index 0 is  corresponded to the right turn lane in the north, and the index number is increased clockwise, but I want to know the connection corresponding to the request index(as shown below).
![image](https://user-images.githubusercontent.com/54823725/201560123-f148e9a4-e7f7-4560-8bc8-0f3794104d7a.png)

**SUMO-version:**

**Comment by namdre** [comment]
the index is implicit in the ordering within the .net.xml file. You can use `sumolib.net.node.getLinkIndex(connection)` to retrieve it.

**Comment by a-123-du** [comment]
> 

How to get all connections in the net? I cannot find the function in sumolib

**Comment by namdre** [comment]
for each lane call `getOutgoing`
