### ISSUE TITLE
add a parameter in algorithm

### ISSUE THREAD

**Issue by sokyoei** [eclipse/sumo#12037]
Hi, I am now working on a project to simulate evacuation. Now I want to add an input parameter to the routing algorithm (dijkstra, astar, etc.), so that the algorithm can make some path choices based on this parameter (as far as possible, the algorithm can decide by itself). I have found a lot of information on the Internet, but it is not different from my situation. Can you help me? Could you be more specific?

**SUMO-version: 1.14.1**

**operating system: win10**

**Comment by behrisch** [comment]
You can give custom weights (think travel times) to edges in SUMO and influence the decisions that way. You can of course also  try to modify the network and add some edges in places you want to block etc. Everything real multiparametric will need a major redesign and should probably done outside of SUMO for now. You can however still feed the caclulated routes in the simulation using traci/libsumo.

**Comment by sokyoei** [comment]
Hello, the path to be controlled by the algorithm in the simulation is changing (once every 1000 seconds to simulate diffusion). Whether the added weight file can change with the simulation

**Comment by behrisch** [comment]
You can also change the weights dynamically using traci/libsumo either per vehicle: https://sumo.dlr.de/pydoc/traci._vehicle.html#VehicleDomain-setAdaptedTraveltime or per edge

**Comment by sokyoei** [comment]
OK, I'll try. Thank you.
