### ISSUE TITLE
show aggregated detector values in parameter dialog

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#12031]
can rely on the same infrastructure as #9501, #12029, #12030

- [x] E1
- [ ] E2
- [x] E3

**Comment by KEYAGO** [comment]
@namdre Thank you for the 1.16 version and the improvements. When the simulation is finished, the detector data returns to its default values. Is there a setting for this that I'm not aware of?

![image](https://user-images.githubusercontent.com/116079618/217803211-cba4a177-a2b9-4f1f-9cd5-7d359169afdf.png)

**Comment by namdre** [comment]
Once the simulation ends, the current interval is written to the output file and the file is flushed.
Writing implies the following actions:
- the values are stored as *last interval*
- all values of the current interval are reset

Depending on the aggregation period this final interval may be quite short and thus appear to not have any data.
I.e. period=300 and end=310 would give a final interval of 10s that might not have had any vehicles recorded.
According to your screenshot, the detector didn't have any traffic for the last 147 seconds of the simulation.

As a workaround, you could let the simulation end on a detector interval boundary or load a detector without period that covers the whole simulation.
Note, that you can also track the values in an extra window if you wish to observe/record the data from all intervals: https://sumo.dlr.de/docs/sumo-gui.html#plotting_object_properties
