### ISSUE TITLE
Sidewalk handling in lefthand roads when converting .osm to .xodr 

### ISSUE THREAD

**Issue by danigian** [eclipse/sumo#12038]
As #11995, we would like to convert .osm to .xodr using netconvert, for following import in CARLA simulator.

When running the following conversion `netconvert --proj "+proj=tmerc" --geometry.remove --ramps.guess --edges.join --junctions.join --roundabouts.guess --default.lanewidth 4.0 --osm-files london.osm --opendrive-output london.xodr --keep-edges.by-type "highway.motorway, highway.motorway_link, highway.trunk, highway.trunk_link, highway.primary, highway.primary_link, highway.secondary, highway.secondary_link, highway.tertiary, highway.tertiary_link, highway.unclassified, highway.residential" --osm.layer-elevation 4.0 --no-turnarounds --lefthand` **`--osm.sidewalks`** something is off with the generated OpenDrive file

Attaching the [simple_repro_sidewalk.zip](https://github.com/eclipse/sumo/files/10001080/simple_repro_sidewalk.zip) including .osm and resulting .xodr

As you can notice in the following image, sidewalks are put in the middle of the street and successor/predecessor in junctions is computed incorrectly.

<img width="847" alt="image" src="https://user-images.githubusercontent.com/1955514/201612207-27808067-cf15-47dd-aa4d-1ca5ac1a09b2.png">

**SUMO-version:** v1_15_0+0211-86805c9d61f

**operating system:** Windows 11

**Comment by danigian** [comment]
@namdre this is the new bug I was mentioning last friday. Thanks for having a look at it 👍

**Comment by danigian** [comment]
Hi @namdre, thanks for fixing this. There is still something off. I opened a new bug #12047 

Could you please have a look? Thanks and enjoy your day

**Comment by namdre** [comment]
No need to open a new bug if it's still the old issue. I'm tracking the new test case here.
