### ISSUE TITLE
How to get the vehicles that will arrive at their destination in the next step?

### ISSUE THREAD

**Issue by Peppebalzanoo** [eclipse/sumo#12039]
I need to get the vehicles that will have arrived at their destination in the next step so that I can assign them a new destination and not let them exit the simulation.

To do this it can be useful to calculate the distance traveled by the vehicle in the next step, but how to calculate it if the speed and acceleration of the vehicle in the next step cannot be obtained?

**Comment by namdre** [comment]
The easiest solution is not to wait until the last step. The maximum speed of a vehicle serves to compute an upper bound of the distance it can travel. If you assign a new destination as soon as the vehicle could theoretically exit, this will typically not be too early. A similar strategy is employed within SUMO:  https://github.com/eclipse/sumo/blob/c66e53cfc8dcbc21fc242afc33fba9e17ca8b048/src/microsim/devices/MSIdling.cpp#L103

**Comment by Peppebalzanoo** [comment]
Thanks  @namdre for the reply.  The solution you propose is similar to the one I currently use.

The solution uses the method getFollowSpeed(self, vehID, speed, gap, leaderSpeed, leaderMaxDecel, leaderID).


I basically pretend that there is a leading vehicle (with the maximum speed allowed for that lane and the maximum deceleration for that type of vehicle) in front of my real vehicle vecID.

getFollowSpeed(vecID, getSpeed(vecID), getMinGap(vecID), getAllowedSpeed(vecID), getDecel(vecID)) 


The speed returned by the getFollowSpeed() method will be a more accurate upper limit (than maxSpeed) of the vehicle "vecID" in the next step, do you agree with me? Or is there something wrong?

**Comment by namdre** [comment]
your reasoning is correct.

**Comment by Peppebalzanoo** [comment]
Hi @namdre , the solution I proposed above seems to work.

But doing several tests, I realized that it doesn't always give an upper bound when the vehicle is in a junction.

So I would like to propose a solution similar to the above (based on the same concept) that seems to solve this problem.

`
curr_position = traci.vehicle.getLanePosition(vecID)
distanceToLastEdge = get_distance_tolast(curr_edgeID, last_edgeID, curr_position)
lane_length = traci.lane.getLength(curr_laneID)

**gap** = lane_length - curr_position

upper_bound = getFollowSpeed(vecID, getSpeed(vecID), **gap**, getAllowedSpeed(vecID), getDecel(vecID)) 
`
The `get_distance_tolast `method calculates the distance in meters from the current road to the destination road using the `traci.simulation.getDistanceRoad ` method.

**Comment by namdre** [comment]
Generally, I'd recommend against using the last possible moment for adapting the route:
- If a vehicle is approaching it's final edge and there is no leading vehicle, then it will have no constraints on speed
- If the route is extended, the vehicle may have to to perform emergency braking when interacting with next intersection that must be passed (i.e. to stop at a red light)
- 
Thus it's much better to adapt the route well in advance to ensure safe speeds (and appropriate lane changing!).

**Comment by Peppebalzanoo** [comment]
Hi @namdre, I agree with you, while implementing the solution I thought it's a good idea to fix the path already when it occurred that the distance to the destination is <= of the upper limit.  That is, actually the route is adjusted when I realize that the vehicle in the next stage will reach the initial position of the destination.  So that the vehicle has plenty of time (because it still has to travel the last previous road) to adjust its speed and, if necessary, change lanes for the new route assigned to it.  Do you agree with me or is there something wrong?

**Comment by namdre** [comment]
Your solution relies on the last edge being sufficiently long. In an OSM derived network you can come across sequences of multiple very short roads so you might still change the route too late with regard to safety and timely lane changing.
