### ISSUE TITLE
invalid selection outline

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#12033]
select mode: when the pointer is over a junction bubble (where a left click would only toggle the selection state of the junction) blue edge outlines should not occur:
![Bildschirmfoto von 2022-11-13 22-55-35](https://user-images.githubusercontent.com/6240630/201546518-46e732f5-5e6a-4cdc-8fa6-0c4fd24167aa.png)

**Comment by namdre** [comment]
regression in 1.15.0 via #11636

**Comment by palvarezlopez** [comment]
![Sin título](https://user-images.githubusercontent.com/8238561/201932335-1f06a6b6-a518-4bc4-b294-1985f20eafc7.png)

Same problem for all elements.

**Comment by palvarezlopez** [comment]
@namdre I think this is not a regression, because the problem exist from the beginning. I cannot found earlier, because I works always with the network compiled, not wit bubbles.

**Comment by namdre** [comment]
The general rule should be: If a left click would open up the disambiguation menu, then all the ambiguous elements should have an outline. If the selected item is clear (no menu) then only this item should have an outline.

**Comment by namdre** [comment]
Technically not a regression because the outlines are a new feature in 1.15.0 so we didn't exactly break something that was working before.
