### ISSUE TITLE
the same object occurs twice in right-click disambiguation

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#12034]
![grafik](https://user-images.githubusercontent.com/6240630/201548296-fbda2e65-9d86-41cc-8d90-1b2a512603bd.png)

**Comment by namdre** [comment]
This should fix the symptoms but what is the actual cause of having the same id twice?

**Comment by palvarezlopez** [comment]
After many tries I cannot reproduce it under Windows :( Could be a Linux problem.
