### ISSUE TITLE
Can vehicle "see" internal lane ahead to change lane for speed gain?

### ISSUE THREAD

**Issue by Eviannn** [eclipse/sumo#12048]
Hi,

I find that vehicle can not change lane for speed gain in the internal lane in advance,  most time they stop and wait, then they realize that they should change lane for speed gain.

However, when I do not use junction, vehicles can change lane for speed gain in the normal lane in advance.

So I wonder if vehicle can "see" internal lane ahead to change lane for speed gain.

![屏幕截图 2022-11-15 175735](https://user-images.githubusercontent.com/89377838/201889536-1208f4bb-c09b-4de5-b317-7e02abd3726c.png)

**Comment by namdre** [comment]
in principle they can and should do this. Lane choice ahead of intersections is often influenced by strategic considerations (the need to be on the correct turn lane). 
If you have a use case where all internal lanes are strategically valid and the expected changing for speed gain does not occur, please attach it here (https://sumo.dlr.de/docs/FAQ.html#how_do_i_report_erroneous_behavior_of_a_sumo_application)

**Comment by behrisch** [comment]
If you have further input just add a comment
