### ISSUE TITLE
sumolib.net.lane.getShape()

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#12041]
Why sumolib.net.lane.getShape() cannot be used? I cannot find the function.
![PR6TGZ@GDMIZ}PRHU{LOGQS](https://user-images.githubusercontent.com/54823725/201647775-6bb2d078-4be0-4319-bd3c-952d7fdb38f3.jpg)
![image](https://user-images.githubusercontent.com/54823725/201648112-094e22e4-04f2-4145-9b46-90d8ddcbaecf.png)

**SUMO-version:**

**Comment by m-kro** [comment]
Please stop asking the same over and over. See #11873 .
