### ISSUE TITLE
Question - Get incoming road lanes for unprioritized crossing

### ISSUE THREAD

**Issue by JulianCzymmeck** [eclipse/sumo#12059]
In order to change pedestrian and vehicle behavior when a pedestrian is intent on entering an unprioritized crossing, I want to look at all nearby incoming vehicles. 
My current solution requires me to look at all vehicles currently simulated and calculate their respective distance to the pedestrian and filter for those that are nearby. It would be way easier and efficient if I could get a list of all (vehicle) lanes crossing the unprioritized crossing.

Is there a more efficient way of getting these vehicles of interest?

Kind regards

**Comment by m-kro** [comment]
Did you have a look at [TraCI context subscriptions](https://sumo.dlr.de/docs/TraCI/Interfacing_TraCI_from_Python.html#context_subscriptions)? Alternatively, you can access vehicles on edges/lanes you are interested in using e.g. [traci.edge.getLastStepVehicleIDs](https://sumo.dlr.de/pydoc/traci._edge.html#EdgeDomain-getLastStepVehicleIDs). You can build a list of edges to assess from the network definition using [sumolib](https://sumo.dlr.de/docs/Tools/Sumolib.html#import_a_network_and_retrieve_nodes_and_edges). Have a look at the linked doc pages to see what fits your task best.

**Comment by namdre** [comment]
You can use `traci.lane.getFoeLanes(crossingID)` which will return the internal lanes that intersect with that crossing.
To build up a map between internal lane ids and their successor and predecessor lanes (which are required to find vehicles with matching routes) you can use `traci.lane.getLinks`.

**Comment by JulianCzymmeck** [comment]
@namdre I already tried your suggestion but didn't manage to get it to work with a crossing. Specifically calling:
```            
if "c" in traci.person.getNextEdge(pedestrian):
    print(traci.lane.getFoes(traci.person.getNextEdge(pedestrian)))
```
leads to following error:
`TypeError: LaneDomain.getFoes() missing 1 required positional argument: 'toLaneID'`
Which doesn't make sense to me, as i quote: 
> If toLane is empty and laneID is an internal lane, the list contains all internal lanes that intersect with laneID.

and as far as I understand, a crossing is an internal lane.

**Comment by namdre** [comment]
My mistake. The call you want is `lane.getInternalFoes(crossingID)`

**Comment by JulianCzymmeck** [comment]
Thank you for your help in that matter, I had misinterpreted `If toLane is empty` as to completely omit this variable.
While I no longer get any errors or problems of that kind, no matter on what unprioritized crossing in whatever city from osm or custom build network I try, `traci.lane.getInternalFoes(crossingID)` or `traci.lane.getFoes(crossingID, "")` does ALWAYS return an empty list. While other lane value retrieval functions on the same crossingID work without issue.
Does this function not support unprioritized crossings?

**Comment by namdre** [comment]
> Does this function not support unprioritized crossings?

It does now after the fix. You can obtain a patched version tomorrow at https://sumo.dlr.de/docs/Downloads.php#nightly_snapshots (or build from the latest sources yourself).

**Comment by JulianCzymmeck** [comment]
Thanks a lot for the quick fix, but I'm not sure if it's working the way it's supposed to.
Specifically in the documentation of your traci.lane.getFoes description I quote: 

> If toLane is empty and laneID is an internal lane, the list contains all internal lanes that intersect with laneID.

But when I call:
```
for internal_foe in traci.lane.getFoes(crossingID, ""):
    print(traci.lane.getLinks(internal_foe))
```
I receive information about all reachable lanes from the crossing. But none about any incoming lanes.

Here is a bad visualization of the lanes I receive information about (marked in blue) and the lanes I am trying to look for (marked in red) when calling the above code on the selected unprioritized crossing:

![paintIntersection](https://user-images.githubusercontent.com/50736721/203022140-24a000ff-e660-459c-9e5f-dcd835a27f0b.png)

Or is this after all not the way to approach finding incoming lanes to any crossing during runtime?
