### ISSUE TITLE
How to use a rerouter?

### ISSUE THREAD

**Issue by e1958229** [eclipse/sumo#12050]
I have a question about the route indicator, I want to change the route of a vehicle that has reached one edge during the simulation, but I am not sure how to use it. Of course, I have tried to do it in my own way, using the Wiki as a reference, but I have not been able to make it have the role of a route indicator that I ideally want. Ideally, I would like to give simple instructions to the vehicle that reaches the edge with the route indicator to go right or left, and to do this during the simulation. I am attaching my current progress (which is not going very well) in case you are interested. I know this is probably a rather elementary question, but thank you in advance.(Im using translator)

![image](https://user-images.githubusercontent.com/113490031/201907386-4e0db64d-e6d6-4c74-8424-eb33c58c1373.png)
![image](https://user-images.githubusercontent.com/113490031/201907615-2ee4d5a3-7c28-45a3-bca6-dc6318526a0f.png)
![image](https://user-images.githubusercontent.com/113490031/201907758-61ecbe3b-3985-4c4c-a480-700044ba9c76.png)

**Comment by m-kro** [comment]
The error you got comes from XML validation process. Please move your route elements to a .rou file. You can load it using the `-r` switch (see [cmd line parameters](https://sumo.dlr.de/docs/sumo.html#input)). Your additional file should then contain the following:
- detector elements
- rerouters (with interval definitions inside)

**Comment by e1958229** [comment]
First of all, thanks for answering my question. And I am ashamed to ask, but I am not sure how to use the -r switch. I have moved the route to the rou.xml file as shown in the attached image.

![image](https://user-images.githubusercontent.com/113490031/201914607-3739a37e-4abf-488f-ba7c-4b397650443d.png)
![image](https://user-images.githubusercontent.com/113490031/201914746-bc05771f-e7a2-4efb-9c0f-714990b00d23.png)

**Comment by m-kro** [comment]
You can read [more about using the cmd line options](https://sumo.dlr.de/docs/Basics/Using_the_Command_Line_Applications.html) in the documentation. 
If you just want to have a basic setup, create a .sumocfg calling
`sumo --save-configuration config.sumocfg -n mynet.xml -r carsetting_main.rou.xml -a myadditional.add.xml`
(replace the file names with those you actually use).
Afterwards load it into sumo-gui and observe what is happening:
`sumo-gui -c config.sumocfg`

**Comment by m-kro** [comment]
Sorry, I didn't remember correctly: The route files are loaded after the additional files, so place again the routes used in the rerouter above the rerouter def. Then the remaining problem is that some edges in your route do not exist. Please correct to
`<route id="gne6togne10_0" edges="gneE6 gneE5 gneE10"/>`

**Comment by e1958229** [comment]
Sorry for the delay after my reply. Thank you for taking the trouble to correct me. I will give it a try. Thanks for all the advice.

**Comment by e1958229** [comment]
When I moved the route definition from the rou file to the additional file, I got the error shown in the image. Is there any way to resolve this? Thank you again and again.

![image](https://user-images.githubusercontent.com/113490031/202484796-799f86c8-53d2-4e5b-9c5d-0c16ba2a24f0.png)
![image](https://user-images.githubusercontent.com/113490031/202485170-d174a92e-3f5d-4118-ba4c-c5a24a4d70a8.png)

**Comment by behrisch** [comment]
The closing tag for the rerouter should be `</rerouter>`.

**Comment by e1958229** [comment]
Thank you so much! It works.
