### ISSUE TITLE
OpenDRIVE: official support for road object export

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#12060]
support for exporting boxes was implemented 49108de6ecef2ae277ee18b04af75a0eaa74085b

- [ ] general shapes should be supported (using `<outline><cornerLocal.../> ...`
- [ ] POI support
- [ ] optional mapping of loaded shapes onto closest edge (**--opendrive-output.match-shapes**)

note: debugging works via https://odrviewer.io/

**Comment by danigian** [comment]
I see from 49108de that roadObjects is parsed from the SUMO network in order to export such boxes. Is there a way to get the roadObjects parameter directly added importing a polygon file into a SUMO network? Or is that something that would need to be added to the backlog?

**Comment by namdre** [comment]
> Is there a way to get the roadObjects parameter directly added importing a polygon file into a SUMO network? 

Yes. See the test added in f24175da4e5d03c93160198b398e1dc24a272b56 which uses the new option
