### ISSUE TITLE
implausibleRoutes.py: unsorted input and vehtype missing

### ISSUE THREAD

**Issue by ambuehll** [eclipse/sumo#12069]
I am currently facing multiple issues with implausibleRoutes.py. 
I use the script to check whether the routes from a sumo sim are realistic. Therefore, I test it on standard route-output from a sumo micro/meso sim. 
The issues below are caused by calling duarouter inside implausibleRoutes.py

1. when I have veh_types in the route file, I have to copy paste the vType_distribution into the route file. Otherwise I get e.g.  `Error: The vehicle type 'car' for vehicle 'F38545' is not known.` 
Copying the vtype dist is not a problem, but not an elegant work-around
2. my routes file is not sorted. So it throws another error telling me the input is not sorted. 

Setting `unsorted-input` in the duarouter call would solve 2. 

Thanks

Lukas

**Comment by namdre** [comment]
Adding two options to the script that can be passed to duarouter (**--additional-files** and **--unsorted-input**) should easily solve this. Would you care to do this yourself and add a pull request? Alternatively, could you be so kind and prepare a minimal input test case. Then I could quickly add a fix myself.

**Comment by ambuehll** [comment]
[aminissn](https://github.com/aminissn) volunteered 🥇

**Comment by behrisch** [comment]
There is still a test missing, I suppose?

**Comment by behrisch** [comment]
@aminissn @ambuehll Do you find the time to add a test here?

**Comment by ambuehll** [comment]
Unfortunately not right now. Sorry. I can try to look into it next month. Maybe @aminissn :)

**Comment by aminissn** [comment]
@behrisch I hope this fulfills the requirements as a minimal test scenario:
[test_implausibleRoutes.zip](https://github.com/eclipse/sumo/files/10166624/test_implausibleRoutes.zip)

**Comment by behrisch** [comment]
4 MB of data is more than what I would call minimal ;-) Nevermind I added a test.
