### ISSUE TITLE
How to generate vehicles from a trip.trips.xml file?

### ISSUE THREAD

**Issue by Peppebalzanoo** [eclipse/sumo#12061]
Essentially I have a trip.trips.xml file and would like to generate a vehicle for each trip in the file.

The quickest fix I've used is to create a script that does this, but I was wondering if there was already a way to do this.

**Comment by m-kro** [comment]
You can actually load trips directly into SUMO and vehicles will get created implicitly for them. If you want to create routes and vehicles from them, you can let SUMO write this as an [output](https://sumo.dlr.de/docs/sumo.html#output):
`sumo -c your.sumocfg --vehroute-output yourRoutes.rou.xml`
You can also run [duarouter ](https://sumo.dlr.de/docs/duarouter.html) to create routes from your trips.

**Comment by Peppebalzanoo** [comment]
Thank you @m-kro
