### ISSUE TITLE
mismatch between optimal and actual cycle duration

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#12068]
in the test case `tls/tlsAdaptation/unified_flows` the verbose output suggests and optimal cycle duration of 120s but the generated signal plan has a cycle time of 126s (for some reason, the timeloss of 18s seems to be estimated as 12s during the calculation).

**Comment by yunpangfloetteroed** [comment]
The different between lost time and yellow time is already considered in the calculation of effective green times. So, only yellow time and all-red are considered when calculating totalLength
