### ISSUE TITLE
incLanes and intLanes

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#12071]
what are inclanes and intLanes of a junction？
I have searched the document ,but I cannot understand, can you explain them easily?
Can the wait point in the intersection be cancelled?
![image](https://user-images.githubusercontent.com/54823725/202457882-9fc837d7-9d39-4852-b68d-c69a544b7337.png)

**SUMO-version:**

**Comment by namdre** [comment]
incLanes are lanes that approach the junction (relevant for right-of-way on approach) and intLanes are all the internal lanes within the junction (relevant for conflict handling between cars that have already entered the intersection).

you can set connection attribute contPos = 0 to cancel a wait point.

**Comment by a-123-du** [comment]
> you can set connection attribute contPos = 0 to cancel a wait point.

how to set connection attribute contPos = 0 to cancel a wait point?
is there any api? Is the api of  connection.setParam(self,key,value) OK?
Also I want to ask why I see the contPos of a connection with the wait point is -1 in netiedit?( the yellow connection in the figure below)
![image](https://user-images.githubusercontent.com/54823725/202602873-996141aa-91f5-4c57-91b2-7df11a619d2c.png)

**Comment by namdre** [comment]
`-1` means: automatically determine whether there should be an internal junction.
See https://sumo.dlr.de/docs/Netedit/neteditUsageExamples.html#setting_connection_attributes
