### ISSUE TITLE
the type of junction

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#12072]
What are the types of junction and what do they mean?
I haven't seen the explanation of the type.
![image](https://user-images.githubusercontent.com/54823725/202459556-2345fefc-d807-4c4e-bd02-db0ed4b43086.png)

**Comment by m-kro** [comment]
see [node types](https://sumo.dlr.de/docs/Networks/PlainXML.html#node_types) in docs

**Comment by a-123-du** [comment]
> see [node types](https://sumo.dlr.de/docs/Networks/PlainXML.html#node_types) in docs



> see [node types](https://sumo.dlr.de/docs/Networks/PlainXML.html#node_types) in docs

but there is not the type "dead_end"，what does the type mean?
![image](https://user-images.githubusercontent.com/54823725/202601121-276ac410-0e9d-489d-95d8-1b833d3bbbea.png)
