### ISSUE TITLE
get foes from linkindex in net.xml

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#12088]
How do I get the foes sequence corresponding to the link index? Is there an api or function of sumolib?
![image](https://user-images.githubusercontent.com/54823725/202655653-7cdcc8a9-b820-4e0e-8c94-5949a9380b55.png)

**SUMO-version:**

**Comment by a-123-du** [comment]
> Is there an api or function of sumolib?

Is there an api or function to get the  correspondence relationship?
I want to get the foes of the requestindex

**Comment by namdre** [comment]
`node.areFoes(index1, index2)`  (where node is a `sumolib.node`)

**Comment by a-123-du** [comment]
> `node.areFoes(index1, index2)`（其中节点是`sumolib.node`)

ok,thank you
