### ISSUE TITLE
macOS sumo-gui crashes immediately

### ISSUE THREAD

**Issue by ambuehll** [eclipse/sumo#12082]
I installed sumo 1.15.0 using homebrew on a mac, M1, Ventura
Build features: Darwin-22.1.0 arm64 GNU 12.2.0 Release FMI Proj GUI Intl

Whenever I open sumo-gui, the window crashes as soon as I open a network/config file. 
sumo itself runs fine. 
See attached gif. 

What I've tried so far:
- building the homebrew formula with gcc12 instead of clang -> didn't help
- building sumo (latest) from scratch -> got errors (clang and gcc12) (I might open a ticket for that separately)
- reinstalled homebrew completely -> still didn't help.

any help would be appreciated. 

![Kapture 2022-11-17 at 23 20 52](https://user-images.githubusercontent.com/48930860/202573031-1c6db4f0-1e47-4f9c-b355-fe214862ae83.gif)

**SUMO-version:** 1.15.0

**operating system:** macOS

**Comment by namdre** [comment]
- does netedit (1.15.0) also crash?
- can you recheck whether a freshly built 1.14.1 release works fine? 
  - if yes, would you be willing to run a git-bisect to find the breaking commit?

**Comment by ambuehll** [comment]
netedit also fails. 
I'll check tomorrow with 1.14.1

**Comment by ambuehll** [comment]
So, I checked the following: 
1.14.1 and 1.12 -> still crashes
installed quartz 2.8.3_rc1 -> still crashes

seems like it's something on my end, but really not sure where to look next...

**Comment by angelobanse** [comment]
Based on the gif animation, i suspect that it's not actually crashing. This is most likely related to https://github.com/eclipse/sumo/issues/12014.
@ambuehll can you check if [this temporary workaround](https://github.com/eclipse/sumo/issues/12014#issuecomment-1310581582) works for you?

**Comment by ambuehll** [comment]
yes, you're right! https://github.com/eclipse/sumo/issues/12014 is exactly what happens.

**Comment by angelobanse** [comment]
Discussion / work will continue in #12014
