### ISSUE TITLE
the type of crossing junction

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#12089]
Must a junction of an intersection or a junction  with internal lanes be priority type?like the J1 junction.
I want to get the crossing junction ,but I am not sure whether its type is always priority or not.
![image](https://user-images.githubusercontent.com/54823725/202667938-f4fde6a3-2e07-4cb6-8ffb-36c7c7604f86.png)

**SUMO-version:**

**Comment by namdre** [comment]
This is something you can easily check yourself: change the junction type and look into the .net.xml.
