### ISSUE TITLE
tracemapper duplicates edges in route

### ISSUE THREAD

**Issue by m-kro** [eclipse/sumo#12094]
Reported on Mattermost by peterbug.

**Comment by m-kro** [comment]
Also maps to one point to road and next one to unconnected bridge crossing the road.

**Comment by m-kro** [comment]
Edges are duplicated when several trace points are nearby the same edge and some are at larger distance than the one set as tracemapper input (standard 1m).

**Comment by pietrolechthaler** [comment]
> Edges are duplicated when several trace points are nearby the same edge and some are at larger distance than the one set as tracemapper input (standard 1m).

I solved this problem by checking when adding a new id in the edge list.
The main problem I think is the fact that by not setting the vehicle type it is possible that an edge type not suitable for cars is chosen, for example, an edge that corresponds to a bike path. This causes an error in the connection of the various edges.

**Comment by pietrolechthaler** [comment]
> Edges are duplicated when several trace points are nearby the same edge and some are at larger distance than the one set as tracemapper input (standard 1m).

A solution could be to add a "type" parameter which, when searching for the closest edge, checks whether the passed type is valid in the internal parameters of the edge.

![immagine](https://user-images.githubusercontent.com/94111800/203066223-22271f20-4979-48bc-8500-19c47c570d52.png)

**Comment by m-kro** [comment]
Obviously, you can edit the route in a text editor to make it conform with what SUMO expects. Actually, the duplicate edges are a plain bug in the tracemapper code which we will solve within short time. Then you will be relieved of correcting the route manually. Thank you for pointing us in that direction!

**Comment by m-kro** [comment]
@pietrolechthaler Now the duplicate edges should be gone. You can increase a bit the search distance for potential route edges using the tracemapper option **--delta [distance in m]**. Use the new option **--vehicle-class passenger** to avoid pedestrian and bike paths. Have a look at all options calling tracemapper.py with **--help**.  
There are still quite some places in your network where the wrong edge gets selected (mostly the opposite direction). This may be due to other problems with tracemapper but to some extent it is due to the network: overlapping edges and roundabouts with extremely short edges inside.
