### ISSUE TITLE
the shape of internal lanes

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#12092]
Is there an api of sumolib to get the shape coordinates of the internal lanes ?
![image](https://user-images.githubusercontent.com/54823725/202694764-37323f49-2560-4f5e-bc43-f64f4c850eeb.png)

**SUMO-version:**

**Comment by m-kro** [comment]
[What should I do to get helpful answers on the mailing list or on the issue tracker?](https://sumo.dlr.de/docs/FAQ.html#what_should_i_do_to_get_helpful_answers_on_the_mailing_list_or_on_the_issue_tracker)

Already answered in #11873 , #12040 , ...
