### ISSUE TITLE
the different colors of the connections

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#12097]
What do the different colors of the connections have different meanings (gray, white)?
![image](https://user-images.githubusercontent.com/54823725/202889894-31665a20-90b5-4197-a1dc-822ecdb1976e.png)

**SUMO-version:1.14.1**

**operating system:Windows**

**Comment by namdre** [comment]
https://sumo.dlr.de/docs/sumo-gui.html#understanding_what_you_see
