### ISSUE TITLE
 the junction id with internal lanes

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#12093]
Is the junction id with internal lanes J1 always ? whatever intersection?
![image](https://user-images.githubusercontent.com/54823725/202703544-af8e917a-9d59-4a57-8ff3-c267bcea1671.png)

**SUMO-version:1.14.1**

**operating system:Windows**

**Comment by behrisch** [comment]
J1 is the default name for the second junction created by netedit. It does not depend on the internal lanes

**Comment by a-123-du** [comment]
> J1 is the default name for the second junction created by netedit. It does not depend on the internal lanes

How do I get the junction ID with the internal lanes?

**Comment by behrisch** [comment]
you mean you want to determine the junction id from the internal lane id?

**Comment by a-123-du** [comment]
I want the junction with the connection, how to get it?

**Comment by behrisch** [comment]
Please be precise. What exactly is your input. An internal lane id?

**Comment by a-123-du** [comment]
> 请准确。您的输入究竟是什么。内部车道 ID？
I want the junction ,which has connections. I want to has its ID using api when I don't open the netedit or net.xml to see the ID.
![image](https://user-images.githubusercontent.com/54823725/203729156-29dda9f0-8a5c-4f7e-8157-fdcbbe5310f3.png)

**Comment by behrisch** [comment]
Which information do you have about the connection?

**Comment by a-123-du** [comment]
> 
I want to have the ID of the junction with connections.How can get the id via an api? 
![image](https://user-images.githubusercontent.com/54823725/204290556-34dfecaa-6f9e-46e3-bfa1-5f9c357635ad.png)

**Comment by behrisch** [comment]
Sorry I am giving up here. I do not understand which information you have.
