### ISSUE TITLE
insertionChecks is not defined for element 'vType

### ISSUE THREAD

**Issue by amin-tabrizian** [eclipse/sumo#12100]
When I try to disable all safety checks in the route file, the following error will be occurred:

**Error: attribute 'insertionChecks' is not declared for element 'vType'**

Here is the code for the route file:

![Screen Shot 2022-11-21 at 1 13 03 AM](https://user-images.githubusercontent.com/34487658/202978176-ccd0dd56-fc6c-471f-9c05-7bc09cb2a9fd.png)

**operating system:**
LINUX 5.11.0-37-generic

**Comment by namdre** [comment]
`insertionChecks` can only be used within the elements `<vehicle>`, `<trip>` and `<flow>.
