### ISSUE TITLE
 a car going straight into the right turn lane

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#12118]
Why would a car going straight into the right turn lane? This can cause deadlock problems.I've put a lane change ban 100 meters from the junction

**SUMO-version:1-14-1**

**operating system:Windows**

**Comment by m-kro** [comment]
Can you show a screenshot how it actually looks like? Does the vehicle really move to a lane it cannot proceed on its route or does it just stop before because changing lanes is difficult?

**Comment by a-123-du** [comment]
> 你能展示一个截图它的实际外观吗？车辆是否真的移动到无法继续行驶的车道，或者只是因为变道很困难而停下来？
Here, I've circled the two cars
![image](https://user-images.githubusercontent.com/54823725/203324175-c8cd12ba-114f-46e5-bab6-aca3e6a7c0ad.png)

**Comment by namdre** [comment]
please attach the zipped scenario files.

**Comment by a-123-du** [comment]
[cross3.zip](https://github.com/eclipse/sumo/files/10067873/cross3.zip)



> 请附上压缩的场景文件。

**Comment by m-kro** [comment]
Happens with veh `01.163` at t 1748.

**Comment by a-123-du** [comment]
Why will it happen?

**Comment by Eviannn** [comment]
> Why will it happen?

先把departlane设成best，应该能解决，不行的话就延长西进口车道
