### ISSUE TITLE
let simpla report platoon-based information and statistics

### ISSUE THREAD

**Issue by thinker310** [eclipse/sumo#12124]
Hello, I wonder if simpla tool can report platoon information including the number of vehicles, platoon average speed, the lane id and the position by some means (e.g. traci) ? I did not find any information on this function and hope it can be developed sooner. Thank you!

**Comment by m-kro** [comment]
@thinker310 We will add helper functions to simpla for some basic information / statistics about the platoons in the future. 
If you cannot wait, have a look yourself at the simpla data structure. The needed data is already gathered by simpla and kept in its data structure, so it is basically about calling Python aggregate functions like len, min, max, avg etc.

**Comment by thinker310** [comment]
> @thinker310 We will add helper functions to simpla for some basic information / statistics about the platoons in the future. If you cannot wait, have a look yourself at the simpla data structure. The needed data is already gathered by simpla and kept in its data structure, so it is basically about calling Python aggregate functions like len, min, max, avg etc.

Hi, where is the instruction for simpla data structure? I only can see the configuration on the parameters in the SUMO documentation. And now I have a specific demand on simpla, I want to get the number of platoons on a certain edge and the id of vehicles in the platoons respectively. Could you help me or give some suggestions? Thank you!

**Comment by m-kro** [comment]
There are no instructions outside of the source code as there was no need fot this. All the simpla code is contained in the folder $SUMO_HOME/tools/simpla. Maybe I find the time during the next days to implement some of your request. Then you'll see how to do it.

**Comment by thinker310** [comment]
> 

Ok, that's great, thank you!

**Comment by m-kro** [comment]
There is some news: I have made information about the platoons more accessible by some functions explained in the [docs](https://sumo.dlr.de/docs/Simpla.html#statistic_helper_functions). You'll need to download the updated simpla files from github or wait until tomorrow to download the SUMO developer version from [here](https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_development_version).

**Comment by m-kro** [comment]
@thinker310 I am interested in whether the changes fulfil your needs in the regard of access to simpla platoons.

**Comment by thinker310** [comment]
> @thinker310 I am interested in whether the changes fulfil your needs in the regard of access to simpla platoons.

Ok, thank you for your help!  I will reply you as soon as possible after finishing some work.

**Comment by m-kro** [comment]
Suggestion on the sumo-user mailing list: Add a method simpla.getPlatoonLeaders()

**Comment by thinker310** [comment]
Hi, I try to call simpla.getPlatoonIDList() command, but the error showed _AttributeError: module 'simpla' has no attribute 'getPlatoonIDList'_ . Need I build a developer version?
My version is SUMO1.16.0

**Comment by m-kro** [comment]
As simpla.getPlatoonIDList() has been added after the v1.16 release, currently it is available only in the developer version (as mentioned in my previous post).

**Comment by m-kro** [comment]
Closed as completed. In case you still have question or comments, just add them here and we will reopen the issue.
