### ISSUE TITLE
unpack requires a buffer of 369607680 bytes

### ISSUE THREAD

**Issue by burakseyitkara** [eclipse/sumo#12122]
**Exception has occurred: error
unpack requires a buffer of 369607680 bytes

  File "C:\Program Files (x86)\Eclipse\Sumo\tools\traci\storage.py", line 38, in read
    return struct.unpack(format, self._content[oldPos:self._pos])
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\traci\storage.py", line 69, in readString
    return str(self.read("!%ss" % length)[0].decode("latin1"))
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\traci\connection.py", line 94, in _sendExact
    err = result.readString()
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\traci\connection.py", line 181, in _sendCmd
    return self._sendExact()
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\traci\connection.py", line 319, in simulationStep
    result = self._sendCmd(tc.CMD_SIMSTEP, None, None, "D", step)
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\traci\main.py", line 228, in simulationStep
    return _connections[""].simulationStep(step)
  File "C:\Users\Burak\Desktop\SocketPython\Server.py", line 50, in sim_trigger
    traci.simulationStep()**

Hello guys, recently i started to work on one sumo traci project. I try to use TCP/IP protocol to send signal  type of byte that adds car to my simulation on time. I have one server and one client file. It works but i cant handle that issue, byte size that shown in error always changes. any ideas?

**1.10.0**

**Windows**

**Comment by namdre** [comment]
what command are you using exactly to add a car?  It sounds as if you might not be using the intended api functions.

**Comment by burakseyitkara** [comment]
> what command are you using exactly to add a car? It sounds as if you might not be using the intended api functions.

I'm using `traci.vehicle.add` command.

**Comment by namdre** [comment]
Please put together a minimal example to replicate your problem

**Comment by burakseyitkara** [comment]
> Please put together a minimal example to replicate your problem

I have 2 major files, server.py and client.py. In server i start SUMO and run simulation without any vech without signal.  i used simulationstep() func for that. Signals that i receive from client are used for which route to create vech. For example if signal is 1, i create vech at road number 1 etc. Also i use threading for handling client's signals and simulationstep loop together. Basicly this is what im working about.

my server.py basicly:
`class Server:
    
    def __init__(self):
        self.header = HEADER
        self.port = PORT 
        self.server = SERVER 
        self.addr = ADDR 
        self.format = FORMAT 
        self.dc= DISCONNECT_MESSAGE 
        self.step = STEP 
        
    server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    server.bind(ADDR)
    
    if 'SUMO_HOME' in os.environ:
        tools = os.path.join(os.environ['SUMO_HOME'], 'tools')
        sys.path.append(tools)
    else:
        sys.exit("please declare environment variable 'SUMO_HOME'")

    #Converting area
    def int_to_bytes(number: int) -> bytes:
        return number.to_bytes(length = (8+(number+(number<0)).bit_length())//8, byteorder='big', signed=True)

    def int_from_bytes(binary_data: bytes) -> Optional[int]:
        return int.from_bytes(binary_data, byteorder='big', signed=True)
    
    def sim_trigger(self):
        print("Sim Trigger")
        while True:
            traci.simulationStep()
            time.sleep(.2)
        
    #Handle client area
    def handle_client(self,conn, addr):
        def int_from_bytes(binary_data: bytes) -> Optional[int]:
            return int.from_bytes(binary_data, byteorder='big', signed=True)
        print(f"[NEW CONNECTION] {addr} connected.")
        connected = True
        while connected:
            msg = conn.recv(1024)
            state = int_from_bytes(msg)

            # print(int_from_bytes(msg))
            match state:
                case 1:
                    traci.vehicle.add(f"vec_{self.step+1}",f"r1_{random.choice([1,2,3,4,5,6,7])}",departLane="best",departSpeed="speedLimit")
                    self.step += 1

**(This cases goes on like that)**

def start(self,server = server):
        server.listen()
        sumoBinary = checkBinary('sumo-gui')
        traci.start([sumoBinary, "-c", "kilis.sumocfg", "--tripinfo-output", "tripinfo.xml","--start","--quit-on-end"])
        route_list = list()
        for i in range(1,8):
            for j in range(1,8):
                if (i == 1 and j == 1) or (i==2 and j==2):
                    traci.route.add(f"r{i}_{j}",[f"{i}_0", f"{j}_1" ])
                    route_list.append(f"r{i}_{j}")
                if not (i == j): 
                    traci.route.add(f"r{i}_{j}",[f"{i}_0", f"{j}_1" ])
                    route_list.append(f"r{i}_{j}")
        # 10 33 22 45 77 66 55
        print(route_list)
        thread = threading.Thread(target=self.sim_trigger)
        thread.start()
        
            
        print(f"[LISTENING] Server is listening on {self.server}")
        # subprocess.Popen(['python', 'Client.py'])
        
        # subprocess.Popen(['python', 'ClientTest.py'])
        while True:
            conn, addr = server.accept()
            thread = threading.Thread(target=self.handle_client, args=(conn, addr))
            thread.start()
            print(f"[ACTIVE CONNECTIONS] {threading.activeCount() - 1}")

obj  = Server()
obj.start()`


my client.py basicly:

`HEADER = 64
PORT = 5050
FORMAT = 'utf-8'
SERVER = "192.168.1.213"
ADDR = (SERVER, PORT)
SIGNAL_LIST = [1,2,3,4,5,6,7,0,0,0,0,0,0,0]

def int_to_bytes(number: int) -> bytes:
    return number.to_bytes(length = (8+(number+(number<0)).bit_length())//8, byteorder='big', signed=True)

def int_from_bytes(binary_data: bytes) -> Optional[int]:
    return int.from_bytes(binary_data, byteorder='big', signed=True)
client = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
client.connect(ADDR)
while True:
    state = random.choices(SIGNAL_LIST,weights=(10,5,5,10,5,1,1,5,5,5,5,5,5,5),k=1)
    msg = int_to_bytes(int(state[0]))
    client.send(msg)
    time.sleep(.2)`


i hope i can explain correctly, i dont know how to explain this basicly. sorry if i cant handle explaining. thanks for your help.

**Comment by namdre** [comment]
The default way of using TraCI is to have a client script that starts sumo and then sumo acts as the server. Basically, you never have to deal with the raw bytes. See https://sumo.dlr.de/docs/Tutorials/index.html#traci_tutorials

**Comment by burakseyitkara** [comment]
i used additional client for send signals that creates vehicles, i simulate real traffic detector with that. my plan i will take real traffic signals from real detectors to make real time simulation on sumo. i already know that sumo acts as the server
