### ISSUE TITLE
sumo-gui crashes with Show Parameter

### ISSUE THREAD

**Issue by Domsall** [eclipse/sumo#12136]
Open sumo-gui.exe
Open Simulation..., start the simulation configuration by stepping.
Right click on a vehicle, Show Parameter -> sumo-gui crashes

**SUMO-version:** v1_15_0+0530-d4e6d777f74

**operating system:** Windows 10

**Comment by palvarezlopez** [comment]
Introduced in https://github.com/eclipse/sumo/commit/ae6756cfd33fafa7143aa94b980702dae58f1511

**Comment by palvarezlopez** [comment]
@Domsall thanks for the report! :)

**Comment by Domsall** [comment]
thanks for fixing it ;-)
