### ISSUE TITLE
long option synonymes are not displayed in the help text

### ISSUE THREAD

**Issue by FrederikRB** [eclipse/sumo#12135]
Hey SUMO-team,

through an error-message during the netconvert process I learned, that netconvert is also able to write a taz-output which is not to be found in the documentation nor the config-template, just to let you know.

Are there any further output-possibilities for netconvert, which are not mentioned in the documention?

SUMO 1.14.1
Windows 10

Thank you and kind regards,
Frederik

**Comment by m-kro** [comment]
Can you please be more specific: Which error message and what exactly is your netconvert call? In any case, it is not intentional if something is missing in the documentation but present in the software - at least for the releases.

**Comment by FrederikRB** [comment]
I do not know anymore which error message it was, however, that was also not the point of the new issue.
I just wanted to point out that the taz-output of netconvert is not mentioned in the documentation.

**Comment by m-kro** [comment]
OK, I found it. `--taz-output` is implemented as a synonyme for `--polygon-output`. Somehow this is not displayed by the **--help** option and not mentioned in the documentation.

**Comment by m-kro** [comment]
Only one character synonymes (e.g. `-r`) are currently treated but multi-character synonyme options are skipped.

**Comment by namdre** [comment]
added documentation in 795fd9712626d518f87ca3c5e4def7ff5deaccf9 and 4100245cf25805180dec0601d888a5d2ea1412d8
