### ISSUE TITLE
Is it safe to store additional metadata in the parameters map?

### ISSUE THREAD

**Issue by dariuszparys** [eclipse/sumo#12132]
We're currently using netconvert to convert openstreetmap data into opendrive data. We need to extend the current conversion with additional tags that can be mapped to opendrive data, like e.g. roadMarks. The question I have, is it safe to place additional data into the `NBEdge` parameters map so we can adjust the importer for openstreetmap and exporter for opendrive to leverage the data their?

**Comment by m-kro** [comment]
We already use parameters to store the original OpenStreetMap IDs in the SUMO network, see netconvert option **--output.original-names**. I think there is no problem in reading parameters in your customised exporter.

**Comment by behrisch** [comment]
@dariuszparys And please consider doing a pull request with your enhancements

**Comment by namdre** [comment]
Note that there is already some infrastructure in place to import additional attributes by setting option **--osm.all-attributes** an **--osm.extra-attributes all**

**Comment by dariuszparys** [comment]
Thanks @namdre I indeed have overlooked this. This reduces the changes to the opendrive export.

**Comment by namdre** [comment]
also: roadMarks should already be exported based on lane change prohibitions. If this doesn't work pleas file a bug report.

**Comment by dariuszparys** [comment]
So there is full support for 6.2 Road Mark Type Information from OpenDrive 1.4?

**Comment by namdre** [comment]
at the moment only the marktypes broken,solid and none are used and infered from the lane restrictions on the lane. The lane change restrictions that are already imported into the network model and which could be used to infer "solid broken" and "broken solid" (and which are already painted in sumo gui) are not used in the xodr export. Pull requests are very welcome.
