### ISSUE TITLE
Error occurs when loading route xml-file due to xml-validation setting

### ISSUE THREAD

**Issue by yunpangfloetteroed** [eclipse/sumo#12138]
Add your issue description here.
The xml-validation setting needs to be set to never in cfg-file. Otherwise, error occurs when loading route xml-file.

*If possible, upload an example that shows your problem.*
Examples are unter sumo\docs\exmaples
**SUMO-version:**
sumo 1.15.0
**operating system:**
Windows

**Comment by namdre** [comment]
@behrisch also, a dev_regression, right?

**Comment by behrisch** [comment]
yes, also it probably still needs a reproducible test
