### ISSUE TITLE
sumolib phase != libsumo phase

### ISSUE THREAD

**Issue by mschrader15** [eclipse/sumo#12131]
We encounter an error when attempting to set the phases attribute of a libsumo traffic light object with sumolib phases:

```Python
logic = self.sumo.trafficlight.getAllProgramLogics(self.id)[0]
logic.phases = self.phases # previously created using sumolib net reader
```

Error:
```
In method 'TraCILogic_phases_set', argument 2 of type 'std::vector< std::shared_ptr< libsumo::TraCIPhase >,std::allocator< std::shared_ptr< libsumo::TraCIPhase > > > const &'
```

This occured when trying to port RESCO to libsumo: 
https://github.com/UnivOfAlabama-BittleResearchGroup/RESCO/blob/101b0b725c21809097b2b1414da6fbec3c0b9e0a/resco_benchmark/traffic_signal.py#L250-L261 

The work around is simple enough, but maybe this could be done internally in libsumo's Python API as well as more clear error reporting?

**Comment by behrisch** [comment]
Please note that the modifications I did will only apply to assignment (`logic.phases = new_phases`). Constructing a new TraCILogic with sumolib phases is still not possible.
