### ISSUE TITLE
marouter is not working from eclipse-sumo wheel

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#12142]
It exits with error code 245 (probably a segfault). jtrrouter and dfrouter are affected as well. sumo, netconvert, duarouter run just fine. Last working version was 1.15.0.post434

**Comment by namdre** [comment]
Only within the github action infrastructure or also when you install it locally?

**Comment by behrisch** [comment]
Locally as well so it is probably something different than the DB error

**Comment by behrisch** [comment]
It is fixed now by going back to a different version of the docker image which is used to build the wheels. @namdre This might be an option for the DB too.
