### ISSUE TITLE
Linux freezes during build (make)

### ISSUE THREAD

**Issue by tinova-1** [eclipse/sumo#12169]
Hi there! I am trying to build from source code for Linux, and I am exactly following this: https://sumo.dlr.de/docs/Installing/Linux_Build.html and have installed all tools that are described there. However, during `make`, at 60% to 80%, Linux freezes and I have to restart the system. Anyone has an idea what is the issue and how to solve it?

I am using Linux Mint
Linux version 5.15.0-41-generic (buildd@lcy02-amd64-065) (gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #44-Ubuntu SMP Wed Jun 22 14:20:53 UTC 2022
Architektur:                       x86_64
  CPU Operationsmodus:             32-bit, 64-bit
  Adressgrößen:                    36 bits physical, 48 bits virtual
  Byte-Reihenfolge:                Little Endian
CPU(s):                            8
  Liste der Online-CPU(s):         0-7
Anbieterkennung:                   GenuineIntel
  Modellname:                      Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz

**Comment by tinova-1** [comment]
Nevermind, looks like 16GB RAM + 2GB of Swap is too little...

**Comment by namdre** [comment]
I cannot tell what your problem is but I don't think this is only about resources. I'm personally building SUMO with 16GB RAM on Ubuntu just fine (and have done so with fewer resources in the past).

**Comment by behrisch** [comment]
Try using `make -j8` or something similar. Usually the reason for such behavior is that make is spawning too many processes.
