### ISSUE TITLE
Is there a way to clear all vehicles after a certain time step during the simulation?

### ISSUE THREAD

**Issue by JamesPsh** [eclipse/sumo#12165]
I initially ran a simulation using the traffic demand xml file for about 2 hours.

And I want to clear all vehicles after a certain time whenever necessary.
For example, during a 2-hour simulation, I would like to stop generating vehicles after the first hour.
How can I do that? Is there a traci method that does this?

Thank you.

**Comment by namdre** [comment]
the only way is to remove these vehicles individually with `traci.vehicle.remove`  (you can do this for all vehicles that were loaded from an xml file even if they haven't yet departed). Note that files loaded with option **--route-files** are loaded incrementally. You can load a route file with option **--additional-files** all at once and could then be sure to have access to all vehicles for removal purpose.
