### ISSUE TITLE
LineReader keeps wrong state for long last line (>1024 bytes)

### ISSUE THREAD

**Issue by m-kro** [eclipse/sumo#12161]
When the DLR Navteq input file misses a _newline_ at the last line, the converter still works but repeats the polygon in the output several times. Not sure how the DLR Navteq format is defined, but I expect the converter to work correctly (1 input polygon = 1 output polygon) or issue an error and  stop...

**Comment by m-kro** [comment]
General problem with reading file (LineReader)

**Comment by m-kro** [comment]
See  S:\Bugreports\12161_LineReader

**Comment by m-kro** [comment]
Improper use of LineReader::hasMore :
https://github.com/eclipse/sumo/blob/49ab8f9a585dacb19df15f9a1bddfda87a2f3e1c/src/polyconvert/PCLoaderDlrNavteq.cpp#L104
It does not necessarily indicate there are more lines but there is more data (which is not the same).

**Comment by m-kro** [comment]
Finally, `myRread` was not updated with the actual read number of bytes but only in steps of 1024. This probably did not show up earlier as most data schemes encourage having more lines but a small number of characters per line (<=1024).

**Comment by namdre** [comment]
Could we get a test failing/succeeding in our daily tests?
