### ISSUE TITLE
HELLO， can I ask you that what's the meaning of the word called depart delay? And could you also tell me the meaning of all of the words in the picture? Thank you !

### ISSUE THREAD

**Issue by Cherrycurryy** [eclipse/sumo#12166]
HELLO， can I ask you that what's the meaning of the word called depart delay? And could you also tell me the meaning of all of the words in the picture? Thank you !

![image](https://user-images.githubusercontent.com/118825893/204094077-83e02cb9-1a37-4aca-8a49-d656e3a43b18.png)

**Comment by namdre** [comment]
several things are explained here:
https://sumo.dlr.de/docs/Simulation/Output/Summary.html
https://sumo.dlr.de/docs/Simulation/Output/StatisticOutput.html#vehicletripstatistics

*insertion backlogged* indicates vehicles that are currently waiting for insertion.
