### ISSUE TITLE
Negative electricity consumption

### ISSUE THREAD

**Issue by alexrsanchez** [eclipse/sumo#12172]
Hello there,

I was investigating my lane-based emissions file for using them as inputs on plot_net_dump.py script, when I have noticed some negative values on electricity consumption. Here is a brief example:

        <edge id=":22575926_0">
            <lane id=":22575926_0_0" sampledSeconds="50.66" CO_abs="9.482334" CO2_abs="4844.331285" HC_abs="3.764833" PMx_abs="0.511404" NOx_abs="20.780597" fuel_abs="1536.957661" electricity_abs="-2.283441e-01"
            CO_normed="41.227538" CO2_normed="21062.309933" HC_normed="16.368839" PMx_normed="2.223495" NOx_normed="90.350421" fuel_normed="6682.424612" electricity_normed="-9.928006e-01"
            traveltime="0.02" CO_perVeh="0.003271" CO2_perVeh="1.671035" HC_perVeh="0.001299" PMx_perVeh="0.000176" NOx_perVeh="0.007168" fuel_perVeh="0.530168" electricity_perVeh="-7.876652e-05"/>

This also raises an error when trying to plot emissions in SUMO GUI:
**Error: value '-2.793943e-01' must be greater than or equal to minInclusive facet value '0'**
 In file '.../seed31lanebased_emissions.xml'
 At line/column 62180/203.

At the moment I'm using SUMO 1.15.0 version with PHEMlight5 emission data.

**operating system:**
[negative_electriciry.zip](https://github.com/eclipse/sumo/files/10101860/negative_electriciry.zip)

**Comment by m-kro** [comment]
The error comes from the XML validation. As a workaround, you can switch that off by calling sumo-gui with `--xml-validation never`.

**Comment by behrisch** [comment]
since negative values can actually happen when it comes to electricity, this is a bug in the schema

**Comment by namdre** [comment]
The negative values come from recuperation.

**Comment by namdre** [comment]
also: coloring by laneData doesn't work yet: #12176
