### ISSUE TITLE
the color of the stopline in gui

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#12186]
Why are my intersection stop lines blue and tan and what do they mean?
![image](https://user-images.githubusercontent.com/54823725/204686660-a3e9dc04-ff7f-4e62-ad88-c08fb2fc97dc.png)

**SUMO-version: 1.14**

**operating system: Windows**

**Comment by namdre** [comment]
The traffic light is switched off.
https://sumo.dlr.de/docs/sumo-gui.html#right_of_way

**Comment by a-123-du** [comment]
> The traffic light is switched off. https://sumo.dlr.de/docs/sumo-gui.html#right_of_way
If I want the intersection to be a no-signal intersection，I changed the fringe from inner to default, and I see the gui looks like this. Is this a no-signal intersection now?
![image](https://user-images.githubusercontent.com/54823725/204731982-24902d79-4233-4c11-993b-84548d5c3760.png)
![image](https://user-images.githubusercontent.com/54823725/204732044-b4684ab6-aae6-4d71-ba13-b0f399d665fc.png)

**Comment by namdre** [comment]
yes. Priority is the standard "no-signal" intersection.
