### ISSUE TITLE
Questions about Emulate the INTERACTION dataset with SUMO

### ISSUE THREAD

**Issue by ShenZC25** [eclipse/sumo#12187]
Add your issue description here.
Hello, I'm using SUMO to simulate the scene in the interaction data set. Now I have the map (.osm file) and vehicle track (.csv file) in the data set. I don't know how to restore them in SUMO. Could you please explain the general process for me?

I also encountered problems in the process of importing maps. First of all, I tried to convert one of them, osm file, into a net.xml file, and input the following command in win10 system: "net convert-OSM-files DR _ CHN _ merging _ zs.osm-O DR _ CHN _ merging _ zs.net.xml", but the error was as follows:

Warning: Cannot read local schema 'D:\sumo-1.15.0\bin/data/xsd/additional_file.xsd'.
Warning: Cannot read local schema 'D:\sumo-1.15.0\bin/data/xsd/routes_file.xsd'.
Warning: Cannot read local schema 'D:\sumo-1.15.0\bin/data/xsd/net_file.xsd'.
Error: Could not open types-file 'D:\sumo-1.15.0\bin/data/typemap/osmNetconvert.typ.xml'.
Error: No nodes loaded.
Quitting (on error).

Excuse me, how to solve it?

In addition, in the csv file containing car tracks, I have the following data formats (excerpts). How can I automatically generate them and input them into relevant configuration files?

*If possible, upload an example that shows your problem.*

（There is no “data ” folder under “bin” folder.）
![image](https://user-images.githubusercontent.com/89288084/204703423-9cb335f3-e8a9-4143-bfbb-71f1c437af04.png)

**SUMO-version:**
1.15.0
**operating system:**
win10

**Comment by namdre** [comment]
it appears that you have set the value of environment variable SUMO_HOME to point to `D:\sumo-1.15.0\bin/` whereas it should be `D:\sumo-1.15.0`

**Comment by namdre** [comment]
Also, can you given an example of the *the csv file containing car track*?

**Comment by ShenZC25** [comment]
> Also, can you given an example of the _the csv file containing car tracks_?



Thank you for your answer. csv file mainly includes the following information:
Track id, frame id, ... length, width

![example](https://user-images.githubusercontent.com/89288084/204726503-d0d91781-d8c7-4133-a809-c95e16cb201a.png)

**Comment by namdre** [comment]
The supported input formats for importing traces are described at https://sumo.dlr.de/docs/Tools/Routes.html#tracemapperpy
With a bit of re-formating you could turn you file into this supported format:

```
<fcd>
  <vehicle id="TRACK_ID" x="X_VALUE" y="YVALUE"/>
   ...
</fcd>
```
