### ISSUE TITLE
Sometimes the internal lane comes out as a straight line.

### ISSUE THREAD

**Issue by JamesPsh** [eclipse/sumo#12188]
[sumo.net.zip](https://github.com/eclipse/sumo/files/10119641/sumo.net.zip)
Sometimes the internal lane comes out as a straight line.

![image](https://user-images.githubusercontent.com/101240964/204712245-2026a463-c327-4776-ba29-8f45fbfff3b6.png)

**Comment by namdre** [comment]
Looks like *fallback* behavior in case the regular geometry could not be computed. Can you attach the network file (or the input files from which it was built)?

**Comment by namdre** [comment]
there is a hardcoded assumption about the maximum intersection size being below 100m and for anything bigger there is a fallback to a simple shape. In your case I'd actually model this thing as two intersections:
![net2](https://user-images.githubusercontent.com/6240630/205314635-e47dc98a-d5a8-4465-8514-80a19c5d8ece.png)
