### ISSUE TITLE
SUMO_HOME Variable

### ISSUE THREAD

**Issue by tanyaprins** [eclipse/sumo#12185]
Good day. I have a Mac mini. Angelo helped my friend today as well. I am unable to install the variable. What to do? The Terminal says I cannot do this command
open ~/.zshrc

Thank you, Tanya

**Comment by angelobanse** [comment]
First make sure your Mac is using the Z shell (zsh) by executing `echo $0` in a terminal window. If the response you get is "-zsh" you are indeed using Z shell.

It looks like you don't have a .zshrc file yet. To create it just execute `touch ~/.zshrc` and then open it in TextEdit (using `open ~/.zshrc`).

Then just copy the following line, to set the SUMO_HOME environment variable (only if you installed SUMO using Homebrew!):
`export SUMO_HOME="/opt/homebrew/opt/sumo/share/sumo"`
You can check if you have SUMO installed via Homebrew (and in the caveats section even see the instructions - and exact PATH - to set the SUMO_HOME variable) by executing `brew info sumo` in a terminal.

After saving and closing that TextEdit window, you just need to run `source ~/.zshrc` and that should be all.

**Comment by tanyaprins** [comment]
Dear Angelo

I think everything is very confused now.

1. I installed Homebrew and Installed SUMO
I was able to open the window of the xQuartz App using the following commands:
 export SUMO_HOME="$PWD/sumo"
 cd sumo/bin
 ./sumo
(Open Xquartz)
 ./sumo-gui 

I then downloaded from the SUMO Website the Applications with a launcher that required me to set the SUMO_HOME variable in the environment
I did that but I think I used the wrong path and the variable is now what it is . 

I have followed yours steps and this is where I am at the moment in Text edit:
￼
I used that path to set the variable because it was in the info of the three relevant apps.

Please can you assist?

Kind Regards

Tanya Prins CA(SA) MBA
Director: HDP Capital Pty Ltd
Israel: +972 53 243 6809
T: +27827814912
E: ***@***.*** ***@***.***>
A: 18 Maraispark, 11 Marais Rd, Stellenbosch, 7600

**Comment by angelobanse** [comment]
I don't completely understand the issue. When you run `brew list` in a Terminal, do you see **sumo** in the list you get? If so, run `brew info sumo` and take a look at the path stated under *"Don't forget to set your SUMO_HOME environment variable:"* at the end.

**Comment by tanyaprins** [comment]
I think I set the variable but it is the wrong path .. what to do?Tanya Prins CA(SA) MBA HDP Capital Pty Ltd+27 (0) 82 781 ***@***.*** On 01 Dec 2022, at 10:36, Angelo Banse ***@***.***> wrote:﻿
I don't completely understand the issue. When you run brew list in a Terminal, do you see sumo in the list you get? If so, run brew info sumo and take a look at the path stated under "Don't forget to set your SUMO_HOME environment variable:" at the end.

**Comment by tanyaprins** [comment]
O good grief I don’t see SUMO

But I installed everything .. must I do it again now?

**Comment by tanyaprins** [comment]
HI there

￼

It is not in the list but it won’t allow me to export it. Herewith a screenshot of the terminal.

Regards, Tanya

**Comment by tanyaprins** [comment]
Dear Angelo

Everything seems to be in order now. I have installed the application launchers and the environment variable is set with the path you provided. How do I open osmWebWizard in the Application now. I can see it in settings but don’t know how to actually open it.

Please assist.

Kind Regards
Tanya Prins

**Comment by tanyaprins** [comment]
Good day

I am just following up on this. What to do next?

Much appreciated,
Tanya Prins
