### ISSUE TITLE
the following model and traci control

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#12197]
What is the relationship between SUMO's own following model and traci's control of the vehicle? Will adding traci control destroy the following model and cause a crash?
I have conducted  an experiment,  I did not turn off the default following model, only two cars were set in my traffic flow, and I performed traci control on the rear car,I set the acceleration value of 6 when I let the rear car enter the road network,I set the initial speed and maximum acceleration of the rear car higher than that of the front car, in order to test whether the rear car will rear-end the front car. But his acceleration output is not 6 and they will not crash.So I wondered about the relationship between the default following model and my own control of the car. Would the following model change the speed of the car, so that the car did not follow the speed I set? Thanks in advance.
![image](https://user-images.githubusercontent.com/54823725/204992692-7b7ff895-5896-4e19-90c7-52dc21cc349f.png)
![image](https://user-images.githubusercontent.com/54823725/204992827-e6d8b7a8-dad0-4238-9da1-50195577b874.png)
![a553372b8182dd415577129274f9850](https://user-images.githubusercontent.com/54823725/204992856-7346459b-41fe-4e1f-aa23-cfd54ae7ac8f.png)

**SUMO-version:1.14**

**operating system:Windows**

**Comment by m-kro** [comment]
The vehicle does not necessarily use the full acceleration all the time. Overriding the actual speed is done with traci.vehicle.setSpeed (to be called in every time step you'll want this to take effect).  You'll have to disable some speed checks using [traci.vehicle.setSpeedMode](https://sumo.dlr.de/pydoc/traci._vehicle.html#VehicleDomain-setSpeedMode) (see also the [speed mode definition](https://sumo.dlr.de/docs/TraCI/Change_Vehicle_State.html#speed_mode_0xb3)).

**Comment by a-123-du** [comment]
> 车辆不一定一直使用全加速。覆盖实际速度是通过traci.vehicle.setSpeed完成的（在每个时间步中调用，您希望它生效）。您必须使用[traci.vehicle.setSpeedMode](https://sumo.dlr.de/pydoc/traci._vehicle.html#VehicleDomain-setSpeedMode)禁用某些速度检查（另请参阅[速度模式定义](https://sumo.dlr.de/docs/TraCI/Change_Vehicle_State.html#speed_mode_0xb3)）。
How do you keep the car accelerating at 6？ and  I understand that the setAcceleration function is going to accelerate to 6 in one second,am I right?  
![image](https://user-images.githubusercontent.com/54823725/205001810-62aee4f2-894e-4ca7-8f2a-5afd6845c700.png)

**Comment by a-123-du** [comment]
> 车辆不一定一直使用全加速。覆盖实际速度是通过traci.vehicle.setSpeed完成的（在每个时间步中调用，您希望它生效）。您必须使用[traci.vehicle.setSpeedMode](https://sumo.dlr.de/pydoc/traci._vehicle.html#VehicleDomain-setSpeedMode)禁用某些速度检查（另请参阅[速度模式定义](https://sumo.dlr.de/docs/TraCI/Change_Vehicle_State.html#speed_mode_0xb3)）。
How do you keep the car accelerating at 6？ and  I understand that the setAcceleration function is going to accelerate to 6 in one second,am I right?  
![image](https://user-images.githubusercontent.com/54823725/205001810-62aee4f2-894e-4ca7-8f2a-5afd6845c700.png)
