### ISSUE TITLE
How to automate the modification of junction shapes

### ISSUE THREAD

**Issue by meco2020** [eclipse/sumo#12194]
Hello！I have a question here about the SUMO‘s net. 

We know that SUMO has the netconvert plugin to convert some electronic maps (e.g. SHP, OSM, XODR) to NET files. At the same time, SUMO provides netedit, a tool to fine-tune the shape of intersections and roads.

However， manually adjusting the shape of the intersection and roads  means too much work，even if a high-precision intersection such as xodr is introduced, there are various errors when introduced XODR into SUMO. 

When I want to create nod.xml, edg.xml to make a sumo net, I find that node does not have the shape attribute.  

After using netconvert to generate net's junctions, modifying the property values of the junction by reading the XML file is an automated modification method( But this requires a huge amount of data pre-processing) and do you have other ways to automate the modification of intersections and edges?

Thanks in advance！

**Comment by meco2020** [comment]
Thanks! 
I found the attribute of shape in the description of the nod.xml，I hope to build a small city level road network automatically, so as to avoid a lot of manual work

**Comment by namdre** [comment]
@meco2020  what data source are you using for the node shapes?
