### ISSUE TITLE
drawing quadrilaterals on intersections

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#12190]
Does SUMO support drawing quadrilaterals on intersections?
![image](https://user-images.githubusercontent.com/54823725/204704977-9f4a06aa-8020-43e1-971a-80aa80ed91aa.png)
I want to draw rectangles in the crossroad. And I want the quadrilateral to show up when the gui runs. Thank you.
**SUMO-version:1.14**
**operating system:Windows**

**Comment by namdre** [comment]
for decoration you can draw polygons in netedit (using shape mode), depending on the 'layer' attribute this will be placed above or below the intersection drawing. (load the polygons into sumo-gui from an *additional-file*. See 

https://sumo.dlr.de/docs/Simulation/Shapes.html
https://sumo.dlr.de/docs/Netedit/elementsShape.html

**Comment by a-123-du** [comment]
> for decoration you can draw polygons in netedit (using shape mode), depending on the 'layer' attribute this will be placed above or below the intersection drawing. (load the polygons into sumo-gui from an _additional-file_. See
> 
> https://sumo.dlr.de/docs/Simulation/Shapes.html https://sumo.dlr.de/docs/Netedit/elementsShape.html
But I don't want to draw the graph by hand, I want to place the graph by my coordinate points.

**Comment by namdre** [comment]
Then use polyconvert to import the shapes in any of the supported formats or write some code to generate an xml file with `<poly>` definitions.
