### ISSUE TITLE
How to calculate the time required to reach a destination

### ISSUE THREAD

**Issue by e1958229** [eclipse/sumo#12196]
Is there a way to calculate the time taken by a vehicle from start to arrival at its destination? I looked at https://sumo.dlr.de/docs/TraCI/Vehicle_Value_Retrieval.html in the meantime but couldn't find it. If you know how to calculate it, please let me know. Thanks in advance.　(Im using translator)

**Comment by m-kro** [comment]
You can use the [TripInfo ](https://sumo.dlr.de/docs/Simulation/Output/TripInfo.html) output:

- run SUMO with option `--tripinfo-output FILE`
- you'll get one tripinfo XML element per vehicle in FILE
- find the travel time in the `duration` attribute of every tripinfo element

**Comment by e1958229** [comment]
Thank you so much! I will try it.

**Comment by e1958229** [comment]
Sorry. This is my mistake, but I need to get that value for each step during the simulation run for reinforcement learning. is it possible to do that by traci etc?

**Comment by namdre** [comment]
Do you intend to retrieve this only for vehicles that already arrived or do you wish to take an estimate of the remaining travel time for vehicles that are still underway?

**Comment by e1958229** [comment]
I would like to know the time since the start of the remaining vehicles in the simulation.

**Comment by namdre** [comment]
You have several options:
- in the release version (1.15.1 and earlier):  call `traci.simulation.getDepartedIDList` in every step and store the vehicle ids and the current time in a map for later retrieval. Based on this departure time you can always compute the current driving duration
- in the latest development version, call `traci.vehicle.getDeparture` to retrieve the departure time

**Comment by e1958229** [comment]
Thank you so much ! I will try it!
