### ISSUE TITLE
avg.loss.trip.loss

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#12207]
Why is there no avg.trip.time.loss on the parameter of my network?
![image](https://user-images.githubusercontent.com/54823725/205206658-139dd34c-df9f-420e-a6ec-1571a5643bf8.png)
But I've seen sumogui in other people's papers have this parameter.
![image](https://user-images.githubusercontent.com/54823725/205206825-76cf76d1-19cb-4e48-b547-023bc0de93b3.png)

**SUMO-version:sumo1.14.1**

**operating system:Windows**

**Comment by namdre** [comment]
These values are only recorded if the simulation is launched with the options
--tripinfo-output or --statistic-output.

**Comment by a-123-du** [comment]
> These values are only recorded if the simulation is launched with the options --tripinfo-output or --statistic-output.
Yes, I added tripinfo to sumocfg, but the parameter of my gui still doesn't have awg.trip.time.loss
![image](https://user-images.githubusercontent.com/54823725/205468806-5e249c2e-1040-4f08-b095-d7af6b94a44c.png)
![image](https://user-images.githubusercontent.com/54823725/205468818-1c6eca85-0d39-413f-a29d-41b99330b371.png)

**Comment by namdre** [comment]
in the 1.15.0 release version and earlier, the statistics are only included if both of the following condition are met:
- option **--duration-log.statistics** is set
- option **-no-duration-log** is not set

In the latest development version the conditions are:
- either option **--tripinfo-output** or option **--duration-log.statistics** is set

**Comment by a-123-du** [comment]
> * option **--duration-log.statistics** is set

How to set option --duration-log.statistics?
