### ISSUE TITLE
flows distribution setting of random trips

### ISSUE THREAD

**Issue by thinker310** [eclipse/sumo#12206]
Hello, I wonder how the difference between Traffic volume/Arrival rate and insertion distribution as described in the screen shot：
![uTools_1669948148484](https://user-images.githubusercontent.com/62609436/205201686-7f4c3ff6-7230-4f6b-9abc-028da6553ea8.png)
case1: python randomTrips.py -b 0 -e 3600 -p (3600 / 2000) --binomial 150
case2: python randomTrips.py -b 0 -e 3600 --insertion-rate 2000 --binomial 150
case3: python randomTrips.py --random-depart -b 0 -e 3600 --insertion-rate 2000 --binomial 150
case4: python randomTrips.py --random-depart -b 0 -e 3600 --insertion-rate 2000
1.Are the effects in simulation for case1 and case2 same?
2.Is the description of command in case3 right (--random-depart&--binomial 150 both exist)? what is the difference between case2 and case 3?
3.Can I regard the case2 as the binomial distribution and case4 as the exponential distribution for flows in the simulation?
4. I want to make the distribution of the vehicle flow exponential for the whole network on each edge, how can I achieve it?
Could you help me answer these questions please? Thank you a lot!

**Comment by namdre** [comment]
1. yes
2. if options --binomial is set, then option --random-depart takes no effec
3. yes. Though it's the number of departures per second that is binomial whereas the exponential distribution describes the distribution of time gaps between insertions.
4. use option --random-depart (case 4)
