### ISSUE TITLE
I can open SUMO and Netedit but not osmWebWizard

### ISSUE THREAD

**Issue by tanyaprins** [eclipse/sumo#12208]
Add your issue description here.

*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**

**Comment by tanyaprins** [comment]
Hi there. I have Mac mini. I have come as far as the Applications added with the Launcher. I can open SUMO-gui and Netedit but not osmWebWizard. What to do? 
Installing the cask sumo-gui seems to only speak to sumo and netedit. Herewith my last terminal window.

[Terminal.pdf](https://github.com/eclipse/sumo/files/10138562/Terminal.pdf)

Kind Regards, Tanya

**Comment by m-kro** [comment]
I am not a Mac user, but can tell that your reference of the environment variable SUMO_HOME and the path style look like you would do on Windows. Maybe try something like `python $SUMO_HOME/tools/osmWebWizard.py`?

**Comment by tanyaprins** [comment]
Hi there

Thank you so much for the reply!

When I do that it says the following:
***@***.*** ~ % python $SUMO_HOME/tools/osmWebWizard.py
zsh: command not found: python

**Comment by angelobanse** [comment]
Try downloading the launchers manually (from [here](https://sumo.dlr.de/docs/Downloads.php#application_launchers)) and dragging the icons to the Applications folder. Open the osmWebWizard by clicking on the launcher.

**Comment by angelobanse** [comment]
It looks like you don't have Python installed (or at least not in the path). Try installing Python: https://www.python.org/downloads/macos/ first.

**Comment by tanyaprins** [comment]
Hi there.

I have done that. The sumo-gui opens as well as the netedit. It’s only the ism webwizard that doesn’t. I have noticed it gives the tiny system settings icon on top for a brief second.

**Comment by angelobanse** [comment]
> It looks like you don't have Python installed (or at least not in the path). Try installing Python: https://www.python.org/downloads/macos/ first.

Try that ⬆️

**Comment by tanyaprins** [comment]
Thanks I did that
I hade version 3.10 and now 3.11 but it still does the same

**Comment by tanyaprins** [comment]
Dear Angelo

Thank you so much. It is at least opening in my Safari Browser. I still can’t open the APP though. 

Do I always just execute this in the terminal to at least work in the browser?

**Comment by angelobanse** [comment]
osmWebWizard is supposed to open in the browser.

Take a look at the [tutorial](https://sumo.dlr.de/docs/Tutorials/OSMWebWizard.html), to see what it should look like.

**Comment by tanyaprins** [comment]
Ok Great! Thank you so so so very much!

Have a lovely day further!

I cannot tell you how thankful I am! Just a little feedback!

Kind Regards
Tanya

Tanya Prins CA(SA) MBA
Director: HDP Capital Pty Ltd
Israel: +972 53 243 6809
T: +27827814912
E: ***@***.*** ***@***.***>
A: 18 Maraispark, 11 Marais Rd, Stellenbosch, 7600
