### ISSUE TITLE
how to open more sumo server

### ISSUE THREAD

**Issue by 385628424** [eclipse/sumo#12218]
Add your issue description here.

I have some questions about Sumo and would like to consult. I am currently training in reinforcement learning. In a single environment, the sampling rate can be about 10 frames per second. But now a larger amount of data is needed, so I opened multiple environments (more than 100) through Traci, but only one Sumo server can be opened on a computer, although the number of routing-threads can be set, but the overall The sampling rate is still slow, and the CPU and GPU resources are light.
Is there any way for me to open multiple sumo servers on one computer, and one sumo server corresponds to one traci service, so as to fully utilize the computing resources of the computer to increase the sampling rate.

*If possible, upload an example that shows your problem.*

**SUMO-version:**
1.15.0
**operating system:**
ubuntu20.04

**Comment by namdre** [comment]
https://sumo.dlr.de/docs/TraCI/Interfacing_TraCI_from_Python.html#controlling_parallel_simulations_from_the_same_traci_script

**Comment by 385628424** [comment]
This method is not the way I want to deal with it. Essentially, this method still uses one Server to control multiple Clients. The help I want is how to open multiple Sumo Servers on one computer, or how to connect traci to a sumo server that is not a local address

**Comment by 385628424** [comment]
> https://sumo.dlr.de/docs/TraCI/Interfacing_TraCI_from_Python.html#controlling_parallel_simulations_from_the_same_traci_script

This method is not the way I want to deal with it. Essentially, this method still uses one Server to control multiple Clients. The help I want is how to open multiple Sumo Servers on one computer, or how to connect traci to a sumo server that is not a local address

@namdre

**Comment by namdre** [comment]
the described method actually uses a single client that starts multiple instances of sumo (servers). 
- your own code acts as a client
- sumo acts as a server

The method `traci.connect` allows setting a remote address but you have to make sure that sumo was already started on that address. (https://sumo.dlr.de/pydoc/traci.main.html)

**Comment by JamesPsh** [comment]
@385628424 

You can run multiple simulations using the "ray" library.
The link below is an example of my multi-simulation using ray.

https://github.com/JamesPsh/ReinforcementLearning-TrafficLights
