### ISSUE TITLE
Question on GLOSA code

### ISSUE THREAD

**Issue by thinker310** [eclipse/sumo#12211]
For the calculation of GLOSA, I am confused about variable the _root_argument_, what does it mean? Then, I found that the traffic light state are not identified, but target speed can be calculated, how does GLOSA do it? Because normally, we need obtain the traffic light state, then judge the cars accelerate or decelerate, otherwise the specific target value cannot be calculated.Hope someone can help me please. Thank you in advance! https://github.com/eclipse/sumo/blob/b3eb37bc71378b626e183c0b2aa245b114c7a1c0/src/microsim/devices/MSDevice_GLOSA.cpp#L294
For
![uTools_1669972403154](https://user-images.githubusercontent.com/62609436/205257954-9fab8ad5-9dd9-4d52-a2d9-c0ac079348f0.png)

**Comment by namdre** [comment]
the traffic light state is incorporated via `timeToSwitch`. The root_argument is simply a temporary name for the term within the square root.
