### ISSUE TITLE
traffic light mode: right click on connection should not have disambiguation menu

### ISSUE THREAD

**Issue by bcoueraud87** [eclipse/sumo#12237]
right now it allows selecting between the connection and the junction (thereby wasting a click) but in this mode only the connection is wanted.

could be considered a regression

**Comment by palvarezlopez** [comment]
@bcoueraud87 I cannot reproduce it :(

**Comment by bcoueraud87** [comment]
@palvarezlopez Perhaps you should ask Jakob, he created this ticket on my computer with my account, he unterstands the problem better :).

**Comment by palvarezlopez** [comment]
Not anymore. Probably Benjamin has an old version

**Comment by bcoueraud87** [comment]
@palvarezlopez Yes we used the jupedsim branch yesterday.
