### ISSUE TITLE
Cannot reconstruct fw_speed from 3D positions - Question

### ISSUE THREAD

**Issue by sitidom** [eclipse/sumo#12235]
This problem has been quite puzzling and I cannot seem to find a reference in the documentation which explains how the values are computed.

I query a vehicle between 3 sequential positions, and obtain the fwd_speed value (in UTM coordinates)
In all cases, lateral_speed is 0.0000
I then also compute the velocity by taking differences in the 3D position of the same vehicle (also in UTM), and dividing by dt, the timestep.

Somehow the velocity magnitude calculated by using the 3D positions, is less than the fw_speed retrieved from the vehicle properties.

Can you please clarify how the forward speed of the vehicle is computed, and how it related to the 3D positions reported by the vehicles?

If the computed speed was less that the one reported in the vehicle properties, then it would have been some kind of rotation (projection) however. However in this case, it is not clear to me how the forward speed can be greater than the magnitude of the velocity.

Relevant values:

dt = 0.0500 #seconds

Position 1:
pos(Utm)=( x=478.652471; y=2171.836697; z=582.929280;)
angle=326.628239, slope=8.759307
fw speed=13.996934, lat speed=0.000000
magnitude ((pos 2 - pos 1)/dt) = 13.724708530

Position 2:
pos(Utm)=( x=478.204968; y=2172.352118; z=583.000000;)
angle=325.579315, slope=8.376619
fw speed=13.999229, lat speed=0.000000
magnitude ((pos 3 - pos 2)/dt) = 13.97389154

Position 3
 pos(Utm)=( x=477.626506; y=2172.743980; z=583.000000;)
angle=322.436801, slope=7.209585
 fw speed=13.973823, lat speed=0.000000

**SUMO-version: 1.15**

**operating system: Windows 10**

**Comment by behrisch** [comment]
Is your edge somehow curvy or has a custom length defined?

**Comment by namdre** [comment]
Please attach the network file

**Comment by sitidom** [comment]
Thank you for following up on this.

The network files were imported from open street maps and we added height data separately from a different source.

Attaching the network file below. Let me know if you need additional files like the poly etc.
[TestArea.net.xml.txt](https://github.com/eclipse/sumo/files/10169001/TestArea.net.xml.txt)

**Comment by m-kro** [comment]
![image](https://user-images.githubusercontent.com/33294728/206015228-49b1a795-5ef5-4492-a3f6-2a919b8ca0a8.png)
Apparently no custom lengths set, but the example data comes from a sharp curve.

**Comment by behrisch** [comment]
Because it is a curve, the vehicle needs to driver a longer distance than just the bee line. So the speed calculated from the bee line is smaller
