### ISSUE TITLE
netedit: Inability to create crossings for one way (two sidewalks) roads

### ISSUE THREAD

**Issue by danigian** [eclipse/sumo#12232]
As you can see from the image below, it's not possible to specify a simple pedestrian crossing in junction J2 as, from my understanding, edges -E0 and -E1 only have a pedestrian lane (no driving lanes)
![image](https://user-images.githubusercontent.com/1955514/205859986-1ac6f5ee-a47b-4984-ba00-8b5ed82828d2.png)

Ideally though, in real life, this might be a perfectly fine scenario, how can this be solved?

I am attaching the reference network in the following zip file:
[not_working_crossing.net.xml.zip](https://github.com/eclipse/sumo/files/10164225/not_working_crossing.net.xml.zip)

**Comment by namdre** [comment]
The issue here is that the road to be crossed permits pedestrians to walk on the driving lane (thereby indicating a shared space simulation) which does not admit  adding crossing.
The simple fix is to change the driving lane permissions so that it disallows pedestrians.

**Comment by danigian** [comment]
I am sorry @namdre but the road is disallowing pedestrians:
![image](https://user-images.githubusercontent.com/1955514/205891878-7b77cb67-9ee4-44a9-9a4f-36eb14e62991.png)

unless I misunderstood what you mean.

**Comment by namdre** [comment]
My bad, the error looked to much like a typical error. In your case, you only need to add the edge with the driving lane when defining the crossing. (only `E1` and not `E1 -E1`).
