### ISSUE TITLE
Can i change sumogui settings?

### ISSUE THREAD

**Issue by e1958229** [eclipse/sumo#12230]
I am using reinforcement learning and am opening and closing sumo-gui to learn. If I change the application settings in sumo-gui and then close and reopen the gui, the settings are not transferred, is it possible to transfer them? Is it possible to transfer the settings? Or is it possible to repeat the simulation without closing the gui?

Settings to be transferred
![image](https://user-images.githubusercontent.com/113490031/205813527-7fea67a1-2c01-4c2b-9af1-d0cdfdb35ae3.png)
Codes for closing and opening parts
![image](https://user-images.githubusercontent.com/113490031/205830256-88f0ac6f-0b3f-4e9c-942b-c84b7092e759.png)

**Comment by namdre** [comment]
These settings cannot be stored accross sessions but they can be set using the options 
- **--quit-on-end**
- **--start**
- **--demo**

You can either add them to a .sumocfg  (`</start value="true"/>`)  or  pass them in `traci.start(['sumo', '--start', ...])`

**Comment by e1958229** [comment]
Thank you so much ! I will try it.
