### ISSUE TITLE
Improve expand button in TLS Frame

### ISSUE THREAD

**Issue by bcoueraud87** [eclipse/sumo#12236]
by default the traffic light frame is so narrow that the buttons are invisible. Without knowing that the frame can be expanded and without knowing that the buttons are there, it's very hard to discover the functionality of these buttons (i.e. for adding phases)

**Comment by namdre** [comment]
also, the frame-expand/collapse buttons should get a mouse-over tooltip

**Comment by namdre** [comment]
placing the buttons on the left had other disadvantages.  I have a new suggestion:

We could change the color of the "Expand" button if the frame smaller than the required (expanded) width. This would make it abit more disoverable.
