### ISSUE TITLE
ignore grid when editing junction / walking area shape

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#12243]
Usually it does not help to have the shape points snap to the grid. We could add a threshold if someone has a very fine grained grid, something like grid size < junction radius.

**Comment by palvarezlopez** [comment]
I think disable grid with ctrl+g is the easiest way to solve this. Grid could be usefull for certain shapes.

**Comment by behrisch** [comment]
I think the problem is that you do not notice that the grid is still active. Maybe we could at least emit a warning or something if someone enables junction / walking area editing while the grid is still active.

**Comment by palvarezlopez** [comment]
We have already two flags for grid: The grid drawed in background and the enabled checkbox in the toolbar. Do you think that we need more?

![Sin título](https://user-images.githubusercontent.com/8238561/210247913-328a407e-43e1-437e-97f9-a16872a36a06.png)

**Comment by behrisch** [comment]
Just a small reminder in the message window maybe? Something like "Warning: Grid is still active, press ctrl+g to deactivate" whenever someone switches to the editing mode for walking areas / junctions (and maybe even lanes)

**Comment by palvarezlopez** [comment]
Ok, I add it.
