### ISSUE TITLE
netconvert removes tls phases when deleting connections

### ISSUE THREAD

**Issue by jjyyxx** [eclipse/sumo#12247]
A default 3-lane junction generated with `netgenerate` generates:
- lane 0: r + s
- lane 1: s
- lane 2: l + s

Then I use `netconvert` to remove these too many (for me) straight connections. But this also removes the dedicated left green phase (controlled by `--tls.left-green.time`). My current workaround is to call `netconvert` a second time and rebuilds tls with `--tls.discard-loaded true --tls.guess true` to restore the dedicated left green phase.  (Mixing the second time's options with the first one leads to another weird behavior, creating more tls links than the number of connections.)

Since this can be restored, the previous removal seems like incorrect behavior to me (maybe related to #12143).

netgenerate
```
netgenerate --output-file m.net.xml --rand --rand.iterations 5 --rand.grid --rand.min-distance 120 --rand.max-distance 120 --rand.min-angle 60 --rand.bidi-probability 1.0 --no-turnarounds true --tls.cycle.time 90 --tls.yellow.time 3 --tls.layout opposites --tls.left-green.time 6 --tls.minor-left.max-speed 19.44 --internal-junctions.vehicle-width 3 --junctions.internal-link-detail 5 --junctions.corner-detail 0 --default-junction-type traffic_light --rand.random-lanenumber False --default.speed 10.0 --default.lanenumber 3 --default.lanewidth 3.75 --default.junctions.radius 8.0 --perturb-x 0 --perturb-y 0 --lefthand False --seed 763607780 --precision 8
```

netconvert
```
netconvert --output-file m.net.xml --sumo-net-file m.net.xml --connection-files connections.xml --seed 1465149968 --precision 8
```

connections.xml
```xml
<?xml version='1.0' encoding='utf-8'?>
<connections version="1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/connections_file.xsd">
    <delete from="-17" to="9" fromLane="0" toLane="0" />
    <delete from="-17" to="9" fromLane="2" toLane="2" />
    <delete from="-3" to="7" fromLane="0" toLane="0" />
    <delete from="-3" to="7" fromLane="2" toLane="2" />
    <delete from="-7" to="3" fromLane="0" toLane="0" />
    <delete from="-7" to="3" fromLane="2" toLane="2" />
    <delete from="-9" to="17" fromLane="0" toLane="0" />
    <delete from="-9" to="17" fromLane="2" toLane="2" />
</connections>
```

netconvert 2 (workaround)
```
netconvert --output-file m.net.xml --sumo-net-file m.net.xml --tls.discard-loaded true --tls.guess true --tls.cycle.time 120 --tls.yellow.time 3 --tls.layout opposites --tls.left-green.time 6 --tls.minor-left.max-speed  19.44 --precision 8 --seed 1465149968
```

**SUMO-version:** 1.15.0

**operating system:** Windows 10 / Ubuntu 22.04

**Comment by namdre** [comment]
The original network created by netgenerate doesn't have a dedicated left turn phase (due lack of a dedicated turning lane). Insofar no *removal* of a left-turn phase takes place.

When you patch a .net.xml file with new connections, the current code assumes that the original tls plan should be "fixed" rather than rebuilt from scratch. 

It might be useful to provide a **--tls.rebuild** option because your solution of **--tls.discard-loaded true --tls.guess true** does not guarantee that all node types will be restored. 

If you want dedicated left turn phases in netgenerate networks, consider using option **--turn-lanes 1 --turn-lanes.length X**

**Comment by jjyyxx** [comment]
@namdre Thank you for your quick response! It's my mistake that I **carelessly assumed that** ~~*the original network created by netgenerate has a dedicated left turn phase*~~. Now everything is much clearer. I agree it's a good idea to have **--tls.rebuild** to recreate traffic light programs.

There is still one point I find confusing: could you explain a bit more about my workaround *does not guarantee that all node types will be restored*? For the pipeline `netgenerate -> netconvert 1 -> netconvert 2` described above (maybe with more nodes in netgenerate), are there any potential problems using this workaround?

**Comment by namdre** [comment]
Option tls.guess assigns traffic lights based on number of lanes and lane speeds.  If the input network has some "small" junctions that are controlled and some "big" junctions that are uncontrolled then after using discard+guess the small junctions will be uncontrolled and the big junctions controlled instead.

It may not be a problem for the style of network you are getting out of netgenerate though.
