### ISSUE TITLE
tls buidling for >4-leg intersections

### ISSUE THREAD

**Issue by ambuehll** [eclipse/sumo#12249]
Hello,

I am sorry to bring up these tls problems again and again, I am just trying to find work-arounds, but most fail. 
So, here we go again:
<img width="271" alt="image" src="https://user-images.githubusercontent.com/48930860/206204679-a96a4fe5-5d9a-40ed-b1f4-88d11bc88e30.png">

This is a bit of a complex intersection, which gets tls when tls.discard-simple is false. But doesn't when it's true. Setting tls.guess does create tls, but in a cumbersome way, and in addition I don't like using tls.guess too much, as it creates tls in the whole network, where there are none in reality (I know that's still sometimes useful).

<img width="201" alt="image" src="https://user-images.githubusercontent.com/48930860/206205293-3b2daf07-ca75-4a20-b952-9d9243e88274.png">

So, any work-around would be appreciated. This might be related to https://github.com/eclipse/sumo/issues/12163

As always, many many thanks!
Lukas

*If possible, upload an example that shows your problem.*

**SUMO-version:** latest

**operating system:** win

[files](https://drive.google.com/drive/folders/1BsM2o2CIzRArz8hfl8LhM_0VgcR4UtmX?usp=share_link)

**Comment by namdre** [comment]
The problem why **tls.guess-signals** fails here is because the incoming edge from the north-west (*-92142133*) doesn't have an upstream traffic_light node.  I recall that we had similar cases multiple times before and I'm trying to think of a solution.

We could give the heuristic some slack (i.e. signals on 3 out of 4 incoming edges is enough to declare the central node as the *actual* traffic light node. (i.e **--tls.guess-signals.slack INT** to specify how many uncontrolled edges are permitted)

PR welcome (-:

**Comment by ambuehll** [comment]
Thanks for looking into this! That's what I thought. I think giving north-west a signal isn't an issue if all the others at least would get one. but right now, some seem to get two. And also the one from the south has a weird look. I'll post some other examples, that I have somewhere, when I find some time.

**Comment by namdre** [comment]
There is a crucial difference between **--tls.guess** and **--tls.guess-signals**.
- the former is a heuristic that guesses based on junction size and is quite error prone
- the latter detects "simple" traffic lights around an uncontrolled central junction and infers that these are actually the signals of the central junction (thus it is usually quite accurate). Currently, it requires signals to be found on all incoming arms which a new *slack* option should remedy.

Hence, the solution i'm proposing works without **--tls.guess**

**Comment by ambuehll** [comment]
ah, sorry, too tired... got it. makes sense.
