### ISSUE TITLE
misguiding info in lane/edge output info about normalization

### ISSUE THREAD

**Issue by ambuehll** [eclipse/sumo#12248]
see: 
https://sumo.dlr.de/docs/Simulation/Output/Lane-_or_Edge-based_Traffic_Measures.html

"In the case of the edge-dump the values are not only **_normalized_** by the number of the collected vehicle moves and the length of the lane, but also **_by the number of lanes of the edge._** "

-> this is not the case for density; only for laneDensity

**Comment by namdre** [comment]
fixed in 778e51dbb28ed2c411ee5f8b5956051f862ebe12
