### ISSUE TITLE
do not modify shape points which were not edited

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#12244]
If I edit a very detailed junction shape with a lot of nearby points the automated point merge will also merge points which are nowhere near my edit

**Comment by palvarezlopez** [comment]
Solution: Flag for disabling automatic merge points

**Comment by palvarezlopez** [comment]
Fixed in https://github.com/eclipse/sumo/commit/21e5b949e674eb741fdcc2c1e34990247852050e
