### ISSUE TITLE
Cannot compile JuPedSim in Windows (VS 2017) due to fmt library

### ISSUE THREAD

**Issue by m-kro** [eclipse/sumo#12254]
Related to #12913 . Cannot compile JuPedSim as the fmt library v.9.0 still triggers a C2662 error (differently than expected).

**Comment by behrisch** [comment]
Since we have a (more or less) functional CI build on github now, I consider this wontfix. We will not ship all jupedsim dependencies in SUMOLibraries but only the readily built jupedsim
