### ISSUE TITLE
what is the difference between duarouter and trip-file input?

### ISSUE THREAD

**Issue by Eviannn** [eclipse/sumo#12252]
Hi, when I use trip-file as input of the simulation, and output all the routes after the simulation, I find 1500 different routes in my network. However, when I use duarouter to transfer the trip-file into the route-file, and other settings are all default values, I only find 700 different routes. So I wonder what is the difference between duarouter and trip-file input? Which method is more real and recommended?

**Comment by namdre** [comment]
duarouter (by default) computes fastest routes under the assumption that all roads permit travelling at the speed limit.
In contrast, sumo computes routes according to the current traffic conditions in the network.
A good introduction to the topic can be found at https://sumo.dlr.de/docs/Demand/Dynamic_User_Assignment.html#introduction
