### ISSUE TITLE
**SUMO-traffic jam:**  ** Python**

### ISSUE THREAD

**Issue by xhy12345x** [eclipse/sumo#12267]
**SUMO-traffic jam:**
How to achieve traffic congestion in SUMO? I tried to use flow to write the traffic flow, but found that the speed obtained was almost the same, which could not generate traffic congestion.

**Comment by m-kro** [comment]
Depending on your network geometry you have several options to make traffic congestions more probable:

- distribute the vehicles across lanes on insertion to get high volumes (see [docs](https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#departlane))
- create a bottleneck (can be lane reduction, traffic light, ...)
- let vehicles choose individual speeds from a large range (see [docs ](https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#speed_distributions)about speed factor)

**Comment by namdre** [comment]
we have several tests that create jam density and you can download them here: https://sumo.dlr.de/extractTest.php?path=sumo/cf_model/fundamental

See also:
https://sumo.dlr.de/docs/Simulation/RoadCapacity.html
https://sumo.dlr.de/docs/Tutorials/FundamentalDiagram.html#fundamental_diagram_on_a_straight_piece_of_road

**Comment by xhy12345x** [comment]
Thank you very much！ The scene I simulated is that there are two lanes in the upstream and downstream of the expressway, and three lanes in the acceleration ramp. I want to create congestion on the acceleration ramp. If I want to adopt the measure of speed factor, what is the speed factor.




3447386862
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "eclipse/sumo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月9日(星期五) 晚上7:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [eclipse/sumo] **SUMO-traffic jam:**  ** Python** (Issue #12267)





 
Closed #12267 as completed.

**Comment by namdre** [comment]
You need to ensure enough traffic density on the expressway lanes and the easiest way to do this is by adding the attributes `departLane="free" departSpeed="avg"` to your flow.
If you want to simulate at the default step -length of 1s then the option **--extrapolate-departpos** also helps to achieve high density.

For speedfactor, please refer to the documentation linked in https://github.com/eclipse/sumo/issues/12267#issuecomment-1344192637
