### ISSUE TITLE
No signal intersection

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#12274]
Hello, if I study the vehicle scheduling of unsignaled intersections and I control the vehicle movement by myself, does the priority of my intersections need to be removed？From the picture ,you can get the order of passage from the stop line's color.
![image](https://user-images.githubusercontent.com/54823725/206893204-54976de4-9548-4a93-bea9-93437e656ec6.png)

**Comment by namdre** [comment]
if you control the vehicle movements with TraCI, you can make the vehicles ignore the original priorities so you do not need to change the network.

**Comment by a-123-du** [comment]
> 如果使用 TraCI 控制车辆移动，则可以使车辆忽略原始优先级，因此无需更改网络。
OK，thank you
