### ISSUE TITLE
KINEMATIC BICYCLE MODEL FOR VEHICLES 

### ISSUE THREAD

**Issue by LorenzoUccello** [eclipse/sumo#12278]
Hello, 

I have a question about the vehicle model used in SUMO. 
Is it possible to use a kinematic bicycle model to represent the vehicles in the simulation?

**SUMO-version:** v1_14_1+0776-419d5e4252e

**operating system:**MacOS Monterey

**Comment by namdre** [comment]
There are no kinematic models in SUMO (neither for cars nor bicycles). Instead longitudinal and lateral movements are computed by distinct models (carFollowMode, laneChangeModel).
 You can remote control vehicles with a coupled process using the TraCI API (traci.vehicle.moveToXY) to employ any model you want. See https://sumo.dlr.de/docs/TraCI.html
