### ISSUE TITLE
What is the working principle of the "--emission-output" command?

### ISSUE THREAD

**Issue by erev-84** [eclipse/sumo#12273]
Hello,

What is the working principle of the command "--emission-output"? How does this command predict how much co2 a vehicle emits?

**Comment by namdre** [comment]
please refer to the individual model descriptions and linked literature

**Comment by erev-84** [comment]
Hello,

First of all thank you very much for reply

I checked the link you sent but unfortunately I did not understand the logic behind it and I would be glad if you can explain how emissions created with the command I mentioned on my first message

**Comment by namdre** [comment]
Did you read this? http://elib.dlr.de/89398/

**Comment by erev-84** [comment]
Yes I read it but unfortunately I did not understand the working principle of the "--emmision-output" command, I would be glad if you can explain it to me shortly because I really want to know how it works and how the outputs are generated

**Comment by namdre** [comment]
see https://github.com/eclipse/sumo/blob/e63aa960e18e76089a9d5bc65d67f4bbb8a120cf/src/utils/emissions/HelpersHBEFA3.h#L96
