### ISSUE TITLE
black screen when starting with option --osg-view

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#12281]
was still working in 1.15.0

**Comment by m-kro** [comment]
Still works on my side... ?!

**Comment by namdre** [comment]
I seems to be network-specific:
- test/sumo/net3.net.xml shows the problem
- test/sumo/net2.net.xml works

**Comment by m-kro** [comment]
Well, it is what i supposed earlier: The viewport looks down on the black road but the model is loaded correctly. Just zoom out. Rather the bad initial viewport is to blame.

**Comment by namdre** [comment]
but why is the viewport so close to the ground? This didn't happen before.

**Comment by m-kro** [comment]
Should be OK again now - but cannot remember why I deleted the relevant lines before ?!
