### ISSUE TITLE
Warning: Command returned negative repeat number; will be deleted.

### ISSUE THREAD

**Issue by JamesPsh** [eclipse/sumo#12286]
A warning message like the title.
I'm not sure what the message means. Could you tell me the meaning?

thank you.

![image](https://user-images.githubusercontent.com/101240964/207246780-290b2c82-8b56-4b2c-b6ce-428899d7514f.png)

**Comment by namdre** [comment]
This is an internal debug message related to scheduling of timed events. It suggests that some things may not be working as expected. Can you provide the input files to reproduce these messages?

**Comment by JamesPsh** [comment]
hello.

As a result of checking,
it was a warning that occurred because the duration was a negative number in the xxx.tll.xml file.
~~~
      <phase duration="-4" state="ggGGGGggGGG"/>
~~~

After removing the negative number and running the simulation again, the warning no longer occurred.
