### ISSUE TITLE
lane change question

### ISSUE THREAD

**Issue by ckh0715** [eclipse/sumo#12289]
why the posLat error? Please look the yellow and green vehicle, LCM is LC2013.

![070SV)8HCYX(S8)JZ }IB~4](https://user-images.githubusercontent.com/56399136/207311851-4930227a-9087-4c66-98e2-bf120025186f.png)

![K (773R7MUBD}7PQFRE9711](https://user-images.githubusercontent.com/56399136/207311257-8bc9a8b6-b51b-4158-8860-0a01cca228e4.png)

**Comment by m-kro** [comment]
Could you please share your files? It is difficult to guess from the screenshots what is happening.

**Comment by m-kro** [comment]
No, please attach the SUMO files like the network, routes definition and so on (e.g. in a zip archive).

**Comment by namdre** [comment]
lateral movements are expected when setting `lcSigma` != 0. However, this should not cause vehicles to drift outside lane bounds.

**Comment by m-kro** [comment]
Actually the vehicles move/are animated in the opposite direction of their target lane (lanechange.duration is set).

**Comment by namdre** [comment]
The lane numbering in the network is different from the expectation (0 should be the rightmost lane in driving direction).
Also, the network is lacking the header. Taken together this strongly suggests that some unusual processing was done on the .net.xml

**Comment by namdre** [comment]
Instead, please generate plain-xml inputs and let netconvert build the network: https://sumo.dlr.de/docs/FAQ.html#i_made_changes_to_the_netxml-file_but_it_did_not_work_as_expected_why
