### ISSUE TITLE
stateReplay for Windows

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#12298]
Currently the dependency on rsync requires Linux or MacOS

**Comment by behrisch** [comment]
still does not work

- [ ] absolute paths are not handled correctly when picking up the state files
- [ ] documentaion should mention how to do ssh without passwords

**Comment by robertalms** [comment]
You're recent changes for the windows/linux path defintion work just fine. Thanks!

**Comment by behrisch** [comment]
needs activation of WSL for the test servers
