### ISSUE TITLE
merge two separate lanes 

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#12299]
How to create a one way single lane?Or how to merge two separate lanes into one lane? I want to merge the lane1 and lane2 into a single lane.
![image](https://user-images.githubusercontent.com/54823725/207628623-ebe3878b-9080-40c5-98fe-1e22c54e4421.png)

**SUMO-version:1.14**

**operating system:Windows**

**Comment by palvarezlopez** [comment]
The most easy way is removing lane 1 (using delete mode), inspect lane 2 and optionally set spreadtype="center".

**Comment by a-123-du** [comment]
> The most easy way is removing lane 1 (using delete mode), and optionally inspect lane 2 and set spreadtype="center".

OK，I have done this.But why does the one way single lane not have the connections(internal lanes)?
![image](https://user-images.githubusercontent.com/54823725/207796049-82904074-2b4e-4c8f-a00a-a24a5508ab93.png)

**Comment by palvarezlopez** [comment]
You can not see connections in "Connection mode"?

**Comment by a-123-du** [comment]
![image](https://user-images.githubusercontent.com/54823725/208300811-73fdbf8e-6e43-46de-a7fd-6a2b454e6789.png)
Yes, I have click the"show connections over junctions" in the edit tool, but there isn't the connections in the graph.

**Comment by palvarezlopez** [comment]
Can you please add the network here in the current status to check it?
