### ISSUE TITLE
why getTimeLoss didnt work

### ISSUE THREAD

**Issue by e1958229** [eclipse/sumo#12303]
getTimeLoss does not work. Does anyone know why? When I try to move it, I get an error.

![image](https://user-images.githubusercontent.com/113490031/207770047-38af7f9b-68e2-4014-86fd-00eaee258b2d.png)
![image](https://user-images.githubusercontent.com/113490031/207770370-17ba7b52-41ae-4165-a3f4-ce87a2947f4b.png)

PS
getDeparture does not work too. traci version 1.15.0
![image](https://user-images.githubusercontent.com/113490031/207772357-77d90696-add7-4286-8ddb-cb758d17c873.png)

**Comment by m-kro** [comment]
Does your SUMO_HOME environment variable point to an older SUMO version? In your second screenshot, it reads "Simulation version 1.6.0 [...]". Please check and update the path to point to your SUMO v.1.15 main directory.

**Comment by e1958229** [comment]
Ohhhh! Thank you! I appreciate your quick reply.

**Comment by e1958229** [comment]
Sorry, can the update be completed by installing SUMO again? Im using translator.

**Comment by m-kro** [comment]
I think that the installer cares about the environment variable. In case this does not work, you can do it separately. There are several resources on the internet which show how to set environment variables in Windows, for example [this one](https://phoenixnap.com/kb/windows-set-environment-variable#ftoc-heading-4).

**Comment by e1958229** [comment]
Thank you for taking the time to do this. Maximum thanks.

**Comment by e1958229** [comment]
I tried it, TimeLoss worked, but getDeparture doesn't for some reason. Do you know the cause?
![image](https://user-images.githubusercontent.com/113490031/207817599-6fa8fc1d-3ec3-481e-8126-ba15d02661b2.png)

**Comment by m-kro** [comment]
Please post the error / result you get after calling `traci.vehicle.getDeparture`, as you did in the first post.

**Comment by namdre** [comment]
getDeparture is not available in 1.15.0 but only in dev: https://sumo.dlr.de/docs/Downloads.php#nightly_snapshots

**Comment by e1958229** [comment]
First of all, I apologize for the delay in replying. Thank you for your response. I will calculate it another way for now.
