### ISSUE TITLE
NETEDITConfig files

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#12309]
- Currently there are many NETEDIT exclusive options (prefixes, meandata-files, outputs, etc)
- These options **can't** appear in SUMOConfigs to avoid incompatibilities.
- Currently in NETEDIT we can load SUMOConfigs, but can be confused to the user due different options

Solution: NETEDITConfig files (*.neteditcfg)

- This file works like a "project file"
- Can be loaded and saved by menus and through netedit.exe --neteditcfg (file)
- NETEDIT can deal with SUMOConfigs and NETEDITConfigs, but SUMO only with SUMOConfigs
- Make NETEDIT test more easy (load single NETEDITConfig instead a big command input file)
- Double click over SUMOConfig open SUMO-GUI, double click over NETEDITConfig open NETEDIT (very useful for Windows users)

Update:

- [x] Netedit must support --configuration <netconvertFile, NETEDITConfig file>
- [x] Saving NETEDITConfig file will give automatic names to network/additonal/etc. files

**Comment by palvarezlopez** [comment]
@namdre @behrisch @angelobanse @m-kro What do you think?

**Comment by namdre** [comment]
netedit can already load config files from the command line. So this is mostly about making them accessible via UI and promoting their use as something like a *project file*.
