### ISSUE TITLE
problems with edge.setAllowed

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#12305]
- it doesn't work
- the method name in the traci client differs from the method name in libsumo (`setAllowedVehicleClasses`)

**Comment by namdre** [comment]
Surprisingly, this is not a regression. It never worked!

**Comment by justinehadean** [comment]
Hi, I've tried to use this method and it's still giving the same error: "Change Edge State: unsupported variable 0x34 specified". Could you look into it? Thanks.
