### ISSUE TITLE
netEdit slows down with converted opendrive file

### ISSUE THREAD

**Issue by msnir009** [eclipse/sumo#12302]
I tried to convert an opendrive file into a sumo network file by using the basic netconvert command. The conversion works fine with some warnings. But when I load the network onto netEdit and when I try to zoom into a particular lane or part of the area, it is very slow or just hangs.  

I do get an error at the beginning of the conversion as below (but still ends up as success in the end): 
proj_create: Error 1029 (File not found or invalid): pipeline: Pipeline: Bad step definition: proj=vgridshift (File not found or invalid)
Warning: Ignoring geoidgrids and vgridshift in projection

Is there anything else I should add to the command or that should  be removed from the xml file to make it faster? 

*If possible, upload an example that shows your problem.*

**SUMO-version: 1.15.0**

**operating system: Windows 10**

**Comment by namdre** [comment]
try setting option **--opendrive.curve-resolution 20** and see if this speeds things up.

**Comment by msnir009** [comment]
this helped. thank you very much!
