### ISSUE TITLE
if function is wrong in line 426 of routeSampler.py?

### ISSUE THREAD

**Issue by Eviannn** [eclipse/sumo#12307]
Hi, I wonder if  it is Ax + s = b in line 426 instead of x + s = b?

For a simple case, objective is min s, subject to Ax + s = b, and s >= 0, am i right?

Or we can say min z=b-Ax, subject to Ax<=b?

**Comment by Eviannn** [comment]
And I have another question, when I use routeSampler.py, if I set --optimize full, after stage "routes will be sampled from the input route set until no further routes can be added without exceeding one of the counts" ,  optimization algorithm would be used,  so is the result of  stage "routes will be sampled from the input route set until no further routes can be added without exceeding one of the counts" important? If I do not excute that stage and use optimization algorithm directly, is the result same?  I know if I set --optimize INT, that stage is important.

**Comment by namdre** [comment]
> Hi, I wonder if it is Ax + s = b in line 426 instead of x + s = b?

yes

> If I do not execute that stage and use optimization algorithm directly, is the result same?

Theoretically, the first sampling stage should not matter but practically, the optimizer may fail to find a solution unless it is provided with an initial value by the sampling stage.

**Comment by Eviannn** [comment]
> 

u mean u set x0 to provide an initial value by the sampling stage in "res = opt.linprog(c, A_ub=A_ub, b_ub=b_ub, A_eq=A_eq, b_eq=b, bounds=bounds, x0=x0, options=linProgOpts)"?

However, it shows "OptimizeWarning: x0 is used only when method is 'revised simplex'.
  warn(warning_message, OptimizeWarning)" when I use routeSampler.py, which means that x0 is not there, so the initial value is not given, and the sampling stage does not matter at all. 

Then I tried to set method='revised simplex', but x0 should be a basic feasible solution. However, the initial value provided by the sampling stage is not a basic feasible solution, it is a feasible solution, so the optimization fails.

So the result shows that x0 does not help at all.

**Comment by Eviannn** [comment]
> u mean u set x0 to provide an initial value by the sampling stage in "res = opt.linprog(c, A_ub=A_ub, b_ub=b_ub, A_eq=A_eq, b_eq=b, bounds=bounds, x0=x0, options=linProgOpts)"?
> 
> However, it shows "OptimizeWarning: x0 is used only when method is 'revised simplex'. warn(warning_message, OptimizeWarning)" when I use routeSampler.py, which means that x0 is not there, so the initial value is not given, and the sampling stage does not matter at all.
> 
> Then I tried to set method='revised simplex', but x0 should be a basic feasible solution. However, the initial value provided by the sampling stage is not a basic feasible solution, it is a feasible solution, so the optimization fails.
> 
> So the result shows that x0 does not help at all.

**Comment by namdre** [comment]
1. I can confirm that the inclusion of x0 makes no difference in our current regression tests. I do recall this making a difference in the past but this was likely with an older python (and scipy) version and some specific data set.
2. I agree that the formulation of x0 is in error and `priorRelevantRouteCounts + [cd.count for cd in countData]"` is correct. This problem is obviously hidden by point 1.
3. I'm speculating here that my prior impression of a positive impact of x0 in the optimization might have been mistaken or that even a faulty x0 (wrong values + not basic) might have some random and sometimes beneficial impact on the optimization behavior. Obviously, this should not be relied upon.
