### ISSUE TITLE
proj.db is included twice in the release zip

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#12316]
- included sumo/share/proj and in sumo/data/proj
- two different versions!
- has been happening since 0.12.0. Earlier versions did not contain data/proj

possibly related: #8497, #7848, #6155

**Comment by palvarezlopez** [comment]
@behrisch did you a git clean of entire repository before compiling release?

**Comment by namdre** [comment]
another interesting thing:  The data/proj folder is empty in the *extra* release. There has been a report of `pj_obj_create: Cannot find proj.db` when running the extra version.

**Comment by behrisch** [comment]
> @behrisch did you a git clean of entire repository before compiling release?

It is always a clean build
