### ISSUE TITLE
counter lanechange deadlock after busstop

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#12320]
Bus A stops at the bus stop in lane 0, Bus B wants to reach the same stop and is waiting behind but in lane 1. Bus C also wants to reach the same stop but waits behind A in lane 0. When A moves both B and C advance. C reaches the stop first but needs to change lanes to leave it. B wants to change the other way -> deadlock

**Comment by behrisch** [comment]
The reason may also be a strange connectivity which is not handcrafted but comes directly from a webwizard scenario

**Comment by namdre** [comment]
Problem: hardcoded imperative to not change to a lane with a stopped vehicle ahead. 
Solutions:
  - consider remaining stop duration
  - consider the special case where ego also needs to stop on that lane

**Comment by namdre** [comment]
regression via #12113
