### ISSUE TITLE
What is the difference between getJunctionIndex and getTLLinkIndex among connection related methods?

### ISSUE THREAD

**Issue by JamesPsh** [eclipse/sumo#12323]
In sumolib, What is the difference between getJunctionIndex and getTLLinkIndex among connection related methods?

And node.getLinkIndex(conn) matches which method above?

thank you~

**Comment by m-kro** [comment]
Each connection inside a junction gets a unique junction index by which it can be identified. This index can change when the junction is edit & recomputed. The TL link index refers to a column of the associated TL program. A TL program can control multiple junctions together and multiple connections can use the same signal value. `node.getLinkIndex` refers to the junction index.

**Comment by namdre** [comment]
see https://sumo.dlr.de/docs/Simulation/Traffic_Lights.html#defining_signal_groups
