### ISSUE TITLE
How to separate the network files into two files (pedestrian road and all other roads) and load them seperately into netedit without error.

### ISSUE THREAD

**Issue by thilagaguru** [eclipse/sumo#12324]
Operating system : Windows 10
Sumo version : 1.12.0

I am working on SUMO network file. I want to know how to achieve the below steps. 

Step1:
For my work purpose, I would like to seperate network file (net.net.xml) into two parts. 
1. Network file contains only the pedestrian road (netped.net.xml)
2. All the other roads (except pedestrian road) into a seperate network file (netroad.net.xml). 
I have enclosed all the three network files into the zip file

Step2:
I would like to load only the pedestrian network file in netedit and make some changes into the network and save.
Then I would like to load the road network file sepearately in the netedit and make changes to the network and save.  

What i have done so far is :

I have seperated the network file(net.net.xml) into only pedestrian road as seperate xml file (netped.net.xml) and all the other road network (netroad.net.xml) into a seperate xml file (using python xml coding). 
When I load the seperated files on the netedit, I ended up with the below issues.

1.While loading only the pedestrian road network file(netped.net.xml), the netedit automatically closes
2.I am getting connection errors for the all the other road network files (netroad.net.xml).  

I would like to know,
Is there any possible ways to seperate only the pedestrian road alone from the network and load the seperated pedestrian network into netedit without errors and viceversa.

For reference, I am enclosing the network file (net.net.xml), seperated pedestrian network file (netped.net.xml) and all other road network files (netroad.net.xml) 
[network file.zip](https://github.com/eclipse/sumo/files/10255102/network.file.zip)

Thanks in Advance,
Thilaga.

**Comment by m-kro** [comment]
Have a look at the [netconvert options](https://sumo.dlr.de/docs/netconvert.html#edge_removal) for edge removal. Sounds like calling `netconvert -s inout.net.xml --keep-edges.by-vclass pedestrian -o output.net.xml` could fit your purpose to keep only the network pedestrians can use.

**Comment by namdre** [comment]
- you can merge networks: https://sumo.dlr.de/docs/netconvert.html#merging_networks
- you can split networks by vClass or edgeType or simple a list of edge ids
- keeping the pedestrian and vehicular parts separate is probably not feasible if you want the modes to interact (i.e. pedestrian crossings). You will run into problems with defining traffic lights since they will be different in the non-pedestrian network, in the pedestrian-only network and in the merged network.

Maybe there is some other way the solve the original problem that is causing your desire to separate the networks?

**Comment by thilagaguru** [comment]
> * you can merge networks: https://sumo.dlr.de/docs/netconvert.html#merging_networks
> * you can split networks by vClass or edgeType or simple a list of edge ids
> * keeping the pedestrian and vehicular parts separate is probably not feasible if you want the modes to interact (i.e. pedestrian crossings). You will run into problems with defining traffic lights since they will be different in the non-pedestrian network, in the pedestrian-only network and in the merged network.
> 
> Maybe there is some other way the solve the original problem that is causing your desire to separate the networks?

Thank you so much for the reply. I understood the issues clearly when we seperate pedestrian only network from the other road network. 
I will consider other option for the solving the original problem without seperating the network.
