### ISSUE TITLE
Check route traci

### ISSUE THREAD

**Issue by hassanidoudi** [eclipse/sumo#12321]
Hi all,

I want to check if a route exists between a beginning edge and an end edge using Traci.
so get the result of verification.

Regards
Hassan

**Comment by m-kro** [comment]
If you do not [open/close lanes](https://sumo.dlr.de/docs/sumo-gui.html#closing_and_opening_edges_and_lanes) during the simulation, then you could use [sumolib ](https://sumo.dlr.de/pydoc/sumolib.net.html) instead of TraCI: For example sumolib.net.getShortestPath. You can instatiate the sumolib net object like this:
```
net = sumolib.net.readNet(pathToNet)
route = net.getShortestPath("startEdgeID", "endEdgeID")
```

**Comment by namdre** [comment]
https://sumo.dlr.de/pydoc/traci._simulation.html#SimulationDomain-findRoute

**Comment by hassanidoudi** [comment]
Hi all I
 am programming with c++ and I need a function in traci not sumolib or how can import sumolib in c++. 
Regards 
Hassan

**Comment by namdre** [comment]
You can use function `Simulation.findRoute` from C++:
https://sumo.dlr.de/docs/Libsumo.html
https://sumo.dlr.de/docs/Libtraci.html

There is currently no C++ equivalent for sumolib.

**Comment by hassanidoudi** [comment]
Hi all,

Can I use sumolib inside veins omnet++?

Regards
Hassan

**Comment by m-kro** [comment]
As fas as I know, Veins means C++, thus no. Please look into `Simulation.findRoute` (see post above).

**Comment by hassanidoudi** [comment]
Hi all,

using veins I cannot use simulation.findroute because veins are already connected to sumo with traci and I couldn't implement a function called findroute in veins to connect with the traci findroute because of the return type (stage object)

Regards,
Hassan

**Comment by namdre** [comment]
At this point your best approach is probably to engage with the Veins developers on Stackoverflow: https://veins.car2x.org/documentation/faq/

**Comment by m-kro** [comment]
Veins has its own interface to generate and process TraCI messages, limited to the functions the developers deem useful. See [TraCICommandInterface](https://github.com/sommer/veins/blob/master/src/veins/modules/mobility/traci/TraCICommandInterface.cc) in their github repo.
