### ISSUE TITLE
Speed control mode in ACC and CACC

### ISSUE THREAD

**Issue by mehmetnedimyavuz** [eclipse/sumo#12349]
Hello, I would like to ask speed control mode in ACC and CACC car following model according to documentation.  In ACC model, speed control mode: "The speed control mode is designed to maintain the pre-defined by the driver desired speed and is activated when there are no preceding vehicles in the range covered by the sensors or preceding vehicles exist in a spacing larger of 120 m." In CACC model, "The speed control mode is designed to maintain the pre-defined by the driver desired speed and is activated when there are no preceding vehicles in the range covered by the sensors or when the time-gap is larger than 2 s." Why ACC model defines a certain distance (120 m) for speed control mode, CACC model defines in terms of time headway? Can you clarify this issue? Thank you for help.

**Comment by namdre** [comment]
@robertalms can you help with this?

**Comment by robertalms** [comment]
Hi there,
I can only encourage you to look into the respective references given in the SUMO documentation (plus TransAID report WP3.1. You should find the link in the Wiki as well). 
In principal, the CACC model accounts for desired time gaps whereas the ACC model evaluates the gap error and speed difference to the preceding vehicle. I would assume that the additional time gap (2 seconds) for mode (i) was added to perpetuate the speed cruising mode reasonably longer than it would, if only accounted for the sensor range.
