### ISSUE TITLE
Bad default settings when loading a 2D viewport in OSG view

### ISSUE THREAD

**Issue by m-kro** [eclipse/sumo#12348]
Currently, default values for camera and "lookAt" position are (-1;-1;-1). As there is no check whether "lookAt" and camera Z coordinate are actually overwritten, the resulting view is different from bird position if only X/Y coordinates are present in the view settings. Instead, Z coordinate should be checked and coordinates prepared for bird view if no Z value is found.

**Comment by namdre** [comment]
needs a little rework to preserve written gui settings for the non-3D case.
