### ISSUE TITLE
Convert to roundabout issue

### ISSUE THREAD

**Issue by mehmetnedimyavuz** [eclipse/sumo#12355]
Hello,
I created a four-legged intersection and I would like to convert to a roundabout. According to documentation, I set to junction radius ,right-click on junction and select "Convert to roundabout". After last step,the file is closing suddenly. I am using latest development version. I am adding net file. Can you help with this problem? Thank you,regards.
[roundabout3.net.zip](https://github.com/eclipse/sumo/files/10323405/roundabout3.net.zip)

**Comment by m-kro** [comment]
Was already present in v.1.15

**Comment by namdre** [comment]
was broken in e42cdeedda31ca069878689fa96314c332ca6b65. 
@palvarezlopez I could not find a test for convert-to-roundabout. Can you check and add one in case it is actually missing?

**Comment by palvarezlopez** [comment]
yes
