### ISSUE TITLE
No-signal intersections

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#12356]
I'm working on no-signal intersections,message interaction between intersection controller and vehicle realizes vehicle-road collaboration,whether I can fully control the logic of the vehicle autonomously on sumo.Do you have relevant research or materials for reference?

**SUMO-version:1.15**

**operating system:Windows**

**Comment by m-kro** [comment]
You can find quite a few articles on topics like "autonomous intersection management" and "vehicle-to-infrastructure communication" connected to SUMO withina quick search. Just some example:

- [Intersection management for autonomous vehicles with vehicle-to-infrastructure communication](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7331991/)
- [Safe and Efficient Intelligent Intersection Control of Autonomous
Vehicles](https://digitalcommons.du.edu/cgi/viewcontent.cgi?article=2541&context=etd)

**Comment by a-123-du** [comment]
Can you give me more examples, preferably with the source code on github.Thank you very much.

**Comment by m-kro** [comment]
This is out of scope of this issue tracker. Please do yourself some search using the suggested keywords.
