### ISSUE TITLE
about traci.inductionloop.getAllSubscriptionResults()

### ISSUE THREAD

**Issue by Clown1206** [eclipse/sumo#12354]
Add your issue description here.

*If possible, upload an example that shows your problem.*

**SUMO-version: 1.14

**operating system:windows 10
I opened the simulation using traci. Inductionloop. GetAllSubscriptionResults () successfully detected some information, for example：
AllSubsResult:  {'Detector_-gneE16_0': {16: 0, 18: ()}, 'Detector_-gneE17_0': {16: 0, 18: ()}.
When I set up a simulation time (such as 500 seconds) to turn off and then re-open the simulation, but this way with traci. Inductionloop. GetAllSubscriptionResults () will not be able to detect the information. for example: AllSubsResult:  {}
(AllSubsResult is just a variable in my code)

**Comment by namdre** [comment]
please attach a (zipped) log file of all traci commands that you sent (https://sumo.dlr.de/docs/TraCI/Interfacing_TraCI_from_Python.html#generating_a_log_of_all_traci_commands)

**Comment by m-kro** [comment]
Closed due to inactivity. Though please feel free to post here again if your problem remains unsolved.
