### ISSUE TITLE
Traci control vehicle through red light running

### ISSUE THREAD

**Issue by hesuieins** [eclipse/sumo#12351]
Hi all,

Currently, I'm working on a project that includes red light running behavior. I'm wondering if there is any option to allow the TraCI controlled vehicle to run the red light? If not, could you please point out if it is possible to modify part of the code by myself to allow the TraCI controller vehicle not have traffic light information?
Thanks!

**Comment by m-kro** [comment]
See junction model parameter [jmDriveAfterRedTime](https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#junction_model_parameters). Set it to a higher value than the red light duration if you want vehicles to ignore the red signal under any circumstance. You can define multiple [vehicle types](https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#vehicle_types) to have one which respects traffic signals and one which doesn't.

**Comment by namdre** [comment]
also with TraCI you can use setSpeedMode + setSpeed to force red light running: https://sumo.dlr.de/docs/TraCI/Change_Vehicle_State.html#speed_mode_0xb3
