### ISSUE TITLE
Inconsistent between GUI tlLogic parameter and traci.trafficlight.setProgramLogic

### ISSUE THREAD

**Issue by thinker310** [eclipse/sumo#12357]
Hello,  to implement a adaptive traffic light function, I use TraCI to set traffic light program logic in real-time. However, after finishing that, I found the tlLogic parameter, cycle time, in GUI is inconsistent with my setting as shown in the terminal picture:
![uTools_1672547995510](https://user-images.githubusercontent.com/62609436/210161232-f5a7b120-38d0-4a75-a0f6-8cd90f5f286e.png) The cycle time should be 84.
The GUI tlLogic parameter is:

![uTools_1672547941010](https://user-images.githubusercontent.com/62609436/210161246-1077beb5-e6a0-477b-a389-07669c6b5ae5.png)
But the cycle time in GUI is 44. Could you tell me the reason? Is it a bug?

**Comment by m-kro** [comment]
Could you provide a minimal working example and attach it to this issue (e.g. as a zip archive)?

**Comment by m-kro** [comment]
Closed due to inactivity. Though please feel free to post here again if your problem remains unsolved.
