### ISSUE TITLE
a division sign is error typed in the formula of distance between detector and stop line

### ISSUE THREAD

**Issue by lei-won** [eclipse/sumo#12369]
Hi,
I found a typo that could be misleading， the original description  is as follow：

passing-time: estimates the headway between vehicles when passing the stop line. This sets an upper bound on the distance between detector and stop line according to the formula **(minDur / passingTime + 0.5) / 7.5**. The intent of this bound is to allow all vehicles between the detector and the stop line to pass the intersection within the minDur time. A warning will be issued if the minDur gives insufficient clearing time.

The url is https://sumo.dlr.de/docs/Simulation/Traffic_Lights.html#type_actuated

Based on traffic engineering fundamentals and I also checked the src, I think that the formula **(minDur / passingTime + 0.5) / 7.5** should be revised as **(minDur / passingTime + 0.5) * 7.5**
![image](https://user-images.githubusercontent.com/59924958/210522897-050bb8e0-37b9-49bc-a9c6-971f80244a8c.png)

Sincerely

**Comment by m-kro** [comment]
Thanks!
