### ISSUE TITLE
node type drop-down should not have a scrollbar

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#12391]
instead id should be long enough to show all values without scrolling

![Bildschirmfoto von 2023-01-06 11-02-20](https://user-images.githubusercontent.com/6240630/210978029-a88d3f3d-fe65-46bb-bb0d-c22baf04de0d.png)

**Comment by namdre** [comment]
the scrollbar is gone but now the drop-down widget is about 4 lines too long (tested on linux and windows)

**Comment by palvarezlopez** [comment]
Probably related with DPS (with 125 it works)
