### ISSUE TITLE
 vehicle ignores the distance between vehicles

### ISSUE THREAD

**Issue by zhaotuo0815** [eclipse/sumo#12404]

**Comment by zhaotuo0815** [comment]
hello, sumo developers, the question is that the vehicle ignores the distance between vehicles when the signal light is set to be all green.
![TL](https://user-images.githubusercontent.com/59630993/211148486-3ee70e22-cf37-48ce-8079-34da2c4cf189.png)
![TL1](https://user-images.githubusercontent.com/59630993/211148488-f91678de-a293-46e1-9d21-3aead787c5ce.png)
![TL2](https://user-images.githubusercontent.com/59630993/211148490-e0d90b3d-b538-4ee1-aa0f-c12354cb83ad.png)

**Comment by namdre** [comment]
what junction type did you use? traffic_light or traffic_light_unregulated?

**Comment by zhaotuo0815** [comment]
traffic_light




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "eclipse/sumo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月7日(星期六) 晚上10:01
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [eclipse/sumo]  vehicle ignores the distance between vehicles (Issue #12404)





 
what junction type did you use? traffic_light or traffic_light_unregulated?

**Comment by namdre** [comment]
please attach the scenario files (zipped)

**Comment by zhaotuo0815** [comment]
> please attach the scenario files (zipped)

thank you so much!
[TL_Regular.zip](https://github.com/eclipse/sumo/files/10367561/TL_Regular.zip)

**Comment by namdre** [comment]
- vehicle behavior is expected when setting all lights to green (signal state 'G' "promises" exclusive right of way)
  - if the intersection is made bigger or the vehicles drive slower then they will still react to the presence of other vehicles on the intersection but in your scenario there is not enough time for this (such reactions may cause emergency braking and rear-end collisions)
- collisions on junction are only detected when setting option **--collision.check-juncions** (for efficiency reasons)
