### ISSUE TITLE
Incorrect phase switching use setProgramLogic and setPhase

### ISSUE THREAD

**Issue by YSXXXXXXX** [eclipse/sumo#12414]
Hello, I use ```traci.trafficlight.setProgramLogic()```to set a new program logic, 
I want the vehicles from North to South pass the junction first, so I use```traci.trafficlight.setPhase("J1", 0)``` to switch phase. However, the following code cannot execute the new program logic correctly. The flow from North to South cannot pass the junction, and the return value of ```traci.trafficlight.getRedYellowGreenState()```and sumo-gui is inconsistent.
```python
import traci

traci.start(["sumo-gui", "-c", "my.sumocfg", "--quit-on-end", "true"])
trafficLightLogic = traci.trafficlight.Logic(programID=0, type=0, currentPhaseIndex=0,
                                             phases=(
                                                 traci.trafficlight.Phase(5, "GGgrrrGGgrrr"),   # Phase 0
                                                 traci.trafficlight.Phase(5, "yyyrrryyyrrr"),   # Phase 1
                                                 traci.trafficlight.Phase(10, "rrrGGgrrrGGg"),  # Phase 2
                                                 traci.trafficlight.Phase(10, "rrryyyrrryyy")   # Phase 3
                                                )
                                             )
time = 0
while time < 3600:
    traci.simulationStep()
    time += 1
    if time % 30 == 0:
        traci.trafficlight.setProgramLogic("J1", trafficLightLogic)
        traci.trafficlight.setPhase("J1", 0)

```
This is the net file
![gui](https://user-images.githubusercontent.com/98463936/211542083-e5c7e16f-8d54-4e10-b2ad-ba1a159b0213.png)

This is the route file (from North t South)
```xml
<?xml version='1.0' encoding='utf-8'?>
<routes>
	<flow id="E1_E2_0" from="E1" to="-E2" departLane="0" departPos="base" arrivalLane="current" arrivalPos="max" begin="0" end="3600" vehsPerHour="1200" />
</routes>
```

Here are the inconsistent times

|  time    |  return value| gui         |
|  ----    | ----         | ----        |
| 30 - 34  | GGgrrrGGgrrr |rrryyyrrryyy |
| 60 - 64  | GGgrrrGGgrrr | rrryyyrrryyy|
|...       | ...          |...          |

SUMO-version: 1.15

Operating System: Windows 10 

Could you help me?

**Comment by m-kro** [comment]
You have discovered a bug, thanks. The traffic signal does not work correctly when you set the same `traci.trafficlight.Logic` in a row one after another. We will investigate the underlying problem and you can use a workaround like this for the time being:
```
logicSet = False
while time < 3600:
    traci.simulationStep()
    time += 1
    if time % 30 == 0:
        if not logicSet:
            traci.trafficlight.setProgramLogic("J1", trafficLightLogic)
            logicSet = True
        traci.trafficlight.setPhase("J1", 0)
```

**Comment by YSXXXXXXX** [comment]
>The traffic signal does not work correctly when you set the same traci.trafficlight.Logic in a row one after another. 

I have another example, in this example I change the program logic to a different one every 30s, but the traffic signal still works incorrectly.
I think maybe ```traci.trafficlight.setPhase()``` cannot be called immediately after ```traci.trafficlight.setProgramLogic()```? 
The state of the first phase (Phase 0) ```GGgrrrGGgrrr``` in the new program logic seems to be *replaced* by the state of the last phase (Phase 3) ```rrryyyrrryyy``` in the old program logic:
time=30, state in gui is ```rrryyyrrryyy``` the correct sstate is ```GGgrrrGGgrrr``` 
time=60,61 state in gui is ```rrryyyrrryyy``` the correct state is ```GGgrrrGGgrrr``` 
And so on.
```python
import traci

traci.start(["sumo-gui", "-c", "my.sumocfg", "--quit-on-end", "true"])
trafficLightLogic = traci.trafficlight.Logic(programID=0, type=0, currentPhaseIndex=0,
                                             phases=(
                                                 traci.trafficlight.Phase(5, "GGgrrrGGgrrr"),   # Phase 0
                                                 traci.trafficlight.Phase(5, "yyyrrryyyrrr"),   # Phase 1
                                                 traci.trafficlight.Phase(10, "rrrGGgrrrGGg"),  # Phase 2
                                                 traci.trafficlight.Phase(10, "rrryyyrrryyy")   # Phase 3
                                                )
                                             )
time = 0
while time < 300:
    traci.simulationStep()
    time += 1
    if time % 30 == 0:
        trafficLightLogic.phases[0].duration = time / 30
        trafficLightLogic.phases[1].duration = 10 - time / 30
        traci.trafficlight.setProgramLogic("J1", trafficLightLogic)
        traci.trafficlight.setPhase("J1", 0)
```

**Comment by m-kro** [comment]
@YSXXXXXXX The signal state was not updated directly after overwriting the phase definition with TraCI. This has now been corrected. You can download a compiled developer version from [here](https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_development_version) tomorrow, build from source by yourself or wait a few days for the next release.

I'll still add a test for this issue within the next days.

**Comment by YSXXXXXXX** [comment]
OK, thank you very much for your help.
