### ISSUE TITLE
how do vehicles in sumo recognize traffic lights and slow down

### ISSUE THREAD

**Issue by zhl555** [eclipse/sumo#12427]
Hello,
I have a question about vehicles slowing down at traffic lights:
how do vehicles in sumo recognize traffic lights and slow down? I understand that the longitudinal speed of the vehicle is generally controlled by the car-following model, but when encountering a traffic light, how is the longitudinal speed of the vehicle calculated?

**Comment by namdre** [comment]
The junction model computes right of way (https://elib.dlr.de/93669/) and then the
carFollowModel computes the speed with method `stopSpeed`.
