### ISSUE TITLE
invalid rotation of E1/E2 icon detectors

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#12428]

**Comment by namdre** [comment]
still has unexpected rotation:
![Bildschirmfoto von 2023-01-13 09-26-26](https://user-images.githubusercontent.com/6240630/212273440-f42aa769-bed0-4c84-920c-1a97fea5e9bf.png)

Also, there is alread some code to compute the correct rotation. See GUIEdge.cpp:

`double angle = s.getTextAngle(lane1->getShape().rotationDegreeAtOffset(lane1->getShape().length() / (double) 2.) + 90);`

**Comment by palvarezlopez** [comment]
Add arrow with direction
