### ISSUE TITLE
Mini-Roundabout

### ISSUE THREAD

**Issue by mehmetnedimyavuz** [eclipse/sumo#12426]
Hello,
I have two mini-roundabout in my real network. The diameter of these roundabouts are approximately 5-6 meter. When I use "convert to roundabout" with  3 meter radius, the roundabout is created like figure below:
![image](https://user-images.githubusercontent.com/79362739/211745664-7f24dc64-cab2-465b-8a9f-741b20cc6346.png)
When I would like to create a flow between legs of roundabout, I get connection errors. Also I am adding the real network screenshot and network file. How can I solve this problem?Thank you for help,regards.
 
![image](https://user-images.githubusercontent.com/79362739/211749195-d7bb20c1-312a-407b-9d7c-c635a6bc5bba.png)
![image](https://user-images.githubusercontent.com/79362739/211751598-ae0a3ad3-fac5-4b50-946d-cfa4e781345a.png)

[real_roundabout.net.zip](https://github.com/eclipse/sumo/files/10390047/real_roundabout.net.zip)

**Comment by namdre** [comment]
1. the route must include the roundabout edges (i.e. "-E5 E29 E60"). It may help to define the routes/vehicles/flows in netedit as this will fill in the gaps automatically
2. the roundabout looks better if you set radius=0 for the 4 junctions that make up each roundabout
3. also, it may reflect reality better if you set numLanes=2 for the roundabout edges (E28, E29, E30, E31) etc.

**Comment by mehmetnedimyavuz** [comment]
Thank you for recommendations @namdre. I applied last two recommendations on one roundabout and it is created like this:
![image](https://user-images.githubusercontent.com/79362739/211882355-24c0f121-86d7-4a83-9fa3-98f58869a33c.png)
[real_roundabout2.net.zip](https://github.com/eclipse/sumo/files/10394859/real_roundabout2.net.zip)

**Comment by namdre** [comment]
If you need to refine the shape further, you can do this manually by right-clicking on a junction a choosing "set custom junction shape".
