### ISSUE TITLE
i18n.py tries to write code to /usr/local/.. if built under user account

### ISSUE THREAD

**Issue by atellyro** [eclipse/sumo#12439]
i18n.py tries to write code to /usr/local/.. , if
a) build under an user account
b) in a user directory
c) the SUMO_HOME points to /usr/local/share/sumo

Here is an example message
[ 35%] Generating /dosd/src/opensource/Sumo/sumo-git-co/sumo/data/locale/tr/LC_MESSAGES/sumo.mo
msgcat: Ausgabedatei „/usr/local/share/sumo/data/po/de.po“ kann nicht erstellt werden: Keine Berechtigung
Traceback (most recent call last):
  File "/dosd/src/opensource/Sumo/sumo-git-co/sumo/tools/build/i18n.py", line 104, in <module>
    main()
  File "/dosd/src/opensource/Sumo/sumo-git-co/sumo/tools/build/i18n.py", line 93, in main
    subprocess.check_call([path + "msgcat"] + po_files + ["--output-file=" + merged_po_file])
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)

My expectation is:
I can build SUMO everywhere (make), the install process (make install) makes the changes in directories beneath /usr/local

**SUMO-version:**
current git copy, on Dec 29, 2022 it worked

**operating system:**
ubuntu 22.10

**Comment by behrisch** [comment]
I changes the behavior now such that it does not respect SUMO_HOME any longer. If you ever feel the need to process a different sumo directory there is now the --sumo-home option to the script.
