### ISSUE TITLE
configure randomness in rescue lane formation

### ISSUE THREAD

**Issue by heinovski** [eclipse/sumo#12437]
### Context
When an emergency vehicle with an enabled blue-light device approaches, other vehicles will (ideally) create a rescue lane. After the emergency vehicle has passed through the rescue lane, the vehicles will move back to their initial position and thereby close the rescue lane. This process is influenced by a lot of parameters, such as the `reaction distance` of the blue light device, and is therefore not so easy to control. 

### Idea
Therefore, I was wondering whether it would be possible to trigger the creation and closing of a rescue lane via TraCI taking into account all required steps (e.g., lateral alignment, lane change mode, speed, etc.). 

### Benefits
Adding such TraCI commands would allow to create more flexible scenarios and algorithms for improving the traffic flow in the presence of emergency vehicles. It will also make the evaluation of such more deterministic and easy.

### Current Situation
In order to create/close a rescue lane, one currently needs to experiment with a lot of parameters (e.g., reaction distance to blue light device, lateral alignment, lane change mode). This makes the result complex to predict and the impact of the individual parameters not easy to understand. Alternatively, one need to manually trigger lane changes and changes to the lane change mode via TraCI, which is impractical as well.

### Difficulties
I am not sure, however, whether it is easily possible to implement this, since the reaction to emergency vehicles (such as the rescue lane creation) impact many models and thus parts of the code and is influenced by a lot of parameters.

### Tasks
- Definition of requirements for creating/closing a rescue lane
- Addition of new TraCI commands for triggering such changes

What do you think? Is this useful? Is it even possible w.r.t. to defining clear requirements for creating a rescue lane?

**Comment by namdre** [comment]
The only effect that the bluelight device has on surrounding traffic w.r.t rescue lane creation is to set the preferred lateral alignment. I think you can use this directly without to much effort (`traci.vehicle.setLateralAlignment`).

The non-determinism that you notice was implemented as a feature: 

https://github.com/eclipse/sumo/blob/357e9ed3771050e13a8a1fdf24aae7e3a8f3f79d/src/microsim/devices/MSDevice_Bluelight.cpp#L211-L221

An easiert approach to your problem might be to make the probability thresholds configurable to achieve deterministic influence.

**Comment by heinovski** [comment]
The mentioned code suggest that also some other attributes are influenced (e.g., vehicle type, lane change mode). Thus, I am not sure whether modifying only the lateral alignment is sufficient.

However, having the probability for reacting configurable (i.e., as a parameter with sane defaults) and being able to dynamically overwrite the value via TraCI will indeed help me in my current project. Therefore, I like to sincerely request this feature :-)
-- 
Julian Heinovski, M.Sc.

Researcher and PhD Candidate
Telecommunication Networks (TKN)
TU Berlin, Germany

Einsteinufer 25, HFT-TA 334
10587 Berlin, Germany
https://www.tkn.tu-berlin.de/team/heinovski/

11 Jan 2023 17:15:57 Jakob Erdmann ***@***.***>:
