### ISSUE TITLE
feature request: proj.plain-geo could also be applied to the net.xml

### ISSUE THREAD

**Issue by ambuehll** [eclipse/sumo#12443]
`netconvert -s XXX.net.xml --plain-output-prefix plain --proj.plain-geo -o XXX_geo.net.xml`
transforms the coordinates back to WGS84 and creates edg.xml and nod.xml files with WGS84. 
Unfortunately, it keeps the net.xml in the original projection. 
The issue is that the **lane** shape attribute is not preserved in the edg.xml, and therefore it cannot be drawn from the edg.xml in a WGS84 system. 

-> a nice enhancement would be that if the net is rebuilt as `XXX_geo.net.xml `, the shape attribute get transformed as well. Or any other approach would be appreciated. 

Thanks
Lukas

**SUMO-version:** 1.15

**Comment by ambuehll** [comment]
@aminissn just told me about https://sumo.dlr.de/docs/Tools/Net.html#net2geojsonpy
partially solves this. I would still love to have all the lane attributes in the edg.xml itself. or a net.xml in WGS84 (which I understand is not a good idea for the sumo-gui).

**Comment by behrisch** [comment]
I think it is a better idea to write the lane shape to the plain xml (optionally). @ambuehll Which further lane attributes do you need?

**Comment by namdre** [comment]
Lanes and their attributes are written if they differ from the default values that could be derived from the edge.
An option that treats all lane attributes as if they were customized sounds most useful here:  **--plain-output.lanes BOOL**

**Comment by ambuehll** [comment]
Thank you. It would be great if it just wrote all attributes, e.g.:
` <lane id="-103531716#1_1" index="1" speed="13.89" length="50.58" width="3.60" shape="404.00,146.59 395.40,143.32 385.31,139.40 371.48,133.41">`
with the transformed shapes (WGS84).
Whatever is the simplest implementation :)

**Comment by aminissn** [comment]
> Lanes and their attributes are written if they differ from the default values that could be derived from the edge. An option that treats all lane attributes as if they were customized sounds most useful here: **--plain-output.lanes BOOL**

netconvert ignores all the lane attributes in the net.xml except the index when generating plain-output. Surprisingly, it keeps the user-defined parameters... I think an easy fix is to keep all attributes and as @ambuehll said, convert the shape of the lane into the expected projection as well.

**Comment by namdre** [comment]
> 

try setting a custom speed, shape or width value for one of the lanes and you will see what I meant.

**Comment by ambuehll** [comment]
Fair I see. I changed the speed for one lane to 14 instead of 13.89 BUT the shape is always different from the edge. 
See the following: 

```
    <edge id="-103531716#1" from="17288555" to="17288550" priority="10" type="highway.tertiary" spreadType="roadCenter" shape="414.27,148.57 396.04,141.64 385.99,137.73 367.37,129.67">
        <lane id="-103531716#1_0" index="0" speed="13.89" length="50.58" width="3.60" shape="402.72,149.96 394.11,146.68 383.94,142.73 370.05,136.72">
            <param key="origId" value="103531716"/>
        </lane>
        <lane id="-103531716#1_1" index="1" speed="14" length="50.58" width="3.60" shape="404.00,146.59 395.40,143.32 385.31,139.40 371.48,133.41">
            <param key="origId" value="103531716"/>
        </lane>
```

after netconvert 

```
    <edge id="-103531716#1" from="17288555" to="17288550" priority="10" type="highway.tertiary" numLanes="2" shape="8.544760,47.508609 8.544519,47.508546 8.544386,47.508510 8.544139,47.508437" width="3.60">
        <lane index="0" speed="13.89">
            <param key="origId" value="103531716"/>
        </lane>
        <lane index="1" speed="14.00">
            <param key="origId" value="103531716"/>
        </lane>
```

As you said, now it keeps the speed attribute. But the shapes were different from the beginning.

**Comment by namdre** [comment]
the default lane shapes are derived from the edge shape by shifting it sideways. For this reason they are not written even when they differ because it would be redundant (user-customized lanes shapes are written though).

**Comment by namdre** [comment]
Anwway,  you can now use the new option (-:

**Comment by ambuehll** [comment]
as always, wonderful! Many many thanks! :)
