### ISSUE TITLE
question for convert "edge.xml ,  node.xml , type.xml" to "net.xml"

### ISSUE THREAD

**Issue by SongKun2022** [eclipse/sumo#12454]
Add your issue description here.
Hello, I write some  files, such as node.xml, edge.xml and type.xml file. And I want to use netconvert to create a net.xml file. It's successful. However, the coordinates of the nodes that I have defined in node.xml file have changed in the new net.xml file. I don't know the reasons, could you give me some suggestions? Thank you very much.

SUMO-version:1.15

operating system: Windows

**Comment by namdre** [comment]
By default, coordinates are shifted to towards to coordinate origin to avoid numerical issues. To keep your original coordinates, set option **--offset.disable-normalization**

**Comment by SongKun2022** [comment]
Do I need to write codes to accomplish this function? Or are there any API to use?

**Comment by namdre** [comment]
`netconvert -s net.net.xml -p prefix`

**Comment by SongKun2022** [comment]
OK，thanks a lot.
