### ISSUE TITLE
question for lane change

### ISSUE THREAD

**Issue by SongKun2022** [eclipse/sumo#12461]
Add your issue description here.
Hello, I use "traci.vehicle.setStop()" to stop a red car at a position of a lane and prohibit another lane which is on the left of the lane 
that I said before changing right by setting "changeRight, authority". I don't understand that the following yellow cars stop before the red car and don't change lane like changing left, meanwhile, the type of all the yellow cars is default ,and I have never changing their type. There are some simulation pictures as follows:

![~NTF$3R_ENE@SL%V0Z)J1`0](https://user-images.githubusercontent.com/97946646/212551342-ada932ed-cbe8-4b38-b8f7-5558eb3889c1.png)

![`($}PGU_(5D8~9WPW2567CI](https://user-images.githubusercontent.com/97946646/212551414-69bfad6e-399b-48cc-b24d-8d817cc0951f.png)

![Y 65`5F}CI ({$C{XC{ML0D](https://user-images.githubusercontent.com/97946646/212551434-d2cca66b-668a-48ca-a22b-3e5e55c3560d.png)

SUMO-version:1.15

operating system:Windows

**Comment by namdre** [comment]
can you provide the input files (zipped)?

**Comment by SongKun2022** [comment]
Ok ,this file contains "route.xml" and "net.xml"
[inputFiles.zip](https://github.com/eclipse/sumo/files/10422496/inputFiles.zip)

**Comment by SongKun2022** [comment]
OK, sir, thank you. Could you give me some suggestions to use another alternative method to solve this problem? Or when you can fix this bug?

**Comment by namdre** [comment]
regression in version 1.9.0

**Comment by namdre** [comment]
@SongKun2022 the problem is fixed and a new version is schedule for release next week. You can get preview of today's fix tomorrow at https://sumo.dlr.de/docs/Downloads.php#nightly_snapshots

**Comment by SongKun2022** [comment]
OK, thank you very much.
