### ISSUE TITLE
No module named "validate" in San Pablo Dam 

### ISSUE THREAD

**Issue by mehmetnedimyavuz** [eclipse/sumo#12466]
Hello,
While I am running "runner.py" within the San Pablo Dam calibration tutorial, it gives an error: "No module named 'validate' ". Then using pip install validate, the error is like below:

Collecting validate
  Using cached validate-1.0.1.tar.gz (32 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\mehmetnedimyavuz\AppData\Local\Temp\pip-install-rboop8a3\validate_291ab5c71bda45bab14dfa7663eaf5e1\setup.py", line 13, in <module>
          from configobj import __version__ as VERSION
        File "C:\Users\mehmetnedimyavuz\AppData\Local\Temp\pip-install-rboop8a3\validate_291ab5c71bda45bab14dfa7663eaf5e1\configobj.py", line 1632
          except Exception, e:
                 ^^^^^^^^^^^^
      SyntaxError: multiple exception types must be parenthesized
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

I am using Python 3.11.0. It seems that problem is not directly related to SUMO. But I could not find a exact solution with google search. Thank you for help, regards.

**Comment by m-kro** [comment]
You can find the file [validate.py](https://github.com/eclipse/sumo/blob/main/tests/complex/tutorial/san_pablo_dam/validate.py) in the repository. As it seams, the tutorial files have been included in the release only until v.1.11. Sorry for the outdated documentation, we will change that.

**Comment by m-kro** [comment]
Related to #8774 .

**Comment by mehmetnedimyavuz** [comment]
I downloaded files using online test extraction. The downloaded zip file does not contain "validate.py" file. But I can see in the repository. I used test path as: "https://github.com/eclipse/sumo/tree/main/tests/complex/tutorial/san_pablo_dam".

**Comment by m-kro** [comment]
Yes, unfortunately the extraction script doesn't include other local python files currently, as it is of very limited use within our big range of tests / maybe has been neglected until now. We will discuss internally whether to extend the test extraction script.

You can download the missing file from Github without problems and use it to do the tutorial.

**Comment by mehmetnedimyavuz** [comment]
Thank you @m-kro

**Comment by m-kro** [comment]
Actually the file was just not set correctly in the test suite configuration. From now on it should be included when extracting the tutorial.
