### ISSUE TITLE
Getting Neighbor vehicles in TRAAS- Error: Answered with error to command 0xa4: Retrieval of neighboring vehicles needs bitset to specify mode.

### ISSUE THREAD

**Issue by mahyarsadeghi** [eclipse/sumo#12462]
Hi everyone. I'm trying to get the neighboring vehicles in sumo v 1.14 using TRAAS in java. Although I specify the mode, but I always get the error: 
Error: Answered with error to command 0xa4: Retrieval of neighboring vehicles needs bitset to specify mode.
How can I fix this? I also used sumo version 1.2 but no changes in the error. 
Here is the java code I'm using for it.

```

int mode=3;
Object[] array = new Object[]{mode};
SumoCommand c=new SumoCommand(Constants.CMD_GET_VEHICLE_VARIABLE, Constants.VAR_NEIGHBORS, vehID, array, 
                                Constants.RESPONSE_GET_VEHICLE_VARIABLE, Constants.TYPE_STRINGLIST);

                                        Object o =  connection.do_job_get(c);
                                        System.out.println("my neighbors are: " +o);
```

Im running this on windows and sumo v 1.14.

**Comment by namdre** [comment]
TRAAS is obsolete and does not support the full API.  It's replacement is Use libtraci / libsumo: https://sumo.dlr.de/docs/Libtraci.html#java
