### ISSUE TITLE
How to parse multiple route files via single route file in sumo config file

### ISSUE THREAD

**Issue by thilagaguru** [eclipse/sumo#12464]
I am trying to build multiple scenarios with multiple route files. 
For example there are more than 20 route file.
1.trafficflow.rou.xml, 
2.slowped.rou.xml,
3.slowveh.rou.xml 
and so on.

Requirement:

I would like to add or remove the route files based on the scenario requirement. 
But, I dont want to disturb the config file. 
What I know is, we can add multiple route file in config file like 

route-files value="trafficflow.rou.xml,slowped.rou.xml,slowveh.rou.xml "

What I would like to achieve is, 
In config file parse mother_route.rou.xml as input route file.
Edit the mother_route.rou.xml files by adding or deleting the required route files. 

How I am imagining is 

Config file

<configuration>

    <input>
        <net-file value="net.net.xml"/>
        <route-files value="mother_route.rou.xml"/>
        <additional-files value="additional.add.xml"/>						
    </input> 

</configuration>

mother_route.rou.xml : specify the required route files inside

Is there any sumo trick to help achieving this?

**Comment by namdre** [comment]
in your *mother* route file, include multiple lines of the form
```
 <include href="trafficflow.rou.xml"/>
 <include href="slowped.rou.xml"/>
 ...
```

**Comment by thilagaguru** [comment]
> ...

Thank you so much for the reply. 
In the config file, for input route I added mother route file as below. 

**Config file input**
<img width="306" alt="config file input" src="https://user-images.githubusercontent.com/36147578/212787677-705579e5-523b-4319-880d-1ea3e6a3f381.PNG">

Inside the mother route file, I added below two lines. 

**Mother route file**
<img width="261" alt="mother route file" src="https://user-images.githubusercontent.com/36147578/212787701-9d541cbc-bd81-4907-884b-b2b04f883346.PNG">

When I executed Sumo config file, I get the below error. 
It would be really helpful if you could help me with the below error message. 

**Error message**
Warning: Found root element 'include' in file 'D:\NICT\MM2ITS2\Plugins\SumoCoSimulation\Content\Python\Minato_old_routefiles\mother.rou.xml' (expected 'routes').
Error: comment or processing instruction expected
 In file 'D:\NICT\MM2ITS2\Plugins\SumoCoSimulation\Content\Python\Minato_old_routefiles\mother.rou.xml'
 At line/column 3/1.

Quitting (on error).
**Error file** 
<img width="560" alt="error" src="https://user-images.githubusercontent.com/36147578/212787670-73ef06ae-1750-4c5a-b746-61bc7f7fa330.PNG">


Thank you.

**Comment by namdre** [comment]
the mother file needs a root element:
```
<routes
   <include .../>
</routes>
```

**Comment by thilagaguru** [comment]
> the mother file needs a root element:
> 
> ```
> <routes
>    <include .../>
> </routes>
> ```

Thank you very much for the response. 
This works as expected.
