### ISSUE TITLE
Save edgeTypes call save "TLS as" instead save "edgeTypes as"

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#12467]
if (neteditOptions.getString("edgetypes-file").empty()) {
        return **onCmdSaveTLSProgramsAs**(obj, sel, ptr);

**Comment by namdre** [comment]
can you give a bit more detail on what is supposed to happen here?

**Comment by palvarezlopez** [comment]
Originally save edgeTypes and saveEdgeTypesAs use two different methods for saving. But after a refactoring of saving element functions, this ticket is not neede anymore.

But after checking code, I see the following bug:

long
GNEApplicationWindow::onCmdSaveEdgeTypes(FXObject* obj, FXSelector sel, void* ptr) {
    // get option container
    auto& neteditOptions = OptionsCont::getOptions();
    // Check if edgeType file was already set at start of netedit or with a previous save
    if (neteditOptions.getString("edgetypes-file").empty()) {
        return **onCmdSaveTLSProgramsAs**(obj, sel, ptr);
    } else {
