### ISSUE TITLE
tcpip::Socket::recvAndCheck @ recv: Bad address

### ISSUE THREAD

**Issue by mahyarsadeghi** [eclipse/sumo#12475]
When i'm using multi agent systems to retrieve vehicle variables , libtraci returns this error and then simulation step doesn't work at all. Agents running in a parallel way and they are all trying to access vehicles variables. How can I fix this error?

**Comment by behrisch** [comment]
TraCI is not thread safe. So if your agents issue TraCI commands from concurrent threads this is not going to work.

**Comment by mahyarsadeghi** [comment]
Thanks for the information. Is there a way that I can make it work?
If there's no way with libttaci, what about libsumo?

**Comment by mahyarsadeghi** [comment]
I was using TRAAS and everything was working fine with agents. The only reason i changed it to libttaci was because of getNeighbors nethod which didn't work in it.

**Comment by behrisch** [comment]
I added some locking to the traci implementation. Could you please retry (either by building a fresh version yourself or with the nightly build of tomorrow)?

**Comment by behrisch** [comment]
> Thanks for the information. Is there a way that I can make it work? If there's no way with libttaci, what about libsumo?

Performancewise it is definitely a good idea to use libsumo, but it is not protected against concurrent access as well. You may just have luck because the calls are much faster or because they only query things.

**Comment by mahyarsadeghi** [comment]
Thanks for the support. I'm going to test it again. Could you please give me the updated jar file link so I can test it out? I will report the results here.

**Comment by behrisch** [comment]
For Windows everything should be here: https://sumo.dlr.de/daily/sumo-win64-git.zip

**Comment by mahyarsadeghi** [comment]
Thanks. I tested the program with the new libtraci you shared it's link, and still I get the same error. More specifically, the error is in the form of the following: 
 #Error: received status response to command: 65 but expected: 2.
And it occurs when an agent tries to retrieve the the vehicle variables. Concurrently, it is possible to create vehicles, but I suppose the error arises when I try to retrieve values from simulation.
Dou you want me to give you a simpler version of my codes so you can try it out?

**Comment by behrisch** [comment]
yes, please

**Comment by mahyarsadeghi** [comment]
Ok. Here is the link in my google drive for the codes. Make sure you have jade and libtraci that you shared with me here. https://drive.google.com/file/d/135q3EsKjeVUWW7K9cyKd1GRe4VcfSs75/view?usp=sharing
You just run it and you will see it can add vehicles but each agent(which are vehicles) cant retrieve the values. 
In case of any questions please contact me.
Thank you very much.

**Comment by mahyarsadeghi** [comment]
Hi. Our research group was wondering if the sumo team could manage fixing the problem of the codes I have given you in this issue. The problem was that since I was using sumo with jade it was not thread-safe. That would be perfect if you give me any update regarding this.

**Comment by behrisch** [comment]
Your example is a little hard to reproduce. It contains hard coded paths, so it needs adaptions. I will have a look today but it would be great if you can set up a failing example which does not need a GUI and an external framework

**Comment by behrisch** [comment]
I always get  this, when starting:

    SEVERE: Cannot create agent RMA: Name-clash Agent RMA@172.17.0.1:1099/JADE already present in the platform

**Comment by behrisch** [comment]
I found some further concurrency issues with my own example and fixed them, so you may also try again (either by building yourself or waiting for the nightly build of tomorrow)

**Comment by mahyarsadeghi** [comment]
Awesome. Tomorrow I'm gonna test it using the link you gave me:
https://sumo.dlr.de/daily/sumo-win64-git.zip
I will update you, if the package workd in our example or not.

**Comment by mahyarsadeghi** [comment]
Hi. I tested it now using the new build(I'm not sure if tonight I can have access to new build or it is already updated), I have the following errors:
1. #Error: received status response to command: 0 but expected: 2
2.  #Error: received status response to command: 0 but expected: 164
3. tcpip::Socket::recvAndCheck @ recv: Bad address 
which are similar to previous ones.
New libtraci.jar file I'm using is version 1.17.0 snapshot. The sumo version is 1.14 .
Can you share with me the codes you tested based on my program?

**Comment by mahyarsadeghi** [comment]
Ok. I also updated my sumo from 1.14 to 1.16, Everything works perfectly. Thanks for the collaboration, we appreciate the effort.
