### ISSUE TITLE
cannot load network in sumo without saving sumocfg

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#12485]
the following workflow must still be supported:
1. load a network (i.e. from the command line)
2. press ctrl+t  ->see network in sumo-gui

Currently, this prompts for saving a sumocfg and slows the user down.

If no demand or infrastructure objects are present, the network should be loaded directly.

**Comment by palvarezlopez** [comment]
@namdre what is the purpose of edit a network without an associated SUMOConfig?

I have the following proposal: automatic define the *.sumocfg file (for example, sumo.sumocfg or <networname>.sumocfg) whe Ctrl+T is pressed AND wasn't previously defined.

**Comment by namdre** [comment]
- faster reload speed
- looking at a "raw" network instead of a computed one is sometimes useful
