### ISSUE TITLE
road network connection state clarification

### ISSUE THREAD

**Issue by JulianCzymmeck** [eclipse/sumo#12490]
I'm trying to create a dictionary containing all incoming lanes to each unprioritized crossing in the network. But finding out exactly which crossing is unprioritized and which isn't is proving to be quite difficult and the documentation on that topic under [Road Networks Connection state](https://sumo.dlr.de/docs/Networks/SUMO_Road_Networks.html) doesn't help.
My current approach is to first create a dictionary containing all internal foes for each crossing:
```
    for lane in traci.lane.getIDList():
        # filter for crossings
        if ("c" in lane) and ("cluster" not in lane):
            internal_foes_dict[lane] = traci.lane.getInternalFoes(lane)
```
and then look at the links of each lane, comparing them to the entries in the dictionary:
```
    for lane in traci.lane.getIDList():
        # for each lane get all successors
        for successor_tuple in traci.lane.getLinks(lane):
            internal_successor = successor_tuple[4]
            # TODO: filter  for unprioritized crossings only (information in successor_tuple[5])
            if internal_successor != '':
                # look if successor is an internal foe of a crossing
                for crossing in internal_foes_dict:
                    if internal_successor in internal_foes_dict.get(crossing):
                        # add original lane to value set of the crossing
                        cross_dict.setdefault(crossing, set()).add(lane)
```
I'm assuming that the relevant information is in the state variable of `traci.lane.getLinks(lane)`, but the documentation doesn't make clear what values I'm looking for. Upon printing out `successor_tuple[5]` for each of my connections, I've come across almost all existing states. The documentation I found is: `("-" = dead end, "=" = equal, "m" = minor link, "M" = major link, traffic light only: "O" = controller off, "o" = yellow flashing, "y" = yellow minor link, "Y" = yellow major link, "r" = red, "g" = green minor, "G" green major)`. I'm especially confused regarding what the difference between a major and minor link is.
Manually examining a couple of lanes suggests that the state I am looking for is "M", but I want to be certain.

**Comment by m-kro** [comment]
Major link means it has priority over others (or at least does not care to yield), while minor links do yield. However I would suggest to have a look at [sumolib ](https://sumo.dlr.de/docs/Tools/Sumolib.html) (especially sumolib.net) as your request uses mostly static data (unless you plan to close lanes during your simulation).
There you can read the network topology and attributes associated with the network elements:

- load the network as described in the doc page (use additional options like withPedestrianConnections to load all necessary data)
- loop through nodes and their connections, filter for crossings / alternatively check edge.getCrossings() and access the relevant Connection item
- use node.areFoes with the link indices of crossing and connections

**Comment by m-kro** [comment]
Forget about "O" state, as this is still related to traffic lights. You'd need to look for a "crossing" connection with "m" state or a connection from the crossed street with "M" to infer there is an unprioritised crossing.
