### ISSUE TITLE
How to add reverse lane next to already existing lane

### ISSUE THREAD

**Issue by thilagaguru** [eclipse/sumo#12492]
Operating system : Windows 10
Sumo version : 1.12.0

I am working with a big network file. 
In few places I have a one way pedestrian lane attached to the edge. 
Due to the scenario's requirement, I want the pedestrian to walk both directions on the same side. 
So I would like to add a reverse pedestrian lane next to the already existing pedestrian lane.

**What I have now:**
![pedlane1](https://user-images.githubusercontent.com/36147578/213336504-e8d45f22-3810-4d9d-bc1f-698d50309f36.PNG)

**What I would like to achieve**
So I duplicated the already existing lane. But I do not know, how to reverse the direction of the newly added lane. 
![pedlane3](https://user-images.githubusercontent.com/36147578/213336647-c1c113d8-ef49-4d76-a605-626cc933a39c.PNG)

I would like to know, Is there any  options on the netedit to reverse the direction of the lane. 
It would be very helpful if the query is being answered. 
Thank you,
Thilaga.

**Comment by m-kro** [comment]
There is no need to add a reverse lane as pedestrians can use both directions by default. Just make your sidewalk more wide if you feel this is necessary. Only if you want pedestrians to walk on both sides of a one-way street, you actually have to create a reverse edge for that (see [docs](https://sumo.dlr.de/docs/Simulation/Pedestrians.html#generating_a_network_with_sidewalks)).
