### ISSUE TITLE
loading networks in netedit fails (presumably, by crashing the loadthread)

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#12494]
as a corollary, lauching netedit from within sumo-gui fails to load the network

**Comment by namdre** [comment]
broken in 76fdb8690e18ec2e48f8f49cd7db84c7667fd678 (GUI modified from another thread). As explained by Jeroen this is forbidden:
  **"Neither Windows nor Linux can safely access the GUI from more than two threads."**.

**Comment by palvarezlopez** [comment]
This brokes loading of networks in SUMO
