### ISSUE TITLE
How to simulate a barrier at a road?

### ISSUE THREAD

**Issue by SongKun2023** [eclipse/sumo#12504]
Add your issue description here.
Hello, according to some real situations, I want to set a barrier at a lane or edge in my simulation. Are there some methods in sumo to make it? I can not find.  Could you give me some advice? Thanks a lot.

SUMO-version:1.15

operating system:Windows

**Comment by m-kro** [comment]
You can use any of the following to forbid access to a lane or edge temporarily or at least obtain a change in the traffic flow:

- traffic light
- low speed limit (can be [dynamic](https://sumo.dlr.de/docs/Simulation/Variable_Speed_Signs.html))
- close edge with [rerouter ](https://sumo.dlr.de/docs/Simulation/Rerouter.html#closing_a_street) / in the GUI / via [TraCI](https://sumo.dlr.de/docs/TraCI/Change_Lane_State.html) (setAllowed)
- place vehicles on stops to block the vehicles upstream (can be done with TraCI or defined beforehand in additional files)

**Comment by SongKun2023** [comment]
OK. Thank you for your respones.
