### ISSUE TITLE
PT-routes: split edges at bus/train-stops

### ISSUE THREAD

**Issue by MHeinrichs** [eclipse/sumo#12519]
To visualize traffic and calculated the link-related occupancy it is necessary to have separate edges between all stops of a pt-route.

**Comment by namdre** [comment]
Presumably this is about railways where a single edge has multiple stops.
Assuming an edge that has 3 Stops, how would you like to split it?

```
      S1                  S2                 S3
    -------------------------------------------------
                               E
```

a) Split in three parts:

```
      S1                  S2                 S3
   -------------   ----------------  ------------------
        E1                  E2                E3
```

In this case, you would have traffic between S1-S2 and S2-S3 be counted on E2


b) Split in five parts (each stop gets a short part):

```
      S1                  S2                 S3
   -------   ---------  ------  --------  -------
      E1       E2        E3       E4     E5
```

In this case the locations of the edges would better fit with the traffic locations

**Comment by MHeinrichs** [comment]
I would prefer option b to analyze both: usage of stops (odd edges in your example) and tracks (even edges), if the extra data in SUMO is acceptable.



Von: Jakob Erdmann ***@***.***>
Gesendet: Dienstag, 31. Januar 2023 13:30
An: eclipse/sumo ***@***.***>
Cc: Heinrichs, Matthias ***@***.***>; Author ***@***.***>
Betreff: Re: [eclipse/sumo] PT-routes: split edges at bus/train-stops (Issue #12519)



Presumably this is about railways where a single edge has multiple stops.
Assuming an edge that has 3 Stops, how would you like to split it?

      S1                  S2                 S3
    -------------------------------------------------
                               E

a) Split in three parts:

      S1                  S2                 S3
   -------------   ----------------  ------------------
        E1                  E2                E3

In this case, you would have traffic between S1-S2 and S2-S3 be counted on E2

b) Split in five parts (each stop gets a short part):

      S1                  S2                 S3
   -------   ---------  ------  --------  -------
      E1       E2        E3       E4     E5

In this case the locations of the edges would better fit with the traffic locations

**Comment by namdre** [comment]
- should give a helpful error message when no stop files are given as additional arguments
- would be nice to warn if the stop files do not contain the default stop type (who expects trainStop?)
