### ISSUE TITLE
Electric Vehicle Model: Internal moment of inertia power calculated incorrectly

### ISSUE THREAD

**Issue by abrac** [eclipse/sumo#12513]
Hi there. As [stated in the docs](https://sumo.dlr.de/docs/Models/Electric.html), there is a model parameter called `internalMomentOfInertia`. This parameter, _I_, has units: kg·m². The correct way of calculating the power required for generating rotational inertia is: 

*P* = [ ½ * *I*/*r_wheel*^2 * (*v*^2 - *v_old*^2) ] / *Δt*

According to [HelpersEnergy.cpp#L65](https://github.com/eclipse/sumo/blob/b0d06669911fbbfbabf7ea7e9c614b2a4d856119/src/utils/emissions/HelpersEnergy.cpp#L65), it is calculated differently... Instead of the factor *I*/*r_wheel*^2, it simply uses *I*. 

On the other hand, the new MMPEVEM model calculates it correctly, as show in [HelpersMMPEVEM.cpp#L83](https://github.com/eclipse/sumo/blob/b0d06669911fbbfbabf7ea7e9c614b2a4d856119/src/utils/emissions/HelpersMMPEVEM.cpp#L83).

According to my calculations, SUMO's internalMomentOfInertia default, seems incorrect... The default is 0.01 kg·m². On the other hand, the values in the [example configurations](https://github.com/eclipse/sumo/tree/2ec6693914ccd2644d56fee9170ab0fb51631ea3/data/emissions/MMPEVEM) of MMPEVEM are in the magnitude of 12--16 kg·m², which are much closer to my calculations...

Something seems to be wrong somewhere with the modeling.

**SUMO-version:** 1.15

**operating system:** N/A

**Comment by namdre** [comment]
Thank you for looking at this in detail!

1. The low value of 0.01 comes via #5505 and I'm in doubt that the cited reference is correct since there are no numbers in this publication.  Our nightly tests (presumably for electric buses) uses a value of 30. 
2. Looking at  [HelpersMMPEVEM.cpp#L83](https://github.com/eclipse/sumo/blob/b0d06669911fbbfbabf7ea7e9c614b2a4d856119/src/utils/emissions/HelpersMMPEVEM.cpp#L83), I cannot find the part corresponding to (v^2 - v_old^2) / Δt

**Comment by m-kro** [comment]
@namdre wouldn't that be `a` (see input parameters of calcPowerConsumption())?

**Comment by abrac** [comment]
I assume that it is part of `a` as @m-kro has said. However, it may be important to note that MMPEVEM uses a slightly different approach. They calculate P using the following equation:

*P* = *F v* = *T*/*r_wheel v* = (*α I*)/*r_wheel v* = (*a I*)/*r_wheel*² *v*

**Comment by abrac** [comment]
The [publication](Accurate physics-based modeling of electric vehicle energy consumption in the SUMO traffic microsimulator) ([Open access version](https://www2.tkn.tu-berlin.de/bib/koch2021accurate/koch2021accurate.pdf)) from the developers of the MMPEVEM model does report their model parameter of 12.5 kg·m². So maybe the SUMO default could be changed to that. In addition, if the existing SUMO EV model needs to have its inertia divided by *r_wheel*² in [HelpersEnergy.cpp#L65](https://github.com/eclipse/sumo/blob/b0d06669911fbbfbabf7ea7e9c614b2a4d856119/src/utils/emissions/HelpersEnergy.cpp#L65). I think if these two changes are implemented, the two models should output a similar result...

**Comment by kevbad** [comment]
Hello everyone,

in [HelpersMMPEVEM.cpp](https://github.com/eclipse/sumo/blob/main/src/utils/emissions/HelpersMMPEVEM.cpp#L83), we calculate the mass factor of the vehicle which allows us to take rotating parts into account when using formulas for translational movement. Please note that we also divide by the vehicle mass and not just by the square of the wheel’s radius.
I agree with @abrac that this isn’t implemented correctly in [HelpersEnergy.cpp](https://github.com/eclipse/sumo/blob/main/src/utils/emissions/HelpersEnergy.cpp#L65). Either the authors forgot to divide by m∙r² or they meant to multiply by the angular velocity and forgot to convert `v`.

**Comment by behrisch** [comment]
To add a little bit to the confusion, the [ElectricHybrid docs](https://sumo.dlr.de/docs/Models/ElectricHybrid.html) state that they use the `internalMomentOfInertia` as a mass and not as a moment.

**Comment by abrac** [comment]
> To add a little bit to the confusion, the [ElectricHybrid docs](https://sumo.dlr.de/docs/Models/ElectricHybrid.html) state that they use the `internalMomentOfInertia` as a mass and not as a moment.

Indeed. The authors of ElecHybrid obviously noticed that HelpersEnergy does not divide _I_ by _r_^2. Therefore they redefine _I_ as the _"equivalent mass"_ that would compensate for the inertia. This equivalent mass is ordinarily calculated by dividing _I_ by _r_^2. But since, _I_ is not divided by _r_^2, they just redefined _I_ as the equivalent mass.

**Comment by m-kro** [comment]
After consulting the [thesis ](https://doi.org/10.24355/dbbs.084-201707181031) of the model author `Kurczveil, Tamás (2017): Optimierung einer induktiven Energieversorgungsinfrastruktur für den urbanen Straßenverkehr.` (p. 95), it seems the parameter ist just wrongly named "internal moment of inertia" and the default value & unit is questionable, too. From the publication, it should have read something like "equivalent mass for internal rotating elements".

**Comment by m-kro** [comment]
Closing here due to the upcoming release. The doc update now reflects more the original model definition and the physical relations. Discussions about the default values of battery device etc. continue in #13422 .

**Comment by behrisch** [comment]
I changed the name of the param to "rotatingMass" now for the Electric and Hybrid models and changed the default to 40 (which is the value PHEMlight uses for its battery vehicle). @abrac @kevbad If you want to change something please speak up before the release is out in two weeks.
