### ISSUE TITLE
PT: starting / ending train/busStop is not mentioned in the routes.xml

### ISSUE THREAD

**Issue by MHeinrichs** [eclipse/sumo#12521]
In the vehroutes_oneshot_meso.rou.xml a ride mentions only the exiting trainStop / busStop. 

Please mention the entering stop aswell.

**Comment by namdre** [comment]
the entering stop is always the exiting stop of the previous entry of the person plan (if one exists).

**Comment by behrisch** [comment]
@MHeinrichs Is this sufficient? If not please add another comment with details and we will reopen
