### ISSUE TITLE
How to obtain width value from a converted OpenDrive to SUMO network file?

### ISSUE THREAD

**Issue by msnir009** [eclipse/sumo#12524]
Issue/Question:
I am trying to obtain the road width value for a specific edge in the network file but the width value is currently shown as "default". Is there any way to obtain this value from a converted opendrive file?

**SUMO-version:**
Netedit version: 1.15.0
**operating system:**
Windows 10

**Comment by m-kro** [comment]
You can access the lane widths in sumo-gui through the context menu: right click on a lane and select "Show Parameter". Default width for a lane seems to be 3.20m.

**Comment by msnir009** [comment]
found it, thank you very much.
