### ISSUE TITLE
Generating all possible routes that start and end at the fringes of the network using randomtrips.py

### ISSUE THREAD

**Issue by MohamadReza-Haghani** [eclipse/sumo#12538]
Hi,

I intend to use randomtrips.py to generate all possible routes that start and end at the fringes of the network using this:
`python randomTrips.py -n map.net.xml -r sampleRoutes.rou.xml --fringe-factor 1000`
By setting the "--fringe-factor" to 1000, all the routes start and end at the fringes of the network. However, some possible routes are missing. I tried to increase the end time by setting "-e" to 36000 so it includes more routes, but it is still missing the same routes as before. I was wondering how I can make a route file including all possible routes starting and ending at the fringes of the network.

Best,
Reza.

**Comment by MohamadReza-Haghani** [comment]
I also have a minor question. Recently, I had a problem opening SUMO documentation [https://sumo.dlr.de/docs/index.html]. I was wondering whether there is a problem with your server or with my internet connection.

Thanks,
Reza.

**Comment by namdre** [comment]
If the same routes are missing regardless of the number of generated routes, this suggests that some of the edges you would like to see are not considered as "fringe". a possible solution is the following
1. process your network with `netconvert -s old.net.xml -o new.net.xml --fringe.guess
2. manually check / correct the 'fringe' attribute of the junctions in netedit
3. run randomTrips with option --fringe-junctions

**Comment by MohamadReza-Haghani** [comment]
Thank you for your response. When I run randomTrips with option --fringe-junctions, I get this error:
randomTrips.py: error: unrecognized arguments: --fringe-junctions

**Comment by namdre** [comment]
1. The option **--fringe-junctions** is only available in version 1.12.0 or later.
2. You may set options **--vehicle-class CLASSNAME**  to ensure that that generated traffic has the respective class and can make use of those lanes
