### ISSUE TITLE
Open the simulation, the example that comes with the system, there is a problem

### ISSUE THREAD

**Issue by jianki1314** [eclipse/sumo#12536]
Warning: Cannot read local schema 'D:\sumo-win64-1.15.0/data/xsd/additional_file.xsd'.
Warning: Cannot read local schema 'D:\sumo-win64-1.15.0/data/xsd/routes_file.xsd'.
Warning: Cannot read local schema 'D:\sumo-win64-1.15.0/data/xsd/net_file.xsd'.
Loading net-file from 'D:\sumo-win64-1.15.0\sumo-1.15.0\docs\examples\sumo\busses\net.net.xml' ... done (7ms).
Loading additional-files from 'D:\sumo-win64-1.15.0\sumo-1.15.0\docs\examples\sumo\busses\input_additional.add.xml' ... 
Warning: Cannot read local schema 'D:\sumo-win64-1.15.0/data/xsd/additional_file.xsd', XML validation will fail.
Error: invalid document structure
 In file 'D:\sumo-win64-1.15.0\sumo-1.15.0\docs\examples\sumo\busses\input_additional.add.xml'
 At line/column 2/1.

Loading of additional-files failed.
Quitting (on error).

**Comment by jianki1314** [comment]
Does anyone know, thank you

**Comment by behrisch** [comment]
Please double check that you have set SUMO_HOME correctly. It should probably point to `D:\sumo-win64-1.15.0\sumo-1.15.0` and not `D:\sumo-win64-1.15.0`
