### ISSUE TITLE
Question for using "Road Segment Refining"

### ISSUE THREAD

**Issue by SongKun2023** [eclipse/sumo#12532]
Add your issue description here.
Hello, I use "--plain-output-prefix" in netconvert to split a net.xml into plain xml, like nodes, edges, types and connections xml. And then, I merge these flies into a net.xml, it's successful. But I attempt adding a subelement of <split> in one edge in edg.xml and using netconvert to merge them, a error will happen. Could you tell me the reasons? Thank you. The error and some screenshots are as follows:

![0(L9@LCS}}32{}A$HOY3%X2](https://user-images.githubusercontent.com/97946646/214816471-0822ae8a-38ab-4001-84bb-b1c51ae1889b.png)

![JWYO8YO 3I`5)U7KLK1SDM8](https://user-images.githubusercontent.com/97946646/214816537-ccaa6fd1-ba68-49f9-8498-5ddf07de6188.png)

![XM~SCOQ (%K9~5_TCUZV}MJ](https://user-images.githubusercontent.com/97946646/214816573-91b93060-3a86-4046-b47d-34aba3774c36.png)

![IWRI6PIR{21F 0E27TVB6KR](https://user-images.githubusercontent.com/97946646/214816676-acb2cc2e-cff6-4e5c-82bb-c17a4dd47a67.png)

operating system:Windows

**Comment by m-kro** [comment]
Could you attach your plain XML files in a zip archive to this issue?

**Comment by namdre** [comment]
After splitting an edge with `<split>` the second part will get a newly generated edgeID and thus any connections defined as outgoing from the original edgeID are not usable anymore. You can use split attributes `idBefore` and `idAfter` to ensure that the second part keeps the old id and the first part gets renamed. However, this would be a problem for all connections that are defined as targeting the original edgeID.
If this is the case for you, the best work-around is to apply the splits in a secondary netconvert step without loading any connections (in this case, existing connections will be adapted automatically for the split edge).
(or modify the connection definitions to employ the new edge ids).

**Comment by SongKun2023** [comment]
If I apply the splits in a secondary netconvert step without loading any connections, are the generated connections that are adapted automatically for the split edge different from original connections?

**Comment by namdre** [comment]
no. The connections should remain exactly the same, only that they start from the second part of the split edge.

**Comment by SongKun2023** [comment]
OK，that's great, thanks for your response.
