### ISSUE TITLE
invalid saved-status for meanData

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#12542]
Problem A
1.  load net
2.  create meandata
3. qui
4. t  -> **no saving dialog comes up**

Problem B
1.  load net
2.  create meandata
3. modify meandata attribute
5. quit
6. **dialog for saving edgeData comes up** -> save 
-> **empty edgeData is saved, netedit quits  and meanData is lost**

Problem C
1.  load net
2.  create meandata
3. modify meanData attribute
4. save meanData to File
5. quit
6. **dialog for saving edgeData comes up** -> abort
7. **dialog for saving meanData comes up**  (even though meanData was saved)

**Comment by palvarezlopez** [comment]
The problem was caused due originally MeanDatas were Data Elements
