### ISSUE TITLE
Can't access sumo documentation

### ISSUE THREAD

**Issue by lola-notraffic** [eclipse/sumo#12546]
I can't access sumo documentation. Getting the following error:
![image](https://user-images.githubusercontent.com/95179338/215499308-d20d91b3-9803-46ed-a737-1bfeaa5b15bb.png)
Thank you in advance.

**SUMO-version:*1.13.0*

**operating system:*ubuntu 20.04*

**Comment by palvarezlopez** [comment]
Our server is undergoing maintenance and expected to be back online tomorrow

**Comment by namdre** [comment]
backup documentation is at  https://sumo.sourceforge.net/docs/
downloads at https://sourceforge.net/projects/sumo/files/sumo/

**Comment by namdre** [comment]
Latest nightly build of SUMO can be obtained via https://test.pypi.org/project/eclipse-sumo/

**Comment by m-kro** [comment]
Documentation is accesible again at [https://sumo.dlr.de/docs/](https://sumo.dlr.de/docs/)

**Comment by robertalms** [comment]
@m-kro wiki is down again

**Comment by m-kro** [comment]
Online again
