### ISSUE TITLE
How can vehicle turn might be retrieved?

### ISSUE THREAD

**Issue by lola-notraffic** [eclipse/sumo#12548]
I want to retrieve vehicle turn value:  right, left, straight.
From what I found there is an angle that can be retrieved: but it may vary from various intersections positions and not be the same for same turn.
Another option was found is vehicle signalling and blinkers. But even  if there is  a case of vehicle going straight (it might blink left to change lane inside the intersection). 
Is there any additional option?
Thank you in advance.

**SUMO-version:*1.13.0*
**operating system:*ubuntu 20.04*

**Comment by namdre** [comment]
1. you can retrieve the upcoming edges of the vehicle with `getRoute` and `getRouteIndex`
2. for each edge you can get the laneID as EDGEID_INDEX (number of lanes via `edge.getLaneNumber`)
3. for each lane you can retrieve the connections and their directions via `lane.getLinks`

Based on the known route you can figure out which of the connections/links the vehicle will use and then you have the turning directions along the route.
