### ISSUE TITLE
SUMO's documentation website is not working

### ISSUE THREAD

**Issue by ricardofdc** [eclipse/sumo#12547]
SUMO's documentation website is not working (https://sumo.dlr.de/)

The website has been down since 29th January.

Error message:
Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

**Comment by vijay-jaisankar** [comment]
The website is down and should be back up soon


Ref: https://github.com/eclipse/sumo/issues/12546

**Comment by rockkult** [comment]
There is a problem with your website:
**Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.**

**Comment by vijay-jaisankar** [comment]
> There is a problem with your website: **Service Unavailable The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.**

Yes, as mentioned in #12546, we are supposed to use https://sumo.sourceforge.net/docs/ as a back-up.

**Comment by namdre** [comment]
#12546 also contains links to alternative release/nightly-version downloads
