### ISSUE TITLE
Vtype parameters cannot be defined as 0

### ISSUE THREAD

**Issue by stepeos** [eclipse/sumo#12557]
When I try to define the following vtype:
```
<vType id="follower3" speedFactor="1.2" minGap="1.137171479839561" accel="1.104540519756387" decel="3.366666383170067" emergencyDecel="10" startupDelay="0.570474864107661" tau="0.04" delta="2.8535389135293916" stepping="0.25" tpreview="2.8239930727558527" tPersDrive="2.6546726300929278" tPersEstimate="7.92625730418846" treaction="0.34182299403740535" ccoolness="0.6029547618186811" sigmaleader="0.0" sigmagap="0.0" sigmaerror="0.0" jerkmax="1.2518327981828308" epsilonacc="2.5670125399439625" taccmax="4.05356546860394" Mflatness="1.351369694810589" Mbegin="1.39948990868375" carFollowModel="EIDM" />
```

Then upon loading the simulation config, I get the Error `Error: value '0.0' must be greater than or equal to minExclusive facet value '0'`

I can resovle the issue by setting sigmaleader, sigmaerror, sigmagap and other parameters which were 0.0 to 0.001 for every vtype defined in the routes config.
I know it does not make sense to have acc=0, but I image the **error message** to be more precise.

*If possible, upload an example that shows your problem.*
[calibration_routes.rou.txt](https://github.com/eclipse/sumo/files/10551077/calibration_routes.rou.txt)
[calibration_network.txt](https://github.com/eclipse/sumo/files/10551079/calibration_network.txt)
[calibration_config.sumocfg.txt](https://github.com/eclipse/sumo/files/10551081/calibration_config.sumocfg.txt)
**operating system:**

OS: Ubuntu 22.04.1 LTS
**SUMO-version:**
1.15.0

**Log**
Error: value '0.0' must be greater than or equal to minExclusive facet value '0'
At line/column 4/613.

**Comment by m-kro** [comment]
The error message above is due to XML validation. If you set the sigma* attributes to "0", the validation will go through.
