### ISSUE TITLE
tif view in sumo-gui and netedit

### ISSUE THREAD

**Issue by mfsen** [eclipse/sumo#12554]
Hi is it possible to open tif file in both netedit and sumo-gui. In sumo-gui we can able to see tif file but it is not mapped according to tif coordinate. On the other hand i didnt able to tif in netedit a all. 

https://sumo.dlr.de/docs/sumo-gui.html#showing_background_images

i did it according to this link.

**Comment by mfsen** [comment]
hi I have already did that i can upload tif file to sumo-gui however i cannot upload it to netedit

**Comment by m-kro** [comment]
I tried it and was able to load a tif file in netedit. Please check that settings for image center and size take meaningful values (an image with a size of 0 will not be drawn)...
