### ISSUE TITLE
How to get edge ID from latitude longitude coordinate

### ISSUE THREAD

**Issue by radhityavirya** [eclipse/sumo#12559]
I have a dataset consist of 730 latitude and longitude coordinate, when I want to make code for person there is "ride from = <edge id> to = <edge id>", so how to get the edge ID in Netedit with latitude and longitude coordinate automatically? Thankyou.

**Comment by namdre** [comment]
you can you fromLonLat, toLonLat and viaLonLat directly as input: https://sumo.dlr.de/docs/Demand/Shortest_or_Optimal_Path_Routing.html#mapmatching

**Comment by radhityavirya** [comment]
Ok thankyou i'll try it.
-------- Original message --------From: Jakob Erdmann ***@***.***> Date: 2/1/23  2:25 PM  (GMT+07:00) To: eclipse/sumo ***@***.***> Cc: radhityavirya ***@***.***>, Author ***@***.***> Subject: Re: [eclipse/sumo] How to get edge ID from latitude longitude coordinate (Issue #12559) 
you can you fromLonLat, toLonLat and viaLonLat directly as input: https://sumo.dlr.de/docs/Demand/Shortest_or_Optimal_Path_Routing.html#mapmatching

**Comment by radhityavirya** [comment]
Sorry, is this applied for taxi ride sharing too?

**Comment by radhityavirya** [comment]
Hello,
I want to ask again about fromLonLat and toLonLat.
When I opened the SUMO-GUI I got a warning like this "Error: attribute
'fromLonLat' is not declared for element 'ride' ". Is it normal or is the
code not working for a person to ride?
Thankyou for helping me.

**Comment by namdre** [comment]
1. it's not working for `<ride>` (hence my advice to use a personTrip)
2. lonLat attributes are not working with sumo/sumo-gui at the moment, You need to use this with duarouter (and can the load the output files in sumo)

**Comment by radhityavirya** [comment]
Hello, I already use duarouter and the results show that the person will
either "ride" or "walk", can you help me if I want all of the result is the
person must be "ride" with taxi lines? Thank you for any help you can offer.

**Comment by namdre** [comment]
define `<personTrip modes="taxi" .../>`
