### ISSUE TITLE
About "getLastStep*", "getInterval*", "getLastInterval*" in Lane Area Detector Value Retrieval

### ISSUE THREAD

**Issue by JamesPsh** [eclipse/sumo#12558]
https://sumo.dlr.de/docs/TraCI/Lane_Area_Detector_Value_Retrieval.html

I would like to know more details about "getLastStep*", "getInterval*", "getLastInterval*".
Could I ask what difference the above function makes?

Thank you.

**Comment by m-kro** [comment]
Lane Area Detectors aggregate/accumulate values using time intervals (see their XML definition in the [docs](https://sumo.dlr.de/docs/Simulation/Output/Lanearea_Detectors_%28E2%29.html#attributes)). You can access the aggregated values with "getInterval*" (running interval) and "getLastInterval*" (the last completed interval). Additionally, the current value during last time step can be read with "getLastStep*".
