### ISSUE TITLE
add vehicle.getNextLinks

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#12551]
similar to getNextTLS but for all links along the route. Should return a list of TraCIConnections.

simplify retrieval (see #12548 )

**Comment by yunlishao** [comment]
Hi there, I tested this new feature with both v1.17 and v1.18, the getNextLinks command works fine for Python TraCI, but I have the following error for C++ TraCI and libsumo:
![image](https://github.com/eclipse/sumo/assets/73845081/5d25c6f5-0fcf-4cdf-95bb-3c80b308a767)

I am using a very simple C++ code for testing:
```cpp
#include <iostream>
#include <libsumo/libtraci.h>
#include <windows.h>
using namespace std;

using namespace libtraci;

int main()
{
	string trafficIp = "127.0.0.1";
	int trafficPort = 1337;

	Simulation::init(trafficPort, 60, trafficIp);
	Simulation::setOrder(1);

	while (1) {
		try {
			Simulation::step();

			vector <string> vehIdList = Vehicle::getIDList();
			for (int i = 0; i < vehIdList.size(); i++) {
				string vehId = vehIdList[i];
				vector <string> edgeList = Vehicle::getRoute(vehId);
				vector <libsumo::TraCIConnection> nextLinkList = Vehicle::getNextLinks(vehId);

				int a = 1;
			}
		}
		catch (const std::exception& e) {
			std::cout << e.what();
			return -1;
	       }
	}

    return 0;
}
```

**Comment by m-kro** [comment]
@yunlishao There was a leftover copy paste fragment in the libtraci code causing the problem. Please try again with a fresh build of SUMO (using the Github source).

**Comment by yunlishao** [comment]
@m-kro sorry for my late reply. Thanks for your comment and it seems to fix the issue. Wondering will this be put into a SUMO release version anytime soon?

**Comment by m-kro** [comment]
It will be included in the upcoming release in October this year.
