### ISSUE TITLE
SUMO server (https://sumo.dlr.de/docs) is down - netconvert not working

### ISSUE THREAD

**Issue by krivi12** [eclipse/sumo#12561]
SUMO server (https://sumo.dlr.de/docs) is down at the moment.
With SUMO server down ./sumo/bin/netconvert doesn't work.
Which relation does a local build SUMO especially the tool netconvert has to the SUMO server? 

Sumo version: v1_13_0
OS: Debian 10

**Comment by m-kro** [comment]
The only thing I can think of is XML validation, where some schema URL points to the named domain. You can disable XML validation by adding the command line parameter `-X never`.

**Comment by namdre** [comment]
Also, as long as you define SUMO_HOME the local installation should use local schema files and never try to look up things online.

**Comment by vijay-jaisankar** [comment]
https://sumo.dlr.de/docs/ seems to be up now.
