### ISSUE TITLE
question：About Coordinate Conversion

### ISSUE THREAD

**Issue by qqkkwan** [eclipse/sumo#12565]
Hello,
After i use netcovnert to convert osm to opendrive, i have a question for coordinate conversion. Here's what I did:
1. download a osm map: map.osm
2. use netconvert to convert osm to opendrive: `netconvert --osm-files map.osm --opendrive-output map.xodr`
3. I found `<![CDATA[
 +proj=utm +zone=32 +ellps=WGS84 +datum=WGS84 +units=m +no_defs
]]>` and `<offset x="-457511.90" y="-5428693.76" z="0.00" hdg="0"/>` in map.xodr
4. If I select a coordinate on map.osm, how can I generate a world coordinate system and match the converted map.xodr? 
If there is a case with python, I would be grateful.

**Comment by namdre** [comment]
- you can use a projection library (i.e. pyproj) and use the value of `+proj=utm +zone=32 +ellps=WGS84 +datum=WGS84 +units=m +no_defs` to configure a conversion algorithm. Example code is in 
- if you don't want to deal with an offset but prefer to have "raw UTM" meter values in your map, you can add netconvert option **--offset.disable-normalization** in the initial conversion.

see https://github.com/eclipse/sumo/blob/1709483215c9330c08b555496a571a89ea896b5d/tools/sumolib/net/__init__.py#L445-L480

**Comment by Hjp-momojiji** [comment]
I use -offset.disable-normalization，why output xodr still not lat and lon，such as:
  <![CDATA[
 +proj=utm +zone=49 +ellps=WGS84 +datum=WGS84 +units=m +no_defs
]]>

**Comment by namdre** [comment]
> I use -offset.disable-normalization，why output xodr still without lat and lon，such as: ` **<![CDATA[ +proj=utm +zone=49 +ellps=WGS84 +datum=WGS84 +units=m +no_defs]]>**`

@Hjp-momojiji  Please open up another ticket and attach the xodr file in question.
