### ISSUE TITLE
Error while adding vehicle to simulation using traci.

### ISSUE THREAD

**Issue by thilagaguru** [eclipse/sumo#12566]
Operating system : Windows 10
Sumo version : 1.12.0

I am trying to add vehicle during the simulation using traci.vehicle.add
I have the below two requirements. 
1. Add route using Traci and add vehicle to the newly added route
2. Add vehicle to the predefined route

**Requirement1: Add route using Traci and add vehicle to the newly added route.** 

I want to add a route and let the vehicle flow in the route  @timestep = 10
My code is as below and ended up with the below error message

while traci.simulation.getMinExpectedNumber() > 0:    
 
        traci.simulationStep();
        timestep = traci.simulation.getTime()
        vehicleID=traci.vehicle.getIDList();
        trafficlights=traci.trafficlight.getIDList();
		
        for i in range(0,len(vehicleID)):		
                vehid = vehicleID[i]
                if timestep == 10:
                    traci.route.add("route_5", ["26616878#2", "328071933#1"])
                    traci.vehicle.add("veh5", "route_0", typeID="passenger")
                    
traci.close()

**Error message**
![route_error1](https://user-images.githubusercontent.com/36147578/216929150-22e1feb7-3155-459b-aa14-263034fe5838.png)

![route_error11](https://user-images.githubusercontent.com/36147578/216929162-b4b266d0-059e-499d-a624-8138ae3f5e7a.png)

**Requirement2: Add vehicle to the predefined route**
In a route file there is a route called route_0
I want to add the vehicle and let the vehicle follow route_0 from route file. 
I want to know if that is possible. 
I tried the below coding for the purpose and ended up with the below error message.

while traci.simulation.getMinExpectedNumber() > 0:
       
        traci.simulationStep();
        timestep = traci.simulation.getTime()
        vehicleID=traci.vehicle.getIDList();
        trafficlights=traci.trafficlight.getIDList();	
		
        for i in range(0,len(vehicleID)):		
                vehid = vehicleID[i]
                if timestep == 10:
                    traci.vehicle.add("veh5", "route_0", typeID="bus")
traci.close()

**Error message**
![route_error2](https://user-images.githubusercontent.com/36147578/216929821-467aaac0-e817-44ae-8358-f4c53ffe70f0.png)
![route_error22](https://user-images.githubusercontent.com/36147578/216929847-3284a219-cb12-4a39-914d-2a915d46c484.png)

It would be grateful if you could advise, what did i miss for the above two requirements.

Thanks in advance
Thilaga.

**Comment by namdre** [comment]
1. you cannot add two routes with the same ID (but you can catch the TraCIException)
2. you cannot add two vehicles with the same ID (but you can catch the TraCIException)

**Comment by thilagaguru** [comment]
> 1. you cannot add two routes with the same ID (but you can catch the TraCIException)
> 2. you cannot add two vehicles with the same ID (but you can catch the TraCIException)


Thank you so much for the reply. 
I forgot to mention earlier, that route id and vehicle id mentioned in the traci.add are unique.
For reference, I have shared the netfile, routefile, config file and traci file. 
Please have a look.
It would be really helpful if you could advise me what should i modify to make traci.add working.


Thank you. 
[github.zip](https://github.com/eclipse/sumo/files/10670473/github.zip)

**Comment by namdre** [comment]
The error message unambiguously indicates that the same vehicle id was used twice. Moreover, the code that you gave in your issue description shows that the hardcoded vehicleID `veh5`  will added multiple times: `traci.vehicle.add("veh5", "route_0", typeID="bus")`  (under the condition  that there are at least two vehicles in the simulation at time 10)

**Comment by thilagaguru** [comment]
> 

Thank you very much for the clear explanation. 
I worte the traci.add.vehicle command outside the loop and it worked. 
Your help is greatly appreciated.
