### ISSUE TITLE
Adding background images and tiff file.

### ISSUE THREAD

**Issue by KEYAGO** [eclipse/sumo#12560]
Right now, Netedit and GUI can open background images. We make it by giving file paths to apps. I think it should be more easy. For example, we can use buttons named "Add Image" or "Open Image" like "Open Network" button in the "File" menu. Can it doable? 

My second question is about geographical image files. I think we can use .tiff files only in sumo-gui. But having this feature in Netedit will give the traffic engineers convenience in their municipal works. Can it doable?

**1.14.1**

**Windows 10**

**Comment by namdre** [comment]
for point 1, we already have this as an issue: #1627
for point 2, geotiff should also reposition automatically in netedit when loading a geo-referenced network

**Comment by namdre** [comment]
#1627 has been added to the 1.17.0 milestone.
w.r.t. feel free to provide a net and geotiff that are not working as expected in netedit but working in sumo-gui

**Comment by behrisch** [comment]
Closing for lack of feedback. Feel free to add another comment if you have more information or can provide example files.
