### ISSUE TITLE
traci.vehicle.setAcceleration - invalid command

### ISSUE THREAD

**Issue by ShanJiang-2020** [eclipse/sumo#12564]
When I use 'traci.vehicle.setAcceleration' to control the motion of vehicles, the returned results are completely different from my comands.
Take vehicle '1' (its id) as an example, in simulation time 19.0s, I give the command: traci.vehicle.setAcceleration('1', 1.1304, 1.7692), where 1.1304 m^2/s is the acceleration and 1.7692 s is the expected duration of the given acceleration. 
However, the real-time results are:
Current time: 19.00 s.
Position of vehicle 1: 5.10 m.
Speed of vehicle 1: 0.00 m/s.
Acceleration of vehicle 1: 0.00 m^2/s.
Current time: 20.00 s.
Position of vehicle 1: 5.82 m.
Speed of vehicle 1: 0.72 m/s.
Acceleration of vehicle 1: 0.72 m^2/s.
Current time: 21.00 s.
Position of vehicle 1: 7.27 m.
Speed of vehicle 1: 1.44 m/s.
Acceleration of vehicle 1: 0.72 m^2/s.
Current time: 22.00 s.
Position of vehicle 1: 10.39 m.
Speed of vehicle 1: 3.13 m/s.
Acceleration of vehicle 1: 1.68 m^2/s.
Current time: 23.00 s.
Position of vehicle 1: 15.27 m.
Speed of vehicle 1: 4.87 m/s.
Acceleration of vehicle 1: 1.75 m^2/s.
Current time: 24.00 s.
Position of vehicle 1: 21.85 m.
Speed of vehicle 1: 6.59 m/s.
Acceleration of vehicle 1: 1.71 m^2/s.
Current time: 25.00 s.
Position of vehicle 1: 28.62 m.
Speed of vehicle 1: 6.77 m/s.
Acceleration of vehicle 1: 0.18 m^2/s.
Current time: 26.00 s.
Position of vehicle 1: 36.23 m.
Speed of vehicle 1: 7.61 m/s.
Acceleration of vehicle 1: 0.84 m^2/s.
......

**Comment by ShanJiang-2020** [comment]
Found a good answer: https://www.eclipse.org/lists/sumo-user/msg10468.html
The author suggests using traci.vehicle.setSpeed directly, so I will try to use setSpeed to control the acceleration.

**Comment by namdre** [comment]
There is some scaling over sub-second step lengths going on. You will probably have more success if you only set acceleration for a duration that matches the step-length.
