### ISSUE TITLE
Maximum number of loop detectors in the network

### ISSUE THREAD

**Issue by muzammilabbas94** [eclipse/sumo#12567]
I am placing loop detectors (e1) in the network after placing 510+ detectors, the .sumocfg file couldn't upload the additional file (det.xml). The error message "too many files" was prompting. When I removed some detectors and bring them to 502, the issue was resolved. Is there any limitation in SUMO in placing the number of detectors?

Version 1.13.0

Windows

**Comment by namdre** [comment]
There is no limit in the number of detectors but there is a limit (by the operating system) on the maximum number of open files. A simple solution is to have all detectors write to the same output file (their output can still be distinguished based on the detector id).
