### ISSUE TITLE
Split the joined junctions in NETEDIT

### ISSUE THREAD

**Issue by MohamadReza-Haghani** [eclipse/sumo#12578]
Hi,

I know there is a command named "Join selected junctions" in NETEDIT to merge adjacent junctions into one junction. I was wondering if there is a way to split the joined junctions.

Best,
Reza.

**Comment by namdre** [comment]
If edges have distinct end points (i.e. because the junction was created from a join) then you can split it from the junction context menu (*split* or *split and reconnect*).
