### ISSUE TITLE
import width and custom length from shapefile

### ISSUE THREAD

**Issue by SongKun2023** [eclipse/sumo#12575]
Add your issue description here.
Hello, sumo developer, I attempted using "netconvert" to convert shapefile to net.xml. But I don't know how to convert some attributions into net.xml, such as the shapes, the speed limits and the width of lanes. I will appreciate it if you can provide some suggestions.

SUMO-version:1.16

operating system:Windows

**Comment by namdre** [comment]
call `netconvert --help formts` and check out the options that start with **shapefile.**
If you load a shapefile with option **--verbose** it will list the available data fields that can be used with the above options. (geometry is used automatically).

**Comment by SongKun2023** [comment]
According to the documentation, the all options are as follows ( the output of "netconvert --help formts" is the same):

![L4 0%~73Q~E@U~H$%OSLQLQ](https://user-images.githubusercontent.com/97946646/217223909-6f645e31-7066-44c7-aa7e-657cf0c8cbfd.png)

**Comment by namdre** [comment]
there is currently no option provided to import width but the rest should work.

**Comment by SongKun2023** [comment]
OK, sir. Besides, I notice that the length of edge can not convert accurately, the example is as follows. Some even have bigger deviation.

![} }2$GOAA6%`0H4%YP1JCF6](https://user-images.githubusercontent.com/97946646/217236945-22a50e4c-b1a9-46c1-9099-1a24a4bda008.png)



![FW98%W (Z@6{P9 00`LN_Q2](https://user-images.githubusercontent.com/97946646/217236969-3ad7dc33-088e-44db-9df1-51ba57b639c3.png)

**Comment by namdre** [comment]
Can you provide a small example input file that we could use for testing this feature?

**Comment by SongKun2023** [comment]
yes.
[shapefile.zip](https://github.com/eclipse/sumo/files/10674841/shapefile.zip)

**Comment by namdre** [comment]
Note, that there may be a mismatch if the provided length fields are between intersection centers whereas netconvert assumes the length that is not part of an intersection.

**Comment by SongKun2023** [comment]
OK, thank you Dr. namdre for your response.
