### ISSUE TITLE
make sure that python tools can run with option --save-template

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#12589]
some tools (i.e. randomTrips) preempt template generation with their own error checking:

  `randomTrips.py: error: argument -n/--net-file is required.`

required for #4138

**Comment by behrisch** [comment]
This requires unsetting the "required" flag temporarily before parsing the options for the template saving

**Comment by behrisch** [comment]
The infrastructure has been fixed, everything else is up to the individual tools
