### ISSUE TITLE
Errors in netconvert (public transport infrastructure)

### ISSUE THREAD

**Issue by gladysmcgan** [eclipse/sumo#12592]
There are some edges in my network that are not imported with the right number of lanes and direction. In particular, they are in the opposite (wrong) direction as the on-road tram rails, creating errors when merging the rails onto the road. 

1. Badenerstrasse

<img width="560" alt="badenerstrasse" src="https://user-images.githubusercontent.com/59922884/217896728-2c385c65-f85c-4f18-9b45-e9d63a6d8946.png">

```
bus:lanes:backward=yes lanes=3 lanes:backward=1 lanes:forward=2 oneway=yes oneway:bus=no vehicle:lanes:forward=no|yes 
```

- The edge was created with three lanes going one way, instead of one going the opposite direction. 
- This seems like the same issue as #10650, where oneway tag for the bus is not read.
- edge 408534466#0 in the badenerstrasse.net.xml

2. Birmensdorferstrasse

<img width="560" alt="birmensdorferstrasse" src="https://user-images.githubusercontent.com/59922884/217896783-af4479b2-ff14-4b62-a828-d5fbab9bfa6c.png">

```
access=no bus=yes lanes=2 oneway=no psv=yes
```
- The edge was created with two lanes going one way, instead of one going in the opposite direction. 
- I am not sure of the reason for this error.
- edge 375503745#6 in birmensdorferstrasse.net.xml 

Thanks in advance for the help.

The network files: [google drive folder](https://drive.google.com/drive/folders/1rXVG5s4hQiy1xtGFbvGFWPVLOpnk4qJX?usp=share_link)

Eclipse SUMO netconvert Version 1.15.0

**Comment by behrisch** [comment]
@gladysmcgan Please recheck whether the issues are really fixed. It was a little hard to reproduce since the input osm files were not in the google drive. If problems persist add a comment here.

**Comment by gladysmcgan** [comment]
Thanks very much for fixing this! The oneway errors are solved. But the Birmensdorferstrasse error above still remains, which seems to be due to the tags indicating access to the road. Below are similar examples:

1. Schaffhauserstrasse [(OSM page)](https://www.openstreetmap.org/way/418255957)
<img width="524" alt="schaffhauserstrasse" src="https://user-images.githubusercontent.com/59922884/221827150-d7284f46-d75a-497f-9d69-04953092df1d.png">

`access=no lanes=2 vehicle=no bus=yes oneway=no`
- see edge 418255957 in oerlikon-osm.net.xml

2. Edisonstrasse [(OSM page)](https://www.openstreetmap.org/way/33688393)
<img width="525" alt="edisonstrasse" src="https://user-images.githubusercontent.com/59922884/221827173-188fa524-9636-4ff7-922f-c7f78328886e.png">

`motorcar=no bus=yes psv=yes oneway=yes`
- see edge 208161493 in oerlikon-osm.net.xml


The files are here (with the inputs this time!): [google drive](https://drive.google.com/drive/folders/1EjTudQmPlwjNi6xFwFJZOIBeGcJSHfW3?usp=sharing)

**Comment by behrisch** [comment]
@gladysmcgan Please recheck if it resolves all your worries. We also added the oerlikon to our regular test suite
