### ISSUE TITLE
After removing the traffic lights, the length of the edge is reduced. 

### ISSUE THREAD

**Issue by ZJ726** [eclipse/sumo#12598]
After discarding the traffic lights in map.net.xml by --tls.discard-loaded, the length of many edges becomes a little shorter. How to ensure that the traffic lights in the original road network map.net.xml are removed and a new road network newmap.net.xml without traffic lights is obtained while the edges' length remains unchanged?

Or, I just want to remove all traffic lights from the original road network, and the attribute information of the edges and nodes remains unchanged. What should I do?

**SUMO-version:** sumo-1.8.0

- the original road network ：map.net.xml 
![984c5bbfb25396b55d91732ca717914](https://user-images.githubusercontent.com/76982408/218302740-70cd513e-3de5-471d-8724-f17c7518be52.png)
- the new road network without traffic lights：newmap.net.xml 
![28eddd68b1b9e0b170392ca9a281260](https://user-images.githubusercontent.com/76982408/218302749-7d60f620-7f7d-4b8b-a54b-9f869fa868a1.png)

**Comment by behrisch** [comment]
Can you recheck whether the problem is also present in the most recent SUMO (1.16.0)?

**Comment by ZJ726** [comment]
> Can you recheck whether the problem is also present in the most recent SUMO (1.16.0)?

Thank you very much. Let me try.

**Comment by behrisch** [comment]
Closing for lack of feedback. Feel free to add another comment if you have more information or can provide a scenario which fails with the most recent SUMO.
