### ISSUE TITLE
Failed to generate e2 detector for a road network without traffic lights.

### ISSUE THREAD

**Issue by ZJ726** [eclipse/sumo#12606]
Failed to generate e2 detector file e2.add.xml for a road network without traffic lights.
![c2aa4cb24248b6eb95bed25c38f3151](https://user-images.githubusercontent.com/76982408/218426581-a128e1ad-61a9-4e2d-b865-02a808e3f2ef.png)

What should I do？

**SUMO-version:**sumo-1.8.0

**Comment by m-kro** [comment]
The script is meant for networks with traffic lights (TLS = traffic light signal): the detectors created by the script are positioned in the incoming lanes of the signal-controlled intersections. So you have to provide a network with traffic lights to obtain detector definitions.

**Comment by ZJ726** [comment]
Thank you very much！
I want to observe the relevant statistics of each lane in the road network without traffic lights, such as flow information, average speed, etc., what should I do? Is there any other good way besides the e2 detector?

**Comment by ZJ726** [comment]
> The script is meant for networks with traffic lights (TLS = traffic light signal): the detectors created by the script are positioned in the incoming lanes of the signal-controlled intersections. So you have to provide a network with traffic lights to obtain detector definitions.

Thank you very much！
I want to observe the relevant statistics of each lane in the road network without traffic lights, such as flow information, average speed, etc., what should I do? Is there any other good way besides the e2 detector?

**Comment by m-kro** [comment]
Then maybe you should look at [edge / lane data output](https://sumo.dlr.de/docs/Simulation/Output/Lane-_or_Edge-based_Traffic_Measures.html).

**Comment by ZJ726** [comment]
> Then maybe you should look at [edge / lane data output](https://sumo.dlr.de/docs/Simulation/Output/Lane-_or_Edge-based_Traffic_Measures.html).



> Then maybe you should look at [edge / lane data output](https://sumo.dlr.de/docs/Simulation/Output/Lane-_or_Edge-based_Traffic_Measures.html).

Thank you very much.

**Comment by ZJ726** [comment]
> Then maybe you should look at [edge / lane data output](https://sumo.dlr.de/docs/Simulation/Output/Lane-_or_Edge-based_Traffic_Measures.html).

There is currently no way to accurately count the total number of vehicles passing through tool “lanes in the Lane-or Edge-based Traffic Measures”, but this data is very important for me.
So can I use the information of edge in the road network without traffic lights and the file format of xxx.add.xml to generate my_e2.add.xml by python encoding to achieve the purpose of setting e2 detectors for every edge? I only need the flow information in the e2 detector output file.

**Comment by namdre** [comment]
The values `entered` or `left` give you the count of vehicles per edge (for edgeData) or lane (for laneData). Depending on your needs you can also use `entered - arrived` to count the number of vehicles that fully passed the edge.  What exactly are you missing?

Of course you can write a python script that simple creates a detector for every edge should you so desire.

**Comment by ZJ726** [comment]
> The values `entered` or `left` give you the count of vehicles per edge (for edgeData) or lane (for laneData). Depending on your needs you can also use `entered - arrived` to count the number of vehicles that fully passed the edge. What exactly are you missing?
> 
> Of course you can write a python script that simple creates a detector for every edge should you so desire.

Thank you very much! Your answer is very helpful to me！
