### ISSUE TITLE
[homebrew] Cannot install 1.16 version and 1.15 version anymore

### ISSUE THREAD

**Issue by palikao** [eclipse/sumo#12604]
Hi,
I’m using Mojave-bottle of Homebrew and I had 1.15 version of sumo installed.
Recently I noticed that sumo 1.15 didn’t start anymore. I tried to install it again, but I can’t install it anymore. The error is on Freetype dependency..

1.16 is parked, and can’t be installed..

How can I install a working version of Sumo (1.15)? Which are the latest working versions of dependencies?
I’m not so expert in command line..

**Comment by angelobanse** [comment]
Can you post that "Freetype dependency" error message?
You can install an earlier version using `brew install sumo@1.15.0`

**Comment by palikao** [comment]
This is the log:

==> Installing sumo@1.15.0 from dlr-ts/sumo
==> Installing dependencies for dlr-ts/sumo/sumo@1.15.0: freetype, libx11, libxrender, libxrandr, mesa, fox and proj
==> Installing dlr-ts/sumo/sumo@1.15.0 dependency: freetype
==> ./configure --prefix=/usr/local/Cellar/freetype/2.13.0 --enable-freetype-con
==> make
Last 15 lines from /Users/stefano/Library/Logs/Homebrew/freetype/02.make:
libtool: compile:  clang -pedantic -std=c99 -I/private/tmp/freetype-20230213-74459-1pymfo5/freetype-2.13.0/src/sfnt -I/private/tmp/freetype-20230213-74459-1pymfo5/freetype-2.13.0/objs -I./builds/unix -I/private/tmp/freetype-20230213-74459-1pymfo5/freetype-2.13.0/include -c -Wall -g -O2 -fvisibility=hidden -DDARWIN_NO_CARBON -I/usr/local/Cellar/libpng/1.6.39/include/libpng16 -pthread "-DFT_CONFIG_CONFIG_H=<ftconfig.h>" "-DFT_CONFIG_MODULES_H=<ftmodule.h>" "-DFT_CONFIG_OPTIONS_H=<ftoption.h>" -DFT2_BUILD_LIBRARY /private/tmp/freetype-20230213-74459-1pymfo5/freetype-2.13.0/src/sfnt/sfnt.c  -fno-common -DPIC -o /private/tmp/freetype-20230213-74459-1pymfo5/freetype-2.13.0/objs/.libs/sfnt.o
In file included from /private/tmp/freetype-20230213-74459-1pymfo5/freetype-2.13.0/src/sfnt/sfnt.c:21:
/private/tmp/freetype-20230213-74459-1pymfo5/freetype-2.13.0/src/sfnt/pngshim.c:411:7: error: expected expression
      FALL_THROUGH;
      ^
/private/tmp/freetype-20230213-74459-1pymfo5/freetype-2.13.0/include/freetype/internal/compiler-macros.h:46:27: note: expanded from macro 'FALL_THROUGH'
#    define FALL_THROUGH  __attribute__(( __fallthrough__ ))
                          ^
1 error generated.
./builds/unix/libtool --mode=compile clang -pedantic -std=c99 -I/private/tmp/freetype-20230213-74459-1pymfo5/freetype-2.13.0/src/autofit -I/private/tmp/freetype-20230213-74459-1pymfo5/freetype-2.13.0/objs -I./builds/unix -I/private/tmp/freetype-20230213-74459-1pymfo5/freetype-2.13.0/include  -c -Wall -g -O2 -fvisibility=hidden -DDARWIN_NO_CARBON   -I/usr/local/Cellar/libpng/1.6.39/include/libpng16 -pthread -DFT_CONFIG_CONFIG_H="<ftconfig.h>" -DFT_CONFIG_MODULES_H="<ftmodule.h>" -DFT_CONFIG_OPTIONS_H="<ftoption.h>" -DFT2_BUILD_LIBRARY -o /private/tmp/freetype-20230213-74459-1pymfo5/freetype-2.13.0/objs/autofit.lo /private/tmp/freetype-20230213-74459-1pymfo5/freetype-2.13.0/src/autofit/autofit.c
make: *** [/private/tmp/freetype-20230213-74459-1pymfo5/freetype-2.13.0/objs/sfnt.lo] Error 1
make: *** Waiting for unfinished jobs....
libtool: compile:  clang -pedantic -std=c99 -I/private/tmp/freetype-20230213-74459-1pymfo5/freetype-2.13.0/src/autofit -I/private/tmp/freetype-20230213-74459-1pymfo5/freetype-2.13.0/objs -I./builds/unix -I/private/tmp/freetype-20230213-74459-1pymfo5/freetype-2.13.0/include -c -Wall -g -O2 -fvisibility=hidden -DDARWIN_NO_CARBON -I/usr/local/Cellar/libpng/1.6.39/include/libpng16 -pthread "-DFT_CONFIG_CONFIG_H=<ftconfig.h>" "-DFT_CONFIG_MODULES_H=<ftmodule.h>" "-DFT_CONFIG_OPTIONS_H=<ftoption.h>" -DFT2_BUILD_LIBRARY /private/tmp/freetype-20230213-74459-1pymfo5/freetype-2.13.0/src/autofit/autofit.c  -fno-common -DPIC -o /private/tmp/freetype-20230213-74459-1pymfo5/freetype-2.13.0/objs/.libs/autofit.o
libtool: compile:  clang -pedantic -std=c99 -I/private/tmp/freetype-20230213-74459-1pymfo5/freetype-2.13.0/src/bdf -I/private/tmp/freetype-20230213-74459-1pymfo5/freetype-2.13.0/objs -I./builds/unix -I/private/tmp/freetype-20230213-74459-1pymfo5/freetype-2.13.0/include -c -Wall -g -O2 -fvisibility=hidden -DDARWIN_NO_CARBON -I/usr/local/Cellar/libpng/1.6.39/include/libpng16 -pthread "-DFT_CONFIG_CONFIG_H=<ftconfig.h>" "-DFT_CONFIG_MODULES_H=<ftmodule.h>" "-DFT_CONFIG_OPTIONS_H=<ftoption.h>" -DFT2_BUILD_LIBRARY /private/tmp/freetype-20230213-74459-1pymfo5/freetype-2.13.0/src/bdf/bdf.c -o /private/tmp/freetype-20230213-74459-1pymfo5/freetype-2.13.0/objs/bdf.o >/dev/null 2>&1
libtool: compile:  clang -pedantic -std=c99 -I/private/tmp/freetype-20230213-74459-1pymfo5/freetype-2.13.0/src/autofit -I/private/tmp/freetype-20230213-74459-1pymfo5/freetype-2.13.0/objs -I./builds/unix -I/private/tmp/freetype-20230213-74459-1pymfo5/freetype-2.13.0/include -c -Wall -g -O2 -fvisibility=hidden -DDARWIN_NO_CARBON -I/usr/local/Cellar/libpng/1.6.39/include/libpng16 -pthread "-DFT_CONFIG_CONFIG_H=<ftconfig.h>" "-DFT_CONFIG_MODULES_H=<ftmodule.h>" "-DFT_CONFIG_OPTIONS_H=<ftoption.h>" -DFT2_BUILD_LIBRARY /private/tmp/freetype-20230213-74459-1pymfo5/freetype-2.13.0/src/autofit/autofit.c -o /private/tmp/freetype-20230213-74459-1pymfo5/freetype-2.13.0/objs/autofit.o >/dev/null 2>&1

**Comment by palikao** [comment]
> Can you post that "Freetype dependency" error message? You can install an earlier version using `brew install sumo@1.15.0`

I was trying to install that version.. But that is the error...
The problem is on Freetype 2.13.. Probably 2.12.1 version is ok..

**Comment by angelobanse** [comment]
Freetype is a dependency of Fox, and was [updated recently](https://github.com/Homebrew/homebrew-core/commits/master/Formula/freetype.rb) (2 days ago).

Maybe due to an old macOS version / clang compiler?

- https://gitlab.freedesktop.org/freetype/freetype/-/blob/master/include/freetype/internal/compiler-macros.h#L46
- https://gitlab.freedesktop.org/freetype/freetype/-/commit/ac5babe87629107c43f627e2cd17c6cf4f2ecd43

**Comment by angelobanse** [comment]
The user has macOS 10.14 (Mojave), for which there is no bottle available for FreeType (a dependency of Fox), thus requiring a build. During set manual homebrew build of FreeType, an error was raised by the Apple LLVM compiler.
The issue has been addressed by the FreeType developers (see [thread](https://gitlab.freedesktop.org/freetype/freetype/-/commit/ac5babe87629107c43f627e2cd17c6cf4f2ecd43#note_1771027)).
