### ISSUE TITLE
Crossing cannot be created in a intersection with four arms with sidewalks

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#12609]
Check NBNode::checkCrossing(EdgeVector candidates, bool checkOnly)

Found by netedit tests.

[net.net.xml.zip](https://github.com/eclipse/sumo/files/10730562/net.net.xml.zip)

**Comment by namdre** [comment]
you network used edge speeds of 13.9 which is above the threshold for guessed crossings of 13.89. Now, netedit doesn't check the speed threshold anymore.

**Comment by namdre** [comment]
was a regression in 1.16.0
