### ISSUE TITLE
Loading JNI dll does not work on Windows anymore

### ISSUE THREAD

**Issue by kschrab** [eclipse/sumo#12605]
Trying to load `libsumojni.dll` or `libtracijni.dll` on Windows machine does not work anymore since 1.16.0 (Downloaded from https://sumo.dlr.de/docs/Downloads.php).

```java
public static void main(String[] args) {
    System.loadLibrary("libsumojni");
}
```

When starting with `-Djava.library.path=C:\dev\sim\sumo-1.16.0\bin`, results in: 

```
java.lang.UnsatisfiedLinkError: C:\dev\sim\sumo-1.16.0\bin\libsumojni.dll: Can't find dependent libraries
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
	at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:315)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:287)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2422)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
	at java.base/java.lang.System.loadLibrary(System.java:1989)
```

Tried out with several JDK versions ranging from 8 to 17, all result in the same error message. Switching to SUMO 1.14.0 or 1.15.0 does not come with this problem. Using the [Dependencies](https://github.com/lucasg/Dependencies) tool did not reveal any broken link. Using the extra version of SUMO did not help either.

**SUMO-version:** 1.16.0

**operating system:** Windows 10 x64

**Comment by behrisch** [comment]
There are now new dependencies due to the localization and apparently java is too stupid to find them (sorry about the rant but I just spent two hours on that). The solutions provided here: https://stackoverflow.com/questions/42536366 propose that you can manually preload the needed libraries and I can confirm that adding

        System.loadLibrary("iconv-2");
        System.loadLibrary("intl-8");
before

        System.loadLibrary("libtracijni");
indeed solved the issue here. The error does not occur on every machine though, so you might also be lucky by just installing an up to date MSVC redistributable package (also proposed in the stackoverflow above). Please report back whether it helps!

**Comment by palvarezlopez** [comment]
@behrisch should we add the dlls in the SUMOLibraries?

**Comment by behrisch** [comment]
That's not the point. They are there. The point is that every libtracijni-user needs to add (at least) those two lines to their code.

**Comment by kschrab** [comment]
Thanks for looking at this immediately! 

For `libsumojni` one need to load `proj_9_0` in advance, too:

```java
System.loadLibrary("iconv-2");
System.loadLibrary("intl-8");
System.loadLibrary("proj_9_0");

System.loadLibrary("libsumojni");
```

**Comment by behrisch** [comment]
@kschrab Could you check whether installing a new msvc redistributable helps too?

**Comment by kschrab** [comment]
> @kschrab Could you check whether installing a new msvc redistributable helps too?

I installed the redistributables [from here](https://learn.microsoft.com/de-de/cpp/windows/latest-supported-vc-redist?view=msvc-170) but it did not help

**Comment by behrisch** [comment]
Thanks for testing. I don't think we can do much here. I added a note to the docs and we removed the dependencies for libtraci. @palvarezlopez Do you think anything in the compilation process for proj changed which could result in this new behavior? The workaround is not nice but I hope it is feasible. Please reopen/comment if you have more ideas.

**Comment by kschrab** [comment]
This issue seems to got worse with 1.21.0 :(

It's not sufficient anymore to just load `iconv-2`, `intl-8`, `proj_9_0` beforehand. Some other libraries fail as well, but it's not possible to find any reason for that. I was also not yet able to find a complete list of System.load(...) calls which would lead to a successful call of `System.loadLibrary("libsumojni");`. Since the order of loading the libraries is important, we cannot just import all of them in a row, but only in the correct order, which I was not yet able to find.

As a really really (!) ugly workaround I currently run several times through all dll-files I can find in the SUMO bin directory and try to load them by ignoring any link errors, until after 4 iterations everything could be loaded. 💀

```java
final String SUMO_HOME = System.getenv("SUMO_HOME");
for (int i = 0; i < 4; i++) {
    Files.list(Path.of(SUMO_HOME).resolve("bin"))
            .filter(f -> f.toString().endsWith(".dll"))
            .forEach(f -> {
                try {
                    System.load(f.toAbsolutePath().toString());
                } catch (Throwable ignore) {}
            });
}
Simulation.load(new StringVector());
```

**Comment by namdre** [comment]
@kschrab I just received your comment `This issue seems to got worse with 1.21.0 :(` by mail but cannot see it here in the ticket. Can you confirm that this is relevant and wasn't intentionally deleted?
