### ISSUE TITLE
how to get distance

### ISSUE THREAD

**Issue by SongKun2023** [eclipse/sumo#12608]
Add your issue description here.
Hello, sir. If I have a coordinate of a point on a edge, how can I get the distance between this point and the starting point of the edge along the edge?

**Comment by m-kro** [comment]
In sumo-gui, this information is displayed in the lane context menu:

- right mouse click above lane
- context menu opens with a line saying **"pos: [...] height: [...]"**
- the "pos" value is what you asked for

**Comment by SongKun2023** [comment]
OK, sir, thank you. Can I get those attributions by codes automatically?

**Comment by m-kro** [comment]
Have a look at [sumolib](https://sumo.dlr.de/docs/Tools/Sumolib.html) (see docs how to use it in general), especially [sumolib.net.edge.getClosestLanePosDist](https://sumo.dlr.de/pydoc/sumolib.net.edge.html).

**Comment by SongKun2023** [comment]
OK, thanks a lot.
