### ISSUE TITLE
randomTrips.py: do not generate trips that start/end inside a roundabout

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#12619]
maybe with an option to allow this if needed explicitly

**Comment by mehmetnedimyavuz** [comment]
I am using the latest development version of SUMO (sumo Version v1_16_0+0802-cb0bb8ac9af), I can not reach with --help option to --allow-roundabouts. 
My command line is like this: python randomTrips.py -n deneme2.net.xml -r deneme2.rou.xml --allow-roundabouts
 It gives an error: randomTrips.py: error: unrecognized arguments: --allow-roundabouts

Thank you for help,regards.

**Comment by namdre** [comment]
This option was added after the release of 1.16.0 and thus, is only available in the latest development version. You can obtain that version: https://sumo.dlr.de/docs/Downloads.php#nightly_snapshots
Note, that in 1.16.0 and earlier, trips can always start and end in roundabouts so that option only exists to provide backward-compatibility for what is considered an uncommon use case.

**Comment by mehmetnedimyavuz** [comment]
However, I checked it with the latest development version. I downloaded to the latest development version with this link: https://sumo.dlr.de/daily/sumo-win64extra-git.msi a few minutes ago. (Eclipse SUMO sumo Version v1_16_0+0802-cb0bb8ac9af)
.

**Comment by namdre** [comment]
My best guess is, that you still have an older version of randomTrips on your system.
Try running without option --allow-roundabouts and then post the first 3 lines of the generated trip file (it contains the exact version string of randomTrips)
