### ISSUE TITLE
About emergency stop at the end of lane

### ISSUE THREAD

**Issue by ckh0715** [eclipse/sumo#12617]
[000a07a3-fec1-47d5-8ba7-e8610409efb3.zip](https://github.com/eclipse/sumo/files/10740981/000a07a3-fec1-47d5-8ba7-e8610409efb3.zip)

![image](https://user-images.githubusercontent.com/56399136/218974997-679e7ab0-8f46-4bb1-80fd-e08b61b5a677.png)

How to solve this problem?

**Comment by namdre** [comment]
The problem is that you are using a custom network where lanes of the same edge have different lengths. This violates a core assumption about normal driving edges.
See https://sumo.dlr.de/docs/FAQ.html#i_made_changes_to_the_netxml-file_but_it_did_not_work_as_expected_why
