### ISSUE TITLE
Simulation file closing suddenly

### ISSUE THREAD

**Issue by mehmetnedimyavuz** [eclipse/sumo#12618]
I have a network file and I used randomtrips.py tool to obtain initial routes for using routesampler tool. When running network file with randomtrips.py tool,it seems no problem,and it creates route and trip file. When running config file, the file is closing suddenly at simulation 55.second. I am adding the files.Can you help on this issue? Regards.
[files.zip](https://github.com/eclipse/sumo/files/10741397/files.zip)

**Comment by m-kro** [comment]
Breaks assertion for vehicle id="43" (no bluelight device involved):
https://github.com/eclipse/sumo/blob/c935e8d62ab58cf3402dd2ce479fd3d85c94d58f/src/microsim/MSLane.cpp#L377

**Comment by namdre** [comment]
regression in 1.13.0. Would throw towns of warnings before that but not crash.

**Comment by palvarezlopez** [comment]
@namdre @m-kro crash only in Windows?

**Comment by namdre** [comment]
I can reproduce this on linux

**Comment by namdre** [comment]
there was a corner case in which the further lanes and their occupation were not correctly updated when lane changing while the back of the car was on a strongly curved internal lane.
