### ISSUE TITLE
How download older version sumo's rpm packages

### ISSUE THREAD

**Issue by yeyingwuyue** [eclipse/sumo#12629]
When i use rpm to install sumo, find that in  " http://download.opensuse.org/repositories/science:/dlr/"  always keep the latest release version.  is there any way to get the rpm packages' older version?

thanks for yor attention ~

**Comment by behrisch** [comment]
No, unfortunately not. You might have some luck with looking here: https://pkgs.org/download/sumo but apart from that you need to build yourself.

**Comment by yeyingwuyue** [comment]
Thanks for your warm reply. 
I'm tring to build the older version .

**Comment by behrisch** [comment]
And I forgot to mention. If you are fine with installing sumo via pip. The [pypi package index](https://pypi.org/project/eclipse-sumo/#history) goes back to sumo 1.8
