### ISSUE TITLE
OSG font does not print "umlaut"

### ISSUE THREAD

**Issue by m-kro** [eclipse/sumo#12628]
OSG standard font is used for displaying the note about different navigation modes inside the OSG view. In order to use a different font with more characters, the system fonts have to be loaded correctly (didn't work in previous trials).

Possible solutions: ~Either find a font which provides the character, replace with "ue"/"oe"/"ae" or move the message out of the OSG view window...~ use UTF8 encoding first!

**Comment by m-kro** [comment]
@palvarezlopez I could not load the osgdb_freetype.dll from SUMO_LIBRARIES on my system through OpenSceneGraph. This prevents using system fonts like Arial for text in OSG. The self-compiled version of the dll did work though. So there might be a problem with dependencies.

**Comment by palvarezlopez** [comment]
@m-kro Thanks! I'm going to check OSM

**Comment by palvarezlopez** [comment]
Fixed in new OSM version
