### ISSUE TITLE
how to get a coordinate

### ISSUE THREAD

**Issue by SongKun2023** [eclipse/sumo#12621]
Add your issue description here.
Hello, sumo developer, according to a situation, there is a point near the edge, if I want to get the coordinate of the point projected onto the edge, what should I do to get it? is there such method in sumo? I would appreciate it if you can give me a reply.

**Comment by namdre** [comment]
https://sumo.dlr.de/docs/Tools/Sumolib.html#coordinate_transformations
https://sumo.dlr.de/pydoc/traci._simulation.html#SimulationDomain-convert3D
