### ISSUE TITLE
declare sumolib.options as having type 'file'

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#12635]
find a way to annotate options that are file names

related to #4138  because we want to generate file-picker dialogs instead of string input fields.

An ideomatic way would be to use an existing ArgumentParse option type https://docs.python.org/3/library/argparse.html#filetype-objects  but probably wouldn't go well together with our automated handling of gziped input and magic 'stdout', 'stderr' file names.

**Comment by behrisch** [comment]
While it is nice that those filetypes exist, I don't think we want to use them. They lead to further difficulties if you want to read the file twice or want to delay opening it for some reason. The cleanest way would be to invent our own type (sumolib.options.filename), a possible dirty workaround is to check for a magic metavar like "FILE"

**Comment by namdre** [comment]
duplicate of #12636
