### ISSUE TITLE
Issue with setStopParameter(...)

### ISSUE THREAD

**Issue by dalishalo** [eclipse/sumo#12630]
Hello everyone,

I have created a simulation, where a delivery truck waits at container stops for a period of time. This is working fine.
Now I wrote a python script, where the delivery truck should skip certain container stops during runtime, i.e it should not stop at certain container stops.

For that, I am calling the method `setStopParameter(vehicleID, 0, "duration", 0)`, which sets the duration of the next container stop to zero.

However, this call does not change anything in the behavior of the vehicle. It still waits at every container stop.

I have attached a small example, in order to understand the problem better.

SUMO-version: 1.16.0

operating system: Debian 10 (buster)
[Test_SetStopParam.zip](https://github.com/eclipse/sumo/files/10753323/Test_SetStopParam.zip)

**Comment by namdre** [comment]
skipping a stop with `setStopParameter` only works if you supply the exact lane and endPos of the stop you want to change.
An easier alternative may be to remove it by it's index using `replaceStop(vehID, index, "")`
