### ISSUE TITLE
how to save a net

### ISSUE THREAD

**Issue by SongKun2023** [eclipse/sumo#12633]
Add your issue description here.
Hello, sir, I want to add a lane by using the function of "net.addLane(...)" in sumolib, it's successful, but I don't know how to save the net. I'm looking forward to your reply, thanks.

**Comment by m-kro** [comment]
Changing network topology & geometry programmatically can be done with netconvert using the [Plain XML format](https://sumo.dlr.de/docs/Networks/PlainXML.html). Sumolib is not intended for this purpose and the addLane method is used to initialise the network graph in sumolib from a *.net.xml file.

**Comment by SongKun2023** [comment]
OK, thanks.

**Comment by namdre** [comment]
see https://sumo.dlr.de/docs/Tutorials/ScenarioGuide.html#modifying_the_network for a guide to change the network with python code using sumolib.

**Comment by SongKun2023** [comment]
Thank you for your help.
