### ISSUE TITLE
Buggy, discolored networks (edges and nodes) in sumo gui 

### ISSUE THREAD

**Issue by TheMedicineSeller** [eclipse/sumo#12639]
I installed sumo from their windows 10 installer for a RL project and when I open *any* `.net.xml` file or any simulation file, the networks and sim are all noisy and buggy. Same for when i use Netedit to render my own networks.. 

![image](https://user-images.githubusercontent.com/87657352/219428758-5337e402-c040-4011-891c-ef91661f2e7a.png)
![image](https://user-images.githubusercontent.com/87657352/219428960-477b5541-2f82-4cf0-96e8-0b5d9bef16c9.png)
![image](https://user-images.githubusercontent.com/87657352/219429019-2565c0e7-8cb3-40ad-b535-de9ae8966d6c.png)

Can someone from the sumo-staff please clarify and help ?

SUMO-version :  `1.14.1`
OS : Windows 10

**Comment by m-kro** [comment]
Please check your graphics card driver (see [FAQ](https://sumo.dlr.de/docs/FAQ.html#sumo-gui_windows_and_buttons_appear_but_no_netcars_are_visible_vehicles_are_not_visible_or_flicker_roads_are_drawn_on_top_of_vehicles)).

**Comment by TheMedicineSeller** [comment]
Checked my intel and nvidia (gpu) drivers

![image](https://user-images.githubusercontent.com/87657352/219436357-79b86b02-3f67-4547-96d4-533a4a4cb1c4.png)

![image](https://user-images.githubusercontent.com/87657352/219436489-a1a87e5a-8870-46bc-89f9-4d2bd1efe532.png)

Are these incompatible with the sumo gui ?

**Comment by TheMedicineSeller** [comment]
Ok according to [(https://sumo.dlr.de/docs/FAQ.html#distorted_view_with_green_lines_all_over_the_network)] I tried setting NVIDIA processor as the preferred settings for the sumo-gui and netgen programs and the flickering seems to have stopped. Thank you, you can close the issue.
