### ISSUE TITLE
libsumocpp.lib does not get copied to ./bin when compiling with VS

### ISSUE THREAD

**Issue by Domsall** [eclipse/sumo#12634]
When I compile SUMO with Visual Studio (cmake), libsumocpp.lib/libsumocppD.lib do not get copied to the ./bin folder. The libraries still get compiled and can be found in the build folder (.\out\build\x64-Release\src\libsumo), but then I need to copy them manually.

With libtracicpp, everything works as expected.

**SUMO-version:** 1.16.0

**operating system:** Windows 10

**Comment by palvarezlopez** [comment]
before every compilation, libsumo and libtraci files must be removed from bin
