### ISSUE TITLE
clang-debug build: supress foreign memleaks by default

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#12646]
always set `export LSAN_OPTIONS=suppressions=$PREFIX/sumo/build/clang_memleak_suppressions.txt`

**Comment by namdre** [comment]
it seems, that the LSAN_OPTIONS must be exported to the shell that runs the excutable. It doesn't seem to be fixed at compile time (or not by default anyway).

**Comment by behrisch** [comment]
It is not possible to (easily) set an environment variable for all build steps, but fortunately we only need it for the template generation step and this is what the above fix does
