### ISSUE TITLE
Create connections from OSM relation exceptions (netconvert)

### ISSUE THREAD

**Issue by gladysmcgan** [eclipse/sumo#12645]
I am trying to fix disconnected routes in public transport vehicles, and some disconnects are arising from missing connections between adjacent edges. I am guessing the reason is that netconvert does not read exceptions in OSM restriction relations. 

[Example of OSM restriction relation in the Zurich network](https://www.openstreetmap.org/relation/1157947). Here, except=psv (in other instances, except=bus) <img width="317" alt="connections-tag" src="https://user-images.githubusercontent.com/59922884/219687067-2802aba7-c220-4049-8e89-799b6e99f583.png"> 
<img width="424" alt="connections-milchbuck-osm" src="https://user-images.githubusercontent.com/59922884/219693636-15bfed47-50d5-44d3-85fd-66a6a7750188.png">

If it doesn't already exist, a useful option would be to write bus-specific connections to the network during netconvert. My fix now is to add the additional bus-specific connection (as below) to the connection file, to then patch the network file.
```
<connection from="576411466" to="38101627" fromLane="0" toLane="0" allow="bus"/>
<connection from="576411466" to="38101627" fromLane="1" toLane="1" allow="bus"/>
```

The option to teleport vehicles on disconnected routes (**--time-to-teleport.disconnected**) works, but the vehicles would not interact with car traffic realistically, e.g. if the edge to teleport the bus is full, the bus skips to the next edge and it might miss stops.

Eclipse SUMO netconvert Version 1.15.0

**Comment by namdre** [comment]
slightly related to #10406 and #6767 but looks like a distinct thing (exceptions in connection restrictions)

**Comment by gladysmcgan** [comment]
Awesome, thank you!
