### ISSUE TITLE
How to get real-time laneChangedFrom or laneChangedTo

### ISSUE THREAD

**Issue by xiaoyue-zhu** [eclipse/sumo#12649]
Hello!

My question is, how to dynamically get the number of vehicles that changed away from/to a specific lane during an interval (like the values in the [Lane- or Edge-based Traffic Measures](https://sumo.dlr.de/docs/Simulation/Output/Lane-_or_Edge-based_Traffic_Measures.html))?

And I have searched the documents about TraCI, like Lane Area Detector Value Retrieval and Lane Value Retrieval. But I can not find a proper way to solve my problem. If you have any suggestions, please let me know. Thank you very much!

**Comment by m-kro** [comment]
You could call lane.getLastStepVehicleIDs at every time step, store the results and compare the vehicle lists between adjacent lanes for times **t** and **t-1** whether a lane change has taken place. Maybe there are better options but that's what came to my mind...

**Comment by xiaoyue-zhu** [comment]
Thanks a lot!
