### ISSUE TITLE
generate documentation page with attribute help

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#12658]
using #12657

**Comment by behrisch** [comment]
for starters one separate page is enough

**Comment by behrisch** [comment]
Page is there: https://sumo.dlr.de/docs/Netedit/attribute_help.html
Things which still need to be resolved:

- [ ] from where to link to this page
- [ ] fix strange types  like "list of vclasses VClasses" and "discrete string"
- [ ] fix wrong types like "positive float" with a default of 0

**Comment by namdre** [comment]
some parts of the hierarchy outline are still broken (i.e. flow is a child of taz instead of calibrator).

@behrisch 
- 'unique' technically means, that the attribute isn't show when selecting multiple objects of it's type. I would filter this out 
- 'discrete string' means that it's a finite list of accepted values
