### ISSUE TITLE
If we need to generate the road network automatically, how to get the intersection 'shape' value?

### ISSUE THREAD

**Issue by programming-rubbish** [eclipse/sumo#12656]
Add your issue description here.

*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**

**Comment by namdre** [comment]
generation of junction shapes is performed automatically by netconvert (and it's quite complicated). Just put in the road geometries and netconvert does the rest.
Also, see https://sumo.dlr.de/docs/FAQ.html#i_made_changes_to_the_netxml-file_but_it_did_not_work_as_expected_why
