### ISSUE TITLE
change lane in sumo

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#12655]
Does sumo have a uniform lane change model instead of the default lane change model of instantaneous movement? In addition, if there is, how is the lane change trajectory calculated. How to get the position (x, y) of the next step vehicle during the lane change process?
**SUMO-version:1.14.1**

**operating system:Windows**

**Comment by namdre** [comment]
see https://sumo.dlr.de/docs/Simulation/SublaneModel.html

**Comment by a-123-du** [comment]
> see https://sumo.dlr.de/docs/Simulation/SublaneModel.html
I checked the lane change of sublane, but I didn’t see how it calculates the trajectory of the lane change process. Can you explain it in detail? I want to get the position coordinates of the car movement in each step of the lane change process. , how should I get it? Thank you very much!

**Comment by namdre** [comment]
The lateral movement is using constant lateral speed in the simple continous model whereas the sublane model has a concept of lateral acceleration and deceleration.
How about using **--fcd-output** or calling traci.vehicle.getPosition to get the positions?

**Comment by a-123-du** [comment]
> The lateral movement is using constant lateral speed in the simple continous model whereas the sublane model has a concept of lateral acceleration and deceleration. How about using **--fcd-output** or calling traci.vehicle.getPosition to get the positions?

When a car has the intention to change lanes, I want to predict the coordinates of its next position change from the beginning of the lane change to the end of the lane change. The above is my requirement, how should I implement it, is the sub-lane model feasible, and how to calculate the position of the vehicle in the process of changing lanes? Thank you!

**Comment by namdre** [comment]
the sublane model is less predictable since it may terminate an ongoing lanechange if circumstances dictate this. In contrast, the simple continuous model is well predictable.  The lateral change in each step is equal to the maneuver distance divided by the value of **--lanechange.duration**.

**Comment by a-123-du** [comment]
> the sublane model is less predictable since it may terminate an ongoing lanechange if circumstances dictate this. In contrast, the simple continuous model is well predictable. The lateral change in each step is equal to the maneuver distance divided by the value of **--lanechange.duration**.

is the sample sontinuous model is LC2013 you mean? Isn't this an instant-moving lane-changing model?

**Comment by namdre** [comment]
please read carefully: https://sumo.dlr.de/docs/Simulation/SublaneModel.html#simple_continuous_lane-change_model

**Comment by a-123-du** [comment]
> please read carefully: https://sumo.dlr.de/docs/Simulation/SublaneModel.html#simple_continuous_lane-change_model

Yes,I see.Is there no more detailed description of this model? Can it be used together with traci.vehicel.changelane()? I read in the document that "When using this model, vehicles will move with constant lateral speed to complete a maneuver in the specified time." What is the constant lateral speed?

**Comment by namdre** [comment]
as stated above: "The lateral change in each step is equal to the maneuver distance divided by the value of --lanechange.duration."

The model is compatible with vehicle.changeLane

**Comment by a-123-du** [comment]
> 如上所述：“每一步的横向变化等于机动距离除以--lanechange.duration的值。
> 
> 该模型与车辆兼容。

OK,I have anothe question.How to get the wheelbase of the vehicle (the distance between the front and rear wheel centers, v.l in the below picture) and the track width of vehicle (the distance between the left and right wheel centers,v.w in the below picture)?
![1677055845011](https://user-images.githubusercontent.com/54823725/220569635-dc2b24ec-8053-4b69-a470-9b26c10a9f74.png)

**Comment by namdre** [comment]
these things are not currently modeled in SUMO and you cannot get them
