### ISSUE TITLE
rpmbuilds fail due to python site-packages pushed to /usr/lib instead of /usr/lib64

### ISSUE THREAD

**Issue by RNippold** [eclipse/sumo#12667]
Some time after rev b7ace505f24 changes were made to CMakeLists.txt concerning the handling of python bindings (line 210, 211, 504 - 516). After these changes (rev in time of writing: 1eac7201e62) rpmbuild fails due to python site-packages been located in /usr/lib instead of /usr/lib64.

**SUMO-version:** rev 1eac7201e62

**operating system:** fedora 37

**Comment by behrisch** [comment]
seems to be solved, at least the obs builds are green again
