### ISSUE TITLE
SUMO gui windows on macOS hide after closing the colorwheel dialog

### ISSUE THREAD

**Issue by RobertHilbrich** [eclipse/sumo#12689]
Steps to reproduce on macOS:

- build SUMO from sources with clang14 on macOS (all deps installed via brew)
- start sumo-gui and load a scenario (e.g. Bologna)
- start the simulation
- open the colorwheel dialog
- click on "OK" to close dialog
- now the main window "hides" in the background
- it cannot be brought to foreground by clicking on "Xquartz" icon in the taskbar or using cmd-tab to switch to other windows
- only a click on the macOS "Windows" menu and selecting "Bring all windows to the foreground" brings back the sumo gui window

**SUMO-version:** v1.16.0

**operating system:** macOS Ventura 13.2.1 (22D68), XQuartz 2.8.5, Clang 14

**Comment by angelobanse** [comment]
This is a duplicate of https://github.com/eclipse/sumo/issues/12014

**Comment by RobertHilbrich** [comment]
Closing due to duplicate of #12014
