### ISSUE TITLE
modify TAZ edges with netedit

### ISSUE THREAD

**Issue by rummel123** [eclipse/sumo#12697]
Netedit should have the possibility to change the owning edges of a TAZ by edge attributes (as remove all edges with "disallowed=passenger").

**Comment by palvarezlopez** [comment]
Allow to select edges by TAZ

**Comment by namdre** [comment]
> Allow to select edges by TAZ
This is already implemented

Also a python tool for filtering exists:  https://sumo.dlr.de/docs/Tools/District.html#filterdistrictspy

**Comment by palvarezlopez** [comment]
There is already a way in netedit.
