### ISSUE TITLE
the shape point  in net.xml

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#12699]
Hello，I want to ask after fitting the trajectory through Bezier, what rules are the points (the point I circled in the pic)taken according to (shape value in net.xml)?
![2b1d40744a74da4942edda42d5b8548](https://user-images.githubusercontent.com/54823725/221343889-6b52aef6-7749-42e7-a4a8-f11bdee7ff58.png)

**SUMO-version:1.14**
**operating system:Windows**

**Comment by namdre** [comment]
it's a fixed number of evenly spaced points according to option **--junctions.internal-link-detail**
