### ISSUE TITLE
the maximum steering angle of the vehicle

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#12693]
How to know the maximum steering angle for a certain type of vehicle?
**SUMO-version:1.14**

**operating system:Windows**

**Comment by namdre** [comment]
steering angles are not modelled by SUMO. there is only `maxSpeedLat`.

**Comment by a-123-du** [comment]
What is maxSpeedLat?

**Comment by m-kro** [comment]
maxSpeedLat = maximal lateral speed, thus the speed orthogonal to the lane direction. This is used for lane changing.
