### ISSUE TITLE
the "reaction time" in krauss cfmodel

### ISSUE THREAD

**Issue by YangYuhua122121** [eclipse/sumo#12700]
I use krauss cfmodel to run the vehicle, and i know that krauss cfmodel uses reaction time as a parameter.
![image](https://user-images.githubusercontent.com/119411487/221348621-c625def6-deac-42ab-841c-1e1df2db5f0c.png)
 However,  I can't learn which parameter defined in vType represents the "reaction time". Is "tau", "action-step-length" or others? 

In addition, the "tau" seems to mean the "time headway" according to documentation. I know that krauss will calculate a safe speed for next step, but how the time headway limitation interacts with the safe speed to ensure the following car choose a proper speed in next step.

thank you!

**Comment by namdre** [comment]
the interaction between these values is explained at https://sumo.dlr.de/docs/Car-Following-Models.html#model_parameters
