### ISSUE TITLE
Where are the details on emissions model used in SUMO?

### ISSUE THREAD

**Issue by thinker310** [eclipse/sumo#12705]
Hello, I want to learn the calculation for the emissions in SUMO, but in the SUMO documentation there exist no details regards to the emission models, could you give me some references on the emission model including calculation formulas please?

**Comment by m-kro** [comment]
Have a look at this publication: [Second Generation of Pollutant Emission Models for
SUMO](https://core.ac.uk/download/pdf/31011113.pdf)
