### ISSUE TITLE
How can I use gpu to run this program,the efficient of sumo which just using cpu is not well

### ISSUE THREAD

**Issue by jinyuxinjinyuxin** [eclipse/sumo#12708]
Add your issue description here.

*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**

**Comment by m-kro** [comment]
Impossible, sorry. See #10433 .

**Comment by namdre** [comment]
Depending on your use case, the efficiency of sumo can be increased by fixing network problems or improving choice of model parameters or simulation options.

**Comment by keivanmoazami** [comment]
can you see this repo:
https://github.com/chrisblatchley/sumo-cuda/tree/master

is it possible to merge this repo ?

**Comment by namdre** [comment]
Despite the project description of 

>  An implementation of the SUMO traffic simulation tool suite using CUDA for GPU speedup

The code has actually nothing to do with SUMO and thus there is no way it can be merged.
