### ISSUE TITLE
taxi dispatch algorithm

### ISSUE THREAD

**Issue by radhityavirya** [eclipse/sumo#12706]
For the case of ride sharing, how is the difference in how the greedyShared and routeExtension dispatch algorithms work in taxis? In the experiments that I did, with the same coding routeExtension didn't give any results, whereas with greedyShared there are several people who can do ride sharing

**Comment by namdre** [comment]
routeExtension only allows shareing be picking up persons along the existing route and extending the existing route (without every doing detours). 
Greedy allows only two reservations to be shared but routeExtension permits an arbitrary number.

**Comment by radhityavirya** [comment]
Ok thank you for the help
