### ISSUE TITLE
the speed after changing lane

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#12707]
Hello，In the process of lane change, I set the speed of the vehicle to a fixed value and let him change the lane at a constant speed. When the lane change is over, why does his speed remain unchanged? How can SUMO control his speed instead of constant speed.Thank you very much.

**SUMO-version:1.14**

**operating system:Windows**

**Comment by namdre** [comment]
I would expect this answer to be easily found in the documentation. 
Since we're always looking for user feedback on the later, Please let me know what problems you encountered when looking this up.

**Comment by behrisch** [comment]
Closing for lack of feedback. Please add a comment if you have more information
