### ISSUE TITLE
movement on the y-axis of the coordinate system

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#12701]
Does SUMO support microscopic movement on the y-axis of the coordinate system? As shown in the figure, I want the vehicle to move according to the trajectory I calculated, but after I use the traci.vehicle.moveToXY() function, in the output fcd file, each step corresponds to the y value of the vehicle's trajectory point and my given The values are not the same. How to make the vehicle move smoothly?  pic1 is the trajectory coordinates I set, and pic2 is the coordinates of the movement of each step vehicle in my fcd output file, please check the movement process of the vehicle with id 'W-E_0', because I control 'W-E_0' '.Thank you very much.
![6d77835100d5855af4a3d4aed93e52b](https://user-images.githubusercontent.com/54823725/221349092-b04b648c-021a-48a2-901f-4b2787e886fe.png)
![7d754716ecf6a35b35164a465ef4a3c](https://user-images.githubusercontent.com/54823725/221349127-b05c7590-f0eb-41a7-a333-0e76e4a03bfa.png)

**SUMO-version:1.14**

**operating system:Windows**

**Comment by namdre** [comment]
the vehicle coordinate after calling moveToXY is influenced by the 'keepRoute' flag. See https://sumo.dlr.de/docs/TraCI/Change_Vehicle_State.html#move_to_xy_0xb4

with keepRoute=2 you should see the exact position that you requested in your fcd-output

**Comment by a-123-du** [comment]
> the vehicle coordinate after calling moveToXY is influenced by the 'keepRoute' flag. See https://sumo.dlr.de/docs/TraCI/Change_Vehicle_State.html#move_to_xy_0xb4
> 
> with keepRoute=2 you should see the exact position that you requested in your fcd-output

OK, thank you very much. But the angle of the car during the movement of the track point I set has not changed, because my track is the track of the car changing lanes, the angle must change during this process, but there is no change in the output fcd file, it has always been 90 degrees, what is going on here? 
![02d8c45a669cc3e33ba792383485736](https://user-images.githubusercontent.com/54823725/221353148-d582778c-c6e3-48c9-acc4-4f4b09a35ae7.png)

**Comment by namdre** [comment]
mvoements via moveToXY do not try to "guess" the maneuver that is being performed. Instead the normal road angle is used. You can override the angle by using the optional angle argument of moveToXY

**Comment by a-123-du** [comment]
> 通过 moveToXY 的 mvoements 不会试图“猜测”正在执行的操作。而是使用正常的道路角度。您可以使用 moveToXY 的可选角度参数覆盖角度
I wonder what is the meaning of angle in moveToXY? Is it the angle of the car during the movement? Why isn't this angle variable? Also, what should I do if I want to know the angle of the vehicle while moving, thanks a million.

**Comment by a-123-du** [comment]
> I wonder what is the meaning of angle in moveToXY? Is it the angle of the car during the movement? Why isn't this angle variable? Also, what should I do if I want to know the angle of the vehicle while moving, thanks a million.

I wonder what is the meaning of angle in moveToXY? Is it the angle of the car during the movement? Why isn't this angle variable? Also, what should I do if I want to know the angle of the vehicle while moving, thanks a million.
