### ISSUE TITLE
exclude short edges

### ISSUE THREAD

**Issue by ZJ726** [eclipse/sumo#12724]
Based on a.net.xml file, I want to remove all short edges (< 50m) or merge short edge with long edge in this network, I tried the following solution（netconvert） but nothing changed, what is wrong with my setup, or is there any other solution?

![image](https://user-images.githubusercontent.com/76982408/222058715-a55c8ced-f4e4-4a91-9e3e-8d80880cc811.png)

road network：
![image](https://user-images.githubusercontent.com/76982408/222059096-ad43e46e-ad19-4829-997e-2bbb2f46e830.png)

**SUMO-version:**1.8.0

**Comment by namdre** [comment]
You still need to set option **--geometry.remove** (option **--geometry.remove.min-length** is only a parameter for the former).
Even this will only merge edges at junctions that are *geometry-like* (i.e. not a real intersection).
For the latter, you may want to set **--junctions.join** to simplify certain types of multi-node intersections.
