### ISSUE TITLE
(the length between the front and rear wheels of the vehicle and the length between the left and right wheels of the vehicle

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#12723]
How to obtain the wheelbase (the length between the front and rear wheels of the vehicle) and the wheelbase (the length between the left and right wheels of the vehicle) of the vehicle? All I know so far is the total length and total width of the vehicle.Thank you very much!

**SUMO-version:1.14**

**operating system:Windows**

**Comment by namdre** [comment]
this is not modeled in sumo
