### ISSUE TITLE
Questions about "--fcd-output.max-leader-distance FLOAT"

### ISSUE THREAD

**Issue by FujieZhou** [eclipse/sumo#12722]
Hi,

I would like to know what the input value "FLOAT" of "--fcd-output.max-leader-distance" means. For example, what is the diffence between "FLOAT=300" and "FLOAT=1000"?

The Scend question about the "vehicle_leaderGap" output of "--fcd-output.max-leader-distance": If vehicle dimensions are taken into account when calculating the "vehicle_leaderGap".

Best Regards,
Fujie

**Comment by FujieZhou** [comment]
The gap is the distance between the rear of a lead-vehicle and the front of a following-vehicle to calculate TTC(Time to Collision).

**Comment by namdre** [comment]
1. if there is a leader vehicle at a distance between 301m and 1000m then it may or may not be found with max-leader-distance of 300 but it will definitely found with a value of 1000.
2. the distance is front-bumper-to-leader-back-bumper (so it varies with the length of the leader vehicle)

**Comment by FujieZhou** [comment]
Thanke you for your reply.

There is another question about the "vehicle_pos" output: Is the position of a vehicle the geometric center?

Best Regards,
Fujie

**Comment by namdre** [comment]
it is the center of the front-bumper

**Comment by FujieZhou** [comment]
OK, I understand.

Thank you for your prompt reply.
