### ISSUE TITLE
sumo-gui is missing some FFMPEG DLL

### ISSUE THREAD

**Issue by bcoueraud87** [eclipse/sumo#12736]
Some FFMPEG DLL are missing in the _bin_ directory of _sumo-gui_: _avcodec-58 avformat-58 avutil-56 swscale-5 swresample-3_. One can add them manually from SUMOLibraries but this should be automated.

SUMOLibraries commit number: 7632fdefd1e7f335221c77c6961ceac68bb87753
SUMO commit number: d196e53626f5c0f136d3c7fc1b6885cd07178fae

**Comment by palvarezlopez** [comment]
Fixed after adding new version in https://github.com/eclipse/sumo/issues/12750
