### ISSUE TITLE
invalid edge ordering with curved input

### ISSUE THREAD

**Issue by meco2020** [eclipse/sumo#12735]
Hello, when I use netconvert to convert OSM to net file, I found a strange problem.
1. I use osm2plain.bat to split the osm file into nod.xml, edg.xml, etc., and then use osm2plain2net.bat  synthesize the net file(the file name is osm2plain2net.net.xml) through nod.xml, edg.xml, etc. 
![image](https://user-images.githubusercontent.com/65943065/222370432-d424b3ce-ec4f-47f2-8b6b-302e8ae79b98.png)

2. I use osm2net.bat to convert osm file to net file(name is osm2net.net.xml) directly 
![image](https://user-images.githubusercontent.com/65943065/222370743-9afd1ee0-35ea-486b-a6db-c39310d0acd6.png)

I guess it is because the netconvert plug-in has some errors in the logic of the osm file to the con.xml，I also see the connection file, the first connection's fromLane and toLane is wrong. 
![image](https://user-images.githubusercontent.com/65943065/222372918-d08404bf-54c7-45a5-9476-993afa6f9390.png)

**Comment by namdre** [comment]
The mentioned batch files *osm2plain.bat* and *osm2net.bat* are not part of the SUMO distribution and thus any encountered problems may be outside the scope of this issue tracker.  Where do these tools come from?
The recommended way to import OSM data is documented at: https://sumo.dlr.de/docs/Networks/Import/OpenStreetMap.html

**Comment by meco2020** [comment]
Sorry about that I forget to upload these files
the bat files you mentioned are just some commands about netconvert. 
[Q_netconvert.zip](https://github.com/eclipse/sumo/files/10870536/Q_netconvert.zip)

**Comment by namdre** [comment]
The key difference between the two networks is that the direct import (`netconvert --osm-files prepared.osm -o osm2net.net.xml`) didn't set option **--geometry.remove**. Thus it contains many short edges with individual edge being straight.

The plain-output on the other hand was using **--geometry.remove** and this causes edge *1* to curve back on itself. At some point netconvert uses the *total angle* (from the start to the end of the edge) when sorting edges and this is causing the problem.
