### ISSUE TITLE
OSM Web Wizard doesn't launch scenario in sumo-gui 

### ISSUE THREAD

**Issue by palikao** [eclipse/sumo#12741]
When I generate scenario, then nothing happens..

**SUMO-version: 1.16**

**operating system: macOS 10.14**

**Comment by namdre** [comment]
The most likely reason is that the OSM servers rejected your download request due to size or being otherwise busy.
There should be a command line window in the background that logs what the wizard is doing.  Please copy and paste the contents of that window if the messages are unclear.

**Comment by palikao** [comment]
I tried launching WW from Terminal:

`Traceback (most recent call last):
  File "/usr/local/Cellar/sumo/1.16.0/share/sumo/tools/osmWebWizard.py", line 589, in <module>
    main(get_options())
  File "/usr/local/Cellar/sumo/1.16.0/share/sumo/tools/osmWebWizard.py", line 584, in main
    server = SimpleWebSocketServer(options.address, options.port, OSMImporterWebSocket)
  File "/usr/local/Cellar/sumo/1.16.0/share/sumo/tools/webWizard/SimpleWebSocketServer.py", line 608, in __init__
    self.serversocket.bind(hostInfo[0][4])
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 48] Address already in use`

**Comment by namdre** [comment]
you first need to close the old version of the webWizard that is still running somewhere (it's blocking the required port).

**Comment by palikao** [comment]
I have not any old version! how can I check it..?

**Comment by namdre** [comment]
try `ps -aux | grep osmWebWizard.py` then kill the offending process

**Comment by palikao** [comment]
> try `ps -aux | grep osmWebWizard.py` then kill the offending process

`ps: No user named 'x'`

**Comment by palikao** [comment]
I did `pip3 install -U certifi` and worked, then I tried again, and this is the result:

`python3 /usr/local/Cellar/sumo/1.16.0/share/sumo/tools/osmWebWizard.py 
Building scenario in '/Users/stefano/2023-03-02-18-12-03'.
Downloading map data
504 Gateway Timeout
Traceback (most recent call last):
  File "/usr/local/Cellar/sumo/1.16.0/share/sumo/tools/osmWebWizard.py", line 499, in build
    builder.build()
  File "/usr/local/Cellar/sumo/1.16.0/share/sumo/tools/osmWebWizard.py", line 194, in build
    raise RuntimeError("Download failed")
RuntimeError: Download failed

Recovering
Recovering
Recovering
Recovering
Recovering
Recovering
Recovering
Recovering
Recovering
Recovering

`

**Comment by namdre** [comment]
There is a bit of randomness involved due to the load situation of the OSM servers. If they are busy you are more likely to get a timeout for your request. 
You can also obtain osm files from other sources though:
- https://planet.openstreetmap.org/
- https://sesam.co4e.com/

**Comment by palikao** [comment]
Yes, but not the calculation! OWW does it too!

**Comment by namdre** [comment]
If you have even a single osmWebWizard scenario, you can replace the osm_bbox.osm.xml file with a file obtained elsewhere,
then rebuild the whole scenario by calling
`netconvert -c osm.netccfg`
`polyconvert -c osm.polycfg`
`build.bat`

**Comment by palikao** [comment]
Of course! 
I mean the calculation of movements and displacements..

**Comment by palikao** [comment]
I'm again in trouble..

**Comment by namdre** [comment]
you could try https://sesam.co4e.com/dashboard/ which has an OSM mirror in the background and lets you download a webwizard scenario.

**Comment by Muhammadusmanmalik701** [comment]
(base) C:\Program Files (x86)\Eclipse\Sumo\tools>python osmWebWizard.py
Building scenario in 'C:\Program Files (x86)\Eclipse\Sumo\tools\2026-05-07-22-49-50'.
Downloading map data
Traceback (most recent call last):
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\osmWebWizard.py", line 539, in build
    builder.build()
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\osmWebWizard.py", line 203, in build
    raise RuntimeError("Download failed")
RuntimeError: Download failed

Download failed Recovering
Download failed Recovering
Download failed Recovering
Download failed Recovering

i am also facing the same issue

**Comment by namdre** [comment]
@Muhammadusmanmalik701 The OSM server recently tightened it's rules for downloading content and this broke older versions of the wizard. You need to upgrade to the latest development version: https://sumo.dlr.de/docs/Downloads.php#nightly_snapshots
