### ISSUE TITLE
Error: Disconnected walk for person '[id of person]'

### ISSUE THREAD

**Issue by m-cak** [eclipse/sumo#12744]
"Error: Disconnected walk for person '[id of person]'"

This is the kind of error message that I get every other 100th timestep in the simulation of a bigger city from OSM. I already validated (--validate) the generated pedestrian trips. It seems the network of the the scenario is broken. Is there a way to fix this programmatically *without* having to change any of the scenario xml files (since the city is quite large) so the simulation does not end?

SUMO-version: 1.16.0

operating system: macOS Ventura 13.2.1

**Comment by namdre** [comment]
This sounds like a bug that must be fixed on the SUMO side (plausibly, at the validation stage).
Can you provide files for reproducing this issue?
Ideally you could reduce your traffic to the minimum necessary amount that triggers the error (maybe even one person is enough).

**Comment by m-cak** [comment]
I simply used this scenario:
https://github.com/TUM-VT/sumo_ingolstadt

And added these trips...
[persons.trips.xml.txt](https://github.com/eclipse/sumo/files/10889208/persons.trips.xml.txt)
[vehicles.trips.xml.txt](https://github.com/eclipse/sumo/files/10889209/vehicles.trips.xml.txt)

...to the .sumocfg:
[24h_sim.sumocfg.txt](https://github.com/eclipse/sumo/files/10889205/24h_sim.sumocfg.txt)

**Comment by namdre** [comment]
@m-cak note, that the Ingolstadt network has many signalized pedestrian crossings that stay 'red' all the time. Apparently, the network wasn't tested for detailed pedestrian simulation.

**Comment by namdre** [comment]
also, there are still 3 disconnected vehicle trips in your input but these can be found and filtered by running them through duarouter with `duarouter -r vehicles.trips.xml -n ingolstadt_24h.net.xml -o validated.trips.xml --write-trips --ignore-errors`

**Comment by m-cak** [comment]
@namdre Thank you so much! I will consider everything you stated.

**Comment by behrisch** [comment]
I added some remarks concerning pedestrians and traffic lights to the readme of the ingolstadt scenario
