### ISSUE TITLE
A problem between netedit and sumo-gui

### ISSUE THREAD

**Issue by zhoupeng0427** [eclipse/sumo#12755]
I wanted to modify the shape of the intersection, so I directly changed the shape of the xml file, saved it and opened it with netedit without any change. 
Only when I opened the gui could I see the change. I wonder if this bug can be fixed. Here are the xml files before and after the ### changes.Since I cannot transfer the xml format file, I converted it to txt file.
![QQ截图20230304161217](https://user-images.githubusercontent.com/103175365/222885676-c0b7a0f1-a1c2-47a0-acc3-9c9445d483b7.jpg)
[suzhounet.txt](https://github.com/eclipse/sumo/files/10887860/suzhounet.txt)
[suzhounet_modified.txt](https://github.com/eclipse/sumo/files/10887861/suzhounet_modified.txt)

**Comment by namdre** [comment]
1. https://sumo.dlr.de/docs/FAQ.html#i_made_changes_to_the_netxml-file_but_it_did_not_work_as_expected_why
2. you can set a custom shape in netedit: https://sumo.dlr.de/docs/Netedit/neteditPopupFunctions.html#junction

also, if you ever wish to upload xml files, puting them in a zip archive is usually the easiest method.

**Comment by zhoupeng0427** [comment]
> 1. https://sumo.dlr.de/docs/FAQ.html#i_made_changes_to_the_netxml-file_but_it_did_not_work_as_expected_why
> 2. 您可以在Netedit：https://sumo.dlr.de/docs/Netedit/neteditPopupFunctions.html#junction 中设置自定义形状
> 3. 如果只想放大交汇点大小，可以直接更改“半径”属性
> 
> 此外，如果您希望上传XML文件，将它们放在zip存档中通常是最简单的方法。

Thanks for your answer!
1. We found that the map crawled by osm was not very accurate, so we wanted to carry out a high-precision map Secondary development.There are many intersections to modify, so it is difficult to modify with netedit
2. We used the intersection shape data extracted from gis to replace the shape attribute in xml file, so we encountered this situation. netedit does not show the modified shape of the intersection.
![QQ截图20230304212337](https://user-images.githubusercontent.com/103175365/222905586-983cf3f3-b693-45e3-8b48-375f98d8055e.jpg)
10/5000
[翻译](javascript:;)
[net.xml.zip](https://github.com/eclipse/sumo/files/10888485/net.xml.zip)
Attached is the road network before and after modification
3. Do you have the function of directly modifying xml to synchronize

**Comment by namdre** [comment]
Yes. See https://sumo.dlr.de/docs/Tutorials/ScenarioGuide.html#modifying_the_network

**Comment by namdre** [comment]
Junction shapes aren't part of OSM and any shapes you see are guessed by netconvert. If you encounter systematic errors in the junction shape generation, please let me know so netconvert can be improved. 
If the junction sizes are all to small you can also increase the default radius with netconvert option **--default.junctions.radius**

**Comment by zhoupeng0427** [comment]
> Junction shapes aren't part of OSM and any shapes you see are guessed by netconvert. If you encounter systematic errors in the junction shape generation, please let me know so netconvert can be improved. If the junction sizes are all to small you can also increase the default radius with netconvert option **--default.junctions.radius**

Thank you very much for your detailed answer. I'll give it a try.
