### ISSUE TITLE
Why changeLanes after executeMovement in MSNet.cpp?

### ISSUE THREAD

**Issue by ckh0715** [eclipse/sumo#12759]
What happen if I swap the order of myEdges->changeLanes and myEdges->executeMovements? I want to do this, but I'm afraid of creating some bugs.

**Comment by namdre** [comment]
The current order is mostly for historical reason. We even have long-standing plans to change this ourselves:
see #3665

If you do swap things, the only thing that will probably break is the code for running with actionStepLength != simStepLength
