### ISSUE TITLE
Compile error in GNEApplicationWindow.cpp Line 454

### ISSUE THREAD

**Issue by atellyro** [eclipse/sumo#12757]
Compile error

[ 96%] Building CXX object src/netedit/CMakeFiles/netedit.dir/GNEApplicationWindow.cpp.o
In file included from /dosd/src/opensource/Sumo/sumo-git-co/sumo/src/netedit/GNEApplicationWindow.cpp:61:
/dosd/src/opensource/Sumo/sumo-git-co/sumo/build/cmake-build/src/netedit/templates.h:454:45: error: expected primary-expression before ‘;’ token
  454 | const std::string addStops2RoutesTemplate = ;
      |                                             ^
make[2]: *** [src/netedit/CMakeFiles/netedit.dir/build.make:108: src/netedit/CMakeFiles/netedit.dir/GNEApplicationWindow.cpp.o] Fehler 1

**SUMO-version:**
Latest GitHub as of 2023-03-05

**operating system:**
Ubuntu 22.10

**Comment by namdre** [comment]
templates.h is generated by the python script `sumo/tools/build/templates.py` and the error suggests that the script failed on your end.
Try running `/path/to/sumo/tools/build/templates.py  /path/to/sumo` (using whatever is the path to sumo on your system) and see whether you get an error.

**Comment by atellyro** [comment]
According to https://sumo.dlr.de/docs/Installing/Linux_Build.html#building_the_sumo_binaries_with_cmake 
I have a source directory <build-sumo-co>/sumo and a build directory <build-sumo-co>/sumo/build/cmake-build
I have tried the script in both directories, even in <build-sumo-co>/sumo/build/cmake-build(src/netedit, no success

This is my output
> ../../../../tools/build/templates.py ../../../../bin/sumo
Obtaining sumo template
Obtaining 'generateRerouters' tool template
Obtaining 'addStops2Routes' tool template

My expectation is that a clean build with a newly set up build/cmake-build directory should work out of the box

**Comment by namdre** [comment]
> My expectation is that a clean build with a newly set up build/cmake-build directory should work out of the box

Of course. Normally this script runs automatically without problems. Can you post the contents of `...sumo/build/cmake-build/src/netedit/templates.h` ?

**Comment by tasosb** [comment]
This is probably related to recent changes in templates.py https://github.com/eclipse/sumo/commit/88a07eb9b09348844f1d4f16873842eab8554dec and options.py in https://github.com/eclipse/sumo/commit/cf9bfb8ca87e9e0eea4f2fc7403f80e9a9a920bc.

The reason could be a stable version already installed, in which the SUMO_HOME env variable is pointing at.
`generateRerouters` works because it is in the (new) tools folder itself, which is prioritized against SUMO_HOME
`addStops2Routes` is on the tools/routes folder, thus SUMO_HOME takes precedence over the relative import made on the file itself.

**Comment by namdre** [comment]
Thanks to Harald, I got a sample of a broken templates.h. 
The sumo-template is fine but the tool template looks like this:
```
const std::string addStops2RoutesTemplate = ;
```

**Comment by namdre** [comment]
@atellyro please update `templates.py` to the latest dev version and post any errors it generations after the *obtaining ... template* section.

**Comment by tasosb** [comment]
Follow-up to my previous comment if it can be of any help: 
Deleting the old SUMO_HOME environment variable (pointing to C:\Program Files (x86)\Eclipse\Sumo) (or setting the variable to the new directory), restarting and then building again solved the problem (on Windows)

**Comment by namdre** [comment]
Running templates.py requires and recent version of the sumolib library (tools\sumolib) du to changes in handling of the **--save-template** option. One of the tools that we're currently generating templates for (generateRerouters.py) imports sumolib based on the SUMO_HOME variable. If that variable points to an older version, saving the template fails. After 2996d6f this no longer kills the build. (the generated templates are optional for proper netedit functioning).

**Comment by atellyro** [comment]
This changes does not work for me
My proposal is to make the output of  formatToolTemplate in template.py more stable

diff -c1 tools/build/templates.py tools/build/templates.py-orig
*** tools/build/templates.py    2023-03-06 12:02:04.868860800 +0100
--- tools/build/templates.py-orig       2023-03-06 11:29:14.599071600 +0100
***************
*** 72,75 ****
      # update last line
-     if templateStr == '':
-         templateStr = '""'
      templateStr += ';\n'
