### ISSUE TITLE
question for merging edges

### ISSUE THREAD

**Issue by SongKun2023** [eclipse/sumo#12756]
Add your issue description here.
Hello, sir. How can I merge two connecting edges? In other words, I want to delete the connection that is between two edges and keep the two edges.

**Comment by namdre** [comment]
With netconvert option **--geometry.remove**. See also: https://sumo.dlr.de/docs/Networks/Import/OpenStreetMap.html#recommended_netconvert_options

**Comment by SongKun2023** [comment]
Thank you sir, I will try.
