### ISSUE TITLE
Using of routesampler.py

### ISSUE THREAD

**Issue by mehmetnedimyavuz** [eclipse/sumo#12764]
Hello,
I have a network that contains three intersections consecutively. I have traffic counts for these intersections in terms of different vehicle types with 15-min intervals. According to searching documentation, the right tool is routesampler to create traffic demand. As a first step, I used to randomTrips.py to obtain candidate routes.
1- python tools/randomTrips.py -n deneme2.net.xml -r deneme2.rou.xml --fringe-factor 1e100 (I used to increased fringe factor to prevent creating vehicles on middle edges.)
 After this step, I used to generateTurnRatios.py to obtain turn-count data with candidate route file.
2- python tools/turn-defs/generateTurnRatios.py -r deneme2.rou.xml -o input_turns.xml -i 900
I obtained turn-count data format with 15-min interval. While I investigate this file, how counts are distributed into time intervals?
 and how I ensure matching between the real situation and simulation? Do I need examination step by step?

**Comment by namdre** [comment]
Since you have your own counting data, step 2 is not appropriate.
Assuming you have local counts (rather than turn counts) you need to create an edgeData file with appropriate count values 
and intervals.
For the format, see https://sumo.dlr.de/docs/Tools/Turns.html#edge_counts
You can also process your counts by way of csv input: https://sumo.dlr.de/docs/Tools/Detector.html#edgedatafromflowpy

For dealing with the different vehicle types, see https://sumo.dlr.de/docs/Tools/Turns.html#multiple_vehicle_types)

**Comment by mehmetnedimyavuz** [comment]
Thank you for help @namdre. I have turn counts for each  intersection. In this regard, I have to create  an turn-count data format with appropriate counts and interval (https://sumo.dlr.de/docs/Tools/Turns.html#turn_counts) for each vehicle type. If step 2 is not appropriate, Do I have to create manually or prepare custom script for this? 
Regards.

**Comment by namdre** [comment]
Depending on the amount of data either one of these might be the fastest / best way
- create the file visually with netedit (using data mode-> edgeRelation mode)
- write out the xml file by hand
- write a custom script that generates the xml file based on your data

**Comment by mehmetnedimyavuz** [comment]
I have one more question about this topic @namdre. I run randomTrips.py with default begin and end value and then, it creates 3600 candidate routes. If I increases end time, more candidate routes would be created. At this point, how can I determine obtaining enough number of candidate routes?

**Comment by namdre** [comment]
routeSampler tells you about the quality of the found solution (GEH value). If routeSampler doesn't find a good solution,  Increasing the number of candidate routes may help. See also https://en.wikipedia.org/wiki/GEH_statistic
