### ISSUE TITLE
traci4matlab not updated

### ISSUE THREAD

**Issue by suryatejatalluri** [eclipse/sumo#12776]
I am using latest sumo version and I am using Traci4Matlab to control the vehicles. 

I am adding new vehicles to the simulation using `traci.vehicle.add` and trying to update their speed to make them start at 10m/s and move them at the constant speed. But the vehicle always starts with zero speed even when I mention initial speed using `departSpeed` when adding vehicle. It is not following the speed set using  `traci.vehicle.setSpeed`. I found some issues in git mentioning about setPreviousSpeed that can be used to set vehicle speed, but they are not available in Traci4Matlab.

I have found that traci4Matlab is not updated for 2 years and the functions in `traci.vehicle` are not updated from 5 years. How to access latest traci apis in MATLAB

**Comment by suryatejatalluri** [comment]
> The traci4Matlab interface is not part of SUMO itself but a contribution of third party (see the traci4Matlab [Github page](https://github.com/pipeacosta/traci4matlab)). How does your call to `traci.vehicle.add` look like? I am not sure how Matlab treats the optional parameters (they could be positional).
> 
> Remember that `traci.vehicle.setSpeed` has to be called for every time step you want it to take effect.

I am adding vehicle like this `traci.vehicle.add('10',routeID,departSpeed='10')` I found that additional arguments for `traci.vehicle.add` can be provided in `argumentName = value` format.

I am doing `traci.vehicle.setSpeed` at every time step and checking the speed using `traci.vehicle.getSpeed` after `traci.simulation.step()`, it is showing near zero speed

**Comment by m-kro** [comment]
@suryatejatalluri  Could you please provide an example scenario including the SUMO files as well as your MATLAB script?

**Comment by behrisch** [comment]
@suryatejatalluri The best way to go forward here is to install the python client and then use this one from inside matlab. You only need Python on your system. Then you can do `pip install traci` and from now on you can use all functions documented in the TraCI API in matlab by just prepending them with a `py.` for instance `py.traci.start`.
