### ISSUE TITLE
recheck access for non pedestrian network

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#12774]
If gtfs is mapped to a network without pedestrian infrastructure there are wide range access connections to the train and even the bus stops because many streets do not have lanes allowing pedestrian. Probably there should not be access in this case, it is just questionable how to detect this automatically.

**Comment by behrisch** [comment]
I think it is probably more useful to disable access generation altogether in this case. If the network is not useful for pedestrians anyway why include access?

**Comment by namdre** [comment]
You are right. Yet, even if the network allows pedestrians somewhere far away, we probably wouldn't want to build access either.
