### ISSUE TITLE
pedestrian maxSpeed

### ISSUE THREAD

**Issue by callmorn** [eclipse/sumo#12786]
Whatever the pedestrian maxSpeed value set in the rou.xml file is, it is equal to 10.438888888888888 via traci.person.getMaxSpeed().

*If possible, upload an example that shows your problem.*

        <vType id="fwd0" vClass="pedestrian" width="0.7" length="0.35" minGap="0.2" maxSpeed="1.18146025765" guiShape="pedestrian" color="blue"/>
        <person id="fwd0" type="fwd0" depart="1" >
            <walk from="NC" to="CS"/>
        </person>
        <vType id="fwd1" vClass="pedestrian" width="0.7" length="0.35" minGap="0.2" maxSpeed="1.46034168036" guiShape="pedestrian" color="blue"/>
        <person id="fwd1" type="fwd1" depart="3" >
            <walk from="NC" to="CS"/>
        </person>

fwd0 10.438888888888888
fwd1 10.438888888888888

**SUMO-version:** 1.16.0

**operating system:** Win11

**Comment by namdre** [comment]
regression in 1.15.0 via the introduction of `desiredMaxSpeed` (#11102). The actual speed comes out correctly but TraCI doesn't report the relevant number anymore.
