### ISSUE TITLE
OSM Web Wizard net showing lane to lane connections not included in OSM turn:lanes

### ISSUE THREAD

**Issue by jalemann** [eclipse/sumo#12785]
When using the OSM Web WIzard to generate the net for an intersection, a lane can end up with more lane to lane connections in the net than given by the `turn:lanes`-Tag in OSM.

Example:
[This way in OSM](https://www.openstreetmap.org/way/224189871#map=19/52.13831/11.64519) has the Tag `turn:lanes=left|through;right`, meaning there are two lanes (separated by `|`) where the first only allows for turning left while the second allows for going straight or right.
However if the same intersection is used to generate a net using the OSM Web Wizard, the first lane is allowed to turn left and also to do a U-turn and to go straight (marked with blue rectangle in screenshot).
<img width="855" alt="SCR-20230312-qaqp" src="https://user-images.githubusercontent.com/58050402/224561427-10d10ebb-6db1-4aa1-86c9-c86018dff093.png">

**SUMO-version:**
1.16.0

**operating system:**
MacOS 13.2.1

**Comment by m-kro** [comment]
The [OSM import option](https://sumo.dlr.de/docs/netconvert.html#formats) `--osm.turn-lanes` is off by default and probably not set currently in OSMWebWizard...

**Comment by jalemann** [comment]
@m-kro Ah I see, thank you! I thought that was a bug, closing the issue.

**Comment by namdre** [comment]
I dimly recall there being a reason why we didn't activate it by default. I think for complicated lane arrangements (i.e. bike, car, bike) the option **--osm.turn-lanes** produces invalid results at the moment.
