### ISSUE TITLE
Cannot locate sumo.exe file after complete successful installation

### ISSUE THREAD

**Issue by subhrajit93** [eclipse/sumo#12784]
I have followed the instructions thoroughly for SUMO installation in **macos (ventura 13.2.1)**

**"/c/Users/user/src/sumo-1.8.0/bin/sumo.exe -c erlangen.sumo.cfg"** ---This is the command line to start SUMO and run an example. I edited it according to my system's environment:
**../Downloads/sumo/bin/sumo.exe -c erlangen.sumo.cg.** [_after setting the directory to my veins folder_.]

BUT THIS IS NOT WORKING! It is saying:
"zsh: no such file or directory: ../Downloads/sumo/bin/sumo.exe"

I have installed sumo in Downloads folder and renamed the file from 'sumo-1.16.0' to 'sumo'

I set the path for SUMO_HOME as **'export SUMO_HOME=../Downloads/sumo'** in bash.

**SIDE NOTE**---> The path stated in the caveats section of the brew install sumo command was : 
**export SUMO_HOME="/usr/local/opt/sumo/share/sumo"** but I thought it is not the absolute path for my specific setup so I changed it to the one I mentioned above.

**Comment by namdre** [comment]
.exe files are exclusive to the windows operating system. On mac the binaries are named 'sumo', 'sumo-gui' etc.

**Comment by subhrajit93** [comment]
Thank you so much!

 So how can I connect veins and sumo?
 The command mentioned in the installation guide is :
**/c/Users/user/src/sumo-1.8.0/bin/sumo.exe -c erlangen.sumo.cfg**

Inside sumo/bin folder there is only one file named '**start-command-line.bat**'

**Comment by namdre** [comment]
try `sumo -c erlangen.sumo.cfg`

**Comment by subhrajit93** [comment]
Tried but giving the same error. I am almost losing hope. :(

**Comment by subhrajit93** [comment]
I even tried installing it in windows. My luck is so tough right now that, even omnet is not getting installed 100% accurately. So I am back in mac again. Next I will try ubuntu in near future. I need some simulated results for DDOS attack in VANET environment. Help please if you can.
