### ISSUE TITLE
Can you tell me the meaning of the value?

### ISSUE THREAD

**Issue by SongKun2023** [eclipse/sumo#12783]
Add your issue description here.
Hello, sir, I get the edg.xml by using "--plain-output-prefix" in netconvert, but I don't know the meaning of the value in lane element.
The screenshot is as follows:

![_UCRAV9A~P%IF5$_KKK8B44](https://user-images.githubusercontent.com/97946646/224488034-000ae112-f7c7-46b1-81a0-606e4c2f80eb.png)

**Comment by namdre** [comment]
see https://sumo.dlr.de/docs/Networks/Import/OpenStreetMap.html#relationship_between_osm_ids_and_sumo-ids

**Comment by SongKun2023** [comment]
thank you
