### ISSUE TITLE
support multiple (different) vTypeDistributions that share types

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#12799]
right now, there is only a single probability value per type. Instead, vTypeDistributions should get a new attribute to override probabilities 

(new attribute `probabilities` to be used together with `vTypes`), similar to routeDistribution.

**Comment by ambuehll** [comment]
wow, that was fast! :) 
Thanks!

**Comment by behrisch** [comment]
@namdre @palvarezlopez Does this still need netedit support?

**Comment by namdre** [comment]
also #12846
