### ISSUE TITLE
Location of the code for SSMs computation

### ISSUE THREAD

**Issue by QilinTang** [eclipse/sumo#12792]
Hi guys, I want to edit the code for SSMs (mainly TTC and PET) calculation but just cannot find the location of the relevant code. Could someone please help me out? Looking for the reply :)

**Comment by m-kro** [comment]
No problem, have a look at the file [src/microsim/devices/MSDevice_SSM.cpp](https://github.com/eclipse/sumo/blob/main/src/microsim/devices/MSDevice_SSM.cpp).
