### ISSUE TITLE
ignore-route-errors + public transport routes

### ISSUE THREAD

**Issue by ambuehll** [eclipse/sumo#12809]
I have the following scenario:
1. I generate pt-lines/stops etc. from gtfs
2. I modify the network by removing some links, which also have a bus stop matched.
3. Understandably, I get the following error:
`Error: The lane 73906957#5_0 to use within the busStop 'gen:23026:1277:1:51_0' is not known.`

Any chance that this could be ignored when routing pt vehicles with `ignore-route-errors`?

**SUMO-version:** 1.16.0

**Comment by namdre** [comment]
It seems this isn't really about a route error but rather about loading infrastructure that doesn't match the network.
The proper fix is to load / save the busStops while modifying the infrastructure (either in netedit or in netconvert). This shoud already be working.

**Comment by ambuehll** [comment]
yes, you're right. let me check via netconvert. Thanks!
