### ISSUE TITLE
OpenDRIVE: access (allow/disallow)

### ISSUE THREAD

**Issue by m-kro** [eclipse/sumo#12804]
Introduced in OpenDRIVE v.1.4 and extended in v.1.5.

VuV group is interested in it.

**Comment by namdre** [comment]
- no tests are referenced by this ticket 
- internal test SanFranciso fails because the implementation breaks compatibility with version 1.4 (attribute 'rule' does not exist in that version and is implicitly `allow`)

**Comment by m-kro** [comment]
Removed predecessor propagation to comply with current tests. Turning loops will now be built by default if the permissions change in the middle of an edge.
