### ISSUE TITLE
There was a problem installing the sumo program.

### ISSUE THREAD

**Issue by moneymined** [eclipse/sumo#12813]
**I use homebrew to install the sumo program, but in the Git Cloning and Building part, cmake --build. --parallel$(sysctl -n hw.ncpu) This part displays an error as shown below.**

**I did it in order through https://sumo.dlr.de/docs/Installing/MacOS_Build.html.**

```
[ 97%] Linking CXX executable /Users/gimsuyeon/sumo/bin/testmicrosim

Undefined symbols for architecture x86_64:

Undefined symbols for architecture x86_64:

  "typeinfo for testing::Test", referenced from:

      typeinfo for Boundary_test_method_add_Test in BoundaryTest.cpp.o

      typeinfo for Boundary_test_method_add_multiple_Test in BoundaryTest.cpp.o

      typeinfo for Boundary_test_method_getCenter_Test in BoundaryTest.cpp.o

      typeinfo for Boundary_test_method_getWidthHeight_Test in BoundaryTest.cpp.o

      typeinfo for Boundary_test_method_around_Test in BoundaryTest.cpp.o

      typeinfo for Boundary_test_method_overlapsWith_Test in BoundaryTest.cpp.o

      typeinfo for Boundary_test_method_crosses_Test in BoundaryTest.cpp.o

  "typeinfo for testing::Test", referenced from:

      typeinfo for StringTokenizer_test_split_with_whitechar_Test in StringTokenizerTest.cpp.o

      typeinfo for StringTokenizer_test_split_with_newline_Test in StringTokenizerTest.cpp.o

      typeinfo for StringTokenizer_test_split_with_x_Test in StringTokenizerTest.cpp.o

      typeinfo for StringTokenizer_test_split_any_char_Test in StringTokenizerTest.cpp.o

      typeinfo for StringTokenizer_test_method_reinit_Test in StringTokenizerTest.cpp.o

      typeinfo for StringTokenizer_test_method_size_Test in StringTokenizerTest.cpp.o

      typeinfo for StringTokenizer_test_method_front_Test in StringTokenizerTest.cpp.o

      ...

ld: symbol(s) not found for architecture x86_64

      ...

ld: symbol(s) not found for architecture x86_64

clang: error: linker command failed with exit code 1 (use -v to see invocation)

clang: error: linker command failed with exit code 1 (use -v to see invocation)

make[2]: *** [/Users/gimsuyeon/sumo/bin/testgeom] Error 1

make[2]: *** [/Users/gimsuyeon/sumo/bin/testcommon] Error 1

make[1]: *** [unittest/src/utils/geom/CMakeFiles/testgeom.dir/all] Error 2

make[1]: *** Waiting for unfinished jobs....

make[1]: *** [unittest/src/utils/common/CMakeFiles/testcommon.dir/all] Error 2

Undefined symbols for architecture x86_64:

  "typeinfo for testing::Test", referenced from:

      typeinfo for MFXWorkerThread_test_init_Test in MFXWorkerThreadTest.cpp.o

      typeinfo for MFXWorkerThread_test_get_all_Test in MFXWorkerThreadTest.cpp.o

ld: symbol(s) not found for architecture x86_64

clang: error: linker command failed with exit code 1 (use -v to see invocation)

make[2]: *** [/Users/gimsuyeon/sumo/bin/testfoxtools] Error 1

make[1]: *** [unittest/src/utils/foxtools/CMakeFiles/testfoxtools.dir/all] Error 2

Undefined symbols for architecture x86_64:

  "typeinfo for testing::Test", referenced from:

      typeinfo for MSEventControl_test_method_execute_Test in MSEventControlTest.cpp.o

      typeinfo for MSCFModelTest in MSCFModelTest.cpp.o

      typeinfo for MSCFModel_IDMTest in MSCFModel_IDMTest.cpp.o

ld: symbol(s) not found for architecture x86_64

clang: error: linker command failed with exit code 1 (use -v to see invocation)

make[2]: *** [/Users/gimsuyeon/sumo/bin/testmicrosim] Error 1

make[1]: *** [unittest/src/microsim/CMakeFiles/testmicrosim.dir/all] Error 2

make: *** [all] Error 2
```

**I don't know how to fix the error.
I desperately need your help.**

**I'm using MacBook Pro.
The macos version is Ventura 13.0.1.**

**Comment by angelobanse** [comment]
Did you follow the "Optional Steps", in particular the "Examples and Unit Tests" one?
This looks like a problem with Google Test.

Try to install it only using Homebrew. Take a look [at the instructions here](https://sumo.dlr.de/docs/Installing/index.html#macos).

**Comment by angelobanse** [comment]
To install SUMO via homebrew just execute:
```
brew tap dlr-ts/sumo
brew install sumo
```

**Comment by moneymined** [comment]
/Users/gimsuyeon/googletest/googlemock/include/gmock/gmock-matchers.h:3908:10: note: in implicit move constructor for 'testing::PolymorphicMatcher<testing::internal::EndsWithMatcher<std::wstring>>' first required here
  return MakePolymorphicMatcher(
         ^
12 errors generated.
make[2]: *** [googlemock/CMakeFiles/gmock.dir/src/gmock-all.cc.o] Error 1
make[1]: *** [googlemock/CMakeFiles/gmock.dir/all] Error 2
make: *** [all] Error 2

**I did the Google test in order, but the error keeps popping up as shown below.**

**I installed sumo through homebrew, but the error still appears.**

**Comment by moneymined** [comment]
> **나는 homebrew를 사용하여 sumo 프로그램을 설치하지만 Git Cloning and Building 부분에서는 cmake --build를 사용합니다. --parallel$(sysctl -n hw.ncpu) 이 부분은 아래와 같이 에러가 납니다.**
> 
> **https://sumo.dlr.de/docs/Installing/MacOS_Build.html 을 통해 순서대로 했습니다 .**
> 
> ```
> [ 97%] Linking CXX executable /Users/gimsuyeon/sumo/bin/testmicrosim
> 
> Undefined symbols for architecture x86_64:
> 
> Undefined symbols for architecture x86_64:
> 
>   "typeinfo for testing::Test", referenced from:
> 
>       typeinfo for Boundary_test_method_add_Test in BoundaryTest.cpp.o
> 
>       typeinfo for Boundary_test_method_add_multiple_Test in BoundaryTest.cpp.o
> 
>       typeinfo for Boundary_test_method_getCenter_Test in BoundaryTest.cpp.o
> 
>       typeinfo for Boundary_test_method_getWidthHeight_Test in BoundaryTest.cpp.o
> 
>       typeinfo for Boundary_test_method_around_Test in BoundaryTest.cpp.o
> 
>       typeinfo for Boundary_test_method_overlapsWith_Test in BoundaryTest.cpp.o
> 
>       typeinfo for Boundary_test_method_crosses_Test in BoundaryTest.cpp.o
> 
>   "typeinfo for testing::Test", referenced from:
> 
>       typeinfo for StringTokenizer_test_split_with_whitechar_Test in StringTokenizerTest.cpp.o
> 
>       typeinfo for StringTokenizer_test_split_with_newline_Test in StringTokenizerTest.cpp.o
> 
>       typeinfo for StringTokenizer_test_split_with_x_Test in StringTokenizerTest.cpp.o
> 
>       typeinfo for StringTokenizer_test_split_any_char_Test in StringTokenizerTest.cpp.o
> 
>       typeinfo for StringTokenizer_test_method_reinit_Test in StringTokenizerTest.cpp.o
> 
>       typeinfo for StringTokenizer_test_method_size_Test in StringTokenizerTest.cpp.o
> 
>       typeinfo for StringTokenizer_test_method_front_Test in StringTokenizerTest.cpp.o
> 
>       ...
> 
> ld: symbol(s) not found for architecture x86_64
> 
>       ...
> 
> ld: symbol(s) not found for architecture x86_64
> 
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> 
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> 
> make[2]: *** [/Users/gimsuyeon/sumo/bin/testgeom] Error 1
> 
> make[2]: *** [/Users/gimsuyeon/sumo/bin/testcommon] Error 1
> 
> make[1]: *** [unittest/src/utils/geom/CMakeFiles/testgeom.dir/all] Error 2
> 
> make[1]: *** Waiting for unfinished jobs....
> 
> make[1]: *** [unittest/src/utils/common/CMakeFiles/testcommon.dir/all] Error 2
> 
> Undefined symbols for architecture x86_64:
> 
>   "typeinfo for testing::Test", referenced from:
> 
>       typeinfo for MFXWorkerThread_test_init_Test in MFXWorkerThreadTest.cpp.o
> 
>       typeinfo for MFXWorkerThread_test_get_all_Test in MFXWorkerThreadTest.cpp.o
> 
> ld: symbol(s) not found for architecture x86_64
> 
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> 
> make[2]: *** [/Users/gimsuyeon/sumo/bin/testfoxtools] Error 1
> 
> make[1]: *** [unittest/src/utils/foxtools/CMakeFiles/testfoxtools.dir/all] Error 2
> 
> Undefined symbols for architecture x86_64:
> 
>   "typeinfo for testing::Test", referenced from:
> 
>       typeinfo for MSEventControl_test_method_execute_Test in MSEventControlTest.cpp.o
> 
>       typeinfo for MSCFModelTest in MSCFModelTest.cpp.o
> 
>       typeinfo for MSCFModel_IDMTest in MSCFModel_IDMTest.cpp.o
> 
> ld: symbol(s) not found for architecture x86_64
> 
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> 
> make[2]: *** [/Users/gimsuyeon/sumo/bin/testmicrosim] Error 1
> 
> make[1]: *** [unittest/src/microsim/CMakeFiles/testmicrosim.dir/all] Error 2
> 
> make: *** [all] Error 2
> ```
> 
> **오류를 수정하는 방법을 모르겠습니다. 당신의 도움이 절실히 필요합니다.**
> 
> **저는 맥북 프로를 사용하고 있습니다. macos 버전은 Ventura 13.0.1입니다.**

**Comment by moneymined** [comment]
/Users/gimsuyeon/googletest/googlemock/include/gmock/gmock-matchers.h:3908:10: note: in implicit move constructor for 'testing::PolymorphicMatcher<testing::internal::EndsWithMatcherstd::wstring>' first required here
return MakePolymorphicMatcher(
^
12 errors generated.
make[2]: *** [googlemock/CMakeFiles/gmock.dir/src/gmock-all.cc.o] Error 1
make[1]: *** [googlemock/CMakeFiles/gmock.dir/all] Error 2
make: *** [all] Error 2

I did the Google test in order, but the error keeps popping up as shown below.

I installed sumo through homebrew, but the error still appears.

**Comment by angelobanse** [comment]
> To install SUMO via homebrew just execute:
> 
> ```
> brew tap dlr-ts/sumo
> brew install sumo
> ```

Try this. Forget the other build instructions.

**Comment by moneymined** [comment]
brew tap dlr-ts/sumo
brew install sumo
xcode-select --install
clang --version
brew install cmake
brew install --cask xquartz
brew install xerces-c fox proj gdal gl2ps
git clone --recursive https://github.com/eclipse/sumo
export SUMO_HOME="$PWD/sumo"
cd $SUMO_HOME
mkdir build/cmake-build
cd build/cmake-build
cmake ../..
cd $SUMO_HOME/build/cmake-build
cmake --build . --parallel $(sysctl -n hw.ncpu)

Should I proceed at the terminal in the order I wrote down now?
I just used my MacBook. I don't know.
I would appreciate it if you could tell me the exact installation order to fill out at the terminal!

**Comment by angelobanse** [comment]
You just need to do the following two commands (and in that order) in the terminal:
```
brew tap dlr-ts/sumo
brew install sumo
```

Ignore all other steps, which are to build SUMO yourself (which i do not recommend you doing at this moment).

**Comment by moneymined** [comment]
You have installed two commands.
What should I do next?

**Comment by angelobanse** [comment]
That means the SUMO_HOME environment variable is missing.

Execute `brew info sumo` in the terminal, and copy the line below the "Don't forget to set your SUMO_HOME environment variable:" message you get.
Save that line to the `.zshrc` file (located in your home directory).

**Comment by angelobanse** [comment]
[Here](https://sumo.dlr.de/docs/Basics/Basic_Computer_Skills.html#macos) are the instructions on how to set the SUMO_HOME environment variable in macOS. Just keep in mind to replace the `export SUMO_HOME="/your/path/to/sumo"` with the line you copied from `brew info sumo`

**Comment by moneymined** [comment]
export PATH="/usr/local/opt/mysql@5.7/bin:$PATH"
export PATH="/usr/local/opt/mysql-client/bin:$PATH"
export SUMO_HOME="/usr/local/opt/sumo/share/sumo"

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/gimsuyeon/opt/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/gimsuyeon/opt/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/gimsuyeon/opt/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/gimsuyeon/opt/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

I added the path as I told you in the .zshrc file. Still, the same error continues to occur.
