### ISSUE TITLE
Right click over an element in front of a polygon always select polygon

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#12819]
It's the same regression that was (successfully) fixed in 1.16.0 via  #12111

This time we really need to figure out why it broke again and how we can prevent this in the future.

**Comment by palvarezlopez** [comment]
The problem was caused by an invalid sorting of objects by layer.

**Comment by palvarezlopez** [comment]
@behrisch currently we don't have Pyautogui test for SUMO-GUI :(

**Comment by behrisch** [comment]
see #12847
