### ISSUE TITLE
close process when closing tool

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#12832]
subtask of #4138 

this is mainly for osmWebWizard:  it keeps running until ended with ctrl+c and any open process blocks the port so it cannot be started again. This could be very ocnfusing for users.

**Comment by behrisch** [comment]
Actually not. The proper thing to do in my opinion is to stop the webWizard script when closing the browser (tab). But I don't now whether this can be implemented easily and maybe it even conflicts with our workaround of opening the site in a second browser if the default browser does not work. A close button is not something I expect on a web site.

**Comment by palvarezlopez** [comment]
Now netedit can close all process called in GNETools. The specific task for WebWizard continues in #12859
