### ISSUE TITLE
 create a curved road

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#12835]
Hello,I have a question.How do you create a curved road (curve) on Netedit? Like the picture below.Thank you
![w640_h427_6fbfbbac4ce543c0946c74771a9fb59c](https://user-images.githubusercontent.com/54823725/225528749-8f0d799e-e4d5-4693-a880-8a4310de53ef.jpeg)

**SUMO-version:1.14**

**operating system:Windows**

**Comment by namdre** [comment]
see https://sumo.dlr.de/docs/Netedit/neteditUsageExamples.html#making_curved_roads

**Comment by a-123-du** [comment]
Yes ,I have had a try,but I want to each edge have two numLanes,why there is no separation line between lanes (dotted line)？
![f01ebcd2fca1f64af87145cc8d0a101](https://user-images.githubusercontent.com/54823725/225557047-46b50498-db50-45d8-804d-ec33a1a011b2.png)
like this pic below.
![523c3ca4f0b7dc2da8a396f214fa2fb](https://user-images.githubusercontent.com/54823725/225557223-7ff382fc-7f45-4fc5-93e6-10e772621a2e.png)

**Comment by namdre** [comment]
this a visual artifact (#12837) but the simulation will work fine

**Comment by a-123-du** [comment]
> 这是一个视觉伪影（#12837），但模拟将正常工作。您可以将曲线分辨率更改为 ~6，标记将照常显示。
But in the sumo-gui,there is not shown.
![Uploading 7e7eac8aef17427920f50f99b79c3c0.png…]()

**Comment by namdre** [comment]
your screenshot is not show. You need to change the curve resolution option (in the 'Formats' tab of the F10 dialog)  *before* you use the 'smooth shape' operation.

**Comment by a-123-du** [comment]
> your screenshot is not show. You need to change the curve resolution option (in the 'Formats' tab of the F10 dialog) _before_ you use the 'smooth shape' operation.

Yes,I have had a try , it showed.But How can I make the curve more smooth, because each small segment is still a straight line.
![3e345643123395a7e011515a627c3b4](https://user-images.githubusercontent.com/54823725/225799278-e8ff5dad-384e-4f1b-99ab-ea04ce0c4572.png)

**Comment by a-123-du** [comment]
hello,friend,are you online?

**Comment by namdre** [comment]
It's always straight lines. You can only decide the level of detail. The latest dev version of sumo-gui and netedit supports rendering lane markings for high-density geometry so go with that if you prefer.

**Comment by a-123-du** [comment]
> 它总是直线。您只能决定详细程度。Sumo-gui 和 netedit 的最新开发版本支持渲染高密度几何体的通道标记，因此如果您愿意，请继续使用。
you mean the version 1.16.0? yes or no? Thank you very much

**Comment by namdre** [comment]
the fix for lane markings is only in the nightly version: https://sumo.dlr.de/docs/Downloads.php#nightly_snapshots

**Comment by a-123-du** [comment]
> the fix for lane markings is only in the nightly version: https://sumo.dlr.de/docs/Downloads.php#nightly_snapshots

ok，thank you. This is a curved road I created, there are two lanes, is the center line of each lane connected by a broken line segment? When the car is driving in one lane, is the front midpoint and rear midpoint always on the center line?
![a004d51dae81102c00df8bab16d8eda](https://user-images.githubusercontent.com/54823725/226237440-37aed4b3-5921-4db2-8ff5-6beaa37d3df9.png)

**Comment by namdre** [comment]
In the default model, yes. 

But there are 2 more models that change this: https://sumo.dlr.de/docs/Simulation/SublaneModel.html
