### ISSUE TITLE
Inconsistent between traci.simulation.getTime and sumo-gui when debug

### ISSUE THREAD

**Issue by YSXXXXXXX** [eclipse/sumo#12839]
Hi, while debugging the python script, I encountered the issue that mentioned in the title. Here are the steps I followed:

In the python file ```test.py```, I set a breakpoint on **line 12**, and continuously use ```Resume Program``` command (```F9``` in pycharm, not the ```Step Over``` command, ```F8``` in pycharm) during the debug. Each time run to the breakpoint, the time displayed in SUMO-GUI is inconsistent with the return value of ```traci.simulation.getTime()```, the difference of these two variables is about 29, while the correct difference is 1.
```traci.simulationl.getTime()``` seems works well, maybe something wrong with SUMO-GUI? 

Could you help me? Thank you in advance.

**SUMO-version: 1.15/1.16**

**operating system: Windows10**
[example.zip](https://github.com/eclipse/sumo/files/10988858/example.zip)

**Comment by m-kro** [comment]
Your python code prints values only every thirty simulation steps as you have two nested loops but print only in the outer one. If you stop the code in the meantime, the difference between the last printed time on the console and the sumo-gui can get greater than 1.

**Comment by YSXXXXXXX** [comment]
So I should execute the ```traci.simulationStep()``` step by step (use ```Step Over``` ?) to make sure the sumo-gui display the right time?

**Comment by m-kro** [comment]
No, you need to restructure your script to call `traci.simulationStep()` every time after you call `traci.simulationStep()`! This has nothing to do with your IDE...
