### ISSUE TITLE
Interconnecting Two Sumo Simulations for Coordination via TCP/IP: Challenges and Solutions

### ISSUE THREAD

**Issue by burakseyitkara** [eclipse/sumo#12855]
We want to run two separate Sumo simulations on two different computers, and connect them to each other via tcp/ip to create coordination between them. In these simulations, when a vehicle exits from the right side of the simulation on the left, we want a vehicle to enter from the left side of the simulation on the right. In other words, a vehicle leaving from one simulation should go to the other. However, we have not been able to find any resources on how to write two interconnected simulations that can make changes to each other under certain conditions. When we tried traci.connect() or traci.init() functions, we were unable to connect to the desired port or IP address. Can you help us with how to do this?

**SUMO-version: 1.16.0**

**operating system: Windows 11**

**Comment by m-kro** [comment]
You might be interested in publications regarding partitioning and parallelisation of SUMO:

- [Partitioning of urban transportation networks utilizing real-world traffic parameters for distributed simulation in SUMO](https://ieeexplore.ieee.org/abstract/document/7835942)
- [dSUMO: Towards a Distributed SUMO](https://researchrepository.ucd.ie/rest/bitstreams/20063/retrieve)
- [QarSUMO: A Parallel, Congestion-optimized Traffic Simulator](https://arxiv.org/pdf/2010.03289.pdf)

**Comment by burakseyitkara** [comment]
> You might be interested in publications regarding partitioning and parallelisation of SUMO:
> 
> * [Partitioning of urban transportation networks utilizing real-world traffic parameters for distributed simulation in SUMO](https://ieeexplore.ieee.org/abstract/document/7835942)
> * [dSUMO: Towards a Distributed SUMO](https://researchrepository.ucd.ie/rest/bitstreams/20063/retrieve)
> * [QarSUMO: A Parallel, Congestion-optimized Traffic Simulator](https://arxiv.org/pdf/2010.03289.pdf)

Thank you very much for sharing the articles and theses related to the subject. I will definitely look into them. However, we have a short time to complete this step, so if you could provide a simple code example or  a project part that accomplishes this, I would be very grateful. Thank you again!

**Comment by behrisch** [comment]
Please add another comment if you have more info
