### ISSUE TITLE
build process under Linux / Ubuntu requires new python packages

### ISSUE THREAD

**Issue by atellyro** [eclipse/sumo#12851]
The build process (generation of template.h in netedit) requires new python packages.
These packages should be documented in  https://sumo.dlr.de/docs/Installing/Linux_Build.html.

Until now i have figured out:
  sudo apt install python3-ezdxf
  sudo apt install python3-ortools

There are some remaining issues:

[ 81%] Built target netedit_elements_data
[ 81%] Generating templates.h
Traceback (most recent call last):
  File "/dosd/src/opensource/Sumo/sumo-git-co/sumo/src/netedit/../../tools/build/../drt/drtOrtools.py", line 30, in <module>
    import ortools_pdp
  File "/dosd/src/opensource/Sumo/sumo-git-co/sumo/tools/drt/ortools_pdp.py", line 29, in <module>
    from ortools.constraint_solver import routing_enums_pb2
  File "/usr/lib/python3/dist-packages/ortools/constraint_solver/routing_enums_pb2.py", line 5, in <module>
    from google.protobuf import descriptor as _descriptor
ModuleNotFoundError: No module named 'google'
Error when generating tool template for drtOrtools: 'Command '['/bin/python', '/dosd/src/opensource/Sumo/sumo-git-co/sumo/src/netedit/../../tools/build/../drt/drtOrtools.py', '--save-template', 'stdout']' returned non-zero exit status 1.'.
Traceback (most recent call last):
  File "/dosd/src/opensource/Sumo/sumo-git-co/sumo/src/netedit/../../tools/build/../output/attributeStats.py", line 35, in <module>
    from sumolib.statistics import setPrecision, identity
ImportError: cannot import name 'identity' from 'sumolib.statistics' (/usr/local/lib/python3.10/dist-packages/sumolib/statistics.py)
Error when generating tool template for attributeStats: 'Command '['/bin/python', '/dosd/src/opensource/Sumo/sumo-git-co/sumo/src/netedit/../../tools/build/../output/attributeStats.py', '--save-template', 'stdout']' returned non-zero exit status 1.'.

**SUMO-version:**
Daily build as of 2023-03-17 09:30

**operating system:**
Ubuntu 22.10

**Comment by palvarezlopez** [comment]
@atellyro I updated the linux documentation. If after install python libraries you have problems yet, please put here the compiling errors.

**Comment by atellyro** [comment]
It seems that the less sign '<' in comments is transformed to '"<'  

line 336 in template.py
336:    return templateStr.replace("<", '"<').replace("\n", '"\n')

**Comment by atellyro** [comment]
A new issue
[ 81%] Generating templates.h
Traceback (most recent call last):
  File "/dosd/src/opensource/Sumo/sumo-git-co/sumo/src/netedit/../../tools/build/../drt/drtOrtools.py", line 30, in <module>
    import ortools_pdp
  File "/dosd/src/opensource/Sumo/sumo-git-co/sumo/tools/drt/ortools_pdp.py", line 29, in <module>
    from ortools.constraint_solver import routing_enums_pb2
  File "/usr/lib/python3/dist-packages/ortools/constraint_solver/routing_enums_pb2.py", line 34, in <module>
    _descriptor.EnumValueDescriptor(
  File "/usr/local/lib/python3.10/dist-packages/google/protobuf/descriptor.py", line 796, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
Error when generating tool template for drtOrtools: 'Command '['/bin/python', '/dosd/src/opensource/Sumo/sumo-git-co/sumo/src/netedit/../../tools/build/../drt/drtOrtools.py', '--save-template', 'stdout']' returned non-zero exit status 1.'.

**Comment by palvarezlopez** [comment]
@atellyro do you have protobuf installed?

**Comment by atellyro** [comment]
No, it is not mentioned in the build docu, but if i installed it (sudo apt install python3-protobuf), it works except for the '<' in comments

**Comment by palvarezlopez** [comment]
@atellyro in my build it works. After a clean build, can you send me the full make trace?

**Comment by namdre** [comment]
@atellyro The build should go through even if not all python modules are available.

**Comment by atellyro** [comment]
Please apply the following patch to template.py

> diff -C1 ./tools/build/templates.py.orig ./tools/build/templates.py
*** ./tools/build/templates.py.orig     2023-03-16 14:13:55.303066400 +0100
--- ./tools/build/templates.py  2023-03-17 19:55:36.108348000 +0100
***************
*** 334,337 ****
      templateStr = templateStr.replace('"', '\\"')
!     # add quotes and end lines
!     return templateStr.replace("<", '"<').replace("\n", '"\n')
  
--- 334,343 ----
      templateStr = templateStr.replace('"', '\\"')
!     # break template string into single lines
!     templateLines = templateStr.strip().split('\n')
!     quotedTemplateLines = []
!     for templateLine in templateLines:
!         # add double quotes around each line
!         quotedTemplateLines.append(templateLine.replace("<", '"<', 1) + '"')
!     # return lines as one string
!     return('\n'.join(quotedTemplateLines))

Now the compilation went through. The above mentioned exceptions (new issue) are indeed ignored during the template generation

**Comment by behrisch** [comment]
@atellyro I am not sure I understand. Did the compilation only work after your fix? Can you please send a unified diff (`diff -u`)?

**Comment by atellyro** [comment]
The problem is:
in line 336 of templates.py every '<' in the xml string is replaced by "<, even those in substrings like xml help
You can make templates.py more stable or do not use < inside strings of the xml help.
Meanwhile it seems, that the < inside the help-strings are eliminated. Otherwise a xml line like 
      <xlim value="None" type="string" help="Defines x-limits of the figure <XMIN>,<XMAX>"/>
is transformed into
    "<xlim value=\"None\" type=\"string\" help=\"Defines x-limits of the figure "<XMIN>,"<XMAX\"/>"
which is not compilable

diff -u ./tools/build/templates.py.orig ./tools/build/templates.py
--- ./tools/build/templates.py.orig     2023-03-16 14:13:55.303066400 +0100
+++ ./tools/build/templates.py  2023-03-17 19:55:36.108348000 +0100
@@ -332,8 +332,14 @@
     templateStr = templateStr.replace('netedit', '="')
     # replace " with \"
     templateStr = templateStr.replace('"', '\\"')
-    # add quotes and end lines
-    return templateStr.replace("<", '"<').replace("\n", '"\n')
+    # break template string into single lines
+    templateLines = templateStr.strip().split('\n')
+    quotedTemplateLines = []
+    for templateLine in templateLines:
+        # add double quotes around each line
+        quotedTemplateLines.append(templateLine.replace("<", '"<', 1) + '"')
+    # return lines as one string
+    return('\n'.join(quotedTemplateLines))

**Comment by behrisch** [comment]
We should hide the tracebacks

**Comment by behrisch** [comment]
please add further comments if you still have build problems
