### ISSUE TITLE
multiple threads when using traci

### ISSUE THREAD

**Issue by Ljiaooo** [eclipse/sumo#12860]
I want to use multiple threads in traci, for example, use multiple threads to add route(traci.route.add()). Are there any methods to do this? 
When I used threading.Thread to create multiple threads and control sumo-gui with traci, I found it will cause problems when excute traci.xx with multiple threads.  
![image](https://user-images.githubusercontent.com/86714259/226166015-8b3ee3eb-be5e-4abc-aa89-2de3f9661c42.png)
Any one knows how to fix this? Thansk in advance!

**Comment by namdre** [comment]
see https://sumo.dlr.de/docs/TraCI/Interfacing_TraCI_from_Python.html#controlling_the_same_simulation_from_multiple_clients

Using a single client with multiple threads that use TraCI at the same time is not supported (unless you use locks to ensure that only one thread uses traci calls at a time).
