### ISSUE TITLE
maximum vehicle acceleration and maximum lateral acceleration

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#12864]
Hello，does Traci have interfaces for obtaining maximum vehicle acceleration and maximum lateral acceleration?

**SUMO-version:1.16.0**

**operating system:Windows**

**Comment by a-123-du** [comment]
> https://sumo.dlr.de/pydoc/traci._vehicletype.html#VTypeDomain-getAccel

yes，but is there an interface for obtaining maximum  lateral acceleration? I don't find it in the website. Thank you.

**Comment by namdre** [comment]
`vehicle.getParameter(vehID, "laneChangeModel.lcAccelLat")`

https://sumo.dlr.de/docs/TraCI/Vehicle_Value_Retrieval.html#supported_lanechangemodel_parameters
