### ISSUE TITLE
[Bug] Bicycles will go backwards at the intersection.

### ISSUE THREAD

**Issue by LiXiuqiXJTU** [eclipse/sumo#12870]
![image](https://user-images.githubusercontent.com/93695420/226547165-7329afd2-e62d-45ed-8059-e573e921ae26.png)

    As is  depicted on the image above, we've drown a trajectory of a bicycle and found that the bicycle went backwards while going through an intersection at the coordinate of (92.5, 297), (94.5, 298.2) and (95.7, 300.2). We would be glad if your team can fix this BUG ASAP.

**SUMO-version:**
1.15.0
**operating system:**
ubuntu 20.04

**Comment by m-kro** [comment]
Could you please add the SUMO files to reproduce your result?

**Comment by namdre** [comment]
I suspect it's the same problem as discussed in #11643 and #8790 (this has a nice picture)

**Comment by zicyair** [comment]
> I suspect it's the same problem as discussed in #11643 and #8790 (this has a nice picture)

Seems the same problem from my view. 

And here's our SUMO files which can reproduce our result: [Issue_12870.zip](https://github.com/eclipse/sumo/files/11037416/Issue_12870.zip)

**Comment by namdre** [comment]
The task you are trying to accomplish (extremely high-fidelity trajectories) is at the margin of what SUMO was designed to accomplish. (From the perspective of the vehicle they are continuously moving forward so the trajectory errors do not affect vehicle interactions).
While, there is a possible improvement described in #11643 (storing outer borders), there probably won't be a fix anytime soon. 
You might either increase the simulation step length to smooth over the error or add some post-processing of your own.
