### ISSUE TITLE
Avoid unregistered platoon objects

### ISSUE THREAD

**Issue by TrinhTuanHung2021** [eclipse/sumo#12878]
Hello.
I run a road network where all vehicles are platooning vehicles.
I used simpla to create platoons.

My code is simple 

```
if __name__ == "__main__":
    
    for i in range(10):          
        sumo_cmd = ['sumo-gui', '--duration-log.statistics', '--tripinfo-output', 'intelligent_lights_output_file.xml', '-c', 'scenario/amman.sumocfg']
        traci.start(sumo_cmd)
        simpla.load("scenario/1type.cfg.xml")
        step = 0 
        
        while step <36000:  # 1 hour
            step += 1        
            traci.simulationStep()

        traci.close()
```
But the model often gets errors when running
![image](https://user-images.githubusercontent.com/82990411/226783918-8fe5c4a5-9be8-4991-b7ff-ab8a2828c150.png)

![image](https://user-images.githubusercontent.com/82990411/226783969-6a77b817-b2eb-4a2b-9ae7-1fdca8ea2830.png)

**Comment by m-kro** [comment]
Could you please supply the files to reproduce the simulation? Seems quite odd that the removal of arrived vehicles does not work as expected.

**Comment by m-kro** [comment]
Could be reproduced in sumo v.1.16 , but not in the developer version...

**Comment by TrinhTuanHung2021** [comment]
> 



> Could be reproduced in sumo v.1.16 , but not in the developer version...

Because I set the `maxVehicle =3` in cfg.xml. This feature is only available in version 1.16.
I remove it to try in other versions but it has still errors

**Comment by TrinhTuanHung2021** [comment]
> There was a side effect in checking whether platoons can split. The split was executed and only then was checked for safety. If the check failed, the platoon would not be added to the main platoon register and left as is.
> 
> @TrinhTuanHung2021 You can find the updated version here at Github or download the nightly snapshot tomorrow.

Thank you. I will download the snapshot tomorrow and check it later.

**Comment by m-kro** [comment]
Closed as completed. If you still have questions or comments, please feel free to add them here and we will reopen the issue.
