### ISSUE TITLE
general junctionModel parameter matching all types or IDs

### ISSUE THREAD

**Issue by JulianCzymmeck** [eclipse/sumo#12876]
Hey there!
I'm trying to make a pedestrian ignore all vehicles in the simulation (temporarily), thus enabling them to ignore traffic rules in custom situations.
My current approach to this is to call
```traci.person.setParameter(pedestrian, "junctionModel.ignoreTypes", "DEFAULT_VEHTYPE")```
for said pedestrian. And while that works perfectly in my scenario, it comes with the limitation of only ignoring vehicles of the DEFAULT_VEHTYPE. Now I want to generalize that call to include all vehicles.

Is there a VEHTYPE matching all vehicle types in the simulation?
Or is there maybe another alternative way of solving my issue?
The same question can be applied to using `traci.person.setParameter(pedestrian, "junctionModel.ignoreID", "veh_ID")` where I would need an ID matching all individual vehicles in the simulation.

Thanks a lot in advance :)

**Comment by namdre** [comment]
There is no way of matching all types automatically at the moment. You can obtain a list of all vehicle types in the scenario with `traci.vehicletype.getIDList()` and  then use `" ".join(typelist)` as parameter value.

**Comment by JulianCzymmeck** [comment]
Thank you for the swift response. I'm assuming that I can undo that afterwards by calling `traci.person.setParameter(pedestrian, "junctionModel.ignoreTypes", "")`. Is that correct?

If so, that would solve my issue completely.

**Comment by namdre** [comment]
Yes, that is correct.
