### ISSUE TITLE
Train reversing in bi-directional edges

### ISSUE THREAD

**Issue by LorenzoUccello** [eclipse/sumo#12877]
I am building a simple metro train network where trains can reverse their direction. I cannot complete the reversing since I am not able to insert a turn-around connection at dead ends. How can I add them? 
I created the route by listing the subsequent edges to be reached, but since no turn-around connection is defined, the train cannot reverse and continue to the next edge once it reached a dead-end. 

[Railway_example.zip](https://github.com/eclipse/sumo/files/11034504/Railway_example.zip)

**SUMO-version: 1.15.0**

**operating system: MacOS**

**Comment by namdre** [comment]
see https://sumo.dlr.de/docs/Simulation/Railways.html#working_with_bidirectional_tracks_in_netedit

**Comment by LorenzoUccello** [comment]
I read it and created the bidirectional edges as indicated. However, if I give the train a route that requires reversing, I get that it is not possible to connect the two edges (e.g. arrived at the dead end, I communicate the next edge in the opposite direction, so the train should reverse direction, but it needs a turn-around connection which I don't know how to create).

**Comment by namdre** [comment]
you need to use 'connection mode' to define the turn-around connection explicitly. The link explains how to ensure that all relevant edges are visible in netedit.
