### ISSUE TITLE
value not in enumeration

### ISSUE THREAD

**Issue by ckh0715** [eclipse/sumo#12889]
I try to add LCModel and modify routeTypes.xsd like under code.
In rou.xml, I set LaneChangeModel="MYLCM".
But when I run sumo, it told me value 'MYLCM' not in enumeration.
How to solve this?

<xsd:attribute name="laneChangeModel">
          <xsd:simpleType>
              <xsd:restriction base="xsd:string">
                  <xsd:enumeration value="default"/>
                  <xsd:enumeration value="DK2008"/>
                  <xsd:enumeration value="LC2013"/>
                  <xsd:enumeration value="SL2015"/>
                  <xsd:enumeration value="MYLCM"/>
              </xsd:restriction>
          </xsd:simpleType> 
      </xsd:attribute>

**Comment by namdre** [comment]
see https://sumo.dlr.de/docs/Developer/How_To/Lane-Changing_Model.html#loading_into_simulation for the full list of steps
