### ISSUE TITLE
ability to show a car straddling in a highway

### ISSUE THREAD

**Issue by harirRzi** [eclipse/sumo#12887]
Add your issue description here.

*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**
Hi I'm working with Sumo in MAC OS. I want to know if it is possible in Sumo to simulate abruptly changing of acceleration or Car straddling in it? I appreciate of any help

**Comment by namdre** [comment]
- using traci (https://sumo.dlr.de/docs/TraCI.html) you can create traffic events such as abrupt acceleration changes
- using the sublane model (https://sumo.dlr.de/docs/Simulation/SublaneModel.html) you can have cars that drive between lanes

**Comment by harirRzi** [comment]
Thank you so much for your help so can I make just one car among others to have abruptly acceleration change by using the Traci?

**Comment by namdre** [comment]
yes.
