### ISSUE TITLE
generate

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#12888]
I give some point coordinates, how to generate a road so that the shape value of the centerline of the road is the given coordinate points?

**SUMO-version:1.16**

**operating system:Windows**

**Comment by namdre** [comment]
set edge attribute 'spreadType="center"`

**Comment by a-123-du** [comment]
> set edge attribute `spreadType="center"`

I'm sorry, you may have misunderstood what I mean, it's like this, I set up the equation of a curve myself, and get the points on the curve, I want to create the shape of the centerline in netedit as the lane of these points I give, think It shows a corner, what should I do? I directly modified the shape of the lane in net.xml, and found that it is not a curve.

**Comment by namdre** [comment]
usually you set the shape of the edge and let netconvert/netedit compute the individual lane shapes.
There are two options on how the edge shape is interpreted:
- spreadType=right: shape is the centerline of the whole road encompassing both directions
- spreadType=center: shape is the centerline of a unidirectional road
