### ISSUE TITLE
Semi-automatic checks of translation strings

### ISSUE THREAD

**Issue by m-kro** [eclipse/sumo#12894]
We currently have quite a lot of translation strings which come in a few variants (upper / lower case, space) and which may be present in both .pot files. Additionally, there are a lot of terms which are written in a few variants (e.g. "id" <> "ID",  "edge type" <> "edgeType", "dataset" - "dataSet" - "data set").

Some ideas how this could be more unified and how potential duplicates could be removed:

- search for similar values: either use some simple heuristic (match after some transformations like lower case) or use some editing metric (number of operations to make two strings match)
- give some preferences to define the chosen value (like: give a fixed list of words to be replaced)
- comfort function to fusion the existing translations (if there is no conflict beyond upper/lower case and other minor transformations)
- suggest translations which are present for one pot file but not in the other if the msgids match
- write the updated pot/po content to separate files for further checking

**Comment by m-kro** [comment]
@behrisch Was there a technical reason to assign the source files to two separate pot files (gui.pot, sumo.pot) if in the end we translate both?

**Comment by behrisch** [comment]
No it was purely to help people focus and limit the size. Maybe some translators only want to have the GUI translated. Yes, in the end we should have both

**Comment by m-kro** [comment]
Another idea: Create test to check for "orphaned" messages (to see if translations were lost due to changed msgid values)

**Comment by m-kro** [comment]
Maybe add an option to obsoleteTranslations.py to patch an already orphaned translation giving both the old and the new string as input
