### ISSUE TITLE
TraCI-controlled RL: when running multiple instances in parallel, SUMO randomly crashed

### ISSUE THREAD

**Issue by liyan2015** [eclipse/sumo#12893]
Hi, SUMO community. I have a customized RL environment based on SUMO. During the training, I use `subprocess` to launch multiple instances in parallel. The simulation environment would periodically restart (with `traci.start()` following a `traci.close()`). When I launch more than 4 instances in parallel, some processes may randomly crash at any step of training, either due to `Error: std::bad_alloc`:
```
Error: std::bad_alloc
Quitting (on error).
Process ForkServerProcess-13:
Traceback (most recent call last):
  File "/home/yan_l/anaconda3/envs/rl/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/yan_l/anaconda3/envs/rl/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yan_l/RL/stable-baselines3/stable_baselines3/common/vec_env/subproc_vec_env.py", line 30, in _worker
    observation, reward, done, info = env.step(data)
  File "/home/yan_l/RL/stable-baselines3/stable_baselines3/common/monitor.py", line 95, in step
    observation, reward, done, info = self.env.step(action)
  File "/home/yan_l/anaconda3/envs/rl/lib/python3.9/site-packages/gym/wrappers/order_enforcing.py", line 11, in step
    observation, reward, done, info = self.env.step(action)
  File "/home/yan_l/RL/stable-baselines3/canalenv/canalenv/envs/canalenv_gym.py", line 712, in step
    traci.simulationStep()
  File "/home/yan_l/sumo-1.16.0/tools/traci/main.py", line 199, in simulationStep
    return connection.check().simulationStep(step)
  File "/home/yan_l/sumo-1.16.0/tools/traci/connection.py", line 363, in simulationStep
    result = self._sendCmd(tc.CMD_SIMSTEP, None, None, "D", step)
  File "/home/yan_l/sumo-1.16.0/tools/traci/connection.py", line 225, in _sendCmd
    return self._sendExact()
  File "/home/yan_l/sumo-1.16.0/tools/traci/connection.py", line 135, in _sendExact
    raise FatalTraCIError("connection closed by SUMO")
traci.exceptions.FatalTraCIError: connection closed by SUMO
```
or simply loses connection with SUMO. However, running one instance does not have such problems.

I have [generated a log of all traci commands](https://sumo.dlr.de/docs/TraCI/Interfacing_TraCI_from_Python.html#generating_a_log_of_all_traci_commands) as in [here](https://github.com/eclipse/sumo/issues/8477). The `traceFile.txt` can run repeatedly without causing errors. The `log` and `error-log` files output by SUMO only captures the errors like `Error: tcpip::Socket::recvAndCheck @ recv: peer shutdown` or `Error: std::bad_alloc`.

I have used libsumo to avoid socket communication, but the same problem keeps popping.

To fix the `Error: std::bad_alloc`, I have also checked `ulimit -a`, but no use.
```
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 1030204
max locked memory       (kbytes, -l) 32972780
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 1030204
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```
Could you please give me any clue on how to solve this? Any instructions are appreciated!

*If possible, upload an example that shows your problem.*

**SUMO-version:**
1.16.0

**operating system:**
Ubuntu 18.04.5 LTS (GNU/Linux 5.4.0-126-generic x86_64)

**Comment by liyan2015** [comment]
> @liyan2015 Is your environment issuing traci commands from multiple different threads? Can you post the libsumo error as well (libsumo does not use a traci connection so it should at least have a different stack trace).

Yes, each thread (an environment instance) contains a sumo call and issues traci commands. Below is the libsumo stack trace that just crashed:
```
creating 68 environments.
Using cuda device
Traceback (most recent call last):
  File "/home/yan_l/RL/stable-baselines3/canal_train_parallel.py", line 166, in <module>
    model.learn(
  File "/home/yan_l/RL/stable-baselines3/stable_baselines3/ppo/ppo.py", line 304, in learn
    return super().learn(
  File "/home/yan_l/RL/stable-baselines3/stable_baselines3/common/on_policy_algorithm.py", line 246, in learn
    continue_training = self.collect_rollouts(self.env, callback, self.rollout_buffer, n_rollout_steps=self.n_steps)
  File "/home/yan_l/RL/stable-baselines3/stable_baselines3/common/on_policy_algorithm.py", line 174, in collect_rollouts
    new_obs, rewards, dones, infos = env.step(clipped_actions)
  File "/home/yan_l/RL/stable-baselines3/stable_baselines3/common/vec_env/base_vec_env.py", line 163, in step
    return self.step_wait()
  File "/home/yan_l/RL/stable-baselines3/stable_baselines3/common/vec_env/vec_normalize.py", line 178, in step_wait
    obs, rewards, dones, infos = self.venv.step_wait()
  File "/home/yan_l/RL/stable-baselines3/stable_baselines3/common/vec_env/vec_check_nan.py", line 40, in step_wait
    observations, rewards, dones, infos = self.venv.step_wait()
  File "/home/yan_l/RL/stable-baselines3/stable_baselines3/common/vec_env/subproc_vec_env.py", line 121, in step_wait
    results = [remote.recv() for remote in self.remotes]
  File "/home/yan_l/RL/stable-baselines3/stable_baselines3/common/vec_env/subproc_vec_env.py", line 121, in <listcomp>
    results = [remote.recv() for remote in self.remotes]
  File "/home/yan_l/anaconda3/envs/rl/lib/python3.9/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/home/yan_l/anaconda3/envs/rl/lib/python3.9/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/home/yan_l/anaconda3/envs/rl/lib/python3.9/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
```
When using libsumo, the reported `log` and `error-log` files are all empty, so I only have the stack trace in stdout. Below is my environment implementation (i.e. OpenAI gym) using libsumo:
```
import libsumo as traci
......
import libsumo as traci
......
def reset(self):
	############ libsumo #################
	if self.port != None:
		sumoCmd = ['-c', self.sumoConfig]
		traci.load(sumoCmd)
	else:
		self.port = sumolib.miscutils.getFreeSocketPort()
		traci.start(self.sumoCmd, traceFile="/data2/sumo/" + self.label + "_traci_commands.log")
	......
```
At the start of training or completion of all the steps in the environment, `reset()` will be called. I have also attached the configuration files for each env instance: [SUMO_configs.zip](https://github.com/eclipse/sumo/files/11051466/SUMO_configs.zip). `train1_canal.sumocfg` corresponds to the conf file of the first env instance thread, and `train1_charger.rou.xml` is the starting position of my RL agent on the road network.

**Comment by liyan2015** [comment]
> The stack trace does not mention libsumo at all. Any hints where it crashed?

There are no other contents directely related to libsumo in my stack trace:
![image](https://user-images.githubusercontent.com/10633479/227254607-68116ed2-76b4-46ab-830e-a42d98f6ddda.png)
The doc of libsumo says: "with traci every TraCIException will generate a message on stderr, Libsumo does not generate this message". Can you hint me on how to generate more detailed stack traces?

> And concerning concurrency: There is only one thread per traci connection?

I launch a subprocess to run each env instance (i.e., there is a sumo server launched in each subprocess), and within the subprocess, there are no more concurrent traci calls.

**Comment by robertalms** [comment]
Hello @liyan2015 , if you're willing to share your project, I could try to help my colleague @behrisch to replicate the error here on a linux server since I'm also interested in multiprocessing with stable_baselines + SUMO.

**Comment by behrisch** [comment]
Furthermore could you please try whether the error also occurs if you use vanilla python and not anaconda? And did you install sumo via pip or do you use the ubuntu package?

**Comment by liyan2015** [comment]
> Furthermore could you please try whether the error also occurs if you use vanilla python and not anaconda? And did you install sumo via pip or do you use the ubuntu package?

@robertalms OK, I will try vanilla python on my code. I installed sumo by compiling from the source code on my ubuntu server. I will be attending a conference in the following days, so I may delay a bit in wrapping up the codes.

**Comment by liyan2015** [comment]
> Hello @liyan2015 , if you're willing to share your project, I could try to help my colleague @behrisch to replicate the error here on a linux server since I'm also interested in multiprocessing with stable_baselines + SUMO.

@robertalms @behrisch Hi, the vanilla python has the same problem. Please extract the [code](https://github.com/eclipse/sumo/files/11079260/stable-baselines3.zip) to the root directory of [stable-baselines3](https://github.com/DLR-RM/stable-baselines3). The environment only works in gym==0.21.0.

**Comment by robertalms** [comment]
Hey @liyan2015, so after a lot of fiddling with some hard coded pathes, I finally managed to start your experiment yesterday. I'm training 4 envs in parallel now for about 12hours, which is about a third of the 10m steps you had defined... so far no errors. I used some nigthly SUMO version 1.15... that I had build already on the server. (I see you had 1.16). 

I could either kill the current training process now and try it with libsumo to see if that working/crashing... or directly switch to 1.16 and restart the training with traci - what do you think?

**Comment by liyan2015** [comment]
> Hey @liyan2015, so after a lot of fiddling with some hard coded pathes, I finally managed to start your experiment yesterday. I'm training 4 envs in parallel now for about 12hours, which is about a third of the 10m steps you had defined... so far no errors. I used some nigthly SUMO version 1.15... that I had build already on the server. (I see you had 1.16).
> 
> I could either kill the current training process now and try it with libsumo to see if that's working/crashing... or directly switch to 1.16 and restart the training with traci - what do you think?

Hi Robert. Thank you for the testing. On my server, 4 envs can also run without crash. Can you try to create 64 instances (set n_envs to 64 in `canalenv_gym.py`)? You can set MAX_STEP to 100 steps in `canalenv_gym.py`, and use the random agent in `canal_train_parallel.py` to speed up the fake simulation progress. Hopefully, it will crash within 5000000 total steps on my server with 72 cpu cores.

**Comment by liyan2015** [comment]
Maybe it is because of the SUMO version I used? I complied SUMO by following [this](https://sumo.dlr.de/docs/Installing/Linux_Build.html). The compiling returned no errors. Can you tell me your server specifications related to SUMO, such as the installation of SUMO, python version, stable-baseline3 version, etc.

**Comment by robertalms** [comment]
So, my model now crashed also after +6m steps, but supposedly not because of the same probem you faced, but because of a RecursionError, which I would tie to the model size I mentioned before.

![image](https://user-images.githubusercontent.com/53571755/228284696-3a4ad482-3e57-4d88-970c-50a463d31997.png)

In terms of building SUMO yourself in combination with anaconda, it's important that you provide the correct python interpreter for cmake (see documentation for additional cmake options). @behrisch Any other suggestions? I don't think the difference between some nightly 1.15 and 1.16 would have any effect on this behavior, but if there's nothing else, I could build another 1.16 and rerun everything tomorrow (as a last try, so to say).

**Comment by robertalms** [comment]
> Can you tell me your server specifications related to SUMO, such as the installation of SUMO, python version, stable-baseline3 version, etc.

@liyan2015 I simply cloned the current stable-baseline3 version from the link you provided, created a conda env with python 3.9, installed all the necessary packages, fiddled with your path-definitions until the training ran - while using my current 1.15something SUMO build on my ubuntu 20.04 server. so nothing special...

**Comment by liyan2015** [comment]
By saying "correct python interpreter for cmake", do you mean setting PYTHON_EXECUTABLE to the python path corresponding to the anaconda virtual env? For example, I have a conda env named "rl" with python=3.9, I must set PYTHON_EXECUTABLE to the python path used in the env to compile SUMO?

**Comment by robertalms** [comment]
correct

**Comment by liyan2015** [comment]
I used `cmake -D PYTHON_EXECUTABLE=/home/yan_l/anaconda3/envs/rl/bin/python ../..` to recompile SUMO 1.16.0. Now running my envs with libsumo still fails but returns a more detailed stack trace:
![Clip_20230329_000956](https://user-images.githubusercontent.com/10633479/228302333-dd7812c8-d5d2-48f8-9693-5e65270e46b4.jpg)

**Comment by robertalms** [comment]
@liyan2015 Well, with libsumo I just successfully trained for 10m steps in about 1:40h - no errors. I noticed that the memory did not increase (opposed to the traci run) - so apparently traci cashes something inconveniently, which might be relevant for @behrisch. But in terms of reproducing your crash, I can only try one more time with 1.16, tomorrow.

**Comment by behrisch** [comment]
@liyan2015 Can you maybe have an eye on memory consumption, too? Even if your memory is bigger than Robert's it would still be good to know

**Comment by liyan2015** [comment]
I tested my code on another server in our lab, and SUMO runs smoothly... There is definitely something wrong with the first server setup.

**Comment by behrisch** [comment]
Thanks @robertalms for looking into it!

**Comment by robertalms** [comment]
@behrisch Is there anything left to discuss about the memory issue or is that clear already, that traci cashes stuff which libsumo doesn't?

**Comment by behrisch** [comment]
If you can craft a small example, it would be helpful to find memory leaks

**Comment by liyan2015** [comment]
Nothing to discuss further. My other server runs well on training. Thank you @behrisch @robertalms for the guidance on this issue!
