### ISSUE TITLE
how to set the lane change only by traci?

### ISSUE THREAD

**Issue by dongyu768** [eclipse/sumo#12904]
How to make a car change lanes only through traci, but not at all other times?

**Comment by namdre** [comment]
`traci.vehicle.setLaneChangeMode(vehID, 0)`
or possible `traci.vehicle.setLaneChangeMode(vehID, 256)`
https://sumo.dlr.de/docs/TraCI/Change_Vehicle_State.html#lane_change_mode_0xb6
