### ISSUE TITLE
 the point sets of two boundaries of a road

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#12903]
Hello，how to obtain the point sets of two boundaries of a edge? (As shown by the red edge in the figure)?
![image](https://user-images.githubusercontent.com/54823725/227712880-231603a5-5666-41e2-8d76-864a36241422.png)

**SUMO-version:1.16**

**operating system:Windows**

**Comment by namdre** [comment]
`sumolib.geomhelper.move2side`
or 
`sumolib.geomhelper.line2boundary`

**Comment by a-123-du** [comment]
> `sumolib.geomhelper.move2side` or `sumolib.geomhelper.line2boundary`
Ok ,thank you very much.But I can't find its usage in the document. Should I pass in the whole list of values for this shape? 
For example, if I give the shape list of the dividers in the middle of the lane (as shown by the red line in the figure), and then give the width w, can I get the shape point set of my road boundary (as shown by the blue line in the figure) by using this line2boundary interfaceFor example, if I give the shape list of the dividers in the middle of the lane (as shown by the red line in the figure), and then give the width w, can I get the shape point set of my road boundary (as shown by the blue line in the figure) by using this line2boundary interface?
![37cebbf4d35b7030250dca23363e788](https://user-images.githubusercontent.com/54823725/227863361-0be09493-e7e9-41e5-90a2-529cd7a97908.png)
![3ba58e9440cede7a5fc95170bf4b7a6](https://user-images.githubusercontent.com/54823725/227863796-48698eea-0c23-4b03-b2a6-bda16cde2473.png)

**Comment by namdre** [comment]
I encourage you to discover these things on your own. If you pass in a shape and look at the result it should be quite obvious what the method does.

**Comment by a-123-du** [comment]
> 我鼓励你自己发现这些东西。如果您传入一个形状并查看结果，则该方法的作用应该很明显。

OK，thank you.I will have a try.
