### ISSUE TITLE
Wrong OpenDRIVE lane speed limit position 

### ISSUE THREAD

**Issue by m-kro** [eclipse/sumo#12906]
OpenDRIVE speed limits can be placed at a certain position along a lane (the so-called `sOffset`). The position is the same for both directions, but the `s` coordinate increases in the road direction = in the direction of the lanes with negative indices.

While the position of a speed limit change is transferred correctly into sumo, in the case of lanes with positive indices it is interpreted as the end of the speed limit.

**Comment by namdre** [comment]
I think this was by design, based on the assumption that the speed limits are the same in both directions. Hence the start in forward direction is the end in reverse direction.

**Comment by m-kro** [comment]
Yes, but this is stated in a rather hidden manner in the standard (in the text it says the speed limit is valid in the direction of the increasing s coordinate, but in the attribute table it reads "start position").
