### ISSUE TITLE
How to show a weaving car in Sumo

### ISSUE THREAD

**Issue by harirRzi** [eclipse/sumo#12905]
Add your issue description here.

*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**
Hello. I'm working with sumo and I want to show a car flow but among them there should be car that has weaving behavior. How can I show it in sumo? I appreciate of any help.

**Comment by namdre** [comment]
there several ways to force a lanechange:
- set departLane, arrivalLane for that car (if the route is short)
- define waypoints (https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#stops_and_waypoints)
- use TraCI https://sumo.dlr.de/docs/TraCI.html

**Comment by namdre** [comment]
for smooth weaving, see https://sumo.dlr.de/docs/Simulation/SublaneModel.html

**Comment by harirRzi** [comment]
Thank you so much for your help.

**Comment by harirRzi** [comment]
Hello. In command prompt, I went to the directory where my sumocfg file is and write the following command sumo --lateral-resolution 0.8 -c demo.sumocfg and after opening my sumo cfg file in Sumo-guy application, I can not see each lane division to 4 subleases. Did I do correctly to divide the lane to 4 subleases ignorer to make a car to weave smoothly in a lane?

**Comment by namdre** [comment]
Yes. For the impact of the resolution option, see https://sumo.dlr.de/docs/Simulation/SublaneModel.html#lateral_resolution_and_vehicle_position

**Comment by harirRzi** [comment]
If I want to make the car to have weaving behavior seems like I have to define a speed for the stop tag like <stop lane="end_1" endPos="10" speed="13.89"/>. Is it possible to set the speed for the stop to be the same as the car's previous speed (The speed before entering the position mentioned in Stop tag)?

**Comment by behrisch** [comment]
If you just use a high value for the `speed` it will be automatically reduced to the safe speed.

**Comment by JackYang2022** [comment]
> If I want to make the car to have weaving behavior using waypoints, seems like I have to define a speed for the stop tag like `<stop lane="end_1" endPos="10" speed="13.89"/>`. Is it possible to set the speed for the stop to be the same as the car's previous speed (The speed before entering the position mentioned in Stop tag)?

@namdre @behrisch Hello，what should I do if I want to set the speed for the stop using Traci ? Thanks.

**Comment by namdre** [comment]
`traci.vehicle.setStopParameter(vehID, stopIndex, "speed", str(speed))`
