### ISSUE TITLE
 bus stop additional file in Routesampler

### ISSUE THREAD

**Issue by dominique-AR** [eclipse/sumo#12901]
# Using `routesampler `to generate route file and asking how to add a bus stop

Hi [@namdre, 
I'm asking for help. I use routesampler to merge public transport traffic from turn-count data and manual embedded route. It works well but I'm not able to stop my buses at the bus stop.
It works with the manual embedded route but when I used to add the code line inside the routed vehicles file It doesn't work anymore. 

This work:

```
<vehicle id="v_3" depart="0.00" color="red">
        <route edges="311385272#5 311385272#6 303459216 303459215#0 303459215#1 527575285#0 527575285#1 28863240#0 28863240#1 28863240#2 28863240#3 581551799 581551802 527575284 527575283 580966905 303455656#0 303455656#1 303455656#2 303455656#3 303455656#4 303455656#5 303455656#6 732507984 910533996 732507982 304652154 303459681#0 303459681#1 303459681#2 303459681#3 577830093 303455655 -707056102#3 -707056102#3.67 -28930701#0 -E5 -E4 -E3"/>
        <stop busStop="bs_1" duration="60.00"/>
```

This doesn't:

    <vehicle id="b0_2" depart="11.08" type="bus">
        <route edges="311385272#5 311385272#6 303459216 303459215#0 303459215#1 527575285#0 527575285#1 28863240#0 28863240#1 28863240#2 28863240#3 581551799 581551802 527575284 527575283 580966905 303455656#0 303455656#1 303455656#2 303455656#3 303455656#4 303455656#5 303455656#6 732507984 910533996 732507982 304652154 303459681#0 303459681#1 303459681#2 303459681#3 577830093 303455655 -707056102#3 -707056102#3.67 -28930701#0 -E5 -E4 -E3"/>
        <stop busStop="bs_1" duration="60.00"/>

So I have two questions:
1- Does this error occured because of the incrementation of <stop busstop inside <route?
2- Is it possible to let routesampler add automatically for each bus a stop or should we add it manually?

Thanks,

**SUMO-version:**
SUMO 1.15

**operating system:**
Windows 10

<img width="653" alt="Route Bus-Stop" src="https://user-images.githubusercontent.com/108085848/227542726-c659cd49-2461-4905-8169-bd802968d75a.png">

**Comment by namdre** [comment]
routeSampler.py is not compatible with public transport as it simply ignores any stops in the input. While this might be changed with little effort, there is also a conceptual gap: routeSampler randomly distributes traffic in each measurement interval whereas public transport runs according to fixed and regular schedules.  

If you can describe the exact use case and expectations for the generated scenario, I might have an idea on how to accomplish them with existing tools.

**Comment by dominique-AR** [comment]
Thanks @namdre,

It's not possible to use bus stop with routesampler now. But is it possible to generate flow from counting-data inside routesampler? And then,  taking the bus.rou.xml (with flow not vehicle), and to implement a python loop adding an xml line for each lane corresponding to the bus stop. Does it make sense?

**Comment by namdre** [comment]
You could add the stops in post processing (i.e. with python). However, now you can also load routes with stops and routeSampler will carry them over to the output if you set option **--keep-stops**.

Note, that the stops must be child elements of the route like this:

```
<route ...>
   <stop .../>
</route>
```

rather than
```
<vehicle ...>
  <route .../>
  <stop .../>
</vehicle>
```

PS: I didn't initially make the connection with the public transport in Tana. There it makes a lot of sense to preserve the stops since they don't follow a schedule anyway.

**Comment by dominique-AR** [comment]
Thanks Jackob,
yes I forgotted to mention that, sorry. So I guess I have to take the routesampler from github then?

**Comment by namdre** [comment]
yes

**Comment by namdre** [comment]
yes
