### ISSUE TITLE
Questions about traci code

### ISSUE THREAD

**Issue by jianki1314** [eclipse/sumo#12936]
How can I output the travel time of the vehicle? The travel time is defined as the time taken by the vehicle from the generated position, through the various road sections to the last intersection.

**Comment by namdre** [comment]
- while the vehicle is still driving: `traci.simulation.getTime() - traci.vehicle.getDeparture(vehID)`
- to have the value after the vehicle has arrived is, store the departure time for every vehicle (i.e. with the help of `simulation.getDepartedIDList()` and then use it with `simulation.getArrivedIDList()`
- you can get the average duration of all arrived vehicles with `traci.simulation.getParameter("device.tripinfo.duration")` (this requires to run the simulation with option **--tripinfo-output** or **--duration-log.statistics**)

**Comment by jianki1314** [comment]
Thank you, sir.
