### ISSUE TITLE
Why is the search function of the official websites useless

### ISSUE THREAD

**Issue by SongKun2023** [eclipse/sumo#12934]
![59fbf18fcf3185d933f606a9c49de4c](https://user-images.githubusercontent.com/97946646/228244595-e4025afe-f3c6-45f5-a382-b4ea590915ab.png)

**Comment by m-kro** [comment]
Which browser do you use?

**Comment by SongKun2023** [comment]
I'm so sorry sir, It's network problem. Now, it can works. Thank you for your response.
