### ISSUE TITLE
 AttributeError: partially initialized module 'traci' has no attribute 'start' (most likely due to a circular import)

### ISSUE THREAD

**Issue by Y-AMDIAZ** [eclipse/sumo#12941]
Please , I had this issue and I don t know how I resolve it ; 

![image](https://user-images.githubusercontent.com/129278941/228507268-a2faaaf0-8f23-4b07-8fce-cf9c2e257a2a.png)

**Comment by namdre** [comment]
From what kind of environment are you trying to use traci?

**Comment by Y-AMDIAZ** [comment]
> From what kind of environment are you trying to use traci
is the probleme of TraCI4Traffic Lights by using the detector of traffic (vehicul emergency ) , and I found a programme on (data/traci_tls) but isnt working I dont know why . 
![image](https://user-images.githubusercontent.com/129278941/228522744-194ea11c-ce32-4299-94cf-a7b59476f13c.png)

**Comment by namdre** [comment]
- What version of SUMO are you using?
- what python interpreter are you using (https://www.mathworks.com/help/matlab/ref/pyenv.html)

**Comment by Y-AMDIAZ** [comment]
I use the last version , and I want to tell me if you know where I can find the detector (capture)  on Sumo Just like that , how can find it : 
![image](https://user-images.githubusercontent.com/129278941/228562375-e0c238fa-9842-45d1-8dcf-951aa3a121d3.png)

**Comment by namdre** [comment]
Your question of "where I can find the detector (capture) on Sumo" is ambiguous. You can find the documentation at https://sumo.dlr.de/docs/Simulation/Output/Induction_Loops_Detectors_%28E1%29.html
