### ISSUE TITLE
Lane change from Traci is not executed when a route is set

### ISSUE THREAD

**Issue by mpfist-no** [eclipse/sumo#12944]
This issue may be related to my recently resolved issue #12810. 

In my scenario, a lane change that I request via TraCI is not executed when I explicitly set a route that contains more than only the current edge (see the attached example).
Also, it doesn't matter if the second lane change goes to the right or to the left.

Minimum working example: [lanechange-route-bug.zip](https://github.com/eclipse/sumo/files/11101375/lanechange-route-bug.zip)

**SUMO-version:** current main branch & 1.15.0

**operating system:** Windows 10

**Comment by namdre** [comment]
fixed in 58272511811e798d7e56e0487bc2540491d330f5

**Comment by mpfist-no** [comment]
Thanks @namdre for the quick fix.

I've been playing around with this situation a bit more and one more question has come up: I modified the example from the initial issue report to do a right lane change instead of a left lane change (as second lane change). Also, I manually re-set the route just before the second lane change: 

```
step = 0
    while step < 1000:
        traci.simulationStep()
        traci.vehicle.setLaneChangeMode(VEHICLE_ID, 0b00_01_00_00_00_00)
        # Remove the next statement to make the second lane change work
        # traci.vehicle.setRoute(VEHICLE_ID, ["-9#1", "-9#2"])
        if step == 20:
            traci.vehicle.changeLaneRelative(VEHICLE_ID, 1, 10)
            traci.vehicle.highlight(VEHICLE_ID, alphaMax=255, duration=0.1)
        if step == 60:
            traci.vehicle.changeLaneRelative(VEHICLE_ID, -1, 10)
            traci.vehicle.setRoute(VEHICLE_ID, ["-9#1", "-9#2"])
            traci.vehicle.highlight(VEHICLE_ID, alphaMax=255, duration=0.1)
        step += 1
```
![image](https://user-images.githubusercontent.com/94060139/230093614-ec476e23-bc1b-4101-b4f7-c6b4c50f87bb.png)

With the current main branch I see that the vehicle signals for the second lane change, but does not execute it. I assume it is because the next edge of the route is not reachable from the lane where I want it to change to. Is this correct? 

If so, is there are way to enforce a lane change no matter what the route is?

**Comment by namdre** [comment]
the failed change was due to #13007
