### ISSUE TITLE
Wrong dead-end edges

### ISSUE THREAD

**Issue by gladysmcgan** [eclipse/sumo#12957]
I have some edges in my network that dead-ends or dead-starts when they are supposed to be connected to the next edge. I would like to ask how the connections between edges are guessed by netconvert, and if there is any fix or netconvert setting that could solve these errors? 
A few examples from the network, dead-end/start edges: 191828216#2, -791941939#0_0, 543698012#2_0, 152001420#3_0

![191828216#2](https://user-images.githubusercontent.com/59922884/228913103-fc9938d1-6da5-4b75-ab46-acdc2307d1a8.png)

And a side question, a similar issue exists for lanes, i.e. lanes in an edge has no connection to lanes on next edge. But I wonder if affects the simulation very much, since cars can still access the next edge and change lanes within it? If so, is there also a solution for this? 
dead-end/start lanes: -270084158_0, -410265080_1, -4721156#1_1

![-270084158_0](https://user-images.githubusercontent.com/59922884/228913124-d65846af-c103-455e-9b7d-f2437978030b.png)

Many thanks!

OSM and SUMO network in here: [Google drive folder](https://drive.google.com/file/d/1vZkrD9mMTY2HQsEk67DSNBrEsrzT963S/view?usp=sharing)

SUMO netconvert Version 1.16

**Comment by namdre** [comment]
for edge 191828216#2, the reason is found in the osm data:
```
<relation id="9201641" version="1">
		<member type="way" ref="191828216" role="from"/>
		<member type="node" ref="775938713" role="via"/>
		<member type="way" ref="29199468" role="to"/>
		<tag k="restriction" v="no_right_turn"/>
		<tag k="type" v="restriction"/>
	</relation>
```

for -791941939#0 it's similar:
```
<relation id="10997261" version="1">
		<member type="way" ref="791941939" role="from"/>
		<member type="node" ref="7403508828" role="via"/>
		<member type="way" ref="791941939" role="to"/>
		<tag k="restriction" v="only_u_turn"/>
		<tag k="type" v="restriction"/>
	</relation>
```


The lack of connection to lane -270084161#2_1 will have not practical effect on simulation behavior since vehicles will change lane instantly if the prefer this lane.

**Comment by gladysmcgan** [comment]
Ach my mistake, sorry. And thanks!
