### ISSUE TITLE
Bluelight Device ,Emergency Vehicle Simulation

### ISSUE THREAD

**Issue by Y-AMDIAZ** [eclipse/sumo#12951]
hi , just I want to use a Emergency Vehicle on SUMO , and I took a look on the documentry of sumo but I'dont know how can I add the Emergency Vehicle on Sumo , I write that on my.rou.xml 
![image](https://user-images.githubusercontent.com/129278941/228797685-ebc6796f-4d51-485f-8249-756dfa201dd7.png)

they did'nt give me anythings just can you  give me somethings to continue , I think the probleme on Traci I should write a algorithme that define the Emergency Vehicle
ps : I found that but I dont know how can I use it , 
[traci.vehicle.setParameter(vehID, "device.bluelight.reactiondist", str(value))]

**Comment by Y-AMDIAZ** [comment]
I will add it on my.rou.xml , ?

**Comment by m-kro** [comment]
Yes. Just enhance the already defined type "CarA" in your file according to the template I posted. Obviously the other attributes of the vType can stay as they are.

**Comment by Y-AMDIAZ** [comment]
I think should I create a fils Traci on python

**Comment by m-kro** [comment]
Now you have an invalid XML file. Here is a [tutorial ](https://www.w3schools.com/xml/xml_syntax.asp)you can read more about XML in general. Please just do as previously explained and put the param tag as a child element of your vType tag:
```
<vType id="CarA" accel="2.0"> <!-- with all the attributes, you already had that line from the beginning, just pay attention to the tag ending -->
    <param key="has.bluelight.device" value="true"/>
</vType>
```

**Comment by m-kro** [comment]
Well you have defined the id attribute twice, otherwise it should be OK

**Comment by Y-AMDIAZ** [comment]
It still give me erreur
![image](https://user-images.githubusercontent.com/129278941/228830193-748712a2-70bf-4323-a537-5f1ae3a20d02.png)
I enhance just on my.rou.xml , should I enhance on somewhere ? for exemple should I use Traci  by using python  or not ?

**Comment by m-kro** [comment]
Please just follow this [example scenario](https://sumo.dlr.de/extractTest.php?path=sumo/devices/bluelight/multiple). I cannot help you more than that.

**Comment by Y-AMDIAZ** [comment]
thank you very much
