### ISSUE TITLE
question for lane use

### ISSUE THREAD

**Issue by SongKun2023** [eclipse/sumo#12973]
Add your issue description here.
Hello, sir. I want to know why is the rightmost lane not being used?  The allowed vehicle class of the lane is vip before. Then, I use rerouter to change it. Now, the disallowed vehicle class of the lane is vip, but all the vehicle types in simulation are not vip. I don't know the reason. Could you give me some advice?  Some screenshots are as follows.

![df42a58885570c4354ef7cc5c01da64](https://user-images.githubusercontent.com/97946646/229276630-deeebe7b-6e44-4ed5-bb15-808e2050d8aa.png)

![b9488b17c0862fc6e657f9a3fa12ab3](https://user-images.githubusercontent.com/97946646/229276640-a443cd36-116a-4b2c-a03a-54123cc81374.png)

SUMO-version:1.16

operating system: Windows

**Comment by namdre** [comment]
the next lane on the right appears to be forbidden so during congested traffic, cars would also avoid the previous lane because they cannot easily change back.

**Comment by SongKun2023** [comment]
OK, sir. But I find that there is no car entering the lane during uncongested traffic.

**Comment by SongKun2023** [comment]
For example, I set a E2 detector, according to the output of the detector, there is no car entering the lane. Some screenshots are as follows:

![af4a7498c0acaa8a01f696415c0a3d7](https://user-images.githubusercontent.com/97946646/229400484-6e61e8c0-cb22-475d-8b43-7df9a5c03b7c.png)

**Comment by SongKun2023** [comment]
![ce1b5f7267e786b407d0a5ef792ea96](https://user-images.githubusercontent.com/97946646/229400966-8430c57e-c1b7-4845-9c07-54123555495a.png)

**Comment by SongKun2023** [comment]
How to explain this problem?

**Comment by m-kro** [comment]
Vehicles plan which lane they want/need to use with some lookahead distance. They decide on the lane to use considering their route and the possible speed under the current traffic conditions. If they stayed on the right lane only for a short stretch and could go at least as fast on the neighbour lane, they might choose the neighbour lane right away.

There are chances you can change this behaviour through the [lane change model parameters](https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#lane-changing_models), playing with `lcStrategic` and `lcKeepRight`.

**Comment by SongKun2023** [comment]
Thank you sir. If I want to alleviate traffic congestion and simulate dynamic road expansion, how can I do?

**Comment by SongKun2023** [comment]
Do I have to change this behaviour through the lane change model parameters?

**Comment by SongKun2023** [comment]
Sir, can you give me a reply?

**Comment by m-kro** [comment]
Yes, you have to change the lane change model parameters.

**Comment by SongKun2023** [comment]
If this, is it different from closing or opening lane in SUMO GUI ?

**Comment by m-kro** [comment]
These are two separate topics: 
- lane access (precondition for selecting a lane at all)
- lane change model parameters (preferred lane among the accessible ones)

**Comment by SongKun2023** [comment]
OK， Thank you.
