### ISSUE TITLE
Unsupported traffic light type '2'

### ISSUE THREAD

**Issue by Batuhun** [eclipse/sumo#12974]
At the start of the simulation I have a traffic light that is type 2. Logic printed out by getAllProgramLogics: 

_Logic(programID='0', type=2, currentPhaseIndex=0, phases=(Phase(duration=0.001, state='GG', minDur=0.001, maxDur=0.001, next=()), Phase(duration=5.0, state='yy', minDur=5.0, maxDur=5.0, next=()), Phase(duration=0.001, state='rr', minDur=0.001, maxDur=0.001, next=()), Phase(duration=3.0, state='uu', minDur=3.0, maxDur=3.0, next=())), subParameter={'min-green-time': '5.0', 'opening-delay': '3.0', 'opening-time': '3.0', 'space-gap': '-1.0', 'time-gap': '108.0', 'yellow-time': '3.0'})_

When I try to set a new logic with type 2 I get Error: **Answered with error to command 0xc2: Unsupported traffic light type '2'**.
the code I used to set the new logic:

_trafficLightLogic = traci.trafficlight.Logic(programID='1', type=2, 
                                                subParameter={'min-green-time': '5.0', 'opening-delay': '3.0', 'opening-time': '3.0', 'space-gap': '-1.0', 'time-gap': '30.0', 'yellow-time': '3.0'},
                                             currentPhaseIndex=0,
                                             phases=(traci.trafficlight.Phase(duration=0.001, state='GG', minDur=0.001, maxDur=0.001, next=()), traci.trafficlight.Phase(duration=5.0, state='yy', minDur=5.0, maxDur=5.0, next=()), traci.trafficlight.Phase(duration=0.001, state='rr', minDur=0.001, maxDur=0.001, next=()), traci.trafficlight.Phase(duration=3.0, state='uu', minDur=3.0, maxDur=3.0, next=())))

traci.trafficlight.setProgramLogic("J4",trafficLightLogic)
traci.trafficlight.setProgram("J4","1")_

Thanks for the help in advance.

**SUMO-version:1.15.0**

**operating system:Windows 10**

**Comment by namdre** [comment]
type is a rail crossing. You cannot define new programs for these because they follow their own hard coded logic with a fixed sequence of phases.
