### ISSUE TITLE
Routing Algorithms

### ISSUE THREAD

**Issue by TrinhTuanHung2021** [eclipse/sumo#12979]
![image](https://user-images.githubusercontent.com/82990411/229526642-b6cce372-6258-4419-afd7-24b4ee336347.png)
Hello. 
I am using algorithms in Sumo to simulate traffic. I want to implement navigation in my models. 
But according to the instructions, there is little information related to Dijkstra and Astar. Could you please let me know about the formulas you used in Sumo? How do you define the shortest route in Dijkstra? And the probability that vehicles choose that route. I saw that first, vehicles choose the shortest routes and next they choose the other routes to travel.
Thank you very much

**Comment by m-kro** [comment]
In general the routing algorithms work with the travel time associated to the current route option.
