### ISSUE TITLE
About the stopping time of busSTop in SUMO

### ISSUE THREAD

**Issue by 2p0h1** [eclipse/sumo#12972]
I know that in your simulation software you set the "duration" or "until" attribute in the "rou.xml" file to artificially set the bus stopping time before the simulation starts. But now I want to set the bus stop time according to the number of passengers in the "busStop" during the simulation.

So how should I proceed? Sincerely hope to hear from your team.

**Comment by namdre** [comment]
duration is only the minimum duration. The stopping time automatically increases according to the number of passengers based on the value of `boardingDuration` (per passenger that embarks/disembarks).
