### ISSUE TITLE
netconvert OSM turn:lanes with 1.16 vs dev. version

### ISSUE THREAD

**Issue by ambuehll** [eclipse/sumo#12978]
netconvert does not build the right connections for OSM way 371732298. 

turn-lanes and vehicle-lanes from OSM: 

		<tag k="turn:lanes" v="through|slight_right|through"/>
		<tag k="vehicle:lanes" v="yes|yes|no"/>

in 1.15 this worked like a charm where private lanes were correctly mapped (with the bus lane being unconnected though).
Now, in 1.16, it generates a "slight_right" for the bus-lane (vehicle:lanes "no") and two "through" connections. 

see below (sorry for the colours)

1.15:
<img width="507" alt="image" src="https://user-images.githubusercontent.com/48930860/229484425-e0e2b7de-aae9-4e10-aace-6d3778a708eb.png">

1.16:
![Image 03 04 23 at 12 40](https://user-images.githubusercontent.com/48930860/229486879-196effbc-ad90-4d3f-9f7d-806962aa25dc.jpg)

**SUMO-version:**1.15 vs current

[files](https://drive.google.com/drive/folders/1wCIqNJjpoB5lPGbwUWr-nGRn5SAX2rWe?usp=sharing
)

**Comment by m-kro** [comment]
So in essence you need an intersection where neighbour lanes are in conflict with each other (the bus lane crosses the right turn)? If I remember correctly, this is still a problematic case in SUMO...

**Comment by ambuehll** [comment]
Yes, that's it. It's correctly tagged in OSM, but then netconvert changes the turn:lanes order somehow. 
The thing is it didn't do so in sumo 1.15 - back then the car lane connections were correct. (probably because now the bus lane connectivity is better).

**Comment by m-kro** [comment]
I could reproduce the issue only in the development version, not in the v1.16 release.

**Comment by ambuehll** [comment]
Sorry to come back to this, but it seems to me as if this is not yet fixed in the newest nightly:
v1_16_0+2119-c93da6fc232
<img width="409" alt="image" src="https://user-images.githubusercontent.com/48930860/233294629-707bba18-3f0b-4d27-ac4e-79b705a92b36.png">
not sure, where I went wrong.

**Comment by namdre** [comment]
you are using an outdated nightly (+2119) but need at least v1_16_0-2131-gcac8ec2

**Comment by ambuehll** [comment]
ahhh. downloaded "Windows zip with all extras" from the nightly, which is the one lagging behind by two days. thanks and sorry! :)
