### ISSUE TITLE
Uniform motion in the intersection

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#12981]
Hello, how to make the car move at uniform speed inside the intersection? Does SUMO provide the corresponding interface？ Thank you very much
![image](https://user-images.githubusercontent.com/54823725/229755418-54fb8ca7-b589-4159-ad99-e272f1ed044b.png)

**SUMO-version:1.16**

**operating system:Windows**

**Comment by m-kro** [comment]
The maximum speed inside the intersection is influenced by the turning radius and assigned during the build process of the network. There is no switch to disable the feature completely, but you can process your network such that it doesn't happen anymore under any meaningful conditions (see the [netconvert paramer list](https://sumo.dlr.de/docs/netconvert.html#junctions)):
`netconvert -s input.net.xml --junctions.limit-turn-speed.min-angle 180 -o output.net.xml`

Only turns with an angle of more than 180 degrees between the incoming and the outgoing lane would then be impacted by the turn speed limit. Alternatively you can raise the lateral acceleration above which the speed limit is applied through the netconvert parameter **--junctions.limit-turn-speed**.

**Comment by a-123-du** [comment]
> 交叉路口内的最大速度受转弯半径的影响，并在网络的构建过程中分配。没有完全禁用该功能的开关，但您可以处理您的网络，使其在任何有意义的条件下不再发生（请参阅[netconvert参数列表](https://sumo.dlr.de/docs/netconvert.html#junctions)）： `netconvert -s input.net.xml --junctions.limit-turn-speed.min-angle 180 -o output.net.xml`
> 
> 只有在进车道和出车道之间角度超过 180 度的转弯才会受到转弯速度限制的影响。或者，您可以通过 netconvert 参数 --**junctions.limit-turn-speed 提高**横向加速度，高于该加速度即可应用速度限制。

I'm not quite sure what you mean. What I want to achieve is that the car can keep a constant speed in the intersection.

**Comment by a-123-du** [comment]
> > 交叉路口内的最大速度受转弯半径的影响，并在网络的构建过程中分配。没有完全禁用该功能的开关，但您可以处理您的网络，使其在任何有意义的条件下不再发生（请参阅[netconvert参数列表](https://sumo.dlr.de/docs/netconvert.html#junctions)）：`netconvert -s input.net.xml --junctions.limit-turn-speed.min-angle 180 -o output.net.xml`
> > 只有在进车道和出车道之间角度超过 180 度的转弯才会受到转弯速度限制的影响。或者，您可以通过 netconvert 参数 --**junctions.limit-turn-speed 提高**横向加速度，高于该加速度即可应用速度限制。
> 
> 我不太确定你的意思。我想要实现的是汽车可以在十字路口保持恒定速度。

Or how do you keep the car moving at its current speed for a certain amount of time?

**Comment by namdre** [comment]
If you set option **--junctions.limit-turn-speed 0** then no turn speed limits will be applied at junctions.
