### ISSUE TITLE
NEMA Controller fails if uneven yellow time at barrier

### ISSUE THREAD

**Issue by mschrader15** [eclipse/sumo#12989]
@EGDoge showed that the current implementation of the NEMA controller will get stuck at the barrier if yellow times are not the same. 

Desired behavior is the phase with shorter yellow + red time enters into red transfer state, waiting indefinitely for the others to terminate, then crossing the barrier together.

I have a fix implemented, need to finish test cases. Just creating this issue to track the bug.

**Comment by namdre** [comment]
Thanks!
