### ISSUE TITLE
FatalTraCIError: could not connect

### ISSUE THREAD

**Issue by prajwalvinod** [eclipse/sumo#12982]
I am not able to open the sumo-gui from python using the simple command example on the sumo website. As a way to solve it I changed the path variables, uninstalled and reinstalled sumo, tried generating log files (although I don't know how to access those).  Attaching error message below.

Error message while trying to open GUI from Python
* Retrying in 1 seconds
Could not connect to TraCI server at localhost:51818 [WinError 10061] No connection could be made because the target machine actively refused it
 Retrying in 1 seconds
Could not connect to TraCI server at localhost:51818 [WinError 10061] No connection could be made because the target machine actively refused it
 Retrying in 1 seconds
Could not connect to TraCI server at localhost:51818 [WinError 10061] No connection could be made because the target machine actively refused it
 Retrying in 1 seconds
Could not connect to TraCI server at localhost:51818 [WinError 10061] No connection could be made because the target machine actively refused it
 Retrying in 1 seconds

FatalTraCIError                           Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_14208\2788396650.py in <module>
     18 import traci
     19 
---> 20 traci.start(sumoCmd,traceFile="traci.log")
     21 
     22 traci.close()

C:\Program Files (x86)\Eclipse\Sumo\tools\traci\main.py in start(cmd, port, numRetries, label, verbose, traceFile, traceGetters, stdout, doSwitch)
    145         sumoProcess = subprocess.Popen(cmd2, stdout=stdout)
    146         try:
--> 147             result = init(sumoPort, numRetries, "localhost", label, sumoProcess, doSwitch, traceFile, traceGetters)
    148             if traceFile is not None:
    149                 connection.get(label).write("start", "%s, port=%s, label=%s" % (repr(cmd), repr(port), repr(label)))

C:\Program Files (x86)\Eclipse\Sumo\tools\traci\main.py in init(port, numRetries, host, label, proc, doSwitch, traceFile, traceGetters)
    114     pool concurrently.
    115     """
--> 116     con = connect(port, numRetries, host, proc, 1, traceFile, traceGetters, label)
    117     if doSwitch:
    118         switch(label)

C:\Program Files (x86)\Eclipse\Sumo\tools\traci\main.py in connect(port, numRetries, host, proc, waitBetweenRetries, traceFile, traceGetters, label)
    104                 print(" Retrying in %s seconds" % waitBetweenRetries)
    105                 time.sleep(waitBetweenRetries)
--> 106     raise FatalTraCIError("Could not connect in %s tries" % (numRetries + 1))
    107 
    108 

FatalTraCIError: Could not connect in 61 tries*

Code Snippet

**import os, sys

if 'SUMO_HOME' in os.environ:
    tools = os.path.join(os.environ['SUMO_HOME'], 'tools')
    sys.path.append(tools)
else:
    sys.exit("Please declare the environment variable 'SUMO_HOME'")

sumoBinary = "C:/Program Files (x86)/Eclipse/Sumo/bin/sumo-gui.exe"
sumoCmd = [sumoBinary, "-c", "hegyi_net.sumocfg"]

import traci

traci.start(sumoCmd,traceFile="traci.log")

traci.close()**

Please let me know if you need any additional information

**SUMO-version: 1.16.0**

**operating system: Windows 11**

**Comment by m-kro** [comment]
Do you have very restrictive firewall settings? Does the python script have the rights to execute the sumo binary?

**Comment by behrisch** [comment]
try calling `sumo-gui` from the command line first and look whether warnings / errors pop up

**Comment by prajwalvinod** [comment]
Hey, yes I am able to call sumo-gui from command line. Sorry for the late reply. I am working on multiple things.

**Comment by prajwalvinod** [comment]
I get the error that 'subprocess' is not defined. Do I have to import another library for this ?

**Comment by prajwalvinod** [comment]
As an additional measure I checked the path of SUMO and it has been set as shown on the website.

**Comment by prajwalvinod** [comment]
`import os, sys
import subprocess
import sumolib

if 'SUMO_HOME' in os.environ:
    tools = os.path.join(os.environ['SUMO_HOME'], 'tools')
    sys.path.append(tools)
else:
    sys.exit("Please declare the environment variable 'SUMO_HOME'")

sumoBinary = "C:/Program Files (x86)/Eclipse/Sumo/bin/sumo-gui.exe"
# subprocess.call([sumoBinary])
sumoCmd = [sumoBinary, "-c", "hegyi_net.sumocfg"]


import traci

traci.start(sumoCmd)

traci.close()`

This is the code I am using. If there are any modifications to this that I can try please let me know. 

Also does it matter if the config file is in C:\ drive just like the SUMO installation files or does that not make a difference ?

**Comment by Cahune** [comment]
u r my super hero :_) thank you so muchhhhhhh <3

**Comment by Transyltooniaa** [comment]
Can you explain this in detail please
