### ISSUE TITLE
Crash if netedit tries to save demand/additionals into non-writable dir

### ISSUE THREAD

**Issue by Davidez86** [eclipse/sumo#12984]
I try to follow the instructions for HELLO WORLD (tutorial beginners).

when I do: save the Demand (route + vehicle) file . Use File -> Demand elements -> Save demand elements (Ctrl + Shift + D) 

then the software is crashed. NETEDIT IS CLOSED IMMEDIATELY.

What is the problem?

SUMO-1.16.0 

WINDOWS 10 64 BIT

**Comment by m-kro** [comment]
I cannot reproduce the problem on my side following the steps of the tutorial. Can you maybe provide the network file, a screenshot just before the crash or anything else which might help?

**Comment by Davidez86** [comment]
I have attached the file vidoe with screen recording. I don't see any massege. Netedit crashed.

**Comment by Davidez86** [comment]
https://user-images.githubusercontent.com/18556011/229887896-4b1a573e-5dd5-44a2-ad59-13c3726ef4ac.mp4

**Comment by Davidez86** [comment]
Hi,
could you help me?

Il giorno mar 4 apr 2023 alle ore 19:49 Mirko Barthauer <
***@***.***> ha scritto:

**Comment by m-kro** [comment]
Do you have write access in the folder you wanted to save the demand file?

**Comment by m-kro** [comment]
We have changed a few things in the netedit code. Could you please wait until tomorrow and then try the same process with the SUMO development version available [here](https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_development_version)?

**Comment by Davidez86** [comment]
> 

Perfect, now it is working!
SUMO development version (10th april) after the comand  "save demand element" I see the following error "Saving demand element failed - Permission denied". Now I have changed the directory path to a writable directory.
Thank you for the important and fast support!
