### ISSUE TITLE
qst about sumo urgent

### ISSUE THREAD

**Issue by Y-AMDIAZ** [eclipse/sumo#12993]
I have a qst about a communication between vehicule on sumo I want to send a message from vehicule to vehicule , (OBU) and how I can make an accident  , if the accident is done , automaticaly the vehicule of emergency will run to a place of accident , by using OBU or RSU , so sumo can do that or I should use an other application please

**Comment by angelobanse** [comment]
How to simulate an accident -> https://sumo.dlr.de/docs/FAQ.html#how_to_simulate_an_accident
Deliberately causing collisions -> https://sumo.dlr.de/docs/Simulation/Safety.html#deliberately_causing_collisions

**Comment by m-kro** [comment]
Emergency vehicles: -> [https://sumo.dlr.de/docs/Simulation/Emergency.html](https://sumo.dlr.de/docs/Simulation/Emergency.html)

Note that you have to [reroute ](https://sumo.dlr.de/docs/Simulation/Routing.html#traci)the emergency vehicle to the accident location. Whether this is triggered by Car2X messages or some other mechanism depends on your interest in network communication. If you want to model the communication part in detail, then please read about in e.g. on the [Veins site](https://veins.car2x.org/). Veins is  a combination of sumo and the communication simulation OMNeT++.

**Comment by Y-AMDIAZ** [comment]
Thanks , So if I use veins I can send message between vehicules  ?

**Comment by behrisch** [comment]
You can always send "messages" between the vehicles by remote controlling them using the traci or libsumo interface. The problem you are trying to solve is probably solvable without veins by just using traci.

**Comment by Y-AMDIAZ** [comment]
my probleme is when I have an accident on sumo ,  they send message to a vehicule (V2V)  that near  of  accident and search the ambulance ( they search for tha ambulance that is near to an accident  ) whene they found it , it will go to a place of accident .
so should I use veins to use V2V and traci for accident ?
