### ISSUE TITLE
How to make a flow of cars to have weaving behavior in some random time

### ISSUE THREAD

**Issue by harirRzi** [eclipse/sumo#12997]
Add your issue description here.

*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**
Hello. I have a flow of cars and I need some of the cars to have weaving behavior not all the time but in some random time. Is it possible to do it by using a specific function for all the cars without doing it manually for each car by using for example Traci? Also my other question is how can I make a car to have sometime to swerving behavior and sometime to have unsafe lane change?

**Comment by namdre** [comment]
- random swerving: with a small bit of work you can use https://sumo.dlr.de/docs/Tools/Routes.html#random_stopping to create random waypoints. Simply do a search and replace on the added stops to exchange attribute `duration="x"` with `speed="x"`.  You can run the tool multiple times to have multiple waypoints per vehicle
- unsafe changes: see https://sumo.dlr.de/docs/Simulation/Safety.html#lane-changing_model (setting lcAssertive is the easiest way to reduce safety)
