### ISSUE TITLE
How to make a vehicle to turn around in the middle of a lane?

### ISSUE THREAD

**Issue by ShanJiang-2020** [eclipse/sumo#12999]
I want a vehicle in the middle of a lane to turn around, because I have to reassign its route due to emergency events on some lanes.
Anyone knows the corresponding command?

![image](https://user-images.githubusercontent.com/73733728/230711131-b40b0df1-1f9a-46a6-9b8e-1182e98983de.png)

**SUMO-version: 1.15.0**

**operating system: win10**

**Comment by behrisch** [comment]
I assume you use TraCI. You probably have to use traci.vehicle.moveToXY and make sure you do not let the vehicle keep its current route. After that you also need to set a new route.

**Comment by ShanJiang-2020** [comment]
> I assume you use TraCI. You probably have to use traci.vehicle.moveToXY and make sure you do not let the vehicle keep its current route. After that you also need to set a new route.

Thanks a lot! I think moveToXY could solve my problem.

**Comment by ShanJiang-2020** [comment]
> I assume you use TraCI. You probably have to use traci.vehicle.moveToXY and make sure you do not let the vehicle keep its current route. After that you also need to set a new route.

Thanks a lot! I think moveToXY could solve my problem.
