### ISSUE TITLE
How sumo step is implemented for each vehicle? And how to speed up the simulation?

### ISSUE THREAD

**Issue by lola-notraffic** [eclipse/sumo#13002]
Hello,
I want to understand how sumo step is implemented in terms of each vehicle. Do all the vehicles in simulation make step in parallel or partially some after another?
I am asking, because the simulations where i have a lot more vehicles are much slower. So i am trying to understand if it is from my side or sumo step takes more time if it is more vehicles.
Besides sumo step length definition (which is currently 1 sec which is high), is there any way to speed up the simulation?
Thank you in advance.

**SUMO-version:*1.13.0*
**operating system:* ubuntu 20.04*

**Comment by behrisch** [comment]
sumo is not parallelized yet, so yes the vehicle step is executed iteratively for all the vehicles and thus the simulation gets slower the more vehicles you have in it. Concerning speed-up thewre are some tips in the [FAQ](https://sumo.dlr.de/docs/FAQ.html#how_can_i_make_the_simulation_run_faster)
