### ISSUE TITLE
problems after loading state

### ISSUE THREAD

**Issue by Ljiaooo** [eclipse/sumo#13005]
I use the python API traci to save buses' and passengers' states (with --save-state.transportables), but when I use traci.simulation.loadstate() to load the state, the passengers don't get on the bus which they are supposed to get on. Actually the passengers just don't get on any buses. Could anyone help? Thanks in advance.

**Comment by Ljiaooo** [comment]
I found the buses's vtype was not loaded by loadstate(), which caused the problem. How can I fix this problem.

**Comment by Ljiaooo** [comment]
I found the vehicles were not loaded with vtype which caused the problem. How can I load the vehicles with vtype?

**Comment by namdre** [comment]
In case the problem persists, can you provide (minimal) input files that showcase the problem?

**Comment by Ljiaooo** [comment]
> In case the problem persists, can you provide (minimal) input files that showcase the problem?

Sorry for my late reply. Here is a minimal test example. 
[minimal.zip](https://github.com/eclipse/sumo/files/11238051/minimal.zip)

**Comment by behrisch** [comment]
Please add another comment if the problem persists.
