### ISSUE TITLE
OSError: [WinError 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by buntyk48** [eclipse/sumo#13001]
Trying to start the simulation using the script:

import traci
traci.start(sumoCmd)
step = 0
while step < 1000:
    traci.simulationStep()
    if traci.inductionloop.getLastStepVehicleNumber("0") > 0:
        traci.trafficlight.setRedYellowGreenState("0", "GrGr")
    step += 1

traci.close()

SUMO-version: 1.16.0

**operating system: Windows 11
![Screenshot (36)](https://user-images.githubusercontent.com/96794970/230731865-b9b8c373-5fa9-42b7-b522-4875d7c8fa70.png)

**Comment by behrisch** [comment]
Please try whether running `sumo-gui` or `sumo` works from the command line. Furthermore there are sometimes problems with anaconda which brings its own libraries which can conflict with the ones SUMO brings. So if you can try to do this with a plain python installation.

**Comment by buntyk48** [comment]
I tried running the sumo-gui from the command line and it runs. I also installed python 3.11 again but the error still appears.  
@behrisch

**Comment by namdre** [comment]
what is the value of `sumoCmd` ?

**Comment by namdre** [comment]
`sumoBinary` should be something like `sumo` or `"c:\Program Files (x86)\Eclipse\Sumo\bin\sumo"`

**Comment by namdre** [comment]
If you cannot solve the remaining problem ("I still cannot run the simulation"), please post more details and I'll reopen this ticket.

**Comment by buntyk48** [comment]
Thank you very much for your kind support. Issues are solved. There were some path-related issues in the .sumocfg file.
