### ISSUE TITLE
How to speed up the simulation?

### ISSUE THREAD

**Issue by SongKun2023** [eclipse/sumo#13003]
Add your issue description here.

Hello, sir. I find it very slow when I simulate a large network. It's far from my expectation, is there some method to speed up the simulation?  I set the threads value in .sumocfg, but it's useless.

**Comment by behrisch** [comment]
Please describe your scenario in more detail and tell us which other tips of the [FAQ](https://sumo.dlr.de/docs/FAQ.html#how_can_i_make_the_simulation_run_faster) you already tried.

**Comment by SongKun2023** [comment]
I set the threads value with three in .sumocfg as follows, it is useless for speeding up simulation  and my simulation crashed.

![b8eea7384f5852ea2fedd0294fe7263](https://user-images.githubusercontent.com/97946646/230886710-9b2d1f68-d559-4762-810f-0c4a8275cc3d.png)

**Comment by SongKun2023** [comment]
And I find a way to speed up simulation on [https://github.com/philliptay/Parallel-Sumo](url). is this method produced by your team?

**Comment by behrisch** [comment]
> I set the threads value with three in .sumocfg as follows, it is useless for speeding up simulation and my simulation crashed.
> 
> ![b8eea7384f5852ea2fedd0294fe7263](https://user-images.githubusercontent.com/97946646/230886710-9b2d1f68-d559-4762-810f-0c4a8275cc3d.png)

Yes, multithreading is still experimental.

**Comment by SongKun2023** [comment]
OK, sir. When will you finish the function of multithreading ? Because the multithreading is useful in large network simulation.

**Comment by namdre** [comment]
The work on multithreading will likely not be finished this year.
In most our usage contexts, the need to speed up a single simulation is low even for large simulations because a single simulation is not enough. 
This is due to the stochastic nature of many scenarios and the need to average out *noise* over multiple runs.
When running multiple simulations it is trivial to run them in parallel and thereby making use of the available compute power.

**Comment by sdsjb** [comment]
> The work on multithreading will likely not be finished this year. In most our usage contexts, the need to speed up a single simulation is low even for large simulations because a single simulation is not enough. This is due to the stochastic nature of many scenarios and the need to average out _noise_ over multiple runs. When running multiple simulations it is trivial to run them in parallel and thereby making use of the available compute power.

This is a misconception because, for example, such an important task as simulation of a large city (for example, for the purpose of automatic real-time traffic control) requires exactly the possibility of parallelization. That is why SUMO vitally needs this feature.
