### ISSUE TITLE
findRoute

### ISSUE THREAD

**Issue by HasanHaydarY** [eclipse/sumo#13009]
![Screenshot_133](https://user-images.githubusercontent.com/94067819/231143289-bd178f3b-ea66-436d-b936-f273df47624e.png)

I don't get it. Can someone help me why i am getting this error?

**SUMO-version:1.14.1

**operating system:Microsoft Windows 10

**Comment by namdre** [comment]
get rid of the `self` argument to `findRoute`. The current call interprets `destination` as the third argument (which is `vType`).

**Comment by HasanHaydarY** [comment]
Thank you for your help but now i am getting this error.

![image](https://user-images.githubusercontent.com/94067819/231562831-572b0deb-9920-4f2d-a8f7-d0902f4c5fbc.png)

**Comment by namdre** [comment]
findRoute returns a Stage object. use `vehicle.setRoute(vehID, findRoute(...).edges)`

**Comment by HasanHaydarY** [comment]
traci.vehicle.setRoute(vehId,traci.simulation.findRoute(location, destination, vType='taxi', depart=-1.0, routingMode=0))

Do you mean like this? I tried like this and got the same error.

**Comment by namdre** [comment]
no. the important point is the `.edges` part where you use the edges from the stage object. See 

https://github.com/eclipse/sumo/blob/c93da6fc23290d8e600ea885c516c9d638218f0d/tools/traci/_simulation.py#L27-L55

**Comment by HasanHaydarY** [comment]
I get it now. Thank you so much!
