### ISSUE TITLE
invalid bestLanes computation on a highway

### ISSUE THREAD

**Issue by Domsall** [eclipse/sumo#13021]
I have a highway scenario with very high speedlimits (German highway).

What I am seeing: Vehicles change to the left, stay there and never go back to the right or the middle (3-lane highway). I tried changing the LC-parameters, but nothing changed. They only go back at lower speedlimits.
I debugged the scenario and took a look at the Code. The vehicles are all jumping out of the wants_change-function here:

https://github.com/eclipse/sumo/blob/d42d89b6f550f83614558a7459d929798a2c73ea/src/microsim/lcmodels/MSLCM_LC2013.cpp#L1599-L1611

The vehicles are driving on the highway and are not on the on-ramp.

Do you have a test scenario on a highway, where the speedlimit is above 100 km/h? My scenario is quite large and would not be suitable for a test / to show the issue.

**SUMO-version:** 1.16.0

**operating system:** Windows

**Comment by namdre** [comment]
fix is long overdue: #4374

**Comment by Domsall** [comment]
After digging deeper, the issue does not seem to arise from the on-ramp heuristic.
You received a test case via Mail.

**Comment by namdre** [comment]
Indeed, this isn't about the lanechange model but rather about the part where lanes are classified according to their strategic value (`MSVehicle::updateBestLanes`).

**Comment by Domsall** [comment]
The length of the lanes changed after updating the z-values of each lane. I was a bit confused why the bestLanes were valid in some cases and in some not (although all lanes/edges differ in length).

Thank you very much for the fast fix!

**Comment by namdre** [comment]
How exactly where the z-values updated? Normally, the lane length written in .net.xml should be the average of all lanes.

**Comment by Domsall** [comment]
I am not fully sure, my algorithm just changed the z-values, but I must have changed the length, too. After opening the network in netedit and saving it from there, the length of the lanes go back to the same value for each edge. Sorry for the inconvenience.
