### ISSUE TITLE
Add check method for control status of vehicle

### ISSUE THREAD

**Issue by pshai065** [eclipse/sumo#13029]
Is there a method that can check if existing SUMO vehicle is in a platoon, its place in the platoon, and what are its following, preceding and leading vehicles? Can we also get location of these vehicles in terms of x,y coordinates and the edges and lanes they are currently on?  (all using python)
Also, is there a way to change the rate of electric consumption of the vehicles in SUMO using python?

*If possible, upload an example that shows your problem.*

**SUMO-version:** latest 

**operating system:** macOS

**Comment by m-kro** [comment]
Regarding simpla: 
At the moment you can enumerate all platoon members (see [docs](https://sumo.dlr.de/docs/Simpla.html#getplatoonidlist_and_getplatooninfo)) and then derive individual vehicle IDs of your interest. Using these vehicle IDs as an input parameter for methods like `traci.vehicle.getLaneID` (see [ref](https://sumo.dlr.de/pydoc/traci._vehicle.html#VehicleDomain-getLaneID)), you can derive lane & edge, `traci.vehicle.getLanePosition` for the position along the lane. To get XY coordinates, see `traci.simulation.convert2D` ([ref](https://sumo.dlr.de/pydoc/traci._simulation.html)).

But I take your suggestion to offer a more direct access to check whether a vehicle is controlled through simpla.

**Comment by m-kro** [comment]
You can update the battery device parameters as shown in this example using `traci.vehicle.setParameter`:

https://github.com/eclipse/sumo/blob/ccfe441f1f92c1d045f10f73974ee6c7569726d6/tests/complex/traci/vehicle/vehicle/runner.py#L460
