### ISSUE TITLE
How to upgrade sumo version 1.12.0 to 1.13.0 in Mac OS

### ISSUE THREAD

**Issue by harirRzi** [eclipse/sumo#13023]
Add your issue description here.

*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**
Hi. I want to use Poisson distribution for my car flow and seems like I need to use it in  Sumo version 1.13.0. My previous Sumo version was 1.11.0 and after trying to upgrade it, it just upgrades to 1.12.0. I appreciate if there is any suggestion for helping me how can I do it?

Here is the error when I use period="ex(0.01)" in `<flow id="carflow" type="car" beg="0" number="15" speedFactor="0.5" route="route_0" departLane="random" departPos="random_free" period="exp(0.01)"/>`:
 Attribute 'period' in definition of flow 'carflow' is not a time value.

**Comment by namdre** [comment]
this easiest way should be this:  https://sumo.dlr.de/docs/Downloads.php#python_packages_virtual_environments

**Comment by namdre** [comment]
You can try `pip install -i https://test.pypi.org/simple/ eclipse-sumo`
According to our logs, there should be up-to-date dev packges for python veresions 3.6-3.10

**Comment by harirRzi** [comment]
I wrote the command you mentioned in command prompt and it says `"zsh: command not found: pip"`

**Comment by namdre** [comment]
[please consult the internet on how to install pip](https://stackoverflow.com/questions/17271319/how-do-i-install-pip-on-macos-or-os-x)

**Comment by behrisch** [comment]
Also did you just try uninstalling and re-installing again with brew? https://sumo.dlr.de/docs/Installing/index.html#macos
The pypi index lists a 1.16 release for macOS: https://pypi.org/project/eclipse-sumo/#files Can you report your macos version?
