### ISSUE TITLE
How to show car straddling on a marked line between two lanes

### ISSUE THREAD

**Issue by harirRzi** [eclipse/sumo#13025]
Add your issue description here.

*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**
Hi. I need to show a car straddling meaning that it should drive on a marked line that is between two lanes. For doing this I activated sublane model by using following command: `sumo --lateral-resolution 0.8 -c demo.sumocfg` and in python script I tried to add the following code:

```
if step==500:
      traci.vehicle.changeSublane("veh_1", -3.1)
```

However, I can not see at that time step, that the car is straddling. I appreciate if any one can help me with this.

**Comment by m-kro** [comment]
Remember negative values indicate moving to the right. Is there a neighbour lane on the right side?

**Comment by harirRzi** [comment]
I'm using sumo version 1.12.0 and I wrote the following code in my python script, however I don't see car straddling. I even can't see the car's change its sublime!

```
if step==500:
      traci.vehicle.changeSublane("veh_1", 1.6)
      traci.vehicle.setLaneChanageMode(vehID, 0)
```

I appreciate if anyone helps me.

**Comment by harirRzi** [comment]
> Remember negative values indicate moving to the right. Is there a neighbour lane on the right side? And do you use the last release or an older SUMO version?

I'm using Sumo version 1.12.0.

> * to drive between lanes you need to move by a half lane width (so rather 1.6)
> * to have the car stay there, disable the default model behavior with `setLaneChanageMode(vehID, 0)`

Also here is  what I defined about the car in routes.rou.xml that should have straddling behavior:
```
<route id="route_0" edges="e1 e2"/>
<vType id="drunk_2" vClass="passenger" accel="3.5" decel="2.5" color="red"/>
<vehicle id="d2" type="drunk_2" depart="28" number="1" route="route_0" lcPushy="1" lcSigma="1" lcAssertive="1.5" departPosLat="random"/>
```

**Comment by harirRzi** [comment]
I think this command that I execute in command prompt while I'm in the directory where demo.sumocfg file is,  doesn't work.

sumo --lateral-resolution 0.8 -c demo.sumocfg

**Comment by m-kro** [comment]
Calling the command line version of sumo with additional parameters will activate these for the current run but not save them to the configuration file. Either add the same parameters to your sumo-gui call or execute this first to update your configuration:
`sumo --lateral-resolution 0.8 -c demo.sumocfg --save-configuration demo.sumocfg`

**Comment by Han21-yes** [comment]
>       traci.vehicle.setLaneChanageMode("veh_1", 0)
> ```
It's "setLaneChangeMode". You misspelled
