### ISSUE TITLE
Change vehicle shape

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#13030]
Because I have rectangles of car in my model, how do I make my car a rectangle? Instead of the following.Thank you very much
![`4(D(27YJLY `M(SKOJMDV](https://user-images.githubusercontent.com/54823725/231960113-d2fd358e-1de6-4daf-abf7-96f1da780025.jpg)

**SUMO-version:1.16.0**

**operating system:Windows**

**Comment by m-kro** [comment]
Open the [GUI settings](https://sumo.dlr.de/docs/sumo-gui.html#changing_the_appearancevisualisation_of_the_simulation). Choose "boxes" as [vehicle shape](https://sumo.dlr.de/docs/sumo-gui.html#vehicle_shape_schemes).
