### ISSUE TITLE
I need to stop a  vehicle for a certain amount of time sumo

### ISSUE THREAD

**Issue by Y-AMDIAZ** [eclipse/sumo#13034]
I need to stop a vehicle for a certain amount of time, but I can't do it statically, 
since it is dependant by the simulation.

What is the best method to stop a vehicle and then restart it when the 
time expires?

**Comment by m-kro** [comment]
`traci.vehicle.setStop` (see [ref](https://sumo.dlr.de/pydoc/traci._vehicle.html#VehicleDomain-setStop)) allows to define stops dynamically using TraCI (see [docs ](https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#stops_and_waypoints)on the stop concept).

**Comment by Y-AMDIAZ** [comment]
I want to stop my vehicule emergence , whene they receive a msg from a vehicule than they go , so should I use stop or parking ?

**Comment by Y-AMDIAZ** [comment]
<parkingArea id="ParkAreaA" lane="a_0" startPos="200" endPos="250" roadsideCapacity="5" angle="45" length="30"/> 
i add this on the fils.nod.xml where I add it 
<parkingArea id="ParkAreaB" lane="b_0" startPos="240" endPos="260" roadsideCapacity="0" width="5" length="10" angle="30">
    <space x="853" y="623"/>
    <space x="863" y="618"/>
    <space x="873" y="613"/>
    <space x="883" y="608"/>
    <space x="893" y="603"/>
    <space x="848" y="611" width="4" length="8" angle="120"/>
    <space x="858" y="606" width="4" length="8" angle="120"/>
    <space x="868" y="601" width="4" length="8" angle="120"/>
    <space x="878" y="596" width="4" length="8" angle="120"/>
    <space x="888" y="591" width="4" length="8" angle="120"/>
</parkingArea>
and that alsoo

**Comment by m-kro** [comment]
You can add parking spaces in [additional files](https://sumo.dlr.de/docs/Simulation/Basic_Definition.html#additional_files).

**Comment by Y-AMDIAZ** [comment]
![image](https://user-images.githubusercontent.com/129278941/232054868-9585c416-b2da-4138-9737-4327f3202539.png)
![image](https://user-images.githubusercontent.com/129278941/232055127-5f6d50b8-1552-4e73-92b8-b10f97bc2971.png)
it gave me erreur :
