### ISSUE TITLE
How to simulate dynamic shoulder lane situtation ?

### ISSUE THREAD

**Issue by Jinbo0201** [eclipse/sumo#13048]
How to create a highway with shoulder lanes?
And, how to open or close dynamic shoulder lanes in the simulation process？

**Comment by m-kro** [comment]
You create all the lanes you ever need beforehand, e.g. in netedit. There (in [inspect mode](https://sumo.dlr.de/docs/Netedit/editModesCommon.html#inspecting_lanes)) you set the access permissions for each lane as you want them to be at the simulation begin. In your case, all vehicles would be forbidden on the outmost lane.

During the simulation, you can change the permissions using `traci.lane.setAllowed` ([ref)](https://sumo.dlr.de/pydoc/traci._lane.html#LaneDomain-setAllowed) / `traci.lane.setDisallowed` ([ref](https://sumo.dlr.de/pydoc/traci._lane.html#LaneDomain-setDisallowed)).

**Comment by Jinbo0201** [comment]
Thank you, useful!

**Comment by Jinbo0201** [comment]
![shoulder lane](https://user-images.githubusercontent.com/44746291/232663301-ea8acf91-8a4f-4407-9bd7-548e407116e1.png)

**Comment by Jinbo0201** [comment]
Another question about dynamic shoulder lanes
I open the shoulder lane by using traci.lane.setAllowed. However, no cars enter the shoulder lane, as shown in the above picture.

**Comment by namdre** [comment]
It's more likely that cars don't  *want* to enter the shoulder lane because the lane is quite short and they would have to change lanes at the end of it. trying opening a longer sequence of shoulder lanes at the same time.

**Comment by Jinbo0201** [comment]
Yes. When I extend the length of hard shoulders opening, there are cars entering the shoulder.
Thanks.
