### ISSUE TITLE
SUMO File Locations

### ISSUE THREAD

**Issue by prajwalvinod** [eclipse/sumo#13040]
Do the configuration files have to be in the same directory/drive where SUMO has been installed like C:/ ? If not will it cause errors while trying to load files through Python using TraCI ?

**SUMO-version: 1.16**

**operating system: Windows 11**

**Comment by m-kro** [comment]
No, the configuration files don't need to be in the same directory as the executable. However you still have to care about the right path, e.g.:

- add the SUMO_HOME/bin directory to the PATH env variable
- consider the current working directory you run the command from
- check whether you have write rights in the directories the sumo output shall be written to
