### ISSUE TITLE
get the average speed of a edge

### ISSUE THREAD

**Issue by Clown1206** [eclipse/sumo#13044]
Add your issue description here.
Hello,I want to get the average speed of a certain edge over a period of time during the simulation (e.g., every 5 minutes).
*If possible, upload an example that shows your problem.*

**SUMO-version:**
sumo1.16.0
**operating system:**
win10

**Comment by namdre** [comment]
https://sumo.dlr.de/docs/Simulation/Output/Lane-_or_Edge-based_Traffic_Measures.html

**Comment by Clown1206** [comment]
> https://sumo.dlr.de/docs/Simulation/Output/Lane-_or_Edge-based_Traffic_Measures.html

Thank you for your answer. I haven't used this method yet. If I use this method, will I get the data I want after the sumo simulation (such as the average speed of a certain road section every five minutes)?

**Comment by namdre** [comment]
Yes. Subject to configuring the aggregation period as documented.

**Comment by Clown1206** [comment]
> Yes. Subject to configuring the aggregation period as documented.

Can I get period-aggregated data during the sumo simulation run. Because I want to use the average speed of the previous several times on a particular stretch of road to predict the speed of the next period of time.

**Comment by namdre** [comment]
To obtain aggregated values at runtime, define detectors according to your exact needs (https://sumo.dlr.de/docs/Simulation/Output/index.html#simulated_detectors) and use TraCI functions for aggregated retrieval (i.e.  [`traci.lanearea.getLastIntervalMeanSpeed`](https://sumo.dlr.de/docs/TraCI/Lane_Area_Detector_Value_Retrieval.html))

**Comment by Clown1206** [comment]
I also have a question about generating traffic flow. Is there any way to generate regular traffic flow (such as morning rush hour and evening rush hour for commuting)?
