### ISSUE TITLE
vehroute-output error

### ISSUE THREAD

**Issue by leejs-2022** [eclipse/sumo#13051]
I am doing a simulation using sumo. During the simulation, congestion occurred due to vehicles stopped inside the intersection, so when loading the previous save file, 'load-state.remove-vehicles' was used to remove the vehicle in question. However, since the tool has a limit on the number of vehicle's that can be removed, traci was used to load the saved file, and the necessary vehicle was removed using traci.vehicle.remove, then saved again, and the saved file was loaded and used in sumo-.

After using this method, there were no problems in the simulation, but errors occurred in other parts.
--vehroute-output is used to determine the vehicle movement path, but when the save file that written by traci is loaded and the simulation is executed, an error occurs in the exit_time of the vehicles recorded in the save file among the information recorded in vehroute-output. .
Following the exit-time of the path recorded in the save file, the exit-time generated by the simulation should be recorded. The previous record is ignored and the exit-time is recorded at the first position. For the edge of the route, the previous simulation record remains, but only the exit-time is newly recorded, so it is not possible to determine the route and passage time. I am wondering how can I solve it.

I used SUMO-1.41. on windows

**Comment by namdre** [comment]
- there should be no limit to the number of vehicles that can be removed with **--load-state.remove-vehicles**. If you the shell/command line doesn't accept enough arguments, put the option and it's arguments into a .sumocfg file instead
- to ignore congestion inside intersections you can also set option: **--ignore-junction-blocker TIME**.
- restoring exit times after loading state is working in my test for the current version. Please try upgrading your SUMO version. If it still fails after this, please provide a minimal failing example. (and I will then re-open this ticket)

**Comment by leejs-2022** [comment]
thank you so much!
I have reason not to change version. so I will try to use sumocfg file.
