### ISSUE TITLE
libsumo segfault in simulation step

### ISSUE THREAD

**Issue by jjyyxx** [eclipse/sumo#13053]
See reproducing script `LIBSUMO_AS_TRACI=1 python trace.py`
[repro2.zip](https://github.com/eclipse/sumo/files/11259400/repro2.zip)

To my understanding, it seems that under certain conditions, `myLane` of vehicle '181' became inconsistent with `myCurrEdge` in `MSVehicle::getDistanceToPosition`. `myCurrEdge` (ID: "7") points to the end of the route, while `myLane` (ID: ":1_***") is internal, so `myCurrEdge + 1` leads to out-of-bound read.

Interestingly, this is not quite reproducible with traci (with or without GUI), but I did not investigate further.

**SUMO-version:** 1.16.0 & main

**operating system:** Ubuntu 22.04.1

**Comment by namdre** [comment]
I can confirm that it crashes with libsumo but not with traci. strange indeed.

**Comment by namdre** [comment]
the same problem (access of end iterator occurs) when running with traci. The difference between traci and libsumo is due to c++ "undefined behavior" in this case.

**Comment by jjyyxx** [comment]
So it can be considered lucky that libsumo at least crashes in time. 🤣

**Comment by jjyyxx** [comment]
@namdre Thanks, and one more question, is there a simple workaround for this that only needs to change the net.xml (and do not need to upgrade to a dev version)? For example, last time regarding #12063 and #12065, we workarounded by avoiding parallel internal junctions for three-way intersections, enforcing at most two lanes for each edge.

**Comment by namdre** [comment]
Avoiding parallel internal junctions will probably be enough to avoid the problem. 
However, we're planning release 1.17.0 for next week so you could simply use that instead of dev.
