### ISSUE TITLE
Connection to TraCI server lost while using veins Omnet++ 

### ISSUE THREAD

**Issue by Y-AMDIAZ** [eclipse/sumo#13076]
![image](https://user-images.githubusercontent.com/129278941/233311133-c016d6ff-f053-4bfb-96b9-02178f746cb7.png)
![image](https://user-images.githubusercontent.com/129278941/233311403-022a2117-e407-4f60-9bec-907d3fc65675.png)
plz ant help here 
I dont know where can I  fixe the probelm

**Comment by m-kro** [comment]
Did you manage to complete the [Veins tutorial](https://veins.car2x.org/tutorial/)? Does the error occur with the tutorial files or with your custom ones?

**Comment by behrisch** [comment]
Closing for lack of feedback. Feel free to add another comment if you have more information.
