### ISSUE TITLE
carFollowing-Krauss's acc

### ISSUE THREAD

**Issue by jianki1314** [eclipse/sumo#13071]
Can the acceleration value at time t given by 1 be obtained by traci in a default-following model, such as carFollowing-Krauss.

**Comment by namdre** [comment]
I don't understand what you mean by the phrase "given by 1".
- You can retrieve a vehicle's acceleration in the previous step using `vehicle.getAcceleration`
- if you call `simulation.executeMove`, you can also retrieve the acceleration in the current step (but before outputs have happened).

**Comment by JJ-passion** [comment]
Hello, the description of Krauß-model is "the Krauß-model with some modifications which is the default model used in SUMO". Could you please tell me what specific content has been modified in carFollowing-Krauss.  Since I am not a C++ user, is there any relevant literature introduction?
