### ISSUE TITLE
1.16 vs current: turning lane connects with bus lane instead of car lane

### ISSUE THREAD

**Issue by ambuehll** [eclipse/sumo#13087]
similar to #12978
same data as #12978

1.16:
<img width="448" alt="image" src="https://user-images.githubusercontent.com/48930860/233412027-d158fed3-7a7c-46fe-8b64-56ee3c6d1dd4.png">

current build:
<img width="493" alt="image" src="https://user-images.githubusercontent.com/48930860/233416184-aab91802-dca0-404b-9c22-0b86c696c3b9.png">

**SUMO-version:** 1.16 vs current

**Comment by namdre** [comment]
in contrast to #12978, there is no `turn:lanes` data in the OSM.
The layout here has to be resolved based on common sense (which is much harder :smile: )

**Comment by ambuehll** [comment]
just wanted to reply, and then I saw you just fixed it. Many thanks! 👍

**Comment by namdre** [comment]
As it turned out we had several test networks that were suffering from disconnects due to having their "natural" continuation lane marked as dedicated. Thanks for pointing out this one!

**Comment by ambuehll** [comment]
just double-checked. 
The southern approach with its right turning lane still connects with the bus lane. I don't know if that's intended with this fix. 

<img width="445" alt="image" src="https://user-images.githubusercontent.com/48930860/233571700-8b407560-45b4-4102-8054-4519b4c11bcf.png">

sumo Version v1_16_0+2269-f45ba1c2a90

**Comment by namdre** [comment]
whereas #12978 was about applying turnSigns after applying a standard pattern of connections and #13087 was about permitting double connections to satisfy all modes, the final(?!)  fix was about finding correct lanes when applying turnSigns.

**Comment by ambuehll** [comment]
perfect! I think this fix is related to https://github.com/eclipse/sumo/issues/10080, but didn't fix it.

**Comment by namdre** [comment]
#10080 was about about rechecking vClasses after applying a standard pattern of connections
