### ISSUE TITLE
How can I let a vehicle stop at a parking area and then travel to its destination?

### ISSUE THREAD

**Issue by tranvary** [eclipse/sumo#13092]
I'm trying to use TRACI to let a vehicle stop at a certain parking area for 20 seconds and then travel to its destination.This vehicle is defined as below:
`    <trip id="6" depart="0.60" from="B1C1" to="D3E3" type="EV"/>`
and I try to use
`    traci.vehicle.insertStop(vehID="6",nextStopIndex=0,edgeID="ParkAreaB",flags=64,duration=20)`
to let this vehicle stop at "ParkAreaB" for 20 seconds and then travel to edge = "D3E3".However，after it finishes its stop at "ParkAreaB",it doesn't travel to its original destination "D3E3".
What should I do to fulfill my purpose?

**Comment by namdre** [comment]
it should work the way you expect and the problem is most likely due to some misunderstanding somewhere. Can you attach the scenario files and traci code that you used (zipped)?

**Comment by tranvary** [comment]
[traci.zip](https://github.com/eclipse/sumo/files/11294550/traci.zip)
I hope this car will travel to its original destination after it finishes its stop.However,it leaves the simulation at the lane where the  parking area is located

**Comment by namdre** [comment]
It was a bug after all, you can download the fixed version tomorrow at https://sumo.dlr.de/docs/Downloads.php#nightly_snapshots
