### ISSUE TITLE
SUMO configuration error

### ISSUE THREAD

**Issue by Chenyu3194** [eclipse/sumo#13090]
Hi everyone,

I'm new to SUMO Simulation and I'm learning to edit some networks and routes in order to generate a configuration file. However when I started the automactically generated sumocfg file, the sumo-gui always shows: 

Error: No nodes loaded.
Error: Failed to build network.

I cheked the sumocfg with the text editor and it seems to be fine:

<configuration>
    <net-file value="D:\Studium an der TU Braunschweig\HiWi\Arbeit\SUMO\Config\junction.net.xml"/>
    <route-files value="D:\Studium an der TU Braunschweig\HiWi\Arbeit\SUMO\Config\junction.rou.xml"/>
</configuration>

I can get access to the sumocfg with MATLAB or Python but cannot open the file directly with sumo-gui 

Hope this issue is not hard to solve and thanks at first for any solution!

**SUMO-version:** NETEDIT 1.15.0

**operating system:** Win11

**Comment by palvarezlopez** [comment]
Hi! Can you attach the sumo config file and network?

**Comment by namdre** [comment]
it looks as if you are trying to load a .sumocfg with a menu that expects to load e .neteditcfg

**Comment by namdre** [comment]
the error message `Error: Failed to build network.` can only come from netconvert or netedit
