### ISSUE TITLE
SUMO incompatible with swig > 4.0 ?

### ISSUE THREAD

**Issue by meerfrau** [eclipse/sumo#13094]
swig 4.1.1 leads to a compilation failure:
```
[ 72%] Swig compile libsumo.i for java
:1: Error: Unable to find 'swig.swg'
:3: Error: Unable to find 'java.swg'
./src/libsumo/libsumo_typemap.i:356: Error: Unable to find 'std_shared_ptr.i'
./src/libsumo/libsumo_typemap.i:374: Error: Unable to find 'std_string.i'
./src/libsumo/libsumo_typemap.i:375: Error: Unable to find 'std_vector.i'
./src/libsumo/libsumo_typemap.i:376: Error: Unable to find 'std_map.i'
./src/libsumo/libsumo_typemap.i:387: Error: Unable to find 'std_pair.i'
./src/libsumo/libsumo_typemap.i:395: Error: Unable to find 'exception.i'
```

**SUMO-version:** git master

**operating system:** Linux

**Comment by behrisch** [comment]
Can you please share which Linux you use and where your swig comes from?

**Comment by meerfrau** [comment]
[ArchLinux](https://archlinux.org/packages/extra/x86_64/swig/files/)

**Comment by RNippold** [comment]
I tried to do a build from scratch in a clean Arch installation. All went well, apart from some problems with gtest as this is min c++14 and Sumo is still built with c++11:
 
[ronald@archlinux bin]$ sumo
Eclipse SUMO sumo Version v1_17_0+0008-32330d3f0f5
 Build features: Linux-6.2.12-arch1-1 x86_64 GNU 12.2.1 Release FMI Proj GUI Intl SWIG tcmalloc GDAL FFmpeg OSG GL2PS
 Copyright (C) 2001-2023 German Aerospace Center (DLR) and others; https://sumo.dlr.de
 License EPL-2.0: Eclipse Public License Version 2 <https://eclipse.org/legal/epl-v20.html>
 Use --help to get the list of options.

What version of maven and openjdk did you install? Any (other) warnings from running cmake?

**Comment by RNippold** [comment]
And just to add:

[ronald@archlinux cmake-build]$ swig -version

SWIG Version 4.1.1

Compiled with g++ [x86_64-pc-linux-gnu]

Configured options: +pcre

Please see https://www.swig.org for reporting bugs and further information

**Comment by meerfrau** [comment]
Oh, I'm very sorry: Cleaning ./src was enough to succeed.
