### ISSUE TITLE
personFlow stopping at trainStop before riding crashes sumo-gui on completion

### ISSUE THREAD

**Issue by theDivj** [eclipse/sumo#13108]
A personflow walking to a trainstop then riding behaves as expected. (trainStop has an access onto a pedestrian only edge.)
If the flow includes a \<stop\>  at the trainStop - to model a delayed boarding - then sumo-gui may crash at the end of the simulation. (Or in the middle of a more complex simulation.) 

Under debug a null person is being drawn on an edge (line 375 of https://github.com/eclipse/sumo/blob/main/src/guisim/GUIEdge.cpp) it appears the edge immediately prior to the stop still has entries in myPersons. 

ie When the person is going edge->ride the edge is being cleaned correctly, when going from edge->stop->ride the edge is not decrementing myPersons correctly.

The crash is reliably seen in sumo-gui if the edge is visible on the screen at the time the simulation ends. The crash also happens less reliably with sumo.

A minimal example attached - the workaround is not to add the stop :)

[testaccess.zip](https://github.com/eclipse/sumo/files/11304516/testaccess.zip)

**Comment by namdre** [comment]
the crash is only in the gui but the internal state is clearly wrong as seen by fcd output:

```
   <timestep time="99.00">
        <vehicle id="LO286" x="-13.59" y="62.28" angle="269.05" type="T1" speed="0.00" pos="120.00" lane="E3_0" slope="0.00"/>
        <person id="pf1.0" x="-13.22" y="63.89" angle="179.05" speed="0.00" pos="105.00" edge="E118" slope="0.00"/>
    </timestep>
    <timestep time="100.00">
        <vehicle id="LO286" x="-13.59" y="62.28" angle="269.05" type="T1" speed="0.00" pos="120.00" lane="E3_0" slope="0.00"/>
        <person id="pf1.0" x="-13.22" y="63.89" angle="179.05" speed="0.00" pos="119.60" edge="E118" slope="0.00"/>
        <person id="pf1.0" x="-13.22" y="63.89" angle="179.05" speed="0.00" pos="119.60" edge="E3" slope="0.00"/>
    </timestep>
```

**Comment by namdre** [comment]
Thanks for the nicely small error example! This should be an inspiration to error report providers everywhere (-:

**Comment by theDivj** [comment]
On my (wintel) desktop, under VS2022 debug, the equivalent memory address failure 'crash' in sumo is when writing the summary output - ie sumo running against that example doesn't produce the summary - just the running step output - presumably the inconsistent state is what upsets sumo in preparing the summary?

**Comment by namdre** [comment]
I'd say yes., though didn't try to replicate it. Please let me know if further problems arise after my fix.

**Comment by theDivj** [comment]
That's fine - both sumo/sumo-gui working as expected - many thanks for rapid fix.
