### ISSUE TITLE
carFollowingModel, setSpeedMode clarification

### ISSUE THREAD

**Issue by Oritchimaru** [eclipse/sumo#13105]
It's not an issue or a bug, I'm just trying to understand the common grounds between carFollowingModels, setSpeedMode and weather a car ignores or no traffic lights.

I've made a simulation that is fully custom where I set my own speed on vehicles and all safety measures are turned off.

I now want to compare my results with IDM or Krauss carFollowingModel, thus I specify it in the sumocfg file, yet I still don't want cars to have signaled intersections and also reach the maximum speed on the road regardless of the speed defined in the .net.xml on edges.

What combination of the above functions should I use to achieve that?

Sorry for my disturbance, I am just super confused as the documentation is vast and it's a mistake from my side.

Best regards, Thanks in advance!

Theodore Tranos

**Comment by namdre** [comment]
- setSpeedMode only applies when calling `traci.vehicle.setSpeed`.
- If you want a default carFollowModel that ignores speedLimits, seed a high speedFactor in the vType
- If you want a car that ignores red lights or junction foes, see https://sumo.dlr.de/docs/Simulation/Safety.html#junction_model

**Comment by Oritchimaru** [comment]
> * setSpeedMode only applies when calling `traci.vehicle.setSpeed`.
> * If you want a default carFollowModel that ignores speedLimits, seed a high speedFactor in the vType
> * If you want a car that ignores red lights or junction foes, see https://sumo.dlr.de/docs/Simulation/Safety.html#junction_model

Thanks Andre for the quick response! I was away for a couple of days!

I understood everything right now, just one thing, If I want to have Krauss following model with the only difference the complete absence of traffic lights, which junction_model should I use? 
Everything else will be the same, I've set a desired min and max speed, also accel and decel, I want cars to make the right velocity adjustments according to Krauss to avoid collisions but in the same time not regarding traffic lights.

**Comment by namdre** [comment]
`<vType ... jmDriveAfterRedTime="1000"/>`

**Comment by Oritchimaru** [comment]
Thanks a lot! Will try that right away!

**Comment by Oritchimaru** [comment]
Andre,

I in my .rou.xml file I have registers of this type:

`    <vehicle id="0" depart="0.00" departLane="best" departPos="base" departSpeed="10.00"> 
<route edges="E1 E2"/> `

Thus, from what I understand there's no explicit definition of vType. I am trying this code here for .sumocfg in order to change the defaultVehicleType supposedly.

`    <defaultVehicleType vClass='passenger' carFollowModel="IDM" accel="3.0" decel="5.0" sigma="0.5" length="5.0" minGap="0" maxSpeed="20.0" minSpeed="0.0" jmDriveAfterRedTime="1000"/>`

but it doesn't seem to work, do you happen to know why this is happening? No matter what I change, the result is always deterministically the same.

**Comment by namdre** [comment]
simply set `<vehicle type="..." .../>. See https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#vehicle_types
If you want to change the default type you have to define `<vType id="DEFAULT_VEHTYPE" .../>

**Comment by Oritchimaru** [comment]
so regardless of situation I should write a script that adds a property to these vehicles at .rou.xml right? I can't do It by hand because there are like 3000 vehicles and multiple .rou files.

**Comment by namdre** [comment]
You can leave the vehicles as they are and just load another file which defines
`<vType id="DEFAULT_VEHTYPE" .../>`
in the list of route-files, load the file with the vType first.

Whichever tool you used to generated your vehicles likely supports an option to set the type as well.
