### ISSUE TITLE
Is it possible to upload a dataset in Sumo for car movement behavior?

### ISSUE THREAD

**Issue by harirRzi** [eclipse/sumo#13107]
Add your issue description here.

*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**
Hi. I want to simulate car movements meanwhile some cars will have special behavior which I will implement in Sumo. After simulation, I will produce a dataset with fcd command and then I will feed it to GAN which produce mode data by combining different data from original data I produced. I want to know is it possible to upload a dataset in sumo and see accordingly what that behavior can GAN produced?

**Comment by namdre** [comment]
https://sumo.dlr.de/docs/FAQ.html#how_do_i_generate_sumo_routes_from_gps_traces
