### ISSUE TITLE
Load XML decals fail

### ISSUE THREAD

**Issue by mehmetnedimyavuz** [eclipse/sumo#13113]
Hello, I am using the latest development version of SUMO. I am loading background images by using load xml decals button. Then images are loading unproblematically. While I would like to make netedit operations on my network,file is closing suddenly. I could not detect any error messages. Thank you for help. Regards.

**Comment by mehmetnedimyavuz** [comment]
[load_decals.zip](https://github.com/eclipse/sumo/files/11307745/load_decals.zip)

**Comment by palvarezlopez** [comment]
Thanks!

**Comment by mehmetnedimyavuz** [comment]
Thank you @palvarezlopez.
