### ISSUE TITLE
spreadtype "center" introduces issues when re-running netconvert 

### ISSUE THREAD

**Issue by ambuehll** [eclipse/sumo#13127]
1. first time running netconvert from OSM with spreadtype "center" (using same test net as always): `netconvert -c osm.netccfg`
<img width="590" alt="image" src="https://user-images.githubusercontent.com/48930860/234100656-eadabc3c-8e6c-4b60-be69-14a1471bce65.png">

2. second time running netconvert using `netconvert -s ZRH_sumo_raw.net.xml -o out.net.xml`
<img width="671" alt="image" src="https://user-images.githubusercontent.com/48930860/234100962-1607f233-0e84-439b-9f84-c2e79a853e7c.png">

test files (change spreadtype to center in the netconvert config file) here: https://github.com/eclipse/sumo/issues/12978
**SUMO-version:**current

**operating system:**Win

**Comment by namdre** [comment]
It never occured to me that people would even try to set the default to 'center'!
spreadType center only makes sense for unidirectional roads, bidirectional rail tracks or at least such roads where you handcrafted center-line shapes. By default, both directions of an osm-road have the same shape definition so they have to use spreadType 'right' or 'roadCenter' by necessity.
Maybe you meant to use --default.spreadType roadCenter ?

The observed behavior is fixable though.

**Comment by ambuehll** [comment]
Thanks. never used it before either. I was actually double checking the exact lane positions from OSM and from sumo. I always used roadCenter, but I found some cases where center was more precise. I guess it depends on OSM quality. 
to make sure I understand correctly: the roadCenter does the following: 
<img width="343" alt="image" src="https://user-images.githubusercontent.com/48930860/234190448-7420ecb6-44c8-4b4f-9211-3c23bd8cc8fc.png">
I am just wondering because I found cases where "center" would do the above more accurately. But again, might be an OSM data quality issue.

**Comment by namdre** [comment]
the picture you drew describes the behavior of having spreadType=right, whereas roadCenter would have the whole road centered on the red line (so it goes through the center of the middle lane).

**Comment by namdre** [comment]
it becomes complicated by the fact that OSM import completely ignores it when you set default.spreadType=center and basically defaults to using the default of spreadType=right.

**Comment by ambuehll** [comment]
ah, perfect. I never really understood the description then. 
May I suggest adding pictures or changing the text a bit. I always thought "right" interprets the edge geom as the left of the whole edge not the middle of the road - especially because it says "flares out to the right". Now I understand this is meant from the middle right?

**Comment by ambuehll** [comment]
essentially, I just found that sometimes "right" and sometimes "roadCenter" is the correct interpretation of OSM, which seems to be due to inconsistent mapping in OSM...
