### ISSUE TITLE
How to make the car do specific actions during the simulation without `traci`?

### ISSUE THREAD

**Issue by Sirus1110** [eclipse/sumo#13129]
Hello, I wish to load a car in `sumo`. 
The car first accelerated at a certain acceleration on the road for a period of time, then maintained a constant speed for a few seconds, and finally decelerated for a period of time.
Is it possible to implement this function without using the interface of `traci`.
Please advise as to how I can get around this.

**Comment by namdre** [comment]
Yes: by careful declaration of waypoints: https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#stops_and_waypoints

also eventually via #1922
