### ISSUE TITLE
about "getIntervalMeanSpeed"

### ISSUE THREAD

**Issue by Clown1206** [eclipse/sumo#13148]
Add your issue description here.

*If possible, upload an example that shows your problem.*
 Hello,the description of "getIntervalMeanSpeed" in the documentation is:" Returns the average speed of vehicles during the previous interval".What about the definition of "during the previous interval"? I use this function and sometimes I get ‘-1’.
**SUMO-version:**
sumo1.16.0
**operating system:**
win10

**Comment by namdre** [comment]
-1 is used to indicate that no data was collected and the value is not meaningful: https://math.stackexchange.com/questions/909395/what-is-the-arithmetic-mean-of-no-numbers (since speeds in sumo are always positive).

**Comment by Clown1206** [comment]
> -1 is used to indicate that no data was collected and the value is not meaningful: https://math.stackexchange.com/questions/909395/what-is-the-arithmetic-mean-of-no-numbers (since speeds in sumo are always positive).

Thank you, What about the definition of "during the previous interval" in getIntervalMeanSpeed? I couldn't find a description.

**Comment by Clown1206** [comment]
> the previous interval is the last full interval that was collected and written to file. In contrast, getIntervalMeanSpeed is the value from the current interval which covers a time range lower than the 'period' value depending on when the previous interval was completed.

When I use the code:
if(traci.simulation.getTime()%10==0):            
       print(traci.lanearea.getIntervalMeanSpeed('e2Detector_B2C2_0'))
all the values printed are '-1'.
I don't understand how getIntervalMeanSpeed works, and I don't know the value of the time interval for getIntervalMeanSpeed

**Comment by Clown1206** [comment]
sorry, I think I should use traci. lanearea. getLastIntervalMeanSpeed.
The average speed obtained by this function is the same as the output file of the detector and the output file of the edge.

**Comment by namdre** [comment]
the interval is configured in the xml input to your simulation: https://sumo.dlr.de/docs/Simulation/Output/Lanearea_Detectors_%28E2%29.html (attribute **period**)

the -1 suggests that no vehicles are passing this detector. Otherwise it would give you the ["space-mean-speed"](https://www.google.com/search?&q=space-mean%20speed)
