### ISSUE TITLE
geometry.remove when bus lane ends

### ISSUE THREAD

**Issue by ambuehll** [eclipse/sumo#13143]
geometry.remove merges two edges that differ in bus lane use (or vehicle:lanes tags)
The first picture shows how it is tagged in OSM and correctly shown in OSM. The second image show the incorrect merge. 

`geometry.remove false`

<img width="650" alt="image" src="https://user-images.githubusercontent.com/48930860/234345903-1c549122-e45d-4bd6-a702-bc83f31e3fae.png">

`geometry.remove true`

<img width="569" alt="image" src="https://user-images.githubusercontent.com/48930860/234346098-2149848d-5ca6-41e6-8efa-652dd1076ae5.png">

same data as always.

**SUMO-version:**current

**Comment by namdre** [comment]
your configuration sets option `<geometry.remove.min-length value="50"/>` and this explicitly permits such removals.
