### ISSUE TITLE
Open netgenerate-network directly on process end

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#13149]
the new networks should show up without pressing close but the dialog can stay open for Back->Reconfigure (or close)

**Comment by behrisch** [comment]
Only keep the dialog open on errors

**Comment by behrisch** [comment]
May also apply to other tools

**Comment by namdre** [comment]
On windows, this leaves an orphaned window called "netgenerateoutput" open.

**Comment by namdre** [comment]
now problems occur when trying to close the new netedit instance or the dialog that holds the netgenerate output.
