### ISSUE TITLE
[Question] List of algorithms

### ISSUE THREAD

**Issue by meerfrau** [eclipse/sumo#13146]
I've wanted to document all microsim algorithms supported by SUMO for its Wikipedia entry.

https://github.com/eclipse/sumo/tree/0aaf800384c2aae273192e2656ee7e4a7df13bc8/src/microsim/cfmodels gives me:
* Krauß 1998
** changing accel and speed by slope
** Krauß-Wagner
* Cruise Control 
* [**A**daptive **C**ruise **C**ontrol](https://sumo.dlr.de/docs/Car-Following-Models/ACC.html) [[doi]](https://doi.org/10.1080/15472450.2015.1016023)
* [**C**ooperative ACC](https://sumo.dlr.de/docs/Car-Following-Models/CACC.html)
* Intelligent Driver Model (IDM)
** [Extended Intelligent Driver Model](https://sumo.dlr.de/docs/Car-Following-Models/EIDM.html) (EIDM) [[doi]](https://doi.org/10.52825/scp.v1i.95)
* Kerner [[arvix]](https://arxiv.org/pdf/0712.2711.pdf)
* smarter S. Kerner?
* Wiedemann (1974) psycho-physical model
* Widemann99 psycho-physical model

Please correct me if necessary!

**Comment by namdre** [comment]
There is also carFollowModel="Rail" which supports traction curves for different train types (https://sumo.dlr.de/docs/Simulation/Railways.html#modelling_trains).

For Wiedemann, two versions of the Model are available: W99 and Wiedemann (corresponding to the 1974 version).

**Comment by meerfrau** [comment]
@behrisch Sorry for bothering you: Is the taxonomy correct? I don't want to misrepresent it.

**Comment by behrisch** [comment]
Yes it is with the additions of @namdre
