### ISSUE TITLE
traci.load not working properly in 1.17.0

### ISSUE THREAD

**Issue by MAKahs** [eclipse/sumo#13150]
Hi,
I noticed that traci.load doesn't seem to load or clear the simulation state while using the sumo-gui.exe
but works fine using the sumo.exe.

Example:
[LoadFail1.17.zip](https://github.com/eclipse/sumo/files/11331215/LoadFail1.17.zip)

SUMO-version: 1.17.0

operating system: Windows 64-bit

**Comment by namdre** [comment]
reproducible on Linux and with all recent sumo versions down to 1.1.0

**Comment by behrisch** [comment]
It seems that traci.load with GUI broke due to https://github.com/eclipse/sumo/commit/45d341a1f174da9f944fb806b87bd2416587496e because traci.load reuses the onCmdReload code
