### ISSUE TITLE
libsumo use error

### ISSUE THREAD

**Issue by SongKun2023** [eclipse/sumo#13169]
Add your issue description here.
Hello, sir. I download source code of SUMO, and I build it on visual studio 2022 on windows, it's OK. Then I want to use libsumo like following photo. but there is an error that cant not find nteconvertD.exe in bin file. I don't know the reason, could you give me some advice?

![image](https://user-images.githubusercontent.com/97946646/235130583-09075407-1f00-401b-b964-9cd83b139c38.png)

**Comment by namdre** [comment]
running a libsumo simulation does not make use of netconvert so your code screenshot doesn't help to clear up the problem.
There must be some other process that tries to use netconvert.

**Comment by SongKun2023** [comment]
Thank you sir, but I can not find some other process that tries to use netconvert. Some screenshot are as follows:

![80651b4380e0336f10b50885a066235](https://user-images.githubusercontent.com/97946646/235152128-2d3b98b8-9b9a-42d9-b4ae-fda83c180930.png)


![d1f523064739a102f33ed879c534d31](https://user-images.githubusercontent.com/97946646/235152170-e0e5ccd2-d06f-4d93-bff6-40861ebb5d93.png)


![723df85ae4da8c0eda73afef18b59c9](https://user-images.githubusercontent.com/97946646/235152193-48cba4e1-5547-411c-a4ad-81aa9d76d291.png)

**Comment by SongKun2023** [comment]
And I want to know how much faster would I use C++ to control simulation than python?

**Comment by namdre** [comment]
> And I want to know how much faster would I use C++ to control simulation than python?

depending on how much of your own code you use, the difference may be negligible (i.e. if the running time is dominated by the simulation).
