### ISSUE TITLE
 V2V vehicle-to-vehicle messaging

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#13165]
How does SUMO implement V2V vehicle-to-vehicle messaging? For example, I want to send a customized reservation message to other vehicles in the network in SUMO. The content of the reservation message includes the following fields: ID of the reserved vehicle, location of the reserved vehicle, priority of the reserved vehicle, reservation time of the reserved vehicle, and elapsed time. Let other cars pick it up. How do you do that? Thank you very much

**SUMO-version:1.16.0**

**operating system:Windows**

**Comment by namdre** [comment]
https://sumo.dlr.de/docs/FAQ.html#can_sumo_simulate_v2v_v2x_messages
