### ISSUE TITLE
absLoss and relLoss threshold

### ISSUE THREAD

**Issue by radhityavirya** [eclipse/sumo#13164]
how to estimate the numbers in the absLoss and relLoss threshold parameters when using the greedyShared algorithm? does the greater the threshold value, the more joined orders will be?
![Capture](https://user-images.githubusercontent.com/97588265/234730993-bf783fb3-eccd-4d48-8a9d-6fd5646d10c9.PNG)

**Comment by namdre** [comment]
yes
