### ISSUE TITLE
Randomtrips.py with multiple flows and periods

### ISSUE THREAD

**Issue by lainas262** [eclipse/sumo#13173]
Hello,

I am trying to use randomTrips.py with multiple flows and periods. Is this at all possible? As I can see here:
https://github.com/eclipse/sumo/blob/83496a5972528fd2378c4058a6362cd6b91a0d80/tools/randomTrips.py#L117
flows expects a single INT?

Also as I can see here: 
https://github.com/eclipse/sumo/blob/83496a5972528fd2378c4058a6362cd6b91a0d80/tools/randomTrips.py#L80
period expects a single FLOAT?

Forgive me for the simplicity of my question as I am fairly new to this and still trying to grasp the concepts :)

**SUMO-version:** 1.10.0

**operating system:** Windows 10

**Comment by lainas262** [comment]
Basically I have a list of vehicles per hour broken down to 0,5 hour intervals. And based on my network, I would like to generate a route file based on some other specification I have for the network.

**Comment by namdre** [comment]
to use the vehicles-per-hour values, set the option
`-e H:0:0 --insertion-rate x0,x1,x2,... `
where H is the number of hours for which you have data and x0,x1,... are the per-hour values you have for each half-hour (so 2 * H values).

The option --flows generates a fixed number of origin-destination pairs and distributes the specified amount of traffic evenly among those O-D-pairs.  If you don't set --flows, you will get a new random O-D pair for each vehicle.

**Comment by lainas262** [comment]
Hello, thanks for the help!
Will the following flags represent the graph?
-b 0 -e 10800 --insertion-rate 100 300 400 500 600 200
![GraphSample](https://user-images.githubusercontent.com/17641992/235637808-ff67ad04-7f60-4ded-aa6f-17f52a8c228e.png)

**Comment by lainas262** [comment]
Hello @namdre is there any chance you could help with the above? I think I am heading towards the right direction, but I maybe I am missing something :/

Thanks!

**Comment by namdre** [comment]
Yes, the flags you posted should represent the depicted demand graph.  An easy way to debug the generated volumes is to set option **--flows 1**  (though don't use this flag for actual traffic because you probably want more than 1 OD-pair).
