### ISSUE TITLE
Question: Update Pandas to version 2.0.1 for improved speed

### ISSUE THREAD

**Issue by M-Colley** [eclipse/sumo#13175]
Hey there, I was wondering whether the requirements could explicitly state that pandas>=2.0.1 should be used? pandas in version 2.0.0 did significantly increase speed, which could be very helpful for SUMO.

Kind regards

**Comment by behrisch** [comment]
Personally I would like to keep the requirements at the minimum of what is really being required. But we can add this to the docs. Do you have numbers concerning the speed improvements maybe even with one of the SUMO scripts?

**Comment by M-Colley** [comment]
I agree that that is probably a more viable way for more users. 

We tried a larger scenario with a simulated hour (3600 timesteps) and had an improvement of about 7%. 


With pandas version 1.5: 14.25 min
With pandas version 2.0.1: 13.28 min

.
