### ISSUE TITLE
How to define `route id` in `route_prob_reroute`

### ISSUE THREAD

**Issue by Sirus1110** [eclipse/sumo#13184]
Sorry to bother you again!
I want to simulate the scene of road congestion and vehicles choosing other routes in sumo.
So I refered to the following link
[assigning_a_new_route](https://sumo.dlr.de/docs/Simulation/Rerouter.html#assigning_a_new_route)
When I defined routes in `xx.rou.xml` file
```
  <route id="crushing_2_normal" edges="-E12 E13 E8 E17 E23 E5 -E11 -E1 -E22" color="cyan"/>
  <route id="crushing_2_congestion" edges="-E12 E28 E31 E8 E17 E23 E5 -E11 -E1 -E22" color="cyan"/>
```
then defined rerouter in the xx.add.xml file
```
  <rerouter id="rr_0" edges="E23" pos="176.74,153.58" off="0">
      <interval begin="0.00" end="900.00">
          <routeProbReroute id="crushing_2_normal" probability="0"/>
          <routeProbReroute id="<crushing_2_congestion>" probability="1"/>
      </interval>
  </rerouter>
```
However, sumo returns an error:
`Error: MSTriggeredRerouter rr_0: Route 'crushing_2_normal' does not exist.`
My questions are as follows：
1. Why does this Error happend?
2. How to correctly define `routeProbReroute id="crushing_2_normal"` in the sumo configuration file?

 It’s very kind of you to help me!

**Comment by m-kro** [comment]
Please consider the loading order of input files (explained in the [docs](https://sumo.dlr.de/docs/sumo.html#loading_order_of_input_files)). Additional files are loaded before route files and at that point, the routes are still unknown. It is possible to add route definitions to additional files, too. You can simply cut out the route definitions shown in your post and paste them in the additional file just above the rerouter definition.

**Comment by Sirus1110** [comment]
> Please consider the loading order of input files (explained in the [docs](https://sumo.dlr.de/docs/sumo.html#loading_order_of_input_files)). Additional files are loaded before route files and at that point, the routes are still unknown. It is possible to add route definitions to additional files, too. You can simply cut out the route definitions shown in your post and paste them in the additional file just above the rerouter definition.

Thanks!
I have tried the first solution. Actually the inplut oder of my sumo configuration files is as follow:
```
    <input>
        <net-file value="../multi-leg%20intersection/daye.net.xml"/>
        <route-files value="../multi-leg%20intersection/daye_flow.rou.xml"/>
        <additional-files value="../multi-leg%20intersection/daye.add.xml"/>
    </input>
```
Then I tried to paste the route definitions to the additional file, like
```
    <!-- Routes -->
    <route id="crushing_2_normal" edges="-E12 E13 E8 E17 E23 E5 -E11 -E1 -E22" color="cyan"/>
    <route id="crushing_2_congestion" edges="-E12 E28 E31 E8 E17 E23 E5 -E11 -E1 -E22" color="cyan"/>
    <!-- Other additionals -->
    <rerouter id="rr_0" edges="E23" pos="176.74,153.58" off="0">
        <interval begin="0.00" end="900.00">
            <routeProbReroute id="crushing_2_normal" probability="0"/>
            <routeProbReroute id="<crushing_2_congestion>" probability="1"/>
        </interval>
    </rerouter>
```
it doesn't work. And SUMO returns 
```
Error: '<' character cannot be used in attribute value 'id'; use &lt; instead
 In file ''
 At line/column 21/77.
```
The content of the line 21 is `        </interval>`
I can't understand the cause of this error, 
Could you spend a little bit more time to help me solve this problem?
Or is there any file or link for reference?
Thanks for your help!

**Comment by Sirus1110** [comment]
> Please consider the loading order of input files (explained in the [docs](https://sumo.dlr.de/docs/sumo.html#loading_order_of_input_files)). Additional files are loaded before route files and at that point, the routes are still unknown. It is possible to add route definitions to additional files, too. You can simply cut out the route definitions shown in your post and paste them in the additional file just above the rerouter definition.

Thanks!
I have tried the first solution. Actually the inplut oder of my sumo configuration files is as follow:
```
    <input>
        <net-file value="../multi-leg%20intersection/daye.net.xml"/>
        <route-files value="../multi-leg%20intersection/daye_flow.rou.xml"/>
        <additional-files value="../multi-leg%20intersection/daye.add.xml"/>
    </input>
```
Then I tried to paste the route definitions to the additional file, like
```
    <!-- Routes -->
    <route id="crushing_2_normal" edges="-E12 E13 E8 E17 E23 E5 -E11 -E1 -E22" color="cyan"/>
    <route id="crushing_2_congestion" edges="-E12 E28 E31 E8 E17 E23 E5 -E11 -E1 -E22" color="cyan"/>
    <!-- Other additionals -->
    <rerouter id="rr_0" edges="E23" pos="176.74,153.58" off="0">
        <interval begin="0.00" end="900.00">
            <routeProbReroute id="crushing_2_normal" probability="0"/>
            <routeProbReroute id="crushing_2_congestion" probability="1"/>
        </interval>
    </rerouter>
```
it doesn't work. And SUMO returns 
```
Error: attribute 'id' is not declared for element 'route'
 In file 'C:\Users\XXX\XXX\XXX\multi-leg intersection\../multi-leg intersection/daye_flow.rou.xml'
 At line/column 14/85.
```
The content of the line 21 is `<route id="crushing_2_normal" edges="-E12 E13 E8 E17 E23 E5 -E11 -E1 -E22" color="cyan"/>`

Could you spend a little bit more time to help me solve this problem?
Or is there any file or link for reference?
Thanks for your help!

**Comment by Sirus1110** [comment]
Thanks.
I didn’t describe my operation clearly, sorry.
Actually I have already removed the route elements in the route file. And the Error `Error: attribute 'id' is not declared for element 'route'  ` still occurred.

**Comment by Sirus1110** [comment]
> In any case you can't have a second route definition with the same ID. Change the ID to a new unique string value or remove the route elements in the route file you have copied to the additional file.
> 
> Finally, the parameter order in the sumocfg file doesn't influence the actual loading order of the referenced files.
Thanks!
Sorry, I didn’t describe the problem clearly.
Actually, I have remove the route elements in the route file, but the Error `Error: attribute 'id' is not declared for element 'route'` still occurred.

**Comment by m-kro** [comment]
And how does the route file now look like (close to the indicated error)? Without that it is impossible to guess the reason. Do you have other route elements without defined ID attribute?

**Comment by Sirus1110** [comment]
Thanks!
here is the route file
```
<?xml version="1.0" encoding="UTF-8"?>

<!-- generated on 2023-05-04 08:41:33 by Eclipse SUMO netedit Version 1.16.0
-->

<routes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/routes_file.xsd">
    <vType id="type1" accel="2.6" decel="4.5" sigma="0.5" length="5" maxSpeed="10">
        <param key="has.rerouting.device" value="true"/>
    </vType>
    <vType id="type2" accel="2.6" decel="4.5" sigma="0.5" length="5" maxSpeed="10">
    </vType>
    <vehicle id="flow2.0" type="type2" depart="0.00" color="red">
        <route id="-E12 E13 E8 E17 E23 E5 -E11 -E1 -E22" edges="-E12 E13 E8 E17 E23 E5 -E11 -E1 -E22"/>
        <stop parkingArea="pa_0" duration="60.00"/>
    </vehicle>
    <vehicle id="flow3.0" type="type1" depart="30.00" color="blue">
        <route edges="-E12 E13 E8 E17 E23 E5 -E11 -E1 -E22"/>
        <stop parkingArea="pa_0" duration="60.00"/>
    </vehicle>
    <vehicle id="flow4.0" type="type2" depart="50.00" color="magenta">
        <route edges="-E12 E13 E8 E17 E23 E5 -E11 -E1 -E22"/>
        <stop parkingArea="pa_0" duration="60.00"/>
    </vehicle>
    <vehicle id="flow5.0" type="type1" depart="70.00" color="green">
        <route id="-E12 E28 E31 E8 E17 E23 E5 -E11 -E1 -E22" edges="-E12 E28 E31 E8 E17 E23 E5 -E11 -E1 -E22"/>
        <stop parkingArea="pa_0" duration="60.00"/>
    </vehicle>
</routes>
```

and the addtional file is as follows:
```
<?xml version="1.0" encoding="UTF-8"?>

<!-- generated on 2023-05-04 09:05:01 by Eclipse SUMO netedit Version 1.16.0
-->

<additional xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/additional_file.xsd">
    <!-- Routes -->
    <route id="crushing_2_normal" edges="-E12 E13 E8 E17 E23 E5 -E11 -E1 -E22" color="cyan"/>
    <route id="crushing_2_congestion" edges="-E12 E28 E31 E8 E17 E23 E5 -E11 -E1 -E22" color="cyan"/>
    <!-- Other additionals -->
    <rerouter id="rr_0" edges="E23" pos="176.74,153.58" off="0">
        <interval begin="0.00" end="900.00">
            <routeProbReroute id="crushing_2_normal" probability="0"/>
            <routeProbReroute id="crushing_2_congestion" probability="1"/>
        </interval>
    </rerouter>
</additional>
```

**Comment by Sirus1110** [comment]
> And how does the route file now look like (close to the indicated error)? Without that it is impossible to guess the reason. Do you have other route elements without defined ID attribute?

Yes, Is it possible reason for the problem?

**Comment by Sirus1110** [comment]
Oh, it works after I removed route id in route file!
I'm so careless, thank you for your help
