### ISSUE TITLE
parkingArea angle moves actual parking spot

### ISSUE THREAD

**Issue by 880KB** [eclipse/sumo#13185]
The actual parking spot of a parkingArea is computed from its end when the parkingArea's angle is zero and computed from its center otherwise. Is this behavior intentional?

From left to right: 
- parkingArea with capacity 0
- parkingArea with capacity 1 and angle 0
- parkingArea with capacity 1 and angle 5

![parking_area](https://user-images.githubusercontent.com/43952244/236176334-49bcb26c-6276-49fb-a1dc-9752d95adfd8.png)

Netedit-version: 1.14.1 and 1.17.0

Operating system: Win 10

Simple example:
[SUMO parking.zip](https://github.com/eclipse/sumo/files/11396396/SUMO.parking.zip)

**Comment by namdre** [comment]
Yes. The behavior is intended. (the obvious use case is a 90 degree angle relative to the road) and everything that is not 0 uses that code as well.
