### ISSUE TITLE
traci.vehicle.getPosition

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#13186]
This function is to get the position of the vehicle in the last time step, how do I get the current position in the current time step, that is, how do I get the position of the vehicle in real time?
![5e9488d80fb416b0dad7bdab5307a2c](https://user-images.githubusercontent.com/54823725/236219461-3d6ea23b-dd58-486d-99dc-0353e5251ac2.png)
**SUMO-version:1.17.0**

**operating system:Windows**

**Comment by namdre** [comment]
you can call
```
traci.executeMove()
traci.vehicle.getPosition()
traci.simulationStep()
```
to get the position in the current step.
