### ISSUE TITLE
How do I create a cluster from two junctions?

### ISSUE THREAD

**Issue by fguio44** [eclipse/sumo#13188]
How do I create a cluster from two junctions?

**SUMO-version: latest**

**operating system: Windows**

**Comment by namdre** [comment]
- manually in by selecting the junctions in netedit and pressing F7
- automatically with netconvert: https://sumo.dlr.de/docs/Networks/PlainXML.html#joining_nodes

**Comment by fguio44** [comment]
Thank you!
