### ISSUE TITLE
How generate a report by edges and junctions

### ISSUE THREAD

**Issue by fguio44** [eclipse/sumo#13189]
Hoy can I to generate a report by edges and junctions in intervals of 900 seconds?

**SUMO-version: latest**

**operating system: Windows**

**Comment by namdre** [comment]
https://sumo.dlr.de/docs/Simulation/Output/Lane-_or_Edge-based_Traffic_Measures.html  (`period="900"`)
support for junctions is limited:
https://sumo.dlr.de/docs/Simulation/Output/index.html#values_for_junctions

**Comment by fguio44** [comment]
Thank you
