### ISSUE TITLE
crash after rerouting and losing a stop

### ISSUE THREAD

**Issue by Sirus1110** [eclipse/sumo#13190]
Hi !
I have created a bidi road, like
```
    <edge id="-E22" from="J2" to="J33" priority="-1" spreadType="center" bidi="E22">
        <lane id="-E22_0" index="0" speed="13.89" length="144.30" width="10.00" shape="113.83,107.61 -30.26,99.79"/>
    </edge>
    <edge id="E22" from="J33" to="J2" priority="-1" spreadType="center" bidi="-E22">
        <lane id="E22_0" index="0" disallow="pedestrian" speed="13.89" length="144.30" width="10.00" shape="-30.26,99.79 113.83,107.61"/>
    </edge>
```
Then I created a loop route, the vehicles depart from E22 and leave on -E22.
When multi-vehicles meet on E22, SUMO crashed without  raising any Error.
![sumo crash](https://user-images.githubusercontent.com/55885023/236366133-ddc9b859-3f4d-421f-8213-dbeeed1a376b.png)
However, it seems the crash would not happen when there are only 2 vehicles meet on bidi road. Like,
![image](https://user-images.githubusercontent.com/55885023/236366464-275dd26b-99d0-4634-ba96-4f1a63ddafa8.png)
The sumo configuration file is as follows:
```
<?xml version="1.0" encoding="UTF-8"?>

<!-- generated on 2023-05-04 09:05:01 by Eclipse SUMO sumo Version 1.16.0
-->

<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/sumoConfiguration.xsd">

    <input>
        <net-file value="../multi-leg%20intersection/daye.net.xml"/>
        <route-files value="../multi-leg%20intersection/daye_flow.rou.xml"/>
        <additional-files value="../multi-leg%20intersection/daye.add.xml"/>
    </input>
    <processing>
        <lateral-resolution value="0.3"/>
        <collision.action value="warn"/>
        <default.speeddev value="0"/>
        <pedestrian.model value="striping"/>
    </processing>

</configuration>
```
How can I solve this problem? Thanks.

**Comment by Sirus1110** [comment]
Probably not the cause of the bidi. In the following scenario, sumo also crashes without throwing an error.
![image](https://user-images.githubusercontent.com/55885023/236367888-01cf23d6-f2b3-437e-8d4c-b1de1db5b7b8.png)

**Comment by Sirus1110** [comment]
Related Information

CPU	11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz   2.30 GHz
RAM	32.0 GB (31.7 GB 可用)
Windows Version:  Windows 10 professional 21H2

Eclipse SUMO sumo Version 1.16.0 
Build features: Windows-10.0.17763 AMD64 MSVC 19.29.30133.0 Release FMI Proj GUI Intl SWIG

**Comment by Sirus1110** [comment]
![image](https://user-images.githubusercontent.com/55885023/236371623-082a9e89-c176-48cc-aa1b-ff19ba86d007.png)
In fact, it is because of some errors when drawing the intersection in Netedit, this error will cause sumo to crash when the vehicle passes through the intersection.

**Comment by namdre** [comment]
Please provide the input files to make sumo crash because this needs to be fixed.

**Comment by Sirus1110** [comment]
Sorry, the bug has been fixed before I closed this issue.
I just tried to reproduce this bug, but it didn't work.
I'll try to reproduce the bug at a later time (maybe this Sunday).
And my guess is that when I use the "set custom junction shape" of netedit, there are some unreasonable operations.

My guess is that when I use the "set custom junction shape" of netedit, there are some unreasonable operations. Maybe J24 is too close to J2.
![image](https://user-images.githubusercontent.com/55885023/236392197-1b0c92dd-ae36-4597-a9f0-c6af34f5abcd.png)

[multi-leg intersection.zip](https://github.com/eclipse/sumo/files/11403823/multi-leg.intersection.zip)

**Comment by Sirus1110** [comment]
Hello, namdre !
To solve #13192 ,I increased the width of roads E22 and -E22, and changed the lateral-resolution value to 0.1.
The car will still be stuck in the road, but there will be many warning messages
```
Warning: Vehicle 'flowCrushing14'; frontal collision with vehicle 'flowCrushing11', lane='E3_0', gap=-9.85', latGap=-0.20, time=51.00 stage=move.
Warning: Vehicle 'flowCrushing11'; frontal collision with vehicle 'flowCrushing14', lane='-E3_0', gap=-9.85', latGap=-0.20, time=51.00 stage=move.
Warning: Vehicle 'flowCrushing12'; frontal collision with vehicle 'flowCrushing14', lane='E7_0', gap=-7.83', latGap=-1.80, time=55.00 stage=move.
Warning: Vehicle 'flowCrushing14'; frontal collision with vehicle 'flowCrushing12', lane='-E7_0', gap=-7.83', latGap=-1.80, time=55.00 stage=move.
```
Then I referd to #9402 and increased the length of all vehicles, the bug occurs again!

**Comment by namdre** [comment]
when you talking about SUMO crashing, are you referring to the collision warnings are do you mean that the application itself aborts and stops working?

**Comment by Sirus1110** [comment]
> when you talking about SUMO crashing, are you referring to the collision warnings are do you mean that the application itself aborts and stops working?

Sorry, I mean that application itself aborts and stops working.
And here are the input files.
[multi-leg intersection.zip](https://github.com/eclipse/sumo/files/11404419/multi-leg.intersection.zip)

**Comment by Sirus1110** [comment]
> > when you talking about SUMO crashing, are you referring to the collision warnings are do you mean that the application itself aborts and stops working?
> 
> Sorry, I mean that application itself aborts and stops working. And here are the input files. [multi-leg intersection.zip](https://github.com/eclipse/sumo/files/11404419/multi-leg.intersection.zip)

the confiuration file is `day.sumocfg`

**Comment by Sirus1110** [comment]
> "set custom junction shape" of netedit

It is worth mentioning that I didn't use the "set custom junction shape" of netedit this time, so I am not sure what is causing the bug.

**Comment by namdre** [comment]
custom junction shapes should rarely be responsible for such problems

**Comment by namdre** [comment]
note, that your vehicles "lose" their stops on rerouting if the new route doesn't pass the original parkingArea. You could avoid this by defining stops as child elements of the routes which are assigned by the rerouters.

**Comment by Sirus1110** [comment]
> note, that your vehicles "lose" their stops on rerouting if the new route doesn't pass the original parkingArea. You could avoid this by defining stops as child elements of the routes which are assigned by the rerouters.

I decided to assign parking areas with traci instead of setting parking areas in the route. and the bug didn't happen and this bug didn't happen again.
Thanks again for your kindness help!
