### ISSUE TITLE
Unable to project coordinates for edge when using netconvert

### ISSUE THREAD

**Issue by Tamson17** [eclipse/sumo#13191]
Hi, the warning is posted when i tried to convert a shapefile into sumo net structure.

![Snipaste_2023-05-05_11-18-40](https://user-images.githubusercontent.com/48231533/236371002-ec403406-c19d-4a30-86d9-48bd0de4084e.png)

In my_file, where the .dbf, .shp and .shx files are, i typed cmd in the header followed by netconvert --shapefile-prefix my_file. I have found out that netconvert switched x-axis and y-axis of polylines in my_file.

Any advice what else could be done? Or any reasons for this warning?
Deeply appreciate any suggestions/recommendations.

**Comment by namdre** [comment]
set option **--shapefile.traditional-axis-mapping**

**Comment by Tamson17** [comment]
Thank you so much Dr. Erdmann for your guidance.
I tried the option you shared and it worked!
Thanks again.
