### ISSUE TITLE
Congestion occurs when multiple vehicles meet on a bidi road

### ISSUE THREAD

**Issue by Sirus1110** [eclipse/sumo#13192]
Hi !
I have created a “bidi” road, like
```
    <edge id="-E22" from="J2" to="J33" priority="-1" spreadType="center" bidi="E22">
        <lane id="-E22_0" index="0" speed="13.89" length="144.30" width="10.00" shape="113.83,107.61 -30.26,99.79"/>
    </edge>
    <edge id="E22" from="J33" to="J2" priority="-1" spreadType="center" bidi="-E22">
        <lane id="E22_0" index="0" disallow="pedestrian" speed="13.89" length="144.30" width="10.00" shape="-30.26,99.79 113.83,107.61"/>
    </edge>
```
Then I created a loop route, the vehicles depart from E22 and leave on -E22.

When multi-vehicles meet on E22, congestion occurs.
![image](https://user-images.githubusercontent.com/55885023/236371405-f588bb50-4eb1-48e2-8fea-2ad0c186b451.png)

The sumo configuration file is as follows:
```
<?xml version="1.0" encoding="UTF-8"?>

<!-- generated on 2023-05-04 09:05:01 by Eclipse SUMO sumo Version 1.16.0
-->

<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/sumoConfiguration.xsd">

    <input>
        <net-file value="../multi-leg%20intersection/daye.net.xml"/>
        <route-files value="../multi-leg%20intersection/daye_flow.rou.xml"/>
        <additional-files value="../multi-leg%20intersection/daye.add.xml"/>
    </input>
    <processing>
        <lateral-resolution value="0.3"/>
        <collision.action value="warn"/>
        <default.speeddev value="0"/>
        <pedestrian.model value="striping"/>
    </processing>

</configuration>
```
How can I solve this problem? Thanks.

**Comment by namdre** [comment]
The bidi feature is still experimental and conflicts at intersections aren't fully handled yet, hence the collisions.

To avoid congestion (and likely the collisions as well), you could configure `latAlignment="right"` in the vType.
However, if the roads are routinely used in both directions, you may consider defining two normal directional roads instead of a wide bidi road.

**Comment by Sirus1110** [comment]
> The bidi feature is still experimental and conflicts at intersections aren't fully handled yet, hence the collisions.
> 
> To avoid congestion (and likely the collisions as well), you could configure `latAlignment="right"` in the vType. However, if the roads are routinely used in both directions, you may consider defining two normal directional roads instead of a wide bidi road.


-------------------
I'm trying to simulate a mountainous intersection where all roads are unstructured (no signs and markings).
So I thought the bidi road might be suitable for my needs.
I have solved this problem by configuring latAlignment="right" in the vType.

Thank you very much for your kind help.
