### ISSUE TITLE
question for edge type defining

### ISSUE THREAD

**Issue by SongKun2023** [eclipse/sumo#13194]
Add your issue description here.
Hello sir, I find that the setting of speed in edge type is useless.

![88ba50cd408759bf77fccf7882b4257](https://user-images.githubusercontent.com/97946646/236632432-97aead04-faea-4848-b75b-bec7cd5464a5.png)

**Comment by SongKun2023** [comment]
I define the edge type as screenshot 1,the max speed of this type of edge is 28 m/s and I use this edge type as screenshot 2, but the car drive on the edge at the speed of 33.3 m/s actually as screenshot 3. I don't know the reason.

![101347a646a2baf87119244176113dd](https://user-images.githubusercontent.com/97946646/236632877-1737c905-e777-4a9c-9304-a400c798df4c.png)

![77d7f8eedd0ab1fad7be118d229998d](https://user-images.githubusercontent.com/97946646/236632888-5805937f-9b84-4ce4-8baa-78adac5e5e44.png)

![02db817ea1a56e32839484d210f94f7](https://user-images.githubusercontent.com/97946646/236632895-266766f1-69b4-473f-99b8-3f9df49d15cd.png)

**Comment by namdre** [comment]
the edge types are only applied when building the network with netconvert and no individual edge speed is given. 
Within a sumo net, all edges speeds are explicitly defined so the edge type speed mainly serves as a record of the older input (and can be used in netedit for setting the default of new edges).

Note, that you can use netedit to select edges by type and then use inspect mode to change the speed for all selected edges at once.

**Comment by SongKun2023** [comment]
OK, thanks for your reply.
