### ISSUE TITLE
Can the signal lights of sumo only control one type of vehicle

### ISSUE THREAD

**Issue by Sirus1110** [eclipse/sumo#13202]
Hi, sorry to bother you again.
I have a somewhat weird question: can the signal lights of sumo only control one specified type of vehicle？
For example，there 2 types of vechicle: passenger cars and trucks.When the signal turns green, passenger car are still blocked from passing even though it lines up at the front of the intersection approach, rather than trucks. Passage is only allowed when the truck is at the front.

Thanks for your help!

**Comment by Sirus1110** [comment]
Thanks for your help! The second option seems to work, and I will try it soon.
I would like to suggest some possible solutions:
#https://sumo.dlr.de/pydoc/traci._lane.html#LaneDomain-setDisallowed
Would it be possible to achieve the same effect if setting the current lane to be impassable for the type of the first car?
Or use traci to set the front lane 2 lane connection as impassable？

**Comment by namdre** [comment]
Yes. you disallow the internal lane to block the car but it wouldn't affect the signal state.
