### ISSUE TITLE
Identify if a lane change sent from TraCI was successful 

### ISSUE THREAD

**Issue by mpfist-no** [eclipse/sumo#13206]
Hello,

is there a reliable way to determine if a lane change command sent from TraCI was successfully completed?

For a example, I trigger a lane change to the right lane via `traci.vehicle.changeLaneRelative(VEH_ID, -1, 0)` while a vehicle is blocking this lane. The lane change state after traci (second return value of `traci.vehicle.getLaneChangeStatePretty(VEH_ID, -1)` changes as follows:

1. [right, TraCI, urgent, sublane]
2. [right, TraCI, sublane]
3. []

The lane change is not executed (as expected). Can this be derived only from the lane change state?

I already thought about workarounds such as monitoring the vehicle's lane ID/index but this does not seem very robust (e.g. when passing a junction during the lane change).

Could it be an issue that the lane change duration is set to 0? 

Thanks a lot for your help.

**Comment by namdre** [comment]
After success you will either have an empty state (if you set a low duration) or "TraCI" and "stay" if you set a higher duration value for the changeLane or changeLaneRelative command.
