### ISSUE TITLE
CarFollowingMode without any further safety checks.

### ISSUE THREAD

**Issue by Oritchimaru** [eclipse/sumo#13210]
Hello!

What is the procedure I should follow in order to make a simulation where in a certain network and traffic, vehicles follow ONLY the Krauss car following model while having no restrictions about right-of-way rule or traffic lights or vehicles in other lanes that approach a junction?

Krauss regards only the lead vehicle from what I understand and I want to evaluate a model just on that, no further interventions from sumo or traci in any form. I define on vtype the decel, accel, max_speed, min_speed and length and these are the only information along with the Krauss decisions on speed that the vehicles should have.

Do you think this is possible?
Should I change something in the sumo.cfg or add something in the vtype attributes?

Thanks!

**Comment by namdre** [comment]
set vType attribute jmDriveAfterRedTime=1000  jmIgnoreFoeProb=1  jmIgnoreJunctionFoeProb=1

**Comment by Oritchimaru** [comment]
Thanks a lot, I will try this later!
