### ISSUE TITLE
How to initialize a simulation, in which there are vehicle on the road?

### ISSUE THREAD

**Issue by Jinbo0201** [eclipse/sumo#13219]
I want to predict traffic flow on highways, based on the detector data over a period of time.
So, firstly, I should initialize a simulation, in which there are vehicles on the road.
The states of running vehicles are based on the detector data.
Secondly, set the future input to simulate and obtain the predicted data.

**Comment by behrisch** [comment]
The first step can be achieved by starting the simulation in the night when the net is nearly empty and saving the state at the time you are interested to start. The generation of a [base demand from counts](https://sumo.dlr.de/docs/Demand/Routes_from_Observation_Points.html) can be done with [dfrouter,](url) flowrouter or routeSampler, where the latter is probably the most mature tool. The basic tool to achieve an adaptation to the current counts are [calibrators](https://sumo.dlr.de/docs/Simulation/Calibrator.html). We are planning to release a tool which does this large scale with database support soon but it may be not so well documented yet.
