### ISSUE TITLE
Loading Data Elements

### ISSUE THREAD

**Issue by mehmetnedimyavuz** [eclipse/sumo#13224]
I am using SUMO version 1.17.0. I am working on edge relation data mode to prepare appropriate turn-count data format for the  input of routesampler tool. I created the dataset, time intervals and entered real count values. I am saving data elements as (carcounts.dat.xml). and closing netedit. My intention is to continue where I left off, load to "carcounts.dat.xml" from (File>Data Elements>Load Data Elements), however I can not load "carcounts.dat.xml" and not appear dataset and time intervals data. Can you help this issue? Thank you, regards.

**Comment by palvarezlopez** [comment]
@mehmetnedimyavuz Thanks for reporting it. I check it, and in my SUMO 1.17 version works as espected. Can you send an screenshot of the edgeData / EdgeRelData frame before saving?

**Comment by mehmetnedimyavuz** [comment]
Data file is created as expected.
![image](https://github.com/eclipse/sumo/assets/79362739/c18623c5-d6de-4b90-9ee3-54d23935e488) 
![image](https://github.com/eclipse/sumo/assets/79362739/e34115d3-a9f1-4fa5-ae27-c2ef4bd0af5d)

When I try to load dat.xml file from data elements and choosing carcounts.dat.xml from folder. There is no appear loaded data.

![image](https://github.com/eclipse/sumo/assets/79362739/e7b441ba-3379-4b3f-9714-3f0531897734)
![image](https://github.com/eclipse/sumo/assets/79362739/1286e96c-9ac5-42d9-852d-b46ac27d16af)

**Comment by palvarezlopez** [comment]
@mehmetnedimyavuz Thanks. Indeed, I can reproduce the bug. The problem is loading a single data file. If loading is through a neteditConfig, it works. I'm going to repair it.

**Comment by namdre** [comment]
regression in 1.17.0
