### ISSUE TITLE
traci.simulationStep() cost 100ms every 1s

### ISSUE THREAD

**Issue by yunmo555** [eclipse/sumo#13235]
Hello，When I tick with sumo I find that every 1s traci.simulationStep costs 100ms，It's going to affect my perception that there's a pause in the traffic. Is this a known bug or a special setting.What can be done about this pause

**SUMO-version:**
sumo Version 1.14.1
**operating system:**
ubuntu 20.04

**Comment by m-kro** [comment]
See [https://sumo.dlr.de/docs/TraCI.html#performance](https://sumo.dlr.de/docs/TraCI.html#performance)

**Comment by yunmo555** [comment]
> See https://sumo.dlr.de/docs/TraCI.html#performance


        start = round(time.time()*1000)
        traci.simulationStep()
        start2 = round(time.time()*1000)
        self.traffic_light_manager.tick()

        # Update data structures for the current frame.
        # set(traci.simulation.getIDList())
        self.spawned_actors = set(traci.vehicle.getIDList())

        self.destroyed_actors = set(traci.simulation.getArrivedIDList())

        logger.info(f"==================== cost:{start2-start} {traci.simulation.getMinExpectedNumber()}")

TraCI function calls does it affect traci.simulationStep() time? I try change step-length, But traci.simulationStep() cost 100ms every 1s. This is the printout:
==================== cost:100 1
==================== cost:0 1
... * 99
==================== cost:100 1

**Comment by yunmo555** [comment]
> > See https://sumo.dlr.de/docs/TraCI.html#performance
> 
> ```
>     start = round(time.time()*1000)
>     traci.simulationStep()
>     start2 = round(time.time()*1000)
>     self.traffic_light_manager.tick()
> 
>     # Update data structures for the current frame.
>     # set(traci.simulation.getIDList())
>     self.spawned_actors = set(traci.vehicle.getIDList())
> 
>     self.destroyed_actors = set(traci.simulation.getArrivedIDList())
> 
>     logger.info(f"==================== cost:{start2-start} {traci.simulation.getMinExpectedNumber()}")
> ```
> 
> TraCI function calls does it affect traci.simulationStep() time? I try change step-length, But traci.simulationStep() cost 100ms every 1s. This is the printout: ==================== cost:100 1 ==================== cost:0 1 ... * 99 ==================== cost:100 1

current step-length is 0.01. And I call the above code every 0.01 seconds in the timing function.

**Comment by m-kro** [comment]
The simulated time is not synchronised with the system time. It is executed as fast as possible. The simulation time step is needed as an input for sub-models like the car-following model, see [docs](https://sumo.dlr.de/docs/Simulation/Basic_Definition.html#defining_the_time_step_length).
