### ISSUE TITLE
'LaneAreaDomain' object has no attribute 'getIntervalMeanSpeed'

### ISSUE THREAD

**Issue by Jinbo0201** [eclipse/sumo#13233]
'LaneAreaDomain' object has no attribute 'getIntervalMeanSpeed'

**Comment by m-kro** [comment]
It is working in our tests, see this [example scenario](https://sumo.dlr.de/extractTest.php?path=complex/traci/lanearea/lanearea). Please compare with this working test and report here if you still cannot solve the error.

**Comment by namdre** [comment]
most likely your sumo version is too old. You need at least 1.16.0

**Comment by Jinbo0201** [comment]
@namdre The problem is solved when using sumo 1.17.0,
Thanks.
