### ISSUE TITLE
insufficient rail signals imported from OSM

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#13231]
contrast the berlin light rail network in sumo and OSM (overpass):

![berliner_ring_Hauptsignale](https://github.com/eclipse/sumo/assets/6240630/dc9b460b-0d81-4fd9-b484-f6a959d8ecb1)

![grafik](https://github.com/eclipse/sumo/assets/6240630/972d35b3-46ff-4ee0-8457-8da72062c793)

**Comment by namdre** [comment]
a fresh osm import shows a lot more signals than the first screenshot (i.e. at Plänterwald). @behrisch could it be that the OSM file on which the berlin scenario is based is outdated?

**Comment by behrisch** [comment]
here is the network with the most recent geofabrik data. It has now 512  signals (before 226).
[berlin-sbahn.net.xml.gz](https://github.com/eclipse/sumo/files/11438795/berlin-sbahn.net.xml.gz)

**Comment by namdre** [comment]
there is still a big signal gap  between Sonnenalle and Tempelhof but I'm now certain that it is really a lack in OSM data.
