### ISSUE TITLE
Question on the difference between the function provided by simpla and CACC (ACC, IDM etc.) following models?

### ISSUE THREAD

**Issue by thinker310** [eclipse/sumo#13243]
Excuse me, I wonder platooning vehicle if comply the car following model setting in simulation configuration and what the difference between the function provided by simpla and CACC (ACC, IDM etc.) following models is. As if both of them can adjust the gap between vehicles and control vehicle travelling. The CACC model seems to be able to arrange vehicles as well. Thank you in advance!

**Comment by m-kro** [comment]
Simpla builds up on sets of car-following model parameters calling TraCI functions from Python, whereas CACC is a car-following model of its own integrated into sumo. Simpla may be useful when you are more interested in platooning which is 

- fast to build
- easy to integrate into existing scenarios
- extended to a large number of vehicles / the network.

On the downside, the resulting trajectories might look less smooth than CACC as it depends much on how you define the vehicle types simpla can switch between and when it actually performs the switch. If you want to look closely at the platoon dynamics, I'd advise to try CACC.
