### ISSUE TITLE
[JuPedSim] Use internal paths of walking areas instead of straight lines

### ISSUE THREAD

**Issue by bcoueraud87** [eclipse/sumo#13244]
Currently the code that creates the geometry for JuPedSim uses straight lines to generate walking areas. We should reuse the internal lanes of the SUMO walking areas so that the difference between the JuPedSim network of pedestrian lanes on one side, and the SUMO one on the other side, is minimized.

**Comment by bcoueraud87** [comment]
@behrisch Please assign me.

**Comment by namdre** [comment]
You can now use the function
`MSPModel_Striping::insertWalkArePaths(const MSEdge* edge, WalkingAreaPaths& into)` to obtain all paths for a given walkingarea (without having to load a striping model).

**Comment by bcoueraud87** [comment]
Many things were tried. The results are not as good as expected but now some curvy pedestrian lanes are taken into account. Some other are not because they lead to artefacts that can not easily be solved by using computational geometry. The original idea of using internal paths of the walking areas proved to not improve the curves and so were not used in the end.
