### ISSUE TITLE
how to change traffic signal duration according to the congestion .

### ISSUE THREAD

**Issue by shivanipathania002** [eclipse/sumo#13253]
Add your issue description here.

*If possible, upload an example that shows your problem.*

**SUMO-1.8.0:**

**Ubuntu 20.04:**
I want to change traffic signal durations according to the congestion data. But, I'm getting stuck at this point my durations cannot be changed according to the calculated value.

**Comment by m-kro** [comment]
Our [Traci TLS tutorial](https://sumo.dlr.de/docs/Tutorials/TraCI4Traffic_Lights.html) shows how interaction with traffic lights can be done in general. For extending/shortening phases use `traci.trafficlight.setPhaseDuration` ([ref](https://sumo.dlr.de/pydoc/traci._trafficlight.html#TrafficLightDomain-setPhaseDuration)).
