### ISSUE TITLE
How to use Netedit to set up a safety island for pedestrians crossing the street and achieve a second crossing for pedestrians?

### ISSUE THREAD

**Issue by zhangm269** [eclipse/sumo#13256]
How to use Netedit to set up a safety island for pedestrians crossing the street and achieve a second crossing for pedestrians? As shown in the picture, pedestrians who encounter insufficient green light time when crossing the street will stop at the safety island and wait for the red light to disappear before crossing the street.

![safety island](https://github.com/eclipse/sumo/assets/50513332/0c103443-87e3-44c3-abb0-0dcd1c4ee70b)

**SUMO-version:**
1.17.0
**operating system:**
Windows

**Comment by namdre** [comment]
- crossing mode (R)
- click on junction
- click on an incoming edge -> ENTER
- click on an outgoing edge -> ENTER

in contrast, to obtain a crossing without island, click both edges and then ENTER.

Make sure that the roads have sidewalks and that the vehicle lanes disallow pedestrians for the above to work.

**Comment by zhangm269** [comment]
这是来自QQ邮箱的自动回复邮件。您好，邮件已收到。祝好，张萌。

**Comment by jinx2plus** [comment]
Will there be a good example of net.xml for creating a traffic island?

**Comment by behrisch** [comment]
It was a part of the 2022 tutorial but you already noticed, see #13808

**Comment by way-thu** [comment]
@behrisch @zhangm269 @namdre sorry for my bad understanding，i don‘t the problem of setting up island after i try the methods mentioned above，can u give a more detailed information？

**Comment by zlh212** [comment]
I also encountered a similar problem. Have you solved it

**Comment by zlh212** [comment]
I could not make a safe island using the method provided by Namdre. Have you created a safe island in.net.xml? Can I have a look at the file

**Comment by way-thu** [comment]
> I could not make a safe island using the method provided by Namdre. Have you created a safe island in.net.xml? Can I have a look at the file

Give me your email, and I can send a example for you.

**Comment by zlh212** [comment]
Thank you very much
brucezhenglh@gmail.com

**Comment by zlh212** [comment]
I made modifications on the file you provided. First, I deleted the sidewalk in the red circle, and when I added it in the crossing mode, it would prompt an error.
![image](https://github.com/eclipse-sumo/sumo/assets/62287281/9a32bb7c-c616-4752-8f63-4090d842ca9d)
![image](https://github.com/eclipse-sumo/sumo/assets/62287281/5d6e85bf-c878-4be9-8bdd-e70f51ba6455)
Why is that?

**Comment by namdre** [comment]
It seems like you have extra edges in between the outer ones which need to be crossed as well. For this reason the crossings are not connected by an island and go nowhere. If you want a wide green verge, delete the inner edges and instead do the following:

1. select the horizontal edges in select mode
2. use move mode and enter the value 3.2 into the input box labeled "Shift value", then press enter.

**Comment by zlh212** [comment]
![image](https://github.com/eclipse-sumo/sumo/assets/62287281/a8f2be60-9f65-406c-8af6-9f1f5be081f7)
Can sumo build this area in the red circle? If so, can you provide an example file

**Comment by namdre** [comment]
https://sumo.dlr.de/extractTest.php?path=netconvert/function/crossings/specified/4_arm/separate_right_turn_island
