### ISSUE TITLE
simulation error

### ISSUE THREAD

**Issue by leejs-2022** [eclipse/sumo#13265]
Hello
An error occurred during sumo simulation. Both signal data and traffic data were loaded normally, and the simulation was performed normally. However, during the simulation, the simulation stopped with the message "Error: vector too long".
how can I solve it?

warning and error message:
Warning: Missing yellow phase in tlLogic '3843', program '0' for tl-index 6 when switching to phase 0.
Warning: State was written at a different time=1683645299.00 than the begin time 1683645300!
Warning: Teleporting vehicle '766.51122_1683644400_PCAR.663'; waited too long (wrong lane), lane='-36_5', time=1683645426.00.
Warning: Vehicle '766.51122_1683644400_PCAR.663' ends teleporting on edge '368', time=1683645426.00.
Error: vector too long
Quitting (on error).

SUMO-version:1.16
operating system:window 10 pro

**Comment by m-kro** [comment]
How many time steps did you run the simulation before the error occurred and which types of output did you configure? Your warning features a very high SUMO time value. Could it be that you ran out of memory?
