### ISSUE TITLE
Warning:No routes pass edges in routesampler tool

### ISSUE THREAD

**Issue by mehmetnedimyavuz** [eclipse/sumo#13266]
I have a network with two roundabouts. Also ,I have turning count data. I created all possible routes in netedit and saving as  
an candidate route file. And then I prepared  turn count data file for each vehicle type (edge relation data mode in netedit) for input of routesampler tool. In an example for roundabout, possible route is created in netedit like  figure below( route id="r_0" edges="-E5 E18 E60")
![problem](https://github.com/eclipse/sumo/assets/79362739/7c78fa38-9b4b-450e-a7b1-d7ba6495ea04)
For turn count data file, only clicking two edges are allowed and created in netedit like  figure below(-E5 E60).
![image](https://github.com/eclipse/sumo/assets/79362739/ecccb5d3-e8cc-4f5e-b4f5-bc11e75af9ba)

After preparing input files, I called routesampler tool, gives warnings "No routes pass edges "-E5 E60". I am not sure final routes would created properly , and  need to clarify this issue. Thank you for help,regards.

**Comment by namdre** [comment]
by default, edgeRelations expect consecutive edges. However, you can change this by setting option **----turn-max-gap 1** and then your turn counts should work.

**Comment by namdre** [comment]
Could you briefly describe what you did to fix the problem, please? (these issues are a valuable resource for other people who encounter similar problems).

**Comment by mehmetnedimyavuz** [comment]
In my cases, "--turn-max-gap 1" does not satisfy all warnings because some vehicles propagates through three roundabout edges to pass the other leg of intersection. I missed this point from documentation. I set "--turn-max-gap 3". It removes all warnings in my case.
