### ISSUE TITLE
netedit/sumo-gui error

### ISSUE THREAD

**Issue by shiyu022** [eclipse/sumo#13272]
macOS11.7.6
sumo version 1.17.0
![截屏2023-05-16 21 46 55](https://github.com/eclipse/sumo/assets/101698390/32839363-4729-4e76-8de1-26fa25ec17b0)
dyld: Library not loaded: /usr/local/opt/libtiff/lib/libtiff.5.dylib

how can i fix this?
help!!!

**Comment by namdre** [comment]
check workaround described in  #13147
