### ISSUE TITLE
sumolib Convert2D

### ISSUE THREAD

**Issue by JoaoMarcelino** [eclipse/sumo#13275]
Hello,
I'm trying to create a vizualization of the busStops created in pt_stops.add.xml.
I saw that its possible to get the Lat and Lon using TraCI simulation.convert2D [(https://sumo.dlr.de/pydoc/traci._simulation.html)]
Is it possible to do the same using sumolib? If not, is is possible to give me any indications how I could try to implement it?

Thanks,
João Marcelino

**SUMO-version:**
sumo Version 1.17.0

**Comment by namdre** [comment]
see https://sumo.dlr.de/docs/Tools/Sumolib.html#coordinate_transformations
