### ISSUE TITLE
netedit questions(edge length adjustment, intersection length, stop line addition)

### ISSUE THREAD

**Issue by jinx2plus** [eclipse/sumo#13281]
I am a total noob in SUMO and I have three problems using netedit. 

1. How can I edit length of each edge to a certain number? I used Network Mode-Inspect-length by selecting edge, but it seems not working through GUI. 

![image](https://github.com/eclipse/sumo/assets/51274389/1f1b12ca-36de-4b00-b106-de5051023853)

2. How can I adjust this intersection(junction) width to 23meters and height to 21meters. 

![image](https://github.com/eclipse/sumo/assets/51274389/8767fc3d-aba4-4609-bb6e-21d8ad6a6821)

3. Are there options for adding stop line? I want to add a stop line before pedestrian crosswalk, on each intersection edges. 

**netedit 1.17:**

**operating system:**

**Comment by m-kro** [comment]
Changing the edge length:

- Updating the "length" attribute of an edge in Inspect mode will only change its numerical length but not the shape (setting a higher value than that of the shape will make vehicles travel "slower" in the visualisation)
- Change the shape by moving the nodes it is connected to. You can enter coordinates directly in "pos" attribute of a node or use the [grid ](https://sumo.dlr.de/docs/Netedit/index.html#background_grid) to help with positioning

Change intersection shape:

- open context menu (right click on junction)
- choose "Set custom junction shape)
- move the corners as you like
- confirm with [Enter]

Stop lines:

- stop lines are generated automatically - there is no option to add them explicitly just for visualisation
- the stop line can be moved upstream by editing the "stopOffset" [m] attribute of an edge

**Comment by namdre** [comment]
also, you can use 'crossing mode' to add pedestrian crosswalks (https://sumo.dlr.de/docs/Simulation/Pedestrians.html#generating_a_network_with_crossings_and_walkingareas)

**Comment by jinx2plus** [comment]
For measuring length of intersection width and length, I just made another edge next to it and used Inspection mode to check the length.
