### ISSUE TITLE
Teleport semantics: time-to-teleport vs. time-to-teleport.disconnected

### ISSUE THREAD

**Issue by m-kro** [eclipse/sumo#13282]
Not sure whether the documentation does not state it clearly or whether the implementation is to blame:

The option `time-to-teleport.disconnected` is explained as following: _The waiting time after which vehicles with a disconnected route are teleported. Negative values disable teleporting; default: -1._ 
However if `time-to-teleport` is set to a positive value (which it is by default), vehicles are teleported anyway. If teleporting is forbidden by setting `time-to-teleport` to a negative value, it can be reenabled for disconnected routes. But where is the use case of a negative `time-to-teleport.disconnected` value?

**Comment by namdre** [comment]
- time-to-teleport.disconnected = -1: no special rules for disconnected routes (behavior is governed by option time-to-teleport)
- time-to-teleport.disconnected = 0: vehicle teleport instantly upon reaching a gap in their route
- time-to-teleport.disconnected = x: vehicle teleport after x seconds upon reaching a gap in their route
- time-to-teleport.disconnected > time-to-teleport > 0: behavior is governed by option time-to-teleport

So the main use case for -1 is not having to change another option if you just want to change --time-to-teleport and want this to be the general behavioral rule. (i.e. for backward compatibility with simulation configs that predate the option time-to-teleport.disconnected).

The possibly surprising difference in treating the value 0 arises from the fact that a value of 0 makes sense for time-to-teleport.disconnected (and thus -1 is the magic value to disable it) whereas for time-to-teleport 0 is not a reasonable value and we can use it as the "magic" value to disable teleporting-after-jam.
