### ISSUE TITLE
Emergency braking warnings approaching roundabout and on junction

### ISSUE THREAD

**Issue by mehmetnedimyavuz** [eclipse/sumo#13280]
Hello, I am encountering a lots of emergency braking warnings during three hours simulation. When looking into these warnings, some of vehicles perform emergency braking approaching roundabout and some of them occurs on junctions. Vehicles are governed by default car following model.  How to handle these warnings? To reproduce, I am adding files. Thank you for help,regards.
[emergency_braking_issues.zip](https://github.com/eclipse/sumo/files/11507628/emergency_braking_issues.zip)

**Comment by namdre** [comment]
remaining warning are due to #13292  and the easiest work-around at the moment is to increase the step-length

**Comment by namdre** [comment]
('m closing this as a duplicate, but feel free to add comments)

**Comment by mehmetnedimyavuz** [comment]
> remaining warning are due to #13292 and the easiest work-around at the moment is to increase the step-length

Thanks for explanation @namdre .Is there any time planning for remaining warnings fix?

**Comment by namdre** [comment]
The number of warnings has dropped by 80% w.rt. to version 1.17.0.  I cannot give a time frame for when the remaining warnings will be fixed.

**Comment by mehmetnedimyavuz** [comment]
Hello @namdre , I used IDM car following model instead of Krauss. There are warnings with step length 1 second. There was no emergency braking warnings with Krauss model in 1 s step- length.  If step-length sets 0.1 s with IDM model, the number of warnings reaches more than 400 during 10800 s simulation.

**Comment by namdre** [comment]
Is this with 1.17 or with the latest development version? For the latter, the level of emergency braking should be roughly the same for IDM and Krauss for all step lengths (tested with your initial example).

**Comment by mehmetnedimyavuz** [comment]
I downloaded (v1_17_0+0611-19e794c0a97) nightly snapshots. Actually I changed some roundabout connections with respect to initial example and maxSpeed. The results are like below:

-  Krauss cf model with step-length 0.1s : #  of events 46
- Krauss cf model with step-length 1s: no warning
- IDM cf model with step-length 0.1s : #  of events 364
- IDM cf model with step-length 1s : #  of events 35
[comparison_emergency_braking_events.zip](https://github.com/eclipse/sumo/files/11627343/comparison_emergency_braking_events.zip)
