### ISSUE TITLE
Get simulation time after reload crashes sumo-gui

### ISSUE THREAD

**Issue by jjyyxx** [eclipse/sumo#13298]
After starting `sumo-gui` through traci, then calling `traci.load` to reload the scenario, the next `getTime` call would fail with `traci.exceptions.FatalTraCIError: Received answer 2 for command 171`. Using `sumo` or `libsumo` instead of `sumo-gui` works as expected.

```python
import traci
from sumolib import checkBinary

sumo_binary = checkBinary('sumo-gui')
sumo_args = ['--configuration-file', '/usr/share/doc/sumo-doc/examples/sumo/simple_nets/box/box1l/test.sumocfg']

traci.start([sumo_binary, *sumo_args])
traci.simulation.getTime()
traci.load(sumo_args)
traci.simulation.getTime()  # Fails here; may need to tap start button twice
traci.close()
```
**SUMO-version:** 1.17.0

**operating system:** Ubuntu 22.04, Windows 10

**Comment by namdre** [comment]
this is a known issue (#13150) and fixed in dev
