### ISSUE TITLE
[BUG]The desire of vehicles to drive on the right is too strong, resulting in empty lanes that cannot be used

### ISSUE THREAD

**Issue by programming-rubbish** [eclipse/sumo#13300]
[
<img width="301" alt="ea4c306d756ba1ae77c6356438c330a" src="https://github.com/eclipse/sumo/assets/101782360/fc9e7a95-6df8-4806-9733-a074299d6f4c">
](url)
Especially in the area where the road is widened at the intersection, when the lane is changed from three lanes to four lanes, the right side of the road section is the straight lane and the straight right lane, and all straight cars enter the straight and right lanes, but do not enter the straight lane。

**Comment by namdre** [comment]
the most likely reason for the observed behavior is downstream connectivity. if the road narrows to one directional lane somewhat behind the intersection, you can set the junction where it narrows to type=zipper (and also add connections from both lanes) to avoid biasing one of the lanes ahead of the intersection.

**Comment by programming-rubbish** [comment]
The downstream lanes and channelization are shown in the figure below.Please take a look. Thank you!
[
<img width="554" alt="d24777f5aff5eb213c6b64ab344b712" src="https://github.com/eclipse/sumo/assets/101782360/b1021e82-a012-4a6c-b0ab-1a06e803e521">
](url)

**Comment by namdre** [comment]
The problem likely comes from somewhere else:
There is currently no model that randomizes lane choice when *passing* the split that opens up the two rightmost lanes.  Instead, vehicles will perform lane changes to sort themselves on the two right most lanes (and if both lanes are suitable they will form two queues). However, your network model defines a lane changing prohibition between the two rightmost lanes and thus the second queue does not form.

Another doubtful point is whether the fourth lane should open on the right or on the left (in many cases the extra left turn lane is added on the left. Changing the connection layout would also permit two straight-going queues to form regardless of change prohibition.

**Comment by programming-rubbish** [comment]
Thank you for your patient response！ After considering your advice, I changed the lane attributes from prohibiting lane changes to allowing them, and I also adjusted the left turn lane connections as shown in the diagram below. However, I encountered an awkward situation where the simulation's performance worsened. I started wondering if it might be related to the vehicle parameters. Which parameters are relevant to the vehicles' lane change intentions? Once again, thank you for your helpful response.
[
<img width="545" alt="6f63e5d028b199a1df199b07f17b8b8" src="https://github.com/eclipse/sumo/assets/101782360/23ea9271-484d-4b6b-8e97-db017c55fc1d">
](url)[
<img width="700" alt="3ea8046105424001969a4b91210a71f" src="https://github.com/eclipse/sumo/assets/101782360/bd85c0fb-cb12-4714-945d-8ae53207d3c9">
](url)

**Comment by programming-rubbish** [comment]
Thank you for your patient response. After considering your advice, I changed the lane attributes from prohibiting lane changes to allowing them, and I also adjusted the left turn lane connections as shown in the diagram below. However, I encountered an awkward situation where the simulation's performance worsened. I started wondering if it might be related to the vehicle parameters. Which parameters are relevant to the vehicles' lane change intentions? Once again, thank you for your helpful response.
[
<img width="545" alt="6f63e5d028b199a1df199b07f17b8b8" src="https://github.com/eclipse/sumo/assets/101782360/2aa9545d-45e0-4ff8-83e4-a600602df1bd">
](url)
[
<img width="596" alt="921dc3e4f2cf04ed1fd5a35bae5d90b" src="https://github.com/eclipse/sumo/assets/101782360/b018ca2a-be10-48b1-b0c4-03c06cd4706d">
](url)

**Comment by namdre** [comment]
- your intersection features conflicting connections originating on the same edge and targeting the same lane. This is rather unusual in actual traffic layouts (i.e. the two North->South connections merge on a single lane)
- the connection layout I suggested in my previous post was this:
![tmp](https://github.com/eclipse/sumo/assets/6240630/49c1b2d1-089b-4da9-b8ac-790a7faec4d2)
- with respect to traffic performance, i recommend that you change things one at a time to get a better understanding of which change is responsible for the change in behavior.

**Comment by programming-rubbish** [comment]
OK! Thank you soooo much！！！

**Comment by dtGaoP** [comment]
set lcStrategic="-1" maybe can solve this problem
