### ISSUE TITLE
Unit of fuel consumption is ml/s or mg/s

### ISSUE THREAD

**Issue by TrinhTuanHung2021** [eclipse/sumo#13301]
Add your issue description here.

*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**
Hello, I got the output from Sumo simulation

In full-ouput the unit for fuel is ml/s
https://sumo.dlr.de/docs/Simulation/Output/FullOutput.html
![image](https://github.com/eclipse/sumo/assets/82990411/7a95c147-d4a5-4924-a957-05afde9c0ab2)

In emission-output the unit for fuel is mg/s
https://sumo.dlr.de/docs/Simulation/Output/EmissionOutput.html
![image](https://github.com/eclipse/sumo/assets/82990411/48d55ba5-aa31-495b-8864-f0db6ef0031b)

I do not know which unit is correct

**Comment by namdre** [comment]
it's mg/s (unless you set the legacy option **--emissions.volumetric-fuel**.
