### ISSUE TITLE
[JuPedSim] Convert annotated DXF files to SUMO polygon (XML file).

### ISSUE THREAD

**Issue by bcoueraud87** [eclipse/sumo#13306]
For the needs of the SISAME 2.0 project and the SUMO-JuPedSim coupling in general, we need to convert a DXF file into SUMO polygons (as an XML file). This could be implemented using the Python library ezdxf, polyconvert and libsumo.

**Comment by behrisch** [comment]
@RNippold maybe for you as well

**Comment by behrisch** [comment]
We decided to write this as geo-coordinates (at least optionally)

**Comment by behrisch** [comment]
Almost done, the projection should be configurable in the script
