### ISSUE TITLE
Issues about activitygen tool

### ISSUE THREAD

**Issue by hhhhhhyl** [eclipse/sumo#13315]
Hello, I’m trying to generate demand using the activitygen tool (https://sumo.dlr.de/docs/Demand/Activity-based_Demand_Generation.html), but it seems that there was an error in the generation of the work place. How should I fix this?
![image](https://github.com/eclipse/sumo/assets/96480310/ddca5d4d-4790-4f3d-982f-fe9b66fac34d)

**Comment by m-kro** [comment]
Please attach the input files and post how you call activitygen.

**Comment by hhhhhhyl** [comment]
The command I use is "activitygen --net-file map-outer-public-1.net.xml --stat-file activity.xml --output-file activity_trip.trips.rou.xml --random --verbose --debug true", and the input files is shown in netdisk link as below.
[Link: https://pan.baidu.com/s/1Cs9tUQtijrlsSwrkxZ0p2g 
Extracted code: ibpg](url)

**Comment by hhhhhhyl** [comment]
The command I use is "activitygen --net-file map-outer-public-1.net.xml --stat-file activity.xml --output-file activity_trip.trips.rou.xml --random --verbose --debug true", and the input files is shown in netdisk link as below.
[https://pan.baidu.com/s/1Cs9tUQtijrlsSwrkxZ0p2g](url)
Extracted code: ibpg

**Comment by m-kro** [comment]
Could you please attach the files **here** on Github? Baidu is not really usable outside China and is in Chinese only.

**Comment by hhhhhhyl** [comment]
Sorry, my files still exceed the size limit after compression and cannot be uploaded. Could I use Google Disk?
The link is shown as bellow. Thank you very much.
[https://drive.google.com/drive/folders/1n3JtdXRQ3QYYeqh-a103FXkHhytgBuaY?usp=sharing](url)

**Comment by m-kro** [comment]
I can reproduce your result, but fail to debug it effectively due to the size of the example. Is there any chance you can prepare a smaller failing example?

**Comment by hhhhhhyl** [comment]
Hello, I just tried to generate a route using the activitygen example at [https://github.com/eclipse/sumo/blob/main/tests/activitygen/activitygen-example.stat.xml](url), and everything worked normally. 
However, I found that the sum of the population of each age group in the example is significantly different from the total number of inhabitans. May I ask why this is? Will this have an impact on the results?
<img width="1181" alt="image" src="https://github.com/eclipse/sumo/assets/96480310/f8839051-2ea8-4c93-bf0c-beb0fa6bc17c">

**Comment by namdre** [comment]
The values will be normalized: https://sumo.dlr.de/docs/Demand/Activity-based_Demand_Generation.html#populations_age_brackets
