### ISSUE TITLE
Using SUMO with NoiseModelling

### ISSUE THREAD

**Issue by Y-Yahyaoui** [eclipse/sumo#13319]
Hi, I'm currently working on traffic simulation and noise pollution. The NoiseModelling library offers support for MATSim, but I was wondering if there is a way to use SUMO instead ?

**Comment by namdre** [comment]
There is currently no tool to generate the required ROADS table for NoiseModelling, though the sumo edgedata-output (https://sumo.dlr.de/docs/Simulation/Output/Lane-_or_Edge-based_Traffic_Measures.html) does provide the required aggregated traffic data.

Note, that sumo comes with it's own emission model and can provide aggregated (https://sumo.dlr.de/docs/Simulation/Output/Lane-_or_Edge-based_Noise_Measures.html and) as well as raw vehicle noise (https://sumo.dlr.de/docs/Simulation/Output/EmissionOutput.html).  I'm not sufficiently familiar with NoiseModelling to tell you whether this could be used directly.

If you can get the NoiseModelling devs into the discussion I'd be happy to lend some support to get this to work.

**Comment by Y-Yahyaoui** [comment]
Thank you or your response I actually asked the same question in the NoiseModelling repo and got no response, I will check out these emission models. Thank you for your help

**Comment by lavinakarva** [comment]
where u able to use MATSim for noise emission calculation? cuz I am working on something similar and would greatly appreciate help

**Comment by yuzarseeef** [comment]
@lavinakarva I ended up using SUMO and then adapting the outputs for NoiseModelling, I didn't use MATSIM.

**Comment by namdre** [comment]
If you created tools to convert SUMO outputs into NoiseModelling inputs, please consider making them open source (-:

**Comment by lavinakarva** [comment]
can u tell me how did u get traffic volume data which is needed for noise modeling. I actually have data for traffic volume but it's not categorized into Heavy good vehicles and cars.

**Comment by namdre** [comment]
you can define two instances of volume (edgeData)-output which each filters for a different list of vehicle types by setting attribute `vTypes` (https://sumo.dlr.de/docs/Simulation/Output/Lane-_or_Edge-based_Traffic_Measures.html)
