### ISSUE TITLE
What would be the fastest way to change collected vehicle data to flows.xml shape?

### ISSUE THREAD

**Issue by jinx2plus** [eclipse/sumo#13310]
If I have a row of vehicle data(in dataframe dtype) collected from real world, how should I change to flows.xml shape?
Are there tools inside SUMO? Or should I make a code such as below to make it best for me?

---------------------------code---------------------------
import pandas as pd
import xml.etree.ElementTree as ET

# Example traffic volume data in a DataFrame
traffic_volume_df = pd.DataFrame({
    "edge": ["edge1", "edge2"],
    "vehicle_type": ["car", "truck"],
    "begin": [0, 0],
    "end": [3600, 1800],
    "probability": [0.2, 0.1]
})

# Create the root element of the XML file
root = ET.Element("routes")

# Iterate over the traffic volume DataFrame and create flow elements
for _, row in traffic_volume_df.iterrows():
    flow_elem = ET.SubElement(root, "flow")
    flow_elem.set("id", row["edge"])
    flow_elem.set("type", row["vehicle_type"])
    flow_elem.set("begin", str(row["begin"]))
    flow_elem.set("end", str(row["end"]))
    flow_elem.set("probability", str(row["probability"]))

# Create the XML tree
tree = ET.ElementTree(root)

# Save the XML tree to a file
tree.write("flows.xml")

**Comment by namdre** [comment]
you can use` sumo/tools/xml/csv2xml.py -x sumo/data/xsd/routes_file.xsd flows.csv -o flows.xml` if you have a csv file in the correct format.
To get an example for the correct format, define a small exemplary flow.xml and convert it to csv with
`sumo/tools/xml/xml2csv.py example_flows.xml`

Depending on your setup it might be easier to convert your pandas data frame into the appropriate csv but generating the xml directly should also work fine.
