### ISSUE TITLE
Change the default behavior of vehicles in which directory? And I want to build into a new SUMO, how?

### ISSUE THREAD

**Issue by Chaiendxdx** [eclipse/sumo#13326]
Hi everybody. I am a student and am working on a project related to SUMO. The requirement is that the vehicle will automatically change the speed in certain cases. So in which directory do I need the config code, and how do I build a new SUMO application that applies my code to run?
Thanks for reading my problem

**Comment by angelobanse** [comment]
It sounds like you will need to control vehicles using TraCI.
Take a look at the following documentation, specially the tutorials:

### Vehicles and Demand modelling
- [Introduction to demand modelling in SUMO](https://sumo.dlr.de/docs/Demand/Introduction_to_demand_modelling_in_SUMO.html)
- [Definition of Vehicles, Vehicle Types, and Routes](https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html)

### TraCI
- [First steps](https://sumo.dlr.de/docs/TraCI/Interfacing_TraCI_from_Python.html#first_steps)
- [TraCI tutorials](https://sumo.dlr.de/docs/Tutorials/index.html#traci_tutorials)
