### ISSUE TITLE
Who can provide a sumo tutorial for installing old versions of Mac OS? 

### ISSUE THREAD

**Issue by wangyu2233** [eclipse/sumo#13324]
Add your issue description here.
Who can provide a sumo tutorial for installing the old version of Mac OS? Veins only supports version 1.11. According to the command on the official website, the latest version 1.17 is always automatically installed, and the interface for removing version 1.17 and then installing version 1.11 is provided

**SUMO-version:**1.11

**operating system:**macos13.4

**Comment by angelobanse** [comment]
It is possible to install SUMO 1.0.1 or newer via Homebrew. To list all available versions, run `brew search sumo`.

To install the particular version you want, use `brew install sumo@1.11.0`
