### ISSUE TITLE
traffic accident simulate

### ISSUE THREAD

**Issue by SongKun2023** [eclipse/sumo#13336]
Add your issue description here.
Hello, sir. There is a long edge and I want to close a part of the edge to  simulate a traffic accident. However, according to the official website, I have to close the entire edge, and I don't want to split the edge. Will there be any enhancements  in SUMO's future versions?

**Comment by namdre** [comment]
No enhancement for closing part of an edge is planned at the moment though I would not rule out enhancements in principle. However, you can place a stationary car (with a `<stop>`) on an edge to emulate a partial closing. The car may be of arbitrary length.
