### ISSUE TITLE
taxi.idle-algorithm for returning to a specific set of locations

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#13334]
i.e. taxi stand

**Comment by alviraat** [comment]
Can the taxi idling and parking algorithm work with drtOnline.py dynamic routing simultaneously?

**Comment by namdre** [comment]
@alviraat Yes, it works.

**Comment by alviraat** [comment]
i got this warning:  "Warning: unexpected sub_stop format: 'idling' " why am i getting this?  I am using drtOnline.py and <device.taxi.idle-algorithm value="taxistand"/> with parking area additional files.

**Comment by namdre** [comment]
This warning doesn't seem to originate from anywhere in the SUMO code tree. Please open a new ticket and attach minimal example files for reproducing the error.
