### ISSUE TITLE
Variation in output values using sumo-gui, libsumo and eclipse-sumo

### ISSUE THREAD

**Issue by prasuka4** [eclipse/sumo#13339]
Add your issue description here.
Hi,
While running the simulation, It has been observed that the results generated from libsumo and sumo-gui are comparitively different even though the libsumo version and sumo version are same. 
We have observed the difference with vehicle teleporting and also with the change in position of vehicles during the simulation.

Also, if the same simulation is run in different hardware with similar sumo setup and simulation files, then also there was a difference that is being observed.

Along with that I have tried to generate the results using eclipse sumo v 1.16.0 then also there is a difference that is being observed.

Could you please do let me know how can this be solved for maintaining the consistency in the results?

Thanks in advance 

**SUMO-version:**
V1.16.0
*operating system:**
Windows

**Comment by namdre** [comment]
> Along with that I have tried to generate the results using eclipse sumo v 1.16.0

What version of libsumo / sumo-gui have you compared this with? Generally speaking, results may differ between versions due to bug fixing but should be consistent between libsumo / sumo / sumo-gui when running the same version on the same platform.  Almost all of sumo behavior should also be platform independent. 

There are some known platform / hardware depencies in the following components:
- import of geo-referenced networks and any transformations between lon,lat / x,y: This occurs when the different platforms use different versions of the proj library
- some models (EIDM and DriverState) make use of the `log` function which has platform dependent behavior according to the C++ standard (#8921)

**Comment by prasuka4** [comment]
1. Version of libsumo and sumo used in one hardware is  v1.16.0 and python version is 3.7
2. Version of libsumo and sumo used in second hardware is v1.16.0 and python version is 3.8

Ego car following model used was EIDM.
Based on this i have observed that teleport time for Ego is varying for different hardware's 
for 1st the teleport seconds was 284
for 2nd the teleport seconds was 68

Is this due to EIDM or any other dependency.

**Comment by prasuka4** [comment]
Hi,
I have tried with IDM and Krauss, 
For IDM - the output results for some files are similar but few of them are again different for various hardware's.
Similarly, for krauss it has been visualized.
Even the results for krauss and IDM are different in single hardware.

If no carfollowing model is provided will all vehicles, choose Krauss?

**Comment by prasuka4** [comment]
Hi,
A sample has been tested again with IDM in two different hardware's with same configuration of SUMO package.
But the results are quite different:
Hardware 1: Teleport time of Ego: 156, File size: 1067823 kb
Hardware 2: Teleport time of Ego: 1021, File size: 1055142 kb

Also, will there be any difference while running in different OS platforms?
Could you please do let me know how can this be solved for maintaining the consistency in the results?

**Comment by namdre** [comment]
- Do you have a non-traci simulation of IDM or Krauss vehicles behaving differently on different hardware? If so, please provide a minimal version (privately if you cannot share it publicly).
- If not, do you have traci command logs (https://sumo.dlr.de/docs/TraCI/Interfacing_TraCI_from_Python.html#generating_a_log_of_all_traci_commands) that allow reproducing different results on different hardware?
- If neither is the case, consider that the difference may come from your own traci code.

**Comment by prasuka4** [comment]
Hi, I have tried to generated the traci log files, It was observed that the information/results generated between the files of different hardware are different.
![image](https://github.com/eclipse/sumo/assets/48856575/2953c86a-7eed-44af-9c03-34a91d4e4ddf)

**Comment by namdre** [comment]
As already mentioned in an [earlier comment](https://github.com/eclipse/sumo/issues/13339#issuecomment-1569660066), if you have different coordinate conversion libraries on the different systems, this can fully explain the differences in behavior. The different coordinate values in your traci script show that this is most likely the case.

**Comment by prasuka4** [comment]
Hi,
Based on the previous suggestion, I have tried running the simulation on two different hardware's by following similar parameters:
SUMO version: 1.16.0
![image](https://github.com/eclipse/sumo/assets/48856575/f98e0086-eb11-4039-923c-87fd1971156d)

pyproj version: 3.5.0
![image](https://github.com/eclipse/sumo/assets/48856575/24c97eb5-a880-43c7-ba72-8a3276a47a0e)

python version: 3.8.10
eclipse_sumo, traci, libsumo, sumolib version: 1.16.0
Proj: 9.2
Also, while running the simulation following error/warning message is also popping out:
![image](https://github.com/eclipse/sumo/assets/48856575/3d0762dc-ddf4-478b-9a04-430c02877de4)

Still, the output results were different and not accurate. Tested with EIDM, IDM car following models. Could please let me know, how it can be resolved.
Thanks in advance.
