### ISSUE TITLE
POI range visuvalisation

### ISSUE THREAD

**Issue by prasuka4** [eclipse/sumo#13332]
Add your issue description here.
Is it possible to visuvalise the radius of POI range in SUMO-GUI. This helps in understanding of how many vehicles are there under POI range. For your reference please do check below image.
![image](https://github.com/eclipse/sumo/assets/48856575/0fd84142-3f65-4ada-b7e1-3576c78be3e4)

*If possible, upload an example that shows your problem.*
![image](https://github.com/eclipse/sumo/assets/48856575/9b6af7a6-f330-4a03-827f-2c3c3b49701f)

**SUMO-version:**
Version 1.16.0
**operating system:**
Windows

**Comment by namdre** [comment]
either: `traci.poi.highligh`
or https://sumo.dlr.de/docs/Tools/Shapes.html#circlepolygonpy

**Comment by prasuka4** [comment]
Hi,
Is it possible to set the field of view for a POI in sumo gui for detecting the vehicles at specific area of interest.
Please do let me know
THanks
