### ISSUE TITLE
How to connect passenger route for pedestrians to cross crosswalks.

### ISSUE THREAD

**Issue by jinx2plus** [eclipse/sumo#13337]
How to connect passenger edges for pedestrians to cross crosswalks.
From selecting the above north pedestrian-only lane, how should I connect to either edge next to? 
I want to create certain number of passengers and random routes. 
Are there good tutorial videos I can learn and watch for pedestrian walking simulation?

![image](https://github.com/eclipse/sumo/assets/51274389/56d3c467-f49f-42bb-a3c5-762aa7432a3a)

**SUMO-version: netedit 1.17.0**

**operating system:**

**Comment by namdre** [comment]
At the moment, passengers always select the shortest path across an intersection that connects inbound and output "normal" edges (the edges with sidewalks). 
Refer to https://sumo.dlr.de/docs/Simulation/Pedestrians.html
and https://sumo.dlr.de/docs/Tutorials/index.html#sumo_user_conference_tutorials
