### ISSUE TITLE
"fatal: Not a valid object name HEAD" error

### ISSUE THREAD

**Issue by jinx2plus** [eclipse/sumo#13341]
After implementing the below code in SUMO, I get message "fatal: Not a valid object name HEAD".
There seem to be error inserting the file name. How should I fix it?

'''
D:\Traffic-Light-master\SUMO_Tutorial\TrafficLight\trafficLight_traci\env>python tools/turn-defs/generateTurnRatios.py -r magok_dijkstra.rou.xml 
fatal: Not a valid object name HEAD
''''

**Comment by m-kro** [comment]
This sounds rather like a Git-related problem. What if you execute the tool in a freshly cloned repository?

**Comment by jinx2plus** [comment]
Happens the same for using generateTurnRatios.py 

'''
C:\Users\Yong Jin Park>python "C:\Program Files (x86)\Eclipse\Sumo\tools\turn-defs\generateTurnRatios.py" --route-files "D:\Traffic-Light-master\SUMO_Tutorial\TrafficLight\trafficLight_traci\env\magok_dijkstratoomany.rou.xml"
fatal: Not a valid object name HEAD
''''

I just moved "tools" folder to "D:/tools". Thank you!
