### ISSUE TITLE
osmWebWizard.py does not generate scenario at all

### ISSUE THREAD

**Issue by adamelsawaf** [eclipse/sumo#13347]
Hi, I'm using the WSL terminal for VSCode on Windows 10 and I'm trying to run "python osmWebWizard.py" (in the tools directory), but I am immediately greeted with this error, in red text:

```
Start : This command cannot be run due to the error: The system cannot find the file specified.
At line:1 char:1
\+ Start "file:///mnt/c/Program Files (x86)/Sumo/tools/webWizard/index.h ...
\+ \~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand
```

but the process is not killed. I manually open the webWizard in my browser (Google Chrome) and when I click the "Generate Scenario" button, the following error is printed to the console, in white text:

```
Cannot create directory '/mnt/c/Program Files (x86)/Sumo/tools/2023-05-31-15-34-43'.
Building scenario in '/home/adamhc/Sumo/2023-05-31-15-34-43'.
Downloading map data
200 OK
Converting map data
Loading configuration... done.
Error: Could not open types-file '${SUMO_HOME}/data/typemap/osmNetconvert.typ.xml'.
Quitting (on error).
Written configuration to 'osm.polycfg'
Loading configuration... done.
Error: Could not open net-file 'osm.net.xml.gz'.
Quitting (on error).
Traceback (most recent call last):
  File "/mnt/c/Program Files (x86)/Sumo/tools/sumolib/net/__init__.py", line 903, in readNet
    parse(gzip.open(filename), netreader)
  File "/usr/lib/python3.10/gzip.py", line 58, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/usr/lib/python3.10/gzip.py", line 174, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/home/adamhc/Sumo/2023-05-31-15-34-43/osm.net.xml.gz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Program Files (x86)/Sumo/tools/osmWebWizard.py", line 506, in build
    builder.build()
  File "/mnt/c/Program Files (x86)/Sumo/tools/osmWebWizard.py", line 318, in build
    self.edges = sumolib.net.readNet(os.path.join(self.tmp, self.files["net"])).getEdges()
  File "/mnt/c/Program Files (x86)/Sumo/tools/sumolib/net/__init__.py", line 905, in readNet
    parse(filename, netreader)
  File "/usr/lib/python3.10/xml/sax/__init__.py", line 33, in parse
    parser.parse(source)
  File "/usr/lib/python3.10/xml/sax/expatreader.py", line 105, in parse
    source = saxutils.prepare_input_source(source)
  File "/usr/lib/python3.10/xml/sax/saxutils.py", line 365, in prepare_input_source
    f = urllib.request.urlopen(source.getSystemId())
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 503, in open
    req = Request(fullurl, data)
  File "/usr/lib/python3.10/urllib/request.py", line 322, in __init__
    self.full_url = url
  File "/usr/lib/python3.10/urllib/request.py", line 348, in full_url
    self._parse()
  File "/usr/lib/python3.10/urllib/request.py", line 377, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/home/adamhc/Sumo/2023-05-31-15-34-43/osm.net.xml.gz'

Recovering
Recovering
Recovering
```

The process is still alive by the way, but sumo-gui doesn't open, and no files are generated. I have tried restarting my machine. I have also tried changing my SUMO_HOME environment variable, but that doesn't seem to fix anything, so I think my SUMO_HOME is set correctly (in my ~/.bashrc). Sorry if I am repeating a previously stated problem, but I've looked through many of these pages for solutions and nothing seems to work for me. I really appreciate any help, this is my first time using SUMO and OpenStreetMap. Thanks!

**Comment by namdre** [comment]
try running osmWebWizard from a folder in which you have write permissions (instead of from the sumo/tools folder).
(cd to another path and call webWizard using the full path)

**Comment by adamelsawaf** [comment]
> try running osmWebWizard from a folder in which you have write permissions (instead of from the sumo/tools folder). (cd to another path and call webWizard using the full path)



I believe I still run into the same error when I try this.


adamhc@LAPTOP-3M07OLGH:/mnt/c/shared_Lubuntu/coding_stuff/SUMO$ stat .
  File: .
  Size: 4096            Blocks: 0          IO Block: 4096   directory
Device: eh/14d  Inode: 5629499534429725  Links: 1
Access: (0777/drwxrwxrwx)  Uid: ( 1000/  adamhc)   Gid: ( 1000/  adamhc)
Access: 2023-06-01 10:23:08.173500100 -0400
Modify: 2023-06-01 10:23:08.152582800 -0400
Change: 2023-06-01 10:23:08.152582800 -0400
 Birth: -
adamhc@LAPTOP-3M07OLGH:/mnt/c/shared_Lubuntu/coding_stuff/SUMO$ python /mnt/c/Program\ Files\ \(x86\)/Sumo/tools/osmWebWizard.py
Start : This command cannot be run due to the error: The system cannot find the file specified.
At line:1 char:1
+ Start "file:///mnt/c/Program Files (x86)/Sumo/tools/webWizard/index.h ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand
 
Building scenario in '/mnt/c/shared_Lubuntu/coding_stuff/SUMO/2023-06-01-10-24-05'.
Downloading map data
200 OK
Converting map data
Loading configuration... done.
Error: Could not open types-file '${SUMO_HOME}/data/typemap/osmNetconvert.typ.xml'.
Quitting (on error).
Written configuration to 'osm.polycfg'
Loading configuration... done.
Error: Could not open net-file 'osm.net.xml.gz'.
Quitting (on error).
Traceback (most recent call last):
  File "/mnt/c/Program Files (x86)/Sumo/tools/sumolib/net/__init__.py", line 903, in readNet
    parse(gzip.open(filename), netreader)
  File "/usr/lib/python3.10/gzip.py", line 58, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/usr/lib/python3.10/gzip.py", line 174, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/c/shared_Lubuntu/coding_stuff/SUMO/2023-06-01-10-24-05/osm.net.xml.gz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Program Files (x86)/Sumo/tools/osmWebWizard.py", line 506, in build
    builder.build()
  File "/mnt/c/Program Files (x86)/Sumo/tools/osmWebWizard.py", line 318, in build
    self.edges = sumolib.net.readNet(os.path.join(self.tmp, self.files["net"])).getEdges()
  File "/mnt/c/Program Files (x86)/Sumo/tools/sumolib/net/__init__.py", line 905, in readNet
    parse(filename, netreader)
  File "/usr/lib/python3.10/xml/sax/__init__.py", line 33, in parse
    parser.parse(source)
  File "/usr/lib/python3.10/xml/sax/expatreader.py", line 105, in parse
    source = saxutils.prepare_input_source(source)
  File "/usr/lib/python3.10/xml/sax/saxutils.py", line 365, in prepare_input_source
    f = urllib.request.urlopen(source.getSystemId())
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 503, in open
    req = Request(fullurl, data)
  File "/usr/lib/python3.10/urllib/request.py", line 322, in __init__
    self.full_url = url
  File "/usr/lib/python3.10/urllib/request.py", line 348, in full_url
    self._parse()
  File "/usr/lib/python3.10/urllib/request.py", line 377, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/mnt/c/shared_Lubuntu/coding_stuff/SUMO/2023-06-01-10-24-05/osm.net.xml.gz'

Recovering
Recovering
Recovering

**Comment by namdre** [comment]
is the environment variable SUMO_HOME defined inside the windows container? It should point to `/mnt/c/Program\ Files\ (x86)/Sumo`

**Comment by adamelsawaf** [comment]
> is the environment variable SUMO_HOME defined inside the windows container? It should point to `/mnt/c/Program\ Files\ (x86)/Sumo`

I think so? I'm not sure how to check that other than running `echo $SUDO_HOME`, which seems to print the correct value every time. My SUDO_HOME is set to "/mnt/c/Program Files (x86)/Sumo", without any backslashes at all. I tried adding backslashes to escape the spaces, or adding backslashes to escape the pair of parentheses, or adding backslashes to escape both. Changing my SUMO_HOME like this doesn't seem to fix much, adding backslashes gives me a different error message after clicking **Generate Scenario**:


```
Building scenario in '/mnt/c/shared_Lubuntu/coding_stuff/SUMO/2023-06-01-12-21-11'.
Downloading map data
200 OK
Converting map data
usage: osmWebWizard.py [-h] [-c FILE] [-C FILE] [--save-template FILE] [-p PREFIX] [-f OSM_FILE] [-m TYPEMAP] [--netconvert-typemap NETCONVERT_TYPEMAP] [-o OLDAPI_PREFIX] [-t TILES]
                       [--vehicle-classes VEHICLE_CLASSES] [-d OUTPUT_DIRECTORY] [-n NETCONVERT_OPTIONS] [--pedestrians] [-y POLYCONVERT_OPTIONS] [-z] [-v]
osmWebWizard.py: error: typemap file "${SUMO_HOME}/data/typemap/osmPolyconvert.typ.xml" not found
```




Since osmWebWizard.py is displaying its usage message, it seems like that's worse.

**Comment by namdre** [comment]
Can you successfully run osmWebWizard outside WSL (on plain windows)?

**Comment by adamelsawaf** [comment]
> Can you successfully run osmWebWizard outside WSL (on plain windows)?

When I tried to run `osmWebWizard.py` using PowerShell instead of WSL, the process hangs until I force it to terminate (ctrl + c):

```
PS C:\shared_Lubuntu\coding_stuff\SUMO> python 'C:\Program Files (x86)\Sumo\tools\osmWebWizard.py'

Traceback (most recent call last):
  File "C:\Program Files (x86)\Sumo\tools\osmWebWizard.py", line 596, in <module>
    main(get_options())
  File "C:\Program Files (x86)\Sumo\tools\osmWebWizard.py", line 592, in main
    server.serveforever()
  File "C:\Program Files (x86)\Sumo\tools\webWizard\SimpleWebSocketServer.py", line 703, in serveforever
    self.serveonce()
  File "C:\Program Files (x86)\Sumo\tools\webWizard\SimpleWebSocketServer.py", line 645, in serveonce
    rList, wList, xList = select(self.listeners, writers, self.listeners, self.selectInterval)
KeyboardInterrupt
PS C:\shared_Lubuntu\coding_stuff\SUMO>
```

I tried this in both the tools folder as well as a different folder that has full permissions (shown above), but both display the same error message after I terminate them. Right after I enter the command in PowerShell, `tools/webWizard/index.html` opens in a new VSCode window, but I can't really do anything with it. But before terminating the process in PowerShell, I open the local webpage `http://127.0.0.1:5500/tools/webWizard/index.html` to see if anything worked, but after a few seconds I receive a JavaScript alert saying `Socket connection failed. Please open the OSM WebWizard by using osmWebWizard.py or the link in your start menu`.

**Comment by namdre** [comment]
I don't really have a good idea what could be causing this. For me it's running fine on windows. There might be some security settings on your machine that prevent local scrips from communicating with a web browser.

What version of python are you using?
Does it make a difference if you use 'cmd' instead of powershell?

**Comment by behrisch** [comment]
Please double check whether your WSL has GUI support at all

**Comment by adamelsawaf** [comment]
> Please double check whether your WSL has GUI support at all

I'm not sure how to check this, but I'm using WSL 1, which I believe has GUI support? It's never given me problems like this.





> I don't really have a good idea what could be causing this. For me it's running fine on windows. There might be some security settings on your machine that prevent local scrips from communicating with a web browser.
> 
> What version of python are you using? Does it make a difference if you use 'cmd' instead of powershell?


I'm using Python 3.10.11. But using cmd now works! I'm not sure why, but now osmWebWizard works properly using PowerShell as well! I'm still having the same error with running osmWebWizard on WSL, but this isn't a huge issue since now I can just use cmd or PowerShell instead to run the one command in the background.


Thank you guys for your attention, I really appreciate everyone's help!
