### ISSUE TITLE
What is the Route cost calculation formula from using DUA router? 

### ISSUE THREAD

**Issue by jinx2plus** [eclipse/sumo#13348]
1. What is the Route cost calculation formula from using DUA router? 
I've gotten routes(adjacent edges connected) from setting TAZ(O-D matrix) in DUA router, but cannot interpret how routes of each vehicles are formed. 
I assume it's mainly by travel time and congestion level. 
If I cannot know the exact Route cost calculation formula, what are the main factors of it? 

2. Are there a tool for assigning routes based on the simulation's congestion? 
If the routes are defined by the fastest route by DUA router, and if the results are same for each entry direction, congestion will happen after all. 
 I tried dualterate.py, but keep getting errors. I used the same input xml files for DUArouter configuration. 
 I assume there is Automatic Routing(https://sumo.dlr.de/docs/Demand/Automatic_Routing.html), but it I guess my network is just one intersection, so I might try at a bigger intersection. 

**SUMO-version:1.17.0**

**operating system:**

**Comment by namdre** [comment]
1. by default, total travel time is used as route cost and the route with the shortest duration is used. This takes into account speed limits and vehicle maximum speed. By default non congestion effects are considered. However, there is a configurable penalty (default 1.5s) when passing an intersection without priority. If running with option **--weight-files** (i.e. in the context of duaIterate.py) then the travel times are instead based on time-dependent recorded values. This means the estimated travel time for a particular part of the network depends on the time of day at which cars travel there.  See also https://sumo.dlr.de/docs/Simulation/Routing.html

2. https://sumo.dlr.de/docs/Demand/Dynamic_User_Assignment.html. If you cannot get duaIterate.py to work, post the errors here. Though assignment shouldn't play any role in a network with just one intersection and thus without alternative routes.
