### ISSUE TITLE
problem in connecting to sumo as server x11 (sumo-gui) with traci

### ISSUE THREAD

**Issue by erfanmo** [eclipse/sumo#13356]
Hello, I would be grateful if someone could help me with this problem. I currently have a Linux server (Ubuntu) that I install and run Sumo as a container, and I also use X11 protocol and Sumo-gui to view its graphical environment in my client, but when I want to use Traci, I connect to sumo server container with below code I see output with error "Quittiny (on error)" in sumo window , How can I solve this problem?

Traci Sampel ==> ![image](https://github.com/eclipse/sumo/assets/34267051/4ce536d9-a55b-4768-b9e3-6d7a20639576)

Error Code ==> ![image](https://github.com/eclipse/sumo/assets/34267051/6dfe7a40-aca8-4bdb-8526-7aab6d9f6fc2)

**SUMO-version: 1.12.0**

**operating system:Ubuntu**

**Comment by m-kro** [comment]
I suspect this may be related to the SUMO_HOME variable not being set. You could try to either set the variable or start sumo-gui with option `--xml-validation never`.

**Comment by erfanmo** [comment]
Thank you for your solution but again when I run test traci code I get same error  
![image](https://github.com/eclipse/sumo/assets/34267051/3ec2cc79-3225-4584-b510-432a51d253e0)

**Comment by erfanmo** [comment]
To run sumo-gui , I first enter the container on the server, and then I run sumo-gui so that the Sumo graphical environment can be run for me using X11 and xming in my Windows client and through Putty.

**Comment by namdre** [comment]
The clue is `loading of '' failed`.  You need to start sumo-gui with a network file if you want to use it as traci server.

**Comment by erfanmo** [comment]
thanks you so much for your helping can you tell me how I should use network file in  this command :
sumo-gui --remote-port 1234

**Comment by namdre** [comment]
sumo-gui -n networkfile.net.xml --remote-port 1234

**Comment by erfanmo** [comment]
thanks you so much it worked finally.
