### ISSUE TITLE
provide xsd for .netecfg

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#13355]

**Comment by namdre** [comment]
@angelobanse @behrisch The script that generates xsd also populates the netedit.md file with option documentation. This results in the creation of `docs/netedit.html`. However, the page is never shown and instead redirects to `docs/Netedit/index.html`.  
Would you rather rewrite `tools/build/rebuildConfigDocsAndXsd.py` to patch Netedit/index.md or remove the redirect and move the contents from Netedit/index.md to netedit.md ?

**Comment by behrisch** [comment]
I would remove the redirect. Both pages seem to me already big enough.

**Comment by namdre** [comment]
Please do. I would then add links between them and maybe shuffle some content around.
