### ISSUE TITLE
Mouse click does not control the intersection correctly

### ISSUE THREAD

**Issue by m-kro** [eclipse/sumo#13366]
Some of the game variants cannot be played (well) because of the mouse interaction:

- six junctions: control by keyboard is fine, but left mouse click targets the upper left intersection indepedently of the cursor position (still working in v.1.17)
- highway ramp: does not work at all (since at least v1.17)
- on off ramp: only works once then does not react on left mouse click (since at least v.1.17)

**Comment by namdre** [comment]
any idea what caused the regression for six junctions?

**Comment by m-kro** [comment]
@namdre Hope I understood your intention for #12971 correctly. With your code, a single green phase like in the ramp game would get skipped.
