### ISSUE TITLE
How to combine  traffic signal phases in a Position-time diagram?

### ISSUE THREAD

**Issue by TrinhTuanHung2021** [eclipse/sumo#13364]
Add your issue description here.
In a report with SUMO, I see that they can combine traffic signal phases in a position-time diagram. For example:
![image](https://github.com/eclipse/sumo/assets/82990411/9595498a-0ab6-420f-aec5-d0d06579af5f)

I followed the instruction on the Sumo website to plot trajectories
python plot_trajectories.py fcd.xml -t td -o plot.png -s
![image](https://github.com/eclipse/sumo/assets/82990411/959e250a-1e96-448a-bd81-715043516529)

So I would like to ask the way to show traffic signal phases in the position-time diagram.
Thanks

*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**

**Comment by namdre** [comment]
There is no tool or tool option in SUMO to create this kind of plot. I'm guessing it was either created with a custom matplotlib script or manually (i.e. with an image editor).
