### ISSUE TITLE
error when calling tools without argument

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#13388]
various python tools are using an invalid format string in their usage message

**Comment by namdre** [comment]
regression in 1.17.0

**Comment by namdre** [comment]
caused by switching from the old `OptionParser` to `sumolib.ArgumentParser`  which used `%prog` instead of `%(prog)s`

**Comment by behrisch** [comment]
I would argue that most of these usage strings do not add any information above the standard generated help message and should be removed

**Comment by namdre** [comment]
whereas the defaut usage message contains all options, a custom usage string is potentially more succinct. I'd rather keep it.
