### ISSUE TITLE
vehicle type missing in saved state and vehroute-output for vehicle added via TraCI

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#13384]

**Comment by bonni93** [comment]
Hi, I think the patch works only if the type and vehicle ID are the same.
Example: if you have a vehicle with ID 'xx_0' but type 'xx', the saved state will have for both ID and type 'xx_0', and therefore you will have an error for type 'xx_0' not existing when trying to load that saved state in the same simulation. It could be circumvented by having one type for each vehicle added, but I think a more flexible approach would be to indeed show the type in the vehicle type statement within the saved state. That would correspond to a modification as:
`vehicleParams.vtypeid = vehicleType;` 
on line 1522 of `Vehicle.cpp` (or something similar that reflect the true vehicle type...)
