### ISSUE TITLE
about '--max-num-vehicles'

### ISSUE THREAD

**Issue by Clown1206** [eclipse/sumo#13398]
Add your issue description here.
 How to use the parameter ‘max-num-vehicles’. It didn't work when I wrote code like this `<processing><max-num-vehicles values='350'/> </processing>` in.sumocfg
*If possible, upload an example that shows your problem.*

**SUMO-version:**
1.16
**operating system:**
win10

**Comment by namdre** [comment]
its `value` not `values`
