### ISSUE TITLE
How to config car following and lane change model type and parameters using TRACI in python.

### ISSUE THREAD

**Issue by CRHPlusAI** [eclipse/sumo#13399]
I am setting up SUMO traffic using tarci and randomly adding vehicles via `traci.vehicle.add` in python. 
I want to config different lane-change and car-following models for each different vehicle. but I did not find any function available [here](https://sumo.dlr.de/pydoc/traci._vehicle.html)
Is configuring different lane change model supported? 

If so how to do this with `traci.vehicle` when adding the vehicle? 

Also in terms of model parameter setting, I am a bit confused on the correlation between model parameters and the name. 
From the doc it is stated that one should use [setParameter](https://sumo.dlr.de/userdoc/Developer/How_To/Lane-Changing_Model.html#using_custom_parameters_via_traci) with corresponding fields. 

Yet I found it hard to correlate model parameters with the method/string that one should use to change it. 
Is there a summary or list on the parameter name for each models? 

For example, I think by default the car following model is Krauss model and the default for lane change model is LC2013. 
Then I attempt to change car following model using the following

```
    traci.vehicle.setParameter(veh_id, "carFollowModel.myHeadwayTime", "2")
    traci.vehicle.setParameter(veh_id, "carFollowModel.myDawdle", "0.5")
```
where [myHeadwayTime](https://github.com/eclipse/sumo/blob/7d162bcda564f9c7c34a8ac4def1f7ccf78abdc3/src/microsim/cfmodels/MSCFModel.h#L703) is in the parent class, while [myDawdle](https://github.com/eclipse/sumo/blob/7d162bcda564f9c7c34a8ac4def1f7ccf78abdc3/src/microsim/cfmodels/MSCFModel_KraussOrig1.h#L148) is defined in the Karuss derived class.

This appears to be working with no error popped up. 

By contrast, to change some of the lane change model parameter, I have to base on [this layout](https://github.com/eclipse/sumo/blob/7d162bcda564f9c7c34a8ac4def1f7ccf78abdc3/src/utils/xml/SUMOXMLDefinitions.cpp#LL593C9-L593C19) which are used in the [`setParameter` function](https://github.com/eclipse/sumo/blob/7d162bcda564f9c7c34a8ac4def1f7ccf78abdc3/src/microsim/lcmodels/MSLCM_LC2013.cpp#L2132-L2133)

```
      traci.vehicle.setParameter(veh_id, "laneChangeModel.lcSpeedGain", "2.0")
```
And yet if I use [lookAheadSpeed](https://github.com/eclipse/sumo/blob/7d162bcda564f9c7c34a8ac4def1f7ccf78abdc3/src/microsim/lcmodels/MSLCM_LC2013.cpp#L2171-L2172)
```
      traci.vehicle.setParameter(veh_id, "laneChangeModel.lookAheadSpeed", "1.0")
```
I would get unsupported error, although there is a string [defined](https://github.com/eclipse/sumo/blob/7d162bcda564f9c7c34a8ac4def1f7ccf78abdc3/src/microsim/lcmodels/MSLCM_LC2013.cpp#L2171-L2172) for it.

```
traci.exceptions.TraCIException: Vehicle 'veh01' does not support laneChangeModel parameter 'laneChangeModel.lookAheadSpeed' (Setting parameter 'lookAheadSpeed' is not supported for laneChangeModel of type 'LC2013').

```
Using parameters like  `laneChangeModel.mySpeedGainParam` similar to the car following model case [defined in header](https://github.com/eclipse/sumo/blob/7d162bcda564f9c7c34a8ac4def1f7ccf78abdc3/src/microsim/lcmodels/MSLCM_LC2013.h#L217-L248) would lead to similar error  "unspported parameter"

I wonder if what I am doing is the designed way or there are better approach to achieve this? 
I hope there could be a clear list on the correspondence some where.
Thanks!

**SUMO-version:**
1.8.0
**operating system:**
Ubuntu 20.04 docker

**Comment by namdre** [comment]
- there is currently no way to change the carFollowModel via TraCI. As a workaround, you can define vTypes with differnt carFollowModels in an xml input file and then use those types when adding vehicles. Note that you can copy an existing type via TraCI and change most other attributes
- there is currently no way to change the laneChangeModel via TraCI but it also shouldn't be necessary. There is one dedicated model for sublane simulation and another one for the normal (non-sublane simulation) and they are selected automatically as appropriate 
- the carFollowModel parameters tau and sigma (dawdle) can be set using traci.vehicletype.setTau and traci.vehicletype.setImperfection
- the call `traci.vehicle.setParameter(veh_id, "carFollowModel.myHeadwayTime", "2")` takes no effect and should instead trigger a warning. **This is a bug**
- `laneChangeModel.lookaheadspeed` is only supported in more recent versions but not in version 1.8.0. Note, that it belongs to the set of "internal state" variables wich are mainly exposed for debugging. It should not be confused with the parameter `lcSpeedGainLookahead` (which is also supported in 1.8.0)

**Comment by CRHPlusAI** [comment]
Thank you @namdre  for the reponses! Very helpful!

A quick follow up:

> * there is currently no way to change the laneChangeModel via TraCI but it also shouldn't be necessary. There is one dedicated model for sublane simulation and another one for the normal (non-sublane simulation) and they are selected automatically as appropriate
I assume the non-sublane simulation uses LC2013 while the sublane simulation uses SL2015? What about 'JE2013' and 'DK2008'? 

> * the carFollowModel parameters tau and sigma (dawdle) can be set using traci.vehicletype.setTau and traci.vehicletype.setImperfection

For setting with method like `traci.vehicletype.setTau` is there a instruction or list between each function and model parameters? for exmaple [setLaneChangeMode](https://github.com/eclipse/sumo/blob/1d9458f9fa0593bca2e6105f70748e3c3030ed3b/tools/traci/_vehicle.py#L1406) function I cannot find good content on the flag and its meanings,
 
Thank you again!

**Comment by namdre** [comment]
- JE2013 was folded into LC2013 and DK2008 is obsolete.
- see https://sumo.dlr.de/docs/TraCI/Change_VehicleType_State.html and  https://sumo.dlr.de/docs/TraCI/Change_Vehicle_State.html#lane_change_mode_0xb6
