### ISSUE TITLE
How to get the information of car neighbors for each car

### ISSUE THREAD

**Issue by harirRzi** [eclipse/sumo#13401]
Add your issue description here.

*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**
Hi. I'm trying to simulate cars movements in Sumo. I need to output the y position and x position, acceleration and speed for each car and id of each car. I want to know how can I output these information while I would like to know the id of each car and the neighbor cars of each? I appreciate if you let me know how can I get these information.

**Comment by namdre** [comment]
https://sumo.dlr.de/docs/Simulation/Output/FCDOutput.html with option **--fcd-output.acceleration**
you can get the leader by setting option --fcd-output.max-leader-distance FLOAT.
There is no xml output that gives neighbors or followers (but of course you can do post-processing to get them).

Alternatively you can use traci to retrieve the surrounding vehicles but this is considerably more involved: https://sumo.dlr.de/docs/TraCI/Object_Context_Subscription.html#command_0x7e_add_context_subscription_filter

**Comment by harirRzi** [comment]
Is this command correct according to what you mentioned as the output?   sumo -c /SUMOT/detection/square-street/demo.sumocfg--fcd-output//SUMOT/detection/square-street/sumoTracefcdfile1.xml--fcd-output.acceleration, because when I use this command, I get this error: Error: Could not access configuration '/SUMOT/detection/square-street/demo.sumocfg'

**Comment by namdre** [comment]
no. As the error indicates, the command is wrong. However, it is wrong because you are setting incorrect file paths and not due to any problem with the choice of sumo options.

**Comment by harirRzi** [comment]
As you mentioned I used this command while being in the directory to output also the acceleration data: 

sumo -c demo.sumocfg --fcd-output.acceleration output/sumoTracefcdfile1.xml

but I get this error:
Error: While processing option 'fcd-output.acceleration':
 'output/sumoTracefcdfile1.xml' is not a valid bool.
Error: Could not parse commandline options.
Quitting (on error).

How can I get also the acceleration data for each car?

**Comment by namdre** [comment]
please refer to the documenation on how these options are to be used: https://sumo.dlr.de/docs/Simulation/Output/FCDOutput.html#further_options
**--fcd-output output/sumoTracefcdfile1.xml --fcd-output.acceleration**
