### ISSUE TITLE
how to change the lane line type?

### ISSUE THREAD

**Issue by Wenxiao69** [eclipse/sumo#13405]
I create a two-lane road in both directions. The default road has a solid line in the middle. How to change it to a dashed line and change the color of line?

**Comment by namdre** [comment]
Changing line style or color for the central road divider is not supported at the moment (these things would have no impact on the simulation anyway). 
- if you load background images at layer 5 you can use them to occlude the default roads and have cars drive on top of your custom image: https://sumo.dlr.de/docs/sumo-gui.html#showing_background_images
- for opposite overtaking, see https://sumo.dlr.de/docs/Simulation/OppositeDirectionDriving.html
