### ISSUE TITLE
'viaLonLat' is not declared for element 'personTrip'

### ISSUE THREAD

**Issue by mich-pest** [eclipse/sumo#13406]
I'm trying to define a route for a pedestrian in the simulation, providing two locations in terms of their Longitude and Latitude. In my specific case I should also be able to indicate intermediate points through the `viaLonLat` attribute inside the `personTrip` tag. However, when I insert this field in my trips.xml file, the following error appears: 

```bash
Error: attribute 'viaLonLat' is not declared for element 'personTrip'
``` 
This is the command I run: 
```bash
duarouter --net-file map.net.xml --route-files trips.xml -o result.rou.xml
```
And this is my `trips.xml` file:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<routes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/routes_file.xsd">
    <person id="1" depart="0.3" color="red">
        <personTrip fromLonLat="18.058728387072627,59.34050237576734" toLonLat="18.061471026704893,59.3375947022346" viaLonLat="18.062154395383633,59.34025894072966"/>    
    </person>
</routes>
```
Reading online I found these 2 discussions (https://www.eclipse.org/lists/sumo-user/msg07261.html, https://github.com/eclipse/sumo/issues/12559) in which this feature is considered to be available for `personTrip` items. Nothing changes also if I insert a `mode` attribute inside the tag.
Am I missing something? 

**SUMO-version:**
My SUMO-version should be 1.17.0 and I'm working on Ubuntu 20.04.6 LTS.

Thanks

**Comment by namdre** [comment]
persons don't support any kind of via attributes because their definition already allows a list of plan elements:
```
<person ...>
    <personTrip fromLonLat="START" toLonLant="VIA"/>
    <personTrip toLonLant="VIA2"/>
    <personTrip toLonLant="END"/>
</person>
```
