### ISSUE TITLE
Warm-up period and RouteSampler tool

### ISSUE THREAD

**Issue by mehmetnedimyavuz** [eclipse/sumo#13408]
Hello @namdre , My network has three intersection consecutively and three hours analysis period. I created turn-count data files for each vehicle type with 15 min interval. (0-900,900-1800 etc.). Then route files are created by using routesampler tool. At this point, I would like to input flow that already some vehicles running in the network before three-hour analysis period. Is there any option to integrate the random flow as an warm-up and count data files? Or, Do I need to change time intervals in  count data files for each vehicle type? 
Thank you for help, regards.

**Comment by namdre** [comment]
you could use randomTrips to put a lot of traffic onto the network in the first simulation second:
ie. with options **-p 0.001 -e 1** you will get 1000 vehicles. Simply load those randomTrips alongside the routeSampler output and make sure that you are getting distinct ids by setting option **--prefix**.
