### ISSUE TITLE
Flow randomness doesn't work

### ISSUE THREAD

**Issue by amin-tabrizian** [eclipse/sumo#13418]
When using different randomness options for a flow, I don't get the expected behavior. Although I tried different methods for adding randomness to the flow (e.g., end and period="exp(x)" or end and probability) the number of taken steps are exactly the same in different simulations

v1_15

![Screenshot 2023-06-14 at 1 56 41 PM](https://github.com/eclipse/sumo/assets/34487658/443567de-151f-40ff-87a9-2c1bcb829277)

**Comment by namdre** [comment]
you need to use different random seeds to achive different outcomes: https://sumo.dlr.de/docs/Simulation/Randomness.html

**Comment by amin-tabrizian** [comment]
Is there any way for using different random seeds using traci?
