### ISSUE TITLE
After reloadState  , traci.simulation.getCollidingVehiclesNumber() result inconsistency [bug]

### ISSUE THREAD

**Issue by MJLee00** [eclipse/sumo#13419]
I want to reload the state file to replay the collision events, but when I reload it, traci.simulation.getCollidingVehiclesNumber() results are inconsistent, here is a part of my state file which contains the collisions keyword
*If possible, upload an example that shows your problem.*

    <vehicle id="182162_431_0" type="pkw" depart="26711.00" route="!182162_431_0" distance="351.23 0" speedFactor="1.1252" reroute="1" state="262146 26749000 0 4.40 0 4.35 26776000 0 0" pos="7.11 2.81 14.75" speed="14.75 15.31" angle="257.27" posLat="0.00" waitingTime="10000000 0">
        <stop lane=":cluster_357187_359543_1_1" startPos="5.29" endPos="5.29" duration="50.00" collision="1"/>
        <device id="routing_182162_431_0" state="0"/>
    </vehicle>

**SUMO-version: 1.17.0

**operating system: windows. 11

**Comment by namdre** [comment]
getCollidingVehiclesNumber only counts collision events in the prior step. If the collision event took place before the state was saved (which it did according to your state file), it is not expected to be counted after loading the state. Instead, the state should be saved before the collision.

**Comment by MJLee00** [comment]
I save the states of the prior 10 steps of the collision, load them in turn, execute the next step, and count the number of collisions until the collision, the function traci.simulation.getCollidingVehiclesNumber() always returns 0

**Comment by MJLee00** [comment]
Thank you for the explanation！
