### ISSUE TITLE
osmGet OSM data update frequency

### ISSUE THREAD

**Issue by gladysmcgan** [eclipse/sumo#13417]
How frequently is the OSM data obtained from osmGet updated? Is it obtained directly from the OSM database?

**Comment by m-kro** [comment]
The default access to OSM data in osmGet.py happens through the [Overpass API](www.overpass-api.de/api/interpreter) service. This service is meant to give a read access to the OSM database. The [OpenStreetmap website](https://wiki.openstreetmap.org/wiki/Overpass_API) states that it can take a few minutes of lag until OSM changes are available.
