### ISSUE TITLE
sumolib.geomhelper.line2boundary()

### ISSUE THREAD

**Issue by a-123-du** [eclipse/sumo#13435]
I use the function line2bounary to expand the shape value of the edge to half of the width. Why is the shape value of the lane obtained inconsistent with the shape value of the lane generated by the road network file? How to put the shape value of the lane generated by the line2boundary function into .net.xml? Thank you very much.
![f73dc81c8a38e3ead83f3ba0c8632e5](https://github.com/eclipse/sumo/assets/54823725/0b0e3f25-c8de-4ce6-b60c-fe9d51aa7c42)

**SUMO-version:1.17.0**

**operating system:Windows**

**Comment by namdre** [comment]
the edge shape usually denotes the center line of the road (i.e. both directions have the same shape only reversed) whereas line2boundary spreas the shape evenly to both sides.  For some background see https://sumo.dlr.de/docs/Networks/PlainXML.html#spreadtype.

You cannot ever put lane boundaries into the .net.xml, only lane center lines.
