### ISSUE TITLE
Can not change right of way of junction in netedit

### ISSUE THREAD

**Issue by mehmetnedimyavuz** [eclipse/sumo#13434]
Hello, I would like to change right of way setting "default" to "edgepriority" in netedit. However, it can not be changed. I am using Eclipse SUMO sumo Version v1_17_0+0966-791c67e8cd8. Regards.
![image](https://github.com/eclipse/sumo/assets/79362739/a89cc8e4-0a10-4635-a6cd-839a2f06059d)

**Comment by namdre** [comment]
Thanks for reporting! @palvarezlopez was still working in 1.17.0, do we have a test for this?

**Comment by namdre** [comment]
please note that 'edgePriority' is usually not needed unless you mix different traffic modes ad the same intersection (i.e. cars and tram). The "normal" case can be handled with default mode, simply by setting higher priority values to the main road edges. See also #13436

**Comment by palvarezlopez** [comment]
Broken in be873a69540e3f0a479ea5afb435b24782cf19b6
