### ISSUE TITLE
Is there a way to generate random trips with additional parameter actualBatteryCapacity?

### ISSUE THREAD

**Issue by tranvary** [eclipse/sumo#13430]
I want to generate random trips of electric vehicles and set their initial battery capacity via additional parameter actualBatteryCapacity, but it seems randomTrips.py dosen't provide such function.What should I do?

**Comment by m-kro** [comment]
You can prepare a vehicle type (or a distribution of vehicle types) which represent your electric vehicles. Each is equipped with a battery device and has the value of actualBatteryCapacity defined. See [this test](https://github.com/eclipse/sumo/tree/main/tests/tools/trip/randomTrips/attributes/vtype_additional_file_validate) on how to use a specific vehicle type in randomTrips.

**Comment by tranvary** [comment]
It works.I finally use createVehTypeDistribution.py to create a series of vehType and use randomTrips.py to create random trips  with different initial battery capacity by specifying --trip-attributes="type=\"EVdist\"" --additional-file vTypeDistributions.add.xml, where "EVdist" is the name of VehTypeDistribution.Hope this will be helpful to other users.
