### ISSUE TITLE
vehicles depart at wrong time 

### ISSUE THREAD

**Issue by yuameier111** [eclipse/sumo#13437]
hello, 
I run 24 hours simulations on vehicles around 200,000，all the vehicles deaprt and arrive within 24 hours. But the simulation lasts over 200,000 seconds (almost 60 hours). From the vehroute-output, I found some vehicles departures are delayed by several hours. What's the reason? how do I solve it?
Thanks for your help.

**Comment by namdre** [comment]
see https://sumo.dlr.de/docs/Simulation/VehicleInsertion.html
The most likely cause for delayed insertion is jamming https://sumo.dlr.de/docs/FAQ.html#the_simulation_has_lots_of_jamsdeadlocks_what_can_i_do

**Comment by yuameier111** [comment]
> see https://sumo.dlr.de/docs/Simulation/VehicleInsertion.html The most likely cause for delayed insertion is jamming https://sumo.dlr.de/docs/FAQ.html#the_simulation_has_lots_of_jamsdeadlocks_what_can_i_do

ok,thank you. I‘ve figured out it's because of too many vehicle, I wanna know if it is possiblea  to adjust the threshold for insertion jam?

**Comment by namdre** [comment]
There is no threshold. If the road is full, its full. The insertion capacity depends on many things and you can read about at https://sumo.dlr.de/docs/Simulation/RoadCapacity.html
