### ISSUE TITLE
How to quickly find out the electric vehicle whose SoC is below its charging threshold

### ISSUE THREAD

**Issue by tranvary** [eclipse/sumo#13432]
Hi,I have some questions about controlling EV through TRACI:
1.I manage to get the SoC (state of charge) of EVs by calculating actualBatteryCapacity/maximumBatteryCapacity.Is there a more convenient way to get SoC?
2.It seems SUMO dosen't provide charging threshold attribute for EVs.If I  want to find out the EV whose SoC is below its predefined charging threshold,what should I do? I am not sure whether calculating SoC of EVs and comparing with their charing threshold at each time step is the only way to achieve this.

**Comment by namdre** [comment]
1. At the moment there is no better way. 
2. we are working on this: #9663
