### ISSUE TITLE
fix broken game scenarios

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#13445]
- 3D scenarios were crashing (at least in the stand-alone executable
- highway.sumocfg makes no sense
- A10KW switching doesn't work (looks like #13366 wasn't fully resolved)

**Comment by m-kro** [comment]
@namdre A10KW seems to work differently from other game scenarios as there are separate signal programs for every direction. Virtual World 3D scenario depends on models which are not included in the release.

**Comment by namdre** [comment]
Then the solution for A10 KW is to convert them to the signal plan style (sequence of green phases) as the other scenarios (and #13366 is fine).

**Comment by m-kro** [comment]
Looks like the game release does not support OSG?

**Comment by m-kro** [comment]
Scenarios have been updated. Probably the highway ramp needs some more tuning to make it fun, but at least now the scenario looks more like real-world examples (previously vehicles on the ramp would stop those already on the motorway immediately).
