### ISSUE TITLE
Can road tolls be set at the edges in SUMO？

### ISSUE THREAD

**Issue by minimi0912** [eclipse/sumo#13441]
Can road pricing be considered in path planning？

**Comment by namdre** [comment]
Yes. you can route by "effort" and this effort may be an arbitrary weighted combination of price and travel time. See https://sumo.dlr.de/docs/Simulation/Routing.html#routing_by_effort

**Comment by namdre** [comment]
duarouter doesn't use a road resistance function. Instead it relies on iterating between routing and simulation to find equilibrium:  https://sumo.dlr.de/docs/Demand/Dynamic_User_Assignment.html
A simple fix for toll-both time  would be to set a low maximum speed on the toll booth edge.

The marouter application encodes a resistance function but you cannot customize it yet (#5699)
