### ISSUE TITLE
Macro Assignment to Vehicle Flows

### ISSUE THREAD

**Issue by KEYAGO** [eclipse/sumo#13452]
Hi, so i am using MAROUTER for macro assignment and it gives me some route outputs. Can we convert it to flows automatically as .rou file so SUMO can read and run it?

![image](https://github.com/eclipse/sumo/assets/116079618/857ae004-2c6f-40d5-9adb-3f6c96fe0286)

**SUMO-version: 1.16**

**operating system: Windows 10**

**Comment by KEYAGO** [comment]
Follow-up: I couldn't find which volume-delay function sumo uses?

**Comment by namdre** [comment]
1. you can load the output file into sumo as it is.
2. see https://sumo.dlr.de/docs/marouter.html#capacity-constraint_volume-delay_function

**Comment by namdre** [comment]
see also #5699

**Comment by TrinhTuanHung2021** [comment]
> Follow-up: I couldn't find which volume-delay function sumo uses?

Hello. Did you find a way to fix this

**Comment by KEYAGO** [comment]
> > Follow-up: I couldn't find which volume-delay function sumo uses?
> 
> Hello. Did you find a way to fix this

Yes. the below link explains some. But if you want to change the basics you have to do it inside the code i guess. Otherwise sumo uses predefined parameters.

https://sumo.dlr.de/docs/marouter.html#capacity-constraint_volume-delay_function
