### ISSUE TITLE
[bug] output of getLastStepHaltingNumber() is not correct

### ISSUE THREAD

**Issue by tranvary** [eclipse/sumo#13453]
I'm using lane area detector and try to get the number of halting vehicles by traci.lanearea.getLastStepHaltingNumber.But the output result is not consistent with the truth. For example,the two cars in the following figure are waiting for charging and thus halting from 127s to 144s.However, the output of traci.lanearea.getLastStepHaltingNumber is 0 during this period.
![image](https://github.com/eclipse/sumo/assets/97677925/8e77fc2b-caac-41d7-810a-c7cfede071c1)
attached is my code:
[bug.zip](https://github.com/eclipse/sumo/files/11786533/bug.zip)

**Comment by namdre** [comment]
bug is triggered by having a full parkingArea.
