### ISSUE TITLE
SUMO Processing Configure Option - Options for Time missing? 

### ISSUE THREAD

**Issue by Chenyu3194** [eclipse/sumo#13465]
Hello,

i am trying to redefine the time step from default 1 sec to 0.1 sec, and when I opened the Processing-Options menu, I can't find any options in the field Time. However on the website of Usage Description it supposed to be at least 3 options which are begin, end, and step-length. 

The list of options on the left side looks like:
...
Visualisation
Time
Report
...

for Visualisation above and Report below there are plenty of option to adjust. Only the Time part has nothing. Did I miss something?

**SUMO-version:1.15.0**

**operating system:Windows 11**

**Comment by namdre** [comment]
prior to version 1.17.0 you are only able to configure netedit options. Defining a .sumocfg with sumo options requires 1.17.0 and you will then have a new option setting dialog.
