### ISSUE TITLE
feature request: tls.join-exclude

### ISSUE THREAD

**Issue by ambuehll** [eclipse/sumo#13466]
for a given sumo network.
similar to junctions.join-exclude.

**Comment by ambuehll** [comment]
great! thanks. Lukas

**Comment by gladysmcgan** [comment]
Thanks for implementing this option! It works well; I ran netconvert to first to group the tls signals, identified the tlss with high cycle times, then ran netconvert again to exclude the identified tlss. But there is one instance I found in the network where netconvert still groups (albeit in a smaller group than before) two of the tlss stated in the **tls.join-exclude** option. 

<img width="313" alt="Screenshot 2023-07-05 at 11 01 56 AM" src="https://github.com/eclipse/sumo/assets/59922884/234d6d78-15c2-4a3e-93cf-fec836b757ed">

It results in a normal cycle time, but I would expect that the tlss should be excluded from being grouped at all.

Nevertheless, it works for the purpose of removing high cycle time signal groups from the network :)

**Comment by namdre** [comment]
Can you provide a minimal failing example?

**Comment by gladysmcgan** [comment]
Yes, here. [google drive folder](https://drive.google.com/drive/folders/1tJ2IEBXhR_YdHkAygInOHsRmrAVvWqnK?usp=sharing) 

See junctions 441716589, 446770965 in TOR_sumo_raw2.net.xml

**Comment by gladysmcgan** [comment]
Ah I see, thanks for pointing that out!
