### ISSUE TITLE
polyconvert changes the coordinates

### ISSUE THREAD

**Issue by Y-Yahyaoui** [eclipse/sumo#13475]
I'm trying to convert a shapefile to polygons using polyconvert and I put in the inputs my network file that is in the UTM zone 19 projection, however the polygon result has mixed up coordinates.

here's my network boundary : 

`<location netOffset="0.00,0.00" convBoundary="310529.64,5177544.33,332725.97,5191961.90" origBoundary="-71.480723,46.710552,-71.193503,46.859138" projParameter="+proj=utm +zone=19 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"/>
`

and here's the polygons result :

`<location netOffset="0.00,0.00" convBoundary="310529.64,-10963268.47,2440671.61,5191961.90" origBoundary="-71.480723,-71.804812,47.093642,46.859138" projParameter="+proj=utm +zone=19 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"/>
`

it switches the min lat with the max lon, and all the polygons are messed up.

here's the command that I'm running :

`polyconvert --osm-files map.osm --shapefile-prefixes zones --shapefile.id-column id`

**Comment by namdre** [comment]
set polyconvert option **----shapefile.traditional-axis-mapping** (the GDAL devs changed the default axis order some time ago).
