### ISSUE TITLE
TAZ from shapefile

### ISSUE THREAD

**Issue by Y-Yahyaoui** [eclipse/sumo#13474]
Hello, I have a shapefile of polygones with ids and a csv file of origin destination data from the zones in the shapefile.

Is there a way to create the TAZs file from the shp.

**Comment by namdre** [comment]
1. import shapefile into sumo poly xml: https://sumo.dlr.de/docs/polyconvert.html
2. https://sumo.dlr.de/docs/Tools/District.html#edgesindistrictspy
