### ISSUE TITLE
Don't use deprecated distutils module.

### ISSUE THREAD

**Issue by sebastic** [eclipse/sumo#13485]
`tools/game/setup.py` still uses the deprecated distutils module which will be removed in Python 3.12.

From [What’s New In Python 3.10](https://docs.python.org/3/whatsnew/3.10.html#distutils-deprecated):
> The entire `distutils` package is deprecated, to be removed in Python 3.12. Its functionality for specifying package builds has already been completely replaced by third-party packages `setuptools` and `packaging`, and most other commonly used APIs are available elsewhere in the standard library (such as [platform](https://docs.python.org/3/library/platform.html#module-platform), [shutil](https://docs.python.org/3/library/shutil.html#module-shutil), [subprocess](https://docs.python.org/3/library/subprocess.html#module-subprocess) or [sysconfig](https://docs.python.org/3/library/sysconfig.html#module-sysconfig)). There are no plans to migrate any other functionality from distutils, and applications that are using other functions should plan to make private copies of the code. Refer to [PEP 632](https://peps.python.org/pep-0632/) for discussion.

[Porting from Distutils](https://setuptools.pypa.io/en/latest/deprecated/distutils-legacy.html#prefer-setuptools) suggests using `setuptools` instead of `distutils.core`.

This patch resolves the issue:
```diff
Description: Don't use deprecated distuils module.
 https://setuptools.pypa.io/en/latest/deprecated/distutils-legacy.html#prefer-setuptools
Author: Bas Couwenberg <sebastic@debian.org>

--- a/tools/game/setup.py
+++ b/tools/game/setup.py
@@ -18,7 +18,6 @@

 from __future__ import absolute_import

-from distutils.core import setup
 # import is needed to make the module known
 import py2exe  # noqa
 import sys
@@ -29,6 +28,8 @@ import zipfile
 import subprocess
 import tempfile

+from setuptools import setup
+
 for d in ["Program Files", "Program Files (x86)", "Programme"]:
     sevenZip = r'C:\%s\7-Zip\7z.exe' % d
     if os.path.exists(sevenZip):
```

**SUMO-version:** 1.17.0

**Operating System:** Debian GNU/Linux unstable

**Comment by m-kro** [comment]
[py2exe ](https://github.com/py2exe/py2exe/blob/master/docs/migration.md)changes things:
```
# setup(console=...) # old
freeze(console=...)
```

**Comment by sebastic** [comment]
This might suffice then:
```diff
--- a/tools/game/setup.py
+++ b/tools/game/setup.py
@@ -18,9 +18,6 @@
 
 from __future__ import absolute_import
 
-from distutils.core import setup
-# import is needed to make the module known
-import py2exe  # noqa
 import sys
 import shutil
 import os
@@ -29,6 +26,9 @@ import zipfile
 import subprocess
 import tempfile
 
+from py2exe import freeze
+
+
 for d in ["Program Files", "Program Files (x86)", "Programme"]:
     sevenZip = r'C:\%s\7-Zip\7z.exe' % d
     if os.path.exists(sevenZip):
@@ -50,7 +50,7 @@ subprocess.call(['git', 'archive', 'HEAD', '-o', zipfName] + files)
 tmpDir = tempfile.mkdtemp()
 os.chdir(tmpDir)
 os.mkdir("dist")
-setup(console=[os.path.join(base, 'runner.py')])
+freeze(console=[os.path.join(base, 'runner.py')])
 # collect sumo binaries and dlls
 osgPlugins = None
 with zipfile.ZipFile(inZip) as binZip:
```

**Comment by m-kro** [comment]
Yes I already tried that before posting. Still having issues though (missing modules etc.). I have to check a bit further whether changing freeze parameters helps.

**Comment by m-kro** [comment]
@behrisch Do you have experience with py2exe freeze?

**Comment by behrisch** [comment]
we don't use py2exe anymore to build the binary game release. We currently use pyinstaller. So probably the setup.py can be removed
