### ISSUE TITLE
replay state problem

### ISSUE THREAD

**Issue by MJLee00** [eclipse/sumo#13487]
I want to play back the previously saved state and have it be the same after the traci.simulation.step() method is executed, how can I do that?
For example, I have saved state_01.xml to state_10.xml, and after loading state_01.xml and executing traci.simulation.step() method 9 times, I get the same result as state_10.xml.
It seems that traci.simulation.step() has some randomness, how do I preserve this randomness？
Vehicle speed or acceleration information will only change if the traffic light changes
**SUMO-version:**  sumo 1.17.0

**operating system:**  ubuntu

**Comment by namdre** [comment]
https://sumo.dlr.de/docs/Simulation/SaveAndLoad.html#random_number_generators_rng

**Comment by MJLee00** [comment]
It looks like you can only use the command line. Is there a traci package can i use?

**Comment by MJLee00** [comment]
![1687541933732](https://github.com/eclipse/sumo/assets/23303649/755c1e39-44de-4e0d-a2bb-9e6cfd3eb057)
I recorded this state a second before the vehicle collision when getCollisionNumber=2, and when I reload, getCollisionNumber=0, and execute the next step, getCollisionNumber=0 but traci.simulation.getCollisions( ) is 2, is this a bug？

**Comment by namdre** [comment]
Could be a bug. Can you provide the simulation and commands that caused the state to be written?
Instead of the whole traci and surrounding scripts, please record a trace file of  the traci commands: https://sumo.dlr.de/docs/TraCI/Interfacing_TraCI_from_Python.html#generating_a_log_of_all_traci_commands
