### ISSUE TITLE
How to get fuel comsumption of vehicle after set Speed 

### ISSUE THREAD

**Issue by Chaiendxdx** [eclipse/sumo#13495]
I set the vehicle speed using traci library and want to get the vehicle's fuel consumption after setting that speed. But when using the getFuelComsumption function, only the amount of fuel is obtained before setting speed. So how do I get the data I need?

**Comment by namdre** [comment]
1. vehicle.setSpeed
2. traci.executeMove  (requires version 1.17.0)
3. vehicle.getFuelConsumption
4. traci.simulationStep

**Comment by Chaiendxdx** [comment]
sorry, but I don't quite understand. Can you give more specific instructions?

**Comment by namdre** [comment]
if you execute the first 3 commands, then you will get the fuel consumption for the speed that you set in the current step. Afterwards you still have toll call simulationStep (as usual) to advance to the next step.
