### ISSUE TITLE
About loading additional output files failed.

### ISSUE THREAD

**Issue by Clown1206** [eclipse/sumo#13497]
Add your issue description here.
  Hello, When I open my.sumocfg file using suo-GUI, Error is displayed: Could not build output file  'D:\experiments\pythonCode\my_routing\map\6x5\additional/e2DetectorP3_output\e2DetectorD5C5_1.xml' (Too many open  files).
Both e1 and e1 detectors are included in my road network.
*If possible, upload an example that shows your problem.*

**SUMO-version:**
1.16
**operating system:**
win10

**Comment by namdre** [comment]
in case you have very many detectors, let the write to the same file (their output will be distinguished by id) to avoid opening a new file for every detector and running into limitations of your operating system.
