### ISSUE TITLE
windows build failed in vs2019  x64-release mode

### ISSUE THREAD

**Issue by 1952890** [eclipse/sumo#13518]
**windows 10:**

during the build process , errors occured.
![a143704add27fab20c10f2d4736cafa](https://github.com/eclipse/sumo/assets/110601017/e819257e-202f-4585-bdd3-2ad8b32856be)

**Comment by 1952890** [comment]
did the problem occur due to libtraci or libsumo

**Comment by palvarezlopez** [comment]
@1952890 in CMake-gui, disable "Enable python binding"

**Comment by 1952890** [comment]
![image](https://github.com/eclipse/sumo/assets/110601017/108cccae-af61-4c8d-b58a-f7da84594942)
in cmake-gui disable "enable python binding" is done， shown in picture above
but same error still occured
![image](https://github.com/eclipse/sumo/assets/110601017/eaa34831-6df3-464e-ae4b-a168e8b99b4f)

**Comment by 1952890** [comment]
solved by updating to new versions ，thanks for your help
