### ISSUE TITLE
SetStop function is not working when i have the setspeed function to set the speed of vehicle for some constant value 

### ISSUE THREAD

**Issue by Swayam069** [eclipse/sumo#13526]
I am working this with only one vehicle in the simulation, the vehicle stops on some given point for some given duration of time is the setspeed function is not bought up in the code, but if the setspeed function is in the code to set the speed of the vehicle say 1m/s the setstop function dont actually work.
Please help me with this problem.
-swayam

[code.txt](https://github.com/eclipse/sumo/files/11915048/code.txt)

**Comment by m-kro** [comment]
The speed you set calling `traci.vehicle.setSpeed` is active until you either set a different speed or give the control back to SUMO calling it with speed value -1. For this reason the stop cannot be made.
