### ISSUE TITLE
routeSampler.py: bias/pattern in generated depart times

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#13523]
when generating traffic for a particular data interval:
- when generating individual vehicles or flows with number, the first vehicle always departs at the start of the interval
- a list of fixed, departure times (within an raster of times) is assigned to every route, if a route occurs only once per interval, even poisson flow setting doesn't shift it. -> this algorithm is pretty weird 

The problem is especially noticeable when there are many intervalls with only a few vehicles.

**Comment by namdre** [comment]
There will always be some bias when using flow=period or flow=number. This is because any algorithm that picks endpoints in an interval and then evenly spaces departures between these points is going to bias the middle of the interval.  A related example is picking random points on a circle by picking points on the circumference and then picking at random from the connecting line. This will also bias the center over the border.   

However, the bias is fixable for
- individual vehicles (obviously)
- flow=poisson
- flow=random

**Comment by mschrader15** [comment]
Thanks @namdre!
