### ISSUE TITLE
traceExport.py kepler-JSON generates raw timestamps from SUMO simulations (not epoch)

### ISSUE THREAD

**Issue by aminissn** [eclipse/sumo#13522]
in version 1.17, using traceExport.py doesn't generate correct timestamps for visualizations in Kepler-JSON format.
fcd2keplerjson in tools/output/convert needs to be modified to read the option 'base-date' passed through traceExport.py

**Comment by aminissn** [comment]
I wasn't again really sure why the options are set to ignore currently, otherwise, I would have made a pull request. 
here is the fix (in my opinion):
def fcd2keplerjson(inpFCD, outStream, further):
    tracks = defaultdict(list)
    for timestep in inpFCD:
        for v in timestep.vehicle:
            tracks[v.id].append([v.x, v.y, v.z, timestep.time+further['base-date'].timestamp()])
    jsonRoot = {
        "type": "FeatureCollection",
        "features": [makeFeature(*veh) for veh in tracks.items()]
    }
    json.dump(jsonRoot, outStream)

**Comment by namdre** [comment]
Thanks!
