### ISSUE TITLE
tls.guess-signals does not work in consecutive intersections

### ISSUE THREAD

**Issue by gladysmcgan** [eclipse/sumo#13536]
In my network, the option appears to shift the traffic light from upstream nodes to the intersection in some cases and not in others. I noticed this in a series of consecutive intersections, where some intersections became TLS controlled and other TLS remained on the upstream node. 

Is there a minimum number of incoming edges required for option to work? Or perhaps a minimum number of nodes in an incoming edge?

<img width="347" alt="Screenshot 2023-07-03 at 12 09 33 PM" src="https://github.com/eclipse/sumo/assets/59922884/fcf6242b-034d-470a-9249-588aaa5ecdc2">

I also set the slack option to 3, but the problem remained.

The network and sumoconfig files are here: [google drive folder](https://drive.google.com/drive/folders/1r6DiFHbV54WrSZPh9BYk2H2AeVaakuO_?usp=sharing)

Examples: junction:435668531, junction:446770967, junction:250685721

SUMO version 1.17

**Comment by namdre** [comment]
- signals are only identified as such when they are not on a "real" intersection. Therefore the norther and southern lights don't count for the central junction (but the east and west lights count)
- on top of the condition that the number of missing signals is no higher than the slack option, there is another requirement that the number of correct signals is larger than the number of missing signals. This condition is violated in your example (2 correct and 2 missing).

**Comment by namdre** [comment]
The cluster of junctions might be better modeled by being joined into a single junction.  It goes beyond what the **--tls.guess-signals** heuristic is supposed to handle.

**Comment by gladysmcgan** [comment]
I see, thank you!
