### ISSUE TITLE
Different Vtypes pararameters definitions for each intersection in simulation

### ISSUE THREAD

**Issue by lola-notraffic** [eclipse/sumo#13538]
Hello,
I have vtypes.xml file of my model where I define parameters like "accel" and "tau" like this:
<vType id="passenger" jmTimegapMinor="0" accel="2.9" decel="7.5" emergencyDecel="9" tau="1.2" sigma="0.5" length="4.3" width="1.8" height="1.5" minGap="2.5" maxSpeed="50" guiShape="passenger"/>

If i have 12 intersections in simulation: in each intersection these parameters will be the same.
How can I define these parameters to be different for each intersection? 
For example:
In intersection 1 tau value will be lower than other intersections,  because it is busy intersection and vehicles behave more aggressive and less hesitant.

Thank you in advance!

**SUMO-version: 1.13.0**

**operating system: ubuntu 20.04**

**Comment by namdre** [comment]
you can either change the types / their attributes via TraCI or with a type-calibrator: https://sumo.dlr.de/docs/Simulation/Calibrator.html#calibrating_vehicle_types
