### ISSUE TITLE
send a message to a vehicle by using omnet++ and sumo

### ISSUE THREAD

**Issue by Y-AMDIAZ** [eclipse/sumo#13548]
I would like to use SUMO and OMNeT++ to send a message to a vehicle using the VEINS framework. For example, I want to change the route or direct a vehicle to a specific destination by using a Roadside Unit (RSU). Can someone provide me with instructions on how to do this or suggest where I can start? I would appreciate an example or any guidance. 
Thank you

**Comment by m-kro** [comment]
Veins uses its own TraCI interface to communicate with SUMO (to actually make vehicles react). There is nothing Veins-specific to do on the SUMO side - you just build your scenario (net, routes, traffic demand etc.). Please look at the [Veins resources](https://veins.car2x.org/documentation/) and consider the [Veins question on StackOverflow](https://stackoverflow.com/questions/tagged/veins). 
We cannot help you more regarding Veins, please consider asking their team if you have further questions.
