### ISSUE TITLE
question about plain-xml in geo-coordinates

### ISSUE THREAD

**Issue by yuameier111** [eclipse/sumo#13544]
hi,
I used netconvert to obtain the plain-xml in geo-coordinates, but I found some edges missing in QGIS, and some edges lost their shape fields. What's the reason and how can I solve it?
thanks.
![微信图片_20230704145654](https://github.com/eclipse/sumo/assets/136823316/57b70b9d-d8e2-42c1-940e-8e536753c3a7)
![微信图片_20230704145854](https://github.com/eclipse/sumo/assets/136823316/c22cdd00-19b6-4f40-82c1-4e04110b0b55)

**Comment by namdre** [comment]
- no shape field is written for straight edges (geometry is implicit from the node coordinates)
- the offset between edge geometries in the first screenshot is there to inform the computation of junction geometries. The gaps are filled by so called "internal" edges but these are not part of plain-output
- if you want to load the network into QGIS, see https://sumo.dlr.de/docs/Tools/Net.html#net2geojsonpy

**Comment by yuameier111** [comment]
> * no shape field is written for straight edges (geometry is implicit from the node coordinates)
> * the offset between edge geometries in the first screenshot is there to inform the computation of junction geometries. The gaps are filled by so called "internal" edges but these are not part of plain-output
> * if you want to load the network into QGIS, see https://sumo.dlr.de/docs/Tools/Net.html#net2geojsonpy

thank you, I  use net2gojson.py and --internal command ,but there still exsit some edges  not connected. how can I solve it? 
![Uploading 微信图片_20230704165300.png…]()

**Comment by namdre** [comment]
the problem here is that 'edge' is only a guideline to compute lane shapes which are then connected. You could set option --lanes but this would give you more than one line per edge.  
The only workaround I can think of is to modify the network so that every edge has exactly one lane and then use option --lanes.
