### ISSUE TITLE
deadlock on junction when approaching occupied bidiEdge at traffic light

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#13541]
The connection from the major street should get the major green even if it is a left turn vs  a right turn. See corresponding test

**Comment by namdre** [comment]
on further consideration, the problem occurs while the main road has the red light. It probably must be solved inside the simulation (i.e. with something like `checkRewindLinkLanes`)

**Comment by namdre** [comment]
remaining deadlocks in the original (large) scenario are due to choice of bestLane and must be solved via #13402
