### ISSUE TITLE
cmd jump problem when SUMO source code calls python program

### ISSUE THREAD

**Issue by Alexsv2** [eclipse/sumo#13554]
When the python program is called by using the sumo source code, the python program contains the Traci statement. When the python program is called in the GUI interface of the source code, the cmd interface will be jumped to generate a new Gui interface for simulation. How to make the simulation simulate in the original GUI interface without jumping cmd and generating new process.

**Comment by Alexsv2** [comment]
Whether a python traci-controlled simulation can display the simulation process under an existing sumo-gui interface

**Comment by namdre** [comment]
after the initial call to `traci.start` you can call `traci.load` to reload the simulation with new options (instead of starting a new instance).

**Comment by 1952890** [comment]
Can traci.load reload a brand new sumocfg , and then the sumo-gui may show the new net and new simulation process ?

**Comment by namdre** [comment]
yes
