### ISSUE TITLE
problem with --save-configuration option for sumo in windows

### ISSUE THREAD

**Issue by RahelehSh** [eclipse/sumo#13557]
Hello,

I am working on Traci interacting with Python, and every thing was OK; but when add --save-configuration option to sumoCmd, i ran into the Problem with following error:

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\traci\main.py:154: UserWarning: Could not connect to TraCI server using port 60042 (TraCI server already finished). Retrying with different port.
  warnings.warn(("Could not connect to TraCI server using port %s (%s)." +
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\traci\main.py:154: UserWarning: Could not connect to TraCI server using port 60044 (TraCI server already finished). Retrying with different port.
  warnings.warn(("Could not connect to TraCI server using port %s (%s)." +

Thanks in advance for possible solutions!

**SUMO-version:**
Eclipse SUMO sumo Version 1.18.0

**operating system:**
windows 10

**Comment by m-kro** [comment]
SUMO ends after saving the configuration. You have to do a separate call for running the simulation with TraCI.
