### ISSUE TITLE
PermissionError: [WinError 5] Access is denied

### ISSUE THREAD

**Issue by Chenyu3194** [eclipse/sumo#13555]
Hello,

I am working on Traci interacting with Python, and ran into the Problem with following error:

 File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
PermissionError: [WinError 5] access is denied。
PS D:\Softwares\SUMO Simulation\MA>

I run the MS VS code as administer and set all the environmental variables as the tutorial told but still doesnt work.

Thanks in advance for possible solutions!

**1.17.0**

**Windows 11:**

**Comment by m-kro** [comment]
Well this seems to be some user rights problem related to you system configuration. Could you try a separate Python installation (following the [instructions ](https://docs.python.org/3/using/windows.html)on python.org)?

**Comment by Chenyu3194** [comment]
> Well this seems to be some user rights problem related to you system configuration. Could you try a separate Python installation (following the [instructions ](https://docs.python.org/3/using/windows.html)on python.org)?

I will try this out and see if it was the user administraion problem.  Thanks for the reply!
