### ISSUE TITLE
traci.start() leads to sumo-gui crash when click close button of the gui window

### ISSUE THREAD

**Issue by 1952890** [eclipse/sumo#13578]
traci.start() leads to sumo-gui crash when click close button of the gui window
*If possible, upload an example that shows your problem.*

traci.start(cmd);
while True:
    print("after load")

if click close button during the loop, gui crashes.

**SUMO-version: 1.18**

**operating system: windows**

**Comment by m-kro** [comment]
Is this your actual script code? Then you have an infinite loop as the while condition will remain true forever and will output as many print statements it can. This will consume a lot of your computer resources and may make the GUI not respond.

**Comment by 1952890** [comment]
well, After some test, i found that during the simulation controlled by traci , clicking the close buttton of the gui may lead to crash. if the simulation has ended or has not started yet, the close button works as usual.

**Comment by m-kro** [comment]
This is expected behaviour. The GUI is an integral part of the simulation and closing it will make the connected TraCI client fail.
