### ISSUE TITLE
allow me to arrive more quickly to my destination 

### ISSUE THREAD

**Issue by Y-AMDIAZ** [eclipse/sumo#13577]
I use trips to reach my destination, and I have three different routes to choose from. However, when I provide the trip details from the source to the destination, the system often selects the slower route, even though there are two alternative routes that would allow me to arrive more quickly
<img width="1037" alt="image" src="https://github.com/eclipse/sumo/assets/129278941/73e3a403-426e-42af-838e-6c3ef8452ff2">

**Comment by namdre** [comment]
the route shown within netedit for a trip is only tentative. The vehicle may take a different route in the situation (in particular when reacting to existing traffic)

If you feel that vehicles are not taking a sensible path in the simulation, please provide an example scenario.

**Comment by Y-AMDIAZ** [comment]
So, you want me to create a different scenario okey

**Comment by namdre** [comment]
If you are still working with the scenario from #13379  then 
trip t_2 starts too early to "see" the jam. If you let it start at time 100 then it will avoid the jam.
