### ISSUE TITLE
"--start" won't work with traci.start()

### ISSUE THREAD

**Issue by Chenyu3194** [eclipse/sumo#13579]
Hi,

I built a scenario with network and demand elements and I'm tring to call the simulation through Traci in Python. It works but the simulation always need a manual start by clicking the button, and I tried the "--start" command from the SUMO startup webpage, and it shows error. Wondering how to solve this. Thx in advance. here is part of the codes

*# Function to start the SUMO simulation
def run_simulation():
    # Start the SUMO simulation
    traci.start([sumoCmd, "--start"])
    # Run the simulation steps
    while traci.simulation.getMinExpectedNumber() > 0:
        traci.simulationStep()

    # Stop the SUMO simulation
    traci.close()

# Call the function to start the simulation
run_simulation()*

**SUMO-version:1.18.0**

**operating system:Windows 11**

**Comment by Chenyu3194** [comment]
> What is the error exactly? What is the value of `sumoCmd` ?

sumoCmd contains the path to sumo-gui and the sumocfg data as follow:

sumoCmd = [sumoBinary, "-c", "Neustadtring2.sumocfg"]

and the error appears to be:

  File "C:\Program Files (x86)\Eclipse\Sumo\tools\traci\main.py", line 145, in start
    sumoProcess = subprocess.Popen(cmd2, stdout=stdout)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python311\Lib\subprocess.py", line 1462, in _execute_child
    args = list2cmdline(args)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\subprocess.py", line 608, in list2cmdline
    for arg in map(os.fsdecode, seq):
  File "<frozen os>", line 824, in fsdecode
TypeError: expected str, bytes or os.PathLike object, not list

**Comment by m-kro** [comment]
You have created a nested list. Change it to:
```
traci.start(sumoCmd + ["--start"])
```

**Comment by Chenyu3194** [comment]
> traci.start(sumoCmd + ["--start"])

It works perfectly now, thank you for the solution!
