### ISSUE TITLE
CO2 emission information in SUMO 

### ISSUE THREAD

**Issue by Y-AMDIAZ** [eclipse/sumo#13574]
Hi, I would like to calculate the CO2 emissions  . How can I do it using SUMO? Where can I find the CO2 emission information in SUMO, and how can I use it in Netedit or in the rou.XML file?

**Comment by m-kro** [comment]
See the [overview](https://sumo.dlr.de/docs/Models/Emissions.html) on emissions in the documentation and options how to process them. You define the `emissionClass` attribute of your vehicle (type) and activate [TripInfo ](https://sumo.dlr.de/docs/Simulation/Output/TripInfo.html) output to get the amount of CO2 for each trip.
