### ISSUE TITLE
Problem with routeSampler. py 

### ISSUE THREAD

**Issue by zhangm269** [eclipse/sumo#13590]
I used the randomtrip command to generate a bicycle route file named bicycle. rou. xml. In this rou file, I defined a vtype named bicycle_ bicycle, as shown in the following figure
![image](https://github.com/eclipse/sumo/assets/50513332/58cc45f5-d844-48ee-9707-e29883a4f404)

When I used the command Python tools/routeSampler. py - r<input route file>-- turn files<turn files>- o<output file>, I found that the generated route file lacked the definition of vtype in the original file. Is there a corresponding solution besides copying the definition over? Thanks for your reply!
![image](https://github.com/eclipse/sumo/assets/50513332/d495d221-3a62-46ed-8d36-aae59a1c9981)

**SUMO-version:**
1.17.0
**operating system:**
Windows

**Comment by m-kro** [comment]
Consider separating the vehicle types in a separate file like explained in the [randomTrips docs](https://sumo.dlr.de/docs/Tools/Trip.html#setting_a_vehicle_type_from_an_external_file). Then you can reuse/load this vType additional file everywhere you need it.

**Comment by zhangm269** [comment]
Okay, I understand. Thank you for your reply.
