### ISSUE TITLE
charging station

### ISSUE THREAD

**Issue by wy12184163** [eclipse/sumo#13599]
I desired to know if the vehicles must stop when them are in the charging station，Through the output file of the charging station, I found that when the vehicle did not stop, the vehicle could not be charged。

**SUMO-version:**1.17

**Comment by m-kro** [comment]
You have to set the charging station attribute **chargeInTransit="true"** (see [doc](https://sumo.dlr.de/docs/Models/Electric.html#charging_stations)) to allow charging while still moving. As the default value is **chargeInTransit="false"** you didn't experience that.
