### ISSUE TITLE
Regarding the issue of parameter randomness.

### ISSUE THREAD

**Issue by adoreador** [eclipse/sumo#13602]
Hi mates! I encountered some issues while creating traffic flow. I am using `vehsPerHour` to generate the traffic flow, and I would like the generated vehicle models to have some randomness in their parameters. I noticed that someone had raised a similar question before.

`<vType id="P" vClass="passenger" delta="norm(3.5238,3.6240)" carFollowModel="IDM" speedFactor="normc(1,0.1,0.2,2)"/>`

I also want the parameters to be generated from a normal distribution, so I'm trying to solve this problem with the following code:

`<vType id="type1"  carFollowModel="W99" color="1,1,0" />`
       `    <param key="cc1" value="norm(1.4991,0.4813)"/>`

I have found that this approach works, so I would like to know if this means that I can proceed with such an operation. In other words, does it already possess the parameter randomness effect that I expect?
I would greatly appreciate it if you could clarify my doubts.

**Comment by m-kro** [comment]
Actually the current way to get some randomness is to prepare a [distribution of vehicle types ](https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#vehicle_type_distributions) and let SUMO draw the next vehicle type out of it. The only point where the special "norm[...]" syntax is valid is the speedFactor attribute. Your vType "P" should raise an error during XMl validation. The param is fine but will have no effect as you just assign a key-value pair of text to the vehicle type.

**Comment by namdre** [comment]
since vehsPerHour creates an equi-distance spacing in vehicle insertion, consider using a Poisson flow instead: https://sumo.dlr.de/docs/Simulation/Randomness.html#poisson_distribution

**Comment by adoreador** [comment]
Thank you for your response, but I still have some confusion. CC1 is a parameter in the W99 car-following model, and I would like the generated vehicle to have random values for the parameters of the car-following model. Is it not possible to assign a value to CC1 through the step "param key="cc1" value="norm(1.4991,0.4813)"?

**Comment by adoreador** [comment]
Certainly, I understand. Thank you for your patient explanation.
