### ISSUE TITLE
Vehicle position jumps back during lane change

### ISSUE THREAD

**Issue by mpfist-no** [eclipse/sumo#13601]
With the provided Sumo network, the vehicle 3D position jumps back on the target lane when changing the lane. The lane change movement is smooth until the neighboring lane is reached. Then, the vehicle is set back approximately a meter on the new lane.

Please see the attached example [car-jump-on-lanechange.zip](https://github.com/eclipse/sumo/files/12012631/car-jump-on-lanechange.zip), containing the network, the sumo config and the python script that triggers the lane change and plots the position.

The XY position is plotted here: 
![vehicle-position-plot](https://github.com/eclipse/sumo/assets/94060139/872ce097-3d66-436d-aeac-8206a178d2b5)

**SUMO-version:** 1.18

**Operating system:** Windows 10

**Comment by m-kro** [comment]
Looks similar to #11719 to me: There is the inherent problem of the current system architecture that curved lanes can be longer or shorter than the reference line of the edge, to which the position attribute of the vehicle relates to.
