### ISSUE TITLE
Discrepancy between nVehContrib of e1 detector and nVehLeft of e2 detector.

### ISSUE THREAD

**Issue by JamesPsh** [eclipse/sumo#13607]
Hello,

I've encountered an issue while using the e1 and e2 detectors.

Here's the setup:
1. Installed the e1 detector at the end of the lane.
2. Placed the e2 detector covering the entire lane.

I was expecting the values of `nVehContrib` from e1 and `nVehLeft` from e2 to be closely aligned, as they both should theoretically reflect the same situation. However, there is a substantial difference when I look at the simulation results.

Based on the description given in the nVehLeft of e2 documentation, i.e., "vehicle back has passed 'endPos'", I initially assumed these two values would match closely. I am wondering if I might be misunderstanding something here?

If it would help to look at my data, I am more than willing to provide sample data.

Any guidance on this issue would be greatly appreciated.

Thank you.

**Comment by m-kro** [comment]
Please share your example / data.

**Comment by JamesPsh** [comment]
I am providing an example data set here.

The detector is defined in `detector.add.xml`.
The results for e1 and e2 are stored in `e1_out.xml` and `e2_out.xml`, respectively.

I believe that the `nVehContrib` in `e1_out.xml` and the `nVehLeft` in `e2_out.xml` should match, but the results appear to be different.

In my opinion, the number of lane changes without the vehicle passing the endpos of e2 also counts.
[sample.zip](https://github.com/eclipse/sumo/files/12027211/sample.zip)

**Comment by m-kro** [comment]
I updated the documentation to mention lane changes and other reasons for leaving the detector explicitly. What do you actually want to achieve with the detectors that they have to lead to the same numbers?

**Comment by JamesPsh** [comment]
Thank you for your response, @m-kro.

My main objective is to obtain the number of vehicles passing the stop line.
I thought I could achieve this by using either `nVehContrib` or `nVehLeft`.

However, based on the discrepancies I've observed in the simulation results,
I've concluded that `nVehContrib` would be the more appropriate measure for my purpose.
I appreciate your help and the updates to the documentation.
They have been very helpful in understanding the functionality of the detectors.

Also, if there's a better or more accurate way to measure the number of vehicles passing the stop line,
I would be very interested to know. Your expertise and guidance are greatly appreciated.

Thank you.

**Comment by m-kro** [comment]
If it is only about the vehicles passing the stop line, then reducing the detector length would already help (such that lane changes far upstream are not captured). Anyhow it might be an idea to distinguish between different ways of leaving the detector in the output.

**Comment by JamesPsh** [comment]
Thank you for your answer.
