### ISSUE TITLE
Fundamental Diagram

### ISSUE THREAD

**Issue by adoreador** [eclipse/sumo#13612]
Hello! I have a few questions about the basic graph. I have set up two different types of vehicles and measured the "edgedata" of a segment of the road network to create a basic graph. However, some issues have arisen. To be honest, even after carefully reading the documentation and studying the examples, I still don't know how to resolve them. Could you please provide me with some answers?
![Figure_1](https://github.com/eclipse/sumo/assets/139220434/8d2e935b-342b-4b64-a882-d5cda7319b80)

Additionally, I have a  questions. I've noticed that "edgedata" has additional outputs, such as "Traffic volume at the beginning of the lane/edge (#/h)". I would like to know how I can generate this data during the simulation process. Is it possible to obtain this information directly during the simulation, or do I need to process the "edgedata" afterwards to obtain such data?

I sincerely appreciate your guidance in advance, considering my limited technical knowledge.

**Comment by m-kro** [comment]
> However, some issues have arisen

Which exactly? Your plotted values are quite big if originating from a single lane. Consider plotting the lane density instead. Then it depends on your SUMO scenario if / how much traffic breakdown can be observed.
You can color the edges by the "live edgeData" scheme to get a direct visual feedback during the simulation.

**Comment by adoreador** [comment]
I apologize for not responding in a timely manner.  I took the initiative to educate myself on the subject and was able to resolve the issue.  Thank you for your patience and guidance!
