### ISSUE TITLE
How to add a new custom car following model in SUMO

### ISSUE THREAD

**Issue by 1564406576** [eclipse/sumo#13614]
Firstly, my research project requires a new car following model. I have already created it in Python, but it cannot be imported into SUMO in any case. How should I solve this problem? Secondly, where are the source files of your SUMO's 17 car following models located.

**SUMO-version:**1.18

**operating system:**windows

**Comment by m-kro** [comment]
You can overwrite vehicle dynamics using TraCI (e.g. [traci.vehicle.setSpeed](https://sumo.dlr.de/pydoc/traci._vehicle.html#VehicleDomain-setSpeed) / [traci.vehicle.setAcceleration](https://sumo.dlr.de/pydoc/traci._vehicle.html#VehicleDomain-setAccel) / [traci.vehicle.moveToXY](https://sumo.dlr.de/pydoc/traci._vehicle.html#VehicleDomain-moveTo)). 

For the integrated car-following models, see the respective [doc page](https://sumo.dlr.de/docs/Developer/How_To/Car-Following_Model.html).
