### ISSUE TITLE
traffic flow network design issue

### ISSUE THREAD

**Issue by zapcity** [eclipse/sumo#13617]
I'm trying to design the network for an on-ramp, but I'm having problems setting it up correctly. 

How do I set things up so that
1. the mainline traffic is not hindered by a traffic light system, and 
2. the on-ramp flow initially uses the right most lane on the mainline i.e. L0, and then slowly merges into L1 on the mainline  
as shown by the yellow arrows in the diagram below:

![image](https://github.com/eclipse/sumo/assets/37337474/32f94149-58c1-40f9-82c6-2f39c4929ff1)

The best I can do is set up a traffic light control at the junction, and configure the mainline traffic to always be in green phase. However setting this up creates two crossover connections which are problematic, which I want to get rid of i.e.:
1. on-ramp flow into L1 and 
2. mainline flow into L0.

The way the simulation runs at the moment is that on-ramp traffic immediately flows into L1 at the junction, cutting off mainline traffic flowing into L1.

I'd also like to have mainline traffic on L1 to slow down to allow on-ramp traffic on L0 to eventually merge into L1 before L0 ends.

Is there any way around this?

**Comment by m-kro** [comment]
Two separate things:

- building an on-ramp see [docs](https://sumo.dlr.de/docs/Simulation/Motorways.html): acceleration lane (L0) ends as dead-end, every vehicle changes lanes to get on the motorway (no explicit connections)
- configure the [lane change model](https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#lane-changing_models) for more cooperative behaviour (lcCooperative)

**Comment by m-kro** [comment]
You can add another node a bit upstream on the ramp access and add a traffic light to it.

**Comment by zapcity** [comment]
Thanks so much for that. Just getting use to the software as I've never used it before.
