### ISSUE TITLE
I would like to set different initial battery charge levels for electric vehicles. I want to achieve a randomized effect where each vehicle has a unique starting charge. How can I accomplish this?

### ISSUE THREAD

**Issue by wy12184163** [eclipse/sumo#13615]
I gave each car a different starting power value, but found that their starting power value was always the same default MaxBatKap/2

*If possible, upload an example that shows your problem.*

    <vehicle id="0" type="type1" depart="0" color="1,0,0">
        <param key="actualBatteryCapacity" value="500"/>
    </vehicle>

I used the code above to define the initial power values for different vehicles

**SUMO-version:**1.16

**operating system:**Windows

**Comment by m-kro** [comment]
Do you actually have a vehicle type with ID "type1" which is equipped with the battery device? Otherwise this won't work.

**Comment by wy12184163** [comment]
> 您是否真的有ID为“type1”的车辆类型配备了电池装置？否则这将不起作用。
<vType id="t0" length="5.00" minGap="2.50" maxSpeed="70.00" vClass="evehicle" emissionClass="Energy/default" guiShape="passenger" color="red" carFollowModel="IDM" accel="1.0" decel="1.0">
        <param key="airDragCoefficient" value="0.6"/>
        <param key="constantPowerIntake" value="100"/>
        <param key="frontSurfaceArea" value="5"/>
        <param key="has.battery.device" value="true"/>
        <param key="internalMomentOfInertia" value="0.01"/>
        <param key="maximumBatteryCapacity" value="2000"/>
        <param key="maximumPower" value="1000"/>
        <param key="propulsionEfficiency" value="0.9"/>
        <param key="radialDragCoefficient" value="0.5"/>
        <param key="recuperationEfficiency" value="0.9"/>
        <param key="rollDragCoefficient" value="0.01"/>
        <param key="stoppingThreshold" value="0.1"/>
        <param key="vehicleMass" value="2000"/>
    </vType>
   <vehicle id="9" type="t0" depart="0.00" route="r_0" color="1,0,0">
        <param key="device.battery.actualBatteryCapacity" value="500" />
    </vehicle>
    I did the above Settings but it is true that the initial charge is still half the maximum charge

**Comment by m-kro** [comment]
Your example works for me (after some XML cleaning). Remember you lowered the battery charge only for vehicle "9".
