### ISSUE TITLE
A question about LC2013 and DK2008

### ISSUE THREAD

**Issue by Sirus1110** [eclipse/sumo#13613]
As _SUMO’s Lane-Changing Model_ descibed that LC2013 was developed by Jakob Erdmann based on DK2008, and DK2008 is the lane-changing model of the paper, _Traffic Simulation with SUMO – Simulation of Urban Mobility_. 
Here, I have a few questions for you:
1. Why did you study a new lane-changing model at that time? Why not go with some classic rule-based lane change models?
2. What are the advantages of DK2008 or LC2013 over other models? At present, it is rare to use LC2013 as a lane-changing model in academia. How to prove that LC2013 is an authoritative lane-changing model？
Thanks for your help!

**Comment by m-kro** [comment]
Of which lane-change models do you think as possible alternatives? Could you name them and possibly give a reference?

**Comment by Sirus1110** [comment]
> Of which lane-change models do you think as possible alternatives? Could you name them and possibly give a reference?

What about the Gipps model and its variants (MITSIM or CORISM)? 
---------------------------------------------------------------------------------------------
Most of the current micro traffic simulation software packages are based on rule-based classical models(Gipps?),  However, there are generally problems of poor compatibility in the simulation software, such as the compatibility between the lane change model and the car-following model, and the compatibility between micro-cosmic lane-changing and macro-traffic flow, etc.

So, could it be considered that DK 2008 or SL 2013 has overcome the above shortcomings?

**Comment by Sirus1110** [comment]
To add, do the Gipps model and its variants still have the following problems:
1. The amount of calculation is large, and it is not suitable for large-scale road network simulation;
2. Lack of real-world data calibration;
Therefore, has SL2013 (DK2008) taken targeted measures to address the above problems?

**Comment by behrisch** [comment]
I think the best source on the topic is still [Jakob's 2014 paper](https://elib.dlr.de/89233/1/SUMO_Lane_change_model_Template_SUMO2014.pdf). So yes we did empirical validation not so much for the lane changing process itself but for lane usage. And as far as I remember the different motivations we use in SUMO for lane changing (tactical, cooperation, spped gain, keep-right) were not modelled properly in the existing models. Furthermore as you already noted there is always a strong interdependence to the car folllowing and also the junction model in use.

**Comment by Sirus1110** [comment]
Thank you for your kind assistance, it helps me a lot

**Comment by Sirus1110** [comment]
> I think the best source on the topic is still [Jakob's 2014 paper](https://elib.dlr.de/89233/1/SUMO_Lane_change_model_Template_SUMO2014.pdf). So yes we did empirical validation not so much for the lane changing process itself but for lane usage. And as far as I remember the different motivations we use in SUMO for lane changing (tactical, cooperation, spped gain, keep-right) were not modelled properly in the existing models. Furthermore as you already noted there is always a strong interdependence to the car folllowing and also the junction model in use.
-----------------------------------------------------------------
Sorry for not getting back to you sooner, your kind assistance  helps me a lot! 
And thank you very much for your contribution to the development of sumo!
