### ISSUE TITLE
Output issues about traci.person.getRemainingStages()

### ISSUE THREAD

**Issue by hhhhhhyl** [eclipse/sumo#13616]
Hello! May I ask why when I use `traci.person.getRemainingStages()` to get the completion of pedestrian routes, until the end of the simulation my number of completed routes stays zero and the number of uncompleted paths keeps increasing?
Here's my input files and the python file I used:
https://drive.google.com/file/d/1NDqihWsBeBhvYuxcvQ-_V_n3HqjA8kc3/view?usp=drive_link

**Comment by m-kro** [comment]
I cannot access the file - Google is asking for a login

**Comment by hhhhhhyl** [comment]
Sorry, I've updated the permissions：https://drive.google.com/file/d/1NDqihWsBeBhvYuxcvQ-_V_n3HqjA8kc3/view?usp=sharing

**Comment by hhhhhhyl** [comment]
I'm sorry, I don't really understand. What does it mean to adapt my check condition? How should I solve it?

**Comment by hhhhhhyl** [comment]
Oh, I see. Thank you very much!
