### ISSUE TITLE
About traci.vehicle.setRoute()

### ISSUE THREAD

**Issue by Clown1206** [eclipse/sumo#13628]
Add your issue description here.
Hello, I am now experimenting with vehicle routing planning using sumo based on reinforcement learning algorithm.For example, my sumo simulation uses the traci.vehicle.setRoute (['B6B5', 'B5B6', 'B6B5']) method to set a route for a vehicle (36_vehicle_37.00_F2) (current_road is B6B5, current_road is B6B5, next_roads are 'B5B6', 'B6B5'), and you can see the car starting from B6B5 and back to B6B5, which is not the destination of the car, but sumo removed the car and printed it in the trip info directory.

<tripinfo id="36_vehicle_37.00_F2" depart="37.00" departLane="B6B5_0" departPos="5.10" departSpeed="0.00" departDelay="0.00" arrival="129.00" arrivalLane="B6B5_1" ../>
*If possible, upload an example that shows your problem.*

**SUMO-version:**
1.16
**operating system:**
win10

**Comment by m-kro** [comment]
The first edge of your route is also the last one. So the trip output looks fine to me at first sight from the information you provided. What is your actual question?

**Comment by Clown1206** [comment]
This situation is not normal in my program. Because the vehicle has not yet arrived at its true destination. There are many similar cases in the trip file, and they all have one thing in common: By traci.vehicle.setRoute (['A', 'B', 'A']), The first edge of in the route is also the last one. The vehicles then exit the simulation automatically, and the tripinfo file outputs the vehicle journey information. However, in my program I detect if the vehicle has actually arrived at its destination and then remove the vehicle via traci.vehicle.remove().

**Comment by m-kro** [comment]
Vehicles leave when they have completed their route, whether it is cyclical or not. If you want to keep them in the simulation, you have to reassign a route or let them stop shortly before arriving at their destination.
