### ISSUE TITLE
Netconvert adds sidewalk to edge which does not allow pedestrians

### ISSUE THREAD

**Issue by m-kro** [eclipse/sumo#13624]
[Posted](https://www.eclipse.org/lists/sumo-user/msg13245.html) on the mailing list.

Netconvert uses the sidewalk width from the edge type, but the edge does not allow pedestrians.

**Comment by behrisch** [comment]
I think this is not a proper fix. Specifying a sidewalk width is the correct way to add a sidewalk. If you do not want to use the type information you should not load the types

**Comment by behrisch** [comment]
Maybe we could switch on `--ignore-errors.edge-type` by default if there is no type file loaded. This would make this use case considerably easier

**Comment by m-kro** [comment]
@behrisch OK then I'll add that.
