### ISSUE TITLE
Question Regarding "speed" in SUMO .rou Configuration Files

### ISSUE THREAD

**Issue by Jmiceli17** [eclipse/sumo#13629]
I have a question related to the configuration of SUMO simulations (apologies in advance if this is the incorrect forum for this question).

In my `.net` file, I have edges defined like
```xml
    <edge id=":1_9" function="internal">
        <lane id=":1_9_0" index="0" speed="13.89" length="5.00" shape="291.95,595.05 293.31,594.86 294.27,594.27 294.86,593.31 295.05,591.95"/>
    </edge>
```

My question is how is the `speed` parameter used? I am observing vehicle speeds that exceed `13.89` so I assume this parameter is treated more like a _statistical mean_ to sample from rather than a _maximum_ allowed value. Is this correct? 

This behavior is fine for my applications, I just want to make sure that I understand my observations.

Thank you for the help!

**SUMO-version:**
1.16.0

**operating system:**
Ubuntu 20.04 via WSL2 (hosted on Windows 11 Home machine)

**Comment by m-kro** [comment]
The allowed speed per lane is multiplied with the vehicle's `speedFactor` value such that you can have individual drivers easily. If all were capable and willing to drive at the same speed, a lot of effects you usually see in traffic would not happen (e.g. overtaking, traffic jams). Read more about it in the [docs](https://sumo.dlr.de/docs/Simulation/VehicleSpeed.html#edgelane_speed_and_speedfactor).
