### ISSUE TITLE
Retrieve Vehicle Signal, particularly blink right

### ISSUE THREAD

**Issue by enter802** [eclipse/sumo#13638]
I am trying to log the vehicle signals as defined [here](https://sumo.dlr.de/docs/TraCI/Vehicle_Signalling.html). However, when I export to a CSV file (or XML file), even when there is no VEH_SIGNAL_BLINKER_RIGHT, I get "0" in the output; this seems like the logger is logging zeros even when no actual vehicle signal is being activated. I've included my configuration file below and attached the CSV file. I wonder how I can separate VEH_SIGNAL_BLINKER_RIGHT. Thanks for your time in advance.

```
<configuration>
<input>
<net-file value="testing_matlab.net.xml"/>
<route-files value="testing_matlab.rou.xml"/>
</input>
<time>
<begin value="0"/>
<end value="200"/>
<step-length value="0.1"/>
</time>
<processing>
<lateral-resolution value="0.01"/>
</processing>
<output>
<fcd-output.signals value="true"/>
<fcd-output precision="1" value="simData.xml" />
</output>
</configuration>
```
[simData.csv](https://github.com/eclipse/sumo/files/12096358/simData.csv)

**Comment by m-kro** [comment]
The return value is an integer (base 10), whereas the cited documentation page tells you the bit which would be set for each signal (base 2). A value of 0 means that all bits are off. If only the right blinker is activated, you expect a value of  `2^0 = 1` . Have a read on [Wikipedia ](https://en.wikipedia.org/wiki/Binary-coded_decimal#Background)if you need more help on this.

**Comment by enter802** [comment]
Thanks. I just noticed - silly of me!
