### ISSUE TITLE
 generate traffic flow

### ISSUE THREAD

**Issue by Clown1206** [eclipse/sumo#13636]
I already have a ready-made road network, I want to use randomTrips.py to generate traffic flow, and set the simulation time to 3600s. I want to generate traffic flow with different congestion degrees, what should I do?
*If possible, upload an example that shows your problem.*

**SUMO-version:**
1.16
**operating system:**
win 10

**Comment by m-kro** [comment]
You can run randomTrips.py several times, each with different option values:

- begin time **-b**
- end time **-e**
- using different probabilities for start/edge/intermediate edges with **--weights-prefix**

**Comment by Clown1206** [comment]
![image](https://github.com/eclipse/sumo/assets/59904738/1c46eedd-ad6b-4d35-b4df-6966ed43f86b)
Hello, here's a schematic of my road network file, and I use this command to generate traffic flows: python randomTrips.py -n D:/experiments/pythonCode/my_routing/map/5x5_2/5x5_2.net.xml --begin 1 --end 3600 -- fringe-factor 7 --period="0.8" --random-depart --min-distance 1800 -o D:/experiments/pythonCode/my_routing/map/5x5_2/trips/5x5_2.trips. xml
But I noticed that the horizontal traffic flow is much more than the vertical traffic flow. Do you know what is the reason for this?

**Comment by m-kro** [comment]
No I don't. Your network seems larger along the x axis than along the y axis. What happens if you lower the **--min-distance** value?

**Comment by m-kro** [comment]
Please post here again if you still have the problem.
