### ISSUE TITLE
How can I modify the speed of the vehicle type using the traci interface

### ISSUE THREAD

**Issue by adoreador** [eclipse/sumo#13633]
Hello, I would like to ask some questions. I have defined the following vehicle types and traffic codes:

`<vType id="human" length="4.7500" color="1,1,0" accel="3.0" decel="3.0" stepping="1.0" carFollowModel="W99" >`
`<vType id="auto" length="4.75" carFollowModel="ACC" color="0,0,255" minGap="1" accel="4.0" decel="4" sigma="0.0">`
`<flow id="a1" begin="0" end= "3600" number="2000" type="human" departLane="random" departSpeed="33.34" >`
         `<route edges="E0 E1"/>`
`</flow>`
`<flow id="a2" begin="0" end= "3600" number="2000" type="auto" departLane="random" departSpeed="33.34" >`
 `<route edges="E0 E1"/>`
`</flow>`

I would like to inquire whether it is possible to modify the speed of an entire vehicle type on a specific road segment.  For example, I wish to make vehicletype with the ID "auto" proactively reduce their speed on the road segment with the ID "E1."  Can this be achieved using traci?  I have searched through the traci documentation for vehicletype but could not find a solution.  If you could provide some guidance, I would be immensely grateful.

**Comment by m-kro** [comment]
You could switch the vehicle type automatically using a [calibrator ](https://sumo.dlr.de/docs/Simulation/Calibrator.html#calibrating_vehicle_types) for the named edge (and back on the next edge if needed). Do you need this to change during the simulation? Otherwise there is no need for TraCI.

**Comment by adoreador** [comment]
Thank you for your response. I have read the information regarding Calibrators. However, I am still not entirely clear on whether it is possible to dynamically adjust the speed of each vehicle with the vehicle type ID "auto" based on the traffic conditions during the simulation. Can this be achieved in traci?

**Comment by m-kro** [comment]
You can lower the maximum speed of the vehicle type using `traci.vehicletype.setMaxSpeed`.
