### ISSUE TITLE
Some of the OSM derived roads are on the left. When edited using Nededit, it cannot be changed. It can only be deleted and redrawn.

### ISSUE THREAD

**Issue by HRYEJJKUK** [eclipse/sumo#13630]
OSM exported roads with some roads traveling on the left and some on the right. So using Netedit for editing, I found that I could not modify the roads traveling on the left to traveling on the right, e.g., redrawing them while entering parameters in shape, but still could not solve the problem. It can only be deleted and redrawn.
![image](https://github.com/eclipse/sumo/assets/121792232/193e3f7e-762b-432d-808e-94ed2043902a)

**SUMO-version:1.18.0**

**operating system:win-64**

**Comment by m-kro** [comment]
In first place, is the OSM import wrong? Do you know the place and tell give us the location?

**Comment by HRYEJJKUK** [comment]
It's been fixed, just need to change the option-processing-left hand.
