### ISSUE TITLE
Veh0 is not found

### ISSUE THREAD

**Issue by Swayam069** [eclipse/sumo#13634]
```
import sys
import traci
from sumolib import checkBinary
traci.start(["sumo", "-c", "osm.sumocfg"])
simulation_output = "Road_Trace_708364392_1.txt"
original_stdout = sys.stdout
sys.stdout = open(simulation_output, "w")
step = 0
vehicle = "veh0"
path=["708364392"]
print("708364392")
traci.vehicle.setMaxSpeed(vehicle, 1)
traci.vehicle.setRoute(vehicle,path)
while step <= 1000:      
    traci.simulationStep()
    vehicle="veh0"
    position = traci.vehicle.getPosition(vehicle)
    x_coord, y_coord = position
    lon, lat = traci.simulation.convertGeo(x_coord, y_coord)
    angle=traci.vehicle.getAngle(vehicle)
    print(lat,lon,angle)
sys.stdout.close()
sys.stdout = original_stdout
traci.close()
```

this is my code where i defined the vehicle which is in the osm.passenger file, i am only working with only one vehicle soo i defined it, but when i run the code the error says veh0 is not defined. i dont want to try the getidlist because i am working with only one vehicle.

please help me to optimize the code and find the errors
-swayam

**Comment by m-kro** [comment]
You can only access the vehicle once it has departed. That's why it is good practice to keep track of the vehicles in the simulation. If you know exactly when your vehicle is inserted, just advance to that time using `traci.simulationStep()` before calling get/set functions on the vehicle.
