### ISSUE TITLE
question for speed limit for multiple edges 

### ISSUE THREAD

**Issue by SongKun2023** [eclipse/sumo#13648]
Add your issue description here.
Hello sir. If I want to set the speed limit for multiple edges with traci, how can I do?  For instance, I set the max speed for the two edges as is shown in the screenshot in below. I find that first is working, but the second is useless. I don't know the reason. I'll appreciate it if you can give me some suggestions.

![59703606daedb9909fa31f61c29418d](https://github.com/eclipse/sumo/assets/97946646/ff81fc7f-90cf-4305-aec4-dd504384d56e)

SUMO-version: 1.17

operating system: Windows

**Comment by SongKun2023** [comment]
Hello? Could you give me some help?

**Comment by m-kro** [comment]
No reason to scream just because it's weekend and people do other stuff.

Please define **useless**. Where did you check the speed limit?

**Comment by SongKun2023** [comment]
[test.zip](https://github.com/eclipse/sumo/files/12147676/test.zip)

**Comment by SongKun2023** [comment]
Thanks a lot.

**Comment by SongKun2023** [comment]
Hello sir?

**Comment by m-kro** [comment]
You have defined vehicle class specific speed limits as part of edge types which override the general speed limit, see an excerpt of your net file below:

```
    <type id="G0512" priority="14" numLanes="3" speed="33.33">
        <restriction vClass="bus" speed="27.78"/>
        <restriction vClass="trailer" speed="27.78"/>
    </type>
    <type id="G5" priority="14" numLanes="3" speed="33.33">
        <restriction vClass="private" speed="30.00"/>
        <restriction vClass="bus" speed="27.78"/>
        <restriction vClass="truck" speed="28.00"/>
        <restriction vClass="trailer" speed="27.78"/>
    </type>
    <type id="SA2" priority="14" numLanes="3" speed="27.78">
        <restriction vClass="private" speed="30.56"/>
        <restriction vClass="bus" speed="22.22"/>
        <restriction vClass="truck" speed="30.56"/>
        <restriction vClass="trailer" speed="22.22"/>
    </type>
```
So you cannot have both at the same time. If you want to use `traci.edge.setMaxSpeed`, please remove the speed restrictions.

**Comment by SongKun2023** [comment]
OK, thank you sir. Can this conflict be resolved in the future, as both are important in my project.

**Comment by SongKun2023** [comment]
what other methods can achieve the same goal？

**Comment by m-kro** [comment]
A workaround:
You can define multiple vehicle types and change the vehicles' type using a [calibrator ](https://sumo.dlr.de/docs/Simulation/Calibrator.html#calibrating_vehicle_types) item at the begin and the end of the section previously using edge types. Define a different max. speed for the vehicle type you wwant to use inside this segment.

**Comment by SongKun2023** [comment]
Thank you very much. I will try. And I want to know if the priority can be defined between different speed limit functions including dynamics and constants .
