### ISSUE TITLE
About "allowed speed".

### ISSUE THREAD

**Issue by JamesPsh** [eclipse/sumo#13640]
Hello.

I have a question about `allowed speed (0xb7)` for vehicles.
I'd like to understand how `allowed speed (0xb7)` is defined.
https://sumo.dlr.de/docs/TraCI/Vehicle_Value_Retrieval.html

1. Is the `allowed speed` defined as follows?
~~~
# https://sumo.dlr.de/docs/Simulation/VehicleSpeed.html#edgelane_speed_and_speedfactor
allowed speed = min(maxSpeed, speedFactor * desiredMaxSpeed, speedFactor * speedLimit)
~~~

2. I anticipate that as the number of vehicles on the road increases, the allowed speed would decrease. Does the allowed speed also decrease as the number of surrounding vehicles increases?

Thank you.

**Comment by m-kro** [comment]
1. No. It is defined as 
```
allowed speed = min(maxSpeed, speedFactor * speedLimit)
```
2. No.

**Comment by JamesPsh** [comment]
@m-kro 
Thank you~
