### ISSUE TITLE
How to disable collision avoidance for a given vehicle in Sumo?

### ISSUE THREAD

**Issue by jfqureshi** [eclipse/sumo#13658]
Hello. i am using sumo for traffic simulation and testing planning algorithms. I want to disable collision avoidance for the ego vehicle because currently, the ego vehicle does not change lane due to safety concerns. This way Sumo overrides most of the commands i send to ego vehicle because of possibility of collision. i want to avoid that and set the actions even if they result into a collision. 
i set `collision.mingap-factor value="0"` and `collision.action value="none"`, still the ego vehicle is not changing lanes when it thinks its risky. Appreciate any help.

**SUMO-1.18:**

**Ubuntu-18.04:**

**Comment by m-kro** [comment]
I assume you use TraCI to request lane changes? Then you'll have to change the **lane change mode** (see [docs](https://sumo.dlr.de/docs/TraCI/Change_Vehicle_State.html#lane_change_mode_0xb6)) to disable collisions checks (bit 9/8).

**Comment by jfqureshi** [comment]
> I assume you use TraCI to request lane changes? Then you'll have to change the **lane change mode** (see [docs](https://sumo.dlr.de/docs/TraCI/Change_Vehicle_State.html#lane_change_mode_0xb6)) to disable collisions checks (bit 9/8).

Thanks a lot for the helpful information. I tried a lot of things without any success but this worked.

Also, could you please tell me why i am not able to detect collisions using TraCI?

This is my python code:
`colliding_vehicles_list = traci.simulation.getCollidingVehiclesIDList()`
`number_of_colliding_vehicles = len(traci.simulation.getCollidingVehiclesIDList())`
`if number_of_colliding_vehicles > 0:`
`    for vehicle_id in enumerate(colliding_vehicles_list):`
`        if vehicle_id == ego_vehicle_id:`
`            print("Collision has taken place, moving to next episode")`
`            print("Number of colliding vehicles is: ", number_of_colliding_vehicles)`
`            break`

Even after collisions, I get an empty list. Could you suggest any possible reason?
Thanks

**Comment by m-kro** [comment]
You'll have to set `collision.action value="warn"` to be notified about collisions both in the GUI and in TraCI.

**Comment by jfqureshi** [comment]
> You'll have to set `collision.action value="warn"` to be notified about collisions both in the GUI and in TraCI.

Thanks.

**Comment by MoMingQimio** [comment]
> You'll have to set `collision.action value="warn"` to be notified about collisions both in the GUI and in TraCI.

If I set  `collision.action value="warn"`  and ` --no-warnings, value = True`， can I obtain the collision information?

sumoBinary = "sumo"
        if self.render_mode=="human":
            sumoBinary = "sumo-gui"
        sumoCmd = [sumoBinary,
                   "-c", "sumo_networks/test.sumocfg",
                   "--lateral-resolution","3.8",
                   "--start", "true",
                   "--quit-on-end", "true",
                   "--no-warnings","True",
                   "--no-step-log", "True",
                   "--collision.mingap-factor", "0.0",
                   "--collision.action", "warn",
                   #"--log","/runs/sumo_log.txt",
                   ]

        traci.start(sumoCmd)

**Comment by m-kro** [comment]
No. Please open a new issue for questions not tightly related to an old one.
