### ISSUE TITLE
Can't calculate the remaining time of travel of a vehicle through multiple edges to the target junction

### ISSUE THREAD

**Issue by Chenyu3194** [eclipse/sumo#13651]
Hello,

I'm working on the SUMO Traci function and trying to calculate the remaining time of a vehicle approaching a junction. However, I only can do it when the vehicle appears on the edge in front of the junction, and I used the traci.getLanePosition. Is there possible solution that get the distance of the vehicle to the target junction through multiple edges and calculate the time? My code example is as follow:

if traci.vehicle.getRoadID(target_vehicle_id1) == target_edge_id1 and traci.vehicle.getLanePosition(target_vehicle_id1) >= 0:

                speed= traci.vehicle.getSpeed(target_vehicle_id1)
                speed2= traci.vehicle.getSpeed(target_vehicle_id2)

               
                remaining_distance1 = traci.lane.getLength(target_edge_id1 + "_0") - traci.vehicle.getLanePosition(target_vehicle_id1)
                remaining_distance2 = traci.lane.getLength(target_edge_id2 + "_0") - traci.vehicle.getLanePosition(target_vehicle_id2)
                remaining_time1 = remaining_distance1 / speed if speed> 0 else float('inf')
                remaining_time2 = remaining_distance2/ speed2 if speed> 0 else float('inf')

because I didn't find the solution so I only used the edge ID before the target junction

**SUMO-version:1.18**

**operating system:Win 11**

**Comment by m-kro** [comment]
You'll have to know where the vehicle wants to go: `traci.vehicle.getRoute`. Then you can use [sumolib.net](https://sumo.dlr.de/docs/Tools/Sumolib.html#loading_a_network_file) methods (see also [reference](https://sumo.dlr.de/pydoc/sumolib.net.html)) to compute the length of the retrieved edges including the internal ones. Some hints which sumolib methods may be helpful:

- sumolib.net.readNet
- sumolib.net.getEdge
- sumolib.net.Edge.getLength
- sumolib.net.Edge.getConnections

**Comment by Chenyu3194** [comment]
> You'll have to know where the vehicle wants to go: `traci.vehicle.getRoute`. Then you can use [sumolib.net](https://sumo.dlr.de/docs/Tools/Sumolib.html#loading_a_network_file) methods (see also [reference](https://sumo.dlr.de/pydoc/sumolib.net.html)) to compute the length of the retrieved edges including the internal ones. Some hints which sumolib methods may be helpful:
> 
> * sumolib.net.readNet
> * sumolib.net.getEdge
> * sumolib.net.Edge.getLength
> * sumolib.net.Edge.getConnections

I will try the sumolib function out and learn the usage of these methods. Thank you for the hints and suggestions!
