### ISSUE TITLE
can we use different taxi dispatch algorithm in one simulation?

### ISSUE THREAD

**Issue by mingunn** [eclipse/sumo#13663]
Add your issue description here.

*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**

Hello, I'm currently doing some experiments using 'taxi'.

The Traci currently offers 5 taxi dispatch algorithms. And I want to try to make some taxis follow the greedy algorithm and others to follow directly assigned reservations according to my algorithm whenever new reservations pop up. but it seems I can not use Traci and Greedy at the same time.  would be there some way to do this?

**Comment by m-kro** [comment]
The only way I see is to dispatch everything using TraCI and replicate the greedy algorithm there. You can find the source code of the integrated dispatch algorithms at src/microsim/devices/.
