### ISSUE TITLE
error LNK2019 and error LNK1120 at using Libtraci and Libsumo

### ISSUE THREAD

**Issue by SunTianzhHERE** [eclipse/sumo#13664]
I used libtraci for C++ to connect with Sumo in the Window development. But  LNK2019 and LNK1120 errors occur. How can I solve it? 
Below is my Code.
````
#include <iostream>
#include <libsumo/libtraci.h>

using namespace libtraci;

int main(int argc, char* argv[]) {
    Simulation::start({ "sumo", "-n", "cross.net.xml" });
    for (int i = 0; i < 5; i++) {
        Simulation::step();
    }
    Simulation::close();
}
```

**libsumo**

**libtraci**

**C++**

**Windows**

**Comment by palvarezlopez** [comment]
You need to link the sumolib in your visual studio solution. Check project options, linker, and there link the libsumo.lib placed in bin folder

**Comment by SunTianzhHERE** [comment]
Thanks, it works. But I have another problem when I use Simulation::start({ "sumo", "-n", "net.net.xml" }) ,and it tells me 0x00007FFE37B16D06 (libtracicpp.dll)  and : 0xC0000005 and  0x000001B8CD682018. What is wrong with that ?

**Comment by behrisch** [comment]
@SunTianzhHERE Please add the complete error messages and preferably open a new issue if the problem still persists
