### ISSUE TITLE
Collision detection at junction

### ISSUE THREAD

**Issue by RuiFilipe2802** [eclipse/sumo#13661]
Hello, 

I want to get warnings for collisions taking place in a intersection as shown 

![collisionNotDetected](https://github.com/eclipse/sumo/assets/56730143/cbb482a8-8ab9-45f2-bbec-c633d03d18a9)

I am using "--collision.action warn --collision.check-junctions true" but still no colision is detected on the intersection. Can you help with this issue?

Also i have my junction defined as follows

![image](https://github.com/eclipse/sumo/assets/56730143/ebce834b-a434-4cf2-993c-b29ad5351989)

Thanks in advance!

SUMO-version: 1.18.0
Operating system: Linux

**Comment by m-kro** [comment]
Could you please attach your zipped scenario here?

**Comment by m-kro** [comment]
Do you use [Eclipse MOSAIC](https://eclipse.dev/mosaic/)? You did not supply any traffic demand as your route file is empty. Could you please provide an example which can be executed without any third party content?

**Comment by RuiFilipe2802** [comment]
> Do you use [Eclipse MOSAIC](https://eclipse.dev/mosaic/)? You did not supply any traffic demand as your route file is empty. Could you please provide an example which can be executed without any third party content?

Yes, i am using Eclipse Mosaic. I tried to create an example where i could show you the problem in SUMO and the situation is as follows

![image](https://github.com/eclipse/sumo/assets/56730143/c74e0361-5882-48b6-aa61-85a3115696c6)

Despite the vehicles colliding i only get warning about emergency braking and nothing about a collision in the intersection.

Scenario zip file: [projectCommSumo.zip](https://github.com/eclipse/sumo/files/12172730/projectCommSumo.zip)
I ran the simulation with: "sumo-gui --step-length 0.1 -c vehrsu.sumocfg"

**Comment by m-kro** [comment]
You didn't activate `--collision.action warn --collision.check-junctions true` this time. I get the collision warnings when I do:
```
Warning: Vehicle 't_0'; junction collision with vehicle 't_1', lane=':J1_1_2', gap=-1.00, time=13.60 stage=move.
Warning: Vehicle 't_1'; junction collision with vehicle 't_0', lane=':J1_0_0', gap=-1.00, time=13.90 stage=move.
```

**Comment by RuiFilipe2802** [comment]
Yes indeed if i activate I receive the warnings, so it must be a problem with the Eclipse Mosaic files. I will try to see what the issue might be and if not will ask on the mosaic github. Thank you for your time

**Comment by RuiFilipe2802** [comment]
Hello @m-kro , 

I contacted the mosaic team and it seems like the problem might be on SUMO side. I have another example project only using sumo where I use --collision.action warn and --collision.check-junctions true but do not obtain warnings on collisions.

Project: [collision_sumo_only.zip](https://github.com/eclipse/sumo/files/12183141/collision_sumo_only.zip)

If you could have a look at it and help me find the issue I would appreciate it.

**Comment by m-kro** [comment]
@RuiFilipe2802 I noted that recomputing the junction logic in netedit leads to a different right-of-way than in your net file. Did you modify the net file directly in a text editor?

**Comment by m-kro** [comment]
Yes, as not every change which seems to work from the outside actually does. See our [FAQ](https://sumo.dlr.de/docs/FAQ.html#i_made_changes_to_the_netxml-file_but_it_did_not_work_as_expected_why).

**Comment by m-kro** [comment]
You are better off using options of the [junction model](https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#junction_model_parameters): add the following attributes to your vehicle types: `jmIgnoreFoeProb="1" jmIgnoreJunctionFoeProb="1"`. As they are tied to the vehicle type, the vehicle will behave correspondingly at all intersections, though (unless you combine it with [Calibrator ](https://sumo.dlr.de/docs/Simulation/Calibrator.html#calibrating_vehicle_types)items to switch vehicle types).
