### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by 17377786473** [eclipse/sumo#13662]
Add your issue description here.

*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**

Hello! I am running this code "https://github.com/seanfhear/mcts-intersections/issues"on my computer and the message 'D: Eclipse Sumo tools trace main. py: 162: UserWarning: Could not connect to TraCI server using port 54246' appears Retrying with different ports

Warnings. warn ("Could not connect to TraCI server using port% s. Retrying with different port."% sumoPort)

Traceback (most recent call last):

File "E: alanechangemethod Monte Carlo Tree Search on Traffic mcts interactions main src main. py", line 140, in

Main()

File "E: alanechangemethod Monte Carlo Tree Search on Traffic mcts interactions main src main. py", line 62, in main

Traci. start (sumOCmd)

File "D: Eclipse Sumo tools track main. py", line 164, in start

Raise FatalTraCIError ("Could not connect.")

Traci. exceptions. FatalTracCIError: Could not connect.
I have searched for a lot of information, and both my computer system variables and user variables have been set to sumo.I don't know how to solve this problem.

**Comment by m-kro** [comment]
The sumocfg files (like [this one](https://github.com/seanfhear/mcts-intersections/blob/main/data/2x4_intersection.sumocfg)) provided in the cited repository have to be updated regarding file paths. At the moment they still have absolute paths to a local directory of the author. Consequently SUMO cannot load the sumocfg file and not allow TraCI to connect.
Please update the paths to net file etc. in your local copy to match the actual path.

**Comment by 17377786473** [comment]
Hello, I have modified the file path, but the code still has this issue“File "E:\alanechangemethod\Monte Carlo Tree Search on Traffic\mcts-intersections-main\src\main.py", line 62, in main
&nbsp; &nbsp; traci.start(sumoCmd)
&nbsp; File "D:\Eclipse\Sumo\tools\traci\main.py", line 164, in start
&nbsp; &nbsp; raise FatalTraCIError("Could not connect.")
traci.exceptions.FatalTraCIError: Could not connect.”. I don't know how to make the changes




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "eclipse/sumo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月26日(星期三) 下午2:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [eclipse/sumo] problem (Issue #13662)





 
The sumocfg files (like this one) provided in the cited repository have to be updated regarding file paths. At the moment they still have absolute paths to a local directory of the author. Consequently SUMO cannot load the sumocfg file and not allow TraCI to connect.
 Please update the paths to net file etc. in your local copy to match the actual path.

**Comment by m-kro** [comment]
The path to SUMO is encoded in [src/config.yaml](https://github.com/seanfhear/mcts-intersections/blob/main/src/config.yaml) . Please contact the author of the mcts-intersections repository for further questions as this clearly related to his code!

**Comment by 17377786473** [comment]
Okay, thank you again for your reply




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "eclipse/sumo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月27日(星期四) 下午3:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [eclipse/sumo] MCTS intersections scenario at https://github.com/seanfhear/mcts-intersections (Issue #13662)





 
The path to SUMO is encoded in src/config.yaml . Please contact the author of the mcts-intersections repository for further questions as this clearly related to his code!
