### ISSUE TITLE
Problem when install SUMO on M2 macbook pro

### ISSUE THREAD

**Issue by MelodyyyYin** [eclipse/sumo#13660]
**SUMO-version: 1.18.0**

**operating system: macbook pro m2 chip ventura 13.4**

Here is what I got from terminal, when I follow the installation step on https://sumo.dlr.de/docs/Installing/MacOS_Build.html#prerequisites, I receive error after run command `cmake --build . --parallel $(sysctl -n hw.ncpu)`

<img width="1017" alt="Screenshot 2023-07-25 at 11 03 06 AM" src="https://github.com/eclipse/sumo/assets/97646140/00fc75a0-e922-45da-84c0-4930c613fff1">

<img width="1073" alt="Screenshot 2023-07-25 at 11 03 29 AM" src="https://github.com/eclipse/sumo/assets/97646140/f0d031a2-0135-4e7f-ac27-cd3df8c6dff1">
<img width="1023" alt="Screenshot 2023-07-25 at 11 03 51 AM" src="https://github.com/eclipse/sumo/assets/97646140/18442530-a28a-4b02-8aea-322acf3b6a8c">

**Comment by MelodyyyYin** [comment]
here is the result when running `cmake ../..`
<img width="1067" alt="Screenshot 2023-07-25 at 11 09 53 AM" src="https://github.com/eclipse/sumo/assets/97646140/08e69634-e897-44e1-adcf-a4fed0bfaacb">
<img width="1053" alt="Screenshot 2023-07-25 at 11 10 15 AM" src="https://github.com/eclipse/sumo/assets/97646140/53c7cff3-8ac8-493a-8665-3ca14f69be88">

**Comment by angelobanse** [comment]
Delete the entire content of the `cmake-build` directory, and try again:
```
cmake ../..
cmake --build . --parallel $(sysctl -n hw.ncpu)
make install
```

**Comment by MelodyyyYin** [comment]
I tried again and still have this problem 
<img width="863" alt="Screenshot 2023-07-26 at 1 43 46 AM" src="https://github.com/eclipse/sumo/assets/97646140/89cd324b-5bda-4c0f-a45e-f35ea7f13276">

<img width="874" alt="Screenshot 2023-07-26 at 1 44 02 AM" src="https://github.com/eclipse/sumo/assets/97646140/e79e3746-96af-4492-af7f-c1f0740a72f3">

<img width="888" alt="Screenshot 2023-07-26 at 1 44 16 AM" src="https://github.com/eclipse/sumo/assets/97646140/7747bc0e-0347-432c-9a5e-0780c7c5436f">

**Comment by MelodyyyYin** [comment]
After that, I tried another time
<img width="744" alt="Screenshot 2023-07-26 at 1 49 46 AM" src="https://github.com/eclipse/sumo/assets/97646140/f441bb56-a91d-4fa8-a565-1b3461bea896">

<img width="880" alt="Screenshot 2023-07-26 at 1 47 50 AM" src="https://github.com/eclipse/sumo/assets/97646140/e18b1dc1-6812-4159-bf24-05d94070a091">
<img width="876" alt="Screenshot 2023-07-26 at 1 48 04 AM" src="https://github.com/eclipse/sumo/assets/97646140/7be96bac-c53b-4ef1-a6c0-b8eea9eea77c">
<img width="878" alt="Screenshot 2023-07-26 at 1 48 16 AM" src="https://github.com/eclipse/sumo/assets/97646140/3a3f3433-8eec-47d3-a8ec-bedfb2d92ce1">
<img width="878" alt="Screenshot 2023-07-26 at 1 48 44 AM" src="https://github.com/eclipse/sumo/assets/97646140/3edbced0-b113-462c-
<img width="878" alt="Screenshot 2023-07-26 at 1 48 56 AM" src="https://github.com/eclipse/sumo/assets/97646140/f3768103-b886-4763-8fe8-dc013f428f31">
8b79-d4e2f3a52cf6">

**Comment by angelobanse** [comment]
You didn't remove the files first. 
According to the first screenshot, you tried to delete the files inside `sumo/build/cmake-build/cmake-build` - a directory that doesn't exist. Just use the Finder and manually remove all folders and files inside `cmake-build` or run `rm -r *` from inside the `cmake-build` directory.

**Comment by MelodyyyYin** [comment]
I first empty the `cmake-build` folder

<img width="767" alt="Screenshot 2023-07-26 at 10 20 30 AM" src="https://github.com/eclipse/sumo/assets/97646140/a0ccc0ac-cf02-4a6f-9f2d-f21f493db5de">


Then, I manually delete the `cmake-build` folder from Finder and create again. 
The following is just double check the file is deleted and create a new one.

<img width="515" alt="Screenshot 2023-07-26 at 10 22 34 AM" src="https://github.com/eclipse/sumo/assets/97646140/223caf09-c39a-4c36-a824-1da16e4a499a"> 


And the following is the result from `cmake ../..`

<img width="947" alt="Screenshot 2023-07-26 at 10 24 03 AM" src="https://github.com/eclipse/sumo/assets/97646140/14e79103-52ee-4b8b-b821-7ead7e62ac5b">
<img width="947" alt="Screenshot 2023-07-26 at 10 24 44 AM" src="https://github.com/eclipse/sumo/assets/97646140/2e22ab93-081d-42dd-8894-c03998ebd314">
the following is the result from `cmake --build . --parallel $(sysctl -n hw.ncpu)`
<img width="952" alt="Screenshot 2023-07-26 at 10 25 16 AM" src="https://github.com/eclipse/sumo/assets/97646140/0e9de725-0c2c-4dcd-9713-fd186f075d65">
<img width="910" alt="Screenshot 2023-07-26 at 10 26 10 AM" src="https://github.com/eclipse/sumo/assets/97646140/d760fff4-43b3-4dfb-bcdb-0b291e5ea613">
<img width="955" alt="Screenshot 2023-07-26 at 10 26 28 AM" src="https://github.com/eclipse/sumo/assets/97646140/e77a75bb-349a-4f80-99c2-61169a43bd66">

**Comment by angelobanse** [comment]
Where did you download the SUMO files from? I can see you didn't clone it from GitHub. The `version.h` file may be missing.

May I ask if you have any particular reason not to [install SUMO through homebrew](https://sumo.dlr.de/docs/Installing/index.html#macos)?

**Comment by MelodyyyYin** [comment]
I download file from this website https://sumo.dlr.de/docs/Downloads.php#macos, but I don't know I need to install it first in order to build it. I will try to install it and try again.

**Comment by MelodyyyYin** [comment]
Just want to make sure the process: download -> install -> build right?
I install the sumo but it still doesn't work and I make sure I set the environment correctly
<img width="677" alt="Screenshot 2023-07-27 at 9 06 21 PM" src="https://github.com/eclipse/sumo/assets/97646140/9a6af5e7-20e3-4d1c-90d2-75ef53fc05d8">


and this is the install process
<img width="963" alt="Screenshot 2023-07-27 at 9 06 53 PM" src="https://github.com/eclipse/sumo/assets/97646140/ca7078f7-e5df-4342-973e-c97e9181a8d6">
<img width="962" alt="Screenshot 2023-07-27 at 9 08 53 PM" src="https://github.com/eclipse/sumo/assets/97646140/427c2554-5933-4cd0-9d1d-6cbbbbbfe76c">

and the build process 
<img width="957" alt="Screenshot 2023-07-27 at 9 09 31 PM" src="https://github.com/eclipse/sumo/assets/97646140/15437b7f-25b3-44a8-af22-42a0a937a3b0">
<img width="967" alt="Screenshot 2023-07-27 at 9 09 48 PM" src="https://github.com/eclipse/sumo/assets/97646140/16c538e2-ce29-418b-b4ab-f8f5c06b79ca">
<img width="961" alt="Screenshot 2023-07-27 at 9 10 08 PM" src="https://github.com/eclipse/sumo/assets/97646140/92cceb97-5a45-4a20-a377-2f15a17fd7bb">

So, it still can not build successfully. I also tried restart the terminal, empty the `cmake-build` directory, run `cmake --build . --parallel $(sysctl -n hw.ncpu)` again and it appears the same problem. 

I also open the x11 (which just showing open in the dock but did not have any window open), but I cannot open the sumo-gui (sumo-gui doesn't have any response after I click it)

**Comment by angelobanse** [comment]
If you install SUMO using Homebrew, you don't need to do a manual build or install it using pip.

It looks like you succesfully installed SUMO using Homebrew. Change the SUMO_HOME variable to:
`SUMO_HOME="/opt/homebrew/opt/sumo/share/sumo"` instead of ~~/Users/yueyin/Downloads/sumo-1.18.0~~

**Comment by MelodyyyYin** [comment]
The sumo-gui does not open automatically after I manually open the x11. I am wondering what does it mean by log in and log out, does it mean restart the computer? Also, i changed the variable only in zshrc file. Does that might be a reason for cannot open sumo-gui

**Comment by angelobanse** [comment]
- sumo-gui opens X11, not the other way around
- if you have the application launchers (https://sumo.dlr.de/docs/Downloads.php#application_launchers) use them to open sumo-gui
- log in / log out means closing the user session, but a restart will also work
