### ISSUE TITLE
0x00007FFE37B16D06 (libtracicpp.dll) and : 0xC0000005 and 0x000001B8CD682018

### ISSUE THREAD

**Issue by SunTianzhHERE** [eclipse/sumo#13666]
*When I use Simulation::start({ "sumo", "-n", "net.net.xml" }) , it tells me 0x00007FFE37B16D06 (libtracicpp.dll) and : 0xC0000005 and 0x000001B8CD682018. What is wrong with that ?*
```
#include <iostream>
#include <libsumo/libtraci.h>

using namespace libtraci;

int main(int argc, char* argv[]) {
    Simulation::start({ "sumo", "-n", "net.net.xml" });
    for (int i = 0; i < 5; i++) {
        Simulation::step();
    }
```

**Comment by angelobanse** [comment]
Did you build SUMO or did you download it?
Are you on Windows and using Visual Studio to run that file?

**Comment by m-kro** [comment]
The code is the same as in our docs. Probably there is no net file of this name at the given local path...
