### ISSUE TITLE
E.consumption-E.charging

### ISSUE THREAD

**Issue by wy12184163** [eclipse/sumo#13677]
How do I use traci to get the difference between the amount of energy my EV consumes at the charging station and the amount of energy it replenishes

**SUMO-version:**1.16

**operating system:**windows

**Comment by wy12184163** [comment]
Can I get the value of energy recovery of electric vehicle through traci

**Comment by m-kro** [comment]
Please have a read in the [docs](https://sumo.dlr.de/docs/Models/Electric.html#traci). You can access the current state of the battery device calling the `traci.vehicle.getParameter` function with `device.battery.<KEY>` (where <KEY> is one those in the battery device [definition table](https://sumo.dlr.de/docs/Models/Electric.html#defining_electric_vehicles)).

**Comment by wy12184163** [comment]
> 请阅读[文档](https://sumo.dlr.de/docs/Models/Electric.html#traci)。您可以访问调用函数的电池设备的当前状态（其中是电池设备[定义表中](https://sumo.dlr.de/docs/Models/Electric.html#defining_electric_vehicles)的电池设备）。`traci.vehicle.getParameter``device.battery.<KEY>`

Function traci. Vehicle. GetElectricConsumption () is the vehicle's power loss value minus the energy recovery value minus the charging stations to obtain energy？

**Comment by m-kro** [comment]
Charging effects are not included in `traci.vehicle.getElectricConsumption()` but recovery is.
