### ISSUE TITLE
Tracemapper + Duarouter causing gridlock

### ISSUE THREAD

**Issue by Mehdi-Inane** [eclipse/sumo#13679]
Hi, 

I am running a traffic simulation on SUMO, and the demand is generated from real world vehicle trajectories of an urban network. I have imported this network using OSM, and converted the vehicle lon,lat points to rouets using tracemapper.py, that is provided in the SUMO library. Since several of the resulting routes had some connectivity issues, I had to correct the route file using duarouter. But now I can see in the simulation that the routes have significantly changed, especially causing some vehicles to keep doing U-turns from an intersection to the other, which starts by spreading spillback all over the network and ultimately causing gridlock. Do you have an idea why I have such an issue ? Or should I change the way I'm converting the trajectories to routes ?
Please find below the commands I'm using for conversion : 
 python3 tracemapper.py --n SUMO.net.xml --t routes.txt --o SUMO.rou.xml --geo
duarouter --net-file SUMO.net.xml -r SUMO.rou.xml --output-file routes.rou.xml --precision 6 --precision.geo 6 --repair
Thank you very much for your help.

Eclipse SUMO sumo Version 1.18.0
 Build features: Linux-5.4.0-153-generic x86_64 GNU 9.4.0 Release FMI Proj GUI Intl SWIG GDAL GL2PS Eigen
 Copyright (C) 2001-2023 German Aerospace Center (DLR) and others; https://sumo.dlr.de

**Comment by m-kro** [comment]
Did you try the tracemapper options to help with disconnected routes like **--fill-gaps DIST** where **DIST** is in meters? This may help in some cases. If not, there may be similar problems to #12101 in your network (still unsolved). For more advice we need the net and the route file (can be zipped and attached to this issue).

**Comment by m-kro** [comment]
OK I think duarouter tries hard to correct faulty tracemapper routes and is not to blame here. The problem is really with tracemapper so could you please add the trace data, too?

**Comment by Mehdi-Inane** [comment]
Yes ! Please find them below. I have also tried verifying the accuracy of the GPS data and it is pretty accurate, it comes from https://open-traffic.epfl.ch/ . I have used weTransfer to share the trajectory data as even the zipped version is too big for upload here : https://we.tl/t-IcQZ3ISsrP
Thanks again for the help !

**Comment by m-kro** [comment]
I have checked only few trajectories but it seems the problem is already present in the input GPS data. I tested the line from "Bus_101410" which goes back and forward around Omonoia square of Athens within a few data points.

**Comment by Mehdi-Inane** [comment]
I'm sorry for not checking that. I'll try to better clean the data then, maybe use some smoothing and interpolation. Thanks again for all the help !
