### ISSUE TITLE
How to load the output from marouter

### ISSUE THREAD

**Issue by TrinhTuanHung2021** [eclipse/sumo#13670]
Add your issue description here.

*If possible, upload an example that shows your problem.*

Hello. I followed your instructions to create traffic generation based on marouter
`marouter -n input_net.net.xml -a input_taz.taz.xml -r input_trips.trips.xml --output routes.rou.xml --routing-threads 5`

The output of marouter is here
![image](https://github.com/eclipse/sumo/assets/82990411/48664cd7-c05e-47a4-88fe-bd1af2d8306d)

When loading this by Sumo, it has errors.
![image](https://github.com/eclipse/sumo/assets/82990411/df2e72a6-ef2e-40bd-a1ab-94f6c492ca80)

I do not know how to load this traffic demand.
Thanks and best regards

**SUMO-version:** 1.18

**operating system:**

**Comment by m-kro** [comment]
This is related to XML validation. You can switch that off calling sumo with **--xml-validation never**. I am not sure why it is considered invalid from what is on your screenshot... Could you maybe provide the files to reproduce it on our side?

**Comment by TrinhTuanHung2021** [comment]
[marouter.zip](https://github.com/eclipse/sumo/files/12190960/marouter.zip)


> This is related to XML validation. You can switch that off calling sumo with **--xml-validation never**. I am not sure why it is considered invalid from what is on your screenshot... Could you maybe provide the files to reproduce it on our side?
Thank you for your quick reply.
Hello. This is my files.

**Comment by TrinhTuanHung2021** [comment]
Thank you for your quick reply.
Hello. This is my files. 
[marouter.zip](https://github.com/eclipse/sumo/files/12191005/marouter.zip)

I add this option `-xml-validation never`

`marouter -n input_net.net.xml -a input_taz.taz.xml -r input_trips.trips.xml --output routes.rou.xml --routing-threads 5 --xml-validation never`

But I still can not load it with Sumo

**Comment by m-kro** [comment]
Can you please add the resulting routes file? I don't run into problems when generating it on my side.

**Comment by TrinhTuanHung2021** [comment]
> Can you please add the resulting routes file? I don't run into problems when generating it on my side.

I can generate route file from marouter. The result route file is in this folder. But I can not load this file with Sumo

**Comment by m-kro** [comment]
Overlooked the file as I immediately called marouter and generated it myself, sorry. However I cannot reproduce the problem. Do you call sumo-gui exactly like this?
```
sumo-gui -n input_net.net.xml -r routes.rou.xml
```

**Comment by TrinhTuanHung2021** [comment]
> sumo-gui -n input_net.net.xml -r routes.rou.xml

Thanks. I can load it.

In the past, I opened the net.xml file and loaded the route file, and it had errors. 
![Untitled](https://github.com/eclipse/sumo/assets/82990411/bf01e0ba-899b-4140-9dfa-82fffe5d710f)
But it is ok if I follow your instructions
