### ISSUE TITLE
macOS build from source for Conda

### ISSUE THREAD

**Issue by martinherrerias** [eclipse/sumo#13688]
I'm trying to install from source (commit [6b758c2](https://github.com/eclipse/sumo/commit/6b758c2f201ace3719a59ee7b920f0e317510e6b)) on a Mac with OS X, following these instructions: https://sumo.dlr.de/docs/Installing/MacOS_Build.html

I seem to have solved all dependencies (`make` runs without errors), but I still can't `import libsumo` from (Conda) python. I tried using variations of the suggested `cmake` command:

```
conda activate sumo

cmake \
-DPYTHON_EXECUTABLE=`which python` \
-DPYTHON_INCLUDE_DIR:PATH=/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Headers \
-DPYTHON_LIBRARY:FILEPATH=/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/Current/lib/libpython3.8.dylib \
../..
```

However, no matter what I set for `-DPYTHON_EXECUTABLE`, `-DPYTHON_INCLUDE_DIR:PATH` and `-DPYTHON_LIBRARY:FILEPATH`, cmake seems to default back to:
```
-- Found Python: /opt/homebrew/Frameworks/Python.framework/Versions/3.11/bin/python3.
```
... and issues a warning:
```
CMake Warning:
  Manually-specified variables were not used by the project:

    PYTHON_INCLUDE_DIR
    PYTHON_LIBRARY
```

**Questions:**
- How do I configure SUMO to use (and run on) a particular Conda environment 
- Does it even matter? Is it just a matter of adding it to the system path? (https://sumo.dlr.de/docs/FAQ.html#python_tools)

**Comment by angelobanse** [comment]
Make sure to sumo/tools to the path (https://sumo.dlr.de/docs/Libsumo.html#building_and_installing_it).

You can also consider installing libsumo via pip `pip install libsumo`

**Comment by temetski** [comment]
Hi @martinherrerias! I did a pull request a while back supposedly fixing this issue on MacOS. I have since then been successful in compiling and running libsumo from my conda installation. Can you try running the make command with 
```
-DPYTHON_INCLUDE_DIR:PATH=/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Headers \
-DPYTHON_LIBRARY:FILEPATH=/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/Current/lib/libpython3.8.dylib \
```
removed? Preferrably remove your cmake cached files. Also, does `which python` report the conda-installed python?

**Comment by behrisch** [comment]
Closing for lack of feedback. If the problem persists, please add another comment here.

**Comment by martinherrerias** [comment]
Thanks for the reply, and sorry for the lack of feedback, I was sorting this out for one of our students, and she just disappeared.
