### ISSUE TITLE
Parameter usage

### ISSUE THREAD

**Issue by wy12184163** [eclipse/sumo#13689]
How can i use these
device.battery.energyConsumed
device.battery.energyCharged
device.battery.actualBatteryCapacity
device.battery.maximumBatteryCapacity
device.battery.chargingStationId
device.battery.vehicleMass
device.battery.totalEnergyConsumed
device.battery.totalEnergyRegenerated

**SUMO-version:**1.16

**operating system:**windows

**Comment by m-kro** [comment]
Some of them are output data of the battery device while some are input values which influence how the device works. An example task might be to query the current battery state of charge (`device.battery.actualBatteryCapacity / device.battery.maximumBatteryCapacity`).
