### ISSUE TITLE
Traffic light signals cannot be created

### ISSUE THREAD

**Issue by HRYEJJKUK** [eclipse/sumo#13684]
A warning appears when I create a traffic signal.
![image](https://github.com/eclipse/sumo/assets/121792232/e22a6cd8-4c3b-4491-8d88-4ca295a72fa4)
Above is where the signal will be created
The following warning is then displayed.
Warning: The traffic light 'cluster_2127100019_J116' does not control any links; it will not be build.
Warning: Could not build program '2' for traffic light 'cluster_2127100019_J116'

**SUMO-version:1.14.1**

**operating system:win 10**

**Comment by palvarezlopez** [comment]
@HRYEJJKUK select all connections and change attribute "uncontrolled" to false
