### ISSUE TITLE
SUMO unexpectedly crashed when add <stop>

### ISSUE THREAD

**Issue by HuyTyskland** [eclipse/sumo#13694]
Hello everyone,

Currently, I am working with SUMO and I am trying to add <stop> for a vehicle in the `.rou.xml` file. However, something weird happened
I have 4 vehicles as below:
```
    <vehicle id="pl_a1" type="platoonLeader" route="route0" depart="0" departLane="0" departSpeed="max"> <!--[0]-->              <!---->
        <stop lane="hw0_0" endPos="1000" duration="100"/>
    </vehicle>
    <vehicle id="ll_a1" type="laneLeader" route="route0" depart="0" departLane="1" departSpeed="max"> <!--[1]-->              <!---->
        <stop lane="hw0_1" endPos="1000" duration="100"/>
    </vehicle>
    <vehicle id="pl_c1" type="platoonLeader" route="route0" depart="0" departLane="4" departSpeed="max"> <!--[2]-->              <!---->
        <stop lane="hw0_4" endPos="1000" duration="100"/>
    </vehicle>
    <vehicle id="ll_c1" type="laneLeader" route="route0" depart="0" departLane="5" departSpeed="max"> <!--[3]-->              <!---->
        <stop lane="hw0_5" endPos="1000" duration="100"/>
    </vehicle>
```
and their type are:
```
    <vType id="platoonLeader" vClass="passenger" length="5" maxSpeed="5" speedDev="0.0" color="1,0,0" lcSpeedGain="0" lcKeepRight="0" lcCooperative="0">
      <param key="vehroute.output.sorted" value="true"/>
   </vType>
    <vType id="laneLeader" vClass="passenger" length="5" maxSpeed="5" speedDev="0.0" color="0,1,0" lcSpeedGain="0" lcKeepRight="0" lcCooperative="0">
      <param key="vehroute.output.sorted" value="true"/>
   </vType>
```

The edge is:
```
    <edge id="hw0" from="hwStart" to="hwEnd" priority="1" type="highway">
        <lane id="hw0_0" index="1" allow="private emergency authority army vip passenger hov taxi bus coach delivery truck trailer motorcycle evehicle" speed="10" length="2000.00" width="3.00" shape="2000.00,17.05 0.00,17.05"/>
        <lane id="hw0_1" index="2" allow="private emergency authority army vip passenger hov taxi bus coach delivery truck trailer motorcycle evehicle" speed="10" length="2000.00" width="3.00" shape="2000.00,13.95 0.00,13.95"/>
        <lane id="hw0_2" index="3" allow="private emergency authority army vip passenger hov taxi bus coach delivery truck trailer motorcycle evehicle" speed="10" length="2000.00" width="3.00" shape="2000.00,10.85 0.00,10.85"/>
        <lane id="hw0_3" index="4" allow="private emergency authority army vip passenger hov taxi bus coach delivery truck trailer motorcycle evehicle" speed="10" length="2000.00" width="3.00" shape="2000.00,7.75 0.00,7.75"/>
        <lane id="hw0_4" index="5" allow="private emergency authority army vip passenger hov taxi bus coach delivery truck trailer motorcycle evehicle" speed="10" length="2000.00" width="3.00" shape="2000.00,4.65 0.00,4.65"/>
        <lane id="hw0_5" index="6" allow="private emergency authority army vip passenger hov taxi bus coach delivery truck trailer motorcycle evehicle" speed="10" length="2000.00" width="3.00" shape="2000.00,1.55 0.00,1.55"/>
    </edge>
```
When I run that in SUMO, the application unexpectedly stopped. Without all the <stop>s, it still ran okay. I checked each <stop> and found out that, the <stop> in the fourth vehicle is the problem (I tried to delete the fourth <stop> and the program still ran but as soon as I added the fourth <stop>, the program stopped). However, I am not sure what I did wrong with it.

So what might be the reason for such error?

Kind regards,
Huy Nguyen.
SUMO-version: 1.18

Operating system: Linux 20.04

**Comment by HuyTyskland** [comment]
[scenario.zip](https://github.com/eclipse/sumo/files/12262176/scenario.zip)
Hello @m-kro , thank you for your response. Can you recreate with this zip file?

**Comment by HuyTyskland** [comment]
Ah okay, thank you for your help.

**Comment by HuyTyskland** [comment]
Hello @m-kro  just to make sure: did you get the latest scenario.zip? I did edit the file once.

**Comment by HuyTyskland** [comment]
Hello @m-kro , I just checked the "latest" scenario.zip on Windows and SUMO crashed so I guessed that you downloaded the file before I edited.

**Comment by m-kro** [comment]
@HuyTyskland Exactly, I used the first version you uploaded. The second one makes SUMO crash on Windows.

**Comment by HuyTyskland** [comment]
Good morning @m-kro yeah. the second one is the one that causes crash. I also tried a different version in which I have 4 flows only and with each flow, I put a <stop> to it. That also had crash.

**Comment by m-kro** [comment]
Did you edit the net file manually? If yes, then we [clearly advise against](https://sumo.dlr.de/docs/FAQ.html#i_made_changes_to_the_netxml-file_but_it_did_not_work_as_expected_why) this . The lanes have 1-based indices whereas SUMO uses 0-based indices. SUMO crashes because it expects the leftmost lane to have index 5, not 6!

**Comment by HuyTyskland** [comment]
Yes I did. I am sorry for that. 

So to temporarily fix this, I need to change the index starting from 0 instead of 1? or there are many other things?. Because now it's a bit time critical. Or I must follow the link?

I can do your advice from the link later.

**Comment by m-kro** [comment]
Yes change the lane index...

**Comment by HuyTyskland** [comment]
Thank you for your help.
