### ISSUE TITLE
Program about changing SUMO version

### ISSUE THREAD

**Issue by SunTianzhHERE** [eclipse/sumo#13695]
Hi, I have two versions of SUMO in my computer. One is 1.18.0, and the other is 1.12.0. I want to run my project  by different version, but it seems to  always use 1.18.0. How can I solve it? Thanks u all .

**Comment by palvarezlopez** [comment]
Hi.

Just open your SUMO 1.12.0 (<folder>/bin/sumo-gui.exe), go to file, and select "load simulation".

**Comment by m-kro** [comment]
See [FAQ](https://sumo.dlr.de/docs/FAQ.html#can_i_run_multiple_versions_of_sumo_alongside_each_other)...
