### ISSUE TITLE
Why is traci.person.moveXY() unable to execute?

### ISSUE THREAD

**Issue by callmorn** [eclipse/sumo#13696]
I am unable to execute traci.person.moveXY() in order to move a pedestrian to a specific coordinate after it is generated. Alternatively, I would like to know how to generate a pedestrian at a specified coordinate.

**SUMO-version 1.13:**

**Comment by m-kro** [comment]
Please try this [test example](https://sumo.dlr.de/extractTest.php?path=complex/traci/person/moveToXY/after_creation) of traci.person.moveToXY() to see if this works for you. And please update to the latest SUMO release if possible.
