### ISSUE TITLE
How to judge the front-and-rear relationship between two cars in sumo?

### ISSUE THREAD

**Issue by frankling2020** [eclipse/sumo#13697]
**Basic Setup**
```
Eclipse SUMO sumo Version 1.17.0
Environment: Linux-5.15.0
```

In this investigation, I am using the carFollowModel "Intelligent Driver Model (IDM)" to study traffic accidents in a roundabout, as depicted in the figure provided.

![carfollow](https://github.com/eclipse/sumo/assets/62578647/df70fa20-bea7-4683-9977-10ea5495d8c1)

**Investigation**
To examine the distance between vehicles, I have used the `traci.vehicle.getLeader` function to determine the lead vehicle for each car. I have observed that the distance between the vehicles is consistently equal to the minGap parameter specified for each vehicle type in the given situation. For example, vehicle A is the leading vehicle of vehicle B, but they haven't formed the front-and-rear relationship in the figure. The `traci.vehicle.getLeader` function returns the distance from the ego vehicle's front bumper plus the minGap to the back bumper of the lead vehicle. This implies that the returned distance is always no smaller than the minGap, even if I attempt to increase the likelihood of accidents in this environment.

**Confusion**
My confusion arises from whether the distance between a vehicle and its leading vehicle being larger than the minGap can be universally used as a criterion for determining a front-and-rear relationship between two cars in a roundabout. Furthermore, can this criterion be considered a general rule to judge the front-and-rear relationship of vehicles in all scenarios? If it can't, what can be used as a universal criterion then?

Thanks for your help!

**Comment by m-kro** [comment]
`traci.vehicle.getLeader` will report vehicles crossing the ego route, too (see [this test](https://sumo.dlr.de/extractTest.php?path=complex/traci/vehicle/getLeader)). If you really want to be sure ego and leader vehicles follow each other, you'll have to check their positions / lanes.
