### ISSUE TITLE
libsumo c++

### ISSUE THREAD

**Issue by kikiQuentin** [eclipse/sumo#13705]
I have compiled sumo and put it in the home directory. Following the libsumo c++ tutorial on the official website, it still reports that the libsumo header file cannot be found. I have placed the test.cpp project folder in the home directory as well. Where should I put the test.cpp file in sumo, or what is the structure of the test.cpp project folder, and how should I write CMakeLists?

SUMO-version: 1.18

operating system: ubuntu18.04

**Comment by palvarezlopez** [comment]
hi @kikiQuentin 

Why you don't use the official SUMO uploaded in the linux packet repository?

**Comment by kikiQuentin** [comment]
I followed the Linux Build tutorial and compiled to get SUMO. When I run it, it shows the version as 1.18.

**Comment by kikiQuentin** [comment]
Is there something wrong with my steps? I just want to run the libsumo example successfully. May I ask you what I should do next?

**Comment by palvarezlopez** [comment]
What value had your SUMO_HOME value?

**Comment by kikiQuentin** [comment]
/home/zq/sumo

**Comment by palvarezlopez** [comment]
and in /home/zq/sumo/bin is the file libsumo?

**Comment by kikiQuentin** [comment]
This directory(/home/zq/sumo/bin) contains libsumocpp.so and other similar files.

**Comment by palvarezlopez** [comment]
@kikiQuentin can you write your compiling command? (For example: g++ -o test -std=c++11 -I$SUMO_HOME/src test.cpp -L$SUMO_HOME/bin -lsumocpp
)(

**Comment by kikiQuentin** [comment]
The compiling command is g++ -o test -std=c++11 -I$SUMO_HOME/src test.cpp -L$SUMO_HOME/bin -lsumocpp. Since I just want to run the test.cpp file, the compile command is the same as the tutorial. Should I need to change the compile command here?

**Comment by palvarezlopez** [comment]
@kikiQuentin Thanks. We're going to check it.

**Comment by kikiQuentin** [comment]
I have solved the issue with your help, thanks a lot! But still have the same issue in windows.

**Comment by kikiQuentin** [comment]
I have solved the issue with your help, thanks a lot! But still have the same issue in windows.

How can I use MinGW to compile sumo source code under windows? I've read the answer to the previous issues. MinGW doesn't support compiling sumo, is this issue solved now?

**Comment by palvarezlopez** [comment]
@kikiQuentin no :( Currently you can only compile SUMO in Windows using Visual Studio. You have a free version (Visual Studio Community)
