### ISSUE TITLE
setScale value is not used in flows

### ISSUE THREAD

**Issue by YDLin9784** [eclipse/sumo#13707]
Hi all, 

I am trying to use traci.vehicleType.setScale() to manipulate the density of my flow. so I has this piece of code in my .py:
![image](https://github.com/eclipse/sumo/assets/44907175/6ad52250-eab4-40f6-8f83-28863d4214dc)
That returns "100.0" as the scale, in the meanwhile in my route file I have this :
![image](https://github.com/eclipse/sumo/assets/44907175/6607bd72-4f2c-424b-9cb5-b8d08ba0d3bb)
but when I run simulations, the flow "hdv" is still having 12 vehicles instead of 1,200 as I expected. 
I tried other traci.vehicleType command, seems they are all working except this one. 

Any help would be appreciated!

**Comment by m-kro** [comment]
You have discovered a bug. Getters and setters were implemented in #10161 but the scale value is not checked for updates after the simulation has been initialised. So currently it is not possible but we will fix that.

**Comment by YDLin9784** [comment]
Hi, 

thank you for your information!

Just a follow up question if you don’t mind. Are there other ways to change the flow capacity from the code like the setScale function? I am trying to run multiple simulations with different vehsPerHour of flows.

**Comment by m-kro** [comment]
It may be a bit cumbersome but you can always replicate flows yourself by adding single vehicles (`traci.vehicle.add`). But you are probably better off waiting for the bug fix (expected for today).

**Comment by YDLin9784** [comment]
Thank you for the quick response!
