### ISSUE TITLE
Question Regarding EdgeData and TraCI

### ISSUE THREAD

**Issue by adoreador** [eclipse/sumo#13708]
I'm facing some challenges while using traci for simulation, and I would like to calculate density and speed similar to the edgedata formula. Therefore, I went through previous responses for guidance.
```
        if (edge->getFunction() == SumoXMLEdgeFunc::NORMAL) {
            dev.openTag(SUMO_TAG_EDGE).writeAttr(SUMO_ATTR_ID, edge->getID());
            const double traveltime = edge->getTravelTime(a.getDefaultVehicle(), STEPS2TIME(begin));
            const double speed = edge->getLength() / traveltime;
            const double flow = edge->getFlow(STEPS2TIME(begin));
            dev.writeAttr("traveltime", traveltime);
            dev.writeAttr("speed", edge->getLength() / traveltime);
            dev.writeAttr("entered", flow);
            const double timeGap = STEPS2TIME(end - begin) / flow;
            const double spaceGap = timeGap * speed;
            const double density = 1000.0 / spaceGap;
            const double laneDensity = density / edge->getNumLanes();
            dev.writeAttr(SUMO_ATTR_TRAVELTIME, traveltime);
            dev.writeAttr(SUMO_ATTR_SPEED, speed);
            dev.writeAttr(SUMO_ATTR_ENTERED, flow);
            dev.writeAttr(SUMO_ATTR_DENSITY, density);
            dev.writeAttr(SUMO_ATTR_LANEDENSITY, laneDensity);
```
From the code, I've learned that "flow" essentially represents the “entered” data. Consequently, I'm interested in tracking this aspect in traci, specifically counting the number of vehicles entering road segment E1 from road segment E0 within a 5-second interval (which I've assumed as the frequency). Despite my attempts with various traci commands, I haven't been successful in achieving this. Could you kindly provide me with some guidance on how to approach this?

**Comment by m-kro** [comment]
You can keep track of the vehicles on an edge calling `traci.edge.getLastStepVehicleIDs` repeatedly. Compare the IDs to the ones of the previous call to see which one arrived and which left.

**Comment by adoreador** [comment]
Hello, I believe I have figured out how to calculate the number of vehicles entering the edge, i.e., the value of "entered." However, I've noticed a significant discrepancy in the calculated density. I'm not quite sure what might be causing this disparity. Could you kindly provide some insight and help me understand the potential reasons behind it? Your guidance would be greatly appreciated.
I will now attach my code below.
```
                # Calculate time gap, space gap, and density
                time_gap = flow_interval / total_flow
                traveltime = traci.edge.getTraveltime("E1")
                speed = traci.lane.getLength("E1_0") / traveltime
                space_gap = time_gap * speed
                density = 1000.0 / space_gap
```

**Comment by m-kro** [comment]
Why not use something more simple? You know the length of the edge / lane and the amount of vehicles for every step. Obviously you would need to handle corner cases (only vehicle portion is on the edge of interest), but you can get a density estimate just by dividing the number of vehicles by the edge length (and normalise to the unit you want)...?

**Comment by adoreador** [comment]
Thank you for your response. The method you mentioned was initially my consideration as well. However, I've noticed a significant discrepancy between the results obtained using this estimation method and the data from edgedata. The reason I'm interested in understanding how edgedata calculates its data is because I've achieved better model fitting using the edgedata. That's why I raised this question.

**Comment by adoreador** [comment]
Hello, I retested it again and found that the method you mentioned for multi-lane situations, which was actually my initial thought, turned out to be more effective. Regardless, I appreciate your guidance and assistance.

**Comment by adoreador** [comment]
Hello, I have retested everything once again and found that in the scenario with multiple lanes, the approach you mentioned – which coincidentally aligns with my initial idea – actually results in the least deviation from the edgedata. Regardless, I am sincerely thankful for your response and guidance
