### ISSUE TITLE
Error: tcpip::Socket::recvAndCheck @ recv: peer shutdown

### ISSUE THREAD

**Issue by anthonyKiggundu** [eclipse/sumo#13717]
Hello there,
Trying the following:
`self.sumoBinary = "/usr/bin/sumo-gui"`
 `self.path_to_sumo_config = ".../sumo/tools/2023-05-16-00-00-54/osm.sumocfg"`
  `self.sumoCmd = [self.sumoBinary, "-c", self.path_to_sumo_config]` followed by:
`traci.start(self.sumoCmd)`
This problem is still not solved. I tried downgrading to versions below 1.18.0 but just run into more errors.
Trying to start up the traci server reading from a sumo config.
`Error in sumo -> Simulation started with time: 0.00`.
`Error: tcpip::Socket::recvAndCheck @ recv: peer shutdown`
`Quitting (on error).`
 
After some digging I find the above error raised in the socket.h file.
**1.18.0**

**ubuntu 20-focal:**

**Comment by m-kro** [comment]
Can you please load the sumocfg file directly in sumo-gui and look for some error message?

**Comment by m-kro** [comment]
Do you call any TraCI functions other than the stated above? Are there more messages immediately before the error message?

**Comment by nightring** [comment]
Using Traci opening sumocfg seems to require executing "traci.simulationStep()" for each step. Without this command, this error will occur.

**Comment by namdre** [comment]
The error will also occur if you do not call traci.close() at the end of your python code.
