### ISSUE TITLE
Mark conflicting points in the path at the intersection

### ISSUE THREAD

**Issue by SunTianzhHERE** [eclipse/sumo#13712]
Hi, how can I mark conflicting points in the path when two vehicles are passing the intersection at the same time ? Like this 
![Snipaste_2023-08-15_10-25-27](https://github.com/eclipse/sumo/assets/96806032/230b9acc-a30d-4767-b387-e8cc63b000e6)

**Comment by m-kro** [comment]
Do you want to enumerate all the possible conflict points or do you want to know which conflict points are actually critical during the simulation? For the latter we have the [SSM device](https://sumo.dlr.de/docs/Simulation/Output/SSM_Device.html) output. 

To enumerate all the points, you can use some helpers from our [sumolib](https://sumo.dlr.de/docs/Tools/Sumolib.html) tools:

- load the network file using `sumolib.net.readNet`
- get the shapes of internal lanes with `sumolib.net.lane.getShape`
- test for intersections between two of them using the `sumolib.geomhelper.intersectsLineSegment` function
