### ISSUE TITLE
Vehicles don't overtake leader controlled by TraCI

### ISSUE THREAD

**Issue by m-kro** [eclipse/sumo#13710]
Reported on the [mailing list](https://www.eclipse.org/lists/sumo-user/msg13290.html). Vehicles travel on a lane with no vehicle on the opposite neighbour lane when the leader vehicle is stopped by `traci.vehicle.slowDown` and kept at the stand-still position by `traci.vehicle.setSpeed(vehID, 0)`. 
The following vehicles will stop behind it and not try to overtake, which they do if the leader vehicle stops at a regular stop (either defined in XML or through `traci.vehicle.setStop`).

**Comment by m-kro** [comment]
This overtaking case is catched by conditions introduced with #10360 , specifically this time threshold:

https://github.com/eclipse/sumo/blob/f01a34745f91df2e29f5be3ed698e81b0f91130c/src/microsim/MSLaneChanger.cpp#L57

**Comment by m-kro** [comment]
Seems to work, so let's close the issue

**Comment by behrisch** [comment]
@m-kro can we get a test from the user scenario (or your own) here?
