### ISSUE TITLE
length with traci.simulation.findRoute()

### ISSUE THREAD

**Issue by claudiacbh** [eclipse/sumo#13715]
Hello!

The findRoute function returns a Stage object that gives the edges of the path, the "length", etc.

Could you help me with the following questions please:

i) what distance is taken to calculate the length in the junctions (internal edges), since it has some possible lanes?

*If possible, upload an example that shows your problem.*

For instance:
The result of traci.simulation.findRoute('-E1', '-E0') is:

ruta Stage(type=3, edges=('-E1', '-E0'), travelTime=13.55858417402557, cost=13.55858417402557, length=178.03, depart=INVALID, departPos=INVALID, arrivalPos=INVALID)

When comparing with the real data of the network we have:

    <edge id="-E0" from="J1" to="J0" priority="-1">
        <lane id="-E0_0" index="0" allow="pedestrian" speed="13.89" length="111.84" width="2.00" shape="104.80,87.77 -7.04,87.57"/>
        <lane id="-E0_1" index="1" disallow="pedestrian" speed="13.89" length="111.84" shape="104.81,85.17 -7.04,84.97"/>
    </edge>
    <edge id="-E1" from="J2" to="J1" priority="-1">
        <lane id="-E1_0" index="0" allow="pedestrian" speed="13.89" length="55.39" width="2.00" shape="115.50,23.21 114.22,78.59"/>
        <lane id="-E1_1" index="1" disallow="pedestrian" speed="13.89" length="55.39" shape="112.90,23.15 111.62,78.53"/>
    </edge>

    <edge id=":J1_0" function="internal">
        <lane id=":J1_0_0" index="0" disallow="pedestrian" speed="7.11" length="10.80" shape="111.62,78.53 111.13,81.44 109.84,83.52 107.73,84.76 104.81,85.17"/>
    </edge>
    <edge id=":J1_1" function="internal">
        <lane id=":J1_1_0" index="0" disallow="pedestrian" speed="5.37" length="5.72" shape="104.81,81.97 106.36,81.75 107.48,81.09 108.16,80.00 108.42,78.45"/>
    </edge>

Consequently I get a length of:

172.6 (with "J1_1" ) or 174.34 (":J1_0)

ii) Could you tell me what I need to configure the function to obtain the same value as by hand? Or what length am I not considering that is causing this difference?

**SUMO-version:**
SUMO 1.18.0

**operating system:**
Windows 11

**Comment by m-kro** [comment]
Actually the sum of lane lengths amounts to 178.03 with ":J1_0", so there is no problem... The algorithm takes the first internal edge it finds for connecting two sequential edges of the route which probably coincides with the order in the network file.
