### ISSUE TITLE
How to generate crossings correctly (or close to reality as possible) from OpenStreetMap?

### ISSUE THREAD

**Issue by maisyhoang** [eclipse/sumo#13725]
Question 1:
What netconvert options should I use to generate pedestrian crossings closest to reality (not using .guess options)?  I tried ----osm.sidewalks and --osm.crossings but there seems to be some issue. For example, in this case one of the crossing seems to be missing. Also I think that some of the pedestrian area around the intersection are redundant here. 

![image](https://github.com/eclipse/sumo/assets/30378093/c84f9605-5213-485a-9466-9113610fc078)
![image](https://github.com/eclipse/sumo/assets/30378093/9bb7aafb-e42e-4613-af6f-8ebecc2c4356)

Is there any option to make pedestrian walkway only one lane instead of two lanes in parralel?

My netconvert command is: 
> netconvert --osm-files ./map.osm -o sumo.net.xml \
           --geometry.remove \
           --ramps.guess \
           --junctions.join \
           --tls.guess-signals \
           --tls.discard-simple \
           --tls.join \
           --tls.default-type actuated \
           --junctions.internal-link-detail 20 \
           --junctions.corner-detail 20 \
           --output.street-names true\
           --output.original-names \
           --osm.sidewalks true \
           --osm.crossings true \
           --type-files osmNetconvert.typ.xml,osmNetconvertUrbanDe.typ.xml,osmNetconvertPedestrians.typ.xml

Question 2:
What type of OSM tags are needed for normal crossing vs zebra crossing generation in netconvert?

Here is my overpass query (https://overpass-turbo.eu/) which finds a few nodes that is ["highway"="*"] and ["crossing"="marked"], but I dont find any zebra crossing in sumo-gui.

` [out:json][timeout:50];
(
  node["highway"="*"];node["crossing"="marked"](60.15547501163754,24.75944995880127,60.165318995436905,24.779255390167233);
);
out center;`

***
The whole simulation files is attached below. original OSM map is map.osm. The simulation file to use with sumo-gui is experiment.sumocfg. The script I use to generate my scenario is setup_scenario.sh.

***

SUMO-version: 1.18.0
Operating system: Ubuntu 22.04

[scenario_6.zip](https://github.com/eclipse/sumo/files/12377835/scenario_6.zip)

**Comment by bcoueraud87** [comment]
Hi Hoang Mai,

Zebra crossings are known to be problematic as far as I know. I used the osmWebWizard tool and it gave good results (as far as I understand):

![image](https://github.com/eclipse/sumo/assets/56519579/e3db7668-4a26-467a-bd26-56aa1d8b8473)

Looking at the tool's code, I see that the `--osm.sidewalks` and `--crossings.guess` netconvert options were used, so the guesses were quite good actually. You can actually modify this geometry in netedit, as a further step. Also in netedit using the selection tool and the inspection tool, you can edit the number of pedestrian lanes. But I guess you will use SUMO's pedestrian [striping model](https://sumo.dlr.de/docs/Simulation/Pedestrians.html#model_striping) (the one by default) and in this case it could be perhaps a good idea to keep one lane for movement in one direction, one lane for the other direction.

And just in case you didn't have that part of the documention yet: https://sumo.dlr.de/docs/Simulation/Pedestrians.html#generating_a_network_with_crossings_and_walkingareas
