### ISSUE TITLE
traci.exceptions.TraCIException: Invalid acceleration.

### ISSUE THREAD

**Issue by SunTianzhHERE** [eclipse/sumo#13723]
Hi, I want to set my vehicle acceleration, but sumo reminded me of traci.exceptions.TraCIException: Invalid acceleration.
Whats wrong?

**Comment by m-kro** [comment]
Acceleration values have to be greater than 0.

**Comment by m-kro** [comment]
Do you intend to change the acceleration capability of a single vehicle, then use [setAccel](https://sumo.dlr.de/pydoc/traci._vehicle.html#VehicleDomain-setAccel):
`traci.vehicle.setAccel(vehID, accel)` 
Similar [for a vehicle type](https://sumo.dlr.de/pydoc/traci._vehicletype.html#VTypeDomain-setAccel):
`traci.vehicletype.setAccel(typeID, accel)`

Or do you want to influence the acceleration of a single vehicle temporarily, then use [setAcceleration](https://sumo.dlr.de/pydoc/traci._vehicle.html#VehicleDomain-setAcceleration):
`traci.vehicle.setAcceleration(vehID, acceleration, duration)`

**Comment by m-kro** [comment]
`traci.vehicle.setAcceleration` was introduced in SUMO v.1.13. Please update (preferably to the latest version v.1.18 if you don't have particular objections).

**Comment by SunTianzhHERE** [comment]
Thanks  a lot
