### ISSUE TITLE
Set car-following model

### ISSUE THREAD

**Issue by SunTianzhHERE** [eclipse/sumo#13727]
Hi, I have three questions.
First, if I dont set flow's car-following model, is the default model Krauss Model?
Second, in the first question's situation, if I change flow's speed and accerleration using traci, is it reasonable？
Third , when I have set the vehicle's speed using traci.vehicle.setSpeed(), why doesnt it change to the set speed？ It seems to change in acceleration with every step of simulation time.

**Comment by SunTianzhHERE** [comment]
you mean speed can be changed directky after setting? It does not change gradually according to the acceleration？

**Comment by m-kro** [comment]
Not if you use `traci.vehicle.setSpeed`. If you want sumo to accelerate to a certain speed, look at `traci.vehicle.slowDown` (see [reference](https://sumo.dlr.de/pydoc/traci._vehicle.html#VehicleDomain-slowDown), despite the name, it works both for getting slower and faster).
