### ISSUE TITLE
distance on sumo how ? 

### ISSUE THREAD

**Issue by Y-AMDIAZ** [eclipse/sumo#13737]
hi, I want to calculate the distance on Sumo that a vehicle did from E12 to E34 for example, and there are someone who know how?

**Comment by angelobanse** [comment]
You can add a TripInfo device to the vehicle: https://sumo.dlr.de/docs/Simulation/Output/TripInfo.html#output_only_for_selected_vehicles_or_vehicle_types
If you define one of those points as depart and the other as arrival, the resulting `routeLength` should be the value you are looking for.

**Comment by angelobanse** [comment]
You could also use the [vehicle route output](https://sumo.dlr.de/docs/Simulation/Output/VehRoutes.html) and take a look at the list of edges the vehicle drove (between the two points), and add their lengths.
