### ISSUE TITLE
Question about randomtrips.py

### ISSUE THREAD

**Issue by zhangm269** [eclipse/sumo#13743]
Hello, I have a question about randomtrip.py as follows:

1. I have a 4*4 road network and I want to generate random traffic flow by randomtrips.py . 
2. The random traffic flow needs to satisfy that the east-west traffic flow is much larger than the north-south traffic flow, as if east-west is the main direction for commuting in real life. How to do it by randomtrips.py?

Thank you very much for your answer!
**SUMO-version:**
1.17.0
**operating system:**
windows10

**Comment by angelobanse** [comment]
You can make use of the [edge probabilities](https://sumo.dlr.de/docs/Tools/Trip.html#edge_probabilities) by giving each edge a custom value, which will be taken into account by randomTrips.py  (`--edge-param EDGEPARAM`).

Or [customized weights](https://sumo.dlr.de/docs/Tools/Trip.html#customized_weights). You need to define the edge probabilities in three files (.src.xml, .dst.xml, .via.xml) and call randomTrips.py with the `--weights-prefix` option.
