### ISSUE TITLE
Where is config.h file?

### ISSUE THREAD

**Issue by thinker310** [eclipse/sumo#13745]
Hello, I wonder where is the file path of <config.h> as shown in the figure below:
![image](https://github.com/eclipse/sumo/assets/62609436/e9266c8a-2186-4f21-b622-e8488a20be62)
I want to read details in <config.h> file. Could you help me?
Thank you in advance!

**Comment by palvarezlopez** [comment]
Hello. The config file is in the subfolder "src" of the folder in wich you configured the CMake build.
