### ISSUE TITLE
sumo emission CO2 erreur 

### ISSUE THREAD

**Issue by Y-AMDIAZ** [eclipse/sumo#13752]
just whene I want to calculate the emission CO2 it gives that 
<img width="578" alt="image" src="https://github.com/eclipse/sumo/assets/129278941/774bcaa8-86cf-41b4-90ac-5c06ab9edd4a">

**Comment by angelobanse** [comment]
The configuration file should be `final.sumocfg` instead of `final.sumo.cfg`
