### ISSUE TITLE
About routeDistribution

### ISSUE THREAD

**Issue by Clown1206** [eclipse/sumo#13754]
Add your issue description here.
I'm using the trip file that has been iterated through duaIterate.py for simulation, but I get the same result every time I run it, what is the reason for this?(Each path has a probability of being chosen, and the results of the run are not necessarily the same every time?)
*If possible, upload an example that shows your problem.*
![image](https://github.com/eclipse/sumo/assets/59904738/a5a800c9-90f7-468d-8448-4e17a9058702)
![image](https://github.com/eclipse/sumo/assets/59904738/6cf69b87-de5a-464e-b0f9-43056124224a)

**SUMO-version:**
1.16
**operating system:**
win 10

**Comment by palvarezlopez** [comment]
Hi @Clown1206 . Try to set a different seed in every simulation enabling option --random (https://sumo.dlr.de/docs/sumo.html)
