### ISSUE TITLE
A Problem on the Minimum Speed Threshold

### ISSUE THREAD

**Issue by zhangm269** [eclipse/sumo#13756]
In sumo, by default, a vehicle with a speed lower than **0.1m/s** is in a stopped state, and related functions are also based on this for data statistics, such as _getLastStepHaltingNumber (self, edgeID)._ 

Can this threshold be **manually adjusted,** such as setting it to 3m/s, while affecting the corresponding functions?

**Comment by behrisch** [comment]
You can change this for detectors such as the [lanearea](https://sumo.dlr.de/docs/Simulation/Output/Lanearea_Detectors_%28E2%29.html) and the [multientryexit](https://sumo.dlr.de/docs/Simulation/Output/Multi-Entry-Exit_Detectors_%28E3%29.html) detectors but not in general.
