### ISSUE TITLE
placement of road in GUI 

### ISSUE THREAD

**Issue by Nitinyerra** [eclipse/sumo#13773]
Hi,
It is just a question, which would help me with my work.
I would like to understand how this UI coordinates are considering to drop that road 

![image](https://github.com/eclipse/sumo/assets/140040498/c78e5a47-1a71-43df-b4cb-c39e07f1db88)

1.18.0

Windows

Thanks in Advance!!

**Comment by Nitinyerra** [comment]
also is there ay other way to get the screenshot of the road scenario with considering the addtional space which was used in the screenshot added?

**Comment by Nitinyerra** [comment]
or you can also provide with the file(or section of code) which is responsible for creating the road in gui

**Comment by angelobanse** [comment]
I don't quite understand your question.

If there is no projection defined, the (x,y) coordinate system is used.
The viewport dialog you show in the screenshot is used to navigate/move the center of the view. Z and Zoom change the same in this case, and A refers to angle.

If you want to move the edges/nodes, go to the Inspect mode (Shortcut I), click on an element and modify its `pos` property.

--
The screenshot (or "snapshot") feature saves the entire view. If you only want to have the elements, I recommend to use that feature but save the image file as a vector image (.svg). This way you can easily manipulate the elements / roads of the resulting image in a program such as Inkscape.

**Comment by behrisch** [comment]
Please add another comment if you feel your question has not been answered
