### ISSUE TITLE
vehicle speed exceeds edge speed

### ISSUE THREAD

**Issue by alon910** [eclipse/sumo#13777]
Hi everyone,

I am running a simulation and I see that the vehicle speed in an edge exceeds the speed of the edge

I was wondering if someone also had this issue and I can enforce the speed limit of the edge to the vehicles?

Thanks!

![Selection_1514](https://github.com/eclipse/sumo/assets/7622761/715139c5-f80f-4cb0-b479-aa41cde7f0a6)
![Selection_1513](https://github.com/eclipse/sumo/assets/7622761/8075622b-0001-42ca-8ffd-b4fa21faabc5)

**SUMO-version: 1.13.0

**operating system: Linux

**Comment by palvarezlopez** [comment]
Hi @alon910

The speed-attribute is usually defined for edges but may also differ among the lanes of the same edge. It models the legal speed limit.

https://sumo.dlr.de/docs/Simulation/VehicleSpeed.html#edgelane_speed_and_speedfactor

**Comment by alon910** [comment]
@palvarezlopez 
All lanes in this edge has the same speed
this is not the issue

also I tried various types of configs for speed - attaching a screenshot

![image](https://github.com/eclipse/sumo/assets/7622761/5379ec3e-6b78-405c-b70f-48789c9cf49f)

**Comment by behrisch** [comment]
SUMO vehicles are allowed to speed, see https://sumo.dlr.de/docs/Simulation/VehicleSpeed.html#edgelane_speed_and_speedfactor. If you don't want that use `--default.speeddev 0`

**Comment by alon910** [comment]
Thanks @behrisch - I will try it

if I understand correctly, even when vehicles can go faster than the speed limit, the stdv should be only up to 0.1

so it's unlikely they will go from 13.89 --> 15.61

**Comment by behrisch** [comment]
It is somehow a relative standard deviation because it is applied to the speedFactor and not to the speed itself. So 15.61 is still quite likely.
