### ISSUE TITLE
Chinese characters not being rendered in language toggle menu

### ISSUE THREAD

**Issue by vijay-jaisankar** [eclipse/sumo#13780]
On navigating to the language toggle menu on SUMO, it was observed that the Chinese(`zh`) characters were not being rendered. This issue is permeated after restarting SUMO as well, most of the characters on screen are not rendered.
![Chinese Characters not being rendered](https://github.com/eclipse/sumo/assets/56185979/af46f12e-e48e-4f00-b15a-0bfa13f7eadb)

**SUMO-version: 1.18.0**

**Operating system:  Zorin OS 16.2**

**Comment by angelobanse** [comment]
This is a known issue, and also affects macOS.

**Comment by angelobanse** [comment]
Maybe try this out: https://sumo.dlr.de/docs/FAQ.html#missing_characters_in_parameter_dialogs_ie_chinese_street_names_on_linux

**Comment by vijay-jaisankar** [comment]
> Maybe try this out: https://sumo.dlr.de/docs/FAQ.html#missing_characters_in_parameter_dialogs_ie_chinese_street_names_on_linux

Thanks for this, `noto-fonts` fixed the issue for me.
