### ISSUE TITLE
Excessive vehicles are generated than expected when vTypeDistributions sharing types

### ISSUE THREAD

**Issue by yunpangfloetteroed** [eclipse/sumo#13786]
The number of the generated vehicles does not correspond to the probability of vTypeDistribution in the given multiple vTypeDistributions.   It seems more vehilces are generated than expected. 

e.g. 
expected: 10% BEV  --> generated: 13.4%;
expected: 20% BEV  --> generated: 25.7%;
expected: 30% BEV  --> generated: 37.9%;
expected: 50% BEV  --> generated: 58.7%;

**SUMO-version:**
V1_18_0+0508-22637e2f52c
**operating system:**
Linux

**Comment by yunpangfloetteroed** [comment]
The related ticket is #12799.

**Comment by behrisch** [comment]
a missing normalization is the reason
