### ISSUE TITLE
Sumo-gui not opening after generating scenario in OSM Web Wizard 

### ISSUE THREAD

**Issue by njakhar88** [eclipse/sumo#13787]
I open PyCharm and launch osmwebwizard.py. This launches the OSM Web Wizard. After selection of parameters, I click on Generate Scenario and the comman terminal in Pycharm shows the following errors:

Building scenario in 'C:\sumo-win64extra-1.18.0\sumo-1.18.0\tools\2023-09-05-23-42-54'.
Downloading map data
200 OK
Converting map data
Warning: Value of key 'maxspeed:type' is not numeric ('urban') in edge '250957628'.
Warning: No way found for reference '828550385' in relation '11177277'
Warning: Ignoring restriction relation '11177277' with unknown to-way.
Warning: No way found for reference '813383809' in relation '11177279'
Warning: Ignoring restriction relation '11177279' with unknown to-way.
Warning: No way found for reference '828550385' in relation '11177281'
Warning: Ignoring restriction relation '11177281' with unknown from-way.
Warning: No way found for reference '813383809' in relation '11177284'
Warning: Ignoring restriction relation '11177284' with unknown from-way.
Warning: No way found for reference '1002703400' in relation '13445817'
Warning: Ignoring restriction relation '13445817' with unknown from-way.
Warning: Ignoring restriction relation '13445817' with unknown to-way.
Warning: Ignoring restriction relation '13445818' with unknown from-way.
Warning: Ignoring restriction relation '13445818' with unknown to-way.
Warning: Not joining junctions 2208493171,2208493173 (parallel incoming 263790600,813965759#1).
Warning: Not joining junctions 10228384254,2208493184,2208493185 (parallel incoming 233840269#15,263790605).
Warning: Reducing junction cluster 10239639314,2539465615,2539465622 (parallel outgoing -246996019#0,246996047#1).
Warning: Not joining junctions 1396823572,2208385014 (parallel incoming 210788741,815893768#1).
Warning: Not joining junctions 10239760951,2208385053 (parallel outgoing 125860931#13,210788877).
Warning: Not joining junctions 10243910712,10243910714 (only 1 edge within and no cross-traffic).
Warning: Reducing junction cluster 10854304018,1430380275,691258341 (parallel outgoing -827014029#2,828550388#1).
Warning: Reducing junction cluster 1226577998,2421647003,2496146804,2496146819,2496146820 (parallel outgoing 233840277#8,242052533#0).
Warning: Reducing junction cluster 1226578539,2015020205,2442374680,2442374683,2442391862,2442391863,2442391864,2442391865 (6 incoming edges).
Warning: Reducing junction cluster 1226578724,2015020200,2442374638,2442374649,2442391857,2442391858,2442391859,2442391860 (6 incoming edges).
Warning: Ambiguity in turnarounds computation at junction '10239636234'.
Warning: Ambiguity in turnarounds computation at junction '10244086949'.
Warning: Ambiguity in turnarounds computation at junction '6181070093'.
Warning: Ambiguity in turnarounds computation at junction '6771581414'.
Warning: Ambiguity in turnarounds computation at junction '7171517507'.
Warning: Found angle of 108.88 degrees at edge '-106621432#0', segment 0.
Warning: Found angle of 101.34 degrees at edge '-106621448#0', segment 0.
Warning: Found sharp turn with radius 8.75 at the start of edge '-106621994#1'.
Warning: Found sharp turn with radius 7.38 at the start of edge '-1118295003'.
Warning: Found sharp turn with radius 4.59 at the start of edge '-1118303433#0'.
Warning: Found sharp turn with radius 8.73 at the end of edge '-1118341175'.
Warning: Found sharp turn with radius 6.68 at the start of edge '-1118346625'.
Warning: Found sharp turn with radius 4.47 at the start of edge '-1118635262'.
Warning: Found sharp turn with radius 4.67 at the end of edge '-1118648817'.
Warning: Found sharp turn with radius 6.91 at the end of edge '-1118817362#2'.
Warning: Found angle of 102.80 degrees at edge '-1119528191#3', segment 0.
Warning: Found angle of 124.60 degrees at edge '-1119528192', segment 0.
Warning: Found angle of 113.00 degrees at edge '-1119543488#2', segment 0.
Warning: Found sharp turn with radius 7.02 at the end of edge '-1119545963#1'.
Warning: Found sharp turn with radius 4.48 at the end of edge '-1119546431'.
Warning: The traffic light '1396782776' does not control any links; it will not be build.
Warning: Could not build program '0' for traffic light '1396782776'
Warning: Minor green from edge '829087179#0' to edge '829087178#0' exceeds 19.44m/s. Maybe a left-turn lane is missing.
Warning: Minor green from edge '615466559#1' to edge '567727146' exceeds 19.44m/s. Maybe a left-turn lane is missing.
Warning: Minor green from edge '22841785#0' to edge '568077185' exceeds 19.44m/s. Maybe a left-turn lane is missing.
Warning: Minor green from edge '250957619' to edge '615466559#4' exceeds 19.44m/s. Maybe a left-turn lane is missing.
Warning: Minor green from edge '250300550' to edge '22841785#2' exceeds 19.44m/s. Maybe a left-turn lane is missing.
Warning: Speed of straight connection '233840269#16_0->233840269#17_0' reduced by 16.08 due to turning radius of 24.90 (length=6.40, angle=30.21).
Warning: Speed of straight connection '233840269#16_1->233840269#17_1' reduced by 14.92 due to turning radius of 30.08 (length=7.77, angle=30.21).
Warning: Speed of straight connection '253976045#5_1->253976045#6_1' reduced by 22.68 due to turning radius of 4.72 (length=11.28, angle=179.74).
Warning: Speed of straight connection '106621994#1_0->106621994#2_0' reduced by 10.77 due to turning radius of 23.83 (length=9.36, angle=38.29).
Warning: Speed of straight connection '-106621994#2_0->-106621994#1_0' reduced by 10.65 due to turning radius of 24.34 (length=9.57, angle=38.29).
Warning: Connection '240145849#1_0->-1118363078_0' is only 0.04m short.
Warning: 16 total messages of type: Ambiguity in turnarounds computation at junction '%'.
Warning: 44 total messages of type: Found angle of % degrees at edge '%', segment %.
Warning: 49 total messages of type: Found sharp turn with radius % at the end of edge '%'.
Warning: 66 total messages of type: Found sharp turn with radius % at the start of edge '%'.
Warning: 77 total messages of type: Minor green from edge '%' to edge '%' exceeds %m/s. Maybe a left-turn lane is missing.
Warning: 6 total messages of type: No way found for reference '%' in relation '%'
Warning: 49 total messages of type: Not joining junctions % (%).
Warning: 8 total messages of type: Reducing junction cluster % (%).
Warning: 170 total messages of type: Speed of % connection '%' reduced by % due to turning radius of % (length=%, angle=%).
Success.
Processing Bicycles
Success.
Success.
Processing Bus
Success.
Success.
Processing Motorcycles
Warning: no trip found after 100 tries
Success.
Success.
Processing Cars
Success.
Success.
Processing Urban Trains
Traceback (most recent call last):
  File "C:\sumo-win64extra-1.18.0\sumo-1.18.0\tools\osmWebWizard.py", line 506, in build
    builder.build()
  File "C:\sumo-win64extra-1.18.0\sumo-1.18.0\tools\osmWebWizard.py", line 336, in build
    randomTrips.main(randomTrips.get_options(options))
  File "C:\sumo-win64extra-1.18.0\sumo-1.18.0\tools\randomTrips.py", line 230, in get_options
    options.period = [3600.0 / rate for rate in options.insertionRate]
  File "C:\sumo-win64extra-1.18.0\sumo-1.18.0\tools\randomTrips.py", line 230, in <listcomp>
    options.period = [3600.0 / rate for rate in options.insertionRate]
ZeroDivisionError: float division by zero

Recovering
Recovering
Recovering

**SUMO-version:1.18.0

**operating system: i7 , RAM - 8 GB, 64-bit operating system

**Comment by behrisch** [comment]
It looks like you entered 0 in the count field for urban trains. Please use rather the checkbox to disable them. But you are right, the script should not crash on that error.
