### ISSUE TITLE
Multiple traffic light program in long simulations

### ISSUE THREAD

**Issue by mfsen** [eclipse/sumo#13796]
Hi I want to make long simulations like 2 or 3 hours or more. In the simulation how can I set changing traffic light program. For example in the first hour the junction should use program 1 and the rest it should use program 2. Can you help me with that?

**Comment by robertalms** [comment]
Have a look here: [doc](https://sumo.dlr.de/docs/Simulation/Traffic_Lights.html#defining_program_switch_times_and_procedure)
