### ISSUE TITLE
Modifying the "extension" Parameter 

### ISSUE THREAD

**Issue by claudiacbh** [eclipse/sumo#13812]
Hi!!

I'm looking for guidance on how to change the "extension" parameter in a running simulation. I've noticed the existence of the setBusStop function, which allows to modify the "duration" and "until" parameters. 

Is there an alternative function that accomplishes the same task, but for the "extension" parameter? 

Thank you!

**SUMO-version:**
SUMO 1.18.0

**operating system:**
Windows 11

**Comment by m-kro** [comment]
You can use `traci.vehicle.setStopParameter` (see [ref](https://sumo.dlr.de/pydoc/traci._vehicle.html#VehicleDomain-setStopParameter)) using "extension" as param. Use `traci.vehicle.getNextStops` (see [ref](https://sumo.dlr.de/pydoc/traci._vehicle.html#VehicleDomain-getNextStops)) to know which stop index to provide.
