### ISSUE TITLE
fix state of random number generation when loading state (trac #1418)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#1418]
* the current state of the RNG should be saved
* we need to watch out on parsing the route files and (re-)creating the vehicles

Migrated from http://sumo.dlr.de/ticket/1418
```json
{
    "status": "new", 
    "changetime": "2014-11-04T14:15:09Z", 
    "description": "* the current state of the RNG should be saved\n* we need to watch out on parsing the route files and (re-)creating the vehicles", 
    "reporter": "behrisch", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1415110509864409", 
    "component": "simulation data input", 
    "summary": "fix state of random number generation when loading state", 
    "priority": "major", 
    "keywords": "", 
    "time": "2014-08-29T12:50:37Z", 
    "milestone": "1.0.0", 
    "owner": "", 
    "type": "defect"
}
```

**Comment by namdre** [comment]
saving the state for 6 rngs takes about 40kb.

**Comment by namdre** [comment]
definitely needs tests because there might be some additional calls while loading the vehicles from the state that desynchronize the loaded rng.

**Comment by namdre** [comment]
by default the state takes 400kb+ due to the 64 lane-rngs. To reduce this, a lower value for **--thread-rngs** can be set.
We may consider storing the number of rng calls and avoid saving rngs that were never called.

**Comment by behrisch** [comment]
If we keep track of rng calls we could also consider saving the number calls and rather "redo" the calls on loading (if they are below some threshold).

**Comment by namdre** [comment]
Then we need to store the seed value as well.

**Comment by behrisch** [comment]
Of course but should still be less than 6kb per rng :-)
