### ISSUE TITLE
add new handler for poi and polygon files (trac #1668)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#1668]
PO is the common prefix of POIs and polygons
sumo option --po-files bla.po.xml
POHandler 

this handler can use the <location> element for remapping polygons while loading.

Migrated from http://sumo.dlr.de/ticket/1668
```json
{
    "status": "new", 
    "changetime": "2015-08-24T06:21:17Z", 
    "description": "PO is the common prefix of POIs and polygons\nsumo option --po-files bla.po.xml\nPOHandler \n\nthis handler can use the <location> element for remapping polygons while loading.", 
    "reporter": "namdre", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1440397277196217", 
    "component": "simulation data input", 
    "summary": "add new handler for poi and polygon files", 
    "priority": "minor", 
    "keywords": "", 
    "time": "2015-03-09T07:58:53Z", 
    "milestone": "1.1.0", 
    "owner": "", 
    "type": "enhancement"
}
```

**Comment by palvarezlopez** [comment]
@namdre Does this ticket still make sense? (due new AdditionalHandler)

**Comment by namdre** [comment]
No it doesn't. All the more because we also have src/shapes/ShapeHandler.py
It makes sense to have this as a separate thing because polyconvert also loads shapes but no additionals.
Eventually we can add handlers/ShapeHandler (which AdditionalHandler can inherit from) and let polyconvert use this.
