### ISSUE TITLE
make cooperative behavior on multi-lane roundabouts smarter (trac #1807)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#1807]
currently the decision for using an inner lane is taken based on the number of edges to the target. It would be better to base this on 
* distance (taking into account internal lanes) 
* the number of exits before the own roundabout exit

And generally (not just at roundabouts) the decision for back-and-forth changes should depend on:
* the duration for the lane changing manoeuvre (in case of continuous lane changing)
* the length of the vehicle (which makes lane-changing more difficult in dense traffic)

In iTETRIS_acosta, jamming occurs because vehicles use the inner lane where they should not.

Migrated from http://sumo.dlr.de/ticket/1807
```json
{
    "status": "new", 
    "changetime": "2017-01-31T20:26:30Z", 
    "description": "currently the decision for using an inner lane is taken based on the number of edges to the target. It would be better to base this on \n* distance (taking into account internal lanes) \n* the number of exits before the own roundabout exit\n\nAnd generally (not just at roundabouts) the decision for back-and-forth changes should depend on:\n* the duration for the lane changing manoeuvre (in case of continuous lane changing)\n* the length of the vehicle (which makes lane-changing more difficult in dense traffic)\n\n\n\n\nIn iTETRIS_acosta, jamming occurs because vehicles use the inner lane where they should not.", 
    "reporter": "namdre", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1485894390293153", 
    "component": "microsim - lane change", 
    "summary": "make cooperative behavior on multi-lane roundabouts smarter", 
    "priority": "major", 
    "keywords": "", 
    "time": "2015-05-21T10:24:44Z", 
    "milestone": "1.1.0", 
    "owner": "", 
    "type": "enhancement"
}
```

**Comment by namdre** [comment]
distance and number of exist are taken into account in [c89681b5b9c83b30bb8974814ba80d2ad3c0a6b6]
