### ISSUE TITLE
setting uniform lane color does not work in OSG-view (trac #1818)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#1818]
parsing it from gui settings has no effect, see the game as an example

Migrated from http://sumo.dlr.de/ticket/1818
```json
{
    "status": "new", 
    "changetime": "2015-08-21T11:47:44Z", 
    "description": "parsing it from gui settings has no effect, see the game as an example", 
    "reporter": "behrisch", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1440157664426514", 
    "component": "simulation gui (GUISIM)", 
    "summary": "setting uniform lane color for 3D does not work", 
    "priority": "major", 
    "keywords": "", 
    "time": "2015-06-11T07:52:37Z", 
    "milestone": "1.0.0", 
    "owner": "", 
    "type": "defect"
}
```

**Comment by passengerxuhongli** [comment]
how can i switch OSG-view in sumo version0.32?  it does not work in configuration file, part of contents in *.sumocfg are as follow：
<guionly> 
		<OSG-view value="false"/>
		<gui-settings-file value="settings.xml"/>
		<start value="true"/>
		<quit-on-end value="true"/>
</guionly>

**Comment by namdre** [comment]
if sumo was built with osg support (see sumo-gui Menu->Help->About) you can use `<osg-view value="true"/>` However, you can also open an osg-view from sumo-gui by clicking on the rightmost icon in the icon bar right of the delay control

**Comment by passengerxuhongli** [comment]
while when i used <osg-view value="true"/> , sumo-gui.exe say there are errors: no option "osg-view"

**Comment by namdre** [comment]
then your version of sumo was not compiled with osg support. Use http://sumo.dlr.de/daily/sumo-msvc12extrax64-git.zip instead.
