### ISSUE TITLE
too much setRequest at roundabout (trac #1847)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#1847]
Currently, a vehicle approaching a roundabout may already block another vehicle which is approaching the roundabout downstream. 
In reality, the latter vehicle would drive (safe in the knowledge that the other vehicle may have to stop anyway).

One possible solution is to limit the requests for later links after slowing down for approaching a minor link.

Migrated from http://sumo.dlr.de/ticket/1847
```json
{
    "status": "assigned", 
    "changetime": "2016-10-14T11:17:07Z", 
    "description": "Currently, a vehicle approaching a roundabout may already block another vehicle which is approaching the roundabout downstream. \nIn reality, the latter vehicle would drive (safe in the knowledge that the other vehicle may have to stop anyway).\n\nOne possible solution is to limit the requests for later links after slowing down for approaching a minor link.", 
    "reporter": "namdre", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1476443827739308", 
    "component": "microsim - junctions", 
    "summary": "too much setRequest at roundabout", 
    "priority": "major", 
    "keywords": "", 
    "time": "2015-08-18T06:17:55Z", 
    "milestone": "1.0.0", 
    "owner": "namdre", 
    "type": "defect"
}
```

**Comment by namdre** [comment]
needs another test for the situation described in the earlier comment

**Comment by namdre** [comment]
The effect is only present for a short time when the blocked outside-vehicle has not yet aborted it's request.
