### ISSUE TITLE
Check IE /Chrome support of osmWebWizard.py (trac #1945)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#1945]
There were some issues in the tutorial

Migrated from http://sumo.dlr.de/ticket/1945
```json
{
    "status": "new", 
    "changetime": "2015-12-02T10:08:16Z", 
    "description": "There were some issues in the tutorial", 
    "reporter": "behrisch", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1449050896907159", 
    "component": "tools (python)", 
    "summary": "Check IE /Chrome support of server.py", 
    "priority": "major", 
    "keywords": "", 
    "time": "2015-09-25T11:09:17Z", 
    "milestone": "1.0.0", 
    "owner": "", 
    "type": "task"
}
```

**Comment by angelobanse** [comment]
Are you talking about "_tools/webWizard/SimpleWebSocketServer.py_" and "_osmWebWizard.py_"?

If so, some changes need to be made in this Wiki page: http://sumo.dlr.de/wiki/Networks/Import/OpenStreetMap#3-click_scenario_generation under the section **3-click scenario generation**, mainly renaming "_server.py_" for "_osmWebWizard.py_"

**Comment by namdre** [comment]
Thanks. I've updated the wiki. This issue predates the renaming from 'server.py' to 'osmWebWizard.py'
