### ISSUE TITLE
allow dynamic demand definition (trac #1946)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#1946]
- add new menus and dialogs for defining a flow
  - allow setting (at least) attributes from,to,via/route ,begin,end,type and probability/period
  - allow picking edges with the mouse
- show list of gui-defined (and loaded?) flows
  - modify probability/period
  - save to file
  - load from file
- allow defining types
- show list of known types
- show list of known (stand-alone) routes

 

Migrated from http://sumo.dlr.de/ticket/1946
```json
{
    "status": "new", 
    "changetime": "2015-09-29T11:42:38Z", 
    "description": "- add new menus and dialogs for defining a flow\n  - allow setting (at least) attributes from,to,via/route ,begin,end,type and probability/period\n  - allow picking edges with the mouse\n- show list of gui-defined (and loaded?) flows\n  - modify probability/period\n  - save to file\n  - load from file\n- allow defining types\n- show list of known types\n- show list of known (stand-alone) routes\n\n \n\n", 
    "reporter": "namdre", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1443526958085684", 
    "component": "simulation gui (GUISIM)", 
    "summary": "allow dynamic demand definition", 
    "priority": "major", 
    "keywords": "", 
    "time": "2015-09-29T11:41:55Z", 
    "milestone": "1.0.0", 
    "owner": "", 
    "type": "enhancement"
}
```

**Comment by namdre** [comment]
scaling flows is now working via slider in the gui. (vehicles that are still loaded from xml are also scaled)

**Comment by namdre** [comment]
next step is to allow demand definition in NETEDIT. SUMO-GUI at least has the 'scale'-slider now.
