### ISSUE TITLE
improve TLS editor

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#2038]
* ~~jump directly into the phase editor on creating a new TLS~~
* ~~add 'Recompute' button for re-guessing the plan~~
* ~~add button 'Duplicate Phase'~~
* ~~allow reordering phases by drag-and-drop (or buttons)~~ 
* ~~allow creating (recompute/duplicate) and deleting additional programs for the same TLS~~
* add support for WAUT (http://sumo.dlr.de/wiki/Simulation/Traffic_Lights#Defining_Program_Switch_Times_and_Procedure)
* ~~shortcuts when explicitly setting phases:~~
* ~~allow setting the state for all phases simultaneously (check box in the top bar)~~
* ~~add lane-popup options for setting the state of all connections from that lane or edge~~
  * ~~if multiple lanes/edges are selected, state applies to all of them~~
* smart adaptation of existing plans if another lane or connection is added to the junction
* ~~add button for removing unused parts of the state (if tlIndex attributes are customized and reused)~~ (cleanup)

related: #3427, #3420, #3423, #2389, #3418, #3419, #3421

**Comment by palvarezlopez** [comment]
WAUT support and future improvements will be implemented in different tickets
