### ISSUE TITLE
allow configuring rail_crossing parameters (trac #2062)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#2062]
Migrated from http://sumo.dlr.de/ticket/2062
```json
{
    "status": "assigned", 
    "changetime": "2016-10-14T10:39:37Z", 
    "description": "", 
    "reporter": "namdre", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1476441577749276", 
    "component": "simulation data input", 
    "summary": "allow configuring rail_crossing parameters", 
    "priority": "major", 
    "keywords": "", 
    "time": "2015-12-08T12:15:44Z", 
    "milestone": "1.0.0", 
    "owner": "namdre", 
    "type": "enhancement"
}
```

- load junction parameters from net.xml
- load tlLogic parameters from additional  (re-init paramters after constructor)
- set parameter via TraCI (re-set members)

**Comment by behrisch** [comment]
still needs tests for all parameters except time-gap and also for setting the parameters in the net or via traci instead of using an additional file

**Comment by behrisch** [comment]
docs are missing too

**Comment by namdre** [comment]
docs were added in the meantime.
