### ISSUE TITLE
inconsistent tl data in vissim network (trac #2099)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#2099]
in tests/import/vissim/bayernstrasse 
the same connection is controlled by two signal groups with conflicting state information

tl=454 group=10 tst=Con(from=91 fromLane=0 to=87[0](../commit/0)+94 toLane=0 tlIndex=3)
tl=454 group=9  tst=Con(from=91 fromLane=0 to=87[0](../commit/0)+94 toLane=0 tlIndex=21)

it is unclear whether the problem comes from the input  data or from invalid processing

Migrated from http://sumo.dlr.de/ticket/2099
```json
{
    "status": "new", 
    "changetime": "2016-04-06T09:20:18Z", 
    "description": "in tests/import/vissim/bayernstrasse \nthe same connection is controlled by two signal groups with conflicting state information\n\ntl=454 group=10 tst=Con(from=91 fromLane=0 to=87[0]+94 toLane=0 tlIndex=3)\ntl=454 group=9  tst=Con(from=91 fromLane=0 to=87[0]+94 toLane=0 tlIndex=21)\n\nit is unclear whether the problem comes from the input  data or from invalid processing", 
    "reporter": "namdre", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1459934418731060", 
    "component": "net building (NETGEN, NETCONVERT)", 
    "summary": "inconsistent tl data in vissim network", 
    "priority": "minor", 
    "keywords": "", 
    "time": "2016-01-11T11:52:39Z", 
    "milestone": "2.0.0", 
    "owner": "", 
    "type": "defect"
}
```

**Comment by m-kro** [comment]
In current dev. version, the max tl index is 20. Tl indices for connections between edges 91 and 870+94 show the signal values. >> I can't reproduce the error anymore?!
