### ISSUE TITLE
invalid emissions for decelerating / standing vehicles for HBEFA and HBEFA3 (trac #2110)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#2110]
models return 0 emissions for vehicles with acceleration < 0

- this does not take into account engine power to overcome friction losses
- at speeds near 0, numerical instability could cause the inequality to evaluate 'true' despite engine idle power being active at this speed.

related issues:
- #4019
- #10441 
- #10491

Migrated from http://sumo.dlr.de/ticket/2110
```json
{
    "status": "new", 
    "changetime": "2016-01-21T12:43:05Z", 
    "description": "models return 0 emissions for vehicles with acceleration < 0\n\n- this does not take into account engine power to overcome friction losses\n- at speeds near 0, numerical instability could cause the inequality to evaluate 'true' despite engine idle power being active at this speed.", 
    "reporter": "namdre", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1453380185950969", 
    "component": "simulation data output", 
    "summary": "invalid emissions for decelerating / standing vehicles for HBEFA and HBEFA3", 
    "priority": "minor", 
    "keywords": "", 
    "time": "2016-01-21T12:43:05Z", 
    "milestone": "1.1.0", 
    "owner": "", 
    "type": "defect"
}
```

**Comment by AliMirzaei5778** [comment]
What is interesting to me is that in addition to the vehicles' emissions not being recorded because of what you mentioned, the emission values of the first two seconds of the bus that is going to enter the bay are zero, and from the third second, it backs to what is expected.

**Comment by behrisch** [comment]
coasting deceleration is now implemented for HBEFA* as well
