### ISSUE TITLE
add node_type roundabout (trac #2303)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#2303]
This node should be expanded into multiple nodes that form a roundabout.
The 'radius' attribute of the node should be used to define the roundabout radius. Naturally, a <roundabout> definition should be generated as well and the node priorities set accordingly.

This node type is "input-only" and does not appear in the generated network.
This should simplify definitions of custom roundabouts.

Migrated from http://sumo.dlr.de/ticket/2303
```json
{
    "status": "new", 
    "changetime": "2016-05-09T07:37:11Z", 
    "description": "This node should be expanded into multiple nodes that form a roundabout.\nThe 'radius' attribute of the node should be used to define the roundabout radius. Naturally, a <roundabout> definition should be generated as well and the node priorities set accordingly.\n\nThis node type is \"input-only\" and does not appear in the generated network.\nThis should simplify definitions of custom roundabouts.", 
    "reporter": "namdre", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1462779431983519", 
    "component": "net building (NETGEN, NETCONVERT)", 
    "summary": "add node_type roundabout", 
    "priority": "major", 
    "keywords": "", 
    "time": "2016-05-09T07:37:11Z", 
    "milestone": "2.0.0", 
    "owner": "", 
    "type": "enhancement"
}
```

**Comment by namdre** [comment]
The node type would have to be forbidden in netedit (it would trigger network changes that cannot be undone). A junction context-menu function 'convert to roundabout' could be added to netedt but it would have to duplicate the network manipulations and put each step into the undo list.

**Comment by namdre** [comment]
wontFix: doing #7030 instead.
