### ISSUE TITLE
Improve Wiki-Page Basic Computer Skills (trac #2306)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#2306]
http://sumo.dlr.de/wiki/Basics/Basic_Computer_Skills

With more images

Migrated from http://sumo.dlr.de/ticket/2306
```json
{
    "status": "assigned", 
    "changetime": "2017-01-31T19:58:44Z", 
    "description": "http://sumo.dlr.de/wiki/Basics/Basic_Computer_Skills\n\nWith more images", 
    "reporter": "pablo", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1485892724210497", 
    "component": "documentation", 
    "summary": "Improve Wiki-Page Basic Computer Skills", 
    "priority": "minor", 
    "keywords": "images, basic computer skills", 
    "time": "2016-05-09T12:14:07Z", 
    "milestone": "2.0.0", 
    "owner": "pablo", 
    "type": "task"
}
```

**Comment by angelobanse** [comment]
is this still wanted?
if so, what images or sections are desired?

**Comment by behrisch** [comment]
Yes. I think at least the following steps should be done:
- [ ] remove everything referring to sumo 0.12.2 or earlier
- [ ] update to Windows 10 concerning editor start and setting of environment variables
- [ ] add at least one picture of a complete command execution in the command line
