### ISSUE TITLE
add function getNeighboringNodes to sumolib (trac #2340)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#2340]
Migrated from http://sumo.dlr.de/ticket/2340
```json
{
    "status": "assigned", 
    "changetime": "2017-01-09T11:37:19Z", 
    "description": "", 
    "reporter": "namdre", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1483961839140022", 
    "component": "tools (python)", 
    "summary": "add function getNeighboringNodes to sumolib", 
    "priority": "minor", 
    "keywords": "", 
    "time": "2016-05-19T05:03:50Z", 
    "milestone": "1.0.0", 
    "owner": "", 
    "type": "enhancement"
}
```

**Comment by behrisch** [comment]
Thank you for taking this one up. Unfortunately the implementation does not look correct concerning the outgoing nodes. Furthermore I think we should make it configurable whether the outgoing and the incoming or both are to be looked at by adding two boolean parameters which should default to true. Maybe we even need a third one for "self-neighborhood".

**Comment by lbieker** [comment]
Tests and comment are fixed
