### ISSUE TITLE
Improve lane-change gap finding in congested traffic situations (trac #2341)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#2341]
For instance, in the scenario VMM_muc/plain at time t=28770 the vehicle "emitter_SST92-150 FG 1 DE 2_28658400" has to stop in the middle of the highway, because it couldn't/didn't change lanes in time.

But similar situations also arise in slow dense traffic. The pattern is as follows:
a vehicle v1 that wants to change its lane towards another lane with high density decides to overtake its "neighLeader" (to eventually cut in before), but then finds that there isn't a sufficiently large gap between the "neighLeader" and the leader of "neighLeader", so v1 decides to overtake neighleader as well until the situation becomes really urgent.

A possible fix would be to check the gap between "neighLeader" and its leader when informing about the overtake-attempt and requesting a slow down (in informLeader).

Migrated from http://sumo.dlr.de/ticket/2341
```json
{
    "status": "new", 
    "changetime": "2016-10-14T10:39:37Z", 
    "description": "For instance, in the scenario VMM_muc/plain at time t=28770 the vehicle \"emitter_SST92-150 FG 1 DE 2_28658400\" has to stop in the middle of the highway, because it couldn't/didn't change lanes in time.\n\nBut similar situations also arise in slow dense traffic. The pattern is as follows:\na vehicle v1 that wants to change its lane towards another lane with high density decides to overtake its \"neighLeader\" (to eventually cut in before), but then finds that there isn't a sufficiently large gap between the \"neighLeader\" and the leader of \"neighLeader\", so v1 decides to overtake neighleader as well until the situation becomes really urgent.\n\nA possible fix would be to check the gap between \"neighLeader\" and its leader when informing about the overtake-attempt and requesting a slow down (in informLeader).", 
    "reporter": "leo", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1476441577749276", 
    "component": "microsim - lane change", 
    "summary": "Improve lane-change gap finding in congested traffic situations", 
    "priority": "major", 
    "keywords": "", 
    "time": "2016-05-19T14:06:05Z", 
    "milestone": "1.0.0", 
    "owner": "leo", 
    "type": "defect"
}
```

**Comment by namdre** [comment]
This should be resolved via #2532
