### ISSUE TITLE
import controller information from openDrive (trac #2365)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#2365]
this is used to define grouping of signals (controlled edges or connections)

Migrated from http://sumo.dlr.de/ticket/2365
```json
{
    "status": "new", 
    "changetime": "2016-06-02T08:24:39Z", 
    "description": "this is used to define grouping of signals (controlled edges or connections)", 
    "reporter": "namdre", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1464855879948340", 
    "component": "net building (NETGEN, NETCONVERT)", 
    "summary": "import controller information from openDrive", 
    "priority": "minor", 
    "keywords": "", 
    "time": "2016-06-02T08:24:39Z", 
    "milestone": "1.0.0", 
    "owner": "", 
    "type": "enhancement"
}
```

**Comment by m-kro** [comment]
Is of interest for VuV group

**Comment by m-kro** [comment]
Working:

- controller info is translated into connections sharing the same tlIndex value
- works as well if only a subset of connections of the intersection is linked to an OpenDRIVE controller
- controller information is added to the corresponding connection as a parameter value

To do:

- create a meaningful signal program (currently all off)

**Comment by namdre** [comment]
we probably need an option  for backward compatibility so that users who rely on the old signal programs can still use their toolchains as expected.

**Comment by namdre** [comment]
The new programs aren't valid because they do not distinguish between unrestricted green and restricted green. Please make them optional. Sumo needs different indices / states for restricted/unrestricted whereas in the real world the state of a single movement can be defined by the combination of up to thee different lights.

**Comment by m-kro** [comment]
Well then it's probably better to check if is possible at all to include each OpenDRIVE signal group in the signal program. If it isn't, just leave the automatically generated program in place. If not, try either the implemented strategy or something ~ 1 signal group per phase.
