### ISSUE TITLE
add bicycles (trac #2409)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#2409]
as a separate mode

Migrated from http://sumo.dlr.de/ticket/2409
```json
{
    "status": "new", 
    "changetime": "2016-10-25T07:45:02Z", 
    "description": "as a separate mode", 
    "reporter": "behrisch", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1477381502937752", 
    "component": "urmo", 
    "summary": "add bicycles", 
    "priority": "major", 
    "keywords": "", 
    "time": "2016-06-13T10:14:30Z", 
    "milestone": "1.0.0", 
    "owner": "", 
    "type": "enhancement"
}
```

**Comment by Robinlovelace** [comment]
Seems to me this has been done, based on gif below. My main issue is that the mode is not realistically modelled: bicycles can overtake cars in almost all urban situations so I don't think congestion of the type shown in the gif below is realistic. Any plans to support freer cycling behaviour?

![ezgif com-resize](https://user-images.githubusercontent.com/1825120/46748345-41c98580-ccab-11e8-8093-b265bd36f639.gif)

**Comment by Robinlovelace** [comment]
Worth putting-in another issue on the topic? Hope this is of use/interest.

**Comment by namdre** [comment]
You would probably get more realistic results when enabling the sublane model. Otherwise, each vehicle takes up the whole width of a lane. See http://sumo.dlr.de/wiki/Simulation/SublaneModel#Sublane-Model

**Comment by namdre** [comment]
Also, this ticket refers to a specific city simulation projection and not to SUMO itself.

**Comment by Robinlovelace** [comment]
Thanks for the pointer, great to know SUMO can represent over/undertaking bicycles. As you probably guessed I'm quite new to this so not sure what you mean by "simulation projection", but very happy to see development on active modes.

**Comment by namdre** [comment]
typo now corrected

**Comment by behrisch** [comment]
And bicycles are present in UrMo now.
