### ISSUE TITLE
add frame for create-edge mode (GNECreateEdgeFrame)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#2431]
show/edit edge attribute for the current edge template (similar to inspect mode for edges)

Select template from a list of saved edge templates (should then include lane-level details)

open issues:
- [x] save edge type / save edge type as menu has no effect
- [x] loaded edge types saved in network have no attributes
- [x] created edge types have no attributes when saved
- [x] attributes in lane panel are not updated and take no effect
- [x] updating the template edge attributes (via inspect mode) has no effect when creating new edges according to the current template (regression)
- [x] edges created with a specified type do not have the corresponding type attribute
- [x] new edge type has 2 lanes instead of 1

**Comment by namdre** [comment]
also show/edit default edge id in frame (#5970)
