### ISSUE TITLE
merge recent file lists

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#2471]
it is counterintuitive for the user to have one list with configs and one with networks and it hinders keyboard access. This applies to sumo-gui and netedit

**Comment by m-kro** [comment]
Sumocfg files cannot be loaded from the recent files list as the "isNet" switch is not derived correctly:
https://github.com/eclipse/sumo/blob/ce21059fdfa99146e7420ddf79c23e98d27e832c/src/gui/GUIApplicationWindow.cpp#L950
This evaluates to true for every entry of the recent files list, independently of the file type!

**Comment by behrisch** [comment]
Seems to be still open for netedit
