### ISSUE TITLE
rewrite connection building algorithm (trac #2472)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#2472]
The current system (Double Bresenham + lots of special cases in post-processing) is to inflexible to deal with large intersections (especially multi-modal intersections).

Instead a modular rule-base system should be created.

Migrated from http://sumo.dlr.de/ticket/2472
```json
{
    "status": "new", 
    "changetime": "2016-10-14T11:05:42Z", 
    "description": "The current system (Double Bresenham + lots of special cases in post-processing) is to inflexible to deal with large intersections (especially multi-modal intersections).\n\nInstead a modular rule-base system should be created.", 
    "reporter": "namdre", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1476443142921085", 
    "component": "net building (NETGEN, NETCONVERT)", 
    "summary": "rewrite connection building algorithm", 
    "priority": "major", 
    "keywords": "", 
    "time": "2016-07-04T08:45:14Z", 
    "milestone": "1.0.0", 
    "owner": "", 
    "type": "defect"
}
```

**Comment by namdre** [comment]
connections look almost fine now. Remaining delta to expectations should be discussed

**Comment by namdre** [comment]
some more post processing tweaks did the job for the known failures.

**Comment by namdre** [comment]
I'm happy for now and would rather open a new ticket once the need arises.
Also, getting rid of Bresenham would go beyond what i'd call refactoring. It would be a complete new algorithm (maybe something to add as an alternative even and keep Bresenham for cases not covered by the new system).
