### ISSUE TITLE
recheck automatic routing via TraCI (trac #2583)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#2583]
- addFull with fromTaz, ToTaz probably does not work. When loading routes from XML MSRouteHandler performs route manipulation and sets the edges to [fromTaz-source, toTaz-sink], forceReroute=True. This does not happen via TraCI

- ~~to trigger automatic routing due to incomplete routes (trip-style), a rerouting device must be equipped beforehand (by setting probability to 1 or by using a vType that sets the parameter has.rerouting.device to True~~

Migrated from http://sumo.dlr.de/ticket/2583
```json
{
    "status": "new", 
    "changetime": "2016-10-25T07:45:02Z", 
    "description": "- addFull with fromTaz, ToTaz probably does not work. When loading routes from XML MSRouteHandler performs route manipulation and sets the edges to [fromTaz-source, toTaz-sink], forceReroute=True. This does not happen via TraCI\n\n- to trigger automatic routing due to incomplete routes (trip-style), a rerouting device must be equipped beforehand (by setting probability to 1 or by using a vType that sets the parameter has.rerouting.device to True\n", 
    "reporter": "namdre", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1477381502937752", 
    "component": "TraCI", 
    "summary": "recheck automatic routing via TraCI", 
    "priority": "major", 
    "keywords": "", 
    "time": "2016-10-11T13:09:08Z", 
    "milestone": "1.0.0", 
    "owner": "", 
    "type": "defect"
}
```

**Comment by namdre** [comment]
Trip-style routes given via vehicle.add / addFulll now trigger automatic routing.

**Comment by namdre** [comment]
taz-routing works if the option --device.rerouting.with-taz is set (MSBaseVehicle::reroute adds the -sink / -source suffix.

**Comment by namdre** [comment]
(test needed)
