### ISSUE TITLE
Improve drawing of Bubbles/Shapes of GNEJunctions (trac #2596)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#2596]
GNEJunction's Shapes can be improved in some aspects:

[X] 1 - Every GNEJunction should have a vector with their GNEEdges, to avoid inefficient searchs in big nets (See all @improve labels in netedit project)

[ ] 2 - Every GNELane and lane should habe keeped two differents Shapes: One for when Junctions are represented asn Bubbles and another for when are represented with their real shape

[ ] 3 - Point 2 should be avoid to update geometry of all elements when checkbox "show Junction as Bubbles" is checked.

[ ] 4 - GNEJunction shapes must be correctly drawed after movements.

[ ] 5 - If the shape of an edge is modified, GNEJunction shape must be recalculated.

Migrated from http://sumo.dlr.de/ticket/2596
```json
{
    "status": "assigned", 
    "changetime": "2016-11-12T13:52:16Z", 
    "description": "GNEJunction's Shapes can be improved in some aspects:\n\n[X] 1 - Every GNEJunction should have a vector with their GNEEdges, to avoid inefficient searchs in big nets (See all @improve labels in netedit project)\n\n[ ] 2 - Every GNELane and lane should habe keeped two differents Shapes: One for when Junctions are represented asn Bubbles and another for when are represented with their real shape\n\n[ ] 3 - Point 2 should be avoid to update geometry of all elements when checkbox \"show Junction as Bubbles\" is checked.\n\n[ ] 4 - GNEJunction shapes must be correctly drawed after movements.\n\n[ ] 5 - If the shape of an edge is modified, GNEJunction shape must be recalculated.", 
    "reporter": "pablo", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1478958736631433", 
    "component": "netedit", 
    "summary": "Improve drawing of Bubbles/Shapes of GNEJunctions", 
    "priority": "minor", 
    "keywords": "GNEJunctions, Bubble, shape", 
    "time": "2016-10-17T08:13:13Z", 
    "milestone": "1.0.0", 
    "owner": "pablo", 
    "type": "enhancement"
}
```

**Comment by palvarezlopez** [comment]
This ticket was already solved in successive commits.
