### ISSUE TITLE
errors in induction loop output (trac #2661)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#2661]
importing a heavily outdated detector file, netedit correctly filtered it to fit the network but had the following problems:
* encoded umlauts appearing as &amp;uuml; in the input were not properly translated in the output (&uuml;) which made the xml invalid
* positions behind the lane end were read and written without a warning
* [x] splitByType is not a valid attribute anymore
* [x] it is not possible to specify friendlyPos in the GUI

Migrated from http://sumo.dlr.de/ticket/2661
```json
{
    "status": "assigned", 
    "changetime": "2017-03-29T18:46:49Z", 
    "description": "importing a heavily outdated detector file, netedit correctly filtered it to fit the network but had the following problems:\n - encoded umlauts appearing as &amp;uuml; in the input were not properly translated in the output (&uuml;) which made the xml invalid\n - positions behind the lane end were read and written without a warning\n - splitByType is not a valid attribute anymore\n - it is not possible to specify friendlyPos in the GUI\n", 
    "reporter": "behrisch", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1490813209230231", 
    "component": "netedit", 
    "summary": "errors in induction loop output", 
    "priority": "minor", 
    "keywords": "", 
    "time": "2016-11-09T09:06:24Z", 
    "milestone": "1.1.0", 
    "owner": "pablo", 
    "type": "defect"
}
```

**Comment by palvarezlopez** [comment]
@behrisch I can't reproduce the error with the umlauts. We have an example in the test folder?

**Comment by namdre** [comment]
not important.
