### ISSUE TITLE
Add driver model, which can capture unsafe driving (trac #2668)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#2668]
As a first step we might include "perception noise" to the standard cf-model by imposing stochastic fluctuations on the values use for determining the follow speed (gap to leader, leader's velocity, etc.).

As a next step, such an approach might be included in the gap acceptance models (junction behaviour / lane changing). (By the way, the seperation of the junction behaviour into a proper model seems worth discussing.)

Perspectively, we also might include other existing models (as Treiber's Human Driver Model (HDM)) or model concepts (Fuller's Task Capability Model) from the scientific literature.

Migrated from http://sumo.dlr.de/ticket/2668
```json
{
    "status": "new", 
    "changetime": "2016-11-15T10:11:52Z", 
    "description": "As a first step we might include \"perception noise\" to the standard cf-model by imposing stochastic fluctuations on the values use for determining the follow speed (gap to leader, leader's velocity, etc.).\n\nAs a next step, such an approach might be included in the gap acceptance models (junction behaviour / lane changing). (By the way, the seperation of the junction behaviour into a proper model seems worth discussing.)\n\nPerspectively, we also might include other existing models (as Treiber's Human Driver Model (HDM)) or model concepts (Fuller's Task Capability Model) from the scientific literature.", 
    "reporter": "leo", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1479204712269273", 
    "component": "microsim - car following", 
    "summary": "Add driver model, which can capture unsafe driving", 
    "priority": "major", 
    "keywords": "", 
    "time": "2016-11-15T10:11:52Z", 
    "milestone": "1.0.0", 
    "owner": "leo", 
    "type": "enhancement"
}
```

**Comment by leoluecken** [comment]
This is addressed more abstractly as a DriverState device working with arbitrary cf models, see e.g. #4115 for the current development.
