### ISSUE TITLE
Add support for surrogate safety measures (SSMs) (trac #2669)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#2669]
In some way, the user should be able to extract SSMs from the simulation. 

First, it has to be specified how this should be realized in detail and practise. 

Two options, so far:

1) implement the SSMs ourselves, either by generating on-the-fly output or scripting a post-processing tool for trajectory data. In that case, we should specify, which SSMs are needed.

2) Couple to an existing open source tool for calculating SSMs from trajectory data. (One candidate is [http://www.fhwa.dot.gov/publications/research/safety/08049/ SSAM])

Migrated from http://sumo.dlr.de/ticket/2669
```json
{
    "status": "new", 
    "changetime": "2016-11-15T10:25:54Z", 
    "description": "In some way, the user should be able to extract SSMs from the simulation. \n\nFirst, it has to be specified how this should be realized in detail and practise. \n\nTwo options, so far:\n\n1) implement the SSMs ourselves, either by generating on-the-fly output or scripting a post-processing tool for trajectory data. In that case, we should specify, which SSMs are needed.\n\n2) Couple to an existing open source tool for calculating SSMs from trajectory data. (One candidate is [http://www.fhwa.dot.gov/publications/research/safety/08049/ SSAM])\n", 
    "reporter": "leo", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1479205554449946", 
    "component": "simulation general (micro)", 
    "summary": "Add support for surrogate safety measures (SSMs)", 
    "priority": "major", 
    "keywords": "", 
    "time": "2016-11-15T10:25:54Z", 
    "milestone": "1.0.0", 
    "owner": "", 
    "type": "enhancement"
}
```

**Comment by leoluecken** [comment]
Has been implemented as MSDevice_ToC in a basic version.

**Comment by namdre** [comment]
1. see https://sumo.dlr.de/docs/Simulation/Output/SSM_Device.html
2. see #8051
