### ISSUE TITLE
Introduce actionpoints into CF- and LC-Models (trac #2681)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#2681]
This is not meant as a switch to truly event-based processing but rather provides a way to make the frequency of driving-process related calculations and decisions smaller than the simulation-step frequency (which may be unnecessarily high).

On one hand, this could speed up subsecond simulation dramatically, while offering a possibility to model reaction-time individually per driver (and even per driving situation!) and not via the integration step-width. (refs.#2186 and #2668)

The actionspoints are confined to lie on the time grid implied by the integration step-length. Setting the default value equal to the integration step-width would not change the behaviour of the models.

Migrated from http://sumo.dlr.de/ticket/2681
```json
{
    "status": "new", 
    "changetime": "2016-11-17T11:20:32Z", 
    "description": "This is not meant as a switch to truly event-based processing but rather provides a way to make the frequency of driving-process related calculations and decisions smaller than the simulation-step frequency (which may be unnecessarily high).\n\nOn one hand, this could speed up subsecond simulation dramatically, while offering a possibility to model reaction-time individually per driver (and even per driving situation!) and not via the integration step-width. (refs.#2186 and #2668)\n\nThe actionspoints are confined to lie on the time grid implied by the integration step-length. Setting the default value equal to the integration step-width would not change the behaviour of the models.", 
    "reporter": "leo", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1479381632860885", 
    "component": "simulation general (micro)", 
    "summary": "Introduce actionpoints into CF- and LC-Models", 
    "priority": "major", 
    "keywords": "", 
    "time": "2016-11-17T11:20:32Z", 
    "milestone": "1.0.0", 
    "owner": "leo", 
    "type": "enhancement"
}
```

**Comment by leoluecken** [comment]
This was done already, see action-step-length
