### ISSUE TITLE
allow triggering netdiff from a menu

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#2736]
should select a net to diff against the currently show network (popup to ask whether unsaved changes should be saved first).

Question is how to present the results to the user. Ideas:

- let netdiff generated shapes for removed elements and selection files for added/modified elements
- netedit could then automatically load the shapes and the selection to make changes visible / searchable

**Comment by namdre** [comment]
There some things still missing:
- result integration in netedit
- selecting the diff order (currently the current network is always the first "original" network but maybe it should be something else.

I would like to have a dialog with the following elements:
- a widget to select the "original" network 
- a widget to select the "modified" network
  - both widgets should have a button for "use current network" and a file-dialog button to select any file from the file system
  - both widgets should indicate the path to the used network (and also allow copy/paste into the path field)
- a list of checkboxes to select the following output options for display in netedit
  - select modified elements
  - select added elements
  - select deleted elements (can be useful if the current network is the "original")
  - load shapes for modified elements
  - load shapes for added elements
  - load shapes for deleted elements

I will work on the python side of things and add netdiff options to generate selection files and shape files.
