### ISSUE TITLE
add persons to saved state (trac #2792)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#2792]
this should include a serialization of the current state of the pedestrian model

Migrated from http://sumo.dlr.de/ticket/2792
```json
{
    "status": "reopened", 
    "changetime": "2017-02-01T11:31:39Z", 
    "description": "this should include a serialization of the current state of the pedestrian model", 
    "reporter": "behrisch", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1485948699034104", 
    "component": "simulation data output", 
    "summary": "add persons to saved state", 
    "priority": "major", 
    "keywords": "", 
    "time": "2017-01-18T10:05:31Z", 
    "milestone": "1.0.0", 
    "owner": "namdre", 
    "type": "task"
}
```

**Comment by namdre** [comment]
At least a light-weight solution where the pedestrian model state is lost but the positions are kept should be implemented.

**Comment by kajetanj** [comment]
What's the status of this issue?

**Comment by namdre** [comment]
except for persons riding in a car, state loading is not working.

**Comment by namdre** [comment]
@kajetanj I'd cautiously say it's working now. Make sure to build the latest git version or to download fresh binaries at https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_development_version

and please report any oddities you encounter.

**Comment by kajetanj** [comment]
Wow, thank you! 
> and please report any oddities you encounter.

Will do!
