### ISSUE TITLE
implement proper time error checks (trac #282)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#282]
Checks for parsing the time must be implemented
* whether it's a valid representation (real number)
* whether the time step size and given frequencies/... match

Migrated from http://sumo.dlr.de/ticket/282
```json
{
    "status": "assigned", 
    "changetime": "2013-05-28T09:08:08Z", 
    "description": "Checks for parsing the time must be implemented\n* whether it's a valid representation (real number)\n* whether the time step size and given frequencies/... match\n", 
    "reporter": "dkrajzew", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1369732088000000", 
    "component": "simulation data input", 
    "summary": "implement proper time error checks", 
    "priority": "major", 
    "keywords": "", 
    "time": "2010-05-04T12:02:20Z", 
    "milestone": "1.0.0", 
    "owner": "behrisch", 
    "type": "task"
}
```

**Comment by namdre** [comment]
checks are there and we don't want to restrict time values to multiples of the step-length

**Comment by behrisch** [comment]
@namdre But shouldn't we at least check frequencies/periods (for instance in the fcd-output) whether they are multiples of the step length?

**Comment by namdre** [comment]
No. I expect most things to work independent of the step size (and be rounded in some sensible manner just like fractional vehicle departures).

**Comment by behrisch** [comment]
I agree for fractional vehicle departure times, I disagree for intervals and periods (and also begin and end). Currently I can start a simulation at time 1.5 with step length 1 and won't get any fcd output because the modulo always fails. I suppose this maybe true for other interval checks. Of course we can implement rounding everywhere but a sensible alignment of time values seems more reasonable to me.

**Comment by namdre** [comment]
I wasn't aware of that fcd issue and I would consider it a bug. 
In my opinion the output should come at 1.5, 2.5, 3.5 .... in your example.
I agree that it's simpler to forbid some combinations.
What kind of conditions would you like to impose on the input?

**Comment by behrisch** [comment]
It is not easy but I would issue at least a warning for every detector interval and every begin / end which is not divisible by the step length. But there is the additional point whether periods should be relative to the begin of the simulation or relative to 0. Both approaches probably have use cases and to solve this cleanly we would need something like an offset parameter everywhere (such as the one for traffic lights). I think the default should be relative to simulation begin (although this means more code).

**Comment by behrisch** [comment]
It is probably not complete yet, but it is beyond the scope of this ticket to check each and every occurence of a time related parameter. More problems will result in more tickets.
