### ISSUE TITLE
automatically calculate "until" times (trac #2827)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#2827]
currently the user needs to give until times for all the stops in a public transport description. One could calculate them from (empty network) travel times or from a weight file

Migrated from http://sumo.dlr.de/ticket/2827
```json
{
    "status": "new", 
    "changetime": "2017-01-27T14:30:26Z", 
    "description": "currently the user needs to give until times for all the stops in a public transport description. One could calculate them from (empty network) travel times or from a weight file", 
    "reporter": "behrisch", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1485527426271274", 
    "component": "routing (DUAROUTER)", 
    "summary": "automatically calculate \"until\" times", 
    "priority": "major", 
    "keywords": "", 
    "time": "2017-01-27T14:30:26Z", 
    "milestone": "1.0.0", 
    "owner": "", 
    "type": "enhancement"
}
```

**Comment by namdre** [comment]
ptlines2flows can be used to calculate until-times.

**Comment by behrisch** [comment]
@namdre So the proposed workflow for manually generating a bus line is to write a ptlines file?

**Comment by namdre** [comment]
Yes. This is what I would propose. (I also think it's more valuable to get the timing from a simulation to capture more intersection effects).
For larger projects, I think you will want to import gtfs (or some equivalent format) including all the necessary times directly.
