### ISSUE TITLE
implement person.moveToXY (trac #2872)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#2872]
* walking stage: this should work exactly like vehicle.moveToXY. Care must be taken when moving a person onto an intersection that is not on its route (walkingarea is arbitrary then).
* mapping functionality from TraCIServerAPI_Vehicle should be refactored to allow reuse for persons.
* An MSVehicle::Influencer Analogue should be put in MSPerson
* MSPModel::PedestrianState should be extended with a moveToXY method 
* TraCIServer::postProcessVTD() should also do persons
* waiting stage: move person to an arbitrary location but raise an error if this leads to a disconnected plan
* riding stage (waiting for vehicle): move person to arbitrary location. The user is responsible for ensuring that an eligible vehicle stops there.
* riding stage (in vehicle): allow placement within the vehicle but raise an error when trying to move beyond the vehicle (box) bounds

Migrated from http://sumo.dlr.de/ticket/2872
```json
{
    "status": "new", 
    "changetime": "2017-05-21T11:53:09Z", 
    "description": "* walking stage: this should work exactly like vehicle.moveToXY. Care must be taken when moving a person onto an intersection that is not on its route (walkingarea is arbitrary then).\n * mapping functionality from TraCIServerAPI_Vehicle should be refactored to allow reuse for persons.\n * An MSVehicle::Influencer Analogue should be put in MSPerson\n * MSPModel::PedestrianState should be extended with a moveToXY method \n * TraCIServer::postProcessVTD() should also do persons\n* waiting stage: move person to an arbitrary location but raise an error if this leads to a disconnected plan\n* riding stage (waiting for vehicle): move person to arbitrary location. The user is responsible for ensuring that an eligible vehicle stops there.\n* riding stage (in vehicle): allow placement within the vehicle but raise an error when trying to move beyond the vehicle (box) bounds", 
    "reporter": "namdre", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1495367589084902", 
    "component": "TraCI", 
    "summary": "implement person.moveToXY", 
    "priority": "major", 
    "keywords": "sumo-user", 
    "time": "2017-02-16T08:59:06Z", 
    "milestone": "1.1.0", 
    "owner": "", 
    "type": "enhancement"
}
```

**Comment by namdre** [comment]
work on riding stage continues in #7402
