### ISSUE TITLE
Remove superfluous includes

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#2896]
Remove superflous #includes of netedit, and later in all projects, using:

https://include-what-you-use.org/

and

https://marketplace.visualstudio.com/items?itemName=Wumpf.IncludeToolbox

**Comment by palvarezlopez** [comment]
A big part of superfluous includes were already removed. The rest will be referenced in #12

**Comment by palvarezlopez** [comment]
@behrisch yes, I used IWYU within a Visual Studio modul: 

https://marketplace.visualstudio.com/items?itemName=Wumpf.IncludeToolbox
