### ISSUE TITLE
let public transport that is following a schedule skip stops when possible (trac #2917)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#2917]
if the vehicle reaches a named stop (busStop) after the stop 'until' time is over and there are no persons waiting at the stop and no passengers wish to debark at this stop, the stop may be skipped

Migrated from http://sumo.dlr.de/ticket/2917
```json
{
    "status": "new", 
    "changetime": "2017-03-07T11:08:41Z", 
    "description": "if the vehicle reaches a named stop (busStop) after the stop 'until' time is over and there are no persons waiting at the stop and no passengers wish to debark at this stop, the stop may be skipped", 
    "reporter": "namdre", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1488884921627703", 
    "component": "microsim - intermodal", 
    "summary": "let public transport that is following a schedule skip stops when possible", 
    "priority": "minor", 
    "keywords": "", 
    "time": "2017-03-07T11:08:41Z", 
    "milestone": "2.0.0", 
    "owner": "", 
    "type": "enhancement"
}
```

**Comment by namdre** [comment]
By adding more busStops along the route (virtual stops), a stop-anywhere-on-demand system can be simulated. Maybe with some tooling to create extra stops and a route that uses them.  It may also be a good idea to use busStop color to distinguish virtual stops from "real" stops.

**Comment by behrisch** [comment]
> It might be useful to distinguish between "dumb" stop-on-demand where any waiting persons force stopping and "smart" stop-on-demand where the vehicle "knows" whether any waiting persons are actually waiting for the current vehicle.

Actually this sounds more like an on-demand system to me and nothing I would expect from scheduled vehicles

**Comment by namdre** [comment]
An on-demand system can be as simple (and common) as people raising their hand when a vehicle approaches. In fact I recall it happening to me in Berlin: A delayed bus passed me by because I was sitting on a bench rather than standing on the curb.
