### ISSUE TITLE
allow retrieving the id of the next named stop (trac #2964)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#2964]
return a list of tuples
[(string lane, double endPos, string stoppingPlaceID, int stopFlags, double durationSeconds, double untilSeconds),
...]

Migrated from http://sumo.dlr.de/ticket/2964
```
    "changetime": "2017-03-21T09:35:48Z"
```

**Comment by lcodeca** [comment]
For consistency with http://www.sumo.dlr.de/daily/pydoc/traci._vehicle.html#VehicleDomain-setStop, duration and until should be integers in milliseconds.

**Comment by namdre** [comment]
contribution by @lcodeca still requires additions to our test suite.
