### ISSUE TITLE
invalid right of way rules at traffic light (trac #2975)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#2975]
when left-turning vehicles from a minor road are stuck on the intersection (i.e. because there is no exclusive left-turn phase) they may physically block the junction but are ignored when the main road switches to green.
The stuck vehicles ignore cross traffic ahead of the junction but yield to vehicles once they are on the junction.

This may cause collisions since the stuck vehicle may pass the internal junction just as cross traffic enters the junction with the latter being unable to stop in time.

Migrated from http://sumo.dlr.de/ticket/2975
```json
{
    "status": "new", 
    "changetime": "2017-03-24T13:44:22Z", 
    "description": "when left-turning vehicles from a minor road are stuck on the intersection (i.e. because there is no exclusive left-turn phase) they may physically block the junction but are ignored when the main road switches to green.\nThe stuck vehicles ignore cross traffic ahead of the junction but yield to vehicles once they are on the junction.\n\nThis may cause collisions since the stuck vehicle may pass the internal junction just as cross traffic enters the junction with the latter being unable to stop in time.", 
    "reporter": "namdre", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1490363062065506", 
    "component": "microsim - junctions", 
    "summary": "invalid right of way rules at traffic light", 
    "priority": "major", 
    "keywords": "", 
    "time": "2017-03-24T09:26:08Z", 
    "milestone": "1.1.0", 
    "owner": "", 
    "type": "defect"
}
```

**Comment by namdre** [comment]
was switched with mutual conflicts at tl-controlled intersections.
