### ISSUE TITLE
Support reading and writing of <param>s for all objects

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#3092]
should be handled within the GNEAttributeCarrier Infrastructure.

depends on #3343,

also needs #3485 to make this useful

**Comment by namdre** [comment]
params should be accessible as a single attribute of the form
"key1=value1|key2=value2|...." to allow filtering by parameter value

Editing parameters via dialog (#3485) can be implemented on top of that

**Comment by palvarezlopez** [comment]
Implemented and tested
