### ISSUE TITLE
allow visualising and editing edgeData files

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#3094]
for visual demand building. 
- directly usable by randomTrips.py
- eventually usable by dfrouter/flowrouter See #3093

should be one frame/mode for the 'traffic'-supermode (#6461) or a frame of a new 'data'-supermode
arguments for supermode
- selection frame must be different 
   - less elements in locking box
   - need new attributes 'begin', 'end' to define time range for matching
- inspect mode (optional) must be different (only lists available edge / connection) attributes
- new mode for editing OD-Matrix would also fit in this category

frame design:
- top part: interval frame
  - collapsible list of time intervals (FXCombBox) where one attribute is selected
  - button 'edit intervals': open dialog to edite,copy,remove intervals
        - show a list of time intervals (only start time needed , end time is implicitly the start of the next interval)
        - editable start time - (validate to be within preceding and succeeding time)
        - with an add/remove button next to the interval
        - 'add' inserts a new interval after the current' (copy current data)
        - one extra editable data field for the end time of the last interval

- middle part: attribute list
  - collapsible list of all available edge attributes (FXComboBox) where one attribute is selected
  - button 'edit attributes': open dialog to rename, delete, add attribute

After selecting an interval and attribute, all edges are colored according to the attribute value (when GUIVisualizationSettings::edgeData is set to the current attribute, activate 'color by edgedata')

- bottom part: edge selection info (due to the compactness of the above parts, this should always be visible without scrolling)
 - Individual and rectangle selection of attributes can be clicked to reveal their value range and set it to a new value (similar to taz frame)
 - must be able use selections from 'select mode'
 - should be able to select elements within a value range

**Comment by namdre** [comment]
@palvarezlopez would be useful for Rail2X

**Comment by namdre** [comment]
visualization is working nicely in sumo-gui.

**Comment by palvarezlopez** [comment]
Test added
