### ISSUE TITLE
Documentation for 1.0

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#3136]
List with the pending documentation for SUMO 1.0 (Has to be completed before release)

- ☑ Add attribute "name" to all stopping places (busStop, chargingStation and containerStops) (#3074)

- ☑ In codestyle: 
* ☑ Avoid to use redundant true/false in conditionals.
* ☑ use C++ 11 syntax for loops

- ☑ Section "installing/windows build" has to be updated due using of Visual Studio 2013/2017

- Section "installing/linux build" has to be updated with the CMake compilation

- New page for behavior of friendlyPositions in stoppingPlaces and detectors

- ☑ Add information about Polygon Frame.

- More information about how to load tlLogics in "Simulation/Traffic Lights"

- E1 Instant Detectors

**Comment by behrisch** [comment]
@palvarezlopez @namdre Can we close this and move the remaining items to #4305 ?

**Comment by palvarezlopez** [comment]
@behrisch yes, it's better so.
