### ISSUE TITLE
geometric collision on junction (trac #3155)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#3155]
wen setting the --collision.check-junctions, collisions are detected on small intersections. 
* At foe internal lanes with small radii, this happens because the effect of vehicle bodies cutting the corner is not taken into account when computing the intersections between internal lane shapes.
* At foe internal lanes that meet at sharp angles, this happens because the intersection is always computed under the assumption of orthogonality and this underestimates the necessary gaps.

Migrated from http://sumo.dlr.de/ticket/3155
```json
{
    "status": "new", 
    "changetime": "2017-06-13T19:24:38Z", 
    "description": "wen setting the --collision.check-junctions, collisions are detected on small intersections. \n* At foe internal lanes with small radii, this happens because the effect of vehicle bodies cutting the corner is not taken into account when computing the intersections between internal lane shapes.\n* At foe internal lanes that meet at sharp angles, this happens because the intersection is always computed under the assumption of orthogonality and this underestimates the necessary gaps.", 
    "reporter": "namdre", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1497381878476150", 
    "component": "microsim - junctions", 
    "summary": "geometric collision on junction", 
    "priority": "major", 
    "keywords": "sumo-user", 
    "time": "2017-05-30T07:25:51Z", 
    "milestone": "1.1.0", 
    "owner": "", 
    "type": "defect"
}
```

**Comment by namdre** [comment]
duplicate:
- cutting corners is tracked in #4431
- conflict points of internal lanes meeting at sharp angles is tracked in #4397
