### ISSUE TITLE
slow gui on windows 10 (trac #3162)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#3162]
reported bei Joerg Schweizer 

"2 out of 7 of my project students who use Windows 10 experienced slow
zooming, simulation and tool handling of any kind. I am aware that the GUI is a little slow with zooming in when viewing the whole network (approx 14000 edges), but  editing gets fast when a smaller network area is visible. However, in this case, all operations remain slow (10s just to move the network).

Curiously, the slow down did happen after a windows update, not after a SUMO update (SUMO version has been 0.28). Upgrading SUMO to the newest overnight built did not help.

Of course, all looks like a graphics driver problem. But all other OPENGL Apps, like Autocad, still run fast as normal."

Migrated from http://sumo.dlr.de/ticket/3162
```json
{
    "status": "new", 
    "changetime": "2017-06-05T18:06:08Z", 
    "description": "reported bei Joerg Schweizer \n\n\"2 out of 7 of my project students who use Windows 10 experienced slow\nzooming, simulation and tool handling of any kind. I am aware that the GUI is a little slow with zooming in when viewing the whole network (approx 14000 edges), but  editing gets fast when a smaller network area is visible. However, in this case, all operations remain slow (10s just to move the network).\n\nCuriously, the slow down did happen after a windows update, not after a SUMO update (SUMO version has been 0.28). Upgrading SUMO to the newest overnight built did not help.\n\nOf course, all looks like a graphics driver problem. But all other OPENGL Apps, like Autocad, still run fast as normal.\"", 
    "reporter": "namdre", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1496685968572620", 
    "component": "simulation gui (GUISIM)", 
    "summary": "slow gui on windows 10", 
    "priority": "major", 
    "keywords": "sumo-user", 
    "time": "2017-06-05T18:06:08Z", 
    "milestone": "1.0.0", 
    "owner": "", 
    "type": "defect"
}
```

**Comment by namdre** [comment]
@behrisch Any Idea what we could do here? Otherwise I'd close this as wont-fix / upstream

**Comment by behrisch** [comment]
Switching to the 32bit version helped as far as I remember. But I don't think we will investigate it until we really need to (e.g. need to switch to Windows 10 ourselves)
