### ISSUE TITLE
length of pt stops is limited by edge length (trac #3307)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#3307]
pt stops on edges that are shorter than a corresponding pt vehicle  cause an error in MSVehicle:

        if (myParameter->departPosProcedure == DEPART_POS_BASE || myParameter->departPosProcedure == DEPART_POS_DEFAULT) {
            pos = MIN2(static_cast<double>(getVehicleType().getLength() + POSITION_EPS), (*myCurrEdge)->getLength());
        }
        if (pos > stop.endPos) {
            if (stop.busstop != 0) {
                errorMsg = "Bus stop '" + stop.busstop->getID() + "'";
            } else {
                errorMsg = "Stop";
            }
            errorMsg += " for vehicle '" + myParameter->id + "' on lane '" + stopPar.lane + "' is before departPos.";
            return false;
        }

Migrated from http://sumo.dlr.de/ticket/3307
```json
{
    "status": "new", 
    "changetime": "2017-07-19T13:44:39Z", 
    "description": "pt stops on edges that are shorter than a corresponding pt vehicle  cause an error in MSVehicle:\n\n        if (myParameter->departPosProcedure == DEPART_POS_BASE || myParameter->departPosProcedure == DEPART_POS_DEFAULT) {\n            pos = MIN2(static_cast<double>(getVehicleType().getLength() + POSITION_EPS), (*myCurrEdge)->getLength());\n        }\n        if (pos > stop.endPos) {\n            if (stop.busstop != 0) {\n                errorMsg = \"Bus stop '\" + stop.busstop->getID() + \"'\";\n            } else {\n                errorMsg = \"Stop\";\n            }\n            errorMsg += \" for vehicle '\" + myParameter->id + \"' on lane '\" + stopPar.lane + \"' is before departPos.\";\n            return false;\n        }\n", 
    "reporter": "laemmel", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1500471879465335", 
    "component": "microsim - car following", 
    "summary": "length of pt stops is limited by edge length", 
    "priority": "major", 
    "keywords": "", 
    "time": "2017-07-19T13:44:39Z", 
    "milestone": "1.0.0", 
    "owner": "laemmel", 
    "type": "defect"
}
```

**Comment by namdre** [comment]
already fixed (#4367)

**Comment by ZoltanBaksa** [comment]
Hi,
How can I define a bus stop that is longer than an edge.
There are cases, when on a multi lane road the number of lanes changes next to a bus stop. See road structure around 51.462365, -0.115073 or 48.802875, 9.216424 as example scenes

**Comment by namdre** [comment]
Right now this isn't possible. A solution would probably come via #5115.
However, there are workarounds by using the parkingLength attribute if you need multiple vehicles to stop on a short stop (a single vehicle will always be able to stop regardless of length).

**Comment by ZoltanBaksa** [comment]
Thanks for linking, I did not found that issue during my search. It's ok to use the parking length, altough it is not obvious, if this length is measured from the startPos  forwardly or from the endPos backwards.

**Comment by namdre** [comment]
parking length does something similar to overriding the geometrical edge length. You can declare that between startPos 20 and endPos 30 there are 50m of space to park busses.
