### ISSUE TITLE
Custom selection color (trac #3367)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#3367]
Give the possibility of changing color of selected elements (currently blue) via configuration dialog.

Migrated from http://sumo.dlr.de/ticket/3367
```json
{
    "status": "new", 
    "changetime": "2017-09-01T06:46:40Z", 
    "description": "Give the possibility of changing color of selected elements (currently blue) via configuration dialog.", 
    "reporter": "pablo", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1504248400845285", 
    "component": "netedit", 
    "summary": "Custom selection color", 
    "priority": "minor", 
    "keywords": "selectoin", 
    "time": "2017-08-29T12:16:49Z", 
    "milestone": "1.1.0", 
    "owner": "", 
    "type": "enhancement"
}
```

**Comment by namdre** [comment]
This can already done for edges, junctions, pois and polys when setting coloring mode to 'color by selection' and customizing the colors there. This principle should be extened to other objects.

However, this requires some changes which also apply to sumo-gui.

**Comment by namdre** [comment]
added new settings tab a while ago.
