### ISSUE TITLE
geometrical collision on junction at lane split (trac #3398)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#3398]
when one lane has two successors on the next edge both internal lanes A and B are treated like parallel lanes for the purpose of lane changing. 
when there is a third parallel internal lane C, only the direct neighbor is checked for lane-changing even though both neighbors A and B are geometrically at some points.

This is only detected via option --collision.check-junctions

example: acosta 
lanes
:44_5_0
:44_5_1
:44_5_2

Migrated from http://sumo.dlr.de/ticket/3398
```json
{
    "status": "new", 
    "changetime": "2017-09-07T11:12:29Z", 
    "description": "when one lane has two successors on the next edge both internal lanes A and B are treated like parallel lanes for the purpose of lane changing. \nwhen there is a third parallel internal lane C, only the direct neighbor is checked for lane-changing even though both neighbors A and B are geometrically at some points.\n\nThis is only detected via option --collision.check-junctions\n\nexample: acosta \nlanes\n:44_5_0\n:44_5_1\n:44_5_2", 
    "reporter": "namdre", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1504782749563764", 
    "component": "microsim - lane change", 
    "summary": "geometrical collision on junction at lane split", 
    "priority": "major", 
    "keywords": "", 
    "time": "2017-09-07T11:11:49Z", 
    "milestone": "1.0.0", 
    "owner": "", 
    "type": "defect"
}
```

**Comment by namdre** [comment]
this is handled via getLeaderInfo which knows about sibling lanes. Any remaining issues with this are handled via #4463
