### ISSUE TITLE
when importing networks with --ptline-output, ensure that edges have correct permissions (trac #3437)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#3437]
i.e. in some places a bus line uses a way of type highway=pedestrian. The affected edges should have their permissions extended to accommodate this automatically.

Migrated from http://sumo.dlr.de/ticket/3437

related to #4384

**Comment by namdre** [comment]
In berlin, the s-bahn tracks are tagged with ligh_rail whereas the public transport lines are marked as "train" instead of "light_rail"
