### ISSUE TITLE
platform-dependent screenshots (trac #3449)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#3449]
most likely caused by different canvas size due to variations in window-toolkit implementation/styling.

A possible solution would be to use option --window-size for the canvas size rather than the whole window size (as already done for netedit in testing mode)

Migrated from http://sumo.dlr.de/ticket/3449
```json
{
    "status": "new", 
    "changetime": "2017-09-20T08:55:00Z", 
    "description": "most likely caused by different canvas size due to variations in window-toolkit implementation/styling.\n\nA possible solution would be to use option --window-size for the canvas size rather than the whole window size (as already done for netedit in testing mode)", 
    "reporter": "namdre", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1505897700924413", 
    "component": "Test system", 
    "summary": "platform-dependent screenshots", 
    "priority": "minor", 
    "keywords": "", 
    "time": "2017-09-20T06:36:34Z", 
    "milestone": "1.0.0", 
    "owner": "", 
    "type": "defect"
}
```

**Comment by namdre** [comment]
The only real problem with this is multiplatform test replication. @behrisch  Could we also fix this with a smarter diff tool (as we do for floats)?

**Comment by behrisch** [comment]
Yes, we should close this in favor of #1179
