### ISSUE TITLE
finalize trac import

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#3550]
* rerun script to finalize assignees
* check whether there are valuable attachments
* check whether anything in the wiki needs to be migrated

**Comment by behrisch** [comment]
Assigning is done but we will keep the trac instance alive so the other two points won't be done. Another point is switching the instance to git.

**Comment by palvarezlopez** [comment]
@behrisch it's finished?

**Comment by behrisch** [comment]
The old instance is not alive any longer but nobody seems to miss it.
