### ISSUE TITLE
allow asymmetrical lane-change restrictions

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#3656]
- [x] add optional lane attributes `changeLeft`, `changeRight` (each encoding a list of vClasses that may change in this direction
  - [x] netconvert
  - [x] netedit
- [x] add optional connection attributes `changeLeft`, `changeRight` (each encoding a list of vClasses that may change in this direction
  - [x] netconvert
  - [x] netedit
- [x] use new attributes in MSLaneChanger::mayChange
- [x] use new attributes in MSVehicle::updateBestLanes
- [x] use attribute to restrict opposite-direction driving
- [x] change line drawing style when passenger cars may not change in a given diretion (drawing double lines if asymmetrical)
- [x] update documentation
- ~~[ ] import lane changing restrictions from network input that contains this data (OpenDRIVE, OSM?)~~ (moved to other tickets #8821, #8822)
- [x] swap interpretation for left-hand networks
  - [x]  when loading in sumo
  - [x] when converting between LHT and RHT with netconvert
related: #2653, #2739, #8055

**Comment by namdre** [comment]
lane change restriction may only be applicate to a subset of vehicle classes

**Comment by namdre** [comment]
implement 'changeLeft', 'changeRight'  (#7595)

**Comment by behrisch** [comment]
@namdre Do changeLeft and changeRight keep the semantics with left hand networks?

**Comment by namdre** [comment]
No. At the moment, left corresponds to increasing lane index and right to decreasing lane index and the lane indices always count from the outside to the road center line.
It would be trivial to swap the interpretation on loading.

**Comment by behrisch** [comment]
I have no clear preference here, just wondered how the average left hand driver is supposed to use this.
