### ISSUE TITLE
more bidirectional tracks from OSM

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#3687]
Continuing from #2987 and reading the tagging guide http://wiki.openstreetmap.org/wiki/OpenRailwayMap/Tagging again, tracks inside stations are always considered bidirectional. Detecting them could be a matter of detecting a node with railway=station having a relation. Some other indicators are an existing railway:track_ref (Gleis) or the presence of maxspeed:forward and maxspeed:backward. Maybe also looking for railway:bidirectional.

**Comment by namdre** [comment]
fixed via #5531, stations are handled via --railway.topology.repair
