### ISSUE TITLE
nVehEntered does not count vehicles on detector (trac #371)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#371]
This might be a documentation bug only http://sourceforge.net/apps/mediawiki/sumo/index.php?title=SUMO_OUTPUT_E1#Generated_Output but from the docs I would expect that the induction loop output nVehEntered includes the number of vehicles which are still on the detector. For an example see source:trunk/sumo/tests/sumo/output/examples/cross3ltl_inductloops/detector.sumo (the 2si_1 detector in the interval 187-188)

Migrated from http://sumo.dlr.de/ticket/371
```json
{
    "status": "assigned", 
    "changetime": "2013-12-10T11:45:42Z", 
    "description": "This might be a documentation bug only http://sourceforge.net/apps/mediawiki/sumo/index.php?title=SUMO_OUTPUT_E1#Generated_Output but from the docs I would expect that the induction loop output nVehEntered includes the number of vehicles which are still on the detector. For an example see source:trunk/sumo/tests/sumo/output/examples/cross3ltl_inductloops/detector.sumo (the 2si_1 detector in the interval 187-188)", 
    "reporter": "behrisch", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1386675942063540", 
    "component": "simulation data output", 
    "summary": "nVehEntered does not count vehicles on detector", 
    "priority": "major", 
    "keywords": "", 
    "time": "2010-10-06T10:48:25Z", 
    "milestone": "1.0.0", 
    "owner": "bieker", 
    "type": "defect"
}
```

**Comment by lbieker** [comment]
The documentation was already updated here http://sumo.dlr.de/wiki/Simulation/Output/Induction_Loops_Detectors_(E1)
