### ISSUE TITLE
Collision on opposite direction overtaking

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#3718]
see failing test. the test shows also a vehicle stopping directly after changing to the opposite lane.

**Comment by namdre** [comment]
this happens because the distance to leader vehicles which are also driving in the opposite direction is calculated wrong.

**Comment by namdre** [comment]
leader vehicles that are also driving in the opposite direction are wrongly classified as oncoming leaders and wrongly trigger a return to the forward lane.

**Comment by namdre** [comment]
follower vehicles on the opposite direction lane (which are also overtaking through the opposite direction) are ignored even though they are too fast to brake safely.

**Comment by namdre** [comment]
while driving in the opposite direction and considering the remaining distance before an oncoming vehicle, no safety buffer is maintained.

**Comment by namdre** [comment]
vehicles rescind their decision to overtake because LC2013 uses a different formula for computing the remaining time to complete a lane change. This cause vehicles to slow down on the opposite direction lane and traps them (related to #4563)

**Comment by namdre** [comment]
when computing overtaking time, leader acceleration is ignored

**Comment by namdre** [comment]
wrong speed used when computing leader safe-gap in computeOvertakingTime

**Comment by namdre** [comment]
no more collisions after fixing #4563.

**Comment by namdre** [comment]
lack of collisions was due to randomness/luck
