### ISSUE TITLE
'cleanup states' in traffic light mode sometimes takes no effect

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#3725]
after saving and reloading the network it works again.

**Comment by behrisch** [comment]
Accidentally closed by typo in commit message

**Comment by palvarezlopez** [comment]
The entire GNETrafficLightFrame must be checked and tested

**Comment by palvarezlopez** [comment]
In other cases produces a crash (See #3773)

**Comment by namdre** [comment]
should be fixed now
