### ISSUE TITLE
Slowdown during grabbing in nets with a high number of elements

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#3794]
In a big net (For example, test/netElements/crossings/load_big) there is a slowdown moving net using click-grabbing. Zoom using mouse wheel or move view using arrow keys doesn't affect.

Thanks to Andrea Giaccherini for report it.

**Comment by palvarezlopez** [comment]
The problem is caused by a strange delay between click and moving mouse

**Comment by palvarezlopez** [comment]
Problem is caused by function _GNEViewNet::onLeftBtnPress(FXObject*, FXSelector, void* eventData)_. The delay in the movement is the delay from beging of funciton to calling of function _processClick(e, eventData);_

**Comment by palvarezlopez** [comment]
The main delay is caused by function getObjectUnderCursor() (652)

**Comment by namdre** [comment]
getObjectAtPosition should only consider objects where the bounding box overlaps with a small area around the cursor (0.2mx0.2m).
Possibly, some simulation objects have an invalid bounding box.
Please debug the set of objects that are returned by the call getObjectsInBoundary(selection) in line 316

There is definitely a problem with objects that have a "diagonal" shape because their bounding box is much bigger then the object itself.

**Comment by palvarezlopez** [comment]
@namdre The number of objects returned by _getObjectsInBoundary(selection)_ is correct (Normally 0 or 1). I see, that in function GUISUMOAbstractView::getObjectsInBoundary(const Boundary& bound) the number of hints is very hight, but almost all are 0. This behavior is normal?

![unbenannt](https://user-images.githubusercontent.com/8238561/36193715-3e7e6f9e-1167-11e8-813b-3ac73326c1b1.png)

**Comment by palvarezlopez** [comment]
I found a solution for this problem. Now the performance is the same in SUMO-GUI and Netedit. But I think that can be mehr improved.

**Comment by palvarezlopez** [comment]
The solution causes an error moving elements

**Comment by namdre** [comment]
the array 'hits' is pre-allocated and thus may contain arbitary stuff. The critical value is 'nb_hits'.
If that number is usually low, then object boundaries are not the issue.
