### ISSUE TITLE
Allow editing lane's and edge's stopOffset parameter in netedit

### ISSUE THREAD

**Issue by leoluecken** [eclipse/sumo#3799]
Although defined as a child element in the net.xml, the stopOffset-value and stopOffset-exceptions, resp. stopOffset-vClasses, can be treated as lane-/edge-attributes in netedit, since currently only one offset value is allowed. Further it is allowed to either define exceptions or vClasses, but not both. The semantics are as for permissions.

**Comment by namdre** [comment]
could be treated like params in the UI. (serialized into a single string and edited with a dialog).
However, further thought should first be give on simplification of the xml data model.

**Comment by namdre** [comment]
new virtual attributes
- edge: stopOffset (optional double, default empty
- edge: stopOException (optional vClasses-list, default empty, disabled when stopOffset is empty)
- lane:  stopOffset (optional double, default empty
- lane:  stopOException (optional vClasses-list, default empty, disabled when stopOffset is empty)

**Comment by namdre** [comment]
Some netconvert stop offset tests are failing now
