### ISSUE TITLE
data dir missing from ubuntu package

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#3802]
especially the xsds should be there. We also should think about a mechanism to set SUMO_HOME to /usr/share/sumo when installing

**Comment by gladk** [comment]
Adding some more dirs/files into the package is not a problem at all. Setting SUMO_HOME is almost not possible. What is the goal of having this variable?  Where is it used?

**Comment by behrisch** [comment]
The goal is detecting the installation dir. We have a lot of python scripts which do not get installed into /usr/bin (well maybe they should) and data files like xsds or our own type maps for street types and emission data. They get located relative to the SUMO_HOME dir.

**Comment by naweiss** [comment]
Is this going to be fixed?

**Comment by behrisch** [comment]
This should be fixed at least in the sumo ppa.
