### ISSUE TITLE
Add TraCI function for relative lane change

### ISSUE THREAD

**Issue by lbieker** [eclipse/sumo#3844]
At the moment it is only possible to set the lane index for a lane change. Especially, for overtaking at the opossing edge it is necessary to have a relative lane change. The vehicle should change one lane to right with -1 and one to the left with 1.

**Comment by namdre** [comment]
@lbieker can this be closed?

**Comment by lbieker** [comment]
At the moment only relative lane changes on the current edge are working. It is missing to change to the opposite direction

**Comment by namdre** [comment]
currently, relative lane change also works with +2 but not with -2. It would be good to also allow the latter (lane checking should be moved from traci-server into libsumo/Vehicle.cpp).

**Comment by lbieker** [comment]
It needs to be documented that the duration needs to be large enough to perform the lane changes
