### ISSUE TITLE
sumo-gui issue

### ISSUE THREAD

**Issue by iamxg** [eclipse/sumo#3866]
Hi,
The frequent of “time” addition is very slow in Sumo-GUI. That is to say, the time value will increase 0.1 after a few seconds. The configuration file is as follows. Could you let me know where this issue may be?
Best Regards,
Xian

<?xml version="1.0" encoding="UTF-8"?>

<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/sumoConfiguration.xsd">

    <input>
        <net-file value="osm.net.xml"/>
        <route-files value="osm.rou.xml"/>
        <additional-files value="osm.poly.xml"/>
    </input>

    <output>
        <tripinfo-output value="maptripinfo.out.xml"/>
    </output>

    <time>
        <begin value="0"/>
        <end value="1000"/>
        <step-length value="0.1"/>
    </time>

    <report>
        <verbose value="true"/>
        <duration-log.statistics value="true"/>
        <no-step-log value="true"/>
    </report>

    <traci_server>
         <processing>
                <time-to-teleport value="100"/>
         </processing>
         <remote-port value="8813"/>
    </traci_server>

    <gui_only>
        <gui-settings-file value="osm.view.xml"/>
    </gui_only>

</configuration>

**Comment by namdre** [comment]
- if you have lots of vehicles in the simulation, it may be come slow (how many do you have at the same time?)
- if many vehicles cannot be inserted due to lack of road space the simulation may become slow (check the number of vehicles that have their insertion delayed in the simulation parameter dialog)
- if you are sending a lot of traci commands the simulation may become slow as well

**Comment by iamxg** [comment]
Hi，
Thank you very much for your timely replying. 
I try to simulate 200 vehicles. I set different delay values. But it didn't work. I found that this issue seem be only relative with the line "<remote-port value="8813"/>". It was normal when I deleted this line. But I can't get vehicle's location. So, maybe it is the third reason that you mentioned. But I don't know how to resolve it.
Thanks a lot.
Xian

**Comment by behrisch** [comment]
Which line do you refer to? Could you send your script?

**Comment by iamxg** [comment]
Hi，
So sorry. The line that I copied didn't displayed. It is '<remote-port value="8813">'. 
I find that it can normally work when there are about 30-40 vehicles in the simulation network. It will become very slow if the number of vehicles are greater than 50.  
Have a good day!
Xian

**Comment by iamxg** [comment]
Hi,
This line still don't displayed. It is 'remote-port value="8813"'
Sorry!

**Comment by behrisch** [comment]
Depending on the way you start the traci server the remote port is necessary. Can you send your scenario / script?

**Comment by iamxg** [comment]
Hi,
How are you!
My scenario scripts are in here https://github.com/iamxg/minindn-wifi/tree/master/mem-data. And SUMO module is called by line  "sumo_vndn.useExternalProgram('sumo-gui', config_file='map.sumocfg')" in program https://github.com/iamxg/minindn-wifi/blob/master/ndnwifi/sumo_vndn.py. My purpose is that I create a emulation network for vehicle, and need to map each vehicle in the network to vehicle in SUMO environment. And then I hope that I can evaluate performance of protocol, for routing etc.
Thank you very much for your time.
Best Regards.
Xian

**Comment by behrisch** [comment]
This is quite a complex environment. Can you extract a minimal example which shows the behavior?

**Comment by iamxg** [comment]
Hi Behrisch,
Thank you very much for your attention. This is a simple example used SUMO. 
https://github.com/intrig-unicamp/mininet-wifi/blob/master/examples/sumo-experimental.py
Best Regards,
Xian Guo

**Comment by behrisch** [comment]
This seems to require root rights, at least I get this one:
*** Mininet-WiFi must run as root.

**Comment by namdre** [comment]
closing as outdated.
