### ISSUE TITLE
rail crossings without roads waste processing time

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#3868]
by design, step duration should not increase when adding unused parts of the network. The KIT-demo scenario shows otherwise.

**Comment by behrisch** [comment]
even without routing (and trafficlights)?

**Comment by namdre** [comment]
I just realized that the network contains 46k rail crossings which compute their state even though they do not cross any roads.

**Comment by namdre** [comment]
rail crossings without roads are no longer generated by netconvert
