### ISSUE TITLE
rename generated traffic lights

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#3871]
currently, the id is built with a prefix and a running index. It would be more useful to incorporate the junction id(s) into the tls id.

- joined_nodeA_nodeB_nodeC
- guessed_nodeD
- guessedSignals_nodeE

**Comment by namdre** [comment]
for some reason, renaming joined tls affects the simulation behavior of the webwizard tests. I'm guessing it is related to actuated traffic lights.

**Comment by namdre** [comment]
There should be an option for backward-compatibility and the naming scheme should probably be consistent with #10795

**Comment by behrisch** [comment]
@namdre Apart from the "joined" there are some open questions:

- Concerning 29ed3af it seems the "joined_" ids actually do not occur (except for warning output) but only "joinedS_", Is this intentionally?
- Should we really distinguish guessed TLS from imported ones via the name? Wouldn't an attribute or param be better?
- The param / attribute approach would also better fit for the programs and thus make the distinction of guessed and guessedSignals obsolete. Do you agree?

**Comment by namdre** [comment]
At some point I still want to distinguish the three different heuristics in the generated network
- pre-defined controlled junctions that were fused into a joined tls (from **--tls.join**)
- pre-defined 'simple' tls that actually belong to a central junction (from **--tls.guess-signals**)
- guessed clusters that had no tls info in the input (from **tls.guess.joining**)

Doing this via the name has the advantage of making them easy to distinguish via the locate dialog.
There is currently no method to search for traffic lights based on their param in sumo-gui or netedit.
I guess I could live with the param approach and maybe we'll add some tooling for this but we could as well save our effort for other tasks and keep some name prefixes.

**Comment by behrisch** [comment]
The consensus for the new id style was

- joinedS_nodeA_nodeB for traffic lights being joined by `--tls.join`
- joinedG_nodeC_nodeD for traffic lights being joined by `--tls.guess.joining`
- GS_nodeE for guessed signals
- no separate prefix for guesses TLS in general
