### ISSUE TITLE
SUMO TRACI in LINUx SYstem

### ISSUE THREAD

**Issue by chmene** [eclipse/sumo#3891]
Dear all, 

I am using SUMO sim in both  Linux (CentOs 6.9) and Windows (10)  operating systems! More specific i am using traci4matalb in both systems in similar specs PCs  and over the  same Matlab version! Unfortunately any traci commands executes 40x more quick in windows environment rather the Linux one! Does anyone knows why this happens? Do i require any Library or i am missing something in order to speed up traci commands execution in Linux OS?

Thanks in Advance,
C.

**Comment by namdre** [comment]
Hello,
we have not noticed such a discrepancy with other clients (i.e. python) so I would guess this is somehow related to the way matlab does socket communication on linux. I'm forwarding this issue to the matlab client maintainer. Possibly he has an idea.

**Comment by namdre** [comment]
wont-fix
