### ISSUE TITLE
Fine-grained phase generation and control for intersection links and traffic lights in netgenerate

### ISSUE THREAD

**Issue by chrisshen** [eclipse/sumo#3892]
This is an improvement suggestion.
I am not sure if anyone has already proposed this.

I am using netgenerate to generate grid map for research, particularly I'm working on traffic light control. In the current version (sumo-0.32.0) of the netgenerate tool, the --tls option can allow to guess a default static traffic light schedule. 

However, the generated static traffic light schedule seems does not consider **right-turn through**, i.e., always letting right-turn be green light. The netedit tool can do the trick, the thing is that if the road network is small, using netedit is OK, but when the network is large, like including a lot of intersections, using netedit is a manual labor. 

Another suggestion is that adding a function to netgenerate that can specify link connection at intersections. e.g., **separate left-turn link and straight link**. 

Thanks!

**Comment by behrisch** [comment]
You could load traffic light programs from a file, but I agree having some influence here would be great.

**Comment by namdre** [comment]
Hello,
you can already get right-turn through by setting the netgenerate option
--default-junction-type traffic_light_right_on_red

If you need to change many network objects at once, you can first select
them in netedit (i.e. in select mode, select all junctions of type
traffic_light) and then set the attribute (i.e. junction type) for all of
them simultaneously in inspect mode.

Regarding your other suggestion, do you refer to the way lane-to-lane
connectivity is set up (i.e. create turning lanes 20m ahead of the
intersection)?
Or do you refer to the way left turns are treated within the signal program
(i.e. duration of an extra left-turn phase)?

regards,
Jakob



2018-03-13 13:33 GMT+01:00 Michael Behrisch <notifications@github.com>:

**Comment by chrisshen** [comment]
Hi @behrisch and @namdre ,

Thank you for your reply.

I checked the netgenerate option as follows:
```bash
-j, --default-junction-type STR      [traffic_light|priority|right_before_left] Determines the type of the build junctions
```
The option you mentioned is not here, but I found those **junction-type options in the netedit**. Then I use this option, traffic_light_right_on_red, to generate traffic light schedule, get this schedule:

```xml
<tlLogic id="2/1" type="static" programID="0" offset="0">
        <phase duration="33" state="GGgsrrGGgsrr"/>
        <phase duration="3" state="yygsrryygsrr"/>
        <phase duration="6" state="rrGsrrrrGsrr"/>
        <phase duration="3" state="rrysrrrrysrr"/>
        <phase duration="33" state="srrGGgsrrGGg"/>
        <phase duration="3" state="srryygsrryyg"/>
        <phase duration="6" state="srrrrGsrrrrG"/>
        <phase duration="3" state="srrrrysrrrry"/>
</tlLogic>
```
I found the **"s" signal state**, which is not explained in [Signal_state_definitions](http://www.sumo.dlr.de/wiki/Simulation/Traffic_Lights#Signal_state_definitions).

I guess the document needs to be updated.

The other suggestion I propose is to have a option to **separate left-turn link and go-straight link** in netgenreate, i.e., as shown in the following figure:

![eg1](https://user-images.githubusercontent.com/4958558/37445625-60c5f232-285c-11e8-8223-227bcc587fc1.png)

By default, the left-turn link and go-straight link are grouped together, here I use netedit to remove the go-straight link as you can see from the figure.

My suggestion for netgenerate is giving user more freedom to decide the link connection setting.

Thank you for your help!
Chris.

**Comment by namdre** [comment]
Thank you for pointing out the gaps in documentation.
The following items have been updated: 
* http://sumo.dlr.de/wiki/Simulation/Traffic_Lights#Signal_state_definitions
* netgenerate help text

**Comment by namdre** [comment]
Regarding the connection building, I'm questioning whether the above situation is common enough to warrant an option. Possibly, what is actually needed is an option for something like the configuration below. What do you think?
![grafik](https://user-images.githubusercontent.com/6240630/37454897-0cae1d2a-283c-11e8-8e04-0cd25f21a67c.png)

**Comment by tomerkay** [comment]
Is it possible to disable the minor turn-left completely? meaning there won't be and "g" lights and only "G" lights.

**Comment by namdre** [comment]
the network shown above can now be generated using options --turn-lanes and turn-lanes.length
