### ISSUE TITLE
Disable calls to gSelected.isSelected(...) in al drawgl() functions

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#3897]
In big nets, when all elements of the same type (for example, edges) are selected, the call to the function "gSelected.isSelected(...)" produces a delay. The call to function has to be replaced with a boolean variable called "mySelectedElement" in GNENetElement and GNEAdditional.

**Comment by namdre** [comment]
Could this be responsible for #3794 ?
Maybe it would make sense to upgrade the 'selected' bool to a proper netedit attribute (like 'locked').

**Comment by palvarezlopez** [comment]
@namdre I think no, because if there isn't selected elements in the net, the call to the function gSelected.isSelected(...) is constant, but the problem #3794 remains.

**Comment by palvarezlopez** [comment]
@namdre about "select" as attribute, I think that can be usefull.

**Comment by palvarezlopez** [comment]
All regressions fixed, issue solved and added more test.
