### ISSUE TITLE
Sometimes Cmake takes the GDAL directory as the xerces directory

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#3901]
Due GDAL directory contains the Xerces Library, some random times CMake takes the GDAL directory as the Xerces directory, and their xercesC-3.1.lib as library. This produces a compilation error

```
//Xerces-C++ include directory
XercesC_INCLUDE_DIR:PATH=C:/Libraries/proj_gdal-1911_64/include

//Xerces-C++ libraries (debug)
XercesC_LIBRARY_DEBUG:FILEPATH=C:/Libraries/xerces-c-3.2.0_64/lib/xerces-c_3D.lib

//Xerces-C++ libraries (release)
XercesC_LIBRARY_RELEASE:FILEPATH=C:/Libraries/proj_gdal-1911_64/lib/xerces-c_3.lib
```

The solution is to define in CMAKEList.txt the variable SUMO_LIBRARIES_DIRECTORY, that automatically fill all CMake fields with the libraries and folders structured in project SUMOLibraries

**Comment by palvarezlopez** [comment]
@behrisch It's the same methode that use OSG. What do yo think?
![cmake_sumolibraries](https://user-images.githubusercontent.com/8238561/37515786-4122146e-290c-11e8-9759-b9b24b62c378.png)

**Comment by behrisch** [comment]
I added the functionality to look for SUMOLibraries to the buildcmake script. If we change the search order so that we look first into SUMOLibraries and then in PATH this should solve it already without modifying CMakeLists.txt.

**Comment by palvarezlopez** [comment]
I think that this solution is useful, but is incomplete. If both folders (proj_gdal and xerces) are in the PATH, CMake sometimes look first in proj_gdal and find a Xerces version that produces a compilation error. The solution is forcing CMake to take the Xerces Variables (XercesC_INCLUDE_DIR, XercesC_DEBUG and XercesC_RELEASE)

**Comment by palvarezlopez** [comment]
There is a way to "force" the use of correct library paths without writing a new XercesC finder. I'm going to open a branch called "CMake_NewFeatures" to implement it.

**Comment by palvarezlopez** [comment]
Problem fixed using enviroment Variable SUMO_LIBRARIES
