### ISSUE TITLE
inconsistency in road width between drawing and simulation

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#3972]
when generating lane geometries from a road reference line, there is an offset of 0.1 between them (SUMO_const_laneOffset) for lane-markings but when changing lanes this offset is not considered.

Likewise, at roads with laneSpread="right" going in both directions, the total road width includes SUMO_const_laneOffset for the center-line marking.

One possible solution would be to keep the simulation code and abolish the lane-offset. Road-markings could be drawn on top of the lanes rather than between them.

**Comment by gprichter** [comment]
there seems to be a remaining problem-fragment
netconvert on an xodr file and subsequent rendering shows these discrepancies.
![side-by-side_s](https://user-images.githubusercontent.com/33460332/38671865-d18f12a4-3e4c-11e8-8b66-172223b06ab3.png)
where lane_data are the rendered xodr lane slabs, hatched are the rendered sumo lane slabs, cyan sumo lane center lines.
there is a "shoulder" type lane of 0.4m width on the very left which is not considered in the netconvert process.
adding arguments `--opendrive.min-width=0.1 --opendrive.import-all-lanes` did not help.

**Comment by namdre** [comment]
Shoulder lanes are explicityly discared in the default typemap
(data/typemap/opendriveNetconvert.typ.xml) and this takes precedence over
the option --opendrive.import-all-lanes.
Using another typemap should solve this.



2018-04-12 12:31 GMT+02:00 Gerald Richter <notifications@github.com>:
