### ISSUE TITLE
moving edge geometry at sharp edges was broken in recent commit

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#3985]
in move mode, trying to grab a geometry point at a sharp corner does not work.

Before, grabbing the geometry point anywhere would always register as a click on the edge. In the current version it only works when clicking on the geometry point where it overlaps with the edge itself.
At sharp corners there is no overlap so the point cannot be moved at all.

**Comment by palvarezlopez** [comment]
@namdre enabling the drawn of GeometryPoints in GUIVisualizationSettings::drawForSelecting mode produces the bug #3794.
