### ISSUE TITLE
crash after splitting an edge

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#3986]
reproduce:

- load tests/sumo/net2.net.xml
- split edge SC in the middle
- set numLanes to 3 for the upper part
- F5
- undo

**Comment by namdre** [comment]
was working in 0.32.0

**Comment by palvarezlopez** [comment]
@namdre Probably it's caused by the same bug as the bug #3779

**Comment by namdre** [comment]
i'll check this.

**Comment by namdre** [comment]
the bug was unrelated to #3779 even though the crash took place in the same function.
