### ISSUE TITLE
Issue with "Set custom junction shape" in NETEDIT

### ISSUE THREAD

**Issue by sumo-fanclub** [eclipse/sumo#3988]
Hi,
Clicking on the "Set custom junction shape" option seems to modify the shape, even before any modifications was actually done.

![image](https://user-images.githubusercontent.com/37397574/38657709-4c477890-3e54-11e8-911c-fa59f58eef8b.png)
![image](https://user-images.githubusercontent.com/37397574/38657712-50dda438-3e54-11e8-8c10-c3defbaae270.png)
![image](https://user-images.githubusercontent.com/37397574/38657716-54db738a-3e54-11e8-8487-765fc2b14160.png)

**Comment by namdre** [comment]
can you check whether this only happens in lefthand networks?

**Comment by sumo-fanclub** [comment]
Yes, just checked and this issue seems to only occur in lefthand networks
