### ISSUE TITLE
Weird behavior when using traci's vehicle.moveToXY(...)

### ISSUE THREAD

**Issue by sumo-fanclub** [eclipse/sumo#3993]
Hi,
When setting position of a vehicle using traci's vehicle.moveToXY(...) with keepRoute value of 2, the following message is sometimes printed in SUMO:
`Warning: Vehicle '0' performs emergency stop at the end of lane '-gneE16_0' for unknown reasons (decel=0.00, offset=0.07), time=52.99`
Following that, the vehicle '0' is then removed from simulation:
`Error: Answered with error to command 0xc4: Vehicle '0' is not known`

**Comment by namdre** [comment]
this could happen if the vehicle does not receive a moveToXY command in each simulation step. Basically, the vehicle has a route which consists only of the current edge, it reaches the end of that edge with high speed and has nowhere to go. 
You can avoid this by setting the route or continue issuing moveToXY commands.
If this does not solve your problem, please provide an example scenario.

**Comment by sumo-fanclub** [comment]
PFA sample project that demonstrates the issue. 
In `main.cpp` in line 174, where I call the `simulationStep()` function, if I scale `dt` to thrice its value or higher (i have `dt*10` in the code), the simulation core-dumps with 
```
terminate called after throwing an instance of 'tcpip::SocketException'
  what():  .. Answered with error to command (196), [description: Vehicle 'remote_vehicle' is not known]
Aborted (core dumped)
```
Seems like the `remote_vehicle` that we try to control is removed from the simulation. The simulation proceeds smoothly when `dt` is not scaled. 

**Questions:**
1. Why is the "remote_vehicle" removed from the simulation?
2. What are the bounds for the `time` parameter we pass into the `simulationStep()` function?

**P.S:**: You will have to fix the path in line 74 in `main.cpp`, to get my code running.
[SumoTraciTest.tar.gz](https://github.com/eclipse/sumo/files/1927576/SumoTraciTest.tar.gz)
[test_map.tar.gz](https://github.com/eclipse/sumo/files/1927579/test_map.tar.gz)

**Comment by sumo-fanclub** [comment]
Thanks for getting back. I am indeed calling moveToXY before every `simulationStep` (line 145). We noticed that the vehicle is removed only if the time value we pass to the `simulationStep` function call is large. Does that mean if one call to TraCI `simulationStep` internally performs multiple steps, I need to ensure the route extends beyond the current edge?

**Comment by namdre** [comment]
Yes. When I said 'simulation step' I was thinking of the internal stepping of the simulation. 
Most of the time, people just call traci.simulationStep() so there is not difference in meaning but when you call it with a time value the simulation may indeed perform multiple steps for one call of traci.simulationStep.

**Comment by namdre** [comment]
The current behavior is within spec. The documentation has been clarified at http://sumo.dlr.de/wiki/TraCI/Change_Vehicle_State#move_to_XY_.280xb4.29
