### ISSUE TITLE
Disable labels from POI and POILanes if owns a valid imgFile

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#3998]
@yunpangfloetteroed need it.

**Comment by namdre** [comment]
does 'label' mean its 'id'?
does 'bild' mean 'imgFile'?

**Comment by palvarezlopez** [comment]
@namdre with "Label" means the words "POI" and "POILane" draw over circles

![unbenannt](https://user-images.githubusercontent.com/8238561/38854369-c169dbd6-420f-11e8-837c-220ae0f5fdbb.png)

(And with 'bild' I mean ''imgFile' before mix German and English...

**Comment by namdre** [comment]
Oh. I wasn't even aware of these labels. I don't think they are really necessary (no other objects has such a label).  If a user needs to distinguish them visually (and not via inspect mode) a selection filter can be used to color them. This would also be a simpler solution to yunpangs request (-:

I think the labels are not needed in either case
