### ISSUE TITLE
selection modification mode was broken in recent commit

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#4001]
mode 'add' is always used. options keep,remove and replace do not work

**Comment by namdre** [comment]
reproduce: 
open tests/sumo/net2.net.xml
select all edges
switch selection mode to 'replace'
perform rectangle selection around 2 edges
expected result: only two edges select. Instead all edges remain selected

**Comment by palvarezlopez** [comment]
@namdre It's correct. I have only tested using "match selection", not using rectangle selection, because I didn't know that "modification mode" affects also to rectangle selection. I'm going to add an extra test.

**Comment by palvarezlopez** [comment]
More test added and issue fixed.
