### ISSUE TITLE
Non-ASCII paths are copied into output XMLs without re-encoding to UTF-8

### ISSUE THREAD

**Issue by jprk** [eclipse/sumo#4004]
I am using the current Git snapshot on Windows to run some tests and at the same time verify the behaviour of SUMO with accented paths. When processing the output data (detectors, lane info, tlsStates), XML parsers go berserk when digesting the initial comment with SUMO configuration:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- generated on Tue Apr 17 20:16:24 2018 by SUMO gui Version UNKNOWN
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/sumoConfiguration.xsd">
    <input>
        <net-file value="D:\Data\Dropbox\K611\PROJEKTY\2016%20MAVEN\MAVEN%20osobní\Sumo\Zlicin\osm.zlicin.495-601.net.xml"/>
        <route-files value="D:\Data\Dropbox\K611\PROJEKTY\2016%20MAVEN\MAVEN%20osobní\Sumo\Zlicin\osm.conventional_30_70_1800.trips.xml,D:\Data\Dropbox\K611\PROJEKTY\2016%20MAVEN\MAVEN%20osobní\Sumo\Zlicin\osm.automated_30_70_1800.trips.xml"/>
        <additional-files value="D:\Data\Dropbox\K611\PROJEKTY\2016%20MAVEN\MAVEN%20osobní\Sumo\Zlicin\sanity_test.additionals.xml"/>
    </input>
[...]
    <gui_only>
        <gui-settings-file value="D:\Data\Dropbox\K611\PROJEKTY\2016%20MAVEN\MAVEN%20osobní\Sumo\Zlicin\osm.view.xml"/>
        <tracker-interval value="0.1"/>
    </gui_only>
</configuration>
-->

<detector xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/det_e1_file.xsd">
    <interval begin="0.00" end="1.00" id="e1Detector_e5.601A_0_DVA" nVehContrib="0" flow="0.00" occupancy="0.00" speed="-1.00" length="-1.00" nVehEntered="0"/>
[...]
</detector>
```

The file is namely windows-1250 encoded, and not utf-8 encoded -- the cause is the path component `D:\Data\Dropbox\K611\PROJEKTY\2016 MAVEN\MAVEN osobní\Sumo\Zlicin` that gets inserted by SUMO and probably on Windows machines the path will be still windows-1250 encoded unless one specifically asks for the "wide" string ...

My guess is that this problem is only Windows related but I have not tested it on other operating systems yet, sorry.

**Comment by palvarezlopez** [comment]
Hi. I updated yesterday the Xerces libraries of project [SUMOLibraries](https://github.com/DLR-TS/SUMOLibraries). I'm not 100% sure, but I think that recompiling SUMO with these updated Xerces library can solve your problem. Can you check it please?

**Comment by jprk** [comment]
@palvarezlopez, I am unable to verify at the moment, see #4005 ... I will go through recent commits and I will optionally try to downgrade back to older SUMOLibraries version to see if it not the cause.
