### ISSUE TITLE
Regression in accented paths handling

### ISSUE THREAD

**Issue by jprk** [eclipse/sumo#4005]
@palvarezlopez, @namdre I have just built the current Git master on Windows using the current master branch of SUMOLibraries to test the problem referenced in #4004 and it seems that there is a regression in accented path handling:
```
Error: Could not access configuration 'D:\Data\Dropbox\K611\PROJEKTY\2016 MAVEN\MAVEN osobní\Sumo\Zlicin\sanity_test.sumocfg'.
Quitting (on error).
```
moving to directory without spaces:
```
Error: Could not access configuration 'D:\temp\MAVEN\Zličín\sanity_test.sumocfg'.
Quitting (on error).
```
the same if the path is okay but the configuration file itself is accented:
```
Error: Could not access configuration 'D:\temp\MAVEN\Zlicin\sanity_test_ěščřžýáíéů.sumocfg'.
Quitting (on error).
```
and in case that the path and config file name are not accented, but the network file is windows-1250 or UTF-8 encoded
```
Loading configuration... done.
Error: File 'D:\temp\MAVEN\Zlicin\osm.zli?.495-601.net.xml' is not accessible (Invalid argument).
Quitting (on error).
```
(cannot reproduce the dot correctly, in both cases I have the correct encoding specified in the XML header tag).

It could be caused by the move from Fox 1.6.54 to 1.6.55, I will try to investigate further.

**Comment by namdre** [comment]
I did some reading on utf8 path handling on windows and its a mess (read: hard to write portable code). I'm afraid you will have to work within the ascii set if you are on windows.

**Comment by jprk** [comment]
Yep. The funny thing is that if you specify the network file on the Windows command-line, it seems to work, even though the path `D:\temp\MAVEN\Zličín\sanity_test.sumocfg` is written out in Chinese in the sumo-gui console ... I understand that addressing this will be not easy and definitely should not be top-priority.

Please feel free to close the issue.
