### ISSUE TITLE
NameError: global name 'defs' is not defined

### ISSUE THREAD

**Issue by tianqiwil** [eclipse/sumo#4006]
Hello,

When I tried to run tls_csv2SUMO.py, it reported that

Traceback (most recent call last):
File "tls_csv2SUMO.py", line 177, in <module>
if len(defs) > 0:
NameError: global name 'defs' is not defined

Please help me to solve this problem.
Thanks!

**Comment by behrisch** [comment]
Please post your tls definition file if possible. It looks like it might miss the "key" entry.

**Comment by behrisch** [comment]
Please post your tls definition file if possible. It looks like it might miss the "key" entry.

**Comment by behrisch** [comment]
no feedback from original author, closing as hopefully fixed

**Comment by 56dikzzzz** [comment]
In personGenerator.py it shows me error of no module named lxml

**Comment by behrisch** [comment]
You can install lxml using pip or the package manager of your distro if you are on Linux.

Please stop commenting on random vaguely related tickets and rather open a new one or post to the mailing list, see https://www.eclipse.org/sumo/contact/
