### ISSUE TITLE
heap corruption due to double-delete when quitting on error

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#4009]
when a vehicle with an invalid trip is loaded, the initial reroute command raises an exception in MSBaseVehicle.cpp:212
This causes the rerouting command to be deleted in MSEventControl.cpp:77
However, the command is also deleted in the destructor of the routing device.

**Comment by namdre** [comment]
causes failing sumo gui test bugs/ticket1861

**Comment by behrisch** [comment]
worked before under windows, please recheck whether the proposed fix really helps
