### ISSUE TITLE
Downstream vehicle lane change causes upstream E2 detector to register the vehicle as passing over

### ISSUE THREAD

**Issue by jprk** [eclipse/sumo#4015]
It seems that when using E2 detectors on a long edge with multiple lanes, vehicles that change lanes downstream from a detector get briefly (one simulation step) registered by the detector on the "target lane" even if they did not pass over it. See the screenshot below (I have placed both E1 and E2 detectors on approximately the same position for debugging purposes, that is why the arrow points to E1 loop):

![e2errordesaturated](https://user-images.githubusercontent.com/5995093/39137047-f564a35a-471c-11e8-8a7a-b507f2c1b6c1.png)

This results in the following XML reading from the detector

```xml
<interval begin="66.00" end="67.00" id="e2Detector_e5.601A_1_SAa" sampledSeconds="0.00" nVehEntered="1" nVehLeft="1" nVehSeen="1" meanSpeed="-1.00" meanTimeLoss="0.00" meanOccupancy="0.00" maxOccupancy="0.00" meanMaxJamLengthInVehicles="0.00" meanMaxJamLengthInMeters="0.00" maxJamLengthInVehicles="0" maxJamLengthInMeters="0.00" jamLengthInVehiclesSum="0" jamLengthInMetersSum="0.00" meanHaltingDuration="0.00" maxHaltingDuration="0.00" haltingDurationSum="0.00" meanIntervalHaltingDuration="0.00" maxIntervalHaltingDuration="0.00" intervalHaltingDurationSum="0.00" startedHalts="0.00" meanVehicleNumber="0.00" maxVehicleNumber="0" />
```

and the following debug log produced by `MSE2Collector.cpp`:

```
[...]
66.20 notifyEnter() (detID = e2Detector_e5.601A_1_SAa on lane 'e5.601A_1') called by vehicle 'conventional1' entering lane 'e5.601A_1'
66.20 Adding VehicleInfo for vehicle 'conventional1'.
66.20 Making VehicleInfo for vehicle 'conventional1'.
distToDetectorEnd = -104.75
veh.getPositionOnLane() = 127.15
entry lane offset (lane begin from detector begin) = -20.40

66.20 detectorUpdate() for detector 'e2Detector_e5.601A_1_SAa'
myCurrentMeanSpeed = -1.00
myCurrentMeanLength = -1.00
myNumberOfEnteredVehicles = 0
myNumberOfLeftVehicles = 0
myNumberOfSeenVehicles = 0

66.20 Current lanes for vehicles still on or approaching the detector:
 Vehicle 'conventional1': 'e5.601A_1'
66.20 Discarding vehicles that have left the detector:

66.30 MSE2Collector::notifyMove() (detID = e2Detector_e5.601A_1_SAa on lane 'e5.601A_1') called by vehicle 'conventional1' at relative position 107.63, distToDetectorEnd = -105.63
Vehicle entered lane behind detector.
Vehicle has left the detector longitudinally.

66.30 detectorUpdate() for detector 'e2Detector_e5.601A_1_SAa'
myCurrentMeanSpeed = -1.00
myCurrentMeanLength = -1.00
myNumberOfEnteredVehicles = 1
myNumberOfLeftVehicles = 0
myNumberOfSeenVehicles = 1

66.30 Current lanes for vehicles still on or approaching the detector:
 Vehicle 'conventional1': 'e5.601A_1'
66.30 Discarding vehicles that have left the detector:
Erased vehicle 'conventional1'
[...]
```

I am on cc94d4910476423c41d9ba3ebb690fa5e0596d36. I am willing to debug, if you point me out where to look (I suppose the `notifyEnter()` and `notifyMove()` hooks should be called as the detector has to decide that the vehicle is completely behind it -- the code sees that at 66.30, but counts the vehicle as "entered" nevertheless).

I am also able to provide the (almost) minimum working simulation that demonstrates the issue if someone wishes to play with that.

-- jan

**Comment by jprk** [comment]
I might have found it. I have patched `MSE2Collector::notifyEnter()` to ignore vehicles that are entering the lane behind the detector and do not subscribe to theirs `notifyMove` events. At a first glance it seems to work:

```c++
[...]
    if (!vehicleApplies(veh)) {
        // That's not my type...
        return false;
    }

    // determine whether the vehicle entered the lane behind the detector end
    // e.g. due to lane change manoeuver
    const double vehBackPos = veh.getBackPositionOnLane(enteredLane);
    bool vehEnteredBehindDetectorEnd = myEndPos <= vehBackPos;
    if (vehEnteredBehindDetectorEnd) {
        // this vehicle cannot influence detector readings, do not subscribe
        // to move notifications
#ifdef DEBUG_E2_NOTIFY_ENTER_AND_LEAVE
        if DEBUG_COND{
            std::cout << "Vehicle entered the lane behind the detector, ignoring it." << std::endl;
            std::cout << "(myEndPos = " << this->myEndPos << ", veh.getBackPositionOnLane() = " << vehBackPos << ")" << std::endl;
        }
#endif
        return false;
    }
```

I am testing it, if it works, I will submit a pull request.

**Comment by namdre** [comment]
That would be great. Note, that submitting pull request is a bit more complicated due to the eclipse foundation rules (sorry). See http://sumo.dlr.de/wiki/FAQ#How_do_code_contributions_work.3F

**Comment by namdre** [comment]
If you also submit a small example scenario I can add this to our regression tests.

**Comment by jprk** [comment]
@namdre, are there any rules how example scenarios should be provided? Shall I put it to an ZIP archive and make it an attachment to this issue or would it be better to provide it as a part of the pull request, say, in `tests/sumo/bugs/ticket4015` directory? I am not familiar with Texttest package so I am afraid I can provide only a test scenario without the necessary Texttest config files.

**Comment by namdre** [comment]
You can put it into the pull request at that position. I will fix it up so it runs with texttest. Thanks.

**Comment by namdre** [comment]
Thanks for the patch. Sorry for the IP-complications.
