### ISSUE TITLE
 support stop <access>

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#4018]
this is quite noticeable when editing a webwizard-generated scenario: access definitions are lost when loading and then saving.  Would be good if this would be fixed for the tutorial.

the tasks from most to least important:

- preserve access information when loading/saving
- visualize access information
- allow editing access information (probably as a new additional element similar to the way detEntry and detExit children are added to an E3 detector)

**Comment by palvarezlopez** [comment]
Finished implementation and Netedit tests
