### ISSUE TITLE
stopped vehicles always idle

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#4019]
This is about stopping with a `<stop>` (not waiting at a traffic light).
Vehicles with with start-stop logic would stop the engine either way.

- it makes sense that a bus keeps it's engine running while stopping to pick up passengers
- a vehicle that stops at a parkingArea should always  shut off the engine

**Comment by behrisch** [comment]
has been fixed in 041b37b6cf348b6c7bc1c2acc985f6a8f559910d
