### ISSUE TITLE
Add switch to enable conflicting left turn conflicts at junctions

### ISSUE THREAD

**Issue by leoluecken** [eclipse/sumo#4024]
Per default, opposing left turns are conflict-free, even if the corresponding internal lanes geometrically interesect (and apparently even if the foe-matrix accounts for the conflict). 

The user should be enabled to have the conflict dependent on the internal lane geometries. Probably this should be activated as soon as a custom geometry is given to the left turn internal lane.

Certain geometries cannot reasonably be assumed to be conflict-free - this might also be considered in the heuristics.

**Comment by namdre** [comment]
Currently, at intersections with 1 lane per direction, left turns intersect.
As just discovered with our traffic engineers, the default junction radius of 1.5 is ridiculously low and should be raised to 8 (#4235). This would allow conflict free left turns as intended for 1 lane junctions.

When using custom geometries are indirect left-turns, the conflicts should be recognized automatically  and not require an option
