### ISSUE TITLE
Add sublane model parameter lcTurnAlignmentDistance

### ISSUE THREAD

**Issue by leoluecken** [eclipse/sumo#4025]
The value is a positive distance to an upcoming turn, below which a vehicle changes its default alignment to the side of the turn [left/right] (also center for straight?)

**Comment by namdre** [comment]
The alignment for straight connection should depend on the presence of other available connections:
If there is no right turn but there are straight and left turns from the lane, straight going vehicles should allign to the right.

**Comment by leoluecken** [comment]
Not necessarily - this may cause cause undesireable deviations in the trajectory.. 
Current implementation does not alter aligment specified in vType, when vehicle goes straight.
Implemented in 1710da37aa0352af9
