### ISSUE TITLE
collision between pedestrian and vehicle at intersection

### ISSUE THREAD

**Issue by MelanieWeber** [eclipse/sumo#4026]
If a vehicle is already on the intersection/crossing pedestrians walk on the road to the vehicle and wait in the middle of the street.  (~time=1153.00)
![unbenanntes bild](https://user-images.githubusercontent.com/38243649/39297430-cdb8e05e-4943-11e8-9aeb-8b7f3f6348ef.png)
The next vehicle driving on the opposite lane push the pedestrians into the waiting vehicle. When the waiting vehicle drives away, the pedestrians walk on.) (~time=1446.00)
![unbenanntes bild2](https://user-images.githubusercontent.com/38243649/39297575-2048b948-4944-11e8-8052-9f5a841f01b8.png)

**Comment by m-kro** [comment]
![image](https://user-images.githubusercontent.com/33294728/50726641-2b975e00-1110-11e9-97ef-54f9148f05ff.png)
A similar issue here: While a vehicle is stopped on the crossing, a pedestrian just walks across it.

**Comment by aloreggia** [comment]
Hi, 
I'm generating scenarios where vehicles and pedestrian can potentially collide.
When I use the GUI, I can see the warnings, which notify about collisions among vehicles and pedestrians (see attached figure), but I can't get the number of colliding vehicles or the list of their IDs using TRACI. Is there any way to detect this kind of collisions from TRACI?

Thanks

<img width="620" alt="Schermata 2020-10-26 alle 11 14 23" src="https://user-images.githubusercontent.com/10076528/97450347-eec6d780-1932-11eb-859c-b6c1716be824.png">

**Comment by namdre** [comment]
@aloreggia I've moved your question to #7728 because it is orthogonal to this issue.

**Comment by aloreggia** [comment]
Dear Jakob,
thanks for your reply.
May I ask you if you have any forecast about the release of the solution?

Thanks for your attention, best regards
Andrea Loreggia

Il giorno ven 30 ott 2020 alle ore 11:02 Jakob Erdmann <
notifications@github.com> ha scritto:

**Comment by namdre** [comment]
no more collisions observed, probably a duplicate of some other fix.
