### ISSUE TITLE
Crash in SUMO GUI after enabling OSG View.

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#4028]
Enabling OSG in simulation.zip produces a crash in OSGViewer (error.png)

![error](https://user-images.githubusercontent.com/8238561/39365248-df18035a-4a30-11e8-9546-b7711a9e20e4.png)

[simulation.zip](https://github.com/eclipse/sumo/files/1955290/simulation.zip)

**Comment by namdre** [comment]
I cannot reproduce this on windows (release, debug), and linux (release,debug). 
Please check different plattforms and builds so we can narrow down the error case.

**Comment by namdre** [comment]
@palvarezlopez  please check if the crash still occurs.

**Comment by palvarezlopez** [comment]
Crash doesn't occurs.
