### ISSUE TITLE
crash when rendering persons in OSG view

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#4039]

**Comment by palvarezlopez** [comment]
Probably related with #4028

**Comment by namdre** [comment]
After the last commit I don't see crashes anymore. Does #4028 still crash now?

**Comment by palvarezlopez** [comment]
@namdre Yes, but only in Windows. In Linux works as expected.

**Comment by namdre** [comment]
I'm closings this as any remaining crashes are tracked via #4028.
