### ISSUE TITLE
additionals should not write attributes with default values

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#4047]
1) it makes saved objects harder for a human to read
2) empty string default values violate the xml schema and results in warnings:

Warning: Format of optional string attribute 'imgFile' of vType with ID 'caliType' is invalid; Default value '' will be used.
Warning: Format of optional string attribute 'line' of flow is invalid; Default value '' will be used.
Warning: Format of optional string attribute 'arrivalPosLat' of flow is invalid; Default value '' will be used.

this should be solved generically via #4049

**Update:**

Optional and non-set double values (As RouteProbe::frequency) are represented as -1

**Comment by palvarezlopez** [comment]
Fixed in #4056
