### ISSUE TITLE
appendable lists in options (trac #405)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#405]
A nice feature would be to have appendable lists in the command line options, e.g. to give an extra route file on the command line which is loaded in addition to the route files mentioned in the configuration file.

Migrated from http://sumo.dlr.de/ticket/405
```json
{
    "status": "new", 
    "changetime": "2011-01-03T10:03:29Z", 
    "description": "A nice feature would be to have appendable lists in the command line options, e.g. to give an extra route file on the command line which is loaded in addition to the route files mentioned in the configuration file.", 
    "reporter": "behrisch", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1294049009000000", 
    "component": "simulation data input", 
    "summary": "appendable lists in options", 
    "priority": "minor", 
    "keywords": "", 
    "time": "2011-01-03T10:03:29Z", 
    "milestone": "1.0.0", 
    "owner": "", 
    "type": "enhancement"
}
```

**Comment by namdre** [comment]
sometimes, replacement of the original list is also desirable. How to support both use-cases?

**Comment by behrisch** [comment]
@namdre The initial idea was to prefix the options with a "+" instead of a "-" or "--" to trigger appending. If we go so far to allow loading multiple config files we could introduce an "append" in addition to the "value" attribute.

**Comment by behrisch** [comment]
This should be possible with our python option parsing as well and needs to be checked whether it also works with texttest and extractTest

**Comment by behrisch** [comment]
a single + should be sufficient everywhere and docs are still missing

**Comment by RobertHilbrich** [comment]
Needs to be reopened. Consider the following sumo config:
```
<?xml version="1.0" encoding="UTF-8"?>
<!-- generated on 2022-09-30 07:59:30 by Eclipse SUMO sumo Version 1.14.1-->
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/sumoConfiguration.xsd">
    <input>
        <net-file value="network.net.xml.gz"/>
    </input>
</configuration>
```

If you want to add trips, you might do it the following way:
```
sumo -c test.sumocfg +r trips.rou.xml -C test.sumocfg
```

This leads to a sumo config with duplicate `trips.rou.xml` entries:
```
<?xml version="1.0" encoding="UTF-8"?>
<!-- generated on 2022-09-30 08:06:17 by Eclipse SUMO sumo Version 1.14.1-->
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/sumoConfiguration.xsd">
    <input>
        <net-file value="network.net.xml.gz"/>
        <route-files value="trips.rou.xml,trips.rou.xml"/>
    </input>
</configuration>
```
