### ISSUE TITLE
refactor GNECalibratoVehicleType

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#4050]
instead of adding all attributes directly to the class, a single member of the existing class SUMOVTypeParameter should be used to hold them.

**Comment by namdre** [comment]
this is really not urgent.

**Comment by palvarezlopez** [comment]
@namdre GNECalibratorVehicleType, GNECalibratorFlow and GNECalibratorRoute have to be refactoriced when GNERoutes is implemented. The current implementation is only temporal.

**Comment by namdre** [comment]
likewise, the constuctor should only take a single argument of type SUMOVTypeParameter instead of the long list it takes now.

**Comment by palvarezlopez** [comment]
This ticket was solved during refactoring #4049 See c5aea8cafa12eb2e1afa0ddf53a00209e7b3301c
