### ISSUE TITLE
How to use "traci/change traffic light state" to control the signal manual

### ISSUE THREAD

**Issue by tianqiwil** [eclipse/sumo#4059]
In sumo official document, it said that "Sets the phase definition to the given. Assumes the given string is a tuple of light definitions from rRgGyYoO, for red, green, yellow, off, where lower case letters mean that the stream has to decelerate. After this call the program-ID of the traffic light will be set to "online" and the state will be maintained until the next call of setRedYellowGreenState() or until setting another program with setProgram(). " But, when I inherite the TrafficLightDomain subclass and use the setRedYellowGreenState() method, it cannot work with reporting " 'NoneType' object has no attribute "_sendStringCmd". Could you please help me solve this problem, thanks!

**Comment by namdre** [comment]
you are not supposed to inherit from the traci domains. They undergo a non-standard construction process that is hard to replicate.

Just import the library and use it directly.

**Comment by tianqiwil** [comment]
Not yet, I have imported  TrafficLightDomain from traci._trafficlight baseclass

**Comment by namdre** [comment]
do it like this:
`import traci`
and the use
`traci.trafficlight`
or at least
`trafficlight = traci.trafficlight`

**Comment by tianqiwil** [comment]
Sorry, the question is I used the code below, it reported the error. I dont know why.

 traffic_state_setting = TrafficLightDomain()
 traffic_state_setting.setRedYellowGreenState('1', 'G')

  File "D:/Sumo/doc/tutorial/test2/test2.py", line 97, in run
    traffic_state_setting.setRedYellowGreenState('1', 'G')
  File "D:\Sumo\tools\traci\_trafficlight.py", line 185, in setRedYellowGreenState
    self._connection._sendStringCmd(
AttributeError: 'NoneType' object has no attribute '_sendStringCmd'

**Comment by namdre** [comment]
because the constructor TrafficLightDomain() is insufficient to construct the object. The _connection attribute which is 'None' in your script is set via the method traci.switch which is all done automatically for the object accessible via traci.trafficlight.

**Comment by tianqiwil** [comment]
But, I  follow your method with using
import traci
trafficlight = traci._trafficlight
traffic.setRedYellowGreenState('1','G')

It also report the  error 'module' object has no attribute 'getRedYellowGreenState'. It is obviouly the _trafficlight class doesnt have the setRedYellowGreenState() method

**Comment by tianqiwil** [comment]
Actually, it also cant work for that way

**Comment by namdre** [comment]
then I need to see more lines of your code as well as the error message.

**Comment by tianqiwil** [comment]
I used for the codes below to solve the error mentioned  above.  
```
  traffic_state_setting = TrafficLightDomain()
    traffic_state_setting._setConnection(traci._connections['default'])
```
Because according to my comprehension about the interface, I think the first step is to conduct connection through traci.start, but i have to call setphase method to control the traffic light. Then, I creat object with TrafficLightDomain class, however, obviously, Domain init method connection arguments is NONE, so then I used traffic_state_setting._setConnection(traci._connections['default'])
to set coonetion Ture. It  is normal to run the sumo-gui, but when amplify the road, it crashed

**Comment by namdre** [comment]
I'm not exactly sure what you are trying to accomplish by manually initializing the TrafficLightDomain().
There are plenty of examples online to show how traci can be used without doing that.
https://github.com/eclipse/sumo/blob/master/tests/complex/traci/pythonApi/trafficlight/runner.py
https://github.com/eclipse/sumo/blob/master/tests/complex/tutorial/traci_tls/runner.py

Please try the regular method of using traci domains and check if this solves the crash.

**Comment by tianqiwil** [comment]
I dont find there are tafficlight class

**Comment by namdre** [comment]
Ah. Maybe your are using a programming environment that tells you this class does not exist because it cannot find the corresponding python file. Ignore this and just run the python script anyway. This is a known issue with the dynamic nature of the traci library.

**Comment by tianqiwil** [comment]
Yes, I know that example, but it report the error with  "AttributeError: 'module' object has no attribute 'trafficlight",  just because of this reason, i tried to use trafficdomain class.
"

**Comment by namdre** [comment]
then you may be using an old version of the traci library where the object was called 
traci.trafficlights

**Comment by tianqiwil** [comment]
So, can you tell me how to update the traci library, i download the latest sumo version from the official website

**Comment by namdre** [comment]
if your traci script uses the default header that finds the library using environment variable SUMO_HOME
(http://sumo.dlr.de/wiki/TraCI/Interfacing_TraCI_from_Python#importing_traci_in_a_script) than it is enough to set SUMO_HOME to the directory in which the latest sumo version was downloaded.

**Comment by tianqiwil** [comment]
Ah, is that the way to update traci library. my code also includes the  environment variable SUMO HOME. Can you tell the how wo update library directly, thanks!

**Comment by namdre** [comment]
what operating system are you using?

**Comment by namdre** [comment]
It should be working with this version already. It is new enough.
What happens when you try to run this traci tutorial: http://sumo.dlr.de/wiki/Tutorials/TraCI4Traffic_Lights ?

**Comment by tianqiwil** [comment]
<img width="955" alt="sumo-gui error" src="https://user-images.githubusercontent.com/30425894/40229385-a6c95b38-5ac6-11e8-8024-6f652344facf.png">

<img width="282" alt="python-error" src="https://user-images.githubusercontent.com/30425894/40229446-d520b8c8-5ac6-11e8-8140-25c0765ad32e.png">

**Comment by tianqiwil** [comment]
import traci: ['Connection', 'FatalTraCIError', 'StepListener', 'TraCIException', '_STEPS2TIME', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__', '_connections', '_defaultDomains', '_edge', '_embedded', '_gui', '_inductionloop', '_junction', '_lane', '_lanearea', '_multientryexit', '_person', '_poi', '_polygon', '_route', '_simulation', '_stepListeners', '_trafficlight', '_vehicle', '_vehicletype', 'abc', 'absolute_import', 'addStepListener', 'areal', 'close', 'connect', 'connection', 'constants', 'domain', 'edge', 'exceptions', 'getConnection', 'getFreeSocketPort', 'getVersion', 'gui', 'inductionloop', 'init', 'isEmbedded', 'junction', 'lane', 'lanearea', 'load', 'multientryexit', 'pdb', 'person', 'poi', 'polygon', 'print_function', 'removeStepListener', 'route', 'setOrder', 'simulation', 'simulationStep', 'socket', 'start', 'storage', 'subprocess', 'sumolib', 'switch', 'time', 'trafficlights', 'vehicle', 'vehicletype', 'warnings']
options.nogui is  False
Loading configuration... done.
Could not connect to TraCI server at localhost:61387 [Errno 10061]

**Comment by namdre** [comment]
This indicates that the variable %SUMO_HOME% points to a version of the traci library that is older than version 0.32.0 (the module is called `traci.trafficlights`, rather than `traci.trafficlight`)

please check the value of %SUMO_HOME% (i.e. on the cmdline type `echo %SUMO_HOME%` against the directory where version 0.32.0 is present.

**Comment by namdre** [comment]
If you are still struggling with this, please report. Otherwise I will close this ticket.

**Comment by tianqiwil** [comment]
Hi，Jakob,

Thanks for your help. Now, it can support simulation without any bug reports.
I am attending for industrial conference in China so that I dont reply you timely. I feel so sorry. 

Thanks again,
best Regards!

--Henry

 
From: Jakob Erdmann
Date: 2018-05-23 21:51
To: eclipse/sumo
CC: 何书贤_Henry; Author
Subject: Re: [eclipse/sumo] How to use "traci/change traffic light state" to control the signal manual (#4059)
If you are still struggling with this, please report. Otherwise I will close this ticket.
