### ISSUE TITLE
Creating different number of lanes with NETGENERATE

### ISSUE THREAD

**Issue by tomerkay** [eclipse/sumo#4072]
Hello,
As I currently understand, you can only create a net with a fix number of lanes using --default.lanenumber INT (when the default is 1). Is there a way to produce a net with different number of lanes?
And if not, is there another way of regarding several lanes as "main roads" and others as "side roads"?
Best,
Tomer

**Comment by namdre** [comment]
fixed in [6ca354f53ed1eaa0432874ea0acb77527f286b36]. (added two new options for random networks). Thanks for the suggestion.

**Comment by tomerkay** [comment]
Thank you !!!

**Comment by tomerkay** [comment]
Unfortunately I am having problems with compiling the netgenerate cpp files ):
Is there any chance you can upload a zip file containing the new compiled netgenerate for **Windows**?
I can not tell you how much it would help me.
Best,
Tomer

**Comment by namdre** [comment]
download it here: http://sumo.dlr.de/wiki/Downloads#SUMO_-_Latest_Development_Version
Also check out the other new options (awesome random grid networks): http://sumo.dlr.de/wiki/ChangeLog#Enhancements

**Comment by tomerkay** [comment]
Thank you so much once again !!!
