### ISSUE TITLE
connect junctions in NetEdit

### ISSUE THREAD

**Issue by JaneCheung** [eclipse/sumo#4077]
Hi, guys, there is one question that I want to ask for help.
When someone use the NetEdit to draw the network, the TWO junctions will be drawn in NetEdit together at once, how to connect the dependent junctions shown in picture?
Look forward for your help!

![1](https://user-images.githubusercontent.com/39317241/40087702-6d7f8d7a-5869-11e8-9529-8002a52afbae.png)

 Cheung

**Comment by namdre** [comment]
- if you want to preserve the shapes of both edges, select both junctions (left-click in select mode) and then join them using the F7 key ('Processing' menu option 'Join selected junctions')
- alternatively you can move one junction on top of the other one in 'move mode' and confirm merging them in the popup-dialog

Please address future usage question to the sumo user mailing list: http://sumo.dlr.de/wiki/Contact

**Comment by JaneCheung** [comment]
When I use the SECOND METHOD to connect the junction(in 'move-mode'),  
click the junction with left button, two scenarios happened:
1) the junction could not be chosen, some 'red bubble' appeared on the lanes ;
or 
2) the whole view was moving with the track of mouse,  nothing could be chosen;
![1](https://user-images.githubusercontent.com/39317241/40125741-42eacce0-58f1-11e8-8e86-80cc2e494fbb.png)
![2](https://user-images.githubusercontent.com/39317241/40125742-42f66014-58f1-11e8-8af6-210e2ed61ed5.png)

**Comment by namdre** [comment]
I cannot reproduce this problem on my end but I have heard of similar cases. What operating system and which version of netedit are you using?

**Comment by JaneCheung** [comment]
The operating system is Win10 and the version of SUMO is 0.32.0.
Thanks for your reply! sincerely!

**Comment by namdre** [comment]
please check whether the problem persists when using the latest development version: http://sumo.dlr.de/wiki/Downloads#SUMO_-_Latest_Development_Version

**Comment by namdre** [comment]
Another user could solve a quite similar problem by updating the graphics driver. See #4080. I recommend you try this as well.

**Comment by Fatimaghaffar** [comment]
I have an issue in joining of junctions from the open street map, whenever 4 roads meet at a junction, it ends up by creating four separate junctions instead of one junction. I have tried to merge them in netedit but create a terrible type of junction. so I can't mount traffic light on that so anyone who know this issue please tell me

**Comment by namdre** [comment]
@Fatimaghaffar 
1) Please open up a new ticket for your question
2) Please include some example screenshots / networks to illustrate your problem
