### ISSUE TITLE
The vehicleSum of an entryExitDetector detector does not match the demand.

### ISSUE THREAD

**Issue by MartijnHarmenzon** [eclipse/sumo#4079]
I am trying to use the entryExitDetector detectors as ‘route’-evaluations (such as in Vissim).
Using the entryExitDetector detectors it is easy to define a start and an end point in the network and to retrieve evaluation data from these ‘routes’ such as:
[UC5-1.zip](https://github.com/eclipse/sumo/files/2008549/UC5-1.zip)

- Travel time and delay for each movement;
- Number of stops per vehicle for each movement;
- Number of vehicles for each movement.
 
When comparing the results of an entryExitDetector detector with the results of an inductionLoop detector the total number of vehicles (vehcileSum) do not match the demand. The number of vehicles measured with an inductionLoop detector match the defined traffic demand. The number of vehicles measured with an entryExitDetector detector are much lower.
 
Can you please have a look at my network? Thanks in advance and if you have any question, please ask.

**Comment by namdre** [comment]
This is quite strange. To begin with, when I run the same configuration with the latest dev version I get vehicleSum=925 in the first interval whereas your output file had vehicleSum=99. 
Still to low...
