### ISSUE TITLE
Create string lists at parse time (trac #408)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#408]
Analogous to the int vector option there should be a string vector option which parses the list immediately.

Migrated from http://sumo.dlr.de/ticket/408
```json
{
    "status": "new", 
    "changetime": "2011-01-03T10:09:52Z", 
    "description": "Analogous to the int vector option there should be a string vector option which parses the list immediately.", 
    "reporter": "behrisch", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1294049392000000", 
    "component": "other (also unclassified)", 
    "summary": "Create string lists at parse time", 
    "priority": "minor", 
    "keywords": "", 
    "time": "2011-01-03T10:09:52Z", 
    "milestone": "1.0.0", 
    "owner": "", 
    "type": "enhancement"
}
```

**Comment by schwamborn** [comment]
Going a little off-topic here:
@behrisch `Option_FloatVector` seems to be completely unused, so far, right? Would it still be sensible to add it to the [list in the docs](https://github.com/eclipse/sumo/blob/master/docs/web/docs/Developer/Implementation_Notes/Options_Sub_System.md) or is testing needed first?

**Comment by schwamborn** [comment]
I added a `Option_StringVector` class (type name `STR[]`) analogous to `Option_IntVector`. Now it looks like I'll have to find all calls to `getStringVector()` and touch the corresponding options' `doRegister()` call. Any idea about how I can avoid going through all of the 100+ calls/options by hand? :wink:

**Comment by schwamborn** [comment]
Introducing Option_StringVector leads to the question about what to do with Option_FileName, which currently derives from Option_String. There seem to be both single an list filename options. I'd rather not add Option_FileNameVector. Opinions?

**Comment by behrisch** [comment]
> Going a little off-topic here:
> @behrisch `Option_FloatVector` seems to be completely unused, so far, right? Would it still be sensible to add it to the [list in the docs](https://github.com/eclipse/sumo/blob/master/docs/web/docs/Developer/Implementation_Notes/Options_Sub_System.md) or is testing needed first?

I would remove it since it is not used.

**Comment by behrisch** [comment]
> Introducing `Option_StringVector` leads to the question about what to do with `Option_FileName`, which currently derives from `Option_String`. There seem to be both single an list filename options. I'd rather not add `Option_FileNameVector`. Opinions @behrisch @namdre?

Derive from StringVector.

**Comment by schwamborn** [comment]
Left the `Option_FileName::getString()` method as a convenience, for now. Not exactly in line with the code style for the Options sub-system, though. New code should call `Option_FileName::getStringVector()` instead.

**Comment by namdre** [comment]
There is now an uninformative error message "Error: Error occurred: basic_string::resize while parsing..." when passing a directory as argument to Option_File. 
The previous error was at least slightly better: "Error: unable to read data from file".

**Comment by schwamborn** [comment]
The cryptic error message does not seem to be related to this issue as the path name is parsed by Option_FileName as expected. Instead, it seems to be related to the way exceptions are handled in src/utils/xml/XMLSubSys.cpp:XMLSubSys::runParser(). Any idea which sumo version printed the old error message?

**Comment by namdre** [comment]
Indeed, the issue is unrelated. Sorry for that. It was last working in 1.2.0 and I've opened up a new ticket for this. #6191
