### ISSUE TITLE
sumo-gui crash when amplify the display proportion

### ISSUE THREAD

**Issue by tianqiwil** [eclipse/sumo#4084]
when amplify the display proportion, it reported some error and waited to restart

**Comment by namdre** [comment]
- Can you reproduce this reliably or is it random?
  - what sequence of operations can be used to reproduce it?
- What was the reported error?
- What operating system did you use
- Which version of sumo was that?

**Comment by tianqiwil** [comment]
1. it is random

2.    it reported error of “ raise FatalTraCIError("connection closed by SUMO")
traci.exceptions.FatalTraCIError: connection closed by SUMO” when I amplify the sumo-gui. But if it clicked running directly, nothing error happened.

3. operate windows 10 system

4. sumo version: 0.32.0

**Comment by namdre** [comment]
related to #4059

**Comment by tianqiwil** [comment]
not exactly, crash noly occured after I amplify the sumo-gui road network. 
but, under the precondition of code——
`TrafficLightDomain()._setConnection(traci._connections['default'])`

Also, can you help me to update the traci library, the local version of mine is the same as that of official. And the official API inferred that the if you want to accomplish traffic control, you have to call
` setphase() `
method. 
So, i also want to know which method is available to accomplish adaptive traffic controll

Thanks very much!

**Comment by namdre** [comment]
Please post usage questions at the mailing list in the future (as this issue tracker is for bugs and feature requests). 
- if you want to use existing algorithms for adaptive traffic control, see http://sumo.dlr.de/wiki/Simulation/Traffic_Lights#Actuated_Traffic_Lights
- if you want to develop your own algorithms, then use traci to retrieve traffic information from the simulation and use setphase() or setRedYellowGreenState()
