### ISSUE TITLE
sumo-gui and netedit mousewheel zoom not centered around mouse position anymore

### ISSUE THREAD

**Issue by gprichter** [eclipse/sumo#4086]
using the last developer version from before sumo conference 

    Eclipse SUMO Version c74462f14a
    Build features: x86_64-pc-linux-gnu Debug PROJ GDAL GUI Python OSG ffmpeg

running on ubuntu 18.04

i checked on a current working-scenario and 
when ___zooming with the mouse scrolling function___
the behavior was unexpected

the __steady point__ between zooming steps is __not the position of the mouse anymore__,
__but instead the center point__ of the view(port) / drawing canvas / ...

I am not sure if this was an issue already once before (long way back),
but something got mixed up here

**Comment by namdre** [comment]
there is a little button in sumo-gui that toggles between these two behaviors and which is rembered between program starts (usually). The button is the the third in the bottom toolbar with a magnifying glass and a mouse pointer on it.

**Comment by gprichter** [comment]
as long as it is not remembered by me but just by the program 
I will probably stumble over it again ;)

but thanks!
