### ISSUE TITLE
context subscriptions retrieve the object of which the context is queried if the domains match

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#4088]
i.e. when subscribing for vehicles around the ego vehicle, the ego vehicle itself is returned.

**Comment by behrisch** [comment]
I am not sure whether I would consider this a bug.

**Comment by namdre** [comment]
I think I can see what you mean from a purely technical standpoint.
As evidenced by previous questions on the mailing list, the behavior is unexpected and I would also argue that it is wasteful because in many usage contexts the ego vehicle is filtered out and just creates data overhead on the socket (e.g. sending a message to neighboring vehicles, checking neighbors for safe distance).

**Comment by dbuse** [comment]
I just tripped over this change and only after hours found out that the behavior changed. I agree with @behrisch here that the ego vehicle would be part of its own context. Maybe it would be better to provide a flag for this when subscribing?

**Comment by namdre** [comment]
Thanks for comment @dbuse . I thought having the vehicle as part of it's context was only a theoretical use case. Adding a flag would leave open the question of an appropriate default value.
As mentioned before, the old behavior did cause confusion for other users. Can you explain your use case some more (which might help me guess at how common it is)?

**Comment by dbuse** [comment]
Sure, and thanks for the swift answer @namdre .
Our use case is to synchronize the environment of a TraCI-controlled ego vehicle to other simulators. We did this by subscribing to the context of said ego vehicle and then forwarding said data to the other simulators.
While it is still possible to achieve the same using an additional "simple" subscription to the ego vehicle and then combining the data afterwards, the change appeared strange to me. I just would expect to have the vehicle itself in the set of data returned on the query: what vehicles are in within the radius of x meters around a given vehicle.

**Comment by namdre** [comment]
@behrisch Needs further discussion apparently.
