### ISSUE TITLE
How to realize real-time offset config instead of static in ttl program

### ISSUE THREAD

**Issue by tianqiwil** [eclipse/sumo#4089]
considering the scenario —— multiple vehicles in a platoon need to pass the continuous intersections without stopping. So, we need to creat adaptive traffic control environment. 

To achieve this goal, we need to modify the offset of the intersections tn ensure the traffic light is green whtn the platoon arrive the stop line.

But，I dont find the available API in
 `TraCI/Change Traffic Lights State`
it looks like only suitable for single intersection traffic light state modification

So, how to modify the offset with using python?

**Comment by namdre** [comment]
as mentioned before: this is a usage question that will only be answered on the mailing list. Please stop flooding the issue tracker with these.
