### ISSUE TITLE
The website is down

### ISSUE THREAD

**Issue by kyleger** [eclipse/sumo#4111]

**Comment by namdre** [comment]
we noticed.

**Comment by KostyaAtarik** [comment]
Are you going to fix it?

**Comment by namdre** [comment]
Yes. To be more precise, we are waiting for our network provider to get this fixed but despite our angry reports they do not know when that will be. As multiple servers from our network are affected,  I have some hopes that it will be fixed within the next 10 days.  The wiki itself is still there. It's just not reachable from outside our institutional network.

Please refer to our backup wiki at http://sumo.sourceforge.net/ which is updatedy daily.

**Comment by JaneCheung** [comment]
Thanks for youre reply, wish it will be ok soon! Thank you very much!

**Comment by behrisch** [comment]
It is back again.
