### ISSUE TITLE
crash when using carFollowModel="TCI" hasDriverState="0"

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#4133]
* if driverState is set to 0 explicitly, sumo should abort with an error
* if driverState is not specified, it should be enabled automatically when using this carFollowModel (or at least abort with an error as well)

**Comment by leoluecken** [comment]
TCI Model will be removed completely. All intended functionality will be included in the driver state, see also #4115

**Comment by namdre** [comment]
then this is a non-issue
