### ISSUE TITLE
add wizards for python tools

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#4138]
- [x] add serialization function for optParse / argParse to sumolib (style of OptionsCont configuration templates)
- [x] add option --save-template to the wrapper around optParse / argParse that 
supports serialization
   - bonus: this would make it feasible to support configuration files for python tools
- [x] let all (relevant) tools use that wrapper for argument parsing
- [x] add deserialization function to OptionsCont
- [x] in netedit, add a dialog for picking a python tool
  - call the tool with option --save-template
  - instantiate a new OptionsCont instance
  - use that instance to populate the wizard
  - call the tool with the given options (and optionally store the last used options in the registry)

See:
https://github.com/eclipse/sumo/issues/2736

**Comment by angelobanse** [comment]
The osmWebWizard option listed in the Tools menu should make clear that it doesn't actually open the browser. The average user could get confused, as we always mention the browser being involved -> (https://sumo.dlr.de/docs/Tools/Import/OSM.html#osmwebwizardpy - https://sumo.dlr.de/docs/Tutorials/OSMWebWizard.html)

Should there also be a shortcut to the web browser version of the wizard, just as planned for sumo-gui (#4896), maybe in another menu?

**Comment by angelobanse** [comment]
So this option should be (as an exception) just a call to `osmWebWizard.py`, and not be a dialog that allows input (as for the other tools).

**Comment by namdre** [comment]
since osmWebWizard exposes some command line options, it should be a dialog as any other tool. Upen pressing 'run' I would expect the webbrowser to launch.

**Comment by palvarezlopez** [comment]
.
