### ISSUE TITLE
game racing outdated and very buggy

### ISSUE THREAD

**Issue by ziyadedher** [eclipse/sumo#4149]
The `racing.py` file under `tools/game` is very outdated (does not work with Python 3) and buggy. Without tweaks, the racing module will not run.

Full rewriting is probably needed, but that is not much of a task as the module is currently only about 250 lines long.

**Comment by namdre** [comment]
If you care to refactor the code, I'd be happy to accept pull requests (see http://sumo.sourceforge.net/userdoc/FAQ.html#How_do_code_contributions_work.3F)
