### ISSUE TITLE
SUMO site down?

### ISSUE THREAD

**Issue by yairf11** [eclipse/sumo#4181]
Hi,

It seems like the sumo website (http://sumo.dlr.de/) is down. Is there any expectation as of when it will be back up?

Thanks

**Comment by behrisch** [comment]
Yes it is for about two weeks now and we really cannot do anything about it, that we did not try yet, sorry. In the meantime please see http://sumo.sourceforge.net/ which is updated once a time with the nightly docs and follow #4111 where we will post updates.

**Comment by Chakroo** [comment]
hi behrisch..sumo site is down again
i need to understandd traci and how to write a code which can move the vehicles from an external python code.
