### ISSUE TITLE
netedit does not consider length/geometry factor when rendering additional infrastructure

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#4182]
in sumo, all lanes of an edge are defined to have the same length even if the edge is curved.
This leads to a mismatch between the geometrical length and the defined length. The quotient of shapeLength/laneLength is called 'lengthGeometryFactor' and is used in SUMO-GUI to translate between the geometrical and logical coordinate system.

i.e. in GUIInductLoop.cpp
` myFGPosition = detector.getLane()->geometryPositionAtOffset(pos);`

Netdit must do this as well for all additionals that are placed on lanes

**Comment by namdre** [comment]
lengthGeometryFactor != 1 can also occur for user-defined edge lengths (which may differ in arbitrary ways from the geometrical edge length implied by the shape vector)

**Comment by namdre** [comment]
![image](https://user-images.githubusercontent.com/6240630/41126389-a0823baa-6aa7-11e8-8957-6352caed742d.png)

Additionals off the same type have the same position and should line up

**Comment by namdre** [comment]
the rendering difference between loading and after the first call to 'compute' (which is triggered by using connection mode) is a feature rather than a bug. Computation can take several seconds for large networks and it is deemed useful to have a network visible for inspecting after loading a file as fast as possible. However, this means parts of the geometry are still rough on first loading.

**Comment by palvarezlopez** [comment]
@namdre should I use these method in GNEAdditionals?

**Comment by namdre** [comment]
you should add the function interpolateEdgePosToGeometry to GNEEdge which follows the pattern
of MSLane::interpolateLanePosToGeometryPos (interpolating positions to reflect any difference between NBEdge::getFinalLength() and NBEdge->getGeometry()->getLength() )

This function should then be used when rendering additionals just as it is done in [0a963d0] for E2 detectors. (You can take a look at the corresponding sumogui classes for additional examples)
