### ISSUE TITLE
Could not see Charging Station in SUMO GUI 

### ISSUE THREAD

**Issue by JaneCheung** [eclipse/sumo#4183]
Hi guys,

There are something when I could not figure out with SUMO.
These are some files in "SUMO_HOME\tests\sumo\extended\electric\chargingStations” .Charging Station defined in the additional files "input_additional.add.xml" have be configured in the "sumo.sumocfg". The charging stations could not be found in SUMO GUI if someone open the "sumo.sumocfg".
What a the right way open it ?

Apprecite for your reading  my quesiton!

Best regards!

**Comment by namdre** [comment]
Possibly there is still some misconfiguration. Take a look at the examples in https://github.com/eclipse/sumo/tree/master/tests/sumo/extended/electric
If you cannot see the charging stations in these example, then update your graphics drivers.

**Comment by JaneCheung** [comment]
It  could not find the Charging Station in the SUMO GUI  after I downloaded after I downloaded the whole package  and released it on the desk by my computer. And I have updated the  graphics drivers on my own computer.

I clicked the file named "sumo.sumocfg" directly and the SUMO GUI opened. I was trying to use the method showed  in the picture below  to find the additional, however, only Bus Station could be shown in the subwindow.

Is it the right way to run the file by clicking that file directly?  



![1](https://user-images.githubusercontent.com/39317241/41164145-1362e6e4-6b00-11e8-9aab-11ca1bfe0740.png)
![2](https://user-images.githubusercontent.com/39317241/41164146-1379659a-6b00-11e8-9461-8fb6c2ed3b31.png)

**Comment by JaneCheung** [comment]
Are there other examples that simulate with electircal vehicles ?

**Comment by namdre** [comment]
Opening the simulation by clicking on sumo/tests/sumo/extended/electric/chargingStations/sumo.sumoconfig should indeed load some chargingstations:

![image](https://user-images.githubusercontent.com/6240630/41168019-fff43f64-6b44-11e8-82e4-4ad6bac5f634.png)

The fact that they do not even show up in the selection dialog makes it clear that this is not a graphics bug. What happens when you use the files in the attached zip?
[chargingstations_test.zip](https://github.com/eclipse/sumo/files/2085081/chargingstations_test.zip)

**Comment by JaneCheung** [comment]
I download the attached zip, and click the ".sumocfg " directly,  I still could not found the CSs objects.
![1](https://user-images.githubusercontent.com/39317241/41168443-977556b4-6b0b-11e8-890a-72f80e82ee53.png)
![2](https://user-images.githubusercontent.com/39317241/41168444-97854132-6b0b-11e8-9158-a937f3da73cf.png)
my system is Win 10

**Comment by JaneCheung** [comment]
Here it goes
![1](https://user-images.githubusercontent.com/39317241/41168563-fc8e41aa-6b0b-11e8-836a-0fff99957cc8.png)

**Comment by namdre** [comment]
When you open up the 'About' dialog (Menu 'Help' in SUMO-GUI) what does it say?

**Comment by JaneCheung** [comment]
Sorry for that, I haven't  seen the reply before.

 Here it goes
![tim 20180608133119](https://user-images.githubusercontent.com/39317241/41174652-61fe2f5a-6b20-11e8-9ef6-ca223e415cd5.png)

**Comment by JaneCheung** [comment]
I have also done some tests.
1) One small test network (with one lane and one charging station) in the attached zip has been made.
If there was nothing wrong with that file, the Charing Station defined the additional file could also not be shown in SUMO GUI. 
2) What's more, I have tried to use another computer installed  the Win 10 operating system in order to check the problem is related to my computer or not. It came to the same problem. 

[CharingStation0608_by JC.zip](https://github.com/eclipse/sumo/files/2085699/CharingStation0608_by.JC.zip)

**Comment by namdre** [comment]
When I load your files the chargingStation loads as expected. 

Please check what happens when you replace the first and last lines of the additional file with these (this enables xml validation):

<additional xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/additional_file.xsd">
</additional>

**Comment by JaneCheung** [comment]
Execuse me, I have found nothing in the reply to replace the first and last lines of the additional file, could you please tell me more detail about that?

**Comment by namdre** [comment]
sorry. That was lost in the formatting. Should be visible now

**Comment by JaneCheung** [comment]
There  are some message  showed  in SUMO GUI
----------------------------------------------------------------------------------------
Loading configuration... done.
Loading net-file from 'G:\CharingStation0611_by JC\CharingStation0611.net.xml'... done (1ms).
Loading additional-files from 'G:\CharingStation0611_by JC\CharingStation0611.add.xml'... 

Error: prefix 'xsi' can not be resolved to namespace URI
 In file 'G:\CharingStation0611_by JC\CharingStation0611.add.xml'
 At line/column 2/88.

Loading of additional-files failed.
Quitting (on error).
[CharingStation0611_by JC.zip](https://github.com/eclipse/sumo/files/2090848/CharingStation0611_by.JC.zip)

**Comment by namdre** [comment]
Sorry, my mistake again )-:
the header needs to be

` <additional xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/additional_file.xsd"> `

**Comment by JaneCheung** [comment]
Never mind ~~~
After I used the correct one, I still could not see any  charging station.
![1111111111111](https://user-images.githubusercontent.com/39317241/41255763-38b1b3d2-6d8d-11e8-8112-b893dc86a96c.png)

**Comment by namdre** [comment]
I was not yet expecting you to see them but rather hoped there would be another error message that sheds light on this mystery. 
I still have no Idea what could be causing this (despite using an old version of sumo that predates chargingStations and thus ignores them. But your 'About' Dialog contradicts this).

Maybe my colleague @palvarezlopez has access to a win10 system where this issue can be reproduced and debugged.

**Comment by JaneCheung** [comment]
Thanks a lot for your whole  and  kindly reply! I am looking forward for  @palvarezlopez  could deal with this problem !
Appreciate for what you have done for this problem!

**Comment by palvarezlopez** [comment]
@JaneCheung Effectively, Charging stations aren't loaded in Windows 10 in SUMO 0.32 (At least in the release Version)

**Comment by namdre** [comment]
@palvarezlopez  Did you figure out why?

**Comment by palvarezlopez** [comment]
@JaneCheung we observed the same problem in the release 0.32 under Windows 7.  It's only a visual problem (Charging Station are loaded but don't drawn). In the Daily version works. Can you check it?

**Comment by namdre** [comment]
I broke this in [160e368602] and Micha fixed it again in [1bed900f2e0]

**Comment by JaneCheung** [comment]
I have not noticed  the update news of this work! Thanks both of you! Appreciate for all the things you did for my question.!

**Comment by Izdhar** [comment]
please help me 
![image](https://user-images.githubusercontent.com/39618668/53906920-22b60080-405d-11e9-93e2-6a3393030fe1.png)
when i run in sumo-gui , this error show , please help me to solve it

**Comment by namdre** [comment]
see https://sumo.dlr.de/wiki/FAQ#What.27s_the_deal_with_schema_resolution_warnings_.2F_xsd_errors.3F
