### ISSUE TITLE
add 4-junctions scenario with emergency vehicles

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#4202]
extra scoring for emergency vehicle delay
Extra delay panel in the gui

**Comment by lbieker** [comment]
Emergency vehicles are colored like the other vehicles this looks not good for the sumo game. Maybe use default colors for emergency vehicle in gaming mode?

**Comment by namdre** [comment]
Yes. I think that would be an improvement.

**Comment by m-kro** [comment]
Should be complete, right?
