### ISSUE TITLE
actuated type of traffic lights

### ISSUE THREAD

**Issue by JaneCheung** [eclipse/sumo#4205]
Hi, 
   Here is one word confused me when I was trying to define the type of traffic light.
   for example
<tlLogic id="0" programID="my_program" offset="0" type="actuated">

What dose **actuated**  mean? What actuated the dynamic phase duration time of traffic lights? In other words, what are the factors that will influence the duration each phase of traffic light ?Are there some mathematical formulations  that SUMO used to model the function of "actuated "?

Looking forward for your reply! 

Appreciate for you reading this message!

**Comment by namdre** [comment]
Hello,
please adress further usage and documenation question to the mailing list (this issue tracker is intended for bugs and feature request).
For an answer to your question, see http://sumo.dlr.de/wiki/Simulation/Traffic_Lights#Actuated_Traffic_Lights
