### ISSUE TITLE
energy charged is negative

### ISSUE THREAD

**Issue by JaneCheung** [eclipse/sumo#4213]
Hi, there is  a  result  that I found in    **line 69-71**  of "sumo/tests/sumo/extended/electric/chargingStations/battery.sumo"   
https://github.com/eclipse/sumo/blob/master/tests/sumo/extended/electric/chargingStations/battery.sumo

<timestep time="11.00">
   <vehicle id="veh0" energyConsumed="-10.5040" actualBatteryCapacity="12957.4612" maximumBatteryCapacity="35000.0000" chargingStationId="NULL" energyCharged="0.0000" energyChargedInTransit="0.0000" energyChargedStopped="0.0000" speed="3.9500" acceleration="-5.0000" x="-930.0000" y="995.0500" lane="D2_0" posOnLane="70.0000" timeStopped="0"/>
</timestep>

the energyConsumed="-10.5040" (NEGATIVE VALUE" **-**"), however, it could be seen in 11s the  
 **energyCharged="0.0000" energyChargedInTransit="0.0000" energyChargedStopped="0.0000"** 
I could not understand why it is negative value?  I thought the value should be POSITIVE VALUE  "**+** "for it did not charged in charging station between 10s -11s. The value did not match with physical phenomena.

**Comment by namdre** [comment]
This is not a bug:
The vehicle parameters in that test set a recuperation efficiency of 0.8. This means the battery is recharged when braking.
