### ISSUE TITLE
netgenerate fails with grid.alphanumerical-ids

### ISSUE THREAD

**Issue by jimonreal** [eclipse/sumo#4215]
Netgenerate does not recognize the option: --grid.alphanumerical-ids anymore. 
http://www.sumo.dlr.de/userdoc/NETGENERATE.html but the wiki shows this option.
Did you remove this option for any reason in particular?

**Comment by namdre** [comment]
yes. In the latest development version, this option is on by default and supports grids and spider networks of arbitrary size. See http://sumo.dlr.de/wiki/ChangeLog#Enhancements
If you need old style ids, call `netgenerate --alphanumerical-ids false`
