### ISSUE TITLE
cutting out a subnetwork using select+invert loses connection information unless the checkbox show-connections is set

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#4217]
Solution:
when the option auto-select nodes is active, all connections from selected edges and lanes must be selected as well when performing a rectangle selection (also applies to filter selection pending #4218)

**Comment by palvarezlopez** [comment]
@namdre Also Crossings?

**Comment by namdre** [comment]
Yes. Crossings as well.
And we probably want another checkbox for 'auto-select additionals'
