### ISSUE TITLE
I/O bottleneck when calling traci repeatly

### ISSUE THREAD

**Issue by uwmyuan** [eclipse/sumo#4233]
Description:
In the definition of method [traci.start ](https://github.com/eclipse/sumo/blob/58d0dc244f4eded3e8337a546747da6dd224400e/tools/traci/__init__.py#L78), it [inputs](https://github.com/eclipse/sumo/blob/58d0dc244f4eded3e8337a546747da6dd224400e/tests/complex/tutorial/traci_tls/runner.py#L130-L131) from xml files such as:
```
       traci.start([sumoBinary, "-c", "data/cross.sumocfg",
                             "--tripinfo-output", "tripinfo.xml"])
```
The I/O of configuation files would involve a bottleneck when running the simulation repeatly. 
Possible solution:
The `traci.start` method may take xml string of file object as inputs and the code calling this method could manuplate the xml string or file instead of writing them into a file for `traci` inputting.

**Comment by namdre** [comment]
I'm not convinced that this is an issue. Whenever you use traci.start(), then sumo must be started as well and read a .net.xml file which typically involves a lot more xml parsing compared to reading a .sumocfg file. 
You could even avoid the .sumocfg alltogether by just setting all options in the call to traci.start().
In applications where disk I/O was our bottleneck, we put everything on a ramdisk.
If I misunderstood your request, feel free to re-open the ticket.

**Comment by uwmyuan** [comment]
Hi @namdre,
Sorry for the discrepancy. I didn't mean the `.sumocfg` should be replaced with `.net.xml`.
When running multiple sumo cases, the inputs would be changed frequently. The current pipeline would be (1) manipulating the inputs objects (2) serializing the objects and writing `.net.xml` and `.sumocfg` files (3) calling `traci.start()` to read the serialized files and (4) reading results from the output files. In the experiments, the writing and reading files would take time. `ramdisk` would definitely work but mostly as a hack. Thanks for the clue. I'll try it.
I understand passing a string to the parser may be hard since the `sumo.exe` would take inputs by reading files such as `sumo -c hello.sumocfg`.

**Comment by namdre** [comment]
For what it's worth, sumo also supports reading and writing a binary data format but in our experiments that wasn't a big speedup (http://sumo.dlr.de/wiki/Simulation/Output/Binary)
Writing data to sockets is also supported: http://sumo.dlr.de/wiki/Basics/Using_the_Command_Line_Applications#Writing_files

**Comment by uwmyuan** [comment]
Thanks for the information. Could you share a sample code for writing data to sockets for the tutorial case? Should I use it to pass input parameters? Or listen to the port for outputs?

**Comment by namdre** [comment]
Currently, It can only be used to retrieve simulation outputs. As the output data is still serialized to XML and must be deserialized on the receiving side It's unlikely that this would be much faster than the ramdisk approach. 
It may take some time until I manage to put a tutorial together because I hardly use this feature myself.

**Comment by uwmyuan** [comment]
Thanks. It's a good feature anyway. Sumo is still under active development. More utilities/contribs are desired.
