### ISSUE TITLE
Improve option defaults, vehicle and vType defaults for the 1.0 release

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#4235]
Sumo Candidates

- [x] speedDev = 0.1
- [x] emergencyDecel = vClassSpecific, higher than decel
-  ~~sigma >= 0.6~~ 
- later:
  * default.action-step-length 1.0
  * step-method.ballistic

 Netconvert Candidates
- [x]  roundabouts.guess
- [x]  ramps.guess (not to add lanes but in order to set  lane attribute acceleration=true where appropriate)
-  ~~tls.allred.time 1~~
- [x]  junctions.limit-turn-speed (probably something in [1-2] depending on Lauras and Evas findings)
- [x] default.junctions.radius (4), #4024 , #4260)

**Comment by palvarezlopez** [comment]
Default values has to be updated also in GNEAttributeCarrier.h

**Comment by leoluecken** [comment]
1) We may also consider using an acceleration profile per default (refs #3920).
2) If we want to change the default vehicle model, v1.0 may be a good time point for that as well?

**Comment by namdre** [comment]
still need to iron out the bugs when apply the new emergencyDecel defaults
