### ISSUE TITLE
I met a problem when i use ./configure

### ISSUE THREAD

**Issue by HZQ950419** [eclipse/sumo#4238]
when I was compiling SUMO,I typed "./configure --with-xerces=/usr/lib --with-python",after I installed the Dependencies，but I got this error:

./configure: line 14874: syntax error near unexpected token `XERCES,'
./configure: line 14874: `PKG_CHECK_MODULES(XERCES, xerces-c >= 3.0,'

I don't know what's wrong, whether I install the Xerces-C wrongly or "--with-xerces=/usr/lib" is wrong.
Could anyone help me? Thank you!

**Comment by behrisch** [comment]
Could you please post which operating system (with version you are at). It looks like pkg-config may be missing.

**Comment by HZQ950419** [comment]
I have solve it ,thank you all the same !
