### ISSUE TITLE
start a simulation with python

### ISSUE THREAD

**Issue by HZQ950419** [eclipse/sumo#4268]
I am building a traffic_light program with traci ,but I don't know which function I can use to start a simulation without clicking the start buttons in the sumo-gui.
Could anyone help me?Thanks!

**Comment by namdre** [comment]
the simulation will start running automatically when the option --start is set (in the traci start() function or in the .sumocfg). Please post future questions of this type to the mailing list (http://sumo.dlr.de/wiki/Contact)
