### ISSUE TITLE
add new coloring mode 'color by param' (all objects)

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#4276]
when selecting this mode, two new input fields must appear:
- param (string)
- default value (float)

The values for the given param must be convertable to float.

**Comment by palvarezlopez** [comment]
This new feature affects to NETEDIT?

**Comment by namdre** [comment]
Yes. I'll test how it works in SUMO-GUI and then I would also put it into Netedit

**Comment by namdre** [comment]
fixed via 1c6d0bb75d0d382f9ff0d11e8c046246767c066c
