### ISSUE TITLE
adapt sub-step departPos according to departSpeed

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#4277]
When specifying a departure time that is not a multiple of the the simulation step-length, the vehicle is currently inserted earlier.

When specifying a numerical departPos, the actual insertion position should be shifted upstream according to the vehicle speed so that the vehicle passes the specified departPos at the specified departure time (interpolating between steps).

Implementation Options:
- add a global option to toggle this behavior (default stays as it is)
- add a new departPos value (eg 'extrapolate:42') to enables this behavior for specific vehicles

**Comment by behrisch** [comment]
I don't like the idea of modifying a given insertion pos. What happens if a detector is inbetween or the lane ends?

**Comment by namdre** [comment]
Making this adaption optional would be better than having it mandatory.
The lane length would be an obvious limit to the position adaptation. 
As it stands now, there is no possibility for declaring an evenly spaced flow with arbitrary spacing independent of the step-length. I would like to see some way to remedy this.

**Comment by namdre** [comment]
@behrisch  How about using a compound value: `departPos="extrapolate:42"` 
This would at least be explicit.

**Comment by namdre** [comment]
I'm still in favor of changing the default so that extrapolation is active unless disabled. However, I still want to run more tests before this.
