### ISSUE TITLE
duarouter cannot handle additional files

### ISSUE THREAD

**Issue by levente-s** [eclipse/sumo#4279]
...or at least not the same way as sumo does.
In the latest development version, I tried to call duarouter, providing 2 additional files (with taz and vType definitions). Duarouter reported the following error:

Error: Found root element 'additional' in file 'vTypes.add.xml' (expected 'routes').

The same files can be parsed by sumo without an error.

**Comment by namdre** [comment]
This is overspill of #4272 and will be fixed.
