### ISSUE TITLE
Error loading a saved state with "impatience" vehicle type attribute

### ISSUE THREAD

**Issue by levente-s** [eclipse/sumo#4280]
To reproduce the error:
1. run a simulation with the following vehicle type definition:
\<vType id="default" impatience="0.5"/>
2. save the simulation state
3. try to load the saved state

The following error will be reported:
Error: Attribute 'impatience' in definition of vType 'default' is empty.

**Comment by namdre** [comment]
I can neither reproduce this with the latest development version nor with 0.32.0.
Please provide the unloadable state file, all inputs used to generate it and the configuration files for saving as well as loading.

**Comment by levente-s** [comment]
I attached the network and the route file.
I start the simulation with:
`sumo -n a.net.txt -r trip.txt --save-state.times 10 --save-state.files state.sbx -e 20`

I load the saved state with:
`sumo -n a.net.txt -r trip.txt --load-state state.sbx`

I noticed that the error only occurs when I use the **sbx** format

[a.net.txt](https://github.com/eclipse/sumo/files/2148533/a.net.txt)
[trip.txt](https://github.com/eclipse/sumo/files/2148534/trip.txt)
