### ISSUE TITLE
The performance index 'Duration' is increasing explosively

### ISSUE THREAD

**Issue by HZQ950419** [eclipse/sumo#4291]
I am trying to optimize the traffic light timings based on reinforcement learning ,but I meet a problem ,the performance index 'Duration' is increasing explosively.At the beginning,the Duration is about 8092 ms,but soon,it increased to 130000 ms,and is still increasing.
I don't know what is wrong ,could you please tell me the possible reasons?

**Comment by namdre** [comment]
this question has been answered already on the mailing list. I have forwarded the answer to your email address in case you missed it.
