### ISSUE TITLE
Replace wiki search field with Google search

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#4303]
https://www.mediawiki.org/wiki/Extension:GoogleSiteSearch

**Comment by behrisch** [comment]
Well, just have a look. It looks pretty urgh. I also tried https://www.mediawiki.org/wiki/Extension:GoogleCustomWikiSearch which did not work at all

**Comment by behrisch** [comment]
We can maybe apply for an NGO account at Google to remove the ads. I leave this open as a reminder.

**Comment by behrisch** [comment]
Furthermore the Google CSE shttps://cse.google.com/cse/create/getcode?cx=017443838066251231748%3Acivv5xqe2bk till needs to be moved to an institutional account instead of my private one

**Comment by angelobanse** [comment]
https://support.google.com/customsearch/answer/4542102?hl=en

**Comment by angelobanse** [comment]
The process to obtain a Google NGO account is complicated and SUMO / DLR does not apply. The Eclipse Foundation itself wanted to apply for the same reason (get an Ad free Google Custom Search for their site) and was rejected.

Google CSE is already implemented in the SUMO documentation. 
To not see the ads, users must simply have an Adblocker (most people already have that).
