### ISSUE TITLE
Collision detection at crossings

### ISSUE THREAD

**Issue by rgugale** [eclipse/sumo#4311]
I am trying to get a warning for a collision taking place at a junction in SUMO. However, even after setting the junction as 'traffic_light_unregulated', and the --collision.check-junctions set as true and the --collision.action warn set as well, I do not get a collision warning in SUMO. 

I request you to please help me with the required changes to get a warning for such collisions.

The attachments include the example files. 

Please let me know in detail, what changes have to be made for getting a warning in SUMO for the collisions.

Regards, 
Rohan

[Files.zip](https://github.com/eclipse/sumo/files/2171015/Files.zip)

**Comment by namdre** [comment]
If you set a junction to 'unregulated' it will not perform any type of collision checking on the intersection. I've updated the documentation at http://sumo.dlr.de/wiki/Networks/PlainXML#Node_types.

To force a collision you can set the junction to type 'priority' and then set unsafe right-of-way rules by editing the connections from the side road with netedit and set the attribute 'pass=true'

Alternatively, you can override the speed of one vehicle using traci.vehicle.setSpeedMode and setSpeed to create collision without altering the network. Or you can create a traffic-light controlled junction and set both directions to green.

See http://sumo.dlr.de/wiki/Simulation/Safety#Deliberately_causing_collisions
