### ISSUE TITLE
Unwanted Braking in SUMO to avoid Collisions 

### ISSUE THREAD

**Issue by rgugale** [eclipse/sumo#4317]
I am writing an algorithm to control the vehicles at an intersection in SUMO. I want to get the collisions occurring at the junction because of this algorithm to evaluate its performance. However, I can see some irregularities in the functioning of the Algorithm. 

1) When I release the vehicle using my Algorithm in TraCI, it collides with the other vehicle and gives me a warning (Can be seen in the first screenshot that I have attached)

2) Sometimes, even when the vehicle has been released by me using TraCI, the vehicle brakes and lets the other vehicle pass and then it crosses the junction (refer to the second image - the red vehicle brakes even when the algorithm has released the vehicle and does not collide with the yellow vehicle). This is an undesirable behavior for me and I want to know the cause for

Please help me with parameters that might help me to avoid this behavior and get collisions if the vehicles have been released. I do not want the vehicles to brake on their own. 
Thanking you in Anticipation.

Regards,
Rohan 

![collision_warning_desired](https://user-images.githubusercontent.com/38133758/42459791-b57c3426-839c-11e8-8b80-a873a57d388a.png)
![undesired_braking](https://user-images.githubusercontent.com/38133758/42459794-b86a79a4-839c-11e8-8790-9de34ddad84c.png)

**Comment by namdre** [comment]
Vehicles, by default react to other vehicles that are on an intersection and blocking their path.
To disable this, you need to use traci.vehicle.setSpeedMode(). Setting speedMode to 0 disables all checks.
Refer to  http://sumo.dlr.de/wiki/TraCI/Change_Vehicle_State#speed_mode_.280xb3.29 for details.

**Comment by namdre** [comment]
please attach all your scenario files as a zip archive, so I can reproduce the issue on my side.

**Comment by rgugale** [comment]
Please find in the attachments my SUMO files in the data.zip file. Also, I have attached the Python Script that has the algorithm. 
Please let me know what may be possibly wrong and the vehicles are braking at the junction. 

After you run the simulation, at time step 216, 441, 530 and 544 you can see the undesired behaviors. The behavior is extremely clear at time steps 530 and 544. 

The Python file 'Sumo_Custom_Algorithm' has been attached as a Text (.txt) file. 


[Sumo_Custom_Algorithm.txt](https://github.com/eclipse/sumo/files/2179812/Sumo_Custom_Algorithm.txt)


[data.zip](https://github.com/eclipse/sumo/files/2179774/data.zip)

**Comment by namdre** [comment]
The behavior of setSpeedMode only affects speeds that are set via TraCI (setSpeed, slowDown).
Please see http://sumo.dlr.de/wiki/TraCI/Change_Vehicle_State#speed_mode_.280xb3.29

(Vehicles really try to avoid collisions unless forced to do so)

**Comment by rgugale** [comment]
If the vehicles try to avoid collisions even when they have been released unsafe, how can performance of algorithms be evaluated ? 
Also, if I try to set the speed of the vehicles using setSpeed, the behavior of the entire simulation is too vague. 
Please advise what should be used to make collisions happen !

**Comment by namdre** [comment]
In most research on traffic light algorithms I have seen, a basic assumption is that they must seperate conflicting streams. I'm not aware that this type of basic safety was ever a performance criterion (as it is quite trivial to ensure).
Also, vehicles only react to other vehicles that are already visible on the intersection and in their path. Your example scenario shows plenty of collisions from vehicles that drive onto the intersection at the same time. I posit that both kinds of behavior are plausible. Human drivers also would avoid collisions if they can see a vehice in their path and there is time to brake.

If you want to see more collisions you can reduce the available braking force for vehicles. (set decel=0.5 in the vType).

**Comment by rgugale** [comment]
We are trying to write an algorithm to extract maximum efficiency of the traffic flow. We also know that this may result into collisions and hence only after a collision has been registered, we can tweak our algorithm. I tried using slowDown to set the desired speed again so that they do not stop at the junction, but it results in vehicles colliding within the same lane. It disregards the Follow Model.
Is there any other solution to this problem ? 
If yes, please let me know.

**Comment by namdre** [comment]
I think a good approach would be to use setSpeed only if the vehicle is the first one at the intersection and reset to the regular speed once it reaches the edge beyond the intersection using setSpeed(vehID, -1)
