### ISSUE TITLE
Disable editing of GEO Parameters in Netedit if parameter "Projection" isn't set

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#4328]
POIs and Polys with GEO-coordinates needs the parameter "~~Location~~" "Projection". In other case, cannot be loaded in SUMO-GUI

**Comment by namdre** [comment]
In SUMO-GUI the location parameter of the current network should always be used. If there is an error it mus be something else.

**Comment by namdre** [comment]
Netedit, also should not use the projection of the shape file but that of the loaded network. If the current network does not have a geo projection, loading should fail (it does not make sense to have geo-referenced pois in a non-geo-referenced network)

**Comment by palvarezlopez** [comment]
@namdre then editing of GEO Position parameters should be disabled if current edited network doesn't have Projection?

**Comment by namdre** [comment]
yes
