### ISSUE TITLE
import internal lane shapes from OpenDRIVE

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#4331]

**Comment by chengyuny** [comment]
Hi, I am very interested in this feature. How is it going now? Thanks

**Comment by namdre** [comment]
@chengyuny Please test out the new option --opendrive.internal-shapes
There are still some geometry issues (see above comment)
If you could provide example xodr inputs that would be great as well.

**Comment by chengyuny** [comment]
Hmm. Your change is almost the same as what I did locally. However, this solution is highly dependent on the fact that the connecting road geometry is precisely connected at the start/end point with the incoming road or outgoing road which is not always guaranteed according to the OpenDrive files I tested.

**Comment by namdre** [comment]
Yes. The internal lane shape has to be taken into account when defining the edge and junction geometry.
Currently, the process consists of three steps:
1) junction geometry is computed based on the edge geometries 
2) edges that do not reach the junction shape are extended and those that go beyond it are cut off
3) internal lane geometries are computed based on these modified edge geometries

I see at least two options to deal with pre-defined internal lane geometries:
a) take internal lane geometries into account when computing junction geometries (basically, use them to define where the junction starts)
b) extend the internal shapes or cut them off to match the computed junction shape

The answer should depend on the quality of junction shapes that can be achieved with option a) In the past I had some networks were that did not look feasible. Option b) seems safer in this regard but it could also lead to the loss of useful information.


I think b) should be implemented first and a) should be implemented as an option at a later time.

**Comment by namdre** [comment]
b) doesn't solve all problems so a) is needed as well.

**Comment by namdre** [comment]
a) is already working. remaining issues where due to #4812
