### ISSUE TITLE
Building SUMO: local build of xerces-lib not found

### ISSUE THREAD

**Issue by Stigjb** [eclipse/sumo#4345]
I am trying to install SUMO (0.32.0) on a server, and have built the libraries xerces-c (3.1.4), gdal (1.11.2) and proj (4.6.1) locally. For the most part this went well according to [the guide in the SUMO wiki](http://sumo.dlr.de/wiki/Installing/Linux_Build_Libraries#The_Libraries), except for xerces, where the commands in the wiki do not match the xerces source structure. For instance, there is no `runConfigure` script in `<xerces>/src/xercesc`. Instead, I built xerces using `./configure --prefix=$HOME && make install`, similarly to the other libraries.

I am now trying to build SUMO, but the configure script stops on the error `configure: error: xerces-lib not found in "<HOME>/lib".` However, `libxerces-c.a`, `libxerces-c.la` and `libxerces-c.so` all exist in `<HOME>/lib`.

Is the configure script looking for them by another name? Is there a versioning issue?

I tried to install another version of xerces-c, namely 3.0.1, the one mentioned in the SUMO wiki, but to no avail. There is no `runConfigure` script in that version of the repository, either, and the command that worked in xerces 3.1.4 exited with a syntax error in the `configure` script in xerces 3.0.1.

**Comment by palvarezlopez** [comment]
Hi,

Do you have „Xercesc-dev“installed? (you can find it in the Linux repository)

Regards

Von: Stig Johan Berggren [mailto:notifications@github.com]
Gesendet: Mittwoch, 18. Juli 2018 14:43
An: eclipse/sumo
Cc: Subscribed
Betreff: [eclipse/sumo] Building SUMO: local build of xerces-lib not found (#4345)


I am trying to install SUMO (0.32.0) on a server, and have built the libraries xerces-c (3.1.4), gdal (1.11.2) and proj (4.6.1) locally. For the most part this went well according to the guide in the SUMO wiki<http://sumo.dlr.de/wiki/Installing/Linux_Build_Libraries#The_Libraries>, except for xerces, where the commands in the wiki do not match the xerces source structure. For instance, there is no runConfigure script in <xerces>/src/xercesc. Instead, I built xerces using ./configure --prefix=$HOME && make install, similarly to the other libraries.

I am now trying to build SUMO, but the configure script stops on the error configure: error: xerces-lib not found in "<HOME>/lib". However, libxerces-c.a, libxerces-c.la and libxerces-c.so all exist in <HOME>/lib.

Is the configure script looking for them by another name? Is there a versioning issue?

I tried to install another version of xerces-c, namely 3.0.1, the one mentioned in the SUMO wiki, but to no avail. There is no runConfigure script in that version of the repository, either, and the command that worked in xerces 3.1.4 exited with a syntax error in the configure script in xerces 3.0.1.

**Comment by Stigjb** [comment]
The only xerces-related packages that seem availalble for install via the server's package manager are the following:
```
$ yum search xerces
Loaded plugins: dkms-build-requires, priorities, update-motd, upgrade-helper
=================================================================== N/S matched: xerces ===================================================================
xerces-j2-demo.noarch : Demo for xerces-j2
xerces-j2-javadoc-apis.noarch : Javadoc for xerces-j2 apis
xerces-j2-javadoc-impl.noarch : Javadoc for xerces-j2 implementation
xerces-j2-javadoc-other.noarch : Javadoc for other xerces-j2 components
xerces-j2-javadoc-xni.noarch : Javadoc for xerces-j2 xni
xerces-j2-scripts.noarch : Additional utility scripts for xerces-j2
xerces-j2.noarch : Java XML parser
```
As mentioned, I have `libxerces-c.a` in my ~/lib folder after building Xerces.

**Comment by behrisch** [comment]
Which OS / distribution are you using? This sounds like it might be a little outdated. You might run into more trouble if your compiler does not support C++11.

**Comment by Stigjb** [comment]
OS is Amazon Linux AMI 2017.09. It's got GCC 4.8.5.

**Comment by palvarezlopez** [comment]
Command „sudo yum install xerces-c-devel” doesn’t work?

Von: Stig Johan Berggren [mailto:notifications@github.com]
Gesendet: Donnerstag, 19. Juli 2018 08:22
An: eclipse/sumo
Cc: Alvarez Lopez, Pablo; Comment
Betreff: Re: [eclipse/sumo] Building SUMO: local build of xerces-lib not found (#4345)


OS is Amazon Linux AMI 2017.09. It's got GCC 4.8.5.

**Comment by Stigjb** [comment]
No, `No package xerces-c-devel available`.

**Comment by palvarezlopez** [comment]
Try to download it from here:

https://rpmfind.net/linux/rpm2html/search.php?query=xerces-c-devel

Regards

Von: Stig Johan Berggren [mailto:notifications@github.com]
Gesendet: Donnerstag, 19. Juli 2018 15:48
An: eclipse/sumo
Cc: Alvarez Lopez, Pablo; Comment
Betreff: Re: [eclipse/sumo] Building SUMO: local build of xerces-lib not found (#4345)


No, No package xerces-c-devel available.

**Comment by Stigjb** [comment]
I'm not sure which of the downloads on that page would be appropriate for the Amazon Linux OS, but I'll try to ask around to find out.

In any case, I think the Linux build instructions on the SUMO wiki need a review. For instance, the mentioned `runConfigure` script in the Xerces sources doesn't seem to exist in the download. And the external link to "Xerces build" on [this page](http://sumo.dlr.de/wiki/Installing/Linux_Build_Libraries) of the Wiki is dead.

**Comment by Stigjb** [comment]
My problem has been resolved. `xerces-c-devel` was, in fact, available in an unenabled repository and could be installed with `sudo yum install xerces-c-devel --enablerepo=epel`. However, I still think the build info in the wiki needs review. In addition, the source download from [sumo.dlr.de](sumo.dlr.de) lacks `Makefile.cvs`.
