### ISSUE TITLE
nightly netedit builds are broken

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#4347]
Currently some tests seem to hang and cannot be killed. Therefore the old netedit binary cannot be deleted and the win64 package contains the 32 bit netedit binary which won't work.

**Comment by palvarezlopez** [comment]
@behrisch Probably the problem is the Netedit test Sikulix_Error. Sikulix doesn't kill Netedit.

**Comment by palvarezlopez** [comment]
The problem is caused  by a inconsistence between the function wait(...) of sikuli and Java.
