### ISSUE TITLE
The sumo.exe or sumo-gui.exe stop and quit,when I control a vehicle via moveToXY function.

### ISSUE THREAD

**Issue by Lengfan** [eclipse/sumo#4371]
The vehicle travels on a curved road which made up of many short straight lines.
  And my driving algorithm will calculate the position of the next step of the vehicle,so I control it via moveToXY() function.
 It will work for a while, but in a specific place the sumo.exe program will lose its response and then quit without any error message. The vehicle will change its lane,but no more action. 
Bye the way,if I put the vehicle directly at the beginning of the simulation where it crashed last time, the program will not crash.
![image](https://user-images.githubusercontent.com/13976612/43458838-3a7470b8-94fe-11e8-96ac-e52ea5595869.png)
![image](https://user-images.githubusercontent.com/13976612/43459027-b95d866c-94fe-11e8-8d1c-f65b1462924c.png)
As you can see in the picture,the sumo.exe quit at step 22.07,and without any message.
What could be the reason, thank you for your help.

**Comment by namdre** [comment]
Please check if the problem still appears when using the latest development version (http://sumo.dlr.de/wiki/Downloads#SUMO_-_Latest_Development_Version)
If it does, attach input files that allow reproducing the crash.

**Comment by namdre** [comment]
closing due to lack of response and reproduction data.
