### ISSUE TITLE
document/clarify semantics of MSVehicle::myAmOnNet (trac #438)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#438]
Migrated from http://sumo.dlr.de/ticket/438
```json
{
    "status": "assigned", 
    "changetime": "2014-10-20T12:36:39Z", 
    "description": "", 
    "reporter": "namdre", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1413808599169752", 
    "component": "documentation", 
    "summary": "document/clarify semantics of MSVehicle::myAmOnNet", 
    "priority": "major", 
    "keywords": "", 
    "time": "2011-01-27T13:26:07Z", 
    "milestone": "1.1.0", 
    "owner": "namdre", 
    "type": "task"
}
```

**Comment by namdre** [comment]
myAmOnNet means: driving on a lane (as opposed to teleporting, waiting for insertion or driving off-road via moveToXY)

**Comment by behrisch** [comment]
@namdre does this differ from having a valid lane pointer? Also from looking at the code I am not sure whether movetoxy really sets this to false.

**Comment by namdre** [comment]
postProcessRemoteControll always starts with removeVehicle->leaveLane which sets myAmOnNet=false,
then, if a new lane exists the flag is switch back on via forceVehicleInsertion->enterLaneAtInsertion
