### ISSUE TITLE
invalid walking distance and timeLoss in pedestrian  in tripinfo output

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#4385]
reported by Gregory at August 1st via sumo-user

**Comment by namdre** [comment]
triggered when the first two edges a the reverse of each other or the last two edges are the reverse of each other (walking direction is ambiguous without routing)

**Comment by kmalena** [comment]
still seems to be an issue for me...
defining via TRACI a route with start edge, crossing and end edge the routeLength is way too big and therefore negative time losses can result...
I need the crossing edge to prevend the person to take a different route over the junction

**Comment by namdre** [comment]
@kmalena now tracked at #11983  (next time please open up a new ticket and mention the old one in the ticket description)
