### ISSUE TITLE
Vehicle Too close to Break error

### ISSUE THREAD

**Issue by rgugale** [eclipse/sumo#4386]
I am writing an algorithm using TraCI to control the vehicles at an intersection without a traffic signal. However, I am getting a few very random errors in SUMO. 
I send a  command to the vehicle as soon as it is detected by the detector to stop at a distance 482 from the junction start  using the command - 

traci.vehicle.setStop(vehicle, "4i", 482, 1)

At some next time step, I request the vehicle to be released using the command - 
(The vehicle has not yet reached 482, it is at 478 but it has started decelerating)

traci.vehicle.setStop(vehicle, "4i", 482, 1, 0)

At the same time step, I give it a new command to wait at a further distance - 
traci.vehicle.setStop(vehicle, "4i", 485, 1)

However, the simulation crashes during this command and outputs an error - vehicle is too close too brake on lane 4i_1

I do not understand the reason of this error. Any help would be appreciated. 

Also, the errors are not reproducible, because, at each simulation run, the same error takes place for different vehicles and SUMO shuts down. All the generators have been seeded to generate the same numbers each time during the Simulation.

I request you to please let me know, what might be the cause of this error.

**Comment by namdre** [comment]
the error "too close to brake' is not fatal.
You can continue simulation by catching the exception:
```
try:
  traci.vehicle.setStop(....)
except traci.TraCIException:
  pass

To understand what is happening, take a look at the speed of the vehicle and it's distance from the requested stop position.
```
