### ISSUE TITLE
Closing the sumo session after an error and starting a new one using TraCI

### ISSUE THREAD

**Issue by rgugale** [eclipse/sumo#4389]
I am trying to write an algorithm for controlling the vehicles at an intersection using TraCI without the conventional traffic lights. 
Due to a random error - Vehicle too close to brake on lane 'X', my Simulation stops. 
I want to execute multiple times the SUMO session. So after the first one crashes with the above error, I want it to close that session and start the new one. 
How can this be done using TraCI ? 
Please let me know if it is possible.

**Comment by namdre** [comment]
Please post future usage questions to our mailing list: http://sumo.dlr.de/wiki/Contact
You can recover from "too close to brake" as indicated in #4386
You can restart your simulation using the command traci.load
