### ISSUE TITLE
"tests" folder not downloaded when downloading zip file of repository

### ISSUE THREAD

**Issue by arsenious** [eclipse/sumo#4433]
Hi

I've noticed that when downloading the zip version of the repository, the "tests" folder doesn't get downloaded. I was searching for it based on the wiki tutorials I was following, but couldn't find it locally. 

However, cloning the repository ensures "tests" folder is downloaded. 
Not sure if this is a bug or on purpose

**Comment by namdre** [comment]
test have a separate download package: 
http://sumo.dlr.de/daily/sumo-tests-git.tar.gz
(see http://sumo.dlr.de/wiki/Downloads)

**Comment by namdre** [comment]
note: the tests folder is excluded specifically from the zip download using` .gitattributes`:
`tests export-ignore  `

**Comment by arsenious** [comment]
Thank you for the clarification!
