### ISSUE TITLE
jmSigmaMinor > 0 does not imply dawdling at approach

### ISSUE THREAD

**Issue by leoluecken** [eclipse/sumo#4434]
See test junction_model/jmSigmaMinor/keep_dawdling_jmSigmaMinor

**Comment by namdre** [comment]
I think it is workign as intended:
- vehicles below visibility distance approaching an open minor link always us vLinkPass (MSVehicle.cpp:2555)
In the test network, visibility was set to 100

The parameter jmSigmaMinor comes into play once the vehicle is on the intersection. (Step 7)

**Comment by leoluecken** [comment]
Oh, then I misunderstood that... I thought jmSigmaMinor would take effect during the approach.

**Comment by namdre** [comment]
I guess It would make sense to change the behavior so that it takes effect within the visibility distance. But then we would have to change the default value to 0 to better reproduce the current dynamics.
