### ISSUE TITLE
freeze when selecting many objects via attribute

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#4454]
caused by calls to updateLockGLObjectTypes().

**Comment by namdre** [comment]
@palvarezlopez Mass selection becomes usable again. As an unfortunate side effect, the selection statistics is no longer updated on undo/redo. 
To fix this without major slowdowns is going to be tricky and should be addressed after the release.

**Comment by palvarezlopez** [comment]
@namdre I have an idee to fix this.

**Comment by palvarezlopez** [comment]
@namdre Yes, I'm going to try it today.
