### ISSUE TITLE
Crash setting Position of a Junction through Inspector in the same position of another Junction

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#4483]
Instead should be shown a "Merging Junction" dialog.

**Comment by namdre** [comment]
@palvarezlopez  I could not reproduce the crash now. If it's the same for you, then the remaining task is left for the next milestone

**Comment by palvarezlopez** [comment]
@namdre Problem is caused by Crossings. Try it in input_network.net.xml
