### ISSUE TITLE
Inconsistent default edge priorities (trac #449)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#449]
Merged edges have default priority ''0'' while unmerged edges have default priority ''-1''. 

see ''tests\netconvert\function\join_double_conn\plain''

The offending code is in NBEdgeCont::joinSameNodeConnectingEdges
but I'm not sure what the default priority is really supposed to be.

Migrated from http://sumo.dlr.de/ticket/449
```json
{
    "status": "new", 
    "changetime": "2011-02-04T07:48:12Z", 
    "description": "Merged edges have default priority ''0'' while unmerged edges have default priority ''-1''. \n\nsee ''tests\\netconvert\\function\\join_double_conn\\plain''\n\nThe offending code is in NBEdgeCont::joinSameNodeConnectingEdges\nbut I'm not sure what the default priority is really supposed to be.\n", 
    "reporter": "namdre", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1296805692000000", 
    "component": "other (also unclassified)", 
    "summary": "Inconsistent default edge priorities", 
    "priority": "minor", 
    "keywords": "", 
    "time": "2011-02-04T07:48:12Z", 
    "milestone": "1.0.0", 
    "owner": "", 
    "type": "defect"
}
```

**Comment by behrisch** [comment]
The priority should be inherited from the merged edges and there should be no changes in the default. If the edges have different priorities they should not be merged.

**Comment by behrisch** [comment]
@lbieker Thanks for solving this. Could you do a test for not merging edges of different priorities as well?

**Comment by lbieker** [comment]
The egdes are not merged now when the priorites are different, but it looks a little bit weird in sumo-gui because the unmerged edges are overlapping. Should I add a warning? @behrisch

**Comment by namdre** [comment]
As far as I can tell the option **--edges.join** (parallel joining) has not been relevant for a long time. We usually do not have input networks that need to be treated with this option. I also don't think that different priorities should prevent merging. The current code even computes the new speed as the average of the joined speeds.

This should not be mistaken for the intended semantics of option **--geometry.remove** (lengthwise-join) where different speeds and priority should definitely prevent joining.

@behrisch: Do you have any example where this option is currently useful?

**Comment by behrisch** [comment]
While I could imagine use cases from OSM or OpenDrive where things are modelled as separate edges when we may want to allow lane changes, I currently do not have an example. And I agree it is not an important feature.

I am not sure why the merging code averages speed when it is possible to have different max speeds for different lanes. I would consider this a bug. And I would not average the priority as well or at least give a warning if this induces junction logic changes.

**Comment by behrisch** [comment]
> The egdes are not merged now when the priorites are different, but it looks a little bit weird in sumo-gui because the unmerged edges are overlapping. Should I add a warning? @behrisch
We never give a warning if edge geometries overlap, so I don't think we start this now :-)

**Comment by namdre** [comment]
> We never give a warning if edge geometries overlap, so I don't think we start this now :-)
Well no. There is netconvert option ** --geometry.check-overlap** and even **--geometry.check-overlap.vertical-threshold**
In short: The user could already get a warning if desired.
