### ISSUE TITLE
Show "Lon/Lat" instead GeoPosition" in inspector frame for POI/POILanes

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#4495]

**Comment by namdre** [comment]
do you just want to rename the label or split the attribute? 
There is a reason why the virtual attribute exists: so that copy/paste is more convenient.
The same is done for junction position which use attributes 'x' and 'y' in the xml files.

**Comment by palvarezlopez** [comment]
@namdre I need to rename the label and check if it actually works
