### ISSUE TITLE
shape files should get the .xml extensions automatically when saving

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#4497]
recheck additional and tls filename as well

**Comment by palvarezlopez** [comment]
@namdre additionals, shapes and TLS already saved automatically the output files with .xml extension

```
    FXString file = MFXUtils::getFilename2Write(this,
                    "Select name of the shape file", ".xml",
                    GUIIconSubSys::getIcon(ICON_MODEPOLYGON),
                    gCurrentFolder);
```

Or do you mean "<name>.add.xml"?

**Comment by namdre** [comment]
It's working as expected. must have been a mistake on my part.
