### ISSUE TITLE
what the naming rules of  the linkIndex  in traffic light file? 

### ISSUE THREAD

**Issue by passengerxuhongli** [eclipse/sumo#4504]
how can i konw which linkIndex is control which connection without the sumo-gui? for example:
`<additional>    <tlLogic id="0" programID="my_program" offset="0" type="static">       <phase duration="31" state="GGggrrrrGGggrrrr"/>       <phase duration="5"  state="yyggrrrryyggrrrr"/>       <phase duration="6"  state="rrGGrrrrrrGGrrrr"/>       <phase duration="5"  state="rryyrrrrrryyrrrr"/>       <phase duration="31" state="rrrrGGggrrrrGGgg"/>       <phase duration="5"  state="rrrryyggrrrryygg"/>       <phase duration="6"  state="rrrrrrGGrrrrrrGG"/>       <phase duration="5"  state="rrrrrryyrrrrrryy"/>    </tlLogic> </additional>` 
the first pahse controls  wihch direction of intersection?

**Comment by namdre** [comment]
Please post usage questions to the sumo user mailing list (http://sumo.dlr.de/wiki/Contact).

You can obtain the relationship between linkIndex and controlled connections in 3 ways:
- via traci.trafficlight.getControlledLinks
- via sumolib.net.getLane().getOutgoing(index).getTLLinkIndex
- via sumolib.net.getTLS(id).getLinks()
- parsing a .tll.xml file (obtained netconvert -s your.net.xml --plain-output-prefix plain)
