### ISSUE TITLE
Emergency stop at red light with deceleration lower than default

### ISSUE THREAD

**Issue by levente-s** [eclipse/sumo#4509]
Dear developers,

I made a simple example that shows an emergency braking at red traffic light.
I would say that the conditions are quite close to real-world values:
* speed limit 50 km/h
* 3s yellow phase
* deceleration 3.4 m/s²

To run the simulation I use
`sumo -r rou.txt -n net.net.txt --step-length 0.1`

An emergency stop occurs in the simulation.
[net.net.txt](https://github.com/eclipse/sumo/files/2339228/net.net.txt)
[rou.txt](https://github.com/eclipse/sumo/files/2339229/rou.txt)

**Comment by namdre** [comment]
Please check with the very latest development version. On my end the vehicle passes the yellow light without decelerating. A bug related to braking at yellow was recently fixed (#4450) that would have caused such behavior.
