### ISSUE TITLE
"Add to selected" doesn't work

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#4526]

**Comment by namdre** [comment]
@palvarezlopez can you give some details, please?

**Comment by palvarezlopez** [comment]
@namdre Contextual Button "add to selected" doesn't work in Netedit. The reason is that button calls the function "gSelected.deselect(myObject->getGlID());" throught "MID_ADDSELECT/MID_REMOVESELECT" . This add the object to gSelected, but doesn't changes the Flag "selected" of GNEAttributeCarriers.

**Comment by palvarezlopez** [comment]
Select edges will be implemented in #4549
