### ISSUE TITLE
refactor netedit test input files

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#4536]
input files (net, additionals, options,...)  that are the same in all sibling folders can be placed on a higher level in the folder hierarchy and will be added automatically by texttest

If only some tests in a suite needs a different network, the network can be placed in the test folders  for those tests and the default could still be placed in the suite or below to be used by all others.

As an example, take a look at the sumo tests where the network net2.net.xml is placed directly in tests/sumo and used by many tests in subfolders and sub-sub-...-sub-folders

**Comment by namdre** [comment]
@palvarezlopez  can this be closed?

**Comment by palvarezlopez** [comment]
@namdre this isn't finished. Additionals test has to be refactored.

**Comment by palvarezlopez** [comment]
Finished in all Netedit test.
