### ISSUE TITLE
opposite-direction overtaking not considered on multi-lane road even when the other lanes are not usable

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#4550]

**Comment by rlloretb** [comment]
Does SUMO allow opposite-direction overtaking if the midline is a continuous line (not dashed)?

**Comment by namdre** [comment]
Yes. If you wish to forbid opposite overtaking explicitly you can use attribute changeLeft: https://sumo.dlr.de/docs/Networks/PlainXML.html#lane-specific_definitions

**Comment by rlloretb** [comment]
My doubt is that I would vehicles to violate the continuous line after some time whenever a vehicle is blocking the lane. So far, this is not happening (as it should, since it would be in fact an illegal maneuver)

**Comment by namdre** [comment]
attribute changeLeft/changeRight applies to specific vehicle classes. You could modify a vehicles vehicleClass after some waiting time to model their rule-compliance.
