### ISSUE TITLE
TraCI: expressing maximum time

### ISSUE THREAD

**Issue by riebl** [eclipse/sumo#4553]
Since the removal of `SUMOTime` (a.k.a. `long long int`) from TraCI API, it is not clear anymore how to express the maximum time. For example, subscribing to variables requires an `endTime` parameter which is of type `double` now. Before SUMO 1.0 one would use `SUMOTime_MAX` to express "subscribe until the end". Since SUMO 1.0 one still has to use the equivalent value but converted to double while using `DBL_MAX` fails.

Proposal: Add `MAX_TIME_VALUE` to TraCIConstants.h

**Comment by behrisch** [comment]
I think sumo should understand DBL_MAX or rather std::numeric_limits<double>::max(). You can already send INVALID_DOUBLE_VALUE though which should give the correct result.
