### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by gmusjha** [eclipse/sumo#4555]
Hello,

I am trying to compile Sumo on centos 7. Whem I am running make, I get following:

home/gmusjha/Documents/software/sumo-sim/sumo/src/libsumo/Edge.h:106: Error: Syntax error in input(3).
make[2]: *** [src/libsumo/CMakeFiles/libsumojni.dir/libsumoJAVA.stamp] Error 1
make[2]: *** Deleting file `src/libsumo/CMakeFiles/libsumojni.dir/libsumoJAVA.stamp'
make[1]: *** [src/libsumo/CMakeFiles/libsumojni_swig_compilation.dir/all] Error 2
make: *** [all] Error 2

I am using oracle  jdk 10. What could be the issue. Your kind consideration will be appreciated.

Thank you.
Regards,
gmusjha

**Comment by namdre** [comment]
This is most likely caused by SWIG using an outdated compiler.
You should be able to fix this by setting
```
ENABLE_JAVA_BINDINGS:BOOL=false
ENABLE_PYTHON_BINDINGS:BOOL=false
```
in CMakeCache.txt

**Comment by behrisch** [comment]
@gmusjha Can you please check which swig version you have installed? We require at least swig 3.0. because earlier versions do not handle C++11. I will add a check to the CMakeLists.

**Comment by gmusjha** [comment]
@behrisch Thank you. It works. Looks like centos 7 installs old swig ( may be version 2.1.0). I downloaded swig and compiled. Now everything gets compiled
