### ISSUE TITLE
TraCI Error after updating SUMO to 1.0.1

### ISSUE THREAD

**Issue by FlorianJa** [eclipse/sumo#4617]
Hi,

i am getting an error in SUMO when i try to make a simulation step via TraCI.

> Error: tcpip::Storage::readIsSafe: want to read 8 bytes from Storage, but only 4 remaining

I didnt change my TraCI code, just updated SUMO. Before the update everthing worked fine.

**Comment by FlorianJa** [comment]
i found a commit which maybe causes the problem:
https://github.com/eclipse/sumo/commit/e6478ae88b2383bd7daf8544aa1959cce388a707

`myInputStorage.readInt();` was changed to `myInputStorage.readDouble();` (4 bytes to 8 bytes)

**Comment by namdre** [comment]
This was an intended protocol change (#912) mentioned in the changelog for 1.0.0
The clients that come with sumo are patched correspondingly. 
Are you using your own client?
In that case you will have to adopt to the change.

**Comment by FlorianJa** [comment]
Ahh, ok! I am using/developing the TraCI.NET lib as client. To be honest, i didnt had a look into the changelog yet. Shame on me

**Comment by namdre** [comment]
Is your implementation related to https://github.com/CodingConnected/CodingConnected.Traci ?

**Comment by FlorianJa** [comment]
Yes!
