### ISSUE TITLE
netconvert does not apply offset values to custom shapes of nodes and crossings

### ISSUE THREAD

**Issue by m-kro** [eclipse/sumo#4621]
Two separate cases where custom shapes are not shifted but connected edges do when using netconvert: 

1. Load "SUMO native XML" edge, node and connection files in netconvert. The network features custom shapes for nodes and crossings. Use --offset.x X and offset-y Y options (X, Y != 0).
**Result: Crossings get the offset, node shapes don't**

2. Load the same network in net.xml format in netconvert and apply the same offset options.
**Result: Neither node shapes nor crossings receive the offset.**

**Comment by namdre** [comment]
found another instance where crossing shapes are not shifted as necessary
