### ISSUE TITLE
Sumo jumps and program closes unexpectedly. Bug Problem Event Name:BEX

### ISSUE THREAD

**Issue by abed1856** [eclipse/sumo#4627]
Problem signature:
  Problem Event Name:	BEX
  Application Name:	sumo-gui.exe
  Application Version:	0.0.0.0
  Application Timestamp:	5ba2e4da
  Fault Module Name:	StackHash_0a9e
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	00000000
  Exception Offset:	67800000
  Exception Code:	c0000005
  Exception Data:	00000008
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Suddenly program closes. What should I do? I saw that lots of time during simulation especially after 4000 simulation steps.

**Comment by namdre** [comment]
please attach a minimal failing set of input data

**Comment by abed1856** [comment]
> please attach a minimal failing set of input data



> please attach a minimal failing set of input data

I have sent you the file to email. namdre.sumo@gmail.com. please check it. Thanks Jakob

**Comment by namdre** [comment]
The stated address is correct but the file did not arrive.

**Comment by namdre** [comment]
Alternatively, you can zip up your files and attach them directly to this ticket.

**Comment by namdre** [comment]
I still did not receive any example files. I no example data is forthcoming, I will close the ticket.

**Comment by namdre** [comment]
closing due to lack of test data
