### ISSUE TITLE
what is this error

### ISSUE THREAD

**Issue by dcaisurusampath** [eclipse/sumo#4638]
Loading configuration... done.
Loading net-file from 'D:\Acadamic\Final year research\Research\sumo\Munich edit\galle.net.xml'... done (247ms).
Loading additional-files from 'D:\Acadamic\Final year research\Research\sumo\Munich edit\ped.add.xml'... done (1ms).
Loading additional-files from 'D:\Acadamic\Final year research\Research\sumo\Munich edit\galle.poly.xml'... done (25ms).
Loading done.
Error: The edge '-167443078' within the route for vehicle '2' is not known.
 The route can not be build.
Quitting (on error).

**Comment by namdre** [comment]
Not a github issue. Take this to the mailing list.
