### ISSUE TITLE
Wheels for SUMO

### ISSUE THREAD

**Issue by mtgibson2014** [eclipse/sumo#4639]
Hello!

I sent an email about this, but I was told to also submit an issue for it? This is what was sent ---

"We wanted to put out a quick request/idea for SUMO. Could SUMO possibly include wheels with the software (and updated wheels for every new version)? 

We know this could potentially be a big ask, but it would really be helpful to a lot of users if this was developed. Many people really enjoy using SUMO to run traffic simulations (its amazing!) and our lab at Berkeley has even used it to make a new software platform, called FLOW, for AV research. However, our users regularly encounter errors in the installation and build process. We've currently developed a practice of creating pip install wheels to install pre-compiled binaries for SUMO, but since this would break with new versions of SUMO, this seems like something best done by the SUMO project. Is it possible that this might be added to the SUMO development path? This would be great if so and would make SUMO even more awesome! 

Please let us know what you think. Thank you for your time."

Best,
Berkeley-FLOW
University of California - Berkeley

**Comment by palvarezlopez** [comment]
@behrisch what do you think?

**Comment by behrisch** [comment]
We already create a wheel for libsumo now which contains all the libraries (at least for windows) so yes we could do this. CMake also has this, but I personally dislike the idea of using pip as a general purpose (i.e. non-python) package manager. Does anyone know people doing this?

**Comment by pikeas** [comment]
New Sumo here, I would *love* wheels for macOS and Linux!

**Comment by behrisch** [comment]
I am still not convinced that this is a good idea. We have linux packages for the major distributions and a wheel would need a completely statically linked sumo.

**Comment by pikeas** [comment]
The mainline packages for Debian and Ubuntu are both for SUMO 1.1, which is 1.5 years old. The Ubuntu PPA isn't installable on Debian.

As far as I know, using a recent version of SUMO in the official Python image, which is based on Debian 10, currently requires a lot of extra steps in order to build SUMO. Either a wheel or a maintained mainline package would help a lot!

**Comment by behrisch** [comment]
OK, I see your point. Docker is not an option due to the lack of GUI support?

**Comment by pikeas** [comment]
> OK, I see your point. Docker is not an option due to the lack of GUI support?

Yes, that's correct. I'm trying to generate wheels for my team and it's proving to be a real bear, please let me know if you have any tips!

**Comment by pikeas** [comment]
@behrisch Thank you so much for working on this! Will the wheels include libsumo? I've just spent half a day trying to build install it with no success. The closest I've gotten is a working `make install` into my system Python, with segfaults when used in a virtualenv. :-(

**Comment by behrisch** [comment]
Yes, there are separate wheels for libsumo as well. You can give them a try by downloading the artifacts here: https://github.com/eclipse/sumo/suites/981375619/artifacts/12565646 (You might need to login to github for this link to work).

**Comment by pikeas** [comment]
@behrisch I'll check these out today, thanks! Are OS X wheels available as well? I can build them directly and post my results if there's a script?

**Comment by pikeas** [comment]
Error when attempting a MacOS build:

```
$ python tools/build/setup-sumo.py --cmake-executable cmake -j 2 bdist_wheel
...
[ 99%] Linking CXX shared module ../../../../../bin/liblibsumojni.jnilib
Undefined symbols for architecture x86_64:
  "_libintl_bind_textdomain_codeset", referenced from:
      _PyIntl_bind_textdomain_codeset in libpython3.8.a(_localemodule.o)
  "_libintl_bindtextdomain", referenced from:
      _PyIntl_bindtextdomain in libpython3.8.a(_localemodule.o)
  "_libintl_dcgettext", referenced from:
      _PyIntl_dcgettext in libpython3.8.a(_localemodule.o)
  "_libintl_dgettext", referenced from:
      _PyIntl_dgettext in libpython3.8.a(_localemodule.o)
  "_libintl_gettext", referenced from:
      _PyIntl_gettext in libpython3.8.a(_localemodule.o)
  "_libintl_setlocale", referenced from:
      _PyLocale_setlocale in libpython3.8.a(_localemodule.o)
      _PyLocale_localeconv in libpython3.8.a(_localemodule.o)
  "_libintl_textdomain", referenced from:
      _PyIntl_textdomain in libpython3.8.a(_localemodule.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by pikeas** [comment]
And on Linux, sumo installs successfully, but libsumo isn't installable due to a constraint on traci's version:

```
$ pip install sumo-1.6.0.1343-py2.py3-none-manylinux2014_x86_64.whl
Processing ./sumo-1.6.0.1343-py2.py3-none-manylinux2014_x86_64.whl
Installing collected packages: sumo
Successfully installed sumo-1.6.0.1343
$ pip install libsumo-1.6.0.1343-cp38-cp38-manylinux2014_x86_64.whl
Processing ./libsumo-1.6.0.1343-cp38-cp38-manylinux2014_x86_64.whl
ERROR: Could not find a version that satisfies the requirement traci>=1.6.0.1343 (from libsumo==1.6.0.1343) (from versions: 1.6.0)
ERROR: No matching distribution found for traci>=1.6.0.1343 (from libsumo==1.6.0.1343)
```

**Comment by behrisch** [comment]
> Error when attempting a MacOS build:
> 

Sorry, I can't help with the mac, no device here to test.

**Comment by behrisch** [comment]
For the traci wheels please try to pick the right ones from this list: https://github.com/eclipse/sumo/actions/runs/187652244

**Comment by behrisch** [comment]
what is still missing here:

- [ ] wheels for Windows
- [ ] wheels for MacOS
- [ ] automated pypi upload

**Comment by pikeas** [comment]
The sumolib and traci wheels seem to be working, but I'm not sure how they differ from the 1.6 wheels on Pypi? 

I have libsumo working under Linux with one issue - a failure to resolve the XML file:

```
Error: unable to open file 'https://sumo.dlr.de/xsd/routes_file.xsd'
```

I can `wget` the file directly, so I'm not sure why it's failing. I can work around this by disabling XML validation, what's interesting is that this only seems to happen when using libsumo, and not with traci.

Happy to help with building the MacOS wheels - is there anything I can do to help in terms of providing output/config from failed builds?
