### ISSUE TITLE
warning: Vehicle 'flow_7.6' performs emergency stop at the end of lane 'bot1_0_0 ' because of a red traffic light (decel=-20.94, offset=7.53), time=84.00.

### ISSUE THREAD

**Issue by eugenevinitsky** [eclipse/sumo#4640]
I'm controlling traffic lights in SUMO via a controller but no matter what I do I'm unable to get this error message to stop occuring. Are there some standard tricks to be done to make this work better?

If any of the following details help:
(1) Its a set of inflows travelling N-S and E-W through a single intersection
(2) The lights go from green to red with a 3 second yellow time in between

Thank you!

**Comment by namdre** [comment]
What is the speed of vehicle flow_7.6 in time steps 80 - 84?

**Comment by namdre** [comment]
Has your problem been resolved?
If no further information is given, I will close the ticket.

**Comment by eugenevinitsky** [comment]
Oh, sorry, I missed the first message. I will update with the speed shortly.

**Comment by FarshadKoohifar** [comment]
I assume you are working on Flow project. I am getting the same error. have you found a way around the error?

**Comment by namdre** [comment]
My general advice would be to try with the latest development version

**Comment by palvarezlopez** [comment]
@namdre  it's fixed?
