### ISSUE TITLE
Driving distance does not take into account loops in routes

### ISSUE THREAD

**Issue by m-kro** [eclipse/sumo#4642]
**Precondition:** 
A vehicle travels on a route which contains the same edge twice. For example, it goes around a circle for _n_ times before traveling to other parts of the network.
**Problem:**
The user queries the remaining driving distance of the route through traci.vehicle.getDrivingDistance(). The result only takes into account the position of the vehicle but not how often it has already passed the current edge (=the actual position in the route). For this reason, the driving distance may result longer than it actually is.

**Comment by namdre** [comment]
It would be great if you could add a failing test to sumo/tests/complex/traci/pythonApi/bugs
