### ISSUE TITLE
POLYCONVERT

### ISSUE THREAD

**Issue by shuowang572875852** [eclipse/sumo#4653]
when i use POLYCONVERT, the codes :

F:\software\sumo\xuexiod>F:\software\sumo\bin\polyconvert --net-file jilinuniver
sity.net.xml --type-file jilinuniversity.xml -o jilinuniversity.poly.xml
Success.

although success,but the generated files   jilinuniversity.poly.xml is wrong ,the files code as follow :

```
<additional xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/additional_file.xsd">
   <location netOffset="-685028.00,-4850878.88" convBoundary="0.00,0.00,3933.53,17688.53" origBoundary="125.302426,43.787403,125.350903,43.946731" projParameter="+proj=utm +zone=51 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"/>
</additional>
```

and  the jilinuniversity.xml is the polygon shapes file,as follows :
```
<additionals>
    <poly id="A" color="green" fill="1" layer="0.00" shape="340.57,6824.34 2389.03,6901.24 3032.23,8970.67 -176.79,8816.86 319.60,6831.33 347.56,6838.32"/>
    <poly id="B" color="red" fill="1" layer="0.00" shape="2392.37,6909.86 2951.98,8682.00 2959.67,8682.00 3075.03,9108.82 4813.07,9154.96 4474.69,7009.32 2398.27,6909.35"/>
    <poly id="C" color="red" fill="1" layer="0.00" shape="301.01,6765.41 673.23,6807.71 4454.62,6985.36 4505.38,4709.76 470.20,4726.67 284.09,6756.95"/>
</additionals>

```
and how can i do ?

**Comment by namdre** [comment]
polyconvert is used to import polygons from OSM and other 'raw' input sources. If you already have the polygons in jilinuniversity.xml, then you do not need to use polyconvert.
