### ISSUE TITLE
Crash creating Parking Spaces

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#4667]
Crash is caused because attribute Position isn't mask as composition of X-Y values.

**Comment by namdre** [comment]
@palvarezlopez I assume it's a regression since I recall creating parking spaces with netedit. Did our parkingspace tests catch this?

**Comment by palvarezlopez** [comment]
@namdre yes, it was catch by "parkingSpace/create" test. It was a design error that had not come up until now.
