### ISSUE TITLE
Could not connect to TraCI server 

### ISSUE THREAD

**Issue by wwwyn** [eclipse/sumo#4672]
Hello, I directly run runner.py in traci_tls of the  tutorial, but the following error occurs:

Could not connect to TraCI server at localhost:38687 [Errno 111] Connection refused
 Retrying in 1 seconds
SUMO Version 0.32.0
 Build features: x86_64-unknown-linux-gnu TRACI GDAL
 Copyright (C) 2001-2017 German Aerospace Center (DLR) and others; http://sumo.dlr.de
 License EPLv2: Eclipse Public License Version 2 <https://eclipse.org/legal/epl-v20.html>
 Use --help to get the list of options.
Could not connect to TraCI server at localhost:38687 [Errno 111] Connection refused
 Retrying in 2 seconds
Could not connect to TraCI server at localhost:38687 [Errno 111] Connection refused
 Retrying in 3 seconds
Could not connect to TraCI server at localhost:38687 [Errno 111] Connection refused
 Retrying in 4 seconds

The environment is my lab server with Centos 7 and the sumo I installed is no-gui.
What's the reason? Thanks a lot.

**Comment by namdre** [comment]
The output suggests that sumo was started without a network.
Try something like traci.start['sumo', '-n', 'yournetwork.net.xml'])

**Comment by priyabundela** [comment]
i am also having the same issue , i started sumo with the configuration file
still its not working.
@wwwyn  did you resolve the issue?

**Comment by behrisch** [comment]
Which python version do you use?

**Comment by priyabundela** [comment]
I am using python 2.7

**Comment by santiagoslopez** [comment]
did you resolve the issue?

**Comment by behrisch** [comment]
@santiagoslopez Please have a close look whether there are any error messages indicating that sumo could not start properly and if you cannot find any or still assume a bug, open a new ticket possibly attaching your scenario.
