### ISSUE TITLE
 --duration-log.statistics

### ISSUE THREAD

**Issue by shuowang572875852** [eclipse/sumo#4679]
i want to  get the "Avg.waiting time",and i used the " --duration-log.statistics"in the command line ,the code as follws:

F:\software\sumo\HannoverSuedNetwork-master> test.sumocfg  --duration-log.statistics

and nothing  output ,so what can i do?

**Comment by namdre** [comment]
possibly you have set other options which prevent output.
What are the contents of test.sumocfg?

**Comment by shuowang572875852** [comment]
the contents of test.sumocfg is :

<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/sumoConfiguration.xsd">

    <input>
        <net-file value="suedstadt.net.xml"/>
        <route-files value="test.trips.xml"/>
    </input>

	
</configuration>

**Comment by namdre** [comment]
I notice that there is no 'sumo' in your call.
Try F:\software\sumo\bin\sumo -c test.sumocfg --duration-log.statistics 
(or wherever your sumo is).
The trick with calling only a .sumocfg file does not work anymore when adding extra options.
Alternatively you  can put <duration-log.statistics value="true"/> into the sumocfg file.
