### ISSUE TITLE
cannot connect to traci server

### ISSUE THREAD

**Issue by priyabundela** [eclipse/sumo#4686]
![whatsapp image 2018-10-06 at 12 29 02](https://user-images.githubusercontent.com/44003278/46713719-ba155400-cc75-11e8-8db3-8bfac626a35c.jpeg)
i started my .py file from terminal using python command 
then this error is coming . the sumo-gui opens but after that nothing happens . i put the limit for 60 seconds.

**Comment by namdre** [comment]
When starting sumo-gui there should be message output in the lower part of the window stating 
***Starting sever on part X****
Does the value of X must match the port where your python script is trying to connect?  It's 56279 in your screenshot but this number may differ every time you start the script.

**Comment by priyabundela** [comment]
starting server on port X* is not appearing in the lower part of the window. the sumo-gui window just starts and nothing else appears.
I

**Comment by priyabundela** [comment]
should I start the sumo-gui from command line separately on a port and then run ,py file??

**Comment by namdre** [comment]
If your python script uses traci start (e.g. `traci.start(['sumo-gui', '-c', 'example.sumocfg'])`) then sumo is started automatically with the correct port setting.

**Comment by priyabundela** [comment]
Yes I am doing this only . BT window just starts but it don't starts the
configuration file . Also it keeps trying to connect to traci served

**Comment by priyabundela** [comment]
import os , sys

import environment

tools = os.path.join(os.environ['SUMO_HOME'], 'tools')
sys.path.append(tools)

sumoBinary = "/home/priya/sumo/bin/sumo-gui"
sumoCmd = [sumoBinary, "-c", "/home/priya/sumo/tests/complex/tutorial/q-learning/my_config_file.sumocfg"]
import traci
traci.start(sumoCmd)
environment.test_workflow()
#traci.close()

this is what I am doing

**Comment by namdre** [comment]
what are the contents of my_config_file.sumocfg ?

**Comment by priyabundela** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <input>
        <net-file value="my_net.net.xml"/>
        <route-files value="my_route.rou.xml"/>
        <gui-settings-file value="my_settings.settings.xml"/>
    </input>
    <time>
        <begin value="0"/>
        <end value="10000"/>
    </time>
</configuration>
I don't think there are errors in this file because i am able to run it directly

**Comment by priyabundela** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <input>
        <net-file value="my_net.net.xml"/>
        <route-files value="my_route.rou.xml"/>
        <gui-settings-file value="my_settings.settings.xml"/>
    </input>
    <time>
        <begin value="0"/>
        <end value="10000"/>
    </time>
</configuration>
I don't think there are errors in this file as I am able to run separately from sumo-gui

**Comment by priyabundela** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <input>
        <net-file value="my_net.net.xml"/>
        <route-files value="my_route.rou.xml"/>
        <gui-settings-file value="my_settings.settings.xml"/>
    </input>
    <time>
        <begin value="0"/>
        <end value="10000"/>
    </time>
</configuration>

**Comment by priyabundela** [comment]
[my_config_file.txt](https://github.com/eclipse/sumo/files/2465493/my_config_file.txt)

**Comment by namdre** [comment]
Nevermind, I was thinking there might be a superfluous port option. 
Can you attach a screenshot of sumo-gui after it has been started by your script?

**Comment by namdre** [comment]
@behrisch Do you have any Idea what could prevent the message output 
`            WRITE_MESSAGE("***Starting server on port " + toString(port) + " ***");`
?

**Comment by behrisch** [comment]
Is there any very restrictive firewall running?

**Comment by priyabundela** [comment]
no there is no restrictive firewall running. ya I tried this also . did not work. 
if I am starting sumo on some port with remote port option with the config file . it prints the message . "starting server on port X" .
but i don't know why its unable to connect to traci server.

**Comment by namdre** [comment]
for debugging, run
`sumo-gui -c my_config_file.sumocfg --remote-port 9999`
and in your script replace `traci.start()` with `trac.init(9999)`, then run the script

**Comment by SAG-DAG** [comment]
I am having the same error. Everything was working fine before restarting my PC. But after the restart, I am getting the following error.
 "
Retrying in 1 seconds
Could not connect to TraCI server at localhost:53361 [WinError 10061] No connection could be made because the target machine actively refused it.
"
What should I do??

**Comment by behrisch** [comment]
Did you try to specify a port manually just as mentioned above?

**Comment by muhammadsohaib60** [comment]
> I am having the same error. Everything was working fine before restarting my PC. But after the restart, I am getting the following error.
> "
> Retrying in 1 seconds
> Could not connect to TraCI server at localhost:53361 [WinError 10061] No connection could be made because the target machine actively refused it.
> "
> What should I do??

Hello Do you  have solve this problem

**Comment by muhammadsohaib60** [comment]
I'm still working on this problem how to solve.

**Comment by behrisch** [comment]
There may be a local firewall blocking socket access

**Comment by behrisch** [comment]
But please rather open a new ticket and attach your scenario if possible

**Comment by monasabeti** [comment]
hello, i have a same problem. when i write this code, i get the error that i attach bellow.
because i think i didn't write in a good way that connect traci to osm.cfg i just write traci.init(9999)
how do you think i can solve the problem
![Capture](https://user-images.githubusercontent.com/43193011/144716671-819a4513-1701-4c8a-a522-582ab4dfcdac.PNG)
m

and i have another question. when i connect to sumo, could you please explain for me how can i use the .xml file data in python?

**Comment by muhammadsohaib60** [comment]
Hello

**Comment by monasabeti** [comment]
@muhammadsohaib60 do you have any idea for this problem?

**Comment by muhammadsohaib60** [comment]
Yes.I will send you my code tomorrow.I solved that problem.
Please send me your whatsapp number for further discussion.
My Fyp is based on Sumo simulation.it will be good to discuss problems to
each other

**Comment by behrisch** [comment]
@monasabeti The best way to start up traci is to call traci.start not init. Please try to follow the traci tutorials at https://sumo.dlr.de/docs/Tutorials/index.html#traci_tutorials

**Comment by monasabeti** [comment]
thanks alot for your respond

**Comment by IJdewangan** [comment]
> 

I was facing same problem i pressed go live option in right bottom corner and after that i used pip install traci in powershell. now i am able to simulate.

**Comment by mayaaarahayu1** [comment]
> 

Hi, I'm maya that also working with sumo simulation. Can I discuss this with you? because I'm facing a similar problem.

**Comment by IJdewangan** [comment]
> 

yes please

**Comment by mayaaarahayu1** [comment]
may I ask your email? or you can send me email to mayaprezi3@gmail.com.
thanks

**Comment by SunTianzhHERE** [comment]
hello，I have been facing the same problem after I tried all of your advice. How can I solve it?

**Comment by muhammadsohaib60** [comment]
I will solve this problem

**Comment by muhammadsohaib60** [comment]
Arrange the zoom meeting

**Comment by SunTianzhHERE** [comment]
thank you for your help
Topic：Cannot connect to traci server

https://us05web.zoom.us/j/84233804708?pwd=MBmNjKgtWXP1LXfCGgkKy6K2UlrbEp.1

Meeting number：842 3380 4708
Password：ZpNrr1

**Comment by txf-** [comment]
I should add to this, though possibly this should be added to a FAQ, that this error will also be caused by an incorrect file name.

for example I had a myconfig.sumocfg.xml file  and traci was specifying a myconfig.sumocfg. The result was the error in this very report.

**Comment by muhammadsohaib60** [comment]
yes

**Comment by muhammadsohaib60** [comment]
?
