### ISSUE TITLE
Traas - Simulation.getNetBoundary

### ISSUE THREAD

**Issue by pesvan** [eclipse/sumo#4698]
Hi, 

after migrating my java project to support SUMO 1.0.1 and also included new TraaS jar, I stumbled upon an issue that when I try to call 

`traciConnection.do_job_get(Simulation.getNetBoundary());`

, I am presented with:

> it.polito.appeal.traci.TraCIException$UnexpectedData: Unexpected : expected 5, got 6
>         at de.tudresden.sumo.util.Query.verify(Unknown Source)
>         at de.tudresden.sumo.util.CommandProcessor.do_job_get(Unknown Source)
>         at it.polito.appeal.traci.SumoTraciConnection.do_job_get(Unknown Source)
> ....

I had a look into the TraaS-sources jar, seems like the verify method expects different type constant, but I didn't have time yet to debug this to know more.

So maybe its a bug? Or in the end, I am somehow doing something wrong?
Thanks for any response!

**Comment by behrisch** [comment]
I can confirm that this method was not updated in the traas client
