### ISSUE TITLE
ActivityGen output cannot completely written in xml

### ISSUE THREAD

**Issue by Smiley4ever21** [eclipse/sumo#4704]
ActivityGen cannot write large trips into xml files. For example, I create over 4 million trips in ActivityGen, but it can just write 300 thousand  trips into xml files. The prombelm shows: unhandled exception on 0x00007FF7A7BF9B6E in activitygen.exe: 0xC0000005: Access violation while reading at position 0xFFFFFFFFFFFFFF.

**Comment by namdre** [comment]
did you use the windows 32bit version? If so, try 64bit.

**Comment by Smiley4ever21** [comment]
No, I tried several times in different computers, all 64 bit. And the results are similar, RAM 8G or 16G also has nothing to do with the results.

**Comment by behrisch** [comment]
Which sumo version did you use?

**Comment by Smiley4ever21** [comment]
version 0.31 and version 1.01, separately simulated.

**Comment by behrisch** [comment]
Can you provide your inputs?

**Comment by Smiley4ever21** [comment]
Of course. That is a little big long, Can I send it to your Email?

**Comment by behrisch** [comment]
Yes.

**Comment by Smiley4ever21** [comment]
Your Email address?

**Comment by behrisch** [comment]
oss@behrisch.de

**Comment by Smiley4ever21** [comment]
Email already sent. 

Command: activitygen --net-file jianghan.net.xml --stat-file jianghan.stat.xml --output-file jianghan.trips.rou.xml --random

**Comment by behrisch** [comment]
Is it OK to publish the files?

**Comment by Smiley4ever21** [comment]
OK, if it helps to solve the problem. I'm actually writing a paper about it and needs the results.

**Comment by behrisch** [comment]
I can confirm the crash.

**Comment by Smiley4ever21** [comment]
Thanks a lot for your help;-)

**Comment by behrisch** [comment]
The stat input file is faulty. It does not contain the bus stop locations similar to

	<busStations>
		<busStation id="1" edge="e11t12" pos="10" />
...

**Comment by Smiley4ever21** [comment]
please delete the part of bus stations.

**Comment by Smiley4ever21** [comment]
My computer just finished the simulation without bus stations. No problem now! It's my fault, not programming bug. Thanks a lot for your help!
