### ISSUE TITLE
Is it possible to automaticlly generate a 4 phase signal timing strategy?

### ISSUE THREAD

**Issue by TransUMDxSEU** [eclipse/sumo#4706]
Dear SUMO developer,

I am a researcher doing large scale network simulation using SUMO. And currently I am investigating the effect of traffic light on network fundamental diagram. The automatic signal timing plan may cause the entrace of the network ( especially left turn volume ) getting stuck. I am wondering whether there has been a way to avoid it. 

Thank you

Bests

**Comment by namdre** [comment]
No. This is currently not supported (though it is planned to allow this eventually #4033) The default plan gives opposite directions simultaneous green. To improve tls efficiency you can set the netconvert option
--tls.default-type actuated
This will cause left-turn phases to be prolonged automatically when there is much traffic in this direction.

(closing ticket as duplicate of #4033)

**Comment by namdre** [comment]
@TransUMDxSEU The latest development version allows for the netconvert option` --tls.layout incoming` which causes 4-phase signal plans to be generated.
