### ISSUE TITLE
NETEDIT crashes after joining junctions

### ISSUE THREAD

**Issue by ZoltanBaksa** [eclipse/sumo#4716]
After joining junctions Netedit throws Error: "FXCommandGroup: abort: already working on undo or redo"
Observed in netedit 1.0.1+0176-65b48fbf1c

**Comment by palvarezlopez** [comment]
Hi Zoltan,

Thanks for the Report! do you have an screenshot or a net that produces the error?

**Comment by ZoltanBaksa** [comment]
I cannot attach it to the issue, the upload fails. I send it separately.

**Comment by ZoltanBaksa** [comment]
I have done some tests, and it seems, there is some time limit, when the error occurs. If I wait some seconds (min. 5-6) after junction join, before I do another change, the issue does not occur.

**Comment by ZoltanBaksa** [comment]
If I do recomputing after I load the net to netedit, the issue happens more often, but it also happens without recomputing.
It is sporadic, when it happens.

**Comment by palvarezlopez** [comment]
It was already fixed.
