### ISSUE TITLE
Enhancement to create layers of streets with different heights

### ISSUE THREAD

**Issue by ZoltanBaksa** [eclipse/sumo#4717]
In some situations there are streets, that are crossing each other's path, although in real life there is a bridge over another road, or tunnel under the earth. In case the height information is missing from the OSM data, the converted network is flat. In these cases it is hard to edit the network, because the click event not always correct, selects, or moves wrong network element. With additional layer information, only for netedit purpose, the not needed part could be hidden.

**Comment by namdre** [comment]
This is what you can do already:

1.  convert layer information into z-data using netconvert option --osm.layer-elevation. 
2.  set edge coloring according to z-data.
3. custom coloring allows you to create schemes which hide unwanted layers by making the corresponding z range transparent. 
4. you can quickly switch between pre-defined color schemes in netedit to show different layers

This is what could be done in addition as an enhancement:
- add layer data to the list of imported attributes when setting option --osm.all-attributes
- implement #4276 
- make the unwanted layers transparent as describe above

**Comment by namdre** [comment]
try out importing with --osm.all-attributes and using the new 'color by param' mode.

**Comment by namdre** [comment]
new color mode still missing from NETEDIT, only works in SUMO-GUI so far
