### ISSUE TITLE
Get acceleration of vehicle

### ISSUE THREAD

**Issue by fengbaozhiling111** [eclipse/sumo#4718]
I could not get the acceleration of vehicle because the 
> traci.vehicle.getAcceleration(vehid)

 is error. Moreover, I could not set the acceleration of vehicle.
Dose sumo have this function that get the acceleration of one vehicle?

**Comment by namdre** [comment]
getAcceleration retrieves the momentary acceleration. The function is only available since version 1.0.0.
You can get/set the maximum acceleration of a vehicle using the functions getAccel / setAccel.
The acceleration in the current step can only be set indirectly by calling setSpeed
