### ISSUE TITLE
problem while using NETEDIT

### ISSUE THREAD

**Issue by JaneCheung** [eclipse/sumo#4728]
Hi guys, there is something that confused me and I would like someone familiar with this problem could help me. Appreciated in advance!
While I was using the Netedit to build a simple edge and using the "inspect" function to modify the length  of the edge, the length changed  but  the l X and Y coordinates keep the same. 
While I was running  the simple demo, the running time for cars had no changes between  the original length (62.72 meters)   and  the modified
![modified](https://user-images.githubusercontent.com/39317241/47320455-159cf580-d617-11e8-9329-1c8ca3e46c13.png)
![original](https://user-images.githubusercontent.com/39317241/47320456-159cf580-d617-11e8-995b-aa68575e6be9.png)

 one (620.72 meters).

**Comment by behrisch** [comment]
Please share your route file. Did the vehicle start on the edge in question and did you use a custom departPos?

**Comment by namdre** [comment]
The length of an edge can be set independently of its geometrical length.
If it is set, the cars only care about the user-defined length. However, you will not notice any effect if departPos and arrivalPos are set to fixed values.
