### ISSUE TITLE
Once a parameter set in Netedit, it cannot be reset to default

### ISSUE THREAD

**Issue by ZoltanBaksa** [eclipse/sumo#4730]
When I set the speed parameter of a connection to limit the speed in curving road, I'm not able to set it back to 'default' value to let it be calculated from the start-end edges speed, (-1 in original state).
This happens with visibility, contPos, width by edges, radius by junctions

**Comment by namdre** [comment]
This is a bug. It should be possible to set the value to -1 and let written value be computed.
