### ISSUE TITLE
Netedit crash when loading trafficlights

### ISSUE THREAD

**Issue by leoluecken** [eclipse/sumo#4731]
This occurs if I attempt to load traffic light programs for a larger network into a subnet.
See [expl.zip](https://github.com/eclipse/sumo/files/2510560/expl.zip).

**Comment by palvarezlopez** [comment]
@leoluecken Thanks for the report

**Comment by namdre** [comment]
@leoluecken 
The subnet itself looks invalid. There are no connections and consequently no traffic lights in it.
This may indicate that another bug was triggered while cutting the network from the larger scenario.

Can you reproduce the steps that led to the creation of belair.net.xml?

**Comment by leoluecken** [comment]
No, I redid the subnet extraction (both times in netedit) after noticing the missing connections and it was ok. 

Maybe something went wrong, when I inverted the selection after first selecting the rectangle I wanted to extract the first time... Perhaps my fault, though I can't reproduce it.
