### ISSUE TITLE
how can i get fcd information every time step by traci during ? note: not via "--fcd-output" option

### ISSUE THREAD

**Issue by passengerxuhongli** [eclipse/sumo#4741]
i want to get vehicle's trajectory(x,y,angle,ect.) every control time step in my codes, but i cannot found any api about that, can you help me ? note: output fcd.xml via --fcd-output options is not what i want,because i can read the output file untill sumo runing over

**Comment by namdre** [comment]
traci.vehicle.getPosition
traci.vehicle.getAngle
...
http://sumo.dlr.de/wiki/TraCI
