### ISSUE TITLE
Platoon in SUMO 

### ISSUE THREAD

**Issue by warm2018** [eclipse/sumo#4742]
I want make the vehicles become a platoon when they approach the intersection. Let the vehicles in the platoon stop and departure at the same time.  I think about this problem for a long time ,but have no ways. Anybody can help me to solve this problem?

**Comment by leoluecken** [comment]
Please post usage questions to the sumo user mailing list (http://sumo.dlr.de/wiki/Contact).

Take a look at [simpla](http://sumo.dlr.de/wiki/Simpla) and at speed control via [Traci](http://sumo.dlr.de/wiki/TraCI/Interfacing_TraCI_from_Python).
