### ISSUE TITLE
Netedit closes if error in net file, forced logging not done

### ISSUE THREAD

**Issue by ZoltanBaksa** [eclipse/sumo#4745]
I have created a merged network with netconvert, but it seems to contain some errors, while during loading into netedit, there are warnings and errors in the log window. Unfortunately I cannot read the log because netedit automatically closes. I tried to start netedit from windows command line with the options -s netfile.net.xml -l logfile.txt, but the produced logfile did not contain any bytes. I set the same log file name in the netedit in the processing/options/report page and afterwards opened the network with file/open, but the result was the same.
The issue is not related to the current network. If I open a good network, the log is still not saved.

**Comment by palvarezlopez** [comment]
Hi Zoltan,

Did you used the GIT Version or the 1.0 release?

**Comment by ZoltanBaksa** [comment]
Hi,
I use currently latest development version from download site, v1_0_1+0405-cf78e9505c
I tried it also with an own compiled version from GIT, where I had to switch off PROJ_GDAL to be able to compile and run it.

**Comment by palvarezlopez** [comment]
If you execute Netedit using Visual Studio Debugging, in which part of Code occurs the error?

**Comment by ZoltanBaksa** [comment]
If I load a normal map, which is not having inconsistencies, and use the netedit, the log is not stored at all.
There is no error to analyse, just the log is not stored as I expected, when I set a logfile name.

**Comment by ZoltanBaksa** [comment]
The PROJ_GDAL issue produces this log:
'neteditD.exe' (Win32): Loaded 'D:\sumo\SUMOLibraries\proj_gdal-1911_64\bin\geos.dll'. Module was built without symbols.
Exception thrown at 0x00007FFFD99099A8 (ntdll.dll) in neteditD.exe: 0xC0000139: Entry Point Not Found.
The thread 0x4d04 has exited with code -1073741511 (0xc0000139).
The thread 0x4a98 has exited with code -1073741511 (0xc0000139).
The program '[20256] neteditD.exe' has exited with code -1073741511 (0xc0000139) 'Entry Point Not Found'.

**Comment by ZoltanBaksa** [comment]
If I switch of HAVE_GDAL in config.h, the debugging stops here:
    /// @brief enable drawing of the reference square when testing
    void enableReferenceSquare() {
        myTestingMode.drawRefSquare = true;
    }

**Comment by palvarezlopez** [comment]
if you rebuild the entire Project the error occurs in the same point?

**Comment by ZoltanBaksa** [comment]
yes
I have tried it a few times in the past day.
But again, the main issue now is that the saving of the content of the log window does not happen, even if there is no any error.

**Comment by palvarezlopez** [comment]
@ZoltanBaksa I found the error, and I'm going to fix.

**Comment by palvarezlopez** [comment]
Log works again. If there is an error loading Netedit and log option is saved, Netedit has to be closed for writting log.
