### ISSUE TITLE
How to use --tls.layout incoming?

### ISSUE THREAD

**Issue by TransUMDxSEU** [eclipse/sumo#4752]
Dear Developers,

Sorry to bother you. I acutually have two problems.

(1) I did not find instructions on the webpage about how to generate traffic light (like actuated, and 4 phases, not the default 2 phases ) when constructing the network. Where should I put this sentence in? 

Currently I am constructing the network use Netconvert with node and edge file. I don't know where should I put --tls.layout.incoming or --tls.default-type actuated.

(2) Another issue is that the getAcceleration() in vehicle value retrival seems like it still gonna return vehicle speed, is that right?
(http://sumo.sourceforge.net/pydoc/traci._vehicle.html#VehicleDomain-getAcceleration)

Thank you very much.

**Comment by behrisch** [comment]
(1) You can add these options to the command line, please read sumo.dlr.de/wiki/Basics/Using_the_Command_Line_Applications
(2) This was a documentation bug only. Thanks for pointing it out, I just fixed it. The results will appear tomorrow.
