### ISSUE TITLE
GUI  problem

### ISSUE THREAD

**Issue by JaneCheung** [eclipse/sumo#4753]
Dear all, 
While I was clicking the configuration built by myself, all the files were loaded successfully, however nothing is shown on the GUI. 
Looking forward for your help  !

Best!

Jane
![1](https://user-images.githubusercontent.com/39317241/47969109-60b40100-e038-11e8-82d2-d840e2b008b0.png)

[bug.zip](https://github.com/eclipse/sumo/files/2546229/bug.zip)

**Comment by behrisch** [comment]
There is a typo in your vtype definition. It should read `<param key="has.battery.device" value="true"/>` But nevertheless the GUI should print the error.

**Comment by JaneCheung** [comment]
Michael, thanks for your reply! I have paid some days to deal with this case…
Thanks a lot!
