### ISSUE TITLE
how to understand “ --timeline.day-in-hours”

### ISSUE THREAD

**Issue by JaneCheung** [eclipse/sumo#4760]
Dear all, 
while use the command  of the "-timelane"  like below：
**od2trips>od2trips --timeline.day-in-hours --timeline 1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 -n input_taz.taz.xml -d input_od_o.fma -o trips.trips.xml**

the input files are listed as attachment 
[od2trips.zip](https://github.com/eclipse/sumo/files/2555114/od2trips.zip)
[trips.trips.zip](https://github.com/eclipse/sumo/files/2555119/trips.trips.zip)

only  one trip was generated by using the command 

So how to understand the command 
 **--timeline 1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0** and these numbers in the command

Jane

**Comment by namdre** [comment]
outdated
