### ISSUE TITLE
SUMO-GUI freezes when video snapshot is running

### ISSUE THREAD

**Issue by jekhor** [eclipse/sumo#4774]
If direct video recording has been started in SUMO-GUI, interface doesn't response anymore.
OS: Debian linux unstable
SUMO: 1.0.1 build
ffmpeg: 4.1

**Comment by behrisch** [comment]
How long did you wait, it is sometimes very slow?

**Comment by behrisch** [comment]
Closing for lack of feedback. Please reopen if problems persist.
