### ISSUE TITLE
cannot import libsumo "dynamic module does not define module export function"

### ISSUE THREAD

**Issue by katzdave** [eclipse/sumo#4780]
Traceback (most recent call last):
  File "rl-sumo/rl_sumo/envs/figure8_env.py", line 49, in <module>
    import libsumo as blah
  File "/home/user/sumo-installs/sumo-1.0.1/tools/libsumo/__init__.py", line 15, in <module>
    from .libsumo import *  # noqa
  File "/home/user/sumo-installs/sumo-1.0.1/tools/libsumo/libsumo.py", line 28, in <module>
    _libsumo = swig_import_helper()
  File "/home/user/sumo-installs/sumo-1.0.1/tools/libsumo/libsumo.py", line 24, in swig_import_helper
    _mod = imp.load_module('_libsumo', fp, pathname, description)
  File "/home/user/.local/share/virtualenvs/shoup-q539J3Dj/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/user/.local/share/virtualenvs/shoup-q539J3Dj/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: dynamic module does not define module export function (PyInit__libsumo)

I installed sumo 1.0.1 from source. I also verified that the testlibsumo binary can properly load a binary. Not sure what is going wrong here. I want to use libsumo to eliminate overhead from sockets.

SUMO_HOME is set to /home/user/sumo-installs/sumo-1.0.1

Relevant code:

if 'SUMO_HOME' in os.environ:
    tools = os.path.join(os.environ['SUMO_HOME'], 'tools')
    sys.path.append(tools)
else:
    sys.exit("please declare environment variable 'SUMO_HOME'")

from sumolib import checkBinary  # noqa
import traci
import sumolib
import libsumo as blah

**Comment by behrisch** [comment]
It may be the case that cmake picked up a different python when compiling. Can you check the cmake output whether it mentions a python2 interpreter?

**Comment by katzdave** [comment]
Thanks! Uncommenting https://github.com/eclipse/sumo/blob/master/CMakeLists.txt#L85 let cmake find my python3.6 path, and I can now import libsumo :).

**Comment by manman25** [comment]
I face this problem again
https://github.com/eclipse/sumo/issues/4780#issuecomment-440035284

> It may be the case that cmake picked up a different python when compiling. Can you check the cmake output whether it mentions a python2 interpreter?

**Comment by behrisch** [comment]
This ticket is about importing an already compiled libsumo. You seem to have an error at compilation. Please open a new ticket and share details like sumo version and compiler used
