### ISSUE TITLE
Unable to generate network with multiple geotif files

### ISSUE THREAD

**Issue by yannolecool** [eclipse/sumo#4786]
I try to generate the network with multiple geotif files (.tif) with this [config](https://github.com/eclipse/sumo/files/2577286/netconvert.txt), but the file is never created.
I received this sequence of message in the terminal and it quit without any error:

Removing duplicate edges... done.
Loading configuration... done.
Parsing types from 'C:\Program Files (x86)\Eclipse\Sumo\data\typemap\osmNetconvert.typ.xml'... done.
Parsing from GeoTIFF '.\n34_e075_1arc_v3.tif'...  done (parsed 12967201 features, Boundary: 75.00,34.00,76.00,35.00).
Parsing from GeoTIFF '.\n34_e076_1arc_v3.tif'...  done (parsed 12967201 features, Boundary: 75.00,34.00,77.00,35.00).
Parsing from GeoTIFF '.\n35_e075_1arc_v3.tif'...  done (parsed 12967201 features, Boundary: 75.00,34.00,77.00,36.00).
Parsing nodes from osm-file '.\kashmir.map.osm'...
Found duplicate nodes. Substituting 2462822741 with 2462819529
Found duplicate nodes. Substituting 3929824745 with 3929823023
done.
Parsing edges from osm-file '.\kashmir.map.osm'... done.
Removing duplicate edges... done.

Otherwise, when I use a tool to merged those geotif into a single one and use it instead, it works perfectly.

**Comment by namdre** [comment]
Can you provide example inputs to reproduce this issue?

**Comment by yannolecool** [comment]
Du to the limited size of files that I can join to this message, I will host on my google drive files that you need. There is the link to access those files (zip): https://drive.google.com/file/d/1zalIe9E4CvwssV-lALkBPcDivgrzrbeb/view?usp=sharing

**Comment by namdre** [comment]
Thanks for the sample input. Nobody tried loading multiple geotifs before.
