### ISSUE TITLE
Add GDAL build to SourceForge

### ISSUE THREAD

**Issue by yannolecool** [eclipse/sumo#4787]
I want to know if it could possible to create msi for Windows with GDAL included because I need to recompile the project each time new version is available.

**Comment by namdre** [comment]
you can download our nightly build with GDAL at http://sumo.dlr.de/daily/sumo-msvc12extrax64-git.zip

**Comment by yannolecool** [comment]
Thank you for the daily build, but my real problem is that I want to download the last stable version with GDAL. Is this version if available somewhere?
And I think that a version with GDAL on SourceForge could be a good thing because other person like could use it directly. The msi isn't absolutely necessary, only the zip file like the daily build could be enough.

**Comment by behrisch** [comment]
We already released it for 1.1.0.
