### ISSUE TITLE
add phase property 'name'

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#4788]
to allow for arbitrary user annoted phase descriptions

- [x] load into sumo
- [x] show in gui
- [x] get/set via traci
- [x] preserve when loading/saving network
- [x] edit with netedit
- [x] support in sumolib
- [x] documentation

**Comment by palvarezlopez** [comment]
@namdre "phase " should be treated as a GNEAttributeCarrier?

**Comment by namdre** [comment]
The whole Traffic light should be treated as an attribute carrier eventually but this is a whole other issue. Right now, things can stay as they are and 'name' treated like the other phase attributes.
The netedit changes should come after the netconvert/sumo changes anway.
