### ISSUE TITLE
Lane changing at 0 longitudinal speed

### ISSUE THREAD

**Issue by HolyBugger** [eclipse/sumo#4794]
The vehicles could keep lane changing even when stopping at the end of the roads, which might result from traffic lights turing to red in the junctions. How could i avoid such lane changjing at 0 longitudinal speed and make it more close to reality.
Hope for your reply soon!

**Comment by namdre** [comment]
currently, this can only be achieved when using the sublane model or the simple continuous lane change model by setting vType attribute lcMaxSpeedLatStanding=0
see http://sumo.dlr.de/wiki/Simulation/SublaneModel

related: #4795, #3392

**Comment by HolyBugger** [comment]
So...then how could i resolve sth like "deadlock" when "lcMaxSpeedLatStanding=0", which always happened when the vehicle at the middle lane wanted to turn left or right?
