### ISSUE TITLE
simulation involving E3 detectors does not terminate

### ISSUE THREAD

**Issue by JaneCheung** [eclipse/sumo#4803]
Hi, after I used the **generateTLSE3Detectors.py** to generate the E3 detectors for the network ,
the simulation by adding the E3 could not  terminate and escape the simulation.
Why does it happen ? How could we add the E3 detector and finish our simulation?
the attachment is the **log** file of the simuation.
[log.log](https://github.com/eclipse/sumo/files/2586733/log.log)
![1](https://user-images.githubusercontent.com/39317241/48576688-c9259c80-e8da-11e8-9cf0-09a8553d63ff.png)
![2](https://user-images.githubusercontent.com/39317241/48576689-caef6000-e8da-11e8-9a9e-942473a5d005.png)

**Comment by namdre** [comment]
did you use traci? 
can you provide example input files?

**Comment by JaneCheung** [comment]
Just use the python to generate the **E3 dectector** according to my network configuration and combine it to my **sumcfg** file 
[bug.zip](https://github.com/eclipse/sumo/files/2589916/bug.zip)

**Comment by JaneCheung** [comment]
Hi, Jakob,
If I would like to run the simulation with the E3 installed in the network.
How could I do that?

Best regards!

Jane

**Comment by JaneCheung** [comment]
Jakob, if I would like to use the scenario to do the simulation, how could I avoid the terminate? Decrease the number of views that would be inserted in the network? Or other measures?

**Comment by namdre** [comment]
Download the latest development version where the bug which causes termination is fixed:
http://sumo.dlr.de/wiki/Downloads#Nightly_Snapshots

**Comment by JaneCheung** [comment]
Thank you Jakob,I would try it later!

**Comment by JaneCheung** [comment]
Jakob, I have checked the scenario, the  simulation end  at the  expected
time and all things are right! Thank you so much!
Jane

**Comment by JaneCheung** [comment]
Jakob, I found I run the different scenairo to check the bug!
The simulation* still could not* end at the expected end time!


I have downloaded  the
[image: image.png]
and let the new files replace the old one. Is it right to do that?




Is there something wrong that I did?
[image: image.png]


Best  regards!

Jane

**Comment by namdre** [comment]
sorry. I found another crash. Closing the ticket was premature.

**Comment by namdre** [comment]
I've fixed another issue and your original dataset runs to completion. Please try again with the very latest version.

**Comment by JaneCheung** [comment]
Thank you Jabok,
Happy holiday~

**Comment by JaneCheung** [comment]
![tim 20181124145231](https://user-images.githubusercontent.com/39317241/48972981-58c5fc00-effb-11e8-8ccb-49bd361b2655.png)
![tim 20181124145105](https://user-images.githubusercontent.com/39317241/48972982-58c5fc00-effb-11e8-83bf-45bc10afb323.png)
I have downloaded  the file“sumo-msvc12x64-git. zip”, and replace the old version. In my computer  the simulation still could not get the expected the final termination.

**Comment by namdre** [comment]
when you run 'where sumo' what does it say?
when you run 'sumo' by itself what is the output (I'm interested in the exact version specifier)
It should be something like Eclipse SUMO Version v1_0_1+0793-2e8063c695

**Comment by JaneCheung** [comment]
hi, Jakob,
1) after I run "where is sumo", the output is

*F:\Eclipse\Sumo\bin\sumo.exe*
*INFO: Could not find "is"*


2) after I sun "sumo"

*Eclipse SUMO Version v1_0_1+0616-439afd19a3*
 Build features: Windows-6.3.9600 AMD64 MSVC 18.0.40629.0 Proj GUI
 Copyright (C) 2001-2018 German Aerospace Center (DLR) and others;
http://sumo.dlr.de
<https://mailtrack.io/trace/link/ce6334ee99374fb1cb53929a2d103b39ee280217?url=http%3A%2F%2Fsumo.dlr.de&userId=3378854&signature=6e45a59e82781c66>
 License EPL-2.0: Eclipse Public License Version 2 <
https://eclipse.org/legal/epl-v20.html
<https://mailtrack.io/trace/link/5a723ee7524a15927af4ddf4ed5822b425976647?url=https%3A%2F%2Feclipse.org%2Flegal%2Fepl-v20.html&userId=3378854&signature=9b03f62f51f0352b>
>
 Use --help to get the list of options.


3) maybe the version is not right, which is not fit with the information
you provided
 Eclipse SUMO Version v1_0_1+
*0793-2e8063c695  *

4) I downloaded the file

   - http://sumo.sourceforge.net/daily/sumo-msvc12x64-git.zip
   <https://mailtrack.io/trace/link/fe0bdb5c40e1fa8ac6f81a0d18d5c5b89ba8710c?url=http%3A%2F%2Fsumo.sourceforge.net%2Fdaily%2Fsumo-msvc12x64-git.zip&userId=3378854&signature=f2a0b1d69333de93>
(windows,
   64bit)

[image: image.png]


Do I need to download the other file "

   - http://sumo.dlr.de/daily/sumo-msvc12x64-git.msi
   <https://mailtrack.io/trace/link/c53fe06931b205da77a3f4d438d9d00d21779f34?url=http%3A%2F%2Fsumo.dlr.de%2Fdaily%2Fsumo-msvc12x64-git.msi&userId=3378854&signature=1bfbc6655961dfd9>
(windows
   installer, 64bit)

"

[image: image.png]

unload the original program and  reload it by using the file above?


Best  regards!

Jane

**Comment by JaneCheung** [comment]
Hi, Jakob, I have removed the sumo1.0.1 and reload the last one from the Nightly_Snapshots;
However, there are lot of warnings while I was simulating the scenario, like :
______________________________________________________________________________________
performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=26469.00.
Warning: Vehicle '11687' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=26477.00.
Warning: Vehicle '16176' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=26483.00.
Warning: Vehicle '14224' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=26483.00.
Warning: Vehicle '16279' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=26488.00.
Warning: Vehicle '15866' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=26498.00.
Warning: Vehicle '15068' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=26498.00.
_______________________________________________________________________________________________________
This warning has not been presented while I was using the original version of SUMO, how could I deal with this problem?

Best regards!

**Comment by JaneCheung** [comment]
What‘s more, the emergency brakes of vehicles were not printed in Log.

**Comment by namdre** [comment]
1) The request command was 'where sumo' not 'where is sumo'
2,3) Your version was old and did not include the fix.
4) either the zip or msi version should work if the paths are set correctly

The version with emergency warnings is newer. If you post the output of 'sumo' (the version info) I can tell you if it's the correct one.

The emergency warnings were added last week to report suspicious driving behavior. The driving behavior itself did not change. Some of these warnings may be due to bugs in SUMO and these will be fixed. The warnings could also indicate bad model parameters or bad traffic light configurations. You can disable the warnings using the option --emergencydecel.warning-threshold 1.1

**Comment by JaneCheung** [comment]
Below is the updated output after run the command of
''sumo''
-------------------------------------------
Eclipse SUMO Version v1_0_1+0795-316a7cead1
 Build features: Windows-6.3.9600 AMD64 MSVC 18.0.40629.0 Proj GUI
 Copyright (C) 2001-2018 German Aerospace Center (DLR) and others;
http://sumo.dlr.de
<https://mailtrack.io/trace/link/e4b335378453dd89bdc021fe1d6b011e39af5098?url=http%3A%2F%2Fsumo.dlr.de&userId=3378854&signature=ba68b9b8817f51db>
 License EPL-2.0: Eclipse Public License Version 2 <
https://eclipse.org/legal/epl-v20.html
<https://mailtrack.io/trace/link/2187d2232ad369d5299d2346f3bfc9c617a890ee?url=https%3A%2F%2Feclipse.org%2Flegal%2Fepl-v20.html&userId=3378854&signature=b3825c66ccdfd7ed>
>
 Use --help to get the list of options.


Best regards!

**Comment by namdre** [comment]
This version should be able to run your scenario without crashing.

**Comment by namdre** [comment]
Note, that I've fixed one more crash related to E3 detectors yesterday that is not included in the version you have. This crash only occurs if vehicles leave the simulation without passing e3 exit detectors. Since this does not happen in your scenario, the issue (#4845) does not affect you but it might be relevant for future scenarios.

regards,
Jakob

**Comment by JaneCheung** [comment]
Jskob, thanks for your suggestion

**Comment by JaneCheung** [comment]
Thanks Jakob!
