### ISSUE TITLE
Missing DLLs when building sumo from source

### ISSUE THREAD

**Issue by durraniu** [eclipse/sumo#4816]
Thanks for fixing the code. It rebuilt successfully. However, now when I try to launch sumo-gui in the location `C:\Users\durraniu\source\repos\sumo\bin`, I get the error:  

*The program can't start because LIBBZ2.dll is missing from your computer. Try reinstaling the program to fix this problem.*  

Is this something related to sumo installation? I tried fixing the issue by using various suggested methods on the web but sumo won't open. Please advise.

_Originally posted by @durraniu in https://github.com/eclipse/sumo/issues/4807#issuecomment-440035489_

**Comment by behrisch** [comment]
I leave the ticket open until we get a good method of copying the dlls into the right places with a cmake target. You may already try the install_dll target but it does not copy everything.

**Comment by palvarezlopez** [comment]
@behrisch we can add an extra option in CMake. "Copy .dlls into SUMO bin directory"

**Comment by behrisch** [comment]
I prefer the separate target because the option handling is not easy especially when using the builtin cmake from visual studio 2017.

**Comment by durraniu** [comment]
Hi, I was wondering if there's any update on this issue?

**Comment by behrisch** [comment]
There is now a install_dll target which should do everything related to copying dlls. Please reopen the ticket if problems persist.

**Comment by durraniu** [comment]
Thanks for your reply. I am still getting the same error after cloning and building sumo, although the sumo libraries folder is already in my system path. Here are the steps that I followed:  

1. Clone the sumo and sumo libraries repos in Visual studio 2017
2. Edit the Cmakecache.txt (The path to sumo libraries was already added when I opened this file so I didn't have to edit anything)  
3. CMake > Build all (x64-Release configuration; the build succeeds)
4. Add sumo libraries and sumo/bin folders to the system path  

Am I missing anything?

**Comment by behrisch** [comment]
Did you build the install_dll target?

**Comment by durraniu** [comment]
> 
> 
> Did you build the install_dll target?

Sorry, I am not sure how to do that. I only did: CMake > Build all

**Comment by behrisch** [comment]
You need to find a way to list all your cmake targets (maybe like this https://blogs.msdn.microsoft.com/vcblog/2018/04/09/cmake-support-in-visual-studio-targets-view-single-file-compilation-and-cache-generation-settings/) and then select the install_dll target and build it. The target is probably in a folder called CMake. Your error also suggests that there may be a 32bit version of the library in your path before the 64bit version.
