### ISSUE TITLE
New NETEDIT cursors

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#4818]
- Select element (ctrl, in inspect mode)
- Move (additional, polygon and createEdge #4791)
- ~~Create new Edge (?)~~
- inspect lanes (#4817)
- ~~Zoom with right button (?)~~

**Comment by namdre** [comment]
- I don't think create edge needs a new icon as this is pretty obvious from the chosen mode and no keyboard modifier is used. 
- For zooming, it's pretty obvious and you do not get to see the new cursor unless you actually zoom (stationary right-click opens context menu). Thus a new icon would not give additional information

**Comment by namdre** [comment]
After using it for a bit I think the inspect cursor feels awkward. Since it doesn't have a clear point you never know where to click will go.
I suggest changing it to a classical arrow with a magnifier in the lower right corner (placement like the symbol of the move cursor).

**Comment by angelobanse** [comment]
I agree, it does look a little bit odd.
