### ISSUE TITLE
Obtain GEO Coordinates from sumo simulation using TraCI

### ISSUE THREAD

**Issue by adr-arroyo** [eclipse/sumo#4819]
I am using TraCI library in python to launch and control a sumo simulation from code, step by step. My problem is that I need the coordinates of the vehicles in lat, lon UTM evey step of the simulation. I obtain the x,y coordinates from the simulation every step with a TraCI listener and then I try to convert these values to lat and lon:

    for vehicleId in traci.vehicle.getIDList():
        speed = traci.vehicle.getSpeed(vehicleId)
        x, y = traci.vehicle.getPosition(vehicleId)
        lon, lat = traci.simulation.convertGeo(x, y)
        lon, lat = self.net.convertXY2LonLat(x, y)

None of the two conversions work, first one returns the same values and the second one usually throws an error:

> "RuntimeError: b'projection not named'"

Which I guess is because there is no projection properly described in the network file. Problem here is that NONE of the scenarios work here, even though some of them can do the fcd-output (projected coordinates).

Does any one have encountered a similar problem?

Regards and thank you!

**Comment by namdre** [comment]
Please provide an example network file that allows for correct geo-coordinates in sumo-gui and fcd-output but which fails to return proper results via traci and sumolib.

**Comment by adr-arroyo** [comment]
Here is an example network:
[pasubio_buslanes.net.zip](https://github.com/eclipse/sumo/files/2603193/pasubio_buslanes.net.zip)

**Comment by namdre** [comment]
The example network is not geo-referenced. You can check this from the <location> element at the top of the .net.xml file:
`
    <location netOffset="0.00,0.00" convBoundary="0.00,0.00,1827.72,1339.53" origBoundary="0.00,0.00,1827.72,1364.86" projParameter="!"/>`

the projection parameter is '!' instead of '+proj=utm ...' .
This means any fcd-output you are getting is also provided in terms of x,y (cartesian) network coordinates. Likewise, the lower left-right corner in sumo-gui will not provide correct lat,lon values for such a network.

If you have networks where conversion fails despite valid projParameter, please re-open the ticket.

**Comment by adr-arroyo** [comment]
Hello again,
I am having the same problem but this time I do have a network file with the projection parameter set up correctly. 
I download the scenario from https://github.com/lcodeca/LuSTScenario/archive/v2.0.tar.gz
The file is named "lust.net.xml" (I cannot upload the file/scenario here as it is greater than 10Mb).

I am launching the simulation from traci library as:

`sumo_bin = sumolib.checkBinary(os.environ['SUMO_HOME'] + "/bin/sumo")

args = [sumo_bin, '-c', os.path.join(scenariopath, "dua.actuated.sumocfg"), "--fcd-output.geo", "TRUE"]

traci.start(args)
`

And I obtain the output: 
> Warning: no valid geo projection loaded from network. fcd-output.geo will not work


I actually remember being able to run it with the geo projection, but now I am using last sumo version obtained from https://sourceforge.net/projects/sumo/files/sumo/version%201.1.0/sumo-src-1.1.0.tar.gz and compiled with:
`./configure && make install`

Where does this problem come from?
Thanks for the help!

**Comment by namdre** [comment]
It sounds as if you have built sumo without proj support. 
What is the output when running 
sumo --version
?

**Comment by adr-arroyo** [comment]
Hello, output is:

sumo --version
Eclipse SUMO Version 1.1.0
 Build features: x86_64-pc-linux-gnu GUI
 Copyright (C) 2001-2018 German Aerospace Center (DLR) and others; http://sumo.dlr.de

Eclipse SUMO Version 1.1.0 is part of SUMO.
This program and the accompanying materials
are made available under the terms of the Eclipse Public License v2.0
which accompanies this distribution, and is available at
http://www.eclipse.org/legal/epl-v20.html
SPDX-License-Identifier: EPL-2.0

I did not know that there was an option to build sumo with proj support.

**Comment by namdre** [comment]
The output confirms that the 'proj' library was not part of the build. Please install libproj as explained below and rebuild:  http://sumo.dlr.de/wiki/Installing/Linux_Build_Libraries#Ubuntu_18.04_.28tested_with_SUMO_0.32.0.29

**Comment by lcodeca** [comment]
@adr-arroyo Just for the records, LuST Scenario is meant to be used with SUMO 0.26. If you use it with a different version of SUMO, you cannot consider the resulting mobility validated.

**Comment by adr-arroyo** [comment]
Hello, thanks for the replies. 

@lcodeca What does it mean that we cannot consider the resulting mobility validated? Is that the coordinates of the vehicles will not be properly computed?

ps: @namdre That website is currently down. Are there any other sources of information where I can read about the installation of libproj and necessary libraries?

**Comment by lcodeca** [comment]
LuST Scenario is a realistic mobility scenario of the city of Luxembourg where the traffic demand and the resulting mobility pattern are validated with real data. If you use the scenario with a different version of sumo, you cannot consider it validated anymore; it's just a scenario. 

It depends on what you need from it. Do you want to have vehicles moving in a city, you can use the SUMO version that you want. Are you optimizing something and you want to use a realistic scenario with realistic mobility to prove a point? Then you have to run it with the SUMO version I build it with.

Thanks to this thread, I added this piece of information on the README.md of LuST Scenario.

**Comment by namdre** [comment]
sorry for the broken link. While our wiki is temporarily down, use http://sumo.sourceforge.net/userdoc/Installing/Linux_Build_Libraries.html#Ubuntu_18.04_.28tested_with_SUMO_0.32.0.29

**Comment by adr-arroyo** [comment]
Hello, thanks for the replies. 

@namdre From the instructions, I assume that projection in SUMO is only supported until version 0.32, and version 1.1.0 is not, am I correct?

@lcodeca I guess I need the right and validated version of LuST :) thank you!

**Comment by namdre** [comment]
No, this is a misunderstanding. It's just that the documentation was last updated at that version. The same libraries should work just fine with the latest sumo version.

**Comment by adr-arroyo** [comment]
Ok for the docs, thank you.

I finally successfully compiled SUMO 1.1.0 with projection support :). One remark is that (for ubuntu 18.04) the lib libgdal1-dev is named libgdal-dev, rest of the libraries work fine. 

Additionally, I was able to run MOST and Cologne 0.24 scenarios with fcd-output. I am also working on compiling SUMO for LuST scenario, I will post any important update/problem here.

Thanks for the help so far!

**Comment by AmbercatXu** [comment]
@namdre I encounter the same problem on win10 platform. 
Get the x,y in every simulation step, then use the `convertGeo` function to obtain GEO position, but the GEO position is always wrong.
```
            x, y = traci.vehicle.getPosition(veh_id)
            lon, lat = traci.simulation.convertGeo(x, y)
```
The above mentioned suggusetion is building with proj support and the referece file is also talking about build in linux. But my platform is win10, I don't know if my sumo is also not proj support. What should I do to add the proj support? Or there is another cause?

```
C:\Program Files (x86)\Sumo\bin>sumo --version
Eclipse SUMO Version 1.1.0
 Build features: Windows-6.3.9600 AMD64 MSVC 18.0.40629.0 Proj GUI
 Copyright (C) 2001-2018 German Aerospace Center (DLR) and others; http://sumo.dlr.de

Eclipse SUMO Version 1.1.0 is part of SUMO.
This program and the accompanying materials
are made available under the terms of the Eclipse Public License v2.0
which accompanies this distribution, and is available at
http://www.eclipse.org/legal/epl-v20.html
SPDX-License-Identifier: EPL-2.0
```

Best regards and thank you!

**Comment by namdre** [comment]
Did you build SUMO yourself or are you using the pre-computed binaries?

**Comment by AmbercatXu** [comment]
using the pre-computed binaries: sumo-win64-1.1.0.msi

**Comment by namdre** [comment]
what are the contents of the <location> element in the .net.xml?

**Comment by AmbercatXu** [comment]
My .net.xml file is below:
[TestCaseExp.zip](https://github.com/eclipse/sumo/files/2898736/TestCaseExp.zip)

I create the .net.xml file by NETCOVERT with `test.edg.xml` and `test.nod.xml` in the zip file.
```
C:\Program Files (x86)\Sumo\bin>netconvert.exe -e test.edg.xml -n test.nod.xml -o test.net.xml --proj.plain-geo
Success.
```

**Comment by AmbercatXu** [comment]
I knew the parameter `projParameter` in .net.xml file is not correct, but if I modify it to "+proj=plain-geo" or "proj.plain-geo" or "<2D-POSITION>" or "2D-POSITION", the simulation cannot start. 

If I try `--proj.utm`, it said the x,y in node.xml need to be geographic position.
```
C:\Program Files (x86)\Sumo\bin>netconvert.exe -e test.edg.xml -n test.nod.xml -o test.net.xml --proj.utm
Warning: Invalid longitude 500.00
Error: Unable to project coordinates for node 'node2'.
Quitting (on error).
```
I am confused how to use the NETCONVERT to create a .net.xml file which can be used in simulation to generate GEO position, and the input node.xml file's x,y is based meters.

**Comment by namdre** [comment]
The solution is to add a `<location>` element to the .nod.xml file. For an example, see 
https://github.com/eclipse/sumo/blob/master/tests/netconvert/node_building/combinations_50/rtest10/input_plain.nod.xml

**Comment by AmbercatXu** [comment]
It's ok. I can get the GEO position.
thank you very much.

**Comment by KangChou** [comment]
traci.simulation.convertGeo

**Comment by KangChou** [comment]
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/nodes_file.xsd">

**Comment by KangChou** [comment]
https://www.eclipse.org/lists/sumo-user/msg05106.html

**Comment by ibrahimth** [comment]
Hi, 
I have the same problem where I need to run the code in windows 10  where I use Traci on sumo v1_14_1
         ```
       sumoBinary = 'sumo'
if 'nogui' in sys.argv:
    sumoBinary = 'sumo'
 # change the packet sending frequency at V2I.sumocfg and the step range in this code
sumoProcess = subprocess.Popen([sumoBinary, '-c', sumoConfig, "--remote-port", str(PORT)], stdout= sys.stdout, stderr=sys.stderr)
traci.init(PORT)
for step in range(3500):
    traci.simulationStep()
for Id in traci.vehicle.getIDList():
    x, y = traci.vehicle.getPosition(Id)
    lon, lat = traci.simulation.convertGeo(x, y)

```
However, it only gives me the same output for all vehicles.

**Comment by namdre** [comment]
- are the x,y values distinct?
- does your network have a geo-projection?  -> post the contents of the `<location>` element of your .net.xml file

**Comment by ibrahimth** [comment]
Thank you, I solve it  and no need to update in `.net.xml`. I use list to store the `lon` and  `lat`. It seems that the problem that it print the last results.

```
list=[]
for step in range(3500):
    # warm up sumo simulation
    traci.simulationStep()
    for Id in traci.vehicle.getIDList():
        x, y = traci.vehicle.getPosition(Id)
        lon, lat = traci.simulation.convertGeo(x, y)
        list.append([lon, lat])
```
