### ISSUE TITLE
Does sumo support parallell simulation? 

### ISSUE THREAD

**Issue by ZoeShaw101** [eclipse/sumo#4824]

**Comment by namdre** [comment]
No. The latest release only supports parallel routing (in the simulation and the routing applications). Parallel simulation is being worked on and might be ready for the upcoming release.

**Comment by ZoeShaw101** [comment]
> No. The latest release only supports parallel routing (in the simulation and the routing applications). Parallel simulation is being worked on and might be ready for the upcoming release.

Oh, thanks！And does the branch parallell is working on the parallel simulation ?

**Comment by namdre** [comment]
Yes. Work on parallel simulation is taking place in that branch. If you want to test it and give feedback, feel free.
