### ISSUE TITLE
Invalid behavior of parseStringVector if input contains ";"

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#4825]
if input value is: "%%;$$$ %%$$ type.3", then the generated string vector is: "%%", "$$$" "%%$$" "type.3" instead "%%", "$$$" "%%$$" "type.3"

**Comment by behrisch** [comment]
The wrong and the correct output in your description look the same to me. We would expect it to ignore the ";" and only split at whitespace?

**Comment by palvarezlopez** [comment]
@behrisch yes, it's the idee.
