### ISSUE TITLE
Edge overlaps with itself

### ISSUE THREAD

**Issue by leoluecken** [eclipse/sumo#4830]
If clicking on an edge at a geometry point, netedit registers the same edge twice as two overlapped elements. Refs #2385

Probably that's no problem, but who knows.

**Comment by palvarezlopez** [comment]
@namdre "overlapping elements" should be disabled in "move" mode?

**Comment by namdre** [comment]
the second object in the list comes from glPushName in GNEEdge.cpp:497. However, when removing this line, edges are no longer clickable via their geometry points when drawing lanes with reduced exaggeration.
A better alternative is filtering the duplicate edge from the overlapped result.

**Comment by namdre** [comment]
@palvarezlopez  I think the duplicate is introduced in swapLanesToEdge and should be filtered out in this function. However, there is some code which I don't understand and which I would like to discuss before changing anything.
