### ISSUE TITLE
support editing walkingarea shapes

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#4836]
difficult insofar walkingareas are mostly implicit right now. (except for http://sumo.dlr.de/wiki/Networks/PlainXML#Walking_Areas)

**Comment by namdre** [comment]
They could be drawn in crossing mode as special polygons for the active junction.
Or they could always be drawn like crossings as part of the junctions drawgl call (kept outside the rtree).
Since the custom shape is kept in NBNode::myWalkingAreaCustomShapes, and there are no further attributes, I think a new attribute carrier can be avoided.

**Comment by palvarezlopez** [comment]
It's being implemented here: #11623
