### ISSUE TITLE
crash when trying to take pdf screenshot

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#4838]

**Comment by palvarezlopez** [comment]
@namdre in Windows or Linux? (or both?)

**Comment by namdre** [comment]
only in windows. Caused by incompatible build of gl2ps.dll. 
@behrisch The version on our build server needs to be recompieled
@palvarezlopez SUMOLibrarries should include different versions for  for MSVC17 and 13

**Comment by behrisch** [comment]
fixed now
