### ISSUE TITLE
shift-single-click in selection mode should select lanes

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#4846]
for consistency with inspect and delete mode (#4817).

Care must be taken to keep rectangle selection behavior unaffected.

**Comment by palvarezlopez** [comment]
@namdre And if we want to select a set of lanes using shitf? Can we use Control + Click to create the rectangle selection?

**Comment by namdre** [comment]
No. In this case we would simply uncheck the 'select edges' checkbox as before.
I would reserve the ctrl-modfier for future use in this mode.
