### ISSUE TITLE
If I want the adjacent vehicles to accelerate at the same time  like a platoon in TraCI, which command should I use?

### ISSUE THREAD

**Issue by warm2018** [eclipse/sumo#4849]

**Comment by namdre** [comment]
either with repeated setSpeed commands for all involved vehicles or with a speed time line (command slowDown also allows accelertion). Alternatively, consider http://sumo.dlr.de/wiki/Simpla

**Comment by warm2018** [comment]
what's "speed time line "?  A command?

**Comment by namdre** [comment]
command slowDow: http://sumo.dlr.de/wiki/TraCI/Change_Vehicle_State
