### ISSUE TITLE
Query about the new version and request for old version.

### ISSUE THREAD

**Issue by TransUMD** [eclipse/sumo#4862]
Dear developers,

Previously I was doing research with the old version of SUMO in April.

However, with the same demand, driving behavior data, the simulation result is totally different from the previously simulated result. I am wondering is that because of some changes of the version update for SUMO?

Also, I am wondering whether can I have an old version installation of SUMO (guess it should be 0.3x) since I need to re-simulation my research result.

Thank you very much for your help and I really appreciate it.

Best.

**Comment by TransUMD** [comment]
I have successfully installed the old version and reproduce my scenario. Just wondering what makes it so different between the two version... I was simulating a freeway segment with Krauss model.

**Comment by namdre** [comment]
Hello, with the release of version 1.0.0 several default parameters were changed. The most notable one is the default speed deviation which was changed from 0 to 0.1 to increase the realism for motorway traffic at default settings. In older versions, vehicles of the same vType would all drive at the same speed and never overtake each other.  All changes are listed at http://sumo.dlr.de/wiki/ChangeLog

If you do not specify speedDev in your inputs, this is the most likely reason.  Otherwise, can you describe how the behavior differs from your expectations?

**Comment by TransUMD** [comment]
Thank you forthe prompt reply. I think it might be the reason you said. 

The behavior differs a lot. I did not specify the speed deviation in the default Krauss car-following model.

<vType id="CarA" length="5" maxSpeed="35" carFollowModel="Krauss" accel="2.6" decel="4.5" minGap="2" tau="2" sigma="0.5" color="white" speedFactor="1"/>

With the same amount of traffic demand, the scenario in previous version of SUMO may cause severe congestion in the weaving section, while in the new version there's no congestion and backward queue to upstream.

Just wondering what makes it so different. But my problem now is solved by using the old version 0.32.0 for now. Thank you very much.

**Comment by TransUMD** [comment]
<vType id="CarA" length="5" maxSpeed="35" carFollowModel="Krauss" accel="2.6" decel="4.5" minGap="2" tau="2" sigma="0.5" color="white" speedFactor="1" lcStrategic="100" lcSpeedGain="100" lcLookaheadLeft="200" lcCooperative="0.8"  lcAssertive="5" lcPushy="1"/>

Krauss Model defined by me

**Comment by TransUMD** [comment]
id="CarA" length="5" maxSpeed="35" carFollowModel="Krauss" accel="2.6" decel="4.5" minGap="2" tau="2" sigma="0.5" color="white" speedFactor="1" lcStrategic="100" lcSpeedGain="100" lcLookaheadLeft="200" lcCooperative="0.8"  lcAssertive="5" lcPushy="1"

Krauss model defined by me for testing

**Comment by namdre** [comment]
The most important change related to your parameters is the fact that lcAssertive had no effect on the default lane changing model until version 1.0.0 (before that, it only affected the sublane-lane-changing mode, as per documentation). A value of 5 greatly increases gap acceptance and thus aids in weaving.

The different speed deviation probably leads to a better distribution of vehicles among the lanes and also causes a distribution of gaps in the traffic stream that would aid in weaving.

Furthermore, version 1.0.1 contains two bug fixes related to lane changing. These might also improve traffic performance at the weaving section.
