### ISSUE TITLE
Error in Demand/Dynamic User Assignment

### ISSUE THREAD

**Issue by Smiley4ever21** [eclipse/sumo#4866]
Hallo,

I face  a problem wenn using python duaIterate.py.
The error comes in dua.log as: Error: The edge '-404679829#1.321' within the route for trip 'randUni17118:1' is not known.
The edge is the starting edge of the trip in trip file(XXX.trips.rou.xml).

Then I checked the edge in netedit.exe, but the edge was perfect, with entry road(edge) and exit road(edge). 

Could I ask why this error happens and what can I do about it?
It is OK if you need my input files.

Thanks for your reply.
Best Regards,
Smiley

**Comment by behrisch** [comment]
Please double check that you are using the same network in netedit and when calling duaIterate. If this is really the case can you send / attach your inputs for inspection?

**Comment by Smiley4ever21** [comment]
Thanks a lot for your reply.

It is the same net file. Yesterday I change each unnecessary node into
geometry node and it stop showing the error.
The file I use now can not crate route file, I already started for over two
hours and not even one route file is generated.

my command:  python duaIterate.py -n jianghan.net.xml -t
jianghan.trips.rou.xml -l 10

Thank you again.

Files:(to big so I put the link)
https://drive.google.com/open?id=1lPZTuelBCGh4lXPFTNXC2B6V1oC6I0L4
https://drive.google.com/open?id=10GbjoLrCQeRyr9GJEUuWtyekLrRQkHss

Michael Behrisch <notifications@github.com> 于2018年12月6日周四 上午11:31写道：

**Comment by behrisch** [comment]
Closing since there is no further input. If problems persist please reopen with more specific data.
