### ISSUE TITLE
density in meandata for edges has wrong upper bound

### ISSUE THREAD

**Issue by khuebner** [eclipse/sumo#4904]
If I have an edge with 2+ lanes, and traffic congestion on this edge, the calculation of the density in the meandata for edges is wrong (`<edgeData .../>`). Actually, it outputs a wrong upper bound.

If the length of the vehicles is 5m, the maximum density given in the meandata is 200 (1000m/5m). This upper bound is, however, only valid for one single lane. If there's more than one lane, the maximum bound should increase lineary (e.g. 600 veh/km for an edge with 3 lanes).

**Comment by namdre** [comment]
was broken in a8068549bb872dd3ba9a2b00de0f4f62fa5594f5 refs #3265. 
Thank you for reporting!

**Comment by namdre** [comment]
Maybe not really a regression since the value was far to high before the commit which introduced an invalid upper bound.
