### ISSUE TITLE
Crash in function "straighten edge"

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#4905]

**Comment by namdre** [comment]
supposedly this is related to #4906 and #4901. Was this caused by a recent commit or did you find a new corner case that was always there?

**Comment by palvarezlopez** [comment]
@namdre  probably a recent commit. I'm now testing the contextual menu options, and I found it.

**Comment by palvarezlopez** [comment]
@namdre Update: It's an inconsistency in RTREE.

**Comment by namdre** [comment]
@palvarezlopez  So it only crash in testing?

**Comment by palvarezlopez** [comment]
@namdre yes, specifically in edges that owns a POILane.
