### ISSUE TITLE
Invalid movement of edges with from/to junction selected

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#4918]

**Comment by palvarezlopez** [comment]
![unnamed](https://user-images.githubusercontent.com/8238561/50149372-53d33000-02bb-11e9-8c62-0d1d6f79b420.png)

**Comment by namdre** [comment]
This is too much! Please find a less invasive solution to the crash. 
As a minimum it must be possible to select two edges that are the reverse of each other (connecting the same nodes in opposite directions) and to create matching geometry points via move mode.
Breaking this core functionality is worse than a rare crash.

**Comment by palvarezlopez** [comment]
@namdre I'm working in the solution now
