### ISSUE TITLE
Unittest for StringUtils::toDouble("1,1") fails

### ISSUE THREAD

**Issue by schwamborn** [eclipse/sumo#4922]
Unittest for StringUtils fails for the following cases:
```StringUtils::toDouble("1,1")```
```StringUtils::toDouble(",1")```
Double values ```1.1``` and ```.1```, respectively, should not be the expected results.

```bin/testcommon``` output:
```
[ RUN      ] StringUtils.test_toDouble
unknown file: Failure
C++ exception with description "Invalid Number Format '(double) 1,1'" thrown in the test body.
[  FAILED  ] StringUtils.test_toDouble (0 ms)
```

Corresponding code:
https://github.com/eclipse/sumo/blob/6c764d9a5962af9e0675d19db5e2860aa618a132/unittest/src/utils/common/StringUtilsTest.cpp#L143-L144

**Comment by behrisch** [comment]
This was an attempt to make this work on de and en locales but maybe we should add something to set locales explicitly if needed.

**Comment by behrisch** [comment]
Furthermore we should run the unit tests as part of texttest to catch these things earlier.

**Comment by behrisch** [comment]
Just for the records: we could use setlocale if anyone really wants to dive into it.
