### ISSUE TITLE
netedit cannot load <inductionLoop>

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#4923]
synonym for e1Detector

**Comment by palvarezlopez** [comment]
@namdre E2 have the same problem

**Comment by namdre** [comment]
@palvarezlopez supposedly E3 as well (synonym is entryExitDetector)

**Comment by palvarezlopez** [comment]
@namdre yes, it's right.

I have a question: If for example an E1 is loaded with tag "Induction loop", it has to be saved with the same tag, or can be changed with "E1detector"?
