### ISSUE TITLE
is there an example.via.xml about ranomtrips.py?

### ISSUE THREAD

**Issue by taowang7** [eclipse/sumo#4926]
we use an via.xml like this:
```
<edgedata>
<interval begin="0" end="60">
<edge id="85106752" value="0.3"/>
<edge id="85106755" value="0.3"/>
</interval>
<interval begin="60" end="100">
<edge id="85106752" value="0.5"/>
<edge id="85106755" value="0.8"/>
</interval>
</edgedata>
```
and a python command to call randomtrips.py like this:
python ..\tools\randomTrips.py -n E:\sumo_test\sumo_20181123\net\net.net.xml --weights-prefix E:\sumo_test\sumo_20181123\test_link  -p 0.5 -e 100 -o E:\sumo_test\trip_test.xml --route-file E:\sumo_test\trip_route.xml

without success that we can't find edges of via.xml in the output route file
that will be very kind of you giving some exampls or suggestions

**Comment by namdre** [comment]
via-edges are only used along with option --intermediate (to specify the number of intermediate edges to use).

**Comment by taowang7** [comment]
thanks

**Comment by taowang7** [comment]
We now use a realworld road condition data to control the —weights-prefix in randomTrips.py . an edge's road condition is 3 (means congestion) then it get a weights of 0.7 for example. Then we use the routes produced by randomTrips.py to simulating real incidents.   However. we do not know if it makes sense cause when we compare the edge speed in  outputdata with real world data , it doesn't match .  Be grateful to  any suggestions .

**Comment by namdre** [comment]
The weights in randomTrips.py only controll the likelyhood of departing/arriving. The via-weights along with option --intermediate are meant to create convoluted routes which travel back and forth across the  network so they are unsuitable for controlling path-finding for simple origin-destination routes.

I recommend that you create your routes in two steps: 
1) generate random trips
2) process the trips with duarouter and use the option --weight-files to include road condition data. You can even model time-varying congestion data this way.

**Comment by taowang7** [comment]
we faild with trying file like this:
the command is
\bin\duarouter.exe -n E:\sumo_test\sumo_20181123\net\net.net.xml -t E:\sumo
_test\trip_test.xml --weight-files E:\sumo_test\sumo_20181123\link_via\hefei_sumo_20181122_2hour_7_9.xml -o E:\sumo_test
\sumo_20181123\rou_xml\route_1122_7_9_useweights_map_repair.rou.xml -s 7200

weight-files like this:
<edgedata>
<interval begin="0" end="60">
<edge id="85189366" value="0.3"/>
<edge id="85106395" value="0.3"/>
<edge id="145208" value="0.3"/>
<edge id="172791" value="0.3"/>
<edge id="172792" value="0.3"/>
</interval>
<interval begin="60" end="120">
<edge id="85189366" value="0.4"/>
<edge id="85106395" value="0.6"/>
<edge id="145208" value="0.8"/>
<edge id="172791" value="0.3"/>
<edge id="172792" value="0.3"/>
</interval>
.......
......
<interval begin="7140" end="7200">
<edge id="85189366" value="0.3"/>
<edge id="85106395" value="0.7"/>
<edge id="145208" value="0.3"/>
<edge id="172791" value="0.7"/>
<edge id="172792" value="0.7"/>
</interval>
</edgedata>

**Comment by namdre** [comment]
by default, duarouter uses the attribute 'travelTime' which does not exist in your file. To use your current file, set the option --weigh-attribute value

**Comment by taowang7** [comment]
### **trip_test.xml like this:**
<trip id="0" depart="0.00" from="87598793" to="95118996"/>
    <trip id="1" depart="0.50" from="72293294" to="20456041"/>
    <trip id="2" depart="1.00" from="39272961" to="84992"/>
    <trip id="3" depart="1.50" from="54948865" to="42359143"/>
    <trip id="4" depart="2.00" from="31759721" to="87753161"/>

**Here's how I use it:**
 ..\bin\duarouter.exe -n E:\sumo_test\sumo_20181123\net\net.net.xml -t E:\sumo
_test\trip_test.xml --weight-attribute traveltime --weight-files E:\sumo_test\sumo_20181123\link_via\hefei_sumo_20181122
_2hour_7_9.xml -o E:\sumo_test\sumo_20181123\rou_xml\route_1122_7_9_useweights_map_repair.rou.xml -s 7200

But they don't seem to help.There are too few instructions on the website.Can you give me a simple example.

**Comment by taowang7** [comment]
trip_test.xml like this ：
<trip id="0" depart="0.00" from="87598793" to="95118996"/>
    <trip id="1" depart="0.50" from="72293294" to="20456041"/>
    <trip id="2" depart="1.00" from="39272961" to="84992"/>
    <trip id="3" depart="1.50" from="54948865" to="42359143"/>
    <trip id="4" depart="2.00" from="31759721" to="87753161"/>

**Comment by taowang7** [comment]
trip_test.xml like this:
<trip id="0" depart="0.00" from="87598793" to="95118996"/>
 <trip id="1" depart="0.50" from="72293294" to="20456041"/>

**Comment by taowang7** [comment]
<trip id="0" depart="0.00" from="87598793" to="95118996"/>
    <trip id="1" depart="0.50" from="72293294" to="20456041"/>
    <trip id="2" depart="1.00" from="39272961" to="84992"/>
    <trip id="3" depart="1.50" from="54948865" to="42359143"/>
    <trip id="4" depart="2.00" from="31759721" to="87753161"/>

**Comment by taowang7** [comment]
<trip id="0" depart="0.00" from="87598793" to="95118996"/>
    <trip id="1" depart="0.50" from="72293294" to="20456041"/>
    <trip id="2" depart="1.00" from="39272961" to="84992"/>
    <trip id="3" depart="1.50" from="54948865" to="42359143"/>
    <trip id="4" depart="2.00" from="31759721" to="87753161"/>

**Comment by taowang7** [comment]
<trip id="0" depart="0.00" from="87598793" to="95118996"/>

**Comment by taowang7** [comment]
I used the following command:
..\bin\duarouter.exe -n E:\sumo_test\sumo_20181123\net\net.net.xml --route-files E:\sumo_test\trip_test.xml  --weight-attribute value --weight-files E:\sumo_test\sumo_20181123\link_via\hefei_sumo_20181122_2hour_7_9.xml  -o E:\sumo_test\sumo_20181123\rou_xml\route_1122_7_9_useweights_map_repair.rou.xml -s 7200
 I get the following error message:
Error: Unknown measure (weight attribute 'value')!
Quitting (on error).

**Comment by namdre** [comment]
Are you still using the file from above
```
<edgedata>
<interval begin="0" end="60">
<edge id="85189366" value="0.3"/>
...
```
or are you using a different type of file now?

**Comment by taowang7** [comment]
still using the file from above

**Comment by namdre** [comment]
my mistake. Duarouter is inflexible and only supports attribute names which are part of SUMOs edgeData-output (http://sumo.dlr.de/wiki/Simulation/Output/Lane-_or_Edge-based_Traffic_Measures).

You will have to regenerate your weight files to use attribute traveltime.
Using your previous probability 'value' this should be something like 
edgeLength * speedLimit * value

**Comment by taowang7** [comment]
you mean edgeData-output attributes here?  

traveltime="<MEAN_TRAVEL_TIME>" \
            density="<MEAN_DENSITY>" occupancy="<MEAN_OCCUPANCY>" \
            waitingTime="<TOTAL_WAITING_TIME>" speed="<MEAN_SPEED>" \
            departed="<EMITTED_VEH_NUMBER>" arrived="<ARRIVED_VEH_NUMBER>" \
            entered="<ENTERED_VEH_NUMBER>" left="<LEFT_VEH_NUMBER>" \

not all attributes works.    We tried "traveltime" and it successed. However "density" and "speed" threw the same error as "values"

**Comment by namdre** [comment]
Sorry, my above remark was imprecise again. Duarouter only supports traveltime and emission measures from 
http://sumo.dlr.de/wiki/Simulation/Output/Lane-_or_Edge-based_Emissions_Measures#Generated_Output
http://sumo.dlr.de/wiki/Simulation/Output/Lane-_or_Edge-based_Noise_Measures#Generated_Output

The data must be something that suitable for minimization (less traveltime and less emissions are better). Minimizing 'speed' makes little sense.
Usage of 'density' could actually be useful but the list of allowed attributes is hard-coded at the moment and density is not included.

**Comment by taowang7** [comment]
we've worked on it for 3days and get better results under the help of you, Thanks a Ton！
