### ISSUE TITLE
Lefthand drive - Vehicle has right of way at intersection but stops!

### ISSUE THREAD

**Issue by arashkav** [eclipse/sumo#4938]
I converted a network to a lefthand drive one with netconverter. All the connections at the intersection were rebuilt and seem to be fine. However, vehicle stops where it has right of way. Please see below:

![image](https://user-images.githubusercontent.com/6721433/50128415-ffcf4800-02c8-11e9-80ab-7ce885999419.png)
Below is the connections rights:
![image](https://user-images.githubusercontent.com/6721433/50128439-0eb5fa80-02c9-11e9-9e59-cb6bc1452eb1.png)

**Comment by namdre** [comment]
please attach the scenario input files (network, routes, .sumocfg)

**Comment by namdre** [comment]
The issues is due to #4256
Please load and save the network with today's release of netedit 1.1.0
