### ISSUE TITLE
source release does not allow building from source

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#4946]
- missing files (FileHelpersTest.cpp)
- version.py runs and assumes existing git repository

**Comment by behrisch** [comment]
Seems to occur only with the "all" download which I did  not adapt after the last minute cmake fix.

**Comment by behrisch** [comment]
src release is broken as well if you do not have git, because we have a config.h in src which does not have version info. I will monkey patch the release.

**Comment by behrisch** [comment]
New files uploaded. Please reopen if problems persist.

**Comment by behrisch** [comment]
../../tools/build/setup-libsumo.py:SUMO_VERSION = version.gitDescribe()[1:-11].replace("_", ".").replace("+", ".")
../../tools/build/setup-sumolib.py:SUMO_VERSION = version.gitDescribe()[1:-11].replace("_", ".").replace("+", ".")
../../tools/build/setup-traci.py:SUMO_VERSION = version.gitDescribe()[1:-11].replace("_", ".").replace("+", ".")

The setup scripts calls directly version.gitDescribe(), which does not work from an unpacked tar-file.

**Comment by behrisch** [comment]
We probably need to patch the version into those files in the release process or parse it from the CMakeLists.txt as a fallback when we do not have git.
