### ISSUE TITLE
edge geometry with varying incline not drawn correctly

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#4952]
somehow the tesselation does not work whenever the inclination changes along the geometry.

**Comment by m-kro** [comment]
Do you have an example network?

**Comment by namdre** [comment]
in the attached network, junction 477605634 flickers when setting a color scheme that gives different colors to junctions and edges and then tilting the view.
[net2.net.xml.zip](https://github.com/eclipse/sumo/files/8859269/net2.net.xml.zip)

**Comment by m-kro** [comment]
Although the attached network uses Z coordinates, the junctions and edges nearby junction 477605634 are at the same height. Shapes of junctions 477605634 and 63288809 and edge 335802685 overlap with each other as they are in the same plane. So it does not have to do with inclination. As mentioned in ref #10773 , overlapping shapes are a problem for 3D view.
Options:
- do more small Z offsets (does only work between shapes of different object types, not with two junctions)
- implement kind of boolean operations for shapes to cut off overlapping pieces (cut where?)

**Comment by namdre** [comment]
looking at this network some more I find the problem to be caused by invalid junction geometry (normally, edges and junctions should not overlap).

**Comment by namdre** [comment]
This network shows artifacts on my end:

[net3.net.xml.zip](https://github.com/eclipse/sumo/files/8860678/net3.net.xml.zip)
![Screenshot from 2022-06-08 12-24-39](https://user-images.githubusercontent.com/6240630/172594177-94a603be-01e1-4ed6-ae41-1fbbc0cd228e.png)

**Comment by m-kro** [comment]
OK looking at the code it becomes obvious: Currently in 3D view the whole lane shape is drawn as one big Polygon. This means that we have to break it into pieces, either at every intermediate geometry point or only if Z changes.

**Comment by namdre** [comment]
If I add more intermediate geometry points, the rendering looks ok again. Thus, rendering non-flat polygons seems to work in principle.

**Comment by m-kro** [comment]
I would assume it looks OK by chance. I have created simple example with one intermediate geometry point which does not render at all:

![grafik](https://user-images.githubusercontent.com/33294728/172608567-a2f0c263-93d1-4cd4-96ff-c3f3a1d9c90c.png)

**Comment by namdre** [comment]
Looks fine now.
