### ISSUE TITLE
routers only consider internal lane cost when reaching the next edge

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#4953]
The cost of the next edge is only added when reaching it by design (to avoid expensive cost calculations)
The current behavior for internal edges cause sub-optimal routes to be found. 
Instead, internal costs should be added before putting the sucessor into the queue.

Supposedly, efficiency is less of a concern with internal edges because expensive cost-timelines are rarely used for them.

**Comment by behrisch** [comment]
should be fixed now together with the last A* fixes
