### ISSUE TITLE
GUI settings: tls index is not drawn for crossings

### ISSUE THREAD

**Issue by m-kro** [eclipse/sumo#4960]
Regression between v.1.1.0 and v1.0.1:
When set through the GUI settings (Junction > show link tls index), the tls index is only drawn on normal lanes, not for crossings.

![grafik](https://user-images.githubusercontent.com/33294728/50282623-a9424500-0453-11e9-9ab3-53794d1fc125.png)

**Comment by namdre** [comment]
Thanks for reporting!
