### ISSUE TITLE
gently handle superfluous space in xml list input

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#4961]
what about things like 
```
  edges="a b "
  edges=" c "
  edges="d   e"
```
Currently this results in multiple strings with length=0 as part of the parsed vector due to the **true** in 
                                                                                                                                                            
```
SUMOSAXAttributes::parseStringVector(const std::string& def, std::vector<std::string>& into) {                                                                    
     StringTokenizer st(def, " ", true);    
```

This type of error is rather difficult to diagnose by the end user (e.g. #4956) and it may be more user-friendly to simply ignore superfluous spaces.

**Comment by behrisch** [comment]
I would also go for user friendliness here and allow arbitrary whitespace.

**Comment by behrisch** [comment]
One thing remains which is how to handle edges=" ". Currently this returns an empty vector while edges="" throws EmptyData.

**Comment by namdre** [comment]
I think it would be better if "  " would also throw EmptyData whenever a list is required.
