### ISSUE TITLE
when i open url from sumo-document,it can't download a  example.

### ISSUE THREAD

**Issue by poppingcode** [eclipse/sumo#4980]
the url is ：http://sumo.sourceforge.net/userdoc/Data/Traffic_Data.html
i want download the Usage examples,but the relevant documents doesn't find.
Can you help me provide it?
thanks

**Comment by namdre** [comment]
the download link http://prdownloads.sourceforge.net/sumo/fsp_speed_and_lengths.tar?download should be working

**Comment by behrisch** [comment]
works here as well

**Comment by poppingcode** [comment]
> the download link http://prdownloads.sourceforge.net/sumo/fsp_speed_and_lengths.tar?download should be working

i can download the data， but can't  know how to use data . you can try to click the  bottom of web .
"An Example of Microscopic Car Models Validation using the open source Traffic Simulation SUMO"; 
it link to ：http://sumo.sourceforge.net/docs/dkrajzew_ESS2002_LOG14_Validation.pdf  
this url can't open

**Comment by poppingcode** [comment]
> the download link http://prdownloads.sourceforge.net/sumo/fsp_speed_and_lengths.tar?download should be working

thanks for you reply

**Comment by behrisch** [comment]
http://sumo.dlr.de/pdf/dkrajzew_ESS2002_LOG14_Validation.pdf

**Comment by poppingcode** [comment]
> http://sumo.dlr.de/pdf/dkrajzew_ESS2002_LOG14_Validation.pdf

ok ， 
thanks，

**Comment by behrisch** [comment]
Link in the wiki is fixed as well.
