### ISSUE TITLE
Ubuntu 18.04 latest using PPA is 0.32 not 1.1.0

### ISSUE THREAD

**Issue by arsenious** [eclipse/sumo#4981]
Hi all

I followed the installation instructions for Ubuntu and was able to install the 0.32 version of SUMO which is a year old. I didn't notice it until I was trying out the TraCI tutorial on the wiki, when I got the following error:

Error: tcpip::Storage::readIsSafe: want to read 4 bytes from Storage, but only 3 remaining

This is likely due to a mismatch between the TraCI version (which I downloaded from latest stable GitHub source along with the tutorial) and SUMO version (installed using apt-get).

The latest version here for Ubuntu 18.04 is 

sumo | 0.32.0+dfsg1+9+22~ubuntu18.04.1 | Anton Gladky (2017-12-24)
-- | -- | --
at
https://launchpad.net/~sumo/+archive/ubuntu/stable

0.32 is over a year old now. Should I continue using it and use an older version of TraCI? I would prefer to use the latest stable release but am having some trouble building from source (not very experienced)
How can I get the latest stable release's binaries for Ubuntu 18.04 LTS? 

Please help
Thanks

**Comment by behrisch** [comment]
It always takes some time before the ubuntu ppa is up to date. So if it is urgent, please try building from source and post your questions here or contact the maintainer.

**Comment by arsenious** [comment]
> It always takes some time before the ubuntu ppa is up to date. So if it is urgent, please try building from source and post your questions here or contact the maintainer.

Thanks for your reply

0.32 came out a year ago, so I think it should have been updated by now. Is there any other way I could install on Ubuntu without building from sources? 

Could it be possible for the SUMO devs to share Ubuntu binaries on the Downloads page, just like the latest Windows binaries? I could use dpkg and install using that.
Thanks

**Comment by behrisch** [comment]
No we won't add another repository. I will have a look at the ppa next year ;-).

**Comment by arsenious** [comment]
I apologize but I don't understand. All I was asking was if it would be possible to get an rpm or deb file for latest SUMO release, rather than using the PPA. Maybe I'm mistaken but why would that require another repository? Based on my understanding of Linux (which I admit is not extensive), the PPA is merely a "well-known location" where Ubuntu keeps the latest .deb file for a particular software. From my understanding, Mr. Anton who is associated with Ubuntu, receives the latest deb file from the SUMO devs and updates the PPA. So why can't SUMO also host the latest releases' .deb files, just as SUMO hosts the latest .exe files for Windows users. While it would be better to use the PPA but it isn't getting updated as often. So as a backup, it might be useful for SUMO to release .deb files of recent releases. This is my understanding and I apologize if I've got some of the above points wrong.

Wishing you all a Happy New Year!

**Comment by behrisch** [comment]
No, the SUMO developers are not building the deb, The debian / ubuntu builds start from the source release.

**Comment by arsenious** [comment]
I apologize for that error. Please can you suggest some other way around this? Thanks

**Comment by behrisch** [comment]
Please try building yourself. It is not that hard and you can come here or to the mailing list for questions.

**Comment by arsenious** [comment]
Thank you
________________________________

**Comment by arsenious** [comment]
PPA seems to be updated. Thank you

**Comment by arsenious** [comment]
@behrisch 
Latest version 1.2 seems to be uploaded to Ubuntu PPA but I'm unable to upgrade my SUMO via apt-get
https://launchpad.net/~sumo/+archive/ubuntu/stable 

Latest updates
sumo 10 days ago 
Failed to build: amd64 i386
sumo 13 weeks ago 
Successfully built

**Comment by namdre** [comment]
amd64 build fails with
`
Traceback (most recent call last):
  File "tools/build/buildHTMLDocs.py", line 191, in <module>
    pages = getAllPages(args)
  File "/<<BUILDDIR>>/sumo-1.2.0+dfsg1/tools/build/mirrorWiki.py", line 46, in getAllPages
    f = urlopen("https://sumo.dlr.de/w/api.php?action=query&list=allpages&aplimit=500&format=json")
  File "/usr/lib/python2.7/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/usr/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 443, in open_https
    h.endheaders(data)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1255, in connect
    HTTPConnection.connect(self)
  File "/usr/lib/python2.7/httplib.py", line 821, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
IOError: [Errno socket error] [Errno -2] Name or service not known
`

whereas i386 build fails with
`
failed to create symbolic link '/usr/share/sumo/bin': No such file or directory
Traceback (most recent call last):
  File "/<<BUILDDIR>>/sumo-1.2.0+dfsg1/tools/build/setup-sumolib.py", line 17, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools
Traceback (most recent call last):
  File "/<<BUILDDIR>>/sumo-1.2.0+dfsg1/tools/build/setup-traci.py", line 17, in <module>
    from setuptools import setup
ImportError: No module named setuptools
`
