### ISSUE TITLE
Will you provide electronic tolling for roads in the simulator?

### ISSUE THREAD

**Issue by GoingMyWay** [eclipse/sumo#4984]
Thank you for such good simulator. Nowadays, roads in many urban areas have electronic tolling gantries that control the traffic.  Will you provide this feature so that the Python API can set gantries for roads and price for the tolling price?

**Comment by behrisch** [comment]
You can already set arbitrary parameters to edges, if you want. In which way do you want the simulation to be affected by the tolling? To use the information in routing is often non trivial because it may be not only an additional cost for one road but valid for a whole region. If you just want to modify costs for the roads that is already possible.

**Comment by GoingMyWay** [comment]
> You can already set arbitrary parameters to edges, if you want. In which way do you want the simulation to be affected by the tolling? To use the information in routing is often non trivial because it may be not only an additional cost for one road but valid for a whole region. If you just want to modify costs for the roads that is already possible.

Hi, sir, thank you for your reply. I want to set the fee for entering some road for different vehicles, such as cars, buses and trucks in order to affect the traffic volume in some regions and the total travelling time for all vehicles.  Tolling is a good way to alleviate traffic congestions in urban areas, for example, [electronic tolling in Singapore](https://en.wikipedia.org/wiki/Electronic_Road_Pricing).  Is sumo possible to do these things now?

**Comment by behrisch** [comment]
Yes, although you will need to give your increased price in form of a time equivalent (or need to set the cost for all edges), see http://sumo.dlr.de/pydoc/traci._edge.html#EdgeDomain-adaptTraveltime
