### ISSUE TITLE
Enhance simulation log to include all used parameters, marked as 'default' or 'user defined'

### ISSUE THREAD

**Issue by ZoltanBaksa** [eclipse/sumo#4992]
When I make several simulations variants, I need to create a summary report about the differences. To have a full report, I want to list all the default values, which might have an influence on the simulation results, not just the ones, which I directly set by configuration xml files. Unfortunately the xsd definition files only list the possible parameters, but they not contain the default values.
Because of higher combination possibilities, I do not see a good way to list all the default parameters before the simulation.
To create the report accordingly after simulation, I suggest to extend the simulation log content with the used parameters at the beginning, with marking which were 'default' and which were set by user defined configuration files.

**Comment by namdre** [comment]
you can get all simulation option default values in human readable form by calling
sumo --save-template defaults.sumocfg --save-commented

**Comment by ZoltanBaksa** [comment]
Yes, I know, but in this case I only get those parameters, which I can set in sumo config file, but not those for example which I can set in vTypes.xml, or detectors.xml.

**Comment by ZoltanBaksa** [comment]
In fact this would be useful, if there is a new parameter in a new release, or a default value was changed between versions.

**Comment by behrisch** [comment]
I see your point but I don't think this will be implemented. Sumo does not currently have any means of generating its own inputs in terms of detector files etc., so this will be a major effort for a single use case. What can be done more easily is to add an option to write the vehicle types including their defaults.

**Comment by ZoltanBaksa** [comment]
This is also a possible way for my use case, but not covers all the default values used. For the rest I will need to search in the html documentation.

**Comment by namdre** [comment]
Whenever default values change this should be covered in the changelog. If you're unsure about a particular default please do not hesitate to ask.
