### ISSUE TITLE
Include Internal edges in sumolib.net.Net.getShortestPath()

### ISSUE THREAD

**Issue by lediogj** [eclipse/sumo#4994]
Getting shortest path between two internal edges or one normal edges and another internal edges gives an error because internal edges are not supported in the current method .

**Comment by behrisch** [comment]
Since the follower edge is always unique you can always use this one but I agree it would be useful for convenience. Is there also a need for having the internal edges in the return value (optionally)?

**Comment by lediogj** [comment]
Optionally yes , maybe "self.hasInternal" value can be used , if this is true then it should include the internal edges in the return value

**Comment by namdre** [comment]
related to #1322
