### ISSUE TITLE
od2trips(Daily Time Lines)

### ISSUE THREAD

**Issue by shuowang572875852** [eclipse/sumo#4996]
My OD matrix is 24 hours, so I used the option Daily Time Lines (TGw2_PKW) in od2trips, and the resulting route has a serious jam, but it is normal without this option. What is the reason for that? How does "Time"in sumo-gui correspond to real time (24 hours)?
[od2trips.zip](https://github.com/eclipse/sumo/files/2724189/od2trips.zip)

**Comment by behrisch** [comment]
The question is rather what did you do for traffic assignment. Just one run of duarouter, duaIterate, or did you feed the trips directly into the simulation?

**Comment by shuowang572875852** [comment]
I want my route to reflect the traffic flow changes throughout the day, so I added weights to the routes generated at each moment. The command line is as follows:

C:\Users\Administrator\Desktop\shengzhen>C:\Users\Administrator\Desktop\sumo-1.1.0\bin\od2trips --taz-files shengzhentest.add.xml --od-matrix-files districts_OD_Matrix.mtx -o shengzhen.trips.xml  --timeline.day-in-hours --timeline 0.8,0.5,0.4,0.3,0.4,1.2,4.5,7.4,6.6,5.2,5.0,5.0,5.2,5.3,5.6,6.7
,8.4,8.6.,74,5.0,3.9,3.0,2.4,0.3,0.4,1.2,4.5,7.4,6.6,5.2,5.0,5.0,5.2,5.3,5.6,6.7,8.4,8.6,7.4,5.0,3.9,3.0,2.1,1.6

C:\Users\Administrator\Desktop\shengzhen>C:\Users\Administrator\Desktop\sumo-1.1
.0\bin\duarouter -n shengzhentest.net.xml -r shengzhen.trips.xml -o tmp.rou.xml
-a shengzhen.add.xml --vtype-output dummy --ignore-errors

C:\Users\Administrator\Desktop\shengzhen>python C:\Users\Administrator\Desktop\s
umo-1.1.0\tools\route2trips.py tmp.rou.xml > shengzhen_valid.trips.xml

When I don't weight od2trips , the generated route is normal.

**Comment by behrisch** [comment]
There is probably a typo in your timeline saying 74 between 8.6 and 5.0. If this is not a copy/paste mistake while writing the comment, please try again after fixing that one.

**Comment by shuowang572875852** [comment]
C:\Users\Administrator\Desktop\od2trips>C:\Users\Administrator\Desktop\sumo-1.1.
0\bin\od2trips --taz-files shengzhentest.add.xml --od-matrix-files districts_OD_
Matrix.mtx -o shengzhen.trips.xml  --timeline.day-in-hours --timeline 0.8,0.5,0.
4,0.3,0.4,1.2,4.5,7.4,6.6,5.2,5.0,5.0,5.2,5.3,5.6,6.7,8.4,8.6,7.4,5.0,3.9,3.0,2.
1,1.6

Not that mistake, the input is 7.4，and the generated trips also have  a serious jam,can you tell me how to do that?

**Comment by behrisch** [comment]
I close this since there seems to be no possible action on our side.
