### ISSUE TITLE
duaIterate.py (how to set vehicle-type)

### ISSUE THREAD

**Issue by shuowang572875852** [eclipse/sumo#5001]
I want to use “duarouter” to check the connection of od2trips  generated routes, and then use duaIterate.py to redistribute routes to ease traffic congestion.

1.   C:\Users\Administrator\Desktop\新建文件夹>C:\Users\Administrator\Desktop\sumo-1.1.0\bin\od2trips --taz-files shengzhentest.add.xml --od-matrix-files districts_OD_Matrix.mtx -o shengzhen.trips.xml --timeline.day-in-hours --timeline 0.8,0.5,0.4,0.3,0.4,1.2,4.5,7.4,6.6,5.2,5.0,5.0,5.2,5.3,5.6,6.7,8.4,8.6,7.4,5.0,3.9,3.0,2.1,1.6

2.  C:\Users\Administrator\Desktop\新建文件夹>C:\Users\Administrator\Desktop\sumo-1.
1.0\bin\duarouter -n shengzhentest.net.xml -r shengzhen.trips.xml -o tmp.rou.xml
 -a shengzhen.add.xml --vtype-output dummy --ignore-errors

3.   C:\Users\Administrator\Desktop\新建文件夹>python C:\Users\Administrator\Desktop\
sumo-1.1.0\tools\route2trips.py tmp.rou.xml > shengzhen_valid.trips.xml

4.   C:\Users\Administrator\Desktop\新建文件夹>python C:\Users\Administrator\Desktop\
sumo-1.1.0\tools\assign\duaIterate.py -n shengzhentest.net.xml -t shengzhen_valid.trips.xml -l 5
> Executing step 0
>> Running router on shengzhen_valid.trips.xml
>>> Begin time: 2019-01-05 15:16:11.642000
Loading configuration... done.
Execution of ['F:\\software\\sumo\\bin\\duarouter', '-c', 'iteration_000_shengzhen_valid.duarcfg'] failed. Look into dua.log for details.
and the dua.log are :  
Warning: Skipping isolated junction '5934394147'.
Warning: Skipping isolated junction '5934394148'.
Warning: Skipping isolated junction '5934394150'.
Error: The vehicle type 'type1' for vehicle '59' is not known.
Error: The vehicle type 'type1' for vehicle '1160' is not known.
Error: The vehicle type 'type1' for vehicle '279' is not known.
Error: The vehicle type 'type1' for vehicle '513' is not known.

so I add the vehicle type files (shengzhen.add.xml)
5.  C:\Users\Administrator\Desktop\新建文件夹>python C:\Users\Administrator\Desktop\
sumo-1.1.0\tools\assign\duaIterate.py -n shengzhentest.net.xml -t shengzhen_valid.trips.xml -l 5 -a shengzhen.add.xml

usage: duaIterate.py [-h] [-w] [-n FILE] [-+ ADDITIONAL] [-b BEGIN] [-e END]
                     [-R ROUTESTEPS] [-a AGGREGATION] [-m] [-p PATH] [-y] [-I]
                     [-j] [-q] [--meso-recheck MESORECHECK]
                     [-Q {CO,CO2,PMx,HC,NOx,fuel,noise}] [--eager-insert]
                     [--time-to-teleport TIMETOTELEPORT]
                     [--time-to-teleport.highways TIMETOTELEPORT_HIGHWAYS]
                     [--cost-modifier {grohnde,isar,None}] [-7] [-C] [-t FILE]
                     [-r FILE] [-F FILE] [-A GA] [-B GBETA] [-E] [-T]
                     [--tripinfo-filter TRIPINFOFILTER] [--inc-start INCSTART]
                     [--inc-max INCMAX] [--inc-base INCBASE]
                     [--incrementation INCVALUE] [--time-inc TIMEINC]
                     [-f FIRSTSTEP] [-l LASTSTEP]
                     [--convergence-iterations CONVIT]
                     [--max-convergence-deviation CONVDEV] [-D FILE]
                     [-x {None,routesonly,detailed}] [-z] [-K]
                     [--routing-algorithm ROUTING_ALGORITHM]
                     [--max-alternatives MAX_ALTERNATIVES]
                     [--skip-first-routing] [--logit] [-g LOGITBETA]
                     [-i LOGITGAMMA] [-G LOGITTHETA] [-J ADDWEIGHTS]
                     [--router-verbose] [-M] [-N] [--weight-memory]
                     [--pessimism PESSIMISM] [--clean-alt] [--binary]
                     [remaining_args [remaining_args ...]]
duaIterate.py: error: argument -a/--aggregation: invalid int value: 'shengzhen.add.xml'

I want to know how to solve this problem. How to set the value of iteration steps(-l) ?

**Comment by behrisch** [comment]
The option for the additional files is -+ in duaIterate.py not -a

**Comment by shuowang572875852** [comment]
C:\Users\Administrator\Desktop\新建文件夹>python C:\Users\Administrator\Desktop\
sumo-1.1.0\tools\assign\duaIterate.py -n shengzhentest.net.xml -t shengzhen_vali
d.trips.xml -l 5 -+shengzhen.add.xml
> Executing step 0
>> Running router on shengzhen_valid.trips.xml
>>> Begin time: 2019-01-06 13:21:46.057000
Loading configuration... done.
Execution of ['F:\\software\\sumo\\bin\\duarouter', '-c', 'iteration_000_shengzh
en_valid.duarcfg'] failed. Look into dua.log for details.

it is still wrong,and can you tell me how to correct it?
[新建文件夹.zip](https://github.com/eclipse/sumo/files/2730189/default.zip)

**Comment by behrisch** [comment]
The easiest way is probably to keep the vtype in the route and trip file (not using the dummy). Why did you choose to seperate it? I keep this issue open because we need to find a better way to feed a vtype file reliably into router and simulation when using duaiterate.

**Comment by shuowang572875852** [comment]
I want to know how to keep the vtype in the route or trip file? I used od2trips to generated the trip files ,
and the vtype  defined in additional files and in od_matrix(vtype) select the vehicle type.

**Comment by shuowang572875852** [comment]
C:\Users\Administrator\Desktop\新建文件夹>python C:\Users\Administrator\Desktop\
sumo-1.1.0\tools\assign\duaIterate.py -n shengzhen.net.xml -t shengzhen_valid.tr
ips.xml -l 5
> Executing step 0
>> Running router on shengzhen_valid.trips.xml
>>> Begin time: 2019-01-17 15:32:13.599000
Loading configuration... done.
>>> End time: 2019-01-17 15:32:49.671000
>>> Duration: 0:00:36.072000
<<
>> Running simulation
>>> Begin time: 2019-01-17 15:32:49.672000


how can i do for it?

**Comment by behrisch** [comment]
What exactly is the question?

**Comment by zhaotuo0815** [comment]
> What exactly is the question?

hi,developer，I want to know that what is the output of DUE,and the iteration process is too long,how can I do for it?

**Comment by behrisch** [comment]
It depends whether the simulation itself is slow, see https://sumo.dlr.de/docs/FAQ.html#how_can_i_make_the_simulation_run_faster or if there are just too many iterations, then limit the number of iterations using **--last-step**.
Please do not comment on old vaguely related tickets, open new ones or ask on the mailing list.

**Comment by zhaotuo0815** [comment]
thank you your reply.I am sorry for that.



发自我的iPhone


------------------ Original ------------------
From: Michael Behrisch ***@***.***&gt;
Date: Thu,Apr 8,2021 2:58 PM
To: eclipse/sumo ***@***.***&gt;
Cc: zhao tuo ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [eclipse/sumo] duaIterate.py (how to set vehicle-type) (#5001)
