### ISSUE TITLE
od2trips(vehicle type)

### ISSUE THREAD

**Issue by shuowang572875852** [eclipse/sumo#5002]
I know the input file od_matrix in od2trips can define the vehicle_type , but  how to define different vehicle 
types in od_matrix?
the additional files : shengzhen.add.xml
<additional>
   <vType id="type1" accel="2.6" decel="4.5" sigma="0.5" length="5" maxSpeed="70"/>
   <vType id="type2" accel="0.8" decel="2.5" sigma="0.5" length="8" maxSpeed="50"/>
</additional>

the od_matrix files : 

$VMR
* vehicle type
type1
* From-Time  To-Time
0.00 24.00
* Factor
1.00
*
* some
* additional
* comments
* District number
   5
* names:
		taz_0	taz_1	taz_2	taz_3	taz_4
*
* District taz_0 Sum=	 928
          64      80      208     352   224
* District taz_1 Sum=	 16880
         128     1184     1488   8304   5776
* District taz_2 Sum=	 22240
         208     1424    7056    8752   4800
* District taz_3 Sum=	 98336
         464     9856     9680   51264  27072
* District taz_4 Sum=	  50144
         208     6080    4528    23904  15424		

How do I define a part of the vehicle type as type1 and another part as type 2? can i use od2trips ( --timeline.day-in-hours --timeline) to separate define vehicle type1 and type2?

**Comment by shuowang572875852** [comment]
In the same time period, I have two OD matrices for  different vehicle type , one is car OD matrix , the other is  trailer OD matrix. I want to know how to simulate the route generated by two different OD matrices in one simulation.

**Comment by behrisch** [comment]
You simply generate two route files from the two OD matrices and give them both to sumo.
