### ISSUE TITLE
Breakpoints editor does not accept time value at first try

### ISSUE THREAD

**Issue by m-kro** [eclipse/sumo#5009]
When setting a breakpoint time in SUMO-GUI through the dedicated editor window, I have run into a time format error e.g. "The value must be a number , is: 100". 
- Open the breakpoint editor, click into the cell and enter a number, say 100
- The error message will be displayed and the typed value will be removed
- Enter the number again - it is accepted and formatted as "100.000"

**Comment by namdre** [comment]
The issue is a single space to the right of the entered number. If you just start typing instead of clicking it will work.
