### ISSUE TITLE
cmake error while building sumo-1.0.1 for ubuntu 16.04

### ISSUE THREAD

**Issue by saifhitawala** [eclipse/sumo#5023]
I recently upgraded sumo to 1.1.0 on my Ubuntu 16.04 LTS machine and was facing this issue #5000  #5020. I am trying to downgrade it back to 1.0.1 building from source and following this link: http://sumo.dlr.de/wiki/Installing/Linux_Build. 

But, when I try to cmake (make -j 8 step) I get this log:

[ 89%] Building CXX object unittest/src/netbuild/CMakeFiles/testnetbuild.dir/NBHeightMapperTest.cpp.o
[ 89%] Building CXX object src/router/CMakeFiles/router.dir/RORoute.cpp.o
[ 89%] Building CXX object unittest/src/microsim/CMakeFiles/testmicrosim.dir/MSCFModel_IDMTest.cpp.o
[ 89%] Building CXX object unittest/src/utils/common/CMakeFiles/testcommon.dir/ValueTimeLineTest.cpp.o
[ 89%] Building CXX object unittest/src/netbuild/CMakeFiles/testnetbuild.dir/NBTrafficLightLogicTest.cpp.o
[ 89%] Building CXX object src/router/CMakeFiles/router.dir/RORouteDef.cpp.o
[ 89%] Building CXX object src/router/CMakeFiles/router.dir/RORouteHandler.cpp.o
[ 89%] Building CXX object src/router/CMakeFiles/router.dir/ROVehicle.cpp.o
[ 89%] Linking CXX executable ../../../../../bin/testnetbuild
[ 89%] Linking CXX executable ../../../../../bin/testmicrosim
[ 89%] Linking CXX executable ../../../../../../bin/testgeom
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../lib/libgtest.a(gtest-all.cc.o): undefined reference to symbol 'pthread_key_delete@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
unittest/src/microsim/CMakeFiles/testmicrosim.dir/build.make:175: recipe for target '../../bin/testmicrosim' failed
make[2]: *** [../../bin/testmicrosim] Error 1
CMakeFiles/Makefile2:4008: recipe for target 'unittest/src/microsim/CMakeFiles/testmicrosim.dir/all' failed
make[1]: *** [unittest/src/microsim/CMakeFiles/testmicrosim.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 89%] Built target testgeom
[ 89%] Built target testnetbuild
[ 89%] Linking CXX executable ../../../../../../bin/testcommon
[ 89%] Built target testcommon
[ 90%] Linking CXX static library librouter.a
[ 90%] Built target router
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

Could someone please point me in the right direction as to where the problem is?

Thanks!

**Comment by behrisch** [comment]
Can you try adding "-pthread" to the CXX_FLAGS? So replace

    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -Wall -pedantic -Wextra")
 with

    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -pthread -Wall -pedantic -Wextra")

in CMakeLists.txt.

**Comment by saifhitawala** [comment]
Yes. It works now. Thank you!

**Comment by kaushikb258** [comment]
I am trying to install Sumo 1.0.1 on Ubuntu 16.04. When I do: 
cmake ../..
I get this error. Any solution to this? Incidentally, Sumo's latest version 1.2 seems to work, but I have an application that specifically requires version 1.0.1. How to fix this cmake error?


-- Setting build type to 'Release' as none was specified.
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_BINARY_DIR: /home/kaushik/sumo_again/sumo-1.0.1/build/cmake-build
-- CMAKE_SOURCE_DIR: /home/kaushik/sumo_again/sumo-1.0.1
-- 
-- Platform: 
--     Host: Linux4.15.0-47-genericx86_64
--     CMake: 3.12.0
--     CMake generator: Unix Makefiles
--     CMake build tool: /usr/bin/make
--     Compiler: GNU
-- 
-- Found PythonInterp: /home/kaushik/anaconda3/bin/python (found version "3.5.5") 
-- Found Python: /home/kaushik/anaconda3/bin/python
-- Found GTest: /usr/lib/libgtest.a  
-- Found XercesC: /usr/lib/x86_64-linux-gnu/libxerces-c.so (found version "3.1.3") 
-- Found Proj: /usr/lib/x86_64-linux-gnu/libproj.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- Found GDAL: /usr/lib/libgdal.so  
-- Found osgGA: /usr/local/lib64/libosgGA.so  
-- Found osgViewer: /usr/local/lib64/libosgViewer.so  
-- Found osgUtil: /usr/local/lib64/libosgUtil.so  
-- Found osgDB: /usr/local/lib64/libosgDB.so  
-- Found osgText: /usr/local/lib64/libosgText.so  
-- Found osg: /usr/local/lib64/libosg.so  
-- Found OpenThreads: /usr/local/lib64/libOpenThreads.so  
-- Found OpenSceneGraph: /usr/local/lib64/libosgGA.so;/usr/local/lib64/libosgViewer.so;/usr/local/lib64/libosgUtil.so;/usr/local/lib64/libosgDB.so;/usr/local/lib64/libosgText.so;/usr/local/lib64/libosg.so;/usr/local/lib64/libOpenThreads.so (found suitable version "3.6.3", minimum required is "3.4.0") 
-- Found GL2PS: /usr/lib/libgl2ps.so  
-- Found SWIG: /usr/bin/swig3.0 (found suitable version "3.0.8", minimum required is "3.0") 
-- Found Java: /usr/bin/java (found version "11.0.2") 
-- Found JNI: /usr/lib/jvm/default-java/jre/lib/amd64/libjawt.so  
-- Found PythonLibs: /home/kaushik/anaconda3/lib/libpython3.5m.so (found version "3.5.5") 
-- Found Git: /usr/bin/git (found version "2.7.4") 
-- Enabled features: Linux-4.15.0-47-generic Proj GUI GDAL FFmpeg OSG GL2PS SWIG
-- Configuring done
CMake Error at unittest/src/utils/common/CMakeLists.txt:1 (add_executable):
  Cannot find source file:

    FileHelpersTest.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at unittest/src/utils/common/CMakeLists.txt:1 (add_executable):
  No SOURCES given to target: testcommon

**Comment by behrisch** [comment]
@kaushikb258 The file mentioned (FileHelpersTest.cpp) is not in the release. Please remove it from the CMakeLists.txt in the same directory. Also please open a new ticket when a problem occurs and do not comment on closed ones.

**Comment by kaushikb258** [comment]
Thanks!
