### ISSUE TITLE
NaN value in ssm output

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#5033]

**Comment by namdre** [comment]
I fail to find the functional change among all the refactoring changes. Can you highlight the relevant lines?

**Comment by mehmetnedimyavuz** [comment]
Hello @m-kro , I am using the Eclipse SUMO sumo Version v1_18_0+1623-3e48cd6c7e7. I faced the NaN  value problem in the ssm output file shown as below. Some of minTTC row is filled with "NA". Thank you for help.Regards.
![image](https://github.com/eclipse-sumo/sumo/assets/79362739/fe17d7e3-2cdc-4ac4-8392-857730e083f5)
[safety_with_na.zip](https://github.com/eclipse-sumo/sumo/files/12782234/safety_with_na.zip)

**Comment by m-kro** [comment]
@mehmetnedimyavuz "NA" and "NaN" are completly different special values. "NA" stands for "not available" and is printed when the SSM device cannot compute the measure for this conflict. Maybe the TTC threshold makes the SSM device discard some values. 
"NaN" is the acronym of "not a number" and indicates a serious computation problem (see e.g. [this tutorial site](https://www.geeksforgeeks.org/nan-in-cpp-what-is-it-and-how-to-check-for-it/)).

**Comment by mehmetnedimyavuz** [comment]
Sorry for the confusion @m-kro .I have one more question about the defining thresholds. Is there any possibility to define different thresholds for different vehicle types (for instance: TTC). I tried to using <param under <vType element in additional xml file for creating route files using randomTrips tool. This method does not work as expected. Can you give me a suggestion? Regards.

**Comment by m-kro** [comment]
@mehmetnedimyavuz Can you please open a new issue to explain what did not work as expected? This is clearly a separate topic. Add a minimum scenario to replicate if you think it is helpful.
