### ISSUE TITLE
osmWebWizard.py errors version 1.1.0

### ISSUE THREAD

**Issue by danieljyj** [eclipse/sumo#5041]
Hello,
an error in sumo version 1.1.0 win64, the first tutorial osmWebWizard.py
when clicking generate scenario, it don't provoque SUMO-GUI.
with this error:  "line 164 of osmWebWizard.py, unicode not defined"
whereas version 1.0.1 works.
Best wishes

**Comment by namdre** [comment]
Thank you for reporting. This issue has already been fixed in the development version (#5007)
