### ISSUE TITLE
Implement SWIG based TraCI client

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#5053]
- possible replacement for TraaS and traci4matlab
- makes the codebase easier to maintain
- can even reuse the header files of libsumo

**Comment by namdre** [comment]
could also be used for a C# client (development of https://github.com/CodingConnected/CodingConnected.Traci seems to have slowed down quite a bit).

**Comment by behrisch** [comment]
libtraci is there since 1.9.0
