### ISSUE TITLE
do not find fx.h during make process

### ISSUE THREAD

**Issue by angler4sdt** [eclipse/sumo#5075]
here are hints when I try to do the make process:

In file included from MSParkingArea.cpp:37:0:
../../src/utils/foxtools/MFXMutex.h:36:16: fatal error: fx.h: No file or directory
compilation terminated.

did you meet the same issue? 

my OS: ubuntu 16.04 TLS  
sumo 0.32.0

Thanks!!

**Comment by behrisch** [comment]
This was a known issue with building this release. The easiest way (if you cannot upgrade to a more recent sumo by using the ppa as described in http://sumo.dlr.de/download) is to install libfox-1.6-dev. Please reopen if problems persist.
