### ISSUE TITLE
Implement GNETrips and GNEFlows

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#5086]
Trips are similar to GNEFlows

- [x] flow params cannot be edited
- [x] flow attribute 'route' is not saved.
- [x]  No error message when loading flow without route from file
- [x] vType saved with wrong id (after editing id)
- [x]  selecting all flow, counts them as vehicles in statistics

**Comment by namdre** [comment]
re-opened to items since they are still not working.

**Comment by palvarezlopez** [comment]
Test and implementation finished. All new bugs/enhancements related with this element will be handled in an different ticket.
