### ISSUE TITLE
TraCI: LineWidth of added polygon

### ISSUE THREAD

**Issue by dbuse** [eclipse/sumo#5113]
There currently seems to be no way of setting:
- the line with for a newly created polygon or
- the default line with for new polygons
This makes polygon creation (via TraCI) less efficient, because the desire lineWidth has to be set with another TraCI call.
So I propose (either or both):
- an optional parameter lineWidth for the add polygon call
- a new call to set the default lineWidth for polygons

**Comment by namdre** [comment]
lineWidth already exists as an optional 6th parameter of polygon.add()
It can be set using the python client but is missing from the C++ client and from TraaS.
Which client are you using?

**Comment by dbuse** [comment]
Ah, interesting, I did not know that. it also does not seem to be documented in the wiki section for the add polygon command ([wiki is down, but here's the link to the userdoc](http://sumo.sourceforge.net/userdoc/TraCI/Change_Polygon_State.html#ADD_.280x80.29)). Since when is this extra parameter available?
I'm using Veins' custom C++ client, so mostly hand-rolled TraCI commands.

**Comment by dbuse** [comment]
Alright. Then I'll consider the issue resolved. Thanks!
