### ISSUE TITLE
deleting junctions does not remove the attached edges from the network view

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#5122]
they can no longer be used as connection target but they are rendered and can be inspected

**Comment by namdre** [comment]
netedit when trying to delete one of these 'ghost' edges

**Comment by namdre** [comment]
seems to be gone. Possibly an intermediate version code version.
@palvarezlopez Any Idea what that could have been?

**Comment by palvarezlopez** [comment]
@namdre Probably a Linker-Error between Netedit and z_netedit_netelements. I had similar errors previously and a entire recompiling solved the problem.
