### ISSUE TITLE
sumo installation from ppa does not work on ubuntu 18.10

### ISSUE THREAD

**Issue by thepatcher** [eclipse/sumo#5123]
I'm trying to install sumo "sumo - 1.1.0+dfsg1-5" from https://launchpad.net/~sumo/+archive/ubuntu/stable/+packages on ubuntu 18.10.
I've added this repo:
`http://ppa.launchpad.net/sumo/stable/ubuntu bionic main`
Currently "libgdal20" and "libproj13" packages are installed (with apt-get from official repos).

This is the output:
```
$sudo apt-get install sumo
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 sumo : Depends: gdal-abi-2-2-3 but it is not installable
        Depends: libproj12 (>= 4.8.0) but it is not installable
        Recommends: sumo-tools but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

I'm aware that the ppa repository supports up to 18.04 only.
But is there a way to install this sumo version on 18.10?

**Comment by behrisch** [comment]
I added a cosmic (ubuntu 18.10) variant to the ppa which installed without problems in a docker container. Please reopen if problems persist.

**Comment by thepatcher** [comment]
It works - I just tested it in my VM.
Thank you :)
