### ISSUE TITLE
allow using explicitly defined inductionloop for actuated traffic light

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#5125]
new optional param in tllogic
`<param key="detectors" value="det1 det2 det3"/>`
replaces auto-generated detectors on the respective lanes (custom placement)

**Comment by abed1856** [comment]
Hello Jakob,
What should be done to affect this new optional param in tllogic?
I have used it but still sumo uses its pre-defined detectors and shows them. I also defined detectord is additional files but the  the "max-gap" defined in param does not connect to custom defined detector (neither by activating "show-detectors" and "max-gap" nor by deactivating them)
my definitions are as below:

    <tlLogic id="gneJ5" type="actuated" programID="0" offset="0">
        <phase duration="42" state="GgGgrrrrrGgGgrrrrr" minDur="5" maxDur="50"/> 
        <phase duration="3"  state="yyyyrrrrryyyyrrrrr"/>
        <phase duration="10" state="rrrrGGGggrrrrGGGgg"/> 
        <phase duration="3"  state="rrrryyyyyrrrryyyyy"/>
        <param key="detectors" value="det_e1 det_e1_1"/>
	<param key="max-gap" value="3.0"/>
	<param key="show-detectors" value="true"/>
    </tlLogic>

[Neuer Ordner.zip](https://github.com/eclipse/sumo/files/3271649/Neuer.Ordner.zip)
Best Regards
