### ISSUE TITLE
vehicles looking for a parking space don't help others return to the road

### ISSUE THREAD

**Issue by zsambokiandras** [eclipse/sumo#5128]
Vehicles rather circle indefinitely (with continuous rerouting to the next parkingArea) than help a car leave its parking space and park there. Closing a lane in the GUI shows that there is enough road length for a car to depart, but the gaps are too small. See the attached simulation.
[parking.zip](https://github.com/eclipse/sumo/files/2812966/parking.zip)

**Comment by namdre** [comment]
Thanks for the scenario. In light of this, #5126 seems more relevant

**Comment by namdre** [comment]
current implementation allows for deadlock if a vehicle "requests help" from another vehicle that has already driven a bit too far. A simple solution would be to restrict the help request scenario to the situation where the parkingArea is at capacity
