### ISSUE TITLE
possible memory leak in SUMORouteHandler.cpp

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#5129]
Line 117: myCurrentVehicleType is updated but the old object isn't deleted.

**Comment by palvarezlopez** [comment]
@namdre Do you think that we can change the code to delete pointer in SUMORouteHandler.cpp?

**Comment by namdre** [comment]
I'll take a look

**Comment by palvarezlopez** [comment]
@namdre This can be a possible solution:

https://github.com/eclipse/sumo/commit/e6a57443a24ead0d4fe9448975197d179a9559d7#diff-68096ac0ece8b2041709f38aad40ba57

**Comment by namdre** [comment]
There is no memory in the other subclasses:
* MSRouteHandler deletes myCurrentVType in myEndElement
* RORouteHandler deletes it implicitly via addVehicleType, called from myEndElement
* your patch takes care of it in GNEDemandElementHandler.

This reminds me: please remame GNEDemandElementHandler to GNERouteHandler to follow the existing naming scheme.
