### ISSUE TITLE
Intentionally cause collision with pedestrians

### ISSUE THREAD

**Issue by ndeshp2s** [eclipse/sumo#5130]
I want to create a collision situation between a pedestrian and my ego vehicle. However, whenever the vehicle comes closer to the pedestrian, the pedestrian tele-operates itself. 

I tried changing the "--collision.mingap-factor" and "--collision.action" parameters. But I am not sure if they work for pedestrians.

**Comment by namdre** [comment]
The pedestrian moves out of the way laterally with its configured speed. If you set the speed to near zero using traci (person.setSpeed()) or make the pedestrian slow all the time using type attribute maxSpeed, you should be able to force the collision.

**Comment by ndeshp2s** [comment]
Thank you @namdre for your quick response. As you mentioned, I tried with setting the speed of pedestrian to zero from traci and by maxSpeed attribute. With traci it works, however, the maxSpeed seem to have no impact on the speed of a pedestrian. I am doing something wrong?

I tried the following options in my .rou file:

1. 
<vType id="vType1" vClass="pedestrian" maxSpeed="0.01"/>
<person id="ped0" type="vType1" depart="0.00" departPos="40.0">
        <walk from="WC1" to="WC1" arrivalPos="0.0" duration="47.50"  />
</person>

2. 
    <person id="ped0" depart="0.00" departPos="40.0" maxSpeed="0.5">
        <walk from="WC1" to="WC1" arrivalPos="0.0" maxSpeed="0.5" duration="47.50"  />
    </person>

**Comment by ndeshp2s** [comment]
Ohk. WIthout duration it works for me as well. 

Thank you.

**Comment by ndeshp2s** [comment]
I had a question regarding the protocol for the status of an issue. Since my query is resolved, am I supposed to close this issue? Or leave it open @namdre

**Comment by namdre** [comment]
Since you said it is resolved I'm closing it now.
In the future, you can also just close it yourself.
