### ISSUE TITLE
About installing sumo software on a Linux system

### ISSUE THREAD

**Issue by taowang7** [eclipse/sumo#5133]
I successfully installed the sumo software on a Linux system.  I verified with the sumo command:sumo. the result  like this:
[root@jtcn139 ydcb]# sumo
SUMO Version 0.32.0
 Build features: x86_64-pc-linux-gnu TRACI
 Copyright (C) 2001-2017 German Aerospace Center (DLR) and others; http://sumo.dlr.de
 License EPLv2: Eclipse Public License Version 2 <https://eclipse.org/legal/epl-v20.html>
 Use --help to get the list of options.

but when I use traCI to sumo samething, the result like this:

[root@jtcn139 ydcb]# python traCI2.py
 Retrying in 1 seconds
Error: Could not access configuration '/root/sumo-0.32.0/caseFile/inputfile/week_6_cross.sumocfg'.
Quitting (on error).
Could not connect to TraCI server at localhost:55337 [Errno 111] Connection refused
 Retrying in 2 seconds
Could not connect to TraCI server at localhost:55337 [Errno 111] Connection refused
 Retrying in 3 seconds
Could not connect to TraCI server at localhost:55337 [Errno 111] Connection refused
 Retrying in 4 seconds
Could not connect to TraCI server at localhost:55337 [Errno 111] Connection refused
 Retrying in 5 seconds
Could not connect to TraCI server at localhost:55337 [Errno 111] Connection refused
 Retrying in 6 seconds
Could not connect to TraCI server at localhost:55337 [Errno 111] Connection refused
 Retrying in 7 seconds
Could not connect to TraCI server at localhost:55337 [Errno 111] Connection refused
 Retrying in 8 seconds
Could not connect to TraCI server at localhost:55337 [Errno 111] Connection refused
 Retrying in 9 seconds
Could not connect to TraCI server at localhost:55337 [Errno 111] Connection refused
 Retrying in 10 seconds
Could not connect to TraCI server at localhost:55337 [Errno 111] Connection refused
Traceback (most recent call last):
  File "traCI2.py", line 40, in <module>
    traci.start([sumoBinary, "-c", "/root/sumo-0.32.0/caseFile/inputfile/week_6_cross.sumocfg", "--no-warnings"])
  File "/root/sumo/sumo-1.0.1/tools/traci/__init__.py", line 97, in start
    _connections[label] = connect(port, numRetries, "localhost", sumoProcess)
  File "/root/sumo/sumo-1.0.1/tools/traci/__init__.py", line 75, in connect
    raise FatalTraCIError("Could not connect in %s tries" % (numRetries + 1))
traci.exceptions.FatalTraCIError: Could not connect in 11 tries

do you know why?

**Comment by namdre** [comment]
It looks as if you installed sumo with root permissions (into the /root folder) and try is running it without root privileges. Advice
- install sumo to a place that can be read by a normal user
- remove the outdated version 0.32.0 and use this instead: 

```
sudo add-apt-repository ppa:sumo/stable
sudo apt-get update
sudo apt-get install sumo sumo-tools sumo-doc 
```

**Comment by taowang7** [comment]
thanks
