### ISSUE TITLE
Make pedestrians move on road

### ISSUE THREAD

**Issue by ndeshp2s** [eclipse/sumo#5139]
Is there a possibility to move pedestrians from one waking area to another through road? The road edge for the vehicle also has permission for pedestrian. 
As shown in the figure below, I am trying to simulate a pedestrian which would often follow the traffic rules, but some times instead of walking over crossing, use a path as shown in the figure by red mark.

![screenshot from 2019-01-31 15-49-28](https://user-images.githubusercontent.com/1629735/52062196-55596e80-2570-11e9-97f3-499b2d4885a5.png)

**Comment by ndeshp2s** [comment]
I tried moveToXY, but seems to teleport the person to the desired x,y location. And does not seem to let it follow a path from its current location to the desired x,y location. I wanted the person to walk continuously on the mentioned path.

**Comment by namdre** [comment]
This is not supported right now, The only way to get this path is to remote-control the person every step of the way.

**Comment by ndeshp2s** [comment]
Ohk. I see. Thank you for the update. And is there a possibility to have this functionality in the future?

**Comment by ndeshp2s** [comment]
Hello. Sorry for delayed reply and thanks a lot for the update.
