### ISSUE TITLE
SUMO crashes on adding person

### ISSUE THREAD

**Issue by ndeshp2s** [eclipse/sumo#5140]
I have been working on adding person in SUMO since a few days.

However, suddenly today, the system has started crashing whenever a person is added. 

I get following error:
`  File "/usr/share/sumo/tools/traci/__init__.py", line 127, in simulationStep
    responses = _connections[""].simulationStep(step)
  File "/usr/share/sumo/tools/traci/connection.py", line 323, in simulationStep
    result = self._sendExact()
  File "/usr/share/sumo/tools/traci/connection.py", line 99, in _sendExact
    raise FatalTraCIError("connection closed by SUMO")
traci.exceptions.FatalTraCIError: connection closed by SUMO
`

I tried something as simple as:
`    <person id="ped0" depart="0.00" departPos="40.0" > 
        <walk from="WC" to="WC" arrivalPos="0.0" /> 
    </person>`

**Comment by namdre** [comment]
please attach all files necessary to reproduce this (the fewer/smaller the better)

**Comment by namdre** [comment]
closing due to lack of response.
