### ISSUE TITLE
sumo.dlr.de not available

### ISSUE THREAD

**Issue by ZoltanBaksa** [eclipse/sumo#5141]

**Comment by namdre** [comment]
It seems there is still a problem with https accessibility.
Pages.
 http://sumo.dlr.de/wiki/SUMO_User_Documentation
is accessible while 
 https://sumo.dlr.de/wiki/SUMO_User_Documentation
generates an SSL error:
 SSL_ERROR_RX_RECORD_TOO_LONG

**Comment by m-kro** [comment]
Well, I still wait forever for **http**://sumo.dlr.de/wiki/SUMO_User_Documentation to load...

**Comment by behrisch** [comment]
Also still not working here: 503 Service Unavailable

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

**Comment by behrisch** [comment]
We are back online.

**Comment by namdre** [comment]
I still cannot access the page from outside the DLR )-:

**Comment by behrisch** [comment]
Are you sure it is not a caching problem? Robert tried it from home this afternoon and I tried it a second ago as well and it worked.

**Comment by namdre** [comment]
I tested 3 different computers at home with various browsers including w3m and it would not work. After rebooting my router it started to work again so I'll assume it was a caching issue.
