### ISSUE TITLE
Move the view window with ego vehicle

### ISSUE THREAD

**Issue by ndeshp2s** [eclipse/sumo#5150]
Hello,

I am building a large urban environment and was wondering if the possible to move the region of view along with the ego vehicle? So that I do not need to zoom out to view the complete environment at a time.

**Comment by m-kro** [comment]
You can track a vehicle either by using the context option in SUMO-GUI or using the TraCI command (e.g. see http://www.sumo.dlr.de/pydoc/traci._gui.html#GuiDomain-trackVehicle )

**Comment by behrisch** [comment]
Seems to be solved, thanks @m-kro
