### ISSUE TITLE
sumo-gui localization

### ISSUE THREAD

**Issue by preskenis** [eclipse/sumo#5166]
Can SUMO-GUI be translated to other language? Maybe a special localisation file where we can type all "words" and "phrases".

**Comment by namdre** [comment]
No, this is currently not possible.
Adding localication capabilities for the GUI wouldn't be too difficult, just a lot of work.
However, all the xml elements will definitely remain english keywords.

**Comment by palvarezlopez** [comment]
@namdre @behrisch can I close this ticket?

**Comment by namdre** [comment]
discussion continued in #11237
