### ISSUE TITLE
Allow retrieval of neighboring vehicles via traci

### ISSUE THREAD

**Issue by leoluecken** [eclipse/sumo#5170]
Signature should be
```python
def traci.vehicle.getNeighbors(par):
    """ byte -> List(Pair(VehID, dist)) """
```
Where the `par` parameter is a bitset (UBYTE), specifying the following:
1: query lateral direction (left:0, right:1)
2: query longitudinal direction (followers:0, leaders:1)
3: blocking (return all:0, return only blockers:1)

For the first version, the exact set of blockers in case blocking==1 is not determined in for the sublane model, but all neighboring vehicles are either returned (in case LCA_BLOCKED) or none os returned (in case !LCA_BLOCKED).

The returned list contains all neighboring leaders, resp. followers, along with their longitudinal distance to the ego vehicle. For the non-sublane case, the lists will contain at most one entry.

**Comment by namdre** [comment]
@leoluecken Could you also add this to the  wiki traci documentation (once it is back online)?

**Comment by leoluecken** [comment]
[ ] Docu
[ ] #5180 related doubts on sanity for sublane case
