### ISSUE TITLE
The mailing address that one could use to ask for help 

### ISSUE THREAD

**Issue by JaneCheung** [eclipse/sumo#5173]
Hi, there are something wrong while I was sending email to **Sumo project User discussions <sumo-user@eclipse.org>**

Is that correct email address? 

**ANOTHER QUESTION：**
My question in previous email is that http://www.sumo.dlr.de/userdoc/Simulation/Output/Lane-_or_Edge-based_Traffic_Measures.htm
Whiel I build the add.xml file  with the  command

<additional>
  <edgeData id="<edge_ID>" file="<OUTPUT_FILE NAME>"/>
<additonal>

I have combined the **add file** in the **configuration file** . I had not get the output file with the name that I defined in the additonal file .

**Comment by namdre** [comment]
1) the address is correct. Did you subscribe to the mailinglist?
2) possibly you additional file contains an error. Please zip your config file and your additional file and attach them to this ticket

**Comment by namdre** [comment]
closing for lack of answer.

**Comment by JaneCheung** [comment]
Today I just write some message without additional files,
I still could not get access from the mailing list and receive  a response like this:
***********************************************************************************************
The results of your email command are provided below. Attached is your
original message.

- Results:
    Ignoring non-text/plain MIME parts

- Unprocessed:
    would like to ask for anyone who could help me ?
    As  the concept in the transportation system, could  we set
    1) Saturation flow for "turn left""turn right""straight" separately?
    2) The average start up (brake) speed;
    3) The free flow speed at junction ?
    Appreciate  for anyone who could give me some suggestion about how to
    modify these parameters!
    Best regards!
    Lizzy Cheung

- Done.
***********************************************************************************************
and  I have subscribed to the mailing list SUMO.
![image](https://user-images.githubusercontent.com/39317241/56511544-79cf4200-64f2-11e9-9062-050f088d0775.png)

How could I deal with the problem like that ?
Appreciate for any kind help!
