### ISSUE TITLE
Invalid `errno` assumption in StringUtils::toLong

### ISSUE THREAD

**Issue by mightyCelu** [eclipse/sumo#5182]
The current implementation of `StringUtils::toLong` assumes that `errno` being `ERANGE` after calling `strtoll`/`strtoi64` means, indicates parsing an out-of-range literal and subsequently raises a `NumberFormatException`. However, the parsing functions set `errno` only when the literal actually is out of range. So when `errno` is already set to `ERANGE` when the function is called, the exception is thrown erroneously.

**Comment by namdre** [comment]
fixed via  b2875d5c0dd48bf5e531e30f482e62e73a111be0
