### ISSUE TITLE
Could't open the sumo tutorial website

### ISSUE THREAD

**Issue by fengbaozhiling1** [eclipse/sumo#5200]
When I  want to browse http://www.sumo.dlr.de/userdoc/Tutorials/Hello_Sumo.html, It says "The requested URL /userdoc/Tutorials/Hello_Sumo.html was not found on this server" even I use different computers.
Could you mind telling me what I can do?

**Comment by namdre** [comment]
the regular wiki is back online. you can use https://sumo.dlr.de/wiki/Tutorials/Hello_Sumo
