### ISSUE TITLE
Importing python TraCI lib requires to have full SUMO installed.

### ISSUE THREAD

**Issue by dbuse** [eclipse/sumo#5207]
Since v1_0_0 (commit 9fced904d62528681c701d3509d739a87c764501), the python traci library need the variable `SUMO_HOME` to be set and point to the current active installation -- otherwise it just dies:
https://github.com/eclipse/sumo/blob/4d2c20da45a0aa51c4626852c795317b71fa6558/tools/traci/__init__.py#L31-L35

It seems like the reason for this is to be able to find the `sumolib` package, which sould be in the same directory.

While this procedure is probably fine if one checks out (or extracts a archive of) the whole sumo source tree, it removes a lot of flexibility, e.g., running some python script using the `traci` package in a lightweight VM or container. Especially as there is no need to access the whole `SUMO_HOME` dir. All that is needed is a way to resolve the `sumolib` package.

I could think of two solutions:
1. Instead of relying on `SUMO_HOME`, just us the path of the current file (`traci/__init__.py`) to find the location of `sumolib`.
2. Use the established ecosystem of Python and provide packages for `sumolib` and `traci`. I've already done this for myself and so far it worked fine for the last 7+ Sumo releases. If you are fine with it, these packages could even go to PyPI (the cheese shop) for easy installation.

**Comment by behrisch** [comment]
@dbuse Thanks for mentioning it. We even have the setup scripts in our tools/build dir, we just did not get around to uploading it. If you could have a short look on them and can give list of steps we need to issue to have everything uploaded I would be grateful.

**Comment by dbuse** [comment]
Cool, totally forgot about these!

The setup files for sumolib and traci look mostly fine. Here are a few remarks:
- sdist building seems to be broken, python source files are not added. Looks like that needs an actual `setup.py` file names just like that. Wheel building and installing works fine, however.
- the current (v1_1_0+) versions get the version tag right, however, before there were (wrong) static version numbers in the setup-*.py file. Keep that in mind when generating packages for previous versions.
- sumolib misses `pyproj` as an extra dependency
- some standard files are missing: README and (possibly) LICENSE
- the calls to `setup()` may lack some information: description or long_description (could be read from README)
