### ISSUE TITLE
SUMO 1.1.0 <-> VTD 2.2 Error: tcpip::Storage::readIsSafe: want to read 4 bytes from Storage, but only 0 remaining

### ISSUE THREAD

**Issue by Zimmermann-Daimler** [eclipse/sumo#5227]
Hello,

I am using SUMO to feed VTD with microscopic traffic data. After I updated SUMO from 0.32 to 1.1.0 I got the following error:

`Error: tcpip::Storage::readIsSafe: want to read 4 bytes from Storage, but only 0 remaining`

The Error occurs after SUMO loads all files and gets the start signal from VTD. It still occurs even if no vehicles are loaded.

Is this a known Issue?

Thank you for your help

My OS is  OpenSUSE Leap 42.3.

My sumo-gui config file:
```<?xml version="1.0" encoding="iso-8859-1"?>
<configuration>
   <input>
      <net-file value="streets.net.xml"/>
      <remote-port value="8813"/>
   </input>
     
   <processing>
      <time-to-teleport value ="120"/>
      <max-depart-delay value ="-1"/>
   </processing>	
</configuration>
```
Here is the configuration from the modulemanager.xml for VTD:
```
[...]
<Sensor name="sumo" type="video">
   <Load lib="libModuleSUMOGateway.so" path="" persistent="" />
   <Port name="SUMOout" number="8813" type="TCP" sendEgo="true" client="true" server="127.0.0.1" />
   <Port name="RDBout" number="49175" type="TCP" sendEgo="false" />
   <SUMO radiusIn="500.0" radiusOut="550.0" 
         radiusFar="700.0" verbose="false" showTrace="false" sendVehicleFrontEdge="true" 
         pathEndAction="delete" startArgs="GUI.sumo.cfg"
         globalHdgOffsetDeg="-90.0" globalHdgScale="-1" />
   <Player default="true" />
   <Filter objectType="vehicle" />
   <Config useSyncMask="true" showTiming="false" useOpenDriveLanes="true" 
         synchronizeInit="true" crateExternalEntities="false" />
   <Debug enable="false" />
</Sensor>
[...]
```

Please let me know if you need more information.

**Comment by namdre** [comment]
There were some modifications to the TraCI protocoll in version 1.0.0 (see the TraCI section of  https://sumo.dlr.de/wiki/ChangeLog#Other_4).
If you are using a custom client you need to patch it. 
Alternatively, you can use one of the provided client librarires (python, C++, Java) which come with the latest SUMO version to achieve compatibility.
