### ISSUE TITLE
Cannot reference route from additionals

### ISSUE THREAD

**Issue by tkchouaki** [eclipse/sumo#5232]
The following setting doesn't work : 
A *routes.rou.xml* file containing
```xml
<routes>
<route id="route1" edges="e1 e2 e3" />
</routes>
```
A *rerouters.add.xml* containing
```xml
<additonal>
<rerouter id="rerouter1" edges="e1">
<interval begin="0" end="3600">
<routeProbReroute id="route1"/>
</interval>
<rerouter>
</additional>
```

Sumo says that route1 doesn't exist

**Comment by palvarezlopez** [comment]
Hello,

you need to load first the routes.rou.xml file before rerouters.add.xml

**Comment by tkchouaki** [comment]
I am already doing so

**Comment by namdre** [comment]
please post the contents of your .sumocfg file

**Comment by tkchouaki** [comment]
Here's the content of the .sumocfg file:

```xml
<configuration>
    <net-file value="net.net.xml"/>
    <route-files value="routes.rou.xml" />
    <additional-files value="rerouters.add.xml" />
</configuration>
```
This leads to the following message from SUMO

```
Loading configuration... done.
Loading net-file from '/media/tarekchouaki/104C12C0104C12C0/sumoWork/Examples/bug/net.net.xml'... done (1ms).
Loading additional-files from '/media/tarekchouaki/104C12C0104C12C0/sumoWork/Examples/bug/rerouters.add.xml'... 
Error: MSTriggeredRerouter rerouter1: Route 'route1' does not exist.
Loading of additional-files failed.
Quitting (on error).
```

This obliges me to move the definition of the route to the file where the rerouter is defined.

I recall the contents of the other files : 
**routes.rou.xml** : 
```xml
<routes>
    <route id="route1" edges="e1 e2 e3" />
</routes>
```

**rerouters.add.xml**
```xml
<additional>
    <rerouter id="rerouter1" edges="e1">
        <interval begin="0" end="3600">
            <routeProbReroute id="route1"/>
        </interval>
    </rerouter>
</additional>
```

**Comment by namdre** [comment]
load the files like this:  `<additional-files value="routes.rou.xml,rerouters.add.xml" />`
For an explanation, see https://sumo.dlr.de/wiki/SUMO#Loading_order_of_input_files

**Comment by tkchouaki** [comment]
thank you for the answer
