### ISSUE TITLE
duarouter could NOT run with command line window

### ISSUE THREAD

**Issue by JaneCheung** [eclipse/sumo#5234]
Dear all,
While I was trying to use the duarouter.exe to generate the  rout for predefined **specified network and flow**, The massage  apppeard on my computer (Window10) 
Could someone help me to deal with this problem. **This kind problem has never appeared before.**
![image](https://user-images.githubusercontent.com/39317241/53306236-2c1abe00-3850-11e9-9d80-8c9b61950fc6.png)

**Comment by namdre** [comment]
Unfortunately, this windows error may have a large number of causes. Did you maybe try to run the 64bit version of SUMO on a 32bit version of Windows?

**Comment by JaneCheung** [comment]
I have downloaded the new one and the software could work appicately in the windows.

Thansks so much!
