### ISSUE TITLE
SUMO error for command 173: Lane area detector '' is not known

### ISSUE THREAD

**Issue by grazmand** [eclipse/sumo#5236]
Using TraCI Lane Area detectors, the Traas command conn.do_job_get(Lanearea.getLastStepVehicleIDs("yourdetector")) don't recongnize the ID detector, altough  specified in its relative additional file; indeed the following message appears on display:

SUMO error for command 173: Lane area detector '' is not known.

Moreover, in the statement under examination the output command is adequately casted to SumoStringList, so the assignment should be well done.

**Comment by namdre** [comment]
fixed in b0fddd3b2d217fd62239dd171bc23801f1cff9a8
