### ISSUE TITLE
vehicle type

### ISSUE THREAD

**Issue by shuowang572875852** [eclipse/sumo#5241]
I want to know what is the vehicle dynamics model equation for vehicles in sumo? Have you considered only longitudinal and lateral movements? Have you considered yaw and roll motion? Is there any related literature or source code reference?

**Comment by namdre** [comment]
yaw and roll are not modelled. 

Longitudinal dynamics depend mostly on the car-following model:
 - https://github.com/eclipse/sumo/tree/master/src/microsim/cfmodels
 - https://sumo.dlr.de/wiki/Definition_of_Vehicles,_Vehicle_Types,_and_Routes#Car-Following_Models
Lateral dynamics are only modelled when activating the sublane model:
 - https://sumo.dlr.de/wiki/Simulation/SublaneModel
