### ISSUE TITLE
edge attribute allow/disallow should be updated after using allow/disallow dialog

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#5242]
keeping the old value until re-inspecting the edge is very confusion.

**Comment by namdre** [comment]
unfortunately, this solution creates a noticable slow-down when undo/redoing a big changeset (e.g. deleting lots of objects).

**Comment by palvarezlopez** [comment]
@namdre Yes, it's a better alternative.

**Comment by namdre** [comment]
here is how to freeze netedit:
- open up a large network (e.g. tests/tools/import/OSM/webWizard/osmimport.tools
- select half the edges in the network 
- delete
- undo 
- inspect the selection
- press redo + undo

**Comment by palvarezlopez** [comment]
@namdre I think this problem is't caused by the solution, but is another different bug.
