### ISSUE TITLE
the generate of different types vehicles with duratouter

### ISSUE THREAD

**Issue by JaneCheung** [eclipse/sumo#5243]
Dear all ,
While I was using the durouter.exe to generate the vehicle with different VtypesDistribution. There is no type ID contained in the route files. Is something wrong that I used the DURATER.exe ?

duarouter.exe    -c H:\sf\flow\flow2route.sumocfg -n  H:\sf\network\net.net.xml   -r   H:\sf\flow\od.flow.xml   -a H:\sf\additional\vTypeDistributions.add.xml  -o   H:\sf\rou\od.rou.xml

Best regards!

Jane

**Comment by namdre** [comment]
your input file od.flow.xml must reference the vTypeDistribution id  as explained here: https://sumo.dlr.de/wiki/Definition_of_Vehicles,_Vehicle_Types,_and_Routes#Vehicle_Type_Distributions
