### ISSUE TITLE
Losing stop signs using netconvert

### ISSUE THREAD

**Issue by zyrgit** [eclipse/sumo#5244]
I have a question about importing stop signs (allway_stop/priority_stop) from OSM data into net.xml file using netconvert. Currently "allway_stop/priority_stop" property can only be added/enforced when building node files from scratch, if I try to convert from OSM data into SUMO net file, the nodes lose stop sign information. I can not modify net.xml to change junction type from "priority" to "allway_stop", that does not work. Testing from sumo-gui, I see correct stop signs only when building the network from scratch (node.xml,edge.xml,connection.xml, etc). How can I preserve correct stop signs at junctions when using netconvert? Thanks for any tips!

**Comment by namdre** [comment]
-  You can use NETEDIT to set junction types to "allway_stop" or "priority_stop". Using select mode you could even mass-convert all junctions of the same type with a few clicks. See 
https://sumo.dlr.de/wiki/NETEDIT#Methods_for_selecting
https://sumo.dlr.de/wiki/NETEDIT#Inspect

- alternatively, you can load a patch file along with the initial OSM import: https://sumo.dlr.de/wiki/Tutorials/ScenarioGuide#Example:_Patching_the_type_of_a_node

Further, we are aware that no all information from OSM is currently used so this ticket duplicates an existing one: #2257

**Comment by zyrgit** [comment]
Thanks a lot!
