### ISSUE TITLE
TraCI

### ISSUE THREAD

**Issue by shuowang572875852** [eclipse/sumo#5249]
I understand that TRACI is an external control interface that is used to control or change the value or attribute of the original quantity in SUMO. For attributes defined in SUMO, such as considering vehicle yaw and roll, whether it is necessary to define parameters in the vehicle properties before external control through the TRACI interface. At this stage, we want to use Matlab to construct a vehicle dynamics model that considers the yaw and roll. By interacting with SUMO through TRACI4MATLAB, do we need to define the vehicle properties first in SUMO. Has anyone done this? Or through TraaS, use SUMO as a server, matlab as a client, need to define vehicle properties in advance?

**Comment by namdre** [comment]
If your vehicle model is defined in matlab and connected via TraCI, you can use the commands vehicle.setParameter and vehicle.getParameter to track arbitrary new attributes for the vehicles. 
Note, that the network model also does not consider road values such as superelevation and crossfall
