### ISSUE TITLE
add attribute 'detectPedestrians' to various output definitions

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#5252]
- [x] edgeData / laneData (#3666)
- [x] e1Detector
- [x]  e2Detector
- [x]  e3Detector
- ~~[ ] routeProbe~~ (persons do not have route ids in general. Walks only store an edge list even when specified with a route id)

**Comment by palvarezlopez** [comment]
@namdre also in NETEDIT?

**Comment by namdre** [comment]
Yes. Eventually after the simulation functionality is ready.

**Comment by namdre** [comment]
Adapting detectors that rely on notifyMove is considerably more involved. Do we really want every pedestrian to keep track of it's own movereminders?

**Comment by namdre** [comment]
pedestrian model nonInteracting is inactive while traversing a single edge. Possible the detectors that wish to register persons should actively collect persons on their lane rather than using moveReminders.
