### ISSUE TITLE
Netedit: Recomputed connections change shape significantly

### ISSUE THREAD

**Issue by m-kro** [eclipse/sumo#5254]
For some relations / big radii, connection shapes may differ visibly from the geometry drawn before a recompute command was issued. Example screenshots are attached below.

1. The cyan connections have just been added.
![image](https://user-images.githubusercontent.com/33294728/53754814-56eebd00-3eb5-11e9-9072-0a30bc0d4d84.png)

2. How they look like after a recompute operation or when saving the network. Looks a bit like an ill-formed basket arch...
![image](https://user-images.githubusercontent.com/33294728/53754881-7ede2080-3eb5-11e9-93f4-de5c985fcbec.png)

**Comment by namdre** [comment]
I think this is caused by a feature in 1.0.0 which intends to avoid intersecting left turns. You can comment out NBNode.cpp line 713 and check if the problem goes away. 
I'm open for suggestions on how to make this work better / configurable.

**Comment by m-kro** [comment]
I can confirm that it is due to the  AVOID_WIDE_LEFT_TURN mode.
