### ISSUE TITLE
traci getNextStop() : stopFlag not chaging-

### ISSUE THREAD

**Issue by tkchouaki** [eclipse/sumo#5260]
Hello : 
I tried with a newtork composed of three chained edges e1 -> e2 -> e3 that respectively contain the busStops 1, 2 and 3.
The content of the route file is as follows:
```xml
<routes>
    <vType id="bus" vClass="bus"/>
    <route id="1" edges="e1 e2 e3">
        <stop busStop="1" duration="10"/>
        <stop busStop="2" duration="10"/>
        <stop busStop="3" duration="10"/>
    </route>
    <person departPos="0" id="1" depart="0">
        <walk from="e1" busStop="1"/>
        <ride busStop="3" modes="public" lines="1"/>
        <stop busStop="3" duration="30"/>
    </person>
    <vehicle id="bus1" route="1" type="bus" depart="100" line="1"/>
</routes>
```
And the bus stops are defined in the additional file:
```xml
<additional>
    <busStop id="1" lane="e1_1" lines="1" startPos="112.20" endPos="122.20"/>
    <busStop id="2" lane="e2_1" lines="1" startPos="100.95" endPos="110.95"/>
    <busStop id="3" lane="e3_1" lines="1" startPos="66.96" endPos="76.96"/>
</additional>
```

I run the simulation via traci with the following code :
```python
traci.start([binary, "-c", conf_path])
    while traci.simulation.getMinExpectedNumber() > 0:
        ids = traci.vehicle.getIDList()
        if bus_id in ids:
            stops = traci.vehicle.getNextStops(bus_id)
            if len(stops) > 0:
                next_stop = stops[0]
                print(next_stop[3])
        traci.simulationStep()
    traci.close()
```

The problem is that the stopFlag that i get is always 17, which, according to the documentation means stopped & isBusStop. It seems it doesn't depend on if there's a person that will exit the bus at the next stop.

**Comment by namdre** [comment]
getNextStops always returns upcoming stops (excluding the current one) so the first bit should always be 0 (now fixed).
However, there is no model for demand-responsive stopping. The vehicles will always stop (to pick up potential passengers).

**Comment by tkchouaki** [comment]
It was effectively my objective to implement demand-responsive stopping, for this i had to check if there was any person in the next stop (using traci.simulation.getBusStopWaiting(bus_stop_id)). 

But i had also to check if any loaded person was going to the next stop. Since the personTriggered flag didn't work, i had to check the current stage of all the loaded persons & see if it is a driving stage & if it's destination edge is the same as the bus stop's

**Comment by namdre** [comment]
Thanks for sharing!
attribute 'triggered' only imposes a condition on ending a stop (e.g. to pick up specific persons for ride sharing).
