### ISSUE TITLE
invalid tls connections after adding sidewalks via 'add special lane'

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#5264]

**Comment by palvarezlopez** [comment]
@namdre Recomputing Network doesn't fix the problem?

**Comment by namdre** [comment]
No. only deleting and recreating the tls helps.


A quick fix would be to add 
  myGNEJunctionSource->setLogicValid(false, undoList);
  myGNEJunctionDestiny->setLogicValid(false, undoList);
in GNENet::duplicateLane (the same happens when setting attr numLanes)

A better solution would be the thing netconvert does:
When netconvert adds sidewalks there is explicit code for shifting the tls connections (NBEdge.cpp:3504)

Netedit would need to do the same and take care of the undoList at the same time (should be doable with one GNEChange_TLS to replace the old tls with an updated version)

I think the correct place for that code would also be GNENet::dupliateLane
