### ISSUE TITLE
crosswalk distorted and disconnected in left hand setting

### ISSUE THREAD

**Issue by xpharry** [eclipse/sumo#5265]
Here is the link to the code showing the issue:
[link](https://www.dropbox.com/sh/3878ms4n7vo7qnw/AAB_IuXK_XLKPaEP2PxKduY0a?dl=0)

I created an intersection scenario in left hand traffic. The crosswalk in this setting becomes wired as the sidewalks cannot connect by the crosswalk correctly and the crosswalks are aligned with diagonal direction.

![lefthand](https://user-images.githubusercontent.com/8265866/53911676-fb831300-400b-11e9-8263-4a7ac3d081a2.png)

Everything in right hand setting seems to be ok.

**Comment by namdre** [comment]
as a quick work-around you can fix the network by calling
`netconvert -s distorted.net.xml -o correct.net.xml`

**Comment by xpharry** [comment]
@namdre 
WoW. It works. I was so close. Thanks!

**Comment by namdre** [comment]
Not it also works with Netedit
