### ISSUE TITLE
allow moving whole polygons

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#5268]
In move mode, If a polygon is selected the whole polygon should be moved.

**Comment by palvarezlopez** [comment]
@namdre The Netedit attribute "block shape" is used to move whole polygon instead a single vertex.

**Comment by namdre** [comment]
This works. However,
- the help button for 'Netedit attributes' (including 'block shape') doesn't do anything
- since this functionality is not easily discoverable it should at least be documented at https://sumo.dlr.de/docs/NETEDIT.html#move

**Comment by palvarezlopez** [comment]
Add checkbox in GNEMoveFrame
