### ISSUE TITLE
The z coordinate will be not updated after using moveToXY with keepRoute = 2. 

### ISSUE THREAD

**Issue by ichtreenewbee** [eclipse/sumo#5269]
this happens by manipulating the behaviour of ego "on-line" with C++TraCIAPI. 
I want to get values from surrounding objects of a ego vehicle but the z coordinate is zeor after using moveToXY with keepRoute = 2.
Than no value will be retrieved if the actual x coordinate is greater than context range.

**Comment by namdre** [comment]
- what version of SUMO did you use?
- is the vehicle being moved outside the road area? 
- what is the z coordinate at the nearest road position?
- what is the z coordinate of the vehicle before calling moveToXY?

**Comment by ichtreenewbee** [comment]
•what version of SUMO did you use?
SUMO version is 1.0.1
•is the vehicle being moved outside the road area?
vehicle is in the road area.  The road-ID will be retrieved with TraCIAPI::VehicleScope::getRoadID after calling moveToXY and the ID is right.
•what is the z coordinate at the nearest road position?
There are only one road from "0.00,1.75" to "1000.00,1.75,350.00"(ego begin from the top of the road and will use the x,y-coordinats from client) 
•what is the z coordinate of the vehicle before calling moveToXY?
the z coordinate is 350 before calling moveToXY (ego begin from the top of the road and will use the x,y-coordinats from client)

**Comment by ichtreenewbee** [comment]
![capture](https://user-images.githubusercontent.com/47788125/53966657-dd90dd80-40f3-11e9-9c1c-1ed0aedc3773.PNG)

**Comment by namdre** [comment]
are you maybe retrieving the coordinate with vehicle.getPosition? in this case z will alway be 0.
Instead you need to use vehicle.getPosition3D.

Note, that there was another bug affecting moveToXY in networks with significant elevation changes: #5272 but I don't think it is responsible for your symptoms

**Comment by ichtreenewbee** [comment]
![08032019](https://user-images.githubusercontent.com/47788125/54029645-6b7ad000-41a9-11e9-82e5-4bc9a75ea077.PNG)
three methods are used to retrieve the position of vehicles, 1. vehicle.getPosition 2. vehicle.getPosition3D and 3. vehicle.subscribeContext with variable 0x39
The blue car is the ego and the other is the fellow.
The position of the Fellow is retrieved with vehicle.subscribeContext.
As the picture shows, the z-coordinate of the fellow is correct and the fellow brakes now. That means the fellow knows there's a car in front of him. But the z coordinate of ego is zero.

**Comment by namdre** [comment]
Then I'll need your input files to reproduce this on my end. My own test didn't trigger the problem.

**Comment by ichtreenewbee** [comment]
![08032019_2](https://user-images.githubusercontent.com/47788125/54037356-43e23280-41be-11e9-8c6d-5909ae18fffe.PNG)
Sorry i must not share anything about my work.
The z coordinate is not updated after calling moveToXY
But if SUMO simulate forward the z coordinate will be generated.

**Comment by namdre** [comment]
This was a bug in 1.1.0 which I already forgot about (#5039). Please use the latest development version.
