### ISSUE TITLE
DriverState not initialised when adding MSDevice_DriverState via TraCI

### ISSUE THREAD

**Issue by m-kro** [eclipse/sumo#5271]
I had in mind to add the DriverState device via TraCI in order to better automate it in my script when using different scenarios. I enable it in the vehicle type like that:
`traci.vehicletype.setParameter(myVehType, 'has.driverstate.device', 'true')`
SUMO crashes when accessing DriverState device properties through TraCI. After some debugging, I have seen the following:

- The MSDevice_DriverState constructor gets called
- A callback to MSDevice_DriverState::createDriverState for the DriverState initialisation is set but never executed
- SUMO crashes because of a non-initialised DriverState when requesting for example the initialAwareness property

I have compiled a small example scenario with a TraCI script:
[addDriverState.zip](https://github.com/eclipse/sumo/files/2941644/addDriverState.zip)

**Comment by m-kro** [comment]
The callback defined in MSDevice_DriverState.cpp:171 is never executed because it disappears (?) from the MSEventControl. When MSEventControl::execute is called the next time, there is no DriverState_Device Event anymore?!

**Comment by namdre** [comment]
I think the initialization code can be rewritten to be much simpler and avoid MSEventControl alltogether.
