### ISSUE TITLE
Can we implement mutual person flows in one side walk?

### ISSUE THREAD

**Issue by xpharry** [eclipse/sumo#5273]
It is doable to implement a flow of pedestrians in one direction,

```
<vType id="pedestrian" length="1.8" width="0.8" maxSpeed="1.4" accel="0.8" decel="1.5" sigma="0.5" speedDev="0.5" vClass="pedestrian"/>

<flow id="pedestrian_WE" type="pedestrian" begin="0" end="1000" probability="0.2" from="WC" to="CE"/>
```

But I cannot add another reversed flow in the same side walk.

All I can do it to use <person> to add pedestrians one by one if I want to use a reversed direction.

```
  <person id="ped0" depart="4.00" departPos="random">
      <walk from="CW" to="EC" arrivalPos="random"/>
  </person>
```

Is there any way to crate a flow in both direction in the sidewalk? 

I saw a similar issue #1515, but this one is never completed yet.

**Comment by namdre** [comment]
you can either use
 sumo/tools/pedestrianFlow.py ped.rou.xml --trip FROM,TO -p PROBABILYT
or od2trips: https://sumo.dlr.de/wiki/Demand/Importing_O/D_Matrices#Generated_traffic_modes

Note, that a <flow> with vClass="pedestrian" will behave very different from regular persons (it will still use the vehicle movement model).
