### ISSUE TITLE
duaIterate.py 

### ISSUE THREAD

**Issue by shuowang572875852** [eclipse/sumo#5277]
I:\浮动车数据处理\复杂路网构建>python F:\SUMO\tools\assign\duaIterate.py -n shen
gzhen.net.xml -t shengzhen_valid.trips.xml -l 3
> Executing step 0
>> Running router on shengzhen_valid.trips.xml
>>> Begin time: 2019-03-07 15:48:53.561150
Loading configuration... done.
>>> End time: 2019-03-07 15:49:42.835968
>>> Duration: 0:00:49.274818
<<
>> Running simulation
>>> Begin time: 2019-03-07 15:49:42.835968
>>> End time: 2019-03-08 10:08:47.685027
>>> Duration: 18:19:04.849059
<<
< Step 0 ended (duration: 3 days, 22:40:14.585670)
Traceback (most recent call last):
  File "F:\SUMO\tools\assign\duaIterate.py", line 684, in <module>
    main()
  File "F:\SUMO\tools\assign\duaIterate.py", line 666, in main
    sys.stdout.flush()
  File "F:\software\sumo\tools\sumolib\__init__.py", line 201, in flush
    fp.flush()
PermissionError: [Errno 13] Permission denied
Exception ignored in: <sumolib.TeeFile object at 0x02BE1370>
Traceback (most recent call last):
  File "F:\software\sumo\tools\sumolib\__init__.py", line 201, in flush
    fp.flush()
PermissionError: [Errno 13] Permission denied

how can i do for it?

**Comment by namdre** [comment]
The duaIterator.py script tries to write log files into the current working directory of the python process. Please make sure that you are calling it from a directory where you have write access.
