### ISSUE TITLE
Bug osmWebWizard no option with the name --write-trips

### ISSUE THREAD

**Issue by roemil** [eclipse/sumo#5288]
Error : On processing option '--write trips': No option with the name --write-trips exists.

I solved it by removing the option in randomTrips.py

From:  args2 = args + ['-o', tmpTrips, '--write-trips']
To: 
        args2 = args + ['-o', tmpTrips]

**Comment by namdre** [comment]
you are using the development version of webWizard with an older version of duarouter. The most likely reason is that your SUMO_HOME variable points to an older SUMO version (this is how webWizard finds duarouter).
