### ISSUE TITLE
Support for PROJ 6.0.0

### ISSUE THREAD

**Issue by sebastic** [eclipse/sumo#5299]
SUMO still uses `proj_api.h` which is deprecated in PROJ 6.0.0 and will be removed in PROJ 7.0.0 (scheduled for March 2020).

When using `proj_api.h` with PROJ 6.0.0 `-DACCEPT_USE_OF_DEPRECATED_PROJ_API_H=1` needs to be added to `CFLAGS` to prevent a compiler error.

SUMO should be updated to (also) support the `proj.h` API.

**Comment by behrisch** [comment]
@sebastic So the correct way would be to first check for the presence of proj.h and if this is not there use proj_api.h?

**Comment by sebastic** [comment]
Yes. Ideally your code is compatible with all major PROJ releases used by users.

PROJ 6 is a major change, and many projects will take significant time to become compatible, so PROJ 5.x will be included in distributions for quite some time.

PROJ 4.x is also still widely used, but will slowly be phased out.
