### ISSUE TITLE
bug in F:\Eclipse\Sumo\tools>generateParkingLots.py -b 2560,2708,2660,3318  -c 48_1_1  -i  48_1 -n  154  -l  4   -a  110 F:\Eclipse\Sumo\tools\sumolib\__init__.py:28: UserWarning: No module named matplotlib   warnings.warn(str(e))

### ISSUE THREAD

**Issue by JaneCheung** [eclipse/sumo#5300]
when using the generateParkingLot.py
There is something wrong
：
**F:\Eclipse\Sumo\tools>generateParkingLots.py -b 2560,2708,2660,3318  -c 48_1_1  -i  48_1 -n  154  -l  4   -a  110
F:\Eclipse\Sumo\tools\sumolib\__init__.py:28: UserWarning: No module named matplotlib
  warnings.warn(str(e))**

How to deal with this problem?

**Comment by namdre** [comment]
This is just a warning. Other tools rely on matplotlib but you can ignore the warning if you don't need those.
