### ISSUE TITLE
Wrong file saved when clicking on "Save additionals Ctrl+Shft+D" in Netedit

### ISSUE THREAD

**Issue by ZoltanBaksa** [eclipse/sumo#5301]
I load an additional file with the menu item File->Additionals and shapes->Load Additionals
After I have made some modifications I save it with Save Additionals menu element, but not the originally loaded file is overwritten, but the last set filename. In case I use the Save additionals as menu before, the name in Save Additionals remembers to this name instead of the newly loadaed one.
This could lead to unexpected overwrite of previously edited, but currently not loaded files.

**Comment by palvarezlopez** [comment]
Thanks! I check it.

**Comment by ZoltanBaksa** [comment]
The problem is not solved correctly, now tested in v1_1_0+1745-468bbad8d0
The current problem is, when I load an additional (containing <additionals> root tag) or demand file (containing <routes>). When I save the file with 'save as' the content is saved to the given file, but any further change I make cannot be saved because the 'save' menu option is grey, the 'save as' menu option will produce following error type:
Error: A value for the option 'additional-files' | 'route-files' was already set.
 Possible synonymes: a, additional | r, routes

**Comment by palvarezlopez** [comment]
Fixed in f9b89634f535253093d071ec019b889a6244ba37
