### ISSUE TITLE
traci.vehicle.getAcceleration

### ISSUE THREAD

**Issue by shuowang572875852** [eclipse/sumo#5304]
I want to add the MOBIL lane change model to SUMO, which needs to get the current vehicle acceleration，the new acceleration for current vehicle after a prospective lane change , the target lane follow vehicle acceleration  and the new acceleration for the target lane follow vehicle  after a prospective lane change . And how to get those acceleration?

**Comment by namdre** [comment]
traci.vehicle.getAcceleration returns current acceleration

to get leader and follower vehicles on the target lane:
traci.vehicle.subscribeContext(...)
followed by
traci.vehicle.addSubscriptionFilterLeadFollow(lanes)
where lanes is a list of relative lanes indices to check (-1, 0, 1)

There is currently no support to retrieve hypothetical acceleration via TraCI (#3361)

**Comment by shuowang572875852** [comment]
I want to get the acceleration of the vehicle at each time step. Since the input parameter for obtaining acceleration is the vehicle ID, I obtained the vehicle ID for each time step, but the following error was obtained . The follows are my codes :

clc;
clear all;
import traci.constants
scenarioPath=['F:\software\SUMO配置文件\bin\quickstart\quickstart.sumocfg'];
system(['sumo-gui -c ' '"' scenarioPath '"' ' --remote-port 8813 --start&']);
traci.init

SIM_STEPS = [1 900];
beginTime = SIM_STEPS(1);
duration =  SIM_STEPS(2);
endTime =  SIM_STEPS(1) +  SIM_STEPS(2) - 1;

for i = 1: duration
    traci.simulation.step();
   IDList{i} = traci.vehicle.getIDList();
   accel{i}=traci.vehicle.getAcceleration(IDList);
end
traci.close()

I   used the traci4matlab and the above  are  my  codes , the ''duration'' is the "simulation duration time ",the error logs are :

error use  uint8
Unable to convert from cell to uint8.

error  traci.beginMessage (line 23)
		traci.packInt32(length(objID)) uint8(objID)];

error  traci.sendReadOneStringCmd (line 10)
traci.beginMessage(cmdID, varID, objID);

error  traci.vehicle.getUniversal (line 21)
result = traci.sendReadOneStringCmd(constants.CMD_GET_VEHICLE_VARIABLE,varID,vehID);

error   traci.vehicle.getAcceleration (line 12)
accel = traci.vehicle.getUniversal(constants.VAR_ACCELERATION, vehID);

error  quickstart (line 19)
   accel{i}=traci.vehicle.getAcceleration(IDList);

**Comment by shuowang572875852** [comment]
I  have got the current vehicle acceleration for every step , but wen i use the   traci.vehicle.addSubscriptionFilterLeadFollow(lanes)  got errors, the following are my codes(I used traci4matlab) : 

clear
close all
clc
import traci.constants
scenarioPath=['F:\software\SUMO配置文件\bin\quickstart\quickstart.sumocfg'];
system(['sumo-gui -c ' '"' scenarioPath '"' ' --remote-port 8813 --start&']);
traci.init

SIM_STEPS = [1 900];
beginTime = SIM_STEPS(1);
duration =  SIM_STEPS(2);
endTime =  SIM_STEPS(1) +  SIM_STEPS(2) - 1;

for i = 1:duration
    traci.simulation.step();

  IDList{i,1} = traci.vehicle.getIDList();
  
  for j=1:length(IDList{i,1})
%       vehicle{i,1}(j,1:end)=char(IDList{1,1}(j,1))
      accel{i,1}(j)=traci.vehicle.getAcceleration(char(IDList{i,1}(1:end,j)));
      laneID{i,1}=traci.vehicle.getLaneID(char(IDList{i,1}(1:end,j)));
       traci.vehicle.addSubscriptionFilterLeadFollow(char(laneID));
  end
  
end
traci.close()

the sumo-gui errors are :
warning: addSubscriptionFilter : No previous vehicle context  subscription exists to apply the context filter.
Error: Answered with error to command 0x7e :  Wrong position in requestMessage after dispatching command. Expected command length was 3 but 2 Bytes  were read.

And for  subscribeContext(vehID, domain, dist, varargin) ,what are (domain, dist, varargin)  and how to use it to  get  the  leader and follower vehicles on the target lane.

**Comment by namdre** [comment]
you can only add a subscription filter after calling subscribe context
to get vehicles position and speed  in a 150m radius around ego, call
subscribeContext(egoID, traci.constants.CMD_GET_VEHICLE_VARIABLE, {traci.constants.VAR_POSITION, traci.constants.VAR_SPEED})

**Comment by shuowang572875852** [comment]
Thanks for your reply ,I have run success ,and generated the "positionspeed" files, for one timestep: 

 <timestep time="54000.00">
        <edge id="D2">
            <lane id="D2_0">
                <vehicle id="veh0" pos="5.10" speed="0.00"/>
            </lane>
            <lane id="D2_1"/>
        </edge>
        <edge id="D4">
            <lane id="D4_0">
                <vehicle id="veh3" pos="5.10" speed="0.00"/>
            </lane>
            <lane id="D4_1"/>
        </edge>
        <edge id="D6">
            <lane id="D6_0">
                <vehicle id="veh6" pos="5.10" speed="0.00"/>
            </lane>
            <lane id="D6_1"/>
        </edge>
        <edge id="D8">
            <lane id="D8_0">
                <vehicle id="veh9" pos="5.10" speed="0.00"/>
            </lane>
            <lane id="D8_1"/>
        </edge>
    </timestep>

Is the lane ID "D2_1, D4_1,D6_1,D8_1 " the surrounding lane ID of the current vehicle? For traci.vehicle.addSubscriptionFilterLeadFollow(lanes), the input parameters are above lane IDs?But how to get only lane IDs for it ?And how to use position and speed to  get the acceleration?

**Comment by shuowang572875852** [comment]
Thanks for your reply ,I have run success ,and generated the "positionspeed" files, for one timestep:

<timestep time="54000.00">
        <edge id="D2">
            <lane id="D2_0">
                <vehicle id="veh0" pos="5.10" speed="0.00"/>
            </lane>
            <lane id="D2_1"/>
        </edge>
        <edge id="D4">
            <lane id="D4_0">
                <vehicle id="veh3" pos="5.10" speed="0.00"/>
            </lane>
            <lane id="D4_1"/>
        </edge>
        <edge id="D6">
            <lane id="D6_0">
                <vehicle id="veh6" pos="5.10" speed="0.00"/>
            </lane>
            <lane id="D6_1"/>
        </edge>
        <edge id="D8">
            <lane id="D8_0">
                <vehicle id="veh9" pos="5.10" speed="0.00"/>
            </lane>
            <lane id="D8_1"/>
        </edge>
    </timestep>

Is the lane ID "D2_1, D4_1,D6_1,D8_1 " the surrounding lane ID of the current vehicle? For traci.vehicle.addSubscriptionFilterLeadFollow(lanes), the input parameters are above lane IDs?But how to get only lane IDs for it ?And how to use position and speed to get the acceleration?

**Comment by shuowang572875852** [comment]
<timestep time="54000.00">
        <edge id="D2">
            <lane id="D2_0">
                <vehicle id="veh0" pos="5.10" speed="0.00"/>
            </lane>
            <lane id="D2_1"/>
        </edge>
        <edge id="D4">
            <lane id="D4_0">
                <vehicle id="veh3" pos="5.10" speed="0.00"/>
            </lane>
            <lane id="D4_1"/>
        </edge>
        <edge id="D6">
            <lane id="D6_0">
                <vehicle id="veh6" pos="5.10" speed="0.00"/>
            </lane>
            <lane id="D6_1"/>
        </edge>
        <edge id="D8">
            <lane id="D8_0">
                <vehicle id="veh9" pos="5.10" speed="0.00"/>
            </lane>
            <lane id="D8_1"/>
        </edge>
    </timestep>

**Comment by shuowang572875852** [comment]
Thanks for your reply ,I have run success ,and generated the "positionspeed" files, for one timestep:
 <edge id="D2"><lane id="D2_0"><vehicle id="veh0" pos="5.10" speed="0.00"/>
  </lane><lane id="D2_1"/></edge>
Is the lane ID "D2_1 " the surrounding lane ID of the current vehicle? For traci.vehicle.addSubscriptionFilterLeadFollow(lanes), the input parameters are above lane IDs?But how to get only lane IDs for it ?And how to use position and speed to get the acceleration?

**Comment by shuowang572875852** [comment]
Thanks for your reply ,I have run success ,and generated the "positionspeed" files, for one timestep:
 <edge id="D2"><lane id="D2_0"><vehicle id="veh0" pos="5.10" speed="0.00"/>
</lane><lane id="D2_1"/></edge>
Is the lane ID "D2_1 " the surrounding lane ID of the current vehicle? For traci.vehicle.addSubscriptionFilterLeadFollow(lanes), the input parameters are above lane IDs?But how to get only lane IDs for it ?And how to use position and speed to get the acceleration?

**Comment by shuowang572875852** [comment]
Thanks for your reply ,I have run success ,and generated the "positionspeed" files, for one timestep:
Is the lane ID "D2_1 "  after the current vehicle position speed is the surrounding lane ID ? For traci.vehicle.addSubscriptionFilterLeadFollow(lanes), the input parameters are above lane IDs?But how to get only lane IDs for it ?And how to use position and speed to get the acceleration?

**Comment by namdre** [comment]
lanes designate relative lane offsets. e.g. {-1} or {1, -1}

**Comment by shuowang572875852** [comment]
Thanks for your reply, I don't understand it means ,can you help me answer the above question?For traci.vehicle.addSubscriptionFilterLeadFollow(lanes), the input parameters are the surrounding lane IDs?But how to get only lane IDs for it ?And how to use position and speed to get the acceleration?

**Comment by namdre** [comment]
The inpurt parameters for traci.vehicle.addSubscriptionFilterLeadFollow(lanes) are NOT the lane IDs.
Instead you filter on relative indices.
To get only vehicles on the left lane of the ego vehicle. use traci.vehicle.addSubscriptionFilterLeadFollow({1})
To get only vehicles on the right lane of the ego vehicle. use traci.vehicle.addSubscriptionFilterLeadFollow({-1})

The subscription call will always return the IDs of the surrounding vehicles (it doesn't have to be specified in the variables list).
To get the acceleration, you can just call vehicle.getAcceleration(surroundingVehicleID).

**Comment by shuowang572875852** [comment]
Thanks for your reply ,the  traci.vehicle.addSubscriptionFilterLeadFollow input must be the string or cellular array,so i modified into traci.vehicle.addSubscriptionFilterLeadFollow('1') and run success. But the output files are the lanechange output attribute and how to return the surrounding vehicles?Looking forward to your reply.

**Comment by namdre** [comment]
Please show the code of the prior contextSubscription call
(this should be right before the addSubscription call).

**Comment by shuowang572875852** [comment]
for i = 1:duration
    traci.simulation.step();
  IDList{i,1} = traci.vehicle.getIDList(); 
  for j=1:length(IDList{i,1})
      accel{i,1}(j)=traci.vehicle.getAcceleration(char(IDList{i,1}(1:end,j)));
      laneID{i,1}=traci.vehicle.getLaneID(char(IDList{i,1}(1:end,j)));
      traci.vehicle.subscribeContext(char(IDList{i,1}(1:end,j)), traci.constants.CMD_GET_VEHICLE_VARIABLE,150,{traci.constants.VAR_POSITION, traci.constants.VAR_SPEED});
     traci.vehicle.addSubscriptionFilterLeadFollow('1');     
  end
end
traci.close()

**Comment by namdre** [comment]
to retrieve subscribed vehicles, you need to call traci.vehicle.getContextSubscriptionResults(egoID)

**Comment by shuowang572875852** [comment]
Thanks for your reply, I have add traci.vehicle.getContextSubscriptionResults(egoID), but the output “ans” is 1*1Map ,the follow is my code:

for i = 1:duration
    traci.simulation.step();
  IDList{i,1} = traci.vehicle.getIDList(); 
  for j=1:length(IDList{i,1})
      accel{i,1}(j)=traci.vehicle.getAcceleration(char(IDList{i,1}(1:end,j)));
      laneID{i,1}=traci.vehicle.getLaneID(char(IDList{i,1}(1:end,j)));
      traci.vehicle.subscribeContext(char(IDList{i,1}(1:end,j)), traci.constants.CMD_GET_VEHICLE_VARIABLE,150,{traci.constants.VAR_POSITION, traci.constants.VAR_SPEED});
     traci.vehicle.addSubscriptionFilterLeadFollow('1');    
     traci.vehicle.getContextSubscriptionResults(char(IDList{i,1}(1:end,j)));
  end
end

**Comment by namdre** [comment]
- your code looks as if you add subscriptions for the same vehicle in every step. This is not needed (this is the whole point of the 'subscription' concept)
- initially your vehicles will not have others in their surroundings so the map will not have any data. Please observe the state of  subscriptionResult via multiple steps.
- if it still doesn't work, please request help from pipeacosta@gmail.com (the author of traci4matlab)

**Comment by shuowang572875852** [comment]
Thanks for you reply , for my code
 "traci.vehicle.subscribeContext(char(IDList{i,1}(1:end,j)), traci.constants.CMD_GET_VEHICLE_VARIABLE,150,{traci.constants.VAR_POSITION, traci.constants.VAR_SPEED});"
the  char(IDList{i,1}(1:end,j)) represents the ID of all running vehicles in each time step ，so i think the  traci.vehicle.subscribeContext is right. And for  traci.vehicle.addSubscriptionFilterLeadFollow('1') ，whether need to add the vehicle IDs to filter the roads around ? To get  getContextSubscriptionResults ,
I have modified the code for get each vehicle ContextSubscriptionResults,the codes are as follows:

for i = 1:duration
    traci.simulation.step();
  IDList{i,1} = traci.vehicle.getIDList(); 
  for j=1:length(IDList{i,1})
      accel{i,1}(j)=traci.vehicle.getAcceleration(char(IDList{i,1}(1:end,j)));
      laneID{i,1}=traci.vehicle.getLaneID(char(IDList{i,1}(1:end,j)));
      traci.vehicle.subscribeContext(char(IDList{i,1}(1:end,j)), traci.constants.CMD_GET_VEHICLE_VARIABLE,150,{traci.constants.VAR_POSITION, traci.constants.VAR_SPEED});
     traci.vehicle.addSubscriptionFilterLeadFollow('1');    
    contextSubscriptionResults{i,1}{j}=traci.vehicle.getContextSubscriptionResults(char(IDList{i,1}(1:end,j)));
  end
end

The output  for every vehicle ID is a contextSubscriptionResults{1, 1}{1, 1}  cell ，It's content  as follows  
Count   1
KeyType   ''char''
ValueType  "any"

**Comment by shuowang572875852** [comment]
I want to know what results will be returned if getContextSubscriptionResults is running normally. In a case to get the current lane, the left lane, the right lane vehicle ID, enter traci.vehicle.addSubscriptionFilterLeadFollow('-1,0,1');

**Comment by namdre** [comment]
The idea of contextSubscriptions is to subscibe each vehicle once (e.g. when it enters the network).
Then you can collect the results in every subsequent time step as long as the vehicle remains in the network.
The whole point is to reduce communication by not having to send requests for every vehicle in every time step but rather to get them automatically.

the result of getContextSubscriptionResult should be restrict to the leader and follower vehicles on the vehicles current, right and left lane. This means at most 6 vehicles should be returned.

Are normal contextSubscriptions (without filtering) working for you?

**Comment by shuowang572875852** [comment]
Yes, I think for my problem don't need filtering. But the contextSubscriptions  inputs need the vehicle ID ,
and for getIDList return the vehicle ID as cell format, so must  change it for string format. So how to get them automatically.

**Comment by namdre** [comment]
Sorry, I'm not familiar with matlab. Maybe you could ask the aforementioned author of traci4matlab

**Comment by shuowang572875852** [comment]
Thank you very much for your previous reply， and I have asked the author of traci4matlab, but did not get a reply .Can you give me some help for it ? I want to know the contextSubscriptions is whether to subscribe a vehicle with vehicle ID ,when it enters the network until it left the network? But the travel time for each vehicle is different， so how to get each vehicles subscription? Can I add contextSubscriptions in a loop to get a subscription for every per time step ?

**Comment by behrisch** [comment]
@shuowang572875852 Please stop opening tickets concerning traci4matlab here. We cannot support it. We do not even have a matlab license. Please try the traci4matlab repo at https://github.com/pipeacosta/traci4matlab/issues.
