### ISSUE TITLE
Fix installation folder structure for OSX

### ISSUE THREAD

**Issue by schwamborn** [eclipse/sumo#5305]
After `brew install sumo`, the folder structure is currently

```
/usr/local/opt/sumo
├── bin
└── share
    └── sumo
        ├── bin -> ../../bin
        ├── data
        └── tools
```

This probably needs to be changed in `CMakeLists.txt`.

**Comment by behrisch** [comment]
I agree it looks a little confusing but what exactly goes wrong here?

**Comment by schwamborn** [comment]
The issue I found was when setting `export SUMO_HOME="/usr/local/opt/sumo"` and running, e.g., an OSM net conversion with 

```netconvert --osm-files map.osm.xml -o map.net.xml```

netconvert would look in SUMO_HOME for the `data` folder, which is, however, located in `$SUMO_HOME/share/sumo/` in this case. 

Setting `export SUMO_HOME="/usr/local/opt/sumo/share/sumo"` would also fix this issue but I'm wondering whether this folder structure is as intended.

**Comment by behrisch** [comment]
Maybe this is the way brew handles these things but under linux the structure does not have the additional opt/sumo so it installs directly into /usr/local/ (or even /usr when coming with the rpm / deb) and sets SUMO_HOME to /usr(/local)/share/sumo. So I would recommend to either adapt the install path to the way linux does it or if this is more in line with what brew does with other projects set SUMO_HOME as noted in the comment above.

**Comment by schwamborn** [comment]
Adapted note about `SUMO_HOME` path in homebrew formula to `/usr/local/opt/sumo/share/sumo`.
