### ISSUE TITLE
Get pedestrians position relative to ego vehicle.

### ISSUE THREAD

**Issue by ndeshp2s** [eclipse/sumo#5307]
Is it possible to get positions/orientation of pedestrians relative to my ego vehicle? I tried using the "subscribeContext", but it still gives the global position of the pedestrian.

I tried the following: 

traci.vehicle.subscribeContext(vehID, traci.constants.CMD_GET_PERSON_VARIABLE, 200.0, [traci.constants.VAR_POSITION])

**Comment by behrisch** [comment]
Why not simply subtract the position of the ego vehicle?

**Comment by namdre** [comment]
There is no support for relative position at the moment but you should be able to calculate this from the ego position and angle.

**Comment by ndeshp2s** [comment]
Thankyou for the update @namdre . @behrisch Yes. Just wanted to know if there is any support for relative position.
