### ISSUE TITLE
Invalid z data when importing OpenDRIVE

### ISSUE THREAD

**Issue by zihao0821** [eclipse/sumo#5314]
When I use netconvert to transfer a OpenDRIVE file into .net.xml, some "elevationProfile" (altitude in sumo) of "line" type (straight line in sumo) road are ignored.

It only calculate the beginning and ending points' altitude, however the middle parts are missing.

**Comment by namdre** [comment]
Can you provide a small OpenDrive sample file?

**Comment by zihao0821** [comment]
[missing_z_axis.zip](https://github.com/eclipse/sumo/files/2981188/missing_z_axis.zip)
*.xodr file is part of a viaduct, and *.net.xml file is what I got from netconvert.

I'm using Ubuntu16.04 and SUMO 1.1.0 version.

**Comment by namdre** [comment]
This looks like a bug in the elevation import. The z-level in the .net.xml only varies between 0 and 1 whereas the changes in the xodr are much larger.

**Comment by zihao0821** [comment]
Thanks, it helps a lot.

**Comment by namdre** [comment]
@zihao0821 would it be ok to add your input example to our public test suite?

**Comment by zihao0821** [comment]
of course yes
