### ISSUE TITLE
Trailer stuff

### ISSUE THREAD

**Issue by HolyBugger** [eclipse/sumo#5316]
Hello~
Is it possible to use TraCI.vehicle.moveToXY() to move a Trailer to an intersection during a simulation? And if it is possible, what would I get when using vehicle.getPosition() on the Trailer?
Thank you~

**Comment by namdre** [comment]
In SUMO trailers are not modelled as individual objects. Instead the length of the truck that pulls it is increased by the length of the trailer. You can move the truck onto the intersection with moveToXY and the trailler will follow.
