### ISSUE TITLE
traci.vehicle.getContextSubscriptionResults

### ISSUE THREAD

**Issue by shuowang572875852** [eclipse/sumo#5322]
I have add the traci.vehicle.getContextSubscriptionResults(vehID), and run success but the output is the 1*1Map, how can i do for it?

for i = 1:duration
    traci.simulation.step();
  IDList{i,1} = traci.vehicle.getIDList(); 
  for j=1:length(IDList{i,1})
      accel{i,1}(j)=traci.vehicle.getAcceleration(char(IDList{i,1}(1:end,j)));
      laneID{i,1}=traci.vehicle.getLaneID(char(IDList{i,1}(1:end,j)));
      traci.vehicle.subscribeContext(char(IDList{i,1}(1:end,j)), traci.constants.CMD_GET_VEHICLE_VARIABLE,150,{traci.constants.VAR_POSITION, traci.constants.VAR_SPEED});
     traci.vehicle.addSubscriptionFilterLeadFollow('1');    
    contextSubscriptionResults=traci.vehicle.getContextSubscriptionResults(char(IDList{i,1}(1:end,j)));
  end
end
traci.close()

**Comment by namdre** [comment]
dupliate of #5304. Please don't do this.
