### ISSUE TITLE
sumo running speed with multi-clients

### ISSUE THREAD

**Issue by zihao0821** [eclipse/sumo#5324]
I tried to use two traci clients to speed up a simulation. One client for simulationStep only, and the other for *.subscribe and *.getSubsriptionResults. It takes about 22 ms per step.

However, when I use single client to do the same things, it takes about 20 ms per step. 

So, did I make mistakes or multi-clients just could not help to speed up simulations?

**Comment by namdre** [comment]
The clients are handled serially so you are just adding overhead. If you need to increase traci speed, use libsumo: https://sumo.dlr.de/wiki/TraCI#Using_SUMO_as_a_library

**Comment by zihao0821** [comment]
thanks, I'll try that.

**Comment by zihao0821** [comment]
Thanks again, I've tried libsumo and it's great. 
But still there are some problems that I couldn't fix. I use ``traci.vehicle.subscribe(sumo_id, [tc.VAR_POSITION, tc.VAR_SIGNALS])`` and ``traci.vehicle.getAllSubscriptionResults()`` to get vehicle variables. 

 · When a subscribed vehicle arrived, on next step there will be a ``TraCIException Error: Vehicle "xxx" is not known`` when running ``traci.simulationStep()``. 
 · When I tried to get position info, it's a type of ``<libsumo.libsumo.TraCIResult; proxy of <Swig Object of type 'libsumo::TraCiResults *' at xxx> ``. Is that a kind of cpp pointer and how can I read it?

**Comment by namdre** [comment]
I'm quoting a question that should have been attached to the ticket:

> Thanks again, I've tried libsumo and it's great.
> But still there are some problems that I couldn't fix. I use traci.vehicle.subscribe(sumo_id, [tc.VAR_POSITION, tc.VAR_SIGNALS]) and traci.vehicle.getAllSubscriptionResults() to get vehicle variables.
> 
> · When a subscribed vehicle arrived, on next step there will be a TraCIException Error: Vehicle "xxx" is not known when running traci.simulationStep().
> · When I tried to get position info, it's a type of <libsumo.libsumo.TraCIResult; proxy of <Swig Object of type 'libsumo::TraCiResults *' at xxx> . Is that a kind of cpp pointer and how can I read it?

maybe @behrisch can help with this.

**Comment by behrisch** [comment]
I fixed the part with the position subscription in 7d08f37 implementing getAllSubscriptions is now a separate ticket #5359
