### ISSUE TITLE
Traci.vehicle.add()   error

### ISSUE THREAD

**Issue by warm2018** [eclipse/sumo#5331]
I want to add 9 vehicles in one step just like the code as follows:
    for i in range(8): (**8 vehicles**, v.0 ---v.7)
        vid = "v.%d" % i
        add_platooning_vehicle(plexe, vid, (n - i + 1) * (DISTANCE + LENGTH) +
                      50, 0, SPEED, DISTANCE, real_engine)
        plexe.set_fixed_lane(vid, 0, safe=False)
        traci.vehicle.setSpeedMode(vid, 0)
   add_platooning_vehicle(####）(**1 vehicle** v.8)
but only 2  vehicle ( v.0， v.8)  appear in the gui

**Comment by namdre** [comment]
this sounds like a plexe question rather than sumo question. Maybe @michele-segata can answer this

**Comment by michele-segata** [comment]
It looks like you are using the Python APIs for Plexe (https://github.com/michele-segata/plexe-pyapi). Is this correct? If so, which version of SUMO are you using them with?

**Comment by warm2018** [comment]
Thank you guys! I have solved the problem under the instructions in plexe.  The plexe-pyapi must run  in plexe-sumo rather than standard sumo, I'm stupid!

**Comment by namdre** [comment]
I suppose we can drop this requirment for plexe-sumo soon.
