### ISSUE TITLE
how to handle SwigPyObject from libsumo

### ISSUE THREAD

**Issue by zihao0821** [eclipse/sumo#5343]
I used ``traci.vehicle.subscribeContext(veh_id, tc.CMD_GET_VEHICLE_BARIABLE, 300, [tc.VAR_POSITION, tc.VAR_ANGLE])`` and ``traci.vehicle.getSubscriptionResults(veh_id)`` with **libsumo**, and got a SwigPyObject. I assume it's a kind of cpp pointer. 

The same code with **traci** will return a dict. How could I get the variables inside, or transform SwigPyObject to a dict like traci?

**Comment by zihao0821** [comment]
I think I know why, but still I don't know fix it. 

When I use subscriptions stuff, swig will report a memory leak. 
``swig/python detected a memory leak of type 'std::map< std::string, std::map< int, std::shared_ptr< libsumo::TraCIResult > > > *', no destructor found``
It means that TraCIResult type is not known by swig and results in the memory leak.

**Comment by behrisch** [comment]
There is no easy way to treat SwigPyObject right, it is merely an indicator that the interface in libsumo is still incomplete. I improved this a little in the 7d08f37 but there are still things missing especially #5359
