### ISSUE TITLE
Dead traci pydoc links in the wiki

### ISSUE THREAD

**Issue by vxid** [eclipse/sumo#5344]
It seems that all links to the pydoc documentation in the wiki are dead.

See [this link](https://sumo.dlr.de/wiki/TraCI/Change_Simulation_State) for an example.

**Comment by namdre** [comment]
sumo.dlr.de/daily is down as well

**Comment by behrisch** [comment]
Works here

**Comment by vxid** [comment]
Sorry I wasn't clear enough. I was referring to all links the wiki page I posted link to. For instance, for the `clearPending` method: [here](http://www.sumo.dlr.de/daily/pydoc/traci._simulation.html#SimulationDomain-clearPending)

**Comment by behrisch** [comment]
@vxid Thank you, it has been fixed now.
