### ISSUE TITLE
How to make the junction(intersection)  become free ?

### ISSUE THREAD

**Issue by warm2018** [eclipse/sumo#5358]
Hello! I want to do something (such  as microscopic control)  to vehicles when they enter in the intersection or junction. But  the junction models which are  exist now (such as conflict -avoid, stop-sign) prevent me from drawing my idea in detail. So, How to make the junction become freer, no any junction model in it ?

**Comment by namdre** [comment]
set the junction type to "unregulated" and vehicles will treat the intersection like a normal road. However, this will also prevent collision from being detected.
