### ISSUE TITLE
CACC carfollowModel can't be loaded and Traci ended suddenly

### ISSUE THREAD

**Issue by warm2018** [eclipse/sumo#5360]
Hello! I set the parameter carFollowModel = "CACC"" in Vtype definition, but when I start the simulation it said " Unknown car following model 'CACC' when parsing..."
So, I changed the carFollowModel = "ACC", but the Traci simulation ended in the process  like a BUG. (Win10, SUMO1.0.1, and Python3.7 are used) 
 why  this two errors happened? Thank for your help  in advance!

**Comment by namdre** [comment]
The CACC model is only available since version 1.1.0
