### ISSUE TITLE
sublane model

### ISSUE THREAD

**Issue by shuowang572875852** [eclipse/sumo#5376]
1. How to set --lateral-resolution? I set the "--lateral-resolution" as follows:
F:\software\SUMO\bin\quickstart>quickstart.sumocfg --lateral-resolution 0.1
I want to know if its value can be set in the configuration file or other files, does its value have a range?
2. When using sublane model, whether to consider the lane change as a continuous process, whether to obtain the lane change time, the lane change track, etc.
I added “netstate-dump” option  in the output ,but the generated files have no above attributes.

**Comment by namdre** [comment]
1) yes. (https://sumo.dlr.de/wiki/Basics/Using_the_Command_Line_Applications#Configuration_Files). The useful range goes from ]0, laneWidth]
2) https://sumo.dlr.de/wiki/Simulation/Output/Lanechange

**Comment by shuowang572875852** [comment]
<?xml version="1.0" encoding="iso-8859-1"?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="http://sumo.sf.net/xsd/sumoConfiguration.xsd">
    <input>
        <net-file value="quickstart.net.xml"/>
        <route-files value="quickstart.rou.xml"/>
        <lateral-resolution value="0.1"/ >
    </input>
    <output>
        <lanechange-output value="quickstart"/>
        <lanechange-output.ended value="quickstart"/>
        <lanechange-output.started value="quickstart"/>
        <netstate-dump value="positionspeed"/>
    </output>
    <time>
          <begin value="54000"/>
          <end value="54900"/>
       
		<step-length value="1"/>
    </time>
    <time-to-teleport value="-1"/>
	
</configuration>

I have modified my configuration files, but it doesn't run.How can i do for it?

**Comment by shuowang572875852** [comment]
<?xml version="1.0" encoding="iso-8859-1"?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="http://sumo.sf.net/xsd/sumoConfiguration.xsd">
    <input>
        <net-file value="quickstart.net.xml"/>
        <route-files value="quickstart.rou.xml"/>
        <lateral-resolution value="0.1"/ >
    </input>
    <output>
        <lanechange-output value="quickstart"/>
        <lanechange-output.ended value="quickstart"/>
        <lanechange-output.started value="quickstart"/>
        <netstate-dump value="positionspeed"/>
    </output>
    <time>
          <begin value="54000"/>
          <end value="54900"/>
       
		<step-length value="1"/>
    </time>
    <time-to-teleport value="-1"/>	
</configuration>

**Comment by shuowang572875852** [comment]
<?xml version="1.0" encoding="iso-8859-1"?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="http://sumo.sf.net/xsd/sumoConfiguration.xsd">
    <input>
        <net-file value="quickstart.net.xml"/>
        <route-files value="quickstart.rou.xml"/>
        <lateral-resolution value="0.1"/ >
    </input>
    <output>
        <lanechange-output value="quickstart"/>
        <lanechange-output.ended value="quickstart"/>
        <lanechange-output.started value="quickstart"/>
        <netstate-dump value="positionspeed"/>
    </output>
    <time>
          <begin value="54000"/>
          <end value="54900"/>
		<step-length value="1"/>
    </time>
    <time-to-teleport value="-1"/>
</configuration>
I have modified my configuration files, but it doesn't run.How can i do for it?

**Comment by shuowang572875852** [comment]
1. Thanks for your reply, I have modified the configuration files, but when I add "lanechange-output.ended" and "lanechange-output.start" option ,the generated files doesn't have "changelane start " information.

<output>
        <lanechange-output value="quickstart"/>
        <lanechange-output.ended value="quickstart"/>
        <lanechange-output.started value="quickstart"/>
        <netstate-dump value="positionspeed"/>
    </output>
2. When use sublane model ,did you consider the trajectory planning  during the lane change? Can i extract the trajectory during the lane change?

**Comment by shuowang572875852** [comment]
1.Thanks for your reply, I have modified the configuration files, but when I add "lanechange-output.ended" and "lanechange-output.start" option ,the generated files doesn't have "changelane start " information.
<output><lanechange-output value="quickstart"/><lanechange-output.ended value="quickstart"/>
<lanechange-output.started value="quickstart"/> <netstate-dump value="positionspeed"/></output>
2. When use sublane model ,did you consider the trajectory planning during the lane change? Can i extract the trajectory during the lane change?

**Comment by namdre** [comment]
the option is called 'lanechange-output', not 'lanechange-output.ended'
