### ISSUE TITLE
moveToXY should consider lane permissions

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#5383]
use keepRoute flag as a bitset

- bit0: keepRoute
- bit1: mayLeaveNetwork
- bit2: ignorePermissions

All combinations should be possible (3: stay within the current route edes but allow moving offroad in perpendicular direction)

**Comment by zoe5** [comment]
hello,I want to ask you a question.
when i use [client.vehicle.add("newVeh", "trip", "DEFAULT_VEHTYPE","100");  ]to add a car in sumo,it always fail,Can you tell me where my mistake is?

**Comment by namdre** [comment]
This type of question is inappropriate for this ticket. Please ask on the mailing list: https://sumo.dlr.de/wiki/Contact 
Also, see https://sumo.dlr.de/wiki/FAQ#What_should_I_do_to_get_helpful_answers_on_the_mailing_list.3F

**Comment by zoe5** [comment]
Ok , thank you very much!

**Comment by namdre** [comment]
there is still a failing test
