### ISSUE TITLE
Change pedestrian speed

### ISSUE THREAD

**Issue by ndeshp2s** [eclipse/sumo#5386]
I wish to change the speed of pedestrians on crossing and on edges. However, the documentation says: 
speed attribute is deprecated and instead determined by the person type and the pedestrian dynamics.

I tried changing the speed limit of the edge where a pedestrian is supposed to move. But this does not change the pedestrian speed.

**Comment by namdre** [comment]
the speed attribute of element `<walk>` is deprecated by you can define a `<vType>` for persons just like for vehicles and thus set the speed.

**Comment by ndeshp2s** [comment]
Ohk. Thanks for the update. I will try this.
