### ISSUE TITLE
Invalid compare operator in MSDevice_SSM::closeEncounter 

### ISSUE THREAD

**Issue by m-kro** [eclipse/sumo#5387]
My self-compiled debug version of SUMO crashes with an "invalid operator <" message when running the given simulation. The call stack points to MSDevice_SSM::closeEncounter / the compare operation within it. The simulation runs without issues in a downloaded release version, though. The example simulation is attached and should stop at time 308.900.
[ssm.zip](https://github.com/eclipse/sumo/files/3022900/ssm.zip)

**Comment by namdre** [comment]
when running with the debug build of  1709438e38a37b817f4b6e9b78153a5aeaab69a4 on linux, the simulation runs to completion for me. Removing the 'end' option and running to 3600 does not change this.

**Comment by m-kro** [comment]
I checked again with a VS2017 debug build of a the git repo from today... Still stops at 308.9 seconds...?! I am not sure what causes this error. In any case, I leave you a screenshot of the stack:
![grafik](https://user-images.githubusercontent.com/33294728/55323963-f2f1f100-5480-11e9-906b-89305998b576.png)

**Comment by namdre** [comment]
MSVC checks for priority_queue corruption whereas gcc/clang do not.

**Comment by leoluecken** [comment]
I've built in a runtime check for queue corruption (order of elements retrieved by top()/pop()) and found no problems with my gcc build (goes active if DEBUG_SSM is defined).

However, I did find that the order of the conflicts in myPastEncounters was not ordered as intended, but reversed (which led to locally reversed order of conflicts in the outfile.) See

**Comment by m-kro** [comment]
The problem has appeared again in the example simulation linked in #5527 . The priority_queue item in SSM device uses a greater/equal comparison of the conflict begin time to sort the encounters. Does this violate the requirements for a custom compare function given in [C++ reference](https://en.cppreference.com/w/cpp/named_req/Compare), especially 

> For all a, comp(a,a)==false

??

**Comment by m-kro** [comment]
Looks OK for me now. The invalid operator message is not triggered anymore.
