### ISSUE TITLE
How long will traci command last ?

### ISSUE THREAD

**Issue by warm2018** [eclipse/sumo#5389]
Hi!  Thank for your reading!  I wonder know the How long Traci command will last after I used it.
For example, I use " traci.vehicle.setspeedMode() " or " speedfactor" to a vehicle,  the speed of this vehicle will be effected by these command for a long time . How long is that?  Is until the vehicle be cleared by SUMO ?

**Comment by namdre** [comment]
Yes. The effect of these commands persists for the lifetime of the vehicle or until an overriding command of setSpeedMode or setSpeedFactor is used.
