### ISSUE TITLE
trafficlights.getNextSwitch function problem in traci4matlab

### ISSUE THREAD

**Issue by Hosinam** [eclipse/sumo#5391]
I am working on implementing a control strategy using TRACI4MATLAB in sumo. However I have trouble calculating the remaining phase time for the traffic lights. I use the command "traci.trafficlights.getNextSwitch('0')*0.001-traci.simulation.getTime()", unfortunately it returns the wrong value. I have tracked the problem and I'm guessing that something is wrong with the "traci.trafficlights.getNextSwitch" function. By the way I have defined a switch time program for the traffic light using a WAUT. I will be glad to receive any recommendations to help solving this problem.

**Comment by namdre** [comment]
since version 1.0.0 the factor of 0.001 is no longer necessary as all those functions return time in seconds as floating point valuee

**Comment by Hosinam** [comment]
Thanks for your answer. Unfortunately the returning value is in the 10^9 order!

**Comment by namdre** [comment]
What version of SUMO and TraCI are you using?

**Comment by Hosinam** [comment]
SUMO 1.0.1 and I think it is the latest version of Traci4Matlab.

**Comment by namdre** [comment]
Since these functions are working with the other python clients, I'm hoping the traci4matlab developer  @pipeacosta can help with this

**Comment by behrisch** [comment]
I would also propose to move the ticket there https://github.com/pipeacosta/traci4matlab/issues. @Hosinam Please close this one once you opened it there.

**Comment by shuowang572875852** [comment]
Hello,
      I want to get the leader and follower vehicle acceleration in the target lane .So ,first I add  traci.vehicle.subscribeContext
 to get ego vehicle context information ,and then I add  traci.vehicle.getContextSubscriptionResults(egoID) to get the surround vehicle ID, but the output “ans” is 1*1Map ,the follow is my code:

clear
close all
clc

import traci.constants
scenarioPath=['F:\software\SUMO配置文件\bin\quickstart\quickstart.sumocfg'];
system(['sumo-gui -c ' '"' scenarioPath '"' ' --remote-port 8813 --start&']);
traci.init

SIM_STEPS = [1 900];
beginTime = SIM_STEPS(1);
duration =  SIM_STEPS(2);
endTime =  SIM_STEPS(1) +  SIM_STEPS(2) - 1;

for i = 1:duration
    traci.simulation.step();
  IDList{i,1} = traci.vehicle.getIDList();
  for j=1:length(IDList{i,1})
      accel{i,1}(j)=traci.vehicle.getAcceleration(char(IDList{i,1}(1:end,j)));
      laneID{i,1}=traci.vehicle.getLaneID(char(IDList{i,1}(1:end,j)));
      traci.vehicle.subscribeContext(char(IDList{i,1}(1:end,j)), traci.constants.CMD_GET_VEHICLE_VARIABLE,150,{traci.constants.VAR_POSITION, traci.constants.VAR_SPEED});
     traci.vehicle.addSubscriptionFilterLeadFollow('1');    
    contextSubscriptionResults=traci.vehicle.getContextSubscriptionResults(char(IDList{i,1}(1:end,j)));
  end
end
traci.close()

Can you give me some help and looking forward to your reply.

**Comment by behrisch** [comment]
@shuowang572875852 Please do not abuse this unrelated ticket for your question. Either post it to the mailing list, see https://sumo.dlr.de/wiki/Contact or open a ticket at the traci4matlab implmentation here:  https://github.com/pipeacosta/traci4matlab/issues.

**Comment by Hosinam** [comment]
Hello everyone
 Since there was not any updates on traci4matlab, and the problem remains unfixed, how can I download previous versions of traci4matlab that the function works right in it? @namdre @behrisch

**Comment by behrisch** [comment]
We do neither maintain nor distribute traci4matlab so we cannot tell which version works with which sumo version. You will need to checkout their repository and go back in history yourself.
