### ISSUE TITLE
contextSubscriptions

### ISSUE THREAD

**Issue by shuowang572875852** [eclipse/sumo#5401]
I want to know the contextSubscriptions is whether to subscribe a vehicle with vehicle ID ,when it enters the network until it left the network? But the travel time for each vehicle are different， so how to get each vehicles subscription? During the entire simulation time for contextSubscriptions, if "veh0" has reached the end point, but the whole simulation has not ended, it will report an error: Error: Vehicle 'veh0' is not known . So whether it is necessary to separately subscribe each vehicle for each vehicle's travel time . And can I add contextSubscriptions in a loop to get a subscription for every per time step ?

**Comment by behrisch** [comment]
Subscriptions should end automatically once the vehicle leaves the network. You can subscribe to the list of arrived vehicles (tc.VAR_ARRIVED_VEHICLES_IDS) to get notified and update your internal bookkeeping. There is no need to renew the subscriptions every timestep. The whole point of subscriptions is to have the info coming in automatically.

**Comment by shuowang572875852** [comment]
Thanks for your reply.But if I want to get information about the surrounding vehicles in real time(not simulation end and vehicles arrived), How can I achieve it?
