### ISSUE TITLE
various demand UI issues

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#5405]
- [x] no feedback when creating flow/vehicle/trip
  - click can be anywhere on the route but the object is created at the start
  - flow object may be hidden beneath other objects
  - possible solution: enter inspect mode on the newly created object
- [x] flows trips and vehicles cannot be distinguished visually
- [x] overlapping routes cannot be distinguished visually (one solution would be to draw the first few routes with a lateral offset
- [x] it's hard to define vehicles with different but overlapping routes: if the routes overlap a lot, the user must find a non-overlapping spot to ensure that the click picks the correct one.
   - one solution would be to a button 'use last defined' route (instead of clicking) because the user must first create the route anyway.
- [x] when inspecting a vehicle or flow, the corresponding route should also be highlighted in some way
  - add checkbox (only in demand+inspect mode) to hide other demand objects when inspecting an object.
- [x] in vehicle mode, remember the previous choice of vehicle type
- [x] clicking 'center' for a route in the Hierarchy Frame uses the wrong boundary ('Center' from right-click menu on the glObject is working as expected)
- [x] some way to selectively delete overlapping vehicle/trip/flow objects must be provided. Currently, the top one is always deleted. Solution: in demand-delete-mode, left click on overlapping objects opens a scrollable dialog for deleting objects individually or all-at-once.
- [x] in the vtype frame, the combobox length should be increased when loading/defining more types to avoid scrolling (up to a maximum of 20 items).
- [x] allow panning with ctrl-drag in route mode and vehicle mode

**Comment by namdre** [comment]
moved some bugs to #5576 so this ticket only tracks usability issues / enhancement ideas

**Comment by namdre** [comment]
move another bug to #5576

**Comment by behrisch** [comment]
@palvarezlopez please review
