### ISSUE TITLE
allow converting between vehicles flows and trips via right-click

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#5407]
- [x] trip <-> flow
- [x] vehicle <-> flow 
- [x] vehicle -> trip
- [x] trip -> vehicle
- [x] flow -> routeFlow
- [x] route -> embedded route

Also for selections

**Comment by palvarezlopez** [comment]
@namdre Flows and Trips use different demandelements Parents. I can convert from Flow to Trip (using the first and last edge of route as "from" and "to" respectively), but not on the other way, because Flow requieres a pre-existing route.

**Comment by namdre** [comment]
Using #5406 you can convert a trip directly to a flowFromTo
To convert a trip into a vehicle you need to create a new route from the shortest path that connects the trip.
