### ISSUE TITLE
flowrouter option --lane-based does not consider lane-changing

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#5409]

**Comment by namdre** [comment]
@behrisch: I don't see a sensible way to implement this and still maintain lane-based counts so I would just remove the option alltogether.

**Comment by behrisch** [comment]
No, I think it still conveys information if the detector is close enough to the junction. We should implement some configurable threshold and treat the lanes as basically separate edges when they are close enough to the junction and aggregate the values otherwise.

**Comment by namdre** [comment]
duplicate of #3847
