### ISSUE TITLE
in mesosim, passengers are only picked up once when reaching the stop regardless of stopping duration

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#5424]

**Comment by namdre** [comment]
I think we need a test for the following situation:
a vehicle reaches a stop where x passengers are waiting.
In MESegment.cpp:531 a leave time is computed once, based on the stops duration parameter.
Boarding of the passengers should extend the stop duration but the function MEVehicle::getStopTime is not called again for this stop so the duration is not extended.

**Comment by behrisch** [comment]
I think it is OK to let the mesosim ignore boarding times. The complicated stop time extension can be saved for the microsim. The test you describe is more or less in sumo/basic/personFlow/ride/
