### ISSUE TITLE
Allow to select all vehicles/Pedestrian/additionals/etc with certain name

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#5426]

**Comment by namdre** [comment]
selection by id substring (selection frame) should already work

**Comment by namdre** [comment]
workaround: 
1) load demand in netedit
2) create selection in select mode
3) save selection to file
4) load selection in sumo-gui

**Comment by namdre** [comment]
locator dialog already supports locating objects by their name. We could simply add a button "select/deselect all" which applies the selection toggle to all objects in the list (based on the selection status of the first element).
