### ISSUE TITLE
connected edges remains visible after deleting its node

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#5436]
to reproduce, create a new network with netedit as shown below, press F5 and then delete the central node. 

![image](https://user-images.githubusercontent.com/6240630/55680816-24563b00-591f-11e9-93e2-3b4f4f0edb48.png)

the result is:

![image](https://user-images.githubusercontent.com/6240630/55680832-54054300-591f-11e9-981f-d440f5c39e64.png)

curiously, the problem does not show up when either
- deleting before pressing F5
- when adding reverse direction for all edges
- when saving and loading the network

**Comment by namdre** [comment]
the error was already present in 1.1.0

**Comment by palvarezlopez** [comment]
@namdre Error was fixed in this commit: cc73b3f9845ecdfd9bff689b52428d4f49845394. The error was caused due an extra call to popMatrix() function in GNEEdge::drawGl()
