### ISSUE TITLE
make output configurable (trac #544)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#544]
- [x] **--fcd-output.attributes pos,speed** 
- [x] `<edgeData writeAttributes="departed,arrived" .../>
- [ ] ...

Current implementation uses a bitset and currently uses 58 attributes (bits).

Migrated from http://sumo.dlr.de/ticket/544
```json
{
    "status": "assigned", 
    "changetime": "2015-10-23T08:41:38Z", 
    "description": "Use some kind of string formatting for enabling/disabling values.\n\nSuggestion: \n--output.discard-attributes attr1,attr2,...\n\nThen filter out these attributes in\nPlainXMLFormatter::writeAttr()\n\nEfficiency considerations: For SumoXMLAttr, a boolean lookup table, For string attrs a set will have to do.\n", 
    "reporter": "dkrajzew", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1445589698261765", 
    "component": "simulation data output", 
    "summary": "make output configurable", 
    "priority": "major", 
    "keywords": "", 
    "time": "2011-07-13T14:56:14Z", 
    "milestone": "1.0.0", 
    "owner": "namdre", 
    "type": "enhancement"
}
```

**Comment by namdre** [comment]
working with an attribute whitelist via **--fcd-output.attributes**

**Comment by namdre** [comment]
netstate-output might be a candidate though i didn't need this myself yet. Pretty much all you have to do is replace `writeAttr` with `writeOptionalAttr` (and hope that we don't run out of bits). Feel free to extend the (now updated) list in the top post.

**Comment by namdre** [comment]
not very useful as a meta ticket and the methodology  is working for several use cases now.
