### ISSUE TITLE
Reduce the number of GLObjects of RTree in Netedit

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#5445]
All GLObjects that are childs of another GLObjects must be drawn within the drawGL(...) function of parent.

**Comment by namdre** [comment]
there are some special cases to consider: 
* parkingArea spaces can be far away for the parkingArea lane
* VSS lane/rerouter edge have multiple parents (the lane/edge and the VSS/rerouter) but should only be drawn with the network element parent.
