### ISSUE TITLE
replace sumo binary format by gzipped xml

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#5448]
Our own format is probably neither space nor parsing time efficient and zip support comes with no additional coding cost.

**Comment by behrisch** [comment]
https://github.com/mateidavid/zstr seems like a good implementation

**Comment by palvarezlopez** [comment]
@behrisch it's finished?

**Comment by behrisch** [comment]
we still need to make a performance comparison, flag sbx as deprecated and remove it eventually

**Comment by behrisch** [comment]
Ok some numbers.
Writing (generating a 100x100 grid network, time as reported by the verbose output):
- XML: 7.0s, 103 MB
- SBX: 3.9s, 72 MB
- GZ: 8.3s, 8MB
Reading (the same grid into sumo):
- XML: 11.0s
- SBX: broken
- GZ: 11.2s

**Comment by namdre** [comment]
And the winner is GZ! :clap:
