### ISSUE TITLE
Provide space-mean speed (harmonic speed) for edge data

### ISSUE THREAD

**Issue by ambuehll** [eclipse/sumo#5453]
Provide space-mean speed (using harmonic mean) for edge data output. 
To my knowledge, multiplying the current time-mean speed with the density value (as suggested in the wiki) does not yield the traffic definition of flow which is the sum of travel_distance on segment / (L_segment x observation period).  This has serious effects on the FD in a congested link. See:
http://www.victorknoop.eu/research/papers/tgf07.pdf (Fig. 2, attached).
![knoop](https://user-images.githubusercontent.com/48930860/55834539-07606a00-5acf-11e9-9c80-9a68db3c6647.JPG)

This is a similar feature request as https://github.com/eclipse/sumo/issues/4919

**Comment by namdre** [comment]
This is a misunderstanding. The speed returned by edgeData output does not work like the naive averaging at a local detector (where fast vehicles have a disproportionate effect on the computed average speed). Instead, the averaging is done overt time **and** space which means that the longer time spent by slower vehicles on any given edge is factored into the average speed. 
This means, the speed value already corresponds to the space-mean-speed. 
The cautioning note that describes the 'speed' attribute in the wiki just doesn't use this terminology.
You can easily test this by putting two vehicles with different speed on a single edge and comparing edgeData output with inductionLoop output.

**Comment by ambuehll** [comment]
OK! thanks for updating the wiki!
