### ISSUE TITLE
Netedit: creating route in route mode should have undo for current route creation

### ISSUE THREAD

**Issue by ZoltanBaksa** [eclipse/sumo#5457]
Creating longer routes in demand mode in netedit needs to be done carefully, because if one selects a wrong next edge, undo does not step back. Instead Ctrl+Z removes the previously created routes!

**Comment by namdre** [comment]
should be solved with a button "Remove last inserted" edge just like in vehicle mode.

**Comment by palvarezlopez** [comment]
@ZoltanBaksa now last selected edge can be removed using "backspace" key (or "remove last inserted edge button). During route creations undo/redo is disabled.
