### ISSUE TITLE
How to make SUMO ignore the emergency stop vehicles ?

### ISSUE THREAD

**Issue by warm2018** [eclipse/sumo#5460]
When a vehicle has emergency stop in the front of stopline because of the red light. SUMO often deletes the vehicle and destroy it. But I still want the vehicle be alive. So, how to let SUMO ignore this emergency and make this vehicle still exist in the next simulation step.

**Comment by namdre** [comment]
vehicles with an emergency stop are never deleted. However, if there is a collision, the rear vehicle is teleported. You can disable this by setting the option --collision.action warn.
Are you using traci?

**Comment by warm2018** [comment]
Yes, traci. OK, I did it under your constriuction, thank you very much!
