### ISSUE TITLE
convert opendrive to OpenStreetMap

### ISSUE THREAD

**Issue by Zealoft** [eclipse/sumo#5463]
# convert opendrive to OpenStreetMap Question
Is there a way to convert OpenDrive files into OpenStreetMap files using the netconvert tool? Or is there any tools available to convert it? Thanks.

**Comment by namdre** [comment]
No. There is currently no way to genererate OSM files with the sumo tools. Technically it would not be too difficult but so far this this type of output format was never required. 

Out of curiosity: what for do you need generated OSM?

**Comment by Zealoft** [comment]
Thanks for the reply. Actually we are working on a project which uses
CityEngine and RoadRunner to generate city scenes for Carla and uses SUMO
for traffic simulation.

Currently the problem is that CityEngine only supports OSM import. So we
are looking for ways to convert to OSM.

Jakob Erdmann <notifications@github.com> 于2019年4月12日周五 下午2:21写道：

**Comment by sajidraza125** [comment]
Is there any way to convert OSM file to OpenDrive file? Any tools to do so or any specific algorithm? I would appreciate your response. Thanks

**Comment by namdre** [comment]
@sajidraza125 `netconvert --osm-files osm.xml --opendrive-output out.xodr`
