### ISSUE TITLE
How to re-insertion vehicle when failed? 

### ISSUE THREAD

**Issue by binderwang** [eclipse/sumo#5465]
How can I add a vehicle again when traci.vehicle.add() failed because the lane is blocked? Is there any info I can subscribe if it fails?

**Comment by namdre** [comment]
By default, the vehicle will be put into the insertion buffer and insertion will be re-attempted every simulation step until successful.
You can use simulation.getDepartedIDlist() to check for success.
Also see https://sumo.dlr.de/wiki/Simulation/VehicleInsertion#Forcing_Insertion_.2F_Avoiding_depart_delay

**Comment by binderwang** [comment]
Thanks a lot, solved it according to the wiki.

1. add option `--eager-insert` when start sumo.

2. check for success during insertion.
`while inserted_ID is not in traci.simulation.getDepartedIDList():
        traci.simulationStep()`
