### ISSUE TITLE
traci.person.getStage() returns 5

### ISSUE THREAD

**Issue by tkchouaki** [eclipse/sumo#5466]
Hi,
the **getStage()** method returns 5 in some cases, while the possible return values are defined like this in the [documentation](http://sumo.sourceforge.net/pydoc/traci._person.html)

- 0 for not-yet-departed
- 1 for waiting
- 2 for walking
- 3 for driving

**Comment by namdre** [comment]
Thank you for reporting. The generated documentation will be updated tomorrow.

4 denotes access (direct movement between an edge and a busStop or trainStop on a disconnected edge)
5 denotes a personTrip which remains part of the plan to allow correct rerouting (changing multiple derived stages at once)
