### ISSUE TITLE
How to retrieve inductionLoops serving specific junction

### ISSUE THREAD

**Issue by Exorcismus** [eclipse/sumo#5471]
given a junction ID, how can I retrieve induction loop IDs which serves this specific junction ?

**Comment by namdre** [comment]
If you are refering to inductionLoops that you have defined yourself, then you have to get the list of all inductionLoop ids and check their lanes, then use sumolib functions (readNet etc) to determine the correspondence between junction and incoming lanes.

If you are refering to inductionLoops that were generated for an actuated traffic light then they have the fixed id 

 "TLS" + <tlLogic-ID> + "_" + <programID> + "_InductLoopOn_" + <laneID>
