### ISSUE TITLE
SUMO trying to load XSD online

### ISSUE THREAD

**Issue by Exorcismus** [eclipse/sumo#5475]
am using a SUMO network which has file
**bangalore.poly.xml**
file content

`
<additional xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/additional_file.xsd">
    <location netOffset="-790641.28,-1441646.19" convBoundary="0.00,0.00,387.69,1075.46" origBoundary="77.679576,13.026894,77.683154,13.036613" projParameter="+proj=utm +zone=43 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"/>
</additional>
`

but when I run it, it throws

`Warning: Cannot find local schema '/home/sumo/bin/data/xsd/additional_file.xsd', will try website lookup.
Error: unable to connect socket for URL 'http://sumo.dlr.de/xsd/additional_file.xsd'
 In file 'data/bangalore.poly.xml'
 At line/column 1/0.`

**bangalor.sumo.cfg**
`  <input>
        <net-file value="bangalore.net.xml"/>
        <route-files value="bangalore.rou.xml"/>
        <additional-files value="bangalore.poly.xml, bangalore.det.xml"/>
    </input>
    <time>
        <begin value="0"/>
        <end value="1000"/>
    </time>
</configuration>`

**Comment by ambuehll** [comment]
desactivate the xml validation by adding:
  <report>
    <xml-validation value="never"/>
  </report>
to your file.

**Comment by behrisch** [comment]
The better solution is to set your SUMO_HOME environment variable to point to the root of your sumo installation.

**Comment by user1325120** [comment]
Warning: Cannot read local schema 'D:\sumo/data/xsd/routes_file.xsd', XML validation will fail.

**Comment by namdre** [comment]
@user1325120 possibly %SUMO_HOME% isn't set correctly. What is the output of `where sumo` on the command line?
