### ISSUE TITLE
Is there any demo for FIFO with intersection management in sumo?

### ISSUE THREAD

**Issue by Jeffrey28** [eclipse/sumo#5476]

**Comment by namdre** [comment]
I'm not sure what you mean. The junction type "allway_stop" operates on a first-in-first-out principle.

**Comment by Jeffrey28** [comment]
Thanks for your answer. And actually it is the "first come first serve", which is proposed by Peter Stone in 2008. 
Dresner, Kurt, and Peter Stone. "A multiagent approach to autonomous intersection management." Journal of artificial intelligence research 31 (2008): 591-656.

**Comment by namdre** [comment]
I'm not aware of a demo that can be downloaded though I recall seeing a video of something like this some years ago. Building FIFO control in SUMO wouldn't be terribly hard as you could just switch the traffic light to all-green and control the vehicle speeds directly using the TraCI-API.
