### ISSUE TITLE
get pedestrians's desired lines using traci

### ISSUE THREAD

**Issue by tkchouaki** [eclipse/sumo#5481]
Hi,
I would like to use traci to retrieve the public transport lines desired by a person in the simulation,

Is it currently possible ? or if not, are there alternatives ?

best regards.

**Comment by behrisch** [comment]
Currently it is not possible to get any information about the stages via traci except for the type. I moved this to a new ticket #5495. If you do not modify the persons dynamically you could parse the input route files to get this information.
