### ISSUE TITLE
IDM vehicle remains stuck inside an intersection, waiting in front of a pedestrian crossing

### ISSUE THREAD

**Issue by m-kro** [eclipse/sumo#5487]
I have found again some example where an IDM vehicle stops forever in front of a pedestrian crossing with no pedestrian nearby, jamming all the "Forschungskreuzung" intersection. In the example scenario attached, watch out for vehicle 21.2 at around 650s.
Then, there are more cases like that where vehicles leaving the intersection stop for those entering it, but which I was not able to repeat yet.
[results_K047_Festzeit_Nullfall1_cal.zip](https://github.com/eclipse/sumo/files/3089561/results_K047_Festzeit_Nullfall1_cal.zip)

**Comment by namdre** [comment]
regression in 1.1.0 most likely due to #4805

**Comment by namdre** [comment]
The bug was triggered due to #5512 (the straight connection from west to east was wrongly classified as a partially-left turn) otherwise there would have been no internal junction for this connection.
