### ISSUE TITLE
subscribeContext

### ISSUE THREAD

**Issue by shuowang572875852** [eclipse/sumo#5494]
I want to use subscribeContext  to get the  Context of the ego vehicle,the following are my codes(traci4matlab):
for i =1:318
   traci.simulation.step();
    traci.vehicle.subscribeContext('veh0',traci.constants.CMD_GET_VEHICLE_VARIABLE,20,{traci.constants.VAR_POSITION, traci.constants.VAR_SPEED});
      traci.vehicle.addSubscriptionFilterLanes(-1,1,20,20);  
    contextSubscriptionResults{i,1}=traci.vehicle.getContextSubscriptionResults('veh0'); 
    surround_vehicle{i,1}=keys(contextSubscriptionResults{i,1});
end

the 'veh0' run in the simulation from step 1 to step 318. 
For  addSubscriptionFilterLanes(self, lanes, noOpposite, downstreamDist, upstreamDist),when I set lanes=-1 or lanes=1, lanes=0,the results are same.
 traci.vehicle.addSubscriptionFilterLanes(-1,1,20,20);  
 traci.vehicle.addSubscriptionFilterLanes(0,1,20,20);  
 traci.vehicle.addSubscriptionFilterLanes(1,1,20,20);  
How can i do for it?And The travel time for each vehicle are different， so how to get each vehicles subscription? . And can I add contextSubscriptions in a loop to get a subscription for every per time step ? If I want to get information about the surrounding vehicles in real time(not simulation end and vehicles arrived), How can I achieve it? Looking forward to your reply.

**Comment by behrisch** [comment]
Please do not ask traci4matlab questions here but open a ticket at https://github.com/pipeacosta/traci4matlab/issues
