### ISSUE TITLE
add access to person stage information

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#5495]
much like route information for a vehicle the information of the different stages for a person plan should be accessible

**Comment by namdre** [comment]
The existing person API dates from before the introduction of TraCIStage.
the current method person.getStage() should be changed from returning the stage type (int) to returning a TraCIStage object

**Comment by tkchouaki** [comment]
I think there's a little problem,
In the TraCIStage class, the line attribute is a single string. while a riding stage can have multiple desired lines.

**Comment by namdre** [comment]
Right now, sumo parses the list of lines from a string (when reading xml) with the hard assumption that SPACE is the separating character. Therefore, multiple lines can also be returned as a single string by joining them with SPACE.
