### ISSUE TITLE
cmake and configure.ac list std=c++11 when it should be gnu++11

### ISSUE THREAD

**Issue by neheb** [eclipse/sumo#5496]
C++11 sets ANSI which in certain circumstances, which disables long long support.

**Comment by behrisch** [comment]
@neheb Can you please give a source for that or describe the circumstances when it made problems for you? This page https://gcc.gnu.org/onlinedocs/gcc/Long-Long.html#Long-Long and this page https://en.wikipedia.org/wiki/C%2B%2B11#Type_long_long_int suggest "long long int" is part of the standard and was a gnu extension only before C++11.

**Comment by neheb** [comment]
Hmm OK nvm. I was trying to build with uClibc++ which targets C++98 or something. It doesn't build (<random> is missing).
