### ISSUE TITLE
traci-python(getNeighbors)

### ISSUE THREAD

**Issue by shuowang572875852** [eclipse/sumo#5497]
For  getNeighbors(self, vehID, mode), I read the explanation of the "mode" :

The parameter mode is a bitset (UBYTE), specifying the following:
bit 1: query lateral direction (left:0, right:1)
bit 2: query longitudinal direction (followers:0, leaders:1)
bit 3: blocking (return all:0, return only blockers:1)

So, if I want to get the ''left leaders" vehicle, the ''mode=01''? The "right leaders", the "mode=11"?  getNeighbors( vehID, 01)?

**Comment by namdre** [comment]
right leaders is binary 11 which translates to decimal 3
