### ISSUE TITLE
getNeighbors

### ISSUE THREAD

**Issue by shuowang572875852** [eclipse/sumo#5501]
Hello,
      Sorry to bother you,I want to add some new functions to traci4matlab in the same way as traci-python: such as getNeighbors(vehID, mode).
      1、I add  VAR_NEIGHBORS = '0xbf'  to constants.m
      2、add   traci.constants.VAR_NEIGHBORS,...   and  {'traci.vehicle.readNeighbors'}  to  RETURN_VALUE_FUNC.m
      3、write readNeighbors.m

 function [vehID, dist] = readNeighbors(result)
N=result.readInt();
    neighs = [];
    for i =1:N
        vehID = result.readString();
        dist = result.readDouble();
        neighs.append(vehID,dist);
    end

     4、write getNeighbors.m

function [vehicleID, dist] = getNeighbors(vehID, mode)
import traci.constants
global message
traci.beginMessage(constants.CMD_GET_VEHICLE_VARIABLE,constants.VAR_NEIGHBORS,...
    vehID, 2);
message.string = [message.string uint8(sscanf(constants.TYPE_UBYTE,'%x'))...
    uint8(mode)];
[vehicleID, dist] = traci.vehicle.readNeighbors(traci.checkResult(...
    constants.CMD_GET_VEHICLE_VARIABLE, constants.VAR_NEIGHBORS, vehID));

But when i run getNeighbors.m , the matlab  commandline get follow errors:
error use traci.sendExact (line 46)
64  164  255 Error Get Vehicle Variable: unsupported variable 0xbf specified
The sumo-gui error:
Error: Answered with error to command 0xa4: Get Vehicle Variable: unsupported variable 0xbf specified

So how can i do for it ?Can you give me some help?Looking forward to your reply.

**Comment by namdre** [comment]
This looks as if your traci client connects to an older sumo version where this traci constant was not yet implemented on the server side.

**Comment by shuowang572875852** [comment]
This is my taci and sumo version :  traciversion =19,  sumoversion =  'SUMO 1.1.0'.
Can i need to update sumo?

**Comment by namdre** [comment]
VAR_NEIGHBORS is not yet availabe in 1.1.0 so you need to upgrade to 1.2.0

Am Mi., 24. Apr. 2019 um 09:28 Uhr schrieb shuowang572875852 <
notifications@github.com>:

**Comment by namdre** [comment]
VAR_NEIGHBORS is not yet availabe in 1.1.0 so you need to upgrade to 1.2.0

**Comment by shuowang572875852** [comment]
Thanks for your help, I have update sumo to 1.2.0, and that  mistake has been solved. But for my  
readNeighbors.m :

function [vehID, dist] = readNeighbors(result)
result.read(2);
N=result.readInt(); 
    neighs = cell(1,N);
    for i =1:N
       result.read(1);
        vehID = result.readString();
         result.read(1);
        dist = result.readDouble(); 
         neighs{i}={vehID,dist};
    end
The following error is displayed at run ： index is out of the matrix dimension. 
I want to know what the second line" result.read（）" value  should be. Looking forward to your reply.

**Comment by mnour94** [comment]
did you  manage to solve this? I'm having the same error.

**Comment by maxfhappy** [comment]
> Do you also need to use getNeighbor in traci4matlb?I have some questions to ask you. May I have your contact information?
> 
> did you manage to solve this? I'm having the same error.

**Comment by Feiju112** [comment]
Hi wangshuo
My work also involves this problem.  Do you succeed in implementing the same function as the Python program in Matlab? 
It would be greatly appreciated if you could inform me of the correct solution.
Bests,
Fei Ju

**Comment by behrisch** [comment]
@Feiju112 It is very easy to use the TraCI python client directly from matlab. You just install python, and then do `pip install traci` and you can call all functions of the python client from matlab just by prepending them with `py` (e.g. `py.traci.vehicle.getNeighbors`).
