### ISSUE TITLE
Map net convert from opendrive is going crazy

### ISSUE THREAD

**Issue by yotamkima** [eclipse/sumo#5504]
![town4mapprob](https://user-images.githubusercontent.com/33685882/56577172-005b5080-65d3-11e9-800b-68b54be6d968.png)

you can notice the weird conversion of sumo as opposed to the open drive.
sumo is deleting roads for example road 210, 209. and place nothing instead.

**Comment by namdre** [comment]
Please provide example inputs for reproducing this issue. You may also send the .xodr privately to namdre.sumo@gmail.com.
What version of netconvert did you use?
