### ISSUE TITLE
The mailing address that one could use to ask for help

### ISSUE THREAD

**Issue by JaneCheung** [eclipse/sumo#5506]
Today I just write some message without additional files,
I still could not get access from the mailing list and receive a response like this:
****************************************************************************************
The results of your email command are provided below. Attached is your
original message.

Results:
Ignoring non-text/plain MIME parts

Unprocessed:
would like to ask for anyone who could help me ?
As the concept in the transportation system, could we set

Saturation flow for "turn left""turn right""straight" separately?
The average start up (brake) speed;
The free flow speed at junction ?
Appreciate for anyone who could give me some suggestion about how to
modify these parameters!
Best regards!
Lizzy Cheung
Done.

and I have subscribed to the mailing list SUMO.

![image](https://user-images.githubusercontent.com/39317241/56581795-60360500-659b-11e9-89c0-746999b8593f.png)

How could I deal with the problem like that ?
Appreciate for any kind help!

**Comment by namdre** [comment]
I can read your message to sumo-user@eclipse.org just fine. 
I think the error response is because you are also sending to
'sumo-user-request@eclipse.org'. (don't do this).

**Comment by JaneCheung** [comment]
Thanks! Jakob!
