### ISSUE TITLE
How could I generate a topology with a fixed number of vehicles?

### ISSUE THREAD

**Issue by ningjing-m** [eclipse/sumo#5508]
In SUMO, using randomTrips.py to generate random traffic, the number of vehicles will gradually increase and gradually decrease to no with the simulation time. How could I generate a topology with a fixed number of vehicles? From the beginning to the end of the simulation are fixed vehicles that will not disappear from the topology.

**Comment by namdre** [comment]
see https://sumo.dlr.de/wiki/FAQ#How_do_I_maintain_a_constant_number_of_vehicles_in_the_net.3F

**Comment by ningjing-m** [comment]
Is it possible to have a fixed 200 cars moving randomly in a city map?

**Comment by namdre** [comment]
Yes. Wasn't this obvious from the linked FAQ?

**Comment by ningjing-m** [comment]
I'm very sorry. But what I want to achieve is to fix 200 cars and keep running. Don't replace the car, I still don't understand how to do it. Please tell me some specific methods.Thank you very much!


------------------ 原始邮件 ------------------
发件人: "Jakob Erdmann"<notifications@github.com>;
发送时间: 2019年4月24日(星期三) 下午3:11
收件人: "eclipse/sumo"<sumo@noreply.github.com>;
抄送: "月光抚平伤痛"<410116987@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [eclipse/sumo] How could I generate a topology with a fixednumber of vehicles? (#5508)




Yes. Wasn't this obvious from the linked FAQ?

**Comment by namdre** [comment]
The FAQ entry describes 4 alternative methods. The first one replaces cars but the remaining 3 keep the fleet constant. Methods 3 and 4 are the simplest to implement. If you are unable to follow the wiki discription, come back with specific questions.
