### ISSUE TITLE
In SUMO, can the node coordinate range be set by ourselves?

### ISSUE THREAD

**Issue by ningjing-m** [eclipse/sumo#5509]
With the map generated by SUMO, the coordinates of the vehicle nodes are all over 10,000. Can I control the map coordinates generated by myself to be less than 2000? Can SUMO's coordinate origin be set by ourselves?

**Comment by namdre** [comment]
Yes. you can shift the network with netconvert options --offset.x  and --offset.y (either during creation or in post-processing).

**Comment by ningjing-m** [comment]
How could I use the netconvert options --offset.x and --offset.y?
Is there a command statement? I was given an error when I tried it.

**Comment by namdre** [comment]
`netconvert -s old.net.xml --offset.x 1234 --offset.y -42 -o new.net.xml`
shifts the old network and saves this as a new network.
