### ISSUE TITLE
The output data of Edgelane Traffic cannot be saved in xml file correctly in a special case

### ISSUE THREAD

**Issue by ImLaoBJie** [eclipse/sumo#5518]
I meet a problem when using the output function ‘Lane- or Edge-based Traffic Measures’ to collect data of junction internal edges/lanes.

If the attribute '**step-length**' was set to '**0.33, 0.34, 0.35**' (other possible value may exist), the data of junction internal edges/lanes will not be written correctly to xml file as shown below. But if it was set to other values, this problem will disappear.

<meandata xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/meandata_file.xsd">

    <interval begin="1800.00" end="3600.10" id=":J2_0_0"/>

    <interval begin="3600.10" end="5400.15" id=":J2_0_0"/>

    <interval begin="5400.15" end="7200.20" id=":J2_0_0"/>

</meandata>

The file only contains the useless information instead of complete details.

The zip file contains rou.xml, net.xml, add.xml, configuration file and incorrect output file.
[files.zip](https://github.com/eclipse/sumo/files/3116797/files.zip)
Thank you.

**Comment by namdre** [comment]
possibly related to #282

**Comment by namdre** [comment]
caused by MSMeanData.cpp:644 
The 'begin' attribute of the edgeData / laneData definition must be a simulation step that is reached exactly.

So in your example if you set step-length to 0.35 then a work-around would be to set the begin attribute  to 1800.05 because this is an exact multiple of 0.35

**Comment by ImLaoBJie** [comment]
Thanks for your reply. The solution is effective.

**Comment by behrisch** [comment]
See the commits related to #282
