### ISSUE TITLE
control the arriving time 

### ISSUE THREAD

**Issue by JaneCheung** [eclipse/sumo#5520]
Dear all,
 Are there some methods that we could  do to  control the vehicle arrival time? 
e.g., 7 vehicles would arrive at one specified parking lot in 7-8 a.m.,  is there some method that could be done to let the three vehicles of them to arrive at  8-9  a.m.?
Best regards for any kind help!

**Comment by JaneCheung** [comment]
One more question, I know for the question like presented above is better to send to the mailing list to ask  for help , however , I have tried many times and the results are always like that !

![image](https://user-images.githubusercontent.com/39317241/56748756-002f9200-6746-11e9-8488-49b8c0905d2e.png)

**Comment by namdre** [comment]
You can only control arrival times indirectly by modifying depart times. 

It seems you are not subscribed to the mailing list. Currently, each of your messages has to be allowed manually by an administrator.

**Comment by JaneCheung** [comment]
Thanks Jakob！
