### ISSUE TITLE
incompatibilities between libsumo and the python client

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#5523]
- [x] #5502 
- [x] simulation.Stage allows write access to members in libsumo but not in traci
- [x] libsumo simulations always finish one step earlier
- [x] context subscriptions

**Comment by namdre** [comment]
@behrisch I would replace the namedtuple in _simulation.py with a simple class (like _trafficlight.py::Phase) and get rid of the enumeration capability of namedtuple unless you have a better suggestion.

**Comment by lcodeca** [comment]
The initialization of libsumo.libsumo.TraCIStage and traci._simulation.Stage should be the same too.

**Comment by lcodeca** [comment]
findIntermodalRoute:
* libsumo: returns a tuple of tuples
* traci: returns a list of namedtuples

**Comment by lcodeca** [comment]
`traci_vehicle_subscription = traci_handler.vehicle.getAllSubscriptionResults()`
where `traci_handler` can be `traci` or `libsumo`.

```
print(traci_vehicle_subscription)
print(type(traci_vehicle_subscription))
for vehicle, data in traci_vehicle_subscription.items():
    ...
```

`traci`: returns a dict where .items() can be used to iterate on the results.
```
{'pedestrian_1_1096_tr': {80: 'D0C0', 115: (('B1C1_1', 33.5, 'parkingArea_B1C1_1_2', 130, 1200.0, -0.001),), 26: ('pedestrian_1_1096',)}}

<class 'dict'>
```

`libsumo`: crashes
```
<Swig Object of type 'std::map< std::string,std::map< int,std::shared_ptr< libsumo::TraCIResult > > > *' at 0x7fe6d2239c00>

<class 'SwigPyObject'>

AttributeError: 'SwigPyObject' object has no attribute 'items'
swig/python detected a memory leak of type 'std::map< std::string,std::map< int,std::shared_ptr< libsumo::TraCIResult > > > *', no destructor found.
```

**Comment by behrisch** [comment]
@lcodeca This is already a known issue, see #5359

**Comment by namdre** [comment]
python traci stage is now a class (#5798)

**Comment by behrisch** [comment]
seems to be largely fixed by now, remaining stuff is repairing the tests (or needs separate tickets)

**Comment by behrisch** [comment]
There is no documentation on what is different, since we do not know :-). But I think it is better to continue with separate tickets here, so I opened #6164
