### ISSUE TITLE
lisum-gui needs jdk 11 on ubuntu 18.04

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#5534]
ubuntu seems to be in the process of upgrading to JDK 11 and updated the openjfx package needed by lisum-gui accordingly. Currently you need to downgrade the package manually to get a working build. Unfortunately we cannot update to JDK 11 currently due to #5104.

**Comment by behrisch** [comment]
The following call is needed to downgrade:

    sudo apt install libopenjfx-jni=8u161-b12-1ubuntu2 libopenjfx-java=8u161-b12-1ubuntu2 openjfx=8u161-b12-1ubuntu2

**Comment by behrisch** [comment]
I needed to add a new file to lisum gui to work around this: https://stackoverflow.com/questions/52653836/maven-shade-javafx-runtime-components-are-missing

**Comment by palvarezlopez** [comment]
@behrisch it's fixed?

**Comment by behrisch** [comment]
The immediate build problems seem to be fixed although lisum and lisum-gui still need tests.
