### ISSUE TITLE
 getNeighbors(vehID, mode)

### ISSUE THREAD

**Issue by shuowang572875852** [eclipse/sumo#5535]
Hello,
Sorry to bother you,I want to add some new functions to traci4matlab in the same way as traci-python: such as getNeighbors(vehID, mode).
1、I add VAR_NEIGHBORS = '0xbf' to constants.m
2、add traci.constants.VAR_NEIGHBORS,... and {'traci.vehicle.readNeighbors'} to RETURN_VALUE_FUNC.m
3、write readNeighbors.m

function [vehID, dist] = readNeighbors(result)
result.read(2);
N=result.readInt();
neighs = cell(1,N);
for i =1:N
result.read(1);
vehID = result.readString();
result.read(1);
dist = result.readDouble();
neighs{i}={vehID,dist};
end

The following error is displayed at run ： index is out of the matrix dimension.
I want to know what the second line" result.read（）" value should be. Looking forward to your reply.

**Comment by behrisch** [comment]
@shuowang572875852 Please stop opening tickets concerning traci4matlab here. We cannot support it. We do not even have a matlab license. Please try the traci4matlab repo at https://github.com/pipeacosta/traci4matlab/issues.
