### ISSUE TITLE
Error in example of getAllSubscriptionResults() in wiki

### ISSUE THREAD

**Issue by hoxovic** [eclipse/sumo#5537]
Retrieval of subscription results in example on [wiki](https://sumo.dlr.de/wiki/TraCI) should call `traci.vehicle.getAllSubscriptionResults()` instead of `traci.vehicle.getSubscriptionResults()` since the latter requires the object id to be specified. 

Appears to have been overlooked after an update to the API, as described in #4486

**Comment by namdre** [comment]
Thanks for reporting. Now fixed.
