### ISSUE TITLE
Question about 'duaIterate.py' 'cost-modifier' choices

### ISSUE THREAD

**Issue by zyrgit** [eclipse/sumo#5543]
Hi, can someone tell me the difference between the cost-modifier choices: ('grohnde', 'isar', 'None')?

If it is None, then there is no change of edge weights, and iterations of routing will not consider traffic load information, right?

Another question, after say 20 iterations, are we supposed to only use the last one (routes_019.xml) or several last ones (*_017.xml + *_018.xml + *_019.xml) since each iteration has different flow patterns/ congestion areas? Using only one without down-sampling still has congestion under light traffic.

Thanks!

**Comment by namdre** [comment]
The cost-modifiers are for specific projects are likely not relevant for your use case. 
If the flow patterns still vary a lot after 20 iterations this means the traffic assignment has not converged and you need more iterations. Once convergence has been achieved it should matter if you use the last one or the one before that. 
you can try option --max-convergence-deviation 0.05 to determine convergence automatically.
Sometimes the option --weight-memory helps to achieve convergence.
