### ISSUE TITLE
Building error  in VS 2017

### ISSUE THREAD

**Issue by warm2018** [eclipse/sumo#5546]
System can't launch  " SUMO_HOME/Cmake-build/ Debug/ALL-Build
The specified file could not be found. 

Win10  is used

**Comment by palvarezlopez** [comment]
@warm2018 You need to specify a project (for example, SUMO-GUI) as startup project

![startup](https://user-images.githubusercontent.com/8238561/57064992-4f3a7180-6cc8-11e9-9ac3-c38e3c896574.png)

**Comment by warm2018** [comment]
![image](https://user-images.githubusercontent.com/35907049/57066757-b1629900-6cff-11e9-8d7f-f396d186b602.png)

OK, I follow it, but  sumo-gui.exe can't be excutable.

**Comment by warm2018** [comment]
I choose Win32 , not Win64 which wiki advise when  I configure sumo by Cmake.  And Python3.7, VS2017, win10 64 are used.

**Comment by palvarezlopez** [comment]
@warm2018 Can you compile for 64 bits instead of 32 bits?

**Comment by warm2018** [comment]
When I choose 64bits, erros happened.  "Failed to run MSBuild command:"
![image](https://user-images.githubusercontent.com/35907049/57070136-1b337080-6d09-11e9-98fa-72d38b2906ca.png)
![image](https://user-images.githubusercontent.com/35907049/57070150-238bab80-6d09-11e9-9048-f4df1448e58c.png)

**Comment by palvarezlopez** [comment]
Can you translate the chinese characters of the output messages?

**Comment by warm2018** [comment]
OK, thank for your patience. 
TRANSLATION:
CMake Error at CMakeLists.txt:7 (project):
Failed to run MSBuild command:

D:/Program Files (x86)/VisualStudio/Packages/MSBuild/15.0/Bin/MSBuild.exe
to get the value of VCTargetsPath:

Microsoft (R) build engine version 15.9.21+g9802d43bc3 for the.net Framework
Copyright (C) Microsoft Corporation.All rights reserved.

The build startup time is 2019/5/2 18:35:53.
Item "D:\Project\SUMO\cmake-build\CMakeFiles\3.14.3\VCTargetsPath. Vcxproj" on node 1 (default target).
D: \ \ Program Files \ VisualStudio \ Packages (x86) \ Common7 \ VC IDE \ \ VCTargets \ Microsoft Cpp. InvalidPlatform. 
The Targets (22, 7) : error MSB8007: project "VCTargetsPath. Vcxproj" platform is invalid.The platform is "Win64".The likely reason you will see this message is that you are trying to build a project without a solution file and specify a non-default platform for the project that does not exist.[D: \ Project \ SUMO \ cmake - build \ CMakeFiles \ 3.14.3 \ VCTargetsPath vcxproj]

"D:\Project\SUMO\cmake-build\CMakeFiles\3.14.3\VCTargetsPath. Vcxproj" (default target) operation - failed.
Build failed.
"D:\Project\SUMO\cmake-build\CMakeFiles\3.14.3\VCTargetsPath. Vcxproj" (default target) (1) ->
InvalidPlatformError target ->
D: \ \ Program Files \ VisualStudio \ Packages (x86) \ Common7 \ VC IDE \ \ VCTargets \ Microsoft Cpp. InvalidPlatform. The Targets (22, 7) : error MSB8007: project "VCTargetsPath. Vcxproj" platform is invalid.The platform is "Win64".The likely reason you will see this message is that you are trying to build a project without a solution file and specify a non-default platform for the project that does not exist.[D: \ Project \ SUMO \ cmake - build \ CMakeFiles \ 3.14.3 \ VCTargetsPath vcxproj]
0 a warning
1 mistake

**Comment by palvarezlopez** [comment]
Try the following solution:

1) Close Visual Studio and CMake
2) Remove folder "D:\Project\SUMO\Cmake-build"
3) Open CMake-gui and repeat the entire process, but for Visual Studio 15, 64 bits

![Cmake1564](https://user-images.githubusercontent.com/8238561/57070906-1d7dd680-6cd9-11e9-8e4b-bc1151046062.png)

4) Check if now works

If not, check the following thread in which there is differents solutions for your porblem:

https://github.com/vector-of-bool/vscode-cmake-tools/issues/222

**Comment by warm2018** [comment]
Thank you for your guide, and I sloved the CMAKE problem.   But when I build it in VS,  error happened again. 
![image](https://user-images.githubusercontent.com/35907049/57074099-84b97c00-6d15-11e9-846b-889c842602f2.png)

**Comment by warm2018** [comment]
"LINK : fatal error LNK1104: cannot open file 'gui\dialogs\Debug\gui_dialogs.lib'

I check the path  and find it has no gui_dialogs.lib but nothing.

**Comment by palvarezlopez** [comment]
Try to compile using this button:

![buildSolution](https://user-images.githubusercontent.com/8238561/57074656-ced63980-6ce4-11e9-9f5c-78075eec1329.png)

**Comment by warm2018** [comment]
![image](https://user-images.githubusercontent.com/35907049/57075948-ec25fa80-6d1a-11e9-9fda-0982f3e36369.png)
![image](https://user-images.githubusercontent.com/35907049/57075956-f3e59f00-6d1a-11e9-9cd0-0eee173a5c51.png)

I am a beginner in VS and C++. Thank for your patience again. When  I rebuild it and VS shows above errors.  When I Check path: "D:\Project\SUMO\bin" , find some excutable files(Every one have the suffix "D")  are generated ,
![image](https://user-images.githubusercontent.com/35907049/57076177-93a32d00-6d1b-11e9-8f8f-1309c88e0c51.png)

 but when I click them,  errors happened  :
![image](https://user-images.githubusercontent.com/35907049/57076246-c6e5bc00-6d1b-11e9-82ea-babda1a36ae2.png)
![image](https://user-images.githubusercontent.com/35907049/57076277-d9f88c00-6d1b-11e9-843d-2994dabb1f0e.png)

TRANSLATION:  
Unable to continue executing the code because  them cannot be found. Reinstallation may solve this problem.

**Comment by palvarezlopez** [comment]
The suffix D is normal, because its the debug version. If you compile in Release mode, the suffix D disappeared.

About the other error, you only need to build the project "Solution 'SUMO'/CMake/install_dll"

**Comment by warm2018** [comment]
Ok, thank you very much. 
where is "install_all"?   Is it "ALL_BUILD"?(maybe my sumo is older version. Correctly, I clone it from "plexe-sumo" )

![image](https://user-images.githubusercontent.com/35907049/57079790-ab7eaf00-6d23-11e9-839f-5c0cff0504d0.png)

**Comment by palvarezlopez** [comment]
Yes, definitely your SUMO version is old. Try it cloning the current GIT version.

**Comment by warm2018** [comment]
Thank for your advice. But I want “plexe-sumo” for a  special use. The functions which plexe-sumo has is important to my project.  Did the platooning function has been intergrated in latest SUMO?

**Comment by palvarezlopez** [comment]
@namdre is Platooning already in SUMO?

**Comment by namdre** [comment]
We integrated several compatibility fixes for plexe  into SUMO and I think that the author of plexe (@michele-segata) has an updated version of plexe that works with the latest sumo version. I suggest that @warm2018 approaches him directly.

**Comment by warm2018** [comment]
OK，thank you guys!

**Comment by michele-segata** [comment]
@warm2018 if you fetch updates from [plexe-sumo](https://github.com/michele-segata/plexe-sumo) (master branch, 1d0977320a4e71a1ce92f908ef5a87c884bf23cd) you will get the latest SUMO version. This is **exactly the same** as SUMO 1.2.0, as Plexe models have been integrated into the official SUMO release.

**Comment by warm2018** [comment]
Oh! Thank you ! I clone branch "plexe2.1", not master branch.   

You mean that  latest SUMO is same as plexe-sumo?

**Comment by warm2018** [comment]
OK, I downloaded  latest SUMO 1.2.0 binary files just now, and find that it can  realize the platooning behavior which python scripts  support . 
I understand what we want know  at first, thank you guys so much.

**Comment by michele-segata** [comment]
If you just need the python support and not the Plexe-Veins network simulator, then you are fine with SUMO 1.2.0.

**Comment by behrisch** [comment]
Looks like being solved to me, please reopen if questions persist.
