### ISSUE TITLE
Crash after sequence of Undo-redo, recomputings and Join junctions

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#5552]
Only in Debug Mode:

Network is: simo\members\alvarez\bugs\join_junctions_undoredo\input_net.net

And sequence is:

F7 -> F5 -> Split junctions and reconnect -> F5 -> Ctrl+Z -> Ctrl+Z -> F5 -> Ctrl+Y  -> Ctrl+Y

**Comment by namdre** [comment]
I am able to reproduce this

**Comment by palvarezlopez** [comment]
@namdre Are you testing in Windows or in Linux?

**Comment by namdre** [comment]
> @namdre Are you testing in Windows or in Linux?

Sorry, my previous comment was invalid. I meant to say: I'm unable to reproduce this (tested only on linux).
