### ISSUE TITLE
bug when deleting edge

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#5555]

**Comment by namdre** [comment]
- create edge
- move node
- delete node
  - first click does nothing
  - second click on node removes it but the edge remains visible

**Comment by namdre** [comment]
was still working in version 1.2.0

**Comment by palvarezlopez** [comment]
After a moving, edge and lane are inserted in RTree two times:

GLDebug: Removed object junction:gneJ6 from SUMORTree with boundary 15.98,65.42,59.98,109.42
GLDebug: Inserted junction:gneJ6 into SUMORTree with boundary 1.36,47.09,45.36,91.09
GLDebug: Removed object junction:gneJ5 from SUMORTree with boundary -56.11,67.35,-12.11,111.35
GLDebug: Inserted junction:gneJ5 into SUMORTree with boundary -56.11,67.35,-12.11,111.35
GLDebug: Removed object edge:gneE7 from SUMORTree with boundary -64.15,55.82,67.98,119.35
GLDebug: Inserted edge:gneE7 into SUMORTree with boundary -64.64,37.58,53.36,119.35
**GLDebug: Inserted edge:gneE7 into SUMORTree with boundary -64.64,37.58,53.36,119.35**
GLDebug: Inserted junction:gneJ5 into SUMORTree with boundary -56.11,67.35,-12.11,111.35
**GLDebug: Inserted junction:gneJ6 into SUMORTree with boundary 1.36,47.09,45.36,91.09**
