### ISSUE TITLE
long delay when creating new network on windows

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#5556]
about 5s where nothing happens after pressing 'Ctrl+N'. Works instantly on Linux.
Worked instantly on Windows with version 0.26.0
~2s with version 0.27.0 - 1.1.0 
~5s since version 1.2.0

The same delay occurs when loading a network as well

**Comment by namdre** [comment]
slow down is most likely due to different fox-toolkit version.
Caused by calls to delete FXMDIChild (GUIGlChildWindow) in ::closeAllWindows()

**Comment by palvarezlopez** [comment]
@namdre I check it with the FOX 1.6.57 and the problem remains.

**Comment by palvarezlopez** [comment]
Fixed in https://github.com/eclipse/sumo/commit/503c2de5304f430f580c4610d27a110aed866d80
