### ISSUE TITLE
How to dynamically set up "StopID"?

### ISSUE THREAD

**Issue by YenKang** [eclipse/sumo#5570]
Dear @namdre , @behrisch ,
## How to dynamically set up "StopID"?

Firstly,I ran the following codes,

`String senderEdge=“'-537706053#2”`

`conn.do_job_set(Vehicle.setBusStop("8", senderEdge, 20.0, 100));`

then I got error messages,
> SUMO error for command 196: The BusStop '-537706053#2' is not known for vehicle '8'

After checking the document, I realize the **StopID** is the parameter which is needed to put in the **setBusStop** function.

Therefore, I add `busStop.xml` by hand into the simulation foler and the codes are

```
<additional xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/additional_file.xsd">
  <busStop id="senderStop" 
		name="sender address" 
		lane="160253722#1_0" 
		startPos="5" endPos="25">
  </busStop>
</additional>
```
It works after adding the **busStop.xml**.

## Is there any way of adding the script to generate the ***"StopID"*** automaticlly?
or I only can product ***"stopID"*** by adding **busStop.xml** on hand?

**Comment by namdre** [comment]
You don't need a busStop to let vehicles stop and pick up passengers. A normal stop (Vehicle.setStop) is sufficient. 
If you want to use a busStop it must be added with an xml file.
You can automatically import busStops from OSM using option --stop-output or you place them visually  in Netedit.
