### ISSUE TITLE
Traci closed  by SUMO  without any warning in gui while running 

### ISSUE THREAD

**Issue by warm2018** [eclipse/sumo#5581]
After  I ADD a steplistener ,  SUMO  always  closes the gui while running and shows " connection closed by SUMO"(below).  Strangely, there is  no any warnings in gui! before crush.
I want to know the reasons why result the gui crush, maybe because of my steplistener?

![image](https://user-images.githubusercontent.com/35907049/57271891-ce161c80-70c3-11e9-9c44-76d33b7e6aaf.png)

**Comment by namdre** [comment]
What version of SUMO did you use? 
If it crashes with version 1.2 or later, please provide minimum inputs for reproducing the issue

**Comment by warm2018** [comment]
SUMO 1.2 is used.  Ok,  I will pack these in minimum files,  can I send it to your email address ？

**Comment by warm2018** [comment]
Sorry, I have no idea to describe this error in simple  because of lots of files.
and maybe this will waste your time. 

I just wonder why this traci error happened, (I use a lots of traci.vehicle commands) maybe I can debug it. 
Please help me list the possibilities if you are free.
thank you very much !

**Comment by warm2018** [comment]
I find this error always happen when the first car is destroyed by sumo.

**Comment by namdre** [comment]
Your help in finding the error is welcome. See here for how to do this: https://sumo.dlr.de/wiki/TraCI/Interfacing_TraCI_from_Python#Debugging_a_TraCI_session_on_Linux

You can send files to namdre.sumo@gmail.com

**Comment by warm2018** [comment]
Thank you very much,  I have found the reason. The detail will be presented in few days after I am sure.

**Comment by namdre** [comment]
If SUMO crashed then there is a bug somewhere. Even if you can work around the crash, please let us know how to reproduce it so we can fix the problem (or send a pull request with a patch).

**Comment by warm2018** [comment]
Ok, thank you ! I will check this bug in a few days and draw this in detail.
