### ISSUE TITLE
How to get the position when "Waiting before the Intersection"

### ISSUE THREAD

**Issue by binderwang** [eclipse/sumo#5582]
How does a car know it is approaching an intersection or its distance to an intersection? I know each junction has ID and position, but how can I get this info with Traci? Thanks.

**Comment by namdre** [comment]
for trafficlights you can use traci.vehicle.getNextTLS to retrieve distance and junction ids (and more).

For intersections in general, there is no such convenience function. You can use traci.lane.getLlinks to figure out connectivity but it's much more convenient to use sumolib for reading an analyzing the network topology (https://sumo.dlr.de/wiki/Tools/Sumolib).
You can use traci.vehicle.getRoute and getRouteIndex to determine the upcoming edges along the route and then check the sumolib network object for topology.
