### ISSUE TITLE
Unify criterias for Warnings and Errors loading additional elements

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#5587]
Invalid esential parameters will be handled as Errors (Example: StoppingPlace lane), and optional parameters with default value as Warnings (example: FriendlyPos)

**Comment by namdre** [comment]
When we discussed this I had a different understanding:
- recoverable problems (stop lane index is wrong but the edge exists) should generate a warning and attemp to fix the object
- irrecoverable problems (edge corresponding to stop lane unknown or lane attribute missing) should generate an error

**Comment by palvarezlopez** [comment]
Was fixed in #3863
