### ISSUE TITLE
traci-python(getNeighbors)

### ISSUE THREAD

**Issue by shuowang572875852** [eclipse/sumo#5607]
H​ello,
   Sorry to bother you, I have some questions about  getNeighbors(self, vehID, mode):

The parameter mode is a bitset (UBYTE), specifying the following:
 bit 1: query lateral direction (left:0, right:1) 
bit 2: query longitudinal direction (followers:0, leaders:1) 
bit 3: blocking (return all:0, return only blockers:1) 

I want to know how to define the "mode"? When i want to get rightfollower vehicle ID use getNeighbors(vehID,mode),what the mode value should be? Can you give me some help,Looking forward reply. Best wishes!

**Comment by shuowang572875852** [comment]
Can someone give me some help or advice？Thank you very much.

**Comment by LawranceXcl** [comment]
If you want to get rightFollower vehicle ID ,you can set as follow:
neighborVehicles = traci.vehicle.getNeighbors(your egovehicleID,1)

bit1: right ->1
bit2-bit8: 0
So mode:0x00000001
