### ISSUE TITLE
Some performance issues

### ISSUE THREAD

**Issue by HolyBugger** [eclipse/sumo#5608]
Hello~
I have several points to learn about:
1.the max numbers of vehicles can exist at the same time to keep a scenario running in real time.
2.the max frequency to make a scenario run normally
3.maybe for the scenario mentioned above you made some benchmarks before, could you share some information or materials with me about a standard scenario and some performance parameters.
Thanks!

**Comment by HolyBugger** [comment]
Sorry for the point 1, it should be 'same time' of 'same'.

**Comment by namdre** [comment]
This depends on a number of things:
- carfollowmodel
- lanechangemodel
- presence of junction internal lanes
- network topology (are the vehicles interacting at intersetions or just following each other)

With the default models and options you should usually manage to get 50k vehicles running in real time.
If your own benchmarks give different results please let me know.
