### ISSUE TITLE
TAZ polygon is not visible in NETEDIT

### ISSUE THREAD

**Issue by ZoltanBaksa** [eclipse/sumo#5616]
If I create a TAZ manually in Network mode, after clicking "Stop" or pressing "Enter" the polygon disappears. I did not find any setting to make it visible again. Selecting with Additional locator is possible, but it is not drawn again.
Used version: v1_2_0+0190-e4fde986ea

**Comment by palvarezlopez** [comment]
@ZoltanBaksa Thanks!, I fix it immediately.

**Comment by ZoltanBaksa** [comment]
Thanks, it works now
Unfortunately I did not find any setting to change the view setting of the drawn line.
The "Draw with constant size..." in the "Additional" pane does not make an effect on it.
