### ISSUE TITLE
sumo  --- the maximum speed limit

### ISSUE THREAD

**Issue by ningjing-m** [eclipse/sumo#5622]
Hello, I would like to ask where to check the maximum speed limit of the vehicles after sumo generates the map?

**Comment by namdre** [comment]
either
- right click on an edge in sumo-gui and select 'Show Parameter'
- color edges according to speed, optionally set  the check 'show edge color value' to also draw the number (m/s) for each edge. See https://sumo.dlr.de/wiki/SUMO-GUI#Changing_the_appearance.2Fvisualisation_of_the_simulation
