### ISSUE TITLE
shape changed when convert opendrive map to sumo road network in lefthand

### ISSUE THREAD

**Issue by o-u-p** [eclipse/sumo#5638]
it caused shape changed when executing "netconvert -c defaultSchema.xsd --opendrive opendrive.xodr --lefthand -o test.net.xml "

![Screenshot from 2019-05-15 11-52-25](https://user-images.githubusercontent.com/22117027/57747383-f7f4c200-7707-11e9-88a7-4f24bcd341a4.png)
Could someone tell me how to make it work correctly?
Any help will be appreciated!

**Comment by namdre** [comment]
I never tested OpenDRIVE import for lefthand networks. Can you provide a sample .xodr file?

**Comment by o-u-p** [comment]
I have sent it to your email.

**Comment by namdre** [comment]
Some kinds of geometrical definition already imply a specific jurisdiction and you cannot set the option --lefthand independent of that (https://sumo.dlr.de/wiki/NETCONVERT#Lefthand_Networks)

For OpenDRIVE, this translates to:
- if both directions of a street are defined as a single road, option --lefthand will produce reasonable results even if the network was not intended as a left-hand network
- if both directions of a street are defined as separate roads then only lefthand geometries work correctly with option --lefthand (and the option is needed to produce correct results)

**Comment by o-u-p** [comment]
If I don't set the option --lefthand, it will generate a righthand network, so, do you mean I need to change the opendrive map?

**Comment by namdre** [comment]
Right now the opendrive map encodes some geometries that only make sense for a right-hand network.
If you want a lefthand network you need to change the opendrive (specifically, you must reverse all road elements which only define lanes in one direction) and then you can import with option  --lefthand

**Comment by o-u-p** [comment]
Thanks for your help. By the way, can I know if I can reverse the shape in sumo code to make the lefthand work correctly?

**Comment by namdre** [comment]
You can do the following
- import as a righthand network
- in netedit, select all edges and right-click on an edge and selected 'reverse ... edges'
- using processing options (F10) to set the option lefthand
- save the network
