### ISSUE TITLE
Query: Modelling "burst" traffic and platooning

### ISSUE THREAD

**Issue by arsenious** [eclipse/sumo#5641]
Hi
I'm currently using SUMO to model a single intersection, in order to try various signal optimization strategies. Usually, signals are a part of a larger grid/corridor. Hence, the traffic a signal receives is often in the form of "bursts", based on when upstream signals let their traffic flow. 
Is there any way to model this kind of demand?
Thanks

**Comment by namdre** [comment]
The simplest way to do this is by placing a traffic light upstream of the test intersection that shapes incoming flow. By changing the distance and speed deviation of the vehicles you can fine-tune the density of the bursts.
