### ISSUE TITLE
removing and reinserting a vehicle with TraCI fails

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#5647]
sumo reports the vehicle is already known. Observed in the driver Rotterdam scenario

**Comment by behrisch** [comment]
This only applies when both actions are done in the same time step and is a consequence of the parallelization efforts which now delay vehicle removal until the end of the time step. As I suppose it is not a too common use case but rather a workaround for setting a new route or changing some other vehicle properties, I would rather close this and work on the "real" requirement of changing more vehicle properties. @namdre Please reopen if you disagree.

**Comment by namdre** [comment]
The current behavior would still be surprising to the user. I think it would not hurt to just call removePending instantly when removing vehicles via traci (either via optional boolean for scheduleVehicleRemoval or via explicit clal in libsumo::Vehicle).

**Comment by roireshef** [comment]
so @namdre, what is the best practice here? Should I use removePending? Does it need a simulationStep to work? if yes, could you please where to put it in https://github.com/eclipse/sumo/issues/8607? Thanks!

**Comment by namdre** [comment]
I'm still in favor of instantly removing vehicles via TraCI.
Also,  we already have Simulation::clearPending which clears the queue of insertion-delayed vehicles, so we shouldn't introduce another method with a similar name to avoid confusion.

**Comment by roireshef** [comment]
@namdre - I'd really appreciate your advice here on the https://github.com/eclipse/sumo/issues/8607 case (which is described here similarly, but is detailed with code example). When wanting to get an episode done, clear all vehicles and spawn new ones - should I use cleanPending? If yes, should I run an additional simulationStep afterwards?

**Comment by roireshef** [comment]
@namdre do you have any expected timeframe for solving this? 

So far I have been using **SUMO Version v1_1_0+0000-2147d155b1** to train Reinforcement Learning agents. Runtime is critical as I'm running hundreds of SUMO applications for days. I tried switching TraCI for libsumo a while ago, which showed really great runtime improvements, but in V1_1_0 libsumo is having memory explosion issues, so my training experiments ended up too soon with memory errors. I tried upgrading SUMO to the latest version, but then all kinds of other issues apear, like this one (also opened this one https://github.com/eclipse/sumo/issues/8607 on May 21`). 

Unfortunately, I couldn't find a stable SUMO+libsumo setup, so I'm stuck with TraCI, which has its communication overhead that slows it down.

**Comment by namdre** [comment]
@roireshef  Thanks for pointing out the wide applicability. Could have been done sooner but got lost in the stack.

**Comment by roireshef** [comment]
@namdre Thanks for handling this one.
I saw you closed this ticket. Did the problem reproduce and you were able to solve it? Or was it that it didn't even reproduce? I don't see any PR for this commit. What SUMO version did you run that it worked?

**Comment by namdre** [comment]
I've added a test that reproduced the issue in 03e00164a86a6d33790aa5cf9291809a3099990b and committed the fix in 6ada7b0d1c031e33b3974cdf60a3a4700b02e9b5 both were already linked above.

**Comment by colton-nevs** [comment]
Quick question related to this. Do parked vehicles affect the speed of SUMO? I.e., if I am running a full day and most cars are parked during most of the day, can I speed up my sim by removing when parked and re-inserting right before needed, or is that not a big factor?

**Comment by namdre** [comment]
Parked vehicles take up some time though far less than moving vehicles.  At best they simply count down their remaining duration but they can also have entering and exiting passengers while parking.  I haven't done any benchmarks on this. Would be intersted to learn about your savings if you happen to try this.
