### ISSUE TITLE
How to add " until attribute" into setStopin Traas?

### ISSUE THREAD

**Issue by YenKang** [eclipse/sumo#5656]
## How to  add " until attribute" into setStop?

Dear @namdre 

I want to use setStop function with adding **until attribute** instead of **double duration**.

However, I just observed that the **until attribute** existed in setStop of **python version** and **ContainerStop in TraaS**.

As a result, I tried detect the difference between setStop and setContainerStop in **Vehicle.java** and realized how to deal with **until attribute**.

However, I still had no clue to **add until attribute**after reading the related codes.

### setContainerStop
```java
/**
 *  Adds or modifies a container stop with the given parameters. 
The duration and the until attribute are
    in milliseconds.

 * @param vehID id of the vehicle
 * @param stopID
 * @param duration
 * @param until
 * @return SumoCommand
 */
public static SumoCommand setContainerStop(String vehID, String stopID, 
double duration, int until){
    SumoStopFlags sf = new SumoStopFlags(false, false, false, false, true);
    return setStop(vehID, stopID, 1, (byte) 0, duration, sf);
}
```

### setStop
```java
public static SumoCommand setStop(String vehID, String edgeID, 
        double pos, byte laneIndex, double duration, SumoStopFlags sf){

    Object[] array = new Object[]{edgeID, pos, laneIndex, duration, sf};
    return new SumoCommand(Constants.CMD_SET_VEHICLE_VARIABLE, Constants.CMD_STOP, vehID, array);
}
```

mit freundlichen Grüßen

Kang Yen

**Comment by behrisch** [comment]
Dear Kang Yen,
take the python client as a template https://github.com/eclipse/sumo/blob/master/tools/traci/_vehicle.py#L930 and just add two more (floating point) values to the function signature with INVALID_DOUBLE_VALUE as a default and append them to the object array. Please report back whether it already does the trick.

**Comment by YenKang** [comment]
Dear @behrisch,

After reading your instruction, I tried to re-write the **setStop** function with adding two more parameters of **startPos and until**

### Edited codes
```java
public static SumoCommand setStop(String vehID, String edgeID, 
     ouble pos, byte laneIndex, double duration, SumoStopFlags sf, double startPos, double until){

    Object[] array = new Object[]{edgeID, pos, laneIndex, duration, sf, startPos, until };
    return new SumoCommand(Constants.CMD_SET_VEHICLE_VARIABLE, Constants.CMD_STOP, vehID, array);
}
```
Then, I executed this line of code

`conn.do_job_set(Vehicle.setStop(vehID, edge, pos+10, (byte)0,  0.0, sf, pos,until));`

### It works sucussfully!
![68](https://user-images.githubusercontent.com/16321107/58600458-446b0080-82b7-11e9-816d-42df4922f84f.PNG)


Thanks for your help again!

Kang Yen

**Comment by behrisch** [comment]
@YenKang Great! Would you do a pull request so that others can benefit from your work too?

**Comment by YenKang** [comment]
Sorry for late reply!
This is my [pull-request version](https://github.com/eclipse/sumo/pull/5710)!

Thank you!
Kang Yen
