### ISSUE TITLE
How to modify the traffic logic?

### ISSUE THREAD

**Issue by wrs777** [eclipse/sumo#5658]
I wanna modify the traffic logic when two cars encountered with each other in an intersection. Which file should I  read and modify? Thanks

**Comment by namdre** [comment]
see https://sumo.dlr.de/wiki/Simulation/Traffic_Lights
and https://sumo.dlr.de/wiki/NETEDIT#Traffic_Lights

**Comment by wrs777** [comment]
Thx a lot. But it seems that this two links are aiming to show how to control traffic flow in an intersection with traffic light. I'm trying to simulate the situation that self-driving vehicles cross the intersections without traffic light. Are there any files I need to modify?

**Comment by wrs777** [comment]
Thx a lot. But it seems that this two links are aiming to show how to control traffic flow in an intersection with traffic light. I'm trying to simulate the situation that self-driving vehicles cross the intersections without traffic light. Are there any files I need to modify?

**Comment by wrs777** [comment]
Thx a lot. But it seems that this two links are aiming to show how to control traffic flow in an intersection with traffic light. I'm trying to simulate the situation that self-driving vehicles cross the intersections without traffic light. Are there any files I need to modify?

**Comment by namdre** [comment]
The code in src/microsim/MSLink::blockedByFoe determines whether the time gap between two vehicles is sufficient for letting them both pass the intersection so you might make your modifications there.

Alternatively, you can use the TraCI API to make vehicles selectively ignore each other at junctions by setting their speed mode to ignore intersection logic: 
https://sumo.dlr.de/wiki/TraCI/Change_Vehicle_State#speed_mode_.280xb3.29
and then overriding their speed using (e.g. using traci.vehicle.setSpeed)

**Comment by wrs777** [comment]
Thx
