### ISSUE TITLE
Pedestrian walk corrupted by too short walkingarea

### ISSUE THREAD

**Issue by m-kro** [eclipse/sumo#5661]
The "striping pedestrian model" skips (see [src](https://github.com/eclipse/sumo/blob/master/src/microsim/pedestrians/MSPModel_Striping.cpp#L566)) short walkingareas. This can lead to pedestrians jumping across crossings and wrong walking directions. In my example, the pedestrian gets beamed across the junction and then inverts the direction. As a result, the error "Disconnected walk [...]" (see [src](https://github.com/eclipse/sumo/blob/master/src/microsim/pedestrians/MSPModel_Striping.cpp#L1497)) is thrown.
At least the walking direction should be updated, too, when the pedestrian jumps across walkingareas and the user should be notified about the problem of short walkingareas. In case a simulation example is needed, I can prepare one within the next days.

**Comment by namdre** [comment]
A small test case would be helpful.

**Comment by m-kro** [comment]
[DisconnectedWalk.zip](https://github.com/eclipse/sumo/files/3219378/DisconnectedWalk.zip)
Here it is...
