### ISSUE TITLE
simulation slowdown while showing vehicle route

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#5665]

**Comment by palvarezlopez** [comment]
@namdre NETEDIT has the same problem

**Comment by namdre** [comment]
This is a misunderstanding. I'm not talking about rendering speed but rather that the simulation thread itself is slowed down (which typically should not happen due to rendering). This is likely caused by locking the simulation thread in an inappropriate way.

**Comment by namdre** [comment]
Caused by locking in GUIViewTraffic.cpp:302.
Workaround is to increase simulation delay until it matches the real-time factor. (related to #4008)
