### ISSUE TITLE
Netedit does not handle keyboard events correclty

### ISSUE THREAD

**Issue by ZoltanBaksa** [eclipse/sumo#5673]
I have a strange issue, while in Netedit some of my keyboard events are not handled at all. Here is a list, probably not full:
File menu short cuts like ctrl+s to save changes
switching between modes
processing commands like F5
in case of changing junction shape the Enter to finish the editing
If I use the arrow buttons it moves the map, and if I click in any editor box in inspection mode, I'm able to change the content
I use currently v1_2_0+0461-a55c34aad on windows x64

**Comment by palvarezlopez** [comment]
@ZoltanBaksa Thanks, I check it.

**Comment by ZoltanBaksa** [comment]
After restarting the whole computer, not just sign-out-sign-in the problem did not occur again, probably some windows issue

**Comment by palvarezlopez** [comment]
It's cannot be reproduced.

**Comment by ZoltanBaksa** [comment]
Hello Pablo,
I was able to reproduce the problem. The issue comes up, when I try to edit a junction or connection shape and by faulty keyboard command I enter to Demand mode, because I pressed F4 instead of F5 (recalculate junction).
