### ISSUE TITLE
non-signalized intersection

### ISSUE THREAD

**Issue by wrs777** [eclipse/sumo#5676]
I want to find the codes when two cars encounter with each other in a non-signalized intersection,  maybe two self-driving cars. I want to modify the logic to control which car goes first, which file should I modify?

**Comment by namdre** [comment]
duplicate, answered in #5658

**Comment by hht980309** [comment]
> I want to find the codes when two cars encounter with each other in a non-signalized intersection, maybe two self-driving cars. I want to modify the logic to control which car goes first, which file should I modify?

Hi! Are you doing coordinated control of unsignalized intersections？I have some questions, could you please help me？My email is hht337110412@gmail.com.THX!
