### ISSUE TITLE
Vehicle collision at zipper node

### ISSUE THREAD

**Issue by m-kro** [eclipse/sumo#5680]
![grafik](https://user-images.githubusercontent.com/33294728/58418706-cfb27f00-8088-11e9-88bc-5e71f1c0cad3.png)
The situation can be repeated using the simulation from #5527 (first post) waiting for the encounter of vehicles "Pkw.34.15" and "Pkw.34.17" at around 2230s. The vehicles advance on adjacent lanes to the zipper node and keep their speeds until they "collide". No warning about the collision is issued though this option had been set in the config.

**Comment by namdre** [comment]
Both vehicles alternate their action steps. This causes link-approach information (in particular, distance to the merge point) to be slightly outdated and as a consequence both vehicles assume that the other vehicle will brake .

**Comment by namdre** [comment]
the collision warning is not issued due to the used options `--no-warnings`
