### ISSUE TITLE
optionally add legend to GUI when coloring by values with many colors

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#5682]
especially if we want to convince people to use screenshots instead of custom plotting scripts a legend is important

**Comment by rjmaris** [comment]
@namdre The legend accidentally includes the no data colour. This is a bit confusing since the colour continues to change beyond the highest value. I'd suggest to remove the no data colour or to show this in its own rectangle.

**Comment by behrisch** [comment]
@rjmaris sounds reasonable to me, please open a new ticket
