### ISSUE TITLE
tls.discard-simple

### ISSUE THREAD

**Issue by ambuehll** [eclipse/sumo#5684]
Setting up OSM networks with tls:
When playing around with `tls.discard-simple` and `tls.discard-loaded = false` (and tls.guess =true) I noticed that setting tls.discard-simple = true ends up removing certain tls recorded in osm. The following two screenshots illustrate the dilema: 
when setting tls.discard-simple = false -> all tls remain instated, as expected.
![tls.discard-simple = false](https://user-images.githubusercontent.com/48930860/58465449-098e8e80-8138-11e9-9b92-8e184e4020e1.png)
when setting tls.discard-simple = true-> tls that are not at a 4-way intersection are removed, even if they satisfy the tls.guess.treshold value. It seems as non-standard intersections (such as T-intersections) are classified as geometry-like nodes.
![tls.discard-simple = true](https://user-images.githubusercontent.com/48930860/58466627-4bb8cf80-813a-11e9-986e-642ecca27877.png)
I would like to remove tls that are truly located at geometry nodes, but not the ones at non-standard intersections. Any workaround appreciated!

Reproducible with:
[files](https://drive.google.com/open?id=1ZVr7oZUP0S7x-OFFYCLbf9CK86PwVo_6) and SUMO v1_2_0+0624-36fd61ea35 at junction:402294227

P.S. any way to make the intersection look nicer in terms of connectivity (the white, unconnected angle space)?

**Comment by namdre** [comment]
The white space at junctions is due to https://github.com/eclipse/sumo/issues/5687
If you don't set option --rectangular-lane-cut it will look somewhat better.

**Comment by ambuehll** [comment]
thanks for the tip and for the fix! quick as always!
Cheers.
