### ISSUE TITLE
Apply offset to parking spaces with netgenerate --offset.x

### ISSUE THREAD

**Issue by leoluecken** [eclipse/sumo#5685]
Currently only the area element is shifted, not its "space" child elements.

**Comment by leoluecken** [comment]
Hmm, I just noticed these are defined in the additional file - perhaps this is invalid. Please check

**Comment by namdre** [comment]
Netconvert can import parking areas from OSM (only road-side at the moment) but it cannot read them back in. 
Netgenerate does not support parking areas.
This means there currently is no way to process <space> elements with --offset.*
