### ISSUE TITLE
Implement getSecureGap() and insertionFollowSpeed() for CACC model

### ISSUE THREAD

**Issue by leoluecken** [eclipse/sumo#5686]
As done for ACC model in f699dcb6270e8380e10b16a845ceca2e79949962 and 9ecd9cc4c3b85887b57cad1ff8fc0d7ee1e93745

refs #4861

**Comment by leoluecken** [comment]
@kporfyri: Could you please check if it is working as desired?

FYI: Also note issue #5352

**Comment by namdre** [comment]
fixing issues that were causing collisions on insertion.

**Comment by namdre** [comment]
commit 21983201b4ee8802f75df74ab7866d118b48a134 also applies to this ticket (it is responsible for the prior expected results commit)
