### ISSUE TITLE
DFRouter should be able to filter edges by allowed vclass

### ISSUE THREAD

**Issue by wastene** [eclipse/sumo#5698]
When using DFRouter, it will also generating routes for cars which includes padestrian ways. This results to errors when simulating this routes. 

For smaller Nets it is possible to use a simple Python-Script to output all edges which cant be driven by a passenger car and put it in the disallowed-edges option of the DFRouter.

But if the net is a bit bigger the DFRouter cannot be executed, because of the maximum argument length.

Maybe its possible to check the streets before generating it or adding an option for giving a file with disallowed edges. So it can be executed despite a high number of disallowed edges.

**Comment by behrisch** [comment]
@wastene A simple workaround would be to add the list of edges in a configuration file and not on the command line but I agree that filtering by allowed vclass should be an option. (You can also modify the network in netedit removing all pedestrian paths and calculate the routes in the reduced network.)
