### ISSUE TITLE
make python3 the new default

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#5700]
unfortunately we are not there yet

- [x] daily build script is not working with python3 
- [x] mirrorWiki is not working
- [x] libsumo tests are not running although python3 seems to be picked up correctly
- [x] Texttest does not run with python3 yet
- [x] there is no py2exe for python3 (for the sumo game)
- [x] adapt documentation
- [x] add python2 tests

**Comment by palvarezlopez** [comment]
@behrisch it's finished?

**Comment by behrisch** [comment]
No, unfortunately nothing of the above list.

**Comment by behrisch** [comment]
work continues in #8777
