### ISSUE TITLE
[Question] Is it possible to set step-length less than 0.01s?

### ISSUE THREAD

**Issue by IronicallySerious** [eclipse/sumo#5703]
I am working on a SUMO simulation and I may require a step length of close to 1/60s (I am trying to reach 60 FPS with the SUMO updates).

Is there any way to do this? I see that the command-line option `--step-length` only take values greater or equal to 0.01. Is there any way to circumvent this limit?

**Comment by namdre** [comment]
The limit for --step-length is 0.001 (1ms)
1ms is also the accuracy limit  so the closest you can get to 60fps is --step-length 0.017.

**Comment by IronicallySerious** [comment]
Thanks!
