### ISSUE TITLE
scaling demand crashes simulation

### ISSUE THREAD

**Issue by ambuehll** [eclipse/sumo#5704]
Running the simulation (meso/micro) for taz demand (routes not pre-defined) with another scale value than 1, crashes the sim shortly after the start. 
Should be reproducible with:
sumo v1_2_0+0639-3dcaea6686
and the following files:
[files](https://drive.google.com/drive/folders/1-RBNtxWHysU3KeezXWKcS-VI64ANHI4v?usp=sharing)

**Comment by namdre** [comment]
2.5GB inpuf files are a bit too much. Could you provide a smaller demand input sample?
I could not trivially reproduce the crash by setting a scale value in our own traz-routing test so I assume there might be some special properties of your network/taz that cause this.

**Comment by ambuehll** [comment]
Sure. let me down size it: 
here the new file:
[new files](https://drive.google.com/drive/folders/15j5KzyHJ_Yo0a9_a7WoRfXeuAy9gYsRN?usp=sharing)
