### ISSUE TITLE
Add location to ToC device's output

### ISSUE THREAD

**Issue by leoluecken** [eclipse/sumo#5705]
Should provide the coordinates and/or(?) lane+lanePos for each event.

**Comment by namdre** [comment]
@lbieker please updated the expected test results (https://sumo.dlr.de/daily/gcc4_64report/complex/test_default.html)

**Comment by schwamborn** [comment]
Restored test results for failing tests 

> ToC_with_sampled_responseTime
> dynamic_ToC
> dynamic_ToC_stop

I'm guessing that the corresponding output changes introduced in 50bd292 originate from running the tests with a different sumo version, or possibly with local uncommitted changes, @lbieker ?

**Comment by lbieker** [comment]
Thank you @schwamborn
