### ISSUE TITLE
saving sumocfg from netedit

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#5707]
once I have edited net and demand I would like to save the corresponding sumocfg from netedit (maybe also "open in sumo gui" should not only open the net but the demand as well)

**Comment by namdre** [comment]
* I propose to add checkboxes to Edit menu (include demand, include additionals to the Edit menu which modify the behavior of 'Open in SUMO GUI')
* I would leave the task of saving sumo configurations to sumo-gui (the netedit-option-dialog is modular) and avoid adding MSFrame as a netedit dependency.
