### ISSUE TITLE
Original setStop would vanish when the following setStop is created

### ISSUE THREAD

**Issue by YenKang** [eclipse/sumo#5712]
Dear @behrisch ,@namdre :

Due to your [help](https://github.com/eclipse/sumo/issues/5656#issuecomment-498710403), I can successfully execute the **setStop** function!
`conn.do_job_set(Vehicle.setStop(vehID, edge, pos+10, (byte)0, 0.0, sf, pos,until));`

![58600458-446b0080-82b7-11e9-816d-42df4922f84f](https://user-images.githubusercontent.com/16321107/58896861-7e119080-8729-11e9-9f9a-8e0d06dacfd5.png)

## However, now I meet a trick issue when I execute **setStop** **several times**, which would make some of the previous **setStop** information vanish.

For example, at 150 seconds, we executed the line (**success**)
`double until_1 = 500.0;`
`conn.do_job_set(Vehicle.setStop("1", edge1 , pos1, (byte)0,  0.0,  sf1, pos1, until_1));`
![2](https://user-images.githubusercontent.com/16321107/58897427-ddbc6b80-872a-11e9-825d-094e0107121e.PNG)

Furthermore, we runned the codes which had two setStop functions (one succeed, the other fails)
`double until_1 = 500.0;`
`onn.do_job_set(Vehicle.setStop("1", edge1 , pos1, (byte)0,  0.0,  sf1, pos1, until_1));`
`double until_2 = 800.0;`
`conn.do_job_set(Vehicle.setStop("1", edge2 , pos2, (byte)0,  0.0,  sf2, pos2, until_2));`

> ### The stop which would finish until 500.0 would not appear!!!

> ### The stop which would finish until 800.0 would appear!!!

![150-4444](https://user-images.githubusercontent.com/16321107/58897900-02fda980-872c-11e9-89ee-f31c2727bd8c.PNG)

When the time is in 250 seconds, we runned the three setStop functions. (two functions succeed, one failed)

```java
double until_1 = 500.0;
SumoStopFlags sf1 = new SumoStopFlags(false, false, false, false, false);
conn.do_job_set(Vehicle.setStop("1", edge1 , pos1, (byte)0,  0.0,  sf1, pos1, until_1));

double until_2 = 800.0;
SumoStopFlags sf2 = new SumoStopFlags(false, false, false, false, false);
conn.do_job_set(Vehicle.setStop("1", edge2 , pos2, (byte)0,  0.0,  sf2, pos2, until_2));
					
double until_3 = 1200.0;
SumoStopFlags sf3 = new SumoStopFlags(false, false, false, false, false); 
conn.do_job_set(Vehicle.setStop("1", edge3 , pos3, (byte)0,  0.0,  sf3, pos3, until_3));
```
> ### The stop which would finish until 500.0 would **appear again**

> ### The stop which would finish until 800.0 **vanished**.

> ### The stop which would finish until 1200.0 successful appear!

![3](https://user-images.githubusercontent.com/16321107/58898433-2543f700-872d-11e9-9c2e-a52dc6fbe3f0.PNG)

## Finally, I really want to know how to smoothly execute **setStop** function successfully after **duplicating** the **setStop**.

Thanks for your help!

Kang Yen

**Comment by namdre** [comment]
Thanks for reporting. Existing stops are updated when calling setStop with the same edge,lane and pos value.
Setting duration=0 can be used to remove a stop. However this is only supposed to happen when until is not set to a positive value (The condition on 'until' was broken and has now been fixed)
