### ISSUE TITLE
sumo  trace using for vanet

### ISSUE THREAD

**Issue by evalut** [eclipse/sumo#5716]

**Comment by evalut** [comment]
I want use sumo trace file  which has node position to vanet  ,so i need node position(x,y) during my simulation ,now i had put sumo trace file into ns3  and cofig right ,but when i running protocol  ,there is only the last position can be read in ,so i could not  obtained  the real time data correctly..

**Comment by namdre** [comment]
did you convert the trace file from sumo fcd-output with sumo/tools/traceExporter.py?
