### ISSUE TITLE
meso: densities exceed jam density

### ISSUE THREAD

**Issue by ambuehll** [eclipse/sumo#5723]
Might be related to #3265
Densities are too high when analysed in very short periods (3s). (Also for steady-state conditions! (edge_entered=edge_exited))
![image](https://user-images.githubusercontent.com/48930860/59052614-bdf28800-888f-11e9-9ce1-5d8d22423612.png)

This problem vanishes when time period is increased to e.g. 360s.
![image](https://user-images.githubusercontent.com/48930860/59052690-dfec0a80-888f-11e9-8163-d64f6f7126de.png)

**Comment by namdre** [comment]
I don't quite see the differences between the plot shapes.  The peak appears to be at ~7000 in both versions and the slopes look similar as well.

**Comment by ambuehll** [comment]
Density in the x-axis.

**Comment by namdre** [comment]
The downward slope points to (600, 0) in both cases. 
But i suppose your are talking about the tail at (800, 0). 

How many lanes does the road have and what are the vehicle lengths?
Are you still using segment length 50? Can you check with segment length 25 and 100?

**Comment by ambuehll** [comment]
Yes, the tail is my issue. 
Sure, will run the tests with 25 and 100 tomorrow. Thanks

**Comment by ambuehll** [comment]
Sorry about the delay. Here the results for 25, 50, 100. 
The artifact remains throughout all meso-edgel-length. 
![FDs](https://user-images.githubusercontent.com/48930860/59758606-95568f00-928e-11e9-9aa6-4c5db259a59e.png)

N.B. Interestingly, the FD becomes clearer with decreasing meso-edge length.

**Comment by ambuehll** [comment]
Apologies for bringing this up again...

This issue is still persistent, now also with longer aggregation levels. Here some example FDs for an OSM network. The densities are well beyond jam density and the edges are not short (i.e. up to 200m long). 

The jam density is at roughly 1000/(5 car length+2.5 minGap), but there is a second peak (with non zero flows for completely jammed) at 200, which is 1000/5m car length

Doesn't depend on meso-edge length, nor on tls penalty, jam treshold, or teleport. Changing taus doesn't seem to solve the issue either. 
The issue vanishes if minGap is set to 0. 

See [here](https://drive.google.com/drive/folders/1QmhobUaPRwEj06nEDiAD-Y0jYyd3yO3t?usp=sharing) for toy network (Zurich)
here the plotted edges:
"-146545816#0" "-4721156#0"   "-82956882"    "120613502#0"  "136214058#0"  "33693780#3"   "530012508#1"  "548370028#2"  "656591301#0" 

![image](https://user-images.githubusercontent.com/48930860/77260240-1829d180-6c87-11ea-9e71-5d7ec84675d2.png)

**Comment by namdre** [comment]
@ambuehll Here is what I've got so far: The high density is written as an upper bound computed from the minimum vehicle length that was observed: https://github.com/eclipse/sumo/blob/9f6f2cf5b34959befc60b53709b2763412b11d56/src/microsim/output/MSMeanData_Net.cpp#L278

I can easily fix this by using lengthWithGap instead of length alone. However, the fact that the upper bound is reached points to some deeper issue which I am still investigating. A minor point: your scenario uses minGap 1.5 rather than 2.5 as written above.

**Comment by ambuehll** [comment]
That's what I thought. Thanks!
I am sorry, you're right, minGap = 1.5m. 
Just thinking out loud, is it maybe related somehow to the fact that the taus are net-time headways instead of gross? Because that in essence means that throughput (1/tau_gross) is speed dependent.

I saw in Eissfeldt's thesis the following figure 
<img width="603" alt="image" src="https://user-images.githubusercontent.com/48930860/77761903-0787ab80-7039-11ea-90c4-5401ddf5be9e.png">
It seems that his model has some (numerical) issues for jam density.

**Comment by namdre** [comment]
The issue was triggered when vehicles were teleporting across multiple edges.
