### ISSUE TITLE
[Question] Does SUMO allow a smooth transition while overtaking?

### ISSUE THREAD

**Issue by IronicallySerious** [eclipse/sumo#5727]
I am looking for ways to let SUMO animate a full overtaking animation instead of just making the vehicle jump to the next lane while overtaking.

I also read that SUMO allows sublanes, which is an experimental feature as of now. Can using sublanes help my case?

**Comment by IronicallySerious** [comment]
Using sublanes with `--lateral-resolution 10` startup option solves this

**Comment by namdre** [comment]
Alternatively, consider https://sumo.dlr.de/wiki/Simulation/SublaneModel#Simple_Continous_lane-change_model

**Comment by IronicallySerious** [comment]
Thanks that looks even better
