### ISSUE TITLE
How to avoid collision in a junction?

### ISSUE THREAD

**Issue by wrs777** [eclipse/sumo#5728]
I wrote python codes to make cars cross the junction automatically without traffic light. I use the setspeedmode function and set the parameter as 31. At most times, the cars are able to brake in advance to avoid collision. However, sometimes, two cars run into each other as if they ignore other cars. I can't find where I did wrong.

**Comment by namdre** [comment]
What junction type do you use and what are the link states at the junction (m,M,g,G,...?)

**Comment by behrisch** [comment]
Closing due to missing input from @wrs777.
