### ISSUE TITLE
do number of passenger at a bus stop impact dwell time?

### ISSUE THREAD

**Issue by ambuehll** [eclipse/sumo#5733]
in routes, one can define triggered=true and expected= "some pax IDs"
-> does that mean it will take into account that more people (more IDs) need more time to enter the bus, hence changing the dwell time (automatically)?

if not -> feature request.

**Comment by namdre** [comment]
Each person takes a fixed time to board the vehicle (vType parameter boardingDuration) and the dwell time is automatically extended to let all persons board.
