### ISSUE TITLE
can not use ACC and CACC as car-following model

### ISSUE THREAD

**Issue by fengbaozhiling1** [eclipse/sumo#5734]
I have tried other kinds of car-following model such as Krauss, IDM, Wiedemann and it can work well. However, when I use the ACC/CACC model(see attached), it appears wrong and I could not handle with it. Please help me, thank you a lot! 
[acc.zip](https://github.com/eclipse/sumo/files/3276009/acc.zip)

**Comment by namdre** [comment]
What problems are you refering to specifically?

**Comment by fengbaozhiling1** [comment]
> What problems are you refering to specifically?

I could not run the "pe10.sumocfg" and I don't know why.
If I change the car following model from ACC to IDM or Krauss in "pe10.rou.xml",
(In other word, if I  change

`   <vType id="CarB" length="5" maxSpeed="30" carFollowModel="ACC" speedDev="0.0" emergencyDecel="5" speedFactor="1.0" departSpeed="30" departLane="best" lcSpeedGain="2" lcLookaheadLeft="200" lcAssertive="5" lcPushy="0.2"/>
`

to 

   <vType id="CarB" length="5" maxSpeed="30" carFollowModel="IDM" speedDev="0.0" emergencyDecel="5" speedFactor="1.0" departSpeed="30" departLane="best" lcSpeedGain="2" lcLookaheadLeft="200" lcAssertive="5" lcPushy="0.2"/>,

it can work well.)

So the problem is that the car-following model "ACC" can not be correctly used in this file. 
If I use ACC, I could not run the "pe10.sumocfg". If I use other models like IDM or Krauss, it works well.

**Comment by fengbaozhiling1** [comment]
> What problems are you refering to specifically?

I could not run the "pe10.sumocfg" and I don't know why.
If I change the car following model from ACC to IDM or Krauss in "pe10.rou.xml",
(In other word, if I change

<vType id="CarB" length="5" maxSpeed="30" carFollowModel="ACC" speedDev="0.0" emergencyDecel="5" speedFactor="1.0" departSpeed="30" departLane="best" lcSpeedGain="2" lcLookaheadLeft="200" lcAssertive="5" lcPushy="0.2"/>

to

<vType id="CarB" length="5" maxSpeed="30" carFollowModel="IDM" speedDev="0.0" emergencyDecel="5" speedFactor="1.0" departSpeed="30" departLane="best" lcSpeedGain="2" lcLookaheadLeft="200" lcAssertive="5" lcPushy="0.2"/>

it can work well.)

So the problem is that the car-following model "ACC" can not be correctly used in this file.
If I use ACC, I could not run the "pe10.sumocfg". If I use other models like IDM or Krauss, it works well.

**Comment by fengbaozhiling1** [comment]
I could not run the "pe10.sumocfg" and I don't know why.
If I change the car following model from ACC to IDM or Krauss in "pe10.rou.xml",
(In other word, if I change
<vType id="CarB" length="5" maxSpeed="30" carFollowModel="ACC" speedDev="0.0" emergencyDecel="5" speedFactor="1.0" departSpeed="30" departLane="best" lcSpeedGain="2" lcLookaheadLeft="200" lcAssertive="5" lcPushy="0.2"/>
to
<vType id="CarB" length="5" maxSpeed="30" carFollowModel="IDM" speedDev="0.0" emergencyDecel="5" speedFactor="1.0" departSpeed="30" departLane="best" lcSpeedGain="2" lcLookaheadLeft="200" lcAssertive="5" lcPushy="0.2"/>

it can work well.)
So the problem is that the car-following model "ACC" can not be correctly used in this file.
If I use ACC, I could not run the "pe10.sumocfg". If I use other models like IDM or Krauss, it works well.

**Comment by namdre** [comment]
This is not specific enough.
Do you get an error message and if so, what is the message?
Or does SUMO just crash?

**Comment by fengbaozhiling1** [comment]
> This is not specific enough.
> Do you get an error message and if so, what is the message?
> Or does SUMO just crash?

I get an error message and it says

Traceback (most recent call last):
  File "E:\limeng\TRB1\fixed.py", line 756, in <module>
    Q=acc10()
  File "E:\limeng\TRB1\fixed.py", line 462, in acc10
    traci.simulationStep()                 
  File "E:\SUMO\tools\traci\__init__.py", line 127, in simulationStep
    responses = _connections[""].simulationStep(step)
  File "E:\SUMO\tools\traci\connection.py", line 323, in simulationStep
    result = self._sendExact()
  File "E:\SUMO\tools\traci\connection.py", line 99, in _sendExact
    raise FatalTraCIError("connection closed by SUMO")
traci.exceptions.FatalTraCIError: connection closed by SUMO

you can run this acc.zip file and you can get the same wrong message

**Comment by fengbaozhiling1** [comment]
> > This is not specific enough.
> > Do you get an error message and if so, what is the message?
> > Or does SUMO just crash?
> 
> I get an error message and it says
> 
> Traceback (most recent call last):
> File "E:\limeng\TRB1\fixed.py", line 756, in 
> Q=acc10()
> File "E:\limeng\TRB1\fixed.py", line 462, in acc10
> traci.simulationStep()
> File "E:\SUMO\tools\traci__init__.py", line 127, in simulationStep
> responses = _connections[""].simulationStep(step)
> File "E:\SUMO\tools\traci\connection.py", line 323, in simulationStep
> result = self._sendExact()
> File "E:\SUMO\tools\traci\connection.py", line 99, in _sendExact
> raise FatalTraCIError("connection closed by SUMO")
> traci.exceptions.FatalTraCIError: connection closed by SUMO
> 
> you can run this acc.zip file and you can get the same wrong message

If you change the car-following model ACC to IDM in "pe10.rou.xml" file, There will be not any wrong message and it works well. Why is ACC not feasible in this file?

**Comment by namdre** [comment]
I cannot reproduce your issue because acc.zip does not include the traci script that you used.
When I run pe10.sumocfg, the simulation runs to completion as expected.
Can you trigger a crash without traci?

**Comment by fengbaozhiling1** [comment]
> I cannot reproduce your issue because acc.zip does not include the traci script that you used.
> When I run pe10.sumocfg, the simulation runs to completion as expected.
> Can you trigger a crash without traci?

Thank you a lot. I solved this problem. It is because I used the version of 1.0.1 instead of 1.2.0. Thank you sincerely!
