### ISSUE TITLE
Vehicles are hidden beneath their coloring bubble.

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#5735]
This makes it hard for the end user to check whether 3D-Models have been loaded correctly.

**Comment by namdre** [comment]
The propper solution would be to get rid of the bubble and figure out a generic way to recolor the models themselves.
A quick-fix could be to draw a flat oval beneath the vehicle rather  than enclose it in a bubble.

**Comment by m-kro** [comment]
Recently I played a bit with OpenSceneGraph and managed to recolor the vehicles themselves entirely, using additional osg::Material items. If the vehicle is textured, the view scheme color is added on top (not visible in the example image). 

Example image using the [bs3dosm sumocfg](https://github.com/eclipse/sumo/blob/3665087fdf29e4e158f2a90e8ced1a2fd37e3231/tools/game/bs3d.sumocfg):
![vehicleColourScheme](https://user-images.githubusercontent.com/33294728/151866693-74197192-c45e-4070-878e-46e81de56f82.png)

Should there be a fallback solution if the base model cannot be loaded? Moving lights without any vehicle body look quite strange ;-)

**Comment by namdre** [comment]
A default passenger car body as fallback would probably make the most sense.

**Comment by namdre** [comment]
@m-kro Are you planning to do a pull-request for this?

**Comment by m-kro** [comment]
Yes I do. Didn't have the time to implement the fallback solution yet - hopefully this week. Then I will do the pull request.

**Comment by namdre** [comment]
Awesome! Thanks!
