### ISSUE TITLE
question:  meso-tls-penalty

### ISSUE THREAD

**Issue by ambuehll** [eclipse/sumo#5746]
First of all, thanks for all the hard work put into the meso simulation!

I tried to understand the source code on the meso-tls-penalty.
I am not sure if I completely understand, thus here some questions:

1. Is the capacity of an intersection is reduced by changing the headways (as suggested in #2753)? If I understand correctly, it seems in the source code that the capacity is adjusted to (Cycle - meso-penalty * sum(Red)) / Cycle. In other words, if meso-tls-penalty is set to 0 (perfect coordination, the capacity is not reduced? Shouldn't the capacity be reduced to G/C independently of tls coordination?

`            myLinks[j][k]->setGreenFraction(MAX2((durationSeconds - MSGlobals::gMesoTLSPenalty * totalRedDuration[j]) / durationSeconds, NUMERICAL_EPS))
` 

2. The delay attributed to the tls coordination is a bit cumbersome. It seems that there are penalties due to the phases

`penalty[j] += 0.5 * (redDuration[j] * redDuration[j] + redDuration[j]); `

 which is then multiplied to the meso-tls-penalty 

` myLinks[j][k]-> setMesoTLSPenalty(TIME2STEPS(MSGlobals::gMesoTLSPenalty * penalty[j] / durationSeconds));`

 Any light shed on this calculation would be very helpful (any citable article is a plus).

As always, many thanks!

**Comment by namdre** [comment]
1). You are right. Capacity is independent of coordination in principle. There are two things at play here:
- setting an increased time headway for vehicles would be incorrect for perfect coordination when below capacity. (Of course, the way it is down now is quite wrong when above capacity).
- the code was implemented to deal with the fact that the green split in a large simulation network could not be adapted to the real green split (and was simply set to split the cycle evenly. Thus it would have been wrong to derive the capacities from this green split. I suppose it would make sense to provide two separate tuning parameters for the time penalty as well as the capacity penalty. 

2) The penalty is derived from the expected waiting time. For each second of the cycle, consider the waiting time for a vehicle that arrives at this second, sum the values and then divide by the cycle length. Vehicles arriving at green have no waiting time and for the other seconds it's a sum from 1 to redDuration (https://en.wikipedia.org/wiki/1_%2B_2_%2B_3_%2B_4_%2B_%E2%8B%AF)
