### ISSUE TITLE
Prevent cooperative lane change

### ISSUE THREAD

**Issue by Tarek-Gh** [eclipse/sumo#5750]
The lane change mode is set to be 0b011001010101 by default for all cars.
I need to prevent any scenario of cooperative lane change in my simulation.
I get that you can prevent a car from doing cooperative lane changes by doing the following:
`traci.vehicle.setLaneChangeMode(carid, 0b011001010001)`
but I couldn't find a way to apply this to all cars in my simulation. Is there any way to do so ?

**Comment by namdre** [comment]
set vType parameter lcCooperative="0"
