### ISSUE TITLE
meso: tls-penalty documentation

### ISSUE THREAD

**Issue by ambuehll** [eclipse/sumo#5758]
According to the doc, different settings of meso-tls-penalty result in different tls coordination. 1 is uncoordinated, 0 is said to be coordinated. However, I think 0 itself means "do not apply any penalty, use current tls settings". 
The following travel time distributions help to illustrate what I mean. Decreasing the penalty results in generally shorter travel times. This trend does not hold for 0. It seems that at 0 nothing is done to coordination (also seen in GUI), that's why the mean can be higher than 0.1 and 0.5.   

-> Adjust the documentation to exclude 0? Adding the formula discussed in #5746 would also be nice. 

![image](https://user-images.githubusercontent.com/48930860/59862755-a92fed00-9383-11e9-97f4-976ba1c5209c.png)

BTW, I looked into the signal coordination in more details. Here some results, that might be of interest:

1. The FD (120s aggregate values) changes, but remains intact in its form. 
![FD](https://user-images.githubusercontent.com/48930860/59868729-f0bd7580-9391-11e9-9f08-5ecb84d60cc2.png)

2. The comparison between maximum flow when tls-penalty=0 vs tls-penalty>0  on all links in the simulation. For most links, the maximum flow (veh/h) does not change substantially. 
![image](https://user-images.githubusercontent.com/48930860/59869078-bdc7b180-9392-11e9-98a2-af426acc4f51.png)

Both results put the discussion in #5746 into perspective - i.e. the effects on traffic dynamics are fine - also when using tls-penalty>0.

**Comment by namdre** [comment]
I've updated the documentation to properly describe the behavior when setting meso-tls-penalty=0.
Thanks for pointing it out.
