### ISSUE TITLE
Why we couple the SUMO and other simulators like NS2?

### ISSUE THREAD

**Issue by suraty** [eclipse/sumo#5759]
Hello,

I am a beginner in SUMO simulator, I studied some papers in urban traffic simulation that they have coupled SUMO and other simulators like NS2 for their implementation.
Why they couple the SUMO and other simulators like NS2?
What is impossible in SUMO that we need to couple the SUMO and NS2?

Thank you

**Comment by namdre** [comment]
SUMO does not model communication protocols and communication networks. It only models mobility.
