### ISSUE TITLE
Cannot convert a custom opendrive map

### ISSUE THREAD

**Issue by cmpute** [eclipse/sumo#5760]
Thanks for your great work! I'm trying to port an opendrive map to sumo. I ran command `netconvert --opendrive-files opendrive03.txt -o map03.net.xml` and comes to an assertion error: 
```
<many warnings...>
netconvert: /build/sumo-t9zLet/sumo-1.2.0+dfsg1/src/netbuild/NBNodeShapeComputer.cpp:121: void computeSameEnd(PositionVector&, PositionVector&): Assertion `l2[0].distanceTo2D(l2[1]) >= 100.' failed.
Aborted (core dumped)
```

I'm currently using the tool on Ubuntu 18.04 with SUMO 1.2.0 installed from ppa repository. I also tried this command on Windows which didn't prompt assertion errors, but the result map is incorrectly twisted in some part. This should be that SUMO binary in ppa repo is not built with release configuration?

The map file can be [downloaded here](https://drive.google.com/file/d/1Tra1buqmGDfD9SA-1vcmK6ngkRqzoZ6Z/view?usp=sharing)

**Comment by namdre** [comment]
@behrisch Any idea why the ubuntu ppa would be compiled with assertions?

**Comment by namdre** [comment]
@cmpute You may find the netconvert results closer to your expectations when adding option:  
`--opendrive.import-all-lanes`

**Comment by cmpute** [comment]
Thanks! Is this assertion a mis-reported error or it actually affect something?

**Comment by namdre** [comment]
It indicated mishandling of extremely short roads. Thus, the assertion was valid and the handling of short roads was changed.

**Comment by cmpute** [comment]
Another thing is that, I found some map points from opendrive are not perfectly converted. For example in [this map](https://drive.google.com/file/d/1up1FtG-xIx3sxHeVnSg2KyYUPl88xJdT/view?usp=sharing) point `66, -260.3` in original map is inside a lane, but when converted to SUMO map, the point is outside any lanes. Could you also look into this? Thanks.

**Comment by cmpute** [comment]
Here I also created a comparison picture showing the original opendrive map and converted sumo map for the file above. It's down by screenshoting both SUMO GUI and OpenDrive Viewer. There's some parts aligned well and other parts not. I guess it would be related to some lane width settings? The convert command is the same as one on the top.

![map_compare](https://user-images.githubusercontent.com/9154441/60149173-d1fc1c00-97a1-11e9-867e-f6a205a0c843.jpg)

**Comment by namdre** [comment]
The mismatch is related to #4913.
When setting option `--opendrive.import-all-lanes` the mentioned point is on a lane and the mismatch disappears.
To understand what's going on, change the sumo-gui visualization settings so that 'green verge' lanes are visible (by default their alpha value is set to 0).

Also, when comparing with odrViewer, it may helpful to add the netconvert option `--offset.disable-normalization` as that will keep the original coordinates.

**Comment by cmpute** [comment]
@namdre Thanks! This helps a lot. Also, using `--offset.disable-normalization`, the map on the top can also be successfully converted.

**Comment by behrisch** [comment]
> 
> 
> @behrisch Any idea why the ubuntu ppa would be compiled with assertions?

I have no idea and did not find any clue in the build files :-(
