### ISSUE TITLE
Add W99 (10-Parameter Wiedemann version) model

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#5765]
maybe this avoids issues with the current implementation (#3946, #5715, #5754)
Also, the 10-Parameter version appears to be better known.

* http://w99demo.com/
* https://github.com/glgh/w99-demo

**Comment by palvarezlopez** [comment]
@namdre also in NETEDIT?

**Comment by namdre** [comment]
W99 already shows up in the car Following Model list.
