### ISSUE TITLE
tls-guess for complex intersections (from OSM)

### ISSUE THREAD

**Issue by ambuehll** [eclipse/sumo#5773]
I am importing many OSM networks, and tls are guessed well for most cases. There are some (odd) behaviors for certain complex intersections. I understand that guessing/setting tls is not a trivial task, nonetheless, I believe some improvements can be made to the current implementation. Procedure so far:
1. Import OSM traffic signals by setting discard-loaded = false and discard-simple = true.
2. Guessing additional tls by setting tls-guess = true with a treshold of X (depending on the speeds defined).

![image](https://user-images.githubusercontent.com/48930860/60257735-31f2df80-98d4-11e9-8e77-ca14b5e28a00.png)

My problem is that if I use 1. only, I lack many important tls (not just at the two intersections shown). If I add 2. there are many unnecessary tls. This is not as grave as one could imagine, because they are then coupled with the same logic (however, in meso, such layout will still add waiting time #5758). 

There are multiple issues in the intersections shown, but some solutions could be:
->  Do not add tls when node degree is 2 if they were not build from OSM (discard-loaded = false) (see orange circled tls). 
->  Do not add tls if the only difference is that downstream links have more lanes (possibly splitting) AND are one-way (see yellow circled tls).
->  If the distance to the last tls is small and phases are identical, remove redundant tls. (Do not create tls right downstream of a signalized intersection).  

As always, many thanks!
reproducible with SUMO Version v1_2_0+0837-4e29156304
and [files](https://drive.google.com/drive/folders/1nTBXhe6rQBKmsWKWWEAJBiw6Xuzp3pwF?usp=sharing)

**Comment by namdre** [comment]
Explanation: there are three stages to tls guessing and joining
1) guess whether a cluster of uncontrolled nodes could be jointly controlled
2) guess whether single nodes should be tls-controlled (--tls.guess)
3) joined individual tls into a joint controller (--tls.join)

Before cdbeadb1671a36443c1033454e02c5db5644a8e3, step 1)  was always active when options --tls.guess and --tls.join were set. Now this step is optional and only activated by setting option --tls.guess.joining (deactivated by default)

I stronlgy suspect that step 1 is responsible for your issues so I recommend that you rebuild your network and check.

Still, I would like to improve the working of step 1. For that I twould be really helpful if you could provide smaller network snippets (about as big as in your screenshot). You shoud be able to get those easily by retrieving the geo-coordinate from sumo-gui and the downloading a small rectangle using osmWebWizard.

**Comment by ambuehll** [comment]
Thanks for looking into this! I updated the [files](https://drive.google.com/drive/folders/1nTBXhe6rQBKmsWKWWEAJBiw6Xuzp3pwF?usp=sharing). Both intersections are now included "planet.osm" and "planet2.osm". 
I'll double check tomorrow with the new build.

**Comment by ambuehll** [comment]
Here some comments:
1. some of the problems were due to tls-uncontrolled-within (my mistake, sorry)
2. Setting tls.guess.joining true does indeed help to reduce the number of problems further in the newest build.
3. There are some weird behavior:
a.   on the second complex intersection (planet2.osm), all phases are green at all times. I am not sure how this could be improved, as there are many relations...
![image](https://user-images.githubusercontent.com/48930860/60659565-fc12a580-9e55-11e9-82ee-93cf25c5da14.png)
b.  using tls.guess.joining true creates **errors** in the GUI for some networks. 
 `Error: Invalid linkIndex '9' in connection controlled by 'joinedS_1'
Error: Invalid linkIndex '10' in connection controlled by 'joinedS_1'
Loading of net-file failed.
Quitting (on error).`
This is the case with "planet4.osm" in the files.

**Comment by namdre** [comment]
I find this surprising because tls.guess.joining=true is the old behavior and what I actually tried to recommend is to rebuilt with the new default of tls.guess.joining=false (because all the issues you mentioned disappear when rebuilding your small test networks with the new default)

**Comment by ambuehll** [comment]
tls.guess.joining=false
![image](https://user-images.githubusercontent.com/48930860/60666919-88c65f00-9e68-11e9-9326-873f3f394d65.png)
vs 
tls.guess.joining=true
![image](https://user-images.githubusercontent.com/48930860/60666965-a85d8780-9e68-11e9-944b-0ac92ea3657c.png)

I think either way is fine (at least for meso). Any ideas on 3a?

**Comment by namdre** [comment]
3a is caused by the combination of 3 things
- tls.guess.joining=true
- tls.uncontrolled-within=true
- a bug in the code that checks whether any given 2 streams at a joined controller are in conflict. This code only checks direct successor edges of both streams and gives incorrect results at large clusters without intermediate traffic lights

**Comment by ambuehll** [comment]
OK. thanks! I would then classify 3a as a bug.

**Comment by ambuehll** [comment]
resolved in 1.4
