### ISSUE TITLE
Netedit discards node to geometry point conversion

### ISSUE THREAD

**Issue by m-kro** [eclipse/sumo#5777]
Two sequential edges are be converted to one by converting the node into a geometry point. After using the context option in my example, the joined edge is displayed in Netedit (1_2_0+0830). But after recomputing the network, only the previous upstream part is saved and the downstream part is discarded. 
Try node gneJ190 in the attached example:
[TT_VV_test.net.xml.zip](https://github.com/eclipse/sumo/files/3339361/TT_VV_test.net.xml.zip)

**Comment by namdre** [comment]
was related to having a custom junction shape at the end.
