### ISSUE TITLE
weight modify

### ISSUE THREAD

**Issue by JaneCheung** [eclipse/sumo#5778]
Dear all
Is there any methods that I could change (or cover) the travel time cost which is used by SUMO to be treated as  the edge  Weight. 

For this problem, I would like to know,
1) Howe  SUMO reads the edge travel  time while it is running?
2) How could I change the travel time cost  of one specific  edge?
For example, 
The travel time cost for EedgID =''2"  is 2s and I would like to change it to 4s (which could not be the real travel time cost, the reason that I would like to change is to mark this edge as a more important edge and give it a more probability to be selected for vehicles travel in the network  just as an example). 
Could I do it while the SUMO is running?

Best  regards!

**Comment by JaneCheung** [comment]
The things that I would like to do is to change the probability that one edge would be chosen while simulating .
For the **TAZ file** could only decide the one edge to be chosen as the start and end  of a route. 
How could I change the probability that one edge chosen while **rerouting**

**Comment by namdre** [comment]
You can affect the probability by setting a custom travel time for the network edges.
See https://sumo.dlr.de/wiki/Simulation/Routing#Travel-time_values_for_routing
and https://sumo.dlr.de/wiki/Demand/Automatic_Routing#Randomness

**Comment by rahelehzarei** [comment]
I think you can also the formula mentioned in this link https://sumo.dlr.de/wiki/Demand/Automatic_Routing
in Adapting by exponential average section.
