### ISSUE TITLE
traci.simulation.convert2D issues

### ISSUE THREAD

**Issue by sapirbm** [eclipse/sumo#5780]
hey,
i have a couple of issues with convert2D.

1. at the very end of edges, sometimes the last 0.2meter is converted to the same x,y coordinates. (i am working with high demand for position precision), the net have been converted from opendrive using "--opposites.guess.fix-lengths true" together with a lot of other flags, could that be in charge of the mismatch?

![image](https://user-images.githubusercontent.com/21673117/60397844-05e89000-9b5a-11e9-8710-c7aec32ea4a8.png)
in the image you can see the lane position (left value) and the same x,y output (mid & right values)

2. when i try to convert between road and x.y conventions, there is a mismatch between the results of convert2D(edge, lane_pos, lane_index) and vehicle.getPosition(). mostly in favor of getPosition.

thanks a lot,
Sapir.

**Comment by behrisch** [comment]
Can you share your network?

**Comment by sapirbm** [comment]
[tmp_hptvi9r.zip](https://github.com/eclipse/sumo/files/3348451/tmp_hptvi9r.zip)

my example above was received at the end of edge 22.0.00_1 before a left turn 

netconvert from opendrive with flags:
--output.original-names true
--opendrive.advance-stopline 0
--default.junctions.radius 0
--junctions.small-radius 0
--opendrive.internal-shapes true
--junctions.limit-turn-speed 0
--default.speed 50.0
--opposites.guess true
--opposites.guess.fix-lengths true
--precision 8
--no-warnings true
