### ISSUE TITLE
Netedit: junction next to custom shape not selectable in move or tl mode

### ISSUE THREAD

**Issue by ZoltanBaksa** [eclipse/sumo#5781]
I have a bigger junction with custom shape, and next to it more small junctions with TL controls. When I want to move some elements near the big junction, the move will be done on the big junction, not on the desired element. In TL mode, although I click outside the shape, over a small TL controlled junction, I see only the big junction's properties.
In inspect mode I can select the small junction with some clicks, the listing of nearby objects works properly. On request I can send network via email, but I cannot attach it to the issue...
Used SUMO version:
v1.2.0+0837-4e29156304

**Comment by namdre** [comment]
related to #5767. (The  bounding box of the big junction may encompass the smaller junction even if they do not overlap).

@Pablo: My suggestion to fix this:
- add a dotted boundary when clicking an a non-selected object in move mode 
- add a move-mode frame that shows overlapped objects just like inspect mode
- allow cycling the object-to-be moved with multiple clicks on the same location (just like inspect mode)

**Comment by palvarezlopez** [comment]
Fixed in #4903. Insect TLS and mark it as front element.
