### ISSUE TITLE
Arrival Position and Depart Position Value Error

### ISSUE THREAD

**Issue by nnuk** [eclipse/sumo#5784]
Hi,

I was doing some routing on a OSM map in Sumo. When I play the simulation of the configuration file I get this error. 

**Error**: Invalid arrivalPos definition for walk 'person 'person0' walking from 198727654_1';
 must be one of ("random", "max", or a float)
Quitting (on error).

The **xml code** that my routing file has is in the attached file.
[RoutingFile.pdf](https://github.com/eclipse/sumo/files/3346686/RoutingFile.pdf)

Can anyone help me regarding this issue? I think that arrival pos and depart pos used in the code are in X Y format and Sumo documentation says that we have to use these positions with unit "m". So I don't know how to convert. Hope it helps understanding the question.

Thanks.

**Comment by namdre** [comment]
ArrivalPosition must be given as an offset along the edge as a single number (which is then interpreted as meters). If the edge is 100m long then arrivalPos="55" would let the person arrive 5 meters after the middle. (in vehicle driving direction).
