### ISSUE TITLE
the wrong  output of Summary.xml

### ISSUE THREAD

**Issue by JaneCheung** [eclipse/sumo#5785]
Dear all,
While I stop the simulation of SUMO  while it is still running and has not get the end . 
the output of **summary .xml** has something wrong , the problem is that  the output in summary.xml  is not right:
the meantraveltime  are all the '-1'

If I let the simulation end at the time it has setted， the  meantraveltime at the same time has it value

[withoutTraci_smmary.txt](https://github.com/eclipse/sumo/files/3347342/withoutTraci_smmary.txt)
[withTraci_smmary.txt](https://github.com/eclipse/sumo/files/3347343/withTraci_smmary.txt)

**Comment by namdre** [comment]
The meanTravelTime is only computed for vehicles that have finished their trip. Your traci code somehow keeps vehicles in the network (ended is always 0) and therefore meanTravelTime is not computed.
Note, that withoutTraCi_smmary.txt only outputs meanTravelTime other than -1 once ended > 0.

**Comment by JaneCheung** [comment]
Could  I know why the question is INVALID?

**Comment by JaneCheung** [comment]
In is case, is there some method that I could use to read or retrieve the meantravetime for all the vehicles which have finished and unfinished their trip.

**Comment by JaneCheung** [comment]
Another question , the duration in the summary.xml is very big, how to convert it to the time as the traditional type of time is represented?

**Comment by namdre** [comment]
sumo option --human-readable-time stores time as [DD:]HH:MM:SS

You can use option --duration-log.statistics along with option --tripinfo-output.write-unfinished to retrieve the mean traveltime. (Duration; ...) but this value will only be printed at the end of the simulation.
