### ISSUE TITLE
How to write a new car-following model which considers driving behaviors?

### ISSUE THREAD

**Issue by fengbaozhiling1** [eclipse/sumo#5791]
I want to simulate a real traffic oscillation in SUMO because the car-following model like IDM in SUMO did not consider the aggressive and timid driver as well as the change of tau after experiencing oscillation. 
I could not reproduce an traffic oscillation using IDM or other car-following model. Is it possible to write a new car-following model which is not based any other models ?
(car following model like: 
Laval, J. A., Toth, C. S., & Zhou, Y. (2014). A parsimonious model for the formation of oscillations in car-following models. Transportation Research Part B: Methodological, 70, 228-238.
Chen, D., Laval, J., Zheng, Z., & Ahn, S. (2012). A behavioral car-following model that captures traffic oscillations. Transportation research part B: methodological, 46(6), 744-761.
)

**Comment by behrisch** [comment]
Without having looked a the references, you can in general implement arbitrary car following models, just use one of the existing ones in [src/microsim/cfmodels](https://github.com/eclipse/sumo/tree/master/src/microsim/cfmodels) as a template. Please also see https://sumo.dlr.de/wiki/Developer/How_To/Car-Following_Model
