### ISSUE TITLE
Pedestrian Flow generates too many vTypes

### ISSUE THREAD

**Issue by jimonreal** [eclipse/sumo#5792]
When creating a Flow of pedestrians, the script creates a vType for each pedestrian.
This could be fixed, by adding only once the Type if not given. And if the type is given we assume that is defined in the additionals or somewhere.

**Comment by namdre** [comment]
the tool pedestrianFlow is obsolete. You can use the xml element `<personFlow>` directly. 
The reason behind defining a vType for every person was to get a distribution of properties but you can get this by using a vTypeDistribution for the personFlow.
