### ISSUE TITLE
Could not find the file in <SUMO_HOME>/src/microsim/cfmodels

### ISSUE THREAD

**Issue by fengbaozhiling1** [eclipse/sumo#5795]
When I develop a new car-following model, I could not find the file MSCFModel_KraussOrig1.h and the path <SUMO_HOME>/src/microsim/cfmodels in Version 1.2.0.
[https://sumo.dlr.de/wiki/Developer/How_To/Car-Following_Model](url)
This page was updated in 2017 so maybe it is not suitable for this version 1.2.0? (i.e. I am not sure if I can develop a new car-following model according to this tutorial page)

**Comment by m-kro** [comment]
https://github.com/eclipse/sumo/blob/master/src/microsim/cfmodels/MSCFModel_KraussOrig1.h 
Nothing changed...

**Comment by fengbaozhiling1** [comment]
> https://github.com/eclipse/sumo/blob/master/src/microsim/cfmodels/MSCFModel_KraussOrig1.h
> Nothing changed...

I can find MSCFModel_KraussOrig1.h in website but I could not find it in installed zip. The change in website can not be used in my computer.

**Comment by m-kro** [comment]
Which SUMO archive did you download? If you want v. 1.2.0, the source files are on [Sourceforge](http://prdownloads.sourceforge.net/sumo/sumo-src-1.2.0.zip?download) and on [Github](https://github.com/eclipse/sumo/archive/v1_2_0.zip), both include the header file you mentioned.

**Comment by fengbaozhiling1** [comment]
> Which SUMO archive did you download? If you want v. 1.2.0, the source files are on [Sourceforge](http://prdownloads.sourceforge.net/sumo/sumo-src-1.2.0.zip?download) and on [Github](https://github.com/eclipse/sumo/archive/v1_2_0.zip), both include the header file you mentioned.

I want to use the v. 1.2.0 and I download the version in your link [Sourceforge](http://prdownloads.sourceforge.net/sumo/sumo-src-1.2.0.zip?download). But there are not sumo-gui and netedit in the sumo-1_2_0 zip. How can I edit the network and run the simulation? 
Thanks for your help!

**Comment by m-kro** [comment]
Well, you will have to build the projet yourself anyway if you add a new car-following model. Read more about that in the [SUMO wiki](https://sumo.dlr.de/wiki/Developer/Main) under "build instructions". If you want to use pre-compiled binaries, they are available, too, at the usual download sites (see [https://sumo.dlr.de/wiki/Downloads](https://sumo.dlr.de/wiki/Downloads)).

**Comment by fengbaozhiling1** [comment]
> Well, you will have to build the projet yourself anyway if you add a new car-following model. Read more about that in the [SUMO wiki](https://sumo.dlr.de/wiki/Developer/Main) under "build instructions". If you want to use pre-compiled binaries, they are available, too, at the usual download sites (see https://sumo.dlr.de/wiki/Downloads).

This work might be a little difficult for a c++ beginner. But thank you sincerely!
