### ISSUE TITLE
make netbuild node-type guessing constant configurable

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#5799]
Current, there is a fixed threshold of 49km/h that controls whether the junction type may be guesses as right-before-left

**Comment by namdre** [comment]
@ambuehll The legal speed limit is used as part of the node-type heuristic. If you set a lower edge speed to model typical driver behavior, you will interfere with this heuristic and should consider changing the speed threshold (--junctions.right-before-left.speed-threshold)

**Comment by ambuehll** [comment]
Perfect! Thanks.
