### ISSUE TITLE
SUMO Crashed in container scenario

### ISSUE THREAD

**Issue by MelanieWeber** [eclipse/sumo#5801]
SUMO Crashed in container scenario.

No futher information, just crashed when I start it.

(see files)

**Comment by namdre** [comment]
so what happend? A crash usually demands some kind of fix even when caused by invalid inputs.

**Comment by MelanieWeber** [comment]
I thought it would crashed because I used ride instead of transport on a conainer route, but it might not be the problem because if I use the transship/transport on containerFlow the simulation also crashed. So I think the problem is somewhere with the ConatinerFlow.

I also add the new files into the bugreport folder.
ContainerRoute.rou.xml,  work (just container routes (transport/transship))
ContainerFlow.rou.xml,  CRASHED (container routes (transport/transship) and containerFlow)

**Comment by namdre** [comment]
containerFlow is not implemented yet.
