### ISSUE TITLE
How can I set the desired speed of IDM model?

### ISSUE THREAD

**Issue by fengbaozhiling1** [eclipse/sumo#5804]
How can I set the desired speed of IDM model? Is it the "maxSpeed" in vType Attributes?  What if the "speedLimit" is smaller or larger than "maxSpeed"?
For example, the speedLimit is 30m/s, maxSpeed is 33m/s, then what is the desired speed of IDM?
Another problem. It says if the departSpeed is unsafe, departure is delayed. So what is the safe speed for IDM model?

**Comment by namdre** [comment]
The desired speed is MIN(maxSpeed, speedLimit * speedFactor)
The safe speed at insertion is computed based  on the speed and gap of the leading vehicle so I cannot give you a single numer as an answer. See MSCFModel_IDM::insertionFollowSpeed.

**Comment by fengbaozhiling1** [comment]
> The desired speed is MIN(maxSpeed, speedLimit * speedFactor)
> The safe speed at insertion is computed based on the speed and gap of the leading vehicle so I cannot give you a single numer as an answer. See MSCFModel_IDM::insertionFollowSpeed.

Thanks for your help. But there truly exist some problems in IDM model. I have used that model but it could not produce a correct traffic oscillation when I add a disturbance to the traffic. 
The parameters are set according to some papers: length="5" maxSpeed="30" carFollowModel="IDM" tau="1.4" accel="1" decel="2" speedFactor="1.0" minGap="2" delta="4" stepping="1.5".
The wave speed of oscillation produced by IDM model is less than 3m/s (10.8km/h), which is unrealistic since the wave speed should be 15 to 20 km/h according to empirical data.

**Comment by namdre** [comment]
I've tested this with a flow of vehicles on a single lane where the first vehicle stops briefly.
At maximum density (achievable with vehicle options departSpeed="max" departPos="last") I'm seeing a wave speed of 4.8m/s using the default IDM parameters

**Comment by fengbaozhiling1** [comment]
> I've tested this with a flow of vehicles on a single lane where the first vehicle stops briefly.
> At maximum density (achievable with vehicle options departSpeed="max" departPos="last") I'm seeing a wave speed of 4.8m/s using the default IDM parameters

You are so kind to me! I also tested a flow of vehicles on a single lane where the first vehicle stops briefly (with vehicle options departSpeed="max" departPos="last"). But the wave speed is even 0 using default IDM parameters. I don't know why. It is very significant to me so I ask for your help sincerely! 
If possible, can you send your files to me or check my files and find the problem(see attachment)?
[test.zip](https://github.com/eclipse/sumo/files/3363129/test.zip)

**Comment by fengbaozhiling1** [comment]
If I set a high flow rate larger than 800veh/h to increase density, the departure will be delayed, contributing to a low density. So the vehsPerHour="800" in my files.

**Comment by namdre** [comment]
The departSpeed and departPos options must be set for the flow rather than the vType element. Since 'last' inserts at the end of the edge when there are no predecessor vehicles, you either need to add another edge or insert another vehicle to avoid all vehicles exiting immediately.

**Comment by fengbaozhiling1** [comment]
> The departSpeed and departPos options must be set for the flow rather than the vType element. Since 'last' inserts at the end of the edge when there are no predecessor vehicles, you either need to add another edge or insert another vehicle to avoid all vehicles exiting immediately.

I have inserted another vehicle to avoid all vehicles exiting immediately:
`   <vType id="CarA" maxSpeed="30" carFollowModel="IDM" speedDev="0.0" speedFactor="1.0"/>
   <route id="route0" edges="BL1" />
   <vehicle id="0" type="CarA" route="route0" depart="0" color="1,0,0" departSpeed="max"/>
   <flow id="a" color="1,1,0"  begin="0" end= "1000" vehsPerHour='2500' type="CarA" departSpeed="max" departPos="last">
     <route edges="BL1"/>
`
The first vehicle stops for 50s and then recover to free flow speed.
But the oscillation only lasted for 150s from 100 to 250 and disappeared soon (see testFig). The width of the oscillation decreased dramatically.
![testFIg](https://user-images.githubusercontent.com/44236971/60764629-e3a5c380-a0bf-11e9-9ff8-63f98a8f74cc.jpg)
So is it possible to produce a oscillation which can propagate longer and farther because the traffic wave sometimes propagates longer and doesn't decay in real world. So what kinds of parameters in IDM models should I revise to achieve a steady and longer oscillation (attachment is my files).
[test.zip](https://github.com/eclipse/sumo/files/3365329/test.zip)

**Comment by fengbaozhiling1** [comment]
Or is there other car-following model which can produce a steady traffic wave and never decay under the condition of maximum density?

**Comment by namdre** [comment]
I you set the 'accel' paramete to 1.2 you will get a growing jam wave with IDM.
The same holds true for the Krauss model (but there you can also use the 'sigma' parameter to influence jam stability).

**Comment by fengbaozhiling1** [comment]
> I you set the 'accel' paramete to 1.2 you will get a growing jam wave with IDM.
> The same holds true for the Krauss model (but there you can also use the 'sigma' parameter to influence jam stability).

Excellent! Your comment help me a lot. Thank you sincerely!
