### ISSUE TITLE
Facing issue during installation of SUMO

### ISSUE THREAD

**Issue by SrilekhaPavuluri** [eclipse/sumo#5814]
While installing SUMO, it is throwing error saying that required libraries are not found even after manually installing all the required libraries.
Logs of the issue are attached below- 
"
 srilekha@ubuntu:~/Downloads/sumo-master/build/cmake-build$ cmake ../..
 -- CMAKE_BINARY_DIR: /home/srilekha/Downloads/sumo-master/build/cmake-build
 -- CMAKE_SOURCE_DIR: /home/srilekha/Downloads/sumo-master
 -- Platform: 
 -- Host: Linux-4.15.0-54-generic x86_64
 -- Target: Linux-4.15.0-54-generic x86_64
 -- CMake: 3.15.0-rc3
 -- CMake generator: Unix Makefiles
 -- CMake build tool: /usr/bin/make

 -- Compiler: GNU 5.4.0
 -- Found Python: /usr/bin/python
 Traceback (most recent call last):
 File , line 1, in <module>
 ImportError: No module named setuptools
 -- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_MAIN_LIBRARY) 
 -- Could NOT find suitable FFmpeg.
 -- Could NOT find Java (missing: Java_JAVAC_EXECUTABLE Java_JAVAH_EXECUTABLE Java_JAVADOC_EXECUTABLE) (found version 1.8.0_212)
 -- Could NOT find JNI (missing: JAVA_INCLUDE_PATH JAVA_INCLUDE_PATH2 JAVA_AWT_INCLUDE_PATH) 
 -- Could NOT find Git (missing: GIT_EXECUTABLE) 
 -- CPACK_GENERATOR: ZIP
 -- Enabled features: Linux-4.15.0-54-generic x86_64 GNU 5.4.0 Release Proj GUI GDAL OSG GL2PS SWIG
 -- Configuring done
 -- Generating done
 -- Build files have been written to: /home/srilekha/Downloads/sumo-master/build/cmake-build
"
In the above logs, it is mentioned that " Couldn't find GTest, FFmpeg, Java, JNI, Git ", but all those libraries are installed manually.
Could you please check into this issue.
Here I am attaching complete log details file :-
[SUMO Logs.txt](https://github.com/eclipse/sumo/files/3372911/SUMO.Logs.txt)

**Comment by behrisch** [comment]
@srilekha-tcs What do you mean by installed manually? Did you use something like `sudo apt-get install git` or compile them yourself? Which ubuntu version are you using?

**Comment by behrisch** [comment]
Closing since there seems to be no further reaction. Please reopen if problems persist.
