### ISSUE TITLE
Meso: unsignalized intersections (node type)

### ISSUE THREAD

**Issue by ambuehll** [eclipse/sumo#5816]
It seems as if the node type in a network does not play any importance for unsignalized intersections in meso. The travel time distribution remains identical.  
I tested by directly modifying the net file directly from right-before-left to allway-stop etc. (I know this is not advised). 
Same holds for tls allowing right-turn-on-red.

Is that correct? Then I suggest editing the sentence in the doc: "junctions are modeled as in the simplified microsim model" (which I am assuming refers to no-internal-links). 

Here some test [files](https://drive.google.com/drive/folders/1d6lnQgNGAzrO_q4lSpwoAQf06Vk0c85a?usp=sharing).

**Comment by namdre** [comment]
The simulation behavior is not influenced by the type attribute in the `<junction> `element. Instead, setting a different type causes netconvert to modify the `<request>` elements as well as the `<connection>` state attribute.

... and this is the reason why editing the .net.xml file diretly is not advised
