### ISSUE TITLE
Error in netconvert trying to convert some plain xml files

### ISSUE THREAD

**Issue by alexdawn** [eclipse/sumo#5817]
When I run the following command on netconvert 1.2.0:
`netconvert --node-files="road_network.nod.xml" --edge-files="/road_network.edg.xml" --verbose --output-file="road_network.net.xml" --lefthand --log netconvert.log`

Using two xml files (attached at the bottom of the ticket) I've generated with a script to convert to plain xml for another format.

I get the follow error in the log file. 

```
Building inner edges... 
Error: no line intersection
```

Without any previous errors or warnings to suggest what might be wrong. I'm not familiar with the project and don't understand the error message so I don't know if there is a mistake with the input files or an bug with the program. Please can you help suggest what might be wrong? The full log is as follows:

```
Parsing nodes from './model_input/road_network.nod.xml'... done.
Parsing edges from './model_input/road_network.edg.xml'... done.
 Import done:
   102 nodes loaded.
   177 edges loaded.
Removing self-loops... done (1ms).
Removing empty nodes... done (2ms).
   39 nodes removed.
Moving network to origin... done (2ms).
Computing turning directions... done (2ms).
Assigning nodes to traffic lights... done (2ms).
Sorting nodes' edges... done (2ms).
Computing node shapes... done (6ms).
Computing edge shapes... done (4ms).
Computing node types... done (1ms).
Computing priorities... done (2ms).
Computing approached edges... done (3ms).
Guessing and setting roundabouts... done (2ms).
Computing approaching lanes... done (4ms).
Dividing of lanes on approached lanes... done (3ms).
Processing turnarounds... done (1ms).
Rechecking of lane endings... done (3ms).
Computing traffic light control information... done (4ms).
Computing node logics... done (7ms).
Computing traffic light logics... done (2ms).
 6 traffic light(s) computed.
Building inner edges... 
Error: no line intersection
Quitting (on error).
```

[road_network.nod.xml.txt](https://github.com/eclipse/sumo/files/3373858/road_network.nod.xml.txt)
[road_network.edg.xml.txt](https://github.com/eclipse/sumo/files/3373859/road_network.edg.xml.txt)

**Comment by alexdawn** [comment]
Ah sorry I believe some of the lanes widths were ridiculously wide due to scaling issues, this is probably the cause of the unclear error message

**Comment by ambuehll** [comment]
yes, you should reduce your width drastically. that solves your issues.
