### ISSUE TITLE
netedit

### ISSUE THREAD

**Issue by JaneCheung** [eclipse/sumo#5818]
Dear all 
While I use  the NETEDIT  to modify the length of the edge, the edge value could only be changed on the left pannel. The value on the net file still  could change, the POS value did not change.

![19910723](https://user-images.githubusercontent.com/39317241/60934743-033e1700-a28d-11e9-8bf9-8fa7724af93e.png)
![19910724](https://user-images.githubusercontent.com/39317241/60934745-0802cb00-a28d-11e9-8650-682a7fc3d3fe.png)

**Comment by namdre** [comment]
This is a feature. By default, the edge length is computed from the geometry and when you move the junctions / edge-geometry around you will get a different length. 
However, you can also set a custom length value that is independent of the geometrical length in case you need this.
