### ISSUE TITLE
Multiple connections from the same edge to the same target lane: build a zipper by default?

### ISSUE THREAD

**Issue by ambuehll** [eclipse/sumo#5828]
> By default, the right-most lane will have the right of way but this can be customized by using attribute pass. [doc]

How about setting them as zipper by default?
![image](https://user-images.githubusercontent.com/48930860/61120308-f6900d80-a49c-11e9-999a-45697237b509.png)

**Comment by namdre** [comment]
The documentation refers to a different situation: Multiple connections from the **same** edge to the same target lane (in your case the connections are from different edges). In most cases, merging from the same edge happens via lane-drop / lanechange (one lane is priviliged over the other one) and that is why we don't use zipper as default.

Also, when merging from different edges, priority/yielding is more common than the equality implied by zipper.

**Comment by ambuehll** [comment]
True. Thanks. I am not sure about reality though... the problem is then: #5830
