### ISSUE TITLE
After setLength, Rerouter is not updating route anymore

### ISSUE THREAD

**Issue by LukaszSolo** [eclipse/sumo#5831]
If I change vehicles length via TraCI, the Rerouter stops working. I've narrowed it down to simplest example network:
![image](https://user-images.githubusercontent.com/1267372/61237360-99b18300-a73a-11e9-9864-45cfedee808c.png)

[rerouter-length-bug.zip](https://github.com/eclipse/sumo/files/3393508/rerouter-length-bug.zip)

and sample Python code (the same behaviour happens under C#:

```python
sumoBinary = "sumo-gui.exe"
sumoCmd = [sumoBinary, "-c", "bug.sumocfg"]


import traci
import traci.constants as tc

traci.start(sumoCmd) 
vehID = "egoVehicle.0"
step = 0
time = 0.1

while step < 250:
   traci.simulationStep(time)
   step += 1
   time += 0.1
   appeared = vehID in traci.vehicle.getIDList() 
   if appeared:
      traci.vehicle.setLength(vehID, 3.5)
   
traci.close()
```

If you comment `traci.vehicle.setLength(vehID, 3.5)` the vehicle correctly goes to the end of the path (is being rerouted to the end). If the length is changed as per the line, the rerouter does not update ego's position.

**Comment by behrisch** [comment]
This is more or less by design. You have a vehicle type filter on your rerouter and when you change the length, the vehicle type changes (because length is a type property) and the filter does not apply anymore. I agree that this might be unexpected. I am not sure if we need to make this configurable or if we just can change the behavior to check for the "original" vtype. @namdre opinions?

**Comment by LukaszSolo** [comment]
Thank you for the answer and explanation. In that case, in the meantime, do you see a way to be able to have both rerouter for that specific vtype and ability to change it's length? Or in the descriptive way, I'm loooking to have an infinite loop for a single car for whom I can set up a custom length.

Thank you again!

**Comment by behrisch** [comment]
If you do not mind hard coding the vehicle id into your reroute you can add the type `egoCar@egoVehicle.0` to your list. This is the name sumo gives to the new type.
