### ISSUE TITLE
extend ignore route errors?

### ISSUE THREAD

**Issue by ambuehll** [eclipse/sumo#5832]
When setting ignore-route-errors true, sumo does not check for the connectivity of a given route. However, it still requires that the origin and the destination edges exist in the network. 
Maybe ignoring the latter check as well might be interesting to some?

**Comment by behrisch** [comment]
Can you elaborate your use case a little? Since we currently cannot add edges dynamically (but change permissions or reroute thereby fixing connectivity) I do not see why I would want to specify a non existing edge.

**Comment by ambuehll** [comment]
It's not at all a top priority issue, but here application examples for light modifications of the network. The general idea is that we modify the network slightly but want to keep identical trip IDs (we're talking about >10^6 trips).

- OD2trips on original network - remove/edit some edges - compare the results of both networks: The comparison is much easier if the **trip ID is identical**. Re-running OD2trips on the modified network changes the ID.
- When trips distances and durations are validated against map API for different network configurations (slight modifications on the original network), we save the trip ID. It is very costly to re-run the whole API query just because some trips cannot be executed. 

Again, nice to have, not at all essential. 
Thanks!

**Comment by behrisch** [comment]
Thanks for the examples. I would probably run duarouter (with ignore-errors and write-trips) in those cases to fix the trips. Would this already solve the problem?

**Comment by ambuehll** [comment]
Ah, true. Forgot about duarouter. Thanks!
