### ISSUE TITLE
Sumo simulator for urban traffic simulation

### ISSUE THREAD

**Issue by suraty** [eclipse/sumo#5834]
Hello,

For urban traffic simulator, we can use Sumo simulator with other simulators like Omnet++ or Matlab or Ns2/3.

I know Sumo can model mobility and other simulators coupled to Sumo for communication protocols or communication networks.

While it is possible to simulate VANET with just using Matlab.

What is the difference between them (SUMO and others or just using Matlab)?

How can we find which is better?

Thank you

**Comment by behrisch** [comment]
answered here: https://stackoverflow.com/questions/57087742/sumo-simulator-for-urban-traffic-simulation
