### ISSUE TITLE
Netconvert splitting and joining network produces diffrent content

### ISSUE THREAD

**Issue by ZoltanBaksa** [eclipse/sumo#5836]
I edit and store my network without internal lanes, so it is faster and easier to handle. Before I do a simulation I run a process with netconvert, where I create from one net file the separated version (con, edge, nod, tll, typ) and rejoin them to get a net with internal lanes.
If there is an edge or lane in the original network which has 'all' in the allow attribute, but has 'highway.service' in the type attribute, the new network will contain 'pedestrian delivery bicycle' as this is the default for 'highway.service'.
If I previously edit the 'allow' attribute to other than 'all', the new network will contain the edited version.

**Comment by behrisch** [comment]
Did you edit the network with netedit? Does the edge really contain `allow="all"` afterwards or is the `allow` attribute missing completely? If the latter is the case I would consider it a netedit bug.

**Comment by ZoltanBaksa** [comment]
I have allow="all" at newly added edges. I do network editing only in netedit. I did not checked the xml file, if it contains the allow or disallow attribute in this case.

**Comment by behrisch** [comment]
Do you have allow="all" in the netedit GUI or also in the net.xml?

**Comment by behrisch** [comment]
I made this a separate ticket now #5861 but i don't know whether it resolves all your problems.

**Comment by namdre** [comment]
note, that you can run 
`netconvert -s net.net.xml -o net2.net.xml --no-internal-links false`
to add internal lanes to an existing nework. This should work around #5861

**Comment by ZoltanBaksa** [comment]
I have tried the newest version of SUMO v1_2_0+1406-58ee75451d.
If I change the edge or lane permission with allow/disallow box to enable all vehicle types, the allo or disallow attribute is not written to the xml, the allow input box contains 'all'. If I enter the text 'all' manually, it results the same xml.
When I use my old version (separating to network elements and then rejoining them with internal edges) produces another result as the namdre advised version. In the later version some of my direclty set or imported edge speeds are reset to a some default like speed. In some cases the edge/lane lengths and shapes show differences. Almost all of the junction shapes are also different. The original problem still occurs in the split and rejoin process, but it is correct in the later method.
Here is the first method's generated header:
```
<?xml version="1.0" encoding="UTF-8"?>
<!-- generated on 08/06/19 01:31:07 by Eclipse SUMO netconvert Version v1_2_0+1406-58ee75451d
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/netconvertConfiguration.xsd">
    <input>
        <node-files value="StuttgartAreaDetailed.nod.xml"/>
        <edge-files value="StuttgartAreaDetailed.edg.xml"/>
        <connection-files value="StuttgartAreaDetailed.con.xml"/>
        <tllogic-files value="StuttgartAreaDetailed.tll.xml"/>
        <type-files value="StuttgartAreaDetailed.typ.xml"/>
    </input>
    <output>
        <output-file value="StuttgartAreaDetailedInternal.net.xml"/>
        <output.street-names value="true"/>
    </output>
    <report>
        <ignore-errors value="true"/>
    </report>
</configuration>
-->
<net version="1.3" junctionCornerDetail="5" limitTurnSpeed="5.50" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/net_file.xsd">

```
This is the second's header
```
<?xml version="1.0" encoding="UTF-8"?>
<!-- generated on 08/06/19 01:32:02 by Eclipse SUMO netconvert Version v1_2_0+1406-58ee75451d
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/netconvertConfiguration.xsd">
    <input>
        <sumo-net-file value="D:\repo/StuttgartCity/net/StuttgartAreaDetailed_nointernal.net.xml"/>
    </input>
    <output>
        <output-file value="StuttgartAreaDetailedInternal_new.net.xml"/>
        <output.street-names value="true"/>
    </output>
    <processing>
        <geometry.max-grade.fix value="false"/>
        <offset.disable-normalization value="true"/>
        <lefthand value="false"/>
    </processing>
    <junctions>
        <no-internal-links value="false"/>
        <no-turnarounds value="true"/>
        <junctions.corner-detail value="0"/>
        <junctions.limit-turn-speed value="-1"/>
        <rectangular-lane-cut value="false"/>
    </junctions>
    <pedestrian>
        <walkingareas value="false"/>
    </pedestrian>
</configuration>
-->
<net version="1.3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/net_file.xsd">
```

**Comment by namdre** [comment]
About those differences:
* changing permissions are indeed a bug (#5861)
* changing speeds (on normal edges) are also a bug and I'd like to get example input for reproducing this
* changing junction geometry should not happen if the same netconvert version is used throughout and options such as --default.junctions.radius where at the default in the source network (which seems to be the case in your example). In my own tests, I receive idential geometries with both methods. Please provide (small) example input for reproducing the difference.

Note, that you can try using 
`
netconvert ^
-n "withinternal.nod.xml" ^
-e "withinternal.edg.xml" ^
-x "withinternal.con.xml" ^
-i "withinternal.tll.xml" ^
--ignore-errors.edge-type
-o "withinternal.net.xml" ^
`
as another work-around for #5861 because the bug is linked to the loading of edge types (which is unecessary as edge attributes are already known).

**Comment by ZoltanBaksa** [comment]
The last advised workaround solves the original problem about the permissions. The one-step method modifies the maps calculated offset and boundary values, that is why all shapes are recalculated. This indicates the recalculation of all internal edge/lane shapes, which results the newly calculated speeds. Also this re-positioning results that at some edge/lane lengths are changed.
I send the content via email, because it is too big for git proxy.
You can test with it the view by permission code settings too,

**Comment by namdre** [comment]
Actually, the one-step method preserves the offset from the original network whereas the two-step method re-shifts the geometry towards the coordinate origin. 
You can force the one-step method to re-shift by setting option `--offset.disable-normalization false` or you can force the two-step method to keep the original offset by setting `--offset.disable-normalization`

**Comment by ZoltanBaksa** [comment]
Yes, I have recognised this shift at generating the decal definitions, because I had to create two set, one for no-internal and one for with internal lanes.
Although I forced the two-step method to not change the offset, the result is still not the same.

If I use the one-step method an compare the results with the original version, I see that the edge lengths are recalculated according to the inserted internal lane lengths, so the overall length of the network does not change. Also the edge/lane speed values and the allow/disallow settings are ok 👍

**Comment by namdre** [comment]
With your example input, the following options produce identical networks:
`
netconvert 
-n "cutout.nod.xml" 
-e "cutout.edg.xml" 
-x "cutout.con.xml" 
-i "cutout.tll.xml" 
-o "cutoutInternal_notyp.net.xml" 
--ignore-errors.edge-type 
--offset.disable-normalization 
--junctions.corner-detail 0 
--junctions.limit-turn-speed 0
`

`
netconvert 
-s cutout.net.xml 
-o cutoutInternal_onestep.net.xml 
--no-internal-links false
`
