### ISSUE TITLE
device.rerouting.probability

### ISSUE THREAD

**Issue by ambuehll** [eclipse/sumo#5837]
When routing based on trip file, all vehicles receive a rerouting device, independently of device.rerouting.probability. 
If I wanted to use re-routing with device.rerouting.period >0, ALL vehicles get re-routed. It would be a nice enhancement, if only a certain portion gets re-routed every period. Ideally, the vehicles getting re-routed are randomly selected every period. 
similar to #4635 , but could be done by re-activating device.rerouting.probability for trip file routing. 

Thanks.

**Comment by namdre** [comment]
Note, that equipment status is only determined once per vehicle.
