### ISSUE TITLE
SUMO crashes when using SSM devices with opposite direction

### ISSUE THREAD

**Issue by usamael2000** [eclipse/sumo#5839]
Hi All,
I am  trying to use SUMO to generate possible traffic conflicts for two-lane two-way roads.
The program runs fine without using opposite directions driving but it crashes right after I run SUMO when I use the opposite directions driving
along with SSM devices.

I attached the  two networks I used.

Your help is much appreciated.

By the way, I am using the latest developed sumo program (64 version) as of July 20, 2019.

Best Regards,
Usama

[sumo_networks.zip](https://github.com/eclipse/sumo/files/3415441/sumo_networks.zip)

**Comment by usamael2000** [comment]
update: I found that by setting "lcOpposite>=10", SUMO no longer crashes, as the default value for lcOpposite is 1.0.

**Comment by usamael2000** [comment]
update: I found that by setting "lcLookaheadLeft>=10", SUMO no longer crashes,
as the default value for lcLookaheadLefte is 2.0.

**Comment by namdre** [comment]
related to #5231. The existing test case did not cover enough of the state space.
