### ISSUE TITLE
Netedit: generic parameters of connections are not loaded

### ISSUE THREAD

**Issue by m-kro** [eclipse/sumo#5842]
Generic parameters can be added to **connections** using the Netedit dialog. They also get saved in the net file. When reloading the same net file, the generic parameter dialog is empty again.

**Comment by palvarezlopez** [comment]
@m-kro Yes, currently connections doesn't support generic parameters. Do you need it?

**Comment by m-kro** [comment]
Well, it is not that important. I will find a workaround. If you have some time left, I would appreciate this feature being implemented, though.

**Comment by namdre** [comment]
I found no code that would have written generic connection params to a .net.xml but it's working now.
