### ISSUE TITLE
How to use /tools/randomTrips.py on ubuntu

### ISSUE THREAD

**Issue by xiaoToby** [eclipse/sumo#5843]
My os system is 18.04. The sumo version is 1.2.0
I want to use the tool - randomTrip.
I input the command like that:
<python ~/sumo/tools/randomTrips.py  -n xxx.net.xml -r xxx.rou.xml -e 50 -l>
But, there is an error, the error log is:
<
File "/home/dnl/sumo/tools/randomTrips.py", line 506, in <module>
          if not main(get_options()):
        File "/home/dnl/sumo/tools/randomTrips.py", line 485, in main
          subprocess.call(args)
        File "/home/dnl/anaconda3/envs/flow/lib/python3.5/subprocess.py", line 247, in call
          with Popen(*popenargs, **kwargs) as p:
        File "/home/dnl/anaconda3/envs/flow/lib/python3.5/subprocess.py", line 676, in __init__
          restore_signals, start_new_session)
        File "/home/dnl/anaconda3/envs/flow/lib/python3.5/subprocess.py", line 1289, in _execute_child
          raise child_exception_type(errno_num, err_msg)
      FileNotFoundError: [Errno 2] No such file or directory: 'duarouterD'
>

How to deal with it?

**Comment by xiaoToby** [comment]
@ palvarezlopez

**Comment by behrisch** [comment]
Please try to locate the duarouter binary. If it is in /home/dnl/sumo/bin, then set the environment variable SUMO_HOME like this `export SUMO_HOME=/home/dnl/sumo` and run the script again. If duarouter is not there install sumo from the ubuntu ppa or build it yourself.

**Comment by xiaoToby** [comment]
First, I want to know you said duarouter binary is a file ?
However I can not found it, and I followed the instruction on sumo website.
sudo add-apt-repository ppa:sumo/stable
sudo apt-get update

The result is same, i cannot find duarouter binary on the /home/dnl/sumo/bin.

And as you said, build it by yourself. How to build it ? I have no idea

**Comment by behrisch** [comment]
Yes, duarouter is a file. You missed the most important step in installing sumo from the ppa which is

    sudo apt-get install sumo sumo-tools sumo-doc

after that the sumo binaries (including duarouter) will not be in /home/dnl/sumo/bin but rather in /usr/bin, but the script should find them anyway.
