### ISSUE TITLE
ImportError: No module named traci

### ISSUE THREAD

**Issue by wrs777** [eclipse/sumo#5844]
I installed sumo on my mac through:
brew tap dlr-ts/sumo
brew install sumo

and it seems to work, as i input sumo in my terminal:
Eclipse SUMO Version 1.2.0
 Build features: Darwin-17.7.0 x86_64 Clang 10.0.0.10001044 Release Proj GUI
 Copyright (C) 2001-2019 German Aerospace Center (DLR) and others; https://sumo.dlr.de
 License EPL-2.0: Eclipse Public License Version 2 <https://eclipse.org/legal/epl-v20.html>
 Use --help to get the list of options.
 
but when i import traci in my python file, it tells:
 import traci
ImportError: No module named traci

**Comment by m-kro** [comment]
Well your Python installation cannot find the TraCI package located in SUMO_HOME/tools.
SUMO_HOME is the main directory of SUMO with subdirs like bin, data, doc, tools. You need to point Python to it somehow. This is usually achieved by setting an environment variable named "SUMO_HOME" to the SUMO main dir path and adding the tools dir to the PATH before the import call:
`sys.path.append(os.path.join(os.environ.get("SUMO_HOME"), 'tools'`

**Comment by wrs777** [comment]
It works. Thanks!

**Comment by behrisch** [comment]
Seems to be fixed

**Comment by ishanrai32** [comment]
How would the same thing work if I'm trying this in Google colab? When running it in anaconda, `sys.path.append(os.path.join(os.environ.get("SUMO_HOME"), 'tools'))` worked fine. But now in colab, I'm confused as to where to put this. The solution that worked offline doesn't work when I'm using it in Colab, do I put this in the Notebook cell before calling the file that I want to run?

**Comment by behrisch** [comment]
We do not have so many colab users around here. It may be better to ask on the mailing list or open at least a separate issue.

**Comment by ishanrai32** [comment]
Thank you for the response, yes I will do that.

**Comment by namansati** [comment]
> How would the same thing work if I'm trying this in Google colab? When running it in anaconda, `sys.path.append(os.path.join(os.environ.get("SUMO_HOME"), 'tools'))` worked fine. But now in colab, I'm confused as to where to put this. The solution that worked offline doesn't work when I'm using it in Colab, do I put this in the Notebook cell before calling the file that I want to run?

Can you tell me how the issue got fixed in offline mode, what's the exact thing i have to do?
I am getting the following error as I added the `sys.path.append(os.path.join(os.environ.get("SUMO_HOME"), 'tools'))`  line in my code.

'sys.path.append(os.path.join(os.environ.get("SUMO_HOME"), 'tools')) 
File "/usr/lib/python3.10/posixpath.py", line 76, in join
a = os.fspath(a)

TypeError: expected str, bytes or os.pathlike object, not NoneType'
