### ISSUE TITLE
Crash due a high number of VType/PersonType attributes

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#5846]
- Problem starts in df580791036301e051ae2c51890584589cb6d4a5. 
- It's caused by function fillLaneChangingModelAttributes(...)
- Reproducible with Clang and MSVC
- Problem ocurred in FOX dll, not in NETEDIT itself
- Also in 32 and 64 bits

**UPDATE:**

-  Problem found. Its the high number of AttributesCreatorRows

**Comment by palvarezlopez** [comment]
@namdre probably the most bizarre bug of the year...

**Comment by namdre** [comment]
I cannot reproduce this with gcc / clang on my linux machine. Can you check whether it works on linux for you?

**Comment by palvarezlopez** [comment]
@namdre I found the problem and I'm currently fixing it.
