### ISSUE TITLE
Netedit: allow / disallow window does not open on Windows 10

### ISSUE THREAD

**Issue by ZoltanBaksa** [eclipse/sumo#5851]
In inspection mode the allow/disallow window does not open. Not urgent, I can change the settings by writing directly to the input box.
I use v1_2_0+1287-e3a008b72 version of Netedit on Windows 10 Enterprise V1809, build 17763.615

**Comment by palvarezlopez** [comment]
@ZoltanBaksa I checked it, and in my case it works. Yesterday I updated the FOX 1.6.55 to 1.6.57 in SUMOLibraries. Can you check if a new version from FOX solves your problem?

**Comment by ZoltanBaksa** [comment]
After I replaced the dll only in the bin folder, it solved the problem.

**Comment by ZoltanBaksa** [comment]
Unfortunately the issue is not solved yet, because after I have downloaded a newer version, the problem still occurred. I have now v1_2_0+1339-9920f6b16 version.
After I start netedit, the allow/disallow window appears several times, but after some actions taken (I could not find out yet, which causes it) the allow/disallow window does not appear again.

**Comment by palvarezlopez** [comment]
@ZoltanBaksa I modified the design of allow/disallow modul. Can you check if the problem persist?

**Comment by ZoltanBaksa** [comment]
Hello @palvarezlopez, it seems, with the new design in v1_2_0+1376-f869dda154, the issue does not occur any more.

**Comment by palvarezlopez** [comment]
@ZoltanBaksa  Then I close the Ticket. If issue appears again, please open this ticket again.
