### ISSUE TITLE
Edge color by permission code panel does not work properly

### ISSUE THREAD

**Issue by ZoltanBaksa** [eclipse/sumo#5852]
It is not deterministic how the written permission code is used, because if I write the value of a bit combination, it is not colouring the streets accordingly. I have highway.secondary type edges with 5 lanes, where I set the 2 rightmost lanes to be used by bus only. At the 3 other lanes I removed bus, to avoid unexpected usage by bus. If I set a permission code for this last type the colour of edge stays the original, as the bus were there.
I would except, if I give the two following bit codes 51641855 and 51642367, I would become two different colours, but through the input panel I'm not able to set this. If I save the view setting in an XML file, I'm able to change the values, but after re-loading it, the expected result is not seen.
Furthermore the input box shows the written permission code in E-notation form (5.08559E+07) which hides the exact value (50855935) so I'm not able to check my setting.
I would suggest to change this panel to be able to set the different permission codes by setting it similarly as the allow/disallow box.
It is also a problem to change the values directly by typing, because they each input box is connected to the previous level. If I have 32 number at the first input box and I want to write 256 to the second box, the entry will change the first number to 2. This kind of update should not happen.
If I push the 'Recalibrate rainbow' button, the current function creates 7 colours with 7 thresholds with evenly set distances.  I would expect such a function, that checks the network for the current permission combinations, and tries to set as many colours as many combination currently exists.

**Comment by namdre** [comment]
setting distinct colors for the above codes (or saving the new rainbow colors) and then loading them produces the expected color difference.

**Comment by ZoltanBaksa** [comment]
In case there is an edge with only one lane, the colouring is ok, but in case there are at least 2 parallel lanes, where only one lane is shared, the edge colouring is not showing the difference, eg. it is not recognisable if the priorities are correct for the tram or not.

**Comment by namdre** [comment]
I'm seeing distinct lane colors for multi-lane roads with heterogeneous permissions in my test. Please provide a small example network.

**Comment by ZoltanBaksa** [comment]
Hi Jakob,
I use currently the development version v1_7_0+0223-475229c79.
The recalibration of the rainbow works properly for sumo, but the issue is still open for netedit.
This function works different for the two SW?
They should use the same routines, if the functionality is the same...

**Comment by namdre** [comment]
They do use different code (where necessary) because the data structures are quite different (edges during the network-building process have other state than edges during the simulation).
