### ISSUE TITLE
How to make vehicles accelerate in constant acceleration / deceleration ?

### ISSUE THREAD

**Issue by warm2018** [eclipse/sumo#5853]
I used the traci.setAccel()  command to realize it , but it didn't work, why?

**Comment by behrisch** [comment]
setAccel sets the maximum acceleration. To always use that you should use the default Krauss model and disable dawdling by setting the sigma parameter to 0. The vehicle will of course still brake if there are conflicting vehicles or junctions where it might need to yield on the way.
