### ISSUE TITLE
TraCI Python IDE Autofill

### ISSUE THREAD

**Issue by patmalcolm91** [eclipse/sumo#5855]
I'm currently developing some python scripts using the TraCI API, and noticed that my IDE is not able to autofill most of the traci module.

I have tested this on both PyCharm on my machine and Spyder on a colleague's and have ensured that the python path was configured correctly in the IDE (as evidenced by the fact that *some* of the module components are read properly, for example `traci.simulationStep()`). However, many (such as `traci.route` and `traci.vehicle`) are not.

I assume this has to do with the fact that TraCI itself is written in C++, and the python API files are incomplete. If this is the case, is there a plan to update them to make development with TraCI more convenient?

**Comment by behrisch** [comment]
The reason is that traci.route is inserted into the traci module using setattr which is not supported by most code completion engines. I tried to rework that, so if you are working with the current git master, please try to update and reopen if problems persist.

**Comment by patmalcolm91** [comment]
That resolved the issue. Thanks a lot!
