### ISSUE TITLE
Counting the number of vehicles within a given distance of lane

### ISSUE THREAD

**Issue by suraty** [eclipse/sumo#5862]
Hello,

I am a beginner and I am using TraCI4matlab and I would like to count the number of vehicles which are in a given distance of the lane, e.g. within 20 meters of the junction.
Like this code:

`    nb = 0

    for k in traci.lane.getLastStepVehicleIDs(lane):

        if traci.vehicle.getLanePosition(k) < X-100:

             nb += 1`

I guess that I could use
 _`function subscribeContext(laneID, domain, dist, varargin)`_

Is it true?
How can I set the parameters and get the results?

Another question is it possible to get the distance of the last vehicle which exists within a given distance of junction? 
(For example, there are 2 vehicles within 10 meters distance of junction, one of them in 5 meters distance and another in 7 meters distance, 7 meters is the result.)

Thank you

**Comment by behrisch** [comment]
The best way to do this is probably a lanearea detector, see https://sumo.dlr.de/wiki/Simulation/Output/Lanearea_Detectors_%28E2%29. Their results can also be retrieved using traci4matlab. There is currently no way to get them ordered by position. You will need to retrieve the positions and find the last vehicle manually.
