### ISSUE TITLE
Modifying the network while the simulation is running

### ISSUE THREAD

**Issue by galman33** [eclipse/sumo#5869]
I'm using sumo through C++. Is it possible to modify the network while the simulation is running?  (for example, adding edges during runtime). What's the best way to achieve such behaviour?
From my research it seems like there isn't a straight forward way to do that.

**Comment by namdre** [comment]
Yes. Either by 
1) adding all edges in advance with disallow=all and changing permissions at runtime via TraCI
2) [saving simulation state and loading it](https://sumo.dlr.de/wiki/Simulation/SaveAndLoad) for a different network (depends on #5872)
