### ISSUE TITLE
load lane by id when loading state

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#5872]
currently, lanes are loaded by index and all lanes must be saved/loaded.

Saving and loading by ID has two advantages
- only occupied lanes must be saved
- state may be loaded for modified networks.

**Comment by palvarezlopez** [comment]
@namdre this will affect Netedit?

**Comment by namdre** [comment]
> 
> 
> @namdre this will affect Netedit?

No. Completely unrelated.
