### ISSUE TITLE
Weird angle visualization during lane-change at junction

### ISSUE THREAD

**Issue by schwamborn** [eclipse/sumo#5879]
sumo-gui shows weird angle during lane-change at junction:

At step t (bug):

![lc_over_junction_angle_bug_t](https://user-images.githubusercontent.com/35012744/62536347-132a2600-b84e-11e9-85b8-9d0990011ebe.png)

At step t+1 (as it should be):

![lc_over_junction_angle_bug_t+1](https://user-images.githubusercontent.com/35012744/62536353-16bdad00-b84e-11e9-89e1-77275a7244e1.png)

**Comment by schwamborn** [comment]
Added minimal working example scenario to `5879_bad_angle_during_lc` bug report folder.
Occurs at time 17.100.

**Comment by m-kro** [comment]
Probably due to internal lane with length=0.

**Comment by namdre** [comment]
@m-kro can you add a small test to our test suite that captures the changed computation? fcd-output records angles.
