### ISSUE TITLE
allow removing geometry-like nodes if lane widths of differ less than a given treshold

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#5883]

**Comment by palvarezlopez** [comment]
@namdre Do you think that this could be useful also in NETEDIT?

**Comment by namdre** [comment]
> 
> 
> @namdre Do you think that this could be useful also in NETEDIT?

No, this is a very specialized functionalty (mainly for OpenDRIVE processing) and not needed for the general Netedit audience.
