### ISSUE TITLE
Plain XML Output: edge length

### ISSUE THREAD

**Issue by ambuehll** [eclipse/sumo#5902]
I have the feeling it should be possible to retrieve the length of an edge directly from the edge file. I am not sure if this related to this doc: "Geometry information is stored only if the imported edge has a shape, meaning that it is not only a straight connection between the from/to-nodes."

When creating a net file from OSM, there are shape geometries stored, e.g.:
`    <edge id="-101784365#2" from="442593134" to="cluster_4153656429_440149543" priority="3" type="highway.residential" shape="75122.82,23718.44 75134.84,23723.65 75161.76,23744.89">
`
However, when setting plain-output-prefix, no length is returned: 
```
  <edge id="-101784365#2" from="442593134" to="cluster_4153656429_440149543" priority="3" type="highway.residential" numLanes="1" speed="6.85" shape="-43.353120,-22.856661 -43.353003,-22.856613 -43.352743,-22.856418" disallow="tram rail_urban rail rail_electric ship">
        <lane index="0">
            <param key="origId" value="101784365"/>
        </lane>
        <param key="origTo" value="4153656429"/>
    </edge>
```
It would just be slightly more confortable if there were a way to retrieve it directly from the edge file.

**Comment by behrisch** [comment]
Well, the plain XML is not designed for being parsed comfortably ;-). The purpose is rather to have an automatically (or manually) editable version of the network with a minimum of redundancy. If we introduce `length` here, I think the risk of people changing `shape` and forgetting to adapt `length` is higher than the benefit. If you need the length you can still parse the net. Feel free to reopen if you have a convincing use case.

**Comment by namdre** [comment]
You could also use sumolib.geomhelper.polyLength on the shape parsed from an .edg.xml file.

**Comment by ambuehll** [comment]
No worries, it's easy enough to just use the node files and calculate the length from start node to end node. It was more of a lazy day question ;) But thanks for getting back to me again!
