### ISSUE TITLE
strip unused dlls from windows release

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#5903]
it currently contains gdal dlls even in the non GDAL build

**Comment by palvarezlopez** [comment]
https://github.com/lucasg/Dependencies/issues

**Comment by palvarezlopez** [comment]
Entire folder "osgPlugins-3.4" can be removed.

**Comment by behrisch** [comment]
> Entire folder "osgPlugins-3.4" can be removed.

I don't think so. Probably osg just loads the plugins dynamically when it needs to read a specific file type.

**Comment by behrisch** [comment]
there are still gdal libraries inside

**Comment by behrisch** [comment]
should be resolved when moving to VS 2019

**Comment by behrisch** [comment]
seems to be done at least for gdal, more work in #8526 #7568
