### ISSUE TITLE
include libsumo header files in binary dist

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#5906]
otherwise users still need to download the src package

**Comment by palvarezlopez** [comment]
@behrisch should we include also the .pdb files?

**Comment by behrisch** [comment]
Only in the debug zip which is not part of the official release. I don't think they are usable with the release build.

**Comment by behrisch** [comment]
they are in the zip but probably not in the rpm / deb yet

**Comment by behrisch** [comment]
for rpm it's done, continues in #9032
