### ISSUE TITLE
meso: fundamental diagram for short edges

### ISSUE THREAD

**Issue by ambuehll** [eclipse/sumo#5909]
Correct fundamental diagram for regular edges (>100m, e.g. edge ID -14693213#1):
![](https://user-images.githubusercontent.com/48930860/62865859-d2c81d80-bd0f-11e9-9a4e-1ccf83f62ebb.png)

For relatively short edges (<10m), some anomalies exist (edge ID 181765436#1 and 14519991#2):
![](https://user-images.githubusercontent.com/48930860/62865932-fee39e80-bd0f-11e9-844a-4ac8dcd2b362.png)

1. substantially exceeding standard jam density (with max at 200veh/km)
2. (very) high flows at jam density - even when no teleports happen.
might be related to #5723
Each dot is a 3min average from the edge data output. 
As always, thanks! 
I can provide a smaller dummy network (original [files](https://drive.google.com/drive/folders/18aKo1T2s1KMp8dComwY_Bu8rXM7njsch?usp=sharing)) if necessary (I would need to scale it down first).

**Comment by namdre** [comment]
The meso model computes jammed state by comparing occupancy to some threshold value.
For short edges, the occpuancy at any given time is either 0% or ~100% and thus the model is not applicable. 

With the current default parameters (--meso-jam-threshold -1), the jam treshold is computed based on the speed limit using the assumption that a succesion of vehicles driving at full speed should not be considered jammed, Consquently this can set the threshold for short edges to >100% which means the edge can never jam. 

If you set meso-jam-treshold = 0.3 (30%) then the segment will be jammed whenever a vehicle is on it. 

I think the only solution with the current model is to make sure that there aren't too many short edges (and then their effect should be negligible anyway).

**Comment by ambuehll** [comment]
OK. Thanks for the detailed explanation. Fully makes sense!
I am not sure, however, if the jam density should be fixed to normal ranges (200 veh/km is much higher than the 5m length+2.5m gap).

**Comment by namdre** [comment]
This should only ever happen if the segment length is <=5m. The meso model assumes that each segment can fit at least one vehicle. 
The only reasonable solution I can see would be to exclude short segments from the simulation altogether (letting vehicles jump over them). 
Either way of dealing with short segments will introduce artefacts in the meso model.

I agree that it could be wortwhile to compensate some simulation outputs whenever a vehicleLengthPlusGap is longer than the segment. Which output values exactly do you suggest?

**Comment by gyq18** [comment]
Dear ambuehll, I'm very sorry to bother you. I'm new to SUMO  and I haven't figure out how to plot fundamental diagram by SUMO.  Could you please send me your code about fundamental diagram. My email is: gyq18@mails.tsinghua.edu.cn.  In order to express my gratitude, I will express my gratitude to you in my papers and list references to your article or code. Thank you very much!
