### ISSUE TITLE
What is the unit of emissions in </tripinfo> file

### ISSUE THREAD

**Issue by warm2018** [eclipse/sumo#5912]
I use the command "--device.emissions.probability" to get the emissions for every vehicle. But the output data make me wonder. WHAT is the  unit of account for emissions, g  or mg?
![image](https://user-images.githubusercontent.com/35907049/62911740-06f71900-bdb8-11e9-9f3a-67fed55a2ecd.png)

**Comment by namdre** [comment]
see https://sumo.dlr.de/wiki/Simulation/Output/TripInfo#Devices
