### ISSUE TITLE
TraCI C++ simulationStep() not working

### ISSUE THREAD

**Issue by DannyBehnecke** [eclipse/sumo#5914]
When trying out the [TRaCI C++ example](https://sumo.dlr.de/wiki/TraCI/C%2B%2BTraCIAPI), this little twist showed that the client is not working correctly:

main function:
>  Client client;
	client.connect("localhost", 1337);
	std::cout << "time in s: " << client.simulation.getTime() << "\n";
	std::cout << "run 5 steps ...\n";
	for(int i=0; i<10000; i++)
		client.simulationStep(5);
	std::cout << "time in s: " << client.simulation.getTime() << "\n";
	client.close(); 

Setup:
ran  ./sumo.exe -c ../tools/game/square.sumocfg --remote-port 1337 --start --log testLog.txt through cygwin under Windows 7. testLog.txt stays empty. 

Sumo 1.2.0 was built with VisualStudio 2017, the little test program was also built with that.

Expected Behavior:
Simulation just runs until it ends

Observed Behavior:
The first 5 steps are made, every following call to `client.simulationStep(5)` does nothing.

**Comment by behrisch** [comment]
@DannyBehnecke It is not intended behavior for sure but did you try calling just simulationStep() (without the 5)?

**Comment by behrisch** [comment]
Sorry, I was wrong, the behavior is just as specified https://sumo.dlr.de/wiki/TraCI/Control-related_commands#Command_0x02:_Simulation_Step. The argument is the target time or zero (for exactly one step) and if it is not zero and the target time is already reached it does nothing.
