### ISSUE TITLE
Recheck whether sumo can be linked against GPL code

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#5919]
We may need to enable the exhibit A clause in the EPL and add it to the source

**Comment by sommer** [comment]
The [EPL-2.0 FAQ Section 4.15](https://www.eclipse.org/legal/epl-2.0/faq.php#h.fn86eyf5mvhs) seems to state that this requires effort. Might still be very worthwhile, to allow using `libsumo` from Veins or ns-3, both of which are GPL-licensed.

**Comment by namdre** [comment]
The effort is outlined at [EPL-2.0 FAQ Section 3.3](https://www.eclipse.org/legal/epl-2.0/faq.php#h.tintzo3jnku1)
Our old CLAs explicitly permit relicensing to any OSI-approved license so this "only" applies to all other contributors (the ECA is less broad).

**Comment by behrisch** [comment]
@sommer It may be also possible to solve this on your side, if I read this correctly: https://www.gnu.org/licenses/gpl-faq.html#GPLIncompatibleLibs

**Comment by sommer** [comment]
> https://www.gnu.org/licenses/gpl-faq.html#GPLIncompatibleLibs

Indeed, though the overhead might be slightly bigger (if I read the statement `if you want to use parts of other GPL-covered programs by other authors in your code, you cannot authorize the exception for them` right): Veins builds on other authors' GPL (version 2) code itself, so we'd need permission from the heads of 3 companies, 4 universities, and a few dozens of individuals.

**Comment by behrisch** [comment]
superseded by #6506
