### ISSUE TITLE
type="DEFAULT_BIKETYPE" must be saved

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#5923]
this is different from DEFAULT_VEHTYPE (since this is really the default when no type is set).
However, for bicycles the type must be set explicitly (though the <vType> must not be written because it is always known by the sumo applications).

**Comment by palvarezlopez** [comment]
@namdre It should only written if at least there is a vehicle with vType="DEFAULT_VEHTYPE". It's correct?

**Comment by palvarezlopez** [comment]
@namdre It works.
