### ISSUE TITLE
 traci.simulation.getDepartedNumber() doesn't return right value

### ISSUE THREAD

**Issue by xiahaochong** [eclipse/sumo#5925]
Hello, I used traci.simulation.getDepartedNumber() to count the number of cars inserted in my simulation. However, I found out that the number it returns only equals to almost half(not exactly half) of the cars that truly inserted in my simulation. I am an amateur in coding and I don't know how to look into your code to find the code that does the calculation for traci.simulation.getDepartedNumber(). Can you check this function? Thank you!

**Comment by namdre** [comment]
Please provide a minimal sample scenario (traci script and all input files) to reproduce this unexpected behavior.

**Comment by xiahaochong** [comment]
> Please provide a minimal sample scenario (traci script and all input files) to reproduce this unexpected behavior.

Thank you for your reply! The function works fine actually. I found out that it was because I ran two steps of simulation and only call this function once to calculate the number of cars. Sorry for bothering you!

**Comment by xiahaochong** [comment]
> Please provide a minimal sample scenario (traci script and all input files) to reproduce this unexpected behavior.

Thank you for your reply! The function works fine actually. I found out that it was because I ran two steps of simulation and only call this function once to calculate the number of cars. Sorry for bothering you!
