### ISSUE TITLE
Issue in running highway.police sample application

### ISSUE THREAD

**Issue by shalinits** [eclipse/sumo#5931]
While running highway.police sample application, I had made changes related to the depart parameter as shown below  in highway.rou.xml file

   <vehicle id="car0" type="car" route="route0" depart="1" departLane="1" departSpeed="max" />
   <vehicle id="car1" type="car" route="route0" depart="1" departLane="2" departSpeed="max" />
   <vehicle id="car2" type="car" route="route0" depart="1" departLane="free" departSpeed="max" />
   <vehicle id="police0" type="police" route="route0" depart="3" departLane="2" departSpeed="max" />
   <vehicle id="emergency" type="emergency" route="route0" depart="3" departLane="3" departSpeed="max" />

It is showing as  tcpip::SocketException: tcpip::Socket::recvAndCheck @ recv: peer shutdown -- in module (traci::Core) World.traci.core (id=4), at t=1.1s, event #1213 

If we give departLane as 3 in either of the three vehicle ids it is crashing.The simulation ends at t=2.1s.

**Comment by namdre** [comment]
This description doesn't sound like pure SUMO. Are you using FLOW or some such framework? In that case, please open a ticket for the corresponding project. 
You may reopen this ticket if you can make sumo crash with a pure sumo+traci setup.
