### ISSUE TITLE
enhancement: edge_data output: number of teleports 

### ISSUE THREAD

**Issue by ambuehll** [eclipse/sumo#5939]
low priority, really just a suggestion:
add the number of teleports on a specific lane/link to edge output. 
This would avoid the parsing of the log file.

**Comment by namdre** [comment]
good idea. Not sure though whether this attribute should always be present (one more thing to increase output size and which may not carry data in most cases) or whether there should be an attribute in the `<edgeData>` definition to switch this one.
Probably the latter

**Comment by ambuehll** [comment]
I am in favour of the edgeData attribute idea :)
