### ISSUE TITLE
remove java.util.Observer from TraaS

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#5940]
It is deprecated since Java 9 but still used as a public interface in applications. Unfortunately recommended alternatives such as the flow API are not available in Java 8.

**Comment by namdre** [comment]
Only used for handling Subscriptions and ContextSubscriptions (see Subscription test).

**Comment by behrisch** [comment]
@mkrumnow which could probably easily replaced by a self made API without using any Observer like class?

**Comment by mkrumnow** [comment]
The flow API should be used to handle traci subscription in the future. In the meanwhile the methods of java.beans.PropertyChangeEvent should be used instead of java.util.Observer to be backward compatible.

**Comment by namdre** [comment]
@mrkumnow Do you mean backwards compatible with older client scripts or with older java versions? I think client scripts have to be changed either way and a custom Observer class with minimal interface would also be compatible with other java versions. The flow API (backpressure, etc) looks like overkill for something that doesn't even use data streams in all the other clients.

Frankly, we might also harmonize Traas with the other clients and just put the subscription results into a HashMap. Or am I missing a major design advantage here?

**Comment by mkrumnow** [comment]
Hi Jacob, i totally agree with you. A minimal interface would be the preferred solution (independent from the used java jre). The observer design pattern is not hard to implement e.g. https://www.journaldev.com/1739/observer-design-pattern-in-java

I will replace the references java.util.observer and java.util.observer in the code in the next time.
