### ISSUE TITLE
The information obtained by detectors is wrong

### ISSUE THREAD

**Issue by fengbaozhiling1** [eclipse/sumo#5942]
I used "traci.inductionloop.getLastStepVehicleNumber('DEL1')" to get the number of vehicles that were on the named induction loop within the last simulation step and I also used len(traci.inductionloop.getVehicleData('DEL1')) to get the number of vehicles which passed the detector in every time step. But actually, the data is wrong. Even the accumulated number of vehicles which passed the detector is larger than the departed number in the network. 
Why does it happen and How could I do? Thanks for help me!

**Comment by fengbaozhiling1** [comment]
The loop is e1Detector

**Comment by namdre** [comment]
Please look carefully at the data returned by traci.inductionloop.getVehicleData.
It includes vehicle that are on the detector as well as vehicles that have passed in the last time step. Thus the same vehicle may be reported during multiple steps. If you want to use getVehicleData for counting you need to make sure to only use vehicles that set a positive value for entry_time and exit_time

**Comment by fengbaozhiling1** [comment]
> Please look carefully at the data returned by traci.inductionloop.getVehicleData.
> It includes vehicle that are on the detector as well as vehicles that have passed in the last time step. Thus the same vehicle may be reported during multiple steps. If you want to use getVehicleData for counting you need to make sure to only use vehicles that set a positive value for entry_time and exit_time

Thank you for reply. But I still don't know how to get two value. One is the number of vehicles passing the detector. The other is the number of vehicles on the detector. Could you give me an example if the detector named "DE1"? 

And the exist_time sometime is -1, what is the meaning?

**Comment by namdre** [comment]
exit_time -1 means that the vehicle has not yet exited the detector.
