### ISSUE TITLE
invalid vType in created vehicle

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#5945]
- vehicle mode: vehicle=trip. set vType=DEFAULT_BIKETYPE
- create trip with two-clicks, Enter
- inspect trip: type=DEFAULT_VEHTYPE

was the actual cause for #5923

**Comment by namdre** [comment]
If you are sure that you can fix this safely for 1.3 please do so. Otherwise, we'll keep this open.

**Comment by palvarezlopez** [comment]
@namdre Fixed. The problem was exclusive of Flows and Trips.
