### ISSUE TITLE
allow retrieving ids of stopping places

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#5952]
- parkingArea
- chargingStation
- containerStop

currently, a special command exists only for busStop: TRACI_CONST int VAR_BUS_STOP_ID_LIST = 0x9f;

**Comment by namdre** [comment]
@behrisch maybe we should add a new domain for this?
Alternatively, we continue using a mish-mash of simulation value retrieval and and magic simulation.getParameter calls

**Comment by behrisch** [comment]
Yes, a new domain would be good here.

**Comment by namdre** [comment]
depends on #6147
