### ISSUE TITLE
keep-edges.input-file slow

### ISSUE THREAD

**Issue by ambuehll** [eclipse/sumo#5954]
**low priority:**
I have large networks where I delete half of the links based on some heuristic. 
It seems that netconvert is very slow when I use keep-edges.input-file (or remove-edges.input-file). Any speed up available?

netconvert -s osm.net.xml --keep-edges.input-file edges_valid_strongcon.txt -o RIO_osm.net.xml --proj.plain-geo true --geometry.remove true --plain-output-prefix RIO -v true

[files](https://drive.google.com/drive/folders/1q9o7_00L6BF1BeGpguZwOX_DEfjYDStW?usp=sharing)

**Comment by namdre** [comment]
Code was already using sets but iterating over them with linear effort rather than performing logarithm-effort lookup.
