### ISSUE TITLE
Building 4-leg (8 lanes) intersection in SUMO

### ISSUE THREAD

**Issue by suraty** [eclipse/sumo#5955]
Hello,

I am a beginner in SUMO, I would like to build an intersection like this picture.
![A-typical-4-lanes-intersection-with-2-nodes-per-lane_W640](https://user-images.githubusercontent.com/38600508/63407144-09352500-c401-11e9-8fb1-1a84ede530b4.jpg)

I defined .nod file:
```
   <node id="0" x="0.0" y="0.0"  type="traffic_light"/>

   <node id="1" x="-500.0" y="0.0" type="priority"/>
   <node id="2" x="+500.0" y="0.0" type="priority"/>
   <node id="3" x="0.0" y="-500.0" type="priority"/>
   <node id="4" x="0.0" y="+500.0" type="priority"/>
```
.edg file:
```
   <edge id="1i" from="1" to="0" type="a" />  
   <edge id="1o" from="0" to="1" type="a" />
   <edge id="2i" from="2" to="0" type="a" />
   <edge id="2o" from="0" to="2" type="a" />
   <edge id="3i" from="3" to="0" type="a" />
   <edge id="3o" from="0" to="3" type="a" />
   <edge id="4i" from="4" to="0" type="a" />
   <edge id="4o" from="0" to="4" type="a" />
```

.typ file:
`   <type id="a" numLanes="2" />`

.con file:
```
	<connection from="1i" to="2o"/>
	<connection from="1i" to="3o"/>
	<connection from="1i" to="4o"/>
	
	<connection from="2i" to="1o"/>
	<connection from="2i" to="4o"/>
	<connection from="2i" to="3o"/>
	
	<connection from="3i" to="4o"/>
	<connection from="3i" to="2o"/>
	<connection from="3i" to="1o"/>
	
	<connection from="4i" to="3o"/>
	<connection from="4i" to="1o"/>
	<connection from="4i" to="2o"/>
```

.net.cfg file is like this picture:
![image](https://user-images.githubusercontent.com/38600508/63407573-0e46a400-c402-11e9-95c4-29d7fc854aca.png)

It is different from what I desired.
How should I edit my code to build an intersection like of what requested?

Thank you

**Comment by namdre** [comment]
specify your connections with lane indices:

	<connection from="1i" to="2o" fromLane="0" toLane="0"/>
	<connection from="1i" to="3o" fromLane="0" toLane="0"/>
	<connection from="1i" to="4o" fromLane="1" toLane="1"/>

Or simply edit the connections visually with netedit.
