### ISSUE TITLE
crash after defining flow on unusable edges

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#5958]
- define edges that prohibit some vehicle class (e.g. allow="bicycle"
- define flow between these edges (DEFAULT_VEHTYPE with vClass="passenger")
  - both clicks are permitted (should be forbidden with this type)
  - after 'finish route creation' no flow object is visible 
- save demand -> crash

**Comment by namdre** [comment]
For trips this is mostly working (invalid element dialog on saving) and no crashing. (Still the clicks on unusable edges should be prevented).

Since from-to-flows were not available in 1.2.0 this is not a regression.

**Comment by palvarezlopez** [comment]
Fixed in 7647e0cbed7ce82ba2958a11166f96f578bb15b7
