### ISSUE TITLE
sumo-gui black boxes on MS Server 2016

### ISSUE THREAD

**Issue by ambuehll** [eclipse/sumo#5960]
black (or white) boxes over scale and other objects (e.g. phases of tls).
![image](https://user-images.githubusercontent.com/48930860/63429840-7fdf1c00-c41b-11e9-9f8c-ee7d5440d808.png)
![image](https://user-images.githubusercontent.com/48930860/63430513-0c3e0e80-c41d-11e9-86f3-77658d1f23e2.png)

I'll be happy to give more info if needed.

**Comment by palvarezlopez** [comment]
@ambuehll Thanks. This error is probably related with gl2ps library. Is direct3D enabled in your system?

**Comment by ambuehll** [comment]
If I understand correctly, it is not. See the output of [DxDiag](https://drive.google.com/open?id=1-O-zFR9BSxW4UsMoPQQTiYrrN7OYdg1g).

**Comment by palvarezlopez** [comment]
@ambuehll then it's the most probably cause. Can you please enable it?

https://support.microsoft.com/en-sg/help/191660/directdraw-or-direct3d-option-is-unavailable

If this solutions don't work, then we try another way.

**Comment by ambuehll** [comment]
Thanks! Appreciate the help. It seems to be enabled now. But it's still the same. 
![image](https://user-images.githubusercontent.com/48930860/63458212-a5d3e300-c452-11e9-83f8-6e6fd013d660.png)
I should have added that I am accessing the server via remote desktop (and I do not have any admin rights...).
In any case this issue is not urgent (or major), I just thought I wanted to let you know.

**Comment by namdre** [comment]
for remote desktop, this is a known issue: #5702
