### ISSUE TITLE
crash when loading flow with invalid route

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#5967]
See bugreports folder.

To reproduce crash call
     `netedit -s debug.net.xml -a stops.add.xml -r trains3.rou.xml`
then F4

Working as expected for trips. Since from-to-flows were not supported earlier, this is not a regression.

**Comment by palvarezlopez** [comment]
Fixed in 410aaf0c61d7b85ac1b88839d4fd05bb5306c12b
