### ISSUE TITLE
invalid flow/trip route not updated after adding connection

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#5968]
see bugreports folder
- connection to add is from gneE3 to -gneE3
- new trips from gneE0 to gneE5 can be created and saved without issue
- the initially loaded trip from gneE0 to gneE5 never updates it's route and triggers the 'fix demand element dialog'

**Comment by namdre** [comment]
a related test case is loaded an invalid flow and then changing it's type so that a correct route exists.

Solution in all cases is to reroute before populating the 'fix demand element dialog'.

Also, user should be able to trigger rerouting (#5978)

**Comment by palvarezlopez** [comment]
Fixed in a793ac1a30947dae82db1f8ff927b1d837d2b167
