### ISSUE TITLE
invalid unsaved-additionals warning

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#5971]
- load network file and additional file from command line
- quit netedit
- unsaved-additionals-warning pops up

related to #4239

**Comment by palvarezlopez** [comment]
@namdre I thought that this behavior was correct. For example, for loading two different additionals files and saving it in a single file.

**Comment by namdre** [comment]
Yes. Whenever something happens to additionals after loading the first file (e.g. loading a second file), then unsaved-warning should pop up.

**Comment by palvarezlopez** [comment]
Invalid hotkeys (problem with Fluxbox)
