### ISSUE TITLE
Issue with right flaring and NETCONVERT

### ISSUE THREAD

**Issue by alexdawn** [eclipse/sumo#5976]
Using the splits facility in the plain xmls I am able to write a python script to get flared lanes working for nearside turns, however for offside turns this does not work as a gap exists between carriageways. I thought adding an additional split further upstream which shifts the lanes across would work and act like what is called in the UK a ghost island:

![image](https://user-images.githubusercontent.com/12990914/63514901-9b145f00-c4e1-11e9-9ed4-1b4cdc43d403.png)

Despite the additional split where the lane on both edges are the most offside lane, a gap still exists between carriageways.

![image](https://user-images.githubusercontent.com/12990914/63514734-30632380-c4e1-11e9-8cdd-0c60ef9a7e32.png)

Does anyone have any suggestions how to get right hand flaring to work so that the upstream carriageways are connected? I'm not clear if the current behaviour is intended or a bug

The following snippet is the code for the South Arm, the code which generates them puts splits with common ids on both sides of the lane to ensure the edges properly connect:
```
    <edge from="24" id="198" length="395" numLanes="1" origid="R:J55050-J55115" shape="-1.2872206,51.678971 -1.2871015,51.677918" speed="8" to="32" type="S2-urban">
        <split id="237" lanes="0" pos="23.0"/>
        <split id="238" lanes="0" pos="34.5"/>
    </edge>
    <edge from="32" id="199" length="395" numLanes="2" origid="R:J55115-J55050" shape="-1.2871015,51.677918 -1.2872206,51.678971" speed="8" to="24" type="S2-urban">
        <split id="237" lanes="0 1" pos="-23.0"/>
        <split id="238" lanes="0" pos="-34.5"/>
        <split lanes="1" pos="0"/>
    </edge>
```

I believe it to be a bug as there are other working examples:
![image](https://user-images.githubusercontent.com/12990914/63530548-95794200-c4fe-11e9-9e54-8dbc5f8ac4f3.png)

**Comment by namdre** [comment]
Instead of creating ghost islands by shifting lanes with splits I recommend defining them as lanes with disallow="all". If you  set option --junctions.scurve-stretch you can ensure smooth transitions between both edges. 
The favoured solution for most of the lane-alignment issue is #1758 as it solves it much more cleanly compared to using splits. However, since this is not implemented, creating disallowed lanes is still the cleanest solution.

That being said, there may still be a bug in the current split implementation somewhere.

**Comment by alexdawn** [comment]
Thanks for the suggestions. Is there a way of setting lane properties for a segment of a split link?

**Comment by namdre** [comment]
Not in a single step. However, you can reprocess the network with a patch file where you can set explicit lane attributes (in a patch file you only need to set the id and the attributes that you wish to modify):
`netconvert -s net.net.xml -o net2.net.xml -e patch.edg.xml`

**Comment by namdre** [comment]
on an unrelated note: The explicit edge lengths that you define in your input create a major mismatch between geometical length and nominal length. You can investigate this by setting edge coloring'by given length/geometrical lengt' in sumo-gui

**Comment by alexdawn** [comment]
Nice tip, glad I don't have to handle splits in my own code!

Ah yeah I'm worried about the quality of the source data for some of the edges. The source model is from a strategic model where they often set a minimum value to an edge length to prevent 1-2 car queues from blocking the neighbouring junction. Might just drop the nominal length now I've got the geometric shapes. I like how SUMO handles the capacity on nominal lengths, nice feature!

**Comment by namdre** [comment]
You can now use edge spreadType="roadCenter" to improve the way roads with different lane numbers in each direction line up at an intersection.
