### ISSUE TITLE
Add new Button "Recompute Routes" (F5) in Demand Mode

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#5978]

**Comment by palvarezlopez** [comment]
Fixed in b29b7ab0329cc52fa01fc80173cb392fddc2d6d5

**Comment by namdre** [comment]
It is not working in my test. I tried this with #5968 on linux.

**Comment by palvarezlopez** [comment]
@namdre "Recompute routes" button and function are implemented in differents tickets (#5968)

**Comment by namdre** [comment]
It's a bit confusing when the commit message states: "added button and functions" and there is no other ticket for implemening the functionality (at least I didn't find one). Please close this ticket with a reference to a ticket with the remaining work.

**Comment by palvarezlopez** [comment]
The functionality of recomputing routes will be implemented in this ticket: #5968

**Comment by namdre** [comment]
Ah. Now I understand the source of the confusion:
To my mind #5968 and adding a recompute button are two unrelated items (fixing a bug, adding a feature)
