### ISSUE TITLE
flowId.runningNumber

### ISSUE THREAD

**Issue by gyq18** [eclipse/sumo#5981]
I want to set a fixed flow, i.e: 2400 pc/h/ln by using "flow". And I want to make to set a vehicle in the flow to stop for 30s. How to do this? Hope to receive your solution.

**Comment by namdre** [comment]
Please post this type of question on the mailing list in the future (https://sumo.dlr.de/wiki/Contact).
For flows, see attr vehsPerHour (https://sumo.dlr.de/wiki/Definition_of_Vehicles,_Vehicle_Types,_and_Routes#Repeated_vehicles_.28Flows.29).
Either define one flow per lane and set attribute departLane to a fixed number or multiply vehsPerHour by the number of lanes and define a single flow with departLane=free.

To let only a single vehicle in the flow stop you can either
- use TraCI.
- define a `<vehicle>` or `<trip>` in addition to the flow and add a stop to that vehicle

**Comment by gyq18** [comment]
thanks for your reply
