### ISSUE TITLE
problem about libsumo.trafficlight.setCompleteRedYellowGreenDefinition(tls_id, old_logic)

### ISSUE THREAD

**Issue by passengerxuhongli** [eclipse/sumo#5986]
i try to set net tls into sumo using libsumo.trafficlight.setCompleteRedYellowGreenDefinition with python3.

my code like this :
  old_logic=libsumo.trafficlight.getCompleteRedYellowGreenDefinition(tls_id)# 所有相位的信息logic
  libsumo.trafficlight.setCompleteRedYellowGreenDefinition(tls_id, old_logic)
but it is wrong, message like this:
    libsumo.trafficlight.setCompleteRedYellowGreenDefinition(tls_id, old_logic)
TypeError: in method 'trafficlight_setCompleteRedYellowGreenDefinition', argument 2 of type 'libsumo::TraCILogic const &'

could you help me how can i use the  libsumo.trafficlight.setCompleteRedYellowGreenDefinition function? is there some example code?

i want to email this problem to yours, but when i registered on website, it always infer me "Please verify that you are not a robot." but not a picture or some thing need i do. 
do you have any advice？

**Comment by behrisch** [comment]
trafficlight.getCompleteRedYellowGreenDefinition(tls_id) returns a vector of all logics, while trafficlight.setCompleteRedYellowGreenDefinition only needs a single logic as parameter. So please retry with old_logic[0].
@namdre Should we rename this to getAllLogics and setLogic?

Concerning the mailing list, we cannot help here, Eclipse it administering it. Maybe try with a different browser?

**Comment by passengerxuhongli** [comment]
thx, 
it success when i replace old_logic to old_logic[0];
 i think rename getALLLogic and setLogic  more easily to  understand than get getCompleteRedYellowGreenDefinition

finally,  actually i try to regiester mail list with ie, google. no one can fix it. it is reason i am in china? anyway i must to fix it,there are many things about sumo i want to share with all sumo users
thanks !!!

**Comment by behrisch** [comment]
@passengerxuhongli You can try to use the forum interface here: http://sumo-user.90755.n8.nabble.com/

**Comment by behrisch** [comment]
I am closing this one and keep the renaming issue in #5995.
