### ISSUE TITLE
Variable Speed limit control

### ISSUE THREAD

**Issue by gyq18** [eclipse/sumo#5988]
Hello everyone.  I've been trying to carry variable speed limit control to two lanes of an edge with different speed limit.  However, "traci.edge.setMaxSpeed" set a new maximum speed (in m/s) for all lanes of the edge. If I want to set two lanes of an edge with different speed limit, how can I achive this? And "traci.vehicle.setSpeed" only set vehicles within tha last step, so if I want to set a lot of  vehicles which go through the part of two lanes of an edge with two speed limits, how can I achive this? This problem troubles me a lot. Hope to receive your reply.

**Comment by gyq18** [comment]
My question is how to  control a route with two lanes with different vsl signs, i.e. control lane_0 with 20m/s and control lane_1 with 15m/s?

**Comment by namdre** [comment]
answered in #5579

**Comment by gyq18** [comment]
thanks a lot!
