### ISSUE TITLE
rename {set,get}CompleteRedYellowGreenDefinition

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#5995]
The name is awkward and they are not the usual get/set pair, see #5986. Proposed new name is getAllLogics and setLogic with aliases at least for the python client.

**Comment by namdre** [comment]
already implemeneted as `setProgramLogic` and `getAllProgramLogics`

**Comment by behrisch** [comment]
should we deprecate the old call?

**Comment by namdre** [comment]
I don't mind keeping the alias. There's probably tons of old code still using ths.

**Comment by behrisch** [comment]
Yes, but if we deprecate it, at least there is no need to reimplement it in libsumo, libtraci etc.

**Comment by namdre** [comment]
fine then (-:
