### ISSUE TITLE
how to modify phase offset value of tllogic with libsumo or traci during simuation?

### ISSUE THREAD

**Issue by passengerxuhongli** [eclipse/sumo#5996]
hi all:

i want to control tlsid intersection and its adjacent intersection Coordinately. 
but  setCompleteRedYellowGreenDefinition(tlsid,tllogic) function can not modify offset of tllogic.
so is there function i can set a new offset for tllogic during simulation?

**Comment by namdre** [comment]
You can call trafficlight.setPhaseDuration to permanently shift the offset. This function only changes the duration of the current phase in the ***current*** cycle and keeps subsequent cycles at the original duration.
