### ISSUE TITLE
Split proj and gdal and update both to last version

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#5997]

**Comment by namdre** [comment]
@behrisch I'm sure there were some good reasons for having these in a single library. Are these reasons obsolete now?

**Comment by palvarezlopez** [comment]
@namdre The main reason is the following: The proj_gdal package provided by http://www.gisinternals.com has the following dependent libraries:

ECWSDK53
Oracle\instantclient_12_2
PDFlib-Lite-7.0.4p1
SWIG-1.3.39
agg-2.4
cairo-1.14.10
curl-7.37.1
expat-2.0.1
fcgi-2.4.0
fits-3.14
fontconfig-2.12.4
freetype-2.9.1
fribidi-0.19.2
gd-2.0.35
geos-3.4
gettext-0.13
giflib-4.1.6
hdf-4.2.9
hdf5-1.8.14
jpeg-6b
kealib-1.4.4
libiconv-1.11.1
libkml-svn-VC14
libpng-1.2.35
libspatialite-4.3.0a
libsvg-0.1.4
libsvg-cairo-0.1.6
libxml2-2.9.8 
mrsid\MrSID_DSDK-9.5.4.4709-win32-vc14
mysql-6.1.11
netcdf-4.3.2 
openjpeg-2.3.0
openssl-1.0.1h
pixman-0.34.0
poppler-0.30.0
postgresql-9.6.8
proj-6.0
sqlite-3.24.0
szip-2.1
xerces-c-3.2.1
zlib-1.2.3

I'm not sure if all these libraries are compatible with Eclipse license.

**Comment by behrisch** [comment]
@namdre No, it was just the easiest way to get them both in one package.
