### ISSUE TITLE
draw fundamental diagram--how to control density change

### ISSUE THREAD

**Issue by gyq18** [eclipse/sumo#6002]
Hello everyone. I'm new to SUMO community. I've been trying to  change speed to change density so that I could plot the relationship between volume and density.But it didn't work out as expected. Here are the test_codes:
![image](https://user-images.githubusercontent.com/45897323/63823615-0d27f080-c987-11e9-8716-8e276840258e.png)
![image](https://user-images.githubusercontent.com/45897323/63823633-1c0ea300-c987-11e9-9dd7-ea76f69b752f.png)
![image](https://user-images.githubusercontent.com/45897323/63823647-27fa6500-c987-11e9-8b0e-a0f0094d92a7.png)
![image](https://user-images.githubusercontent.com/45897323/63823659-334d9080-c987-11e9-9c11-d508306288b0.png)

[code.txt](https://github.com/eclipse/sumo/files/3548992/code.txt)

In order to learn space average and time average, I used loop and edge to measure and control speed. Here are the loop lane.det.xml:
`<additional>
<inductionLoop id="1" lane="lanetest_0" pos="10" freq="1" file="lanedrop.xml" friendlyPos="x"/>
<inductionLoop id="2" lane="lanetest_1" pos="10" freq="1" file="lanedrop.xml" friendlyPos="x"/>
<inductionLoop id="3" lane="lanetest_0" pos="90" freq="1" file="lanedrop.xml" friendlyPos="x"/>
<inductionLoop id="4" lane="lanetest_1" pos="90" freq="1" file="lanedrop.xml" friendlyPos="x"/>
</additional>`
Here are the nod.xml:
`<additional>
<inductionLoop id="1" lane="lanetest_0" pos="10" freq="1" file="lanedrop.xml" friendlyPos="x"/>
<inductionLoop id="2" lane="lanetest_1" pos="10" freq="1" file="lanedrop.xml" friendlyPos="x"/>
<inductionLoop id="3" lane="lanetest_0" pos="90" freq="1" file="lanedrop.xml" friendlyPos="x"/>
<inductionLoop id="4" lane="lanetest_1" pos="90" freq="1" file="lanedrop.xml" friendlyPos="x"/>
</additional>`
Here  are the lane.edg.xml:
`<edges xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/edges_file.xsd">
   <edge id="lanetest" from="1" to="2" numLanes="2" speed="33.3" />
</edges>`
However, results depend on speed control methods but speeds don't change as setted and all results seem greatly different from triangular fundamental diagram.  I don't know what mistakes are.  Hope to receive your answers.
![Figure_17](https://user-images.githubusercontent.com/45897323/63823205-95a59180-c985-11e9-8d6c-fb449f8f0d80.png)
![Figure_18](https://user-images.githubusercontent.com/45897323/63823212-9b02dc00-c985-11e9-870f-8c402bb8500e.png)
![Figure_19](https://user-images.githubusercontent.com/45897323/63823217-9fc79000-c985-11e9-8f66-1ecf5d258544.png)
![Figure_20](https://user-images.githubusercontent.com/45897323/63823225-a3f3ad80-c985-11e9-8197-18e2c7c13b20.png)

**Comment by gyq18** [comment]
I found that I made mistakes in coding. I will update coding and results.

**Comment by gyq18** [comment]
After I  fixed errors I found, codes and results are lister below:

[fd.zip](https://github.com/eclipse/sumo/files/3549525/fd.zip)
I'm new to SUMO so I don't understand some problems:
1. I set step 5000, however, it runs almost 9000 step in sumocfg.
2. As shown in figure_3, though I set speed from 33m/s to 1m/s,  speed_space and speed_time only change from 15/10 m/s to 0.  So how to control speed to change density?
3. As shown in figure_4, the max capacity is only 500 pc/h/ln, however, the max capacity about highway is about 2000 pc/h/ln
4. As shown in figure_1, the fundamental diagram is not triangle.

Hope to receive your answers.

**Comment by namdre** [comment]
Without looking at your files in detail I suppose that the issues you encounter are mostly due to insertion and speed distribution artifacts. 
I recommend taking a look at the following pages:
https://sumo.dlr.de/wiki/Tutorials/FundamentalDiagram
https://sumo.dlr.de/wiki/Simulation/VehicleInsertion#Insertion_.28Departure.29
https://sumo.dlr.de/wiki/FAQ#How_do_I_get_high_flows.2Fvehicle_densities.3F
https://sumo.dlr.de/wiki/FAQ#How_do_I_insert_vehicles_with_a_fixed_density.3F

**Comment by gyq18** [comment]
I'll look at these pages. Thank you very much!

At2019-08-28 18:44:01，Jakob Erdmannnotifications@github.comwrote:

Without looking at your files in detail I suppose that the issues you encounter are mostly due to insertion and speed distribution artifacts.
I recommend taking a look at the following pages:
https://sumo.dlr.de/wiki/Tutorials/FundamentalDiagram
https://sumo.dlr.de/wiki/Simulation/VehicleInsertion#Insertion_.28Departure.29
https://sumo.dlr.de/wiki/FAQ#How_do_I_get_high_flows.2Fvehicle_densities.3F
https://sumo.dlr.de/wiki/FAQ#How_do_I_insert_vehicles_with_a_fixed_density.3F
