### ISSUE TITLE
Container triggered stops block vehicles without container capacity

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#6003]
Warning: Vehicle 'trip_0' ignores container triggered stop on lane 'gneE0_0' due to capacity constraints.

check" tests\netedit\demandElements\stop\stopContainerStop\inspect_selection\duration"

**Comment by namdre** [comment]
the test is working as expected. The stop use both attributes 'triggered' and 'containerTriggered'. 
containterTriggered is ignored and triggered is responsible for blocking the vehicle.
