### ISSUE TITLE
platform dependencies in the undo list

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#6005]
In several tests Windows has 1 item less in the undo list than Linux, see for instance additionalElements/access/inspect_selection/blockmove (Windows has 3, Linux 4). The code in test.py suggests that 4 is the correct value.

**Comment by palvarezlopez** [comment]
Closed in https://github.com/eclipse/sumo/commit/edb31feb82bfbb8fde1c5ff51819c3ea39ed3971, but with invalid ticket reference
