### ISSUE TITLE
extractTest.py fails for sumo arguments with quotes

### ISSUE THREAD

**Issue by m-kro** [eclipse/sumo#6007]
Experienced with test sumo\devices\ssm\bugs\ticket5231:

> Error: The parameter 'DRAC'' is not allowed in this context.
>  Switch or parameter name expected.
> Error: The parameter '3'' is not allowed in this context.
>  Switch or parameter name expected.
> Error: Could not parse commandline options.
> Quitting (on error).

**Comment by karunasaga** [comment]
I am facing this issue while while trying to convert shapefile to SUMO Network , could you help thanks in advance

G:\SUMO_Project\NewYork_roadNetwork>netconvert -v --shapefile-prefix tl_2008_36061_edges -o net.net.xml--shapefile.from-id TNIDF --shapefile.to-id TNIDT --arcview.street-id tlid--shapefile.use-defaults-on-failure
Error: The parameter 'TNIDF' is not allowed in this context.
 Switch or parameter name expected.
Warning: Please note that 'arcview.street-id' is deprecated.
 Use 'shapefile.street-id' instead.
Error: Could not parse commandline options.
Quitting (on error).

**Comment by m-kro** [comment]
@karunasaga Please open a new ticket if you have a different problem. You don't use extractTest.py but netconvert here. Do you have any control characters (e.g. `\n`) in your command?
