### ISSUE TITLE
windows debug build is slow on flows in netedit checkoutput tests

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#6010]
Tests with a single flow work just fine but more flows exceed the 300 seconds (but only on windows debug), see netedit/demandElements/flow/create/arrivalPosLat

**Comment by palvarezlopez** [comment]
@behrisch probably related with the number of flows

**Comment by behrisch** [comment]
@palvarezlopez yes, the question is only why it is so extreme, the linux debug build does this in 40 seconds, windows needs more than 300.

**Comment by palvarezlopez** [comment]
This problem doesn't appear anymore. (But I cannot understand why)
