### ISSUE TITLE
NETEDIT: setting constant size for additionals not works at all zoom levels

### ISSUE THREAD

**Issue by ZoltanBaksa** [eclipse/sumo#6026]
Hi,
I have a network of a country region with detectors on the main roads. I switched on the "Draw with constant size when zoomed out" option in View settings. If I zoom out, the detectors disappear at a certain zoom level and reappear after zooming in.
I use latest development version v1_3_1+0039-5d6d0f05d7 on Windows 10 with the latest SUMOLibraries (30 aug. 2019 14:24)

**Comment by palvarezlopez** [comment]
@ZoltanBaksa Thanks! This case wasn't tested. I fix it.
