### ISSUE TITLE
speed adaption for departPos last

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#6041]
According to the code in MSLane.cpp:373 "last" insertion always fails if the gap to the leader is smaller than the secure gap with the input speed. Speed adaption is not considered.

**Comment by namdre** [comment]
This is intentional. The whole point of departPos=last is to keep the speed fix and adapt the position instead (ensuring high flow).

**Comment by namdre** [comment]
Since the introduction of departSpeed  `desired`, this special case isn't strictly needed anymore but I'd prefer not to break the current behavior as it would reduce the flow in existing scenarios.
