### ISSUE TITLE
Different edge length calculation methods are inconsistent in sumo 1.1.0

### ISSUE THREAD

**Issue by AlbertYuChen** [eclipse/sumo#6043]
There are several ways to get the length of an edge.

1. Netconvert converts the raw OSM file into sumo type network file. In the OSM file, an edge is described by a sequence of line segments. The line segments ends' positions in an edge are in latitude/longitude. netconvert change the latitude/longitude into meters. And the edge/lane length is in the output file.

2. sumolib.net.readNet gets the length data directly from the sumo type network file, which is the output of the netconvert.

3. of course we can manually calculate the edge length manually by adding the sum of the lengths of each line segment using the ends' positions.

4. In the sumo simulation fcd output file, you can get vehicle's position relative to the end of the edge at each time step. This is an indirect way to get the length of an edge. If you run the simulation with large traffic and get the largest position, that can be used to estimate the length of an edge.

5. netedit shows the edge length in the GUI.

The problem is that the values in 1,2,3 are the same and very close to 4, but they are different from 5. Sometime the error is significant, for example 1,2,3 = 557.10, 4=556.82, 5=560.72

**Comment by namdre** [comment]
After pressing F5 (compute junctions), netedit should show the same length value as 1,2,3. 
This computation (junction geometry, internal lanes)  is intentional to speed up network laoding.
