### ISSUE TITLE
Vehicular communications using Traci4matlab

### ISSUE THREAD

**Issue by suraty** [eclipse/sumo#6047]
Hello,
I am a beginner in SUMO and I am using Traci4matlab.
In [Traci4Matlab USER’S MANUAL](https://usermanual.wiki/Pdf/usermanual.2041518461.pdf) it is written:

> TraCI4Matlab allows controlling SUMO objects such as vehicles, traffic lights, junctions, etc, enabling
> applications like traffic lights predictive control, dynamic route assignment, and vehicular communications, among others.

Now I would like to send a message from a vehicle to the traffic light via vehicular communication, How can I do it?

Thank you

**Comment by namdre** [comment]
this type of communication is not part of sumo but can be emulated in a traci script. (use traci to determine the traffic light being approached and then use traci commands to change the traffic light state to simulate the intended result of the communication.
