### ISSUE TITLE
flow recovery and different flow on lanes

### ISSUE THREAD

**Issue by gyq18** [eclipse/sumo#6054]
![image](https://user-images.githubusercontent.com/45897323/64600158-3d42ab00-d3ed-11e9-8b7d-ba82ae7da5e5.png)
Hello, every one!  I ran 2-lanes road of 3000 cars/h/2lns flow. And let one car had accident for 20mins. However, after the accident was removed, the flow can't reach 3000 cars/h/2lns any more and flow on lane_1 is bigger than flow on lane_0.  I didn't understand why flow cann't recover to 3000cars/h/2lns any more and why flow on lane_1 is bigger than flow on lane_0. Hope to receive your answers. I'll appreciate that.  It's weird that, before accident, there isn't insertion-backlogged cars and  there are insertion-backlogged cars during and after the car accident.  I don't understand why there are still insertion-backlogged cars after the "the accident car" was in normal operation.
 In my figure, "v(m/s)" is supposed to be  "v(km/h)". And the abscissa is time, and each point is a five-minute statistic.
![image](https://user-images.githubusercontent.com/45897323/64600587-002ae880-d3ee-11e9-81de-fbb09b5ed1a5.png)
![image](https://user-images.githubusercontent.com/45897323/64600593-03be6f80-d3ee-11e9-83b1-17357206b86b.png)
![image](https://user-images.githubusercontent.com/45897323/64600604-091bba00-d3ee-11e9-9300-5d6cbd26f3a6.png)
My route file is:
![image](https://user-images.githubusercontent.com/45897323/64600940-95c67800-d3ee-11e9-8e3a-fa9b7ab46149.png)

**Comment by namdre** [comment]
departSpeed="max" can cause jams on the entry edge to persist because it allows lowering departSpeed rather than delaying insertion.  This can lead to very pronounced effects due to the low accel value you have set for your cars.
**Please try again with departSpeed="desired".**
Also, when running with the default step-length of 1s, vehicle insertion at a fixed position is affected by time step discretization and this can also reduce the maximum possible flow. You can compensate by using departPos="random_free" or departPos="last".

Insertion backlog for some time after the incident is too be expected because the flow really is lower during the incident and it takes some time to clear the backlogged insertion queue.

**Comment by gyq18** [comment]
Thank you very much for your reply.  However,  when I set departSpeed="desired",  there is an error as below:
Error: Invalid departSpeed definition for flow 'flow_car0';
must be one of ("random", "max", or a float>=0)
Quitting (on error).

Hope to receive your answer. Thank you very much!

At2019-09-10 18:17:59，Jakob Erdmannnotifications@github.comwrote:

departSpeed="max" can cause jams on the entry edge to persist because it allows lowering departSpeed rather than delaying insertion. This can lead to very pronounced effects due to the low accel value you have set for your cars.
Please try again with departSpeed="desired".
Also, when running with the default step-length of 1s, vehicle insertion at a fixed position is affected by time step discretization and this can also reduce the maximum possible flow. You can compensate by using departPos="random_free" or departPos="last".

Insertion backlog for some time after the incident is too be expected because the flow really is lower during the incident and it takes some time to clear the backlogged insertion queue.

**Comment by gyq18** [comment]
Thank you very much for your reply.  However,  when I set departSpeed="desired",  there is an error as below:
Error: Invalid departSpeed definition for flow 'flow_car0';
must be one of ("random", "max", or a float>=0)
Quitting (on error).

So I deleted departSpeed(default: 0m/s)  and used departPos="random_free"  and draw these results:
![image](https://user-images.githubusercontent.com/45897323/64609447-88fe5000-d3ff-11e9-8c33-603298c197d6.png)
![image](https://user-images.githubusercontent.com/45897323/64609466-96b3d580-d3ff-11e9-830c-45c812d52e19.png)
![image](https://user-images.githubusercontent.com/45897323/64609498-a7fce200-d3ff-11e9-9435-57bfbe70d680.png)
From the results, we can see that flow on lane_1 is still bigger than flow on lane_0. I didn't figure out. Hope to receive your answers! Thanks vey much!

**Comment by namdre** [comment]
departSpeed 'desired' is available since sumo version 1.3.0. I recommend upgrading.

If you cannot upgrade, you can also use the combination
departSpeed="max" departSpeed="last". This triggers a special behavior where positions are adapted but speeds are kept at the desired driver speed (preventing persistent jamming as described above).

**Comment by gyq18** [comment]
Thank your reply very much!
I still have a question. I set lane_0 and lane_1 with the same flow input. However, when the program runs, flow on lane_1 is still bigger than flow on lane_0 by 500 cars/h/ln.  Does sumo prioritize the left lane so that the left lane has more traffic flow than the right lane?

**Comment by namdre** [comment]
in the absence of ramps or other route-related lane-preferences, the only asymmetry should come from 
- the prohibition to overtake on the right (can be disabled by setting --lanechange.overtake-right)
- the obligation to move to the right lane when it is free (configurable with vType parameter lcKeepRight)
Also, the incident on lane 0 can have immediate as well as a lingering effects.

**Comment by gyq18** [comment]
Thank you very much.  I made a test with no incident before and found that flow on lane_1 was always still bigger than flow on lane_0 by 500 cars/h/ln. I just tried as you said. It works!(Although just using --lanechange.overtake-right doesn't work. However, changing lcKeepRight works!) 
I really appreciate your help!

**Comment by namdre** [comment]
I find the difference of 500 cars/h surprising. Can you attach your scenario files?
