### ISSUE TITLE
libsumo.trafficlight.getCompleteRedYellowGreenDefinition(tls_id)[0].phases.size() always is 0?

### ISSUE THREAD

**Issue by passengerxuhongli** [eclipse/sumo#6093]

**Comment by passengerxuhongli** [comment]
add some information about this issue.

i found a intresting things:
    old_logic=libsumo.trafficlight.getCompleteRedYellowGreenDefinition(tls_id)[0]
    phases_num=old_logic.phases.size()
       (the value of phases_num>0)
  this code's result is different below:
     phases_num= libsumo.trafficlight.getCompleteRedYellowGreenDefinition(tls_id)[0].phases.size()
    (the value of phases_num=0)
is that a bug?

**Comment by behrisch** [comment]
size() is not the way to get the size of a list in python, using len(...) works here. Please reopen (also with more details about the python version you use) if problems persist.

**Comment by passengerxuhongli** [comment]
envoriment:win10+ python3.7 + sumoV1.2.0+libsumo come from source code via complied

the type of libsumo.trafficlight.getCompleteRedYellowGreenDefinition(tls_id)[0].phases is a c++ vecotor.
when using len(...), it error, that is why i used size() and it does work! !!

and similar problems like this:

phases=libsumo.trafficlight.getCompleteRedYellowGreenDefinition(tls_id)[0].phases

"phases.append(newphases)"   error, but "phases.push_back(newphases) "  success

i want to know how this occured?

**Comment by behrisch** [comment]
Please retry with a newer sumo version, libsumo support was still rudimentary in 1.2.0. There needs to be a separate mapping to be defined in the interface file libsumo.i to translate the vector into a python list.
