### ISSUE TITLE
Vehicles will be stucked when change sub lane

### ISSUE THREAD

**Issue by Laysest** [eclipse/sumo#6106]
I use sub lane model (lateral resolution) to simulate mixed traffic in undeveloped countries. In real world, cars usually move on left of lane and go parallelly with motorbikes. But in SUMO cars tend to move on center of lane and prevent motorbikes to go parallely. So I use traci.vehicel.changeSublane to put cars on left of lane with a probability. But It make a few cars to be stucked, although front of these cars is clear.

You can see the image of the stocked car in our intersection. Thank you so much.
[https://drive.google.com/file/d/1BrrKGfu_0EINoyaV3R2uKb-JV0iAw-DE/view](https://drive.google.com/file/d/1BrrKGfu_0EINoyaV3R2uKb-JV0iAw-DE/view)

**Comment by namdre** [comment]
A vehicle must be fully within the boundaries of their lane before leaving an intersection. I suppose this condition might be violated in your example. 

Note, that you can change the preferred lateral alignment of the cars: `<vType latAlignment="left"... />`

**Comment by Laysest** [comment]
Thank for your supporting
