### ISSUE TITLE
how to charge electric vehicle

### ISSUE THREAD

**Issue by JINGUO918** [eclipse/sumo#6118]
I have set the electric vehicle type and charging station,  but how can I set the charging station? Is it automatically?  I have set the EV low electricity, but it seems it does not work.

**Comment by namdre** [comment]
By default charging stations are only activated if a vehicle drops below a threshold speed (default 0.1m/s).
You can either
- place the charging station where vehicles usually stop (ahead of a traffic light)
- make the vehicle stop with a `<stop>` element
- set the station to charge in transit 
- set a different speed threshold for the battery device.

**Comment by JINGUO918** [comment]
but how can I assign the battery device to vehicles, I have set the parameters for EV.
`    <vType id="evehicle" length="12.00" minGap="2.50" maxSpeed="100.00" accel="1.0" decel="1.0" sigma="0.0">
        <param key="actualBatteryCapacity" value="50"/>
        <param key="airDragCoefficient" value="0.6"/>
        <param key="constantPowerIntake" value="100"/>
        <param key="frontSurfaceArea" value="5"/>
        <param key="internalMomentOfInertia" value="0.01"/>
        <param key="maximumBatteryCapacity" value="2000"/>
        <param key="maximumPower" value="1000"/>
        <param key="propulsionEfficiency" value="0.9"/>
        <param key="radialDragCoefficient" value="0.5"/>
        <param key="recuperationEfficiency" value="0.9"/>
        <param key="rollDragCoefficient" value="0.01"/>
        <param key="stoppingTreshold" value="0.1"/>
        <param key="vehicleMass" value="10000"/>`

**Comment by namdre** [comment]
add `<param key="has.battery.device" value="true"/>`
also see https://sumo.dlr.de/docs/Definition_of_Vehicles,_Vehicle_Types,_and_Routes.html#devices
