### ISSUE TITLE
step-length > 5s causes error

### ISSUE THREAD

**Issue by AlbertYuChen** [eclipse/sumo#6123]
I'm using sumo 1.1.0. 
if step-length > 5, it shows the following error.
F0929 14:58:19.205404  190194 logging.cc:89] assert.h assertion failed at third_party/sumo/sumo_1_1_0/src/microsim/output/MSInductLoop.cpp:111 in virtual bool MSInductLoop::notifyMove(SUMOVehicle &, double, double, double): !MSGlobals::gSemiImplicitEulerUpdate || newSpeed > 0 || myVehiclesOnDet.find(&veh) == myVehiclesOnDet.end()

if step-length > 20
F0929 15:01:54.298340  190771 logging.cc:89] assert.h assertion failed at third_party/sumo/sumo_1_1_0/src/microsim/lcmodels/MSLCM_LC2013.cpp:1188 in int MSLCM_LC2013::_wantsChange(int, MSAbstractLaneChangeModel::MSLCMessager &, int, const std::pair<MSVehicle *, double> &, const std::pair<MSVehicle *, double> &, const std::pair<MSVehicle *, double> &, const MSLane &, const std::vector<MSVehicle::LaneQ> &, MSVehicle **, MSVehicle **): memoryFactor > 0.

**Comment by namdre** [comment]
Most components of SUMO are only tested with step-length 1.0 or lower. 
At the level of detail that the microscopic simulation aims for, going higher doesn't make much sense. If you need a faster, coarser simulation, use meso: https://sumo.dlr.de/docs/Simulation/Meso.html

**Comment by AlbertYuChen** [comment]
I still have that problem even after setting step-length to 1.0. 
It seems this error is related to the detector output. Should I avoid creating some specific types of output? My current settings are:
```
<input>
        <net-file value="map/mynet.net.xml"/>
        <route-files value="demands/demands.rou.xml"/>
        <additional-files value="map/detector.add.xml,map/taz.add.xml"/>
    </input>

    <output>
        <fcd-output value="output/traffic.fcd.xml"/>
        <summary-output value="output/summary.xml"/>
        <tripinfo-output value="output/tripinfo.xml"/>
        <vehroute-output  value="output/vehicle_route.xml"/>
        <vehroute-output.cost value="true"/>
        <vehroute-output.route-length value="true"/>
        <lanechange-output value="output/lane_change.xml"/>
        <lanechange-output.started value="true"/>
        <lanechange-output.ended value="true"/>
    </output>

    <processing>
        <ignore-route-errors value="true"/>
        <collision.action value="none"/>
    </processing>

    <time>
        <step-length value="1.0"/>
        <!-- 12 hours -->
        <end value="43200"/>
    </time>
```

**Comment by zhuliwen** [comment]
When I run **traci.simulationStep()** in SUMO 1.2.0, I got these issues:
`sumo: /build/sumo-tHynv2/sumo-1.2.0+dfsg1/src/microsim/output/MSInductLoop.cpp:111: virtual bool MSInductLoop::notifyMove(SUMOTrafficObject&, double, double, double): Assertion `!MSGlobals::gSemiImplicitEulerUpdate || newSpeed > 0 || myVehiclesOnDet.find(&veh) == myVehiclesOnDet.end()' failed.`

And when I switched to SUMO 1.0.1, the problem doesn't exist.
I don't know why, but it makes sense.

**Comment by namdre** [comment]
That assertion has been part of the code since version 0.28.0. However, the assertion is invalid under some circumstances and therefore was removed in version 1.3.0
(Since most people run the release version, that assertion never got triggered in the meantime).

**Comment by AlbertYuChen** [comment]
@namdre Thanks Jakob. Would you please explain more why this can happen? This can happen a lot when there is a congestion with many teleports. If I disable the teleport, the assertion disappears but the gridlocks can happen. Are those related?

**Comment by namdre** [comment]
Teleporting vehicles may pass detectors without registering and the assertion assumed that vehicles can only pass the detector if they are registered along the way.
