### ISSUE TITLE
each client receive the same data strean

### ISSUE THREAD

**Issue by ichtreenewbee** [eclipse/sumo#6124]
i use sumo to simulate the traffic. three clients connecte with sumo. each ego is a clinet and receives the traffic surround the three egos. 
but for the vehicle simulation, only the fellows surround the simulated vehicle are needed. is it possible that each client gets only the fellows surround the simulatede ego?
e.g: three egos: ego 1(client 1), ego 2(client 2) and ego 3(client 3)
sumo send only fellows arround ego 1 to client 1.

SUMO-RLS: 1.3.1
Multi client scenarios: 3 Client, each client is a ego

**Comment by namdre** [comment]
No, this is not yet possible but it's a known issue: https://github.com/eclipse/sumo/issues/4447
