### ISSUE TITLE
Simulation state saving crash (TraaS)

### ISSUE THREAD

**Issue by danpittphd** [eclipse/sumo#6125]
Dear Sumo team,

I tried the following simple scenario:
* I loaded one of the sumocfg files from the Luxembourg scenario
* After one step into the scenario, I tried to save the state. The java application crashes:
import de.tudresden.sumo.cmd.Simulation;
import it.polito.appeal.traci.SumoTraciConnection;

import java.io.IOException;

public class scrub {
    static String config_file = "LUXscenario/scenario/due.actuated.sumocfg";

    static double step_length = 10;
    static String sumo_cmd = "sumo";

    public scrub() throws Exception {
        System.out.println("Hello World!");
        SumoTraciConnection conn = new SumoTraciConnection(sumo_cmd, config_file);
        conn.addOption("step-length", step_length + "");
        conn.addOption("start", "true"); //start sumo immediately
        conn.runServer();
        conn.setOrder(1);
        while ((int) conn.do_job_get(Simulation.getMinExpectedNumber()) > 0) {
            conn.do_timestep();
            conn.do_job_get(Simulation.saveState("file-state-now"));
        }
    }
}
Result:
Exception in thread "main" java.lang.NullPointerException
	at de.tudresden.sumo.util.CommandProcessor.verifyGetVarResponse(Unknown Source)
	at de.tudresden.sumo.util.CommandProcessor.do_job_get(Unknown Source)
	at it.polito.appeal.traci.SumoTraciConnection.do_job_get(Unknown Source)
	at scrub.<init>(scrub.java:21)
	at Main.main(Main.java:25)

Operating system: Ubuntu 18.04
Sumo version: 1.2.0
Traas version: the one that comes with Sumo 1.2.0

**Comment by behrisch** [comment]
You need to do do_job_set instead of do_job_get here but I agree this needs a better error message.

**Comment by danpittphd** [comment]
Thanks a lot! It worked.
