### ISSUE TITLE
documentation search not working in chrome

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#6128]
Google Chrome Version 77.0.3865.90 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/6240630/65950400-43510800-e43e-11e9-8654-756436881067.png)

**Comment by angelobanse** [comment]
@namdre could you try it again by opening the site in a Private Tab or by deleting the Browser-Cache?

**Comment by angelobanse** [comment]
it works just fine, i just tried it with the same Chrome version.

**Comment by lcodeca** [comment]
I'm using Version 77.0.3865.90 (Official Build) (64-bit) on Ubuntu 19.04 and I cannot make it work.
Browsing Incognito presented the same issue. 
I cleaned the cache (last 4 weeks using the options panel), but both normal and incognito are just showing the screenshot, but not the search.

**Comment by angelobanse** [comment]
@lcodeca is it working on Firefox?

**Comment by lcodeca** [comment]
No, still the same. It's the first time I opened it, just so you know that there are no personal configurations associated with it. It's Firefox Quantum 69.0.1 (64-bit)

![FirefoxSUMOSearch](https://user-images.githubusercontent.com/5700703/66026920-be272b00-e4f1-11e9-8ece-5b298a4d07e4.png)

Is it possible that I don't understand the interaction? 
Click on Search Icon, start typing what you are looking for. (nothing happens)
Click on the Search (green bar), nothing happens.
Click on the white part, nothing happens.
Click everywhere else, it closes.

**Comment by angelobanse** [comment]
@lcodeca we are using a Google Custom Search Engine like in the old Wiki.

You can open the search Modal by clicking on the search-icon or simply pressing the "s" key.

A search box should appear:
<img width="1440" alt="Captura de Pantalla 2019-10-02 a la(s) 9 58 17" src="https://user-images.githubusercontent.com/16121932/66027682-b5d3ed80-e4fb-11e9-91ad-c1c981b6f8d4.png">

Type your search and press <Enter\>.

The results will appear on the Modal (you can scroll down and even get multiple results pages).
<img width="1440" alt="Captura de Pantalla 2019-10-02 a la(s) 9 58 26" src="https://user-images.githubusercontent.com/16121932/66027712-c5ebcd00-e4fb-11e9-9bd8-2e31713711de.png">

You can dismiss the Modal by clicking outside of it, clicking the upper right corner "x" or just pressing the <esc> key.

If you click on any result, the link will open in the same browser tab you were currently using.

---
I am using the Documentation on Google Chrome (77.0.3865.90) and Firefox (69.0.1) on macOS Mojave (10.14.6), Windows 10 (v.1903) and Ubuntu 19.04 and this search Modal is working.

I will continue investigating this issue.

**Comment by lcodeca** [comment]
Problem understood, not sure yet how to solve it for real.
It's the work infrastructure firewall. I tried with my personal VPN and it works.
I have no idea what queries the search bar is actually making in order to be blocked in that way.
Anyway, sorry to waste your time.

**Comment by angelobanse** [comment]
Not a waste at all, thanks for this information.
