### ISSUE TITLE
e1 Detectors get wrong counts.

### ISSUE THREAD

**Issue by AlbertYuChen** [eclipse/sumo#6132]
If I place several detectors at the an entrance road and cover all lanes, the total count is different from the total number of cars entering the map. Neither nVehContrib or nVehEntered gives the right answer. I also tried setting a long interval, which is long enough to cover the whole simulaiton, but still does not work. All those detectors are aligned at the same position, so if a car changes its lane to another, it should be caught by at least one detector right?

**Comment by namdre** [comment]
depending on insertion options, vehicles might be inserted beyond the detectors.

**Comment by AlbertYuChen** [comment]
The detectors are places behind the entrance edge.

**Comment by AlbertYuChen** [comment]
Can I send you my simulation? It's a very simple network I used to test the detectors.

**Comment by namdre** [comment]
Yes. Attach the simulation files or send them directly to me.
