### ISSUE TITLE
wrong strerror_r function gets used under musl

### ISSUE THREAD

**Issue by neheb** [eclipse/sumo#6136]
strict_fstream.hpp has an interesting ifdef maze that goes like this:

non-standard function
standard function
non-standard function

This breaks compilation when musl gets used as the conditions end up not being true (gcc defaults to std=gnuXX which enables GNU_SOURCE). musl does not support the GNU extension under any circumstance.

The solution is to manually compile with std=c++XX (which is probably not wise) or fix the ifdef maze as such:

non-standard function
non-standard function
standard function

**Comment by behrisch** [comment]
seems to be fixed
