### ISSUE TITLE
Vehicle behaviors at intersections and roundabouts

### ISSUE THREAD

**Issue by fywu85** [eclipse/sumo#6138]
What is the model being used for vehicles approaching traffic lights and roundabout? I know vehicles will follow whichever model you specify (i.e. IDM, Krauss), but these car following models don't dictate vehicle behavior at traffic lights -- Is there any information on this? The same goes for lane changing models -- I'd appreciate any information about how vehicle perform lane changes at those junctions too!

**Comment by namdre** [comment]
Vehicles apprach traffic lights with a model-specific deceleration profile. This is often derived from the way a stationary car is being approached. Roundabouts are approached like a non-prioritized approach at a priority junction (deceleration up the the point of clear visibility, stopping only when necessary). For details, see https://elib.dlr.de/93669/
Lane changing ahead of intersections/roundabout is subject to the standard lane-changing model rules (https://elib.dlr.de/89233/). Leader search for purpose of tactical lane-changing choice is not performed beyond red lights and junctions that are reserved by higher priority traffic.
There are some exlicit provisions for changing to the inside of a multi-lane roundabout for cooperative reasons. This also includes changing ahead of roundabouts for entering on the inside roundabout-lane. The details are not published but can be found in https://github.com/eclipse/sumo/blob/master/src/microsim/lcmodels/MSLCM_LC2013.cpp#L1778
