### ISSUE TITLE
keeping the same cycle time after using traci.trafficlight.setPhaseDuration

### ISSUE THREAD

**Issue by aminissn** [eclipse/sumo#6143]
Hi,

When I change the duration of one phase, all the other phases remain the same as before which means the cycle length will increase. Is there an easy way to reduce the duration of other phases automatically in order to get the same cycle time? 
My particular example is to set green/cycle ratio for the traffic light instead of setting the duration of each two phases (red-green) separately. 

Thanks,
Sasan

**Comment by namdre** [comment]
setPhaseDuration only affects the current cycle. Thus it is unsuited to changing the green split for future cycles anyway. Alternatively, you can patch the whole signal plan using 
traci.trafficlight.getCompleteRedYellowGreenDefinition
traci.trafficlight.setCompleteRedYellowGreenDefinition
