### ISSUE TITLE
How do you write a custom scheduling algorithm to switch between phases of a custom traffic signal?

### ISSUE THREAD

**Issue by anon747** [eclipse/sumo#6145]
Hello!
I am trying to implement the ITLC algorithm (PDF in the attached file) for a study project. I want to know how I can incorporate a scheduling algorithm of my own into my code, to switch between the phases of my actuated traffic signal. 
Any help would mean a lot! 
[TrafficSim2.zip](https://github.com/eclipse/sumo/files/3713758/TrafficSim2.zip)

**Comment by namdre** [comment]
see https://sumo.dlr.de/docs/Simulation/Traffic_Lights.html#controlling_traffic_lights_via_traci
