### ISSUE TITLE
Error when loading a simulation file (on mac)

### ISSUE THREAD

**Issue by rs06085** [eclipse/sumo#6149]
When I am trying to open a simulation file, it shows an error:
Error: File '/usr/local/Cellar/sumo/1.3.1/bin/example1.net.xml' is not accessible (No such file or directory).
Quitting (on error).

I have tried all possible locations but I have always the same error.

Thanks in advance

**Comment by namdre** [comment]
are you trying to open a network from within sumo-gui or loading it from the command line or are you loading a .sumocfg file?

**Comment by rs06085** [comment]
I am trying both ways, but the error is the same.

**Comment by namdre** [comment]
have you tried loading the example networks that can be found in the docs/examples folder of your sumo installation?

**Comment by rs06085** [comment]
I have installed sumo using brew. I searched all folders but I cannot find the examples.

**Comment by rs06085** [comment]
I replaced 
<configuration> 
with
<?xml version="1.0" encoding="UTF-8"?>

<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/sumoConfiguration.xsd">

in my file and now it works fine!
