### ISSUE TITLE
Add new MRMSafeSpot-parameter to ToC device and adjust MRM vehicle behaviour

### ISSUE THREAD

**Issue by robertalms** [eclipse/sumo#6157]
In case a vehicle performs an MRM it should target a given safespot (ParkingArea) when given such a safespot via an additional paramater like "MRMSafeSpot". If such a parameter is not provided the vehicle should perform its MRM as it is currently implemented in the ToC model.

**Comment by behrisch** [comment]
@robertalms a stop needs always a duration or until time. Shall we assume simply "inifnity" here or do you need another parameter?

**Comment by robertalms** [comment]
We'll need the 'duration' as a parameter. Otherwise our dynamic safespot assignments wouldn't be of much use if MRMvehicles never continue their trip.

**Comment by behrisch** [comment]
Do we have an idea for a good default?

**Comment by robertalms** [comment]
60 seconds

**Comment by robertalms** [comment]
TODO: Once both parameters are fully tested (within the next few weeks for TransAID simulations), add parameters to Wiki description; https://sumo.dlr.de/docs/ToC_Device.html .
