### ISSUE TITLE
AttributeError: module 'traci' has no attribute 'trafficlights'

### ISSUE THREAD

**Issue by chuckbassx** [eclipse/sumo#6163]
Hi,
my codes run well using "sumo-0.32.0", but I updated to "sumo-1.3.1", the error 'AttributeError: module 'traci' has no attribute 'trafficlights'' came out.
Can you tell me how to solve this, please?

**Comment by behrisch** [comment]
0.32.0 should have shown a deprecation warning for that already. The module is now called trafficlight (without the "s").

**Comment by dannymanastireanu** [comment]
Thanks
