### ISSUE TITLE
how can i make a car running acorrding to a loop route?

### ISSUE THREAD

**Issue by passengerxuhongli** [eclipse/sumo#6166]
now there is a 4 intersections network ( box network);
i want to make a car looping in this network forever,
how can i make the route.xml file?

**Comment by m-kro** [comment]
Have a look at the [rerouter](https://sumo.dlr.de/docs/Simulation/Rerouter.html) documentation. Define a route which goes around for one time and then use a rerouter to make the vehicle repeat the route.
