### ISSUE TITLE
SUMO street-parking implementation issue

### ISSUE THREAD

**Issue by lijiayi9712** [eclipse/sumo#6173]
Hi, I am trying to implement street-parking on SUMO with traci. However, I encountered some difficulties with the setup. The basic idea of my implementation is to 
(1). set up an array of parking lot of capacity 1 on a lane 
(2). add cars to the lane with traci.vehicle.addFull( vehID=veh_idi, routeID=route_id, departSpeed=0) and set stop using traci.vehicle.setParkingAreaStop(vehID=veh_idi, stopID='PCD03_00', duration=5). 
(3). add rerouter that any parking lot in one lane can be rerouted to any other lots on the same lane.

However, when the space between two parking lots is less than (such as half of) the length of a car, I would encounter conflicts between cars trying to entering and leaving the same parking space, which would stop the entire traffic flow. Here is a screenshot: 
/Users/LiJiayi/Desktop/Screen Shot 2019-10-18 at 7.51.19 PM.png

When space between two parking lots is greater than or equal to car length, this problem could be solved. But large spacing is not realistic in real-life street parking. 

Is this control behavior well-supported in SUMO? And is there any solution to this issue? Truly appreciate your help!

**Comment by lijiayi9712** [comment]
Sorry, here is the screenshot:
<img width="1156" alt="Screen Shot 2019-10-18 at 7 51 19 PM" src="https://user-images.githubusercontent.com/25253573/67137050-1f364a80-f1e4-11e9-829a-53a519ef556f.png">

**Comment by behrisch** [comment]
We solved something like this in #5128. Which sumo version do you use? (It might also be related to #5577.)

**Comment by lijiayi9712** [comment]
Dear Michael,

Thank you so much for your reply. I used version 1.2.0. Is that the latest
version? The two earlier issues are very relevant to my problem. But I am
still confused about how to solve it, specifically how to "restrict the
help request scenario to the situation where the parkingArea is at capacity"?
Also, do you have suggestions on the implementation of street parking? Is
an additional parking lane going to be helpful? Truly appreciate your help!

Best,
Jiayi

**Comment by namdre** [comment]
The latest version is 1.3.1. so please try that.

Street parking is somewhat supported by setting the onRoad="true" in the parkingArea definition. The problem here is that parkingAreas by themselves do not consider vehicle size (they can fit at 10m vehicle in a 1m space). If you activate onRoad, the these checks are enforced by the simulation which means that vehicles may not be able to reach their assigned space.

It should work, if each parking space is long enough to accomodate length+minGap of the longest vehicle.
