### ISSUE TITLE
cant build with visual Studio2019

### ISSUE THREAD

**Issue by TRYGISER** [eclipse/sumo#6174]
visual Studio 2019 can't config CmakeLists.txt with the right path of xerces-c-3.2.0_64 in win64_debug mode

**Comment by palvarezlopez** [comment]
@TRYGISER are you using SUMOLibraries?

**Comment by TRYGISER** [comment]
yes with sumo_libraries at https://github.com/DLR-TS/SUMOLibraries

**Comment by TRYGISER** [comment]
i have build sumo with cmake and vs2017,but for the latest edition it can't find the correct path of the libs like SUMOLibraries_64 or not the xerces-c-3.2.0_64 but xerces-c-3.2.0 under x64_debug mode

**Comment by TRYGISER** [comment]
here is the auto generated cmake config with vs2019,
```
{
  "configurations": [
    {
      "name": "x64-Debug",
      "generator": "Ninja",
      "configurationType": "Debug",
      "inheritEnvironments": [ "msvc_x64_x64" ],
      "buildRoot": "${projectDir}\\out\\build\\${name}",
      "installRoot": "${projectDir}\\out\\install\\${name}",
      "cmakeCommandArgs": "",
      "buildCommandArgs": "-v",
      "ctestCommandArgs": "",
      "variables": [
        {
          "name": "SUMO_LIBRARIES",
          "value": "E:/Documents/DR/ITS/SUMO/SUMOLibraries_64",
#there is no "SUMOLibraries_64" directory,the directory of SUMO lib cloned is "SUMOLibraries"
          "type": "PATH"
        }
      ]
    }
  ]
}
```

**Comment by TRYGISER** [comment]
if i should set the cmake variables of these lib path like "XERCES_PATH"  in CMakeSettings.json or in the system enviroment variables?

**Comment by TRYGISER** [comment]
Should i  set the cmake variables of these lib path like "XERCES_PATH" in CMakeSettings.json or in the system enviroment variables?

**Comment by palvarezlopez** [comment]
@TRYGISER you only need to set the environment variable SUMO_LIBRARIES with the path to SUMOLibraries folder (ej: SUMO_LIBRARIES="C:\SUMOLibrares"). Also you need to have the last version of SUMOLibraries. Open the windows command console (CMD), move to SUMOLibraries folder, and execute "git pull"

**Comment by behrisch** [comment]
Another important step is to clear the CMakeCache.txt after updating SUMOLibraries.

**Comment by TRYGISER** [comment]
i will try to update my sumo_libraries and build again

**Comment by TRYGISER** [comment]
thank you
it build success with the default setting
