### ISSUE TITLE
Can DFROUTER work for a signalized corridor? 

### ISSUE THREAD

**Issue by arsenious** [eclipse/sumo#6176]
Hi

I went through https://sumo.dlr.de/docs/Demand/Routes_from_Observation_Points.html  
and noticed that DFROUTER tool is used for highway traffic replication from recorded data.

Is there any such tool for a signalized corridor? I have high-resolution loop detector logs for a small corridor(all approaches) with signal event times. I have hand-drawn the lanes by hand and wanted to replicate recorded flows in SUMO.

Thank you!

**Comment by behrisch** [comment]
DFROUTER cannot take signal timings into account. You can generate input for your simulation but it will only use the aggregated values. There is currently no tool in the SUMO suite which does that. What we once did is to start with a scenario generated from aggregated data and then optimize it to fit the measured data using a similar approach like the one here: https://sumo.dlr.de/docs/Tutorials/Calibration/San_Pablo_Dam.html

**Comment by arsenious** [comment]
Thank you I will check it out
