### ISSUE TITLE
change laneChangeModel's parameters by traci ---is there function in traci to change lcCooperative's value?

### ISSUE THREAD

**Issue by passengerxuhongli** [eclipse/sumo#6177]
hi sumo developer
i want to calibrator my lanechange mode and carfollowing model,
so i need to change lanechange model parameters such as lcCooperative, lcStrategic, lcLookaheadLeft and so on.
and i know how to change vehicleType attribultes by traci_vehicleType, but it do not containt  some attribute such as lcCooperative. so i want to know where can i change laneChange& carFollowing model parameters by traci?

now, i know change vType.add.xml to acheive it. but i also want to know if i can acheive it by traci?

thks!

**Comment by behrisch** [comment]
You can set them using the generic parameter interface, see https://sumo.dlr.de/docs/TraCI/Change_Vehicle_State.html#setting_device_and_lanechangemodel_parameters_0x7e. So for setting lcCooperative to 0.5 for vehicle "x" you call
 `traci.vehicle.setParameter("x", "laneChangeModel.lcCooperative", "0.5")`. This works for carFollowModel parameters as well (using the prefix `carfollowModel`).

**Comment by zhaotuo0815** [comment]
> You can set them using the generic parameter interface, see https://sumo.dlr.de/docs/TraCI/Change_Vehicle_State.html#setting_device_and_lanechangemodel_parameters_0x7e. So for setting lcCooperative to 0.5 for vehicle "x" you call
> `traci.vehicle.setParameter("x", "laneChangeModel.lcCooperative", "0.5")`. This works for carFollowModel parameters as well (using the prefix `carfollowModel`).

hello,developer.When I call traci.vehicletype.setParameter("carType", "laneChangeModel.lcCooperative", "0.5"),the running state of sumo has not change,it seems that the call does not work

**Comment by namdre** [comment]
Since version 1.5.0 the cooperative behavior is influenced by three differet parameters which you can adjust independently via traci:
- laneChangeModel.lcCooperative: for cooperative lane changing
- laneChangeModel.lcCooperativeSpeed: cooperative speed adjustment
- laneChangeModel.lcCooperativeRoundabout: driving on the inside of a multi-lane roundabout

**Comment by zhaotuo0815** [comment]
> Since version 1.5.0 the cooperative behavior is influenced by three differet parameters which you can adjust independently via traci:
> 
> * laneChangeModel.lcCooperative: for cooperative lane changing
> * laneChangeModel.lcCooperativeSpeed: cooperative speed adjustment
> * laneChangeModel.lcCooperativeRoundabout: driving on the inside of a multi-lane roundabout

thank you for your reply!but I still have some troubles when  I want to change lanechange model parameters such as lcCooperativeI by traci.vehicletype.setParameter("carType", "laneChangeModel.lcCooperative", "0.1"),however the running state of sumo has not change.For example I set the lcCooperative to 0.1 in the rou.xml file,there will be congestion in the vehicle,but I use  traci.vehicletype.setParameter("carType", "laneChangeModel.lcCooperative", "0.1"),the behavior of the vehicle is the same as before it was not set ,it seems that the call does not work !

**Comment by namdre** [comment]
The lanechangemodel parameters must be set on the vehicle, not the vehicle type.

**Comment by zhaotuo0815** [comment]
> The lanechangemodel parameters must be set on the vehicle, not the vehicle type.

Thanks a lot!

**Comment by zhaotuo0815** [comment]
> hi sumo developer
> i want to calibrator my lanechange mode and carfollowing model,
> so i need to change lanechange model parameters such as lcCooperative, lcStrategic, lcLookaheadLeft and so on.
> and i know how to change vehicleType attribultes by traci_vehicleType, but it do not containt some attribute such as lcCooperative. so i want to know where can i change laneChange& carFollowing model parameters by traci?
> 
> now, i know change vType.add.xml to acheive it. but i also want to know if i can acheive it by traci?
> 
> thks!



> The lanechangemodel parameters must be set on the vehicle, not the vehicle type.

hello,developer,I have met some troubles when I used traci.vehicle.setParameter:traci.exceptions.TraCIException: Vehicle 'xinshi142985' does not support laneChangeModel parameter 'laneChangeModel.IcKeepRight' (Setting parameter 'IcKeepRight' is not supported for laneChangeModel of type 'LC2013').

and I do not how to deal with this trouble,thks!
