### ISSUE TITLE
Test suite result differs from single SUMO run

### ISSUE THREAD

**Issue by m-kro** [eclipse/sumo#6183]
Related to #6009 : I have problems replicating test results obtained through texttest by running SUMO individually. Using texttest, I get the same results as @schwamborn for test devices/ssm/config/decreased_extratime_following :

```
TEST FAILED on IVS012 : SUMO test-case decreased_extratime_following (under devices/ssm/config/decreased_extratime_following)
---------- Differences in ssm ----------
5c5
<     <conflict begin="1.00" end="10.60" ego="ego1" foe="foe1">
---
>     <conflict begin="1.00" end="10.00" ego="ego1" foe="foe1">
```
Using the sumocfg obtained with extractTest.py, the SSM result file reads...
`<conflict begin="1.00" end="10.60" ego="ego1" foe="foe1">`

**Comment by schwamborn** [comment]
I actually copied the output from the daily test runs:

https://sumo.dlr.de/daily/gcc4_64report/sumo/test_default_17Oct2019_17Oct19rv1_3_1+0617-7fdb5d8271.html#defaultdevices%20ssm%20config%20decreased_extratime_following

Are you sure the sumo version used by TextTest and the one you used after the test extraction are the same? You might want to take a look at the env var SUMO_HOME.

**Comment by m-kro** [comment]
Yes, I just repeated it by calling SUMO explicitly with SUMO_HOME\bin\sumo just to be sure.

**Comment by m-kro** [comment]
OK, the SUMO versions are not the same. The output above is from DLR-compiled SUMO 1.3.1, while Texttest result is from my own build. Does not help much but I will look more closely...
