### ISSUE TITLE
convert fcd-output into IPG traces

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#6190]
(another output format option for traceExporter.py)

Format is

```
# Time tx ty tz rx ry rz
0 0 0 0 0 0 0
1 0 0 0 0 0 0
2 0 0 0 0 0 0
```

(time, 3 location values, 3 rotation values)

**Comment by namdre** [comment]
@RNippold: how about it?

**Comment by lbieker** [comment]
@namdre Is there an example for an IPG file? How should the rotation values look like?

**Comment by namdre** [comment]
I do not have en example file. Probably the angles are yaw,pitch and roll so you can set the first one to the 'angle' value and leave the others at 0.

**Comment by lbieker** [comment]
Thx

**Comment by behrisch** [comment]
For the records: I removed the extra newlines in 63fd54060c1e81a3814b16d04fc147e735cdc99d
