### ISSUE TITLE
tlTypes without documentation

### ISSUE THREAD

**Issue by alexdawn** [eclipse/sumo#6195]
![image](https://user-images.githubusercontent.com/12990914/67497632-26db7080-f676-11e9-9c04-99591a89cc13.png)

has a number of signal types not documented, trying to use one of these additional types such as sotl, swarm or deterministic causes SUMO to crash due to missing arguments.

The wiki page for signals https://sumo.dlr.de/docs/Simulation/Traffic_Lights.html
only describes the static, actuated and delay based types.

**Comment by namdre** [comment]
Even the devs cannot easily document these algorithms due to lack of familiarity. They were provided by a third party and are no longer actively maintained. Instead of documenting them we might choose to remove them.
