### ISSUE TITLE
Lane change model details

### ISSUE THREAD

**Issue by shuowang572875852** [eclipse/sumo#6196]
I want to know how to predict the vehicle state information after lane change based on the current known vehicle state (speed, position information) . And Is there have a relevant lane change control algorithm or trajectory planning formulation? Looking forward to your reply.

**Comment by gyq18** [comment]
https://elib.dlr.de/102254/1/Springer-SUMOs_Lane_changing_model.pdf
hope this can  help you

**Comment by behrisch** [comment]
Please reopen if the paper did not answer all questions.
