### ISSUE TITLE
SUMO's  virtual simulation engine 

### ISSUE THREAD

**Issue by shuowang572875852** [eclipse/sumo#6198]
I would like to know if there is a virtual simulation engine in SUMO that can retrieve vehicle status information from the simulation results of the next several time steps.  If so, how to achieve it?

**Comment by namdre** [comment]
You could store the simulation state, run the simulation as prediction and then restore the state. 
See https://sumo.dlr.de/docs/Simulation/SaveAndLoad.html but note the limitations.

**Comment by shuowang572875852** [comment]
Is there have  corresponding TraCI commands implementation? I want to obtain vehicle status information of the next several time steps in the real-time simulation

**Comment by shuowang572875852** [comment]
Is there have  corresponding TraCI commands implementation? I want to obtain vehicle status information of the next several time steps in the real-time simulation

**Comment by namdre** [comment]
traci.simulation.saveState 
traci.load
