### ISSUE TITLE
Details of using multiple clients with TraCI are unclear, possible race conditions

### ISSUE THREAD

**Issue by FlorianDietz** [eclipse/sumo#6200]
I am accessing Sumo from multiple clients. Each of the clients can perform TraCI commands, both to get data and to set values.

The documentation here: [https://sumo.dlr.de/docs/TraCI.html#multiple_clients](https://sumo.dlr.de/docs/TraCI.html#multiple_clients) is very unclear to me, and I do not know if my current approach is safe.

How can I avoid race conditions when both clients execute commands, and how can I ensure that any subscriptions I create will retrieve data from the correct iteration when there are multiple clients at different stages?

In what order should I do these things so that everything becomes safe:
-advance the iteration
-define subscriptions
-retrieve subscriptions
-retrieve values directly
-set values directly

Please update the documentation to explain more clearly if this is always safe, is never safe, or is only safe if I adhere to certain rules.

**Comment by namdre** [comment]
fixed in [22391f4] (basically, all operations are safe).
Subscriptions are currently global, though this shall be changed in the future: #4447

**Comment by FlorianDietz** [comment]
I do not understand what you mean by subscriptions are global. Just that they always return all data for all clients, or that I have to be careful about how I retrieve from them?

**Comment by namdre** [comment]
It means that subscriptions from any one client will be received by all clients. Adding/Retrieving them is always safe.
