### ISSUE TITLE
How to draw a left turn buffer/auxiliary lane? [QUESTION]

### ISSUE THREAD

**Issue by arsenious** [eclipse/sumo#6203]
Hi

How can I draw auxilliary lanes/ buffers at intersections, where the road "fans out"? I tried connecting 3-lane segments with 4-laned one, but they always misalign and form a right-turn buffer.
Thanks

[https://www.fhwa.dot.gov/publications/research/safety/04091/images/fig120.gif](url)

from Section 12.1 https://www.fhwa.dot.gov/publications/research/safety/04091/12.cfm

**Comment by namdre** [comment]
to make this work, set custom endpoints for the edges and thereby shift them laterally as desired. See https://sumo.dlr.de/docs/NETEDIT.html.

**Comment by arsenious** [comment]
Thanks!

**Comment by alexdawn** [comment]
related to suggestions in here #5976
