### ISSUE TITLE
keep-edges.in-geo-boundary uses straight line not polylines to filter

### ISSUE THREAD

**Issue by alexdawn** [eclipse/sumo#6206]
![image](https://user-images.githubusercontent.com/12990914/67673141-47a30f00-f971-11e9-9dc9-5cc6c844d2fc.png)

Despite the two motorway links (1) being entirely outside the geo boundary (start, end and shaped middle links), they are being kept in the filter as the straight line (between start and end) (2) is intersecting the geo-boundary filter, this is also occurring in another model with a similarly C shaped link.

**Comment by palvarezlopez** [comment]
@namdre it's fixed?
