### ISSUE TITLE
Parking vehicles cannot continue their trip when traffic is too dense and congested

### ISSUE THREAD

**Issue by robertalms** [eclipse/sumo#6208]
When traffic is dense and congested, vehicles appartenly don't reenter traffic to continue their trip although the average speed is only about 5m/s their on their adjacent lane. (I stopped testing after finding parking durations of more than - 600secs.)

Even if a vehicle model does not find a safe enough gap to reenter, I guess this is not a very realistc behaviour under such conditions. Every driver would enforce their way back into such slow traffic conditions, don't you think?

**Comment by namdre** [comment]
I agree. I can think of two solutions

- junction model style:
  - let drivers accumulate impatience
  - enforce harsher braking on followers

- lane change model style
  - parking vehicles requests help
  - follower vehicle cooperates and opens a gap

**Comment by robertalms** [comment]
Yes, I thought about the junction behaviour as well. But I don't have an opinion on what would be the best solution to pursue first. Both should somehow do the trick.

In real life it would probably be a combination of both but I prefer to have a suitable solution before going into that topic ;)

**Comment by namdre** [comment]
One way to make this configurable would be to set a threshold for the minimum waitingTime of the parking vehicle.
(it collects waitingTime from the time where it's stop ends and it is unsuccessful in entering the road)

arguably this is not only a property of the ego vehicle which yields but also a property of the parking vehicle (busses will receive more courtesy than trucks)

**Comment by namdre** [comment]
Insertion of parking vehicles is a special case of the enhancement discussed in #9031 (which also comes to the conclusion that lane-change style cooperation is needed)
