### ISSUE TITLE
allow handling cyclical stops via TraCI

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#6211]
- allow passing relative routeIndex in traci.setStop (number of edges until the stop edge)
- allow passing relative stop index attribute ("end", "fit" index) in traci.setStop (number of stops before inserting the given stop)
- return relative routeIndex in TraCINextStopData

**Comment by behrisch** [comment]
The relative index seems to me the only realistic option because nobody wants to keep track about all the stops a vehicle already had.

**Comment by behrisch** [comment]
it is already largely covered by replaceStop

**Comment by namdre** [comment]
needed functionality is complete with insertStop (#10132), setStopParameter (#7981) and getStops
