### ISSUE TITLE
wiki search results in error

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#6214]
```
Unauthorized access to internal API. Please refer to https://support.google.com/customsearch/answer/4542055
```

**Comment by angelobanse** [comment]
I can't reproduce this issue. I have tried in different browsers and the search function seems to be working as expected.

Could you confirm if it is still showing?

**Comment by namdre** [comment]
It's working now. Possibly, we temporarily exceeded some treshold on the usage of our current google API key.
