### ISSUE TITLE
Lane Changing during calls to the TraCI-command MovetoXY

### ISSUE THREAD

**Issue by Domsall** [eclipse/sumo#6215]
I am trying to control an ego-vehicle in SUMO via TraCI using the built in car-following, junction and lane changing models. The ego-Vehicle is a submicroscopic model. The used setpoints then come from the SUMO models. To Control the velocity I use a built in "modified IDM" and a TraCI command, that gives me the future acceleration (one time step ahead). 
I then move the vehicle (update the position-error) accordingly to my submicroscopic model with the command MovetoXY (in every time step).
Now i would like to get the Information when the car wants to Change a lane (wantsAndCouldChangeLane), so i can trigger the submicroscopic model. But the car never changes a lane, even stops at the end of an edge, because the vehicle is on the wrong lane to follow the route. When I use the commands couldChangeLane for every lane (-1, 0, 1), the result is always 0. But there are no other objects in the simulation. LaneChangeMode is the Default and GetLaneChangeState is 1073741824 (0b 0100 0000 0000 0000 0000 0000 0000 0000) for every lane.

Is this the normal behaviour? Do I have to trigger the lane Change myself when using MoveToXY via ChangeLane? Is is possible to still let the SUMO model trigger the lane Change?

I am using the Sumo-Version 1.0.1

This is my first issue, so I hope nothing is missing.

**Comment by namdre** [comment]
This was fixed in #4545 (released in version 1.2.0).
