### ISSUE TITLE
allow location based change in vehicle behavior

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#6219]
Let vehicles of type A change their type to B when entering a specified edge in a specified time range

Implementation thoughts
- infrastructure for handling time ranges and filtering by type is already available via Rerouters and Calibrators, both could be repurposed / inherited from
- a minor change to calibrators could work:
  - when a calibrator flow defines type (other than DEFAULT_VEHTYPE), optionally speed and does not define vehsPerHour, then change the type of all vehicles that pass the calibrator
- if lots of mappings have to be defined, a new calibrator definition is needed for each one (as each calibrator has to use the vTypes attribute to define type A
- a special case coud be made if vTypes (A) references a type distribution and the flow type (B) is also a type distribution id and both distributions have the same length and probabilities. In this case a conditional mapping based on index in the distibution could be made.

**Comment by mdeamico** [comment]
Would this approach allow lane-specific vehicle behaviors? For example an edge with 3 lanes, 2 of which are general-purpose lanes and 1 is an HOV lane. The vehicles in the HOV lane may have different behavior than the general purpose lanes. However, vehicles may change in and out of lanes on the same edge, which would complicate the suggested implementation?

**Comment by namdre** [comment]
@mdeamico Yes. Calibrators can be defined as lane-specific or edge-specific. For lane-specific Calibrators, changing lanes would then trigger the type change as well.
