### ISSUE TITLE
Invalid Car-Following-Model Attribute delta. Cannot be parsed to float.

### ISSUE THREAD

**Issue by ChocolateDave** [eclipse/sumo#6220]
Hi mates! I'm new in this society. Here's a problems I faced with recently while trying to implement IDM model. As required, I'm supposed to use a normal distribution stochastic float genereated by norm(1.5554, 0.9633) for delta (the acceleration exponent). But I got an error warning:

```
Error: Invalid Car-Following-Model Attribute delta. Cannot be parsed to float
Quitting (on error).
```

Here's part of the description from rou.xml:

` <vType id="P" vClass="passenger" delta="norm(3.5238,3.6240)" carFollowModel="IDM" speedFactor="normc(1,0.1,0.2,2)"/>`

Could you mates help me out?

**Comment by namdre** [comment]
Defining parameters directly with a distribution is only support for the speedFactor parameter at this time. You can use this tool instead: https://sumo.dlr.de/docs/Tools/Misc.html#createvehtypedistributionspy
