### ISSUE TITLE
Check external links in docs for availability

### ISSUE THREAD

**Issue by schwamborn** [eclipse/sumo#6221]
When randomly checking some external links in the docs, some returned 404 and/or were outdated.

**Comment by angelobanse** [comment]
I am performing a link-check using https://github.com/tcort/markdown-link-check
```
find . -name \*.md -exec markdown-link-check {} \;
```

**Comment by behrisch** [comment]
We should add this to the nightly build

**Comment by behrisch** [comment]
OK, it is not that easy, since our build servers do not have complete internet access.
