### ISSUE TITLE
Dangling pointer occurs when debuging sumo-gui with TRACI using VS2019

### ISSUE THREAD

**Issue by Jimwaa** [eclipse/sumo#6222]
The simulation using TRACI would always be interrupted after runing a few hours, prompting that “traci.exceptions.FatalTraCIError: connection closed by SUMO”. 

To find out the reason causes the above problem, we download [the source code of sumo](https://github.com/eclipse/sumo) on October 30, 2019, and build it on Windows. 

We attach the sumo-guiD process to debug with VS2019, and a few hours later the error occurs, which is  "**Unhandled exception thrown: read access violation veh-> is 0xFFFFFFFFFFFFFEDF**" at sumo-guiD.exe!MSVehicleControl::removePending() Line 139.  The full debug stack is:
```
sumo-guiD.exe!MSVehicleControl::removePending() Line 139
	at D:\UserFiles\GitProject\sumo\src\microsim\MSVehicleControl.cpp(139)
sumo-guiD.exe!MSEdgeControl::executeMovements(__int64 t) Line 195
	at D:\UserFiles\GitProject\sumo\src\microsim\MSEdgeControl.cpp(195)
sumo-guiD.exe!MSNet::simulationStep() Line 526
	at D:\UserFiles\GitProject\sumo\src\microsim\MSNet.cpp(526)
sumo-guiD.exe!GUINet::simulationStep() 行 226
	at D:\UserFiles\GitProject\sumo\src\guisim\GUINet.cpp(226)
sumo-guiD.exe!GUIRunThread::makeStep() Line 168
	at D:\UserFiles\GitProject\sumo\src\gui\GUIRunThread.cpp(168)
sumo-guiD.exe!GUIRunThread::run() Line 135
	at D:\UserFiles\GitProject\sumo\src\gui\GUIRunThread.cpp(135)
```

The above problems will lead to sumo-gui closed and the simulation using TRACI interrupted. We haven't changed or modified the source code. Is this a bug in sumo, how to fix it ?

![sumo-gui crash](https://user-images.githubusercontent.com/56436406/68173184-1e0f6680-ffb5-11e9-854b-693144b18c2d.png)

**Comment by namdre** [comment]
This is probably a harder-to-find bug. 
- does the crash always happen at the same simulation step?
- what sumo options are you using?
- how big is your simulation (number of edges, number of vehicles, number of simulation steps before the crash occurs?)
- which traci commands are you using?

**Comment by namdre** [comment]
I'm closing this ticket due to lack of user feedback. Please re-open if necessary.
