### ISSUE TITLE
Problems making the network perfect to use ChangeTarget()

### ISSUE THREAD

**Issue by gustavo-azevedo** [eclipse/sumo#6226]
I'm trying to make all the vehicles stay on my simulation, the simulation tries to create a contamination program in which the red cars contaminate the green ones until every car is contaminated.
The problem is that eventually some car cannot change route, that happens because some parts of the map that are randomly choosen are not reachable from the current edge. So I used the netcheck tool to integrate all the map, but even after making the map connected, some edges are still not reachable. The time that is spend on correcting this is immense and sometimes i get a feeling that I'm creating more unreachable edges. Is there a way to correct those errors and be sure that you're not creating more of them or easily correcting those, something like a python script?
Here are the files used in the project:
[every_file_that_i_am_using.zip](https://github.com/eclipse/sumo/files/3816650/every_file_that_i_am_using.zip)

I'm on Ubuntu 18.04.3, SUMO 1.3.1 and using the os, sys, optparse, subprocess, random, math libraries.
Thank you in advance!

**Comment by namdre** [comment]
You can simply catch the TraCIException and issue the changeRoute command again with another target.
If a car is in a real dead-end (an edge with no successor edge) then you could still move it to another part of the network using the moveToXY function.

The latest development version offers a function in sumo-gui to highlight all the edges that are reachable from a specific spot. This could make it easier for you to indentify unreachable parts of the network. (see https://sumo.dlr.de/docs/ChangeLog.html#enhancements)
