### ISSUE TITLE
multiple junctions created in the same place when grid mode is active

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#6228]
tested with 1.3.1 and dev.
also, edges with length 0 are created
to reproduce click multiple times close (but not on) the same grid point

- all clicks should go the the same junction (at the grid point)
- no edge with length 0 should be created in edge mode

**Comment by palvarezlopez** [comment]
@namdre can you check if this solution is correct?

**Comment by namdre** [comment]
@palvarezlopez perfect!
