### ISSUE TITLE
dyld: Library not loaded

### ISSUE THREAD

**Issue by AaronLiuSy** [eclipse/sumo#6232]
Hello:
When I run the command `sumo` or  `sumo-gui`, there is an error:
  dyld: Library not loaded: /usr/local/opt/proj/lib/libproj.13.dylib
  Referenced from: /Users/aaron/sumo/bin/sumo
  Reason: image not found
  Abort trap: 6

It seems the sumo cannot find the libproj in that path, I searched online for a long time, but I did not find a proper way to solve this problem. Would you please give me some help.
Thank you

Suyue Liu

**Comment by schwamborn** [comment]
Please provide more details:
- system environment
- steps/commands you performed to install sumo
- output of those commands

**Comment by AaronLiuSy** [comment]
this is my system environment:
TERM_PROGRAM=Apple_Terminal
SHELL=/bin/bash
TERM=xterm-256color
TMPDIR=/var/folders/7f/h_92bj_d0_l5_65_4f02gp600000gn/T/
CONDA_SHLVL=2
CONDA_PROMPT_MODIFIER=(py3) 
TERM_PROGRAM_VERSION=433
TERM_SESSION_ID=3F05115D-823C-4DE4-9BF4-962200D18D8F
USER=aaron
CONDA_EXE=/Users/aaron/anaconda3/bin/conda
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.3ZtyLdxjzF/Listeners
CONDA_PREFIX_1=/Users/aaron/anaconda3
PATH=/Users/aaron/anaconda3/envs/py3/bin:/Users/aaron/anaconda3/envs/flow/bin:/Users/aaron/anaconda3/bin:/Users/aaron/sumo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/aaron/sumo_binaries/bin:/Users/aaron/sumo_binaries/bin
CONDA_PREFIX=/Users/aaron/anaconda3/envs/py3
PWD=/Users/aaron/Desktop/BristolRobotics/DriveML/starter_kit
LANG=zh_CN.UTF-8
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
SHLVL=1
HOME=/Users/aaron
SUMO_HOME=/usr/local/opt/sumo/share/sumo
CONDA_PYTHON_EXE=/Users/aaron/anaconda3/bin/python
PYTHONPATH=/Users/aaron/rllab-multiagent:/Users/aaron/rllab-multiagent:/Users/aaron/rllab-multiagent:/Users/aaron/sumo/tools:/Users/aaron/sumo/tools:
LOGNAME=aaron
CONDA_DEFAULT_ENV=py3
DISPLAY=/private/tmp/com.apple.launchd.xF696nNhQW/org.macosforge.xquartz:0
_=/usr/bin/env
OLDPWD=/Users/aaron/Desktop/BristolRobotics/DriveML

I install the sumo using clone:
 Cloning into 'sumo'...
 remote: Enumerating objects: 13152, done.
 remote: Counting objects: 100% (13152/13152), done.
 remote: Compressing objects: 100% (1833/1833), done.
 remote: Total 792070 (delta 12441), reused 11341 (delta 11319), pack-reused 778918
 Receiving objects: 100% (792070/792070), 546.06 MiB | 7.95 MiB/s, done.
 Resolving deltas: 100% (654844/654844), done.
 Checking out files: 100% (68212/68212), done.
 Submodule 'build/brew' (https://github.com/DLR-TS/homebrew-sumo) registered for path 'build/brew'
 Submodule 'tools/contributed/calibration' (https://github.com/gunnarfloetteroed/java) registered for path 
 'tools/contributed/calibration' 
 Submodule 'tools/contributed/saga' (https://github.com/lcodeca/SUMOActivityGen) registered for path 
 'tools/contributed/saga'
 Submodule 'tools/contributed/sumolib4matlab' (https://github.com/pipeacosta/sumolib4matlab) 
 registered for path 'tools/contributed/sumolib4matlab'
 Submodule 'tools/contributed/traci4matlab' (https://github.com/pipeacosta/traci4matlab) registered for 
 path 'tools/contributed/traci4matlab'
 Cloning into '/Users/aaron/Desktop/BristolRobotics/DriveML/starter_kit/sumo/build/brew'...
 remote: Enumerating objects: 54, done.        
 remote: Counting objects: 100% (54/54), done.        
 remote: Compressing objects: 100% (46/46), done.        
 remote: Total 149 (delta 27), reused 33 (delta 7), pack-reused 95        
 Receiving objects: 100% (149/149), 29.34 KiB | 9.78 MiB/s, done.
 Resolving deltas: 100% (72/72), done.
 Cloning into 
 '/Users/aaron/Desktop/BristolRobotics/DriveML/starter_kit/sumo/tools/contributed/calibration'...
 remote: Enumerating objects: 1246, done.        
 remote: Total 1246 (delta 0), reused 0 (delta 0), pack-reused 1246        
 Receiving objects: 100% (1246/1246), 540.55 KiB | 1.21 MiB/s, done.
 Resolving deltas: 100% (626/626), done.
 Cloning into '/Users/aaron/Desktop/BristolRobotics/DriveML/starter_kit/sumo/tools/contributed/saga'...
 remote: Enumerating objects: 52, done.        
 remote: Counting objects: 100% (52/52), done.        
 remote: Compressing objects: 100% (38/38), done.        
 remote: Total 366 (delta 21), reused 35 (delta 14), pack-reused 314
 Receiving objects: 100% (366/366), 24.03 MiB | 3.57 MiB/s, done.
 Resolving deltas: 100% (218/218), done.
 Cloning into '/Users/aaron/Desktop/BristolRobotics/DriveML/starter_kit/sumo/tools/contributed/sumolib4matlab'...
remote: Enumerating objects: 3, done.        
remote: Counting objects: 100% (3/3), done.        
remote: Compressing objects: 100% (3/3), done.        
remote: Total 132 (delta 1), reused 0 (delta 0), pack-reused 129        
Receiving objects: 100% (132/132), 547.43 KiB | 541.00 KiB/s, done.
Resolving deltas: 100% (44/44), done.
Cloning into '/Users/aaron/Desktop/BristolRobotics/DriveML/starter_kit/sumo/tools/contributed/traci4matlab'...
remote: Enumerating objects: 4774, done.        
remote: Total 4774 (delta 0), reused 0 (delta 0), pack-reused 4774
Receiving objects: 100% (4774/4774), 3.55 MiB | 1.06 MiB/s, done.
Resolving deltas: 100% (3066/3066), done.
Submodule path 'build/brew': checked out 'b3fd67528910b3721675faf65ccea9fb26413fce'
Submodule path 'tools/contributed/calibration': checked out 'be76e8cccfb03cbcdbd1803d507f25dea2fbd022'
Submodule path 'tools/contributed/saga': checked out 'ac4e52861c35ea6f923af9d4a4ab1dbd4f3de3f1'
Submodule path 'tools/contributed/sumolib4matlab': checked out '6bd9c1b4ddf429f82b852c1502ad0d749d2f2a89'
Submodule path 'tools/contributed/traci4matlab': checked out 'b89f4827b1239ded3e2ad2abc456c03266292446'

that all !

**Comment by schwamborn** [comment]
On macOS, please use Homebrew to install sumo:

https://sumo.dlr.de/docs/Installing/MacOS_Build.html

If you still have problems after that, please open a new issue.

**Comment by AmrARaouf** [comment]
In my case the error was:
dyld: Library not loaded: /usr/local/opt/proj/lib/libproj.15.dylib

I was able to solve the problem using the following command:

`ln -s /usr/local/opt/proj/lib/libproj.19.dylib /usr/local/opt/proj/lib/libproj.15.dylib`

since my /usr/local/opt/proj/lib/ directory only contained libproj.19.dylib file. I just linked it to the expected name.

Credits go to this answer:
https://stackoverflow.com/questions/56466395/libproj-not-loaded-while-installing-sumo-on-macos
