### ISSUE TITLE
Computing the throughput

### ISSUE THREAD

**Issue by suraty** [eclipse/sumo#6233]
Hello,

I am a beginner and I am using TraCI4matlab.
There is an intersection in sumo and I would like to count the number of vehicles that cross the intersection per second (The throughput of intersection).
How can I set the junction to count the number of vehicles that cross the intersection?

Thank you

**Comment by angelobanse** [comment]
See https://sumo.dlr.de/docs/TraCI.html#traci_commands

If you have any questions about SUMO, please post them into one of our mailing lists (especially the sumo-user list). Several people are observing it and may give you some hints. https://sumo.dlr.de/docs/Contact.html

best regards
