### ISSUE TITLE
misplaced/missing break commands in TraCIServerAPI_GUI.cpp file

### ISSUE THREAD

**Issue by vmintsis** [eclipse/sumo#6238]
In the following file: [TraCIServerAPI_GUI.cpp](https://github.com/eclipse/sumo/blob/master/src/gui/TraCIServerAPI_GUI.cpp)

The following issues have been identified:
- line 188: break command should be outside brackets
- line 229: missing  break command for case libsumo::VAR_TRACK_VEHICLE

**Comment by schwamborn** [comment]
Have you run into any bugs/errors due to this? While I agree from a syntactical point of view, semantically, this should not make any difference.

**Comment by vmintsis** [comment]
No we haven't run into any errors/bugs. Regarding line 188 it would better to place the break command outside of the brackets for consistency reasons, but in line 229 the issue can become critical since the break command is missing ([switch with default](https://en.cppreference.com/w/cpp/language/switch)).
