### ISSUE TITLE
libsumo does not do a complete simulation reset when loading another config

### ISSUE THREAD

**Issue by passengerxuhongli** [eclipse/sumo#6239]
hello sumo developers
   when i used libsumo open two simulation in loops like this:
   
   
		# import traci as libsumo
		import libsumo as libsumo
		import os
		import traci.constants as tc

		def test(sumo_cfg_file):

			sumo_home = os.environ['SUMO_HOME']
			sumo_bin = sumo_home + r'/bin/sumo'
			sumo_cmd_libsumo = [sumo_bin, '-c', sumo_cfg_file, '--step-length', '1',
								 '--no-step-log', "True"]
			libsumo.start(sumo_cmd_libsumo)

			set_subscribe()

			sim_time =0
			while sim_time <=5400:

				libsumo.simulationStep()
				sim_time += 1
			libsumo.close()
			print("simulation end!!!")

		def set_subscribe():
			inductionloop_det = libsumo.inductionloop.getIDList()
			print("inductionloop id list:\n",inductionloop_det)

			lanearea_det = libsumo.lanearea.getIDList()
			for e1det in inductionloop_det:
				libsumo.inductionloop.subscribe(e1det, (tc.LAST_STEP_VEHICLE_NUMBER,))
			for e2det in lanearea_det:
				libsumo.lanearea.subscribe(e2det, (tc.JAM_LENGTH_METERS,
														  tc.JAM_LENGTH_VEHICLE,))

		if __name__=="__main__":

			for i in range(1000):
				if i ==0:
					sumo_cfg_file_path = r"C:\Users\lixuhong\Desktop\libsumo_bug\test1\test1.sumocfg"
					print("test1.sumocfg")
				else:
					sumo_cfg_file_path = r"C:\Users\lixuhong\Desktop\libsumo_bug\test2\test2.sumocfg"
					print("test2.sumocfg")

				test(sumo_cfg_file_path)

   
   
   
   i found libsumo a error like this: test1 information occurred in test2 simulation,it make me confused!!!
   
   
		test1.sumocfg
		Loading configuration... done.
		inductionloop id list:
		 ('e1det_0_0_0', 'e1det_0_0_1', 'e1det_0_0_2', 'e1det_0_1_0', 'e1det_0_1_1', 'e1det_0_1_2', 'e1det_0_2_0', 'e1det_0_2_1', 'e1det_0_2_2', 'e1det_0_3_0', 'e1det_0_3_1', 'e1det_0_3_2', 'e1det_2_0_0', 'e1det_2_0_1', 'e1det_2_1_0', 'e1det_2_1_1', 'e1det_2_1_2', 'e1det_2_2_0', 'e1det_2_2_1', 'e1det_2_3_0', 'e1det_2_3_1')
		simulation end!!!
		test2.sumocfg
		Loading configuration... done.
		inductionloop id list:
		 ('arrival_0_1_0', 'arrival_0_1_1', 'arrival_0_1_2', 'arrival_0_2_0', 'arrival_0_2_1', 'arrival_0_2_2', 'arrival_0_3_0', 'arrival_0_3_1', 'arrival_0_3_2', 'arrival_0_4_0', 'arrival_0_4_1', 'arrival_0_4_2', 'arrival_1_1_0', 'arrival_1_1_1', 'arrival_1_1_2', 'arrival_1_2_0', 'arrival_1_2_1', 'arrival_1_2_2', 'arrival_1_3_0', 'arrival_1_3_1', 'arrival_1_3_2', 'arrival_1_4_0', 'arrival_1_4_1', 'arrival_1_4_2', 'arrival_2_1_0', 'arrival_2_1_1', 'arrival_2_1_2', 'arrival_2_2_0', 'arrival_2_2_1', 'arrival_2_2_2', 'arrival_2_3_0', 'arrival_2_3_1', 'arrival_2_3_2', 'arrival_2_4_0', 'arrival_2_4_1', 'arrival_2_4_2', 'arrival_3_1_0', 'arrival_3_1_1', 'arrival_3_1_2', 'arrival_3_2_0', 'arrival_3_2_1', 'arrival_3_2_2', 'arrival_3_3_0', 'arrival_3_3_1', 'arrival_3_3_2', 'arrival_3_4_0', 'arrival_3_4_1', 'arrival_3_4_2', 'e1det_0_1_0', 'e1det_0_1_1', 'e1det_0_1_2', 'e1det_0_2_0', 'e1det_0_2_1', 'e1det_0_2_2', 'e1det_0_3_0', 'e1det_0_3_1', 'e1det_0_3_2', 'e1det_0_4_0', 'e1det_0_4_1', 'e1det_0_4_2', 'e1det_1_1_0', 'e1det_1_1_1', 'e1det_1_1_2', 'e1det_1_2_0', 'e1det_1_2_1', 'e1det_1_2_2', 'e1det_1_3_0', 'e1det_1_3_1', 'e1det_1_3_2', 'e1det_1_4_0', 'e1det_1_4_1', 'e1det_1_4_2', 'e1det_2_1_0', 'e1det_2_1_1', 'e1det_2_1_2', 'e1det_2_2_0', 'e1det_2_2_1', 'e1det_2_2_2', 'e1det_2_3_0', 'e1det_2_3_1', 'e1det_2_3_2', 'e1det_2_4_0', 'e1det_2_4_1', 'e1det_2_4_2', 'e1det_3_1_0', 'e1det_3_1_1', 'e1det_3_1_2', 'e1det_3_2_0', 'e1det_3_2_1', 'e1det_3_2_2', 'e1det_3_3_0', 'e1det_3_3_1', 'e1det_3_3_2', 'e1det_3_4_0', 'e1det_3_4_1', 'e1det_3_4_2')
		Traceback (most recent call last):
		  File "C:/Users/lixuhong/Desktop/sumoenv_test/libsumo_bug.py", line 71, in <module>
			test(sumo_cfg_file_path)
		  File "C:/Users/lixuhong/Desktop/sumoenv_test/libsumo_bug.py", line 45, in test
			libsumo.simulationStep()
		  File "C:\Program Files (x86)\Eclipse\Sumo\tools\libsumo\libsumo.py", line 121, in simulationStep
			simulation.step(step)
		libsumo.libsumo.TraCIException: Error: Induction loop 'e1det_0_0_0' is not known

		Process finished with exit code 1
   
  
   
   but traci is not show this error.
   
   

   could you tell me why?

**Comment by passengerxuhongli** [comment]
and when i loop a same file with libsumo, computer memory growth!!!!, bu traci is not, so i doubt libsumo may memory parts of  sumo object of last loop。is that ture?

**Comment by behrisch** [comment]
This looks like a bug. Can you share your scenario?

**Comment by passengerxuhongli** [comment]
thank you for your reply. i am very glad to share this scenario。
but i am so sorry that i have no idea to send any thing from my computer to email or internet due to some privated reason。
luckly this scenario is a normal isolated intersection without any specials, so you can test this code in any sumo scenario.

**Comment by 4ndynator** [comment]
Hello I am facing the same problem and I see that the Issue is still open. My Problem is that when using libsumo for running multiple simulations sequentially through a script (similar to the given code in this issue), vehicles of the previous simulation in the Departed ID List or Arrived ID List still occur in the next simulation which makes my script not work.

Is there any fix or update for this issue?

**Comment by namdre** [comment]
can you provide a minimum reproducible example of your libsumo script and inputs?

**Comment by 4ndynator** [comment]
```python
import os
import sys

if 'SUMO_HOME' in os.environ:
    sys.path.append(
        os.path.join(os.environ['SUMO_HOME'], 'tools')
    )
else:
    sys.exit("please declare environment variable 'SUMO_HOME'")

import libsumo as traci

def run():
    print(traci.simulation.getArrivedIDList())
    print(traci.simulation.getDepartedIDList())
    while ("57" not in traci.simulation.getArrivedIDList()):
        traci.simulationStep()

def runner(sumoconfig:str):
    sumo_binary = os.path.join(os.environ['SUMO_HOME'], 'bin', 'sumo')
    sumo_command = [sumo_binary, '-c', sumoconfig]
    sumo_command.extend(["--eager-insert", "true", "--no-warnings", "--ignore-route-errors",
         "--collision.action", "none", "--no-step-log", "--step-length", "0.1"])

    traci.start(sumo_command)

    try:
        run()
    finally:
        print("Closing sumo...")
        traci.close()

if __name__ == '__main__':
    print("Starting")
    path = "YOUR_PATH_TO_SUMO_CFG_HERE"
    sumoconfig_name = "SUMO_CONFIG_NAME_HERE"

    for i in range(10):
        print("Run ", i)
        runner(f"{path}{sumoconfig_name}_{i}.sumocfg")
```

This is a minimum example for the given problem, the car with ID 57 is always present at the start of every simulation after the first one.

**Comment by 4ndynator** [comment]
[basic_example.zip](https://github.com/eclipse/sumo/files/7209784/basic_example.zip)

I have added a very simple scenario in sumo with network, route and config file you can use for this example.
