### ISSUE TITLE
speedDev can influence the flow rate largely

### ISSUE THREAD

**Issue by fengbaozhiling1** [eclipse/sumo#6241]
I want to make vehicles randomly distributed.

This is my car-following model and my vehsperHour="6000".  <vType id="CarA" maxSpeed="33" carFollowModel="IDM" sigma="0.0" accel="1.4" decel="2" tau="1.1" minGap="2" speedDev="0.0" speedFactor="1.0"/>

When I set speedDev="0.2" or other value, the flow rate will decrease largely to about 2500 veh/h.

Then, I add a parameter "sigma", but it doesn't work.

Is there easy method to make vehicles randomly distributed?

**Comment by namdre** [comment]
See https://sumo.dlr.de/docs/Simulation/Randomness.html#departure_times
https://sumo.dlr.de/docs/Simulation/Randomness.html#flows_with_a_random_number_of_vehicles
(and all the other options on this page)
