### ISSUE TITLE
od2trips (--prefix) generates invalid trip file

### ISSUE THREAD

**Issue by shuowang572875852** [eclipse/sumo#6244]
In the same area, I divided the OD matrix by vehicle type, which was divided into car_districts_OD_Matrix.mtx and trailer_districts_OD_Matrix.mtx. The routes are successfully generated by od2trips for two different OD matrices, and can be run separately.And I use  --prefix option to avoid  the ID duplication. Then I copied the generated trailer route after the car route, but the following error was reported during operation:

Error: no declaration found for element 'vType'
 In file 'C:\Users\Administrator\Desktop\Complex network\shengzhen_valid.trips.xml'
 At line/column 8/85.

Quitting (on error).

my route files as follow,the type1 is car type and the type2 is trailer :
```
<routes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/routes_file.xsd">
    <vType accel="2.6" decel="4.5" id="type1" length="5.00" maxSpeed="70.00" sigma="0.5">
	<vType accel="2.6" decel="3" id="type2" length="7.00" maxSpeed="50.00" sigma="0.5">
    <trip id="7416" depart="1.27" departLane="free" departSpeed="max" from="-229083178#0" fromTaz="taz_4" to="72241793#8" toTaz="taz_1" type="type1"/>
    <trip id="3183" depart="1.88" departLane="free" departSpeed="max" from="245962640#4" fromTaz="taz_3" to="245962640#4" toTaz="taz_3" type="type1"/>
    <trip id="280" depart="2.83" departLane="free" departSpeed="max" from="-25565505#11" fromTaz="taz_1" to="-25565505#11" toTaz="taz_3" type="type1"/>
    <trip id="3019" depart="4.33" departLane="free" departSpeed="max" from="-25565505#11" fromTaz="taz_3" to="-119460299#1" toTaz="taz_2" type="type1"/>
    <trip id="516" depart="4.77" departLane="free" departSpeed="max" from="72241793#2" fromTaz="taz_1" to="25565505#18" toTaz="taz_3" type="type1"/>
    <trip id="3876" depart="4.80" departLane="free" departSpeed="max" from="-25565505#18" fromTaz="taz_3" to="-25565505#18" toTaz="taz_3" type="type1"/>
    <trip id="9047" depart="4.89" departLane="free" departSpeed="max" from="45569111#10" fromTaz="taz_4" to="45569111#10" toTaz="taz_4" type="type1"/>

```
how can i do? or how can put car.trips.xml and trailer.trips.xml in the same simulation?

**Comment by shuowang572875852** [comment]
<routes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/routes_file.xsd">
    <vType accel="2.6" decel="4.5" id="type1" length="5.00" maxSpeed="70.00" sigma="0.5">
	<vType accel="2.6" decel="3" id="type2" length="7.00" maxSpeed="50.00" sigma="0.5">
    <trip id="7416" depart="1.27" departLane="free" departSpeed="max" from="-229083178#0" fromTaz="taz_4" to="72241793#8" toTaz="taz_1" type="type1"/>
    <trip id="3183" depart="1.88" departLane="free" departSpeed="max" from="245962640#4" fromTaz="taz_3" to="245962640#4" toTaz="taz_3" type="type1"/>
    <trip id="280" depart="2.83" departLane="free" departSpeed="max" from="-25565505#11" fromTaz="taz_1" to="-25565505#11" toTaz="taz_3" type="type1"/>
    <trip id="3019" depart="4.33" departLane="free" departSpeed="max" from="-25565505#11" fromTaz="taz_3" to="-119460299#1" toTaz="taz_2" type="type1"/>
    <trip id="516" depart="4.77" departLane="free" departSpeed="max" from="72241793#2" fromTaz="taz_1" to="25565505#18" toTaz="taz_3" type="type1"/>

**Comment by shuowang572875852** [comment]
<routes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/routes_file.xsd">
    <vType accel="2.6" decel="4.5" id="type1" length="5.00" maxSpeed="70.00" sigma="0.5">
	<vType accel="2.6" decel="3" id="type2" length="7.00" maxSpeed="50.00" sigma="0.5">
    <trip id="7416" depart="1.27" departLane="free" departSpeed="max" from="-229083178#0" fromTaz="taz_4" to="72241793#8" toTaz="taz_1" type="type1"/>
    <trip id="3183" depart="1.88" departLane="free" departSpeed="max" from="245962640#4" fromTaz="taz_3" to="245962640#4" toTaz="taz_3" type="type1"/>
    <trip id="280" depart="2.83" departLane="free" departSpeed="max" from="-25565505#11" fromTaz="taz_1" to="-25565505#11" toTaz="taz_3" type="type1"/>
    <trip id="3019" depart="4.33" departLane="free" departSpeed="max" from="-25565505#11" fromTaz="taz_3" to="-119460299#1" toTaz="taz_2" type="type1"/>
    <trip id="516" depart="4.77" departLane="free" departSpeed="max" from="72241793#2" fromTaz="taz_1" to="25565505#18" toTaz="taz_3" type="type1"/>

**Comment by shuowang572875852** [comment]
<routes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/routes_file.xsd">
    <vType accel="2.6" decel="4.5" id="type1" length="5.00" maxSpeed="70.00" sigma="0.5">
	<vType accel="2.6" decel="3" id="type2" length="7.00" maxSpeed="50.00" sigma="0.5">
    <trip id="7416" depart="1.27" departLane="free" departSpeed="max" from="-229083178#0" fromTaz="taz_4" to="72241793#8" toTaz="taz_1" type="type1"/>
    <trip id="3183" depart="1.88" departLane="free" departSpeed="max" from="245962640#4" fromTaz="taz_3" to="245962640#4" toTaz="taz_3" type="type1"/>
    <trip id="280" depart="2.83" departLane="free" departSpeed="max" from="-25565505#11" fromTaz="taz_1" to="-25565505#11" toTaz="taz_3" type="type1"/>
    <trip id="3019" depart="4.33" departLane="free" departSpeed="max" from="-25565505#11" fromTaz="taz_3" to="-119460299#1" toTaz="taz_2" type="type1"/>
    <trip id="516" depart="4.77" departLane="free" departSpeed="max" from="72241793#2" fromTaz="taz_1" to="25565505#18" toTaz="taz_3" type="type1"/>

**Comment by shuowang572875852** [comment]
<vType accel="2.6" decel="4.5" id="type1" length="5.00" maxSpeed="70.00" sigma="0.5">
	<vType accel="2.6" decel="3" id="type2" length="7.00" maxSpeed="50.00" sigma="0.5">
    <trip id="7416" depart="1.27" departLane="free" departSpeed="max" from="-229083178#0" fromTaz="taz_4" to="72241793#8" toTaz="taz_1" type="type1"/>
    <trip id="3183" depart="1.88" departLane="free" departSpeed="max" from="245962640#4" fromTaz="taz_3" to="245962640#4" toTaz="taz_3" type="type1"/>
    <trip id="280" depart="2.83" departLane="free" departSpeed="max" from="-25565505#11" fromTaz="taz_1" to="-25565505#11" toTaz="taz_3" type="type1"/>
    <trip id="3019" depart="4.33" departLane="free" departSpeed="max" from="-25565505#11" fromTaz="taz_3" to="-119460299#1" toTaz="taz_2" type="type1"/>
    <trip id="516" depart="4.77" departLane="free" departSpeed="max" from="72241793#2" fromTaz="taz_1" to="25565505#18" toTaz="taz_3" type="type1"/>
    <trip id="3876" depart="4.80" departLane="free" departSpeed="max" from="-25565505#18" fromTaz="taz_3" to="-25565505#18" toTaz="taz_3" type="type1"/>

**Comment by shuowang572875852** [comment]
<vType accel="2.6" decel="4.5" id="type1" length="5.00" maxSpeed="70.00" sigma="0.5">
	<vType accel="2.6" decel="3" id="type2" length="7.00" maxSpeed="50.00" sigma="0.5">
   
    <trip id="7416" depart="1.27" departLane="free" departSpeed="max" from="-229083178#0" fromTaz="taz_4" to="72241793#8" toTaz="taz_1" type="type1"/>
    <trip id="3183" depart="1.88" departLane="free" departSpeed="max" from="245962640#4" fromTaz="taz_3" to="245962640#4" toTaz="taz_3" type="type1"/>
    <trip id="280" depart="2.83" departLane="free" departSpeed="max" from="-25565505#11" fromTaz="taz_1" to="-25565505#11" toTaz="taz_3" type="type1"/>
    <trip id="3019" depart="4.33" departLane="free" departSpeed="max" from="-25565505#11" fromTaz="taz_3" to="-119460299#1" toTaz="taz_2" type="type1"/>
    <trip id="516" depart="4.77" departLane="free" departSpeed="max" from="72241793#2" fromTaz="taz_1" to="25565505#18" toTaz="taz_3" type="type1"/>
    <trip id="3876" depart="4.80" departLane="free" departSpeed="max" from="-25565505#18" fromTaz="taz_3" to="-25565505#18" toTaz="taz_3" type="type1"/>

**Comment by shuowang572875852** [comment]
<routes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/routes_file.xsd">
    <vType accel="2.6" decel="4.5" id="type1" length="5.00" maxSpeed="70.00" sigma="0.5">
	<vType accel="2.6" decel="3" id="type2" length="7.00" maxSpeed="50.00" sigma="0.5">
   
    <trip id="7416" depart="1.27" departLane="free" departSpeed="max" from="-229083178#0" fromTaz="taz_4" to="72241793#8" toTaz="taz_1" type="type1"/>
    <trip id="3183" depart="1.88" departLane="free" departSpeed="max" from="245962640#4" fromTaz="taz_3" to="245962640#4" toTaz="taz_3" type="type1"/>
    <trip id="280" depart="2.83" departLane="free" departSpeed="max" from="-25565505#11" fromTaz="taz_1" to="-25565505#11" toTaz="taz_3" type="type1"/>
    <trip id="3019" depart="4.33" departLane="free" departSpeed="max" from="-25565505#11" fromTaz="taz_3" to="-119460299#1" toTaz="taz_2" type="type1"/>
    <trip id="516" depart="4.77" departLane="free" departSpeed="max" from="72241793#2" fromTaz="taz_1" to="25565505#18" toTaz="taz_3" type="type1"/>
    <trip id="3876" depart="4.80" departLane="free" departSpeed="max" from="-25565505#18" fromTaz="taz_3" to="-25565505#18" toTaz="taz_3" type="type1"/>
    <trip id="9047" depart="4.89" departLane="free" departSpeed="max" from="45569111#10" fromTaz="taz_4" to="45569111#10" toTaz="taz_4" type="type1"/>
    <trip id="7417" depart="5.67" departLane="free" departSpeed="max" from="393911167#0" fromTaz="taz_4" to="72241793#4" toTaz="taz_1" type="type1"/>
    <trip id="4520" depart="6.04" departLane="free" departSpeed="max" from="-25565505#18" fromTaz="taz_3" to="-25565505#13" toTaz="taz_3" type="type1"/>
    <trip id="5962" depart="6.68" departLane="free" departSpeed="max" from="25565505#12" fromTaz="taz_3" to="25565505#12" toTaz="taz_4" type="type1"/>
    <trip id="3055" depart="7.36" departLane="free" departSpeed="max" from="-25565505#13" fromTaz="taz_3" to="633620744#12" toTaz="taz_2" type="type1"/>
    <trip id="5454" depart="7.63" departLane="free" departSpeed="max" from="-245962643#0" fromTaz="taz_3" to="-245962643#0" toTaz="taz_3" type="type1"/>
    <trip id="4130" depart="8.70" departLane="free" departSpeed="max" from="-25565505#11" fromTaz="taz_3" to="545681215#1" toTaz="taz_3" type="type1"/>
    <trip id="5739" depart="8.97" departLane="free" departSpeed="max" from="44394823#11" fromTaz="taz_3" to="25565505#18" toTaz="taz_3" type="type1"/>
    <trip id="2247" depart="10.87" departLane="free" departSpeed="max" from="223463854#1" fromTaz="taz_3" to="-72241793#3" toTaz="taz_1" type="type1"/>

**Comment by behrisch** [comment]
Your vType declaration is missing the closing slash, i should read `<vType ... />`. In principle it should work then but be aware that sumo expects its input to be sorted by time or you need to give the file as an additional file and not as a route file.
