### ISSUE TITLE
get  Traffic density

### ISSUE THREAD

**Issue by shuowang572875852** [eclipse/sumo#6245]
How to  get the hourly traffic density of an area?Can I get it directly from sumo

**Comment by behrisch** [comment]
Yes, please have a look at the output section of the docs https://sumo.dlr.de/docs/Simulation/Output.html, especially on Multi-Entry-Exit-Detectors and aggregated edge data. Also please consider asking on the mailing list, see https://sumo.dlr.de/docs/Contact.html
