### ISSUE TITLE
TraCI induction loop gives wrong occupancy values

### ISSUE THREAD

**Issue by aminissn** [eclipse/sumo#6246]
Dear SUMO developers,

The problem with the wrong occupancy values from the induction loop still persists. I have reported this almost 2 years ago, but I kind of felt this has been forgotten https://github.com/eclipse/sumo/issues/3552. 
This problem will affect  (almost) any application of E1 detectors when using TraCI. It would be great if you could revisit the issue.

Thank you for your efforts,
Sasan

**Comment by behrisch** [comment]
Yes you are right, we did not pu the attention it deserves to this topic, but please do not open new tickets, a comment on the original one suffices to trigger our notifications :-)
