### ISSUE TITLE
Jtrrouter unexpected behaviour

### ISSUE THREAD

**Issue by bond90** [eclipse/sumo#6247]
Hello,
I'm trying to generate routes from flows and turndefs using jtrrouter.
The turndefs are calculated using the python GenerateTurnDefs script, while the flows are written by hand.
For some flows, I would like the cars to follow a random pattern but passing through an edge specified in the "via" attribute, mimicking a flow to a POI, in this case an hospital, and stopping at the adjacent parking lot.
However, when calculating the routes using JTRROUTER, the software seems to ignore the attribute and still follow the probabilities in the turndefs file, thus generating spurious routes.
This is the command I'm using:
jtrrouter -n TestNet.net.xml -r TestNet.flows.xml -t TestNet.turndefs.xml --additional-files TestNet.add.xml -o TestNet.routes.xml

The input files are: 
[InputFilesForSpuriousRoutes.zip](https://github.com/eclipse/sumo/files/3839457/InputFilesForSpuriousRoutes.zip)
And the output file:
[OutputFileWithSpuriousRoutes.xml.zip](https://github.com/eclipse/sumo/files/3839460/OutputFileWithSpuriousRoutes.xml.zip)

Most of the routes generated are not passing through that edge and end at the specified ending point; seemingly, both the via and to attributes are completely ignored.

Is this expected behaviour? And, in that case, what do I have to do in order to accomplish my goal of having mixed completely random flows and flows passing by specific points?
Thank you

**Comment by namdre** [comment]
The current behavior is expected. JTRROUTER does not handle the via attribute at all. 
To get the desired behavior I would define the flows separately:
- the random ones with jtrrouter 
- the via-ones I would load direclty into the simulaton (with from,to,via) and let sumo figure out a sensible route given the current traffic situation.
