### ISSUE TITLE
Connection reset when using traci.vehicle.getNeighbors

### ISSUE THREAD

**Issue by shuowang572875852** [eclipse/sumo#6248]
I want use  traci.vehicle.getNeighbors  to get neighbor vehicle ID. It is normal when I run in simple traffic scenarios (with fewer cars), but when I run in complex traffic scenarios (with more cars), I report the following error after running for a period of time:

Error use  traci.recvExact (line 35)
Java exception occurred:
java.net.SocketException: Connection reset

	at java.net.SocketInputStream.read(SocketInputStream.java:210)

	at java.net.SocketInputStream.read(SocketInputStream.java:141)

	at java.net.SocketInputStream.read(SocketInputStream.java:224)

	at java.io.DataInputStream.readInt(DataInputStream.java:387)

I think it may be caused by the server sending too many requests to the client per second. How should I modify it?

**Comment by behrisch** [comment]
Please recheck whether there are any errors on the server side. It looks to me as if the connection got closed by sumo.

**Comment by namdre** [comment]
I'm closing this due to lack of response
