### ISSUE TITLE
"--disable-summary" option make duaIterate.py fail

### ISSUE THREAD

**Issue by ugirumurera** [eclipse/sumo#6252]
The "--disable-summary", "--disable-tripinfos" and "--clean-alt" parameters make duaIterate.py script fail. I am running SUMO-1.1.0. I am also attaching a small example that  show the issue.
[Small_Example.zip](https://github.com/eclipse/sumo/files/3848694/Small_Example.zip)

**Comment by namdre** [comment]
I tried
`sumoVersions/1.1.0/tools/assign/duaIterate.py -n net.net.xml -t pass.trips.xml -e 900 --disable-summary --disable-tripinfos --clean-alt`
and this worked fine for me.
- what command did you use?
- what is the exact error message?

**Comment by ugirumurera** [comment]
Thanks. Your command worked for me too. I was using "t" after the "--disable-summary", "--disable-tripinfos", and "--clean-alt" options to set it to "true", since this is how other SUMO options work. Maybe clarify the usage in documentation? The documentation and error message does not make this clear.

**Comment by namdre** [comment]
Thanks. I was not aware of that issue. We are using the option parsing libraries that come with python. Confusingly, python has two to choose from: optparse (which is outdated but works like the other sumo applications in this regard) and argparse (which is newer but works differently).

Note, that you can also call the  boolean sumo options without an argument to set them to 'true'.  (`sumo --no-step-log -n net.net.xml ...`)
I'm not sure how the argparse error message "Encountered argument "t" without a preceding option" could be made more clear though.
