### ISSUE TITLE
generate-documentation script takes no effect

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#6255]
After pushing a change to sumo/docs/web/docs and reloading generate-documentation.php
the script reports "All done" but the online documentation is not updated.

I recall that that this was due to permission issues.on the documentation server. Maybe @behrisch already had an idea for solving those.

**Comment by angelobanse** [comment]
It finally works!

Things to keep in mind next time:
- `http.proxy` and `https.proxy` in `git config`
- `www-data` user permissions
