### ISSUE TITLE
add buildTransitions functionality into tls mode

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#6257]
simplify definition of branching tls programs.
one new button "build transitions"
see https://github.com/eclipse/sumo/blob/master/tools/tls_buildTransitions.py
To stay within the netedit data model using phase indices in next instead of phase names

**Comment by palvarezlopez** [comment]
@namdre should we implement this in TLS Frame, or use the new "tools" interface?

**Comment by namdre** [comment]
It think the tool is obsolete. It was built to simplify building NEMA-like controllers based on tlType=actuated but since we now have a dedicated NEMA controller (which creates the transitions automatically) nobody will need this.
