### ISSUE TITLE
how can i get a new rou.xml file with calibrator? using "--vehroute-output"?

### ISSUE THREAD

**Issue by passengerxuhongli** [eclipse/sumo#6261]
i mean i have a orignal rou.xml, in order to make it close to real world, i use sumo calibrator tool.
so, my question is how can i get the route file under calibrator, because i don,t want to run sumo with calibrator additional file everytime?
untill now, i read issues "allow for vehroute-output to record calibrator-influenced routes #5826",  and have been tried "--vehroute-output" options, but i find "--vehroute-output" fuction could not record all routes( in my case just 1/3 routes was recorded) .
so, i need help to output all routes in sumo with calibrator to a new rou.xml file.

**Comment by behrisch** [comment]
The vehroute output is the way to go and works in our tests as expected. Please post your scenario together with a more precise description of what you would expect as an output.

**Comment by passengerxuhongli** [comment]
hi&nbsp;
&nbsp;yes "--vehroute-output"&nbsp; is working normal,but together with "--vehroute-output.sorted" the output become abnormal. the output lost some routes.



硕士生：李旭红
导师：倪颖副教授
交通运输工程系
同济大学交通运输工程学院
电话：13162195801


&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Michael Behrisch"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月16日(星期六) 晚上11:05
收件人:&nbsp;"eclipse/sumo"<sumo@noreply.github.com&gt;;
抄送:&nbsp;"李旭红"<836287211@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [eclipse/sumo] how can i get a new rou.xml file with calibrator? using "--vehroute-output"? (#6261)




The vehroute output is the way to go and works in our tests as expected. Please post your scenario together with a more precise description of what you would expect as an output.

**Comment by behrisch** [comment]
Can you upload your scenario somewhere? (If it is not too big just attach it to this ticket.)

**Comment by passengerxuhongli** [comment]
there is the example
https://pan.baidu.com/s/1CjuYsuzxASF3fvYCOkHqAA 
mybe you need a baidu yunban acount to download.



&nbsp;



姓名：李旭红
name：xuhong li
email：836287211@qq.com







------------------ 原始邮件 ------------------
发件人:&nbsp;"Michael Behrisch"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月17日(星期天) 晚上7:02
收件人:&nbsp;"eclipse/sumo"<sumo@noreply.github.com&gt;;
抄送:&nbsp;"李旭红"<836287211@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [eclipse/sumo] how can i get a new rou.xml file with calibrator? using "--vehroute-output"? (#6261)




Can you upload your scenario somewhere? (If it is not too big just attach it to this ticket.)

**Comment by behrisch** [comment]
@passengerxuhongli Apparently you need a chinese mobile phone to get an account. Can't you just attach the files to the ticket here (simply drag and drop it into the comment field)?
