### ISSUE TITLE
get vehicle information(vehicle ID is empty)

### ISSUE THREAD

**Issue by shuowang572875852** [eclipse/sumo#6262]
When I get the ID of the front car through getleader and retrieve the vehicle speed through the ID, it will happen that the current car has no front car, so the front car ID is empty, and the corresponding retrieval speed will report an error. Could you please set that when ID is empty, the corresponding retrieval information is also empty, instead of reporting an error

**Comment by behrisch** [comment]
No, I don't think we will implement this. Why don't you simply check whether the ID is empty before you ask for the speed?

**Comment by shuowang572875852** [comment]
Because I want to get the vehicle status information around each car in real time, some cars are not surrounded by cars, but the status information will be reported in the loop.




---Original---

**Comment by behrisch** [comment]
I am sorry, I still do not understand why you cannot filter this easily in your program.
