### ISSUE TITLE
Projection result is different from pyproj

### ISSUE THREAD

**Issue by heathcliffYang** [eclipse/sumo#6272]
Hi, 

I used `netconvert` to turn OpenStreetMap's osm file into net.xml and then took `projParameter`  as `CRS.from_proj4()`'s input in `pyproj` for coordinate transformation.

But I got different result in the following example:

The origin of my map is (120.520001, 24.128001).
According to `netOffset`, I suppose it is (247956.65, 2670317.99) after transformation.
`net.xml`:
```=html
<location netOffset="-247956.65,-2670317.99" convBoundary="0.00,0.00,19662.36,16128.38" origBoundary="120.520001,24.128001,120.710999,24.271000" projParameter="+proj=utm +zone=51 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"/>
```

In my script, I want to redo the transformation:
```=python
from pyproj import CRS, Transformer
crs = CRS.from_proj4("+proj=utm +zone=51 +ellps=WGS84 +datum=WGS84 +units=m +no_defs")
proj = Transformer.from_crs(crs.geodetic_crs, crs)
longitude = 120.520001
latitude = 24.128001
a, b = proj.transform(longitude,latitude)
```
a, b is (247953.99368484528, 2670628.882260092)

I don't know what causes this difference or I misunderstand the format of net.xml.

**Comment by namdre** [comment]
by default, netconvert shifts the output coordinates so that the lower left network corner is at 0,0
- You can prevent this by using netconvert option `--offset.disable-normalization`
- Alternatively, you can add the netOffset attribute in your location element to all values return by proj.transform.
- you can also use sumolib to do this automatically. see 
https://sumo.dlr.de/docs/Tools/Sumolib.html#coordinate_transformations
https://sumo.dlr.de/docs/Geo-Coordinates.html

**Comment by heathcliffYang** [comment]
I think the difference doesn't come from coordinate shift because the origin becomes (247956.65,2670317.99) as I add netconvert option `--offset.disable-normalization`. (shift is done after transformation)

`net.xml`:
```
<location netOffset="0.00,0.00" convBoundary="247956.65,2670317.99,267619.01,2686446.37" origBoundary="120.520001,24.128001,120.710999,24.271000" projParameter="+proj=utm +zone=51 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"/>
```

Third suggestion, I tried it in the following script:
```
import sumolib

net = sumolib.net.readNet('taichung.net.xml')

x, y = net.convertLonLat2XY(120.520001,24.128001) ## origin's coordinates

print(x,y)
```
I got the same result as `pyproj`'s (247953.99368484528, 2670628.882260092) but it is different from 'net.xml' file (247956.65,2670317.99)

Therefore, I guess maybe `pyproj` and `netconvert` use different implementation.

**Comment by namdre** [comment]
I think the difference comes from different interpretations of what the origin is (junction position vs edge shape vs lane shape).
To check whether pyproj and the netconvert/sumo projection libraries agree, test the coordinate conversion via TraCI in a network that was built with option --offset.disable-normalization: 
`traci.simulation.convertGeo(120.520001,24.128001, True)`
