### ISSUE TITLE
Use Google satellite pictures as background in Netedit and in SUMO GUI

### ISSUE THREAD

**Issue by RobertHilbrich** [eclipse/sumo#6279]
see openmobility-wg/userstories#1.

There may be similar functionality already available in SUMOpy

**Comment by palvarezlopez** [comment]
@RobertHilbrich Do you want a static image, or a interactive google maps background?

**Comment by RobertHilbrich** [comment]
If it is easier on the implementation side, then a static image is absolutely fine. It does not need to be interactive.

**Comment by behrisch** [comment]
still improvement for instance concerning projections but basic functionality is there

**Comment by wpenistone** [comment]
I cannot seem to use the TileGet function (permission denied errors), is that the intended way? how is this currently implemented?

**Comment by namdre** [comment]
if you set option **--url** you will need to set option **--key** to authenticate against the API in most case. The default URL *arcgis* should work without key.

**Comment by wpenistone** [comment]
> if you set option **--url** you will need to set option **--key** to authenticate against the API in most case. The default URL _arcgis_ should work without key.

I see, I was able to get arcgis working, I now have around 400 megabytes of tiles, but it crashes when loading the XML file; after around 2,4GB of memory usage.
