### ISSUE TITLE
import Shapefile using Polyconvert, output file is almost empty

### ISSUE THREAD

**Issue by Smiley4ever21** [eclipse/sumo#6281]
Hello,

I am trying to import the OD demand into SUMO, and for the OD boundary the shapefiles are given. To build the TAZ I noticed that I need to import polygons into SUMO, then generate TAZ.

But when I use Polyconvert to import shapefile, the output file does not have the polygons information.

My command is: polyconvert --shapefile-prefix V-Modell-Bezirke_zone  -o converted.poly.xml

In the conterted.poly.xml, the file is as follows:
```
### > <?xml version="1.0" encoding="UTF-8"?>
> 
> <!-- generated on 11/19/19 15:15:54 by SUMO polyconvert Version 0.30.0
> <?xml version="1.0" encoding="UTF-8"?>
> 
> <configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/polyconvertConfiguration.xsd">
> 
>     <input>
>         <net-file value="duisburg.net.xml"/>
>         <shapefile.fill value="V-Modell-Bezirke_zone.DBF"/>
>     </input>
> 
>     <output>
>         <output-file value="duisburg_con.poly.xml"/>
>     </output>
> 
> </configuration>
> -->
> 
> <additional xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/additional_file.xsd">
>     <location netOffset="-334875.04,-5689557.05" convBoundary="0.00,9.26,14042.77,24067.51" origBoundary="6.625585,51.333772,6.830242,51.560015" projParameter="+proj=utm +zone=32 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"/>
> 
> </additional>
```
Could you tell me the polygons in the shapefile is not imported and what can I do for that?

Thank you for your help.

**Comment by namdre** [comment]
add option
`  <shapefile-prefix value="V-Modell-Bezirke_zone"/>`

**Comment by Smiley4ever21** [comment]
Thanks for your reply.

But after I change my command to :polyconvert --shapefile-prefix value="V-Modell-Bezirke_zone  -o duisburg_con.poly.xml

it shows that Error: Could not open shape description 'value=V-Modell-Bezirke_zone  -o duisburg_con.poly.xml.shp'.
Quitting (on error).

Have I misunderstand something?
Thank you.

**Comment by namdre** [comment]
Yes.
on the commandline, use
`polyconvert --shapefile-prefix V-Modell-Bezirke_zone -o duisburg_con.poly.xml`
in the config file use
`<shapefile-prefix value="V-Modell-Bezirke_zone"/>`

**Comment by Smiley4ever21** [comment]
Could you explain a little bit more like, Where to change the config file?
I tried to change the duisburg.sumocfg and duisburg.net.xml, but I don't think the polyconvert have somthing to do with these files and the shape file do not have a configration...

**Comment by namdre** [comment]
you can call polyconvert with command line options or a config file (no need to do both).
see https://sumo.dlr.de/docs/Basics/Using_the_Command_Line_Applications.html#using_sumo_applications_from_the_command_line

**Comment by Smiley4ever21** [comment]
Thank you for your suggest, it works, but the polygons converted from the shapefile are just points, not polygons. In the output file it is just 
 <poly id="0" type="unknown" color="51,128,255" fill="1" layer="-1.00" shape="6.123573,51.857953"/>

And the original ID in Shapefile  is also lost.

How can I make the output file as polygons and is it possible to keep the original shapefile ID in the poly file?

Thank you.

**Comment by namdre** [comment]
The keep the original ID, use option `--shapefile.id-column` the specify then name of the field to use as ID.
Regarding the resulting, shapes. I cannot tell you what is wrong here. Polyconvert supports shapes defined as
- lineString
- polygon
- multiLineString
- multiPolygon

If these shapes consists of multiple points then these will also appear in the `<poly shape.../>`
