### ISSUE TITLE
[ Is it a specification?] Cars don't collide when roads are overlapped.

### ISSUE THREAD

**Issue by MokkeMeguru** [eclipse/sumo#6282]
Here is the example.
https://drive.google.com/open?id=1wa_ympzSHQ0F-24yBV5oZcWZYewvPXDl

I wonder cars will do which runs on these roads which are same position. So I change the position of the roads. (see. these line)

```xml
    <edge id="gneE4" from="gneJ0" to="gneJ6" priority="-1">
        <lane id="gneE4_0" index="0" speed="20.00" length="500.00" shape="0.00,4.80 500.00,4.80"/> // Here! -4.8.0 => 4.80
        <lane id="gneE4_1" index="1" speed="20.00" length="500.00" shape="0.00,1.60 500.00,1.60"/> // Here! -1.60 => 1.60
    </edge>
```

I found these cars are not collide. 

I have two questions.

- This phenomenon is correct specification? or bug?
- I have another question. Is it possible to implement reverse running that causes a collision in Sumo?

**Comment by namdre** [comment]
1) The simulation behavior is correct. Vehicles on different roads do not interact with each other regardless of geometry. The only exceptions to that is the interior space of intersections.
2) Yes. See https://sumo.dlr.de/docs/Simulation/OppositeDirectionDriving.html  Also, you can remote-control a vehicle via the TraCI API (setting position and angle). This also allows you to drive in the wrong direction.

**Comment by MokkeMeguru** [comment]
Thanks a lot!
