### ISSUE TITLE
cmd commands 

### ISSUE THREAD

**Issue by BuddhaZhang** [eclipse/sumo#6285]
Could you help me?
The version number of the sumo I am using is 0.32.0, then when I run the “netcovert --osm-files shangrao_china.osm -o shangrao.net.xml “ code in cmd, I get the error 
“Error： unable to open file 'https://sumo.dlr.de/xsd/types_file.xsd'     
   In file 'built in type map'         
   At line/column 1/0

    The types could not be loaded from 'built in type map'.”

**Comment by namdre** [comment]
see https://sumo.dlr.de/docs/FAQ.html#whats_the_deal_with_schema_resolution_warnings_xsd_errors
Please post future questions to the sumo-user mailing list: https://sumo.dlr.de/userdoc/Contact.html

**Comment by BuddhaZhang** [comment]
Sorry, I followed the prompt to create an account and it failed, but I don't know what went wrong. And I have a new difficulty, the version of sumo is 0.32.0, when I run the ''netconvert --osm-files map.osm -o map.net.xml' command, it will get the error "unable to open primary Document entity 'D:\sumo-0.32.0' In file 'D:\sumo-0.32.0'
At line/column 1/0", what should I do?

**Comment by namdre** [comment]
report the result of calling
`netconvert --osm-files map.osm -o map.net.xml --xml-validation never`

**Comment by BuddhaZhang** [comment]
The result is the same as before.
Error: unable to open primary document entity 'D:\sumo-0.32.0'
In file 'D:\sumo-0.32.1'
At line/column 1/0.

Error: Could not open types-file '/data/typemap/osmNetconvert.typ.xml.

**Comment by namdre** [comment]
@behrisch got an idea?

**Comment by BuddhaZhang** [comment]
When I delete the environment variable SUMO_HOME and then run the command you just gave, it will generate a lot of warnings, but it runs successfully.

**Comment by behrisch** [comment]
What exactly is the value of SUMO_HOME?

**Comment by BuddhaZhang** [comment]
It's 'D:\sumo-0.32.1'.

**Comment by BuddhaZhang** [comment]
‘bin’ parent directory

**Comment by behrisch** [comment]
No, I'm sorry, I have no idea why this happens. Can you recheck whether it also happens with the most recent sumo?

**Comment by BuddhaZhang** [comment]
When I use the sumo-1.3.1 version to run the command "netconvert --osm-files map.osm -o map.net.xml", in win7, it prompts that netconvert has stopped working. In win10, there is no prompt, No success.

**Comment by behrisch** [comment]
Can you provide your input file?

**Comment by BuddhaZhang** [comment]
This is my input file.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Michael Behrisch"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月5日(星期四) 凌晨1:04
收件人:&nbsp;"eclipse/sumo"<sumo@noreply.github.com&gt;;
抄送:&nbsp;"一生迁就与疼爱"<2573328502@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [eclipse/sumo] cmd commands  (#6285)




Can you provide your input file?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

map.osm (9.96M, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=05313139b8cd039e4fd150a04462514e0f53025d5b5b015814015558004f570501551c010350524c0a08505b010154020f5755096265630c58411f56110f635c&t=exs_ftn_download&code=9119bbca

**Comment by BuddhaZhang** [comment]
And I want to ask you other questions.
The first is that I want to set a certain point on the road as the end point of the person
<person id = "p_0" depart = '35 .00 'guiShape = "pedestrian" departPos = '67 .4'>
<walk edges = "540918325 # 0 540918323 28623899 # 9 -28623889 # 1 137133120 # 2" arrivalPos = "15.0" />
</ person>
But every time I run, the person disappears in the middle and back part of the last side, and the end point is not the position I set.
The second is that I want the car to run for a while and then stop at a certain point for a while and then start again
traci.vehicle.setStop ("0", "137133120 # 2", 15.0, 0), this is my code. After I set it, the car will stop at that location, but it can no longer be started.
Hope you can give suggestions, thanks.

**Comment by BuddhaZhang** [comment]
And I want to ask you other questions.
The first is that I want to set a certain point on the road as the end point of the person.
<person id = "p_0" depart = '35 .00 'guiShape = "pedestrian" departPos = '67 .4'>
       walk edges = "540918325 # 0 540918323 28623899 # 9 -28623889 # 1" arrivalPos = "15.0" />
</ person>
But every time I run, the person disappears in the middle and back part of the last side, and the end point is not the position I set.
The second is that I want the car to run for a while and then stop at a certain point for a while and then start again.
traci.vehicle.setStop ("0", "137133120 # 2", 15.0, 0), this is my code. After I set it, the car will stop at that location, but it can no longer be started.
Hope you can give suggestions, thanks.

**Comment by BuddhaZhang** [comment]
I want to ask you another question.

I want the car to stop for a while after starting and then restart
traci.vehicle.setStop ("0", "137133120 # 2", 15.0, 0, 60), this is my code. Once set, the car will stop at this position but will not restart.
Hope you can make suggestions, thank you.

**Comment by behrisch** [comment]
I am sorry, I cannot reproduce it. It works fine here on Windows 10 with sumo 1.3.1, 1.4.0, and the current HEAD of master.

**Comment by BuddhaZhang** [comment]
Thank you, this problem does not affect my experiment, I can get the net.xml file through the lower version of sumo.
