### ISSUE TITLE
Poly file from version 0.30 can not open in version 1.3.1

### ISSUE THREAD

**Issue by Smiley4ever21** [eclipse/sumo#6286]
Hello,
For using TAZ I download the new version 1.3.1 of SUMO, the net file can opened in the new version, but the poly file cannot be opened. 

Warning: Format of essential list of unique positions attribute 'shape' of poly with ID '5512002' is invalid; List of Positions aren't neither x,y nor x,y,z; poly cannot be created
Error: Loading of C:\Users\sjxxmaaa\Desktop\sumo-1.3.1\bin\duisburg.polyneu.xml failed.

The positions of polygons are already in x,y and can be opend in the old version.
How can I change about it to use it in SUMO 1.3.1?

Thank you.

**Comment by palvarezlopez** [comment]
@Smiley4ever21 Can you attach the TAZ file?

**Comment by Smiley4ever21** [comment]
I've found out. 
SUMO 1.3.1 only takes the polygon file without "type" description, after deleting type, it can be shown.
Anyway, thank you.

**Comment by namdre** [comment]
what exactly do you mean by "type" description. The type attributes of polygons should be supported. Please post an example polygon definition that cannot be loaded.  I want to make sure this isn't a bug.

**Comment by Smiley4ever21** [comment]
Yes, you are right, that is nothing to do with the type description, the reason is that my poly file has a extra space in the end. Like:
<poly id="1" color="1,0,0" fill="1" layer="1.00" shape="61.2514,22.8887  61.2514,22159.2487 "/>
The right descrption should be without this space like:
<poly id="1" color="1,0,0" fill="1" layer="1.00" shape="61.2514,22.8887  61.2514,22159.2487"/>
This extra space can be ignored in old version 0.30, but in new version 1.3.1 it can not be read.
