### ISSUE TITLE
Issue with distributing trips uniformly over time

### ISSUE THREAD

**Issue by Rayaprolus** [eclipse/sumo#6289]
Hi! I used od2trips to generate vehicle trips among 26 TAZs (13 for inflow and 13 for outflow). The simulation is expected to generate 6000 vehicles in 3.5 hrs. (12600 timesteps). When I generated trips, they were distributed from 0 to 3600 instead of 12600. Why? Here's my command:

"od2trips -c Updated_od2trips_proj.config.xml -n Updated_TAZ_proj.taz.xml -d Updated_OD_proj.od -o Updated_od_proj.odtrips.xml --begin 0 --end 12600 --spread.uniform true -H true"
![image](https://user-images.githubusercontent.com/46505218/69270221-873fce00-0ba0-11ea-97c3-f37177786c27.png)

All I want is to spread out vehicle departures uniformly from 0 to 12600 sim steps.
I'd really appreciate your help.

**Comment by namdre** [comment]
please post the first 10 lines of your od matrix file

**Comment by Rayaprolus** [comment]
Here is the .od file:
![image](https://user-images.githubusercontent.com/46505218/69344291-27e3cb80-0c3d-11ea-93e8-9df8584e48d6.png)

Here is TAZ file:
![image](https://user-images.githubusercontent.com/46505218/69344436-5d88b480-0c3d-11ea-8494-43b42452db8b.png)
In case you're not looking for a screenshot:

$O;D2
* From-Time To-Time
0.00 1.00
* Factor
1.00
*
* some
* additional
* comments
		 1 16 63
		 1 17 35
		 1 18 43
		 1 19 7
		 1 20 2
		 1 21 52
		 1 22 1
		 1 23 7
		 1 24 21
		 1 25 28
		 1 26 70
		 2 14 67
		 2 16 107
		 2 17 64

**Comment by namdre** [comment]
Change the the From-Time, To-Time values in the matrix to
0 3.5

**Comment by Rayaprolus** [comment]
Oh! I will. What does that mean? I'm a beginner.

**Comment by Rayaprolus** [comment]
> 
> 
> Oh! I will. What does that mean? I'm a beginner.



> 
> 
> Change the the From-Time, To-Time values in the matrix to
> 0 3.5

It did not work.

**Comment by Rayaprolus** [comment]
Thanks, that's great! It worked
