### ISSUE TITLE
od2trips bug begin time is lager than end time

### ISSUE THREAD

**Issue by Smiley4ever21** [eclipse/sumo#6294]
Hello,

In od2trips funtion, I have a command of:
od2trips --taz-files duisburgroad.taz.xml  -d Pkw-G.mtx -o duisburg.trips.xml 

but faild because of 
Error: Begin time is larger than end time.
Quitting (on error).

So I try to change the begin time and end time to default, I change my command to
od2trips --taz-files duisburgroad.taz.xml  -d Pkw-G.mtx -o duisburg.trips.xml --vtype Pkw  -b 0  -e 9223372036854774

Thee error is the same.
Is this a bug of od2trips or I've done something wrong?
Thank you for your reply.

**Comment by namdre** [comment]
That error message refers to the begin and end time define in the od matrix file (I've improved the error message in [7124b40d3507663543c85171a2fb4ffdf00656d0]

**Comment by Smiley4ever21** [comment]
Thank your for your help.
What can I do about it? Should I adjust the begin time in OD matrix or I could change the end time in SUMO?

**Comment by Smiley4ever21** [comment]
I have changed the od matrix. Everyting's fine now. Thank you.
