### ISSUE TITLE
vehroute-output should reproduce symbolic departSpeed value

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#6296]
when loading vehicles with `departSpeed="max"` the resulting vehroute-output will often cause warnings when used as input because the individual speedFactor may be lower when running again.

**Comment by namdre** [comment]
alternatively, the individual speedFactor would have to be recorded and re-used

@behrisch: any thoughts on making speedFactor a numerical vehicle parameter that overrides vType default?

**Comment by behrisch** [comment]
I agree, making the speedFactor an optional vehicle attribute would allow for best reproducibility.
