### ISSUE TITLE
SubLanemodel(Vehicle overlap)

### ISSUE THREAD

**Issue by shuowang572875852** [eclipse/sumo#6305]
Overlap of vehicle position occurs when sublane model is enabled, or the distance between vehicles is too close . Is there any option to make adjustments?

**Comment by namdre** [comment]
Visual overlap may result when you override edge lengths (i.e. define an edge with geometry length of 50m and then declare it's length to be 100m). 
Actual overlap over vehicles in the simulation results in a collision.

**Comment by behrisch** [comment]
@shuowang572875852 If this answer did not help, please reopen with more information,
