### ISSUE TITLE
Mutual lane change blocking

### ISSUE THREAD

**Issue by alexdawn** [eclipse/sumo#6306]
This seems to be a paricular issue for roundabouts, but equally for any highly congested junction where vehicles are in the wrongly lane.

![image](https://user-images.githubusercontent.com/12990914/69424537-ce54cd00-0d20-11ea-893e-8cf430e8d48a.png)
this example is less serious as the outer lane is still moving, but the blue HGV remains blocked, despite having priority being to the right of the left most lane.

however the below example each vehicle is mutually blocking each other:
![image](https://user-images.githubusercontent.com/12990914/69424623-00662f00-0d21-11ea-9eb2-45a29c84ce08.png)

Is there config to prevent the these relatively common mutual blocking resulting in a permanent jam? (Either one or the other vehicle should yield priority, or teleport)

**Comment by namdre** [comment]
You can apply the connection layout described for motorway weaving: https://sumo.dlr.de/docs/Simulation/Motorways.html#combined_on-off-ramps
