### ISSUE TITLE
add updated Hello Sumo Tutorial that uses Netedit

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#6317]
like https://github.com/eclipse/sumo/blob/master/docs/web/docs/Tutorials/Hello_Sumo.md but using netedit to create the network and demand.

**Comment by angelobanse** [comment]
Should it be a brand new (different) tutorial or should it be the same one but modified for example with a new section called "using Netedit", and leaving the current content under a section called "using the text editor"?

**Comment by namdre** [comment]
I would prefer to have a completely new tutorial with a link to the old version

**Comment by angelobanse** [comment]
And this new tutorial should be at the 'Beginner Tutorials' section?

**Comment by namdre** [comment]
yes (see #6316 for reasoning)

**Comment by namdre** [comment]
I like this very much. Especially the animated gifs.
