### ISSUE TITLE
Crash in functions PositionVector::positionAtOffset()/positionAtOffset2D()

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#6328]
Current implementation doesn't support shapes with size() = 1

**Comment by namdre** [comment]
@palvarezlopez  The functions that you changed are used in many different places. Some may have relied on the old behavior. I'm seeing failures in netconvert and sumo tests after these changes. There may also be regressions in sumo-gui that cannot be caught by our automated tests.
Frankly, I'm  dismayed for having  to review this kind of change so shortly before a release.

It's made worse by the fact that you mixed refactoring and behavior changes in a non-obvious way.

- Please revert the changes
- Please separate them into reasonably sized commits that separate the different aspects which were changed (refactoring, etc.)
- Please take a careful look at all application tests before you commit a change to a widely used core library function.

I think it would be better to delay some or all of this changeset until after the release (and mitigate the crash in a less invasive way).

Please note that I'm not saying the changes are bad. It's just that I'm not confident to release them at short notice.

**Comment by palvarezlopez** [comment]
Solution implemented in https://github.com/eclipse/sumo/commit/952e03109af0cacf9da84c54e28b9d8568fda2cf fix the problem
