### ISSUE TITLE
DriverState device only affects carFollowModel Krauss

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#6330]
@schwamborn I think this impacts on TransAID

**Comment by schwamborn** [comment]
@namdre Thanks for the heads up! All configs I checked use Krauss as manualType, so our results shouldn't be affected by this. Nevertheless, also pinging @yunpangfloetteroed @robertalms

**Comment by robertalms** [comment]
@schwamborn What about about the ACC/CACC models we use in TransAID?

**Comment by namdre** [comment]
They are not supposed to suffer from the human imperfections that the driverstate device models.

**Comment by robertalms** [comment]
Ah, correct. Then our results should be fine.

**Comment by robertalms** [comment]
As I understand it, the 'applyDriverState' is deactivated by default. So that means, that the addition shouldn't affect the ACC/CACC model behavior or the TransAID results at all. I guess, this issue could be closed then.

**Comment by namdre** [comment]
agreed.
