### ISSUE TITLE
Error: Edge's from-node and to-node are identical.

### ISSUE THREAD

**Issue by ambuehll** [eclipse/sumo#6333]
if I run:
`netconvert -c osm.netccfg
`
with 
[osm.netccfg
](https://drive.google.com/file/d/1p7H7iWonK1cGzEsYOLpGi8kSYmsMuGPx/view?usp=sharing) and 
[planet file
](https://drive.google.com/file/d/1R17ndox2EQRou17NZdY8FzviIfhNA0LN/view?usp=sharing)
and run then:
`netconvert -s osm.net.xml
`
I get: 
```
Error: Edge's '265841710#2' from-node and to-node '2714576574' are identical.
Error: Edge's '265841713#2' from-node and to-node '2714589164' are identical.
Quitting (on error).
```

-> the reason is the (new) setting 	<geometry.remove.min-length value="5"/>

v1_3_1+1127-470e1b529c

**Comment by namdre** [comment]
you scared me at first with the input file name 'planet.osm' ^^
