### ISSUE TITLE
tripinfo-output.write-unfinished option not working when using TraCi

### ISSUE THREAD

**Issue by citronek842** [eclipse/sumo#6348]
When I use the tripinfo-output.write-unfinished option in TraCi and I use sumo-gui it is working just fine, all vehicles are listed in the output file, but when I use only sumo there are listed only vehicles which arrived to their destination.

**Comment by namdre** [comment]
I cannot reproduce this in my own test. Please provide example files for reproducing the issue.

**Comment by namdre** [comment]
closing due to lack of feedback.
