### ISSUE TITLE
broken build after refactoring

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#6360]
cmake may get stuck with outdated dependecies. To remedy, the cmake cache must be cleared manually and reconfigured (in particular on our windows test servers)

**Comment by palvarezlopez** [comment]
@namdre In Visual Studio 2019 works as expected

**Comment by namdre** [comment]
on my ubuntu box I had to remove the cmake directory. Even deleting CMakeCache.txt was insufficient.

**Comment by behrisch** [comment]
The build servers always delete the complete build dir before starting cmake, so they probably won't notice but I wait until tomorrow.
