### ISSUE TITLE
refactor usage of sumolib.writeXMLHeader

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#6367]
argument 'script' is no longer used and can be removed from all calling scripts

**Comment by JCodyA** [comment]
Hello!  This might be a good one for me but I'll need some guidance on it (I'm pretty new to this still).  I was exploring the code a little with ```git grep -i -n sumolib.writeXmlHeader``` and see lots of cases where its being called but I'm not sure where to go from here.  I'm not seeing the script argument, and I haven't figured out where writeXMLHeader is actually defined.

**Comment by behrisch** [comment]
Hi, yes this might have been a good starter. Unfortunately the code changed in f3e1ed5c6af and now allows again to modify the script name and albeit not used very much, I think it is good idea to have this flexibility. For the record: sumolib.writeXMLHeader is an alias for sumolib.xml.writeHeader.
