### ISSUE TITLE
geometry-remove should consider street names (trac #637)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#637]
this option turns junctions into geometry nodes if this is deemed possible. If output of street names is enabled, the option geometry-remove should not cause the loss of street names.

Migrated from http://sumo.dlr.de/ticket/637
```json
{
    "status": "new", 
    "changetime": "2013-05-26T19:06:59Z", 
    "description": "this option turns junctions into geometry nodes if this is deemed possible. If output of street names is enabled, the option geometry-remove should not cause the loss of street names.", 
    "reporter": "namdre", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1369595219000000", 
    "component": "net building (NETGEN, NETCONVERT)", 
    "summary": "geometry-remove should consider street names", 
    "priority": "minor", 
    "keywords": "", 
    "time": "2012-01-06T15:22:10Z", 
    "milestone": "1.0.0", 
    "owner": "namdre", 
    "type": "defect"
}
```

**Comment by behrisch** [comment]
probably needs to be added as a reason to NBEdge::expandableBy

**Comment by lbieker** [comment]
In the test network the streetnames were kept after geometry-remove. I guess this issue was already fixed somehow.

**Comment by behrisch** [comment]
Could you please also test the case of two edges with the same name getting joined? The name should be kept then.

**Comment by namdre** [comment]
The bug is this: roads with different street names should not be joined because then a streetname is lost.
The original test network did not exhibit the bug because a traffic light prevented the edges from being joined. After removing the traffic light edges are now wrongly joined and the test fails.
