### ISSUE TITLE
how can i stop the car smoothly at junction?

### ISSUE THREAD

**Issue by allenlai38** [eclipse/sumo#6379]
I use TraCI to set the speed mode of the car that is 31,  it means the car will braked hardly when approaching the junction. However, when the car is braking, the deleration is high. 

I use TraCI to get the speed of the car and it shows that the value is always zero when the car is braking.

Could you please suggest me how to configure the setting of the car or the junction parameters to stop the car smoothly at junction? 

I run in sumo-gui and it throw the warning like this.

> Loading configuration... done.
***Starting server on port 49696 ***
Loading net-file from 'data/urban.net.xml'... done (3ms).
Loading additional-files from 'data/urban.det.xml'... done (3ms).
Loading done.
Simulation started with time: 0.00
Warning: Vehicle 'bugatti-veyron' performs emergency stop at the end of lane 'edge_1_2_2' because of a red traffic light (decel=-69.27, offset=0.52), time=12.35.
Warning: Vehicle 'bugatti-veyron' performs emergency stop at the end of lane 'edge_1_2_2' because of a red traffic light (decel=0.23, offset=0.00), time=12.36.
Warning: Vehicle 'bugatti-veyron' performs emergency stop at the end of lane 'edge_1_2_2' because of a red traffic light (decel=0.23, offset=0.00), time=12.37.
Warning: Vehicle 'bugatti-veyron' performs emergency stop at the end of lane 'edge_1_2_2' because of a red traffic light (decel=0.23, offset=0.00), time=12.38.
Warning: Vehicle 'bugatti-veyron' performs emergency stop at the end of lane 'edge_1_2_2' because of a red traffic light (decel=0.23, offset=0.00), time=12.39.
Warning: Vehicle 'bugatti-veyron' performs emergency stop at the end of lane 'edge_1_2_2' because of a red traffic light (decel=0.23, offset=0.00), time=12.40.
Warning: Vehicle 'bugatti-veyron' performs emergency stop at the end of lane 'edge_1_2_2' because of a red traffic light (decel=0.23, offset=0.00), time=12.41.
Warning: Vehicle 'bugatti-veyron' performs emergency stop at the end of lane 'edge_1_2_2' because of a red traffic light (decel=0.23, offset=0.00), time=12.42.
Warning: Vehicle 'bugatti-veyron' performs emergency stop at the end of lane 'edge_1_2_2' because of a red traffic light (decel=0.23, offset=0.00), time=12.43.
Warning: Vehicle 'bugatti-veyron' performs emergency stop at the end of lane 'edge_1_2_2' because of a red traffic light (decel=0.23, offset=0.00), time=12.44.

**Comment by namdre** [comment]
From the warning output it looks as if the car is going 250km/h (sumo speeds are in m/s) and you set the speed mode when it is already is very close to the intersection. If you lower the speed or set the speed mode earlier, the car should have enough time to brake smoothly.
