### ISSUE TITLE
netedit and sumo-gui accept different additional files formats

### ISSUE THREAD

**Issue by yunpangfloetteroed** [eclipse/sumo#6381]
sumo-gui can open additonal files with ids containing ':', e.g. id="t4:01" But netedit cannot. netedit can accept ids containing "_". It would be reasonable that sumo-gui and netedit are consistant regarding file format.

**Comment by namdre** [comment]
I think ':' should be acceptable. @behrisch do you recall the reason for forbidding it?

**Comment by namdre** [comment]
I'd like to lift unnecessary restrictions for the upcoming release

**Comment by behrisch** [comment]
Are we talking about polygons here or which elements are parsed?
