### ISSUE TITLE
unable to open website

### ISSUE THREAD

**Issue by Smiley4ever21** [eclipse/sumo#6388]
Hallo,

in using python duaIterate.py, a error comes out. 

Warning: Cannot read local schema 'C:\Users\sjxxmaaa\Desktop\sumo-1.3.1\bin/data/xsd/routes_file.xsd', will try website lookup.
Error: unable to open file 'https://sumo.dlr.de/xsd/routes_file.xsd'
 In file 'duisburg_all_000.rou.xml'
 At line/column 1/0.

Quitting (on error).

How can I skip this step of connecting the website, or how can I let it connect the website?
Thank you for your help.

**Comment by namdre** [comment]
see https://sumo.dlr.de/docs/FAQ.html#whats_the_deal_with_schema_resolution_warnings_xsd_errors

**Comment by Smiley4ever21** [comment]
Thank you for your quick reply.
For python command, the " --xml-validation never " does not work, and because it is a iteration, just remove the website in input file is useless, because it will generate new route file with the website as new input file.

In the introduction webite you metioned, only these two solution for disabling schema validation is given. Do you have any other solution for this? Thank you.

**Comment by Smiley4ever21** [comment]
the "--xml-validation never" command is invalid in duaIterate.py.
[duaIterate.py: error: unrecognized arguments: --xml-validation]

Is there a command for disabling schema validation can be used in duaIterate.py?
Thank you.

**Comment by namdre** [comment]
it looks like you misdefined SUMO_HOME to point to C:\Users\sjxxmaaa\Desktop\sumo-1.3.1\bin/
and for this reason the local schema files are not found.
Set `SUMO_HOME=C:\Users\sjxxmaaa\Desktop\sumo-1.3.1` instead

**Comment by Smiley4ever21** [comment]
It is exactly this problem!
Thanks a lot!
Have a nice day! 👍
