### ISSUE TITLE
Draw Junctions without connections using special color

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#6391]
currently, there is no way to distinguish disconnected junctions from geometry-like nodes and this can cause a lot of trouble when debugging connectivity

**Comment by namdre** [comment]
- in netedit, junctions without shape (or small shape) are drawn as bubble. in this case it makes sense to use the junction color
- in sumo-gui, small junctions may not be visible. Therefore it is more useful to use another link-rule color
   - whenever an edge has no connections and the toJunction has outgoing edges.
