### ISSUE TITLE
sumo-gui - No save configuration option? 

### ISSUE THREAD

**Issue by airqualityanthony** [eclipse/sumo#6392]
As the title says, I've followed the tutorial found here: https://sumo.dlr.de/docs/Tutorials/Hello_World.html

But when I open in sumo-gui both the vehicle demand model doesn't seem to load vehicle and also there is no save configuration option in File?

**Comment by angelobanse** [comment]
Hi @airqualityanthony, are you using SUMO 1.4.0?

**Comment by angelobanse** [comment]
the option to ***Save Configuration*** (Ctrl + Shift + S) was introduced in SUMO-GUI version 1.4.0. Please download and use that version -> https://sumo.dlr.de/docs/Downloads.html

**Comment by airqualityanthony** [comment]
This is on 1.3.1 from the Windows ZIP (local admin restrictions require use of this). I've just noticed the 1.4.0 release. Will try now.

**Comment by airqualityanthony** [comment]
Both issues resolved in 1.4.0 - save configuration there, and also demand model loads into SUMO-GUI correctly. 

Many thanks
