### ISSUE TITLE
fcd-output distance

### ISSUE THREAD

**Issue by ambuehll** [eclipse/sumo#6396]
It seems that the distance output is always by lane. never the actual total distance traveled (sum over all edges). I would be interested in getting the total distance traveled, not only per lane. (I know, I can sum them up, it's just a matter of usability)

**Comment by namdre** [comment]
The fcd distance output is for linear referencing. It works with the distance attribute of the edge.
See https://sumo.dlr.de/docs/Simulation/Railways.html#kilometrage_mileage_chainage
If the vehicle travels in a city network, this scheme is generally not applicable to computing travelled distance.
