### ISSUE TITLE
Vehicles brake for no reasons using SL2015 lane-changing model

### ISSUE THREAD

**Issue by ChocolateDave** [eclipse/sumo#6405]
Hi fellas! Recently I've been working on an intersection simulation while using the IDM model as car-following model, and the SL2015 for lane-changing model. Here's a problem I came up with.

![image](https://user-images.githubusercontent.com/45930715/70691127-4cd6d600-1cf3-11ea-9154-57dfffcccfd3.png)

As shown in the graph above, there was clearly enough space ahead of the left-turning vehicle. The vehicle, however, chose to brake for no obvious reasons and caused a conflict. The traffic brokedown.

What was the problem here? Could you help me out?

**Comment by ChocolateDave** [comment]
BTW here's the parameters of the leading car that chose to brake.

![image](https://user-images.githubusercontent.com/45930715/70691709-b3102880-1cf4-11ea-9ec9-fe50e6229d59.png)

**Comment by namdre** [comment]
Possibly invalid intersection right of way rules. This can happen if the right of way rules were determined with reference to a particular signal plan and you are loading a different signal plan during the simulation. 
You could try rebuilding your network and loading alternative signal plans into netconvert using option --tllogic-files
If that doesn't fix the problem, upload a minimal failing scenario.

**Comment by ChocolateDave** [comment]
> Possibly invalid intersection right of way rules. This can happen if the right of way rules were determined with reference to a particular signal plan and you are loading a different signal plan during the simulation.
> You could try rebuilding your network and loading alternative signal plans into netconvert using option --tllogic-files
> If that doesn't fix the problem, upload a minimal failing scenario.

Thank you, sir! I've tried rebuilding my network and it worked.🙂
