### ISSUE TITLE
indicate freshness of nightly-build on the download page

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#6440]
it should be possible to pull the compile time and git description when calling mkdocs.
We do get hickups occasionally and it would be nice if people could check this without downloading.

**Comment by angelobanse** [comment]
it is enough to use the **LastModified** date of each file in the server?

e.g. :arrow_down:
![nightly](https://user-images.githubusercontent.com/16121932/71890292-3c741880-3144-11ea-9c00-6766ffe3cfd1.png)

**P.S.** The **_sumo-game-win32-git.zip_** file is mentioned in the download list, but it does not exist on the server.

**Comment by namdre** [comment]
This is certainly a big improvement for determining freshness.
Something like  v1_4_0+0118-fc0e3c59b8e would be nice to have, though.

**Comment by angelobanse** [comment]
We now show the *LastModified* date of each nightly build file.

To have the version such as **v1_4_0 + 0397-af7b55f2bb** it is required that the file `version.h` be included within all nightly build packages.

**Comment by namdre** [comment]
as far as I recall the discussion with @behrisch this was our plan anyway.
