### ISSUE TITLE
IDM car-following model maybe has a question 

### ISSUE THREAD

**Issue by lishuaimarshall** [eclipse/sumo#6449]
When using the IDM model,The distance between the car in front and the car behind is only 3 meters in this simulation.
but I seted the  length="5", minGap="2" .
     <vType id="HDV" carFollowModel="IDM" color="0,1,0" length="5" maxSpeed="33.3" accel="2.0" decel="4.0" tau="1.6"  delta="4"  stepping="1" minGap="2" emergencyDecel="5"/>

I added the vehicles by using this codes in python file
    traci.vehicle.add("1", "route1", typeID="HDV", depart="0", departPos="450", departSpeed="20")
    traci.vehicle.add("2", "route1", typeID="HDV", depart="0", departPos="300", departSpeed="20")

and the simulation scenario is  a straight road ,codes:
        <lane id="gneE0_0" index="0" speed="33" length="200000.00" shape="0.00,-1.60 20000.00,-1.60"/>

so I do not know how to deal with this question.please hlep me!
The CACC MODEL has similar problems!

**Comment by namdre** [comment]
minGap denotes net-distance (follower front-bumper to leader back-bumper). a distance with 3 is thus more than enough.

**Comment by lishuaimarshall** [comment]
But you should know length="5" and the speed=20, so  the simulation result is not right!
There is something wrong with the SUMO system default program!!!!!!!!
Now I find out a bug the  Unit of  "departPos" is wrong ,I think you should X10;
and the unit of "tau" is also wrong ,I think you should also X10！

**Comment by namdre** [comment]
- Please specify the complete vType definition that you used in your test
- what is the speed attribute of your roads?

**Comment by lishuaimarshall** [comment]
(rou.xml)   
<vType id="HDV" carFollowModel="IDM" color="0,1,0" length="5" maxSpeed="30" accel="2.0" decel="4.0" tau="1" delta="4"  stepping="1" minGap="2" emergencyDecel="5"/>
(control.py)
    traci.vehicle.add("1", "route1", typeID="HDV", depart="0", departPos="450", departSpeed="20")
    traci.vehicle.add("2", "route1", typeID="HDV", depart="0", departPos="300", departSpeed="20")
    traci.vehicle.add("3", "route1", typeID="HDV", depart="0", departPos="150", departSpeed="20")
    traci.vehicle.add("4", "route1", typeID="HDV", depart="0", departPos="0", departSpeed="20")
    traci.vehicle.setSpeed("1", 20)

is my vtype ，you know, in python contral program ,my control car speed is 20m/s, and in this vtype tau="1",so if I want to keep my car is safe,the diatance of car1 and car2 should approximately equal to  20,but simulation result only 3m.it is must worry. so i think the unit of tau is worry ,and you see my
departPos=150m , but in fact only has 15m ,so I think is worry

**Comment by lishuaimarshall** [comment]
in addition , my sumo version is 1.3.1

**Comment by lishuaimarshall** [comment]
<vType emergencyDecel="5" minGap="2" stepping="1" delta="4" tau="14" decel="4.0" accel="2.0" maxSpeed="30" length="5" color="0,1,0" carFollowModel="IDM" id="HDV"/>

**Comment by lishuaimarshall** [comment]
vType emergencyDecel="5" minGap="2" stepping="1" delta="4" tau="14" decel="4.0" accel="2.0" maxSpeed="30" length="5" color="0,1,0" carFollowModel="IDM" id="HDV

**Comment by lishuaimarshall** [comment]
it is my vtype setting

**Comment by namdre** [comment]
There must be something else wrong with your setup. Please provide all input files. (python script, net.xml etc.)

**Comment by lishuaimarshall** [comment]
（rou.xml）
``<routes>
     <vType id="HDV" carFollowModel="IDM" color="0,1,0" length="5" maxSpeed="30" accel="2.0" decel="4.0" tau="1" delta="4"  stepping="1" minGap="2" emergencyDecel="5"/>
     <route id="route1" edges="gneE0"/>
</routes>

(control.python)
`import os
import sys
import optparse
import traci
import matplotlib.pyplot as plt
import numpy as np

if 'SUMO_HOME' in os.environ:
    tools = os.path.join(os.environ['SUMO_HOME'], 'tools')
    sys.path.append(tools)
else:
    sys.exit("please declare environment variable 'SUMO_HOME'")
from sumolib import checkBinary  
def get_options():
    optParser = optparse.OptionParser()
    optParser.add_option("--nogui", action="store_true",
                         default=False, help="run the commandline version of sumo")
    options, args = optParser.parse_args()
    return options
if __name__ == "__main__":
    options = get_options()   
    if options.nogui:
        sumoBinary = checkBinary('sumo')
    else:
        sumoBinary = checkBinary('sumo-gui')
    traci.start([sumoBinary, "-c", "single.sumocfg"])
    traci.vehicle.add("1", "route1", typeID="HDV", depart="0", departPos="30", departSpeed="20")
    traci.vehicle.add("2", "route1", typeID="HDV", depart="0", departPos="15", departSpeed="20")
    traci.vehicle.add("3", "route1", typeID="HDV", depart="0", departPos="0", departSpeed="20")
    traci.vehicle.setSpeed("1", 20)
    for step in range(0,1000):
                  traci.simulationStep()
    traci.close()`

（sumocfg）
`    <input>
        <net-file value="single.net.xml"/>
        <route-files value="single.rou.xml"/>
    </input>
    <time>
        <begin value="0"/>
        <end value="30000"/>
        <step-length value="1"/>
    </time>
    <gui_only>
         <gui-settings-file value="single.settings.xml"/>
    </gui_only>
</configuration>`

(net.xml)
`<net version="1.3" junctionCornerDetail="5" limitTurnSpeed="5.50" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/net_file.xsd">

    <location netOffset="0.00,0.00" convBoundary="0.00,0.00,200000.00,0.00" origBoundary="10000000000.00,10000000000.00,-10000000000.00,-10000000000.00" projParameter="!"/>

    <edge id="gneE0" from="gneJ0" to="gneJ1" priority="-1">
        <lane id="gneE0_0" index="0" speed="33" length="200000.00" shape="0.00,-1.60 20000.00,-1.60"/>
    </edge>

    <junction id="gneJ0" type="dead_end" x="0.00" y="0.00" incLanes="" intLanes="" shape="0.00,0.00 0.00,-3.20"/>
    <junction id="gneJ1" type="dead_end" x="200000.00" y="0.00" incLanes="gneE0_0" intLanes="" shape="200000.00,-3.20 200000.00,0.00"/>

</net>
`

**Comment by lishuaimarshall** [comment]
(rou.xml)
`<routes>
     <vType id="HDV" carFollowModel="IDM" color="0,1,0" length="5" maxSpeed="30" accel="2.0" decel="4.0" tau="1" delta="4"  stepping="1" minGap="2" emergencyDecel="5"/>
     <route id="route1" edges="gneE0"/>
</routes>`

**Comment by lishuaimarshall** [comment]
this my all input files,please help me

**Comment by lishuaimarshall** [comment]
[single.zip](https://github.com/eclipse/sumo/files/4006611/single.zip)

**Comment by lishuaimarshall** [comment]
sorry,the zip is my all file ,you can see the departPos="15" ,but diatance of car1 and car2 only 3m  in 0 second.so maybe have a bug.

**Comment by namdre** [comment]
- your edge is defined with a length of 200000.00m whereas it's geometrical length is only 20000m this causes visual distortions.  If you look at the actual vehicle position (vehicle.getLanePosition) you can see that the distances are fine.
- it looks as if you manipulated the network in a text editor. This is not recommended as you can easily  create a network that fails to work as expected (if you are lucky you just get an error but you might also get bad simulation results as well)

**Comment by lishuaimarshall** [comment]
Thank you for your help.the Problem solved！thanks！！！
