### ISSUE TITLE
[traci] e1Detector does not detect passed vehicle

### ISSUE THREAD

**Issue by KavinduZoysa** [eclipse/sumo#6450]
![traffic](https://user-images.githubusercontent.com/28332708/71431141-e3dd5e00-26f5-11ea-8d5a-fed3061e878f.png)
 Pointed image (orange circle) change the lane on the indicator. Then both indicators do not detect the passed vehicle(marked in orange circle).

**Comment by namdre** [comment]
what sumo version are you using?

**Comment by KavinduZoysa** [comment]
It is 1.2.0 and I am using it on Ubuntu 16.0.4. Also, I faced the above issue when I get the vehicle details using traci.

![version](https://user-images.githubusercontent.com/28332708/71456259-aa245a00-27be-11ea-8c4a-ee7a49aa6c14.png)

**Comment by namdre** [comment]
Please share a minimal scenario for reproducing the issue (preferably without traci). You can attach the files (zipped) to this ticket.

**Comment by KavinduZoysa** [comment]
Here I have attached the configurations. The issue occurs at the 888th time step.
Please note that this issue only occurs for below configurations. If I change the configurations, for example, change the minimum acceleration, the issue disappears.

[resources.zip](https://github.com/eclipse/sumo/files/4002009/resources.zip)

**Comment by namdre** [comment]
What is the id of the affected vehicle?

**Comment by KavinduZoysa** [comment]
f3.129

**Comment by namdre** [comment]
I cannot reproduce the issue. In my test (with 1.2.0 as well as 1.4.0), the vehicle f3.129  is counted as having passed detector lowerIn1_2 (in traci as well as xml output).
My test looks like this:

```
import traci
traci.start(['sumo', '-c', 'test.sumocfg', '--no-step-log'])
for i in range(770):
    traci.simulationStep()
    print(traci.simulation.getTime())
    for det in traci.inductionloop.getIDList():
        print("  %s last=%s" % (det, traci.inductionloop.getLastStepVehicleIDs(det)))
traci.close()
```

**Comment by KavinduZoysa** [comment]
In my code what I am doing is, I am maintaining a python dict to hold the vehicle details which are running on the junction. If one vehicle is entered or one vehicle has departed the junction. As a workaround, I catch the exception and continue, so the count does not change.

Therefore let's close the issue, I will reopen it if it becomes a big problem to my project, then we can dig more on the issue.

Thank you, for your support.
