### ISSUE TITLE
BUG about the "dispose"and"tau"

### ISSUE THREAD

**Issue by lishuaimarshall** [eclipse/sumo#6453]
the unit of "dispose"and"tau" is not right!
the unit of "dispose" should be  (m) not (dm)
the unit of "tau" should be  (s) not (..)

**Comment by namdre** [comment]
The unit of tau is (s). If this ticket refers to #6449. Please do not open up new issues until the original question is resolved.
Also,  what do you mean by "dispose". There is no such attribute.

**Comment by lishuaimarshall** [comment]
sorry  “departPos”，not dispose,sorry!
