### ISSUE TITLE
Problems of vehicle's crash in SUMO

### ISSUE THREAD

**Issue by Yuchen-CC** [eclipse/sumo#6454]
When two vehicles crash, how to set up to simulate a real failure scenario, rather than removing the vehicle involved.
![warning](https://user-images.githubusercontent.com/59412251/71641552-ebde6480-2cd8-11ea-8527-7c283b747db6.png)
![crash](https://user-images.githubusercontent.com/59412251/71641554-f4cf3600-2cd8-11ea-82a2-92036376d466.png)

**Comment by namdre** [comment]
set option --collision.stoptime SECONDS to make both participants of the collision stop for the specified time.
