### ISSUE TITLE
add supermode 'Data'

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#6461]
edit modes:
- edgeData mode (#3094)
- edgeRelation mode (#6462)
- OD mode (#6463)
- special select mode (allow filtering by minTime, maxTime)
- special inspect mode: 
   - when inspecting an edge, show hierarchy of all connected data objects and their intervals
   - when inspecting an edge that has selected edgeData objects (from select mode), open an attribute frame for jointly editing all (common) attributes the selected objects

**Comment by palvarezlopez** [comment]
Rest of issures related with this DataElements will be fixed in other tickets.
