### ISSUE TITLE
allow visualising and editing edgeRelation files

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#6462]
similar to edgeData (#3049) and part of 'Data' supermode (#6461).
- required by #6229 
- `<edgeRelation from="fromEdgeID" to="toEdgeID" attibute1="..." attribute2="..." .../>`

- [x] When possible, edgeRelations should be rendered on single lanes instead of edges (independent of available connections). This way overlap can be reduced and relations can more often be selected with a single click

**Comment by namdre** [comment]
sumo-gui now supports visualization via #6659

**Comment by palvarezlopez** [comment]
edgeRelations are 100% functionals. New issues/enhancements will be handled in a different ticket
