### ISSUE TITLE
allow visualising and editing tazRelation files

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#6463]
similar structure to edgeRel (#6462) and part of 'Data' supermode (#6461).
- required for editing OD-Matrizes
- `<tazRelation from="fromTazID" to="toTazID" attibute1="..." attribute2="..." .../>`
- Add  TAZRelation in RTREE

**Comment by namdre** [comment]
The basics are working. Work continues in #9131

**Comment by palvarezlopez** [comment]
Test needed
