### ISSUE TITLE
Deadlock in MSVehicle.cpp at an intersection with complicated left turns

### ISSUE THREAD

**Issue by jprk** [eclipse/sumo#6471]
The change in 1.4.0 with respect to yielding deadlocks in [MSVehicle.cpp](https://github.com/eclipse/sumo/blob/d502525be96ef978cbb2b60adeefc60bfcc56110/src/microsim/MSVehicle.cpp#L2696-L2711) introduces deadlocks that may be related to intersecting left turns (ref #4322). The intersection that causes that in our simulation has indeed rather weird internal lane shapes (due to OSM import) and `netconvert` warns that

```
Warning: Intersecting left turns at junction 'cluster_417025056_417025059'
from lane '-35586894#4_0' and lane '-35586887_0'
(increase junction radius to avoid this).
```

Given the almost TT shape of the intersection, I think that the intersection of left turns is unavoidable in this case. I have also tried to edit the internal lane shapes to remove some of the OSM importer/netconvert artifacts (creating `deadlock.new.new.xml` in the attached archive), but it does not seem to help.

Network files to demonstrate the deadlock are here: [deadlock.zip](https://github.com/eclipse/sumo/files/4040405/deadlock.zip). The simulation typically freezes at 15th or 16th second.

Jan

**Comment by namdre** [comment]
Well, this is embarrassing but it should be fixed now. 

FYI: we added that code to pave the way for parallelization (the earlier way to resolve right-before-left deadlock was subject to a race-condition when the approaching vehicles are handled by different threads).

The junction does look ugly that way it is. I think the best way to model this road structure is by avoiding the join. Either by setting netconvert option **--junctions.join-exclude**  or by using the Netedit 'split junction' functionality in the junction context-menu).

**Comment by namdre** [comment]
Another scenario deadlocked. Back to the drawing board.
