### ISSUE TITLE
allow defining trip locations with junction ids

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#6474]
- new trip attributes: fromJunction, toJunction, viaJunctions
- when starting at a junction this is shorthand for starting on any of the edges outgoing from that junction
- when arriving at a junction this is shorthand for arriving on any of the edges incoming to that junction
- the necessary TAZ should be defined ~~automatically~~ in an option is set (to avoid needless increase in routing graph). Defining them on-demand would cause problems with runtime routing-graph modifications.

**Comment by palvarezlopez** [comment]
@namdre also in NETEDIT?

**Comment by namdre** [comment]
eventually. But please don't worry about it just yet (-:
