### ISSUE TITLE
add GPL v2.0+ as secondary license

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#6506]
This ticket tracks the progress in adapting SUMO's license from a pure Eclipse Public License v2 to one which uses the Exhibit A to allow people to license SUMO under GPL v2 or later as well. For details see https://www.eclipse.org/legal/epl-2.0/faq.php#epl-secondary. We need every contributor and committer to add a +1 to this ticket. Please do not use the GitHub "reactions" to send a  simple "thumbsup" but post a comment to this ticket with at least a +1 in it (for an example see below). You can also use the comments to ask for clarifications. Thanks for your support!

**Comment by behrisch** [comment]
+1

**Comment by angelobanse** [comment]
+1

**Comment by RobertHilbrich** [comment]
+1

**Comment by lbieker** [comment]
+1

**Comment by ArmelliniMG** [comment]
+1

**Comment by schwamborn** [comment]
+1

**Comment by namdre** [comment]
+1

**Comment by palvarezlopez** [comment]
+1

**Comment by m-kro** [comment]
+1

**Comment by michele-segata** [comment]
+1

**Comment by lcodeca** [comment]
+1

**Comment by jprk** [comment]
+1

**Comment by rummel123** [comment]
+1

**Comment by yunpangfloetteroed** [comment]
+1

**Comment by RNippold** [comment]
+1

**Comment by mightyCelu** [comment]
+1

**Comment by theDivj** [comment]
+1

**Comment by seb-ehm** [comment]
+1

**Comment by bstriner** [comment]
+1

**Comment by srishtidh** [comment]
+1

**Comment by tkchouaki** [comment]
+1

**Comment by mkrumnow** [comment]
+1

**Comment by sommer** [comment]
+1

**Comment by gprichter** [comment]
+1

**Comment by dbuse** [comment]
+1

**Comment by Anisotrop** [comment]
+1

**Comment by jacobowitz** [comment]
+1

**Comment by behrisch** [comment]
Thank you all! The license change is now complete. The official announcement will be made once the Eclipse process of certifying the 1.5.0 release is through.
