### ISSUE TITLE
retrieve average consumption per km from battery device

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#6507]
for this, the device needs to track the total energy consumed since the trip began. This can be combined with vehicle.getOdometer() to compute the average consumption.

**Comment by schwamborn** [comment]
New (read-only) battery device parameters introduced:

 - `device.battery.totalEnergyConsumed`
 - `device.battery.totalEnergyRegenerated`

Can both be retrieved via `vehicle.getParameter()`.
