### ISSUE TITLE
Avoid draw inverted text

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#6516]
busStop lines, detectors, vehicle tags...

**Comment by namdre** [comment]
Please refactor to use GUIVisualizationSettings::getTextAngle (see GUIEdge.cpp) and restore the previous signature of GLHelper::drawText.

Also, happy easter (-:

**Comment by palvarezlopez** [comment]
Fixed in #7208

**Comment by namdre** [comment]
it's worse than before

**Comment by namdre** [comment]
![Screenshot from 2020-09-28 20-17-49](https://user-images.githubusercontent.com/6240630/94470295-c4fd8200-01c7-11eb-8023-6a09c589e104.png)
