### ISSUE TITLE
WAUT Switches break if time greater than 1 day.

### ISSUE THREAD

**Issue by FlorianDietz** [eclipse/sumo#6522]
I am using a WAUT switch, but it is not working properly if times exceed 1 day, or 86400 seconds:

The bug is predictable:
All times that exceed 86400 are taken modulo 86400. This interferes with the actual correct times. If you have switches for 7 days, then the switches for all 7 days will be executed on the first day, and the remaining 6 days have no switches at all.

Here is example code that triggers the bug:

`
    <WAUT id="WAUT_cluster_25880842_25880843_325130564" refTime="0" startProg="tls_cluster_25880842_25880843_325130564_program_SP1">
        <wautSwitch time="21600" to="tls_cluster_25880842_25880843_325130564_program_SP3"/>
        <wautSwitch time="32400" to="tls_cluster_25880842_25880843_325130564_program_SP2"/>
        <wautSwitch time="54000" to="tls_cluster_25880842_25880843_325130564_program_SP4"/>
        <wautSwitch time="68400" to="tls_cluster_25880842_25880843_325130564_program_SP2"/>
        <wautSwitch time="77440" to="tls_cluster_25880842_25880843_325130564_program_SP1"/>
        <wautSwitch time="108040" to="tls_cluster_25880842_25880843_325130564_program_SP3"/>
        <wautSwitch time="118860" to="tls_cluster_25880842_25880843_325130564_program_SP2"/>
    </WAUT>
`

**Comment by namdre** [comment]
fixed via #6540. If you want to disable modulo, set new WAUT argument period="0".
Alternatively, you can make the switches repeat after one week for easy multi-week simulation by setting period="7:0:0:0" (this is DAY:H:M:S time format which can be used for all time inputs, see https://github.com/eclipse/sumo/blob/master/tests/sumo/extended/wauts/week/input_additional.add.xml)
