### ISSUE TITLE
TraCI API for taxi dispatch algorithm

### ISSUE THREAD

**Issue by RobertHilbrich** [eclipse/sumo#6526]
Implement new TraCI functions to allow an external dispatching algorithm. We should treat the external dispatching algorithm as a regular TraCI client interacting with the SUMO simulation.

- [x] add a new dispatch algorithm "traci" that records and updates reservations

Needed API calls:
- [x] `traci.person.getTaxiReservations` - returns a list of all open reservations
- [x] `traci.vehicle.getTaxiFleet` - returns a list of (vehicle_id, status, list of reservation_ids...)
- [x] `traci.vehicle.dispatchTaxi(vehicle_id, list of reservation_ids)`

**Comment by namdre** [comment]
Only documentation is missing now. @MelanieWeber can you help out?

**Comment by kaalnaag** [comment]
kindly update the documentation please

**Comment by MelanieWeber** [comment]
Documentation added.
