### ISSUE TITLE
fix satelite background projection glitches

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#6539]
- downloaded satelite imagery (#6481) is using the global mercator projection (a web mapping standard) 
- netconvert uses UTM to project OSM data by default (less projection errors for typical scenarios)

The differences in coordinate transformation leads to gaps in the satelite background 

Possible solutions:
- use gdalwarp or python `gdal.Warp` to reproject the satelite images -> creates additional dependencies. see
   - https://gis.stackexchange.com/questions/139906/replicating-result-of-gdalwarp-using-gdal-python-bindings
  - https://stackoverflow.com/questions/48706402/python-perform-gdalwarp-in-memory-with-gdal-bindings
   - https://gis.stackexchange.com/questions/247871/convert-gps-coordinates-to-web-mercator-epsg3857-using-python-pyproj
   
-  when using the 'satelite background' in webwizard, set the netconvert projection to global mercator -> creates (bigger) distortions in generated network. 

The required netconvert option is 
```--proj "+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext  +no_defs"```

source: https://epsg.io/3857

**Comment by BjoernPK** [comment]
I just recently encountered this problem and wanted to check on the status. Is it possible to manually run the projection of tiles downloaded via `tileGet.py`? If so, is it sufficient to run netconvert on the `settings.xml` created with the downloaded tiles? Or do I have to run it on the net file that is linked to the `settings.xml`? Which command do I have to use for this?

I would be very happy to receive your feedback - thanks in advance! :)

**Comment by namdre** [comment]
assuming you have a webWizard-derived scenario, this is what you need to run:

```
netconvert -c osm.netccfg --proj "+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs"
tools/tileGet.py -n osm.net.xml -t 100 -d background_images -l -300
```

**Comment by namdre** [comment]
this solution comes with a downside: #14641
