### ISSUE TITLE
How to deactivate a WAUT with traci?

### ISSUE THREAD

**Issue by FlorianDietz** [eclipse/sumo#6546]
I am using traci to change traffic lights at runtime.

My problem is that whenever I try to set the TLS, SUMO will set it back if a WAUT schedules it. It doesn't understand that my traci commands should have priority over the WAUT.

My code works on top of other people's code, and I do not have access to the network configuration file or additional files, so I can't just delete the WAUT in the configuration.

I have tried using traci.trafficlight.setCompleteRedYellowGreenDefinition(). This can get overridden by a WAUT, in which case the WAUT takes over until the next time I call traci.trafficlight.setCompleteRedYellowGreenDefinition().

I have also tried just calling conn.trafficlight.setRedYellowGreenState() on every step, to just manually override everything. However, even this does not work: On the step on which a WAUT switches to a new program, the state will be set according to that Program for this one step. Apparently the WAUT takes priority over my traci command on that step.

Is there a way to override the WAUT without going through the config files and deleting them? I'm fine if I can delete the WAUT through traci by the way, but I couldn't find any options for this.

**Comment by namdre** [comment]
Now, WAUT should no longer affect tls after traci calls to setRedYellowGreenState.
Also, if the "magic" program id "online" is used, WAUTs no longer take effect.
