### ISSUE TITLE
simplify cyclical route definition

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#6554]
new route attribute `repeat="INT"` specifies the number of repetions when reaching the end of the route. Using 'period' (#6550) without `repeat` implies infinite repeats.

Benefit: allows cyclical routes without rerouter definitions.

Design questions:
- feature could be implemented as "syntactic sugar" by simply extending the route on first loading. 
  - Pro: very simple, no need to decide when the route must be extended (To ensure safe simulation, the route extension would have to be known in the latest when reaching the braking distance for the end of the last edge)
  - Con: requires more memory and does not allow for infinite repeats (which shouldn't be a problem in most cases)
- what should happen if the last edge is not connected to the first?. Probable solution: error when loading route, can be ignored with **--ignore-route-errors**

**Comment by shift-Jaegger** [comment]
Hello, excuse me for my lack of full knowledge of how the software works... In my version of SUMO the route attribute "repeat" doesn't exist.

Should I be downloading a new version? and if so, do I have to download everything again or just update the file? Where do I look for the specific file if that's the case?

Thank you for your constant support.

**Comment by namdre** [comment]
@shift-Jaegger  This is just an enhancement idea (hence the ticket status is 'open' and 'created 5h ago'. Now that you commented on this ticket, you will receive emails when this changes.

**Comment by shift-Jaegger** [comment]
Okay, now I see how it works.

Great, thank you!
