### ISSUE TITLE
Missing "Network" and "Demand" buttons from NETEDIT 1.1.0

### ISSUE THREAD

**Issue by brylie** [eclipse/sumo#6560]
I am following the Hello World tutorial, but don't see the "Network" and "Demand" buttons:

![screenshot](https://user-images.githubusercontent.com/17307/73244149-eb3ece00-41b1-11ea-8af9-f245017d2054.png)

The tutorial screenshot looks like this:

![tutorial screenshot](https://sumo.dlr.de/docs/images/NeteditNetworkMode.png)

How can I add the toolbar with "Network" and "Demand" buttons?

## Environment
Sumo 1.4.0 (Ubuntu PPA)
NETEDIT: 1.1.0
OS: Kubuntu 19.10

**Comment by namdre** [comment]
The screenshot shows Netedit version 1.1 so you probably have an old version installed that comes before the newer version in your $PATH

**Comment by brylie** [comment]
I just used the PPA to install SUMO, and haven't installed any other version. What is the latest version that I should expect to see?

**Comment by namdre** [comment]
The latest package on https://launchpad.net/~sumo/+archive/ubuntu/stable is 1.4 so this is the version you should get. Possibly, you ended up with the outdated sumo from the default ubuntu repository (19.10 provides SUMO version 1.1)
