### ISSUE TITLE
StepListener, step function argument 't' is always 0 in Python API

### ISSUE THREAD

**Issue by Trashcleaner** [eclipse/sumo#6561]
When using traci.StepListener, the function `step(self, t)` is supposed to contain the current time of the simulation. This seems to not be the case. The minimal example to recreate the issue is to directly use the example from the docs https://sumo.dlr.de/docs/TraCI/Interfacing_TraCI_from_Python.html#adding_a_steplistener. 

SUMO version 1.4., but I had the same issue also in version 1.2 and 1.3.1 earlier.

Because StepListeners are quite handy for my scenarios, I currently use a workaround like this:
```    
traci.simulation.subscribe(varIDs=[traci.constants.VAR_TIME])

class MyListener(traci.StepListener):
        def step(self, t=0):
                t = traci.simulation.getSubscriptionResults()[traci.constants.VAR_TIME]
                # ....
```
Whether the argument t has the default value set to 0 or not does not change a thing.

Thank you.

**Comment by namdre** [comment]
The t parameter contains the argument that was passed to traci.simulationStep (this step argument is optional with default 0)
@behrisch  I'm not sure whether this behavior is the intended or not.

**Comment by Trashcleaner** [comment]
I see. That was not clear from the documentation.

In that case, if you pass e.g. counter variable from main simulation loop (usually called step) then your logic might break if you change simulation step length. 

I assumed the argument t is supposed to be the time of simulation. That would seem more logical and 'correct' in  my opinion.

Thank you for answer.
