### ISSUE TITLE
I don't want any vehicles to stop on the junction,how could I do?

### ISSUE THREAD

**Issue by Sheldon-Zhou1997** [eclipse/sumo#6571]
Here is a junction which connects a 4-lanes edge to a 5-lanes edge with the same direction.Some vehicles always stop on the junction at a small angle and bar all vehicles' way behind them.So how could I do to prohibit any vehicles stop on the junction?Thank you!

when using using SL2015 without sublane model, some lanes are not utilized.
(lane FSN2_2 at time 430)

**Comment by namdre** [comment]
Can you add a screenshot of the situation?

**Comment by Sheldon-Zhou1997** [comment]
You can say a long queue in the picture,but vehicles can't flow into the third lane so that the third lane is empty.Thank you!










At 2020-01-29 22:52:35, "Jakob Erdmann" <notifications@github.com> wrote:

Can you add a screenshot of the situation?

**Comment by namdre** [comment]
I still cannot see your screenshot. Can try again to attach it to the issue?

**Comment by Sheldon-Zhou1997** [comment]
![微信图片_20200129150555](https://user-images.githubusercontent.com/52645665/73414513-fdec0b00-4349-11ea-963d-3339dcc85c07.jpg)

**Comment by Sheldon-Zhou1997** [comment]
I've send them to your email,"namdre.sumo@gmail.com".My email is 1768453783@qq.com.I'm a Chinese.

**Comment by namdre** [comment]
The lane is not blocked. Rather, not a single vehicle likes to use that lane.
The problem seems to be the connectivity downstream of the circled junction. 
Instead of connecting straight on, the connection arrow points slightly to the right.

**Comment by Sheldon-Zhou1997** [comment]
Since lane3 is free,why don't vehicles in lane4 and lane2 flow into the lane3?

**Comment by namdre** [comment]
Most likely, because the connections form lane3 do not lead to their desired destination. Check your lane-to-lane connections.

**Comment by Sheldon-Zhou1997** [comment]
I've check the connections for a whole afternoon.I still cannot solve it yet.Could you please check my source file to solve it? My tutor said it may be a bug.Firstly, why vehicles in lane2 & lane4 could not flow into lane3?Lane3 is empty and lane3 is also a available part of the route.Secondly,why do the vehicles detained in the connection so that vehicles behind them cannot pass?
I send my network file to your email,"namdre.sumo@gmail.com". My email is 1768453783@qq.com.

**Comment by Sheldon-Zhou1997** [comment]
[networks.tar.gz](https://github.com/eclipse/sumo/files/4133869/networks.tar.gz)

**Comment by namdre** [comment]
You have configured laneChangeModel="SL2015" even though you are not using the sublane model. This mode of operation is experimental / buggy. If you use the default laneChangeModel, all lanes will be used.
