### ISSUE TITLE
Vehroute output crashes the simulation while rerouting the vehicle under some circumstances

### ISSUE THREAD

**Issue by Trashcleaner** [eclipse/sumo#6572]
I run simulation scenarios where I reroute vehicles via two traci functions: `traci.vehicle.changeTarget(vehID, "dest_edg")` and `traci.vehicle.setRouteID(vehID, rouID)`. My simulation sometimes crashes while calling `changeTarget`.

While digging into the problem I tried to set up a minimal scenario with example TraCI program to replicate the bug.

While I  was preparing the files to submit here I accidentally fixed the crash by removing outputs from sumocfg file. I found out that only vehroute output causes crash this way.

I submit the scenario ready to be run and crash with a detailed explanation of what I'm doing in the script. There are 4 functions - 2 that causes the crash and 2 that does not. However, if you turn off vehroute output in sumocfg, then no crash occurs.

Thank you
Files: 
[rerouting_bug.zip](https://github.com/eclipse/sumo/files/4128549/rerouting_bug.zip)

**Comment by namdre** [comment]
Just to be clear on the wording: As far as I can tell, the simulation does not crash. It just responds with an error to a traci command. This error is not fatal and can be handled with try/except. Not handling it, makes the traci script crash. After this, sumo aborts with an error because the traci script is not responding (peer shutdown). 
It's still a bug because vehroute-output should not be causing such an error.

**Comment by namdre** [comment]
Crash was caused by the sequence of changeTarget, setRouteID, changeTarget.
Thanks for the excellent preparation of the failure example!

**Comment by Trashcleaner** [comment]
> Just to be clear on the wording: As far as I can tell, the simulation does not crash. It just responds with an error to a traci command. This error is not fatal and can be handled with try/except. 

I understand. In my main program, I have much better error handling. But I could not recover from the exception somewhat gracefully, i.e. to reroute the vehicle to another rou/target. The only way how to handle it is just to let the vehicle finish the route and let it disappear from the simulation. However, such a situation is disruptive for my use case.
