### ISSUE TITLE
Duarouter error log file issue when used with multiple threads

### ISSUE THREAD

**Issue by motaa** [eclipse/sumo#6579]
duarouter is being launched from Java:
`ProcessBuilder pb3 = new ProcessBuilder("cmd","/c","duarouter.exe","--trip-files="+trip_file,"--net-
  file="+net_file, "--output-file="+route_file_level3, "--ignore-errors", "true", "--error-log", 
  error_file_level4, "--routing-threads","16");
pb3.inheritIO();
pb3.directory(new File(sumo_bin));		
Process p3 = pb3.start();
p3.waitFor();`

The resulting error log file mixes up several rows:

`Warning: The vehicle '14' has no valid route.
Warning: Warning: **NNoo  ccoonnnneeccttiioonn  bbeettwweeeenn  eeddggee**  ''-153819437#4376553475#1''  aanndd  eeddggee  ''308322273-43966419#7' found.
' found.
Warning: Mandatory edge '308322273' not reachable by vehicle '16'.
Warning: Mandatory edge '-43966419#7' not reachable by vehicle '17'.
Warning: The vehicle '16' has no valid route.
Warning: The vehicle '17' has no valid route.`

The log file becomes almost unparseable.
As a workaround, launch 16 duarouters on a split trip file

**Comment by namdre** [comment]
which version of SUMO are you using?

**Comment by motaa** [comment]
Version 1.4.0
