### ISSUE TITLE
Vehicles fail to reach their target position (IDM) (trac #658)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#658]
-> sounds like a bug in the car following model. This was an issue with Wiedemann.

Hello again,

I have now tried the same simulation with the standard kraus-sumo
algorithm and this problem doesn't occur so often, but it does neither
the less.
The reason is that the vehicle are on their destination edge but are
stopping before they are arriving the destination position. So after the
time-to-teleport ends they are teleported.

Is this a bug in Sumo?

With best regards
Claudius Heine

Am Donnerstag, den 26.01.2012, 11:39 +0100 schrieb Claudius Marpa Heine:
> Hello SUMO users,
>
> I am using IDM to simulate the traffic in Augsburg, Germany and got a
> strange problem while simulating with SUMO.
> The vehicles, that arrives on their destination edge, stops and waits
> for some time. This behaviour creates lots of traffic jams all over the
> map.
>
> Is there any parameter or something to change this behaviour?
>
> With thanks and best regards
>
> Claudius Heine
>

Migrated from http://sumo.dlr.de/ticket/658
```json
{
    "status": "new", 
    "changetime": "2013-09-10T09:06:22Z", 
    "description": "-> sounds like a bug in the car following model. This was an issue with Wiedemann.\n\nHello again,\n\nI have now tried the same simulation with the standard kraus-sumo\nalgorithm and this problem doesn't occur so often, but it does neither\nthe less.\nThe reason is that the vehicle are on their destination edge but are\nstopping before they are arriving the destination position. So after the\ntime-to-teleport ends they are teleported.\n\nIs this a bug in Sumo?\n\nWith best regards\nClaudius Heine\n\nAm Donnerstag, den 26.01.2012, 11:39 +0100 schrieb Claudius Marpa Heine:\n> Hello SUMO users,\n>\n> I am using IDM to simulate the traffic in Augsburg, Germany and got a\n> strange problem while simulating with SUMO.\n> The vehicles, that arrives on their destination edge, stops and waits\n> for some time. This behaviour creates lots of traffic jams all over the\n> map.\n>\n> Is there any parameter or something to change this behaviour?\n>\n> With thanks and best regards\n>\n> Claudius Heine\n>\n", 
    "reporter": "namdre", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1378803982885816", 
    "component": "microsim - car following", 
    "summary": "Vehicles fail to reach their target position (Claudius Heine)", 
    "priority": "minor", 
    "keywords": "", 
    "time": "2012-01-27T15:34:31Z", 
    "milestone": "1.0.0", 
    "owner": "", 
    "type": "defect"
}
```

**Comment by namdre** [comment]
original bug example now succeeds
