### ISSUE TITLE
How to set the "delay" in ACC car-following model

### ISSUE THREAD

**Issue by fengbaozhiling1** [eclipse/sumo#6581]
Is it possible to set a delay (1.5s) in ACC car-following model? Delay is the "ta" in this model. Thank you!

<img width="240" alt="微信图片_20200131120434" src="https://user-images.githubusercontent.com/44236971/73511778-ee3ff580-4421-11ea-96e6-363867f61f9d.png">

**Comment by namdre** [comment]
You cannot really set a delay in the sense that the model reacts to outdated observations. However, you can constrain action points (changes in acceleration) to a larger interval by setting vType attributie actionStepLength="1.5". The model will still react to observations at that action point.

**Comment by fengbaozhiling1** [comment]
> You cannot really set a delay in the sense that the model reacts to outdated observations. However, you can constrain action points (changes in acceleration) to a larger interval by setting vType attributie actionStepLength="1.5". The model will still react to observations at that action point.

Thank you! This method is practical.
