### ISSUE TITLE
Error found when i defined bus stop in rou.xml file

### ISSUE THREAD

**Issue by BhagyaJb** [eclipse/sumo#6587]
Error: The lane 352424275#4_0to352424275#4_1 to use within the busStop 'B1' is not known.
Error: Could not end a stopping place that is not opened.

**Comment by namdre** [comment]
The error probably tells you the truth: you used a lane id that does not exist in the network.

**Comment by BhagyaJb** [comment]
Thank you.

**Comment by Sirus1110** [comment]
it also happens when the postion of a bus defined in xx.add.xml exceeds the edge length

**Comment by behrisch** [comment]
@Sirus1110 It should not give the "unknown lane" error then. If it does in your scenario please open a new issue and attach the example.
