### ISSUE TITLE
Installation problems for versions 1.4.0, 1.3.1 and 1.3.0

### ISSUE THREAD

**Issue by coloal** [eclipse/sumo#6590]
I am trying to install this versions following the instructions described in: 'https://sumo.dlr.de/docs/Installing/Linux_Build.html', when calling: 'make -j $(nproc)' it always crash when trying to build polyconvert and netgenerate as shown in the image: 
![sumoInstallation141Break](https://user-images.githubusercontent.com/45335317/73665995-5c92eb00-46a2-11ea-96fb-b7fbb8da58d0.png)
It has to be said that 1.1.0 version is built properly.

**Comment by schwamborn** [comment]
Please don't double-post on the mailing list and here. Harald Schaefer already gave you some pointers on the mailing list. Please continue there.
