### ISSUE TITLE
netconvert - Assumption in calculation of UTM zone in GeoConvHelper::x2cartesian

### ISSUE THREAD

**Issue by f5maki** [eclipse/sumo#6596]
Position passed as parameter. If position has x as latitude and y as longitude the following will give an incorrect UTM zone: 

GeoConvHelper::x2cartesian
line 356 : int zone = (int)(x + 180) / 6 + 1;

x must be a longitude for this to work. The ArcView shapefile import inputs positions as lat long.

**Comment by namdre** [comment]
I doubt this. The class NIImporter_ArcView retrieves geometry points using the functions OGRLineString::getX and ::getY  which should return them in lon,lat order if the shape is defined correctly. Also, the functionality is working fine in our tests.

If you can provide a failing input sample I can take a look, though.

**Comment by f5maki** [comment]
Looking at the gdal site - https://gdal.org/tutorials/osr_api_tut.html - CRS and axis order

"Before GDAL 3.0, the OGRSpatialReference class did not honour the axis order mandated by the authority defining a CRS and consequently stripped axis order information from the WKT string when the order was latitude first, longitude second. Coordinate transformations using the OGRCoordinateTransformation class also assumed that geographic coordinates passed or returned by the Transform() method of this class used the longitude, latitude order.

Starting with GDAL 3.0, the axis order mandated by the authority defining a CRS is by default honoured by the OGRCoordinateTransformation class, and always exported in WKT1. Consequently CRS created with the “EPSG:4326” or “WGS84” strings use the latitude first, longitude second axis order."

This implies that axis order in a shape file which uses GDAL for WGS84 assumes that x will be latitude. 

I understand your test data works. Thanks for looking at the issue. I can generate my shape file with longitude first.

**Comment by namdre** [comment]
I was not aware that OGR can sometimes return lat as x. Thanks for pointing this out. If I understand the documentation correctly, than calling 'SetAxisMappingStrategy(OAMS_TRADITIONAL_GIS_ORDER);' should make our code work with lat,lon-ordered data as well. Can you provide a small example shapefile that we could use to improve our tests?

**Comment by behrisch** [comment]
There is no easy fix as we found out that it very much depends on how you create the shapefile (or which source it comes from) so we added an option and continue work in #6936
