### ISSUE TITLE
discount overlapping flows

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#6601]
If a flow that spreads around the network reaches another flow-source edge it may either
a) ignore the new source and just keep going - this is the current behavior
b) terminate at the source and let a the new flow start
c) continue past the source and the upstream flow is subtracted from the departing flow 
d) continue past the source and the upstream flow is subtracted from the departing flow. If the upstream flow is larger, some of it terminates 

Let A be the upstream flow and B the departing flow
Effective traffic of the above variants:
a) A + B
b) B (routes are cut of)
c) max(A,B) (routes continue)
d) B (routes continue)

To be implemented via new options
- [ ] b) --sources-are-sinks, -S
- [ ] c) --discount-sources, -D
- [ ] d) --setting both options --subtract-sources and --sources-are-sinks

**Comment by jane212** [comment]
Hi Jakob,

You mentioned that to implement option d, we need to set both --subtract-sources and --sources-are-sinks. But I tried and found that there is no `--subtract-sources` option in both jtcrouter.py or JTRROUTER. Do you mean `--discount-sources` instead? (which is the current behavior in jtcrouter.py that sets both -S and -D for JTRROUTER).

Thanks,
Tingting

**Comment by namdre** [comment]
- I fixed the description (the option name is --discount-sources)
- jtcrouter sets the option --sources-are-sinks by default so you only need to add option --discount-sources
