### ISSUE TITLE
How should I solve the warning?

### ISSUE THREAD

**Issue by Sheldon-Zhou1997** [eclipse/sumo#6618]
I don't know how to solve the warning "Vehicle 'frnlb2775.920' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=11628338.00."?It always happens in my simulation.Thank you.

**Comment by namdre** [comment]
It depends. What car-following model are you using? For some models this indicates network or parameter issues, for other other models it is expected behavior (and the warning may be safely disabled).

**Comment by Sheldon-Zhou1997** [comment]
I used the default car-following model in large flow situation.So,it is not suitable?

**Comment by namdre** [comment]
The default model generally should not  raise this warning. What vType parameters did you set?

**Comment by Sheldon-Zhou1997** [comment]
![2020-02-09 23-01-07屏幕截图](https://user-images.githubusercontent.com/52645665/74104502-400a1d80-4b90-11ea-9859-14c98a3f089c.png)
![2020-02-09 23-01-29屏幕截图](https://user-images.githubusercontent.com/52645665/74104506-46989500-4b90-11ea-839a-1de2c7d64ed4.png)

**Comment by Sheldon-Zhou1997** [comment]
The situation can be seen as an uncontrolled intersection.

**Comment by Sheldon-Zhou1997** [comment]
I also used the default setting.

**Comment by namdre** [comment]
- what is the exact node type of the junction where this happens?
- do the warnings also occur with the default laneChangeModel? (LC2013). It could be due to a bug in DK2008 because this model is not actively developed anymore and not tested either.
