### ISSUE TITLE
Set stops for vehicle in particular order via TraCI does not work as expected.

### ISSUE THREAD

**Issue by Trashcleaner** [eclipse/sumo#6628]
Let's say I control a vehicle with id `veh_id` that is traversing route of following edges: `'A1' 'A2' 'A3' 'A1' 'A2' 'A3'` (note the loop traversed twice). 

Consider the vehicle is currently located at the edge `'A2'` (for the first time).
I use Python API and SUMO 1.4. If I call:

```
traci.vehicle.setStop(veh_id, 'A3', pos = 250)
traci.vehicle.setStop(veh_id, 'A2', pos = 250)
```
then these things can happen:

- vehicle `veh_id` was somewhere at the beginning of the edge `'A2'` and the stops are set in the following order: firstly at `'A2'` and then at `'A3'`
- vehicle `veh_id` was too far at the edge `'A2'`(close to end of the edge) and the second call of `setStop` could not be executed and TraCI throws exception.

Either way, it is not what I expected to happen. I want the vehicle to stop firstly at edge `'A3'` and then on the edge `'A2'`.  Is it possible to achieve this behaviour? Or is it a bug that `setStop` calls do not enforce the order?

For your convenience, I attach a ready to run scenario describing the problem in more detail.
Files:  [setStop_issue.zip](https://github.com/eclipse/sumo/files/4181108/setStop_issue.zip)

Thank you very much.

**Comment by namdre** [comment]
Thank you for reporting. I'll close this to avoid a duplicate ticket. See #6211

**Comment by Trashcleaner** [comment]
My apologies for duplicate, I didn't notice the relevant issue. 
Thank you very much.
