### ISSUE TITLE
Configuration to control the insertion of vehicles

### ISSUE THREAD

**Issue by KavinduZoysa** [eclipse/sumo#6632]
Hi,

What is the configuration should I use to control the insertion of vehicles into a junction. For example, I want to insert 2 vehicles per minute, or time difference between two vehicles should be greater than 30 seconds.

I was unable to find this configuration in SUMO or traci documentatoin. Please help me to get an answer.

Thank you

**Comment by namdre** [comment]
use flow attribute period="30" (see https://sumo.dlr.de/docs/Definition_of_Vehicles,_Vehicle_Types,_and_Routes.html#repeated_vehicles_flows)

**Comment by KavinduZoysa** [comment]
Thank you.
