### ISSUE TITLE
add optional junction attribute 'name'

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#6635]
similar to edges where 'name' stores the stree name, junctions may have a name as well.
This is different from the id because the name is optional, can contain spaces and doesn't have to be unique.

The name should be listed in the gui-property dialog and the gui-settings should allow rendering the name.

**Comment by m-kro** [comment]
Currently, "name" is used for IDs in the visualisation dialog (street, junction). It should be replaced by "ID" to reflect which attribute it refers to.

**Comment by namdre** [comment]
Agreed.
