### ISSUE TITLE
Improve usefulness of nightly Linux-Netedit tests

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#6637]
The current tests fail because netedit in a virtual framebuffer behaves differently from netedit over a live sessions.

Step 1:
Check whether the virtual framebuffer approach (which was working earlier) can be salvaged
- use screenshots to hunt for the problematic clicks
- test another window manager

Step 2 (fallback):
- run a smaller selection of netedit test with a live gui just as it is done for the windows netedit tests
- The full suite of netedit tests should run on a dedicated server once a week

**Comment by behrisch** [comment]
Everything works fine here. The test failures are basically due to the addition of the data mode. @palvarezlopez I fixed some easy ones. Could you have a look at the remaining tests?

**Comment by behrisch** [comment]
@palvarezlopez @namdre  Can we somehow make the tests less sensitive? Three days after the release we were already back to "all red".

**Comment by palvarezlopez** [comment]
@behrisch I'm working on it.

**Comment by behrisch** [comment]
It is a permanent task but the immediate problem is solved.
