### ISSUE TITLE
Lanearea detector: jam length exceeds detector length

### ISSUE THREAD

**Issue by m-kro** [eclipse/sumo#6642]
Currently, the detector can output values exceeding its own length due to how the first vehicle is treated:
https://github.com/eclipse/sumo/blob/2ac57f0e4cbafd56ad8fbd4df02c60d6e962174d/src/microsim/output/MSE2Collector.cpp#L1199-L1201
"distToDetectorEnd" gets negative when the vehicle front has already left the detector but still contributes to the result. **What is the intended semantics of the lanearea jam length?** I suggest 
`
const double jamLengthInMeters = lastVeh->distToDetectorEnd - MAX2(0.,firstVeh->distToDetectorEnd) + lastVeh->lengthOnDetector;
`
to limit the jam length to the detector length. If you want I can prepare a pull request for this.

**Comment by namdre** [comment]
I also think that the jam length should be limited to the detector length. Your opinion @behrisch?

**Comment by behrisch** [comment]
It is definitely wrong the way it is but I am unsure whether one would expect here the sum of the length of all vehicles plus gaps. m-kro's  solution has the side effect that for a long vehicle and a short detector the jam length could be less than the vehicle length. But still better than before ;-), so yes please do a pull request unless you find my remark so convincing that you want to introduce a configurable version of that :-)
