### ISSUE TITLE
minor datamode issues

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#6651]
minor stuff collected here instead of individual tickets (#3094, #6462) This ticket should stay open for some time to after merging the datamode-branch to allow issue collection.

- [x] lots of compiler warnings (e.g.  `/scr1/sumoDataBranch/src/netedit/GNEViewNetHelper.cpp:1531:29: warning: comparison between ‘enum DataEditMode’ and ‘enum DemandEditMode’`
- [x] open data file currently filters for .dat.xml (should filter for .xml only)
- [x] 'grid' and 'spread vehicles' options should be removed from data mode
- [x] data-mode edit modes are missing from the edit menu
- [x] Inspect-mode overlap should not include network elements
- [x] edgeData mode should not show edgeRelation objects (on junctions)
- [x] inspect mode dotted contour is missing
- [x] top bar values (data type, data data set, interval) selection should persist when switching between modes (greyed out in edgeData and edgeRelation mode but return to the previous value when switching to inspect/select mode).
- [x] color scale should have a legend that shows min and max value for the selected attribute
- [x] color scales are not yet working
- [x] edgeData frame attribute selection lists attributes that are define in edgeRelations and not applicable to the loaded edgeData (and vice versa)
- [x] Esc does not clear the data selection when in data-select mode

**Comment by palvarezlopez** [comment]
@namdre about point "Inspect-mode overlap should not include network elements", I think that could be usefull to check parent edges (ID, numLanes, width, etc.). What do you think?

**Comment by namdre** [comment]
This can still be accomplished with a quick switch to network mode. I think it is more important to reduce the "overlap" situations because in most cases the user will have to figure out whether there are multiple data definitions on the same spot.

**Comment by palvarezlopez** [comment]
@namdre all issues fixed. Did yo found more?

**Comment by palvarezlopez** [comment]
All fixed. Future problems will be handled in new tickets.

**Comment by namdre** [comment]
data-mode edit modes are still missing from the edit menu

**Comment by namdre** [comment]
modes are there now
