### ISSUE TITLE
schema reference writen with http urls instead of https

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#6658]
would be a simple fix but I'm not sure if there are any downsides.
The current URL goes to a redirect page which the xml validation probably cannot handle.

affected functions:
- sumolib.xml.writeHeader 
- OutputDevice::writeXMLHeader

**Comment by behrisch** [comment]
We tried this a year ago but xerces cannot handle https, see for instance the history here: https://github.com/eclipse/sumo/commits/master/tests/activitygen/meta/write_template_full
