### ISSUE TITLE
how can i get indicators when sumo runing with meso?

### ISSUE THREAD

**Issue by passengerxuhongli** [eclipse/sumo#6666]
hello , 
when i run sumo with meso, i meet some problems.
when i get veh number on some edge in subcribe way, their is always 0.
and i try traci function getParameter(edge_id,"flow") ,it always return "".
and also i tried edge.getLastStepVehicleNumber(edge_id) , it also always return 0.
i try both traci and libsumo,but both samilar wrong.
note: same code works well when sumo run with micro.
so anyone can help me?

**Comment by namdre** [comment]
TraCI meso support is missing at the moment. see #3815

**Comment by namdre** [comment]
The latest development version supports traci.edge.getLastStepVehicleNumber for meso (https://github.com/eclipse/sumo/suites/472851395/artifacts/2087459)
