### ISSUE TITLE
Yes. using traci with commands vehicle.moveTo or vehicle.moveToXY.

### ISSUE THREAD

**Issue by siqi95** [eclipse/sumo#6670]
Yes. using traci with commands vehicle.moveTo or vehicle.moveToXY.
see 
https://sumo.dlr.de/docs/TraCI.html#traci_commands
https://sumo.dlr.de/docs/TraCI/Change_Vehicle_State.html

_Originally posted by @namdre in https://github.com/eclipse/sumo/issues/6669#issuecomment-587049968_

Hi namdre,
However, it seems once traci.simulationStep() loads, vehicle will move automatically, do I still need that command if I want to move it manually from the beginning?

**Comment by namdre** [comment]
Please do not open up new tickets for a followup question! Just  post to the old ticket.
