### ISSUE TITLE
Please help me with the traffic lights

### ISSUE THREAD

**Issue by Timor7hao** [eclipse/sumo#6675]
Dear friends:
     I want to achieve Coupled Lane Area Detectors in https://sumo.dlr.de/docs/Simulation/Output/Traffic_Lights.html#generated_output.But there is too little information about _tl_ and _to_.
    Please tell me the properties of tl and the to must manually in the add. Add is in the XML file, if there was any way to make generateTLSE2Detectors. Py automatically generated.I really need any help from you!
    Best wishes!

**Comment by namdre** [comment]
Now, generateTLSE2Detectors.py supports the option --tl-coupled 
to automatically set the `tl`-attribute.
Attribute `to` is not necessary.

**Comment by Timor7hao** [comment]
thank you very much for your reply.
And then I'm really sorry to ask you that I want to add a custom new property (summary-output) to this property set. Can I do that? Which python file do I need to change?
Sorry to trouble you.Thank you very much!
![image](https://user-images.githubusercontent.com/38340783/74949856-43779180-5439-11ea-8ab3-d5a92d083142.png)

**Comment by namdre** [comment]
The output values of the E2-Detector are encoded within the sumo application written in C++:
https://github.com/eclipse/sumo/blob/3a2f4ce9774bb177f5d10c77a81607a1fd782362/src/microsim/output/MSE2Collector.cpp#L1293-L1373

**Comment by Timor7hao** [comment]
thank you! love you!
