### ISSUE TITLE
How to change the direction of a road

### ISSUE THREAD

**Issue by KavinduZoysa** [eclipse/sumo#6678]
In our country, the left side is allowed for vehicles. However, when I simulate a junction in SUMO(first in netedit), I cannot configure the left side for vehicles. For example, the marked lane in green should be allowed for incoming vehicles to the junction.

![sumo](https://user-images.githubusercontent.com/28332708/74848376-9e3bbb00-535d-11ea-8e98-3e1a3780eb8b.png)
After I create all routes and run, I am getting below error.
```
Error: Vehicle 'f1.0' has no valid route. No connection between edge 'leftIn' and edge 'lowerOut'.
Quitting (on error).
```
Here I have attached all the resource files I used. Please help me solve this issue. I searched through the internet but I was unable to find anything related to this problem.
[resource.zip](https://github.com/eclipse/sumo/files/4225828/resource.zip)

**Comment by namdre** [comment]
set option lefthand (in netedit, hit F10 and then check 'lefthand' in the Processing options tab)

**Comment by KavinduZoysa** [comment]
Thank you a lot. I think it is better if this can be added to the online documentation if it is not added.

**Comment by namdre** [comment]
now documented at https://sumo.dlr.de/docs/FAQ.html#can_sumo_simulate_lefthand_traffic

**Comment by KavinduZoysa** [comment]
Thank you.
