### ISSUE TITLE
upstream build, sumo-gui run problem on ubuntu bionic 18.04

### ISSUE THREAD

**Issue by gprichter** [eclipse/sumo#6683]
for current upstream version build
`commit 292c3d1261844c4a0e005f903e28db8c64bae143`
I am experiencing **run problems for sumo-gui**

build completes fine, launching `sumo-gui` returns
  
    sumo-gui: error while loading shared libraries: libavformat.so.58: cannot open shared object file: No such file or directory
this library version is (to my understanding) not part of bionic LTS and not installed on my system (so also not present during the build)

the **question is:** why is it required on launch

**Comment by namdre** [comment]
please clean out the cmake-build folder and post the output of running `cmake`

**Comment by gprichter** [comment]
thanks, have done that before the make and build already.
however, see following attachment:

**comments:**
regarding `libproj`:

    libproj-dev/bionic,now 4.9.3-2 amd64 [installed]
    libproj12/bionic,now 4.9.3-2 amd64 [installed]
    libproj13/eoan,now 5.2.0-1 amd64 [installed]
regarding `libfox`:

    $ apt list '*libfox*'
    libfox-1.6-0/bionic,now 1.6.56-1 amd64 [installed,automatic]
    libfox-1.6-dev/bionic,now 1.6.56-1 amd64 [installed]

[SUMO-build_cmake-out.log](https://github.com/eclipse/sumo/files/4235536/SUMO-build_cmake-out.log)

**Comment by namdre** [comment]
What is the output when running `sumo` on the command line?

**Comment by gprichter** [comment]
Eclipse SUMO Version v1_5_0+0183-292c3d1261
 Build features: Linux-5.3.0-40-generic x86_64 GNU 7.4.0 Release SWIG GDAL
 Copyright (C) 2001-2020 German Aerospace Center (DLR) and others; https://sumo.dlr.de
 License EPL-2.0: Eclipse Public License Version 2 <https://eclipse.org/legal/epl-v20.html>
 Use --help to get the list of options.

**Comment by gprichter** [comment]
`libavformat.so.58` seems to be dependency connected to 
package `ffmpeg`, which is installed too, 
but the current version depends on package `libavformat57`
so I do not understand, where the runtime requirement of sumo-gui is coming from

**Comment by gprichter** [comment]
## UPDATE:
problem seems caused by a build artifact 
that was *not resolved by just deleting the build/cmake-build directory*
## SOLUTION:
* got myself a new git clone
* cmake output looks different
* make process caused problem with missing libswscale
  1. installed: `sudo apt install libswscale-dev`
    **NOTE:** add package dependency for ubuntu 18.04 LTS
  2. re-configured: `cmake ../..`
  3. contd. make process
* sumo-gui runnning fine now

**Comment by namdre** [comment]
postmortem: @behrisch any idea what could have happened here?

**Comment by behrisch** [comment]
The build log looks as if the build/cmake_modules directory is missing. @gprichter Could you please check whether it is present also with regard to #6688. As far as I can see it already contains a check for swscale.

**Comment by behrisch** [comment]
Furthermore it is strange that there is an eoan proj package on the machine when everything else is from bionic.

**Comment by gprichter** [comment]
@behrisch: 
## regarding the proj package 
- there does not seem to be a problem with that package
- some things are needed in more recent versions ... thererfore my default release is set to bionic, allowing very few exceptions
## the `build/cmake_modules`
- it is there, contains an `FindFFMPEG.cmake`
- which itself contains the find_path for `libswscale/swscale.h`
- BUT the path reference actually finding it seems to be the penultimate line,
  as no other reference to FFMPEG_DIR is found anywhere in the project
  and `ccmake ../..` does not show this variable to be set.
```
find_path(FFMPEG_INCLUDE_DIR4 libswscale/swscale.h
  $ENV{FFMPEG_DIR}
  $ENV{FFMPEG_DIR}/ffmpeg
  $ENV{FFMPEG_DIR}/libswscale
  $ENV{FFMPEG_DIR}/include/libswscale
  $ENV{FFMPEG_DIR}/include/ffmpeg
  /usr/local/include/ffmpeg
  /usr/include/ffmpeg
  /usr/include/libswscale
  /usr/include/ffmpeg/libswscale
  /usr/include/${CMAKE_LIBRARY_ARCHITECTURE}/libswscale
  /usr/local/include/libswscale
)
```
- with `cd build/cmake-build; ccmake ../..`
  FFMPEG_INCLUDE_DIR4 is set to /usr/include/x86_64-linux-gnu, while CMAKE_LIBRARY_ARCHITECTURE does not even show up. 
  so I wonder what makes make make the proper lookups ;)

**Comment by behrisch** [comment]
@gprichter As far as I understand the cmake mechanism those further arguments are just additional hints where to find the include. The default search path probably already contains `/usr/include/x86_64-linux-gnu` that's why everything is found. What made me ask about the presence of the cmake_modules is the output in the build log in https://github.com/eclipse/sumo/issues/6683#issuecomment-589595106. This looks like the Find* modules were not found.
