### ISSUE TITLE
sumo-gui freezing at random time step in 1.4 and 1.5

### ISSUE THREAD

**Issue by alexdawn** [eclipse/sumo#6684]
I afraid there no helpful error message other than the windows popup:

```
Description:
  A problem caused this program to stop interacting with Windows.

Problem signature:
  Problem Event Name:	AppHangB1
  Application Name:	sumo-gui.exe
  Application Version:	0.0.0.0
  Application Timestamp:	5e4200f8
  Hang Signature:	c7c6
  Hang Type:	513
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	2057
  Additional Hang Signature 1:	c7c63f4878454d240921e90b83293b44
  Additional Hang Signature 2:	371b
  Additional Hang Signature 3:	371b84ffb9535f01ea4dd9255755d4e2
  Additional Hang Signature 4:	997c
  Additional Hang Signature 5:	997cc3ec601fb5b9dd522357357b01f3
  Additional Hang Signature 6:	d89b
  Additional Hang Signature 7:	d89b4cd7830ffd042647b761dec0d8bd

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt
```
 but sumo-gui freezes and becomes non responsive at a random interval. The same simulation runs without issue in the headless sumo program and so far I've not seen issue with 1.3.1. Is there any way I can run it to get more verbose error logging?

**Comment by namdre** [comment]
You could run the debug version in a debugger and interupt the code when frozen to see where the call stack is at.
How reproducible is this? (How often and how soon does the freeze occur?)
Did you try on another operating system?
Can you share the scenario that is causing the issue?

**Comment by behrisch** [comment]
no further updates, please reopen if problems persist
