### ISSUE TITLE
upstream build problem / ubuntu bionic 18.04: ffmpeg dependent functionality missing libswscale

### ISSUE THREAD

**Issue by gprichter** [eclipse/sumo#6688]
when cmake detects the presence of `ffmpeg` it seems to want to build for video encoding
however, this requires the presence of headers that are missing and not checked by the cmake process
leading to a terminated compile:

    [ 62%] Building CXX object src/gui/CMakeFiles/gui.dir/GUIViewTraffic.cpp.o
    In file included from devel/sumo/src/gui/GUIViewTraffic.cpp:32:0: devel/sumo/src/utils/gui/div/GUIVideoEncoder.h:53:10: fatal error: libswscale/swscale.h: No such file or directory
    #include <libswscale/swscale.h>
             ^~~~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    src/gui/CMakeFiles/gui.dir/build.make:230: recipe for target 'src/gui/CMakeFiles/gui.dir GUIViewTraffic.cpp.o' failed

## solution:
additional install of package **libswscale-dev** remedies the situation
see https://github.com/eclipse/sumo/issues/6683#issuecomment-589680313

## required action:
- [x] ~~adapt cmake deps to~~ check for headers was implemented OK before
- [ ] document required packages for ffmpeg in build instructions
  (video recording functionality ?)

**Comment by behrisch** [comment]
fixed in https://github.com/eclipse/sumo/commit/426341b3f26d5ce90643b7803c09e4e89a02755c
