### ISSUE TITLE
enable optional CACC control mode key in fcd-output

### ISSUE THREAD

**Issue by schwamborn** [eclipse/sumo#6700]
Should print control mode ("ACC" or "CACC") for CACC CFModel if key "caccControlMode" is enabled in fcd-output, see #6685.

**Comment by schwamborn** [comment]
Re-opened due to dubious results reported by CERTH.

**Comment by namdre** [comment]
@schwamborn: I think it is necessary to consult MSGlobals::gComputeLC (true during lane change compuation) before updating the caccControlMode parameters because the functions freeSpeed and followSpeed can also be called during lane changing.

**Comment by namdre** [comment]
also, happy easter!

**Comment by schwamborn** [comment]
@namdre So lane changing does not affect the mode? Shouldn't `MSGlobals::gComputeLC` then be consulted by other code in `MSCFModel_CACC::freeSpeed()` and `MSCFModel_CACC::followSpeed()` as well?

**Comment by namdre** [comment]
The mode that is used to compute safe gaps (ACC,CACC) should of course also be considered during lane changing. However, the fcd-output should only refer to the mode that was used for car-following, hence we must guard before calling setParameter.

**Comment by schwamborn** [comment]
Got it, thanks for clarifying.

**Comment by behrisch** [comment]
@schwamborn I think those changes did not make it into the changelog for 1.8. Can you add them with a short description?

**Comment by schwamborn** [comment]
@behrisch Done!
