### ISSUE TITLE
Suggestion: NETEDIT save selection order in selection order

### ISSUE THREAD

**Issue by alexdawn** [eclipse/sumo#6701]
I'm producing cumulative travel time plot of selected routes within a model. In NETEDIT I'm making use of the selection tool to save out the edge ids to txt file, however it seems to have dumped them out alphabetically rather than in the order I selected them. Given it is always possible to sort alphabetically with just the list itself, it might be more valuable to save them out in the selection order, if the user is making use of the order of selection.

**Comment by namdre** [comment]
Edge selection in netedit uses a global map which does not preserve ordering.
Why don't you use the demand mode to define actual routes and save those?
This also saves clicks because you can define a route via sparse intermediate points and Netedit routes between them.

**Comment by alexdawn** [comment]
Ah yes great idea!
