### ISSUE TITLE
Trip merging issue,sort by depart time

### ISSUE THREAD

**Issue by Smiley4ever21** [eclipse/sumo#6704]
Hallo,

I have now two trip file generated seperately, one for LKW and the other for PKW, I want to merge them together. But when I copy one trip file into another, the simulation runs by the command sequence, not by the departure time. Is there a method in SUMO that I can sort my trip file by depart time? Or is there some tools can merge two trip file and then sort by depart time? Thank you.

**Comment by behrisch** [comment]
There is currently no tool achieving this directly but if, both files are sorted individually you can simply give them both as input to sumo. If not (and if they are not too big) you can load them as additional files where sorting does not matter. You can also pass them through the duarouter and generate trip output which has the additional benefit that you can check whether there is a connection from source to destination.

**Comment by Smiley4ever21** [comment]
Thank you for your reply.

I try to duarouter to generate route from both trips, and I tried two ways in command lines, both not possible, how can I use two trip files as input? Thank you a lot.

duarouter -n duisburg.net.xml --route-files duisburg_lkw.trips.xml --route-files duisburg_pkw.trips -o duisburg_.rou.xml

duarouter -n duisburg.net.xml --route-files uisburg_pkw.trips.xml duisburg_lkw.trips.xml -o duisburg_.rou.xml

**Comment by behrisch** [comment]
Just separate the two files with a comma ",".

**Comment by Smiley4ever21** [comment]
Wonderful! Thank you!
