### ISSUE TITLE
missing HBEFA3 emission coefficients

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#6707]
several emission classes have all zeros in their coefficient matrix for some pollutants.
some Examples:
* LDV - NOx
* LDV_D_EU2 - Fuel and CO2
* PC_G_EU2 - HC
* PC_D_EU4 - PM

**Comment by ArmelliniMG** [comment]
HC emissions for classes LDV_G_East and PC_G_East show much higher values than all other classes. It would be helpful to check the coefficients for these cases as well.

**Comment by behrisch** [comment]
Just wanted to mention that those deficiencies are at least partly known for a long time, see https://sumo.dlr.de/docs/Models/Emissions/HBEFA3-based.html

**Comment by namdre** [comment]
Current solution as proposed by Peter & Micha:
- update HBEFA version
-  recompute with more coefficients
- more thorough checking for implausible coefficients (i.e. all zeros)
- adding more classes (raw HBEFA classes) in addition to the clustered groups
- publish tools
