### ISSUE TITLE
ACC model keeps double minGap distance

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#6728]
The issue was already noted by @leoluecken https://github.com/eclipse/sumo/blob/ee4de48177a7236cc54f93dc549b815eefaca01c/src/microsim/cfmodels/MSCFModel_ACC.cpp#L179-L181

Changing it might cause additional collisions and would affect several project results. We should discuss this before changing it.

**Comment by schwamborn** [comment]
Also here:

https://github.com/eclipse/sumo/blob/ee4de48177a7236cc54f93dc549b815eefaca01c/src/microsim/cfmodels/MSCFModel_CACC.cpp#L232

**Comment by schwamborn** [comment]
Changing both locations results in several (additional) collisions and teleports in tests

- tests/sumo/cf_model/drive_in_circles/ACC
- tests/sumo/cf_model/drive_in_circles/CACC (cf. #4839)
- tests/sumo/cf_model/apparentDecel_emergencyDecel/avoid_collision/ (cf. #4889)

**Comment by namdre** [comment]
CACC does not show faulty minGap in our tests so the dubious line  232 must be compensated elsewhere (looks like it should be refactored).

**Comment by schwamborn** [comment]
Test suite tests/sumo/cf_model/drive_in_circles_steplength (cf. c70a0e95b7c75c35a1fa9799b96b74603482621d) added with smaller scenario and stepLength to account for CF models which benefit from lower actionSteplength (like ACC and CACC).
