### ISSUE TITLE
routeSampler.py: allow non-consecutive edgeRelations with explicit multi-edge sequence

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#6729]
using optional attribute `via`

**Comment by jane212** [comment]
Hi,
When I try to implement this new feature, I first got a parsing error:
` File "tools\routeSampler.py", line 155, in parseTurnCounts
    for edgeRel in interval.edgeRelation:
TypeError: 'NoneType' object is not iterable`
I have already formatted the edge relation file as shown in your test: [https://github.com/eclipse/sumo/blob/master/tests/tools/turndefs/routeSampler/via/input_turns.xml](url)
Could you please advise where this might go wrong? Thanks.

**Comment by namdre** [comment]
The released version 1.5 is already outdated.
Are you using the latest development version of routeSampler?
https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_development_version


Am Di., 10. März 2020 um 03:25 Uhr schrieb Tingting <
notifications@github.com>:
