### ISSUE TITLE
osmWebWizard.py :Failed to load net file in SUMO-GUI

### ISSUE THREAD

**Issue by Livinu** [eclipse/sumo#6731]
Hello all,

I tried to use the osmWebWizard.py to generate simulation network topology to be exported for NS3 simulation. However, the script failed to load the osm.net.xml [osm.net.txt file](https://github.com/eclipse/sumo/files/4283202/osm.net.txt)
 file with the following errors:
Loading net-file from '/path/to/sumo/tools/2020-03-03-14-39-36/osm.net.xml' ... 
Error: Attribute 'netOffset' in definition of a location is not of type PositionVector.
Error: Attribute 'convBoundary' in definition of a location is not of type Boundary.
Error: Attribute 'origBoundary' in definition of a location is not of type Boundary.
Error: Attribute 'speed' in definition of lane ':1102112672_0_0' is not of type float.
Error: Attribute 'length' in definition of lane ':1102112672_0_0' is not of type float.
Error: Attribute 'shape' in definition of lane ':1102112672_0_0' is not of type PositionVector.
Error: Shape of lane ':1102112672_0_0' is broken.
 Can not build according edge.
............
Here is the Log file [detailed sumoError.txt](https://github.com/eclipse/sumo/files/4283183/sumoError.txt)

# Versions:
 - Run on Linux Ubuntu 16.04
 - Sumo 1.4.0

I would like to ask how to deal with this conversion issue.

**Comment by namdre** [comment]
I can load your Reims network with sumo 1.4 just fine. What happens when you try to process the network with netconvert? 
`netconvert -s osm.net.txt -o test.net.xml`

**Comment by Livinu** [comment]
When I process the network with this ```netconvert -s osm.net.txt -o test.net.xml``` command,
I got just the below warnings:
Warning: Ambiguity in turnarounds computation at junction 'cluster_2341977906_278845620_6983029885'.
Warning: Ambiguity in turnarounds computation at junction 'cluster_350555696_6786609689_6983015082'.
Warning: Ambiguity in turnarounds computation at junction 'cluster_354541195_6786609688'.
Warning: Found sharp turn with radius 6.93 at the start of edge '-94957274#1'.
Warning: Found angle of 120.20 degrees at edge '31432324#3', segment 3.
Warning: Found sharp turn with radius 6.93 at the end of edge '94957274#1'.
Warning: Speed of straight connection '684800140_0->-684800142#0_0' reduced by 6.75 due to turning radius of 9.26 (length=10.31, angle=84.81).
Warning: Speed of straight connection '684800138_0->-684800140_0' reduced by 5.91 due to turning radius of 11.56 (length=13.12, angle=84.81).
Warning: Speed of straight connection '31695752_0->-31695756_0' reduced by 6.26 due to turning radius of 10.57 (length=1.60, angle=24.38).
Success.

However, when I load the test.net.xml with ```netedit``` or ```sumo-gui``` I got the same error as mentionned above.

**Comment by namdre** [comment]
what happens when you run `sumo -n osm.net.txt` ?

**Comment by Livinu** [comment]
I don't get any log.  The command do not produce any output, seems like it works.
```bash
 $ sumo -n osm.net.xml
 $
```

**Comment by namdre** [comment]
Did you build your sumo from source or install pre-built binaries from a package?

**Comment by Livinu** [comment]
I built it from source by cloning this repo as given in the readme:
```bash
git clone --recursive https://github.com/eclipse/sumo
```
P.S. The tools/traceExporter.py is able to export the FCD traces, even though the sumo-gui failed to load the .net.xml

**Comment by namdre** [comment]
what is the output if you run `sumo` without any arguments?

**Comment by namdre** [comment]
I'm fishing for a clue here... Can you define new networks in netedit, save them and load them with  'sumo -n ...'?

**Comment by Livinu** [comment]
I made just a simple net for test, I am not sure if it is enough for you to see a clue. You can tell me if the net elements are not enough.
```bash
../../bin/sumo -n testForNet.net.xml -r rou.rou.xml 
```
and got the output below:

Step #0.00 (0ms ?*RT. ?UPS, vehicles TOT 7 ACT 7 BUF 29)                      
  Step #29.00 (0ms ?*RT. ?UPS, vehicles TOT 36 ACT 0 BUF 0)

**Comment by namdre** [comment]
I'm stumped. Any ideas @behrisch ?
- xml parsing is working (or netconvert and sumo would produce the same errors)
- netedit is working (or you couldn't have created the network)
- sumo is compiled with all the right features
- yet, opening a gui seems to break xml parsing

**Comment by behrisch** [comment]
Is there any reason for this specific version? Could you please retest with the released 1.5.0 or 1.4.0 and/or send a build log?

**Comment by Livinu** [comment]
When using v1.5.0, it does not even reach the generation of the net file. It still asking the installation of PROJ-Library while the proj and proj-dev libraries are properly installed.
```bash
python osmWebWizard.py 
```
Opening in existing browser session.
Building scenario in '/..../sumo/tools/2020-03-12-18-11-59'
Downloading map data
200 OK
Converting map data
path-to/sumo/bin/netconvert: path-to/miniconda3/lib/libtiff.so.5: no version information available (required by /usr/lib/x86_64-linux-gnu/libpoppler.so.58)
Written configuration to 'osm.netccfg'
path-to/sumo/bin/netconvert: path-to/miniconda3/lib/libtiff.so.5: no version information available (required by /usr/lib/x86_64-linux-gnu/libpoppler.so.58)
Loading configuration ... done.
Error: Cannot import network data without PROJ-Library. Please install packages proj before building sumo
Quitting (on error).
path-to/sumo/bin/polyconvert: path-to/miniconda3/lib/libtiff.so.5: no version information available (required by /usr/lib/x86_64-linux-gnu/libpoppler.so.58)
Written configuration to 'osm.polycfg'
path-to/sumo/bin/polyconvert: /path/miniconda3/lib/libtiff.so.5: no version information available (required by /usr/lib/x86_64-linux-gnu/libpoppler.so.58)
Loading configuration ... done.
Error: Could not open net-file 'osm.net.xml'.
Quitting (on error).
Traceback (most recent call last):
  File "osmWebWizard.py", line 474, in build
    builder.build()
  File "osmWebWizard.py", line 288, in build
    self.edges = sumolib.net.readNet(os.path.join(self.tmp, self.files["net"])).getEdges()
  File "path-to/sumo/tools/sumolib/net/__init__.py", line 780, in readNet
    parse(filename, netreader)
  File "/usr/lib/python2.7/xml/sax/__init__.py", line 33, in parse
    parser.parse(source)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 105, in parse
    source = saxutils.prepare_input_source(source)
  File "/usr/lib/python2.7/xml/sax/saxutils.py", line 349, in prepare_input_source
    f = urllib.urlopen(source.getSystemId())
  File "/usr/lib/python2.7/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/usr/lib/python2.7/urllib.py", line 216, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 472, in open_file
    return self.open_local_file(url)
  File "/usr/lib/python2.7/urllib.py", line 486, in open_local_file
    raise IOError(e.errno, e.strerror, e.filename)
IOError: [Errno 2] No such file or directory: 'path-to/sumo/tools/2020-03-12-18-11-59/osm.net.xml'

Recovering
..

It is the same error with python 3.6.9


Note: the command ```sudo apt-get install cmake python g++ libxerces-c-dev libfox-1.6-dev libgdal-dev libproj-dev libgl2ps-dev swig``` shows that all the required packages are installed and updated.
I have uninstalled and re-installed the libproj-dev and  libproj, but nothing changed.

So I downloaded the v1.0.0  tar  and the osmWebWizard.py script works.

**Comment by behrisch** [comment]
I think it is a problem with anaconda which brings its own version of libraries and also modifies the library search path. Can you try to uninstall it and use a "vanilla" python?

**Comment by behrisch** [comment]
No further feedback so seems to be resolved.
