### ISSUE TITLE
duaIterate doesn' work on SUMO-1.5

### ISSUE THREAD

**Issue by aminissn** [eclipse/sumo#6750]
Somehow I can't use duaIterate.py anymore on SUMO-1.5. I get the following error:
..Sumo\tools\sumolib\options.py", line 35, in get_long_option_names m = reprog.search(line)
TypeError: cannot use a string pattern on a bytes-like object
I can use the same script on SUMO-1.3 though without any problems.

**Comment by namdre** [comment]
fixed in [52529f9c34b7e17a282ae63e9]
