### ISSUE TITLE
How could I avoid collision like this?

### ISSUE THREAD

**Issue by Sheldon-Zhou1997** [eclipse/sumo#6757]
I don't know how to avoid collision in this two edges.Thank you

**Comment by Sheldon-Zhou1997** [comment]
![2020-03-07 15-25-04屏幕截图](https://user-images.githubusercontent.com/52645665/76144434-52a64280-60bb-11ea-9e3f-fec5cae0e45e.png)
![2020-03-07 15-23-49屏幕截图](https://user-images.githubusercontent.com/52645665/76144435-54700600-60bb-11ea-8067-13f1dae738eb.png)

**Comment by namdre** [comment]
Your network specifies that both roads have right-of-way which is obviously unsafe. You could either
- make one road yield (set junction type to 'priority' and don't set any connection attributes). The road with the lower priority value will yield.
- set the junction type to 'zipper' for a "fair" conflict resolution

**Comment by Sheldon-Zhou1997** [comment]
Which edge's waiting time does traci.edge.getWaitingTime() return? Edge in pic1 or pic2?Thank you!
![pic2](https://user-images.githubusercontent.com/52645665/76159284-c139dd80-6159-11ea-9b99-ca8b6b94b7d5.png)
![pic1](https://user-images.githubusercontent.com/52645665/76159286-c303a100-6159-11ea-9eb7-79ea6fac05a4.png)
I've signed them by red lines.

**Comment by Sheldon-Zhou1997** [comment]
![pic2](https://user-images.githubusercontent.com/52645665/76159308-1544c200-615a-11ea-974f-6ddee1119ab2.png)
![pic1](https://user-images.githubusercontent.com/52645665/76159309-1675ef00-615a-11ea-9589-1fb6d430020e.png)

**Comment by namdre** [comment]
1) do not post unrelated questions in the same issue
2) post usage questions on the mailing list. The issue tracker is for bugs and enhancements (https://sumo.dlr.de/docs/Contact.html)
2) each edge has a unique id and this is what determines the value returned by edge.getWaitingtime.
