### ISSUE TITLE
How to catch "not be able to depart" exception?

### ISSUE THREAD

**Issue by ykwd** [eclipse/sumo#6758]
Currently I am integrating c++ libsumo into our project. When inserting a vehicle with a given speed via Vehicle::add function, the inserting may fail with the following message:

Error: Vehicle 'xxx' will not be able to depart using the given velocity (unpriorised junction too close)!

or:

Error: Vehicle 'yyy' will not be able to depart using the given velocity (junction too close)!

My intention is that if the speed is too high and the inserting fails, I can decrease the speed and try again. But besides the above message which is printed on screen, there is no exception thrown from Vehicle::add. So my question is, how can I detect the inserting failure so that I can try inserting again.

ps: I guess the error message comes from checkInsertions in src/microsim/MSVehicleTransfer.h

**Comment by namdre** [comment]
Insertions (and insertion failure) do not happen immediately after calling vehicle.add() so there is no good way for raising an exception. Here are things you can do:
- check in the next simulationStep whether the vehicle is on the road (getRoadID()) and re-insert if not
- set departSpeed="max" so the vehicle will automatically lower it's speed to the highest possible value that makes insertion succeed
- set sumo option --ignore-route-errors to allow insertion with unsafe speed
