### ISSUE TITLE
mismatching connection info in letfhand network

### ISSUE THREAD

**Issue by ZoltanBaksa** [eclipse/sumo#6760]
Hi,
I use netedit v1_5_0+0485-872778a9d6 to edit a lefthand network. In my network, there is a junction, where a connection binds a two laned street section with a one laned street with a right turn. Visually the rightmost lane has the connection. If I check the connections information pane, it shows from lane 0 to lane 0, although the start lane has the index 1. If I check the same connection in the net.xml, it contains the correct informations, and the simulation is also running without problems, where I have a detector on the internal lane.

**Comment by namdre** [comment]
I cannot reproduce this but I'm also not sure what you mean by "connections information pane".
- When I look at the connection in inspect mode it shows correct fromLane and toLane values
- When I right-click the connection to show its properties, I also see the correct information.
Can you send me an example network and tell me which connection to look at?

**Comment by ZoltanBaksa** [comment]
Connection info pane is the information seen in the left side panel when I left click on the connection in inspect mode. 

I have another junction, where the mismatch occurs at straight going lanes, where the start lane has 3 lanes.The leftmost lane has two connections to turn left to a two laned street. The info pane shows fromLane 0 toLane 0 and fromLane 1 and toLane 1. The middle lane has one straight going connection to a one laned street. The info pane shows fromLane 0, toLane 0.
I'll send a picture, and also a network in separate email.

**Comment by ZoltanBaksa** [comment]
I could reproduce the problem with V1_5_0+0568-56b7eca441
The same problem is visible if I load a network with and without internal lanes.
I also found one other case, where a one laned street is connected to a three laned street (to the leftmost 2 lane) and the connection information in this case shows fromLane 2, toLane 2, see connection from 4976043.30 to 24687152#0 in the sent network.
It seems the fromLane information mirrors somehow the toLane information in the not editable field

**Comment by ZoltanBaksa** [comment]
Works correctly, thanks
