### ISSUE TITLE
How to get halting numbers in zipper-type junction

### ISSUE THREAD

**Issue by Sheldon-Zhou1997** [eclipse/sumo#6765]
I want to get total halting numbers in this road.
But there is a zipper-type junction,in this road and traci.edge.getLastStepHaltingNumber() can only detect edges.So I can't get the halting number in the zipper-type junction.What should I do? Thank you!

**Comment by Sheldon-Zhou1997** [comment]
![2020-03-09 22-38-01屏幕截图](https://user-images.githubusercontent.com/52645665/76226089-57ecc400-6258-11ea-9457-8c35bcdeee76.png)

**Comment by namdre** [comment]
the junction contains "internal edges" for which you may also retrieve all the data. See https://sumo.dlr.de/docs/SUMO-GUI.html#investigating_internal_edges_and_lanes

**Comment by Sheldon-Zhou1997** [comment]
Sorry, I'm still not understand it. How should I get "internal edges" ? By sumo-gui or XML?

**Comment by namdre** [comment]
You can use SUMO-GUI to show the ids of iternal edges (read carefully the description in the link I sent). Then you can use those ids in your TraCI query. You can also use TraCI to find out which internal edges are used to connect different "normal" edges. But first you should use SUMO-GUI to increase your understanding of the concept.
