### ISSUE TITLE
import bus lane restrictions from OSM

### ISSUE THREAD

**Issue by ambuehll** [eclipse/sumo#6767]
It seems as if dedicated bus lanes allow private vehicles. OSM has some tags which would allow identifying such lanes and reducing the number of lanes accessible to cars. I guess the OSM tagging not really unified.
Nonetheless, there are some tags, e.g: 
<tag k="vehicle:lanes:backward" v="no|yes|yes"/>

		<tag k="bus:lanes:forward" v="designated|"/>

		<tag k="psv:lanes:forward" v="yes|"/>

		<tag k="bus:lanes:backward" v="designated|"/>`
which provide information regarding the number of lanes dedicated to cars.

[files](https://drive.google.com/open?id=1dfs31I5hMuSeajkrKkx6OEquz3WBhzFM)
(check way id 145204590, for example)

Thanks!

**Comment by namdre** [comment]
There are three tagging schemes for bus lanes (https://wiki.openstreetmap.org/wiki/Bus_lanes).
Currently, netconvert only supports the busway scheme

**Comment by namdre** [comment]
also somewhat related to #10650

**Comment by behrisch** [comment]
is fixed now with 40e05193c05c3a2d441cb2e859897aefa9ff166b but needs the option `--osm.lane-access`

**Comment by behrisch** [comment]
@ambuehll Just one more question concerning the Seilergraben example edge (145204590). It has a trolley wire _and_ a tram edge running parallel (217408202). Is this correct? (Are there rails?)

**Comment by ambuehll** [comment]
Thanks!
Seilergraben has 4 lanes in total: 2 lanes inbound, 2 lanes outbound. in each direction, there is a lane for cars (the right lane in direction of travel) and one lane for bus **and** trams. This lane has tram tracks and is used as a bus lane at the same time.
I hope that clarifies things. Essentially, how I see the OSM-tagging in Zurich, it's "psv:lanes" if there is something else than a bus (either a tram or a bus and a tram) and a "bus:lanes" when it's only for buses.

**Comment by behrisch** [comment]
Thanks for the answer, I just could not imagine that you can have a trolley bus and a tram on the same track but my trolley bus experience is very limited ;-).
The way it is currently implemented psv:lanes maps to taxi and bus while bus:lanes maps only to bus. Tram is always imported from the tracks. Are taxis allowed on Zurich's psv and/or bus lanes?

**Comment by ambuehll** [comment]
ha! good question, the answer is "it depends". so I am not quite sure actually how this is tagged in OSM by the Zurich community.
