### ISSUE TITLE
How to manually control/move multiple vehicles parallel/at the same time? 

### ISSUE THREAD

**Issue by siqi95** [eclipse/sumo#6778]
Hi, 
So the situation is I have prefined the route in route.xml, and I had the code to overwrite the route using moveToXY() command, it works fine for one running vehicle. But I'm not sure, is it possible to do the same thing for multiple vehicles at the same time? For example, inside the `while traci.simulation` I had a for loop to fill the x, y position for the moveToXY(x,y) command. But I cannot really do an outer for loop to loop through all the vehicles because it's not gonna happen at the same time. Any ideas would be highly appreciated! Do I need to do multi-threading for this? 

Thank you

**Comment by namdre** [comment]
I think the easiest solution is to asynchroneausly collect positions of all vehicles (e.g. with multiple threads) and then send synchronized moveToXY commands in the main traci loop.

Alternatively, you could use a multi-client approach but that would for each client to wait unti all other clients have send their update for that step.

**Comment by siqi95** [comment]
Hi ,
So as suggested, in the `traci.simulation.getMinExpectedNumber` loop, I used two threads constantly sending commands to different vehicles, however ,vehicles are all placed here  (-1073741824.0, -1073741824.0) initially which is not even in the map, also it wont move using the moveXY command. Do u have any ideas what's going on with it?

**Comment by namdre** [comment]
It won't help to send commands from different threads. TraCI is not thread-safe that way.
Instead use a synchronized data-structure to collect commands (e.g. as tuple(vehID, x, y, angle,...) and then use a single thread to call simulationStep and send all the moveToXY commands.

The value of (-1073741824.0, -1073741824.0) denotes the "invalid location".

**Comment by siqi95** [comment]
Hi, 
So I tried something like this: 
`
while traci.simulation.getMinExpectedNumber() > 0:
      def func1(queue):  # to read the shared varible queue
      def func2(queue): # to add tuple (vehID, position) to variblae queue
           for()
           #for loop to keep adding to queue
      
      _thread.start_new_thread(func2, (queue, ))
       _thread.start_new_thread(func1, (queue, ))
 
`

I want to have one thread keeping add to queue and another thread to keep reading and sending traci command, however, I found it impossible to achieve synchronize, code will finally fall in func2, and func1 seems only can be used once at the very beginning. Also, the position is still invalid. I'm not sure whether the place I put thread is wrong(cuz I assume it has to be in traci.simulation loop? )  I spent one day on this, but still couldn't figure out why... If you have any idea on this, that would be much much appriciated！！！ thank you so much

**Comment by namdre** [comment]
what can I say... multithreading is hard. Unfortunately, I don't have time to debug this for you. I recommend logging the moveToXY commands with all their arguments that you are actually sending to figure out if the arguments are correct.
