### ISSUE TITLE
Detecting parked vehicles when using context subscription

### ISSUE THREAD

**Issue by Domsall** [eclipse/sumo#6785]
Dear all,
I'm subscribing to a vehicle to detect other vehicles in range. This works perfectly with driving vehicles, but not with parked ones. The vehicles don't get detected, although they are still in the network (stop on route). Is there a reason it works this way or can this be changed to account for all vehicles that are "running" in the simulation and are in range? Or has this issue already been solved as I am not working with the newest version?!
Thanks in advance!

**Comment by behrisch** [comment]
If the parking attribute of the stop is not set, the vehicle should be detected. Whic sumo version do you use?

**Comment by namdre** [comment]
I think it makes sense to also detect vehicles with `parking="true"` because these vehicles are visible as well. This currently does not work because vehicles are found by looking up lanes in the rtree and retrieving their vehicles.

**Comment by Domsall** [comment]
Is it something that will take a while to implement due to the structure of the MSLane class and parking vehicles not being on the lane? Or is it easier/possible to create another Tree for parkingAreas and their vehicles?!
I would like to use the enhancement soon and am thinking about other solutions and/or changing the code myself. For latter I should of course understand the underlying logic and not change parts that are needed elsewhere.
