### ISSUE TITLE
Car Follower Model: Calculating the next velocity for the follower car

### ISSUE THREAD

**Issue by wmustafaAwad** [eclipse/sumo#6791]
Hi There .. 
I hope this is the right place to look for help regarding SUMO code logic. If not, please redirect me.

Using SUMO's Python API, throughout. 

I have been trying to replicate the logic that SUMO implements to have a follower car follow a leading car.  (I have checked #2548 and [KraussOrig1.cpp](https://sumo.dlr.de/doxygen/d7/d4b/_m_s_c_f_model___krauss_orig1_8cpp_source.html), but I am afraid I was in over my head and couldn't figure out the code's logic)
I need to do this to find if a certain acceleration is feasible/infeasible to apply on the following car, before actually applying it (any method to check for longitudinal feasibility would totally solve my problem, similar to checking lane 
 change feasibility in [couldChangeLane](https://sumo.dlr.de/pydoc/traci._vehicle.html#VehicleDomain-couldChangeLane) function, for lateral feasbility).

# Theory 
Specifically, I realize (from [here](https://sumo.dlr.de/docs/Definition_of_Vehicles,_Vehicle_Types,_and_Routes.html#default_krauss_model_description)) that SUMO uses an edited version of the Krauss car follower model by default. The equation for the car-follower model can be found on page 34 of the [linked document](https://sumo.dlr.de/pdf/KraussDiss.pdf) in the SUMO documentation as follows:

![image](https://user-images.githubusercontent.com/40274507/76559006-02f2bd00-64a7-11ea-9250-40d37dc8748e.png)

I have been trying to use several resources (like page 3 [on this paper](
https://www.researchgate.net/profile/Zhexin_Xu/publication/282987750_Research_on_car-following_model_based_on_SUMO/links/5c4d398fa6fdccd6b5cc29e4/Research-on-car-following-model-based-on-SUMO.pdf)).. which all seem to agree on the following equations for the Krauss model:

![image](https://user-images.githubusercontent.com/40274507/76559606-1fdbc000-64a8-11ea-871f-1090238cd616.png)

# Code : 
I implemented the below function to replicate the logic of the Krauss model (please guide me if I have done something wrong here):

 ```
def  Krauss_get_vsafe(vf, tr, g, vl, b):
        '''
        :param vl: velocity of nearest leading vehicle
        :param g: gap between current agent and nearest leading vehicle
        :param tr: time reponse delay (tau in SUMO, entered in the vtype inside rou.xml) see: https://sumo.dlr.de/docs/Car-Following-Models.html#tau
        :param vf: velocity of the following car (i.e. my velocity, the car for which we want to calculate vsafe)
        :param b: maximum decleration magnitude(i.e. a positive value) of the follower(i.e. me) vehicle

        :return vsafe: safe velocity to seek by follower(i.e. me) vehicle
        '''
        vsafe =  vl + ( (g-vl*tr) / ( ((vl +vf)/(2*b)) + tr )  )
        return vsafe

```

The output of `Krauss_get_vsafe` function (i.e. vsafe) is then inputted to the following function to determine the expected next velocity (I do not input this velocity nor vsafe to SUMO, it's just printed
to see if I have got the numbers right.. which -to no surprise- I haven't..):

```
    def get_next_velocity(self, vsafe):
        '''
        :param vsafe: safe velocity of the car

        :return v_next: expected next speed
        '''
        v_next = min(self.max_speed, self.spd + self.accel , v_safe) #self.accel: max positive acceleration

        return v_next
```

# Numbers  and XML files

For my test case, I have 2 vehicles. First, an agent (leading vehicle) with the following properties:
`      <vType id="Ego" length="2.0" maxSpeed="5.0" sigma="0.0" color='0,0,1' accel = "1.0" decel = "1.0"  emergencyDecel="1.0" minGap = "2.5" />
 `
and an Emergency vehicle (Following Vehicle) with the following properties:
`      <vType id="Emergency" length="2.0" maxSpeed="10.0" sigma="0.0" color='1,0,0' depart= "10.0" accel = "2.0" decel = "2.0" emergencyDecel="2.0" minGap = "2.5"/>
`
The emergency vehicle follows the Ego (agent) vehicle, and both are in the same lane. I have functions that measure observations from the simulation environment and print them to my console, every step, and an excerpt from the output is as follows:
```
#format: step number, 
# gap:  between two agent
# vl:  velocity of agent (Ego--leading), 
# velocity of Emergency Vehicle (vf --follower), 
# v_next Expected velocity (not the actual, but the one predicted using my faulty Krauss model with vf, vl, and gap as input)

12,gap: 33.099999999999994, vl: 3.0, vf: 10.0, v_next: 10.0
 13,gap: 26.1802, vl: 3.0, vf: 9.919800000000002, v_next: 8.480017494296622
 14,gap: 20.644360000000006, vl: 3.0, vf: 8.53584, v_next: 7.5428789173935895
 15,gap: 16.35852, vl: 3.0, vf: 7.285840000000001, v_next: 6.740352684896372
 16,gap: 13.144139999999993, vl: 3.0, vf: 6.214380000000002, v_next: 6.0706366851868925
 17,gap: 10.929759999999987, vl: 3.0, vf: 5.21438, v_next: 5.596860421896155
 18,gap: 9.45350666666667, vl: 3.0, vf: 4.476253333333334, v_next: 5.249342700695582
 19,gap: 8.477253333333323, vl: 3.0, vf: 3.9762533333333345, v_next: 4.996037506422953
 20,gap: 7.989126666666664, vl: 3.0, vf: 3.4881266666666684, v_next: 4.902771324272081
```

The expected velocity by my model `(v_next)` is clearly wrong, and actually does not saturate at vl (3.0 in this case) but at a value a bit larger than it _(at 4.800, exactly)_ , which is again, wrong and opposes the "car following" meaning.

My main best guess regarding why my model is faulty is:
I have calculated the gap wrongly. The current gap calculation returns the difference in value of the `traci.vehicle.getLanePosition(vehicle.ID)` for each vehicle from `Ego` and `Emergency`. However, I realize that some other factors that I should consider are: `minGap` and vehicle `length` , but I don't know how to incorporate them in my calculations for the gap. Any help with that, specifically?

Also, for b (maximum decleration) in the Krauss model, should I input the maximum decleration for the leading or the following vehicle ?

**Comment by namdre** [comment]
in the latest development version you can use traci to call the carFollowModel functions directly (#3361). (updated downloads available **tomorrow** at https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_development_version
