### ISSUE TITLE
Enhancement: control simulation when additional window is active

### ISSUE THREAD

**Issue by ZoltanBaksa** [eclipse/sumo#6818]
Hi,
I use currently only one monitor during simulation. When I use phase tracking at a time loss based traffic light, the phases show up in an additional window, but I have to switch between windows to step-run the simulation in the gui and to check the phases. I would like to use the Ctrl+d, Ctrl+s or Ctrl+a combinations when one of the additional windows is active.

**Comment by namdre** [comment]
On Linux, most window managers have an option to put windows 'always on top'. I use this the place a tracker window on top of the simulation, then switch the focus back to the simulation while keeping the tracker visible.
On windows, I shrink the sumo-gui window and place the tracker window next to it so I can switch back focus without hiding the tracker.

**Comment by ZoltanBaksa** [comment]
I use windows on the company laptop. The resizing is a good idea, although if I do it, the details are not that visible, because the observation area is a bigger junction.

**Comment by namdre** [comment]
consider https://www.howtogeek.com/196958/the-3-best-ways-to-make-a-window-always-on-top-on-windows/

**Comment by ZoltanBaksa** [comment]
Thanks for the hint, DeskPins works as expected
