### ISSUE TITLE
Dynamically change priority of an edge 

### ISSUE THREAD

**Issue by ali-danesh** [eclipse/sumo#6820]
Hi,
I'm beginner in Sumo. Is there any way to dynamically change the priority of an edge during simulation with TraCI or other methods?
As far as I know, we can set the priority of each edge in the beginning. but not during simulation.
thanks

**Comment by namdre** [comment]
Edge priority cannot be changed at runtime. However, the priority of the edge is mostly used to determine right-of-way at intersections and there is a way to change the right-of-way dynamically. It's called "traffic light". You can customize the traffic light program to define any right of way timings that you desire.
