### ISSUE TITLE
Can't download data from OSM Web Wizard

### ISSUE THREAD

**Issue by idmdvan** [eclipse/sumo#6832]
Hi! When I run OSM Web Wizard, it seems that it can't download imagery from OSM. I just see pink boxes full of Xs. When I tried it with Microsoft Edge, it warned me socket connection failed. However I know I have a connection with OSM because I can search and find places... does anybody know what might be happening? thanks!

**Comment by namdre** [comment]
The OSM servers do not cache imagery for the whole world but only for the parts the people have looked at recently. When you look at places that are not in the cache then it take a while to compute the images from the database. Depending on the number of simultaneous users, your image requests may fail. Using a different zoom level often helps.

**Comment by idmdvan** [comment]
Hello Jakob, and thanks for your answer. However, I can't even see at Berlin's downtown default image. It is not a problem about OSM, it is about the  connection between the script and OSM. Could you reopen the issue so maybe somebody else can help me? Thanks.

**Comment by namdre** [comment]
Did you try with firefox yet?

**Comment by angelobanse** [comment]
Hi @idmdvan please try it using Firefox or IE. 

If you explicitly want to use Microsoft Edge with osmWebWizard, run in a command prompt (as admin!) 
`CheckNetIsolation LoopbackExempt -a -n=Microsoft.MicrosoftEdge_8wekyb3d8bbwe`
Read more here: https://answers.microsoft.com/en-us/edge/forum/all/edge-4015063-websocket-error-12029/0ca51068-5196-4c16-9484-bc92b5ad457c

I have reproduced your connection error and i can attest that the above command fixes it.
