### ISSUE TITLE
consider: edgeData density output may be more useful as vehs/km/lane rather than vehs/km/edge

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#6840]
it think the current output makes it hard to interpret edgeData between edges with different lane numbers because the lane number would have to be retrieved from some other dataset.

**Comment by ambuehll** [comment]
absolutely agreed.

**Comment by behrisch** [comment]
I agree, but we should probably not change the meaning of an existing attribute but rather add a new one.

**Comment by namdre** [comment]
how about laneDensity ?
