### ISSUE TITLE
computeSpeedLat doesn't work

### ISSUE THREAD

**Issue by HolyBugger** [eclipse/sumo#6843]
Hello, friends!
I changed the code of computeSpeedLat in MSAbstractLaneChangeModel.cpp and rebuild SUMO. But when I run the SUMO in a lane change situation, the new code doesn't work, even some print-scripts output nothing. Could you figure out the possible reason?

**Comment by namdre** [comment]
Sorry, you're on your own when debugging your own code. I recommend using a debugger to figure out what is happening.

**Comment by HolyBugger** [comment]
In what situations will the computeSpeedLat be called with a default laneChangeModel?

**Comment by namdre** [comment]
only when sumo option --lanechange.duration is set (lanechange will be instant otherwise).
