### ISSUE TITLE
traci.vehicle.getFollowSpeed error on macOS

### ISSUE THREAD

**Issue by Abdulhady-Feteiha** [eclipse/sumo#6845]
I installed the nightly build of past 19 March on my macOS Mojave 10.4.6. It worked perfectly like the stable SUMO distribution. However, when I try using traci.vehicle.getFollowSpeed, it fails with the following error:

Error: Answered with error to command 0xa4: Get Vehicle Variable: unsupported variable 0x1c specified
Traceback (most recent call last):

    follow_speed = traci.vehicle.getFollowSpeed(agent.ID, agent.max_speed, distance_to_leader, leading_vehicle.spd, agent.max_decel, leading_vehicle.ID)
  File "/usr/local/lib/python3.7/site-packages/traci/_vehicle.py", line 755, in getFollowSpeed
    return self._connection._checkResult(tc.CMD_GET_VEHICLE_VARIABLE, tc.VAR_FOLLOW_SPEED, vehID).readDouble()
  File "/usr/local/lib/python3.7/site-packages/traci/connection.py", line 158, in _checkResult
    result = self._sendExact()
  File "/usr/local/lib/python3.7/site-packages/traci/connection.py", line 108, in _sendExact
    raise TraCIException(err, prefix[1], _RESULTS[prefix[2]])
traci.exceptions.TraCIException: Get Vehicle Variable: unsupported variable 0x1c specified
Error: tcpip::Socket::recvAndCheck @ recv: peer shutdown
Quitting (on error).
sumo(14513,0x1032155c0) malloc: Incorrect checksum for freed object 0x7f8b2ac366e0: probably modified after being freed.
Corrupt value: 0x0
sumo(14513,0x1032155c0) malloc: *** set a breakpoint in malloc_error_break to debug

It's worth noting that the same code perfectly runs on my colleague's Windows 10 OS.

**Comment by namdre** [comment]
Most likely there is still an older version of sumo somewhere on your system and your traci script is starting that version. You can check this by writing any output file with sumo started from your script  (-i.e. summary-output) and the checking the version info the in output file header.
