### ISSUE TITLE
GDAL changed default axis order in 3.0

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#6857]
this invalidates all coordinate transformations from shapefiles. See https://github.com/OSGeo/gdal/blob/release/3.0/gdal/MIGRATION_GUIDE.TXT#L12 for a fix

**Comment by namdre** [comment]
was already reported by user: #6596

**Comment by behrisch** [comment]
@namdre But he never sent a sample, did he?

**Comment by namdre** [comment]
@behrisch Unfortunately, no.

**Comment by behrisch** [comment]
work continues in #6936

**Comment by vishalmhjn** [comment]
Getting this error when using Polyconvert (SUMO 1.5.0). I think it might be related
`Error: SUMO was compiled without GDAL support.`

OSX 10.15.4

**Comment by namdre** [comment]
GDAL is an optional dependency. If you need this, make sure that the dev package (i.e. libgdal-devel) is installed when building sumo.

**Comment by vishalmhjn** [comment]
Thanks, So I guess using binaries is not an option. Build I should?

**Comment by behrisch** [comment]
Yes
