### ISSUE TITLE
Netconvert failed to convert pt_stop file

### ISSUE THREAD

**Issue by Shiyunyang-seu** [eclipse/sumo#6862]
Hi, I used the sumo version 1.3.1 and followed this step: https://sumo.dlr.de/docs/Tutorials/PT_from_OpenStreetMap.html. But, compared to my input osm file, the output pt_stop and pt_line file  lack many bus stops which should be in  the osm file.
![pt_stop(lack many stops)](https://user-images.githubusercontent.com/55737075/78227797-6ac58200-7500-11ea-808e-da726b72aa99.png)
![osm file (many other stops exit but can not be converted)](https://user-images.githubusercontent.com/55737075/78227810-6ef19f80-7500-11ea-8b37-d13fdd65ce2f.png)
![errors](https://user-images.githubusercontent.com/55737075/78227825-7749da80-7500-11ea-9104-679201ca733e.png)

**Comment by namdre** [comment]
This due to issues with the older version. Please upgrade to sumo version 1.5

**Comment by Shiyunyang-seu** [comment]
> This due to issues with the older version. Please upgrade to sumo version 1.5
I tried to use sumo 1.5, but the problem still exits. In the original osm file, there is about 178 bus stops, but in the pt_stop file created by netconvert, only two are converted.

**Comment by namdre** [comment]
Please attach a minimal osm input file for reproducing the issue (cut down the area so that at least one bus stop is missing but preferably not all of the 178).

**Comment by Shiyunyang-seu** [comment]
> Please attach a minimal osm input file for reproducing the issue (cut down the area so that at least one bus stop is missing but preferably not all of the 178).

Thanks for your suggestion.
I download a smaller input file(see the figure), but this time, no bus stop was built. Whether it is a command error, or whether there are other methods to extract the bus stop and  line information in the OSM file in batches. Thanks a lot.
![osm file](https://user-images.githubusercontent.com/55737075/78260744-e3dccd80-7530-11ea-997e-c9197d05ed72.jpg)
![processing](https://user-images.githubusercontent.com/55737075/78260753-e7705480-7530-11ea-8ae1-ccd0c6037fec.png)
![busstop](https://user-images.githubusercontent.com/55737075/78260796-f35c1680-7530-11ea-9aee-d1429b2575c8.jpg)

**Comment by namdre** [comment]
You have attached screenshots but I require an osm **file** attachment (it should be in a .zip archive in order to be accepted by github).

**Comment by Shiyunyang-seu** [comment]
> Please attach a minimal osm input file for reproducing the issue (cut down the area so that at least one bus stop is missing but preferably not all of the 178).

Thanks a lot.
[bus.zip](https://github.com/eclipse/sumo/files/4421805/bus.zip)

**Comment by namdre** [comment]
Thank you for the example. The public transport lines were defined with a reduced style (only stop platform locations were included and no vehicle stop positions). The updated version of netconvert now supports the reduced style as well but issues a warning for it. You can obtained updated binaries tomorrow at https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_development_version

**Comment by Shiyunyang-seu** [comment]
> Thank you for the example. The public transport lines were defined with a reduced style (only stop platform locations were included and no vehicle stop positions). The updated version of netconvert now supports the reduced style as well but issues a warning for it. You can obtained updated binaries tomorrow at https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_development_version

Thanks for your answer！
