### ISSUE TITLE
Visualization problem after adding polygon and poi

### ISSUE THREAD

**Issue by ajid951125** [eclipse/sumo#6865]
![image](https://user-images.githubusercontent.com/33246398/78337530-0cfe6c00-75cc-11ea-9374-777458197baf.png)

Sorry for asking such amateur problem but how can I remove the numbers? Thank you.

**Comment by angelobanse** [comment]
Hi, just open the Visualization settings menu (clicking on the ![](https://sumo.dlr.de/docs/images/Colorwheel.gif) icon) and uncheck the "show id" option wherever it is active.

**Comment by angelobanse** [comment]
![Unbenannt](https://user-images.githubusercontent.com/16121932/78348287-0f4bd080-75a2-11ea-9baf-751f1933002a.PNG)

**Comment by namdre** [comment]
Sorry, but the above answer is incorrect. It looks like you are using a developer version with debugging features enabled.
The affected version was available for a brief time recently. These numbers cannot be switched of using the Options.
Updating to the latest development version should resolve the issue (https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_development_version)
