### ISSUE TITLE
Flickering Positions of Vehicles

### ISSUE THREAD

**Issue by repa1030** [eclipse/sumo#6867]
Hello,

i am using SUMO combined with a game engine (Unity) to generate and manage the traffic. The simulation time step is 0.04s. As SUMO does not always run in real time, I calculate the "real" velocity of the vehicles inside Unity. Because of that I noticed huge jumps of the vehicle positions that are already exist in SUMO. The figure below shows the derivation of position in x direction of a single vehicle when using TraCIs getPosition(). Is the small simulation step causing those flickering/noise? What could be the problem?

![delta_x](https://user-images.githubusercontent.com/54360863/78345899-90a16400-759e-11ea-9689-2b16cd6271eb.png)

**Comment by namdre** [comment]
Are these jumps from one simulation step to the next or do they occur over multiple steps?
What are the labels of your plot? If you are using option --no-internal-links (in netconvert or sumo) then vehicles "jump" across junctions.

**Comment by repa1030** [comment]
Yes these jumps are from one step to the next.
x-axis is simulation step, y-axis is delta x, based on previous step, in meter.
I do not use the option --no-internal-links and this also happen on one single edge (without any junction).

**Comment by namdre** [comment]
I suspect numerical issues when converting the vehicle position from their 1-dimensional lane coordinates to x,y-coordinates.
- is the edge straight?
- what is the magnitude of the absolute x,y values? (There are known "flickering" issues in large networks due to numerical inaccuracy)
- try plotting the value of vehicle.getDistance() so see whether it is smooth (this gives the 1-d coordinate).

**Comment by repa1030** [comment]
* This edge was a curve with 30 degrees, but the same behaviour is on a straight edge.
* The magnitude of the plotted figure is between (0, 0) and (300, 700)
* If I plot a figure with getDistance() it looks much better. No flickering at all. x-Axis is simulation step, y-Axis is the getDistance() value.

So is there a possibility to get more accurate x,y-Positions?
![getDistance](https://user-images.githubusercontent.com/54360863/78528603-08aa9c80-77e0-11ea-826b-f442c26a3e16.png)

**Comment by namdre** [comment]
Possibly the edge has a corrupted geometry. This could happen when sampling with a high resolution from some kinds of opendrive-parameterized-curves. Try resampling your network with the option
`netconvert -s old.net.xml --geometry.min-dist 5 -o new.net.xml`
and run your experiment again on that network.

**Comment by repa1030** [comment]
I tried the command and it changed some edges in the network definition, but there is still flickering of 0.1...0.2m of the positions which is pretty high I think. The network is also not that complex, it is just a circuit but I used junctions instead of geomtry points. Could this cause the issue? 
![grafik](https://user-images.githubusercontent.com/54360863/79196827-088a4c80-7e31-11ea-9ce6-b84c478a456f.png)

**Comment by namdre** [comment]
I'm note sure. Can you attach the .net.xml file (zipped) so I can look at it myself?

**Comment by repa1030** [comment]
Of course! Thank you! :)

[circuit.zip](https://github.com/eclipse/sumo/files/4474709/circuit.zip)

**Comment by namdre** [comment]
The junctions are the reason:
All lanes of an edge must have the same length (from the point of view of the simulation vehicle) regardless of curvature to satisfy a fundamental constraint of the sumo lane-changing module. This introduces a length/geometry mismatch which is usually negligible. (visible when coloring edges 'by given length/geometrical length'). When there are lots of junctions, the curvature is concentrated in the short junction-internal edges which causes higher mismatch.
If you reprocess the network with  `netconvert -s circuit.net.xml -R -o circuit2.net.xml` the flickering should go away.
