### ISSUE TITLE
A encoding problem in ptlines2flows.py

### ISSUE THREAD

**Issue by Shiyunyang-seu** [eclipse/sumo#6868]
Hi, I follwed the https://sumo.dlr.de/docs/Tutorials/PT_from_OpenStreetMap.html to create PT schedules and travel time. When I utilized ptlines2flows.py, a encoding problem occursed. I thought maybe the Chinese characters in the XML file, but they are all of string type.  I attached an OSM file for your convenience. Thanks a lot.

![gbk problem](https://user-images.githubusercontent.com/55737075/78420393-565cc300-7681-11ea-89b4-43fc2e32dcdf.png)
[map.zip](https://github.com/eclipse/sumo/files/4430852/map.zip)

**Comment by namdre** [comment]
I've tried with python2.7 and python3.8 on linux (ubuntu) as well as windows10 and could not reproduce the encoding error.
Can you attach the network, stops and ptline file for me to compare with my own version?

**Comment by Shiyunyang-seu** [comment]
[map_net.zip](https://github.com/eclipse/sumo/files/4431773/map_net.zip)
Thanks for your answer. I got the network, stop and ptline file by netconvert(the lastest version last night and version 1.5.0), error reported in both versions of the file.

**Comment by namdre** [comment]
The files are identical to the ones I have been using for my tests. Since it's working on two different machines for me, the issue might be specific to your setup. Can you do a test on a different computer or operating system?

**Comment by Shiyunyang-seu** [comment]
Thanks for your answer. I used two different computers, but they had the same error report. But I tried the version sumo 1.3.1, then no error reported.

**Comment by namdre** [comment]
However, the 1.3.1 export has fewer stops which probably accounts for the difference.
- What version of windows did you use one the two computers?
- Can you try removing <busStop> elements from the stops file one by one to see which line is causing the issue?
- After having identified the line(s) that are causing the issue, can you try removing only the 'name="..."' attribute from those lines and see if that fixes it?

**Comment by Shiyunyang-seu** [comment]
Hi, I tried two ways.
1. I change the Chinese name of bus stop and bus line in English.
2.I delete all the name of bus stops. 
But, the gbk error also exits.
I used the updated version in windows(0413) python3.7
![busstop](https://user-images.githubusercontent.com/55737075/79144469-97777480-7df1-11ea-95ad-fbf5318e6a2c.png)
![error](https://user-images.githubusercontent.com/55737075/79144496-a100dc80-7df1-11ea-8b30-14092d0babde.png)

**Comment by Shiyunyang-seu** [comment]
Please check the osm file, from line 57521 node id="5867516256" to line 58398 node id="5868786085" almost all the bus stops in the middle of these lines have not been successfully converted through Netconvert. Is there a fatal error?
[suzhou_gucheng.zip](https://github.com/eclipse/sumo/files/4470998/suzhou_gucheng.zip)

**Comment by namdre** [comment]
The issue seems to be that on the Chinese version of the windows operating system, the default encoding is 'gbk' rather than 'utf8'. The solution for python3 would be to open the file with a predefined encoding ( `open(file, enconding="utf8"`).
@behrisch The backward-compatible way would  be to use io.open in sumolib/xml.py
https://stackoverflow.com/questions/10971033/backporting-python-3-openencoding-utf-8-to-python-2
which is already done in xml2csv.py and csv2xml.py
There is a caveat about speed though. As an alternative we could let python2 fail and only use open-with-encoding if pythonversion >= 3.

**Comment by namdre** [comment]
> Please check the osm file, from line 57521 node id="5867516256" to line 58398 node id="5868786085" almost all the bus stops in the middle of these lines have not been successfully converted through Netconvert. Is there a fatal error?

These bus stops are not referenced by any lines and they are not part of any osm ways (either one of these conditions must be met for bus stops to be imported). Please move questions of this type to another ticket since it's not related to the encoding issue.

**Comment by Shiyunyang-seu** [comment]
> The issue seems to be that on the Chinese version of the windows operating system, the default encoding is 'gbk' rather than 'utf8'. The solution for python3 would be to open the file with a predefined encoding ( `open(file, enconding="utf8"`).
> @behrisch The backward-compatible way would be to use io.open in sumolib/xml.py
> https://stackoverflow.com/questions/10971033/backporting-python-3-openencoding-utf-8-to-python-2
> which is already done in xml2csv.py and csv2xml.py
> There is a caveat about speed though. As an alternative we could let python2 fail and only use open-with-encoding if pythonversion >= 3.

Thanks for your helping. I opened the files with a predefined encoding(see figure1) and the encoding problem solved. But the new error occors.
![open file](https://user-images.githubusercontent.com/55737075/79247066-95262080-7eac-11ea-9e44-7de7096c45e4.jpg)
![error](https://user-images.githubusercontent.com/55737075/79247070-97887a80-7eac-11ea-8b22-2de3891e86da.jpg)

**Comment by namdre** [comment]
I cannot reproduce this error. Can you zip and attach all input files to ptlines2flows? Possibly they are different from the ones I get when importing your osm file.

**Comment by Shiyunyang-seu** [comment]
[encoding.zip](https://github.com/eclipse/sumo/files/4479121/encoding.zip)
Thanks for your helping(Another problem:the fixedstop file in the zipfile is converted by NETCONVERT, but the stop still on the sidewalks).

**Comment by namdre** [comment]
1) The error "no element found" comes from reusing the file object f2 (after using it in line 132 the file pointer is at the end of the file so it does not find any data when used again in line 142.

2) The busstop lanes are not fixed with your version of netconvert because you have the one that was built on the morning before my fix was included. Update to today's version to make use of the fix.

**Comment by Shiyunyang-seu** [comment]
Thanks a lot! I solved it!
