### ISSUE TITLE
WebWizard - Strange Vessel behavior

### ISSUE THREAD

**Issue by MelanieWeber** [eclipse/sumo#6874]
I create a WebWizard scenario from a habour and in the simulation every second a vessel appears.

**Comment by namdre** [comment]
What was the count setting for ships? What are the contents of build.bat?

**Comment by MelanieWeber** [comment]
As far as I can see it should have the following count settings:
40 through traffic factor
2 count

Build.bat:
python "%SUMO_HOME%\tools\ptlines2flows.py" -n osm.net.xml -e 3600 -p 600 --random-begin --seed 42 --ptstops osm_stops.add.xml --ptlines osm_ptlines.xml -o osm_pt.rou.xml --ignore-errors --vtype-prefix pt_ --stopinfos-file stopinfos.xml --routes-file vehroutes.xml --trips-file trips.trips.xml --min-stops 0 --extend-to-fringe --verbose
python "%SUMO_HOME%\tools\randomTrips.py" -n osm.net.xml --seed 42 --fringe-factor 1 -p 16.896141 -o osm.pedestrian.trips.xml -e 3600 -r osm.pedestrian.rou.xml --vehicle-class pedestrian --persontrips --prefix ped --trip-attributes "modes=\"public\"" --additional-files osm_stops.add.xml,osm_pt.rou.xml
python "%SUMO_HOME%\tools\randomTrips.py" -n osm.net.xml --seed 42 --fringe-factor 5 -p 24.005685 -o osm.passenger.trips.xml -e 3600 --vehicle-class passenger --vclass passenger --prefix veh --min-distance 300 --trip-attributes "departLane=\"best\"" --fringe-start-attributes "departSpeed=\"max\"" --allow-fringe.min-length 1000 --lanes --validate
python "%SUMO_HOME%\tools\randomTrips.py" -n osm.net.xml --seed 42 --fringe-factor 5 -p 36.008527 -o osm.truck.trips.xml -e 3600 --vehicle-class truck --vclass truck --prefix truck --min-distance 600 --fringe-start-attributes "departSpeed=\"max\"" --trip-attributes "departLane=\"best\"" --validate
python "%SUMO_HOME%\tools\randomTrips.py" -n osm.net.xml --seed 42 --fringe-factor 5 -p 72.017054 -o osm.bus.trips.xml -e 3600 --vehicle-class bus --vclass bus --prefix bus --min-distance 600 --fringe-start-attributes "departSpeed=\"max\"" --trip-attributes "departLane=\"best\"" --validate
python "%SUMO_HOME%\tools\randomTrips.py" -n osm.net.xml --seed 42 --fringe-factor 40 -p 0.353616 -o osm.ship.trips.xml -e 3600 --vehicle-class ship --vclass ship --prefix ship --validate --fringe-start-attributes "departSpeed=\"max\""
python "%SUMO_HOME%\tools\randomTrips.py" -n osm.net.xml --seed 42 --fringe-factor 40 -p 358.895320 -o osm.rail.trips.xml -e 3600 --vehicle-class rail --vclass rail --prefix rail --fringe-start-attributes "departSpeed=\"max\"" --min-distance 2400 --trip-attributes "departLane=\"best\"" --validate


Von: Jakob Erdmann [mailto:notifications@github.com]
Gesendet: Sonntag, 12. April 2020 21:41
An: eclipse/sumo
Cc: Weber, Melanie; Author
Betreff: Re: [eclipse/sumo] WebWizard - Strange Vessel behavior (#6874)


What was the count setting for ships? What are the contents of build.bat?

**Comment by namdre** [comment]
> python "%SUMO_HOME%\tools\randomTrips.py" -n osm.net.xml --seed 42 --fringe-factor 40 **-p 0.353616** -o osm.ship.trips.xml 

The problem is already in the randomTrips parameters that are set to generate ~ 3 ships per second.
The 'count' attribute is vehicles per hour per kilometer of appropriate network edge. If the network size is huge then this would explain the high frequency (which becomes concentrated on a few edges) due to the --fringe-factor value.

**Comment by namdre** [comment]
total edge length of ~5000km is to blame.
