### ISSUE TITLE
About simulation step-length

### ISSUE THREAD

**Issue by yumianhuli2** [eclipse/sumo#6875]
Hello！
I run traci.start(['sumo', "-c", "data/cross.sumocfg","--step-length","0.05"]), 
I expected e.g. if I use 3600 steps,it could get 3600*0.05=180s,
but the simulation finished in 5s,so how can I  do what I expected by Traci?

**Comment by m-kro** [comment]
See [SUMO docs](https://sumo.dlr.de/docs/TraCI.html#shutdown). It depends on your TraCI code when it finishes earlier.

**Comment by yumianhuli2** [comment]
> See [SUMO docs](https://sumo.dlr.de/docs/TraCI.html#shutdown). It depends on your TraCI calls when it finishes earlier.

Thank you! Is there a python example for it?

**Comment by m-kro** [comment]
Below is an excerpt of the runner.py script (see [tutorial](https://sumo.dlr.de/docs/Tutorials/TraCI4Traffic_Lights.html)):
https://github.com/eclipse/sumo/blob/a526d4b47ae293ef0232abcef19abf6a374d2990/tests/complex/tutorial/traci_tls/runner.py#L87-L97
If you want the traci.simulationStep() command to be repeated for _n_ steps, then you could e.g. change the while condition to "while step < _n_".
