### ISSUE TITLE
Warnings while converting an opendrive file to .net.xml

### ISSUE THREAD

**Issue by Akshay-sudo-ux** [eclipse/sumo#6876]
Hi,
I converted an opendrive file and I got the warnings as follows:-

Warning: Lane '-21.0.00000000_0' is not connected from any incoming edge at junction '21.20'.
Warning: Lane '-8.0.00000000_0' is not connected from any incoming edge at junction '8.7'.
Warning: Lane '12.27.48457143_0' is not connected from any incoming edge at junction '13.12'.
Warning: Lane '26.0.00_0' is not connected from any incoming edge at junction '27.26'.
Warning: Edge '-18.0.00' has a grade of 46.58%.
Warning: Edge '-4.0.00' has a grade of 45.11%.
Warning: Edge '3.0.00' has a grade of 46.69%.
Warning: Edge '5.0.00' has a grade of 39.81%.

I want to point out that, the junction '21.20' is not mentioned in opendrive map.
**When an extra lane is added to a road, I am getting this warning.**
and also, can anyone help me to debug the warning message "Edge '-18.0.00' has a grade of 46.58%."

**Comment by namdre** [comment]
1) OpenDRIVE only models at most one successor lane for each lane. When an extra lane is added, this is typically modeled in SUMO by one lane having two successor lanes, hence the warning. Vehicles can still make use of the extra lane by lane changing so the impact on simulation is usually not that big. However, the ambiguity about successors can have a big impact ahead of intersections.

2) The junction 21.20 is created to model the direct connectivity between road 21 and road 20 (SUMO always needs a junction between two edges)

3) The grade warning is about suspicious 3D-road geometry. See https://sumo.dlr.de/docs/Networks/Elevation.html#visualizing_elevation_data

**Comment by Akshay-sudo-ux** [comment]
Thank you! @namdre
