### ISSUE TITLE
About sumo java  examples

### ISSUE THREAD

**Issue by yumianhuli2** [eclipse/sumo#6877]
Hello！
Where can I find examples for java?
like : 
 for (vehid:conn.do_job_get(Vehicle.getIDList())) {
                    System.out.println(vehid);
                    var xxx = (double)conn.do_job_get(Vehicle.getPosition(vehid));
                }

Thank you!

**Comment by namdre** [comment]
https://github.com/eclipse/sumo/blob/master/tests/complex/traas/api/data/APITest.java
