### ISSUE TITLE
Error: Could not open types-file 'osmNetconvert.typ.xml'.

### ISSUE THREAD

**Issue by Luiscri** [eclipse/sumo#6878]
I'm trying to convert an osm.xml file of the city of Madrid to the a sumo network file. For this, once I got the osm file using the Overpass API of OSM, I run the following command:

```
netconvert --type-files osmNetconvert.typ.xml,osmNetconvertUrbanDe.typ.xml --osm-files map.osm.xml --output-file madrid.net.xml --geometry.remove --roundabouts.guess --ramps.guess --junctions.join --tls.guess-signals --tls.discard-simple --tls.join
```

but I am getting the following error message:

```
Error: Could not open types-file 'osmNetconvert.typ.xml'.
Warning: ...
...
Error: No edges loaded.
Quitting (on error).
```

This can be solved my copying those two files to my project directory, but I am afraid that if sumo can not locate manually those two files, neither can find other data files necessary for doing the other conversions. Any clue what is happening?

I have checked manually my installation path and those files are in the path `/usr/share/sumo/data/typemap/`. Moreover, I have in my `~/.bashrc` file the following environment variable:

```
#SUMO 
export SUMO_HOME=/usr/share/sumo/
```

and running `echo $SUMO_HOME` from the command line returns that path.

Finally, I am using Ubuntu 19.10 and this is the version of sumo I currently have installed:

```
Eclipse SUMO Version 1.5.0
Build features: Linux-4.4.0-173-generic x86_64 GNU 9.2.1 None Proj GUI SWIG GDAL GL2PS
```

**Comment by namdre** [comment]
This is working as expected. You must give the full path to the type file (i.e. .../sumo/data/typemap/osmNetconvert.typ.xml) or copy the file to the working directory.
Only if you do not set the `--type-files` option the default typemap is loaded from the data/typemap directory.

**Comment by Chandu-dappadi** [comment]
> This is working as expected. You must give the full path to the type file (i.e. .../sumo/data/typemap/osmNetconvert.typ.xml) or copy the file to the working directory. Only if you do not set the `--type-files` option the default typemap is loaded from the data/typemap directory.

I am also getti

> I'm trying to convert an osm.xml file of the city of Madrid to the a sumo network file. For this, once I got the osm file using the Overpass API of OSM, I run the following command:
> 
> ```
> netconvert --type-files osmNetconvert.typ.xml,osmNetconvertUrbanDe.typ.xml --osm-files map.osm.xml --output-file madrid.net.xml --geometry.remove --roundabouts.guess --ramps.guess --junctions.join --tls.guess-signals --tls.discard-simple --tls.join
> ```
> 
> but I am getting the following error message:
> 
> ```
> Error: Could not open types-file 'osmNetconvert.typ.xml'.
> Warning: ...
> ...
> Error: No edges loaded.
> Quitting (on error).
> ```
> 
> This can be solved my copying those two files to my project directory, but I am afraid that if sumo can not locate manually those two files, neither can find other data files necessary for doing the other conversions. Any clue what is happening?
> 
> I have checked manually my installation path and those files are in the path `/usr/share/sumo/data/typemap/`. Moreover, I have in my `~/.bashrc` file the following environment variable:
> 
> ```
> #SUMO 
> export SUMO_HOME=/usr/share/sumo/
> ```
> 
> and running `echo $SUMO_HOME` from the command line returns that path.
> 
> Finally, I am using Ubuntu 19.10 and this is the version of sumo I currently have installed:
> 
> ```
> Eclipse SUMO Version 1.5.0
> Build features: Linux-4.4.0-173-generic x86_64 GNU 9.2.1 None Proj GUI SWIG GDAL GL2PS
> ```

I also got the same error would you help me to solve it
Warning: Please note that 'xml-type-files' is deprecated.
 Use 'type-files' instead.
Error: Could not open osm-file 'eichstaett.osm'.
Error: No nodes loaded.
Quitting (on error).

**Comment by namdre** [comment]
The type files are special and not meant to be located automatically (copying a default type file and making customization is an intended and common use case).  Instead of giving a full path, you can also use `--type-files  ${SUMO_HOME}/data/typemap/osmNetconvert.typ.xml,${SUMO_HOME}/data/typemap/osmNetconvertUrbanDe.typ.xml`

Also, the eichstaett warnings are from an outdated example for a specific osm input file by that name.

**Comment by Chandu-dappadi** [comment]
> 

got it
