### ISSUE TITLE
Public Transport: Urban rail only support one direction

### ISSUE THREAD

**Issue by Shiyunyang-seu** [eclipse/sumo#6880]
Hi ,  I tried to build the subway in sumo, and I have successfully built the site and defined the flow, but the subway only supports a single direction, which is inconsistent with the fact, and I can't change the direction by defining the stop order in the opposite way, the urban subway only exists on one edge. 
I import the network from the OSM and convert it. Does the rail only support urban_rail running in one direction (because the lane is 1) and can I make it drive in two directions?

![flow of subway](https://user-images.githubusercontent.com/55737075/79050248-606f5a80-7c5b-11ea-869c-c8eaba5ec910.png)

**Comment by namdre** [comment]
see https://sumo.dlr.de/docs/Simulation/Railways.html#handling_problems_in_bidirectional_railway_networks
