### ISSUE TITLE
allow setting traffic light params

### ISSUE THREAD

**Issue by pengyuan-zhou** [eclipse/sumo#6881]
Hi, 

I'm wondering if there's a convenient way to set max-gap in run time, other than editing 
the add.xml in run time?

Thanks.

**Comment by namdre** [comment]
actuated traffic light parameter "max-gap" is only evaluated once and there is currently no way to change this for a running simulation. You will have to modify the add.xml and reload the simulation.

**Comment by zpymyyn** [comment]
> actuated traffic light parameter "max-gap" is only evaluated once and there is currently no way to change this for a running simulation. You will have to modify the add.xml and reload the simulation.

Thanks for the reply. I can do the file modification, however seems to fail to let it reload. 
Is there a function or file I can look into to reload it? 

Thanks:)

**Comment by namdre** [comment]
I've tested with sumo-gui and the 'reload' button. You can see the changed parameter when right-clicking on a traffic light and opening the parameter dialog ('show parameter').
Restarting the process or using traci.load should also work.

**Comment by zpymyyn** [comment]
> I've tested with sumo-gui and the 'reload' button. You can see the changed parameter when right-clicking on a traffic light and opening the parameter dialog ('show parameter').
> Restarting the process or using traci.load should also work.

Thank you! You save my day :)

**Comment by pengyuan-zhou** [comment]
> I've tested with sumo-gui and the 'reload' button. You can see the changed parameter when right-clicking on a traffic light and opening the parameter dialog ('show parameter').
> Restarting the process or using traci.load should also work.

Hi, sorry for readdressing this, but is there any plan to enable modifying actuated traffic light parameter in run time without gui?
Thanks.

**Comment by pengyuan-zhou** [comment]
@namdre Great, thanks a lot :)
