### ISSUE TITLE
Bus stop and bus operation conversion error

### ISSUE THREAD

**Issue by Shiyunyang-seu** [eclipse/sumo#6882]
Hi, I tried to add sidewalks to all urban roads (Input is OSM data), but when I used netconvert to build bus stops, I found that the bus stop will be built on the sidewalk (in fact, it's true, because pedestrians couldn't walk to the bus stop without sidewalks), but when I used pylines2flow.py to created the bus routes, it showed that the bus can't stop, because It's parked on the sidewalk, but actually it should be parked on the adjacent vehicle lane.
![stop](https://user-images.githubusercontent.com/55737075/79091965-e7b6ee00-7d81-11ea-91a8-3f7c304ef6f9.png)
![erroe](https://user-images.githubusercontent.com/55737075/79091971-eb4a7500-7d81-11ea-9522-2f296a963cae.png)

**Comment by Shiyunyang-seu** [comment]
Version is the sumo version 1.5.0, the problem occured both in windows and ubuntu.

**Comment by namdre** [comment]
When the stops are built for a network without sidewalks and then the network is changed, the stops must be re-processed to fix the lane (the stop lane defines where the vehicle stops so it cannot be on a sidewalk). 
To fix the stops call:

`netconvert -s new.net.xml --ptstop-files old.stops.xml --ptstop-output fixed.stops.xml`

There was a bug that prevent lane-reassignment which is now fixed. You can get the updated version of netconvert tomorrow at https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_development_version

**Comment by Shiyunyang-seu** [comment]
> When the stops are built for a network without sidewalks and then the network is changed, the stops must be re-processed to fix the lane (the stop lane defines where the vehicle stops so it cannot be on a sidewalk).
> To fix the stops call:
> 
> `netconvert -s new.net.xml --ptstop-files old.stops.xml --ptstop-output fixed.stops.xml`
> 
> There was a bug that prevent lane-reassignment which is now fixed. You can get the updated version of netconvert tomorrow at https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_development_version

Thanks a lot and I will try the updated version tomorrow.
