### ISSUE TITLE
How to figure out list of edges

### ISSUE THREAD

**Issue by jylee3302** [eclipse/sumo#6887]
Hi,

traci.edge.getIDList() or getIDCount is not giving the edge list, but all object list including lanes.
What I want to do is

for all Edges:
  do something with the edgeID

but traci.edge.getIDList() is not only giving the list of edge, but also all objects, which makes me difficult to do the above code. 
One possible solution I got is, simply remove any object that has "_", underbar symbol, from the result of traci.edge.getIDList() and what's left is the edge ID list. Is there any better way than this?

**Comment by namdre** [comment]
edge.getIDList is not giving you lanes. What it does give you though are the IDs of *internal* edges (edges within junctions). You can recognize these by the `:` character at the start of the id and easily filter them:

```
for edgeID in [e for e in traci.edge.getIDList if e[0] != ":"]:
   do stuff
```

**Comment by jylee3302** [comment]
Thank you very much. 
I appreciate your help.

> edge.getIDList is not giving you lanes. What it does give you though are the IDs of internal edges (edges within junctions). You can recognize these by the : character at the start of the id and easily filter them:
> for edgeID in [e for e in traci.edge.getIDList if e[0] != ":"]:
>    do stuff
