### ISSUE TITLE
About simulation.subscribeContext  in C++

### ISSUE THREAD

**Issue by zoe5** [eclipse/sumo#6896]
Hello:
I  wonder how to use  simulation.subscribeContext() in the C++ program;
I don't  understand the parameter‘s  meaning ,such as:const std::string& objID   and  const std::vector<int>& vars .And can you give me an example of this sentence .
If you know ,please tell me.
Thank you very  much.

**Comment by namdre** [comment]
objID is the object around which you wish to collect data in the given distance
vars is a list of traci constants such as VAR_SPEED or VAR_POSITION to denote the values that you wish to subscribe to (i.e. to get the positions of all pedestrians around an ego vehicle).

**Comment by zoe5** [comment]
Thank you ,and i wonder  if the int domID is the type of values i want to subscribe .
and if the domID value can use  CMD_SUBSCRIBE_VEHICLE.

**Comment by namdre** [comment]
The domID is something like CMD_GET_VEHICLE_VARIABLE or CMD_GET_PERSON_VARIABLE

**Comment by zoe5** [comment]
OK,I  get it.
Thank you very much.

**Comment by zoe5** [comment]
Hello , Jakob Erdmann. Excuse me again!
**i am using  simulation.subscribeContext like this:
	std::vector<int>vars = { VAR_DISTANCE};
	client.simulation.subscribeContext(CMD_GET_VEHICLE_VARIABLE, "TestCar",0,5000, CMD_GET_VEHICLE_VARIABLE,50,vars);
	client.simulation.getContextSubscriptionResults("TestCar");

**and i want to get the value return ,but it is wrong like this:
Error: Answered with error to command 0xa4: Wrong position in requestMessage after dispatching command. Expected command length was 36 but 11 Bytes were read.

**and  how int domain mean ,is it like domID .I set the domain value is CMD_GET_VEHICLE_VARIABLE . Whether the value is wrong.

**Can you give me some suggestion to deal with this problem.

**Comment by namdre** [comment]
If you want to subscribe to objects around **vehicle** TestCar you need to call
client.**vehicle**.subscribeContext 
 (the domain must match the category of objectID)
see https://github.com/eclipse/sumo/blob/988feb08a80e8179874bf75fb9fb0231d829382f/src/traci_testclient/TraCITestClient.cpp#L917-L919

**Comment by zoe5** [comment]
Hello , Jakob Erdmann.      Excuse me again!
I can not  find subscribeContext()  in the vehicle.h 
when i  write  program like
 vehicle.subscribeContext("1", libsumo::CMD_GET_VEHICLE_VARIABLE, 1000, vars3, 0, 100);
the undefined identifier vehicle is displayed
HOW do i  get the source file about vehicle.subscribeContext();

**Comment by namdre** [comment]
Lets back up a little bit. Are you trying to use the C++ client for socket communication (https://sumo.dlr.de/docs/TraCI/C++TraCIAPI.html) or are you trying to link against libsumo? (https://sumo.dlr.de/docs/Libsumo.html

**Comment by zoe5** [comment]
yes . 
 I already use some function , such as:
`	client.vehicle.add("TraciMoveToCar", "TraciMoveToRoute", "TraciCarType","6");
	client.vehicle.moveTo("TraciMoveToCar", "-40006_0", 20);`
and They can all be used normally。
I find vehicle.subscribeContext() In the following file about my sumo: 
[](https://github.com/eclipse/sumo/blob/master/src/libsumo/Vehicle.h)

**Comment by zoe5** [comment]
yes .
I already use some function , such as:
client.vehicle.add("TraciMoveToCar", "TraciMoveToRoute", "TraciCarType","6"); client.vehicle.moveTo("TraciMoveToCar", "-40006_0", 20);
and They can all be used normally。
I find vehicle.subscribeContext() In the following file about my sumo
[](https://github.com/eclipse/sumo/blob/master/src/libsumo/Vehicle.h)

**Comment by zoe5** [comment]
yes .
I already use some function , such as:
client.vehicle.add("TraciMoveToCar", "TraciMoveToRoute", "TraciCarType","6"); client.vehicle.moveTo("TraciMoveToCar", "-40006_0", 20);
and They can all be used normally。
I find vehicle.subscribeContext() In the following file about my sumo
https://github.com/eclipse/sumo/blob/master/src/libsumo/Vehicle.h

**Comment by namdre** [comment]
I was asking an either/or question so your answer of 'yes' is ambiguous to me.
The function vehicle.subscribeContext is defined via the marcro https://github.com/eclipse/sumo/blob/d70d7ccb2d8117f41c698471248d6d9a4904831a/src/libsumo/Vehicle.h#L182
which is defined at https://github.com/eclipse/sumo/blob/d70d7ccb2d8117f41c698471248d6d9a4904831a/src/libsumo/TraCIDefs.h#L39-L81

**Comment by zoe5** [comment]
I'm sorry I didn't make myself clear, which made you confused。
I just didn't fully understand your suggestion.
But now ,i  understand what you  mean,  and know ,how to do , i will try again。
Thank you very much for your careful answer。
