### ISSUE TITLE
how to set lane direction when creating net.xml from plain files?

### ISSUE THREAD

**Issue by whvagrant** [eclipse/sumo#6897]
Hi,

I want to create net files from plain files, but I do not find which attribute define that. I notice the net xml files has the attr in connect parts, but I do not know how to set that in plain xml files.

**Comment by namdre** [comment]
Each edge (and all of its lanes) are directional as defined by the junction ids in attributes 'from' and 'to'.

**Comment by whvagrant** [comment]
> Each edge (and all of its lanes) are directional as defined by the junction ids in attributes 'from' and 'to'.

thanks from reply.

If I have 1 'from' edge(A) which has 3 lanes(A1, A2, A3) and 2 'to' edges(B,C) which have 2 lanes(B1, B2, C1, C2). I want to make from 'A1' to 'B1, B2', from 'A2, A3' to 'C1, C2', how do I set in connection files?

**Comment by namdre** [comment]
I suggest that you click the desired connections in netedit, then use the menu option "save plain xml" and look into the generated files.

**Comment by whvagrant** [comment]
> I suggest that you click the desired connections in netedit, then use the menu option "save plain xml" and look into the generated files.

Good idea, thanks a lot
