### ISSUE TITLE
Traffic light  adding in case of missing information

### ISSUE THREAD

**Issue by Shiyunyang-seu** [eclipse/sumo#6899]
Hi, the original OSM file lacks many traffic light information(nearly 2000 nodes, but 6 signal plans ). So, through Netconvert, I can only get the signal timing plan of six intersections, but in large-scale network, it is difficult to add Netedit one by one. How can I give each intersection a default or fixed signal light plan?

**Comment by namdre** [comment]
The option **--tls.guess** already serves the purpose of adding additional traffic light. The function adds together the speeds of all incoming lanes and compares this against a threshold value (default 250/3.6) to determine whether the junction should get a traffic light. You can set a lower threshold using option **-tls.guess.threshold**. 
Note, that the root problem seems to be deflated lane numbers on many roads in the OSM database. If the lane numbers were higher, traffic lights would already be guessed. You could try to fix the lane numbers by changing the defaults: https://sumo.dlr.de/docs/SUMO_edge_type_file.html
https://sumo.dlr.de/docs/Networks/Import/OpenStreetMap.html#recommended_typemaps

Also, I recommend setting option --junctions.join (see https://sumo.dlr.de/docs/Networks/Import/OpenStreetMap.html#recommended_netconvert_options)

**Comment by Shiyunyang-seu** [comment]
Hi, thank you for your helping.
I have modified the number of lanes for each level of road by modifying the Netconvert.maptype.xml file, but tls.guess still doesn't add lights for intersections. At the same time, I reduced the tls.guess.threshold and found that many small intersections were equipped with signal lights, but the primary road and secondary road intersections did not (about 20 similar ones).
![error](https://user-images.githubusercontent.com/55737075/79414975-a66f4a00-7fde-11ea-9cff-78e595454f3e.png)

**Comment by namdre** [comment]
There is a hard-coded speed threshold that prevents building traffic lights on motorways and other fast roads (no tls are guessed if any of the incoming lanes has speed >= 80km/h). 
It appears that speed limits are missing in your osm file so the default speed for rural roads of 100km/h is used. You could add the 'urban' typemap wich changes speed limits (typemaps can be combined) or just change them in your custom typemap.
