### ISSUE TITLE
crash when trying to define a walk to a busStop

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#6903]
Using the network and stops from [0e66491c781e15ada8bf1b3414144f218f24df9d], try to define the first walk of the person.
When trying to save, the walk is flagged as invalid. When pressing 'accept', netedit crashes.

Bonus: allow for the rest of the plan (ride from busStop to busStop and walk from busStop to edge) to be defined as well.

**Comment by palvarezlopez** [comment]
Fixed in #8377
