### ISSUE TITLE
Import for AcitivityGen

### ISSUE THREAD

**Issue by Shiyunyang-seu** [eclipse/sumo#6905]
Hi, I followed the tutorial of activitygen, but still have some questions.
1. When I define `<streets>`,it must be accurate to the specific side, so it is difficult for large-scale road network to manually input one by one. Is there an automatic way?
2. When I define `<citygates>`, an error is displayed. I didn't define the access ratio for one edge at the same time, because I think an edge has only one direction, so it should only be one of incoming or outgoing.
![error](https://user-images.githubusercontent.com/55737075/79487308-a4db6b80-804a-11ea-8973-330effe4f090.png)
![citygate](https://user-images.githubusercontent.com/55737075/79487314-a86ef280-804a-11ea-8eea-41fc7573d27c.png)
3. The bus definition in this file is different from that of additional files. Can I use additional directly or only make some modifications?
Thank you!

**Comment by namdre** [comment]
I think activitygen is not the best possible choice for a population modelling tool at the moment. I recommend that you look at sumo/tools/contributed/saga instead which is more advanced and features higher automation.
Also, activitygen has not been maintained for years wheras saga is under active development.
https://github.com/lcodeca/SUMOActivityGen/blob/master/docs/HOWTO.md

**Comment by Shiyunyang-seu** [comment]
Hi, I followed the tutorial but there is an error that I cannot find the reason( No module named 'libsumo.libsumo')
![error](https://user-images.githubusercontent.com/55737075/79599965-f6eac280-8118-11ea-822b-182949d2531e.png)
).

**Comment by namdre** [comment]
I think this is an oversight in the current development version of saga. I think you can safely remove line 26 in sagaActivityReport @lcodeca (can you check this?)

**Comment by lcodeca** [comment]
Yes, in my setup (I don't know why) it does not raise the error. 
Nonetheless, the import is useless at this stage and I removed it.
I just tested it and pushed the change.
You can pull [commit/1a5c5be909aea3539177916c8b4e25a42c903cdd](https://github.com/lcodeca/SUMOActivityGen/commit/1a5c5be909aea3539177916c8b4e25a42c903cdd).
In case you have other issues, do not hesitate to contact me directly.

**Comment by Shiyunyang-seu** [comment]
Hi,

> Yes, in my setup (I don't know why) it does not raise the error.
> Nonetheless, the import is useless at this stage and I removed it.
> I just tested it and pushed the change.
> You can pull [commit/1a5c5be909aea3539177916c8b4e25a42c903cdd](https://github.com/lcodeca/SUMOActivityGen/commit/1a5c5be909aea3539177916c8b4e25a42c903cdd).
> In case you have other issues, do not hesitate to contact me directly.

Hi, I made the same mistake when I tried to remove 26 lines separately and 23-29 lines.
![0418](https://user-images.githubusercontent.com/55737075/79626648-3ee30700-8164-11ea-9908-1e3228264283.png)

**Comment by namdre** [comment]
saga requires SUMO_TOOLS to be defined. Usually its the 'tools' subdirectory of SUMO_HOME
`os.environ['SUMO_TOOLS'] = os.path.join(os.environ['SUMO_HOME'], 'tools')`

**Comment by lcodeca** [comment]
You removed the wrong line from the wrong file.
You can check the commit above to remove the right lines, or you can just pull from the repository.
It's fixed now.

**Comment by Shiyunyang-seu** [comment]
Thanks for your replying. I have solved the previous problem by modifying the environment variables, but a new error
![1](https://user-images.githubusercontent.com/55737075/79694206-799e8980-82a1-11ea-8d40-308a0c1b354f.png)
 appears, as shown in the figure.

**Comment by lcodeca** [comment]
The administrative boundaries in the OSM file you are using are broken.
You should manage to avoid the problem by using `--single-taz`.
Nonetheless, if you send me your OSM file, I'm going to try to catch the exception.
Additionally, would you mind sharing log files instead of images, and opening issues on [SUMOActivityGen/issues](https://github.com/lcodeca/SUMOActivityGen/issues), it would make it easy for me to actually keep track of what's going on.
