### ISSUE TITLE
Add compound type TraCIResult structs to libsumo

### ISSUE THREAD

**Issue by schwamborn** [eclipse/sumo#6910]
For example, representing results from

```
traci.vehicle.getLeader(string, double) -> (string, double)
traci.vehicle.getNextStops(string) -> [(string, double, string, int, int, int)], ...
```

**Comment by schwamborn** [comment]
Only just found `libsumo::TraCINextStopData`.
@namdre @behrisch Any objections to deriving TraCINextStopData from TraCIResult? Would also remove TraCIStop then.

**Comment by namdre** [comment]
Sounds good to me.

**Comment by behrisch** [comment]
I am not so much a fan of adding a struct where a pair would do (TraCILeaderDistance) but everything else is just fine. And now that it is done we can just keep it. @schwamborn Can we close this?

**Comment by schwamborn** [comment]
@behrisch I'd agree if it were not for iCS, where every TraCI response needs to be a TraCIResult.
