### ISSUE TITLE
netconvert

### ISSUE THREAD

**Issue by albertcruzeyork** [eclipse/sumo#6911]
when i use netconvert like this:`call([netconvert, '-s', 'C:/Users/albert/Desktop/bottleneck/test.net.xml' , '--plain-output-prefix','plain'])`. i find some edges in the output 'plain.edg.xml' whose attributes 'numlanes' is different from the original. How to solve it?

**Comment by namdre** [comment]
please provide your test network and an edgeID where the attribute differs.

**Comment by albertcruzeyork** [comment]
in test.net.xml:`<edge id="1" from="1" to="2" priority="3" type="b">
        <lane id="1_0" index="0" speed="13.89" length="287.20" shape="6.40,695.20 293.60,695.20"/>
        <lane id="1_1" index="1" speed="13.89" length="287.20" shape="6.40,698.40 293.60,698.40"/>`
in plain.edg.xml: `<edge id="1" from="1" to="2" priority="3" type="a" numLanes="3" speed="13.89"/>`

**Comment by namdre** [comment]
please zip the input .net.xml file and the output plain.edg.xml file and attach them to this ticket.

**Comment by albertcruzeyork** [comment]
[net.zip](https://github.com/eclipse/sumo/files/4499067/net.zip)

**Comment by namdre** [comment]
Strange. I cannot reproduce this when doing the .net.xml -> plain.xml conversion (tested with 1.3.1 and 1.5).
What I did notice though is that not only is the numLanes different, but also the type. 
Could it be that you have two different networks named 'test.net.xml' (i.e. one in bottleneck and one in bottleneck/test)?

**Comment by albertcruzeyork** [comment]
that's true. i ignored it.
