### ISSUE TITLE
marouter crashes when using "CH"

### ISSUE THREAD

**Issue by ambuehll** [eclipse/sumo#6912]
I am having a bit of fun with marouter, but unfortunately it's been crashing with: 

`marouter -n RIO.net.xml -r trips24h.trips.xml -o marouted.rou.xml --exit-times true --routing-algorithm CH --routing-threads 20 --weight-period 300 --max-iterations 1 -d taz.xml`

CH seems to be the issue here. 
[files](https://drive.google.com/drive/folders/1Sc12D-mlsU3Y-hgvMuUXz6ATglnouZ4T?usp=sharing)
Also, not quite sure why it seems to be routing from taz and not from edges directly. If I don't provide any taz, it won't route anything. 

As always, sorry for the large files, and thanks a lot!

Lukas

**Comment by namdre** [comment]
I recommend not using CH (#9635)
