### ISSUE TITLE
Vehicles cannot park on roadside parking area 

### ISSUE THREAD

**Issue by Shiyunyang-seu** [eclipse/sumo#6915]
Hi, I define a on road parking area, but only the front car can stop. On the other hand, there will be overlaps in the parking area, but I think we should specify the location according to the actual vehicle length, rather than the overlaps. Furthermore, whether the parking area should be set up on the vehicle lane, because when it is set on the sidewalk, it will cause the vehicles to be unable to stop (at the same time, I don't know whether it will affect the
![parking2](https://user-images.githubusercontent.com/55737075/79760296-77e0ce80-8352-11ea-8108-1720cb9e14e0.png)
![parking](https://user-images.githubusercontent.com/55737075/79760305-79aa9200-8352-11ea-905a-24ba4ead572a.jpg)

 pedestrian)

**Comment by namdre** [comment]
parkingAreas were originally implemented for roadside parking (not on a driving lane).
The `onRoad` setting is still experimental. It will only work if the length of the parkingArea divided by roadsideCapacity gives a length that is large enough for each of the vehicles that want to park there (length + minGap).
