### ISSUE TITLE
add checkbox for scaling vehicles with edge geometry factor

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#6920]
Currently, normal cars are always the same length even when the road has scaled geometry.
This is confusing  when the edge geometry is shorter than its length because vehicles bodies overlap suggesting collision. 
Rail-carriages however, are scaled according to edge geometry which can look bad on abstract rail networks because the apparent train length constantly changes. (it can be useful to understand exactly where the train is).
The problem is particularly pronounced when set to 'draw with constant size when zoomed out'.

Solution: make behavior configurable and consistent
- with check disabled, vehicles are drawn as always and carriages are no longer scaled
- with checkbox enabled, vehicles and carriages are scaled to match the edge length/geometry factor

**Comment by palvarezlopez** [comment]
@namdre also in NETEDIT?

**Comment by namdre** [comment]
Possibly, but not urgent because the vehicles do not move around.
