### ISSUE TITLE
long duration when loading a polygon file in netedit, but not in sumo-gui

### ISSUE THREAD

**Issue by yunpangfloetteroed** [eclipse/sumo#6925]
It takes around 4-5 minutes to load a zipped polygon file (153KB, the original file size is 5 MB) in netedit, but it takes only a couple of seconds to do that in sumo-gui. The test data set is attached.
[testdata.zip](https://github.com/eclipse/sumo/files/4510211/testdata.zip)

**Comment by palvarezlopez** [comment]
Problem is causes by a lot of invalid warnings.
