### ISSUE TITLE
Vehicles can't get correct lane id

### ISSUE THREAD

**Issue by NiklasDanz** [eclipse/sumo#6933]
**Situation**: Getting a vehicle's current lane id (in the GUI or API)
**Expected**: Correct lane id with correct suffix (so its clear which lane the vehicle is currently in)
**Reality**: Correct lane id with wrong suffix (_1, _2 ...). So it's only clear on which side of the road (positive or negative value) and which part of the road network the vehicle is driving. But not the lane when there are multiple.

**Demonstration**:
When right clicking on a lane in the GUI, the correct ID and suffix appear.
![image (4)](https://user-images.githubusercontent.com/12987574/79965655-94812180-848c-11ea-8af4-14f613b33179.png)
When positioning the vehicle at this lane, it reads another lane's value (from the same side of the road).
![image (5)](https://user-images.githubusercontent.com/12987574/79965638-91863100-848c-11ea-9ed0-66b334fae953.png)

**Comment by namdre** [comment]
possibly a duplicate of #6870. If you are placing the vehicles with moveToXY, leave the 'edgeID' empty or set the lane to -1 and check if the problem persists.

**Comment by NiklasDanz** [comment]
This solved the issue. Thanks for your help!
