### ISSUE TITLE
[Question] Is there a way to detect which vehicles have arrived in the last step in libsumo? 

### ISSUE THREAD

**Issue by ykwd** [eclipse/sumo#6934]
Is there an API in libsumo that can tell which vehicles have arrived their destination at last simulation step?
Currently the only method I know is calling Edge::getLastStepVehicleIDs for each edge to get all vehicles in the last step, and compare this information between each step. But the overhead of this method is very huge if there are a lot of edge or vehicles.

**Comment by namdre** [comment]
use Simulation::getArrivedIDList()
