### ISSUE TITLE
marouter gives different results when using CH

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#6935]
instead of defining two routes with similar probability, only a single route is defined in the distribution

**Comment by namdre** [comment]
Since MAROUTER cannot make use of bulk-routing it is arguably not a meaning full algorithm for the task anyway. Maybe we should simply remove it from the supported marouter algorithms.

**Comment by behrisch** [comment]
In my opinion the main problem is not the missing bulk routing support but rather the need for a new hierarchy whenever the edge weights change. It could still be of use for a sparse OD matrix.
