### ISSUE TITLE
warning and no simulation when PT elelemts defined in separate files

### ISSUE THREAD

**Issue by ZoltanBaksa** [eclipse/sumo#6937]
Hi,
I try to define public transport schedule as demand for a small city scenario, where there are many bus stops, many different routes for the different bus lines, and I have all the scheduling of the bus lines at each bus stop separetly.
I already managed to define all bus stops and routes, as a test I have created scheduled vehicles to.
I want to generate all the stuff from a database, and it makes the generator much more easier, if these are in separate files, so I have created an <additional> file for busStops, a <routes> file for the lines' route definitions, and another bunch of <routes> files for each bus line separately for the scheduled vehicles.
But I could not load these to a simulation separetly, because then I get warnings like "Warning: busStop '4597188241' for vehicle 'bus_37_001800' on lane '722409769#7.3_0' is not downstream the current route".
If I put the busStop, route and vehicle definitons into a single file under <additonal>, it runs fine.
I do not get any warning, if I load these files into netedit, both in single file case and separated case.

**Comment by ZoltanBaksa** [comment]
I found the cause of the problem.
I have written the <stop busStop=.../> definitions twice, as sub-tag under route with duration="20" and sub-tag under vehicle with until=".
If I remove the sub-tags from route definitions, I get the expected files and simulation is also running

**Comment by namdre** [comment]
Defining the stops as child-elements of a named route and then referencing the route also works. (The until times are then interpreted as offset from vehicle departure).
