### ISSUE TITLE
Crash in netedit when editing junction shape

### ISSUE THREAD

**Issue by ZoltanBaksa** [eclipse/sumo#6945]
I use the latest development version v1_5_0+1299-dac81a970
Sporadically but rather often netedit crashes when I try to customize junction shape. It lets change into edit junction shape mode, but at the first click on an already existing point netedit crashes.
In addition to network an additional is loaded, which contains busStop definitions, which are also in  modified state.

**Comment by palvarezlopez** [comment]
Hi, thanks for the reporting. I'm trying to reproduce it, but I can't do it. Do you have an scenario, in which this crash appear with more frequency?

**Comment by ZoltanBaksa** [comment]
Hi Pablo,
I sent a private message with the affected network and additional. I did not tested if it is specific to this configuration or not.

**Comment by palvarezlopez** [comment]
Problem found
