### ISSUE TITLE
Documentation for Emissions output reports speed in kph

### ISSUE THREAD

**Issue by kanaadp** [eclipse/sumo#6947]
https://sumo.dlr.de/docs/Simulation/Output/EmissionOutput.html

Says here that the speed output of an emissions file is in kph, but I believe I'm actually seeing m/s being output. Seems like a bug?

**Comment by angelobanse** [comment]
Thank you @kanaadp :+1:

**Comment by angelobanse** [comment]
> 
> 
> https://sumo.dlr.de/docs/Simulation/Output/EmissionOutput.html
> 
> Says here that the speed output of an emissions file is in kph, but I believe I'm actually seeing m/s being output. Seems like a bug?

it is in **m/s**
