### ISSUE TITLE
Construction of Highway Ramp

### ISSUE THREAD

**Issue by repa1030** [eclipse/sumo#6949]
Hello,

I have a question about constructing a highway ramp. The way I did it is forming the junctions so that it looks real, but now the vehicles don't act like it is an acceleration ramp (even with netconvert command --ramps.guess). 
![highway_ramp](https://user-images.githubusercontent.com/54360863/80470725-af4b0e80-8942-11ea-85d9-f03ea60a9017.png)
They are decelerating to zero at the end of the ramp and then "crawl" onto highway which often causes collisions. Is there a documentation how to build a highway entrance correctly? 
Thank you for your reply!

**Comment by angelobanse** [comment]
https://sumo.dlr.de/docs/Networks/Further_Options.html#guessing_on-_and_off-ramps
https://sumo.dlr.de/docs/Simulation/Motorways.html#motorway_ramps

**Comment by repa1030** [comment]
I already tried all those things but the vehicles still decelerate to 0 m/s (or almost 0 m/s) before entering the highway.

**Comment by namdre** [comment]
SUMO vehicles drive very conservatively: If they are unable to merge (change lanes) they must still be able to stop safely at the end of the acceleration lane. This means, that the acceleration lane should be at least as long as vehicleLength + breakingDistance to ensure that vehicles can enter then acceleration lane at full speed. 

Generally, I would recommend making the acceleration lanes longer than in reality to compensate for the increased caution (in reality, cars could often continue driving on the shoulder of the road if merging fails).

**Comment by repa1030** [comment]
Thank you for your answer.
With a longer ramp, the merge-in looks much more real, even if still some vehicles break down to zero with no reason (no oncoming cars on highway). An other problem at the ramp is that they often ignore the ego vehicle (position and velocity is set with TraCI) and they push it away. 
![sumo_ramp](https://user-images.githubusercontent.com/54360863/80943182-e740ce80-8de6-11ea-9670-27f4d71922a2.png)

**Comment by namdre** [comment]
- If you can provide a small scenario without TraCI where the ramp is long enough, there is no motorway traffic on the target lane and the merging vehicles brakes to 0, please attach it to this ticket and note down the time of the incident (zip up all input files)
- if you can provide a small scenario with TraCI where the ego vehicle is being ignored by the other vehicles, please attach it to this ticket (include the traci script with the other input files)

**Comment by repa1030** [comment]
* I observed that the braking disappears when I make the ramp even longer. So this is no problem anymore
* Providing a scenario that shows this issue is very difficult as SUMO is communicating with Unity via TCP for the ego vehicle positions, but I noticed that it disappears with the old net.xml file that uses junctions instead of geometry points. The vehicles don't crash into the ego car with this file.
[circuits.zip](https://github.com/eclipse/sumo/files/4574897/circuits.zip)

**Comment by repa1030** [comment]
I just noticed, that the pushing away happens when I rebuild the Sumo Network with

netconvert -s network_name.net.xml -R -o network_name_output.net.xml 

to replace the junctions with geometry points.

**Comment by namdre** [comment]
I assume you are using moveToXY for positioning the ego vehicle. The observed behavior might be due to #6870. Can you try with laneIndex=-1 in your moveToXY call ?

**Comment by repa1030** [comment]
Thank you very much, there are currently no more crashes now!
