### ISSUE TITLE
DFROUTER speed conflict

### ISSUE THREAD

**Issue by Smiley4ever21** [eclipse/sumo#6951]
Hallo, I enconter a speed conflict in simulation. The simulation files are in attachment.

The error information in SUMO-gui.exe is:
Error: Vehicle '605-D1.8347' will not be able to depart using the given velocity (slow lane ahead)!
But the depart speed of the vehicle is 22.39, and the allowed speed of the lane I have already changed to 27.79. The speed limit should be enough to let the vehicle start.

Could you please tell me why the vehicle can still not depart and how can I fix it? Thank you.
[DFRouter problem.zip](https://github.com/eclipse/sumo/files/4545854/DFRouter.problem.zip)

**Comment by Smiley4ever21** [comment]
Hi, thanks for your reply.
I've changed lots of speed limit, but still, I have the error like:
Error: Vehicle '611-D8.144' will not be able to depart using the given velocity (slow lane ahead)!

I've checked that the route is  "gneE3_to_-149387019#1", and for this route, all the edges("gneE3 137827143.83.5 761102692#1 37702997#0.17 149521204#0 -149387019#1") have higher speed limit than 9.42, the depart speed. 
[DF speed conflict.zip](https://github.com/eclipse/sumo/files/4599428/DF.speed.conflict.zip)

Could you please tell me why it still have the speed conflict? Thank you.

**Comment by m-kro** [comment]
I couldn't run your last example out of the box and thus stopped investigating. Did you really check the internal lanes, too? You can increase the allowed lateral acceleration in junctions using the cmd line options provided by netconvert, like _--junctions.limit-turn-speed_. What happens if you set this option to a value bigger than default? If you want to allow 50 km/h even when turning sharply, a value of ~ 20 [m/s^2] might be appropriate.

**Comment by Smiley4ever21** [comment]
Super! Thank you!
It is really the limit turn speed that matters. 

![Inked捕获_LI](https://user-images.githubusercontent.com/38075241/81539152-1a97d600-9370-11ea-97e2-c2588b36750f.jpg)
Now another issue comes out, like in the photo, the blue arrows shows the route generated by dfrouter, but on this lane, the vehicles can only turn left, so when I run the simulation, it has warnings. 

How can I generate routes considering the possible turn possibilities or can I make the vehicles change lanes? Thank you.

**Comment by m-kro** [comment]
Can you elaborate more why you think:

> but on this lane, the vehicles can only turn left

The "turn right" arrow suggests something different. You should recompute the junction shape in Netedit (e.g. press F5) to see this better.

**Comment by Smiley4ever21** [comment]
Hi, I mean the lane on the right side. 
![捕获](https://user-images.githubusercontent.com/38075241/81563735-f8657e80-9396-11ea-8905-781505d5f88d.PNG)
Also the blue lane in this image. It can just turn to the green lane, but the dfrouter generated route make it turn to the yellow one. Thus, the problem I described happed.

**Comment by m-kro** [comment]
Again, routes are defined by their **edges**, not by **lanes**. There may be vehicles coming from the cyan lane heading to the yellow lane/edge. Vehicles will try to change lanes in order to reach their target. Sometimes this becomes difficult because of heavy traffic, short edges and so on. But the route itself should still be valid. 

What kind of warning do you get?

**Comment by Smiley4ever21** [comment]
![捕获](https://user-images.githubusercontent.com/38075241/81569457-92c9c000-939f-11ea-86f5-2e8e55f0441b.PNG)
The warning is like:
Warning: Teleporting vehicle '726-D4.157'; waited too long (wrong lane), lane='316215706#1_1', time=2873.00.
Warning: Vehicle '726-D4.157' ends teleporting on edge '9794056#0', time 2873.00.

And D4 is the source induction loop on the cyan lane on the last image.

**Comment by m-kro** [comment]
Ok, so both vehicles block each other just after entering the network. 
This is more related to vehicle insertion rules. Have a look at the [vehicle insertion options](https://sumo.dlr.de/docs/Definition_of_Vehicles,_Vehicle_Types,_and_Routes.html#a_vehicles_depart_and_arrival_parameter) (departLane, departPos) and if you want to set some [default in DFROUTER](https://sumo.dlr.de/docs/DFROUTER.html#defaults) directly to make this happen less frequently. I'd start using departLane=best...

**Comment by Smiley4ever21** [comment]
Thank you.
Just one more question.
Something wrong happens still in this Junction, but another direction. The errors are like：
Error: Vehicle '726-D1.10' will not be able to depart using the given velocity (unpriorised junction too close)!
![捕获1](https://user-images.githubusercontent.com/38075241/81659327-e5f05100-9439-11ea-9305-b4777cba7d00.PNG)

And the induction loops named 726-D1 located on the cyan lane below.
![捕获](https://user-images.githubusercontent.com/38075241/81659174-c22d0b00-9439-11ea-8abf-d8b1db4600ec.PNG)
The turn speed limit of the junction have changed to 30, and the depart speed of vehicle 726-D1.10 is 11.08.
Could you please tell me why it still says the junction is too close and cannot depart? Thank you.

**Comment by m-kro** [comment]
I don't have an idea why you get this message, especially without the current simulation files. Please understand that everybody also has other tasks to do... If you know how to compile SUMO by yourself, you could debug starting at this point in code:
https://github.com/eclipse/sumo/blob/aadafb2fdd5167a8693e526f86dc3f1c2242a9b0/src/microsim/MSLane.cpp#L755

**Comment by Smiley4ever21** [comment]
Thank you for your time.
