### ISSUE TITLE
plot_trajectories: allow filtering by edges 

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#6952]

**Comment by Mikroni998** [comment]
<img width="706" alt="Capture" src="https://user-images.githubusercontent.com/91965719/145842634-2278e98f-1c82-437e-8ac8-a7bb11be2b5c.PNG">

Hello
I tried to filter out two edges, but it doesn't recognize it. What is the syntax for this? I'd like to select multiple edges, more the 10 so I can plot trajectories on the main corridor

**Comment by namdre** [comment]
put a comma between the edge ids.
