### ISSUE TITLE
When does a vehicle conduct emergent deceleration?

### ISSUE THREAD

**Issue by fengbaozhiling1** [eclipse/sumo#6954]
Hello, I want to know how to judge whether a vehicle should conduct an emergent deceleration in SUMO if the 'emergencyDecel' parameter is equal to 5 m/s2. How to calculate the condition?

**Comment by namdre** [comment]
emergencyDecel events are triggered whenever the deceleration reaches a given fraction of the emergencyDecel Value. (by default his fraction is 1 but it can be configured with **--emergencydecel.warning-threshold**).
If emergencyDecel is close to the decel value, such events are more likely. 
Reasons for decelerating beyond 'decel' vary by carFollowModel (for Krauss, this only happens in problematic situations - i.e. a missing yellow phase, unsafe tau parameter, ..)  but for other models decel is not a sharp boundary and frequently exceeded.

**Comment by fengbaozhiling1** [comment]
> emergencyDecel events are triggered whenever the deceleration reaches a given fraction of the emergencyDecel Value. (by default his fraction is 1 but it can be configured with **--emergencydecel.warning-threshold**).
> If emergencyDecel is close to the decel value, such events are more likely.
> Reasons for decelerating beyond 'decel' vary by carFollowModel (for Krauss, this only happens in problematic situations - i.e. a missing yellow phase, unsafe tau parameter, ..) but for other models decel is not a sharp boundary and frequently exceeded.

Thank you, so when does the IDM model conduct an emergency deceleration if the 'Decel' is 3m/s2 and 'emergyDecel' is 5m/s2 for example. In addition, the speed of subject vehicle and the vehicle ahead are 30m/s and 10m/s, repectively, and the gap ahead is 10m. Could you clarify the calculation process? Or could you list the required information or parameters to show which condition will trigger the emergency in IDM model.

**Comment by namdre** [comment]
the IDM model gives no boundary on the necessary deceleration to avoid collision. Thus you will frequently encounter emergency deceleration when the difference between decel and emergencyDecel is low.  The likellyness of emergency deceleration depends also on the step-length / reaction time.
For the computation, refer to https://github.com/eclipse/sumo/blob/master/src/microsim/cfmodels/MSCFModel_IDM.cpp
