### ISSUE TITLE
default transparency for 3D view

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#6955]
The default transparency for colorings in the 3D mode should be different to make the vehicle still visible. It is however hard to map this consistently to the current data model. The easiest solution would be to let the current maximum value of 255 correspond to something like 50% transparency and do not allow the user to go beyond. The most flexible solution would be another parameter.

**Comment by namdre** [comment]
Even better would be to figure out how to re-color 3D-Models and get rid of that awful bubble.

**Comment by namdre** [comment]
see #5735

**Comment by angelobanse** [comment]
I think this issue can be closed
