### ISSUE TITLE
different edge list when writing vehroutes with exit times for unfinished routes

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#6956]
Currently activated exit times shorten the route to the list of edges that were really driven. If the option is not active the whole planned route is printed. Writing exit times should not affect the list of edges printed. The best solution is probably another option which allows to print the full planned route even if it was not driven to the end (so it may be longer than the list of exit times). The proposed default behavior is to print always only the edges that were really driven (changing current behavior).

**Comment by namdre** [comment]
Using -1 for the exit times of edges that were not driving if both options are combined?

**Comment by ambuehll** [comment]
That was super quick. Thanks!
