### ISSUE TITLE
How to obtain traffic flow parameters of multiple links?

### ISSUE THREAD

**Issue by Shiyunyang-seu** [eclipse/sumo#6958]
Hi, I want to use the speed, flow and density of several links of the network to do the analysis. How can I customize the designated roads to get them? Thanks for your help.

**Comment by namdre** [comment]
Let sumo generate output for all edges and then filter in post-processing.
https://sumo.dlr.de/docs/Simulation/Output/Lane-_or_Edge-based_Traffic_Measures.html

**Comment by Shiyunyang-seu** [comment]
Thanks for your replying.But according to your method, each edge can only output one group data. I want to get a group of data of different edges every 10 minutes in a day. Can this be realized?

**Comment by namdre** [comment]
Yes. by using the **freq** attribute:
```
<edgeData id="whatever" freq="600" file="outputfile.xml"/>

**Comment by Shiyunyang-seu** [comment]
Thanks for your helping! But when I define the edgeData like figure1, all the edges are output,see figure2. The interval ID equals to the edge ID,and repeated 5 times (because 5 edge IDS were input
![1](https://user-images.githubusercontent.com/55737075/80613498-f387fd00-8a6f-11ea-9857-252754ad6cc3.png)
![2](https://user-images.githubusercontent.com/55737075/80613517-f8e54780-8a6f-11ea-9a44-b6ae2dbddc27.png)

)

**Comment by namdre** [comment]
the id given in the edgeData definition is the name of  the dataset (so you can have multiple datasets in one file). Each dataset always contains all edges so you only need to define one.
After the simulation you can filter the dataset with your own postprocessing.

**Comment by Shiyunyang-seu** [comment]
Thanks a lot.  Another problem I need to confirm that there is no traffic flow in the output data. Whether sampleseconds * interval is the flow in this period of time.

**Comment by namdre** [comment]
see https://sumo.dlr.de/docs/Simulation/Output/Lane-_or_Edge-based_Traffic_Measures.html#how_to_aggregate_derive_further_values
