### ISSUE TITLE
netedit hangs for a while when unfinished polylines loaded

### ISSUE THREAD

**Issue by ZoltanBaksa** [eclipse/sumo#6959]
Hi,
I have created a bunch of polylines to indicate geo-traces of public transport routes. If I try to slide the network with mouse by pushing the mouse button above the network, it does not move and the netedit program hangs a few seconds. If I zoom out, and try to slide out of the network, it is moveable and netedit does not hang.
I can slide the network with keyboard buttons without any problem in any case and zoom level.
I use v1_5_0+1299-dacd81a970 version. I have checked the new release 1.6, it also shows the issue.
I can send the polygon definitions per email.

**Comment by palvarezlopez** [comment]
@ZoltanBaksa Thanks! I check it.

**Comment by ZoltanBaksa** [comment]
The hanging behaviour is also happens, when I want to move poly points

**Comment by ZoltanBaksa** [comment]
Hello Pablo,

I attach you the additional file, which I used on the network I sent you last time.

Regards
Zoltan

Feladó: Pablo Alvarez Lopez <notifications@github.com>
Küldve: 2020. április 29., szerda 16:12
Címzett: eclipse/sumo <sumo@noreply.github.com>
Másolatot kap: Baksa Zoltan (PS-TC/ENG12-Bp) <Zoltan.Baksa@hu.bosch.com>; Mention <mention@noreply.github.com>
Tárgy: Re: [eclipse/sumo] netedit hangs for a while when unfinished polylines loaded (#6959)


@ZoltanBaksa<https://github.com/ZoltanBaksa> Thanks! I check it.

**Comment by ZoltanBaksa** [comment]
I tested the issue a bit more. It seems, I have to hold down the mouse button and not move the mouse for at least 3 seconds, before the desired position is registered. After 3 seconds holding down the mouse, the network slide is also possible the

**Comment by palvarezlopez** [comment]
part of #7287
