### ISSUE TITLE
Geo-Coordinates Tranformation problem

### ISSUE THREAD

**Issue by Smiley4ever21** [eclipse/sumo#6960]
Hi,
I try to convert the polygons from shape file (lon,lat) into SUMO coordinates, using TraCI.

But from the result, it can be seen that the edges are far from the polygons. The net files I convert from the osm file.
[Geo.zip](https://github.com/eclipse/sumo/files/4552580/Geo.zip)

Could you please tell me why the edges and the polygons are not together? Thank you.

**Comment by namdre** [comment]
I cannot tell you why this is because I do not have the details of your conversion. However, you could try loading the polygons with geo-coordinates directly into sumo-gui to see if they match:
```<poly geo="true" shape="lon1,lat1 lon2,lat2 ..." .../>```

**Comment by Smiley4ever21** [comment]
Thank you, I tried, but it is still far from the net ring.
[Geo.zip](https://github.com/eclipse/sumo/files/4556784/Geo.zip)
Can I change the offset of the poly? will it help?

**Comment by namdre** [comment]
The poly file in your latest attachment does not contain geo-coordinates and therefore does not reflect my previous suggestion. 
You can use polyconvert to apply a fixed offset but you should first figure out why there is a mismatch.
