### ISSUE TITLE
Flow definition error

### ISSUE THREAD

**Issue by Shiyunyang-seu** [eclipse/sumo#6961]
Hi, I define the flow like figure1, but the warning indicates that I need to define depart time. However, Flow has no depart attribute(I thought this warning did not occur in the old version
![1](https://user-images.githubusercontent.com/55737075/80625117-503ee400-8a7f-11ea-8d7a-65e48a7529a5.png)
![2](https://user-images.githubusercontent.com/55737075/80625127-546b0180-8a7f-11ea-9773-43d484de4005.png)

).

**Comment by namdre** [comment]
for flows the 'begin' time is used. There must be some other elements (vehicles, trips, etc.) that depart after time 0 defined before the flows.

**Comment by Shiyunyang-seu** [comment]
Thanks for your replying. But I still can not understand why my definition can not work. And how can I realize the flow in the figure.
![1](https://user-images.githubusercontent.com/55737075/80632315-ae70c480-8a89-11ea-9d0e-2cd2d6006ea1.png)
Thanks a lot.

**Comment by namdre** [comment]
The second definition should not result in a warning message since the flows are sorted by begin time. If there is a warning, please zip up the input files and attach them to this ticket.

Note, that you can also specify times in H:M:S format (begin="17:0:0") as well as D:H:M:S if you need days.
