### ISSUE TITLE
noticable slowdown when selecting attribute in edgeData mode

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#6962]
once coloring becomes active, the framerate drops from ~100 FPS to ~5 FPS in a network with 500 edges

**Comment by namdre** [comment]
I have a strong suspicion that the calls
```
dataInterval->getMinimumGenericDataChildAttribute(filteredAttribute);
dataInterval->getMaximunGenericDataChildAttribute(filteredAttribute);
``` 
need to to use cached values instead of looping over the whole dataset!

**Comment by palvarezlopez** [comment]
@namdre can you check if current solution solves the problem?

**Comment by namdre** [comment]
The rendering is fast but there appear to be no more intermediate color hues (only the extreme ends of the rainbow are shown)

**Comment by palvarezlopez** [comment]
@namdre can you check if problem is solved?

**Comment by namdre** [comment]
works for me
