### ISSUE TITLE
optionally include person statistics in summary-output

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#6964]
via new boolean option **--summary-output.persons**

Values
- loadedPersons
- insertedPersons
- arrivedPersons
- walkingPersons
- stoppingPersons
- ridingPersons
- waitingForRidePersons
- jammedPersons

**Comment by namdre** [comment]
@lcodeca  (SAGA)

@behrisch would it be better to write these values into a separate file (**--person-sumary-output**) instead and avoid the 'Persons' suffix for all attributes?

**Comment by behrisch** [comment]
> @behrisch would it be better to write these values into a separate file (**--person-sumary-output**) instead and avoid the 'Persons' suffix for all attributes?

Yes, I think so
