### ISSUE TITLE
Netfile from OSM have different offset everytime

### ISSUE THREAD

**Issue by Smiley4ever21** [eclipse/sumo#6965]
Hallo,
I download map from OSM three times, all of them contain the same area, but with different scope.
And the poly file is the same, for these areas. However, for the first scope (figure 1) the poly and the net file match, but the other two do not match. 
[netoffset.zip](https://github.com/eclipse/sumo/files/4557215/netoffset.zip)

Is it true that the osm have different offset everytime I download? And how can I know the default offset from the osm, to make the poly and net file match to eachother? Thank you.

**Comment by namdre** [comment]
If you safe the poly in geo format (polyconvert option --proj.plain-geo) then it will always match.

**Comment by Smiley4ever21** [comment]
[Geo.zip](https://github.com/eclipse/sumo/files/4558463/Geo.zip)
I’ve converted into geo format, but it still does not match...only one of the nework match.

**Comment by namdre** [comment]
The polygons are correct but the network has an invalid geo-reference. I recommend patching the 
netOffset="-344875.04,-5690557.05" in the location element until you get some a reference point to align (i.e. the roundabout at junction:1615342473 should end up at 51.437710, 6.780503)

**Comment by Smiley4ever21** [comment]
Do you know why this network has a invalid geo-reference? Is it deleted while I convert it from the osm file? Because I still have the osm file, could I get the geo reference from osm? Thank you.
[osm.zip](https://github.com/eclipse/sumo/files/4558576/osm.zip)

**Comment by Smiley4ever21** [comment]
OK, thank you. Only for information: I used Version 1.3.1 to convert the net file from osm.

**Comment by Smiley4ever21** [comment]
Hi, can I also use geo-format in TAZ? OR in TAZ it must be in XY format? Thank you.

**Comment by namdre** [comment]
The functionality of TAZ when defining trips with fromTaz, toTaz will work regardless of shape (it uses the edges that belong to the TAZ). Visualization of TAZ will only work with XY at the moment.
