### ISSUE TITLE
Some questions about junction setting.

### ISSUE THREAD

**Issue by Sheldon-Zhou1997** [eclipse/sumo#6969]
<img width="495" alt="2020-05-01 15-51-49屏幕截图" src="https://user-images.githubusercontent.com/52645665/80791961-cc434400-8bc5-11ea-8de6-081326c90a2e.png">

**Comment by Sheldon-Zhou1997** [comment]
Why is the junction point at the center of the edge in the left one and the  junction point at the left of the edge in the right one? How could I set the right point to the center?

**Comment by m-kro** [comment]
See SUMO docs about [edge spreadtype](https://sumo.dlr.de/docs/Networks/PlainXML.html#spreadtype) attribute.
