### ISSUE TITLE
How to calculate the safe speed in IDM model 

### ISSUE THREAD

**Issue by fengbaozhiling1** [eclipse/sumo#6973]
Hello, I have a question. According to the speed mode (0xb3), the big0 is regard safe speed, so how to calculate the safe speed in IDM model? Would you mind giving a small example?

**Comment by namdre** [comment]
Look at the code or call traci.vehicle.getFollowSpeed(...)
https://github.com/eclipse/sumo/blob/master/src/microsim/cfmodels/MSCFModel_IDM.cpp
