### ISSUE TITLE
Netconvert -vehicles can not find their ways

### ISSUE THREAD

**Issue by Shiyunyang-seu** [eclipse/sumo#6974]
Hi, I check the network(convert by Nerconvert from osm) and I find some junctions can not direct the vehicles correctly which making some vehicles can not find their ways. I used the command like figure2, how can I improve the network.
![1](https://user-images.githubusercontent.com/55737075/80870789-53361080-8cdb-11ea-8e1d-75f35db3d6f9.png)
![2](https://user-images.githubusercontent.com/55737075/80870794-59c48800-8cdb-11ea-8341-1a151cad8436.png)

**Comment by namdre** [comment]
You can use Netedit connection-mode: https://sumo.dlr.de/docs/NETEDIT.html#edit_connections
