### ISSUE TITLE
[QUERY] Get queue output via Additional Files

### ISSUE THREAD

**Issue by arsenious** [eclipse/sumo#6976]
Hi

I would like to know how to get the queue output XML file, by specifying this inside the additional file, and not by modifying the sumo command using the option --queue-output

This ability is available for other Edge measures https://sumo.dlr.de/docs/Simulation/Output/Lane-_or_Edge-based_Traffic_Measures.html 

Thanks

**Comment by namdre** [comment]
**--queue-output** cannot be specified in an additional file (edgeData is special that way). However, you can add the entry `<queue-output value="FILENAME"/>` to a .sumocfg file and load this.
