### ISSUE TITLE
plot_visualization.py support plotting person trajectories

### ISSUE THREAD

**Issue by Shiyunyang-seu** [eclipse/sumo#6978]
Hi, I run the simulation and acquire the fcd file and the plot_visualization is also utilized to get the graph, but no matter speed, time and other attributes can't be displayed correctly in the graph
[fcd.zip](https://github.com/eclipse/sumo/files/4573634/fcd.zip)
.

**Comment by namdre** [comment]
currently, only vehicle trajectories are supported

**Comment by namdre** [comment]
you can now set option **--persons** to plot person trajectories.
