### ISSUE TITLE
merging osm tram lanes into mixed traffic lanes

### ISSUE THREAD

**Issue by ArmelliniMG** [eclipse/sumo#6980]
[tram_osmscenarios.zip](https://github.com/eclipse/sumo/files/4575159/tram_osmscenarios.zip)

**Comment by behrisch** [comment]
@ArmelliniMG Can you please give a little context here?

**Comment by ArmelliniMG** [comment]
When OSM networks are imported in SUMO, lanes used by trams and vehicles are not built, but two different edges (one for trams and one for vehicles) are created one above the other (see picture). This happens because the railway network is considered separately in OSM. A possible solution would be to check if the edges are the same based on the location and then merge them. (Jakob is aware of this).
The Zip folder contains two small OSM areas as examples. 

![grafik](https://user-images.githubusercontent.com/48476390/81164051-fb73ff80-8f8f-11ea-987b-7318cd754086.png)

**Comment by ZoltanBaksa** [comment]
same issue as #5850

**Comment by namdre** [comment]
It will require some matching/heuristics because the osm-ways do not have common nodes.

**Comment by namdre** [comment]
Most of the tram edges in the test networks are correctly joined now. The algorithm also works when using option **--junctions.join**. Public transport routes are adapted as well and the output gives a smooth simulation (via ptlines2flows.py).

It may be useful to define a longitudinal threshold for matching tram edges with road edges to handle alignment errors (responsible for one case of an un-joined tram edge).

**Comment by namdre** [comment]
found another crash when using the whole BS network )-:
