### ISSUE TITLE
draw parkingArea roadsideCapacity slots

### ISSUE THREAD

**Issue by MelanieWeber** [eclipse/sumo#6982]

**Comment by ZoltanBaksa** [comment]
The reloading possibility would be great in case of demand elements to.

**Comment by namdre** [comment]
@palvarezlopez The rendering of parkingArea slots should try to reuse code from the MSParkingArea constructor. When refactoring the microsim code, extra care must be taken because the changes are mostly visual and we do not have automated tests that would catch regression.

**Comment by namdre** [comment]
@MelanieWeber as a workaround until #7897 you can use edge template functionality which also stores this attribute.

**Comment by namdre** [comment]
@MelanieWeber regarding point 3: parking space elements are already supported by netedit. What else do you need?
