### ISSUE TITLE
Why the detector can not be loaded today

### ISSUE THREAD

**Issue by fengbaozhiling1** [eclipse/sumo#6994]
I set <additional-files value="e1detector.xml"/> in the .sumocfg file. I run the file in last month, and it worked well. Hower, when I try to run the same file today, it reports an error ""
![image](https://user-images.githubusercontent.com/44236971/81257324-8d9a0780-9065-11ea-8acb-2fa8bce89082.png)

[Desktop.zip](https://github.com/eclipse/sumo/files/4590843/Desktop.zip)
Could you help me find the correct code? How to write the detector information in .sumocfg file?Thank you!

**Comment by namdre** [comment]
The detector is fine and being loaded. The warning you are seeing concerns automatic XML-validation using schema files: https://sumo.dlr.de/docs/FAQ.html#whats_the_deal_with_schema_resolution_warnings_xsd_errors
Probably you changed SUMO_HOME or moved folders around.
