### ISSUE TITLE
How to add continuous multi day traffic flow (distinguish weekends and weekdays)

### ISSUE THREAD

**Issue by Shiyunyang-seu** [eclipse/sumo#6998]
Hi, how can I use sumo's tools to generate continuous traffic flow for many days, and satisfy the characteristics of large peak traffic in the morning and evening.

**Comment by namdre** [comment]
It depends on the tool you are using to create your traffic.
- If you have a whole-day OD-Matrix, you can use the od2trips option **--timeline** to scale the matrix with an hourly-demand-factor-curve.
- If you are using randomTrips.py you can call it repeatedly with a different value for **--begin --end --period** to get the different hours. (you also need to use the **--prefix** option to avoid vehicle id clashes)

**Comment by Shiyunyang-seu** [comment]
Thanks for you replying. For example, if I use randomTrips.py, how can I get a 7-day trip plan? 
Like -b 0 -e 25200 -p ((25200 - 0) / 500), -b 25211 -e 28800 -p ((28800 - 25211) / 2000)(morning peak)... repeatedly?

**Comment by behrisch** [comment]
Yes
