### ISSUE TITLE
closingReroute is ignored by the first vehicle in routeFile when it departs on a closed edge

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#6999]
the vehicle is loaded via https://github.com/eclipse/sumo/blob/b0e7d8c0a92ec3b6fae800008b59154d449d2e19/src/netload/NLBuilder.cpp#L297
which comes before the first call to https://github.com/eclipse/sumo/blob/b0e7d8c0a92ec3b6fae800008b59154d449d2e19/src/microsim/MSNet.cpp#L553 (where the edge permissions are updated)

related to #2561

**Comment by namdre** [comment]
@behrisch Is the loadRoutes call only for TraCI-convenience?

**Comment by behrisch** [comment]
Yes, I think so.

**Comment by namdre** [comment]
I'm not sure how useful it is because it's very hard to figure out which vehicles are actually loaded by this. (#3593).

**Comment by behrisch** [comment]
In my opinion, a valid approach for solving this would also be that rerouters should only influence the routing decision of vehicles which touched the rerouter edge.

**Comment by namdre** [comment]
I think the current behavior of trips that take into account hard road closures regardless of rerouterEdge at depart-time-rerouting is an important feature to model "well-known" closings (and much more convenient then placing rerouter edges on the whole network).

**Comment by behrisch** [comment]
OK, but if we somehow insist on the fact that a rerouter must be "somehow" located (only gets active once a vehicle has entered one of the edges belonging to the rerouter) then it is just a matter of defining a "global" rerouter (or one with a center and a radius), so we could simply add another syntax option to the rerouter (yay). Or do you fear that it is computationally to costly to have "global" rerouters?

**Comment by namdre** [comment]
In fact, I do think it's a bad idea because rerouter edges trigger quite a bit of computation upon entering:
- a linear check through the whole route to see if the current vehicle is affected
- for affected vehicles, this would also amount to triggering a new route computation on every edge

Frankly, I would not insist that rerouters have to be located somewhere. I think, using them for "hard" closings without signage is useful in itself. Of course you could invent a new structure for this (variableLaneClosing) but I don't think this is necessary. 

My suggestion to solve the original issues is to add an additional check upon departure for all vehicles to resolve inconsistencies for vehicles loaded before the first simulation step.

**Comment by behrisch** [comment]
We could mitigate the effect of triggering new computations by somehow tracking which rerouters were already handled by the vehicle but it is probably not worth the effort. I think it is counterintuitive that the rerouter has a location but still has a global effect not only concerning edge permissions but concerning routing decisions. And I even more dislike that this is triggered at load time. So maybe we should always delay the initial routing to insertion time in the presence of rerouters (this also opens up the topic of taz routing but this may be too much for this poor little ticket :-))

**Comment by namdre** [comment]
Already, the routing does not happen at load time but at insertion time. The inconsistency comes only from the "departEdge allows vClass check" which happens at load time (i've updated the ticket name to make this more clear).

I think it is useful to do some checks early (because it is annoying to have the simulation error out after already simulating for some time). 
However, we could always postponed the check to insertion time if any rerouters have been loaded.

**Comment by behrisch** [comment]
I am not sure maybe we should remove this "departEdge allows vClass check" on vehicle creation completely. In a way it is not different from "there is no route between start and end edge". I just found another bug related to this one #7023

**Comment by namdre** [comment]
Hm. There is still the hasValidRoute-check in MSBaseVehicle which would be triggered for vehicles (not trips). However, delaying all these checks to insertion time would be fine with me.

My remark regarding "earlier checks are better" are moot for larger route files anyway because loading of later vehicles does come later in the simulation anyway.

**Comment by behrisch** [comment]
And there is also traci/libsumo where people are always keen on early feedback. Maybe we can discuss this with the group next week.
