### ISSUE TITLE
Still have deadlock on junction in sublane simulation

### ISSUE THREAD

**Issue by cuijiaxun** [eclipse/sumo#7003]
sumo version **1.6.0**
when merging from two sublanes, got negative leader headway, and thus cyclic leader relations, and thus deadlock.

**Comment by namdre** [comment]
Please attach minimal example scenario by zipping all the necessary files and note the time/location of the incident.

**Comment by cuijiaxun** [comment]
Sorry I do not know how to provide a smallest incident as I had this problem when using the Berkeley's Flow. When the junction is relatively long and the two entering lane have a long distance overlapped, i.e. the junction can contain multiple vehicles, one of them would stop[Emergency brake] because it has a leader with negative headway.

**Comment by namdre** [comment]
Can you recreate the incident without using flow? The requirement of "minimality" is not meant in a very strong way. It would be sufficient if you have a scenario that can simulate up to the time of the incident taking minutes rather than hours to do so.

**Comment by namdre** [comment]
Closing due to lack of feedback. Also likely a duplicate of similar issues that were recently fixed.
