### ISSUE TITLE
traci.person.appendWalkingStage() cannot work properly

### ISSUE THREAD

**Issue by heathcliffYang** [eclipse/sumo#7008]
After I added person into the network, error occurs when I use `traci.person.appendWalkingStage()` to have it walk.

Here is my part of code:
```python
traci.person.add(personID, source, pos=0, typeID="person")
traci.person.appendWalkingStage(personID, ["3657","3658"], 10)
```
The type defined in .rou.xml:
```xml
<vType id="person" length=".25" minGap="0" guiShape="pedestrian" width=".25" maxSpeed="0.5" color="1,0.2,0.2"/>
```
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/traci/_person.py", line 271, in appendWalkingStage
    self._connection._sendExact()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/traci/connection.py", line 106, in _sendExact
    raise TraCIException(err, prefix[1], _RESULTS[prefix[2]])
traci.exceptions.TraCIException: Fourth parameter (duration) requires a double.

Thank you!

**Comment by namdre** [comment]
It looks as if you are using a traci library written for version 1.2.0 or older with a sumo version of 1.3.0 or newer. There was a small change in protocol which causes this message. It is generally recommended to use a traci library that matches your sumo version.

**Comment by heathcliffYang** [comment]
Because I use brew to install sumo, did it upgrade traci library also?
How could I only upgrade traci library?

Jakob Erdmann <notifications@github.com> 於 2020年5月13日 週三 下午2:36寫道：

**Comment by namdre** [comment]
Most likely you installed traci from another package. Try instead using the traci in your SUMO_HOME folder.
