### ISSUE TITLE
Crash recomputing big Network in debug mode

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#7010]
Network: simo\members\alvarez\berlin-demand\osm.net.xml

Line: NBNode.cpp/33

 std::sort(allEdges.begin(), allEdges.end(), NBContHelper::edge_by_angle_to_nodeShapeCentroid_sorter(this));

Problem: _STL_VERIFY(!_Pred(_Right, _Left), "invalid comparator");

**Comment by namdre** [comment]
I cannot reproduce it on Linux (@palvarezlopez can you?)

**Comment by namdre** [comment]
I can reproduce it on Windows, though
