### ISSUE TITLE
Problem of plot_net_dump.py 

### ISSUE THREAD

**Issue by Shiyunyang-seu** [eclipse/sumo#7011]
Hi, I want to ask how can I obtain the dumps file to be the input -i of plot_net_dump.py?
![Q](https://user-images.githubusercontent.com/55737075/81689885-465cae00-948d-11ea-8e93-58da981125d4.jpg)

**Comment by behrisch** [comment]
You need to generate meanData edge dumps see https://sumo.dlr.de/docs/Simulation/Output/Lane-_or_Edge-based_Traffic_Measures.html

**Comment by Shiyunyang-seu** [comment]
Thanks for you reply. And I output the file as tutorial, but an error occurred.
![Q](https://user-images.githubusercontent.com/55737075/81692486-0992b600-9491-11ea-82bb-1c77d1cb8880.png)

**Comment by behrisch** [comment]
XML parsers have sometimes strange ways of saying "file not found". Are you 100% sure the filename is correct?

**Comment by Shiyunyang-seu** [comment]
I tried again. It seems that I can't read the information of the dump file accurately. I don't know what's the problem is. Attached please find the test file.
[test.zip](https://github.com/eclipse/sumo/files/4615819/test.zip)

**Comment by Shiyunyang-seu** [comment]
![R)E6}`LDCBEDJ4`6 R)5RSB](https://user-images.githubusercontent.com/55737075/81887815-8ed1b400-95d2-11ea-82db-6173cfc111bf.png)
The widthDump can not be created.

**Comment by behrisch** [comment]
A simple `tools\visualization\plot_net_dump.py -n osm.net.xml -i output.data3.xml,output.data3.xml -o test.png` works here. Please note that you have to give the input file twice (I just fixed that in the code).
