### ISSUE TITLE
How to set up the mode of traci getNeighbors(vehicleID, mode)?

### ISSUE THREAD

**Issue by tanghui0102** [eclipse/sumo#7021]
Hi, I am confused about the mode of getNeighbors(vehID, mode) for long time.

The doc in official website says the mode is a bitset, and indicates how to set up.

Could anybody have ideas about the setup of mode.

I set the mode like 0b....., 0o....., ox.....,but only get the ego_vehicle's followers, cannot get other directions' vehicles.

Such as 0b01000000, get the ego_vehicle's followers vehicles.
`print(traci.vehicle.getNeighbors("1",  0b01000000)`

**Comment by tanghui0102** [comment]
Nice, when I set the mode to 0b00000010, the function can get many vehicle around the ego_vehicle.

![image](https://user-images.githubusercontent.com/47203090/81893564-84b6b200-95e0-11ea-9801-45d5454a7d31.png)
![image](https://user-images.githubusercontent.com/47203090/81893595-8e401a00-95e0-11ea-9a00-0d73efa1046b.png)
![image](https://user-images.githubusercontent.com/47203090/81893637-96985500-95e0-11ea-8681-955eec24edda.png)

**Comment by tanghui0102** [comment]
After my verification, the setting method obtains the vehicleID in front of the ego_vehicle.

**Comment by namdre** [comment]
Instead of calling getNeighbors and memorizing all the bits in the bitset, you can call the high-level functions such as
- getLeftLeaders,
- getRightFolowers
- getLeader
....
