### ISSUE TITLE
ignore-route-errors creates invalid state file

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#7023]
If I have a vehicle with a trip from taz to taz which cannot depart on any edge of the source taz (due to permissions) it will still create an (invalid) route and write it to the state file. On loading the state file sumo will throw an error because the departEdge does not allow the vehicle.
Wird das state file auch mit ignore-route-errors geladen, crashed sumo weil der state handler nicht darauf vorbereitet ist, dass die Fahrzeugerzeugung fehlschlagen kann und in closeVehicle immer von einem gültigen Fahrzeug ausgeht.

**Comment by namdre** [comment]
@behrisch would you prefer that invalid routes are excluded from the state file (related to #3542)?

**Comment by behrisch** [comment]
I depends a little on the "level" of invalidity. I think if sumo discards the vehicle even if ignore-route-errors is set then it should not appear in the state file as well.

**Comment by behrisch** [comment]
Just as a side note: I already tried to make up a small test for this ticket but failed, so the description might not be accurate concerning the crash I had with the Berlin scenario.

**Comment by behrisch** [comment]
I cannot reproduce this with the current sumo at least not when loading the state from the hour before. Should we "repair" the state parsing nevertheless, just for defensive programming? Or is this not needed because the MS(Base)Vehicle constructor is not supposed to throw exceptions any longer?

**Comment by namdre** [comment]
The constructor should no longer throw. I'm still in favor of defensive programming.

**Comment by behrisch** [comment]
Just for the record: Even when starting the scenario from start, the error does not show up anymore.
