### ISSUE TITLE
I want to add a vehicle without car-following model and lane-change model predefined in Sumo to perform a lane-change and overtake a car.

### ISSUE THREAD

**Issue by Sheldon-Zhou1997** [eclipse/sumo#7031]
I want to add a vehicle without car-following model and lane-change model predifined in Sumo to perform a lane-change and overtake a car via traci like bellow.What should I do?

**Comment by Sheldon-Zhou1997** [comment]
![图片](https://user-images.githubusercontent.com/52645665/82148513-0f203f80-9887-11ea-995b-8db4760fd478.png)

**Comment by namdre** [comment]
to disable the carFollowingModel call
- traci.vehicle.setSpeedMode(0)
- traci.vehicle.setSpeed(desiredSpeed)

to disable laneChangeModel call
- traci.vehicle.setLaneChangeMode(0)

to trigger a lanechange call
- traci.vehicle.changeLane or changeLaneRelative

**Comment by Sheldon-Zhou1997** [comment]
![IMG_20200522_212048](https://user-images.githubusercontent.com/52645665/82671895-2a69c100-9c72-11ea-8792-456a77697ebf.jpg)

**Comment by Sheldon-Zhou1997** [comment]
I want a vehicle above to move to pos4 from pos1 via pos2 and pos3 without  car-following model and lane-change model predifined in Sumo by traci. What should I do? Thank you!

**Comment by namdre** [comment]
activate either of the two models for that: https://sumo.dlr.de/docs/Simulation/SublaneModel.html
