### ISSUE TITLE
long vehicle fails to pass short edge

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#7035]
If the space requirements of a vehicle exceed the segment capacity (length * numLanes) it should nevertheless be able to enter if the segment is empty.
This is currently checked via `myOccupancy == 0`. 
However, due to numerical inaccuracy (x + y - x - y != 0),  the occupancy can be different from 0 for an empty segment.

**Comment by namdre** [comment]
The problem occurs when there are edges in the network where capacity  (length * laneNumber) is less than the brutto length (length+minGap) of a long vehicle, yet it is long enough to accomodate two short vehicles at the same time.

**Comment by namdre** [comment]
@ambuehll  I recommend updating as your simulation might be affected by this.

**Comment by ambuehll** [comment]
Thanks! 👍  I saw the ticket a few minutes ago and thought the same. I Will let you know if there is a substantial change.
