### ISSUE TITLE
Question for input

### ISSUE THREAD

**Issue by Shiyunyang-seu** [eclipse/sumo#7039]
Hello, I want to know if I have the trajectory data (CSV file, including coordinates, time, speed) of pedestrians or vehicles extracted through video, can I define pedestrians and vehicles according to this data in sumo?

**Comment by namdre** [comment]
Usually, the point of running a simulation is to obtain such trajectory data.
Hence, importing this type of data has only limited supported.

What you can do:
- define a vehicle `<trip fromLonLat="lon0,lat0" toLonLat="lonk,latk"  viaLonLat="lon1,lat1 lon2,lat2 ..."/>`
- define a person `<personTrip fromLonLat="lon0,lat0" toLonLat="lonk,latk"/>`

and then process these definitions with duarouter to obtain vehicle routes and person plans.
However, this process will ignore exact positions and speeds.

We do have long term plans for something more detailed: #1922
