### ISSUE TITLE
question about routing.

### ISSUE THREAD

**Issue by Sheldon-Zhou1997** [eclipse/sumo#7047]
I want vehicles in lane 4 flow into lane 7 and vehicles in lane1,2,3 flow into lane 5,6 evenly,but I can't do it because two different flow seem cannot flow into the same lane.

**Comment by Sheldon-Zhou1997** [comment]
<img width="722" alt="QQ截图20200519195428" src="https://user-images.githubusercontent.com/52645665/82394490-c7aed480-9a7b-11ea-88e5-8734307ba924.png">

**Comment by namdre** [comment]
you can change to node type to 'zipper' and create two connections to the same target lane (ctrl+click in netedit).
