### ISSUE TITLE
About the execution time of the call to Traci through the python API

### ISSUE THREAD

**Issue by chengaletai** [eclipse/sumo#7048]
Question：
     I've written a new lane-changing and car-following model in python in a Windows environment and implemented it on SUMO by calling Traci to get the vehicle information. When the number of simulated vehicles increases, the vehicle running state displayed by the SUMO GUI is stuck. After checking, I found that calling a Traci function, such as getSpeed, requires 0.001 seconds of execution, so if the loop is called 100 times, the execution time will also increase, so the simulation speed will slow down. 
    The reason for the slow down is as I said, is it because of the Traci execution time? Or maybe it's just the logic of my python program.If this is the case, do I need to modify the source code for the model to run smoothly

**Comment by namdre** [comment]
Try setting a small delay in the gui (between 10 and 100) and check whether you get smooth gui updates this way.

**Comment by chengaletai** [comment]
> Try setting a small delay in the gui (between 10 and 100) and check whether you get smooth gui updates this way.

I tried to modify the delay and simulation step size, but it was still a little bit slow, although it was improved

**Comment by namdre** [comment]
Regarding your question
1) calling lots of traci functions takes significant time
2) your own code very likely also requires significant

Regarding the speed of 1) you can switch to faster communication by using libsumo (https://sumo.dlr.de/docs/Libsumo.html)

Regarding 2) you could try to benchmark your code and figure out how to make it run faster
