### ISSUE TITLE
Problem for traci

### ISSUE THREAD

**Issue by Shiyunyang-seu** [eclipse/sumo#7050]
Hi, I tried to use traci to control the vehicle, but the route can not be add when I define the startedge and endedge(see figure). Another problem is that when my traci_test file occours some error, it will tell me that the connection has be actived and I must reopen the spyder to solve it(Maybe the sumo do not close correctly and how can I avoid it).
![traci](https://user-images.githubusercontent.com/55737075/82473522-45b2c000-9afc-11ea-9ebd-e8fc58a74601.jpg)

**Comment by behrisch** [comment]
You can only add a route with the same id once. Your script does that in every step. The same holds for the vehicle. For the errors, you could catch the TraCIException and call traci.close in every case.
