### ISSUE TITLE
Questions relating to lane changes

### ISSUE THREAD

**Issue by Timor7hao** [eclipse/sumo#7053]
Dear professor:
    I would like to know how to adjust the lane change position of the vehicle. As shown in the picture, there are traffic lights ahead. The left-turn vehicle starts to change lanes long before (the position of the red box).How do you adjust this position?I have tried to add the attribute lcStrategic="0" in the flow, but it has no effect.
![111](https://user-images.githubusercontent.com/38340783/82561293-b6fa7d80-9ba5-11ea-825f-9129021dd9ae.png)
    Thank you very much! Best wishes to you!

student chen

**Comment by namdre** [comment]
the attribute must be added in a `<vType>` and that type must be assigned to the flow.
