### ISSUE TITLE
sumolib.net.edge.getType() not available

### ISSUE THREAD

**Issue by marcelreppi** [eclipse/sumo#7054]
Hello,

the [sumolib documentation](https://sumo.dlr.de/pydoc/sumolib.net.edge.html) shows that sumolib.net.edge.getType() should be available but I get the following error:
```
AttributeError: 'Edge' object has no attribute 'getType'
```
I have checked the source code and I also couldn't find its implementation.
I need this functionality. Could you bring it back?

In the meantime I'll try to better understand how sumolib works and see if I can implement it myself.

Thanks!

**Comment by marcelreppi** [comment]
Implemented it by myself.

Wouldn't it still be useful to bring this functionality back in general?

**Comment by m-kro** [comment]
I think the sumolib documentation is generated automatically from the code itself. The method is there:
https://github.com/eclipse/sumo/blob/a639193a5f88e236313e531bff28a33a13c01f2a/tools/sumolib/net/edge.py#L74
Did you maybe forget the round brackets? I think the AttributeError would be thrown in that case...

**Comment by marcelreppi** [comment]
I did used it correctly.

I just realized that the last commit in that file where `getType` was added is 16 days ago so it is not included in the latest 1.6.0 release.
I just downloaded the nightly version and there I was able to find it.

Thanks for the hint and sorry for the confusion!
