### ISSUE TITLE
Travel time from simulation.findRoute

### ISSUE THREAD

**Issue by jylee3302** [eclipse/sumo#7055]
Hi,

I want to know the difference between

traci.simulation.findRoute(origin, destination).travelTime
and
traci.lane.getLength(origin_0) / traci.lane.getMaxSpeed(origin_0) +
traci.lane.getLength(destination_0) / traci.lane.getMaxSpeed(destination_0)

There's no vehicles loaded in the network, and origin - destination are directly connected two links, so I thought these two will be the same. But, findRoute.travelTime was little bit larger than the lower one. No weights of anything was assumed.

Is findRoute assuming acceleration/deceleration times? What is causing the difference between two?

**Comment by namdre** [comment]
findRoute accounts for the time to pass the intersection between origin_0 and destination_0 (even if there is no intersection, the so-called internal lane between origin and destination lane has a minimum lenght of 0.1m).
