### ISSUE TITLE
Could not connect to TraCI server;

### ISSUE THREAD

**Issue by doubley529** [eclipse/sumo#7061]
HELLO,when i run in omnet, always come up this bug. please help me, thanks!
** Event #1  t=0  RSUExampleScenario.manager (TraCIScenarioManagerLaunchd, id=6)  on selfmsg connect (omnetpp::cMessage, id=14)

WARN:Could not connect to TraCI server; error message: 0: No error -- Will retry in 1 second(s).

**Comment by schwamborn** [comment]
Since this seems to be related to omnetpp, have you tried asking the guys over at https://github.com/omnetpp/omnetpp?
