### ISSUE TITLE
Charging Station use like parking

### ISSUE THREAD

**Issue by khibuya** [eclipse/sumo#7068]
How can I use charging station outside of network? Parking area has an area outside the road network, I want to use charging station like parking.

**Comment by namdre** [comment]
Enhancement ideas:
- with vehicle stop attribute `parking="true"`, charging should still work but the vehicle is outside the road network
- when vehicle stop attributes `chargingStation` and `parkingArea` are both used (and both object locations along the lane are overlapping), the vehicle should be placed according to the parkingArea rules and it should be charged during the stop.

**Comment by khibuya** [comment]
thank you so much !!
