### ISSUE TITLE
implausible routes with a single edge

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#7071]
are probably not implausible

**Comment by namdre** [comment]
the min-dist, and min-air-dist options are 0 by default. Which implausibility metric does this result come from?

**Comment by behrisch** [comment]
The air distance metric fails. It is probably an artefact of --no-internal-links. There are several edges where the length (as given by the length attribute of the first lane) is much larger than the euclidean distance between the first and the last point of the shape. Maybe it would be better to use start-end-junction distance in those networks.

**Comment by namdre** [comment]
Yes. That would probably help (many more things can go wrong with air distance when edges have lengt/geometry factor != 1).
