### ISSUE TITLE
Departed ID list subscription result inconsistent for vehicle at timestep 0

### ISSUE THREAD

**Issue by marcelreppi** [eclipse/sumo#7076]
Hello,

when a vehicle has departure time 00:00:00 it shows up twice in the subscription result for
`tc.VAR_DEPARTED_VEHICLES_IDS`.
Once after step 0 and then also after step 1.
This does not happen for the second vehicle departing at 00:00:10.

I have attached a minimum failing example.

Best regards
Marcel

[repeated-departed-ids.zip](https://github.com/eclipse/sumo/files/4682496/repeated-departed-ids.zip)

**Comment by namdre** [comment]
The observed behavior is not a bug: the effect of calling traci.simulationStep(step=0)  (which is also the default argument) is to advance the simulation by one step from time 0 to time 1.
The next call of traci.simulationStep(step=1) advances the simulation to the target step of 1 (effectively doing nothing). Hence, both steps report the same subscription result.

If you always call simulationStep without argument you can easily avoid this.

**Comment by marcelreppi** [comment]
Thank you very much for the clarification!
