### ISSUE TITLE
--route-step has no effect on initial vehicle load

### ISSUE THREAD

**Issue by marcelreppi** [eclipse/sumo#7077]
Hello,

I have noticed that setting `--route-step` to for example 3600 has no effect on the initial amount of vehicles that are loaded in the simulation.
For me it only took effect after the second vehicle has departed.

I have attached an example scenario.

[route-steps-no-initial-effect.zip](https://github.com/eclipse/sumo/files/4682671/route-steps-no-initial-effect.zip)

**Comment by namdre** [comment]
It's a known issue: #3593.
Thanks for reporting though.
