### ISSUE TITLE
The corresponding relationship between OSM and net.xml

### ISSUE THREAD

**Issue by Shiyunyang-seu** [eclipse/sumo#7091]
Hi, I have a problem right now that I want to do visualization based on the original OSM file, but  my output is based on net.xml. So can I know exactly how the way in the original OSM file relates to the edges in net.xml.Or If I know the longitude and latitude of each edge, the problem also can be solved( but after using netconvert, the longitude and latitude  has been changed).
In addition, in net.xml some of the edges' starting point is not node, as shown in the figure, which also puzzles me.
Thanks in advance!
![edge](https://user-images.githubusercontent.com/55737075/83149126-567eb980-a12c-11ea-9fb4-74b012a7bac0.png)

**Comment by namdre** [comment]
see https://sumo.dlr.de/docs/Networks/Import/OpenStreetMap.html#relationship_between_osm_ids_and_sumo-ids

the cluster ids result from joining multiple OSM ids into a single .net.xml junction.

**Comment by Shiyunyang-seu** [comment]
Thanks for your answer. But I also want to know whether I can get the longitude and latitude of each edge.

**Comment by namdre** [comment]
That should always work for osm-derived networks: https://sumo.dlr.de/docs/Geo-Coordinates.html
