### ISSUE TITLE
How to connect Unity3d with SUMO

### ISSUE THREAD

**Issue by fengbaozhiling1** [eclipse/sumo#7093]
Could you provide some suggestions for SUMO and unity connection?
I have watched the video in youtube but I still could not achieve the connection. Could you show the steps in details?
Thank you so much!

**Comment by namdre** [comment]
The general answer is https://sumo.dlr.de/docs/TraCI.html
Details are beyond the scope of this issue tracker. Please ask the original authors of that coupling (The people that maintain SUMO were not involved).
