### ISSUE TITLE
Building with VSCODE （windows） and problems came

### ISSUE THREAD

**Issue by HolyBugger** [eclipse/sumo#7096]
![微信图片_20200601203704](https://user-images.githubusercontent.com/16741263/83409777-aff62980-a447-11ea-896f-37375e8e8058.jpg)
How can I solve the problems about identifier "SIGUSR1" and "SIGUSR2" where my IDE was VSCode in Windows?
Is there something wrong with the compiler?

**Comment by behrisch** [comment]
@HolyBugger It would help if you can tell us which compiler (I suppose gcc) and environment you use. There are currently not too many people trying gcc on Windows. Also is this the current Git repository or which release do you try?

**Comment by HolyBugger** [comment]
I am using gcc from mingw64 on Windows. And the version of my SUMO is the latest release from github.
Please give some advise!
Thx!

**Comment by RobertHilbrich** [comment]
You could try to use the Windows 10 SDK instead of the GCC from the mingw64 suite. Using the gcc on Windows might make the build system think, that you are actually on Linux, so it expects certain signals to be present. So, if you are not intent on using gcc, try the Windows 10 SDK - cmake and VSCode will recognize the installed SDK and recommend the compiler kits.

[Link to Windows 10 SDK](https://developer.microsoft.com/en-US/windows/downloads/windows-10-sdk/)

**Comment by palvarezlopez** [comment]
@behrisch I reproduced the same error in my VM. The problem is that symbol SIGUSR1 and SIGUSR2 aren't supported (see sumo_main, line 63)

**Comment by angelobanse** [comment]
> 
> 
> @behrisch I reproduced the same error in my VM. The problem is that symbol SIGUSR1 and SIGUSR2 aren't supported (see sumo_main, line 63)

https://github.com/eclipse/sumo/blob/cbaa8c16c6062dfd22ed553ea36f5f2dec333e4b/src/sumo_main.cpp#L63

**Comment by behrisch** [comment]
According to this table https://web.archive.org/web/20140625123925/http://nadeausoftware.com/articles/2012/01/c_c_tip_how_use_compiler_predefined_macros_detect_operating_system
we should check for _WIN32 instead of _MSC_VER. I will change this and could you please check whether it helps?

**Comment by behrisch** [comment]
Please reopen if problems persist.

**Comment by palvarezlopez** [comment]
@behrisch currently SUMO cannot be compiled using mingw32, but it's part of another ticket
