### ISSUE TITLE
How can I make high flows in a large-scale network?

### ISSUE THREAD

**Issue by Shiyunyang-seu** [eclipse/sumo#7097]
Hi, I want to use the randomTrips.py to create the trips in a very large scale, but the result also contains some invalid route. I want to know how can I avoid the invalid route(Whether it can only be deleted manually), or is there any other way to add a large number of vehicles to my network (except define Flow  in rou.xml and also give the ODs manually. This method has great limitations in the road network).

**Comment by namdre** [comment]
Are you using randomTrips.py option **--validate** ? 
If yes, what is an invalid route?

**Comment by namdre** [comment]
randomTrips.py option **--validate** ensures that only valid trips are written.
