### ISSUE TITLE
emissionClass Energy/zero does not consume electricity

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#7098]
it gets interpreted as HBEFA2/zero which burns no fuel but does not consume any electricity either.

**Comment by behrisch** [comment]
I thought that is the meaning of zero ;-). Seriously, I think every emission model should have the possibility to have a zero emissions class for propulsions we do not model (muscle power for instance). We could of course have one global zero class for that but it was developed under the impression that you decide once your model (HBEFAx or PHEM or ...) and then still have the freedom to choose the emission class (including zero) in the model. Maybe it is a documentation issue.

**Comment by namdre** [comment]
Point taken on the meaning of "zero".
It is still unexpected that 'Energy/zero' resolves to 'HBEFA2/zero' (i.e. in emission-output).
Also, we should probably find a better (alternative) name for the default electricity model because "Energy/unknown" is not intuitive.

**Comment by behrisch** [comment]
Since it is not well documented anyway we could also change it and make "zero" a "model" so independent of HBEFA etc. Internally it is implemented this way, that's why the output is wrong. Should we use "default" as an alias for "unknown"?

**Comment by namdre** [comment]
Yes. I like both ideas.

**Comment by behrisch** [comment]
Names are important: "Zero" or "zero" (or something completely different such as "NoEmissions")?

**Comment by namdre** [comment]
As all the other models start with an uppercase letter, I opt for "Zero".
Also, it would be nice if it could be used as "Zero" as an alternative to "Zero/unknown" or "Zero/default".
