### ISSUE TITLE
how to use routes generated by flowrouter

### ISSUE THREAD

**Issue by Pol52** [eclipse/sumo#7104]
Hello,
What is the correct approach to use the routes.xml generated by flowrouter?
When I set it as route file in the sumocfg and launch the simulation, it tells me that a certain route is not known for a flow.
Do i need to convert it into a routes.rou.xml file?

**Comment by namdre** [comment]
The same rules as for DFROUTER apply. See https://sumo.dlr.de/docs/Demand/Routes_from_Observation_Points.html#how_to_include_the_files
