### ISSUE TITLE
Using TraCI for changing lateral alignment

### ISSUE THREAD

**Issue by MohamadReza-Haghani** [eclipse/sumo#7106]
Hi,

I am writing a code to change the lateral alignment of vehicles. There is nested if conditions in this code. In the second level, the "if 20 < sim_time < 60" is performed, and the results of it is observed in the simulation. However, it does not perform the statement after "elif sim_time > 60." Any help will be appreciated. Please find attached the simulation files.

Regards,
Reza.

![Capture](https://user-images.githubusercontent.com/64617116/83678184-51e25700-a5ab-11ea-8d83-90c2abc5c08c.PNG)

**Comment by namdre** [comment]
please note the the sumo issue tracker is not the place for general programming questions.
https://sumo.dlr.de/docs/FAQ.html#my_traci-program_is_not_working_as_intended_can_you_help_me_debug_it
