### ISSUE TITLE
Invalid number of selected elements

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#7113]
After a certain numbers of selection/deselection, number of elements selected is invalid.
![L_1C49 tmp](https://user-images.githubusercontent.com/8238561/83760907-e3b69680-a675-11ea-8a36-1d67c10aafae.PNG)

**Comment by namdre** [comment]
Yes. I noticed a while a ago and kept forgetting to open up a ticket. I think it can easily be triggered with undo/redo of mass-select/deselect operations.
