### ISSUE TITLE
setLateralAlignment does not work properly in a if condition in TraCI

### ISSUE THREAD

**Issue by MohamadReza-Haghani** [eclipse/sumo#7114]
Hi,

I utilized the command of "setLateralAlignment" in TraCI. There is a nested if in my code. Based on the code, for every vehicle at every simulation step, it should check the vehicle type. If the vehicle type is "1," it should check the simulation second. For the vehicles with type "1," if the simulation second is between 20 and 40, it should change the lateral alignment according to the code. Every vehicle did so according to the results. However based on the results, in the next if condition that says when the simulation second is more than 40, the lateral alignment is not changed for all of the vehicles but only for vehicles that enter the network after second 40. I would appreciate if any body knows what I should change in order to make the second condition affect all of the vehicles in the network.

Thanks,
Reza.

![Capture](https://user-images.githubusercontent.com/64617116/83788707-a1845980-a663-11ea-9621-fa9a3deaec0d.PNG)

**Comment by namdre** [comment]
did you check for which vehicles the second 'if' is executed (i.e. by printing the vehicle id?)
If so, you can check whether the alignment was successfully set by calling  getLateralAlignment on the vehicle after the call to setLateralAlignment.

**Comment by MohamadReza-Haghani** [comment]
Hi Namdre,

Thanks. I added a sentence to the code to print the lateral alignment. It was observed that the first 7 vehicles entered the network before second 40. For these 7 vehicles, lateral alignment was first "center," then it was changed to "right" and remained until the end. For the vehicles that entered the network after second 40 (8th, 9th, 10th etc.), the lateral alignment was "center" from the beginning to end. I think the second "if" only affects the vehicles after number 7 (8th, 9th, 10th etc.).

**Comment by namdre** [comment]
since the default alignment is "center", you would not see any effect when setting it to "center" again.

**Comment by MohamadReza-Haghani** [comment]
I changed it to the "left" and saw that the vehicles after number 7 (8th, 9th, 10th etc.) enters the network in the left side of the lane.  But it still did not had any effect on the first 7 vehicles.

**Comment by namdre** [comment]
Did you add a print statement to check whether the relevant code was active for the first group of vehicles?
```if sim_time > 40:
        print("setLateralAligntment=... for vehicle", veh_id)
         traci.vehicle.setLateralAlignment(...)
```

**Comment by MohamadReza-Haghani** [comment]
I added the print command, and it printed 8, 9, 10 etc., meaning that the second "if" does not affect the first group of vehicles.

**Comment by namdre** [comment]
To me, this does not look like an issue with TraCI since setLateralAlignment is not called for the first group. Thus, the title of this issue is incorrect and you are dealing with a problem in your own python code.
Are the vehicles of the first group even  in the simulation after time 40? 
Are they part of traci.vehicle.getIDList()?
If so, did you try printing out their type?
Did you attach the python debugger to check why the second `if` branch is not being entered?

**Comment by MohamadReza-Haghani** [comment]
Thank you a lot for your attention to my question. I really appreciate that. I see the first group continue their way in GUI after second 40 until they arrive at the end of network. And since they are affected by the first "if," I think they are part of traci.vehicle.getIDList(). I also printed their type and found out that they are of type "1." How can I attach the python debugger?

**Comment by namdre** [comment]
python -m pdb runner.py
or within the source: `import pdb; pdb.set_trace()`

**Comment by MohamadReza-Haghani** [comment]
Thank you very much for your help.

**Comment by behrisch** [comment]
If this is not resolved please reopen.
