### ISSUE TITLE
retrieve additional stop attributes

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#7117]
optional attributes that are missing from TraCINextStopData
- startPos
- arrival
- speed
- awaitedPersons, awaitedContainers
- split, join
- tripId, line (attributes that are updated on the vehicle when the stop is reached)
- index
- used defined stop params (this is not yet supported by NLHandler but SUMOVehicleParameter::Stop is already Parameterized in anticipation of future extension)

We could either add all these things to TraCINextStopData or if this is deemed excessive, devise an additional way to retrieve them. @behrisch what do you think?

**Comment by behrisch** [comment]
I would add them to the existing TraCINextStopData object.
