### ISSUE TITLE
reconsider default permissions on roads for pedestrians

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#7119]
By default, pedestrians are allowed on all road lanes for all road types (except motorway).
For pedestrian simulation, this makes it necessary to disallow pedestrians on those lanes (which happens automatically when adding sidewalks.

User who forget this step can easily become confused when trying to add pedestrian crossings because these require a configuration of pedestrian lanes separated by non-pedestrian lanes (which must be crossed).

In some (OSM) networks, no extra sidewalks must be added because the OSM community has mapped them with separate edges (highway.path). This means the user cannot use the standard osmNetconvertPedestrians.typ.xml typemap but must use osmNetconvertPedestriansNES.typ.xml instead. (see #7041). This isn't very obvious.

A possible solution would be to always forbid pedestrians on road lanes (at least for the "larger" road classes). The only downside would be that simulation with non-interacting pedestrians (without sidewalks and crossings) would require a special typemap which re-adds pedestrian permissions. Since this use case is probably used less often for pedestrian simulation, the change may be worthwhile.

**Comment by behrisch** [comment]
If we forbid pedestrians on the street, I think we should add sidewalks by default, so that the user always has a pedestrian enabled network unless they decide explicitly otherwise. Maybe we could ease the switch by adding some netedit buttons which try to convert a car-centric network into a pedestrian enabled one and back? I think also the modelling of public transport (access) currently requires a lane which allows pedestrians so even if you do not model walking too detailed you still need it for public transport (unless we change that too).

**Comment by namdre** [comment]
Adding sidewalks by default is not a good idea for reasons outlined in #7041.
I'm not sure whether we really need to have a pedestrian enabled network by default.
With the current defaults (pedestrians allowed on all lanes, default pedestrian model 'striping') a realistic simulation is not possible anyway.

- if the user wants to have a detailed pedestrian simulation, several network building options must be set
- if the user wants an abstract pedestrian simulation, at least the sumo model option must be set

Having a car-only network by default and having to rebuild the network for pedestrians (with sidewalks or abstract permissions) *might* be more useful.

**Comment by behrisch** [comment]
I agree that the current default is bad for pedestrian as wella s non pedestrian simuations. I also agree that adding sidewalks everywhere is abad solution (in the light of #7041) but I think there is a solution mentioned in the same ticket. To me the situation is similar to the introduction of the junction internal lanes. In the beginning it was optional and we thought nobody really needs this level of detail but finally it was enabled by default and is only disabled rarely although it makes the network considerably larger and the simulation slower. The same may be true here and I would love to see sumo move more to a person centric instad of a vehicle centric view. But I may be ahead of time ;-)

**Comment by namdre** [comment]
The solution in #7041 involves an informed user choice in the webWizard UI. We still need to figure out a good default. (automation might be possible with a topological analysis of the OSM file but this isn't easy and may still be ambiguous). 

In other words: we still need a good default. I don't think we're at a level were
1) most sumo users care about person simulation
2) we can decided automatically whether we need to add sidewalks or not.

I'm also not sure whether changing the default to 'forbid pedestrians on roads" would actually improve things for the user so I'm closing this for now.
