### ISSUE TITLE
How to make one vehicle in one scene not obey the signal light rules, while other vehicles follow the signal light rules?

### ISSUE THREAD

**Issue by Mzy526** [eclipse/sumo#7122]
In an intersection scenario, I want one of the vehicles not to obey the traffic rules of the traffic lights, while other vehicles obey the traffic rules of the traffic lights. How can I set up the corresponding files?

**Comment by namdre** [comment]
Give one vehicle a different vehicle type and set junction model parameters for that vType to ignore red lights by setting jmDriveAfterRedTime="1000" :https://sumo.dlr.de/docs/Definition_of_Vehicles,_Vehicle_Types,_and_Routes.html#junction_model_parameters

**Comment by Mzy526** [comment]
thanks very much!!!

**Comment by Mzy526** [comment]
my sumo version is 0.30.0,this set can't make work!!!! cry!

**Comment by Mzy526** [comment]
For some reasons,  I must still using sumo version 0.30.0,maybe have another way to handle up problem?

**Comment by namdre** [comment]
You could combine two TraCI calls:
- call setSpeed(vehID, someValue) to make the vehicle drive
- call setSpeedMode(vehID, 0) to make the vehicle ignore red lights and other safety constraints when applying the speed you set.
