### ISSUE TITLE
I think in VEINS project, called traci interface to implement the control of traffic lights, but I don't know how to write a call statement traci interface.

### ISSUE THREAD

**Issue by Mzy526** [eclipse/sumo#7123]
Below I call the traci interface code for the vehicle so that the vehicle can use the tracI commands, but control the traffic light signals and I don't know how to start.
cModule* vehicle = getParentModule();
        Veins::TraCIMobility* traci = dynamic_cast<Veins::TraCIMobility*>(vehicle->getSubmodule("veinsmobility", 0));
        Veins::TraCICommandInterface::Vehicle*traciVehicle = traci->getVehicleCommandInterface();``

**Comment by namdre** [comment]
Sorry, The Sumo team cannot answer Veins-related questions. Try a Veins tutorial or ask on Stackoverflow.
