### ISSUE TITLE
I wonder if this code is written in an older version of SUMO ?(for example, older than 0.30.0) Or is it another way of writing it?

### ISSUE THREAD

**Issue by Mzy526** [eclipse/sumo#7125]
`<vType id="ambulance" jmDriveAfterRedTime="300" jmDriveAfterRedSpeed="5.56"/>`

**Comment by namdre** [comment]
The vType definition is correct for 0.30.0 and newer versions.

**Comment by Mzy526** [comment]
jmDriveAfterRedTime="300" jmDriveAfterRedSpeed="5.56"，for this code，I see the SUMO's official website said that the code can not come into force in 0.30.0 or earlier versions of work, I mean that if in earlier versions, it ignored the traffic lights of writing is the other way?

**Comment by Mzy526** [comment]
https://sumo.dlr.de/docs/Definition_of_Vehicles,_Vehicle_Types,_and_Routes.html#junction_model_parameters

**Comment by namdre** [comment]
I removed the incorrect note. jmDriveAfterrRedTime was first available in 0.30.0 so it should work for you.

**Comment by Mzy526** [comment]
<vType id="vtype2" accel="2.6" decel="2.5" sigma="0.5" length="5.0" width="3" minGap="6.0" maxSpeed="35.2"  speedFactor="10" maxdecel="4.5" deapartspeed="max" color="red"  jmDriveAfterRedTime="1000"  />  this is my rou.xml file,This is my vehicle type parameter Settings, I added jmDriveAfterRedTime="1000" this parameter, but my vehicle arrived at the intersection or follow the traffic light rules, when the red light on it is still waiting for the red light, it is very obey the rules, it did not ignore the signal

**Comment by Mzy526** [comment]
`<vType id="vtype2" accel="2.6" decel="2.5" sigma="0.5" length="5.0" width="3" minGap="6.0" maxSpeed="35.2"  speedFactor="10" maxdecel="4.5" deapartspeed="max" color="red"  jmDriveAfterRedTime="1000"  />`

**Comment by Mzy526** [comment]
my sumo version is 0.30.0

**Comment by Mzy526** [comment]
`<tlLogic id="gneJ1" type="static" programID="0" offset="0">
        <phase duration="50" state="rrrrGGGGrrrrGGGG"/>
        <phase duration="20" state="rrrryyyyrrrryyyy"/>
        <phase duration="25" state="GGGGrrrrGGGGrrrr"/>
        <phase duration="20" state="yyyyrrrryyyyrrrr"/>
    </tlLogic>
    <tlLogic id="gneJ1" type="static" programID="1" offset="0">
        <phase duration="50" state="rrrrrrrrrrrrrrrr"/>
    </tlLogic>` this  is my trafficlight setting

**Comment by namdre** [comment]
please attach all files rather than quoting them in a comment.

**Comment by Mzy526** [comment]
[scenario.zip](https://github.com/eclipse/sumo/files/4744806/scenario.zip)

**Comment by Mzy526** [comment]
this is my sumo file!

**Comment by Mzy526** [comment]
Please take a look at the document to see what the problem is. thanks

**Comment by Domsall** [comment]
Your vtype2-vehicle seems to be stuck behind other vehicles. When you remove flow2, the vehicle should drive through the red traffic light.

**Comment by Mzy526** [comment]
When I removed flow2, my red car was still waiting for the red light instead of going straight through it. The removal seemed to have no effect and the problem was still unresolved.

**Comment by Mzy526** [comment]
![image](https://user-images.githubusercontent.com/63463594/84039763-52785480-a9d4-11ea-9de1-9597b9550946.png)

**Comment by Mzy526** [comment]
I done as you say,but sir,it still wait the red light,the remove flow2 change still can't handle the problem. this is the file after remove the flow2.

**Comment by Mzy526** [comment]
[scenario-changed.zip](https://github.com/eclipse/sumo/files/4749550/scenario-changed.zip)

**Comment by namdre** [comment]
It turns out my earlier comment about availability of the parameters was in error. In fact, the parameter jmDriveAfterRedTime is only available since 0.31.0. Sorry.
