### ISSUE TITLE
repeating public transit routes

### ISSUE THREAD

**Issue by cweinhaupl** [eclipse/sumo#7127]
@namdre 

For clarification regarding repeating PT.
I am wanting to have the same type vehicle repeat its route.

I tried repeating edges and stops in router and flow.
I think I misunderstood your comments regarding this question:
https://github.com/eclipse/sumo/issues/6550

```
    <flow id="f1" color="1,1,0"  begin="0" end= "3600" period="30" type="12passenger">
        <route edges="north gneE0 city gneE1 north gneE0 city gneE1 north gneE0 city gneE1 north gneE0 city gneE1"/>
        <stop busStop="busStop_north_0_1" duration="10"/>
        <stop busStop="busStop_city_0_0" duration="10"/>
        <stop busStop="busStop_north_0_1" duration="10"/>
        <stop busStop="busStop_city_0_0" duration="10"/>
        <stop busStop="busStop_north_0_1" duration="10"/>
        <stop busStop="busStop_city_0_0" duration="10"/>
        <stop busStop="busStop_north_0_1" duration="10"/>
        <stop busStop="busStop_city_0_0" duration="10"/>
    </flow>
```

```
    <route id="r_north_to_city" edges="north gneE0 city gneE1 north gneE0 city gneE1 north gneE0 city gneE1 north gneE0 city gneE1">
        <stop busStop="busStop_north_0_1" duration="10"/>
        <stop busStop="busStop_city_0_0" duration="10"/>
        <stop busStop="busStop_north_0_1" duration="10"/>
        <stop busStop="busStop_city_0_0" duration="10"/>
        <stop busStop="busStop_north_0_1" duration="10"/>
        <stop busStop="busStop_city_0_0" duration="10"/>
    </route>
```

**Comment by namdre** [comment]
I'm not sure what your question is.
- if you want to keep the same vehicle circulation (vehicle id stays the same) then you can either
  - define a vehicle or trip with lots of repeating stops
  - define a route that loops back to the start once and uses attribute 'repeat'. then assign that route to a vehicle
- if you want to keep sending a new vehicle on the same route repeatedly you can use a flow. 

Of course, both things can be combined if you want multiple vehicles running the same repeating loop.

**Comment by pearlahajjar** [comment]
hello @namdre,

I am still facing the same problem. 

I have a circle like route with stops along the route. In the first run of the buses, they stop at assigned stops, but in the following runs, the buses stop at every stop and passengers do not board. 

The additional file: 
 <additional>
    <busStop id="busStop_0" lane="2_0" startPos="4.58" endPos="14.58"/>
    <busStop id="busStop_2" lane="6_0" startPos="5.52" endPos="15.52"/>
    <busStop id="busStop_1" lane="9_0" startPos="7.49" endPos="17.49"/>
    <busStop id="busStop_3" lane="11_0" startPos="6.74" endPos="16.74"/>

    <route id="reroute1" edges="12 1 2 3">
	<stop busStop="busStop_0" duration="10"/>
    </route>

    <route id="reroute2" edges="3 4 5 6 7">
	<stop busStop="busStop_2" duration="10"/>
    </route>

    <route id="reroute3" edges="7 8 9 10">
	<stop busStop="busStop_1" duration="10"/>
    </route>

    <route id="reroute4" edges="10 11 12">
	<stop busStop="busStop_3" duration="10"/>
    </route>

   <rerouter id="rerouter_0" edges="12" probablity="1">
        <interval begin="0.00" end="3600.00">
            <routeProbReroute id="reroute1"/>
        </interval>
    </rerouter>
    <rerouter id="rerouter_1" edges="3" probablity="1">
        <interval begin="0.00" end="3600.00">
            <routeProbReroute id="reroute2"/>
        </interval>
    </rerouter>

     <rerouter id="rerouter_2" edges="7" probablity="1">
        <interval begin="0.00" end="3600.00">
            <routeProbReroute id="reroute3"/>
        </interval>
    </rerouter>

    <rerouter id="rerouter_3" edges="10" probablity="1">
        <interval begin="0.00" end="3600.00">
            <routeProbReroute id="reroute4"/>
        </interval>
    </rerouter>

</additional>

and the route xml file: 
<routes>
    <route edges="1 2 3 4 5 6 7 8 9 10 11 12" color="yellow" id="route_0"/>
    <vType id="Bus" length="14.00" maxSpeed="25.00" guiShape="bus" color="red" accel="1.1176" decel="0.89"/>
    <vType id="Car" length="5.00" maxSpeed="30.00" color="green" accel="3" decel="1.3" sigma="0.5"/>

    

    <vehicle id="Bus_1" type="Bus" depart="0.00" route="route_0" color="red">
        <stop busStop="busStop_0" duration="10.00"/>
        <stop busStop="busStop_2" duration="10.00"/>
    </vehicle>

    <person id="person0" depart="0.00">
        <walk from="1" busStop="busStop_0" arrivalPos="55.00"/>
        <ride busStop="busStop_1" lines="Bus_2"/>
        <walk to="10" arrivalPos="30.00"/>
    </person>

    <personFlow id="personf" begin="0" probability="0.1" departPos="10">
       <walk from="1" busStop="busStop_0" arrivalPos="55.00"/>
       <ride busStop="busStop_1" lines="Bus_2"/>
       <walk from="9" to="11" arrivalPos="15"/>
   </personFlow>

    <vehicle id="Bus_2" type="Bus" depart="0.00" route="route_0" color="yellow">
        <stop busStop="busStop_0" duration="10.00"/>
        <stop busStop="busStop_1" duration="10.00"/>
    </vehicle>

    <person id="person1" depart="5.00" >
	<walk from="1" busStop="busStop_0" departPos="21" arrivalPos="55"/>
	<ride busStop="busStop_3" lines="ANY" />
	<walk to="10" arrivalPos="30" />
     </person>

     <vehicle id="Bus_3" type="Bus" depart="10.00" route="route_0" color="blue">
        <stop busStop="busStop_2" duration="10.00"/>
        <stop busStop="busStop_1" duration="10.00"/>
     </vehicle>

     <vehicle id="Bus_4" type="Bus" depart="15.00" route="route_0" color="green">
        <stop busStop="busStop_0" duration="10.00"/>
        <stop busStop="busStop_2" duration="10.00"/>
        <stop busStop="busStop_1" duration="10.00"/>
        <stop busStop="busStop_3" duration="10.00"/>
     </vehicle>
</routes>

Thank you for your help.

**Comment by namdre** [comment]
Rerouters are not recommended for modelling looped public transport routes.
- if you have busses that service different stops you would need to define a different rerouter for each bus and make them specific to a particular bus by using vTypes filtering (difficult and error prone)
- rerouters cannot handle public transport schedules ('until'-times)
-
Instead, define a route for each bus that includes the stops and use the 'repeat' attribute for looping.

**Comment by pearlahajjar** [comment]
Can I still change the route stops using traci throughout the simulation in this way?

**Comment by namdre** [comment]
Yes. When using 'repeat',  all stops the vehicle will ever take can be retrieved with `traci.vehicle.getStops`. They can be replaced or removed using `traci.vehicle.replaceStop`

**Comment by pearlahajjar** [comment]
Thank you so much for your help. It was very useful. I managed to let the buses stop at desired stops the whole simulation.

If I want to let a bus skip the next stop in the simulation dynamically, can it be done? I don't want to remove it from the road, just this bus do not stop on it now.

**Comment by namdre** [comment]
You can use replaceStop with an empty string for the edgeID argument to remove the stop at the specified index in the stop list.
