### ISSUE TITLE
SumoPy Not Working

### ISSUE THREAD

**Issue by lenri001** [eclipse/sumo#7132]
Hello all, 
I am new to SUMO, and tried using SumoPy. The problem is that the SUMOPy gui code is really outdated. It uses wx verson 2.8 and python 2. I could not get it to run even with legacy software. I want to know if this can be updated? 
Also, if anyone knows how to get it running currently, please let me know. 
[sumopy_userman_v01_contrib.pdf](https://github.com/eclipse/sumo/files/4748772/sumopy_userman_v01_contrib.pdf)

Thank you for the help.

**Comment by schwoz** [comment]
SumoPy is in continuous development, just githup has not been updated.
We'll soon do that, check again in a couple of days. 
Still, it does not work with the newest libraries and packages, but it is now compatible with wxWindows 3.x which you may find also on newer Linux distributions.
