### ISSUE TITLE
all lanes become bikelanes when adding a sidewalk to an edge in NETEDIT

### ISSUE THREAD

**Issue by HDSFaust** [eclipse/sumo#7135]
![before](https://user-images.githubusercontent.com/58727183/84152210-a3d02480-aa64-11ea-8650-7fe9fd9f60aa.png)
![after](https://user-images.githubusercontent.com/58727183/84152248-acc0f600-aa64-11ea-9880-8c098dca8e0b.png)

when right clicking on a lane to add a restrictive lane (sidewalk), the rest of the lanes become bikelanes

**Comment by namdre** [comment]
Thanks for reporting.
