### ISSUE TITLE
mismodelled capacity when using multiple queues

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#7143]
jam state is based on occupancy/capacity for the whole segment. If only some queues/lanes are used (i.e. because there is mostly straight going traffic that does not utilize the left-turn-lane) than the jam-treshold is not reached even though individual queues/lanes are filled to capacity.

This can cause large discrepancy in comparison to the micro simulation.

**Comment by behrisch** [comment]
Would the "simple" solution of a jam state per queue do the trick?

**Comment by namdre** [comment]
Yes. That would be my proposed fix.

**Comment by namdre** [comment]
I follow you reasoning. It might even simplify the code to replace multi-queue with lane-segments (#7137).
Besides slightly larger memory requirements from more MESegment instances I don't see why it should be slower (at least for the old behavior where only the last segment is split lane-wise).

**Comment by behrisch** [comment]
Test for **--meso-lane-queue** is missing

**Comment by behrisch** [comment]
queue specific capacities and block times are implemented, work continues in #7137
