### ISSUE TITLE
 How can define the proportion of different vehicle types in flow?

### ISSUE THREAD

**Issue by Shiyunyang-seu** [eclipse/sumo#7159]
Hi, when I use flow to define travel demand, can I define the proportion of different vehicle type (for example, 70% cars, 30% trucks...), and can the shape displayed as trucks in SUMO-GUI.
Thanks in advance!

**Comment by namdre** [comment]
For different types in the same flow, see https://sumo.dlr.de/docs/Definition_of_Vehicles,_Vehicle_Types,_and_Routes.html#vehicle_type_distributions

When you define a type with vClass="truck" you will automatically get appropriate parameters and shape. For details see https://sumo.dlr.de/docs/Definition_of_Vehicles,_Vehicle_Types,_and_Routes.html#abstract_vehicle_class
