### ISSUE TITLE
refactor python client to infer command length automatically

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#7160]
like the c++ client does it

This would reduce a lot of code and confusion.

**Comment by namdre** [comment]
also: get rid of most entries of _RETURN_VALUE_FUNC (only the special functions are needed). Instead, connection._checkResult can preserve the response type bit and let domain._getUniversal make use of it.

**Comment by behrisch** [comment]
There is still some code in traci.connection which would benefit from refactoring.
