### ISSUE TITLE
Libsumo : Memory Leak in getLeader

### ISSUE THREAD

**Issue by Thibaud-Ardoin** [eclipse/sumo#7169]
Hi, 

I'm using libsumo in a deep learning project. Therefore, I run a lot of simulations in a row and I noticed a memory leak that prevents me from training long enough...
I use the python framework and the leak doesn't appear for the same process with TraCI.
I have narrowed down the leak source to the `vehicle.getLeader` function.

I hope you have a way to fix it, or to bypass it,
Thanks in advance for the help !

Thibaud

**Comment by namdre** [comment]
if you are using version 1.6.0 please upgrade to the latest development  version where a related issue was fixed (#7012) and try again: https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_development_version

**Comment by Thibaud-Ardoin** [comment]
Thanks for the quick answer, I think this is resolving my problem !
Do you know when that fix will be merged to a proper release ?

**Comment by namdre** [comment]
1.7.0 is planned for September: https://github.com/eclipse/sumo/milestones

**Comment by roireshef** [comment]
@Thibaud-Ardoin - just curious - were you able to make it work with libsumo at scale? Are you using RLlib?
