### ISSUE TITLE
traci.close() failing

### ISSUE THREAD

**Issue by zevnicsca** [eclipse/sumo#7170]
When running `traci.close()` (or `traci.close(False)`) I get the following error

```Traceback (most recent call last):
  File "runner.py", line 223, in <module>
    traci.close()
  File "/usr/local/opt/sumo/share/sumo/tools/traci/main.py", line 215, in close
    del _connections[_currentLabel[0]]
KeyError: 'default'
```

Sumo version is 1.6.0 and Python version is 3.7.6

Thanks for any ideas!

**Comment by namdre** [comment]
traci.close should only be called once after a matching call to traci.start (or possibly traci.init).
Did you do this?

**Comment by zevnicsca** [comment]
Apologies I did not have this properly paired with the code I had for running the simulation. I'm new to SUMO and still getting used to traci. Thanks for the pointer!
