### ISSUE TITLE
traci utf8 support

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#7171]
Currently all strings in the python client are latin1 encoded. This is probably an API breaking change and should be discussed first.

**Comment by namdre** [comment]
Is  there any latin1 encoding/decoding going on at the server side?

**Comment by behrisch** [comment]
I don't think so.

**Comment by namdre** [comment]
So basically, when the server side loads utf8-encoded xml, the client tries to interpret this as latin1 and we might break this faulty interpretation? Can you describe other use cases that would be user-visible?

**Comment by behrisch** [comment]
The user sets an attribute (a vehicle id, poi type or something) via traci using latin1 characters. SUMO currently does not care and it probably looks also "correct" in output files if they are interpreted as latin1 encoded. This would fail when we change to utf8. We could invent a function to set a global default encoding to mitigate this.

**Comment by namdre** [comment]
Sound like a plan! I would change the default to UTF8 without to much worry.

**Comment by behrisch** [comment]
We probably cannot support this for libsumo though.

**Comment by behrisch** [comment]
With some distance my own example looks a little contrived now and I would just change to utf8 because that's what SUMO's XML (and thus sumolib and libsumo) do anyway.
