### ISSUE TITLE
emergency vehicle on another edge is ignored

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#7172]
in the current implementation, vehicles only react to an emergency vehicle on the same edge regardless of distance. 

It would probably be better (and more efficient) to apply the reaction to all vehicles within the defined radius (i.e. 25m)

**Comment by WeroNikaNa** [comment]
I think that nice to have would be to have both of those functionalities. (same edge and radius)
I like the new option that I am able to change the reaction distance from 25m to a longer one. But it wouldn't make sense to have a radius reaction 150m. (bc it would mess up with cars on some other lines for nothing)
So for example option that the user can change the reaction to an emergency vehicle on the same edge to 150m and keep the radius reaction 25m or even less would be perfect.

**Comment by namdre** [comment]
I see your point about keeping the other side of the road unaffected so maybe the whole radius is not a general solution to this issue (rather an additional feature that could be added).

The current issue about the distance being cut short by the end of the edge must still be fixed.
An alternative solution would be to scan the forward edges along the route of the vehicle until the configured distance is reached. This would ensure emergency lane formation within the given distance.

**Comment by lbieker** [comment]
was closed in last commit
