### ISSUE TITLE
Problems in expressway simulation

### ISSUE THREAD

**Issue by Shiyunyang-seu** [eclipse/sumo#7177]
Hello, I encountered the following problems during the simulation of expressway:
1. Can the shape or linearity of the road be more accurate and real at the ramp entrance
2. Can the toll station be simulated (the vehicle has a stop and start process here)
3. How to simulate when part of the road section is under construction or cannot pass (similar to simulated traffic accident)
4. Can I import CAD or PNG in Netedit so that I can draw roads.
Thanks in advance.

**Comment by namdre** [comment]
1) see https://sumo.dlr.de/docs/NETEDIT.html#specifying_the_complete_geometry_of_an_edge_including_endpoints
2) https://sumo.dlr.de/docs/Definition_of_Vehicles,_Vehicle_Types,_and_Routes.html#stops
3) close a lane permanently in Netedit or use https://sumo.dlr.de/docs/Simulation/Rerouter.html#closing_a_lane
4) https://sumo.dlr.de/docs/SUMO-GUI.html#showing_background_images (also works in Netedit)

**Comment by Shiyunyang-seu** [comment]
> 1. see https://sumo.dlr.de/docs/NETEDIT.html#specifying_the_complete_geometry_of_an_edge_including_endpoints
> 2. https://sumo.dlr.de/docs/Definition_of_Vehicles,_Vehicle_Types,_and_Routes.html#stops
> 3. close a lane permanently in Netedit or use https://sumo.dlr.de/docs/Simulation/Rerouter.html#closing_a_lane
> 4. https://sumo.dlr.de/docs/SUMO-GUI.html#showing_background_images (also works in Netedit)

Thanks for your replying. When I tried to load png in SUMO (define a XML file like <decal file="rongcheng.jpg" centerX="550.00" centerY="1530.00" width="64.00" height="64.00" rotation="0.00"/>), also I tried to add path in picture file column in view  setting, but the image both can not be loaded.
My version is 1.5.1. Thanks in advance.
![gui](https://user-images.githubusercontent.com/55737075/84846930-7e55a300-b082-11ea-9f60-63e2e028a385.png)

**Comment by namdre** [comment]
When defining the background image it's easy to get a leading or trailing space in the input field. It may be easier to define the background file with xml input in the gui-settings file

**Comment by Shiyunyang-seu** [comment]
Thanks for your replying. Through GUI setting, I successfully imported the PNG base map, but there is still a problem: 
I have already imported a net.xml, and the PNG is the future planning map, so there is only a small part of it matching with net.xml, how can I find a benchmark to match them quickly, or can I only try to change centerx, centery and length and width manually.

**Comment by namdre** [comment]
There is currently no method to match them automatically. You could try to select the whole network and move that around with the mouse rather than moving the image via centerx, centery. You still have to get the scaling right manually (width, length).

**Comment by Shiyunyang-seu** [comment]
Hi,if there is a section of road closed due to construction, can I get the queue length of bottleneck section?

**Comment by namdre** [comment]
- https://sumo.dlr.de/docs/Simulation/Output/Lanearea_Detectors_(E2).html
- https://sumo.dlr.de/docs/Simulation/Output/QueueOutput.html

**Comment by Shiyunyang-seu** [comment]
Thanks for your replying. Furthermore, If I set the speed limit on the highway, can I make different proportions (for example, 90%, 70%...) of vehicles to follow the rules and obey the speed limit.

**Comment by namdre** [comment]
see https://sumo.dlr.de/docs/Definition_of_Vehicles,_Vehicle_Types,_and_Routes.html#speed_distributions
