### ISSUE TITLE
Cannot install lib sumo with pip

### ISSUE THREAD

**Issue by zevnicsca** [eclipse/sumo#7178]
I saw on pypi that there seems to be an option to install libsumo with pip which I thought would be convenient (https://pypi.org/project/libsumo/). However when I run `pip install libsumo` I get the following error 

```
ERROR: Could not find a version that satisfies the requirement libsumo (from versions: none)
ERROR: No matching distribution found for libsumo
```

I'm using pip 20.1.1 with python 3.7

**Comment by RobertHilbrich** [comment]
Did you install python 3.7 32bit or 64bit?

Am 16.06.2020 um 18:06 schrieb zevnicsca <notifications@github.com<mailto:notifications@github.com>>:



I saw on pypi that there seems to be an option to install libsumo with pip which I thought would be convenient (https://pypi.org/project/libsumo/). However when I run pip install libsumo I get the following error

ERROR: No matching distribution found for libsumo


I'm using pip 20.1.1 with python 3.7

**Comment by angelobanse** [comment]
Currently, the installation of libsumo via pip only works in Windows.
@zevnicsca are you using Windows?

**Comment by zevnicsca** [comment]
I'm currently on 64 bit Python and Mac. So I guess the Mac versus windows is the problem then
