### ISSUE TITLE
More output

### ISSUE THREAD

**Issue by pengyuan-zhou** [eclipse/sumo#7179]
Hi,

Is it possible to enable more output w/o GUI?
For instance, I'm looking at the output such as queueing_length and queueing_time.
Could it be printed after running or presented in the GUI as one of the network:parameter?
If there's no direct option to enable, a hint on which file I could look into is also appreciated.

Thanks.
BR

**Comment by namdre** [comment]
queuing-related info can be written via
- https://sumo.dlr.de/docs/Simulation/Output/Lanearea_Detectors_(E2).html
- https://sumo.dlr.de/docs/Simulation/Output/QueueOutput.html

**Comment by pengyuan-zhou** [comment]
> queuing-related info can be written via
> 
>     * https://sumo.dlr.de/docs/Simulation/Output/Lanearea_Detectors_(E2).html
> 
>     * https://sumo.dlr.de/docs/Simulation/Output/QueueOutput.html

Ya thanks, I'm aware of that, but was looking for sth. like directly output the average value of such metrics, like how sumo prints average speed after each round.
But anyway, I can keep using the xml files for the result extraction, just wondered if there's an easier way.
BR

**Comment by namdre** [comment]
You can call 
`tools/output/attributeStats.py --element lane --attribute queueing_length queueoutput.xml`

**Comment by pengyuan-zhou** [comment]
> You can call
> `tools/output/attributeStats.py --element lane --attribute queueing_length queueoutput.xml`

Neat! Thanks, this is convenient, seems the current version has lots of improvements. 
I should upgrade my 0.26.0 version lol
