### ISSUE TITLE
Netedit messes loaded stop declarations of routes

### ISSUE THREAD

**Issue by toiviot** [eclipse/sumo#7191]
Hello, I'm using NetEdit 1.6. If I load routes for the demand mode that have stop declarations, they seem to pile up so that the second loaded route has the stops of first and second route ,... , and last loaded route contains all the stops from all loaded routes in order. So if I save the loaded demand immediately the  stops in the routes are messed up.

**Comment by palvarezlopez** [comment]
@toiviot Thanks! I check it.

**Comment by palvarezlopez** [comment]
Problems with person stops will be fixed in ticket #6903
