### ISSUE TITLE
What is the difference between "traci.vehicle.getElectricityConsumption" and "energyConsumed in battery-output"

### ISSUE THREAD

**Issue by khibuya** [eclipse/sumo#7196]
I want to calcualte the battey SoC of EV, and I found there are difference between the value of "traci.vehicle.getElectricityConsumption" and "energyConsumed (in battery-output)" . 
How can I use each one properly?
Thank you.

**Comment by khibuya** [comment]
The definition is as bellow. I has not modified timestep, so timestep remains default(1 second). So ①and② has same unit (Wh). 
---------
①traci.vehicle.getElectricityConsumption
⇒Vehicle's electricity consumption in Wh/s during this time step, to get the value for one step multiply with the step length.
②energyConsumed (in battery-output file)
⇒energy consumption in this timestep in Wh.
---------


Next, I read following publication 
「Implementation of an Energy Moedel and Charging Infrastructure in SUMO, 2014」
(https://elib.dlr.de/93885/1/Proceeding_SUMO2013_15-17May%202013_Berlin-Adlershof.pdf)

The energy is calculated as follows③.
・E_vehicle[k] = E_kinect[k] + E_potential[k] + E_rotation,internal[k]
・ΔE_gain[k] = E_vehicle[k+1] - E_vehicle[k] - ΔE_loss[k]
・E_Battery[K+1] = E_Battery[k] + ΔE_gain[k]・η_recuperation
　(k:：timestep、 E：energy)

Now, which term in formula③ does the ①traci.vehicle.getElectricityConsumption and ②energyConsumed (in battery-output file) correspond to ?

Is it correct there are following correspondence?
①energyConsumed (in battery-output file) is E_vehicle[k+1] - E_vehicle[k]
②traci.vehicle.getElectricityConsumption is E_battery[k+1] - E_battery[k]

**Comment by namdre** [comment]
Both outputs ("traci.vehicle.getElectricityConsumption" and "energyConsumed (in battery-output)" should correspond to
E_battery[k+1] - E_battery[k]
(losses and recuperation are included, charged energy from charging infrastructure is not included)

However, the value of traci.vehicle.getElectricityConsumption appears to always use the default parameters for an electric vehicle whereas energyConsumed  makes use of all the parameters listed in https://sumo.dlr.de/docs/Models/Electric.html#defining_electric_vehicles

**Comment by khibuya** [comment]
Thank you for replying, then I will use "energyConsumed (in battery-output)" to check the battery SoC.
