### ISSUE TITLE
decide on a naming convention for capitalization of applications

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#7198]
we need to distinguish between 
- `SUMO` (the whole software package with all tools)
- `SUMO` the application (sumo.exe)

Currently, we are using 'SUMO', 'Sumo' and `sumo` (and NETEDIT, Netedit, netedit etc) in a rather unprincipled way.

Right now, the documentation capitalizes all C++ application names
we may not want to emphasize the distinction between C++ applications and python tools.

Suggestion
- use SUMO for the whole package
- use lowercase for all applications (this reference the actual file names for these applications)
- to emphasize application names in documentation text we could always make them a link (presumably all-caps was used with this intent)

**Comment by behrisch** [comment]
I am very much in favor of less capital letters :-)
Your suggestion sounds perfect to me.

**Comment by angelobanse** [comment]
+1
* `SUMO` for the entire package / project
* lowercase for all applications (obviously including `sumo` and `sumo-gui`)

maybe even use _italics_ or **bold** when mentioning app names?

**Comment by palvarezlopez** [comment]
SUMO for the entire package / project and lowercase for all applications.

**Comment by behrisch** [comment]
looks fixed to me
