### ISSUE TITLE
Sublane model vehicles drive on lane marking regardless of lc parameters

### ISSUE THREAD

**Issue by patmalcolm91** [eclipse/sumo#7202]
Hello, I'm experiencing some strange behavior, in which vehicles using the sublane model drive down the lane marking of a two-lane roadway, regardless of the values of lcLaneDiscipline and other similar parameters. This occurs when the vehicle is on an edge with two vehicular lanes preceding an edge with one vehicular lane (see images). 

The lane change (or stay) reason in the vehicle parameters is always listed as "cooperative". However, changing lcCooperative, lcSublane, and lcLaneDiscipline seems to have no effect on this behavior. I have observed the same behavior in Sumo 1.6 as well as a build from today on both Linux and Windows. Is this a bug, or is there another parameter which affects lane discipline behavior? Any help would be greatly appreciated.

![image](https://user-images.githubusercontent.com/13092577/85130749-ccf76e80-b235-11ea-9924-e05816cddfcb.png)
![image](https://user-images.githubusercontent.com/13092577/85130363-1bf0d400-b235-11ea-993b-70dfac93732c.png)

**Comment by namdre** [comment]
could be a bug. Please attach scenario files for reproducing this behavior.

**Comment by patmalcolm91** [comment]
Thank you for the fast response, @namdre. Attached is a stripped-down version of the files which produce the behavior.
[sumo-sublane-bug.zip](https://github.com/eclipse/sumo/files/4805120/sumo-sublane-bug.zip)

**Comment by namdre** [comment]
Thanks for the concise example. Please follow #3681 for updates.

**Comment by patmalcolm91** [comment]
Rebuilding SUMO after the commits in the referenced issue does indeed seem to have resolved the issue for me. Thank you, @namdre!
