### ISSUE TITLE
Retrieval of complex types with libsumo in java (TraCIBestLanesData struct)

### ISSUE THREAD

**Issue by SvenMertin** [eclipse/sumo#7204]
Hey there!
Unfortunately, I am stuck to a specific traci/libsumo problem. I am using libsumo via java native interface. It's working fine except of the 'TraCIBestLanesData' structure. This structure is used when calling the traci/libsumo function getBestLanes(vehicleID).

This struct consists of 6 fields (laneID, length, occupation, bestLaneOffset, allowsContinuation and continuationLanes). Using jni, a pointer is returned that can be interpreted by the java class TraCIBestLanesData which is generated by swig. This class sucessfully reads the laneID located within the above mentioned structure. However, the remaining 5 fields can not be read sucessfully. 
I prepared a minimal example:

	package org.eclipse.sumo.libsumo;

	public class LibsumoTest {

	public static void main(String[] args) {

	try {
		
		System.loadLibrary("libpng16");
		System.loadLibrary("xerces-c_3_2");
		System.loadLibrary("libsumojni.dll");
		
		// Load any example, doesn't matter
		StringVector sv = new StringVector();
		sv.add("-c");
		sv.add("sumoroot\\tools\\sumolib\\scenario\\scenarios\\RealWorld\\RiLSA_example4\\run.sumo.cfg");
		Simulation.load(sv);

		// Run some simulation steps
		Simulation.step();				
		Simulation.step();				
		Simulation.step();				
		
		StringVector vehIds = new StringVector();
		vehIds = Vehicle.getIDList();

		if(vehIds.size() > 0){
			SWIGTYPE_p_std__vectorT_libsumo__TraCIBestLanesData_t bla = Vehicle.getBestLanes(vehIds.get(0));
			long cPtr = SWIGTYPE_p_std__vectorT_libsumo__TraCIBestLanesData_t.getCPtr(bla);
			TraCIBestLanesData tbl = new TraCIBestLanesData(cPtr, false);

			StringVector sv2 = tbl.getContinuationLanes();

			System.out.println("Vehicle: " + vehIds.get(0));
			System.out.println("Lane: "+ tbl.getLaneID());
			System.out.println("Length: "+ tbl.getLength());
			System.out.println("Occupation: "+ tbl.getOccupation());
			System.out.println("BestLaneOffset: "+ tbl.getBestLaneOffset());
			System.out.println("AllowsContinuation: "+ tbl.getAllowsContinuation());
			System.out.println("#ContinuationLanes: "+ sv2.size());
		}		
		
		Simulation.close();
	} catch (UnsatisfiedLinkError ex) {
		System.out.println(ex.getLocalizedMessage());
		System.out.println(ex.getMessage());
		ex.printStackTrace();
	}
	}

The output is:
> 
Loading configuration ... done.
Vehicle: em2mnLKW.0
Lane: em_0
Length: 3.28E-321
Occupation: 0.0
BestLaneOffset: 0
AllowsContinuation: false
#ContinuationLanes: 288230365259160606

Is it possible that there is some kind of derefencing error in the compiled libsumojni.dll in other words in the c++ world? The size of the StringVector ContinuationLanes is way to large. If I try to get an object from the vector jvm crashes due to memory violation.

As example, swig generates this c++-function for reading the length on my machine:

	SWIGEXPORT jdouble JNICALL Java_libsumoJNI_TraCIBestLanesData_1length_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
	  jdouble jresult = 0 ;
	  libsumo::TraCIBestLanesData *arg1 = (libsumo::TraCIBestLanesData *) 0 ;
	  double result;  
	  (void)jenv;
	  (void)jcls;
	  (void)jarg1_;
	  arg1 = *(libsumo::TraCIBestLanesData **)&jarg1; 
	  result = (double) ((arg1)->length);
	  jresult = (jdouble)result; 
	  return jresult;
	}

Do you have an idea on which side (java,jni / c++) the problem is located? I currently have no sumo development environment installed to try this on my own. I am using precomopiled realeases.

Thank you very much,
best regards
Sven

**Comment by behrisch** [comment]
The retrieval of complex data types using the java libsumo interface is untested so thanks for trying it out :-). Already the retrieval code looks weird, we probably need to invent a typemap here.

**Comment by SvenMertin** [comment]
Hey there!
I could be wrong, but maybe I found the error.  I downloaded the sumo source and debugged the libsumo/java connection and came across this:

When calling the native Java_org_eclipse_sumo_libsumo_libsumoJNI_Vehicle_1getBestLanes (located within libsumo_java_wrap.cxx which is generated by swig) to get the best lanes data, the function is returning a pointer address as follows:

`*(std::vector< libsumo::TraCIBestLanesData > **)&jresult = new std::vector< libsumo::TraCIBestLanesData >((const std::vector< libsumo::TraCIBestLanesData > &)result); `

So this is a pointer address to a **vector** of TraCIBestLanesData structs and is correctly transferred to java and back the native interface.

When afterwards calling e.g. the native Java_libsumoJNI_TraCIBestLanesData_1laneID_1get (as well libsumo_java_wrap.cxx), the pointer address to this vector of structs is forwarded. The implementation, however, won't derefence to the vector of structs but to a single TraCIBestLanesData struct: 

` arg1 = *(libsumo::TraCIBestLanesData **)&jarg1`

on which the field laneID is accessed (which is not correct in my opinion)

`result = (std::string *) & ((arg1)->laneID);`

I am not familiar with the swig syntax in libsumo.i, but I think this can be corrected there. I found numerous special cases for python in this file, but none for java.

**Comment by SvenMertin** [comment]
I am realizing that my code has a problem, too:

	SWIGTYPE_p_std__vectorT_libsumo__TraCIBestLanesData_t bla = Vehicle.getBestLanes(vehIds.get(i));	
	long cPtr = SWIGTYPE_p_std__vectorT_libsumo__TraCIBestLanesData_t.getCPtr(bla);	
	TraCIBestLanesData tbl = new TraCIBestLanesData(cPtr, false);

I am assuming here that the pointer adress (cPtr) is pointing to a TraCIBestLanesData-struct and can therefore be interpreted by the java class of the same name. But the pointer instead points to the vector head which itself contains a pointer to the (first) actual TraCIBestLanesData-struct. It's no wonder, that it can't be interpreted. So there has to be a proper data structure inbetween as you already suggested. Correct me, if I am wrong.

Best regards
Sven

**Comment by SvenMertin** [comment]
I just wrote a workaround and now I am able to get the information correctly. But it's not in the 'nice' way you probably would do it. I just added my own 'BestLanesDataHelper' to the libsumo folder.

BestLanesDataHelper.cpp:

	namespace libsumo {
		int BestLanesDataHelper::getSize(std::vector<TraCIBestLanesData> * bestLanesData) {
			return bestLanesData->size();
		}

		long BestLanesDataHelper::getPointerToItemAt(std::vector<TraCIBestLanesData> * bestLanesData, int index) {
			return (long) & (bestLanesData->at(index));
		}
	}

Now my java code looks like this and properly works:

	SWIGTYPE_p_std__vectorT_libsumo__TraCIBestLanesData_t bla = Vehicle.getBestLanes(vehIds.get(i));

	int size = BestLanesDataHelper.getSize(bla);

	for (int u = 0; u < size; u++) {
		long address = BestLanesDataHelper.getPointerToItemAt(bla, u);

		TraCIBestLanesData tbl = new TraCIBestLanesData(address, false);				
		StringVector sv2 = tbl.getContinuationLanes();

		System.out.println("Vehicle " + vehIds.get(i) + ": ");
		System.out.println("Lane: \t\t\t\t" + tbl.getLaneID());
		System.out.println("Length: \t\t\t" + tbl.getLength());
		System.out.println("Occupation: \t\t\t" + tbl.getOccupation());
		System.out.println("BestLaneOffset: \t\t" + tbl.getBestLaneOffset());
		System.out.println("AllowsContinuation: \t\t" + tbl.getAllowsContinuation());
		System.out.println("#ContinuationLanes: \t\t" + sv2.size());

		System.out.println("-----------------------------\n");
	}

The output looks promising (here for multiple vehicles):

	Vehicle 0: 
	Lane: 				gneE51_0
	Length: 			560.0699999999999
	Occupation: 			0.0
	BestLaneOffset: 		0
	AllowsContinuation: 		true
	#ContinuationLanes: 		7
	-----------------------------

	Vehicle 10: 
	Lane: 				-gneE47_0
	Length: 			50.19
	Occupation: 			0.0
	BestLaneOffset: 		0
	AllowsContinuation: 		true
	#ContinuationLanes: 		1
	-----------------------------

	Vehicle 11: 
	Lane: 				-gneE4_0
	Length: 			229.17
	Occupation: 			0.0
	BestLaneOffset: 		0
	AllowsContinuation: 		true
	#ContinuationLanes: 		1
	-----------------------------

	Vehicle 12: 
	Lane: 				gneE1_0
	Length: 			438.23
	Occupation: 			30.0
	BestLaneOffset: 		0
	AllowsContinuation: 		true
	#ContinuationLanes: 		9
	-----------------------------

	Vehicle 14: 
	Lane: 				gneE58_0
	Length: 			390.68
	Occupation: 			22.5
	BestLaneOffset: 		0
	AllowsContinuation: 		true
	#ContinuationLanes: 		8


and so on .....

Don't know whether or not this information ist helpful, but I think sharing the proceeding won't harm ;-)
Best regards!
Sven

**Comment by behrisch** [comment]
starting with sumo 1.10.0 we now have TraCIBestLanesVector encapsulating a list of TraCIBestLanesData. @SvenMertin Please give it another try and reopen if problems persist.
