### ISSUE TITLE
improve efficiency of bluelight device

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#7206]
currently, all vehicles in the simulation are checked for proximity with the emergency vehicle.
It would be faster to only check vehicles on the upcoming edges.

**Comment by Trashcleaner** [comment]
May I suggest that maybe checking vehicles in a circle around an emergency vehicle is a better idea.

I'm wondering that if we only check vehicles on the upcoming edges, then vehicles which are crossing the path of the EV (e.g. on the intersection) might not react appropriately. 

Regards.

**Comment by namdre** [comment]
No radius scan is needed:
- inform all vehicles on `myUpcomingEdges`
- reset all vehicles that were in `influencedVehicles` in the previous step but not in the current step (influencedVehicles from the previous step must be cached for this)

- a radius scan may latter be useful to inform cross traffic and avoid crashes when passing are red light (might be unrealistic though).

**Comment by lbieker** [comment]
was closed in the last commit
