### ISSUE TITLE
How to simulate a bottleneck？

### ISSUE THREAD

**Issue by Shiyunyang-seu** [eclipse/sumo#7217]
Hi, when I use flow to define the input traffic flow, how to make the vehicles not choose the same path to simulate the bottleneck queuing phenomenon.
![flow](https://user-images.githubusercontent.com/55737075/85291546-3644df00-b4cd-11ea-9a17-55388f6a1090.png)
![xml](https://user-images.githubusercontent.com/55737075/85291886-ad7a7300-b4cd-11ea-9148-bf2e43ca5baa.png)

**Comment by behrisch** [comment]
What exactly do you mean? As soon as the streets get more traffic, vehicles will start to use the other lanes too.

**Comment by Shiyunyang-seu** [comment]
Actually, no matter how much input traffic volumn I increase (2000 to 10000 per hour), vehicles only pass through the top Lane like the figure above. You can test it.
Thanks in advance.
[test.zip](https://github.com/eclipse/sumo/files/4813978/test.zip)

**Comment by namdre** [comment]
by default, vehicles are all inserted on the rightmost lane which limits insertion flow.
use `departLane="free" departSpeed="max"`
See https://sumo.dlr.de/docs/Simulation/VehicleInsertion.html#forcing_insertion_avoiding_depart_delay

**Comment by Shiyunyang-seu** [comment]
Thanks for your replying! According to your suggestion, when the number of lanes decrease from 3 to 2, there is a queue indeed, but when the number of lanes decrease from 2 to 1 (as shown in the figure, the vehicle will not take the lower lane, but will change lanes very early). Even if I add lcstrategic ='0.1 'lckeepright = '0.1'
![1](https://user-images.githubusercontent.com/55737075/85438921-06760400-b5bf-11ea-97e0-60b8f740983f.png)

**Comment by namdre** [comment]
lcStrategic must be specified in the vType. Then you will see queuing at both bottlenecks.

```
    <vType id="t0" lcStrategic="0.1"/>
    <flow id="1" type="t0" from="gneE0" to= "gneE2" begin="0.0" vehsPerHour= "10000" end="3600.0" departLane="free" departSpeed="max"/>
```

**Comment by Shiyunyang-seu** [comment]
Thanks for your replying. Actually,the IcStrategic has been specified in the vType, but vehicles still start to change their lane at the red line, but in real world they should also use the other lane(Even though it can cause congestion).
![1](https://user-images.githubusercontent.com/55737075/85530993-f272e680-b640-11ea-9970-cc4dd1619d23.png)
![2](https://user-images.githubusercontent.com/55737075/85531177-1e8e6780-b641-11ea-9ffe-be0cf3d494ad.png)

**Comment by namdre** [comment]
If you wish achieve equal use among both lanes you can set the junction type to 'zipper' and set connections from both lanes to the target lane.
