### ISSUE TITLE
Libsumo MemoryError

### ISSUE THREAD

**Issue by marcelreppi** [eclipse/sumo#7220]
Hello,

using libsumo I experienced the following error:

```
MemoryError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mazel/master-thesis-code/sumo/traci/simulation_controller.py", line 47, in start
    traci.simulationStep(step)
  File "/usr/local/share/sumo/tools/libsumo/libsumo.py", line 85, in simulationStep
    result += [(k, v) for k, v in domain.getAllContextSubscriptionResults().items()]
  File "/usr/local/share/sumo/tools/libsumo/libsumo.py", line 4985, in getAllContextSubscriptionResults
    return _libsumo.vehicle_getAllContextSubscriptionResults()
SystemError: <built-in function vehicle_getAllContextSubscriptionResults> returned a result with an error set
```

The same code worked with regular TraCI so I am not exactly sure what happened.
Hope this is easily fixable!

Thanks!

Best regards
Marcel

**Comment by marcelreppi** [comment]
I was running this simulation in WSL2.
I noticed that when running my scenario with TraCI the memory consumption is fairly constant (around 2.5-3 GB) but when I used libsumo the memory consumption just endlessly increases.
I do have 16GB of RAM so I would expect that not be an issue.

**Comment by namdre** [comment]
Several issues of this kind were already found in 1.6.0 and fixed. Did you try with the latest development version? If so, can you try to narrow it down to as few functions as possible to trigger the memory leak?

**Comment by marcelreppi** [comment]
I was able to narrow it down to this part of my code:
```
for vid in traci.simulation.getDepartedIDList():
  traci.vehicle.setParameter(
      vid, "zone_timestep", self.zone_controller.current_timestep
  )
  traci.vehicle.subscribe(
      vid,
      [
          tc.VAR_POSITION,
          tc.VAR_SPEED,
          tc.VAR_EDGES,
          tc.VAR_ROUTE_INDEX,
          tc.VAR_EMISSIONCLASS,
      ],
  )
  traci.vehicle.subscribeContext(
      vid,
      tc.CMD_GET_POLYGON_VARIABLE,
      self.sim_config["dynamicReroutingDistance"],
      [tc.ID_COUNT],
  )
```

This loop is executed every simulation step.
I have repeatedly checked and the **main cause** of the memory leak is the following:

```
traci.vehicle.subscribe(
      vid,
      [
          tc.VAR_POSITION,
          tc.VAR_SPEED,
          tc.VAR_EDGES,
          tc.VAR_ROUTE_INDEX,
          tc.VAR_EMISSIONCLASS,
      ],
  )
```

I have recently also opened this issue #7209 which was already fixed. 
Maybe this is somehow related?

**Comment by namdre** [comment]
Subscriptions are supposed to allocate additional memory.
I'm guessing that this memory is not cleaned up once the vehicle leaves the simulation.

**Comment by marcelreppi** [comment]
Yes I had the same thought.

I would very much appreciate a quick fix because it would save me a lot of time and money (using AWS EC2 instances) for running my simulations.
Thank you very much!

**Comment by behrisch** [comment]
Please reopen if problems persist.

**Comment by marcelreppi** [comment]
It's working! 🎉 
Thank you very very much!!

**Comment by behrisch** [comment]
It's a pleasure. Consider donating the saved money to a good cause :-)

**Comment by marcelreppi** [comment]
Great idea! 😊 


![image](https://user-images.githubusercontent.com/22420478/85750647-2bc35900-b70a-11ea-9a80-310cd1be1337.png)

**Comment by marcelreppi** [comment]
Hello again,

I think there is still some issue here...
I have some custom rerouting in my scenario and when it is turned off the memory consumption is fairly constant.
When I turn it on, even just for 5% of all vehicles, after a while the memory consumption continuously rises.

Possible other causes (except the one that was previously fixed) that are related to my rerouting are:

- I set 3-4 parameters per vehicle using `traci.vehicle.setParameter` which I also access frequently. Maybe they aren't cleared after a vehicle has arrived?

- I set custom traveltimes for individual vehicles using `traci.vehicle.setAdaptedTraveltime(vid, eid, time=t)`. This can often cover every edge in the whole network. For rerouting I then use `traci.vehicle.rerouteTraveltime(vid, False)`. Maybe the custom traveltimes for individual vehicles are not cleared once they have arrived?

Even my 16GB laptop reaches the maximum after running the simulation for a while...

Thank you very much!

**Comment by marcelreppi** [comment]
I can't reopen the issue... there is no button for it

**Comment by marcelreppi** [comment]
You can actually look at my TraCI code here:

Setting up newly departed vehicles:
https://github.com/marcelreppi/master-thesis-code/blob/1a30b022be881ae8fe7a199bc13885639104d23c/sumo/traci/vehicle_controller.py#L380

Checking if to reroute a vehicle or not:
https://github.com/marcelreppi/master-thesis-code/blob/1a30b022be881ae8fe7a199bc13885639104d23c/sumo/traci/vehicle_controller.py#L170

Actual rerouting
https://github.com/marcelreppi/master-thesis-code/blob/1a30b022be881ae8fe7a199bc13885639104d23c/sumo/traci/vehicle_controller.py#L114

**Comment by behrisch** [comment]
I fixed a leak which is probably unrelated, can you try to narrow it down maybe by disabling the explicit rerouting call and look whether the problem persists?

**Comment by marcelreppi** [comment]
Yes I will try and let you know tomorrow.
Thanks a lot!

**Comment by marcelreppi** [comment]
The simulation still crashes.

I have thought about my use case a bit more and I think I know why it could crash.
I have roughly 290k vehicles throughout the simulation. And for most of them I set custom edge weights for almost every edge of the network and I think this is what is causing the immense memory consumption.

I believe my program is not coded in the most efficient way because for example all vehicles that enter between 01-00-00 and 02-00-00 get the same edge weights. I am using TraCI to set individual edge weights instead of using a weights file. I did it this way initially because 1) I don't want to affect the device.rerouting (global) edge weights and 2) I have some edges cases where I would maybe want specific vehicles to have a little bit different edge weights.

This leads me to the question: Is there a way to define an edge weights file and assign only this file to certain vehicles? I would need to use TraCI with these custom weights to reroute without affecting the edge weights calculated for the device.rerouting.
I already looked into the docs for rerouting and I only saw that you can specify an interval for when custom weights should be active. But it also seems that they are global (they affect the device.rerouting) and not for specific vehicles...

A solution for my use case would be a way to define different custom "edge weight profiles" and then assign these profiles to certain vehicles using TraCI. This way they can share the same edge weights without having to store them each individually when they are exactly the same. The device.rerouting weights should of course not be affected.
Would something like that be possible?

I assume setting custom edge weights via TraCI was most likely designed for modifying a few vehicles instead of almost all of them but this would immensely help with my masters thesis.

Thank you very much for your efforts!

**Comment by behrisch** [comment]
If you need just one additonal edge weight profile at a time you could use efforts and route by effort for traci while still using traveltime for device.rerouting. If you need several weight profiles simultaneously you are currently out of luck and this is not implemented easily, I suppose.

**Comment by marcelreppi** [comment]
For my most basic case one edge weight profile at a time would be enough.
However, I have tried using efforts in the past but I ended up not using it because I got really weird results... here are some of my observations:

Some basic information first: the vehicle drives from right to left. All edges covered by the polygons get a custom (very high) edge weight so that the vehicles drives around them.

When using traveltime I got the following results which seem optimal to me.

![reroute-traveltime](https://user-images.githubusercontent.com/22420478/86917034-c36e7180-c124-11ea-8d63-eb69b0614e41.png)

If use the same values for effort that I use for traveltime without any further adaptation to my code I get the following results.

![reroute-effort-bad](https://user-images.githubusercontent.com/22420478/86917252-0d575780-c125-11ea-81e5-9b2e1104a427.png)

I saw that the default effort is `-1.0`. Only when I iterated through the whole network beforehand to set every edge effort to at least `1.0` and then apply to custom weights on top I got the following result. 

![reroute-effort](https://user-images.githubusercontent.com/22420478/86917416-56a7a700-c125-11ea-9ffd-d32dab4e4940.png)

The last one is still not the same as the traveltime so therefore I did not use effort in the first place.

![reroute-comparison](https://user-images.githubusercontent.com/22420478/86917702-d5044900-c125-11ea-9a79-ead8ef830a25.png)

Do you have any insight as to why this happens and how I could fix it so that I get the same results?

Thanks a lot!

**Comment by behrisch** [comment]
First of all, yes -1 is the worst possible default, see #7296. What happens when you set 1 as the effort is that the router chooses the route with the fewest number of edges but this is not always the shortest one. So a good result should be if you set length divided by maxspeed.

**Comment by marcelreppi** [comment]
Using `length / max speed` did indeed lead to the same results!
I am closing this issue for now.

Thank you very much for your help!!!
