### ISSUE TITLE
SGAP, minGap, and distance returned from MSVehicle::getLeader()

### ISSUE THREAD

**Issue by whatgit** [eclipse/sumo#7233]
Hello, 
(this is also related to TGAP, but TGAP is highly related to SGAP, so I omit it for the moment)

I apologize in advance if I completely misunderstood the code.

I was trying to log the "SGAP" (and "TGAP") in the SSM device output. Then I see some strange values that did not make much sense to me. Therefore, I look deeper into the code why the value does not make sense. And this is what I found.

This is currently how SGAP is calculated:
https://github.com/eclipse/sumo/blob/1a95f0fc7063d77489ed00bb8bc7c0280dedc826/src/microsim/devices/MSDevice_SSM.cpp#L478

Then I ask myself:
##  Why  is `minGap` part of the equations here?

I dig further, and see that this is because of how `MSVehicle::getLeader()` is implemented.

https://github.com/eclipse/sumo/blob/e8c2d7e9a81fbfb9f57867ba8fedcfcb376e8a0e/src/microsim/MSVehicle.cpp#L5627-L5632

Then, I realized that this returns `gap - minGap`, instead of just returning the actual `gap` (let us define `gap` here as the distance from front bumper of ego to rear bumper of the leader).

I do not know SUMO enough in details to understand the motivation behind involving `minGap` here, hopefully someone can clarify it for me.

## Note
Of course, this all works fine as long as the same `minGap` is set for all vehicles. It just happens that I have set it differently for this particular leader-follower pair that I checked the result.

**Comment by namdre** [comment]
minGap is part of the equation for historical reasons. The car follow model that was first implemented was expected to treat minGap like a part of the vehicle itself (minGap should never be violated). Other models add the minGap back in when needed.

**Comment by whatgit** [comment]
Thank you for the response and the fix @namdre . 

If I may ask one further question:
I am still a bit confused why should ` - getVehicleType().getMinGap()` be kept in the line below. I guess it is still needed for the old car-following models to work (?). Is that true? Could you please clarify it?

https://github.com/eclipse/sumo/blob/e8c2d7e9a81fbfb9f57867ba8fedcfcb376e8a0e/src/microsim/MSVehicle.cpp#L5629
