### ISSUE TITLE
The problem of setting the number of vehicle nodes

### ISSUE THREAD

**Issue by Mzy526** [eclipse/sumo#7235]
I want to produce the scene under different vehicle number, for example, I want to test 200 vehicles, respectively, 150 cars and 100 vehicles, 50 at the intersection of car scene, but I always can not reach the maximum vehicle number in the scene of the 200 or 150, because these vehicles run left the vehicle number in my scenario never reached 200 or 150, 100, how do I set the vehicle number, please?
[scenario.zip](https://github.com/eclipse/sumo/files/4840747/scenario.zip)

**Comment by Mzy526** [comment]
Attached is my SUMO file

**Comment by namdre** [comment]
see https://sumo.dlr.de/docs/FAQ.html#how_do_i_maintain_a_constant_number_of_vehicles_in_the_net
