### ISSUE TITLE
I cannot install the last version of sumo 1.6.0 in Mac.

### ISSUE THREAD

**Issue by cesarg39** [eclipse/sumo#7241]
I have been to try install the last version of sumo with the homebrew but I cannot install and I have to come back  at older version 0.32, using the macports 

Please help me to install the last version

**Comment by behrisch** [comment]
Can you please give the detailed error message.

**Comment by angelobanse** [comment]
We already fixed it. The problem was:
- SUMO_HOME was not set
- PATH pointed to an old SUMO version that he had installed
- Fox has a bug on macOS Catalina, it is necessary to use the Mojave bottle of Fox (see https://github.com/eclipse/sumo/issues/6242#issuecomment-553458710)
