### ISSUE TITLE
An error occurred while using an if condition in a for loop in TraCI

### ISSUE THREAD

**Issue by MohamadReza-Haghani** [eclipse/sumo#7245]
Hi,

I got into an error while utilizing if conditions in a for loop in TraCI. As it is shown here in the first code, the if conditions are checked for every vehicle at every simulation step. However, since in the second code, the term 'vehtp == "1"' is added to the if condition, while running, every vehicle is checked once in the conditions. I was wondering to know how I should change it that the if conditions are checked for every vehicle at every simulation step until the end of simulation. I appreciate for any help in advance.

Thanks,
Reza.

![1](https://user-images.githubusercontent.com/64617116/86073355-93064380-ba51-11ea-8c2a-02e33b3c9b9c.PNG)
![2](https://user-images.githubusercontent.com/64617116/86073357-93064380-ba51-11ea-9e23-a330daa31c7e.PNG)

**Comment by behrisch** [comment]
This has nothing to do with traci but seems to be a rather general programming question. You probably wanted to write this:
```
if veh_tp == "1":
    if 20 < sim_time < 40:
        ...
    elif sim_time > 40
        ...
```
