### ISSUE TITLE
Add scrollbar into OverlappedInspection modul

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#7247]

**Comment by palvarezlopez** [comment]
Changed priority due inspection of generic datas

**Comment by namdre** [comment]
default-size could be improved upon so that unnecessary scrollbars are avoided when there is sufficient vertical space in the frame:
![Screenshot from 2020-07-03 15-56-09](https://user-images.githubusercontent.com/6240630/86475908-cf81ba00-bd45-11ea-8405-7d490bf77c03.png)
