### ISSUE TITLE
Traffic flow setting problem on the road

### ISSUE THREAD

**Issue by Mzy526** [eclipse/sumo#7270]
I want cars to travel evenly across all three lanes of the road, not just one lane, and how do you set the vehicle density, like 100 cars per kilometer

**Comment by namdre** [comment]
see 
- https://sumo.dlr.de/docs/Definition_of_Vehicles,_Vehicle_Types,_and_Routes.html#departlane
- https://sumo.dlr.de/docs/FAQ.html#how_do_i_insert_vehicles_with_a_fixed_density
