### ISSUE TITLE
Crash problem of sumocfg

### ISSUE THREAD

**Issue by AnsonChan852** [eclipse/sumo#7273]
After running the sumocfg, crash & flashback. Exclude the problem of sumo software since it can run the other simply network which assign random. The computer is win10 base.

[test.zip](https://github.com/eclipse/sumo/files/4867665/test.zip)
All the file including od matrix, net, taz and sumocfg also inside the zip file.

**Comment by namdre** [comment]
The network file is invalid. Was it edited with some other tool besides netedit/netconvert by chance?
If not, can you reproduce the steps that created this network?

A quick way to fix the network is to call `netconvert -s lefthand.net.xml -o fixed.net.xml`

**Comment by namdre** [comment]
closing due to lack of feedback
