### ISSUE TITLE
e2detector attribute freq is optional

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#7275]
currently, netedit requires it on loading.

Either "Freq" or "TL"

**Comment by palvarezlopez** [comment]
@namdre Question: There is two ways to fix this:

1) Add attribute "TL", that can have any string. Netedit don't check if this Strings correspond to a TL or not.

2) Add a strong relationship between TL und E2 detectors:
-> E2 detector could be a child of a (1...n)s GNELane AND a (0...1) GNETLS
-> We need a new GNETLS class


Solution 2 will take more time and code, but a new GNETLS class could be very usefull for edit traffic lights

**Comment by namdre** [comment]
For now I would go with option 1 and then do option 2 once we have GNETLS (since TLS-editing is mostly working I would not want to prioritize this now but defer the work to some later point in time).

**Comment by palvarezlopez** [comment]
Current version works. Option 2 will be implemented in #7370
