### ISSUE TITLE
add HBEFA4 model

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#7277]
- reduce gaps in model coverage (#6707 )
- provide dis-aggregated classes
- include model for pseudo-friction so that low accelerations do not cause zero-emissions (as with the other models)
- make HBEFA4 the new default

**Comment by NoNoid** [comment]
Is there an ETA on HBEFA4?

**Comment by behrisch** [comment]
AFAIK no one is working on it currently so definitely not 2021

**Comment by namdre** [comment]
> Is there an ETA on HBEFA4?

Could happen in 2022 (the coefficients are ready and only need to be integrated)

**Comment by behrisch** [comment]
docs are still missing

**Comment by namdre** [comment]
docs are online. Anything still missing?

**Comment by behrisch** [comment]
we still wanted to make the tables sortable and highlight the entries with high error values

**Comment by behrisch** [comment]
work continues in #11505 and #11506
