### ISSUE TITLE
sumo - route valid and saying no connection between two edges

### ISSUE THREAD

**Issue by AnsonChan852** [eclipse/sumo#7281]
After running the simulation, the system show this msg

Warning: No connection between edge 'n20n17' and edge 'n29n28' found.
Warning: No route for vehicle '243253' found.
Error: Vehicle '243253' has no valid route.
Quitting (on error).

All the files including od, net, od2trips placed in the zip file
[X (2).zip](https://github.com/eclipse/sumo/files/4872833/X.2.zip)

**Comment by angelobanse** [comment]
You have to modify the network or the routes. I have seen that multiple trips defined in the `od_file1.odtrips.xml` cannot be performed (some edges defined in the trips `from` and `to` have no possible connection)
