### ISSUE TITLE
links in sumo-gui and netedit do not work in macOS

### ISSUE THREAD

**Issue by angelobanse** [eclipse/sumo#7286]
Links in the About dialog (the EPL-2.0 license and SUMO website) or links to the Online Documentation (in the Help menu) do nothing on macOS.

I have tested it on macOS Catalina (10.15.5) with SUMO 1.6.0 and with the Latest Development Version.

**Comment by behrisch** [comment]
@angelobanse Please recheck and maybe add safari :-)

**Comment by angelobanse** [comment]
@behrisch It still doesn't work :(

**Comment by behrisch** [comment]
But starting firefox from the command line with `firefox` works on MacOS, doesn't it?

**Comment by RobertHilbrich** [comment]
Nope - `open https://eclipse.org/sumo` works to start the default browser, but the firefox app cannot be started from the terminal like that on macOS.

**Comment by angelobanse** [comment]
`open https://eclipse.org/sumo` opens the default Browser, to open it with a certain browser (e.g. Firefox) you should use `open -a firefox "https://eclipse.org/sumo"` (the double quotes are important in this case)

**Comment by behrisch** [comment]
It is hard to test this without a mac. The code is in src/utils/foxtools/FXLinkLabel.cpp. I would be glad if one of you gave it a try. The easiest fix could be to add "open" to the end of the list of programs here: https://github.com/eclipse/sumo/blob/5446dd825c5057cfe5e4efb6e436eb75b1f04539/src/utils/foxtools/FXLinkLabel.cpp#L49.

**Comment by angelobanse** [comment]
it works now. 👍 thanks @behrisch
