### ISSUE TITLE
netedit slowdown when polylines are loaded

### ISSUE THREAD

**Issue by ZoltanBaksa** [eclipse/sumo#7287]
Hi,
I use currently the latestDev version v1_6_0+1090-8910f245e3
I have a lot (aprox. 120) polylines, that represent the routes of public transport buses in a city. When I load the network only and try to select edges, or move with mouse everything works fine, eg. the effect takes place instantly. When I load at least one not closed polygon, these actions take at least 10 seconds at each mouse click.

**Comment by palvarezlopez** [comment]
@ZoltanBaksa thanks! I'm going to check it.

**Comment by palvarezlopez** [comment]
@ZoltanBaksa can you check if the last version works fine with polylines?

**Comment by ZoltanBaksa** [comment]
Yes, I can try it tomorrow, after the new daily version is created.

Feladó: Pablo Alvarez Lopez <notifications@github.com>
Küldve: 2020. július 8., szerda 15:14
Címzett: eclipse/sumo <sumo@noreply.github.com>
Másolatot kap: Baksa Zoltan (PS-TC/ENG12-Bp) <Zoltan.Baksa@hu.bosch.com>; Mention <mention@noreply.github.com>
Tárgy: Re: [eclipse/sumo] netedit slowdown when polylines are loaded (#7287)


@ZoltanBaksa<https://github.com/ZoltanBaksa> can you check if the last version works fine with polylines?
