### ISSUE TITLE
No SUMO snapshot with .svg

### ISSUE THREAD

**Issue by MelanieWeber** [eclipse/sumo#7289]
Saving failed.

Could not save ...svg gl2ps was not enabled at compile time.

(windows download and windows + extra download)

**Comment by behrisch** [comment]
works here with https://sumo.dlr.de/daily/sumo-win64extra-git.zip as well as https://sumo.dlr.de/releases/1.6.0/sumo-win64extra-1.6.0.zip

**Comment by behrisch** [comment]
no further updates, please reopen if problems persist

**Comment by Michael-wang0225** [comment]
> Saving failed.
> 
> Could not save ...svg gl2ps was not enabled at compile time.
> 
> (windows download and windows + extra download)

hello, i am facing the same problem. Could you please tell me how you fixed it?

**Comment by behrisch** [comment]
Please double check you used the "extra" version and report your operating system and precise SUMO version.

**Comment by Michael-wang0225** [comment]
> Please double check you used the "extra" version and report your operating system and precise SUMO version.

Hi, i am using SUMO 1.11.0， with windows 10 system.

**Comment by palvarezlopez** [comment]
> > Please double check you used the "extra" version and report your operating system and precise SUMO version.
> 
> Hi, i am using SUMO 1.11.0， with windows 10 system.

Tomorrow download the last SUMO dev-version
