### ISSUE TITLE
default effort should not be -1 when routing by effort

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#7296]
This confuses every routing algorithm but it is hard to tell what a good default is. Either NUMERICAL_EPS, 1, some large value or length/speed would be good.

**Comment by namdre** [comment]
As far as I can tell, the default effort is 0 (as explained in #6886)
Having a default of 1 might be better for some but not all use cases.

Where does the -1 come from?

**Comment by behrisch** [comment]
It was mentioned here: https://github.com/eclipse/sumo/issues/7220#issuecomment-655483406. I did not validate this. But 0 seems not very helpful as a default. We should use at least some epsilon (will update the description).

**Comment by behrisch** [comment]
work continues in #6886
