### ISSUE TITLE
How can I set the automatic driving vehicle and manual driving vehicle  in sumo?

### ISSUE THREAD

**Issue by zhaotuo0815** [eclipse/sumo#7299]
HI,I just wondering that can manual driving vehicles and automatic driving vehicles be distinguished by modifying car following and lane changing models when setting vehicle types,just like..
<vType id="hv_bus" vClass="bus" accel="2.6" decel="2" sigma="1" carFollowModel="IDM" length="12" minGap="3"  maxSpeed="40" color="1,0,0" guiShape="bus"/>
<vType id="av_bus" vClass="bus" accel="2.6" decel="2" sigma="0" carFollowModel="CACC" lcKeepRight="0" length="12" minGap="3"  maxSpeed="40" color="0,1,0" guiShape="bus"/>

**Comment by behrisch** [comment]
The automation implementation may differ considerably between manufacturers and there is no standard implementation or large real world fleet available so it is basically guessing (or using well motivated assumptions, scientifically spoken). What we usually do is to reduce the tau (aspired time gap) and maybe also the minGap, assuming automated vehicles drive shorter gaps. sometimes we also assume different accelerations / deceleration but it is not clear here whether the automated car is "snappier" (reaction time reduced) or needs to drive more conservative to reduce motion sickness.
