### ISSUE TITLE
A large number of bus stops converted from OSM by Netconvert are missing

### ISSUE THREAD

**Issue by Shiyunyang-seu** [eclipse/sumo#7303]
Hi, I used Netconvert to extract bus stops from OSM, but I found that only subway stations were extracted and many bus stops were not converted successfully. By comparing the stations which are converted successfully in OSM, there is no missing information between them and those not converted.

[busstop-osm.zip](https://github.com/eclipse/sumo/files/4906432/busstop-osm.zip)

**Comment by namdre** [comment]
Please try with the latest development version as it already contains the fix for #6963 
If any busStop is still missing please specify its osm ID.

**Comment by namdre** [comment]
closing due to lack of feedback
