### ISSUE TITLE
Erratic behaviour of FXRealSpinner in color scheme

### ISSUE THREAD

**Issue by m-kro** [eclipse/sumo#7304]
View settings allow to set a color scheme with threshold values for each color. The thresholds are sorted in ascending order and can be lowered only up to the directly preceding value.

If the thresholds are edited using the small "up" and "down" arrows, everything is fine in this respect. Typing the value however has undesired effects, if the GUI elements have just been loaded:

**If the first typed digit is smaller than the preceding threshold, the latter is set to this value (only in the GUI - the old and still correct value is saved). If the values have already been altered using the arrows, everything works as expected.**

Experienced using a recent development version...

**Comment by behrisch** [comment]
The succeeding threshold seems to be affected as well, if large numbers are entered

**Comment by namdre** [comment]
The code tried to enforce ranges for the surrounding thresholds. However, it did not do this reliably if the entered value went beyond the allowed range of the thresholds that were not direct neighbors. 
I decided that the erratic behavior was more bothersome than the unreliable consistency check was worth and therefore removed the whole range-setting code.
