### ISSUE TITLE
Loading simulation failed because of invalid threshold in color scheme "by edgeData (numerical, streetwise)"

### ISSUE THREAD

**Issue by m-kro** [eclipse/sumo#7305]
View settings have been created before running a simulation and saved for reuse. The color scheme creates an invalid/overflow(?) threshold value:

`            <colorScheme name="by edgeData (numerical, streetwise)" interpolated="1">
                <entry color="204,204,204" threshold="179769313486231610000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000.00" name="missing data"/>
            </colorScheme>`

SUMO stops loading the simulation with the error message **Error: Attribute 'threshold' in definition of a entry is not of type float.**.

**Comment by behrisch** [comment]
It works here (windows), although the serialized value looks slightly different. Which platform are you on?

**Comment by m-kro** [comment]
Well, Windows. It works with v1.6.0 but fails with a self-compiled (VS2019) version of a recent development state.

**Comment by behrisch** [comment]
@namdre I don't like my solution, if you have a better idea, please speak up.

**Comment by namdre** [comment]
We could use "max" as the implicit default and not write it at all.
