### ISSUE TITLE
Problem in Set Lateral Alignment in TraCI

### ISSUE THREAD

**Issue by MohamadReza-Haghani** [eclipse/sumo#7306]
Hi,

This is the second time I am asking this question here. I appreciate if any one can help me with this question. I wrote a code, in TraCI, in order to make vehicles to pull over and stop in a two-lane one-way road and in a specified duration. For the vehicles moving in the right lane, the lateral alignment is set to "right," and the speed is set to 0. Also vehicles in the left lane are forced to change lane to the right lane. When the code is running, the vehicles on the right lane pull over to the right side of the lane and stop. The vehicles on the left lane change their lanes but stop in the left side of the right lane. I checked their lateral alignment. Although it is set to "right", they stop in the left side. Please find attached a screenshot of the code and other required files. Any help would be appreciated.

Thanks,
Reza.

![Capture](https://user-images.githubusercontent.com/64617116/87258212-d3ad8600-c46f-11ea-88e5-3c2fbf8a2c79.PNG)

[ezyzip.zip](https://github.com/eclipse/sumo/files/4909771/ezyzip.zip)

**Comment by namdre** [comment]
is this still relevant?
