### ISSUE TITLE
Meso and carFollowModel?

### ISSUE THREAD

**Issue by jylee3302** [eclipse/sumo#7307]
Hi,

I'd like to ask if the type of carFollowModel defined in vType attribute has impact in meso-simulation.
If 2 vTypes, one Krauss and the other one IDM, and mesosim true, are these two vehicles moving differently under different car-following model? Or the same movement in mesosim?

Does the vType attributes (e.g., minGap, accel, decel, emergencyDecel, etc.) affect vehicle characteristics in mesosimulation? If not, what are the ignored vType attributes in meso simulation?
(I'm trying to simulate vehicle heterogeneity using meso.)

**Comment by behrisch** [comment]
The model itself has no influence but some of the parameters do, especially length, minGap and maxSpeed, accel and decel are used for some calculations (but I would rather see this a s a leftover from microsim than as a meso feature.

**Comment by namdre** [comment]
Heterogenity (vehicle lengths and speeds) are features we use in our own meso simulation hence I do not see this as a leftover. 
I've documented the attributes recognized by meso here: https://sumo.dlr.de/docs/Simulation/Meso.html#used_vtype_parameters

**Comment by behrisch** [comment]
> Heterogenity (vehicle lengths and speeds) are features we use in our own meso simulation hence I do not see this as a leftover.

Just to make this clear: Leftover only referred to `accel`and `decel`.
