### ISSUE TITLE
Setting shape of node from api

### ISSUE THREAD

**Issue by roik** [eclipse/sumo#7308]
Hi, 
I've used the example (https://github.com/eclipse/sumo/blob/master/tests/tools/sumolib/patch_network/runner.py) you gave in order to move nodes of existing junction.
I want to edit junction shape as well from api and wasn't able to do so.
I saw that  if I don't use api, delete junction shape in netedit and than F5 in order to recalculate net it works, my question is how can I do it with api.

Thanks in advance

**Comment by m-kro** [comment]
The procedure does not change much in this respect. In the same way you can set the reference position of a node, you can set a new shape. The linked script just calls netconvert with some options. It needs a [Plain XML style](https://sumo.dlr.de/docs/Networks/PlainXML.html) file as input. Please refer to the Plain XML reference what attributes are available.
