### ISSUE TITLE
Problem of direction

### ISSUE THREAD

**Issue by AnsonChan852** [eclipse/sumo#7310]
In the network, i have invalid all the U-turn direction like that. 

    <connection from="n41n40" to="n40n39" fromLane="0" toLane="0" via=":n40_6_0" tl="n40" linkIndex="6" dir="invalid" state="o"/>
    <connection from="n41n40" to="n40n41" fromLane="0" toLane="0" via=":n40_7_0" tl="n40" linkIndex="7" dir="invalid" state="o"/>

Also set up the traffic light to block U-turn direction. But in the simulation the veh always U-turn.
How to slove this problem? Or to delect the stop line
[neo_X_1.zip](https://github.com/eclipse/sumo/files/4917187/neo_X_1.zip)

**Comment by lbieker** [comment]
Normally, you can use the option --no-turnarounds in netconvert to avoid u turns (https://sumo.dlr.de/docs/Networks/Further_Options.html). But if you have to edit the net manually you can use netedit (network mode, connection mode) to exlude specific connections.

**Comment by namdre** [comment]
also see https://sumo.dlr.de/docs/FAQ.html#i_made_changes_to_the_netxml-file_but_it_did_not_work_as_expected_why
