### ISSUE TITLE
netedit: tl join by giving same tl name leads to wrong net.xml

### ISSUE THREAD

**Issue by ZoltanBaksa** [eclipse/sumo#7311]
Hi,
I use currently the latest development version v1_6_0+1218-642d16a7a5, but the issue is observed also in 1.6.0 release.
I usually create TL controlled junctions by separating the real junction from the positions, where the vehicles must stop, to represent the reality more accurate, and not to have huge junction shapes.
During the process I usually create additional junctions for each direction, and then add TL programs for each. To join them, I use the inspection mode, where I rename the TL program and add the same name for all. At the next step I change the TL index of the connections to match the real world TL program's order. And at last I define the different TL programs and waut schedulings based on the existing phase plans in TL mode.
In some cases the the process works fine, but in some cases the changing of the connections' TL index leads to error, because the additional junctions turn into inconsistent state.  Sometimes, if I click on the different TL joined junctions, the TL id of the connections changes, and even the TL program in the side panel is also different.
According to the inspection window, all junctions type is traffic_light, but the TL program name is lost. When I change it to priority, and try to create TL program again, nothing happens. The connections within the .net.xml related to these junctions become a tag uncontrolled="1" and until I delete them directly the situation is not changing.
After I delete these tags, the above described process works again.
Where do I make a mistake during the process, which leads to this?
Is there another, better way to create these TL joined separate junctions accordingly?
Regards
Zoltan

**Comment by namdre** [comment]
I don't think you are making a mistake in the process. Most likely there is some edge case when re-assigning tl indices where netedit bugs out. If you can provide an example network and a sequence of operations for reproducing the inconsistent state we can fix this.

**Comment by ZoltanBaksa** [comment]
Hello Jakob,
Thanks for your answer. I sent you an example, where I try to TL control a 'Turbo roundabout'. In this case the moving of custom endpoints does not play a role.

**Comment by namdre** [comment]
a classic case of memory corruption by modifying a vector while iterating over it.
