### ISSUE TITLE
Assertion error

### ISSUE THREAD

**Issue by cspatharis** [eclipse/sumo#7312]
Hello,
I've been running into an unusual problem lately. I have installed sumo version 1.6.0 on Ubuntu 20.04 and it fails to load scenarios created by OSM Web Wizzard. More specifically it outputs the following error message while running:

Simulation version 1.6.0 started with time: 0.00
sumo: /build/sumo-1YPhJX/sumo-1.6.0+dfsg1/src/microsim/output/MSInductLoop.cpp:128: virtual bool MSInductLoop::notifyMove(SUMOTrafficObject&, double, double, double): Assertion `entryTime < leaveTime' failed.

I'm using SUMO through TraCI and my Python version is the '3.8.2'. 
sumo --version output:
Eclipse SUMO Version 1.6.0
Build features: Linux-4.4.0-178-generic x86_64 GNU 9.3.0 None Proj GUI SWIG GDAL GL2PS

Thanks in advance.

**Comment by m-kro** [comment]
Assertions are evaluated **only in debug mode**. If you want to see how the simulation continues, please build the release version.

However one should also try to understand why the assertion triggered. Do you have a detector at a position in the network where vehicles are inserted?

**Comment by cspatharis** [comment]
I 've re-installed SUMO from source and now it works as intended. 

Thanks for your immediate response.
