### ISSUE TITLE
congested() in MSVehicle

### ISSUE THREAD

**Issue by Domsall** [eclipse/sumo#7315]
In the old DK2008 model the congested function (in MSAbstractLaneChangeModel) to check whether a Highway is congested, takes the SpeedLimit into account.
In the LC-models LC2013 and SL2015 this isn't done anymore, only the actual speed is used. But with this implementation vehicles aren't allowed to overtake on the right when driving higher speeds than 60km/h. This often happens at 50km/h or 60km/h speed limits (with high enough SpeedFactors).
Why not also check for the Speed Limit to get the road type?

Code:
```
bool congested() const {
    return myState.mySpeed < double(60) / double(3.6);
}
```

Could be changed to something like:
```
bool congested() const {
    if (myLane->getSpeedLimit() > double(70 + NUMERICAL_EPS) / double(3.6)) {
        return myState.mySpeed < double(60) / double(3.6);
    } else {
        return true; // true means that the vehicle is allowed to overtake on the right
    }
}
```

**Comment by Domsall** [comment]
Are there any objections this shouldn't be changed / used as in DK2008?

**Comment by namdre** [comment]
In principle I have no objections. Though I would use the road speed limit at 60km/h+epsilon rather than 70. 
Also, plenty of tests seem to be affected by the change so I'll have to check whether this is ok.
