### ISSUE TITLE
duarouter: Edge a not connected to edge b for vehicle x

### ISSUE THREAD

**Issue by AakashSasikumar** [eclipse/sumo#7319]
System Specs:
- sumo version: 1.6.0
- built from source: no (apt install)
- OS: Ubuntu 16.04

I have created a statistics file for a city to simulate. Using `activitygen`, a trip file was generated. When trying to get the route file using `duarouter`, I get the following error

```text
Edge '-254968961#0' not connected to edge '-28952785#1' for vehicle 'bl14b6:17'.
Edge '-28952785#1' not connected to edge '225516712#0' for vehicle 'bl14b6:17'.
Edge '225516712#0' not connected to edge '192552507#1' for vehicle 'bl14b6:17'.
Edge '192552507#1' not connected to edge '635235528#1' for vehicle 'bl14b6:17'.
Edge '635235528#1' not connected to edge '-766805264' for vehicle 'bl14b6:17'.
Edge '-766805264' not connected to edge '88572932#0' for vehicle 'bl14b6:17'.
Edge '88572932#0' not connected to edge '27571801#1' for vehicle 'bl14b6:17'.
```
This error appears for pretty much all the bus routes that were defined in the stat file. Here is a sample bus route that was generated by `activitygen`

```xml
<trip id="bl14b6:17" type="bus" depart="23160.00" departPos="22.05" arrivalPos="12.04" arrivalSpeed="0.00" from="37573385" via="-286434721#1 -254968961#0 -28952785#1 225516712#0 192552507#1 635235528#1 -766805264 88572932#0" to="27571801#1"/>
```

As you can see, the intermediate edges were mentioned in the `via` attribute but `duarouter` expects them to be neighboring edges.

Also, I have checked if there was a valid route between two of these routes using `net.getShortestPath()` and all these pairs have a valid route.

If I run the command with the `--ignore-errors` argument, it seems to fill in the missing edges, but I want to be able to run it without the `--ignore-errors` argument as I want to see if there are more important errors in routing for other vehicles. I was under the assumption that duarouter would be able to handle incomplete routes.

Any help regarding this would be appreciated and I'll be glad to provide additional information.

**Comment by behrisch** [comment]
I suppose your vType "bus" has vClass "bus" and there are some intermediate edges forbidding  busses. Please double check whether the vClasses and edge permissions are correct. net.getShortestPath does not check the vClass by default while the duarouter does.

**Comment by AakashSasikumar** [comment]
I see. I got the net file by converting an OSM file. I assumed the permissions would be mapped correctly. Is there something extra I need to do when converting it?

**Comment by behrisch** [comment]
The easiest way is to run duarouter with **--ignore-errors**. It can also write a trip file if you want to do the routing in the simulation. This will however just remove all invalid routes. If you want to fix the network try to find out which edge types should allow busses and provide your own typemap, see https://sumo.dlr.de/docs/SUMO_edge_type_file.html

**Comment by behrisch** [comment]
No further feedback, so seems to be resolved.
