### ISSUE TITLE
keep_right_acceptance, keep_right_time and acceptanceTime

### ISSUE THREAD

**Issue by Domsall** [eclipse/sumo#7321]
As I am working my way through the LC models, I found another behavior, which I don't understand / can't explain.
When simulating a highway scenario, the vehicles stay on the left lane for a long time before changing back to the right lane.
`KEEP_RIGHT_TIME` is 5 and `myKeepRightParam` is 1, so I would understand, that when a car doesn't have any other vehicles in his way, he would change back to the right lane in approx. 5 seconds. If I change lcKeepRight, I could lower that time.

Now when I look into the Code, I think I understand why the vehicles stay on the left lane. At high speeds the `acceptanceTime` of a vehicle becomes pretty high. Example with `vMax=vLimit=vIst`:

```
acceptanceTime = KEEP_RIGHT_ACCEPTANCE * Speed = 7 * 25m/s = 175 (unit?)
fullSpeedGap / vMax                            = 800m / 25m/s = 32s
fullSpeedDrivingSeconds                        = MIN2(acceptanceTime, fullSpeedGap / vMax) = 32s
```

which means that the lane Change is slowed down by 32/175.
Is this the intended behavior? The results of the `acceptanceTime` seem to be pretty high to me. My understanding is that it is some kind of "staying on the left" of fast vehicles.

My idea would be to have vehicles, which change the lane pretty fast when already driving at vMax or at some low speed (like it is now). Something like this could do the trick:

`acceptanceTime = MIN2(KEEP_RIGHT_ACCEPTANCE * vMax * MAX2((double)1, myVehicle.getSpeed()) / myVehicle.getLane()->getSpeedLimit(), MAX2(vMax, KEEP_RIGHT_ACCEPTANCE * vMax * (vMax - myVehicle.getSpeed()) / myVehicle.getLane()->getSpeedLimit()));`

This way the first part until `vMax/2` stays the same. When driving at vMax/2, the vehicles want to accelerate first before checking to move right. Near vMax then the vehicle has no problem moving back to the right. One could also use some other value as upper bound to not lower the `acceptanceTime` that hard again when approaching vMax.

Does this make sense? Am I forgetting some behavior, that is counterproductive to this implementation?

**Comment by namdre** [comment]
The code around KEEP_RIGHT_ACCEPTANCE hasn't seen any tuning since first being written in 2014 (0bc42d3b2221fd59d8ae73c81037aaa548c1d321).

The intended semantic of `acceptanceTime` is the minimum time that a vehicle must be able to continue driving fast on the right lane before accepting a change to the right. The actual time for driving fast on the right lane is `fullSpeedDrivingSeconds`.
If there is a slow truck ahead on the right lane, the decision to change to the right depends on the distance and speed difference to that truck. Slower drivers should accept lower gaps to the truck.

The main of line idea of line `acceptanceTime = KEEP_RIGHT_ACCEPTANCE * vMax * MAX2(1.0, myVehicle.getSpeed()) / myVehicle.getLane()->getSpeedLimit()` was this:

- preference and capability to drive faster increase the time for staying on the left `vmax / myVehicle.getLane()->getSpeedLimit()`. vmax factors in speedFactor as well as the maximum speed of the vehicle
- faster vehicles are more likely to stay on the left (vehicles that are slow to accelerate or that have become slowed down for other reasons move to the right quickly)


The term `myVehicle.getSpeed()` is responsible for the observed issue and should probably be scaled with the average road speed. Scaling it with the speed limit would dominate the effect of vmax on keepRight behavior during jamming otherwise.
On an empty road, the time before changing to the right should be independent of the road speed.

**Comment by Domsall** [comment]
I just took a deeper look into the variables again and recognized, that `KEEP_RIGHT_ACCEPTANCE` used to be 2.0 instead of the 7.0 value it is today. Is there a reason why it was changed? That would also make the vehicles change the lane back to the right earlier.
But as you wrote, it would be great and probably the best practice to incoperate the average road speed. Should the average road speed then also be included in the fullSpeedDrivingSeconds-calculation instead of vMax? The calculation with the Gap to the neighLeader is also done with vMax.

**Comment by namdre** [comment]
current thinking: rather than average road speed, this should use the speed of the direct follower vehicle via #8296 (something I wanted to added for 5+ years)

**Comment by Domsall** [comment]
if I am understanding it correctly, adding a kind of "pushy" term from faster vehicles from behind sounds like a great improvement. Using speedFactor would be an easy way to differentiate between "faster pushy" vehicles and slower ones. I think the average road speed still has an effect in real traffic, as at lower average road speeds (high traffic volume), a vehicle with a lower speedFactor may not make room for a vehicle with a higher speedFactor. The "slower" vehicle may also want to overtake and drive faster than the current speed.
Also one could then investigate the effect of temporarily lowering the speed limit. With the "pushy" improvement, vehicles with lower speedFactors would then start moving to the right to let faster vehicles pass. Without lowering the speed limit, the "slower" vehicles may still stay on the left.

**Comment by namdre** [comment]
changes:
- new vType parameter 'lcKeepRightAcceptanceTime'
- current default -1 keeps legacy behavior (will be changed once if figure out a good value - somewhat tricky since it affects a gazillion test
- when set to something else, acceptanceTime will be set to this value but also scaled down if
  - the follower vehicle is faster than ego
  - the follower vehicle can drive faster than ego

@domsall If you happen to do your own tests with the new parameter, please share your results

**Comment by Domsall** [comment]
I very much like the added follower adaption. I'll do some checks soon, but at this point I don't really know what to check against (real data or what does the change between the old and the new implementation mean, how to "measure" it).
Also one change stood out to me: With the new implementation the calculation of the `acceptanceTime` without a follower looks like this:
`acceptanceTime = myKeepRightAcceptanceTime * roadSpeedFactor * 1.0;`
The `MAX2(1.0, myVehicle.getSpeed())`-part went missing. So the vehicles are now changing the lanes to the right pretty fast independently of the vehicle speed. Thats why I added a term, that slowly decreases when the vehicle comes closer to `vMax`.
Do you know what I mean? Am I maybe missing something?

**Comment by namdre** [comment]
Are you referring to the previous idea  quoted below?

> This way the first part until vMax/2 stays the same. When driving at vMax/2, the vehicles want to accelerate first before checking to move right. Near vMax then the vehicle has no problem moving back to the right. One could also use some other value as upper bound to not lower the acceptanceTime that hard again when approaching vMax.

I don't understand why vehicles should accelerate on the left lane before moving to the right. The main factor should be whether they can drive freely on the right. And without "social" pressure from follower vehicles I don't see why the ego speed should play a role. Your original question points in the same direction:

> KEEP_RIGHT_TIME is 5 and myKeepRightParam is 1, so I would understand, that when a car doesn't have any other vehicles in his way, he would change back to the right lane in approx. 5 seconds. If I change lcKeepRight, I could lower that time.

The intended effect of "staying on the left for fast vehicles" is by my thinking fulfilled by the new lcKeepRightAcceptanceTime parameter: fast vehicles will stay on the left if they cannot drive just as fast on the right lane for long enough (with configurable "long enough").

**Comment by Domsall** [comment]
Thanks for your answer. Ok, I thought this term adds some kind of "Mittelspurfahr"-behavior. As `myKeepRightProbability` is calculated over time, I was guessing, that vehicles would change to the right too early now, although they want to overtake. This may happen even more when the average speed of neihbor lanes are similar, which I thought would go against the idea of "Mittelspurfahrer". But I now think that this behavior is a problem of finding the right parameter values.
The change from the old implementation just seemed a bit intense too me (like e.g. `32/175` from above to `7/7` now), because the KeepRight functionality also incluences the model in many other regions, like you pointed out with the tests.

Nonetheless, I just ran a few tests and found out, that the `follower` input is always the ego vehicle itsself. It works perfectly when the followers are on neighbor lanes, but on the same lane, getRealFollower() outputs the ego vehicle itsself. Could you please check this? I hope the mistake it not on my side and that I am not doing anything wrong.

**Comment by namdre** [comment]
added more tests in 04a2348. Fixed invalid follower vehicle in 3d5d2c8. Thanks for pointing this out.

**Comment by Domsall** [comment]
Thanks for fixing! :)

**Comment by Domsall** [comment]
sorry, its me again :)
During a bit of more testing I found out, that a fast vehicle in the front is actually influenced by a slow vehicle behind, because of the calculation of `factor`:

`const double factor = MAX2(1.0, myVehicle.getSpeed()) / (MAX3(follower.first->getSpeed(), 1.0, myVehicle.getSpeed()) * MAX2(roadSpeedFactor, fRSF));`

In this case, `factor` for an egovehicle in the front is calculated with his own `roadSpeedFactor`. So without a slow follower, the vehicle would stay longer on the left lane. With a slow follower, the attribute `roadSpeedFactor` is cut out. Was this intended?

**Comment by namdre** [comment]
This wasn't intended

**Comment by namdre** [comment]
Since you had no further complaints I assume the current solution is working fine. Please reopen if not.

**Comment by Domsall** [comment]
Its working fine. I still wanted to do a test on a 29km Autobahn map and share the results

**Comment by Domsall** [comment]
[KeepRight_results.zip](https://github.com/eclipse/sumo/files/6310034/KeepRight_results.zip)

Here are my results, I unfortunately couldn't find any real data regarding flows on different lanes (its often accumulated over all lanes). Maybe you have such data to compare against.
