### ISSUE TITLE
why many emergency braking existed with CACC in 3-lane freeway

### ISSUE THREAD

**Issue by Emilyli233** [eclipse/sumo#7322]
I would like to analyze the effect on the maximum flow of adding different market penetration rates of CACC into a 3-lane freeway. The manually drive model that I use is Krauss. The problem is that many emergency braking warning occurs when I run the simulation. How can I solve it?

**Comment by namdre** [comment]
see https://sumo.dlr.de/docs/Car-Following-Models/CACC.html#notes
