### ISSUE TITLE
Question: drawing text into simulation

### ISSUE THREAD

**Issue by urielka** [eclipse/sumo#7323]
When developing an algorithm for traffic control, It is sometimes useful to display inside the simulation information about the state of the algorithm.

It seems that it is possible to add polygons and POIs via TraCI but they only support a bitmap and not text. ( https://sumo.dlr.de/pydoc/traci._poi.html#PoiDomain-setImageFile )

I can render the text into a bitmap but was thinking this might be supported in another way and I couldn't find any in the docs.

**Comment by m-kro** [comment]
There is some support (but for vehicles only atm):
- update a custom key-value pair using [traci.vehicle.setParameter](https://sumo.dlr.de/pydoc/traci._vehicle.html#VehicleDomain-setParameter)
- in the view settings activate "Show vehicle text param" and choose/enter the key of the parameter

**Comment by urielka** [comment]
@m-kro I can try this but it means I need to put a vehicle in the middle of nowhere and make sure it doesn't move - sounds complicated.

I actually managed to do this with the path I suggested but it seems that now sumo-gui leaks memory every time I change the images.

Any other idea?

**Comment by behrisch** [comment]
You can change the type of the POI and let the GUI display the type.

**Comment by urielka** [comment]
@behrisch can you explain this? can I set the gui settings (via viewsettings) to show the type?

**Comment by behrisch** [comment]
Yes, it has an option to show the POI id and one to show the type.

**Comment by urielka** [comment]
@behrisch what is the name of the option? 

So the idea is if I want say 5 lines of text I will put 5 POIs set the text in the type and then enable this GUI option in view settings?

**Comment by behrisch** [comment]
The easiest way is via the GUI in the POI tab, then you save your view settings file and load it when you need it.

**Comment by urielka** [comment]
@namdre thank you for adding this feature!
Is it going to be part of next sumo release?

Any way to show in type for now a multiline?

**Comment by urielka** [comment]
I mean that right now in SUMO 1.6.0 the way I implemented this (instead of using an image that has a memory leak) is using 1 POI for each line.

The problem that I have is that all the text is centered to the POI center instead to it leftmost side, making multiline text quite annoying to read:
![Screenshot from 2020-08-11 21-58-13](https://user-images.githubusercontent.com/30956/89937450-ca097080-dc1d-11ea-98df-7dcc63705a23.png)

Also SUMO uses Roboto font if I read correctly the source which is not a fixed size font which means I can't compensate for this with simple space padding.

**Comment by namdre** [comment]
> @namdre thank you for adding this feature!
> Is it going to be part of next sumo release?

Yes. You can already use this now by downloading the latest dev version from https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_development_version

**Comment by urielka** [comment]
@namdre I was asking when it is going to be part of a stable release? I see that since 1.6.0 there are 1000+ of commits (impressive!) so I am guessing it is a big version, right?

I prefer to work only on stable versions

**Comment by namdre** [comment]
My first "yes" was in answer to your question "Is it going to be part of next sumo release?"
See https://github.com/eclipse/sumo/milestones
Setting param values of POIs is already part of the traci API in 1.6.0
