### ISSUE TITLE
DUARouter - problem with lat/lon

### ISSUE THREAD

**Issue by MelanieWeber** [eclipse/sumo#7325]
I have a big network (waterway/world) and I want to route via DUARouter by lat/lon coordinates, but often it failed and the algorithmn did not match the right edge (sometimes thousand of miles away) .

**Comment by behrisch** [comment]
@MelanieWeber Can you put the net and the offending coordinats in the bug reports folder?

**Comment by MelanieWeber** [comment]
Add test files in the bug reports folder.
(If needed I also can add more test cases which fails)

**Comment by behrisch** [comment]
I could not even load the network in sumo-gui (Could not build projection). Did this happen to you as well?

**Comment by MelanieWeber** [comment]
No, my sumo-gui load the network without problems.

Von: Michael Behrisch [mailto:notifications@github.com]
Gesendet: Freitag, 21. August 2020 09:10
An: eclipse/sumo
Cc: Weber, Melanie; Mention
Betreff: Re: [eclipse/sumo] DUARouter - problem with lat/lon (#7325)


I could not even load the network in sumo-gui (Could not build projection). Did this happen to you as well?

**Comment by namdre** [comment]
@MelanieWeber Has this problem been solved?

**Comment by behrisch** [comment]
Closing for lack of feedback, please reopen if problems persist.
