### ISSUE TITLE
NETEDIT: Mouse click does not select lane in 'Edit Connections' mode

### ISSUE THREAD

**Issue by ZoltanBaksa** [eclipse/sumo#7327]
Hello,
I use the latest dev version v1_6_0+1254-201f316c98 available from July 21 2020 00:14:39 UTC
I'm not able to select any lanes to edit connection options.
In Move or Inspect mode everything works fine
Regards
Zoltan

**Comment by palvarezlopez** [comment]
I'll fix now.

**Comment by palvarezlopez** [comment]
@ZoltanBaksa Fixed. Thanks again for the report.
