### ISSUE TITLE
Add CACC CFModel parameter for overriding CACC control mode

### ISSUE THREAD

**Issue by schwamborn** [eclipse/sumo#7328]

**Comment by schwamborn** [comment]
Now accessible via parameter key `carFollowModel.caccControlModeOverride`.
Awaiting documentation and test case from CERTH.

**Comment by namdre** [comment]
@robertalms could you create a test for this?

**Comment by robertalms** [comment]
Uff, I'm not sure. Maybe :)

**Comment by robertalms** [comment]
Can you create a test out of this?
[complex_cf_model_CACC_fast_approach_standing.zip](https://github.com/eclipse/sumo/files/10814968/complex_cf_model_CACC_fast_approach_standing.zip)

Essentially, the overrideMode is functional as the test shows. The output between default mode 0 and manual mode 3 is in fact significantly different, if you compare the attached plots. Given that the leading, standing vehicle is a CAV, plot 3 looks more like the expected outcome, from my point of view - but this might be a different issue, as you know.

![mode0](https://user-images.githubusercontent.com/53571755/220945309-602b3416-7012-4f0b-8af4-742d3eb48681.png)
![mode3](https://user-images.githubusercontent.com/53571755/220945323-2d3f8eba-5a8f-4607-805a-2d36307d1506.png)

**Comment by robertalms** [comment]
Here is an updated version for the test (no different results, but some files fixed and adapted for testsuite)
[caccCommunicationOverrideMode.zip](https://github.com/eclipse/sumo/files/10815798/caccCommunicationOverrideMode.zip)

**Comment by namdre** [comment]
Thanks!
