### ISSUE TITLE
NETEDIT: Contect menu of connections are not shown properly in TL mode

### ISSUE THREAD

**Issue by ZoltanBaksa** [eclipse/sumo#7331]
Hello,
I use the latest dev version v1_6_0+1254-201f316c98 available from July 21 2020 00:14:39 UTC
When I click with right mouse button above a connection in TL mode, the context menu does not show the TL light options, but shows the context menu of the junction as in inspection mode, The colouring of the connections changes, when I manually change the current phase.
Regards
Zoltan

**Comment by palvarezlopez** [comment]
Thanks for report it
