### ISSUE TITLE
Automatically generated connections cause conflicts and emergency brakings

### ISSUE THREAD

**Issue by ChocolateDave** [eclipse/sumo#7332]
Hello there!
In a signalized intersection demonstrated by the graph below, given two separate left-turning lanes, sumo automatically generated two connections and caused conflicts among vehicles' routes. Hence it continuously reports warnings about emergency braking or collisions. How could I solve this?

![image](https://user-images.githubusercontent.com/45930715/88121842-8eb8ea80-cbf9-11ea-8ce4-06a9922ecafc.png)

**Comment by ZoltanBaksa** [comment]
Hello @ChocolateDave,
It is probably not to good, that the automatically generated connections overlap. As a workaround you can change the connections' shape by selecting 'Set custom shape' in context menu.
Regards
Zoltan

**Comment by ChocolateDave** [comment]
> Hello @ChocolateDave,
> It is probably not to good, that the automatically generated connections overlap. As a workaround you can change the connections' shape by selecting 'Set custom shape' in context menu.
> Regards
> Zoltan

Much appreciation for your reply. The problem is solved. 
However it would be much better if I wouldn't have to enter the coordinate sequence manually. Hope new features could be add to Netedit.😅

**Comment by namdre** [comment]
You can right-click on a connection and select "set custom shape" rather than entering coordinates manually.

**Comment by namdre** [comment]
Regarding the original issue: There are two different modes for computing normal and wide turning shapes. In your example the left turns were computed with different modes and this is a bug.

**Comment by ChocolateDave** [comment]
> You can right-click on a connection and select "set custom shape" rather than entering coordinates manually.

Much appreciated sir, it did help me a lot. :-)
