### ISSUE TITLE
NETEDIT and TraCI lane length difference

### ISSUE THREAD

**Issue by cspatharis** [eclipse/sumo#7333]
Hello,

I have been running into an unusual bug ( ? ) lately. To begin with, I have created a scenario using OSM Web Wizzard so I haven't made any changes to the .xml files myself. In my algorithm, I use the traci.lane.getLength() function in order to retrieve the length of every lane of the scenario. I have noticed that this value differs a lot from the value that I see when I open the scenario in sumo's NETEDIT.

I have also uploaded two images (NETEDIT and xml) which give an example of the problem. Moreover, this happens for all the lanes in the scenario and in some lanes the max speed value also differs. Is this a bug or am I doing something wrong?

Thanks in advance.

![SumoBug1](https://user-images.githubusercontent.com/25799770/88155563-e57dee80-cc10-11ea-95d1-ad5b2e7c3821.png)
![SumoBug2](https://user-images.githubusercontent.com/25799770/88155566-e6af1b80-cc10-11ea-9060-335b78fd3d19.png)

**Comment by palvarezlopez** [comment]
Hi @cspatharis, thanks for report it. Can you check if after a recomputing (F5) edge lenght in NETEDIT is the same as in xml file?

**Comment by cspatharis** [comment]
Hi @palvarezlopez . It worked! Thanks for the tip, I haven't done that before (f5). Should I do this every time I create a scenario with Web Wizzard?

**Comment by palvarezlopez** [comment]
Yes, at least after first load in netedit. During saving recomputing will be automatically do it.
