### ISSUE TITLE
I want to calibrate driver behavior parameters

### ISSUE THREAD

**Issue by SujanSanjula96** [eclipse/sumo#7337]
In Vissim, we have the chance to change nearly 40 driving behavior parameters. I want to know whether Sumo is capable of changing driving behavior parameters below.

1. Average Standstill Distance (This should be the minGap attribute when defining vehicle type)
2. Additive part of safety distance
3. Multiplicative part of safety distance
4. Distance Standing (0 kmph)
5. Distance Driving (50 kmph)

**Comment by m-kro** [comment]
- You already found out for minGap. Have a look at the [parameter table](https://sumo.dlr.de/docs/Definition_of_Vehicles,_Vehicle_Types,_and_Routes.html#car-following_models) in the docs. 
- Assuming you want to use Wiedemann CFM, Sumo now offers the 10-parameter version as "W99". There is also a previous implementation "Wiedemann" with two parameters, but IMHO it is not documented how they relate to the safety distance formula (AX + (BX +CX*z)*sqrt(v)). 
- As for the lateral distance (points 4-5), have a look at the[ sublane model](https://sumo.dlr.de/docs/Simulation/SublaneModel.html). You can set the preferred alignment with respect to the lane and a minimum distance minGapLat.

**Comment by SujanSanjula96** [comment]
Does Wiedemann CFM 74 available in Sumo? Because second and third parameter mentioned here are related to that model.

**Comment by m-kro** [comment]
Yes it is (named "Wiedemann"), but the parameters "security" and "estimation" do not relate 1:1 to the ones you named (BX, CX). Have a look yourself at the relevant code portion (mySecurity and myEstimation are the variables carrying the parameter values):
https://github.com/eclipse/sumo/blob/6f542e5c3a42021e7bc0840e8d68537919b493fd/src/microsim/cfmodels/MSCFModel_Wiedemann.cpp#L52

https://github.com/eclipse/sumo/blob/6f542e5c3a42021e7bc0840e8d68537919b493fd/src/microsim/cfmodels/MSCFModel_Wiedemann.cpp#L118
