### ISSUE TITLE
Errors building sumo on ubuntu 16.04

### ISSUE THREAD

**Issue by ChocolateDave** [eclipse/sumo#7339]
Hello mates!

While I was trying to transfer my project onto an Ubuntu server, I got CMake error building sumo. Here's the retrieved report:

> -- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)
>CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
>  Failed to find XercesC (missing: XercesC_LIBRARY) (found version "3.1.3")
>Call Stack (most recent call first):
>  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
>  /usr/share/cmake-3.5/Modules/FindXercesC.cmake:101 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
>  CMakeLists.txt:268 (find_package)

Would you help me out with this? Much thanks!

**Comment by palvarezlopez** [comment]
@ChocolateDave Hi, try to install xerces-c-dev
