### ISSUE TITLE
Where can I set the distribution function of vehicle arrivals?

### ISSUE THREAD

**Issue by chen-2121** [eclipse/sumo#7340]
I want to know the distribution of Sumo's vehicle arrival obedience and how to modify it to the distribution function I want.THANK YOU VERY MUCH.

**Comment by behrisch** [comment]
Vehicle arrival is a resulting effect from the simulation and cannot modelled in advance. For vehicle departure see here: https://sumo.dlr.de/docs/Simulation/Randomness.html#flows_with_a_random_number_of_vehicles
