### ISSUE TITLE
Taxi module development

### ISSUE THREAD

**Issue by Shiyunyang-seu** [eclipse/sumo#7341]
Hi, I am doing research related taxi , and I have learned the relevant content(https://sumo.dlr.de/docs/Simulation/Taxi.html). But if I need to modify the taxi attributes or test the new strategy and dispatching algorithm, how can I find the relevant descriptive documents? Thanks in advance.

**Comment by namdre** [comment]
There are no further documents at the moment. 
You can find plenty of usage examples at https://github.com/eclipse/sumo/tree/master/tests/sumo/devices/taxi
For extracting tests, see https://sumo.dlr.de/docs/Tutorials.html#using_examples_from_the_test_suite
Taxi attributes are configured just as they are for normal vehicles (https://sumo.dlr.de/docs/Definition_of_Vehicles,_Vehicle_Types,_and_Routes.html#vehicle_types)

Feel free to add more specific questions and I may extend the documentation where needed.
