### ISSUE TITLE
vehicles and pedestrians collision detection

### ISSUE THREAD

**Issue by Drzgy** [eclipse/sumo#7349]
Dear developer:
--collision.action just detects the collisions between vehicles. does Sumo provide a method to detect the collisions between vehicle and pedestrian?

**Comment by behrisch** [comment]
Collisions with vehicles and also among pedestrians are detected as well but no action is taken, sumo just prints a warning.

**Comment by namdre** [comment]
note, that for performance reasons collisions on junctions are only detected when option **--collision.check-junctions** is set
