### ISSUE TITLE
Why can't you draw a picture in Python

### ISSUE THREAD

**Issue by Yuanzhuo-Liu** [eclipse/sumo#7350]
D:\LenovoSoftstore\Soft\Python\python.exe "C:/Program Files (x86)/Eclipse/Sumo/tools/visualization/plot_net_speeds.py"
Error: a network to load must be given.

Process finished with exit code 1

This a error in python,please help me!
Thanks!

**Comment by lbieker** [comment]
Hi, you have to provide as a parameter the name of your sumo network. Here you can find a describtion and an example: https://sumo.dlr.de/docs/Tools/Visualization.html#plot_net_speedspy
