### ISSUE TITLE
switch to PEP440 versioning

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#7356]
At least for the wheels we should apply this https://www.python.org/dev/peps/pep-0440/
The current 1.6.0.335 would become 1.7.0.dev335 which makes it easier for pip installation and makes it also explicitly that it is not a release. It may be worthwhile to discuss this for the complete package as well.

**Comment by namdre** [comment]
internal discussion revealed a preference for 1.6.0.post335 over 1.7.0.dev335

**Comment by behrisch** [comment]
We won't do this for all of SUMO
