### ISSUE TITLE
person getStage(id, -1) crashes sumo - nullptr

### ISSUE THREAD

**Issue by atellyro** [eclipse/sumo#7357]
Same input files as issue #7336:
Now it crashes earlier

Simulation version v1_6_0+1371-fa1f1ed7e8 started with time: 0.00
==13222== Invalid read of size 8
==13222==    at 0xE5CFB1: MSStageDriving::getEdgePos(long long) const (MSStageDriving.cpp:102)
==13222==    by 0xE53714: MSPerson::MSPersonStage_Walking::proceed(MSNet*, MSTransportable*, long long, MSStage*) (MSPerson.cpp:91)
==13222==    by 0xE61F57: MSTransportable::proceed(MSNet*, long long) (MSTransportable.cpp:102)
==13222==    by 0xD4822F: MSDevice_Transportable::notifyMove(SUMOTrafficObject&, double, double, double) (MSDevice_Transportable.cpp:116)
==13222==    by 0xA6F735: MSVehicle::workOnMoveReminders(double, double, double) (MSVehicle.cpp:1218)
==13222==    by 0xA7E9A3: MSVehicle::executeMove() (MSVehicle.cpp:4204)
==13222==    by 0xB26551: MSLane::executeMovements(long long) (MSLane.cpp:1755)
==13222==    by 0xB03D68: MSEdgeControl::executeMovements(long long) (MSEdgeControl.cpp:187)
==13222==    by 0x9DBB53: MSNet::simulationStep() (MSNet.cpp:579)
==13222==    by 0x9D908A: MSNet::simulate(long long, long long) (MSNet.cpp:355)
==13222==    by 0x9D629B: main (sumo_main.cpp:107)
==13222==  Address 0x0 is not stack'd, malloc'd or (recently) free'd

**Comment by namdre** [comment]
regression caused by fb6fe47dd9ce7303594c7c822a1962fd25b59d60 not caught by existing tests.
