### ISSUE TITLE
validate files loaded with --route-files by default

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#7358]
currently, they are only validated if the schema location is set. For route files, the schema location is known and people may not have set it when writing files from scratch (where validation would be most needed).

**Comment by behrisch** [comment]
@namdre Do we need another command line option here like **--xml-validation.net**? Or do we just add another option to the standard **--xml-validation** like "routes"

**Comment by namdre** [comment]
**--xml.validation.routes** seems more consistent to me. This way the same arguments apply to all --xml.validation... options
(no weird things like **--xml.validation.net autovalidateRoutes**)

**Comment by behrisch** [comment]
Some further ideas / questions here:

- We preparse now only selected grammars (net, addtional, routes). Should we do this for all?
- If we do it for all files we could even disable external lookup
  - Pro: always be sure that people use the schema which fits their SUMO version
  - Pro: less code / easier lookup procedure because we could remove our entity resolver
  - Pro: we could make "always" the default for all file types
  - Con: less flexibility when adding a new filetype or parsing other people's XML
- Should **--xml-validation never** imply **--xml-validation.routes never** if no explicit value for the latter is set?
- Should we disable **--xml-validation.routes** and **--xml-validation.net** for applications which do not load routes (or a net)?

@namdre Input is welcome :-)

**Comment by namdre** [comment]
some thoughts
- **--xml-validation never** should override all defaults but an explicit option of  --xml-validation.routes should override this
- the **.routes** and **.net** options should not exist for applications that don't use those file types
- regarding "preparse all grammars", "lack of flexibililty". This would be something like a vissim xml schema, correct? Did we ever have an external file that used a schema reference?  Can you elaborate on a scenario where we add a new file type and the missing resolver affects us?

**Comment by behrisch** [comment]
>     * regarding "preparse all grammars", "lack of flexibililty". This would be something like a vissim xml schema, correct? Did we ever have an external file that used a schema reference?  Can you elaborate on a scenario where we add a new file type and the missing resolver affects us?

Yes, basically for matsim and vissim and similar imports validation would not happen if "always" is set unless we duplicate their schema files in our repo (which does not look like a great idea to me).

**Comment by namdre** [comment]
@lcodeca brought up the point of non-standard root element names. I think we should circumvent validation if the root element of a route-file is named differently and print a warning to ensure backward compatibility.

**Comment by behrisch** [comment]
I am not convinced. Either we enforce the schema then it holds for the root element as well or we don't. The user can set **--xml-validation.routes auto** to get the old behavior back. We could do this in a two step procedure though. In the next release we just warn about the wrong root element and we enable "always" as the new default in the release after that.

**Comment by namdre** [comment]
Yes. I think warning about this first would be better. I would not wish to break things that are working fine right now.

The big change is not schema validation consistency but rather that until now only files written by a sumo tool were validated (at least I don't think that anybody writes a schema reference by hand).
Even though people should be able to learn about the backward compatibility option from the changelog it will inevitably happen that people who start with SUMO pick up the latest release, try to load files from their colleagues and run into an error that they cannot easily interpret.
Also, we previously communicated that the root element is arbitrary and people who wrote their files themselves had no reason to believe otherwise.

We need at least a new FAQ entry for this.

**Comment by behrisch** [comment]
I am still in favor of switching to "always" here but not on the day before the release :-)

**Comment by namdre** [comment]
I've been thinking about this some more and I have a strong gut feeling against breaking things for users which are currently working. There are many harmless cases such as 'loading an additional file with vTypes using the route-files option' that would suddenly break.

Also I don't think there is a sufficient gain in clarity,usability or expected reduction in user questions to offset the negative of breaking compatibility.

I'm fine with always warning about unexpected root element names.

**Comment by behrisch** [comment]
Since you answer most of the questions it's your vote that counts.
