### ISSUE TITLE
when adding stops to a trip, the route does not change

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#7364]
also, the trip that was selected in the drop down does not appear to gain the stops as child element

**Comment by palvarezlopez** [comment]
@namdre I'm working in ticket #6903

**Comment by palvarezlopez** [comment]
@namdre Question: What has more priority? a Stop or a "via" edge?

**Comment by namdre** [comment]
when both stops and vias are given, sumo only uses the vias for routing and then expects the stops to be on the found route.
However, stops and vias should generally not be used at the same time #2275
