### ISSUE TITLE
Libsumo on OSX causes segfault error

### ISSUE THREAD

**Issue by eugenevinitsky** [eclipse/sumo#7368]
Trying to build / use libsumo on macOS Catalina Version 10.15.3. Using latest SUMO build on github (9a829a8).

Build completes successfully, and other functionality seems to be working fine as in the testlibsumo passes; however, importing libsumo fails with segmentation fault. This happens when the libsumo.py attempts to import _libsumo. 

Thanks!

**Comment by behrisch** [comment]
Which python version do you use? Please also make sure that if you have multiple versions installed that you use the same version sumo is picking up whe doing cmake.

**Comment by eugenevinitsky** [comment]
3.7.3, do you know how it detects the python version? I'm using conda as the installation.

**Comment by behrisch** [comment]
SUMO uses the CMake FindPython mechanism. It should report in the CMake output which version it found, like this.
```
-- Found PythonInterp: /usr/bin/python (found version "2.7.17") 
-- Found Python: /usr/bin/python
```
conda might be difficult because they tend to bring their own libraries and not use the system ones as far as I know but my MacOS experience is very limited. @schwamborn @angelobanse ?

**Comment by schwamborn** [comment]
Even though Apple announced to not do so with future macOS releases, macOS Catalina should still ship with a system version of python3. This means that conda (probably) installs its own version in addition. Therefore, I can only second the suggestion by @behrisch to make sure the correct version is used. Unfortunately, I don't have a Catalina system at hand to verify myself.

**Comment by eugenevinitsky** [comment]
This is still super helpful; I'll dig into which python is being used and see if that resolves things. Thank you!

**Comment by pikeas** [comment]
@eugenevinitsky Were you able to get libsumo working on a Mac?

**Comment by RobertHilbrich** [comment]
@pikeas please have a look at the other issue libsumo segfault issue (#6804). I tried to put an explanation and some guidance [here](https://github.com/eclipse/sumo/issues/6804#issuecomment-723792664).

**Comment by pikeas** [comment]
In CMakeCache.txt, I see a few references to library paths that may be relevant:

```
PYTHON_INCLUDE_DIR:PATH=/usr/local/Frameworks/Python.framework/Versions/3.8/include/python3.8
PYTHON_LIBRARY:FILEPATH=/usr/local/Frameworks/Python.framework/Versions/3.8/lib/libpython3.8.dylib
FIND_PACKAGE_MESSAGE_DETAILS_PythonLibs:INTERNAL=[/usr/local/Frameworks/Python.framework/Versions/3.8/lib/libpython3.8.dylib][/usr/local/Frameworks/Python.framework/Versions/3.8/include/python3.8][v3.8.6()]
```

Full file: https://gist.github.com/pikeas/ce0e5167a863e98f217f11c404351121
