### ISSUE TITLE
Is it possible to use TraCI in a notebook/Google Colab?

### ISSUE THREAD

**Issue by felipec23** [eclipse/sumo#7369]
Hi! Is this possible? Google Colab is basically a linux virtual machine, however, I'm having problems because, since it's a notebook, no CMD is available. Any idea of how to implement it?

What I do can run in Google Colab is a normal simulation, just adding an ! before:

`!sumo -c 'configuration_file.sumocfg'
`

However, when running traci.simulationStep(), I get the following error:

"AttributeError: 'Connection' object has no attribute '_socket'"

 Thanks!

**Comment by angelobanse** [comment]
> What I do can run in Google Colab is a normal simulation, just adding an ! before:
> `!sumo -c 'configuration_file.sumocfg'`

How did you installed SUMO in Google Colab? Did you do it using `!sudo apt-get install sumo`?

**Comment by felipec23** [comment]
Thanks for answering!
Yes, more specifically:

`!sudo apt-get install sumo sumo-tools sumo-doc`

**Comment by angelobanse** [comment]
So you have SUMO Version 0.32.0? You can check it with `!sumo`. 

Is everything else SUMO-related (except TraCI) working fine?

**Comment by felipec23** [comment]
Correct, that's the version installed. And yes, everything else seems to be fine.

**Comment by behrisch** [comment]
Can you run one of the tutorials?

**Comment by abderraouf2che** [comment]
Have you been able to establish connection using traci?

**Comment by felipec23** [comment]
Hi, well, I only needed Traci to change the traffic lights durations among many iterations. I got to do it but without using Traci. It's somehow easy because SUMO is mainly based on XML files, so I parsed the net file (read it) and modified through Python. For running the simulation, I found using the module 'subprocress' is way faster than putting the !

**Comment by behrisch** [comment]
Please don't modify the network directly, see https://sumo.dlr.de/docs/FAQ.html#i_have_changed_my_network_and_now_sumo_does_not_load_it

**Comment by felipec23** [comment]
Thanks, the thing is that it's not plausible for me to manually change 133 phase durations among +2000 iterations (in Google Colab). Locally I'm using Traci as the documentation recommends!

**Comment by behrisch** [comment]
It is probably not critical if you just change durations, I just wanted to avoid that this stands here as a rule for others to follow. You could still make a round trip writing plain XML tls output and rebuilding the network using netconvert. But if it works for you it is just fine, just wanted to mention the dragons around the corner.

**Comment by namdre** [comment]
The recommended way would be to put the signal plans with modified duration in their own file and load this into the simulation with option **--additional-files**. This way you don't have to touch the '.net.xml'
