### ISSUE TITLE
invalid taxi stop sequence when using 'routeExtension'

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#7373]
If request A wants to travel to edge E position 50 and request wants to be picked up at edge E position 10, to stop sequence should be 'A B A B' but the dispatcher sends 'A A B B' causing a superfluous loop.

**Comment by behrisch** [comment]
tests are still missing

**Comment by namdre** [comment]
According to devices/taxi/2taxis_10persons/routeExtension it still doesn't work. See vehicle trip_0 at time 60
Person 1 is picked up after person 3 is dropped of even though it would save a large detour to do it in reverse.
