### ISSUE TITLE
colored flash when placing junction in edge mode

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#7378]

**Comment by palvarezlopez** [comment]
@namdre I don't understad what do you mean with "colored flash"

**Comment by namdre** [comment]
I've only tested on linux. Whenever I click in edge mode, the whole viewnet-canvas is filled with the color of the last placed junction (green or red) before going back to the updated network view.

To be precise. The very first click is normal, afterwards every further click causes a flash.

**Comment by namdre** [comment]
A typical cause for this would be an unmatched pair of pushMatrix/popMatrix

**Comment by palvarezlopez** [comment]
Now I understand it
