### ISSUE TITLE
how to get instantaneous information of vehicles from instantaneous induction loop detectors

### ISSUE THREAD

**Issue by muruimarie** [eclipse/sumo#7385]
We can use the python method getVehicleData in traCI to get the passed vehicles' data, however, the detector will miss some vehicle occasionally.
In order to get all vehicles' information, I want to use the instantaneous induction loop, however, there are no such python method in traCI.
So how can I get the instantaneous information of vehicles' from instantaneous induction loop detectors, not from the output file, just the instantaneous ones second by second?

**Comment by namdre** [comment]
getVehicleData should not miss vehicles and therefore provide the role of an instantInductionLoop. Hence there is not separate python model for instantInductLoop. Can you provide a small example case where this happens?

**Comment by muruimarie** [comment]
I put detectors separately on both side of the road. There are vehicles which can be detected on the beginning side, but can not be detected on the ending side. Then I tried the instantaneous loop detectors, which can detect all vehicles passed. But I can only get the information of vehicles from the corresponding output file.

**Comment by namdre** [comment]
Can you provide your scenario? (attached in a zip file)

**Comment by muruimarie** [comment]
OK. Please wait for about 15 mins

**Comment by muruimarie** [comment]
[traci_tls-lefthand-1396313437-1396211426-detector trial.zip](https://github.com/eclipse/sumo/files/5060956/traci_tls-lefthand-1396313437-1396211426-detector.trial.zip)
For example, the vehicle 'wtoe_49' can be detected by the instantaneous induction loop 'i0', which can be found from the output file 'cross.detout2.xml', however, it is missed by the induction loop 'wlea0'.

**Comment by muruimarie** [comment]
> Can you provide your scenario? (attached in a zip file)

hello, can you see the zip file?

**Comment by namdre** [comment]
yes

**Comment by muruimarie** [comment]
> yes

Did you find the same problem? or if you have any problem or question about the scenario, please tell me.

**Comment by namdre** [comment]
The issue you encounter is due to a bug in version 1.4.0. I checked with version 1.6.0 and no vehicles are being missed.

**Comment by namdre** [comment]
@behrisch Do you have an idea which ticket this could have been? I could not find one in the change log.

**Comment by muruimarie** [comment]
> The issue you encounter is due to a bug in version 1.4.0. I checked with version 1.6.0 and no vehicles are being missed.

I downloaded and tried version1.6.0, and the problem is still there.

**Comment by muruimarie** [comment]
![WeChat Photo Editor_20200813163632](https://user-images.githubusercontent.com/57517778/90107154-61d49f00-dd83-11ea-8afd-e9221d5639f2.jpg)
See the 'wtoe_49' and 'wtos_198' in the printed screen, it means that the detector did not sense the two's leave.

**Comment by muruimarie** [comment]
however, we can find the two leave normally from the output file 'cross.detout2.xml'

**Comment by muruimarie** [comment]
> The issue you encounter is due to a bug in version 1.4.0. I checked with version 1.6.0 and no vehicles are being missed.

My apologies, I found the 'wtoe_49' out in the cmd window. I will check the coding for runner.py, maybe there are some bug in it.

**Comment by namdre** [comment]
The problem is not with your runner (or if it is, this is not the only problem). I really did observe vehicles being missed in version 1.4.0. This happens when a vehicle changes lanes while on the detector.

**Comment by muruimarie** [comment]
> The problem is not with your runner (or if it is, this is not the only problem). I really did observe vehicles being missed in version 1.4.0. This happens when a vehicle changes lanes while on the detector.

Many thanks for your kindly help and support! Yes, some vehicles did be missed in version 1.4.0. And the problem did be solved in version 1.6.0. I meant that I found the 'wtoe_49' out in the cmd window by the running result from version 1.6.0. So the new version works.
The following problem which I thought it is still the same problem of version 1.4.0 (actually it is not), is caused by the bug of runner.py, and now it is also solved.
Thanks again!
