### ISSUE TITLE
Output of xml2csv depends on the first row of input xml file

### ISSUE THREAD

**Issue by vishalmhjn** [eclipse/sumo#7387]
I tried to convert a network to a plain file, using:

`netconvert --sumo-net-file network.net.xml --plain-output-prefix abc --proj.plain-geo`

Then I tried to convert the generated ABC.edg.xml to CSV using:

`python sumo/tools/xml/xml2csv.py ABC.edg.xml`

The columns in output CSV file depend on the first row in the input XML file, and the **_edge_shape_** column was absent in generated CSV. When I swapped the rows in XML so that the first row had an **_edge_shape_** property, then the corresponding column in output CSV was present.

**Comment by vishalmhjn** [comment]
I should have known this can be resolved by using the schema ```-x``` option, so should be ok to close this issue.

**Comment by namdre** [comment]
Might be good to describe this in the documentation
