### ISSUE TITLE
unable to load a timing plan/ confusing message pops up when loading a timing plan in netedit

### ISSUE THREAD

**Issue by yunpangfloetteroed** [eclipse/sumo#7388]
- When loading a timing plan, the additional_file.xsd must exist. Otherweise, the respective error shows up (see the part circled in red in the attached picture "errors.jpg"). Users who only downloads the bin directory will not have xsd-files.

- It seems that a message "No programs found for ....." pops up all the times when loading a timing plan, although the timing plan can be loaded. (see the part marked in blue in the attached picture "errors.jpg") This message results in the confusion that users are not sure if the loading action is successful. 

-The network file and a example timing plan file are attached as well.
[files.zip](https://github.com/eclipse/sumo/files/5057168/files.zip)

**Comment by behrisch** [comment]
Concerning the xsd, this might be an effect of our website migration. We redirect everything to https, so xerces tries to load https://sumo.dlr.de/xsd/additional_file.xsd instead of http://sumo.dlr.de/xsd/additional_file.xsd and fails because it has no https support built in. I am surprised this did not show up earlier. But you should still be able to set SUMO_HOME to a directory containing the data/xsd folder. Though shall not only download the bin-dir ;-).

**Comment by yunpangfloetteroed** [comment]
Ah, that's the reason.. Thanks! I think, most of users have downloaded the sumo dirs more than the bin dir and set SUMO_HOME. Perhaps that's the reason why this probelm does not appear eariler. :)

**Comment by behrisch** [comment]
I just double checked the web server and cannot find a place where we do a redirect from http to https. @angelobanse Ideas?

**Comment by angelobanse** [comment]
I also can't see a place where we specify that redirect ourselves. I would guess it's probably an inherited setting from **dlr.de** (where they configured that to work on each subdomain??).

Maybe we should disable SSL in the Apache2 config file (`SSLEngine off`) and specify the https redirects manually in the `.htaccess` file (except for the `/xsd` directory where we need to use http).

**Comment by behrisch** [comment]
I think it is not the server, it is the client. I just tried it on the linux server and it works. Maybe our DLR machines are now configured to use only https?

**Comment by behrisch** [comment]
It seems that Xerces-c supports https only on Linux.

**Comment by angelobanse** [comment]
\+ we could make **sumo.dlr.de** accessible via both HTTPS *and* HTTP (it might be useful).

**Comment by behrisch** [comment]
I am a big fan of using https only. The best solution in my opinion would be to enable xerces-c to do this (especially since it already works on Linux).

**Comment by behrisch** [comment]
@palvarezlopez There seems to be a working build of libxerces-c with https support here: https://cppget.org/?builds=libxerces-c
It introduces dependencies to libcurl and libssl but I think it is worth it. Can you maybe copy their recipe?

**Comment by palvarezlopez** [comment]
Fixed in #7517
