### ISSUE TITLE
setting the  environment variable to my SUMO 

### ISSUE THREAD

**Issue by wissamnhiri3** [eclipse/sumo#7389]
hey everyone, i just started with sumo so i set the SOMO_HOME , the PATH and SUMO_LIBRARIES and i wanna know if my sumo

 environment variable is set correctly, what can i do ? 

if someone can help that would be much apriciated .

**Comment by namdre** [comment]
see https://sumo.dlr.de/docs/Basics/Basic_Computer_Skills.html
