### ISSUE TITLE
Restrict SSM device locally

### ISSUE THREAD

**Issue by m-kro** [eclipse/sumo#7398]
My simulations feature a lot of vehicles equipped with SSM devices in order to get big samples of SSM measures. At the same time, there might be 50+ of them moving through the network. I don't mind so much that this slows down the simulation, but sometimes the simulation runs out of memory. 

I think a valid option would be to operate the device only on certain edges, limiting the output and the search process to places of interest. As far as I am aware, currently SSM devices cannot be created/removed during the simulation and cannot be restricted to work e.g. on a specific junction.

Removing the device would simply cut all active conflict data like when the vehicle leaves the network. **Adding an edge filter to the device would allow in theory to follow already active conflicts until they end while no new conflicts are picked up**. Firstly, I'd make an edge filter like from the FCD device working.

 @behrisch @namdre : Could you give some advice on how this might be implemented?

**Comment by namdre** [comment]
- add a new option device.ssm.filter-edges.input-file
- copy and adapt code from MSDevice_FCD::initEdgeFilter
- in MSDevice_SSM::update(), skip findSurroundingVehicles if there are filter edges and the ego vehicle is not on any of them

**Comment by rummel123** [comment]
@m-kro does your commit solves the problem? I am also interested in restricting the SSM device to an area/specific edges.

**Comment by m-kro** [comment]
@rummel123 Yes it does the trick, defining a set of edges and junctions where the SSM device should operate. I had more important problems to solve in the last days, thus didn't have time to really test it and issue a pull request.

**Comment by rummel123** [comment]
@m-kro I'm still insterested in your solution. Are you still busy? If needed, I can help to test the code.

**Comment by m-kro** [comment]
@rummel123 I have uploaded the last state of my solution in my fork (see branch ssmSpatialFilter). Short instructions after build:
Use global option --device.ssm.filter-edges.input-file [FILE] where [FILE] is a selection filter like for [FCD filter](https://sumo.dlr.de/docs/Simulation/Output/FCDOutput.html#restricting_the_locations), except that it considers edge and junction elements. It crashes in Debug mode due to some assertions. 

I won't have much time to help within the next days, but will keep an eye on it from time to time to make this into a pull request.

**Comment by rummel123** [comment]
I adjusted the warnings and added some tests. Seems to work fine for me.

**Comment by rummel123** [comment]
see:
[inital commit by m-kro](https://github.com/eclipse/sumo/commit/0ed2829518a40f7a4ba50f5e823280c416436c2e)
[adjusted warnings](https://github.com/eclipse/sumo/commit/a1d62f08a2c6aa9f4c76e2de65a0c1ed53b74db2)
[tests](https://github.com/eclipse/sumo/commit/c2c6d4657ff91a9d349e9480cdfbc4934eb1fa3e)
