### ISSUE TITLE
How to keep the vehicle driving in a circle?

### ISSUE THREAD

**Issue by Mzy526** [eclipse/sumo#7408]
`<route id="route3" edges="E3   -E2   gneE0   gneE1   gneE2   E2   -E3   gneE3   gneE4   gneE5   E3 "/>` this is my vehicle route.When the vehicle completes a lap, It disappears from side E3, but I don’t want this. I want the vehicle to keep circulating on this section of the road, and it looks like it’s been driving in a circle.what should I do? thanks.

**Comment by namdre** [comment]
https://sumo.dlr.de/docs/FAQ.html#how_do_i_maintain_a_constant_number_of_vehicles_in_the_net
