### ISSUE TITLE
Dispatching for taxi: circulate

### ISSUE THREAD

**Issue by Shiyunyang-seu** [eclipse/sumo#7413]
Hi, when I use the taxi module, after a taxi receives a passenger and sends the passenger to his destination, it will stop at the passenger's destination. How to make the taxi not stop and continue to drive on the road so as to continue to receive orders. (e.g. Driving on the road near the passenger's destination randomly)
Thanks in advance.

**Comment by namdre** [comment]
random circling is not yet implemented (though planned for the future). Right now the taxi will stop 60s for discharging the passenger, payment etc and then accept the next order (or wait for the next order).

**Comment by namdre** [comment]
The random circling isn't totally random (i.e. taxis will try to optimize their chance of finding a random customer) so some sort of model is needed that prefers "busy" edges but also avoids driving in small circles.

**Comment by Shiyunyang-seu** [comment]
Thank you for your answer, I am looking forward to the improvement of this module. 
On the other hand, I want to solve this problem by changing the vehicle state through Traci, but I find that I can't return the order and vehicle state by traci.person.getTaxiReservations() and traci.vehicle.getTaxiFleet(), the error will be 'VehicleDomain' object has no attribute 'getTaxiFleet'. The same question occurs when I use traci.person.getEdge (), but traci.person.getPosition()  can return the value.
![traci](https://user-images.githubusercontent.com/55737075/90375335-682a8a00-e0a7-11ea-8608-468c996e2cf2.png)

**Comment by namdre** [comment]
The new traci taxi commands are only available in the latest development version (https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_development_version)
