### ISSUE TITLE
implausibleRoute.py file not found error "routes.rou.xml.rerouted.rou.alt.xml"

### ISSUE THREAD

**Issue by khibuya** [eclipse/sumo#7414]
I use "flowrouter.py" to generate the traffic route and flow from the observed count data. 
Then traffic jam is occured due to implausible route, such as U-Turn, so I tried remove these route to use "implausibleRoute.py". 

I followed the following procedure
・python flowrouter.py -n <net.xml> -d~ -f~ -o <route.xml> -e~
・python implausibleRoute.py  <net.xml> <route.xml>

The following error masage are occured, while using implausibleRoute.py.
===============
line 144, in main
  for vehicle in parse(duarouterAltOutput, 'vehicle'): 
line 253, in parse
  for _, parsenode in ET.iterparse(_open(xmlfile, None)):
line 331, in _open
  return open(xmlfile) if encoding is None else io.open(xmlfile, encoding=encoding)
FileNotFoundError No such file or directory "route.xml.rerouted.rou.alt.xml"
================

Similar error is reported, 
https://sumo.dlr.de/daily/extra_gcc4_64report/tools/test_default_24Dec2017.html

How can I fix my file, or How to use implausibleRoute.py correctly?
I use sumo-win64-1.6. 
Thanks.

**Comment by namdre** [comment]
sounds like you simply passed the wrong file name. When in doubt, try giving an absolute rather than a relative path to the route file.
