### ISSUE TITLE
Traci can not get the -busstop.py and _chargingstation.py

### ISSUE THREAD

**Issue by zhaotuo0815** [eclipse/sumo#7415]
hello，I faced some troubles，when I download the sumo from the official website，the tools/traci folder does not have the _busstop.py and _chargingstation.py,but there are on Github /tools/traci.After I replace these py files,Traci can still get the previous parameters by itself.So how can I access these py files through Traci
![github](https://user-images.githubusercontent.com/59630993/90473249-09234e80-e155-11ea-82be-97697bf27ff8.jpg)
![traci](https://user-images.githubusercontent.com/59630993/90473255-0aed1200-e155-11ea-885b-cdce95b61fae.png)
![version](https://user-images.githubusercontent.com/59630993/90473257-0c1e3f00-e155-11ea-83e7-099fa28b4566.png)
![weibsite](https://user-images.githubusercontent.com/59630993/90473258-0c1e3f00-e155-11ea-9105-fa332f089b9c.jpg)

**Comment by namdre** [comment]
the new domains are not available in 1.6.0. Use the latest development version or wait for 1.7.0
https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_development_version

**Comment by zhaotuo0815** [comment]
> the new domains are not available in 1.6.0. Use the latest development version or wait for 1.7.0
> https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_development_version

thanks a lot
