### ISSUE TITLE
deadlock on junction

### ISSUE THREAD

**Issue by shlbuya** [eclipse/sumo#7424]
Hi, I encountred deadlock on junction.

Mr. namdre sayed deadlock no longer happens after fixing [#6649](url)
https://github.com/eclipse/sumo/issues/6636

How can I do to resolve this problem??

![deadlock](https://user-images.githubusercontent.com/66761823/90579917-6923fe80-e202-11ea-8608-7b08f63f15e6.PNG)

**Comment by shlbuya** [comment]
I use "--tls.ignore-internal-junction-jam" when I generate network, 
following previous resolutoin [#6269](url)
but deadlock remains.

**Comment by namdre** [comment]
The deadlock is caused by the structure of the junction itself. You could possibly resolve it with **--ignore-junction-blocker TIMEOUT** but it would be preferable to merge this cluster of junctions into a single junction: https://sumo.dlr.de/docs/Networks/PlainXML.html#joining_nodes

**Comment by shlbuya** [comment]
Thank you very much, it solved.
