### ISSUE TITLE
Traci for Taxi service

### ISSUE THREAD

**Issue by Shiyunyang-seu** [eclipse/sumo#7426]
Hi,  I encountered two problems when using Traci for Taxi experiments:
To facilitate observation, I defined two taxis and one passenger in the road network.
1. When using traci.person.getTaxiReservations(1), there will be a Error: Answered with error to command 0xae: device.taxi.dispatch-algorithm 'traci' has not been loaded.
2. (traci.vehicle.getTaxiFleet(0),traci.vehicle.getTaxiFleet(1),traci.vehicle.getTaxiFleet(2)) are used to return the state of the taxi, at time step 28, v1 picked up the passenger, but the return information is as follows:
Empty_TAXI: ('v0',) Picked_up_TAXI: ('v0', 'v1') Occupied_TAXI: ('v0',) Simulation time：26.0
Empty_TAXI: ('v0',) Picked_up_TAXI: ('v0', 'v1') Occupied_TAXI: ('v0',) Simulation time：27.0
Empty_TAXI: ('v0',) Picked_up_TAXI: ('v0',) Occupied_TAXI: ('v0', 'v1') Simulation time：28.0
Empty_TAXI: ('v0',) Picked_up_TAXI: ('v0',) Occupied_TAXI: ('v0', 'v1') Simulation time：29.0
which does not match the description of this https://sumo.dlr.de/daily/pydoc/traci._vehicle.html#VehicleDomain-getTaxiFleet.
Thanks in advance.

**Comment by namdre** [comment]
1) you must set option  **--device.taxi.dispatch-algorithm traci** to use getTaxiReservations and dispatch
2) there was an issue that has been fixed in [e4fa5c7bfc14ec160f4f61ecad06938c49c3a6c6]. see also the updated description at https://sumo.dlr.de/docs/TraCI/Vehicle_Value_Retrieval.html#command_0xa4_get_vehicle_variable

**Comment by ivankapovich** [comment]
Hi Everyone!
I hope this message find you well! I would like to ask how can I "set the option --device.taxi.dispatch-algorithm traci to use getTaxiReservations and dispatch". Should I make this in the demand file?? Thank you very much!
