### ISSUE TITLE
Problems in implementing stochastic car following model

### ISSUE THREAD

**Issue by miracelplus** [eclipse/sumo#7430]
Hello,

I am developing a new data-driven stochastic car following model based on the default IDM model. However, when I am testing the freespeed model (on a single vehicle), I found that at each time step, the simulator called the freespeed function for 3 times and pick the smallest acceleration value, which makes the model performs bad. (usually negative acceleration). I wonder if there are some documents to illustrate this phenomenon?

Thanks

**Comment by namdre** [comment]
During movement planning the vehicle looks multiple edges into the future and calls freeSpeed to adapt to the speed limit on each edge. To avoid a stochastic bias, you could cache the results for each speed limit within VehicleVariables and thus avoid sampling multiple times in one simulation step.
