### ISSUE TITLE
sumo vehicle collided when my vehicle cut in its lane

### ISSUE THREAD

**Issue by lidongke** [eclipse/sumo#7434]
It happens when the vehicle is suddenly inserted into the lane.
my vehicle is "player_30000".
collision vehicle is "vv003".
[Screencast 2020-08-20 19:47:14.mp4.tar.gz](https://github.com/eclipse/sumo/files/5102800/Screencast.2020-08-20.19.47.14.mp4.tar.gz)
You can see that the "vv003" performs the braking action first and then performs acceleration action. Can you tell me the reason about this?Thanks!
@ketan @atoulme

**Comment by namdre** [comment]
Most likely this is due to a bug which has been fixed in the meantime. Please upgrade to a newer sumo version. The latest release is 1.16.0 but you could also try the latest development version because it includes further fixes to some traci commands.
