### ISSUE TITLE
In the sublane model, can the continuous lane change of vehicle produce a yaw angle?

### ISSUE THREAD

**Issue by Jianhua-Jiang** [eclipse/sumo#7437]
When changing lanes instantly, the vehicle will not produce a yaw angle. Therefore, I would like to know, after switching to the sub-lane model, the vehicle can achieve continuous lane change and the yaw angle will also exist? Or is the front of the car always forward?

**Comment by namdre** [comment]
When using the sublane model, a yaw-angle will be computed. However, the primary action of the sublane model is a lateral change and the yaw angle is computed based on speed and lateral change (not the other way around).

**Comment by Jianhua-Jiang** [comment]
> When using the sublane model, a yaw-angle will be computed. However, the primary action of the sublane model is a lateral change and the yaw angle is computed based on speed and lateral change (not the other way around).

After the vehicle calculates the yaw angle, can it be set and visualized? Can the yaw angle be calculated without using the sub-lane model? Such as passing speed and distance from centerline? THANKS!!!!!!!!

**Comment by namdre** [comment]
you set set a custom yaw angle using traci.moveToXY with the optional angle argument.
