### ISSUE TITLE
Brew installation broken (gdal, proj)

### ISSUE THREAD

**Issue by eugenevinitsky** [eclipse/sumo#7439]
Dear all,

If you follow the mac installation instructions, it suggests that you brew install both gdal and libproj. However, the default brew will install libgdal 27.0 and libproj 19.0. Both of these are seemingly not compatible with sumo which expects libproj.15.dylib and libgdal.20.dylib.

Do you have any thoughts on an alternate installation mechanism that might avoid these issues? For example, packaging SUMO with the desired versions might work.

**Comment by RobertHilbrich** [comment]
Please note, that the link you provided, is for setting up the build enviromment for SUMO on macOS, i.e., to build SUMO from its sources. (It says at the top: "If you don't want to extend SUMO, but just use it, you may want to simply follow the installation instructions for macOS instead.").

If you just want to install SUMO for using it, please follow the [link](https://sumo.dlr.de/docs/Installing.html#macos) to the instructions for the macOS installation.

**Comment by eugenevinitsky** [comment]
Ah yes, I don't want to extend it but we are trying to extend Flow (https://github.com/flow-project/flow) to get some speedups from libsumo. This is why we're running into issues with Brew installs.

The help is very appreciated.
