### ISSUE TITLE
Does the method of pedestrian insertion and vehicle insertion need to be distinguished?

### ISSUE THREAD

**Issue by Jianhua-Jiang** [eclipse/sumo#7457]
I am using python and sumo for co-simulation. After arranging the initial traffic flow through sumo, I need to read the initial traffic flow information in sumo, and then insert it in python, may I ask, Does the method of pedestrian insertion and vehicle insertion need to be distinguished? 
I use traci.vehicle.addLency, traci.vehicle.setRoute and traci.vehicle.moveToXY to realize the insertion of vehicles. Is the insertion of pedestrians in accordance with these three arrangements? But I only found traci.person.add, traci.person.moveToXY, and there is no setroute function for me to choose.Is this kind of thinking right?
Thank you very much for helping me answer my doubts!!!!!!!

**Comment by namdre** [comment]
pedestrians are different because they have a plan with multiple stages (i.e. walk, ride, walk). Thus you need to use other methods (i.e. `person.appendWalkingStage`)
