### ISSUE TITLE
Parallel simulation only possible when compiled with Fox

### ISSUE THREAD

**Issue by jylee3302** [eclipse/sumo#7460]
Hi,

In the .sumocfg file, processing, when I define:  threads value="8"/ or any integer,
I get the error below.

Error: Parallel simulation is only possible when compiled with Fox.
Error: Parallel routing is only possible when compiled with Fox.

I'm using a Linux environment, and this error doesn't come when I comment out this threads value.
I suppose device.rerouting.threads is also responsible for this error.

I read the manual saying Fox is needed when I want a GUI, but is this also dependent on parallel simulation?

**Comment by namdre** [comment]
Yes. Fox is also needed for parallel operation. This may change in the future.
