### ISSUE TITLE
How to get the position of any vehicle within pre-step？

### ISSUE THREAD

**Issue by JianGong-seu** [eclipse/sumo#7461]
Hello！ I want to get the position of vehicle within preceding time step，such as traci.vehicle.getPosition(vehicleId) within step-1. How to deal with it

**Comment by namdre** [comment]
There is no traci call for this. You need to record and store these positions during the previous step in your own script. (i.e. in a python dict).

**Comment by JianGong-seu** [comment]
> There is no traci call for this. You need to record and store these positions during the previous step in your own script. (i.e. in a python dict).

Thank you.
