### ISSUE TITLE
How a bicycle passes through a blocked road？

### ISSUE THREAD

**Issue by Jianhua-Jiang** [eclipse/sumo#7464]
In order to realistically restore the real road, sometimes there is a problem of motor vehicles occupying the bicycle lane to park. How to make bicycles pass?

**Comment by namdre** [comment]
I don't understand your question. Do you wish to model the obstruction from parking vehicles or do you wish to let bicycles move through a road that is blocked for motor vehicles?

**Comment by Jianhua-Jiang** [comment]
> I don't understand your question. Do you wish to model the obstruction from parking vehicles or do you wish to let bicycles move through a road that is blocked for motor vehicles?

I am sorry that I did not state the problem clearly. I wish to let bicycles move through a road that is blocked for motor vehicles.

**Comment by Jianhua-Jiang** [comment]
> 我不明白你的问题。您是要模拟停车车辆的障碍物，还是要让自行车在机动车阻塞的道路上行驶？

I am sorry that I did not state the problem clearly. I want to simulate a bicycle lane blocked by a fixed obstacle and make bicycles pass through the section.

**Comment by namdre** [comment]
you may define a bicycle lanes and still permit bicycle traffic on the road lanes. When there is an obstacle on the bicycle lane (best modelled by a stopped vehicle with a vType that has vClass="ignoring"), the bicycles will automatically move onto the road lane and afterwards return to the bicycle lane.
