### ISSUE TITLE
Add a bicycle with an error: invalid type

### ISSUE THREAD

**Issue by Jianhua-Jiang** [eclipse/sumo#7466]
Can traci.vehicle.addLegacy add bicycles？Why always report an error: invalid type？

**Comment by namdre** [comment]
you first have to define a bicycle type in your xml input or set the type to "DEFAULT_BIKETYPE"

**Comment by Jianhua-Jiang** [comment]
> 您首先必须在xml输入中定义自行车类型，或将类型设置为“ DEFAULT_BIKETYPE”

I defined a bicycle type in my xml input as follows (Part of the code).
          <vType id="bicycle_1" length="1" width="0.48" maxSpeed="2.39" vClass="bicycle"/>
and fefined the traffic flow:
          <flow id="carflow_0.1" type="bicycle_1" beg="0" end="20" number="50" from="-gneE1" to="-gneE1"/>

It is normal to run in sumo, but an error occurred during python programming.
My code is:
                print(veh)
                print(self.random_traffic[veh][87])
                print(self.random_traffic[veh][traci.constants.VAR_TYPE])
                traci.vehicle.addLegacy(vehID=veh,
                                                      routeID='self_route',   #self.random_traffic[veh][87],
                                                      depart=1,
                                                      pos=0,
                                                      lane=-6,
                                                      speed=init_speed,
                                                      typeID=(self.random_traffic[veh][traci.constants.VAR_TYPE]))
                print("0000000000000000000000000000000000000------------------")   #test

OUTPUTS:

carflow_0.1.48
('-gneE1', 'gneE3', 'gneE7', 'gneE6', 'gneE5', '-gneE4', 'gneE10', '-gneE11')
bicycle_1
Step #0.00Error: Answered with error to command 0xc4: Invalid type 'bicycle_1' for vehicle 'carflow_0.1.48'

Traceback (most recent call last):
  File "D:/codecode/LasVSim-gui 0.2.1.200826_alpha_111/main.py", line 749, in on_new_sim
    if not self.on_settings():
  File "D:/codecode/LasVSim-gui 0.2.1.200826_alpha_111/main.py", line 660, in on_settings
    simulation.reset(dialog.settings)
  File "D:\codecode\LasVSim-gui 0.2.1.200826_alpha_111\simulator.py", line 137, in reset
    self.traffic.init(settings.points[0])
  File "D:\codecode\LasVSim-gui 0.2.1.200826_alpha_111\traffic_module.py", line 336, in init
    self.__initiate_traffic()
  File "D:\codecode\LasVSim-gui 0.2.1.200826_alpha_111\traffic_module.py", line 671, in __initiate_traffic
    [traci.constants.VAR_TYPE]))
  File "D:\AAAsofeware\sumo\tools\traci\_vehicle.py", line 1371, in addLegacy
    self.addFull(vehID, routeID, typeID, depart, lane, str(pos), str(speed))
  File "D:\AAAsofeware\sumo\tools\traci\_vehicle.py", line 1393, in add
    self._connection._sendExact()
  File "D:\AAAsofeware\sumo\tools\traci\connection.py", line 106, in _sendExact
    raise TraCIException(err, prefix[1], _RESULTS[prefix[2]])
traci.exceptions.TraCIException: Invalid type 'bicycle_1' for vehicle 'carflow_0.1.48'


Obviously the error appears in the step of traci.vehicle.addLegacy，is there a mistake in my usage?

THANK you very much！

**Comment by namdre** [comment]
I recommend calling traci.vehicletype.getIDList() to check whether the type "bicycle_1" has been loaded.

**Comment by Jianhua-Jiang** [comment]
> I recommend calling traci.vehicletype.getIDList() to check whether the type "bicycle_1" has been loaded.

I checked and found that the type "bicycle_1" has not been loaded, why does this happen？

**Comment by namdre** [comment]
either your call to traci.start did not include loading the additional xml file with the type definition or that definition is invalid and ignored (which can happen if the file has not schema information).
