### ISSUE TITLE
How to cancel default car-following model and intersection model in traci？

### ISSUE THREAD

**Issue by JianGong-seu** [eclipse/sumo#7467]
I want to  take some works in coordination of connected automated vehicles at intersections. How to invalidate the all car-following models and intersection model in simulation?

**Comment by namdre** [comment]
see https://sumo.dlr.de/docs/TraCI/Change_Vehicle_State.html#lane_change_mode_0xb6
and https://sumo.dlr.de/docs/TraCI/Change_Vehicle_State.html#speed_mode_0xb3

**Comment by JianGong-seu** [comment]
> see https://sumo.dlr.de/docs/TraCI/Change_Vehicle_State.html#lane_change_mode_0xb6
> and https://sumo.dlr.de/docs/TraCI/Change_Vehicle_State.html#speed_mode_0xb3

Thanks, friend.
