### ISSUE TITLE
when loading simulation state with flows, the original route file must also be loaded

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#7471]
otherwise, remaining flow vehicles will not be emitted.

This might be surprising since otherwise, all loaded vehicles are included in the state (and when loading a route file with -a) the state contains all necessary information.

**Comment by namdre** [comment]
@behrisch We are already saving the flowstate and could as well store additional attributes to restore the whole flow. Not sure If it's worth it though.

**Comment by behrisch** [comment]
In my opinion loading state should only guarantee to work properly if you use the same options (including all input files!) you used when saving. Everything else is very experimental. So I would close this one as wontfix.

**Comment by namdre** [comment]
This decisions has implications for 'traci.simulation.loadState' (#6201) where the explicit goal is to only load the state file.

We need at least to warn the user when loading an unfinished flow with loadState (or better, add flow support)

**Comment by behrisch** [comment]
> 
> @behrisch Is there a feasible way to rewind a loaded route file (loaded with option **--route-files**) to the previous time when calling loadState to prevent loss of vehicles?

I don't think so. There is a state token when doing incremental parsing but I don't think it saves the file location and can be saved. We could cache the contents in memory but I don't like that idea too much.

**Comment by namdre** [comment]
Then we should probably tag the saved state to indicate that it came from a simulation with incremental parsing and warn the user when using simulation.loadState with a state so tagged.

**Comment by roireshef** [comment]
@namdre I'm running into an issue where, when calling loadState in traci, the simulation restarts but without inflows. What should I do to fix that? It is not clear from your description.

**Comment by roireshef** [comment]
@namdre I'm not sure I'm following. I might have not explained myself well enough. The SUMO process is already up, first episode is running well. Then when an episode ends (according to some custom rule), I want to erase all vehicles in the scene, re-add my agent vehicle at the initial position (which is done successfully) and have the inflows keep sampling vehicles into the scene. The last part I can't figure out how to do. 

What I've done so far is: 
1. calling saveState at the beginning of my first episode
2. at the end of episode, when I want to erase all vehicles, call loadState from that same file I previously saved
3. re-add my agent vehicle. 

There is no actual restarting of the SUMO process, it's more like a soft reset functionality, without restarting of the simulator. so I can't see where to add that --additional-files flag you mentioned.

The original code I was using was just going over all existing "human" vehicles and removing them one by one in a loop, which stopped working as of one of the newer SUMO versions, not sure which one, but it lost backward compatibility w.r.t. to that. So I tried adding a clearPending() call - this has fixed some of the issues, but you suggested in https://github.com/eclipse/sumo/issues/8607#issuecomment-837913929 I then tried replacing this whole logic by calling loadState. Can't manage to make the inflows work with that solution yet.

**Comment by roireshef** [comment]
@namdre - OK, I tried doing exactly what you said (I'm doing it based on my best understanding, not sure I'm not missing anything). Initially, the file config file included:
```
<?xml version='1.0' encoding='UTF-8'?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/sumoConfiguration.xsd">
  <input>
    <net-file value="/tmp/flow/debug/net/lc_merge_longer_250m_fixed_c578b506-be00-11eb-9ad5-54bf6489db28.net.xml"/>
    <route-files value="NegotiationMergeScenario_20210526-0900081622019608.7957544.rou.xml"/>
    <additional-files value="NegotiationMergeScenario_20210526-0900081622019608.7957544.add.xml"/>
    <gui-settings-file value="NegotiationMergeScenario_20210526-0900081622019608.7957544.gui.cfg"/>
  </input>
  <begin value="0"/>
  <step-length value="0.1"/>
  <lateral-resolution value="0.1"/>
  <no-step-log value="true"/>
  <seed value="1235"/>
  <no-warnings value="true"/>
  <time-to-teleport value="-1"/>
  <collision.check-junctions value="true"/>
</configuration>
```

The *route-files* contents are:
```
<?xml version='1.0' encoding='UTF-8'?>
<routes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/routes_file.xsd">
  <route id="routeramp_0" edges="ramp merging goal_lane"/>
  <route id="routehwy_rear_0" edges="hwy_rear merging goal_lane"/>
  <route id="routegoal_lane_0" edges="goal_lane"/>
  <flow id="flow_00" route="routehwy_rear_0" type="other" departLane="0" departSpeed="21.964691855978614" begin="1" end="200000000.0" probability="0.43929383711957226"/>
</routes>
```

and the output of saveState is:
```
<?xml version="1.0" encoding="UTF-8"?>

<!-- generated on 2021-05-26 09:02:02 by Eclipse SUMO GUI Version 1.9.1
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/sumoConfiguration.xsd">

    <input>
        <net-file value="/tmp/flow/debug/net/lc_merge_longer_250m_fixed_c578b506-be00-11eb-9ad5-54bf6489db28.net.xml"/>
        <route-files value="/tmp/flow/debug/cfg/NegotiationMergeScenario_20210526-0900081622019608.7957544.rou.xml"/>
        <additional-files value="/tmp/flow/debug/cfg/NegotiationMergeScenario_20210526-0900081622019608.7957544.add.xml"/>
    </input>

    <time>
        <begin value="0"/>
        <step-length value="0.1"/>
    </time>

    <processing>
        <lateral-resolution value="0.1"/>
        <collision.action value="none"/>
        <collision.check-junctions value="true"/>
        <time-to-teleport value="-1"/>
    </processing>

    <report>
        <no-warnings value="true"/>
        <no-step-log value="true"/>
    </report>

    <traci_server>
        <remote-port value="43999"/>
        <num-clients value="1"/>
    </traci_server>

    <random_number>
        <seed value="1235"/>
    </random_number>

    <gui_only>
        <gui-settings-file value="/tmp/flow/debug/cfg/NegotiationMergeScenario_20210526-0900081622019608.7957544.gui.cfg"/>
        <quit-on-end value="true"/>
        <start value="true"/>
        <tracker-interval value="0.1"/>
    </gui_only>

</configuration>
-->

<snapshot xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/state_file.xsd" version="1.9.1" time="0.10" type="micro">
    <route id="routegoal_lane_0" state="1" edges="goal_lane"/>
    <route id="routehwy_rear_0" state="1" edges="hwy_rear merging goal_lane"/>
    <route id="routeramp_0" state="1" edges="ramp merging goal_lane"/>
    <flowState id="flow_00" index="0"/>
    <delay number="0" begin="0" end="0" depart="0.00" time="0.00"/>
    <vType id="other" minGap="3.00" maxSpeed="30.00" speedFactor="normc(1.00,0.10,0.20,2.00)" impatience="0.50" laneChangeModel="SL2015" lcStrategic="1.0" lcCooperative="1.0" lcSpeedGain="1.0" lcKeepRight="1.0" lcSublane="1.0" lcPushy="1" lcPushyGap="0" lcAssertive="1" lcAccelLat="10" lcLookaheadLeft="2.0" lcSpeedGainRight="1.0" carFollowModel="IDM" accel="3.0" decel="5.5" tau="0.1"/>
    <vType id="rl" minGap="0.00" maxSpeed="25.00" speedFactor="normc(1.00,0.10,0.20,2.00)" impatience="0.50" laneChangeModel="SL2015" lcStrategic="1.0" lcCooperative="1.0" lcSpeedGain="1.0" lcKeepRight="1.0" lcSublane="1.0" lcPushy="1" lcPushyGap="0" lcAssertive="1" lcAccelLat="10" lcLookaheadLeft="2.0" lcSpeedGainRight="1.0" carFollowModel="IDM" accel="3.0" decel="5.5" tau="0.1"/>
</snapshot>
```


Your proposed change is to modify the following line in the config file from:
`    <route-files value="NegotiationMergeScenario_20210526-0900081622019608.7957544.rou.xml"/>`
to:
`    <additional-files value="NegotiationMergeScenario_20210526-0900081622019608.7957544.rou.xml"/>`

Am I correct? If yes, I did try it but sumo won't start.

**Comment by namdre** [comment]
lack of flow support leads to surprising behavior when using #2443

**Comment by namdre** [comment]
now more surprises w.r.t. flows for #2443
