### ISSUE TITLE
I need a flow defined by probability.

### ISSUE THREAD

**Issue by Sheldon-Zhou1997** [eclipse/sumo#7472]
I want to get a random flow number from 2200-2600, but defining by probability=0.66 seems not doable.

**Comment by namdre** [comment]
running a flow with probability="0.66" for one hour will give you a binomial distribution with p=0.66, n=3600.
However, you need to make sure that the road can handle this much traffic: https://sumo.dlr.de/docs/FAQ.html#how_do_i_get_high_flowsvehicle_densities

**Comment by Sheldon-Zhou1997** [comment]
<flow id="flow0" type="type1" route="route_0" begin="0" end="3600" probability="0.2" departSpeed="max" departPos="base" departLane="best" arrivalPos="max"/>
If I define the flow like above,the flow in a short time interval may be 0, or very high, the "probability="0.2"" only make sure the average flow in 3600 is 720,but the flow'fluctuation can't be controled in the short time interval. I need a relatively stable and unconstant flow.

**Comment by Sheldon-Zhou1997** [comment]
<flow id="flow0" type="type1" route="route_0" begin="0" end="3600" probability="0.2" departSpeed="max" departPos="base" departLane="best" arrivalPos="max"/>

**Comment by behrisch** [comment]
If I understand correctly you want a flow with a random but more or less constant volume (something like this: https://xkcd.com/221/ ;-)). I would propose to either generate your inputs by a script which can write the sumo route input with the random numbers or maybe it is enough to have a constant base flow and add a second flow with random variation on top.
