### ISSUE TITLE
I don't know how to get all available routes.

### ISSUE THREAD

**Issue by Sheldon-Zhou1997** [eclipse/sumo#7476]
I want to get all available routes between these circled junctions in the network. What should I do?

**Comment by Sheldon-Zhou1997** [comment]
![qq_pic_merged_1598604604773](https://user-images.githubusercontent.com/52645665/91541717-579fcc80-e94f-11ea-9ff8-7295089b15e0.jpg)

**Comment by behrisch** [comment]
Take a class in combinatorics ;-). I am sorry but the question is not well defined. The number of routes is potentially infinite if you allow circles. If you don't, you can simply enumerate them by tracking all possibilities at each junction and aborting if an edge occurs twice. So you start for instance with edge 1 which is connected to 2 and 3, which gives you the paths 1,2 and 1,3 then you look where 2 and 3 are connected to and so on.
