### ISSUE TITLE
Routing clarity in Documentation

### ISSUE THREAD

**Issue by vishalmhjn** [eclipse/sumo#7478]
I think this could be an issue (unless I did or understood something incorrectly), the documentation on routing says:

at https://sumo.dlr.de/docs/Demand/Automatic_Routing.html
`--device.rerouting.probability <FLOAT> | 0 | The probability for a vehicle to have a routing device` 

at https://sumo.dlr.de/docs/sumo.html
`--device.rerouting.probability <FLOAT> | The probability for a vehicle to have a 'rerouting' device; default: -1`

Firstly, what is the default value **0 or -1.**

Secondly, if I run a simulation simply without specifying any routing using:
`sumo --mesosim -n network.net.xml -r routes.rou.xml` where routes.rou.xml are actually trips

Am I right if I assume that the online routing in the above should be turned off by default, and the vehicles should follow the shortest routes at the departure (as they do in Duarouter). 

Based on my results, I found that setting device rerouting probability to either 0 or 1 or default (not specifying anything) gives the same results. could you please clarify, or point me in the right direction?

Thanks in advance.

**Comment by behrisch** [comment]
Thanks for pointing it out, I clarified the docs. The default is -1 which has the one minor (and only technical) difference to 0 that it does not induce a call to the random number generator at all. To activate the routing while the vehicle is on the way you need to give **--device.rerouting.pre-period**.

**Comment by vishalmhjn** [comment]
Could you please explain the difference between these two options?
`--device.rerouting.pre-period <STRING> | 60 | The rerouting period before insertion/depart` Is this for both the pre-trip routing and en-route routing at 60 s interval, what does **before** mean?

`--device.rerouting.period <STRING> | 0 | The period with which the vehicle shall be rerouted` Is this also for en-route routing at a specified interval?

Thank you for your time.

**Comment by behrisch** [comment]
The first option (pre-period) defines the interval after which the vehicle will try to find a new route before it is departed. If the starting point is a district / taz / junction this may even change the starting edge of the route. This interval is not used for routing when the vehicle has departed. In this case (en route) the second interval (period) will be used.
