### ISSUE TITLE
SUMO GUI not opening

### ISSUE THREAD

**Issue by subhagakannan** [eclipse/sumo#7484]
Hello All,
 I am a new user of SUMO. i was working on the tutorial: https://sumo.dlr.de/docs/Tutorials/OSMWebWizard.html
After I click on 'GENERATE SCENARIO' Sumo GUI is not automatically opening and scenario is not being created. Can anyone pls tell me what the issue could be with?

**Comment by namdre** [comment]
when starting osmWebWizard a black command line window should have opened up in the background with additional information as to what is happening. Post the contents of that window (or a screenshot thereof).

**Comment by behrisch** [comment]
Closing for lack of feedback. Please reopen if problems persist.

**Comment by subhagakannan** [comment]
![issue_osm](https://user-images.githubusercontent.com/70543709/94022540-7d38be00-fdb5-11ea-8761-9a1f6cb30efa.PNG)
Hello All,
I am facing this issue when I am using OSM web wizard from SUMO. **.net file** is not being generated. I have attached the screenshot. Someone pls help me.

**Comment by behrisch** [comment]
Please check your SUMO_HOME variable. It seems to contain two paths.

**Comment by subhagakannan** [comment]
Can you pls tell me those paths? When I install SUMO it automatically adds SUMO_HOME.
Thanks in advance.

**Comment by subhagakannan** [comment]
I see that I have only one path named SUMO_HOME (automatically added during installation)

**Comment by behrisch** [comment]
And what is the value? I am asking because the "Could not open types file" error above looks like it tried to use an invlaid value for SUMO_HOME.

**Comment by subhagakannan** [comment]
![issue1](https://user-images.githubusercontent.com/70543709/94033689-8596f600-fdc1-11ea-80ee-04d8d22b2199.PNG)
i see that the value is 
C:\Users\skannan\Work\Eclipse\Sumo

**Comment by behrisch** [comment]
Yes but with a ";" at the end which should not be there.

**Comment by subhagakannan** [comment]
Thank you. The issue is solved.
