### ISSUE TITLE
How can i get vehicle's hidden state between steps

### ISSUE THREAD

**Issue by lidongke** [eclipse/sumo#7485]
HI
I want to get vehicle's hidden state to construct an episode to test my agent. If the episode has 800 steps, i focus on the sub episode like 500-600 steps, i want to get the vehicle's hidden state at the 500th step so that i can let the 500th step become the first state of my sub episode and this state not only has some parameters by initialization, but also has the hidden state by historical trajectory. is there some features like snapsort to do that?Thanks!
@ketan @jponge @atoulme @namdre

**Comment by namdre** [comment]
see https://sumo.dlr.de/docs/Simulation/SaveAndLoad.html
