### ISSUE TITLE
length given in dlrnavteq is ignored (trac #749)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#749]
Maybe it is for some good reason but the column containing the length attribute is parsed and even checked for numeric value but never used.

Migrated from http://sumo.dlr.de/ticket/749
```json
{
    "status": "new", 
    "changetime": "2015-01-22T11:47:53Z", 
    "description": "Maybe it is for some good reason but the column containing the length attribute is parsed and even checked for numeric value but never used.", 
    "reporter": "behrisch", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1421927273941814", 
    "component": "net building (NETGEN, NETCONVERT)", 
    "summary": "length given in dlrnavteq is ignored", 
    "priority": "minor", 
    "keywords": "", 
    "time": "2012-09-01T20:45:46Z", 
    "milestone": "1.0.0", 
    "owner": "", 
    "type": "defect"
}
```

**Comment by namdre** [comment]
For the record: I think the dlrnavteq lengths are calculated between junction centers. This makes the lengths suitable when building a network with option **--no-internal-links**. Otherwise, it makes more sense to recompute lengths so correctly add up with the internal lane lengths.
