### ISSUE TITLE
load state crash

### ISSUE THREAD

**Issue by lidongke** [eclipse/sumo#7503]
./sumo -c '/home/me/track03.sumocfg' --seed 0 --load-state '/home/me/sumo-1.6.0/data/2.xml'

log:
Loading configuration ... done.
Segmentation fault (core dumped)

SUMO crash after loading a XML file that saved by sumo-gui.[2.xml.tar.gz](https://github.com/eclipse/sumo/files/5172530/2.xml.tar.gz)
@namdre

**Comment by namdre** [comment]
to reproduce this, you must attach the network file as well.

**Comment by lidongke** [comment]
I have written my network config in track03.sumocfg:

<configuration>
    <input>
       <net-file value="track01.net.xml"/>
       <route-files value="track01.rou.xml,track01.vehicles.xml"/>
       <additional-files value="track01.vtype.xml"/>
    </input>
    <lanechange.duration value="3.0" />
	<lanechange.overtake-right value="true" />
	<max-depart-delay value="2" />
    <gui-settings-file value="track01.settings.xml"/>
</configuration>

**Comment by namdre** [comment]
please attach 'track01.net.xml' (zipped)

**Comment by lidongke** [comment]
[track01.net.xml.tar.gz](https://github.com/eclipse/sumo/files/5192365/track01.net.xml.tar.gz)

**Comment by namdre** [comment]
I can load the state with sumo version 1.6.0.
If you wish to use a more recent sumo version, make sure that version which wrote the state is the same version that loads the state. The state format is not stable between versions and may therefore fail to load.
