### ISSUE TITLE
probability setting can not work

### ISSUE THREAD

**Issue by JaneCheung** [eclipse/sumo#7506]
The values of duration in log files are all the same in my different cases, no matter how much the probability is.
My sumo version is 1.1.0.
[mycase1.zip](https://github.com/eclipse/sumo/files/5178177/mycase1.zip)

**Comment by namdre** [comment]
In versions before 1.3.0 the probability option did not have an effect on `<trip>` definitions and all vehicles were rerouting with the given period.
