### ISSUE TITLE
SUMO-gui interface display exception

### ISSUE THREAD

**Issue by Shiyunyang-seu** [eclipse/sumo#7511]
Hi, when I running sumo-GUI in my new device, there are large amount of green lines occuring, but all the vehicles can run correctly, and I try to re-install different version by MSI files, but the problem still exits. 
Basic configuration of the new device: 
Intel core i5-10300H CPU@2.5GHZ 16GB
Thanks in advance!
![gui](https://user-images.githubusercontent.com/55737075/92428414-a2c4a580-f1c1-11ea-8059-a7475d1f12ed.png)

**Comment by namdre** [comment]
see https://sumo.dlr.de/docs/FAQ.html#distorted_view_with_green_lines_all_over_the_network
