### ISSUE TITLE
How to control accelearation of vehicles using Traci？

### ISSUE THREAD

**Issue by JianGong-seu** [eclipse/sumo#7512]
I want load the acceleartion（the results by my designed algorithm）of vehicles in SUMO using Traci. What commands can help me realize it?

**Comment by namdre** [comment]
use vehicle.setSpeed and setSpeedMode (you need to compute the speed that would result from the desired acceleration at the configured step-length).

**Comment by JianGong-seu** [comment]
> use vehicle.setSpeed and setSpeedMode (you need to compute the speed that would result from the desired acceleration at the configured step-length).
Thanks. But I know vehicle.setSpeed is to set the speed of vehicle within the last step, how to set it within current step. What about vehicle.slowDown?

**Comment by namdre** [comment]
no. setSpeed sets the speed for **all** future steps (reset to sumo control with a negative speed value, actual vehicle speed subject to speedMode).
You can also use slowDown but note #7361

**Comment by JianGong-seu** [comment]
> no. setSpeed sets the speed for **all** future steps (reset to sumo control with a negative speed value, actual vehicle speed subject to speedMode).
> You can also use slowDown but note #7361

Thanks a lot.
