### ISSUE TITLE
How do I join the building around the road?To simulate the shadow interference brought by the building.I have already written the net.xml file and the rou.xml file and the sumocfg.xml file.

### ISSUE THREAD

**Issue by Mzy526** [eclipse/sumo#7513]

**Comment by namdre** [comment]
you can use polyconvert to import building shapes from OSM. However, sumo does not simulate communication or interference. For this you need to couple to a network simulator such as http://veins.car2x.org/

**Comment by Mzy526** [comment]
thanks!Can you give about the polyconvert  tutorials?

**Comment by namdre** [comment]
see https://sumo.dlr.de/docs/Networks/Import/OpenStreetMap.html#importing_additional_polygons_buildings_water_etc
you can change the typemap to discard everything except buildings.

**Comment by Mzy526** [comment]
thanks，I have use the netedit tool join the buildings，very convenience.
