### ISSUE TITLE
SUMO in Google Colab

### ISSUE THREAD

**Issue by alexDS12** [eclipse/sumo#7514]
Hey!

I'm currently trying to run a repo I've cloned but it fails printing out this error:

**please declare environment variable 'SUMO_HOME'**

I've tried to use **!export SUMO_HOME=/home/sumo-0.32.0/sumo/** trying to fix it nevertheless it didn't change a thing. When I navigate to _/home/_, there is no sumo-0.32.0 folder, all dependencies are installed correctly: SUMO, traci, tensorflow.

Any ideas how to solve this?

Many thanks.

**Comment by namdre** [comment]
SUMO_HOME must be set to the folder that contains sumo 'tools'. This will typically not be in your home directory but someplace like `/usr/share/sumo`
