### ISSUE TITLE
Update Xerces-C++ 3.2.3 in SUMOLibraries

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#7517]
[XERCESC-1963] - Custom HTTP headers missing with CURL NetAccessor
[XERCESC-2126] - Type Confusion from DTDGrammar to SchemaGrammar
**[XERCESC-2146] - Patch to build with older GCC**
**[XERCESC-2155] - fix build without pthread**
[XERCESC-2158] - XMLUTF8Transcoder: One multibyte UTF8 character is swallowed from the srcData when the resulting surrogate pair does not fit in toFill at the end
[XERCESC-2160] - Postpone freeing the memory being used by CURL
[XERCESC-2161] - No rule to make target '/src/xercesc/util/MsgLoaders/MsgCatalog/XercesMessages_en_US.Msg'
[XERCESC-2168] - Memory leak in ValueVectorOf
[XERCESC-2172] - There is an error in the parameters of the ThreadTtest8 script in Apache xerces-c++ XML's tests/script
[XERCESC-2176] - Incorrect symbolic links created for Linux static library and MacOS static and shared libraries
**[XERCESC-2177] - invalid windows version check for `onXPOrLater`**
[XERCESC-2180] - Handle surrogate pairs when reading a QName instead of ASSERTing
[XERCESC-2185] - Janitor.hpp fails to compile on Solaris with Solaris Studio 12.2 and 12.4
[XERCESC-2186] - undef symbols on HPUX for ArrayJanitor
[XERCESC-2187] - DOM tests crash on AIX
[XERCESC-2189] - XMLChar with NEED_TO_GEN_TABLE has 2 buffer out of bounds reads
**[XERCESC-2194] - Including Xerces_autoconf_config.hpp on Windows fails due to undefined ssize_t**

**Comment by behrisch** [comment]
Please also try to make sure that we have https support. Don't know if it helps, but this one seems to have it: https://cppget.org/?builds=libxerces-c.

**Comment by palvarezlopez** [comment]
New version uploaded in SUMOLibraries

**Comment by behrisch** [comment]
At least on my machine it still does not support https. Can you please recheck?

**Comment by behrisch** [comment]
I am still getting "unsupported protocol" but now for both http and https :-(

**Comment by palvarezlopez** [comment]
@behrisch do you removed all previous dlls before install new dlls?

**Comment by behrisch** [comment]
yes

**Comment by palvarezlopez** [comment]
New version was compiled with CURL, SSH2 and OpenSSL, then support https
