### ISSUE TITLE
How to calculate the maximum capacity of road network？

### ISSUE THREAD

**Issue by Shiyunyang-seu** [eclipse/sumo#7524]
Hi, if I want to test the maximum number of vehicles in a large-scale road network (it can be understood that all roads are full of vehicles). Can RandomTrips.py to test it?
Thanks in advance!

**Comment by namdre** [comment]
sumo-gui will list the total lane-length of the network in the network properties dialog (click on the car button in the status bar).
You can use this to compute the theoretical capacity when all roads are filled.
