### ISSUE TITLE
image problems

### ISSUE THREAD

**Issue by IB25** [eclipse/sumo#7526]
Good morning,

I have a display prblomes with Sumo.
I tried a lot but I didn't get a solution.
I have the screenshot attached.

I need your help.

Thank you in advance.

**Comment by palvarezlopez** [comment]
@IB25 we cannot see the attached screenshots

**Comment by IB25** [comment]
<img width="770" alt="Capture1" src="https://user-images.githubusercontent.com/71011982/92593318-33be7e00-f2a1-11ea-860d-c8b0d9eb2952.PNG">

**Comment by namdre** [comment]
see https://sumo.dlr.de/docs/FAQ.html#distorted_view_with_green_lines_all_over_the_network
