### ISSUE TITLE
convert visum netfile to sumo error

### ISSUE THREAD

**Issue by freegoo** [eclipse/sumo#7530]
I try to import net file which was generated by visum 2020 into sumo.  
command and error information
D:\test2\net>netconvert --visum  testdyna.net -o testsumo.net.xml
Error: No nodes loaded.
Quitting (on error).

[testdyna.zip](https://github.com/eclipse/sumo/files/5195767/testdyna.zip)

**Comment by namdre** [comment]
1) your network contains zones without ids. (lines 220-227). You either need to delete these lines or assign ids
2) you need to specify the input language (because visum files come in different languages)

after fixing the zones this worked for me (adapt the path to the language file):
```
netconvert --visum-file testdyna.net --visum.language-file /path/to/sumo/data/lang/visumEN.txt -v --taz-output taz.xml -o net.net.xml
```

**Comment by freegoo** [comment]
Hi, namdre.
I use your tips, and now I have converted VISUM net file to SUMO successfully.  Thank you very much.

Zones' attributes are correct, but there are 8 zones without boundaries. This caused the command to fail. I added boundaries to these zones, and the tools work well.

best regards,
Xianlong
