### ISSUE TITLE
When using Traci to start sumo, how can I monitor the traffic log information of SUMO?

### ISSUE THREAD

**Issue by radiateboy** [eclipse/sumo#7531]
Who can tell me what to do?
I want to get the following log information in real time in traci script？

for example:
`Warning: Teleporting vehicle '4482'; waited too long (yield), lane='-318.0.00_0', time=32656.00.`
`Warning: Vehicle '602' ends teleporting on edge '-337.0.00', time 434.00.`
`Warning: Teleporting vehicle '536'; collision with vehicle '386', lane=':6_1_0', gap=-1.00', latGap=0.00, time=436.00 stage=move.`
`Warning: Teleporting vehicle '878'; collision with vehicle '865', lane=':8_6_0', gap=-1.00', latGap=0.00, time=504.00 stage=move.`
`Warning: Teleporting vehicle '1112'; collision with vehicle '1101', lane=':18_9_0', gap=-1.00', latGap=0.00, time=588.00 stage=move.
`

**Comment by namdre** [comment]
you can use `traci.simulation.getStartingTeleportIDList` and `traci.simulation.getCollidingVehiclesIDList` to retrieve this directly from the simulation.

**Comment by radiateboy** [comment]
> 您可以使用`traci.simulation.getStartingTeleportIDList`并`traci.simulation.getCollidingVehiclesIDList`直接从模拟中检索。

@namdre Thanks, friend.
