### ISSUE TITLE
Can Sumo generate overhead image data for particular approach or intersection?

### ISSUE THREAD

**Issue by parthjaggi** [eclipse/sumo#7538]
I plan to work with image data with respect to traffic intersections.
Is it possible to do this with Sumo: generate images for the duration of the simulation, for a single approach or for an intersection.
Images would in the form of an overhead view, similar to the view that is visible from the GUI.

**Comment by angelobanse** [comment]
Take a look at this: https://sumo.dlr.de/docs/Tools/Visualization.html

**Comment by namdre** [comment]
You can generate simulation images with the screenshot feature: https://sumo.dlr.de/docs/sumo-gui.html#screenshots
Screenshots can also be triggered via the TraCI API with 'traci.gui.screenshot'.

**Comment by parthjaggi** [comment]
Thanks. Could you let me know about the following as well:
1. Is it possible to get screenshots using TraCI.
2. Is it possible to get them without using the GUI.

**Comment by namdre** [comment]
1).yes. using traci.gui.screenshot
2) no
