### ISSUE TITLE
crash when loading state and route file with routeDistribution

### ISSUE THREAD

**Issue by lidongke** [eclipse/sumo#7539]
It still has some problems when i load the state with sumo version 1.7.0.
windows:
debug:OK
release:crash
linux:
debug:crash
release:crash
![Screenshot from 2020-09-14 14-26-19](https://user-images.githubusercontent.com/51981935/93050923-4b797600-f696-11ea-843a-b45fdaa32e1c.png)
It seems like i can only use the debug version with windows.
@namdre

**Comment by namdre** [comment]
please attach 
- your state file 
- the inputs that were used to generated that file
- the command you used for loading the state

**Comment by lidongke** [comment]
[junction3.net.xml.tar.gz](https://github.com/eclipse/sumo/files/5218006/junction3.net.xml.tar.gz)
[junction3_test.sumocfg.tar.gz](https://github.com/eclipse/sumo/files/5218007/junction3_test.sumocfg.tar.gz)
[4.xml.tar.gz](https://github.com/eclipse/sumo/files/5218010/4.xml.tar.gz)
./sumo-gui -c '/home/me/cyrl/Cybertron/SUMO/Junction3/junction3_test.sumocfg'
./sumo-gui -c '/home/me/cyrl/Cybertron/SUMO/Junction3/junction3_test.sumocfg' --load-state '/home/me/cyrl/sumo-1.7.0/data/4.xml'

**Comment by namdre** [comment]
I cannot run junctio3_test.sumocfg because you did not include all the needed route- and additional-files.
However, the command
`sumo -n junction3.net.xml --load-state 4.xml` 
runs without problems.
Note, that it will not work with the latest development version since the state format already changed since the release.
Could it be that your debug and linux built are using the latest dev-tree?

**Comment by lidongke** [comment]
OK,I can run the command "sumo -n junction3.net.xml --load-state 4.xml" without problems too.
[junction3.vtype.xml.tar.gz](https://github.com/eclipse/sumo/files/5222873/junction3.vtype.xml.tar.gz)
[junction3.settings.xml.tar.gz](https://github.com/eclipse/sumo/files/5222874/junction3.settings.xml.tar.gz)
[junction3.rou.xml.tar.gz](https://github.com/eclipse/sumo/files/5222875/junction3.rou.xml.tar.gz)
[junction3.vehicles.xml.tar.gz](https://github.com/eclipse/sumo/files/5222876/junction3.vehicles.xml.tar.gz)
Could you help me to test my junctio3_test.sumocfg?

**Comment by namdre** [comment]
If you want to use 1.7 instead of the nightly build, you can just exclude the routeDistribution from your sumocfg. It's already in the saved state anyway so you are not losing anything.
