### ISSUE TITLE
randomTrips: Many Warning: No connection between edge 'A' and edge 'B' found.

### ISSUE THREAD

**Issue by ovechou** [eclipse/sumo#7541]
Some warning log:
Warning: No connection between edge '40988600#0' and edge '44380090#2' found.
Warning: No route for vehicle '19' found.
Warning: No connection between edge '25445890#17' and edge '228119756#1' found.
Warning: No route for vehicle '27' found.
Warning: No connection between edge '25445890#0' and edge '228119768#1' found.
Warning: No route for vehicle '33' found.
Warning: No connection between edge '25529686#16' and edge '270044023' found.
Warning: No route for vehicle '34' found.
Warning: No connection between edge '672979252' and edge '228119756#0' found.
Warning: No route for vehicle '46' found.
Warning: No connection between edge '25445890#3' and edge '228119757#3' found.

**And in the gui, the car about the warning route would stop a  a period of time**

**Comment by namdre** [comment]
Your network has disconnected edges. See https://sumo.dlr.de/docs/sumo-gui.html#check_connected_components

**Comment by ovechou** [comment]
> Your network has disconnected edges. See https://sumo.dlr.de/docs/sumo-gui.html#check_connected_components

I am so sorry, but the network is generated by osmWebWizard.py And the trips.xml is generated by randomTrips.py

**Comment by namdre** [comment]
Disconnected networks are nothing unusual (i.e. a city with a river and your area has no bridge). You either have to change the selected area or add randomTrips option **--validate** to make sure that only valid trips are written.
In this case you may want to generate additional trips to account for the discarded disconnected trips.
