### ISSUE TITLE
I can run program in Windows10 but can not run the same in ubuntu

### ISSUE THREAD

**Issue by ovechou** [eclipse/sumo#7543]

**Comment by ovechou** [comment]
error Log:
/usr/share/sumo/tools
 Retrying in 1 seconds
Loading configuration ... done.
***Starting server on port 53339 ***
Loading net-file from '/userhome/ove/MCOMA_REAL/real/2020-09-14-15-08-17/osm.net.xml' ... 
Error: invalid document structure
 In file '/userhome/ove/MCOMA_REAL/real/2020-09-14-15-08-17/osm.net.xml'
 At line/column 2/1.

Loading of net-file failed.
Quitting (on error)

The version in linux.
Eclipse SUMO Version 1.6.0
 Build features: Linux-4.4.0-178-generic x86_64 GNU 5.4.0 None Proj GUI SWIG GDAL GL2PS
 Copyright (C) 2001-2020 German Aerospace Center (DLR) and others; https://sumo.dlr.de
 License EPL-2.0: Eclipse Public License Version 2 <https://eclipse.org/legal/epl-v20.html>
 Use --help to get the list of options.

The version in windows.
Eclipse SUMO Version 1.6.0
 Build features: Windows-6.3.9600 AMD64 MSVC 18.0.40629.0 Release Proj GUI SWIG
 Copyright (C) 2001-2020 German Aerospace Center (DLR) and others; https://sumo.dlr.de
 License EPL-2.0: Eclipse Public License Version 2 <https://eclipse.org/legal/epl-v20.html>
 Use --help to get the list of options.

**Comment by ovechou** [comment]
The net-file is generated by osmWebWizard.py

**Comment by namdre** [comment]
please zip and attach the network.

**Comment by ovechou** [comment]
> please zip and attach the network.

Sorry，I want to know how to zip and attach the network.
Now I use the github to git push and git pull the file from the windows 10 to ubuntu.

**Comment by namdre** [comment]
I mean: attach the network file to this issue. You can simply drag a zip file into the comment box.

**Comment by ovechou** [comment]
[osm.net.zip](https://github.com/eclipse/sumo/files/5223726/osm.net.zip)
OK, thanks very much

**Comment by namdre** [comment]
The file loads fine on my version of Linux (tested with RHEL7).
What version of Ubuntu are you using?

@behrisch could this error plausibly come from an ancient version of Xerces?

**Comment by ovechou** [comment]
**This is the information about my version of Liunx.**
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial

4.15.0-45-generic

**Comment by behrisch** [comment]
Yes, I would also assume a xerces bug here. I will try to package the new sumo version today and we will see whether this helps.

**Comment by ovechou** [comment]
> Yes, I would also assume a xerces bug here. I will try to package the new sumo version today and we will see whether this helps.
Thanks very much. I would be very happy if you could send me a copy of the link for the new sumo version.

**Comment by behrisch** [comment]
I updated the launchpad so it should come automatically when you do an `apt full-upgrade`.

**Comment by ovechou** [comment]
Loading net-file from '/userhome/ove/MCOMA_REAL/real/2020-09-14-15-08-17/osm.net.xml' ... 
Error: invalid document structure
 In file '/userhome/ove/MCOMA_REAL/real/2020-09-14-15-08-17/osm.net.xml'
 At line/column 2/1.

Loading of net-file failed.
Quitting (on error).
Traceback (most recent call last):
  File "main3.py", line 22, in <module>
    env = SumoAgent(sumoCmd, 6, time_now)
  File "/userhome/MCOMA_REAL/MCOMA_REAL/envs/SumoAgent.py", line 97, in __init__
    env.start_sumo(sumo_cmd_str)
  File "/userhome/MCOMA_REAL/MCOMA_REAL/envs/env.py", line 143, in start_sumo
    traci.start(sumo_cmd_str)
  File "/usr/share/sumo/tools/traci/main.py", line 158, in start
    return init(sumoPort, numRetries, "localhost", label, sumoProcess)
  File "/usr/share/sumo/tools/traci/main.py", line 138, in init
    return getVersion()
  File "/usr/share/sumo/tools/traci/main.py", line 242, in getVersion
    return _connections[""].getVersion()
  File "/usr/share/sumo/tools/traci/connection.py", line 345, in getVersion
    result = self._sendCmd(command, None, None)
  File "/usr/share/sumo/tools/traci/connection.py", line 178, in _sendCmd
    return self._sendExact()
  File "/usr/share/sumo/tools/traci/connection.py", line 88, in _sendExact
    raise FatalTraCIError("connection closed by SUMO")
traci.exceptions.FatalTraCIError: connection closed by SUMO


I am so sorry about that, I updated my ubuntu and updated  the launchpad using `apt full-upgrade`.
It is still the error.

**Comment by ovechou** [comment]
> I updated the launchpad so it should come automatically when you do an `apt full-upgrade`.

Loading net-file from '/userhome/ove/MCOMA_REAL/real/2020-09-14-15-08-17/osm.net.xml' ...
Error: invalid document structure
In file '/userhome/ove/MCOMA_REAL/real/2020-09-14-15-08-17/osm.net.xml'
At line/column 2/1.

Loading of net-file failed.
Quitting (on error).
Traceback (most recent call last):
File "main3.py", line 22, in
env = SumoAgent(sumoCmd, 6, time_now)
File "/userhome/MCOMA_REAL/MCOMA_REAL/envs/SumoAgent.py", line 97, in init
env.start_sumo(sumo_cmd_str)
File "/userhome/MCOMA_REAL/MCOMA_REAL/envs/env.py", line 143, in start_sumo
traci.start(sumo_cmd_str)
File "/usr/share/sumo/tools/traci/main.py", line 158, in start
return init(sumoPort, numRetries, "localhost", label, sumoProcess)
File "/usr/share/sumo/tools/traci/main.py", line 138, in init
return getVersion()
File "/usr/share/sumo/tools/traci/main.py", line 242, in getVersion
return _connections[""].getVersion()
File "/usr/share/sumo/tools/traci/connection.py", line 345, in getVersion
result = self._sendCmd(command, None, None)
File "/usr/share/sumo/tools/traci/connection.py", line 178, in _sendCmd
return self._sendExact()
File "/usr/share/sumo/tools/traci/connection.py", line 88, in _sendExact
raise FatalTraCIError("connection closed by SUMO")
traci.exceptions.FatalTraCIError: connection closed by SUMO

I am so sorry about that, I updated my ubuntu and updated the launchpad using `apt full-upgrade`.
It is still the error.

**Comment by namdre** [comment]
Did you manage to solve your problem?

**Comment by behrisch** [comment]
It would also help to see the output of `ldd /usr/bin/sumo`.

**Comment by palvarezlopez** [comment]
@behrisch can I close this ticket?

**Comment by behrisch** [comment]
Closing for lack of feedback. Please reopen with the required info if problems persist.
