### ISSUE TITLE
Cannot compile SUMO on MacOS Catalina

### ISSUE THREAD

**Issue by rlloretb** [eclipse/sumo#7545]
I get the following error while compiling on MacOS Catalina: 
`brew update --with-ffmpeg --with-gdal --with-gl2ps --with-swig sumo`

==> Downloading https://www.python.org/ftp/python/2.7.16/Python-2.7.16.tar.xz
######################################################################## 100.0%
==> Reinstalling python@2 
Error: An exception occurred within a child process:
  FormulaUnavailableError: No available formula with the name "/usr/local/opt/python@2/.brew/python@2.rb" 

Where is Python 2 needed, BTW?

**Comment by schwamborn** [comment]
Please try again with the correct command line `brew install --with-ffmpeg --with-gdal --with-gl2ps --with-swig sumo`

**Comment by rlloretb** [comment]
I had used update since I already had a SUMO previously installed. 
I will try this new command.

**Comment by rlloretb** [comment]
I get this error now:

`Last 15 lines from /Users/lloretroger/Library/Logs/Homebrew/sumo/02.make:
[ 98%] Building CXX object src/marouter/CMakeFiles/marouter.dir/ROMARouteHandler.cpp.o
cd /tmp/sumo-20200915-65338-1flwar5/sumo-1_6_0/build/cmake-build/src/marouter && /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -DFLOAT_MATH_FUNCTIONS -I/tmp/sumo-20200915-65338-1flwar5/sumo-1_6_0/build/cmake-build/src -I/tmp/sumo-20200915-65338-1flwar5/sumo-1_6_0/src -std=c++11 -pthread -Wall -pedantic -Wextra -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -fPIE   -I/usr/local/Cellar/fox/1.6.56_1/include/fox-1.6 -o CMakeFiles/marouter.dir/ROMARouteHandler.cpp.o -c /tmp/sumo-20200915-65338-1flwar5/sumo-1_6_0/src/marouter/ROMARouteHandler.cpp
[ 98%] Linking CXX executable ../../../../bin/marouter
cd /tmp/sumo-20200915-65338-1flwar5/sumo-1_6_0/build/cmake-build/src/marouter && /usr/local/Cellar/cmake/3.18.2/bin/cmake -E cmake_link_script CMakeFiles/marouter.dir/link.txt --verbose=1
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++  -std=c++11 -pthread -Wall -pedantic -Wextra -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names CMakeFiles/marouter.dir/marouter_main.cpp.o CMakeFiles/marouter.dir/ROMAAssignments.cpp.o CMakeFiles/marouter.dir/ROMAEdge.cpp.o CMakeFiles/marouter.dir/ROMAEdgeBuilder.cpp.o CMakeFiles/marouter.dir/ROMAFrame.cpp.o CMakeFiles/marouter.dir/ROMARouteHandler.cpp.o -o ../../../../bin/marouter  ../router/librouter.a ../od/libod.a ../utils/emissions/libutils_emissions.a ../foreign/PHEMlight/cpp/libforeign_phemlight.a ../utils/vehicle/libutils_vehicle.a ../utils/distribution/libutils_distribution.a ../utils/shapes/libutils_shapes.a ../utils/options/libutils_options.a ../utils/xml/libutils_xml.a ../utils/geom/libutils_geom.a ../utils/common/libutils_common.a ../utils/importio/libutils_importio.a ../utils/iodevices/libutils_iodevices.a ../utils/traction_wire/libutils_traction_wire.a ../foreign/tcpip/libforeign_tcpip.a /usr/local/lib/libxerces-c.dylib /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/lib/libz.tbd /usr/local/lib/libproj.dylib -L/usr/local/Cellar/fox/1.6.56_1/lib -lFOX-1.6 -lX11 -lXext -lfreetype -lfontconfig -lXft -lXcursor -lXrender -lXrandr -lXfixes -lXi -lGL -lGLU -ldl -lpthread -ljpeg -lpng -ltiff -lz -lbz2 -lGLU -lGL 
[ 98%] Built target marouter
[ 98%] Linking CXX executable ../../../../bin/TraCITestClient
cd /tmp/sumo-20200915-65338-1flwar5/sumo-1_6_0/build/cmake-build/src/traci_testclient && /usr/local/Cellar/cmake/3.18.2/bin/cmake -E cmake_link_script CMakeFiles/TraCITestClient.dir/link.txt --verbose=1
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++  -std=c++11 -pthread -Wall -pedantic -Wextra -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names CMakeFiles/TraCITestClient.dir/tracitestclient_main.cpp.o CMakeFiles/TraCITestClient.dir/TraCITestClient.cpp.o -o ../../../../bin/TraCITestClient  ../utils/traci/libutils_traci.a ../utils/distribution/libutils_distribution.a ../utils/shapes/libutils_shapes.a ../utils/options/libutils_options.a ../utils/xml/libutils_xml.a ../utils/geom/libutils_geom.a ../utils/common/libutils_common.a ../utils/importio/libutils_importio.a ../utils/iodevices/libutils_iodevices.a ../utils/traction_wire/libutils_traction_wire.a ../foreign/tcpip/libforeign_tcpip.a /usr/local/lib/libxerces-c.dylib /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/lib/libz.tbd /usr/local/lib/libproj.dylib 
[ 98%] Built target TraCITestClient
[ 98%] Linking CXX shared module ../../../../tools/libsumo/_libsumo.so
cd /tmp/sumo-20200915-65338-1flwar5/sumo-1_6_0/build/cmake-build/src/libsumo && /usr/local/Cellar/cmake/3.18.2/bin/cmake -E cmake_link_script CMakeFiles/libsumo.dir/link.txt --verbose=1
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++  -std=c++11 -pthread -Wall -pedantic -Wextra -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -bundle -Wl,-headerpad_max_install_names -o ../../../../tools/libsumo/_libsumo.so CMakeFiles/libsumo.dir/__/__/tools/libsumo/libsumoPYTHON_wrap.cxx.o  liblibsumostatic.a ../traci-server/libtraciserver.a ../netload/libnetload.a ../microsim/cfmodels/libmicrosim_cfmodels.a ../microsim/engine/libmicrosim_engine.a ../microsim/lcmodels/libmicrosim_lcmodels.a ../microsim/devices/libmicrosim_devices.a ../microsim/trigger/libmicrosim_trigger.a ../microsim/output/libmicrosim_output.a ../microsim/transportables/libmicrosim_transportables.a ../microsim/actions/libmicrosim_actions.a ../microsim/traffic_lights/libmicrosim_traffic_lights.a ../microsim/libmicrosim.a ../mesosim/libmesosim.a ../utils/emissions/libutils_emissions.a ../foreign/PHEMlight/cpp/libforeign_phemlight.a ../utils/vehicle/libutils_vehicle.a ../utils/distribution/libutils_distribution.a ../utils/shapes/libutils_shapes.a ../utils/options/libutils_options.a ../utils/xml/libutils_xml.a ../utils/geom/libutils_geom.a ../utils/common/libutils_common.a ../utils/importio/libutils_importio.a ../utils/iodevices/libutils_iodevices.a ../utils/traction_wire/libutils_traction_wire.a ../foreign/tcpip/libforeign_tcpip.a /usr/local/lib/libxerces-c.dylib /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/lib/libz.tbd /usr/local/lib/libproj.dylib -L/usr/local/Cellar/fox/1.6.56_1/lib -lFOX-1.6 -lX11 -lXext -lfreetype -lfontconfig -lXft -lXcursor -lXrender -lXrandr -lXfixes -lXi -lGL -lGLU -ldl -lpthread -ljpeg -lpng -ltiff -lz -lbz2 -lGLU -lGL /usr/lib/libpython2.7.dylib 
[ 98%] Built target libsumo
make: *** [all] Error 2`

**Comment by rlloretb** [comment]
![image](https://user-images.githubusercontent.com/15695480/93199186-a6879780-f780-11ea-99b7-09d5cbd5594e.png)

**Comment by rlloretb** [comment]
> This error keeps popping out, after clicking cancel many times, compiling keeps going:
> ![image](https://user-images.githubusercontent.com/15695480/93199186-a6879780-f780-11ea-99b7-09d5cbd5594e.png)

I am following these instructions now:
https://errors.wtf/openjdk-cannot-be-opened-because-the-developer-cannot-be-verified-adb-brew/

**Comment by schwamborn** [comment]
The Java issue is not (directly) related to the sumo formula AFAIK. It might be related to SWIG, though. In any case, if you do not especially need openjdk, I would suggest using Oracle Java.

I just ran the sumo install command on a fresh Catalina system without issues.
You might want to try uninstalling your old sumo install first and then try again.
Also, please attach the whole output from the install command this time, including all of the `make` output.

**Comment by rlloretb** [comment]
Since I only needed gdal, I compiled SUMO with only the gdal requirement.
I did uninstall the old SUMO installation. It was required, actually.
I did fix the java problem following the advice from the link I posted.
SUMO compiled successfully.
