### ISSUE TITLE
How to get the steering information allowed by the lane？

### ISSUE THREAD

**Issue by radiateboy** [eclipse/sumo#7546]
I want to know if the current Lane allows left or right turns. What should I do?
No such information can be found in the net file.

**Comment by namdre** [comment]
you can use sumolib to parse the net. (https://sumo.dlr.de/docs/Tools/Sumolib.html)
net.getLane(laneID).getOutgoing() gives you all connection objects. These connections provide the method getDirection() which is "l" for left turn and "r" for right turn.

**Comment by radiateboy** [comment]
@namdre Thank you very much, friend.
