### ISSUE TITLE
Vehicle Speed using Engine Models

### ISSUE THREAD

**Issue by mahbub-iut** [eclipse/sumo#7549]
I'm trying to use the engine model created for Plexe and some other factors that affects the vehicle speed to finalize the vehicle speed in the next simulation step. I was wondering what Classes I should have a look at to get started? The vehicle state is handled in the MSVehicle.* . I was wondering which class is finalizing the speed for the next simulation step

**Comment by namdre** [comment]
see https://github.com/eclipse/sumo/blob/74e69e43f081c73f4448a6b0e39ae23c8418f8a6/src/microsim/cfmodels/MSCFModel.cpp#L163
carfollowmodels may override this function (and some do).
