### ISSUE TITLE
How to import real-world vehicle trajectory datasets into sumo?

### ISSUE THREAD

**Issue by kinwgze** [eclipse/sumo#7554]
I want to import a real-world vehicle trajectory data set into Sumo. The data set includes the latitude, longitude and time of a vehicle trajectory, which is sampled every 3s. Is there a tool in sumo that can process it into trajectory data supported by sumo?

**Comment by behrisch** [comment]
There is FAQ on this https://sumo.dlr.de/docs/FAQ.html#how_do_i_generate_sumo_routes_from_gps_traces.
