### ISSUE TITLE
How can I get the statistics of the number of vehicles passing by in 30 minutes at a certain intersection?

### ISSUE THREAD

**Issue by radiateboy** [eclipse/sumo#7562]
I want to know how to get the traffic flow of each intersection at a certain time stage?

**Comment by namdre** [comment]
see https://sumo.dlr.de/docs/Simulation/Output.html#values_for_junctions
Alternatively, use https://sumo.dlr.de/docs/Simulation/Output/Lane-_or_Edge-based_Traffic_Measures.html and extract information for the desired edges from the result.
