### ISSUE TITLE
How can I know if one edge to the other edge is a left turn, straight line or right turn connection?

### ISSUE THREAD

**Issue by radiateboy** [eclipse/sumo#7570]
How can I know if one edge to the other edge is a left turn, straight line or right turn connection?

**Comment by namdre** [comment]
looks like a duplicate of #7546. Please refine your question in the original ticket (with an explanation why the old answer was insufficient) or clarify the question so I can understand that you are asking for something different.

**Comment by radiateboy** [comment]
thank you very very much.  @namdre 
I want to play back a real scene. I only have the steering information of real vehicles on the lane and edgeID and lane ID. I can create a traffic flow through jtroute. Then according to the statistics of lane flow information in the output after the end, it is found that the result is somewhat different from the actual situation, so I want to add traffic flow to some lanes dynamically during the driving process.

**Comment by namdre** [comment]
The answer given in #7546 is applicable to your task.

**Comment by radiateboy** [comment]
ok，thanks friend. @namdre

**Comment by radiateboy** [comment]
`import sumolib

net = sumolib.net.readNet('input_tri.net.xml')
edges = net.getEdges()
for i in edges:
    lanes = i.getLanes()
    for l in lanes:
        out = net.getLane(l.getID()).getOutgoing()
        if out:
            for i in out:
                print(i, i.getDirection())`
