### ISSUE TITLE
sumo/ traci cannot allocate memory on ubuntu 16.04

### ISSUE THREAD

**Issue by ChocolateDave** [eclipse/sumo#7574]
Hello! I've been trying to test a scenario on my cloud server recently when I came across an error. The warning said "Cannot allocate memory" and traced back to one of the function related to traci. Could you help with this?

> Traceback (most recent call last):
>>   File "main.py", line 41, in <module>
>     main(parser.parse_args())
>   File "main.py", line 33, in main
>     agent.currentState = env.reset()
>   File "/root/Intellectual-Traffic-Light-System/env/wrapped.py", line 256, in reset
>     traci.start(sumoCmd, label=mode)
>   File "/usr/share/sumo/tools/traci/main.py", line 156, in start
>     sumoProcess = subprocess.Popen(cmd2, stdout=stdout)
>   File "/usr/local/miniconda3/envs/dl/lib/python3.6/subprocess.py", line 729, in __init__
>     restore_signals, start_new_session)
>   File "/usr/local/miniconda3/envs/dl/lib/python3.6/subprocess.py", line 1295, in _execute_child
>     restore_signals, start_new_session, preexec_fn)
> OSError: [Errno 12] Cannot allocate memory

**Comment by behrisch** [comment]
Is the code somewhere public? It is hard to tell just from the stack trace. If this is happening after some time and/or the network is very large it may very well be that the system ran out of memory.

**Comment by ChocolateDave** [comment]
> Is the code somewhere public? It is hard to tell just from the stack trace. If this is happening after some time and/or the network is very large it may very well be that the system ran out of memory.

Yes, the code is now publicly available in my [repository](https://github.com/ChocolateDave/Intellectual-Traffic-Light-System).
The network for experiment is currently a single intersection, which in my opinion shouldn't have caused the allocation error.

**Comment by behrisch** [comment]
And it is happening right after start?

**Comment by ChocolateDave** [comment]
Yes, I tried restarting the device once, but same prompt apprised.

**Comment by behrisch** [comment]
Does the same thing happen when running locally or only in the cloud?
