### ISSUE TITLE
Socket connection failed in Sumo OSM web wizard

### ISSUE THREAD

**Issue by subhagakannan** [eclipse/sumo#7586]
![grafik](https://user-images.githubusercontent.com/70543709/94035835-df98bb00-fdc3-11ea-98ce-fd9811c21a9e.png)
Hello All,
I face this issue when OSM web wizard opens in microsoft edge.
Can anyone pls tell me how does this impact the network generation? Its working fine with Firefox. How to change the default browser?
Thanks in advance.

**Comment by behrisch** [comment]
If the browser cannot connect to the script, no network will be created. For setting the default browser see https://support.mozilla.org/en-US/kb/how-change-your-default-browser-windows-10
