### ISSUE TITLE
lock against concurrent file write access when running with multiple threads

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#7587]
Example: multiple inductionLoops writing to the same file.
The current mutex `    FXConditionalLock lock(myNotificationMutex, myNeedLock);` cannot solve this because it only prevents the *same* detector from being access concurently.
However, it would not prevent an E1 and E2 detector (or just different E1 detectors) from writing to the same file.
To solve this we probably need per-file locks.

**Comment by behrisch** [comment]
Currently this should not be a problem since output generation is not parallelized yet. MSNet::writeOutput comes at the very end.

**Comment by namdre** [comment]
You're right. However, we do have a report of crashing when running with 4 threads on sumo-dev. What could be the reason?

**Comment by behrisch** [comment]
The valgrind runs I did on the grid found some concurrent write access. I will have a closer look.

**Comment by behrisch** [comment]
No further input here
