### ISSUE TITLE
When the OSM file is converted into the road network file of sumo, one junction with green belt is converted into four junctions, which makes the setting of traffic lights more complicated.

### ISSUE THREAD

**Issue by radiateboy** [eclipse/sumo#7593]
there are many such junction in my map.  how to solve this problem?
1. osm map
![20200925101728](https://user-images.githubusercontent.com/9248754/94220402-6c09c180-ff1b-11ea-9c2c-3a26e2458508.png)

2. sumo network map
![20200925101711](https://user-images.githubusercontent.com/9248754/94220443-85ab0900-ff1b-11ea-9994-11c6edace94c.png)

**Comment by namdre** [comment]
see https://sumo.dlr.de/docs/Networks/Import/OpenStreetMap.html#junctions
