### ISSUE TITLE
reconsider element <neigh>

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#7595]
currently, the optional `<neigh>` element only holds a single lane attribute which is used to encode the id of the opposite lane for opposite-direction-driving. It would have been sufficient to invent an optional attribute (i.e. `oppositeID`) for this.

The original design reason for using a new element was probably to obtain flexibility for #3656. However, lane change restrictions for a specific set of vClasses (I don't see that we need this type-specific) could also be accomplished via attributes such as
`changeLeft="bicycle" changeRight="authority" `
Using attribute 'lane' for this would be overly redundant since outside of opposite-direction-driving the edge id is already fixed.
Using a blacklist (`disallowChangeLeft="all"`) is probably not needed because `"authority"` is a realistic stand-in for "normal traffic is not permitted to change". It would be more justified if restricting only a few vClass (trucks?) were common.

Using lane attributes rather than child elements would simplify other tooling (netedit, netDiff, parsers) and probably reduce file size as well.

**Comment by behrisch** [comment]
I think another reason was #1620 to have the synchronization points in a separate element and not in the lane itself.

**Comment by namdre** [comment]
Ok. Then lets keep things as they are now.

**Comment by namdre** [comment]
After thinking about this some more, I think I prefer to add attributes 'changeLeft', 'changeRight' now and use the `<neigh>` element for synchronization points eventually in version 2.0
