### ISSUE TITLE
enable logging debug output on windows for release build

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#7599]
On windows, there is no default console to write to (at least in release mode). Nevertheless, some messages would be useful (in particular rail_signal stuff).

- replace naked std::cout calls with WRITE_DEBUG (check if this clashes with netedit usage of WRITE_DEBUG)
- new option **--debug-log** that outputs debug messages to file
- log file can be observed continuously (https://superuser.com/questions/274961/how-to-automatically-reload-modified-files-in-notepad)

Alternatively, the messages could be piped to the sumo-gui message window

**Comment by palvarezlopez** [comment]
Fixed in #7656
