### ISSUE TITLE
netconvert vehicle:lanes=yes|yes|no support

### ISSUE THREAD

**Issue by ambuehll** [eclipse/sumo#7601]
This is a feature request for netconvert. I am not sure how common this is in OSM tags. So, it might be low priority, but maybe it's also an easy fix...
When vehicle:lanes=yes|yes|no -> only two lanes should be accessible for traffic (https://wiki.openstreetmap.org/wiki/Lanes)
See edge:-313465298#1 in the example.

[files](https://drive.google.com/drive/folders/18ktPZuGKGZb4NI6vg9Be_bKtolDwHEFo?usp=sharing)
As always, many thanks!

**Comment by namdre** [comment]
Current implementation only considers whether the lanes permit vehicles but does not add add alternative permissions (i.e. bicycle) if vehicles are forbidden.
