### ISSUE TITLE
the issue of traci.trafficlight.setCompleteRedYellowGreenDefinition

### ISSUE THREAD

**Issue by zhaotuo0815** [eclipse/sumo#7602]
hello，developers.I have met some trouble when I use traci.trafficlight.setCompleteRedYellowGreenDefinition.
I set up two traffic light control schemes,and the used the corresponding traffic light control 

scheme after each fixed simulation time and edge occupancy reached the value I set,but I found that the traffic light always used the first contrl strtegy....

there is the phase  I set:
"""
    phases = []
    phases.append(traci.trafficlight.Phase(5, "GGGGGrrrrrrrGGGGGrrrrrrr", next=()))
    phases.append(traci.trafficlight.Phase(3, "yyyyyrrrrrrryyyyyrrrrrrr", next=()))
    phases.append(traci.trafficlight.Phase(20, "rrrrrGrrrrrrrrrrrGrrrrrr",next=()))
    phases.append(traci.trafficlight.Phase(3, "rrrrryrrrrrrrrrrryrrrrrr", next=()))
    phases.append(traci.trafficlight.Phase(5, "rrrrrrGGGGGrrrrrrrGGGGGr",next=()))
    phases.append(traci.trafficlight.Phase(3, "rrrrrryyyyyrrrrrrryyyyyr", next=()))
    phases.append(traci.trafficlight.Phase(5, "rrrrrrrrrrrGrrrrrrrrrrrG",next=()))
    phases.append(traci.trafficlight.Phase(3, "rrrrrrrrrrryrrrrrrrrrrry",next=()))

    phases_origin = []
    phases_origin.append(traci.trafficlight.Phase(35, "GGGGGrrrrrrrGGGGGrrrrrrr",  next=()))
    phases_origin.append(traci.trafficlight.Phase(3, "yyyyyrrrrrrryyyyyrrrrrrr",next=()))
    phases_origin.append(traci.trafficlight.Phase(20, "rrrrrGrrrrrrrrrrrGrrrrrr",next=()))
    phases_origin.append(traci.trafficlight.Phase(3, "rrrrryrrrrrrrrrrryrrrrrr",next=()))
    phases_origin.append(traci.trafficlight.Phase(35, "rrrrrrGGGGGrrrrrrrGGGGGr",next=()))
    phases_origin.append(traci.trafficlight.Phase(3, "rrrrrryyyyyrrrrrrryyyyyr",next=()))
    phases_origin.append(traci.trafficlight.Phase(20, "rrrrrrrrrrrGrrrrrrrrrrrG",next=()))
    phases_origin.append(traci.trafficlight.Phase(3, "rrrrrrrrrrryrrrrrrrrrrry",next=()))

"""

there is the code:
    while traci.simulation.getMinExpectedNumber()>0:
        traci.simulationStep()
        if traci.edge.getLastStepOccupancy("gneE27")>0.2 and traci.simulation.getTime()%120==0:
            logic = traci.trafficlight.Logic("J22_0", 0, 0, phases)
            traci.trafficlight.setCompleteRedYellowGreenDefinition("gneJ22", logic)

        elif traci.edge.getLastStepOccupancy("gneE27")<0.2 and traci.simulation.getTime()%120==0:
            logic_origin= traci.trafficlight.Logic("J22_origin", 0, 0, phases_origin)
            traci.trafficlight.setCompleteRedYellowGreenDefinition("gneJ22", logic_origin)

**Comment by namdre** [comment]
did you check whether the code ` traci.trafficlight.setCompleteRedYellowGreenDefinition("gneJ22", logic_origin)` is ever executed?

**Comment by zhaotuo0815** [comment]
Thank you very much for your reply.&nbsp;python can execute this part of the code, but the traffic light control scheme has been using the first one.&nbsp;This question has been bothering me for a long time.



发自我的iPhone


------------------ Original ------------------

**Comment by namdre** [comment]
try switching with traci.trafficlight.setProgram. Does this work or is there an error message?

**Comment by namdre** [comment]
closing due to lack of feedback.
