### ISSUE TITLE
unable to open file 'https://sumo.dlr.de/xsd/additional_file.xsd'

### ISSUE THREAD

**Issue by Jianhua-Jiang** [eclipse/sumo#7607]
Sumo can't run suddenly, I would like to ask you, is this a software problem or a code problem?

Error: unable to open file 'https://sumo.dlr.de/xsd/additional_file.xsd'
 In file 'D:\codecode\LasVSim-gui 0.2.1.200901_alpha\Map\Map1_Urban Road\grid-map-additions.add.xml'
 At line/column 1/0.

**Comment by palvarezlopez** [comment]
Hi,

did you defined the enviroment variable SUMO_HOME?

**Comment by Jianhua-Jiang** [comment]
> Hi,
> 
> did you defined the enviroment variable SUMO_HOME?

Yes, I have defined the enviroment variable SUMO_HOME as D:\AAAsofeware\sumo-1.6.0\. Btw, I would like to ask, when there are two versions of sumo, how to choose a certain one in pycharm? THANKS!

**Comment by behrisch** [comment]
Please double check that there is no warning about SUMO_HOME and that SUMO_HOME is also known in the terminal / cmd window you are starting sumo from. For your second question: you can always give the full path when starting sumo.
