### ISSUE TITLE
Grid disappears when enabling Tooltips

### ISSUE THREAD

**Issue by angelobanse** [eclipse/sumo#7608]
Disabling the Tooltips brings the Grid back.

**Comment by angelobanse** [comment]
This also affects sumo-gui. Is it intentional?

**Comment by angelobanse** [comment]
If it was indeed a bug and not an intentional behaviour / feature, then 39ecd09 fixes this issue. @namdre

**Comment by namdre** [comment]
Though the code does look somewhat intentional, I don't see a good reason why it should have been that way. Works fine now.
