### ISSUE TITLE
modify the lateral speed bug during lane change

### ISSUE THREAD

**Issue by Jianhua-Jiang** [eclipse/sumo#7612]
When the car is driving and changing lanes, it will suddenly appear that the lateral speed is almost zero. At this time, the calculated yaw angle will be close to 90 degrees, resulting in errors. How to modify the speed bug during lane change? Thanks！

**Comment by namdre** [comment]
please attach an example scenario that shows this issue. Also provide information regarding the vehicle and time step.

**Comment by namdre** [comment]
With the default model, lane change is instant. If you need more details, see https://sumo.dlr.de/docs/Simulation/SublaneModel.html
