### ISSUE TITLE
feature: breakpoint creation on timestamp click in sumo log window for scenario analysis convenience

### ISSUE THREAD

**Issue by gprichter** [eclipse/sumo#7617]
I thought it were nice _to analyze problematic situations_ in a sumo scenario
apart from having the *nice features of links* behind lanes and vehicle ids *in the sumo log*
to also have those _when clicking on the logged time of the event_ and *thereby create a breakpoint* 
maybe 5 seconds before the occurrence of the warning or so.

just a reload and rerun and focusing in on the position 
should let one step through the occurrence to get a better understanding of what just happened.

optionally: 
* the click on the time would toggle this breakpoint being set or not.
* the pre-event offset could be configures as an option somewhere

**Comment by namdre** [comment]
That would fit my own debugging pattern as well.
