### ISSUE TITLE
rescue lane on 3-lane road does not work if emergency vehicle must turn right

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#7619]
on a 3-lane road, the leftmost vehicle moves left while the other vehicles align right. This blocks access to the right-turn lane.

Also relevant: #7620

**Comment by namdre** [comment]
Suggested solution: emergency vehicle drives up to stop line on the wrong lane, then teleports silently to the correct internal lane that continues it's route.

**Comment by lbieker** [comment]
First try to fix this issue but problems in the debug build occur: 
[emergencyvehicle_rightturn.txt](https://github.com/eclipse/sumo/files/5558758/emergencyvehicle_rightturn.txt)

Another solution will follow
