### ISSUE TITLE
webwizard simulation spends 2/3 of it's time updating edge weights for device.rerouting

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#7640]
simulation has a few pedestrians with long walks which inflates simulation time.
Even within the core execution time where vehicles are still being inserted the option
**--device.rerouting.adaptation-interval 1 / 0**
changes the running time from 24s to 15s.
This suggests that
a) edge updates are too slow
b) the default adaptation-interval of 1 may be too wasteful

**Comment by namdre** [comment]
@behrisch I would consider changing the default from 1s to 10s (and the change device.rerouting.adaptation-steps from 180 to 18 so that the same time range is covered)

**Comment by behrisch** [comment]
+1

**Comment by namdre** [comment]
changing defaults impacts many tests some of them in surprising ways (i.e. train collision)
