### ISSUE TITLE
stopSpeed/followSpeed for information purpose and for speed update

### ISSUE THREAD

**Issue by Domsall** [eclipse/sumo#7642]
Hello,
I use a CF-model which saves values each timestep and uses an internal reaction time.
For this reason, I differentiate between speed update calculations and information calculations (e.g. in the LC-model). Depending on those 2 cases, the calculated values in stopSpeed and followSpeed are saved.
Is it possible to add a bool value to the inputs of followSpeed/stopSpeed to account for those 2 cases? Is there another/better way of implementing such an internal update (if a followSpeed/stopSpeed-calculation resulted in an updated speed for the next time step)?
Thanks in advance!

**Comment by namdre** [comment]
There is already a flag that distinguishes carFollowing-updated calculations from laneChanging calls to the cfModel. You can check the value of `MSGlobals::gComputeLC`

**Comment by Domsall** [comment]
That variable unfortunately does not do the trick in every case. Some calls in planMoveInternal don't result in immediate speed updates, especially when checking Links/foes on Links, e.g. calculating `double vLinkWait = MIN2(v, cfModel.stopSpeed(this, getSpeed(), stopDist));` in Line 2712. Calculated vLinkWait values then get processed in processLinkAproaches.

**Comment by namdre** [comment]
Those calls are also relevant for updating speed. The computed speed goes into effect if the junction model determines that the vehicle has to break at an upcoming intersection. I'm not convinced that a clear-cut separation of "real" speed update calls and "auxiliary"  speed update calls can be made. What prevents you from applying your internal reaction time calculations to all these calls?

**Comment by Domsall** [comment]
Thanks for reopening the issue. Problems involve the usage of vLinkWait and vLinkPass. As you pointed out, those variables are "created" in planMoveInterval and then for example used in processLinkAproaches. So when calculating the above mentioned stopSpeed in planMoveInterval, the CF-model doesn't know at this time of calculation, if this Speed update is going to be used for the next time step. But I would like to save the variables, that were the reason for the last Speed update (gap, leaderspeed, desired gap, etc.). The model also calculates a "wanted acceleration" in every step and compares this acceleration with the current one for a variable reaction time.

Going through the code again, I think that the second part can be implemented in finalizeSpeed by overriding the previous calculated speed with the one from the variable reaction time and add Errors there.
Untill now I checked if the stopSpeed/followSpeed call would result in an updated speed. If an update would occur, the speed was calculated using the respected values from the last update or with the new values when the reaction time was reached. When a call to stopSpeed/followSpeed resulted in a lower acceleration than the last call (during one time step), this was considered to be the reason for the next speed update and the last variables were overwritten. I thought this was the prefered method, as the output would always be the actual speed value the vehicle would achieve in the next step with estimation errors, driving errors, reaction time, etc. and not the speed the vehicle could achieve if it would update in every time step (without reaction times). As you mentioned, I now think that the calculations in planMoveInterval are somewhat a "this would happen when...".
I hope you understand what I am trying to explain.

**Comment by namdre** [comment]
I hope I do. I do agree with the description that the calculations in planMoveInternal are of the type "this would happen when". 
You might want to treat followSpeed and stopSpeed differenty though. The former is always called in response to an observed leader vehicle whereas the latter is computed in a more hypothetical way.

**Comment by namdre** [comment]
Were you able to solve your problem?

**Comment by Domsall** [comment]
unfortunately not. I tested a few different implementations and ideas, but I always rely on the variables that were the reason for the speed update in that step: the gap, the leaderSpeed and the information if the vehicle needs to stop oder is following (freeSpeed is like following someone who is far away in my case, I just change the desired velocity to the targetSpeed here). Is it possible with reasonable efforts to add code for saving the above mentioned variables? They could be saved into the MSVehicle class or in the vehicle State. The variables could then be fetched in finalizeSpeed via the MSVehicle class without changing the Input-Parameters.

**Comment by namdre** [comment]
You can easily do this in your own model code because there is already support for saving vehicle-specific data from within the car following model. Please take a look at MSCFModel_IDM and all code involving `VehicleVariables`

**Comment by Domsall** [comment]
I already use CF-model VehicleVariables. I actually started off with the IDM model implementation in SUMO, but I had a hard time differentiating between followSpeed calls that come into effect right away and stopSpeed calls that are used to check the possiblity of braking.
To sum up my understanding of your recommendations:
- During one time step the variables of each call to followSpeed/stopSpeed should get stored into respective vectors.
- In finalizeSpeed the model would then check which entry was responsible for the speed update (some kind of calculatedSpeed[X]==wanted_speed+-NUMERICAL_EPS).
- After finalizeSpeed the vectors get emptied again.

Two last questions then arise: Does the speed get manipulated on the way so that the calculated speed in followSpeed/stopSpeed doesn't match the Input speed in finalizeSpeed? And are the above mentioned steps the intended procedure (also regarding computation time and storage)?

**Comment by namdre** [comment]
- if there is not interaction with a junction, the call to followSpeed / freeSpeed that results in the lowest speed value is responsible for the speed update and will be passed to finalizeSpeed. Lets call this v1
- if the vPos value that is passed to finalize speed is lower than v1, it means that one of the calls to stopSpeed must have been responsible. The only way to figure out which one is to compare vPos to the stored result values of all stopSpeed calls. Actually, you could also access MSVehicle::myLFLinkLanes which stores all the stopSpeeds (myVLinkWait) and distance for all upcoming links. I would not mind giving MSVehicle an function to hand out that data.
- in MSBaseVehicle::finalizeSpeed (which you should call in your own version of finalizeSpeed) the speed may be further reduced to account for lane-changing interaction or planned stops

**Comment by Domsall** [comment]
that sounds perfect, then I'll just check if vPos is one of the myVLinkWait and get the according distance
