### ISSUE TITLE
created data element is invisible

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#7643]
to reproduce:
- load some data
- enter either edgeData or edgeRelation mode
- select data attribute other than `<all> `
- create new element with empty parameters
- new element is invisible due to the data attribute filtering

suggested solution:
- when selecting a data attribute other than `<all`> and the default parameters are empty, change the default parameters to `<attr>=0`
- when creating a new data element, surround it with a dotted shape

**Comment by palvarezlopez** [comment]
Fixed
