### ISSUE TITLE
function "getContextSubscriptionResults" returns None

### ISSUE THREAD

**Issue by Hans-Lan** [eclipse/sumo#7649]
In which condition does the function "traci.vehicle.getContextSubscriptionResults()" return None?
my code is:
`self.veh_info_dict = traci.vehicle.getContextSubscriptionResults('ego')`
Our simulation was shut down in some point because this function return None while many cars still in simulation.

**Comment by behrisch** [comment]
Can you please give more information about the sumo and python version you are using?

**Comment by Hans-Lan** [comment]
> f

sumo - 1.60
python - 2.7

**Comment by behrisch** [comment]
If there are no subscription results for the given vehicle, this function returns None. This changed in version 1.7. Now it returns an empty map. Maybe the vehicles are not in range?
