### ISSUE TITLE
ignore-junction-blocker is not working as intended

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#7650]
As soon as a junction foe is "inTheWay", it cannot be ignored. This goes against the original intended semantic of resolving any kind of junction  deadlock with this option.

When option **--collision.check-junctions** is set, collisions should be ignored while moving "through" an ignored foe.

**Comment by vespialis** [comment]
any updates on this?

**Comment by namdre** [comment]
was broken in 1.0.0
