### ISSUE TITLE
implausible taxi rides

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#7651]
routed personTrips in an intermodal network yield plans that alternate repeatedly between walking and taxi.
Probably some sort of "embarking" penalty is needed.

Option name: **--persontrip.taxi.waiting-time**

The given time is added applied when entering a taxi and is reflected in the final travel time estimate.

**Comment by namdre** [comment]
starting in a taxi still does not use the waiting time (hence one failing duarouter test 'longTaxiWait')

**Comment by rummel123** [comment]
Entry in sumo documentation for --persontrip.taxi.waiting-time is missing
