### ISSUE TITLE
SUMO reports wrong cumulated waiting time after loading simulation step

### ISSUE THREAD

**Issue by mtreca** [eclipse/sumo#7657]
This issue is pretty easy to reproduce:

- Run a given traffic scenario for around 50 iterations and print the accumulated waiting time of all vehicles at every time step.
- Run the same traffic scenario, but save and load the simulation step between each time step.

The continuous simulation reports a waiting time of around 338.0 for my scenario, and around 17.0 for the save-and-load case.

Originally mentioned in issue #7020

**Comment by namdre** [comment]
Vehicle waiting time is stored as part of the vehicle state and should be restored correctly so this deserves investigation.

**Comment by mtreca** [comment]
Do you need logs, my SUMO version or simulation files? I can provide you with those but it should be easy to reproduce in a simple simulation setting.

**Comment by mtreca** [comment]
@namdre I uploaded the script, network and trip files I am using to reproduce this issue on this gist: https://gist.github.com/mtreca/99e604570f56f7e057fc88c8a2e519da

**Comment by namdre** [comment]
Vehicle waiting time is stored (easy because it's a single number) but accumulated waiting time is not stored in the state at the moment. 
(Accumulated waiting time is computed over a given time horizon which requires that historical data for that time horizon is stored within the vehicle and needs to be saved as part of the simulation state)

**Comment by namdre** [comment]
@mtreca If your project allows it, you could use getWaitingTime() instead of getAccumulatedWaitingTime()

**Comment by mtreca** [comment]
@namdre Thanks for the feedback, this is what I ended up doing. I compared the two same scenarios using getWaitingTime() (one with save and load, one with continuous) and the values seem to match. Should I close this ticket then?

**Comment by namdre** [comment]
The ticket must stay open because there really is a bug concerning getAccumulatedWaitingTime
