### ISSUE TITLE
Bicycle turn left modification

### ISSUE THREAD

**Issue by Jianhua-Jiang** [eclipse/sumo#7663]
I have been able to modify the left turn path of the bicycle into two stages, as shown in #4252. But I also hope that the bicycle can turn left like pedestrian, stop after the first stage, and wait until the green light of the second stage lights up before passing the second stage. What method or function can be used to achieve？Thanks！！

**Comment by namdre** [comment]
see the updated documentation at https://sumo.dlr.de/docs/Simulation/Bicycles.html#indirect_left_turn
