### ISSUE TITLE
allow platform independent syntax for python tools that read additional xml attributes

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#7667]
possibility: always use single-quote for the inner quotes and replace them with double-quote on writing. (Alternative solution to #7581).

`randomTrips.py --trip-attributes "modes='public' color='red'"`

Reason: platform independent example commands in tutorial slides

**Comment by namdre** [comment]
@behrisch: in my test, the windows scheme of using escaped double quotes also works on linux. Do you remember why we did not use this syntax on both platforms? 
`randomTrips.py --trip-attributes "modes=\"public\" color=\"red\""`

(https://github.com/eclipse/sumo/blob/0baeb4bee16cc0d9d83fe6fd64c01a34302bf0f3/tools/osmWebWizard.py#L90-L101)

**Comment by behrisch** [comment]
No
