### ISSUE TITLE
Adjust the position of the division between the two stages of left turn

### ISSUE THREAD

**Issue by Jianhua-Jiang** [eclipse/sumo#7671]
Left-turning bicycles may move in two stages 1. move straight across 2. turn 90° left and then move straight across. The left-turn connection line in NETEDIT has a short line. Does that represent the dividing line between the two stages? In the actual application process, the first stage was found to be very short. How to adjust the position of this short line between the first stage and the second stage？

**Comment by namdre** [comment]
Yes. The thin orthogonal line represents the division between the two stages. You can modify this by setting attribute 'contPos' fir the connection (offset from connection start)
