### ISSUE TITLE
taxi simulation with sumo-gui differs from sumo

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#7674]
probably a set or map with pointers and unstable sorting is involved

**Comment by behrisch** [comment]
Does this show up in one of the regular tests?

**Comment by namdre** [comment]
No. A testcase is in the bugreports folder. It's the same scenario that also shows #7662

**Comment by namdre** [comment]
one thing I noticed: When configuring persons to be picked up at stops, the persons are registered as waiting at the busStops but since the taxi stops target a lane rather than a stop, the person is never removed from the stop. This leads to lots of stale pointers and is probably responsible for the issue when a transportable pointer is reused and then found during map-lookup.
