### ISSUE TITLE
vehicles wait side by side for TLS in a lane in the sub-lane model

### ISSUE THREAD

**Issue by Jianhua-Jiang** [eclipse/sumo#7678]
When the sub-lane model is used, cars will wait side by side for the traffic light signal in the same lane at the intersection, but this is not allowed in the traffic laws. Is there a way to use the sub-lane model only for pedestrians and bicycles? , Not in motor vehicles.

**Comment by namdre** [comment]
you can set lcLaneDiscipline="1" for the car type which should avoid this behavior.

**Comment by Jianhua-Jiang** [comment]
> you can set lcLaneDiscipline="1" for the car type which should avoid this behavior.

Thanks for your suggestions. However, after I set lcLaneDiscipline="1" for the car type, there will still be two vehicles waiting for TLS in the same edge. As shown in the following two pictures.

Figure 1:  http://m.qpic.cn/psc?/V50FpksP4HKBAH2mqbNx3Is8Fg3QfQqZ/45NBuzDIW489QBoVep5mccjvy0dRTEJWzQzK9DipPizKw0g0idT.38fAPJ2IxWy4ehcM7CZbqQyeGG39HydmzVlkXqCeqSCA9wYIUwQs6R4!/b&bo=SwKbAUsCmwEDGTw!&rf=viewer_4
Figure 1:  http://m.qpic.cn/psc?/V50FpksP4HKBAH2mqbNx3Is8Fg3QfQqZ/ruAMsa53pVQWN7FLK88i5mnY*SPw9DckCUCnI6zmjys2NYQ6*R3e*xrHSdI*yGiI*.mFYZxr0QQLq3z5HfZDjfwgndSeOYOi5hJ2lthw4fQ!/b&bo=MQSEAjEEhAIDCSw!&rf=viewer_4

Is there any other solution? I would be very grateful if you could provide valuable suggestions. THAKS!

**Comment by namdre** [comment]
Did you maybe change the value of `latAlignment` ? In our tests it works when this value is left at its default ("center"). 
If you did not change this value, please attach an example scenario that reproduces those situations.
