### ISSUE TITLE
Driver state parameters are not reflected to the simulation results.

### ISSUE THREAD

**Issue by khibuya** [eclipse/sumo#7679]
I chenge driver state parameter described below, but simulation result does not change.
<https://sumo.dlr.de/docs/Driver_State.html>

I use following driver.rou.xml as one of input file for the simulation. 
Despite major changes of driver state parameters such as "initialAwareness, errorTimeScaleCoefficient, errorNoiseIntensityCoefficient, speedDifferenceErrorCoefficient, headwayErrorCoefficient", the simulation returns the same results as the default parameter. 

## driver.rou.xml

<img width="638" alt="driver rou xml" src="https://user-images.githubusercontent.com/46508903/95733674-6d7a0e80-0cbd-11eb-95e4-70e036ca3288.png">
<routes>
    <vType color="1,0,0" carFollowModel="Krauss" id="EV" maxSpeed="16.66" sigma="0.0" speedDev="0" tau="1.0">
        <param key="maximumPower" value="1000" />
        <param key="vehicleMass" value="1600" />
        <param key="stoppingTreshold" value="0.1" />
        <param key="has.driverstate.device" value="true" />
    </vType>
    <route edges="-59429851#2 ・・・ -5809244#1" id="MyRoute" />
    <vehicle depart="0" id="e_veh0" route="MyRoute" type="EV">
        <param key="initialAwareness" value="5.0" />
        <param key="errorTimeScaleCoefficient" value="500.0" />
        <param key="errorNoiseIntensityCoefficient" value="2.0" />
        <param key="speedDifferenceErrorCoefficient" value="0.30" />
        <param key="headwayErrorCoefficient" value="1.5" />
    </vehicle>
</routes>

## test.sumocfg

<img width="274" alt="test sumocfg" src="https://user-images.githubusercontent.com/46508903/95733691-736fef80-0cbd-11eb-902a-4214e3f48674.png">

<configuration>
    <input>        
        <net-file value="test.net.xml" /> 
        <route-files value="driver.rou.xml" />
     </input>
     ・
     ・
</configuration>

How can I use driver state collectly ??

**Comment by m-kro** [comment]
Firstly, you have to add the device to your vType or vehicle. Add this line before the other param tags:
`<param key="has.device.driverstate" value="true"/>`
See [device doc](https://sumo.dlr.de/docs/Definition_of_Vehicles,_Vehicle_Types,_and_Routes.html#devices).

**Comment by khibuya** [comment]
@m-kro 

I check the result using traci.getSpeed("e_veh0"), and the result was completely the same speed of 「default driver state」 and 「parameter changed one」, at all time steps (also fcd-output).

I use Krauss as carFollowmodel, considering the following remarks.
#6330
and use the same random seed at both experiments.

Could you show me driver definition file?? thanks

**Comment by namdre** [comment]
initialAwareness should be in [0, 1] and must be less than 1 to affect driving behavior.
