### ISSUE TITLE
sumolib polygon/shape reader - potential unwanted snippet snuck in? 

### ISSUE THREAD

**Issue by gprichter** [eclipse/sumo#7682]
using the referenced sumolib module **to load a taz file**,
I **encountered an error** on read while the **color** attribute (python string "blue" in that case) was **processed**.

https://github.com/eclipse/sumo/blob/3c4997f682db117fd9ea2b7ad0ca098e420bec49/tools/sumolib/shapes/polygon.py#L60

it seems likely to me, that some pasting mishap took place.
the `.toXML()` is probably misplaced here.

**Comment by namdre** [comment]
@behrisch do we even need the shapes module anymore or should we remove it and suggest the generic xml reader?

**Comment by behrisch** [comment]
edgesInDistricts is using it but that seems to be the only place at least in sumo/tools. So yes removing (or at least deprecating) seems to be a good option
