### ISSUE TITLE
Improving the Kerner cfmodel by stochastic components

### ISSUE THREAD

**Issue by Kitsunow** [eclipse/sumo#7683]
I have a few questions about the Kerner car-following model as implemented in SUMO:

1. On which model is the cfmodel Kerner based on? The continuous one? The acceleration time delay model? The stochastic one? The KKW CA? I guess it's the discrete stochastic one, but it lacks much of the models described rules such as random acceleration for slow start. 
2. What does phi stand for in the model and what does it achieve?
3. Is it somehow possible to cache old speed values in the VehicleVariable-object and use them only once per simulation step? I saw that followSpeed and stopSpeed are called mutliple times per simulation step, so i can't figure out how to implement the state of motion calculation from Kerner, which is mandatory for the stochastic model.

**Comment by namdre** [comment]
Sorry for the lack of immediate feedback. 
Did you arrive at the answers yourself or did you give up on your project?

**Comment by Kitsunow** [comment]
Kind of. For the first question, i just assumed an earlier version of the Kerner-Klenov model with less specifics on the stochastic part. I'm currently implementing and testing those to verify the implementation adheres to the most current model description of Kerner-Klenov.

Question 2 and 3 are obsolete now, since i do not use phi in my implementation anyways and the caching of the value is not necessary anymore.
