### ISSUE TITLE
Sometimes the angle of newly added vehicles are not correct

### ISSUE THREAD

**Issue by ykwd** [eclipse/sumo#7686]
I found that when the vehicles are added into the network via libsumo's API: Vehicle::add , sometimes their angles are not correct.

For example, the angles of the first few steps of an added vehicle with a non-zero initial speed is: 142.06, 88.86, 88.86, 88.86, 88.86. So obviously the angle of the first step is not correct.

For the same vehicle, with the same initial position but zero speed, the angles of the first few steps are: 142.06, 124.81, 102.74, 88.86, 88.86. So the angle of the first 3 steps are not correct.

On the other hand, when the same vehicle is not newly added, even though it arrives at the same position with the same speed, the angles are all correct.

I am not sure if there is a bug. If you can tell me which part in the source code decides the initial angle, I can help to check as well. Thanks

**Comment by behrisch** [comment]
How did you retrieve the angle, is this fcd output? And this does not happen when you insert the vehicle with an XML file? The code is in MSVehicle::computeAngle https://github.com/eclipse/sumo/blob/master/src/microsim/MSVehicle.cpp#L1284 which is called from MSVehicle::enterLaneAtInsertion

**Comment by ykwd** [comment]
I have identified the root cause is that the newly inserted vehicles may have incorrect myFurtherLanes properties. But later I found that it seems like this bug has already been fixed on the newest sumo version, while I was using sumo 1.5.0 before. So I will close this issue. Thanks for your kind comment.
