### ISSUE TITLE
duarouter - route depart times value integer overflow while processing trips file

### ISSUE THREAD

**Issue by tipech** [eclipse/sumo#7687]
Routes  were being generated from a set of pedestrian trips with particularly large depart timestamps (they're meant to be used in sumo with 60 second intervals). At some point (well before the SUMO max), duarouter stops using the initial trip departure times, but instead reduces them by incrementally larger amounts, reversing the sorted order mid-way.

No random-routing or similar parameters were used. The first timestamp where this starts happening is 2147447, which is 1000*the maximum size of an integer, therefore it looks like an overflow issue. In the screenshot below it's visible where the reversal happens.

![duarouter_bug_stdout](https://user-images.githubusercontent.com/7738957/95932867-f3b85280-0d9a-11eb-908d-5836c5293cec.png)

Attached is a zip with the .net.xml and trips.xml files to reproduce: [2k.zip](https://github.com/eclipse/sumo/files/5375024/2k.zip)

**Comment by behrisch** [comment]
It works here. Can you please report your platform and sumo version.

**Comment by namdre** [comment]
The 1000*maxInt limit used to be a problem for sumo versions before 0.24.0
