### ISSUE TITLE
tools/ptlines2flows stopped working

### ISSUE THREAD

**Issue by Tan-Guo** [eclipse/sumo#7690]
I have generated well-defined ptlines.xml and ptstops.xml. But every time when I use tools/ptlines2flows.py, it breaks down, there is a window shows:

sumo.exe has stopped working
A problem has occurred, causing the program to stop working properly. If there is an available solution, Windows will close the program and notify you.

and sometimes the terminal returns:
Traceback (most recent call last):
  File "ptlines2flows.py", line 359, in <module>
    main(get_options())
  File "ptlines2flows.py", line 355, in main
    createRoutes(options, trpMap, stopNames)
  File "ptlines2flows.py", line 296, in createRoutes
    for vehicle in sumolib.output.parse(options.routes, 'vehicle'):
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\sumolib\xml.py", line 253, in
parse
    for _, parsenode in ET.iterparse(_open(xmlfile, None)):
  File "C:\Users\lenovo\Anaconda3\lib\xml\etree\ElementTree.py", line 1227, in i
terator
    root = pullparser._close_and_return_root()
  File "C:\Users\lenovo\Anaconda3\lib\xml\etree\ElementTree.py", line 1274, in _
close_and_return_root
    root = self._parser.close()
xml.etree.ElementTree.ParseError: unclosed token: line 3, column 0

it puzzles me a lot, and your replies and suggestions are highly appreciated!

**Comment by behrisch** [comment]
Please report your sumo version and provide your inputs if possible.

**Comment by Tan-Guo** [comment]
Version: 1.6.0

I have finally located the problem: some ptlines cannot be imported. if delete these items, the "sumo-gui.exe has stopped working problem" would no longer exist, and the program can continue.

But I also found another problem:

ptlines2flows.py only recognizes the busStops placed in the outermost lane (i.e. the lane ID must be zero). if not, it would probably stop working again. However, in sumo-gui simulation, the busStops can be placed at any lane on the edge.

Here are my inputs:
the network is osm.net.xml;
the ptlines file is busLines.xml;
In busSops_raw.xml, all busStops are placed in lane 0.  In busStops.xml, the busStops are placed in more appropriate lanes of the edge. However, if we import busStops.xml into ptlines2flows.py, the sumo-gui would stop working. Currently, we can only import busStops_raw.xml into ptlines2flows.py.

(To make ptlines2flows.py recognize Chinese characters and prevent encoding problems (actually, the current version cannot recognize Chinese due to encoding problems), I made a slight change of ptlines2flows.py at line 119, 120, 141, 143, i.e. add encoding = 'utf-8'.)

You can change the ptlines2flows's ptstops input from busStops_raw.xml to busStops.xml, and the SUMO-GUI would stop work, but the only difference between the two documents is the lane of each stop.

 
[Github #7690.zip](https://github.com/eclipse/sumo/files/5395109/Github.7690.zip)

**Comment by namdre** [comment]
The problem is triggered when defining trips with stops on internal edges.
