### ISSUE TITLE
Why use VAR_ POSITION_ 3D The height to obtain the position of the vehicle on the viaduct is always 0 ？

### ISSUE THREAD

**Issue by radiateboy** [eclipse/sumo#7697]
Why use VAR_ POSTION_ 3D The height to obtain the position of the vehicle on the viaduct is always 0 ？

**Comment by behrisch** [comment]
It works here. Please check whether your network really contains the elevation. The easiest way to check is to open the net in sumo-gui and right click on a lane where you expect elevation and look whether a height is reported in the context menu.
