### ISSUE TITLE
pedestrian model at the intersection is abnormal

### ISSUE THREAD

**Issue by Jianhua-Jiang** [eclipse/sumo#7703]
At the walkingareas, the pedestrians will make a circle before passing. Ps: Right turn is normal. May I ask what caused it？

**Comment by behrisch** [comment]
Walking areas only roughly approximate the movement of the persons, especially with complex junction shapes. So if you mean by a circle that the movement on the walking area looks strange, this is "normal". They should however not go once around the whole junction before turning right.

**Comment by Jianhua-Jiang** [comment]
> Walking areas only roughly approximate the movement of the persons, especially with complex junction shapes. So if you mean by a circle that the movement on the walking area looks strange, this is "normal". They should however not go once around the whole junction before turning right.

What I mean is that some pedestrians will turn a circle and then go straight or turn left in the WALKINGARES of the intersection (the four corners of the intersection). The circle area is similar to the size of the walkingareas, and the other part is normal. The scenes I built is a simple intersection, so this phenomenon is abnormal, right? THANKS!

**Comment by namdre** [comment]
From that description it sounds as if you are using vehicles with vClass="pedestrian" instead of persons with `<walk>` elements.  In our tests, the persons walk straight across the walkingarea.

**Comment by Jianhua-Jiang** [comment]
> From that description it sounds as if you are using vehicles with vClass="pedestrian" instead of persons with `<walk>` elements. In our tests, the persons walk straight across the walkingarea.

what should I do?

**Comment by namdre** [comment]
Use osmWebWizard to define a scenario with pedestrian. Then look at the scenario definitions to understand how pedestrians should be defined. Also, consider the documentation: https://sumo.dlr.de/docs/Specification/Persons.html
