### ISSUE TITLE
Regarding exact positioning of traffic lights in OSMWebWizard

### ISSUE THREAD

**Issue by mainakchain** [eclipse/sumo#7708]
How are we getting the **exact location** and **lane** for each traffic light displayed on the _sumo-gui_ simulator after using OSMWebWizard? Is it exact afterall or just provides with a approximate notion of the placement of traffic lights in the streets?

@namdre @palvarezlopez

**Comment by behrisch** [comment]
The exact position of the pole is not saved in the SUMO network. you can only retrieve the position and shape of the junction.
