### ISSUE TITLE
Osm web wizard not generating .net files

### ISSUE THREAD

**Issue by subhagakannan** [eclipse/sumo#7709]
Hello all,
When I am trying to generate .net files from OSM web wizard of SUMO i get the following error:
![Capture](https://user-images.githubusercontent.com/70543709/96917053-a9288b80-14a8-11eb-997c-24031d116095.PNG)

Can anyone pls help me?? 
Thanks in advance

**Comment by behrisch** [comment]
Please try installing certificates using: `pip install python-certifi-win32`

**Comment by subhagakannan** [comment]
Thankyou for the information. I am able to generate now.
