### ISSUE TITLE
checkbox labels missing in netedit

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#7710]
the labels for show grid, select lanes etc. are currently not shown here

**Comment by palvarezlopez** [comment]
@behrisch It's part of #7444

**Comment by behrisch** [comment]
But I suppose it would not hurt much to leave the labels in place until the icons are there?

**Comment by palvarezlopez** [comment]
@behrisch I thought that Icons was finished on Friday. I fix it.

**Comment by behrisch** [comment]
Thanks!
