### ISSUE TITLE
make gzipped files the default for osmGet / webWizard

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#7713]
at least for the raw osm data

**Comment by namdre** [comment]
people may not be aware that gzipped files can be read directly by the SUMO applications. This would not be a problem when gzipping the raw osm data within the webwizard context but might be confusing when osmGet is used by itself or when other generated files are gzipped.

**Comment by behrisch** [comment]
> people may not be aware that gzipped files can be read directly by the SUMO applications. 

But this seems rather a documentation issue to me. The question is: Is it more beneficial to have files easily editable or small. And at least for the files which are not meant to be edited manually (raw osm and maybe the sumo net) I would go for gzip.

**Comment by namdre** [comment]
Yes. It boils down to a documentation issue but we should not underestimate how hard it can be to solve these (-:
I think that only files not meant for editing should be gzipped by default. And still I would only want to gzip networks in a context where the corresponding .sumofg is generated as well (webWizard).

**Comment by behrisch** [comment]
Sounds like a plan.
