### ISSUE TITLE
Hardware connection with SUMO

### ISSUE THREAD

**Issue by subhagakannan** [eclipse/sumo#7715]
Dear all, 
I want to stream data to another device (example: D-space simulator or any other HIIL) from SUMO. I am not able to figure out how to interface an external device with SUMO using TRACI. Can anyone pls help me?

Thanks in advance.

**Comment by behrisch** [comment]
TraCI can easily be used over a TCP/IP network (in fact it always uses a network connection even if run on the same machine). So you need to enable a network connection between the two machines. Then you can run sumo on one machine and the traci client on the other. You specify the port where sumo listens when starting sumo and the host name and port number when starting the traci client.
