### ISSUE TITLE
Problem for traci.edge.getLastStepOccupancy(self, edgeID)

### ISSUE THREAD

**Issue by Shiyunyang-seu** [eclipse/sumo#7716]
Hi, occupancy is divided into time occupancy and space occupancy. I consider that the valuecalculated by this function is  time occupancy and what is the specific calculation formula of this value? In addition, whether can add a space occupancy calculation (the total length of vehicles on the edge / the length of edge). Thanks in advance!

**Comment by namdre** [comment]
getLastStepOccupancy returns the space-occupancy as a fraction in [0,1]. (this is the net-occupancy excluding gaps so you will typically not see a value of 1.0).
