### ISSUE TITLE
Sublane model problem（vehicles overlap）

### ISSUE THREAD

**Issue by Jianhua-Jiang** [eclipse/sumo#7718]
When I use the Sublane model, vehicles will overlap at the intersection, as shown in the figures below.
(Figure1)_http://m.qpic.cn/psc?/V50FpksP4HKBAH2mqbNx3Is8Fg3QfQqZ/ruAMsa53pVQWN7FLK88i5sDEKvl.yjMk358dU112sQ*N3bacmyEuMJu6UHmNlVrykN2wOSZYEXEiz7TuvDc8lgUH*8Qvij.D9BJvLWfkG*4!/b&bo=XwSPAl8EjwIDCSw!&rf=viewer_4
(Figure2)_http://m.qpic.cn/psc?/V50FpksP4HKBAH2mqbNx3Is8Fg3QfQqZ/45NBuzDIW489QBoVep5mcXZi5xmBFs2dnGCgsrTWtQ8pTjedZNtLYJmeEJvRGx89rib4Cd.NeeVnYX*ljwnVApRFYy7erW9A85Z8WBx6obo!/b&bo=IgTBAiIEwQIDGTw!&rf=viewer_4

It is explained in issue #6305：Visual overlap may result when you override edge lengths (i.e. define an edge with geometry length of 50m and then declare it's length to be 100m). Actual overlap over vehicles in the simulation results in a collision.

When I must declare edge lengths as a standard length, how should I solve this problem?
Draw an edge longer than the length I deeclare, and then declare?

**Comment by namdre** [comment]
The overlap in your screenshot is not due to custom edge lengths which were discussed in #6305.
It looks like a bug that was fixed in an earlier sumo version.
What version are you using?
Can you attach a small sample scenario that demonstrates your issue?

**Comment by namdre** [comment]
closing due to lack of response. Reopen if still relevant.
