### ISSUE TITLE
The program cannot run automatically with "traci"Module

### ISSUE THREAD

**Issue by ppt067-hub** [eclipse/sumo#7719]
I try to learn the traci through the "traci_tls" demo, it loads the net_file but does not run. It needs me pressing the "play" button to run the program.
My sumo version is 1.7.0 and  python is 3.7.8
  
![issue](https://user-images.githubusercontent.com/64182804/97405767-246bc080-1933-11eb-9453-a854dcff05f7.PNG)

**Comment by ppt067-hub** [comment]
I find that traci.simulationStep does not run

**Comment by namdre** [comment]
The default behavior is to wait for user input (pressing the play button).
You can add the sumo option `--start` to make the gui start automtically.

**Comment by ppt067-hub** [comment]
Thank you for your reply,but I don't know where add this option --start

**Comment by behrisch** [comment]
This is  command line option to sumo-gui so add it to your script where you start sumo-gui, here: https://github.com/eclipse/sumo/blob/master/tests/complex/tutorial/traci_tls/runner.py#L126
