### ISSUE TITLE
file:///usr/share/sumo/tools/webWizard/index.html does not show in browser when python osmWebWizard.py is run in tools folder

### ISSUE THREAD

**Issue by jmpinder** [eclipse/sumo#7720]
john@john-dev:/usr/share/sumo/tools/webWizard$ ls -l
total 64
drwxr-xr-x 2 root root  4096 Oct 16 10:43 images
-rw-r--r-- 1 root root  4895 Sep  8 19:42 index.html
-rw-r--r-- 1 root root   866 Sep  8 19:42 __init__.py
-rw-r--r-- 1 root root  1482 Sep  8 19:42 lib.js
-rw-r--r-- 1 root root 15862 Sep  8 19:42 script.js
-rw-r--r-- 1 root root 22950 Sep  8 19:42 SimpleWebSocketServer.py
-rw-r--r-- 1 root root  2618 Sep  8 19:42 style.css
john@john-dev:/usr/share/sumo/tools/webWizard$ cd ..
john@john-dev:/usr/share/sumo/tools$ python osmWebWizard.py
Gtk-Message: 08:17:26.548: Failed to load module "canberra-gtk-module"
Gtk-Message: 08:17:26.550: Failed to load module "canberra-gtk-module"

**Comment by namdre** [comment]
Can you try to navigate to that file via the file->open dialog of your browser?

**Comment by jmpinder** [comment]
I can open it in Firefox, but not in chromium. Does it have to be opened via running osmWebWizard.py to work properly with sumo or can I open the index.html in firefox each time and resume the second tutorial without running python osmWebWizard.py?

**Comment by jmpinder** [comment]
Hi Jakob,
Thanks for getting in touch, im new to SUMO and would like to get started with it. I can open it in Firefox, but not in chromium. Does it have to be opened via running osmWebWizard.py to work properly with sumo or can I open the index.html in firefox each time and resume the second tutorial without running python osmWebWizard.py?

Regards,
John

**Comment by namdre** [comment]
It's a browser security issue I think. 
Opening it in Firefox after running osmWebWizard.py should work just fine.
