### ISSUE TITLE
GLOSA device

### ISSUE THREAD

**Issue by Domsall** [eclipse/sumo#7721]
Hello,
during the poster presentation of "Simulation of automated and connecting driving traffic in the test field Hamburg" the question arose, if SUMO already has a kind of GLOSA or at least traffic light information device. Audi for example use a transition graph to optimize the information for the driver. This is maybe a difficult task to implement with SUMO's traffic light definition, but @namdre your colleagues meant about 5 years ago you already worked a lot on that topic.
Is there such a device already in SUMO? What have you already done in SUMO regarding traffic light optimization and driver information?
If such a system doesn't exist yet, I would probably work with a student to get it implemented, as I am very interested in this field, but don't have the time to fully do it myself.

Thanks in advance!

**Comment by namdre** [comment]
I did implement a GLOSA algorithm as a traci script and we've been using this for quite some time. Putting it into a vehicle device to make it work with fixed traffic light controls sounds like a reasonable plan.
In my work I came up with the AGOSA algorithm which combines GLOSA with an actuated controller wich I should probably put into sumo eventually. You can read about it here:https://elib.dlr.de/82952/

**Comment by namdre** [comment]
Currentlly, no SPAT messages are simulated and the V2X communication is implicit: The device "looks" directly into the signal plan when in the configured range. To hook in custom messages two additional pieces of code would be needed
- inventing a new tlLogic parameter or device option that disables the default behavior (making all traffic lights "silent")
- supporting a new parameter (vehicle.setParameter(vehID, "device.glosa.spat") to supply custom timing information via TraCI

**Comment by Domsall** [comment]
Thank you very much for the great work! That is the "logic implementation" I was looking for. Including SPAT messages and optimization algorithms for adaptive traffic lights can still be added later, when one needs the details.
I'm working on many different topics right now, but will get back with some tests and maybe results as soon as possible (But could still take a few months).
