### ISSUE TITLE
Nonzero exit code although successful execution

### ISSUE THREAD

**Issue by hoxovic** [eclipse/sumo#7722]
Hey,

This line in `generateContinuousRerouters.py` will always exit with non-successful status since `main()` implicitly returns `None`.
https://github.com/eclipse/sumo/blob/294ce9332e926f1fa359a7fdb699b0f9816272ed/tools/generateContinuousRerouters.py#L179

While not limited to docker, this prevents the script from being used when building an image unless the exit code is overridden.

**Comment by namdre** [comment]
Thanks!
