### ISSUE TITLE
how can I get the information around the ego vehicle whthin some area

### ISSUE THREAD

**Issue by ppt067-hub** [eclipse/sumo#7725]
I want to  get  the informations around the ego vehicle whthin some area (eg 100m),while I don't want to get all the informations in the scenario. How can I do it?

**Comment by behrisch** [comment]
The easiest way to do this is to use traci/libsumo with context subscriptions, see https://sumo.dlr.de/docs/TraCI/Interfacing_TraCI_from_Python.html#context_subscriptions
