### ISSUE TITLE
How to check if route is possible? 

### ISSUE THREAD

**Issue by zmajstorovic** [eclipse/sumo#7726]
Hello, I'm new to SUMO and I am currently working on simulation of urban traffic on a map downloaded from OSM and I have to create some traffic. 

Can you please advise me how to easily create routes between selected edges? I have source, destination and via edge and I would like to create routes based on that constraints. 

I tried to make a script in a python which randomly choose edges (from my list) and make traffic flow between those edges and I made this:
<flow id="flow_0" begin="0.00" from="-304907" to="-304467" via="-304533#1" end="3600.00" number="1800"/>

The problem is that not all routes are possible and SUMO returns error. Is there any way to verify routes that I generate with my python script? 

Any advices are welcome. 

Kind regards, 
Zeljko

**Comment by behrisch** [comment]
You can run duarouter on your resulting trips, like this:
`duarouter -n mynet.net.xml -r mytrips.rou.xml --ignore-errors -o myroutes.rou.xml`
The resulting route file will contain the valid routes. You can also use sumolib.net.getShortestPath to find a route, see https://sumo.dlr.de/daily/pydoc/sumolib.net.html. You might also want to look at randomTrips.py which does more or less what you did without preselecting the edges.
