### ISSUE TITLE
retrieve collisions between vehicles and pedestrians via TraCI

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#7728]
currently, the function `simulation.getCollidingVehiclesIDList` only returns vehicle-vehicle collisions.

@behrisch 
- should vehicles involved in a person-vehicle collision be retrieved with a separate function?
- is `simulation.getCollidingPersonIDList` a good name for the involved-person retrieval (maybe it's to suggestive of person-person collisions)?

**Comment by behrisch** [comment]
I would prefer something like getColliderIDs(types) where you can configure whether you want vehicles, persons or both.

**Comment by namdre** [comment]
But that would not allow a distinction between vehicle/vehicle collisions and vehicle/person collisions that happen in the same time step.
(Though admittedly we also cannot distinguish between participants of multiple simultaneous collisions with the current API).

I guess eventually we need something that returns a list of lists (participants per collision).

**Comment by behrisch** [comment]
Yes, returning a list of pairs would be better. But I would still allow for filtering for the collision "type". We could even externalize the internal determination of rear end vs frontal collision.

**Comment by namdre** [comment]
Yes. That would be nice. We could even flag "flank" collisions on junctions (frontal is only for opposite-direction driving and trains).

**Comment by behrisch** [comment]
OK, so getColliders could return a list of triples of the both ids and one of our infamous bitsets, where the bitset encodes whether the first and the second are a person or a vehicle and some more bits for the type of collision and we leave the filtering to the user?

**Comment by namdre** [comment]
Sounds good to me.

**Comment by behrisch** [comment]
Not that I want to start right now implementing it, but to round up the discussion: Should we go for a triple (so a 3-tuple also in the C++ implementation) or invent a new class?

**Comment by namdre** [comment]
Whichever makes it easier to have a smooth libsumo mapping (-:
 I prefer a class so the meaning of the 3 fields is more obvious.

**Comment by namdre** [comment]
@aloreggia. The fix is a bit more involved and I cannot give you a time frame for this.

**Comment by aloreggia** [comment]
Hi Jakob,
sorry for bothering you again, we are planning some simulations and thus we
would like to know if we can use SUMO for that or not.
I'm wondering whether you have some ideas when the solution for the issue
will be released.

Thank you for your attention to this.
Best regards,
Andrea

Il giorno mar 10 nov 2020 alle ore 12:24 Jakob Erdmann <
notifications@github.com> ha scritto:

**Comment by aloreggia** [comment]
Dear Jakob,
can you help in debugging the following problem?

SUMO_HOME=/Users/XXXX/Downloads/sumo/sumo/
Using the last version of SUMO, whenever I try to run the following code:

import os, sys
if 'SUMO_HOME' in os.environ:
tools = os.path.join(os.environ['SUMO_HOME'], 'tools')
sys.path.append(tools)
else:
sys.exit("please declare environment variable 'SUMO_HOME'")
import traci
import sumolib
t=traci.connect(27910)
for i in range(10000):
l=t.simulationStep()
t.simulation.getCollisions()


I got the following error:

Traceback (most recent call last):

  File "<stdin>", line 3, in <module>

  File "/Users/XXXX/Downloads/sumo/sumo/tools/traci/_simulation.py", line
400, in getCollisions

    return self._getUniversal(tc.VAR_COLLISIONS)

  File "/Users/XXXX/Downloads/sumo/sumo/tools/traci/domain.py", line 168,
in _getUniversal

    return _parse(self._retValFunc, varID, self._getCmd(varID, objectID,
format, *values))

  File "/Users/XXXX/Downloads/sumo/sumo/tools/traci/domain.py", line 173,
in _getCmd

    r = self._connection._sendCmd(self._cmdGetID, varID, objID, format,
*values)

  File "/Users/XXXX/Downloads/sumo/sumo/tools/traci/connection.py", line
180, in _sendCmd

    return self._sendExact()

  File "/Users/XXXX/Downloads/sumo/sumo/tools/traci/connection.py", line
97, in _sendExact

    raise TraCIException(err, prefix[1], _RESULTS[prefix[2]])

traci.exceptions.TraCIException: Get Simulation Variable: unsupported
variable 0x23 specified


Thanks in advance, best wishes

Andrea Loreggia

Il giorno mer 16 dic 2020 alle ore 16:53 Jakob Erdmann <
notifications@github.com> ha scritto:

**Comment by behrisch** [comment]
Please double check that you use a current development version of SUMO for the client _and_ the server. From your script it is not clear how the server is started. This functionality is not present in 1.8.0.

**Comment by aloreggia** [comment]
This is the version I'm using after downloading the gitHub package


sumo --version

Eclipse SUMO sumo Version 1.8.0

 Build features: Darwin-18.2.0 x86_64 Clang 10.0.0.10001044 Release Proj GUI

 Copyright (C) 2001-2020 German Aerospace Center (DLR) and others;
https://sumo.dlr.de


The server is started as follows:

sumo --step-length 0.05 -n test.net.xml -r
cars2_mod.rou.xml,pedestrians2.rou.xml --pedestrian.striping.dawdling 5
--remote-port 27910 --start -Q --collision.mingap-factor 50
--collision.check-junctions --collision.action warn

Il giorno mer 20 gen 2021 alle ore 11:41 Michael Behrisch <
notifications@github.com> ha scritto:

**Comment by aloreggia** [comment]
FIXED.
I downloaded and built a fresh copy of the repository. Now everything is
working.

Thank you for your help,
Andrea

Il giorno mer 20 gen 2021 alle ore 12:50 Andrea Loreggia <
andrea.loreggia@gmail.com> ha scritto:
