### ISSUE TITLE
Dynamically change the number of lane in an edge

### ISSUE THREAD

**Issue by HanwGeek** [eclipse/sumo#7735]
Can TraCI dynamically change the number of lane in an edge when running simulation step like this?
```python
traci.edge.setParameter("3to2", "type", "3L45")
```

**Comment by behrisch** [comment]
No. This would potentially involve a recomputation of the junction logic which is something only netconvert does. If you need lanes which are only part time available you should include them into the basic network and then adapt the permissions dynamically.

**Comment by XuanlinZeng** [comment]
> Can TraCI dynamically change the number of lane in an edge when running simulation step like this?
> 
> ```python
> traci.edge.setParameter("3to2", "type", "3L45")
> ```

Hello, what "3L45" is generally used to represent in the attributes of edges? Thank you for your help.
