### ISSUE TITLE
ModuleNotFoundError: No module named 'traci' in Google Colab

### ISSUE THREAD

**Issue by ishanrai32** [eclipse/sumo#7736]
This issue is probably an extension of #5844 to Google Colab.  
I have 2 python files; _main.py_ & _sim.py_. The file _main.py_ calls _sim.py_ for simulation and I'm importing traci in _sim.py_. When running it in anaconda, adding `sys.path.append(os.path.join(os.environ.get("SUMO_HOME"), 'tools'))` before `import traci` in _sim.py_ worked fine. How would the same thing work if I'm trying this in Google colab? The solution that worked offline doesn't work when I'm using it in Colab. I have declared the environment variable SUMO_HOME with `%env SUMO_HOME = "path to sumo in colab"`. I couldn't find this issue anywhere online, any help would be greatly appreciated.

**Comment by behrisch** [comment]
Just to have this clear. You get an import error but SUMO_HOME is set and is found? Can you print the sys.path just before the import and double check the traci directory is there?

**Comment by ishanrai32** [comment]
Yes, it's there. There doesn't seem to be anything off about that part. After spending some time, it seems to me that the issue is in finding the file 'sumo'. Somehow after installation, 2 sumo folders are created. One in usr/local/python and one in the content/my_folder which is the folder I was present in. I am looking into the directory structure and how the installation of packages works in Colab, which seems to be the catch.
One question: as Jupyter notebooks can run both Python and Linux commands, which method is preferable to install it in Google Colab?

**Comment by behrisch** [comment]
I would use the linux package manager so apt instead of pip if that is the question

**Comment by ishanrai32** [comment]
So, I have finally got it to work. As the errors in Colab showed, turns out installing Traci separately after installing SUMO is necessary. So for future references, here's what worked:
**First install SUMO**
`!add-apt-repository ppa:sumo/stable -y`
`!apt-get update -y`
`!apt-get install sumo sumo-tools sumo-doc`
**Install Traci**
`!pip install traci`
**Declare the environment variable, SUMO_HOME**
`import os`
`os.environ['SUMO_HOME'] = "/usr/share/sumo"`

**Comment by behrisch** [comment]
This is not a solution but rather a workaround. Doy ou have any idea why the sys.path modification mentioned above does not work?

**Comment by ishanrai32** [comment]
Yes, agreed it's just a workaround.  I had hit a dead-end, with the only clue being that I had to recall `traci` separately. I tried solutions available with this in mind and this one worked. Nope, I have no clue as to why that doesn't work. Probably somebody with more knowledge about the way Colab directories work could come up with something.

**Comment by sam99dave** [comment]
traci.exceptions.FatalTraCIError: Could not connect in 1 tries
FXApp::openDisplay: unable to open display :0.0

Can someone help with displaying a sumo simulation in Colab. I was trying out the sumo Traci tutorial using Colab. It seems that I'm missing something here.

**Comment by behrisch** [comment]
Colab probably does not allow GUI applications to be started. Try to run sumo instead of sumo-gui in your traci.start command.
