### ISSUE TITLE
add jmIgnorePedestrianProb to ignore pedestrians on a crossing or shared walkingArea

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#7741]
right now it is only applied in MSLink::opened but should also be applied in MSLink::getLeaderInfo when performing the pedestrian checks.

- related to #7717 as it might be useful to configure ignorance of pedestrians differently from ignorance of vehicles
- related to #8078 which allows vehicles to ignore other vehicles and pedestrians already on a junction
- related to #8205 which allows to ignore specific foe vehicle ids

**Comment by namdre** [comment]
whereas jmIgnoreFoeProb currently applies to foes that have not yet entered the junction (so they could still emergency-brake or simply keep standing to avoid a collisions) the proposed ignorance in `getLeaderInfo` might ignore objects that are already in the way so there is a profound difference.

Hence it would be better to add a new attribute for this.

**Comment by namdre** [comment]
@behrisch I am wondering on how best to encode a type-dependent probability map:

1) complexity is in the attribute value: `<vType ... ignoreJunctionFoeProb="myPedType,0.5 myCarType,0.2" />` (',' is already forbidden in typeIDs)
2) complexity is pushed into child elements 
```
<vType ...>
       <ingoreJunctionFoeProb type="myPedType" value="0.5"/>
       <ingoreJunctionFoeProb type="myCarType" value="0.2"/>
   </vType>
```
3) complexity is reduced and pushed into different attribute names `<vType ... ignorePedestrianFoeProb="0.5" ignoreJunctionFoeProb="0.2"/>

4) ???

**Comment by behrisch** [comment]
I vote for 2. This is explicit and similar to the style of adding specific values to edge types see #1800. Maybe we could also use generic parameters with key="ignoreJunctionFoeProb:type" here but my favourite is still 2.

**Comment by namdre** [comment]
ignoring specific pedestrians is almost working with #8205. The only thing that is missing is a change when calling the pedestrian model since it doesn't return the ids of blocking pedestrians by default, only a boolean blocked/notBlocked.

**Comment by namdre** [comment]
ignoring individual persons or types on junctions is working via #13057

**Comment by namdre** [comment]
ignoring pedestrians on crossings and walkingareas is working via #8078
