### ISSUE TITLE
rename TIME2STEPS to SECONDS2SUMOTIME

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#7742]
This conveys the intended conversion much better but it changes a lot of code, so we should discuss this first. Maybe we can also transform it into an (inline) function which would remove the need for ALLCAPS. Of course this applies for the inverse as well.

**Comment by palvarezlopez** [comment]
@behrisch We can define an structo SUMOTimeConv in which define all conversion functions (SPEED2DIST, STEPS2TIME, TIME2STEPS...) What do you think?

**Comment by behrisch** [comment]
No, actually I wanted to have this smaller and we decided today it is not worth the effort.
