### ISSUE TITLE
Connecting TraCI to another host

### ISSUE THREAD

**Issue by subhagakannan** [eclipse/sumo#7756]
Dear all, 
I am trying to start sumo GUI on another host using traci.connect(). I am not able to do so and getting an error like **Could not connect to TraCI server at 192.168.1.111:8813 [WinError 10060]**
Can anyone pls help me?
thanks in advance!

**Comment by subhagakannan** [comment]
I am using ethernet connection to set up connection between my two PCs. I want to use one as client and the other as server. I need to control the traffic in sumo gui on another pc from python script in one pc. But I am not exactly knowing what to do. Someone pls help me.

**Comment by behrisch** [comment]
You need to start sumo-gui first on the server (192.168.1.111 in your case). Make sure you have the configuration loaded which specifies the correct port (8813 in your case). Then start the client on the other machine. If it does not work check whether you can ping your server or connect to any other service running there (ssh?) and check whether there is a firewall running blocking port 8813.
