### ISSUE TITLE
How can I close the sumo-gui with traci

### ISSUE THREAD

**Issue by ppt067** [eclipse/sumo#7759]
I want to close the sumo-gui with traci's command, what can I do.

**Comment by namdre** [comment]
add sumo option '-Q' when calling traci.start([ ....]) and then the gui will close when calling  `traci.close()`

**Comment by ppt067** [comment]
Thank you for your reply. But I want to know  if it can be used with traic4matlab. if can how to use?

**Comment by namdre** [comment]
then add `<Q value="true">` to the .sumocfg file that is loaded by traci.
