### ISSUE TITLE
moveToXY command lets sumo-gui.exe crash with SUMO 1.7.0 and keepRoute=0

### ISSUE THREAD

**Issue by schottb85** [eclipse/sumo#7763]
Using the attached road network, a moveToXY command fails with option keepRoute=0. sumo-gui.exe is crashing without a proper exception. The same network and moveToXY command was working with SUMO 1.6.0 and earlier releases. Using keepRoute option 1 or 3, the moveToXY command is working well, however, we require to use option keepRoute = 0.

Find attached, the required files.
note: please remove the txt file ending (just used to be able to attach the files in github)

[test.net.xml.txt](https://github.com/eclipse/sumo/files/5493874/test.net.xml.txt)
[test.sumo.cfg.txt](https://github.com/eclipse/sumo/files/5493875/test.sumo.cfg.txt)
[test_demand.rou.xml.txt](https://github.com/eclipse/sumo/files/5493876/test_demand.rou.xml.txt)
[vehUrban.rou.xml.txt](https://github.com/eclipse/sumo/files/5493877/vehUrban.rou.xml.txt)
[test_move_to_xy.py.txt](https://github.com/eclipse/sumo/files/5493890/test_move_to_xy.py.txt)

Steps for reproduction:

1. "sumo-gui.exe --c test.sumo.cfg --lateral-resolution 0.5 --seed 22222 --step-length 0.1 --scale 1 --remote-port 8813 --num-clients 1"
2. "python test_move_to_xy.py"
3. Start simulation in sumo-gui.exe

**Comment by namdre** [comment]
thanks for the report. Github accepts .zip archives which is much easier.
