### ISSUE TITLE
nightly build crashes

### ISSUE THREAD

**Issue by ambuehll** [eclipse/sumo#7767]
sumo nightly build (v1_7_0+0824-402dae1211) crashes. 
see [files](https://drive.google.com/drive/folders/1YjIATNQSsYZ_CcY2w2PI3sQaw3I9mEdC?usp=sharing). 
on Windows 10

**Comment by namdre** [comment]
suspected reason is a change in MSLink approaching registration when rerouting via [3c4997f682db117fd9ea2b7ad0ca098e420bec49]
