### ISSUE TITLE
Speed up detectors when using null device

### ISSUE THREAD

**Issue by jacobowitz** [eclipse/sumo#7772]
We are heavily using E1 and E2 detectors in our SUMO simulations for calculating some traffic metrics on the fly via traci/libsumo from Python code. We only access those detector metrics via traci and dont need their xml output, which is why I set the _file_ parameter for all of them to "NUL" (as written in the documentation).

I noticed that the simulation was rather slow, did a quick profile and found that almost half of the time in SUMO is actually spent in `MSDetectorControl::writeOutput()`. That was quite a surprise as I expected that functionality to be disabled by setting the output device to the null device. 
I read your code and if I understand it correctly, you always generate actually the xml output of the detectors. The null device setting just prevents this xml to be written to disk.
As this xml generation is apparently rather slow and useless in case of null device, I think it would be better to skip output generation alltogether for these cases? I dont know if that has any other side effects though?

For testing I just hard coded detector output generation to be skipped altogether in my fork (https://github.com/jacobowitz/sumo/commit/42ae2679d12aa65a5d258490bc3d6ca7cbcfdbbb) and it seems that this speeds up as expected and the detectors are still doing their job via Traci calls?

If you think the suggested change would be a good idea, I would be happy to work on a proper solution for this.

**Comment by behrisch** [comment]
Your understanding of the code concerning the NUL device is correct but I am sure there are side effects when disabling the call to write output completely. Nevertheless if you do this detector type by detector type we would be very happy about pull requests. The first thing which needs to be done is to separate the writing from the call to reset.
