### ISSUE TITLE
Conflict cause by lane changing 

### ISSUE THREAD

**Issue by Smiley4ever21** [eclipse/sumo#7775]
Hi,

I have a problem can not been solven in my simulation. Please see the screenshot in the attachment. The vehicle on the right lane should go to the left side, and the vehicle on the left lane should go to the right side. And all the vehicles just stuck in the intersection, no vehicle can go any further. Could you please tell me does SUMO have some solutions with this problem? Thank you! 

![Unbenannt](https://user-images.githubusercontent.com/38075241/98459021-b9be4e80-2196-11eb-884f-e2099094cf2a.PNG)

Best Regards.

**Comment by namdre** [comment]
this looks like a motorway ramp for which the suggested solution is this: https://sumo.dlr.de/docs/Simulation/Motorways.html#combined_on-off-ramps
