### ISSUE TITLE
How to import the opendrive file of version 1.5 into networks file?

### ISSUE THREAD

**Issue by radiateboy** [eclipse/sumo#7777]
How to import the opendrive file of version 1.5 into networks file?
`netconvert --opendrive one.xodr -o mySUMOnetwork.net.xml`  is failed.

**Comment by namdre** [comment]
Generally, xodr 1.5 should be importable.
Your file has all kinds of issues:
- the encoding looks broken (road names are garbage). converting the encoding to utf8 allows the parser to run
- in several lines there are missing quotes around the attribute value (`level=0` must be `level="0"`)
- sometimes the attribute value is missing completely (`level= `)

please come back with a file that is valid xml.  For xodr feature support see: #6694, #6695

**Comment by radiateboy** [comment]
okey i got it. thank you very much. @namdre
