### ISSUE TITLE
TraCI connection via cpp API is hanging when loading larger scenarios

### ISSUE THREAD

**Issue by schottb85** [eclipse/sumo#7784]
Since SUMO 1.7.0 we have the problem that for larger scenarios, the load time in sumo-gui seems to have increased significantly. While for the python traci-api the connection is still working, for the cpp traci api the simulation cannot be started properly, but the application seems to hang once the traci-connection has been started. Libsumo in contrast seems to work well, therefore it seems to be an issue with the TraCI connection. We attached a python script to start sumo-gui externally with specified command line options. Further, we attached the cpp commands extract from our larger cpp application. The important information is that a sufficient large sleep-time is required between traci.connect and the first traci.simulationStep command. I hope that you can reproduce the problem as well.

If you need further information, please contact me.
[bug_report_traci.zip](https://github.com/eclipse/sumo/files/5531372/bug_report_traci.zip)

**Comment by behrisch** [comment]
The platform is Windows and your compiler is Visual Studio?

**Comment by schottb85** [comment]
Yes, that is correct

________________________________

Von: Michael Behrisch <notifications@github.com>
Datum: 12. November 2020 um 21:39:42 MEZ
An: eclipse/sumo <sumo@noreply.github.com>
Cc: Schott, Benedikt <Benedikt.Schott@vector.com>, Author <author@noreply.github.com>
Betreff: Re: [eclipse/sumo] TraCI connection via cpp API is hanging when loading larger scenarios (#7784)


The platform is Windows and your compiler is Visual Studio?

**Comment by schottb85** [comment]
Platform: Windows
Compiler Visual Studio 2015, x64
The problem seems to arise just for sumo-gui.exe, not for sumo.exe

**Comment by schottb85** [comment]
Hi Michael, do you need further information about our setup?

**Comment by behrisch** [comment]
Did you install via the installer or compile sumo yourself?

**Comment by schottb85** [comment]
we use the zip-package for SUMO 1.7.0, but we had to compile the utils_traci and the foreign_tcpip libs

**Comment by schottb85** [comment]
could you already reproduce our problem? It would be an important feature for us for SUMO 1.8.0

**Comment by behrisch** [comment]
Unfortunately not. I compiled your traci app with Visual Studio 2019 but used the same sumo 1.7.0 64bit from the zip file. I can run the complete scenario in about 3 seconds with sumo and 4 seconds with sumo-gui. I am attaching my modfied files for you to inspect.
[modified_code.zip](https://github.com/eclipse/sumo/files/5583035/modified_code.zip)

**Comment by schottb85** [comment]
[bug_sumo.zip](https://github.com/eclipse/sumo/files/5641296/bug_sumo.zip)
Unfortunately, even your program does not work for us. I attached a Visual Studio Project including our compiled traci libs. Please open the .sln file in the source folder, build Release configuration x64.

Hint: linker paths need to be adapted in the .sln properties and as well as the paths in the start_sumo.py

**Comment by behrisch** [comment]
Even without recompiling I could start your test_traci.exe directly (after adapting the paths in start_sumo.py) and it works just fine. It is getting slower after some time but startup time is OK. Can you try this on a different machine outside of any corporate firewalls, virus checkers etc?

**Comment by behrisch** [comment]
closing for lack of feedback, please reopen if problems persist
