### ISSUE TITLE
generate jupedsim "walls" from a sumo net

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#7785]
We need an input file describing which edges, junctions and/or polygon areas (TAZ?) are to be simulated by JuPedSim and at least for debug purposes an output file describing the resulting polygons or line segments for the outer borders and start / end positions or areas.

**Comment by schwamborn** [comment]
TODO:
- [ ] test with bigger networks
- [ ] write documentation

**Comment by bcoueraud87** [comment]
@namdre Not at all, I propose to close the ticket.

**Comment by behrisch** [comment]
I opened #13088 to keep track of the "define parts of the network where the new model applies" thing
