### ISSUE TITLE
What does 'traci.edge.getWaitingTime' mean in detail?

### ISSUE THREAD

**Issue by Sheldon-Zhou1997** [eclipse/sumo#7789]
What does 'traci.edge.getWaitingTime' mean?All vehicles in the edge's waiting time when vehicles in the edge or  vehicles in the edge's waiting time since vehicles was imported in the network?

**Comment by angelobanse** [comment]
The waiting time of all vehicles currently on a specific edge.

https://sumo.dlr.de/pydoc/traci._edge.html#EdgeDomain-getWaitingTime
