### ISSUE TITLE
netconvert can not create all subway stations

### ISSUE THREAD

**Issue by meco2020** [eclipse/sumo#7790]
when I use netconvert to create ptstops and ptlines, I find that not all bus stops will be created. 

![image](https://user-images.githubusercontent.com/65943065/99184558-b1f63f80-277e-11eb-8cd5-ba67a47113df.png)
In my OSM map, there are many subway stations, but I can only create two stations in my additional file.
[question.zip](https://github.com/eclipse/sumo/files/5542323/question.zip)

**Comment by namdre** [comment]
regarding subway import there are two issues:
1) netconvert had trouble importing lines that are defined with a single '<way>' element in the osm data for the exported area (now fixed)
2) osm standards recommend that each track of the line is mapped with it's own way but in this area only one way is mapped so the exported network is incomplete.

regarding busstop import, it would help if you could check whether the missing busstop is even included in the osm data (i.e. by looking here http://öpnvkarte.de/ or https://www.openstreetmap.org) and the point out the id within the osm data (i.e. by searching for the name within the file).

**Comment by namdre** [comment]
closing due to lack of feedback. Please reopen if problem persists.
