### ISSUE TITLE
wrong queue selection

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#7794]
queue (lane) does not correspond to connection.

Vehicles that want to go straight queue on a left-turn lane and thereby block it for left-turning traffic.

regression in 1.7.0 probably introduced during **--meso-lane-queue** work

The behavior can be seen in basic/tls/actuated/dualring_simple but likely affects many more tests

**Comment by namdre** [comment]
https://github.com/eclipse/sumo/blob/7157d9bd9a53462be9cc5ec8f5d12c60d7c98851/src/mesosim/MESegment.cpp#L277 looks wrong. Queue selection appears to work correctly when reversing the two cases of the operator

**Comment by namdre** [comment]
any reason for keeping this open?

**Comment by behrisch** [comment]
no specific test yet

**Comment by namdre** [comment]
The tls actuated test reacts strongly to this. Good enough for me.

**Comment by behrisch** [comment]
Now for me as well ;-)
