### ISSUE TITLE
extractTest does not collect all option files for variants

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#7797]
extracting sumo\basic\tls\actuated\dualring_simple does not collect options.sumo.meso in the tls dir

**Comment by namdre** [comment]
also, the option default.speeddev 0 from options.sumo in the base folder is not collected for meso tests even though it gets applied during test runs.

**Comment by namdre** [comment]
sometimes it works, sometimes it doesn't. A failure example is tests/meso/junction_control/network_problem/control.limited_minor_penalty

This creates a test.sumocfg and a testmeso.sumocfg

**Comment by namdre** [comment]
in contrast, when exporting tests/meso/jamming/single_jam_1lane the speeddev option is present but the --mesosim option is missing

**Comment by behrisch** [comment]
I was under the impression that the specific file overrides the generic one but noth are read. Should now be fixed in ee2a5088108d036e91c1e04d51c683f2affbd337

**Comment by behrisch** [comment]
> in contrast, when exporting tests/meso/jamming/single_jam_1lane the speeddev option is present but the --mesosim option is missing

This is a tricky one. I currently try to determine which variants to generate by looking at the files in the test dir. If there is any variant file (any file ending in .meso in this case) the variant is generated. I do this to avoid generating always all variants (which we have many of). Ideas?

**Comment by behrisch** [comment]
> 
> 
> > in contrast, when exporting tests/meso/jamming/single_jam_1lane the speeddev option is present but the --mesosim option is missing
> 
> This is a tricky one. I currently try to determine which variants to generate by looking at the files in the test dir. If there is any variant file (any file ending in .meso in this case) the variant is generated. I do this to avoid generating always all variants (which we have many of). This test however does not have a meso file although it is only run with meso. Ideas (besides parsing testsuites)?

There is the command line option -a though where you can choose -a meso or -a ALL

**Comment by namdre** [comment]
More trouble:

```
extractTest.py sumo/tests/sumo/sublane_model/basic/overtaking_lefthand/
Error: A value for the option 'xml-validation' was already set.
 Possible synonymes: X
Error: Could not parse commandline options.
Quitting (on error).

```

**Comment by behrisch** [comment]
Texttest seems to be clever enough to filter duplicate identical options. I don't think we need this in extractTest or do we?

**Comment by namdre** [comment]
your fix is fine.

**Comment by behrisch** [comment]
> > This is a tricky one. I currently try to determine which variants to generate by looking at the files in the test dir. If there is any variant file (any file ending in .meso in this case) the variant is generated. I do this to avoid generating always all variants (which we have many of). This test however does not have a meso file although it is only run with meso. Ideas (besides parsing testsuites)?

I don't have a good idea how to solve this but I think it is visible to the extractor that no meso variant is extracted (because it is not a testmeso.sumocfg) and he/she can still use -a meso, so I am closing it. Please reopen with good ideas :-)
