### ISSUE TITLE
Black screen with brew installed sumo-gui and netedit on macOS Catalina

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#7799]
There are no issues loading files and running the simulation from Python. It seems that only the visualizations are affected.
However, this also happens in Netedit when a new network is created or an existing network is loaded.

They are running on SUMO 1.7.0 with XQuartz 2.7.11.
In order to get SUMO to work they have had to install the Mojave bottle of Fox as suggested in #6242.

**Comment by schwamborn** [comment]
It looks like uninstalling SUMO v1.7.0 and installing v1.6.0 instead might work, see #7830.

**Comment by schwamborn** [comment]
Got positive feedback for this approach: https://github.com/eclipse/sumo/issues/7830#issuecomment-740024652

**Comment by schwamborn** [comment]
Closing due to missing further feedback.
