### ISSUE TITLE
meso-minor-penalty is applied at traffic light junctions

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#7802]
The member MESegment::myMinorPenalty may be 'false' and yet the code in getLinkPenalty() causes the penalty to be added anyway if junctionControl=true or myTLSPenalty=true

this bug looks to be as old as meso-minor-penalty itself

This could have been intended as a feature (green minor) but looks strange when applied to a red light. (happens with junction-control.limited)

**Comment by behrisch** [comment]
imho meso-minor-penalty should only apply to priority junctions
