### ISSUE TITLE
dubious timeLoss value in edgeData output

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#7805]
- negative timeLoss (spec/departure/extrapolat_departpos) - possibly the meso variant of #7749
- timeLoss < waitingTime (output/meandata_lanebased)

**Comment by behrisch** [comment]
several tests in extended/calibrator and extended/variablespeedsigns are affected as well

**Comment by namdre** [comment]
timeLoss < waitingTime is mathematically possible if either
- vmax == 0 (happens due to a vss)
- 0 < v < haltingSpeedThreshold  (the whole step is counted as halting but timeLoss is less since the vehicle is still moving)

**Comment by namdre** [comment]
negative timeloss is long term accumulation of numerical errors.
