### ISSUE TITLE
macOS Application launchers should also open file

### ISSUE THREAD

**Issue by RobertHilbrich** [eclipse/sumo#7806]
Currently, the macOS application launchers can only be used to launch the sumo-gui application (or netedit or osm webwizard). Some users may want to assign files with the extension .sumocfg to be always opened with sumo-gui. Unfortunately, due to the way these application launchers are currently built, command line arguments (like a filename) cannot be forwarded to the call to open sumo-gui. This is inconvenient, because they click on the file, sumo-gui opens up, but the file is not loaded. The users need to open the scenario manually, after sumo-gui has been opened.

Seems like platypus does not offer this capability. Will explore macOS automator options.

**Comment by angelobanse** [comment]
`⌘`+`Q` closes the Apps (as it should) but then displays an "X Fatal error" dialog. If I remember correctly, that did not occur with the previous Platypus-launchers. Maybe it's worth taking a look at that...

**Comment by behrisch** [comment]
This maybe worth a separate ticket

**Comment by RobertHilbrich** [comment]
I think this is not related to the new launchers - rather an XQuartz issue on macOS ... I am not sure, if we can fix that.

**Comment by angelobanse** [comment]
fixed in a167f72a8d87b6f28cb3c6f67dfa240e4f2b17b2
