### ISSUE TITLE
nightly debug windows build fails to start

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#7814]
caused by missing dll as explained here https://stackoverflow.com/questions/33743493/why-visual-studio-2015-cant-run-exe-file-ucrtbased-dll

we should copy this into the bin folder for the debug zip

**Comment by behrisch** [comment]
@namdre Please let them try again tomorrow (afternoon)

**Comment by behrisch** [comment]
dll is now in and starting the debug version works at least here. Please reopen if problems persist
