### ISSUE TITLE
taxi and container

### ISSUE THREAD

**Issue by MelanieWeber** [eclipse/sumo#7815]
Taxi device do not work with container. 
The containers are picked up, but the taxi does not get a new route and therefore does not drive off.

**Comment by MelanieWeber** [comment]
![grafik](https://user-images.githubusercontent.com/38243649/99536083-22cd6f80-29aa-11eb-9033-9b7a3eb6c426.png)

**Comment by rummel123** [comment]
The vehicle is still not moving, after loading the container.
[Scenario_Container_Truck_Train.zip](https://github.com/eclipse/sumo/files/5621673/Scenario_Container_Truck_Train.zip)

**Comment by namdre** [comment]
For your scenario to work, you need some workarounds:
1) do not set personCapacity="0" on your truck (#7892)
2) do not set an initial stop (idle algorithm can handle this). (#7893)

**Comment by namdre** [comment]
capacities are working now (#7892)
