### ISSUE TITLE
More information in tripinfo

### ISSUE THREAD

**Issue by MelanieWeber** [eclipse/sumo#7822]
We also need the following information in the tripinfo file:
personinfo:
- for ride and walk: departLane and arrivalLane (departPos/arrivalPos are allready included)
- for access: depart and arrival

containerinfo:
- for transship and transport: departLane and arrivalLane (departPos/arrivalPos are allready included)

**Comment by rummel123** [comment]
If a busStop (containerStop) is used in the routing file, the stop should also be in the tripinfo file (instead of the arrivalLane) as it is for vehicles.

**Comment by namdre** [comment]
> We also need the following information in the tripinfo file:
>     * for ride and walk: departLane and arrivalLane (departPos/arrivalPos are allready included)
>     * for transship and transport: departLane and arrivalLane (departPos/arrivalPos are allready included)

In the original design transportables do not care about lanes and only about edges. The default pedestrian model always uses the rightmost lane that allows persons. Thus there is little extra information in the lane index. The edge however is already part of the input. How do you intend to use the lane information?

**Comment by rummel123** [comment]
The lane is not the important point here (edge would also be adequate).
We need the tracks of the persons and containers, i.e. locations and related times for the evaluation. It would be much easier to get that joined information from the tripinfo file instead of relating the two files (route file, tripinfo file).

**Comment by namdre** [comment]
should be solved via #7632

**Comment by namdre** [comment]
not easily solved via #7632. Solved instead via project-specific python script as discussed with @rummel123
