### ISSUE TITLE
GUI does not render on MacOS (red background)

### ISSUE THREAD

**Issue by krkv** [eclipse/sumo#7830]
Hello,

I followed the installation (with homebrew) for MacOS, but the result of the rendering is a red screen for me:

![Screenshot 2020-11-20 at 10 56 58](https://user-images.githubusercontent.com/3106514/99784272-3f8db280-2b24-11eb-9a8e-f5d2e5bbe153.png)

**Comment by krkv** [comment]
I uninstalled 1.7.0 and installed 1.6.0 and GUI now works as expected 👍

**Comment by namdre** [comment]
It would be awesome if you could check whether the nightly version also has this error on your system. 
https://sumo.dlr.de/daily/sumo-src-git.zip
https://sumo.dlr.de/docs/Installing/MacOS_Build.html

This way we could avoid an issue in our upcoming release of versio 1.8.0

**Comment by schwamborn** [comment]
> I uninstalled 1.7.0 and installed 1.6.0 and GUI now works as expected 👍

Awesome, thanks for the feedback! Are you running macOS Catalina?

**Comment by krkv** [comment]
> Awesome, thanks for the feedback! Are you running macOS Catalina?

Yes, I am on Catalina. Thank you guys for reply, I will try to check the nightly for you.

**Comment by cbdm** [comment]
Hi,

I'm having the same problem as the original post.
Both sumo-gui and netedit show this problem.

I've tried both homebrew (v 1.7.0), and compiling from source (v1.6.0 and the HEAD from the repository).
All with the same result.

Is there any other fix I could try?
I'm on Mojave btw.

Thanks!

Caio

**Comment by schwamborn** [comment]
Unfortunately, we haven't been able to reproduce this bug, yet.
Can you give us all the steps you took for compiling?

**Comment by cbdm** [comment]
Sure, I just followed the homebrew instructions from https://sumo.dlr.de/docs/Installing.html#macos and the build instructions from https://sumo.dlr.de/docs/Installing/MacOS_Build.html.
I can send any data/logs that might help (or retry any of those methods), I'm just not sure what would be of interest to you.

Caio

**Comment by schwamborn** [comment]
I'm still puzzled by this issue. Have you tried to [troubleshoot your homebrew installation](https://docs.brew.sh/Troubleshooting) first? Other than that, I would be interested in what your results are with installing SUMO v1.8.0:

`% brew uninstall sumo`
`% brew update`
`% brew install sumo --verbose`

**Comment by cbdm** [comment]
I reinstalled the homebrew version as you suggested and it seems to be working now!
I checked the homebrew-sumo repository and looks like it was updated to 1.8.0 a few days ago, maybe that fixed it? Weird that I was still having the problem when compiling 1.8.0 from source though.

Anyway, your last suggestion made it work and I don't see the problem with the 1.8.0 homebrew formula.

Thanks!
Caio

**Comment by qichaow** [comment]
I'm still seeing the red background in GUI with the latest code (pulled just now) on Mac. I also installed sumo with brew and there was no issue.

**Comment by schwamborn** [comment]
@qichaow Please [troubleshoot your homebrew installation](https://docs.brew.sh/Troubleshooting) first. You might also want to check your XQuartz version. Version 2.8.0+ is known to have caused some problems.

If the problem persists, please post your output from:

```
% brew uninstall sumo
% brew update
% brew install sumo --verbose
```

**Comment by qichaow** [comment]
> @qichaow Please [troubleshoot your homebrew installation](https://docs.brew.sh/Troubleshooting) first. You might also want to check your XQuartz version. Version 2.8.0+ is known to have caused some problems.
> 
> If the problem persists, please post your output from:
> 
> ```
> % brew uninstall sumo
> % brew update
> % brew install sumo --verbose
> ```

Thanks for the quick response. There was nothing wrong with the homebrew-installed SUMO. The GUI issue was only observed in the SUMO that was built from source code. Both homebrew-installed SUMO and the built-from-source-code SUMO are installed on the same machine. I was suspecting issues from XQuartz. My Xquartz was updated today to version 2.8 from a much older version.

**Comment by ugirumurera** [comment]
I am having the same "red screen" gui issue when I compile from source. For my application, I need to compile from source.
How do I fix this? I have tried compiling from 1.8 source code, still same issue.

**Comment by schwamborn** [comment]
@ugirumurera Please try updating XQuartz to 2.8.1. Most recent sumo version is 1.9.1 now, by the way.

**Comment by CoskunGorkem** [comment]
Hello @schwamborn,
I used to have roughly 1 year old version of sumo, today I have installed the latest release(1.9.1) from source code and faced with red screen issue. Then I have updated my XQuartz to 2.8.1. Same thing happened. Later I deleted sumo and re-installed by following your previous suggestion;
```
% brew uninstall sumo
% brew update
% brew install sumo --verbose.
```
Nothing changed, then I followed the installation instructions from [here](https://sumo.dlr.de/docs/Installing/index.html). Red screen again. I should also mention, Netedit works alright, I see red screen only in sumo-gui. Any idea how I can use latest methods and also render the network?
Any help would be appreciated
```
Operating system: macOS Catalina Version 10.15.7
```
Regards

**Comment by schwamborn** [comment]
@CoskunGorkem Have you tried to [troubleshoot your homebrew installation](https://docs.brew.sh/Troubleshooting) first? If that seems fine, have you made sure that your earlier sumo build attempts have been cleaned up and that the sumo-gui binary you run is actually the one you recently built?

**Comment by CoskunGorkem** [comment]
Hello @schwamborn,
I tried the homebrew troubleshoot page. After my massage, I decided to use a windows device. I will keep this message updated when I figure out what was the problem on macOS. Thanks for the answer.

**Comment by DayuanTan** [comment]
I encouter this problem also. How did you fix it? Thank you very much

**Comment by DayuanTan** [comment]
> I uninstalled 1.7.0 and installed 1.6.0 and GUI now works as expected 👍

Hi how did you install a older version? thank you very much

**Comment by krkv** [comment]
> > I uninstalled 1.7.0 and installed 1.6.0 and GUI now works as expected 👍
> 
> Hi how did you install a older version? thank you very much

Hi, I believe I did:

```% brew uninstall sumo
% brew update
% brew install sumo@1.6.0```

**Comment by kairosiann** [comment]
@krkv I tried that and I still ran into the exact same issue. In fact, netedit also began showing the red screen, which didn't happen before. In addition, when I turned sumo on today, I kept getting 
dyld: Library not loaded: /usr/local/opt/proj/lib/libproj.22.dylib
  Referenced from: /usr/local/bin/sumo
  Reason: image not found
errors, could someone help me please?

Thank you!

**Comment by mschrader15** [comment]
I have encountered the "black screen error" attempting to build from source on macOS Monterey with the M1 chip. Both sumo-gui and netedit have black screens where OP had a red one.

I have installed sumo with homebrew and it works without issue.

**Comment by ion-turcanu** [comment]
Hi everyone! I have the same "black screen error" issue when trying to build from source SUMO 1.11.0 (also 1.8.0) on macOS Monterey version 12.1 with M1 chip. Netedit has the same issue. I have tried with XQuartz 2.8.1 and 2.8.0.

<img width="1666" alt="Screenshot 2022-01-13 at 14 28 17" src="https://user-images.githubusercontent.com/12728962/149359547-3fc934c6-b316-49c8-a2d1-aae6eb3cac33.png">

Unfortunately, the brew solution would not work for me, as I need to build from source.
Any ideas on how this issue could be fixed?

Thanks in advance and best regards!

**Comment by harirRzi** [comment]
When I run downloads/veins-master/sumo-launchd.py -vv -c ~/sumo/bin/sumo-gui, it shows a black page. And when I hit the run button, it show the time that its running. My sumo-gui and netedit run correctly and they both show the simulation. But the black screen just rises when I use vein to run sumo-gui. Also when I run downloads/veins-master/sumo-launchd.py -vv -c ~/sumo/bin/sumo-gui, it shows me the following warnings: WARNING: the sumo-launchd.py script is deprecated in favor of bin/veins_launchd. Redirecting.
WARNING: the sumo-launchd.py script is deprecated in favor of bin/veins_launchd. Redirecting.
Logging to /var/folders/ss/_3stplfj063cqkd70rr3rsdh0000gn/T/sumo-launchd.log
Listening on port 9999.
I appreciate if anyone can suggest me how can I fix it.

**Comment by behrisch** [comment]
@harirRzi Your question will not get much attention if posted below a closed ticket. You may have more luck on the mailing list see https://www.eclipse.org/sumo/contact/

**Comment by ambuehll** [comment]
Sorry to bing this back to life. I am having the same issue as @ion-turcanu on macos (M1) with Quartz 2.8.1: back screen when I open sumo-gui. Has anyone figured out how to solve this?
Thanks in advance!

**Comment by ambuehll** [comment]
works fine with sumo from homebrew:
```
Eclipse SUMO sumo Version 1.12.0 
Build features: Darwin-21.3.0 arm64 Clang 13.1.6.13160021 Release Proj GUI SWIG 
```

back screen with:
```
Eclipse SUMO sumo Version v1_12_0+1429-0b76cdf2a5d
Build features: Darwin-21.3.0 arm64 GNU 11.2.0 Release FMI Proj GUI SWIG GDAL FFmpeg GL2PS
```

on a macOS 12.2.1, Apple M1 Max
XQuartz 2.8.1 (xorg-server 1.20.11)

**Comment by ambuehll** [comment]
I modfied the CMakeCache file for `CHECK_OPTIONAL_LIBS:BOOL=OFF`, built sumo, and I still have a black screen.

**Comment by behrisch** [comment]
Sorry for asking but just to make sure: Did you do a clean build? (So are the Build features no shown any more when starting sumo?)

**Comment by ambuehll** [comment]
Here all the things I did:
1. delete the existing sumo directory
2. followed https://sumo.dlr.de/docs/Installing/MacOS_Build.html#git_cloning_and_building up to the build process: 
After  running 
`cmake ../..`
-> modify CMakeCache.txt in cmake-build directory to follow `CHECK_OPTIONAL_LIBS:BOOL=OFF`
then build with: 
```
cd $SUMO_HOME/build/cmake-build
cmake --build . --parallel $(sysctl -n hw.ncpu)
```
3. re-opened sumo-gui from terminal directly from the bin folder.

**Comment by behrisch** [comment]
Can you try to build with clang? Probably by doing `CXX=clang++ cmake ../..`

**Comment by ambuehll** [comment]
I re-build sumo using clang, **doesn't work**:
```
Eclipse SUMO sumo Version v1_12_0+1516-c590785ca63
Build features: Darwin-21.3.0 arm64 Clang 13.1.6.13160021 Release FMI Proj GUI SWIG
```


stable version from homebrew **works** (also build using clang):
```
Eclipse SUMO sumo Version 1.12.0
Build features: Darwin-21.3.0 arm64 Clang 13.1.6.13160021 Release Proj GUI SWIG

```

**Comment by behrisch** [comment]
Very strange. Can you check whether there are differences in the linked libraries by doing `ldd sumo-gui` for both versions

**Comment by ambuehll** [comment]
<img width="1331" alt="image" src="https://user-images.githubusercontent.com/48930860/159157486-c3250000-5615-4295-8847-7073dd8bc9d0.png">
**left**: my build using latest dev -- **right**: homebrew build

I removed the library paths to compare the versions - they differ for most libraries.

**Comment by mschrader15** [comment]
FYI I am following along with @ambuehll on my M1 Mac and getting the same result

**Comment by behrisch** [comment]
Thanks a lot for your efforts! Can you maybe attach the full ldd diff (or the two logs) I would like to know the library paths especially for the GL related stuff. Also given the attention this is getting we should reopen it.

**Comment by ambuehll** [comment]
Thank you for the help!
Homebrew:

```
/opt/homebrew/opt/xerces-c/lib/libxerces-c-3.2.dylib (compatibility version 0.0.0, current version 0.0.0)
/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
/opt/homebrew/opt/proj/lib/libproj.25.dylib (compatibility version 25.0.0, current version 25.9.0)
/opt/homebrew/opt/fox/lib/libFOX-1.6.0.dylib (compatibility version 1.0.0, current version 1.56.0)
/opt/homebrew/opt/libx11/lib/libX11.6.dylib (compatibility version 11.0.0, current version 11.0.0)
/opt/homebrew/opt/libxext/lib/libXext.6.dylib (compatibility version 11.0.0, current version 11.0.0)
/opt/homebrew/opt/freetype/lib/libfreetype.6.dylib (compatibility version 25.0.0, current version 25.1.0)
/opt/homebrew/opt/fontconfig/lib/libfontconfig.1.dylib (compatibility version 14.0.0, current version 14.0.0)
/opt/homebrew/opt/libxft/lib/libXft.2.dylib (compatibility version 6.0.0, current version 6.4.0)
/opt/homebrew/opt/libxcursor/lib/libXcursor.1.dylib (compatibility version 2.0.0, current version 2.2.0)
/opt/homebrew/opt/libxrender/lib/libXrender.1.dylib (compatibility version 5.0.0, current version 5.0.0)
/opt/homebrew/opt/libxrandr/lib/libXrandr.2.dylib (compatibility version 5.0.0, current version 5.0.0)
/opt/homebrew/opt/libxfixes/lib/libXfixes.3.dylib (compatibility version 5.0.0, current version 5.0.0)
/opt/homebrew/opt/libxi/lib/libXi.6.dylib (compatibility version 8.0.0, current version 8.0.0)
/opt/homebrew/opt/mesa/lib/libGL.1.dylib (compatibility version 4.0.0, current version 4.0.0)
/opt/homebrew/opt/mesa-glu/lib/libGLU.1.dylib (compatibility version 5.0.0, current version 5.1.0)
/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.0.0)
/opt/homebrew/opt/jpeg/lib/libjpeg.9.dylib (compatibility version 15.0.0, current version 15.0.0)
/opt/homebrew/opt/libpng/lib/libpng16.16.dylib (compatibility version 54.0.0, current version 54.0.0)
/opt/homebrew/opt/libtiff/lib/libtiff.5.dylib (compatibility version 13.0.0, current version 13.0.0)
/usr/lib/libbz2.1.0.dylib (compatibility version 1.0.0, current version 1.0.8)
/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1200.3.0)
```

own build:

```
/opt/homebrew/opt/xerces-c/lib/libxerces-c-3.2.dylib (compatibility version 0.0.0, current version 0.0.0)
/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
/opt/homebrew/opt/proj/lib/libproj.25.dylib (compatibility version 25.0.0, current version 25.9.0)
/opt/homebrew/opt/fox/lib/libFOX-1.6.0.dylib (compatibility version 1.0.0, current version 1.56.0)
/opt/X11/lib/libX11.6.dylib (compatibility version 11.0.0, current version 11.0.0)
/opt/X11/lib/libXext.6.dylib (compatibility version 11.0.0, current version 11.0.0)
/opt/X11/lib/libfreetype.6.dylib (compatibility version 24.0.0, current version 24.4.0)
/opt/X11/lib/libfontconfig.1.dylib (compatibility version 14.0.0, current version 14.0.0)
/opt/X11/lib/libXft.2.dylib (compatibility version 6.0.0, current version 6.3.0)
/opt/X11/lib/libXcursor.1.dylib (compatibility version 2.0.0, current version 2.2.0)
/opt/X11/lib/libXrender.1.dylib (compatibility version 5.0.0, current version 5.0.0)
/opt/X11/lib/libXrandr.2.dylib (compatibility version 5.0.0, current version 5.0.0)
/opt/X11/lib/libXfixes.3.dylib (compatibility version 5.0.0, current version 5.0.0)
/opt/X11/lib/libXi.6.dylib (compatibility version 8.0.0, current version 8.0.0)
/opt/X11/lib/libGL.1.dylib (compatibility version 4.0.0, current version 4.0.0)
/opt/X11/lib/libGLU.1.dylib (compatibility version 5.0.0, current version 5.1.0)
/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.100.3)
/opt/homebrew/opt/jpeg/lib/libjpeg.9.dylib (compatibility version 15.0.0, current version 15.0.0)
/opt/X11/lib/libpng16.16.dylib (compatibility version 55.0.0, current version 55.0.0)
/opt/homebrew/opt/libtiff/lib/libtiff.5.dylib (compatibility version 13.0.0, current version 13.0.0)
/usr/lib/libbz2.1.0.dylib (compatibility version 1.0.0, current version 1.0.8)
/opt/homebrew/opt/gdal/lib/libgdal.30.dylib (compatibility version 31.0.0, current version 31.1.0)
/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1300.23.0)
```

**Comment by behrisch** [comment]
It seems we are getting closer. Probably the problem are the X11 libs. can you try commenting out the lines https://github.com/eclipse/sumo/blob/main/CMakeLists.txt#L178 and 179 and rebuild. If this does not work can you replace all /opt/X11 references in CMakeCache.txt with the /opt/homebrew/opt equivalent?

**Comment by ambuehll** [comment]
Commenting out L178 and 179 in the CMakeLists.txt works!!
Thank you!

**Comment by ion-turcanu** [comment]
Hi everyone! Thank you so much for looking into this.
I can confirm that commenting out L178 and L179 in CMakeLists.txt worked for me too!

**Comment by behrisch** [comment]
Please recheck whether it works with the latest commit now without manual changes. Also I would be interested in feedback whether anyone sees value in keeping the MacPorts support.

**Comment by ambuehll** [comment]
works for me! no need for manual changes anymore.
No need for MacPorts for me. A homebrew tap for the latest dev version would be convenient though.

**Comment by schwamborn** [comment]
@ambuehll Have you tried `brew install --HEAD sumo` (cf. https://github.com/DLR-TS/homebrew-sumo#usage)?

**Comment by ambuehll** [comment]
@schwamborn 
Ha! my bad! That's great - exactly what I was looking for. 
I didn't understand "HEAD version", when I went throught the doc, so I just ignored the option... 
Maybe it could be called something along "latest dev version".

**Comment by schwamborn** [comment]
Glad to hear it works for you.
And good point, I will edit the description.

**Comment by schwamborn** [comment]
It looks like the description of option `--HEAD` is automatically generated by brew and is read-only.
Made changes to README.md, though.

**Comment by gma-uw** [comment]
I am having the black screen problem with MacPorts install of git. Any ideas how to fix that?

**Comment by behrisch** [comment]
Can you please go back to an older version (before https://github.com/eclipse/sumo/commit/c07b462f727c9873162fce53638f01264407c012) or the last release and recheck whether it still worked then?
