### ISSUE TITLE
Reversible lanes support

### ISSUE THREAD

**Issue by urielka** [eclipse/sumo#7831]
Hi,

Couldn't find something explicit about reversible lanes in the documentation? Is it supported by sumo?

Can it be worked around?

I have a lane in an intersection which sometimes in the day it is a south bound lane and sometimes it is a north bound lane. 

I would prefer not to build two networks, one per case if possible.

**Comment by namdre** [comment]
Define an extra lane in both directions and make one disallowed. You may place those lanes on top of each other for a more realistic visualization but for debugging it should be easier to have them next to each other. Then either
a) use traci to configure allowed vehicles on either lane to prohibit one or the other direction
b) use laneClosingReroute to change the permissions at preconfigured times via XML input

If the whole edge should switch direction, see https://sumo.dlr.de/docs/Simulation/Traffic_Lights.html#default_4-arm_intersection_layout_opposites

**Comment by urielka** [comment]
Thank you for the quick reply! I will try this and report back :)
