### ISSUE TITLE
Subline Model Problem

### ISSUE THREAD

**Issue by Timor7hao** [eclipse/sumo#7839]
Dear Professor:
     I need to simulate traffic on a stretch of road, but the cars don't seem to change lanes. By setting up the command line sumo-gui -c run.sumo-cfg --Lateral resolution 0.2 or the scheme shown in the following figure, I hope to open the SL2015 lane change model, but I always report errors as shown in the figure below. I'm currently at 0.25.0 for SUMO.How do you change lanes without changing the version?
![image](https://user-images.githubusercontent.com/38340783/99874246-21f24300-2c21-11eb-9f48-be58c0ff6ee7.png)
![image](https://user-images.githubusercontent.com/38340783/99874283-801f2600-2c21-11eb-9aca-fdde9841dab2.png)

**Comment by namdre** [comment]
The sublane feature (lateral resolution) is not supported by version 0.25.0. I recommend that you upgrade to 1.7.0
