### ISSUE TITLE
deadlock at traffic_light_right_on_red

### ISSUE THREAD

**Issue by ChocolateDave** [eclipse/sumo#7840]
Hello! I recently researched the lateral interferences of bicycle/moped lanes, and it came up with some problems while adding these lanes to the previous model. As demonstrated by the following figure, the forward space of Vehicle WN.SP.0.1 was clearly empty, and it would be safe for it to finish passing through the intersection area.

![Before braking](https://user-images.githubusercontent.com/45930715/99897027-dc8d4e80-2cd0-11eb-88c1-5271bedb3e5d.png)

However, its speed critically dropped, and the brake gap shortened, as shown by the following figure. And the vehicle would then stopped at its current position and caused a deadlock in the intersection.

![image](https://user-images.githubusercontent.com/45930715/99897088-7d7c0980-2cd1-11eb-8370-d5242ad5b5e2.png)

I'm currently using IDM car-following model with tau=1.1 and delta=3.8 for this specific type of vehicle. I disabled the non-motorized vehicle flows, but the problem still existed. What might be the cause of the problem above?

**Comment by namdre** [comment]
- what version of sumo are you using?
- what simulation options are you using?

**Comment by ChocolateDave** [comment]
> 
> 
>     * what version of sumo are you using?
> 
>     * what simulation options are you using?

* I'm currently using SUMO 1.7.0
* Simulation options in the configuration file are as follows:

`<configuration>
    <input>
        <net-file value="ITLS.net.xml"/>
        <route-files value="ITLS.rou.xml"/>
        <additional-files value="ITLS.add.xml"/>
        <gui-settings-file value="view.settings.xml"/>
    </input>

    <time>
        <begin value="0"/>
    </time>

    <processing>
        <step-length value="0.2"/>
    </processing>

    <report>
        <verbose value="false"/>
        <no-duration-log value="true"/>
        <no-warnings value="true"/>
    </report>

    <gui_only>
        <start value="false"/>
        <quit-on-end value="false"/>
    </gui_only>
</configuration>
`

**Comment by namdre** [comment]
can attach the scenario (preferably reduced to the minimum contents that reproduce this situation)?

**Comment by ChocolateDave** [comment]
> 
> 
> can attach the scenario (preferably reduced to the minimum contents that reproduce this situation)?

Here are the definition files of network and demand.

[scenario.zip](https://github.com/eclipse/sumo/files/5581659/scenario.zip)

**Comment by namdre** [comment]
May I use your example for our public tests?

**Comment by ChocolateDave** [comment]
> 
> 
> May I use your example for our public tests?

Sure. Feel free to test.
