### ISSUE TITLE
Assign color to lines in ptlines2flows

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#7845]
New visualisation mode: Draw vehicles by lines. Change vehicle color if it's using a line

**Comment by namdre** [comment]
I thought about it some more: I don't think we need an new attribute or a new color mode for this. Instead we can use the vehicle color or the route color for this (in particular the route color should correspond well). 
This means, that the tools that import public transport schedules (i.e. ptlines2flows or gtfs2pt.py) should set those colors for each line.

**Comment by behrisch** [comment]
Also in gtfs import

**Comment by behrisch** [comment]
Also recheck whether OSM has color or color names already stored

**Comment by behrisch** [comment]
@namdre There is also color in GTFS: http://gtfs.org/reference/static/#routestxt Is it worth the effort?

**Comment by namdre** [comment]
@behrisch I think yes. The effort ought to be small.
