### ISSUE TITLE
Dynamic Traffic Controlling

### ISSUE THREAD

**Issue by SujanSanjula96** [eclipse/sumo#7846]
I need to use adaptive traffic control for a junction. For that, I need to start with static timing for the first cycle and then dynamically change the green times of the next cycle by keeping a fixed cycle time. At the end of a cycle, phase times are calculated for the next cycle and I need to change the green times to that obtained values.

**Comment by namdre** [comment]
see https://sumo.dlr.de/docs/Simulation/Traffic_Lights.html#controlling_traffic_lights_via_traci
