### ISSUE TITLE
proj.db cannot be found when runing duarouter under windows 10

### ISSUE THREAD

**Issue by yunpangfloetteroed** [eclipse/sumo#7848]
The file can be generated after building sumo and can be found under $SUMO_HOME/data/proj. 
It still does not work even to copy the file from SUMOLibraries\proj-6.1.1\share\proj to $SUMO_HOME/data/proj.
It works only when setting PROI_LIB = $SUMO_HOME/data/proj in the environmental variables.

**Comment by behrisch** [comment]
@palvarezlopez Can you help here?

**Comment by behrisch** [comment]
@yunpangfloetteroed Is this still relevant?

**Comment by yunpangfloetteroed** [comment]
No, Pablo has helped me to slove this problem.
