### ISSUE TITLE
How to calculate K-shortest path in Assignment.py?

### ISSUE THREAD

**Issue by Shiyunyang-seu** [eclipse/sumo#7849]
Hi, if I want to calculate K-shortest path, how should I use assignment.py ? In particular, what are the specific meanings of the parameters (newroutes, startvertices, endvertices, matrixpshort and gamma)? 
Thanks in advance!

**Comment by behrisch** [comment]
Probably, you should not. Please rather try marouter like this:
`marouter -n input_net.net.xml -d input_taz.taz.xml -m input_od_o.fma -o
routes.rou.xml --paths 3 --assignment-method SUE`
