### ISSUE TITLE
Different probability flows between simulations

### ISSUE THREAD

**Issue by tiagoasilva** [eclipse/sumo#7856]
I'm generating a flow of vehicles with probability='0.3' as seen in the code below:

```
<flow id='flow_2' color="0,0,1" begin='0' end='4500' probability='0.3' type='vehicleType_1'>
    <route edges='5to1 1to3'/>
</flow>
```

It works correctly and generates the random flows. However, I noticed that if I execute the simulation again it will generate the same random flow as the previous execution. To solve this, I included a random_number in **sumo.cfg**:
```
<random_number>
       <random value='true'/>
</random_number>
```
It works fine if I load the simulation directly in sumo-gui. However, I'm using Veins and it loads simulation in Sumo via TraCi. In this case the random_number is not been loaded properly. Sumo set random to false apparently in parse process.

To check parse behavior, I changed the value in overtaking.sumo.cfg to a invalid value:
```
<random_number>
       <random value='trsdue'/>
</random_number>
```
And included a debug WRITE_WARNING in OptionsCont::set() function (https://github.com/eclipse/sumo/blob/master/src/utils/options/OptionsCont.cpp#L249):
```
diff --git a/src/utils/options/OptionsCont.cpp b/src/utils/options/OptionsCont.cpp
index 8061dfd1e0..d2ebe7ff91 100644
--- a/src/utils/options/OptionsCont.cpp
+++ b/src/utils/options/OptionsCont.cpp
@@ -247,6 +247,7 @@ OptionsCont::getStringVector(const std::string& name) const {
 
 bool
 OptionsCont::set(const std::string& name, const std::string& value) {
+       WRITE_WARNING("set '" + name + "' = '" + value + "'");
     Option* o = getSecure(name);
     if (!o->isWriteable()) {
         reportDoubleSetting(name);
```
In sumo-gui directly, the tool tries to parse incorrect value and displays a error message: 
![sumo-gui](https://user-images.githubusercontent.com/30944827/100133445-8867a300-2e65-11eb-85f0-28c4a6aa4e74.png)
But using TraCi it loads default value false to random:
![traci](https://user-images.githubusercontent.com/30944827/100133442-87cf0c80-2e65-11eb-88e1-a0292a140410.png)

**Comment by tiagoasilva** [comment]
Issue also reported in sumo-user email "[sumo-user] Different probability flows between simulations"

**Comment by namdre** [comment]
As a workaround, try passing all config options as an option list in traci.load() instead of only setting **-c sumocfg**

**Comment by behrisch** [comment]
This is probably a GUI only problem. Can you run this without GUI and check whether the problem disappears?

**Comment by tiagoasilva** [comment]
Unfortunately, running without a UI had the same behavior:

![Captura de tela de 2020-11-24 20-57-58](https://user-images.githubusercontent.com/30944827/100165031-f75def80-2e97-11eb-9450-554a2ba02178.png)

**Comment by tiagoasilva** [comment]
Forcing the value to true in OptionsCont now works as expected:
```
tiago@tiago-inspiron-5448:~/src/sumo-git/sumo/build/cmake-build$ git diff ../../src/utils/options/OptionsCont.cpp
diff --git a/src/utils/options/OptionsCont.cpp b/src/utils/options/OptionsCont.cpp
index 8061dfd1e0..3aef7b87f7 100644
--- a/src/utils/options/OptionsCont.cpp
+++ b/src/utils/options/OptionsCont.cpp
@@ -246,16 +246,25 @@ OptionsCont::getStringVector(const std::string& name) const {
 }
 
 bool
-OptionsCont::set(const std::string& name, const std::string& value) {
+OptionsCont::set(const std::string& name, const std::string& value) {          
+       WRITE_WARNING("set '" + name + "' = '" + value + "'");
     Option* o = getSecure(name);
     if (!o->isWriteable()) {
         reportDoubleSetting(name);
         return false;
     }
     try {
-        if (!o->set(value)) {
-            return false;
-        }
+        if(name == "random"){
+        	WRITE_WARNING("Set random to true");
+        	if (!o->set("true")) {
+        		return false;
+        	}
+        }	
+        else {
+        	if (!o->set(value)) {
+        		return false;
+        	}
+        }
     } catch (ProcessError& e) {
         WRITE_ERROR("While processing option '" + name + "':\n " + e.what());
         return false;
```
Flow generates in first execution via traci (10s of simulation):
![Captura de tela de 2020-11-24 22-12-15](https://user-images.githubusercontent.com/30944827/100169543-840dab00-2ea2-11eb-837b-5695fb912fa5.png)

Flow generates in second execution via traci (10s of simulation):
![Captura de tela de 2020-11-24 22-13-24](https://user-images.githubusercontent.com/30944827/100169601-a1db1000-2ea2-11eb-9b8d-e2cad7b38c74.png)

Green vehicles are generated with probability='0.2', blue vehicles with probability='0.4' and red vehicles are fixed with period='3'.

So, I think that the problem is on caller of **OptionsCont::set()**

**Comment by behrisch** [comment]
We are no veins experts here. Can you say which command you issue on the Veins side to trigger the reload?

**Comment by tiagoasilva** [comment]
Dear @behrisch the Veins calls a new Veins simulation in each Sumo execution. So, the networks is a new one and not reloaded in each simulation. To do this, Veins uses sumo-launchd.py as a deamon for TraCI client. As explained in https://github.com/sommer/veins/blob/master/sumo-launchd.py#L27 it sends a file sumo-launchd.launch.xml containing sumo.cfg, rou and net files. I'm now changing sumo-launchd.py to print the contents of the  sumo.cfg and check that Veins is not changing the value of random before sending. As soon as I have the result I will put the result here.
Thanks!

**Comment by tiagoasilva** [comment]
Dear @behrisch and @namdre 

I found the source of the problem. Veins' **sumo-launchd.py** file is changing the value of random to false at this point: https://github.com/sommer/veins/blob/master/sumo-launchd.py#L372 . 
This was made by a change 9 years ago to migrate Veins to SUMO 0.13.0: https://github.com/sommer/veins/commit/2b8e64689a50d09172b2cdaf64068dd832dc2b50
I will contact the Veins community to check if we can remove this definition. I apologize for bothering you with this issue.

Best Regards!

**Comment by namdre** [comment]
Thanks for diving so deep and letting us know.
