### ISSUE TITLE
sumo --no-step-log and --duration-log.disable does not work in the remote server 

### ISSUE THREAD

**Issue by GyChou** [eclipse/sumo#7858]
I started sumo using the traci of the remote server and found that the parameter --no-step-log --duration-log.disable does not work
Here is a example code: (path need to be instead of your sumo example)
`from sumolib import checkBinary
sumoBinary = checkBinary('sumo')
cmd = [sumoBinary, "-c", path]
cmd.append('--duration-log.disable')
traci.start(cmd)`

**Comment by GyChou** [comment]
> I started sumo using the traci of the remote server and found that the parameter --no-step-log --duration-log.disable does not work
> Here is a example code: (path need to be instead of your sumo example)
> `from sumolib import checkBinary sumoBinary = checkBinary('sumo') cmd = [sumoBinary, "-c", path] cmd.append('--duration-log.disable') traci.start(cmd)`

**Comment by angelobanse** [comment]
you need to put the bool `true` to use the `--no-step-log` and `--duration-log.disable` options:

`cmd = [sumoBinary, "-c", path, "--duration-log.disable", "true", "--no-step-log", "true"]`

**Comment by behrisch** [comment]
This should not be necessary. @angelobanse Any idea why?

**Comment by angelobanse** [comment]
idk, should we reopen this issue?

**Comment by behrisch** [comment]
@GyChou Can you please report your python version and your platform?

**Comment by GyChou** [comment]
@behrisch python3.6.10
write 
<report>
<no-step-log value="true"/>
<duration-log.disable value="true"/>
</report> 
into .sumocfg file can solve the question.

cmd = [sumoBinary, "-c", path, "--duration-log.disable", "true", "--no-step-log", "true"]  doesn't work

**Comment by behrisch** [comment]
Can you please post your platform / operating system as well?

**Comment by GyChou** [comment]
I  test in local pc win10 python3.6 and remote server ubuntu1804 python3.6, both exist

![image](https://user-images.githubusercontent.com/30279942/101428975-c8865580-393c-11eb-8a6e-1dc7d3c3f5ab.png)
  
![1607392817(1)](https://user-images.githubusercontent.com/30279942/101428726-439b3c00-393c-11eb-84cd-db7870291e80.jpg)
