### ISSUE TITLE
Change lc (lanechange) parameters on runtime using traCI in python

### ISSUE THREAD

**Issue by mateen-malik** [eclipse/sumo#7862]
Hi,

I want to change the parameters values on runtime using traCI in python.
The parameters which i am interesting mostly in are such as, 

lcSpeedGain="xx"
lcLookaheadLeft="xx"
lcAssertive="xx"
lcPushy="xx"  etc
maxSpeed="xx"    #the "xx" value i want to play with during runtime
speedDev="xx"
emergencyDecel="xx"
speedFactor="xx"
minGap="xx"
departSpeed="xx"
departLane="xx"

detail list of paramets are in the link below which i want to access and change on runtime.

https://sumo.dlr.de/docs/Definition_of_Vehicles,_Vehicle_Types,_and_Routes.html

How can i do that?

need some help regarding this.

Thanks in advance.

best regards,
/Mateen

**Comment by behrisch** [comment]
Please read the TraCI documentation https://sumo.dlr.de/docs/TraCI/Change_Vehicle_State.html and possibly follow the TraCI tutorials https://sumo.dlr.de/docs/Tutorials.html then try to ask a more specific question. Most of the parameters are directly changeable using TraCI commands but it very much depends on which programming language you choose for your client. Parameters influencing only departure (such as departSpeed and departLane) cannot be changed via TraCI.
