### ISSUE TITLE
how ACC car following model interacts with other vehicles models such as Krauss car following model in Sumo Env?

### ISSUE THREAD

**Issue by mateen-malik** [eclipse/sumo#7864]
Hi,

I wish to know if there is a way to visualize and log all the parameters related to the interaction of ACC car following model with other vehicles models such as Krauss in Sumo environment?

I wish to understand how vehicles interact with with vehicles in Sumo environment. How a vehicle know that there is a vehicle infront and i have to brake or change lane etc?

Thanks in advance,

Best regards,
/Mateen

**Comment by namdre** [comment]
in the latest development version you can use options
**--fcd-output fcd.xml --fcd-output.max-leader-distance 300** to obtain a log of all car-following releations (egoSpeed, leaderSpeed, gap etc).

For visualization you can use https://sumo.dlr.de/docs/Tools/Visualization.html#plot_trajectoriespy

The simulator uses the internal network graph to inform every vehicle of it's leader vehicle properties. You can access this at runtime using 'traci.vehicle.getLeader'.
