### ISSUE TITLE
Netedit: Checking issues in 'Fix demand elements problems' window is not possible on Windows

### ISSUE THREAD

**Issue by ZoltanBaksa** [eclipse/sumo#7868]
Hi,
I use the latest dev. version v1_7_0+1189-3037b6cc19.
I have generated routes from vehicle trajectories, and I wanted to check them in Netedit. If I want to save the loaded demand again, a window pops up with the invalid routes. Because the map matching of the original data is done outside SUMO environment, the list is quite long. which means I have a generic problem and it needs some re-processing to figure out the root causes. Would it be possible to save this issue list in a separate log file?
If there would be a shorter list. it still problematic to check the problems, since the size of the window and the columns are fixed, therefore the actual conflict text is not readable.
If test files are needed, I can send them per mail.
Regards
Zoltan

**Comment by ZoltanBaksa** [comment]
If I can suggest, a possible solution could be, when the user click on 'Save invalid routes' button to add the found issue as an xml comment next to the problematic route.

**Comment by palvarezlopez** [comment]
@ZoltanBaksa I have separated the Fix demand elements dialog in four categories (routes, vehicles, stopPositions and personPlans), and now  a log file for every category can be generated clicking in "saving" button. I hope this is useful for you :)

Regards
