### ISSUE TITLE
allow restricting persons that can enter vehicle at stop

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#7869]
currently, only the taxi device can restrict boarding.

The problem happens if a a vehicle stops twice at the same stop and the person that waits at the stop should only enter on the second stop. Currently, the person may enter at the first stop which causes the followig problems
- person takes up passenger capacity and may thus prevent others from entering as planned
- If the second stop is using triggered/expected the vehicle even fails to continue because the person does not enter at that stop

Possible solution:
- ~~reinterpret stop attribute 'expected' as an exclusive list.~~
- add new stop attribute 'permitted' which defines a list of persons that may enter (but does not require them)

**Comment by namdre** [comment]
Problem with backward compatibility:  expected might actually be used with the semantic of "wait for this person but allow all others to enter": #5092

**Comment by ArmelliniMG** [comment]
The possibility of using both options would also be relevant - > _expected = "person0" permitted="person0"_ ensures that the vehicle will wait to person0 and that only that person may enter the vehicle
