### ISSUE TITLE
--fcd-output.max-leader-distance not working

### ISSUE THREAD

**Issue by mateen-malik** [eclipse/sumo#7872]
this is related to issue #7864

Thanks a lot for your generous and quick help in issue #7864,

I manage to use one of the command told to me i.e. --fcd-output fcd.xml

However, couldn’t use this command --fcd-output.max-leader-distance 300
Got the following error when using via CMD

 C:\Users\mateenma\Downloads\Installed SW\sumo-1.7.0\doc\examples\sumo\demo_mat_1>sumo -c demo.sumocfg --fcd-output.max-leader-distance 300
Error: On processing option '--fcd-output.max-leader-distance':
 No option with the name 'fcd-output.max-leader-distance' exists.
Error: The parameter '300' is not allowed in this context.
 Switch or parameter name expected.
Error: Could not parse commandline options.
Quitting (on error).
Quitting (on error).

Wondering what I am doing wrong here ☹

and also how can i log this data in file for later analysis?

Thanks again for your generous and quick help,

best regards,
/MM

**Comment by namdre** [comment]
feel free to keep posting in an old issue when you have further questions that are closely related. To use **--fcd-output.max-leader-distance** you must use the latest development version (https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_development_version ) or wait until next tuesday for the release of version 1.8.0.
