### ISSUE TITLE
A scenario in SUMO simulator

### ISSUE THREAD

**Issue by amiradavoudi** [eclipse/sumo#7873]
Hello, 

I wish to simulate a scenario in SUMO as follows:

I wish to define some vehicles that are randomly located in a residential area on the network, and then these vehicles will move to their corresponding workplace that is located randomly in the industry place on the map. Afterward, these vehicles are expected to return to their corresponding residential area. 
I also wish that each vehicle move according to a daily schedule. Which demand generation would suit my scenario? 
According to the link below, there are a few methods but I am a little bit confused about which one is more suitable for my scenario. 

https://sumo.dlr.de/docs/Demand/Introduction_to_demand_modelling_in_SUMO.html
Thank you in advance for your attention.

**Comment by namdre** [comment]
Possible options:
- SAGA (https://github.com/lcodeca/SUMOActivityGen)
- https://sumo.dlr.de/docs/Demand/Activity-based_Demand_Generation.html (less sophisticated)
- randomTrips (https://sumo.dlr.de/docs/Tools/Trip.html#randomtripspy) combined with own scripting to create the return journey.

**Comment by amiradavoudi** [comment]
Dear Jakob,

Thank you very much for your quick response.


Best regards,

Amirhossein Adavoudi Jolfaei

________________________________
