### ISSUE TITLE
questions about vehPerHour.

### ISSUE THREAD

**Issue by Sheldon-Zhou1997** [eclipse/sumo#7878]
If there is a two-lane edge and it is 10 flow's source edge, each flow defined by vehPerHour = 1, how does the edge generate vehcles? Every vehcle generate in 900s ? But there is no space for 10 vehcles when all vehcles was generated in 900s.

**Comment by behrisch** [comment]
If the flows are identical, sumo will generate 10 vehicles at exactly the same time but It depends on the [depart position](https://sumo.dlr.de/docs/Definition_of_Vehicles,_Vehicle_Types,_and_Routes.html#departpos) and the length of the edge whether they will be inserted immediately. With the default "base" the insertion will probably be delayed until the previously inserted vehicle left the position.
