### ISSUE TITLE
Documentation Simulation/Public Transport: Transport Schedules

### ISSUE THREAD

**Issue by FrederikRB** [eclipse/sumo#7883]
Hello.

In the chapter simulation/public transport of the documentation, there is a subtopic "transport schedules" (right before passengers) which seemed to be incomplete. Does it supposed to reveal additional information to the subtopic of "public transport schedules"?

Thank you.

**Comment by namdre** [comment]
Thanks. That section was superfluous.
I added some more information here: https://sumo.dlr.de/docs/Simulation/Public_Transport.html#further_schedule_attributes

**Comment by FrederikRB** [comment]
Thank you. :)
