### ISSUE TITLE
E2 detectors negative length not having any effect on GUI

### ISSUE THREAD

**Issue by balbok0** [eclipse/sumo#7894]
Hi!

When (in `netedit`) I add an E2 detector on a lane between two junctions, I seem to always run into 2 issues:

1. length cannot be set to a negative number. This is contradictory to the [documentation](https://angelobanse.github.io/sumo-documentation2/NETEDIT.html#lane_area_detectors_e2) ("As a real detector has a certain length, "length" must be supplied as a further parameter. It may be a negative number which let the detector be extended, upstream to the given start position")
2. length seems to have no effect on the position of the detector. The detector is always defined between _pos_ and the start of the lane.

Both of these problems do not allow me to add E2 detectors in front of traffic lights (which are near the end of the lane).

Thank you in advance! Is there additional information I should provide for debugging purposes?

**Comment by namdre** [comment]
1) the documentation you have linked is invalid (negative lengths are not permitted). Please refer to https://sumo.dlr.de/docs/netedit.html#lane_area_detectors_e2
2) There is a visualization bug: #7895 (Thanks for bringing this to our attention). When in doubt, check the saved objects in sumo-gui which will show the correct placement

also see https://sumo.dlr.de/docs/Simulation/Output/Lanearea_Detectors_(E2).html#instantiating_within_the_simulation for additional definition styles (not all of those are supported by netedit).
