### ISSUE TITLE
refactor use of NBLoadedSUMOTLDef as GNEAttribute carrier (maybe)

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#7898]
- pro: tls has some standard attributes: tlType, programID, offset, genericParameters
- con: key features are not attributes in the classic sense:
  - id:  is shared with multiple definitions
  - tlLayout: is only used to shape the new signal plan when resetting - basically the whole thing must be replaced
  - phases are child elements rather than attributes (complicated dependency structure from netbuilder has to be replicated on the netedit side) - I'm worried that this will waste a lot of time.

Currently missing features from TLS-Frame
1) change id,
1) change tlType
1) recompute plan (i.e. by selecting a layout)
1) #7659 
1) change  programID, 
1) signal plan editor with inverted layout (time on the x-axis, shift switch points per signal)

I'm not sure it would be easier to support the new features with an attribute carrier structure.
We could also add UI for (1-3) that work by performing changes on GNEJunction since the functionality is already supported and add extra widgets for 4 and 5

Feature 6 is orthogonal to the whole debate.

@palvarezlopez discuss!

**Comment by palvarezlopez** [comment]
I think we have to use Attribute Carriers for TLSs


Basic Hierarchy:

- A GNEJunction owns 0 oder 1 GNETLS
- There is a container in GNENet with 0 oder more GNETLSPrograms
- A GNETLSProgram have one 0 oder or more phases

**Comment by palvarezlopez** [comment]
@namdre I have an idea about GNEChange_TLS:

Currently, in GNEChange_TLS we have a pointer to an NBTrafficLightDefinition. This could produces inconsistences during undo-redo sequence. My solution is:

1) GNEChange_TLS  has a static NBTrafficLightDefinition member instead a pointer 
2) Before every change (id, phase, parameters, etc.) we make a copy of NBTrafficLightDefinition (**NBTrafficLightDefinitionPrevious**), then we apply the change, and therefore we obtain a modified NBTrafficLightDefinition  (**NBTrafficLightDefinitionModified**)
3) A GNEChange_TLS has as input the two **NBTrafficLightDefinition** (Previous and Modified), then:
 3.1) redo() function replaces current NBTrafficLightDefinition in Junction with NBTrafficLightDefinitionModified, 
 3.2) undo() function replaces current NBTrafficLightDefinition in Junction with NBTrafficLightDefinitionModified,

**Comment by namdre** [comment]
> Currently, in GNEChange_TLS we have a pointer to an NBTrafficLightDefinition. This could produces inconsistences during undo-redo sequence. My solution is:

It isn't producing inconsistencies now because NBTrafficLightDefinition are not deleted until closing the application (they are instead stored in the set NBTrafficLightLogicCont::myExtracted.

**Comment by palvarezlopez** [comment]
With inconsistencies I mean, for example, the value of an attribute (ej: offset). GNEChange_Attribute stores the old and new value of a XMLAttribute, but if we want to do the same operation with GNEChange_TLS, we need to create a constructor for edit offset, another constructor for edit ID, another for ever phase, etc.

**Comment by namdre** [comment]
as discussed previously: we stick to using GNEChange_TLS
