### ISSUE TITLE
Lane link problem

### ISSUE THREAD

**Issue by radiateboy** [eclipse/sumo#7905]
![图片1](https://user-images.githubusercontent.com/9248754/100992772-8b624200-358f-11eb-8176-80aceeb638bd.png)
Road link relations are 1-4, 2-5, at the time of the simulation run, lane 1 vehicles will drive into the lane 4, lane 2 cars will drive into the lane 5, but the traffic lane 3 will disappear after the node, not like in real life the driver will wait for security clearance into the lane 5, I try to track lane 3, and 5 link, but according to conflict, there is no way to establish the link between the two lanes, the lane if I want to lane 2, and 3 of the vehicle can find their own space into the lane 5, how to set?

**Comment by angelobanse** [comment]
open the network file in `netedit` and in the `Network` supermode, inspect the node (junction). Change it to type `zipper` and then in `Connection mode` select lane 3 and hold `Ctrl` and click on lane 5, to create the connection.

**Comment by namdre** [comment]
On motorways on-ramps the connection layout where lane 3 is a dead-end is preferred because this forces vehicles to change lanes at the earliest convenience rather than driving to the end and waiting for a gap in traffic.
Zipper makes the right-of-way symmetrical. You can also leave the junction type as 'priority' which will make the driver on the right lane always yield to the left lane.

**Comment by radiateboy** [comment]
> open the network file in `netedit` and in the `Network` supermode, inspect the node (junction). Change it to type `zipper` and then in `Connection mode` select lane 3 and hold `Ctrl` while clicking on lane 5, to create the connection.

![1607329207(1)](https://user-images.githubusercontent.com/9248754/101327115-31bc8900-38a9-11eb-8311-5110781f167d.jpg)
The zipper type operation will report an error when the route from 3 lanes becomes 1 lane.

**Comment by radiateboy** [comment]
> On motorways on-ramps the connection layout where lane 3 is a dead-end is preferred because this forces vehicles to change lanes at the earliest convenience rather than driving to the end and waiting for a gap in traffic.
> Zipper makes the right-of-way symmetrical. You can also leave the junction type as 'priority' which will make the driver on the right lane always yield to the left lane.

![图片1](https://user-images.githubusercontent.com/9248754/101327807-2fa6fa00-38aa-11eb-8289-830f73533345.png)
Intersection type of connection is traffic_light intersection, lane 1 and 2 are straight to the lane 3, in the real road, lane lane 1 and 2 vehicles will alternate with passage to lane 3, but is always in the sumo lane 1 cars after all through the lanes of 2 vehicles to get the right of way, so how to adjust to this kind of love is more realistic traffic.

**Comment by namdre** [comment]
A zippered traffic light is not supported but both your use cases can be solved with staggered junctions
 - 3-to-1: place two successive zipper junctions where each junction merges two lanes
 - equal opportunity merge after tls: use two outgoing lanes after the traffic light and merge them with zipper shortly afterwards
