### ISSUE TITLE
Inconsistent downloads at the latest development versions

### ISSUE THREAD

**Issue by ZoltanBaksa** [eclipse/sumo#7909]
Hi,
not all Windows downloadables are updated on the downloads site, the Windows 32bit and 64 bit installer and the Windows 64bit with GDAL, FFmpeg, OSG, GL2PS, SWIG packages are stuck at November 30.
Regards
Zoltan

**Comment by behrisch** [comment]
Sorry about that, the nightly windows build is experiencing problems.

**Comment by namdre** [comment]
could this have affected the release downloads?

**Comment by behrisch** [comment]
Well it did because I had to start the extra build manually. But apart from that I don't think so. Curently the server just fills with some broken instances and the process fails to kill them properly and even the scheduler cannot kill the build process so the next day everything hangs :-(

**Comment by behrisch** [comment]
The osg tests seem to crash even more than they used to, delaying everything.

**Comment by behrisch** [comment]
Immediate problem seems to be solved, work continues in #7914

**Comment by behrisch** [comment]
hanging again

**Comment by behrisch** [comment]
resaon was #8073
