### ISSUE TITLE
Multi thread parallel simulation

### ISSUE THREAD

**Issue by Shiyunyang-seu** [eclipse/sumo#7913]
Hi, how can I call traci.simulationStep ()  twice at the same time ,and the two sumo processes to simulate each other?（whether I can use the same simulation step to control multiple sumo processes）
Thanks in advance!

**Comment by behrisch** [comment]
You cannot. You enable two connections to different processes and either use the connection objects and call step on each of them or if you prefer to let traci handle the connections you do
```
traci.switch("con1")
traci.simuationStep()
traci.switch("con2")
traci.simuationStep()
```

**Comment by Shiyunyang-seu** [comment]
Thanks for your answer. Is there any other way to speed up the simulation? I try to set the step length to 2, but the GUI shows that some vehicles will move instantaneously over the other. At the same time, when the network becomes larger and the number of vehicles increases, the simulation seems to slow down.

**Comment by behrisch** [comment]
This is not useful for speeding up a single simulation but for accessing two separate instances. For speeding up see https://sumo.dlr.de/docs/FAQ.html#how_can_i_make_the_simulation_run_faster

**Comment by JamesPsh** [comment]
@behrisch Hello.

I tried multi-thread parallel simulation, and it seems to run without any problem.
I used the threading and multiprocessing libraries.

Could you please review my code?

**Comment by behrisch** [comment]
It looks fine to me, it just will not speed up simulation considerably
