### ISSUE TITLE
When does SUMO produce an inner edge

### ISSUE THREAD

**Issue by radiateboy** [eclipse/sumo#7917]
![1607332507(1)](https://user-images.githubusercontent.com/9248754/101332980-fde56180-38b0-11eb-9b16-ae4c92678642.jpg)
At first, I thought that just going straight and turning left would produce edges like gneJ3_20_0, : gneJ3_21_, : gneJ3_22_0, : gneJ3_23_0, : gneJ3_24_0, but it doesn't!
![1607332635(1)](https://user-images.githubusercontent.com/9248754/101333417-8e23a680-38b1-11eb-8f97-ba58472323b9.jpg)
Not all the places where going straight and turning left collide produce edges like gneJ1_13_0,:gneJ1_12_0, so under what circumstances does SUMo produce edges like gneJ1_12_0?

**Comment by namdre** [comment]
The internal junctions that split internal lanes into two parts are generated whenever the left turning traffic is permitted to wait inside the intersection area for oncoming straight traffic:
- at traffic lights
- at priority junctions when turning from the priority road
