### ISSUE TITLE
OSM map Georeferencing - coordinates conversion? 

### ISSUE THREAD

**Issue by zmajstorovic** [eclipse/sumo#7922]
Hello, 

I found out that my map is not georeferenced properly. The map is imported from OSM, and I expected that it will be properly georeferenced but for some reason, it's not. 

Is there any formula or procedure on how to georeference a map? I know that somehow I need to shift the map, but I don't know how much I need to decrease/increase the numbers in _.net.xml_ file.  

In my _.net.xml_ file I have following line 
`<location netOffset="-553876.04,-5070797.99" convBoundary="0.00,0.00,27232.63,13860.45" origBoundary="15.695505,45.786086,16.046752,45.910209" projParameter="+proj=utm +zone=33 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"/>
`
I tried to change numbers but I can't match the coordinates. 

This is the sketch of the current situation: 
![image](https://user-images.githubusercontent.com/18489380/101393543-8f5fce00-38c7-11eb-8415-77bdf1da229b.png)

When I click on the green circle and copy the geo-coordinates to google maps it positions me on the red circle. The orange circle is the location of coordinates in .net file.

**Comment by namdre** [comment]
1. can you provide the osm input file and generated network?
2. was the osm input obtained directly from the osm database or could it have been modified somehow?

**Comment by zmajstorovic** [comment]
To answer the second question: the OSM map is downloaded from OSM servers and then I filtered all the unnecessary data using the JOSM tool. After filtering all irrelevant data I created .net file and edited it through the NetEdit tool. 

Info about files in the attachment:
_planet.osm_ is the initial file downloaded from OSM server
_planet3.osm_ is filtered map, I items filtered by tags all unnecessary items from map
_planet32.net.xml_ - planet file made from planet3.osm which is again edited (removed some roads and corrected some junctions)

[Files.zip](https://github.com/eclipse/sumo/files/5659300/Files.zip)

**Comment by namdre** [comment]
When loading Zagreb data directly from the OSM server, georeferencing works fine. I suspect that the invalid offset somehow originates in the JOSM processing. I noticed that the OSM entities were saved with negative ids which customarily indicates altered data (I'm not sure if mere filtering should cause this).
Note, that you can also do your filtering with the osmfilter tool (https://wiki.openstreetmap.org/wiki/Osmfilter) as well es directly with netconvert (`--keep-edges.by-type  highway.motorway,highway.motorway_link,highway.secondary,highway.secondary_link,highway.tertiary,highway.tertiary_link,highway.trunk`)

See also https://sumo.dlr.de/docs/Networks/Import/OpenStreetMap.html#recommended_netconvert_options
