### ISSUE TITLE
Unrealistic stop at an intersection

### ISSUE THREAD

**Issue by zhuhj-tery** [eclipse/sumo#7925]
Hello,
When I used the latest version of SUMO to conduct a simulation in a complex network, I encountered an issue as shown in the following figure. There was one vehicle stopping at the junction, while there are no blocking vehicles. This stop was unrealistic and confused me. I also noticed this unrealistic stop appeared at other junctions if there was a connection with the direction of "partial right". Is there any reason for the stop? I also attach the source files here. Thanks.
![image](https://user-images.githubusercontent.com/69643560/101423552-60495c80-38c7-11eb-9301-1d8c1b186dfa.png)
Best,
Haojie
[source-files.zip](https://github.com/eclipse/sumo/files/5656150/source-files.zip)

**Comment by namdre** [comment]
I cannot reproduce the stop issue. Can you state the exact time and vehicle id?

**Comment by zhuhj-tery** [comment]
I can provide some details related to the simulation. I used the sublane model by setting the lateral resolution to be 0.25. And the time step is set as 0.1 s. The stop issue is a little bit random, but it also occurs at other locations:
![image](https://user-images.githubusercontent.com/69643560/101502033-77776100-393e-11eb-950f-f9479728e1fb.png)
(vehicle 0.20 stops at239.10s, junction 703)
![image](https://user-images.githubusercontent.com/69643560/101502362-dc32bb80-393e-11eb-815d-f78df29c2bc1.png)
(vehicle 0.119 stops at 725.5s, junction 548)
![image](https://user-images.githubusercontent.com/69643560/101502656-329ffa00-393f-11eb-9402-0399c9576420.png)
(vehicle 4.165 stops at 1093.7s, junction 92)
![image](https://user-images.githubusercontent.com/69643560/101502781-5bc08a80-393f-11eb-9efe-c7465b352318.png)
(vehicle 0.172 stops at 1114.4s, junction 669)
The stop issue also occurs at junction 648 and junction 720 of my network. The vehicle will stop unrealistically and then start again after a few seconds.

**Comment by ZoltanBaksa** [comment]
I have also found similar a issue in case of roundabouts, when there are vehicles partly on a leaving arm. In my case I did not used sublane model. Also there are vehicles in the roundabout, which brake before a junction without any reason.

**Comment by namdre** [comment]
@ZoltanBaksa I think yours is an unrelated issue because the problem above is tied to the sublane model. Please provide failure examples.

**Comment by ZoltanBaksa** [comment]
Hi Jakob,

Here is a small scene from my city simulation. The issue I found is at 00:01:43

Regards
Zoltan

Feladó: Jakob Erdmann <notifications@github.com>
Küldve: 2020. december 9., szerda 7:49
Címzett: eclipse/sumo <sumo@noreply.github.com>
Másolatot kap: Baksa Zoltan (PS-TC/ENG12-Bp) <Zoltan.Baksa@hu.bosch.com>; Mention <mention@noreply.github.com>
Tárgy: Re: [eclipse/sumo] Unrealistic stop at an intersection (#7925)


@ZoltanBaksa<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FZoltanBaksa&data=04%7C01%7Czoltan.baksa%40hu.bosch.com%7C3ee17b53074348ace07e08d89c0e8157%7C0ae51e1907c84e4bbb6d648ee58410f4%7C0%7C0%7C637430933394425787%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=7wclNdg%2BkE2L4W0eJIAuP9DpKTs2EEb6kov%2B8IbPMgw%3D&reserved=0> I think yours is an unrelated issue because the problem above is tied to the sublane model. Please provide failure examples.

**Comment by ZoltanBaksa** [comment]
Hi @namdre,
I sent you a test scene about a one laned roundabout via email.

**Comment by namdre** [comment]
@zoltan Thanks for the example. It's a case of #4811
The problem is a lot more obvious in a roundabout though.

**Comment by namdre** [comment]
> @zoltan Thanks for the example. It's a case of #4811
I have to retract that. 
- The vehicle coming from the NE is waiting due to a blocked exit (somewhat reasonably, see explanation in #7936) 
- The vehicle coming from the SE is waiting due to a regression in #6766 (now reverted)

**Comment by zhuhj-tery** [comment]
@namdre Thanks for the revision. However, the issue has not been solved completely. When simulating with the same source files, I still encounter the similar issue using the latest version. Here is an example:
![image](https://user-images.githubusercontent.com/69643560/101659877-83cded80-3a14-11eb-9d93-316938cb60d3.png)
(vehicle 2.1, at 126.4 s, junction: 669)
I also find the foes of vehicle 2.1:
![image](https://user-images.githubusercontent.com/69643560/101660170-de674980-3a14-11eb-8b9a-12244a3237f6.png)
(the blue vehicle: vehicle 1.14)
Previously, the foe vehicle is just the rear vehicle and the situation has been changed by fixing the bug. Maybe, further revision is needed. Thanks.

**Comment by zoltan** [comment]
@ZoltanBaksa is not @zoltan, FYI.

**Comment by namdre** [comment]
@zhuhj-tery Please re-open if you find more oddities.
