### ISSUE TITLE
Does Traci has a method to determine whether a pedestrian collided with a car while crossing the road

### ISSUE THREAD

**Issue by GyChou** [eclipse/sumo#7926]
Does Traci has a method to determine whether a pedestrian collided with a car while crossing the road？

I read the documentation, but I didn’t find a suitable method

**Comment by namdre** [comment]
Currently not (#7728). A workaround would be to retrieve all vehicles in a small radius around a person (or vice versa) using context subscription and to detect overlap geometrically.
