### ISSUE TITLE
How to let the vehicle randomly choose the lane

### ISSUE THREAD

**Issue by radiateboy** [eclipse/sumo#7928]
![1111](https://user-images.githubusercontent.com/9248754/101480955-5b4fe000-398f-11eb-8e61-3e6e29cb9ae3.png)
Vehicles in one lane can travel to the opposite 2/3/4 lane, but in the process of running, almost all vehicles in one lane will travel to the opposite 2 lane. How to make the vehicles in one lane drive to the opposite 2/3/4 lane randomly

**Comment by namdre** [comment]
If the edge beyond the junction is the arrival lane then you can set vehicle attribute `departLane="random"`.  Otherwise, the chosen lane depends on how the vehicles can best continue their route. They will select a connection that minimizes future lane changes.

**Comment by namdre** [comment]
I have to retract part of my earlier statement. I meant to say `arrivalLane="random"` (a typo) but in fact that input value is not supported yet (#7932). 
You could however define individual vehicles with arrivalLane="N" where n is a random valid lane number (i.e if you are generating input with a script).

**Comment by namdre** [comment]
And I retract my earlier retraction: in the github master branch arrivalLane="random" is now supported. You can obtain updated binaries tomorrow at https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_development_version
