### ISSUE TITLE
non deterministic results for Person::movetoxy

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#7933]
The test complex/traci/person/moveToXY/keepRoute1_junction/ fails for about three months. The changing commit was bcb4b562022e4ae802ce1483d16ef3207172d818 but in trying to reproduce it, it appears to be a Heisenbug. A possible explanation is that the set used in Helper::collectObjectsInRange may return the candidate lanes in different orders due to memory layout. Maybe we can switch to numerical ids instead of memory addresses here.

**Comment by namdre** [comment]
Since there is a complex heuristic that picks the best mapping lane, the only way ordering could have an influence here, is for two candidate lanes to get the same heuristic fitness value. This is quite unlikely and may also indicate an issue with the heuristic.

**Comment by behrisch** [comment]
But it seems to happen at least on a junction.

**Comment by behrisch** [comment]
Either it is not fixed or creeped back in. At least the test fails in a similar fashion on Linux again.

**Comment by namdre** [comment]
the clang debug build shows no other signs of undefined behavior.

**Comment by behrisch** [comment]
Unfortunately not, still failing here (occasionally).
