### ISSUE TITLE
invalid stop due to checkRewindLinkLanes at roundabout

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#7936]

**Comment by namdre** [comment]
on second thought it may be a good idea to stop outside a roundabout if the exit is blocked. After all there might be cross traffic that leaves on a different unblocked exit

**Comment by ZoltanBaksa** [comment]
I would say, this stopping behaviour should be a vehicle type option, because this depends on the driver. In 99 % cases in Hungary the drivers go in to the roundabout, if it is possible, even if they will block others. I saw similar behaviour also in Germany to, but not with that high probability.

**Comment by namdre** [comment]
The no-block behavior can already be configured via `jmIgoreKeepClearTime`. Do you think it is necessary to distinguish roundabout and non-roundabout keep-clear behavior?

**Comment by ZoltanBaksa** [comment]
I think yes, because the `jmIgnoreKeepClearTime` parameter is suggest that it will affect junction behaviour.
A roundabout might have multiple junctions based on the topology, and even the visibility varies due to circle size or slope at entry or the height of the mound in the middle. Due to these circumstances this is different from the keep clear behaviour in an intersection which is a True/False setting for the junction and a kind of grace period for all drivers at the specific junction.

**Comment by namdre** [comment]
If the behavior of "entering a roundabout with jammed exit" is dependent on locality (i.e. visibility from the entry edge) than you are free to set keepClear=False for the affected entering connections (setting this for a whole junction is only a convenience feature, keepClear is always disabled while inside a roundabout).
If this is more of a driving style issue then it might be strongly correlated with a general driving style of "entering any kind of junction with jammed exit". In this case it would be over-engineering to invent an new parameter.
But if you are fairly confident that 99% of drivers would enter the roundabout while they would tend to keep normal intersections clear, than I'm fine with adding another parameter ("jmIgnoreKeepClearRoundaboutTime") which you could then set to 0 to reflect Hungarian driving (-:

**Comment by ZoltanBaksa** [comment]
I give a try to set up some scenes with the existing parameters, to not increase the parameter number.
The observed Hungarian behaviour in driving style is probably one of the main reasons, why do we have many traffic jams at roundabouts. In relative high percent of the cases even the blinker is not used before exiting the circle to help to the entering vehicles, so they can enter.
