### ISSUE TITLE
How can I divide my random network to different areas? #7937

### ISSUE THREAD

**Issue by amiradavoudi** [eclipse/sumo#7938]
Hello,

I want to generate let's say a random grid network (7*7) via the tool  **netgenerate** in SUMO and then for example divide the generated grid map in to two different areas; 1-residential area 2-working area. Then I want to use **randomTrips.py** tool to generate vehicles randomly in the residential area moving to the working area.

Would you please help me how to divide the map in to two areas as explained above? And does it make sense to use **randomTrips.py** for such a scenario?

Thank you in advance for your consideration.

**Comment by namdre** [comment]
randomTrips is not well suited to the task (though you could load custom source and sink probabilities to model the desired mobility pattern). It should be easier to
1. define two TAZ elements in netedit (draw a polygon to define each area)
2. define a 2x2 od-matrix (by copying from the examples at https://sumo.dlr.de/docs/Demand/Importing_O/D_Matrices.html
3. run od2trips

**Comment by amiradavoudi** [comment]
Thank you very much for your quick help.
