### ISSUE TITLE
update "Choosers" during simulation

### ISSUE THREAD

**Issue by rummel123** [eclipse/sumo#7942]
If I have an open "Chooser" window, to search for elements in the simulation (persons, edges, ...) the elements list do not update during the simulation. For **persons, vehicles** and **containers** I have to open the Chooser again and again, if I wait and search for a special element that is not already inserted.
Alternatively also the currently not inserted elements could be listed there?

**Comment by namdre** [comment]
Updating the entity list requires locking the simulation. An auto-update feature would therefore slow down the simulation.
a refresh button would be possible though (and could be made to refresh all open chooser dialogs).

What would your use case look like for listing elements that are not yet in the simulation?

If you wish to advance the simulation to a point where some object is visible, it might be more useful to run the simulation with option `-S -B someBreakpoint`

**Comment by behrisch** [comment]
+1 for the refresh button

**Comment by rummel123** [comment]
+1 for refresh button
If there are problems with elements, I want to track them before the problems occure, to analyse the possible reason for that.
