### ISSUE TITLE
Can sumo grab data with Wireshark? What should I do?

### ISSUE THREAD

**Issue by KangChou** [eclipse/sumo#7944]
Can sumo grab data with Wireshark?
What should I do?

**Comment by namdre** [comment]
Assuming this is about traci:
- If client and server run on the same machine, It depends on your operating system (or require additional software): https://wiki.wireshark.org/CaptureSetup
- if client and server run on different machines it should work

However, if you have questions about the protocol you can just ask directly and don't need to capture the traffic.

**Comment by KangChou** [comment]
I really appreciate your reply, but I still haven't solved the problem.
Can you provide a detailed operation tutorial?
Very emotional!
![image](https://user-images.githubusercontent.com/36963108/103076477-c690e780-4608-11eb-9822-86395e65b8ee.png)

**Comment by namdre** [comment]
No, I cannot give you a wireshark tutorial since I never tried to use this with sumo myself. What are you trying to accomplish?
