### ISSUE TITLE
How can I automatically divide a random generated grid or spider to several TAZs?

### ISSUE THREAD

**Issue by amiradavoudi** [eclipse/sumo#7945]
Hello,

For a scenario, I have created about 500 random grids and spider with the help of **netgenerate** tool in SUMO. 
I want to divide all these generated grids in to different _random_ TAZs _automatically_ as creating TAZs using the netedit (draw a polygon to define each area.) for all these grids is tedious.
 
Is there any available script to do so? Could you please help me how I can achieve this?

Thank you very much.

**Comment by behrisch** [comment]
There is currently no tool I know of which does this and you probably have many things to consider (connectivity of the taz, size, etc.) which makes writing a script your self the best solution.

**Comment by namdre** [comment]
actually there is a tool it was just lacking documentation (#7946). See https://sumo.dlr.de/docs/Tools/District.html#griddistrictspy
