### ISSUE TITLE
Feature Idea: OSM Web Wizard vehicle type proportion

### ISSUE THREAD

**Issue by M-Colley** [eclipse/sumo#7953]
Hey, using the OSM Web Wizard is really easy and great!

However, I wondered whether it would be useful to be able to define additional car parameters. For example, defining the vehicle types (e.g., autonomous and manual, or SAE based) and the proportion (e.g., 80% manual, 20% autonomous) could avoid the necessity to define this afterward in the file.

Do you consider sth like this useful?

Thanks for considering.
Kind regards

**Comment by namdre** [comment]
Thanks for the suggestion.
The range of possible customization is huge. Also, there is no agreed upon definition on how to best model any given SAE level via microscopic model parameters.
Therefore, I think that putting in 1 or even 10 additional sliders would give a wrong impression on the properties of the resulting simulation.
