### ISSUE TITLE
Netedit: Edit Traffic Light mode, enhancement at timing

### ISSUE THREAD

**Issue by ZoltanBaksa** [eclipse/sumo#7962]
Hi,
It would be very helpful, if there would be a cumulated time from cycle begin, next to each phase, which is obviously recalculated at every change. This way it would be more easy to debug the program.
An alternative enhancement would be to draw the program's timing diagram in a separate window by re-using the 'show phases' feature from sumo-gui.

**Comment by namdre** [comment]
@palvarezlopez has plans to build an alternative tls-editor dialog with the usual time-in-seconds-is-horizontal layout

**Comment by palvarezlopez** [comment]
@ZoltanBaksa this work as expected?
