### ISSUE TITLE
How to record the time of vehicles at every junction and a point on an edge?

### ISSUE THREAD

**Issue by amiradavoudi** [eclipse/sumo#7969]
Hello, 

I have generated a grid network with the help of **netgenerate** in SMUO, and have generated some randomly vehicles using the **randomTrips.py** that move on the map.

1- How can I record the exact time of each vehicle when passing through _a junction_ on a map?
2- How can I record the exact time of each vehicle when passing through _an exact point_ on an edge, for example in the middle of each edge, on a map?

Thank you very much in advance for your consideration.

**Comment by namdre** [comment]
see https://sumo.dlr.de/docs/Simulation/Output/Instantaneous_Induction_Loops_Detectors.html
Place them at any location on an edge.
To record time at junctions, either place them
- on the end of the incoming edge (pos = -0.1) 
- at the start of the outgoing edge (pos=0)
- or even on an internal edge (see https://sumo.dlr.de/docs/sumo-gui.html#investigating_internal_edges_and_lanes)

**Comment by amiradavoudi** [comment]
Thank you very much for your response.
