### ISSUE TITLE
How to define a different speed per trip in randomTrips script?

### ISSUE THREAD

**Issue by amiradavoudi** [eclipse/sumo#7972]
Hello,

I want to modify the randomTrips.py script so that each vehicle moves with a specific speed during its trip. Can I add a speed element to each generated trip?

Thank you in advance for your consideration.

**Comment by namdre** [comment]
by default, each vehicle picks it's preferred speed from a distribution of speeds (speedDev=0.1).
You can change this by setting a custom vType.
See
https://sumo.dlr.de/docs/Tools/Trip.html#setting_a_vehicle_type_from_an_external_file
https://sumo.dlr.de/docs/Definition_of_Vehicles,_Vehicle_Types,_and_Routes.html#speed_distributions

**Comment by amiradavoudi** [comment]
Thank you very much for your quick response.
