### ISSUE TITLE
How to define a constant speed for a vehicle?

### ISSUE THREAD

**Issue by amiradavoudi** [eclipse/sumo#7973]
Hello,

I want a vehicle move with a constant speed through its trip. For example, vehicle A moves from the edge A to the edge B with speed 70 km/h. In my scenario, in fact, the speed cannot be changed.
How can I define such a constant speed in SUMO?

Thank you in advance for your attention.

**Comment by namdre** [comment]
If the vehicle should ignore other vehicles, junctions etc. to retain this speed you need to call
```
traci.vehicle.setSpeedMode(vehID,0)
traci.vehicle.setSpeed(vehID, 70 / 3.6)
```

**Comment by amiradavoudi** [comment]
Thanks a lot for your answer.
