### ISSUE TITLE
How to define some random junctions located on a path

### ISSUE THREAD

**Issue by amiradavoudi** [eclipse/sumo#7974]
Hello,
In my scenario, I have a grid map 10*10 that is generated by the netgenerate script in SUMO and I am using the randomTrips.py to generate about 1000 random trips and their associated routes stored in test.trips.xml , and test.rou.xml.
 
Now, I want to select several random junctions (per trip/route) located along each generated trip/route and then define the Induction Loops Detector on each random selected junction.

**For example:**  If the created route is like "<route edges="C1D1 D1C1 C1B1 B1A1 A1A0 A0B0"\/>" 
then I want to select randomly two junctions along this route and put an induction loops detector on them. (I will later use these detectors to record the time and speed of a vehicle moving through these randomly chosen junctions)

Using the randomTrips with the parameter -i, we can create random edges along a path but ranomTrips does not support creating the random junctions along a route.
How should I modify the randomTrips.py script for doing such a scenario? Should I call the duarouter in randomTrips.py file?

Thank you in advance for your suggestion.

**Comment by behrisch** [comment]
Maybe you misunderstand what `-i` does in randomTrips.py. It does not select random edges in an existing path but rather defines via edges mainly to keep the vehicle in the network for a longer time period and allow for routes which are not simple shortest paths. For your question you should probably post process the resulting routes and simply find the excit node for randomly selected edges on the path using sumolib. Please keep in mind that induction loops cannot be placed on a complete junction.

**Comment by amiradavoudi** [comment]
Many thanks for your clear explanation!

**Comment by namdre** [comment]
>  Please keep in mind that induction loops cannot be placed on a complete junction.
Technically, they can if you use the internal lane id.

**Comment by amiradavoudi** [comment]
> > Please keep in mind that induction loops cannot be placed on a complete junction.
> 
> Technically, they can if you use the internal lane id.

Thank you for your helpful comment.
