### ISSUE TITLE
Question about the function setSpeedMode

### ISSUE THREAD

**Issue by zhuhj-tery** [eclipse/sumo#7975]
Hello,

Recently, we are working on a project on testing. We need to include collision in the simulation. We notice that there is a function called setSpeedMode in SUMO and setSpeedMode(0) could disregard the safety check. We are confused about what does safety check include and what's the effect of setSpeedMode(0). Thanks.

**Comment by namdre** [comment]
see https://sumo.dlr.de/docs/TraCI/Change_Vehicle_State.html#speed_mode_0xb3
