### ISSUE TITLE
randomTrips: set explicit random departPos and arrivalPos

### ISSUE THREAD

**Issue by amiradavoudi** [eclipse/sumo#7977]
Hello,
I want to generate a trip and its reverse (from, to, departPos and arrivalPos are reversed ) as follows:

\<trip id="0" depart="28239.00" from="C1D1" to="A0B0" departPos="10" arrivalPos="20"/>
\<trip id="0" depart="28239.00" from="A0B0" to="C1D1" departPos="20" arrivalPos="10"/>

I used the random.uniform(0,60) function for generating the random values. All the lane's length are 60, but I get the following warnings after simulation. (a related file is attached )

Warning: Vehicle '1' will not be able to arrive at the given position!
Warning: Vehicle '6_6' will not be able to arrive at the given position!
Warning: Invalid departPos 51.00 given for vehicle '6'. Inserting at lane end instead.

How can I get the minimum and maximum valid values for the departPos and arrivalPos parameter?

Thank you very much for your help.

**Comment by amiradavoudi** [comment]
![netedit](https://user-images.githubusercontent.com/75085693/102190762-b7979000-3eb8-11eb-8aa0-588bd99a09fc.png)

**Comment by namdre** [comment]
You can simple use departPos="random". 
The latest development version also supports arrivalPos="random".

The edge lengths are reduced after junction shape calculation (F5)

**Comment by amiradavoudi** [comment]
Hello,
Thank you very much. After F5 I found the value I was looking for. Thank you!
With regard to the random positions, I want to see what random positions are printed in the trips.xml and the rou.xml file, but I see the output as follows:

\<vehicle id="0" type="type3" depart="1.00" departPos="random" arrivalPos="**random**">
\<trip id="0" depart="1.00" from="C1D1" to="A0B0" type="typedist1" departPos="random" arrivalPos="**random**"/>

More precisely, can I modify the randomTrips.py in a way that prints the positions like this:
\<trip id="0" depart="28239.00" from="C1D1" to="A0B0" departPos="**10**" arrivalPos="**20**"/>

Thank you.

**Comment by namdre** [comment]
That isn't supported at the moment, sorry.

**Comment by amiradavoudi** [comment]
Thank you very much.

**Comment by namdre** [comment]
@bcoueraud87 for you
