### ISSUE TITLE
How to obtain the edge lengths that are reduced after junction shape calculation (F5)?

### ISSUE THREAD

**Issue by amiradavoudi** [eclipse/sumo#7978]
Hello,

In randomTrips.py script I want to obtain the edge lengths that are reduced after junction shape calculation (F5). What function can I call to get this value?

Thank you.

**Comment by namdre** [comment]
```
    net = sumolib.net.readNet(options.netfile)
    length = net.getEdge(edgeID).getLength()
```

**Comment by amiradavoudi** [comment]
Thank you very much.
