### ISSUE TITLE
pip install sumo-rl failed

### ISSUE THREAD

**Issue by meco2020** [eclipse/sumo#7980]
I want to install the sumo-rl but failed. My python version is 3.8 and my sumo version is 1.8.
I can install eclipse-sumo and libsumo by using pip, but sumo-rl failed.
![image](https://user-images.githubusercontent.com/65943065/102212910-e7728200-3f10-11eb-895f-9e7bc224b05f.png)

**Comment by namdre** [comment]
Please take this up with @LucasAlegre from https://github.com/LucasAlegre/sumo-rl
