### ISSUE TITLE
pip install sumo-rl failed by using pip and setup

### ISSUE THREAD

**Issue by meco2020** [eclipse/sumo#7986]
Hi, there is a question about sumo-rl install.
when I install the sumo-rl by using pip, there is an error like this,
![image](https://user-images.githubusercontent.com/65943065/102268724-a1401180-3f56-11eb-86c2-e43aa0f76f27.png)
and when I use setup to install the sumo-rl, there is an error like this one,
![image](https://user-images.githubusercontent.com/65943065/102268866-ce8cbf80-3f56-11eb-8ca2-457b20e1d607.png)

Thank you in advance!

**Comment by behrisch** [comment]
We are not affiliated, so you should probably ask here: https://github.com/LucasAlegre/sumo-rl
