### ISSUE TITLE
Track accidents

### ISSUE THREAD

**Issue by M-Colley** [eclipse/sumo#7987]
Hey, I am currently looking at how to detect accidents between vehicles and pedestrians. I came across the SSM device, but it does not seem to support accidents (https://sumo.dlr.de/docs/Simulation/Output/SSM_Device.html) and also only is available for vehicles.

Is there a built-in way to detect accidents or would I have to detect these myself (overlapping positions)?

Kind regards

**Comment by namdre** [comment]
sumo already tracks collisions between pedestrians and cars on normal edges. It may be helpful to also set option **--collision.check-junctions**.
