### ISSUE TITLE
Import .pbf files in netconvert

### ISSUE THREAD

**Issue by angelobanse** [eclipse/sumo#7988]
[PBF Format](https://wiki.openstreetmap.org/wiki/PBF_Format)

There is a tool to convert `.pbf` into `.osm` -> ([Osmconvert](https://wiki.openstreetmap.org/wiki/Osmconvert)) but it would be nice to support `.pbf` files directly as input in netconvert, to save the extra conversion-step.

FYI: [Osmconvert source code](http://m.m.i24.cc/osmconvert.c)

If it is decided not to implement this, a mention of `.pbf` and `Osmconvert` on the netconvert documentation page would be OK.

**Comment by namdre** [comment]
I do not wish to duplicate this in netconvert. Please extend the documentation as you see fit.

**Comment by namdre** [comment]
@behrisch or do you think PBF (based on protocolbuffer) should be supported generically like .gz?

**Comment by behrisch** [comment]
No, PBF is osm only, no generic support needed. For the general direction of this issue, I am not so sure. I also thought about adding o5m and if osmconvert had a library version instead of being a single blob we should probably do it, but I don't want to duplicate their code. Maybe we can adapt the OSM importer such that it reads the input only once. You could work with a pipe then.

**Comment by behrisch** [comment]
@namdre What do you think about the osm import refactoring to a single read?

**Comment by namdre** [comment]
quoting https://osmcode.org/file-formats-manual/:
```
All OSM files can have the entities they contain in any order.
...
All of this being said, OSM files are almost always ordered in a specific way: First nodes, then ways, then relations. 
```
On the other hand https://wiki.openstreetmap.org/wiki/OSM_XML writes:
```
can be certain that blocks come in this order (nodes, ways, rels)
```

This means we could merge the three handlers into a single handler and probably even gain parsing speed at some cost to code readability (and moderate refactoring effort).
