### ISSUE TITLE
How to get the list of all junctions in a random network?

### ISSUE THREAD

**Issue by amiradavoudi** [eclipse/sumo#7991]
Hello,

I have generated 100 grid, spider, and random networks using netgenerate script. I want to write a python script to get the list of 
all junctions on the created maps. How can I obtain the mentioned list ?
Thank you in advance for your help.

**Comment by namdre** [comment]
use sumolib to read the net and the `net.getNodes()`

**Comment by amiradavoudi** [comment]
Thank you very much

**Comment by amiradavoudi** [comment]
May I also use the the function **getIDList** that TraCI supports?
