### ISSUE TITLE
Why the defined detectors cannot output to the file?

### ISSUE THREAD

**Issue by amiradavoudi** [eclipse/sumo#7994]
Hello,

I added two instantInductionLoop detectors to the file type.add.xml, but when I execute the following command 
sumo -c test.sumocfg --additional-files=type.add.xml, but my problem is that it will not output to the detect.txt file.
I attached the files here.

[files.zip](https://github.com/eclipse/sumo/files/5704657/files.zip)

Thank you very much.

**Comment by Domsall** [comment]
The lane-attribute expects a lane, which are normally characterized with <edgeID>_<laneNumber>. <edgeID>_0 for the rightmost lane, <edgeID>_1 for the next, <edgeID>_2 and so on. You only wrote C1D1/C0D0, which are the edges. Write C1D1_0 and C0D0_0 and you should recieve the detect.txt file.

**Comment by amiradavoudi** [comment]
Thank you very much for your help.
