### ISSUE TITLE
What value should I set for the pos parameter to locate the detector exactly on a junction?

### ISSUE THREAD

**Issue by amiradavoudi** [eclipse/sumo#7995]
Hello,

I want to put a instantInductionLoop exactly on a junctions located on a grid map with the help of the following  element:

<instantInductionLoop id="1" lane="C1B1" pos="<POSITION_ON_LANE>" file="detect.txt" [friendlyPos="false"]/>

My question is that what value I should set for the pos parameter so that the instantInductionLoop can be located exactly on a junction.
My intention is to record the speed and the time of the vehicles pass through a junction. (There is no traffic light)

Thank you very much.

**Comment by angelobanse** [comment]
Detectors must be on lanes, you can use `0` as the position, to put it at the beginning of the lane (as close as possible to the desired junction).

**Comment by amiradavoudi** [comment]
Thank you very much.

**Comment by namdre** [comment]
You can place the detector anywhere on the junction if you specify the id of a junction internal lane. See https://sumo.dlr.de/docs/sumo-gui.html#investigating_internal_edges_and_lanes
