### ISSUE TITLE
I received the error while the inductionloop detector was outputting

### ISSUE THREAD

**Issue by amiradavoudi** [eclipse/sumo#7999]
Hello,

When I execute the command "sumo -c test.sumocfg --additional-files=type.add.xml" I get the attached error:
Loading configuration ... done.
Error: Another vehicle type (or distribution) with the id 'type3' exists.
Quitting (on error).

I should mention that in type.add.xml file (attached here), vTypeDistribution element is defined.
I have attached all the required files.
Thank you in advance for your attention.

[file2.zip](https://github.com/eclipse/sumo/files/5708766/file2.zip)

![error](https://user-images.githubusercontent.com/75085693/102476890-f1ed6280-405b-11eb-9434-311c3b926be0.png)

**Comment by Domsall** [comment]
You double-defined the different `vTypes`, in test.rou.xml you defined type1-type3 and in type.add.xml you again defined them as part of `vTypeDistribution`. So SUMO doesn't know which ones to pick from.
You can use the explicit definition in the test.rou.xml-file and delete the `vTypeDistribution` or you can delete the `vType`-Definitions in the test.rou.xml-file and use the distribution typedist1 as the vehicle types.

**Comment by amiradavoudi** [comment]
I defined the vTypeDistribution in type.add.xml so when I execute the below command, all the trips will contain the parameter
type="typedist1".
python randomTrips.py -n test.net.xml --trip-attributes="type=\"typedist1\""  --additional-files=type.add.xml  -b 1 -e 2 -p 1  -o test.trips.xml 

Then I execute the below command so the duarouter tool automatically generate the types for the routes according to the probabilities I defined in type.add.xml file.

duarouter -n test.net.xml --route-files test.trips.xml --additional-files type.add.xml -o test.rou.xml 

Would you please help me how I should change my commands to solve this problem. I have lots of trips and routes and I cannot delete types by hand.

Thank you.

**Comment by Domsall** [comment]
You could seperate the distribution from the detectors in the type.add.xml-file. Use another file and copy the detectors in there, e.g. called detectors.add.xml. Then use type.add.xml to perform the duarouter call and when you simulate you just add the additional file detectors.add.xml and leave the type.add.xml-file out. The distribution is already correctly in the test.rou.xml-file from the duarouter call.

**Comment by amiradavoudi** [comment]
Thank you very much for your help. The second solution(seperate the distribution from the detectors) worked for me.
Just out of curiosity, why are vtypes defined two times in test.rou.xml? What is the problem with my commands I mentioned in the previous command?
Thank you.

**Comment by Domsall** [comment]
They aren't defined two times in test.rou.xml. They are defined once in test.rou.xml and once in type.add.xml. You could also let SUMO pick the vehicle-types with your distribution at run-time. But as you run duarouter with your configuration, the corresponding vehicle types from type.add.xml are put into Output-File test.rou.xml, so the distribution of the vehicle types is already done in duarouter before your sumo simulation. You then only need to use the test.rou.xml-File as Input to your simulation. You can also find more information on this topic here:
https://sumo.dlr.de/docs/Definition_of_Vehicles,_Vehicle_Types,_and_Routes.html
https://sumo.dlr.de/docs/duarouter.html

**Comment by namdre** [comment]
To prevent duarouter from putting the vTypes directly into the output route file you can also set the option **--vtype-output** and write them somewhere else.

**Comment by amiradavoudi** [comment]
Thanks a lot for your helpful information!
