### ISSUE TITLE
How to see the properties of all vehicles on SUMO-gui

### ISSUE THREAD

**Issue by amiradavoudi** [eclipse/sumo#8003]
Hello,

I want to see the properties of the vehicles moving on a map in sumo-gui application. For example, is it possible to see the speed and the time of a vehicle in sumo-gui when the  vehicle is moving on a map?

Thank you.

**Comment by namdre** [comment]
Color by that value and then activate 'show color value' (https://sumo.dlr.de/docs/sumo-gui.html#common_visualization_settings)
Only one value can be shown at the time.
For custom values or a secondary value you can use traci to set them as parameter and then use 'show vehicle text param'.

**Comment by amiradavoudi** [comment]
Thank you very much. I will use the traci as I want to show several parameters.
