### ISSUE TITLE
Does my approach make sense?

### ISSUE THREAD

**Issue by amiradavoudi** [eclipse/sumo#8004]
Hello,

I have a grid map that is generated by the netgenerate in SUMO. Now, I want to prepare a script that automatically locates several Instantaneous Induction Loops Detectors on some of the junctions (which are selected randomly) on a map. 
This script will write to a file detector.add.xml as follows:

I will create the list of all the lanes (using TraCI/Lane Value Retrieval) of the grid map. Then, I will choose randomly several lanes from the list and create the following xml  file: 

```
<additional>
	<instantInductionLoop id="1" lane="C1D1_0" pos="0" file="detect.txt" freq="10"  friendlyPos="false"/>
...
        <instantInductionLoop id="10" lane="A1B1_0" pos="0" file="detect.txt" freq="10"  friendlyPos="false"/>
</additional>
```

Does this approach make sense?

**Comment by namdre** [comment]
This is a value judgment out of scope of this issue tracking facility. See https://sumo.dlr.de/docs/FAQ.html#i_want_to_do_a_project_with_sumo_can_you_help_me_with_the_implementation
