### ISSUE TITLE
The relation between the duration time and all the travel times along a route

### ISSUE THREAD

**Issue by amiradavoudi** [eclipse/sumo#8005]
Hello,

According to the SUMO documents the duration parameter in the trip information `(<tripinfos>)` is _the time the vehicle needed to accomplish the route_. My question is that whether the **duration time** equals to the addition of all the time (traveltime(Edge-Based Network States)) needed to pass the edges/lanes along the route. 

More precisely, if the route is  `route edges="C1D1 D1C1 C1B1 B1A1"/>` then is the following formula correct?
duration time = traveltime(C1D1) + traveltime(D1C1) +traveltime(C1B1) + traveltime(B1A1)

traveltime is define on the below link:
https://sumo.dlr.de/docs/Simulation/Output/Lane-_or_Edge-based_Traffic_Measures.html

duration time is define on the below link:
https://sumo.dlr.de/docs/Simulation/Output/TripInfo.html

Thank you.

**Comment by namdre** [comment]
No. 
- the tripinfo traveltime also includes the time needed to pass the junctions.
- edge traveltime is an aggregated value whereas tripinfo is for each vehicle which can use more or less time for a particular edge.
