### ISSUE TITLE
Can Traci provide  the flexible steering controll？

### ISSUE THREAD

**Issue by GyChou** [eclipse/sumo#8006]
Can Traci provide  the flexible steering controll  instead of the fixed lane changing policy？

**Comment by namdre** [comment]
Sumo does not model steering but you can activate the sublane model (https://sumo.dlr.de/docs/Simulation/SublaneModel.html) and use `traci.vehicle.changeSublane` for fine grained lateral movement. The visual vehicle angle will automatically be adapted to a somewhat plausible value.

**Comment by GyChou** [comment]
thank you very much!!!

**Comment by GyChou** [comment]
I hope to achieve direction control through `traci.vehicle.changeSublane`， but this has no effect, it seems to be restricted by safety constraints.
It has no effect for safety constraints to change lane by `traci.vehicle.setLaneChangeMode(veh_id, lcm=2218)`

**Comment by namdre** [comment]
You not need to set laneChangeModel SL2015 (in fact this does not activate the sublane model).
Instead use option **--lateral-resolution** to activate sublane mode. The lanechange model will be set automatically.

**Comment by GyChou** [comment]
thank you. I got it

**Comment by cloudfly519** [comment]
> 
> 
> You not need to set laneChangeModel SL2015 (in fact this does not activate the sublane model).
> Instead use option **--lateral-resolution** to activate sublane mode. The lanechange model will be set automatically.

sorry ,After seeing your answer.I still do not know how to activate the sublane mode.now I want to use the traci to control the vehcle change to another lane.but I meet the same question as GyChou did that it seems to be restricted by safety constraints.I don't know how to achieve it.could you help me

**Comment by namdre** [comment]
See https://sumo.dlr.de/docs/TraCI/Change_Vehicle_State.html#lane_change_mode_0xb6

**Comment by cloudfly519** [comment]
> OK，I got it.tks

**Comment by cloudfly519** [comment]
I have another question that what value should I put in the second of the changesublane(ID,latdist).Now I built a 3-lane which width is 3.75m.I want to make the vehicle change to the next lane.so I  give the commend:changesublane(ID,3.75).because the documentation says:"negative values indicate changing to the right, positiveto the left".But it doesn't work.what did I do wrong?

**Comment by namdre** [comment]
the speed is limited by the maximum lateral speed of the vehicle (default 1m/s). To perform a smooth lanechange you need to call changeSublane in multiple subsequent steps.

**Comment by cloudfly519** [comment]
> 
> 
> the speed is limited by the maximum lateral speed of the vehicle (default 1m/s). To perform a smooth lanechange you need to call changeSublane in multiple subsequent steps.

sorry I'm not understand.could you please give me an example to help me to understand the changesublane

**Comment by namdre** [comment]
just call traci.vehicle.changeSublane(vehID, 1) three times (in three simulation steps)

**Comment by cloudfly519** [comment]
> 
> 
> just call traci.vehicle.changeSublane(vehID, 1) three times (in three simulation steps)

when i call traci.vehicle.changeLane(vehID,1,5),the car can change lanes to the appropriate lane.but when I call traci.vehicle.changeSublane(vehID, 1).the car is not responding.If I want to write my own lane change model.What should I do

**Comment by namdre** [comment]
> when i call traci.vehicle.changeLane(vehID,1,5),the car can change lanes to the appropriate lane.but when I call traci.vehicle.changeSublane(vehID, 1).the car is not responding.

sounds like the sublane model is not active
