### ISSUE TITLE
How to add my desired parameter in the output?

### ISSUE THREAD

**Issue by amiradavoudi** [eclipse/sumo#8011]
Hello,

The output of the instantInductionLoop is stored in the output as follows:

```
<instantE1 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/instant_e1_file.xsd">
    <instantOut id="1" time="2.00" state="stay" vehID="0" speed="2.41" length="3.00" type="type3"/>
</instantE1>
```

Now, I want to add my desired parameters **Myparam1**="12.23"  **Myparam2**="normal"  to this output, for example:

```
<instantE1 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/instant_e1_file.xsd">
    <instantOut id="1" time="2.00" state="stay" vehID="0" speed="2.41" length="3.00" type="type3" Myparam1="12.23"  Myparam2="normal" "/>
</instantE1>
```
Is there any  possibilities in SUMO to add my desired parameters to the output?

Thank you.

**Comment by namdre** [comment]
The only xml output that supports custom parameters is the fcd output via option **--fcd-output.params**

**Comment by amiradavoudi** [comment]
Thank you very much for the helpful information.
