### ISSUE TITLE
Why the shortest path is not chosen in the below scenario?

### ISSUE THREAD

**Issue by amiradavoudi** [eclipse/sumo#8014]
Hello,

According to the path.png file attached here, I am wondering why the vehicle chooses the green path, while the red path is shorter. What changes I should make to my net so that the vehicle choose the red path, and not the green path?

Thank you very much.
I attached all the required files.

[file1.zip](https://github.com/eclipse/sumo/files/5714686/file1.zip)
![path](https://user-images.githubusercontent.com/75085693/102595155-74872800-4117-11eb-9455-d5cb8bc2678f.png)

**Comment by namdre** [comment]
if you use attribute from, the path starts on the chosen edge. you can use attribute fromJunction if you want to have a flexible starting edge.

**Comment by amiradavoudi** [comment]
Thanks a lot for your help.
