### ISSUE TITLE
Why is it that when I save the road network in Opendrive format, all the elevation information is 0

### ISSUE THREAD

**Issue by panpan113** [eclipse/sumo#8016]

**Comment by namdre** [comment]
most likely because your input network had no z-data.

**Comment by panpan113** [comment]
> most likely because your input network had no z-data.

I download the map from openStreamMap and use the command netconvert --osm-files wuhan. Osm --opendrive-output 22. Xord --osm. Elevation true --osm. Layer-elevation 4.0

**Comment by namdre** [comment]
You can use sumo-gui to check whether the network contains elevation data (color by elevation).
In my test, conversion to OpenDRIVE correctly exports elevation.

**Comment by panpan113** [comment]
> You can use sumo-gui to check whether the network contains elevation data (color by elevation).
> In my test, conversion to OpenDRIVE correctly exports elevation.

Does converting a sumo.NET file to an Opendrive file remove the coordinate points by default? How can You add coordinates to an Opendrive file

**Comment by namdre** [comment]
Currently, a geo-reference is only supported for unshifted networks (#4417). Either set option **--offset.disable-normalization** when first importing the network or shift if later using **--offset.x, --offset.y**.
