### ISSUE TITLE
I get the Warning: Route file should be sorted by departure time, ignoring '53'!

### ISSUE THREAD

**Issue by amiradavoudi** [eclipse/sumo#8017]
Hello, 

When I execute the following simulation command, I will receive the attached warnings.

`sumo -c test.sumocfg --vehroute-output.sorted --additional-files=detectors.add.xml`

Thank you.

[files3.zip](https://github.com/eclipse/sumo/files/5714881/files3.zip)
![warning](https://user-images.githubusercontent.com/75085693/102599406-b6b36800-411d-11eb-85ec-3b33649aa786.png)

**Comment by ambuehll** [comment]
see: https://sumo.dlr.de/docs/Definition_of_Vehicles,_Vehicle_Types,_and_Routes.html#routes

> The route file has to be sorted by starting times.

Sumo requires a route file sorted by depature time. Your vehicle 53 is supposed to depart at  54s, but you have vehicles listed before that departing later. 

use https://sumo.dlr.de/docs/Tools/Routes.html#sort_routespy to sort your route files.

**Comment by behrisch** [comment]
Thanks @ambuehll

**Comment by amiradavoudi** [comment]
> see: https://sumo.dlr.de/docs/Definition_of_Vehicles,_Vehicle_Types,_and_Routes.html#routes
> 
> > The route file has to be sorted by starting times.
> 
> Sumo requires a route file sorted by depature time. Your vehicle 53 is supposed to depart at 54s, but you have vehicles listed before that departing later.
> 
> use https://sumo.dlr.de/docs/Tools/Routes.html#sort_routespy to sort your route files.

Thank you.

**Comment by amiradavoudi** [comment]
Thank you very much.
