### ISSUE TITLE
allow merging overlapping geo-referenced networks

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#8019]
- basic merging (#4085) works but fails on overlap (works with **--ignore-errors)
- setting a prefix for one network and then joining nodes with the same position (#7567) fails due to geometrical differences after reprojecting geo-referenced coordinates
   - when junctions are joined successfully, duplicated edges must be joined as well
     - when using **--edges.join** the lane numbers are added so this is not a solution
   - the joined nodes are renamed (cluster...)

Instead, the importer should automatically handle duplicates

**Comment by namdre** [comment]
current work-around is this
```
netconvert -s a.net.xml --plain-output-prefix a --proj.plain-geo
netconvert -s b.net.xml --plain-output-prefix b --proj.plain-geo
netconvert -e a.edg.xml,b.edg.xml -n a.nod.xml,b.nod.xml -x a.con.xml,b.con.xml -i a.tll.xml,b.tll.xml -t a.typ.xml,b.typ.xml --proj.utm -o ab.net.xml
```

**Comment by ZoltanBaksa** [comment]
In case of merging, it is important to take care about the traffic light controller programs.
It can happen, that there is a part of a multi-junction TL controller, but not all related junctions are in the overlapped part. This case the connections' TL indexing could change. The previously written TL program could be lost or corrupted. A warning message should be raised, to inform the user about it.

**Comment by namdre** [comment]
final result:
- when the edges to be merged have identical ids it is sufficient to load both with option **-s**
- when the ids are different, the the options **--junctions.join-same --edges.join** must be set as well.

**Comment by namdre** [comment]
> In case of merging, it is important to take care about the traffic light controller programs.
> It can happen, that there is a part of a multi-junction TL controller, but not all related junctions are in the overlapped part. This case the connections' TL indexing could change. The previously written TL program could be lost or corrupted. A warning message should be raised, to inform the user about it.

Could you provide a small example for our tests suite?
