### ISSUE TITLE
Can vehicles move between min and max speed?

### ISSUE THREAD

**Issue by amiradavoudi** [eclipse/sumo#8021]
Hello,

I want to force the speed of all the moving vehicles on the map between a minimum and maximum speed.  For example,
I have 100 cars and I want them to move with the speed between 70 and 90 (70,90). (not less that 70 and not more than 90)

I set the maxSpeed(vType attribute) to 90, but I don't know how to set the minimum speed that is 70 in this example.
Should I set the decel(vType attribute) to zero to satisfy my need?

Thank you in advance for your help.

**Comment by namdre** [comment]
Currently, the only way to enforce a mimimum speed is to set the speed explicitly via traci (setSpeed + setSpeedMode).
However, there are "softer ways" to raise speeds 
- setting a high-enough departSpeed
- cutting off the lower part of the speed distribution (see speedFactor documentation).

**Comment by amiradavoudi** [comment]
Thank you very much.
