### ISSUE TITLE
How to prevent the junctions from impacting on the vehicles' speed?

### ISSUE THREAD

**Issue by amiradavoudi** [eclipse/sumo#8022]
Hello,

How should I config the intersections (junctions) so that they have no influence on the vehicles' speed?
More precisely, vehicles must not reduce their speed when passing through the intersections. (There is no traffic light on the map)
 
Is it possible to use _netgenerate_ to config this as I want to use it to create my maps?

Thank you in advance for your help.

**Comment by namdre** [comment]
set junction type to "unregulated"

**Comment by amiradavoudi** [comment]
> set junction type to "unregulated"

Thank you. Is it possible also to set the --no-internal-links option to true?

**Comment by namdre** [comment]
No. "unregulated" completely ignores right-of-way. See also https://sumo.dlr.de/docs/Simulation/Intersections.html#internal_links

**Comment by amiradavoudi** [comment]
Thank you very much for the helpful information.
