### ISSUE TITLE
Cannot make car1(ego) follow car2(leader) by using the ACC carfollowingModel

### ISSUE THREAD

**Issue by mateen-malik** [eclipse/sumo#8023]
Hi, 

I wish to have car1 always follow car2, so what i did was as follows,

<vType id="car1" length="5" maxspeed="50" vClass="passenger" lcSpeedGain="0.1" speedFactor="1.0"
           carfollowingModel="ACC" minGap="2.5" accel="1.0" decel="4" sigma="0.5"/>

<vType id="car2" length="5" maxspeed="50" vClass="passenger" lcSpeedGain="0.0" speedFactor="0.7"
           carfollowingModel="Krauss" minGap="2.5" accel="3.5" decel="4" sigma="0.5"/>

I thought even if the lcSpeedGain of 'car1' is higher than 'car2', the car1 should still follow car2 as the carfollowingModel of car1 is set to ACC.

So ACC will adjust its speed according to the vehicle infront?
But what i found was that, the car1 driving behaviour is dependent on the parameters, such as lcSpeedGain, speedFactor and accel  . It totally ignores the carfollowingModel parameter.

I am using the latest version that is, sumo-1.8.0 
what am i doing wrong here?  :(
Need some help.

Thanks alot for your help in advance.

Best regards,

**Comment by mateen-malik** [comment]
<vType id="car1" length="5" maxspeed="50" vClass="passenger" lcSpeedGain="0.1" speedFactor="1.0"
     carfollowModel="ACC" minGap="2.5" accel="1.0" decel="4" sigma="0.5"/>
<vType id="car2" length="5" maxspeed="50" vClass="passenger" lcSpeedGain="0.0" speedFactor="0.7"
      carfollowModel="Krauss" minGap="2.5" accel="3.5" decel="4" sigma="0.5"/>

**Comment by namdre** [comment]
I think the model name ACC is misleading you. The model just determines the following speed under the condition that there is a leader to be followed and no reason for lane changing exists. It does not activate any kind of platooning behavior.

**Comment by mateen-malik** [comment]
got it, thanks alot for the explanation.
So, I wonder if i can make the ego vehicle (i.e. ca1)  always follow the vehicle (i.e. car2) in front of it? even if the ego vehicle's speed is higher?
How can i activate the platooning behavior? 

Thanks again,
Best regards,

**Comment by namdre** [comment]
- disable lane changing via XML set lcSpeedGain="0" and lcKeepRight="0"
- disable lane changing using traci.vehicle.setLaneChangeMode
- use a platooning toolkit https://sumo.dlr.de/docs/Simpla.html or https://plexe.car2x.org/

**Comment by mateen-malik** [comment]
Hi again,

thank you sooo much for your generous help and guidance, really appreciated!
One further question i have in mind which i need some help to understand that is as follows,

by setting  lcSpeedGain="0" and lcKeepRight="0" and disabling laneChangeMode we can keep the vehicle in one lane following the vehicle in front. This behavior will be the same with both Krauss and ACC carfollowModels. Then what is the difference between Krauss and ACC models?

Thanks again,
best regards,
/MM

**Comment by namdre** [comment]
ACC uses a different formula to compute follow speed and this results in different gaps and accelerations.
