### ISSUE TITLE
how to access and visualize the V2V communication in SUMO?

### ISSUE THREAD

**Issue by mateen-malik** [eclipse/sumo#8025]
Hi,

Is it possible to access and visualize the V2V communication in SUMO simulation?
Such as how the data (parameters or signals) is transferred between the vehicles, data packets format and frequency of data transfer etc?
Is it a separate tool that is used to access the above information or is it possible to see in SUMO as well? 

Need guidance. 

thanks in advance, 

Best regards,

**Comment by behrisch** [comment]
SUMO itself does not do V2V communication so the data is not directly available. You can visualize arbitrary data using POIs, polygons and vehicle / edge coloring using TraCI or XML though. https://sumo.dlr.de/docs/sumo-gui.html#changing_the_appearancevisualisation_of_the_simulation
