### ISSUE TITLE
How to use several additional files in my scenario?

### ISSUE THREAD

**Issue by amiradavoudi** [eclipse/sumo#8026]
Hello,

I have created three different additional files as follows. Based on the conditions in my scenario, I will use one of these xml file to create my trips (test.trips.xml).

```
The type1.add.xml file includes   <vType id="type1" maxSpeed = "15" length="3"  />
The type2.add.xml file includes    <vType id="type2" maxSpeed = "10" length="3"  />
The type3.add.xml file includes    <vType id="type3" maxSpeed = "5"   length="3"  />
```

I want to include the three type.add.xml files in the configuration file in the sumocfg file as follows:
`<additional-files value="type1.add.xml, type2.add.xml, type3.add.xml"/>`
 
Now, my question is that in my code how I can read from the sumocfg file to use one of these type.add.xml files?

Thank you.

**Comment by namdre** [comment]
you can use option **--additional-files file1.xml,file2.xml,...**

**Comment by amiradavoudi** [comment]
Thank you.
