### ISSUE TITLE
How to get the angle of the lane by Traci?

### ISSUE THREAD

**Issue by GyChou** [eclipse/sumo#8027]
Excuse me, how do I use Traci to get the angle of the lane?
I'm sorry, I really can't find the method I need in the documentation.

**Comment by namdre** [comment]
There is no direct way but this will work:
- place a vehicle on the lane (i.e with moveTo or moveToxY) and retrieve the vehicle angle
- use traci.lane.getShape and sumolib.geomhelper: positionAtShapeOffset with two different offsets and angle2D (if needed naviDegree(angle2D( ...))
