### ISSUE TITLE
I received an error while working with randomTrips script in a specific condition

### ISSUE THREAD

**Issue by amiradavoudi** [eclipse/sumo#8028]

**Comment by amiradavoudi** [comment]
Hello,
When I execute the following command I recevie the attached error.
[file.zip](https://github.com/eclipse/sumo/files/5719497/file.zip)

Thank you.

**Comment by amiradavoudi** [comment]
![error](https://user-images.githubusercontent.com/75085693/102690997-9eb91280-4209-11eb-93ac-efdabd5a3f94.png)

**Comment by namdre** [comment]
flow uses [begin, end[ an this means begin must be smaller than end for a non-empty range.
