### ISSUE TITLE
copy traffic light

### ISSUE THREAD

**Issue by GumpWorks** [eclipse/sumo#8029]
I am so confuse that I cant copy the traffic light to another crossing.

**Comment by namdre** [comment]
what did you try and what was the error you encountered?

**Comment by GumpWorks** [comment]
I copied the traffic light of one crossing, but I cant find how to paste it to another crossing.Or does it need to save the traffic light as an additional file or else.

**Comment by namdre** [comment]
You can save the program to a file, change the traffic light id and then rel-load it in  netedit for another junction (or load the file together with sumo). Note, that this only works if the junctions have the same layout and orientation.
