### ISSUE TITLE
Why the departSpeed saved in the log is less than the departSpeed?

### ISSUE THREAD

**Issue by amiradavoudi** [eclipse/sumo#8032]
Hello,
I have defined the departSpeed (80) for all types in the type.add.xml file as follows (attached the file):
```
<additional>
<vType id="type2" departSpeed = "80" length="2" color="1,0,0" />
</additional>
```
I have placed two instantInductionLoops as follows to record the speed of the vehicles: 
```
<additional>
	<instantInductionLoop id="1" lane="B2B3_0" pos="0" file="DB1.txt" freq="10"  friendlyPos="false"/>
	<instantInductionLoop id="2" lane="B1B0_0" pos="0" file="DB2.txt" freq="10"  friendlyPos="false"/>
</additional>
```
 Why all the speed recorded in the log is less than the departSpeed that is set to 80? (The route file and the instantInductionLoop logs are attached here.)

Does this problem have anything to do with the position of the instantInductionLoops or the positions of vehicles? 
How can I record the departSpeed of the vehicles passing through the instantInductionLoops ?

Thank you.
[files.zip](https://github.com/eclipse/sumo/files/5725018/files.zip)

**Comment by namdre** [comment]
attribute departSpeed does not take effect when set in the vType. It must be set in the vehicle/trip

**Comment by amiradavoudi** [comment]
Sorry. I made a mistake. Thanks a lot!

**Comment by namdre** [comment]
please do not double-post your questions!

**Comment by amiradavoudi** [comment]
> please do not double-post your questions!

Sorry. I will do that.
