### ISSUE TITLE
How can I use the attributeStats.py

### ISSUE THREAD

**Issue by amiradavoudi** [eclipse/sumo#8033]
Hello,

I want to use the attributeStats.py script to analyze the depart attribute in the tripinfo element. 
I use the following command but no output is generated:

`python attributeStats.py --element tripinfo --attribute depart
`
I don't know how I can give the trip informaion output as the input to the attributeStats.py script.

Thank you.
[trip-informaion-output.txt](https://github.com/eclipse/sumo/files/5725399/trip-informaion-output.txt)

**Comment by namdre** [comment]
call 

`python attributeStats.py tripinfos.xml --element tripinfo --attribute depart 
`

**Comment by amiradavoudi** [comment]
It worked! Thank you.
