### ISSUE TITLE
Why the depart speed is 0.00 in the tripinfo output?

### ISSUE THREAD

**Issue by amiradavoudi** [eclipse/sumo#8034]
Hello,

According to the attached files I have defined depart Speed for all vehicle types in the network, but the trip output information print 0.00 for the depatSpeed.
Would you please help me with this problem in my scenario?

Thank you.
[file.zip](https://github.com/eclipse/sumo/files/5725508/file.zip)

**Comment by Domsall** [comment]
I think you aren't using the xml-attributes the expected way. The default departSpeed is actually 0, so you may not be setting the departSpeed as intended. The documentation is very good for understanding the setup:
https://sumo.dlr.de/docs/Definition_of_Vehicles,_Vehicle_Types,_and_Routes.html
The vType-attribute is used to define the vehicle type, which has nothing to do with the route. You can then use the different attributes trip or vehicle like you do to set up route-specific attributes, e.g. departSpeed, arrivalSpeed, arrivalPos, etc.. You should also note, that all speed-values are used/given in m/s. Values of 60-80 seem to be too high. The speed limit of the road may only be 13.89m/s=50km/h. In this case the simulation would output warnings and/or errors.

**Comment by amiradavoudi** [comment]
Thank you very much for your clear explanation.
