### ISSUE TITLE
Why the event of vehicle with id=2 is not recorded in the file created by instantOut id="1" 

### ISSUE THREAD

**Issue by amiradavoudi** [eclipse/sumo#8036]
Hello, 

In my scenario, I have created several trips and then recorded the output of the two instantInductionLoops with id=1 and id=2 to the DB1 and DB2 files respectively. 
I am wondering why the vehicle with id=2 is not recorded in DB1(The other vehicles are recorded correctly)?

[file.zip](https://github.com/eclipse/sumo/files/5728415/file.zip)
[file-new.zip](https://github.com/eclipse/sumo/files/5728474/file-new.zip)

Thank you in advance for your help.

**Comment by namdre** [comment]
the network file is missing in your attachment

**Comment by amiradavoudi** [comment]
> the network file is missing in your attachment

I updated the attached files. Thank you.

**Comment by Domsall** [comment]
Yes, both issues refer to the same problem. Shift the InductionLoop position by a small amount (e.g. pos="0.01") and you will recieve the values to the departing vehicles. As the InductionLoop sits at 0m (or better is 4m long at +-2m) and the vehicle also departs at 0m meters, the vehicles may not be counted, because they only drive over half or less than half (numerical) of the InductionLoop.

**Comment by amiradavoudi** [comment]
> Yes, both issues refer to the same problem. Shift the InductionLoop position by a small amount (e.g. pos="0.01") and you will recieve the values to the departing vehicles. As the InductionLoop sits at 0m (or better is 4m long at +-2m) and the vehicle also departs at 0m meters, the vehicles may not be counted, because they only drive over half or less than half (numerical) of the InductionLoop.

Thank you very much. Just out of curiosity, is the pos="0.01" computed from the center of the junction or is computed from the beginning of the lane(without considering the junction) ?

**Comment by namdre** [comment]
positions are always counted from the beginning of a lane. For internal lane this means it counts from the stop line.

**Comment by amiradavoudi** [comment]
> positions are always counted from the beginning of a lane. For internal lane this means it counts from the stop line.

Thank you.
