### ISSUE TITLE
Feature request: lane line type

### ISSUE THREAD

**Issue by rlloretb** [eclipse/sumo#8037]
Traffic Intersection approaches (and also freeways) often present solid lanes to forbid vehicles change lanes. This is normally done to increase safety or intersection efficiency (throughput).

I've just realized that SUMO lanes don't have a "lane line type" feature.
While there are creative alternatives to model this, i.e. adding ghost small lanes and disallowing traffic or directly forbidding the vehicle to change lanes, this is actually inconvenient and complicates the network and the modeling greatly.
Would it be possible to include this feature?

For example:
lane_line_type: [solid, dashed]

PS: there are other types of lane lines (solid-dashed), but they are intimately related to the lane changing model, which would have a more complicated implementation.

**Comment by namdre** [comment]
duplicates #3656
