### ISSUE TITLE
In my scenario, why the instantInduction Loops cannot record the departing data of vehicles?  

### ISSUE THREAD

**Issue by amiradavoudi** [eclipse/sumo#8038]
Hello,

In my scenario, when I choose the departSpeed between 10 and 13 for the vehicles, the instantInduction Loops cannot record the events for the vehicles that depart the lane B2B3_0 and depart the lane B1B0_0, but when I reduce the departSpeed to 1 then the instantInduction Loops can successfully record all the events. 

I am wondering why the instantInduction Loops cannot record in the mentioned scenario (when the departSpeed is in range(10,13)). I attached the related files.  

This question might have a relation to the issue #8036 I created. So, sorry if  my question is duplicated.

Thank you.
[file.zip](https://github.com/eclipse/sumo/files/5728915/file.zip)

**Comment by behrisch** [comment]
I suppose it has been solved together with #8036. If not please reopen.
