### ISSUE TITLE
What is the location of the instantInduction loop in my scenario?

### ISSUE THREAD

**Issue by amiradavoudi** [eclipse/sumo#8040]
Hello,

I have located two detectors with position 7.5 on the lanes B2B3_0 and B1B0_0 respectively. The length of the lane is 35.60 (I used the netedit and pressed F5 to get this value(35.60)). The lane's length including the junctions is 50(without F5).

According to the below configuration,  are the detectors placed 7.5 meter from the center of the junction or 7.5 meter from the beginning of the lane that does not include the junction?

```
<additional>
	<instantInductionLoop id="1" lane="B2B3_0" pos="7.5" file="toll_plaza1.txt"  friendlyPos="false"/>
	<instantInductionLoop id="2" lane="B1B0_0" pos="7.5" file="toll_plaza2.txt"  friendlyPos="false"/>
</additional>
```
More precisely, does the lane B1B3_0 include the length of the junction or not?

Thank you.

**Comment by namdre** [comment]
"normal" lane lengths do not include the junction size. The size of the junction is reflected in the length of the "internal" lanes that lie within the junction.

**Comment by amiradavoudi** [comment]
Thank you very much for your response.
