### ISSUE TITLE
Why does the instant induction loops not record any data? 

### ISSUE THREAD

**Issue by amiradavoudi** [eclipse/sumo#8042]
Hello,

I have defined to instantInductionLoops at pos="2" on the junctions' internal edges **:B2_1_0** and **:B0_1_0**, but the instantInductionLoops have not recorded any data to the files. 
More precisely, I want the instantInductionLoops record the related vehicle's data when it is moving from the junction B2 to B1.

Would you please help me with this problem?

Thank you in advance for your help.
All related files are attached.
[files.zip](https://github.com/eclipse/sumo/files/5742308/files.zip)

**Comment by m-kro** [comment]
The vehicle does not travel along the mentioned internal edges - its route includes the edges between junctions B0 and B2 only. The detectors are placed upstream/downstream of the traveled route. If you lengthen your route to "B3B2 B2B1 B1B0 B0C0", you will see detector output.
