### ISSUE TITLE
How can I set the junction type in SUMO?

### ISSUE THREAD

**Issue by amiradavoudi** [eclipse/sumo#8044]
Hello,

I want to change the type of a junction in my python script. What is the method for set a type for a junction in SUMO?
What library should I use for this purpose?

Thank you.

**Comment by namdre** [comment]
in a running simulation you can only change between traffic light and priority junction by switching traffliclights to the "off" program.
For offline network editing, see this example: https://sumo.dlr.de/docs/Tutorials/ScenarioGuide.html#modifying_node_positions_with_the_help_of_sumolib
