### ISSUE TITLE
netconvert tls actuated

### ISSUE THREAD

**Issue by raphael-arce** [eclipse/sumo#8045]
Hello,

in the [traffic lights documentation](https://sumo.dlr.de/docs/Simulation/Traffic_Lights.html#improving_generated_programs_with_knowledge_about_traffic_demand) it is mentioned how to generate actuated traffic lights using `netconvert`. However, later in the same doc it is mentioned that there are multiple types of actuated traffic lights (gap based, time loss).

Which type is actually generated with `netconvert`? Is there more documentation about how exactly the traffic light programs are generated and how they will work?

If there is no documentation, perhaps someone knows where (folder or source file) the actuated tls generation happens for me to try to understand it through reading the code? I could not find it myself unfortunately. 

Thanks!

**Comment by namdre** [comment]
* **--tls.default-type actuated** will create a controller with gap-based actuation
* **--tls.default-type delay_based** will create a controller with delay based actuation
both controllers are documented at https://sumo.dlr.de/docs/Simulation/Traffic_Lights.html#actuated_traffic_lights
phase generation is described only at https://sumo.dlr.de/docs/Simulation/Traffic_Lights.html#automatically_generated_tls-programs
the code is in src/microsim/traffic_lights (MSActuatedTrafficLightLogic, MSDelayBasedTrafficLightLogic)

**Comment by raphael-arce** [comment]
thanks a lot!
