### ISSUE TITLE
Mac sumo-gui backgroud all red

### ISSUE THREAD

**Issue by thomasyyang** [eclipse/sumo#8048]
I have built sumo from source code, but i start sumo-gui encounter this：

sumo-version: 
Eclipse SUMO sumo Version v1_8_0+0367-5b405151e5
 Build features: Darwin-19.5.0 x86_64 Clang 12.0.0.12000032 Release Proj GUI SWIG GDAL GL2PS Eigen
 Copyright (C) 2001-2020 German Aerospace Center (DLR) and others; https://sumo.dlr.de
 License EPL-2.0: Eclipse Public License Version 2 <https://eclipse.org/legal/epl-v20.html>
 Use --help to get the list of options.

![image](https://user-images.githubusercontent.com/22517691/103470601-2593f080-4daf-11eb-98ce-37018b09e471.png)

**Comment by namdre** [comment]
see https://sumo.dlr.de/docs/FAQ.html#distorted_view_with_green_lines_all_over_the_network

**Comment by schwamborn** [comment]
Seems to be related to #7830. Please take a look [here](https://github.com/eclipse/sumo/issues/7830#issuecomment-740024652).
