### ISSUE TITLE
No "select edges","spread vehicles","show connection","grid" available in NETEDIT 1.8.0

### ISSUE THREAD

**Issue by rkprasadq805** [eclipse/sumo#8050]
For my project work i was working with SUMO tool. for designing part i was using NETEDIT 1.8.0, in which the above mentioned checkbox is not present. Whereas in NETEDIT 1.7.0 its present and working fine. The latest version SUMO 1.8.0 have some issue with this check box. 
Attached the is picture of both NETEDIT 1.7.0 and 1.8.0.
![no select edges checkbox in netedit 1_8_0](https://user-images.githubusercontent.com/76935807/103509247-affc5300-4e88-11eb-946f-aa6511ee1a95.PNG)
![issue](https://user-images.githubusercontent.com/76935807/103509256-b4c10700-4e88-11eb-9d2b-b84811998cd9.PNG)

**Comment by namdre** [comment]
those checkboxes now show up as buttons next to the edit mode buttons.

**Comment by rkprasadq805** [comment]
Thank you for your response but not getting those check box in 1.8.0, checked all the tool bar options.
![Capture](https://user-images.githubusercontent.com/76935807/103514732-403f9580-4e93-11eb-8e87-d3a4eea014cc.PNG)

**Comment by namdre** [comment]
The buttons are even in your screenshot. It's the row of buttons (the rightmost 4) below the main menu bar.
