### ISSUE TITLE
Why do I receive the detector error in a specific scenario?

### ISSUE THREAD

**Issue by amiradavoudi** [eclipse/sumo#8052]
Hello,
When I want to generate detectors I receive the following error:
`Error: The position of detector 'A0A1_0' lies beyond the lane's 'A0A1_0' end`

The config of my detector is as follows:
`    <instantInductionLoop file="toll_outputs.xml" id="A0A1_0" lane="A0A1_0" pos="1004.5"/>
`
Would you please help me with this problem?
Thank you.

**Comment by amiradavoudi** [comment]
[test.net.zip](https://github.com/eclipse/sumo/files/5763791/test.net.zip)

**Comment by namdre** [comment]
I think you should be able to figure it out from the error message and by checking the length of that lane in sumo-gui.
