### ISSUE TITLE
How is the duration time( shown in trip information) calculated?   

### ISSUE THREAD

**Issue by amiradavoudi** [eclipse/sumo#8053]
Hello,
The speed of all edges are _13.89 m/s_, and the _routeLength_ is equal to 3980.19.  How can I obtain **the average speed** so that I can calculate the duration time? The duration time in the below example is 280.00, but I don't know how it is calculated.

    <tripinfo id="3" depart="7.00" departLane="B3C3_0" departPos="0.02" departSpeed="7.00" departDelay="0.00" arrival="287.00" arrivalLane="C1C0_0" arrivalPos="985.58" arrivalSpeed="14.49" **duration**="280.00" **routeLength**="3980.19" waitingTime="0.00" waitingCount="0" stopTime="0.00" timeLoss="14.05" rerouteNo="0" devices="tripinfo_3" vType="Euro6" speedFactor="1.08" vaporized=""/>

Thank you.

**Comment by namdre** [comment]
if you divide routeLength by duration you will get the average speed. Your vehicle is sometimes driving faster than the speed limit due to speedFactor being 1.08

**Comment by amiradavoudi** [comment]
> if you divide routeLength by duration you will get the average speed. Your vehicle is sometimes driving faster than the speed limit due to speedFactor being 1.08

My assumption is that I don't know the duration time, so I am looking for a way to compute the average speed and then compute the duration time? Is there any tool that gives me the average speed of each edge on the map?

**Comment by namdre** [comment]
For aggregated speeds: https://sumo.dlr.de/docs/Simulation/Output/Lane-_or_Edge-based_Traffic_Measures.html
Note, that this can only be used to estimate actual *individual* vehicle speeds. To get those you need to track them continuously with fcd-output.

**Comment by amiradavoudi** [comment]
> For aggregated speeds: https://sumo.dlr.de/docs/Simulation/Output/Lane-_or_Edge-based_Traffic_Measures.html
> Note, that this can only be used to estimate actual _individual_ vehicle speeds. To get those you need to track them continuously with fcd-output.

Many thanks for your helpful info.
