### ISSUE TITLE
Why the lane-based traffic measures output is not generated in my scenario?

### ISSUE THREAD

**Issue by amiradavoudi** [eclipse/sumo#8054]
Hello, 

I used the following sumo config for generating the lane-based Traffic Measures output, but when I use the command 
_sumo -c test-sorted-route-measures.sumocfg_, it will not generate any output. Would you please help me with this?

```
<configuration>
	<additional>
		<laneData id="1" file="aaa.txt"/>
	</additional>
    <input>
        <net-file value="test.net.xml"/>
        <route-files value="test-sorted.rou.xml"/>
    </input>
    <time>
        <begin value="0"/>
        <end value="2000"/>
    </time>
</configuration>
```
Thank you in advance for your help.

**Comment by namdre** [comment]
The laneData definition must go into an extra file which is then added to the configuration with option `<additional-files value="extrafile.xml"/>`

**Comment by amiradavoudi** [comment]
> The laneData definition must go into an extra file which is then added to the configuration with option `<additional-files value="extrafile.xml"/>`

Thank you very much. It worked!
