### ISSUE TITLE
tlsCycleAdaptation.py only modified 1 traffic light in multiple traffic lights optimization problem

### ISSUE THREAD

**Issue by jtkhair** [eclipse/sumo#8056]
I'm working on multiple traffic lights systems optimization problem. I tried using the tlscycleadaptation.py to modify the duration of green phases of 2 traffic lights to best accommodate a given traffic demand. I've configured the route file using duarouter function which includes both junctions. However, I can only observe traffic light 1 cycle being modified. Though, I can observe changes in the queue length for traffic light 2 based on the --queue-output. Any advice on this issue?

Original cycle traffic light 1
![image](https://user-images.githubusercontent.com/59551598/103632260-021fa000-4f7f-11eb-8786-2b2ce19c1ce3.png)

Optimized cycle traffic light 1
![image](https://user-images.githubusercontent.com/59551598/103632485-532f9400-4f7f-11eb-996d-4ab417ef9e99.png)

Original cycle traffic light 2
![image](https://user-images.githubusercontent.com/59551598/103632047-bf5dc800-4f7e-11eb-9629-e7d719ab3450.png)

Optimized cycle traffic light 2
![image](https://user-images.githubusercontent.com/59551598/103632089-cab0f380-4f7e-11eb-91b3-7d7b0e9abdf8.png)

**Comment by namdre** [comment]
to rule out the case that traffic light 2 is already webster-optimal, try passing in a different program for traffic light 2 and check if it still comes out unchanged.

**Comment by jtkhair** [comment]
Hi Jakob, thanks for the reply. Based on the current situation, I've tried
using different cycle for traffic light 2. The new *.add.xml just updated
the traffic light junction 2 cycle to the cycle that I've configured in
the  *.net.xml file while the cycle for traffic light 1 is unchanged.
However, when I changed both traffic lights cycle to the same default
value, then I can see the changes at both junctions. They are different
than the first attempt.

**Comment by jtkhair** [comment]
I noticed that the tlsCycleAdaptation.py only works if all the traffic
lights are having the same phase

**Comment by yunpangfloetteroed** [comment]
Hi,
the tlsCycleAdaptation.py should also work when traffic lights with different number of phases. The considered number of phases at each traffic light is inherited from the given sumo network file. Furthermore, there are default values for the maximal and minimal cycle lengths (120s and 20s). You could check if it is your case.

**Comment by jtkhair** [comment]
Hi @yunpangfloetteroed, 

I'll give another try & will update it here.

**Comment by namdre** [comment]
@yunpangfloetteroed Is there anything else we could/should do on this issue? Otherwise I would close for lack of feedback

**Comment by yunpangfloetteroed** [comment]
I have not received any feedback since Feb. From my side, you can close this ticket.
