### ISSUE TITLE
Activitygen cannot get file attributes

### ISSUE THREAD

**Issue by nieljoncarl** [eclipse/sumo#8062]
Error when using activitygen with 4GB+ of net file on Windows but works perfectly on Ubuntu.

`Error: Cannot get file attributes for file 'map.net.xml'!
Quitting (on error).`

**Comment by namdre** [comment]
make sure you are using the 64bit version of sumo.

**Comment by nieljoncarl** [comment]
> make sure you are using the 64bit version of sumo.

I'm using sumo-win64 version. I can open the net file on sumo-gui but I can't generate activities using activitygen tool on windows.

**Comment by namdre** [comment]
what is the output of calling activitigen without arguments on the command line?

**Comment by nieljoncarl** [comment]
```
Eclipse SUMO activitygen Version v1_8_0+0424-dc9d55ff90
 Build features: Windows-6.3.9600 AMD64 MSVC 18.0.40629.0 Release SumoUtilsLibrary Proj GUI SWIG GDAL FFmpeg OSG GL2PS Eigen
 Copyright (C) 2001-2020 German Aerospace Center (DLR) and others; https://sumo.dlr.de
 Copyright (C) 2010-2012 Technische Universitaet Muenchen
 License EPL-2.0: Eclipse Public License Version 2 <https://eclipse.org/legal/epl-v20.html>
 Use --help to get the list of options.
```

**Comment by namdre** [comment]
most likely the same issue as #6620. I suspect that one of the libraries being used by sumo is running in 32bit mode.
@behrisch @palvarezlopez any ideas?
