### ISSUE TITLE
Vehicles do not get in the correct exit lanes on time

### ISSUE THREAD

**Issue by sumo2021** [eclipse/sumo#8074]
Hi,

I am modelling a highway scenario with several interchanges and I experience a problem at the highway exits. Vehicles on the left lane which want to leave the highway do not get in the correct exit lanes on time which causes them to stop on the highway and change lanes in the last possible moment. This leads to a traffic jam behind those vehicles.

![LaneChange_Problem](https://user-images.githubusercontent.com/77237297/104331986-03f1e200-54f0-11eb-8f77-b2055cd032b1.jpg)

I have already tried to use the “lcTurnAlignmentDistance” attribute to force the vehicles to change lanes early. However, this did not solve the issue. I also tried to assign the appropriate lanes to the vehicles, but it seems like the “lanes” attribute cannot be used when defining “routes”.

Has anybody experienced a similar issue and is there a way to solve it?

I am grateful for any idea.

**Comment by namdre** [comment]
- lcTurnAlignment is only for alignment within a lane so it is not relevant to your scenario.
- insertion vehicles into the simulation with `departLane="best"` is often a good idea to prevent bad insertion lanes
- you can diagnose lane change issues by coloring vehicles according "offset from best lane" and tracking them in sumo-gui ahead of the junction/off-ramp

**Comment by sumo2021** [comment]
Thank you for the advice! The option "departLane="best" improved the situation, but did not solve it.
Nevertheless, meanwhile I solved my problem.
