### ISSUE TITLE
dead end nodes in input (trac #808)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#808]
It is possible to give "dead_end" as type on node files (and it is written on plain output). The semantics should be that all connections on this node are removed. There is no test validating whether this works.

Migrated from http://sumo.dlr.de/ticket/808
```json
{
    "status": "new", 
    "changetime": "2013-09-10T10:13:42Z", 
    "description": "It is possible to give \"dead_end\" as type on node files (and it is written on plain output). The semantics should be that all connections on this node are removed. There is no test validating whether this works.", 
    "reporter": "behrisch", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1378808022776167", 
    "component": "net building (NETGEN, NETCONVERT)", 
    "summary": "dead end nodes in input", 
    "priority": "minor", 
    "keywords": "", 
    "time": "2012-12-03T09:43:58Z", 
    "milestone": "1.0.0", 
    "owner": "", 
    "type": "defect"
}
```

**Comment by behrisch** [comment]
Currently dead_end in input is silently ignored and the type is recomputed. Maybe a warning would be appropriate if the type really changes in the end. @namdre If you think the warning would be useful please leave it open otherwise just close it.

**Comment by namdre** [comment]
I don't think it would be useful. There are other methods available for specifying that a node has no connections.
