### ISSUE TITLE
Vehicles turning left are mostly waiting on one left turn lane

### ISSUE THREAD

**Issue by urielka** [eclipse/sumo#8083]
Hi,

I have a simulation where there are two left turn lanes, what I see is that vehicles will get queued mostly on one lane and only after a while they will start moving to the other lane and even then it will be only a few.

What happens is that I have a queue with 1-2 cars and another queue with 10 cars and it will require much more green time to discharge all of them than in reality causing split failures that don't happen in reality.

I tried playing with lcStrategic, putting a larger value didn't fix it, putting 0 fixed it but caused cases where vehicles gets stuck in the middle of the queue.

What is the recommended way to fix this?

SUMO Version: 1.6.0
Issue:
![image](https://user-images.githubusercontent.com/30956/104603012-acd14600-5684-11eb-9e1e-b7f158c31859.png)

**Comment by namdre** [comment]
Most likely, the downstream route after the left turn favors  one of the two lanes over the other. The easiest solution is to convert any lane drops after the left turn to a zipper merge so that both lanes will have equal merit. Other changes to downstream connections may also helper. Lowering lcStrategic may help (but 0 is probably too low).

**Comment by zmajstorovic** [comment]
Try setting _lcKeepRight_ option to 0 (or some value closer to zero)

**Comment by urielka** [comment]
Regarding the downstream route - after turning left you are leaving the network so I am not sure how/why the route would prefer a specific lane.

Can you explain how you change to zipper merge? Wouldn't that cause both lanes to merge?

Attached is my network (forgot to include it in the first post)
[model.net.zip](https://github.com/eclipse/sumo/files/5825765/model.net.zip)

**Comment by urielka** [comment]
@namdre zipper merge solved the issue, thank you!

**Comment by namdre** [comment]
Actually, the network doesn't look like there should be a preference for either lane. Where did you put the zipper merge?

**Comment by urielka** [comment]
@namdre that was before the zipper merge.
