### ISSUE TITLE
joining of junction 

### ISSUE THREAD

**Issue by Fatimaghaffar** [eclipse/sumo#8087]
I have an issue in joining of junctions from the open street map, whenever 4 roads meet at a junction, it ends up by creating four separate junctions instead of one junction. 
![1](https://user-images.githubusercontent.com/56623612/104701834-1873eb80-5737-11eb-8016-7e00e5124cbc.png)

 I have tried to merge them in netedit but created a terrible type of junction.  
![1](https://user-images.githubusercontent.com/56623612/104702116-5cff8700-5737-11eb-9847-5372cef5398a.png)

and I want junction in the following picture. 
![1](https://user-images.githubusercontent.com/56623612/104702373-b8ca1000-5737-11eb-9733-fc1b62e98279.png)

 so that I would able to mount traffic light on that so anyone who know this issue please tell me

Regards

**Comment by namdre** [comment]
To join the junctions into a nice shape, select the 4 component junctions in select mode and then join them using F7 (Processing menu -> Join selected junctions)
