### ISSUE TITLE
What causes a blurred simulation during running the SUMO?

### ISSUE THREAD

**Issue by zihan9826** [eclipse/sumo#8090]
Hi, guys. I'm new in SUMO.  I just got the blurred result when I try to run a simulation here. 
![image](https://user-images.githubusercontent.com/47419112/104833359-fd68bf00-588f-11eb-85e6-6ae78981748b.png)
You could see the issue above. I'm using the windows 10 and running it on my gaming laptop (I got last year), So I don't think it's a hardware problem, and I've tried lots of version of SUMO, but it still doesn't' work. Any suggestion here?

**Comment by behrisch** [comment]
Please see https://sumo.dlr.de/docs/FAQ.html#distorted_view_with_green_lines_all_over_the_network
