### ISSUE TITLE
Can sumo set the randomness of traffic flow in Python files instead of in 'sumocfg' file?

### ISSUE THREAD

**Issue by BBDrive** [eclipse/sumo#8096]
Hello.
Sumo can set randomness in the `sumocfg` file, but is it possible to set randomness in a python file?

**Comment by namdre** [comment]
Please explain in more detail what you are trying to achieve.

**Comment by BBDrive** [comment]
When running a program, i want to chooese different random seeds to create different traffic flow. Meanwhile, it's convenient for me to reproduce.
However, if i set randomness in the `sumocfg` file,  i have to explicitly define random seeds.
For example, if i want to set 50 random seeds, i have to create 50 `sumocfg` files corresponding to different random seeds.(In my understanding, it's that.)
So I want to ask if there is such a method call that can directly change the randomness in the python file, it may be like this `traci.setSeed`.
I am looking forward to your answer. Thanks

**Comment by BBDrive** [comment]
Is the following code correct in the `sumocfg` file?
```
<random_number>
        <random value="true"/>
    </random_number>
```

**Comment by behrisch** [comment]
yes and you can give this also as a command line argument when starting sumo from python
