### ISSUE TITLE
Parallel simulation of SUMO

### ISSUE THREAD

**Issue by jiao1997** [eclipse/sumo#8103]
Dear all, 
         I am new to SUMO. I have a network partition algorithm for parallel simulation. I wonder if SUMO support parallel simulation that can test my algorithm. If it supports, how can I work with it?
Yours,
Jiao

**Comment by behrisch** [comment]
There have been several attempts to do this https://link.springer.com/chapter/10.1007/978-3-319-15024-6_5 https://www.researchgate.net/publication/305045832_Distributed_Simulation_in_SUMO_Revisited_Strategies_for_Network_Partitioning_and_Border_Edges_Management but none of them made it to the main SUMO repository and I don't know if the code is available. So apart from removing and adding vehicles on boundaries using traci or libsumo there is no support yet.

**Comment by jiao1997** [comment]
> There have been several attempts to do this https://link.springer.com/chapter/10.1007/978-3-319-15024-6_5 https://www.researchgate.net/publication/305045832_Distributed_Simulation_in_SUMO_Revisited_Strategies_for_Network_Partitioning_and_Border_Edges_Management but none of them made it to the main SUMO repository and I don't know if the code is available. So apart from removing and adding vehicles on boundaries using traci or libsumo there is no support yet.

Dear behrisch,
       You mean that parallel simulation is not yet fully supported? Is the source code which use traci or libsumo available? I just want to test my road network partition algorithm.

**Comment by behrisch** [comment]
There is a repo: https://github.com/QarSUMO/QarSUMO but without code. You may open a ticket there. Quick googling did not bring up further results, please ask the authors, addresses should be in the papers.

**Comment by jiao1997** [comment]
> There is a repo: https://github.com/QarSUMO/QarSUMO but without code. You may open a ticket there. Quick googling did not bring up further results, please ask the authors, addresses should be in the papers.

Thanks for your reply. I will ask the authors.

**Comment by behrisch** [comment]
@jiao1997 It would be nice if  you could report back here if they answer

**Comment by jiao1997** [comment]
> @jiao1997 It would be nice if you could report back here if they answer

Dear behrisch,
          I have contact to the author of QarSUMO. But this work is still  a on-going work, the source code may be not available.

**Comment by behrisch** [comment]
Thanks for reporting back but sorry to hear that. It sounded like the community could benefit.
