### ISSUE TITLE
How to make the collision warning just appear once 

### ISSUE THREAD

**Issue by Izzatbrg** [eclipse/sumo#8106]
I'm trying to make sumo an environment for Reinforcement learning  but always when a collision is happening the sumo send more than a warning due to the same collision but to notify the collision from the side of the other participant here is an example:

> Warning: Vehicle '0'; collision with vehicle '1', lane=':Intersection_1_0', gap=-1.00, time=9.80 stage=move.

> Warning: Vehicle '1'; collision with vehicle '0', lane=':Intersection_0_0', gap=-1.00, time=9.80 stage=move.

> Warning: Vehicle '0'; collision with vehicle '1', lane=':Intersection_1_0', gap=-1.00, time=9.80 stage=laneChange.

> Warning: Vehicle '1'; collision with vehicle '0', lane=':Intersection_0_0', gap=-1.00, time=9.80 stage=laneChange.

> Warning: Vehicle '0'; collision with vehicle '1', lane=':Intersection_1_0', gap=-1.00, time=9.80 stage=insertion.

> Warning: Vehicle '1'; collision with vehicle '0', lane=':Intersection_0_0', gap=-1.00, time=9.80 stage=insertion.

is there any way to make this warning happen once and not more?

thanks in advance

**Comment by namdre** [comment]
The latest development version counts collisions only once per step.
