### ISSUE TITLE
Public transport tutorial (without web wizard)

### ISSUE THREAD

**Issue by MPLoves** [eclipse/sumo#8108]
Hello,

We want to study the subway trafic and more especially the waiting time of the passenger, and how to reduce it. 
Do do that we want to use SOMO and simulate a piece of subway, only 3-4 station on a straight line, but we really don't know how to start it.
Is there some exemple or a tutorial that we can follow please?

Thank you very much for the help

Best;

**Comment by behrisch** [comment]
You can start with the WebWizard extracting your favourite subway line from OpenStreetMap https://sumo.dlr.de/docs/Tutorials/OSMWebWizard.html. Make sure to check the "Public Transport" checkbox. Unfortunately there is currently no public transport tutorial. I keep this ticket open as a reminder to write one.

**Comment by lbieker** [comment]
ticket was closed in last commit
