### ISSUE TITLE
Vehicle moving backwards after collision

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#8109]
Doing a rear end collision with a collision stop the collider can end up on a position which is smaller than the collision position. Not sure about the physics (this is not a rubber car so I think it should not bounce back), but this also causes problems in the simulation because the vehicle may now lap into a lane it already left and myFurtherLanes is not updated. The case can be observed in complex/state/save_collision_stopped (timestep 39, collider always_right.3).

**Comment by behrisch** [comment]
I retract my earlier comment on backward movements because this is probably rather a late correction of the initially "wrong" position than a backward movement. So the question is whether we should either update myFurtherLanes or ensure that the position correction does not lead to an overlapping vehicle. I prefer updating myFurtherLanes. @namdre Ideas?

**Comment by namdre** [comment]
Updating myFurtherLanes would surely be nicer but could have all kinds of interesting implications because the collision may come at various points in the simulation step and some implicit constraints on sorted data structures must be kept (i.e. #8079).

**Comment by behrisch** [comment]
Shall we give it a try and wait for further reports?

**Comment by namdre** [comment]
go ahead.

**Comment by behrisch** [comment]
Shall we give it a try and wait for further reports?

**Comment by namdre** [comment]
causing crash #8359
