### ISSUE TITLE
officially deprecate TraaS web service functionality

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#8117]
There is no working test and probably it would need some work to get it running with JDK >= 11. Comments are welcome especially if you know people who are actively using it.

**Comment by behrisch** [comment]
@mkrumnow Feel free to defend it ;-)

**Comment by mkrumnow** [comment]
In my opinion, the soap interface is not more state of the art. In recent years the implementation of soap clients was a convenient way to use the SUMO API very quickly. Currently, SOAP communication is outdated and produces too much (time-consuming) overhead regarding the fast simulation speed of SUMO. We should remove the web-service component from trass because there is no need for soap communication anymore.

**Comment by behrisch** [comment]
Change documentation and maybe give a warning

**Comment by behrisch** [comment]
While I appreciate the prompt initiative, moving files to sumo/objects changed the interface for many TraaS users. We might want to rethink that.

**Comment by mkrumnow** [comment]
Sure, for me the namespace seems to be false (ws ..) so I decided to change it. Of course we can slow down that process and change it back so users can prepare the change too. Unfortunatly, i've seen some more Traci methods which should be fixed to work with a current sumo version.

**Comment by namdre** [comment]
Could we keep the classes in the more logical package and add `ws` as an alias for backward compatibility?

**Comment by behrisch** [comment]
The idea is good but except for implementing an actual wrapper there seems to be no way. https://stackoverflow.com/questions/2204157/class-or-method-alias-in-java

**Comment by mkrumnow** [comment]
I've just added some classes as a kind of reference (extends) because as you already mentioned there is no alias in java

**Comment by behrisch** [comment]
But shouldn't the new classes inherit from the old ones? People will expect to get an old (now subclass) instance but will get an instance of the superclass so their cast will fail. Alternatively the code could still produce the old instances.

**Comment by behrisch** [comment]
@mkrumnow Do you agree with my analysis?

**Comment by mkrumnow** [comment]
Hi @behrisch you're fully right. This is just a quick and very dirty solution to get some deprecated messages to the user code.  The usage of the java classes/objects via casting has never been the best approach here. In my opinion, it is possible to change the namespace as mentioned and increasing the package version number of traas.  So users can decide to upgrade or not ;-)

**Comment by behrisch** [comment]
There seem to be more problems in the code because it often checks for equality of class objects instead of using instanceof. To keep it brief: I don't think it is worth the effort. People will need to modify their code when using the new TraaS version and we should encourage them to switch to libtraci and deprecate the whole TraaS.
