### ISSUE TITLE
lack of feature on traci.vehicle.getNeighbors()

### ISSUE THREAD

**Issue by Mikemraz** [eclipse/sumo#8122]
Just out of curiosity, is there a way to detect neighbor vehicles not just immediately near the ego vehicle? For example, if the ego vehicle is in the 1st lane, is there a way to access the nearby vehicles' IDs in the 3rd lane? This is useful if two vehicles (on 1st lane and 3rd respectively) intend to make lane changes onto the same lane **at the same time**, but we need to determine which one has the right to do so or a collision would occur.

**Comment by namdre** [comment]
a filtered context subscription should help with this
```
traci.vehicle.subscribeContext(objID, traci.constants.CMD_GET_VEHICLE_VARIABLE,  viewRange,traci.constants.VAR_POSITION])
traci.vehicle.addSubscriptionFilterLateralDistance(lateralDistance, downstreamDistance, upstreamDistance)
```
