### ISSUE TITLE
Clang build doesn't work in Windows 10

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#8123]
Found during fixing of #7544

**Comment by behrisch** [comment]
What is the reason for doing clang builds on Windows? And what is the error message?

**Comment by palvarezlopez** [comment]
The purpose is debugging and the problem is a incompatibility with std::tuple and GTest libs

**Comment by palvarezlopez** [comment]
The problem is caused by std::tuple

**Comment by palvarezlopez** [comment]
Currently work for Release, not for Debug

**Comment by tlobig** [comment]
the #include <config.h> broke the build at least for Linux it seems. Something missing in the CMakeLists.txt or should there be a config.h which is actually missing?

../sumo/src/utils/traci/TraCIAPI.h:23:10: fatal error: config.h: No such file or directory
   23 | #include <config.h>
      |          ^~~~~~~~~~
compilation terminated.

**Comment by palvarezlopez** [comment]
@tlobig Try to rebuild entire solution

**Comment by tlobig** [comment]
i rebuilt the "solution" (Linux -> cmake, make) the error persists. Sadly I'm not setup to run the test suite, but I could build my traci app by simply **commenting out the include line for the config.h**

**Comment by palvarezlopez** [comment]
Fixed
