### ISSUE TITLE
traci.exceptions.FatalTraCIError: connection closed by SUMO

### ISSUE THREAD

**Issue by Adaickalavan** [eclipse/sumo#8125]
We have built an application using SUMO and we receive the following error from SUMO.
+ Steps to reproduce: huawei-noah/SMARTS#453
+ Attached the SUMO crash log from `/var/crash/` folder. File: [sumo-gui-1000-crash.log](https://github.com/eclipse/sumo/files/5857432/sumo-gui-1000-crash.log)
+ Attached the SUMO run log. File: [sumo-26c2829c.log](https://github.com/eclipse/sumo/files/5857433/sumo-26c2829c.log)
+ Error message printed to the terminal is as follows:
 ```
Traceback (most recent call last):
  File "/home/kyber/workspaces/SMARTS/smarts/core/sumo_traffic_simulation.py", line 313, in step
    self._traci_conn.simulationStep(self._cumulative_sim_seconds)
  File "/usr/share/sumo/tools/traci/connection.py", line 302, in simulationStep
    result = self._sendCmd(tc.CMD_SIMSTEP, None, None, "D", step)
  File "/usr/share/sumo/tools/traci/connection.py", line 180, in _sendCmd
    return self._sendExact()
  File "/usr/share/sumo/tools/traci/connection.py", line 90, in _sendExact
    raise FatalTraCIError("connection closed by SUMO")
traci.exceptions.FatalTraCIError: connection closed by SUMO
```

**Comment by behrisch** [comment]
I really tried (https://github.com/huawei-noah/SMARTS/issues/472) but it is hard to reproduce. Can you send a somewhat isolated example?

**Comment by behrisch** [comment]
Agreed with the original reporter to close it until a better example shows up. See also https://github.com/huawei-noah/SMARTS/issues/472
