### ISSUE TITLE
some cursors don't behave as expected on Linux

### ISSUE THREAD

**Issue by angelobanse** [eclipse/sumo#8126]
- INSPECT_LANE and SELECT_LANE cursors only appears if a click is performed first
- SELECT does not appear at all

---
DELETE_CURSOR and MOVEELEMENT work just fine on Linux.
On Windows all cursors work as expected.

---
Info: Using Ubuntu 20.04 on a Parallels 15 VM on macOS 10.15.7

**Comment by namdre** [comment]
working for me with redhat and ubuntu. Supposedly your problem has to do with using a virtual machine.
