### ISSUE TITLE
Sumo Simulation

### ISSUE THREAD

**Issue by muaid-ahmed** [eclipse/sumo#8128]
I am trying to obtain different phasing during a simulation. However, I am only getting 1 second per traffic signal.. it should be at least 20 seconds as in the code.. Can someone help?

if __name__ == '__main__':
    sumoInt = SumoIntersection()
    # this script has been called from the command line. It will start sumo as a
    # server, then connect and run
    options = sumoInt.get_options()

    if options.nogui:
    #if True:
        sumoBinary = checkBinary('sumo')
    else:
        sumoBinary = checkBinary('sumo-gui')
    
      
    #training 
    state_size= SumoIntersection.getState
    action_size = 4
    
    agent = DQNAgent(state_size, action_size)
    done = False
    EPISODES = 1
    batch_size = 32
    render = True
    rewardList= []

    for e in range(EPISODES):
        # Initialize DNN with random weights
        # Initialize target network with same weights as DNN Network
        
        traci.start([sumoBinary, "-c", "J1-Intersection.sumocfg", '--start', '--ignore-route-errors'], port= 8813) #play button to press instead of start
        
      
        #state = sumoInt.reset()
        step = 0
        reward1 = 0
        reward2 = 0
        reward3 = 0
        reward4 = 0
        waiting_time = 0
        total_reward = reward1 - reward2 - reward3 - reward4    
            
        
                                         
        #WT_S = traci.edge.getWaitingTime('14367817#2') #south
        #WT_N = traci.edge.getWaitingTime('185056611#2') #north #returns the mean waiting time for all vehicles on the edge at the last time step
        #WT_E = traci.edge.getWaitingTime('185056637#2') #east
        #WT_W = traci.edge.getWaitingTime('185056635#1') #west
            
        while traci.simulation.getMinExpectedNumber() > 0:
                
            traci.simulationStep()
            state = sumoInt.getState()
            action = agent.get_action(state)
            light = state[2] #2 if three inputs
            TimeStep= int(traci.simulation.getTime())
            

                
            WT_S = (traci.lanearea.getLastStepVehicleNumber("RightLane-14367817#1_0")
                + traci.lanearea.getLastStepVehicleNumber("MiddleLane-14367817#1_1")
                + traci.lanearea.getLastStepVehicleNumber("LeftLane-14367817#2_1"))#south
        
            WT_N = (traci.lanearea.getLastStepVehicleNumber("RightLane-185056611#2_0")
                    + traci.lanearea.getLastStepVehicleNumber("RightLane-185056611#1_0")
                    + traci.lanearea.getLastStepVehicleNumber("RightLane-gneE12_0") 
                    + traci.lanearea.getLastStepVehicleNumber("MiddleLane-185056611#1_1") 
                    + traci.lanearea.getLastStepVehicleNumber("LeftLane-185056611#1_2") 
                    + traci.lanearea.getLastStepVehicleNumber("LeftLane-gneE12_1"))#north #returns the mean waiting time for all vehicles on the edge at the last time step
            
            WT_E = (traci.lanearea.getLastStepVehicleNumber('RightLane-185056637#0_0')
                    + traci.lanearea.getLastStepVehicleNumber('LeftLane-185056637#0_1'))  #east
            
            WT_W = (traci.lanearea.getLastStepVehicleNumber('RightLane-gneE1_0') 
                    + traci.lanearea.getLastStepVehicleNumber('LeftLane-185056635#1_1')
                + traci.lanearea.getLastStepVehicleNumber('LeftLane-gneE1_1')) #west

            
            if(action == 0 and light[0][0][0]==1):
                                   
                
                if (traci.trafficlight.getPhaseName('cluster_1956408958_1956408961_1956408963_463134911') == 1 or 
                    traci.trafficlight.getPhaseName('cluster_1956408958_1956408961_1956408963_463134911') == 3 or 
                    traci.trafficlight.getPhaseName('cluster_1956408958_1956408961_1956408963_463134911') == 5 or 
                    traci.trafficlight.getPhaseName('cluster_1956408958_1956408961_1956408963_463134911') == 7):
                    
                    
                    
                    traci.trafficlight.setPhase('cluster_1956408958_1956408961_1956408963_463134911', 0)
                    for ts in range (20):
                        traci.trafficlight.setPhaseDuration('cluster_1956408958_1956408961_1956408963_463134911', 20)
                    
                                        
                reward1 += traci.edge.getTraveltime('14367817#2')
                reward2 += traci.edge.getTraveltime('185056611#2')
                reward3 += traci.edge.getTraveltime('185056637#2')
                reward4 += traci.edge.getTraveltime('185056635#1')
                
                                                    
               
             
            if(action == 1 and light[0][0][0]==1):
                                  
                
                if (traci.trafficlight.getPhaseName('cluster_1956408958_1956408961_1956408963_463134911') == 1 or 
                    traci.trafficlight.getPhaseName('cluster_1956408958_1956408961_1956408963_463134911') == 3 or 
                    traci.trafficlight.getPhaseName('cluster_1956408958_1956408961_1956408963_463134911') == 5 or 
                    traci.trafficlight.getPhaseName('cluster_1956408958_1956408961_1956408963_463134911') == 7):
                    
                    
                    
                    traci.trafficlight.setPhase('cluster_1956408958_1956408961_1956408963_463134911', 2)
                    
                    for ts in range (20):
                        
                        traci.trafficlight.setPhaseDuration('cluster_1956408958_1956408961_1956408963_463134911', 20)
                
                reward1 += traci.edge.getTraveltime('14367817#2')
                reward2 += traci.edge.getTraveltime('185056611#2')
                reward3 += traci.edge.getTraveltime('185056637#2')
                reward4 += traci.edge.getTraveltime('185056635#1')
            
            if(action == 2 and light[0][0][0]==1):
                                   
                
                if (traci.trafficlight.getPhaseName('cluster_1956408958_1956408961_1956408963_463134911') == 1 or 
                    traci.trafficlight.getPhaseName('cluster_1956408958_1956408961_1956408963_463134911') == 3 or 
                    traci.trafficlight.getPhaseName('cluster_1956408958_1956408961_1956408963_463134911') == 5 or 
                    traci.trafficlight.getPhaseName('cluster_1956408958_1956408961_1956408963_463134911') == 7):
                    
                    
                    
                    traci.trafficlight.setPhase('cluster_1956408958_1956408961_1956408963_463134911', 4)
                    
                    for ts in range (20):
                                       
                        traci.trafficlight.setPhaseDuration('cluster_1956408958_1956408961_1956408963_463134911', 20)
            
                reward1 += traci.edge.getTraveltime('14367817#2')
                reward2 += traci.edge.getTraveltime('185056611#2')
                reward3 += traci.edge.getTraveltime('185056637#2')
                reward4 += traci.edge.getTraveltime('185056635#1')
            
            
            if(action == 3 and light[0][0][0]==1):
                          
                
                if (traci.trafficlight.getPhaseName('cluster_1956408958_1956408961_1956408963_463134911') == 1 or 
                    traci.trafficlight.getPhaseName('cluster_1956408958_1956408961_1956408963_463134911') == 3 or 
                    traci.trafficlight.getPhaseName('cluster_1956408958_1956408961_1956408963_463134911') == 5 or 
                    traci.trafficlight.getPhaseName('cluster_1956408958_1956408961_1956408963_463134911') == 7):
                    
                    traci.trafficlight.setPhaseDuration('cluster_1956408958_1956408961_1956408963_463134911', 4)
                    
                    traci.trafficlight.setPhase('cluster_1956408958_1956408961_1956408963_463134911', 6)
                    
                    for ts in range (20):
                        traci.trafficlight.setPhaseDuration('cluster_1956408958_1956408961_1956408963_463134911', 20)
                    
                reward1 += traci.edge.getTraveltime('14367817#2')
                reward2 += traci.edge.getTraveltime('185056611#2')
                reward3 += traci.edge.getTraveltime('185056637#2')
                reward4 += traci.edge.getTraveltime('185056635#1')
            
            
            if (action == 0 and light[0][0][0]==0):
                for TS in range(20):
                    traci.trafficlight.setPhase('cluster_1956408958_1956408961_1956408963_463134911', 0)                
                    traci.trafficlight.setPhaseDuration('cluster_1956408958_1956408961_1956408963_463134911', 20)
                    
                               
                for TS in range (4):
                           
                    traci.trafficlight.setPhase('cluster_1956408958_1956408961_1956408963_463134911', 1)
                    traci.trafficlight.setPhaseDuration('cluster_1956408958_1956408961_1956408963_463134911', 4)
                   
                       
                        
                reward1 += traci.edge.getTraveltime('14367817#2')
                reward2 += traci.edge.getTraveltime('185056611#2')
                reward3 += traci.edge.getTraveltime('185056637#2')
                reward4 += traci.edge.getTraveltime('185056635#1')
            
            if (action == 1 and light[0][0][0]==0):
                for TS in range(20):
                    traci.trafficlight.setPhase('cluster_1956408958_1956408961_1956408963_463134911', 1)                
                    traci.trafficlight.setPhaseDuration('cluster_1956408958_1956408961_1956408963_463134911', 20)
                    
                
                for TS in range (4):
                    traci.trafficlight.setPhase('cluster_1956408958_1956408961_1956408963_463134911', 3)
                    traci.trafficlight.setPhaseDuration('cluster_1956408958_1956408961_1956408963_463134911', 4)
                       
                    
                        
                reward1 += traci.edge.getTraveltime('14367817#2')
                reward2 += traci.edge.getTraveltime('185056611#2')
                reward3 += traci.edge.getTraveltime('185056637#2')
                reward4 += traci.edge.getTraveltime('185056635#1')
            
            if (action == 2 and light[0][0][0]==0):
                for TS in range(20):
                    traci.trafficlight.setPhase('cluster_1956408958_1956408961_1956408963_463134911', 4)
                    traci.trafficlight.setPhaseDuration('cluster_1956408958_1956408961_1956408963_463134911', 20)
                    TOT_WT = WT_S + WT_N + WT_W
                    
                for TS in range (4):
                    
                    traci.trafficlight.setPhase('cluster_1956408958_1956408961_1956408963_463134911', 5)
                    traci.trafficlight.setPhaseDuration('cluster_1956408958_1956408961_1956408963_463134911', 4)
                       
                        
            
                reward1 += traci.edge.getTraveltime('14367817#2')
                reward2 += traci.edge.getTraveltime('185056611#2')
                reward3 += traci.edge.getTraveltime('185056637#2')
                reward4 += traci.edge.getTraveltime('185056635#1')
            
            if (action == 3 and light[0][0][0]==0):
                for TS in range(20):
                    traci.trafficlight.setPhase('cluster_1956408958_1956408961_1956408963_463134911', 6)
                    traci.trafficlight.setPhaseDuration('cluster_1956408958_1956408961_1956408963_463134911', 20)
                    TOT_WT = WT_S + WT_N + WT_E
                
                for TS in range (4):
                    
                    traci.trafficlight.setPhase('cluster_1956408958_1956408961_1956408963_463134911', 7)
                    traci.trafficlight.setPhaseDuration('cluster_1956408958_1956408961_1956408963_463134911', 4)
                   
                                          
                reward1 += traci.edge.getTraveltime('14367817#2')
                reward2 += traci.edge.getTraveltime('185056611#2')
                reward3 += traci.edge.getTraveltime('185056637#2')
                reward4 += traci.edge.getTraveltime('185056635#1')
              
             

        
        # take the following action and observe the reward
    next_state = sumoInt.getState()
    reward = reward1 - reward2 - reward3 - reward4

**Comment by namdre** [comment]
This is the wrong place for "debug my code for me" questions: https://sumo.dlr.de/docs/FAQ.html#i_want_to_do_a_project_with_sumo_can_you_help_me_with_the_implementation
