### ISSUE TITLE
Simulation timestamp Output

### ISSUE THREAD

**Issue by Domsall** [eclipse/sumo#8129]
Hello SUMO-Team,

when I output simulation results via fcd-output or tlsState (probably also happens when outputting other results), the timestamp only gets written with 2 numbers after the decimal point. I now have a few simulations, which I, for example, run at 0.025s. The timestamps are then outputted as "0.03", "0.05", "0.08", etc.

Is there an option to output more numbers after the decimal point or was this not needed and therefore not implemented yet?!

Thanks in advance!!!

**Comment by namdre** [comment]
the easiest workaround is to set **--precision 3**

**Comment by namdre** [comment]
@behrisch should we simply warn about low precision when running with step-length that is not a multiple of 0.01? We could automatically increase the time-output precision but most likely, the other outputs will suffer from low precision as well.

**Comment by behrisch** [comment]
The default for precision should probably be at least the number of digits the step size has.

**Comment by namdre** [comment]
> The default for precision should probably be at least the number of digits the step size has.

We already had the code that tried to do this. It was just using the wrong math.
