### ISSUE TITLE
output --queue-output command

### ISSUE THREAD

**Issue by Fatimaghaffar** [eclipse/sumo#8133]
I'm using --queue-output command 
**sumo-gui -n map.net.xml --queue-output queue.xml** 
and 
simo gui got open but simulation didn't start. 

![Untitled](https://user-images.githubusercontent.com/56623612/105819738-6364ed00-5fda-11eb-9f98-381910857e99.png)

**Comment by namdre** [comment]
You did not define any traffic for your simulation. Please see https://sumo.dlr.de/docs/Tutorials.html#beginner_tutorials

**Comment by Fatimaghaffar** [comment]
> You did not define any traffic for your simulation. Please see https://sumo.dlr.de/docs/Tutorials.html#beginner_tutorials

I have defined the traffic for simulation and its working properly without --verbose command and showing this error with --verbose.

**Comment by namdre** [comment]
your command `sumo-gui -n map.net.xml --queue-output queue.xml` does not load any traffic (only the network).

**Comment by Fatimaghaffar** [comment]
> your command `sumo-gui -n map.net.xml --queue-output queue.xml` does not load any traffic (only the network).

then how to load traffic in this command?

**Comment by behrisch** [comment]
add `-r myroutes.rou.xml`

**Comment by Fatimaghaffar** [comment]
> -r myroutes.rou.xml

its running :) thank you
