### ISSUE TITLE
fix or prevent an "inverse selection" on the webWizard OSM-Map

### ISSUE THREAD

**Issue by angelobanse** [eclipse/sumo#8135]
explaining it is a little bit tricky...
here is a video showing the current (undesired) behavior:

https://user-images.githubusercontent.com/16121932/105865523-4f79b500-5ff3-11eb-957d-0e0dd6217fcc.mov

**Comment by behrisch** [comment]
I would consider this a feature not a bug. I mean what would be the alternative? Blocking the movement of the cursor beyond the lower left corner of the selected area?

**Comment by angelobanse** [comment]
This happens whenever any selection border is exceeded. Just one border is enough (any side, top or bottom), and not necessarily two as in the video (in this case vertical ⬇️  and horizontal ◀️ at the same time).

I see three alternatives:
a) As you say, prevent the resizing that exceeds any of the current selected borders.
b) Allow a free selection and movement (as it is tried in the video), and internally adjust the borders (x0, x1, y0, y1) in https://github.com/eclipse/sumo/blob/1c5bfdba3c017f8ca68a2bbe0642901f5c91278f/tools/webWizard/script.js#L130
c) Leave it as it is, but offer some kind of a "selection reset". If someone falls into this bug, the only current way to modify their ***bad*** selection is by reloading the page, but this way they lose all input and configuration that the user may have already done in the wizard.

**Comment by namdre** [comment]
As a user I would expect b) - the obvious interpretation of the given border.
