### ISSUE TITLE
Acosta is not using busses anymore

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#8136]
Maybe they are afraid of COVID? Honestly the pedestrian/persontrip scenario sees no one entering a bus.

**Comment by namdre** [comment]
I do see people entering buses and riding (easy to spot the blue persons when coloring persons 'by mode'). However, towards the end of the scenario, pedestrians are getting jammed when exceeding busStop capacity (#3706)

**Comment by namdre** [comment]
fixed by setting option **--pedestrian.striping.reserve-oncoming 0.34**.
An alternative would have been to increased busStop capacity by setting `personCapacity="100"` at busStop "busStop#31" (90 is not enough).

**Comment by behrisch** [comment]
The problem was with the extraction script which did not work for Windows (quoting of command line arguments). Has been fixed now.
