### ISSUE TITLE
Cannot find tutorial/citymobil in SUMO_HOME

### ISSUE THREAD

**Issue by FrederikRB** [eclipse/sumo#8137]
Hello,
I cannot find the citymobil tutorial files such as createnettaxi.py among other tutorials as well. I can only find the files to the tutorials: "hello", "manhattan", "quickstart" and "traci_tls". 
I installed the newest version (1.8.0) and downloaded the tar package. May I kindly ask you where I can find these files?
Thank you.
Kind regards, 
Frederik

**Comment by behrisch** [comment]
You can find the files here: https://github.com/eclipse/sumo/tree/master/tests/complex/tutorial/city_mobil but you are right they should be in the downloads

**Comment by FrederikRB** [comment]
Thank you.
