### ISSUE TITLE
Conflict with flows

### ISSUE THREAD

**Issue by SujanSanjula96** [eclipse/sumo#8142]
![Screenshot (272)](https://user-images.githubusercontent.com/56070320/106098445-0e061880-615f-11eb-864f-1bd308b758cd.png)
![Screenshot (275)](https://user-images.githubusercontent.com/56070320/106098452-0fcfdc00-615f-11eb-8c1f-4d073f71c790.png)

I am currently working on a simulation with left lane driving. At the junction, there are 4 left turns which are not controlled by traffic lights. As shown in simulation window, circled vehicles are blocked due to a conflict issue with the left turn of the south edge even though there is no any left turn vehicles.(Sometimes there can be vehicles waiting to  join it) I attached netedit window with connections as well. What is the reason and is there any way to fix this kind of conflict?

**Comment by namdre** [comment]
The right-of-way rules should be changed to give the blocked vehicle right of way over the channelized left turn. This can be accomplished by giving the channelized left turn edge a lower priority value than the westbound exit edge from the main junction.

**Comment by behrisch** [comment]
Please reopen if problems persist.
