### ISSUE TITLE
Deadlocks on junctions after forced lane changes

### ISSUE THREAD

**Issue by BjoernPK** [eclipse/sumo#8143]
Dear community,

in one of our simulation models a problem occurs in the newer SUMO versions (1.7 and 1.8), which I had already read about in another (already solved) ticket. Here, reproducible, but depending on the simulation model and parameterization, deadlocks occur at different times in the intersection area.

The problem seems to be due to the forced execution of lane changes - in a reference simulation without manually executed lane changes, no congestion/deadlocks occur. Is this possibly a known bug? Or have I done something wrong in our implementation? At least in the version 1.1 used so far, the following code could be used without any problems:

`self.LC_MODE_DEFAULT = traci.vehicle.getLaneChangeMode(self.id)`

`traci.vehicle.setLaneChangeMode(self.id, 0)`

`traci.vehicle.changeLane(self.id, self.get_new_lane_id(), 0.2)`

`traci.vehicle.slowDown(self.id, self.MAX_SPEED * 0.75, 0.4)`

...

`traci.vehicle.setLaneChangeMode(self.id, self.LC_MODE_DEFAULT)`

I appreciate any feedback and help - many thanks in advance!

Best regards,
BjoernPK

![deadlock_v1 7](https://user-images.githubusercontent.com/65404947/106100990-822fc480-613d-11eb-9681-833a3f237f1a.png)
![deadlock_v1 8](https://user-images.githubusercontent.com/65404947/106100992-82c85b00-613d-11eb-8ec5-72b83ce3a835.png)

**Comment by namdre** [comment]
Some aspects of the junction model were changed to enable parallel execution. I guess that your forced lane change runs into an untested part of the state space and triggers a bug. It would be great if you could package a minimal version of the scenario (minimal traci script and all necessary input files) and attack it to this ticket (as zip).
See also https://sumo.dlr.de/docs/TraCI/Interfacing_TraCI_from_Python.html#generating_a_log_of_all_traci_commands

**Comment by BjoernPK** [comment]
Please find all requested files attached. Unfortunately, the bug appears only after a relatively long simulation time, so the files have become quite large. If more files are needed for diagnosis, I will be happy to provide them.

Thanks for your effort in advance!

[simulation_8143.zip](https://github.com/eclipse/sumo/files/5893393/simulation_8143.zip)

**Comment by namdre** [comment]
Thanks for the example data. I can reproduce the deadlock with 1.8.0.
However I don't think that this is actually due to a bug in the newer sumo version. I think that the problem is triggered by problems with the old network file (network version 0.27.0). In the sumo versions since 0.27.0 many issues with regard to intersection rules (which are encoded in the network) have been fixed.
When updating the network via `netconvert -s old.net.xml -o new.net.xml` the deadlock disappears. 

Please re-open if you can catch a deadlock using an updated network file.
