### ISSUE TITLE
refactor osm import to read the file only once

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#8147]
would allow for piping data from osmconvert and may speed up things, see #7988

**Comment by behrisch** [comment]
may be more difficult when parsing multiple osm files

**Comment by behrisch** [comment]
only enable single pass if there is only a single file as input

**Comment by behrisch** [comment]
Reduced the time spent on the Berlin network from 7 minutes to below 4.
You cannot parse OSM files with multiple node / way sections any longer, though (which is illegal according to the [specs](https://wiki.openstreetmap.org/wiki/OSM_XML#Certainties_and_Uncertainties) anyway, but was used in some tests).

**Comment by namdre** [comment]
nice!
