### ISSUE TITLE
Remote Server and Client

### ISSUE THREAD

**Issue by ilyasbsran** [eclipse/sumo#8149]
Hello, I'm trying to build a server-client based system on SUMO. I want SUMO working as a server to work on a remote server and clients to connect to here and show the same system on more than one computer synchronously. For this, you have code explanations on the link given below and you communicate over TCP, but when I try to run the system, unfortunately it does not work. Where can I access the sample server-client codes, in which the codes in the link given below are explained?
https://sumo.dlr.de/docs/TraCI.html

**Comment by namdre** [comment]
running GUI as a client is currently not supported (#6673). If you need to show the simulation on multiple systems you can use a middleware like https://pypi.org/project/sumo-web3d/

For general traci examples, see https://sumo.dlr.de/docs/Tutorials.html#traci_tutorials

**Comment by ilyasbsran** [comment]
Hello, Thank you for your answer, I want to add random vehicle and route, are there any examples for this?

**Comment by behrisch** [comment]
see https://sumo.dlr.de/docs/Tools/Trip.html#randomtripspy
