### ISSUE TITLE
Lane Offset of sublane model seems to depend on simulation step length

### ISSUE THREAD

**Issue by Domsall** [eclipse/sumo#8154]
Hello,

I started to use the sublane model for better lateral representation. But when I simulate with small time steps (0.1s), the vehicles don't really dawdle laterally although I am using lcSigma=0.9. When I change the simulation step length to 0.5s, then the vehicles dawdle as expected.

Am I using the parameters wrong or is this simulation step dependant and shouldn't be?! I could backtrace the resulting output to `MSLCM_SL2015::computeSpeedLat`.

I also added a short example:
[test_junction.zip](https://github.com/eclipse/sumo/files/5888787/test_junction.zip)

Thanks in advance!!!

**Comment by namdre** [comment]
lateral deviations appear to be independent of sim-step when using latAlignment="center". I think the problem is specific to latAlignment="arbitrary".

**Comment by Domsall** [comment]
thanks for looking into it, I will just use "center" for now. I am having another problem with the lateral speed, which can also be seen in the simulation above. It may increase/decrease for a while, but then happens to jump back to 0, when the directionWish changes. Can this be changed in the future to allow for more smooth trajectories?!

**Comment by namdre** [comment]
> I am having another problem with the lateral speed, which can also be seen in the simulation above. It may increase/decrease for a while, but then happens to jump back to 0, when the directionWish changes. Can this be changed in the future to allow for more smooth trajectories?!

can you point out which vehicle and timestep to look at? Is this with "center"?

**Comment by Domsall** [comment]
I am not using the last build, so it might not be the same time step. But e.g. vehicle_0 has a lateral speed between -0.3m/s and -0.4m/s at time steps 4.5s-5.0s, but at 5.1s (0.1s steps) this lateral speed is changed to 0.0m/s. This happens again at 8.5s with the lateral speed going from 0.5m/s to 0.0m/s.

**Comment by Domsall** [comment]
Did you look into the simulation and could find the mentioned jumps?

**Comment by namdre** [comment]
yes. I'm seeing the jump

**Comment by namdre** [comment]
now tracked via #8195
