### ISSUE TITLE
remap pt stops instead of keeping edges

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#8155]
currently public transport stops inhibit edge joining leading to larger networks if ptstop-output is active

**Comment by namdre** [comment]
current behavior can cause loss of route edges in ptline-output if the route starts at a joined edge (the id of the joined edge is not in the route). This may be problematic when using ptline-output for gtfs mapping.
Indicated by ptlines2flows warning "Cannot extend route before first stop for line 'X' (stop edge Y not in route)
