### ISSUE TITLE
Simulate the Own Model

### ISSUE THREAD

**Issue by ilyasbsran** [eclipse/sumo#8158]
Create a model with examples /exp_configs/rl/singleagent/singleagent_traffic_light_grid.py file and rlibs library. How can we simulate this model we have created on TrafficLightGridNetwork. We did not find any results when we examined the related documents. When we run "python3 simulate.py singleagent_traffic_light_grid" in this way, it works without including the model. We want to run it according to our model.

**Comment by behrisch** [comment]
This seems to be a question concerning flow. Please ask there: https://github.com/flow-project/flow
