### ISSUE TITLE
netconvert Warning: Could not write OpenDRIVE geoReference

### ISSUE THREAD

**Issue by samidh93** [eclipse/sumo#8159]
I imported openstreetmap osm to sumo netedit and add demands .rou.xml.
I exported the network as .net.xml and switch to sumo-gui and save sumocfg file.
I ran the simulation and everything was working.
last step i tried to convert the network .net.xml to opendrive xodr but i got the following message:
<pre>
netconvert -s map2.net.xml --opendrive-output map2.xodr 
Warning: Found angle of 144.82 degrees at edge '376269501#2', segment 1.
Warning: Could not write OpenDRIVE geoReference. Only unshifted Coordinate systems are supported (offset=-387572.76,-5821156.19)
Success.
</pre>
Unfortunately, the output xodr file could not be processed for later purposes.
I tried different osm maps with  different sizes and complexity but i got always a lot of warnings.
Any help on this issue?
is there a better way to use netconvert?
is it faisable to convert osm map with sumo at all?

**Comment by namdre** [comment]
If you need a geo-referenced xodr file, add option **--offset.disable-normalization** during initial osm import.
Regarding other warnings (i.e about angles), note that you are converting from a format with comparatively low geometric detail into a high detail format.  Netconvert does some smoothing but this is often guesswork.
I know projects that have successfully used used osm-derived xodr.
Are the other warnings you are getting on the netconvert side or from other applications that are using the generated xodr?

**Comment by namdre** [comment]
discussion continues via email
