### ISSUE TITLE
SUMO installation

### ISSUE THREAD

**Issue by g-shilpi** [eclipse/sumo#8161]
Platform: 
--     Host: Linux-4.18.0-25-generic x86_64
--     Target: Linux-4.18.0-25-generic x86_64
--     CMake: 3.19.4
--     CMake generator: Unix Makefiles
--     CMake build tool: /usr/bin/make
--     Compiler: GNU 8.3.0
-- 
-- Found Python: /usr/bin/python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named setuptools
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
CMake Error at /snap/cmake/775/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
  Failed to find XercesC (missing: XercesC_LIBRARY XercesC_INCLUDE_DIR
  XercesC_VERSION)
Call Stack (most recent call first):
  /snap/cmake/775/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:582 (_FPHSA_FAILURE_MESSAGE)
  /snap/cmake/775/share/cmake-3.19/Modules/FindXercesC.cmake:105 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:295 (find_package)

-- Configuring incomplete, errors occurred!

**Comment by behrisch** [comment]
The error message is quite clear: Please install xerces-c

**Comment by g-shilpi** [comment]
Hi,

Following video tutorial: *https://www.youtube.com/watch?v=T4ooawKRsTM
<https://www.youtube.com/watch?v=T4ooawKRsTM>*
Installed SUMO from site: *https://sourceforge.net/projects/sumo/
<https://sourceforge.net/projects/sumo/>*
Installed repositories from:
*https://sumo.dlr.de/docs/Installing/Linux_Build_Libraries.html
<https://sumo.dlr.de/docs/Installing/Linux_Build_Libraries.html>*

Installed tar file for Xerces and it's configured correctly. But still when
I compile ./configure command for SUMO, it's returning missing libxerces
file after compiling for some time. Most of the files are configured
successfully. Just returning this error message

Error:


*checking for XERCES... nochecking for main in -lxerces-c... noconfigure:
error: xerces-lib not found. Specify path with option
--with-xerces-libraries=DIR.*

I am not able to find this file. Kindly help out.

**Comment by behrisch** [comment]
The Build Libraries docs are only for people who want to build everything from scratch. Please try installing xerces-c from you package manger as mentioned here: https://sumo.dlr.de/docs/Installing/Linux_Build.html#installing_required_tools_and_libraries
