### ISSUE TITLE
detecting the cause of a collision

### ISSUE THREAD

**Issue by Izzatbrg** [eclipse/sumo#8163]
Hello,
I'm trying to make the sumo an RL environment to manage an intersection. In order to make a reward function, I should know which action did the agent takes, that caused the collision. I did use the : 
`traci.simulation.getCollidingVehiclesIDList()`
but it doesn't provide any extra information that can be used to detect which vehicle is responsible. Is there any way to get this info? what do you recommend to solve this problem?
thanks a lot

**Comment by namdre** [comment]
in the latest development version you can use traci.simulation.getCollisions to get additional information on collision events.
Download available at https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_development_version
The simulation tries to guess the roles of "collider" and "victim" . For junction collision it classifies the vehicle with right-of-way as "victim".
