### ISSUE TITLE
let personFlow start within vehicle

### ISSUE THREAD

**Issue by rummel123** [eclipse/sumo#8165]
It would be a nice feature, if I can start a `personFlow` or a `containerFlow` with a `ride` or a `transport` within a vehicle.

In my case I like to start a large number of containers within a train with `containerFlow` and parameter `number`. Now the containers are loaded (that lasts n x loadingTime) and after the loading the train is starting. If I change the number of containers, the train is starting at different times that changes my schedule of the szenario.

**Comment by behrisch** [comment]
Proposal add a depart attribute to the personflow which can have the value triggered

**Comment by namdre** [comment]
alternative which might be easier on the schema with regard to permitted flow attributes: permit personFlow with `begin="triggered"`
(also: if this is used, ignore attribute end and only permit attribute number)
