### ISSUE TITLE
invalid SCALED_TAU in intermodal scenario

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#8167]
tau is scaled by total lane number instead of usable lanes

**Comment by behrisch** [comment]
depends on the vehicle classes to be used and probably needs a new option

**Comment by behrisch** [comment]
Proposal: new option "meso.vclass-queues" (or something similar) accepting a list of vclasses, default something like the complement of "pedestrian bicycle moped rail rail_urban rail_electric tram ship". Semantics:
1. Make a separate queue for each lane which has at least one permitted class in this list
2. Merge two adjacent queues into one if they have same permissions (restricted to this list) and multilane is not active for the segment.

@namdre please add your comments

**Comment by behrisch** [comment]
It may be easier to specify the vclasses which should be ignored, so maybe rather meso.vclass-ignore and the default "pedestrian" could be enough.
