### ISSUE TITLE
extend taxi api for reservation state

### ISSUE THREAD

**Issue by ArmelliniMG** [eclipse/sumo#8168]
It would be useful to be able to retrieve reservations by state, for example:
getTaxiReservations( -1 all, 0 reservations waiting for assignment, 1 reservations assigned to a vehicle, 2 reservations served)
It would be also useful to have an extra reservation attribute with the state (assined, waiting, served). Maybe an extra state for "rejected" reservations could be relevant too.

**Comment by namdre** [comment]
the integer argument for getTaxiReservations now has the following semantics:
- 0: retrieve all
- 1: only new (retrieves every reservation just once)
- 2: already retrieved
- 4: assigned
- 8: picked up
- 16: finished (currently not used. finished reservations are deleted from the system)

any combinations are possible 4+8 means assigned + picked up.

**Comment by ArmelliniMG** [comment]
State 8 (picked up) is not working as I expected. the state wont change until the taxi leave the stop of drop-off. 
For example: if `traci.vehicle.dispatchTaxi('taxi', [0][0])` is defined, the state of reservation `0` would be **8 (picked up**) until simulation ends, even though the person of reservation `0` even left simulation.

**Comment by namdre** [comment]
> **State 8 (picked up)** wont change until the taxi leave the stop of drop-off.
> For example: if `traci.vehicle.dispatchTaxi('taxi', [0][0])` is defined, the state of reservation `0` would be **8 (picked up**) until simulation ends, even though the person of reservation `0` left simulation.
> 

In the current tests, the state is "picked up" until the vehicle reaches the stop. Then the reservation is removed from the system. So indeed, state 16 (fulfilled) is never used but the returned state is valid as long as the reservation exists. 
I wasn't able to reproduce your finding of  "picked up, though person left the simulation".

**Comment by ArmelliniMG** [comment]
Mini scenario for testing:
[Test_States.zip](https://github.com/eclipse/sumo/files/6041936/Test_States.zip)

**Comment by ArmelliniMG** [comment]
I wasn't working with the latests sumo...
Now it works perfectly :)
