### ISSUE TITLE
Install SUMO on Linux

### ISSUE THREAD

**Issue by jiao1997** [eclipse/sumo#8169]
Dear all,
       I am new to SUMO. I'd like to install SUMO on a Linux server. But I didn't have the root permission. I can not run "sudo". What should I do with it.

**Comment by behrisch** [comment]
Try [building sumo yourself](https://sumo.dlr.de/docs/Installing/Linux_Build.html) or use `pip install sumo`.

**Comment by jalemann** [comment]
When using `pip` it's actually `pip install eclipse-sumo` (see: https://pypi.org/project/eclipse-sumo/) as `sumo` is [some other package](https://pypi.org/project/sumo/).

**Comment by behrisch** [comment]
You are right, I edited my post above to reflect the correct name
