### ISSUE TITLE
SUMO-GUI and NETEDIT aren't compatible with FFMPEG-4.3.1

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#8170]
Entire recording video modul must be reimplemented and tested in Windows and Linux

**Temporal solution:** SUMOLibraries has old FFMPEG version 4.2.0. New 4.3.1 is in _experimental/FFMPEG-4.3.1_

**Comment by behrisch** [comment]
may be connected to #10378

**Comment by behrisch** [comment]
I just tested 4.3.1 on Windows (the experimental branch from SUMOLibraries) and it just works. Even #10378 does not show up anymore. @palvarezlopez can you maybe recheck?

**Comment by palvarezlopez** [comment]
Fixed in https://github.com/eclipse/sumo/issues/12750
