### ISSUE TITLE
Error Installing SUMO on UBUNTU

### ISSUE THREAD

**Issue by edgaremanu** [eclipse/sumo#8172]
Hello everyone.

I have the following error when trying to install SUMO on ubuntu 16

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 sumo : Depends: gdal-abi-2-2-3
E: Unable to correct problems, you have held broken packages.

Thanks for your help!

**Comment by behrisch** [comment]
Please check whether you have some unusual gdal packages installed. Most of the time it is Anaconda or some similar package which brings its own libraries and modifies the library path.

**Comment by edgaremanu** [comment]
> Please check whether you have some unusual gdal packages installed. Most of the time it is Anaconda or some similar package which brings its own libraries and modifies the library path.

Yes. I have installed Anaconda in /home/Anaconda

Where should I install Anaconda to avoid this problem?

When uninstalling Anaconda the problem with the installation of SUMO is solved?

**Comment by behrisch** [comment]
Uninstalling should definitely help, changing the location probably won't. Please check your LD_LIBRARY_PATH after uninstalling by using `echo $LD_LIBRARY_PATH`

**Comment by behrisch** [comment]
Seems to be solved, please reopen if problems persist
