### ISSUE TITLE
improve netconvert logging

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#8175]
even with warning aggregation it is hard to keep track of what led to a failed run. Proposals

- [ ] make sure "Quitting on error" is always the last line (if it needs to be printed)
- [ ] maybe repeat at least the last error message leading to abortion (if fast failure is not an option)
- [ ] do not print network statistics for failed runs

**Comment by namdre** [comment]
always repeating error messages even if there is no intermediate output looks a bit silly.

**Comment by behrisch** [comment]
That's why it is only done in verbose mode but we can also add an option for that. Ideas are welcome.
