### ISSUE TITLE
I need detailed information of the traffic light index 

### ISSUE THREAD

**Issue by Ildemselcuk** [eclipse/sumo#8183]
How can I learn the duration of the information of traffic lights in Sumo for light for link in tllogic with the help of traci?

I don't ask for all the traffic lights or the stage, I just need detailed information about an index within the traffic lights.

Best Regards,

**Comment by namdre** [comment]
If I understand your question correctly, you wish to determine how long a specific traffic light link index will remain in it's current state.
To do this, you have to retrieve the complete signal plan (all phases) and then add the following durations:
- the remaining duration in the current phase
- the duration of subsequent phases where the link remains in it's current state

**Comment by Ildemselcuk** [comment]
Are there any example studies? I haven't encountered any examples in the documents on Sumo's official github and site. I am waiting for your feedback on the subject. 

Best Regards,

**Comment by namdre** [comment]
https://sumo.dlr.de/docs/Tutorials.html#traci_tutorials
https://github.com/eclipse/sumo/blob/master/tests/complex/traci/trafficlight/trafficlight/runner.py

**Comment by Ildemselcuk** [comment]
First of all, thank you for the links you sent, but how can I find out the duration of traffic lights information in Sumo for light in the index on tllogic with the help of traci in the links you send?

Regarding my above question, I could only see a set method for traffic lights index (setLinkState ()).

But give me linkstate's duration and other information, I need get methods. 

Best Regards,

**Comment by namdre** [comment]
for current phase remaining time, see command getNextSwitch: https://sumo.dlr.de/docs/TraCI/Traffic_Lights_Value_Retrieval.html
to retrieve the durations of future phases:
-  use traci.trafficlight.getAllProgramLogics 
- if there are multiple programs, determine the current program from the list using `getProgram`
- determine the current phase in the programs list of phases (Logic.phases) using `getPhase`
- each phase has a state that describes all links. Check the state of the desired link by looking up the state code at the corresponding index

if you only need the state in the current phase its getRedYellowGreenState(tlsID)[linkIndex])

**Comment by Ildemselcuk** [comment]
Thank you for sharing information Mr.Nambre.Well, is there a method by which I can learn the traffic light index of the time? 

Best Regards,

**Comment by namdre** [comment]
maybe your are looking for traci.vehicle.getNextTLS ?
