### ISSUE TITLE
Questions about config files and output

### ISSUE THREAD

**Issue by jiao1997** [eclipse/sumo#8184]
Dear all,
       I am using sumo for a real city simulation. What I concern about is the simulation time. How can I output the total simulation time?(may in the config file?). By the way, where can I find the meaning of the various options in "config files".
      Hope to get your early reply.
Yours,
Jiahao Wang

**Comment by namdre** [comment]
see https://sumo.dlr.de/docs/sumo.html
https://sumo.dlr.de/docs/Simulation/Output.html#timing_data

**Comment by jiao1997** [comment]
Thanks for your reply, I will look at it.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "eclipse/sumo"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月4日(星期四) 晚上8:24
收件人:&nbsp;"eclipse/sumo"<sumo@noreply.github.com&gt;;
抄送:&nbsp;"J"<1056378996@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [eclipse/sumo] Questions about config files and output (#8184)





 
see https://sumo.dlr.de/docs/sumo.html
 https://sumo.dlr.de/docs/Simulation/Output.html#timing_data
