### ISSUE TITLE
document statistic-output

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#8188]
was added in #3751  (reproduces command-line output in xml form)

- [x] new output page
- [x] linked from https://sumo.dlr.de/docs/Simulation/Output.html#simulationnetwork-based_information
- [x] linked from https://sumo.dlr.de/docs/Simulation/Output.html#commandline_output_verbose

**Comment by namdre** [comment]
fair TTT  after setting sumo options **--tripinfo-output.write-unfinished --duration-log.statistics --statistic-output stats.xml**
based on the elements of stats.xml:

vehicles.inserted * (vehicleTripStatistics.duration + vehicleTripStatistics.departDelay)+ vehicles.waiting * vehicleTripStatistics.departDelayWaiting

**Comment by angelobanse** [comment]
FYI: i'm moving `docs/Simulation/Output.md` to `docs/Simulation/Output/index.md`
