### ISSUE TITLE
od2trips should complain on non square matrices (trac #819)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#819]
at least a warning would be helpful if lines or columns are left out

Migrated from http://sumo.dlr.de/ticket/819
```json
{
    "status": "new", 
    "changetime": "2014-03-07T12:10:57Z", 
    "description": "at least a warning would be helpful if lines or columns are left out", 
    "reporter": "behrisch", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1394194257239153", 
    "component": "tools (OD2TRIPS, POLYCONVERT)", 
    "summary": "od2trips should complain on non square matrices", 
    "priority": "major", 
    "keywords": "", 
    "time": "2012-12-12T11:28:37Z", 
    "milestone": "1.1.0", 
    "owner": "", 
    "type": "defect"
}
```

**Comment by passengerxuhongli** [comment]
what is the od2trips's input-files(OD_matric?)? 
what is the format of this input files?

**Comment by namdre** [comment]
http://sumo.sourceforge.net/userdoc/Demand/Importing_O/D_Matrices.html#Describing_the_Matrix_Cells

**Comment by passengerxuhongli** [comment]
thanks namdre, this answer helps me. The "districts" confused me at first, now i understand that this "districts" means the number of nodes in my *.net.xml file!

**Comment by namdre** [comment]
Error handling for the V-Format is working.
For the O-Format I would regard it at as a feature that sparse matrices can be defined.

**Comment by behrisch** [comment]
I would not consider EOF a helpful error message. Furthermore we should probably also warn if there are superfluous rows or columns. I agree for the O format.
