### ISSUE TITLE
Where to modify IDM / CACC carfollow model code?

### ISSUE THREAD

**Issue by gaofenxia** [eclipse/sumo#8191]
I set up carfollowmodel = "IDM"（or "CACC"） in .rou.xml,   but I want to modify the car following rules of IDM,   so where should I modify them?

**Comment by namdre** [comment]
https://github.com/eclipse/sumo/blob/master/src/microsim/cfmodels/MSCFModel_IDM.cpp etc

**Comment by gaofenxia** [comment]
And how to use the modified code in my own case? How to quote?

**Comment by namdre** [comment]
I don't understand your question. If you modify the original IDM code and recompile sumo then you can obviously use this.
If you wish to implement a new model, see https://sumo.dlr.de/docs/Developer/How_To/Car-Following_Model.html
