### ISSUE TITLE
Problems encountered when using different action time step and simulation time step

### ISSUE THREAD

**Issue by zhuhj-tery** [eclipse/sumo#8193]
Hello SUMO team,

Recently, we are trying to use Traci to control the vehicle. We set the simulation time step to be 0.1s and set the action time step to be 1s. The simple continuous lane-change model is implemented and we set the lane change duration to be 1s. We generate a vehicle "CAV" controlled by IDM and LC2013. We tried to use Traci.vehicle.lanechangerelative("CAV",1,1) to force the vehicle to conduct a lane change. After the lane-change behavior is completed, we couldn't control the vehicle any further.  The sumo-GUI showed the message: Request backPos of vehicle 'CAV' for invalid lane '0to1_0' time=17.70. In addition, the acceleration was always 0, which was not reasonable. We also did some tests and found out that when we set the action time step to 0.1s, the simulation became normal. So, we are guessing if there are some problems when the action time step is different from the simulation time step.

Thank you very much!

**Comment by zhuhj-tery** [comment]
Also, after we set the action time step to be 1s, the functions: traci.vehicle.getneighbors() and traci.vehicle.getfollower(), can't output anything. In our opinion, there might be some problems with the action time step setting.

**Comment by namdre** [comment]
> Also, after we set the action time step to be 1s, the functions: traci.vehicle.getneighbors() and traci.vehicle.getfollower(), can't output anything. In our opinion, there might be some problems with the action time step setting.

This issue should be fixed via #8119 so you could update to the latest development version and test this.

**Comment by zhuhj-tery** [comment]
> > So, we are guessing if there are some problems when the action time step is different from the simulation time step.
> 
> This may well be since there haven't been any tests for combining action-step-length with the simple continuous lanechange model until just now.
> 
> Can you reproduce unexpected behavior or warnings when running your simulation without traci?

The unexpected behavior does not happen when traci is not involved. And the warnings also disappear.

**Comment by namdre** [comment]
please provide a minimal scenario that reproduces your issue. See also https://sumo.dlr.de/docs/TraCI/Interfacing_TraCI_from_Python.html#generating_a_log_of_all_traci_commands

**Comment by zhuhj-tery** [comment]
When I update sumo to the latest version, the problem does not occur again. Thank you very much.
