### ISSUE TITLE
lateral acceleration exceeds lcAccelLat

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#8195]
responsible code was meant to avoid unsafe driving but may not be needed in many situations (if at all)
https://github.com/eclipse/sumo/blob/3adde0c10ac74afe77d080fe11145721f40aefdf/src/microsim/lcmodels/MSLCM_SL2015.cpp#L3171

**Comment by Domsall** [comment]
Thanks for checking and adding!!!
