### ISSUE TITLE
Override Vehicle spawning

### ISSUE THREAD

**Issue by DarkRaven97** [eclipse/sumo#8202]
How can I spawn vehicles in the Simulation based on Real-Time/Real-Life data input.

Where would i need to override a function in SUMO to change the creation of Vehicles in a flowroute?

I know how many vehicles of predefined Vehicle types (Car, small Truck, large Truck) I need to spawn on which route (and/or lane) each secound if I have the Systemtime and input ID . Network and route are created based on that ID so I could (and probably have to) put it in the route file as some tag value of flow to get it in the function creating vehicles.

**Comment by namdre** [comment]
you can use the traci functions 
`traci.vehicle.add` to create vehicles  and `traci.vehicle.moveTo` (the latter to force vehicles into the network regardless of insertion safety constraints).
See https://sumo.dlr.de/docs/TraCI.html#introduction_to_traci
