### ISSUE TITLE
ACTIVITYGEN street workPosition calculation

### ISSUE THREAD

**Issue by AakashSasikumar** [eclipse/sumo#8203]
Specifications:

OS: Ubuntu 16.0.4
sumo: 1.8.0
Built From Source?: No (apt install)

I've created a statistics file for a city to be used for `activitygen`. In the [documentation website](https://sumo.dlr.de/docs/Demand/Activity-based_Demand_Generation.html#population_and_work_position_distribution), the following is given as the definition for workPosition

workPosition: Number of work positions per meter street. Relative value (normalized with the total number of city's work demand).

This definition seems pretty ambiguous to me. If I have the following information,

- edge length = `L`,
- number of work places on this edge = `n`,
- the total number of work places across all edges = `N`.

Would the formula for calculating the value of `workPosition` be

```
workPosition = n/L

or

workPosition = n/(N*L)
```

I tried the first formula (`n/L`) for getting the value for workPosition, but activitygen throws this error,
```text
===> ERROR: Not enough work positions in the city for all working people...
Not enough free work positions in AGHousehold::allocateAdultsWork. Should not happen.
```
There is the possibility that the number of work positions I have for stat.file is too less for the number of people. Either way, some clarification on how the workPosition is to be calculated will help.

**Comment by namdre** [comment]
according to the code,  `n = L * workPosition * (D / N)`
with `D` = total number of needed work positions. 

See https://github.com/eclipse/sumo/blob/9000d431b77364ce078f1b00d08ca794fd2ab23a/src/activitygen/city/AGCity.cpp#L59-L78

Due to the normalization with the needed work positions, there should not be a shortage if at least on edge has workPosition > 0
(I supposed this gave reason to the "should not happen" part of the error).

**Comment by AakashSasikumar** [comment]
I see that makes a little bit more sense now. I think I had misunderstood the meaning of workPositions so far. From this code, it looks like workPositions is the number of jobs/working people in the city/area of the simulation. I had assumed that it was the number of offices/buildings in each street.

**Comment by namdre** [comment]
No, `workPosition` does model the places where people go to work (office/factory). However, due to the normalization with the number of working people it's a relative density of work places rather than an absolute number. (full employment utopia).

**Comment by AakashSasikumar** [comment]
Sorry for the delayed response.

If the code handles the normalization, what value would I have to put in `workPosition`? I have the number of offices/buildings in each street, I do not have the number of people working in each one however. Would this value suffice for the statistics file?

**Comment by namdre** [comment]
I think the number of buildings should suffice though you will get some inaccuracy due to treating all buildings the same regardless of actual working numbers.

**Comment by AakashSasikumar** [comment]
I see, so if the raw number of buildings are sufficient, does this (raw number of people for a street) hold true for the `population` attribute as well? From the [documentation](https://sumo.dlr.de/docs/Demand/Activity-based_Demand_Generation.html#population_and_work_position_distribution), the `per meter street` makes it a little confusing. I thought we had to divide these raw values with the length of the street.

**Comment by namdre** [comment]
Yes. population is also treated as a density per meter street and normalized with the total number of inhabitants.

**Comment by AakashSasikumar** [comment]
Alright. Thank you so much. I will close this issue.
