### ISSUE TITLE
Vehicle resistance

### ISSUE THREAD

**Issue by Domsall** [eclipse/sumo#8206]
Dear SUMO developers,

I would like to add an option to my CF-model to include vehicle resistance parameters (a_max is reduced at higher speeds). The needed parameters actually already exist via the generic parameter key attribute (e.g. for the battery device and engine models). I was thinking, that the implementation should maybe be a level higher, for example in MSVehicleType, so all models could use the parameters, as this is not a model specific parameter set, but a vehicle specific one.
You probably already talked about this and maybe have a good reason not to implement it that way, but I couldn't find an issue or anything similar. It would also probably be nice to add a default parameter set to the different type definitions (passenger, bus, truck, etc., just like length and width definition).

Is this a good idea? Models, that don't want/need the parameters don't have to be changed, but it would be a "ready-to-go" solution for the Krauss model, if somebody would like to have a changing a-max value depending on the speed and vehicle resistance. New users could use the same parameter set for a highway scenario and in the city, although one would still need to study if this is realistic.
Still, one problem would be, that this increases the parameter set with values, which may not be needed and increases the memory and computation time. A plus would be, that the brake lights would be a bit more realistic.

**Comment by namdre** [comment]
this is strongly related to #3920, #1231

**Comment by namdre** [comment]
Generally, I agree that something along these lines is needed. The question is what level of complexity the solution should take.
FYI, there is already code that computes a friction term and tries to reduce flickering brake lights. Obviously the hard coded defaults don't work in all cases: https://github.com/eclipse/sumo/blob/12a3eb8fa9a1f0371d67e1d5a19dac615f5a243a/src/microsim/MSVehicle.cpp#L3473-L3474

**Comment by Domsall** [comment]
It was more of an architecture question: There already exist engine and battery models. Especially the structure of the battery device is great, although a realistic energy consumption of the vehicle strongly relies on an expert setting up the CF-model for the specific scenario (see also OpenMobility issues 6 and 7), because there is no coupling between the CF models and vehicle dynamics.
For an easier setup of the simulation it would be great to seperate the different levels of detail depending on what the user needs. For understanding and using SUMO to replicate traffic phenomena or huge networks, the existing models are perfect.
Thats why I would like to use a modular approach and the 3 possibilities:
- Simulate only with the CF models ("driver")
- Simulate with resistance force, that is, depending on the CF model, coupled with the driver (environment->vehicle->driver)
- Simulate with a drivetrain, like the battery and engine model (environment->vehicle->drivetrain->driver)

I could now all implement this in my existing CF-model part, but for a better, modular structure I was thinking of this:
- drivetrain parameters (battery model, engine model, street friction model) are already defined in devices, they may change amax or something else, but its up to them
- vehicle parameters are stored in the VehicleType, so the resistance parameters could be put there too and each Vehicle has a default set. Devices (battery, engine) already use resistance parameters, but each device has their own parameterset and calculation.
- The resistance parameters could then be used in the different devices and also in CF-models, if wanted.

I want to implement the vehicle dynamics anyway, so I could also reuse the resistance calculations from the battery device and put it into MSVehicleType and make a pull request. I just thought before implementing resistance terms for my own model, I could also make it "ready-to-go" for all models.

**Comment by namdre** [comment]
Since, the generic vType parameters that are used by the battery device are already quite general (no device prefix) I think you could use those for your cfmodel as well. If you want to refactor some functions from the battery device (or actually the EnergyHelper) to be able to use them from cfmodels, do so.
