### ISSUE TITLE
'offset' is missing when creating a trafficlight.Logic object using traci in Python

### ISSUE THREAD

**Issue by jiawei92** [eclipse/sumo#8209]
The arguments for a Logic object initialization including `programID`, `type`, `currentPhaseIndex`, `phases` and `subParameter`. It seems we cannot pass the parameter `offset` while creating a Logic object. Is there any walkaround for it?

    <tlLogic id="gneJ2" type="static" programID="0" offset="10">
        <phase ...>
        <phase ....>
    </tlLogic>

**Comment by namdre** [comment]
call `traci.trafficlight.setPhaseDuration` immediately after the call to `setProgramLogic`. This will only set the duration of the current active phase of the *current* cycle (and return to the default duration in subsequent cycles).
