### ISSUE TITLE
How to use an algorithm such as bayes theorem to predict the accident events on the roads?

### ISSUE THREAD

**Issue by fahmi06** [eclipse/sumo#8210]
Hi,

I'm still new with the SUMO simulator.

Still having a problem with:
1. How to implement the algorithm such as bayes theorem to predict an accident events on the route? 
2. Do I need to implement the algorithm within TraCI?
3. How do I get a dataset or data from sumo simulator such as speed or traffic light condition using the python?

Thank you. 
Cc: @namdre @behrisch

**Comment by namdre** [comment]
SUMO does not accidents by default.
You can configure models and infrastructure to trigger accidents (https://sumo.dlr.de/docs/Simulation/Safety.html) but then you have to do your own statistics to determine conditional probabilities.
You could do this based on various XML outputs with the help of sumolib: https://sumo.dlr.de/docs/Tools/Sumolib.html
Alternatively, you can use the traci API to retrieve traffic conditions etc: https://sumo.dlr.de/docs/TraCI/Interfacing_TraCI_from_Python.html

Note, that we cannot give you any help on algorithm design. You will have do your own thinking and your own programming:
https://sumo.dlr.de/docs/FAQ.html#i_want_to_do_a_project_with_sumo_can_you_help_me_with_the_implementation
