### ISSUE TITLE
breadcrumbs navigation in SUMO docs

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#8211]
I am often tempted to click on parts of the docs headline to navigate "upwards" (e.g. from Tools/Net to Tools)  which does not work but would be a great feature. I know that the page does not always exist (e.g. there is no Simulation.html) but maybe at least in the cases where it does.

**Comment by angelobanse** [comment]
I will look at it. 
We could offer an index page for every documentation subdirectory, if there is no existing page (e.g. Simulation.html), where we list all available subpages.
