### ISSUE TITLE
od2trips - Error: Out of bounds

### ISSUE THREAD

**Issue by philippwulff** [eclipse/sumo#8218]
I am receiving this error from running od2trips.

```
Error: Out Of Bounds
Quitting (on error).
```

What does it mean? I could not find any explanation of the error in the documentation or somewhere else

**Comment by namdre** [comment]
Could it be that your input is quite large od2trips exceeds available memory?
If not, the error likely indicates a bug. Please attach input files for reproducing the issue (zipped).

**Comment by philippwulff** [comment]
Thank you for your help, but we found a different solution.
