### ISSUE TITLE
Time stamp for Traci control command

### ISSUE THREAD

**Issue by zhuhj-tery** [eclipse/sumo#8220]
Hello,
When I use Traci to control SUMO simulation, I encounter a common phenomenon. In my case, the simulation time step is set to be 0.1s and I use traci.simulation.step(traci.simulation.getTime()+1) to force simulation runs 1s per step. After the step command, I try to control the vehicle's acceleration through traci.vehicle.slowDown(vehID, speed, duration=1.0). I carefully set the target speed considering the issue related to this command. When I check the output trip information, I find out that the vehicle speed starts to change earlier than expected. For example, I want to set the acceleration of the vehicle in [1.0s, 2.0s] to be 1m/s^2, while the results show that the acceleration in [0.9s, 1.9s] is 1m/s^2. Then, in [1.9s, 2.0s], the acceleration changes. I am confused about this issue, and I'm wondering how to realize my goal of setting acceleration in [1.0s, 2.0s]. 
Thanks

**Comment by namdre** [comment]
The first thing to check would be whether your simulation.step commands are aligned with full seconds as intended. 
Note also, that there is currently a known issue with the slowDown command which might affect your results:: #7361

**Comment by zhuhj-tery** [comment]
Thanks!
