### ISSUE TITLE
Vehicle seen on only one of multiple clients

### ISSUE THREAD

**Issue by ilyasbsran** [eclipse/sumo#8227]
I created a multi client by adding a unique tag when starting traci. After i opened two sumo gui (it works). But when i added to car, sometimes ı just see vehicles on one of sumo gui. How can i fix this problem?

**Comment by m-kro** [comment]
As far as I know, your commands should be processed using the currently active TraCI connection using its assigned port. This means your command affects only one SUMO instance at a time. See also [the switch function of the TraCI Python interface](https://sumo.dlr.de/pydoc/traci.main.html) to select a different connection.
