### ISSUE TITLE
Plotting waiting time & queue length by edges at every junction

### ISSUE THREAD

**Issue by amerfathullah** [eclipse/sumo#8239]
Hi, I'm a newcomer here and still learning to use SUMO. I'm trying to plot the waiting time and queue length by edges at every junction. I tried to use --queue-output command and xml2csv.py to convert the output into csv file. Then, I manually rearrange the column and plot it using bubble chart in LibreOffice. This is the output.

![lane plot](https://user-images.githubusercontent.com/36897396/108164999-c9054e80-712c-11eb-92ee-cbdcab3b85c0.png)

Although I manage to plot it, the chart is barely understandable and the process to plot it takes too long as I plot it manually from LibreOffice. Not to mention this is a single chart for a single intersection. Is there any easier way to do this or any SUMO functionalities that I'm not aware of? Thank you.

Regards,
Amer

**Comment by namdre** [comment]
There is no ready made script to plot this kind of information. However, building plots from data in an automated way usually involves some kind of scripting (programming). 
My best advice would be to look at the existing visualization tools in "sumo/tools/visualization" and use them as a guide on writing your own plotting script.
If you create something that could be generally useful, we'd be happy to include it in that collection for other users.

**Comment by amerfathullah** [comment]
alright, thanks for the reply. I'll try looking at it.
