### ISSUE TITLE
How to add new parameters on Sumo Gui network:Parameters

### ISSUE THREAD

**Issue by Ildemselcuk** [eclipse/sumo#8244]
Hello,

I want to add traci other parameters to the blank lines in the attached picture, but I don't know where to change it.I request your support on the subject. 

Best Regards,
![paremeters](https://user-images.githubusercontent.com/15704833/108199505-2fd73780-712e-11eb-8243-aa4e818bee5e.png)

**Comment by namdre** [comment]
Other traci domains (vehicle, junction) already display user-set params in their property dialog.
The simulation domain also supports the getParameter call with a few "magic" parameters.
It would be a small step to also allow the setParameter call with arbitrary values and list those values in the property dialog.

**Comment by Ildemselcuk** [comment]
Firstly, thank you.I have successfully added to the parameters of the vehicles.I understood that  that SetParameters is the objectID vehicle id here.

However, when I wanted to change the general parameters in the above picture for simulation, I got stuck.Because I could not find what parameter I can give as objectID.

Can you give information about the general parameters of the simulation, which are the parameter parts in the example in the picture above?

If there is sample code on this topic, I would be glad if you can share the line in the sample code.

Best Regards,

**Comment by namdre** [comment]
now working: use `traci.simulation.setParameter("", key, value) to set global parameters. They will show up in that dialog just as they do for other domains.
