### ISSUE TITLE
How to prevent vehicles from slowing down when passing road junctions

### ISSUE THREAD

**Issue by kecan666** [eclipse/sumo#8262]
I drew an approximately circular ring road, but found that the vehicle will automatically slow down when passing the road junction, but this is what I don't want. I want the vehicle to drive through this circular road without slowing down as if it were on a straight road. What do i need to do？thank you very much！
![image](https://user-images.githubusercontent.com/47028398/108797757-f0de3180-75c6-11eb-9846-3adcf22ef2f4.png)
this is the road I created.
![image](https://user-images.githubusercontent.com/47028398/108797784-02273e00-75c7-11eb-83e6-6cab65a016e8.png)
Vehicles will slow down when they reach here.

**Comment by namdre** [comment]
build/reload the network with option **--junctions.limit-turn-speed -1"
