### ISSUE TITLE
randomTrips Issue

### ISSUE THREAD

**Issue by CamiloSanabria97** [eclipse/sumo#8266]
Hello
I am trying to use randomTrips to run a traffic experiment over city map, but anytime I run randomTrips I get the same .rou.xml file no matter what. I tried to change the names of the files but is the same, and I tried to use a different number of vehicles, the number of vehicles change, but the routes of the remaining vehicles is the same. In other words the routes never change

Thanks

**Comment by namdre** [comment]
use option **--seed** to change to random seed or use option **--random**
