### ISSUE TITLE
Missing connection road information when importing Opendrive map

### ISSUE THREAD

**Issue by zhuhj-tery** [eclipse/sumo#8269]
Hello, SUMO developers:

I encounter an issue when transforming the Opendrive map file to SUMO network file using netconvert tool. I notice that the SUMO network misses the connection road information in all the junctions. For example, in my Opendrive map file, there are data related to the connection road (id: 3000024) within the junction (id: 3000000) and the road (id: 1029000) connecting this junction with another junction. As a result, the connection road 3000024 is not displayed in the network. It seems that the netconvert tool ignores the road connecting two roads within the junction, i.e. the junction id is not equal to "-1". But, we want to model all the roads in the Opendrive map file including the connection road within the junction. Is there any possible solution?
![image](https://user-images.githubusercontent.com/69643560/108904782-f189be80-75ec-11eb-8c8b-425a95ba6dfc.png)
![image](https://user-images.githubusercontent.com/69643560/108906095-80e3a180-75ee-11eb-92f8-b910ccd37005.png)
![image](https://user-images.githubusercontent.com/69643560/108905792-22b6be80-75ee-11eb-8b83-54721a5ee66e.png)

Thanks!

**Comment by namdre** [comment]
can you provide example input?

**Comment by zhuhj-tery** [comment]
Here is part of the map I want to convert and the corresponding sumo network. This Opendrive map file describes junction 3000000 and there should be 9 roads related to it. However, the netconvert tool only converts the first four roads, which start or end at the junction, and ignores the remaining five roads, which are within the junction. Is it possible to also implement these five roads in the SUMO network file?
Thanks!

[example.zip](https://github.com/eclipse/sumo/files/6039601/example.zip)

**Comment by namdre** [comment]
The connecting roads (within the junction) are transformed to "internal lanes" on the sumo side. Please see https://sumo.dlr.de/docs/sumo-gui.html#investigating_internal_edges_and_lanes 

If you set netconvert option **--output.original-names** then each lane (including internal) lanes will receive a param `origId` that  gives the road id and lane index from the xodr file.  (you can see them in sumo-gui by right-clicking on a lane and selecting Show Parameter').
