### ISSUE TITLE
Improve performance of node removal checks

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#8270]
iterating over all pt stops whenever an edge is merged seems to slow down the process

**Comment by namdre** [comment]
- previous time to build network: 11:46
- time with sc.replaceEdge disabled: 9:8
- new code with lookup table: 9:19

**Comment by behrisch** [comment]
Are there new network build time numbers?

**Comment by namdre** [comment]
* new time for berlin: 6:44
* the time for the 'germany'-network was reduced from 150min to 6min
