### ISSUE TITLE
Locating nearby edges based on the geo-coordinate - error/not working

### ISSUE THREAD

**Issue by zmajstorovic** [eclipse/sumo#8279]
Hello, 
I tried to use the script for[ locating nearby edges based on the geo-coordinates](https://sumo.dlr.de/docs/Tools/Sumolib.html#locate_nearby_edges_based_on_the_geo-coordinate) but it's not working as expected. Although, I have installed _rtree_ and _pyproj_ modules and I still get errors. Tried on two different computers. 

On first PC it shows me error:
> raise OSError("could not find or load {}".format(lib_name))
> OSError: could not find or load spatialindex_c-64.dll

Tried the same script on the second PC and the script does not return any result.  

Any ideas on how to fix the error on the first PC, and why the script does not return any result?

Thank you!

**Comment by zmajstorovic** [comment]
I managed to get the original script for locating nearby edges to work, it just took some time to play with different coordinates and radius values to figure out how it works. Maybe it would be useful if there would be more details about how the script works.

I still have OSError persistent, no idea how to solve that. Any comments are welcome..  thank you

**Comment by namdre** [comment]
feel free to suggest additional information to be put into the documentation. 
regarding OSError, see https://stackoverflow.com/questions/64398516/pyinstaller-exe-oserror-could-not-find-or-load-spatialindex-c-64-dll

**Comment by behrisch** [comment]
closing for lack of feedback
