### ISSUE TITLE
custom color for busStop

### ISSUE THREAD

**Issue by rummel123** [eclipse/sumo#8280]
It would be nice to give `busStop` and `containerStop` a customized color for sumo-gui as:
```xml
<busStop id="stop_0" lane="lane_0" color="red">
```
instead of green for busStops and blue for containerStops.
It is also not possible to change the color in sumo-gui via View Settings. (#8282)

**Comment by rummel123** [comment]
with commit [https://github.com/eclipse/sumo/commit/6122418002ff7693582740f1203591b6f04abe71](https://github.com/eclipse/sumo/commit/6122418002ff7693582740f1203591b6f04abe71) custom color:
- [x] can be defined in `<busStop id="stop_0" color="red"/>` (or containerStop)
- [x] is used in visualization of sumo-gui

**Missing features:**
- [ ] is not used in visualization of netedit
- [ ] color cannot be changed in sumo-gui "View Settings"
- [ ] ...

**Comment by behrisch** [comment]
changing color from view settings is still open

**Comment by namdre** [comment]
In netedit, trainStops still use the busStop color

**Comment by palvarezlopez** [comment]
Fixed (For SUMO and NETEDIT)

**Comment by namdre** [comment]
The current settings are not stored and loaded from gui settings file
