### ISSUE TITLE
No lane changes in specific areas of the highway

### ISSUE THREAD

**Issue by sumo2021** [eclipse/sumo#8283]
Hi,

I am modelling a highway scenario. The track has multiple lanes which are seperated by a continuous line in specific areas of the track (No lane changes are allowed in these areas) while other areas of the track allow free lane changing. 
Therefore, I am trying to prevent the vehicles in my simulation from changing lanes in specific parts of the track. Is there an other way to achieve this than changing the mutiple lane road into several single lane roads?

Thanks for your help!

**Comment by namdre** [comment]
in the lastest development version you can set the lane attributes 'changeLeft' and 'changeRight' to set local lane change restrictions for some (or all) vehicle classes. See https://sumo.dlr.de/docs/Networks/PlainXML.html#lane-specific_definitions

**Comment by sumo2021** [comment]
Thanks for your answer.
I tried to fix my problem with the lane attributes 'changeLeft' and'changeRight'...
![Net_no_lane_changes](https://user-images.githubusercontent.com/77237297/109331908-b80bba00-785d-11eb-9eab-4f6123a2a0d6.jpg)
...but it did not solve it. Vehicles still change the lane (in this picture from -130.0.00_1 to -130.0.00_2) even if only vehicle class 'emergence' is allowed to do this.
![lane_Change_SendenOst](https://user-images.githubusercontent.com/77237297/109331927-bc37d780-785d-11eb-95f9-47036fbdf13b.jpg)

Did I do something wrong or is there an other way to prevent lane changings in specific parts of the track?

**Comment by namdre** [comment]
possibly you are using an older sumo version that doesn't have this feature. Did you download and run the version from here?
https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_development_version
