### ISSUE TITLE
Information about connection roads missing when transforming an Opendrive map

### ISSUE THREAD

**Issue by zhuhj-tery** [eclipse/sumo#8284]
Hi,

Thanks for the reply to issue #8269. I followed the guide and checked the internal edges carefully. There are some other problems:
1. The internal edges are not so accurate as normal edges (for example, the internal edge ":3000000_0_1" only has two shape points). I know it is possible to increase the accuracy of the normal edge when transforming an Opendrive map. Is it also possible to increase the accuracy of the internal edges automatically?
2. There is one connection missing (i.e. the connection from road 1057000 to road 1029000). One reason might be that road 1057000 is bidirectional, which might not be considered by the netconvert tool. Can sumo model the bidirectional edges?

Thanks!

**Comment by namdre** [comment]
1. You may increase the accuracy by setting netconvert option **--opendrive.internal-shapes** (by default, they use netconvert-generated shapes)
2. Sumo cannot model bidirectional roads directly at the moment (see #8287). 

Feel free to re-open for direct follow-up questions (no need to open a new ticket).
