### ISSUE TITLE
.dispatchTaxi() shows problems when redispatching near next stop

### ISSUE THREAD

**Issue by ArmelliniMG** [eclipse/sumo#8285]
If the route needs to be changed or extended when the vehicle is close to the next stop, the following warning is given:
`Could not add taxi stop for vehicle 'taxiA' to pickup 0. time=60.00 error=stop for vehicle 'taxiA' on lane 'C1C2_1' is too close to brake`
and the vehicle is rerouted but without completing the stop, resulting in route problems.

Given that the new route assigned, doesn't considered the first stop, maybe would be possible to conclude the stop before the assignment. So, if warning -> complete current stop + assign route.

Test scenario:
[Test_AssignWarning.zip](https://github.com/eclipse/sumo/files/6045831/Test_AssignWarning.zip)

**Comment by namdre** [comment]
The example shows a bug because the replacement stop is identical to the earlier stop and so the vehicle speed should allow stopping there.
