### ISSUE TITLE
The details of JUNCTION model

### ISSUE THREAD

**Issue by warm2018** [eclipse/sumo#8286]
Hi 
Rencently, I want to modfie the junction model because of some special usage. The first step is to know the junction rules in detail and I meet some confusions when I read the model documentation.

In the doc, you write:
_When approaching an intersection (an entry link), a vehicle computes how long it will occupy the intersection and then checks against all approaching vehicles in all foe links of its entry link. If the requested time slot is separated from all approaching foe 
time slots by a suitable safety gap the vehicle is allowed to pass the entry link and thus enter the intersection._

And I have several questions about these descriptions:
1. what's the method to calculate how long the vehicles will occupy the intersection? (occupy the the whole intersection is too long if intersection is big)
2. I guess that the coordination rules with foe links is similar with FCFS rules, but the safety gap, the gap point what?
    because the time slots have many time slot, but the time gap should be calculate by two time_slot [t_i - t_{i-1}], what are the t_i and t_{i-1}
3.Where can I locate the src code of this logic?
Thank you in advance!

**Comment by namdre** [comment]
1) the model assumes acceleration-to-maximum speed to compute time for passing an intersection. The code is at 
https://github.com/eclipse/sumo/blob/b9032b2f7c986e5b6cec06f9061e11178ab44024/src/microsim/MSVehicle.cpp#L2545-L2546
https://github.com/eclipse/sumo/blob/b9032b2f7c986e5b6cec06f9061e11178ab44024/src/microsim/MSLink.cpp#L476

> occupy the the whole intersection is too long if intersection is big

the description is not the whole picture but your problem statement is still correct. 
a) once a foe vehicle has entered the junction, the ego vehicle doesn't have to wait until it leaves the junction, instead it may enter into a car-following relationship while the foe is still on the junction (and thus may enter the junction early)
b) however, the reverse is currently not implemented: the ego vehicle may not enter a large junction early and let the foe vehicle enter into a car following relationship early. The unrealistic safety gaps from this are especially obvious when the vehicles are slow compared to the intersection size (bicycles).

2) I'm not sure I understand the question. The points at which trajectories intersect for each pair of movements are computed in https://github.com/eclipse/sumo/blob/b9032b2f7c986e5b6cec06f9061e11178ab44024/src/microsim/MSLink.cpp#L131 (this is used for 1a). A first-come-first-served logic only applies to junction type "alway_stop". For other junction types there are priority rules among the different movements.

3. see links above. The junction model is basically spread over MSVehicle and MSLink (right-of-way rules are pre-computed by netconvert though).
