### ISSUE TITLE
traci doesn't have 'traci.lane.getPendingVehicles'

### ISSUE THREAD

**Issue by 798283635** [eclipse/sumo#8291]

**Comment by 798283635** [comment]
Get Lane Variable: unsupported variable 0x94 specified

**Comment by namdre** [comment]
only supported in the latest development version: https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_development_version

**Comment by 798283635** [comment]
thank you

**Comment by 798283635** [comment]
> only supported in the latest development version: https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_development_version
thank you
