### ISSUE TITLE
traci.close()

### ISSUE THREAD

**Issue by subhagakannan** [eclipse/sumo#8292]
Dear all, 
I want to stop the simulation and close the connection in the middle of my simulation. I tried using traci.close(), but i find that it is not effective. I am not able to close the connection or stop the simulation. How can I achieve this?
Could anyone pls help me?? It would be of great help.
Thanks in advance.

**Comment by angelobanse** [comment]
By default the close command will wait until the sumo process really finishes. You can disable this by calling
```
traci.close(False)
```

https://sumo.dlr.de/docs/TraCI/Interfacing_TraCI_from_Python.html#first_steps

**Comment by namdre** [comment]
When running sumo-gui, the default is to wait for user confirmation before quiting. You can change this by setting option "--quit-on-end" in your traci.start options or .sumocfg.

**Comment by subhagakannan** [comment]
Thank you @angelobanse  and @namdre 
Actually I tried doing it. But the control is struck in the while loop and traci.close(False) is not working.
Here is the code:
![image](https://user-images.githubusercontent.com/70543709/109507038-99e0cc80-7a9e-11eb-9e7e-1668baccdbdf.png)
pls help me.

**Comment by namdre** [comment]
try closing the simulation after a specific time: 
```
if traci.simulation.getTime > x:
   traci.close()
   break
```
