### ISSUE TITLE
Adding getNeighbors to C++ TraCI or getting to a better workaround

### ISSUE THREAD

**Issue by fergian94** [eclipse/sumo#8293]
Hi all!

I'm developing a new driver model written in C++ and want to interface it to SUMO to better understand how it works.
Now, since I understood that only with TraCI is possible to launch sumo-gui to see what's happening, I embedded those libraries into my client code.
Now my problem: the driver model I'm developing needs to know the surrounding vehicles, and the only TraCI function that does so is getNeighbors.
Unfortunately this is one of those functions only available in TraCI for python, while I'm sticking with the (outdated?) C++ declination.

At this point I was thinking about two possibilities:
- adapt the already existing getNeighbors of libtraci (under src/libtraci/vehicle) to TraCIAPI::VehicleScope
- directly use libtraci, since many other unported functions might be needed in the future, and I might face other problem similar to this one.

For the latter case, if it a better solution, please let me know and I'll open a new issue asking how to include libtraci libraries and getting my client code working properly within sumo-gui.

For the first case I attach the code that should adapt to the getNeighbors function but it doesn' seem to work as expected:

```
std::vector<std::pair<std::string, double> >
TraCIAPI::VehicleScope::getNeighbors(const std::string& vehID, const int mode) {
    std::vector<std::pair<std::string, double> > neighs;
    tcpip::Storage content;
    content.writeUnsignedByte(libsumo::TYPE_UBYTE);
    content.writeUnsignedByte(mode);
    myParent.createCommand(libsumo::CMD_GET_VEHICLE_VARIABLE, libsumo::VAR_NEIGHBORS, vehID, &content);
    myParent.processGet(libsumo::CMD_GET_VEHICLE_VARIABLE, libsumo::TYPE_COMPOUND);
    // tcpip::Storage& ret = Dom::get(libsumo::VAR_NEIGHBORS, vehID, &content);
    const int items = myParent.myInput.readInt(); // components
    for (int i = 0; i < items; i++) {
        const std::string neighID = myParent.myInput.readString();
        neighs.emplace_back(neighID, myParent.myInput.readDouble());
    }
    return neighs;
}
```

As you can see, I substituted the `Dom::get` function with the typical two-step get query of TraCIAPI. The problem here is that, when I call the function with:

```
std::vector<std::pair<std::string, double> > neighbors = client.vehicle.getNeighbors(sumo_vehicles[0], 2);
std::cout << "Neighbors ahead/left for the first vehicle: " << neighbors.size() << "\n";
```
I get an empty vector, even though it should retrieve a vehicle which is in the left lane, ahead with a gap of about 3-4 mt.

Many thanks for the support!

**Comment by namdre** [comment]
Using libtraci directly would be preferable since we intend to phase out the old src/utils/traci client. Using this with sumo-gui should work directly by calling Simulation.start with 'sumo-gui' in the  cmd list.

**Comment by fergian94** [comment]
Great I managed to let it work, thanks to your brand new tutorial given in the issue: #8300

**Comment by behrisch** [comment]
Why did you reopen?

**Comment by fergian94** [comment]
I'm sorry I made a mistake and did not recognize that.
