### ISSUE TITLE
questions regarding self-defined lane-changing reasons

### ISSUE THREAD

**Issue by Mikemraz** [eclipse/sumo#8297]
First, thanks for building and maintaining such great simulation tool! I have a question about Traci's functionality. I am now exclusively using Traci to control vehicles in SUMO. I would like to record the reason of lane change behavior occurs each time. The lane change reasons are purely based on control logic I defined, which could be various. And I also need them to be generated the output file. I have looked into the documentation and only find traci.vehicle.getLaneChangeMode. This is not good enough as it only indicates the reason to be "traci". Is there a way to work around this?

Best,
Liming

**Comment by namdre** [comment]
In the latest development version, you can set vehicle parameter "lcReason" and this will be added to the `reason` attribute in **lanechange-output**.

**Comment by Mikemraz** [comment]
@namdre Hi Jakob, thanks for replying. What if I want this function to be more general, which means traci could also store the information of the behavior of vehicles that do not make lane changes, as well as enabling us to analyze their behavior in the output file? 
In other words, is it possible for us to store interested behavior in some kind of user-defined variables that could be accessed by traci and generated in the output file?

Thanks,
Liming

**Comment by namdre** [comment]
you can use function vehicle.setParameter (`setParameter(vehID, "lcReason", yourCustomReason`) and getParameter to store custom values. Some values are "magic" and have additional effects:
https://sumo.dlr.de/docs/TraCI/Vehicle_Value_Retrieval.html#device_and_lanechangemodel_parameter_retrieval_0x7e
https://sumo.dlr.de/docs/TraCI/Change_Vehicle_State.html#setting_device_and_lanechangemodel_parameters_0x7e

You can use options **--fcd-output** and **--fcd-output.params** to write custom values to xml output (https://sumo.dlr.de/docs/Simulation/Output/FCDOutput.html#further_options)

**Comment by Mikemraz** [comment]
It works! Thanks you! Highly appreciated it!
