### ISSUE TITLE
Issue with creating pedestrian crossings over one way street

### ISSUE THREAD

**Issue by guardiana** [eclipse/sumo#8298]
Hello,

we have a problem with creating a crossing for pedestrians over a one way street as shown in the picture. We get  "Warning: Discarding invalid crossing ':gneJ1_c0' at junction 'gneJ1' with edges [gneE2 gneE3] (no vehicle lanes to cross)" and the crossing is not created, even though there is a vehicle lane to cross. Are we doing something wrong?

Thank you very much in advance!
![error1](https://user-images.githubusercontent.com/21042529/109508620-b6820200-7aa8-11eb-8a10-619fea94353a.png)
![error2](https://user-images.githubusercontent.com/21042529/109508629-ba158900-7aa8-11eb-9747-97b3d757ddb5.png)

**Comment by namdre** [comment]
you need to select one of the roads (to be crossed) rather than booth of the foot paths.
