### ISSUE TITLE
How to use/include libtraci with C++

### ISSUE THREAD

**Issue by fergian94** [eclipse/sumo#8300]
Hi everyone!

I'm developing a C++ client and want to use/include libtraci. I'm a newbie to this and I was looking for some tutorials on how to do it. I cannot find'em.
Can anyone please explain me how to?

**Comment by namdre** [comment]
see https://sumo.dlr.de/docs/Libtraci.html#c

**Comment by fergian94** [comment]
Great that's exactly what I was looking for!
My problem was linking the wrong library object, now I understood that the library to add is bin/libtraci

Many thanks!

**Comment by SunTianzhHERE** [comment]
hello, everyone! I am facing the same problem? Where is the library of libtraci in the C++ client? How can I do it？

**Comment by palvarezlopez** [comment]
@SunTianzhHERE the library ist in your SUMO folder, in subfolder "bin". In Visual Studio, you need to put the SUMO Folder in your inlcude and lib paths

**Comment by SunTianzhHERE** [comment]
But an error occurs that  fatal error LNK1120. How can I deal with it?

**Comment by SunTianzhHERE** [comment]
I refered "D:\Sumo\bin" "D:\Sumo\include" "D:\Sumo\tools\lib“  . Are they correct?
