### ISSUE TITLE
Missing  traCI functions in C++

### ISSUE THREAD

**Issue by JaneyJin** [eclipse/sumo#8301]
Hello,

I'm using C++ TraCIAPI client library to retrieve simulation information from SUMO. I follow the instruction I check the person value retrieval website (https://sumo.dlr.de/docs/TraCI/Person_Value_Retrieval.html). There are several functions I cannot find in the C++ TraCI: _getWidth, getMinGap, getTaxiReservation_ . I know python got these method, but I need to use C++ run my code. Will these missing functions be added to the C++ TraCIAPI?

**Comment by namdre** [comment]
No. The client described in https://sumo.dlr.de/docs/TraCI/C%2B%2BTraCIAPI.html is deprecated in favour of the new libraci client which supports all these functions: https://sumo.dlr.de/docs/Libtraci.html
