### ISSUE TITLE
Can Netedit draw 3D roads?

### ISSUE THREAD

**Issue by gaofenxia** [eclipse/sumo#8306]
So far, when drawing roads, it is found that nodes are defined by X and Y coordinates, that is, 2D simulation. Can Netedit draw 3D roads?

**Comment by namdre** [comment]
Yes. In move-mode you can set the 'apply mouse movement to elevation checkbox' to input z-data. To visualize this, see https://sumo.dlr.de/docs/Networks/Elevation.html#visualizing_elevation_data

After selecting one or more edges, you can also use move-mode to shift the whole selection in z-direction

**Comment by angelobanse** [comment]
Yes. You can specify the elevation for each node. 

Look out in the Move-mode (Shortcut `M`) for the "Apply mouse movement to elevation" option:
![checkbox_elevation](https://user-images.githubusercontent.com/16121932/109683582-c7517700-7b7f-11eb-991e-cb57e4eb1b80.png)
Select it and drag your cursor up and down to adjust the elevation.

You can also select a node, in Inspect-mode (Shortcut `I`) and change its `pos` internal attribute to `x,y,z`.
e.g. -> `10,15,20` is x=10, y=15 and z=20
