### ISSUE TITLE
calibrator: unclear warning - no valid routes in calibrator

### ISSUE THREAD

**Issue by yunpangfloetteroed** [eclipse/sumo#8309]
The calibrator in SUMO sends the warning "no valid routes in calibrator" also when only speeds need to be calibrated. When reading this warning it is not clear if something wrong with the calibrator or the involved calibrators are only for speed calibration. 

When SUMO sends this warning, it is not known for SUMO which data type should be calibrated yet. Afterwards the calibration type will be known by parsing each calibrators.add.xml.

**Comment by namdre** [comment]
The warning "no valid routes in calibrator" is only triggered in the "execute" method of the calibrator after parsing is complete (and supposedly only if flow calibration is being done). 
Please provide example input for an invalid/unclear warning.

**Comment by yunpangfloetteroed** [comment]
Hi! I put an example under s:/Sumo/Bugreports/8309_unclear_warning; You are right in some cases. But, sometimes, some calibrators have no such warning in the beginning and then have this warning afterwards, eg. 728952330. In the directory, there is a file named 05sumoError_00-20.txt, where you can find this warning.

**Comment by namdre** [comment]
```
erdm_ja@ts-070167dl:/localdata2/debug/8309_unclear_warning/unclear_warning_2$ grep -n 728952330 calibrators.add.xml 
153:    <calibrator id="calibrator_728952330.67" lane="728952330.67_0" pos="0" freq="5" friendlyPos="x" output="calibrators.log.xml">
154:        <flow begin="600" end="900" vehsPerHour="522" speed="3.47515277778" vtype= "vtypedist" route="routedist_728952330.67" force="0.875" />
155:        <flow begin="900" end="1200" vehsPerHour="564" speed="3.46727777778" vtype= "vtypedist" route="routedist_728952330.67" force="1.375" />
6575:    <calibrator id="calibrator_728952330.50" lane="728952330.50_0" pos="0" freq="5" friendlyPos="x" output="calibrators.log.xml">
6576:        <flow begin="600" end="900" vehsPerHour="522" speed="3.47515277778" vtype= "vtypedist" route="routedist_728952330.50" force="0.875" />
6577:        <flow begin="900" end="1200" vehsPerHour="564" speed="3.46727777778" vtype= "vtypedist" route="routedist_728952330.50" force="1.375" />
7263:    <calibrator id="calibrator_728952330" lane="728952330_0" pos="0" freq="5" friendlyPos="x" output="calibrators.log.xml">
7264:        <flow begin="600" end="900" vehsPerHour="522" speed="3.47515277778" vtype= "vtypedist" route="routedist_728952330" force="0.875" />
7265:        <flow begin="900" end="1200" vehsPerHour="564" speed="3.46727777778" vtype= "vtypedist" route="routedist_728952330" force="1.375" />
```
All calibrators with '728952330' in their id define vehsPerHour. Do you have another example of a speed-only calibrator that generates a "no valid routes" warning?

**Comment by namdre** [comment]
On a closer look the "no valid route" warnings are created because the calibrator defines `route="routedist_728952330"` but `"routedist_728952330"` isn't defined anywhere in the loaded input.

**Comment by yunpangfloetteroed** [comment]
after the direct discussion the probelm is  that there is no corresponding route_distributions in the static.rou.xml. The waring reflects the situation properly. Such warining should be taken into serious consideration.
