### ISSUE TITLE
error: use of undeclared identifier

### ISSUE THREAD

**Issue by qichaow** [eclipse/sumo#8313]
When I try to build the latest SUMO on Mac, I received "error: use of undeclared identifier {XXX}" for many header files. One example is 
"{dir}/sumo/src/utils/router/SUMOAbstractRouter.h:316:17: error: use of undeclared identifier
      'ROUTER_DEBUG_COND'"

Is there a way to fix it?

**Comment by namdre** [comment]
should be fixed with 243177afbc4011880cc0ea0b0d1763b3755fabf1
