### ISSUE TITLE
launching sumo-gui from netedit uses the wrong zoom

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#8314]
working as expected with 1.8.0

also affects the reverse case

**Comment by namdre** [comment]
@angelobanse FYI: was broken in a5d3cce0e18d63a31ff9f00898 because the FXApp(name, vendor) initialization defines the fox-internal registry address and other parts of the code assume a different registry location.

**Comment by angelobanse** [comment]
thanks for the info, @namdre :+1:
