### ISSUE TITLE
SubscriptionFilter doesn't filter subscribed Context

### ISSUE THREAD

**Issue by fehnkera** [eclipse/sumo#8318]
Dear Community,

I want to implement a side sensor, that detects all vehicles in the near distance on the lane next to the ego car, in my simulation and therefore tried to use a context subscription, where I add a SubscriptionFilterLCManeuver. The code I use therefore is:

```
traci.vehicle.subscribeContext(vehicle_id, 0xa4, self.range)

traci.vehicle.addSubscriptionFilterLCManeuver(direction=-1, noOpposite=True, downstreamDist=(self.range / 3 * 2), upstreamDist=(self.range / 3))

results = traci.vehicle.getContextSubscriptionResults(self.vehicle.id)
```
 Where `self.range` is the sensor range of my vehicle, which shall be distributed 1/3 to the space in front of the ego vehicle and 2/3 to the space behind the vehicle.
 
When I ask for the ContextSubscriptionResults I get all IDs from vehicles around the ego vehicle indepentendly if they are in the range of the filter. What do I have to do to get just the vehicles in the range of the filter?

I hope anyone has worked with SubscriptionFilter before and can tell me what my problem is. I am looking forward for your answers

Kind Regards

Anselm Fehnker

P.S: I have attached the model and the traci log file in case that helps solving my problem.
[SubscriptionFilter.zip](https://github.com/eclipse/sumo/files/6083863/SubscriptionFilter.zip)

**Comment by namdre** [comment]
oops. wrong issue reference

**Comment by behrisch** [comment]
There are two problems with the scenario
 1. you cannot retrieve the filtered values directly after setting the filter, filters are only applied in the next step. I just clarifed the docs.
 2. downstream means in front and upstream means behind, you applied it the other way round
