### ISSUE TITLE
Retrieve route shape including internal edges

### ISSUE THREAD

**Issue by fergian94** [eclipse/sumo#8325]
Hi all.
I'm developing a motion planner, and wish to use SUMO to retrieve information about the scenario in the nearby of each vehicle.
One of my current concern is about converting the route assigned to each vehicle, into a full sequence of vertices.
Here I do have two issues:

1. With `getRoute` I don't really retrieve the full route (edge list), if in the middle there are internal edges. I need to know internal edges in advance to let my planner adapt the speed in a curve. So I can't currently figure a way of doing this.
2. When the vehicle is actually on the internal edge I'm able to read it, but as soon as I update my commands with `moveToXY` and `setSpeed`, based on the shape that I read and the deltas computed, I get a deviation of the position after the curve. As you can see from the images attached, the vehicle seems to follow the right lane edge instead of the centerline, which is described by the shape. Internally, my planner is following the right lane, with lateral delta=0, so it should exactly follow the shape of the entire route but it does not. Please notice that `speedMode=0` and `keepRoute=7`.

![2](https://user-images.githubusercontent.com/61280881/110145096-5c9b7800-7dd9-11eb-9f6b-c9ba7e09a297.png) ![3](https://user-images.githubusercontent.com/61280881/110145099-5d340e80-7dd9-11eb-98d7-c69cda5adf68.png) ![4](https://user-images.githubusercontent.com/61280881/110145100-5d340e80-7dd9-11eb-99ac-af6bb7865d3a.png)

EDIT: by reducing the simulation step from 0.05s to 0.01s I'm able to track accurately the lane position, is this a bug?

**Comment by namdre** [comment]
1) Currently, the only way to obtain the internal edges for a route is to look up the connections between pairs of "normal" successive edges (E1, E2) that appear in the route. 
- traci.lane.getLinks (may have to be called on all lanes of E1) until finding a connection that targets a lane of E2. internal id is in attribute "approachedInternal"
- sumolib.net.getEdge(E1).edge.getConnections() (same idea: find the connection that leads to E2 and then call getViaLaneID() on that connection
  - sumolib.net.edge.getConnections 

2) I don't think that this is a sumo bug. Here are things you can check:
- compare the vehicle position that you sent with moveToXY with the position obtained by vehicle.getPosition(). These always should match when keepRoute=7
- run your tests with higher step length but lower max-speed of the vehicle
- run your tests with bigger intersections (so the vehicle stays on the internal lane for multiple steps)
- run your scenario without traci and fcd-output. Then check if the sequence of x,y-positions in the output file match the assumptions of your own geometry computations

**Comment by namdre** [comment]
question 1 can be considered a duplicate of #1322

closing this due to lack of feedback on question 2
