### ISSUE TITLE
How to change the lanechange time dynamically

### ISSUE THREAD

**Issue by cloudfly519** [eclipse/sumo#8329]
Now I used the sublane model as
                <processing>
                       <lanechange.duration value="3"/>
                 </processing>
and I used the command traci.vehcle.changlane(vehID,duration=4).I find the duration value in this command is no effort.It took 3s for the vehicle to complete the lane change
I want to have different lane change time for different vehicles,rather than every car is 3s.
so what should I do

**Comment by namdre** [comment]
The duration parameter of changeLane() only defines how long a lane change should be attempted.
To set a custom duration you need to change vType parameter maxSpeedLat (default 1). If this is set to a custom value either in the xml input or via traci.vehicle.setMaxSpeedLat.
The duration is then computed as distance/maxSpeedLat
