### ISSUE TITLE
How can I equip SSM equipment to vehicles ?

### ISSUE THREAD

**Issue by sleepysea** [eclipse/sumo#8332]
I tried to add  `<device.ssm.probability 1>` to my sumocfg file like this:
`<?xml version="1.0" encoding="UTF-8"?>

<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/sumoConfiguration.xsd">
    
    <input>
        <additional-files value="vtype.xml"/>
        <net-file value="1.net.xml"/>
        <route-files value="demo.rou.xml"/>
    </input>

    <device.ssm.probability 1>
    
    <output>
        <netstate-dump value="netstate.xml" />
        <emission-output value="emissions.xml"/>
    </output>

    <time>
        <begin value="0"/>
        <end value="3600"/>
    </time>

    

</configuration>
`
But if I do that, the simulation cannnot run.
So what is the problem :(

**Comment by namdre** [comment]
use `<device.ssm.probability value="1"/>`

**Comment by sleepysea** [comment]
Thank you!
I will try.

**Comment by sleepysea** [comment]
> use `<device.ssm.probability value="1"/>`

Thank you!
I will try.
