### ISSUE TITLE
MARouter capping insertion capability?

### ISSUE THREAD

**Issue by Reivajar** [eclipse/sumo#8333]
Hi all,

I have been testing different implementation for high traffic scenarios with dynamic rerouting and marouter.

Under macroscopic assignment routes are modified in such a way that basically, only edges on the TAZ border are frequently used as origin or destination.

However, when it comes with a high rate of insertion, it seems it affect the capacity of the network to accept new vehicles, as only a restricted amount of edges are used, instead of the whole area.

Can it be a disadvantage of using macroscopic trafic assignment?

Thanks!

**Comment by namdre** [comment]
Yes, no, maybe:
- a limited number of insertion edges can have an impact on the maximum flow due to discretization artifacts (https://sumo.dlr.de/docs/Simulation/VehicleInsertion.html#effect_of_simulation_step-length)
- the routes computed by marouter are fastest paths between TAZ. In this way they minimize route lengths (in a way that may be considered unrealistic) and maximize throughput. This also reduces jamming within a TAZ in an overly optimistic manner, especially for TAZ that are directly adjacent.
- if your input exceeds flow capacity, then yes: you will have far fewer vehicles in your network compared to inserting them everywhere
- if the TAZ are not directly adjacent, the capacity for moving vehicles between these TAZ should not be affected

If you want your routes to start/end all over the TAZ you can first process the routes with od2trips (which assigns fixed random edges) and then call marouter on the trips.

**Comment by Reivajar** [comment]
Thanks.

Yes, I tried to increase the simulation-step and still, there were too many waiting vehicles.

However, I am curious about your very last suggestion:

> If you want your routes to start/end all over the TAZ you can first process the routes with od2trips (which assigns fixed random edges) and then call marouter on the trips.

I tried to do that as well:

OD_matrix_O-Format --> od2trips --> trips.rou.xml --> MARouter --> rou.xml

But, MArouter is still not preserving the origin-destinations. It crops all the routes to the edge of the corresponding TAZ. So, for instance, I have this trip into a trips.rou.xml file generated from od2trips:

`<trip id="14465" depart="0.15" from="237715992#11" to="237799300#1" fromTaz="08019172" toTaz="08019200" departLane="best" departPos="last" departSpeed="max"/>`

Then, after applying MARouter, it is tranformed into:

```
    <vehicle id="14465" depart="0.15" type="DEFAULT_VEHTYPE" fromTaz="08019172" toTaz="08019200" departLane="best" departPos="last" departSpeed="max">
        <routeDistribution>
            <route cost="257.90" probability="895.00000000" edges="4751951#0 4751951#1 551928442 360374686#0 360374686#1 360374686#2 360374686#3 360374686#4 440369837#0 440369837#1 440369837#2 440369837#3 440369837#4 440369837#5 440369837#6 440369837#7 440369837#8 440369837#9 440369837#10 440369837#11 547022186 490432365#0 490432365#1 490432365#2 490432365#3 46738594#0 46738594#1 46738594#2 46738594#3 46738594#4 46738594#5 46738594#6 46738594#7 294393944#0 294393944#1 294393944#2 294393944#3 294393944#4 294393944#5 294393944#6 294393944#7 294393944#8 294393944#9 294393944#10 554992977#0 554992977#1 114573199#0 114573199#1 114573199#2 114573199#3 114573195 554991023#0 554991023#1 114573197#0 114573197#1 114573197#2 114573197#3 114573197#4 114573197#5 114573197#6 114573197#7 114573197#8 114573197#9 554991022 490432362 554992981 490432359 490432363 54848611 54848612 96647295 490432358 519914557 543646803 39026718#0 39026718#1 39026718#2 39026718#3 39026718#4 251204566#0 251204566#1 37457949#0 37457949#1 37457950 37457952#0 37457952#1-AddedOnRampEdge 37457952#1 744147441 78845319 18522294 18522273#0 18522273#0-AddedOffRampEdge 34303608"/>
          </routeDistribution>
</vehicle>
```

So, maybe am I missing one of the options in MARouter for preserving origin and destination in routes?

Thanks!

**Comment by namdre** [comment]
I forgot that I always applied the workaround described in #8343 to make this work. If you grab the latest development version (updated download **tomorrow** at https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_development_version) you can use a new option for this.

**Comment by Reivajar** [comment]
Thank you so much for adding the new option to marouter.

However, I bet that I am missing something in that way of dealing with trips generated from od2trips (to be completely precise, I am using a rou file from applying duarouter for merging a bunch of trip.rou.xml files generated by od2trips.

I removed the fromTaz and toTaz tags from the  routes XML file, and when I input it into marouter it complaints:

![image](https://user-images.githubusercontent.com/9416202/110829611-9e746480-8298-11eb-9e60-f869c8eba83a.png)

If I remove the TAZ file, it gives the same error.

![image](https://user-images.githubusercontent.com/9416202/110829409-60774080-8298-11eb-8782-a77afde4a83c.png)

And using marouter without any TAZ file but with a route file with fromTaz and toTaz tags does not work either. 

I may wait for the release of the new dev version, but anyhow, is there anything that I am missing from the workaround that you suggested?

Best.

**Comment by namdre** [comment]
marouter currently does not support duarouter output with `<vehicle>` elements (and without fromTaz, toTaz).
If you want to process multiple trip files, you can pass them as a comma separated list to marouter.
If you first want to merge them with duarouter you must add option **--write-trips**  and pass the generated trip elements to marouter (with our without fromTaz,toTaz).

**Comment by Reivajar** [comment]
Thank you so much for the whole update. i really appreciate it. As well, I have seen you have added a tool for editing attributes on XML files. I don´t need my script anymore :D

Anyway, now it is working and the routes are preserved. I am compiling on Linux, but I bet it will be working like on Windows.

A linked question to MARouter though: **is the --scale option working for MARouter?** Because it is generating the same output independently on the scale value provided.

**Comment by namdre** [comment]
> A linked question to MARouter though: **is the --scale option working for MARouter?** Because it is generating the same output independently on the scale value provided.

see #8352
