### ISSUE TITLE
Bug in parking area rerouters with startPos="0"

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#8338]
if startPos="0" or endPos="0", then vehicle generates the following warnings:

Warning: Vehicle '100153985_100093056_434_0' performs emergency stop at the end of lane '84488280#4_0' because there is no connection to the next edge (decel=-2.00, offset=0.03), time=1:07:26:17.
Warning: Vehicle '100153985_100093056_434_0' performs emergency stop at the end of lane '84488280#4_0' because there is no connection to the next edge (decel=0.00, offset=0.09), time=1:07:26:18.
Warning: Vehicle '100213617_100126164_457_0' performs emergency stop at the end of lane '206391414#0_0' because there is no connection to the next edge (decel=-0.23, offset=0.00), time=1:07:45:36.
Warning: Vehicle '100083748_100053032_468_0' performs emergency stop at the end of lane '-206391414#0_0' because there is no connection to the next edge (decel=-0.60, offset=0.00), time=1:07:56:42.
Warning: Vehicle '100022457_100015087_506_0' performs emergency stop at the end of lane '23207367#0_0' because there is no connection to the next edge (decel=-0.80, offset=0.04), time=1:08:28:38.
Warning: Vehicle '100022457_100015087_506_0' performs emergency stop at the end of lane '23207367#0_0' because there is no connection to the next edge (decel=0.00, offset=0.06), time=1:08:28:39.
Warning: Invalid departPos 14.30 given for vehicle '100153985_100093056_434_0'. Inserting at lane end instead.
Warning: Invalid departPos 14.30 given for vehicle '100153985_100093056_434_0'. Inserting at lane end instead.
Warning: Invalid departPos 14.30 given for vehicle '100153985_100093056_434_0'. Inserting at lane end instead.
Warning: Invalid departPos 14.30 given for vehicle '100153985_100093056_434_0'. Inserting at lane end instead.
Warning: Vehicle '100031461_100020536_600_0' performs emergency stop at the end of lane '5134723#0_0' because there is no connection to the next edge (decel=-0.15, offset=0.00), time=1:10:03:32.
Warning: Vehicle '100046864_100030020_605_0' performs emergency stop at the end of lane '-27060186#2_0' because there is no connection to the next edge (decel=-1.22, offset=0.00), time=1:10:10:03.
Warning: Vehicle '100046864_100030020_605_0' performs emergency stop at the end of lane '-27060186#2_0' because there is no connection to the next edge (decel=0.00, offset=0.00), time=1:10:10:04.
Warning: Vehicle '100084126_100053302_645_0' performs emergency stop at the end of lane '512158816#0_0' because there is no connection to the next edge (decel=-3.46, offset=0.01), time=1:10:40:43.
Warning: Vehicle '100084126_100053302_645_0' performs emergency stop at the end of lane '512158816#0_0' because there is no connection to the next edge (decel=0.00, offset=0.03), time=1:10:40:44.
Warning: Vehicle '100038170_100024625_647_0' performs emergency stop at the end of lane '321714431#0_0' because there is no connection to the next edge (decel=-1.30, offset=0.03), time=1:10:49:00

![bug](https://user-images.githubusercontent.com/8238561/110625316-8ec52500-819f-11eb-8429-4471b6f87f53.png)

**Comment by namdre** [comment]
@palvarezlopez  can you push a test that is small enough for inclusion in our test suite?
