### ISSUE TITLE
Rerouter does not work

### ISSUE THREAD

**Issue by reihanehk** [eclipse/sumo#8355]
I use Siouxfalls network for simulation, and in run-time, I want to close the edge from node 19 to node 17 (which is named 19to17).
To do this, I use additional file like this:

    <rerouter id="rerout1" edges="19to17" probability="1.0">
           <interval begin="300" end="1500">
               <closingReroute id="19to17"/>
           </interval>
     </rerouter>

This rerouter does not make any change in vehicle movements and all vehicles used to pass 19to17, again pass it, but this time with just a warning.
Next time, I add the following line after closingRoute to show the other routes that they can choose:

    <destProbReroute id="19to15;15to10;10to17"/>

I have the warning for ';', so I separet it in three lines:

    <destProbReroute id="19to15"/> 
    <destProbReroute id="15to10"/>
    <destProbReroute id="10to17"/>

And again no change in the output results!

So, How does the rerouter work?\

Thanks in advance

**Comment by namdre** [comment]
For the record: rerouter attribute 'edges' defines the location where the route changes and should lie ahead of the closed edge.

Please do not double-post your questions to the mailing list *and* the issue tracker.
