### ISSUE TITLE
Read the collisions at every time step.

### ISSUE THREAD

**Issue by Izzatbrg** [eclipse/sumo#8357]
is there any way to write the collisions at every time step to a file (txt or XML)? I did `--collision-output <FILE>` but it writes the collisions after the end of the simulation. I'm asking because I'm using sumo with Matlab and the library(TraCI4Matlab) doesn't support the (getCollisions) and I need to know the collider and victim when the collision is happening. can you please recommend a solution? is there a possibility to use python to get this info from the runing simulation  or isn't possible
Thanks a lot

**Comment by namdre** [comment]
traci4matlab supports the (less detailed) method simulation.getCollidingVehiclesIDList which you can call in every step.

If you use the latest development version of sumo (https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_development_version) you can also use the python client method simulation.getCollisions() to get a lot of details for individual collisions in every step.
