### ISSUE TITLE
Use time in hour format in sumo config file

### ISSUE THREAD

**Issue by amiradavoudi** [eclipse/sumo#8368]
Hello,

Is it possible to use time in hour format in Sumo config file:
By 1 and 2 values, I mean from 1 am to 2 am (in hour not in second)
```
		<time>
			<begin value="1"/>
			<end value="2"/>
		</time>
```

Thank you.
Best,
Amirhossein Adavoudi

**Comment by namdre** [comment]
yes. You can use `<begin value="1:0:0"/>`.  See https://sumo.dlr.de/docs/Basics/Using_the_Command_Line_Applications.html#time_values

**Comment by amiradavoudi** [comment]
> yes. You can use `<begin value="1:0:0"/>`. See https://sumo.dlr.de/docs/Basics/Using_the_Command_Line_Applications.html#time_values

Thank you very much.
