### ISSUE TITLE
Generating traffic for several days

### ISSUE THREAD

**Issue by amiradavoudi** [eclipse/sumo#8369]
Hello,

I want to use the randomTrips.py script to generate traffic for all days of a month. The only possible solution, I think, is to call the randomTrips.py script for each day of the month, with different parameters (for -b and -e). Am I right? For example,
Day1: -b 1 -e 20000
Day2: -b 100 -e 30010
....
Day30: -b 400 -e 35000

Should I add a separate sumo config file for each individual day as the beginning time and the end time for each day is different?
I think if I use only one sumo config file for all the days, I would have to adjust the end value=/> parameters in a way that covers all the days' time, and it will have a negative impact on the simulation time. Am I right?

Should I necessarily use the time in seconds? Is it possible to use time in hour format for randomTrips.py?

Thank you in advance for your help.
Best,
Amirhossein Adavoudi

**Comment by namdre** [comment]
there is no harm in setting -b before the first traffic enters (an empty network can be simulated very effciently).
Also, you don't need to set an end time in your sumocfg and can just simulation until all traffic has left the simulation.
randomTrips.py allows human readable time (HH:MM:SS) for options begin and end.

**Comment by amiradavoudi** [comment]
> there is no harm in setting -b before the first traffic enters (an empty network can be simulated very effciently).
> Also, you don't need to set an end time in your sumocfg and can just simulation until all traffic has left the simulation.
> randomTrips.py allows human readable time (HH:MM:SS) for options begin and end.

@namdre: Thank you very much for your helpful information. Would you please explain to me how I can generate traffic for each individual day of the month?  Should I use the randomTrips.py script repeatedly for each day?

**Comment by namdre** [comment]
Using the script repeatedly for each day could work. It really depends on whether you need any kind of additional continuity (i.e. each car starts from the same origin and only varies destination).

**Comment by amiradavoudi** [comment]
> Using the script repeatedly for each day could work. It really depends on whether you need any kind of additional continuity (i.e. each car starts from the same origin and only varies destination).

Thank you very much for your helpful information.
