### ISSUE TITLE
nodes and edges disappear when shaking selection in Move mode

### ISSUE THREAD

**Issue by angelobanse** [eclipse/sumo#8372]
Some nodes and edges must be selected. Then, in the `Move mode` if you click on a node and shake the entire selection several times, all items (except the node on which was clicked) will disappear.

![bug](https://user-images.githubusercontent.com/16121932/111452693-12888f80-8713-11eb-9d27-3379a3d8a36a.gif)

**Comment by palvarezlopez** [comment]
https://github.com/eclipse/sumo/commit/1a8ba5636b3896e8085717edd795e7f4cd0c1f27
