### ISSUE TITLE
Merge "Windows CMake" and "Windows Build" pages

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#8376]
https://sumo.dlr.de/docs/Installing/Windows_CMake.html

https://sumo.dlr.de/docs/Installing/Windows_Build.html

- Only Cmake Build (due SUMO doesn't have a VS Solution)
- Reference SUMOLibraries and (https://sumo.dlr.de/docs/Installing/Windows_Libraries.html)
- Screenshot for Clang
- Merge both Troubleshooting

**Comment by palvarezlopez** [comment]
@behrisch are you ok with this?

**Comment by behrisch** [comment]
I think the Windows_Build page is slightly better but yes, I am fine with merging. Can mkdocs generate a version with small screenshots which only enlarge on clicking?

**Comment by angelobanse** [comment]
> 
> 
> I think the Windows_Build page is slightly better but yes, I am fine with merging. Can mkdocs generate a version with small screenshots which only enlarge on clicking?

See #8476
