### ISSUE TITLE
Get netconvert.exe source code

### ISSUE THREAD

**Issue by 91MrZhang** [eclipse/sumo#8382]
Hi team~
netconvert.exe This tool is really easy to use. And It's wonderful！

In my project, it also will include map conversion, such as OSM, opendrive, geojson

Therefore, If we can have this part of the code.it will be very effective for us to learn. 
Thank you very much

BR

**Comment by behrisch** [comment]
You are in the right place, just click on the code link above or clone the repo. The code for netconvert is mainly in src/netimport src/netbuild and src/netwrite. You might even add your own network format as a new output format (see netwrite) and add a pull request to have it in the sumo mainline.

**Comment by namdre** [comment]
netconvert can already convert to opendrive and geojson: https://sumo.dlr.de/docs/netconvert.html#export
