### ISSUE TITLE
Connection reset using TraCI

### ISSUE THREAD

**Issue by JustinMue** [eclipse/sumo#8384]
So I can run simple simulations of up to 600 steps in TraCI but as I have for example a simulation of up to 1800 steps, at some point the simulation (not always on the same step) crashes due to (probably) connection loss to the sumo server. Matlab as the TraCI user tells me then:

Java exception occurred:
java.net.SocketException: Connection reset

at java.net.SocketInputStream.read(SocketInputStream.java:210)

	at java.net.SocketInputStream.read(SocketInputStream.java:141)

	at java.net.SocketInputStream.read(SocketInputStream.java:224)

	at java.io.DataInputStream.readInt(DataInputStream.java:387)

Java should be on the latest update...
The simulation itself goes on for maybe half an hour, because every step has to be computed by some algorithm. So maybe the whole simulation time itself is causing connection issues?
This topic has been here already but closed on #6248, hopefully someone can help?
Thanks
![Matlab_errorCode](https://user-images.githubusercontent.com/80890452/111613684-0f5ad580-87df-11eb-9f55-3cacda5e2834.PNG)

**Comment by behrisch** [comment]
Can you share your scenario? Also please add information about the SUMO / TraaS version you are using (assuming you are using TraaS).

**Comment by JustinMue** [comment]
I use TraCI in a matlab script to intervene into a simulation of a small net, in which to reproduce a real traffic state. 
In order to validate the model, I try to simulate the traffic state for half an hour. Less simulation time works just fine, but after some point of simulation time this mentioned error appears.

I am not using TraaS, just simply TraCI on matlab. The sumo version is 1.7.0 and the traciVersion is '20'.

**Comment by behrisch** [comment]
So you are using [traci4matlab ](https://github.com/pipeacosta/traci4matlab) or your own traci implementation?

**Comment by JustinMue** [comment]
I am using traci4matlab, yes

**Comment by behrisch** [comment]
Then please report there: https://github.com/pipeacosta/traci4matlab/issues
