### ISSUE TITLE
unexpected behavior when calling traci.simulation.subscribeContext

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#8388]
Helper::findObjectShape does not set a shape and due to the way the box boundary is initialized, no value is ever returned.

solution ideas
- issue a warning/exception when trying this subscription
- use the network boundary and return everything regardless of subscription range

**Comment by behrisch** [comment]
I'd prefer the warning / exception path.

**Comment by behrisch** [comment]
preferred solution: give a semantic to the call as above but throw excpetions for domains where subscribeContext is really not applicable (meandata, ...)
