### ISSUE TITLE
Convert MATSim scenario to SUMO? 

### ISSUE THREAD

**Issue by HawkTom** [eclipse/sumo#8392]
Hello,

I want to ask if it is possible to transfer the scenario generated by MATSim to SUMO.  

As you know, it is hard to obtain the real scenario data for the simulation, but the MATSim could simulate all agents in the scenario and generate a scenario in which each agent obtains a good score.  So, if we can convert this scenario to SUMO, it will be very easy to get more realistic scenarios. 

Best,
Hao

**Comment by behrisch** [comment]
You can convert matsim networks to SUMO networks using `netconvert --matsim`and plans using [tools/import/matsim_importPlans.py](https://sumo.dlr.de/userdoc/Tools/Import/MATSim.html#matsim_importplanspy)
