### ISSUE TITLE
Empty edges attr. in MARouter output

### ISSUE THREAD

**Issue by Reivajar** [eclipse/sumo#8394]
Hi!

I have checked that sometimes MARouter generates empty route probabilities. The pattern is always a router distribution with 0.9 probability with correct list of edges, and another one with 0.1 probability with no edges. It makes SUMO crash. I can remove manually them as they are few, but I was just curious if it was an expected bug in MARouter or so.

`    <vehicle id="CORtoCOR171734" depart="35512.53" type="DEFAULT_VEHTYPE" fromTaz="553587567" toTaz="569435706#0" departLane="best" departPos="last" departSpeed="max">

        <routeDistribution>

            <route cost="356.53" probability="0.90000000" edges="553587567 912446185 35163009#2 251742369#0 34054316 360830951#0 519563659 544991392 34054318#0 812545735 34054320#1 542495686#0 54847779 49581770#3 550280511 288000443#1 288000443#2 34054323 550280510#0 309254651 664147081 34054326#0 34054326#2 449606869#0 862197871#0 449751440 129169446#0 449751444#0 32450852#0 24793131#0 145560650#0 145560650#1 569435706#0"/>

            <route cost="0.00" probability="0.10000000" edges=""/>

        </routeDistribution>

    </vehicle>`

Thanks.

**Comment by namdre** [comment]
Can you provide example inputs (preferably small) for this?

**Comment by Reivajar** [comment]
Sure. Let me check if I can isolate these trips somehow. The inputs are somehow large...

**Comment by behrisch** [comment]
Closing for lack of feedback. Please reopen if problems persist.
