### ISSUE TITLE
Electrical vehicle 

### ISSUE THREAD

**Issue by karutthappandi** [eclipse/sumo#8399]
when we put a command .  it will return error
python randomTrips.py --trip-attributes="has.battery.device=\"true\" maximumBatteryCapacity=\"2000\" maximumPower=\"1000\" constantPowerIntake=\"100\" actualBatteryCapacity=\"500\" " --vehicle-class evehicle -n madurai.net.xml -r madurai.rou.xml --device-battery-probability 1 -e 10 -l  
Usage: randomTrips.py [options]

randomTrips.py: error: no such option: --device-battery-probability

**Comment by behrisch** [comment]
The name of the option is `--device.battery.probability`.

**Comment by namdre** [comment]
actually, this option is to be set when calling sumo, not when calling randomTrips.py! Also, you cannot set those trip attributes since the given values must be given in another style (with `<param>`) which is not supported by randomTrips.

Instead you can set --trip-attributes=' type="myType"' and then add an additional file to your simulation which defines ]

```<vType id="myType">
         <param key="maximumBatteryCapacity" value="2000"/>
         ....
   </vType>
```

**Comment by karutthappandi** [comment]
thank you for your answer behrisch and namdre . behrisch sir where did the device.battery.probability  option is used . can you help us sir

**Comment by behrisch** [comment]
After the call to randomTrips.py you probably want to call sumo or sumo-gui with something like `sumo -n myNet.net.xml -r routes.rou.xml` You can add the the battery option tot his call.

**Comment by karutthappandi** [comment]
thank you sir .traci.exceptions.TraCIException: chargingStation 'chargingStation_0' for vehicle '1' on lane 'e6_1' is not downstream the current route. this error is occur when we using the   
 traci.vehicle.setChargingStationStop( "1","chargingStation_0",duration=-1073741824.0, until=-1073741824.0,flags=0)
        if(traci.vehicle.isStopped("1")):
             traci.vehicle.resume("1") can you help us sir

**Comment by karutthappandi** [comment]
thank you sir .traci.exceptions.TraCIException: chargingStation 'chargingStation_0' for vehicle '1' on lane 'e6_1' is not downstream the current route. this error is occur when we using the   
 traci.vehicle.setChargingStationStop( "1","chargingStation_0",duration=-1073741824.0, until=-1073741824.0,flags=0)
        if(traci.vehicle.isStopped("1")):
             traci.vehicle.resume("1") can you help us sir

**Comment by behrisch** [comment]
It probably is as the error message says. The lane e6_1 (or rather the edge "e6") is not part of the route of vehicle "1".  Lets continue this on the mailing list, see https://www.eclipse.org/sumo/contact/
