### ISSUE TITLE
Collision between bikes and peds

### ISSUE THREAD

**Issue by yunpangfloetteroed** [eclipse/sumo#8403]
It seems that they occur when peds walk in the opposite direction on the road. 

I tried to cut the network, only including the collision location and the edges used by the involved bike and ped. But (1) I needed to re-define the turning connections on the ped/bike paths after cutting and saving network with netedit; (2) after doing that, additional warning/ error related to walkingArea/disconnected walk appeared, although no other changes were made in the network.

**Comment by yunpangfloetteroed** [comment]
Both versions with the cut network and the original network locate at S:\Sumo\Bugreports\8403_ped_bike_collision. Some collision warnings are listed below.
Warning: Vehicle 'bike2855' collision with person 'ped4884', lane='30407720#1_0', gap=-0.04, time=29044.80 stage=move.
Warning: Vehicle 'bike2875' collision with person 'ped4878', lane='2535745#11_0', gap=-0.07, time=29275.60 stage=move.
Warning: Vehicle 'bike2900' collision with person 'ped4860', lane='2535745#11_0', gap=-0.11, time=29513.40 stage=move.

**Comment by yunpangfloetteroed** [comment]
@namdre: it is the case I talked with you one week before. It would be great if you could have a look on it!

**Comment by namdre** [comment]
problem occurs because option **--pedestrian.striping.stripe-width** is set to a lower value than the pedestrian width. (0.3 < 0.48). 
This is not guaranteed to be safe on shared lanes. (the model assumes that the pedestrian can fit into a  single strip when walking in it's center). I'll add a warning but you are advise to change the stripe-width. (The stripe-width doesn't have to match the lateral resolution of the sublane model).

**Comment by yunpangfloetteroed** [comment]
Aha, OK, thanks!

**Comment by yunpangfloetteroed** [comment]
I adjusted the setting value from 0.3 to 0.48, and ran the simulation with re-generated traffic demand. I got then the following  collision warning. 
                      Warning: Collision of person 'ped4936' and person 'ped4922', lane='-405338801#1_0', time=29171.50.

The related files are under S:\Sumo\Bugreports\8403_ped_bike_collision\collision_peds

For better tracing the issue I reopen this ticket.

**Comment by namdre** [comment]
looks like a numerical issue with stripe-width = pedWidth. When setting strip-width to 0.481 the collision does not occur. I'll change the warning to include this case.

**Comment by behrisch** [comment]
maybe also adapt documentation on pedestrian stripe width

**Comment by yunpangfloetteroed** [comment]
According to the discussions in this ticket, I added more info in the sumo wiki. A ticket for the issue that a ped jumps out of the way of a bike is open (#8419).
