### ISSUE TITLE
TraCI: Clear vehicles waiting for insertion into the network.

### ISSUE THREAD

**Issue by philippwulff** [eclipse/sumo#8407]
I want to get the the vehicles which are waiting for insertion in my network and remove them before they are inserted.

I found `simulation.clearPending()` and `simulation.getPendingVehicles()` in the docs [here](https://sumo.dlr.de/pydoc/traci._simulation.html)

However calling `traci.simulation.getPendingVehicles()`

causes this error: `{AttributeError}'SimulationDomain' object has no attribute 'getPendingVehicles'`

and calling `traci.simulation.clearPending()` does not throw an error, but I also does not clear the vehicles waiting for insertion.

Edit: I called `simulationStep()` before `clearPending()` and now it works, but I still get the error for the first command.

**Comment by namdre** [comment]
getPendingVehicles is only available in the latest development version: https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_development_version
