### ISSUE TITLE
dfrouter does not work for nets with walking areas

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#8408]
It returns routes ending in walking areas which sumo cannot use

**Comment by namdre** [comment]
is this a duplidate of #5698 or are you trying to generated pedestrian routes?

**Comment by behrisch** [comment]
Yes, in a sense it is a special case (fixing #5698 would probably fix this one as well) but the results file also contains routes ending in walking areas and I suppose this also happens if you have a network where  all edges allow cars.
