### ISSUE TITLE
TraCI: Exception when adding vehicles after loadState; {TraCIException}Invalid type 'DEFAULT_VEHTYPE' for vehicle '65' 

### ISSUE THREAD

**Issue by philippwulff** [eclipse/sumo#8410]
I saved the simulation state at the beginning of my simulation with `traci.simulation.saveState("path/to/file")` and then after the simulation has run for a specified number of steps, I reset my simulation with `traci.simulation.loadState("path/to/file")`.

In between I manually insert my vehicles with `traci.vehicle.add("route_id", "veh_id")` and this works until I reset my simulation. After that, the `add` command raises this exception

`{TraCIException}Invalid type 'DEFAULT_VEHTYPE' for vehicle '65'.`

Is this a bug or why does it happen? I add the same vehicles to the simulation after every reset, if this is important.

Edit: When I call `self.traci_api.vehicle.add("200", "!65", typeID="passenger")`, I get this error 
`{TraCIException}Invalid type 'passenger' for vehicle '200'.`

**Comment by namdre** [comment]
It's a bug.
as a workaround, define `<vType id="default"/> in your simulation input and then call `traci.veihcle.add("route_id", "veh_id", typeID="default")

**Comment by philippwulff** [comment]
Thanks for your quick reply. The workaround is working right now (I am loading a .rou.xml file which includes the vType you specified). Is is possible to also add this vType through TraCI? I only found `traci.vehicletype.copy()` which does not work, as I have no other vTypes to copy from...

**Comment by namdre** [comment]
No. adding types via traci is not yet supported.
