### ISSUE TITLE
geometry-remove corrupts traffic light

### ISSUE THREAD

**Issue by ambuehll** [eclipse/sumo#8413]
Removing geometry while at the same time "keeping edges" in an input file, results in intersections being modified in type:
junction:cluster_2500446880_2500446883_26807332_3653729587_5038202989

original input:

![image](https://user-images.githubusercontent.com/48930860/112321399-3ec28400-8cb0-11eb-822d-9eb785629ba0.png)

output: 
![image](https://user-images.githubusercontent.com/48930860/112321318-2e120e00-8cb0-11eb-9ce9-3e340514a568.png)

netconvert -s ZRH_sumo_raw.net.xml --keep-edges.input-file edges_valid_strongcon.txt -o ZRH_strong.net.xml --proj.plain-geo true --geometry.remove **true** --plain-output-prefix ZRH -v true --keep-edges.components 1

setting geometry.remove false resolves the issue. 
[files](https://drive.google.com/drive/folders/1i3wkI6zJ9oxCLQ18PJ5BKyes3UHaSNHb?usp=sharing)

**Comment by behrisch** [comment]
I think we removed a similar bug in #8219 Which sumo version is this?

**Comment by ambuehll** [comment]
Just tested it again with the newest version v1_8_0+1858-7a5638250d
and the problem still persists.
Thanks!

**Comment by namdre** [comment]
I think the issue is unrelated to keep-edges:

```
netconvert -s ZRH_sumo_raw.net.xml --keep-edges.input-file edges_valid_strongcon.txt -o **2.net.xml** --proj.plain-geo true --geometry.remove **false** --plain-output-prefix ZRH -v true --keep-edges.components 1
netconvert -s 2.net.xml -R -o 3.net.xml
```
When running the above, then the traffic light still is correct in 2.net.xml but broken in 3.net.xml

**Comment by namdre** [comment]
Thanks for the report. I broke this recently when adding a cache to speed up the import (#8270)
