### ISSUE TITLE
enable vehroute-output.exit-times for walks

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#8415]

**Comment by rummel123** [comment]
Update of the documentation is still missing:
[https://sumo.dlr.de/docs/Simulation/Output/VehRoutes.html](https://sumo.dlr.de/docs/Simulation/Output/VehRoutes.html)

**Comment by rummel123** [comment]
An arrival time for the rides would be nice, e.g. an additional value "<ride from=... to=... **until=...**".

**Comment by namdre** [comment]
@rummel123 kümmerst du dich um die Doku des vehroute-person output?
