### ISSUE TITLE
edit-mode toggle does not work properly

### ISSUE THREAD

**Issue by yunpangfloetteroed** [eclipse/sumo#8416]
When the toggle option is activiated, the respective connections are still not be automatically selected when selecting edges and intersections. I am using the netedit compiled this morning. (v1_8_0+ 1819-2015b27388)

![activated_toggle](https://user-images.githubusercontent.com/26454969/112453087-9b2cae80-8d57-11eb-981b-c724111607d4.png)

**Comment by yunpangfloetteroed** [comment]
note: it happens when selecting objects

**Comment by namdre** [comment]
to toggle only applies when doing a rectangle selection. Did you maybe use single clicks?

**Comment by yunpangfloetteroed** [comment]
Yes, I expected that it works also when using single clicks at intersections. could it be possible?

**Comment by namdre** [comment]
No. Selecting junctions by default when single-licking on an edge would violate user expectation in other use cases.
Just hold shift briefly (a mini rectangle).
