### ISSUE TITLE
TraCI: loadState() causes: Error! Vehicle '3' is not known. 

### ISSUE THREAD

**Issue by philippwulff** [eclipse/sumo#8426]
I am loading the state of my empty simulation (to remove all vehicles) with `traci.simulation.loadState("path/to/file")`. After this, I redistribute the vehicles (which have the same ids as before) with `traci.vehicle.add()` 

However, calling `loadState()` and `simulationStep()` throws:

```
Error! Vehicle '3' is not known.
Error! Vehicle '3' is not known.
Error! Vehicle '3' is not known.
Error! Vehicle '3' is not known.
Error! Vehicle '3' is not known.
Error! Vehicle '3' is not known.
```

The simulation state file looks like this:

```
<!-- generated on Thu 25 Mar 2021 05:23:24 PM CET by Eclipse SUMO GUI Version v1_8_0+1048-d0b9cb4851
<configuration>
            ...
</configuration>
-->

<snapshot xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/state_file.xsd" version="v1_8_0+1048-d0b9cb4851" time="0.00" type="micro">
    <delay number="0" begin="0" end="0" depart="0.00" time="0.00"/>
    <vType id="default"/>
</snapshot>
```

It does not quit the SUMO-simulation but looks ugly. What is causing this error or is it a bug?

**Comment by namdre** [comment]
Yep. Looks like a bug. Please provide input files for reproducing the problem.

**Comment by philippwulff** [comment]
I finally managed to reproduce the issue in a small runnable example and attached the files to the end of this comment. I also just noticed the error log in SUMO displays the following command code and that the mentioned vehicle id is the one I subscribed to for the past episode (from after the last reset until the current reset):

```
Error: Answered with error to command 0xa4: Vehicle '1' is not known.
Error: Answered with error to command 0xa4: Vehicle '1' is not known.
Error: Answered with error to command 0xa4: Vehicle '1' is not known.
Error: Answered with error to command 0xa4: Vehicle '1' is not known.
Error: Answered with error to command 0xa4: Vehicle '1' is not known.
Error: Answered with error to command 0xa4: Vehicle '1' is not known.
```

The `constants.py` file in traci tells me `0xa4` has something to do with gui objects...:

```
#  select/deselect object (gui)
VAR_SELECT = 0xa4
```

[traci_bug.zip](https://github.com/eclipse/sumo/files/6211170/traci_bug.zip)

**Comment by namdre** [comment]
Thanks for the example scenario!
Note, that you can also use sumolib for convenient parsing: https://sumo.dlr.de/docs/Tools/Sumolib.html#parse_vehicles_and_their_route_edges_in_a_route_file

**Comment by philippwulff** [comment]
Thanks, I will have a look at sumolib!

**Comment by ShenZC25** [comment]
Hello, I encountered the same BUG in the process of using SUMO. I'm using SUMO for reinforcemet learning. In the first epoch, I used "traci.simulationStep ()" without any abnormality. In the "RESET" phase of each subsequent epoch, I removed all the vehicles first, and then used "traci.simulationStep ()". In principle, there should be an GUI without any vehicles. However, the same error occurred, and the program continued to run without exiting. Will this BUG affect my training data?

Error: Answered with error to command 0xa4: Vehicle 'veh00' is not known.
Error: Answered with error to command 0xa4: Vehicle 'veh00' is not known.
Error: Answered with error to command 0xa4: Vehicle 'veh00' is not known.
Error: Answered with error to command 0xa4: Vehicle 'veh00' is not known.
Error: Answered with error to command 0xa4: Vehicle 'veh00' is not known.
Error: Answered with error to command 0xa4: Vehicle 'veh01' is not known.
Error: Answered with error to command 0xa4: Vehicle 'veh01' is not known.
Error: Answered with error to command 0xa4: Vehicle 'veh01' is not known.
Error: Answered with error to command 0xa4: Vehicle 'veh01' is not known.
Error: Answered with error to command 0xa4: Vehicle 'veh01' is not known.
Error: Answered with error to command 0xa4: Vehicle 'veh02' is not known.
Error: Answered with error to command 0xa4: Vehicle 'veh02' is not known.
Error: Answered with error to command 0xa4: Vehicle 'veh02' is not known.
Error: Answered with error to command 0xa4: Vehicle 'veh02' is not known.
Error: Answered with error to command 0xa4: Vehicle 'veh02' is not known.
Error: Answered with error to command 0xa4: Vehicle 'veh03' is not known.
Error: Answered with error to command 0xa4: Vehicle 'veh03' is not known.
Error: Answered with error to command 0xa4: Vehicle 'veh03' is not known.
Error: Answered with error to command 0xa4: Vehicle 'veh03' is not known.
Error: Answered with error to command 0xa4: Vehicle 'veh03' is not known.
...

Thanks.

**Comment by namdre** [comment]
@ShenZC25  Your error is unrelated: This ticket is about `simulation.load` whereas your error arrise becaus of a `traci.vehicle` command with an unknown vehID.  You can catch the TraCIException and nothing bad will happen (though you should probably figure out why you are trying to access vehicles when the vehicle isn't there anymore).

**Comment by rvangaal** [comment]
Which Simulation::getXXX() function would you use to detect vehicles that are being removed? I have a similar issue but have trouble in keeping an uptodate list of vehicles (and getIDList() doesn't seem available in the C++ API).

**Comment by namdre** [comment]
> Which Simulation::getXXX() function would you use to detect vehicles that are being removed? I have a similar issue but have trouble in keeping an uptodate list of vehicles (and getIDList() doesn't seem available in the C++ API).

- getArrivedIDList() (called on the simulation domain) can be used to track arrived vehicles
- getIDList() is supported by all domains including vehicles
- The C++ API is obsolete (see https://sumo.dlr.de/docs/TraCI/C%2B%2BTraCIAPI.html)

**Comment by jianki1314** [comment]
When I use durouuter to input the odtrips.xml file, I set vtype=passenger when creating odtrips.xml, but when I run durouuter, I get an error:
Error: The vehicle type 'passenger' for vehicle 'Car3063' is not known.
Error: The vehicle type 'passenger' for vehicle 'Car1456' is not known.
Error: The vehicle type 'passenger' for vehicle 'Car2679' is not known.
Quitting (on error).

**Comment by jianki1314** [comment]
Sorry, I made a typo when using the durouter.
