### ISSUE TITLE
Connection to TraCI server lost while using veins

### ISSUE THREAD

**Issue by divakar5** [eclipse/sumo#8427]
I'm getting the below issue

divakar@divakar:~/veins-5.1/veins-veins-5.1$ ./sumo-launchd.py -vv -c sumo
WARNING: the sumo-launchd.py script is deprecated in favor of bin/veins_launchd. Redirecting.
WARNING: the sumo-launchd.py script is deprecated in favor of bin/veins_launchd. Redirecting.
Logging to /tmp/sumo-launchd.log
Listening on port 9999
Connection from 127.0.0.1 on port 44898
Handling connection from 127.0.0.1 on port 44898
Got TraCI message of length 2
Got TraCI command of length 1
Got TraCI command 0x0
Got CMD_GETVERSION
Got TraCI message of length 304
Got TraCI command of length 299
Got TraCI command 0x75
Got CMD_FILE_SEND for "b'sumo-launchd.launch.xml'"
Got CMD_FILE_SEND with data "b'<launch>\n  <copy file="erlangen.net.xml"/>\n  <copy file="erlangen.rou.xml"/>\n  <copy file="erlangen.poly.xml"/>\n  <copy file="erlangen.sumo.cfg" type="config"/>\n  <basedir path="/home/divakar/veins-5.1/veins-veins-5.1/examples/veins/"/>\n  <seed value="0"/>\n</launch>\n'"
Creating temporary directory...
Temporary dir is /tmp/sumo-launchd-tmp-kxqifxm5
Base dir is /home/divakar/veins-5.1/veins-veins-5.1/examples/veins/
Seed is 0
Finding free port number...
Claiming lock on port
...found port 40991
Starting SUMO (sumo -c erlangen.sumo.cfg) on port 40991, seed 0
Connecting to SUMO (sumo -c erlangen.sumo.cfg) on port 40991 (try 1)
Error ([Errno 111] Connection refused)
Connecting to SUMO (sumo -c erlangen.sumo.cfg) on port 40991 (try 2)
Releasing lock on port
Starting proxy mode
Done with proxy mode
Done with proxy mode, killing SUMO
Done running SUMO
Cleaning up
Result: "<?xml version="1.0"?>
<status>
	<exit-code>1</exit-code>
	<start>1616690356</start>
	<end>1616690357</end>
	<status>Exited with error code 1</status>
	<stdout><![CDATA[Loading configuration ... done.
***Starting server on port 40991 ***
Loading net-file from 'erlangen.net.xml' ... done (265ms).
Loading additional-files from 'erlangen.poly.xml' ... done (10ms).
Loading done.
Simulation version v1_8_0+1682-0e6d5dc9a4 started with time: 0.00
]]></stdout>
	<stderr><![CDATA[Error: Storage::readChar(): invalid position
Quitting (on error).
]]></stderr>
</status>
"
Closing connection from 127.0.0.1 on port 44898
^CKeyboard interrupt.
Shutting down.
WARNING: the sumo-launchd.py script is deprecated in favor of bin/veins_launchd. Redirection done.
WARNING: the sumo-launchd.py script is deprecated in favor of bin/veins_launchd. Redirection done.

I tried adding **log value="log.txt"** and  **verbose value="true"** in erlangen.sumo.cfg (in veins example) after that i triggered simulation i got same error and Omnetpp console displayed the below error.

terminate called after throwing an instance of 'omnetpp::cRuntimeError'
what(): Connection to TraCI server lost. Check your server's log. Error message: 32: Broken pipe

Please guide me, I'm new to this domain.

**Comment by behrisch** [comment]
I cannot immediately spot a sumo error here, maybe it is better to ask here: https://github.com/sommer/veins/issues and also see the comments here #7090

**Comment by sommer** [comment]
The console output is missing anything between angle brackets `<` and `>`. Coincidentally, this is what contains the output received from SUMO (see the below example) 

```
Done running SUMO
Cleaning up
Result: "<?xml version="1.0"?>
<status>
        <exit-code>1</exit-code>
        <start>1616770618</start>
        <end>1616770618</end>
        <status>Exited with error code 1</status>
        <stdout><![CDATA[Loading configuration ... done.
]]></stdout>
        <stderr><![CDATA[Error: expected end of tag 'net'
 In file 'erlangen.net.xml'
 At line/column 83/7.

Quitting (on error).
]]></stderr>
</status>
```

In this case, the error message written by SUMO was "**Error: expected end of tag 'net' In file 'erlangen.net.xml' At line/column 83/7. Quitting (on error).**"

**Comment by divakar5** [comment]
Hi SIr,
This is how my error looks
![image](https://user-images.githubusercontent.com/80413167/112653490-7b3edd00-8e74-11eb-8aab-46d84fa6319b.png)

**Comment by sommer** [comment]
So, your error message is "**`Error: Attribute 'maxSpeed' in definition of vType 'vtype0' is empty.`**".

Most likely you changed `vtype0` in your `.rou.xml` and made a mistake there.

**Comment by behrisch** [comment]
Please reopen with more info if problems persist.
