### ISSUE TITLE
osmWebWizard.py: error: argument -n/--netconvert-options: expected one argument

### ISSUE THREAD

**Issue by raviteja-1504** [eclipse/sumo#8428]
python osmWebWizard.py 
Building scenario in '/home/ravi/ns-allinone-3.32/sumo/tools/2021-03-25-23-20-48'
Downloading map data
200 OK
Converting map data
usage: osmWebWizard.py [-h] [-c FILE] [-C FILE] [--save-template FILE]
                       [-p PREFIX] [-f OSM_FILE] [-m TYPEMAP]
                       [--netconvert-typemap NETCONVERT_TYPEMAP]
                       [-o OLDAPI_PREFIX] [-t TILES]
                       [--vehicle-classes VEHICLE_CLASSES]
                       [-d OUTPUT_DIRECTORY] [-n NETCONVERT_OPTIONS]
                       [--pedestrians] [-y POLYCONVERT_OPTIONS]
osmWebWizard.py: error: argument -n/--netconvert-options: expected one argument

**Comment by namdre** [comment]
- does this happen with any area you try to import or only with some of them?
- which version of sumo are you using?

**Comment by raviteja-1504** [comment]
I'm using the default location (Berlin) and sumo version is 1.8.0

**Comment by namdre** [comment]
I'm able to replicate the issue

**Comment by namdre** [comment]
@angelobanse was broken by f51f308ff2363083025e71632db because sumolib.options.ArgumentParser misinterprets an option value that looks like an option (a list of comma-separated netconvert options is passed as a single argument to osmBuild.py)

**Comment by namdre** [comment]
@raviteja-1504 I'm pretty sure this was only broken 2 days ago so I suspect your are somehow using a tools package  that is newer than 1.8.  Either use the real 1.8.0 or upgrade to the very latest development build or just overwrite the file osmBuild
