### ISSUE TITLE
duarouter --repair changes the route significantly

### ISSUE THREAD

**Issue by ArmelliniMG** [eclipse/sumo#8429]
Test scenario:
[test_duarouter.zip](https://github.com/eclipse/sumo/files/6213480/test_duarouter.zip)

I'm trying to use duarouter in #8251 to fix pt routes from OSM that show some disconnected edges. 
The first picture shows the route input and the second one the repaired route by duarouter:
![raw](https://user-images.githubusercontent.com/48476390/112671170-23977600-8e62-11eb-8964-2d60142ec303.PNG)![repaired](https://user-images.githubusercontent.com/48476390/112671885-10d17100-8e63-11eb-9192-0e64402a2cba.PNG)

**Comment by namdre** [comment]
Route repair reconnects between "mandatory" edges: stop edges and via-edges. It might be worthwhile to add an option which makes all route edges mandatory (and then only connect the gaps).  i.e. **--repair.keep-all**

As a workaround you can simply define the input as a trip where all known edges are written into the via-attribute (no 'from' and 'to' attributes are needed).

**Comment by ArmelliniMG** [comment]
I was defining the routes with the attribute "edges". I changed it to trips with the "via" attribute and the output was better.
I think the "via" attribute might already be working as the option **--repair.keep-all** you suggested. For example, if an edge of the "via" definition was not reachable, the route was not valid and no route was suggested:
```
Warning: Mandatory edge '-97133107#7' not reachable by vehicle '2077771'.
Warning: The vehicle '2077771' has no valid route.
```

**Comment by behrisch** [comment]
Also please enhance **--repair** documentation.
