### ISSUE TITLE
centos install 

### ISSUE THREAD

**Issue by zzchuman** [eclipse/sumo#8430]
Hello, I have install the sumo on the win10 andd ubuntu!
But, when I try to install  it on centos! It not works!

First, I downlowd the sumo-src-1.8.0.tar.gz,  tar-zxvf sumo-src-1.8.0.tar.gz.
Sencond, I set the Environment variable export SUMO_HOME="/home/liusu/sumo-1.1.0" and source it.

But, it shows that there is not sumo bash.

And, I try to ./configuure and cmake, IT not works.
Can you teach me?

**Comment by namdre** [comment]
make sure you've installed all the depencies: 
https://sumo.dlr.de/docs/Installing/Linux_Build_Libraries.html#centos_rhel

If case of problems, posted the actual error messages.

**Comment by behrisch** [comment]
There are also CentOS RPMs available: https://sumo.dlr.de/docs/Downloads.php#repositories but please be aware that they do not have GDAL support (no shapefiles or GeoTIFFs can be read). Please reopen if problems persist.
