### ISSUE TITLE
Bluetooth by traci

### ISSUE THREAD

**Issue by thinker310** [eclipse/sumo#8431]
SUMO currently can not provide traci to connect bluetooth specified in documentation, so I want to consult when the function can be supported?

**Comment by namdre** [comment]
bluetooth connects automatically when in range. What functionality would you like to trigger via TraCI?

**Comment by thinker310** [comment]
> bluetooth connects automatically when in range. What functionality would you like to trigger via TraCI?

Yeah. I need to know if the vehicle  carry a bluetooth device while the simulation is running. I want to manipulate  the vehicles with blue tooth online. Do you have any suggestions please?

**Comment by namdre** [comment]
you can use 
```
traci.vehicle.getParameter(vehID, "has.btreceiver.device")
traci.vehicle.getParameter(vehID, "has.btsender.device")
```
which will return "true" / "false"
