### ISSUE TITLE
Actuated lights not supported by meso simulation?

### ISSUE THREAD

**Issue by Reivajar** [eclipse/sumo#8432]
Hi,

I had a doubt regarding actuated lights. Does this option work for mesoscopic simulation? 

I have not found any information regarding this issue on the documentation, but I got some log files confirming that actuated is not used by mesoscopic simulation.

Thanks.

**Comment by namdre** [comment]
The mesoscopic simulation does not support actuated traffic lights. It's targeting larger and coarser scenarios and allows switching between microscopic (fixed timing) and macroscopic traffic lights.
