### ISSUE TITLE
A question about travelling time on each lain? 

### ISSUE THREAD

**Issue by HawkTom** [eclipse/sumo#8438]
Hello,

Now, I want to use SUMO to test an dynamic vehicle routing problem (e.g. TSP)  and I have found real scenario in the SUMO website.  

We are aimed to test our algorithm's reschedule ability when happened to the dynamic traffic events, like congestion. Therefore, we want to have the data of travesing time of vehicles on each edge/lane at each time.  

So I want to ask if it possible to obtain the travelling time of an vehicle on each edge/lane.  I find that there's a function `traci.lane.getTraveltime(laneID)` amd its description is "Returns the estimated travel time in s for the last time step on the given lane."  Does this function calculate an estimated travelling time of an vehicle on the lane at current time point according to the real traffic condition? 

If not, could you please how (which function) can I obtain that information. Thanks. 

Best,
Hao

**Comment by HawkTom** [comment]
One more question  is how to detect the congestion. Thanks. 🤝

**Comment by namdre** [comment]
* traci.lane.getTraveltime(laneID): travel time based on average vehicle speed in the previous step. This will fluctuate strongly ahead of traffic lights
* traci.vehicle.getParameter(vehID, "device.rerouting.edge:EDGE_ID"): traveltime based on travel speeds averaged over multiple steps. (vehID can be any vehicle equipped with rerouting device). See https://sumo.dlr.de/docs/Demand/Automatic_Routing.html#edge_weights

Congestion: compare average speeds/traveltimes to free-flow speeds/traveltimes (i.e. speedLimit, length/speedLimit)
