### ISSUE TITLE
Debugging libsumo/libtraci Application

### ISSUE THREAD

**Issue by Domsall** [eclipse/sumo#8439]
I am working on a C++ Co-Simulation Application, which also includes libsumocpp.lib. When I tried to debug it (Visual Studio Debug Mode), I got an unfamiliar error and nothing worked. Turned out to be a problem with the library, because it was compiled in Release Mode. After I compiled LibSumo in Debug Mode, my Application could load the symbols and debugging was successful.
Most of the Sumo applications (sumo, sumo-gui, netedit, etc.) have a "Debug Version", but the libsumocpp and libtracicpp libraries (lib and dll) don't have these kind of versions. Am I doing something wrong and those libraries should work in both Modes?! Or should the libraries be separated (e.g. in libsumocppD.lib/.dll)?!

**Comment by behrisch** [comment]
You are right this is still missing

**Comment by behrisch** [comment]
The build now creates a debug version with D. Still need to check whether it makes it into the nightly zips

**Comment by Domsall** [comment]
Thank you very much, works perfectly for my case!
