### ISSUE TITLE
Junction in SUMO

### ISSUE THREAD

**Issue by rahulbhadani** [eclipse/sumo#8442]
I am looking to create junctions manually in Sumo.

I have followed this tutorial:
https://github.com/eclipse/sumo/blob/master/docs/web/docs/Networks/SUMO_Road_Networks.md#junctions-and-right-of-way

and 
https://sumo.dlr.de/docs/Networks/PlainXML.html#connection_descriptions

However, I am not sure where <junction> tags should go.

Currently, a standard netconvert command looks like this:

```
netconvert --node-files=MyNodes.nod.xml --edge-files=MyEdges.edg.xml \
  --connection-files=MyConnections.con.xml --type-files=MyTypes.typ.xml \
  --output-file=MySUMONet.net.xml

```

So should <junction> tag go to node files, edge files, connection files, type files or additional files?

**Comment by namdre** [comment]
The link https://github.com/eclipse/sumo/blob/master/docs/web/docs/Networks/SUMO_Road_Networks.md#junctions-and-right-of-way is a technical reference. You should not attempt to generated this format
(see https://sumo.dlr.de/docs/FAQ.html#i_made_changes_to_the_netxml-file_but_it_did_not_work_as_expected_why)

For actual tutorials, see
https://sumo.dlr.de/docs/Tutorials/Hello_World.html
and
https://sumo.dlr.de/docs/Tutorials/Hello_SUMO.html

re-open this issue if you have further related questions.

**Comment by rahulbhadani** [comment]
Okay, I may not have understood the notion of a junction. Are junctions tag automatically generated by netconvert? In such a case, how can I specify what other parameters in <node> and <edge> tag can alter the properties of a junction?

**Comment by namdre** [comment]
Yes. Junctions are automatically generated. For setting attributes see https://sumo.dlr.de/docs/Networks/PlainXML.html#node_descriptions
