### ISSUE TITLE
TraCI: How can I disable the terminal output for the SUMO subprocess?

### ISSUE THREAD

**Issue by philippwulff** [eclipse/sumo#8443]
I opened the SUMO process with 

`sumo_process = subprocess.Popen(sumo_cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)`

hoping that this would direct the output not to the terminal, but that does not work. I need this because of a bug that currently exists and outputs lots of error messages in the terminal. Is there a  solution for this?

This same question was also asked in the [mailing list](https://www.eclipse.org/lists/sumo-user/msg04977.html), but did not receive any answer.

**Comment by behrisch** [comment]
This seems to be a rather general python question as answered here: https://stackoverflow.com/questions/1244723/disable-console-output-from-subprocess-popen-in-python. Depending on your python version you might also use os.devnull directly
