### ISSUE TITLE
TraCIAPI.h Conflict with <winsock.h>  (tag: 1.18.0)

### ISSUE THREAD

**Issue by IChihWang** [eclipse/sumo#8444]
I found that when using <winsock.h> my own TraCI client, there will be a compile error. 

I'm building my own TraCI client in C++, which also involves external socket connections.
According to the document (https://sumo.dlr.de/docs/TraCI/C++TraCIAPI.html#building_the_library), I import essential headers and source files according to the instructions.
Also, I import <winsock.h> to establish additional sockets in the same program, and it shows error on "std::numeric_limits<double>::max()" in TraCIAPI.h (line 194, 195, 671, 672).

Here are the cause and a suggestion.

Cause:
<winsock.h> defines    "#define max(a,b) (((a) > (b)) ? (a) : (b))",  which affects the "max" and "min" in "TraCIAPI.h".

Suggestion:
Add parentheses to prevent this issue:  in TraCIAPI.h (line 194, 195, 671, 672)
std::numeric_limits<double>::max()   ==>  **(**std::numeric_limits<double>::max**)**()
std::numeric_limits<double>::min()   ==>  **(**std::numeric_limits<double>::min**)**()

**Comment by behrisch** [comment]
Thanks for the suggestion but TraCIAPI.h is not going to be maintained any longer and will be replaced by libtraci. I think the preferred way to handle this issue is to use a stanza like this: 
```
#define NOMINMAX
#include <winsock.h>
#undef NOMINMAX
```
