### ISSUE TITLE
Getting edge outputs for each iteration of duaIterate?

### ISSUE THREAD

**Issue by Reivajar** [eclipse/sumo#8448]
Hi,

Is it possible to get edge-based output files for each duaIterate iteration, or should I modify the .py file accordingly to pass the step folder path to the init file?

From what I have observed, you cannot assign programmatically the output path in the xml file to catch the step duaIterate is at, so I bet the only option should be through editing the duaIterate.py file.

Thanks.

**Comment by namdre** [comment]
edge-based output files are already written in every iteration (and saved in the iteration folder). They are an integral part duaIterate and are used to record simulation travel times for the subsequent routing step. 

If you need further outputs to be placed in the correct folder, then yes: you need to modify the duaIterate.py script.
