### ISSUE TITLE
Memory leak in loading a state

### ISSUE THREAD

**Issue by atellyro** [eclipse/sumo#8450]
When loading a state, local copies are made with a clone call in MSStateHandler.cpp
These copies are not cleaned up on exit or when overwriting with a new clone

These are the clone lines:
> grep -n clone src/microsim/MSStateHandler.cpp
185:            myVCAttrs = attrs.clone();
205:            myAttrs = attrs.clone();
209:            myDeviceAttrs.push_back(attrs.clone());
307:            myAttrs = attrs.clone();

This is a fix to myVCAttrs
```
  MSStateHandler::~MSStateHandler() {
+   if (myVCAttrs != nullptr) {
+     delete myVCAttrs;
+   }
  }

          case SUMO_TAG_DELAY: {
+             if (myVCAttrs != nullptr) {
+               delete myVCAttrs;
+             }
              myVCAttrs = attrs.clone();
```
The other clone parts need to be handled similar

The input files are in this mail

Betreff: | [sumo-user] Using traci.simulation.loadState increases memory usage
-- | --
Mon, 29 Mar 2021 08:49:39 -0600
. Abdullah <ab11@ualberta.ca>

Attached is a modified version of the python script, which allows running and modification of the parameters by a script (at least under linux)

usage: traci_demo_hs.py [-h] [-v] [-l] [-d DURATION] [-r REPEAT]

Run SUMO and valgrind

optional arguments:
  -h, --help            show this help message and exit
  -v, --valgrind        Run sumo under control of valgrind
  -l, --leak            set leak-check-kinds = all
  -d DURATION, --duration DURATION
                        Duration in sek (default 120)
  -r REPEAT, --repeat REPEAT
                        Number od save/load loops (default=200)

[traci_demo_hs.py.zip](https://github.com/eclipse/sumo/files/6269611/traci_demo_hs.py.zip)

**Comment by namdre** [comment]
all clone calls except `myVCAttrs = attrs.clone();` where already cleaning up after themselves

**Comment by namdre** [comment]
there is still a memory leak (thanks Harald for pointing this out!). It just isn't caught by valgrind this time.

**Comment by rjmaris** [comment]
@namdre I'm not sure whether it fits here, but I see a memory leak after reloading a simulation in sumo-gui. After starting sumo-gui, the memory increases from 2.5 until 7.5 % of 6 Gigs of memory till end of a simulation (tool: top/htop)
Upon every reload+simulation approx. 4 % is added to memory usage.
(v 1.12.0 as well as +0904, with minor differences in memory figures)

**Comment by namdre** [comment]
@rjmaris Thanks for reporting. I'm now tracking it at #10232
