### ISSUE TITLE
geometry.max-segment-length without geometry.split

### ISSUE THREAD

**Issue by ambuehll** [eclipse/sumo#8457]
geometry.max-segment-length is only active when geometry.split is set true. Is this intended?
I'd rather not split the edge when there is a geometry, only if the edge becomes too long (e.g. >1000m)

here an example with 250m:
[files](https://drive.google.com/drive/folders/1FAfJl32UwiRxxfpfNIeJmkHT1bt2QsCV?usp=sharing)
netconvert -s ZRH.net.xml --geometry.split true --geometry.max-segment-length 250 -o ZRH_short.net.xml
vs
netconvert -s ZRH.net.xml --geometry.max-segment-length 250 -o ZRH_short.net.xml

**Comment by ambuehll** [comment]
Ah, I might have been too fast posting this. A geometry.max-segment-length only creates a geometry point, but does not split the edge itself. That's why I need to split it with geometry.split if I want a new edge initiated? Sorry about the confusion

**Comment by namdre** [comment]
Yes. max-segment-length is only for geometry-segments within an edge. It is mostly useful to get higher fidelity in elevation.

**Comment by ambuehll** [comment]
OK! Got it. Sorry about that. Thanks!
