### ISSUE TITLE
how to change the routing algorithms when use duarouter

### ISSUE THREAD

**Issue by zhaotuo0815** [eclipse/sumo#8459]
hi,sumo developer,the default  routing algorithms is  dijkstra ，I want to compare the effect of several  routing algorithms(astar,dijkstra and CH),so my question is that how to change the routing algorithms when use duarouter or route2trips.py or duaIterate.py ,such as (duarouter -n input.net.xml -r input.trips.xml -ooutput.rou.xml  )

**Comment by namdre** [comment]
duarouter and duaIterate both accept the option  **--routing-algorithm ALGONAME**

**Comment by zhaotuo0815** [comment]
> duarouter and duaIterate both accept the option **--routing-algorithm ALGONAME**

thank you very much for your prompt reply.So i just change the algorithms(<routing-algorithm value="dijkstra"/>)  when I set the configuration(qihua.trips2router.duarcfg) like as follows :
<configuration>
	<input>
		<net-file value="qihua.net.xml"/>
		<route-files value="qihua.odtrips.xml"/>
	</input>
	
	<output>
		<output-file value="qihua.odtrips.rou.xml"/>
		<alternatives-output value="qihua.odtrips.rou.alt.xml"/>
	</output>

        <net-file value="qihua.net.xml"/>
        <route-files value="qihua.odtrips.xml"/>
    </input>
    <processing>
        <routing-algorithm value="dijkstra"/>
    </processing>
</configuration>
and ues (duarouter -c qihua.trips2router.duarcfg --ignore-errors) just right?

**Comment by behrisch** [comment]
yes

**Comment by zhaotuo0815** [comment]
> yes

Thank you so much!
