### ISSUE TITLE
Change color of routes by Traci

### ISSUE THREAD

**Issue by HawkTom** [eclipse/sumo#8460]
Hello, 

Now, I want to highlight some routes in the gui. In the tutorial (following page),(https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#vehicles_and_routes), I find the color of vehicles and routes can be set by the configuration file (.xml). Now I want to add some routes by Traci and highlight these routes by different colors. I have found the function to change the color of vehicles but didn't find functions for changing color for routes.  **May I ask if there is a function in the Traci to change the color of routes**. Thanks.

**Comment by namdre** [comment]
There is currently no such function. However, in the gui, the vehicles and their routes are shown with the same color (routes are always a bit darker than the current color for the vehicle). Therefore, the recommended way to change the route color is to just set the vehicle color.
 In the default color scheme the value set by vehicle.setColor takes precedence over other color options.
