### ISSUE TITLE
tripinfo personinfo depart="-1"

### ISSUE THREAD

**Issue by MelanieWeber** [eclipse/sumo#8461]
moin moin,
after one day simulation, the first person in the scenario has at the tripinfo.xml  the depart="-1" at his last ride.

    <personinfo id="passenger_wharf5a_EUROPALINK_on.0" depart="17599.00" type="DEFAULT_PEDTYPE">
        <walk depart="17599.00" departPos="0.00" arrival="17613.00" arrivalPos="15.46" duration="14.00" routeLength="15.46" timeLoss="1.42" maxSpeed="1.23"/>
        <walk depart="17613.00" departPos="15.46" arrival="17668.00" arrivalPos="23.00" duration="55.00" routeLength="59.51" timeLoss="6.57" maxSpeed="1.23"/>
        <ride waitingTime="91.00" vehicle="bus_terminal_wharf5a_on" depart="17759.00" arrival="17838.00" arrivalPos="60.00" duration="79.00" routeLength="655.54" timeLoss="18.17"/>
        <walk depart="17838.00" departPos="60.00" arrival="17841.00" arrivalPos="62.69" duration="3.00" routeLength="2.69" timeLoss="0.81" maxSpeed="1.23"/>
        <access stop="busStop_pier5a_ship" depart="17841.00" arrival="17873.00" duration="32.00" routeLength="45.14"/>
        <ride waitingTime="13.00" vehicle="ferry_wharf5a_EUROPALINK" **depart="-1"** arrival="17886.00" arrivalPos="20.00" duration="17886.00" routeLength="0.01" timeLoss="0.00"/>
    </personinfo>

a small version of this scenatio do not produce this bug... so if you need the big one ask me

**Comment by behrisch** [comment]
I don't think the -1 is the problem. It is a more or less well established way of saying it did not depart yet because it is still waiting. The problem is that the other attributes such as arrival, arrivalPos, duration, routeLength should show invalid values as well.

Is my assumption right that write-unfinished is enabled?

**Comment by namdre** [comment]
Yes. I need a test case for this.

**Comment by behrisch** [comment]
there is a test which shows the behavior sumo/output/tripinfo/write_unfinished_person. For a started stage it should show the values until now for not started stages "-1"
