### ISSUE TITLE
Emergency braking with continuous lane changing

### ISSUE THREAD

**Issue by Domsall** [eclipse/sumo#8466]
First of all this could be a duplicate of #7955. I unfortunately can't provide an exact example, the setup uses an individually built sumo and it takes many minutes until this issue appears. But I could maybe provide some kind of Debug-Output?! 

The issue:
I am simulating traffic with hundreds of vehicles on the freely available A9 Nord OpenDrive map. I am using LC2013 with continuous lane changing. Besides some hiccups its works pretty good. I have a setup where after some time a vehicle emergency brakes from approx. 39m/s to 0m/s. 
I looked into sumo-gui and into the Code. It seems that this vehicle is performing a continuous lane change and one step before finishing (still has its old Lane as a shadowLane) a vehicle next to this vehicle starts its lane change to the shadowLane. The vehicle then "sees" this vehicle as its leader and brakes hard (happens in `MSLane::getLastVehicleInformation` in `MSVehicle::planMoveInternal`). 

It looks like the neighbor vehicle is allowed to change lanes before the other vehicle has completed his lane change. The only problem is that the already changing vehicle then reacts to this action.

An example:

![image](https://user-images.githubusercontent.com/53042793/114065390-e89e3500-989a-11eb-95c2-f443300dc62d.png)

Another example (when one vehicle is actually changing "away from the lane", like described above):

![image](https://user-images.githubusercontent.com/53042793/114146259-a6670900-9917-11eb-8d41-268662976062.png)

**Comment by namdre** [comment]
Yes. That sounds like a bug. Let's look at this once your model has made it into sumo. (unless you can catch this with a standard sumo somehow).

On a side note: Your screenshots will have more intelligible lane markings when you import your OpenDrive networks with less geometic detail using option **--opendrive.curve-resolution 6** (each geometry point resets lane markings)

**Comment by Domsall** [comment]
I just changed a few settings and testet it with the official SUMO-Release. I could also find the bug there and sent you the configuration.

I am using this "high detail" map because I am using a Co-Simulation with Carla, Simulink and SUMO. Therefore I need a twin-map of the OpenDrive map. But yes I was also wondering how I could bring back the lane markings.

**Comment by namdre** [comment]
I'm pretty sure changing the curve-resolution from 2 to 6 will not have a meaningful impact on vehicle localization in different simulators (let me know how it goes if you test this).

**Comment by namdre** [comment]
it's really hard for me to isolate this in a small test case for the current version. I thought I had a test but it was something else: #8489 
If you can manage to create a smaller test case, that would be really helpful.

**Comment by Domsall** [comment]
[LaneChangeBrake.zip](https://github.com/eclipse/sumo/files/6309742/LaneChangeBrake.zip)

I hope this helps. I again tested it with SUMO 1.8, where I am still getting the emergency braking. But it isnt easy to create this issue.

**Comment by Domsall** [comment]
I took a deeper Look into this issue and found the problem in the getPartialBehind function:
https://github.com/eclipse/sumo/blob/54b2652d906d26b4c3589c47cdda2361852c7192/src/microsim/MSLane.cpp#L3535

It (reverse) loops over the partially overlapping vehicles, not in the correct lane position order, but rather in a time dependant fashion. A vehicle seems to be added to the vector `myPartialVehicles` when it starts overlapping. So reverse looping here and taking the first found vehicle just takes the last vehicle, which started overlapping. When another closer vehicle is overlapping, this assumption fails.

Is it better to change the way the vehicles are put into `myPartialVehicles` or just to change the loop to check for all vehicles and take the closest one (may be a bit more expensive on long lanes, but with a low number of changing vehicles this would not be critical)?!

**Comment by namdre** [comment]
The partial vehicles are sorted in MSLane::sortPartialVehicles
- after vehicles have moved
- after all the lane changer has processed an edge

Since the lane changer handles vehicles starting at the end of the edge and processes them in upstream direction, each vehicle should see partially-behind vehicles that are still sorted. 

If you can figure out the exact conditions that violate the above assumptions it would go a long way towards fixing it.

**Comment by Domsall** [comment]
Thanks for your feedback! Just to understand it correctly:
I debugged a bit more and went through the function where `PartialVehicles` are sorted and looked at `vehicle_natural_position_sorter`. It sorts the vehicles in the opposite order as `vehicle_position_sorter`. So the first vehicle [0] in this vector is the last follower on the lane, the last vehicle in the vector the first leader on the lane.

It seems that the problem occurs with vehicles switching edges. All emergency brakes happened, when a vehicle changed the lane far behind between 2 edges. I looked into it and `myPartialVehicles` were sorted differently than above described.

I debugged everything with the example from above.

**Comment by namdre** [comment]
I managed to find at least one bug (sorting wasn't triggered as it should be for continuous-lanechange-mode) and there are fewer emergency braking events.

**Comment by namdre** [comment]
The remaining events are still from lack of sorting:
- sorting is only triggered for lanes that have at least one vehicle (front) on it
- if a vehicle enters a new lane partially (because it enters a neighbor and overlaps), and the new lane has no vehicles, sorting may be needed but not triggered

**Comment by Domsall** [comment]
Thank you very much for helping and finding this small, but critical bug!
I just tested it with the example from above and my adapted 1.8 Version --> all emergency brakes are gone!

Can I somehow help with data and/or the other cases?
