### ISSUE TITLE
Car following model using Traci

### ISSUE THREAD

**Issue by Wangjw6** [eclipse/sumo#8467]
I simulate the cars running in circles (as shown in https://sumo.dlr.de/docs/Tutorials/Driving_in_Circles.html) using python inference (i.e.,traci).
I find that no matter which car-following model I use, I can not observe the stop-and-go wave.  In other words, the cars can maintain nearly constant headway during the simulation.  Is there any bug in this simulation?

**Comment by namdre** [comment]
To obtain stop-and-go waves you need two things:
- high vehicle density: https://sumo.dlr.de/docs/Tutorials/FundamentalDiagram.html#fundamental_diagram_of_a_closed_circular_route
- a suitable combination of carFollowModel and parameters. Some Examples:
   - IDM will never have stop-and-go but will show pronounced slow-and-fast waves starting at ~35 veh/km
   - Krauss model with default parameters has no waves
   - Krauss with sigma=0.65 has waves at ~58veh/km and hgiehr
   - Krauss will with sigma=0.75 has waves at ~38veh/km (including stopped vehicles at average circle density of ~45veh/km)
   - Wiedemann has waves at ~20 veh/km

**Comment by namdre** [comment]
We are aware that the current default parameter behavior of no-stop-and-go is unexpected and we did have plans to change the default (i.e. #4235). I think the main impediment to changing the default is that it would have side effects that could break other simulations which rely on the default behavior and don't need stop-and-go waves. @piwagner do you recall why we didn't make the change for version 1.0 ?

**Comment by namdre** [comment]
In the linked tests, the stop and go-wave develops at around t=3000. A good way to observe this is by changing the visualization settings for vehicles (F9)
- color 'by speed'
- activate 'Draw with constant size when zoomed out'

**Comment by Wangjw6** [comment]
What I used is departPos="base" and I have not specified the departEdge.

**Comment by Wangjw6** [comment]
Also, I would like to ask why only part of the planned vehicles are inserted into the network. I load vehicles in the ring at the same position every 10 secs. For example, the total number of vehicles I planned to load is 22 but in simulation, I only observe 4 running vehicles.

**Comment by namdre** [comment]
Inserting vehicles with high density is not a trivial matter as explained here: https://sumo.dlr.de/docs/Simulation/VehicleInsertion.html#insertion_departure
The test uses departPos="last" to obtain an even spacing for this reason. 
I recommend that you take a look at this scenario: https://sumo.dlr.de/extractTest.php?path=sumo/tests/sumo/cf_model/drive_in_circles/circle_stop_and_go_legacy

**Comment by namdre** [comment]
I'm quoting a personal comment from @piwagner regarding sigma

> I thought that we made the decision to increase it, and dimly remember that I was slightly surprised that we have not. But not disappointed, since this is a borderline decision in my eyes. So, three years later I think that staying at sigma=0.5 was no bad: I do no longer really trust the mechanism in the Sumo-Krauss model that produces the jams, since it needs such a strong disturbance in the speed of an individual car to cause jams. To my knowledge from having looked at many car-following data, this is not realistic. (That does not mean, that the other mechanisms e.g. in the IDM are better…). So, I think it is better to (more or less) consciously increase sigma if it is really needed for some application, and to stick to the already fairly old sigma=0.5 as a default value.

**Comment by Wangjw6** [comment]
I have successfully loaded 22 vehicles in a 600m circle, which result in a density of 36.67 veh/km. But all the vehicles maintain a nearly equal headway during simulation with IDM model. There is no slow-and-fast wave.

**Comment by namdre** [comment]
My first scenario was using a 10km circle. Please see attached scenarios for my findings:

- 600m circle with 22 veh: min wave speed 12m/s max wave speed 21m/s
- 600m cirlce with 30 veh: min wave speed 4m/s max wave speed 19m/s (**run sumo-gui -c 600m.sumocfg --max-num-vehicles 30**)
- 1km circle with 35 veh: min wave speed 9m/s max wave speed 21m/s
- 10km circle with 350 veh: min wave speed 3m/s max wave speed 20m/s

[circles.zip](https://github.com/eclipse/sumo/files/6289329/circles.zip)

**Comment by Domsall** [comment]
If you want to test the IDM with different CF parameters, I can recommend taking a look into the [IDM applet](https://traffic-simulation.de/). You can easily create a one-lane circle and test different parameters to get an understanding of the model.
