### ISSUE TITLE
Car-following model does not function well in running circles

### ISSUE THREAD

**Issue by Wangjw6** [eclipse/sumo#8469]
I conducted an experiment based on https://sumo.dlr.de/docs/Tutorials/Driving_in_Circles.html. I obtained the temporal-space trajectory from the simulation and could not find a clear stop-and-go wave no matter which car-following model was used. Is there any bug when running circles?

**Comment by namdre** [comment]
Possibly you are using sumo-version 1.8 with the new attribute `departEdge="random"`. I recently updated to tutorial for the upcoming release of version 1.9 where this keyword is supported. In 1.8 this keyword is ignored and you will not get sufficient vehicle density. For 1.8 use this version: https://github.com/eclipse/sumo/blob/master/tests/sumo/cf_model/drive_in_circles/circle_stop_and_go_legacy/input_routes.rou.xml

Please post further questions in #8467 regardless of it's closing status.
