### ISSUE TITLE
extractTest.py cannot handle all option resets

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#8473]
* `{CLEAR -foo 1}` is not supported (only `{CLEAR}`)
*  overwriting the same option with a different value in multiple option files is permitted by texttest but trips up config file create (error: option already set)

**Comment by namdre** [comment]
failing example: tests/sumo/cf_model/drive_in_circles_small/circle_stop_and_go

**Comment by behrisch** [comment]
see also https://github.com/texttest/texttest/issues/65
