### ISSUE TITLE
SUMO-GUI Container Counter

### ISSUE THREAD

**Issue by MelanieWeber** [eclipse/sumo#8479]
![grafik](https://user-images.githubusercontent.com/38243649/114385479-6199d700-9b90-11eb-85ad-9db20783f010.png)
It would be nice, if also container were displayed here.

**Comment by namdre** [comment]
The number '503' with the green edge icon is the container count, I suppose the icon should be improved.

**Comment by namdre** [comment]
@angelobanse would you like to design a new icon?
