### ISSUE TITLE
how to get the route when i use traci.simulation.findRoute

### ISSUE THREAD

**Issue by zhaotuo0815** [eclipse/sumo#8480]
hello,developer,i have some questions when use traci.simulation.findRoute.When i use the traci.simulation.findRoute,which return a 
'Stage' object like(Stage(type=3, edges=('141451700#13', '141451700#14', '425696589#3', '425696586#1', '425696586#2', '452302426#4', '452302426#7', '452302426#8', '452302425#0', '452302425#3', '452302425#4', '452302425#7', '543852190#0', '543852190#1', '543852190#2', '320043270#7', '80727607#2', '80727607#3'), travelTime=192.67745085146024, cost=192.67745085146024, length=4999.549999999999, depart=INVALID, departPos=INVALID, arrivalPos=INVALID)), and  i want to get the edges,so i use traci.simulation.findRoute()[1],but come with TypeError: 'Stage' object is not iterable....
So my questio is  how to get the edges when i use the traci.simulation.findRoute....thank you for your help

**Comment by namdre** [comment]
edges = traci.simulation.findRoute().edges

**Comment by zhaotuo0815** [comment]
thank you so much！



发自我的iPhone


------------------ Original ------------------
From: Jakob Erdmann ***@***.***&gt;
Date: Mon,Apr 12,2021 9:05 PM
To: eclipse/sumo ***@***.***&gt;
Cc: zhao tuo ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [eclipse/sumo] how to get the route when i use traci.simulation.findRoute (#8480)





 
edges = traci.simulation.findRoute().edges
