### ISSUE TITLE
sumo-game release is not working

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#8485]
the extracted version with pyinstaller gives: 
```
ModuleNotFoundError: No module named 'colorsys'
```
The "old" py2exe version 1.8.0 gives
```
Traceback (most recent call last):
  File "runner.py", line 43, in <module>
NameError: name '__file__' is not defined
```

**Comment by behrisch** [comment]
Local run is working here on Windows but may have problems with TK on Linux

**Comment by namdre** [comment]
Working on Ubuntu with python2 and python3 (problem on RHEL due to missing tkinter)
