### ISSUE TITLE
how can i get the all route of  fromEdge toEdge

### ISSUE THREAD

**Issue by zhaotuo0815** [eclipse/sumo#8487]
hello,developer，when i use the traci.simulation.findRoute,which return the fastest route between the given edges,but I do not want this fastest route,so my question is that how can i get the all route when i give the fromEdge and toEdge,thank you for your help！

**Comment by namdre** [comment]
traci does not support this but you can use https://sumo.dlr.de/docs/Tools/Routes.html#findallroutespy

**Comment by zhaotuo0815** [comment]
thank you so much



发自我的iPhone


------------------ Original ------------------
From: Jakob Erdmann ***@***.***&gt;
Date: Tue,Apr 13,2021 11:32 PM
To: eclipse/sumo ***@***.***&gt;
Cc: zhao tuo ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [eclipse/sumo] how can i get the all route of  fromEdge toEdge (#8487)





 
traci does not support this but you can use https://sumo.dlr.de/docs/Tools/Routes.html#findallroutespy
