### ISSUE TITLE
Traffic flow density and flow statistics

### ISSUE THREAD

**Issue by duan-keke** [eclipse/sumo#8495]
When studying the relationship between traffic flow density and flow, the flow is detected by a fixed-point detector, but how is the density obtained? Is it calculated by the time average speed detected by a fixed-point detector, or is it measured by a space detector?

**Comment by namdre** [comment]
density can be estimated as
1. space average (count the vehicles in aerial images)
2. time average (estimate average vehicle spacing at fixed point)
3. time and space average ( sum of travel time divided by observation time and observation space).

Method 2 has problems in higher density (cannot measure headway if traffic isn't moving) so 1 is preferred if you can get it. 3 is the most reliable and you can get it from https://sumo.dlr.de/docs/Simulation/Output/Lane-_or_Edge-based_Traffic_Measures.html#value_descriptions

**Comment by duan-keke** [comment]
> density can be estimated as
> 
> 1. space average (count the vehicles in aerial images)
> 2. time average (estimate average vehicle spacing at fixed point)
> 3. time and space average ( sum of travel time divided by observation time and observation space).
> 
> Method 2 has problems in higher density (cannot measure headway if traffic isn't moving) so 1 is preferred if you can get it. 3 is the most reliable and you can get it from https://sumo.dlr.de/docs/Simulation/Output/Lane-_or_Edge-based_Traffic_Measures.html#value_descriptions

Thank you very much for your reply. Here I would like to ask a question: Based on the establishment of a straight highway without ramps and bottlenecks, the relationship between traffic and density analyzed does not conform to the trend of the normal traffic flow basic graph. How should I adjust What about the parameters?

**Comment by duan-keke** [comment]
> 密度可以估计为
> 
> 1. 平均空间（在航空影像中计算车辆）
> 2. 平均时间（估计固定点的平均车辆间距）
> 3. 时间和空间平均值（行驶时间总和除以观察时间和观察空间）。
> 
> 方法2存在密度较高的问题（如果交通不畅，则无法测量车距），因此，如果可以的话，则首选1。3是最可靠的，您可以从https://sumo.dlr.de/docs/Simulation/Output/Lane-_or_Edge-based_Traffic_Measures.html#value_descriptions获取[](https://sumo.dlr.de/docs/Simulation/Output/Lane-_or_Edge-based_Traffic_Measures.html#value_descriptions)

If I need to get density and flow data at the same time, do I need to set up two detectors (E1+E2) in the same place?

**Comment by namdre** [comment]
The easiest solution is to use edgeData for flow and density since it provides both.

**Comment by namdre** [comment]
>  Here I would like to ask you another question: based on the establishment of a straight highway without ramps and bottlenecks, the relationship between traffic and density analyzed does not conform to the trend of the normal traffic flow basic graph. How should I adjust the parameters?

maybe this helps: 
https://sumo.dlr.de/docs/Tutorials/FundamentalDiagram.html
see also the discussion in #8467

**Comment by duan-keke** [comment]
> 最简单的解决方案是将edgeData用于流量和密度，因为它同时提供了两者。

What if I need to get it online through Python?

**Comment by namdre** [comment]
```
vehPerM = traci.lane.getLastStepVehicleNumber(laneID) / traci.lane.getLength(laneID) 
vehPerS =  vehPerM * tracil.ane.getLastStepMeanSpeed(laneD)
```

**Comment by duan-keke** [comment]
> ```
> vehPerM = traci.lane.getLastStepVehicleNumber(laneID) / traci.lane.getLength(laneID) 
> vehPerS =  vehPerM * tracil.ane.getLastStepMeanSpeed(laneID)
> ```

Thank you very much！

**Comment by MustaphaBichi** [comment]
My question here is; what is the measurement ID, if you want to generate edgeData dump? will it be the edge id, or what?

**Comment by namdre** [comment]
@MustaphaBichi edgeData attribute 'id' is only used to distinguish outputs if there are multiple edgeData defintions. The value is otherwise arbitrary and does not influence written outputs.

**Comment by MustaphaBichi** [comment]
> @MustaphaBichi edgeData attribute 'id' is only used to distinguish outputs if there are multiple edgeData defintions. The value is otherwise arbitrary and does not influence written outputs.

Thank you namdre for your quick response

**Comment by MustaphaBichi** [comment]
> @MustaphaBichi edgeData attribute 'id' is only used to distinguish outputs if there are multiple edgeData defintions. The value is otherwise arbitrary and does not influence written outputs.

I used the code below in my configuration file, but no output file for edgeData generated.

<additional>
	<edgeData id="my_edge01" file="bukitEdge.xml"/>
</additional>

can you help me out?

**Comment by MustaphaBichi** [comment]
> @MustaphaBichi edgeData attribute 'id' is only used to distinguish outputs if there are multiple edgeData defintions. The value is otherwise arbitrary and does not influence written outputs.

@namdre  I used the code below in my configuration file, but no output file for edgeData generated.
   <additional>
	<edgeData id="my_edge01" file="bukitEdge.xml"/>
  </additional>
can you help me out?

<img width="960" alt="2021-04-23" src="https://user-images.githubusercontent.com/80806091/115769090-bb46a080-a3dd-11eb-84a8-972dc7194980.png">

**Comment by namdre** [comment]
get a working example here: https://sumo.dlr.de/extractTest.php?path=sumo/tests/sumo/output/meandata_edgebased/one_vehicle/interval15s60s

**Comment by DryCell-x** [comment]
> ```
> vehPerM = traci.lane.getLastStepVehicleNumber(laneID) / traci.lane.getLength(laneID) 
> vehPerS =  vehPerM * tracil.ane.getLastStepMeanSpeed(laneID)
> ```

what about traffic flow per lane? is there any way we could get in online via python too?

**Comment by namdre** [comment]
sum up the vehicle speeds on the lane and divide by the length of the lane to obtain flow in veh/s

To increase the robustness, compute this sum over multiple simulation steps and also divide by the number of steps.

**Comment by DryCell-x** [comment]
> sum up the vehicle speeds on the lane and divide by the length of the lane to obtain flow in veh/s
> 
> To increase the robustness, compute this sum over multiple simulation steps and also divide by the number of steps.

Thank you very much for your response. 

I have further question for Vehicle density on the edge measurement from : 
https://sumo.dlr.de/docs/Simulation/Output/Lane-_or_Edge-based_Traffic_Measures.html#value_descriptions%E8%8E%B7%E5%8F%96%5B%5D(https://sumo.dlr.de/docs/Simulation/Output/Lane-_or_Edge-based_Traffic_Measures.html#value_descriptions)

For a given density (veh/km) that calculated for certain frequency (let's say = 120 s), the value is averaged for every time step (if the time step is 1s, there will be 120 density data that is going to be averaged) or the calculated value is simply the sum of all 120 density data for each time step ?

**Comment by namdre** [comment]
It's the averaged density over that time period.

**Comment by DryCell-x** [comment]
> It's the averaged density over that time period.

Thank you very much！

**Comment by DryCell-x** [comment]
> The easiest solution is to use edgeData for flow and density since it provides both.

i have another question, which property of edgeData that provide flow measurement? is it the 'left' one?

**Comment by namdre** [comment]
Typically 'entered' and 'left' are used as flow values. These value do not include departed or arrived vehicles so you could also use
entered + departed or left + arrived to include those.
