### ISSUE TITLE
proj.db error on windows

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#8497]
release 1.9.0 prints
```
pj_obj_create: Cannot find proj.db
```
as error output on the console multiple times when loading a geo-referenced network with sumo or netconvert. Functionality doesn't seem to be affected

**Comment by palvarezlopez** [comment]
GDAL 6 searchs proj.db in _SUMO\data\proj\proj.db_, but GDAL 7 searchs proj.db in _SUMO\share\proj\proj.db_

**Comment by behrisch** [comment]
I vote for hotfix, let's discuss it tomorrow. But I don't understand why it works nevertheless.

**Comment by palvarezlopez** [comment]
@behrisch because apparently NETCONVERT doesn't use methods implemented in proj.db

**Comment by behrisch** [comment]
But why do we ship it at all then? Just to get rid of the warning?

**Comment by palvarezlopez** [comment]
Probably there is used, (or will be used in the future), but our test cannot find a use case :-(

**Comment by namdre** [comment]
From looking into proj.db it seems to map from epsg codes to the actual geo-conversion parameters.  Since we hardcode the actual conversion parameters in GeoConvHelper.cpp and our generated osm-derived .net.xml files, our tests work fine.

**Comment by namdre** [comment]
the following call only succeeds if proj.db is found:
`netconvert --osm-files osm_bbox.osm.xml -o epsg.net.xml --proj "+init=epsg:4326 +to +init=epsg:25382"`
(though success is relative because the resulting network still has invalid coordinates despite the code being an example for WGS84->UTM from the proj.org documentation).

I don't think this warrants a hotfix.
