### ISSUE TITLE
A question to connect C to Python client. 

### ISSUE THREAD

**Issue by HawkTom** [eclipse/sumo#8498]
Hello,

Now, I use Python Traci to complete my task. But I have a function which is very time-consuming in Python, so I hope to use C/C++ to program this function. In this function, it need to get some information from SUMO (the travel time between two edges). 

Therefore, I tried the example (https://sumo.dlr.de/docs/TraCI/C%2B%2BTraCIAPI.html#compiling_make_sure_sumo_home_is_set) to try to use C++ connect the sumo-gui created by python by the port. But it failed yo connect the sumo-gui by using the same remote port. 

So, may I ask are there any ways to handle my problem: create sumo-gui in Python and implement a function with traci in C, and  use this function in python.  Thanks. 

Best,
Hao.

**Comment by namdre** [comment]
you can obtain travel time between two edges by calling traci.simulation.findRoute  (the 'cost' attribute of the returned stage object is the travel time). 
The travel time is computed inside sumo (which is written in C++) so there isn't any python-related slowness.
Note, that https://sumo.dlr.de/docs/TraCI/C%2B%2BTraCIAPI.html is obsolete and replaced by https://sumo.dlr.de/docs/Libtraci.html

**Comment by HawkTom** [comment]
> you can obtain travel time between two edges by calling traci.simulation.findRoute (the 'cost' attribute of the returned stage object is the travel time).
> The travel time is computed inside sumo (which is written in C++) so there isn't any python-related slowness.
> Note, that https://sumo.dlr.de/docs/TraCI/C%2B%2BTraCIAPI.html is obsolete and replaced by https://sumo.dlr.de/docs/Libtraci.html

Thanks for your reply. 

Yes, I have found that api (traci.simulation.findRoute).   This is not my problem. 

I created a sumo-gui by python so that python program is a client of sumo.  Now, I want to use a C program to connect this sumo-gui again. I found a parameter about multi-client but it raised an error that each client should be set an order. I set a order in Python, but I don't know how to set the order for C/C++ program. 

By the way, I can't build the c++ exmple in https://sumo.dlr.de/docs/Libtraci.html. It always raised an error that 
```
/usr/bin/ld: cannot find -ltracicpp
collect2: error: ld returned 1 exit status
```

Thanks.

**Comment by HawkTom** [comment]
> you can obtain travel time between two edges by calling traci.simulation.findRoute (the 'cost' attribute of the returned stage object is the travel time).
> The travel time is computed inside sumo (which is written in C++) so there isn't any python-related slowness.
> Note, that https://sumo.dlr.de/docs/TraCI/C%2B%2BTraCIAPI.html is obsolete and replaced by https://sumo.dlr.de/docs/Libtraci.html

In addition, the slowness is not caused by sumo api, but caused by my own program.  I want implement them by C/C++ to speed up. But this program contains traci.simulation.findRoute, so I have to call this function in C/C++ program.

**Comment by namdre** [comment]
libtraci provides the commands
`Simulation::findRoute` and `Simulation::setOrder`

the example code assumes that the sumo/bin folder contains `libtracicpp.so`. This should be the case if you have compiled sumo.

**Comment by HawkTom** [comment]
> libtraci provides the commands
> `Simulation::findRoute` and `Simulation::setOrder`
> 
> the example code assumes that the sumo/bin folder contains `libtracicpp.so`. This should be the case if you have compiled sumo. Also, environment variable `SUMO_HOME` must point at the sumo folder which contains `bin`.

So, if I want to run the example code, I have to complied the sumo by myself?

**Comment by namdre** [comment]
on Linux, yes.

**Comment by HawkTom** [comment]
Hello,

accutally, I want to obtain the travel time of a lot of edge pairs (about 40000 pairs). If I use findRoute() in Python, it will consum about 108 seconds. Do you know if it has some quick methods to complete this tasks. I have tried the multiprocess in Python, but the traci seems that can't be used in mutli-process. 

Thanks.

**Comment by namdre** [comment]
- if the pairs have only a small number of origin edges (one-to-many routing) the fastest way is to generated an input file of trips for duarouter and run this with option **--bulk-routing**. Then parse the costs from the generated .rou.alt.xml output file
- otherwise you can speed up traci.simulation.findRoute by setting sumo option **--routing-algorithm CH**. (Use 'CHWrapper' for multi-modal routing).

**Comment by HawkTom** [comment]
> * if the pairs have only a small number of origin edges (one-to-many routing) the fastest way is to generated an input file of trips for duarouter and run this with option **--bulk-routing**. Then parse the costs from the generated .rou.alt.xml output file
> * otherwise you can speed up traci.simulation.findRoute by setting sumo option **--routing-algorithm CH**. (Use 'CHWrapper' for multi-modal routing).
 
Thanks,

I have 40000 pairs (200 edges times 200 edges.)

**Comment by namdre** [comment]
then bulk-routing (with dijkstra) should be faster

**Comment by HawkTom** [comment]
> * if the pairs have only a small number of origin edges (one-to-many routing) the fastest way is to generated an input file of trips for duarouter and run this with option **--bulk-routing**. Then parse the costs from the generated .rou.alt.xml output file
> * otherwise you can speed up traci.simulation.findRoute by setting sumo option **--routing-algorithm CH**. (Use 'CHWrapper' for multi-modal routing).

I have tried the second methods you provide. The time has been reduce to 20 seconds. Very Excellent!!! 
For the first method(duarouter), is that mean we need to creat a trip file for each origina edges? Or we can just put all trips in a same file.

**Comment by namdre** [comment]
all trips in the same file

**Comment by HawkTom** [comment]
> then bulk-routing (with dijkstra) should be faster

Ok, thanks.  Let me have a try.  Can I call the duarouter from the Traci or only can call from the command line?

**Comment by namdre** [comment]
you can use subprocess.call(['duarouter', ....]) from your traci script. For parsing the output, see https://sumo.dlr.de/docs/Tools/Sumolib.html#parse_vehicles_and_their_route_edges_in_a_route_file

**Comment by HawkTom** [comment]
> > then bulk-routing (with dijkstra) should be faster
> 
> Ok, thanks. Let me have a try. Can I call the duarouter from the Traci or only can call from the command line?

Thanks for your so quick reply, but I just see it in the tutorial. It must be executed on the command line.  😄 

One more question, I found that the input must have network and demand.  But I want to calculate the traveltime during the simulation. For example, the vehicles have started their routes for a period time and then, I want to calculate the travel time in current time. Is that possible to complete this by  duaroute？

**Comment by namdre** [comment]
Yes. Duarouter can load a "weight-file" that captures that current travel times in the network. You can prepare such a weight file by retrieving current travel speeds from the simulation and then computing the travel time from that. Note, that edge.getLastStepMeanSpeed averages over all vehicles but doesn't average over time. For alternatives, see 
https://sumo.dlr.de/docs/Demand/Automatic_Routing.html#edge_weights
https://sumo.dlr.de/docs/Demand/Automatic_Routing.html#traci
