### ISSUE TITLE
vehicles ignore connection permissions

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#8499]
network defines two left turns (direct and indirect) and tries to enforce distinct usage for passenger and moped traffic via connection permissions. However, both classes use both connections.

**Comment by namdre** [comment]
#6210 should have made this work but somehow the 'universalMap' branch is entered even though it should not happen

**Comment by palvarezlopez** [comment]
@namdre do you remember this change?

a16cd326e619a56590bfedf14ec933fe4bfd558a

**Comment by namdre** [comment]
> @namdre do you remember this change? [a16cd32](https://github.com/eclipse/sumo/commit/a16cd326e619a56590bfedf14ec933fe4bfd558a) It could be related?

This is completely unrelated
