### ISSUE TITLE
Will the CACC vehicles accelerate or brake at maximum acceleration or deceleration?

### ISSUE THREAD

**Issue by gaofenxia** [eclipse/sumo#8503]
During the simulation, I found that CACC vehicles will brake suddenly at the maximum deceleration when braking, and accelerate suddenly at the maximum acceleration when starting, while IDM vehicles will be more gentle. Compared with IDM vehicles, CACC vehicles does not conform to the actual situation. So, will the CACC vehicles accelerate or brake at maximum acceleration or deceleration?

**Comment by namdre** [comment]
The CACC model was designed for simulations with low step-length (0.1 or lower). To reduce the number of collisions when running with high step length (i.e. the default of 1s) an override was added that allows braking with higher deceleration in situations deemed unsafe. Try lowering the step length.
Acceleration is maximal when there is no leading vehicle (the CACC model falls back to the default model if there is no leader vehicle). 
Note, that the CACC model was added to SUMO by a third party and doesn't claim to replicate a specific brand of CACC functionality. It's just a linear speed control model with a name that is maybe too generic and thus causes people to think that it's a definitive model of how CACC works.
