### ISSUE TITLE
randomTrips.py generating exactly the same outputs

### ISSUE THREAD

**Issue by a-huk** [eclipse/sumo#8506]
I am working on VANETs and AODV. As part of my work, I need to run the same scenario in omnet++ a number of times, with different car movement each time. I use a custom downtown Manhattan map: manhattan.net.xml (see it attached).

To accomplish my goal I first generate trips via randomTrips.py with the following command: `python3 /home/hukad/tools/sumo/tools/randomTrips.py -n manhattan.net.xml -e 50 -o manhattan.trips.xml`

I have noticed that the trips and files are completely identical. In turn, routes generated via duarouter will in turn be the same.Could I get a confirmation of this issue?
[manhattan.zip](https://github.com/eclipse/sumo/files/6325683/manhattan.zip)

**Comment by namdre** [comment]
Reproducibility is a feature. You can set randomoTrips option **--seed** to get a different (reproducible) random output or option **--random** to use a completely random seed.

Also, you can set duarouter option **--weights.random-factor** (with **--seed** / **--random**) if you want more variability in routes.
