### ISSUE TITLE
Impatience and ArrivalTime with the junction model

### ISSUE THREAD

**Issue by Domsall** [eclipse/sumo#8507]
I am using one of the Sumo-Carla examples with an own set of vehicle types. I normally use the impatience parameter (somewhere between 0.3 and 0.7), but then started to realize that vehicles emergency brake at junctions. I found out that the following Code Line is the reason.
When the vehicles arrive at the junction, they check the `arrivalTime` of the other foes. When I use impatience, a portion of the `arrivalTimeBraking` is used, but this parameter is as commented "arbitrarily large". This changes when the foe vehicle can't brake hard enough anymore (seen < cfModel.brakeGap(v)). Then `arrivalTimeBraking` becomes a reasonable value. It then happens that the original vehicle now recognizes, that it won't make it over the junction in time and brakes hard. Is there a reason, that `arrivalTimeBraking` isn't always calculated as in the if-clause? It also says in the comment, that "A small value keeps fractional times (impatience) meaningful". Or is there a better way to treat this problem (maybe some kind of other parameterization)? I actually like the impatience parameter because it accounts for aggressive drivers.

https://github.com/eclipse/sumo/blob/924528fe275e818fb2ac5a0d0de333d9a081bf22/src/microsim/MSVehicle.cpp#L2541

The example:
[examples.zip](https://github.com/eclipse/sumo/files/6326793/examples.zip)

**Comment by Domsall** [comment]
Because of all the work you have going, this issue maybe fell into oblivion. I am going to add another Code Line where the emergency braking originates from:

https://github.com/eclipse/sumo/blob/924528fe275e818fb2ac5a0d0de333d9a081bf22/src/microsim/MSLink.cpp#L672

I do not have any problems when simulating with `impatience=0`. But when I have `impatience>0`, `arrivalTimeBraking` comes into account and lets the ego-vehicle ignore a foe vehicle until the last moment.

**Comment by namdre** [comment]
arrivalTime braking is the time at which the foe vehicle reaches the junction when braking hard (with decel). If it can stop before the junction then this value is infinity.  I think this is somewhat useful if you want vehicles to cut in and force the other guy to brake and this feature would be lost with a smoothed arrivalTimeBraking.

I think the real issue is somewhere else.

Currently, the ego vehicle is asking:  
   (a) "could the foe vehicle brake enough if I enter the junction right now?"
What it should be asking is: 
   (b) "could then foe vehicle brake if I keep driving until I enter the junction and the foe starts braking at that time?"

The latter condition doesn't lead to jump in the "can drive/cannot drive evaluation" if the ego can predict it's on arrival accurately (or use an upper bound that approaches the real time as it gets closer)
The distinction is mostly moot in step-length=1 simulations but it becomes of critical importance at sub-second simulation. 

The problem with (b) is that we need the arrivalTimeBraking as a function of ego-junction-entry time rather than as a constant. However, we can just compute it as needed in MSLink based on foe speed and distance.

**Comment by Domsall** [comment]
I am a bit confused. Does the `arrivalTimeBraking` have to be unreasonable high for other foes to cut in? My example:

- ego vehicle has leave time 00:00:20 (+ lookAhead = 00:00:21)
- foe with right of way has arrival time 00:00:20
- with `impatience=1`, foe has arrival time 00:00:50 (00:00:20 + 00:00:30 = `arrivalTimeBraking`)
- The ego vehicle keeps the 00:00:50 arrival time until the foe vehicle can't brake in time anymore (seen < cfModel.brakeGap(v))
- Then suddenly the foes arrival time jumps to e.g. 00:00:21 --> The ego vehicle makes an emergency brake

This happens with various impatience values (for impatience=0.5, the arrival time is then 00:00:35).

From my understanding, I would assume that an ego vehicle with `impatience=0.5` would force a foe with right of way to brake a little less than with `impatience=1.0`. I wouldn't change the current implementation much, I think it works great, even if it works as (a). 

My suggestion was: 
Instead of `30.0s`, to use a value that maybe calculates the time the vehicle takes to come to a standstill at the stop line when decelerating with a constant value right away (`arrivalTimeBraking`), instead of driving over the junction (`arrivalTime`).
For example the way `arrivalTimeBraking` is already calculated right now: `t_brake=2*gap/v`.
When the vehicle reaches the critical distance `cfModel.brakeGap(v)`, `arrivalTimeBraking` could then smoothly go over into the current calculation and would not jump. 

I do understand the critical difference between second simulationsteps and sub-second simulationsteps, as `arrivalTimeBraking` could then only be slightly higher than `arrivalTime`. But even with a smoothed `arrivalTimeBraking`, I assume that vehicles with higher impatience would still drive more aggressive than others.
I'll do some tests with different equations and simulation steps and check if my assumptions hold.

**Comment by namdre** [comment]
The problems isn't limited to subsecond simulation. I just manged to reproduced it at step-length=1 by increasing the visibility distance.  Stronger-than-desired braking occurs when the following conditions are met:

at step 1:
- the foe vehicle can still brake before the stop line it it were to brake right now
- the ego vehicle is impatient and accelerates towards the junction but cannot reach the stop line in 1 step
at step 2
- the foe vehicle can no longer brake before the stop line (it keeps moving since ego isn't on the junction yet)
- the ego vehicle is also too fast to brake before the stop line with normal deceleration

This situation will still be possible with a smoothed arrivalTimeBraking since there is always a point where the foe vehicle cannot brake anymore (transition form step 1 to step 2). In my understanding, the only solution is to make the ego vehicle consider the time at which the foe vehicle can actually react.

**Comment by Domsall** [comment]
Thank you very much for the detailed explanations, they always help a lot to understand the full problem.

I changed the Code a bit and created a "minimal proposal patch", which I hope goes in the correct, problem solving direction.
I tested it with my example scenario and the two scenarios you created. It worked good and as expected, but it needs some kind of "default time parameter":

[Impatience_minimal_proposal.txt](https://github.com/eclipse/sumo/files/6672906/Impatience_minimal_proposal.txt)

It works as follows: 
- Instead of using the `arrivalTimeBraking` value to compute the time the vehicle will take to reach the junction if it brakes (hard), I use it to capture the time the vehicle will take to reach the "point of no return" (cfModel.brakeGap(v)).
- The ego vehicle then compares the `arrivalTimeBraking` value of the foe with ego's `arrivalTime` value. If the ego can arrive at the junction before the foe needs to start an emergency brake, it is "safe".
- Depending on a default time and with higher impatience, the ego vehicle would disregard this "safe state" and could therefore force the foe to brake.
- With `impatience=0.0`, the calculation should not change from the previous one.

2 issues:
- I do not think I am using the correct arrivalSpeed (see comments) and I am not sure, if `DELTA_T` needs to be subtracted as with `arrivalTime`
- I did some tests with the time `lookAhead + TIME2STEPS(4.0)` and this works good, but it is just a "good guess"

**Comment by Domsall** [comment]
To give this issue a bump, I will add a bit more text to the patch. I would love to get some (even short) feedback. Maybe the patch/idea is not so good as I thought.

- As stated above, I changed the `arrivalTimeBraking` meaning. This could brake other calculations, where `arrivalTimeBraking` is used. But as far as I could understand, this value is only used for the blockedByFoe-function (and impatience>0.0).
> * Instead of using the `arrivalTimeBraking` value to compute the time the vehicle will take to reach the junction if it brakes (hard), I use it to capture the time the vehicle will take to reach the "point of no return" (cfModel.brakeGap(v)).
- For the second part, I tried to change the else-if clause "_ego wants to be leader_" in blockedByFoe to what you stated above:
> * (b) "could then foe vehicle brake if I keep driving until I enter the junction and the foe starts braking at that time?"

The destinction then is:

- If the ego can leave the junction before the foe enters (`avi.arrivalTime > leaveTime + lookAhead`), it will drive onto the junction (always safe, impatience=0.0)
- If we have impatience=1.0, the ego will still drive onto the junction (arrrivalTime), if the foe can still brake in time (`avi.arrivalTimeBraking > arrivalTime`)
- If we have 0.0<impatience<1.0, something in between should occur, like `avi.arrivalTimeBraking > arrivalTime + (lookAhead + timeNeededToClearJunction) * (1.0 - impatience)` (where arrivalTime+timeNeededToClearJunction is probably ~leaveTime)

**Comment by Domsall** [comment]
@namdre Shall I create a pull request with the proposal from above? Is it easier and faster for you to then discuss the rest there?

**Comment by namdre** [comment]
Thanks for giving this a bump since it kept falling through the cracks. I'll take a look at your patch now and then try to give feedback. Do you have additional (small) tests that would be useful to validate the desired behavior (whatever it turns out to be)?

**Comment by namdre** [comment]
- I think the idea of repurposing avi.arrivalTimeBraking as the "point of no return" is good
  - computing this from the average of `v` and `arrivalSpeed` doesn't seem accurate enough though
- I'd prefer to compute an arrivalTimeBraking (in the original meaning) within `blockedByFoe` and keep the old impatience interpolation. As far as I understand your formula for *ego wants to be leader*, it doesn't guarantee that the foe only has to brake at impatience > 0 (i.e. if ego is slow and blocks the junction for a long time)
- there are some issues with comparing a sub-second arrivalTime of with the new arrivalTimeBraking at 1-second steps that I want to fix

**Comment by Domsall** [comment]
I unfortunately was busy after you wrote the message and am now replying after you made the changes.

Your modifications already look great and solve the issues I was facing with my implementation. The minimum patch just solved the problem of emergency braking ego vehicles when encountering a foe (solved both tests). The second issue (accurate calculation of arrival times) was not fixed and ego vehicles did not force themselves in front of foes (even with impatience=1). 
I still have some remarks:

- Calculating arrivalTimeBraking as "point of no return" in MSVehicle works great. Back then I just was not sure if `(seen - bGap) / ((v + arrivalSpeed) * 0.5)` **OR** `(seen - bGap) / ((v + v) * 0.5)` is better. What velocity will the vehicle approx. have at bGap? I assume that arrivalSpeed is the speed at the junction, not at bGap?!
- Regarding blockedByFoe: I got rid of the interpolation, because avi.arrivalTime was then higher than avi.arrivalTimeBraking, which did not make sense anymore. For impatience=0, the _ego wants to be leader_ part (almost) did not change. I later recognized that the default `4s-timeNeededToClearJunction` variable can be replaced by `leaveTime-arrivalTime`, which then ensures the old behavior. Nevertheless, you added the missing part for comparing arrivalTime with arrivalTimeBraking -> calculating the arrival time when braking with `computeFoeArrivalTimeBraking`. That works perfectly with the interpolation again.

The only part I do not understand is the if-clause with `(0.5 * v * v / m <= dist2)` and the resulting output with `return foeArrivalTime + TIME2STEPS(30);`. I first thought this would bring back the emergency braking, but it did not. I varied depart times/positions and it worked perfectly in all cases.

Do you still need another test?
The test results with the above tests are:

- Old implementation: ego braking hard (emergency)
- minimal proposal: ego braking smoothly
- your extensive fix: ego cutting in before foe (with parameter variation smooth braking of ego)

**Comment by namdre** [comment]
The key difference is that the old implementation basically applied `30 * impatience` to the foeArrivalTime. Often, small impatience values (i.e 0.1) were quite enough to make the ego cut it.
Now, impatience is applied to to the foe deceleration (i.e. at impatience 0.5 ego, can force the foe to brake with at most half of its `decel` value). This makes the whole range of impatience values relevant (With the downside of changing lots of tests). To compensate for the delayed impact of impatience, I also reduced default **--time-to-impatience** from 300s to 180s.

Now here is a funny thing: with the new computation, the value of `avi.arrivalTimeBraking` isn't used anymore. It all boils down to solving a small quadratic formulate in (almost) all cases.
We still need to check whether the foe can brake to a stop with the desired deceleration level (which depends on ego impatience and this isn't available in the planMove step of foe). This is accomplished by `0.5 * v * v / m` (the formula for braking distance).

**Comment by Domsall** [comment]
As always, I can't thank you enough for the well thought through fix.
