### ISSUE TITLE
parse_fast_nested has problems when an element is missing some of the attributes to be parsed

### ISSUE THREAD

**Issue by ArmelliniMG** [eclipse/sumo#8508]
sumolib.xml.parse_fast_nested retrieves child elements of elements that were not parsed correctly and associates that child with the previous element.
This leads for example to errors when parsing ptLines from OSM, which can sometimes have some missing attributes.

For example:
```
<ptLines>
    <ptLine id="0" name="bus0" line="line0" type="bus">
        <route edges="edge0"/>
    </ptLine>
    <ptLine id="1" line="line1" type="bus">
        <route edges="edge0 edge1"/>
    </ptLine>
    <ptLine id="2" name="bus2" line="line2" type="bus">
        <route edges="edge0 edge1 edge2"/>
    </ptLine>
</ptLines>
```

Since ptLine id="1" has no **name** attribute, the output from: 
parse_fast_nested("File", "ptLine", ("id", "name", "line", "type"),  "route", "edges") is:
0 bus0 line0 bus
-> edge0
_**0 bus0 line0 bus
-> edge0 edge1**_
2 bus2 line2 bus
-> edge0 edge1 edge2

**Comment by namdre** [comment]
The fix is good but if you need to handle elements with missing attributes, it's better to use sumolib.xml.parse(heterogeoneous=True, ...) instead of parse_fast / parse_fast_nested

**Comment by namdre** [comment]
The fix broke parsing of files with intermediate ignored lines (i.e. vehicles with route within routeDistribution)
