### ISSUE TITLE
How to get "risk lanes" and what are the outputs of traci.lane.getLinks(laneID)?

### ISSUE THREAD

**Issue by philippwulff** [eclipse/sumo#8509]
I have a number of questions about methods concerning foes in TraCI and Sumolib methods. 

1.  `traci.lane.getFoes(lane_id, to_lane_id)` returns the lane ids that have right of way over the given connection [(documentation)](https://sumo.dlr.de/pydoc/traci._lane.html#LaneDomain-getFoes). Is there also a way for getting all ids of incoming lanes which "conflict" with the connection from `lane_id` to `to_lane_id`? By "conflict" I mean, that vehicles coming from the other lane could crash into vehicles travelling on the described connection if they would ignore the right-of-way-traffic-rules. I noticed that `sumolib.net.node.areFoes(self, link1, link2)` ([from the sumolib docs](https://sumo.dlr.de/pydoc/sumolib.net.node.html)) returns whether two lanes "conflict" with each other in such a way and I can use this, but is there a more elegant solution that I don't know of?
2. `traci.lane.getLinks(laneID)` has multiple return values ([docs](https://sumo.dlr.de/pydoc/traci._lane.html#LaneDomain-getLinks)). Could you please clarify what `bool isOpen` means? I also noticed that `bool hasFoe` is `True` when there is a vehicle one of the lanes returned by `getFoes(from_lane_id, to_lane_id)` in a certain distance to the junction. What is the boundary value of this distance? The value was also `True`, when a vehicle was blocking the link/connection. Is this observation for `hasFoe` correct? My last question is about the value of `hasPrio`. This value is `True`, when the edge has the highest priority of the junction's incoming lanes and when the junction type is "priority", right? 

Thanks!

**Comment by namdre** [comment]
1) you can use lane.getInternalFoes to retrieve all internal lanes that conflict in the manner you describe. Using lane.getLinks you can obtain a mapping of incoming lane, target lane and internal lane id

2) see 6e0ee18fd33f0b817dcd210c0e71153cafdbed19 and #8510
