### ISSUE TITLE
Sumo crash: Received FatalTraciError 'connection closed by SUMO'

### ISSUE THREAD

**Issue by philippwulff** [eclipse/sumo#8511]
I assume these errors/ crashes with `UserWarning: Received FatalTraciError 'connection closed by SUMO'` are because of bugs, right?
I created the traceFile for all the TraCI commands and attached it with the necessary input files below.

[fatal_traci_error.zip](https://github.com/eclipse/sumo/files/6331519/fatal_traci_error.zip)

**Comment by namdre** [comment]
I can reproduce the crash (though not in every run). Note that your traceFile still suffers from #8491 so I recommend that you upgrade.

**Comment by namdre** [comment]
can you confirm that this only shows up with sumo-gui? I cannot replicate it with 'sumo'

**Comment by philippwulff** [comment]
Oh sorry, maybe I ran another traceFile yesterday, when I wanted to check if it reproduces the error. I also only receive the error with `sumo-gui` and not on every run.

**Comment by namdre** [comment]
Thanks for the report!

**Comment by vitessel** [comment]
I am sorry for the dumb question, but where do you find the traceFile?

**Comment by namdre** [comment]
@vitessel  see  https://sumo.dlr.de/docs/TraCI/Interfacing_TraCI_from_Python.html#generating_a_log_of_all_traci_commands
