### ISSUE TITLE
Better way to get info about one or some given sub-type(s) in Polyconvert? 

### ISSUE THREAD

**Issue by yunpangfloetteroed** [eclipse/sumo#8512]
It seems that each other sub-type definition needs to be discarded specifically if only one sub-type information is needed. Should we have a better way to deal with it?

E.g. Given only <polygonType id="admin_level.10" name="admin_level" color="1.0,.33,.33" layer="0" fill="false" discard="false"/> the information for all admin_levels is still written in the given output file. Currently, Each other admin_level needs to be specifically discarded in a *typ.xml for only getting the information about admin_level.10

**Comment by namdre** [comment]
A typemap like this works fine:
```
<polygonType id="admin_level"             name="admin_level" color="1.0,.33,.33" layer="0" fill="false" discard="true"/>
<polygonType id="admin_level.10"             name="admin_level" color="1.0,.33,.33" layer="0" fill="false" discard="false"/>
```

**Comment by behrisch** [comment]
Can we also discard everything by default and only output the needed subtypes?

**Comment by namdre** [comment]
Then how would you discover exciting new types added to the OSM database?
It's trivial to get a discard-everything typemap based on the default.

**Comment by yunpangfloetteroed** [comment]
@Micha: sorry for the wrong information before. I looked the buidling defaults and there is an option--discard. With it everything can be discarded.
