### ISSUE TITLE
osmWebWizard.py: Error when importing corrdinates with a negative latitude. 

### ISSUE THREAD

**Issue by pyrosnowman24** [eclipse/sumo#8521]
The osmWebWizard.py gives the following error when attempting to import an area with a negative latitude:

> Building scenario in '.../2021-04-20-11-32-49'
> Downloading map data
> usage: osmWebWizard.py [-h] [-c FILE] [-C FILE] [--save-template FILE]
>                        [-p PREFIX] [-b BBOX] [-t TILES] [-d OUTPUT_DIR]
>                        [-a AREA] [-x POLYGON] [-u URL] [-w]
> osmWebWizard.py: error: argument -b/--bbox: expected one argument

This error occurs when attempting to convert an area based on the coordinates [34.746480 -92.289595] using the following SUMO build:

> Eclipse SUMO sumo Version 1.9.0
>  Build features: Linux-4.15.0-141-generic x86_64 GNU 9.3.0 Release Proj GUI SWIG GDAL GL2PS
>  Copyright (C) 2001-2021 German Aerospace Center (DLR) and others; https://sumo.dlr.de
>  License EPL-2.0: Eclipse Public License Version 2 <https://eclipse.org/legal/epl-v20.html>
>  Use --help to get the list of options.

**Comment by behrisch** [comment]
Thanks for finding this one! This means the webWizard in 1.9.0 is not going to work for anyone west of Greenwich! (It is probably a fall out of tool  refactoring to use the new ArgumentParser.)

**Comment by namdre** [comment]
I can confirm that importing from Ireland was working with 1.8.0 but fails with 1.9.0

**Comment by behrisch** [comment]
I am not sure whether negative longitude is affected as well. Probably only the first coordinate (latitude) matters.

**Comment by namdre** [comment]
longitude is the east-west coordinate and thus concerns west-of-greenwhich issues such as Ireland (which I tested).
For maximum confusion, the web standard is lat,lon but osmGet uses lon,lat,lon2,lat2 for the bounding box.
I can confirm that Madagascar is working fine in version 1.9.0 (positive lon, negative lat)
