### ISSUE TITLE
Code bug in MSMeanData.cpp

### ISSUE THREAD

**Issue by lccycc** [eclipse/sumo#8522]
On Line 99:
https://github.com/eclipse/sumo/blob/5219d47f05ae788b03e3482a1bae400df37616cf/src/microsim/output/MSMeanData.cpp#L99

On line 140:
https://github.com/eclipse/sumo/blob/5219d47f05ae788b03e3482a1bae400df37616cf/src/microsim/output/MSMeanData.cpp#L140
----
It didn't handle the case where newPos == myLaneLength.

My simulation is failing the later assert on this rare case. To be consistent I would suggest changing Line 99 from

> newPos < myLaneLength ? TS : 0.; 

To 
> newPos <= myLaneLength ? TS : 0.;

**Comment by behrisch** [comment]
Thanks for finding this one! The idea for the fix sounds very plausible. I will check whether it changes any of our tests.
