### ISSUE TITLE
Questions for lane changing rule

### ISSUE THREAD

**Issue by Shiyunyang-seu** [eclipse/sumo#8527]
Hi ：
      We noticed that during the operation of Sumo, for this kind of dead-end lane

(No connection), the car will change lanes in advance. The text description is at the following address:

https://sumo.dlr.de/docs/Simulation/Motorways.html#building_a_network_for_motorway_simulation . We want to learn more about how this lane changing rule works. For example, how many meters will the car realize that it needs to change lanes in advance?
![Q1](https://user-images.githubusercontent.com/55737075/115532263-36b62e00-a2c8-11eb-84ed-d3b6c9a59247.jpg)

Thank you very much for seeing my question and looking forward to replying.

**Comment by namdre** [comment]
see https://elib.dlr.de/102254/
