### ISSUE TITLE
Junction "collision" and Turning Angles with lcSigma

### ISSUE THREAD

**Issue by Domsall** [eclipse/sumo#8529]
I have 2 issues which occur with the sublane model. When simulating solely with sumo, these issues don't really matter, but I'm having problems converting the vehicle trajectories to Carla. I added 2 sumo-configs as examples:

[JunctionAngleTurning.zip](https://github.com/eclipse/sumo/files/6353081/JunctionAngleTurning.zip)

First, the vehicles drive to far onto some junctions and therefore create collisions in an 3D-environment (SUMO real-world viewing). Is this something, that can be dealt with better parameters or junction layout? Or is this something that can/should be changed in the Code?!
And secondly, I simulate with lcSigma > 0 to have some kind of "unperfect lane keeping". This works well, despite the fact that vehicles then don't turn so nicely on the junctions anymore. With lcSigma=0, the vehicle angles get updated continuously, which looks perfect.

Thanks in advance!!!

**Comment by namdre** [comment]
regarding "driving to far onto the junction". This is likely a case of  #4397 and can be fixed manually by moving the internal junction back (connection attribute contPos).

regarding the angles: it would be great if you could prepare a set of small tests that showcase the difference between the current and your proposed angle calculation.

**Comment by Domsall** [comment]
No problem at all, you can't do everything ;-)

what do you have in mind when refering to tests? Short video clips?

I was also thinking of updating the slope calculation similar to the angle calculation (front and back position), because when using the slope for vehicle resistance calculation or when using SUMO in a co-simulation framework, small z-differences can have a huge impact on the slope when points lie close to eachother.

**Comment by namdre** [comment]
patch format is what you get with `git diff src > myPatch`

**Comment by Domsall** [comment]
The Patch:
[AnglePatch.zip](https://github.com/eclipse/sumo/files/6465726/AnglePatch.zip)

And 4 sumocfg-Files including lane changes + junction turns with LC2013/SL2015, each with vehicles types with lcSigma>0 and lcSigma=0.

[JunctionAngleTurning_4sumocfgs.zip](https://github.com/eclipse/sumo/files/6465994/JunctionAngleTurning_4sumocfgs.zip)

**Comment by namdre** [comment]
I think i've found another issue with angle calculation that can only be fixed by considering the history of the maneuver.
Consider a vehicle that turns in a tight circle (i.e. to change lane when close to an obstacle)
- the forward speed will be quite low (maybe 0)
- the lateral speed may also be low in each step
- however, the angle should keep increasing during the maneuver rather than stay constant.

The idea of using to points like in MSVehicle is useful here. The solution then is to store the lateral position of the vehicle back from the start of the maneuver and only update it in relation to the forward speed. This way, the angle keeps changing as the  lateral position (of the vehicle front) changes.

**Comment by Domsall** [comment]
Your are right, low values are an issue, especially when the lateral speed and the forward speed have no physical coupling.

I wanted to create a small patch, which uses a kind of single track model, but with beta=0 ("Schwimmwinkel"). This can be done with some assumptions, but then the model has a singularity at 0m/s. That is why I tried to make sure that this case does not occur. So the forward speed got a lower bound of 1m/s, which creates weird/wrong angles at very low speeds.

I think what you are now refering to is to use some kind of beta slip angle. With beta=0, the angle of the vehicle should exactly be the driving direction (atan(lateral_v / forward_v)).

To your point: If the forward speed and the lateral speed stays constant, even if low, I would assume the angle would also be constant. One could ramp up the lateral speed (bound the lateral acceleration) for a changing angle in this scenario. At low speeds beta is also very low. I think the angle only changes smoothly in the real world, because of this "ramp up of lateral speed" and changing tire angles during the maneuver.

**Comment by Domsall** [comment]
> I think i've found another issue with angle calculation that can only be fixed by considering the history of the maneuver. Consider a vehicle that turns in a tight circle (i.e. to change lane when close to an obstacle)
> 
> * the forward speed will be quite low (maybe 0)
> * the lateral speed may also be low in each step
> * however, the angle should keep increasing during the maneuver rather than stay constant.
> 
> The idea of using to points like in MSVehicle is useful here. The solution then is to store the lateral position of the vehicle back from the start of the maneuver and only update it in relation to the forward speed. This way, the angle keeps changing as the lateral position (of the vehicle front) changes.

Correct me, if I am wrong.
My idea would produce something like this:
![Slide1](https://user-images.githubusercontent.com/53042793/194580985-61b5f25e-7368-443c-b83b-c49b6dc237c2.PNG)

And you are looking for something like this:
![Slide2](https://user-images.githubusercontent.com/53042793/194581013-522586ed-654c-4134-b872-cfdbaa6bb16f.PNG)
