### ISSUE TITLE
increase edge probability in randomTrips by priority

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#8530]
having two edges of equal lane count (and length, maxSpeed) randomTrips has currently no way of deciding which to prefer. Usually you would expect more traffic on the higher prioritized road. The problem is to find a good factor here.

**Comment by namdre** [comment]
Of course I'm in favor of adding more options.
I just want to note that
- option **--edge-param** allows adding custom scaling on top of the other factors
- lane count and speed should be correlated with priority
- higher traffic does not equate to higher probability of being an origin or destination. Cars usually don't start their trip on a motorway (unless it's fringe) whereas the low-priority residential roads are an obvious origin point. Hence the option **--via-edge-types**.

**Comment by behrisch** [comment]
Short answers to the remarks:

- Yes, but edge-param only evaluates `<param ../>` entries or should we extend it to attributes as well? And it is only linear
- I noticed that and in fact speed may be sufficient in our case
- The test case had a high priority fringe which was not used. do we want to duplicate all scaling options for fringe and no-fringe or what would be a good approach?

**Comment by namdre** [comment]
Usually, setting a high fringe factor should ensure that the fringe is used. 
If some inner edges are wrongly classified as fringe than i'd rather solve this with node attribute fringe (#4382)
There may be some other issue at play though.

**Comment by behrisch** [comment]
In our case there were several low speed (and low prio) fringe edges connected to a high speed/prio fringe edge and we want to give the latter higher priority

**Comment by namdre** [comment]
I think it might be more useful to apply a priority-based factor only for fringe edges rather than for all edges. It still somewhat difficult to get the scaling factor right since the default priorities for our osm typemap were never intended to be proportional to something (though you might as well modify the typemap values when needed for this).

**Comment by behrisch** [comment]
It is hard to get this calibrated anyway and in principle we even need to deal with negative priorities. So if we can solve the current problem with speed-exponent I would probably change my mind on this ticket

**Comment by behrisch** [comment]
a speed exponent for fringe only might be a good solution as well

**Comment by behrisch** [comment]
normalising prios is also an idea

**Comment by behrisch** [comment]
priority is not "well defined" so it is hard to give a good solution here
