### ISSUE TITLE
Cannot open sumo-gui in Mac Big-sur (11.1)

### ISSUE THREAD

**Issue by yuanjian24** [eclipse/sumo#8532]
Hi, I am installing sumo on my mac following this [web:](https://sumo.dlr.de/docs/Installing/index.html#macos)
After running `touch ~/.bashrc; open ~/.bashrc`, I find my script is **blank**, so I just added `export SUMO_HOME=/usr/local/opt/sumo/share/sumo` on it.

Then, I ran `echo $SUMO_HOME`, however, I got no feedback.

Finally, I ran `sumo-gui`, and got this feedback: 
`FXApp::openDisplay: unable to open display :0.0`

I am sure I followed every step on the documentation, how can I fix it? 

Thanks!

**Comment by angelobanse** [comment]
possibly related to #8208

**Comment by yuanjian24** [comment]
> possibly related to #8208

Thank you, this error turned out to be my incorrectly running of `sumo-gui` on the MAC terminal. 
It works well on the terminal of XQuartz.

**Comment by angelobanse** [comment]
you should also be able to open `sumo-gui` using the macOS terminal...
which shell are you using on your mac? bash or zsh?

**Comment by yuanjian24** [comment]
Oh okay..., I am using bash now.
Will it affect the basic functions of SUMO?

**Comment by angelobanse** [comment]
No.

Did you follow this step, mentioned in the documentation? 👇 
> After the installation you need to log out/in in order to let X11 start automatically, when calling a gui-based application like sumo-gui. (Alternatively, you may start X11 manually by pressing cmd-space and entering XQuartz).

**Comment by yuanjian24** [comment]
> No.
> 
> Did you follow this step, mentioned in the documentation? 👇
> 
> > After the installation you need to log out/in in order to let X11 start automatically, when calling a gui-based application like sumo-gui. (Alternatively, you may start X11 manually by pressing cmd-space and entering XQuartz).

No. Could you please tell me how to log out/in? It seems I do not understand this "log out/in"

**Comment by angelobanse** [comment]
The normal log out on your mac, using either:
- Apple menu > Log Out
- `Cmd`+`Option`+`Shift`+`Q`

After logging back in, please retry opening `sumo-gui` using macOS terminal

**Comment by yuanjian24** [comment]
Retried, but failed,  "opening `sumo-gui` using the macOS terminal" did not give me any feedback. 
By the way, I found the default interactive shell is now zsh. .
![image](https://user-images.githubusercontent.com/50770426/115729150-bff85e00-a3b7-11eb-8138-ce142424e0a1.png)

**Comment by angelobanse** [comment]
If you can, join real quick our [Mattermost channel](https://mattermost.eclipse.org/eclipse/channels/sumo) where I can help you through chat. My username there is also @angelobanse :+1:

**Comment by angelobanse** [comment]
It was a XQuartz related problem.
Updating XQuartz 2.7.11 to 2.8.0 fixed it.
