### ISSUE TITLE
SubscriptionFilterFieldOfVision doesn't detect all Vehicles in Opening Angle

### ISSUE THREAD

**Issue by fehnkera** [eclipse/sumo#8539]
Dear Community,

I have implemented a front sensor for a vehicle with a context subscription on the ego vehicle and a SubscriptionFilterFieldOfVision. When I ask for the results of the context subscription, not all vehicles that lay inside the opening angle are returned.

I added four example screenshots in which I used traci to color the ego vehicle pink and the vehicles that were returned by the filtered context subscription green. In all screenshots vehicles that should be in the filtered area are not detected. (Additionally in screenshot 4 the ego vehicle is returned by its own context subscription). Is this a bug or is there something wrong with the way I use the filter?

Thank you for your help!

Anselm Fehnker

![screenshot-4](https://user-images.githubusercontent.com/32002880/115723488-51e47480-a380-11eb-9d92-340231deaee1.png)
![screenshot-1](https://user-images.githubusercontent.com/32002880/115723490-527d0b00-a380-11eb-9ef6-d097093c7096.png)
![screenshot-2](https://user-images.githubusercontent.com/32002880/115723492-527d0b00-a380-11eb-8b6f-133075501e7f.png)
![screenshot-3](https://user-images.githubusercontent.com/32002880/115723494-5315a180-a380-11eb-8a08-05c75e148d8d.png)

P.S: I have attached the model and the traci log file in case that helps solving my problem.
[FilterFieldOfVision.zip](https://github.com/eclipse/sumo/files/6358644/FilterFieldOfVision.zip)

**Comment by schwamborn** [comment]
Thank you for the bug report. Please also attach your TraCI script, so I can reproduce the issue.

**Comment by fehnkera** [comment]
Of course. Is this the TraCI script you need?
[FilterFieldOfVision.zip](https://github.com/eclipse/sumo/files/6358950/FilterFieldOfVision.zip)

**Comment by schwamborn** [comment]
I only see the log file. How did you produce this log file?

**Comment by namdre** [comment]
the traci.log is equivalent to the traci script

**Comment by schwamborn** [comment]
Fair enough. I guess I was hoping for something more concise.

**Comment by schwamborn** [comment]
It looks like you do not even read the subscription results after calling `traci.vehicle.getContextSubscriptionResults()`. You need to inspect the return value.

Please take a look at the script in `tests/complex/traci/ContextSubscriptionFilters/fieldOfVision/runner.py` for an example of how to use and access results properly.

And for future bug reports, please make your script more concise, e.g., use for/while loops where sensible.

**Comment by namdre** [comment]
> And for future bug reports, please make your script more concise, e.g., use for/while loops where sensible.

Sending the traceFile (no loops and just a long list of commands) is generally ok. However, if you can demonstrate your issue with a shorter script / fewer commands than this is preferable.
