### ISSUE TITLE
Residual image of pedestrians after leaving on a bike

### ISSUE THREAD

**Issue by dhellOwOrldb** [eclipse/sumo#8540]
Dear SUMO experts,

Thank you very much for reading this email and please help me with this problem. I would like to simulate a multi-mode routing process of a person. Say, the person first takes a walk untill it reaches a bike sharing zone and takes a bike. However, after the personleft the area on a bike, the pedestrian image still remains in the GUI at the roadside (as shown in Figure 1). How could I solve this problem? Many thanks. My code is attached as follows:
# remove the previous stages (walking stage)
traci.person.removeStages(eachWalkingPedestrianID)
# assign a bike to the person
bikeID = "bike" + str(eachWalkingPedestrianID)
traci.person.appendDrivingStage(personID=eachWalkingPedestrianID, toEdge=pedestrianEdgeIDList[-1], lines=bikeID)
traci.vehicle.add(vehID=bikeID, routeID="", typeID="bike", personCapacity=1)  # departPos="-1"
# assign a route to the bike
traci.vehicle.setRoute(vehID=bikeID, edgeList=pedestrianEdgeIDList)

Figure 1 Residual image of pedestrians after leaving on a bike
![image](https://user-images.githubusercontent.com/49153858/115837068-c4218b80-a44a-11eb-8de3-295ea6b3509d.png)

**Comment by namdre** [comment]
The person isn't actually riding the bike (otherwise the person symbol would be drawn on top of the bike). Instead the bike is driving all by itself. In principle, there are three ways to fix this

- use vehicle.setStop on the bike so that the person can "enter"
- let the vehicle departure by triggered by the person (currently not working #1721 )
- use person.appendStage with a personTrip that uses a bicycle. This will automatically add a triggered bicycle and a ride that uses it.

**Comment by dhellOwOrldb** [comment]
Dear Jakob, 

Thank you so much for your suggestion and help. I followed your instructions and it worked! However, I found differences in adding vehicle via TraCI and adding vehicle in advance in the  rou.xml file. 

When I add vehicle via TraCI with the following codes, the animation is shown in Figure 1 (not very smooth due to person jumping):

# assign a bike to a walking person
# generate the route ID
routeID = "route" + str(eachWalkingPedestrianID)
# generate the ID of the bike
bikeID = "bike" + str(eachWalkingPedestrianID)
traci.route.add(routeID=routeID, edges=pedestrianEdgeIDList)
# add the bike to the environment
traci.vehicle.add(vehID=bikeID, routeID=routeID, typeID="bike", personCapacity=1)\
# get the current edge the pedestrian is on
currentEdgeID = traci.person.getRoadID(eachWalkingPedestrianID)
# stop the bike so the person can enter as suggested by you, thanks again.
traci.vehicle.setStop(bikeID, edgeID=currentEdgeID, duration=0)
# generate a new stage for the person 
ridingStage = traci.simulation.Stage(type=traci.constants.STAGE_DRIVING, vType="bike", line=bikeID, depart=traci.constants.DEPARTFLAG_TRIGGERED, departPos=0, arrivalPos=100, edges=pedestrianEdgeIDList, description="riding") 
# append the stage to the person's trip plan
traci.person.appendStage(eachWalkingPedestrianID, ridingStage)
# remove the pre-defined walking stage
traci.person.removeStage(eachWalkingPedestrianID, 0) 

Figure 1 Animation of adding bike dynamically via TraCI
![image](https://user-images.githubusercontent.com/49153858/115952006-5c387700-a516-11eb-9561-bea22faafbae.png)
![image](https://user-images.githubusercontent.com/49153858/115952020-6eb2b080-a516-11eb-8ea0-202db1ec57dd.png)
![image](https://user-images.githubusercontent.com/49153858/115952034-85f19e00-a516-11eb-8209-0a4394a56737.png)
![image](https://user-images.githubusercontent.com/49153858/115952083-bc2f1d80-a516-11eb-9062-6d5501d359f4.png)


But when I added the bike in the rou.xml file as follows, the  the animation is very smooth as expected:
<?xml version="1.0" encoding="UTF-8"?>
<routes>
    <vType id="bike" vClass="bicycle" color="1,0,0"/>
    <person id="person0" depart="3">
        <walk from="-gneE11" to="-gneE3" edges="-gneE11 -gneE10 -gneE9 -gneE4 -gneE3"/>
    </person>
    <vehicle id="bikeperson0" type="bike" depart="triggered">
		<route edges="-gneE11 -gneE10 -gneE9 -gneE4 -gneE3"/>
    </vehicle>
</routes>

Figure 2 Animation of adding bike beforehand via rou.xml file
![image](https://user-images.githubusercontent.com/49153858/115952116-ec76bc00-a516-11eb-8931-10041aeedb4a.png)
![image](https://user-images.githubusercontent.com/49153858/115952128-f4cef700-a516-11eb-9e23-c7b78e48bb7c.png)
![image](https://user-images.githubusercontent.com/49153858/115952137-fdbfc880-a516-11eb-9e6b-a541d13d614b.png)


Could you offer me some further gaidance on how to optimise the add-bike-via-TraCI approach? Thank you in advance for your help and your time.

**Comment by namdre** [comment]
use traci.vehicle.add(bikeID, ... , depart="triggered") and don't use setStop.

**Comment by dhellOwOrldb** [comment]
Thank you so much for your help and your kindness. You are the lighthouse of the SUMO sea.
