### ISSUE TITLE
Visualization problem when trying to add a poi image

### ISSUE THREAD

**Issue by dhellOwOrldb** [eclipse/sumo#8541]
Dear SUMO experts,

Thank you for reading this email and sorry to bother you. I tried to add a image-based poi to the sumo-gui (version 1.8.0) via traci. However, the image cannot be shown properly even though I set the layer to a extremely large value(1000). I used other image formats but the problem persists. The source code is as follows:
traci.poi.add("fire", 136, 102, (255, 99, 71, 1), layer=1000, imgFile="images/flame.png", width=100, height=100)
I also found that in the selection view (Figure 2), the image can be shown properly. But I need to display it in the standard or real world view. Could you help me to solve the problem? Many thanks.
In additon, is there any method to change the color of edges or junctions via traci? The only potential solution that can come into my mind is to draw Polygons to cover the edges or junctions. Is there any other more efficient solutions? Thank you in advance for your time and your help.

Figure 1. Standard view:
![image](https://user-images.githubusercontent.com/49153858/115837416-27132280-a44b-11eb-8441-b66093edcbfb.png)
Figure 2. Selection view:
![image](https://user-images.githubusercontent.com/49153858/115837415-27132280-a44b-11eb-82e7-3d53c861758f.png)

**Comment by namdre** [comment]
- can you reproduce the problem when loading the poi from an additional xml file (without using traci)?  
- have you tried lower layer values (layer 10 should be enough to show up on top of the network)?
- can you provide the input files?

The easiest way to change colors via TraCI is to 
- save desired gui-settings to a file
- load the settings file at startup (multiple sets of settings can be placed in the same file)
- use traci.gui.setSchema to switch between settings

If you need more dynamic colors, you can set edge coloring based on a numerical parameter and then use traci.edge.setParameter to update the colors

**Comment by dhellOwOrldb** [comment]
Dear Jakob, 
Thank you so much for your quick reply and your help. I can successfully add the image and dynamically adjust its size when loading the image from an additional xml file (see Figure 1). Thank you so much for your help. The code is attached as follows:
<additional>
	<poi id="fire" type="fire" x="136" y="102" color="0.9,1,0.9" fill="true" imgFile="images/flame.png" layer="10" width="0" height="0"/>
</additional>
 Figure 1  PoI loading from additional xml file
![屏幕截图(198)](https://user-images.githubusercontent.com/49153858/115893010-4e3d1480-a48a-11eb-90b5-c07349d04836.png)

For the second question, I have tried various layer values but unfortunately all failed as long as loading the file with traci. 

For the third question, could please further elaborate the meaning of "input files", currently I am attaching the net, rou, sumocfg, and the image file. 
[input files.zip](https://github.com/eclipse/sumo/files/6366361/input.files.zip)

About changing the colors of edges via TraCI:
Since I would like to display the spreading of fire with the dynamic changes of colors on the designated edges, I am very interested in setting colors using  traci.edge.setParameter. But I am still not sure how to do that. Could you tell me what is the name of the parameter that can be recognised by SUMO? Currently I tried the code below but it would not work:
traci.edge.setParameter("gneE96", "color", "236,0,0")
I noticed there is an option as shown in Figure 2 to customise the color of edges by saving as viewsettings file (colorScheme). But how could I dynamically change the color of a designated edge? Thank you so much in advance for your help and your time. 
Figure 2 
![屏幕截图(200)](https://user-images.githubusercontent.com/49153858/115900463-93654480-a492-11eb-994d-cb6cc7f0f31b.png)

**Comment by namdre** [comment]
If the edges already have a parameter, you can select this in the box that says EDGE_KEY in your screenshot (otherwise you can just type the desired parameter name in the box). Then configure the value-to-color map as desired and save the settings so you can load them with your simulation.

**Comment by namdre** [comment]
regarding your invisible traci poi: You have to specify the color as (255,255,255) or (255,255,255,255)

**Comment by namdre** [comment]
and regarding the meaning of "input files", I meant all the files you sent plus the traci script your are using (ideally reduced to the minimal number of commands for showing the issue).
