### ISSUE TITLE
Omnet++, Veins and Sumo?

### ISSUE THREAD

**Issue by PolynomialDivision** [eclipse/sumo#8546]
On my Manjaro machine 5.10.30-1-MANJARO with:
- Omnet++: Version: 5.6.2, build: 200518-aa79d0918f, edition: Academic Public License
- Veins: veins-5.1
- Sumo: > 1.9.0

I created a simulation with omnet++ in combination with veins and sumo. However, starting the simulation results directly in:

![image](https://user-images.githubusercontent.com/10708466/115967882-661da280-a535-11eb-99cc-b012049d0526.png)

```
Error: Storage::readChar(): invalid position
`````

If I change the version to `sumo 1.8.0-2` it looks like this:

```
Error: tcpip::Socket::recvAndCheck @ recv: peer shutdown
```

![image](https://user-images.githubusercontent.com/10708466/115968001-d62c2880-a535-11eb-9d5f-d0229c74147a.png)

The same project is running on Ubuntu with:
sumo/hirsute,now 1.8.0+dfsg2-5 amd64
omnetpp-5.6.2/
veins-veins-5.1/

**Comment by PolynomialDivision** [comment]
I think it is the TraCi module... So the TCP connection between OMNet++/Veins and sumo. Is the protocol API changing somehow?

**Comment by namdre** [comment]
The first error is most likely a version mismatch. However, the only function call where the protocol changed from 1.8 to 1.9 is traci.person.getTaxiReservations

The second error is a crash in the client program (maybe because an unsupported function is being called?). Look for the error message from the client.

**Comment by PolynomialDivision** [comment]
@namdre 

I found an error:

> ASSERT: "length() > 0" in file /usr/include/qt/QtCore/qline.h, line 383

**Comment by namdre** [comment]
I would guess that the problem occurs at an earlier point in the client code rather than this being a qtcore bug. Try to get a stack trace and maybe request help from the Veins people.

**Comment by PolynomialDivision** [comment]
I have the same issue on Ubuntu 20.04 with sumo 1.9 (master branch).

**Comment by namdre** [comment]
can you find out the names of all the traci functions being called by the client?

**Comment by hanwiz** [comment]
Actually, I noticed this problem later branch of 1.8 (2020 Dec). The Veins cannot proceed with its first subscription using the following code after API version check and initNetworkBoundaries.

```
        // subscribe to list of departed and arrived vehicles, as well as simulation time
        simtime_t beginTime = 0;
        simtime_t endTime = SimTime::getMaxTime();
        std::string objectId = "";
        uint8_t variableNumber = 7;
        uint8_t variable1 = VAR_DEPARTED_VEHICLES_IDS;
        uint8_t variable2 = VAR_ARRIVED_VEHICLES_IDS;
        uint8_t variable3 = commandInterface->getTimeStepCmd();
        uint8_t variable4 = VAR_TELEPORT_STARTING_VEHICLES_IDS;
        uint8_t variable5 = VAR_TELEPORT_ENDING_VEHICLES_IDS;
        uint8_t variable6 = VAR_PARKING_STARTING_VEHICLES_IDS;
        uint8_t variable7 = VAR_PARKING_ENDING_VEHICLES_IDS;
        TraCIBuffer buf = connection->query(CMD_SUBSCRIBE_SIM_VARIABLE, TraCIBuffer() << beginTime << endTime << objectId << variableNumber << variable1 << variable2 << variable3 << variable4 << variable5 << variable6 << variable7);
        processSubcriptionResult(buf);
        ASSERT(buf.eof());
```

**Comment by namdre** [comment]
@behrisch any ideas what could have changed here subscription-wise?

**Comment by behrisch** [comment]
This is very probably the error report to #8601 It seems I broke veins support here

**Comment by behrisch** [comment]
Seems to be solved, if not please reopen
