### ISSUE TITLE
faulty roundabout heuristic (2) (trac #855)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#855]
a critical look at the Braunschweig sceneario reveals more failures of the roundabout heuristic

Migrated from http://sumo.dlr.de/ticket/855
```json
{
    "status": "new", 
    "changetime": "2015-11-21T20:25:07Z", 
    "description": "a critical look at the Braunschweig sceneario reveals more failures of the roundabout heuristic", 
    "reporter": "namdre", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1448137507458361", 
    "component": "net building (NETGEN, NETCONVERT)", 
    "summary": "faulty roundabout heuristic (2)", 
    "priority": "minor", 
    "keywords": "", 
    "time": "2013-02-11T12:05:01Z", 
    "milestone": "1.1.0", 
    "owner": "", 
    "type": "defect"
}
```

**Comment by namdre** [comment]
Checking the miv.net.xml  (https://github.com/DLR-TS/sumo-scenarios/tree/master/brunswick) gives 15 roundabouts of which 14 are fine and one (involving junction 35664416) is a harmless blunder that fits all the formal constraints and is just a bit to large which makes it obvious to the human viewer.
