### ISSUE TITLE
duarouter with logit does not converge to UE

### ISSUE THREAD

**Issue by yunpangfloetteroed** [eclipse/sumo#8550]
The current assignment way results in strong route swapping endlessly when --logittheta is only a little bite large, where very small theta results in cost insensitivity and all routes will be equally used as converged result. Therefore no travel-time based UE can be achieved. With the option --weight-memory the converge can be achieved (a local optimised solution), but not UE.

According the internal discussions, the assignment way should be improved to consider e.g. only a part of trips can change their routes at each iteration, e.g. 1/ number of iterations or the customized option, in duaIterate.py and duarouter.

**Comment by namdre** [comment]
added new option **--skip-new-routes.probability**

**Comment by namdre** [comment]
also duaIterate option is now called **--convergence-steps**

**Comment by yunpangfloetteroed** [comment]
I tried the new version and it works (converged when theta = 1)  only when convergence-steps = the number of iterations = 20. The results is 
r1_time (with the shortcut): 100.23333333333333 r1_flow: 240
r2_time (lower route): 121.1501210653753 r2_flow: 413
r3_time (upper route): 117.12968299711815 r3_flow: 347
avg_time: 114.735

When "convergence-steps = the number of iterations = 50" or "convergence-steps = 50 and the number of iterations = 20" there is no convergence....

**Comment by namdre** [comment]
What happens when steps = 60 and convergence steps = 50? cars shouldn't be able to change their route after step 50...

**Comment by yunpangfloetteroed** [comment]
Opps... I only plotted the results for 20 iterations, which was hard coded in the script. Now I plotted the results correctly and all (iterations=100,60,50,20) are converged. Regarding your question, it looks that the answer is no.
But when iterations = 200, en error occured:  Execution of ['D:\\Wang\\sumo_git\\bin\\duarouter', '-c', '16/iteration_016_input_routes_015.duarcfg'] failed. Look into dua.log for details. In the dua.log, no errors are reported.

**Comment by namdre** [comment]
what were the exact parameters of the failing call to duaIterate?

**Comment by yunpangfloetteroed** [comment]
I sent you the call I used. You find it below.
python "%sumo_home%\tools\assign\duaIterate.py" -n ..\input_net.net.xml -r ..\input_routes.rou.xml --last-step 200 sumo--duration-log.statistics sumo--duration-log.disable --vehroute-file "routesonly" --logit --logittheta 1 --logitgamma 1 --logitbeta 0 --convergence-steps 200

**Comment by yunpangfloetteroed** [comment]
Regarding the option --convergence-steps I suggest that the default value is the number of iterations (or at least >= 20) and it should not be less then the number of iterations in the duaIterate.py. Otherwiese, users will experience the exact situation what we have had, i.e. route chioces are going to oscillate among available routes. It is also nice to send a warning when users use a small number of iterations or convergence steps. What do you think?

**Comment by namdre** [comment]
I think the warning is a good idea. However, I just found one scenario where duaIterate.py results are worse when using convergence-steps so I'm reluctant to change the default (even though it seems to be better on average).

**Comment by yunpangfloetteroed** [comment]
Why did the crash not happen when using iterations = 20, 50, 60, 100?

**Comment by namdre** [comment]
The crash only happened when some routes received probability 0 and were automatically removed even though they should still have been used due to keep-route-probability.
