### ISSUE TITLE
libtraci in Windows, setup procedure 

### ISSUE THREAD

**Issue by jackycstw** [eclipse/sumo#8560]
Dear Sirs,

I am trying to build up a C++ program that can use libtraci. What I have done is:

1. git clone sumo and sumo library from github
2. use VS 2019 to configure the CMAKE data
3. use CMAKE GUI to generate the sumo.sln
4. setting up the environment path for SUMO_HOME and SUMO_LIBRARIES

For this moment, I could use sumo-gui in cmd to start sumo. Then I tired to create a new, clean C++ console project from VS2019.
1. The code was just like the example from https://sumo.dlr.de/docs/Libtraci.html
2. Here is my code:
#pragma once
#include <iostream>
#include <libsumo/libtraci.h>

using namespace libtraci;

int main()
{
    Simulation::start({ "sumo-gui", "-n", "network.net.xml" }, 8813);
    for (int i = 0; i < 5; i++) {
        Simulation::step();
    }
    Simulation::close();
}

3. I included all dll in sumo/bin/ to this project
4. In the include path of this project, I added
C:\sumo\SUMOLibraries\googletest-1.8.0\googletest\include;C:\sumo\CMAKE\src;C:\sumo\src;C:\sumo\SUMOLibraries\32bits\xerces-c-3.2.3\include;C:\sumo\SUMOLibraries\32bits\proj-7.2.0\include;C:\sumo\SUMOLibraries\32bits\fox-1.6.57\include;C:\sumo\SUMOLibraries\32bits\freetype-2.10.4\include\freetype2;C:\sumo\SUMOLibraries\32bits\3rdPartyLibs\zlib-1.2.11\include;%(AdditionalIncludeDirectories)
5. In the dependencies of this project, I added
ws2_32.lib
C:\sumo\bin\libtracicpp.lib
5. Then I tried to build my project with x86 debug mode.

The question is there was a memory error:
![image](https://user-images.githubusercontent.com/48200829/116366269-b304c000-a838-11eb-8abe-722d7f07704c.png)

and I have no idea how to debug this. 

Please suggest me how to solve this problem.

Your help will be appreciated.

Jacky

**Comment by Domsall** [comment]
As I also use VS to compile C++-Code with TraCI, maybe I can help.
Normaly when compiling in Debug-Mode, VS must find dll's/lib's, which where also compiled to run in Debug-Mode. The dll "vcruntime140.dll" is expected to run with Release-Mode, the Debug-Version often has a "D" at the end, e.g. "vcruntime140d.dll". This should also lie in sumo/bin. Maybe the Compiler is not finding it or you explicitly defined "vcruntime140.dll" to run in the Debug-Mode.

**Comment by jackycstw** [comment]
Dear Domsall,

Thank you for your help.

I tried to delete all dll which have these two mode. The error became simple like:

![image](https://user-images.githubusercontent.com/48200829/116369480-01678e00-a83c-11eb-840f-6684332fe76e.png)

It means that there is an exception for tcpip::SocketException.

By the way, is there anything that I can change in the steps I trying to use libtraci?

Jacky

**Comment by Domsall** [comment]
You may not have SUMO open or the right port/ip-adress to connect to. tcpip is failing to connect to the defined socket.
In your case it lookes like the program is not starting SUMO as expected. For Windows you may need to define the path to sumo/bin in the environment variable PATH.
If SUMO starts, it may also crash with an error, if it can't load the configuration/net (error file type or typo).

**Comment by jackycstw** [comment]
Dear Domsall,

I've check about the PATH
![image](https://user-images.githubusercontent.com/48200829/116371997-93709600-a83e-11eb-90c2-4d96f150de5f.png)

You are right. The program did not start SUMO as expected. I also sure about the port and ip-address is availble since I can use sumo-gui --remote-port 8813 to open it.

**Comment by Domsall** [comment]
Can you open sumo-gui with the defined network?

**Comment by jackycstw** [comment]
Yes and here is the result
![image](https://user-images.githubusercontent.com/48200829/116374833-3f1ae580-a841-11eb-83e0-13b2fc4752ca.png)

**Comment by jackycstw** [comment]
Dear Domsall,

Case is close. I found that I didn't use administrator to open this project. What an idiot I am.
