### ISSUE TITLE
traci.start definition document

### ISSUE THREAD

**Issue by Jianhua-Jiang** [eclipse/sumo#8566]
Can you send the parameter description or definition document link of traci.start? I haven't found the complete introduction. thank you!

**Comment by namdre** [comment]
The documentation is at https://sumo.dlr.de/pydoc/traci.main.html but will take a while to update. Here is the reference:

   - cmd (list): uses the Popen syntax. i.e. ['sumo', '-c', 'run.sumocfg']. The remote
      port option will be added automatically
   - numRetries (int): retries on failing to connect to sumo (more retries are needed
      if a big .net.xml file must be loaded)
   - label (string) : distinguish multiple traci connections used in the same script
   - verbose (bool): print complete cmd
   - traceFile (string): write all traci commands to FILE for debugging
   - traceGetters (bool): whether to include get-commands in traceFile
   - stdout (iostream): where to pipe sumo process stdout
