### ISSUE TITLE
netedit does not load polygons properly

### ISSUE THREAD

**Issue by yunpangfloetteroed** [eclipse/sumo#8568]
When loading a file via "additionals and shapes" polygons cannot be properly loaded (see the attached picture), while this problem does not appear when using sumo-gui.
![loaded_polygon_with_netedit](https://user-images.githubusercontent.com/26454969/116526712-2d395100-a8da-11eb-89e1-15b218875fe8.png)

When clicking "Draw with constant size when..." in the view setting the loaded polygons are disappeard.

**Comment by yunpangfloetteroed** [comment]
Example files are under S:\Sumo\Bugreports\8568_netedit does not load polygons properly.zip

**Comment by namdre** [comment]
was still working in 1.6.0

**Comment by namdre** [comment]
would be good to fix this for 1.9.1

**Comment by namdre** [comment]
two things are causing this
- lines are very narrow when zoomed out since 1.7.0
- exaggeration was switched from increasing the line width to expanding the whole shape (this should be returned the previous version, shape expansion instead via a new gui settings option added later)
