### ISSUE TITLE
netedit does not show object ids when zooming out a network

### ISSUE THREAD

**Issue by yunpangfloetteroed** [eclipse/sumo#8571]
The object ids, loaded from an additional file, can only be seen when zooming into a small area. SUMO-GUI does not have this problem.

The example files are the same as those in #8568 ( under S:\Sumo\Bugreports\8568_netedit does not load polygons properly.zip)

**Comment by palvarezlopez** [comment]
Fixed in ccadc841bddf9f6cb9037aa0c96e22daaf9334b1

**Comment by namdre** [comment]
the additional id issue  predates 1.3.1.
