### ISSUE TITLE
TraCI: Vehicle with Speed Mode = 8 does not regard the right of way.

### ISSUE THREAD

**Issue by philippwulff** [eclipse/sumo#8586]
I wanted to set the speed mode in my simulation so that all checks are disabled, but SUMO takes control of the vehicle, if it disregards the right of way at upcoming intersections. The [docs](https://sumo.dlr.de/docs/TraCI/Change_Vehicle_State.html#speed_mode_0xb3) tell me to call `setSpeedMode(veh_id, 8)` for this. However the vehicle does not regard the right of way (I am setting the speed with `setSpeed`). If there is an upcoming intersection with upcoming foes, the vehicle will not stop. Is there something that I am doing wrong or could this be a bug? I could try to upload a traci command log for reproduction if needed.

**Comment by philippwulff** [comment]
Hi, sorry for the late reply. 

The junction type is `traffic_light` and the rightOfWay is `default`. This GIF shows the behavior of the vehicle.

![PPO_AccelEnv_w_dense_small_city_5mio_cropped](https://user-images.githubusercontent.com/45896065/118984177-81859d00-b97d-11eb-99ca-5794c8672cb0.gif)

I am continuously setting the speed of the red vehicle (`setSpeed()`) to a value larger than zero, but I expected SUMO to slow down or stop the vehice, when it has a foe. This is how the check (`setSpeed(vehID, 8)`) works, right?

**Comment by namdre** [comment]
SUMO distinguishes between right-of-way check ahead of a junction and the check while on a junction. 
the 4th  bit (speedMode=8) only controls the former while the latter is handled by the rightmost bit (regard safe speed)

**Comment by philippwulff** [comment]
Ok, thanks. That is good to know. I tested it and the situation from the video is taken care of by SUMO with `speedMode=9`.

**Comment by namdre** [comment]
@philippwulff see #8675
