### ISSUE TITLE
osmWebWizard.py (argument -b/--bbox error)

### ISSUE THREAD

**Issue by Orlando-pt** [eclipse/sumo#8589]
I am trying to make a simulation on my city (Aveiro, Portugal) using the osmWebWizard tool.
I have tested to generate a simulation on the default city (Berlin) and it worked. But, when i try to make a simulation in Aveiro it gives me an error, saying that the argument **-b** was expected and it wasn't provided.
The log is the following:

```
Building scenario in '/home/orlando/Sumo/2021-05-03-16-27-02'
Downloading map data
usage: osmWebWizard.py [-h] [-c FILE] [-C FILE] [--save-template FILE]
                       [-p PREFIX] [-b BBOX] [-t TILES] [-d OUTPUT_DIR]
                       [-a AREA] [-x POLYGON] [-u URL] [-w]
osmWebWizard.py: error: argument -b/--bbox: expected one argument
```

**Comment by namdre** [comment]
This is a know bug (#8521) for which we are doing a hotfix release tomorrow.
