### ISSUE TITLE
TraCI: screenshot only saved after the simulation is incremented

### ISSUE THREAD

**Issue by philippwulff** [eclipse/sumo#8594]
`traci.gui.screenshot` does not save the screenshot until `traci.simulationStep()` is called. Is this supposed to behave this way? Maybe this information should be added to the [documentation](https://sumo.dlr.de/pydoc/traci._gui.html#GuiDomain-screenshot).

Also, I noticed, that one cannot use `hasGUI()` with a connection object but only through `traci` directly:
```
{AttributeError}'Connection' object has no attribute 'hasGUI'
```

**Comment by namdre** [comment]
Currently, all traci commands are only executed upon the subsequent call to simulationStep so I'd say this is expected and the documentation should be amended.

The hasGui thing should indeed be fixed.
