### ISSUE TITLE
Longitudinal and lateral vehicle velocities

### ISSUE THREAD

**Issue by BouchraBenkoussas** [eclipse/sumo#8602]
Hello, 

I would like to create a service to manage the turning manoeuvre at intersection and I need to calculate the velocity and acceleration component. I found that SUMO can report lateral speed via TraCIAPI::VehicleScope::getLateralSpeed but this function returns a 0 even though my vehicle changes direction. Do you have any explanation regarding this result? Does the vehicle move according to its landmark? 

Thank you in advance and kind regards,
Bouchra.

**Comment by namdre** [comment]
lateral movement in sumo refers to movement that is orthogonal to the center-line of the current lane.  This means a vehicle that stays on the center line has lateral speed 0 regardless of lane curvature.  To compute local curvature you need to do your own computation base on the lane geometry. 
Note, that lane geometry is piecewise linear (using 5 line segments per turning movement by default).  Code that computes the turning radius for such geometry can be found at https://github.com/eclipse/sumo/blob/73fc29ec436f18883464994546369132346dff24/src/netbuild/NBEdge.cpp#L1803-L1812

**Comment by BouchraBenkoussas** [comment]
Hello, 

Thank you for your reply.
Please find attached a picture that describes my problem. I would like to know if the turning angle is the alpha shown in the picture and is it the "Yaw rate value"?
![issue - components](https://user-images.githubusercontent.com/62869736/117574254-8ecc9d00-b0dc-11eb-8f5b-9f3ca73c82ae.png)

Kind regards,
Bouchra.

**Comment by behrisch** [comment]
This seems to be an entirely new question so (next time) please open a new ticket. Which turning angle and yaw rate you refer to? Do you mean the angle shown in the GUI and retrievable via TraCI?

**Comment by namdre** [comment]
I'd say the turning angle in your case is 90 degrees (the difference in angle between the roads before and after the turn whereas the yaw raw is the turning angle divided by the time to move through this turn. (assuming constant rate of turn).
Momentary yaw rate is the difference in vehicle angle (as reported by sumo) between successive steps
