### ISSUE TITLE
support tools for KDD citybrains challenge

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#8605]
http://www.yunqiacademy.org/poster
https://github.com/CityBrainChallenge/KDDCup2021-CityBrainChallenge-starter-kit
https://github.com/DLR-TS/KDDCup2021-CityBrainChallenge-starter-kit
https://kddcup2021-citybrainchallenge.readthedocs.io/en/latest/
http://www.yunqiacademy.org/home/leaderboard

**Comment by namdre** [comment]
` sumo/tools/import/citybrain/citybrain_road.py -n citibrain_git/data/roadnet_warm_up.txt -o warmup.net.xml`

Observation: Some of the connection information appears invalid (i.e. a right-turn is specified at a T-intersection with no right turn edge).

**Comment by namdre** [comment]
Posted some questions at https://github.com/CityBrainChallenge/KDDCup2021-CityBrainChallenge-starter-kit/issues/17

**Comment by behrisch** [comment]
I get disconnected routes when importing. Are the connection problems above the reason?
```
> sumo -n warm_up.net.xml -r warm_up.rou.xml 
Error: Vehicle '56.0' has no valid route. No connection between edge '12' and edge '28'.  
```

**Comment by behrisch** [comment]
It works now, thank you!

**Comment by behrisch** [comment]
seems to be a single use format only so no documentation needed
