### ISSUE TITLE
Randomtrips.py

### ISSUE THREAD

**Issue by zzchuman** [eclipse/sumo#8606]
hello ，I just want to know the randomtrips.py .
P means generate vehicles per seconds.
And generally， what the value of the p will be set？

**Comment by behrisch** [comment]
`--period` gives the average interval between two vehicle departures (so the inverse of vehicles per second) and the value depends a lot on the size of your scenario. Usually it is a small value between 1 and 10. Try to extract your scenario using webWizard and have a look at build.bat to get a feeling for the value.
