### ISSUE TITLE
TraCI won't allow re-adding removed vehicles at reset

### ISSUE THREAD

**Issue by roireshef** [eclipse/sumo#8607]
Hi. I was using a code that called traci and it worked well with Sumo v1.1.0. I tried upgrading to newer Sumo version and am now facing issues I just can't figure out how to solve. I'd appreciate your help.

In summary, when my code decides to end an episode, it proceeds by calling:
_**self.k.kernel_api is the TraCI handle.**_

```
for veh_id in self.k.kernel_api.vehicle.getIDList():  
    try:
        if self.render:
            self.kernel_api.vehicle.unsubscribe(veh_id)
        self.kernel_api.vehicle.remove(veh_id)
    except (FatalTraCIError, TraCIException):
        print(traceback.format_exc())
```
to remove all existing vehicles in the simulation, then:

```
for veh_id in self.initial_ids:
    type_id, route_id, lane, pos, speed = self.initial_state[veh_id]
    try:
        self.kernel_api.vehicle.addFull(
            veh_id,
            route_id,
            typeID=str(type_id),
            departLane=str(lane),
            departPos=str(pos),
            departSpeed=str(speed))
    except (FatalTraCIError, TraCIException, libsumo.TraCIException):
        # if a vehicle was not removed in the first attempt, remove it
        # now and then reintroduce it
        if self.simulator == 'traci':
            self.k.kernel_api.vehicle.remove(veh_id)
        self.kernel_api.vehicle.addFull(
            veh_id,
            route_id,
            typeID=str(type_id),
            departLane=str(lane),
            departPos=str(pos),
            departSpeed=str(speed))

# advance the simulation in the simulator by one step
self.kernel_api.simulation_step()
```
to add the vehicles that the next episode would start with. Those vehicles must be spawned at the beginning of each episode.

What happens is that in the first code block, all vehicles are removed, so after it `self.k.kernel_api.vehicle.getIDList()` returns an empty list. Then, when trying to re-add the removed rl_0 vehicle, TraCI raises an error (vehicle already exists). And although the  _except_ clause calls _remove_ again, when reaching the second _addFull_ call, TraCI would raise again the _vehicle already exists_ exception.

If I repalce the second block by:
```
for veh_id in self.initial_ids:
    type_id, route_id, lane, pos, speed = self.initial_state[veh_id]
    try:
        self.kernel_api.vehicle.addFull(
            veh_id,
            route_id,
            typeID=str(type_id),
            departLane=str(lane),
            departPos=str(pos),
            departSpeed=str(speed))
    except (FatalTraCIError, TraCIException, libsumo.TraCIException):
        pass

# advance the simulation in the simulator by one step
self.kernel_api.simulation_step()
```

The 'rl_0' vehicle won't be spawned at all, even after calling the _simulation_step_, which will cause other issues.

So, I'm left confused. How come I can't remove, but also can't add a vehicle with a specific id? Is this a bug? The same code actually works great in Sumo v1.1.0. Has anything changed since in TraCI or SUMO that would require adjustments to the code above? (Taken from the Flow pacakge)

BTW, it happens both when using TraCI and when using libsumo

**Comment by behrisch** [comment]
I think #5647 has already a good description of the problem so let's continue the discussion there.

**Comment by roireshef** [comment]
@namdre the sequence you provided does remove the vehicle and re-inserts it, but ends up with weird behavior in the following setup (the one I use): a single vehicle being inserted at time 0 of an episode (my "agent"), plus an "inflow" of vehicles. It samples vehicles with very weird behavior. I'm currently using `simulation.clearPending` which isn't bulletproof (I'll need to debug to see where issues coming from). 

I am going to try `simulation.loadState` - but what do you mean by 

> resets the whole simulation to **previous state**

where is the previous state taken from?

**Comment by namdre** [comment]
the previous state is taken from a file: https://sumo.dlr.de/docs/Simulation/SaveAndLoad.html
The missing documentation was added here: https://sumo.dlr.de/docs/TraCI/Change_Simulation_State.html
