### ISSUE TITLE
use stop attribute 'ended' to overrule 'until'

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#8611]
when doing a rolling-horizon simulation it is useful to distinguish between schedule information that is according to plan versus according to reality (when simulating a time slice of the past).

the current approach uses only the until attribute to set departure time and thus cannot distinguish (in stop-output) between delay according to schedule versus delay according to reality - two very different things.

In the future, If stop attribute 'ended' is defined, and option **--use-stop-ended** is is set, it shall set an additional lower bound on ending a stop.

The behavior is made optional to preserve the previous semantics of running a simulation with input from **--vehroute-output FILE --vehroute-output.exit-times**.

**Comment by palvarezlopez** [comment]
@namdre also in NETEDIT?

**Comment by namdre** [comment]
Yes. It's one new attribute of type 'time' without any further constraints.
