### ISSUE TITLE
setup a CI test with Veins

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#8612]
similar to what we are doing with SAGA to prevent things like #8601

**Comment by schwamborn** [comment]
Closing as the workflow has been implemented and tested successfully.
Needs to be moved to [`master` branch](https://github.com/sommer/veins/tree/master) (cf. https://github.com/sommer/veins/issues/213#issuecomment-855896141) by @sommer, though.

**Comment by sommer** [comment]
Just for completeness: I won't be able to integrate this with `master`. Would appreciate if the CI could be integrated into the `eclipse/sumo` repo.

**Comment by behrisch** [comment]
@sommer Can you shortly explain why you cannot run it on your side? Is it just the annoying presence of the workflow file? Could you create a separate project just for the workflow?
The problem with integrating it on our side is that GitHub limits the compute time (or the number of prallel jobs) per organization. Our GitHub actions already have considerable lag because there are a lot of Eclipse projects running. Adding another task would just make it worse.

**Comment by sommer** [comment]
I don't think I understand enough about "Github Actions" to do this. If it helps, I would be happy to create a dedicated repo (along with permissions for @behrisch and/or any users you would find helpful) for testing SUMO/Veins integration in the https://github.com/veins/ namespace. I'd only ask to use something that avoids building everything from scratch for every commit. Maybe using a multi-stage docker container or something as simple as an action like https://github.com/hendrikmuhs/ccache-action can help here.

**Comment by behrisch** [comment]
@sommer Ok, then please set up a project in https://github.com/veins/ and give me access. I will setup a nightly build there.

**Comment by sommer** [comment]
@behrisch, I sent you an invite to https://github.com/veins/veins_sumo_ci

**Comment by behrisch** [comment]
Should be working now. It can also be made public. We should check whether we can add the badge somewhere on our site and maybe @sommer wants to do that too ;-) If we have a running action tomorrow this can be closed.

**Comment by sommer** [comment]
Added ccache (cuts cumulative build time from 33 minutes to 6 minutes) and changed repo/badge visibility to public
