### ISSUE TITLE
how to set phase in advance

### ISSUE THREAD

**Issue by zhaotuo0815** [eclipse/sumo#8618]
hello,sumo developer，I want to set the phase order based on flow of each entrance lane,the only I can think is to define all possible phase orders like:
def Traffic_Light(NB_F,DX_F,DX_L,NB_L,junction):
    phases= []
    phases.append(traci.trafficlight.Phase(NB_F, "GrrrGrrr", NB_F, NB_F))
    phases.append(traci.trafficlight.Phase(3, "yrrryrrr", 3, 3))
    phases.append(traci.trafficlight.Phase(DX_F, "rrGrrrGr", DX_F, DX_F))
    phases.append(traci.trafficlight.Phase(3, "rryrrryr", 3, 3))
    phases.append(traci.trafficlight.Phase(DX_L, "rrrGrrrG", DX_L, DX_L))
    phases.append(traci.trafficlight.Phase(3, "rrryrrry", 3, 3))
    phases.append(traci.trafficlight.Phase(NB_L, "rGrrrGrr", NB_L, NB_L))
    phases.append(traci.trafficlight.Phase(3, "ryrrryrr", 3, 3))
    logic = traci.trafficlight.Logic(str(junction), 0, 0, phases)
    traci.trafficlight.setCompleteRedYellowGreenDefinition(str(junction), logic)

def Traffic_Light1(NB_F, DX_F, DX_L, NB_L, junction):
    phases= []
    phases.append(traci.trafficlight.Phase(DX_F, "rrGrrrGr", DX_F, DX_F))
    phases.append(traci.trafficlight.Phase(3, "rryrrryr", 3, 3))
    phases.append(traci.trafficlight.Phase(DX_L, "rrrGrrrG", DX_L, DX_L))
    phases.append(traci.trafficlight.Phase(3, "rrryrrry", 3, 3))
    phases.append(traci.trafficlight.Phase(NB_F, "GrrrGrrr", NB_F, NB_F))
    phases.append(traci.trafficlight.Phase(3, "yrrryrrr", 3, 3))
    phases.append(traci.trafficlight.Phase(NB_L, "rGrrrGrr", NB_L, NB_L))
    phases.append(traci.trafficlight.Phase(3, "ryrrryrr", 3, 3))
    logic = traci.trafficlight.Logic(str(junction), 0, 0, phases)
    traci.trafficlight.setCompleteRedYellowGreenDefinition(str(junction), logic) 
But there are way too many possibilities.When I use the traci.trafficlight.setPhase("gneJ1",2) switches to the phase with the given index,which can not dynamically modifying phase order,thanks for your help.

**Comment by namdre** [comment]
For dynamic phase ordering you need to define all "green" phases and also all transitions between any two phases. (you can simply put all transitions after the green phases)
Use phase attribute 'next' to ensure that each transition ends in the correct green phase. 
Then use setPhase to jump to the start of the transition sequence from the current green phase to the desired next green phase.
