### ISSUE TITLE
Taxis are leaving the simulation after a trip

### ISSUE THREAD

**Issue by ArmelliniMG** [eclipse/sumo#8624]
Some taxis leave the simulation after dropping off the last passenger of the current trip, even though there are more reservation pending to be handled.
I couldn't find a reason why this happens with some vehicles. There is also no warning in the simulation, the vehicle is not beeing teleported.

The vehicle is also no longer reachable with:
`traci.vehicle.getTaxiFleet(-1)`
or:
`traci.vehicle.getIDList()`

And its results are written in the tripinfo file:
```
<tripinfo id="taxiWest.46" depart="14138.00" departLane="-23575970#3_1" departPos="5.10" departSpeed="0.00" departDelay="46.00" arrival="19264.00" arrivalLane="7975410#0_1" arrivalPos="138.14" arrivalSpeed="1.77" duration="5126.00" routeLength="13009.93" waitingTime="185.00" waitingCount="17" stopTime="3649.00" timeLoss="463.67" rerouteNo="23" devices="tripinfo_taxiWest.46 routing_taxiWest.46 taxi_taxiWest.46 person_taxiWest.46" vType="taxi" speedFactor="0.99" vaporized="">
        <taxi customers="3" occupiedDistance="9874.42" occupiedTime="1082.00"/>
    </tripinfo>
```

**Comment by namdre** [comment]
Somehow the vehicle lost the stop that is supposed to keep it in the simulation. Can this be reproduced with xml input only or does it happen under traci-taxi-control?
Either way, I need a minimal example to reproduce it.

**Comment by ArmelliniMG** [comment]
The problem was in the dynamic rerouting of the drtOnline tool.

The cause was that traci.vehicle.getStops() also retrieves the stop that is being taking place at the moment, but  traci.person.getTaxiReservations() shows the passengers that are being picked up / dropped off as already on board/outside the vehicle. 
For example:
Vehicle A has the route: A 1 2 1 2
The vehicle is at stop picking up request 1. Request 1 is allready on board, but the stop is still being retrieve by traci.vehicle.getStops()
