### ISSUE TITLE
The latitude and longitude information is lost when using netconvert to convert the format of sum-net to opendrive.

### ISSUE THREAD

**Issue by radiateboy** [eclipse/sumo#8625]
The latitude and longitude information is lost when using netconvert to convert the format of sum-net to opendrive.

cmd:
`netconvert --net-file cy.net.xml --opendrive-output cy.xodr`

**Comment by namdre** [comment]
duplicate of #4417 (see that issue for a workaround)

**Comment by radiateboy** [comment]
okey, thank you very mush. @namdre
