### ISSUE TITLE
netconvert --proj.scale should scale lane widths too

### ISSUE THREAD

**Issue by turix2** [eclipse/sumo#8629]
I am trying to scale down an existing `map.net.xml` file using `netconvert` in order to make it match some external traffic data.  The `--proj.scale` option seems to do what I want, appropriately scaling all of the edges, coordinates, etc.  Unfortunately, it leaves the `width` attributes for the lanes untouched at the original scale.  Is this a bug with `--proj.scale`, or am I misinterpreting the option?  And is there another way to scale the edges _and_ the lane widths simultaneously?

Here is an example of a command line I tried:  `netconvert --proj.scale=.04 -s map.net.xml -o test.scaling.xml`
(I tried with various scale factors.)

I'm attaching a `map.net.xml` file that I'm trying to scale down in a zip file:  [map.net.zip](https://github.com/eclipse/sumo/files/6487820/map.net.zip)

And here is the version of `netconvert`:
``` bash
$ netconvert --version
Eclipse SUMO netconvert Version 1.9.1
 Build features: Linux-4.15.0-142-generic x86_64 GNU 7.5.0 Release Proj GUI SWIG GDAL GL2PS
 Copyright (C) 2001-2021 German Aerospace Center (DLR) and others; https://sumo.dlr.de

Eclipse SUMO netconvert Version 1.9.1 is part of SUMO.
This program and the accompanying materials
are made available under the terms of the Eclipse Public License v2.0
which accompanies this distribution, and is available at
http://www.eclipse.org/legal/epl-v20.html
SPDX-License-Identifier: EPL-2.0
```

**Comment by behrisch** [comment]
I am not sure where your input network comes from but this sounds broken to me. I am not even sure that netconvert will do anything useful with lanes that are 24m wide. Originally proj.scale was meant to handle input formats which give geo-coordinates in a "fixedpoint" notation so 5212345 for 52.12345. I think it is reasonable to apply it to coordinates only. My proposal would be to generate a plain XML representation (`netconvert --plain ...`) and then process this file with a script removing all superfluous attributes and rely on the defaults for lane width etc.

**Comment by namdre** [comment]
you can use `tools/xml/changeAttribute.py -f plain.edg.xml -o stripped.edg.xml -t edge -a width` to remove the width attribute.
