### ISSUE TITLE
Vehicles overlap on the road

### ISSUE THREAD

**Issue by Jianhua-Jiang** [eclipse/sumo#8632]
Even if I set “minGap = 2.5”, the vehicles will overlap on the road. But the distance between vehicles in the intersection is normal. When I increase the minGap value, the vehicles will not overlap on the road, but the vehicles in the intersection will keep a long distance, which is not reasonable.

**Comment by namdre** [comment]
What you are seeing is mostly like an artifact of custom road lengths: https://sumo.dlr.de/docs/Simulation/Distances.html#vehicle_lengths_in_sumo-gui

**Comment by namdre** [comment]
Did you check the length/geometry factor of the roads? It will be '1' on intersections and hence without distortion since their lengths are based on the geometry.
