### ISSUE TITLE
tls.guess-signals does not move signals to junction(-clusters) in lefthand network

### ISSUE THREAD

**Issue by ambuehll** [eclipse/sumo#8635]
related to #5953

When running netconvert with tls.guess-signals and a tls.guess-signals.dist of even more than 100n, signal heads don't get snapped to the junction. This is different to #5953, as all four legs have signals. 

This makes odd double tls at junctions when tls.uncontrolled-within = true.
As always, many thanks.

[files](https://drive.google.com/drive/folders/1f-RuZaV4VuvUakgTUro_HP79e2BD5H8-?usp=sharing)

![image](https://user-images.githubusercontent.com/48930860/118478793-94476a00-b710-11eb-8ecf-a7817bc003e4.png)
![image](https://user-images.githubusercontent.com/48930860/118478890-afb27500-b710-11eb-86be-f800e09ced24.png)
junction:cluster_109753_7580376905_7580376906_7580376909_7580376911
![image](https://user-images.githubusercontent.com/48930860/118478935-be009100-b710-11eb-9dcc-40f7a11fb373.png)
junction:cluster_1678452728_1678452732_21392089_26406639_3096561773_4076643814_7294710446_7294710449_7294710453_7294710458_7294710463

**Comment by namdre** [comment]
The multiple simple tls are all part of the input. The real issue was a coordinate transformation error that prevented signals.guess from finding the signals.

**Comment by ambuehll** [comment]
Thanks a lot - super fast as always!
