### ISSUE TITLE
question about the target lane of one vehicle 

### ISSUE THREAD

**Issue by Yangx97** [eclipse/sumo#8636]
Hello, I wanna use Traci to get the target lane of one vehicle at one simulation step (the lane that the vehicle will arrive at the next step)

I have tried traci.vehicle.getLateralSpeed(), but the results are always 0. I also tried traci.vehicle.getLaneChangeState(), but there are some unexpected values in the results (e.g., 0, 2^30)

Why? and is there any better solution to this problem?

Thanks !!

**Comment by namdre** [comment]
lateral speed is only used with sublane simulation: https://sumo.dlr.de/docs/Simulation/SublaneModel.html

getLaneChangeState returns a bitset that must be interpreted. You can use getLaneChangeStatePretty for a human-readable result.
