### ISSUE TITLE
Set the maxSpeed when using random.Trips to generate pedestrians

### ISSUE THREAD

**Issue by Jianhua-Jiang** [eclipse/sumo#8637]
How to set the maximum speed when using random.trips to generate pedestrians？Thanks！
Here are the commands I use. What options should I add？

python D:\AAAsofeware\sumo-1.6.0\tools\randomTrips.py -n a_del.net.xml --pedestrians -e 100000

**Comment by namdre** [comment]
add ` -t 'maxSpeed="2"' --vehicle-class pedestrian`

(type attributes are only added correctly if a vehicle-class is set - this must be pedestrian for pedestrians)

**Comment by Jianhua-Jiang** [comment]
> add ` -t 'maxSpeed="2"' --vehicle-class pedestrian`
> 
> (type attributes are only added correctly if a vehicle-class is set - this must be pedestrian for pedestrians)

I generate trips.xml. But when I use duarouter to convert it to Rou file, an error is reported.
Error: attribute value expected

I guess that there is no this element of plan definitions.

I can't define "maxSpeed" when I use this code.

    <person id="0" depart="0.00">
        <walk edges="1 2 3"/>
    </person>

https://sumo.dlr.de/docs/Specification/Persons.html#persons

**Comment by namdre** [comment]
Sorry, the code I sent works on linux only. A platform independent call is
`-t "maxSpeed=\"2\"" --vehicle-class pedestrian`

**Comment by Jianhua-Jiang** [comment]
> Sorry, the code I sent works on linux only. A platform independent call is
> `-t "maxSpeed=\"2\"" --vehicle-class pedestrian`

I generated this code after adding that.

    <person id="0" depart="0.00" maxSpeed="1.8" --vehicle-class pedestrian>
        <walk from="4i" to="2o"/>
    </person>

But when I use duarouter to convert it to Rou file, an error is reported.
Error: attribute name expected

**Comment by namdre** [comment]
It looks as if you placed quotes around all options. (and thereby include the option --vehicle-class pedestrian) as an argument of option **-t**.  Please post a screenshot of the cmd window with the command that you used.
