### ISSUE TITLE
route cost in MAROUTER and DUAROUTER

### ISSUE THREAD

**Issue by aminissn** [eclipse/sumo#8642]
Hi all,

I made a small test to compare the results of route cost from both MAROUTER and DUAROUTER. For this very small demand scenario, the cost values are very close to each other. However, I have experienced that under some congestion MAROUTER costs are extremely higher than the reality which may depend on edge class and capacityConstraintFunction. 
[muc_router.zip](https://github.com/eclipse/sumo/files/6501276/muc_router.zip)

**Comment by namdre** [comment]
one of the issues is to determine the appropriate road class for the capacityConstraintFunction. Some possibilities
1. use all edge probabilities in the network and map that range onto a fixed scale (the same thing is done with option **--weights.priority-factor**
2. use osm edge types when available
3. let the user provide a mapping from edge priorities to road classes via an option (i.e. a list of thresholds such as **--road-classes 3,8,10,13** (edge priority below 3 is road class 4, priority below 8 is road class 3, ...) with the standard sumo convention where a higher edge priority is "more important"

**Comment by aminissn** [comment]
The plots in the Jupyter Notebook were a bit misleading for a small demand scenario, thus, I ran another scenario with 100,000 cars. I think a fixed factor on certain edges can significantly reduce the size of the problem 
[sumoRouters.pdf](https://github.com/eclipse/sumo/files/6502030/sumoRouters.pdf)

**Comment by namdre** [comment]
This issue is strongly related to #5699

**Comment by behrisch** [comment]
My idea would be to make it independent of the priority and add it as parameters to the types (either really `param`s or some other child elements). This would give us configurable capacity functions.

**Comment by behrisch** [comment]
In analogy to restrictions we could define
```
<type id = ...>
    <capacity maxSpeed="10" parameter="1,2,3,4,5">
</type>
```
and the parameters are the ones which are currently hardcoded in ROMAAssignments.cpp

**Comment by aminissn** [comment]
I modified the ROMAAssignment.cpp in a way that all roads have a capacity of 1800 veh/h-lane and replaced capacityConstraintFunction with BPR function T = T0 + (1+0.15*(v/c)^4) and got extremely better results (95K cars randomly driving in Munich --> not empty roads but also not much congestion): 
![Capture](https://user-images.githubusercontent.com/30176885/118732800-4ed38b80-b83b-11eb-8a2e-10f30f58d662.PNG)
![Capture2](https://user-images.githubusercontent.com/30176885/118732866-732f6800-b83b-11eb-8cc8-a0718b115674.PNG)

**Comment by namdre** [comment]
As a first step we could simply add an option that sets the default parameters for all edges and ignores priorities. This would be a lightweight way to achieve the same good result, that @aminissn has demonstrated.

**Comment by behrisch** [comment]
@aminissn Thank you for the insights! Could you please check if you also get plausible results if you fix the roadClass to -1 in ROMAAssignments::getCapacity and ROMAAssignments::capacityConstraintFunction without changing the function itself?

**Comment by behrisch** [comment]
> 
> 
> As a first step we could simply add an option that sets the default parameters for all edges and ignores priorities. This would be a lightweight way to achieve the same good result, that @aminissn has demonstrated.

Yes and that option will be useful even if we implement the other solution as well.

**Comment by namdre** [comment]
> can this be linked to other applications that depend on road type? for example [#7243](https://github.com/eclipse/sumo/issues/7243)

What do you mean by linked? The configuration for #7243 works with the `<meso>` child-element of the type. I wouldn't want to put any maraouter parameters into the `meso` element. What would be the problem with adding another child element in every edge type definition?

**Comment by aminissn** [comment]
> > can this be linked to other applications that depend on road type? for example [#7243](https://github.com/eclipse/sumo/issues/7243)
> 
> What do you mean by linked? The configuration for #7243 works with the `<meso>` child-element of the type. I wouldn't want to put any maraouter parameters into the `meso` element. What would be the problem with adding another child element in every edge type definition?

Adding another child element is totally fine, it's just sometimes hard to get an overview of which parameters affect which part of the simulation/traffic assignment. I was mainly asking if all these parameters can be consistent in all applications. Since these are all related to the macroscopic behavior of edges, the parameters of MAROUTER such as capacity and capacityRestraintFunction can be changed simultaneously (~ be linked) with taus of the meso model. For example, for road-type highway.motorway if capacity is estimated (2500veh/h)*numLanes, then tau_ff can be also automatically be set to 3600/2500. In other words, making the default values of the child-element of the meso model consistent with MAROUTER default values.

**Comment by namdre** [comment]
Since the meso tau values are exclusive of the vehicle length you would at least have to make some assumptions about the length to convert them to veh/h. Also this veh/hr is just one of the parameters that goes into the constraint function. In short I'm not sure if there is a good way to enforce consistency but suggestions are welcome.

**Comment by behrisch** [comment]
@aminissn there is now an option `--capacity.default` which should trigger ignoring edge priority values

**Comment by behrisch** [comment]
With the invention of default capacities and the recent fix to the costs the remaining part should be handled with #5699
