### ISSUE TITLE
Bicycle will wait for the car to pass when it is far away

### ISSUE THREAD

**Issue by Jianhua-Jiang** [eclipse/sumo#8645]
I use sumo for simulation to control my car to turn left through the intersection (south to west). But when facing the opposite bicycle (north to south), the bicycle will stop waiting, and when there is no car in front of it, it will not drive until my car passes. What parameters can be set for bicycles to take precedence over cars, or for what other reason？Thanks!

**Comment by namdre** [comment]
I find your description unclear 
- "the bicycle will stop waiting" sounds as if the bike drives
- "it will not drive"  sounds as if it does not
Please attach a minimal scenario and describe the sequence of events that you would like to achieve.
