### ISSUE TITLE
traci.vehicle.setStop not working properly with MESO

### ISSUE THREAD

**Issue by jylee3302** [eclipse/sumo#8647]
Hello,

I'm using MESO option 1.9.1 ("--mesosim", "true", "--meso-overtaking", "true").

traci.vehicle.changeTarget(vehID, edgeID)
length = traci.lane.getLength(edgeID + "_0")
traci.vehicle.setStop(vehID, edgeID, startPos=length-0.5, pos=length, duration=9900, flags=traci.constants.STOP_PARKING)
is not working properly.

It's working (vehicle stops) with first few seconds, but after, the vehicle is treated as arrived and disappears from the simulation.
I've also tried duration = -1073741824.0 & other pos values, but the result is same. Vehicle stops for the first few seconds, but disappears later (suppose it's treated as arrived.)
No such issue in MICRO version SUMO.

Hope this helps.

**Comment by namdre** [comment]
might be working after all the latest meso stop fixes

**Comment by behrisch** [comment]
yes, it does
