### ISSUE TITLE
Transform SUMOTime to a class instead a typedef

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#8649]
I would like to transform SUMOTime to a class that inherits from long long int. All functions from SUMOTime will be implemented within this class.

The main goal is avoid duplicated code in SUMOSAXAttributes

**Comment by palvarezlopez** [comment]
@behrisch What do you think? Do you think that could have performance problems?

**Comment by behrisch** [comment]
I don't think it is  a good idea and probably not even possible: https://stackoverflow.com/questions/2143020/why-cant-i-inherit-from-int-in-c. I thin if we want to reduce code duplication there are better places ;-)
