### ISSUE TITLE
tls vanishes with larger junction.join-dist

### ISSUE THREAD

**Issue by ambuehll** [eclipse/sumo#8653]
Not sure if this behavior is expected:
When joining junctions with a larger join-dist threshold, tls vanishes.

**junction.join-dist = 10**
![image](https://user-images.githubusercontent.com/48930860/118822892-d1e6f700-b8b8-11eb-8640-ab6c1918a8a0.png)
**junction.join-dist = 20**
![image](https://user-images.githubusercontent.com/48930860/118822761-b7ad1900-b8b8-11eb-927d-32d8f0956216.png)

[files](https://drive.google.com/drive/folders/1f-RuZaV4VuvUakgTUro_HP79e2BD5H8-?usp=sharing)

Thanks, as always,

Lukas

**Comment by namdre** [comment]
Somewhat working as expected:

 By setting a larger join-dist, a larger cluster is considered for joining. This one is too large though and generates a warning:
"Warning: Reducing junction cluster 1237957495,1641773523,2512310242,2623962998,2623963000,2623963014,2623963018,2623968672,2623968676,2623968677,2623968679,2623968680,2623968683,2623968687,2623968690,2623968696,364282,4848681129,4848681131,5245754266,5245754267,5245754268,5896933794,5912280513,6400434432,6400434433,6986229751,6986229753,6986229754 (8 incoming edges)."

The critical junction that pushes the cluster of the edge is 364282
When reducing the too-big cluster to something that makes sense (heuristically), the end result is a smaller join compared to before:

with join-dist=10: cluster_2623963014_5245754266_5245754267_5245754268
with join-dist=20: cluster_2623963014_5245754266

However, the smaller cluster doesn't have the correct surrounding signals anymore so the signals-guess heuristic fails.

The recommended approach is too take a closer look at all junctions with a joining-related warning.
