### ISSUE TITLE
How to calculate the length of internal edge

### ISSUE THREAD

**Issue by zhangqi1008** [eclipse/sumo#8656]
dear sir:
    We found that the internal edge in net.xml has a specific length. What is the calculation rule for the length of this internal edge?

thx

**Comment by namdre** [comment]
the internal lane shape is a spline that smoothly connects incoming and outgoing lanes. By default, that spline consists of 1 or 5 line segments (configurable with netconvert option **--junctions.internal-link-detail**). The length of the internal lane is the sum of the line segment lengths with a hard minimum of 0.1m.

**Comment by zhangqi1008** [comment]
If the length of the internal edge we want to generate is 0.1, will it affect the road network?

**Comment by namdre** [comment]
you can set a custom length for each connection by setting its 'length' attribute. You can also set a default length to override the geometrical length with netconvert option **--default.connection-length**
