### ISSUE TITLE
"upgrading" footpaths does not add connections

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#8658]
If I add bicycles to the allowed list of a sequence of footpaths they are mostly still not used because connections are missing. Even if I "Reset Selected" in connections mode afterwards they are still missing. (Bonus points are awarded for finding a clever way to automate the connection reset when permissions are added to footpaths or at least issue a warning.)

**Comment by namdre** [comment]
reset selected requires the affected junctions to be selected, not the lanes/edges

**Comment by behrisch** [comment]
I did that, it did not work. Take for instance junction 831574725 in the Wildau network https://github.com/DLR-TS/sumo-scenarios/blob/master/Wildau/Netzmodell2.net.xml. I would expect resetting the junction should connect the bike lanes.

**Comment by behrisch** [comment]
The proposals do not cover exactly what I meant by "automated". I need something to remind me that after editing permissions I need to reset connections. Maybe we could just label junctions which have been patched or modified manually somehow and reset all the otherts which have been affected by the permission change?

**Comment by behrisch** [comment]
Furthermore I would like to have "reset connections" in the context menu of a junction.

**Comment by namdre** [comment]
> Furthermore I would like to have "reset connections" in the context menu of a junction.

That already exists

**Comment by behrisch** [comment]
My fault, just clicked the wrong element

**Comment by namdre** [comment]
There is a bug: reset connections buttion in connection mode doesn't mark the junction as "needs recompute"
