### ISSUE TITLE
sumo stop at some steps if use --grid.attach-length 

### ISSUE THREAD

**Issue by DayuanTan** [eclipse/sumo#8662]
I found sumo 1.9.1 and 1.9.2 stop st some steps if I use --grid.attach-length when I generate grid roadnet. But it works well if I don't use this option flag.

It prints no error log or anything. Just stop there and never continue. (It never continue at step 2236 in below screenshot)

<img width="1447" alt="image" src="https://user-images.githubusercontent.com/20853539/119016605-2301f400-b968-11eb-9cce-a32131b1513f.png">

I don't think my code has bugs. Because:
1. the previous 2235 steps works well.
2. I used sumo 1.3.1 before and it works well.

I am not 100% sure it is caused by "--grid.attach-length". But I have tried some roadnet generated witohut "--grid.attach-length" on sumo 1.9.2 and they work well.

The only difference I can see from my perspective is the sumo version and --grid.attach-length.

Any idea about how to fix it?

Thank you very much!

**Comment by DayuanTan** [comment]
I  have encountered same issue when I use a roadnet generated without --grid.attach-length option flag. This time it printed an error "Error: Answered with error to command 0xa4: Vehicle '4920' it not known."

**Comment by namdre** [comment]
The error indicates that the problem comes from your own traci script.  You are sending a command to a vehicle that isn't present in the simulation. Either handle the TraCIException with try/except or check for vehicle existence before the call
