### ISSUE TITLE
How Sumo Vehicle uses the Signal Phase Timing?

### ISSUE THREAD

**Issue by mahbub-iut** [eclipse/sumo#8672]
I'm planning to use SPaT and MAP messages to manage the intersections. From one of the issue I found, I need to make the Sumo Traffic light silent then possibly pass the SPaT message as a parameter in a device. However I am not finding how the vehicle is using the current Signal Phase information of Sumo. To be exact I am looking for the file where Vehicle is using the current signal state to make it's decision whether to enter an intersection or not

**Comment by namdre** [comment]
the timing part of a signal is currently only considered when the vehicle is equipped with a glosa device:
https://sumo.dlr.de/docs/Simulation/GLOSA.html
https://github.com/eclipse/sumo/blob/master/src/microsim/devices/MSDevice_GLOSA.cpp

The reaction to red/green happens at https://github.com/eclipse/sumo/blob/848bb3fb2ee4f6d84e6416e6d148ea0e1d254691/src/microsim/MSVehicle.cpp#L3048
You can make a vehicle ignore traffic light states: 
https://sumo.dlr.de/docs/Definition_of_Vehicles,_Vehicle_Types,_and_Routes.html#junction_model_parameters
