### ISSUE TITLE
About traci.vehicletype.copy()

### ISSUE THREAD

**Issue by thinker310** [eclipse/sumo#8673]
Hi everyone! Can I use traci.vehicletype.copy() to duplicate a type defined by a xml file? I attempt it but failed, could you tell me some solutions about that? Thank you in advance!
![image](https://user-images.githubusercontent.com/62609436/119293483-1097fb00-bc85-11eb-97b2-f44e1873d1fe.png)
![image](https://user-images.githubusercontent.com/62609436/119293622-6371b280-bc85-11eb-92c8-0cb8e440218f.png)
![image](https://user-images.githubusercontent.com/62609436/119293691-8a2fe900-bc85-11eb-8fa7-9a69b7d46883.png)

**Comment by m-kro** [comment]
You try to copy a vehicle type distribution, not a single vehicle type. Although in the XML vehicle definition you can reference either a vehicle type or a distribution, this does not work everywhere vehicle types come into play.

**Comment by namdre** [comment]
Traci currently does not allow to add/remove/copy vTypeDistributions (#2862)
