### ISSUE TITLE
reconsider semantics of speedMode

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#8675]
currently, it isn't possible to specify that a vehicle should ignore foes while on a junction without also ignoring it's immediate leader vehicle. (#8586)

Solutions
- add a new bit: ignore right-of-way for link leaders (foes on junction)
- apply right-of-way bit also for foes on junction

**Comment by behrisch** [comment]
proposal: more power to the user, add one bit

**Comment by namdre** [comment]
new bit must have inverted semantics (set to disable) in order to achive backward compatibility
