### ISSUE TITLE
large tls.guess-signals.dist and tls.discard-simple false

### ISSUE THREAD

**Issue by ambuehll** [eclipse/sumo#8677]
I am really sorry to bring this up again, but there is something that I still don't quite understand, when setting tls.discard-simple false. 
I thought the "simple" tls should be snapped to the junction, if **tls.guess-signals.dist** is large enough (and tls.guess-signals true). 
However, in the example, this does not happen - also with the new fix, which works fine when tls.discard-simple true.

When tls.discard-simple false: In the example below, there are 4 tls from OSM, they get interpreted as "simple", even though tls.guess-signals.dist is large enough (90m) to snap them to the intersection.

As far as I understand this is due to the following (?):
The simple tls is initiated as a junction on its own, before checking whether it is allowed to be snapped to the downstream intersection. Then, the only way to snap it is to increase junctions.join-dist (e.g. to 30m), which works in some cases (cluster_109753_7580376905_7580376906_7580376909_7580376911 -> cluster_109753_7580376900_7580376902_7580376904_7580376905_7580376906_7580376909_7580376910_7580376911), but does not in others (cluster_2623963014_2623963018_2623968676_2623968677_2623968679_2623968680_2623968683_5245754266_5245754267_5245754268_6400434432 ->2623963014 (too complex?)).

So is there another way to snap a simple tls within the tls.guess-signals.dist to the next downstream intersection?
Many thanks!
Lukas
[files](https://drive.google.com/drive/folders/1RMWUVXMd0YXkpph4iKEET9087A99Urd4?usp=sharing)

![image](https://user-images.githubusercontent.com/48930860/119543014-7ae99200-bd90-11eb-8a17-95439c33cf9b.png)
![image](https://user-images.githubusercontent.com/48930860/119543936-7f627a80-bd91-11eb-9853-30822ca2babe.png)

**Comment by namdre** [comment]
Your network has two simple tls on each approach (since pedestrian crossings are also interpreted as simple tls). Consequently only the one closer to the junction gets "snapped" while the other one remains.
In many locations only the pedestrian crossing or the tls node are present in the osm database, hence the current interpretation.

**Comment by ambuehll** [comment]
OHHHH. I see the pedX! thanks! sorry about the confusion.
