### ISSUE TITLE
How to define a number of vehicle types in batch using OD demand?

### ISSUE THREAD

**Issue by JianGong-seu** [eclipse/sumo#8678]
For example, I want to randomly define 30% vehicles belong to "vtype 1", and others are "vtype 2". How to operate it in xml file? I define traffic demand using OD matrix.

**Comment by namdre** [comment]
set od2trips option **--vtype myTypeDist** and then define a `<vTypeDistribution id="myTypeDist">` with the desired types and probabilities: https://sumo.dlr.de/docs/Definition_of_Vehicles,_Vehicle_Types,_and_Routes.html#vehicle_type_distributions

**Comment by JianGong-seu** [comment]
> set od2trips option **--vtype myTypeDist** and then define a `<vTypeDistribution id="myTypeDist">` with the desired types and probabilities: https://sumo.dlr.de/docs/Definition_of_Vehicles,_Vehicle_Types,_and_Routes.html#vehicle_type_distributions

Thank you sir. You help me a lot.
