### ISSUE TITLE
Junctions-join specified by batch operation

### ISSUE THREAD

**Issue by zhangqi1008** [eclipse/sumo#8680]
dear sir
      In netedit, Button F7 can be used to join selected junctions. But if there are many situations where junctions need to be joined, manual methods are more troublesome. Does netconvert have a function that can replace this manual join in netedit? Or, is there a way to enter a list as the id of the specified junction to wake up the function of junctions-join?

thank

**Comment by namdre** [comment]
see https://sumo.dlr.de/docs/Networks/PlainXML.html#joining_nodes
