### ISSUE TITLE
Test update path

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#8689]
We are not sure what the installer does (not even what it should do) if SUMO is already installed. Probably (automatically) removing the old installation and installing fresh is the safest option. There should be no user data in the installation dir. The $HOME/Sumo dir should be kept of course

**Comment by schwamborn** [comment]
This is what I get when trying to install `sumo-win64-1.9.2.msi` over an existing sumo 1.7.0 installation on Windows 10:

![Capture](https://user-images.githubusercontent.com/35012744/121381830-5a036e00-c946-11eb-90c7-59f18429dae5.PNG)

**Comment by schwamborn** [comment]
On another note, the default installation path for 64-bit version of SUMO was
`C:\Program Files (x86)\Eclipse\Sumo\`
for me. Shouldn't it be
`C:\Program Files\Eclipse\Sumo\`
instead?

**Comment by schwamborn** [comment]
Recent test to install `sumo-win64-1.12.0.msi` over an existing sumo 1.9.2 installation on Windows 10 results in overwriting earlier version. Old files like `libsumo-1.9.2.jar` remain, though.

**Comment by schwamborn** [comment]
Even a fresh installation of SUMO 64-bit is currently installed under ` C:\Program Files (x86)\Eclipse\Sumo\`. We might want to add code that chooses the correct Program Folder depending on the architecture.

**Comment by behrisch** [comment]
see #4242

**Comment by schwamborn** [comment]
Closing since this issue should be fixed by 4b2b657, i.e., the old installation is removed when upgrading.
