### ISSUE TITLE
questions about adding vehicle in a circle route

### ISSUE THREAD

**Issue by miracelplus** [eclipse/sumo#8691]
Hello,

I am trying to use traci to add vehicles in a circle route. In the documentation of traci, I found that https://sumo.dlr.de/docs/TraCI/Add_Vehicle.html tells me that we can add vehicle using the route, the laneid of the initial edge and the insert position to add vehicles to a certain route, without knowing the actual edge of the inserted vehicle. However, when I search the python traci documentation, I notice that we can only add the vehicle with the DepartureLane ("best", "first", ...) using add, addFull, addLegacy.

I wonder if there are some approaches using python traci to add vehicles only using the route, the initial laneid at the initial edge and the inserted position and speed. Or I have to insert the vehicle and manually move it to the given edge and lane id? 

Thanks a lot!

**Comment by namdre** [comment]
- vehicle.add will always insert vehicles on the first edge of the route
- if you want to start somewhere in the middle of the route you may call vehicle.moveTo after vehicle.add
- parameter departLane can also be used with numbers: `departLane="1"` but you cannot give a full laneID here, only the index.
