### ISSUE TITLE
gtfs2pt enable begin and end definition

### ISSUE THREAD

**Issue by ArmelliniMG** [eclipse/sumo#8697]
Allow the user to set the begin and end time to import public transport.
Since some GTFS definitions are not consistents with day times (from 00:00 to 23:59) the departure times should be adapted to avoid data gaps.
The route-output file should be renamed to the .add extension.

**Comment by behrisch** [comment]
If I define begin 0:23:00:00 and end 2:03:00:00 I would expect a complete day inbetween but it only extracts the time slices 0:23:00:00 to 0:23:59:59 and 1:23:00:00 to 1:23:59:59
