### ISSUE TITLE
getFollower() function issue when entering junction (using TraCI with Python)

### ISSUE THREAD

**Issue by Ozgenur** [eclipse/sumo#8701]
Hi,
I’m reaching out to report an issue we have run into in SUMO. Here is the information about the issue:
•	We are using SUMO 1.8.0 and Windows 10 64-bit OS.
•	When running SUMO with Python, we believe there is an issue regarding getting follower vehicle information using the getFollower() Python function. Whenever the ego vehicle is crossing the stop bar on a road network, the getFollower() function returns (“”,-1.0), meaning that no follower vehicle is detected, even though there is clearly a follower vehicle in the sumo-gui. We have replicated this issue on 2 different networks, the first one being the example in the doc\tutorial\traci_tls and another network file we have created.
•	In the following picture, you can see that I’m printing the ego vehicle position (“right_2”) and the follower vehicle number and distance between the ego and the follower vehicle to the Windows command window. When the vehicle is just travelling on the network, the getFollower() function returns the follower vehicle ID (“right_3”).
 
![image](https://user-images.githubusercontent.com/14892842/119901018-5669f300-bf13-11eb-9015-6cc53984009d.png)

•	Now, you can see the ego vehicle crossing the stop bar and the result of the getFollower() function returning the following: (“”,-1.0), meaning that there is not a follower (empty) and the distance between the ego vehicle and the follower vehicle is -1. However, the sumo-gui clearly shows that there is a follower (“right_3”) vehicle behind the ego (“right_2”). This happens at simulation time step 47. Once the simulation is run 1 more step, the ego vehicle leaves the junction and no part of the ego vehicle touches the stop bar, and the ego vehicle starts detecting the follower vehicle again. 

![image](https://user-images.githubusercontent.com/14892842/119901037-5ec22e00-bf13-11eb-8c3b-97c922950d5d.png)

•	I also checked the getLeader() function during the simulation for different junctions and traffic networks, however, the same issue of not being able to detect the vehicle does not happen in that function, the leader vehicle is always detected by the ego vehicle, even when the ego vehicle is touching and crossing the stop bar when it is entering a junction. Why do you think the ego vehicle stops detecting follower vehicles and the getFollower() function returns wrong values, when the ego vehicle touches or crosses the stop bar when it is entering a junction? 
•	I have put everything to replicate the issue in the attached zip file. If you run runner_OKT_v1.py from the command window, you can repeat the procedure and replicate the problem. 
Thanks!

[getFollower_sumo_python.zip](https://github.com/eclipse/sumo/files/6556988/getFollower_sumo_python.zip)

**Comment by namdre** [comment]
root cause is #4727

**Comment by odajani** [comment]
Hi
We have similar issue regarding getting follower vehicle information using the getFollower() function whenever ego “host”  vehicle is crossing road junction, the getFollower() function returns (“”,-1.0) even though there is follower vehicle in sumo-gui   
But when using getLeader() the leader vehicle is always identified.  Are getFollower() and getLeader()  similar implementation?     

It would be great if this issue is fixed in next release and if it is possible to provide timing when this issue is solved ? 
Thank you for great tool

**Comment by namdre** [comment]
the issue is already solved in this version: https://sumo.dlr.de/daily/sumo-win64-git.msi
The next officiel release is scheduled for Agust: https://github.com/eclipse/sumo/milestones

**Comment by odajani** [comment]
thank  you
