### ISSUE TITLE
invalid vaporizer attributes

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#8706]
documentation is wrong and netedit defines the wrong attributes

**Comment by namdre** [comment]
xsd validation should have rejected all vaporizers written by netedit. @palvarezlopez  any idea why this wasn't found earlier?

**Comment by palvarezlopez** [comment]
> xsd validation should have rejected all vaporizers written by netedit. @palvarezlopez any idea why this wasn't found earlier?

Because originally it was correct, but during implementation of new AdditionalHandler I used the Documentation as reference, and I changed it  :(
