### ISSUE TITLE
How to plot  output of several method  in one figure?

### ISSUE THREAD

**Issue by JianGong-seu** [eclipse/sumo#8707]
I design several methods to run traffic using traci in sumo. I want to compare the total fuel and emission of these methods, and plot the outputs results in one figure. Is there any visualization tool can be easily used to plot the total fuel and emission of simulation?

**Comment by namdre** [comment]
No. You have to post-process the output files for that.  https://sumo.dlr.de/docs/Tools/Output.html#attributestatspy can give you statistics (also in xml format) including the mean of any given attribute (i.e. total emissions) but you still have to do your own plotting from this.
