### ISSUE TITLE
Can repeat tripType?

### ISSUE THREAD

**Issue by GyeongtaeGim** [eclipse/sumo#8708]
I want repeat tripType, not vehicleType.
can do this ?

**Comment by namdre** [comment]
Yes. Flows also support a trip-like definition:
see https://sumo.dlr.de/docs/Definition_of_Vehicles,_Vehicle_Types,_and_Routes.html#repeated_vehicles_flows

**Comment by GyeongtaeGim** [comment]
unfortunately,  i already check flowType.
i want just setting "from" and "to" attribute. 

Any way is fine. like TraCI... or xml settings... other vehicleType..
if can't do this, that's ok.  because i'm just testing SUMO. then i'll just using flowType that you recomanded

thank you for your answer.

**Comment by GyeongtaeGim** [comment]
> Yes. Flows also support a trip-like definition:
> see https://sumo.dlr.de/docs/Definition_of_Vehicles,_Vehicle_Types,_and_Routes.html#repeated_vehicles_flows

unfortunately, i already check flowType.
i want just setting "from" and "to" attribute.

Any way is fine. like TraCI... or xml settings... other vehicleType..
if can't do this, that's ok. because i'm just testing SUMO. then i'll just using flowType that you recomanded

thank you for your answer.

**Comment by namdre** [comment]
> unfortunately, i already check flowType.
> i want just setting "from" and "to" attribute.

You can define `<flow from="..." to="..." .../>`
