### ISSUE TITLE
missing GTFS dataset link

### ISSUE THREAD

**Issue by angelobanse** [eclipse/sumo#8709]
in the [GTFS Tutorial](https://sumo.dlr.de/docs/Tutorials/GTFS.html#finding_a_data_source_for_gtfs) the "June 2019 dataset by VBB" link is not working.

**Comment by ArmelliniMG** [comment]
Micha @behrisch, the website from VBB has changed and the old GTFS data is not available any more. Should we just load the dataset to the server, as you did with the first version? See: "To keep this tutorial stable, the file has been mirrored at https://sumo.dlr.de/daily/GTFS_VBB_Juni-Dezember-2016.zip."

**Comment by behrisch** [comment]
yes
