### ISSUE TITLE
HOW CAN I GET THE TRAFFIC LIGHT'S PHASE LEFT TIME INFROUNT THE BUS I CREATE??

### ISSUE THREAD

**Issue by kibico** [eclipse/sumo#8710]
Caution : In a SUMO-TLS definition, time is on the vertical axis and each phase describes all signal states that last for a fixed duration. This differs from typical traffic engineering diagrams where time is on the horizontal axis and each row describes the states for one signal. _Another crucial difference is, that in SUMO a new phase is introduced whenever at least one signal changes its state. This means that transitions between green phases can be made up of multiple intermediate phases._
I wanna get the traffic light remain time to change the bus's peed.
Please help me !Thanks!

**Comment by Domsall** [comment]
This sounds like a use-case for the new GLOSA device. You can get some information on the website
https://sumo.dlr.de/docs/Simulation/GLOSA.html, in #7721 or in the Source Code.

**Comment by namdre** [comment]
also, see 
- getNextTLS at https://sumo.dlr.de/docs/TraCI/Vehicle_Value_Retrieval.html
- getNextSwitch at https://sumo.dlr.de/docs/TraCI/Traffic_Lights_Value_Retrieval.html
