### ISSUE TITLE
FatalTraCIError: SUMO Crash

### ISSUE THREAD

**Issue by philippwulff** [eclipse/sumo#8714]
Unfortunately I encountered another error. This time I have no idea what I might be doing that is causing this :(. I am using `setPreviousSpeed` and `moveTo` frequently here...

The correct traci command log:
[FatalTraciError.zip](https://github.com/eclipse/sumo/files/6583853/FatalTraciError.zip)

**Comment by philippwulff** [comment]
I am using the newest Dev Version of SUMO.

**Comment by namdre** [comment]
The zip doesn't include a network file. Is it supposed to include all files for reproducing the crash?

**Comment by philippwulff** [comment]
Oh, sorry. I forgot to include the file. I edited the first comment and added the correct `.zip`.
