### ISSUE TITLE
How to define capacity (traffic density) for a lane

### ISSUE THREAD

**Issue by amiradavoudi** [eclipse/sumo#8720]
Hello,

Would you please help me how I can define the capacity (traffic density) for a lane? For example, I want to generate traffic with randomTrips.py in a way that I can make sure there are 100 cars moving on each lane.

How should I calculate the length of each lane, the speed of cars so that the capacity of each lane is for example 100 cars/sec? 

My cars are generated at the middle of each lane and not the start of the lane in my scenario.
Is it possible to calculate the period option in a way that we guarantee such a capacity?
 
I saw a formula on the SUMO website which is -b t0 -e t1 -p ((t1 - t0) / n). I am not sure if I can define capacity by the notion of this formula.

The link https://sumo.dlr.de/docs/FAQ.html#how_do_i_get_high_flowsvehicle_densities (part: How do I insert vehicles with a fixed density?) used the notion of flow but in my scenario, I don't want to use this notion for some reasons, and so I have to define one trip for each vehicle as follows:
`<trip id="0" depart="25200.00" from="A3B3" to="F3G3"  departSpeed="2" departPos="50.05" arrivalPos="-50.1"/>
...
`

Thank you in advance for your help.

**Comment by namdre** [comment]
You cannot achieve this with randomTrips (except for the trivial case where there is only a single route through the network). 
Even if you were to achieve the desired rate of insertion on each edge, cars with different routes would randomly meet on some edges and exceed the counts.

Instead, you can use the output of randomTrips and combine it with routeSampler.py to create a scenario that matches desired traffic counts: https://sumo.dlr.de/docs/Tools/Turns.html#routesamplerpy

**Comment by amiradavoudi** [comment]
Thank you very much for your answer.
