### ISSUE TITLE
why is there no vehicle stand in the middle lane?

### ISSUE THREAD

**Issue by zhaotuo0815** [eclipse/sumo#8725]
hello，sumo developer,I have met some trouble when i use sumo,my question is that the no vehicle stand in the middle lane,like the picture.....thank you for your help!
![1](https://user-images.githubusercontent.com/59630993/121013858-f3f2db80-c7cb-11eb-9f93-3474b22066db.png)
![2](https://user-images.githubusercontent.com/59630993/121013861-f5240880-c7cb-11eb-953a-46b27c549684.png)

**Comment by namdre** [comment]
possibly, the vehicles have a strategic preference for the rightmost lane. How does their route continue after the intersection?
If their route ends after the junction, try setting arrivalLane="1"
