### ISSUE TITLE
[bug] Non-smooth heading signal

### ISSUE THREAD

**Issue by jonasmmiguel** [eclipse/sumo#8727]
In some cases, a vehicle might make a turn in a way that heading changes abruptly over time. 

Is this an expected behavior? Is there a way to mitigate this?

That is currently important in my use case, where I'm estimating yaw rates based on the rate of change in heading, which I obtain at every timestep via traci.vehicle.getAngle(veh_id). 

So far, I've tried to overcome this by (a) smoothing intersection corners via "--junctions.corner-detail 500", (b) increasing the spatial resolution in lateral motion resolution via "--lateral-resolution 0.2" and (c) increasing simulation temporal resolution via "--step-length 0.005".

Here is an example case, which includes a small video demonstrating the behavior, alongside the .sumocfg, net.xml, rou.xml files I'm using.
[arc-de-triomphe.zip](https://github.com/eclipse/sumo/files/6611370/arc-de-triomphe.zip)

Thank you guys for this great tool!

**Comment by namdre** [comment]
Junctions corner detail has purely visual effect. To obtain smoother turning geometry, you may set netconvert option **--junctions.internal-link-detail**.  Increasing junction size (attribute 'radius') will also help.
