### ISSUE TITLE
How to modify the departlane of all vehicles in Traci?

### ISSUE THREAD

**Issue by JianGong-seu** [eclipse/sumo#8728]
How to modify the attributes of departLane of all vehicles in Traci? Where should orders be added?

**Comment by namdre** [comment]
If you use traci.vehicle.add you can use parameter "departLane". If you load the vehicles from XML you may set xml attribute "departLane". 
You cannot modify the departLane of an xml-defined vehicle via TraCI but you can force it into the network on any route lane with traci.vehicle.moveTo

**Comment by JianGong-seu** [comment]
> If you use traci.vehicle.add you can use parameter "departLane". If you load the vehicles from XML you may set xml attribute "departLane".
> You cannot modify the departLane of an xml-defined vehicle via TraCI but you can force it into the network on any route lane with traci.vehicle.moveTo

Yes，I mean how to set xml attribute "departLane" of all vehicles before load vehicles

**Comment by namdre** [comment]
See https://sumo.dlr.de/docs/Definition_of_Vehicles,_Vehicle_Types,_and_Routes.html#available_vehicle_attributes
If you use tools such as od2trips, randomTrips.py or routeSamper.py they have their own options for setting departLane in written xml

**Comment by JianGong-seu** [comment]
> See https://sumo.dlr.de/docs/Definition_of_Vehicles,_Vehicle_Types,_and_Routes.html#available_vehicle_attributes
> If you use tools such as od2trips, randomTrips.py or routeSamper.py they have their own options for setting departLane in written xml

Thank you,sir. I try

**Comment by JianGong-seu** [comment]
> See https://sumo.dlr.de/docs/Definition_of_Vehicles,_Vehicle_Types,_and_Routes.html#available_vehicle_attributes
> If you use tools such as od2trips, randomTrips.py or routeSamper.py they have their own options for setting departLane in written xml

I use od2trips. Is it right to set the options in od2trips.config.xml?

**Comment by namdre** [comment]
od2trips supports option `<departlane value="..."/> in it's configuration.
