### ISSUE TITLE
How to handle the attached warnings in a scenario

### ISSUE THREAD

**Issue by amiradavoudi** [eclipse/sumo#8729]
Hello,

I have randomly generated some trips using the randomTrips.py. When I run the simulation, SUMO gives me several warning as follows:
```
Warning: Teleporting vehicle '5'; collision with vehicle '44', lane='B2B3_0', gap=-0.73, time=156.00 stage=move.
Warning: Vehicle '5' ends teleporting on edge 'B3C3', time 156.00.
Warning: Teleporting vehicle '1'; collision with vehicle '34', lane='F3G3_0', gap=-3.94, time=163.00 stage=move.
Warning: Vehicle '1' teleports beyond arrival edge 'F3G3', time 163.00.
Warning: Teleporting vehicle '35'; collision with vehicle '41', lane='F3G3_0', gap=-4.27, time=170.00 stage=move.
Warning: Vehicle '35' teleports beyond arrival edge 'F3G3', time 170.00.
Warning: Vehicle '44' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=202.00.
```
What are the solutions for solving these warnings?
Thank you in advance for your help.

Best regards,
Adavoudi
[test.zip](https://github.com/eclipse/sumo/files/6614160/test.zip)

**Comment by namdre** [comment]
Collisions can have many reasons of which the most likely ones are
- unsafe parameters
- unsafe junction design
- simulator bugs
See https://sumo.dlr.de/docs/Simulation/Safety.html

If you cannot identify unsafe parameters, attach the scenario for investigation.

**Comment by amiradavoudi** [comment]
Thank you very much. I will attach the files.

**Comment by namdre** [comment]
Your junction type is set to "unregulated" which means, no traffic rules are applied. If you want a junction without a traffic light use 'priority', 'right_before_left' or 'allway_stop' : https://sumo.dlr.de/docs/Networks/PlainXML.html#node_types

**Comment by amiradavoudi** [comment]
> Your junction type is set to "unregulated" which means, no traffic rules are applied. If you want a junction without a traffic light use 'priority', 'right_before_left' or 'allway_stop' : https://sumo.dlr.de/docs/Networks/PlainXML.html#node_types

Thank you very much for your help.
