### ISSUE TITLE
How to modify the priority of the connections of an intersection？

### ISSUE THREAD

**Issue by JianGong-seu** [eclipse/sumo#8734]
For example，at an typical symmetrical dual-lane intersection with four approaches（only two lanes， i.e., straight and left-turn lane）, I want to set four straight connections with same higher priority, and four left-turn connections with low priority. How to operate it in net.XML or using netedit?

**Comment by namdre** [comment]
With priority, do you mean "right-of-way" or "vehicle-preference"?

**Comment by JianGong-seu** [comment]
> With priority, do you mean "right-of-way" or "vehicle-preference"?

right-of-way
