### ISSUE TITLE
can’t run sumo-gui app on macOs big sur

### ISSUE THREAD

**Issue by arita89** [eclipse/sumo#8747]
Followed instructions as per: https://sumo.dlr.de/docs/Installing/index.html 

All installations successful, but if I try to run the gui (both from terminal or opening from the Applications) nothing happens. 
Help would be appreciated. 
Cheers
A.

**Comment by angelobanse** [comment]
Which XQuartz version are you using?

**Comment by arita89** [comment]
2.8.1

**Comment by schwamborn** [comment]
Have you also followed this?

> After the installation you need to log out/in in order to let X11 start automatically, when calling a gui-based application like sumo-gui. (Alternatively, you may start X11 manually by pressing cmd-space and entering XQuartz).

**Comment by arita89** [comment]
yes i did.

**Comment by schwamborn** [comment]
OK, then please:

- execute command `xclock` in your Terminal and report what happens.
- report all output after executing `sumo`, followed by `sumo-gui` in Terminal.

**Comment by angelobanse** [comment]
additionally - if you are using the Application launchers, make sure to have the SUMO_HOME environment variable set

**Comment by arita89** [comment]
> echo $SUMO_HOME
/usr/local/bin/sumo

>  sumo
Eclipse SUMO sumo Version 1.9.2
 Build features: Darwin-19.6.0 x86_64 Clang 12.0.0.12000032 Release Proj GUI
 Copyright (C) 2001-2021 German Aerospace Center (DLR) and others; https://sumo.dlr.de
 License EPL-2.0: Eclipse Public License Version 2 <https://eclipse.org/legal/epl-v20.html>
 Use --help to get the list of options.

> xclock 
and
> sumo-gui

return nothing, no error. 

I must be doing something silly.

**Comment by schwamborn** [comment]
If even `xclock` doesn't do anything for you, it points to an issue with your XQuartz and not sumo-gui itself. `xclock` relies on an X server (provided by XQuartz) an should open a small window with a clock. You might want to try out a different XQuartz version like XQuartz 2.7.11 or just try rebooting if you haven't done so, yet.

**Comment by arita89** [comment]
I will try with rebooting and using another version then. 
thanks!

**Comment by schwamborn** [comment]
Please also report back if it worked for you.

**Comment by arita89** [comment]
Hello, sorry for the late reply.
Rebooting didnt work, but before i started using different versions I managed to have SUMO running directly on the server, instead of locally (which would have been my backup option in case of issues on the server). 
So I dropped the local installation. Maybe I tinkered around to much with the Display ports.
thanks for the support tho
