### ISSUE TITLE
How to find which path is the shortest

### ISSUE THREAD

**Issue by amiradavoudi** [eclipse/sumo#8751]
Hello,

Assume that in my scenario, I have 3 shopping center and the vehicles will choose a shopping center which is close to them in terms of distance. How can I find out which center is close to a vehicle? Should I first calculate all the routes between the shopping centers and a vehicle and then select the smallest one? 
Which command should I use for this purpose? I mean how can I compute the distance between two nodes in SUMO?

Thank you.
Best,
Amirhossein

**Comment by namdre** [comment]
Yes. Generally, you'll have to compute all 3 route (using traci.findRoute).
If you have many more potential destinations you might define a TAZ that has all the destinations as edges and then find a route to the TAZ. This would be marginally faster to compute.
https://sumo.dlr.de/docs/Definition_of_Vehicles,_Vehicle_Types,_and_Routes.html#traffic_assignment_zones_taz
