### ISSUE TITLE
randomtrips (--validate) + duarouter = error

### ISSUE THREAD

**Issue by ambuehll** [eclipse/sumo#8756]
related in a way to #7347

I would like to run randomtrips.py on a large network, get trips and then run duarouter with some options as weights-random for stochasticity in the routes.
The issue is that I get the following when running duarouter (after randomtrips):
> Error: Route '!15' (vehicle '15') is not valid.
Quitting (on error).

This happens also when I validate my trips with --validate in randomtrips. 

I first run: 
`randomTrips.py -n LON.net.xml -p 0.5 --fringe-factor 1.2 --min-distance 500 --max-distance 50000 --end 1800 -o tripsrand.rou.xml --seed 10 --validate`
then:
`duarouter -n LON.net.xml -t tripsrand.rou.xml -o random2.rou.xml --randomize-flows true --routing-threads 10 --weights.random-factor 2 --routing-algorithm CH --ignore-errors true`

[files](https://drive.google.com/drive/folders/11MtWmCsDshJlf1wp6CTzFhxaUpzwl444?usp=sharing)

Thanks as always.

**Comment by namdre** [comment]
CH isn't so good in intermodal networks.
solution: use CHWrapper instead of CH. 
To be fixed via #8763
