### ISSUE TITLE
Connecting to running Simulation using libtraci

### ISSUE THREAD

**Issue by mahbub-iut** [eclipse/sumo#8757]
I'm trying to connect to a running simulation using libtraci but not finding any method to do so. I suppose I should use this function
https://github.com/eclipse/sumo/blob/a29b8df55d2a8cb2f2b6c16dc0e8a8a47f4c3f77/src/libtraci/Connection.cpp#L46
but not being able to use that after including libsumo/libtraci.h . Any example to do that would be really helpful

**Comment by behrisch** [comment]
Did you try https://sumo.dlr.de/docs/Libtraci.html?

**Comment by mahbub-iut** [comment]
> Did you try https://sumo.dlr.de/docs/Libtraci.html?

Hi I tried this and it works fine  but I want to simulate a scenerio where Sumo is gonna work as a server and multiple traci clients are gonna intereact with the simulation ... Thats what I am failing to do with libtraci ..Thanks

**Comment by mahbub-iut** [comment]
This piece of code can connect to a Sumo simulation running in localhost at port 4001  ... However libtraci fails to handle multiple traci connection as mentioned in #8773 

#include <libsumo/libtraci.h>

using namespace libtraci;
int main () {
Simulation::init(4001,21,"localhost");
for (int i = 0; i < 500000; i++) {
Simulation::step();
}
Simulation::close();
return 0;
}
