### ISSUE TITLE
libtraci fails while trying to connect from multiple traci client

### ISSUE THREAD

**Issue by mahbub-iut** [eclipse/sumo#8773]
I'm trying to connect to the Sumo simulation from multiple traci clients using libtraci. This is how I'm starting the simulation:

**sumo --remote-port 4001  --num-clients  2 -c config_file.sumocfg** 

After starting the simulation I'm trying to connect from two traci client using the code below:

`#include <libsumo/libtraci.h>

using namespace libtraci;
int main  () {
Simulation::init(4001,21,"localhost");
Simulation::setOrder(3);
 for (int i = 0; i < 500000; i++) {
         Simulation::step();
    }
        Simulation::close();
return 0;
}`

And I'm giving different order values in each of the clients but simulation stops with the following error:

terminate called after throwing an instance of 'libsumo::TraCIException'
  what():  #Error: received status response to command: 3 but expected: 2
Aborted (core dumped)

However, If I run the simulation from a single traci client simulation works perfectly fine ... Let me if this is a bug or I'm doing something wrong ...Thanks

**Comment by namdre** [comment]
sounds like a bug
