### ISSUE TITLE
invalid junction rules when setting contPos for a yielding connection

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#8776]
intent: letting vehicles from a side road wait further into the junction (i.e. past a pedestrian crossing.
problem: vehicles at an internal junction assume priority for waiting on the junction over some other vehicles where those vehicles actually have right of way and ignore them

**Comment by namdre** [comment]
possibly fixed via #11160

**Comment by behrisch** [comment]
@namdre so it can be closed?
