### ISSUE TITLE
Cannot install SUMO 1.8.0 on Mac through homebrew

### ISSUE THREAD

**Issue by myzWILLmake** [eclipse/sumo#8780]
I tried `brew install sumo@1.8.0` and got the error:
```
curl: (22) The requested URL returned error: 403 Forbidden
Error: Failed to download resource "sumo@1.8.0"
Download failed: https://dl.bintray.com/dlr-ts/bottles-sumo/sumo%401.8.0-1.8.0.catalina.bottle.tar.gz
```

I found that bintray.com stopped service, so this file is forbidden to get accessed.
I want to use veins on mac and it requires version 1.8.0 of sumo.
By now I downloaded the formula of 1.9.0 manually, changed the sumo archived file to 1.8.0 and installed it on my mac.

**Comment by schwamborn** [comment]
You can still build v1.8.0 from source: `brew install --build-from-source sumo@1.8.0`

**Comment by schwamborn** [comment]
Removed bintray links in older formulas (DLR-TS/homebrew-sumo@fdb1092a0157c57e213e372f2bacd1adfdb54260).
