### ISSUE TITLE
missing crossing when importing the network from OSM Wildau 

### ISSUE THREAD

**Issue by PaulineHartwig** [eclipse/sumo#8782]
When importing the network (Wildau) from OSM, there are no crossings for pedestrians or there are only a few possibilities to cross the streets.

In addition, the transitions at traffic lights are incorrectly positioned. The transitions are placed too far in the intersection. In reality, the holding lines are shifted slightly to the rear.

**Comment by behrisch** [comment]
@PaulineHartwig Please add links to the OSM input either by attaching the (possibly gzipped) osm.xml to this ticket or uploading it in the Wildau repo. And mention the exact junctions in question.

**Comment by PaulineHartwig** [comment]
[osm_wildau.net.zip](https://github.com/eclipse/sumo/files/6701899/osm_wildau.net.zip)
![rrrrr](https://user-images.githubusercontent.com/80676652/123099240-4bcb4c80-d432-11eb-8a1f-f7216569c403.PNG)
![ffvv](https://user-images.githubusercontent.com/80676652/123099256-50900080-d432-11eb-8976-060b2885c015.PNG)

Here are two examples, where crossings are missing (id= 439912279, id=2289279265)

**Comment by namdre** [comment]
The osm input is still missing from https://github.com/DLR-TS/sumo-scenarios/tree/master/Wildau

**Comment by PaulineHartwig** [comment]
[osm.net.zip](https://github.com/eclipse/sumo/files/6731616/osm.net.zip)

**Comment by namdre** [comment]
> [osm.net.zip](https://github.com/eclipse/sumo/files/6731616/osm.net.zip)

The archive contains osm.net.xml which is a sumo network file. We need the raw OSM data instead.

**Comment by PaulineHartwig** [comment]
[osm_bbox.osm.zip](https://github.com/eclipse/sumo/files/6734762/osm_bbox.osm.zip)

**Comment by namdre** [comment]
The road "Bachstelzengang" at 439912279 is classified as highway.residental and the typemap specifies that it should receive a sidewalk (and consequently disallow pedestrians on the traffic lanes).
However, the OSM data contains the `sidewalk=none` and thus no sidewalk is built. 
As a consequence the road completely disallows pedestian traffic (bug) and as a corollary no crossing is build there since the pedestrians have nowhere to go.

The correct solution would be to add pedestrian permissions to the rightmost lane of that edge.
No crossing would be built in this case either (since there are no forbidden lanes to cross) and the junction would contain a single walkingarea instead. 

It might be useful to only apply this solution for edges with a single lane, otherwise sidewalk=none probably implies that pedestrians are forbidden there.

**Comment by namdre** [comment]
At 2289279265 the crossing is guessed as expected. Please specify the exact problem there.

**Comment by namdre** [comment]
Regarding the placement of crossings at traffic light junctions: (i.e. 31511424)
![Screenshot from 2021-07-01 17-02-51](https://user-images.githubusercontent.com/6240630/124146585-31c2e700-da8e-11eb-9c4c-6b3318304622.png)

There are several issues at play here:
- OSM does not record junction size or radius
- The default sidewalk width (which implicitly enlarges junction size) is 2m for that road class even though it's probably at least 3m in reality at that location.  This could in principle be read from OSM (https://wiki.openstreetmap.org/wiki/Sidewalks#Sidewalk_as_refinement_to_a_highway) but the data is missing for Wildau
- The default crossing width is 4m which looks to wide at such a small junction. Related to #3709

One solution might be to define a different default junction radius which applies to junctions with marked pedestrian crossings. However as the [satellite image ](https://www.google.com/maps/place/52%C2%B019'37.4%22N+13%C2%B037'44.2%22E/@52.3247792,13.6230989,47m/data=!3m1!1e3!4m5!3m4!1s0x0:0x0!8m2!3d52.327067!4d13.628934) for that junction shows, the northern crossing is position exactly right whereas the other 3 all have different offsets from their real world location so a single radius value still couldn't fix this.

**Comment by PaulineHartwig** [comment]
At 2289279265 it would be more logical that pedestrians can cross on both sides and not always have to walk to the one crossing.

**Comment by namdre** [comment]
At 2289279265 there is only walkingarea on each side of the road (the norther arm is shared space and is therefore attached with a single walkingarea). The current architecture allows for at most one crossing between any given pair of walkingareas. It would probably look better if the width of the crossing was wider in this case (#3079)

![Screenshot from 2021-07-02 09-33-53](https://user-images.githubusercontent.com/6240630/124238255-a2aee100-db18-11eb-95cc-9b162dfae1f6.png)

**Comment by namdre** [comment]
The remaining points are to be solved via #3709
