### ISSUE TITLE
time dependent OD matrix

### ISSUE THREAD

**Issue by hassanidoudi** [eclipse/sumo#8783]
Could we create time dependent OD matrix in sumo ?

**Comment by namdre** [comment]
Yes. 
- you can split a matrix with a time line
- you can define a matrix for each time slice
- with some formats you can define multiple matrices (for each time) in the same file

https://sumo.dlr.de/docs/Demand/Importing_O/D_Matrices.html#splitting_large_matrices
https://sumo.dlr.de/docs/Demand/Importing_O/D_Matrices.html#the_amitran_format
