### ISSUE TITLE
Restart and have endless simulation

### ISSUE THREAD

**Issue by subhagakannan** [eclipse/sumo#8784]
Dear all, 
I want to restart the SUMO simulation once it is over, and have endless simulation without using a while loop. In I have to give an external command from another script (via TCP) to stop the simulation. Is there any way to have endless simulation until I say stop?

Thanks in advance!

**Comment by namdre** [comment]
if you start sumo-gui with options **--start --demo** it will loop endlessly.

**Comment by subhagakannan** [comment]
Hello Namdre,
Thank you for the reply. 
This is what I found in the SUMO documentation as per your solution.
-D or --demo - Restart the simulation after ending (demo mode); default: false
I want my simulation to run over and over again through the same route without stopping. '--demo' restarts the simulation after ending. I dont want my simulation to be ended, but to continue driving in the same route like a circle. Is there a way to implement it. I am sorry for bothering. But any input means a lot to me.
Thanks! :)

**Comment by namdre** [comment]
see https://sumo.dlr.de/docs/FAQ.html#how_do_i_maintain_a_constant_number_of_vehicles_in_the_net

**Comment by subhagakannan** [comment]
Hello,

How to use the attribute repeat for repeating the route? every time I try, I get this error:
Error: Disconnected route 'route_0' when repeating.
Error: Vehicle 'vehicle_0' has no valid route. No connection between edge 'e12' and edge 'e12'.

How to solve this? I really don't understand this error. 
Pls help me. Thanks

**Comment by behrisch** [comment]
There is no need to have the edge "e12" twice in the list.
