### ISSUE TITLE
About the input distribution of demands

### ISSUE THREAD

**Issue by thinker310** [eclipse/sumo#8785]
Hello, is there any way to control the distribution of vehicle input please? It does not refer to the distribution of Vtype or routes, I want to set the vehicle arrival distribution, for example, setting the vehicle arrival  in a way of poisson distribution or uniform distribution. Is there any solution to achieve it? Thank you in advance!

**Comment by namdre** [comment]
With `<flow probability="..." .../>` you can get arrivals with a Bernoulli Distribution which can be used to approximate the Poisson distribution (https://en.wikipedia.org/wiki/Binomial_distribution#Poisson_approximation). The other variants of `<flow>` define equally spaced vehicles.

For everything else you have to generate your own xml input of individual vehicles or trips with pre-computed departure times that follow the desired distribution.
