### ISSUE TITLE
sumo-gui crashes on broken network

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#8786]
The network has been edited using some intermediate netedit between 1.9.0 and 1.9.1 Unfortunately the creation cannot be reproduced but nevertheless sumo-gui should not crash but give an error message.

**Comment by behrisch** [comment]
[newnet.zip](https://github.com/eclipse/sumo/files/6701516/newnet.zip)

**Comment by namdre** [comment]
The network was edited manually and contains the line
```
<!--connection from=":cluster_31900255_cluster_1830484487_4709826749_w1" to=":cluster_31900255_cluster_1830484487_4709826749_c0" fromLane="0" toLane="0" tl="gneJ0" linkIndex="20" dir="s" state="M"/-->
```

This is the missing connection which causes sumo-gui to crash

**Comment by namdre** [comment]
Trying to fix every kind of broken .net.xml input could add up to quite a bit of overhead. I'm thinking about 'wontfix'.
