### ISSUE TITLE
pedestrians jump on walkingareas

### ISSUE THREAD

**Issue by Domsall** [eclipse/sumo#8790]
I created a subsecond marketplace scenario with many junctions and sidewalks for pedestrians. During simulation I recognized that pedestrians get "pushed back" when they switch from one WalkingArea-Lane to the next.
It seems for me that these lanes do not have a kind of continuous expression (see below), but rather "hard" discrete changes.

<img src="https://user-images.githubusercontent.com/53042793/123238781-0f095f00-d4df-11eb-9106-7c17af9b39c7.png" width="400" height="400">

I attached an example and pictures of the problem (happens at 9.7s/9.75s): [ped_push_back.zip](https://github.com/eclipse/sumo/files/6708321/ped_push_back.zip)

<img src="https://user-images.githubusercontent.com/53042793/123239569-c900cb00-d4df-11eb-8e51-b52b98a9ba63.png" width="400" height="400">

<img src="https://user-images.githubusercontent.com/53042793/123239645-dddd5e80-d4df-11eb-876b-339cfb7aa5a4.png" width="400" height="400">

What I think is happening:

<img src="https://user-images.githubusercontent.com/53042793/123246811-7d9deb00-d4e6-11eb-91a2-702bf3bc881e.png" width="400" height="400">

**Comment by namdre** [comment]
Yes. I think your last image describes the situation perfectly. The same issue shows up within a single lane where it is curved. Fixing this is beyond the scope of the striping model. Even with a complete new pedestrian model you would have to recompute the geometry internally to account for the coarseness of the current network model.

**Comment by namdre** [comment]
(re-open if you have suggestions)

**Comment by Domsall** [comment]
I never recognized that this is network-specific and also applies to all other vehicles, probably because vehicles and even bicycles are a lot faster and "jump over" such corners.

WalkingAreas are created automatically, so I would probably try to smooth the shape (beginning and ending), just like I would do with roads/lanes.

Would this add issues to the striping model?

**Comment by namdre** [comment]
As discussed yesterday, the smoothing would have to happen inside the striping model which computes the path over a given walkingarea.

**Comment by behrisch** [comment]
see #8797 ?

**Comment by Domsall** [comment]
jup, that is the "follow up" issue  with the concrete problem/request
