### ISSUE TITLE
Netconvert imports stop_position as an additional stop

### ISSUE THREAD

**Issue by ArmelliniMG** [eclipse/sumo#8791]
Netconvert imports the element "stop_position" as an extra stop, beside the elements "platform". This produces duplicate stops in one direction.
I think the problem is similar to #8060 but in this case, the element is "stop_position" instead of "stop_area".
The problem could also be an error in the use of the element "stop_position" in OSM, I am not sure about that.

Test scenario:
see stops: 8341032348, 3257573879, and -3257573880.
[duplicate_stops.zip](https://github.com/eclipse/sumo/files/6708540/duplicate_stops.zip)

**Comment by namdre** [comment]
The duplicate stops -1711953915 and -1711953916 are due to invalid direction assignment (the route is short and the only other stop is on a one-way edge).

**Comment by namdre** [comment]
The duplicate stops 8341032348 and 3257573879 are not assigned to a common stop area
