### ISSUE TITLE
Rolling horizon

### ISSUE THREAD

**Issue by hassanidoudi** [eclipse/sumo#8792]
Can we use rolling horizon approach  with SUMO?  (the vehicle  in the optimization horizon are using duaiterate.py)

**Comment by behrisch** [comment]
Do you mean rolling horizons for travel time estimation?

**Comment by hassanidoudi** [comment]
yes I mean could we do rolling horizons for travel time estimation.

**Comment by namdre** [comment]
@behrisch can we close this?
