### ISSUE TITLE
Calculate Slope with vehicles length

### ISSUE THREAD

**Issue by Domsall** [eclipse/sumo#8802]
The angle calculation uses the vehicles front and back position on the lane to output a realistic "intermediate" value.

`getSlope()` only uses the current front position (found in MEVehicle/MSVehicle/MSTransportable).
On a "bumpy" road this can lead to unrealistic results. Possible origin of such roads:

- OpenDrive map converted with high detail (could also have a speed bump)
- OSM-networks where sparse height data was added from SRTM

For the energy/emission/battery-calculation and models with resistance parameters (KraussPS), this could lead to weird results.
Example:
[Slope_calculation.zip](https://github.com/eclipse/sumo/files/6734879/Slope_calculation.zip)

**Comment by namdre** [comment]
Thanks!
