### ISSUE TITLE
slowDownForBlocked uses timestep dependant value

### ISSUE THREAD

**Issue by Domsall** [eclipse/sumo#8804]
Both LC2013 and SL2015 have the function `slowDownForBlocked`, which ensures that following vehicles will decelerate for a blocked vehicle. I tested a lot and found out that this function is only crucial for vehicles, which are blocked at the end of a lane.

The responsible code snippet in the LC2013 model (identical with SL2015): 

https://github.com/eclipse/sumo/blob/39d4ad02cb4cd7fe5ec4ab32eece8c68897bd2ee/src/microsim/lcmodels/MSLCM_LC2013.cpp#L1848

It was a bit hard to create a scenario which explicitly shows this feature, but I think I found it:

[motorway_slowdownblocking.zip](https://github.com/eclipse/sumo/files/6742618/motorway_slowdownblocking.zip)

When `ACCEL2SPEED(myVehicle.getCarFollowModel().getMaxDecel())` is replaced with `HELP_OVERTAKE`, the blocked vehicle is let in in this scenario.

**Comment by Domsall** [comment]
Did you have time to take a look into this issue yet?!

**Comment by namdre** [comment]
Ask me again after the conference (-:

**Comment by Domsall** [comment]
oh of course, thats coming up next week! Sorry :)
Looking forward to it

**Comment by Domsall** [comment]
I am back :)
I would like to fix this issue before adding the fix with the second following neighbor (which was also mentioned at the conference).

But this issue could also become irrelevant when the second following neighbor brakes for the ego vehicle.
