### ISSUE TITLE
 osmWebWizard.py question

### ISSUE THREAD

**Issue by odajani** [eclipse/sumo#8809]
Hello 
I am using osmWebWizard.py  to generated all XML flies to run SUMO-GUI  
Is there a way to save map.osm file while osmWebWizard.py is generating all necessary XML files. 

osmWebWizard.py is great tool thank you for creating it

**Comment by namdre** [comment]
the downloaded raw osm data is saved as osm_bbox.osm.xml along with the generated xml files.

**Comment by odajani** [comment]
thank you
