### ISSUE TITLE
Could not connect to TraCI server at localhost:53361 [WinError 10061] No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by SAG-DAG** [eclipse/sumo#8810]
I am getting the error after restarting my PC which runs on Windows 10. Before the restart, everything was working fine. Please help.

Retrying in 1 seconds
Could not connect to TraCI server at localhost:53361 [WinError 10061] No connection could be made because the target machine actively refused it

**Comment by philippwulff** [comment]
I have seen this error being caused in windows when starting the client before starting the server. Maybe this is the cause of your issue.

**Comment by behrisch** [comment]
It could also be a firewall / virus scanner issue. Please retry on a different machine if possible and reopen if problems persist

**Comment by SAG-DAG** [comment]
I changed the path of my file and it worked. Really don't know the actual cause behind the error. But it's not due to firewall/ virus scanner for sure. I checked it.
