### ISSUE TITLE
Ramp Guessing Options in netconvert

### ISSUE THREAD

**Issue by zhangqi1008** [eclipse/sumo#8812]
Hi，
Generally, This option was found to be able to change the id of the edge in use when type "--ramps.guess"  in NetCovnert, for instance,  
edge id="95-AddedOnRampEdge" from="80" to="95-AddedOnRampNode"  
However, we found that there are also cases where this option is used but the ID of the edge will not change. What causes this situation？
 and，Is there a sequence for the options of netconvert？ such as, "netconvert *****  --ramps.guess --numerical-ids.edge-start 1" and " netconvert ***** --numerical-ids.edge-start 1 --ramps.guess"  
 Does the above two have any difference to the generated net.xml？
 THX for your reply

**Comment by behrisch** [comment]
If netconvert will generate a ramp anyway (so even without ramps.guess) it will get a numerical id. The altered ids only apply to ramps which would not be present without the option. The order of the option does not change the result. If you want to enforce numerical ids everywhere, you can do it in a two step process: e.g. `netconvert --ramps.guess --osm osm.xml -o tmp.net.xml` and then `netconvert --numerical-ids.edge-start 1 -s tmp.net.xml -o final.net.xml`
