### ISSUE TITLE
method behind xml conversion of files 

### ISSUE THREAD

**Issue by Fatimaghaffar** [eclipse/sumo#8813]
when we used routes and trips files with .net.xml file, on the bases of what method they get combined to form a complete network? I am not talking about steps or command, I am talking about methodology behind that.

**Comment by palvarezlopez** [comment]
Hi @Fatimaghaffar . We use Xerces-C (http://xerces.apache.org/xerces-c/)

**Comment by behrisch** [comment]
If you have further questions it may also be easier to ask on the mailing list see https://www.eclipse.org/sumo/contact/

**Comment by namdre** [comment]
The complete network is already encoded in the .net.xml file. Your question seems to imply a misunderstanding somewhere.
