### ISSUE TITLE
Alternative routes duaIterate

### ISSUE THREAD

**Issue by hassanidoudi** [eclipse/sumo#8814]
How to increase the number of alternative routes to select all possible routes in duaIterate?

**Comment by behrisch** [comment]
duaIterate will only add new routes if they are faster than the currently fastest route so there is no way to add additional slower routes while the script is running. You can try to put more route in your initial input file though by using the marouter with the k shortest paths option.

**Comment by namdre** [comment]
Actually, you can add "slower" route by setting option **duarouter--weights.random-factor X** with X > 1 since some slower routes will appear to be "faster" due to randomness
