### ISSUE TITLE
Why doesn't the vehicles move?

### ISSUE THREAD

**Issue by thinker310** [eclipse/sumo#8816]
Hi, I encounter a weird phenomenon that the cars can not go through the intersection when the traffic light keep green, just as the picture below. I want the traffic light keep constant green so traffic lights in the other direction were set as red. And another question is that the two lanes are straight lane but only cars in the right-most lane can go through the intersection, cars in the middle lane cannot. How to sovle it? Thank you in advance!
![image](https://user-images.githubusercontent.com/62609436/124710816-e302ca80-df2f-11eb-814a-46143bf487ba.png)
 
![image](https://user-images.githubusercontent.com/62609436/124712025-5f49dd80-df31-11eb-80e5-5565df0d6dd8.png)
Could you help me please? Thank you in advance!

**Comment by philippwulff** [comment]
I think attaching the simulation scenario (the network, routes and config files) would help a lot with debugging your issue.

**Comment by palvarezlopez** [comment]
Hi @philippwulff. Please attach your scenario (network and route files)

**Comment by philippwulff** [comment]
Hi @palvarezlopez, I believe you meant to tag @thinker310

**Comment by palvarezlopez** [comment]
@philippwulff ups! yes, sorry for the invalid reference

**Comment by thinker310** [comment]
Okk, the file is in the attachment.  The cars cannot go through the intersection when the traffic lights is green.
[Desktop.zip](https://github.com/eclipse/sumo/files/6827657/Desktop.zip)
Thank you !

**Comment by behrisch** [comment]
@thinker310 This is the wrong network. It does not have traffic lights.

**Comment by thinker310** [comment]
Thank you! But after I debuged the traffic lights, this problem are still not solved. And I found that when I set the lane attribute ' changeleft' and 'change right' as 'emergency', this problem can happend, I just do not want the vehicle to change lane, I found set the Changeleft and Changeright as emergency, the lane line can get solid, thus the cars can not change lane any more. But this setting cause the cars can not go through the intersection when traffic lights are green. Is this a bug in SUMO?

**Comment by behrisch** [comment]
If the cars are on the wrong lane they cannot reach their destination and will not drive. You will either need to modify the connections or allow lane changing.

**Comment by namdre** [comment]
Or you can set a better depart lane for each of your flows manually. The attribute 'departLane="best"` takes no effect if the critical turning lane is too far away from the point of departure.

**Comment by behrisch** [comment]
closing for lack of feedback, please reopen and attach the scenario if problems persists
