### ISSUE TITLE
SUMO-controlled vehicles ignore the right of way of other vehicle within an intersection and collide.

### ISSUE THREAD

**Issue by philippwulff** [eclipse/sumo#8817]
I have a simulation with mostly default SUMO parameters, however vehicles controlled by SUMO ignore the right of way of other vehicles and collide with them. To me this looks like something is wrong with the speed mode, but I observe the issue in regular SUMO simulations as well as when using TraCI. I also checked the speed mode for all vehicles when using TraCI and it is `31`. I do not set the speed mode in the .rou.xml file. The routes in the scenario are vehicles with default parameters and some vehicles with this custom vtype:

```
<vType carFollowModel="ACC" id="automated_vehicle" decel="2.5" accel="2.5"/>
```

I am wondering, if the parameters I use are causing these issues, however it also happens for default SUMO vehicles (and also when I set the CF-model to Krauss instead of ACC). In this simulation, the files to which I attached below, I observe two types of collisions:

1. The vehicle outright ignores the right of way of the other vehicle. This issue is particularly bad for me. At t=1064s in the scenario (`sumo-gui -c config.sumocfg --collision.check-junctions`), this type of collision occurs between two "automated_vehicles":
![acc_ignores_acc](https://user-images.githubusercontent.com/45896065/124749698-d9c03080-df24-11eb-9a1d-812daac96044.gif)
I also have a traci-command-log file which calls `setPreviousSpeed` and `moveTo` for the automated vehicles and when running the same scenario with `python traceFile.py`, at t=860s a default-vehicle (yellow) ignores the "automated_vehicle" (red):
![krauss_ignores_acc](https://user-images.githubusercontent.com/45896065/124750193-7682ce00-df25-11eb-872b-4c2c9406374e.gif)

2. In the second type of collision, the vehicle stops at a halting position which is far into the junction and causes a collision with the vehicle which has right of way. Both default and "automated_vehicles" cause this issue. I suspect, the fact that two lanes merge onto one opposite lane at this intersection causes it to happen frequently, but I observed it at other intersections too. The video shows the simulation at t=1042s (`sumo-gui -c config.sumocfg --collision.check-junctions`):
![dual_lane_collision](https://user-images.githubusercontent.com/45896065/124748213-1b4fdc00-df23-11eb-8dc4-8823b987264f.gif)

The locations of these junctions in the simulation scenario files are marked here:
![network_locations](https://user-images.githubusercontent.com/45896065/124751193-a383b080-df26-11eb-8c71-d393c2d2d4f6.png)

Simulation scenario files:
[junc_collisions.zip](https://github.com/eclipse/sumo/files/6776720/junc_collisions.zip)

**Comment by philippwulff** [comment]
I think, `--collision.check-junctions` is what is detecting all these collisions.

According to the docs this is what it does:

When setting the option --collisions.check-junctions, collisions between vehicles on the same intersection are also checked by detecting overlap of the vehicles shapes.

This is the same situation from the first GIF, when I do not start SUMO-GUI with  `--collision.check-junctions`:

![acc_vs_acc_no_coll](https://user-images.githubusercontent.com/45896065/124797028-19e9d800-df52-11eb-98f5-2611c9ec0c7d.gif)

**Comment by behrisch** [comment]
To me this still looks like a bug. They should not enter simultaneously.

**Comment by namdre** [comment]
ACC and CACC indeed drive imprecisely. 

The invalid junction collisions is due to bad geometry computation within the junction model. What those vehicles are trying to do is to move forward a little bit while still respecting the space of the foe vehicle.  In this they make faulty assumptions about relative angles in a manner that is similar to (#4397). 

The behavior is meant to enable close following after leader vehicles that are mostly past the conflict point. In the given scenario it is counter-productive since it results in a short burst of acceleration followed by deceleration (when disabling junction collision checks). Hence the behavior should be refined independently of the collision issue.

**Comment by namdre** [comment]
There are still collisions in the provided scenario but they are all due to #4397 (The vehicle waits at the internal junction but the shapes overlap anyway).
