### ISSUE TITLE
Netedit allow showing selected network elements in demand/data mode

### ISSUE THREAD

**Issue by ArmelliniMG** [eclipse/sumo#8819]
It would be helpful to see the selection of network elements (edges, nodes) when working in demand or data mode. I am referring to the selection of an element via the Location/Chooser tool as a way to locate an element. 
It makes it easier, for example, to find a start/end edge of a route that we want to create or we want to check.

**Comment by behrisch** [comment]
You can still color edges by selection in the visualization options if this helps

**Comment by palvarezlopez** [comment]
After a discusion, we determined that the best solution is using "color edges by selection"
