### ISSUE TITLE
method behind activity generation 

### ISSUE THREAD

**Issue by Fatimaghaffar** [eclipse/sumo#8820]
how by using these parameters "inhabitant, households" traffic is generated?
What's the method behind it?
What's the formula or distribution used to generate traffic?

**Comment by behrisch** [comment]
Except for the code there is little documentation on the model, see https://sumo.dlr.de/docs/Demand/Activity-based_Demand_Generation.html#model_documentation. There is also currently an effort underway to reimplement the model in python to make it more accessible you might want to contact @michelealbano.
