### ISSUE TITLE
 How to keep simulation running forever？

### ISSUE THREAD

**Issue by meco2020** [eclipse/sumo#8821]
Hello! I have a question about sumo simulation.

When one simulation starts, it will end when the simulation time equals to the cfg end time or it will end when all the vehicles have leaft the simulation.

My question is how to keep the simulation running forever?

**Comment by palvarezlopez** [comment]
Hi @meco2020. What is the purpose of running forever a simulation? This could be problematic for writting results in XMLs

**Comment by behrisch** [comment]
If you just want to restart the simulation automatically, you can also use the demo mode, see https://sumo.dlr.de/docs/sumo.html#gui_only

**Comment by namdre** [comment]
If no end time is set, the simulation will terminate after the last vehicle. If an end time is set it keeps running. The maximum simulated time is more than 200 million years.
