### ISSUE TITLE
Netedit imgFile gets distorted with POI

### ISSUE THREAD

**Issue by Domsall** [eclipse/sumo#8823]
When I add a imgFile to a POI, it is displayed quadratic.

When I then change the height/width, the image gets distorted. But it looks like it is getting distorted in the wrong direction.
Is it also possible to let the image reach from one side of the POI-dimension to the other? Right now the image is in the middle of the POI, but does not reach from border to border.
I attached an example:

[disorted_imgFile.zip](https://github.com/eclipse/sumo/files/6800510/disorted_imgFile.zip)

Another problem arises when I want to use relative paths in NETEDIT, I then can not open the file anymore (can not find image anymore).

**Comment by palvarezlopez** [comment]
Hi @Domsall 

Distorsion is caused because currently SUMO cannot calculate the equivalent **scaled** height for the given width. You need to calculate the height manually (for example, using a software like paint), and writting in XML.

About the second problem, I'm going to check it, thanks!

**Comment by Domsall** [comment]
I am using height and width values for my objects. Do you mean this with "manually calculating and writing in XML"?

What I am seeing is this:
![image](https://user-images.githubusercontent.com/53042793/125274261-149fdb00-e30e-11eb-9590-90da7775efb8.png)

When I change "width", the picture actually gets wider, but the POI somehow changes its height dimension...

**Comment by palvarezlopez** [comment]
@Domsall uhm, this is another bug. I'm going to fix it

**Comment by palvarezlopez** [comment]
@Domsall use Paint to calculate the equivalent width/height:

![scale](https://user-images.githubusercontent.com/8238561/125277253-7e6db400-e311-11eb-9aa5-6c492bb58494.png)

**Comment by Domsall** [comment]
ah ok, I already have the "real" dimensions of the object. I am setting both the height and width and am not using a reference/scale.

**Comment by palvarezlopez** [comment]
@Domsall I fixed the problem with width/height dotted contour. The other "problem" with relative path is, that relativePath only applies to saving XML, not for loading. You has to load always either with the image in the same folder as additional file, or with the absolute path.

**Comment by Domsall** [comment]
thanks for fixing and the information! The relative path issue doesn't bother me, I just understood it differently.
I'll close the issue then

**Comment by palvarezlopez** [comment]
@Domsall thanks :-)
