### ISSUE TITLE
How to dynamic reload network file when sumo is running simulation?

### ISSUE THREAD

**Issue by allenzhuyi** [eclipse/sumo#8824]
How to dynamic reload network file?  When is sumo is running simulation, I want dynmaic reload network file once the edge  is changed. For example,one big edge is splited into two small edges,So I want dynamic reload the network file. I dont't want to restart sumo instance.

**Comment by palvarezlopez** [comment]
Hi. When you say "reload network file", do you mean reload network, but leaving traffic (vehicles, persons, etc.) in the same position and with the same values?

**Comment by allenzhuyi** [comment]
Yes，I don't want to restart sumo instance . I want to keep current sumo  instance state(vehicles,persons etc) ,but dynamic reload net file to adjust to the new network file,Is there an api to reload the net file ?

**Comment by palvarezlopez** [comment]
@allenzhuyi currently is not possible to load dinamically the network. You can only restart the simulation with the new network.

**Comment by allenzhuyi** [comment]
Is it possible in the new edition? I only need to relaod the network(edge junction connection)

**Comment by palvarezlopez** [comment]
@allenzhuyi no, probably this will not be implemented

**Comment by behrisch** [comment]
You can try to load a saved state with a different network but in general this is a bad idea because it will not adapt vehicle routes or positions to new or split edges.
