### ISSUE TITLE
Sumo-gui: Changing view size by "restore" button  reduces it to line

### ISSUE THREAD

**Issue by m-kro** [eclipse/sumo#8826]
Experienced in sumo-gui 1.9.2: After loading a network with a single view spreading over the entire SUMO window, click the "restore" button left of the [x] for closing the view. The view element will be scaled to 1px height, making it impossible to return to full size. See the dark gray line in the attached screenshot:
![image](https://user-images.githubusercontent.com/33294728/125341766-4b98df80-e354-11eb-93a5-5a98945d28b9.png)

**Comment by palvarezlopez** [comment]
@m-kro Thanks :)
