### ISSUE TITLE
How do I make a left turn bay?

### ISSUE THREAD

**Issue by parksanha** [eclipse/sumo#8827]
Hello.

How do I make a left turn bay?

Any good information would be greatly appreciated.

**Comment by palvarezlopez** [comment]
Hi @parksanha 

1) Go to NETEDIT, open the Network, and go to the Edge, in which you want to set the left turn bay
2) In inspect mode, left click over edge, and select "split edge in this position"
3) Inspect the new edge, and update the number of lanes
4) Use the new lane as left turn bay

**Comment by parksanha** [comment]
Thank you for the reply.

But when I do as you said, I get something like picture 1 below.
![image](https://user-images.githubusercontent.com/62294108/125422147-7b7e9a8e-1f23-497f-8614-0b8a7e267c81.png)

I found a picture like picture 2, is there a way to draw a road like the picture below?
![image](https://user-images.githubusercontent.com/62294108/125422181-98c8d8c4-005c-4010-badb-49cfb2246fa2.png)

**Comment by m-kro** [comment]
You have to edit the inbound edge, not the outbound one...Then it is a matter of geometry to make it look exactly like the second picture you showed.

**Comment by palvarezlopez** [comment]
@m-kro Thanks

**Comment by parksanha** [comment]
Many thanks to everyone who gave advice.

**Comment by namdre** [comment]
Setting 'spreadType=roadCenter' for the involved edges greatly simplifies geometry manipulation.
