### ISSUE TITLE
loaded vehicles count differs in summary file after state loading

### ISSUE THREAD

**Issue by hassanidoudi** [eclipse/sumo#8828]
Hello,

Loaded vehicle in the summary output file is not equal to the number of trips given as an input?
In the simulation,I am loading a state and after that adding trips to this loaded state.

Thank you in advance.

**Comment by behrisch** [comment]
I can confirm this is a bug.

**Comment by behrisch** [comment]
my test case involved randomness in vehicle generation. Please recheck whether you are saving random number states (--save-state.rng) and report back whether the most recent nightly build saved the problem

**Comment by behrisch** [comment]
Seems to be solved, please reopen if problems persist
