### ISSUE TITLE
How to set the leader for vehicles with the car-following model CACC in sumo?

### ISSUE THREAD

**Issue by gaofenxia** [eclipse/sumo#8830]
How to set the leader for vehicles with the car-following model CACC (here they are called CACC-vehicles for short) in sumo?

When there is no qualified leader for  CACC-vehicles, how does sumo deal with it? What is its internal mechanism?
For example, how does the failure of CACC-vehicles become ACC-vehicles?

**Comment by behrisch** [comment]
If there is no leading car the model falls back to the standard Krauss model.
