### ISSUE TITLE
Is there a way to erase only the node in the center while preserving the edges and lanes?

### ISSUE THREAD

**Issue by parksanha** [eclipse/sumo#8831]
Hello~

Is there a way to erase only the node in the center while preserving the edges and lanes?

The picture below shows the node I want to delete.
![image](https://user-images.githubusercontent.com/62294108/125726319-3351b770-bde0-49e4-8100-0bc424cbef3c.png)

**Comment by palvarezlopez** [comment]
Hi @parksanha ,

in inspect mode, leftclick over junction, and select option "replace junction by geometry point"

**Comment by parksanha** [comment]
Thank you very much for your reply.

I'll try.
