### ISSUE TITLE
Which paper is the BKerner car following model based on?

### ISSUE THREAD

**Issue by fywu85** [eclipse/sumo#8832]
I was playing around with the BKerner model recently and found that the model produced some really nice behaviors. Could anyone provide a link to the paper on which the BKerner mode is based on? Curious to read more about the math behind it.

**Comment by behrisch** [comment]
Sorry, I cannot find the reference. Maybe @dkrajzew can help or the information here #7683

**Comment by dkrajzew** [comment]
Dear all,

As far as I remember, it was this paper:
https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=4621143 (
https://arxiv.org/abs/0712.2711)

Sincerely,
Daniel


Am Mo., 19. Juli 2021 um 14:36 Uhr schrieb Michael Behrisch <
***@***.***>:

**Comment by palvarezlopez** [comment]
@dkrajzew Thanks!
