### ISSUE TITLE
ste vehicle stop in sumocfg

### ISSUE THREAD

**Issue by zhaotuo0815** [eclipse/sumo#8833]
hello,sumo developer,I want to set the vehicle stop in the specific position of a lane in the sumocfg, like the picture as fellow,but the vehicle alway stop in end of the lane that I  give before,so my question is that how can i set the vehicle to stop in a position that I give in the sumocfg!thank a lot.
![question](https://user-images.githubusercontent.com/59630993/125786260-39b240a5-58c6-4c3a-bb0f-accd06ced491.png)

**Comment by palvarezlopez** [comment]
Hi @zhaotuo0815 . You need to specify both attribute **startPos** and **endPos**. EndPos mark the exact position in which vehicle stops.

For your case: **startPos="10" endPos="20"**

**Comment by namdre** [comment]
It is sufficient to give 'endPos'
