### ISSUE TITLE
tools/createVehTypeDistribution.py to sumolib

### ISSUE THREAD

**Issue by mschrader15** [eclipse/sumo#8835]
Hey All,

Any interest in porting over [createVehTypeDistribution](https://github.com/eclipse/sumo/blob/master/tools/createVehTypeDistribution.py) to sumolib? My use case is running many simulations with varying bounds on car-following parameter distributions in a Monte-Carlo analysis. The workflow currently has to include a `subprocess.run()` call, as well as writing a temporary text file.  It'd be nice if I could use sumolib instead.

I'd be happy to adapt createVehTypeDistribution to fit the sumolib convention and create a pull request, but I wanted to first check and see if it was something that the SUMO team sees as beneficial.

**Comment by behrisch** [comment]
Yes that would be great!

**Comment by mschrader15** [comment]
Quick question: which versions of Python does sumolib aim to support? 

Wondering if I can use https://docs.python.org/3/library/dataclasses.html or not?

**Comment by behrisch** [comment]
> Quick question: which versions of Python does sumolib aim to support?

In general we still try to support 2.7 if possible but the main platform is 3.7 and above.

> Wondering if I can use https://docs.python.org/3/library/dataclasses.html or not?

If it is not too much hassle please don't

**Comment by mschrader15** [comment]
Ok, makes sense. I avoided using it in https://github.com/eclipse/sumo/pull/8844
