### ISSUE TITLE
Add side sub road in junction.

### ISSUE THREAD

**Issue by Laudarisd** [eclipse/sumo#8840]
Hello Everyone, 
I am new in sumo and netedit. I tried to import osm from openstreet. Now I am ediditing osm in netedit but the problem is I can't add side road in junction.
I mean a road on junction, which gives acces to go to left to left (like left turn) and right to right(like right turn) without waiting in traffic lights.

Similalry I have one more proble. How can I delete / break nodes which are provided by openstree in neteditor?

Thank you.

**Comment by palvarezlopez** [comment]
Hi @Laudarisd 

1) Inspect road (edge), change number of lanes, and use the new lane for turning. You cand adjust connections using connection mode (shortcut C)

2) Delete nodes: Just go to delete mode (shortcut D) and click over junction to remove.

**Comment by namdre** [comment]
to bypass a traffic light you need to split the incoming and outgoing road. (right-click menu "split edge here"), then add a new route the connects the newly created junctions.
