### ISSUE TITLE
NETGENERATE: edges not deleted, labelled with a "-"

### ISSUE THREAD

**Issue by rlloretb** [eclipse/sumo#8841]
When using the option --remove-edges.explicit in NETGENERATE, the edges are not actually deleted, but just added a minus in front of the name. 

Is that a bug or a feature?

**Comment by behrisch** [comment]
It is probably a bug, can you please give the exact call you tried.

**Comment by behrisch** [comment]
Never mind it already shows up with `netgenerate --grid -o g.net.xml --remove-edges.explicit A1B1`
