### ISSUE TITLE
Prevent detectors from generating output files

### ISSUE THREAD

**Issue by rlloretb** [eclipse/sumo#8846]
Is it possible to prevent E1 detectors from recording output files?

**Comment by m-kro** [comment]
See [docs](https://sumo.dlr.de/docs/Simulation/Output/Instantaneous_Induction_Loops_Detectors.html). I think the NUL value applies to other detectors, too.

**Comment by rlloretb** [comment]
I confirmed it worked for E1 detectors.

**Comment by m-kro** [comment]
@angelobanse Maybe unify the detector documentation about output file paths?
