### ISSUE TITLE
sumo crash when requesting transition of control via TraCI

### ISSUE THREAD

**Issue by vmintsis** [eclipse/sumo#8847]
When vehicles use ACC/CACC cfmodel and a ToC request is issued 
`traci.vehicle.setParameter(self.ID, "device.toc.requestToC", "int available lead time"]` 
then  the vehicle changes type (becomes a legacy vehicle using the Krauss cfmodel). 

In this case (file MSVehicle.cpp - see below) the myCFVariables becomes null 
```
MSVehicle::replaceVehicleType(MSVehicleType* type) {
    MSBaseVehicle::replaceVehicleType(type);
    
    delete myCFVariables;
    myCFVariables = type->getCarFollowModel().createVehicleVariables();  
}
```
and this results in a simulation crash in line 351 of file MSCFModel_CACC.cpp (please see relevant function below)
function: 
```
MSCFModel_CACC::_v(const MSVehicle* const veh, const MSVehicle* const pred, const double gap2pred, const double speed, const double predSpeed, const double desSpeed, const bool /* respectMinGap */)

CACCVehicleVariables* vars = (CACCVehicleVariables*)veh->getCarFollowVariables();
```
***vars pointer is null when line 350 is reached.
We used the following SUMO version for running our sim experiments: v1_9_2+0000-4206cfae24

@namdre @schwamborn

**Comment by schwamborn** [comment]
Can you please provide your scenario, preferably with a [TraCI trace file](https://sumo.dlr.de/docs/TraCI/Interfacing_TraCI_from_Python.html#generating_a_log_of_all_traci_commands)?

**Comment by schwamborn** [comment]
The lane change model currently caches `myCarFollowModel`, which is why `MSCFModel_CACC::_v()` is called here despite having changed to Krauss.
