### ISSUE TITLE
Reporting Wrong HEX in web documentation

### ISSUE THREAD

**Issue by Tambup** [eclipse/sumo#8848]
Hi, 
me and another researcher would like to report that at [this link](https://sumo.dlr.de/docs/TraCI/Vehicle_Value_Retrieval.html#extended_retrieval_messages) of documentation there is a small error:
in the section about "neighboring vehicles" the variable value now is 0x13, but it is wrong (and also wrong are the link about request and response). The HEX should be 0xBF, as can be seen in the content box of the same web page (that saved us some hours).

Cheers.

**Comment by schwamborn** [comment]
Thank you for reporting! Should be fixed now.
