### ISSUE TITLE
Spliting edge

### ISSUE THREAD

**Issue by parksanha** [eclipse/sumo#8849]
Whenever I try to divide a road, there is always a junction.

However, in the picture below that I found on Google, you can see that dividing or merging roads will not create junctions.

How can I divide the road like the picture below?

![image](https://user-images.githubusercontent.com/62294108/126440948-4961bee2-c181-4f5f-9058-cb5999353572.png)

**Comment by palvarezlopez** [comment]
Hi @parksanha 

there is a junction in the road division, but shape is small. See this picture:

![fix](https://user-images.githubusercontent.com/8238561/126441699-4b2a6f3d-4230-4da0-846c-a0d0169737fc.png)
