### ISSUE TITLE
Dynamic User Equilibrium

### ISSUE THREAD

**Issue by zhaotuo0815** [eclipse/sumo#8850]
hello，sumo developer，I want to do Dynamic User Equilibrium with sumo, and I refer to duaIterate.py for Dynamic User Equilibrium based on https://sumo.dlr.de/docs/Demand/Dynamic_User_Assignment.html. So i would like to know if this duaIterate.py script has a reference article to help me better understand the  Dynamic User Equilibrium.

**Comment by behrisch** [comment]
The reference for the implementation used in SUMO's duarouter / duaIterate is this one: https://sumo.dlr.de/pdf/GawronDiss.pdf

**Comment by zhaotuo0815** [comment]
thank you so much.



发自我的iPhone


------------------ Original ------------------
From: Michael Behrisch ***@***.***&gt;
Date: Wed,Jul 21,2021 11:00 PM
To: eclipse/sumo ***@***.***&gt;
Cc: zhao tuo ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [eclipse/sumo] Dynamic User Equilibrium (#8850)





 
The reference for the implementation used in SUMO's duarouter / duaIterate is this one: https://sumo.dlr.de/pdf/GawronDiss.pdf
