### ISSUE TITLE
vehicles on long stops should pause rerouting

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#8851]
It does not make sense and wastes a lot of computing time. We should either skip all reroutings until the end of the stop duration is near enough or (maybe more realistic) let departure from a stop trigger rerouting. The latter would also help if the stop is aborted via traci.

**Comment by namdre** [comment]
The rerouting device could store are flag to indicate whether rerouting was skipped while stopped and this could be checked in resumeFromStopping (MSVehicle/MEVehicle).

**Comment by behrisch** [comment]
This came from ArtForum but it does not seem to block their progress

**Comment by namdre** [comment]
when running with 10k vehicles it beomes quite noticable.
