### ISSUE TITLE
Is it possible to add background in 3D?

### ISSUE THREAD

**Issue by Laudarisd** [eclipse/sumo#8853]
Hi @palvarezlopez I tried to follow your instruction to visualize my 2D simulation in 3D. I was able to visualize street but couldn't get any other background information. So is there anything that I am missing?

Actually I want to do following in 3D simulation.

Transform image background in to 3D (just 3D shape is okay).
And when we change vehicle shape into box it doesn't show real shape. Is it possible to fix it?

Here is an image from my simulation(2D and 3D visualization)
![image](https://user-images.githubusercontent.com/53330430/126600162-81bbcaf5-b531-439a-a0fe-272dd8bffce2.png)

**Comment by palvarezlopez** [comment]
Hi @Laudarisd. I cannot see the image. Can you upload it directly in the issue?

**Comment by Laudarisd** [comment]
Hi @palvarezlopez I uploaded the image in above issue.

**Comment by palvarezlopez** [comment]
@Laudarisd currently the 3D simulation is very limited :( What you see is the only that sumo can do in 3D

**Comment by behrisch** [comment]
You can in fact load additional 3D models as background. For an example use sumo/tools/game/bs3Dosm.sumocfg. I am not sure how the background 3ds file has been generated but I think it was a tool like osm2world

**Comment by Laudarisd** [comment]
@behrisch Thank you for your reply. Let me try it.
