### ISSUE TITLE
netconvert with OpenDrive

### ISSUE THREAD

**Issue by Domsall** [eclipse/sumo#8854]
I often use netconvert to convert OpenDrive-maps to SUMO.
After converting I normally have to do a lot of work to make the SUMO-net match the OpenDrive-file.

I now thought I'll post the problems all together in this issue for feature requests / future fixes:

1. ~~The command `--geometry.avoid-overlap` outputs an error when I use it with the value `false`~~
2. ~~The command `--opposites.guess` outputs an error when I use it with the value `true`~~
3. When lanes end or begin (lane number changes), netconvert has problems creating junctions. The attribute `--junctions.scurve-stretch` did not really help. I attached pictures of the problem below (parking spaces start/end, left turning lanes begin/end)
4. ~~Are internal lanes on junctions created from the OpenDrive-File?! I am not sure, if they actually match.~~
5. ~~Is it possible to create "stop-lines" just like in the OpenDrive-File, so that the vehicles stop at the correct position?~~
6. parking spaces do not seem to be created correctly, neither in the parking-output, nor in the net-file.

netconvert is pretty big and has a lot of parameters to "play" with, so maybe a few problems can be solved with correct parameters and/or values.
I would be very thankful, if you could help me with this :)

The Files (OpenDrive, SUMO-net, .typ.xml-file, etc.):
[netconvert_junction.zip](https://github.com/eclipse/sumo/files/6862072/netconvert_junction.zip)

full command list:
--opendrive-files AschaffenburgsIMPLE.xodr
-o AschaffenburgsIMPLE2.net.xml
--street-sign-output streetsigns.add.xml
--parking-output aschaffenburg_parking.xml
--type-files opendrive_netconvert.typ.xml

--plain.extend-edge-shape true
--opposites.guess true

--geometry.min-radius.fix false
--geometry.min-radius.fix.railways false
--offset.disable-normalization true
--lefthand false
--no-internal-links false
--no-turnarounds false
--junctions.corner-detail 10
--junctions.internal-link-detail 10
--junctions.limit-turn-speed 5.5
--junctions.scurve-stretch 7.5
--rectangular-lane-cut true
--walkingareas false
--opendrive.import-all-lanes true
--opendrive.curve-resolution 1
--opendrive.internal-shapes true

Picture of the SUMO-Map:
![image](https://user-images.githubusercontent.com/53042793/126635206-8f69e042-5a70-4443-b3f3-c113ab8fff81.png)

Picture of the real junction as reference (it is not perfectly the same)
![image](https://user-images.githubusercontent.com/53042793/126635637-08f6f023-fce0-4cbf-a34e-1994125b7d37.png)

Picture of the OpenDrive in RoadRunner:
![image](https://user-images.githubusercontent.com/53042793/126635712-85853643-5ea4-4ff9-b9c8-be909355a08c.png)

**Comment by behrisch** [comment]
I think the option parsing errors are due to an empty edge list after **--geometry.remove.keep-edges.explicit**

**Comment by Domsall** [comment]
Thanks, yes you are right, I changed the issue

**Comment by namdre** [comment]
3)  
  -  scurve-stretch is a nonlinear function that works better with input in the range of [0,2] rather than the 7.5 you tried. See https://github.com/eclipse/sumo/blob/68099f5dff0440166ebe725681c746e1d9ec7184/src/netbuild/NBNodeShapeComputer.cpp#L392
  - the wierd shape on the eastern side is a netconvert bug where the geometry changes when recomputing the network a second time (or viewing it in netedit). The output network looks comparatively fine in sumo-gui directly after import.

4) when option **--opendrive.internal-shapes** is set, the internal shapes are imported rather than computed.
5) I'm not aware of a stop-line feature in OpenDrive up to version 1.5. Is that a newer feature or are you referring to general object markings?
6) option **--parking-output** only works for OSM import at the moment. If parking spaces are defined as objects in OpenDrive they can be imported with **--polygon-output**.  However, lanes with type 'parking' are imported as expected from the given input.



The invalid shape on the eastern end looks like a junction-shape-computation bug.

**Comment by Domsall** [comment]
Thanks for the response!

3. I used the parameters 1.0, 1.5 and 2.0 for scurve-stretch. The value 1.5 showed the best result for the western side. The southern and eastern side did not change. It would be great, if you could find the reason for the weird eastern side creation and check if there is some kind of possibility to create longer, smooth junctions when the lane number changes (right now those changes get seperated into 2 junctions). junctions.join unfortunately does not help.

5. You are right, stop lines are a bit tricky. Object markings could be used, but they have no "logical connections" and there is no clear type for stop lines. This should change in the future, where they want to introduce "stopLine" RoadMarks. Right now I only know of "signalReference"-tags, which link a virtual stopline with a signal (e.g. traffic light). But in the above OpenDrive these tags are actually missing.

6. The lanes are imported correctly, for the future it would be great to also get some kind of logical parking spaces with --parking-output.

So from my understanding:
- For 5.: I will just modify the junctions to get correct stopping offsets, because these attributes are missing from OpenDrive
- For 3.: It would be great if the junction-shape-computation could be fixed and maybe modified a bit
- For 6.: I would love to see this feature for OpenDrive in a future SUMO-version.

**Comment by namdre** [comment]
6. is now tracked as #9053 so it doesn't get lost
