### ISSUE TITLE
How to save and load simulation state into variable, NOT file ?

### ISSUE THREAD

**Issue by Mortaza-Seydi** [eclipse/sumo#8855]
Hi, 
I need to save and load sumo simulation state many times. 
In python code, i use ``` traci.simulation.saveState ``` and ``` traci.simulation.loadState ```, but this functions work with files.
for performance issues, i want to save and load state into variable to change simulation state faster.
what can i do ?
Thanks.

**Comment by namdre** [comment]
saving and loading states is only supported via files. You could mount a ram-disk to speed this up maybe. 
https://en.wikipedia.org/wiki/RAM_drive

**Comment by behrisch** [comment]
But you should definitely check first whether disk io is really the bottleneck here for instance by redirecting the state output to /dev/null and measuring runtime
