### ISSUE TITLE
co-simulation with unreal engine.

### ISSUE THREAD

**Issue by parksanha** [eclipse/sumo#8856]
Hello!

Is there any information to link sumo and unreal engine?

**Comment by palvarezlopez** [comment]
Hi @parksanha,

I studied a few months ago a possible implementation of Unreal engine in SUMO, but probably we will not do it.

**Comment by behrisch** [comment]
But please have a look here: https://sumo.dlr.de/docs/Other/Projects.html#visualization_related

**Comment by parksanha** [comment]
@palvarezlopez 

thank you. I'll check it out.

**Comment by namdre** [comment]
@palvarezlopez The question was about co-simulation, not integration.
 
Other people have done co-simulation of sumo and unreal as evidenced by https://www.youtube.com/watch?v=TG8k785ELSQ
(Google spits this out on the first page when searching for sumo and unreal)
