### ISSUE TITLE
How to use extractTest.py?

### ISSUE THREAD

**Issue by thinker310** [eclipse/sumo#8858]
Hello, after seeing a problem about during control, I want to have a try. But there is a trouble to be solved. As shown in the picture, I paste the directory behind extractTest.py but there exist some errors. Could you guide me?  Thanks in advance!
![image](https://user-images.githubusercontent.com/62609436/127113424-7fe92897-b094-49df-9071-25ff063bea12.png)

**Comment by behrisch** [comment]
Can you please post the full stack trace?

**Comment by behrisch** [comment]
And please use quotation marks if there is whitespace in the path.

**Comment by behrisch** [comment]
I just noticed that you did not specify a test directory but rather something which looks like an already extracted directory. So you should do something like

`python extractTest.py ..\tests\sumo\basic\tls\actuated\dualring\`

Please reopen if problems persist
