### ISSUE TITLE
partially invisible context menu 

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#8860]
when right-clicking near the bottom of the screen

**Comment by palvarezlopez** [comment]
@namdre can you take an Screenshot?

**Comment by schwamborn** [comment]
Here is an example:
![Picture1](https://user-images.githubusercontent.com/35012744/127306826-3167ba54-79f8-4342-8060-25ffdb0c3e2c.png)

**Comment by palvarezlopez** [comment]
I'm not sure if we can solve this issue, because I think it's a FOX problem

**Comment by namdre** [comment]
@behrisch reports issues on multi-screen setup
