### ISSUE TITLE
libsumo/TrafficLight.h references microsim header

### ISSUE THREAD

**Issue by riebl** [eclipse/sumo#8862]
The *libsumo/TrafficLight.h* header includes *microsim/traffic_lights/MSTLLogicControl.h*. Since no *microsim* headers are getting installed, I cannot properly include *libsumo/TrafficLight.h* in a third-party project and thus cannot use *libsumo* at all. This issue occurs only with "installed" SUMO setups, obviously.

How to proceed with this issue? Shall I try to refactor the headers and extract the `MSTLLogicControl::TLSLogicVariant` into a *libsumo* header (TrafficLightLogic.h?), which is used by *TrafficLight.h* and *MSTTLLogicControl.h* in the end? As far as I know, *microsim* headers are allowed to reference *libsumo* headers.

**Comment by behrisch** [comment]
Thanks for bringing this one up!
