### ISSUE TITLE
Why some junctions could not be joined？

### ISSUE THREAD

**Issue by chen-98** [eclipse/sumo#8863]
I use junctions--join option to process .osm file. Most of them could be joined except several junctions.
see
junction:1949400000
junction:3248000000
junction:3302000000
junction:3333600000
they should be close enough to join like cluster_4632500000_4943700000_5189300000_880600000 , 
and the direction of edges is correct.
How to deal with this situation? Thank you!
Attached .net.xml and .osm
[shahe.txt](https://github.com/eclipse/sumo/files/6890335/shahe.txt)
[shaheroad.net.txt](https://github.com/eclipse/sumo/files/6890336/shaheroad.net.txt)

**Comment by chen-98** [comment]
![image](https://user-images.githubusercontent.com/49219212/127264150-7c1e069b-daec-4c4d-a7a1-5401d1796948.png)

**Comment by namdre** [comment]
A lot of tricky code went into making sure that cluster_4632500000_4943700000_5189300000_880600000 isn't joined any further because joining would destroy the topology of the bypass roads.

If you wish to join that junction cluster anyway (which I would not recommend) then you can do this in netedit by selecting the junctions and pressing F7.

**Comment by chen-98** [comment]
> A lot of tricky code went into making sure that cluster_4632500000_4943700000_5189300000_880600000 isn't joined any further because joining would destroy the topology of the bypass roads.
> 
> If you wish to join that junction cluster anyway (which I would not recommend) then you can do this in netedit by selecting the junctions and pressing F7.

Sorry I didn't make myself clear.
I mean that junction [1949400000,3248000000,3302000000,3333600000] should be joined. Because I think they are close enough. But they didn't join with each other  like I expected. I wonder why?
