### ISSUE TITLE
how to attain the value from a output style like <>

### ISSUE THREAD

**Issue by zhaotuo0815** [eclipse/sumo#8869]
hello,sumo developer,I use traci and the sumolib (netData.getNode(nodeid).getConnections() ) to get the connection information from a nodeID,which return <connection from="EC" to="CN" fromLane="0" toLane="0" tl="C" linkIndex="5" direction="r">, and my question is how to retrieve the value of  "from" or " linkIndex" from  <connection from="EC" to="CN" fromLane="0" toLane="0" tl="C" linkIndex="5" direction="r">.Thank you for your help.

**Comment by schwamborn** [comment]
You can find the pydocs here: https://sumo.dlr.de/pydoc/sumolib.net.connection.html

**Comment by namdre** [comment]
To obtain the linkIndex, call `node.getLinkIndex(connection)`
