### ISSUE TITLE
rwrite tlLogic into sumo.net.xml but the  tlLogic does not show in the netedit

### ISSUE THREAD

**Issue by zhaotuo0815** [eclipse/sumo#8872]
hello,sumo developer,I write the tlLogic into the sumo.net.xml,the tlLogic is like 
```
(    <tlLogic id="C" type="static" programID="0" offset="0">
        <phase duration="31" state="GGGggrrrrGGGggrrrr"/>
        <phase duration="4"  state="yyyggrrrryyyggrrrr"/>
        <phase duration="6"  state="rrrGGrrrrrrrGGrrrr"/>
        <phase duration="4"  state="rrryyrrrrrrryyrrrr"/>
        <phase duration="31" state="rrrrrGGggrrrrrGGgg"/>
        <phase duration="4"  state="rrrrryyggrrrrryygg"/>
        <phase duration="6"  state="rrrrrrrGGrrrrrrrGG"/>
        <phase duration="4"  state="rrrrrrryyrrrrrrryy"/>
        <param key="tk1" value="tv1"/>
        <param key="tk2" value="tv2"/>
    </tlLogic>)
```
and i set the type of the junction "C" to "traffic_light",but when i open the netedit,the junction "C" it does not contain the TL. like the picture as follow.Thank you for your help.
![tl](https://user-images.githubusercontent.com/59630993/127300109-7980d485-e415-401b-8a18-49e1584a0174.png)

**Comment by zhaotuo0815** [comment]
I haven't solved this problem yet, please help me. Thank you so much!

**Comment by zhaotuo0815** [comment]
sumo developer,I use traci and the sumolib (netData.getNode(nodeid).getConnections() ) to get the connection information from a nodeID,which return <connection from="EC" to="CN" fromLane="0" toLane="0" tl="C" linkIndex="5" direction="r">, and my question is how to retrieve the value of  "from" or " linkIndex" from  <connection from="EC" to="CN" fromLane="0" toLane="0" tl="C" linkIndex="5" direction="r">.Thank you for your help.

**Comment by namdre** [comment]
You should never modify the .net.xml directly. Instead add the trafficlight in netedit and then either
- edit the plan in netedit traffic light mode
- load the signal plan from an additional file when running sumo: https://sumo.dlr.de/docs/Simulation/Traffic_Lights.html#defining_new_tls-programs

**Comment by zhaotuo0815** [comment]
> You should never modify the .net.xml directly. Instead add the trafficlight in netedit and then either
> 
> * edit the plan in netedit traffic light mode
> * load the signal plan from an additional file when running sumo: https://sumo.dlr.de/docs/Simulation/Traffic_Lights.html#defining_new_tls-programs

Thank you for your reply! But the question is that if the number of traffic light is large, I can't add them one by one in netedit manually. So how can I customize the traffic light logic based on requirements and junction information in other ways instead of adding traffic light via netedit (i've thought about modifing the net.file before, but it won't work). and I've just tried to load the signal plan from an additional file when running sumo ,and if there's no traffic light in the network, which will return the error like "Error: No initial signal plan loaded for tls '0'."  if  i add the traffic light logic directly to the add.file!

**Comment by namdre** [comment]
If you need to change the type of multiple junctions to "traffic_light" you can write a patch file and apply it with netconvert. See https://sumo.dlr.de/docs/Tutorials/ScenarioGuide.html#example_patching_the_type_of_a_node
Then, use additional files for the custom signal plans.

**Comment by zhaotuo0815** [comment]
> If you need to change the type of multiple junctions to "traffic_light" you can write a patch file and apply it with netconvert. See https://sumo.dlr.de/docs/Tutorials/ScenarioGuide.html#example_patching_the_type_of_a_node
> Then, use additional files for the custom signal plans.

thank you for your help. you are so nice!
