### ISSUE TITLE
libsumo python wheel for python v3.7 compiled against python v3.8

### ISSUE THREAD

**Issue by schwamborn** [eclipse/sumo#8877]

**Comment by behrisch** [comment]
@schwamborn do we need a rebuild of the 1.9.2 wheel or can we wait until 1.10?

**Comment by schwamborn** [comment]
> 
> 
> @schwamborn do we need a rebuild of the 1.9.2 wheel or can we wait until 1.10?

A rebuild of 1.9.2 would be preferable if it's not too much of a hassle.

**Comment by behrisch** [comment]
Should be available here: https://test.pypi.org/project/libsumo/1.9.2.post2/

**Comment by schwamborn** [comment]
Great, thank you!
