### ISSUE TITLE
How is Dynamic Traffic Assignment based on logit model done in SUMO?

### ISSUE THREAD

**Issue by chenming521** [eclipse/sumo#8880]
Generally speaking, the following steps are required for dynamic traffic assignment:
1. Calculate the selection probability of each path based on the logit model, and allocate traffic according to this probability (set to x)
2. Call the simulation program to update the travel time of each path
3. According to the new travel time, use the logit model to calculate the new path selection probability, and redistribute the traffic volume according to this probability to obtain a set of additional traffic (set as x_bar)
4. Update road traffic: x=x+alpha*(x_bar-x)
5. Repeat this process until convergence
What I want to know is how to deal with the step length alpha in sumo. If it is directly set to 1, it means that the path flow is redistributed according to the new travel time, but this is very likely to cause non-convergence; if the alpha is set to another constant, then this is a common SUE problem. Using (x_bar-x) as the search direction may also cause non-convergence.
The only SUE algorithm that can be proven to converge is MSA (I think). I am eager to figure out the principle of Sumo's dynamic traffic assignment, if SUMO's development experts see this question, can you answer it for me? Thanks! @

**Comment by chenming521** [comment]
> Generally speaking, the following steps are required for dynamic traffic assignment:
> 
> 1. Calculate the selection probability of each path based on the logit model, and allocate traffic according to this probability (set to x)
> 2. Call the simulation program to update the travel time of each path
> 3. According to the new travel time, use the logit model to calculate the new path selection probability, and redistribute the traffic volume according to this probability to obtain a set of additional traffic (set as x_bar)
> 4. Update road traffic: x=x+alpha*(x_bar-x)
> 5. Repeat this process until convergence
>    What I want to know is how to deal with the step length alpha in sumo. If it is directly set to 1, it means that the path flow is redistributed according to the new travel time, but this is very likely to cause non-convergence; if the alpha is set to another constant, then this is a common SUE problem. Using (x_bar-x) as the search direction may also cause non-convergence.
>    The only SUE algorithm that can be proven to converge is MSA (I think). I am eager to figure out the principle of Sumo's dynamic traffic assignment, if SUMO's development experts see this question, can you answer it for me? Thanks! @

**Comment by namdre** [comment]
question was re-posted on the mailing list and answered via https://sumo.dlr.de/docs/Demand/Dynamic_User_Assignment.html#forced_convergence
