### ISSUE TITLE
Questions for the actuated traffic lights setting

### ISSUE THREAD

**Issue by thinker310** [eclipse/sumo#8881]
Hello, for the actuated traffic lights in SUMO, I have two questions to ask after I read SUMO documentation. Q1: what is the meaning of 'duration' ? To the best of my knowledge, the actuated traffic lights need three parameters at least, inclding initial green time,  unit extension time and maximum green time. So here I am confused about the attribute 'duration'.
Q2: where is the setting of unit extension time? Can I change it in SUMO?
Thanks for your explanation in advance!

**Comment by namdre** [comment]
Q1:

The 'duration' is not used for normal operation of actuated traffic lights. It only gets used in the following cases
- when using option **--mesosim** where actuation is currently not supported (#8735)
- when doing [time based switching between different plans](https://sumo.dlr.de/docs/Simulation/Traffic_Lights.html#defining_program_switch_times_and_procedure) 

Q2: unit extension time can be any integral number of seconds and is only restricted by minDur and maxDur. The actual value is computed based on the time gaps between vehicles. The corresponding algorithm parameters are explained at https://sumo.dlr.de/docs/Simulation/Traffic_Lights.html#based_on_time_gaps

Feel free to keep posting in this ticket if the question isn't answered to your satisfaction.
