### ISSUE TITLE
OpenStreetMap Import: Changing lane number

### ISSUE THREAD

**Issue by TKeutgens** [eclipse/sumo#8882]
System Information:
NETEDIT 1.9.2
Windows 10

I'm trying to import a road network from OpenStreetMap into Sumo using netedit. 

Unfortunately for road segments, where the number of lanes changes, the road placement does not match the satellite image. For both the road with 3 lanes and 2 lanes the left road edge should be aligned, but apparently, the centers of each road are aligned. 

Is there any setting to fix that issue?

Satellite image as a reference
![grafik](https://user-images.githubusercontent.com/61495604/127464521-59b6a6f0-ef3b-48ee-8c7d-efc539a4dc06.png)

Output of netedit
![grafik](https://user-images.githubusercontent.com/61495604/127464279-7840a2d3-6441-40bd-ae2e-4c2a29cccd55.png)

**Comment by namdre** [comment]
This should be fixable for most motorway networks by setting **--osm.oneway-spread-right** though it wouldn't be a good solution for some urban networks.

**Comment by TKeutgens** [comment]
@namdre  thank you for your quick reply. That helped!
