### ISSUE TITLE
Persons waiting at ptStops are not displayed correctly in sumo-gui

### ISSUE THREAD

**Issue by ArmelliniMG** [eclipse/sumo#8883]
The persons are actually waiting at the public stop, but they are shown at a different position of the edge. The vehicles picked them up at the bus stop anyway, so it looks like a visualization problem.
![grafik](https://user-images.githubusercontent.com/48476390/127468677-bb699de8-f9b3-451e-80a5-2525b02f8ee5.png)

**Comment by namdre** [comment]
possibly related to length/geometry mismatch. Please attach a small test case.

**Comment by ArmelliniMG** [comment]
Test: [test.zip](https://github.com/eclipse/sumo/files/6917112/test.zip)

**Comment by namdre** [comment]
The example does not reproduce the issue for me (tested in windows and linux).

![grafik](https://user-images.githubusercontent.com/6240630/127967544-518b59dd-f6a6-4409-b64d-411a0075f590.png)
![grafik](https://user-images.githubusercontent.com/6240630/127967569-7eff8c10-b825-4fd7-b2f4-64a89fa68bd8.png)

Can you recheck with a freshly built development version?

**Comment by ArmelliniMG** [comment]
I tried again and this time Person 46 is shown right but others have problems. For example Person 47 at stop virtBus_26.
Some persons are also shown outside the network when the option "Draw with constant size when zoomed out" is selected (fig 2)
![grafik](https://user-images.githubusercontent.com/48476390/128321817-cbf0aa87-d891-4f98-90b9-2df5e4eda6f2.png)
![grafik](https://user-images.githubusercontent.com/48476390/128322237-1f17a095-95d5-4fd3-bb5d-9aad109ca5ef.png)

**Comment by namdre** [comment]
Again, I tested on windows and Linux but could not reproduce this.
- is the error repeatable for your or does it change between runs?
- is there a difference between debug and release (same commit)?
- can you reproduce the problem with the official release? (which ones?)

**Comment by ArmelliniMG** [comment]
I found that the error is shown depending on how the view is configurated. I send you a new test with three GUI configurations. Can you please check if the problem is shown to you now?
[test2.zip](https://github.com/eclipse/sumo/files/6944908/test2.zip)

-The visualization problems are shown in TestZoom.sumocfg: with an extended view of the network with persons and stops shown in constant size.
![grafik](https://user-images.githubusercontent.com/48476390/128496715-50c597af-e5bf-417c-a339-466b2ae55cde.png)

-TestZoomLocal.sumocfg: If I zoom in to the area under study, the visualization is right again, despite that persons and stops are still shown with constant size.

-TestNoZoom.sumocfg. If persons and stops are NOT shown with constant size, the visualization is correct, despite the view (extended or zoom in to an area)


To answer your previous questions:
- When maintaining the gui-settings the error is repeatable.
- I have only installed the release version, not debug version.
- I run the simulations with the sumo-version of yesterday morning.

**Comment by namdre** [comment]
I can finally replicate it. Thanks!
