### ISSUE TITLE
undefined behavior when handling internal edges

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#8885]
the test routes\embedded\with_stops_on_junction runs in an infinte loop with the windows release build. All other builds are working fine.
When adding std::cout statements within the while loops of ROEdge.cpp at https://github.com/eclipse/sumo/blob/0baeb4bee16cc0d9d83fe6fd64c01a34302bf0f3/src/router/ROEdge.cpp#L250-L268 the windows release build works as well.

This might be a compiler issue.

**Comment by behrisch** [comment]
Isn't this in fact a bug and this line https://github.com/eclipse/sumo/blob/master/src/router/ROEdge.cpp#L271 should read
`result = result->myApproachingEdges.front();`?

**Comment by namdre** [comment]
Indeed. How in the world did this code ever work in the first place?

**Comment by namdre** [comment]
> Indeed. How in the world did this code ever work in the first place?

Probably because our test has no internal junction so myApproachingEdges already contain the normal edge.
