### ISSUE TITLE
how to defind the traffic light logic in the sumo.net.file

### ISSUE THREAD

**Issue by zhaotuo0815** [eclipse/sumo#8886]
hello, sumo developer ,i want to defind a traffic light logic in the sumo.net.file, in my opinion, firstly, I rewrite the sumo.net.file, and add the traffic light logic like(	
```
        <tlLogic id="C" type="static" programID="0" offset="0">
		<phase duration="42" state="GGGGGrrrrGGGGGrrrr"/>
		<phase duration="3" state="yyyyyrrrryyyyyrrrr"/>
		<phase duration="42" state="rrrrrGGGGrrrrrGGGG"/>
		<phase duration="3" state="rrrrryyyyrrrrryyyy"/>
	</tlLogic>
```
, secondly, I modify the type of the junction that created the traffic light, and  I turn the type="priority"  of the junction into  type="priority",but the the traffic light logic does not work!Am I missing sothing? Thank you for your help.

**Comment by namdre** [comment]
No. You should use Netedit to create a traffic light either by changing the junction type in inspect mode or creating the traffic light in traffic light mode.
Also see https://sumo.dlr.de/docs/FAQ.html#i_made_changes_to_the_netxml-file_but_it_did_not_work_as_expected_why
