### ISSUE TITLE
How to add attribute to an xml file 

### ISSUE THREAD

**Issue by amiradavoudi** [eclipse/sumo#8892]
Hello,

I want to add an attribute such as 'access'  and then assign a value to it in an XML file with the help of "sumolib". 
The root of the xml file is ` <Test>`
I would be very thankful if you could give me a sample for doing so.
Thank you in advance for your help.

I attached the format of the XML file.
[test.txt](https://github.com/eclipse/sumo/files/6909184/test.txt)

```
<Test>
	<taging ID="85779" rty="f75849b" access=??? />
</Test>
```

**Comment by namdre** [comment]
you don't need sumolib and can use 
`sumo/tools/xml/changeAttribute.py -f test.txt -o out.xml -t taging -a access -v VALUE`

with sumolib, you can use sumolib.xml.parse and then call setAttribute() and toXML() on the parsed objects .

**Comment by amiradavoudi** [comment]
> you don't need sumolib and can use
> `sumo/tools/xml/changeAttribute.py -f test.txt -o out.xml -t taging -a access -v VALUE`
> 
> with sumolib, you can use sumolib.xml.parse and then call setAttribute() and toXML() on the parsed objects .

Thank you very much for your clear explanation.
