### ISSUE TITLE
Support nested vTypeDistributions

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#8902]
When defining a vTypeDistribution that references, other distributions, this currently draws a single random type from each inner distribution instead of combining the types of all inner distributions with relative probability. 

Instead of changing all applications, it might be easier to write a small python tool that creates a composite distribution from nested distribution input.

**Comment by behrisch** [comment]
work continues in #8845

**Comment by namdre** [comment]
was solved in #13482
