### ISSUE TITLE
investigate rendering of unicode font in text widgets

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#8907]
Rendering in the GL-Window is limited by gl2ps and lack of shader support by our old OpenGL version (due to Fox toolkit) which precludes FreeType (#5702).

However, rendering in text widgets might use a different code path and be made to work.

**Comment by namdre** [comment]
@behrisch any idea what could cause the platform difference? Maybe installed character sets on the machine?

**Comment by behrisch** [comment]
first check standard font for Fox toolkit on Linux
then check whether we can replace Roboto by something whivch has more unicode

**Comment by namdre** [comment]
This worked on Ubuntu:
- install package `fonts-arphic-ukai` (https://en.wikipedia.org/wiki/Help:Multilingual_support_(East_Asian)#Debian-based_GNU/Linux)
- refresh the font cache: `fc-cache -f -v `
- create ~/.foxrc with contents

```
[SETTINGS]
normalfont="AR PL UKai CN,90"
```

My theory on what is happening:
The default for normalfont is "Sans" which gets mapped to "DejaVu Sans" (according to FXFont::getName, getActualName).
Several programs that render fonts have a per-glyph [fallback](https://eev.ee/blog/2015/05/20/i-stared-into-the-fontconfig-and-the-fontconfig-stared-back-at-me/) to other fonts in order to avoid missing characters. Thats why Chinese characters render fine in webbrowsers, terminals, and text editors.
Fox-toolkit on the other hand picks a single font and sticks with it and this accounts for the missing glyphs.

**Comment by namdre** [comment]
I'm calling this closed since it works in principle. Will update if JVZ has any more suggestions (I asked on the fox list).

**Comment by namdre** [comment]
On Linux a good default font to use might be "Noto Sans CJK JP". This was present by default in my Ubuntu installation.
Fox-toolkit requires the exact font name or it may fall back to it's defaults.
(Font name found via `fc-scan FONTNAME.ttc | grep fullname`).
