### ISSUE TITLE
add 'delete objects' button to selection frame

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#8911]
currently, 'delete' can only be performed with hotkey 'del', which makes it harder to discover this feature

**Comment by namdre** [comment]
@palvarezlopez Can you check if the new tabular button layout interferes with the gui tests?

**Comment by palvarezlopez** [comment]
@namdre ok, but probably not, because it's placed at the end of the button list.

**Comment by namdre** [comment]
its two shorter columns of buttons now.
