### ISSUE TITLE
How to set the driver compliance rate in the simulation？

### ISSUE THREAD

**Issue by Shiyunyang-seu** [eclipse/sumo#8928]
Hi, in the real world, drivers may not fully comply with the rules. 
1. For example of variable speed limit. The road speed limit is 120, but I want 10% of the vehicles driving on this road to be faster than 120.
2. When only trucks are allowed to drive in one lane, but 10% passenger cars will also drive to this lane.
Thanks a lot!

**Comment by namdre** [comment]
Compliance must be configured individually for each model feature:
- speed limit compliance is configured with the speed distribution (non-compliance is the default). See https://sumo.dlr.de/docs/Definition_of_Vehicles,_Vehicle_Types,_and_Routes.html#speed_distributions
- lane access compliance must be configured with custom vehicle classes:

```
<vTypeDistribution id="car">
   <vType id="compliant" vClass="passenger" probability="0.9"/>
   <vType id="noncompliant" vClass="custom1" probability="0.1"/>
</vTypeDistribution>

Then permit vClass "custom1" on truck and passenger car lanes.
