### ISSUE TITLE
Missing methods in libsumojni

### ISSUE THREAD

**Issue by kschrab** [eclipse/sumo#8930]
When implementing libsumojni as a coupling method to Eclipse MOSAIC, we noticed that  some methods are not yet implemented / mapped by the Swig tool chain. There are probably lots of other methods which are not yet configured probably.

```java
// would expect a version object to be returned
SWIGTYPE_p_std__pairT_int_std__string_t version = Simulation.getVersion();

 // would expect a Leader object to be returned
SWIGTYPE_p_std__pairT_std__string_double_t leader = Vehicle.getLeader(vehicleId);

// would expect a StringVector to be returned
SWIGTYPE_p_std__vectorT_std__vectorT_libsumo__TraCILink_t_t controlledLinks = TrafficLight.getControlledLinks(tlId); 

// would expect a VehicleData object to be returned
SWIGTYPE_p_std__vectorT_libsumo__TraCIVehicleData_t vehicleData1 = InductionLoop.getVehicleData(inductionLoopId); 
```

**Comment by behrisch** [comment]
@kschrab @RobertHilbrich Can you think of a better way than mapping the pairs to List<Object>? I mean there is javafx.util.Pair but we probably do not want to depend on javafx. But I also don't want custom classes for every pair of values.

**Comment by kschrab** [comment]
javafx would not be an option. Unfortunately there is now counterpart to c++ Pair in Java standard library. Apache Commons comes with a Pair class, but then you'd depend on commons-lang3. You can use `java.util.AbstractMap.SimpleImmutableEntry` instead, but that's not really clean either. The best approach might be to introduce a separate `Tuple`/`Pair` class.

**Comment by behrisch** [comment]
OK, I think we will invent our own Pair then

**Comment by kschrab** [comment]
That's perfectly fine! :) Thanks

**Comment by behrisch** [comment]
I resolved it with the standard swig typemap way which results in a separate class for every pair type (things like IntIntPair) but is still less code I suppose. Please test (not with the release but with the nightly build of tomorrow)

**Comment by behrisch** [comment]
I hope it is resolved, @kschrab please reopen if not.

**Comment by behrisch** [comment]
The return value needs to be a TraCIResult but we should find a way to let this 

- [ ] get the proper name instead of the convoluted one
- [ ] enable casting to the expected type

**Comment by behrisch** [comment]
Please recheck with the nightly build of tomorrow

**Comment by kschrab** [comment]
Thank you!

Reading the context results now works in principle, but as feared the `TraCIResult` objects can not be cast to the required classes:

![image](https://user-images.githubusercontent.com/2386865/153190963-e101868c-f6f2-44df-bccc-1e5b4584d302.png)

Trying to cast with `(TraCIDouble)contextResults.get("0").get("2").get(0x40)` results in an exception.

If this is too complicated, we could just work-around the problem by parsing the output of `TraCIResult.getString()` 😄

**Comment by behrisch** [comment]
Can you somehow determine what the type (class) of the objects is? It should not be possible to create a plain TraCIResult.

**Comment by kschrab** [comment]
This is from my debug view, those are actually the objects (and its class) returned. So the `SubscriptionResults` contain `TraCIResults` which contain objects of the plain type `TraCIResult`.

**Comment by behrisch** [comment]
@kschrab Maybe we can schedule a debug session together after the summer holidays

**Comment by behrisch** [comment]
The downcasting problem even has a separate section in the swig docs: https://swig.org/Doc4.1/Java.html#Java_adding_downcasts

**Comment by behrisch** [comment]
The implemented solution now adds a cast function to every subclass of TraCIResult, so you can do TraCIInt.cast(result) now and get a TraCIInt.
