### ISSUE TITLE
About how to collect turn-counts.

### ISSUE THREAD

**Issue by parksanha** [eclipse/sumo#8933]
Is there any way to use the python API to collect the turn-count of an intersection?

I searched the python API retrieval document, but couldn't find what I was looking for. Can you give me any advice?

**Comment by m-kro** [comment]
You can retrieve the vehicles on a specific lane calling [traci.lane.getLastStepVehicleIDs()](https://sumo.dlr.de/pydoc/traci._lane.html#LaneDomain-getLastStepVehicleIDs). I think this works with internal lanes of a junction, too.

**Comment by namdre** [comment]
Counting vehicles on internal lanes might not work if vehicles move pass the junction in a single step. However, you can look at vehicles route edges (traci.vehicle.getRoute) and check for a specific sequence edge ids therein. Each turn corresponds to an unique pair of edge ids.
