### ISSUE TITLE
How does rerouting work on compelte route?

### ISSUE THREAD

**Issue by chen-98** [eclipse/sumo#8940]
I built a simulation that defines complete routes for each car like
`<route id="route2271" edges="8420 4215 30745 70368 8084 7062" />
<vehicle  id="3846" type="PrivateCars" route="route2271" depart="1980" departLane="best" departPos="free" departSpeed="desired" />`
During the simulation, some cars stop before the intersection because they can't reach the lane  that allows the desired turning in time. 
So that I add option <device.rerouting.probability value="1"/> on the processing tag. It worked. But I want to know, how does rerouting work on a complete route? Beacuse rerouting on the intersection for a car determines that the car can't follow the defined route perfectly.  Does rerouting ensure the car follows the defined route as much as possible. Or as long as the rerouting worked, the defined route was totally abandoned and only the destination of defined route was considered.

**Comment by chen-98** [comment]
(By the way, the document of Automatic Routing  (https://sumo.dlr.de/docs/Demand/Automatic_Routing.html) is unclear for me  cause I can't find any instructions about where to set those option in the page.

**Comment by namdre** [comment]
Rerouting preserves the destination and any via-edges, stops or waypoints defined for the route.  In your example, only the destination is preserved.

For use of options, see
https://sumo.dlr.de/docs/Basics/Using_the_Command_Line_Applications.html#options
https://sumo.dlr.de/docs/Basics/Using_the_Command_Line_Applications.html#configuration_files
