### ISSUE TITLE
how to Generate real life traffic in sumo ?

### ISSUE THREAD

**Issue by Mortaza-Seydi** [eclipse/sumo#8941]
Hi,

for a reinforcement learning project, i want to simulate vehicles in highways.
how can i generate vehicles like car or bus (demand) **automatically** ?
I do not want to define them one by one explicitly in  ```.rou.xml``` file.
it's important to generate vehicles continuously just like real life.

Thanks.

**Comment by namdre** [comment]
The simples definition for a stream of vehicles use the `<flow>` definition.
If you can make use of traffic data, see See https://sumo.dlr.de/docs/index.html#data_sources_for_demand_generation
If you have counts, I recommend the use of routeSampler.py (https://sumo.dlr.de/docs/Tools/Turns.html#routesamplerpy)
