### ISSUE TITLE
EIDM not showing in SUMO Netedit

### ISSUE THREAD

**Issue by Skyheigh** [eclipse/sumo#8944]
I tried to used EIDM in netedit or xml file. when I open gui for simulation. it said **Error: Unknown car following model 'EIDM' when parsing vType 'EIDM'**

My SUMO version is 1.9.2

**Comment by Domsall** [comment]
The Extended IDM will be available with version 1.10. If you want to use it right away, you will need to pull the version here from github.
Some more information: The Extended IDM is built together from many different published papers. The different characteristics can all be turned off with the correct parameter settings (often =0). The model then becomes the Improved IDM. The model is also intended so run with timesteps ~0.1s. If you want to run simulations with timesteps >0.5s, then the Krauss model or the IDM are the best choices in my opinion.

**Comment by namdre** [comment]
a compiled version with EIDM is available at https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_development_version
