### ISSUE TITLE
polyconvert: expect polygons but got points

### ISSUE THREAD

**Issue by wxinl** [eclipse/sumo#8948]
I was trying to convert shapefiles to poly.xml. My code was: polyconvert --shapefile-prefixes napa_hex7 --shapefile.id-column  hex --shapefile.guess-projection true -o napa_taz.poly.xml

The input shapefiles were polygon, but the output file contains only one point for each feature. What am I supposed to change?

**Comment by namdre** [comment]
polyconvert imports features of type 'point' to `<poi>` and features of type 'linestring', 'multilinestring', 'polygon' and 'multipolygon' to `<poly>`. If you are certain that your shapefile contains one of the above poly inputs, please supply an example input file, so I can check for a potential bug.

**Comment by wxinl** [comment]
Thank you for the reply. I attached a file here.
[shp.zip](https://github.com/eclipse/sumo/files/6994266/shp.zip)

**Comment by namdre** [comment]
It's a bug: polyconvert merges points which are within 0.1 of each other without checking for coordinate system.

As a workaround you can either
- add option **--net-file** to project the polygons into the same reference system as the given network 
- add options **--proj.utm --proj.plain-geo** to convert the polygons to UTM and then reconvert them to WGS84 (lon,lat)

**Comment by wxinl** [comment]
Projection works, thank you

**Comment by namdre** [comment]
It's still a bug that should be fixed even though there is a workaround.
