### ISSUE TITLE
why traci.lanearea.getJamLengthMeters return strange numbers?

### ISSUE THREAD

**Issue by lightly-lyx** [eclipse/sumo#8949]
I called the  traci.lanearea.getJamLengthMeters() during simulation, but I got some strange numbers, such as 5.215606839264604e+170, 6.59377648933455e-310.
I attempted to simulation one step before my first call traci.lanearea.getJamLengthMeters() during my simulation, problem seems to be solved, but I don't know the reason.

**Comment by namdre** [comment]
The value isn't initialized before the first simulation step.
