### ISSUE TITLE
how to make congestion in sumo ?

### ISSUE THREAD

**Issue by Mortaza-Seydi** [eclipse/sumo#8954]
Hi,
I want to create real life congestion in highways (without traffic lights, because there is no traffic lights in highways) .
To solve this problem, if you know a way, please tell me.

The solution that came to my mind was to use a on-ramp. but according to the picture, vehicles on the ramp are waiting for other vehicles to pass and then they enter the highway. is there a way to solve this ?

![Capture](https://user-images.githubusercontent.com/34716943/129723615-45c70536-2286-416c-89e3-f93a60ec93d8.PNG)

my ```rou.xml```
```xml
<!-- highway -->
<route edges="gneE0 gneE1 gneE2 gneE3 gneE4 gneE5 gneE6 gneE7" color="yellow" id="route_0"/>
<!-- on -ramp -->
<route edges="gneE8 gneE7" color="yellow" id="route_1"/>
	
<trip id="vehicle_0" depart="0.00" departLane="best" departPos="random" departSpeed="max" from="gneE0" to="gneE7" via="gneE1 gneE2 gneE3 gneE4 gneE5 gneE6"/>
<trip id="veh_0" depart="0.00" departLane="best" departPos="random" departSpeed="max" from="gneE8" to="gneE7"/>

<trip id="vehicle_1" depart="1.00" departLane="best" departPos="random" departSpeed="max" from="gneE0" to="gneE7" via="gneE1 gneE2 gneE3 gneE4 gneE5 gneE6"/>
<trip id="veh_1" depart="1.00" departLane="best" departPos="random" departSpeed="max" from="gneE8" to="gneE7"/>

....
```

**Comment by namdre** [comment]
What you built is not an on ramp: the acceleration lane is missing. See https://sumo.dlr.de/docs/Simulation/Motorways.html#building_a_network_for_motorway_simulation

To increase the level of congestion, you can tweak the aggressiveness of the merging vehicles via vType attribute 'lcAssertive'.

**Comment by Mortaza-Seydi** [comment]
is this ok ??

![image](https://user-images.githubusercontent.com/34716943/129757312-c4d9ccda-0a70-41cf-9e40-7aaf4c3b8d1d.png)

and ```rou.xml```   ??
```xml
<route edges="gneE0 gneE1 gneE2 gneE3 gneE4 gneE5 gneE6 gneE7 gneE9" color="yellow" id="route_0"/>
<route edges="gneE8 gneE7 gneE9" color="yellow" id="route_1"/>
	
<vType id="myType" lcAssertive="50.00"/>
	
<trip id="veh_0" type="myType" depart="00.00" departLane="best" departPos="random" departSpeed="max" from="gneE8" to="gneE9" via="gneE7"/>
<trip id="vehicle_1" depart="00.00" departLane="best" departPos="random" departSpeed="max" from="gneE0" to="gneE9" via="gneE1 gneE2 gneE3 gneE4 gneE5 gneE6 gneE7"/>
<trip id="vehicle_2" depart="00.00" departLane="best" departPos="random" departSpeed="max" from="gneE0" to="gneE9" via="gneE1 gneE2 gneE3 gneE4 gneE5 gneE6 gneE7"/>
<trip id="veh_2" type="myType" depart="00.00" departLane="best" departPos="random" departSpeed="max" from="gneE8" to="gneE9" via="gneE7"/>
<trip id="vehicle_3" depart="00.00" departLane="best" departPos="random" departSpeed="max" from="gneE0" to="gneE9" via="gneE1 gneE2 gneE3 gneE4 gneE5 gneE6 gneE7"/>

```

**Comment by namdre** [comment]
id recommend values of lcAssertive between 1 and 1.5

**Comment by Mortaza-Seydi** [comment]
Thanks @namdre for your reply
The other problem that i face is that the congestion only happens in 3'rd lane not the first and second.
What can i do for that ?

![Capture](https://user-images.githubusercontent.com/34716943/129857476-208b9350-00e1-4ff7-870a-046fc3becbcf.PNG)

**Comment by namdre** [comment]
This is a known problem with the model: only strategic changes (from the merging vehicles) are urgent enough to cause disturbances on the other lane. Vehicles on the third lane already have their strategic motivation satisfied and do not push urgently into the other lanes *just to gain some speed* regardless of the magnitude of the speed difference. (#1145)

By increasing the value of lcAssertive for all vehicles (not only the merging ones) you will enable some spillover congestion and compensate for the model issue.

**Comment by namdre** [comment]
Another option is to set "lcSpeedGainLookahead" (i.e. 5) This will make vehicles on the right lane of the main flow change to the left before they slow down so much that it's hard to change safely.

**Comment by Mortaza-Seydi** [comment]
```lcSpeedGainLookahead``` does not exist in netedit. we should add it manually.

![Screenshot 2021-08-21 153549](https://user-images.githubusercontent.com/34716943/130319840-e174aecb-8226-43cd-a021-9a57e12e3845.png)

```xml
    <vType id="vType_0" lcAssertive="1.50" lcSpeedGainLookahead="5.00"/>

    <route edges="gneE0 gneE1 gneE2 gneE3 gneE4 gneE5 gneE6 gneE7 gneE8" color="yellow" id="route_0"/>
    <route edges="_gneE7 gneE7 gneE8" color="yellow" id="route_1"/>
    
    <flow id="flow_0" type="vType_0" begin="0.00" departLane="free" route="route_0" end="3600.00" vehsPerHour="900000.00"/>
    <flow id="flow_1" type="vType_0" begin="0.00" departLane="free" route="route_1" end="3600.00" vehsPerHour="1000.00"/>
```
