### ISSUE TITLE
Does version 1.10.0 need an updated SUMOLibraries?

### ISSUE THREAD

**Issue by wxinix** [eclipse/sumo#8961]
The SUMOLibraries has a tag 1.9

Would this create some inconsistencies when trying to build SUMO 1.10?

**Comment by namdre** [comment]
@palvarezlopez do you need to update the tag?

**Comment by palvarezlopez** [comment]
@namdre current SUMOLibrares are compatible with 1.10. But for avoid inconsistences I pushed a new tag
