### ISSUE TITLE
the output of traci.vehicle.setSpeedMode(vehicleID, int("100000", 2)) is wrong.

### ISSUE THREAD

**Issue by Jeffrey28** [eclipse/sumo#8962]
After I set the traci.vehicle.setSpeedMode(vehicleID, int("100000", 2)), but I still get the speedmode is 0 after using getSpeedMode(vehID) to get this value. The result is that the vehicle will take an emergency braking with a deceleration of -9 m/s^2. In the newest introduction, "100000" means that all checks off. So how can I make it work?

**Comment by Jeffrey28** [comment]
After I update the versio of sumo to 1.10.0, it works. That bug exits in sumo-1.9.2.

**Comment by namdre** [comment]
The only documentation always reflects the latest development version. What you are seeing with 1.9.2 is the documented behavior of that version. You may refer to the contents of sumo/docs/userdoc in your installation for version-specific documentation.

**Comment by Jeffrey28** [comment]
But the problem is that when I set the traci.vehicle.setSpeedMode(vehicleID, int("00000", 2)) in sumo-1.9.2, the vehicle still takes an emergency braking.
<img width="749" alt="WeChat Image_20210818143504" src="https://user-images.githubusercontent.com/26816785/129849530-02268428-4617-4f89-963f-4da14504a17a.png">
<img width="769" alt="WeChat Image_20210818143515" src="https://user-images.githubusercontent.com/26816785/129849541-811853c3-4fae-4aa4-a94d-1743f6e0041f.png">

**Comment by namdre** [comment]
This is because conflicts between vehicles that are already on a junction could not be suppressed in 1.9.2 
For this reason a new bit was added to the speed mode in 1.10.0
