### ISSUE TITLE
Vehicles will take an emergency braking with decel=-9.00

### ISSUE THREAD

**Issue by Jeffrey28** [eclipse/sumo#8964]
After I set the speedmode with 32 under sumo-1.10.0, vehicles still take emergency braking with decel=-9.00.  In fact, the vehicles are controlled by my algorithm. If vehicles will collide with each other, just to collide not to take an emergency braking.
![Snipaste_2021-08-18_15-01-38](https://user-images.githubusercontent.com/26816785/129852873-e6acd4f0-d16d-47ed-bbd2-8280bc913d5a.png)

**Comment by namdre** [comment]
Please provide all input files for reproducing this. Instead of attaching your python script, you can supply a trace file of all traci commands: https://sumo.dlr.de/docs/TraCI/Interfacing_TraCI_from_Python.html#generating_a_log_of_all_traci_commands

**Comment by namdre** [comment]
closing due to lack of feedback.
