### ISSUE TITLE
keep attribute order when loading/saving additionals

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#8970]
It is easier to do a diff then

**Comment by namdre** [comment]
is this a duplicate of #7624 or do want to preserve arbitrary user-supplied attribute order?

**Comment by behrisch** [comment]
The reason why I opened it is indeed the same but I thought it would be a good idea in general (not only for busStops).

**Comment by namdre** [comment]
whereas #7624 is easy to solve (it's a single fixed order), a general solution would require the input order to be stored at parsing time which requires a lot more effort.

**Comment by palvarezlopez** [comment]
Currently not neccesary

**Comment by behrisch** [comment]
I needed at least once for a poi file but I admit because of rounding errors it may be not very useful

**Comment by palvarezlopez** [comment]
@behrisch I can try it

**Comment by namdre** [comment]
Are we in agreement that this has low (2.0 level) priority?

**Comment by palvarezlopez** [comment]
I'm not sure. What do you think @behrisch ?

**Comment by behrisch** [comment]
yes

**Comment by palvarezlopez** [comment]
Continue in #9172
