### ISSUE TITLE
Implementation of predefined Driving Cycles / Speed Profiles

### ISSUE THREAD

**Issue by Schiffer-Schmidl** [eclipse/sumo#8971]
Hello everyone,

I´ve recently encountered an issue and cannot find any help online.

I want to implement a predefined driving cycle (for example the WLTP requirements) in one of my scenarios.
I have the required information available in a .csv file (time and required speed at that time step) and want to implement it in
a platooning scenario (ideally as the leader speed).

The purpose is to check rather my implemented car model can pass the WLTP requirements.
I´m grateful for any input.

**Comment by namdre** [comment]
The easiest way to simulate a predefined trajectory is by remote-controlling the vehicles via TraCI.
You can call `traci.vehicle.setSpeed` in each simulation step to override the model speed.  To override safety checks by the model, you can use `traci.vehicle.setSpeedMode`. See https://sumo.dlr.de/docs/TraCI/Change_Vehicle_State.html#speed_mode_0xb3

**Comment by Schiffer-Schmidl** [comment]
Hey @namdre and thank you for your fast reply.
Unfortunately this won´t do, because as I said the purpose is to evaluate the implemented model (a realistic engine model to be precise). Thus the desire is to request certain speeds at certain time steps from the engine (via the .csv file) and to then check, rather the model can reach the desired velocity at the requested times through the engine thrust. Blindly setting the actual speed to the desired value will not be sufficient to evaluate the model.

Sorry if I´ve expressed myself poorly at the first time.

What I´ve written above is the aim of the whole scenario I want to implement.
At the moment I can set the cruising speed to a desired value and this value will then be held throughout the entire simulation until the car (or the platton) comes to a full stop. But what I want to have is a predefined driving cycle with unique desired speeds at unique time steps.

**Comment by namdre** [comment]
Maybe this is what you had in mind? https://sumo.dlr.de/docs/Developer/How_To/Car-Following_Model.html

**Comment by Schiffer-Schmidl** [comment]
Yeah this is kind of the idea. But I now want to have in my omnetpp.ini instead of the command
 " *.node[*].scenario.leaderSpeed = ${leaderSpeed = 80}kmph " (which leads to a constant velocity for the entire simulation)
a way to implement a *.csv file from which the leaderSeepd is written from at specific time steps of the simulation. Thus, implementing a predefined driving profile

**Comment by Schiffer-Schmidl** [comment]
I´m using Segata´s implemented controllers during the simulation. If that helps

**Comment by namdre** [comment]
I was assuming that you are free to use all and any traci commands documented at https://sumo.dlr.de/docs/TraCI.html (which permits step-by-step speed adjustments) whereas you seem to be in a restricted environment. It may be that your question is better directed at the architects of that environment (Veins?).

**Comment by Schiffer-Schmidl** [comment]
Yeah that seems reasonable. I already wrote one of the architects. Hoping for a respond. Thank you very much
