### ISSUE TITLE
review failing ToC tests

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#8973]
tests have been failing for some time. Potentially affected by:
- changes in randomness 
  - 25bb51f499c1427d06a96a971c5dd40eacd20528
  - 670e1cd98c81e2db000b07e060ae5f0cf6234b05
  - 327d7d24c3f20add5d768f620fce6f743a823315
- Toc device changes https://github.com/eclipse/sumo/commit/4f54d973e9b10804f2620d2275e78c0f54bfe81f

It's unclear whether they still test the correct situation and that situation is working as intended.

A first task would be to review the test results after applying either one of the change sets separately.

**Comment by schwamborn** [comment]
Commit 327d7d24c3f20add5d768f620fce6f743a823315 was the one introducing new random numbers (particularly) for the `responseTime` which led to the differences in test results:

- `ToC_with_sampled_responseTime` still works as intended.
- `dynamic_ToC` still works as intended.
- `dynamic_ToC_aborted` **now** works as intended. Before, it did not abort the dynamic ToC.
- `dynamic_ToC_stop` **does not** work as intended, neither before nor now. According to the test case description, it's supposed to test that no dynamic ToC is triggered if a stop lies on the vehicle's current lane continuation. However, both before and now, a dynamic ToC _is_ triggered. I'm not even sure if this ToCDevice feature is actually implemented, at least I did not find any documentation, so far.

**Comment by behrisch** [comment]
In fact it uses the RNG and it also uses normal distribution but even after rounding the log to six digits the discrepancies remain.
