### ISSUE TITLE
error: Negative vehicle step fraction after emergency braking at red light

### ISSUE THREAD

**Issue by chen-98** [eclipse/sumo#8978]
I got the error when runing simlations. It seems like cause by the output of edgeData.
What lead to this problem and how to solve it?
Attached the project files. 
Thank you!
[error.zip](https://github.com/eclipse/sumo/files/7014470/error.zip)

**Comment by namdre** [comment]
The error does not occur if you remove option **step-method.ballistic**. Further investigation is needed.

**Comment by namdre** [comment]
I recommend to add yellow phases to your traffic lights to avoid the emergency braking. Without option **--no-warnings** it would be easier to spot these situations.
