### ISSUE TITLE
output vehroute.xml mixes busStop and containerStop

### ISSUE THREAD

**Issue by rummel123** [eclipse/sumo#8989]
In SUMO-output file vehroute.xml the stops for containers get the attribute "busStop" although the used stop is a "containerStop".
vehroute.xml:
```xml
<container id="container.1" depart="0.00" arrival="1000.00">
    <stop busStop="containerStop1" duration="0.00" until="200.00" started="0.00" ended="200.00"/>
    <transport from="A" to="B" containerStop="containerStop2" lines="taxi" ended="300.00"/>
    <tranship edges="B C" speed="1.39"/>
    <transport from="D" to="C" containerStop="containerStop4" lines="train0" ended="700.00"/>
</container>
```
The container was defined in a containerFlow as follows:
```xml
<containerFlow id="container" begin="0" end="0" number="28">
    <stop containerStop="containerStop1" until="200" duration="0"/> 
    <transport containerStop="containerStop2" lines="taxi"/>
    <tranship containerStop="containerStop3"/>	   
    <transport containerStop="containerStop4" lines="train0"/>
</containerFlow>
```
the containerStop is defined as:
```xml
<containerStop id="containerStop1" lane="xy" startPos="40.00" endPos="120.00" containerCapacity="1"/>
```

**Comment by namdre** [comment]
It's working fine in the committed test. Please attach an example that fails with 1.10 or later.

**Comment by MelanieWeber** [comment]
A small example is attached.

**Comment by MelanieWeber** [comment]
Even with sumo Version v1_10_0+0107-32a7811116 container and containerflows still have busStops instead of containerstops in the vehroute.xml.

    <container id="container" depart="triggered" color="red" arrival="352.00">
        <transport from="149084838#0" to="-149084849" containerStop="containerStop_train" lines="train0" ended="202.00"/>
        <tranship edges="-149084849 -gneE3" speed="1.39"/>
        <stop busStop="containerStop_-gneE3_0" duration="21.00" until="100.00" started="331.00" ended="352.00"/>
    </container>

    <container id="containerflow.0" depart="triggered" color="red" arrival="352.00">
        <transport from="149084838#0" to="-149084849" containerStop="containerStop_train" lines="train0" ended="202.00"/>
        <tranship edges="-149084849 -gneE3" speed="1.39"/>
        <stop busStop="containerStop_-gneE3_0" duration="21.00" until="100.00" started="331.00" ended="352.00"/>
    </container>

**Comment by namdre** [comment]
> A small example is attached.
I was expecting a zip file here.

**Comment by MelanieWeber** [comment]
see s/sumo/bugreports 
it is not that small...
