### ISSUE TITLE
Not an isuue, but I have a few dificulties operating the simulation, and I need some help

### ISSUE THREAD

**Issue by HillelPaley** [eclipse/sumo#8999]
Hi, I'm new to the "Sumo" simulator, and I really need some help.

1. I wasn't able to upload an image to the NetEdit. It says just "Error".
2. I tried to build a network and add cars, but it just doesn't work, and because of that, I don't have any cars in the simulation, so it doesn't work.

I tried looking up everywhere, but in all the tutorials, the guides can do things that for some reason my simulations can't do (not in the way they are showing, at least...)

If someone could help me, I will be VERY grateful to him. I've been working on the simulation for HOURS, and I can do nothing. Please help me.

**Comment by palvarezlopez** [comment]
Hi @HillelPaley,

what do you want to do with the image?

**Comment by namdre** [comment]
did you try https://sumo.dlr.de/docs/Tutorials/OSMWebWizard.html ?
Note, that sumo-gui and netedit are two separate applications.

**Comment by behrisch** [comment]
please reopen if you can give more information
