### ISSUE TITLE
cross day gtfs import

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#9002]
Two peculiarities which are probably related:

- The GTFS file for Berlin contains departure times at certain stops like 24:05:00 if the start time was something like 23:55:00
- The MoveUrban simulation gives error messages like: 
`Warning: busStop '070201072902_0' for vehicle 'U7_106130094.1' on lane '392591722_0' set to end at 86520.00 earlier than previous stop at 172770.00.`

The relevant config for importing is: https://github.com/DLR-TS/tsc/blob/master/data/berlin_net/gtfs/berlin.cfg

**Comment by ArmelliniMG** [comment]
The changes in code fix the problems with trips starting before midnight and ending after.
But it does not add the after midnight part of the trip in the "day 0". 

See vehicles with id "418_132185978.0" and "418_132185786.0" as examples in the tests, which are corresponding to the GTFS trips id 132185978 and 132185786 respectively.

**Comment by behrisch** [comment]
I think it is just fine if we only export the trips which start between *begin* and *end*

**Comment by ArmelliniMG** [comment]
> 
> 
> The changes in code fix the problems with trips starting before midnight and ending after.
> But it does not add the after midnight part of the trip in the "day 0".
> 
> See vehicles with id "418_132185978.0" and "418_132185786.0" as examples in the tests, which are corresponding to the GTFS trips id 132185978 and 132185786 respectively.

Now the tool also adds at the beginning of day "0" the part of trips after midnight.
The test scenario was simplified. See vehicles id "418_132185786.trimmed.0" and "419_132183536.trimmed.0" as examples, which are corresponding to the GTFS trips id 132185786 and 132183536 respectively.
