### ISSUE TITLE
macroscopic simulation with sumo and traci

### ISSUE THREAD

**Issue by Mortaza-Seydi** [eclipse/sumo#9034]
hi, 
I am using sumo for macroscopic simulation. 
I need mean speed, density and vehicle per hour (vehicle/hour) of edges and lanes.
I want to get this values in any time from traci using python.
what can i do for that ?

Thanks.

**Comment by namdre** [comment]
Macroscopic simulation is not supported by traci. However, the result of a macroscopic simulation (values over time) can be retrieved from the output file and thus used from a python context. See https://sumo.dlr.de/docs/Tools/Sumolib.html#parse_all_edges_in_a_edge_data_meandata_file

**Comment by Mortaza-Seydi** [comment]
hi @namdre 
thanks for reply 
I generated that output, but i can't understand what is the logic behind. 
If i want to calculate the variables(density or veh/hour) in my python code, i need to understand formulas and logic.

**Comment by namdre** [comment]
If you set option **--aggregation-interval** to 3600 then "entered" corresponds to veh/hour (for other aggregation intervals, scale accordingly.
The latest development version contains density output for marouter (#9040)
Please refer to 1ed6ef5baada8e2ffd206554c657dbda3ea2ecb0 for the math.

**Comment by Mortaza-Seydi** [comment]
I saw that file, but honestly i didn't realize anything. 
I generated the output file and trying for many hours to guess the formula by tracing simulation step by step using traci, but i couldn't yet.

```xml
<interval begin="0.00" end="20.00" id="edge_data">
  <edge id="_gneE1" sampledSeconds="68.49" traveltime="11.29" overlapTraveltime="11.65" density="34.25" laneDensity="11.42" occupancy="5.67" waitingTime="0.00" timeLoss="49.92" speed="9.02" departed="10" arrived="0" entered="0" left="4" laneChangedFrom="1" laneChangedTo="1"/>
  <edge id="gneE1" sampledSeconds="16.01" traveltime="4.30" overlapTraveltime="4.49" density="8.01" laneDensity="2.67" occupancy="1.27" waitingTime="0.00" timeLoss="4.92" speed="23.37" departed="0" arrived="0" entered="4" left="3" laneChangedFrom="0" laneChangedTo="0"/>
  <edge id="gneE2" sampledSeconds="5.97" traveltime="3.36" overlapTraveltime="3.52" density="2.99" laneDensity="1.00" occupancy="0.47" waitingTime="0.00" timeLoss="0.68" speed="29.84" departed="0" arrived="0" entered="3" left="1" laneChangedFrom="0" laneChangedTo="0"/>
  <edge id="gneE3" sampledSeconds="0.20" traveltime="3.02" overlapTraveltime="3.18" density="0.10" laneDensity="0.03" occupancy="0.01" waitingTime="0.00" timeLoss="0.01" speed="33.06" departed="0" arrived="0" entered="1" left="0" laneChangedFrom="0" laneChangedTo="0"/>
</interval>
```

```python
density = 0
for i in range(0, self.current.edge.getLaneNumber(edge)):
   lane = edge + '_' + str(i)
   density += (self.current.lane.getLastStepVehicleNumber(lane) * self.current.lane.getLastStepLength(lane)) / self.current.lane.getLength(lane)
return density / self.current.edge.getLaneNumber(edge)
```

**Comment by namdre** [comment]
see updated documentation at https://sumo.dlr.de/docs/marouter.html#macroscopic_outputs

**Comment by Mortaza-Seydi** [comment]
can you say some examples of using ```marouter``` command ?

**Comment by namdre** [comment]
from our test suite: `marouter -n input_net.net.xml -d input_taz.taz.xml -m input_od_v.fma -o routes.rou.xml --netload-output aggregated.xml`

**Comment by Mortaza-Seydi** [comment]
please take a look at this photo.
In step 19 there is only one car in lane 'gneE3_0' and lenght of lane is 100m, so the density is equal to 1/0.1 = 10
but the output file says that lane density is 2.02.
How is that possible ? that is my main purpose of openning that issue. 
How sumo calulates this ? is it true or wrong ?

![Untitled](https://user-images.githubusercontent.com/34716943/131526648-47257f60-55eb-4316-8b6e-f70a12b89849.png)

**Comment by namdre** [comment]
This is because edgeData/laneData output estimates the time each car spends on an edge with subsecond resolution. Note, that sampledSeconds is 0.2 in step 19 but 1.0 in step 20.
