### ISSUE TITLE
Two-way left-turn lane in SUMO

### ISSUE THREAD

**Issue by MohamadReza-Haghani** [eclipse/sumo#9038]
Hi,

I was wondering how TWLTLs could be made in SUMO.

Regards,
Reza.

**Comment by MohamadReza-Haghani** [comment]
Thanks dear Jakob. I tried to superimpose two opposite direction lanes to create a TWLTL. The problem is that since there will be two end nodes and two starting nodes for every approach, a traffic light cannot be made in the intersection of four approaches. I was wondering how I can have the superimposed lanes and make a traffic light?

Regards,
Reza.

**Comment by namdre** [comment]
The pair of forward and backward edges with an overlapping lane can have the same starting and ending nodes. All you need to do is modify the geometry of two ormal edges so that they overlap partially. That's what the above documentation link explains.

**Comment by MohamadReza-Haghani** [comment]
I could not make the overlapping edges have the same starting and ending nodes. I was wondering if you could look at this file and tell me what is wrong with my network.

[ezyzip.zip](https://github.com/eclipse/sumo/files/7117821/ezyzip.zip)

**Comment by namdre** [comment]
Select the 3 central junctions in netedit and join them with F7, likewise join the pairs of outer junctions. This corresponds to method https://sumo.dlr.de/docs/Netedit/neteditUsageExamples.html#using_join_selected_junctions

**Comment by MohamadReza-Haghani** [comment]
I used F7 and joined the nodes of opposite direction edges and created a 4-way intersection. There is just one problem. When I want to connect the left-turn of northbound direction to the westbound direction, it does not show me any possible connection. Please find attached my net file.
[ezyzip.zip](https://github.com/eclipse/sumo/files/7124294/ezyzip.zip)

**Comment by namdre** [comment]
The click on the left lane of the northbound edge in connect-mode happens to target the southbound edge. To avoid this, click on the right or middle lane of the northbound edge in inspect mode and select "mark as front element" in the side panel.

**Comment by MohamadReza-Haghani** [comment]
Thank you. It was really helpful. Now, I intend to write a code in Traci to prevent vehicles from moving to TWLTL and only allow some vehicles to move to TWLTL. I was wondering I could do it using what command.

**Comment by namdre** [comment]
You could do this by defining TWLTL attribute "allow" as "custom1" and call traci.vehicle.setVehicleClass to permit/forbid use.

**Comment by MohamadReza-Haghani** [comment]
Is there a way to allow a specific vehicle and prevent other vehicles in the same class from lane changing and moving to a lane?

**Comment by namdre** [comment]
Only by using a temporary custom class for the specific vehicle. The classes custom1 and custom2 exist for this purpose.
