### ISSUE TITLE
Traci.vehicle.setLaneChangeMode

### ISSUE THREAD

**Issue by zhangqi1008** [eclipse/sumo#9042]
Hi:
    Our research wants to make the vehicle lane change more realistic. At present, we have found setLaneChangeMode(self, vehID, lcm). I would like to ask Sets the vehicle's lane change mode as a bitset. How does the bitset explain? Can you have a detailed text introduction? For example, we returned “1621” via getLaneChangeMode. What does this value represent? What does it have to do with LCM?
   Thank you

**Comment by namdre** [comment]
see https://sumo.dlr.de/docs/TraCI/Change_Vehicle_State.html#lane_change_mode_0xb6
For configuring lane changing, also see https://sumo.dlr.de/docs/Definition_of_Vehicles,_Vehicle_Types,_and_Routes.html#lane-changing_models
