### ISSUE TITLE
How to get reports only until vehicles exit the intersection?

### ISSUE THREAD

**Issue by MohamadReza-Haghani** [eclipse/sumo#9056]
Hi,

I am modeling a simple intersection with four 1-mile approaches. I need to calculate the delay of vehicles in the path they enter the network until they exit the intersection. However, if I get the tripinfo results, the calculated delay also includes the delay from the moment vehicles exit the intersection until they exit the network. I was wondering what I should do to omit the second part of delay. Is there a command that I can teleport vehicles when they exit the intersection. So the calculated delay in the tripinfo report would be only the delay between the moment they enter the network and the moment they exit the intersection.

Thanks,
Reza.

**Comment by namdre** [comment]
setting vehicle arrivalPos="0" lets them exit directly after passing the intersection.

**Comment by MohamadReza-Haghani** [comment]
Thank you for you response. Can you please explain more? Where should I put arrivalPos = "0?"

**Comment by namdre** [comment]
into your vehicle/trip/flow definitions: https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#a_vehicles_depart_and_arrival_parameter
