### ISSUE TITLE
tazRelation Mode issues

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#9059]
- [x] always show taz when entering TAZRelation mode
- [x] draw tazRelation on top of everything else
- [x] increase line width for tazRelation
- [x] add dotted contour for inspected tazRelation and the parts that belong to it
- [x] tazRelation should not be visible in network and demand mode

**Comment by monasabeti** [comment]
@namdre  
hello. if you solved your problem, could you please explain it by detail for me?
because i have a same problem

**Comment by palvarezlopez** [comment]
hi @monasabeti what problem do you mean exactly?

**Comment by monasabeti** [comment]
i define the id for my dataset and also time interval and also can create the line of the tazrelation . but i have the problem to see the data:tazRelation when try to inspect it
![Capture](https://user-images.githubusercontent.com/43193011/144590479-df6bea12-4574-4edd-bf0b-6cddaf19c79f.PNG)
.

**Comment by palvarezlopez** [comment]
@monasabeti what sumo version are you using?

**Comment by monasabeti** [comment]
sumo:1.11.0

**Comment by palvarezlopez** [comment]
If you go to inspect mode and click over TAZRel, can you inspect it?

**Comment by monasabeti** [comment]
no, i cant
and exactly this is my problem

**Comment by monasabeti** [comment]
when i am in inspect mode and click on specific taz it show me a data. but when i click on the orange line which is the taz relation it cant inspect the data of tazrelation

**Comment by palvarezlopez** [comment]
@monasabeti thanks! I'm going to check it.

**Comment by palvarezlopez** [comment]
Continue in #9727

**Comment by monasabeti** [comment]
what do you mean exactly to modified the milestones: 1.11.0, 1.12.0?

**Comment by namdre** [comment]
This ticket here concerns work that was done for version 1.11.0. The problem you described is work for 1.12.0 and will be covered in the new ticket #9727

**Comment by monasabeti** [comment]
@palvarezlopez @namdre 
aha, thanks a lot for your quick respond and help

**Comment by monasabeti** [comment]
honestly, i didnt get your point how to solve my problem:\

**Comment by palvarezlopez** [comment]
@monasabeti we're going to fix the problem, and then you can download a new nightly build version from SUMO without the bug :)

**Comment by monasabeti** [comment]
thank you so much again for your respond.

**Comment by monasabeti** [comment]
@palvarezlopez @namdre 
hello, when i install your new built version. i face with this problem :"please declare environment variable 'SUMO_HOME'"
but as always i do, i add the sumo-home environment

**Comment by monasabeti** [comment]
![Capture](https://user-images.githubusercontent.com/43193011/144709046-deb25bef-5f11-4b44-869d-dbb7adf73813.PNG)

**Comment by monasabeti** [comment]
![Capture](https://user-images.githubusercontent.com/43193011/144709093-a0aa85c3-64e5-4eb5-a85e-5b0d5a7f27e0.PNG)

**Comment by monasabeti** [comment]
@palvarezlopez could you please help me to know that how can i solve this problem?

**Comment by palvarezlopez** [comment]
@monasabeti you need to declare **SUMO_HOME**, but you declared **SUMO-HOME**

**Comment by monasabeti** [comment]
you know, i think that because in the bin file there is no sumogui.exe that i can run and set up the sumo. but it is automatically set up and i can run directly from the bin file

**Comment by monasabeti** [comment]
and also in the file that you share with me there is no osmwebwizard.ex and when i write the command python osmWebWizard.py
in cmd i got this error: declare the SUMO-HOME

**Comment by monasabeti** [comment]
and also i think that the problem is that when i want to get the path of sumo in environment variable, i write the address of sumogui.exe. because when i search on my start menu i cant find any file location like this that when i run and set up the sumo from the other file zip
![Capture](https://user-images.githubusercontent.com/43193011/144828527-29ad5549-e8f5-476c-8832-c20ceaaab9cc.PNG)

**Comment by palvarezlopez** [comment]
How did you SUMO Installed? through pip?

**Comment by monasabeti** [comment]
with your file i didnt download any SUMO i think that if i run sumogui in your file everything is fine?
so should i install sumo in addition to your file?

**Comment by monasabeti** [comment]
and again with your new file i cant expect the taz relation data

**Comment by monasabeti** [comment]
@namdre @palvarezlopez 
hello, when i edit my network and generate a new file like osm.net.xml how can i run the new sumocfg after i run the batch file. i mean how can i generate the new sumocfg file according to the specific .xml file.
for example in this picture can see that when generate the tazgrid.add.xml file can access to the tazview.sumocfg
![Untitled](https://user-images.githubusercontent.com/43193011/145254659-c5c49c8e-c125-4607-824d-45c38809c3ba.png)
but when i creat the new file of .xml i dont know how to run and find the new file of sumocfg.

**Comment by namdre** [comment]
Do not post unrelated questions in old tickets. Ask on the mailing list or
open up a new ticket!

Am Mi., 8. Dez. 2021 um 18:26 Uhr schrieb mona ***@***.***>:
