### ISSUE TITLE
i want to get the get the travel time of each car after the trip, what should I do？（using Traci with Python）

### ISSUE THREAD

**Issue by Jinchauuuuu** [eclipse/sumo#9067]

**Comment by Jinchauuuuu** [comment]
i want to get the get the travel time of each car after the trip ,but not using output file tripinfo.xml, what should i do?

**Comment by Jinchauuuuu** [comment]
and another question, when i using "--tripinfo-output.write-unfinished" option insead of "--tripinfo-output" option ,Traci stopped working and a warning was output：_Could not connect to TraCI server using port 63139 (TraCI server already finished). Retrying with different port. warnings.warn(("Could not connect to TraCI server using port %s (%s)." +_ 
I want to know why this is.
my  instruction is：   _traci.start([sumoBinary, "-c", "map_data/wys.sumocfg","--tripinfo-output.write-unfinished","tripinfo.xml"])_

**Comment by namdre** [comment]
> and another question, when i using "--tripinfo-output.write-unfinished" option insead of "--tripinfo-output" option ,Traci stopped working and a warning was output：_Could not connect to TraCI server using port 63139 (TraCI server already finished). Retrying with different port. warnings.warn(("Could not connect to TraCI server using port %s (%s)." +_
> I want to know why this is.
> my instruction is： _traci.start([sumoBinary, "-c", "map_data/wys.sumocfg","--tripinfo-output.write-unfinished","tripinfo.xml"])_

**--tripinfo-output.write-unfinished** must be set together with **--tripinfo-output**. If you are ever in doubt why sumo stops, add option **--log logfile** and look into the logfile.

**Comment by namdre** [comment]
> i want to get the get the travel time of each car after the trip ,but not using output file tripinfo.xml, what should i do?

You can log the departure time for each car in a map by using `traci.simulation.getDepartedIDList` in each time step and use this to calculate the travel time by also checking with `traci.simulation.getArrivedIDList`.

**Comment by Jinchauuuuu** [comment]
Ok, Thank you so much for your reply!
