### ISSUE TITLE
speed mode in SUMO-GUI does not show 6 digits 

### ISSUE THREAD

**Issue by LeoWang71026** [eclipse/sumo#9078]
Hello~ I find there are 6 digits (bit 0 to bit 5) in [document of "speed mode"](https://sumo.dlr.de/docs/TraCI/Change_Vehicle_State.html#speed_mode_0xb3) 
But the SUMO GUI (ver 1.10.0) only shows 5 digits. Bit 5 is gone.
Whenever I set speed mode as 32 via TraCI, the GUI shows "00000" rather than "100000".

![image](https://user-images.githubusercontent.com/53686476/132166512-ed5f2907-f915-4949-a3b8-8c188ded0864.png)

**Comment by namdre** [comment]
Thanks for reporting. You can download the fixed version starting tomorrow at https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_development_version (or build from source)
