### ISSUE TITLE
demand mode: long delay when switching between inspect and select

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#9088]
with ~800 trips loaded in a medium sized network it takes almost 10 seconds to switch between modes.
The console records that the router has spent 0.6**s** answering 787 queries and 0.79**ms** per query.

Observation 1: If nothing has changed, nothing should be recomputed
Observation 2: If the router spends so little time, then something else must be causing the massive delay and this should be fixed as well.

**Comment by palvarezlopez** [comment]
Disadvantages of programming on a very powerful computer :(

**Comment by namdre** [comment]
Should be easily reproducible by running randomTrips.py  on the webwizard test network and loading the generated 3600 trips.
even on a very powerful computer.
