### ISSUE TITLE
Add Tooltip to NETEDIT 

### ISSUE THREAD

**Issue by aminissn** [eclipse/sumo#9092]
Hi,

In the recent updates of NETEDIT many extra buttons have been added to the toolbar for which I cannot find any explanation, see the screenshot below:
![image](https://user-images.githubusercontent.com/30176885/132237246-908bc263-3183-438f-991c-aa5bb5583b6e.png)

Is there a way to add a tooltip i.e. a short tip about each button to appear when the mouse cursor hovers over that button? or a text in the so-called "verbose" window at the bottom?

Thanks,
Sasan

**Comment by palvarezlopez** [comment]
Hi @aminissn,

Thanks for your suggestion. Currently there are a list with the same buttons and a short explanation in "edit", but probably we're going to implement a short tip when the cursor hovers over buttons.

![Sin título](https://user-images.githubusercontent.com/8238561/132243924-2a5d6865-8662-4fb7-a499-2aea266056d0.png)

Regards

**Comment by namdre** [comment]
The tooltips are shown in the bottom status bar when hovering over the button.
