### ISSUE TITLE
About traffic demand generations.

### ISSUE THREAD

**Issue by parksanha** [eclipse/sumo#9093]
Hello~

Is there a way to check the detailed logic for the [Demand Modeling], [Data sources for demand generation] algorithm in the documentation?
ex) dfrouter, flowrouter, jtcrouter, routeSampler, Dynamic User Assignment, etc

I want to understand the exact logic and algorithms and apply them to my projects.

**Comment by namdre** [comment]
You can always check by looking at the code. This is the main reason for having SUMO be open source.
