### ISSUE TITLE
invalid junction logic at complex junction (trac #911)

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#911]
netbuild fails to compute the correct foe/response relations for a complex junction.

see M:\Daten\sumo\bugreports\911_invalid_junction_logic for the net.xml

Migrated from http://sumo.dlr.de/ticket/911
```json
{
    "status": "new", 
    "changetime": "2013-09-10T09:24:50Z", 
    "description": "netbuild fails to compute the correct foe/response relations for a complex junction.\n\nsee M:\\Daten\\sumo\\bugreports\\911_invalid_junction_logic for the net.xml", 
    "reporter": "namdre", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1378805090384370", 
    "component": "net building (NETGEN, NETCONVERT)", 
    "summary": "invalid junction logic at complex junction", 
    "priority": "major", 
    "keywords": "", 
    "time": "2013-05-29T15:17:24Z", 
    "milestone": "1.0.0", 
    "owner": "", 
    "type": "defect"
}
```

**Comment by behrisch** [comment]
This is a strange network with unconnected lanes but the foes still do not look correct to me.

**Comment by namdre** [comment]
When rebuilding the network, the right-of-way matrix is fine. Also, the link indices are numbered continuously when going around rather then with back-and-forth jumps (which indicates invalid edge ordering and was most likely responsible for the issue).
