### ISSUE TITLE
tazRelation mode: no feedback on first click when creating relation

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#9112]
- fromTaz should be highlighted green like the edge in edgeRelation mode
- on second click toTaz green, fromTaz cyan (like edgeRelation mode)
- creation of tazRelation should be confirmed with <ENTER> or button click like edgeRelation mode and aborted with <ESC>

**Comment by palvarezlopez** [comment]
Fixed

**Comment by monasabeti** [comment]
@palvarezlopez 
hello.
i define the id for my dataset and also time interval and also can create the line of the tazrelation . but i have the problem to see the data:tazRelation when try to inspect it.



![Capture](https://user-images.githubusercontent.com/43193011/144590134-c955f359-d584-4b79-bd4d-10050a73d574.PNG)

**Comment by namdre** [comment]
@monasabeti I've moved this to a new ticket: #9728
