### ISSUE TITLE
Vehicles disappearing in the intersection

### ISSUE THREAD

**Issue by MohamadReza-Haghani** [eclipse/sumo#9130]
Hi,

I made a 4-way intersection with a traffic signal. I made a TWLTL for every approach. The problem is when vehicles enter the intersection, they disappear. Then when they want to exit the intersection they appear and continue their trip. I was wondering to know what is the problem that I do not see them in the intersection. Please find attached SUMO files.

Regards,
Reza.

[ezyzip.zip](https://github.com/eclipse/sumo/files/7132520/ezyzip.zip)

**Comment by namdre** [comment]
your network was built without internal links (https://sumo.dlr.de/docs/Simulation/Intersections.html#internal_links)
The easiest fix is `netconvert -s VEL.net.xml -o VEL.net.xml --no-internal-links false`

**Comment by MohamadReza-Haghani** [comment]
Thank you. I was wondering if there is a way to add internal links via Netedit or Traci Python.

**Comment by namdre** [comment]
netedit: F10, junctions tab, uncheck "no internal links", save network
traci: no
