### ISSUE TITLE
improve tazRelation UI

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#9131]
task ordering by priority

- [x] fix invalid geometry in border-to-border mode
- [x] add lateral offset to separate from/to relations
- [x] in inspect mode allow filtering the drawn taz
   - [x]  allow inspecting taz
   - [x] add drawing flags "tazRelations from inspected taz" -> hides all other tazRelations
   - [x] add drawing flags "tazRelations to inspected taz" -> hides all other tazRelations
   - [x] both flags can be combined to show all tazRelations from/to the inspected taz but no other
- [x] in tazRelation mode, show only relations for the current interval
- [x] add gui-settings tab for data-mode related coloring
     - [x] color tazRelations by from-taz-color/to-taz-color/attribute ...
- [ ] scale tazRelation width by their count attribute (should eventually be refined via gui visualisation settings to pick the attribute and scaling function but even scaling this linearly from minCount to maxCount is a big step forward)
- [x] add taz-fill-transparency toggle to data inspect mode
- [x] set default of toggle-taz-rel only-from/to to true
- [ ] when inspecting a tazRel of the currently inspected taz, keep the visibility of other tazRel unchanged (don't switch tazRel from all other taz back on)
- [x] scale side offset of from/to tazrel with tazRel-exaggeration

**Comment by behrisch** [comment]
scaling may be moved to a new ticket

**Comment by namdre** [comment]
follow-ups are #12003, #12004
