### ISSUE TITLE
How to change the width of the lane with Traci 

### ISSUE THREAD

**Issue by Morefrees** [eclipse/sumo#9134]
The default width of the lane I know now seems to be 3.2m, I want to change the width of the lane through Traci, I hope you can give me some guidance .
Thanks in advance ！

**Comment by namdre** [comment]
lane width is a static network parameter than cannot be changed at runtime (only with netconvert/netedit).
You might define additional lanes and allow/disallow them via traci.

**Comment by Morefrees** [comment]
Can Traci control netconvert/netedit to change the width of the lane? T_T ...

**Comment by namdre** [comment]
From a traci script you can call system commands (i.e. via the subprocess module of python). See https://sumo.dlr.de/docs/Tutorials/ScenarioGuide.html#modifying_the_network
