### ISSUE TITLE
no screen refresh when first switching to new frame on Linux

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#9138]
when opening a large network and entering a new mode for the first time (inspect, delete or select) the screen is not refreshed and the frame stays gray.  
The problem is resolved by moving the mouse or hitting a key.

- works fine in small networks
- works fine on windows
- works fine in modes that trigger "compute"
- works fine when entering the new frame a second time

**Comment by behrisch** [comment]
I tried it with two different ingolstadt networks and with brunswick but could not reproduce

**Comment by namdre** [comment]
With these steps I can reproduce it on ubuntu 20.4 and REHL7:
- netedit -s tests/tools/import/OSMwebwizard/osmimport.tools
- press 's'  -> selection frame is gray until moving the mouse

**Comment by behrisch** [comment]
Works just fine here (openSUSE 15.3). Which graphics card (if any)?

**Comment by namdre** [comment]
cannot reproduce
