### ISSUE TITLE
disable traci log print

### ISSUE THREAD

**Issue by Mortaza-Seydi** [eclipse/sumo#9142]
Hi,
when i am using traci. it prints logs like that in stdout.
```
Step #3600.00 (1ms ~= 1000.00*RT, ~88000.00UPS, TraCI: 10ms, vehicles TOT 3082 ACT 88 BUF
Step #3600.00 (1ms ~= 1000.00*RT, ~119000.00UPS, TraCI: 10ms, vehicles TOT 3082 ACT 119 BU
``` 
how can i disable that ?
my run command:
```python
sumo_cmd = [sumo_binary, "-c", self.sumo_cfg, "--no-step-log", "true", "--duration-log.disable", "true"]
traci.start(sumo_cmd, label=f"current-{pid}")
```

**Comment by namdre** [comment]
The option --no-step-log disables this output. Please let your simulation write some kind of xml output file (i.e. tripinfo output) and then check in the xml header for the list of options that were actually used.
