### ISSUE TITLE
Defining random departure lane in specific lanes

### ISSUE THREAD

**Issue by MohamadReza-Haghani** [eclipse/sumo#9150]
Hi,

I was wondering how departure lane could be set to random but from specific lanes in defining traffic flow. Consider a one direction road segment with three lanes. I want vehicles to choose their departure lane randomly between the first and second lane but do not use the third lane.

Regards,
Reza.

**Comment by namdre** [comment]
This currently isn't possible. However, if those lanes should never be used (i.e. trucks on the leftmost lane) you could tweak the permissions (allow/disallow) of the lane to achieve this effect.
