### ISSUE TITLE
Does the traffic demand generation models also take into account traffic signal data to generate routes?

### ISSUE THREAD

**Issue by parksanha** [eclipse/sumo#9153]
Hello~

Does the traffic demand generation models also take into account traffic signal data to generate routes?
For example, I would like to know if the functions listed below take traffic signal data into account when making traffic demand.

dfrouter, flowrouter, jtcrouter, routesampler, etc

**Comment by namdre** [comment]
- dfrouter, flowrouter, jtrcouter: no
- routeSampler: potentially, because candidate routes are part of the input and you can generate routes that do consider those things (i.e. from a random-traffic simulation)
