### ISSUE TITLE
Interpreting the result of "getLaneChangeStatePretty" command in Traci

### ISSUE THREAD

**Issue by MohamadReza-Haghani** [eclipse/sumo#9160]
Hi,

I was wondering how the results of "getLaneChangeStatePretty" command should be interpreted in different directions. I wrote this command for direction = 0, and got (['left', 'sublane'], ['left', 'TraCI', 'urgent']) as the result. If this command is for straight direction, why there is 'left' in its result?

Thanks,
Reza.

**Comment by namdre** [comment]
when simulating with the sublane model, left and right indicate only the direction of the change and direction 0 indicates desired lateral movements within the current lane.

**Comment by MohamadReza-Haghani** [comment]
Thank you. I intend to order a vehicle to change lane and move to the left lane, but it does not follow Traci's order. When I use get lane change state pretty command for directions of 1, 0, -1, I get the following results, respectively:

(['left', 'TraCI', 'urgent'], ['left', 'TraCI', 'urgent']) (['stay', 'sublane'], ['left', 'TraCI', 'urgent', 'sublane']) (['stay', 'right', 'keepRight', 'sublane'], ['left', 'TraCI', 'urgent', 'sublane'])

I was wondering to know if "keepright" of direction -1 prevents it from lane changing.

Regards,
Reza.

**Comment by namdre** [comment]
I don't think that this is the problem. I assume you're referring to #9147 and you can check the maneuver distance in the vehicle parameter dialog of sumo-gui that shows this to be 0 (which is how the bug manifests).

**Comment by MohamadReza-Haghani** [comment]
Thank you. Yes, I am referring to #9147, and I read your answer to it. My other question is why the result of get lane change state command with direction -1 should be (['stay', 'right', 'keepRight', 'sublane'], ['left', 'TraCI', 'urgent', 'sublane']) when the vehicle intends to move to left lane. Since direction -1 means right direction and the vehicle intends to move to left lane, I was wondering why the result of get lane change state command with direction -1 is not empty.

**Comment by namdre** [comment]
The command returns two values: 
- the original state desired by the model and 
- the used state as influenced by traci 

Note, that even without traci, the sublane model may decide to move left within the current lane when considering a change to the right side.

**Comment by MoMingQimio** [comment]
current_lane_index = traci.vehicle.getLaneIndex(self.ego)

		if action == 0:
			# do nothing: stay in the current lane
			pass
		elif action == 1:
			a, b = traci.vehicle.getLaneChangeStatePretty(self.ego, -1)
			c, d = traci.vehicle.getLaneChangeStatePretty(self.ego, 0)
			e, f = traci.vehicle.getLaneChangeStatePretty(self.ego, 1)
			target_lane_index = min(current_lane_index+1, self.num_of_lanes-1)
			traci.vehicle.changeLane(self.ego, target_lane_index, 0.1)
			a1, b1 = traci.vehicle.getLaneChangeStatePretty(self.ego, -1)
			c1, d1 = traci.vehicle.getLaneChangeStatePretty(self.ego, 0)
			e1, f1 = traci.vehicle.getLaneChangeStatePretty(self.ego, 1)
			print("right lane change state before: ",a,b,c,d,e,f)
			print("right lane change state after: ",a1,b1,c1,d1,e1,f1)
		elif action == 2:
			a, b = traci.vehicle.getLaneChangeStatePretty(self.ego, -1)
			c, d = traci.vehicle.getLaneChangeStatePretty(self.ego, 0)
			e, f = traci.vehicle.getLaneChangeStatePretty(self.ego, 1)
			target_lane_index = max(current_lane_index-1, 0)
			traci.vehicle.changeLane(self.ego, target_lane_index, 0.1)
			a1, b1 = traci.vehicle.getLaneChangeStatePretty(self.ego, -1)
			c1, d1 = traci.vehicle.getLaneChangeStatePretty(self.ego, 0)
			e1, f1 = traci.vehicle.getLaneChangeStatePretty(self.ego, 1)
			print("left lane change state before: ",a,b,c,d,e,f)
			print("left lane change state after: ",a1,b1,c1,d1,e1,f1)
			
this is my code


and here are my results

right lane change state before:  ['right', 'sublane'] ['left', 'TraCI'] ['right', 'sublane'] ['left', 'TraCI'] ['left', 'TraCI'] ['left', 'TraCI']
right lane change state after:  ['right', 'sublane'] ['left', 'TraCI'] ['right', 'sublane'] ['left', 'TraCI'] ['left', 'TraCI'] ['left', 'TraCI']
left lane change state before:  ['right', 'sublane'] ['left', 'TraCI'] ['right', 'sublane'] ['left', 'TraCI'] ['left', 'TraCI'] ['left', 'TraCI']
left lane change state after:  ['right', 'sublane'] ['left', 'TraCI'] ['right', 'sublane'] ['left', 'TraCI'] ['left', 'TraCI'] ['left', 'TraCI']
right lane change state before:  ['left', 'TraCI'] ['left', 'TraCI'] ['right', 'sublane'] ['left', 'TraCI'] ['right', 'sublane'] ['left', 'TraCI']
right lane change state after:  ['left', 'TraCI'] ['left', 'TraCI'] ['right', 'sublane'] ['left', 'TraCI'] ['right', 'sublane'] ['left', 'TraCI']
left lane change state before:  ['right', 'sublane'] ['left', 'TraCI'] ['right', 'sublane'] ['left', 'TraCI'] ['left', 'TraCI'] ['left', 'TraCI']
left lane change state after:  ['right', 'sublane'] ['left', 'TraCI'] ['right', 'sublane'] ['left', 'TraCI'] ['left', 'TraCI'] ['left', 'TraCI']
left lane change state before:  ['left', 'TraCI'] ['left', 'TraCI'] ['right', 'sublane'] ['left', 'TraCI'] ['right', 'sublane'] ['left', 'TraCI']
left lane change state after:  ['left', 'TraCI'] ['left', 'TraCI'] ['right', 'sublane'] ['left', 'TraCI'] ['right', 'sublane'] ['left', 'TraCI']
right lane change state before:  ['left', 'TraCI'] ['left', 'TraCI'] ['right', 'sublane'] ['left', 'TraCI'] ['right', 'sublane'] ['left', 'TraCI']
right lane change state after:  ['left', 'TraCI'] ['left', 'TraCI'] ['right', 'sublane'] ['left', 'TraCI'] ['right', 'sublane'] ['left', 'TraCI']
left lane change state before:  ['right', 'sublane'] ['left', 'TraCI'] ['right', 'sublane'] ['left', 'TraCI'] ['left', 'TraCI'] ['left', 'TraCI']
left lane change state after:  ['right', 'sublane'] ['left', 'TraCI'] ['right', 'sublane'] ['left', 'TraCI'] ['left', 'TraCI'] ['left', 'TraCI']
left lane change state before:  ['left', 'TraCI'] ['left', 'TraCI'] ['right', 'sublane'] ['left', 'TraCI'] ['right', 'sublane'] ['left', 'TraCI']
left lane change state after:  ['left', 'TraCI'] ['left', 'TraCI'] ['right', 'sublane'] ['left', 'TraCI'] ['right', 'sublane'] ['left', 'TraCI']
left lane change state before:  ['left', 'TraCI'] ['left', 'TraCI'] ['right', 'sublane'] ['left', 'TraCI'] ['right', 'sublane'] ['left', 'TraCI']
left lane change state after:  ['left', 'TraCI'] ['left', 'TraCI'] ['right', 'sublane'] ['left', 'TraCI'] ['right', 'sublane'] ['left', 'TraCI']
..................................................................................
left lane change state before:  ['left', 'TraCI'] ['left', 'TraCI'] ['left', 'TraCI', 'sublane'] ['left', 'TraCI', 'sublane'] ['left', 'TraCI', 'sublane'] ['left', 'TraCI', 'sublane']
left lane change state after:  ['left', 'TraCI'] ['left', 'TraCI'] ['left', 'TraCI', 'sublane'] ['left', 'TraCI', 'sublane'] ['left', 'TraCI', 'sublane'] ['left', 'TraCI', 'sublane']
right lane change state before:  ['left', 'TraCI'] ['left', 'TraCI'] ['left', 'TraCI', 'sublane'] ['left', 'TraCI', 'sublane'] ['left', 'TraCI', 'sublane'] ['left', 'TraCI', 'sublane']
right lane change state after:  ['left', 'TraCI'] ['left', 'TraCI'] ['left', 'TraCI', 'sublane'] ['left', 'TraCI', 'sublane'] ['left', 'TraCI', 'sublane'] ['left', 'TraCI', 'sublane']
left lane change state before:  ['left', 'TraCI', 'sublane'] ['left', 'TraCI', 'sublane'] ['left', 'TraCI', 'sublane'] ['left', 'TraCI', 'sublane'] ['left', 'TraCI'] ['left', 'TraCI']
left lane change state after:  ['left', 'TraCI', 'sublane'] ['left', 'TraCI', 'sublane'] ['left', 'TraCI', 'sublane'] ['left', 'TraCI', 'sublane'] ['left', 'TraCI'] ['left', 'TraCI']
right lane change state before:  ['left', 'TraCI'] ['left', 'TraCI'] ['left', 'TraCI', 'sublane'] ['left', 'TraCI', 'sublane'] ['left', 'TraCI', 'sublane'] ['left', 'TraCI', 'sublane']
right lane change state after:  ['left', 'TraCI'] ['left', 'TraCI'] ['left', 'TraCI', 'sublane'] ['left', 'TraCI', 'sublane'] ['left', 'TraCI', 'sublane'] ['left', 'TraCI', 'sublane']
left lane change state before:  ['left', 'TraCI', 'sublane'] ['left', 'TraCI', 'sublane'] ['left', 'TraCI', 'sublane'] ['left', 'TraCI', 'sublane'] ['left', 'TraCI'] ['left', 'TraCI']
left lane change state after:  ['left', 'TraCI', 'sublane'] ['left', 'TraCI', 'sublane'] ['left', 'TraCI', 'sublane'] ['left', 'TraCI', 'sublane'] ['left', 'TraCI'] ['left', 'TraCI']
.....
.....
......


I want to know why the original state desired by the model can contain "traci" , and what is the mechanism in here, did the sublane indicate the SL2015 lane change model?  why the traci and sublane in the same list?

**Comment by namdre** [comment]
- When a lane change maneuver takes multiple simulation steps (is is typical when using the sublane model), the 'traci' state from the previous step of the ongoing maneuver will be preserved and show up in the original state
- The 'sublane' state is unrelated to the traci action (the original state indicates a desired to move back to the center of the lane rather than executing a traci-motivated change)
