### ISSUE TITLE
Can I use a function of sumo-traci to obtain a edge‘s real-time vehicle information?

### ISSUE THREAD

**Issue by Jinchauuuuu** [eclipse/sumo#9173]
I want to get the vehicle information of the edge during the operation of sumo (how many cars there are, the ID of the cars, etc.) Can I use a function of sumo-traci to obtain a edge‘s real-time vehicle information? like: traci.route.getVehinf(EdgeID)

**Comment by namdre** [comment]
traci.edge.getLastStepVehicleIDs
traci.lane.getLastStepVehicleIDs

**Comment by Jinchauuuuu** [comment]
> traci.edge.getLastStepVehicleIDs
> traci.lane.getLastStepVehicleIDs

Thanks a lot!
