### ISSUE TITLE
A question about the procedure of changeLane and changeSublane commands

### ISSUE THREAD

**Issue by MohamadReza-Haghani** [eclipse/sumo#9176]
Hi, 

I was wondering how changeLane and changeSublane Traci commands work. For instance, when we write a code and order a vehicle to change lane at a specific point, it would try changing lane once and if not applicable, it would leave it or it would keep trying to complete the lane change until its done. Also, I have a problem with my code. I ordered the vehicles in a specific vehicle flow to change lane if their position is between 150 and 160 but did not observe any lane changing. Please find attached the SUMO files and Python code.

Regards,
Reza.

[ezyzip.zip](https://github.com/eclipse/sumo/files/7186362/ezyzip.zip)

**Comment by namdre** [comment]
changeLane uses the duration argument and the vehicle will try to reach that lane and remain there for the given duration.
In contrast, changeLaneSublane is only attempted in the current step and ignored afterwards. 
You can use setLaneChangeMode to make the laneChange ignore some or all safety constraints.
Testing different flags also allows you to investigate the reason why a lanechange did not succeed.

Feel free to re-post to this question if the reason remains unclear after this.

**Comment by MohamadReza-Haghani** [comment]
Thank you. I was wondering to know what you mean by flag and how I can see flag. I was also wondering if you had a chance to take a look at my code. I wrote a print command after lane changing command in my code to realize when the lane changing command is used. I am surprised why nothing was printed showing that the lane changing command was not sent to vehicles.

Regards,
Reza.

**Comment by namdre** [comment]
"flag" is a technical term for a combination of bits that are used to define the lane change mode. 
Debugging other peoples traci scripts is something I try to avoid as much as possible because it detracts from my own work. 
If your script doesn't even send lane change commands than this is obviously not a sumo bug.
