### ISSUE TITLE
Allow combination of 'turn' with 'lanes'/'lateralDistance' subscription filters

### ISSUE THREAD

**Issue by schwamborn** [eclipse/sumo#9177]
[updated]
So far, the `lanes` and `lateralDistance` filters were ignored when turning on the `turn` subscription filter. A combination of `turn` with either `lanes` or `lateralDistance` filter should result in the union of the individual result sets. Also related to  #9141.

**Comment by namdre** [comment]
After the latest meeting, I have confirmed that we also need to allow the combination of lateralDistance and turn filters.
