### ISSUE TITLE
The difference between vehicle positions observed in SUMO GUI and Traci

### ISSUE THREAD

**Issue by MohamadReza-Haghani** [eclipse/sumo#9178]
Hi,

I noticed the position that Traci gives with getDistance command is different from the position I observe in SUMO GUI at the same time. I was wondering to know the reason. Please find attached SUMO files.

Thanks,
Reza.

[ezyzip.zip](https://github.com/eclipse/sumo/files/7186691/ezyzip.zip)

**Comment by namdre** [comment]
please see #1463

**Comment by MohamadReza-Haghani** [comment]
I looked at #1463. In this issue, Michael said TraCI returns vehicle positions at the beginning of a time step and GUI show vehicle positions of the end of time step. However, I checked it, and, in my simulation, the difference was more than one time step.

**Comment by MohamadReza-Haghani** [comment]
Hi,

With attention to the difference between positions showed in Traci and GUI, I was wondering to know that fcd output would be based on Traci position or GUI position. I am writing a code with Traci to stop one vehicle when it is at a specific distance from another vehicle. Therefore, it is important that this specific distance is observed in their speed profile that is drawn based on fcd output.

Thanks,
Reza.

**Comment by namdre** [comment]
fcd-output should match gui-output as it shows the position at the end of the time step.

Regarding your comment from Sep 17, can you provide an example?

**Comment by namdre** [comment]
The value of `traci.vehicle.getDistance` depends on the insertion position of the vehicle. It should match the lane position from the end of the previous step if departPos="0". 
The default departPos is is the length of the vehicle (i.e. 5m) so getDistance always returns a value that is reduced by 5 (since the vehicle get a 5m head start).
