### ISSUE TITLE
Implement GeneralHandler

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#9200]
GeneralHandler allow to parse from the same file route, additional and data elements. It's needed to avoid problems loading Rerouters (because is an additional with a reference to a route):

GeneralHandler (file)
|->AdditionalHandler
|->RouteHandler
|->~~DataHandler~~

**Comment by palvarezlopez** [comment]
Finish

**Comment by behrisch** [comment]
Just two questions about this:
What is the difference to the SUMOSAXHandler?
Why aren't the RouteHandler and the AdditonalHandler not subclasses of the GeneralHandler?

**Comment by palvarezlopez** [comment]
@behrisch GeneralHandler ist just only a "abstraction layer". Is used by GNEGeneralHandler and will be used for SUMOGeneralHandler. The difference between GeneralHandler and SUMOSAXHandler is low, but in the future can be usefull.

About RouteHandler and AdditionalHandler, they are not subclasses of GeneralHandler because they aren't SUMOSAXHandler
