### ISSUE TITLE
Can't run the libtraci example

### ISSUE THREAD

**Issue by HuaweiAlgolux** [eclipse/sumo#9212]
I created a cpp file called _traci_sumo_run.cpp_, and the code is just a copy from this page https://sumo.dlr.de/docs/Libtraci.html
```
#include <iostream>
#include <libsumo/libtraci.h>

using namespace libtraci;

int main(int argc, char* argv[]) {
  Simulation::start({"sumo", "-n", "net.net.xml"});
  for (int i = 0; i < 5; i++) {
    Simulation::step();
  }
  Simulation::close();
}
```
This _traci_sumo_run.cpp_ file is located under the path ~/sumo/
 I compiled the code using 
`g++ -o traci_sumo_run -std=c++11 -I$SUMO_HOME/src traci_sumo_run.cpp -L$SUMO_HOME/bin -ltracicpp`
And then ran the program as follows
`LD_LIBRARY_PATH=$SUMO_HOME/bin ./traci_sumo_run`
Then I got this error:
```
Error: File 'net.net.xml' is not accessible (No such file or directory).
Quitting (on error).
terminate called after throwing an instance of 'tcpip::SocketException'
  what():  tcpip::Socket::recvAndCheck @ recv: Connection reset by peer
Aborted (core dumped)
```

---
*If possible, upload an example that shows your problem.*

**SUMO-version:** Eclipse SUMO sumo Version v1_10_0+0867-85e8b1b8e4d

**operating system:** Ubuntu 18.04

**Comment by namdre** [comment]
The example assumes basic familiarity with sumo. To run the simulation you need to provide a sumo network file (`net.net.xml` is just an example file name here). You can copy any .net.xml file from sumo/docs/examples/sumo into your working directory for this.
