### ISSUE TITLE
How to query all the agents, traffic and street signs 200m around the ego vehicle using libtraci?

### ISSUE THREAD

**Issue by HuaweiAlgolux** [eclipse/sumo#9219]
I'm pretty new to libtraci. Can anyone give an example of how to get info around ego vehicle in C++?
and how to modify the desired speed and the following distance of ego vehicle based on the speed of the front car and how far the front car is?
how to check the upcoming traffic lights and street sign based on where the ego vehicle is?
how to check if a car is in front of ego vehicle?
  
---
*If possible, upload an example that shows your problem.*

**SUMO-version:** 1.10

**operating system:** Ubuntu 18.04

**Comment by namdre** [comment]
I recommend to familiarize yourself with the following methods
- traci.vehicle.subscribeContext (https://sumo.dlr.de/docs/TraCI/Interfacing_TraCI_from_Python.html#context_subscriptions)
- traci.vehicle.getLeader
- traci.vehicle.getNextTLS
- traci.vehicle.getFollowSpeed, traci.vehicle.getStopSpeed
- traci.vehicle.setSpeed, traci.vehicle.slowDown

see 
https://sumo.dlr.de/pydoc/traci._vehicle.html#VehicleDomain (The method names are the same in C++ as in python)
https://sumo.dlr.de/docs/TraCI/Change_Vehicle_State.html
https://sumo.dlr.de/docs/TraCI/Vehicle_Value_Retrieval.html

**Comment by HuaweiAlgolux** [comment]
> I recommend to familiarize yourself with the following methods
> 
> * traci.vehicle.subscribeContext (https://sumo.dlr.de/docs/TraCI/Interfacing_TraCI_from_Python.html#context_subscriptions)
> * traci.vehicle.getLeader
> * traci.vehicle.getNextTLS
> * traci.vehicle.getFollowSpeed, traci.vehicle.getStopSpeed
> * traci.vehicle.setSpeed, traci.vehicle.slowDown
> 
> see
> https://sumo.dlr.de/pydoc/traci._vehicle.html#VehicleDomain (The method names are the same in C++ as in python)
> https://sumo.dlr.de/docs/TraCI/Change_Vehicle_State.html
> https://sumo.dlr.de/docs/TraCI/Vehicle_Value_Retrieval.html

That's for python, right? Does C++ use the same functions?

**Comment by HuaweiAlgolux** [comment]
> I recommend to familiarize yourself with the following methods
> 
> * traci.vehicle.subscribeContext (https://sumo.dlr.de/docs/TraCI/Interfacing_TraCI_from_Python.html#context_subscriptions)
> * traci.vehicle.getLeader
> * traci.vehicle.getNextTLS
> * traci.vehicle.getFollowSpeed, traci.vehicle.getStopSpeed
> * traci.vehicle.setSpeed, traci.vehicle.slowDown
> 
> see
> https://sumo.dlr.de/pydoc/traci._vehicle.html#VehicleDomain (The method names are the same in C++ as in python)
> https://sumo.dlr.de/docs/TraCI/Change_Vehicle_State.html
> https://sumo.dlr.de/docs/TraCI/Vehicle_Value_Retrieval.html

Do I need to install libtraci separately?

**Comment by namdre** [comment]
It is part of the sumo installation. See https://sumo.dlr.de/docs/Libtraci.html
Libtraci is recommended for it's GUI capabilities. 
For additional speed, see https://sumo.dlr.de/docs/Libsumo.html

**Comment by HuaweiAlgolux** [comment]
First, thank you for the quick reply. I'm still very very confused about how to write a c++ program and use libtraci as a library in my CMakeList.txt for my c++ program? Can you give an example?
