### ISSUE TITLE
The difference between setSpeed and slowDown commands in Traci

### ISSUE THREAD

**Issue by MohamadReza-Haghani** [eclipse/sumo#9235]
Hi,

I was wondering to know more about the difference between setSpeed and slowDown commands in Traci. I noticed that they both set the speed. But slowDown command has a duration. Is it the only difference?

Regards,
Reza.

**Comment by namdre** [comment]
- setSpeed makes the vehicle adjust it's speed as fast as possible and keep the target speed indefinitely
- slowDown makes the vehicle change speed smoothly over the given time and it will resume normal driving afterwards
