### ISSUE TITLE
Can the following Vehicle in disallowd lane detour to another lane

### ISSUE THREAD

**Issue by allenzhuyi** [eclipse/sumo#9237]
If the edge has 2 straight lanes, one lanes set disallowed by traci  using set disallowed meothd, can the following vehicles in the 
disallowed lane detour to another straight lane ? How to  set the vehicle  detour stragetic ?

**Comment by namdre** [comment]
Vehicles only check for allow/disallow when entering a lane but will ignore it when the permissions change while they are on that lane. If you wish to make them leave you can trigger a lane change with `traci.vehicle.changeLane`.
Later vehicles should detour automatically at a distance determined by their `lcStrategic` vType attribute.
