### ISSUE TITLE
document how to install package from OBS

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#9238]
I.e. example commands for installing sumo_nightly on ubuntu. to be put on our downloads/nightly page.
Their own documentation at https://openbuildservice.org/help/manuals/obs-user-guide/art.obs.bg.html#sec.obsbg.uc.install-from-obs isn't may be hard to find and follow.

**Comment by behrisch** [comment]
There is no nightly build repo for ubuntu because of missing dependencies and unfortunately people do different things on different Linux flavors. But I can describe my (openSuse) workflow,
