### ISSUE TITLE
Has Sumo a method to block part of  the lane?

### ISSUE THREAD

**Issue by allenzhuyi** [eclipse/sumo#9239]
Traci has a setDisallowed method to disable vehicles in the whole lane, but  I want block part of the lane for 
road closure in construction area,   the closure area may be part of  the lane, not always  the whole lane. Is there a method or setting to block part of lane ?

**Comment by namdre** [comment]
The only way to block part of a lane is by placing one or more stopped vehicles with the required length in that area.
Note, that the vehicle must be in the 'stopped' state (vehicle.setStop) to trigger correct lane changing behavior by the other vehicles (setSpeed(vehID, 0) is insufficient).

**Comment by allenzhuyi** [comment]
Thanks, the effect way!
