### ISSUE TITLE
Git Cloning and Building Problem

### ISSUE THREAD

**Issue by toprakfirat** [eclipse/sumo#9240]
I downloaded the Latest Development Version of SUMO. I downloaded the file with the git.zip extension from [this](https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_development_version) link. After I try to build SUMO with the "cmake --build . --parallel $(sysctl -n hw.ncpu)" command, I get the following error:
  
`[  0%] Built target generate-version-h
[  0%] Built target foreign_phemlight
[  1%] Built target foreign_tcpip
[  2%] Built target mesogui
[  2%] Built target mesosim
[  3%] Built target microsim_actions
[  5%] Built target microsim_cfmodels
[  5%] Built target microsim_engine
[  6%] Built target microsim_lcmodels
[ 10%] Built target microsim
[ 13%] Built target microsim_devices
[ 15%] Built target microsim_transportables
[ 16%] Built target microsim_output
[ 16%] Built target microsim_trigger
[ 17%] Built target utils_distribution
[ 18%] Built target utils_emissions
[ 19%] Built target netload
[ 23%] Built target microsim_traffic_lights
[ 24%] Built target utils_common
[ 25%] Built target utils_geom
[ 26%] Built target utils_handlers
[ 26%] Built target utils_importio
[ 27%] Built target utils_iodevices
[ 27%] Built target utils_options
[ 28%] Built target utils_shapes
[ 29%] Built target utils_traction_wire
[ 29%] Built target utils_vehicle
[ 32%] Built target traciserver
[ 34%] Built target utils_xml
[ 35%] Built target utils_gui_globjects
[ 36%] Built target utils_foxtools
[ 36%] Built target utils_gui_images
[ 38%] Built target utils_gui_div
[ 38%] Built target utils_gui_cursors
[ 38%] Built target utils_gui_tracker
[ 38%] Built target utils_gui_settings
[ 39%] Built target utils_gui_shortcuts
[ 39%] Built target gui_dialogs
[ 40%] Built target gui
[ 41%] Built target utils_gui_windows
[ 42%] Built target guinetload
[ 42%] Built target foreign_eulerspiral
[ 43%] Built target netimport_vissim
[ 45%] Built target netimport
[ 49%] Built target netbuild
[ 51%] Built target guisim
[ 53%] Built target netimport_vissim_tempstructs
[ 54%] Built target netwrite
[ 54%] Built target od
[ 55%] Built target activitygen_activities
[ 56%] Built target router
[ 58%] Built target activitygen_city
[ 58%] Swig compile libsumo.i for python
[ 64%] Built target netimport_vissim_typeloader
Consolidate compiler generated dependencies of target libtracistatic
Scanning dependencies of target libtraci_swig_compilation
[ 67%] Built target libsumocpp
[ 67%] Swig compile libtraci.i for python
:3: Error: Unable to find 'python.swg'
/Users/toprak/Documents/SUMO/src/libsumo/libsumo_typemap.i:345: Error: Unable to find 'std_string.i'
/Users/toprak/Documents/SUMO/src/libsumo/libsumo_typemap.i:346: Error: Unable to find 'std_vector.i'
/Users/toprak/Documents/SUMO/src/libsumo/libsumo_typemap.i:347: Error: Unable to find 'std_map.i'
/Users/toprak/Documents/SUMO/src/libsumo/libsumo_typemap.i:354: Error: Unable to find 'std_pair.i'
make[2]: *** [src/libsumo/CMakeFiles/libsumo.dir/libsumoPYTHON.stamp] Error 1
make[2]: *** Deleting file `src/libsumo/CMakeFiles/libsumo.dir/libsumoPYTHON.stamp'
make[1]: *** [src/libsumo/CMakeFiles/libsumo_swig_compilation.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 67%] Building CXX object src/libtraci/CMakeFiles/libtracicpp.dir/Connection.cpp.o
[ 67%] Building CXX object src/libtraci/CMakeFiles/libtracicpp.dir/Edge.cpp.o
[ 69%] Built target libtracistatic
[ 69%] Building CXX object src/libtraci/CMakeFiles/libtracicpp.dir/GUI.cpp.o
:3: Error: Unable to find 'python.swg'
/Users/toprak/Documents/SUMO/src/libtraci/../libsumo/libsumo_typemap.i:345: Error: Unable to find 'std_string.i'
/Users/toprak/Documents/SUMO/src/libtraci/../libsumo/libsumo_typemap.i:346: Error: Unable to find 'std_vector.i'
/Users/toprak/Documents/SUMO/src/libtraci/../libsumo/libsumo_typemap.i:347: Error: Unable to find 'std_map.i'
/Users/toprak/Documents/SUMO/src/libtraci/../libsumo/libsumo_typemap.i:354: Error: Unable to find 'std_pair.i'
make[2]: *** [src/libtraci/CMakeFiles/libtraci.dir/libtraciPYTHON.stamp] Error 1
make[2]: *** Deleting file `src/libtraci/CMakeFiles/libtraci.dir/libtraciPYTHON.stamp'
make[1]: *** [src/libtraci/CMakeFiles/libtraci_swig_compilation.dir/all] Error 2
[ 69%] Building CXX object src/libtraci/CMakeFiles/libtracicpp.dir/InductionLoop.cpp.o
[ 69%] Building CXX object src/libtraci/CMakeFiles/libtracicpp.dir/Junction.cpp.o
[ 70%] Building CXX object src/libtraci/CMakeFiles/libtracicpp.dir/Lane.cpp.o
[ 70%] Building CXX object src/libtraci/CMakeFiles/libtracicpp.dir/LaneArea.cpp.o
[ 70%] Building CXX object src/libtraci/CMakeFiles/libtracicpp.dir/MultiEntryExit.cpp.o
[ 70%] Building CXX object src/libtraci/CMakeFiles/libtracicpp.dir/Person.cpp.o
[ 70%] Building CXX object src/libtraci/CMakeFiles/libtracicpp.dir/POI.cpp.o
[ 70%] Building CXX object src/libtraci/CMakeFiles/libtracicpp.dir/Polygon.cpp.o
[ 70%] Building CXX object src/libtraci/CMakeFiles/libtracicpp.dir/Route.cpp.o
[ 70%] Building CXX object src/libtraci/CMakeFiles/libtracicpp.dir/Calibrator.cpp.o
[ 70%] Building CXX object src/libtraci/CMakeFiles/libtracicpp.dir/BusStop.cpp.o
[ 71%] Building CXX object src/libtraci/CMakeFiles/libtracicpp.dir/ParkingArea.cpp.o
[ 71%] Building CXX object src/libtraci/CMakeFiles/libtracicpp.dir/ChargingStation.cpp.o
[ 71%] Building CXX object src/libtraci/CMakeFiles/libtracicpp.dir/RouteProbe.cpp.o
[ 71%] Building CXX object src/libtraci/CMakeFiles/libtracicpp.dir/Rerouter.cpp.o
[ 71%] Building CXX object src/libtraci/CMakeFiles/libtracicpp.dir/VariableSpeedSign.cpp.o
[ 71%] Building CXX object src/libtraci/CMakeFiles/libtracicpp.dir/MeanData.cpp.o
[ 71%] Building CXX object src/libtraci/CMakeFiles/libtracicpp.dir/OverheadWire.cpp.o
[ 71%] Building CXX object src/libtraci/CMakeFiles/libtracicpp.dir/Simulation.cpp.o
[ 71%] Building CXX object src/libtraci/CMakeFiles/libtracicpp.dir/TrafficLight.cpp.o
[ 71%] Building CXX object src/libtraci/CMakeFiles/libtracicpp.dir/Vehicle.cpp.o
[ 72%] Building CXX object src/libtraci/CMakeFiles/libtracicpp.dir/VehicleType.cpp.o
[ 72%] Linking CXX shared library ../../../../bin/libtracicpp.dylib
[ 72%] Built target libtracicpp
make: *** [all] Error 2
`
After I run the same command a couple of times, I get the following error:

`[  0%] Built target generate-version-h
[  1%] Built target foreign_tcpip
[  1%] Built target foreign_phemlight
[  2%] Built target mesogui
[  2%] Built target mesosim
[  3%] Built target microsim_actions
[  3%] Built target microsim_engine
[  5%] Built target microsim_cfmodels
[  6%] Built target microsim_lcmodels
[ 10%] Built target microsim
[ 13%] Built target microsim_devices
[ 15%] Built target microsim_output
[ 16%] Built target microsim_transportables
[ 16%] Built target microsim_trigger
[ 17%] Built target utils_distribution
[ 21%] Built target microsim_traffic_lights
[ 22%] Built target netload
[ 23%] Built target utils_emissions
[ 24%] Built target utils_common
[ 25%] Built target utils_geom
[ 26%] Built target utils_handlers
[ 26%] Built target utils_importio
[ 27%] Built target utils_iodevices
[ 27%] Built target utils_options
[ 30%] Built target traciserver
[ 31%] Built target utils_shapes
[ 32%] Built target utils_traction_wire
[ 32%] Built target utils_vehicle
[ 34%] Built target utils_xml
[ 35%] Built target utils_foxtools
[ 36%] Built target utils_gui_globjects
[ 36%] Built target utils_gui_images
[ 38%] Built target utils_gui_div
[ 38%] Built target utils_gui_settings
[ 38%] Built target utils_gui_cursors
[ 38%] Built target utils_gui_tracker
[ 39%] Built target utils_gui_shortcuts
[ 40%] Built target utils_gui_windows
[ 40%] Built target gui_dialogs
[ 41%] Built target guinetload
[ 42%] Built target gui
[ 42%] Built target foreign_eulerspiral
[ 43%] Built target netimport_vissim
[ 45%] Built target netimport
[ 47%] Built target guisim
[ 51%] Built target netbuild
[ 53%] Built target netimport_vissim_tempstructs
[ 54%] Built target netwrite
[ 54%] Built target od
[ 55%] Built target router
[ 56%] Built target activitygen_activities
[ 58%] Built target activitygen_city
[ 58%] Swig compile libsumo.i for python
[ 64%] Built target netimport_vissim_typeloader
[ 64%] Swig compile libtraci.i for python
[ 66%] Built target libtracistatic
:3: Error: Unable to find 'python.swg'
/Users/toprak/Documents/SUMO/src/libsumo/libsumo_typemap.i:345: Error: Unable to find 'std_string.i'
/Users/toprak/Documents/SUMO/src/libsumo/libsumo_typemap.i:346: Error: Unable to find 'std_vector.i'
/Users/toprak/Documents/SUMO/src/libsumo/libsumo_typemap.i:347: Error: Unable to find 'std_map.i'
/Users/toprak/Documents/SUMO/src/libsumo/libsumo_typemap.i:354: Error: Unable to find 'std_pair.i'
[ 69%] Built target libsumocpp
make[2]: *** [src/libsumo/CMakeFiles/libsumo.dir/libsumoPYTHON.stamp] Error 1
make[2]: *** Deleting file `src/libsumo/CMakeFiles/libsumo.dir/libsumoPYTHON.stamp'
make[1]: *** [src/libsumo/CMakeFiles/libsumo_swig_compilation.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
:3: Error: Unable to find 'python.swg'
/Users/toprak/Documents/SUMO/src/libtraci/../libsumo/libsumo_typemap.i:345: Error: Unable to find 'std_string.i'
/Users/toprak/Documents/SUMO/src/libtraci/../libsumo/libsumo_typemap.i:346: Error: Unable to find 'std_vector.i'
/Users/toprak/Documents/SUMO/src/libtraci/../libsumo/libsumo_typemap.i:347: Error: Unable to find 'std_map.i'
/Users/toprak/Documents/SUMO/src/libtraci/../libsumo/libsumo_typemap.i:354: Error: Unable to find 'std_pair.i'
[ 70%] Built target marouter
[ 73%] Built target libtracicpp
make[2]: *** [src/libtraci/CMakeFiles/libtraci.dir/libtraciPYTHON.stamp] Error 1
make[2]: *** Deleting file `src/libtraci/CMakeFiles/libtraci.dir/libtraciPYTHON.stamp'
make[1]: *** [src/libtraci/CMakeFiles/libtraci_swig_compilation.dir/all] Error 2
make: *** [all] Error 2
[  0%] Built target generate-version-h
[  1%] Built target foreign_tcpip
[  1%] Built target foreign_phemlight
[  2%] Built target mesogui
[  2%] Built target mesosim
[  3%] Built target microsim_actions
[  3%] Built target microsim_engine
[  5%] Built target microsim_cfmodels
[  6%] Built target microsim_lcmodels
[ 10%] Built target microsim
[ 13%] Built target microsim_devices
[ 15%] Built target microsim_output
[ 16%] Built target microsim_transportables
[ 16%] Built target microsim_trigger
[ 17%] Built target utils_distribution
[ 21%] Built target microsim_traffic_lights
[ 22%] Built target netload
[ 23%] Built target utils_emissions
[ 24%] Built target utils_common
[ 25%] Built target utils_geom
[ 26%] Built target utils_handlers
[ 26%] Built target utils_importio
[ 27%] Built target utils_iodevices
[ 27%] Built target utils_options
[ 30%] Built target traciserver
[ 31%] Built target utils_shapes
[ 32%] Built target utils_traction_wire
[ 32%] Built target utils_vehicle
[ 34%] Built target utils_xml
[ 35%] Built target utils_foxtools
[ 36%] Built target utils_gui_globjects
[ 36%] Built target utils_gui_images
[ 38%] Built target utils_gui_div
[ 38%] Built target utils_gui_settings
[ 38%] Built target utils_gui_cursors
[ 38%] Built target utils_gui_tracker
[ 39%] Built target utils_gui_shortcuts
[ 40%] Built target utils_gui_windows
[ 40%] Built target gui_dialogs
[ 41%] Built target guinetload
[ 42%] Built target gui
[ 42%] Built target foreign_eulerspiral
[ 43%] Built target netimport_vissim
[ 45%] Built target netimport
[ 47%] Built target guisim
[ 51%] Built target netbuild
[ 53%] Built target netimport_vissim_tempstructs
[ 54%] Built target netwrite
[ 54%] Built target od
[ 55%] Built target router
[ 56%] Built target activitygen_activities
[ 58%] Built target activitygen_city
[ 58%] Swig compile libsumo.i for python
[ 64%] Built target netimport_vissim_typeloader
[ 64%] Swig compile libtraci.i for python
[ 66%] Built target libtracistatic
:3: Error: Unable to find 'python.swg'
/Users/toprak/Documents/SUMO/src/libsumo/libsumo_typemap.i:345: Error: Unable to find 'std_string.i'
/Users/toprak/Documents/SUMO/src/libsumo/libsumo_typemap.i:346: Error: Unable to find 'std_vector.i'
/Users/toprak/Documents/SUMO/src/libsumo/libsumo_typemap.i:347: Error: Unable to find 'std_map.i'
/Users/toprak/Documents/SUMO/src/libsumo/libsumo_typemap.i:354: Error: Unable to find 'std_pair.i'
[ 69%] Built target libsumocpp
make[2]: *** [src/libsumo/CMakeFiles/libsumo.dir/libsumoPYTHON.stamp] Error 1
make[2]: *** Deleting file `src/libsumo/CMakeFiles/libsumo.dir/libsumoPYTHON.stamp'
make[1]: *** [src/libsumo/CMakeFiles/libsumo_swig_compilation.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
:3: Error: Unable to find 'python.swg'
/Users/toprak/Documents/SUMO/src/libtraci/../libsumo/libsumo_typemap.i:345: Error: Unable to find 'std_string.i'
/Users/toprak/Documents/SUMO/src/libtraci/../libsumo/libsumo_typemap.i:346: Error: Unable to find 'std_vector.i'
/Users/toprak/Documents/SUMO/src/libtraci/../libsumo/libsumo_typemap.i:347: Error: Unable to find 'std_map.i'
/Users/toprak/Documents/SUMO/src/libtraci/../libsumo/libsumo_typemap.i:354: Error: Unable to find 'std_pair.i'
[ 70%] Built target marouter
[ 73%] Built target libtracicpp
make[2]: *** [src/libtraci/CMakeFiles/libtraci.dir/libtraciPYTHON.stamp] Error 1
make[2]: *** Deleting file `src/libtraci/CMakeFiles/libtraci.dir/libtraciPYTHON.stamp'
make[1]: *** [src/libtraci/CMakeFiles/libtraci_swig_compilation.dir/all] Error 2
make: *** [all] Error 2
`

What am I doing wrong? How can I fix this? Thanks a lot.

---
*If possible, upload an example that shows your problem.*

**SUMO-version: v1_10_0+0989-abc956bdb3a**

**operating system: Mac Big Sur**

**Comment by behrisch** [comment]
There seems to be a problem with your swig installation. Can you report the swig version and how you installed it?

**Comment by toprakfirat** [comment]
> Have you tried installing via homebrew? See: https://sumo.dlr.de/docs/Installing/MacOS_Build.html

Homebrew installation works but I need to install a recently updated build.

> There seems to be a problem with your swig installation. Can you report the swig version and how you installed it?

I probably installed it using homebrew, the version is:

SWIG Version 4.0.2
Compiled with clang++ [x86_64-apple-darwin20.1.0]
Configured options: +pcre

**Comment by toprakfirat** [comment]
After reinstalling swig and cmake, the build was done without any errors, however commands such as "sumo" or "netconvert" are not working on the terminal. Do I have to do something manually in order to make them work or is there a problem?

**Comment by toprakfirat** [comment]
After reinstalling swig and cmake, the build was done without any errors. Everything works fine now!
