### ISSUE TITLE
Can SUMO simulate bad weather scenario?

### ISSUE THREAD

**Issue by thinker310** [eclipse/sumo#9241]
Hello everyone, one question I want to ask is how to build bad weather scenario such as raining in SUMO? I saw a paper that simulated the bad sceanrio by SUMO, but I do not find any useful information in the SUMO documentation. The picture below is the description on the setting of bad weather scenario in the paper.
![image](https://user-images.githubusercontent.com/62609436/134802462-b37271ef-15fe-4845-bfc2-f58d788187e5.png)
![image](https://user-images.githubusercontent.com/62609436/134802487-a9afe57c-b466-42d7-9a88-e2095bda33c4.png)
Could you help me please? Thank you in advance!

**Comment by namdre** [comment]
There are no weather settings in SUMO however, you can tune the model parameters (i.e. vehicle deceleration or preferred headway) according to the expected changes in vehicle and driver behavior.
