### ISSUE TITLE
drtOnline.py with "personTrip" 

### ISSUE THREAD

**Issue by ArmelliniMG** [eclipse/sumo#9251]
When a person request is defined with "personTrip" , e.g.:

  <person id="p0" depart="54000">
    <personTrip from="154188894#1" to="181193407" modes="taxi"/>
  </person>

The person will sometimes just walk and no request to the taxi device will be made. I was just wondering, how is this decided.

See Person "p0" in the test scenario:
[test_szenario.zip](https://github.com/eclipse/sumo/files/7238628/test_szenario.zip)

**Comment by namdre** [comment]
The intermodal routing query applies the value of **--persontrip.taxi.waiting-time** (default 300) to the travel time of using a taxi and walks if that would be faster.
