### ISSUE TITLE
About how to use routesampler.py

### ISSUE THREAD

**Issue by parksanha** [eclipse/sumo#9253]
Hello~

I have counts and other information (such as speed, queues, etc.) of each intersection and road in the city I'm investigating.

And this data is collected every 15 minutes.

My question is below. I have two questions.

1. If I input multiple time intervals in routesampler.py, does the result come out correctly?
I wrote the example code below.
ex)
![image](https://user-images.githubusercontent.com/62294108/135005008-65a475d3-26e6-4cf8-965a-d0d14d7b203c.png)

2. If edgedata is also used, is it possible to use information other than count in routesampler.py?
ex)
![image](https://user-images.githubusercontent.com/62294108/135005037-1ef4c42f-429f-42bd-b8fd-7a8b32cced65.png)

**Comment by namdre** [comment]
1) routeSampler assumes stationary traffic within one interval. Routes will be selected to fulfill the counts within each interval (ignoring travel times that could make vehicles show up in multiple intervals) and you will get departures spread out over time to match each interval. (for a planned extension see #7427).

2). Yes. You can set the used attribute with option **--edgedata-attribute**

**Comment by parksanha** [comment]
@namdre Thank you very much for your reply.

If I want to use it with other information
Can I enter the following?

![image](https://user-images.githubusercontent.com/62294108/135181222-ba755106-2720-4c9a-ad73-b29c6539189c.png)

then
python routeSampler.py -r possible_routes.xml --turn-files turn_counts.xml --edgedata-files edge_counts.xml --edgedata-attribute "left traveltime" -o out.xml

**Comment by namdre** [comment]
You can only use a single edgedata attribute ('left' makes sense since it is also a count of the vehicles that passed that edge).
