### ISSUE TITLE
 Cannot load traffic light program for unknown id

### ISSUE THREAD

**Issue by zhaotuo0815** [eclipse/sumo#9265]
hello, sumo developer ,i want to defind a traffic light logic in the sumo.net.file,  the traffic light logic like

```
<tlLogic id="cluster_1520714035_1520714037_2019988555_2019988556_6561193320_6561193324" type="static" programID="0" offset="0">
	<phase duration="21" state="GGGGGGGGGGGGrrrrrrrrrrrr"/>
	<phase duration="3" state="yyyyyyyyyyyyrrrrrrrrrrrr"/>
	<phase duration="21" state="rrrrrrrrrrrrGGGGGGGGGGGG"/>
	<phase duration="3" state="rrrrrrrrrrrryyyyyyyyyyyy"/>
</tlLogic>
```

and i use the command “netconvert -n test.net.xml -i tllogi4Phase.xml -o nanjing_test.net.xml  --ignore-errors.edge-type”, which return "Cannot load traffic light program for unknown id 'cluster_1520714035_1520714037_2019988555_2019988556_6561193320_6561193324', programID '0'." Am I missing sothing? Thank you for your help.

**Comment by namdre** [comment]
this means there is no tlLogic named `cluster_1520714035_1520714037_2019988555_2019988556_6561193320_6561193324`  in net.net.xml

**Comment by namdre** [comment]
Note, that you can also use netedit to load another program using the 'load' button in 'traffic light mode'.

**Comment by zhaotuo0815** [comment]
> Note, that you can also use netedit to load another program using the 'load' button in 'traffic light mode'.

If there are a large number of nodes, I can't manually add them one by one. My idea is to select the nodes that I need to become traffic light, write them into tllogic with python script, and then generate them in batch with netconvert

**Comment by zhaotuo0815** [comment]
> this means there is no tlLogic named `cluster_1520714035_1520714037_2019988555_2019988556_6561193320_6561193324` in net.net.xml

i create the traffic light for the node "cluster_1520714035_1520714037_2019988555_2019988556_6561193320_6561193324" in netedit, and then  use the command “netconvert -n test.net.xml -i tllogi4Phase.xml -o nanjing_test.net.xml --ignore-errors.edge-type”, which return Invalid linkIndex 24 for traffic light 'cluster_1520714035_1520714037_2019988555_2019988556_6561193320_6561193324' with 24 links. But the linkIndex generated by default is 24

**Comment by namdre** [comment]
If the traffic light has 24 links, then their indices are numbered 0,...,23.  Thus your custom program has to many link states. You can also edit the program directly in netedit to avoid these problems.

**Comment by zhaotuo0815** [comment]
> If the traffic light has 24 links, then their indices are numbered 0,...,23. Thus your custom program has to many link states. You can also edit the program directly in netedit to avoid these problems.

Can't you configure traffic light for nodes in batch? Can I only add it manually with Netedit?

**Comment by namdre** [comment]
You sure can. See https://sumo.dlr.de/docs/Tutorials/ScenarioGuide.html#example_patching_the_type_of_a_node

But you should only try to generated custom programs after you've understood how their link indices are to be interpreted. I recommend starting with abstract 4-arm intersections rather than complex OSM junction clusters for this.

**Comment by zhaotuo0815** [comment]
> If the traffic light has 24 links, then their indices are numbered 0,...,23. Thus your custom program has to many link states. You can also edit the program directly in netedit to avoid these problems.

by the way , my custom program link states is 24 links......
<tlLogic id="cluster_1520714035_1520714037_2019988555_2019988556_6561193320_6561193324" type="static" programID="0" offset="0">
	<phase duration="21" state="GGGGGGGGGGGGrrrrrrrrrrrr"/>
	<phase duration="3" state="yyyyyyyyyyyyrrrrrrrrrrrr"/>
	<phase duration="21" state="rrrrrrrrrrrrGGGGGGGGGGGG"/>
	<phase duration="3" state="rrrrrrrrrrrryyyyyyyyyyyy"/>
</tlLogic>

**Comment by zhaotuo0815** [comment]
> You sure can. See https://sumo.dlr.de/docs/Tutorials/ScenarioGuide.html#example_patching_the_type_of_a_node
> 
> But you should only try to generated custom programs after you've understood how their link indices are to be interpreted. I recommend starting with abstract 4-arm intersections rather than complex OSM junction clusters for this.

yes, i do know !i use sumolib netData.getNode(nodeid).getConnections() to get the connections of the nodeid, and use the netData.getNode(nodeid).getIncoming() to get the incomelane, I put them in the dict like"{'138674429#3': [12, 13, 14, 15, 16, 17, 18], '549385015#1': [0, 1, 2, 3, 4, 5, 6], '776677986#2': [7, 8, 9, 10, 11], '833765967#2': [19, 20, 21, 22, 23]} " in the end

**Comment by namdre** [comment]
> > If the traffic light has 24 links, then their indices are numbered 0,...,23. Thus your custom program has to many link states. You can also edit the program directly in netedit to avoid these problems.
> 
> by the way , my custom program link states is 24 links......

My mistake. The error message must be read the other way around: The network defines connections that reference link index 24 so the original program had at least 25 states.
