### ISSUE TITLE
netedit silently changes junction type

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#9273]
Steps to reproduce
- create a new network with a single edge
- change to inspect mode
- split the edge
- change the junction type to "rail crossing"
- save the net
- now inspect the junction again and it has type "priority"

I agree that "rail crossing" does not make much sense here but the user should be notified somehow or rail crossing should be forbidden right from the start.

**Comment by namdre** [comment]
it's actually netconvert that does this in NBNodeTypeComputer::validateRailCrossings (maybe we can just add a warning?)

**Comment by behrisch** [comment]
A warning would be fine but immediate feedback would be better

**Comment by namdre** [comment]
We could run the validateRailCrossingCheck when setting a new junction type in inspect mode and mark the value as 'invalid'
