### ISSUE TITLE
improve "allow" dialog for rails

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#9276]
- [x] add an "allow only rail" button similar to road vehicles
- [x] improve the images ("rail_electric" and "rail_fast" look like a tram while "tram" does not)

**Comment by namdre** [comment]
I don't think there are many places where tram and rail run on the same tracks. Also, the other rail modes carry semantics (electrified vs not-electrified). What is the use case of allowing all rail modes?

**Comment by behrisch** [comment]
You are right for the tram but the use case for the others is that I simply don't know in advance which train will use the tracks.

**Comment by namdre** [comment]
SVC_RAIL and SVC_RAIL_URBAN should be enough for most use cases.
