### ISSUE TITLE
Obtaining initial routes for routeSampler.py

### ISSUE THREAD

**Issue by parksanha** [eclipse/sumo#9282]
I created sampleRoutes.rou.xml by referring to the scrip in the link below.
https://sumo.dlr.de/docs/Tools/Turns.html#obtaining_initial_routes
![image](https://user-images.githubusercontent.com/62294108/135572806-443a7f91-5f45-4706-a9d5-ccc9d97fc874.png)

When routesampler.py selects routes in <sampleRoutes.rou.xml>,
is it affected by departure time of vehicle in  sampleRoutes.rou.xml and multiple intervals in turn-files(or edge-files)?

**Comment by namdre** [comment]
The departure time in sampleRoutes.rou.xml is ignored. Actually, the whole vehicle is ignored and only the `<route>` elements are read.  The intervals in turn-/edge-files will of course be used to create time-varying traffic patterns.

To use a different set of *candidate* routes for different time intervals you must call routeSampler multiple times (once for each interval with the corresponding routes).

**Comment by parksanha** [comment]
@namdre thank you so much.
