### ISSUE TITLE
move experimental libraries into a different branch

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#9292]
may help in clone time in github actions and also give a better overview of what is really needed

**Comment by palvarezlopez** [comment]
Fixed https://github.com/DLR-TS/SUMOLibraries/tree/experimental

**Comment by behrisch** [comment]
The idea was to have the new library in the branch instead of the old library so that you can simply switch branches to let the build pick up the new one. @palvarezlopez Do you think this could work? Also we could move the things which are currently unused like freetype and *malloc into experimental.

**Comment by palvarezlopez** [comment]
@behrisch yes, I can move malloc, but not freetype, because this last is linked in CMakeList

**Comment by palvarezlopez** [comment]
Fixed
