### ISSUE TITLE
how to receive the value from 'Phase' object

### ISSUE THREAD

**Issue by zhaotuo0815** [eclipse/sumo#9295]
hi, sumo developer, my question is that how to receive the value from 'Phase' object, like("Phase(duration=26.0, state='rrrrrrrrrrrrrrrrrGGGGGG', minDur=26.0, maxDur=26.0, next=())"), and i search the attribute of  'Phase' object from https://sumo.dlr.de/pydoc/traci._trafficlight.html#Logicthe , which have no attribute. thank you for your help!

**Comment by namdre** [comment]
https://github.com/eclipse/sumo/blob/0aa9fe10362326e1a167f5a3fc9a2e9681c23dda/tools/traci/_trafficlight.py#L23-L32
