### ISSUE TITLE
netconvert crash on NDS scenario

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#9299]
Just use attached netccfg instead of template_gen0.netccfg in https://github.com/DLR-TS/sumo-scenarios/tree/master/TestfeldNDS. It works if I set `<keep-edges.by-vclass value="passenger,bus,tram"/>`
[bug.netccfg.txt](https://github.com/eclipse/sumo/files/7278073/bug.netccfg.txt)

**Comment by namdre** [comment]
bug.netccfg runs fine when tested on Linux and Windows.

**Comment by namdre** [comment]
just tried this with a freshly built netconvert on windows and it works.

**Comment by namdre** [comment]
finally caught the crash with windows-debug-build and linux clang-debug-build

**Comment by namdre** [comment]
was caused by loading a node patch that creates a custom joined tls with the same id as the junction together with **--tls.join** where the joining heuristic than tries to join that tls with something else.
