### ISSUE TITLE
OSM Web Wizard SSL Verification Error

### ISSUE THREAD

**Issue by Mikroni998** [eclipse/sumo#9304]
<img width="959" alt="Capture" src="https://user-images.githubusercontent.com/91965719/136043286-232f23b6-c43b-43f2-aca2-6f48f385aa07.PNG">

**Comment by namdre** [comment]
The certificate was renewed last week after the old one expired. It works on my end. Possibly there is an outdated certificate version cached on your machine or an intermediate machine within you network.

**Comment by Mikroni998** [comment]
Thank you for the quick answer!

**Comment by namdre** [comment]
Did you manage to get it working?

**Comment by namdre** [comment]
try https://my.justhost.com/cgi/help/clear-local-ssl

**Comment by Mikroni998** [comment]
No, it doesn't work. I guess I have to import it somehow?

**Comment by namdre** [comment]
@behrisch any ideas?

**Comment by behrisch** [comment]
`pip install certifi`? We should maybe add this to the FAQ or to the WebWizard docs

**Comment by Mikroni998** [comment]
I deleted it and restarted my PC. Still the same.

**Comment by behrisch** [comment]
Can you do a small python script and run
```
import certifi
print(certifi.where())
```

**Comment by 123Lucpat** [comment]
Hello, I am having exactly the same problem with osmWizzard. Was found already a solution for it?

**Comment by Mikroni998** [comment]
> > ![image](https://user-images.githubusercontent.com/91965719/136849352-9750eecf-022c-47e6-85c8-c4b6d3cc019e.png) Now shows this.
> 
> Hello, you need to "import ssl" at the beginning of the file

**Comment by devanshee38** [comment]
hello, I am facing the same issue right now, despite following all the measures mentioned above and using the latest version of Sumo, reinstalling certificate, reinstalling python etc. Could you please help me out? It is rather urgent!
![image](https://user-images.githubusercontent.com/86478053/162575581-d8b2213e-d170-4ca1-9b38-ac7dedc13a96.png)

**Comment by Gupta-Kanak** [comment]
> hello, I am facing the same issue right now, despite following all the measures mentioned above and using the latest version of Sumo, reinstalling certificate, reinstalling python etc. Could you please help me out? It is rather urgent! ![image](https://user-images.githubusercontent.com/86478053/162575581-d8b2213e-d170-4ca1-9b38-ac7dedc13a96.png)

Hello.
I am facing the same issue, were you able to resolve it?
