### ISSUE TITLE
Problem with setAllowed command in Traci

### ISSUE THREAD

**Issue by MohamadReza-Haghani** [eclipse/sumo#9305]
Hi,

I used setAllowed command in Traci to change the allowance in some lanes. After the command is performed,  a barrier is made between the left lanes of edge 'E1_1' and edge 'E1_2'. Vehicles cannot move from 'E1_1_2' to 'E1_2_2'. I was wondering what is the reason. Please find attached SUMO files.

Regards,
Reza.
  
[ezyzip.zip](https://github.com/eclipse/sumo/files/7289771/ezyzip.zip)
---

**SUMO-version:** 1.10.0

**operating system:** Windows

**Comment by namdre** [comment]
A solid line between lanes indicates that the lanes do not have a single common vClass permissions. Hence no vehicle can change there.

**Comment by namdre** [comment]
Changing permissions cannot create new connections. You have to define a connection from the disallowed lane E1_1_2 to lane E1_2_2 in the original network.

**Comment by Jinbo0201** [comment]
> Changing permissions cannot create new connections. You have to define a connection from the disallowed lane E1_1_2 to lane E1_2_2 in the original network.

How to define connection by using traci.

**Comment by behrisch** [comment]
You cannot change the network using traci. You have to modify it in netedit or with XML input. @Jinbo0201 And please do not post questions in vaguely related old tickets. Just open a new one
