### ISSUE TITLE
About joining nodes

### ISSUE THREAD

**Issue by parksanha** [eclipse/sumo#9306]
Hello.

I'm using sumo to simulate traffic for an entire city.

I have created a network as shown in the picture below, but there are some problems and I am solving it.

![image](https://user-images.githubusercontent.com/62294108/136128585-dd5df954-1406-4317-949e-8339991b00b0.png)

What I want to ask you is:

Roads will not display normally if there are nodes located close to each other. I tried to create a network by referring to joining nodes in the document, but it doesn't work well.
Nodes marked in blue are not merged.
I've also tried --junctions.join-dist but it doesn't work well.

![image](https://user-images.githubusercontent.com/62294108/136129161-12362712-bd58-4940-9ef8-cd67fc48aa2b.png)

ex : netconvert --sumo-net-file exp.net.xml --output-file joined_juctions.net.xml --junctions.join
https://sumo.dlr.de/docs/Networks/PlainXML.html#joining_nodes

Is there any way to merge the nodes marked in blue?
Any help in this regard would be appreciated.

**Comment by namdre** [comment]
for each of the indicate pairs, the option **--geometry.remove** should be able to remove one of  them (assuming there is no change in speed limit or street name).

**Comment by parksanha** [comment]
Thank you. I'll try.

One more ques.

In the case of nodes that are close to each other, there are cases where the junction covers the edges and thus does not become a normal road. Is there a way to solve this?
![image](https://user-images.githubusercontent.com/62294108/136155488-7c51cf99-2520-48a3-a184-ff955cf68113.png)
