### ISSUE TITLE
delayed insertion

### ISSUE THREAD

**Issue by hassanidoudi** [eclipse/sumo#9308]
is the insertion of vehicles in a delayed way is prioritizing vehicles with less departure time ?

**Comment by namdre** [comment]
Yes. Vehicle insertion should keep the same insertion order regardless of delay.

**Comment by behrisch** [comment]
... unless the vehicles have different properties (such as length) and `--eager-insert` is specified

**Comment by hassanidoudi** [comment]
loaded vehicles with less departure time than newly inserted in the simulation will be prioritized?
