### ISSUE TITLE
A Question about "net.node.getOutgoing( )"

### ISSUE THREAD

**Issue by Jinchauuuuu** [eclipse/sumo#9325]
When I use net.getNode(Node).getOutgoing() to get edges, I find that it cannot return the information of all the edges that can lead to，for example:
![image](https://user-images.githubusercontent.com/44915146/136651886-ca6d238d-50ce-4322-8b1c-cb73c6a54809.png)
![image](https://user-images.githubusercontent.com/44915146/136651894-97420b84-272f-4335-90a9-37e4aa05a148.png)
![image](https://user-images.githubusercontent.com/44915146/136651914-a8d42f23-36f9-4aa0-9772-204793eeb6c3.png)
![image](https://user-images.githubusercontent.com/44915146/136651931-0326a18a-ebaa-4771-bac5-c1f8f4e17c11.png)

Why does this happen?

**Comment by behrisch** [comment]
Can you attach your network xml file (possibly in a zip)?
