### ISSUE TITLE
traci from multiple device makes the Sumo simulation very slow

### ISSUE THREAD

**Issue by mahbub-iut** [eclipse/sumo#9326]
I'm running a simulation where multiple TracI client from multiple devices are interacting with Sumo Simulation and periodically sets a custom device value and call the Simulationstep() at the end. Each of the client receives SPaT messages over http periodically, processes it  and sets customly created device values attached to each vehicles and calls Simulation step command. However, clients get blocked by Sumo and doesn't have the control to receive and process the http packet if http packets come very frequently. So, maintaining the 10Hz requirement is not being possible.  Ideally there will be as many traci client as the number of vehicles running in simulation as they will individually process the SPaT message and take decision based on that while approaching an intersection. I know I'm overwhelming Sumo with lots of things.

 However, if I run all the tracI client in same same device there is no issue. The issue arises only when I try to connect multiple tracI client from multiple devices. Is there any way to speed up the process so that client is not blocked for long by Sumo. What's the limiting factor here ?  I'm running Sumo in a relatively powerful machine with Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz Processor, 32 GB DDR4 RAM and 16GB of GPU. If I run Sumo in a more powerful machine will that help?

**Comment by mahbub-iut** [comment]
@namdre @behrisch  any insight on this will be really helpful

**Comment by namdre** [comment]
the simulator only continues stepping after all clients have sent the simulationStep command. This definitely doesn't scale well if you have lots of vehicles and a small step-length.

**Comment by behrisch** [comment]
Seems to be answered. Feel free to reopen if you have new insights.
