### ISSUE TITLE
jtrrouter does not warn about unsorted flows

### ISSUE THREAD

**Issue by tszking** [eclipse/sumo#9327]
I try to generate rou.xml file with a repeated flow file and a turn file.

The flow file is something like:

![image](https://user-images.githubusercontent.com/33691832/136766774-05fcd417-5a19-4fb8-ae72-2171305f571a.png)

and the turn file is something like: 

![image](https://user-images.githubusercontent.com/33691832/136766986-5eec47ca-81e9-4224-8264-25895baf2e3b.png)

and the command is: 

jtrrouter -t exp.turn.xml -n meilin.net.xml -r exp.flow.xml -o test.rou.xml --departlane random  --accept-all-destinations

The problem i met is that in the generated rou.xml file, in the first 2800 seconds, only vehicles from the first edge in the flow.xml (785866813#3) are generated, demands from other edges start to appear after that. 

I wonder is this a bug or if I have done something wrong, thank you.

![image](https://user-images.githubusercontent.com/33691832/136769318-d1ae8f84-a93a-4480-9092-7f3297808a38.png)

SUMO-version: 1.10.0
Operating system: Ubuntu 18.04

The mentioned files have been attached: 
[sumo_files.zip](https://github.com/eclipse/sumo/files/7334255/sumo_files.zip)

**Comment by namdre** [comment]
@lbieker  There was a misunderstanding: The warning should be given if the input is not sorted by departure time which reminds the user to set option **--unsorted-input** (the option ensures that unsorted input is handled correclty but costs extra memory).

In your patch, the warning is triggered whenever the user sets this option.
