### ISSUE TITLE
 instead of clicking _“Start Tracking”_

### ISSUE THREAD

**Issue by Jinchauuuuu** [eclipse/sumo#9337]
When I'm running SUMO-GUI simulation, I want the window to track a car in real time, so I click _“Start Tracking”_ , I wonder if I can set some commands with sumocfg or other files instead of clicking _“Start Tracking”_ every time?

**Comment by behrisch** [comment]
It is currently not possible to do this from the sumo-gui but if you are using traci you can issue traci.gui.trackVehicle. Does this solve your problem?

**Comment by Jinchauuuuu** [comment]
Yes, this solved my problem, thanks a lot!
