### ISSUE TITLE
SSL Certificate Verification Error

### ISSUE THREAD

**Issue by ZhiKhang** [eclipse/sumo#9347]
Hi guys, I am new to python and also sumo. I just installed the sumo yesterday. When I try to generate scenario by using the OSM Web Wizard , it appears error as shown below. Anyone knows the solution for it ?
  
---
*If possible, upload an example that shows your problem.*

**SUMO-version:**
sumo 1.10.0
**operating system:*
Python 3.10

![Error](https://user-images.githubusercontent.com/92697033/137648833-e773cdb9-776d-4ef1-ad0a-964f69188071.JPG)
*

**Comment by behrisch** [comment]
It seems to be this problem: https://stackoverflow.com/questions/52074590/urllib-request-urlopen-ssl-certificate-verify-failed-error-on-windows-vista. Can you try the solution http://woshub.com/updating-trusted-root-certificates-in-windows-10/ ?

**Comment by monasabeti** [comment]
@ ZhiKhang 
could you please explain for mr by detail your solution about SSL Certificate Verification Error
"Michael, my friend help me to solve this problem by installing a certificate. Change the .txt into .cer , then run it. And the problem solved~"

which type off certificate do you install?
and which file of .txt do you change to cer?

**Comment by behrisch** [comment]
The comment above has a txt file attached. I think, if you download it and rename it with the extension .cer you might be able to install it. I did not try this and do not recommend installing certificates downloaded from an unknown source. Did you try installing certifi instead? It should solve the problems at least with the latest sumo version.

**Comment by monasabeti** [comment]
@behrisch 
i download the certificate from an unknown source and install. and also try your solution install certifi but yet i have gotten the same problem

**Comment by monasabeti** [comment]
and i install it with this command "pip install certifi"
Requirement already satisfied: certifi in c:\users\mona_\appdata\local\programs\python\python310\lib\site-packages (2021.10.8)
but when i want to generate the scenario by osmwebwizard i didnt see the result in sumo
and the error is:"ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)"
