### ISSUE TITLE
delete elements with "del" key in inspect mode

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#9352]
I would expect to be able to delete a POI (and probably each other element as well) from its context menu and/or by pressing the "Del" key. Maybe we can even avoid having a delete mode at all.

**Comment by behrisch** [comment]
I totally agree. It is rather for the newbie / first contact / casual user but I also don't think it would hurt to have it. And pressing Del is even more intuitive than 'd'

**Comment by palvarezlopez** [comment]
Use dinamic_cast for retrieve elements

**Comment by palvarezlopez** [comment]
Fixed
