### ISSUE TITLE
POI positions

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#9353]
- [x] A geo poi shows lon and lat only with 2 decimals
- ~[ ] a regular poi has only one attribute position where I would expect separate x and y (similar to geo poi)~

**Comment by namdre** [comment]
having 'pos' as a single attribute makes it easier to copy/paste positions. This is the reason why pos was introduced as a virtual attribute for junctions.
for lon,lat there is always a problem of user expectations on the ordering (i.e. lat-lon used by google maps) so it's less useful to have a single attr.
