### ISSUE TITLE
 Performance Issue - Calling Sumo APi is a big bottlneck  and Multithread crashes... is there a way to parallize or reduce overhead ?

### ISSUE THREAD

**Issue by meltawk** [eclipse/sumo#9426]
We are running a scenario handeling arround 2000 vehicles and almot 100 crossing pedestrian in every step. but the overhead is  so high.

  we have three maps containing  as  following:  

**- Persons to be added**
- Person::add(wCivilianId, wEdge, libsumo::DEPARTFLAG_NOW);
- Person::appendWalkingStage(wCivilianId, { wEdge.edgeID }, wEdge.pos - 0.01, -1.0, 0.01);

**- Persons to be updated** 
- libsumo::TraCIPosition wCaPos = Simulation::convertGeo(iLong, iLat, true);
- Person::moveToXY(wCivilianId, "", wCaPos.x, wCaPos.y, libsumo::INVALID_DOUBLE_VALUE, 4, 100.0);
- Person::setSpeed(wCivilianId, 0.0);

**- Persons to be removed** 
- while (1 < Person::getRemainingStages(iPersonID))
  {
	Person::removeStage(iPersonID, 1);
}
Person::removeStage(iPersonID, 0);

**- Additionall APis for vehicle are called after the simulation::step() is executed:**
- Vehicle::getIDCount();
- Vehicle::getIDList();
- Vehicle::getSpeed(iVehID);
- libsumo::TraCIPosition wTraciPosition = Vehicle::getPosition(iVehID, iIncludeZ);
- libsumo::TraCIPosition wLon_lat = Simulation::convertGeo(wTraciPosition.x, wTraciPosition.y);
---
Those 3 maps are independents

**What do you advice to increase the overhead :**

- API  areThread Safe so we can parallelize the calling. if yes how.
- Multi clients are created so each client can  mange one of those 3 maps  indepedenly and in paralle. if yes how
- Disable the connection client/server of Traci and use the API directly. if yes how 
- decrease the map size of the scenario and the vehicule count .

*If possible, upload an example that shows your problem.*

**SUMO-version:**
Eclipse SUMO sumo Version 1.10.0
**operating system:**
Linux c++

**Comment by behrisch** [comment]
You should first try libsumo. A small example is here: https://sumo.dlr.de/docs/Libsumo.html#c

If it does not solve it please describe your expectations and measurements concerning performance in more detail.

Please also open a separate issue on how and when multithreading crashes

**Comment by meltawk** [comment]
I was trying to parallelize through Thread_Pool of boost with 2 thread the following Sumo APi:
- Person::add(wCivilianId, wEdge, libsumo::DEPARTFLAG_NOW);
- libsumo::TraCIPosition wCaPos = Simulation::convertGeo(iLong, iLat, true);
- Person::moveToXY(wCivilianId, "", wCaPos.x, wCaPos.y, libsumo::INVALID_DOUBLE_VALUE, 4, 100.0);
- Person::setSpeed(wCivilianId, 0.0);
N.B: we ensure that thread are completely independent and every thread has a set of person ids.
result: #Error: received status response to command: 0 but expected: 171
An issue will be created.

**Comment by behrisch** [comment]
But you did not use two separate connections here? Then it must fail because the two threads will write concurrently to the same socket.

**Comment by meltawk** [comment]
I see. So you mean by two different connections  can be  same host different traciport ? How we handle two different connection in sumo and how static Sumo api is assocaited to a connection.? thank you if you can refere an example.

your help is appreciated

**Comment by behrisch** [comment]
You still use the same port you just connect with two different clients. Some details are here: https://sumo.dlr.de/docs/TraCI.html#multiple_clients. But please be warned that this will not reduce the communication overhead because communication will still be serialized (there is only one thread on the receiving sumo side). If you want to do this to improve performance this will only work if your threads do heavy calculations without communicating to sumo.

**Comment by behrisch** [comment]
Please reopen if problems persist.
