### ISSUE TITLE
How to cancel out the changeLane command?

### ISSUE THREAD

**Issue by MohamadReza-Haghani** [eclipse/sumo#9427]
Hi,

In my simulation, when commanding a vehicle to move to a specific lane using changeLane command in Traci, the vehicle sometimes get stuck, cannot complete the lane change and stop between two lanes. I was wondering to know how I can cancel out the command so the vehicle continues moving. Does a changeLane(vehID, current laneID) command cancel out the previous command?

Regards,
Reza.
  
---
*If possible, upload an example that shows your problem.*

**SUMO-version: 1.10.0**

**operating system: Windows 10**

**Comment by namdre** [comment]
Yes. A new changeLane command cancels out the previous command.
