### ISSUE TITLE
randomTrips.py problem with big scale imported networks.

### ISSUE THREAD

**Issue by Oritchimaru** [eclipse/sumo#9437]
Hello everybody!

I'm currently working on a project where I handle the learning of agents based on big imported sumo networks.
I'm using sumo/tools/**randomTrips.py** with a high fringe factor to generate random .trips.xml files in order to train
the model. My question has nothing to do with machine learning, my problem is explicitly on randomTrips.py.

I want to be able to consistently and automated to be able to produce random trips for my network (without explicitly defining the weights of the edges). The trips generated will need to start from a cropped incoming lane and end to a cropped outcoming lane. (by same cropped lanes I mean the lanes that got cropped by the OSM Wizard when importing the net)

So the problem is that **even with a really high fringe factor I have generated trips who spawn vehicles inside random junctions of the network**. Mostly it works fine but even some wrong spawns in thousands of trips will ruin the learning. I don't know if I misuse the function or if I can do something about that but I would appreciate any kind of help or intuition from someone more experienced than me!

Below is an example command like the one I used for random trips:
`
python3 /home/sumo/tools/randomTrips.py -n osm.net.xml -b 0 -e 1800 -p 4 --trip-attributes="departLane=\"best\" departSpeed=\"10.0\" departPos=\"base\"" --route-file trips.xml --fringe-factor 20000`

Here is a sample network that fulfills the minimum criteria of size (road number etc.)

![athens](https://user-images.githubusercontent.com/26443186/139646675-2b3ebd10-ebcc-4f09-9fd7-f6000bd644a6.png)

and this one is an example of where I want the vehicles to spawn and terminate. (at the start/end of these lanes. Also I don't mind internal final or starting lanes from parkings etc. I just have problem with the junction spawns.)

![athensExample](https://user-images.githubusercontent.com/26443186/139646669-181a21ba-273b-491f-9fd1-5b2a42619e16.png)

Sumo version:
    **SUMO 1.4.0**

OS:
    **Ubuntu 20.04.2 LTS**

Thanks for your time!

T.M.T

**Comment by namdre** [comment]
randomTrips allows writing the origin/destination probabilities for each edge using option **-weights-output-prefix**. 
Please check whether the undesired starting edge is selected despite having a probability of 0 or close to 0.

**Comment by namdre** [comment]
The issue was resolved via #9948
