### ISSUE TITLE
Xodr to .net using netconver

### ISSUE THREAD

**Issue by FadiTela** [eclipse/sumo#9445]
Used the netconverter in sumo to convert xodr to .net but I'm missing crossroads and some roads aren't converted properly. Is this a bug in the converter or I'm not using the tool correctly? 
  
---
Xodr file in Carla:
![image](https://user-images.githubusercontent.com/92377293/139720928-7b8acab2-e704-46aa-884a-253a053dfc21.png)

.net file in the netedit program:
![image](https://user-images.githubusercontent.com/92377293/139720967-b49db507-de9d-4bba-ba5b-5414616c5f79.png)

here is my output from the code I run in command prompt:
![image](https://user-images.githubusercontent.com/92377293/139721642-c54a6b45-277b-4585-8752-29dd27124d81.png)

**SUMO-1.9.2:**

**Windows 10 Pro**

**Comment by namdre** [comment]
- to import the sidewalks, load a custom edge type file using option `--type-files %sumo_home%\data\typemap\opendriveNetconvert.typ.xml,%sumo_home%\data\typemap\opendriveNetconvertPedestrians.typ.xml`
- crossroads are not imported from OpenDRIVE yet. When you are importing sidewalks, also set option **--crossings.guess** to build them automatically
- sections with variable lane width may need some manual fixing. See #9045
