### ISSUE TITLE
Install_dll only install the Release dlls

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#9446]

**Comment by palvarezlopez** [comment]
FilterDebugDLL can be removed

**Comment by behrisch** [comment]
I just retried here and the old version works well with internal and external cmake. Can you give details on what you tried?

**Comment by palvarezlopez** [comment]
@behrisch I generate a MSVC19 Solution with CMake-GUI, execute SUMO.sln, select "Debug" build, execute install_dll but only install the Release Libraries
