### ISSUE TITLE
try modelling complex junction with contPos for straight connection

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#9452]
single-junction for tostmanplatz

**Comment by behrisch** [comment]
multiple stops on a single junction are now possible

**Comment by namdre** [comment]
stopping at two traffic lights (at the entrance and then within the intersection) works for straight and right-turns. However, merging two vehicle streams that stop at the "same" location on different internal edges doesn't work.
The common part "within an intersection" must still be modeled as a normal road.
