### ISSUE TITLE
 expected speed value in the car-following model

### ISSUE THREAD

**Issue by emotion68** [eclipse/sumo#9460]
Which parameter is used to set the expected speed value in the car-following model?
 setSpeed?
 What is the expected speed in the default IDM and ACC car-following models?

**Comment by namdre** [comment]
what do you mean be "expected speed"? Who is expecting the speed of whom?

**Comment by emotion68** [comment]
For example, the V0 value in the IDM car-following mode, the expected speed value of the vehicle

**Comment by namdre** [comment]
See https://sumo.dlr.de/docs/Simulation/VehicleSpeed.html
