### ISSUE TITLE
rou file exported by jtrrouter program, traffic flow steering error

### ISSUE THREAD

**Issue by wyh1050225768** [eclipse/sumo#9471]
Add your issue description here.
  When using jtrrouter, the exported Rou file does not change lanes according to the probability of the self edited turn file
---
*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**

**Comment by namdre** [comment]
Please clarify:
- are you actually concerned about lane-changing? (lane changes are not encoded in a route file, instead the lane changing model decides on suitable lane changes at simulation time)
- are you concerned about turn probabilities? If the input probabilities do not match the output probabilities, this could be either a bug or a mis-configuration. Please attach a minimum input example for reproducing your problem (zip all xml input files for jtrrouter and attach them to this ticket).

**Comment by namdre** [comment]
closing due to lack of feedback
