### ISSUE TITLE
how to use the car-following model which created  by myself

### ISSUE THREAD

**Issue by Hjp-momojiji** [eclipse/sumo#9475]
I new a car-following model such as https://sumo.dlr.de/docs/Developer/How_To/Car-Following_Model.html
But I can't use the new cf-modle. Maybe the os.environ['SUMO_HOME'] still use the Default environment? 
For example, I even modify the IDM source code in src\microsim\cfmodels，but the simulation still not change.
So, how to use the src model rather than Default environment(dll).
Maybe other problem cause the Above situation, hope someone can answer the following questions,thanks.
---
![1636013718(1)](https://user-images.githubusercontent.com/63853587/140279858-6186b45a-4a09-4f9e-abf9-4aeeace17e93.png)
![1636013741(1)](https://user-images.githubusercontent.com/63853587/140279865-82afe966-bae1-4a32-a07b-6c3c4f7af7d3.png)
![ba9b0d70bd83ab35a94589c6a9a07a6](https://user-images.githubusercontent.com/63853587/140279868-e33d9c16-f18b-4c46-936f-5e065273a8b5.png)

**SUMO-version:**1.10.0

**Comment by namdre** [comment]
Have you rebuilt sumo from the modified source files as explained here: https://sumo.dlr.de/docs/Installing/Windows_Build.html ?

**Comment by Hjp-momojiji** [comment]
> Have you rebuilt sumo from the modified source files as explained here: https://sumo.dlr.de/docs/Installing/Windows_Build.html ?

Didn't rebuilt yet.
So,I have to rebuilt sumo if I want to modify or new a cf-model?

**Comment by namdre** [comment]
If you wish to make changes to the C++ code, you have to rebuild. Alternatively, you could attach your own model via process coupling (i.e. from a python script): https://sumo.dlr.de/docs/TraCI.html

**Comment by Hjp-momojiji** [comment]
> If you wish to make changes to the C++ code, you have to rebuild. Alternatively, you could attach your own model via process coupling (i.e. from a python script): https://sumo.dlr.de/docs/TraCI.html

thanks a lot.
