### ISSUE TITLE
The meaning of "amBF," "BL," and "amBBS" terms in the result of "getLaneChangeStatePretty" command in Traci

### ISSUE THREAD

**Issue by MohamadReza-Haghani** [eclipse/sumo#9484]
Hi,

I was wondering to know the meaning of "amBF," "BL," and "amBBS" terms that I get in the result of "getLaneChangeStatePretty" command in Traci.

Best,
Reza.
  
---
*If possible, upload an example that shows your problem.*

**SUMO-version: 1.10.0**

**operating system: Windows 10**

**Comment by namdre** [comment]
- amBL: ego is blocking somebodies lanechange as direct leader vehicle
- amBF: ego is blocking somebodies lanechange as a direct follower vehicle
- amBB: ego is potentially blocking someones lanechange downstream
- amBBS: ego is potentially blocking someones lanechange downstream (and the blocked vehicle is standing)
