### ISSUE TITLE
Mistake in documentation of "vehicle2flow.py"

### ISSUE THREAD

**Issue by gtilg** [eclipse/sumo#9486]
The example for the tool "vehicle2flow.py" refers to "tracegenerator.py":

`python tools/route/tracegenerator.py <route-file> -o <output-route-file> -e <end-time> -r <repeat-period>`

It should probably be:

`python tools/route/vehicles2flow.py <route-file> -o <output-route-file> -e <end-time> -r <repeat-period>`

See: [https://sumo.dlr.de/docs/Tools/Routes.html#vehicle2flowpy](https://sumo.dlr.de/docs/Tools/Routes.html#vehicle2flowpy)

Thanks!

**Comment by namdre** [comment]
Thanks!
