### ISSUE TITLE
make tables look nicer in Documentation

### ISSUE THREAD

**Issue by angelobanse** [eclipse/sumo#9499]
Use line breaks only on columns such as descriptions

Maybe even adapt the ToC sidebar

**Comment by namdre** [comment]
it already looks nicer. But now it seems that all columns have equal width (i.e. https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#stops)

I think it would look even better if tables still tried to fit their content width and only some columns have to accept lower width and line breaks. For most tables the rule could be: fit column with for columns [1, n-1],  give remaining width to column n.

**Comment by angelobanse** [comment]
@namdre reopen if needed.

See https://sumo.dlr.de/docs/sumo.html#driver_state_device

**Comment by namdre** [comment]
:grinning:
