### ISSUE TITLE
cannot create embedded route with three consecutive edges

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#9508]
Steps to reproduce

- Open an arbitrary network
- switch to demand mode / create vehicles
- select flow with embedded route or vehicle with embedded route
- click three consecutive edges and press enter to finish route creation
- try to save the demand
- error message complains about a duplicate edge

**Comment by namdre** [comment]
was working in 1.10.0

**Comment by namdre** [comment]
I can still reproduce this with the new version (i.e. on tests/sumo/net2.net.xml by clicking SC, CE, EC).
this creates the route "SC CE CE EC". Saving throws up the "fix error" dialog.

**Comment by behrisch** [comment]
@palvarezlopez Can you still fix this for 1.11?

**Comment by palvarezlopez** [comment]
@behrisch I try it

**Comment by namdre** [comment]
now works for me also.
