### ISSUE TITLE
split up sumo/extra tests

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#9510]
10k test results on a single webpage are too much (i.e. if just want to find out when a red meso test was last seen green).
Maybe we can somehow split the 'SUMO' line in the 'extra_gcc4_64'-table into 'SUMO-meso, etc.

On a more radical note: The main test page might be more useful if variants of the main suite generally had their own summary line and result pages.

**Comment by behrisch** [comment]
So you propose we should handle every version just like a separate application and have separate entries in the overview table and separate pages behind the link?

**Comment by namdre** [comment]
Yes. I think it would make the linked result pages more useful.

**Comment by behrisch** [comment]
I opened up this one: https://github.com/texttest/texttest/issues/94

**Comment by behrisch** [comment]
has been resolved in texttest
