### ISSUE TITLE
Default value for route color must be empty

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#9512]
Embedded routes take the color of vehicle or vehicle type. Normal routes take color "yellow" if no custom color was defined

**Comment by palvarezlopez** [comment]
@behrisch this is a problem?

**Comment by namdre** [comment]
Not a big problem but it's a superfluous attribute if the user did not set any color. 
Also it may interfere with vType and vehicle color in the default color mode (where it is checked which one of those three colors is defined).

**Comment by behrisch** [comment]
Exactly. Furthermore I would not like to encourage people to set a color in an embedded route. The encapsulating vehicle / flow is the better place.

**Comment by namdre** [comment]
Trying to define a flow crashes with
`Error: Trying to get undefined string attribute 'color' in SUMOBaseObject 'route'`
