### ISSUE TITLE
Person Types Mode is currently empty

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#9513]
Should be disabled (grey) or even removed until fully implemented. Isn't it somehow redundant to the vehicle type anyway?

**Comment by namdre** [comment]
re:redudancy: yes. Though it might make it easier for people to use the recommended vClasses for persons and vehicles.

**Comment by behrisch** [comment]
@palvarezlopez  would be great if you could just disable the code for this release

**Comment by palvarezlopez** [comment]
@behrisch ok, I do it

**Comment by namdre** [comment]
Discussed solution (for 1.12)
- remove persontype frame
- rename title of the vehicle type frame to 'Types'
- add a button "create person type" (which sets vClass to pedestrian)
- warn when assigning a type with unsuitable vClass to a vehicle or person
