### ISSUE TITLE
duarouter + weights.random-factor + CH or dijkstra

### ISSUE THREAD

**Issue by ambuehll** [eclipse/sumo#9515]
Hello,

duarouter with trip file as input results in _identical_ routes when using CH (or CHwrapper for multimodal) with different weights.random-factor (1 vs 100).
duarouter with trip file as input results in reasonably different routes when using dijkstra with different weights.random-factor (1 vs 100).

 Thanks!

Lukas 
---
as always: [files](https://drive.google.com/drive/folders/1U9cIJXsgGHWQ3mPQgARwvN6lZsYWCI3I?usp=sharing)
`duarouter -n LON.net.xml -t tripsrandtest.rou.xml -o randomtest11d.rou.xml --routing-threads 20 --weights.random-factor 1 --ignore-errors true --seed 10
`

result files directly uploaded, d for dijkstra, w for CHwrapper

SUMO-version: latest dev yesterday

operating system: Windows

**Comment by namdre** [comment]
The pre-processed routing graph created by CHRouter isn't compatible with **weights.random-factor**.  There isn't much we can do besides issuing a warning.

**Comment by namdre** [comment]
It would be possible to use the randomized weights when creating the preprocessed graph. All vehicles with the same origin/destination would use the same route (which wouldn't happen for Dijsktra) but at least you could run duarouter with different random seeds and the results would change (This is how the combination of *weights.random-factor** and **CH / CHWrapper** works in sumo)

This might be more useful than no effect at all but there should still be a warning.

**Comment by ambuehll** [comment]
Thanks. Makes sense - still, I like the second option.
