### ISSUE TITLE
The lateral offset can be set to any value in sumo?

### ISSUE THREAD

**Issue by MABENSHAN** [eclipse/sumo#9516]
When I want to control ego vehicle by traci.vehicle.moveToXY, I found that the y coordinate is not continuous, instead, the y coordinate can only be set to be the centerline's value of the lane.
      If vehicle' y coordinate can be set any value in SUMO？If it's available, how?

the code  is:
trac.vehicel.moveToXY("3","","-1",100, 6.2,angle=90.0)

SUMO-version is 1.10.0

operating system is ubantu 20.04

**Comment by namdre** [comment]
to use arbitrary lateral positions, either activate the sublane model or set keepRoute=2

See https://sumo.dlr.de/docs/TraCI/Change_Vehicle_State.html#move_to_xy_0xb4
