### ISSUE TITLE
psv osm import backward and forwar

### ISSUE THREAD

**Issue by ambuehll** [eclipse/sumo#9519]
Hi, 

An enhancement related to #6767 and #8317

`lanes:psv:backward` (or forward) does not get imported.
Would be great to import this as well. 

Thanks
Lukas

**Comment by namdre** [comment]
This looks like a duplicate of #6767 or am I missing something?

**Comment by ambuehll** [comment]
Back then it was about implementing psv which #8317 took care this year - partially.
What's missing is the forward/backward implementation from #6767. 
But, I guess you're right, it's a bit of a duplicate. Sorry 👍

**Comment by namdre** [comment]
no problem. Serves as a reminder that #6767 is still relevant!
