### ISSUE TITLE
grow selection by parent or child elements

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#9524]
add two new buttons in selection Frame:
- add child elements
- add parent elements

Example use cases
- select a list of additional objects -> add their lanes to the current selection
- select edges -> add their lanes to the selection
- select edges -> add their junctions to the selection
- select lanes -> add all additional objects on these lanes to the selection

**Comment by behrisch** [comment]
Can we document somewhere what the exact meaning of "parent" and "child" is in the netedit context? It is quite clear in the context of edge and lane but is a junction a "child" of an edge or the other way round? Or should we rather speak more abstract about relations here just as OSM does?

**Comment by namdre** [comment]
Generally speaking, a child can not exist without it's parent. So edges are the children of junctions.
