### ISSUE TITLE
demand is always considered modified

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#9529]
Directly after loading a demand file the save button is highlighted and I am asked whether I want to save the file on closing netedit even if I did no modification.

**Comment by palvarezlopez** [comment]
@behrisch this was implemented on purpose, because we can load additional/route/data from multiple files and save in the same file.

@namdre what do you think?

**Comment by behrisch** [comment]
I am not sure whether I understand it correctly. Is there a way for the user to decide whether the loaded routes, vTypes etc. should be saved to a route or an additional file?

**Comment by namdre** [comment]
I think that after loading a file, the "save" button should only activate after doing some changes. Loading a second demand file also counts as a change. Loading an additional file with busStops does not. 

@behrisch Demand stuff always gets saved to a route file (except for routes that are referenced by rerouters/calibrators).
