### ISSUE TITLE
Import crossings and sidewalks when converting .osm file to .net.xml file (netconvert)

### ISSUE THREAD

**Issue by LockDownPT** [eclipse/sumo#9544]
Hello there. 

My question is if it is possible to import crossings and sidewalks from an osm file with the netconvert command?
So far I have been trying several command options and there seems to be none for that specific purpose.
The only ones that I found that create crossings/sidewalks are  --crossings.guess or --sidewalks.guess but has the name suggests this only guesses them.

There was an entry in one of SUMO's tutorials that mentioned an option named --osm.sidewalks but this option is not available in the netconvert command anymore.
https://sumo.dlr.de/docs/Networks/Import/OpenStreetMap.html#importing_sidewalks

**operating system:**
windows 10

**Comment by namdre** [comment]
> but this option is not available in the netconvert command anymore.

Not quite. The option is brand new and only available in the latest development version: https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_development_version (soon to be release as 1.11.0)

Importing crossings from OSM is not yet supported (#1750)
