### ISSUE TITLE
vTypeDistribution for more than 2 types?

### ISSUE THREAD

**Issue by hanwiz** [eclipse/sumo#9564]
I tried to use the vTypeDistribution with three types: cars, vans, and trucks. However, the resulting distribution ignores other probabilities except for the first two probabilities, and it produces distributions like 0.5, 0.4, and 1.0. So the number of trucks is dominant, unlike the supposed probability of 0.5, 0.4, and 0.1. 

Is there a different way to achieve this, or can this be fixed?

```
<routes>
    <vTypeDistribution id="typedist1">
        <vType id="cars" accel="0.8" length="5" maxSpeed="70" probability="0.5"/>
        <vType id="vans" accel="1.2" length="8" maxSpeed="60" probability="0.4"/>
        <vType id="trucks" accel="1.8" length="15" maxSpeed="50" probability="0.1"/>
    </vTypeDistribution>
</routes>
```
  
---
**SUMO-version:** 1.8.0 and 1.10.0

**operating system:** Windows

**Comment by namdre** [comment]
When I use your distribution to generated 10.000 vehicles in sumo, this is what I get. 
- 5063 cars
- 3969 vans
- 968 trucks

Similar results when using the vTypeDistribution with duarouter.
Maybe your sample size is too low?
You could also try to run with a different random seed (option **--seed**)
