### ISSUE TITLE
inconsist default "depart" defintion in traci and libsumo when adding a vehicle

### ISSUE THREAD

**Issue by yunpangfloetteroed** [eclipse/sumo#9573]
Add your issue description here.
The default value for "depart" in traci.vehicle.add() is none, which is not available in libsumo.vehicle.add(). When using "import libsumo as traci" and running the existing traci function the repsective error occurs. It would be nice to have a consist default defintion.

---
*If possible, upload an example that shows your problem.*

**SUMO-version:**
v1_10_0+2369-be805626ae7
**operating system:**
Ubuntu 20.04.3 LTS

**Comment by namdre** [comment]
default it python should be changed to "now".

**Comment by yunpangfloetteroed** [comment]
I suppose that depart=None in traci.vehicle.add() also means now, i.e. the current simulation step. or? If it is the case, would it be better to change depart=None also to "now" in traci.vehicle.add() for consistency?
