### ISSUE TITLE
netedit does not route pedestrians correctly

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#9584]
Having a network without explicit pedestrian infrastructure (only peds allowed on the street) like the attached [bs5.net.xml.zip](https://github.com/eclipse/sumo/files/7562629/bs5.net.xml.zip). Steps to reproduce

- Load the net
- Demand Mode -> create persons
- Person plans, walks, walk: edge->edge
- select a starting edge like 33049407#0
- select an end edge like 5724307

netedit tells me about a path of 10 edges while sumo will need only three.

**Comment by namdre** [comment]
duplicate of #8564
