### ISSUE TITLE
creating a second person fails

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#9585]
This may be a documentation issue only but it was not clear to me how to end the creation of a person (plan) and start a new one.

- If I start a second walk after creating the first one I get an error: There is another person with the same ID='person_0'.
- There is no button "finish plan". 

If person creation is not usable yet, we should maybe disable it for the release.

**Comment by namdre** [comment]
It's a regression. The person-id counter doesn't advance anymore. Was working in 1.10.0

**Comment by namdre** [comment]
Person creation is supposed to be usable though some things appear untested (#9568) and there are other regressions (#9587).
Disabling this is not an option in my opinion. I'd rather delay the release to get the regressions out.

**Comment by namdre** [comment]
@behrisch  If you need a quick workaround, for creating multiple persons, set the 'id' checkbox and enter a custom id

**Comment by namdre** [comment]
On usability expectations: We only have tests for person mode and none for person plan mode. Nevertheless I expect to be able to have a release with full functionality and will do some manual testing for person plan mode.
