### ISSUE TITLE
documentation license needed

### ISSUE THREAD

**Issue by robbiemorrison** [eclipse/sumo#9589]
I think you need a LICENSE.txt file somewhere in your documentation tree to cover the documentation.  Possibly here:

- `sumo/docs/web/LICENSE.txt`

And probably under Creative Commons CC‑BY‑4.0, but that is a choice, of course, for the project team.

Please disregard this issue if there is indeed a license and I somehow managed to miss it.&nbsp;R

**Comment by namdre** [comment]
we have this: https://sumo.dlr.de/docs/Libraries_Licenses.html#data_and_documentation

which is a slight contradiction to our main license which covers "documentation source" as well
https://github.com/eclipse/sumo/blob/c739fe6499eba4122d10e9a9e4cd387377dca57b/LICENSE#L55

**Comment by behrisch** [comment]
The whole SUMO project including documentation and data files is covered by the same EPLv2 license (unless mentioned otherwise). I have now made that clear by updating the file mentioned above.

**Comment by robbiemorrison** [comment]
That clarity is useful.  But the [EPL‑2.0](https://en.wikipedia.org/wiki/Eclipse_Public_License) (to use its SPDX identifier) is designed for code and is not generally regarded as suitable for data or content.  A better choice for these later items would be CC‑BY‑4.0, particularly in the case of data.  Happy to discuss if that would help and to provide supporting resources too.

**Comment by behrisch** [comment]
First of all, the usual disclaimer: I am not a lawyer. We know that the EPL2 is primarily a code license. But it is too much of a hassle to always distinguish between code, documentation and data. If we choose a different documentation license what is about code examples on the pages? And do we have a different license for the tutorial files and for the tutorial pages even if they cite verbatim code?

If I understand it correctly, the Eclipse Foundation itself does it the same way. The legal document here https://www.eclipse.org/legal/termsofuse.php refers to https://www.eclipse.org/legal/epl/notice.php which essentially says all code and docs are EPL2 unless otherwise noticed.

Nonetheless, if you have a specific use case for our documentation which is not covered by the EPL2 please give a description here or open a new ticket and we will try our very best to solve it.

**Comment by robbiemorrison** [comment]
I note your concerns and these are not trivial by any means.  I also push the Free Software Foundation Europe (FSFE) to look beyond code too, but with little noticeable effect so far.

To respond specifically, code snippets do not attract copyright and therefore the question of licensing does not apply.  But the threshold for which copyright attaches is not clear and the widely debated "ten lines of code" rule‑of‑thumb has never been subject to case law.  A better approach, I believe, is simply to write in the documentation that the content and data are under CC‑BY‑4.0 and any code is under EPL‑2.0.

I cannot comment on Eclipse Foundation practice, I have not looked into their usage.

There is nothing more I can contribute.  Good luck with your project!  It sounds very necessary.

**Comment by namdre** [comment]
Your comment seems to imply that our current licensing practice runs afoul of some legal danger (*Good luck, it sounds necessary*). Can you be so kind as to give a reference for the kind of danger we are in?

**Comment by robbiemorrison** [comment]
I would imagine — and admittedly without full knowledge of your project and its use cases — that there is some theoretical legal risk to the SUMO project under the current arrangements.   But the principle issue is potentially lost opportunity in the context of data reuse.

At some point, the question of jurisdiction becomes material.  And the location of the server determines the legal jurisdiction in relation to the served material.  So I take it that the Eclipse Foundation servers are located in the United States, but that some of the project development takes place within the European Union.

The most likely legal risk to the SUMO project is, therefore, that your users from Europe transfer datasets either unlicensed or under CC‑BY‑4.0 to the SUMO project and the project reissues these datasets under EPL‑2.0.  I qualified my earlier comment with "theoretical" because the chances of any resulting litigation is vanishingly small.  The worst that will happen is that some legal department contacts your project and asks you to refrain from publishing (and this does happen).

Datasets in Europe are potentially protected as intellectual property — most commonly under [database rights](https://en.wikipedia.org/wiki/Database_Directive).  Conversely, datasets originating in the United States are, according to the US Copyright Office, highly unlikely to be deemed intellectual property.  That may explain why the Eclipse Foundation is comfortable in specifying EPL‑2.0 for data on its servers — because that license (or any other open license for that matter) does not bind in the absence of intellectual property rights.  That is a fundamental principle of IPR law.

The CC‑BY‑4.0 license is one of very few open licenses that traverses so‑called 96/9/EC database protection.  Hence the widespread recommendation for it use on data, datasets, and databases.

I want to return to the question of lost opportunity — because that is the most detrimental issue in my view.  Researchers often work for risk‑averse institutions and, in many cases, any ambiguity concerning the legal status of the material being used results in a freeze on publishing at least (I can cite examples but not on a public issues board).

Apologies for the long answer.  And I haven't provided a reference, as requested, because these kinds of data questions (unlike code) have not been subject to much academic scrutiny. But am happy to back up any individual claims made with substantial sources.

**Comment by behrisch** [comment]
Short answer: the Eclipse Foundation is currently a European entity (Belgian to be precise) and the need to check only one license should make it easier for risk averse people. No offense, but I trust the Eclipse legal people here. While this is not an explicit recommendation they even list the EPL v2 as "first" possible documentation license: https://www.eclipse.org/legal/noncodelicenses.php

**Comment by robbiemorrison** [comment]
The key question is still the location of the servers for the material in question — being GitHub if I am not mistaken?  And I note that the Eclipse Foundation transitioned to "EU‑based governance" in January 2021 but the legal advice cited earlier is dated 6&nbsp;December 2017.  Regarding interpretation and status, I&nbsp;think data is very different from content.  And that data reuse is significantly more important than documentation reuse (although this particular issue was prompted by the legal status of the documentation).  But I have said enough.  Good luck again with your project!

**Comment by namdre** [comment]
Thank you for the thoughtful and detailed response.

**Comment by robbiemorrison** [comment]
Noted.

**Comment by robbiemorrison** [comment]
I am not intending to reactivate an expired discussion.  But the following post to my [openmod community](https://en.wikipedia.org/wiki/Open_Energy_Modelling_Initiative) on open data licensing might be of interest.  The posting is in the context of an upcoming [EU Open Source Policy Summit](https://summit.openforumeurope.org/) on 4&nbsp;February 2022.  Scroll down to the "elephants section" to view my comments.

- https://groups.google.com/g/openmod-initiative/c/U1VX900bMSo/m/0nG8eD-ZBQAJ
