### ISSUE TITLE
user reports outdated sumo 1.9.0 on brew.sh

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#9594]
can another mac user confirm this?
we should make sure that 1.11.0 gets uploaded correctly.

**Comment by namdre** [comment]
@angelobanse @schwamborn can one of you please check?

**Comment by angelobanse** [comment]
i just tested:
```
brew tap dlr-ts/sumo
brew install sumo
```
and got SUMO 1.10.0

**Comment by namdre** [comment]
Thanks!
