### ISSUE TITLE
How to mark two edges as front elements at the same time?

### ISSUE THREAD

**Issue by MohamadReza-Haghani** [eclipse/sumo#9604]
Hi,

I have four edges which overlap with each other. I need to mark the edges which are under as front elements and edit their connections. The problem is that they do not stand as front elements at the same time. I used "mark as the front element" to put the first edge in front. Then, when I used the same command to put the second edge in front, the first edge went under. I was wondering how I can have them as front elements at the same time.
  
Best,
Reza.
---
*If possible, upload an example that shows your problem.*

**SUMO-version: 1.10.0**

**operating system: Windows 10**

**Comment by namdre** [comment]
For this you will need to use a different approach. 
1. select both of the edges that you would like to connect
  - in selection mode
  - or via locate-dialog + select
 2. use the gui settings dialog and color edges "by selection"
 3. set the color of unselected edges to transparent (alpha=0)
 4. create the desired connection (invisible edges will not register clicks)

The latest development version (soon to be 1.11.0) also supports a slightly faster approach
1. select everything *except* the two edges that wish to connect (i.e. with the help over 'invert selection')
2. using the new 'Lock' menu function 'Lock selected elements'
3. create the desired connection (locked objects will not register clicks)
