### ISSUE TITLE
trip generation based on the Markov chain

### ISSUE THREAD

**Issue by amiradavoudi** [eclipse/sumo#9608]
Hello,
I have a question about trip generation based on the Markov chain. I mean that ​I want to define a transition matrix where the probability of transitions from a source node to a destination node is given. Based on this matrix, I want to generate trips in SUMO. For example, A vehicle with a probability of 80% goes from home (lane a) to work (lane b), and then after work with probability 30% goes shopping (lane c), and finally with probability 90% returns home.
​I am wondering if you have any module or code that I can benefit from regarding this scenario?
​Do you think implementing this scenario by myself is straightforward in SUMO?
Thank you in advance for your help and attention.

**Comment by behrisch** [comment]
[randomTrips.py](https://sumo.dlr.de/docs/Tools/Trip.html) allows to define probabilities for an edge being the source, an intermediate waypoint or the destination. This would give a very basic model for only one intermediate location but you could use the code as a starting point. It should not be too hard and you can always contribute intermediate versions and ask for a review with a pull request here. You could also use [random_activitygen](https://github.com/d610f20/random-activitygen-py) or [SAGA](https://github.com/lcodeca/SUMOActivityGen).

**Comment by amiradavoudi** [comment]
> [randomTrips.py](https://sumo.dlr.de/docs/Tools/Trip.html) allows to define probabilities for an edge being the source, an intermediate waypoint or the destination. This would give a very basic model for only one intermediate location but you could use the code as a starting point. It should not be too hard and you can always contribute intermediate versions and ask for a review with a pull request here. You could also use [random_activitygen](https://github.com/d610f20/random-activitygen-py) or [SAGA](https://github.com/lcodeca/SUMOActivityGen).

Thank you for your help.
