### ISSUE TITLE
Obstacle effect

### ISSUE THREAD

**Issue by parksanha** [eclipse/sumo#9622]
Hello~

If there are buildings around the road or obstacles in the road, the vehicle's ability to travel will be affected.

Is there any way to achieve this effect?

**Comment by namdre** [comment]
The simplest way to model this is by reducing the local speed limit.
You could also reduce local lane width but this will only take effect on vehicle behavior when using the sublane model (https://sumo.dlr.de/docs/Simulation/SublaneModel.html#sublane-model)

You can also place vehicles on the road that are stopped for a long time (or permanently). In the default model they will block a whole lane but in the sublane model only part of a lane.
