### ISSUE TITLE
Error when creating SUMOConfig.cmake

### ISSUE THREAD

**Issue by Domsall** [eclipse/sumo#9636]
Since you changed a few lines in the CMakeLists.txt of libtraci and libsumo, I am getting Errors on my side.
I previously just deleted the lines to make it work on my side, because I did not need the SUMOConfig.cmake file (it did not get created then). But I would like to find and fix the problem for good now.

With the current github version I am getting the following error:
`CMake Error at src/libtraci/CMakeLists.txt:57 (install): install Library TARGETS given no DESTINATION!`
`CMake Error at src/libsumo/CMakeLists.txt:77 (install): install Library TARGETS given no DESTINATION!`

When I add the following line of Code to the install command, everything works fine and the SUMOConfig.cmake gets created:
`RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}`

I actually do not know what this does or why this is needed, but it seems to work then...
  
---

**SUMO-version:** Latest Github version

**operating system:** Windows with Microsoft Visual Studio 2017

**Comment by behrisch** [comment]
can you please report your cmake version

**Comment by Domsall** [comment]
I use the cmake version shipped with Visual Studio, which currently is "3.12.18081601-MSVC_2"

**Comment by behrisch** [comment]
This is still in the making. We want to make it easier for people who use libsumo in their own project to do things like find_package(SUMO::libsumo)
