### ISSUE TITLE
LaneLink error in junctions when converting from Vissim to OpenDrive

### ISSUE THREAD

**Issue by stevenhz** [eclipse/sumo#9637]
When converting Vissim file to OpenDrive file using `netconvert` tool, the LaneLink connection in the Junction section is not right. The lanelink "to" points to the lane id of the connected road, instead of the lane of the connecting road.  According to [the document](https://www.asam.net/index.php?eID=dumpFile&t=f&f=4422&token=e590561f3c39aa2260e5442e29e93f6693d1cccd#top-43967f71-51a8-46cb-981a-84e11c37c00c), LaneLink is defined as "Provides information about the lanes that are linked between an incoming road and a connecting." 

---
In this picture it shows the network:
![image](https://user-images.githubusercontent.com/15105936/143220415-9d26dfaf-978f-4bcc-9d15-2a282f0588c2.png)

And this is the xodr file after using netconvert
```
    <junction name="9" id="6">
        <connection id="0" incomingRoad="286" connectingRoad="334" contactPoint="start">
            <laneLink from="-1" to="-4"/>
        </connection>
    </junction>
```

The `<laneLink from="-1" to="-4"/>` is supposed to be `<laneLink from="-1" to="-1"/>`

**SUMO-version:**
V1.10.0
**operating system:**
Windows 10

**Comment by namdre** [comment]
Can you provide an input file to reproduce this?

**Comment by stevenhz** [comment]
[Highway_10.zip](https://github.com/eclipse/sumo/files/7595682/Highway_10.zip)

**Comment by namdre** [comment]
Thank you for the report and input example!
You can download a patched version tomorrow at https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_development_version

**Comment by stevenhz** [comment]
Thank you very much!
