### ISSUE TITLE
unclickable ParkingArea after moving junction with active grid

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#9639]
- create an edge
- place busStop
- activate grid
- move junction a few grid points away
-> busStop cannot be inspected anymore

I suspect that part of the busStop position-updated is affected by the active grip and this causes inconsistent position / rtree data

**Comment by palvarezlopez** [comment]
@namdre I cannot reproduce it

**Comment by namdre** [comment]
- in `tests\tools\misc\generateParkingAreaRerouters\visible_preferredAlternative` run `netedit -s net.net.xml -a input_additional.add.xml`
- activage grid
- move junctions gneJ4 and gneJ5 downwards by one grid point
- try clicking the parkingArea 'pD' on edge 'd'

the parkingArea will also disappear when zooming in to edge 'd'

**Comment by palvarezlopez** [comment]
@namdre the problem is only for ParkingAreas, because they have boundaries
