### ISSUE TITLE
cannot load parkingAreaReroute without probability

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#9640]
the attribute is optional though.

Not a regression since 1.10.0 could lnot oad parkingAreaReroute with any kind of attributes

**Comment by palvarezlopez** [comment]
@namdre I thought that probability is always needed. There is the same error for RouteProbReroute and DestProbReroute

**Comment by namdre** [comment]
When in doubt, check how NLHander loads it. But in this case, the documentation also says this is optional.
