### ISSUE TITLE
How to extract the patterns of the work trips?

### ISSUE THREAD

**Issue by amiradavoudi** [eclipse/sumo#9641]
Hello. 
Assume that we have access to work trips (two types: from home-to-work(h-t-w) and work-to-home(w-t-h)) which are made by n different drivers in a city from source A to destination B. 
Each driver makes typically between 15 and 20 work trips in a period (e.g. a month). 
 
The departure time for h-to-w trips and for w-to-h trips are generated based on a normal distribution. Now assume that we shuffle these trips and now the question is that how we can relate each w-to-h trip to its corresponding h-t-w trip, and finally extract all the corresponding work trips of each driver in a city by means of an algorithm?

(Assumption: We know the departure and arrival times of each work trip and these times are generated based on a normal distribution)
[trips.pdf](https://github.com/eclipse/sumo/files/7595522/trips.pdf)
Thank you in advance for your help.  
---
*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**

**Comment by namdre** [comment]
This really depends on the process that gave you the trips. In an ideal case you would simply maintain the id of the drive despite shuffling and then simply associate the trips by their id. 
If you cannot do this, you can guess that trips with the same pair of (home,work) - (work,home) locations belong to the same driver.

**Comment by amiradavoudi** [comment]
Hello,
Thank you very much for your help. The point is that there is no clue such as ID or the locations of home and work.
The only information is the arrival and departure times. Anyway, Thank you again.

**Comment by namdre** [comment]
From your description, I was under the impression that you know the locations A and B. So if one trip goes from A to B and another from B to A they could be from the same driver. Please clarify the data you have available.

**Comment by namdre** [comment]
Closing due to lack of feedback.
