### ISSUE TITLE
libsumo wheel is broken

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#9647]
regression in 02d6d202c4411dec59a3546940835b3a5eb401a0

**Comment by behrisch** [comment]
So this is a follow up to #9446. We are supporting (at least) four different workflows on windows with Visual Studio:

1. Open the sumo directory in the GUI (this probably calls cmake with the Ninja generator) and select the build config from he GUI (this generates completely different build trees for each config)
2. Call cmake with the Ninja generator from the command line and then cmake --build --config from the command line. This is probably largely equivalent to 1 just without GUI
3. Call cmake with the VS2019 generator and then cmake -- build --config from the command line
4. Call cmake with the VS2019 generator open the resulting SUMO.sln and then select the config in the GUI

@palvarezlopez You are using 4. and #9446 should fix that case, correct?

**Comment by angelobanse** [comment]
i also normally use 1 - but this time, after the changes to SUMOLibraries, i used cmake-gui once to delete the cache and generate a new VS Solution, after which i used the resulting SUMO.sln to execute manually `install_dll` (the first time ever) before returning to the workflow 1.

**Comment by behrisch** [comment]
Why was running install_dll necessary?

**Comment by angelobanse** [comment]
> Why was running install_dll necessary?

When attempting to run the project, `gdal304.dll` could not be found.

**Comment by namdre** [comment]
@behrisch I'm using (1)

**Comment by behrisch** [comment]
So the problem is that if we use a multi-config generator as with Visual Studio (so case 3. or 4.) it is not possible to determine at configure time (so for the cmake call without --build) whether we build Release or Debug. I could not find a way to let cmake determine the dependencies at build time.

The "fix" now is: If "Release" has been chosen at configure time and we use Ninja we copy only release dlls. In any other case everything. Furthermore dll copying is not part of "build all" anymore but is a dependency for every single binary. This ensures it is always executed even if you choose to build only "duarouter" or so. @palvarezlopez Pleaese check whether that works with your setup.

**Comment by behrisch** [comment]
PS: It should never be necessary to run install_dll manually. If you find a case please report a bug.

**Comment by yunpangfloetteroed** [comment]
I use 4, but directly press the icon "build solution" to build sumo

**Comment by behrisch** [comment]
@palvarezlopez please reopen if your workflow is broken now
