### ISSUE TITLE
How to randomize the depart time of a vehicle in a flow

### ISSUE THREAD

**Issue by MohamadReza-Haghani** [eclipse/sumo#9648]
Hi,

I defined a traffic flow with "number" = 1, "begin" = 100, and "end" = 200. I was wondering how I can randomize the depart time of the vehicle created by this flow so that the depart time varies between 100 and 200 in different runs. 
  
Thanks,
Reza.

---
*If possible, upload an example that shows your problem.*

**SUMO-version: 1.10**

**operating system: Windows 10**

**Comment by namdre** [comment]
The easiest way to achieve random departure in a fixed interval is by defining a trip/vehicle with begin=x and setting option **--random-depart-offset y** 
In your case x=100 and y=100.

Then set **--seed** or **--random** to vary runs: https://sumo.dlr.de/docs/Simulation/Randomness.html

Alternatively, run **duarouter --randomize-flows** with random/seed before each simulation run.

**Comment by MohamadReza-Haghani** [comment]
Thank you for your responses. I tried **--random-depart-offset <Time>** in sumocfg file. It randomizes the entrance times of all vehicle flows. I was wondering how I can influence just the entrance time of a specific vehicle flow.

**Comment by namdre** [comment]
You can define `<flow begin="100" number="1" probability="0.02" .../>
The likelihood that the vehicle will appear within the next 100 steps is then 87% but the probably is a bit skewed towards the start of the interval.
