### ISSUE TITLE
failed screenshots should not generate files

### ISSUE THREAD

**Issue by angelobanse** [eclipse/sumo#9653]
Currently, when no file extension is specified saving a screenshot, an error dialog is shown "Saving failed. Unknown file extension for image!" but nevertheless an extensionless file is created.

Possible approaches:
1) assume a default filetype (e.g. .png) when no extension is specified
2) keep the error dialog, but prevent the creation of such file

**Comment by namdre** [comment]
I'm in favor of a default extension (i.e. png)

**Comment by angelobanse** [comment]
closed by e6dc0ea3208883e96d251700ae2aff10e932afeb
