### ISSUE TITLE
changing the vClass should automatically change the guiShape (in the VehicleTypeDialog)

### ISSUE THREAD

**Issue by angelobanse** [eclipse/sumo#9654]
When selecting a certain vClass in the dropdown menu, the corresponding guiShape should be automatically selected (if possible).
Naturally, the user should be able to change the guiShape later if desired, but it would be nice to show the available shapes.

Classes such as `army` or `vip` could use the default passenger shape - or we could create their shapes

**Comment by palvarezlopez** [comment]
@namdre I have a question about this ticket: If I change automatically the guiShape in the vClass dialogs, it implies that the guiShape attribute will be written in XML (for example, for vClass bicycle guiShape="bicycle" will be always written in XML. What do you think about?

**Comment by namdre** [comment]
You can retrieve the default guiShape for a vClass by creating a new instance of SUMOVTypeParameter with that vClass.
There should be no need to set , it will already have the new if you are simply using the new default.

Also, the shape updated should only happen if VTYPEPARS_SHAPE_SET isn't set.

**Comment by namdre** [comment]
The big switch statement is quite redundant since we already have the same information stored in `SUMOVTypeParameter::VClassDefaultValues`

Please refactor
