### ISSUE TITLE
shorten name prefixes for elements

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#9666]
currently, ids are prefixed with the full element name. This is wasteful. Instead we should find a short unique prefix for each element (similar to how we use 'E' for edges and 'J" for junctions).

additionals:
- parkingArea: pa
- busStop: bs
- trainStop: ts
- rerouter: rr
- calibrator: ca
- routeProbe: rp
- vss: vs
- chargingStationg: cs
- polygon: po
- poi:  poi

demand:
- route: r
- vType: t
- vehicle: v
- trip: t
- flow: f
- person: p
- container: c

**Comment by namdre** [comment]
more prefixes are needed:

- e1detector / inductionLoop : e1
- e2detector / laneAreaDetector : e2
- e3detector / entryExitDetector : e3

**Comment by behrisch** [comment]
> @palvarezlopez more prefixes are needed:
> 
>     * e1detector / inductionLoop : e1
> 
>     * e2detector / laneAreaDetector : e2
> 
>     * e3detector / entryExitDetector : e3

Sorry for being late to the party but personally I don't like the e1 e2 e3 classification and would like to phase it out if possible. Can we go for something like il, la, ed (or me for multientry)?

**Comment by palvarezlopez** [comment]
@behrisch what is your proposal? Is like this?

* e1detector / inductionLoop : il

* e2detector / laneAreaDetector : lad

* e3detector / entryExitDetector : eed

**Comment by behrisch** [comment]
I would also be fine with only `la` and `ed` if we want to stick with two letters.

**Comment by palvarezlopez** [comment]
@namdre what do you think?

**Comment by namdre** [comment]
il, la, ed are fine

**Comment by namdre** [comment]
and ii for the instantInductLoop
