### ISSUE TITLE
visualization of sinks and sources when uploading taz.xml file via "Load Additionals" option in netedit

### ISSUE THREAD

**Issue by vmintsis** [eclipse/sumo#9672]
When uploading sinks and sources in netedit using a taz.xml file via the "Load Additionals" option they are not visualized appropriately. 

For example, an edge that has been defined as source in the xml file appears both as a sink and source in netedit.
  
---

**SUMO-version: 1.10.0 & 1.11.0+0033-71fa9d03096**

**operating system: Windows 10 **

**Comment by namdre** [comment]
This is a bug: when only tazSource or tazSink is defined for an edge, the missing weight is initialized with '1' whereas it should be '0'.
