### ISSUE TITLE
SUMO Traci.lane.getLastStepOccupancy calculation result ERROR

### ISSUE THREAD

**Issue by KaguraTart** [eclipse/sumo#9684]
**SUMO-version:1.10.0**

**operating system:Windos10**

  if I turn on the sublane model (using :`<lateral-resolution value="3.5"/>`),the result of Traci.lane.getLastStepOccupancy is not right.

---
Test 1 : not use lateral-resolution: the Occupancy will be close to 100%.

---
Test 2 : not use lateral-resolution:the Occupancy can get the right result.

**Comment by behrisch** [comment]
Can you share your scenario?

**Comment by behrisch** [comment]
3.5 is not the best choice for the lateral resolution. Usually it is smaller than the default lane width of 3.2. But even though our local tests run fine with 3.5 and 0.8 so I am closing this one. Feel free to reopen if you have more information.

**Comment by KaguraTart** [comment]
thanks your reply！



---- 回复的原邮件 ----
| 发件人 | Michael ***@***.***> |
| 日期 | 2022年01月10日 16:14 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [eclipse/sumo] SUMO Traci.lane.getLastStepOccupancy calculation result ERROR (Issue #9684) |

3.5 is not the best choice for the lateral resolution. Usually it is smaller than the default lane width of 3.2. But even though our local tests run fine with 3.5 and 0.8 so I am closing this one. Feel free to reopen if you have more information.
