### ISSUE TITLE
Retrieve neighbors information while driving

### ISSUE THREAD

**Issue by Lenoral** [eclipse/sumo#9686]
I know there is a function traci.Vehicle.getNeighbors, but as I tested, it can only get these information while the ego vehicle changing lanes, so is there any way to get information of neighbors while driving but not changing lanes?

**Comment by namdre** [comment]
take a look at context subscription filters for neighboring vehicles: https://sumo.dlr.de/docs/TraCI/Object_Context_Subscription.html#command_0x7e_add_context_subscription_filter
