### ISSUE TITLE
Issues for using travci to reroute the vehicle

### ISSUE THREAD

**Issue by kivi377** [eclipse/sumo#9687]
Dear Sumo developer,
Thanks a lot for you bring us a so powerful tool.
I am a master student in tu berlin, and I try to use sumo to analyze the parking-related problem.
The route of the vehicle was pre-defined in the xml file and the depart="50". And it will first attempt to park in a full occupied  parking areas. 
After that i use traci :
       traci.vehicle.changeTarget('Parkingflow50',"-1001")
       traci.vehicle.setParkingAreaStop('Parkingflow_1',"parkingArea_3",duration="2000")
to control the vehicle from a full occupied parking area reroute to another parking area, it seems like the vehicle need to wait for about 350 s and then in the sumo-gui, it shows:
_Warning: Vehicle 'Parkingflow50' skips stop on lane '-355983686.19_0' time=403.00.
Warning: Vehicle 'Parkingflow50' ends teleporting on edge '-355983686.192', time 403.00._

And after this long wait, the vehicle will finally go to the parkingArea_3.

And i am curious about this point, is it bacause of the defaut setting in the parking defination?

BR,
Runkai

**Comment by namdre** [comment]
In your simulation, the stop at the original (occupied) parkingArea was not removed from the vehicle route by your commands. Consequently, the vehicle waiting for a free space until teleported. For manual parking rerouting use the command
`traci.vehicle.rerouteParkingArea' (it modifies the route automatically).
