### ISSUE TITLE
Geo coordinates precision not enough (only 4 digits after the comma for lon and lat)

### ISSUE THREAD

**Issue by llu0120** [eclipse/sumo#9688]
Hi, 

I'm trying to get the accurate geo coordinates from sumo x,y coordinate, using the function below. 
`libtraci::Simulation::convertGeo(pos_x, pos_y, false);`
where `pos_x` and `pos_y` is the x,y retrieved in sumo. 

However, after the `converGeo` funcion the geo coordinates outputs a result with only 3~4 digits after the comma, like below.
TraCIPosition(-73.8584,45.702,-1.07374e+09)

I download the map via `./osmWebWizard.py` and try to use netcovert to have a more accurate geo coordinates (more digits after the comma) like below.  
`netcovert -s test.net.xml -o test_geo.net.xml --precision.geo 8 `

Based on the option arguments in netcovert `--precision.geo`, the default is actually 6 digits after the comma for lon and lat, may I know why there's only 3~4 digits after the comma for lon and lat in my case? Is it possible to make it into 8 digits after the comma? 

Thanks in advance.   

---
*If possible, upload an example that shows your problem.*

**SUMO-version:**
![Screenshot from 2021-11-29 13-48-55](https://user-images.githubusercontent.com/41609738/143925504-7e3a202c-4b12-4188-8885-021e5d47ba70.png)

**operating system:**

**Comment by namdre** [comment]
The options you mentioned only take effect for xml-outputs. 
The TraCI-API always returns full precision doubles (and we have tests that show this).
I'm guessing that the limited precision may come from your environment when printing the returned TraCIPositions.

**Comment by llu0120** [comment]
Thanks for the prompt reply. This is what I did to print out the converted geo results, which has limited precision. Any suggestions?
```
 libsumo::TraCIPosition pose_geo = libtraci::Simulation::convertGeo(pos_x, pos_y, false);
std::cout << "Gps Pose: " << pose_geo.getString() << std::endl;
```

**Comment by namdre** [comment]
run
`std::cout << std::setprecision(16) <<  pose_geo.x << ", " << pose_geo.y << "\n";`

and you will understand.
