### ISSUE TITLE
invalid network causes crash on sumo start

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#9701]
See bugfolder

**Comment by namdre** [comment]
- the crash is not specific to sumo-gui (sumo also crashes)
- the crash is not specific to version 1.11.0 (earlier versions also crash)
- caused by invalid network (walkingarea with a predecessor edge that does not permit pedestrians)

**Comment by namdre** [comment]
After refactoring (#9702) the crash does not show up with the given example configuration: The crash occurs during initialization of pedestrian infrastructure and this initialization is superfluous when the network has no persons.

**Comment by namdre** [comment]
The invalid network may have been due to manual modifications after calling netconvert. At least, the faulty walkingarea cannot be reproduced when doing a fresh osm import of the problematic location.

**Comment by namdre** [comment]
faulty network is reproducible

**Comment by namdre** [comment]
regression was via #8587  (fixPermissions)
