### ISSUE TITLE
new error in intermodal simulation

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#9712]
route-not-found in I4Port scenario

simulation completed without errors in 1.10.0

**Comment by rummel123** [comment]
Small example with that error.
[intermodal_bug.zip](https://github.com/eclipse/sumo/files/7640721/intermodal_bug.zip)

**Comment by namdre** [comment]
The vehicle that carries person arrives at the containerStop
The person should arrive at the busStop which has a slightly different location.
In 1.11.0 the person arrives at the containerShop (possibly because it matches the vehicle stop location better) and cannot continue because the containerStop is not connected to the pedestrian network.

most likely broken via #9341

To fix this, we must either
- consider the intended destinationStop in MSStageDriving::setArrived when setting myArrivalPos (and ignore the vehicle position)
- or use the destinationStop of the previous stage in MSStageTrip::setArrived and pass this to intermodalrouter::compute to call getStopEdge rather than getDepartEdge

**Comment by namdre** [comment]
Not a regression because the problem can also be triggered with 1.10.0. It only became exposed via #9341
