### ISSUE TITLE
Unit in Sumo

### ISSUE THREAD

**Issue by TrinhTuanHung2021** [eclipse/sumo#9716]
Hello all, I am a new member.

I wonder is there any way to change unit in Sumo? Using km/h instead of m/s. I try to change unit in Sumo but i can't find how to convert.

Thanks and best regards

Add your issue description here.
  
---
*If possible, upload an example that shows your problem.*

**SUMO-version:**

**operating system:**

**Comment by behrisch** [comment]
Hi and welcome. Actually we are quite happy that the international scientific community has agreed on base units we can use. So sorry but no, I don't think we will provide different units. It is not too hard to process the output though.
