### ISSUE TITLE
gridDistricts.py 

### ISSUE THREAD

**Issue by monasabeti** [eclipse/sumo#9720]
Add your issue description here.
  i want to Generates a grid of districts (TAZ) with a given width (in m) for a given network file.
and use this code: " python tools/district/gridDistricts.py -n <net-file> -o <output-file> -w 300"
but i get error like this:
C:\Program Files (x86)\Eclipse\Sumo\tools\district> python tools/district/gridDistricts.py -n osm.net.xml -o tazgrid.add.xml -w 300

python: can't open file 'C:\Program Files (x86)\Eclipse\Sumo\tools\district\tools\district\gridDistricts.py': [Errno 2] No such file or directory

HOW CAN I SOLVE THIS PROBLEM
---
*If possible, upload an example that shows your problem.*

**SUMO-version:* 1.11.0*

**operating system:**

**Comment by namdre** [comment]
when there is a space (' ') in your path, you must add quotes:
`python "C:\Program Files (x86)\Eclipse\Sumo\tools\district> python tools/district/gridDistricts.py" ...`
