### ISSUE TITLE
Steps to install SUMO 1.10.0

### ISSUE THREAD

**Issue by Adaickalavan** [eclipse/sumo#9723]
A new version of sumo==1.11.0 was released on 22 Nov 2021. 

I would like to install an older version of sumo==1.10.0 in Ubuntu.

Could you help me with the easiest set of detailed steps to install an older version of sumo==1.10.0 in Ubuntu? 

---
**SUMO-version:**
1.10.0

**operating system:**
Ubuntu

**Comment by behrisch** [comment]
Unfortunately the repositories do not keep older versions so you need to build from source. Please download the sources here: https://sumo.dlr.de/releases/1.10.0/sumo-src-1.10.0.tar.gz and follow the instructions here: https://sumo.dlr.de/docs/Installing/Linux_Build.html

**Comment by behrisch** [comment]
If you don't need an all bells and whistles build, you can also try `pip install eclipse-sumo=1.18.0`

**Comment by Adaickalavan** [comment]
Thanks @behrisch, `pip install eclipse-sumo=1.10.0` works.
