### ISSUE TITLE
Netconvert crashed everytime it called 

### ISSUE THREAD

**Issue by SafrasIqbal** [eclipse/sumo#9734]
I am using MOSAIC scenario convertor to generate scenarios with .osm file. However, the process not successful due to net.xml file not created since the netconvert crash. Appreciate any help here to resolve or workaround. 

 
![Scenario_Convert](https://user-images.githubusercontent.com/18607009/144755720-fda70a53-ae24-4a58-9caf-a0d7b324ecd1.png)
 
![netconvert_Crash](https://user-images.githubusercontent.com/18607009/144755725-052a0c03-af21-494c-b00c-a8c7be30a4fa.png)

  
---
*If possible, upload an example that shows your problem.*

**sumo Version 1.11.0**

**Ubuntu 21.04**

**Comment by namdre** [comment]
How did you install sumo? (or did you build it manually?)

**Comment by SafrasIqbal** [comment]
>
Hi @namdre , I installed it as per the official Build and Install guide of this repo. Because of this issue I reinstalled it but still the issue persist. 
Thank you for checking this.

**Comment by SafrasIqbal** [comment]
I think, this crash is common to every apps related to Sumo.Clean removal and reinstall will be a solution? if so what is the best way to remove it clean? Thanks

![sumo_Apps_crash](https://user-images.githubusercontent.com/18607009/144764268-252a07f8-0623-4e18-b4cd-13598405101b.png)

**Comment by namdre** [comment]
A similar issue has not been reported yet  (sumo is working fine on other ubuntu installations) and thus the best way forward is to figure out the root cause. Can you post the exact steps you used to build sumo (i.e. arguments provided to cmake)?

**Comment by SafrasIqbal** [comment]
I have followed below steps to install. However, I don't remember all went smooth in below process as it was sometime back. I can reinstall to test again. Can you suggest a proper way to uninstall sumo. I think just deleting the directory will not work. Thank you. 

```
    sudo apt-get install cmake python g++ libxerces-c-dev libfox-1.6-dev libgdal-dev libproj-dev libgl2ps-dev swig
    cd <SUMO_DIR> # please insert the correct directory name here
    export SUMO_HOME="$PWD"
    mkdir build/cmake-build && cd build/cmake-build
    cmake ../..
    make -j$(nproc)
```

**Comment by namdre** [comment]
Uninstalling isn't necessary and you can easily keep multiple version on your machine.
For the purpose of calling 'sumo' and 'netconvert', all that counts is which bin directory comes first in your $PATH variable.
For running traci and python tools, you only need to make sure that $SUMO_HOME points at the correct directory.

Please install a fresh version of sumo with the steps outline above, the run <SUMO_DIR>/bin/netconvert and report the results.

**Comment by SafrasIqbal** [comment]
I have made a new installation and the problem resolved. Thank you for your prompt help.
