### ISSUE TITLE
od2trips read in multiple od files (question)

### ISSUE THREAD

**Issue by wxinl** [eclipse/sumo#9736]
When using od2trips, is it possible to read in multiple files, each containing an OD file for an hour? For example, I tried this:
od2trips -n osm.nex.xml  -d OD1.txt OD2.txt -o napa.trips.xml,
but with error:
Error: The parameter 'OD2.txt' is not allowed in this context.

**SUMO-version:** v1.9.2

**operating system:** Windows

**Comment by namdre** [comment]
Yes. Separate the file name with a comma:
`od2trips -n osm.nex.xml -d OD1.txt,OD2.txt -o napa.trips.xml`
