### ISSUE TITLE
Vehicle lane changing problem

### ISSUE THREAD

**Issue by emotion68** [eclipse/sumo#9742]
After I set laneChangeMode=0, shouldn't the vehicle only run along one lane? Why does it still change lanes during the simulation process?
[picture.zip](https://github.com/eclipse/sumo/files/7660304/picture.zip)

**Comment by namdre** [comment]
Not necessarily. Lane 0 on the first edge could be connected to lane 1 on the second edge so the vehicle can reach other lane indices without performing a lane change.

However, the vehicle should never change between lanes of the same edge with laneChangeMode=0

**Comment by emotion68** [comment]
OK
I also want to ask, if under a certain lane change model, I want to force a vehicle to change to another lane in a certain section of the road, and after this section, I no longer control it, then it Will you continue to drive along this lane or change lanes based on the lane change model?

**Comment by emotion68** [comment]
My purpose is to control the vehicle to change lanes in a short section of the road, and ignore it after passing this short section.

I need to close the model in the section that controls the vehicle to change lanes. Do I need to control it after walking through this section and then turn on the model?

**Comment by emotion68** [comment]
> Not necessarily. Lane 0 on the first edge could be connected to lane 1 on the second edge so the vehicle can reach other lane indices without performing a lane change.
> 
> However, the vehicle should never change between lanes of the same edge with laneChangeMode=0
OK
I also want to ask, if under a certain lane change model, I want to force a vehicle to change to another lane in a certain section of the road, and after this section, I no longer control it, then it Will you continue to drive along this lane or change lanes based on the lane change model?

**Comment by emotion68** [comment]
> My purpose is to control the vehicle to change lanes in a short section of the road, and ignore it after passing this short section.
> 
> I need to close the model in the section that controls the vehicle to change lanes. Do I need to control it after walking through this section and then turn on the model?

My purpose is to control the vehicle to change lanes in a short section of the road, and ignore it after passing this short section.

I need to close the model in the section that controls the vehicle to change lanes. Do I need to control it after walking through this section and then turn on the model?

**Comment by emotion68** [comment]
> Not necessarily. Lane 0 on the first edge could be connected to lane 1 on the second edge so the vehicle can reach other lane indices without performing a lane change.
> 
> However, the vehicle should never change between lanes of the same edge with laneChangeMode=0

My purpose is to control the vehicle to change lanes in a short section of the road, and ignore it after passing this short section.

I need to close the model in the section that controls the vehicle to change lanes. Do I need to control it after walking through this section and then turn on the model?

**Comment by namdre** [comment]
once you set laneChangeMode=0 you are resposible for all lane changing. If you wish to give back control to the lane change model, set laneChangeMode=1621

**Comment by emotion68** [comment]
> 我也想问一下，如果在某个变道模式下，我想强制车辆在某段路中变到另一条车道，而且过了这一段，我就不再管了，那你会继续沿着这条车道行驶还是根据换道模型换道？

So, if this is the case, after I turn on the lane-changing model again, will the vehicle drive along the previously controlled lane or will it change lanes based on the lane-changing model?

**Comment by emotion68** [comment]
> So, if this is the case, after I turn on the lane-changing model again, will the vehicle drive along the previously controlled lane or will it change lanes based on the lane-changing model?

So, if this is the case, after I turn on the lane-changing model again, will the vehicle drive along the previously controlled lane or will it change lanes based on the lane-changing model?

**Comment by emotion68** [comment]
> once you set laneChangeMode=0 you are resposible for all lane changing. If you wish to give back control to the lane change model, set laneChangeMode=1621
> So, if this is the case, after I turn on the lane-changing model again, will the vehicle drive along the previously controlled lane or will it change lanes based on the lane-changing model?

**Comment by namdre** [comment]
It will change according to the whims of the lane change model as soon as you turn it on fully. However, setLaneChangeMode also allows you to switch it on partially (i.e. to only change for strategic/unavoidable reasons).
