### ISSUE TITLE
Add option to disable all output to stdout/stderr (libsumojni)

### ISSUE THREAD

**Issue by neumannje** [eclipse/sumo#9743]
# Current behaviour
When loading a configuration via Simulation.load(...), sumo will output 'Loading configuraton ... done' to stdout. This prevents writing unittests in java (maven + surefire) with sumo.

# Reason for change
Surefire uses stdout for the communication of testresults between the main-thread and the test-threads. By writing to stdout, surefire gets corrupted.

Error:
```
# Created at 2021-12-06T13:41:36.176
Corrupted STDOUT by directly writing to native stream in forked JVM 1. Stream 'Loading configuration ... done.'.
java.lang.IllegalArgumentException: Stream stdin corrupted. Expected comma after third character in command 'Loading configuration ... done.'.
                at org.apache.maven.plugin.surefire.booterclient.output.ForkClient$OperationalData.<init>(ForkClient.java:507)
                at org.apache.maven.plugin.surefire.booterclient.output.ForkClient.processLine(ForkClient.java:210)
                at org.apache.maven.plugin.surefire.booterclient.output.ForkClient.consumeLine(ForkClient.java:177)
                at org.apache.maven.plugin.surefire.booterclient.output.ThreadedStreamConsumer$Pumper.run(ThreadedStreamConsumer.java:88)
                at java.lang.Thread.run(Thread.java:748)
```

# How to fix it:
Add the option to sumo to disable ALL output to stdout/stderr. Using the --log option did not prevent sumo from writing to stdout.

# How to reproduce:
```
import org.eclipse.sumo.libsumo.Simulation;
import org.eclipse.sumo.libsumo.StringVector;

public class TestSumoOut {

    @Test
    public void testLoad() {
        System.loadLibrary("libsumojni");
        Simulation.load(new StringVector(new String[]{"-c", "/path/to/sumocfg"}));
    }
}
```

**Comment by namdre** [comment]
@behrisch maybe a new option **--silent** ?

**Comment by behrisch** [comment]
I am not sure about the general usefulness of the message anyway. Maybe we can print it only if --verbose is given?

**Comment by namdre** [comment]
I guess I can live without it. However, we don't know whether option --verbose is set until we load the configuration.

**Comment by behrisch** [comment]
Yes, it would only be printed if --verbose is given on the command line. I still think this small inconsistency is better than a new option.
