### ISSUE TITLE
add button "copy link" to test extractor

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#9749]
i.e. https://sumo.dlr.de/extractTest.php?path=sumo/tests/sumo/basic/tls/actuated/dualring_simple

**Comment by namdre** [comment]
@angelobanse can you link the repository in which the change was made?

**Comment by behrisch** [comment]
This was the final change: http://ts-sim-service-ba/trac/log/trunk/projects/sumo/sumo-sim.org/htdocs/extractTest.php?rev=9518 (link only works inside DLR)
