### ISSUE TITLE
I have a question about the values aggregated by Lanearea Detectors (E2): nVehEntered and nVehLeft.

### ISSUE THREAD

**Issue by parksanha** [eclipse/sumo#9752]
Hello.

I have a question about the values aggregated by Lanearea Detectors (E2): nVehEntered and nVehLeft.

When E2 counts nVehLeft, is it when the frontmost part of the vehicle leaves E2? Or is it when the rearmost part of the car leaves the E2?

Likewise,
If E2 counts nVehEntered, is it when the frontmost part of the vehicle enters E2? Or is it when the car is fully in E2?

Thank you.

**Comment by namdre** [comment]
nVehLeft counts when the rearmost part has gone past the detector end. nVehEntered counts when the frontmost part has gone past the detector start.

**Comment by parksanha** [comment]
@namdre Thank you~
