### ISSUE TITLE
allow visualizing active edgeData attributes

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#9756]
instead of loading offline edgeData (output) from a file, select among the list of currently active edgeData definitions to visualize the aggregated data from their previous (or current?) interval

**Comment by rjmaris** [comment]
I'd believe that this improvement not only affects the daily work of the modeler but also makes it easier for casual users to only execute simulations and view meaningful visualisations. Those casual users could be decision makers with fascination for the dynamics of a micro simulation, and play a bit with the model of an upcoming project, e.g. using Scale Traffic and subsequent viewing of visualized edgeData outputs.
