### ISSUE TITLE
Latest SUMO not in brew bottle

### ISSUE THREAD

**Issue by qichaow** [eclipse/sumo#9761]
The SUMO installed through brew install on Mac only has up to SUMO 1.9.

**Comment by schwamborn** [comment]
As you can see [here](https://github.com/DLR-TS/homebrew-sumo/releases), bottles are available up until the latest version 1.11.0.
If your brew installation only shows up to 1.9.0, please try:

> brew update
> brew update

You might also want to check your brew installation with
> brew doctor

**Comment by schwamborn** [comment]
Also see #9594.
