### ISSUE TITLE
how can I get the performance and statistics(avg) data from the specific zone in sumo

### ISSUE THREAD

**Issue by monasabeti** [eclipse/sumo#9762]
@jJakob Erdmann
i want to know that how can i get the performance and statistics data from the specific zone.
like the picture bellow that get this data from the sumocfg file.

  
![Capture](https://user-images.githubusercontent.com/43193011/145450628-792c6c18-31e0-4429-a9a7-ad2039a6e82e.PNG)
and the picture bellow show that i create the TAZ for my scenario now get the trips file from the od2trips tools but in additional i want to get the statistics data from the one zone like zone3-1

![Capture](https://user-images.githubusercontent.com/43193011/145451275-a504b96b-3b35-4679-8755-397aa369ea26.PNG)

**SUMO-version:*1.11.0*

**Comment by namdre** [comment]
there is no traffic for a single zone but you can get statistics for pairs of zones: https://sumo.dlr.de/docs/Tools/Output.html#tripinfobytazpy

**Comment by monasabeti** [comment]
@namdre thanks alot for your respond and guiding.
