### ISSUE TITLE
rerouter + CH = crash

### ISSUE THREAD

**Issue by ambuehll** [eclipse/sumo#9771]
See example [files](https://drive.google.com/drive/folders/1a-TkxAha5Up0gTTXdSXayBs6w0B1B9Dj?usp=sharing). Rerouter placed, activated at 19000, with meso and CH as router -> crash. 

With astar -> no crash, works as expected. 
Thanks

**SUMO-version:**current build

**operating system:**Windows

**Comment by namdre** [comment]
Most likely, the contraction hierarchy must be recomputed every time a rerouter modifes connectivity in the network.

**Comment by namdre** [comment]
for adding new capabilities, see #9776
