### ISSUE TITLE
how should i define the attributes of tazRelation ?

### ISSUE THREAD

**Issue by monasabeti** [eclipse/sumo#9773]
@Jakob Erdmann , @Michael Behrisch,
hello.
the tazRelation is modeled by our attributes that we defined in the parameters.
and now my question is that how should i set the attributes in parameters that i can count the real number of vehicle which are in the upstream of specific zone. for example give me the number of vehicle that goes from zone 1-2 to zone 2-2
when i set the parameters: count=1000 and when get the data from odtrips.xml file and count the vehicle it gives me 1000 that i set it by myself i dont want to get this result , but i want to get the real data that goes from this zone to the other.
or in the other words, how define the real traffic between these zones or how to define the zone in original traffic scenario?

![Capture](https://user-images.githubusercontent.com/43193011/145717541-2e90c1d0-a227-4c8b-9666-3ade7867cbdc.PNG)
and when i want to add more attributes to parameters i face with error: **attribute '-----' is not declared for element 'tazRelation'**
i try to add the routes.rou.xml from batch file and the statics data when run the osm.sumocfg to near my generate traffic to reality but i cant get a result.
![Capture](https://user-images.githubusercontent.com/43193011/145725666-77f9a66d-d0e4-4c95-a784-fbaf495198a5.PNG)

**SUMO-version:*1.11.0*

**Comment by namdre** [comment]
I don't understand your question.
Do you have access to real data that defines the number of trips between zones? If you have this data, then use it for your tazRelations. If you don't have this data, tazRelations will not help you and you need to use something different.

The main purpose of tazRelations files is to 
1. use them as input for od2trips (which cannot make use of all the attributes in your screenshot except 'count')
2. analyze routes from an existing scenario (via route2OD.py)

**Comment by monasabeti** [comment]
@namdre 
thanks alot for your respond.
you know firstly i define the tazgrid.xml file by this command:" python tools/district/gridDistricts.py -n <net-file> -o <output-file> -w 300"
and the try to creat the od.xml file in netedite by tazrelation and then use this two file as an input for od2trips tools and this tools give me the number of the trips like this:
[<trip depart="0.79" departLane="free" departSpeed="max" from="-202596448" fromTaz="3_7" id="63" to="22720660#0" toTaz="4_7"/>, <trip depart="2.83" departLane="free" departSpeed="max" from="22720649" fromTaz="3_7" id="283" to="157890355#1" toTaz="4_7"/>, <trip depart="4.77" departLane="free" departSpeed="max" from="-202604674" fromTaz="3_7" id="519" to="704461601" toTaz="4_7"/>,....
my question is that according to this list of the trip that i gain from od2trips file, this file create according to the real data or not?

**Comment by monasabeti** [comment]
how can i access to real data?

**Comment by namdre** [comment]
Usually, you have to talk to people that collect this type of data for the area under consideration (i.e. city authorities). 
You might also be able to buy it: https://www.tomtom.com/products/origin-destination-matrix-analysis/

**Comment by monasabeti** [comment]
i really appreciated that for your helpful and prompt respond

**Comment by monasabeti** [comment]
and when i access to this real data how should i  use it for my tazRelations?

**Comment by monasabeti** [comment]
@namdre 
hello, i find the real data from this site:"https://sumo.dlr.de/docs/Data/Scenarios.html"
because i am beginner with sumo, could you please explain for me how can i use this real data in this tools :od2trips -n tazgrid.xml --tazrelation-files od.xml --ignore-vehicle-type -o odtrips.xml .
to obtain the odtrips.xml as an output to give me list of vehicle trip according to the real data?

**Comment by namdre** [comment]
The linked page does not contain datat that is suitable for use with od2trips.
