### ISSUE TITLE
About "Lane- or Edge-based Traffic Measures"

### ISSUE THREAD

**Issue by parksanha** [eclipse/sumo#9775]
Hello.

I am trying to calculate various indicators using [Lane- or Edge-based Traffic Measures].
https://bit.ly/30nQOPi

I wrote an add file as below and simulated it, but other values except for the count value do not appear.
![image](https://user-images.githubusercontent.com/62294108/145768990-b952759e-f931-49c3-ac61-e5bc1630b3a5.png)

![image](https://user-images.githubusercontent.com/62294108/145769119-7133f661-8282-43b1-8388-b52300cfdc0d.png)

Is there something I've been doing wrong?

**Comment by namdre** [comment]
your definition is configured to only record vehicles that have the vType id  `passenger` most likely your vehicles have a different type (default type is "DEFAULT_VEHTYPE"). Maybe you are confusing vType and vClass (default vClass is "passenger").
vClass is just one of many attributes for a vType. See https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#available_vtype_attributes

**Comment by parksanha** [comment]
@namdre 

I do not know how to solve the phenomenon that only count data such as left and entered are displayed when executed as above, and other values such as waittime do not appear.

**Comment by parksanha** [comment]
@namdre 

As you can see in the figure above, the calculated data is sampledSeconds, departed, arrived, entered, left, laneChangedFrom, and laneChangedTo only.

I also need other values like waitingTime, speed and I want to know why it is not being produced.

**Comment by namdre** [comment]
What you are seeing are default values which are written when no vehicles are registered.
Remove attribute "vTypes" from your definition and you will see the other attributes as well.

**Comment by parksanha** [comment]
@namdre 
thank you so much.
