### ISSUE TITLE
plot_trajectories: filtering multiple edges

### ISSUE THREAD

**Issue by Mikroni998** [eclipse/sumo#9781]
Hello
I tried to filter out two edges, but it doesn't recognize the second one. What is the syntax for this? I'd like to select multiple edges, more than 10 so I can plot trajectories on the main corridor.
<img width="706" alt="Capture" src="https://user-images.githubusercontent.com/91965719/145844346-dd0b90aa-bfcf-4b28-a27a-1addc3bbce01.PNG">

**Comment by namdre** [comment]
put a comma between the edge ids.
