### ISSUE TITLE
"Lanearea Detectors (E2)" or "Lane- or Edge-based Traffic Measures"

### ISSUE THREAD

**Issue by parksanha** [eclipse/sumo#9791]
Hello.

In the picture below, vehicles passing through lane 47850474702_3 will either go straight or turn left.

![image](https://user-images.githubusercontent.com/62294108/146124498-5af6f654-1f1b-46a3-b648-b0df0bc5f52f.png)

I would like to know if there is a way to aggregate the value for each exit direction of vehicles traveling on lane 47850474702_3 with methods such as "Lanearea Detectors (E2)" or "Lane- or Edge-based Traffic Measures".

For example, if I want to classify by vehicle type, it's like using "vTypes".

**Comment by namdre** [comment]
This is not possible with a detector placed on lane 47850474702_3. However, you can place e2 detectors on the *internal* lane inside the intersection and these detectors would aggregated vehicles according to their turning movement.
Placing detectors in internal lanes is not supported by netedit but it can be done by editing the detector definition file with a text editor.
See https://sumo.dlr.de/docs/sumo-gui.html#investigating_internal_edges_and_lanes
