### ISSUE TITLE
remove sumo-all.zip

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#9794]
It is not even linked from the downloads page. We might consider to remove the tar.gz as well. whoever wants a zipped full state of the repo of a certain version can easily download it here https://github.com/eclipse/sumo/tags

Please discuss

**Comment by namdre** [comment]
we may want to keep such a full state as a backup-of-last resort but we don't need it on the download page.

**Comment by behrisch** [comment]
what for? literally everyone cloning the repo has the full history with all tags. That's more backup than we could ever dream of ;-)

**Comment by namdre** [comment]
Paranoia :wink: 

I don't mind if you get rid of sumo-all.zip.
