### ISSUE TITLE
netdiff should handle edge types

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#9807]
Although the plain output creates type files they are ignored by the diff. It is probably too much effort to generate a real type diff (so comparing the attributes is maybe out of scope) but at least newly added types should be written to a separate type file.

**Comment by namdre** [comment]
computing a type diff shouldn't require much beyond adding ".typ.xml" to the list of PLAIN_TYPES (I don't think type diffing has any special cases).

**Comment by behrisch** [comment]
Can I redefine only single attributes of a type when loading multiple type files?

**Comment by namdre** [comment]
I would expect this to work based on the loading order of type files (later files overrider newer).
However, the code in NBTypeCont::insertEdgeType looks as if all attributes from the older type are kept rather than updated..
Probably needs a test and a fix.
