### ISSUE TITLE
At the intersection, left turning and right turning vehicles get stuck with each other, causing both vehicles to stop and stop

### ISSUE THREAD

**Issue by radiateboy** [eclipse/sumo#9811]
At the intersection, left turning and right turning vehicles get stuck with each other, causing both vehicles to stop and stop.
Is there any way to avoid such an accident?
![深度截图_plasmashell_20211216180052](https://user-images.githubusercontent.com/9248754/146356091-f72ec466-6635-4285-a238-dfc4c23944cf.png)
![深度截图_plasmashell_20211216180150](https://user-images.githubusercontent.com/9248754/146356092-b852d551-5f29-472d-a117-84de94254ce5.png)

**Comment by namdre** [comment]
there are multiple ways to deal with this
- improve insertion lane (i.e. with departLane="best") to avoid vehicles being inserted on unsuitable lanes 
- fix problems with upstream connections (sometimes the connection from prior edge are made in a way that forces vehicle to change across multiple lanes along a short length of road)
- modify vehicle routes dynamically with TraCI
- enable teleporting (vehicles should automatically be "teleported" onto the next edge after being stuck for 300s). It seems that this was disabled in your simulation

Look at the vehicle behavior in the minute before they became stuck to understand what got them into this spot.

**Comment by radiateboy** [comment]
@namdre thanks ! 
 After I added the “--time-to-teleport” parameter to run the simulation, it can run smoothly.

**Comment by namdre** [comment]
I still recommend looking at the simulation. Teleporting should be the last resort.

**Comment by radiateboy** [comment]
hi, @namdre,  thank you for your support and guidance.
that's route file is automatically generated by TAZ.I checked the route file and found that two vehicles blocking each other were derived from the same road section with a short time interval. 
I upload the project file. You can have time to see if it is caused by this problem
[sumo_example.tar.gz](https://github.com/eclipse/sumo/files/7743322/sumo_example.tar.gz)

**Comment by radiateboy** [comment]
`<vehicle id="tsbc_dxj_42976" type="BMW_Z4_2010_grey" depart="582.85" departLane="free" departSpeed="max" fromTaz="taz_101658" toTaz="taz_100342">
        <route edges="**-937 -2887** -2418 -2995 -2996 -2415 -2994"/>
</vehicle>
...
<vehicle id="tsbc_dxj_43003" type="MercedesV_14_Black" depart="586.10" departLane="free" departSpeed="max" fromTaz="taz_101658" toTaz="taz_100664">
        <route edges="**-937 -939** -1055 -2428 -1054 -1061 -1062 -11 -1057 -1056 -1070 -12 -1072 -52 -10 48 53 -1185 -1648 -1048 -1047 -14 -1049 -1050 -1051 -1190 -1188 -1186 -18 -1189 -2669 -2670 -2671 -2981 -2980 -2979 -2655 -2978 -2977 -2976 -2027 2026 230 2660 231 -2661 -232 -235 -2975 -2667 -2974 -2973 -2664 -2666 -2665 -238 -2663 -2662 -168 -167 -2654 -2653 -2652 -2651 -2971 -2972 -2970 -2969 -1728 -2721 -2722 -2723 -2719 -2720 -2725 -2724 -2726 -2727 -2728 -2729 -132 -2731 -2730 -192 -177 -182 -2968 -1729 -189 -2966 -2967 -133 -2965 -1636 -2964 -2963 -2962 -732 -731 2955 2958 -2956 -2957 -2954 -725 2953 2952 2650 2649 2648 2647 2646 2645 1479 1472 877 878 879 2538"/>
    </vehicle>`

**Comment by behrisch** [comment]
see also #1124
