### ISSUE TITLE
junction accident simulation for specified vehicles

### ISSUE THREAD

**Issue by thinker310** [eclipse/sumo#9813]
Hello, I want to know if there are some methods to model accident in the junction for the specified vehicles. I use option --collision.mingap-factor and --collision.stoptime, but the occurence of an accident is stochastic. How should I do to make an accident between specified vehicles in a junction. It is great if traci can reach it but I do not know how. Thank you in advance!

**Comment by namdre** [comment]
Even without TraCI you can use vehicle parameters to provoke collisions between specific vehicles: https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#transient_parameters

For an overview that also mentions the necessary TraCI methods, see https://sumo.dlr.de/docs/Simulation/Safety.html#deliberately_causing_collisions

**Comment by thinker310** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
