### ISSUE TITLE
memory leak in libsumo::TrafficLight::getCompleteRedYellowGreenDefinition

### ISSUE THREAD

**Issue by songjianbupt** [eclipse/sumo#9818]
in python, i used libsumo like this 
`tls = libsumo.trafficlight.getCompleteRedYellowGreenDefinition(tls_id)`
this will called many times

and i use valgrind to check the memory leak, the valgrind report 
==34541== 40,243,031 (34,804,000 direct, 5,439,031 indirect) bytes in 310,750 blocks are definitely lost in loss record 1,295 of 1,295
==34541==    at 0x483BE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==34541==    by 0x82445F9: libsumo::TrafficLight::getAllProgramLogics(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (TrafficLight.cpp:83)
==34541==    by 0x813CAEC: libsumo::TrafficLight::getCompleteRedYellowGreenDefinition(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (TrafficLight.h:79)
==34541==    by 0x8058A0E: _wrap_trafficlight_getCompleteRedYellowGreenDefinition (libsumoPYTHON_wrap.cxx:84182)
==34541==    by 0x5F5DB8: PyCFunction_Call (in /usr/bin/python3.8)
==34541==    by 0x5F698D: _PyObject_MakeTpCall (in /usr/bin/python3.8)
==34541==    by 0x57148A: _PyEval_EvalFrameDefault (in /usr/bin/python3.8)
==34541==    by 0x5F6165: _PyFunction_Vectorcall (in /usr/bin/python3.8)
==34541==    by 0x570E45: _PyEval_EvalFrameDefault (in /usr/bin/python3.8)
==34541==    by 0x5F6165: _PyFunction_Vectorcall (in /usr/bin/python3.8)
==34541==    by 0x56BDDC: _PyEval_EvalFrameDefault (in /usr/bin/python3.8)
==34541==    by 0x56A0B9: _PyEval_EvalCodeWithName (in /usr/bin/python3.8)

In TrafficLight.cpp:83
 77     for (MSTrafficLightLogic* logic : logics) {
 78         TraCILogic l(logic->getProgramID(), (int)logic->getLogicType(), logic->getCurrentPhaseIndex());
 79         l.subParameter = logic->getParametersMap();
 80         for (const MSPhaseDefinition* const phase : logic->getPhases()) {
 81             l.phases.emplace_back(new TraCIPhase(STEPS2TIME(phase->duration), phase->getState(),
 82                                                  STEPS2TIME(phase->minDuration), STEPS2TIME(phase->maxDuration),
 83                                                  phase->getNextPhases(), phase->getName()));
 84         }
 85         result.emplace_back(l);

the "new TraCIPhase" can't released by python

I changed the 
`322     std::vector<TraCIPhase*> phases;`
in TraCILogic into
`322     std::vector<std::shared_ptr<TraCIPhase> > phases;`
and also, some other places referenced to TraCIPhase，seems solved the memory leak

  
---
*If possible, upload an example that shows your problem.*

**SUMO-version:**
1.10.0
**operating system:**
ubuntu20.04

**Comment by namdre** [comment]
Thanks for reporting!

**Comment by behrisch** [comment]
@songjianbupt Thanks for the proposed fix. Unfortunately I get 
```
swig/python detected a memory leak of type 'std::shared_ptr< libsumo::TraCIPhase > *', no destructor found.
```
when I implement it. Did you solve this one?

**Comment by behrisch** [comment]
> when I implement it. Did you solve this one?

Never mind, I found it.
