### ISSUE TITLE
An Error in Documentation

### ISSUE THREAD

**Issue by thinker310** [eclipse/sumo#9820]
[1639725671(1)](https://user-images.githubusercontent.com/62609436/146505435-352a0383-b431-4316-bc04-a8d74bfaebf6.jpg)
![1639725732(1)](https://user-images.githubusercontent.com/62609436/146505545-d215842e-5f89-484a-ac0a-13c7f892a2dd.jpg)
On the option --collision.check-junctions, there is a spelling error in the first picture. The second one is correct, otherwise, the traci will be not connected.

**Comment by namdre** [comment]
Thanks!
