### ISSUE TITLE
closing all views and opening new ones messes up some gui elements

### ISSUE THREAD

**Issue by angelobanse** [eclipse/sumo#9824]
in sumo-gui, after closing all views and opening new ones, some elements (such as text in scale and imgFiles for POI's) are drawn just as colored rectangles.

![issue](https://user-images.githubusercontent.com/16121932/146531005-4def3606-9897-48cb-b044-0859e7eb09f7.png)

btw, this Speed Limit Sign is a POI with color="#ffffff" and uses a PNG imgFile

**Comment by behrisch** [comment]
I can confirm this here on Windows

**Comment by behrisch** [comment]
will be solved via #9822
