### ISSUE TITLE
plotXMLAttr.py does not work

### ISSUE THREAD

**Issue by Mikroni998** [eclipse/sumo#9825]
Hello, this python script does not work for none of the output data I get
Here's the example for detector speed. It cannot recognize the parameter begin. 
![image (1)](https://user-images.githubusercontent.com/91965719/146538749-4c6a8e29-33cb-47c8-9de1-97d926d3fd0d.png)

**Comment by namdre** [comment]
Based on the options you are using, you should call plotXMLAttributes.py (2D plots) rather than it's older cousing plotXMLAttr.py which does 1d plots only.

**Comment by Mikroni998** [comment]
So, to download a new version of SUMO? This one was downloaded a less than two months ago.

**Comment by namdre** [comment]
plotXMLAttributes.py is available since version 1.11.0 (released on 23.11.2021).
https://sumo.dlr.de/docs/Downloads.php
