### ISSUE TITLE
how to change safety distance in the intersection

### ISSUE THREAD

**Issue by thinker310** [eclipse/sumo#9829]
Hello, as shown in the picture, in the red box, I deliberately made a car stop in the intersection. However, in the green box, the car from eastern approach cannot go through and it also stop there, normally, it should slown down, bypass the car in red box and go through the intersection. So how to sovle this problem and achieve my idea? Thank you!
![image](https://user-images.githubusercontent.com/62609436/146667595-54a521ec-dd0b-4566-9d26-4938ddca8ebb.png)

**Comment by namdre** [comment]
It may work if you make the car stop with a <stop> element or traci.vehicle.setStop rather than just setting it's speed to 0. 
Alternatively, let the green car ignore the red car specifically: https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html#transient_parameters
