### ISSUE TITLE
make cars change link in an intersection

### ISSUE THREAD

**Issue by thinker310** [eclipse/sumo#9830]
Hi, as shown in the picture, in this scenario a car stop at the center of an intersection and I wonder how to let the two cars in the red box realize they can change link in the intersection and bypass the standing car. Could you please help me sovle it, thank you very much!
![image](https://user-images.githubusercontent.com/62609436/146673341-60bfd427-82e1-4a4f-8709-9c79dad7bc46.png)

**Comment by namdre** [comment]
lane changing on junctions is disabled by default. To make lane changing work, you need to post-process your network with
`netconvert -s old.net.xml --junctions.join-turns -o new.net.xml`
If the turning movement has an internal junction, lane changing will only work before the internal junction.
Internal junctions are built for a permissive turning movement (oncoming traffic has green hat the same time).
