### ISSUE TITLE
cacc performs emergency braking at low step length

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#9831]
simulation works fine at step-length 1 and 0.1 but starts to go bad at 0.01

**Comment by namdre** [comment]
@schwamborn I think, that the model was designed for a specific step-length (0.1?) and the the planned speed adaptation must be scaled with this in mind. 
This might also be the reason for #4839

**Comment by zaheenSyed** [comment]
Using a step length of 0.1 I still have thousands of warnings for my experiment. (7200s) I am using SUMO 1.10.0
Can you please advice why it is happening? CACC parameters are as shown below


carFollowModel="CACC" actionStepLength="0.1" laneChangeModel="LC2013" accel="3.5" decel="4.5" 𝑒𝑚𝑒𝑟𝑔𝑒𝑛𝑐𝑦𝐷𝑒𝑐𝑒𝑙="6.5" tau="1.5" minGap="1.5" speedControlGainCACC="-0.4" gapClosingControlGainGap="0.001" gapClosingControlGainGapDot="1.6" gapControlGainGap="0.45" gapControlGainGapDot="0.25" collisionAvoidanceGainGap="0.8" collisionAvoidanceGainGapDot="0.23"

**Comment by namdre** [comment]
Have you tried with the original parameters of the authors: https://github.com/eclipse/sumo/blob/6606ae487976349bb7988a52c1962d63e391852e/src/microsim/cfmodels/MSCFModel_CACC.cpp#L57-L64 ?

I'm pretty sure that there are areas of the configuration space where the CACC model is not driving safely and you might just have hit upon such an area.

**Comment by zaheenSyed** [comment]
I have actually been trying with the original parameters and my simulation network is a simple segment of Highway. For similar scenario Krauss, IDM and ACC are performing better than CACC. and for default Gain the TTC count were very high. After changing the gain I now get better result but the warning still pop.

How do I make sure that if my configuration space is not suitable for the cacc model. Can you point to any document discussing this issue of unsafe CACC parameters.

**Comment by namdre** [comment]
> How do I make sure that if my configuration space is not suitable for the cacc model. Can you point to any document discussing this issue of unsafe CACC parameters.

Unfortunately, I'm not aware of any study on this topic.
 As far as I know, the parameters were calibrated to a specific data set and the model behavior with other parameters has not been validated. 
My own maintenance of the model code has been restricted to fixing "obvious" bugs like #9831.

You may get more details from the original authors of the model (https://scholar.google.com/citations?user=rw3HFL4AAAAJ&hl=en, https://ieeexplore.ieee.org/author/37088754163)
Unfortunately, they are no longer active in the SUMO community so they will not be reading here and I don't have any current contact details either.
