### ISSUE TITLE
durouter will delete unexpect edge when remove loop

### ISSUE THREAD

**Issue by songjianbupt** [eclipse/sumo#9837]
in src/router/ROHelper.cpp:recheckForLoops
assume a complete route is like blow
4_5,5_6,6_12,12_13,13_5,5_6,6_8,8_22,22_11,11_12,12_13
where the number represents a junction,4_5 means the road from junction 4 to junction 5
in the original code, the output is 4_5,5_6,6_8,12_13.the 22_11,11_12 will be deleted so that the route is incomplete

here is a possible fix

`diff --git a/src/router/ROHelper.cpp b/src/router/ROHelper.cpp`
`index 51a5d5c..9f2a765 100644`
`--- a/src/router/ROHelper.cpp`
`+++ b/src/router/ROHelper.cpp`
`@@ -41,15 +41,23 @@ recheckForLoops(ConstROEdgeVector& edges, const ConstROEdgeVector& mandatory) {`
`     // XXX check for departLane, departPos, departSpeed, ....`

`     // removal of edge loops within the route (edge occurs twice)`

`-    std::map<const ROEdge*, int> lastOccurence; // index of the last occurence of this edge`
`-    for (int ii = 0; ii < (int)edges.size(); ++ii) {`
`-        std::map<const ROEdge*, int>::iterator it_pre = lastOccurence.find(edges[ii]);`
`-        if (it_pre != lastOccurence.end() &&`
`-                noMandatory(mandatory, edges.begin() + it_pre->second, edges.begin() + ii)) {`
`-            edges.erase(edges.begin() + it_pre->second, edges.begin() + ii);`
`-            ii = it_pre->second;`
`-        } else {`
`-            lastOccurence[edges[ii]] = ii;`
`+    int finished = 0;`
`+    while (finished != 1) {`
`+        std::map<const ROEdge*, int> lastOccurence; // index of the last occurence of this edge`
`+        int ii = 0;`
`+        for (; ii < (int)edges.size(); ++ii) {`
`+            std::map<const ROEdge*, int>::iterator it_pre = lastOccurence.find(edges[ii]);`
`+            if (it_pre != lastOccurence.end() &&`
`+                    noMandatory(mandatory, edges.begin() + it_pre->second, edges.begin() + ii)) {`

`+                edges.erase(edges.begin() + it_pre->second, edges.begin() + ii);`
`+                ii = it_pre->second;`
`+                break;`
`+            } else {`
`+                lastOccurence[edges[ii]] = ii;`
`+            }`
`+        }`
`+        if (ii == (int)edges.size()) {`
`+            finished = 1;`
`         }`
`     }`

 
---
*If possible, upload an example that shows your problem.*

**SUMO-version:**
1.10.0
**operating system:**
ubuntu20.04

**Comment by namdre** [comment]
Thanks!
