### ISSUE TITLE
HOW CAN I RESTRICT THE LOCATION OF FCD output?

### ISSUE THREAD

**Issue by monasabeti** [eclipse/sumo#9839]
@namdre 
Hello namdre;
First, I thank you for quick and useful guidance .
Sorry to get your time again.

Lets imagine that this is the motorway and I get  a FCD output of this motorway. I want to extract the number of passing vehicle befor and after every highway exit, and also extract how many vehicle exit and enter the highway on each exit.

 
![Capture](https://user-images.githubusercontent.com/43193011/146935794-0de5d4cf-ed54-4d97-979a-4205a5540d3a.PNG)

Now my question is that, how can I restrict the locations like the picture above that FCD output can be restricted to a specific set of edges by loading a list of edges from a file with option --fcd-output.filter-edges.input-file <FILE>.

 so how should I define the list of edges which matches exactly with the real edges where I want to define for the real motorway?
i access to the real data of the motorway

Best regards,
MONA

**Comment by namdre** [comment]
Use netedit selection mode to select all the needed edges and then use the button 'save selection'. The saved file can be used as input for filter-edges.input-file

**Comment by monasabeti** [comment]
this is my configuration file:
![Capture](https://user-images.githubusercontent.com/43193011/146953838-61623d18-0ba3-408d-ba04-44df007c525d.PNG)
and when i run the .sumocfg  during the definition time interval i just see the blank page like this:
![Capture](https://user-images.githubusercontent.com/43193011/146955114-1edd17ed-77bd-4ec6-a353-7b580ed0549e.PNG)
and the highway is not fully populated with vehicles.
and when try to open in netedit from sumo i face with this problem:
![Capture](https://user-images.githubusercontent.com/43193011/146955318-c25820b4-1f19-4506-b5ff-788174277f9c.PNG)
and these are files which i access to and create my config file: 
![Capture](https://user-images.githubusercontent.com/43193011/146955703-8466aa76-51e8-4cbe-ab3d-513f3068b698.PNG)

**Comment by namdre** [comment]
The error message when starting netedit suggests that you are using an outdated sumo version.

**Comment by monasabeti** [comment]
@namdre 
Hello;
when i define the list of edge as a filter like this:
![Capture](https://user-images.githubusercontent.com/43193011/147228548-a54a0043-3a57-43f7-adda-c5ef38333f57.PNG)
how should i apply this filter to the fcd output with option --fcd-output.filter-edges.input-file <FILE>
in file i put the file of the selected edge as a filter: edge_selected_for_filter.txt
and instead of fcd-output i put my fcd output file:output_sunday.fcd.xml
i face with this error:
![Capture](https://user-images.githubusercontent.com/43193011/147230061-4c24d562-ff61-4b4d-ade2-6a1e90e83110.PNG)

**Comment by namdre** [comment]
put this in your sumocfg (configuration file)
```
<fcd-output value="output_sunday.fcd.xml"/>
<fcd-output.filter-edges.input-file value="edge_selected_for_filter.txt"/>
```

**Comment by monasabeti** [comment]
@namdre 
 thanks alot for your respond.

Happy Christmas

**Comment by TrinhTuanHung2021** [comment]
> @namdre thanks alot for your respond. when i add this command to my configuration file like this:
> 
> ![Capture1](https://user-images.githubusercontent.com/43193011/147385192-fac805c2-84bc-4e0f-a07a-933d002d5f50.PNG)
> 
> i face with this problem:
> 
> ![Capture](https://user-images.githubusercontent.com/43193011/147385207-6e2948d6-9f87-4294-a9d6-0d359b762124.PNG)
> 
> Happy Christmas

Hello? Do you fix it?

**Comment by namdre** [comment]
Upgrade sumo. Most likely you are using an older version that did not support this option.
