### ISSUE TITLE
SUMO on Ubuntu 20.04.2 ARM64

### ISSUE THREAD

**Issue by fblamanna** [eclipse/sumo#9841]
Hi all, I am trying to install SUMO 1.11 on Ubuntu 20.04.2 ARM64 on a Virtual Machine within Parallels on Apple M1. 

I notice some issues as:

1) Sumo version is 1.4;
2) SUMO can’t run osmWebWizard (missing proj) automatically (need to install it with pip3);
3) SUMO can’t find the Sumo data folder with the generated scenario after running osmWebWizard.py.
  
I am still trying it, does anyone already tried it on this platform? Apart from the minor issues, I am concerned about the compatibility of the most recent 1.11 version and the (older ?) 1.4 on ARM64.

Thanks

**Comment by behrisch** [comment]
Hi
1. 1.4 was the most recent version when ubuntu 20.04 was released, if you need a newer version use our ppa: https://sumo.dlr.de/docs/Downloads.php#linux_binaries If this does not have an ARM64 build please give feedback we might need to switch it on somewhere.
2. Can you give more details here: you needed to do `pip3 install pyproj`?
3. Can you post the precise error message and check whether the environment variable SUMO_HOME is set?

**Comment by fblamanna** [comment]
Hi thanks for your support.

1) I did 
$ sudo add-apt-repository ppa:sumo/stable
$ sudo apt-get update
$ sudo apt-get install sumo sumo-tools sumo-doc

and get:
sumo is already the newest version (1.4.0+dfsg1-1).
sumo-doc is already the newest version (1.11.0-1).
sumo-tools is already the newest version (1.11.0-1).

2) 
parallels@ubuntu-linux-20-04-desktop:~$ pip3 install pyproj
Requirement already satisfied: pyproj in /usr/lib/python3/dist-packages (2.5.0)

3) this is what happened after launching osmWebWizard.py:

```
parallels@ubuntu-linux-20-04-desktop:/usr/share/sumo/tools$ python3 osmWebWizard.py 
Cannot create directory '/usr/share/sumo/tools/2021-12-22-11-24-29'
Building scenario in '/home/parallels/Sumo/2021-12-22-11-24-29'
Downloading map data
200 OK
Converting map data
Written configuration to 'osm.netccfg'
Loading configuration ... done.
Error: Cannot import network data without PROJ-Library. Please install packages proj before building sumo
Quitting (on error).
Written configuration to 'osm.polycfg'
Loading configuration ... done.
Error: Could not open net-file 'osm.net.xml'.
Quitting (on error).
Traceback (most recent call last):
  File "/usr/share/sumo/tools/sumolib/net/__init__.py", line 825, in readNet
    parse(gzip.open(filename), netreader)
  File "/usr/lib/python3.8/gzip.py", line 58, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/usr/lib/python3.8/gzip.py", line 173, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/home/parallels/Sumo/2021-12-22-11-24-29/osm.net.xml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "osmWebWizard.py", line 487, in build
    builder.build()
  File "osmWebWizard.py", line 296, in build
    self.edges = sumolib.net.readNet(os.path.join(self.tmp, self.files["net"])).getEdges()
  File "/usr/share/sumo/tools/sumolib/net/__init__.py", line 827, in readNet
    parse(filename, netreader)
  File "/usr/lib/python3.8/xml/sax/__init__.py", line 33, in parse
    parser.parse(source)
  File "/usr/lib/python3.8/xml/sax/expatreader.py", line 105, in parse
    source = saxutils.prepare_input_source(source)
  File "/usr/lib/python3.8/xml/sax/saxutils.py", line 365, in prepare_input_source
    f = urllib.request.urlopen(source.getSystemId())
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 509, in open
    req = Request(fullurl, data)
  File "/usr/lib/python3.8/urllib/request.py", line 328, in __init__
    self.full_url = url
  File "/usr/lib/python3.8/urllib/request.py", line 354, in full_url
    self._parse()
  File "/usr/lib/python3.8/urllib/request.py", line 383, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/home/parallels/Sumo/2021-12-22-11-24-29/osm.net.xml'

Recovering
Recovering
Recovering
```
the variable is set to:

`export SUMO_HOME="/usr/share/sumo"`

**Comment by behrisch** [comment]
Thank you, it seems the ppa does not contain an ARM64 build and furthermore the old ubuntu build has not even proj support so it won't work for you. I will try to add an ARM64 build for the ppa. Concerning pyproj. Do you remember which exact module complained about missing pyproj?

**Comment by fblamanna** [comment]
Thanks again. I don't remember but it was related to the first osmWebWizard.py launch. After installing pyproj, the wizard worked, it opened the browser and generated the scenario (apart for the above issues).

Let me know when an ARM64 build will be added, so I can continue testing the 1.11 version there.

**Comment by behrisch** [comment]
I found the checkbox ;-) thanks to https://askubuntu.com/questions/371339/how-to-create-ppa-packages-for-arm-or-powerpc-in-launchpad. You can check the progress of the build here: https://launchpad.net/~sumo/+archive/ubuntu/stable/+packages

**Comment by fblamanna** [comment]
> I found the checkbox ;-) thanks to https://askubuntu.com/questions/371339/how-to-create-ppa-packages-for-arm-or-powerpc-in-launchpad. You can check the progress of the build here: https://launchpad.net/~sumo/+archive/ubuntu/stable/+packages

Thanks - after build, the following

`$ sudo add-apt-repository ppa:sumo/stable
$ sudo apt-get update
$ sudo apt-get install sumo sumo-tools sumo-doc`

should find the right ARM64 version?

**Comment by behrisch** [comment]
it had some more hiccups but now it should have a proper arm and ppc build
