### ISSUE TITLE
The number of lanes is incorrect

### ISSUE THREAD

**Issue by zhaotuo0815** [eclipse/sumo#9845]
hello, sumo developer, when I use netconvert (netconvert 
                  --geometry.min-radius.fix
                  --geometry.remove
                  --output.street-names true
                  --tls.guess.joining true
                  --osm-files foshan.osm) turn osm files into net.xml file,  the number of lanes is incorrect and i found that different lane numbers of the same edge type,  a
![wrong](https://user-images.githubusercontent.com/59630993/147090895-2242687f-54d8-4edf-8150-e45c20bbefa6.png)
s shown below

**Comment by behrisch** [comment]
The number of lanes specified by the edge type is overridden if a precise number is given in OSM. So please inspect your OSM file. If you still think the number is wrong try to attach the zipped OSM to this ticket or find another way to share it.

**Comment by zhaotuo0815** [comment]
> The number of lanes specified by the edge type is overridden if a precise number is given in OSM. So please inspect your OSM file. If you still think the number is wrong try to attach the zipped OSM to this ticket or find another way to share it.
Thanks for your reply, this is the osm file 
[foshan.zip](https://github.com/eclipse/sumo/files/7766010/foshan.zip)

**Comment by behrisch** [comment]
Can you please give the edge id together with the expected number of lanes and the number of lanes SUMO generates.

**Comment by zhaotuo0815** [comment]
> Can you please give the edge id together with the expected number of lanes and the number of lanes SUMO generates.

the edge id is "42314307#6", which type is highway.primary, the expected number of lanes is 6 but the number of lanes SUMO generated is 2

**Comment by namdre** [comment]
The lane number is set to 2 in the OSM data: https://www.openstreetmap.org/way/42314307
You could patch this with additional input (https://sumo.dlr.de/docs/Tutorials/ScenarioGuide.html#modifying_the_network) or log in to openstreetmap.org and correct the error there.

**Comment by zhaotuo0815** [comment]
thank you so much



发自我的iPhone


------------------ Original ------------------
From: Jakob Erdmann ***@***.***&gt;
Date: Fri,Dec 24,2021 6:11 AM
To: eclipse/sumo ***@***.***&gt;
Cc: zhao tuo ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [eclipse/sumo] The number of lanes is incorrect (Issue #9845)





 
The lane number is set to 2 in the OSM data: https://www.openstreetmap.org/way/42314307
 You could patch this with additional input (https://sumo.dlr.de/docs/Tutorials/ScenarioGuide.html#modifying_the_network) or log in to openstreetmap.org and correct the error there.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
