### ISSUE TITLE
How to import into SUMo after matlab calculates the speed of each car at each moment

### ISSUE THREAD

**Issue by MrHUANHUHAN** [eclipse/sumo#9846]
How to import into SUMo after matlab calculates the speed of each car at each moment

**Comment by namdre** [comment]
remote-control vehicles using traci.vehicle.setSpeed
if you need to override sumo safety features, call traci.vehicle.setSpeedMode(vehID, 0) once for each vehicle.
see https://sumo.dlr.de/docs/TraCI.html
