### ISSUE TITLE
How to define capacity for a lane?

### ISSUE THREAD

**Issue by shai1111111** [eclipse/sumo#9847]
hello!
I would like to ask how to set the road capacity of the two sections in the figure below while keeping the speed limit unchanged？
![1](https://user-images.githubusercontent.com/96578818/147241246-c627ee8e-feec-4f70-90cb-6a24b8319f3a.png)

**Comment by shai1111111** [comment]
![2](https://user-images.githubusercontent.com/96578818/147241831-a4efe5f0-5b8b-4d60-8c28-ef99026684c8.png)
for example

**Comment by namdre** [comment]
The road capacity is an emergent property of the carFollowModel and it's parameters together with lane count and speed limit. You cannot set the capacity directly, only calibrate your model parameters.

The default model capacity is around 2000 veh/hour/lane  though you need to be careful with insertion options to achieve this flow at vehicle insertion (i.e. departSpeed="speedLimit", --extrapolate-departpos). See https://sumo.dlr.de/docs/Simulation/VehicleInsertion.html

In your case I'd set the lane number to 2 for O-N and to 1 for N-D.
The simplest way to reduce capacity to 1000 veh/hour/lane is to set 'tau' (the desired time headway between vehicles). to ~2.7
(using the default Krauss model with all other parameters left at their defaults).

**Comment by shai1111111** [comment]
您的邮件我已收到，我会尽快处理，谢谢！

**Comment by shai1111111** [comment]
> The road capacity is an emergent property of the carFollowModel and it's parameters together with lane count and speed limit. You cannot set the capacity directly, only calibrate your model parameters.
> 
> The default model capacity is around 2000 veh/hour/lane though you need to be careful with insertion options to achieve this flow at vehicle insertion (i.e. departSpeed="speedLimit", --extrapolate-departpos). See https://sumo.dlr.de/docs/Simulation/VehicleInsertion.html
> 
> In your case I'd set the lane number to 2 for O-N and to 1 for N-D. The simplest way to reduce capacity to 1000 veh/hour/lane is to set 'tau' (the desired time headway between vehicles). to ~2.7 (using the default Krauss model with all other parameters left at their defaults).
Thank you for your reply, which is very helpful to me！
