### ISSUE TITLE
how to set first in first out rule for a flow?

### ISSUE THREAD

**Issue by shai1111111** [eclipse/sumo#9850]
![微信截图_20211227181605](https://user-images.githubusercontent.com/96578818/147462138-9688cab3-f0dd-4ec0-ab2e-d6e2eab88257.png)
in such a case, how to set first-in-first-out rule for the flow,  that is, no overtaking behavior?

Or another way, two road sections are single lane. How to set different car following models for each road section?

**Comment by namdre** [comment]
1. Zipper merge: https://sumo.dlr.de/docs/Networks/PlainXML.html#node_types
2. https://sumo.dlr.de/docs/Simulation/Calibrator.html#calibrating_vehicle_types

**Comment by shai1111111** [comment]
>

**Comment by shai1111111** [comment]
> 1. Zipper merge: https://sumo.dlr.de/docs/Networks/PlainXML.html#node_types
> 2. https://sumo.dlr.de/docs/Simulation/Calibrator.html#calibrating_vehicle_types

**Comment by shai1111111** [comment]
I want to realize first in first out on the whole road section, that is, there is no overtaking behavior on the whole road section

**Comment by namdre** [comment]
can you prohibit lane changing for some or all vehicle classes using 'changeLeft' and 'changeRight':  https://sumo.dlr.de/docs/Networks/PlainXML.html#lane-specific_definitions
