### ISSUE TITLE
How to set left turn waiting area

### ISSUE THREAD

**Issue by zhaotuo0815** [eclipse/sumo#9852]
hello, sumo develop
![left_turn_](https://user-images.githubusercontent.com/59630993/147618728-ac830f14-834e-494a-a5bd-62112fc0625d.jpg)
er, my question is that how to set left turn waiting area, like the picture

**Comment by namdre** [comment]
The waiting area will be created automatically if the traffic light cycle contains a permissive (unprotected) left turn.
Use connection attribute 'contPos' to configure the distance between the stop line and the waiting area.

**Comment by zhaotuo0815** [comment]
thank you so much



发自我的iPhone


------------------ Original ------------------
From: Jakob Erdmann ***@***.***&gt;
Date: Wed,Dec 29,2021 7:15 PM
To: eclipse/sumo ***@***.***&gt;
Cc: zhao tuo ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [eclipse/sumo] How to set left turn waiting area (Issue #9852)





 
The waiting area will be created automatically if the traffic light cycle contains a permissive (unprotected) left turn.
 Use connection attribute 'contPos' to configure the distance between the stop line and the waiting area.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by JackYang2022** [comment]
@namdre hello，what should I do if I want vehicles stop in left turn waiting area until the left turn(protected) phase.

**Comment by namdre** [comment]
By default, there is a permissive green phase where left turning vehicles may pass though a gap in oncoming traffic. If you want vehicles to always wait for the protected phase, then have the left-turning lights stay red until that phase.

**Comment by JackYang2022** [comment]
> By default, there is a permissive green phase where left turning vehicles may pass though a gap in oncoming traffic. If you want vehicles to always wait for the protected phase, then have the left-turning lights stay red until that phase.

Thank you for your reply！But，if I  have the left-turning lights stay red until the protected phase，left turning vehicles will not enter the  left turn waiting area when straight light stay green. I want vehicles enter the left turn waiting area when the straight light is green，and turn left once the left turn protected phase beginning. How should I set it up？Thanks.

**Comment by namdre** [comment]
Understood. In this case, do the following: 

1. in netedit, use traffic light mode, click on the traffic light in question and press the button 'Add States'
2. set connection attribute 'linkIndex2' to the newly created index (the highest index previously used +1)
3. define new states for the new index

This index now controls the behavior of vehicles at the waiting area. You can set it to red before the protected phase starts and then have it turn major  green ('G') and yellow at the same time that the left turn has the protected phase.

**Comment by JackYang2022** [comment]
> Understood. In this case, do the following:
> 
> 1. in netedit, use traffic light mode, click on the traffic light in question and press the button 'Add States'
> 2. set connection attribute 'linkIndex2' of the left turn connection to the newly created index (the highest index previously used +1), see https://sumo.dlr.de/docs/Netedit/neteditUsageExamples.html#setting_connection_attributes
> 3. define new states for the new index
> 
> This index now controls the behavior of vehicles at the waiting area. You can set it to red before the protected phase starts and then have it turn major green ('G') and yellow at the same time that the left turn has the protected phase.

Thank you sir! I solved the problem by referring to your steps.
