### ISSUE TITLE
Roadside parking lane change problem

### ISSUE THREAD

**Issue by WillianmK1** [eclipse/sumo#9853]
Hi, I have a problem here. I sincerely want to ask for help.
Now there is a demand for roadside parking, which is controlled by Traci's setstop. During operation, vehicles will change lanes or stop moving ahead in advance, resulting in congestion due to conflict with roadside vehicles.

![1(1)](https://user-images.githubusercontent.com/96803815/147621446-7b880188-d97e-433c-aa44-c2cdc46901e3.png)

For example, the part drawing the red box wants to park in the parking space in front of the right, but it will change lanes in advance.
Why and how can this be improved?  looking forward to your reply

**Comment by namdre** [comment]
Lane changing for parking is "strategic" and it's urgency is influenced by traffic density on the target lane. 
You can override the default lane changing behavior by either using `vehicle.setLaneChangeMode' (https://sumo.dlr.de/docs/TraCI/Change_Vehicle_State.html#lane_change_mode_0xb6) or by configuring vType attribute lcStrategic.

**Comment by namdre** [comment]
Please re-open if there are further questions on this topic.
