### ISSUE TITLE
How to ignore some vehicles when aggregate measurements?

### ISSUE THREAD

**Issue by thinker310** [eclipse/sumo#9854]
Hello, I wonder how to ignore some vehicles when aggregate measurements. For example, when I use Lane- or Edge-based Traffic Measures, I want to ignore data on vehicle with id 'flow5.3', (because the vehicle stop on the road all the time, the travel time in the output file is very large). So how to achieve it? Thank you!

**Comment by namdre** [comment]
laneData and edgeData support attribute 'vTypes' for including a specific list of vehicle types in the aggregation. All other vTypes are filtered out.
