### ISSUE TITLE
Is there a way to make the vehicle behave exactly the same on all trials?

### ISSUE THREAD

**Issue by Shimizu-Masayuki** [eclipse/sumo#9856]
Add your issue description here.
  Hello, I am currently doing research on route finding for avoiding traffic congestion using FLOW and SUMO. However, in the current SUMO environment, even if the vehicle's route is the same for all trials, the vehicle's behavior can be slightly different for each trial (for example, the arrival time can be slightly different for each trial even if the route is the same). Is there any way to make the behavior of the vehicle exactly the same for all trials?
Thank you very much!

---
*If possible, upload an example that shows your problem.*

**SUMO-version:**
SUMO Version　v1_1_0+0000-2147d155b1
**operating system:**
ubuntu18.04

**Comment by namdre** [comment]
Having repeatable results is the default behavior for SUMO. The only way to have different results in every run while keeping all inputs and options the same is the use of option **--random** (see https://sumo.dlr.de/docs/Simulation/Randomness.html).
If you look into any xml output file of sumo it will contain all the active simulation options so you can easily check if this option was used.

**Comment by Shimizu-Masayuki** [comment]
Thanks for your reply!
I looked into it and found that FLOW has a setting to add randomness to the behavior of vehicles, and commenting out that part solved the problem.
