### ISSUE TITLE
lanechange.duration value = “5”   

### ISSUE THREAD

**Issue by emotion68** [eclipse/sumo#9858]
lanechange.duration value = “5”   
What does this value of 5 mean? 
Is it under the condition that the vehicle is forced to change lanes. If the vehicle cannot change lanes within the simulation step of 5, it will not execute the command for this forced lane change?

**Comment by namdre** [comment]
Yes. The change command only remains active for the given duration. Afterwards the vehicle reverts to it's default behavior.

**Comment by emotion68** [comment]
> Yes. The change command only remains active for the given duration. Afterwards the vehicle reverts to it's default behavior.
The purpose of my research is to change lanes in two consecutive sections of the road. In the first section, I was forced to change lanes, and in the second section, I was ordered to use the lane-changing model 1621, but I have a few problems.
First: how much should I set the value in command of lanechange.duration value
Second: If it exceeds the value value, if it has not been forced to change lanes by me, will my forced lane change command be executed later?
Third: Within the value value, if I have not executed my forced lane change command at the end of the first section, do I have to stop and wait until the value ends?

**Comment by emotion68** [comment]
> Yes. The change command only remains active for the given duration. Afterwards the vehicle reverts to it's default behavior.
The purpose of my research is to change lanes in two consecutive sections of the road. In the first section, I was forced to change lanes, and in the second section, I was ordered to use the lane-changing model 1621, but I have a few problems.
First: how much should I set the value in command of lanechange.duration value
Second: If it exceeds the value value, if it has not been forced to change lanes by me, will my forced lane change command be executed later?
Third: Within the value value, if I have not executed my forced lane change command at the end of the first section, do I have to stop and wait until the value ends?

**Comment by emotion68** [comment]
> 是的。更改命令仅在给定的持续时间内保持活动状态。之后，车辆恢复到其默认行为。

https://github.com/eclipse/sumo/issues/9858#issuecomment-1002557835

**Comment by namdre** [comment]
1. If there is no surrounding traffic that can obstruct lane changing, simply set this to 1 (or to whatever your step-length is if you are using sumo option **--step-length**)
2. the changeLane command will have no effect after the given duration has passed (if that's what you meant)
3. no. The vehicle will just keep driving if the lane change cannot be executed.
