### ISSUE TITLE
Is there a way to get traffic light information from opendrive file?

### ISSUE THREAD

**Issue by parksanha** [eclipse/sumo#9860]
Hello.

When converting "opendrive" file to "sumo network" using "netconvert", is there a way to bring traffic light information as well?

I would like to know whether a node is an intersection or not, and if it is possible to convert information about traffic light as well.

Thank you very much for always answering my questions in detail.

**Comment by namdre** [comment]
The junction type (traffic_light or something else) should already be imported. However, additional controller information is currently not imported (#2365)
Is this something you would need?

**Comment by namdre** [comment]
closing for lack of reply
