### ISSUE TITLE
Is it possible to define not only the departure time but also the arrival time of the vehicle in demand modeling?

### ISSUE THREAD

**Issue by parksanha** [eclipse/sumo#9861]
I learned about demand modeling from the two links below.
But I don't have the information I want, so I'm asking.

https://sumo.dlr.de/docs/Demand/Introduction_to_demand_modelling_in_SUMO.html
https://sumo.dlr.de/docs/Definition_of_Vehicles%2C_Vehicle_Types%2C_and_Routes.html

Is there a way to set the departure time and route of the vehicle as well as the arrival time?
If I have information about which vehicle departs and when it arrives, can I simulate it through sumo as it is?

**Comment by behrisch** [comment]
The arrival time is a result of the simulation since it depends on the chosen route and the traffic situation. There is no point (and hence no way) to define it in advance.

**Comment by namdre** [comment]
At best you could try to calibrate your simulation so that it replicates known arrival times.

**Comment by parksanha** [comment]
@behrisch @namdre 

Thank you very much for answering my question.
