### ISSUE TITLE
edge capacity and the minimum following distance of carfollowing-Krauss 

### ISSUE THREAD

**Issue by Transtars** [eclipse/sumo#9869]
Dear all，

I want to know the traffic capacity of the edge, so I plan to use the minimum following distance and the average vehicle length to calculate, but I don't know what is the minimum following distance of the following model? Can someone tell me if SUMO has defined capacity? Or what is the minimum following distance for Carfollowing-Krauss?

Thank you for your time.

**Comment by namdre** [comment]
see https://sumo.dlr.de/docs/Simulation/RoadCapacity.html

**Comment by Transtars** [comment]
@namdre Thank you for your answer！
