### ISSUE TITLE
write documentation on road capacity and headways

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#9870]

**Comment by namdre** [comment]
tools are stored at http://ts-sim-service-ba/svn/simo/trunk/projects/sumo/tools/theory

**Comment by namdre** [comment]
turn this into a complex test

**Comment by behrisch** [comment]
I think we should either add another table or make more explicit that the present table is only about _insertion_ because the initial part of the document does not mention that at all. @namdre What do you think?

**Comment by namdre** [comment]
If you have ideas for creating another table, I don't mind. 
Insertion is usually the limiting factor on observing the maximum capacity. The maximum values from the insertion table should  already come very close to the "real" maximum capacity.
If you try to use on-ramps or regular intersections for increasing flow, you will typically introduce additional speed reductions which reduce the observed capacity.

Feel free to add wording that conveys this (-:
