### ISSUE TITLE
osmWebWizard error

### ISSUE THREAD

**Issue by tanzeelarubab** [eclipse/sumo#9871]
Add your issue description here.
  
amjad@amjad-Inspiron-N4050:~/sumo/tools$ python osmWebWizard.py
Building scenario in '/home/amjad/sumo/tools/2022-01-04-05-13-21'
Downloading map data
504 Gateway Timeout
Converting map data
usage: osmWebWizard.py [-h] [-c FILE] [-C FILE] [--save-template FILE]
                       [-p PREFIX] [-f OSM_FILE] [-m TYPEMAP]
                       [--netconvert-typemap NETCONVERT_TYPEMAP]
                       [-o OLDAPI_PREFIX] [-t TILES]
                       [--vehicle-classes VEHICLE_CLASSES]
                       [-d OUTPUT_DIRECTORY] [-n NETCONVERT_OPTIONS]
                       [--pedestrians] [-y POLYCONVERT_OPTIONS]
osmWebWizard.py: error: typemap file "/home/sumo/data/typemap/osmPolyconvert.typ.xml" not found

*If possible, upload an example that shows your problem.*

**SUMO-version:**
sumo Version 1.11.0

**operating system:**
Ubuntu 20.04.3 LTS

**Comment by namdre** [comment]
- downloading the map data failed (most likely you need to select a smaller area)
- it looks as if your SUMO_HOME folder was set incorrectly to `/home/sumo` whereas it should probably be set to `/home/amjad/sumo`.

**Comment by tanzeelarubab** [comment]
amjad@amjad-Inspiron-N4050:~$ cd sumo/tools
amjad@amjad-Inspiron-N4050:~/sumo/tools$ python osmWebWizard.py
Traceback (most recent call last):
  File "osmWebWizard.py", line 550, in <module>
    args.address, args.port, OSMImporterWebSocket)
  File "/home/amjad/sumo/tools/webWizard/SimpleWebSocketServer.py", line 595, in __init__
    self.serversocket.bind((host, port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
. i change my path. and execute the command . i face the error

**Comment by namdre** [comment]
you still have a webWizard process running that needs to be killed.

**Comment by tanzeelarubab** [comment]
you means start a new terminal?

**Comment by tanzeelarubab** [comment]
thanks a lot sir. my issue resolves
