### ISSUE TITLE
Possible bug in driving error calculation in EIDM

### ISSUE THREAD

**Issue by quajak** [eclipse/sumo#9878]
I was looking at the code for the EIDM and the calculation of the driving error seems incorrect. https://github.com/eclipse/sumo/blob/6288a2914ff7eec24ed2aa65d9eefede453e3398/src/microsim/cfmodels/MSCFModel_EIDM.cpp#L777-L791
Either all the cases following the first two (`>= 0.5` and `< 0.5`) are not needed or the order of the else if cases should be reversed.

**Comment by namdre** [comment]
paging @Domsall

**Comment by Domsall** [comment]
You are absolutely right. I will change this next week when I am back in office. I will also check the changed results, if they still make sence with the current parameters.

**Comment by Domsall** [comment]
I created a pull request with the patch. After the patch has been merged, you can download the newest git-version.
Please check if it works as intended now.

**Comment by namdre** [comment]
If it doesn't work as intended, please reopen the ticket.

**Comment by quajak** [comment]
Thanks for fixing it.
