### ISSUE TITLE
netconvert import from OSM with a bounding box

### ISSUE THREAD

**Issue by fulldeck** [eclipse/sumo#9881]
Add your issue description here.
I have down loaded osm file https://download.geofabrik.de/north-america/canada/alberta-latest.osm.bz2 from https://download.geofabrik.de/north-america/canada/alberta.html
I can convert then entire file in net format.  (took a bit of time) :)
netconvert --osm-files alberta-latest.osm -o alberta-latest.net.xml

Is there a way I can import an area using a bounding box using the same command line instruction? 

---
*If possible, upload an example that shows your problem.*

**SUMO-version:**
1.11.0

**operating system:**
MS Server 2016 - 32GB RAM 24CPU cores

![alberta](https://user-images.githubusercontent.com/33966660/148141324-23cd0116-626b-4b87-ae84-f09de3147bee.jpeg)

**Comment by namdre** [comment]
Yes. Use option **--keep-edges.in-boundary** or **--keep-edges.in-geo-boundary**
https://sumo.dlr.de/docs/netconvert.html#edge_removal
