### ISSUE TITLE
Questions about the "dir" attribute of connection

### ISSUE THREAD

**Issue by Shimizu-Masayuki** [eclipse/sumo#9882]
Hello.
I have a question about "dir", one of the attributes of a connection. Currently, the directions defined in Sumo are "s", "r", "R", "l", "L", "t", and "invalid". Among these, what criteria are "s", "r", "R", "l", and "L" assigned to?
I think they are assigned according to the angle, but I don't know the specific angle, so I'd like to know.
Also, if an edge is connected to six other edges, I think the same direction is assigned to the different edges, but is there any way to prevent this?
Thanks in advance.
  
---
**SUMO-version:**
v1_1_0+0000-2147d155b1
**operating system:**
ubuntu18.04

**Comment by namdre** [comment]
The directional assignment is based on the angle between incoming and outgoing edge and also the angle of neighboring outgoing edges. Having multiple outgoing edges with the same kind of directional arrow is intended (i.e. if multiple edges have an angle <= 6 degrees, they are all designated "straight"). 
The code is at https://github.com/eclipse/sumo/blob/87db14b482f3a58a90a97d6c5c14de148efaa5cc/src/netbuild/NBNode.cpp#L2221
There is currently no way to overrule this direction assignment. 

Do you have a real-world intersection example where netconvert assigns unsuitable directions?

**Comment by Shimizu-Masayuki** [comment]
Thank you for your answer.
In my research, at each intersection, I distinguish the outgoing edges by direction. However, if I assign the same direction to multiple outgoing edges, the distinction between edges will not work, so I was considering how to assign different directions to all outgoing edges without duplication.

**Comment by namdre** [comment]
for a discussion of edge ordering, see #9859
