### ISSUE TITLE
Questions about vehicle behavior at intersections

### ISSUE THREAD

**Issue by Shimizu-Masayuki** [eclipse/sumo#9884]
Hello, I have a question about vehicle behavior at intersections. when I use maps imported with osm or created with netgenerate as is, vehicles collide at intersections. I have been using "contPos" and "prohibition" to deal with this. However, as the number of intersections increases, it is very difficult to write "prohibition" for every intersection. Is there any other way to prevent vehicle collisions at intersections other than what we are doing now?
Thank you very much for your help.

---
**SUMO-version:**
v1_1_0+0000-2147d155b1
**operating system:**
ubuntu18.04

**Comment by namdre** [comment]
It should almost never be necessary to add custom prohibitions to avoid collisions. The most likely (known) cause for junction collision is invalid location of internal junctions #4397 which can indeed be fixed with custom contPos.
However, this should still be a rare occurrence.

Or maybe you are using custom traffic light plans that happen to be unsafe?
Please provide a small example scenario in it's "raw" form where you are seeing collisions (preferably one small OSM example and one small netgenerate example).

**Comment by Shimizu-Masayuki** [comment]
Thanks for your reply.
I'll share the actual file I'm using. The network file was imported by osm and then simplified by myself.
Thank you very much for your help.
[sample_map.zip](https://github.com/eclipse/sumo/files/7821010/sample_map.zip)

**Comment by namdre** [comment]
Those inputs by themself do not allow me to reproduce any collision.
(running `sumo -n map2.net.xml -a routes4.rou.xml` works fine)

- what sumo options are you using?
- is traci involved?

**Comment by Shimizu-Masayuki** [comment]
I am using traci to run SUMO.

**Comment by Shimizu-Masayuki** [comment]
Sorry for the late reply.
I'm currently using FLOW, a deep reinforcement learning framework, and I can't provide the log of the traci command because "traci.start()" is not used. I'll paste the code for the relevant part.

`def start_simulation(self, network, sim_params):
        """Start a sumo simulation instance.

        This method performs the following operations:

        1. It collect the simulation step size and the emission path
           information. If an emission path is specifies, it ensures that the
           path exists.
        2. It also uses the configuration files created by the network class to
           initialize a sumo instance.
        3. Finally, It initializes a traci connection to interface with sumo
           from Python and returns the connection.
        """
        # Save the simulation step size (for later use).
        self.sim_step = sim_params.sim_step

        # Update the emission path term.
        self.emission_path = sim_params.emission_path
        if self.emission_path is not None:
            ensure_dir(self.emission_path)

        error = None
        for _ in range(RETRIES_ON_ERROR):
            try:
                # port number the sumo instance will be run on
                port = sim_params.port

                sumo_binary = "sumo-gui" if sim_params.render is True \
                    else "sumo"

                # command used to start sumo
                sumo_call = [
                    sumo_binary, "-c", network.cfg,
                    "--remote-port", str(sim_params.port),
                    "--num-clients", str(sim_params.num_clients),
                    "--step-length", str(sim_params.sim_step)
                ]

                # use a ballistic integration step (if request)
                if sim_params.use_ballistic:
                    sumo_call.append("--step-method.ballistic")

                # ignore step logs (if requested)
                if sim_params.no_step_log:
                    sumo_call.append("--no-step-log")

                # add the lateral resolution of the sublanes (if requested)
                if sim_params.lateral_resolution is not None:
                    sumo_call.append("--lateral-resolution")
                    sumo_call.append(str(sim_params.lateral_resolution))

                if sim_params.overtake_right:
                    sumo_call.append("--lanechange.overtake-right")
                    sumo_call.append("true")

                # specify a simulation seed (if requested)
                if sim_params.seed is not None:
                    sumo_call.append("--seed")
                    sumo_call.append(str(sim_params.seed))

                if not sim_params.print_warnings:
                    sumo_call.append("--no-warnings")
                    sumo_call.append("true")

                # set the time it takes for a gridlock teleport to occur
                sumo_call.append("--time-to-teleport")
                sumo_call.append(str(int(sim_params.teleport_time)))

                # check collisions at intersections
                sumo_call.append("--collision.check-junctions")
                sumo_call.append("true")

                # sumo_call.append("--fcd-output")
                # sumo_call.append("sumoTrace.xml")

                logging.info(" Starting SUMO on port " + str(port))
                logging.debug(" Cfg file: " + str(network.cfg))
                if sim_params.num_clients > 1:
                    logging.info(" Num clients are" +
                                 str(sim_params.num_clients))
                logging.debug(" Emission file: " + str(self.emission_path))
                logging.debug(" Step length: " + str(sim_params.sim_step))

                # Opening the I/O thread to SUMO
                self.sumo_proc = subprocess.Popen(
                    sumo_call,
                    stdout=subprocess.DEVNULL
                )

                # wait a small period of time for the subprocess to activate
                # before trying to connect with traci
                if os.environ.get("TEST_FLAG", 0):
                    time.sleep(0.1)
                else:
                    time.sleep(config.SUMO_SLEEP)
                traci_connection = traci.connect(port, numRetries=100)
                traci_connection.setOrder(0)
                traci_connection.simulationStep()

                return traci_connection
            except Exception as e:
                print("Error during start: {}".format(traceback.format_exc()))
                error = e
                self.teardown_sumo()
        raise error`

**Comment by namdre** [comment]
You could call
`traci._startTracing("traceFile.txt, "whatever", port, "default", False)` after `traci.connect`.

However, as unsafe situations may be unavoidable during training, you could also change the collision behavior to encourage safe driving by setting the sumo options
`--collision.action warn --collision.stoptime 300` (increasing the stoptime causes higher traffic delays and can thus impact your scoring)

**Comment by Shimizu-Masayuki** [comment]
I ran the simulation without traci, but a collision occurred. The image is attached.
![collision](https://user-images.githubusercontent.com/74395203/148522816-b2c4ad28-ce47-4715-9316-cc7711a9adb2.png)

**Comment by namdre** [comment]
This is most likely an instance of #4397.  Can you provide the exact simulation options that you used?
If the input files are different from the ones you already sent, can you send the new files as well?

**Comment by Shimizu-Masayuki** [comment]
I just called `sumo-gui -n map2.net.xml -a routes4.rou.xml` and didn't give any additional options. Also, I am using the same file I already sent you.

**Comment by namdre** [comment]
Thanks. I can confirm that this is an instance of #4397 which has now been fixed in the development version.
For obtaining this version, see https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_development_version
On Ubuntu, either build from the latest sources or use test.pypi.org (the pypi build will be updated during the night).

**Comment by Shimizu-Masayuki** [comment]
I'm sorry, but FLOW is not compatible with the latest version of SUMO, and I haven't been able to confirm which version it is compatible with. If you don't mind, could you tell me in which version the relevant part has been fixed?

**Comment by namdre** [comment]
The fix is from today (though the download page will only carry that version starting tomorrow)
You don't need to use an updated version of the 'sumo' application to make use of the fix.
It's enough if you use the latest dev version for reprocessing the .net.xml file: `netconvert -s old.net.xml -o new.net.xml`.

I think the warning in the FLOW documentation "WARNING: Flow is not currently compatible with the most up-to-date version of SUMO." may be outdated though.

**Comment by Shimizu-Masayuki** [comment]
In the modified version, the collisions that had been occurring before have been eliminated. However, collisions with vehicles that do not fit on the edge and extend into the intersection are still occurring.
![collsion2](https://user-images.githubusercontent.com/74395203/148648623-08e14eed-23f0-4971-ac83-017dbb092476.png)

**Comment by namdre** [comment]
This collision is an instance of #4431. The planned fix for this bug does require an updated version of SUMO. Hence it must be cleared up whether the compatibility issue has been resolved or is still an relevant. 
Can you test what happens when using sumo 1.11.0 with flow?

**Comment by Shimizu-Masayuki** [comment]
I'm sorry.
I can't test it right away. However, I remember that when I did it before, there was an error when using the traci command. The version of SUMO I am currently using with FLOW is v1_1_0+0000-2147d155b1, and FLOW uses that version's way of calling the traci command. However, the code for the traci part of the latest version is significantly different from the version I am currently using. Therefore, when I use the traci command I am currently using with the latest SUMO, I get an error.

**Comment by namdre** [comment]
Can you tell which TraCI command is causing the error along with the error message?

**Comment by namdre** [comment]
Issue #4431 is fixed and using the latest dev-version, your scenario runs without collisions.

**Comment by namdre** [comment]
Please re-open if you find more collisions.
