### ISSUE TITLE
I packaged SUMO as a Flatpak and would like to submit it to Flathub.

### ISSUE THREAD

**Issue by kevinsmia1939** [eclipse/sumo#9894]
Hello,

I successfully packaged SUMO as Flatpak for Linux distros.

In summary, Flatpak can build and distribute applications independently of what is installed on the host distro. So I do not have to make a separate package for other distros. It usually consumes more storage space than necessary as it bundles the required dependencies with it. 

The Flatpak manifest (which contains instructions to build SUMO) is here: https://github.com/kevinsmia1939/flathub/tree/org.eclipse.SUMO

I gave it the name "org.eclipse.SUMO" to conform to the reverse DNS naming scheme, but if you have another name in mind, let me know.
https://docs.flatpak.org/en/latest/conventions.html#application-ids

I will also upload it to Flathub, a software store for Flatpak. 
https://flathub.org/home
https://github.com/flathub

I have not built SUMO with Java yet, it complains that no javah executable is found. It does not look like javah exists in openjdk 17.

The package still missing metainfo.xml, I will create and submit it.

**Comment by kevinsmia1939** [comment]
SUMO tried to download extra packages when it found maven.
But flatpak-builder does not allow network connection when building package.
How can I disable this? Or pre-download it.
I set -DCHECK_OPTIONAL_LIBS=false but still try to download.
```
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-jar-plugin/2.3.1/maven-jar-plugin-2.3.1.pom
[WARNING] Failed to retrieve plugin descriptor for org.apache.maven.plugins:maven-jar-plugin:2.3.1: Plugin org.apache.maven.plugins:maven-jar-plugin:2.3.1 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-jar-plugin:jar:2.3.1
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-source-plugin/3.2.0/maven-source-plugin-3.2.0.pom
[WARNING] Failed to retrieve plugin descriptor for org.apache.maven.plugins:maven-source-plugin:3.2.0: Plugin org.apache.maven.plugins:maven-source-plugin:3.2.0 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-source-plugin:jar:3.2.0
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.5/maven-clean-plugin-2.5.pom
[WARNING] Failed to retrieve plugin descriptor for org.apache.maven.plugins:maven-clean-plugin:2.5: Plugin org.apache.maven.plugins:maven-clean-plugin:2.5 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-clean-plugin:jar:2.5
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/2.6/maven-resources-plugin-2.6.pom
[WARNING] Failed to retrieve plugin descriptor for org.apache.maven.plugins:maven-resources-plugin:2.6: Plugin org.apache.maven.plugins:maven-resources-plugin:2.6 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-resources-plugin:jar:2.6
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-compiler-plugin/3.1/maven-compiler-plugin-3.1.pom
[WARNING] Failed to retrieve plugin descriptor for org.apache.maven.plugins:maven-compiler-plugin:3.1: Plugin org.apache.maven.plugins:maven-compiler-plugin:3.1 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-compiler-plugin:jar:3.1
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-surefire-plugin/2.12.4/maven-surefire-plugin-2.12.4.pom
[WARNING] Failed to retrieve plugin descriptor for org.apache.maven.plugins:maven-surefire-plugin:2.12.4: Plugin org.apache.maven.plugins:maven-surefire-plugin:2.12.4 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-surefire-plugin:jar:2.12.4

```

**Comment by behrisch** [comment]
Thanks for your effort! In fact I would prefer a lower case name so org.eclipse.sumo. Concerning Java/Maven it is probably best to start completely without maven. This would still build the java bindings it just does not package them. Everything else would mean you need to basically prepackage the maven repository (the things you find in ~/.m2/repository in a local build) somehow. But I am not a real expert here Maybe @RobertHilbrich has a better idea about maven.

**Comment by behrisch** [comment]
PS: I never used flatpak before and we try to achieve the same distro independent linux package with our python package: https://pypi.org/project/eclipse-sumo/ Can you say something about the benefits / shortcomings of the two approaches?

**Comment by kevinsmia1939** [comment]
> PS: I never used flatpak before and we try to achieve the same distro independent linux package with our python package: https://pypi.org/project/eclipse-sumo/ Can you say something about the benefits / shortcomings of the two approaches?

Things that come to mind in general compare to pip is that Flatpak provide sandboxing, controlling the apps access to the host for security purpose. Flatpak bundle runtime or any other apps to provide customized work flow, you could bundle what ever tool in addition to SUMO like debugger, etc.  You can provide different branches like stable, testing, beta, etc for your apps. Integration with GUI software store, you can install SUMO with command line or GUI front end like GNOME software or Discover (KDE) for user friendliness.

Due to Flatpak sandboxed nature, what ever libraries or package you install through other means or exist in the host will not be seen by the Flatpak app automatically. But it is possible to use the flatpaked app to download them, like Firefox flatpak to download plugins for example.

**Comment by kevinsmia1939** [comment]
I change the name as requested. Also add a patch to disable maven.

**Comment by angelobanse** [comment]
@kevinsmia1939, take a look at: https://github.com/flathub/org.eclipse.sumo/issues/2

**Comment by behrisch** [comment]
@kevinsmia1939 This page https://flathub.org/apps/details/org.eclipse.sumo still shows 1.11.0. What can I do to update it?

**Comment by kevinsmia1939** [comment]
> @kevinsmia1939 This page https://flathub.org/apps/details/org.eclipse.sumo still shows 1.11.0. What can I do to update it?

Sorry for late reply, but I see that you fix it :)
