### ISSUE TITLE
NEMAController does not allow phase extensions on coordinated phases

### ISSUE THREAD

**Issue by mschrader15** [eclipse/sumo#9895]
As it stands, NEMAController does not check the extension timer of coordinated phases. This was a discussion point for us a while back.  

https://github.com/eclipse/sumo/blob/8cc7e1e86d7880cb5badf48a3785f6628ea94eb1/src/microsim/traffic_lights/NEMAController.cpp#L712

I propose that we change the logic slightly and enter the extension timer check if the `tlLogic` file indicates that "actuated coordinated" mode is desired.

This could be done in two ways:

1. Instead of `coordinate-mode` being a boolean: https://github.com/eclipse/sumo/blob/8cc7e1e86d7880cb5badf48a3785f6628ea94eb1/tests/sumo/basic/tls/NEMA/fixForceOff/input_additional.add.xml#L11  it should instead be an enumerated field with a choice for "actuated coordinated" or just "coordinated"

1. Another simple option would be to enter "actuated coordinated" mode anytime there is a non-zero extension timer on the coordinated phases.

@qichaow @namdre  thoughts?

**Comment by qichaow** [comment]
It would be nice if you can provide a reference to the coordinated phase extension (maybe a traffic signal controller manual?). It seems hard to keep the offset or coordination if you can extend the coordinated phases.

**Comment by mschrader15** [comment]
Very fair point @qichaow . I will work on trying to find documentation...

**Comment by mschrader15** [comment]
After internal discussion, closing this. Determined that its not necessary!
