### ISSUE TITLE
NEMALogic::nextPhase doesn't support phase skipping

### ISSUE THREAD

**Issue by mschrader15** [eclipse/sumo#9897]
As it stands, `NEMALogic` doesn't capture the behavior of our traffic signals in the field. The crux of the issue is the nextPhase algorithm.

https://github.com/eclipse/sumo/blob/8cc7e1e86d7880cb5badf48a3785f6628ea94eb1/src/microsim/traffic_lights/NEMAController.cpp#L874-L892

Our traffic lights perform phase skipping. The algorithm should check the status of actuating detectors and proceed to the next sequential phase that has an **active detector**. The detector "calls" can be latching or non-latching depending on the configuration. Phases are "forced" to be served in the cycle through use of recalls (whether hard, maximum, or soft), which basically work as pre-programmed detector calls. A good summary document is here: https://nacto.org/docs/usdg/traffic_signal_phasing_buckholz.pdf 

Adding this functionality to `NEMALogic` will require more substantial changes than #9895

I am happy to try and tackle both this and #9895

@namdre @qichaow Thoughts?

**Comment by qichaow** [comment]
I think it's a good idea to add the phase skipping function to NEMA type controller. We can surround the break in ln 883 with
_if (isDetectorActivated(nphase))_ to do so. Could have some parameter to set the minimum recall to not skip the phase.

**Comment by qichaow** [comment]
@mschrader15 I will go ahead and add the min/max recall function to NEMA. I have a presentation to signal simulation subcommittee at TRB this weekend. It would be nice to make it more complete in the debut at TRB. Thanks for the suggestions.

**Comment by mschrader15** [comment]
Thanks @qichaow! The changes that you implemented in #9899 look great.

**Comment by mschrader15** [comment]
This is closed by #9899 and #9970
