### ISSUE TITLE
Implement path calculator between junctions

### ISSUE THREAD

**Issue by palvarezlopez** [eclipse/sumo#9901]
Continuation of #9081. Used for Trips/Flows with fromJunction/ToJunction.

Implement in GNEPathManager: calculateDijkstraPath(const SUMOVehicleClass vClass, const GNEJunction* fromJunction, const GNEJunction* toJunction) const;

**Comment by namdre** [comment]
Probably, we should add junction-taz automatically as soon as a trip/flow with fromJunction/toJunction exists automatically. This way we can use the same router as always

**Comment by namdre** [comment]
If no path exists, a straight line should be drawn. Also it might be better to prevent defining such from-to-pairs in the first place

**Comment by palvarezlopez** [comment]
"Also it might be better to prevent defining such from-to-pairs in the first place or only with ctrl+click."

Ctrl+click is reserved for moving around scenario. I would like leave it as currently, because all other frames work in the same way.
