### ISSUE TITLE
Selecting elements in the locate dialog

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#9902]
This is a follow up to #9740. I would like to have the following workflow:

- enter the first letters of an object id
- switch to the list using tab
- using cursor up / down to get to the right one
- pressing enter to center it
- bonus: press ctrl+enter to center and close the locate dialog
- alternatively: always center the selected element and remove the center button

The current dialog is almost there but has the following quirks:

- after entering the first letters I can use cursor down (or tab) to get into the list but cannot use cursor up to get into text field again
- when switching to the list it immediately highlights the first entry starting with the given letters and centers it in the view but
  - you cannot highlight a different entry in the list with cursor keys + enter
  - highlighting a different list entry with a mouse click does not center it
- the enter key does basically nothing at all when the list has focus

**Comment by namdre** [comment]
It works if you first press 'space' so that the list item gets highlighted but I guess we can improve on this.

**Comment by behrisch** [comment]
It still autocenters the first list entry when I switch to the list even if auto-center is off

**Comment by behrisch** [comment]
> Also, you can return from the list to the text field with shift+tab.

I know that, it is just the asymmetry which is bugging me. Is there an easy way to fix that or is this FOX internal?

**Comment by behrisch** [comment]
Thanks!
