### ISSUE TITLE
Could not connect to TraCI server at localhost:8813 [Errno 111] Connection refused

### ISSUE THREAD

**Issue by santiagoslopez** [eclipse/sumo#9909]
I'm asking for information with how to communicate mininet-wifi and sumo, I have a VM ubuntu 18.04.6 and both programs are running well but when I try to run an example that includes mininet-wifi and sumo (vanet-sumo.py) some problems happen with the connection with TraCI server, I don't know maybe could be my Python version or what I'm doing wrong. The file for sumo (map.sumocfg) is running well if I just open with SUMO.
 
I'm new on github and I hope someone can help me! Thank you and happy 2022

Details:
SUMO VERSION: 
![image](https://user-images.githubusercontent.com/97123585/148655569-a5608539-e03f-4d60-bb33-3d1fd79d042c.png)

PYTHON VERSION: Python 2.7.17 and Python 3.6.9
 
---
*THIS IS WHAT APPER WHEN I RUN AN EXAMPLE*
![image](https://user-images.githubusercontent.com/97123585/148655806-c16bd50e-c03f-4207-87b1-46820711b1bc.png)

**Comment by namdre** [comment]
The error `sumo-gui` not found indicates an issue with your $PATH variable. Make sure that the sumo/bin folder is in your $PATH or call sumo-gui with its full path.

**Comment by santiagoslopez** [comment]
The problem was the SUMO version I used the v1.2.0 and the minimum version is v1.12 so if I used the old version I have to open first the SUMO with the map that is configured in the python script and the run the python script, otherwise this problem will happen. 
Thanks for answer! 
Good work!
