### ISSUE TITLE
About detectors(e1, e2)

### ISSUE THREAD

**Issue by parksanha** [eclipse/sumo#9926]
Hello?

I am trying to aggregate values using the retrieval of detector(e1, e2).
https://sumo.dlr.de/docs/TraCI/Induction_Loop_Value_Retrieval.html
https://sumo.dlr.de/docs/TraCI/Lane_Area_Detector_Value_Retrieval.html

There are about 4000 detectors when simulating, which slows down the simulation a lot.
(I also use subscriptions.)
I plan to use only e1's getVehicleData, so I do not use the values automatically calculated in xml.
https://sumo.dlr.de/docs/Simulation/Output/Induction_Loops_Detectors_%28E1%29.html#generated_output

I would like to know if there is a way to not automatically output to xml. If unnecessary values are not aggregated, I think the simulation speed will be faster.

**Comment by namdre** [comment]
Heavy TraCI use will slow down any simulation so you might want to take a look at libsumo: https://sumo.dlr.de/docs/Libsumo.html

If you only wish to use e1 getVehicleData, you might instead use the XML output of instantInductionLoop: 
https://sumo.dlr.de/docs/Simulation/Output/Instantaneous_Induction_Loops_Detectors.html

**Comment by parksanha** [comment]
@namdre Thanks for the reply.
I will review the use of libsumo.

And my question was not specific.

Let me ask you a few more questions.

1. When I define a detector, the data is saved as xml even if I don't want it. I want to aggregate data using only retrieval.
Is there a way to prevent data from being saved as xml?

2. I would like to know if it is possible to aggregate sampledSeconds using e2 retrieval or something similar. After collecting data by dividing the road into very small units, I plan to aggregate several sections together.
ex) mean_speed = sum(speed * sampledSeconds) / sum(sampledSeconds)

![image](https://user-images.githubusercontent.com/62294108/149097144-6f5062ef-e568-4b57-96c0-56610051fba2.png)

thank you.

**Comment by namdre** [comment]
1. you can define `file="NUL"` to prevent output. You can also reduce the amount of data written by increasing the aggregation period to a day or more (`freq="86400"`)

2. sampledSeconds should be quite close to lanearea.getLastStepVehicleNumber() * stepLength.  If you only plan on aggregating consecutive sections of similar length, it may be easier to define long overlapping detectors that you do not need to aggregate.

**Comment by parksanha** [comment]
@namdre thank you~
