### ISSUE TITLE
Unsorted persons in vehroute output despite "--vehroute-output.sorted"

### ISSUE THREAD

**Issue by FrederikRB** [eclipse/sumo#9929]
Dear SUMO-team,

I noticed a small error in the documentation. 
On the page about sumo itself (https://sumo.dlr.de/docs/sumo.html)

It says at "--vehroute-output.sorted" that this sorts the output by the departure time. However, according to my outputs, it sorts it by arrival time, just as the tripinfo is also sorted.

SUMO-version 1.11.0.

Thank you.

**Comment by namdre** [comment]
In this case the error isn't in the documentation but rather in the code.

**Comment by FrederikRB** [comment]
I see, so both outputs (tripinfo, vehroute) are supposed to be sorted by departure time?

**Comment by namdre** [comment]
Not quite. Tripinfo is always supposed to be sorted by arrival.
Vehroute output is sorted by arrival by default, and should be sorted by departure if the option **--vehroute-output.sorted** is set.

The main reason for that option is the use case where vehroute-output is used as simulation input and this must generally be sorted by departure.

**Comment by FrederikRB** [comment]
I see, thank you.

**Comment by namdre** [comment]
@FrederikRB  can you provide example simulation inputs where **--vehroute-output.sorted** and vehicles in **vehroute-output** are *not* sorted by departure time?

**Comment by FrederikRB** [comment]
Absolutly. I attached you the inputs.
[SimulationInput.zip](https://github.com/eclipse/sumo/files/7890623/SimulationInput.zip)
y

**Comment by namdre** [comment]
I can confirm that the persons are not sorted by departure (only the vehicles are sorted correctly). Thanks for bringing this to our attention!

**Comment by FrederikRB** [comment]
You are welcome, thank you for taking care of it.

**Comment by namdre** [comment]
Persons that are stuck waiting for a vehicle can now delay vehicular vehroute output (#10281)
