### ISSUE TITLE
Add "fully actuated" operation support to NEMA 

### ISSUE THREAD

**Issue by mschrader15** [eclipse/sumo#9933]
The current NEMA implementation doesn't support "fully actuated" aka "free" mode. [Section 5.2.3 in the Traffic Signal Timing Manual](https://ops.fhwa.dot.gov/publications/fhwahop08024/chapter5.htm#5.2) describes "fully actuated" in further detail.

I would propose that we add a parameter to the TLS file for specifying NEMA mode, with the options being those in [Table 5.1](https://ops.fhwa.dot.gov/publications/fhwahop08024/chapter5.htm#5.2) + "actuated coordinated" (with current implementation does support). This should set the NEMA logic up for expansion in the future and align it with the standard terminology. 

To add the "fully actuated" mode I think the following needs to happen:

1.  The if statement below (and the one corresponding to R2) should be entered regardless of phase if the mode is "fully actuated" https://github.com/eclipse/sumo/blob/618914d720d42430c5217f11daa68a8389fa05c4/src/microsim/traffic_lights/NEMAController.cpp#L745
2. ModeCycle and any cycle length based timing decisions should be bypassed, as "fully actuated" mode does not have a cycle length.
  
As always I am more than will to take a stab at the corresponding PR. 

@qichaow let me know your thoughts!

**Comment by qichaow** [comment]
Hi Max,
The free mode can be achieved by setting coordinate-mode to false.
Thanks,
Qichao

**Comment by mschrader15** [comment]
Hi @qichaow ,

When I use the following settings:
```
        <param key="ring1" value="1,2,3,4"/>
        <param key="ring2" value="5,6,7,8"/>
        <param key="barrierPhases" value="4,8"/>
        <param key="barrier2Phases" value="2,6"/>
        <param key="show-detectors" value="true"/>
        <param key="coordinate-mode" value="false"/>
```
I still see that https://github.com/eclipse/sumo/blob/618914d720d42430c5217f11daa68a8389fa05c4/src/microsim/traffic_lights/NEMAController.cpp#L745:L758 is not entered if the R1Phase is 2.

This does not emulate "Fully-actuated" mode in a controller. As according to [Section 5.2.3 in the Traffic Signal Timing Manual](https://ops.fhwa.dot.gov/publications/fhwahop08024/chapter5.htm#5.2):

> Fully-actuated control refers to intersections for which **all phases are actuated and hence, it requires detection for all traffic movements.**

I have found that by setting 

```
        <param key="coordinatePhases" value="0,0"/>
```

in addition to the above settings, that I am able to get R1 barrier phase to enter the phase extension logic. 

Personally, I don't think this a very user-friendly UI. We could be more explicit in the combinations of parameters required for each mode of operation.

**Comment by qichaow** [comment]
You are right. I think that's a bug for free mode. Thanks for reporting it. It should be an easy fix. If you want to put your hands on it and can do the pull request today. Go ahead and do a pull request. We can have a quick meeting for it if you want. I'm working on wrapping up #9912. It would be nice if we are not working on the same code at the same time.

Qichao

**Comment by mschrader15** [comment]
Sounds good. I'll make the change locally and then handle the rebase on top of #9932 when you get the rest of it implemented. 

Can't let you have all the fun haha!

**Comment by qichaow** [comment]
Glad to hear that you enjoy contributing to this effort. :-)
