### ISSUE TITLE
Can not find SUMO actual path in Mac

### ISSUE THREAD

**Issue by harirRzi** [eclipse/sumo#9934]
Hi. I have Macbook laptop. I installed omnet++ in my Mac and sumo. For installing SUMO, I followed all the instructions in this page: https://sumo.dlr.de/docs/Installing/index.html. Now my problem is I can not set an environment variable permanently. I tried adding export SUMO_HOME=“/opt/homebrew/opt/sumo/share/sumo" in .zsh but after running echo $SUMO_HOME, the terminal doesn't display anything. I also ran the command find / -name sumo | grep share in terminal to see the actual path of SUMO and it shows me 
/opt/homebrew/Cellar/sumo/1.11.0/share/sumo
/opt/homebrew/share/sumo

when I run vein in omnet++, it shows me Could not start SUMO (/path/to/Sumo/bin/sumo-gui.exe -c erlangen.sumo.cfg): [Errno 2] No such file or directory: ‘/path/to/Sumo/bin/sumo-gui.exe. 

I think I paste the actual path wrong but I don't know how to find it. I appreciate if anyone can help me with it.
  
---
*If possible, upload an example that shows your problem.*

**SUMO-version:1.11.0**

**Macos monetrey**

**Comment by angelobanse** [comment]
1) Put the environment variable into `.zshrc` and not `.zsh`
2) You need to restart the terminal after setting the environment variable - just run `source ~/.zshrc`
3) It looks like you need to modify the `/path/to/Sumo/bin/sumo-gui.exe -c erlangen.sumo.cfg` call and use the appropriate path to your sumo-gui executable

**Comment by angelobanse** [comment]
if you also run `brew info sumo`, you can see in the "Caveats" section (at the bottom) the exact path to sumo

**Comment by harirRzi** [comment]
Thank you for your reply. I could set the environment variable like what you suggested and after running echo $SUMO_HOME, it shows me /opt/homebrew/opt/sumo/share/sumo. But when I run vein, it shows me again the error: Could not start SUMO (/path/to/Sumo/bin/sumo-gui.exe -c erlangen.sumo.cfg): [Errno 2] No such file or directory: ‘/path/to/Sumo/bin/sumo-gui.exe.       Then I ran brew info sumo-gui ignorer to find its path and set it as the environment if I understood your suggestion correctly but when I run brew info sumo-gui, it shows me following: ==> Caveats
Before running the apps, please verify that your SUMO_HOME environment variable is set correctly.

sumo-gui is not signed and requires Accessibility access,
so you will need to re-grant Accessibility access every time the app is updated.

Enable or re-enable it in:
  System Preferences → Security & Privacy → Privacy → Accessibility
To re-enable, untick and retick sumo-gui.app.           I did correctly give access to the application in system preferences, I ticked the app but again when I run the above mentioned command it shows me the same information.

**Comment by harirRzi** [comment]
When I list the contents of sumo/bin in terminal, I can see sumo-gui in the list, so I used downloads/veins-master/sumo-launchd.py -vv -c /hrz/sumo/bin/sumo-gui.exe but still in the terminal I get the error Errno 2] No such file or directory: /hrz/sumo/bin/sumo-gui.exe

**Comment by behrisch** [comment]
Since you are on mac I think there should be no .exe suffix

**Comment by harirRzi** [comment]
Thank you for your answer. I omit .exe as well and wrote the following like you mentioned: downloads/veins-master/sumo-launchd.py -vv -c /hrz/sumo/bin/sumo-gui but it still shows the same error. Also I wrote downloads/veins-master/sumo-launchd.py -vv -c Users/hrz/sumo/bin/sumo-gui, it also has the same error. I write clicked on the sumo-gui application icon and clicked on getInfo, I could see in front of where part the following information: Macintosh HD> Users> hrz> sumo> bin. I appreciate if anyone can suggest me how can I fix it.

**Comment by harirRzi** [comment]
In the command line I can see the following error: 	<status>Could not start SUMO (Users/hrz/sumo/bin/sumo-gui -c erlangen.sumo.cfg): [Errno 2] No such file or directory: '/hrz/sumo/bin/sumo-gui'</status>

**Comment by harirRzi** [comment]
This is what I see in the command line:

Listening on port 9999
Connection from 127.0.0.1 on port 62474
Handling connection from 127.0.0.1 on port 62474
Got TraCI message of length 2
Got TraCI command of length 1
Got TraCI command 0x0
Got CMD_GETVERSION
Got TraCI message of length 307
Got TraCI command of length 302
Got TraCI command 0x75
Got CMD_FILE_SEND for "b'sumo-launchd.launch.xml'"
Got CMD_FILE_SEND with data "b'<launch>\n  <copy file="erlangen.net.xml"/>\n  <copy file="erlangen.rou.xml"/>\n  <copy file="erlangen.poly.xml"/>\n  <copy file="erlangen.sumo.cfg" type="config"/>\n  <basedir path="/Users/hrz/Downloads/veins-master/examples/veins/"/>\n  <seed value="0"/>\n</launch>\n'"
Creating temporary directory...
Temporary dir is /var/folders/ss/_3stplfj063cqkd70rr3rsdh0000gn/T/sumo-launchd-tmp-95pq92h1
Base dir is /Users/hrz/Downloads/veins-master/examples/veins/
Seed is 0
Finding free port number...
Claiming lock on port
...found port 62475
Starting SUMO (Users/hrz/sumo/bin/sumo-gui -c erlangen.sumo.cfg) on port 62475, seed 0
Releasing lock on port
Cleaning up
Result: "<?xml version="1.0"?>
<status>
	<exit-code>-1</exit-code>
	<start>1642633033</start>
	<end>1642633033</end>
	<status>Could not start SUMO (Users/hrz/sumo/bin/sumo-gui -c erlangen.sumo.cfg): [Errno 2] No such file or directory: 'Users/hrz/sumo/bin/sumo-gui'</status>
	<stdout><![CDATA[]]></stdout>
	<stderr><![CDATA[]]></stderr>
</status>
"
Closing connection from 127.0.0.1 on port 62474

**Comment by namdre** [comment]
continued in #10129
