### ISSUE TITLE
NEMA should have "Rest in Green" functionality when not in coordinated mode

### ISSUE THREAD

**Issue by mschrader15** [eclipse/sumo#9937]
@qichaow current state of NEMA doesn't rest in phases with recalls when in "free" operation. 

Expected behavior is that the recall phases will stay green when no other vehicle calls are placed.  If there are multiple recall phases, the controller should cycle between the two until a detector call is placed on a non-recall phase.

The current operation is (if 2 & 6 have a soft recall) 2 & 6 green -> 2 & 6 gap out -> yellow -> red -> 2 & 6 green

It should be 2 & 6 green -> 2 & 6 gap out -> 2 & 6 green rest
  
I will attempt to tackle this too. The change will be more substantial than #9933

**Comment by qichaow** [comment]
It's probably good to have a meeting for it. I did it the way intentionally for the time being before moving to another step on it. The current feature capture most of the cases for free mode (note that the green for 2&6 should extend when a vehicle come). The next step should be general enough to be able to support other features (e.g., overlap).

**Comment by qichaow** [comment]
@mschrader15 Now I think about it, adding one line or two could probably solve it.

**Comment by mschrader15** [comment]
@qichaow I had a simple solution worked out as well, though I don't know that it would be the ultimate best solution considering the generality that you reference https://github.com/eclipse/sumo/issues/9937#issuecomment-1012345780

I will create a commit in our fork (https://github.com/UnivOfAlabama-BittleResearchGroup/sumo) and ask you for review before opening a PR to solve this issue.

I think that a meeting is a good idea as well. I will suggest to Dr. Bittle and maybe we can get @namdre as well again. 

Just FYI, we have a SIL Econolite controller with SUMO that I am currently validating against.

**Comment by mschrader15** [comment]
Adding a note to also include Green XFER in this logic

Expected behavior of Green Xfer is (for example): 

1. In [3, 7]
2. Pass minimum timer on [3, 7]
3. Detector call on [3]. [7] goes into Grn XFER
4. Detector call on [8]. [7] enters transition immediately, [3] stays until extension timer exhausted

Current behavior is:

1. In [3, 7]
2. Pass minimum timer on [3, 7]
3. Detector call on [3]. [7] moves to [8] immediately
4. [3] stays until extension timer exhausted, then goes to [4]

**Comment by mschrader15** [comment]
Rest in green should bypass yellow transition if going from rest in [2, 6] to [1, 6] for example. Current idea for implementation depends on #9940
