### ISSUE TITLE
NEMA crossing ring barrier dangerously (serves crossing traffic together)

### ISSUE THREAD

**Issue by mschrader15** [eclipse/sumo#9940]
@qichaow I was doing testing on a 4-way intersection and caught an undesirable barrier crossing.

The command line output looks like:

```
current time in cycle:  43.00   phases: 2       6
phase 3 was skipped
phase 4 was skipped
phase 1 was skipped
phase 7 was skipped
current time in cycle:  44.00   phases: 2       8
current time in cycle:  45.00   phases: 2       8
current time in cycle:  46.00   phases: 2       8
```

It appears to get caught in this error state and then never exiting. I have created a reproduce-able test case here: https://github.com/UnivOfAlabama-BittleResearchGroup/sumo/tree/4way-error/tests/sumo/basic/tls/NEMA/errors/4way_error

It maybe that I have some failing case of parameters, but I think the issue lies in the fact that `NEMALogic::nextPhase` can go all the way around the ring on the top ring `2->3->4->1->2` and in the same call to `NEMALogic::NEMA_Control`, R2 goes from `6 -> 7 -> 8`.

I have some ideas to fix this, but figured that I would hold off until you investigated @qichaow  

Let me know if you have questions & we can discuss further in the meeting tomorrow AM

**Comment by namdre** [comment]
@mschrader15 Thanks for the test case! I've taken the liberty to putting it directly into main.

**Comment by mschrader15** [comment]
No problem!

**Comment by qichaow** [comment]
@mschrader15 I can see this happening with the minRecall function. I usually imagine minRecall on 2 &6 but the scenario you mentioned could happen. We should check the other ring and not cross barrier when do next phase. If you want to work on it, go ahead and do it. I can review it in your fork if you want. I can cover that if you don't have the time to do it now.

I appreciate your enthusiasm in this work. Keep it up.

**Comment by mschrader15** [comment]
@qichaow I have implemented my solution on https://github.com/UnivOfAlabama-BittleResearchGroup/sumo/tree/4way-fix with commit. I also created a pull request #9953, with the purpose of making the changes more visible.

The main addition that I have added to the code is https://github.com/UnivOfAlabama-BittleResearchGroup/sumo/blob/101f6d62752dbab804bcdcd13da5410cea3887dc/src/microsim/traffic_lights/NEMAController.cpp#L1036 , which makes a decision on the next phase with knowledge of whether the other ring is ready to also change state and which "barrier" the other ring is on. 

There are several substantial-ish changes to the structure, but they make the code more extensible IMO.

Let me know if you have questions. This implementation passes all tests in NEMA test folder from my understanding of how to use texttest 😆

**Comment by qichaow** [comment]
Hi Max,

I'm a bit lost to find your code that reflects all the changes. It seems that you have several active branches. Which branch should I look into?

Thanks,
Qichao

**Comment by mschrader15** [comment]
@qichaow Here is the branch with the fix: https://github.com/UnivOfAlabama-BittleResearchGroup/sumo/tree/4way-fix

I opened a PR for it here: #9953

**Comment by qichaow** [comment]
@mschrader15 I read your code but haven't run to test it. 
Nice work. I would do it differently but your version is probably easier to read. It's probably good to have another person (that's you :-)) to read/write the code to keep the code easy to ready. I will talk with you more in the call.

**Comment by mschrader15** [comment]
This is closed by #9970

**Comment by mschrader15** [comment]
@qichaow @namdre  Below are phase trackers for comparing an Econolite controller SIL with SUMO vs. using the native NEMA controller. They are both running "free" with identical (or as close as possible) configurations. Besides one or two minor differences, the results are super promising! 

The main difference is the 33 second 2+6 phase in SUMO vs the 25 second 2+6 in the SIL. I suspect that this is due to the my SIL implementation and the traci call order, and not an issue with the NEMA. Other minor differences exist as well, but again I think it comes down to timing differences in the SIL controller and the order in which I step it / interact with SUMO.

**Econolite Controller SIL**

![image](https://user-images.githubusercontent.com/57813331/150013531-ca9d680c-bd2d-49c6-9c59-833ab869a228.png)

**Native NEMA**

![image](https://user-images.githubusercontent.com/57813331/150013825-7d81b514-dcb8-4d98-9107-c653d4105d4f.png)

There are no immediate action items out of this, just wanted to share!

**Comment by namdre** [comment]
:partying_face:

**Comment by qichaow** [comment]
Great!

Qichao
