### ISSUE TITLE
Meaningless separation appears in the internal lane.

### ISSUE THREAD

**Issue by parksanha** [eclipse/sumo#9941]
Hello. sumo-team.

I've seen meaningless separation in internal lanes.

![image](https://user-images.githubusercontent.com/62294108/149463327-cea2c2fc-e015-452f-a3f5-d96525c14eb7.png)
![image](https://user-images.githubusercontent.com/62294108/149464177-3df931bd-de6a-405e-947b-47de8c5dad69.png)

I am not sure why the separation of internal_lane like the picture below occurs.
I tried traci.trafficlight.getControlledLinks('215173'), but lane :215173_33_0 could not be found.

I would like to know how to make it into one internal lane.

thank you.

**Comment by namdre** [comment]
Most likely, the default signal plan for this crossing contains a phase with permissive left green. Such a phase allows left-turning vehicles to wait within the intersection and the separation marks that waiting spot.
To disable this feature set connection attribute 'contPos=0'.

**Comment by parksanha** [comment]
@namdre 

Thank you very much for your help. ^^
