### ISSUE TITLE
Are there existing networks for benchmarks and baselines.

### ISSUE THREAD

**Issue by Oritchimaru** [eclipse/sumo#9943]
I'm working on different platforms and SUMO versions so I didn't fill the gaps below but the question is independent of these.

I'm working on some Machine Learning algorithms and besides importing from OSM Wizard is there any already existing network (+ traffic !?) that people use for comparison or just to conduct their methods to?

For example I've made an algorithm that approaches a driving policy which achieves 0 collisions in unsignaled networks, starting from random actions. Is there any indicated network that should I test it on...? What networks do people that use SUMO for publications use and test at ?

Let's hope I clearly stated my concerns!

**Comment by Oritchimaru** [comment]
I'm aware of lump, Bologna etc. but these are enormous networks! All I need is a smaller network with the .net.xml and trips.xml files... (architecture and traffic)

**Comment by Oritchimaru** [comment]
@namdre I think this network would be fine but my problem with acosta (Bologna generally) is that the names of the roads/lanes are very hard to interpret. I'm used to X_Y (X = road number, Y = lane number) and respectively for junctions. Bologna uses [] double [] and names, it's hard to code around it.

**Comment by namdre** [comment]
Here is what you can do to convert the ids to purely numerical:
1. load the network in netedit
2. load the vehicles in netedit
3. check option 'numerical ids' in the Processing tab of the options dialog (F10)
4. save network
5. save demand

However, there are two problems you must work around
- netedit doesn't fully support vType distributions yet so loading the acosta routes will fail. A quick fix is to add the line `<vType id="private"/>` to the vehicle route file. (#9946)
- netedit has problems when saving loaded stops in the correct order (#9947). A quick fix is to only work with the passenger car traffic and ignore the busses

**Comment by Oritchimaru** [comment]
Thanks alot namdre thats really helpful, I can use the routine I can make a subnet now with netedit and then use the tripcutter to make new trips with arithmetic edges. Thanks!
