### ISSUE TITLE
randomTrips.py question about fringe_factor

### ISSUE THREAD

**Issue by Oritchimaru** [eclipse/sumo#9948]
### I'm generating some traffic using randomTrips.py on an imported network from OSMWizard.

**Problem:** although I'm using a incredibly high fringe factor (let's say 20000) I have vehicles spawn into random junctions inside the network. While the desired behavior is to have vehicles spawn to internal cropped lanes and finish at external cropped lanes. This makes a learning algorithm fail completely so I wish I could totally eliminate this possibility.

The rest of the parameters don't have much impact to be mentioned, I spawn a vehicle once about every 4 seconds. Did I make a mistake? Is there any solution or maybe a netedit hotfix by hand? What would you do?

_(Sorry for making consecutive questions)_

**EDIT** I meant facing inwards and outwards when I said internal and external.

**Comment by namdre** [comment]
The first thing to check is whether the internal junctions are wrongly classified as fringe. You can export the per-edge probabilities with option **--weights-output-prefix** and then look into the generated .src.xml to check the values of the undesired trip origins.

**Comment by Oritchimaru** [comment]
> The first thing to check is whether the internal junctions are wrongly classified as fringe. You can export the per-edge probabilities with option **--weights-output-prefix** and then look into the generated .src.xml to check the values of the undesired trip origins.

so should I add this **"--weights-output-prefix"** into the randomTrip.py command?

**Comment by Oritchimaru** [comment]
@namdre 
**So my command was this:**

`python3 /home/kblekas/sumo/tools/randomTrips.py -n osm.net.xml -b 0 -e 1800 -p 4 --trip-attributes="departLane=\"best\" departSpeed=\"10.0\" departPos=\"base\"" --route-file trips.xml --fringe-factor 20000 --weights-output-prefix probabilities`

**The probability weight file produced is this. It has some more _0,1_ values and the rest are _0_**

![image](https://user-images.githubusercontent.com/26443186/149518926-2dbce006-db99-4d71-bca4-4ed229718ecb.png)

**Comment by Oritchimaru** [comment]
For example let's look at this junction. This is a junction that I get undesired spawns.

![image](https://user-images.githubusercontent.com/26443186/149519816-fe61e7af-df1e-4bf9-b637-599ed2c15417.png)

Right clicking on that junction gives:

**junction:300398465**

Now let's search for this junction in the net file.

![image](https://user-images.githubusercontent.com/26443186/149519962-bc76d837-9ba6-43a1-9ebd-64f8a3bd4ea7.png)

(also appears in the "from" section of 2 other edges)

![image](https://user-images.githubusercontent.com/26443186/149520110-26c109ad-3262-4f92-a540-10ed857be70e.png)

One of those 2 edges appear on the .src probability file with 100% chance.

This is a clue right?

**Comment by namdre** [comment]
@Oritchimaru  After setting fringe information in your network, you can use randomTrips option **--fringe-junctions** to make use of it.

To obtain the new version you could simply update all the files modified in f5e32d4 or download the latest development version of sumo tomorrow at https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_development_version
