### ISSUE TITLE
allow tracking detector states for NEMA in phase tracker window

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#9952]

**Comment by namdre** [comment]
@qichaow @mschrader15 enjoy! (also, see https://sumo.dlr.de/docs/Simulation/Traffic_Lights.html#track_phases)

**Comment by mschrader15** [comment]
This is awesome @namdre! It will save a lot of post-processing time during validation.

**Comment by namdre** [comment]
@mschrader15 I also invite you to consider whether you see use cases for adapting this to NEMA: https://sumo.dlr.de/docs/Simulation/Traffic_Lights.html#custom_switching_rules
