### ISSUE TITLE
NEMA should support Green Transfer

### ISSUE THREAD

**Issue by mschrader15** [eclipse/sumo#9954]
Expected behavior of Green transfer is (for example): 

1. In [3, 7]
2. Pass minimum timer on [3, 7]
3. Detector call on [3]. [7] goes into Grn XFER
4. Detector call on [8]. [7] enters transition immediately, [3] stays until extension timer exhausted

Current behavior is:

1. In [3, 7]
2. Pass minimum timer on [3, 7]
3. Detector call on [3]. [7] moves to [8] immediately
4. [3] stays until extension timer exhausted, then goes to [4]

The implementation will have to be outside of the nextPhase logic, as the timing will need to be adjusted. 

This is very similar to Rest in Green in #9937

_Originally posted by @mschrader15 in https://github.com/eclipse/sumo/issues/9937#issuecomment-1013740306_

**Comment by namdre** [comment]
This is closed in #9970, right?
