### ISSUE TITLE
The bicycle lateral alignment procedure should be "right" by default

### ISSUE THREAD

**Issue by alexpagri** [eclipse/sumo#9959]
Me and @Ludatan are working on improving the default bicycle model, on behalf of the SimRa data analysis team at TU Berlin.

**Comment by namdre** [comment]
excellent point

**Comment by namdre** [comment]
Code changes and Test changes should come as separate pull requests. Have you already done the Eclipse paperwork (https://sumo.dlr.de/docs/FAQ.html#how_do_code_contributions_work) ?

**Comment by alexpagri** [comment]
Yes. I've checked the paper and signed it online.
https://accounts.eclipse.org/users/alexpagri

**Comment by alexpagri** [comment]
For the tests, which is the approach?

1. Update the bike's lateral alignment procedure to "center" (old value).
2. Update the test's output to match the new implementation.
3. Update the bike's lateral alignment procedure to "center" (old value) and copy-paste the old tests but update the new outputs to match the new implementation.

**Comment by behrisch** [comment]
we will merge it after the 1.12 release

**Comment by namdre** [comment]
@alexpagri Probably a mix of these 3 approaches, depending on whether the lateral alignment is instrumental for the situation under test. I'll have a look at the test myself but this will most likely have to wait until the release next week.
