### ISSUE TITLE
can't see osmWebWizard simulation in sumo-gui

### ISSUE THREAD

**Issue by harirRzi** [eclipse/sumo#9967]
Hi. I'm trying to osmWebWizard simulated scenario in sumo-gui.
I ran the following command python osmWebWizard.py to simulate a scenario.I selected a rather small area and hit the "Generate scenario" button. In the console of osm.sumocfg, I can see Loading done but I just see a black screen. I then hit the open simulation icon, and selected the osm.sumocfg file then clicked "ok" but again I see in the console loading done while I just see a black screen. I don't know why I can not see the simulation while there isn't also any error in the console. I even passed the play button, the time starts incrementing but there is still a black screen. I appreciate if anyone can suggest me a solution for this.

  
<img width="1440" alt="Screen Shot 2022-01-17 at 3 07 29 PM" src="https://user-images.githubusercontent.com/97624131/149837162-fa863de5-9601-4303-8baa-813b7836320c.png">

---
*If possible, upload an example that shows your problem.*

**SUMO-1.11.0*

**Mac OS Monterey**

**Comment by namdre** [comment]
please look into #7830 (add comments there if you need help)
