### ISSUE TITLE
sumo-gui hangs after error

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#9973]
often visible in tests/sumo/pedestrian_model/nonInteracting/errors/disconnected_trip with the windows debug build. Unfortunately not deterministic. There are also similar failures in the standard Linux tests so it is probably not windows and not debug specific.

**Comment by namdre** [comment]
could we disable the timeout for this test for a few days to keep this test open and catch it in a debugger?

**Comment by behrisch** [comment]
I already found the reason.
