### ISSUE TITLE
marouter + CH = does not yield any alternative routes

### ISSUE THREAD

**Issue by ambuehll** [eclipse/sumo#9981]
when using marouter and CH as a router, it does not yield more than 1 route ever, even though `max-alternatives >1` and `path >1` and `keep-all-routes true` . When running marouter with astar, multiple routes per taz relation are found (including probabilities)
I can offer an example, when necessary. 
Probably related to #9803

Thanks, 
Lukas

**Comment by behrisch** [comment]
This is unforunatelky an inherenbt property of the contraction hierarchies router that is cannot deal with the dynamic edge lengths the k shortest path search is using. I added a warning. It is probably unrelated to #9803 though
